### ISSUE TITLE
TypeScript language service dies when denoland.Deno extension enabled in a React/TypeScript app

### ISSUE THREAD

**Issue by zeljkoantich** [microsoft/vscode#100275]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1. Create app with package.json with this dependencies:
```json
  "devDependencies": {
    "@types/react": "^16.9.36",
    "@types/react-dom": "^16.9.8",
    "source-map-loader": "^1.0.0",
    "ts-loader": "^7.0.5",
    "typescript": "^3.9.5",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
```
2. Create and open a tsx file. Example: `src/App.tsx`
3. After that TypeScript language service dies with this pop-up message
```
The TypeScript language service died 5 times right after it got started. The service will not be restarted.
```
**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99888:161)
    at resolveModuleNamesWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100106:26)
    at resolveModuleNamesReusingOldState (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100255:19)
    at processImportedModules (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101668:35)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101411:17)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:60
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:16)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138726:26)
    at Proxy.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138818:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143310:53)
    at ConfiguredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143253:42)
    at ConfiguredProject.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144047:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145700:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146581:44)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:97
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147763:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.27GB (16.92GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
markdown-toc|Ala|1.5.6
ng-template|Ang|0.901.11
markdown-mermaid|bie|1.5.1
vscode-fish|bma|1.0.16
markdown-table-prettify|dar|2.4.0
vscode-eslint|dba|2.1.5
vscode-deno|den|1.25.0
githistory|don|0.6.5
gitlens|eam|10.2.2
html-slim-scss-css-class-completion|gen|1.7.5
vscode-angular-html|gha|1.7.0
rest-client|hum|0.24.1
vscode-peacock|joh|3.7.2
vscode-styled-components|jpo|0.0.29
git-graph|mhu|1.24.0
vscode-docker|ms-|1.3.0
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
quicktype|qui|12.0.46
vscode-yaml|red|0.8.0
code-spell-checker|str|1.9.0
vscode-todo-highlight|way|1.0.4
markdown-pdf|yza|1.4.4

</details>

**Comment by zeljkoantich** [comment]
After disabling vscode-deno extension TypeScript language service works.
