### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 1 === 2. Registered script kind should match new script kind.

### ISSUE THREAD

**Issue by pavlvs** [microsoft/vscode#100240]
**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. Expected 1 === 2. Registered script kind should match new script kind.
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138803:34)
    at tryReuseStructureFromOldProgram (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100366:28)
    at Object.createProgram (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99949:30)
    at synchronizeHostData (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138726:26)
    at Proxy.getProgram (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138818:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143310:53)
    at InferredProject.Project.updateGraph (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143253:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145149:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146643:26)
    at c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:97
    at Object.flatMap (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147763:46)
    at c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Users\PavlvsX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue

**Comment by pavlvs** [comment]
It happened after I changed the language on a yet unsaved  file from Javascript React to Babel Javascript.

**Comment by embarq** [comment]
Same here

In order to not to make duplicate issue I'll post my report here:

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. Expected 4 === 3. Registered script kind should match new script kind.
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:138830:34)
    at tryReuseStructureFromOldProgram (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:100393:28)
    at Object.createProgram (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:99976:30)
    at synchronizeHostData (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:138753:26)
    at Proxy.getProgram (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:138845:13)
    at InferredProject.Project.updateGraphWorker (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:143337:53)
    at InferredProject.Project.updateGraph (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:143280:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:145176:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:146670:26)
    at /home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:146927:97
    at Object.flatMap (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:147790:46)
    at /home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:149544:28)
    at IOSession.Session.executeCommand (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:149553:33)
    at IOSession.Session.onMessage (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:149577:35)
    at Interface.<anonymous> (/home/embarq.dev/.vscode-server-insiders/bin/e95f9e63380a139cb1cbe54bacfc6703b96e30b9/extensions/node_modules/typescript/lib/tsserver.js:150893:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.47.0-insider (e95f9e63380a139cb1cbe54bacfc6703b96e30b9, 2020-07-07T07:46:45.605Z)
OS version: Darwin x64 16.7.0
Remote OS version: Linux x64 4.19.0-9-cloud-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-cloud|
|OS|Linux x64 4.19.0-9-cloud-amd64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.00GHz (1 x 2000)|
|Memory (System)|2.44GB (0.71GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
mermaid-markdown-syntax-highlighting|bpr|1.0.3
vscode-angular-html|gha|1.7.0
remote-containers|ms-|0.127.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
sublime-keybindings|ms-|4.0.7
material-icon-theme|PKi|4.2.0
vscode-todo-highlight|way|1.0.4
EditorConfig|Edi|0.15.1
fontsize-shortcuts|fos|1.5.0
json-to-ts|Mar|1.7.5
polacode|pnp|0.3.4
multi-command|ryu|1.4.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>
