### ISSUE TITLE
VSCode immediately closes on first start after clean install (partial workaround with logs)

### ISSUE THREAD

**Issue by jossjacobo** [microsoft/vscode#100334]
- VSCode Version: 1.46.0
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:

1. Followed these [blog post steps](https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec) to do a clean uninstall of VSCode
2. Download latest version from website
3. Unzip and move to `/Applications` folder
4. Right-click and click on `open`
5. Click Open
- <img width="503" alt="Screen Shot 2020-06-16 at 2 19 07 PM" src="https://user-images.githubusercontent.com/945111/84832076-6da12080-afe1-11ea-9689-4fa98c137c4f.png">
6. VSCode icon would pop up briefly on the dock and immediately close

Does this issue occur when all extensions are disabled?: **Yes**

**Workaround/"Fix"**
After running `$ code --verbose` I noticed a 
```
Unexpected error validating window state:
``` 
and 
```
[main 2020-06-16T21:22:24.347Z] TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:579:21)
``` 
errors, which got me thinking I was always starting vscode on my secondary monitor. Moved to my primary laptop monitor and opened up with `cmd + space -> vscode -> enter` and it started up no problem, been working fine ever since.

Debugging with disabled extensions and gpu
```
$ code --disable-extensions --disable-gpu -w --verbose
Marker file for --wait created: /var/folders/qw/p15rvbr571n9gxvg2m1mddtr0000gp/T/dgiaiul
```

Debugging with only verbose
```
$ code --verbose    
[main 2020-06-16T21:22:24.266Z] Starting VS Code
[main 2020-06-16T21:22:24.268Z] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 2020-06-16T21:22:24.268Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false
}
[main 2020-06-16T21:22:24.270Z] Resolving machine identifier...
[main 2020-06-16T21:22:24.270Z] Resolved machine identifier: 2e880a2064114d3e95540fbe40159595ce1ac0a36863766a7579716d105de5c2 (trueMachineId: undefined)
[main 2020-06-16T21:22:24.297Z] [storage state.vscdb] open(/Users/j0j0471/Library/Application Support/Code/User/globalStorage/state.vscdb, retryOnBusy: true)
[main 2020-06-16T21:22:24.298Z] lifecycle (main): phase changed (value: 2)
[main 2020-06-16T21:22:24.299Z] windowsManager#open
[main 2020-06-16T21:22:24.305Z] window#validateWindowState: validating window state on 2 display(s) {
  width: 1024,
  height: 768,
  mode: 1,
  x: 2768,
  y: -0,
  hasDefaultState: true
}
[main 2020-06-16T21:22:24.308Z] Unexpected error validating window state: TypeError: Error processing argument at index 0, conversion failure from #<Object>
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at Object.module.<computed> [as getDisplayMatching] (electron/js2c/browser_init.js:6954:38)
    at r.validateWindowState (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:519:91)
    at restoreWindowState (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:517:727)
    at new r (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:505:861)
    at u._createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:287:255)
    at u.createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:286:683)
    at t.openInBrowserWindow (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:576:38)
    at t.doOpenEmpty (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:567:97)
    at t.doOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:566:564)
    at t.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:562:495)
    at t.openFirstWindow (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:596:412)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:588:847
    at u.invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:286:212)
    at t.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:588:824)
    at async Object.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:602:367)
[main 2020-06-16T21:22:24.308Z] window#ctor: using window state {
  width: 1024,
  height: 768,
  mode: 1,
  x: 2768,
  y: -0,
  hasDefaultState: true
}
[main 2020-06-16T21:22:24.346Z] telemetry/optInStatus { optIn: true }
[main 2020-06-16T21:22:24.346Z] telemetry/machineIdFallback { usingFallbackGuid: false }
[main 2020-06-16T21:22:24.347Z] TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:579:21)
    at new r (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:507:531)
    at u._createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:287:255)
    at u.createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:286:683)
    at t.openInBrowserWindow (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:576:38)
    at t.doOpenEmpty (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:567:97)
    at t.doOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:566:564)
    at t.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:562:495)
    at t.openFirstWindow (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:596:412)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:588:847
    at u.invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:286:212)
    at t.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:588:824)
    at async Object.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:602:367)
[main 2020-06-16T21:22:24.347Z] Lifecycle#kill()
[main 2020-06-16T21:22:24.347Z] Lifecycle#app.on(window-all-closed)
[main 2020-06-16T21:22:24.426Z] [storage state.vscdb] Trace (event): PRAGMA user_version = 1;
```

**Comment by jossjacobo** [comment]
Actually it seems to still not be quite working correctly, if a second window is open on the secondary monitor it'll just be blank.

<img width="1034" alt="Screen Shot 2020-06-16 at 3 03 46 PM" src="https://user-images.githubusercontent.com/945111/84832759-b60d0e00-afe2-11ea-89f8-170fad0c3068.png">

```
➜ code . --verbose
[main 2020-06-16T22:03:39.102Z] Sending env to running instance...
[main 2020-06-16T22:03:39.118Z] [
  'TypeError: Error processing argument at index 0, conversion failure from #<Object>',
  '    at BrowserWindow.setBounds (electron/js2c/browser_init.js:579:21)',
  '    at new r (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:507:531)',
  '    at u._createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:287:255)',
  '    at u.createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:286:683)',
  '    at t.openInBrowserWindow (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:576:38)',
  '    at t.doOpenFolderOrWorkspace (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:567:417)',
  '    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:566:14',
  '    at Array.forEach (<anonymous>)',
  '    at t.doOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:565:841)',
  '    at t.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:562:495)',
  '    at e.startOpenWindow (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:524:610)',
  '    at e.start (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:524:215)',
  '    at Object.call (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:194:81)',
  '    at E.onPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:186:441)',
  '    at E.onRawMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:186:70)',
  '    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:185:591',
  '    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:52:801)',
  '    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:199:77',
  '    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:52:801)',
  '    at f.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:197:737)',
  '    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:197:89',
  '    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:207:22)',
  '    at Socket.emit (events.js:203:13)',
  '    at addChunk (_stream_readable.js:295:12)',
  '    at readableAddChunk (_stream_readable.js:276:11)',
  '    at Socket.Readable.push (_stream_readable.js:210:10)',
  '    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)'
]
[main 2020-06-16T22:03:39.119Z] Lifecycle#kill()
```

**Comment by Sara1991908** [comment]
https://code.visualstudio.com/updates/v1_44 
download the oldest version will solve this problem 
![image](https://user-images.githubusercontent.com/12132075/84881821-f773eb00-b0c0-11ea-8d2a-8c02e45c87ce.png)
I choosed the March version to deal with it

**Comment by jossjacobo** [comment]
@Sara1991908 thanks! Rolling back to 1.44 made the issue go away

**Comment by bpasero** [comment]
Need to check if we have to defend ourselves from bad values of the window state, but that can only happen if someone else wrote into the `storage.json` file...

**Comment by bpasero** [comment]
@deepak1556 I find this way of throwing not very pleasant and possibly something electron should change. E.g. I notice that when I pass in a very large number to one of the dimensions, I get this runtime exception. What is the story behind it?

**Comment by deepak1556** [comment]
@bpasero the backing container [gfx::Rect](https://source.chromium.org/chromium/chromium/src/+/master:ui/gfx/geometry/rect.h) for screen coordinates only accepts int arguments, hence electron threw an error instead of transforming it into a garbage value that would lead to undefined behaviors.

**Comment by bpasero** [comment]
@deepak1556 well this is coming from persisted state that maybe got tampered with outside of our control, so it can really have any value. I am already checking for the type being number, but was not expecting an error when the number is simply large.

**Comment by deepak1556** [comment]
The current solution should be fine, If needed we can check if the persisted value is a 32-bit integer specifically (parseInt(pos, 10) | 0 === pos)
