### ISSUE TITLE
Notebook Integration test failure

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#100461]
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=79089&view=logs&j=935a53e5-ce00-51d1-185d-b2f737723cea&t=78251e6f-ceae-58b8-b69e-6d3a7d24b6bc

```
 1) notebook undo redo execute and then undo redo:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-notebook-tests\out\notebook.test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  2) notebook working copy multiple tabs: dirty + clean:
     TypeError: Cannot read property 'selection' of undefined
      at Context.<anonymous> (extensions\vscode-notebook-tests\src\notebook.test.ts:683:54)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by rebornix** [comment]
Disabled it temporarily and see if it still reproduces after we moving to native undo/redo commands.

**Comment by joaomoreno** [comment]
Linux: https://dev.azure.com/vscode/VSCode/_build/results?buildId=47912&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d2c76452-9b5b-53aa-b9e7-4eac61843d9f

**Comment by rebornix** [comment]
Not seeing relevant failures anymore.
