### ISSUE TITLE
Loading webview fails: Could not rewrite csp

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#100442]
For Visual Studio Codespaces we load a webview that holds the creation process information right after connecting to a Codespace, but the loading seems to be failing under VS Code insiders latest commit.

- VSCode Version: 1.47.0-insider
-Commit: 84f52fe1c0124307046ac0f5443493cda946e60f
- OS Version: Debian GNU/Linux

Steps to Reproduce:

1. Open online.visualstudio.com
2. Create and connect to a Codespace
3. The Creation Log tries to open a webview but fails to load the resource with the following error

![image](https://user-images.githubusercontent.com/48293249/84969169-fea0f600-b0cc-11ea-9bd2-cd93103e03af.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Just checked and the markdown preview (also webview based) seems like it works. Is there a way to trigger the creation log view after you've already connected so that I can easily test this? Also, do I need to be on ppe?

The CSP error should be non-fatal but it could cause some code not to be loaded.

**Comment by osortega** [comment]
@mjbvz You might need to change your settings under Codespaces portal to insiders channel.
You also can load the webview after connecting to a Codespace by right-clicking on the environment in the tree view and select View Creation Log. You could also execute the command directly from the command palette.

**Comment by mjbvz** [comment]
Thanks. I think the csp problem is a red herring. The reason the content can't load seems to be:

```
ENOPRO: No file system provider found for resource 'file:///home/vsonline/.vscode-remote/extensions/ms-vsonline.vsonline-1.0.2361/out/bundle/splash-bundle.js'
    at b.withProvider (https://online-ppe.core.vsengsaas.visualstudio.com/workbench-page/web-standalone/insider-84f52fe/out/vs/workbench/workbench.web.api.js:1630:299)
    at async b.withReadProvider (https://online-ppe.core.vsengsaas.visualstudio.com/workbench-page/web-standalone/insider-84f52fe/out/vs/workbench/workbench.web.api.js:1630:418)
    at async b.readFile (https://online-ppe.core.vsengsaas.visualstudio.com/workbench-page/web-standalone/insider-84f52fe/out/vs/workbench/workbench.web.api.js:1634:405)
    at async Object.t.loadLocalResource (https://online-ppe.core.vsengsaas.visualstudio.com/workbench-page/web-standalone/insider-84f52fe/out/vs/workbench/workbench.web.api.js:2791:625)
    at async f.loadResource (https://online-ppe.core.vsengsaas.visualstudio.com/workbench-page/web-standalone/insider-84f52fe/out/vs/workbench/workbench.web.api.js:3820:781)
splash-bundle.js:1 Failed to load resource: the server responded with a status of 404 ()
splash-bundle.js:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by mjbvz** [comment]
I think 35c339382828c093a0e562d10d248cb65e5f1188 should fix this but I cannot test in VSO. @osortega Can you please pick up the latest VS code bits from master and see if it fixes the problem?

**Comment by mjbvz** [comment]
Closing as it sounds like it is fixed for VSO

Also the CSP error should now be fixed. Let me know if you see any further problems
