### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by xAt0mZ** [microsoft/vscode#100402]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3

**Context**
I was resolving merge conflicts in my project (AngularJS with .js files). I staged changes of a resolved file then switched to the next conflicting one and got an error message telling me "Typescript Service has stopped unexpectedly".
VSCode asked me if I wanted to open an issue to report the crash.
Not able to reproduce the error

**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:112241:13)
    at Object.releaseDocument (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:112236:20)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:135319:45
    at Object.forEach (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Proxy.dispose (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:135318:20)
    at InferredProject.Project.close (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:139542:38)
    at InferredProject.close (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:140420:40)
    at ProjectService.removeProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - OSS 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-17T22:31:53.325Z)
OS version: Linux x64 5.6.14-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3438)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.53GB (7.46GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
shell-format|fox|7.0.1
Go|gol|0.14.4
gc-excelviewer|Gra|2.1.35
vetur|oct|0.24.0
block-travel|sas|0.0.2

</details>

**Comment by xAt0mZ** [comment]
Seems to be a duplicate of https://github.com/microsoft/TypeScript/issues/37500
