### ISSUE TITLE
ioctl(2) failed, EBADF: Error: ioctl(2) failed, EBADF

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100457]
Seeing this output on macOS running integration tests:

```
ioctl(2) failed, EBADF: Error: ioctl(2) failed, EBADF
    at UnixTerminal.resize (/Users/bpasero/Development/Microsoft/monaco/node_modules/node-pty/lib/unixTerminal.js:238:13)
    at TerminalProcess.resize (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/node/terminalProcess.js:226:38)
    at TerminalProcessManager.setDimensions (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalProcessManager.js:219:31)
    at TerminalInstance._resize (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1137:34)

```

**Comment by Tyriar** [comment]
It's harmless but I'll move it to the debug log level.
