### ISSUE TITLE
TS Server fatal error:  Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by aurelien-altarriba** [microsoft/vscode#100505]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1. Install **Deno 1.1.0**
2. Create a skeleton of API project with **deno run --allow-run --allow-read --allow-write --allow-net https://deno.land/x/drash/create_app.ts --api**
3. **Launch the server**
 
**TS Server Error Stack**
```
TypeError: Cannot read property 'get' of undefined
    at resolveModuleNamesReusingOldState (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100222:92)
    at processImportedModules (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101668:35)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101411:17)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99987:60
    at Object.forEach (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99987:16)
    at synchronizeHostData (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138726:26)
    at Object.getProgram (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138818:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143310:53)
    at InferredProject.Project.updateGraph (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143253:42)
    at updateProjectIfDirty (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144517:45)
    at Array.forEach (<anonymous>)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146631:41)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:97
    at Object.flatMap (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147763:46)
    at c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Users\Aurélien\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
vscode-deno|den|1.25.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
php-namespace-resolver|Meh|1.1.8
vscode-apache|mrm|1.2.0
vscode-language-pack-fr|MS-|1.46.5
twig|wha|1.0.2

</details>

**Comment by mjbvz** [comment]
Does this still happen if you disabled the vscode-deno extension?
