### ISSUE TITLE
[extension]remote workspace ftp, vscode searches for nonexisting files in ftp

### ISSUE THREAD

**Issue by peon501** [microsoft/vscode#100592]
- VSCode Version: 1.45.0
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. use remote workspace extension and try to connect to FTP
2. why does the editor throws these errors and why it searches for these files? how can I block it?

Does this issue occur when all extensions are disabled?: no.

```
[2020-06-19 19:26:58.553] [renderer1] [error] Unable to read file 'ftp://#######@########.com:#######@ftp.#######.com/#######/.vscode/settings.json?debug=1' (Error: 550 Can't open /#######/.vscode/settings.json: No such file or directory): Error: Unable to read file 'ftp://#######@#######.#######@ftp.#######.com/#######/.vscode/settings.json?debug=1' (Error: 550 Can't open /#######/.vscode/settings.json: No such file or directory)
    at e.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by peon501** [comment]
(Error: 550 Can't open /#########/.vscode/settings.json: No such file or directory)
(Error: 550 Can't open /#########//.vscode/launch.json: No such file or directory)
(Error: 550 Can't open /#########//.vscode/tasks.json: No such file or directory)
