### ISSUE TITLE
can not run .\scripts\code.bat

### ISSUE THREAD

**Issue by seujza** [microsoft/vscode#100624]
- VSCode Version:  1.46
- OS Version:   win10 

Steps to Reproduce:

1.  .\scripts\code.bat

I want to Contribute in vscode but when i excute `.\scripts\code.bat`, it return         
```
$ node build/lib/electron
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: end of central directory record signature not found
    at D:\vscode1.46\vscode\node_modules\gulp-vinyl-zip\node_modules\yauzl\index.js:183:14
    at D:\vscode1.46\vscode\node_modules\gulp-vinyl-zip\node_modules\yauzl\index.js:622:5
    at D:\vscode1.46\vscode\node_modules\fd-slicer\index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[11:53:33] Syncronizing built-in extensions...
[11:53:33] You can manage built-in extensions with the --builtin flag
[11:53:33] [marketplace] ms-vscode.node-debug@1.44.6 ✔︎
[11:53:33] [marketplace] ms-vscode.node-debug2@1.42.4 ✔︎
[11:53:33] [marketplace] ms-vscode.references-view@0.0.57 ✔︎
[11:53:33] [marketplace] ms-vscode.js-debug-companion@1.0.2 ✔︎
[11:53:33] [marketplace] ms-vscode.js-debug@1.46.1 ✔︎
[11:53:33] [marketplace] ms-vscode.vscode-js-profile-table@0.0.5 ✔︎
```
So, how to solve the problem?

**Comment by joaomoreno** [comment]
You should have a `gulp-electron-cache` folder in your tmp folder. Just delete it.
