### ISSUE TITLE
Errors from extension viewlet in remote window

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#100880]
- Open a remote ssh window
- Lots of errors in devtools, and once there were layout issues in the extension viewlet

```
  ERR Cannot read property 'type' of undefined: TypeError: Cannot read property 'type' of undefined
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6730:587
    at Array.some (<anonymous>)
    at e.update (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6730:573)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6730:502
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4317:497
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at B.queryInstalled (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4313:334)
    at async X.queryLocal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6815:441)
workbench.desktop.main.js:sourcemap:1666   ERR Cannot read property 'local' of undefined: TypeError: Cannot read property 'local' of undefined
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6732:309
    at Array.some (<anonymous>)
    at e.update (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6732:297)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6732:226
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4317:497
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at B.queryInstalled (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4313:334)
    at async X.queryLocal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6815:441)
```

These 2 alternate over and over. And

`extensionsViews.ts:279 Error querying extensions gallery Cannot read property 'type' of undefined`

**Comment by sandy081** [comment]
@roblourens It would be great if you can repro this OOS?

**Comment by sandy081** [comment]
/duplicate

#101165
