### ISSUE TITLE
Remote SSH broken

### ISSUE THREAD

**Issue by Yuri6037** [microsoft/vscode#100925]
- VSCode Version: 1.46.1
- OS Version: Windows_NT x64 10.0.18363
- Remote OS: Ubuntu Server 18.04 LTS x86_64

Steps to Reproduce:

1. Connect to SSH server running Ubuntu Server 18.04 LTS with an account that already had VSCode ssh installed.
2. Enjoy nice error
[11:50:59.833] Unhandled rejection: Error: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.
    at e.reject (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5363:839)
    at e.resolveAndValidate (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5366:717)
    at e.doWriteConfiguration (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5361:70)
    at Object.factory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5360:801)
    at u.consume (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:130:75)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:886
    at new Promise (<anonymous>)
    at u.queue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:810)
    at e.writeConfiguration (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5360:786)
    at C.writeConfigurationValue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5389:83)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5377:320
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

Does this issue occur when all extensions are disabled?: I don't know how you can connect to SSH server if all extensions are disabled...

**Comment by Yuri6037** [comment]
The error is gone after adding manually the following json code in the User Settings:

```json
    "remote.SSH.remotePlatform": {
        "XXXXX": "linux"
    },
```

However VSCode is still unable to connect to the server. After looking at it seem that VSCode is unable to handle correctly sshkey only connections. Indeed the SSH server I'm using recently got updated to reject password authentication on all important SSH accounts (including the VSCode account). I can still connect through SSH using publickey authentication. I suspect VSCode is unable to correctly respect public key authentication and ends up throwing weird connection errors:
[00:02:50.764] Failed to set up socket for dynamic port forward to remote port 41819: Socket closed. Is the remote port correct?
[00:02:50.770] [Forwarding server 61779] Got connection 1
[00:02:50.772] [Forwarding server 61779] Got connection 2
[00:02:50.788] > channel 3: open failed: administratively prohibited: open failed
> 
[00:02:50.810] Failed to set up socket for dynamic port forward to remote port 41819: Socket closed. Is the remote port correct?
[00:02:50.817] > channel 3: open failed: administratively prohibited: open failed
> 
[00:02:50.818] Failed to set up socket for dynamic port forward to remote port 41819: Socket closed. Is the remote port correct?
[00:02:50.824] > channel 4: open failed: administratively prohibited: open failed
[00:02:50.834] > 
>

**Comment by Yuri6037** [comment]
Issue is now fixed: I had disabled TcpForwarding for certain users. AllowTcpForwarding must be set to at least "local" in the sshd_config for VSCode to work properly
