### ISSUE TITLE
WSL cannot connect after VScode update 1.46.1

### ISSUE THREAD

**Issue by mhebrard** [microsoft/vscode#101004]
- VSCode Version: 1.46.1
- OS Version: Windows 10 Enterprise version 1903 build 18362.900

Steps to Reproduce:

1.Launch VS code
2.Open a folder using extention Remote - WSL

error:

```
[2020-06-25 05:53:45.167] The factory method of "vs/base/node/paths" has thrown an exception
[2020-06-25 05:53:45.167] SyntaxError: /home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/package.json: Unexpected token  in JSON at position 0
[2020-06-25 05:53:45.167]     at JSON.parse (<anonymous>)
[2020-06-25 05:53:45.167]     at Object.Module._extensions..json (internal/modules/cjs/loader.js:799:27)
[2020-06-25 05:53:45.167]     at Module.load (internal/modules/cjs/loader.js:641:32)
[2020-06-25 05:53:45.167]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[2020-06-25 05:53:45.167]     at Module.require (internal/modules/cjs/loader.js:681:19)
[2020-06-25 05:53:45.167]     at require (internal/modules/cjs/helpers.js:16:16)
[2020-06-25 05:53:45.167]     at Object.<anonymous> (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/paths.js:5:24)
[2020-06-25 05:53:45.167]     at Module._compile (internal/modules/cjs/loader.js:774:30)
[2020-06-25 05:53:45.167]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
[2020-06-25 05:53:45.167]     at Module.load (internal/modules/cjs/loader.js:641:32)
[2020-06-25 05:53:45.167]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[2020-06-25 05:53:45.167]     at Module.require (internal/modules/cjs/loader.js:681:19)
[2020-06-25 05:53:45.167]     at require (internal/modules/cjs/helpers.js:16:16)
[2020-06-25 05:53:45.167]     at Function.s [as __$__nodeRequire] (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:33:115)
[2020-06-25 05:53:45.167]     at Object.<anonymous> (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:144:96)
[2020-06-25 05:53:45.167]     at Function.t._safeInvokeFunction (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:20:548)
[2020-06-25 05:53:45.167]     at Function.t._invokeFactory (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:20:795)
[2020-06-25 05:53:45.167]     at t.complete (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:21:10)
[2020-06-25 05:53:45.167]     at s._onModuleComplete (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:31:623)
[2020-06-25 05:53:45.167]     at s._resolve (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:31:174)
[2020-06-25 05:53:45.167]     at s.defineModule (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:25:184)
[2020-06-25 05:53:45.167]     at r (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:32:308)
[2020-06-25 05:53:45.167]     at c (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:16:958)
[2020-06-25 05:53:45.167]     at Object.<anonymous> (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:143:888)
[2020-06-25 05:53:45.167]     at Object.<anonymous> (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:507:685)
[2020-06-25 05:53:45.167]     at t._createAndEvalScript (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:17:3)
[2020-06-25 05:53:45.167]     at /home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:16:639
[2020-06-25 05:53:45.167]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
[2020-06-25 05:53:45.167]   phase: 'factory',
[2020-06-25 05:53:45.167]   moduleId: 'vs/base/node/paths'
[2020-06-25 05:53:45.167] }
[2020-06-25 05:53:45.167] The factory method of "vs/platform/product/common/product" has thrown an exception
[2020-06-25 05:53:45.167] SyntaxError: /home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/product.json: Unexpected token  in JSON at position 0
[2020-06-25 05:53:45.167]     at JSON.parse (<anonymous>)
[2020-06-25 05:53:45.167]     at Object.Module._extensions..json (internal/modules/cjs/loader.js:799:27)
[2020-06-25 05:53:45.167]     at Module.load (internal/modules/cjs/loader.js:641:32)
[2020-06-25 05:53:45.167]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[2020-06-25 05:53:45.167]     at Module.require (internal/modules/cjs/loader.js:681:19)
[2020-06-25 05:53:45.167]     at require (internal/modules/cjs/helpers.js:16:16)
[2020-06-25 05:53:45.167]     at Function.s [as __$__nodeRequire] (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:33:115)
[2020-06-25 05:53:45.167]     at Object.<anonymous> (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:324:359)
[2020-06-25 05:53:45.167]     at Function.t._safeInvokeFunction (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:20:548)
[2020-06-25 05:53:45.167]     at Function.t._invokeFactory (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:20:795)
[2020-06-25 05:53:45.167]     at t.complete (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:21:10)
[2020-06-25 05:53:45.167]     at s._onModuleComplete (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:31:623)
[2020-06-25 05:53:45.167]     at s._resolve (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:31:174)
[2020-06-25 05:53:45.167]     at s.defineModule (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:25:184)
[2020-06-25 05:53:45.167]     at r (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:32:308)
[2020-06-25 05:53:45.167]     at c (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:16:958)
[2020-06-25 05:53:45.167]     at Object.<anonymous> (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:302:206)
[2020-06-25 05:53:45.167]     at Object.<anonymous> (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:507:685)
[2020-06-25 05:53:45.167]     at t._createAndEvalScript (/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:17:3)
[2020-06-25 05:53:45.167]     at /home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/loader.js:16:639
[2020-06-25 05:53:45.167]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
[2020-06-25 05:53:45.167]   phase: 'factory',
[2020-06-25 05:53:45.167]   moduleId: 'vs/platform/product/common/product'
[2020-06-25 05:53:45.167] }
[2020-06-25 05:53:45.167] VS Code Server for WSL closed unexpectedly.
```

Does this issue occur when all extensions are disabled?: No (require Remote - WSL)

**Comment by aeschli** [comment]
I'm not able to reproduce, Version: 1.46.1 (user setup), Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
works for me on WSL.

Can you check out if `/home/hebrardms/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/product.json` got corrupted?

You can close all VSCode instances and delete the bin folder `rm -r /home/hebrardms/.vscode-server/bin` and try again.
If this doesn't work, an you copy the full WSL log (Command: Remote-WSL: Show Log)
