### ISSUE TITLE
Bug: extension keybindings fail to register for specific "enablement" and "when" clauses

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#101015]
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.0-1-amd64

Steps to Reproduce:

1. Create an extension that has a command with an `enablement` clause containint an or-expression:
https://github.com/iliazeus/vscode-keybinding-bug-demo/blob/master/package.json#L21

2. Add to this command a keybinding with a `when`-clause:
https://github.com/iliazeus/vscode-keybinding-bug-demo/blob/master/package.json#L28

Keybinding then fails to register, and the following is printed to the devtools console on VS Code startup:

```
  ERR It is not allowed to have an or expression here due to lack of parens! For example "a && (b||c)" is not supported, use "(a&&b) || (a&&c)" instead.: Error: It is not allowed to have an or expression here due to lack of parens! For example "a && (b||c)" is not supported, use "(a&&b) || (a&&c)" instead.
    at Function._normalizeArr (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1625:160)
    at Function.create (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1624:445)
    at Function.and (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:663)
    at e._asCommandRule (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4336:544)
    at e._handleKeybinding (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4336:267)
    at e._handleKeybindingsExtensionPointUser (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4335:663)
    at u._handler (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4331:216)
    at u._handle (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3902:949)
    at u.acceptUsers (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3902:856)
    at Function._handleExtensionPoint (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4071:826)
    at e._doHandleExtensionPoints (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4070:962)
    at e._registerAndHandleExtensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4894:6)
    at e._startLocalExtensionHost (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4893:654)
    at e._scanAndHandleExtensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4893:558)
    at async e._initialize (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4066:885)
```

Does this issue occur when all extensions are disabled?: N/A

**Comment by iliazeus** [comment]
It looks like VS Code assumes there will never be an or-expression inside of an and-expression in a `ContextKeyExpr`:

https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/platform/contextkey/common/contextkey.ts#L725-L728

But in a specific case that I described, this expression is being constructed by VS Code itself, by joining a command precondition and a keybinding when-clause with and and-expression:

https://github.com/microsoft/vscode/blob/ae7586488746ff59bdde2fa2453615fdf5f0b2ac/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L529-L531

But the precondition is an or-expression! Hence the error.

**Comment by gjsjohnmurray** [comment]
@jrieken can this be solved by simply wrapping the deserialized when clause in parens?

**Comment by iliazeus** [comment]
@alexdima it is not a feature request though, it's a bug report. Can this behavior at least get documented?
