### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by arindamdawn** [microsoft/vscode#101008]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99888:161)
    at resolveModuleNamesWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100106:26)
    at resolveModuleNamesReusingOldState (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100255:19)
    at processImportedModules (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101668:35)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101411:17)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99987:60
    at Object.forEach (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99987:16)
    at synchronizeHostData (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138726:26)
    at Proxy.getProgram (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138818:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143310:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143253:42)
    at ConfiguredProject.updateGraph (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144047:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145700:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146581:44)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:97
    at Object.flatMap (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147763:46)
    at c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Users\arind\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.1000.0
spellright|ban|3.0.50
emojisense|bie|0.7.0
markdown-emoji|bie|0.0.9
vscode-styled-jsx|bla|1.5.0
vscode-tailwindcss|bra|0.4.1
vscode-toggle-quotes|Bri|0.3.3
bracket-pair-colorizer-2|Coe|0.1.4
vscode-eslint|dba|2.1.5
vscode-deno|den|1.25.0
es7-react-js-snippets|dsz|2.8.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
vscode-front-matter|eli|1.1.1
prettier-vscode|esb|5.1.0
vscode-firefox-debug|fir|2.9.0
auto-rename-tag|for|0.1.3
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
vscode-styled-components|jpo|0.0.29
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
angular2-inline|nat|0.0.17
material-icon-theme|PKi|4.2.0
vscode-graphql|Pri|0.2.14
vscode-yaml|red|0.8.0
vscode-scss-formatter|sib|2.0.1
js-jsx-snippets|sky|10.1.0
vscode-stylelint|sty|0.84.0
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Very likely caused by the deno extension: https://github.com/denoland/vscode_deno/issues/89
