### ISSUE TITLE
Localization - starts with 'DE' locale and verifies title and viewlets text is in German

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101005]
I am not sure if this is a fluke or we actually changed some DOM structure that would cause this to fail in [1]

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at /Users/runner/runners/2.170.1/work/1/s/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.170.1/work/1/s/test/automation/out/code.js:9:58)

```

[1] https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=79815&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d&l=77

**Comment by dbaeumer** [comment]
Is caused due to a change in the Git viewlet. Reduced check to Explorer.
