### ISSUE TITLE
TS Server fatal error:  re.test is not a function

### ISSUE THREAD

**Issue by alois-reinstadler** [microsoft/vscode#101079]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1. Open Angular 10 project
2. Wait a bit
3. See if the window crashes or the extension host dies
**TS Server Error Stack**
```
TypeError: re.test is not a function
    at c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:29015:103
    at Object.findIndex (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:289:17)
    at _loop_5 (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:29015:43)
    at getFileNamesFromConfigSpecs (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:29045:17)
    at matchFileNames (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28963:16)
    at getFileNames (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28512:26)
    at parseJsonConfigFileContentWorker (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28444:18)
    at Object.parseJsonSourceFileConfigFileContent (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28402:16)
    at parseProjectReferenceConfigFile (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101779:34)
    at Array.map (<anonymous>)
    at Object.createProgram (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99955:67)
    at synchronizeHostData (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138726:26)
    at Object.getProgram (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138818:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143310:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143253:42)
    at ConfiguredProject.updateGraph (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144047:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145700:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146581:44)
    at c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:97
    at Object.flatMap (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147763:46)
    at c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Users\Alois\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.94GB free)|
|Process Argv|C:\Users\Alois\Documents\Code\Angular\ali|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.0
phpserver|bra|2.4.6
vscode-glsllint|CAD|1.1.1
gltf-vscode|ces|2.2.10
path-intellisense|chr|2.2.1
vscode-deno|den|1.25.0
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
Angular2|joh|9.1.2
python|ms-|2020.6.90262
remote-wsl|ms-|0.44.4
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
shader|sle|1.1.4
sass-indented|syl|1.8.6
vscodeintellicode|Vis|1.2.8
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by zeljkoantich** [comment]
Does it happen after you disable vscode-deno extension?

https://github.com/denoland/vscode_deno/issues/89

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
