### ISSUE TITLE
TS Server fatal error:  No Project.

### ISSUE THREAD

**Issue by andi1984** [microsoft/vscode#101113]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: No Project.
    at Object.ThrowNoProject (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:137981:23)
    at ScriptInfo.getDefaultProject (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:138751:46)
    at ProjectService.telemetryOnOpenFile (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:143324:42)
    at /Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:143406:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:143406:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:144260:46)
    at /Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/Volumes/code/repos/radar/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:210:5)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```

VS Code version: Code - Insiders 1.47.0-insider (6c235c723cb2d8defb840f732eac620f54aa8b9d, 2020-06-26T05:33:20.679Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|-psn_0_807109|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (83)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.6.2
vscode-openapi|42C|3.3.0
commit-message-editor|ada|0.13.0
Bookmarks|ale|11.3.1
tinypng|and|0.3.3
atlascode|atl|2.6.4
markdown-mermaid|bie|1.5.1
shell-syntax|bma|1.0.0
bemhelper|Box|0.8.1
radar-launcher|bru|1.1.0
better-toml|bun|0.3.2
vscode-pytest|Cam|0.1.1
regex|chr|0.2.0
language-postcss|cpy|1.1.0
vscode-svgviewer|css|2.0.0
rapid-json-search|dat|0.1.6
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
dotfiles-syntax-highlighting|dot|0.1.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
moxer-icons|Equ|5.6.0
prettier-vscode|esb|5.1.0
auto-rename-tag|for|0.1.3
html-slim-scss-css-class-completion|gen|1.7.5
vscode-pull-request-github|Git|0.17.0
name-that-color|gui|0.1.2
svg|joc|1.3.4
docthis|joe|0.7.1
read-time|joh|0.2.0
vscode-peacock|joh|3.7.2
vscode-styled-components|jpo|0.0.29
intellij-idea-keybindings|k--|0.2.41
vscode-colorize|kam|0.8.17
graphql-for-vscode|kum|1.15.3
codeacejumper|luc|3.3.2
MagicPython|mag|1.1.0
yarn-lock-syntax|mar|0.1.3
rust-analyzer|mat|0.2.216
twig-language-2|mbl|0.9.1
dotenv|mik|1.0.1
HTMLHint|mka|0.8.0
vscode-apache|mrm|1.2.0
vscode-csscomb|mrm|5.3.1
vscode-scss|mrm|0.9.0
python|ms-|2020.6.90262
remote-containers|ms-|0.123.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
azure-account|ms-|0.8.11
vscode-typescript-next|ms-|4.0.20200625
vsliveshare|ms-|1.0.2377
vsliveshare-audio|ms-|0.1.85
vsonline|ms-|1.0.2390
debugger-for-chrome|msj|4.12.8
indent-rainbow|ode|7.4.0
vscode-versionlens|pfl|1.0.8
nested-comments|phi|2.3.1
vscode-graphql|Pri|0.2.14
vscode-yaml|red|0.8.0
postcss|ric|2.0.0
LiveServer|rit|5.6.1
rust|rus|0.7.8
jinjahtml|sam|0.13.0
preview-vscode|sea|2.1.0
html5-boilerplate|sid|1.0.3
mdx|sil|0.1.0
music-time|sof|2.0.10
vscode-rustfmt|sta|0.1.0
rewrap|stk|1.12.0
svelte-vscode|sve|99.0.51
sass-indented|syl|1.8.6
tabnine-vscode|Tab|2.8.6
vscode-status-bar-format-toggle|tom|2.0.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.8
quokka-vscode|Wal|1.0.301
wallaby-vscode|Wal|1.0.212
twig|wha|1.0.2
jinja|who|0.0.8
zeplin|Zep|2.1.0
grammarly|znc|0.12.1

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Do you see this when using TS 3.9+?
