### ISSUE TITLE
Typescript auto-complete not working in VSCode

### ISSUE THREAD

**Issue by JackkGC** [microsoft/vscode#101296]
I'm trying to make use of Puppeteer within a ts file which works fine except the VSCode Intellisense stops working a soon as I'm inside a .ts and not a .js file.
I've seen some posts about this incident but none could help me. What I did:

 - created a project via npm init 
 - installed dependencies as follows:

```
    "dependencies": {
    "@types/node": "^14.0.14",
    "events": "^3.1.0",
    "puppeteer": "^4.0.1",
    "typescript": "^3.9.5" }

      "devDependencies": {
    "puppeteer-tsd": "0.0.2"  }
```
 - created tsconfig.json

```
 "target": "es5",
 "lib": ["es2015", "dom"],
 "outDir": "./dist",
   .
   .
   .
  "include": ["src/**/*", "node_modules/puppeteer-tsd/src/index.d.ts"]
```

- created src and dist folder
- put a main.ts inside my src
- told VSCode to use the project TS version instead of its own

Then I compiled. Everything works fine. But I get no IntelliSense to help me out while I type.
So I created a .js file in my src directory, copied the code from my main.ts inside it and then I got Intellisense to work perfectly fine with all suggestions and so on. And I have no idea left what I could try except accepting it and code without it.
I'd be greatful for any suggestions on what could be the issue. Thx in advance!

Meanwhile I found out, that it works fine with non imported functions like console.log(). It's only Puppeteer (or probably any imported module).

[Heres a Link to my Log File.](https://pastebin.com/8JX3rGqF)

**Comment by mjbvz** [comment]
Can you share a copy of your project?

**Comment by JackkGC** [comment]
Sure thing, here you go:
[project.zip](https://github.com/microsoft/vscode/files/4850860/project.zip)

**Comment by jtsom** [comment]
I'm also seeing this on an Angular 10 application. I created a new Angular app:
```
ng new ng10-test-app
```

Added a class:

```
export class Contact {
  name: string;
}
```

and tried to use it. VSCode doesn't find and suggest what the import for my class:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/13488/86182583-43ca1c80-bafe-11ea-94e8-9ce4b0c87406.png">
 
VSCode doesn't show any fix-its for adding an import for my class.

There is an error (repeated actually) in the Log (Window) output window:
```
[2020-06-30 17:37:02.038] [renderer1] [error] <semantic> TypeScript Server Error (4.0.0-dev.20200629)
No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:145281:23)
    at ScriptInfo.getDefaultProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:146062:46)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:148858:48)
    at ProjectService.ensureDefaultProjectForFile (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:148853:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152892:87)
    at IOSession.Session.getFileAndProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152875:29)
    at IOSession.Session.getApplicableRefactors (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153331:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152122:61)
    at /Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153634:88
    at IOSession.Session.executeWithRequestId (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153625:28)
    at IOSession.Session.executeCommand (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153634:33)
    at IOSession.Session.onMessage (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153658:35)
    at Interface.<anonymous> (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:155873:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (4.0.0-dev.20200629)
```
