### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by andkvo** [microsoft/vscode#101323]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.2
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/Users/Andy/.nvm/versions/node/v11.15.0/lib/node_modules/typescript/lib/tsserver.js:146871:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/Andy/.nvm/versions/node/v11.15.0/lib/node_modules/typescript/lib/tsserver.js:147749:46)
    at /Users/Andy/.nvm/versions/node/v11.15.0/lib/node_modules/typescript/lib/tsserver.js:149512:88
    at IOSession.Session.executeWithRequestId (/Users/Andy/.nvm/versions/node/v11.15.0/lib/node_modules/typescript/lib/tsserver.js:149503:28)
    at IOSession.Session.executeCommand (/Users/Andy/.nvm/versions/node/v11.15.0/lib/node_modules/typescript/lib/tsserver.js:149512:33)
    at IOSession.Session.onMessage (/Users/Andy/.nvm/versions/node/v11.15.0/lib/node_modules/typescript/lib/tsserver.js:149536:35)
    at Interface.<anonymous> (/Users/Andy/.nvm/versions/node/v11.15.0/lib/node_modules/typescript/lib/tsserver.js:150852:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.3.0
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|11.3.1
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.0
vscode-test-explorer|hbe|2.19.1
swagger-doc-viewer|mim|1.0.4
prettify-json|moh|0.0.3
vscode-docker|ms-|1.3.1
vetur|oct|0.24.0
openapi-designer|phi|0.3.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.5
vscode-jest-test-adapter|rtb|0.2.0
html5-boilerplate|sid|1.0.3

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
