### ISSUE TITLE
ERR Cannot set property 'kernel' of undefined

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#101446]
Testing #101319

* run `INCLUDE_PROPOSED=1  yo code`
![image](https://user-images.githubusercontent.com/5047891/86169102-64ec3680-bb19-11ea-900e-140fc484655b.png)
* press `f5`
* create a `test.sample-json-notebook` file and try to open it
* observe error message and error in dev tools:

![image](https://user-images.githubusercontent.com/5047891/86169255-9ebd3d00-bb19-11ea-87be-f2705a4d585e.png)

```
  ERR Cannot set property 'kernel' of undefined: TypeError: Cannot set property 'kernel' of undefined
    at x.registerNotebookController (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3973:45)
    at _.$registerNotebookProvider (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4212:692)
    at p._doInvokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4255:464)
    at p._invokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4255:156)
    at p._receiveRequest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4253:817)
    at p._receiveOneMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4252:623)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4250:836
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at v.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:430:733)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:435:38)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:432:243
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:428:234)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:427:604
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:436:655)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by connor4312** [comment]
@rebornix this is new between Friday-today. Pulling the latest .d.ts' doesn't result in compilation errors, did something change elsewhere?

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-generator-code/commit/a3ef09c4afc3cc3cf3f1c6d415160e8bc0329438
