### ISSUE TITLE
"Go to File" doesn't update search results after typing

### ISSUE THREAD

**Issue by rcdailey** [microsoft/vscode#101524]
Issue Type: <b>Bug</b>

# Actual Behavior

When I hit my shortcut to activate "Go to File...", I do not get updated search results right after I quickly type a substring. The progress indicator (the thin animation that plays at the bottom edge of the input box) just keeps going and no results are updated.

However, once that animation starts, if I type another character or hit space, I start seeing updated results.

# Expected Behavior

I expect results to update after I finish typing my substring, with no further input required. The fact that the progress is "stuck" after I type an initial few characters seems like a bug to me.

# Steps to Reproduce

1. Open a folder with a significant amount of files (let's say 100,000)
1. Hit your keyboard shortcut to open the "Go to File..." popover
1. Type a substring quickly (probably requires a fast typer). For example if you have a file somewhere named `SetupThings.cs`, type "setup" (without quotes) in the input box. Note that that progress indicator should not appear until after you stop typing.
1. Notice the progress indicator continues to animate, with no relevant results updating in the list below the input box. Note that you do see *some* results, but they are not relevant to the current query. I think they are previous results or searches.
1. Type a space character at the end of your substring. You should now see results populated.

As mentioned in my Expected Behavior, the last step should not be necessary to get results. I should get results any time I stop typing for a moment.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (35.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.2
vscode-markdownlint|Dav|0.36.1
xml|Dot|2.5.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.1
beautify|Hoo|1.5.0
reg|ion|1.0.1
plantuml|jeb|2.13.12
auto-comment-blocks|kev|1.0.1
wordcounter|kir|2.3.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.3.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.2.0
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
vscode-hexdump|sle|1.7.2
rewrap|stk|1.12.0
code-spell-checker|str|1.9.0
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by roblourens** [comment]
Could you do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by rcdailey** [comment]
There wasn't much in the log window so I'll just provide it inline here (as opposed to a file attachment):

```
[2020-06-30 16:05:53.914] [renderer1] [error] <syntax> TypeScript Server Error (3.9.4)
Debug Failure. False expression: Expected line to be non-zero
Error: Debug Failure. False expression: Expected line to be non-zero
    at failIfInvalidLocation (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142416:22)
    at ScriptInfo.positionToLineOffset (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142389:17)
    at toProtocolTextSpan (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149600:35)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149130:68
    at Array.map (<anonymous>)
    at IOSession.Session.toLocationNavigationTree (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149130:39)
    at IOSession.Session.getNavigationTree (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149141:32)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147984:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <syntax> TypeScript Server Error (3.9.4)
Debug Failure. False expression: Expected line to be non-zero
Error: Debug Failure. False expression: Expected line to be non-zero
    at failIfInvalidLocation (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142416:22)
    at ScriptInfo.positionToLineOffset (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142389:17)
    at toProtocolTextSpan (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149600:35)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149130:68
    at Array.map (<anonymous>)
    at IOSession.Session.toLocationNavigationTree (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149130:39)
    at IOSession.Session.getNavigationTree (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149141:32)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147984:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:54700)
	at e.dispatchResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:226420)
	at e.dispatchMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:225338)
	at c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:224814
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
	at t.Reader.onLengthData (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:233476)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:233124)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[2020-07-01 12:48:07.406] [renderer1] [trace] [File Watcher (C#)] Start watching: c:\code\CorepointHealth2
[2020-07-01 12:48:09.628] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\RobertDailey\AppData\Roaming\Code\User\globalStorage
[2020-07-01 12:48:09.830] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\RobertDailey\AppData\Roaming\Code\User\globalStorage
[2020-07-01 12:48:09.832] [renderer1] [debug] User data changed
[2020-07-01 12:48:20.296] [renderer1] [trace] CommandService#executeCommand workbench.action.quickOpen
[2020-07-01 12:48:20.297] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":0,"type":1,"filePattern":"","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:20.303] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"workbench.action.quickOpen","from":"keybinding"}
[2020-07-01 12:48:20.490] [renderer1] [debug] SearchService#search rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' -g '!**/.classpath' -g '!**/.project' -g '!**/.settings' -g '!**/.factorypath' -g '!**/node_modules*' -g '!/./output' --no-ignore-parent --follow --no-config
 - cwd: c:\code\CorepointHealth2
 - Sibling clauses: {}
[2020-07-01 12:48:20.892] [renderer1] [trace] SearchService#search: 570ms
[2020-07-01 12:48:20.893] [renderer1] [trace] telemetry/searchComplete {"reason":"openFileHandler","resultCount":0,"workspaceFolderCount":1,"type":"searchProcess","endToEndTime":570,"sortingTime":-1,"fileWalkTime":407,"directoriesWalked":0,"filesWalked":0,"cmdTime":407,"cmdResultCount":20674,"scheme":"file"}
[2020-07-01 12:48:20.898] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"u","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.042] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"un","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.043] [renderer1] [trace] SearchService#search: 143ms
[2020-07-01 12:48:21.122] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"uni","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.122] [renderer1] [trace] SearchService#search: 74ms
[2020-07-01 12:48:21.218] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unit","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.218] [renderer1] [trace] SearchService#search: 94ms
[2020-07-01 12:48:21.339] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unity","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.340] [renderer1] [trace] SearchService#search: 120ms
[2020-07-01 12:48:21.505] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unityc","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.505] [renderer1] [trace] SearchService#search: 164ms
[2020-07-01 12:48:21.602] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unityco","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.602] [renderer1] [trace] SearchService#search: 94ms
[2020-07-01 12:48:21.666] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unitycon","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.666] [renderer1] [trace] SearchService#search: 62ms
[2020-07-01 12:48:21.746] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unityconf","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.746] [renderer1] [trace] SearchService#search: 75ms
[2020-07-01 12:48:21.890] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unityconfi","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.890] [renderer1] [trace] SearchService#search: 142ms
[2020-07-01 12:48:21.986] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unityconfig","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:21.986] [renderer1] [trace] SearchService#search: 95ms
[2020-07-01 12:48:39.125] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"c:\\code\\CorepointHealth2","_sep":1,"external":"file:///c%3A/code/CorepointHealth2","path":"/c:/code/CorepointHealth2","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/node_modules*":true,"./output":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"unityconfig","sortByScore":true,"cacheKey":"id#83"}
[2020-07-01 12:48:39.125] [renderer1] [trace] SearchService#search: 17137ms
[2020-07-01 12:48:39.291] [renderer1] [debug] SearchService#search rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' -g '!**/.classpath' -g '!**/.project' -g '!**/.settings' -g '!**/.factorypath' -g '!**/node_modules*' -g '!/./output' --no-ignore-parent --follow --no-config
 - cwd: c:\code\CorepointHealth2
 - Sibling clauses: {}
[2020-07-01 12:48:39.711] [renderer1] [trace] SearchService#search: 586ms
[2020-07-01 12:48:39.711] [renderer1] [trace] telemetry/searchComplete {"reason":"openFileHandler","resultCount":56,"workspaceFolderCount":1,"type":"searchProcess","endToEndTime":586,"sortingTime":15,"fileWalkTime":410,"directoriesWalked":0,"filesWalked":0,"cmdTime":410,"cmdResultCount":20674,"scheme":"file"}
[2020-07-01 12:48:52.915] [renderer1] [trace] CommandService#executeCommand workbench.action.output.toggleOutput
[2020-07-01 12:48:53.002] [renderer1] [trace] CommandService#executeCommand setContext
[2020-07-01 12:48:53.002] [renderer1] [trace] MainThreadTreeViews#$refresh xmlTreeView undefined
[2020-07-01 12:49:02.217] [renderer1] [trace] CommandService#executeCommand workbench.output.action.switchBetweenOutputs
[2020-07-01 12:49:02.225] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"workbench.output.action.switchBetweenOutputs","from":"panel"}
[2020-07-01 12:49:02.295] [renderer1] [trace] CommandService#executeCommand setContext
[2020-07-01 12:49:02.295] [renderer1] [trace] CommandService#executeCommand setContext
[2020-07-01 12:49:02.296] [renderer1] [trace] MainThreadTreeViews#$refresh xmlTreeView undefined
[2020-07-01 12:49:02.296] [renderer1] [trace] CommandService#executeCommand setContext
[2020-07-01 12:49:02.465] [renderer1] [trace] MainThreadTreeViews#$refresh xmlTreeView undefined
[2020-07-01 12:49:05.102] [renderer1] [trace] CommandService#executeCommand setContext
[2020-07-01 12:49:05.102] [renderer1] [trace] MainThreadTreeViews#$refresh xmlTreeView undefined
[2020-07-01 12:49:05.581] [renderer1] [trace] CommandService#executeCommand setContext
[2020-07-01 12:49:05.581] [renderer1] [trace] MainThreadTreeViews#$refresh xmlTreeView undefined
[2020-07-01 12:49:05.953] [renderer1] [trace] CommandService#executeCommand editor.action.selectAll
[2020-07-01 12:49:05.954] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"editor.action.selectAll","from":"keybinding"}
[2020-07-01 12:49:06.595] [renderer1] [trace] CommandService#executeCommand setContext
```

**Comment by rcdailey** [comment]
My test was to type "unityconfig" (to find `UnityConfig.cs` in my code base). I waited about 10-15 seconds after typing it, got no results. So I hit SPACEBAR, then I got results after that time.

**Comment by roblourens** [comment]
I think I reproduced this once. Might be related to some other issues related to cancelling search. Will look into it some more

**Comment by rcdailey** [comment]
I'm able to reproduce this very consistently (90% or so). So if there's more testing with logs you'd like me to do, please let me know. Note I'm not running the insiders build right now (I normally value more stable builds in my day to day work) but I'm happy to run one if you need me to. Thank you for the quick response!

**Comment by roblourens** [comment]
Do you have any search-related settings configured (except for search.exclude/files.exclude)?

**Comment by rcdailey** [comment]
Yes I have these:

```
  "search.collapseResults": "alwaysExpand",
  "search.useGlobalIgnoreFiles": true,
  "search.maintainFileSearchCache": true,
  "search.searchOnType": false,
  "search.smartCase": true,
```

**Comment by roblourens** [comment]
In a similar issue, someone said they thought `search.maintainFileSearchCache` was responsible, does disabling that change anything for you?

**Comment by rcdailey** [comment]
Yes, resetting that setting does indeed fix the problem. I only enabled it in the first place because I understood it to be an optimization for faster file search results.

**Comment by roblourens** [comment]
Yeah, that setting is supposed to keep the search process with the cache alive, instead it is broken and can make it shut down at the wrong time, and probably triggers this issue. I need to fix that and also investigate a little more.

**Comment by roblourens** [comment]
I will actually merge this issue into https://github.com/microsoft/vscode/issues/99634 because now I'm sure they are the same.
