### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Daniel-Cuba** [microsoft/vscode#101542]
This error does not goes away! and it shows only in the VScode output console, I run the code in google chrome and the error is gone.

ReferenceError: document is not defined

Example:
https://codepen.io/Dany2020/pen/vYLWPox

`[Running] node "c:\\index.js"
var headerText = document.getElementById("header");
                            ^

ReferenceError: document is not defined
      at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[Done] exited with code=1 in 0.132 seconds`
`

**Comment by mjbvz** [comment]
You are running you script in `node`, which does not support html apis such as `document`
