### ISSUE TITLE
Vscode opens removed file always

### ISSUE THREAD

**Issue by moleszek** [microsoft/vscode#101510]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 20.04

Description: 
Hi, I have a strange problem with vscode. I removed a file from my folder and when I open vscode it opens that removed file all the time. 
When I open vscode in a specific directory, vscode opens twice, once where I wanted and second with the removed file.
If I open normally (without specifying folder or project) that fille will appears in vscode.
That file is unsaved (according to vscode) but when I save it, vscode still opens it on start. 

It's really hard to reproduce (or even no-reproducible) because I have vscode on Windows 10 and the second laptop with ubuntu 20.04 and this situation does not occur.

I tried to clear cache (from vscode and removed from folders *Cache* and *CachedData*

Steps to Reproduce:

1. Remove file
2. Open vscode

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
> That file is unsaved (according to vscode) but when I save it, vscode still opens it on start.

VSCode will always restore files that are not saved, we call this "hot exit". Can you check the log what happens when you save the file or close it without saving?

**Comment by moleszek** [comment]
Hi @bpasero 

I don't know if `render2.log` is the correct one:

```log
[2020-07-03 13:19:25.151] [renderer2] [error] Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/moleszek/scripts/python/if_4c.py'
[2020-07-03 13:19:25.151] [renderer2] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/moleszek/scripts/python/if_4c.py'
[2020-07-03 13:19:25.929] [renderer2] [error] Unable to write file 'vscode-userdata:/home/moleszek/.config/Code/User/Backups/1593592716811/file/ac17be7c8d032294d4f0f0dad12fa519' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/moleszek/.config/Code/Backups/1593592716811/file/ac17be7c8d032294d4f0f0dad12fa519'): Error: Unable to write file 'vscode-userdata:/home/moleszek/.config/Code/User/Backups/1593592716811/file/ac17be7c8d032294d4f0f0dad12fa519' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/moleszek/.config/Code/Backups/1593592716811/file/ac17be7c8d032294d4f0f0dad12fa519')
    at e.writeFile (file:///snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1692:701)
[2020-07-03 13:20:14.990] [renderer2] [error] Error: EACCES: permission denied, unlink '/home/moleszek/.config/Code/Backups/1593592716811/file/ac17be7c8d032294d4f0f0dad12fa519': NoPermissions (FileSystemError): Error: EACCES: permission denied, unlink '/home/moleszek/.config/Code/Backups/1593592716811/file/ac17be7c8d032294d4f0f0dad12fa519'
    at Object.d [as createFileSystemProviderError] (file:///snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1642:38)
    at r.toFileSystemProviderError (file:///snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:184)
    at r.delete (file:///snap/code/35/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:453)

```
but according to that line 

```log
[2020-07-03 13:19:25.151] [renderer2] [error] Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/moleszek/scripts/python/if_4c.py'
```
there is no file like if_4c.py and this is correct because I've removed it. 
However, it still opens in vscode (when I save it and open again vscode, it still appears as a unsaved file)

Maybe, there is a lack of permission (I'm not super Linux user)

**Comment by bpasero** [comment]
Yeah that sounds like the issue, somehow VSCode is not able to remove the backup in `/home/moleszek/.config/Code/Backups`. Can you manually remove it?

**Comment by moleszek** [comment]
Yes, I can remove it and the problem gone ;)

**Comment by moleszek** [comment]
Thanks, @bpasero for help ;)
