### ISSUE TITLE
jupyter NotebookApp "ipykernel_launcher" "UnicodeEncodeError" Uncaught exception

### ISSUE THREAD

**Issue by LJMP** [microsoft/vscode#101670]
- VSCode Version: 1.46.1 cd9ea6488829f560dc949a8b2fb789f3cdc05f5d x64
- OS Version: Linux  4.15.0-106-generic
- GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

## Steps to Reproduce:

1. have a `PS1` _bash_ promt with a fancy unicode char e.g. 💀 (= \U0001f480  relevant in error log)
1. setup `virtualenv -p python Venv`
2. open `.ipynb` file in **vscode**
1. select the virtualenv's kernel
1. crash💥

<details>
<summary>Click to expand: error log (UnicodeEncodeError)</summary>

```sh
Starting Jupyter from ~/work/456/Venv/bin/python with command line --no-browser --notebook-dir=/tmp/3d22c5f7-7335-465c-a630-7a499cf8eab0 --config=/tmp/3d22c5f7-7335-465c-a630-7a499cf8eab0/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
[I 14:11:34.270 NotebookApp] Serving notebooks from local directory: /tmp/3d22c5f7-7335-465c-a630-7a499cf8eab0
[I 14:11:34.270 NotebookApp] The Jupyter Notebook is running at:
[I 14:11:34.270 NotebookApp] http://localhost:8888/?token=b3b91585ee31f0239fd111a13cdcf0f0ef3159d8222628df
[I 14:11:34.270 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:11:34.276 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/user123/.local/share/jupyter/runtime/nbserver-31805-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b3b91585ee31f0239fd111a13cdcf0f0ef3159d8222628df
[I 14:11:34.702 NotebookApp] Creating new notebook in /
[E 14:11:35.013 NotebookApp] Failed to run command:
    [u'/home/user123/work/456/Venv/bin/python', u'-m', u'ipykernel_launcher', u'-f', u'/home/user123/.local/share/jupyter/runtime/kernel-ce56d8f9-8fbf-4fe4-9195-6f469497fbf4.json']
        PATH=u'/home/user123/work/456/Venv/bin:/home/user123/bin:/home/user123/.local/bin:/usr/bin:/home/user123/.pyenv/libexec:/home/user123/.pyenv/plugins/python-build/bin:/home/user123/.pyenv/plugins/pyenv-virtualenv/bin:/home/user123/.pyenv/plugins/pyenv-virtualenv/shims:/home/user123/.pyenv/shims:/home/user123/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user123/node-v10.15.3-linux-x64/bin'
        with kwargs:
    {'cwd': u'/tmp/3d22c5f7-7335-465c-a630-7a499cf8eab0', 'stdin': -1, 'preexec_fn': <function <lambda> at 0x7fe497995b90>, 'stderr': None, 'stdout': None}
    
[E 14:11:35.016 NotebookApp] Uncaught exception POST /api/sessions?1593778294935 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1593778294935', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 151, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
        **kw)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/home/user123/work/456/Venv/local/lib/python2.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f480' in position 0: ordinal not in range(128)
[W 14:11:35.018 NotebookApp] Unhandled error
[E 14:11:35.020 NotebookApp] {
      "Content-Length": "162", 
      "Accept-Encoding": "gzip,deflate", 
      "Connection": "close", 
      "Accept": "*/*", 
      "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)", 
      "Host": "localhost:8888", 
      "Content-Type": "application/json", 
      "Authorization": "token b3b91585ee31f0239fd111a13cdcf0f0ef3159d8222628df"
    }
[E 14:11:35.020 NotebookApp] 500 POST /api/sessions?1593778294935 (127.0.0.1) 32.99ms referer=None
[C 14:11:35.036 NotebookApp] received signal 15, stopping
[I 14:11:35.037 NotebookApp] Shutting down 0 kernels

```
</details>

<details>
<summary>Click to expand: works in bash shell 🤷</summary>

```sh
/home/user123/work/456/Venv/bin/python -m ipykernel_launcher -f /home/user123/.local/share/jupyter/runtime/kernel-ce56d8f9-8fbf-4fe4-9195-6f469497fbf4.json

NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-ce56d8f9-8fbf-4fe4-9195-6f469497fbf4.json
```

</details>

## Already tried:
all system locale are set to `=en_US.UTF-8` 🙁
`export PYTHONIOENCODING=utf-8` 🙁

PS: 
- works with Venv as expected with a standard PS1 (=without 💀 char)
- also works if not in a virtualenv but system installed jupyter

**Comment by rebornix** [comment]
Please file against the Python extension.
