### ISSUE TITLE
Failing smoke test

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#101619]
Testing #101334

Manually checked this, and it works.

```
19 passing (56s)
  1 failing

  1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Language Features
           verifies settings:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at C:\Users\t-adthak\src\github.com\microsoft\vscode\test\automation\out\code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\t-adthak\src\github.com\microsoft\vscode\test\automation\out\code.js:9:58)
```

**Comment by bpasero** [comment]
Should try with recent bits.
