### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by worming004** [microsoft/vscode#101632]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1. open fresh angular project
**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99888:161)
    at resolveModuleNamesWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100106:26)
    at resolveModuleNamesReusingOldState (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100255:19)
    at processImportedModules (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101668:35)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101411:17)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:60
    at Object.forEach (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:16)
    at synchronizeHostData (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138726:26)
    at Proxy.getProgram (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138818:13)
    at ConfiguredProject.Project.updateGraphWorker (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143310:53)
    at ConfiguredProject.Project.updateGraph (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143253:42)
    at ConfiguredProject.updateGraph (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144047:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145700:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146581:44)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:97
    at Object.flatMap (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147763:46)
    at /snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/snap/code/35/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.4.0-39-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3725)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.88GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
ng-template|Ang|0.1000.2
angulardoc-vscode|Ang|6.1.3
path-intellisense|chr|2.2.1
angular-schematics|cyr|4.3.0
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.5
vscode-deno|den|1.25.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
go|gol|0.15.0
json2ts|Gre|0.0.6
rest-client|hum|0.24.1
angular2-switcher|inf|0.3.3
Angular2|joh|9.1.2
restructuredtext|lex|128.0.0
angular-extension-pack|loi|0.7.1
Angular2Tests|Mar|0.7.3
git-graph|mhu|1.24.0
Angular-BeastCode|Mik|8.1.2
azure-pipelines|ms-|1.170.0
vscode-azureappservice|ms-|0.17.0
vscode-azurefunctions|ms-|0.22.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.1
vscode-cosmosdb|ms-|0.13.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
vscode-dotnet-runtime|ms-|0.1.2
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.91350
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
azurerm-vscode-tools|msa|0.11.0
debugger-for-chrome|msj|4.12.8
ng-fortytwo-vscode-extension|NG-|0.0.9
vscode-protolint|ple|0.3.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.8.0
simontest|Sim|1.8.8
autoimport|ste|1.5.3
move-ts|str|1.12.0
Angular2|UVB|0.4.1
vscodeintellicode|Vis|1.2.9
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by worming004** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/100275
deno propose itself to be deactivated, putting

```json
{
    "deno.enable": false
}
```
into .vscode/settings.json.  But obviously, it doesn't work.

I resolve it by deactivating the extension from the extension panel
