### ISSUE TITLE
Typescript intellisense not working

### ISSUE THREAD

**Issue by stoplion** [microsoft/vscode#101641]
- VSCode Version: 1.46
- OS Version: 10.15

Steps to Reproduce:

- Install `JavaScript and TypeScript Nightly` extension
- Add `tsconfig.json`

```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "exclude": ["**/*.spec.ts", "node_modules", "vendor", "public"],
  "compileOnSave": false
}
```

babel
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    ["@babel/preset-typescript", { "allExtensions": true, "isTSX": true }]
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "transform-object-rest-spread",
    "inline-react-svg",
    "transform-async-to-generator",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
What isn't working? Please provide steps to reproduce and a small example project.

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jtsom** [comment]
I'm also seeing this on an Angular 10 application. 
VSCode:
Version: 1.47.0-insider
Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
Date: 2020-07-02T05:41:12.081Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

I created a new Angular app:
```
ng new ng10-test-app
```

Added a class:

```
export class Contact {
  name: string;
}
```

and tried to use it. VSCode doesn't find and suggest what the import for my class:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/13488/86182583-43ca1c80-bafe-11ea-94e8-9ce4b0c87406.png">
 
VSCode doesn't show any fix-its for adding an import for my class.

I was seeing an error (repeated actually) in the Log (Window) output window (But I don't even see the Log (Window) output now:
```
[2020-06-30 17:37:02.038] [renderer1] [error] <semantic> TypeScript Server Error (4.0.0-dev.20200629)
No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:145281:23)
    at ScriptInfo.getDefaultProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:146062:46)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:148858:48)
    at ProjectService.ensureDefaultProjectForFile (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:148853:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152892:87)
    at IOSession.Session.getFileAndProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152875:29)
    at IOSession.Session.getApplicableRefactors (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153331:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152122:61)
    at /Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153634:88
    at IOSession.Session.executeWithRequestId (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153625:28)
    at IOSession.Session.executeCommand (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153634:33)
    at IOSession.Session.onMessage (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153658:35)
    at Interface.<anonymous> (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:155873:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (4.0.0-dev.20200629)
```

**Comment by mjbvz** [comment]
Closing as we need more information from the original poster

@jtsom I see you've opened https://github.com/microsoft/TypeScript/issues/39488 to track your issue
