### ISSUE TITLE
pwa-node type in launch.json stopped working on OSX

### ISSUE THREAD

**Issue by Zophiel** [microsoft/vscode#101683]
- VSCode Version: 1.46.1
- OS Version: OSX v10.14.6

Steps to Reproduce:

1. Have a project in git with basic vue.js submodule
2. Configure the launch.json as follows:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "_rpr-app",
            "request": "launch",
            "runtimeArgs": [
                "run-script",
                "serve"
            ],
            "runtimeExecutable": "npm",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "trace": true,
            "type": "pwa-node",
            "cwd": "${workspaceFolder}/rpr-app",
            "outputCapture": "std",
            "serverReadyAction":{
                "action": "openExternally",
                "pattern": "App running at",
                "uriFormat": "http://localhost:8080"
            }
        }]
}
```

3. Execute the profile

This results in the following error:

```
/usr/local/bin/npm run-script serve
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '"/Applications/Visual'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by connor4312** [comment]
Thanks, this was reported in https://github.com/microsoft/vscode-js-debug/issues/543. This will be fixed in the next vscode release, or you can grab the latest [nightly version](https://github.com/microsoft/vscode-js-debug#nightly-extension).
