### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shyfcka** [microsoft/vscode#101709]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.0.0-dev.20200703
**Steps to reproduce crash**
1.Open the application
**TS Server Error Stack**
```
RangeError: Maximum call stack size exceeded
    at toFileNameLowerCase (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:1514:40)
    at Object.toPath (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:6662:16)
    at ProjectService.toPath (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:148703:27)
    at c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151435:56
    at Object.forEachAncestorDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:6866:26)
    at Object.searchDirectoryAndAncestors (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151431:24)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151328:46)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
    at processDirectory (c:\Users\Administrator\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200703\node_modules\typescript\lib\tsserver.js:151329:36)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
tellraw-preview|act|0.2.1
node-essentials|afr|1.1.0
tinypng|and|0.3.3
language-mcfunction|arc|0.16.0
bat-snippets|bat|0.2.0
todo-language|blu|0.4.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
jquerysnippets|don|0.0.1
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|5.1.3
vs-code-xml-format|fab|0.1.5
vscode-firefox-debug|fir|2.9.0
auto-rename-tag|for|0.1.4
code-runner|for|0.10.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
rest-client|hum|0.24.1
path-autocomplete|ion|1.14.0
docthis|joe|0.7.1
vscode-peacock|joh|3.7.2
minifyall|jos|2.3.1
vscode-gutter-preview|kis|0.26.2
electron-debug|kod|18.11.1
mcjson|Lev|0.4.1
background-cover|man|2.2.3
vscode-todo-plus-plus|mdw|4.14.4
vscode-filesize|mkx|2.1.4
vscode-language-pack-zh-hans|MS-|1.46.3
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
vscode-typescript-next|ms-|4.0.20200703
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
vsliveshare-pack|ms-|0.4.0
debugger-for-edge|msj|1.0.15
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
polacode|pnp|0.3.4
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|1.9.0
svg-preview|Sim|2.8.3
indenticator|Sir|0.6.0
swdc-vscode|sof|2.2.26
datapack-language-server|SPG|2.1.9
guides|spy|0.9.3
mcscript|Ste|0.0.3
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
emmet-live|yse|1.0.0
html-css-class-completion|Zig|1.19.0

(6 theme extensions excluded)

</details>

**Comment by shyfcka** [comment]
I found the reason
There is a "package.json" in my directory, Its contents are empty
I removed it and solved the problem
