### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script should not exist and not be open already

### ISSUE THREAD

**Issue by daiglars** [microsoft/vscode#101887]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.6.5
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression: Script should not exist and not be open already
    at ProjectService.applyChangesInOpenFiles (c:\Users\daiglars\git\InsightsServices\src\ClientApp\node_modules\typescript\lib\tsserver.js:132804:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\daiglars\git\InsightsServices\src\ClientApp\node_modules\typescript\lib\tsserver.js:133611:46)
    at c:\Users\daiglars\git\InsightsServices\src\ClientApp\node_modules\typescript\lib\tsserver.js:135267:88
    at IOSession.Session.executeWithRequestId (c:\Users\daiglars\git\InsightsServices\src\ClientApp\node_modules\typescript\lib\tsserver.js:135258:28)
    at IOSession.Session.executeCommand (c:\Users\daiglars\git\InsightsServices\src\ClientApp\node_modules\typescript\lib\tsserver.js:135267:33)
    at IOSession.Session.onMessage (c:\Users\daiglars\git\InsightsServices\src\ClientApp\node_modules\typescript\lib\tsserver.js:135290:35)
    at Interface.<anonymous> (c:\Users\daiglars\git\InsightsServices\src\ClientApp\node_modules\typescript\lib\tsserver.js:136605:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (12.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.6
xml|Dot|2.5.0
vscode-vsproj|jRi|1.2.1
csharp|ms-|1.22.1

</details>

**Comment by mjbvz** [comment]
Do you see this in more recent TypeScript versions, such as TS 3.9+?

**Comment by daiglars** [comment]
I don’t know. This only happened to me once. I don’t know how to repro it.

**Comment by daiglars** [comment]
I only saw this happen once. I'll just close this.
