### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by izio38** [microsoft/vscode#101899]
**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
I just brwose some files randomly
**TS Server Error Stack**
```
Error: Debug Failure.
    at assertDefined (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:2077:24)
    at Object.assertEachDefined (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:2084:17)
    at resolveModuleNamesWorker (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:97713:155)
    at resolveModuleNamesReusingOldState (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:98059:19)
    at processImportedModules (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:99448:35)
    at findSourceFile (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:99191:17)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:98987:34)
    at processSourceFile (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:99020:13)
    at processRootFile (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:98843:13)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:97809:60
    at Object.forEach (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:97809:16)
    at synchronizeHostData (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:135218:26)
    at Proxy.getProgram (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:140654:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:142246:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143101:44)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143396:107
    at Object.mapDefined (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Do you see this when using the current TypeScript release, 3.9+?

**Comment by izio38** [comment]
I'm really sorry, it was my Deno extension that fucked the module resolution up.
