### ISSUE TITLE
Ext host doc model out of sync with editor properties for split editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101956]
Saw this with notebooks but I can repro it in a normal editor.

- Open a markdown file
- Split the editor
- cmd+a
- duplicate lines down, or paste a large amount of content at the bottom of the file
- See this stack from the markdown extension

```
Error: Illegal value for `line`
	at ExtHostDocumentData._lineAt (/Users/roblou/code/vscode/out/vs/workbench/api/common/extHostDocumentData.js:106:23)
	at Object.lineAt (/Users/roblou/code/vscode/out/vs/workbench/api/common/extHostDocumentData.js:57:53)
	at getVisibleLine (/Users/roblou/code/vscode/extensions/markdown-language-features/out/util/topmostLineMonitor.js:57:34)
	at /Users/roblou/code/vscode/extensions/markdown-language-features/out/util/topmostLineMonitor.js:20:30
	at Emitter.fire (/Users/roblou/code/vscode/out/vs/base/common/event.js:456:38)
	at ExtHostEditors.$acceptEditorPropertiesChanged (/Users/roblou/code/vscode/out/vs/workbench/api/common/extHostTextEditors.js:112:58)
	at RPCProtocol._doInvokeHandler (/Users/roblou/code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:335:27)
	at RPCProtocol._invokeHandler (/Users/roblou/code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:320:45)
	at RPCProtocol._receiveRequest (/Users/roblou/code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:247:32)
	at RPCProtocol._receiveOneMessage (/Users/roblou/code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:175:26)
	at /Users/roblou/code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:65:52
	at Emitter.fire (/Users/roblou/code/vscode/out/vs/base/common/event.js:456:38)
```

Seems that the markdown extension listens to `onDidChangeTextEditorVisibleRanges` and does

```ts
	const firstVisiblePosition = editor.visibleRanges[0].start;
	const lineNumber = firstVisiblePosition.line;
	const line = editor.document.lineAt(lineNumber);
```

When this is called, the document does not know about the new content, but `editor.visibleRanges` has been adjusted for the new content. So if the top visible line is in the range of the new content, it will throw. Debugging, it seems like 
`$acceptEditorPropertiesChanged` is sent before `$acceptModelChanged`, which would explain why they are out of sync.

**Comment by rebornix** [comment]
I know @alexdima and @jrieken worked hard before to make `$acceptEditorPropertiesChanged` correct.

**Comment by jrieken** [comment]
Great find. Thanks @roblourens

**Comment by alexdima** [comment]
Great catch!
