### ISSUE TITLE
Failing integration test

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101911]
see https://dev.azure.com/vscode/VSCode/_build/results?buildId=48130&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=d494b5db-eef8-5766-984e-01186010c86f

**Comment by Tyriar** [comment]
```
1) vscode API - terminal Terminal window.onDidWriteTerminalData should listen to all future terminal data events:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

The second failure likely happened only because of the first test failure.
