### ISSUE TITLE
TS Server fatal error:  Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by mukuljainx** [microsoft/vscode#102018]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.5.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:128286:43)
    at ProjectService.addFilesToNonInferredProject (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:128181:22)
    at ProjectService.updateRootAndOptionsOfNonInferredProject (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:128324:22)
    at ProjectService.loadConfiguredProject (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:128260:22)
    at ProjectService.createAndLoadConfiguredProject (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:128205:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:128210:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:129018:44)
    at /Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:129234:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:129234:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:129980:46)
    at /Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:131662:28)
    at IOSession.Session.executeCommand (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:131671:33)
    at IOSession.Session.onMessage (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:131693:35)
    at Interface.<anonymous> (/Users/i0424/engine/datashop/packages/core/datashop-patient/node_modules/typescript/lib/tsserver.js:132984:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|25, 37, 41|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.29
atom-keybindings|ms-|3.0.8
vsliveshare|ms-|1.0.2427
filetemplate|Ral|2.0.4
code-spell-checker|str|1.9.0
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Do you see this when using TS 3.9+?
