### ISSUE TITLE
TS Server fatal error:  path.replace is not a function 

### ISSUE THREAD

**Issue by yhlukhov** [microsoft/vscode#102073]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1. Open VS Code
2. Open project folder

**TS Server Error Stack**
```
TypeError: path.replace is not a function
    at normalizeSlashes (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:6303:21)
    at combinePaths (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:6364:28)
    at getPathComponents (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:6278:16)
    at getNormalizedPathComponents (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:6404:37)
    at Object.getNormalizedAbsolutePath (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:6408:42)
    at getFileNamesFromConfigSpecs (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:29001:31)
    at matchFileNames (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28963:16)
    at getFileNames (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28512:26)
    at parseJsonConfigFileContentWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28444:18)
    at Object.parseJsonSourceFileConfigFileContent (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28402:16)
    at ProjectService.loadConfiguredProject (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145720:44)
    at ProjectService.createAndLoadConfiguredProject (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145694:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145699:36)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146581:44)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:97
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147763:46)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
code-runner|for|0.11.0
beautify|Hoo|1.5.0
Angular-BeastCode|Mik|8.1.2
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.9

(2 theme extensions excluded)

![image](https://user-images.githubusercontent.com/1419892/87125941-03a03200-c294-11ea-8464-1e2408d4b581.png)

</details>

**Comment by mjbvz** [comment]
Do you see this with TypeScript 3.9.6+

**Comment by yhlukhov** [comment]
I have upgraded to 3.9.6, for some reason it is still showing 3.9.4 in one place - footer

![image](https://user-images.githubusercontent.com/1419892/87220457-87c5e880-c36c-11ea-8112-bcb1d9ac282b.png)

**Comment by mjbvz** [comment]
See https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions

You also need to switch your workspace to use the workspace version of TypeScript

**Comment by yhlukhov** [comment]
I've created new project and it looks error disappear. will see how it
works later, for now is good!

пн, 13 лип. 2020 о 21:19 Matt Bierner <notifications@github.com> пише:
