### ISSUE TITLE
1.47.0  can not load extension

### ISSUE THREAD

**Issue by 1549469775** [microsoft/vscode#102125]
Issue Type: <b>Bug</b>

```
ERR Cannot read property 'uuid' of undefined: TypeError: Cannot read property 'uuid' of undefined
    at o (file:///C:/Users/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1638:272)
    at file:///C:/Users/pData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:140
    at Array.some (<anonymous>)
    at n (file:///C:/Users/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:132)
    at Object.t.groupByExtension (file:///C:/Users/ApData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:202)
    at C.scanUserExtensions (file:///C:/Users/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3890:698)
    at async C.scanExtensions (file:///C:/Users/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3889:705)
    at async Promise.all (index 1)
    at async V._scanAllLocalExtensions (file:///C:/Users/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:85)
    at async V._scanAndHandleExtensions (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5002:652)
    at async V._initialize (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4273:805)
workbench.desktop.main.js:sourcemap:1670   ERR Cannot read property 'uuid' of undefined: TypeError: Cannot read property 'uuid' of undefined
    at o (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1638:272)
    at file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:140
    at Array.some (<anonymous>)
    at n (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:132)
    at Object.t.groupByExtension (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1639:202)
    at C.scanUserExtensions (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3890:698)
    at async C.scanExtensions (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3889:705)
    at async Promise.all (index 1)
    at async V._scanAllLocalExtensions (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:85)
    at async Object.getInitData (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5000:358)
    at async Promise.all (index 1)
    at async z._createExtHostInitData (file:///C:/Users//AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4619:345)
```

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|11.1.0
eggjs|ati|0.3.1
thief-book|C-T|0.0.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
node-version|fiv|0.0.1
code-runner|for|0.11.0
terminal|for|0.0.10
go|gol|0.15.1
todo-tree|Gru|0.0.178
debug-visualizer|hed|1.1.0
vscode-drawio|hed|0.7.2
rest-client|hum|0.24.1
comment-translate|int|1.4.2
path-autocomplete|ion|1.14.0
git-graph|mhu|1.24.0
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|2.1.4
compare-folders|mos|0.13.0
vscode-language-pack-zh-hans|MS-|1.47.3
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.10
sqltools-driver-mysql|mtx|0.1.0
awesome-flutter-snippets|Nas|2.0.4
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
explorer-exclude-vscode-extension|Red|1.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
rainbow-fart|sae|1.3.0
git-merger|sha|0.4.1
sass-indented|syl|1.8.7
tabnine-vscode|Tab|2.8.8
terminal-tabs|Tyr|0.2.0
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
webpack-progress|wk-|0.0.8
html-css-class-completion|Zig|1.19.0

</details>

**Comment by harryharanb** [comment]
I have same issue with Code 1.47.0 Extensions are not loaded. Installed v1.46.0 May 2020 release. Everything back to normal
```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z (1 day ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

```
ERR Cannot read property 'uuid' of undefined: TypeError: Cannot read property 'uuid' of undefined
    at o (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1638:272)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:140
    at Array.some (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:132)
    at Object.t.groupByExtension (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:202)
    at C.scanUserExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3890:698)
    at async C.scanExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3889:705)
    at async Promise.all (index 1)
    at async V._scanAllLocalExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5000:85)
    at async V._scanAndHandleExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5002:652)
    at async V._initialize (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4273:805)
log.ts:197   ERR Cannot read property 'uuid' of undefined: TypeError: Cannot read property 'uuid' of undefined
    at o (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1638:272)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:140
    at Array.some (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:132)
    at Object.t.groupByExtension (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:202)
    at C.scanUserExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3890:698)
    at async C.scanExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3889:705)
    at async Promise.all (index 1)
    at async V._scanAllLocalExtensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5000:85)
    at async Object.getInitData (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5000:358)
    at async Promise.all (index 1)
    at async z._createExtHostInitData (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4619:345)
2console.ts:137 [IPC Library: File Watcher (nsfw)] (node:3026) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**Comment by 1549469775** [comment]
i tried,it worked,but  it reminds me that some plugins are not compatible;

**Comment by sandy081** [comment]
/duplicate

#102082
