### ISSUE TITLE
Smoke: Notebooks moves focus in and out of output

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102113]
```
1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           moves focus in and out of output:
     Error: Timeout: is active element 'webview, .webview' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=81426&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=1fbbf8a8-a0a4-519f-def5-b5fd8ca21811&l=107

**Comment by roblourens** [comment]
I have run it many times and haven't been able to repro it yet
