### ISSUE TITLE
Extension uninstall hook bug

### ISSUE THREAD

**Issue by AShujiao** [microsoft/vscode#102260]
卸载钩子不知道什么时候已经不能用了，刚用时一切正常。我看输出日志卸载后是先将我的扩展目录删除，再去执行卸载钩子脚本对吗？但是脚本就在我的扩展里放着，扩展都给清空了导致找不到脚本，无法执行。是这个情况吗？
下面是输出日志：

[2020-07-12 10:55:52.046] [sharedprocess] [info] main {"machineId":"f42610203afdec24edd0ce140e0754d6c3dfad7da9e9d393a431140010997234","windowId":2}
[2020-07-12 10:55:53.167] [sharedprocess] [info] manasxx.background-cover 2.2.4 Running post uninstall script
[2020-07-12 10:55:53.203] [sharedprocess] [info] Deleted from disk manasxx.background-cover c:\Users\a9168\.vscode\extensions\manasxx.background-cover-2.2.4
[2020-07-12 10:55:53.277] [sharedprocess] [error] manasxx.background-cover 2.2.4 post-uninstall internal/modules/cjs/loader.js:720
    t
[2020-07-12 10:55:53.278] [sharedprocess] [error] manasxx.background-cover 2.2.4 post-uninstall hrow err;
    ^

Error: Cannot find module 'c:\Users\a9168\.vscode\extensions\manasxx.background-cover-2.2.4\out\uninstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[2020-07-12 10:55:53.286] [sharedprocess] [error] manasxx.background-cover 2.2.4 Failed to run post uninstall script: post-uninstall process exited with code 1
[2020-07-12 10:56:32.853] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-07-12 10:56:32.856] [sharedprocess] [info] Skipping directory a51afd50c8d4aef5e5230191ccd083a9.zh-cn. Language pack still in use.

**Comment by iigmir** [comment]
Extension uninstall hook cannot used somehow. It was worked at first. However, when watched the log, I found that VSCode deletes the extension directory first, then executes the extension uninstall hook. Am I correct?

But my script was in my extension directory, too. The script will not found because the directory that stores it was deleted by VSCode.

Here are logs:

```
[2020-07-12 10:55:52.046] [sharedprocess] [info] main {"machineId":"f42610203afdec24edd0ce140e0754d6c3dfad7da9e9d393a431140010997234","windowId":2}
[2020-07-12 10:55:53.167] [sharedprocess] [info] manasxx.background-cover 2.2.4 Running post uninstall script
[2020-07-12 10:55:53.203] [sharedprocess] [info] Deleted from disk manasxx.background-cover c:\Users\a9168.vscode\extensions\manasxx.background-cover-2.2.4
[2020-07-12 10:55:53.277] [sharedprocess] [error] manasxx.background-cover 2.2.4 post-uninstall internal/modules/cjs/loader.js:720
t
[2020-07-12 10:55:53.278] [sharedprocess] [error] manasxx.background-cover 2.2.4 post-uninstall hrow err;
^

Error: Cannot find module 'c:\Users\a9168.vscode\extensions\manasxx.background-cover-2.2.4\out\uninstall'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
at Module._load (internal/modules/cjs/loader.js:622:27)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
at internal/main/run_main_module.js:17:11 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}

[2020-07-12 10:55:53.286] [sharedprocess] [error] manasxx.background-cover 2.2.4 Failed to run post uninstall script: post-uninstall process exited with code 1
[2020-07-12 10:56:32.853] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-07-12 10:56:32.856] [sharedprocess] [info] Skipping directory a51afd50c8d4aef5e5230191ccd083a9.zh-cn. Language pack still in use.
```

**Comment by sandy081** [comment]
/duplicate 

#100323
