### ISSUE TITLE
ENOENT when trying to start debug session using babel-node after updating to 1.47.0

### ISSUE THREAD

**Issue by sceee** [microsoft/vscode#102377]
Issue Type: <b>Bug</b>

After updating VSCode from `1.46.1` to `1.47.0`, starting a node debug session using the following configuration fails:
```
    {
      "type": "node",
      "request": "launch",
      "name": "Debug App",
      "program": "${workspaceRoot}/my/app.js",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node",
      "runtimeArgs": ["--nolazy"],
      "internalConsoleOptions": "openOnSessionStart",
      "preLaunchTask": "babelcompile",
      "env": {
        "BABEL_ENV": "debug"
      },
    },
```
It fails with:
```
C:\my\app/node_modules/.bin/babel-node --nolazy c:\my\app\app.js
Error: spawn C:\my\app/node_modules/.bin/babel-node ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

Downgrading to `1.46.1` makes it work again.

VS Code version: Code 1.47.0
OS version: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
You may need to have a section:

```
"windows": {
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node.cmd",
}
```



/duplicate https://github.com/microsoft/vscode/issues/102235
