### ISSUE TITLE
Support 429 Retry-After

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#102391]
The sync server will soon support throttling via 429 with the [`Retry-After` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) that indicates the number of seconds to wait before trying again. When `Retry-After` is set, sync should be suspended (silently) for the period specified instead of being turned off.

**Comment by sandy081** [comment]
When server returns `retry-after` header with `429` status, client suspends auto sync until mentioned time and enables auto sync after.

```
[2020-07-20 19:00:33.137] [userDataSync] [info] Auto Sync: Started
[2020-07-20 19:00:33.137] [userDataSync] [info] Auto Sync: Triggered by Interval
[2020-07-20 19:00:33.731] [userDataSync] [info] Auto Sync: Suspended until 2020-07-20T19:02:33.730Z because server is not accepting requests until then.
[2020-07-20 19:00:33.731] [userDataSync] [info] Auto sync: Canelled sync that is in progress
[2020-07-20 19:00:33.731] [userDataSync] [info] Auto Sync: Stopped
[2020-07-20 19:00:33.733] [userDataSync] [error] TooManyRequestsAndRetryAfter (UserDataSyncError) syncResource:unknown operationId:ddfabf1187de472a88b05bcfe32c9a6c: GET request 'https://server/v1/manifest' failed because of too many requests (429).
    at UserDataSyncStoreService.request (file:///Users/sandy081/work/vscode/out/vs/platform/userDataSync/common/userDataSyncStoreService.js:265:19)
    at async UserDataSyncStoreService.manifest (file:///Users/sandy081/work/vscode/out/vs/platform/userDataSync/common/userDataSyncStoreService.js:173:29)
    at async UserDataSyncService.createSyncTask (file:///Users/sandy081/work/vscode/out/vs/platform/userDataSync/common/userDataSyncService.js:97:28)
    at async AutoSync.doSync (file:///Users/sandy081/work/vscode/out/vs/platform/userDataSync/common/userDataAutoSyncService.js:323:33)
[2020-07-20 19:02:33.735] [userDataSync] [info] Auto Sync: Started
[2020-07-20 19:02:33.735] [userDataSync] [info] Auto Sync: Triggered by Interval
```

**Comment by sandy081** [comment]
@Tyriar Can you please verify ?
