### ISSUE TITLE
SCM: View becomes empty, with errors in dev tools

### ISSUE THREAD

**Issue by Sharleedah** [microsoft/vscode#102358]
Issue Type: <b>Bug</b>

Since the new design of the source control has been introduced (old one was way better) VSC has a problem loading all gitlab repos after pushing once. The source control is then completely empty and if i try to sort new, an error pops up "template could not be loaded"

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.6
vscode-html-css|ecm|0.2.3
code-runner|for|0.11.0
pythonsnippets|frh|1.0.2
git-graph|mhu|1.24.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
markdown-preview-enhanced|shd|0.5.12
vscode-counter|uct|2.0.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by skyselang** [comment]
I also have this problem！

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/) of the issue?

**Comment by Sharleedah** [comment]
After pushing my source control tab looks like this:
![image](https://user-images.githubusercontent.com/46475675/87307263-8c7bcf80-c519-11ea-9161-4fadef0fb96c.png)

Btw. is there a way to get to the old view? After reopening my VSC it looks like this:
![image](https://user-images.githubusercontent.com/46475675/87307317-a9b09e00-c519-11ea-9e33-ce796d294ff5.png)

**Comment by joaomoreno** [comment]
> After pushing my source control tab looks like this:

Can you reproduce this consistently? It happens right after you push? What button/action do you run/click to push? Can you show me the output of `Developer: Toggle Developer Tools`, the `Console` tab?

**Comment by hunter86bg** [comment]
It happens at least once per hour.

**Comment by joaomoreno** [comment]
It happens right after you push? What button/action do you run/click to push? Can you show me the output of `Developer: Toggle Developer Tools`, the `Console` tab?

**Comment by Sharleedah** [comment]
Unfortunately i does not happen every single time. But like @hunter86bg  it happens like once or more per hour.
Buttons:
- Commit: hook symbol next to the repo name 
- push: upload/download sign in the left lower corner, which appears, when commits/pulls are not merged yet.

Is it possible to change back to an old version of the source-control? @joaomoreno  (in case you know that)

**Comment by joaomoreno** [comment]
It would be great to keep you running in this version, so you get me more information since I can't reproduce it. Giving me more information will lead to a fix as soon as possible. The sooner the better.

> Can you show me the output of `Developer: Toggle Developer Tools`, the `Console` tab?

Can you make sure you do this next time it occurs?

**Comment by rohmanhm** [comment]
![image](https://user-images.githubusercontent.com/7524911/87320460-290f9300-c555-11ea-823e-6329ee577266.png)

I'm getting this as well.

After committing my changes and navigate through the Activity bar and get back to the activity source control.

**Comment by joaomoreno** [comment]
@rohmanhm Can you show me the output of `Developer: Toggle Developer Tools`, the `Console` tab?

**Comment by hunter86bg** [comment]
Console output is very long:
```
ERR name must not be falsy: Error: name must not be falsy
	at Function.validate (c:\Users\MYUSER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:442:18)
	at new x (c:\Users\MYUSER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:441:950)
	at new x (c:\Users\MYUSER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:429:327)
	at asSymbolInformation (c:\Users\MYUSER\.vscode\extensions\vscoss.vscode-ansible-0.5.2\node_modules\vscode-languageclient\lib\protocolConverter.js:251:22)
	at c:\Users\MYUSER\.vscode\extensions\vscoss.vscode-ansible-0.5.2\node_modules\vscode-languageclient\lib\protocolConverter.js:247:42
	at Array.map (<anonymous>)
	at asSymbolInformations (c:\Users\MYUSER\.vscode\extensions\vscoss.vscode-ansible-0.5.2\node_modules\vscode-languageclient\lib\protocolConverter.js:247:23)
log.ts:197   ERR Cannot read property 'domNode' of null: TypeError: Cannot read property 'domNode' of null
    at E.updateItemInDOM (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:512:636)
    at E.render (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:510:905)
    at E.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:377)
    at O.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:655)
    at Object.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:119:927)
    at t.IndexTreeModel.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:104:685)
    at t.ObjectTreeModel.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:112:728)
    at c.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:118:686)
    at t.CompressibleObjectTreeModel.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:121:776)
    at B.updateElementHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1112:242)
    at e.updateHeight (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7256:98)
    at a (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7229:214)
    at l (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7229:316)
    at e.renderElement (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7229:443)
    at c.renderElement (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1112:937)
    at x.renderElement (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1084:219)
    at W.renderElement (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:541:312)
    at E.insertItemInDOM (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:511:912)
    at E._splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:508:54)
    at E.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:699)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:565
    at t.EventBufferer.bufferEvents (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:214)
    at O.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:532)
    at O.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1097:878)
    at Object.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:119:868)
    at t.IndexTreeModel.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:104:116)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:499)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:371)
    at c._setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:117:159)
    at c.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:409)
    at t.CompressibleObjectTreeModel.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:120:771)
    at B.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1114:255)
    at Oe.refresh (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7241:820)
    at Oe._onDidSpliceGroup (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7240:808)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7240:375
    at c.fire (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at g.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4227:431)
    at e.$spliceGroupResourceStates (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4229:957)
    at f.$spliceResourceStates (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4232:76)
    at p._doInvokeHandler (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4258:757)
    at p._invokeHandler (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4258:449)
    at p._receiveRequest (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4257:120)
    at p._receiveOneMessage (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4255:970)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4254:161
    at c.fire (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at v.fire (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:430:733)
    at t.PersistentProtocol._receiveMessage (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:435:38)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:432:243
    at c.fire (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at g.acceptChunk (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:428:234)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:427:604
    at Socket.t (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:436:655)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
log.ts:197   ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at E.removeItemFromDOM (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:513:504)
    at E._splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:964)
    at E.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:699)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:565
    at t.EventBufferer.bufferEvents (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:214)
    at O.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:532)
    at O.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1097:878)
    at Object.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:119:868)
    at t.IndexTreeModel.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:104:116)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:499)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:371)
    at c._setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:117:159)
    at c.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:409)
    at t.CompressibleObjectTreeModel.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:120:771)
    at B.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1114:255)
    at Oe.refresh (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7241:820)
    at Oe._onDidSpliceRepositories (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7239:1004)
    at Oe.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7241:531)
    at c.fire (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:821)
    at Ge.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6387:92)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:328
    at Array.map (<anonymous>)
    at y.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:319)
    at i.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3903:24)
    at e.hideActiveComposite (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5755:399)
    at e.hideActiveViewlet (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6346:218)
    at O.setSideBarHidden (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6376:477)
    at e.run (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6178:841)
    at s.runAction (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:740)
    at s.run (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:598)
    at e.onClick (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:974:176)
    at Immediate._onImmediate (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:973:727)
    at processImmediate (internal/timers.js:439:21)
log.ts:197   ERR Cannot read property 'domNode' of null: TypeError: Cannot read property 'domNode' of null
    at E.updateItemInDOM (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:512:636)
    at E._splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:507:744)
    at E.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:699)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:565
    at t.EventBufferer.bufferEvents (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:214)
    at O.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:532)
    at O.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1097:878)
    at Object.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:119:868)
    at t.IndexTreeModel.splice (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:104:116)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:499)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:371)
    at c._setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:117:159)
    at c.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:409)
    at t.CompressibleObjectTreeModel.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:120:771)
    at B.setChildren (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1114:255)
    at Oe.refresh (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7241:820)
    at Oe._onDidSpliceRepositories (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7239:1004)
    at Oe.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7240:984)
    at c.fire (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:821)
    at Ge.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6387:92)
    at file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:328
    at Array.map (<anonymous>)
    at y.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:319)
    at i.setVisible (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3903:24)
    at e.showComposite (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5753:975)
    at e.doOpenComposite (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5751:1007)
    at e.openComposite (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5751:539)
    at e.doOpenViewlet (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6346:900)
    at e.openViewlet (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6346:313)
    at e.run (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6178:913)
    at s.runAction (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:740)
    at s.run (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:598)
    at e.onClick (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:974:176)
    at Immediate._onImmediate (file:///C:/Users/MYUSER/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:973:727)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by hunter86bg** [comment]
It seems that the first line has a missing info:
```
ERR name must not be falsy: Error: name must not be falsy log.ts:197
	at Function.validate 
```
![VSC_debug_console](https://user-images.githubusercontent.com/22281444/87391235-06ac6280-c5b3-11ea-899e-eb926061ab23.jpg)

**Comment by hunter86bg** [comment]
[VSC-console.log](https://github.com/microsoft/vscode/files/4916928/VSC-console.log)

**Comment by hunter86bg** [comment]
[VSC-console.log](https://github.com/microsoft/vscode/files/4916935/VSC-console.log)

**Comment by joaomoreno** [comment]
Perfect, thanks @hunter86bg!

**Comment by qt1** [comment]
Why would anyone take a good design and break it?

How could this be prevented in future?
