### ISSUE TITLE
TS format doc error

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102506]
- Open remoteExtensionHostAgent.js
- Format document
- Got this error:

```
  ERR <syntax> TypeScript Server Error (3.9.6)
Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
Error: Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
    at addSyntheticNodes (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137852:30)
    at createChildren (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137841:9)
    at NodeObject.getChildren (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137785:56)
    at Object.findChildOfKind (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:108381:26)
    at spanForNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120329:36)
    at getOutliningSpanForNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120275:28)
    at visitNonImportNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120122:28)
    at visitNodes (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:18804:30)
    at Object.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:19035:24)
    at NodeObject.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137808:23)
    at visitNonImportNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120142:23)
    at visitNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:18795:24)
    at Object.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:18925:21)
    at NodeObject.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137808:23)
    at visitNonImportNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120142:23)
    at visitNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:18795:24)
    at Object.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:18998:24)
    at NodeObject.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137808:23)
    at visitNonImportNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120142:23)
    at Array.forEach (<anonymous>)
    at visitNonImportNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120130:33)
    at visitNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:18795:24)
    at Object.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:19017:21)
    at NodeObject.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137808:23)
    at visitNonImportNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:120142:23)
    at visitNode (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:18795:24)
    at Object.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:19015:24)
    at NodeObject.forEachChild (c:\Users\roblou\.vscode-server-insiders\bin\c828a5339bca7222fd8f56ab98361a98f736d185\extensions\node_modules\typescript\lib\tsserver.js:137808:23)
```

**Comment by mjbvz** [comment]
Same error stack as https://github.com/microsoft/TypeScript/issues/35133

I can't repo this though with my local copy of `remoteExtensionHostAgent.js`. @roblourens Did you modify the file in any way before running format?

**Comment by roblourens** [comment]
No

**Comment by roblourens** [comment]
[remoteExtensionHostAgent.js.txt](https://github.com/microsoft/vscode/files/4923083/remoteExtensionHostAgent.js.txt)

**Comment by mjbvz** [comment]
I can't repo this using the latest TS 4.0 nightlies so I'm guessing it is fixed. Let me know if you see this with TS 4.0+
