### ISSUE TITLE
Extension host crash

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#102649]
Since few update vscode start crash in random time
How i can isolate the extensions that's make crash the extensions host ?
Any verbose setting ?
This happen in random time from `ctrl+z` (sometime 1 houre) , and i have too many extensions to try disabling one by one
![image](https://user-images.githubusercontent.com/24865815/87610306-01ded000-c6d3-11ea-95c4-fdc55368c6d3.png)

Restart host work, but it boring.

```cmd
console.ts:137 [Extension Host] (node:18820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 449)
t.log @ console.ts:137
log.ts:197   ERR Cannot read property 'peekBack' of undefined: TypeError: Cannot read property 'peekBack' of undefined
	at IndentSpy._peekBack (c:\Users\InformatiqueLepage\.vscode\extensions\SirTori.indenticator-0.6.0\out\src\extension.js:250:28)
	at IndentSpy._buildHoverString (c:\Users\InformatiqueLepage\.vscode\extensions\SirTori.indenticator-0.6.0\out\src\extension.js:234:35)
	at IndentSpy._buildHoverprovider (c:\Users\InformatiqueLepage\.vscode\extensions\SirTori.indenticator-0.6.0\out\src\extension.js:215:28)
	at Object.provideHover (c:\Users\InformatiqueLepage\.vscode\extensions\SirTori.indenticator-0.6.0\out\src\extension.js:205:29)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:668:818
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:51:761
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:51:733)
	at C.provideHover (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:668:789)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:689:572
	at K._withAdapter (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:499)
	at K.$provideHover (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:689:550)
	at m._doInvokeHandler (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:683)
	at m._invokeHandler (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:375)
	at m._receiveRequest (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:953)
	at m._receiveOneMessage (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:832)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:34
	at l.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:744
	at l.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
	at t.PersistentProtocol._receiveMessage (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:276)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:237:357
	at l.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at p.acceptChunk (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:393)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:753
	at Socket.t (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:241:826)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
2console.ts:137 [Extension Host] Command failed: git config --get remote.origin.url
console.ts:137 [Extension Host] swdc-vscode: storing kpm metrics
abstractExtensionService.ts:166 Extension host terminated unexpectedly. Code:  1  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:166
notificationsAlerts.ts:40 L'hôte d’extension s'est arrêté de manière inattendue.
onDidChangeNotification @ notificationsAlerts.ts:40
localProcessExtensionHost.ts:233 Extension Host
localProcessExtensionHost.ts:234 c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:465
getWordRangeAtPosition:(t,i)=>e._getWordRangeAtPosition(t,i)}}return Object.freeze(this._document)}_acceptLanguageId(e){i.ok(!this._isDisposed),this._languageId=e}_acceptIsDirty(e){i.ok(!this._isDisposed),this._isDirty=e}_save(){return this._isDisposed?Promise.reject(new Error("Document has been closed")):this._proxy.$trySaveDocument(this._uri)}_getTextInRange(e){const t=this._validateRange(e);if(t.isEmpty)return"";if(t.isSingleLine)return this._lines[t.start.line].substring(t.start.character,t.end.character);const i=this._eol,n=t.start.line,r=t.end.line,o=[];o.push(this._lines[n].substring(t.start.character));for(let e=n+1;e<r;e++)o.push(this._lines[e]);return o.push(this._lines[r].substring(0,t.end.character)),o.join(i)}_lineAt(e){let t;if(e instanceof a.Position?t=e.line:"number"==typeof e&&(t=e),"number"!=typeof t||t<0||t>=this._lines.length||Math.floor

[Error: Illegal value for `line`
	at d._lineAt (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:465:884)
	at Object.lineAt (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:464:823)
	at DocumentDecoration.updateScopeDecorations (c:\Users\InformatiqueLepage\.vscode\extensions\coenraads.bracket-pair-colorizer-1.0.61\out\src\documentDecoration.js:186:64)
	at Timeout._onTimeout (c:\Users\InformatiqueLepage\.vscode\extensions\coenraads.bracket-pair-colorizer-1.0.61\out\src\documentDecoration.js:133:18)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]

```

---

Version : 1.47.1 (user setup)
Commit : 485c41f9460bdb830c4da12c102daff275415b53
Date : 2020-07-13T22:42:53.386Z
Electron : 7.3.2
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Windows_NT x64 10.0.19041

**Comment by IllusionMH** [comment]
From your log `.vscode\extensions\SirTori.indenticator-0.6.0\out\src\extension.js:250:28`

Have you tried to disable `SirTori.indenticator-0.6.0` extension?
