### ISSUE TITLE
TS Server fatal error:  re.test is not a function

### ISSUE THREAD

**Issue by POPOEVER** [microsoft/vscode#102673]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.6

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
TypeError: re.test is not a function
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29016:103
    at Object.findIndex (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:289:17)
    at _loop_5 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29016:43)
    at getFileNamesFromConfigSpecs (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29046:17)
    at matchFileNames (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:28964:16)
    at getFileNames (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:28513:26)
    at parseJsonConfigFileContentWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:28445:18)
    at Object.parseJsonSourceFileConfigFileContent (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:28403:16)
    at parseProjectReferenceConfigFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101806:34)
    at Array.map (<anonymous>)
    at Object.createProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:99982:67)
    at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138753:26)
    at Proxy.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138845:13)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143337:53)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143280:42)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:144074:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:145727:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146608:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146927:97
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:147790:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149544:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149577:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:150893:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|7.1.2
angular1-code-snippets|ale|0.0.3
vscode-sqlite|ale|0.8.2
ng-template|Ang|0.1000.4
nestjs|ash|1.4.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-eslint|dba|2.1.8
vscode-deno|den|1.25.0
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
auto-rename-tag|for|0.1.4
terminal|for|0.0.10
rest-client|hum|0.24.1
composer-support-client|Hyp|0.19.12
svelte-vscode|Jam|0.9.3
angular-essentials|joh|9.0.1
Angular1|joh|0.2.1
Angular2|joh|9.1.2
pwa-tools|joh|0.1.0
vscode-peacock|joh|3.7.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
vscode-language-pack-zh-hans|MS-|1.47.3
python|ms-|2020.6.91350
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
awesome-flutter-snippets|Nas|2.0.4
angular2-inline|nat|0.0.17
vscode-gatsby-snippets|nic|1.1.2
angular-console|nrw|12.0.0
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
polacode|pnp|0.3.4
minapp-vscode|qiu|2.2.2
quicktype|qui|12.0.46
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
rust|rus|0.7.8
stylelint|shi|0.51.0
bootstrap4-vscode|the|6.1.0
python|tht|0.2.3
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.1.0

(5 theme extensions excluded)

</details>

**Comment by POPOEVER** [comment]
ts/js intellisense gone

**Comment by mjbvz** [comment]
Please fill in the issue template to the best of your ability

/needsMoreInfo

**Comment by POPOEVER** [comment]
> Please fill in the issue template to the best of your ability
> 
> /needsMoreInfo

I thought this bug report is generated by vs code, should be informative enough, sorry about that, here you go.







- VSCode Version: 1.47.1
- OS Version: macOS 10.14.6 (18G5033)

Steps to Reproduce:

1. Open TS project in vs code, the TypeScript and JavaScript Language Service will stop after 5 tries of enabling
2. Then, TS/JS IntelliSense gone


Does this issue occur when all extensions are disabled?: No.

**Comment by mjbvz** [comment]
So disabling extensions fixes this? This sounds like it could be cause the the vscode-deno extension. Can you please check to see if enabling it cause the problem

**Comment by POPOEVER** [comment]
> So disabling extensions fixes this? This sounds like it could be cause the the vscode-deno extension. Can you please check to see if enabling it cause the problem

Yep, but I don't think it's deno, it set itself disabled in workspace settings when I initiated the project. 

I tried to remove tsdk key in settings, then open with --disable-extensions, it's ok, then reopen code with full feature, it remains fine, and tsdk path was added to my workspace settings automatically instead of being added to general settings.
