### ISSUE TITLE
[exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by AlexBillon07** [microsoft/vscode#102751]
Issue Type: <b>Bug</b>

Hello,

Most of my extensions doesn't work any more. I always have the same error in the Extension Host logs : `[exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`

```log
[2020-07-17 09:04:03.877] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.powershell {"startup":false,"extensionId":{"value":"ms-vscode.powershell","_lower":"ms-vscode.powershell"},"activationEvent":"onLanguage:powershell"}
[2020-07-17 09:04:03.877] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/adm-a.billon/.vscode/extensions/ms-vscode.powershell-2020.6.0/out/src/main
[2020-07-17 09:04:03.879] [exthost] [error] Activating extension ms-vscode.powershell failed due to an error:
[2020-07-17 09:04:03.879] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at Function.Module._nodeModulePaths (internal/modules/cjs/loader.js:590:37)
	at Module.load (internal/modules/cjs/loader.js:777:23)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:176
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
overtype|ada|0.2.0
vscode-edifact|DAX|0.6.0
xml|Dot|2.5.0
gitlens|eam|10.2.2
reg|ion|1.0.1
rainbow-csv|mec|1.7.0
csharp|ms-|1.22.1
powershell|ms-|2020.6.0
vscode-hexdump|sle|1.7.2
poor-mans-t-sql-formatter-vscode|Tao|1.6.10
vscode-icons|vsc|10.2.0
vsc-jsonsnippets|wmo|0.7.0

</details>

**Comment by AlexBillon07** [comment]
I was running VSCode with different user that opened the Windows session.

I opened a session on my station launched VScode with this user and it resolved my issue.

**Comment by roblourens** [comment]
Can you explain what you mean by running vscode with a different user than the one that opened the session? Looking for clues to https://github.com/microsoft/vscode/issues/102642

**Comment by AlexBillon07** [comment]
My OS is Windows 10. I log on with a domain user "a.billon".
When I run VSCode, I run it with a different user (adm-a.billon) and with elevated elevated privileges as I need different rights to connect to shares or SQL servers. 

Hope this helps.

**Comment by roblourens** [comment]
I think we made some progress on https://github.com/microsoft/vscode/issues/102642, if that's the same issue you were having, and a fix should be coming down the line in case you hit it again.
