### ISSUE TITLE
Have to wait for debugger to timeout before rerunning tests

### ISSUE THREAD

**Issue by brucedjones** [microsoft/vscode#102780]
- VSCode Version: 1.47.2
- OS Version: MacOS 10.15.4

Steps to Reproduce:

I'm debugging mocha tests with the following launch configuration
```javascript
{
            "name": "Mocha All",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "cwd": "${workspaceRoot}",
            "args": [
                "--timeout",
                "999999",
                "--colors",
                "--recursive",
                "${workspaceFolder}/profiling/test",
            ],
            "sourceMaps": true,
            "stopOnEntry": false,
            "smartStep": false,
            "runtimeVersion" : "10.20.1",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
```

1. Run the above configuration
2. Tests complete and process appears to exit
3. However the debug controls stay open, hitting stop or restart does nothing except show a "timeout after 1000ms" message
4. After about 30s the debug controls go away and I am able to run the tests again
5. Console output appears to show the process/debugger has exited:
```bash
Waiting for the debugger to disconnect...
bash-3.2$ 
```

Terminating running tests also results in some strange behaviour. I get another "timeout after 1000 ms" message, and then after maybe 5-10s the tests do terminate

Does this issue occur when all extensions are disabled?: Yes

**Comment by brucedjones** [comment]
Some more information, while the debugger appears to be hanging, other issues appear, for example I can't load a git diff view until the debugger finally times out.

I see the following in the "Show running extensions" view:
![Screen Shot 2020-07-17 at 8 42 02 AM](https://user-images.githubusercontent.com/1107675/87787507-be3ab200-c809-11ea-99f5-3d6a1d40733b.png)

And Log(Window) shows the following:
```
[2020-07-17 08:15:47.579] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 76% of 6600.42ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-2e74d7.cpuprofile' [{"id":"gc","total":53150,"percentage":1},{"id":"ms-vscode.js-debug","total":4993409,"percentage":76},{"id":"program","total":1552309,"percentage":24},{"id":"self","total":1316,"percentage":0}]
[2020-07-17 08:16:01.551] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3173:226)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3172:532
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3170:536)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6614:715
[2020-07-17 08:16:08.770] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 99% of 5090.7ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-be4e02.cpuprofile' [{"id":"gc","total":26682,"percentage":1},{"id":"ms-vscode.js-debug","total":5062672,"percentage":99},{"id":"program","total":479,"percentage":0},{"id":"self","total":641,"percentage":0}]
[2020-07-17 08:16:08.908] [renderer1] [error] Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1875:762)
    at b (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:620)
    at async y._processCpuProfile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4285:325)
[2020-07-17 08:16:59.680] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 99% of 5078.766ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-c7b1d9.cpuprofile' [{"id":"gc","total":45168,"percentage":1},{"id":"ms-vscode.js-debug","total":5030759,"percentage":99},{"id":"program","total":2149,"percentage":0},{"id":"self","total":432,"percentage":0}]
[2020-07-17 08:16:59.856] [renderer1] [error] Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1875:762)
    at b (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:620)
    at async y._processCpuProfile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4285:325)
[2020-07-17 08:17:22.452] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 99% of 5119.159ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-8e8b65.cpuprofile' [{"id":"gc","total":26135,"percentage":1},{"id":"ms-vscode.js-debug","total":5092359,"percentage":99},{"id":"program","total":256,"percentage":0},{"id":"self","total":273,"percentage":0}]
[2020-07-17 08:17:22.510] [renderer1] [error] Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1875:762)
    at b (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:620)
    at async y._processCpuProfile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4285:325)
[2020-07-17 08:18:43.619] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3173:226)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3172:532
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3170:536)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6614:715
[2020-07-17 08:18:52.011] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 99% of 5177.013ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-460543.cpuprofile' [{"id":"gc","total":35957,"percentage":1},{"id":"ms-vscode.js-debug","total":5139494,"percentage":99},{"id":"program","total":418,"percentage":0},{"id":"self","total":933,"percentage":0}]
[2020-07-17 08:18:52.152] [renderer1] [error] Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1875:762)
    at b (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:620)
    at async y._processCpuProfile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4285:325)
[2020-07-17 08:21:37.852] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 98% of 5115.211ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-ad1d70.cpuprofile' [{"id":"gc","total":36596,"percentage":1},{"id":"ms-vscode.js-debug","total":4997241,"percentage":98},{"id":"program","total":79863,"percentage":2},{"id":"self","total":1444,"percentage":0}]
[2020-07-17 08:21:52.219] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3173:226)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3172:532
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3170:536)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6614:715
[2020-07-17 08:21:59.445] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 99% of 5093.447ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-eca79b.cpuprofile' [{"id":"gc","total":22889,"percentage":0},{"id":"ms-vscode.js-debug","total":5018615,"percentage":99},{"id":"program","total":51183,"percentage":1},{"id":"self","total":518,"percentage":0}]
[2020-07-17 08:21:59.889] [renderer1] [error] Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1875:762)
    at b (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:620)
    at async y._processCpuProfile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4285:325)
[2020-07-17 08:23:27.107] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 99% of 7711.34ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-31f368.cpuprofile' [{"id":"gc","total":62410,"percentage":1},{"id":"ms-vscode.js-debug","total":7646887,"percentage":99},{"id":"program","total":642,"percentage":0},{"id":"self","total":1238,"percentage":0}]
[2020-07-17 08:23:27.353] [renderer1] [error] Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1875:762)
    at b (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:620)
    at async y._processCpuProfile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4285:325)
[2020-07-17 08:41:33.620] [renderer1] [warning] {}
[2020-07-17 08:41:35.174] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 70% of 7171.238ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-181e88.cpuprofile' [{"id":"gc","total":55769,"percentage":1},{"id":"ms-vscode.js-debug","total":4995928,"percentage":70},{"id":"program","total":2119114,"percentage":30},{"id":"self","total":347,"percentage":0}]
[2020-07-17 08:41:49.514] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3173:226)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3172:532
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3170:536)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6614:715
[2020-07-17 08:41:57.222] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 99% of 5141.131ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-b448bc.cpuprofile' [{"id":"gc","total":32116,"percentage":1},{"id":"ms-vscode.js-debug","total":5108112,"percentage":99},{"id":"program","total":129,"percentage":0},{"id":"self","total":665,"percentage":0}]
[2020-07-17 08:41:57.410] [renderer1] [error] Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1875:762)
    at b (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:620)
    at async y._processCpuProfile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4285:325)

```

**Comment by brucedjones** [comment]
More findings. If I set a breakpoint then the breakpoint is never hit and the whole thing just hangs endlessly.

**Comment by brucedjones** [comment]
Yet more findings. The code I'm debugging is sourcemapped coffeescript. If I set `"sourceMaps": false` in my launch config I don't experience these problems, but then I am in a position where I have to interpret the compiled JS rather than working with the source directly.

**Comment by connor4312** [comment]
Thanks for the issue! Can you do two things?

1. In the logs where it says `[2020-07-17 08:15:47.579] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug' took 76% of 6600.42ms, saved PROFILE here: '/var/folders/9p/67bhbg6x1qz33l29rdyqg3tw0000gp/T/exthost-2e74d7.cpuprofile' ...`, can you share that profile file?
2. With a breakpoint set, collect trace logs using the following instrictions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

Alternatively, if this is an open source project, you can link to it so that I can reproduce the issue locally. Thanks! 🙂 

/needsMoreInfo

**Comment by brucedjones** [comment]
Profile file is here: https://drive.google.com/file/d/1Bj6bIEwTX_De5IOKr5toHzCieIhJxePi/view?usp=sharing

This is a work project so I am unable to provide the trace until i have anonymized it. I will have a look at setting up a minimum working example on monday. In the mean time I found these errors in the trace
```
{"tag":"cdp.receive","timestamp":1595020344419,"metadata":{"connectionId":14,"message":{"error":{"code":-32601,"message":"'Network.enable' wasn't found"},"id":3}},"level":0}
```
and
```
{"tag":"cdp.receive","timestamp":1595020345913,"metadata":{"connectionId":14,"message":{"error":{"code":-32601,"message":"'Debugger.setInstrumentationBreakpoint' wasn't found"},"id":7}},"level":0}
```

**Comment by connor4312** [comment]
Thanks for the profile, I'll take a look at that later today!

Those errors are expected in Node -- debugging functionality that Node doesn't have.

**Comment by connor4312** [comment]
Okay, thanks for the profile. You should be able to avoid this code path by setting `resolveSourceMapLocations: null`; let me know if that works for you and if so I can make a change to optimize that code path.

**Comment by brucedjones** [comment]
Wonderful that seems to have done the trick! Thanks for your help.

**Comment by brucedjones** [comment]
Note I was skeptical due to the following warning:
![Screen Shot 2020-07-20 at 6 24 21 AM](https://user-images.githubusercontent.com/1107675/87927748-b3725e00-ca51-11ea-9968-25e0614847dc.png)

**Comment by connor4312** [comment]
Thanks for the confirmation! Will be fixed in the [next nightly](https://github.com/microsoft/vscode-js-debug/#nightly-extension)
