### ISSUE TITLE
Notebook integration tests depend on window being visible

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102899]
I cannot run the integration tests on macOS and leave the window in the background, there is a ton of exceptions and failures:

``` notebook dirty state
    1) notebook open
  notebook undo redo
    2) notebook open
    - execute and then undo redo
  notebook working copy
rejected promise not handled within 1 second: Error: Not Implemented: document->Symbol(Symbol.toStringTag)
stack trace: Error: Not Implemented: document->Symbol(Symbol.toStringTag)
    at Object.get (/Users/bpasero/Development/Microsoft/vscode-electron-7.0.x/out/vs/base/common/file:/Users/bpasero/Development/Microsoft/vscode-electron-7.0.x/src/vs/base/common/types.ts:278:12)
    at Proxy.toString (<anonymous>)
    at type (/Users/bpasero/Development/Microsoft/vscode-electron-7.0.x/extensions/vscode-notebook-tests/node_modules/vscode/node_modules/mocha/lib/utils.js:269:6)
    at Object.canonicalize (/Users/bpasero/Development/Microsoft/vscode-electron-7.0.x/extensions/vscode-notebook-tests/node_modules/vscode/node_modules/mocha/lib/utils.js:437:26)
    at /Users/bpasero/Development/Microsoft/vscode-electron-7.0.x/extensions/vscode-notebook-tests/node_modules/vscode/node_modules/mocha/lib/utils.js:481:45
    at Array.forEach (<anonymous>)
    at /Users/bpasero/Development/Microsoft/vscode-electron-7.0.x/extensions/vscode-notebook-tests/node_modules/vscode/node_modules/mocha/lib/utils.js:480:12
```

Also often I see this error:

```
Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: Invalid guestInstanceId: 26: Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: Invalid guestInstanceId: 26
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.invoke (electron/js2c/renderer_init.js:2525:19)
```

**Comment by rebornix** [comment]
Commands used in the notebook integration tests which depend on window focus

* `workbench.action.files.revert` (won't finish if window has no focus)
* `workbench.action.revertAndCloseActiveEditor` (won't finish if window has no focus)
* `default:type` (might affect `editorFocus`)

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/103054:

* avoid above commands
* use workspace edit other than `default:type`
