### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by JounQin** [microsoft/vscode#102891]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200717

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`/Users/JounQin/Library/Application Support/Code/logs/20200717T111438/exthost5/vscode.typescript-language-features/tsserver-log-nTJzXY/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:106982:26)
    at resolveNamesWithLocalCache (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:106844:21)
    at Object.resolveModuleNames (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:106898:20)
    at InferredProject.Project.resolveModuleNames (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:147524:45)
    at actualResolveModuleNamesWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102521:133)
    at resolveModuleNamesWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102741:26)
    at resolveModuleNamesReusingOldState (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102815:24)
    at processImportedModules (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104314:35)
    at findSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104050:17)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102621:60
    at Object.forEach (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102621:16)
    at synchronizeHostData (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:143149:26)
    at Proxy.getProgram (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:143237:13)
    at Proxy.proxy.<computed> (/Users/JounQin/.vscode/extensions/asvetliakov.snapshot-tools-0.4.0/node_modules/typescript-snapshots-plugin/out/index.js:38:33)
    at InferredProject.Project.updateGraphWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:148058:53)
    at InferredProject.Project.updateGraph (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:147991:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:150005:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151512:26)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151773:97
    at Object.flatMap (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151773:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:152754:46)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154609:88
    at IOSession.Session.executeWithRequestId (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154600:28)
    at IOSession.Session.executeCommand (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154609:33)
    at IOSession.Session.onMessage (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154633:35)
    at Interface.<anonymous> (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:156848:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (26.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
jest-snippets|and|1.8.0
ng-template|Ang|0.1000.4
snapshot-tools|asv|0.4.0
multi-cursor-case-preserve|Car|1.0.5
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
plantuml|jeb|2.13.12
docthis|joe|0.7.1
Angular2|joh|9.1.2
alauda-snippets|Jou|0.3.0
vscode-mdx|Jou|0.1.4
intellij-idea-keybindings|k--|0.2.41
vscode-language-babel|mgm|0.0.29
Angular-BeastCode|Mik|8.1.2
vscode-language-pack-zh-hans|MS-|1.47.3
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.0.20200717
vscode-typescript-tslint-plugin|ms-|1.2.3
color-highlight|nau|2.3.0
vetur|oct|0.24.0
vscode-yaml|red|0.9.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.6.0
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.84.0
tabnine-vscode|Tab|2.8.10
vscode-icons|vsc|10.2.0
vscode-wakatime|Wak|4.0.0
change-case|wma|1.0.0
yao-translate|Yao|1.0.1
dictionary-completion|yzh|0.9.1
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by JounQin** [comment]
The content of this issue is created by VSCode itself.
