### ISSUE TITLE
Exception has occurred: Error: ENOENT: no such file or directory, open '/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/google/protobuf/google/protobuf/source_context.proto'

### ISSUE THREAD

**Issue by SeanDez** [microsoft/vscode#102810]
- VSCode Version: $ code 
```
--version
1.47.1
485c41f9460bdb830c4da12c102daff275415b53
x64
```
- OS Version: Lubuntu 20.04

Steps to Reproduce:

1. clone; https://github.com/SeanDez/foreignSentenceRepeater
2. run `npm i` to pull deps
3. run `tsc` in terminal (the preLaunchTask is having its own issue, so is commented out)
4. Go to the Run view with CTRL SHIFT D, select `-b` and run this configuration. You should then see the debugger error below from a node_modules library.

```
Exception has occurred: Error: ENOENT: no such file or directory, open '/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/google/protobuf/google/protobuf/source_context.proto'
  at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at fetch (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:162:34)
    at process (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:123:29)
    at fetch (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:168:13)
    at Root.load (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:196:13)
    at Root.loadSync (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:237:17)
    at Object.loadSync (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/index-light.js:69:17)
    at Object.<anonymous> (/home/owner/cp/foreignSentenceRepeater/node_modules/@grpc/proto-loader/build/src/index.js:230:37)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by SeanDez** [comment]
I have been debugging my app successfully in another debugger called NDB. Further along the debug process, I tried VSCode again. The error messages are a little different although they appear to trace back to the same node library:

https://imgur.com/y3fNig2

```
Exception has occurred: Error: ENOENT: no such file or directory, open '/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/google/protobuf/google/protobuf/source_context.proto'
  at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at fetch (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:162:34)
    at process (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:123:29)
    at fetch (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:168:13)
    at Root.load (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:196:13)
    at Root.loadSync (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/root.js:237:17)
    at Object.loadSync (/home/owner/cp/foreignSentenceRepeater/node_modules/protobufjs/src/index-light.js:69:17)
    at Object.<anonymous> (/home/owner/cp/foreignSentenceRepeater/node_modules/@grpc/proto-loader/build/src/index.js:230:37)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
```

The process to duplicate the error should be the same, as the repo has been updated.

**Comment by connor4312** [comment]
This is because you have the debugger set to pause on "caught exceptions". It appears that protobufjs generates a caught exception in the course of loading its proto files.
