### ISSUE TITLE
vscode API - terminal Terminal creationOptions should be set and readonly for TerminalOptions terminals

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102950]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=49046&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=d494b5db-eef8-5766-984e-01186010c86f&l=328

```

      +  "_pidPromiseComplete": [undefined]
         "_proxy": {
           "$createTerminal": [Function]
           "$dispose": [Function]
           "$sendOverrideDimensions": [Function]
           "$startSendingDataEvents": [Function]
           "$stopSendingDataEvents": [Function]
         }
         "_queuedRequests": []
      -  "isOpen": false
      +  "_rows": 0
      +  "isOpen": true
       }
      
      at D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:156:6
      at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
      at ExtHostTerminalService.$acceptTerminalOpened (d:\a\1\s\out\vs\workbench\api\common\file:\D:\a\1\s\src\vs\workbench\api\common\extHostTerminalService.ts:462:27)
      at RPCProtocol._doInvokeHandler (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:402:17)
      at RPCProtocol._invokeHandler (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:387:32)
      at RPCProtocol._receiveRequest (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:303:19)
      at RPCProtocol._receiveOneMessage (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:230:10)
      at d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:105:42
      at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
      at BufferedEmitter.fire (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:453:19)
      at d:\a\1\s\out\vs\workbench\services\extensions\node\file:\D:\a\1\s\src\vs\workbench\services\extensions\node\extensionHostProcessSetup.ts:196:22
      at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
      at BufferedEmitter.fire (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:453:19)
      at PersistentProtocol._receiveMessage (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:733:21)
      at d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:592:73
      at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
      at ProtocolReader.acceptChunk (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:239:21)
      at d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:200:51
      at Socket.listener (d:\a\1\s\out\vs\base\parts\ipc\node\file:\D:\a\1\s\src\vs\base\parts\ipc\node\ipc.net.ts:28:38)
      at addChunk (_stream_readable.js:308:12)
      at readableAddChunk (_stream_readable.js:289:11)
      at Socket.push (_stream_readable.js:223:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)

```

**Comment by Tyriar** [comment]
```
2020-07-20T13:11:28.0659374Z   190 passing (52s)
2020-07-20T13:11:28.0663760Z   2 pending
2020-07-20T13:11:28.0664196Z   1 failing
2020-07-20T13:11:28.0664777Z   1) vscode API - terminal Terminal creationOptions should be set and readonly for TerminalOptions terminals:
2020-07-20T13:11:28.0665164Z 
2020-07-20T13:11:28.0665456Z       AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: ExtHostTerminal {
2020-07-20T13:11:28.0665915Z   _creationOptions: {
2020-07-20T13:11:28.0666182Z     hideFromUser: true,
2020-07-20T13:11:28.0666403Z     name: 'foo'
2020-07-20T13:11:28.0666612Z   },
2020-07-20T13:11:28.0666803Z   _disposed: false,
2020-07-20T13:11:28.0667050Z   _idPromise: Promise {
2020-07-20T13:11:28.0667259Z     <pending>
2020-07-20T13:11:28.0667457Z   },
2020-07-20T13:11:28.0667671Z   _idPromiseComplete: [Function],
2020-07-20T13:11:28.0667952Z   _name: 'foo',
2020-07-20T13:11:28.0668169Z   _pidPromise: Promise {
2020-07-20T13:11:28.0668642Z     <pending>
2020-07-20T13:11:28.0668822Z   },
2020-07-20T13:11:28.0669251Z   _pidPromiseComplete: [Function],
2020-07-20T13:11:28.0669546Z   _proxy: [Object: null prototype] {
2020-07-20T13:11:28.0670235Z     '$createTerminal': [Function],
2020-07-20T13:11:28.0670509Z     '$dispose': [Function],
2020-07-20T13:11:28.0670962Z     '$sendProcessData': [Function],
2020-07-20T13:11:28.0671229Z     '$sendText': [Function],
2020-07-20T13:11:28.0671551Z     '$setEnvironmentVariableCollection': [Function],
2020-07-20T13:11:28.0671886Z     '$show': [... == ExtHostTerminal {
2020-07-20T13:11:28.0672143Z   _creationOptions: {
2020-07-20T13:11:28.0672388Z     cwd: undefined,
2020-07-20T13:11:28.0672602Z     env: undefined,
2020-07-20T13:11:28.0672849Z     name: 'foo',
2020-07-20T13:11:28.0673066Z     shellArgs: [],
2020-07-20T13:11:28.0673411Z     shellPath: 'C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'
2020-07-20T13:11:28.0673721Z   },
2020-07-20T13:11:28.0673929Z   _disposed: false,
2020-07-20T13:11:28.0674132Z   _id: 6,
2020-07-20T13:11:28.0674358Z   _idPromise: Promise {
2020-07-20T13:11:28.0674555Z     6
2020-07-20T13:11:28.0674734Z   },
2020-07-20T13:11:28.0674918Z   _name: 'foo',
2020-07-20T13:11:28.0675158Z   _pidPromise: Promise {
2020-07-20T13:11:28.0675528Z     <pending>
2020-07-20T13:11:28.0675799Z   },
2020-07-20T13:11:28.0676033Z   _pidPromiseComplete: [Function],
2020-07-20T13:11:28.0676346Z   _proxy: [Object: null prototype] {
2020-07-20T13:11:28.0676630Z     '$createTerminal': [Function],
2020-07-20T13:11:28.0676925Z     '$dispose': [Function],
2020-07-20T13:11:28.0677200Z     '$sendProcessData': [Function],
2020-07-20T13:11:28.0677472Z     '$sendTe...
2020-07-20T13:11:28.0677694Z       + expected - actual
2020-07-20T13:11:28.0677889Z 
2020-07-20T13:11:28.0678057Z        {
2020-07-20T13:11:28.0678287Z       +  "_cols": 0
2020-07-20T13:11:28.0678670Z          "_creationOptions": {
2020-07-20T13:11:28.0678976Z       -    "hideFromUser": true
2020-07-20T13:11:28.0679249Z       +    "cwd": [undefined]
2020-07-20T13:11:28.0679538Z       +    "env": [undefined]
2020-07-20T13:11:28.0679792Z            "name": "foo"
2020-07-20T13:11:28.0680076Z       +    "shellArgs": []
2020-07-20T13:11:28.0680465Z       +    "shellPath": "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
2020-07-20T13:11:28.0680804Z          }
2020-07-20T13:11:28.0681047Z          "_disposed": false
2020-07-20T13:11:28.0681293Z          "_id": 6
2020-07-20T13:11:28.0681586Z          "_idPromise": "[object Promise]"
2020-07-20T13:11:28.0681900Z       -  "_idPromiseComplete": [undefined]
2020-07-20T13:11:28.0682204Z          "_name": "foo"
2020-07-20T13:11:28.0683818Z          "_pidPromise": "[object Promise]"
2020-07-20T13:11:28.0684211Z       -  "_pidPromiseComplete": [Function]
2020-07-20T13:11:28.0684530Z       +  "_pidPromiseComplete": [undefined]
2020-07-20T13:11:28.0684835Z          "_proxy": {
2020-07-20T13:11:28.0685105Z            "$createTerminal": [Function]
2020-07-20T13:11:28.0685420Z            "$dispose": [Function]
2020-07-20T13:11:28.0685797Z            "$sendOverrideDimensions": [Function]
2020-07-20T13:11:28.0686184Z            "$startSendingDataEvents": [Function]
2020-07-20T13:11:28.0686548Z            "$stopSendingDataEvents": [Function]
2020-07-20T13:11:28.0686811Z          }
2020-07-20T13:11:28.0687052Z          "_queuedRequests": []
2020-07-20T13:11:28.0687310Z       -  "isOpen": false
2020-07-20T13:11:28.0687572Z       +  "_rows": 0
2020-07-20T13:11:28.0687807Z       +  "isOpen": true
2020-07-20T13:11:28.0688038Z        }
2020-07-20T13:11:28.0688208Z       
2020-07-20T13:11:28.0688608Z       at D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:156:6
2020-07-20T13:11:28.0689330Z       at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
2020-07-20T13:11:28.0690506Z       at ExtHostTerminalService.$acceptTerminalOpened (d:\a\1\s\out\vs\workbench\api\common\file:\D:\a\1\s\src\vs\workbench\api\common\extHostTerminalService.ts:462:27)
2020-07-20T13:11:28.0691733Z       at RPCProtocol._doInvokeHandler (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:402:17)
2020-07-20T13:11:28.0692723Z       at RPCProtocol._invokeHandler (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:387:32)
2020-07-20T13:11:28.0693585Z       at RPCProtocol._receiveRequest (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:303:19)
2020-07-20T13:11:28.0694456Z       at RPCProtocol._receiveOneMessage (d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:230:10)
2020-07-20T13:11:28.0695246Z       at d:\a\1\s\out\vs\workbench\services\extensions\common\file:\D:\a\1\s\src\vs\workbench\services\extensions\common\rpcProtocol.ts:105:42
2020-07-20T13:11:28.0698267Z       at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
2020-07-20T13:11:28.0699001Z       at BufferedEmitter.fire (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:453:19)
2020-07-20T13:11:28.0699766Z       at d:\a\1\s\out\vs\workbench\services\extensions\node\file:\D:\a\1\s\src\vs\workbench\services\extensions\node\extensionHostProcessSetup.ts:196:22
2020-07-20T13:11:28.0700510Z       at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
2020-07-20T13:11:28.0701191Z       at BufferedEmitter.fire (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:453:19)
2020-07-20T13:11:28.0701894Z       at PersistentProtocol._receiveMessage (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:733:21)
2020-07-20T13:11:28.0704434Z       at d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:592:73
2020-07-20T13:11:28.0705060Z       at Emitter.fire (d:\a\1\s\out\vs\base\common\file:\D:\a\1\s\src\vs\base\common\event.ts:587:16)
2020-07-20T13:11:28.0706117Z       at ProtocolReader.acceptChunk (d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:239:21)
2020-07-20T13:11:28.0712224Z       at d:\a\1\s\out\vs\base\parts\ipc\common\file:\D:\a\1\s\src\vs\base\parts\ipc\common\ipc.net.ts:200:51
2020-07-20T13:11:28.0721481Z       at Socket.listener (d:\a\1\s\out\vs\base\parts\ipc\node\file:\D:\a\1\s\src\vs\base\parts\ipc\node\ipc.net.ts:28:38)
2020-07-20T13:11:28.0722132Z       at addChunk (_stream_readable.js:308:12)
2020-07-20T13:11:28.0722499Z       at readableAddChunk (_stream_readable.js:289:11)
2020-07-20T13:11:28.0723284Z       at Socket.push (_stream_readable.js:223:10)
2020-07-20T13:11:28.0723684Z       at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
2020-07-20T13:11:28.0723976Z 
2020-07-20T13:11:29.2316642Z ##[error]PowerShell exited with code '1'.
2020-07-20T13:11:29.2730991Z ##[section]Finishing: Run Integration Tests (Electron)
```
