### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by TiagoF99** [microsoft/vscode#102973]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.0.0-dev.20200717
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (tsserver.js:106982:26)
    at resolveNamesWithLocalCache (tsserver.js:106844:21)
    at Object.resolveModuleNames (tsserver.js:106898:20)
    at InferredProject.Project.resolveModuleNames (tsserver.js:147524:45)
    at actualResolveModuleNamesWorker (tsserver.js:102521:133)
    at resolveModuleNamesWorker (tsserver.js:102741:26)
    at resolveModuleNamesReusingOldState (tsserver.js:102815:24)
    at processImportedModules (tsserver.js:104314:35)
    at findSourceFile (tsserver.js:104050:17)
    at tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (tsserver.js:103846:34)
    at processSourceFile (tsserver.js:103879:13)
    at processRootFile (tsserver.js:103702:13)
    at tsserver.js:102621:60
    at Object.forEach (tsserver.js:188:30)
    at Object.createProgram (tsserver.js:102621:16)
    at synchronizeHostData (tsserver.js:143149:26)
    at Proxy.getProgram (tsserver.js:143237:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:148058:53)
    at InferredProject.Project.updateGraph (tsserver.js:147991:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:150005:25)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:151512:26)
    at tsserver.js:151773:97
    at Object.flatMap (tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:151773:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (tsserver.js:152754:46)
    at tsserver.js:154609:88
    at IOSession.Session.executeWithRequestId (tsserver.js:154600:28)
    at IOSession.Session.executeCommand (tsserver.js:154609:33)
    at IOSession.Session.onMessage (tsserver.js:154633:35)
    at Interface.<anonymous> (tsserver.js:156848:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|25, 22, 15|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
god|bas|0.0.95
xml|Dot|2.5.1
gitlens|eam|10.2.2
go|gol|0.15.1
go-nightly|gol|2020.7.2015
Angular-BeastCode|Mik|8.1.2
vscode-docker|ms-|1.3.1
vscode-kubernetes-tools|ms-|1.2.1
vscode-typescript-next|ms-|4.0.20200717
vscode-typescript-tslint-plugin|ms-|1.2.3
typescript-hero|rbb|3.0.0
java|red|0.64.1
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.22.0
eno|Wsc|2.3.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
