### ISSUE TITLE
Unable to open the file because the associated text model is undefined ...

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10319]
- VSCode Version: Code - Insiders 1.5.0-insider (dde41be0231d6f8397d1da969ddab351f137b833, 2016-08-08T06:03:58.264Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Not sure how - I'm currently in this broken "state" that this error shows up if I click `F12` on method call in TypeScript file to go to definition.

Here is what UI shows:

![image](https://cloud.githubusercontent.com/assets/1723815/17497185/9a858ff4-5d8e-11e6-8f07-8ae6f057ce78.png)

In developers tools:

```
messageService.ts:119 Unable to open 'HostManager.ts': Unable to open the file because the associated text model is undefined..: Error: Unable to open 'HostManager.ts': Unable to open the file because the associated text model is undefined..
    at t.doHandleSetInputError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:103:27776)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:103:27382
    at Object.m [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:8421)
    at Object.V.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:11926)
    at i.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:13247)
    at i.Class.define._chainedError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:12606)
    at i (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:10429)
    at i.Class.define.then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:14056)
    at Object.P.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:10498)
    at i.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:13247)
    at i.Class.define._setCompleteValue (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:12941)e.doShow @ messageService.ts:119e.show @ messageService.ts:103t.doHandleSetInputError @ editorPart.ts:445(anonymous function) @ editorPart.ts:425m @ winjs.base.raw.js:1209V.enter @ winjs.base.raw.js:901i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._chainedError @ winjs.base.raw.js:1031i @ winjs.base.raw.js:736i.Class.define.then @ winjs.base.raw.js:1436P.enter @ winjs.base.raw.js:747i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170W.enter @ winjs.base.raw.js:852i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._completed @ winjs.base.raw.js:1036i.Class.define.then @ winjs.base.raw.js:1566P.enter @ winjs.base.raw.js:747i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._setCompleteValue @ winjs.base.raw.js:1052m @ winjs.base.raw.js:1209V.enter @ winjs.base.raw.js:901i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._chainedError @ winjs.base.raw.js:1031i @ winjs.base.raw.js:736i.Class.define.then @ winjs.base.raw.js:1436P.enter @ winjs.base.raw.js:747i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170W.enter @ winjs.base.raw.js:852i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._completed @ winjs.base.raw.js:1036i.Class.define.then @ winjs.base.raw.js:1566P.enter @ winjs.base.raw.js:747i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170W.enter @ winjs.base.raw.js:852i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._completed @ winjs.base.raw.js:1036(anonymous function) @ async.ts:596(anonymous function) @ original-fs.js:82
shell.ts:422 Cannot read property 'getControl' of undefined: TypeError: Cannot read property 'getControl' of undefined
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:25856
    at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:7841)
    at Object.V.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:11926)
    at i.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:13247)
    at i.Class.define._chainedError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:12606)
    at i (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:10429)
    at i.Class.define.then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:14056)
    at Object.P.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:10498)
    at i.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:13247)
    at i.Class.define._setCompleteValue (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:12941)e.onUnexpectedError @ shell.ts:422(anonymous function) @ shell.ts:324e.onUnexpectedError @ errors.ts:73u @ errors.ts:88(anonymous function) @ winjs.base.js:41(anonymous function) @ winjs.base.js:38
winjs.base.js:45 WARNING: Promise with no error callback:287
winjs.base.js:46 Object {exception: TypeError: Cannot read property 'getControl' of undefined
    at file:////Applications/Visual Studio…, error: null, promise: i.C…s.d…e._creator, handler: undefined, id: 287…}error: nullexception: TypeError: Cannot read property 'getControl' of undefined
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:25856
    at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:7841)
    at Object.V.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:11926)
    at i.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:13247)
    at i.Class.define._chainedError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:12606)
    at i (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:10429)
    at i.Class.define.then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:14056)
    at Object.P.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:10498)
    at i.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:13247)
    at i.Class.define._setCompleteValue (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:12941)handler: undefinedid: 287parent: undefinedpromise: i.Class.derive._creator__proto__: Object
winjs.base.js:48 TypeError: Cannot read property 'getControl' of undefined
    at goToDeclaration.ts:127
    at Object.g [as _notify] (winjs.base.raw.js:1170)
    at Object.V.enter (winjs.base.raw.js:901)
    at i.Class.define._run (winjs.base.raw.js:1068)
    at i.Class.define._chainedError (winjs.base.raw.js:1031)
    at i (winjs.base.raw.js:736)
    at i.Class.define.then (winjs.base.raw.js:1436)
    at Object.P.enter (winjs.base.raw.js:747)
    at i.Class.define._run (winjs.base.raw.js:1068)
    at i.Class.define._setCompleteValue (winjs.base.raw.js:1052)
```

**Comment by wallverb** [comment]
I am unable to open that file from Explorer / Cmd+P - the same error.

It looks like vscode is unable to open couple of files:

![image](https://cloud.githubusercontent.com/assets/1723815/17497398/b4a0d5d2-5d8f-11e6-9459-feeee21a00fd.png)

**Comment by wallverb** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/9865
