### ISSUE TITLE
moveEditor: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10313]
@bpasero Here are the steps to reproduce this issue:

- Initial state: Tabs disabled
- Have some files opened in three groups (left, right and center)
- Enable tabs
- Now move active editor to left or right using actions "Move Editor Left" and "Move Editor Right"

Expected: Active editor should be moved accordingly
Actual: You will see following error in the console. Refreshing the window fixes this issue.

I was using my new actions "Move Editor Left" and "Move Editor Right" and I also switched back and forth between using tabs or not. I got this in the console eventually:

```
shell.js:249 Cannot read property 'indexOf' of undefined: TypeError: Cannot read property 'indexOf' of undefined
    at moveActiveTab (file:///C:/GitDevelopment/monaco/out/vs/workbench/browser/parts/editor/editorCommands.js:65:32)
    at moveActiveEditor (file:///C:/GitDevelopment/monaco/out/vs/workbench/browser/parts/editor/editorCommands.js:57:24)
    at keybindingsRegistry_1.KeybindingsRegistry.registerCommandAndKeybindingRule.handler (file:///C:/GitDevelopment/monaco/out/vs/workbench/browser/parts/editor/editorCommands.js:35:57)
    at _commands.(anonymous function).handler (file:///C:/GitDevelopment/monaco/out/vs/platform/commands/common/commands.js:45:46)
    at InstantiationService.invokeFunction (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:47:34)
    at file:///C:/GitDevelopment/monaco/out/vs/platform/commands/common/commandService.js:34:77
    at CompletePromise_then [as then] (file:///C:/GitDevelopment/monaco/out/vs/base/common/winjs.base.raw.js:1566:49)
    at CommandService.executeCommand (file:///C:/GitDevelopment/monaco/out/vs/platform/commands/common/commandService.js:28:78)
    at MoveEditorRightInGroupAction.run (file:///C:/GitDevelopment/monaco/out/vs/workbench/browser/parts/editor/editorActions.js:1218:33)
    at file:///C:/GitDevelopment/monaco/out/vs/workbench/common/actionRegistry.js:98:64
```

**Comment by sandy081** [comment]
@bpasero after doing initial investigation `editorGroupsService.getStacksModel().getGroup(activeEditor.position)` is returning undefined. This happens only after enabling tabs. I think, some how `groupToIdentifier` map in Stacks model is not refreshed / updated after tabs is enabled. 

Moving this to you for further investigation. 

Thanks

**Comment by bpasero** [comment]
@sandy081 you are using the API wrong: `getEditor` only works with a `GroupIdentifier`, you have to use `groupAt` if you pass in a `Position`.
