### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#103157]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200717

**Steps to reproduce crash**
1. Added a folder to git via integrated console while a to be added .js file was open

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`~/Library/Application Support/Code - Insiders/logs/20200723T120428/exthost4/vscode.typescript-language-features/tsserver-log-oHKzMM/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:106982:26)
    at resolveNamesWithLocalCache (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:106844:21)
    at Object.resolveTypeReferenceDirectives (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:106885:20)
    at InferredProject.Project.resolveTypeReferenceDirectives (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:147530:45)
    at actualResolveTypeReferenceDirectiveNamesWorker (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102538:143)
    at resolveTypeReferenceDirectiveNamesWorker (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102748:26)
    at processTypeReferenceDirectives (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104213:31)
    at findSourceFile (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104044:21)
    at ~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at ~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102621:60
    at Object.forEach (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102621:16)
    at synchronizeHostData (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:143149:26)
    at Proxy.getProgram (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:143237:13)
    at InferredProject.Project.updateGraphWorker (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:148058:53)
    at InferredProject.Project.updateGraph (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:147991:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:150005:25)
    at ProjectService.assignProjectToOpenedScriptInfo (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151512:26)
    at ~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151773:97
    at Object.flatMap (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151773:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:152754:46)
    at ~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154609:88
    at IOSession.Session.executeWithRequestId (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154600:28)
    at IOSession.Session.executeCommand (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154609:33)
    at IOSession.Session.onMessage (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154633:35)
    at Interface.<anonymous> (~/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:156848:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.48.0-insider (8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e, 2020-07-23T05:40:23.559Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|167, 85, 83|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|-psn_0_1175839 --crash-reporter-id 407cf4a7-745b-487a-bfa4-bd7d9370e392|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (92)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
cucumberautocomplete|ale|2.15.0
cypress-snippets|and|1.2.0
vscode-apollo|apo|1.16.6
vscode-zipfs|arc|2.0.0
atlascode|atl|2.6.6
phpstan|bre|1.1.3
twigcs|cer|1.1.0
vscode-opennewinstance|chr|0.0.7
path-intellisense|chr|2.2.1
transformer|dak|1.6.0
scss-grammar-extended|dan|1.0.0
vscode-eslint|dba|2.1.8
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
emberjs|emb|1.0.1
vscode-ember|emb|0.2.1
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vsc-ember-cli|fel|0.3.3
file-icons|fil|1.0.24
vscode-firefox-debug|fir|2.9.0
vscode-architect|gil|0.1.0
vscode-pull-request-github|Git|0.18.1
dance|gre|0.3.0
rest-client|hum|0.24.1
output-colorizer|IBM|0.1.2
composer|ika|0.7.1
smarty|imp|0.3.0
path-autocomplete|ion|1.15.0
svelte-vscode|Jam|0.9.3
vscode-edit-csv|jan|0.3.0
exercism|jgo|0.0.4
vscode-peacock|joh|3.7.2
ember-related-files|jos|1.5.0
php-cs-fixer|jun|0.1.155
language-haskell|jus|3.3.0
graphql-for-vscode|kum|1.15.3
inline-parameters|lia|0.2.1
php-symbols|lin|2.1.0
phpmd|lin|1.2.1
web-accessibility|Max|0.2.82
twig-language-2|mbl|0.9.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.4.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-remote-extensionpack|ms-|0.20.0
js-debug-companion|ms-|1.0.2
js-debug-nightly|ms-|2020.7.2217
references-view|ms-|0.0.61
vscode-github-issue-notebooks|ms-|0.0.35
vscode-typescript-next|ms-|4.0.20200717
debugger-for-chrome|msj|4.12.9
vetur|oct|0.25.0
EmberES6Snippets|pha|2.3.3
prisma|Pri|2.3.0
vscode-yaml|red|0.9.1
elastic|ria|0.13.3
rust|rus|0.7.8
vscode-javascript-booster|sbu|14.0.1
code-settings-sync|Sha|3.4.3
phpcs|she|1.0.8
svg-preview|Sim|2.8.3
sourcegraph|sou|1.1.0
autoimport|ste|1.5.3
stepsize|Ste|0.0.12
tech-debt-tracker|Ste|0.27.5
cucumber|ste|0.12.0
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.84.0
vscode-field-lights|sve|0.0.11
language-stylus|sys|1.11.0
stylus-supremacy|thi|2.14.5
php-phan|Tys|2.0.1
vscode-phpsab|val|0.0.10
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
vscode-meteor|vuh|0.1.1
vscode-wakatime|Wak|4.0.0
twig|wha|1.0.2
vscode-nginx|wil|0.7.2
file-size|zh9|0.1.3
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Can you please add some more detailed steps to reproduce? Also look into including the logs if possible as mentioned in the issue

**Comment by bm-stschneider** [comment]
I uploaded the log file. I was really only waiting for the git add when this happened. I switched between file explorer and version control a bit.

**Comment by mjbvz** [comment]
Thanks. The log file doesn't seem to contain the crash itself so I'm not sure exactly what is going on

Also it looks like you have the IntelliCode extension enabled which could effect the ts server. Do you see this issue with all extensions disabled?

**Comment by bm-stschneider** [comment]
The problem is that it occurs out of the blue, even with me not beeing in vscode window at all.

**Comment by bm-stschneider** [comment]
With disabled extensions this doesn't seem to happen.
