### ISSUE TITLE
Extentions GitLens and GitGraph not working after update

### ISSUE THREAD

**Issue by sanidz** [microsoft/vscode#103229]
Issue Type: <b>Bug</b>

Hi guys, after Visual Studio Code update 1.47.2,  extentions GitLens and GitGraph are not working anymore... GitGraph button at the bottom strip is not visible and GitLens icon in Activity bar shows empty content. 
I tried installing them again and restarting but no luck. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.0.1
githistory|don|0.6.8
gitlens|eam|10.2.2
tslint|eg2|1.0.44
vscode-test-explorer|hbe|2.19.1
git-graph|mhu|1.24.0
vscode-kubernetes-tools|ms-|1.2.1
vsliveshare|ms-|1.0.2478
debugger-for-chrome|msj|4.12.9
angular-console|nrw|12.0.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.9.1

</details>

**Comment by joaomoreno** [comment]
Can you run `Developer: Show Running Extensions`? Do the extensions appear in there? Are they disabled maybe?

**Comment by sanidz** [comment]
This is full list and extentions that are not working are not in it:

![image](https://user-images.githubusercontent.com/40788324/88390725-2153b800-cdb9-11ea-88a5-d7b962e87af6.png)

Is there a way to start them manually?
I can see them in Extentions and in individual details there is just info: This extension is enabled globally.

**Comment by sandy081** [comment]
What does the extensions view show? Are these extensions are shown there and are they enabled?

**Comment by sandy081** [comment]
Do you see any errors ?

    - Help -> Toggle Developer Tools -> Console
    - View -> Open View… -> Log (Window)
    - View -> Open View… -> Log (Extension Host)

**Comment by sanidz** [comment]
Help -> Toggle Developer Tools -> Console: 

abstractExtensionService.ts:411 Activating extension 'eg2.tslint' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'donjayamanne.githistory' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'eamodio.gitlens' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'hbenl.vscode-test-explorer' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'mhutchie.git-graph' failed: The "path" argument must be of type string. Received type undefined.

**Comment by sanidz** [comment]
Extention Host:

[2020-07-24 09:41:58.268] [exthost] [error] Activating extension eamodio.gitlens failed due to an error:
[2020-07-24 09:41:58.268] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at Function.Module._nodeModulePaths (internal/modules/cjs/loader.js:590:37)
	at Module.load (internal/modules/cjs/loader.js:777:23)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at h._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:140)
	at h.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:546)
	at h._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:833:300)
	at h._handleEagerExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:838:218)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:841:872
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/102642
