### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/vscode#103416]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200726

**Steps to reproduce crash**
1. Open an Angular project over Live Share
2. Open a directive, close it
3. Open the tsconfig.json file, close it
4. Open the directive again

This is probably related to the Angular language server.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:107070:26)
    at resolveNamesWithLocalCache (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:106932:21)
    at Object.resolveModuleNames (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:106986:20)
    at InferredProject.Project.resolveModuleNames (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:147629:45)
    at actualResolveModuleNamesWorker (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102605:133)
    at resolveModuleNamesWorker (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102828:26)
    at resolveModuleNamesReusingOldState (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102978:19)
    at tryReuseStructureFromOldProgram (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:103201:35)
    at Object.createProgram (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102668:30)
    at synchronizeHostData (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:143253:26)
    at Proxy.getProgram (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:143341:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:148163:53)
    at InferredProject.Project.updateGraph (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:148096:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:150164:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:151693:26)
    at c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:151954:97
    at Object.flatMap (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:151954:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:152947:46)
    at c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154805:88
    at IOSession.Session.executeWithRequestId (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154796:28)
    at IOSession.Session.executeCommand (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154805:33)
    at IOSession.Session.onMessage (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154829:35)
    at Interface.<anonymous> (c:\Users\natob\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:157044:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:57:10.466Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3468)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (13.89GB free)|
|Process Argv|-n C:\Users\natob\AppData\Local\Temp\vsliveshare\tmp-D4F637A903D5901C1E2E8725E735EDB920E9\Visual Studio Live Share.code-workspace --crash-reporter-id 9f349065-ec75-49e5-9606-c98264b9e294|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
systemd-unit-file|coo|1.0.6
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-markdownlint|Dav|0.36.1
apt-source-list-syntax|dei|0.1.4
docs-yaml|doc|0.2.5
githistory|don|0.6.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.0
shell-format|fox|7.0.1
go-nightly|gol|2020.7.2222
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
discord-vscode|icr|4.0.0
jenkinsfile-support|ivo|1.1.0
hungry-delete|jas|1.6.0
jbockle-format-files|jbo|3.0.0
Angular2|joh|9.1.2
pwa-tools|joh|0.1.0
read-time|joh|0.2.0
dotenv|mik|1.0.1
typescript-javascript-grammar|ms-|0.0.53
vscode-js-profile-table|ms-|0.0.7
vscode-typescript-next|ms-|4.0.20200726
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2478
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|0.16.1
gradle-language|nac|0.2.3
polacode|pnp|0.3.4
prettier-vscode|pre|3.14.1
vscode-graphql|Pri|0.2.14
quicktype|qui|12.0.46
vscode-sorting-attrs|rba|1.0.6
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
vscode-sort-json|ric|1.18.0
vscode-table-formatter|shu|1.2.1
datapack-language-server|SPG|2.1.14
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.9
markdown-pdf|yza|1.4.4

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically the angular and graphql extension since I believe those include Typescript plugins
