### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by aidid-nibir** [microsoft/vscode#103407]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200726

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:107070:26)
    at resolveNamesWithLocalCache (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:106932:21)
    at Object.resolveModuleNames (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:106986:20)
    at InferredProject.Project.resolveModuleNames (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:147629:45)
    at actualResolveModuleNamesWorker (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102605:133)
    at resolveModuleNamesWorker (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102828:26)
    at resolveModuleNamesReusingOldState (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102902:24)
    at processImportedModules (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:104401:35)
    at findSourceFile (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:104137:17)
    at c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:103966:85
    at getSourceFileFromReferenceWorker (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:103933:34)
    at processSourceFile (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:103966:13)
    at processRootFile (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:103789:13)
    at c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102706:60
    at Object.forEach (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:188:30)
    at Object.createProgram (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:102706:16)
    at synchronizeHostData (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:143253:26)
    at Proxy.getProgram (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:143341:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:148163:53)
    at InferredProject.Project.updateGraph (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:148096:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:150164:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:151693:26)
    at c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:151954:97
    at Object.flatMap (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:151954:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:152947:46)
    at c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154805:88
    at IOSession.Session.executeWithRequestId (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154796:28)
    at IOSession.Session.executeCommand (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154805:33)
    at IOSession.Session.onMessage (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:154829:35)
    at Interface.<anonymous> (c:\Users\AididNibir\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200726\node_modules\typescript\lib\tsserver.js:157044:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
vsc-kendo-core-components|art|0.4.4
themes-bundle|baq|0.0.1
vscode-custom-css|be5|3.0.10
vscode-intelephense-client|bme|1.5.3
vscode-standardjs-snippets|cap|0.8.12
path-intellisense|chr|2.2.1
the-powerful-bootstrap|Cro|1.2.4
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.3
php-intellisense|fel|2.3.14
json2ts|Gre|0.0.6
kendotemplatewizard|Ken|1.1.7
ts-extension-pack|loi|0.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|2.3.3
Angular-BeastCode|Mik|8.1.2
kendo-react-snippets|mil|0.4.0
vscode-typescript-next|ms-|4.0.20200726
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
vscode-angularjs-snippet|Nic|0.0.12
bootstrap4code|oua|1.0.0
tsimporter|pmn|2.0.1
vscode-css-peek|pra|3.2.6
typescript-hero|rbb|3.0.0
html5-boilerplate|sid|1.0.3
html-to-css-autocompletion|sol|1.1.2
move-ts|str|1.12.0
bootstrap4-vscode|the|6.1.0
html-snippets|wge|0.1.5
JavaScriptSnippets|xab|1.8.0
bootstrap-v4-snippets|Zac|1.1.3
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
