### ISSUE TITLE
Debugger setting breakpoints on transpiled file

### ISSUE THREAD

**Issue by bborela** [microsoft/vscode#103556]
- VSCode Version: 1.47.3
- OS Version: macOS Catalina 10.15.3

Following the latest update, I cannot debug stepping through the original .ts source files. For legacy reasons, I'm using babel-node to transpile the code. My launch.json configuration looks like this:

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/source/server.ts",
      "runtimeExecutable": "babel-node",
      "runtimeArgs": [
        "--extensions",
        ".ts,.tsx",
      ],
      "outFiles": ["${workspaceFolder}/build/**/*.js"],
      "cwd": "${workspaceFolder}"
    },
```

My tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "es2019",
    "moduleResolution": "node",
    "module": "commonjs",
    "allowJs": true,
    "noEmit": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "lib":["es2019"],
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*"
      ]
    }
  },
  "include": [
    "source/**/*.ts",
    "test/**/*.ts",
    "typings/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/__mocks__/*"
  ]
}
```

Toggling a breakpoint in the .ts file will actually toggle a breakpoint in the transpiled .js file, and not even on the intended line. I've tried setting `"debug.javascript.usePreview": false` in order to use the old debugger, but then it toggles the breakpoint on the wrong line.

**Comment by jonathancreamer-eb** [comment]
ha, I've been pulling my hair out thinking it was something I was doing, but I'm seeing the exact same thing right now.

I made a simple case for reproducibility out of our complicated one, so this script...

![](https://d.pr/i/VeaOWr+)

With this `launch.json` config...

```json
{
    "type": "node",
    "request": "launch",
    "name": "Debug",
    "program": "${workspaceFolder}/script.js",
    "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/babel-node",
    "runtimeArgs": ["--nolazy"]
},
```

With this super simple `babel.config.js`...

```json
module.exports = {
    presets: ['@babel/env'],
    sourceMaps: 'inline',
    retainLines: true,
};
```

But, when I invoke the debugger, with a breakpoint in `./script.js`, it's throwing the debugger in here...

![](https://d.pr/i/EtjD8r+)

Also seeing the following in the developer tools...

```
 ERR Source not found: Error: Source not found
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3173:226)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3172:532
```

```
  ERR unknown thread: Error: unknown thread
    at b.getKnownThread (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6457:60)
    at b.deleteCommentThread (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6456:645)
    at _.$deleteCommentThread (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6459:701)
    at p._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4258:757)
    at p._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4258:449)
    at p._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4257:120)
    at p._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4255:970)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4254:161
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at v.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:430:733)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:435:38)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:432:243
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at g.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:428:234)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:427:604
    at Socket.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:436:655)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
```
ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by jonathancreamer-eb** [comment]
Note this is also happening with `code --disable-extensions`.

**Comment by jonathancreamer-eb** [comment]
I also tried adding `"sourceMaps": true` to the config.

**Comment by connor4312** [comment]
Please try the [js-debug nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) extension; babel-node is a little 'weird' and we've put in an assortment of fixes for it this month 🙂 

/needsMoreInfo

**Comment by jonathancreamer-eb** [comment]
Trying...

**Comment by jonathancreamer-eb** [comment]
Yup, good sir, that does in fact work. :)

**Comment by connor4312** [comment]
Good to hear, thanks for confirming!
