### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by angad777** [microsoft/vscode#103564]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200727

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:107070:26)
    at resolveNamesWithLocalCache (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:106932:21)
    at Object.resolveModuleNames (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:106986:20)
    at InferredProject.Project.resolveModuleNames (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:147629:45)
    at actualResolveModuleNamesWorker (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:102605:133)
    at resolveModuleNamesWorker (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:102828:26)
    at resolveModuleNamesReusingOldState (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:102902:24)
    at processImportedModules (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:104401:35)
    at findSourceFile (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:104137:17)
    at /Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:103966:85
    at getSourceFileFromReferenceWorker (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:103933:34)
    at processSourceFile (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:103966:13)
    at processRootFile (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:103789:13)
    at /Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:102706:60
    at Object.forEach (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:102706:16)
    at synchronizeHostData (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:143253:26)
    at Proxy.getProgram (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:143341:13)
    at InferredProject.Project.updateGraphWorker (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:148163:53)
    at InferredProject.Project.updateGraph (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:148096:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:150164:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:151693:26)
    at /Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:151954:97
    at Object.flatMap (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:151954:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:152947:46)
    at /Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:154805:88
    at IOSession.Session.executeWithRequestId (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:154796:28)
    at IOSession.Session.executeCommand (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:154805:33)
    at IOSession.Session.onMessage (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:154829:35)
    at Interface.<anonymous> (/Users/angad.gupta/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200727/node_modules/typescript/lib/tsserver.js:157044:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 9, 8|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|/Users/angad.gupta/Documents/WORKSPACE/platform-property|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-apollo|apo|1.16.6
swagger-viewer|Arj|3.0.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.18.0
rainbow-csv|mec|1.7.0
vscode-docker|ms-|1.4.1
vscode-typescript-next|ms-|4.0.20200728
vscode-typescript-tslint-plugin|ms-|1.2.3
color-highlight|nau|2.3.0
vetur|oct|0.25.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.9.1
swdc-vscode|sof|2.2.42
vscodeintellicode|Vis|1.2.9
gitblame|wad|4.2.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by angad777** [comment]
Hey @mjbvz - Wouldn't it be unfair to reproduce with all the extensions disabled ?

**Comment by mjbvz** [comment]
If an extension is causing the problem, this issue should be filed against them instead. Please test insiders with extensions disabled
