### ISSUE TITLE
Web view test is broken

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103544]
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=83206&view=logs&j=d71c4c56-574b-5ba9-9268-feb3539ccbff&t=7d37d8af-91f8-5651-2695-cda24483e594

### Mac

```
1) vscode API - webview webviews should preserve vscode API state when they are hidden:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

### Linux

```
1) vscode API - webview webviews should only be able to load resources from workspace by default:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/webview.test.ts:273:11)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)

  2) vscode API - webview webviews using hard-coded old style vscode-resource uri should work:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/webview.test.ts:346:10)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

**Comment by sandy081** [comment]
Skipped the test.

**Comment by sandy081** [comment]
Skipped another failing test

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=83327&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=087c9a82-9b9b-5b5f-17f2-a070cb4808e3

```
 1 failing
  1) vscode API - webview webviews should allow overriding allowed resource paths using localResourceRoots:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/webview.test.ts:319:11)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by isidorn** [comment]
I skipped more failing tests via f3e4ff9196

**Comment by joaomoreno** [comment]
Closing as out of date. cc @mjbvz
