### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 3 === 4. Registered script kind should match new script kind. /users/anikolov/desktop/projects/ts2-psp-merge/ts2-portal/untitled:^untitled-1

### ISSUE THREAD

**Issue by angelnikolov** [microsoft/vscode#103630]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1. Create a new empty file via COMMAND + N
2. The language service crashes. Not consistently.
**TS Server Error Stack**
```
Error: Debug Failure. Expected 3 === 4. Registered script kind should match new script kind. /users/anikolov/desktop/projects/ts2-psp-merge/ts2-portal/untitled:^untitled-1
    at Object.assertEqual (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:2043:17)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:135295:34)
    at tryReuseStructureFromOldProgram (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:98176:28)
    at Object.createProgram (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:97765:30)
    at synchronizeHostData (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:135218:26)
    at Proxy.getProgram (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:135310:13)
    at InferredProject.Project.updateGraphWorker (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:139786:53)
    at InferredProject.Project.updateGraph (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:139729:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:141705:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:143132:26)
    at /Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:143396:107
    at Object.mapDefined (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:144260:46)
    at /Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/Users/anikolov/Desktop/Projects/ts2-psp-merge/ts2-portal/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.46.0-insider (288852d8c26d797974bfb8aed06e1bff9b809223, 2020-05-12T05:42:38.380Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (1.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
cucumberautocomplete|ale|2.15.0
jshint|dba|0.10.21
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
vscode-diff|fab|1.4.0
svelte-vscode|Jam|0.9.3
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
vscode-sshfs|Kel|1.18.2
vscode-scss|mrm|0.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
angular-console|nrw|13.0.0
polacode|pnp|0.3.4
ejs-language-support|Qas|0.0.1
vscode-xml|red|0.13.0
ngx-translate-zombies|sev|0.0.1
vscode-scss-formatter|sib|2.0.1
sass-indented|syl|1.8.9
markdown-all-in-one|yzh|3.2.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
You are on an old VS Code insiders build

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by JDWilson1980** [comment]
Uber.wireshark.net
Herbert.botnet.repository/OP
Servo.local.access/Uber
Cyber(compliance.host.kernel)
Hello(pull.compliance.nsf)
Repository (data.legal.us)pull
Brute(v.ddos.nds)
force(geo.circle.workflow)
AutoRun(dev.nss.ddos)
Create(invite.depo.module)
Assign(label.package.op)
Tag(resources.hubspot.op)
List(omni.msp.vol)
Uber(workflow.hubspot.juno)
Workforce.hubspot.vdb
Workforce.juno.vsl
Workforce.eVerify.dll

SQL.NCIS.IFIX.NET/TREE
