### ISSUE TITLE
"Go to definition" works for a while and then stops

### ISSUE THREAD

**Issue by matkovski** [microsoft/vscode#103695]
Issue Type: <b>Bug</b>

I'm working on a rather big Angular project, with the Angular extension installed but disabled. After I start VScode, it takes a while until it does what it needs to be able to follow the file paths, and then I can just press Cmd-Down to follow the path (that's my custom shortcut for Go to definition/implementation, not important).

However, after a while this stops working - around 5 minutes or so. For any attempts to use the feature, VScode just shows a sort of loading animation in the top of the UI, as if it were searching, but doesn't follow the link. It is the same with anything outside of the current file (anything that's imported from another file) - it does work for links within the same class, for example.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
vscode-mocha-test-adapter|hbe|2.7.0
vscode-test-explorer|hbe|2.19.1
git-graph|mhu|1.25.0
tabsort|oma|1.1.2
code-settings-sync|Sha|3.4.3

</details>

**Comment by gjsjohnmurray** [comment]
Maybe something is causing the Extension Host to crash. Any clues showing up in the "Log (Extension Host)" view of the Output tab on the Output Panel?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by matkovski** [comment]
> Maybe something is causing the Extension Host to crash. Any clues showing up in the "Log (Extension Host)" view of the Output tab on the Output Panel?

Seems so, here's what I see in log this time

```[2020-08-03 16:06:15.900] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-08-03 16:06:15.902] [exthost] [error] Error: DisposableStore is missing...
	at U._convertCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:679:652)
	at U.resolveCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:679:419)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-03 17:21:18.127] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-08-03 17:21:18.128] [exthost] [error] Error: DisposableStore is missing...
	at U._convertCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:679:652)
	at U.resolveCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:679:419)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-03 17:40:42.798] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-08-03 17:40:42.798] [exthost] [error] Error: DisposableStore is missing...
	at U._convertCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:679:652)
	at U.resolveCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:679:419)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by mjbvz** [comment]
Did you test using VS Code insiders with extensions disabled?
