### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by denissabramovs** [microsoft/vscode#103628]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200729

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:107076:26)
    at resolveNamesWithLocalCache (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:106938:21)
    at Object.resolveModuleNames (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:106992:20)
    at InferredProject.Project.resolveModuleNames (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:147645:45)
    at actualResolveModuleNamesWorker (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:102611:133)
    at resolveModuleNamesWorker (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:102834:26)
    at resolveModuleNamesReusingOldState (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:102908:24)
    at processImportedModules (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:104407:35)
    at findSourceFile (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:104143:17)
    at /home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:103972:85
    at getSourceFileFromReferenceWorker (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:103939:34)
    at processSourceFile (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:103972:13)
    at processRootFile (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:103795:13)
    at /home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:102712:60
    at Object.forEach (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:102712:16)
    at synchronizeHostData (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:143269:26)
    at Proxy.getProgram (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:143357:13)
    at InferredProject.Project.updateGraphWorker (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:148179:53)
    at InferredProject.Project.updateGraph (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:148112:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:150180:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:151709:26)
    at /home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:151970:97
    at Object.flatMap (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:151970:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:152963:46)
    at /home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:154821:88
    at IOSession.Session.executeWithRequestId (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:154812:28)
    at IOSession.Session.executeCommand (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:154821:33)
    at IOSession.Session.onMessage (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:154845:35)
    at Interface.<anonymous> (/home/beck/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200729/node_modules/typescript/lib/tsserver.js:157060:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4095)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|31.22GB (13.11GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
sort-imports|ama|6.1.0
prettier-vscode-standard|bys|0.22.1
npm-intellisense|chr|1.3.0
mustache|daw|1.1.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
vscode-yarn|gam|1.7.0
bettercomment|Gru|0.0.9
todo-tree|Gru|0.0.178
beautify|Hoo|1.5.0
intellij-idea-keybindings|k--|0.2.41
linecounter|lyz|0.2.7
git-graph|mhu|1.25.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.0.20200729
vscode-yaml-sort|Pas|2.3.1
linesinfostatusbar|pet|0.0.3
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.9.1
prettier-now|rem|1.4.9
addDocComments|ste|0.0.8
go-to-method|tri|0.2.0
alphabetical-sorter|ue|2.0.1
vscode-todo-highlight|way|1.0.4
disable-eslint-rule|Woo|0.0.2
sort-js-object-keys|zen|1.0.6
file-size|zh9|0.1.3

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
