### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by trevonmckay** [microsoft/vscode#103639]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200728

**Steps to reproduce crash**
1. Ran npm run build -- --prod

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:107076:26)
    at resolveNamesWithLocalCache (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:106938:21)
    at Object.resolveModuleNames (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:106992:20)
    at InferredProject.Project.resolveModuleNames (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:147635:45)
    at actualResolveModuleNamesWorker (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:102611:133)
    at resolveModuleNamesWorker (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:102834:26)
    at resolveModuleNamesReusingOldState (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:102908:24)
    at processImportedModules (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:104407:35)
    at findSourceFile (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:104143:17)
    at c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:103972:85
    at getSourceFileFromReferenceWorker (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:103939:34)
    at processSourceFile (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:103972:13)
    at processRootFile (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:103795:13)
    at c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:102712:60
    at Object.forEach (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:188:30)
    at Object.createProgram (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:102712:16)
    at synchronizeHostData (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:143259:26)
    at Proxy.getProgram (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:143347:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:148169:53)
    at InferredProject.Project.updateGraph (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:148102:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:150170:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:151699:26)
    at c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:151960:97
    at Object.flatMap (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:151960:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:152953:46)
    at c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:154811:88
    at IOSession.Session.executeWithRequestId (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:154802:28)
    at IOSession.Session.executeCommand (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:154811:33)
    at IOSession.Session.onMessage (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:154835:35)
    at Interface.<anonymous> (c:\Users\trevo\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200728\node_modules\typescript\lib\tsserver.js:157050:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.48.0-insider (15e798e081984a17eae00de91adf4479190d5ed2, 2020-07-28T10:39:18.007Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.85GB free)|
|Process Argv|--crash-reporter-id b49a94ec-7cb1-432c-8563-ad46c370f3b5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
jsonviewer|cci|1.2.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
beautify|Hoo|1.5.0
minifyall|jos|2.3.2
gitignore|mic|1.0.1
azure-pipelines|ms-|1.170.0
vscode-azureappservice|ms-|0.18.0
vscode-azurefunctions|ms-|0.23.0
vscode-azurestorage|ms-|0.9.0
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
vscode-dotnet-runtime|ms-|0.1.2
mssql|ms-|1.9.0
remote-wsl|ms-|0.44.4
azure-account|ms-|0.9.1
azurecli|ms-|0.5.0
powershell|ms-|2020.6.0
vscode-typescript-next|ms-|4.0.20200729
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.11.0
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|0.16.1
vscode-auto-scroll|pej|1.0.4
vscode-yaml|red|0.9.1
vscode-odata|sta|0.1.0
vscodeintellicode|Vis|1.2.9
application-insights|Vis|0.4.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Specifically try disabling the vscode-typescript-tslint-plugin and vscode intellicode extension since those both modify the TypeScript server
