### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by kokiebisu** [microsoft/vscode#103764]
**TypeScript Version:** 4.0.0-dev.20200731

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:107105:26)
    at resolveNamesWithLocalCache (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:106967:21)
    at Object.resolveModuleNames (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:107021:20)
    at InferredProject.Project.resolveModuleNames (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:147689:45)
    at actualResolveModuleNamesWorker (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102640:133)
    at resolveModuleNamesWorker (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102863:26)
    at resolveModuleNamesReusingOldState (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102937:24)
    at processImportedModules (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104436:35)
    at findSourceFile (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104172:17)
    at /Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104001:85
    at getSourceFileFromReferenceWorker (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:103968:34)
    at processSourceFile (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104001:13)
    at processRootFile (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:103824:13)
    at /Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102741:60
    at Object.forEach (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102741:16)
    at synchronizeHostData (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:143313:26)
    at Proxy.getProgram (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:143401:13)
    at InferredProject.Project.updateGraphWorker (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:148223:53)
    at InferredProject.Project.updateGraph (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:148156:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:150224:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:151753:26)
    at /Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:152014:97
    at Object.flatMap (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:152014:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:153007:46)
    at /Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154865:88
    at IOSession.Session.executeWithRequestId (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154856:28)
    at IOSession.Session.executeCommand (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154865:33)
    at IOSession.Session.onMessage (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154889:35)
    at Interface.<anonymous> (/Users/ken/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:157104:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Any additional information about how to reproduce this?

/needsMoreInfo

**Comment by kokiebisu** [comment]
VS Code isn't crashing anymore on my side. I'm guessing the problem was on my end. I will close this issue.
