### ISSUE TITLE
Error ao utilizar o debug.

### ISSUE THREAD

**Issue by SebastiaoMoraes** [microsoft/vscode#103761]
Boa tarde, preciso de ajuda.
 Ao utilizar o debug no VScode me deparei com o seguinte problema.
Já atualizei, desinstalei e instalei novamente tanto vs code como o nodejs, mas o erro permanece.

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'c:/Users/Sebasti�o Junior/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1277:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

! [Imagem do erro]
![Debug vs code](https://user-images.githubusercontent.com/54009045/89108449-031c3680-d40f-11ea-876b-7d4b14221247.png)

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018

/duplicate
