### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by mephisto83** [microsoft/vscode#103709]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200730

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:107087:26)
    at resolveNamesWithLocalCache (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:106949:21)
    at Object.resolveModuleNames (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:107003:20)
    at InferredProject.Project.resolveModuleNames (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:147656:45)
    at actualResolveModuleNamesWorker (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:102622:133)
    at resolveModuleNamesWorker (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:102845:26)
    at resolveModuleNamesReusingOldState (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:102919:24)
    at processImportedModules (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:104418:35)
    at findSourceFile (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:104154:17)
    at c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:103983:85
    at getSourceFileFromReferenceWorker (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:103950:34)
    at processSourceFile (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:103983:13)
    at processRootFile (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:103806:13)
    at c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:102723:60
    at Object.forEach (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:188:30)
    at Object.createProgram (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:102723:16)
    at synchronizeHostData (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:143280:26)
    at Proxy.getProgram (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:143368:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:148190:53)
    at InferredProject.Project.updateGraph (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:148123:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:150191:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:151720:26)
    at c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:151981:97
    at Object.flatMap (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:151981:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:152974:46)
    at c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:154832:88
    at IOSession.Session.executeWithRequestId (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:154823:28)
    at IOSession.Session.executeCommand (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:154832:33)
    at IOSession.Session.onMessage (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:154856:35)
    at Interface.<anonymous> (c:\Users\ajporter\.vscode\extensions\ms-vscode.vscode-typescript-next-4.0.20200730\node_modules\typescript\lib\tsserver.js:157071:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.46GB (13.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
ng-template|Ang|0.1000.7
cake-vscode|cak|0.13.0
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
go|gol|0.15.2
gc-excelviewer|Gra|3.0.39
terraform|has|2.1.1
react-native-snippet|jun|0.5.6
code-groovy|mar|0.1.2
code-beautifier|mic|2.3.3
graphql|mqu|0.1.2
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
python|ms-|2020.7.96456
azure-account|ms-|0.8.11
powershell|ms-|2020.6.0
vscode-typescript-next|ms-|4.0.20200730
gradle-language|nac|0.2.3
vscode-graphql|stp|0.2.3
angular-template-formatter|str|0.1.2

</details>

**Comment by mjbvz** [comment]
/needsMoreInfo

Please make sure to fill in the issue template

**Comment by JDWilson1980** [comment]
Add remediation to move transportation character and contact information

Use a nice tag 4 redirecting resources

//STATcomm.qual.link
//Omni.core
QST.omni.dys
Axios.omni.dev

QRL(repo.omni.sql)
