### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#103778]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.0.0-dev.20200731
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationsOfExternalModuleResolutions (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:107105:26)
    at resolveNamesWithLocalCache (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:106967:21)
    at Object.resolveModuleNames (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:107021:20)
    at InferredProject.Project.resolveModuleNames (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:147689:45)
    at actualResolveModuleNamesWorker (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102640:133)
    at resolveModuleNamesWorker (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102863:26)
    at resolveModuleNamesReusingOldState (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102937:24)
    at processImportedModules (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104436:35)
    at findSourceFile (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104172:17)
    at /home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104001:85
    at getSourceFileFromReferenceWorker (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:103968:34)
    at processSourceFile (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:104001:13)
    at processRootFile (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:103824:13)
    at /home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102741:60
    at Object.forEach (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:102741:16)
    at synchronizeHostData (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:143313:26)
    at Object.getProgram (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:143401:13)
    at InferredProject.Project.updateGraphWorker (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:148223:53)
    at InferredProject.Project.updateGraph (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:148156:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:150224:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:151753:26)
    at /home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:152014:97
    at Object.flatMap (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:152014:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:153007:46)
    at /home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154865:88
    at IOSession.Session.executeWithRequestId (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154856:28)
    at IOSession.Session.executeCommand (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154865:33)
    at IOSession.Session.onMessage (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:154889:35)
    at Interface.<anonymous> (/home/s/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200731/node_modules/typescript/lib/tsserver.js:157104:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.45.0-insider (fd5d9a30259bb2bebab3e62dfd8315c2e1b27744, 2020-05-04T09:28:51.508Z)
OS version: Linux x64 5.6.19-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (6.13GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.2
vscode-open-in-node-modules|fab|1.1.1
vscode-firefox-debug|fir|2.9.0
path-autocomplete|ion|1.15.0
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
atom-keybindings|ms-|3.0.8
vscode-typescript-next|ms-|4.0.20200801
color-highlight|nau|2.3.0
vscode-yaml|red|0.9.1
magic-beans|sel|0.23.0
niketa|sel|3.4.2
sass-indented|syl|1.8.9
tabnine-vscode|Tab|2.9.0
jest-snapshot-language-support|tle|1.1.1
vscode-icons|vsc|10.2.0
dingo-vscode|Wal|1.0.7
wallaby-vscode|Wal|1.0.222
vikings-icon-theme|wil|1.0.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
You are on an old VS Code version.

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by selfrefactor** [comment]
I should be with latest version as I don't see any new package updates. 

The bug I cannot reproduce as I was unsure what caused it.

**Comment by mjbvz** [comment]
The reports says you are running VS Code 1.45.0-insiders, which is now at least two months old

Closing as not reproducible. Let us know if you see this again on the latest insiders build with extensions disabled
