### ISSUE TITLE
Can not add index to parent of type array

### ISSUE THREAD

**Issue by muisance** [microsoft/vscode#103943]
**Please search existing issues to avoid creating duplicates.**
I did; there was one closed thread from 2017 where no solution was found and the OP made an assumption that there was something wrong with his OS; I, however, am almost certain that this is not an OS issue despite me running an Insider Beta version of Windows.

- VSCode Version: 1.47.3
- OS Version: **20H2** build **19042.423** (Win 10 Home Insider Beta)

__Steps to Reproduce:__

1. Open VSCode
2. Amend any USER setting whatsoever (for some reason, however, this error doesn't occur when amending Workspace settings)

I think this issue arose after I carelessly amended the settings file or possibly after opening it in Notepads program -- there were issues with signatures of files I opened with it prior to that, Another possibility is that I mass-uncommented a big user settings file -- I can't recall the exact chronology of events, sadly.
# Here's what logs say:

    ERR Can not add index to parent of type array: Error: Can not add index to parent of type array
    at Object.s [as setProperty] (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:77:883)
    at v.getEdits (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5447:852)
    at v.writeToBuffer (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5447:144)
    at v.doWriteConfiguration (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5447:12)

## Not sure if that helps or if it is even related to my problem, but there was also this in the log:

    Cannot read property 'markers' of undefined: TypeError: Cannot read property 'markers' of undefined
    at K.setTreeSelection (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7060:728)
    at K.refreshPanel (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7060:569)
    at K.onDidChangeModel (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7066:411)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7065:690
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92:235
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t.MarkersModel.setResourceMarkers (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3208:741)
    at p.onMarkerChanged (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3493:193)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3493:121
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:915

## and also this:

    TreeError [MarkersView] Tree element not found: [object Object]: Error: TreeError [MarkersView] Tree element not found: [object Object]
    at t.ObjectTreeModel.getElementLocation (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:114:613)
    at t.ObjectTreeModel.setCollapsed (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:113:855)
    at H.expand (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1106:277)
    at K.autoReveal (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7069:818)
    at K.onActiveEditorChanged (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7066:842)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7065:715
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92:235
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at F.doHandleActiveEditorChangeEvent (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6057:491)
    at F.handleActiveEditorChange (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6057:289)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6057:601
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6290:665
    at async e.openEditor (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6289:121)
    at async B.editorOpenHandler (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7025:806)
    at async B.openEditor (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6072:18)
    at async file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6999:476

____
__Does this issue occur when all extensions are disabled?: Yes/No__
Yes, it seemingly has nothing to do with extensions.
I think this is the result of me being not too smart and careful, but if someone takes time out of their day to help me resolve this issue without re-installing VSC, I'd very much appreciate it.
Thanks in advance.
If there's anything else I need to provide to help, I'll be happy to do so.

**Comment by muisance** [comment]
There was also this one in the log:
* Cannot read property 'markers' of undefined: TypeError: Cannot read property 'markers' of undefined
    at K.setTreeSelection (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7060:728)
    at K.refreshPanel (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7060:569)
    at K.onDidChangeModel (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7066:411)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7065:690
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92:235
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t.MarkersModel.setResourceMarkers (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3208:741)
    at p.onMarkerChanged (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3493:193)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3493:121
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:915

and also this:
* TreeError [MarkersView] Tree element not found: [object Object]: Error: TreeError [MarkersView] Tree element not found: [object Object]
    at t.ObjectTreeModel.getElementLocation (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:114:613)
    at t.ObjectTreeModel.setCollapsed (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:113:855)
    at H.expand (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1106:277)
    at K.autoReveal (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7069:818)
    at K.onActiveEditorChanged (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7066:842)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7065:715
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92:235
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at F.doHandleActiveEditorChangeEvent (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6057:491)
    at F.handleActiveEditorChange (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6057:289)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6057:601
    at c.fire (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6290:665
    at async e.openEditor (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6289:121)
    at async B.editorOpenHandler (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7025:806)
    at async B.openEditor (file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6072:18)
    at async file:///C:/Users/1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6999:476

**Comment by muisance** [comment]
Alright, I fixed it myself :)
Please don't close the issue just yet so that I can test and say definitely that I indeed did fix it.
If I did, however, the solution was to copy the text content of the file, create a new one, paste contents there and replace the corrupted settings file with the new one.
If that is correct you might want to look into the Notepads app – I installed it from Microsoft Shop and it still almost gave me cancer :)

**Comment by sandy081** [comment]
> replace the corrupted settings file with the new one.

May I know more about these corrupted settings? Can you please provide the contents?

**Comment by muisance** [comment]
> > replace the corrupted settings file with the new one.
> 
> May I know more about these corrupted settings? Can you please provide the contents?

I'm afraid I deleted/replaced those just to be safe, but I'll look if I did save a copy or something. But if I'm not mistaken, the actual contents of those files weren't changed by the program (Notepads, that is), I think it's just that the program itself has some issues with signatures/certificates.
I uninstalled Notepads due to obvious reasons, but since I'm a part of Insider initiative, I think it makes sense to install it again and try and replicate the process, but I'll wait for your approval just in case, if that's okay with you.

**Comment by sandy081** [comment]
I am not sure how Notepads application is relevant here? Am I missing something?

**Comment by muisance** [comment]
> I am not sure how Notepads application is relevant here? Am I missing something?

This is merely my assumption,
*HOWEVER*
I have just installed Notepads again, made a copy of a PowerShell plugin theme file and opened it with Notepads, all I did was delete one or two spaces between a hash symbol and a following letter in comments, tried to apply this theme and it gave me the same error message (please see the attached screenshot); this is the only thing that I can establish a more or less logical connection with with regards to the issue (I also used Notepads to edit the VSCode settings file and **I think** that was where this whole issue emerged; I still don't have great certainty in this, though).
Unfortunately, my copy of Windows supports only one language, and it is Russian, but essentially as far as I understand it, this error says that the file I edited with Notepads doesn't have a digital signature, but if you have anyone who understands Russian nearby, I wouldn't hold it against you if you asked them to confirm or contest this, since I'm not very smart.
![notepads](https://user-images.githubusercontent.com/66916008/90242484-d10acb80-de35-11ea-99bd-ebf1e07b3dfe.png)

I will try and replicate my issue via amending the VSCode settings file again a bit later today, since I've installed Notepads back on my PC and see what happens.

**Comment by sandy081** [comment]
Not sure if above information is helpful enough for us to repro the issue and fix it. It would be great if you can provide steps to reproduce the issue?
