### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: lambda is not defined

### ISSUE THREAD

**Issue by tomerlevi444** [microsoft/vscode#104039]
- VSCode Version: 1.47.3
- OS Version:
Windows 10 64-bit
- NodeJS version:
12.18.3

Steps to Reproduce:

1. Run an async function that throws an error and catches it.
the file I used to reproduce this:

```
const asyncFunc = async () => { throw 'error' }

(async () => {
    try {
        await asyncFunc()
    } catch (error) {
        console.log({ error })
    }
})();
```
2. When I run the code in the commandline, everything works file, but when debugging file via VSCode, The log in the debugger console shows this:

"C:\Program Files\nodejs\node.exe" "c:\tests\scripts\test.js"
Debugger listening on ws://127.0.0.1:60945/469c5377-8dd0-4a65-bc30-db4539637b80
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
null: {error: 'error'}
(node:46516) UnhandledPromiseRejectionWarning: ReferenceError: lambda is not defined
    at eval (eval at <anonymous> (c:\tests\scripts\test.js:7:9), <anonymous>:1:14)
    at eval (eval at <anonymous> (c:\tests\scripts\test.js:7:9), <anonymous>:1:53)
    at c:\tests\scripts\test.js:7:9
    at Object.<anonymous> (c:\tests\scripts\test.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:46516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:46516) UnhandledPromiseRejectionWarning: ReferenceError: lambda is not defined
    at eval (eval at <anonymous> (c:\tests\scripts\test.js:7:9), <anonymous>:1:14)
    at eval (eval at <anonymous> (c:\tests\scripts\test.js:7:9), <anonymous>:1:53)
    at c:\tests\scripts\test.js:7:9
    at Object.<anonymous> (c:\tests\scripts\test.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:46516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...
Process exited with code 0

My launch.json configuration:
```
{
      "name": "Launch Program",
      "program": "${file}",
      "request": "launch",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "pwa-node"
    }
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
I cannot reproduce this. Try the nightly build and see if it happens there: https://github.com/microsoft/vscode-js-debug#nightly-extension

/needsMoreInfo
