### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by waratah** [microsoft/vscode#104143]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.7

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at LineIndex.edit (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150099:30)
    at ScriptVersionCache._getSnapshot (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149928:47)
    at ScriptVersionCache.lineOffsetToPosition (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149947:29)
    at TextStorage.lineOffsetToPosition (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142065:33)
    at ScriptInfo.lineOffsetToPosition (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142413:41)
    at c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147801:56
    at Object.next (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:579:33)
    at ProjectService.applyChangesToFile (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146949:46)
    at ProjectService.applyChangesInOpenFiles (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146916:30)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147792:46)
    at c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149555:88
    at IOSession.Session.executeWithRequestId (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149546:28)
    at IOSession.Session.executeCommand (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149555:33)
    at IOSession.Session.onMessage (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149579:35)
    at Interface.<anonymous> (c:\Users\kfoskey\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150895:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.48.0-insider (d13d2fc56da7a2f8bcad4256212db0661fcbba45, 2020-08-05T05:30:25.429Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.7
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
tortoise-svn|fan|0.1.1
raml|jep|1.0.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
svn-scm|joh|2.12.1
vscode-github|Kni|0.30.3
refactorix|kri|0.3.6
vscode-azurefunctions|ms-|0.23.0
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurevirtualmachines|ms-|0.1.1
csharp|ms-|1.22.1
vscode-dotnet-runtime|ms-|0.1.2
mssql|ms-|1.9.0
remote-wsl|ms-|0.44.4
azure-account|ms-|0.9.1
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
angular2-inline|nat|0.0.17
angular-console|nrw|13.0.0
raml-ls|One|0.3.0
vscode-jscpd|pau|0.3.4
vscode-print|pdc|0.7.14
material-icon-theme|PKi|4.2.0
code-spell-checker|str|1.9.0
gitflow|vec|1.2.1
vscode-conventional-commits|viv|1.10.1
JavaScriptSnippets|xab|1.8.0
svn-helper|Zlo|1.0.3

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please fill in the template to the best of your ability

/needsMoreInfo
