### ISSUE TITLE
Search smoke test fails

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#104245]
Linux, run smoke test, notice error
fyi @roblourens
I manually verified that search and replace seems good.

```
VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           replaces first search result with a replace term:
     Error: Timeout: get element '.search-view .messages[aria-hidden="true"] .message>span' after 20 seconds.
      at /home/parallels/Development/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/Development/vscode/test/automation/out/code.js:9:58)
```

**Comment by roblourens** [comment]
Can't repro 🤷‍♂️

**Comment by isidorn** [comment]
Let me know if I can provde more details, or feel free to close it...
