### ISSUE TITLE
File menu option vanishes after hover.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#104224]
Issue Type: <b>Bug</b>

file menu item vanishes after hover
same is case for view, go, run, terminal options as well
edit, selection and help are working normally.
i have the file menu in the sidebar

the working screenshot for Edit menu item
![image](https://user-images.githubusercontent.com/9264813/89617850-912d6c80-d8a8-11ea-9291-453e763a747f.png)

VS Code version: Code - Insiders 1.48.0-insider (20cba51fb305868238eddc69758d259c29b3230d, 2020-08-07T05:35:24.758Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.7
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.1.3
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.132.0
remote-ssh|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|1.9.5
debugger-for-chrome|msj|4.12.9
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
sonarlint-vscode|Son|1.17.0
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.84.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by sanket-bhalerao** [comment]
@sbatten , is this fix going to be in the insiders build (August 10)?

**Comment by eamodio** [comment]
At first it seems to work, but hovering around on multiple menus (including deeply nested ones) and then coming back to say the _File_ menu causes the following errors:

```
bootstrap-window.js:216 [uncaught exception]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
onUnexpectedError @ bootstrap-window.js:216
bootstrap-window.js:219 Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Object.removeNode (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/dom.js:17)
    at Menu.dispose (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:352)
    at SubmenuMenuActionViewItem.cleanupExistingSubmenu (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:592)
    at RunOnceScheduler.runner (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:523)
    at RunOnceScheduler.doRun (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:525)
    at RunOnceScheduler.onTimeout (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:520)
onUnexpectedError @ bootstrap-window.js:219
/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/dom.js:17 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Object.removeNode (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/dom.js:17:29)
    at Menu.dispose (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:352:17)
    at SubmenuMenuActionViewItem.cleanupExistingSubmenu (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:592:41)
    at RunOnceScheduler.runner (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:523:26)
    at RunOnceScheduler.doRun (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:525:22)
    at RunOnceScheduler.onTimeout (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:520:22)
bootstrap-window.js:216 [uncaught exception]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
onUnexpectedError @ bootstrap-window.js:216
bootstrap-window.js:219 Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Object.removeNode (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/dom.js:17)
    at Menu.dispose (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:352)
    at SubmenuMenuActionViewItem.cleanupExistingSubmenu (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:592)
    at RunOnceScheduler.runner (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:523)
    at RunOnceScheduler.doRun (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:525)
    at RunOnceScheduler.onTimeout (/C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:520)
onUnexpectedError @ bootstrap-window.js:219
/C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/dom.js:17 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Object.removeNode (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/dom.js:17:29)
    at Menu.dispose (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:352:17)
    at SubmenuMenuActionViewItem.cleanupExistingSubmenu (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:592:41)
    at RunOnceScheduler.runner (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/browser/ui/menu/menu.js:523:26)
    at RunOnceScheduler.doRun (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:525:22)
    at RunOnceScheduler.onTimeout (file:///C:/Users/Eric/code/microsoft/vscode/out/vs/base/common/async.js:520:22)
```
