### ISSUE TITLE
Test failure: `this._configurationService.getValue is not a function`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#104485]
The Unit tests on Windows fail with
```
1) Unexpected Errors & Loader Errors should not have unexpected errors:

      this._configurationService.getValue is not a function
TypeError: this._configurationService.getValue is not a function
    at WordBasedCompletionItemProvider.provideCompletionItems (file:///D:/a/1/s/out/vs/editor/common/services/editorWorkerServiceImpl.js:111:73)
    at file:///D:/a/1/s/out/vs/editor/contrib/suggest/suggest.js:180:49
    at Array.map (<anonymous>)
    at Object.provideSuggestionItems (file:///D:/a/1/s/out/vs/editor/contrib/suggest/suggest.js:175:45)
    at SuggestModel.trigger (file:///D:/a/1/s/out/vs/editor/contrib/suggest/suggestModel.js:327:41)
    at file:///D:/a/1/s/out/vs/editor/contrib/suggest/test/suggestModel.test.js:170:31
    at file:///D:/a/1/s/out/vs/editor/contrib/suggest/test/suggestModel.test.js:158:21
    at new Promise (<anonymous>)
    at assertEvent (file:///D:/a/1/s/out/vs/editor/contrib/suggest/test/suggestModel.test.js:147:20)
    at file:///D:/a/1/s/out/vs/editor/contrib/suggest/test/suggestModel.test.js:169:21
    at file:///D:/a/1/s/out/vs/editor/contrib/suggest/test/suggestModel.test.js:139:29
    at new Promise (<anonymous>)
    at withOracle (file:///D:/a/1/s/out/vs/editor/contrib/suggest/test/suggestModel.test.js:126:20)
    at Context.<anonymous> (file:///D:/a/1/s/out/vs/editor/contrib/suggest/test/suggestModel.test.js:167:20)
    at callFn (file:///D:/a/1/s/node_modules/mocha/mocha.js:4471:21)
    at Test.Runnable.run (file:///D:/a/1/s/node_modules/mocha/mocha.js:4464:7)
    at Runner.runTest (file:///D:/a/1/s/node_modules/mocha/mocha.js:4934:10)
    at file:///D:/a/1/s/node_modules/mocha/mocha.js:5040:12
    at next (file:///D:/a/1/s/node_modules/mocha/mocha.js:4854:14)
    at file:///D:/a/1/s/node_modules/mocha/mocha.js:4864:7
    at next (file:///D:/a/1/s/node_modules/mocha/mocha.js:4796:14)
    at file:///D:/a/1/s/node_modules/mocha/mocha.js:4827:7
    at done (file:///D:/a/1/s/node_modules/mocha/mocha.js:4432:5)
    at callFn (file:///D:/a/1/s/node_modules/mocha/mocha.js:4489:7)
    at Hook.Runnable.run (file:///D:/a/1/s/node_modules/mocha/mocha.js:4464:7)
    at next (file:///D:/a/1/s/node_modules/mocha/mocha.js:4810:10)
    at file:///D:/a/1/s/node_modules/mocha/mocha.js:4832:5
    at timeslice (file:///D:/a/1/s/node_modules/mocha/mocha.js:75:27),this._configurationService.getValue is not a function
```

https://dev.azure.com/vscode/VSCode/_build/results?buildId=50303&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=08e986c2-058e-5f01-51da-ae4278e2d74e

**Comment by jrieken** [comment]
don't reproduce for me... some other hickup?

**Comment by aeschli** [comment]
I've seen it in 3 different builds already.
E.g. here, now on the Mac build: https://dev.azure.com/vscode/VSCode/_build/results?buildId=50345&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b16e48eb-d187-5f92-5721-e17908fef4e2
