### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by sail-sail** [microsoft/vscode#104463]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200811

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at bindThisPropertyAssignment (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:41337:22)
    at bindWorker (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:41029:37)
    at bind (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40899:13)
    at bindExpressionStatement (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39964:13)
    at bindChildren (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39450:21)
    at bind (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40910:21)
    at c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:94
    at Object.forEach (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39398:16)
    at bindEachFunctionsFirst (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:13)
    at bindChildren (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39496:21)
    at bind (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40910:21)
    at visitNode (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:26832:24)
    at Object.forEachChild (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:26962:21)
    at bindEachChild (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39401:16)
    at bindChildren (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39499:21)
    at bindContainer (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39348:17)
    at bind (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40913:21)
    at Object.forEach (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39398:16)
    at visitNodes (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:26837:24)
    at Object.forEachChild (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:27152:21)
    at bindEachChild (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39401:16)
    at bindChildren (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39499:21)
    at bindContainer (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39383:17)
    at bind (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40913:21)
    at c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:94
    at Object.forEach (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39398:16)
    at bindEachFunctionsFirst (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39391:13)
    at bindChildren (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39490:21)
    at bindContainer (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:39348:17)
    at bind (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:40913:21)
    at bindSourceFile (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:38976:17)
    at Object.bindSourceFile (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:38916:9)
    at initializeTypeChecker (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:76465:20)
    at Object.createTypeChecker (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:42923:9)
    at Object.getTypeChecker (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:103469:79)
    at synchronizeHostData (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:143443:21)
    at Proxy.getProgram (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:143525:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:148382:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:148315:42)
    at ConfiguredProject.updateGraph (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:149249:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:150953:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:151860:44)
    at c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:152187:97
    at Object.flatMap (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:152187:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:153206:46)
    at c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155078:88
    at IOSession.Session.executeWithRequestId (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155069:28)
    at IOSession.Session.executeCommand (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155078:33)
    at IOSession.Session.onMessage (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:155102:35)
    at Interface.<anonymous> (c:\Users\15126\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20200811\node_modules\typescript\lib\tsserver.js:157318:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.48.0-insider (4c23fc22ced6d0c1f58215ce91ccd08d0c8a0006, 2020-08-11T10:15:36.363Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
classdiagram-ts|Ale|0.1.33
ng-template|Ang|0.1000.7
better-toml|bun|0.3.2
bracket-select|chu|2.0.2
bracket-pair-colorizer-2|Coe|0.2.0
javascript-ejs-support|Dig|1.3.1
vscode-npm-script|eg2|0.3.13
vscode-drawio|eig|1.0.3
generateuuid|Fir|0.0.5
npm-dependency-links|her|1.1.0
vscode-npm-dependency|how|1.2.2
output-colorizer|IBM|0.1.2
bridlensis|idl|1.0.1
comment-translate|int|1.4.2
vscode-edit-csv|jan|0.3.0
docthis|joe|0.7.1
json-to-ts|Mar|1.7.5
vscode-language-pack-zh-hans|MS-|1.48.2
cpptools|ms-|0.29.0
vscode-typescript-next|ms-|4.1.20200811
vetur|oct|0.26.1
vscode-html-scss|P-d|0.0.42
vscode-xml|red|0.13.0
sass-indented|rob|1.5.1
rust|rus|0.7.8
vscode-icons|vsc|10.2.0

</details>

**Comment by mjbvz** [comment]
Please try to fill in the steps to reproduce
