### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by dmgauthier** [microsoft/vscode#104510]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200811

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at bindThisPropertyAssignment (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:41337:22)
    at bindWorker (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:41029:37)
    at bind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40899:13)
    at bindExpressionStatement (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39964:13)
    at bindChildren (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39450:21)
    at bind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40910:21)
    at /home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39391:94
    at Object.forEach (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39398:16)
    at bindEachFunctionsFirst (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39391:13)
    at bindChildren (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39496:21)
    at bind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40910:21)
    at visitNode (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:26832:24)
    at Object.forEachChild (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:26962:21)
    at bindEachChild (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39401:16)
    at bindChildren (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39499:21)
    at bindContainer (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39348:17)
    at bind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40913:21)
    at maybeBind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40184:21)
    at bindBinaryExpressionFlow (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40132:25)
    at bindChildren (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39462:21)
    at bind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40910:21)
    at bindExpressionStatement (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39964:13)
    at bindChildren (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39450:21)
    at bind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40910:21)
    at /home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39391:94
    at Object.forEach (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39398:16)
    at bindEachFunctionsFirst (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39391:13)
    at bindChildren (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39490:21)
    at bindContainer (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:39348:17)
    at bind (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:40913:21)
    at bindSourceFile (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:38976:17)
    at Object.bindSourceFile (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:38916:9)
    at initializeTypeChecker (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:76465:20)
    at Object.createTypeChecker (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:42923:9)
    at Object.getTypeChecker (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:103469:79)
    at synchronizeHostData (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:143443:21)
    at Proxy.getProgram (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:143525:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:148382:53)
    at ConfiguredProject.Project.updateGraph (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:148315:42)
    at ConfiguredProject.updateGraph (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:149249:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:150953:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:151860:44)
    at /home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:152187:97
    at Object.flatMap (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:152187:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:153206:46)
    at /home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:155078:88
    at IOSession.Session.executeWithRequestId (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:155069:28)
    at IOSession.Session.executeCommand (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:155078:33)
    at IOSession.Session.onMessage (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:155102:35)
    at Interface.<anonymous> (/home/dgauthier/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200811/node_modules/typescript/lib/tsserver.js:157318:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 3993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|30.99GB (20.20GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
prettier-vscode|esb|5.1.3
vscode-typescript-next|ms-|4.1.20200811
typescript-hero|rbb|3.0.0
vscode-icons|vsc|10.2.0

</details>

**Comment by mjbvz** [comment]
Can you share the file that causes this issue?
