### ISSUE TITLE
Issue in install & update extention

### ISSUE THREAD

**Issue by osamamosaad** [microsoft/vscode#104501]
Issue Type: <b>Bug</b>

This issue was from a long time in this version 
I have been waiting until there is a fix for it, but there is not any new version released 

the problem as the title says when I am trying to install any extension there is an error comes up to me, and after opened up the inspector I saw these errors I hop it is helpful

-----
oad resource: net::ERR_NAME_NOT_RESOLVED
Microsoft.VisualStudio.Services.Icons.Default:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
Microsoft.VisualStudio.Services.Icons.Default:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR XHR failed: downloading: XHR failed
    at file:///snap/code/39/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:700
github.gallerycdn.vsassets.io/extensions/github/vscode-pull-request-github/0.18.1/1594656504277/Microsoft.VisualStudio.Code.Manifest:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
github.gallerycdn.vsassets.io/extensions/github/vscode-pull-request-github/0.18.1/1594656504277/Microsoft.VisualStudio.Services.Icons.Default:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2947 Unable to open 'Extension: GitHub Pull Requests and Issues': XHR failed.
onDidChangeNotification @ /snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2947
github.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/vscode-pull-request-github/0.18.1/assetbyname/Microsoft.VisualStudio.Code.Manifest:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
Microsoft.VisualStudio.Services.Icons.Default:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6687 Error: XHR failed
(anonymous) @ /snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6687
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2947 Failed to install 'github.vscode-pull-request-github'.
onDidChangeNotification @ /snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2947
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR XHR failed: downloading: XHR failed
    at file:///snap/code/39/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:700
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6696 Error: XHR failed
(anonymous) @ /snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6696
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2947 Failed to update 'bmewburn.vscode-intelephense-client'.
onDidChangeNotification @ /snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2947
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR XHR failed: downloading: XHR failed
    at file:///snap/code/39/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:700

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|11.60GB (1.16GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-intelephense-client|bme|1.4.1
gitlens|eam|10.2.2
php-debug|fel|1.13.0
smarty|imp|0.3.0
php-namespace-resolver|Meh|1.1.8
sublime-keybindings|ms-|4.0.7
php-docblocker|nei|2.1.0
ci-snippets|sec|0.0.2
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-icons|vsc|10.1.1

</details>

**Comment by osamamosaad** [comment]
Fixed, it was a DNS issue
The solution here: https://www.elharony.com/failed-to-install-this-extension-vscode/
thanks
