### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wensmoke** [microsoft/vscode#104536]
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
RangeError: Maximum call stack size exceeded
    at fresh (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149807:32)
    at EditWalker.pre (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149828:37)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150203:29)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
    at LineNode.execWalk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150206:47)
    at LineNode.walk (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150236:30)
```

CPUs	Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 1076)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: disabled_software
skia_renderer: disabled_off_ok
video_decode: unavailable_off
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off_ok
webgl: enabled
webgl2: enabled
Load (avg)	3, 4, 4
Memory (System)	7.22GB (1.67GB free)
Process Argv	--no-sandbox --unity-launch
Screen Reader	no
VM	0%

vscode-tomcat | ada | 0.11.3
-- | -- | --
vscode-eslint | dba | 2.1.8
prettier-vscode | esb | 5.1.3
mp-rest-client-generator-vscode-ext | Mic | 0.1.1
mp-starter-vscode-ext | Mic | 0.2.5
vscode-microprofile-pack | Mic | 0.0.3
vscode-language-pack-zh-hans | MS- | 1.48.1
korofileheader | OBK | 4.7.4
vetur | oct | 0.26.1
liberty-dev-vscode-ext | Ope | 0.1.6
payara-vscode | Pay | 0.0.4
vscode-boot-dev-pack | Piv | 0.0.8
vscode-spring-boot | Piv | 1.20.0
java | red | 0.65.0
vscode-quarkus | red | 1.6.0
rainbow-fart | sae | 1.4.0
vscode-checkstyle | she | 1.3.3
vscodeintellicode | Vis | 1.2.10
vscode-java-debug | vsc | 0.27.1
vscode-java-dependency | vsc | 0.11.0
vscode-java-pack | vsc | 0.10.0
vscode-java-test | vsc | 0.24.0
vscode-maven | vsc | 0.24.0
vscode-spring-boot-dashboard | vsc | 0.1.10
vscode-spring-initializr | vsc | 0.4.8

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, can you share the project or file that causes this?

**Comment by mjbvz** [comment]
Closing as not actionable without information about the file/project that triggered this error
