### ISSUE TITLE
Remote SSH fails with timeout

### ISSUE THREAD

**Issue by boffman** [microsoft/vscode#104631]
I get this problem trying to run Remote SSH to a Linux host: 

"Failed to connect to the remote extension host server (Error: Time limit reached)"

Could it be some limitation because I'm using VPN to work? My colleague can run Remote SSH in VS code to the same machine, but he's not running VPN.. And probably runs another version of VS code than I do.

I can SSH to the machine.. But are there some way to verify this "tunneling magic stuff" manually or so? :-) Thanks

My VS Code About info: 

Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Remote SSH log follows:

[10:11:58.681] Log Level: 2
[10:11:58.690] remote-ssh@0.51.0
[10:11:58.691] win32 x64
[10:11:58.692] SSH Resolver called for "ssh-remote+xyzoptim10.xyznet.int", attempt 1
[10:11:58.692] SSH Resolver called for host: xyzoptim10.xyznet.int
[10:11:58.692] Setting up SSH remote "xyzoptim10.xyznet.int"
[10:11:59.672] Using commit id "db40434f562994116e5b21c24015a2e40b2504e6" and quality "stable" for server
[10:11:59.674] Install and start server if needed
[10:12:01.178] Checking ssh with "ssh -V"
[10:12:01.237] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[10:12:01.239] Running script with connection command: ssh -T -D 63916 xyzoptim10.xyznet.int bash
[10:12:01.249] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:12:01.429] > 
[10:12:01.429] Got some output, clearing connection timeout
[10:12:01.646] > The authenticity of host 'xyzoptim10.xyznet.int (10.0.56.161)' can't be establis
> hed.
> ECDSA key fingerprint is SHA256:WT87q1+R7nwDklZm+h00AXodI5Gt89/wE9byE5wF1lU.
> Are you sure you want to continue connecting (yes/no)?
[10:12:01.647] Detected fingerprint confirmation message
[10:12:01.647] Showing fingerprint confirmation dialog
[10:12:04.330] Got fingerprint response: yes
[10:12:04.331] "install" wrote data to terminal: "yes"
[10:12:04.367] > Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added 'xyzoptim10.xyznet.int,10.0.56.161' (ECDSA) to the li
> st of known hosts.
> 
[10:12:04.519] > usr1234@xyzoptim10.xyznet.int's password:
[10:12:04.519] Showing password prompt
[10:12:09.238] Got password response
[10:12:09.238] "install" wrote data to terminal: "**********"
[10:12:09.275] > 
> 
[10:12:09.702] > 57cfe0791c96: running
> 
[10:12:09.738] > Acquiring lock on /home/usr1234/.vscode-server/bin/db40434f562994116e5b21c24015a
> 2e40b2504e6/vscode-remote-lock.usr1234.db40434f562994116e5b21c24015a2e40b2504e6
> \ln /home/usr1234/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/vs
> code-remote-lock.usr1234.db40434f562994116e5b21c24015a2e40b2504e6.target /home/c
> sk4446/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/vscode-remote
> -lock.usr1234.db40434f562994116e5b21c24015a2e40b2504e6
> 
[10:12:09.764] > Found existing installation at /home/usr1234/.vscode-server/bin/db40434f56299411
> 6e5b21c24015a2e40b2504e6...
> 
[10:12:09.827] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 35470 with wget
> 
[10:12:09.865] > 57cfe0791c96: start
> sshAuthSock====
> agentPort==35470==
> osReleaseId==rhel==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/1521048302==
> platform==linux==
> 57cfe0791c96: end
> 
[10:12:09.866] Received install output: 
sshAuthSock====
agentPort==35470==
osReleaseId==rhel==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1521048302==
platform==linux==

[10:12:09.867] Remote server is listening on port 35470
[10:12:09.867] Parsed server configuration: {"agentPort":35470,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1521048302","platform":"linux"}
[10:12:09.868] Starting forwarding server. localPort 63920 -> socksPort 63916 -> remotePort 35470
[10:12:09.869] Forwarding server listening on 63920
[10:12:09.869] Waiting for ssh tunnel to be ready
[10:12:09.871] Tunneled remote port 35470 to local port 63920
[10:12:09.871] Resolved "ssh-remote+xyzoptim10.xyznet.int" to "127.0.0.1:63920"
[10:12:09.872] [Forwarding server 63920] Got connection 0
[10:12:09.880] ------

[10:12:09.916] Failed to set up socket for dynamic port forward to remote port 35470: Socket closed. Is the remote port correct?
[10:12:10.879] [Forwarding server 63920] Got connection 1
[10:12:10.879] [Forwarding server 63920] Got connection 2
[10:12:10.895] > channel 3: open failed: administratively prohibited: open failed
> 
[10:12:10.920] Failed to set up socket for dynamic port forward to remote port 35470: Socket closed. Is the remote port correct?
[10:12:10.920] Failed to set up socket for dynamic port forward to remote port 35470: Socket closed. Is the remote port correct?
[10:12:10.961] > channel 3: open failed: administratively prohibited: open failed
> channel 4: open failed: administratively prohibited: open failed
> 
[10:12:13.893] Unhandled rejection: Error: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.
    at D.reject (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5544:245)
    at D.resolveAndValidate (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5547:116)
    at D.doWriteConfiguration (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5541:414)
    at Object.factory (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5541:190)
    at u.consume (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:130:421)
    at file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:130:236
    at new Promise (<anonymous>)
    at u.queue (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:130:160)
    at D.writeConfiguration (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5541:175)
    at C.writeConfigurationValue (file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5569:356)
    at file:///C:/Users/usr1234/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5557:594
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[10:15:09.851] >

**Comment by NotWearingPants** [comment]
Does using `ssh` directly work?

**Comment by boffman** [comment]
Yes, I can log in manually with ssh.

**Comment by roblourens** [comment]
Does it work if you run the "Kill VS Code Server on Host" command and try again?
