### ISSUE TITLE
Error while starting Sync: d is not iterable

### ISSUE THREAD

**Issue by JackieZheng** [microsoft/vscode#104796]
![image](https://user-images.githubusercontent.com/3202385/90377609-c9a02800-e0aa-11ea-83d3-928f42b4900c.png)

#Log(Settings Sync)
```
[2020-08-17 16:30:31.605] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-08-17 16:30:31.605] [userDataSync] [info] Auto Sync is disabled.
[2020-08-17 16:31:05.385] [userDataSync] [info] Did reset the local sync state.
[2020-08-17 16:31:09.330] [userDataSync] [info] Settings: Stopped synchronizing settings.
[2020-08-17 16:51:01.669] [userDataSync] [info] Did reset the local sync state.
[2020-08-17 16:51:08.590] [userDataSync] [info] Settings: Stopped synchronizing settings.
```
# Log(Window)
```
 [2020-08-17 16:31:07.272] [renderer1] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Pending request cancelled: /v2/getcodeactions
[2020-08-17 16:31:09.326] [renderer1] [error] d is not iterable: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: d is not iterable
    at Function.e.toUserDataSyncError (file:///D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2811:935)
    at Object.call (file:///D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5832:376)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-17 16:51:08.587] [renderer1] [error] d is not iterable: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: d is not iterable
    at Function.e.toUserDataSyncError (file:///D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2811:935)
    at Object.call (file:///D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5832:376)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by sandy081** [comment]
#103839

**Comment by JackieZheng** [comment]
> #103839

turning off "Keyboard binging" worked for me.
