### ISSUE TITLE
overflow widget option breaks embedded editors in notebook

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105073]
* open GHI notebook
* run peek references on a variable
* 🐛 the peek editor is broken

The error below is printed. I have debugged this and the problem seems to that `EmbeddedCodeEditor`-instances inherit the raw options from their parent editor. However, those options are cloned which breaks the html element.

```
 ERR overflowWidgetsDomNode.appendChild is not a function: TypeError: overflowWidgetsDomNode.appendChild is not a function
    at new View (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:100:40)
    at EmbeddedCodeEditorWidget._createView (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1177:26)
    at EmbeddedCodeEditorWidget._attachModel (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1099:46)
    at EmbeddedCodeEditorWidget.setModel (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:247:18)
    at ReferenceWidget._revealReference (file:///Users/jrieken/Code/vscode/out/vs/editor/contrib/gotoSymbol/peek/referencesWidget.js:428:31)
```

**Comment by jrieken** [comment]
fyi - I have pushed https://github.com/microsoft/vscode/commit/88b7db28155b2c9f8fd9a71300687c601d44b945 to workaround this

**Comment by joaomoreno** [comment]
The workaround actually looks like a great fix.

**Comment by rebornix** [comment]
I like the fix as well.

**Comment by jrieken** [comment]
sold
