### ISSUE TITLE
Frozen Jupyter Notebook VSCode editor when running on remote 

### ISSUE THREAD

**Issue by nemonominem** [microsoft/vscode#105125]
Issue Type: <b>Bug</b>

Hello,
I have hit some blocking issue which may prevent us from deploying vscode as a Jupyter notebook development platform.

I am able to connect via OpenSSH to my remote folder and to open some notebook, but after executing a few cells the notebook becomes irresponsive (the cells stop being computed and I cannot switch kernels).
The only trace of a problem I can find is in the Windows log, where I can see that vscode keep reconnecting and droping the conection to the remote every 30 seconds or so.
This never stops even after I close the notebook.

Can you please investigate?
Thanks,
Gilles

[2020-08-21 16:45:00.496] [renderer1] [info] [remote-connection][ExtensionHost][24ced…][reconnect] reconnected!
[2020-08-21 16:45:03.767] [renderer1] [trace] telemetry/UnhandledError {"msg":"write ECONNABORTED","callstack":"Error: write ECONNABORTED\n\tat afterWriteDispatched (internal/stream_base_commons.js:149:25)\n\tat writeGeneric (internal/stream_base_commons.js:140:3)\n\tat Socket._writeGeneric (net.js:776:11)\n\tat Socket._write (net.js:788:8)\n\tat doWrite (_stream_writable.js:435:12)\n\tat writeOrBuffer (_stream_writable.js:419:5)\n\tat Socket.Writable.write (_stream_writable.js:309:11)\n\tat Socket.ondata (_stream_readable.js:728:22)\n\tat Socket.emit (events.js:223:5)\n\tat addChunk (_stream_readable.js:309:12)\n\tat readableAddChunk (_stream_readable.js:290:11)\n\tat Socket.Readable.push (_stream_readable.js:224:10)\n\tat TCP.onStreamRead (internal/stream_base_commons.js:181:23)","count":1,"VSCode.ABExp.Features":"","abexp.assignmentcontext":""}
[2020-08-21 16:45:20.421] [renderer1] [info] [remote-connection][ExtensionHost][24ced…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-08-21 16:45:20.422] [renderer1] [info] [remote-connection][ExtensionHost][24ced…][reconnect] waiting for 5 seconds before reconnecting...
[2020-08-21 16:45:25.423] [renderer1] [info] [remote-connection][ExtensionHost][24ced…][reconnect] resolving connection...
[2020-08-21 16:45:25.423] [renderer1] [info] [remote-connection][ExtensionHost][24ced…][reconnect] connecting to 127.0.0.1:60225...
[2020-08-21 16:45:25.424] [renderer1] [trace] [remote-connection][ExtensionHost][24ced…][reconnect][127.0.0.1:60225] 1/6. invoking socketFactory.connect().
[2020-08-21 16:45:27.045] [renderer1] [trace] [remote-connection][ExtensionHost][24ced…][reconnect][127.0.0.1:60225] 2/6. socketFactory.connect() was successful.
[2020-08-21 16:45:27.046] [renderer1] [trace] [remote-connection][ExtensionHost][24ced…][reconnect][127.0.0.1:60225] 3/6. sending AuthRequest control message.
[2020-08-21 16:45:27.088] [renderer1] [error] write ECONNABORTED: Error: write ECONNABORTED
	at afterWriteDispatched (internal/stream_base_commons.js:149:25)
	at writeGeneric (internal/stream_base_commons.js:140:3)
	at Socket._writeGeneric (net.js:776:11)
	at Socket._write (net.js:788:8)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Socket.Writable.write (_stream_writable.js:309:11)
	at Socket.ondata (_stream_readable.js:728:22)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-08-21 16:45:27.494] [renderer1] [trace] [remote-connection][ExtensionHost][24ced…][reconnect][127.0.0.1:60225] 4/6. received SignRequest control message.
[2020-08-21 16:45:27.495] [renderer1] [trace] [remote-connection][ExtensionHost][24ced…][reconnect][127.0.0.1:60225] 5/6. sending ConnectionTypeRequest control message.
[2020-08-21 16:45:28.021] [renderer1] [trace] [remote-connection][ExtensionHost][24ced…][reconnect][127.0.0.1:60225] 6/6. handshake finished, connection is up and running after 2597 ms!
[2020-08-21 16:45:28.103] [renderer1] [info] [remote-connection][ExtensionHost][24ced…][reconnect] reconnected!

VS Code version: Code - Insiders 1.49.0-insider (8e872f41d4ba7807e58938bbf861ca6a22d534aa, 2020-08-20T05:37:43.249Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-1127.13.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.03GB free)|
|Process Argv|--crash-reporter-id ac2486d6-f967-48c8-99ef-c51a1f181949|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxxxx|
|OS|Linux x64 3.10.0-1127.13.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (64 x 2100)|
|Memory (System)|503.60GB (3.25GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-remote-extensionpack|ms-|0.20.0
add-new-line-to-files|jdf|0.1.1
python|ms-|2020.8.101144

(2 theme extensions excluded)

</details>

**Comment by nemonominem** [comment]
Yes, I checked all that. Tried removing most extensions, did a complete uninstall and reinstall, tried to turn off jedi, etc.
Still the same problem.

This typically happens with a complex notebook and the first cell that may take a god 20 secs to compute. The re-connection attempts seem to be freezing the UI (or slowing it down to be near responsive).
Sometimes if the notebook is not too complex it will eventually fall back on its feet. For more complex notebooks it's an endless freeze of the UI (I can't switch kernel in another open notebook for instance).

I am not sure why the UI is allowed to freeze. This makes VSCode unsuitable for any ML or data preparation job. So promising, but short on delivery.

**Comment by rebornix** [comment]
@nemonominem can you help share a screenshot of the window and help me figure out whether you are using a legacy webview based notebook or a new native one?

**Comment by nemonominem** [comment]
Hi,

I am not using the preview Notebook Editor. It just does not work for us as:
- it does not support some key graph types (plotly, bokeh) -> 'No renderer could be found for MIME type: application/vnd.plotly.v1+json'
- it does not support markdown cell styling using CSS (we use that all the time for markdown cells highlighting an coloring). So for instance <div class='blue'><h2>0. Set-Up:</h2></div> shows nothing.

So we use the Python extension support for notebooks instead. After tuning the time-out settings most notebooks now work perfectly fine. We still can't run one notebook that has many quite complex plotly graphs - that one still gets the usual timeout which results in a non-responsive VSCode UI.

This is an image of the notebook getting stuck and never opening, with the constant disconnections/reconnections.
![image](https://user-images.githubusercontent.com/6328083/91794444-297ffc80-ec6f-11ea-8915-34f61887b9c5.png)

Tx,
Gilles

**Comment by rebornix** [comment]
@nemonominem thanks for the info, it means it's an issue with the Python extension you are using, please file issue against https://github.com/microsoft/vscode-python, thanks!

/extPython
