### ISSUE TITLE
Maximum call stack size when opening panel

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105288]
VS Code insiders.

1. Cmd + j to open panel

Panel is slow to open, checkout Dev Tools Console.
I can not repro consistently. Sorry for bad steps, but I hope the stack trace helps

```
Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at Object.t.parseHex (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:42:477)
    at Function.fromHex (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:38:143)
    at f (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2134:618)
    at Object.resolveDefaultColor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2115:141)
    at I.getDefault (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5834:141)
    at I.getColor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5831:993)
    at f (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2134:631)
    at Object.resolveDefaultColor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2115:141)
    at I.getDefault (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5834:141)
    at I.getColor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5831:993)
    at Object.colors (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6634:839)
    at e.updateStyles (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6472:592)
    at e.updateActivity (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6474:527)
    at e.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6474:356)
    at e.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6478:797)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1006:363
    at Array.forEach (<anonymous>)
    at c.push (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1005:914)
    at _.computeSizes (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6502:563)
    at _.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6500:157)
    at e.layoutCompositeBar (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6644:508)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6644:263)
    at v.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:614:11)
    at v.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:583:600)
    at S.layoutViews (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:595:864)
    at S.setViewVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:587:789)
    at m.setChildVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:608:893)
    at f.setViewVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:620:359)
    at p.setViewVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:407)
    at O.setPanelHidden (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6686:611)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6681:513
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at e.setVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3143:491)
```

**Comment by sbatten** [comment]
I can't tell from the stack where the recursion takes place, I'll try to repro but if you happened to recall any additional info that would be great.

**Comment by isidorn** [comment]
If I see it again I will let you know. For now I have no more useful details - sorry!

**Comment by effektsvk** [comment]
Hello, I think I'm having the same issue. [Here's](https://gist.github.com/effektsvk/1ef2dd6c3376cd998aacfcf90a50c021) my log from dev tools.

**Comment by sbatten** [comment]
@effektsvk your issue appears to be #105480, thanks for the stack

I'm still not sure about this one though
