### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fcc4developer** [microsoft/vscode#105358]
We have written the needed data into your clipboard because it was too large to send. Please paste.
**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
RangeError: Maximum call stack size exceeded
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18317:26)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindCallExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31437:21)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30594:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18462:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindAccessExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31419:17)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30591:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18471:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindCallExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31437:21)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30594:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18462:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindAccessExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31419:17)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30591:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18471:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindCallExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31437:21)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30594:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18462:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindAccessExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31419:17)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30591:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18471:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindCallExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31437:21)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30594:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18462:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindAccessExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31419:17)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30591:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18471:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindCallExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31437:21)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30594:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18462:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindAccessExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31419:17)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30591:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18471:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindCallExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31437:21)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30594:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18462:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindAccessExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31419:17)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30591:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18471:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindCallExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31437:21)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30594:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18462:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
    at bindAccessExpressionFlow (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31419:17)
    at bindChildrenWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30591:21)
    at bindChildren (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30487:17)
    at bind (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32002:21)
    at visitNode (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18281:24)
    at Object.forEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18471:24)
    at bindEachChild (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30517:16)
```

**Comment by mjbvz** [comment]
You are on an old TS version: 3.8.3

Do you see this when using TS 4.0+ (which is included in the current VS Code insiders builds)
