### ISSUE TITLE
TS Server fatal error:  Cannot destructure property 'name' of 'object null' as it is null.

### ISSUE THREAD

**Issue by snailuj** [microsoft/vscode#105396]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.8.3-pnpify

**Steps to reproduce crash**
1. I was just renaming symbol but have had this happen several times, will enable tsserver logging

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot destructure property 'name' of 'object null' as it is null.
    at getPackageInformation (/home/julian/coding/treshna/mrimpossible/.pnp.js:24879:5)
    at Object.getPackageInformation (/home/julian/coding/treshna/mrimpossible/.pnp.js:25222:20)
    at getPnpTypeRoots (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28763:42)
    at getDefaultTypeRoots (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28779:24)
    at getEffectiveTypeRoots (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28732:20)
    at Object.getAutomaticTypeDirectiveNames (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28909:29)
    at Object.createProgram (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:97895:56)
    at synchronizeHostData (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:135345:26)
    at Proxy.getProgram (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:135437:13)
    at InferredProject.Project.updateGraphWorker (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:139913:53)
    at InferredProject.Project.updateGraph (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:139856:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:141832:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:143259:26)
    at /home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:143523:107
    at Object.mapDefined (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:143523:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:144387:46)
    at /home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146130:88
    at IOSession.Session.executeWithRequestId (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146121:28)
    at IOSession.Session.executeCommand (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146130:33)
    at IOSession.Session.onMessage (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146154:35)
    at Interface.<anonymous> (/home/julian/coding/treshna/mrimpossible/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:147469:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 4.19.0-10-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.35GB (1.50GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.0
vscode-twitter|aus|0.8.3
awarest-align|awa|1.1.0
lit-html|bie|1.11.1
vscode-multi-line-tricks|big|0.0.3
vscode-intelephense-client|bme|1.5.4
multi-cursor-case-preserve|Car|1.0.5
vscode-jumpy|che|0.3.3
vscode-postgres|cko|1.1.11
sql-formatter|cym|1.0.2
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.8
beautify|Hoo|1.5.0
elixir-ls|Jak|0.5.0
reason-vscode|jar|1.7.11
language-haskell|jus|3.3.0
regionfolder|map|1.0.12
vscode-language-babel|mgm|0.0.29
language-gettext|mro|0.2.0
vscode-docker|ms-|1.5.0
python|ms-|2020.8.103604
vsliveshare|ms-|1.0.2666
shunt|myc|1.0.1
autodocstring|njp|0.5.3
react-proptypes-intellisense|OfH|1.0.3
fluent-syntax-highlighting|pau|0.0.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.13
haskelly|UCL|0.5.5
highlight-matching-tag|vin|0.9.9
vscode-icons|vsc|10.2.0
jinja|who|0.0.8
vscode-eex-beautify|zer|0.1.8

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
You are on an old TS version. Do you see this issue when using a normal TypeScript 4.0+ build?
