### ISSUE TITLE
Workbench broken after startup

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105480]
reopened a workspace this morning and the bottom panel was broken, console shows error below

<img width="1136" alt="Screenshot 2020-08-27 at 09 50 52" src="https://user-images.githubusercontent.com/1794099/91413083-e8d94b00-e84a-11ea-94b9-7cb9c6e8540e.png">

```
  ERR Cannot read property 'setViewVisible' of undefined: TypeError: Cannot read property 'setViewVisible' of undefined
    at O.setPanelHidden (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6737:611)
    at Object.hidePart (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6685:609)
    at _.resetActiveComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6552:609)
    at _.hideComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6551:529)
    at e.hideComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6690:467)
    at e.onDidChangeActiveViews (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6689:321)
    at e.onDidRegisterPanels (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6687:917)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6689:651
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at l.registerComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3147:308)
    at l.registerPanel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4162:391)
    at k.registerPanel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6039:533)
    at k.registerViewletOrPanel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6038:777)
    at k.onDidRegisterViewContainer (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6032:365)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6030:59
    at Array.forEach (<anonymous>)
    at new k (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6030:43)
    at d._createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1682:519)
    at d._createServiceInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1684:540)
    at d._createServiceInstanceWithOwner (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1684:65)
    at d._createAndCacheServiceInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1683:756)
    at d._getOrCreateServiceInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1683:44)
    at Object.get (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1681:596)
    at O.initLayout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6712:220)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6781:907
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1681:465)
    at O.startup (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6781:758)
    at q.open (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7941:911)
workbench.desktop.main.js:1700   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by bpasero** [comment]
@sbatten related/duplicate:
* Maximum call stack size when opening panel #105288
* Bottom panel sometimes blank when opening a new window #103886
* Cannot read property 'setViewVisible' of undefined #101650
* TypeError: Cannot read property 'setViewVisible' of undefined #90836

**Comment by sandy081** [comment]
`setViewVisible` is a grid method and this seems coming from layout which I do not have any clue.

**Comment by sbatten** [comment]
Based on the stack and investigation, this happens when the restored panel is empty and we try to hide the panel in that case but the workbench is not fully initialized. I don't have a good way to reproduce it so I've just prevented hiding the panel before the workbench is initialized and hopefully this is sufficient.

**Comment by connor4312** [comment]
I've not seen this for the last week, marking verified
