### ISSUE TITLE
Problem connecting to the extensions Marketplace on vscode

### ISSUE THREAD

**Issue by goncalof87** [microsoft/vscode#105441]
Hello since last month i cannot connect to the extensions Marketplace dont know how to fix it and cant find the solution on the net, any help?

Best regards

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)


Can you also provide your system details?

**Comment by goncalof87** [comment]
![error2](https://user-images.githubusercontent.com/55550190/91639110-2a652400-ea0c-11ea-87fc-2bb27cac351b.png)
![vs error](https://user-images.githubusercontent.com/55550190/91639111-2b965100-ea0c-11ea-846d-d617e79efe77.jpg)

**Comment by goncalof87** [comment]
![vs error](https://user-images.githubusercontent.com/55550190/91639113-3d77f400-ea0c-11ea-8d9f-05f9f0a3ee26.jpg)
![error2](https://user-images.githubusercontent.com/55550190/91639117-41a41180-ea0c-11ea-9786-45fcf7a74053.png)

**Comment by sandy081** [comment]
@goncalof87 Can you please confirm if you followed all steps from https://github.com/microsoft/vscode/issues/105441#issuecomment-681962750

**Comment by goncalof87** [comment]
Sorry for the time i took not near the computer last days.
Yes i followed all steps, it is not a DNS problem because i was able to open the page

there are the logs:

log(shared) : 

[2020-08-26 17:39:48.522] [sharedprocess] [info] main {"machineId":"63e6c7e56166a48136c884262fb426cd17405dbfc89534fdd5abd324e8ed5a42","windowId":2}
[2020-08-26 17:40:30.401] [sharedprocess] [info] Starting to clean up unused language packs.

log(Window):  

[2020-08-26 18:23:30.199] [renderer1] [error] Illegal value for `line`: Error: Illegal value for `line`
    at d._lineAt (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:478:822)
    at Object.lineAt (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:477:797)
    at FunctionBlock.getBlock (c:\Users\gonca\.vscode\extensions\neilbrayfield.php-docblocker-2.1.0\out\src\block.js:77:41)
    at new Block (c:\Users\gonca\.vscode\extensions\neilbrayfield.php-docblocker-2.1.0\out\src\block.js:28:32)
    at new FunctionBlock (c:\Users\gonca\.vscode\extensions\neilbrayfield.php-docblocker-2.1.0\out\src\block\function.js:16:9)
    at Documenter.autoDocument (c:\Users\gonca\.vscode\extensions\neilbrayfield.php-docblocker-2.1.0\out\src\documenter.js:29:20)
    at Completions.provideCompletionItems (c:\Users\gonca\.vscode\extensions\neilbrayfield.php-docblocker-2.1.0\out\src\completions.js:280:43)
    at d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:690:422
    at d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:136
    at new Promise (<anonymous>)
    at Object.t.asPromise (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:108)
    at U.provideCompletionItems (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:690:393)
    at d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:707:455
    at K._withAdapter (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:698:331)
    at K.$provideCompletionItems (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:707:433)
    at m._doInvokeHandler (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:926)
    at m._invokeHandler (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:618)
    at m._receiveRequest (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:201)
    at m._receiveOneMessage (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:817:6)
    at d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:815:161
    at l.fire (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
    at v.fire (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:494)
    at d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1007:179
    at l.fire (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
    at v.fire (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:494)
    at t.PersistentProtocol._receiveMessage (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:244:17)
    at d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:241:67
    at l.fire (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
    at p.acceptChunk (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:949)
    at d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:301
    at Socket.t (d:\2.Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:245:572)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by sandy081** [comment]
Looks like there is a `ERR_CONNECTION_RESET` error, can you please open dev tools > network tab and confirm this for marketplace requests?

**Comment by goncalof87** [comment]
Hello, i think i solved the problem, i had a pendent update of windows, when i made it it worked, a bit weird but solved, apologize for taking your time and thanks for the help ;)
