### ISSUE TITLE
TS Server fatal error:  Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by mterrel** [microsoft/vscode#105539]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.4.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:127107:43)
    at ProjectService.addFilesToNonInferredProject (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:127002:22)
    at ProjectService.updateRootAndOptionsOfNonInferredProject (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:127145:22)
    at ProjectService.loadConfiguredProject (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:127081:22)
    at ProjectService.createAndLoadConfiguredProject (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:127026:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:127031:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:127839:44)
    at /home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:128055:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:128055:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:128801:46)
    at /home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/home/mark/unbounded/adapt/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 4.14.186-146.268.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|5, 4, 4|
|Memory (System)|15.66GB (1.74GB free)|
|Process Argv|.. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
auto-rename-tag|for|0.1.4
go|gol|0.16.1
vscode-docker|ms-|1.5.0
python|ms-|2020.8.103604
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.10
stylelint|shi|0.51.0
vscode-autohide|sir|1.0.6
vim|vsc|1.16.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as this is an old TS version. If you see this in TS 4.0+, please open a new issue
