### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script should not exist and not be open already

### ISSUE THREAD

**Issue by timmackey** [microsoft/vscode#105508]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.4.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression: Script should not exist and not be open already
    at ProjectService.applyChangesInOpenFiles (c:\Users\Tim\Documents\__ngTTMv800\angular\node_modules\typescript\lib\tsserver.js:128029:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\Tim\Documents\__ngTTMv800\angular\node_modules\typescript\lib\tsserver.js:128801:46)
    at c:\Users\Tim\Documents\__ngTTMv800\angular\node_modules\typescript\lib\tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (c:\Users\Tim\Documents\__ngTTMv800\angular\node_modules\typescript\lib\tsserver.js:130457:28)
    at IOSession.Session.executeCommand (c:\Users\Tim\Documents\__ngTTMv800\angular\node_modules\typescript\lib\tsserver.js:130466:33)
    at IOSession.Session.onMessage (c:\Users\Tim\Documents\__ngTTMv800\angular\node_modules\typescript\lib\tsserver.js:130488:35)
    at Interface.<anonymous> (c:\Users\Tim\Documents\__ngTTMv800\angular\node_modules\typescript\lib\tsserver.js:131789:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
tsco|alj|1.0.20
angular2-snippets|dan|1.0.21
gitlens|eam|10.2.2
vscode-firefox-debug|fir|2.9.1
vs-color-picker|lih|1.0.0
HTMLHint|mka|0.8.0
python|ms-|2020.8.103604
debugger-for-chrome|msj|4.12.10
debugger-for-edge|msj|1.0.15

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as this is an old version of TypeScript. If you see the same issue with TS 4.0+, please let us know
