### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script should not exist and not be open already

### ISSUE THREAD

**Issue by jgg3** [microsoft/vscode#105738]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.7.4

**Steps to reproduce crash**
1. I just updated VS Code to 1.48.2.
2. I run a Jest task that worked before update.
3. During the Jest run, I get a popup about Typescript language service having died 5 times and is dead.
4. The Jest task runs, but every one I try thereafter just hangs with no message.
**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression: Script should not exist and not be open already
    at ProjectService.applyChangesInOpenFiles (d:\K4\Git\K4\node_modules\typescript\lib\tsserver.js:138392:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (d:\K4\Git\K4\node_modules\typescript\lib\tsserver.js:139274:46)
    at d:\K4\Git\K4\node_modules\typescript\lib\tsserver.js:140932:88
    at IOSession.Session.executeWithRequestId (d:\K4\Git\K4\node_modules\typescript\lib\tsserver.js:140923:28)
    at IOSession.Session.executeCommand (d:\K4\Git\K4\node_modules\typescript\lib\tsserver.js:140932:33)
    at IOSession.Session.onMessage (d:\K4\Git\K4\node_modules\typescript\lib\tsserver.js:140955:35)
    at Interface.<anonymous> (d:\K4\Git\K4\node_modules\typescript\lib\tsserver.js:142270:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:14:14.576Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.16GB free)|
|Process Argv|--folder-uri file:///d%3A/K4/Git/K4|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.0.1
vscode-eslint|dba|2.1.8
vscode-antlr4|mik|2.2.4
debugger-for-chrome|msj|4.12.10
vscode-yaml|red|0.10.1

</details>

![image](https://user-images.githubusercontent.com/20710907/91733240-489b6300-eb77-11ea-8f1a-4f14c56bb8cf.png)

**Comment by mjbvz** [comment]
You are on an old TS version. Do you see this with TS 4.0+?
