### ISSUE TITLE
Assertion Failed: argument is undefined or null: Error: Assertion Failed: argument is undefined or null

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105734]
1. VS Code, open debug console in the panel
2. Reload window
3. Exception in the debug console 🐛 

The Debug Console is not present on startup, it gets registered lazily. And due to that it can not be opened on reload.
Thus I think the current behavior of opening the terminal is perfectly fine, but throwing in the dev console we should not do.

Stack trace

```
  ERR Assertion Failed: argument is undefined or null: Error: Assertion Failed: argument is undefined or null
    at Object.assertIsDefined (file:///Users/isidor/Development/vscode/out/vs/base/common/types.js:93:19)
    at PanelPart.createComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:89:149)
    at PanelPart.doOpenComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:56:36)
    at PanelPart.openComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:43:25)
    at PanelPart.doOpenPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:334:25)
    at PanelPart.openPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:338:29)
    at Object.openComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:41:54)
    at CompositeBar.resetActiveComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositeBar.js:299:30)
    at CompositeBar.hideComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositeBar.js:239:22)
    at PanelPart.hideComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:227:31)
    at PanelPart.onDidChangeActiveViews (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:184:22)
    at PanelPart.onDidRegisterPanels (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:133:22)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:198:70
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:456:38)
    at PanelRegistry.registerComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/composite.js:203:33)
    at PanelRegistry.registerPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/panel.js:29:19)
    at ViewsService.registerPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:382:63)
    at ViewsService.registerViewletOrPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:341:26)
    at ViewsService.onDidRegisterViewContainer (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:93:18)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:37:85
    at Array.forEach (<anonymous>)
    at new ViewsService (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:37:55)
    at InstantiationService._createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService._createServiceInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:177:29)
    at InstantiationService._createServiceInstanceWithOwner (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:165:29)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:156:43)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:113:29)
    at Object.get (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:36:45)
    at Workbench.initLayout (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/layout.js:146:42)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:67:26
    at InstantiationService.invokeFunction (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at Workbench.startup (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:61:38)
    at DesktopMain.open (file:///Users/isidor/Development/vscode/out/vs/workbench/electron-browser/desktop.main.js:62:52)
```

**Comment by sbatten** [comment]
The repro only works if the debug console is not in its original container. test by right clicking the title and notice `reset location`.

@isidorn @sandy081 it seems the viewsservice changes at some point made registering the panels happen too soon for the panel part to be ready. I don't really see a logical way to avoid this so instead of preventing registration, i prevent opening the composite and let the composite part figure out the active container when it is created. pls verify this is sane
