### ISSUE TITLE
Only in console: '${selectedText}' can not be resolved

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#105815]
Issue Type: <b>Bug</b>

#105736

There is no notification only the error in the console:

```
ERR '${selectedText}' can not be resolved. Make sure to have some text selected in the active editor.: Error: '${selectedText}' can not be resolved. Make sure to have some text selected in the active editor.
    at g.evaluateSingleVariable (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3783:159)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:598
    at String.replace (<anonymous>)
    at g.resolveString (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:553)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:268)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:328
    at Array.map (<anonymous>)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:316)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:479
    at Array.forEach (<anonymous>)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:421)
    at g.resolveAnyBase (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3780:637)
    at g.resolveAny (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3780:706)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4521:517
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5686:652
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at T.executeInTerminal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4344:341)
```

VS Code version: Code - Insiders 1.49.0-insider (b6d4fec3714ff897f72c1dab8cc02b7421a8f131, 2020-09-01T05:48:29.841Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by alexr00** [comment]
I will make sure the error isn't shown in the console. It is expected that it if it can't be resolved it is silent.

**Comment by alexr00** [comment]
Actually, I get an error:
![image](https://user-images.githubusercontent.com/38270282/91854836-9a6de700-ec64-11ea-9b13-7142b598ed81.png)
which I think is also fine. Did you not get any error at all?

**Comment by alexr00** [comment]
Actually, I only see it in the console when it is in an array. Still a bug.
