### ISSUE TITLE
Custom task inputs: `command has no value`

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#105805]
Issue Type: <b>Bug</b>

#105736

The same input works when I use it for `flavor`, but not for `flags`. The same happens with `${input:chooseFlag}`:

```
  ERR '${input:chooseNumber}' can not be resolved because the command has no value.: Error: '${input:chooseNumber}' can not be resolved because the command has no value.
    at g.resolveFromMap (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3784:73)
    at g.evaluateSingleVariable (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3782:628)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:598
    at String.replace (<anonymous>)
    at g.resolveString (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:553)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:268)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:328
    at Array.map (<anonymous>)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:316)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:479
    at Array.forEach (<anonymous>)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:421)
    at g.resolveAnyBase (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3780:637)
    at g.resolveAny (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3780:706)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4521:517
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5686:652
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at T.executeInTerminal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4344:341)
```

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "custombuildscript",
            "flavor": "${input:chooseFlag}",
            "flags": [
                "${workspaceFolder}",
                "${input:chooseNumber}",
                // "${input:runCommand}"
            ],
            "problemMatcher": [],
            "label": "custombuildscript: 64 "
        }
    ],
    "inputs": [
        {
            "id": "chooseNumber",
            "description": "Choose a Number",
            "type": "pickString",
            "options": ["1", "2"]
        },
        {
            "id": "chooseFlag",
            "description": "Enter some Text",
            "type": "promptString"
        },
        // {
        //     "id": "runCommand",
        //     "type": "command",
        //     "command": "workbench.action.showWelcomePage"
        // }
    ]
}
```

VS Code version: Code - Insiders 1.49.0-insider (b6d4fec3714ff897f72c1dab8cc02b7421a8f131, 2020-09-01T05:48:29.841Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by chrmarti** [comment]
Also: `${defaultBuildTask}` works in the string property, but not in the array property.

**Comment by chrmarti** [comment]
Similar: `${command:foobar}` works in the string property, but lets the task fail when in the array property:
```
ERR '${command:foobar}' can not be resolved because the command has no value.: Error: '${command:foobar}' can not be resolved because the command has no value.
    at g.resolveFromMap (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3784:73)
    at g.evaluateSingleVariable (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3782:572)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:598
    at String.replace (<anonymous>)
    at g.resolveString (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:553)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:268)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:328
    at Array.map (<anonymous>)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:316)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:479
    at Array.forEach (<anonymous>)
    at g.recursiveResolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3781:421)
    at g.resolveAnyBase (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3780:637)
    at g.resolveAny (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3780:706)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4521:517
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5686:652
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at T.executeInTerminal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4344:341)
localProcessExtensionHost.ts:239 Extension Host
localProcessExtensionHost.ts:240 Debugger attached.
﻿```

There is also some interaction between string and array: If one of the above is in a string property it also work in the array property from what I see.

**Comment by alexr00** [comment]
Also fixed by https://github.com/microsoft/vscode/commit/27f7eba78d090817ea30a1d4b6b644c479eb5d7b
