### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by nameliuqi** [microsoft/vscode#105912]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.7.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-3","currentDirectory":"/Users/liuqi/Sites/vinna/thrift","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-3","currentDirectory":"/Users/liuqi/Sites/vinna/thrift","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:137724:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:137710:29)
    at ProjectService.getOrCreateOpenScriptInfo (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:138113:33)
    at ProjectService.applyChangesInOpenFiles (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:138332:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:139212:46)
    at /Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:140861:28)
    at IOSession.Session.executeCommand (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:140870:33)
    at IOSession.Session.onMessage (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:140893:35)
    at Interface.<anonymous> (/Users/liuqi/Sites/vinna/monorepo/node_modules/typescript/lib/tsserver.js:142208:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by nameliuqi** [comment]
fix by remove folders in worksapce
