### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by josh-hemphill** [microsoft/vscode#106004]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.7

**Steps to reproduce crash**
Unsure
Was working with Deno TS files at the time. Along with its Oak and Soxa frameworks. 
I also seemed to be getting weird errors from the Deno runtime, so it might have something to do with the Deno extension's language server.
I'll update if and when I can narrow it down more.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99917:161)
    at resolveModuleNamesWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100135:26)
    at resolveModuleNamesReusingOldState (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100284:19)
    at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101697:35)
    at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101440:17)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101269:85
    at getSourceFileFromReferenceWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101236:34)
    at processSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101269:13)
    at processRootFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101092:13)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100016:60
    at Object.forEach (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100016:16)
    at synchronizeHostData (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138755:26)
    at Proxy.getProgram (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138847:13)
    at InferredProject.Project.updateGraphWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143339:53)
    at InferredProject.Project.updateGraph (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143282:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145178:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146672:26)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146929:97
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146929:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147792:46)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149555:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149546:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149555:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149579:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150895:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (18.60GB free)|
|Process Argv|C:\Users\Work\Desktop\jh-api|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
tasks|act|0.6.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-github-actions|csc|0.8.0
vscode-markdownlint|Dav|0.36.3
vscode-deno|den|2.0.16
githistory|don|0.6.9
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
LogFileHighlighter|emi|2.9.0
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.19.0
auto-comment-blocks|kev|1.0.1
rainbow-csv|mec|1.7.1
git-graph|mhu|1.25.0
dotenv|mik|1.0.1
mssql|ms-|1.9.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.5
debugger-for-chrome|msj|4.12.10
vetur|oct|0.26.1
material-icon-theme|PKi|4.2.0
vscode-graphql|Pri|0.3.1
vscode-yaml|red|0.10.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
rust|rus|0.7.8
crates|ser|0.5.3
code-spell-checker|str|1.9.0
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is likely caused by the deno extension. Please try filing the issue against them
