### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by SandHilt** [microsoft/vscode#106176]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.7

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:104303:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:104338:29)
    at Map.forEach (<anonymous>)
    at clearPerDirectoryResolutions (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:104076:50)
    at Object.finishCachingPerDirectoryResolution (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:104081:13)
    at ConfiguredProject.Project.updateGraphWorker (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143341:38)
    at ConfiguredProject.Project.updateGraph (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143282:42)
    at ConfiguredProject.updateGraph (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144076:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145729:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146610:44)
    at /snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146929:97
    at Object.flatMap (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146929:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147792:46)
    at /snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149555:88
    at IOSession.Session.executeWithRequestId (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149546:28)
    at IOSession.Session.executeCommand (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149555:33)
    at IOSession.Session.onMessage (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149579:35)
    at Interface.<anonymous> (/snap/code/42/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150895:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 4.19.0-10-amd64 snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|7.74GB (0.82GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
vscode-deno|den|2.1.2
prettier-vscode|esb|5.5.0
vscode-language-babel|mgm|0.0.29
dotenv|mik|1.0.1
vscode-docker|ms-|1.5.0
vscode-language-pack-pt-BR|MS-|1.48.3
debugger-for-chrome|msj|4.12.10
material-icon-theme|PKi|4.2.0
polacode|pnp|0.3.4
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
material-theme|zhu|3.8.7

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Specifically try disabling the deno extension

**Comment by SandHilt** [comment]
Disabling fix the problem.
