### ISSUE TITLE
Cannot build on any distro that uses aarch64 to name architecture instead of arm64

### ISSUE THREAD

**Issue by bkeys** [microsoft/vscode#106249]
- VSCode Version: 1.48.1
- OS Version: Fedora Workstation 32, aarch64

Steps to Reproduce:

1. `$ yarn`
2. `$ yarn run gulp vscode-linux-arm64-min`
3. `$ yarn run gulp vscode-linux-arm64-build-rpm`
You will then get this output:

```
[bkeys@localhost vscode]$ yarn run gulp vscode-linux-arm64-build-rpm
yarn run v1.21.1
$ gulp --max_old_space_size=8192 vscode-linux-arm64-build-rpm
[11:57:27] Node flags detected: --max_old_space_size=8192
[11:57:27] Respawned to PID: 19280
[11:57:37] Using gulpfile ~/Devel/vscode/gulpfile.js
[11:57:37] Starting 'vscode-linux-arm64-build-rpm'...
[11:57:37] Starting clean-arm64 ...
[11:57:37] Finished clean-arm64 after 7 ms
[11:57:37] Starting vscode-linux-arm64-prepare-rpm ...
[11:57:37] 'vscode-linux-arm64-build-rpm' errored after 73 ms
[11:57:37] TypeError: Cannot read property 'join' of undefined
    at /home/bkeys/Devel/vscode/build/gulpfile.vscode.linux.js:170:63
    at /home/bkeys/Devel/vscode/build/lib/task.js:45:28
    at new Promise (<anonymous>)
    at _doExecute (/home/bkeys/Devel/vscode/build/lib/task.js:34:12)
    at _execute (/home/bkeys/Devel/vscode/build/lib/task.js:25:11)
    at vscode-linux-arm64-prepare-rpm (/home/bkeys/Devel/vscode/build/lib/task.js:64:19)
    at async _execute (/home/bkeys/Devel/vscode/build/lib/task.js:25:5)
    at async vscode-linux-arm64-build-rpm (/home/bkeys/Devel/vscode/build/lib/task.js:64:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Sometimes I rig it to swap the name of the architectures in the gulpfile after I have built the binary, then have it package it as `aarch64`. But after years of doing this I am finally tired enough of doing it that I am reporting it.

**Comment by joaomoreno** [comment]
This is currently being refactored as I'm attempting to get ARM linux builds: https://twitter.com/joaomoreno/status/1302908128485408768

I will eventually get to the RPM and DEB packages, so closing this for now.
