### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by xuezier** [microsoft/vscode#106266]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.4.1

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/zhijingxue/workspace/gaoding/docs","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/zhijingxue/workspace/gaoding/docs","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127432:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127418:29)
    at ProjectService.getOrCreateOpenScriptInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127812:33)
    at ProjectService.applyChangesInOpenFiles (/usr/local/lib/node_modules/typescript/lib/tsserver.js:128017:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:128787:46)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:130451:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:130442:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:130451:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:130473:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:131770:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.8
daily-anime|dee|1.2.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vscode-author-generator|edw|0.2.1
vscode-npm-script|eg2|0.3.13
vscode-drawio|eig|1.0.3
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.5.0
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
go|gol|0.16.2
rest-client|hum|0.24.2
docthis|joe|0.7.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
dotenv|mik|1.0.1
vscode-filesize|mkx|2.1.4
vscode-docker|ms-|1.5.0
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.10
vuejs-extension-pack|mub|1.2.1
appidocsnippets|mya|0.1.20
vetur|oct|0.27.2
material-icon-theme|PKi|4.2.0
java|red|0.66.0
vscode-essentials-snippets|rob|2.0.0
bash-debug|rog|0.3.9
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-glide|vit|1.0.2
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-icons|vsc|10.2.0
quokka-vscode|Wal|1.0.317
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.3.0
vscode-proto3|zxh|0.4.2

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as reported with old TS version. Let us know if you see this with TS 4.0+
