### ISSUE TITLE
yarn build fails due to release tarball not being a git repository

### ISSUE THREAD

**Issue by bkeys** [microsoft/vscode#106245]
The title says it all, I am running Fedora 32 workstation

```
Installing dependencies in test/automation...
$ yarn 
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ npm run compile
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599493283663-0.7021364290525003/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> vscode-automation@1.39.0 compile /home/bkeys/Devel/vscode-1.48.2/test/automation
> npm run copy-driver && npm run copy-driver-definition && tsc

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599493283663-0.7021364290525003/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> vscode-automation@1.39.0 copy-driver /home/bkeys/Devel/vscode-1.48.2/test/automation
> cpx src/driver.js out/

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599493283663-0.7021364290525003/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> vscode-automation@1.39.0 copy-driver-definition /home/bkeys/Devel/vscode-1.48.2/test/automation
> node tools/copy-driver-definition.js

Done in 23.56s.
Installing dependencies in test/smoke...
$ yarn 
yarn install v1.21.1
warning package.json: No license field
warning code-oss-dev-smoke-test@0.1.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ npm run compile
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599493308344-0.3564166794093986/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> code-oss-dev-smoke-test@0.1.0 compile /home/bkeys/Devel/vscode-1.48.2/test/smoke
> yarn --cwd ../automation compile && tsc

yarn run v1.21.1
$ npm run copy-driver && npm run copy-driver-definition && tsc
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599493311286-0.8924449298895321/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> vscode-automation@1.39.0 copy-driver /home/bkeys/Devel/vscode-1.48.2/test/automation
> cpx src/driver.js out/

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599493311286-0.8924449298895321/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> vscode-automation@1.39.0 copy-driver-definition /home/bkeys/Devel/vscode-1.48.2/test/automation
> node tools/copy-driver-definition.js

Done in 13.42s.
Done in 30.09s.
Installing dependencies in test/integration/browser...
$ yarn 
yarn install v1.21.1
warning package.json: No license field
warning code-oss-dev-integration-test@0.1.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ npm run compile
[#####################################################] 53/53npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599493334711-0.24767742694627648/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> code-oss-dev-integration-test@0.1.0 compile /home/bkeys/Devel/vscode-1.48.2/test/integration/browser
> yarn tsc

yarn run v1.21.1
warning package.json: No license field
$ /home/bkeys/Devel/vscode-1.48.2/test/integration/browser/node_modules/.bin/tsc
Done in 10.38s.
Done in 13.34s.
Installing dependencies in /home/bkeys/Devel/vscode-1.48.2/build/lib/watch...
$ yarn 
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.50s.
fatal: not in a git directory
child_process.js:669
    throw err;
    ^

Error: Command failed: git config pull.rebase true
fatal: not in a git directory

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.<anonymous> (/home/bkeys/Devel/vscode-1.48.2/build/npm/postinstall.js:77:4)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(30) [Uint8Array] [
      102,  97, 116,  97, 108,  58,  32,
      110, 111, 116,  32, 105, 110,  32,
       97,  32, 103, 105, 116,  32, 100,
      105, 114, 101,  99, 116, 111, 114,
      121,  10
    ]
  ],
  pid: 10201,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(30) [Uint8Array] [
    102,  97, 116,  97, 108,  58,  32,
    110, 111, 116,  32, 105, 110,  32,
     97,  32, 103, 105, 116,  32, 100,
    105, 114, 101,  99, 116, 111, 114,
    121,  10
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by joaomoreno** [comment]
What commands are you running *exactly*? Please provide the full shell session. Also, make sure you clean everything before attempting again: `git clean -xfd .`.
