### ISSUE TITLE
XHR failed

### ISSUE THREAD

**Issue by debby12345** [microsoft/vscode#106341]
Issue Type: <b>Bug</b>

Unable to add view extension

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (3.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by debby12345** [comment]
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:2989 Error: XHR failed
    at XMLHttpRequest.r.onerror (workbench.desktop.main.js:446)
onDidChangeNotification @ workbench.desktop.main.js:2989
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:94 [hb7] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ workbench.desktop.main.js:94
workbench.desktop.main.js:94     at new e (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6919:208)
    at d._createInstance (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1661:888)
    at d.createInstance (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1661:309)
    at ce.getSecondaryActions (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7039:34)
    at i.getSecondaryActions (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5842:641)
    at e.collectCompositeActions (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:861)
    at e.onTitleAreaUpdate (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:290)
    at e.<anonymous> (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5898:589)
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:821)
    at i.updateTitleArea (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3040:438)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5842:94
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92:235
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6562:789
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at S.onDidChangeContext (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5943:483)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5936:776
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:482
    at t.PauseableEmitter.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t.PauseableEmitter.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:539)
    at _.setContext (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1861:237)
    at m.set (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1859:658)
    at ce.doSearch (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7041:111)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7039:536
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:128:302
check @ workbench.desktop.main.js:94
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:2989 Error: XHR failed
    at XMLHttpRequest.r.onerror (workbench.desktop.main.js:446)
onDidChangeNotification @ workbench.desktop.main.js:2989
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:2989 Error: XHR failed
    at XMLHttpRequest.r.onerror (workbench.desktop.main.js:446)
onDidChangeNotification @ workbench.desktop.main.js:2989
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED

**Comment by sbatten** [comment]
can you provide repro steps and the expected behavior?

**Comment by debby12345** [comment]
I'm trying to add an extension

Click on the extension icon and nothing happens and only that error
displays

Theres no proxy

I've reloaded and disabled extension
I've uninstalled and reinstalled
I

**Comment by chrmarti** [comment]
Could you try changing your DNS like this user reported: https://github.com/microsoft/vscode/issues/102714#issuecomment-660050590

This article mentions that too and has some other suggestions as well: https://thegeekpage.com/solved-fix-err_tunnel_connection_failed-error-in-chrome/

Does any of that help?
