### ISSUE TITLE
File not found with singular glob: /__w/1/s/resources/code-workspace.xml 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106384]
```
[05:43:34] 'vscode-linux-x64-build-deb' errored after 49 ms
[05:43:34] Error: File not found with singular glob: /__w/1/s/resources/code-workspace.xml (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/__w/1/s/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:313:26)
    at Glob.emit (events.js:223:5)
    at Glob.EventEmitter.emit (domain.js:475:20)
    at Glob._finish (/__w/1/s/node_modules/glob-stream/node_modules/glob/glob.js:197:8)
    at done (/__w/1/s/node_modules/glob-stream/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/__w/1/s/node_modules/glob-stream/node_modules/glob/glob.js:688:12)
    at /__w/1/s/node_modules/glob-stream/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/__w/1/s/node_modules/glob-stream/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/__w/1/s/node_modules/glob-stream/node_modules/glob/glob.js:764:12)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=87237&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=2d4939b1-2b74-59b7-3eb2-605f0910a1a9&l=23

**Comment by Tyriar** [comment]
Caused by https://github.com/microsoft/vscode/pull/95637

**Comment by Tyriar** [comment]
Queued another build to make sure it passes

**Comment by Tyriar** [comment]
Did 3 builds, having trouble verifying as they're all failing on remote integration tests.
