### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by batcodegen** [microsoft/vscode#106532]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200911

**Steps to reproduce crash**
1.Start VS Code

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13424:55)
    at getTextOfNode (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13449:16)
    at Object.declarationNameToString (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13761:66)
    at getDisplayName (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39745:53)
    at declareSymbol (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39859:111)
    at bindExportsPropertyAssignment (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41969:17)
    at bindWorker (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41665:29)
    at bind (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41554:13)
    at bindExpressionStatement (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40619:13)
    at bindChildren (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40104:21)
    at bind (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41565:21)
    at /Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:94
    at Object.forEach (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40052:16)
    at bindEachFunctionsFirst (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:13)
    at bindChildren (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40144:21)
    at bindContainer (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40002:17)
    at bind (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41568:21)
    at bindSourceFile (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39611:17)
    at Object.bindSourceFile (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39550:9)
    at initializeTypeChecker (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:77500:20)
    at Object.createTypeChecker (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:43597:9)
    at Object.getTypeChecker (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:104583:79)
    at synchronizeHostData (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144689:21)
    at Proxy.getProgram (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144771:13)
    at InferredProject.Project.updateGraphWorker (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149616:53)
    at InferredProject.Project.updateGraph (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149549:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:151631:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153151:26)
    at /Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:97
    at Object.flatMap (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:154427:46)
    at /Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:88
    at IOSession.Session.executeWithRequestId (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156291:28)
    at IOSession.Session.executeCommand (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:33)
    at IOSession.Session.onMessage (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156324:35)
    at Interface.<anonymous> (/Users/prakhar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:158540:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 5, 4|
|Memory (System)|16.00GB (3.31GB free)|
|Process Argv|--crash-reporter-id ba67e4ce-7600-4a1b-a8ba-e0dacf41d9f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
dart-code|Dar|3.14.1
flutter|Dar|3.14.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
npm-dependency-links|her|1.1.0
react-native-snippet|jun|0.5.6
vscode-language-babel|mgm|0.0.29
vscode-typescript-next|ms-|4.1.20200911
debugger-for-chrome|msj|4.12.10
vscode-react-native|msj|0.17.0
react-proptypes-intellisense|OfH|1.0.3
material-icon-theme|PKi|4.3.0
vscodeintellicode|Vis|1.2.10

</details>

**Comment by batcodegen** [comment]
Version 1.49.0

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please follow the instructions from the issue to collect the server log for the crash

**Comment by Orodan** [comment]
Just had the same issue (with the same error message).

- TypeScript Version: 4.1.0-dev.20200913 
- Vscode version: 1.49.0

Is happening since the latest update of vscode for me

**Comment by Orodan** [comment]
Following up, without this extension there is no more error : [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next).

Hope it helps :)

**Comment by DScheglov** [comment]
@Orodan , yes, to disable "JavaScript and TypeScript Nightly." helps

**Comment by batcodegen** [comment]
@Orodan Thanks
