### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by SandHilt** [microsoft/vscode#106509]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.2

**Steps to reproduce crash**
1. Deno extension on;
2. Open an file with .ts extension.
3. Just open VSCode and service broken.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107127:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107162:29)
    at Map.forEach (<anonymous>)
    at clearPerDirectoryResolutions (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106899:50)
    at Object.finishCachingPerDirectoryResolution (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106904:13)
    at ConfiguredProject.Project.updateGraphWorker (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:148272:38)
    at ConfiguredProject.Project.updateGraph (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:148203:42)
    at ConfiguredProject.updateGraph (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149137:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150841:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:151739:44)
    at /snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152062:97
    at Object.flatMap (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152062:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:153081:46)
    at /snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154944:28)
    at IOSession.Session.executeCommand (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:33)
    at IOSession.Session.onMessage (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154977:35)
    at Interface.<anonymous> (/snap/code/43/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 4.19.0-10-amd64 snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3482)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|7.74GB (1.81GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id f716ea74-514f-4187-9e4e-df206990518b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
vscode-deno|den|2.2.1
prettier-vscode|esb|5.6.0
vscode-styled-components|jpo|0.0.31
vscode-language-babel|mgm|0.0.29
dotenv|mik|1.0.1
vscode-docker|ms-|1.5.0
vscode-language-pack-pt-BR|MS-|1.48.3
debugger-for-chrome|msj|4.12.10
material-icon-theme|PKi|4.3.0
polacode|pnp|0.3.4
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
material-theme|zhu|3.8.7

</details>

**Comment by mjbvz** [comment]
Does it happen when you disable deno?

**Comment by SandHilt** [comment]
> Does it happen when you disable deno?

Typescript Server can run.
This problem happen when i have tsconfig.json to build and active extension via workspace setting.

Steps to reproduce:
- npx create-react-app my-app --template typescript
- enable deno via workspace setting
- create an folder and put some ts file
- Typescript Serve will read tsconfig.json and broken.

**Comment by mjbvz** [comment]
It sounds like this only happens when Deno is enabled so please file this issue against the Deno extension
