### ISSUE TITLE
Code server will throw an exception when the file argument to code was a 'number' in remote mode

### ISSUE THREAD

**Issue by bN8A** [microsoft/vscode#106617]
- VSCode Version:
(produced from menu Help->About)
Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

- OS Version:
Windows_NT x64 10.0.19041

- remote platform:
Arch linux on x86_64

Description:
When the file argument to code was a 'number' (1, 22, 333 or 1.1, 2.2, ...) whether they were empty or not,
code will throw an exception as below (the exception messages produced were all the same for those different tries).
($code a1, $code 1a were fine, it happened only when the argument was 'number')

Quote(

The factory method of "vs/server/remoteCli" has thrown an exception
TypeError: e.trim is not a function
    at x (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/server/remoteCli.js:33:437)
    at C (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/server/remoteCli.js:33:508)
    at m (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/server/remoteCli.js:30:748)
    at Object.<anonymous> (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/server/remoteCli.js:33:780)
    at Function.t._safeInvokeFunction (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:21:71)
    at Function.t._invokeFactory (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:21:318)
    at t.complete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:21:555)
    at s._onModuleComplete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:32:161)
    at s._onModuleComplete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:32:401)
    at s._onModuleComplete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:32:401)
    at s._onModuleComplete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:32:401)
    at s._resolve (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:31:694)
    at s.defineModule (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:25:782)
    at o (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:30:163)
    at Object.l (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:38:67)
    at Function.t._safeInvokeFunction (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:21:71)
    at Function.t._invokeFactory (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:21:318)
    at t.complete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:21:555)
    at s._onModuleComplete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:32:161)
    at s._onModuleComplete (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:32:401)
    at s._resolve (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:31:694)
    at s.defineModule (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:25:782)
    at r (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:32:838)
    at c (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:17:685)
    at Object.<anonymous> (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/server/remoteCli.nls.js:4:1)
    at t._createAndEvalScript (/home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:17:729)
    at /home/user/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/loader.js:17:366
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
  phase: 'factory',
  moduleId: 'vs/server/remoteCli'
}

)End Quote

Steps to Reproduce:
1. when using remote - ssh and established an ssh connection to remote machine, tried: 
$code 1
$code 22
$code 333
$code 1.1
$code 2.2

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bN8A** [comment]
I just quickly searched through the issues history, did not find similar one. If this is a known issue, please disregard this and sorry for the noise.
