### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by DScheglov** [microsoft/vscode#106630]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200911

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13424:55)
    at getTextOfNode (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13449:16)
    at Object.declarationNameToString (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13761:66)
    at getDisplayName (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39745:53)
    at declareSymbol (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39859:111)
    at bindExportsPropertyAssignment (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41969:17)
    at bindWorker (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41665:29)
    at bind (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41554:13)
    at bindExpressionStatement (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40619:13)
    at bindChildren (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40104:21)
    at bind (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41565:21)
    at /home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:94
    at Object.forEach (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40052:16)
    at bindEachFunctionsFirst (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:13)
    at bindChildren (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40144:21)
    at bindContainer (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40002:17)
    at bind (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41568:21)
    at bindSourceFile (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39611:17)
    at Object.bindSourceFile (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39550:9)
    at initializeTypeChecker (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:77500:20)
    at Object.createTypeChecker (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:43597:9)
    at Object.getTypeChecker (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:104583:79)
    at synchronizeHostData (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144689:21)
    at Proxy.getProgram (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144771:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149616:53)
    at ConfiguredProject.Project.updateGraph (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149549:42)
    at ConfiguredProject.updateGraph (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:150483:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:152187:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153085:44)
    at /home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:97
    at Object.flatMap (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:154427:46)
    at /home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:88
    at IOSession.Session.executeWithRequestId (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156291:28)
    at IOSession.Session.executeCommand (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:33)
    at IOSession.Session.onMessage (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156324:35)
    at Interface.<anonymous> (/home/dmi/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:158540:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by DScheglov** [comment]
Duplicates: #106532 , #106613 , #106602
