### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by aodelta** [microsoft/vscode#106796]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20200914

**Steps to reproduce crash**
1. The bug happend when I registered links to the most downloaded Deno extension. Imports links errors disappeared, but TS restarted 5 times before crashing. Same things when I realoaded VS Code

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:104146:161)
    at resolveModuleNamesWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:104369:26)
    at resolveModuleNamesReusingOldState (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:104519:19)
    at processImportedModules (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105934:35)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105677:17)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105904:21
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105899:16)
    at findSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105674:21)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:85
    at getSourceFileFromReferenceWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105473:34)
    at processSourceFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105506:13)
    at processRootFile (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:105329:13)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:104246:60
    at Object.forEach (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:188:30)
    at Object.createProgram (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:104246:16)
    at synchronizeHostData (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:145277:26)
    at Proxy.getProgram (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:145369:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:150226:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:150159:42)
    at ConfiguredProject.updateGraph (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:151093:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:152797:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:153695:44)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:154018:97
    at Object.flatMap (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:154018:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:155037:46)
    at c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:156910:88
    at IOSession.Session.executeWithRequestId (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:156901:28)
    at IOSession.Session.executeCommand (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:156910:33)
    at IOSession.Session.onMessage (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:156934:35)
    at Interface.<anonymous> (c:\Users\Guillaume Vanleene\.vscode\extensions\ms-vscode.vscode-typescript-next-4.1.20200914\node_modules\typescript\lib\tsserver.js:159150:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (24.11GB free)|
|Process Argv|--crash-reporter-id a577b94e-d26a-4bc2-a4c1-2062fe9bd139|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
dart-code|Dar|3.14.1
flutter|Dar|3.14.1
vscode-eslint|dba|2.1.8
vscode-deno|den|2.2.3
xml|Dot|2.5.1
sourcepawn-vscode|Dre|0.1.4
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.13
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.0
go|gol|0.16.2
discord-vscode|icr|4.0.0
csharp|ms-|1.23.2
python|ms-|2020.8.108011
remote-wsl|ms-|0.44.5
cmake-tools|ms-|1.4.1
cpptools|ms-|1.0.0
powershell|ms-|2020.6.0
vscode-typescript-next|ms-|4.1.20200914
debugger-for-chrome|msj|4.12.10
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by aodelta** [comment]
I installed for the first time (a clean installation so) VS Code Insiders, opened my folders, opened the index.ts file and everything was ok.
Then I installed and enabled the Deno extension, restarted VS Code Insiders and reproduced the steps above. And it happened again.
Then I disabled the Deno extension, restarted Vs Code Insiders, reproduced the steps above, and the was no error remaining

Here is a link with the picture of my problem (the code is a template code for a Discord bot built with DenoDiscord) : https://gyazo.com/ff9ba5cd7de7232a22ec5f88d96b95fb

**Comment by aodelta** [comment]
I just noticed that there are extensions built-in, and the "TypeScript and JavaScript Language Features" is part of these extensions.
I disabled it and, of course, it worked.

I think the problem is related to the Deno extensions, but because it is very new to everyone and there are only 33k of downloads, I did not see a lot of posts about it :/

**Comment by aodelta** [comment]
It seems like the bug come from the latest version of Deno extension (2.2.3), I'll report this issue on their Github, sorry for the inconvenience.
