### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by Bertrand** [microsoft/vscode#106766]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.7.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-3","currentDirectory":"/Users/bertrand/src/FairJungle/FairJungleWeb","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-3","currentDirectory":"/Users/bertrand/src/FairJungle/FairJungleWeb","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:137724:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:137710:29)
    at ProjectService.getOrCreateOpenScriptInfo (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:138113:33)
    at ProjectService.applyChangesInOpenFiles (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:138332:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:139212:46)
    at /Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:140861:28)
    at IOSession.Session.executeCommand (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:140870:33)
    at IOSession.Session.onMessage (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:140893:35)
    at Interface.<anonymous> (/Users/bertrand/src/FairJungle/FairJungleWeb/node_modules/typescript/lib/tsserver.js:142208:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
go|gol|0.16.2
gc-excelviewer|Gra|3.0.40
graphql-for-vscode|kum|1.15.3
csvtomarkdown|mar|0.0.1
Kotlin|mat|1.7.1
rainbow-csv|mec|1.7.1
vscode-docker|ms-|1.5.0
mssql|ms-|1.9.0
python|ms-|2020.8.108011
cpptools|ms-|1.0.0
vsliveshare|ms-|1.0.2740
debugger-for-chrome|msj|4.12.10
toggle|reb|0.0.1
vscode-sort-json|ric|1.18.0
trailing-spaces|sha|0.3.1
ayu|tea|0.20.1
vscode-icons-mac|way|7.25.3
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as this is an old TypeScript version. Let us know if you see this on TypeScript 4.0+
