### ISSUE TITLE
Cannot start Terminal (sudden change) - The terminal process failed to launch: A native exception occurred during launch (/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (

### ISSUE THREAD

**Issue by mtduman** [microsoft/vscode#106785]
**- VSCode Version: 1.50.0-insider (user setup)
- OS Version: Windows 10
- Remote : Jetson Nano
- Remote OS: Ubuntu 18.04**

It simply happened yesterday, I am able to launch to remote Jetson Nano device with VS Code, but can not open terminal with following error:

**Log File: /home/nano/.vscode-server-insiders/.cca20eba8974b1d6b6a9b71bf4e60a29c8f26648.log** 

The terminal process failed to launch: A native exception occurred during launch (/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/nano/.vscode-server-insiders/bin/e13875b77c89b95f20ccb5667e14ff164c198e57/node_modules/node-pty/build/Release/pty.node)).

```
Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/node_modules/spdlog/build/Release/spdlog.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at Module.patchedRequire [as require] (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at Module.patchedRequire [as require] (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at t.load (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/out/vs/loader.js:17:960)
    at e.load (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/out/vs/loader.js:13:941)
    at o (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/out/vs/loader.js:31:189)
    at Object.errorback (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/out/vs/loader.js:31:313)
    at e.triggerErrorback (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/out/vs/loader.js:14:306)
    at /home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/out/vs/loader.js:14:10
    at ReadFileContext.callback (/home/nano/.vscode-server-insiders/bin/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
IP Address: 192.168.1.230
Extension host agent listening on 35167

```

**Comment by Tyriar** [comment]
Looks like issues with both node-pty and spdlog under aarch64

**Comment by joaomoreno** [comment]
@mtduman Can you check what glibc comes in your OS?

**Comment by cha87de** [comment]
Had the same issue on arch linux. Installing glibc solved the problem apparently.

**Comment by alexr4535** [comment]
Same issue on vs code insiders for arm64 on ubuntu. installing glibc did not solve my problem.
