### ISSUE TITLE
Microsoft Visual Studio Code Errors

### ISSUE THREAD

**Issue by Shruthi2125** [microsoft/vscode#106851]
Microsoft Vs Code shows Javascript Error.
Every week I am uninstalling and reinstalling but issue has become repetitive.
This error is occuring with all  versions of Vs Code

Error: Cannot find module 'C:\Program Files (x86)\Microsoft VS Code\resources\app\out\main'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\init.js:171:8)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3).

Help me on this.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is VS Code version, OS etc. as required by issue template?

Do you have an anti-virus installed? Could you check if there are some files removed/quarantined by AV?

**Comment by Shruthi2125** [comment]
My working on office laptop:
Windows version 10
Vs code version 1.49.0
Symantec Endpoint Protection Anti Virus is used

**Comment by aeschli** [comment]
@Shruthi2125 Is the file 'C:\Program Files (x86)\Microsoft VS Code\resources\app\out\main.js' existing?
Can you check is the Symantec Endpoint Protection Anti Virus has quarantined the file?

**Comment by Shruthi2125** [comment]
main.js file is present.But every week the software is getting corrupted even if it is re installed.
How can check the symantec endpoint protection has quarantined file or not?

**Comment by aeschli** [comment]
I assume there's a Symantec management tool. 
Maybe this helps: https://knowledge.broadcom.com/external/article/151677/manage-quarantined-files-with-endpoint.html
