### ISSUE TITLE
No Code AutoCompletion

### ISSUE THREAD

**Issue by nyn3x** [microsoft/vscode#106818]
- VSCode Version: 1.49.0 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

In any *.ts or *.js file, when I try to use auto-completion for eg `console` by typing `con` and then pressing `[STRG]+[SPACE]` I'm not prompted with the expected `console`. However: once I completed typing `console` I get suggestions for `console`'s members.

Looking at the "Log (Extension Host)" I see the following error:

```
[2020-09-16 04:49:13.048] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-09-16 04:49:13.049] [exthost] [error] Error: <semantic> TypeScript Server Error (4.0.2)
Debug Failure. Symbol parent was undefined. Flags: ExportDoesNotSupportDefaultModifier|Alias|AliasExcludes|ModuleMember|Classifiable|Transient. Declarations: undefined.
Error: Debug Failure. Symbol parent was undefined. Flags: ExportDoesNotSupportDefaultModifier|Alias|AliasExcludes|ModuleMember|Classifiable|Transient. Declarations: undefined.
    at getSymbolParentOrFail (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:113347:25)
    at Object.getNameForExportedSymbol (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:113340:61)
    at pushSymbol (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116339:40)
    at c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116323:28
    at Map.forEach (<anonymous>)
    at getSymbolsFromOtherSourceFileExports (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116321:54)
    at getGlobalCompletions (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116082:49)
    at tryGetGlobalSymbols (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115993:25)
    at getCompletionData (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115787:22)
    at Object.getCompletionsAtPosition (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115129:34)
    at Proxy.getCompletionsAtPosition (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143481:35)
    at IOSession.Session.getCompletions (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154320:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153204:61)
    at c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154944:28)
    at IOSession.Session.executeCommand (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:33)
    at IOSession.Session.onMessage (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154977:35)
    at Interface.<anonymous> (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
	at Function.create (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:76465)
	at h.dispatchResponse (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:70340)
	at h.dispatchMessage (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:69199)
	at c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:68709
	at l.fire (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at g.onLengthData (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:45:60018)
	at Socket.<anonymous> (c:\Users\henning\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:45:59666)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

However: for a split second, this seems to work alright - maybe before the internal initialization of some vscode routine complete?

Does this issue occur when all extensions are disabled?: Yes

**Comment by nyn3x** [comment]
None of the suggested "duplicates" seem to be related to code-completion.

**Comment by mjbvz** [comment]
Can you share the project or at least the file the caused this error?

**Comment by nyn3x** [comment]
I've create a stripped version of one of my projects, where this behavior occurs. You can check it out at https://github.com/nyn3x/vscode-autocomplete-error

If you go to the `Home.tsx` and try to access the imported `log` function typing just `lo` doesn't offer the imported `log` function; instead I get the error shown above.
