### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by kishan-dobariya** [microsoft/vscode#106820]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.7.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/apple/Workspace/Hermosa-Server","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/apple/Workspace/Hermosa-Server","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:137724:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:137710:29)
    at ProjectService.getOrCreateOpenScriptInfo (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:138113:33)
    at ProjectService.applyChangesInOpenFiles (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:138332:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:139212:46)
    at /Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:140861:28)
    at IOSession.Session.executeCommand (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:140870:33)
    at IOSession.Session.onMessage (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:140893:35)
    at Interface.<anonymous> (/Users/apple/Workspace/Hermosa-Server/node_modules/typescript/lib/tsserver.js:142208:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (3.11GB free)|
|Process Argv|--crash-reporter-id bd1b38e8-208c-4af1-af8a-f6c43d5e1800|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
turbo-console-log|Cha|1.4.0
vscode-svgviewer|css|2.0.0
cloudformation-yaml-snippets|dst|2.21.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
rest-client|hum|0.24.2
prettify-json|moh|0.0.3
vetur|oct|0.27.3

</details>

**Comment by mjbvz** [comment]
Closing as this is form an old TypeScript version. Let us know if you see this in TS 4.0+
