### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by engr-mubashir** [microsoft/vscode#106952]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (c:\Users\MubashirIqbal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152047:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\MubashirIqbal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153081:46)
    at c:\Users\MubashirIqbal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (c:\Users\MubashirIqbal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154944:28)
    at IOSession.Session.executeCommand (c:\Users\MubashirIqbal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:33)
    at IOSession.Session.onMessage (c:\Users\MubashirIqbal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154977:35)
    at Interface.<anonymous> (c:\Users\MubashirIqbal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.95GB free)|
|Process Argv|--crash-reporter-id 278f147a-a35c-48c7-8961-f051bca75075|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
ng-template|Ang|0.1001.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
Angular2|joh|9.1.2
prettify-json|moh|0.0.3
python|ms-|2020.8.109390
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.10
angular-console|nrw|13.0.0
quicktype|qui|12.0.46
java|red|0.67.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-icons|vsc|10.2.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.7

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please fill in the issue template to the best of your ability

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
