### ISSUE TITLE
workspace.folders is not iterable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#106932]
1. Open vscode out of source and open a folder
2. Notice error in dev tools console

This was not happening yesterday

Based on blame of the diagnostic service file assigning to @RMacfarlane and @eamodio 
fyi @bpasero 

```
ERR workspace.folders is not iterable: TypeError: workspace.folders is not iterable
    at DiagnosticsService.reportWorkspaceStats (file:///Users/isidor/Development/vscode/out/vs/platform/diagnostics/node/diagnosticsService.js:418:45)
    at DiagnosticsChannel.call (file:///Users/isidor/Development/vscode/out/vs/platform/diagnostics/node/diagnosticsIpc.js:25:41)
    at ChannelServer.onPromise (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.js:253:35)
    at ChannelServer.onRawMessage (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.js:226:33)
    at file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.js:171:73
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:456:38)
    at file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:294:37
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:456:38)
    at ProtocolReader.acceptChunk (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:188:37)
    at file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:157:61
    at Socket.listener (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/node/ipc.net.js:17:40)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by bpasero** [comment]
I cannot reproduce. @isidorn did you do full recompile?

**Comment by isidorn** [comment]
Yeah I just rebuilt and I still see it. You might have seen it in my standup demo :)

**Comment by bpasero** [comment]
@isidorn I need your help as I can still not reproduce this. Here is what I do:
* make sure https://github.com/microsoft/vscode/blob/05999d3f3079e45742ea4bdca8f6b7d03ee669ea/src/vs/workbench/contrib/tags/electron-browser/workspaceTags.ts#L43-L43 is called by commenting out the telemtry opt in check
* toggle shared process window and add breakpoint to `diagnosticsService#reportWorkspaceStats`
* open a folder or workspace and wait until breakpoint is hit in shared process
* step over and see no error

You error?

**Comment by isidorn** [comment]
I can no longer reproduce the error which I saw yesterday mutlitple times.
Just to be sure I followed your steps and I also do not see the error when debugging.

So closing this and will reopen if I see it again. Sorry about this, but was seeing it yesterday 100%
