### ISSUE TITLE
Notebook integration tests output

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107003]
This is not a failure but unexpected output:

 ```
notebook working copy
Cannot read property 'extensionLocation' of undefined: TypeError: Cannot read property 'extensionLocation' of undefined
    at NotebookEditorWidget._setKernelsFromProviders (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:635:66)
    at NotebookEditorWidget._setKernels (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:585:29)
```

**Comment by bpasero** [comment]
Also seeing some of these: `Notebook content provider view options file name pattern is invalid undefined`
