### ISSUE TITLE
Autoimplements complex typescript abstract class doesn't works anymore

### ISSUE THREAD

**Issue by Varkal** [microsoft/vscode#107002]
- VSCode Version: 1.49.1
- OS Version: 10.15.6

Steps to Reproduce:

I have an abstract class with a method taking a complexe type as a parameter (see the third file in the below gif)
On 1.48.2, when i create a class extending the abstract one. I can use "Quick fix" to implements all abstract members (with types looks messy, but it works)

![1 48 2](https://user-images.githubusercontent.com/3471491/93589643-6a854a00-f9ad-11ea-81f4-92ae650f6dfb.gif)

On 1.49.1, as you can see on the gif below, it doesn't works : i can only move the class in its own file. 
But, if i use a more simpler type, it works

![1 49 1](https://user-images.githubusercontent.com/3471491/93589907-debfed80-f9ad-11ea-8f2a-c426a3304808.gif)

TS Server logs say : 

```
Err 399   [12:53:55.271] Exception on executing command {"seq":89,"type":"request","command":"getCodeFixes","arguments":{"file":"/Users/varkal/dev/pasta-cli/src/commands/generate.cli.ts","startLine":5,"startOffset":14,"endLine":5,"endOffset":18,"errorCodes":[2515]}}:

    Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol

    Error: Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol
        at getImportFixForSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:132979:22)
        at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:132869:27)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137041:63
        at Array.forEach (<anonymous>)
        at importSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137041:21)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136839:25
        at Object.sameMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:468:30)
        at signatureToMethodDeclaration (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136834:40)
        at outputMethod (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136792:30)
        at addNewNodeForMemberSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136771:25)
        at Object.createMissingMemberNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136679:21)
        at addMissingMembers (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:134566:21)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:134537:28
        at Function.ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:129418:17)
        at Object.getCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:134536:64)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130591:77
        at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
        at Object.getFixes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130591:23)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143788:35
        at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
        at Proxy.getCodeFixesAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143786:23)
        at IOSession.Session.getCodeFixes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154654:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153331:61)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:88
        at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154944:28)
        at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:33)
        at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154977:35)
        at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157193:27)
        at Interface.emit (events.js:223:5)
        at Interface._onLine (readline.js:315:10)
        at Interface._normalWrite (readline.js:460:12)
        at Socket.ondata (readline.js:172:10)
        at Socket.emit (events.js:223:5)
        at addChunk (_stream_readable.js:309:12)
        at readableAddChunk (_stream_readable.js:290:11)
        at Socket.Readable.push (_stream_readable.js:224:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)

File text of /Users/varkal/dev/pasta-cli/src/commands/generate.cli.ts:
    import { AbstractCommand } from "../abstract-command";
    import { Argv } from "yargs";
    import { CommandArgs, ExtractArgv } from "../utils";
    
    export class Toto extends AbstractCommand {
      
    }
    

Info 400  [12:53:55.271] response:
    {"seq":0,"type":"response","command":"getCodeFixes","request_seq":89,"success":false,"message":"Error processing request. Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol\nError: Debug Failure. False expression: Some export
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share an example project or the code (as text) from those screenshots

**Comment by mjbvz** [comment]
Closing as not actionable without a self contained example
