### ISSUE TITLE
Explorer empty on startup

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107143]
* get latest insiders
* open workbench
* 🐛 explorer is empty

```
ERR Cannot read property 'some' of undefined: TypeError: Cannot read property 'some' of undefined
    at NotebookProviderInfo.matches (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/notebookProvider.js:23:35)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/notebookServiceImpl.js:130:149
    at Object.filter (file:///Users/jrieken/Code/vscode/out/vs/base/common/iterator.js:43:21)
    at filter.next (<anonymous>)
    at NotebookProviderInfoStore.getContributedNotebook (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/notebookServiceImpl.js:130:44)
    at NotebookService.getContributedNotebookProviders (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/notebookServiceImpl.js:659:51)
    at NotebookContribution.getContributedEditors (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/notebook.contribution.js:167:41)
    at Object.getEditorOverrides (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/notebook.contribution.js:120:33)
    at EditorService.getEditorOverrides (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/editor/browser/editorService.js:381:71)
    at WorkbenchContextKeysHandler.updateEditorContextKeys (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/contextkeys.js:144:86)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/contextkeys.js:92:82
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:456:38)
    at EditorService.doHandleActiveEditorChangeEvent (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/editor/browser/editorService.js:106:43)
    at EditorService.handleActiveEditorChange (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/editor/browser/editorService.js:99:18)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/services/editor/browser/editorService.js:68:74
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:456:38)
    at EditorPart.doSetGroupActive (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:419:42)
    at Object.fromJSON (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:757:30)
    at GridView._deserializeNode (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/grid/gridview.js:831:52)
    at file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/grid/gridview.js:824:36
    at Array.map (<anonymous>)
    at GridView._deserializeNode (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/grid/gridview.js:822:53)
    at GridView._deserialize (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/grid/gridview.js:816:30)
    at Function.deserialize (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/grid/gridview.js:812:20)
    at Function.deserialize (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/grid/grid.js:423:50)
    at EditorPart.doCreateGridControlWithState (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:746:56)
    at EditorPart.doCreateGridControlWithPreviousState (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:719:26)
    at EditorPart.doCreateGridControl (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:692:38)
    at EditorPart.createContentArea (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:600:18)
    at EditorPart.create (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/part.js:43:37)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/workbench.js:234:34
    at Array.forEach (<anonymous>)
    at Workbench.renderWorkbench (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/workbench.js:232:15)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/workbench.js:76:26
    at InstantiationService.invokeFunction (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at Workbench.startup (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/workbench.js:61:38)
    at DesktopMain.open (file:///Users/jrieken/Code/vscode/out/vs/workbench/electron-browser/desktop.main.js:61:52)
```

**Comment by jrieken** [comment]
@bpasero for making the workbench more fault tolerant

**Comment by jrieken** [comment]
I believe this was caused be https://github.com/microsoft/vscode/commit/ab1f288baa6a75b1de1bf12de15f114a45322398. The problem is that notebook information is persisted in a memento and that the structure of notebook info has changed. Therefore, after the first (re)load, this error happens. Another reload should straighten things out again. Trying to push a workaround.

**Comment by bpasero** [comment]
@jrieken is there a way to reproduce the empty explorer from `master`? The editor area already has a [try-catch](https://github.com/microsoft/vscode/blob/e8760a5d6c0e09ab692e5b3e414eca018745490f/src/vs/workbench/browser/parts/editor/editorPart.ts#L973-L973) block to protect against editors failing to restore, so I think this issue is specific to the file explorer or side bar in general.

Adding @isidorn for explorer to see if he can reproduce and better protect against empty explorer.

**Comment by jrieken** [comment]
> @jrieken is there a way to reproduce the empty explorer from master?


https://github.com/microsoft/vscode/blob/8c1015f5e1a7a686d19ec8a5f56a495332f16062/src/vs/workbench/contrib/notebook/common/notebookProvider.ts#L57

⬆️ replace that line with some error throwing and you should be able to see the same issue

**Comment by isidorn** [comment]
explorer was failing becaue the getEditorOverrides was throwing here
https://github.com/microsoft/vscode/blob/ed3df6e1ea22603fe348c83b1ce4b4179c2d8fb3/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L489

Feels like @bpasero tackled that via this commit
