### ISSUE TITLE
Live-share not working on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by JonasRSV** [microsoft/vscode#107222]
- VSCode Version:

1.49.1
58bb7b2331731bf72587010e943852e13e6fd3cf
x64

- OS Version:

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Steps to Reproduce:

1. sudo snap install code --classic
2. Start code 
3. Install liveshare-extension
4. Try to use it for anything, nothing works (e.g pressing CTRL-Shift P then choosing 'Start collaborative Sesson')

Command 'Live Share: Start Collaboration Session (Share)' resulted in an error (command 'liveshare.start' not found)

Does this issue occur when all extensions are disabled?: Yes/No

I only have liveshare installed. I don't usually use vscode, just tried to download it to use liveshare with a friend. But I can' t get it to work. I have tried purging VScode from my computer a couple of times and installed it from different sources, e.g apt, deb and snap.. It works on none of them. 

What would be next steps for me to try?

**Comment by JonasRSV** [comment]
Here are some logs I found

```bash
[2020-09-22 13:44:17.083] [sharedprocess] [info] main {"machineId":"f87182c3c474e04737aa24625a792e1d6cf00acf1076192d8c2faeba71da4650","windowId":2}
[2020-09-22 13:44:17.109] [sharedprocess] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/jonas/.config/Code/User/snippets'
[2020-09-22 13:44:21.673] [sharedprocess] [info] Installing extension: ms-vsliveshare.vsliveshare
[2020-09-22 13:44:24.653] [sharedprocess] [info] Downloaded extension: ms-vsliveshare.vsliveshare /home/jonas/.config/Code/CachedExtensionVSIXs/ms-vsliveshare.vsliveshare-1.0.2740
[2020-09-22 13:44:25.299] [sharedprocess] [info] Extracted extension to /home/jonas/.vscode/extensions/.ms-vsliveshare.vsliveshare-1.0.2740: ms-vsliveshare.vsliveshare
[2020-09-22 13:44:25.300] [sharedprocess] [info] Renamed to /home/jonas/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2740
[2020-09-22 13:44:25.302] [sharedprocess] [info] Installation completed. ms-vsliveshare.vsliveshare
[2020-09-22 13:44:25.323] [sharedprocess] [info] Extensions installed successfully: ms-vsliveshare.vsliveshare
[2020-09-22 13:44:57.095] [sharedprocess] [info] Starting to clean up unused language packs.
```

that is the installation log

Here are some other logs I found

```bash
[2020-09-22 13:44:16.036] [exthost] [info] extension host started
[2020-09-22 13:44:16.051] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2020-09-22 13:44:16.051] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-09-22 13:44:16.072] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2020-09-22 13:44:16.072] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
[2020-09-22 13:44:16.086] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-09-22 13:44:16.086] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-09-22 13:44:16.091] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-09-22 13:44:16.091] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2020-09-22 13:44:16.115] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-09-22 13:44:16.115] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/git/dist/main
[2020-09-22 13:44:16.169] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-09-22 13:44:16.169] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-09-22 13:44:16.173] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-09-22 13:44:16.173] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/search-result/dist/extension.js
[2020-09-22 13:44:16.218] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-09-22 13:44:16.218] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/github/dist/extension.js
[2020-09-22 13:44:16.243] [exthost] [info] eager extensions activated
[2020-09-22 13:44:25.432] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare {"startup":false,"extensionId":{"value":"ms-vsliveshare.vsliveshare","_lower":"ms-vsliveshare.vsliveshare"},"activationEvent":"*"}
[2020-09-22 13:44:25.433] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/jonas/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2740/out/prod/extension-prod
[2020-09-22 13:44:32.458] [exthost] [error] Activating extension ms-vsliveshare.vsliveshare failed due to an error:
[2020-09-22 13:44:32.458] [exthost] [error] Error: connect ENOENT /home/jonas/tmp/CoreFxPipe_vscode.19a02a333ca2fd3872905bf3e5fb05f3
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
```

And another relevant one maybe

```bash
[2020-09-22 13:42:14.981] [renderer1] [error] ENOENT: no such file or directory, unlink '/home/jonas/.local/share/vsliveshare/cascade.json': Error: ENOENT: no such file or directory, unlink '/home/jonas/.local/share/vsliveshare/cascade.json'
```

And a final one

```bash
[2020-09-22 13:42:12.679] [exthost] [info] extension host started
[2020-09-22 13:42:12.696] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2020-09-22 13:42:12.696] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-09-22 13:42:12.711] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2020-09-22 13:42:12.711] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
[2020-09-22 13:42:12.723] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-09-22 13:42:12.723] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-09-22 13:42:12.726] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-09-22 13:42:12.726] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2020-09-22 13:42:12.743] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-09-22 13:42:12.743] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/git/dist/main
[2020-09-22 13:42:12.777] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-09-22 13:42:12.777] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-09-22 13:42:12.779] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-09-22 13:42:12.779] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/search-result/dist/extension.js
[2020-09-22 13:42:12.780] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare {"startup":true,"extensionId":{"value":"ms-vsliveshare.vsliveshare","_lower":"ms-vsliveshare.vsliveshare"},"activationEvent":"*"}
[2020-09-22 13:42:12.780] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/jonas/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2740/out/prod/extension-prod
[2020-09-22 13:42:13.969] [exthost] [error] Activating extension ms-vsliveshare.vsliveshare failed due to an error:
[2020-09-22 13:42:13.969] [exthost] [error] Error: Agent terminated with exit code: 0 and signal null: A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/jonas/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2740/dotnet_modules/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:- https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.18.04-x64
	at ChildProcess.<anonymous> (/home/jonas/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2740/out/prod/extension-prod.js:136873:32)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
[2020-09-22 13:42:13.969] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-09-22 13:42:13.969] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/44/usr/share/code/resources/app/extensions/github/dist/extension.js
[2020-09-22 13:42:13.982] [exthost] [info] eager extensions activated

```

**Comment by JonasRSV** [comment]
I have tried installing libhostfxr.so, now I get no errors nothing. Just does not work.

**Comment by rzhao271** [comment]
@JonasRSV it seems you solved the issue with the linked issue in MicrosoftDocs?
Labelling this as *caused-by-extension for now.
