### ISSUE TITLE
Ctrl + Shift + T for Ctrl + K, V generated preview doesn't work

### ISSUE THREAD

**Issue by sohomdatta1** [microsoft/vscode#107205]
- VSCode Version: 1.49.1
- OS Version: Linux x64 5.8.6-1-MANJARO

### Steps to Reproduce:

1. Open a markdown file
2. Use the Ctrl + K, V to generate preview
3. Ctrl + W to quit the preview.
4. Ctrl + Shift + T to restore

### Expected Result:

Markdown preview gets restored without error

### Actual Result:

![Screenshot from 2020-09-22 14-00-10](https://user-images.githubusercontent.com/55270802/93859962-f49a1f00-fcdb-11ea-8bb0-189f12667543.png)
### Error in console:
```
  ERR Invalid group provided: Error: Invalid group provided
    at Object.t.editorGroupToViewColumn (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:3859:827)
    at Object.resolveWebview (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:4543:65)
    at k.tryRevive (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:3999:764)
    at file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:3999:872
    at Object.a [as createCancelablePromise] (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:126:565)
    at k.resolveWebview (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:3999:823)
    at I.resolve (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:3997:794)
    at I.o.<computed> (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:43:928)
    at e.setInput (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:4766:672)
    at async p.doSetInput (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:4739:797)
    at async p.openEditor (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:4738:425)
    at async file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:6661:617
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by sohomdatta1** [comment]
Did some detective work :)

The particular error seems to be caused by the lines:
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/api/common/shared/editor.ts#L33-L36
It seems that the group in which the preview was originally opened gets "disposed" when the preview itself is "disposed". Thus, when the editor is revived, it tries to add itself to the now non-existent group. When the main thread tries to look up the particular group, it calls the `editorGroupToViewColumn()` function which throws an error since the `editorGroupsService.getGroup()` function returns an `undefined` value.
