### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by julianramirezch** [microsoft/vscode#107384]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/home/julian/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/node_modules/typescript/lib/tsserver.js:152047:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/julian/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/node_modules/typescript/lib/tsserver.js:153081:46)
    at /home/julian/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/node_modules/typescript/lib/tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (/home/julian/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/node_modules/typescript/lib/tsserver.js:154944:28)
    at IOSession.Session.executeCommand (/home/julian/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/node_modules/typescript/lib/tsserver.js:154953:33)
    at IOSession.Session.onMessage (/home/julian/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/node_modules/typescript/lib/tsserver.js:154977:35)
    at Interface.<anonymous> (/home/julian/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/node_modules/typescript/lib/tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.91GB (1.02GB free)|
|Process Argv|--crash-reporter-id 21fb91b0-cebd-4c35-be8a-9a48aab40ea3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2201)|
|Memory (System)|5.91GB (1.02GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
auto-rename-tag|for|0.1.4
helium-icon-theme|hel|1.0.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
material-icon-theme|PKi|4.3.0
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.8.0
rainbow-brackets|2gu|0.0.6
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.6.0
rainbow-csv|mec|1.7.1
python|ms-|2020.9.111407
cpptools|ms-|1.0.1
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
open-html-in-browser|pea|2.1.3
LiveServer|rit|5.6.1
sass-indented|syl|1.8.11
tabnine-vscode|Tab|3.0.2
vscodeintellicode|Vis|1.2.10
gitblame|wad|5.0.0

(7 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please fill in the issue template to the best of your ability 

/needsMoreInfo
