### ISSUE TITLE
Autocomplete from extension for extension file type not working in v1.49.2

### ISSUE THREAD

**Issue by WilliamVenner** [microsoft/vscode#107550]
## The extension has not been updated since 2017 so this issue cannot be the fault of the extension which has been working fine ever since. Please do not instantly close my issue.

Issue Type: <b>Bug</b>

My autocomplete/tab complete has randomly broken. It was working fine a couple of days ago. I did not change any settings. It was almost like I accidentally pressed a keyboard combination that managed to break it.

It works fine for every language except this:

https://marketplace.visualstudio.com/items?itemName=aStonedPenguin.glua

Upon typing something and pressing tab, it just shows the tab completion popup with just "Loading..." indefinitely:

![image](https://user-images.githubusercontent.com/14863743/94370326-3f0a0a00-00e7-11eb-9338-28f9c7deaa75.png)

I have tried disabling the "glualint" extension which did not fix the issue.

My autocomplete setting:

![image](https://user-images.githubusercontent.com/14863743/94370360-81cbe200-00e7-11eb-9d92-c6f8c48872ce.png)

I also tried downgrading to v1.48.2 but that did not fix anything.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3850)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.05GB free)|
|Process Argv|--crash-reporter-id fd54349d-69a2-48d2-ae73-9e4f10322afc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
glua|aSt|1.1.0
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.8
vscode-npm-script|eg2|0.3.13
comment-anchors|Exo|1.9.0
vscode-glualint|goz|0.5.0
remote-wsl|ms-|0.44.5
vetur|oct|0.28.0
synthwave-vscode|Rob|0.1.8
vscode-counter|uct|2.2.0
vscode-wakatime|Wak|4.0.8

</details>

<details><summary>Console Log</summary>
<pre><code>TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.lua.
Old grammar file: file:///c%3A/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/lua/syntaxes/lua.tmLanguage.json.
New grammar file: file:///c%3A/Users/billy/.vscode/extensions/astonedpenguin.glua-1.1.0/syntaxes/lua.tmLanguage
register @ TMScopeRegistry.ts:43
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'document' of undefined
$onExtensionRuntimeError @ host.ts:10
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at Array.<anonymous> (c:\Users\billy\.vscode\extensions\goz3rr.vscode-glualint-0.5.0\out\glualintProvider.js:19:90)
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:495)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:892
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at b.acceptDocumentsAndEditorsDelta (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:482)
	at b.$acceptDocumentsAndEditorsDelta (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:697:401)
	at g._doInvokeHandler (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
	at g._invokeHandler (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
	at g._receiveRequest (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
	at g._receiveOneMessage (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at p.acceptChunk (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
$onExtensionRuntimeError @ host.ts:10
listWidget.ts:726 List with id 'list_id_10' was styled with a non-opaque background color. This will break sub-pixel antialiasing.
style @ listWidget.ts:675
listWidget.ts:726 List with id 'list_id_11' was styled with a non-opaque background color. This will break sub-pixel antialiasing.
style @ listWidget.ts:675
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'document' of undefined
$onExtensionRuntimeError @ host.ts:10
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at Array.<anonymous> (c:\Users\billy\.vscode\extensions\goz3rr.vscode-glualint-0.5.0\out\glualintProvider.js:19:90)
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:495)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:892
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at b.acceptDocumentsAndEditorsDelta (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:482)
	at b.$acceptDocumentsAndEditorsDelta (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:697:401)
	at g._doInvokeHandler (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
	at g._invokeHandler (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
	at g._receiveRequest (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
	at g._receiveOneMessage (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at p.acceptChunk (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
$onExtensionRuntimeError @ host.ts:10
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'document' of undefined
$onExtensionRuntimeError @ host.ts:10
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at Array.<anonymous> (c:\Users\billy\.vscode\extensions\goz3rr.vscode-glualint-0.5.0\out\glualintProvider.js:19:90)
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:495)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:892
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at b.acceptDocumentsAndEditorsDelta (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:482)
	at b.$acceptDocumentsAndEditorsDelta (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:697:401)
	at g._doInvokeHandler (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
	at g._invokeHandler (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
	at g._receiveRequest (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
	at g._receiveOneMessage (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at p.acceptChunk (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Users\billy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
$onExtensionRuntimeError @ host.ts:10
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/TasApiFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/FilteredFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/BaseFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/AxiosHttpClient.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceAutoPolling.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/MemoryKeyValueStorage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceBase.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/PollingService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/billy/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map: </code></pre>
</details>

**Comment by gjsjohnmurray** [comment]
Thank you for adding information not previously given in #107548. But now you have closed this one. Did you solve the problem yourself?

**Comment by WilliamVenner** [comment]
You know what, you weren't wrong, kind of... it was caused by ANOTHER extension. Whammy.
