### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by alejandronanez** [microsoft/vscode#107583]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.8.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:112241:13)
    at Object.releaseDocument (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:112236:20)
    at /Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:135319:45
    at Object.forEach (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:167:30)
    at Proxy.dispose (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:135318:20)
    at InferredProject.Project.close (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:139542:38)
    at InferredProject.close (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:140420:40)
    at ProjectService.removeProject (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:144260:46)
    at /Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/Users/alejandro/z/blog/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by mjbvz** [comment]
Closing as this TS version is out of date. Let us know if you see this with TS 4.0+
