### ISSUE TITLE
Smoke-Test: Datamigration tests fail

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#107682]
#107568

The Datamigration tests fail with timeouts (on today's Linux build):

```
  1) VSCode Smoke Tests (Electron)
       Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
         Datamigration
           verifies opened editors are restored:
     Error: Timeout: get element '.explorer-folders-view' after 20 seconds.
      at /home/chrmarti/Development/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/chrmarti/Development/vscode/test/automation/out/code.js:9:58)

  2) VSCode Smoke Tests (Electron)
       Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
         Datamigration
           verifies that 'hot exit' works for dirty files:
     Error: Timeout: get element '.explorer-folders-view' after 20 seconds.
      at /home/chrmarti/Development/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/chrmarti/Development/vscode/test/automation/out/code.js:9:58)
```

**Comment by bpasero** [comment]
```
ticino@ubuntu:~/development/vscode$ yarn smoketest --build ~/Downloads/code-insider-x64-1601371524/VSCode-linux-x64 --stable-build ~/Downloads/code-stable-1600965670/VSCode-linux-x64/
yarn run v1.22.5
$ cd test/smoke && node test/index.js --build /home/ticino/Downloads/code-insider-x64-1601371524/VSCode-linux-x64 --stable-build /home/ticino/Downloads/code-stable-1600965670/VSCode-linux-x64/
Running desktop smoke tests against /home/ticino/Downloads/code-insider-x64-1601371524/VSCode-linux-x64/code-insiders


*** Test data: /tmp/t316137Z2GU93HUBb8
*** Preparing smoketest setup...
*** Cloning test project repository...
*** Running yarn...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

*** Smoketest setup done!

  VSCode Smoke Tests (Electron)
    Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
      Datamigration
        ✓ verifies opened editors are restored
        ✓ verifies that 'hot exit' works for dirty files
    VSCode Smoke Tests (Electron)
      Dataloss
        ✓ verifies that 'hot exit' works for dirty files
      Preferences
        ✓ turns off editor line numbers and verifies the live change
        ✓ changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it
      Search
        ✓ searches for body & checks for correct result number
        ✓ searches only for *.js files & checks for correct result number
        ✓ dismisses result & checks for correct result number
        ✓ replaces first search result with a replace term
      Quick Access
        ✓ quick access search produces correct result
        ✓ quick access respects fuzzy matching
      Notebooks
        ✓ inserts/edits code cell
        ✓ inserts/edits markdown cell
        ✓ moves focus as it inserts/deletes a cell
        - moves focus in and out of output
        - cell action execution
      Language Features
        ✓ verifies quick outline
        ✓ verifies problems view
        ✓ verifies settings
      Editor
        ✓ shows correct quick outline
      Statusbar
        ✓ verifies presence of all default status bar elements
        ✓ verifies that 'quick input' opens when clicking on status bar elements
        ✓ verifies that 'Problems View' appears when clicking on 'Problems' status element
        ✓ verifies that 'Tweet us feedback' pop-up appears when clicking on 'Feedback' icon
        ✓ checks if 'Go to Line' works if called from the status bar
        ✓ verifies if changing EOL is reflected in the status bar
      Extensions
        ✓ install and activate vscode-smoketest-check extension
      Multiroot
        ✓ shows results from all folders
        ✓ shows workspace name in title
      Localization
        ✓ starts with 'DE' locale and verifies title and viewlets text is in German
      Launch
        ✓ verifies that application launches when user data directory has non-ascii characters


  29 passing (1m)
  2 pending

Done in 66.14s.
ticino@ubuntu:~/development/vscode$ 
```
