### ISSUE TITLE
Smoke-Test: Notebook tests fail

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#107681]
#107568

The Notebook tests fail with timeouts (on today's Linux build):

```
  3) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           inserts/edits code cell:
     Error: Timeout: get element '.notebook-editor .monaco-list-row.focused' after 20 seconds.
      at /home/chrmarti/Development/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/chrmarti/Development/vscode/test/automation/out/code.js:9:58)

  4) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           inserts/edits markdown cell:
     Error: Timeout: get element '.notebook-editor .monaco-list-row.focused' after 20 seconds.
      at /home/chrmarti/Development/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/chrmarti/Development/vscode/test/automation/out/code.js:9:58)

  5) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           moves focus as it inserts/deletes a cell:
     Error: Timeout: get element '.notebook-editor .monaco-list-row.focused' after 20 seconds.
      at /home/chrmarti/Development/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/chrmarti/Development/vscode/test/automation/out/code.js:9:58)
```

**Comment by roblourens** [comment]
This depends on an extension in `./extensions`, is it possible that it wasn't built/up to date in your repo?

**Comment by chrmarti** [comment]
I think I was on the latest from today. Note that I was running the tests against the latest Insiders build, would that have that extension?

**Comment by roblourens** [comment]
No, the local extensions have to be built

**Comment by chrmarti** [comment]
I think they weren't built, now that I think about it. Can we update the https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md to include that?

**Comment by chrmarti** [comment]
Down to 1 failure:
```
  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           moves focus as it inserts/deletes a cell:
     Error: Timeout: get text content '.notebook-editor .monaco-list-row.focused .monaco-editor .view-lines' after 20 seconds.
      at /home/chrmarti/Development/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/chrmarti/Development/vscode/test/automation/out/code.js:9:58)
```

**Comment by roblourens** [comment]
I tried a few times with the same setup on linux and can't repro

**Comment by chrmarti** [comment]
Double-checked everything is up-to-date and now it's passing. Must have missed something before. Sorry about that. Closing.
