### ISSUE TITLE
Listener leak when scrolling PULL REQUESTS view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#107801]
1. Scroll aggresivly thourhg the PULL REQUESTS view
2. Notice warning in the developer console

```
Potential listener LEAK detected, having 429 listeners already. MOST frequent listener (243):
check @ event.ts:452
_event._event @ event.ts:532
updateParentChangeListener @ contextKeyService.ts:417
y @ contextKeyService.ts:404
createScoped @ contextKeyService.ts:277
getActions @ treeView.ts:1019
getResourceActions @ treeView.ts:1011
renderElement @ treeView.ts:823
renderElement @ asyncDataTree.ts:107
renderElement @ abstractTree.ts:360
renderElement @ listWidget.ts:1006
insertItemInDOM @ listView.ts:733
render @ listView.ts:677
onScroll @ listView.ts:896
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:187
fire @ event.ts:587
_setState @ scrollable.ts:364
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:418
e @ scrollableElement.ts:341
event.ts:453     at y.updateParentChangeListener (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:1846:606)
    at new y (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:1846:366)
    at _.createScoped (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:1844:547)
    at X.getActions (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:5505:174)
    at X.getResourceActions (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:5504:918)
    at e.renderElement (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:5501:400)
    at f.renderElement (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:1120:895)
    at x.renderElement (https://vscode-web-test-playground.azurewebsites.net/static-insider-0c50e1db17168a738235bd7e5c02b9f05ea5df59/out/vs/workbench/workbench.web.api.js:1089:219)
```

**Comment by isidorn** [comment]
author: @isidorn
Just to get notification when this gets closed so I verify it
