### ISSUE TITLE
TS Server fatal error:  Invalid or unexpected token

### ISSUE THREAD

**Issue by cstodor** [microsoft/vscode#107819]
We have written the need
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
SyntaxError: Invalid or unexpected token
    at Object.getTypeChecker (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103427:79)
    at synchronizeHostData (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143351:21)
    at Proxy.getProgram (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143433:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148278:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148211:42)
    at ConfiguredProject.updateGraph (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149145:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150849:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151747:44)
    at c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152070:97
    at Object.flatMap (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153089:46)
    at c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:28)
    at IOSession.Session.executeCommand (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:33)
    at IOSession.Session.onMessage (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154986:35)
    at Interface.<anonymous> (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.50.0-insider (0c50e1db17168a738235bd7e5c02b9f05ea5df59, 2020-09-30T06:53:41.824Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (12.18GB free)|
|Process Argv|--crash-reporter-id 3702c285-7bf1-454e-857d-96199271e976|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.10
gitlens|eam|10.2.2
vscode-firefox-debug|fir|2.9.1
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.11
vscode-versionlens|pfl|1.0.8
material-icon-theme|PKi|4.3.0

(2 theme extensions excluded)

</details>
ed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Please fill in the issue template with details about the problem
