### ISSUE TITLE
Frozen after saving 3000+ files at the same time

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#107935]
Issue Type: <b>Bug</b>

1. In the VS Code codebase
1. Do a workspace search for `/*---------------------------------------------------------------------------------------------`
1. Replace it with: `/*--------------------------------------------------------------------------------------------*`
1. Make sure auto save is disabled
1. Accept the replacement.
1. Now run, `save all`

**Bug**
The editor freezes

I tested this on OSS with extensions disabled 

VS Code version: Code - Insiders 1.50.0-insider (228973889bc0e352f7cd11cc14755893f8d81864, 2020-10-01T05:28:37.293Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|13%|
</details>

**Comment by mjbvz** [comment]
Having trouble collecting a perf profile for this since it freezes the window. However this warning is being continuous printed to the console:

```
[15693:1001/162209.666255:INFO:CONSOLE(344)] "[d17] potential listener LEAK detected, having 351 listeners already. MOST frequent listener (177):", source: file:///Users/matb/projects/vscode/out/vs/base/common/event.js (344)
[15693:1001/162209.666441:INFO:CONSOLE(345)] "    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:20:26
    at file:///Users/matb/projects/vscode/out/vs/workbench/services/progress/browser/progressService.js:197:69
    at ProgressService.withWindowProgress (file:///Users/matb/projects/vscode/out/vs/workbench/services/progress/browser/progressService.js:74:29)
    at createWindowProgress (file:///Users/matb/projects/vscode/out/vs/workbench/services/progress/browser/progressService.js:177:22)
    at onVisibilityChange (file:///Users/matb/projects/vscode/out/vs/workbench/services/progress/browser/progressService.js:251:52)
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:456:38)
    at file:///Users/matb/projects/vscode/out/vs/workbench/common/notifications.js:47:99
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:456:38)
    at NotificationViewItem.updateVisibility (file:///Users/matb/projects/vscode/out/vs/workbench/common/notifications.js:384:45)
    at NotificationsToasts.updateToastVisibility (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/notifications/notificationsToasts.js:424:24)
    at file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/notifications/notificationsToasts.js:404:22
    at Array.forEach (<anonymous>)
    at NotificationsToasts.layoutContainer (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/notifications/notificationsToasts.js:391:63)
    at NotificationsToasts.addToast (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/notifications/notificationsToasts.js:126:18)
    at NotificationsToasts.onDidChangeNotification (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/notifications/notificationsToasts.js:72:33)
    at file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/notifications/notificationsToasts.js:50:77
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:456:38)
    at NotificationsModel.addNotification (file:///Users/matb/projects/vscode/out/vs/workbench/common/notifications.js:103:43)
    at NotificationService.notify (file:///Users/matb/projects/vscode/out/vs/workbench/services/notification/common/notificationService.js:83:33)
    at createNotification (file:///Users/matb/projects/vscode/out/vs/workbench/services/progress/browser/progressService.js:233:63)
    at file:///Users/matb/projects/vscode/out/vs/workbench/services/progress/browser/progressService.js:286:89", source: file:///Users/matb/projects/vscode/out/vs/base/common/event.js (345)
[15693:1001/162210.017958:INFO:CONSOLE(344)] "[cf1] potential listener LEAK detected, having 439 listeners already. MOST frequent listener (265):", source: file:///Users/matb/projects/vscode/out/vs/base/common/event.js (344)
```

**Comment by mjbvz** [comment]
The `trimTrailingWhitespace` setting was slowing down saving, however I still see a large slowdown after disabling that setting.

It seems we try to show a `saving 'file.ts'` notification for every single file being saved. Not sure if this is the cause of the performance issue but it does seem to cause the notifications to get into a very odd state:

<img width="689" alt="Screen Shot 2020-10-01 at 4 30 32 PM" src="https://user-images.githubusercontent.com/12821956/94873226-79371c80-0403-11eb-8780-d2bdedf8becc.png">

**Comment by mjbvz** [comment]
I don't see this performance issue when working with 1000 files instead of 3000 (and only with the full 3000 files do I start seeing the file save notifications)

**Comment by bpasero** [comment]
I would think that leak warning can maybe be explained due to the fact that we simple instantiate so many notifications. 

The notification spam seems to originate from here:

https://github.com/microsoft/vscode/blob/3f0e5b4ab059cb6c05ecac091b652cfc50b9292f/src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts#L36-L41

**Comment by bpasero** [comment]
One idea maybe is to keep 1 notification for each file that is saved by simply updating an existing notification that is already showing. That would mean when "Cancel" is clicked, all those save operations would cancel.

**Comment by bpasero** [comment]
Rather then implementing this on the level of save participants, I added logic to throttle notification spam.

**Verification:** https://github.com/microsoft/vscode/issues/107935#issue-713243491
