### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by Muromi-Rikka** [microsoft/vscode#108188]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107127:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107162:29)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106899:50)
    at InferredProject.Project.updateGraphWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148269:38)
    at InferredProject.Project.updateGraph (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148203:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150285:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151805:26)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152062:97
    at Object.flatMap (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152062:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153081:46)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154944:28)
    at IOSession.Session.executeCommand (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:33)
    at IOSession.Session.onMessage (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154977:35)
    at Interface.<anonymous> (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.29GB free)|
|Process Argv|. --crash-reporter-id 957afdd9-cfb7-4685-9dc4-a1b0ba6e72ef|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
ng-template|Ang|0.1001.0
dart-code|Dar|3.15.0
flutter|Dar|3.15.0
vscode-eslint|dba|2.1.8
translation|dus|0.0.4
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
vscode-flutter-i18n-json|ess|0.28.0
go|gol|0.17.2
fish-redux-template|hua|0.0.7
vscode-format-context-menu|lac|1.0.4
Angular-BeastCode|Mik|10.0.3
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.6.0
vscode-language-pack-zh-hans|MS-|1.49.2
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
azure-account|ms-|0.9.3
hexeditor|ms-|1.3.0
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
arrr|obe|0.1.3
material-icon-theme|PKi|4.3.0
synthwave-vscode|Rob|0.1.8
lit-plugin|run|1.2.1
vscode-nginx|wil|0.7.2
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Closing as not actionable without more info
