### ISSUE TITLE
At startup

### ISSUE THREAD

**Issue by gino-wofford** [microsoft/vscode#108200]
Issue Type: <b>Bug</b>

At startup
[2020-10-06 14:07:19.395] [renderer1] [error] spawn UNKNOWN: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:549:9)
    at r.startWatcher (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1386:56)
    at new r (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1385:959)
    at t.FileWatcher.startWatching (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1387:808)
    at new t.FileWatcher (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1387:732)
    at r.doRefreshRecursiveWatchers (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1748:23)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1747:369
    at l.queue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:128:270)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:774
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:216
[2020-10-06 14:07:28.436] [renderer1] [error] Extension host terminated unexpectedly. The following extensions were running: 

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.80GB (0.52GB free)|
|Process Argv|--crash-reporter-id a2b67ca8-3dda-476e-97a0-2318224a66a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vbscript|Dar|1.0.4
vscode-eslint|dba|2.1.8
vscode-pull-request-github|Git|0.20.0
csharp|ms-|1.23.2
pyright|ms-|1.1.77
python|ms-|2020.9.112786
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
vscode-ansible|vsc|0.5.2

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by JacksonKearl** [comment]
What is the actual issue you're seeing here? For instance does VS Code fail to start or what exactly?
