### ISSUE TITLE
macOS: understand high CPU file watching issues in 1.50

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108441]
There are some reports from macOS users seeing high CPU in the watcher service process:
* https://github.com/microsoft/vscode/issues/108408
* https://github.com/microsoft/vscode/issues/108387
* https://github.com/microsoft/vscode/issues/108376

In September we updated our file watcher library [chokidar](https://github.com/paulmillr/chokidar) from `3.2.3` to `3.4.2` (https://github.com/microsoft/vscode/commit/0de4890a28ab466c340a94fad33e5e8c16cac89d) with the goal to actually reduce the CPU load. I tested this on macOS and Linux and found the CPU pressure to be smaller. This also matches what was announced from their release notes.

@n808 @victorpavlov @davidham @hDmtP merging your issues into here. What would help is to understand better what kind of folder you open triggers this:
* does this NOT reproduce with `1.49.3` ([download](https://az764295.vo.msecnd.net/stable/2af051012b66169dde0c4dfae3f5ef48f787ff69/VSCode-darwin-stable.zip))
* could it have cyclic symbolic links
* would I be able to get access to such a folder to try for myself
* does the high CPU load eventually go away or stay high?

//cc @paulmillr for additional insights if possible

**Comment by hDmtP** [comment]
No there is no such issue with the 1.49 version.

**Comment by paulmillr** [comment]
@bpasero in your tests, CPU usage became smaller, but from reports, it got up?

**Comment by davidham** [comment]
Hi @bpasero, thanks for the reply.

I did not observe the COU to go down, and I quit out of it after 10 minutes
or so.

The folder where this is happening does have some symlinks in it, and while
they should not be cyclic (that is, the path stops at a given point),
that’s a good tip and I will look into it.

The GitHub project this is in contains a lot of Terraform code, so there
are a lot of `.terraform` folders that have a lot of hidden files that are
not tracked in Git.

**Comment by bpasero** [comment]
@hDmtP does it reproduce with all folders? and in the folders it does reproduce, any chance for cyclic symbolic links?

@paulmillr yeah I ran some tests on very large folders to verify the improved performance of reading directories (via `readdirp`) recursively and felt that while the overall operation takes longer, the CPU and memory consumption is lower, which I quite liked. The reason I am wondering about cyclic symbolic links is the [release notes of chokidar](https://github.com/paulmillr/chokidar/blob/master/.github/full_changelog.md#chokidar-340-apr-26-2020) 3.4 saying:

> Support for directory-based symlinks.

@davidham please check and also let me know if it reproduces with other folders.

**Comment by victorpavlov** [comment]
@bpasero On the latest release before 1.50 such an issue was not seen. In my project are couple symbol links which redirects to the docroot. Currently that's all what I can say. I will do more testing on Monday.

**Comment by smiLLe** [comment]
happens to me in 1.49.3 after upgrading flutter to 1.22.1

**Comment by bpasero** [comment]
@victorpavlov is `docroot` outside the workspace folder? Is this a folder I could test this on my machine?

@smiLLe the was no change before `1.50.x` in this area.

**Comment by n808** [comment]
>> does the high CPU load eventually go away or stay high?
Yes, after around 18-20 minutes the system goes back to normal.

**Comment by n808** [comment]
It turns out my project had a symbolic link pointing back to the root of the project. When I removed this link, CPU usage is normal on startup. (So that solves the issue for my part, as the link was not really necessary.)

**Comment by paulmillr** [comment]
@bpasero I don't think we can easily handle cases like this, can we?

**Comment by bpasero** [comment]
@paulmillr as a way for VSCode to mitigate this issue as part of a recovery release, could you release a new version with a new setting that allows to keep the previous behaviour (which I think was to support file-based symbolic links) but not watch folder-based symbolic links until we figure out a better solution?

As for how to prevent this: isn't `chokidar` keeping a map of watched files and folders somewhere that could be used to detect if a folder has been watched already? This probably requires something like [`fs.realPath`](https://nodejs.org/docs/v12.14.1/api/fs.html#fs_fs_realpath_path_options_callback) to be used to know the exact path on disk.

**Comment by victorpavlov** [comment]
@bpasero For me it happens only on one project from all projects I'm having now. Unfortunately I can't grant you access to this project, but here's how the structure of the project is looking now:
Root level:
<img width="361" alt="Screenshot 2020-10-12 at 12 09 13" src="https://user-images.githubusercontent.com/3427831/95728425-2c193d00-0c84-11eb-8880-984e6d0f6871.png">
And here's `docroot` with symlinks:
<img width="379" alt="Screenshot 2020-10-12 at 12 09 45" src="https://user-images.githubusercontent.com/3427831/95728497-3e937680-0c84-11eb-8fdd-0c01325cec10.png">
And those symlinks just redirects back to the `docroot`.

**Comment by bpasero** [comment]
@victorpavlov thanks, so this looks to be the issue, having cyclic symbolic links in the project structure.

**Comment by paulmillr** [comment]
I'll try to dig into this today, if I can't, i'll look around pushing a temp option that disables the behavior

**Comment by bpasero** [comment]
@paulmillr thanks!

**Comment by hDmtP** [comment]
Can anyone please(🙏🏼) explain to me what is cyclic symbolic links you guys are talking about?

**Comment by bpasero** [comment]
@hDmtP sorry sure: a symbolic folder link that eventually points to a parent of that symbolic link so that if you would iterate over the folders it would be endless.

**Comment by hDmtP** [comment]
Got it @bpasero. Thanks!

**Comment by paulmillr** [comment]
Is there any way to test this with readdirp@master? This should handle it.

**Comment by bpasero** [comment]
@paulmillr looks promising! I gave it a quick test running VSCode locally on a folder with symbolic links and could not reproduce the CPU spike when I applied the change in `readdirp` locally 👍 

I could not see the error bubbling up either, I am not sure how you handle it in `chokidar`.

**Comment by paulmillr** [comment]
@bpasero have you had a chance to test this on win32?

**Comment by bpasero** [comment]
@paulmillr vscode is actually not using chokidar on Windows, only macOS and Linux.

**Comment by paulmillr** [comment]
chokidar@3.4.3 is out now.

**Comment by bpasero** [comment]
Thanks 🤝

**Comment by bpasero** [comment]
@paulmillr I was curious and checked the unit test results from `3.4.2` vs `3.4.3` to make sure there are no new regressions from the change. Interestingly you seem to have a test `should not recurse indefinitely on circular symlinks` which now seems to fail but with the error you added, so it seems fine?

* `3.4.2` green Linux test run: https://github.com/paulmillr/chokidar/runs/954558070
* `3.4.3` red Linux test run: https://github.com/paulmillr/chokidar/runs/1247209219

```
1) chokidar
       fs.watch (non-polling)
         watch symlinks
           should not recurse indefinitely on circular symlinks:
     Error: Circular symlink detected: "/home/runner/work/chokidar/chokidar/test-fixtures/44/subdir/circular" points to "/home/runner/work/chokidar/chokidar/test-fixtures/44"
      at ReaddirpStream._getEntryType (node_modules/readdirp/index.js:217:34)
      at async ReaddirpStream._read (node_modules/readdirp/index.js:128:31)
```

Do the tests need adjustment?

**Comment by bhmasterson** [comment]
Still happening w/1.5.1 updated a week ago.  Suggestions? 

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
