### ISSUE TITLE
Remote-SSH Could not establish connection: The VS Code Server failed to start.

### ISSUE THREAD

**Issue by jdrecoulle0001** [microsoft/vscode#108558]
- VSCode Version: 5.6.1
- OS Version: Windows 10 Home, Build: 19041.508

Steps to Reproduce:

1. Remote SSH: Connect to Host...
2. Enter my password

Does this issue occur when all extensions are disabled?: Yes/No

When trying to connect to the server set up for my class, after doing connect to host and entering my password, I get a failure saying "Could not establish connection to (server): The VS Code Server failed to start.". I included the log below, please let me know if anymore information is needed.

[22:44:41.530] Log Level: 2
[22:44:41.532] remote-ssh@0.55.0
[22:44:41.533] win32 x64
[22:44:41.533] SSH Resolver called for "ssh-remote+elnux1.cs.umass.edu", attempt 1
[22:44:41.534] SSH Resolver called for host: elnux1.cs.umass.edu
[22:44:41.534] Setting up SSH remote "elnux1.cs.umass.edu"
[22:44:41.543] Using commit id "93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3" and quality "stable" for server
[22:44:41.543] Install and start server if needed
[22:44:41.545] Checking ssh with "ssh -V"
[22:44:41.570] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[22:44:41.572] Running script with connection command: ssh -T -D 52856 elnux1.cs.umass.edu bash
[22:44:41.573] Terminal shell path: C:\Windows\System32\cmd.exe
[22:44:41.775] > Password:]0;C:\Windows\System32\cmd.exe
[22:44:41.775] Got some output, clearing connection timeout
[22:44:41.776] Showing password prompt
[22:44:46.874] Got password response
[22:44:46.875] "install" wrote data to terminal: "************"
[22:44:46.886] > 
[22:44:47.611] > 518fea47ac5d: running
[22:44:47.656] > Acquiring lock on /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf
> 16c5a4b10e4d5f89737d9c2c25488a3/vscode-remote-lock.jrecoulle.93c2f0fbf16c5a4b10e
> 4d5f89737d9c2c25488a3
[22:44:47.675] > Found existing installation at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/
> bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3...
[22:44:47.738] > SHELL=/bin/bash
> KRB5CCNAME=KEYRING:persistent:35904
> PWD=/nfs/elsrv4/users2/grad/jrecoulle
> LOGNAME=jrecoulle
> XDG_SESSION_TYPE=tty
> MOTD_SHOWN=pam
> HOME=/nfs/elsrv4/users2/grad/jrecoulle
> LANG=C.UTF-8
> VSCODE_AGENT_FOLDER=/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server
> SSH_CONNECTION=73.238.133.148 52858 128.119.243.147 22
> XDG_SESSION_CLASS=user
> USER=jrecoulle
> WWW_HOME=http://edlab-www.cs.umass.edu/
> SHLVL=1
> XDG_SESSION_ID=43213
> XDG_RUNTIME_DIR=/run/user/35904
> SSH_CLIENT=73.238.133.148 52858 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin/:/us
> r/games:/usr/local/games:/usr/ucb:/usr/bin/X11:/usr/bin:/bin:/usr/sbin:/usr/loca
> l/bin:/exp/rcf/share/bin
[22:44:47.745] > 
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/35904/bus
> MAIL=/var/spool/mail/jrecoulle
> _=/usr/bin/printenv
> Starting server with command... /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server
> /bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/server.sh --host=127.0.0.1 --enabl
[22:44:47.750] > 
> e-remote-auto-shutdown  --port=0 &> "/nfs/elsrv4/users2/grad/jrecoulle/.vscode-s
> erver/.93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3.log" < /dev/null
> Waiting for server log...
[22:44:47.769] > 
[22:44:48.245] > Waiting for server log...
[22:44:48.751] > Waiting for server log...
[22:44:49.260] > Waiting for server log...
[22:44:49.765] > Waiting for server log...
[22:44:50.275] > Waiting for server log...
[22:44:50.780] > Waiting for server log...
[22:44:51.286] > Waiting for server log...
[22:44:51.789] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[22:44:51.801] > 
> Server did not start successfully. Full server log at /nfs/elsrv4/users2/grad/jr
> ecoulle/.vscode-server/.93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3.log >>>        
> Error: Cannot find module 'minimist'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
[22:44:51.806] > 
>   ],
>   phase: 'loading',
>   moduleId: 'minimist',
>   neededBy: [ 'vs/platform/environment/node/argv' ]
> }
> Error: Cannot find module 'semver-umd'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'semver-umd',
>   neededBy: [
>     'vs/platform/extensionManagement/node/extensionDownloader',
>     'vs/workbench/services/extensions/node/extensionPoints',
>     'vs/platform/extensionManagement/node/extensionsScanner',
>     'vs/platform/extensionManagement/node/extensionManagementService'
>   ]
> }
> Error: Cannot find module 'applicationinsights'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
[22:44:51.811] > 
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'applicationinsights',
>   neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ]
> }
> Error: Cannot find module 'cookie'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'cookie',
>   neededBy: [ 'vs/server/webClientServer' ]
[22:44:51.817] > 
> }
> Error: Cannot find module 'yauzl'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yauzl',
>   neededBy: [ 'vs/base/node/zip' ]
> }
> Error: Cannot find module 'yazl'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yazl',
>   neededBy: [ 'vs/base/node/zip' ]
[22:44:51.824] > 
> }
> <<< End of server log
> 518fea47ac5d##32##
[22:44:51.824] Received install output: 518fea47ac5d##32##
[22:44:51.827] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:128732)
	at I (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[22:44:51.828] ------

[22:44:52.172] "install" terminal command done
[22:44:52.172] Install terminal quit with output:

**Comment by alannt777** [comment]
This issue doesn't belong here. Open the issue in [this repo](https://github.com/microsoft/vscode-remote-release)
