### ISSUE TITLE
Debug adapter process has terminated unexpectedly on Raspberry pi

### ISSUE THREAD

**Issue by mong87suk** [Microsoft/vscode#10866]
- VSCode Version: 1.5.0
- OS Version: Raspbian GNU/Linux 8.0 (jessie)
                      
Steps to Reproduce:

I installed visual studio code on raspberry pi.

pi@KERNEL_BZ:~ $ uname -a
Linux KERNEL_BZ 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

This is raspberry pi's information.

This is installation process

1. git clone https://github.com/mirosoft/vscode

2. cd vscode

3. ./scripts/npm.sh intall --arch=armhf

4. ./scripts/code.sh

5. Edit on product.json
     adding following to product.jsson

      "extensionsGallery": {
        "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
        "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
        "itemUrl": "https://marketplace.visualstudio.com/items"
        }

After I installed the visual studio code on raspberry pi.
I've tried to debug  by using cpp tools. 
But Debug adapter process has terminated unexpectedly.
I don't why this error happend.
Could you explain why this error happend?
I really want to solve this problem.
Thank you.

Best regards,
Felinus jeong

Conflict detected, command `workbench.action.navigateForward` cannot be triggered by ctrl+shift+- due to workbench.action.zoomOut
[Extension Host] debugger listening on port 5870
[Extension Host] TypeError: Cannot read property 'forEach' of null
    at LanguageClient.cleanUp (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/lib/main.js:471:24)
    at LanguageClient.stop (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/lib/main.js:454:14)
    at LanguageClient.handleConnectionError (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/lib/main.js:684:18)
    at LanguageClient.createConnection.errorHandler (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/lib/main.js:559:19)
    at /home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/lib/main.js:45:42
    at CallbackList.invoke (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:78:22)
    at CallbackList.invoke (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/pi/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.8.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)
Conflict detected, command `workbench.action.navigateForward` cannot be triggered by ctrl+shift+- due to workbench.action.zoomOut
[uncaught exception]: Error: read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at Pipe.onread (net.js:552:26)
Debug adapter process has terminated unexpectedly
Debug adapter process has terminated unexpectedly: Error: Debug adapter process has terminated unexpectedly
    at Object.create (file:////home/pi/Development/vscode/out/vs/base/common/errors.js:317:22)
    at file:////home/pi/Development/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:558:67
    at Object.notifyError [as _notify] (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:1209:50)
    at Object.state_error_notify.enter (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:901:30)
    at _Base.Class.define._run (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.define._chainedError (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:1031:18)
    at error (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:736:33)
    at ErrorPromise_ctor.ErrorPromise_then [as then] (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:1436:50)
    at Object.state_waiting.enter (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:747:28)
    at _Base.Class.define._run (file:////home/pi/Development/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)

lunch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/test_led",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        },
        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/test_led",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "processId": "${command.pickProcess}",
            "externalConsole": false,
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        }
    ]
}

**Comment by weinand** [comment]
The cpp tools are not part of VS Code but a separate extension. I'll move this issue to the correct repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscppsamples#164

**Comment by mong87suk** [comment]
Thank for your support.
