### ISSUE TITLE
TS Server fatal error:  path.replace is not a function

### ISSUE THREAD

**Issue by HiLorrie** [microsoft/vscode#108640]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.7

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: path.replace is not a function
    at normalizeSlashes (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:6305:21)
    at combinePaths (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:6366:28)
    at getPathComponents (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:6280:16)
    at Object.getNormalizedPathComponents (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:6406:37)
    at getSubPatternFromSpec (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18075:29)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18059:28
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at getRegularExpressionsForWildcards (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18058:19)
    at Object.getRegularExpressionForWildcard (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18044:24)
    at getWildcardDirectories (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:29099:34)
    at matchFileNames (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:28964:35)
    at getFileNames (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:28515:26)
    at parseJsonConfigFileContentWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:28447:18)
    at Object.parseJsonSourceFileConfigFileContent (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:28405:16)
    at ProjectService.loadConfiguredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145749:44)
    at ProjectService.createAndLoadConfiguredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145723:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145728:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146610:44)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146929:97
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146929:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147792:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149555:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149546:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149555:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149579:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150895:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.44GB (2.51GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|5.7.1
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
todo-tree|Gru|0.0.183
rust-test-lens|hde|1.0.0
vue-snippets|hol|0.1.12
svg-icons|idl|0.8.0
svg|joc|1.3.10
docthis|joe|0.7.1
vue|liu|0.1.5
debugger-for-chrome|msj|4.12.11
node-modules-resolve|nau|1.0.2
vetur|oct|0.28.0
javascript-test-runner|osh|1.2.1
csslint|ray|0.0.11
npmsmartimporter|ref|3.0.0
any-rule|rus|0.3.6
vs-code-prettier-eslint|rve|0.3.2
prettier-vscode-space-parenthesis|sch|0.17.101
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
svg-snippets|sid|1.0.1
element-ui-snippets|SS|0.7.2
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.85.0
vscode-lldb|vad|1.6.0
vscodeintellicode|Vis|1.2.10
expresssnippet|vla|0.2.4
vscode-icons|vsc|11.0.0
JavaScriptSnippets|xab|1.8.0
axios-snippets|Ygg|1.0.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as this is using an old TS version. let us know if you see this with TS 4.0.3+
