### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script should not exist and not be open already

### ISSUE THREAD

**Issue by SoLasseVanttinen** [microsoft/vscode#108774]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.2

**Steps to reproduce crash**
1. Open pull request on Atlassians "Jira and Bitbucket" extensions
2. Open a .TS file on the extension
3. A notification appears that TS had died...

**TS Server Log**
The folder pointed by the server log entry in this page was empty. I have the settings enabled for verbose logging as requested. 

**Environment**
Working on Windows 10 / WSL 2
VS code version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z (1 mo ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression: Script should not exist and not be open already
    at ProjectService.applyChangesInOpenFiles (/home/lasse/dev/backend/node_modules/typescript/lib/tsserver.js:143322:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/lasse/dev/backend/node_modules/typescript/lib/tsserver.js:144214:46)
    at /home/lasse/dev/backend/node_modules/typescript/lib/tsserver.js:145957:88
    at IOSession.Session.executeWithRequestId (/home/lasse/dev/backend/node_modules/typescript/lib/tsserver.js:145948:28)
    at IOSession.Session.executeCommand (/home/lasse/dev/backend/node_modules/typescript/lib/tsserver.js:145957:33)
    at IOSession.Session.onMessage (/home/lasse/dev/backend/node_modules/typescript/lib/tsserver.js:145981:35)
    at Interface.<anonymous> (/home/lasse/dev/backend/node_modules/typescript/lib/tsserver.js:147296:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|8.75GB (5.06GB free)|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
vscode-firefox-debug|fir|2.9.1
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.11
jinja|who|0.0.8
jslint|ajh|1.2.1
Bookmarks|ale|11.3.1
numbered-bookmarks|ale|7.2.0
project-manager|ale|11.3.0
gitstash|art|3.3.0
atlascode|atl|2.8.3
vscode-django|bat|0.20.0
bb-spectacle|bb-|0.3.0
git-temporal-vscode|bee|1.0.0
git-easy|bib|1.11.0
vscode-coverage-highlighter|bra|1.0.3
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.6.12
python-extension-pack|don|1.6.0
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
json2ts|Gre|0.0.6
vscode-git-add-and-commit|iva|2.1.1
git-tree-compare|let|1.10.0
MagicPython|mag|1.1.0
code-coverage|mar|1.2.3
tgit-cmds|mbi|1.3.0
git-graph|mhu|1.26.0
vscode-docker|ms-|1.6.0
python|ms-|2020.9.114305
vscode-typescript-tslint-plugin|ms-|1.2.3
gulptasks|nic|1.3.1
tsimporter|pmn|2.0.1
vscode-yaml|red|0.11.1
git-merger|sha|0.4.1
vscode-multiclip|sle|0.1.5
code-spell-checker|str|1.9.0
git-rebase-shortcuts|tre|1.0.5
vscodeintellicode|Vis|1.2.10
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by SoLasseVanttinen** [comment]
Seems to work on TS version 3.9.7 (VS code version) but fails on TS version 3.8.2 (codebase version)
