### ISSUE TITLE
Toggle word wrap on diff editor fails: editor.invokeWithinContext

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10874]
- open a diff editor
- from the menu pick View > toggle word wrap

```
messageService.js:80 editor.invokeWithinContext is not a function: TypeError: editor.invokeWithinContext is not a function
    at ToggleWordWrapAction.EditorCommand.runCommand (file:////Users/bpasero/Development/monaco/out/vs/editor/common/config/config.js:79:27)
    at handler (file:////Users/bpasero/Development/monaco/out/vs/editor/common/config/config.js:37:67)
    at InstantiationService.invokeFunction (file:////Users/bpasero/Development/monaco/out/vs/platform/instantiation/common/instantiationService.js:47:34)
    at file:////Users/bpasero/Development/monaco/out/vs/platform/commands/common/commandService.js:34:77
    at CompletePromise_then [as then] (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1566:49)
    at CommandService.executeCommand (file:////Users/bpasero/Development/monaco/out/vs/platform/commands/common/commandService.js:28:78)
    at EventEmitter.<anonymous> (file:////Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/integration.js:48:38)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by alexandrudima** [comment]
@bpasero I cannot reproduce. I did touch code in this area and this is worrying, but simply opening a diff editor doesn't seem to trigger the issue for me.

**Comment by bpasero** [comment]
@alexandrudima I can reproduce and show you if you want, just drop by

**Comment by bpasero** [comment]
![untitled](https://cloud.githubusercontent.com/assets/900690/18056308/a4722ac6-6e0b-11e6-90ff-d1b6d5e791dc.gif)

**Comment by alexandrudima** [comment]
Ok, I can reproduce with the additional step:
* keep focus in the git viewlet

**Comment by alexandrudima** [comment]
Alternative steps:
* click on the git viewlet
* the diff editor pops up
* keep focus in the git viewlet
* press ctrl+f

**Comment by alexandrudima** [comment]
Nice catch!
