### ISSUE TITLE
Pipe error when calling vscode from WSL 

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode#108741]
Is it possible use vscode and pipes from WSL?

From a WSL, I called 
```bash
alan@local:~$ cmd.exe /c 'code --list-extensions'|grep ms
```

and I get 
```
net.js:320
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:320:26)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStderr [as stderr] (internal/process/stdio.js:40:14)
    at Object.get (internal/console/constructor.js:158:40)
    at Object.Console.<computed> (internal/console/constructor.js:276:46)
    at Object.warn (internal/console/constructor.js:287:61)
    at writeOut (internal/process/warning.js:27:3)
    at process.onWarning (internal/process/warning.js:79:3)
    at process.emit (events.js:223:5)
    at internal/process/warning.js:52:24
    at processTicksAndRejections (internal/process/task_queues.js:76:11) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}

```
- VSCode Version: 1.50.0
- OS Version: Windows 10.0.19041

**Comment by aeschli** [comment]
This is WSL issue. Please file against https://github.com/microsoft/WSL
