### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by mojo2012** [microsoft/vscode#108898]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151815:26)
    at /Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152070:97
    at Object.flatMap (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153089:46)
    at /Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/Applications/Development/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (2.13GB free)|
|Process Argv|-psn_0_913631 --crash-reporter-id 4ae431b1-4ae7-4382-a525-d0643853648e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
depot|aft|1.2.1
Bookmarks|ale|11.4.0
vscode-eclipse-keybindings|alp|0.12.0
pgformatter|bra|1.16.0
phpserver|bra|3.0.1
vscode-postgres|cko|1.1.13
vscode-eslint|dba|2.1.10
java-decompiler|dgi|0.0.2
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
LogFileHighlighter|emi|2.9.0
vscode-toggle-column-selection|eri|1.0.6
vscode-highlight|fab|1.4.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.1
vscode-yarn|gam|1.7.1
terraform|has|2.2.3
haxe-hl|Hax|1.1.1
vscode-test-explorer|hbe|2.19.1
theme-macos-classic|hua|1.2.1
composer|ika|0.7.1
haxe-jsx|inf|0.0.5
java-properties|ith|0.0.2
yuml|Jai|3.5.1
plantuml|jeb|2.13.14
pubspec-assist|jer|2.2.1
svg|joc|1.3.11
sftp|lix|1.12.9
eclipse-new-java-project|mel|1.0.1
vscode-antlr4|mik|2.2.4
auto-barrel|mik|1.7.1
vscode-azureterraform|ms-|0.3.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.3
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.114305
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.3
debugger-for-chrome|msj|4.12.11
gradle-language|nac|0.2.3
vshaxe|nad|2.21.4
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.22.0
vscode-manifest-yaml|Piv|1.22.0
vscode-spring-boot|Piv|1.22.0
java|red|0.69.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.11.1
lit-plugin|run|1.2.1
markdown-preview-enhanced|shd|0.5.13
sonarlint-vscode|Son|1.17.0
cucumber|ste|0.12.0
pdf|tom|1.1.0
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.5.0
haxe-checkstyle|vsh|1.6.1
haxe-extension-pack|vsh|1.3.0
haxe-test-adapter|vsh|1.2.10
hxcpp-debugger|vsh|1.2.4
file-icons-mac|way|1.0.1
vscode-icons-mac|way|7.25.3
codedox|wig|1.3.1
local-history|xyz|1.8.1
vscode-java-saber|You|0.1.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Ahmeed2m** [comment]
@mjbvz  
same issue here

Issue Type: <b>Bug</b>

**TypeScript Version:** 4.0.3

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152055:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:153089:46)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.8.16-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|7.57GB (0.61GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|2.0.0
vscode-changelog-generator|axe|1.0.0
vscode-opennewinstance|chr|0.0.7
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.13
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-todo-plus|fab|4.18.0
vscode-pull-request-github|Git|0.20.1
template-string-converter|meg|0.2.2
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.1
cpptools|ms-|1.0.1
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.3.0
code-spell-checker|str|1.9.2
pdf|tom|1.1.0
vscode-jss-snippets|vis|0.2.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing this as we need information from the original poster to investigate this
