### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by DaniGTA** [microsoft/vscode#108859]
Issue Type: <b>Bug</b>

I was debugging my vue project in a workspace, and editing a .ts file then after save it crashed.

**TypeScript Version:** 4.1.0-dev.20201016

**Steps to reproduce crash**
1. Edit .ts file
2. Save .ts file

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:109191:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:109226:29)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:108963:50)
    at InferredProject.Project.updateGraphWorker (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:151050:38)
    at InferredProject.Project.updateGraph (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:150984:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:153075:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:154595:26)
    at c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:154852:97
    at Object.flatMap (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:154852:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:155871:46)
    at c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:157744:88
    at IOSession.Session.executeWithRequestId (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:157735:28)
    at IOSession.Session.executeCommand (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:157744:33)
    at IOSession.Session.onMessage (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:157768:35)
    at Interface.<anonymous> (c:\Users\danig\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.1.20201016\node_modules\typescript\lib\tsserver.js:159978:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.51.0-insider (605bc4ec1eaf8dc1acd89a0c3c5743926ed0dc09, 2020-10-12T10:52:10.028Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.81GB free)|
|Process Argv|--crash-reporter-id 389cf739-eb5b-4f3b-81a6-f0f8ad7b0e8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
ng-template|Ang|0.1001.0
i18n-ally|ant|2.3.20
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.5.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.37.1
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.10.21
vscode-eslint|dba|2.1.10
angular-extension-pack|dog|9.3.0
githistory|don|0.6.12
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
vue-inline-template|fai|1.0.1
vue-format|feb|0.1.8
git-project-manager|fel|1.7.1
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
vscode-lombok|Gab|1.0.1
vscode-pull-request-github|Git|0.20.1
gitlab-workflow|Git|3.3.0
vscode-test-explorer|hbe|2.19.1
beautify|Hoo|1.5.0
discord-vscode|icr|4.0.0
angular2-switcher|inf|0.3.3
docthis|joe|0.7.1
Angular2|joh|9.1.2
vscode-gutter-preview|kis|0.26.2
electron-debug|kod|18.11.1
refactorix|kri|0.3.6
graphql-for-vscode|kum|1.15.3
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.3
python|ms-|2020.9.114305
remote-containers|ms-|0.145.0
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
typescript-javascript-grammar|ms-|0.0.53
vscode-js-profile-flame|ms-|0.0.12
vscode-typescript-next|ms-|4.1.20201016
vsliveshare|ms-|1.0.3014
debugger-for-chrome|msj|4.12.11
arrr|obe|0.1.3
vetur|oct|0.28.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.3.0
quicktype|qui|12.0.46
java|red|0.69.0
vscode-yaml|red|0.11.1
vscode-jest-test-adapter|rtb|0.2.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.1.5
sonarlint-vscode|Son|1.17.0
autoimport|ste|1.5.3
tech-debt-tracker|Ste|0.27.5
move-ts|str|1.12.0
sass-indented|syl|1.8.12
vscode-status-bar-format-toggle|tom|2.0.0
errorlens|use|3.2.3
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
quokka-vscode|Wal|1.0.326
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
