### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by nonameolsson** [microsoft/vscode#108826]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.7.2

**Steps to reproduce crash**
1. Just starting VS Code, restarting extension host or restarting TS Server.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/andreasolsson/Code/Work/Client.CustomerPortal","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/andreasolsson/Code/Work/Client.CustomerPortal","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:137724:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:137710:29)
    at ProjectService.getOrCreateOpenScriptInfo (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:138113:33)
    at ProjectService.applyChangesInOpenFiles (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:138332:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:139212:46)
    at /Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:140861:28)
    at IOSession.Session.executeCommand (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:140870:33)
    at IOSession.Session.onMessage (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:140893:35)
    at Interface.<anonymous> (/Users/andreasolsson/Code/Work/Client.CustomerPortal/node_modules/typescript/lib/tsserver.js:142208:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.51.0-insider (89c002ab02f87102d91efc83c191ef1174756c6a, 2020-10-15T23:12:18.967Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 4, 3|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv|-psn_0_2138634 --crash-reporter-id 4e90d641-557f-43e9-9110-1943f553fc47|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.2.0
depot|aft|1.1.1
project-manager|ale|11.3.0
i18n-ally|ant|2.3.20
docs-view|bie|0.0.3
turbo-console-log|Cha|1.4.0
jsrefactor|cms|2.20.6
codestream|Cod|10.0.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.10
vscode-deepscan|Dee|1.10.3
devdocs|dei|0.2.0
git-extension-pack|don|0.1.3
githistory|don|0.6.12
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
file-icons|fil|1.0.26
vscode-firefox-debug|fir|2.9.1
todo-tree|Gru|0.0.183
rest-client|hum|0.24.3
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|1.1.0
theme-karyfoundation-themes|kar|20.0.3
git-graph|mhu|1.26.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.3
vscode-edge-devtools|ms-|1.0.9
mssql|ms-|1.9.0
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
azure-account|ms-|0.9.3
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.1.0
sqltools|mtx|0.23.0
sqltools-driver-mssql|mtx|0.2.0
color-highlight|nau|2.3.0
hocus-pocus|nic|1.6.0
material-icon-theme|PKi|4.3.0
mdx|sil|0.1.0
swdc-100-days-of-code|sof|1.0.11
swdc-vscode|sof|2.3.13
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
quokka-vscode|Wal|1.0.326
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

(16 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as this is an old TypeScript version. Let us know if you see this in TS 4.0+
