### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by MartinBreznik** [microsoft/vscode#108991]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.2

**Steps to reproduce crash**
1. write code
2. software randomly crashes at what seems to be no particular order
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions/node_modules/typescript/lib/tsserver.js:152047:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions/node_modules/typescript/lib/tsserver.js:153081:46)
    at /root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions/node_modules/typescript/lib/tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions/node_modules/typescript/lib/tsserver.js:154944:28)
    at IOSession.Session.executeCommand (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions/node_modules/typescript/lib/tsserver.js:154953:33)
    at IOSession.Session.onMessage (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions/node_modules/typescript/lib/tsserver.js:154977:35)
    at Interface.<anonymous> (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions/node_modules/typescript/lib/tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.21GB free)|
|Process Argv|--crash-reporter-id cf335297-6a89-493b-a493-a33b4931fad9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container 4a0030dad6a7 (/nifty_jones)|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (2 x 1992)|
|Memory (System)|1.94GB (0.42GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.0.0
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
vscode-react-component-generator|abd|0.0.3
beautify|Hoo|1.5.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
