### ISSUE TITLE
TS Server fatal error:  Unexpected token } in JSON at position 1148

### ISSUE THREAD

**Issue by avinashkurup** [microsoft/vscode#109053]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
SyntaxError: Unexpected token } in JSON at position 1148
    at JSON.parse (<anonymous>)
    at Function.create (/home/avinash_kurup/.vscode-server/extensions/denoland.vscode-deno-2.3.2/node_modules/typescript-deno-plugin/out/core/hash_meta.js:72:30)
    at CacheModule.resolveModule (/home/avinash_kurup/.vscode-server/extensions/denoland.vscode-deno-2.3.2/node_modules/typescript-deno-plugin/out/core/deno_cache.js:114:43)
    at ModuleResolver.resolveModules (/home/avinash_kurup/.vscode-server/extensions/denoland.vscode-deno-2.3.2/node_modules/typescript-deno-plugin/out/core/module_resolver.js:118:60)
    at InferredProject.languageServiceHost.resolveModuleNames (/home/avinash_kurup/.vscode-server/extensions/denoland.vscode-deno-2.3.2/node_modules/typescript-deno-plugin/out/typescript-deno-plugin/src/plugin.js:307:50)
    at actualResolveModuleNamesWorker (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:102685:133)
    at resolveModuleNamesWorker (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:102906:26)
    at resolveModuleNamesReusingOldState (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:102980:24)
    at processImportedModules (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:104466:35)
    at findSourceFile (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:104209:17)
    at processImportedModules (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:104502:25)
    at findSourceFile (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:104209:17)
    at /home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:104038:85
    at getSourceFileFromReferenceWorker (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:104005:34)
    at processSourceFile (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:104038:13)
    at processRootFile (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:103861:13)
    at /home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:102785:60
    at Object.forEach (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:102785:16)
    at synchronizeHostData (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:143341:26)
    at Proxy.getProgram (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:143433:13)
    at InferredProject.Project.updateGraphWorker (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:148278:53)
    at InferredProject.Project.updateGraph (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:148211:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:150293:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:151813:26)
    at /home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:152070:97
    at Object.flatMap (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:153089:46)
    at /home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/home/avinash_kurup/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:57:08.739Z)
OS version: Windows_NT ia32 6.1.7601
Remote OS version: Linux x64 4.15.0-118-generic
Remote OS version: Linux x64 4.15.0-118-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 x 2933)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.47GB (1.67GB free)|
|Process Argv|--file-uri vscode-remote://ssh-remote%2B10.10.11.156/home/avinash_kurup/workspaces/netspective-workspaces.code-workspace --crash-reporter-id f0fe2974-1890-45e5-8e3f-fec05fd4afdb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.10.11.156|
|OS|Linux x64 4.15.0-118-generic|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 2882)|
|Memory (System)|15.49GB (7.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.10.11.156|
|OS|Linux x64 4.15.0-118-generic|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 2882)|
|Memory (System)|15.49GB (7.47GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
vscode-remote-extensionpack|ms-|0.20.0
vscode-changelog-generator|axe|1.0.0
path-intellisense|chr|2.3.0
vscode-deno|den|2.3.2
quicktype|qui|12.0.46
markdown-preview-enhanced|shd|0.5.13
vscodeintellicode|Vis|1.2.10

</details>

**Comment by mjbvz** [comment]
Looks like this is caused by deno. Please file this issue against the Deno extension
