### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by lirannl** [microsoft/vscode#109199]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.0-dev.20201022

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:104737:161)
    at resolveModuleNamesWorker (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:104966:26)
    at resolveModuleNamesReusingOldState (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:105153:19)
    at processImportedModules (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:106536:35)
    at findSourceFile (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:106313:17)
    at /home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:106142:85
    at getSourceFileFromReferenceWorker (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:106109:34)
    at processSourceFile (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:106142:13)
    at processRootFile (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:105965:13)
    at /home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:104837:60
    at Object.forEach (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:104837:16)
    at synchronizeHostData (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:146147:26)
    at Proxy.getProgram (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:146239:13)
    at InferredProject.Project.updateGraphWorker (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:151101:53)
    at InferredProject.Project.updateGraph (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:151034:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:153158:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:154684:26)
    at /home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:154958:97
    at Object.flatMap (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:154958:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:155976:46)
    at /home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:157849:88
    at IOSession.Session.executeWithRequestId (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:157840:28)
    at IOSession.Session.executeCommand (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:157849:33)
    at IOSession.Session.onMessage (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:157873:35)
    at Interface.<anonymous> (/home/liran/.vscode/extensions/ms-vscode.vscode-typescript-next-4.1.20201022/node_modules/typescript/lib/tsserver.js:160083:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.9.1-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2549)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.63GB (0.37GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 4a5ca466-bb8f-489a-b0b2-902230b830ec|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
vscode-deno|den|2.3.2
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-pull-request-github|Git|0.20.1
discord-vscode|icr|4.0.0
git-graph|mhu|1.26.0
vscode-docker|ms-|1.7.0
python|ms-|2020.9.114305
remote-containers|ms-|0.145.1
cpptools|ms-|1.0.1
vscode-typescript-next|ms-|4.1.20201022
debugger-for-chrome|msj|4.12.11
git-merger|sha|0.4.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically deno?
