### ISSUE TITLE
Web selfhost seems to be broken

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109256]
Run web selfhost (MS Edge) and look at devtools:

```
loader.js:16 Refused to execute script from 'https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/workbench/services/extensions/worker/extensionHostWorker.js' because its MIME type ('') is not executable.
e.load @ VM4 loader.js:16
extensionHostWorkerMain.js:5 DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/workbench/services/extensions/worker/extensionHostWorker.js' failed to load.
    at e.load (https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/loader.js:16:490)
    at e.load (https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/loader.js:13:941)
    at o (https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/loader.js:31:189)
    at s._loadModule (https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/loader.js:31:323)
    at s._resolve (https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/loader.js:32:831)
    at s.defineModule (https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/loader.js:27:127)
    at o (https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/loader.js:34:649)
    at https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js:5:332
    at https://vscodeweb.azureedge.net/insider/7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js:5:432

ERR The Web Worker Extension Host did not start in 10s: Error: The Web Worker Extension Host did not start in 10s
    at http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:4741:904
abstractExtensionService.ts:467 Extension host terminated unexpectedly. Code:  81  Signal:  The Web Worker Extension Host did not start in 10s
_onExtensionHostCrashed @ abstractExtensionService.ts:467
_onExtensionHostCrashed @ extensionService.ts:85
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:459
(anonymous) @ abstractExtensionService.ts:449
fire @ event.ts:587
u @ webWorkerExtensionHost.ts:144
(anonymous) @ webWorkerExtensionHost.ts:155
extensionHostManager.ts:73 Error received from starting extension host
(anonymous) @ extensionHostManager.ts:73
extensionHostManager.ts:74 Error: The Web Worker Extension Host did not start in 10s
    at webWorkerExtensionHost.ts:155
```

**Comment by alexdima** [comment]
I could reproduce once, and then I reloaded the page and all of a sudden everything works fine for me. When the page failed, I could clearly see that the response for a `.js` file from the CDN did not have a content-type. And now, the same request gives back a content-type:

<img width="533" alt="Screen Shot 2020-10-23 at 20 31 43" src="https://user-images.githubusercontent.com/5047891/97041943-98dbe380-1570-11eb-86f8-302dcb4a8566.png">

This is very weird... cc @joaomoreno 

@bpasero Could you try emptying your cache?

**Comment by alexdima** [comment]
Evidence that it started working for me (after clearing the cache?):

![image](https://user-images.githubusercontent.com/5047891/97044196-04738000-1574-11eb-927b-883449ce2f61.png)

**Comment by bpasero** [comment]
Yes, this works again after I reloaded once with "Disable Cache".

**Comment by joaomoreno** [comment]
I've fixed the CDN content type headers. Tomorrow's build will already contain the right values.
