### ISSUE TITLE
Extensions Marketplace broken on Ubuntu behind proxy

### ISSUE THREAD

**Issue by pipja** [Microsoft/vscode#10927]
- VSCode Version: 1.4.0 Linux x64
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1. Setup a fresh copy of VS Code on freshly configured Ubuntu 16.04
2. Click on Extensions button or type "ext install <something>"
3. No results get returned, no error in debug console

Proxy settings are correct on the OS level, Ubuntu software store and everything else works fine.

**Comment by pipja** [comment]
Some more information from a command line try:

code --install-extension ms-vscode.csharp
TypeError: Cannot read property 'firstPage' of undefined
    at /usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:7:19462
    at Object.v [as _notify] (/usr/share/code/resources/app/out/vs/code/node/cli.js:4:28915)
    at Object.J.enter (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:993)
    at r.Class.define._run (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:2314)
    at r.Class.define._error (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:1831)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at emitErr (/usr/share/code/resources/app/node_modules/agent-base/agent.js:63:11)
    at /usr/share/code/resources/app/node_modules/agent-base/agent.js:74:9
    at Socket.onerror (/usr/share/code/resources/app/node_modules/https-proxy-agent/https-proxy-agent.js:125:5)

**Comment by joaomoreno** [comment]
You need to configure the [proxy settings](https://code.visualstudio.com/docs/setup/setup-overview#_proxy-server-support) in VS Code itself.

**Comment by pipja** [comment]
Unfortunately it did not work, the only way I can do it was by installing the vsix package manually

**Comment by joaomoreno** [comment]
Can you show me your configured settings?

**Comment by pietromarrone** [comment]
On Ubuntu 16.10 proxy settings doesn't works, here my config:

`    "http.proxy": "http://my-proxy:5865/",
    "http.proxyStrictSSL": false`
