### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by Nikaple** [microsoft/vscode#109379]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:146885:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:147763:46)
    at /root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/root/.vscode-server/bin/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:44.937Z)
OS version: Windows_NT ia32 6.1.7601
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0050
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0050

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 9.134.30.91|
|OS|Linux x64 3.10.107-1-tlinux2_kvm_guest-0050|
|CPUs|Intel(R) Xeon(R) CPU E5-26xx v4 (16 x 3192)|
|Memory (System)|62.60GB (5.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 9.134.30.91|
|OS|Linux x64 3.10.107-1-tlinux2_kvm_guest-0050|
|CPUs|Intel(R) Xeon(R) CPU E5-26xx v4 (16 x 3192)|
|Memory (System)|62.60GB (5.62GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
bracket-pair-colorizer|Coe|1.0.61
dotenv|mik|1.0.1
vscode-docker|ms-|1.6.0
vscode-language-pack-zh-hans|MS-|1.48.3
remote-ssh-edit-nightly|ms-|2020.10.29700
remote-ssh-nightly|ms-|2020.10.29700
material-icon-theme|PKi|4.3.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|11.0.0
material-theme|zhu|3.8.7
better-toml|bun|0.3.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
console-log|Lui|0.0.8
git-graph|mhu|1.26.0
cpptools|ms-|1.0.1
vetur|oct|0.28.0
vscode-jest|Ort|3.2.0
vscode-sort-json|ric|1.18.1
code-spell-checker|str|1.9.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing as an old TS version plus no steps to reproduce provided
