### ISSUE TITLE
Bug in UI when trying to forward multiple ports

### ISSUE THREAD

**Issue by tvvignesh** [microsoft/vscode#109445]
- VSCode Version:
```
Version: 1.51.0-insider (user setup)
Commit: 16f4a29aa0ac05d3cba222b1f347b7404626c680
Date: 2020-10-26T05:35:22.508Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20201
```

- OS Version: Windows 10 Home Insiders

Steps to Reproduce:

1. When you try to forward multiple ports, the UI behaves strangely and am not able to add a port to the existing list of forwards.

**Screencast which illustrates this problem:**

![vscode-bug](https://user-images.githubusercontent.com/1165845/97275141-9375e600-185b-11eb-839e-94ada4718dc0.gif)

And I get these logs when doing so in my DevTools

```
ERR Failed to construct 'URL': Invalid URL: TypeError: Failed to construct 'URL': Invalid URL
    at Function.compactLongAddress (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7775:236)
    at W.get label [as label] (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7775:101)
    at e.renderTunnel (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7772:483)
    at e.renderElement (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7772:197)
    at v.renderElement (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1162:467)
    at x.renderElement (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1130:837)
    at W.renderElement (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:580:673)
    at E.insertItemInDOM (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:551:539)
    at E._splice (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:547:591)
    at E.splice (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:546:201)
    at file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:34:64
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:34:51)
    at file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:586:688
    at t.EventBufferer.bufferEvents (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:101:214)
    at O.splice (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:586:655)
    at O.splice (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1144:720)
    at t.IndexTreeModel.splice (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:107:116)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:499)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:371)
    at l.setChildren (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1159:12)
    at G.render (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1175:516)
    at G.refreshAndRenderNode (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1172:322)
    at async G._updateChildren (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1169:496)
    at async G.updateChildren (file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1169:184)
    at async file:///C:/Users/vigne/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7778:729
```

**Comment by JacksonKearl** [comment]
Verification steps?

**Comment by tvvignesh** [comment]
Have not faced this issue again since yesterday's insiders release. If I continue to face this, will report back.

**Comment by JacksonKearl** [comment]
Thanks!
