### ISSUE TITLE
Smoketest failing on Windows

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#109517]
Testing: https://github.com/microsoft/vscode/issues/109426

Issue Type: <b>Bug</b>

  1) "after all" hook in "{root}"

  29 passing (3m)
  2 pending
  1 failing

  1) "after all" hook in "{root}":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

internal/fs/utils.js:230
    throw err;
    ^

Error: EPERM: operation not permitted, unlink 'C:\Users\stevencl\AppData\Local\Temp\t23800BngacWgUlY9G\d3\Cache\data_0'
    at Object.unlinkSync (fs.js:1053:3)
    at fixWinEPERMSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:319:28)
    at c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:319:28)
    at c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:319:28)
    at c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:217:5)
    at Function.rimrafSync [as sync] (c:\src\vscode\vscode\test\smoke\node_modules\rimraf\rimraf.js:319:28)
    at process.<anonymous> (c:\src\vscode\vscode\test\smoke\out\main.js:34:35)
    at Object.onceWrapper (events.js:417:26)
    at process.emit (events.js:322:22)
    at process.exit (internal/process/per_thread.js:166:15)
    at c:\src\vscode\vscode\test\smoke\test\index.js:38:31
    at done (c:\src\vscode\vscode\test\smoke\node_modules\mocha\lib\mocha.js:843:7)
    at Runner.<anonymous> (c:\src\vscode\vscode\test\smoke\node_modules\mocha\lib\runner.js:918:5)
    at Runner.emit (events.js:322:22)
    at c:\src\vscode\vscode\test\smoke\node_modules\mocha\lib\runner.js:903:12
    at c:\src\vscode\vscode\test\smoke\node_modules\mocha\lib\runner.js:772:9
    at c:\src\vscode\vscode\test\smoke\node_modules\mocha\lib\runner.js:415:18
    at Hook.done [as callback] (c:\src\vscode\vscode\test\smoke\node_modules\mocha\lib\runnable.js:334:5)
    at Timeout.<anonymous> (c:\src\vscode\vscode\test\smoke\node_modules\mocha\lib\runnable.js:266:10)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Users\\stevencl\\AppData\\Local\\Temp\\t23800BngacWgUlY9G\\d3\\Cache\\data_0'
}
error Command failed with exit code 4294967295.

VS Code version: Code - Insiders 1.51.0-insider (e5c0007ce0e9a3816679cba674d03376c03726e3, 2020-10-27T05:37:14.199Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.17GB free)|
|Process Argv|--crash-reporter-id 3e3a507e-1f96-4eab-b407-73bc311f0b54|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
EditorConfig|Edi|0.15.1
chat|kar|0.35.0
vscode-docker|ms-|1.7.0
python|ms-|2020.9.114305
remote-containers|ms-|0.147.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.51.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.3
js-debug-companion|ms-|1.0.8
vscode-github-issue-notebooks|ms-|0.0.56
vsliveshare|ms-|1.0.3046
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.3073
debugger-for-chrome|msj|4.12.11

</details>

**Comment by alexr00** [comment]
I'm guessing this related to something in 

https://github.com/microsoft/vscode/blob/e8760a5d6c0e09ab692e5b3e414eca018745490f/test/smoke/src/main.ts#L265-L275

since it doesn't look like any test actually failed. @joaomoreno is that `after` hook you?

**Comment by joaomoreno** [comment]
@stevencl Does this happen all the time for you? I run the smoketest on windows all the time and never got this error.

**Comment by stevencl** [comment]
I just ran it again, didn't fail this time. Sorry if this was a false alarm.
