### ISSUE TITLE
TS Server fatal error:  Cannot destructure property `name` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by gferreri** [microsoft/vscode#109790]
We have written the needed data
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.5-pnpify

**Steps to reproduce crash**
1. Open project
2. ???
3. The message appears that the typescript server has crashed 5 times

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at getPackageInformation (/var/www/.pnp.js:43438:34)
    at Object.getPackageInformation (/var/www/.pnp.js:43780:20)
    at getPnpTypeRoots (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:28763:42)
    at getDefaultTypeRoots (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:28779:24)
    at getEffectiveTypeRoots (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:28732:20)
    at Object.getAutomaticTypeDirectiveNames (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:28909:29)
    at Object.createProgram (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:97895:56)
    at synchronizeHostData (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:135345:26)
    at Proxy.getProgram (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:135437:13)
    at InferredProject.Project.updateGraphWorker (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:139913:53)
    at InferredProject.Project.updateGraph (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:139856:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:141832:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:143259:26)
    at /var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:143523:107
    at Object.mapDefined (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:143523:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:144387:46)
    at /var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:146130:88
    at IOSession.Session.executeWithRequestId (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:146121:28)
    at IOSession.Session.executeCommand (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:146130:33)
    at IOSession.Session.onMessage (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:146154:35)
    at IOSession.onMessage (/var/www/.yarn/sdks/typescript/lib/tsserver.js:24:32)
    at Interface.<anonymous> (/var/www/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:147469:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.20241
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (18.39GB free)|
|Process Argv|--crash-reporter-id c095256b-707f-469d-9aed-6af069f653e2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Splash Website - App|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3791)|
|Memory (System)|15.62GB (10.51GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
latte|Kas|0.7.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.7.0
remote-containers|ms-|0.145.1
remote-wsl|ms-|0.50.1
debugger-for-chrome|msj|4.12.11
vim|vsc|1.17.1
vscode-intelephense-client|bme|1.5.4
better-phpunit|cal|1.5.3
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.2
phpunit|ema|4.1.1
php-debug|fel|1.13.0
vscode-mysql|for|0.4.0
vscode-pull-request-github|Git|0.20.1
vscode-graphql|Gra|0.3.10

</details>
 into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Closing as this is an old TS version. Let us know if you still see this with TS 4.0.3+
