### ISSUE TITLE
Under WSL2, intermittent success using cwd to change directory when debugging a nodejs app.

### ISSUE THREAD

**Issue by alanosman** [microsoft/vscode#109815]
- VSCode Version: 1.50.1 and insiders 1.51.0
- OS Version: Windows 10 10.0.19041 
- Using WSL2, Ubuntu 20, Node 12.

My code lives through a mounted folder on my E drive.  It was linked to my home folder using the 'ln' function

Steps to Reproduce:

1. I linked to a folder on my E drive using the command `ln -s /mnt/e/elastc-app/` so I see it from my WSL ubuntu home directory (i.e. `\home\aosman\elastc-app`).

2. This is important to this bug.  I launched VC from WSL and it defaults to my home directory `\home\aosman`. 

3. I load a workspace that was saved in my home directory `\home\aosman\.  This includes the `elastc-app` sub-project folder.

4. In the elastc-app folder, I have my various node files (package.json, etc),  but I add a `test.js` file and put these lines of code in.
```
'use strict';

var express = require('express');
var app = express();

app.get ('/', (req, res) => {
    res.send('Hellow world');
});

app.listen(3600, () => {
    console.log('example port');
});
```

5. I then add my launch.json config
```
        {
            "cwd": "${workspaceFolder}",
            "name": "TEST",
            "type": "node",
            "request": "launch",
            "console": "integratedTerminal",
            "program": "${workspaceFolder}/test.js",
            "protocol": "auto",
            "runtimeArgs": [
                "--preserve-symlinks",
                "--preserve-symlinks-main"
            ],
            "serverReadyAction": {
                "pattern": "listening on port ([0-9]+)",
                "uriFormat": "http://localhost:%s",
                "action": "openExternally"
              }
        },
```

6. When I launch with F5 key, I get this error
```
 /usr/bin/env 'NODE_OPTIONS=--require /home/aosman/.vscode-server-insiders/bin/49696e87c64f478f97909a91d41ff2913df9bf71/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.17898-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/aosman/.nvm/versions/node/v12.19.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-c5c3b71876799cfb"}' /home/aosman/.nvm/versions/node/v12.19.0/bin/node --preserve-symlinks --preserve-symlinks-main ./test.js 
(base) 12:58:38 ~$  /usr/bin/env 'NODE_OPTIONS=--require /home/aosman/.vscode-server-insiders/bin/49696e87c64f478f97909a91d41ff2913df9bf71/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.17898-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/aosman/.nvm/versions/node/v12.19.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-c5c3b71876799cfb"}' /home/aosman/.nvm/versions/node/v12.19.0/bin/node --preserve-symlinks --preserve-symlinks-main ./test.js 
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/home/aosman/test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

7. When I try and launch again, the launch.json `cwd` command seems to work and it launches the app how I expect it.

8. Even if I open visual code from the subdirectory, I experience the same issue. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Can you please do two things?

1. Paste the whole output from the terminal after running step 7
1. See if this reproduces if you remove `console: integratedTerminal`

Thanks!

**Comment by alanosman** [comment]
Ahh yes, it seems to work if I take the `console: integratedTerminal` out, but then of course I do not see what is being output on the console. 

The full error is:
```
Sun Nov  1 23:37:06 EST 2020
Enviornment is development
 /usr/bin/env 'NODE_OPTIONS=--require /home/aosman/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.7264-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/aosman/.nvm/versions/node/v12.19.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-527a9ee3f6f1088b"}' /home/aosman/.nvm/versions/node/v12.19.0/bin/node --preserve-symlinks --preserve-symlinks-main ./test.js 
(base) 11:37:07 ~$  /usr/bin/env 'NODE_OPTIONS=--require /home/aosman/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.7264-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/aosman/.nvm/versions/node/v12.19.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-527a9ee3f6f1088b"}' /home/aosman/.nvm/versions/node/v12.19.0/bin/node --preserve-symlinks --preserve-symlinks-main ./test.js 
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/home/aosman/test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
(base) 11:37:09 ~$ 
```

**Comment by connor4312** [comment]
@weinand this looks like an edge case with the implementation of `runInTerminal`, thus adding you back here (but I can also look at it if you are busy)

**Comment by alanosman** [comment]
Thanks for looking into this guys.
