### ISSUE TITLE
tasks.executeTask() throws "Cannot read property '_id' of undefined"

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#109861]
I'm seeing this error in code that uses `tasks.executeTask()`:

```
 TypeError: Cannot read property '_id' of undefined
      at A.$getTaskExecution (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4571:700)
      at p._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4599:202)
      at p._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4598:901)
      at p._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4597:510)
      at p._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4596:283)
      at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4594:400
      at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
      at fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:454:878)
      at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:459:921)
      at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:456:984
      at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
      at g.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:452:306)
      at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:451:657
      at Socket.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:461:515)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:290:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

I an reproduce it with the following code in a test (in this case, the task type does not exist, but in my actual code it does - the error is the same in both cases):

```ts
import * as vs from "vscode";

describe.only("dart tasks", () => {
	it("dart.task.dartdoc causes documentation to be generated", async () => {
		const taskDef = { type: "foo", command: "foo", args: [] };
		const folder = vs.workspace.workspaceFolders![0]; // my test is run with an open workspace, so this is a valid workspace folder
		const task = new vs.Task(
			taskDef,
			folder,
			"my task",
			"foo",
			undefined,
			undefined
		);
		await vs.tasks.executeTask(task);
	});
});
```

It's possible I'm doing something wrong in the code above, though if that's the case I think there should be a clearer error.

**Comment by DanTup** [comment]
Re-reading the docs, it says:

> Executes a task that is managed by VS Code

I suspect this might mean "a task created by VS Code" and I can't just create my own. What's strange though, is that my tests used to pass and the old code did this too:

https://github.com/Dart-Code/Dart-Code/compare/70cc56d240f33400959a12895b515dd4ff112f66..master#diff-e5e3058f2a55b657239d339d3ae4e5fc3b5f752d858737ef06daa19066780874L150

I'll try to figure out what's different between them.

**Comment by DanTup** [comment]
Seems like this may occur when `execution` is undefined, as `executeTask` does not call `resolveTask` (which is where I'd normally attach this).

**Comment by alexr00** [comment]
To run a task using `executeTask` you must include an `execution`.

**Comment by DanTup** [comment]
@alexr00 thanks - I fixed my issue by manually calling `resolveTask`. I think it would be good to provide a useful error in this case though, a null reference in minified VS Code JS is not trivial to understand.
