### ISSUE TITLE
Error when building for VSCode for source.

### ISSUE THREAD

**Issue by Lucaslah** [microsoft/vscode#109872]
- VSCode Version:
- OS Version: macOS 10.14
- Node Version: v10.0

Steps to Reproduce:

1. Clone VSCode
2. Run `yarn install`
3. Run `yarn web`
4. Error

Does this issue occur when all extensions are disabled?: Yes

When Building VSCode for source I get this error when running  `yarn web`.
Error
```
yarn run v1.22.4
$ node resources/web/code-web.js --port 8877 --disable-extensions
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module '../../build/lib/extensions'
Require stack:
- /Volumes/Lucas's HHD/Files/Projects/vscode/resources/web/code-web.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Volumes/Lucas's HHD/Files/Projects/vscode/resources/web/code-web.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Error When running `./scripts/code.sh`
```
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module '/Volumes/Lucas's HHD/Files/Projects/vscode/build/lib/preLaunch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by zethon** [comment]
Is there no resolution to this? Or are we forced to ask on Slack?

**Comment by Lucaslah** [comment]
I asked it on Slack, I forgot `yarn watch`

**Comment by JeffersonVelozo** [comment]
I get the same issue:

```
 ./scripts/code.sh 
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/jefferson/Documentos/Projetos/vscode/build/lib/preLaunch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Is there no resolution to this yet?
