### ISSUE TITLE
Fake workspace symbol search by sending requests to project of all open documents.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#11026]

**Comment by dbaeumer** [comment]
Was busy adoption TS 2.0.3. This has to wait a little.

**Comment by dbaeumer** [comment]
@waderyan at the end it would make more sense to ask the TS team to implement that. They know all open projects and files.

**Comment by mjbvz** [comment]
TS API request: https://github.com/Microsoft/TypeScript/issues/2530

**Comment by mjbvz** [comment]
Added with a new setting: `typescript.workspaceSymbols.scope`. Valid values are:

- `allOpenProjects` — (default) search all opened projects for symbols. Requires TS 3.9+
- `currentProject` — Only search the current project

To verify, in the VS Code codebase open code from an extension and from core and try the following:

- If you are using TS 3.9, all projects should be searched by default
- On older TS versions, only the current project should be searched.
If using TS 3.9, you can switch to only search the current project by setting: `"typescript.workspaceSymbols.scope": "currentProject"`

**Comment by bpasero** [comment]
Gave it a try but seeing this:

```
RR <semantic> TypeScript Server Error (3.9.0-dev.20200420)
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at normalizeSlashes (tsserver.js:6284:21)
    at Object.normalizePath (tsserver.js:6393:16)
    at Object.toNormalizedPath (tsserver.js:140919:23)
    at ProjectService.getScriptInfo (tsserver.js:145375:67)
    at IOSession.Session.getProjects (tsserver.js:148070:45)
    at IOSession.Session.getFullNavigateToItems (tsserver.js:148584:84)
    at IOSession.Session.getNavigateToItems (tsserver.js:148552:33)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:147376:61)
    at tsserver.js:148931:88
    at IOSession.Session.executeWithRequestId (tsserver.js:148922:28)
    at IOSession.Session.executeCommand (tsserver.js:148931:33)
    at IOSession.Session.onMessage (tsserver.js:148955:35)
    at Interface.<anonymous> (tsserver.js:150271:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.9.0-dev.20200420)
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at normalizeSlashes (tsserver.js:6284:21)
    at Object.normalizePath (tsserver.js:6393:16)
    at Object.toNormalizedPath (tsserver.js:140919:23)
    at ProjectService.getScriptInfo (tsserver.js:145375:67)
    at IOSession.Session.getProjects (tsserver.js:148070:45)
    at IOSession.Session.getFullNavigateToItems (tsserver.js:148584:84)
    at IOSession.Session.getNavigateToItems (tsserver.js:148552:33)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:147376:61)
    at tsserver.js:148931:88
    at IOSession.Session.executeWithRequestId (tsserver.js:148922:28)
    at IOSession.Session.executeCommand (tsserver.js:148931:33)
    at IOSession.Session.onMessage (tsserver.js:148955:35)
    at Interface.<anonymous> (tsserver.js:150271:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript-language-features/out/tsServer/serverError.js:19:16)
	at ProcessBasedTsServer.dispatchResponse (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript-language-features/out/tsServer/server.js:143:70)
	at ProcessBasedTsServer.dispatchMessage (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript-language-features/out/tsServer/server.js:85:30)
	at /Users/bpasero/Development/Microsoft/monaco/extensions/typescript-language-features/out/tsServer/server.js:58:45
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:457:42)
	at Reader.onLengthData (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript-language-features/out/utils/wireProtocol.js:112:30)
	at Socket.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript-language-features/out/utils/wireProtocol.js:91:42)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
You need to be on the latest TS nightly for this. The one we have in our workspace isn't recent enough. I'll should pick up the next TS build before the insiders build with this change goes out

**Comment by bpasero** [comment]
Got it 👍
