### ISSUE TITLE
Cannot read property 'isWordWrapMinified' of undefined

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#110235]
1. Latest out of source
2. Recent workspace list > pick a workspace > VS Code reloads with that workspace but there is an error in the dev tools console

```
  ERR Cannot read property 'isWordWrapMinified' of undefined: TypeError: Cannot read property 'isWordWrapMinified' of undefined
    at new ToggleWordWrapController (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/codeEditor/browser/toggleWordWrap.js:144:109)
    at InstantiationService._createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService.createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:59:31)
    at new CodeEditorWidget (file:///Users/isidor/Development/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:149:69)
    at InstantiationService._createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService.createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:59:31)
    at NativeTextFileEditor.createEditorControl (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:107:46)
    at NativeTextFileEditor.createEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:91:54)
    at NativeTextFileEditor.create (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorPane.js:49:18)
    at EditorControl.doCreateEditorPane (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:82:28)
    at EditorControl.doShowEditorPane (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:59:37)
    at EditorControl.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:46:37)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:735:65
    at EditorGroupView.doShowEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:747:19)
    at EditorGroupView.restoreEditors (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:326:24)
    at new EditorGroupView (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:113:39)
    at InstantiationService._createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService.createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:59:31)
    at Function.createFromSerialized (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:122:41)
    at EditorPart.doCreateGroupView (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:371:63)
    at Object.fromJSON (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:753:42)
    at GridView._deserializeNode (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/gridview.js:831:52)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/gridview.js:824:36
    at Array.map (<anonymous>)
    at GridView._deserializeNode (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/gridview.js:822:53)
    at GridView._deserialize (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/gridview.js:816:30)
    at Function.deserialize (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/gridview.js:812:20)
    at Function.deserialize (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/grid.js:423:50)
    at EditorPart.doCreateGridControlWithState (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:746:56)
    at EditorPart.doCreateGridControlWithPreviousState (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:719:26)
    at EditorPart.doCreateGridControl (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:692:38)
    at EditorPart.createContentArea (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:600:18)
    at EditorPart.create (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/part.js:43:37)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:234:34
    at Array.forEach (<anonymous>)
    at Workbench.renderWorkbench (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:232:15)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:76:26
    at InstantiationService.invokeFunction (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at Workbench.startup (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:61:38)
    at DesktopMain.open (file:///Users/isidor/Development/vscode/out/vs/workbench/electron-browser/desktop.main.js:61:52)
```

**Comment by alexdima** [comment]
I think you just need to restart gulp sometimes when pulling, for example when we change the editor options. The problem is that we use a const enum for editor options and that our gulp-tsb does not re-emit JS files when a const enum is changed.

**Comment by isidorn** [comment]
Yes, that must have been the case, since I did not see this afterwards. Thanks
