### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by petarvujovic98** [microsoft/vscode#110260]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1. Open js file
2. Attempt to use code completion
3. After one code completion use, server crashes

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`/home/petar/.config/Code - OSS/logs/20201108T203721/exthost1/vscode.typescript-language-features/tsserver-log-6rJAFb/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at Object.releaseDocumentWithKey (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:117875:35)
    at Object.onReleaseOldSourceFile (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143373:34)
    at Object.createProgram (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:102833:26)
    at synchronizeHostData (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143341:26)
    at Proxy.getProgram (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:143433:13)
    at InferredProject.Project.updateGraphWorker (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:148278:53)
    at InferredProject.Project.updateGraph (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:148211:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:150293:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:151813:26)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:152070:97
    at Object.flatMap (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:153089:46)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - OSS 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-15T10:42:48.064Z)
OS version: Linux x64 5.8.18-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3469)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.40GB (1.93GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
pascal|ale|9.1.0
pascal-formatter|ale|2.4.0
pug|ama|1.0.1
vscode-apollo|apo|1.17.0
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
vscode-deno|den|2.3.3
es7-react-js-snippets|dsz|3.0.0
vscode-rust-syntax|dun|0.0.32
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
RunOnSave|eme|0.2.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
lex-flex-yacc-bison|fau|0.0.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
code-runner|for|0.11.1
lintlens|ghm|3.0.0
go|gol|0.18.1
icon-fonts|idl|2.4.0
latex-workshop|Jam|8.13.2
docthis|joe|0.7.1
mips|kda|0.0.5
kite|kit|0.134.0
graphql-for-vscode|kum|1.15.3
node-module-intellisense|lei|1.5.0
lex|lun|0.1.0
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.9.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
vscode-postgresql|ms-|0.3.0
python|ms-|2020.9.112786
cpptools|ms-|1.0.1
typescript-javascript-grammar|ms-|0.0.53
debugger-for-chrome|msj|4.12.11
gradle-language|nac|0.2.3
vscode-spring-boot|Piv|1.23.0
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.0
java|red|0.70.0
vscode-gradle|ric|3.5.2
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
autoimport|ste|1.5.3
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-spring-initializr|vsc|0.5.0
vscode-icons|vsc|11.0.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.3.0
material-theme|zhu|3.9.3
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically the deno extension

**Comment by petarvujovic98** [comment]
No it does not, when the deno extension is disabled globally it runs fine

**Comment by mjbvz** [comment]
Thanks for checking. Please file this against the deno extension so they can take a look
