### ISSUE TITLE
Unable to SSH to remote server after 1.51.0 update

### ISSUE THREAD

**Issue by pp5311006** [microsoft/vscode#110360]
- VSCode Version: 1.51.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Install Remote SSH or Remote SSH Nightly
2. Connect to a Linux host machine

The issue does NOT reoccur on a VS Code Insider version.

```
Logs:
[09:20:52.982] Log Level: 2
[09:20:52.991] remote-ssh-nightly@2020.11.5281
[09:20:52.991] win32 x64
[09:20:52.993] SSH Resolver called for "ssh-remote***********", attempt 1
[09:20:52.993] SSH Resolver called for host: *****************
[09:20:52.993] Setting up SSH remote "*****************"
[09:20:53.020] Using commit id "fcac248b077b55bae4ba5bab613fd6e9156c2f0c" and quality "stable" for server
[09:20:53.021] Install and start server if needed
[09:20:53.025] Checking ssh with "ssh -V"
[09:20:53.030] Got error from ssh: spawn ssh ENOENT
[09:20:53.031] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[09:20:53.034] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[09:20:53.034] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[09:20:54.232] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[09:20:54.253] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 55642 ***************** bash
[09:20:54.259] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:20:58.030] ssh is not exiting, continuing
[09:20:58.034] ssh is not exiting, continuing
[09:23:56.266] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\eepgnao\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.11.5281\out\extension.js:1:94553)
	at Timeout._onTimeout (c:\Users\eepgnao\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.11.5281\out\extension.js:127:105913)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[09:23:56.269] ------
```

Does this issue occur when all extensions are disabled?: N/A

**Comment by roblourens** [comment]
What does the log say if you try insiders? Looks like we invoked ssh and it didn't respond.

**Comment by pp5311006** [comment]
> What does the log say if you try insiders? Looks like we invoked ssh and it didn't respond.

[10:22:56.556] Log Level: 2
[10:22:56.565] remote-ssh@0.56.0
[10:22:56.565] win32 x64
[10:22:56.566] SSH Resolver called for "***", attempt 1
[10:22:56.566] SSH Resolver called for host: *************
[10:22:56.566] Setting up SSH remote "*************"
[10:22:56.613] Using commit id "65f805d98e798b979901b74d4c8810c05455b792" and quality "insider" for server
[10:22:56.615] Install and start server if needed
[10:22:56.619] Checking ssh with "ssh -V"
[10:22:56.625] Got error from ssh: spawn ssh ENOENT
[10:22:56.625] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:22:56.627] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[10:22:56.627] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[10:22:57.848] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[10:22:57.877] Using SSH config file "C:\Users\eepgnao\.ssh\config"
[10:22:57.877] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 56916 -F "C:\Users\eepgnao\.ssh\config" ************ bash
[10:22:57.882] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:22:58.331] > 
[10:22:58.331] Got some output, clearing connection timeout
[10:23:00.182] > 
Internal SSH Message
> 
[10:23:00.364] > Enter Windows password:
[10:23:01.624] ssh is not exiting, continuing
[10:23:01.626] ssh is not exiting, continuing

[10:25:39.273] > d826cafd5613: running
> 
[10:25:39.771] > Acquiring lock on /home/eepgnao/.vscode-server-insiders/bin/65f805d98e798b979901b74d4c8810c05455b792/vscode-remote-lock.eepgnao.65f805d98e798b979901b74d4c8810
> c05455b792
> Found existing installation at /home/eepgnao/.vscode-server-insiders/bin/65f805d98e798b979901b74d4c8810c05455b792...
> Checking /home/eepgnao/.vscode-server-insiders/.65f805d98e798b979901b74d4c8810c05455b792.log and /home/eepgnao/.vscode-server-insiders/.65f805d98e798b979901b7
> 4d4c8810c05455b792.pid for a running server
> Looking for server with pid: 19878
> 
[10:25:39.790] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[10:25:39.820] > Checking server status on port 37779 with wget
> d826cafd5613: start
> sshAuthSock====
> listeningOn==37779==
> osReleaseId==ubuntu==
> 
[10:25:39.966] > arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/7292887==
> platform==linux==
> d826cafd5613: end
> 
[10:25:39.966] Received install output: 
sshAuthSock====
listeningOn==37779==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/7292887==
platform==linux==

[10:25:39.967] Remote server is listening on 37779
[10:25:39.967] Parsed server configuration: {"remoteListeningOn":{"port":37779},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/7292887","platform":"linux"}
[10:25:39.969] Starting forwarding server. localPort 57033 -> socksPort 57029 -> remotePort 37779
[10:25:39.970] Forwarding server listening on 57033
[10:25:39.970] Waiting for ssh tunnel to be ready
[10:25:39.972] Tunneled 37779 to local port 57033
[10:25:39.972] Resolved "ssh-remote*************" to "127.0.0.1:57033"
[10:25:39.973] [Forwarding server 57033] Got connection 0
[10:25:39.990] ------




[10:25:40.003] [Forwarding server 57033] Got connection 1
[10:25:40.003] [Forwarding server 57033] Got connection 2

**Comment by chozandrias76** [comment]
I am also getting this issue:
```[09:41:42.892] "install" terminal received data: "[?25lPassword:[?25h"
[09:41:42.892] Showing password prompt
[09:41:47.810] Got password response
[09:41:47.811] "install" wrote data to terminal: "************"
[09:41:47.823] "install" terminal received data: "[?25l
[?25h"
[09:41:48.213] "install" terminal received data: "[?25l20e9e2c4e786: running
[?25h"
[09:41:48.234] "install" terminal received data: "[?25lAcquiring lock on /Users/crashoverride/.vscode-server/bin/fcac248b077b55bae4ba5b
ab613fd6e9156c2f0c/vscode-remote-lock.crashoverride.fcac248b077b55bae4ba5bab613f
d6e9156c2f0c[68X[68C
[?25h[?25l\ln /Users/crashoverride/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c
2f0c/vscode-remote-lock.crashoverride.fcac248b077b55bae4ba5bab613fd6e9156c2f0c.t
arget /Users/crashoverride/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e915
6c2f0c/vscode-remote-lock.crashoverride.fcac248b077b55bae4ba5bab613fd6e9156c2f0c
[80X[80C
ln: /Users/crashoverride/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c
2f0c/vscode-remote-lock.crashoverride.fcac248b077b55bae4ba5bab613fd6e9156c2f0c: 
File exists[69X[69C
Installation already in progress...[45X[45C
20e9e2c4e786: start[61X[61C
exitCode==24==[66X[66C
sshAuthSock====[65X[65C
listeningOn====[65X[65C
osReleaseId==Darwin==[59X[59C
arch==x86_64==[66X[66C
webUiAccessToken====[60X[60C
tmpDir==/tmp==[66X[66C
platform==macOS==[63X[63C
20e9e2c4e786: end[63X[63C[24;18H[?25h"
[09:41:48.234] Received install output: 
exitCode==24==
sshAuthSock====
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
webUiAccessToken====
tmpDir==/tmp==
platform==macOS==

[09:41:48.235] Server installation process already in progress - waiting and retrying
[09:41:48.242] "install" terminal received data: "[?25l
[80X[80C
[?25h"
[09:41:48.517] "install" terminal command done
[09:41:48.517] Install terminal quit with output: [80X[80C
[?25h
[09:41:49.240] Running script with connection command: ssh -T -D 50954 mac bash
[09:41:49.241] Terminal shell path: C:\Windows\System32\cmd.exe
[09:41:49.273] "install" terminal received data: "[2J[?25l[m[H```

**Comment by roblourens** [comment]
@pp5311006 that time it looked like it succeeded, did it?

**Comment by pp5311006** [comment]
> @pp5311006 that time it looked like it succeeded, did it?

Yes it did, that's on the insider's version though. The SSH connection is always successful on the insider's version. 

So I tried to go back to the standard version after successfully connected to my remote machine using insider's build, but it still doesn't work.

**Comment by roblourens** [comment]
Do you have your ssh config file set in a setting in insiders? That's one difference in the log.

**Comment by pp5311006** [comment]
> Do you have your ssh config file set in a setting in insiders? That's one difference in the log.

Here is a new log from a few minutes ago using insider's build. It does have a config file set.
The reason that the previous insider'a build log didn't have config file set is probably because of I had not performed settings sync yet.

[08:15:48.523] Log Level: 2
[08:15:48.530] remote-ssh@0.56.0
[08:15:48.530] win32 x64
[08:15:48.532] SSH Resolver called for "xxxxxxxx", attempt 1
[08:15:48.532] SSH Resolver called for host: xxxxxxxx
[08:15:48.532] Setting up SSH remote "xxxxxxx"
[08:15:48.579] Using commit id "65f805d98e798b979901b74d4c8810c05455b792" and quality "insider" for server
[08:15:48.582] Install and start server if needed
[08:15:48.585] Checking ssh with "ssh -V"
[08:15:48.589] Got error from ssh: spawn ssh ENOENT
[08:15:48.589] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[08:15:48.590] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[08:15:48.590] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[08:15:48.749] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[08:15:48.772] Using SSH config file "C:\Users\eepgnao\.ssh\config"
[08:15:48.772] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 54755 -F "C:\Users\eepgnao\.ssh\config" xxxxxxxx bash
[08:15:48.776] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:15:49.217] > 
[08:15:49.217] Got some output, clearing connection timeout
[08:15:50.833] >
> 
> IF YOU ARE NOT AN AUTHORIZED USER, PLEASE EXIT IMMEDIATELY
> 
> You are connected to: xxxxxxxxxx
> 
[08:15:51.107] > Enter Windows password:
[08:15:53.589] ssh is not exiting, continuing
[08:15:53.599] ssh is not exiting, continuing
[08:15:55.498] > 
> 
[08:15:57.434] > 0c33e1cda6a8: running
> 
[08:15:57.466] > Acquiring lock on /home/eepgnao/.vscode-server-insiders/bin/65f805d98e798b979901b74d4c8810c05455b792/vscode-remote-lock.eepgnao.65f805d98e798b979901b74d4c8810c05
> 455b792
> 
[08:15:57.561] > Found existing installation at /home/eepgnao/.vscode-server-insiders/bin/65f805d98e798b979901b74d4c8810c05455b792...
> Checking /home/eepgnao/.vscode-server-insiders/.65f805d98e798b979901b74d4c8810c05455b792.log and /home/eepgnao/.vscode-server-insiders/.65f805d98e798b979901b74d4
> c8810c05455b792.pid for a running server
> Looking for server with pid: 11211
> 
[08:15:57.568] > Starting server with command... /home/eepgnao/.vscode-server-insiders/bin/65f805d98e798b979901b74d4c8810c05455b792/server.sh --host=127.0.0.1 --enable-remote-aut
> o-shutdown  --port=0 &> "/home/eepgnao/.vscode-server-insiders/.65f805d98e798b979901b74d4c8810c05455b792.log" < /dev/null
> printenv:
>     ARC_RELEASE=0
>     SSH_CONNECTION=100.98.221.221 54758 10.120.197.179 22
>     LANG=en_US
>     LMOD_SYSTEM_NAME=UBUNTU18-x86_64
>     LICENSE_SITE=seligic
>     LOADEDMODULES_modshare=isit_modules:1
>     _system_path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
>     XDG_SESSION_ID=797
>     USER=eepgnao
>     LC_COLLATE=C
>     GOPATH=/home/eepgnao/go
>     ISITRELEASE=latest
>     PWD=/home/eepgnao
>     HOME=/home/eepgnao
>     SSH_CLIENT=xxx.xx.xxx.xx 54758 22
>     _LMFILES__modshare=/home/eepgnao/.afs/0/imodules/isit_modules:1
>     ARC_OS_DETECT=UBUNTU18.04-x86_64
>     MAGIC_PATH=/usr/atria/config/magic
>     ARC_ENV=seligic
>     SITE=seligic
>     LOADEDMODULES=isit_modules
>     MAIL=/var/mail/eepgnao
>     SHELL=/bin/bash
>     LC_MESSAGES=C
>     LS_OPTIONS=--color=auto
>     SHLVL=2
>     LANGUAGE=en_US:
>     CCHOME=/usr/atria
>     MANPATH=/usr/local/man:/usr/local/share/man:/usr/share/man:/opt/quest/man:/app/modules/0/man
>     VSCODE_AGENT_FOLDER=/home/eepgnao/.vscode-server-insiders
>     MODULEPATH=/app/modules/0/modulefiles:/env/seligic/modules:/home/eepgnao/.afs/0/imodules:/env/common/modules
>     LOGNAME=eepgnao
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/7292887/bus
>     XDG_RUNTIME_DIR=/run/user/7292887
>     PATH=/usr/local/bin/:/env/seligic/bin:/home/eepgnao/.afs/0/ibin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/sbin:/sbin:/app/
> arc/0/bin
>     _LMFILES_=/home/eepgnao/.afs/0/imodules/isit_modules
>     PROJ_NR=0
>     LC_TIME=C
>     _=/usr/bin/printenv
> Spawned remote server: 2204
> 
[08:15:57.627] > Waiting for server log...
> 
[08:15:58.134] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 0c33e1cda6a8: start
> sshAuthSock====
> listeningOn==39159==
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/7292887==
> platform==linux==
> 0c33e1cda6a8: end
> 
[08:15:58.134] Received install output: 
sshAuthSock====
listeningOn==39159==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/7292887==
platform==linux==

[08:15:58.135] Remote server is listening on 39159
[08:15:58.135] Parsed server configuration: {"remoteListeningOn":{"port":39159},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/7292887","platform":"linux"}
[08:15:58.140] Starting forwarding server. localPort 54769 -> socksPort 54755 -> remotePort 39159
[08:15:58.143] Forwarding server listening on 54769
[08:15:58.143] Waiting for ssh tunnel to be ready
[08:15:58.146] Tunneled 39159 to local port 54769
[08:15:58.146] Resolved "ssh-remote+xxxxxx" to "127.0.0.1:54769"
[08:15:58.147] [Forwarding server 54769] Got connection 0
[08:15:58.172] ------




[08:15:58.212] [Forwarding server 54769] Got connection 1
[08:15:58.213] [Forwarding server 54769] Got connection 2
[08:18:58.163] > 
> arc/0/bin
>     _LMFILES_=/home/eepgnao/.afs/0/imodules/isit_modules
>     PROJ_NR=0
>     LC_TIME=C
>     _=/usr/bin/printenv
> Spawned remote server: 2204
> Waiting for server log...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 0c33e1cda6a8: start
> sshAuthSock====
> listeningOn==39159==
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/7292887==
> platform==linux==
> 0c33e1cda6a8: end

**Comment by roblourens** [comment]
The insider version always had it, the original stable one did not. I assume that's a workaround for you. Or you can just use insiders.

**Comment by pp5311006** [comment]
> The insider version always had it, the original stable one did not. I assume that's a workaround for you. Or you can just use insiders.

I wonder if this issue will be fixed for stable version. I'd prefer using stable version over insider version but now it seems impossible. 
Or at least find out how to fix it for the stable version from user's side.

**Comment by roblourens** [comment]
Check the ssh settings.

**Comment by pp5311006** [comment]
> Check the ssh settings.
Hi @roblourens 
I still haven't been able to figure out what the problem is. 
Seems like there is something wrong with `bash` at the end of the SSH command.
Here is the log when I tried to connect using the SSH command from VS code output via a different SSH tool.
I would really appreciate it if you can provide some feedback on what the problem might be. 

```
Enter Windows password:
debug3: send packet: type 61
debug3: receive packet: type 60
debug2: input_userauth_info_req
debug2: input_userauth_info_req: num_prompts 0
debug3: send packet: type 61
debug3: receive packet: type 52
debug1: Authentication succeeded (keyboard-interactive).
Authenticated to seliiuvd05314.seli.gic.ericsson.se ([10.120.197.179]:22).
debug1: Local connections to LOCALHOST:65174 forwarded to remote address socks:0
debug3: channel_setup_fwd_listener_tcpip: type 2 wildcard 0 addr NULL
debug3: sock_set_v6only: set socket 4 IPV6_V6ONLY
debug1: Local forwarding listening on ::1 port 65174.
debug2: fd 4 setting O_NONBLOCK
debug3: fd 4 is O_NONBLOCK
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 65174.
debug2: fd 5 setting O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug3: ssh_session2_open: channel_new: 2
debug2: channel 2: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 4
debug1: Remote: Ignored authorized keys: bad ownership or modes for directory /home/eepgnao
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x20
debug2: client_session2_setup: id 2
debug1: Sending command: bash
debug2: channel 2: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 2: callback done
debug2: channel 2: open confirm rwindow 0 rmax 32768
debug2: channel 2: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 2
debug2: exec request accepted on channel 2

```

**Comment by roblourens** [comment]
It seems like this is working in insiders for you already. Just make sure you have the same settings set between insiders and stable. There should be no important difference in vscode between the two.
