### ISSUE TITLE
Error: Timeout: get element '.panel .markers-panel' after 20 seconds

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110388]
```
 1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Language Features
           verifies problems view:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

  2) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Language Features
           verifies settings:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

  3) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Statusbar
           verifies that 'Problems View' appears when clicking on 'Problems' status element:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=93716&view=logs&j=c7f62bfb-739d-57a1-95c8-4d7248f0a391&t=e4c6ba37-e76f-5c17-2407-f81465f58302&l=98

**Comment by sandy081** [comment]
/duplicate

This is real bug that smoke tests detected. https://github.com/microsoft/vscode/issues/110410.

**Comment by bpasero** [comment]
:) that doesn't happen often
