### ISSUE TITLE
Notebook editor error

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#110479]
* open a notebook which has GIT changes
* open the diff editor for the notebook
* close the initial notebook editor
* in the diff editor type inside a code cell 
* 🐛 an error happens, suggesting that the notebook editor isn't disposed properly

maybe related to https://github.com/microsoft/vscode/issues/109594

```
 ERR Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at ListView.element (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listView.js:412:38)
    at NotebookCellList._revealRangeInternalAsync (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:602:39)
    at NotebookCellList._revealLineInViewAsync (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:630:25)
    at NotebookCellList.revealElementLineInViewAsync (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:485:29)
    at NotebookEditorWidget.revealLineInViewAsync (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:968:78)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/codeCell.js:287:41
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:456:38)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1099:58
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:456:38)
    at ViewModelEventDispatcher._emitOugoingEvents (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelEventDispatcher.js:45:31)
    at ViewModelEventDispatcher.endEmitViewEvents (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelEventDispatcher.js:84:18)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:255:43
    at file:///Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:213:56
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:456:38)
    at DidChangeContentEmitter.endDeferredEmit (file:///Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:2682:39)
    at TextModel.pushEditOperations (file:///Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:938:36)
    at Function._innerExecuteCommands (file:///Users/jrieken/Code/vscode/out/vs/editor/common/controller/cursor.js:599:45)
    at Function.executeCommands (file:///Users/jrieken/Code/vscode/out/vs/editor/common/controller/cursor.js:566:33)
    at Cursor._executeEditOperation (file:///Users/jrieken/Code/vscode/out/vs/editor/common/controller/cursor.js:344:44)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/common/controller/cursor.js:514:30
    at Cursor._executeEdit (file:///Users/jrieken/Code/vscode/out/vs/editor/common/controller/cursor.js:475:17)
    at Cursor.type (file:///Users/jrieken/Code/vscode/out/vs/editor/common/controller/cursor.js:504:18)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:727:69
    at ViewModel._withViewEventsCollector (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:791:17)
    at ViewModel._executeCursorEdit (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:713:18)
    at ViewModel.type (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:727:18)
    at CodeEditorWidget._type (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:698:39)
    at CodeEditorWidget.trigger (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:648:26)
    at EditorHandlerCommand.runCommand (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/coreCommands.js:1533:20)
    at handler (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/editorExtensions.js:51:55)
    at idOrCommand.handler (file:///Users/jrieken/Code/vscode/out/vs/platform/commands/common/commands.js:35:28)
    at InstantiationService.invokeFunction (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at CommandService._tryExecuteCommand (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/commands/common/commandService.js:74:59)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/services/commands/common/commandService.js:64:47
```

**Comment by jrieken** [comment]
@joaomoreno fixed this with 37103467dcf914b6a5c6c30331f307e2d8de3fa1
