### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#110435]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.2.0-dev.20201104

**Steps to reproduce crash**
1. Open VS Code
2. Check out this PR https://github.com/microsoft/vscode/pull/108401
3. It crashed

**TS Server Log**
[tsserver.log](https://github.com/microsoft/vscode/files/5519121/tsserver.log)

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:155575:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:156608:46)
    at /Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158481:88
    at IOSession.Session.executeWithRequestId (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158472:28)
    at IOSession.Session.executeCommand (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158481:33)
    at IOSession.Session.onMessage (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158505:35)
    at Interface.<anonymous> (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:160715:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.52.0-insider (65f805d98e798b979901b74d4c8810c05455b792, 2020-11-10T09:49:58.382Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.0.0-1027-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|-psn_0_13774114 --crash-reporter-id a2c1d522-e9f0-4e3f-b78a-9253f1c2d2d3|
|Screen Reader|no|
|VM|17%|

|Item|Value|
|---|---|
|Remote|SSH: robfast|
|OS|Linux x64 5.0.0-1027-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (3.95GB free)|
|VM|0%|

**Comment by mjbvz** [comment]
The bug seems to be related to how we normalize paths but I'm not able to tigger it. The specific steps should be something like:

1. Open a file in a pr (this has file path ` ^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts`)
1. Then open that same file in the explorer in a way that closes the original file (maybe using preview mode?)
1. Our resource map mistakenly treats these files as the same file
