### ISSUE TITLE
TypeError: o.provideFileDecoration is not a function

### ISSUE THREAD

**Issue by Morriz** [microsoft/vscode#110569]
I see this error after startup which seems unrelated to extensions:
```
[2020-11-13 13:39:13.301] [exthost] [error] TypeError: o.provideFileDecoration is not a function
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:711:170
    at Array.map (<anonymous>)
    at e.$provideDecorations (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:711:106)
    at g._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:926)
    at g._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:618)
    at g._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:201)
    at g._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:874:6)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:872:136
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1066:179
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:629)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:708
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:989)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:341
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:276)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

I am running node 14, but vscode brings it's own version, right?

- VSCode Version: 1.51.1
- OS Version: OSX

Steps to Reproduce:

1. Open vscode an navigate to `Output` tab and select `Log (Extension Host)`
2. see the error

Does this issue occur when all extensions are disabled?: No

**Comment by Morriz** [comment]
nvermind, it was the `node` extension, duh! Will take it there...

**Comment by Morriz** [comment]
premature closure as the node plugin is built in, reopening...

**Comment by jrieken** [comment]
What `node` extension would that be?

**Comment by Morriz** [comment]
I was referring to ...workbench/services/extensions/**node**/extensionHostProcess.js...

**Comment by jrieken** [comment]
Ok, this error happens when we call into an extension - in particular case an extension that uses a proposed API. Are you using LiveShare by any chance? Can you retry with that disabled?

**Comment by jrieken** [comment]
ping @Morriz 

ping @lostintangent - looks like LiveShare uses a proposed API that has changed

**Comment by Morriz** [comment]
> Ok, this error happens when we call into an extension - in particular case an extension that uses a proposed API. Are you using LiveShare by any chance? Can you retry with that disabled?

No, I don't use that (never heard of it either)

**Comment by jrieken** [comment]
This error is coming from an extension and to proceed the list of extensions you have installed is needed

**Comment by Morriz** [comment]
Oi, how can I get that easily?

**Comment by jrieken** [comment]
pfff.... that's a lot and there is no overlap with the list I have. Are you willing to trying something new? Usually, I'd asking you now to disable extensions one by one to see which is causing this but that is quite painful. In latest Insiders you have "extension bisect" which make this much faster. What you need to do

* install insiders (https://code.visualstudio.com/insiders/)
* install the same set of extensions (which is easy via settings sync when both (stable and insiders) share the data)
* F1 > Start Extension Bisect
