### ISSUE TITLE
compilation error on 1.50.1

### ISSUE THREAD

**Issue by linqing2004** [microsoft/vscode#110605]
- VSCode Version: 1.50.1
- OS Version:  Oracle Linux  7,  4.1.12-61.1.18.el7uek.x86_64

Steps to Reproduce:

$ gulp --max_old_space_size=8192 vscode-linux-x64
[03:34:43] Node flags detected: --max_old_space_size=8192
[03:34:43] Respawned to PID: 13596
[03:34:49] Using gulpfile ~/rpmbuild/BUILD/vscode-1.50.1/gulpfile.js
[03:34:49] Starting 'vscode-linux-x64'...
[03:34:49] Starting clean-out-build ...
[03:34:50] Finished clean-out-build after 589 ms
[03:34:50] Starting compile-build ...
[03:34:53] Starting compilation...
[03:38:02] Error: /home/qinlin/rpmbuild/BUILD/vscode-1.50.1/src/vs/workbench/services/extensions/node/proxyResolver.ts(400,3): Type '(details: SecureContextOptions) => SecureContext' is not assignable to type '(options?: SecureContextOptions | undefined) => SecureContext'.
  Types of parameters 'details' and 'options' are incompatible.
    Type 'SecureContextOptions | undefined' is not assignable to type 'SecureContextOptions'.
      Type 'undefined' is not assignable to type 'SecureContextOptions'.
[03:38:02] Finished compilation with 1 errors after 188945 ms
[03:38:02] Error: /home/qinlin/rpmbuild/BUILD/vscode-1.50.1/src/vs/workbench/services/extensions/node/proxyResolver.ts(400,3): Type '(details: SecureContextOptions) => SecureContext' is not assignable to type '(options?: SecureContextOptions | undefined) => SecureContext'.
  Types of parameters 'details' and 'options' are incompatible.
    Type 'SecureContextOptions | undefined' is not assignable to type 'SecureContextOptions'.
      Type 'undefined' is not assignable to type 'SecureContextOptions'.
[03:38:03] Finished compilation with 1 errors after 189334 ms
[03:38:03] 'vscode-linux-x64' errored after 3.22 min
[03:38:03] Error: Found 1 errors
    at Stream.<anonymous> (/home/qinlin/rpmbuild/BUILD/vscode-1.50.1/build/lib/reporter.js:75:29)
    at _end (/home/qinlin/rpmbuild/BUILD/vscode-1.50.1/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/qinlin/rpmbuild/BUILD/vscode-1.50.1/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:203:15)
    at Stream.EventEmitter.emit (domain.js:466:23)
    at drain (/home/qinlin/rpmbuild/BUILD/vscode-1.50.1/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/home/qinlin/rpmbuild/BUILD/vscode-1.50.1/node_modules/through/index.js:45:5)
    at Stream.end (/home/qinlin/rpmbuild/BUILD/vscode-1.50.1/node_modules/through/index.js:15:35)
    at _end (/home/qinlin/rpmbuild/BUILD/vscode-1.50.1/node_modules/through/index.js:65:9)
error Command failed with exit code 1.

**Comment by joaomoreno** [comment]
> OS Version: Oracle Linux 7, 4.1.12-61.1.18.el7uek.x86_64

We can't provide support for non supported platforms. Sorry about that.
