### ISSUE TITLE
git sync creates many icons in status bar

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#110718]
- VSCode Version: 1.52.0-insider 46ff33b6b6ec2db5906f52c236c7f712988516ff x64
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Click on the "git sync" icon in the status bar
2. It duplicates the branch name in the status bar

![message](https://user-images.githubusercontent.com/23744935/99243476-0510d680-2801-11eb-82de-97d5721cbc92.png)

```
ERR Cannot read property 'tooltip' of null: TypeError: Cannot read property 'tooltip' of null
    at f.renderStatusBar (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6112:694)
    at file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6112:355
    at c.fire (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:99:423)
    at p.$updateSourceControl (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4456:934)
    at m.$updateSourceControl (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4459:300)
    at p._doInvokeHandler (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4491:1013)
    at p._invokeHandler (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4491:705)
    at p._receiveRequest (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4490:344)
    at p._receiveOneMessage (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4489:156)
    at file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4487:213
    at c.fire (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:99:423)
    at fire (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:480:878)
    at t.PersistentProtocol._receiveMessage (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:485:921)
    at file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:482:984
    at c.fire (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:99:423)
    at g.acceptChunk (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:478:306)
    at file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:477:657
    at Socket.t (file:///snap/code-insiders/575/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:487:567)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
@SimonSiefke, are you still able to reproduce this with the latest version of VS Code?
