### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by dramufhi** [microsoft/vscode#110735]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure.
    at ProjectService.setDocument (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149781:37)
    at acquireOrUpdateDocument (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117839:35)
    at Object.acquireDocumentWithKey (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117810:20)
    at getOrCreateSourceFileByPath (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143424:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143376:24)
    at findSourceFile (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:104161:29)
    at c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:104038:85
    at getSourceFileFromReferenceWorker (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:104005:34)
    at processSourceFile (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:104038:13)
    at processRootFile (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103861:13)
    at c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102785:60
    at Object.forEach (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at Object.createProgram (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102785:16)
    at synchronizeHostData (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143341:26)
    at Proxy.getProgram (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143433:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148278:53)
    at InferredProject.Project.updateGraph (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148211:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150293:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151813:26)
    at c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152070:97
    at Object.flatMap (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153089:46)
    at c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:28)
    at IOSession.Session.executeCommand (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:33)
    at IOSession.Session.onMessage (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154986:35)
    at Interface.<anonymous> (c:\Users\dakalo.ramufhi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.39GB free)|
|Process Argv|--crash-reporter-id de8e7cf3-0d02-4157-b577-d8ba2291feb2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.1
gitlens|eam|11.0.1
tslint|eg2|1.0.44
prettier-vscode|esb|5.7.2
vscode-firefox-debug|fir|2.9.1
vscode-pull-request-github|Git|0.21.0
gc-excelviewer|Gra|3.0.40
vscode-docker|ms-|1.7.0
project-snippets|reb|0.5.0
code-spell-checker|str|1.9.4
vscode-icons|vsc|11.0.0

</details>

**Comment by mjbvz** [comment]
Please fill in the template.

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
