### ISSUE TITLE
Cannot turn on settings sync

### ISSUE THREAD

**Issue by michael-motornyi** [microsoft/vscode#110873]
- VSCode Version: 1.51.1
- OS Version: Windows 10 Version 2004 (OS Build 20257.1)

Steps to Reproduce:

1. Click on Accounts > Turn on Settings Sync > Turn on
2. Sign in & Turn on
3. Select account
4. Error: [error] Cannot read property 'locale' of undefined: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot read property 'locale' of undefined

Does this issue occur when all extensions are disabled?: Yes

**Comment by michael-motornyi** [comment]
`[2020-11-18 18:59:49.381] [renderer1] [error] Cannot read property 'locale' of undefined: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot read property 'locale' of undefined
    at Function.e.toUserDataSyncError (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2917:881)
    at Object.call (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:376)
    at async h.preview (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:569)
    at async file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6169:10
[2020-11-18 19:03:43.556] [renderer1] [error] Cannot read property 'locale' of undefined: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot read property 'locale' of undefined
    at Function.e.toUserDataSyncError (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2917:881)
    at Object.call (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:376)
    at async h.preview (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:569)
    at async file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6169:10
[2020-11-18 19:04:03.103] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-11-18 19:04:03.218] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-11-18 19:04:34.026] [renderer1] [error] Cannot read property 'locale' of undefined: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot read property 'locale' of undefined
    at Function.e.toUserDataSyncError (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2917:881)
    at Object.call (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:376)
    at async h.preview (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:569)
    at async file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6169:10
[2020-11-18 19:05:23.400] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-11-18 19:05:23.419] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-11-18 19:05:51.787] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-11-18 19:05:51.789] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-11-18 19:07:41.156] [renderer1] [error] Cannot read property 'locale' of undefined: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot read property 'locale' of undefined
    at Function.e.toUserDataSyncError (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2917:881)
    at Object.call (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:376)
    at async h.preview (file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:569)
    at async file:///C:/Users/shade/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6169:10`

**Comment by sandy081** [comment]
Can you enable log level to trace using command `Developer: Set Log Level` and provide following logs too

- F1 > Developer: Toggle Shared Process > Console
- F1 > Open View > Log (Settings Sync)

**Comment by michael-motornyi** [comment]
Setting Sync:
`[2020-11-18 22:28:15.962] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-11-18 22:28:15.962] [userDataSync] [info] Auto Sync is disabled.
[2020-11-20 10:43:16.263] [userDataSync] [info] Did reset the local sync state.
[2020-11-20 10:43:16.713] [userDataSync] [info] Settings: Stopped synchronizing settings.
[2020-11-20 10:43:16.714] [userDataSync] [info] Keybindings: Stopped synchronizing keybindings.
[2020-11-20 10:43:16.714] [userDataSync] [info] Snippets: Stopped synchronizing snippets.`

**Comment by michael-motornyi** [comment]
Toggle Shared Process > Console: - doesn't show any error regarding settings sync
![image](https://user-images.githubusercontent.com/33175499/99779608-fa668200-2b1d-11eb-9c9a-57a0adb2ec4d.png)

**Comment by sandy081** [comment]
Cant find any helpful info. Can you try turn on sync again and see if there are any errors in shared process log?

- F1 > Open View > Log (Shared)
