### ISSUE TITLE
Exploration: workbench.action.toggleSidebarPosition smoke test failure on macOS

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#110939]
Sample run https://monacotools.visualstudio.com/Monaco/_build/results?buildId=94515&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=88928627-a399-54e7-2f20-a03c2cf00dcd&l=78

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Preferences
           changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:
     Error: Timeout: get element '.keybindings-list-container .monaco-list-row.keybinding-item.focused.selected' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)
```

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/109644
