### ISSUE TITLE
ci: Error: Unknown terminal: 23 in integration tests

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#110936]
Sample runs

* https://monacotools.visualstudio.com/Monaco/_build/results?buildId=94480&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=a099afca-dbc0-5987-bf48-8950ed3c0139&l=435
* https://monacotools.visualstudio.com/Monaco/_build/results?buildId=94480&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=b8cfa60d-6112-5486-b7ad-bbaf650a8650&l=264

```
Unknown terminal: 23: Error: Unknown terminal: 23
    at f._getTerminalProcess (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5244:958)
    at f.$sendProcessReady (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5243:794)
    at p._doInvokeHandler (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4478:1013)
    at p._invokeHandler (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4478:705)
    at p._receiveRequest (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4477:344)
    at p._receiveOneMessage (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4476:156)
    at file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4474:213
    at c.fire (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:99:423)
    at fire (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:480:878)
    at t.PersistentProtocol._receiveMessage (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:485:921)
    at file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:482:984
    at c.fire (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:99:423)
    at g.acceptChunk (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:478:306)
    at file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:477:657
    at Socket.t (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:487:567)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by deepak1556** [comment]
Not exactly test failure, but curious log on all platforms. Filing for code owner to investigate.

**Comment by meganrogge** [comment]
I'm thinking that this delay wasn't long enough for this case for some reason. So the terminal hadn't yet been registered by the time `getTerminalProcess` was called. I can't find any prior issues Daniel had with this.

![terminal](https://user-images.githubusercontent.com/29464607/99712609-27e8f800-2a58-11eb-8a7b-22cd832c799a.PNG)
