### ISSUE TITLE
Setting sync: Replacing Local results in error

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#110964]
Issue Type: <b>Bug</b>

1) Turn on setting sync using the gear menu
2) Sync everything and use insider service
3) Replace Local
-> notification that settings sync resulted in an error, see log below
-> settings sync remains switched off

```
[2020-11-19 09:52:04.671] [userDataSync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2020-11-19 09:52:04.671] [userDataSync] [info] Auto Sync is disabled.
[2020-11-19 09:52:14.886] [userDataSync] [info] Did reset the local sync state.
[2020-11-19 09:52:19.077] [userDataSync] [info] Deleting from backup /C:/Users/kamaet/AppData/Roaming/Code - Insiders/User/sync/settings/20200709T124943.json
[2020-11-19 09:52:19.089] [userDataSync] [info] Settings: Updated local settings
[2020-11-19 09:52:19.100] [userDataSync] [info] Settings: Updated last synchronized settings
[2020-11-19 09:52:19.126] [userDataSync] [info] Keybindings: Updated local keybindings
[2020-11-19 09:52:19.133] [userDataSync] [info] Keybindings: Updated last synchronized keybindings
[2020-11-19 09:52:19.154] [userDataSync] [info] Snippets: Updated snippet markdown.json
[2020-11-19 09:52:19.163] [userDataSync] [info] Snippets: Updated snippet typescript.json
[2020-11-19 09:52:19.169] [userDataSync] [info] Snippets: Updated last synchronized snippets
[2020-11-19 09:52:19.278] [userDataSync] [info] GlobalState: Updated remote ui state
[2020-11-19 09:52:19.305] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-11-19 09:52:19.536] [userDataSync] [info] Extensions: Stopped synchronizing extensions.
[2020-11-19 09:55:20.687] [userDataSync] [info] Did reset the local sync state.
[2020-11-19 09:55:32.364] [userDataSync] [info] Deleting from backup /C:/Users/kamaet/AppData/Roaming/Code - Insiders/User/sync/settings/20200708T182706.json
[2020-11-19 09:55:32.377] [userDataSync] [info] Settings: Updated local settings
[2020-11-19 09:55:32.386] [userDataSync] [info] Settings: Updated last synchronized settings
[2020-11-19 09:55:32.409] [userDataSync] [info] Keybindings: Updated local keybindings
[2020-11-19 09:55:32.417] [userDataSync] [info] Keybindings: Updated last synchronized keybindings
[2020-11-19 09:55:32.439] [userDataSync] [info] Snippets: Updated snippet markdown.json
[2020-11-19 09:55:32.450] [userDataSync] [info] Snippets: Updated snippet typescript.json
[2020-11-19 09:55:32.455] [userDataSync] [info] Snippets: Updated last synchronized snippets
[2020-11-19 09:55:32.457] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-11-19 09:55:32.463] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-11-19 09:55:32.807] [userDataSync] [info] Extensions: Stopped synchronizing extensions.
```

VS Code version: Code - Insiders 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51, 2020-11-19T05:37:52.577Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.84GB free)|
|Process Argv|--crash-reporter-id 4b0156b6-04c0-4ed1-93af-580bb689ce29|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.2
git-branch|ale|1.6.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.1
tsl-problem-matcher|eam|0.3.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
graphviz-markdown-preview|gee|0.0.8
vscode-pull-request-github-insiders|Git|2020.11.25442
mdmath|goe|2.5.1
rainbow-csv|mec|1.7.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-docker|ms-|1.8.0
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.150.0
remote-ssh-edit-nightly|ms-|2020.11.24164
remote-ssh-nightly|ms-|2020.11.24164
remote-wsl|ms-|0.51.3
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2020.11.1117
vscode-github-issue-notebooks|ms-|0.0.58
vscode-js-profile-flame|ms-|0.0.13
vscode-js-profile-table|ms-|0.0.13
vscode-markdown-notebook|ms-|0.0.13
vsonline|ms-|1.0.3075
material-icon-theme|PKi|4.4.0
ruby|reb|0.27.0
vscode-xml|red|0.14.0
vscode-ruby|win|0.27.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092

```

</details>

**Comment by sandy081** [comment]
I do not see any error in the logs, can you please open Shared Process window and see if there are any errors in the console and let me know?

Also try enabling log level to `trace` to get more info and share the logs.

**Comment by kieferrm** [comment]
Shared process

```[2020-11-19 09:52:04.423] [sharedprocess] [info] main {"machineId":"74b57adae405e52d3c927a8ede8f226353249c0929795143f5d1ec001e53edc4","windowId":2}
[2020-11-19 09:52:04.977] [sharedprocess] [info] Deleted from disk ms-vscode-remote.remote-containers c:\Users\kamaet\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.148.1
[2020-11-19 09:52:19.519] [sharedprocess] [info] Uninstalling extension: ms-toolsai.jupyter
[2020-11-19 09:52:19.520] [sharedprocess] [error] Failed to uninstall extension: ms-toolsai.jupyter Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this.
[2020-11-19 09:52:19.522] [sharedprocess] [error] Error: Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this.
    at U.checkForDependents (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:633:131)
    at U.uninstallExtensions (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:632:909)
    at U.checkForDependenciesAndUninstall (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:632:647)
    at async U.uninstall (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:630:888)
    at async file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:488:226
    at async Promise.all (index 0)
    at async e.updateLocalExtensions (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:488:89)
    at async e.applyResult (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:485:866)
    at async e.doApply (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:471:151)
    at async e.apply (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:465:70)
    at async b.pull (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:579:120)
    at async r.call (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:546:977)
[2020-11-19 09:52:44.074] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-11-19 09:55:32.793] [sharedprocess] [info] Uninstalling extension: ms-toolsai.jupyter
[2020-11-19 09:55:32.794] [sharedprocess] [error] Failed to uninstall extension: ms-toolsai.jupyter Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this.
[2020-11-19 09:55:32.794] [sharedprocess] [error] Error: Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this.
    at U.checkForDependents (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:633:131)
    at U.uninstallExtensions (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:632:909)
    at U.checkForDependenciesAndUninstall (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:632:647)
    at async U.uninstall (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:630:888)
    at async file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:488:226
    at async Promise.all (index 0)
    at async e.updateLocalExtensions (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:488:89)
    at async e.applyResult (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:485:866)
    at async e.doApply (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:471:151)
    at async e.apply (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:465:70)
    at async b.pull (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:579:120)
    at async r.call (file:///C:/Users/kamaet/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:546:977)
```

**Comment by kieferrm** [comment]
Trace log

```
[2020-11-19 09:52:04.671] [userDataSync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2020-11-19 09:52:04.671] [userDataSync] [info] Auto Sync is disabled.
[2020-11-19 09:52:14.886] [userDataSync] [info] Did reset the local sync state.
[2020-11-19 09:52:19.077] [userDataSync] [info] Deleting from backup /C:/Users/kamaet/AppData/Roaming/Code - Insiders/User/sync/settings/20200709T124943.json
[2020-11-19 09:52:19.089] [userDataSync] [info] Settings: Updated local settings
[2020-11-19 09:52:19.100] [userDataSync] [info] Settings: Updated last synchronized settings
[2020-11-19 09:52:19.126] [userDataSync] [info] Keybindings: Updated local keybindings
[2020-11-19 09:52:19.133] [userDataSync] [info] Keybindings: Updated last synchronized keybindings
[2020-11-19 09:52:19.154] [userDataSync] [info] Snippets: Updated snippet markdown.json
[2020-11-19 09:52:19.163] [userDataSync] [info] Snippets: Updated snippet typescript.json
[2020-11-19 09:52:19.169] [userDataSync] [info] Snippets: Updated last synchronized snippets
[2020-11-19 09:52:19.278] [userDataSync] [info] GlobalState: Updated remote ui state
[2020-11-19 09:52:19.305] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-11-19 09:52:19.536] [userDataSync] [info] Extensions: Stopped synchronizing extensions.
[2020-11-19 09:55:20.687] [userDataSync] [info] Did reset the local sync state.
[2020-11-19 09:55:32.364] [userDataSync] [info] Deleting from backup /C:/Users/kamaet/AppData/Roaming/Code - Insiders/User/sync/settings/20200708T182706.json
[2020-11-19 09:55:32.377] [userDataSync] [info] Settings: Updated local settings
[2020-11-19 09:55:32.386] [userDataSync] [info] Settings: Updated last synchronized settings
[2020-11-19 09:55:32.409] [userDataSync] [info] Keybindings: Updated local keybindings
[2020-11-19 09:55:32.417] [userDataSync] [info] Keybindings: Updated last synchronized keybindings
[2020-11-19 09:55:32.439] [userDataSync] [info] Snippets: Updated snippet markdown.json
[2020-11-19 09:55:32.450] [userDataSync] [info] Snippets: Updated snippet typescript.json
[2020-11-19 09:55:32.455] [userDataSync] [info] Snippets: Updated last synchronized snippets
[2020-11-19 09:55:32.457] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-11-19 09:55:32.463] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-11-19 09:55:32.807] [userDataSync] [info] Extensions: Stopped synchronizing extensions.
[2020-11-19 10:24:15.839] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/manifest","type":"GET","headers":{"X-Execution-Id":"e709841f-c6db-4ace-8c22-3d2161e2f370","Content-Type":"application/json","X-Client-Name":"code-insiders","X-Client-Version":"1.52.0-insider","X-Machine-Id":"6cfbb294-ff92-4fc7-98d9-4fda98e57150","X-Client-Commit":"a36c68b9ec3d6a0aca9799d7a10be741a6658a51","X-Account-Type":"github","X-Machine-Session-Id":"6be28c18-ab67-42cc-a157-fd267f95f276","X-User-Session-Id":"327e9afd-1abe-4348-a7ee-59640fef55d6"}}
[2020-11-19 10:24:16.001] [userDataSync] [trace] Request succeeded {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/manifest","status":200,"execution-id":"e709841f-c6db-4ace-8c22-3d2161e2f370","operation-id":"6c055ddbceed448d8f9b2b7aa122ccd2"}
[2020-11-19 10:24:16.027] [userDataSync] [info] Did reset the local sync state.
[2020-11-19 10:24:16.033] [userDataSync] [trace] Settings: Started synchronizing settings...
[2020-11-19 10:24:16.036] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/settings/latest","type":"GET","headers":{"X-Execution-Id":"e709841f-c6db-4ace-8c22-3d2161e2f370","Cache-Control":"no-cache","X-Client-Name":"code-insiders","X-Client-Version":"1.52.0-insider","X-Machine-Id":"6cfbb294-ff92-4fc7-98d9-4fda98e57150","X-Client-Commit":"a36c68b9ec3d6a0aca9799d7a10be741a6658a51","X-Account-Type":"github","X-Machine-Session-Id":"6be28c18-ab67-42cc-a157-fd267f95f276","X-User-Session-Id":"327e9afd-1abe-4348-a7ee-59640fef55d6"}}
[2020-11-19 10:24:16.114] [userDataSync] [trace] Request succeeded {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/settings/latest","status":200,"execution-id":"e709841f-c6db-4ace-8c22-3d2161e2f370","operation-id":"dbcbda346bd4484991079097502dfd03"}
[2020-11-19 10:24:16.131] [userDataSync] [trace] Settings: Merging remote settings with local settings...
[2020-11-19 10:24:16.187] [userDataSync] [trace] Keybindings: Started synchronizing keybindings...
[2020-11-19 10:24:16.187] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/keybindings/latest","type":"GET","headers":{"X-Execution-Id":"e709841f-c6db-4ace-8c22-3d2161e2f370","Cache-Control":"no-cache","X-Client-Name":"code-insiders","X-Client-Version":"1.52.0-insider","X-Machine-Id":"6cfbb294-ff92-4fc7-98d9-4fda98e57150","X-Client-Commit":"a36c68b9ec3d6a0aca9799d7a10be741a6658a51","X-Account-Type":"github","X-Machine-Session-Id":"6be28c18-ab67-42cc-a157-fd267f95f276","X-User-Session-Id":"327e9afd-1abe-4348-a7ee-59640fef55d6"}}
[2020-11-19 10:24:16.247] [userDataSync] [trace] Request succeeded {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/keybindings/latest","status":200,"execution-id":"e709841f-c6db-4ace-8c22-3d2161e2f370","operation-id":"ab9987e8c86e4460b6c9ed5b61c8d88d"}
[2020-11-19 10:24:16.252] [userDataSync] [trace] Keybindings: Remote keybindings does not exist. Synchronizing keybindings for the first time.
[2020-11-19 10:24:16.267] [userDataSync] [trace] Snippets: Started synchronizing snippets...
[2020-11-19 10:24:16.270] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/snippets/latest","type":"GET","headers":{"X-Execution-Id":"e709841f-c6db-4ace-8c22-3d2161e2f370","Cache-Control":"no-cache","X-Client-Name":"code-insiders","X-Client-Version":"1.52.0-insider","X-Machine-Id":"6cfbb294-ff92-4fc7-98d9-4fda98e57150","X-Client-Commit":"a36c68b9ec3d6a0aca9799d7a10be741a6658a51","X-Account-Type":"github","X-Machine-Session-Id":"6be28c18-ab67-42cc-a157-fd267f95f276","X-User-Session-Id":"327e9afd-1abe-4348-a7ee-59640fef55d6"}}
[2020-11-19 10:24:16.327] [userDataSync] [trace] Request succeeded {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/snippets/latest","status":200,"execution-id":"e709841f-c6db-4ace-8c22-3d2161e2f370","operation-id":"54a3f2461e2742278fd395f9fe17a3a4"}
[2020-11-19 10:24:16.344] [userDataSync] [trace] Snippets: Merging remote snippets with local snippets...
[2020-11-19 10:24:16.345] [userDataSync] [trace] GlobalState: Started synchronizing globalstate...
[2020-11-19 10:24:16.347] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/globalState/latest","type":"GET","headers":{"X-Execution-Id":"e709841f-c6db-4ace-8c22-3d2161e2f370","Cache-Control":"no-cache","X-Client-Name":"code-insiders","X-Client-Version":"1.52.0-insider","X-Machine-Id":"6cfbb294-ff92-4fc7-98d9-4fda98e57150","X-Client-Commit":"a36c68b9ec3d6a0aca9799d7a10be741a6658a51","X-Account-Type":"github","X-Machine-Session-Id":"6be28c18-ab67-42cc-a157-fd267f95f276","X-User-Session-Id":"327e9afd-1abe-4348-a7ee-59640fef55d6"}}
[2020-11-19 10:24:16.410] [userDataSync] [trace] Request succeeded {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/globalState/latest","status":200,"execution-id":"e709841f-c6db-4ace-8c22-3d2161e2f370","operation-id":"9385e9e164fc459e80272d8768843e9a"}
[2020-11-19 10:24:16.415] [userDataSync] [trace] GlobalState: Merging remote ui state with local ui state...
[2020-11-19 10:24:16.440] [userDataSync] [trace] Extensions: Started synchronizing extensions...
[2020-11-19 10:24:16.442] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/extensions/latest","type":"GET","headers":{"X-Execution-Id":"e709841f-c6db-4ace-8c22-3d2161e2f370","Cache-Control":"no-cache","X-Client-Name":"code-insiders","X-Client-Version":"1.52.0-insider","X-Machine-Id":"6cfbb294-ff92-4fc7-98d9-4fda98e57150","X-Client-Commit":"a36c68b9ec3d6a0aca9799d7a10be741a6658a51","X-Account-Type":"github","X-Machine-Session-Id":"6be28c18-ab67-42cc-a157-fd267f95f276","X-User-Session-Id":"327e9afd-1abe-4348-a7ee-59640fef55d6"}}
[2020-11-19 10:24:16.506] [userDataSync] [trace] Request succeeded {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/extensions/latest","status":200,"execution-id":"e709841f-c6db-4ace-8c22-3d2161e2f370","operation-id":"db7768b297c14fae857e0e8bf3da8c88"}
[2020-11-19 10:24:16.646] [userDataSync] [trace] Extensions: Merging remote extensions with local extensions...
[2020-11-19 10:24:18.648] [userDataSync] [trace] Settings: Updating local settings...
[2020-11-19 10:24:18.657] [userDataSync] [info] Deleting from backup /C:/Users/kamaet/AppData/Roaming/Code - Insiders/User/sync/settings/20200618T114853.json
[2020-11-19 10:24:18.668] [userDataSync] [info] Settings: Updated local settings
[2020-11-19 10:24:18.670] [userDataSync] [trace] Settings: Updating last synchronized settings...
[2020-11-19 10:24:18.676] [userDataSync] [info] Settings: Updated last synchronized settings
[2020-11-19 10:24:18.678] [userDataSync] [trace] Keybindings: Updating local keybindings...
[2020-11-19 10:24:18.695] [userDataSync] [info] Keybindings: Updated local keybindings
[2020-11-19 10:24:18.696] [userDataSync] [trace] Keybindings: Updating last synchronized keybindings...
[2020-11-19 10:24:18.702] [userDataSync] [info] Keybindings: Updated last synchronized keybindings
[2020-11-19 10:24:18.712] [userDataSync] [trace] Snippets: Updating snippet... markdown.json
[2020-11-19 10:24:18.721] [userDataSync] [info] Snippets: Updated snippet markdown.json
[2020-11-19 10:24:18.721] [userDataSync] [trace] Snippets: Updating snippet... typescript.json
[2020-11-19 10:24:18.729] [userDataSync] [info] Snippets: Updated snippet typescript.json
[2020-11-19 10:24:18.729] [userDataSync] [trace] Snippets: Updating last synchronized snippets...
[2020-11-19 10:24:18.735] [userDataSync] [info] Snippets: Updated last synchronized snippets
[2020-11-19 10:24:18.738] [userDataSync] [trace] GlobalState: Updating remote ui state...
[2020-11-19 10:24:18.738] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/globalState","type":"POST","headers":{"X-Execution-Id":"e709841f-c6db-4ace-8c22-3d2161e2f370","Content-Type":"text/plain","X-Client-Name":"code-insiders","X-Client-Version":"1.52.0-insider","X-Machine-Id":"6cfbb294-ff92-4fc7-98d9-4fda98e57150","X-Client-Commit":"a36c68b9ec3d6a0aca9799d7a10be741a6658a51","X-Account-Type":"github","X-Machine-Session-Id":"6be28c18-ab67-42cc-a157-fd267f95f276","X-User-Session-Id":"327e9afd-1abe-4348-a7ee-59640fef55d6"}}
[2020-11-19 10:24:18.909] [userDataSync] [trace] Request succeeded {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/globalState","status":200,"execution-id":"e709841f-c6db-4ace-8c22-3d2161e2f370","operation-id":"aa79477db63344789cd46a3e30999371"}
[2020-11-19 10:24:18.909] [userDataSync] [info] GlobalState: Updated remote ui state
[2020-11-19 10:24:18.909] [userDataSync] [trace] GlobalState: Updating last synchronized ui state...
[2020-11-19 10:24:18.916] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-11-19 10:24:18.964] [userDataSync] [trace] Settings: Checking for local changes...
[2020-11-19 10:24:18.965] [userDataSync] [trace] Keybindings: Checking for local changes...
[2020-11-19 10:24:18.992] [userDataSync] [trace] Snippets: Checking for local changes...
[2020-11-19 10:24:19.003] [userDataSync] [trace] Keybindings: Remote keybindings does not exist. Synchronizing keybindings for the first time.
[2020-11-19 10:24:19.003] [userDataSync] [trace] Settings: Merging remote settings with local settings...
[2020-11-19 10:24:19.041] [userDataSync] [trace] Snippets: Merging remote snippets with local snippets...
[2020-11-19 10:24:19.120] [userDataSync] [trace] Extensions: Uninstalling local extension... ms-toolsai.jupyter
[2020-11-19 10:24:19.154] [userDataSync] [trace] Extensions: Stopping synchronizing extensions.
[2020-11-19 10:24:19.156] [userDataSync] [info] Extensions: Stopped synchronizing extensions.
```

**Comment by sandy081** [comment]
Thanks, seems error in extension syncing is causing this.

**Comment by sandy081** [comment]
To verify:

### Verify installing packs

- Machine 1: Set up Settings Sync
- Machine 1: Install **Remote Development** extensions pack
- Machine 1: Uninstall **Remote - WSL** extension
- Machine 2: Set up Settings Sync
- Make sure **Remote Development** extensions pack excluding **Remote - WSL** extension is installed.

### Verify uninstalling extensions with dependencies

- Machine 1: Set up Settings Sync
- Machine 1: Install **Python** extension. It also install **Jupyter** extension as Python extension depends on it.
- Machine 2: Set up Settings Sync - Make sure **Python** and **Jupyter** extensions are installed
- Machine 1: Open Extensions folder and delete `Jupyter` extension
- Machine 1: Run `Sync Now` command
- Machine 1: Run `Sync Now` command 
- Make sure **Jupyter** extension is uninstalled and there are no errors in Settings Sync logs.
