### ISSUE TITLE
Variables are not displayed in debug console

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#111191]
1. Have a program like

```js
console.log({
  complex: {
      object: true
  }
});
```

1. Debug it it
1. Nothing is displayed in the debug console, and this error is shown

```
  ERR element.onDidChangeCount is not a function: TypeError: element.onDidChangeCount is not a function
    at ReplSimpleElementsRenderer.renderElement (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/workbench/contrib/debug/browser/replViewer.js:122:52)
    at AsyncDataTreeRenderer.renderElement (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:53:27)
    at TreeRenderer.renderElement (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/tree/abstractTree.js:235:27)
    at PipelineRenderer.renderElement (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/list/listWidget.js:748:26)
    at ListView.insertItemInDOM (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/list/listView.js:513:26)
    at ListView._splice (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/list/listView.js:328:26)
    at ListView.splice (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/list/listView.js:267:29)
    at file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///C:/Users/Connor/Documents/Github/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
```

**Comment by isidorn** [comment]
Great catch, thanks for filling!
