### ISSUE TITLE
Notebook integration tests: Lots of error output

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111280]
When I run the notebook integration tests, I get a log of error logging, unlike the other integration tests

```
  Notebook API tests
[22175:1125/094657.756783:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
(node:22175) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
    ✓ document open/close event (378ms)
[22175:1125/094658.179259:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094658.335710:INFO:CONSOLE(137)] "Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (file:///home/martin/workspaces/vscode/out/vs/base/common/lifecycle.js:137:34)
    at EditorWorkerClient._register (file:///home/martin/workspaces/vscode/out/vs/base/common/lifecycle.js:161:32)
    at EditorWorkerClient._getOrCreateModelManager (file:///home/martin/workspaces/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:349:43)
    at file:///home/martin/workspaces/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:358:22
    at async Promise.all (index 0)", source: file:///home/martin/workspaces/vscode/out/vs/base/common/lifecycle.js (137)
[22175:1125/094658.335776:INFO:CONSOLE(238)] "[uncaught exception]: null", source: file:///home/martin/workspaces/vscode/out/bootstrap-window.js (238)
[22175:1125/094658.335811:INFO:CONSOLE(10)] "Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'file:///home/martin/workspaces/vscode/out/vs/loader.js' failed to load.", source: file:///home/martin/workspaces/vscode/out/vs/base/worker/workerMain.js#editorWorkerService (10)
    ✓ notebook open/close, all cell-documents are ready (247ms)
[22175:1125/094658.390360:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ notebook open/close, notebook ready when cell-document open event is fired (136ms)
[22175:1125/094658.507858:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094658.627326:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ shared document in notebook editors (404ms)
[22175:1125/094658.965067:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ editor open/close event (251ms)
[22175:1125/094659.202475:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094659.348748:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ editor open/close event 2 (420ms)
[22175:1125/094659.603945:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094659.657601:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ editor editing event 2 (414ms)
[22175:1125/094700.014786:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094700.063885:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094700.148653:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094700.409529:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ editor move cell event (561ms)
[22175:1125/094700.563966:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094700.673347:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ notebook editor active/visible (547ms)
[22175:1125/094701.160048:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094701.282723:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ notebook active editor change (439ms)
[22175:1125/094701.566233:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094701.626761:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API (replaceCells) (284ms)
[22175:1125/094701.838704:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API (replaceOutput, USE NotebookCellOutput-type) (411ms)
[22175:1125/094702.237063:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API (replaceOutput) (119ms)
[22175:1125/094702.382151:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API (replaceOutput, event) (130ms)
[22175:1125/094702.479983:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API (replaceMetadata) (93ms)
[22175:1125/094702.578724:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API (replaceMetadata, event) (105ms)
[22175:1125/094702.679408:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094702.718397:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ workspace edit API (replaceCells) (171ms)
[22175:1125/094702.851566:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094702.894848:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ workspace edit API (replaceCells, event) (139ms)
[22175:1125/094702.990227:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.029763:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API batch edits (119ms)
[22175:1125/094703.113801:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.146573:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ edit API batch edits undo/redo (127ms)
[22175:1125/094703.238231:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ initialzation should not emit cell change events. (85ms)
  notebook workflow
[22175:1125/094703.321813:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.361219:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.402764:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ notebook open (179ms)
[22175:1125/094703.512143:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.544567:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.587183:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.674315:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ notebook cell actions (378ms)
[22175:1125/094703.891327:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.937972:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094703.972416:INFO:CONSOLE(286)] "monospace assumptions have been violated, therefore disabling monospace optimizations!", source: file:///home/martin/workspaces/vscode/out/vs/editor/browser/viewParts/lines/viewLine.js (286)
    ✓ notebook join cells (337ms)
[22175:1125/094704.255054:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094704.295892:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094704.345393:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ move cells will not recreate cells in ExtHost (340ms)
[22175:1125/094704.578801:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ cell runnable metadata is respected (167ms)
[22175:1125/094704.729238:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ document runnable metadata is respected (121ms)
  notebook dirty state
[22175:1125/094704.849721:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094704.888201:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094704.940705:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ notebook open (246ms)
  notebook undo redo
[22175:1125/094705.108050:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094705.163563:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094705.203679:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ notebook open (310ms)
    - execute and then undo redo
  notebook working copy
[22175:1125/094705.425205:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094705.476351:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094705.521052:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094705.619408:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ multiple tabs: dirty + clean (399ms)
[22175:1125/094705.814688:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094705.860270:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094705.903312:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094706.006391:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094706.060249:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ multiple tabs: two dirty tabs and switching (502ms)
[22175:1125/094706.323260:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094706.411513:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ multiple tabs: different editors with same document (254ms)
  metadata
[22175:1125/094706.580305:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ custom metadata should be supported (118ms)
    - custom metadata should be supported 2
  regression
[22175:1125/094706.689054:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094706.795655:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ #106657. Opening a notebook from markers view is broken  (179ms)
    - Cannot open notebook from cell-uri with vscode.open-command
[22175:1125/094706.885146:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ #97830, #97764. Support switch to other editor types (200ms)
    ✓ #96105 - dirty editors (131ms)
[22175:1125/094707.191714:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
    ✓ #102411 - untitled notebook creation failed (109ms)
[22175:1125/094707.310114:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094707.362818:INFO:CONSOLE(344)] "Element already has context attribute", source: file:///home/martin/workspaces/vscode/out/vs/platform/contextkey/browser/contextKeyService.js (344)
[22175:1125/094707.366590:INFO:CONSOLE(344)] "[hhb] potential listener LEAK detected, having 400 listeners already. MOST frequent listener (1):", source: file:///home/martin/workspaces/vscode/out/vs/base/common/event.js (344)
[22175:1125/094707.366653:INFO:CONSOLE(345)] "    at new ViewportSemanticTokensContribution (file:///home/martin/workspaces/vscode/out/vs/editor/contrib/viewportSemanticTokens/viewportSemanticTokens.js:47:47)
    at InstantiationService._createInstance (file:///home/martin/workspaces/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService.createInstance (file:///home/martin/workspaces/vscode/out/vs/platform/instantiation/common/instantiationService.js:59:31)
    at new CodeEditorWidget (file:///home/martin/workspaces/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:151:69)
    at InstantiationService._createInstance (file:///home/martin/workspaces/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService.createInstance (file:///home/martin/workspaces/vscode/out/vs/platform/instantiation/common/instantiationService.js:59:31)
    at CodeCellRenderer.renderTemplate (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.js:550:47)
    at file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:743:46
    at Array.map (<anonymous>)
    at PipelineRenderer.renderTemplate (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:743:35)
    at RowCache.alloc (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/rowCache.js:33:47)
    at ListView.insertItemInDOM (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/listView.js:491:39)
    at ListView._splice (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/listView.js:328:26)
    at ListView.splice (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/listView.js:267:29)
    at file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:968:67
    at EventBufferer.bufferEvents (file:///home/martin/workspaces/vscode/out/vs/base/common/event.js:655:23)
    at NotebookCellList.splice (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:968:32)
    at NotebookCellList.splice2 (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:388:19)
    at file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:256:30
    at Array.forEach (<anonymous>)
    at file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:243:41
    at Emitter.fire (file:///home/martin/workspaces/vscode/out/vs/base/common/event.js:456:38)
    at compute (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.js:121:44)
    at file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.js:155:25
    at Emitter.fire (file:///home/martin/workspaces/vscode/out/vs/base/common/event.js:456:38)
    at DelayedEmitter.endDeferredEmit (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:138:46)
    at NotebookTextModel.applyEdits (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:312:32)
    at NotebookViewModel.createCell (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.js:481:28)
    at NotebookEditorWidget.insertNotebookCell (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:1132:53)
    at copyCell (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/contrib/coreActions.js:766:48)
    at Object.runWithContext (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/contrib/coreActions.js:1000:20)
    at Object.run (file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/notebook/browser/contrib/coreActions.js:143:29)
    at handler (file:///home/martin/workspaces/vscode/out/vs/platform/actions/common/actions.js:328:52)
    at InstantiationService.invokeFunction (file:///home/martin/workspaces/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at CommandService._tryExecuteCommand (file:///home/martin/workspaces/vscode/out/vs/workbench/services/commands/common/commandService.js:74:59)
    at file:///home/martin/workspaces/vscode/out/vs/workbench/services/commands/common/commandService.js:64:47", source: file:///home/martin/workspaces/vscode/out/vs/base/common/event.js (345)
    ✓ #102423 - copy/paste shares the same text buffer (169ms)
  38 passing (10s)
  3 pending

```

**Comment by rebornix** [comment]
@mjbvz the warning was added a week ago, may I ask what's going on and what's the suggested fix?

**Comment by mjbvz** [comment]
@rebornix See #110363. Creating multiple scoped context key services on the same element can have unexpected behavior. For example:

* All services end up sharing the same storage 
* If any of the services are disposed of, it also clears the keys of all other services on that element

The fix is to make sure there is only a single context key service on an element at a time

**Comment by roblourens** [comment]
I see the problem, I do

```
const contextKeyService = disposables.add(this.contextKeyServiceProvider(container));
...
const editorContextKeyService = disposables.add(this.contextKeyServiceProvider(container));
```

I can probably move editorContextKeyService down a level. I'm not confident I can test whatever this impacts, I'll do it in debt week.
