### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AzadKshitij** [microsoft/vscode#111361]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
RangeError: Maximum call stack size exceeded
    at bindWorker (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40971:28)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40906:13)
    at bindLabeledStatement (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39990:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39460:21)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40917:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
    at bindChildren (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39503:21)
    at bindContainer (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39390:17)
    at bind (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40920:21)
    at c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:94
    at Object.forEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at bindEach (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39405:16)
    at bindEachFunctionsFirst (c:\Users\azadk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39398:13)
```

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|10.94GB (1.45GB free)|
|Process Argv|D:\JavaScript\ReactNative\Intern\GitHub\Secret-Astu --crash-reporter-id c5aaec2c-b3ba-4734-9650-f4bbdf2f3927|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
glsl-canvas|cir|0.2.11
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
flask-snippets|cst|0.1.1
vscode-eslint|dba|2.1.13
competitive-programming-helper|Div|4.5.5
es7-react-js-snippets|dsz|3.0.0
react-native-react-redux|EQu|2.0.6
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
code-runner|for|0.11.1
godot-tools|gee|1.1.2
todo-tree|Gru|0.0.188
pomodoro|lky|1.1.3
rainbow-csv|mec|1.7.1
csharp|ms-|1.23.6
vscode-edge-devtools|ms-|1.1.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
cpptools|ms-|1.1.2
hexeditor|ms-|1.3.0
vscode-react-native|msj|1.1.1
launchx|nei|0.1.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.13
shader|sle|1.1.4
lua|sum|1.1.4
pdf|tom|1.1.0
vscode-counter|uct|2.2.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4
cpp-comment-generator|wuj|0.0.9
material-theme|zhu|3.9.11

</details>

**Comment by mjbvz** [comment]
Please fill in the issue template

**Comment by AzadKshitij** [comment]
I really don't know how the crash has happen there was a notification about filing a issue of this so I filed...😅😅😅😅

**Comment by mjbvz** [comment]
Closing as not actionable with more info.

If you see this again, please follow the instructions on the issue so that we can investigate
