### ISSUE TITLE
Remote-WSL is broken on ARM on latest build

### ISSUE THREAD

**Issue by florentchauveau** [microsoft/vscode#111366]
Version: 1.52.0-insider (user setup)
Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
Date: 2020-11-26T07:31:13.151Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT arm64 10.0.19042

Steps to Reproduce:

1. Run latest vscode insiders (build 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d)
2. Install Remote - WSL extension
3. It will fail with "Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)"

Does this issue occur when all extensions are disabled?: No (obviously)

WSL server logs shows that:
```
[2020-11-26 14:05:45.598] Error: /home/florent/.vscode-server-insiders/bin/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d/node_modules/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory
[2020-11-26 14:05:45.598]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
[2020-11-26 14:05:45.598]     at Module.load (internal/modules/cjs/loader.js:985:32)
...
[2020-11-26 14:05:45.599]     at processTicksAndRejections (internal/process/task_queues.js:83:21) {
[2020-11-26 14:05:45.599]   phase: 'loading',
[2020-11-26 14:05:45.599]   moduleId: 'spdlog',
[2020-11-26 14:05:45.599]   neededBy: [ '===anonymous3===' ]
[2020-11-26 14:05:45.599] }
```

Indeed, loading spdlog from provided node server does not work:
```
$ cd ~/.vscode-server-insiders/bin/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d/
$ ./node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> require("spdlog")
Uncaught:
Error: /home/florent/.vscode-server-insiders/bin/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d/node_modules/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/home/florent/.vscode-server-insiders/bin/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d/node_modules/bindings/bindings.js:112:48)
>
```

It seems that the node binaries provided are ELF 64-bit x86-64, and not aarch64.
```
$ cd node_modules/spdlog/build/Release/
$ ls -l
total 276K
-rwxr-xr-x 1 florent florent 274K Nov 26 07:35 spdlog.node*
$ ./spdlog.node
-bash: ./spdlog.node: cannot execute binary file: Exec format error
$ file spdlog.node
spdlog.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=227085fd5e80ef56ec4ae16834539d3b345d45f2, not stripped
```

Furthermore:
```
$ cd ~/.vscode-server-insiders/bin/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d/node_modules
$ find -name *.node -exec file {} \;
./spdlog/build/Release/spdlog.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=227085fd5e80ef56ec4ae16834539d3b345d45f2, not stripped
./vsda/build/Release/vsda.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=8375612789d2d4888fbc9d83e2cf5d887d16db31, not stripped
./node-pty/build/Release/pty.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2bb315ca3db973ae4d00173989612a47600f5762, not stripped
./native-watchdog/build/Release/watchdog.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=77f63022e523eb440e97dac46dbdf04079223a69, not stripped
./vscode-nsfw/build/Release/nsfw.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c93c890849f1191ee561a832883cfd967f186065, not stripped
```

All node binaries are for x86-64 instead of ARM/aarch64.

Is the CI broken?

**Comment by florentchauveau** [comment]
Sample output from a previous release (commit 6026ab576dc6a4fbb8e255241a364816f42464c5)

Node binary files were aarch64.

```
$ find . -name '*.node' -exec file {} \;
./spdlog/build/Release/spdlog.node: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=ad6efd133c3deb90484b209eedba7327f475d8e7, not stripped
./vsda/build/Release/vsda.node: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=882e2d8abd75ade35274a9128387bf9b45fe97f2, not stripped
./node-pty/build/Release/pty.node: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=22c1d8533246bd48b4f0506877f00c740842debb, not stripped
./native-watchdog/build/Release/watchdog.node: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e2041b2123a5f8a3cc31c5a227be0f3f01c2ef78, not stripped
./vscode-nsfw/build/Release/nsfw.node: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=fe9173f35a9e0203b3248c82dc02ab7c394e567f, not stripped
```

**Comment by aeschli** [comment]
@joaomoreno FYI

**Comment by florentchauveau** [comment]
Hello,

Just received the latest Insiders release (commit bf21395291146c014220eb70b54fdfc0a15956b5). Issue should be reopened I think.

Bundled vs-code-server files are not provided for arm64 (Windows), and download on WSL side does not work.

Logs:

```
[2020-12-01 15:08:42.883] Downloading server on client side to C:\Users\Florent\AppData\Local\Temp\vscode-remote-wsl\bf21395291146c014220eb70b54fdfc0a15956b5\vscode-server-linux-arm64.tar.gz.
[2020-12-01 15:08:42.883] https://update.code.visualstudio.com/commit:bf21395291146c014220eb70b54fdfc0a15956b5/server-linux-arm64/insider
[2020-12-01 15:08:43.106] Unable to download server on client side: Error: Request downloadRequest failed unexpectedly without providing any details.. Will try to download on WSL side.
[...]
[2020-12-01 15:08:43.336] WSL version: 4.19.128-microsoft-standard Ubuntu
[2020-12-01 15:08:43.336] Updating VS Code Server to version bf21395291146c014220eb70b54fdfc0a15956b5
[2020-12-01 15:08:43.336] Removing previous installation...
[2020-12-01 15:08:43.336] Installing VS Code Server for arm64 (bf21395291146c014220eb70b54fdfc0a15956b5)
[2020-12-01 15:08:43.336] Downloading:     100%
[2020-12-01 15:08:43.336] Failed
[...]
[2020-12-01 15:08:43.389] ERROR: Failed to download https://update.code.visualstudio.com/commit:bf21395291146c014220eb70b54fdfc0a15956b5/server-linux-arm64/insider to /home/florent/.vscode-server-insiders/bin/bf21395291146c014220eb70b54fdfc0a15956b5-1606835323.tar.gz
```

In the Temp directory, there are 3 **empty** files:
```
/mnt/c/Users/Florent/AppData/Local/Temp/vscode-remote-wsl/bf21395291146c014220eb70b54fdfc0a15956b5 $ l
total 0
-rwxrwxrwx 1 florent florent 0 Dec  1 16:07 vscode-server-linux-arm64.tar.gz_1606835228790*
-rwxrwxrwx 1 florent florent 0 Dec  1 16:08 vscode-server-linux-arm64.tar.gz_1606835318419*
-rwxrwxrwx 1 florent florent 0 Dec  1 16:08 vscode-server-linux-arm64.tar.gz_1606835322883*
```

Previous releases look like this:
```
/mnt/c/Users/Florent/AppData/Local/Temp/vscode-remote-wsl/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d $ l
total 29M
-rwxrwxrwx 1 florent florent 29M Nov 24 21:29  vscode-server-linux-arm64.tar.gz*
```

**Comment by joaomoreno** [comment]
> [2020-12-01 15:08:43.106] Unable to download server on client side: Error: Request downloadRequest failed unexpectedly without providing any details.. Will try to download on WSL side.

There was a problem publishing this commit's specific server bits. It's a separate and isolated issue. Today's Insiders will be OK.

**Comment by florentchauveau** [comment]
/verified it works! Thank you all :)
