### ISSUE TITLE
Toggle outline icons results in an error

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#111471]
1. Open settings GUI
1. Toggle `outline.icons`

> ERR TreeError [OutlinePane] Tree input not set: Error: TreeError [OutlinePane] Tree input not set
    at G.updateChildren (...resources/app/out/vs/workbench/workbench.desktop.main.js:1088:305)
    at ...resources/app/out/vs/workbench/workbench.desktop.main.js:7905:579
    at c.fire (...resources/app/out/vs/workbench/workbench.desktop.main.js:99:423)
    at k.triggerConfigurationChange (...resources/app/out/vs/workbench/workbench.desktop.main.js:5880:345)
    at k.onLocalUserConfigurationChanged (...resources/app/out/vs/workbench/workbench.desktop.main.js:5875:604)
    at k.reloadLocalUserConfiguration (...resources/app/out/vs/workbench/workbench.desktop.main.js:5872:780)

**Comment by jrieken** [comment]
Doesn't reproduce when running from sources. Please update steps or close

**Comment by usernamehw** [comment]
Ok.
