### ISSUE TITLE
If I drag up from the root of workspace and try to new terminal, vscode crashes.

### ISSUE THREAD

**Issue by hJinRong** [microsoft/vscode#111463]
- VSCode Version: 1.51.1 (system setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. When I drag up from the root of workspace and try to new terminal, vscode crashes.

![2020-11-29 214717](https://user-images.githubusercontent.com/44030391/100560837-0d353f80-32f2-11eb-8704-c97c1e7894b5.png)

![2020-11-29 221720](https://user-images.githubusercontent.com/44030391/100544460-b3505d80-3290-11eb-85f4-b70a0fce38cc.png)

<details>
<summary>settings.json</summary>
<pre><code>
"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
</code></pre>
</details>

<details>
<summary>Devtool warnings</summary>
<pre><code>
[688] potential listener LEAK detected, having 791 listeners already. MOST frequent listener (617):
    at new e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6915:386)
    at d._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1725:671)
    at d.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1725:92)
    at e.getActions (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6930:345)
    at e.collectCompositeActions (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6311:692)
    at e.hideActiveComposite (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6312:269)
    at e.hideActivePanel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6930:795)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:61)
    at Object.hidePart (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6921:609)
    at _.resetActiveComposite (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6785:776)
    at _.hideComposite (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6784:682)
    at e.hideComposite (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6926:467)
    at e.onPanelOpen (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6927:142)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6925:813
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:94:636
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.doOpenComposite (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6308:668)
    at e.openComposite (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6308:136)
    at e.doOpenPanel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6929:599)
    at e.openPanel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6929:688)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:217)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
    at m.setChildVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:893)
    at f.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:646:359)
    at p.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:407)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:294)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
    at m.setChildVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:893)
    at f.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:646:359)
    at p.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:407)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:294)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
    at m.setChildVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:893)
    at f.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:646:359)
    at p.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:407)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:294)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
    at m.setChildVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:893)
    at f.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:646:359)
    at p.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:407)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:294)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
    at m.setChildVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:893)
    at f.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:646:359)
    at p.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:407)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:294)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
    at m.setChildVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:893)
    at f.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:646:359)
    at p.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:407)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:294)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
    at m.setChildVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:893)
    at f.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:646:359)
    at p.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:407)
    at L.setPanelHidden (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7015:294)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7010:47
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at e.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3180:999)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:108)
    at v.setVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:179)
    at S.setViewVisible (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:741)
</code></pre>
</details>

I found out that every time VsCode added 88 listeners until it was a few hundred, and then VsCode crashed。

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
does this happen if you use Ctrl+J or click the menu item Terminal and select New Terminal?

**Comment by hJinRong** [comment]
> does this happen if you click the menu item Terminal and select New Terminal?
> 
> I'm seeing this when I use Ctrl+J and when I drag up from the bottom, but not when I use the menu.

menu item Terminal >> select New Terminal:  It is normal
Ctrl + J / drag up from the bottom: vscode crashed

I was in the same situation as you.

**Comment by meganrogge** [comment]
Are you able to reproduce this issue when you've opened a folder?

**Comment by meganrogge** [comment]
@sguillia @hJinRong @jaques-sam @Cryonayes 

The solution is to right click here and select Reset Location

![term](https://user-images.githubusercontent.com/29464607/101820185-19cc4b80-3adb-11eb-9416-1bc8243bbb5b.PNG)

**Comment by sbatten** [comment]
I have pushed a fix that resolves the issue without the workaround for the future. To verify @meganrogge has a cache of their user data dir that reliably repros the issue.

**Comment by chrmarti** [comment]
@meganrogge Reading above that you can verify this issue. 👍
