### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by SuperTikuwa** [microsoft/vscode#111428]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152055:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153089:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.54GB free)|
|Process Argv|class.code-workspace --crash-reporter-id 01595366-793a-43de-afec-af7de2652506|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
matlab-code-run|bra|1.0.2
bracket-pair-colorizer-2|Coe|0.2.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.13
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.5
matlab|Gim|2.0.0
go|gol|0.19.0
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.15.0
latex-workshop|Jam|8.14.0
rainbow-csv|mec|1.7.1
vscode-docker|ms-|1.8.1
vscode-language-pack-ja|MS-|1.51.2
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
cpptools|ms-|1.1.2
vsliveshare|ms-|1.0.3206
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vuejs-extension-pack|mub|1.2.1
vetur|oct|0.30.3
indent-rainbow|ode|7.4.0
open-html-in-browser|pea|2.1.3
vscode-yaml|red|0.13.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.13
code-spell-checker|str|1.10.0
sass-indented|syl|1.8.13
html-preview-vscode|tht|0.2.5
vscode-status-bar-format-toggle|tom|2.0.0
vscode-lldb|vad|1.6.0
vscodeintellicode|Vis|1.2.10
bracket-lens|wra|1.4.2
JavaScriptSnippets|xab|1.8.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Also, fill in the issue template
