### ISSUE TITLE
WorkdOperations: TypeError: Cannot read property 'get' of null

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111569]
Workaround: https://github.com/microsoft/vscode/commit/648ed9f9d1706a28a5ae1015fafe6371c08f2011

```

      at DeleteInsideWord.reportTelemetry (file:///D:/a/1/s/out-build/vs/editor/browser/editorExtensions.js:200:22)
      at DeleteInsideWord.runEditorCommand (file:///D:/a/1/s/out-build/vs/editor/browser/editorExtensions.js:196:18)
      at runEditorCommand (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:33:21)
      at deleteInsideWord (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:78:13)
      at file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:628:17
      at Object.withTestCodeEditor (file:///D:/a/1/s/out-build/vs/editor/test/browser/testCodeEditor.js:59:9)
      at Context.<anonymous> (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:623:30)

  6) WordOperations deleteInsideWord - in words 1:
     TypeError: Cannot read property 'get' of null
      at DeleteInsideWord.reportTelemetry (file:///D:/a/1/s/out-build/vs/editor/browser/editorExtensions.js:200:22)
      at DeleteInsideWord.runEditorCommand (file:///D:/a/1/s/out-build/vs/editor/browser/editorExtensions.js:196:18)
      at runEditorCommand (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:33:21)
      at deleteInsideWord (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:78:13)
      at file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:650:17
      at Object.withTestCodeEditor (file:///D:/a/1/s/out-build/vs/editor/test/browser/testCodeEditor.js:59:9)
      at Context.<anonymous> (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:645:30)

  7) WordOperations deleteInsideWord - in words 2:
     TypeError: Cannot read property 'get' of null
      at DeleteInsideWord.reportTelemetry (file:///D:/a/1/s/out-build/vs/editor/browser/editorExtensions.js:200:22)
      at DeleteInsideWord.runEditorCommand (file:///D:/a/1/s/out-build/vs/editor/browser/editorExtensions.js:196:18)
      at runEditorCommand (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:33:21)
      at deleteInsideWord (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:78:13)
      at file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:666:17
      at Object.withTestCodeEditor (file:///D:/a/1/s/out-build/vs/editor/test/browser/testCodeEditor.js:59:9)
      at Context.<anonymous> (file:///D:/a/1/s/out-build/vs/editor/contrib/wordOperations/test/wordOperations.test.js:661:30)
```

**Comment by alexdima** [comment]
investigating...

**Comment by alexdima** [comment]
Sorry about that! I converted the command to an action and didn't adjust the unit tests properly. Pushed a fix.
