### ISSUE TITLE
electron tests failing with timeout on Windows

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#111662]
Testing #111492

```
24 passing (3m)
  2 pending
  5 failing

  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Preferences
           changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:     Error: Timeout: click '.keybindings-list-container .monaco-list-row.keybinding-item .action-item .codicon.codicon-add' after 20 seconds.
      at C:\Users\Megan\vscode\test\automation\out\code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\Megan\vscode\test\automation\out\code.js:9:58)

  2) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           verifies problems view:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at C:\Users\Megan\vscode\test\automation\out\code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\Megan\vscode\test\automation\out\code.js:9:58)

  3) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           verifies settings:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at C:\Users\Megan\vscode\test\automation\out\code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\Megan\vscode\test\automation\out\code.js:9:58)

  4) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Statusbar
           verifies that 'Problems View' appears when clicking on 'Problems' status element:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at C:\Users\Megan\vscode\test\automation\out\code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\Megan\vscode\test\automation\out\code.js:9:58)

  5) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Statusbar
           checks if 'Go to Line' works if called from the status bar:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at C:\Users\Megan\vscode\test\automation\out\code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\Megan\vscode\test\automation\out\code.js:9:58)



error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I am not sure how to check my electron version, but perhaps that's the cause?

I tested manually and don't see any problems.

**Comment by lszomoru** [comment]
@deepak1556, could you please take a look at this? Thank you!

**Comment by deepak1556** [comment]
unable to repro, all tests pass with latest insiders. Also tested with `electron-11.x.y` branch and insiders based on Electron 11.

Pretty sure the electron version from OSS copy mismatched with the version from insiders that was tested, since we had a delay in releasing insiders after the Electron 9 revert.
