### ISSUE TITLE
If VSCode is opened first, Webpack cannot use any loaders (Node 6).

### ISSUE THREAD

**Issue by JabX** [Microsoft/vscode#11166]
- VSCode Version: 1.4.0
- OS Version: Windows 7/10

Since I upgraded my Node version to 6, I have a strange bug with my Node/Webpack/VSCode combo that I can reproduce on both my home and work PCs, but not on my colleagues' that are still on Node 5.

Basically, if I open VSCode first, I cannot start any webpack build from either the built-in console, the built-in tasks or even an external console (that had been opened after) without having it fail right away because it cannot use any loader. I use Typescript and I get an error at the first 'non-standard' feature webpack encounters saying it needs a loader to handle that file. I get the error with both `awesome-typescript-loader` and `ts-loader`.

But if I open an external console first and then VSCode, then, in that console, I can launch all my builds without issues, even if VSCode is opened.

This isn't blocking in any way, that it's pretty restrictive (and weird).

**Comment by dbaeumer** [comment]
@JabX can you share a repository that show cases this behavior. Otherwise it is very hard to track down.

**Comment by JabX** [comment]
Sure, I got the problem on my home PC with that repo: https://github.com/mobxjs/mobx-react-typescript-boilerplate

**Comment by dbaeumer** [comment]
This works for me using the following commands:

```
Playgrounds\bugs\11166 [master]> code.cmd .
Playgrounds\bugs\11166 [master]> npm start

> mobx-react-typescript-boilerplate@1.0.0 start P:\mseng\VSCode\Playgrounds\bugs\11166
> node server.js

Listening at localhost:3000
ts-loader: Using typescript@1.8.10 and P:\mseng\VSCode\Playgrounds\bugs\11166\tsconfig.json
Hash: cf0b0bf54914168b2971
Version: webpack 1.13.2
Time: 3292ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.19 MB       0  [emitted]  main
chunk    {0} bundle.js (main) 1.07 MB [rendered]
    [0] multi main 40 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:3000 2.85 kB {0} [built]
    [2] ./~/url/url.js 22.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/querystring/index.js 127 bytes {0} [built]
    [6] ./~/querystring/decode.js 2.4 kB {0} [built]
    [7] ./~/querystring/encode.js 2.09 kB {0} [built]
    [8] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
    [9] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [10] ./~/sockjs-client/lib/transport/websocket.js 2.71 kB {0} [built]
   [11] ./~/process/browser.js 5.3 kB {0} [built]
   [12] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [13] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [14] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [15] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [16] ./~/url-parse/index.js 8.55 kB {0} [built]
   [17] ./~/requires-port/index.js 753 bytes {0} [built]
   [18] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
   [19] ./~/querystringify/index.js 1.3 kB {0} [built]
   [20] ./~/debug/browser.js 3.76 kB {0} [built]
   [21] ./~/debug/debug.js 4.1 kB {0} [built]
   [22] ./~/ms/index.js 2.33 kB {0} [built]
   [23] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [24] ./~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
   [25] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [26] ./~/sockjs-client/lib/transport/browser/websocket.js 172 bytes {0} [built]
   [27] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [28] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
   [29] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0} [built]
   [30] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
   [31] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [33] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
   [34] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [built]
   [35] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
   [36] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [37] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [38] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [39] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [40] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
   [41] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
   [42] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
   [43] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [44] ./~/json3/lib/json3.js 43.3 kB {0} [built]
   [45] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [46] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [47] ./~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
   [48] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [49] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [50] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [51] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [52] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [53] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [54] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [55] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [56] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [57] ./~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [58] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [59] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [60] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [61] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [62] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [63] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [64] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [65] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [66] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [67] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [68] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [69] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [70] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [71] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [72] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [73] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [74] ./src/index.tsx 2.27 kB {0} [built]
   [75] ./~/react/react.js 56 bytes {0} [built]
   [76] ./~/react/lib/React.js 2.72 kB {0} [built]
   [77] ./~/object-assign/index.js 1.99 kB {0} [built]
   [78] ./~/react/lib/ReactChildren.js 6.22 kB {0} [built]
   [79] ./~/react/lib/PooledClass.js 3.59 kB {0} [built]
   [80] ./~/react/lib/reactProdInvariant.js 1.27 kB {0} [built]
   [81] ./~/fbjs/lib/invariant.js 1.49 kB {0} [built]
   [82] ./~/react/lib/ReactElement.js 12.5 kB {0} [built]
   [83] ./~/react/lib/ReactCurrentOwner.js 657 bytes {0} [built]
   [84] ./~/fbjs/lib/warning.js 2.1 kB {0} [built]
   [85] ./~/fbjs/lib/emptyFunction.js 1.08 kB {0} [built]
   [86] ./~/react/lib/canDefineProperty.js 632 bytes {0} [built]
   [87] ./~/react/lib/traverseAllChildren.js 6.74 kB {0} [built]
   [88] ./~/react/lib/getIteratorFn.js 1.15 kB {0} [built]
   [89] ./~/react/lib/KeyEscapeUtils.js 1.33 kB {0} [built]
   [90] ./~/react/lib/ReactComponent.js 4.64 kB {0} [built]
   [91] ./~/react/lib/ReactNoopUpdateQueue.js 3.4 kB {0} [built]
   [92] ./~/fbjs/lib/emptyObject.js 458 bytes {0} [built]
   [93] ./~/react/lib/ReactPureComponent.js 1.36 kB {0} [built]
   [94] ./~/react/lib/ReactClass.js 27.2 kB {0} [built]
   [95] ./~/react/lib/ReactPropTypeLocations.js 552 bytes {0} [built]
   [96] ./~/fbjs/lib/keyMirror.js 1.25 kB {0} [built]
   [97] ./~/react/lib/ReactPropTypeLocationNames.js 614 bytes {0} [built]
   [98] ./~/fbjs/lib/keyOf.js 1.1 kB {0} [built]
   [99] ./~/react/lib/ReactDOMFactories.js 5.56 kB {0} [built]
  [100] ./~/react/lib/ReactElementValidator.js 8.08 kB {0} [built]
  [101] ./~/react/lib/ReactComponentTreeHook.js 10.1 kB {0} [built]
  [102] ./~/react/lib/checkReactTypeSpec.js 4.23 kB {0} [built]
  [103] ./~/react/lib/ReactPropTypesSecret.js 478 bytes {0} [built]
  [104] ./~/react/lib/ReactPropTypes.js 15.6 kB {0} [built]
  [105] ./~/react/lib/ReactVersion.js 382 bytes {0} [built]
  [106] ./~/react/lib/onlyChild.js 1.37 kB {0} [built]
  [107] ./~/react-dom/index.js 63 bytes {0} [built]
  [108] ./~/react/lib/ReactDOM.js 5.08 kB {0} [built]
  [109] ./~/react/lib/ReactDOMComponentTree.js 6.2 kB {0} [built]
  [110] ./~/react/lib/DOMProperty.js 8.13 kB {0} [built]
  [111] ./~/react/lib/ReactDOMComponentFlags.js 471 bytes {0} [built]
  [112] ./~/react/lib/ReactDefaultInjection.js 3.4 kB {0} [built]
  [113] ./~/react/lib/BeforeInputEventPlugin.js 13.9 kB {0} [built]
  [114] ./~/react/lib/EventConstants.js 2.17 kB {0} [built]
  [115] ./~/react/lib/EventPropagators.js 5.32 kB {0} [built]
  [116] ./~/react/lib/EventPluginHub.js 8.32 kB {0} [built]
  [117] ./~/react/lib/EventPluginRegistry.js 9.48 kB {0} [built]
  [118] ./~/react/lib/EventPluginUtils.js 8.17 kB {0} [built]
  [119] ./~/react/lib/ReactErrorUtils.js 2.26 kB {0} [built]
  [120] ./~/react/lib/accumulateInto.js 1.73 kB {0} [built]
  [121] ./~/react/lib/forEachAccumulated.js 893 bytes {0} [built]
  [122] ./~/fbjs/lib/ExecutionEnvironment.js 1.06 kB {0} [built]
  [123] ./~/react/lib/FallbackCompositionState.js 2.47 kB {0} [built]
  [124] ./~/react/lib/getTextContentAccessor.js 997 bytes {0} [built]
  [125] ./~/react/lib/SyntheticCompositionEvent.js 1.14 kB {0} [built]
  [126] ./~/react/lib/SyntheticEvent.js 9.13 kB {0} [built]
  [127] ./~/react/lib/SyntheticInputEvent.js 1.13 kB {0} [built]
  [128] ./~/react/lib/ChangeEventPlugin.js 11.5 kB {0} [built]
  [129] ./~/react/lib/ReactUpdates.js 9.6 kB {0} [built]
  [130] ./~/react/lib/CallbackQueue.js 2.73 kB {0} [built]
  [131] ./~/react/lib/ReactFeatureFlags.js 665 bytes {0} [built]
  [132] ./~/react/lib/ReactReconciler.js 6.25 kB {0} [built]
  [133] ./~/react/lib/ReactRef.js 2.47 kB {0} [built]
  [134] ./~/react/lib/ReactOwner.js 3.6 kB {0} [built]
  [135] ./~/react/lib/ReactInstrumentation.js 559 bytes {0} [built]
  [136] ./~/react/lib/ReactDebugTool.js 9.98 kB {0} [built]
  [137] ./~/react/lib/ReactInvalidSetStateWarningHook.js 1.03 kB {0} [built]
  [138] ./~/react/lib/ReactHostOperationHistoryHook.js 860 bytes {0} [built]
  [139] ./~/react/lib/ReactChildrenMutationWarningHook.js 1.66 kB {0} [built]
  [140] ./~/fbjs/lib/performanceNow.js 845 bytes {0} [built]
  [141] ./~/fbjs/lib/performance.js 588 bytes {0} [built]
  [142] ./~/react/lib/Transaction.js 9.61 kB {0} [built]
  [143] ./~/react/lib/getEventTarget.js 1.04 kB {0} [built]
  [144] ./~/react/lib/isEventSupported.js 1.97 kB {0} [built]
  [145] ./~/react/lib/isTextInputElement.js 1.08 kB {0} [built]
  [146] ./~/react/lib/DefaultEventPluginOrder.js 1.26 kB {0} [built]
  [147] ./~/react/lib/EnterLeaveEventPlugin.js 3.46 kB {0} [built]
  [148] ./~/react/lib/SyntheticMouseEvent.js 2.18 kB {0} [built]
  [149] ./~/react/lib/SyntheticUIEvent.js 1.61 kB {0} [built]
  [150] ./~/react/lib/ViewportMetrics.js 641 bytes {0} [built]
  [151] ./~/react/lib/getEventModifierState.js 1.27 kB {0} [built]
  [152] ./~/react/lib/HTMLDOMPropertyConfig.js 5.38 kB {0} [built]
  [153] ./~/react/lib/ReactComponentBrowserEnvironment.js 958 bytes {0} [built]
  [154] ./~/react/lib/DOMChildrenOperations.js 7.3 kB {0} [built]
  [155] ./~/react/lib/DOMLazyTree.js 3.75 kB {0} [built]
  [156] ./~/react/lib/DOMNamespaces.js 538 bytes {0} [built]
  [157] ./~/react/lib/setInnerHTML.js 3.91 kB {0} [built]
  [158] ./~/react/lib/createMicrosoftUnsafeLocalFunction.js 864 bytes {0} [built]
  [159] ./~/react/lib/setTextContent.js 1.4 kB {0} [built]
  [160] ./~/react/lib/escapeTextContentForBrowser.js 3.48 kB {0} [built]
  [161] ./~/react/lib/Danger.js 2.27 kB {0} [built]
  [162] ./~/fbjs/lib/createNodesFromMarkup.js 2.66 kB {0} [built]
  [163] ./~/fbjs/lib/createArrayFromMixed.js 4.11 kB {0} [built]
  [164] ./~/fbjs/lib/getMarkupWrap.js 3.04 kB {0} [built]
  [165] ./~/react/lib/ReactMultiChildUpdateTypes.js 864 bytes {0} [built]
  [166] ./~/react/lib/ReactDOMIDOperations.js 996 bytes {0} [built]
  [167] ./~/react/lib/ReactDOMComponent.js 38.9 kB {0} [built]
  [168] ./~/react/lib/AutoFocusUtils.js 633 bytes {0} [built]
  [169] ./~/fbjs/lib/focusNode.js 704 bytes {0} [built]
  [170] ./~/react/lib/CSSPropertyOperations.js 6.85 kB {0} [built]
  [171] ./~/react/lib/CSSProperty.js 3.69 kB {0} [built]
  [172] ./~/fbjs/lib/camelizeStyleName.js 1 kB {0} [built]
  [173] ./~/fbjs/lib/camelize.js 708 bytes {0} [built]
  [174] ./~/react/lib/dangerousStyleValue.js 3.06 kB {0} [built]
  [175] ./~/fbjs/lib/hyphenateStyleName.js 974 bytes {0} [built]
  [176] ./~/fbjs/lib/hyphenate.js 800 bytes {0} [built]
  [177] ./~/fbjs/lib/memoizeStringOnly.js 698 bytes {0} [built]
  [178] ./~/react/lib/DOMPropertyOperations.js 7.41 kB {0} [built]
  [179] ./~/react/lib/quoteAttributeValueForBrowser.js 749 bytes {0} [built]
  [180] ./~/react/lib/ReactBrowserEventEmitter.js 12.5 kB {0} [built]
  [181] ./~/react/lib/ReactEventEmitterMixin.js 1 kB {0} [built]
  [182] ./~/react/lib/getVendorPrefixedEventName.js 2.92 kB {0} [built]
  [183] ./~/react/lib/ReactDOMButton.js 634 bytes {0} [built]
  [184] ./~/react/lib/DisabledInputUtils.js 1.16 kB {0} [built]
  [185] ./~/react/lib/ReactDOMInput.js 12.1 kB {0} [built]
  [186] ./~/react/lib/LinkedValueUtils.js 5.28 kB {0} [built]
  [187] ./~/react/lib/ReactDOMOption.js 3.73 kB {0} [built]
  [188] ./~/react/lib/ReactDOMSelect.js 6.94 kB {0} [built]
  [189] ./~/react/lib/ReactDOMTextarea.js 6.36 kB {0} [built]
  [190] ./~/react/lib/ReactMultiChild.js 14.8 kB {0} [built]
  [191] ./~/react/lib/ReactComponentEnvironment.js 1.34 kB {0} [built]
  [192] ./~/react/lib/ReactInstanceMap.js 1.26 kB {0} [built]
  [193] ./~/react/lib/ReactChildReconciler.js 6.13 kB {0} [built]
  [194] ./~/react/lib/instantiateReactComponent.js 4.81 kB {0} [built]
  [195] ./~/react/lib/ReactCompositeComponent.js 36.7 kB {0} [built]
  [196] ./~/react/lib/ReactNodeTypes.js 1.06 kB {0} [built]
  [197] ./~/fbjs/lib/shallowEqual.js 1.66 kB {0} [built]
  [198] ./~/react/lib/shouldUpdateReactComponent.js 1.45 kB {0} [built]
  [199] ./~/react/lib/ReactEmptyComponent.js 743 bytes {0} [built]
  [200] ./~/react/lib/ReactHostComponent.js 2.42 kB {0} [built]
  [201] ./~/react/lib/flattenChildren.js 2.79 kB {0} [built]
  [202] ./~/react/lib/ReactServerRenderingTransaction.js 2.35 kB {0} [built]
  [203] ./~/react/lib/ReactServerUpdateQueue.js 4.95 kB {0} [built]
  [204] ./~/react/lib/ReactUpdateQueue.js 9.03 kB {0} [built]
  [205] ./~/react/lib/validateDOMNesting.js 13.1 kB {0} [built]
  [206] ./~/react/lib/ReactDOMEmptyComponent.js 1.94 kB {0} [built]
  [207] ./~/react/lib/ReactDOMTreeTraversal.js 3.74 kB {0} [built]
  [208] ./~/react/lib/ReactDOMTextComponent.js 5.84 kB {0} [built]
  [209] ./~/react/lib/ReactDefaultBatchingStrategy.js 1.92 kB {0} [built]
  [210] ./~/react/lib/ReactEventListener.js 5.38 kB {0} [built]
  [211] ./~/fbjs/lib/EventListener.js 2.67 kB {0} [built]
  [212] ./~/fbjs/lib/getUnboundedScrollPosition.js 1.05 kB {0} [built]
  [213] ./~/react/lib/ReactInjection.js 1.31 kB {0} [built]
  [214] ./~/react/lib/ReactReconcileTransaction.js 5.31 kB {0} [built]
  [215] ./~/react/lib/ReactInputSelection.js 4.31 kB {0} [built]
  [216] ./~/react/lib/ReactDOMSelection.js 6.81 kB {0} [built]
  [217] ./~/react/lib/getNodeForCharacterOffset.js 1.66 kB {0} [built]
  [218] ./~/fbjs/lib/containsNode.js 1.05 kB {0} [built]
  [219] ./~/fbjs/lib/isTextNode.js 605 bytes {0} [built]
  [220] ./~/fbjs/lib/isNode.js 693 bytes {0} [built]
  [221] ./~/fbjs/lib/getActiveElement.js 895 bytes {0} [built]
  [222] ./~/react/lib/SVGDOMPropertyConfig.js 7.36 kB {0} [built]
  [223] ./~/react/lib/SelectEventPlugin.js 6.49 kB {0} [built]
  [224] ./~/react/lib/SimpleEventPlugin.js 18.9 kB {0} [built]
  [225] ./~/react/lib/SyntheticAnimationEvent.js 1.25 kB {0} [built]
  [226] ./~/react/lib/SyntheticClipboardEvent.js 1.21 kB {0} [built]
  [227] ./~/react/lib/SyntheticFocusEvent.js 1.1 kB {0} [built]
  [228] ./~/react/lib/SyntheticKeyboardEvent.js 2.75 kB {0} [built]
  [229] ./~/react/lib/getEventCharCode.js 1.54 kB {0} [built]
  [230] ./~/react/lib/getEventKey.js 2.9 kB {0} [built]
  [231] ./~/react/lib/SyntheticDragEvent.js 1.11 kB {0} [built]
  [232] ./~/react/lib/SyntheticTouchEvent.js 1.32 kB {0} [built]
  [233] ./~/react/lib/SyntheticTransitionEvent.js 1.27 kB {0} [built]
  [234] ./~/react/lib/SyntheticWheelEvent.js 1.98 kB {0} [built]
  [235] ./~/react/lib/ReactMount.js 25.5 kB {0} [built]
  [236] ./~/react/lib/ReactDOMContainerInfo.js 1.01 kB {0} [built]
  [237] ./~/react/lib/ReactDOMFeatureFlags.js 460 bytes {0} [built]
  [238] ./~/react/lib/ReactMarkupChecksum.js 1.51 kB {0} [built]
  [239] ./~/react/lib/adler32.js 1.22 kB {0} [built]
  [240] ./~/react/lib/findDOMNode.js 2.49 kB {0} [built]
  [241] ./~/react/lib/getHostComponentFromComposite.js 789 bytes {0} [built]
  [242] ./~/react/lib/renderSubtreeIntoContainer.js 466 bytes {0} [built]
  [243] ./~/react/lib/ReactDOMUnknownPropertyHook.js 4.36 kB {0} [built]
  [244] ./~/react/lib/ReactDOMNullInputValuePropHook.js 1.41 kB {0} [built]
  [245] ./~/mobx/lib/mobx.js 102 kB {0} [built]
  [246] ./~/mobx-react/index.js 13.9 kB {0} [built]
  [247] ./~/mobx-react-devtools/index.js 41.2 kB {0} [built]
webpack: bundle is now VALID.
```

Is there more to it?

**Comment by dbaeumer** [comment]
I use node 6.5.0.

**Comment by JabX** [comment]
This is what I get
```
    at Parser.pp$7.readToken (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:2477:17)                                                                   
    at Parser.pp$7.nextToken (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:2468:15)                                                                   
    at Parser.pp$7.next (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:2413:10)                                                                        
    at Parser.pp.eat (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:536:12)                                                                            
    at Parser.pp.expect (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:597:10)                                                                         
    at Parser.pp$1.parseClass (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:1087:10)                                                                  
    at Parser.pp$1.parseStatement (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:697:19)                                                               
    at Parser.pp$1.parseTopLevel (C:\Users\dfrikha\Desktop\mobx-react-typescript-boilerplate\node_modules\acorn\dist\acorn.js:638:25)                                                                
 @ multi main
```

**Comment by JabX** [comment]
That might not be the best idea I had, but here is a gif of what I do:
![loader](https://cloud.githubusercontent.com/assets/3266897/18176994/636eae54-7078-11e6-808d-09bf029f17dc.gif)

**Comment by JabX** [comment]
Well obviously I had the problem with every Node 6 version until 6.5 which is the first release that works (I did the video on 6.3.1 and I just installed 6.5).

So I guess that's fine.
