### ISSUE TITLE
Help needed : Cannot open Visual Studio code on Centos 7.3 machine : Unable to write program user data

### ISSUE THREAD

**Issue by kniyogi** [microsoft/vscode#111918]
I am trying to open Visual Studio Code (I tried versions 1.39.2 as well as 1.51.1) on a CentOS 7.3 machine on which I do not have root privileges. I am using the following command line options :

./VSCode-linux-x64/bin/code --user-data-dir my_dir -verbose

However, in spite of using my own writable directory (my_dir), VS Code opens a error dialog saying : "Unable to write program User data. Please make sure following directories are writeable :"

$my_path/my_dir 
$my_home_dir/.vscode/extensions
**/run/user/31848**
Of these directories, the first two have write permissions, but I do not have access to /run on this machine. It looks like VS Code needs access to this directory to write some .socket files.

 Is this expected behavior ? Are there any workarounds ?

I also get the following error message once I close the dialog box :

[main 2020-12-04T21:31:30.942Z] Error: listen EACCES /run/user/31848/vscode-08e0415b-1.39.2-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1432:5)
    at Promise (/depotbld/RHEL7.0/VS-Code/VS-Code-1.39.2/resources/app/out/vs/code/electron-main/main.js:189:883)
    at new Promise (<anonymous>)
    at Object.t.serve (/depotbld/RHEL7.0/VS-Code/VS-Code-1.39.2/resources/app/out/vs/code/electron-main/main.js:189:820)
    at Object.doStartup (/depotbld/RHEL7.0/VS-Code/VS-Code-1.39.2/resources/app/out/vs/code/electron-main/main.js:536:523)
    at i.invokeFunction (/depotbld/RHEL7.0/VS-Code/VS-Code-1.39.2/resources/app/out/vs/code/electron-main/main.js:534:927)
    at h.invokeFunction (/depotbld/RHEL7.0/VS-Code/VS-Code-1.39.2/resources/app/out/vs/code/electron-main/main.js:251:263)
    at Object.startup (/depotbld/RHEL7.0/VS-Code/VS-Code-1.39.2/resources/app/out/vs/code/electron-main/main.js:534:763)

![image](https://user-images.githubusercontent.com/164441/101228200-7f3db980-364f-11eb-9629-159a6695edf7.png)

**Comment by joaomoreno** [comment]
You can change that directory with the `XDG_RUNTIME_DIR` environment:

```
XDG_RUNTIME_DIR=my-runtime-dir ./VSCode-linux-x64/bin/code --user-data-dir my_dir -verbose
```
