### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by piotr-kwiatek** [microsoft/vscode#112497]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105102:161)
    at resolveModuleNamesWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105340:26)
    at resolveModuleNamesReusingOldState (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105530:19)
    at processImportedModules (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106941:35)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106713:17)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105207:60
    at Object.forEach (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at Object.createProgram (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105207:16)
    at synchronizeHostData (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146570:26)
    at Proxy.getProgram (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146662:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151524:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151457:42)
    at ConfiguredProject.updateGraph (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152412:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154141:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155045:44)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155385:97
    at Object.flatMap (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155385:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156403:46)
    at c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158276:88
    at IOSession.Session.executeWithRequestId (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158267:28)
    at IOSession.Session.executeCommand (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158276:33)
    at IOSession.Session.onMessage (c:\Users\Ryzen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158300:35)
```

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.95GB (7.66GB free)|
|Process Argv|--crash-reporter-id e5d69b3a-789d-4376-a1ec-58b0e5408e07|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
vscode-deno|den|2.3.3
prettier-vscode|esb|5.8.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
vstry914:30236575
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by mjbvz** [comment]
Also does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
