### ISSUE TITLE
General build flakiness

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#112464]
Here I am trying to collect various failed builds that were not caused by our unit tests or integration tests:

####  `yarn electron x64`:
* [`1549639238`](https://github.com/microsoft/vscode/runs/1549639238) failed on Windows:
```
[electron] internal/streams/legacy.js:61
[electron]       throw er; // Unhandled stream error in pipe.
[electron]       ^
[electron] 
[electron] Error: end of central directory record signature not found
[electron]     at D:\a\vscode\vscode\node_modules\gulp-vinyl-zip\node_modules\yauzl\index.js:183:14
[electron]     at D:\a\vscode\vscode\node_modules\gulp-vinyl-zip\node_modules\yauzl\index.js:622:5
[electron]     at D:\a\vscode\vscode\node_modules\fd-slicer\index.js:32:7
[electron]     at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
[electron] error Command failed with exit code 1.
```

#### `yarn`
* [`1549600452`](https://github.com/microsoft/vscode/runs/1549600452) failed on macOS
* [`1549622385`](https://github.com/microsoft/vscode/runs/1549622385) failed on macOS
* [`1549543890`](https://github.com/microsoft/vscode/runs/1549543890) failed on macOS
* [`1549604304`](https://github.com/microsoft/vscode/runs/1549604304) failed on macOS
* [`1549605627`](https://github.com/microsoft/vscode/runs/1549605627) failed on macOS
* [`1550107170`](https://github.com/microsoft/vscode/runs/1550107170) failed on macOS
```
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/date-fns/-/date-fns-2.14.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/vscode/vscode/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by alexdima** [comment]
Closing since now we open new issues directly
