### ISSUE TITLE
SCM panel doesn't show git conflicts list of files

### ISSUE THREAD

**Issue by maltaesousa** [microsoft/vscode#112537]
Issue Type: <b>Bug</b>

This bug happens on version: 1.51.2 and Insiders 1.53.0. Version 1.51.1 works fine.

In a project with git enabled:
1. Do some edits to a file
2. Checkout to a new branch commit, and push to a remote branch
3. Checkout back to master
4. Edit the same file edited before in order to have confilct
5. git pull the previous remote branch
6. SCM button on Side Bar shows the notification number of files but list of changed files remains empty

Console errors:
```
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1780   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'c:\Projects\geoportal\docker\.vscode'
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4584 [[object Object]]Should never happen
$onExtensionRuntimeError @ /C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4584
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4584 Error: Should never happen
	at A.getRightResource (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:72928)
	at A.getResources (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:72210)
	at C.get resources (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:64222)
	at C.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:23851)
	at C.get leftUri [as leftUri] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:64053)
	at A.resolveChangeCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:71760)
	at A.resolveDefaultCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:71556)
	at C.get command [as command] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:64149)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:888
	at Array.map (<anonymous>)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:670
	at Array.map (<anonymous>)
	at w._takeResourceStateSnapshot (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:643)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:828:975
	at Set.forEach (<anonymous>)
	at y.eventuallyUpdateResourceStates (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:828:953)
	at Timeout._onTimeout (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:8:779)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
$onExtensionRuntimeError @ /C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4584
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/96b426ef1da0f0a51ce9ef1931cd1fd2322547e4/node_modules/windows-process-tree/lib/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

VS Code version: Code - Insiders 1.53.0-insider (96b426ef1da0f0a51ce9ef1931cd1fd2322547e4, 2020-12-14T05:59:27.649Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz (8 x 3504)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (11.64GB free)|
|Process Argv|--crash-reporter-id f6ad055e-8037-4edc-9ab8-e090701f2d28|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by fspoettel** [comment]
possibly related to #112713 

seeing the same, seems to be related to conflicts of type `CONFLICT (rename/delete)`. Once I resolved that conflicts and added that file to the merge index, the SCM panel showed all files again.

**Comment by rbaras** [comment]
@fspoettel Same issue here. I think you're right with the type of conflict causing the issue.

**Comment by infinnie** [comment]
Temporary solution:
https://github.com/microsoft/vscode/issues/112717#issuecomment-749321371

Corresponding Git blame:
https://github.com/microsoft/vscode/blame/0c947cb4ee4a35f04aa6c5117a9727be35b3c828/extensions/git/src/repository.ts#L91

**Comment by eamodio** [comment]
@joaomoreno You know more about these changes than me -- does the spirit of this PR look like the right direction?

**Comment by joaomoreno** [comment]
Sounds good, never thought about this case.

**Comment by wottery** [comment]
How long will it take to fix this bug?

**Comment by maltaesousa** [comment]
> 
> 
> How long will it take to fix this bug?

They already fixed it (thanks to them) and it's already in master. You can download VS Code Insiders or wait until next release that probable [will come out February 3rd](https://github.com/microsoft/vscode/issues/114896).

**Comment by infinnie** [comment]
> How long will it take to fix this bug?

That’s a long time to wait!
