### ISSUE TITLE
potential listener LEAK detected `renderActivityCount `

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#112603]
Saw this while selfhosting

```
Version: 1.53.0-insider (user setup)
Commit: f3e95ede9e4b9818c29a5bca3564d6fd162fb210
Date: 2020-12-15T08:23:08.890Z
Electron: 11.0.5
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042
```

```
[847] potential listener LEAK detected, having 703 listeners already. MOST frequent listener (468):
check @ event.ts:452
event.ts:453     at file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:95:312
    at Object.onFirstListenerAdd (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:95:452)
    at _event._event (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:98:809)
    at new g (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5050:627)
    at d._createInstance (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1761:671)
    at d.createInstance (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1761:92)
    at p.showViewActivity (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5051:824)
    at f.renderActivityCount (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6118:568)
    at file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6117:86
    at file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:96:82
    at c.fire (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:99:696)
    at p.$spliceGroupResourceStates (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4493:757)
    at m.$spliceResourceStates (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4495:914)
    at p._doInvokeHandler (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4529:202)
    at p._invokeHandler (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4528:901)
    at p._receiveRequest (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4527:554)
    at p._receiveOneMessage (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4526:385)
    at file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4524:535
    at c.fire (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:99:696)
    at fire (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:447:356)
    at t.PersistentProtocol._receiveMessage (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:452:525)
    at file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:449:519
    at c.fire (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:99:696)
    at g.acceptChunk (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:444:789)
    at file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:444:141
    at Socket.t (file:///C:/Alex/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:454:389)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
check @ event.ts:453

```

**Comment by joaomoreno** [comment]
Great catch, this was a misuse of `MutableDisposable`.
