### ISSUE TITLE
Timeout for SSH connetion even though SSH connects successfully

### ISSUE THREAD

**Issue by torkelrogstad** [microsoft/vscode#112684]
- VSCode Version: 1.52.0
- OS Version: macOS 11.0.1

Does this issue occur when all extensions are disabled?: Yes - I've tried disabling all extensions except the "Remote - SSH" extension

I can't connect to a SSH server due to a timeout issue, even though it appears the SSH connection itself is successfull.

1. Remote-SSH: Connect to host...
2. Choose correct host in the dropdown (which is a host I'm able to SSH into normally)
3. Connection times out, even though I get the Ubuntu greeting banner: 
```
[22:18:12.069] Log Level: 1
[22:18:12.072] remote-ssh@0.62.0
[22:18:12.072] darwin x64
[22:18:12.073] SSH Resolver called for "ssh-remote+torkel-desktop", attempt 1
[22:18:12.074] "remote.SSH.useLocalServer": true
[22:18:12.074] "remote.SSH.sshPath": undefined
[22:18:12.074] "remote.SSH.sshConfigurationFile": undefined
[22:18:12.075] "remote.SSH.useFlock": true
[22:18:12.075] "remote.SSH.lockfilesInTmp": false
[22:18:12.075] "remote.SSH.localServerDownload": auto
[22:18:12.075] "remote.SSH.remoteServerListenOnSocket": false
[22:18:12.075] "remote.SSH.showLoginTerminal": true
[22:18:12.076] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[22:18:12.076] SSH Resolver called for host: torkel-desktop
[22:18:12.076] Setting up SSH remote "torkel-desktop"
[22:18:12.080] Acquiring local install lock: /var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-remote-ssh-torkel-desktop-install.lock
[22:18:12.092] Looking for existing server data file at /Users/torkel/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-torkel-desktop-940b5f4bb5fa47866a54529ed759d95d09ee80be-0.62.0/data.json
[22:18:12.093] Using commit id "940b5f4bb5fa47866a54529ed759d95d09ee80be" and quality "stable" for server
[22:18:12.099] Install and start server if needed
[22:18:12.104] Checking ssh with "ssh -V"
[22:18:12.158] > OpenSSH_8.1p1, LibreSSL 2.7.3

[22:18:12.180] askpass server listening on /var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-ssh-askpass-9eab0d584695ad801f7d4b945054477e43492017.sock
[22:18:12.181] Spawning local server with {"ipcHandlePath":"/var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-ssh-askpass-34a724569dcdf2562cdbf77006c2c33c3273957a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52018","-o","ConnectTimeout=60","torkel-desktop"],"dataFilePath":"/Users/torkel/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-torkel-desktop-940b5f4bb5fa47866a54529ed759d95d09ee80be-0.62.0/data.json"}
[22:18:12.181] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-ssh-askpass-9eab0d584695ad801f7d4b945054477e43492017.sock"}
[22:18:12.185] Spawned 33459
[22:18:12.392] > local-server> Spawned ssh: 33460
[22:18:12.396] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[22:18:12.396] stderr> debug1: Reading configuration data /Users/torkel/.ssh/config
--- some logs omitted, don't want to leak info about my SSH keys
[22:18:12.893] stderr> debug1: Sending environment.
[22:18:12.894] stderr> debug1: Sending env LC_ALL = en_US.utf8
[22:18:12.897] > Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-53-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 21 updates can be installed immediately.
> 8 of these updates are security updates.
> To see these additional updates run: apt list --upgradable
> 
> *** System restart required ***
[22:19:14.190] Terminating local server
[22:19:14.197] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64405)
	at Timeout._onTimeout (/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:277390)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[22:19:14.199] Local server exit: 15
[22:19:14.201] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Timeout","exitCodeLabel":"","osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1"},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":62119,"timing.preSshTime":108}}
```

**Comment by roblourens** [comment]
Your host is not running the script we sent it. Can you see whether it works if you disable the setting `remote.SSH.useLocalServer`?
