### ISSUE TITLE
Error: localExtHost EXISTS already

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112708]
I ran out of sources and opened a workspace which I then "File > Save Workspace As". This restarts the extension host:

```
[41159:1217/081223.129853:INFO:CONSOLE(144)] "%c  ERR color: #f33 localExtHost EXISTS already: Error: localExtHost EXISTS already
    at PerfMarks.setMarks (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/timer/browser/timerService.js:25:23)
    at TimerService.setPerformanceMarks (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/timer/browser/timerService.js:89:25)
    at MainThreadExtensionService.$setPerformanceMarks (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadExtensionService.js:114:36)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:341:27)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:326:45)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:253:32)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:181:26)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:65:52
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:456:38)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:651:41)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:510:83
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:456:38)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:158:61
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:17:40)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js (144)
```

**Comment by jrieken** [comment]
Hm, fair point.. I can list the restriction of those things being enforced to be uniquely named.
