### ISSUE TITLE
Smoke test do not run anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112707]
This looks like a compile issue to me (https://dev.azure.com/monacotools/Monaco/_build/results?buildId=97498&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=18)

```
$ cd test/smoke && node test/index.js --build '/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app'
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/Users/runner/work/1/s/test/smoke/out/main.js'
Require stack:
- /Users/runner/work/1/s/test/smoke/node_modules/mocha/lib/mocha.js
- /Users/runner/work/1/s/test/smoke/node_modules/mocha/index.js
- /Users/runner/work/1/s/test/smoke/test/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/runner/work/1/s/test/smoke/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/runner/work/1/s/test/smoke/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/Users/runner/work/1/s/test/smoke/node_modules/mocha/lib/mocha.js:809:10)
    at Object.<anonymous> (/Users/runner/work/1/s/test/smoke/test/index.js:38:7)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/runner/work/1/s/test/smoke/node_modules/mocha/lib/mocha.js',
    '/Users/runner/work/1/s/test/smoke/node_modules/mocha/index.js',
    '/Users/runner/work/1/s/test/smoke/test/index.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/commit/6d683afb84ff8164465154ce5a4efb7a80193d88
