### ISSUE TITLE
Flaky Test: Markdown Document links -Should navigate to markdown file

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#112834]
See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=97883&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb&l=752

```
  111 passing (3s)
  1 failing
  1) Markdown Document links
       Should navigate to markdown file:
     TypeError: Cannot read property 'target' of undefined
      at executeLink (extensions/markdown-language-features/src/test/documentLink.test.ts:142:50)
      at Context.<anonymous> (extensions/markdown-language-features/src/test/documentLink.test.ts:31:9)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by alexdima** [comment]
Just happened again https://dev.azure.com/monacotools/Monaco/_build/results?buildId=98219&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb&l=750

**Comment by alexdima** [comment]
Saw it again also on macOS https://dev.azure.com/monacotools/Monaco/_build/results?buildId=98698&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=749
```
  111 passing (4s)
  1 failing
  1) Markdown Document links
       Should navigate to markdown file:
     TypeError: Cannot read property 'target' of undefined
      at executeLink (extensions/markdown-language-features/src/test/documentLink.test.ts:142:50)
      at Context.<anonymous> (extensions/markdown-language-features/src/test/documentLink.test.ts:31:9)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by alexdima** [comment]
This just happened again -- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=98810&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=751

```
  111 passing (4s)
  1 failing
  1) Markdown Document links
       Should navigate to markdown file:
     TypeError: Cannot read property 'target' of undefined
      at executeLink (extensions/markdown-language-features/src/test/documentLink.test.ts:142:50)
      at Context.<anonymous> (extensions/markdown-language-features/src/test/documentLink.test.ts:31:9)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by alexdima** [comment]
After getting a bit tired of seeing this test fail, I can see that there is an assumption being made which does not hold: the test executes before the markdown extension gets activated, so sometimes the `vscode.executeLinkProvider` command is executed even before the markdown link provider is registered. I will just push a fix for you.
