### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by Victor1890** [microsoft/vscode#113208]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.0-dev.20201211

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at Object.releaseDocumentWithKey (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:121573:35)
    at Object.onReleaseOldSourceFile (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:147729:34)
    at Object.createProgram (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:105779:26)
    at synchronizeHostData (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:147697:26)
    at Proxy.getProgram (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:147789:13)
    at InferredProject.Project.updateGraphWorker (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:152658:53)
    at InferredProject.Project.updateGraph (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:152591:42)
    at updateProjectIfDirty (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:154069:45)
    at Array.forEach (<anonymous>)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:156308:41)
    at /home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:156594:97
    at Object.flatMap (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:156594:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:157636:46)
    at /home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:159510:88
    at IOSession.Session.executeWithRequestId (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:159501:28)
    at IOSession.Session.executeCommand (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:159510:33)
    at IOSession.Session.onMessage (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:159536:35)
    at Interface.<anonymous> (/home/victor1890/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20201211/node_modules/typescript/lib/tsserver.js:162178:31)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz (4 x 2666)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|7, 4, 3|
|Memory (System)|3.74GB (0.32GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 8f9495f2-0f34-4e25-b846-61cce31fe0c9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-deno|den|2.3.3
prettier-vscode|esb|5.8.0
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
vscode-typescript-next|ms-|4.2.20201219
material-icon-theme|PKi|4.4.0
java|red|0.73.0
LiveServer|rit|5.6.1
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0
material-theme|zhu|3.9.12

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459cf:30237188

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically Deno
