### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by coinmaster4you** [microsoft/vscode#113749]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.0-dev.20210103

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110373:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110408:29)
    at Map.forEach (<anonymous>)
    at clearPerDirectoryResolutions (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110145:50)
    at Object.finishCachingPerDirectoryResolution (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110150:13)
    at InferredProject.Project.updateGraphWorker (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:153179:38)
    at InferredProject.Project.updateGraph (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:153110:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:155276:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:156839:26)
    at /home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:157113:97
    at Object.flatMap (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:157113:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:158168:46)
    at /home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160051:88
    at IOSession.Session.executeWithRequestId (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160042:28)
    at IOSession.Session.executeCommand (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160051:33)
    at IOSession.Session.onMessage (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160077:35)
    at Interface.<anonymous> (/home/milcunicorn/.vscode/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:162729:31)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 4.19.0-13-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (8.65GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 92cce7d5-8f22-4dfe-8833-ab78d0cc0b46|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
pug|ama|1.0.1
vscode-deno|den|2.3.3
vscode-language-babel|mgm|0.0.30
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vscode-typescript-next|ms-|4.2.20210103
vscode-w3cvalidation|Umo|2.8.0
jinja|who|0.0.8
eno|Wsc|2.3.53

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
vstry244cf:30236574
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt859:30239450
vsjup459cf:30237188

```

</details>

**Comment by mjbvz** [comment]
Likely caused by the deno extension. Do you see this when deno is disabled?

**Comment by coinmaster4you** [comment]
found a way round it. No was not problem without deno

**Comment by mjbvz** [comment]
What was the issue?
