### ISSUE TITLE
Cannot read property 'getId' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11373]
Seeing this output during our integration tests on Linux (e.g. https://travis-ci.org/Microsoft/vscode/jobs/156744953#L4115)

```
[5909:0901/084734:INFO:CONSOLE(245)] "Cannot read property 'getId' of null: TypeError: Cannot read property 'getId' of null
    at file:////home/travis/build/Microsoft/vscode/out/vs/workbench/services/progress/browser/progressService.js:32:117
    at CallbackList.invoke (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/event.js:84:40)
    at file:////home/travis/build/Microsoft/vscode/out/vs/workbench/browser/parts/compositePart.js:94:43
    at Object.notifySuccess [as _notify] (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.state_success_notify.enter (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.define._run (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.define._completed (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at CompletePromise_ctor.CompletePromise_then [as then] (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at Object.state_waiting.enter (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:747:28)", source: file:////home/travis/build/Microsoft/vscode/out/vs/workbench/electron-browser/shell.js (245)
```

**Comment by bpasero** [comment]
I wonder if this error is related that comes right after:

```
[5909:0901/084734:INFO:CONSOLE(245)] "Cannot read property 'getContainer' of null: TypeError: Cannot read property 'getContainer' of null
    at file:////home/travis/build/Microsoft/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalService.js:186:53
    at Object.notifySuccess [as _notify] (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.state_success_notify.enter (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._Base.Class.define._run (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._Base.Class.define._completed (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at file:////home/travis/build/Microsoft/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalService.js:130:25
    at Object.notifySuccess [as _notify] (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.state_success_notify.enter (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.define._run (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.define._completed (file:////home/travis/build/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)", source: file:////home/travis/build/Microsoft/vscode/out/vs/workbench/electron-browser/shell.js (245)
```
