### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by exponent42** [microsoft/vscode#113766]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.0-dev.20210103

**Steps to reproduce crash**
1. **M1 Mac mini** Errors stems alongside Deno, installed & enabled: denoland.vscode-deno
2. "Initialising JS/TS .... Deno initialisation" via open .ts file
3. If I disabled Deno extension then this error does not occur. As soon as I enable the extension again the below error re-occurs

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110373:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110408:29)
    at Map.forEach (<anonymous>)
    at clearPerDirectoryResolutions (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110145:50)
    at Object.finishCachingPerDirectoryResolution (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:110150:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:153179:38)
    at ConfiguredProject.Project.updateGraph (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:153110:42)
    at ConfiguredProject.updateGraph (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:154075:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:155832:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:156773:44)
    at /Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:157113:97
    at Object.flatMap (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:157113:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:158168:46)
    at /Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160051:88
    at IOSession.Session.executeWithRequestId (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160042:28)
    at IOSession.Session.executeCommand (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160051:33)
    at IOSession.Session.onMessage (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:160077:35)
    at Interface.<anonymous> (/Users/nolankeenan/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.2.20210103/node_modules/typescript/lib/tsserver.js:162729:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code - Insiders 1.53.0-insider (98106c48a07d4d07f0f71b4db9b3ff156f223339, 2021-01-01T05:22:18.682Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|VirtualApple @ 2.50GHz processor (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 0ced3c74-e079-4333-b6d1-14452c99b607|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-apollo|apo|1.18.0
env-vscode|Ber|0.1.1
markdown-preview-github-styles|bie|0.1.6
vscode-tailwindcss|bra|0.5.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-clock|Com|0.0.1
postcss|css|1.0.9
vscode-deno|den|2.3.3
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.1.2
prettier-vscode|esb|5.8.0
git-project-manager|fel|1.7.1
vscode-graphql|Gra|0.3.13
gql|ide|0.2.2
vscode-react-typescript|inf|1.3.1
vscode-env|Iro|0.1.0
graphql|mqu|0.1.2
vscode-scss|mrm|0.9.0
vscode-typescript-next|ms-|4.2.20210103
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.2.0
gqlformatter|nor|1.0.0
vscode-extension-auto-import|Nuc|1.4.3
firebase-firestore-snippets|Pet|0.0.8
tsimporter|pmn|2.0.1
polacode|pnp|0.3.4
prisma|Pri|2.13.1
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.0.5
mdx|sil|0.1.0
swdc-vscode|sof|2.3.24
sass-indented|syl|1.8.13
vscode-icons|vsc|11.1.0
html-css-class-completion|Zig|1.20.0

(14 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanel:30233467

```

</details>

**Comment by mjbvz** [comment]
Please file this against the Deno extension
