### ISSUE TITLE
Keytar fails to load in Apple SI for oss

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113885]
I see this unit test failure:

```
1) Keytar
       loads and is functional:
     Error: dlopen(/Users/bpasero/Development/Microsoft/monaco/node_modules/keytar/build/Release/keytar.node, 1): no suitable image found.  Did find:
	/Users/bpasero/Development/Microsoft/monaco/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
	/Users/bpasero/Development/Microsoft/monaco/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
      at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
      at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
      at Module.load (internal/modules/cjs/loader.js:992:32)
      at Module._load (internal/modules/cjs/loader.js:885:14)
      at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
      at Module.require (internal/modules/cjs/loader.js:1032:19)
      at Module.patchedRequire [as require] (/Users/bpasero/Development/Microsoft/monaco/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
      at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by bpasero** [comment]
I wonder if this is a problem local to me or are we not running unit tests against Apple SI yet?

**Comment by deepak1556** [comment]
Its just a problem in local build because keytar uses prebuilt modules, and arm version is not available. For the product build I manually cross-compile the package https://github.com/microsoft/vscode/blob/master/build/azure-pipelines/darwin/product-build-darwin.yml#L116.


> are we not running unit tests against Apple SI yet?

Yes we are not running tests, will need to add it back.

**Comment by bpasero** [comment]
I just confirmed that a `node-gyp rebuild` fixes the unit test for me.

**Comment by bpasero** [comment]
@deepak1556 I think this can be closed now with Electron 12?

**Comment by deepak1556** [comment]
Yup this is fixed with https://github.com/microsoft/vscode/pull/120673, thanks for tracking.
