### ISSUE TITLE
Bogous auth provider can break accounts menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#113816]
* implement an auth provider 
* do _not_ register it in package.json
* run and select the accounts menu
* :bug: nothing happens, there is an error on the console

```
ERR No authentication provider 'autho' has been declared.: Error: No authentication provider 'autho' has been declared.
    at AuthenticationService.getLabel (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/authentication/browser/authenticationService.js:320:23)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/activitybar/activitybarActions.js:201:72
    at Array.forEach (<anonymous>)
    at AccountsActivityActionViewItem.resolveActions (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/activitybar/activitybarActions.js:200:20)
    at async AccountsActivityActionViewItem.showContextMenu (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/activitybar/activitybarActions.js:107:29)
```

**Comment by RMacfarlane** [comment]
Should already be fixed with https://github.com/microsoft/vscode/commit/a5a8392079eb08d5166e19f866520bb212166459#diff-a4ee698aba71433019564e70122151ba1d84efb134eacb1c0d795e39274a6d8a
