### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by SimiS22** [microsoft/vscode#113984]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at acquireOrUpdateDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120712:30)
    at Object.updateDocumentWithKey (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120703:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146648:49)
    at tryReuseStructureFromOldProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:105641:28)
    at Object.createProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:105167:29)
    at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146570:26)
    at Proxy.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146662:13)
    at Proxy.proxy.<computed> (/Users/chintu.mohandas/.vscode-insiders/extensions/asvetliakov.snapshot-tools-0.4.0/node_modules/typescript-snapshots-plugin/out/index.js:38:33)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151524:53)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151457:42)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152412:63)
    at updateProjectIfDirty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152922:45)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155050:29)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155385:97
    at Object.flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155385:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156403:46)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158276:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158267:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158276:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158300:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160510:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code - Insiders 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480, 2020-12-21T12:32:43.927Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|32.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id d4155206-9e46-4917-92af-019de4b2113f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.0
vscode-apollo|apo|1.18.0
snapshot-tools|asv|0.4.0
vscode-custom-css|be5|4.0.1
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.18.1
flutter|Dar|3.18.1
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
git-project-manager|fel|1.7.1
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
dotnet-test-explorer|for|0.7.4
vscode-mysql|for|0.4.0
gitlab-workflow|Git|3.8.0
json2ts|Gre|0.0.6
githd|hui|2.2.4
roslynator|jos|3.1.0
vscode-styled-components|jpo|1.4.1
graphql-for-vscode|kum|1.15.3
camelcasenavigation|map|1.1.3
csharp|ms-|1.23.8
remote-containers|ms-|0.154.2
vsliveshare|ms-|1.0.3375
debugger-for-chrome|msj|4.12.11
material-icon-theme|PKi|4.4.0
vscode-protolint|ple|0.5.1
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
vscode-coverage-gutters|rya|2.6.0
file-tree-generator|Shi|1.1.1
mdx|sil|0.1.0
svg-preview|Sim|2.8.3
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
quokka-vscode|Wal|1.0.335
vscode-import-cost|wix|2.13.0
vscode-proto3|zxh|0.5.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600cf:30241728
core-portspanel:30233467

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please fill in the issue template
