### ISSUE TITLE
Unit and integration tests report issues with command argument validation

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113905]
I think this is fairly new. This does not make tests fail, but shows in the console.

**Unite tests:**
```
  ExtHostLanguageFeatureCommands
[30806:0106/132127.309790:INFO:CONSOLE(167)] "Error: Invalid argument 'query' when running 'vscode.executeWorkspaceSymbolProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.309920:INFO:CONSOLE(167)] "Error: Invalid argument 'query' when running 'vscode.executeWorkspaceSymbolProvider', received: null", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.309987:INFO:CONSOLE(167)] "Error: Invalid argument 'query' when running 'vscode.executeWorkspaceSymbolProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.310047:INFO:CONSOLE(167)] "Error: Invalid argument 'query' when running 'vscode.executeWorkspaceSymbolProvider', received: true", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
    ✓ WorkspaceSymbols, invalid arguments
    ✓ WorkspaceSymbols, back and forth
    ✓ executeWorkspaceSymbolProvider should accept empty string, #39522
    ✓ executeFormatDocumentProvider, back and forth
    ✓ vscode.executeDocumentRenameProvider
[30806:0106/132127.468776:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeDefinitionProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.468899:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeDefinitionProvider', received: null", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.468969:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeDefinitionProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
    ✓ Definition, invalid arguments
[30806:0106/132127.469201:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeDefinitionProvider', received: true", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
    ✓ Definition, back and forth
    ✓ Definition Link
    ✓ Declaration, back and forth
    ✓ Declaration Link
[30806:0106/132127.607148:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeTypeDefinitionProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.607271:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeTypeDefinitionProvider', received: null", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.607341:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeTypeDefinitionProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.607411:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeTypeDefinitionProvider', received: true", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
    ✓ Type Definition, invalid arguments
    ✓ Type Definition, back and forth
    ✓ Type Definition Link
[30806:0106/132127.688132:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeImplementationProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.688225:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeImplementationProvider', received: null", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.688270:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeImplementationProvider', received: undefined", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
[30806:0106/132127.688308:INFO:CONSOLE(167)] "Error: Invalid argument 'uri' when running 'vscode.executeImplementationProvider', received: true", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostCommands.js (167)
    ✓ Implementation, invalid arguments
    ✓ Implementation, back and forth
    ✓ Implementation Definition Link
    ✓ reference search, back and forth
```

**Integration tests:**
```
  vscode API - commands
    ✓ getCommands
    ✓ command with args
    ✓ editorCommand with extra args (215ms)
Error: Invalid argument 'left' when running 'vscode.diff', received: undefined
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:106:12
    at Array.map (<anonymous>)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:104:41
    at ExtHostCommands._executeContributedCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:214:26)
    at ExtHostCommands._doExecuteCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:162:16)
    at ExtHostCommands.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:154:15)
    at Object.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHost.api.impl.ts:274:28)
    at Context.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/extensions/vscode-api-tests/src/singlefolder-tests/commands.test.ts:101:20)
    at callFn (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:364:21)
    at Test.run (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:352:5)
    at Runner.runTest (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:677:10)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:801:12
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:594:14)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:604:7
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:486:14)
    at Immediate.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:572:5)
    at processImmediate (internal/timers.js:456:21)
Error: Invalid argument 'left' when running 'vscode.diff', received: 1
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:106:12
    at Array.map (<anonymous>)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:104:41
    at ExtHostCommands._executeContributedCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:214:26)
    at ExtHostCommands._doExecuteCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:162:16)
    at ExtHostCommands.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:154:15)
    at Object.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHost.api.impl.ts:274:28)
    at Context.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/extensions/vscode-api-tests/src/singlefolder-tests/commands.test.ts:102:20)
    at callFn (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:364:21)
    at Test.run (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:352:5)
    at Runner.runTest (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:677:10)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:801:12
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:594:14)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:604:7
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:486:14)
    at Immediate.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:572:5)
    at processImmediate (internal/timers.js:456:21)
    ✓ api-command: vscode.diff (147ms)
Error: Invalid argument 'uri' when running 'vscode.open', received: undefined
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:106:12
    at Array.map (<anonymous>)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:104:41
    at ExtHostCommands._executeContributedCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:214:26)
    at ExtHostCommands._doExecuteCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:162:16)
    at ExtHostCommands.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:154:15)
    at Object.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHost.api.impl.ts:274:28)
    at Context.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/extensions/vscode-api-tests/src/singlefolder-tests/commands.test.ts:111:20)
    at callFn (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:364:21)
    at Test.run (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:352:5)
    at Runner.runTest (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:677:10)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:801:12
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:594:14)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:604:7
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:486:14)
    at Immediate.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:572:5)
    at processImmediate (internal/timers.js:456:21)
Error: Invalid argument 'columnOrOptions' when running 'vscode.open', received: true
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:106:12
    at Array.map (<anonymous>)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:104:41
    at ExtHostCommands._executeContributedCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:214:26)
    at ExtHostCommands._doExecuteCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:162:16)
    at ExtHostCommands.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostCommands.ts:154:15)
    at Object.executeCommand (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHost.api.impl.ts:274:28)
    at Context.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/extensions/vscode-api-tests/src/singlefolder-tests/commands.test.ts:112:20)
    at callFn (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:364:21)
    at Test.run (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runnable.js:352:5)
    at Runner.runTest (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:677:10)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:801:12
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:594:14)
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:604:7
    at next (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:486:14)
    at Immediate.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/lib/runner.js:572:5)
    at processImmediate (internal/timers.js:456:21)
    ✓ api-command: vscode.open (76ms)
  vscode API - configuration
```

If the integration error is expected, we have a hack to disable output for the duration of the test:

https://github.com/microsoft/vscode/blob/479971440393f87108ad93acbfaa99fa4240941b/extensions/vscode-api-tests/src/utils.ts#L63-L63

**Comment by jrieken** [comment]
Nothing new here. I fail to understand the problem here. We log those invalid invocation to the console because that's the place extension developers are looking at when developing extension

**Comment by bpasero** [comment]
Not a big deal, just thought I would report stacktraces I see when running tests. At first I thought we are missing assertions to produce test failures, but maybe in this case these errors are expected.

A while ago @alexdima and me pushed for "clean test output", meaning that tests should only print success or failure, but not other stuff.

**Comment by alexdima** [comment]
@jrieken We did an effort some time ago that we keep our output from running `scripts\test.bat` and `scripts\test-integration.bat` clean from output that looks like errors. This is helpful because CI tools like Azure Pipeline and Github Actions grep for `Error` and focus the first text with `Error`, etc. It is also helpful for us as developers when we troubleshoot a weird test failure that we don't see unrelated Error messages.

So if it is possible, I think it would be good to find out where these messages are logged and suppress during ci. I think we can use an env variable to discover this (like process.env['CI'] or another one for azure pipelines)

**Comment by jrieken** [comment]
I agree that the CI output is noisy but I think avoiding console.log isn't the right way. Isn't the problem that the test output reporter also prints onto the the console so that everything is intermixed. Can we use a different output reporter that e.g creates a file so that the CI build uses that file?

**Comment by alexdima** [comment]
The extra output is new and was not always there -- https://github.com/microsoft/vscode/commit/3ba967fd7eb97621b0e2a4fb0267b70323ffcf5f cc @connor4312 

I think this falls into the same bucket as "break on error" used to be. Kind of like the broken window theory. If we start logging stuff and stop caring about the output, it will spread like wildfire and it might become very full of garbage quickly.

@bpasero Maybe we could do like an environment variable when running tests like `VSCODE_IN_TEST` and then standardize on that and omit console.log when that is defined. I don't know, what do you think?

**Comment by bpasero** [comment]
If code triggers `console` in anyway I don't now how we could prevent this from bubbling to the console unless we overwrite `console` with our own code and ignore it if set.

I think this is not the right way forward. I like what we did in https://github.com/microsoft/vscode/blob/479971440393f87108ad93acbfaa99fa4240941b/extensions/vscode-api-tests/src/utils.ts#L63-L63 where a test explicitly disables the console based logger for the duration of the run. I fear that some console output might actually be useful for diagnosing issues so I would suggest that @connor4312 reverts the printing of the error if possible.

**Comment by connor4312** [comment]
Yes, I queried Isi about that and he mentioned he didn't know a reason why we didn't log a console on command error. I wanted to add some logging there since commands are the first thing we show to extension developers in a 'hello world' extension. Without a console log any errors thrown from inside of them lack stacktraces, which can make debugging difficult especially for people less experienced in Javascript.

In our code there is a varied mix between the log service and console logging. Imo some interaction with a/the log service to deal with this would be better, but I didn't want to make a change there as that affects around ~200 call sites for `.error()` alone.

We [already overwrite](https://github.com/microsoft/vscode/blob/6763d82fdd101cc2f88919f140c447be4e6f0197/src/bootstrap-fork.js#L171-L175) the console in bootstrap-fork, so tweaking that behavior is not unprecedented.  But of course there's the risk of omitting intended console errors.

I can revert as a quick fix but I believe we should try to arrive on a better solution for socializing errors here.

**Comment by bpasero** [comment]
First of all, I don't think we should use `console` for logging but `ILogService`. That gives us a chance to control how the output appears on the other side and is a requirement for the `withLogDisabled` to function properly.

And then, if we think this error is useful in the logs, an integration test can disable logging easily.

**Comment by connor4312** [comment]
For errors to best be displayed to any attached debugger, `console` needs to be called at some point -- it does magic that captures and make the objects available to the debugger, which allows us to inspect them after the fact: e.g. expand nested objects, evaluate methods, use it in the REPL. ([new Console](https://nodejs.org/api/console.html#console_class_console) doesn't work, it needs to be the global console)

**Comment by bpasero** [comment]
Sure, our log service typically comes with a console appender to do that:

https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/services/log/electron-browser/logService.ts#L41-L41

And here I actually realize how messages end up on the console from the CLI run:

https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/services/log/electron-browser/logService.ts#L33-L33

We have an explicit way to forward messages to the main process because otherwise no console log statement would be visible when running API tests. I think we should not change that since it is probably expected behaviour by now for all extensions.

**Comment by jrieken** [comment]
> First of all, I don't think we should use console for logging but ILogService.

Generally agree but not when it comes to extensions. When they use an API wrong they will not check the logs but the console which they are already looking at.

**Comment by bpasero** [comment]
I think I made it clear that our logger always prints to `console`. At least in the workbench core it does.

**Comment by alexdima** [comment]
>  I wanted to add some logging there since commands are the first thing we show to extension developers in a 'hello world' extension. Without a console log any errors thrown from inside of them lack stacktraces, which can make debugging difficult especially for people less experienced in Javascript.

@connor4312 What would be the steps to get the case you improved?

**Comment by connor4312** [comment]
> I think I made it clear that our logger always prints to `console`. At least in the workbench core it does.

It looks like in the extension host, calls to `logger.error` eventually end up in spdlog. We don't get anything over CDP for it so it never shows up in the Debug Console.

> What would be the steps to get the case you improved?

Ideally getting logs over to us in _some_ way would be good. The `console` APIs would work for that, though there may be other more creative (and less performant, though in debug mode it matters less) solutions. Then we can show them in the console and do our sourcemap demangling when possible.
