### ISSUE TITLE
VSCode - TypeScript language service died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by Samantha-uk** [microsoft/vscode#114107]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Occurs immediately upon opening a SSH project.

VS Code version: Code - Insiders 1.53.0-insider (ed6c343edb720d91ee0859e566c84b5687f5a9d5, 2021-01-08T10:44:29.135Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.19.0-12-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id ef901361-5ddb-4073-a63b-e5567ef38c88|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.1.16.131|
|OS|Linux x64 4.19.0-12-amd64|
|CPUs|Common KVM processor (8 x 1607)|
|Memory (System)|9.79GB (7.14GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vscode-peacock|joh|3.9.1
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.5.0
errorlens|use|3.2.4
vscode-icons|vsc|11.1.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600:30241727
core-portspanelcf:30233468

```

</details>

**Comment by Samantha-uk** [comment]
I am seeing this. in my VSCode log (Window)
```
[2021-01-10 20:01:28.305] [renderer1] [error] Could not create TS service. Service state:{"type":0}: Error: Could not create TS service. Service state:{"type":0}
	at T.service (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/typescript-language-features/dist/extension.js:1:232977)
	at T.executeImpl (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/typescript-language-features/dist/extension.js:1:240923)
	at T.execute (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/typescript-language-features/dist/extension.js:1:240526)
	at w.get fixableDiagnosticCodes (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/typescript-language-features/dist/extension.js:1:192814)
	at w.n.<computed> (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/typescript-language-features/dist/extension.js:1:32040)
	at w.getFixableDiagnosticsForContext (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/typescript-language-features/dist/extension.js:1:192669)
	at C.provideCodeActions (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/typescript-language-features/dist/extension.js:1:193315)
	at /home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:779:728
	at /home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:52:1010
	at new Promise (<anonymous>)
	at Object.t.asPromise (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:52:982)
	at P.provideCodeActions (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:779:699)
	at /home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:801:414
	at q._withAdapter (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:796:10)
	at q.$provideCodeActions (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:801:392)
	at m._doInvokeHandler (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:916:926)
	at m._invokeHandler (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:916:618)
	at m._receiveRequest (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:915:201)
	at m._receiveOneMessage (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:914:6)
	at /home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:912:136
	at l.fire (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at /home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1118:104
	at l.fire (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:238:1004)
	at /home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:235:927
	at l.fire (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at p.acceptChunk (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:231:195)
	at /home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:230:547
	at Socket.t (/home/samantha/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by Samantha-uk** [comment]
When I disable _all_ extensions (apart from Visual Studio Code Remote - SSH v0.62.0) I still see the same problem.

The problem occurs with both
VSCode 1.52.1
VSCode Version: 1.53.0-insider
