### ISSUE TITLE
CustomExecution tasks get stuck when run to quickly

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode#114177]
- VSCode Version: 1.53 Insiders
- OS Version: MacOS 10.15.7

VS Code > About details:
```
Version: 1.53.0-insider
Commit: 3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e
Date: 2021-01-11T05:12:22.156Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 19.6.0
```

When using the CustomExecution tasks API and creating a number of tasks in a short time frame occasionally the terminal backing the task will get stuck. 

Steps to Reproduce:

The following snippet used in a new TS extension reproduces this consistently for me.

```
import * as assert from 'assert';
import * as vscode from 'vscode';

class Pty implements vscode.Pseudoterminal {
  writer = new vscode.EventEmitter<string>();
  onDidWrite = this.writer.event;
  closer = new vscode.EventEmitter<number|undefined>();
  onDidClose = this.closer.event;

  constructor(readonly num: number, readonly quick: boolean) {}

  cleanup() {
    this.writer.dispose();
    this.closer.dispose();
  }

  open() {
    console.log('open called', this.num);
    this.writer.fire('starting\r\n');
    setTimeout(() => {
      this.closer.fire(this.num);
      this.cleanup();
    }, this.num * (this.quick ? 1 : 1000));
  }

  close() {
    console.log('close called', this.num);
    this.closer.fire(undefined);
    this.cleanup();
  }
}

async function runTask(num: number, quick: boolean) {
  const pty = new Pty(num, quick);
  const task = new vscode.Task(
      {type: 'task_bug', exampleProp: `hello world ${num}`},
      vscode.TaskScope.Workspace, `task bug ${num}`, 'task bug',
      new vscode.CustomExecution(
          async () => {
            console.log(`custom execution callback (${num})`);
            return pty;
          },
          ));
  vscode.tasks.executeTask(task);
  return new Promise<number|undefined>(resolve => {
    pty.onDidClose(exitCode => {
      console.log('exit called', exitCode);
      resolve(exitCode);
    });
  });
}

suite('Extension Test Suite', () => {
  test('Sample test', async () => {
    const [r1, r2, r3, r4] = await Promise.all([
      runTask(1, false), runTask(2, false), runTask(3, false), runTask(4, false)
    ]);
    assert.strictEqual(r1, 1);
    assert.strictEqual(r2, 2);
    assert.strictEqual(r3, 3);
    assert.strictEqual(r4, 4);

    const [j1, j2, j3, j4] = await Promise.all([
      runTask(1, true), runTask(2, true), runTask(3, true), runTask(4, true)
    ]);
    assert.strictEqual(j1, 1);
    assert.strictEqual(j2, 2);
    assert.strictEqual(j3, 3);
    assert.strictEqual(j4, 4);
  });
});
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ashgti** [comment]
I forgot to mention the output. If you run this from the CLI (`npm run test`) it will output:

```
  Extension Test Suite

  Extension Test Suite
custom execution callback (1)
custom execution callback (2)
custom execution callback (3)
custom execution callback (1)
custom execution callback (2)
custom execution callback (3)
custom execution callback (4)
custom execution callback (4)
open called 2
open called 3
open called 4
open called 1
open called 2
open called 3
open called 4
open called 1
(node:24386) Electron: Loading non-context-aware native module in renderer: 'customeexecution-task-bug/.vscode-test/vscode-1.52.1/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
exit called 1
exit called 1
exit called 2
exit called 2
exit called 3
exit called 3
exit called 4
exit called 4
custom execution callback (4)
open called 4
exit called 4

Unknown terminal: 4: Error: Unknown terminal: 4
    at f._getTerminalProcess (file:///<snip>/customeexecution-task-bug/.vscode-test/vscode-1.52.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5297:326)
    at f._onRequestLatency (file:///<snip>/customeexecution-task-bug/.vscode-test/vscode-1.52.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5296:792)

custom execution callback (4)
open called 4
exit called 4

    1) Sample test
  0 passing (20s)
  1 failing

  1) Extension Test Suite
       Sample test:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/harjohn/Projects/vscode-custom-execution-bug/customeexecution-task-bug/out/test/suite/extension.test.js)
  	at listOnTimeout (internal/timers.js:531:17)
  	at processTimers (internal/timers.js:475:7)
```

As far as I have been able to follow the code, it looks like the task is failing to setup the terminal correctly and throwing an exception around here: https://github.com/microsoft/vscode/blob/9d39f4e6cb7ced1165b9444c937054e22d8e7a31/src/vs/workbench/api/common/extHostTerminalService.ts#L440

**Comment by ashgti** [comment]
I've found a way to mitigate this somewhat. If you change the `runTask` helper to resolve after a small delay of the task finishing the task then the rest of the tasks run fine.

Using `setTimeout(1)` works while `setImmediate` does not. I suspect there is some synchronization race condition happening between the extension host and the main process causing the issue.

```
// This version of `runTask` does not produce the issue.
async function runTask(num: number, quick: boolean) {
  const pty = new Pty(num, quick);
  const task = new vscode.Task(
      {type: 'task_bug', exampleProp: `hello world ${num}`},
      vscode.TaskScope.Workspace, `task bug ${num}`, 'task bug',
      new vscode.CustomExecution(
          async () => {
            console.log(`custom execution callback (${num})`);
            return pty;
          },
          ));
  vscode.tasks.executeTask(task);
  return new Promise<number|undefined>(resolve => {
    pty.onDidClose(async exitCode => {
      console.log('exit called', exitCode);
      // setTimeout(1) works while setImmediate still fails.
      await new Promise(resolve => setTimeout(resolve, 1));
      resolve(exitCode);
    });
  });
}
```

**Comment by award999** [comment]
@alexr00 any idea when this will be assigned to a release? The 1ms timeout is not always enough. For our extension we have it set to 500ms and it still hangs sometimes and the only way around it is to restart VSCode completely.

**Comment by ashgti** [comment]
This no longer reproduces in 1.58 (although it did reproduce in 1.57). Not sure which change seems to have fixed it, but at least my original test example works now.

**Comment by alexr00** [comment]
@ashgti thank you for the comment! I know there have been some changes in terminal, so it's possible that resolved the issue.
