### ISSUE TITLE
After updating to VS Code Insiders 1.53, Remote SSH stopped working

### ISSUE THREAD

**Issue by Menelion** [microsoft/vscode#114211]
- VSCode Version:1.53.0-Insider, Commit: e17aea136d32fdb06d9b32184b04ccd36bb51e9c
- OS Version: Windows 10, Version 1909 (OS Build 18363.815) X64

Steps to Reproduce:

1. Update to VS Code 1.53.0.
2. Install Remote Extension Pack.
3. Try connecting to a Mac OS powered device via Remote SSH.
Expected Result: Everything should work as before.
Actual Result:

```shell
[16:09:48.678] Log Level: 2
[16:09:48.684] remote-ssh@0.62.0
[16:09:48.684] win32 x64
[16:09:48.685] SSH Resolver called for "ssh-remote+mac", attempt 1
[16:09:48.685] "remote.SSH.useLocalServer": false
[16:09:48.686] "remote.SSH.showLoginTerminal": false
[16:09:48.686] "remote.SSH.remotePlatform": {"mac":"macOS"}
[16:09:48.686] "remote.SSH.sshPath": undefined
[16:09:48.686] "remote.SSH.sshConfigurationFile": undefined
[16:09:48.686] "remote.SSH.useFlock": true
[16:09:48.686] "remote.SSH.lockfilesInTmp": false
[16:09:48.686] "remote.SSH.localServerDownload": auto
[16:09:48.686] "remote.SSH.remoteServerListenOnSocket": false
[16:09:48.687] "remote.SSH.showLoginTerminal": false
[16:09:48.687] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[16:09:48.687] SSH Resolver called for host: mac
[16:09:48.687] Setting up SSH remote "mac"
[16:09:48.703] Using commit id "e17aea136d32fdb06d9b32184b04ccd36bb51e9c" and quality "insider" for server
[16:09:48.706] Install and start server if needed
[16:09:48.711] Checking ssh with "ssh -V"
[16:09:48.800] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[16:09:48.803] Running script with connection command: ssh -T -D 53659 mac bash
[16:09:48.806] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:09:49.018] > 
[16:09:49.019] Got some output, clearing connection timeout
[16:09:49.698] > 8f7372bddf85: running
> 
[16:09:49.725] > Acquiring lock on /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d3
> 2fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb
> 06d9b32184b04ccd36bb51e9c
> \ln /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c.target /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d
> 32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fd
> b06d9b32184b04ccd36bb51e9c
> ln: /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c: File exists
> Installation already in progress...
> 8f7372bddf85: start
> exitCode==24==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 8f7372bddf85: end
> 
[16:09:49.726] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:09:49.726] Server installation process already in progress - waiting and retrying
[16:09:50.007] "install" terminal command done
[16:09:50.008] Install terminal quit with output: 
[16:09:50.732] Running script with connection command: ssh -T -D 53659 mac bash
[16:09:50.733] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:09:50.892] > 
[16:09:50.892] Got some output, clearing connection timeout
[16:09:51.545] > 8f7372bddf85: running
> 
[16:09:51.572] > Acquiring lock on /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d3
> 2fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb
> 06d9b32184b04ccd36bb51e9c
> \ln /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c.target /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d
> 32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fd
> b06d9b32184b04ccd36bb51e9c
> ln: /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c: File exists
> Installation already in progress...
> 8f7372bddf85: start
> exitCode==24==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 8f7372bddf85: end
> 
[16:09:51.572] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:09:51.573] Server installation process already in progress - waiting and retrying
[16:09:51.817] "install" terminal command done
[16:09:51.817] Install terminal quit with output: 
<...>
```

Does this issue occur when all extensions are disabled?: N/A, Remote SSH is required

**Comment by Menelion** [comment]
When trying to `rm -rf` the `bin` folder on the Mac (command-line SSH works properly) and re-launching VS Code on Windows, I got the following:

```shell
[16:22:38.760] Log Level: 2
[16:22:38.767] remote-ssh@0.62.0
[16:22:38.767] win32 x64
[16:22:38.768] SSH Resolver called for "ssh-remote+mac", attempt 1
[16:22:38.769] "remote.SSH.useLocalServer": false
[16:22:38.769] "remote.SSH.showLoginTerminal": false
[16:22:38.769] "remote.SSH.remotePlatform": {"mac":"macOS"}
[16:22:38.769] "remote.SSH.sshPath": undefined
[16:22:38.770] "remote.SSH.sshConfigurationFile": undefined
[16:22:38.770] "remote.SSH.useFlock": true
[16:22:38.770] "remote.SSH.lockfilesInTmp": false
[16:22:38.770] "remote.SSH.localServerDownload": auto
[16:22:38.770] "remote.SSH.remoteServerListenOnSocket": false
[16:22:38.770] "remote.SSH.showLoginTerminal": false
[16:22:38.771] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[16:22:38.771] SSH Resolver called for host: mac
[16:22:38.771] Setting up SSH remote "mac"
[16:22:38.833] Using commit id "e17aea136d32fdb06d9b32184b04ccd36bb51e9c" and quality "insider" for server
[16:22:38.838] Install and start server if needed
[16:22:38.841] Checking ssh with "ssh -V"
[16:22:38.917] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[16:22:38.920] Running script with connection command: ssh -T -D 53864 mac bash
[16:22:38.923] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:22:39.115] > 
[16:22:39.116] Got some output, clearing connection timeout
[16:22:39.806] > b4d2d5c8d53e: running
> Acquiring lock on /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d3
> 2fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb
> 06d9b32184b04ccd36bb51e9c
> \ln /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b32184
> b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fdb06d9b32184b04c
> cd36bb51e9c.target /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d
> 32fdb06d9b32184b04ccd36bb51e9c/vscode-remote-lock.andrepolykanine.e17aea136d32fd
> b06d9b32184b04ccd36bb51e9c
> 
[16:22:39.831] > Installing to /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb
> 06d9b32184b04ccd36bb51e9c...
> b4d2d5c8d53e%%1%%
> Downloading with curl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[16:22:39.931] > 100     9  100     9    0     0    104      0 --:--:-- --:--:-- --:--:--   104
> curl download failed
> 404
> printenv:
>     SHELL=/bin/zsh
>     TMPDIR=/var/folders/5g/400zzz211k52lld4t6q06r4r0000gn/T/
>     SSH_CLIENT=172.19.201.2 53866 22
>     USER=andrepolykanine
>     VSCODE_AGENT_FOLDER=/Users/andrepolykanine/.vscode-server-insiders
>     MAIL=/var/mail/andrepolykanine
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     PWD=/Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06d9b3
> 2184b04ccd36bb51e9c
>     SHLVL=1
>     HOME=/Users/andrepolykanine
>     LOGNAME=andrepolykanine
>     SSH_CONNECTION=172.19.201.2 53866 172.19.196.22 22
>     _=/usr/bin/printenv
>     OLDPWD=/Users/andrepolykanine
> Trigger local server download
> b4d2d5c8d53e:trigger_server_download
> platform==macOS==
> vscodeArch==x64==
> destFolder==/Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06
> d9b32184b04ccd36bb51e9c==
> b4d2d5c8d53e:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /Users/andrepolykanine/.vscode-server-insiders/bin/e17aea136d32fdb06
> d9b32184b04ccd36bb51e9c/vscode-scp-done.flag and vscode-server.tar.gz to exist
> 
[16:22:39.932] Got malformed request to download on client, invalid platform: macOS
[16:22:39.935] Resolver error: Error: Client-side server download failed
	at Function.Create (c:\Users\andre.polykanine\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:64276)
	at c:\Users\andre.polykanine\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:134822
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async I (c:\Users\andre.polykanine\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:310885)
	at async c:\Users\andre.polykanine\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:309029
	at async Object.t.withShowDetailsEvent (c:\Users\andre.polykanine\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:403706)
	at async Object.t.resolve (c:\Users\andre.polykanine\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:312426)
	at async c:\Users\andre.polykanine\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:127:110280
[16:22:39.940] ------
```

But the `vscode-server.tar.gz` does exist on the Mac now.

Any help is hugely appreciated as this is essential for my work. I'm a screen reader user, so working on Windows with an SSH connection to the Mac is the most convenient way for me to be as performant as my other colleagues. Thanks.

**Comment by neoswallow** [comment]
I'm having the same issue with same build.
Is there a way to download previous build?
