### ISSUE TITLE
the program is not syncing the java extension

### ISSUE THREAD

**Issue by jonathans09081996** [microsoft/vscode#114243]
[2021-01-13 00:37:18.516] [main] [info] update#setState idle
[2021-01-13 00:37:48.516] [main] [info] update#setState checking for updates
[2021-01-13 00:37:49.042] [main] [error] Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
[2021-01-13 00:37:49.042] [main] [info] update#setState idle

[2021-01-13 00:37:24.044] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2021-01-13 00:37:24.044] [userDataSync] [info] Auto Sync is disabled.
[2021-01-13 00:43:38.923] [userDataSync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2021-01-13 00:51:24.766] [userDataSync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest

**Comment by sandy081** [comment]
Can you please more information/logs about `https://vscode-sync.trafficmanager.net/v1/manifest` failure - failed response?
