### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by prathap0611** [microsoft/vscode#114246]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.5.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/hariprathap/cloudsense/ppr/ppr-ui","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/hariprathap/cloudsense/ppr/ppr-ui","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:128625:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:128611:29)
    at ProjectService.getOrCreateOpenScriptInfo (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:129005:33)
    at ProjectService.applyChangesInOpenFiles (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:129210:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:129980:46)
    at /Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:131662:28)
    at IOSession.Session.executeCommand (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:131671:33)
    at IOSession.Session.onMessage (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:131693:35)
    at Interface.<anonymous> (/Users/hariprathap/cloudsense/ppr/ppr-ui/node_modules/typescript/lib/tsserver.js:132984:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 12|
|Memory (System)|16.00GB (2.04GB free)|
|Process Argv|--crash-reporter-id c878207d-393a-4d5d-8f77-a4321b0de7b8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-apollo|apo|1.18.0
json-tools|eri|1.0.2
prettier-vscode|esb|5.8.0
vscode-graphql|Gra|0.3.13
docthis|joe|0.7.1
apex|Joh|1.0.4
dotenv|mik|1.0.1
compare-folders|mos|0.20.0
vscode-docker|ms-|1.9.0
remote-containers|ms-|0.154.2
prisma|Pri|2.14.0
quicktype|qui|12.0.46
java|red|0.73.0
salesforcedx-vscode-apex|sal|50.8.0
salesforcedx-vscode-core|sal|50.8.0
scala|sca|0.5.0
prophet|Sqr|1.3.33
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
vstes516:30244333
pythonvspyt859:30241729

```

</details>

**Comment by mjbvz** [comment]
Closing as this is an old TS version. Let us know if you hit this in 4.1+
