### ISSUE TITLE
Cannot run smoke tests out of sources anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114332]
Fresh repo checkout and `yarn`:

```
~/Development/Microsoft/vscode-electron-4.0.x> yarn smoketest
yarn run v1.22.5
$ cd test/smoke && node test/index.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '/Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/test/smoke/out/main.js'
Require stack:
- /Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/lib/mocha.js
- /Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/index.js
- /Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/test/smoke/test/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/lib/mocha.js:394:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/lib/mocha.js:391:14)
    at Mocha.run (/Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/lib/mocha.js:970:10)
    at Object.<anonymous> (/Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/test/smoke/test/index.js:38:7)
    at Module._compile (internal/modules/cjs/loader.js:1138:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/lib/mocha.js',
    '/Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/index.js',
    '/Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/test/smoke/test/index.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alexdima** [comment]
`yarn` will not compile the tests as a postinstall step. So the tests need to be compiled manually. @joaomoreno Do you think it would be safe to change `yarn smoketest` to also do a compile?

**Comment by joaomoreno** [comment]
To clarify: this is compiling the smoke tests, not our entire unit and integration test suites. So yeah, compiling it as part of `yarn smoketest` is actually a good idea anyway.
