### ISSUE TITLE
Smoke test failure: Localization

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#114420]
Apparently started with either https://github.com/microsoft/vscode/commit/5b1e59c636cedc9a7ff800fe3fb05e667af0ba05 or https://github.com/microsoft/vscode/commit/5d6cba5cbc22d5c16cb0850ac71cb50bc949134e cc @isidorn @mjbvz 

```
        1) starts with 'DE' locale and verifies title and viewlets text is in German
      Launch
        ✓ verifies that application launches when user data directory has non-ascii characters


  26 passing (2m)
  2 pending
  1 failing

  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content 'div[id="workbench.view.explorer"] .split-view-view:nth-child(1) .title' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)
```

**Comment by joaomoreno** [comment]
Yeah... @isidorn : https://github.com/microsoft/vscode/blob/47ce2a8d6db0ff08ec9a46a7ca0d0d65cc1e6327/test/smoke/src/areas/workbench/localization.test.ts#L31-L31

**Comment by isidorn** [comment]
Thanks for fixing! Yeah I broke this with hiding Open Editors view.
