### ISSUE TITLE
Integration tests throw error at the end

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#114564]
When running `./scripts/test-integration.sh`, any extension test suite will succeed but still show the following error right at the end. Note that the process still exits with `0`, though.

```
[main 2021-01-19T10:29:07.561Z] [uncaught exception in main]: TypeError: Cannot read property 'isDevToolsFocused' of null
[main 2021-01-19T10:29:07.561Z] TypeError: Cannot read property 'isDevToolsFocused' of null
    at BrowserWindow.n.isDevToolsFocused (electron/js2c/browser_init.js:33:2600)
    at Function.n.getFocusedWindow (electron/js2c/browser_init.js:33:1603)
    at WindowsMainService.getFocusedWindow (/home/joao/Work/vscode/out/vs/platform/windows/electron-main/windowsMainService.js:998:53)
    at WindowsMainService.sendToFocused (/home/joao/Work/vscode/out/vs/platform/windows/electron-main/windowsMainService.js:1015:40)
    at CodeApplication.onUnexpectedError (/home/joao/Work/vscode/out/vs/code/electron-main/app.js:248:88)
    at ErrorHandler.unexpectedErrorHandler (/home/joao/Work/vscode/out/vs/code/electron-main/app.js:34:60)
    at ErrorHandler.onUnexpectedError (/home/joao/Work/vscode/out/vs/base/common/errors.js:43:18)
    at Object.onUnexpectedError (/home/joao/Work/vscode/out/vs/base/common/errors.js:60:34)
    at Emitter.fire (/home/joao/Work/vscode/out/vs/base/common/event.js:486:34)
    at LifecycleMainService.beginOnWillShutdown (/home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:137:34)
    at App.<anonymous> (/home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:117:46)
    at Object.onceWrapper (events.js:422:26)
    at App.emit (events.js:315:20)
    at App.windowAllClosedListener (/home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:106:36)
    at App.emit (events.js:327:22)
    at /home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:383:36
    at async LifecycleMainService.kill (/home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:369:13)
    at async NativeHostMainService.exit (/home/joao/Work/vscode/out/vs/platform/native/electron-main/nativeHostMainService.js:443:13)
[main 2021-01-19T10:29:07.561Z] [uncaught exception in main]: TypeError: Object has been destroyed
[main 2021-01-19T10:29:07.561Z] TypeError: Object has been destroyed
    at SharedProcess.onWillShutdown (/home/joao/Work/vscode/out/vs/code/electron-main/sharedProcess.js:54:20)
    at /home/joao/Work/vscode/out/vs/code/electron-main/sharedProcess.js:36:80
    at Emitter.fire (/home/joao/Work/vscode/out/vs/base/common/event.js:479:38)
    at LifecycleMainService.beginOnWillShutdown (/home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:137:34)
    at BrowserWindow.<anonymous> (/home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:209:26)
    at BrowserWindow.emit (events.js:327:22)
    at /home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:383:36
    at async LifecycleMainService.kill (/home/joao/Work/vscode/out/vs/platform/lifecycle/electron-main/lifecycleMainService.js:369:13)
    at async NativeHostMainService.exit (/home/joao/Work/vscode/out/vs/platform/native/electron-main/nativeHostMainService.js:443:13)
```

**Comment by sbatten** [comment]
@bpasero I had to revert this as it was blocking the extension viewlet from loading. `git bisect` pointed to this commit and revert resolves the issue. could repro the issue in OSS on windows and macOS

**Comment by bpasero** [comment]
👏
