### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by OscarFKE** [microsoft/vscode#114507]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.2

**Steps to reproduce crash**
1. Open a javascript file

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`c:\Users\oscar\AppData\Roaming\Code\logs\20210117T211713\exthost1\vscode.typescript-language-features\tsserver-log-7MhrXY\tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105102:161)
    at resolveModuleNamesWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105340:26)
    at resolveModuleNamesReusingOldState (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105530:19)
    at processImportedModules (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106941:35)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106713:17)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106911:21
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at processLibReferenceDirectives (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106906:16)
    at findSourceFileWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106710:21)
    at findSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106575:26)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106499:34)
    at processSourceFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106532:13)
    at processRootFile (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106342:13)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105207:60
    at Object.forEach (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at Object.createProgram (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105207:16)
    at synchronizeHostData (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146570:26)
    at Proxy.getProgram (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146662:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151524:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151457:42)
    at ConfiguredProject.updateGraph (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152412:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154141:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155045:44)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155385:97
    at Object.flatMap (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155385:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156403:46)
    at c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158276:88
    at IOSession.Session.executeWithRequestId (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158267:28)
    at IOSession.Session.executeCommand (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158276:33)
    at IOSession.Session.onMessage (c:\Users\oscar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158300:35)
```

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz (12 x 4125)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (11.20GB free)|
|Process Argv|--crash-reporter-id fd6f5dd3-fea9-4d02-a203-2857dddedd1e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.2
better-toml|bun|0.3.2
dart-code|Dar|3.18.1
flutter|Dar|3.18.1
vscode-deno|den|2.3.3
vscode-firefox-debug|fir|2.9.1
kotlin|fwc|0.2.20
godot-tools|gee|1.1.2
rust-analyzer|mat|0.2.449
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
mono-debug|ms-|0.16.2
godot-csharp-vscode|nei|0.1.3
rust|rus|0.7.8
crates|ser|0.5.5
rust-pack|Swe|0.2.29
vim|vsc|1.18.5
change-case|wma|1.0.0

</details>

**Comment by OscarFKE** [comment]
[tsserver.log](https://github.com/microsoft/vscode/files/5827172/tsserver.log)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically with the deno extension disabled? (it contributes a plugin for typescript )

**Comment by OscarFKE** [comment]
It does not
