### ISSUE TITLE
Native Modules: node-pty

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114683]
https://github.com/microsoft/vscode/runs/1739891607#step:11:7787

```
1) Native Modules (all platforms)
       node-pty:
     Error: Cannot find module './utils'
Require stack:
- D:\a\vscode\vscode\node_modules\node-pty\lib\windowsTerminal.js
- D:\a\vscode\vscode\node_modules\node-pty\lib\index.js
- D:\a\vscode\vscode\test\unit\electron\renderer.js
- D:\a\vscode\vscode\test\unit\electron\renderer.html
      at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
      at Function.i._resolveFilename (electron/js2c/renderer_init.js:35:917)
      at Module._load (internal/modules/cjs/loader.js:848:27)
      at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
      at Module.require (internal/modules/cjs/loader.js:1032:19)
      at Module.patchedRequire [as require] (D:\a\vscode\vscode\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (D:\a\vscode\vscode\node_modules\node-pty\lib\windowsTerminal.js:24:15)
```

Only in GH CI it seems (cc @alexdima )

**Comment by alexdima** [comment]
IMHO this has the same root as https://github.com/microsoft/vscode/issues/114516 . The node modules cached archive is missing files on Windows.
