### ISSUE TITLE
Sometimes Git can't authenticate against GitHub

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#115037]
That domain cropped in the quick input looks suspicious.

![image](https://user-images.githubusercontent.com/22350/105849068-bb790080-5f94-11eb-8132-581fa4e3e4cf.png)

**Comment by joaomoreno** [comment]
I'm surprised this even worked until today.

cc @eamodio

**Comment by joaomoreno** [comment]
**Verification:** please code review https://github.com/microsoft/vscode/commit/75ff8b113101d1362ef87c588cebfd4f16daf0a4 and https://github.com/microsoft/vscode/commit/9e07bfd5946172f0b7bece7b0cec2b58102944d2. This was just wrong, since it was cropping too much:

```ts
	const host = argv[4].substring(1, argv[4].length - 2);
```

**Comment by joaomoreno** [comment]
I may have broken this today: 

```
➜  vscode git:(master) git push
Missing or invalid credentials.
Error: Bad status code: 500
    at ClientRequest.<anonymous> (/home/joao/.vscode-server-insiders/bin/9ee751e859d655e1e80fa0d57253304c01c65732/extensions/git/dist/askpass-main.js:1:2200)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:469:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
```

**Comment by joaomoreno** [comment]
Another fix: https://github.com/microsoft/vscode/commit/7b0cfdd04ad530a9c8d782c618afd79290be3d64
