### ISSUE TITLE
Find all references to file fails on vscode repo

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115001]
Testing #114966

Version: 1.53.0-insider
Commit: 1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3
Date: 2021-01-26T05:14:17.500Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.3.0-64-generic

- open the vscode repo. It uses TypeScript from the workspace (4.2.0-dev.20201207)
- open a TypeScript file (e.g. `themeService.ts`), open the command palette and run `Command 'TypeScript: Find File References'.

- Error dialog 
`Command 'TypeScript: Find File References' resulted in an error (Running the contributed command: 'typescript.findAllFileReferences' failed.)`

2021-01-26 11:05:38.528] [exthost] [error] Error: <semantic> TypeScript Server Error (4.2.0-dev.20201207)
undefined
undefined
    at Function.create (/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:73508)
    at dispatchResponse (/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:67383)
    at dispatchMessage (/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:66242)
    at /usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:65752
    at v.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at g.onLengthData (/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:45:60030)
    at Socket.<anonymous> (/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:45:59678)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) typescript.findAllFileReferences

**Comment by aeschli** [comment]
Works when switching the TypeScript version in the workspace to `typescript@4.2.0-beta`

**Comment by mjbvz** [comment]
We are on an older version of TS 4.2 that does not support this command yet. I try to gate features by version but don't typically do this for pre-release versions of TypeScript (since we generally expect people to upgrade pretty quickly to the latest nightly versions)
