### ISSUE TITLE
macOS ARM: test resolver cannot connect

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115009]
When using macOS ARM to open a window on test resolver, an error is presented:

`/Users/bpasero/Development/Microsoft/monaco/resources/server/bin-dev/server.sh: line 23: /Users/bpasero/Development/Microsoft/monaco/.build/node/v12.18.3/darwin-arm64/node: No such file or directory`

**Comment by aeschli** [comment]
From what I see there are no darwin-arm64 binaries for the mac available yet. 
So I assume we continue to use x64 for the time being.

@bpasero I pushed a fix, can you test it?

**Comment by bpasero** [comment]
Can I do that out of sources or need to wait for insiders?

**Comment by aeschli** [comment]
My fix was for running the TestResolver out of sources...

**Comment by bpasero** [comment]
Yeah it works now but the entire thing is very unhappy from then on:

![image](https://user-images.githubusercontent.com/900690/106103173-cec8cf00-6140-11eb-84d5-28648511aa04.png)

**Comment by aeschli** [comment]
@bpasero Can you help to get more information? I don't have a Mac with ARM.
What does the Test Resolver output say?

**Comment by bpasero** [comment]
@aeschli I think the server just fails early on when requiring some native modules, full log:

```
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/notifications/notificationsAlerts.js:30 The terminal process failed to launch: A native exception occurred during launch (dlopen(/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/node-pty/build/Release/pty.node, 1): no suitable image found.  Did find: 	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/node-pty/build/Release/pty.node: mach-o, but wrong architecture 	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/node-pty/build/Release/pty.node: mach-o, but wrong architecture).
onDidChangeNotification @ vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/notifications/notificationsAlerts.js:30
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:144   ERR dlopen(/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node, 1): no suitable image found.  Did find:
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture

Error: dlopen(/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node, 1): no suitable image found.  Did find:
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.Module._load (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:37:33)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.Module._load (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:37:33)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Function.nodeRequire [as __$__nodeRequire] (/Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1000:24)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:231:40
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:146:41
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at PersistentProtocol._receiveMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:510:83
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at ProtocolReader.acceptChunk (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:158:61
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:366:42
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8): Error: dlopen(/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node, 1): no suitable image found.  Did find:
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture

Error: dlopen(/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node, 1): no suitable image found.  Did find:
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture
	/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/build/Release/watchdog.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.Module._load (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:37:33)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/remote/node_modules/native-watchdog/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.Module._load (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:37:33)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Function.nodeRequire [as __$__nodeRequire] (/Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1000:24)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:231:40
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:146:41
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at PersistentProtocol._receiveMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:510:83
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at ProtocolReader.acceptChunk (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:158:61
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:366:42
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8)
    at Timeout._onTimeout (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/errors.js:16:31)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:179 Extension Host
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:180 Debugger attached.
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:134  INFO [remote-connection][Management   ][57cf6…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:134  INFO [remote-connection][Management   ][57cf6…][reconnect] resolving connection...
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:134  INFO [remote-connection][ExtensionHost][39eca…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:134  INFO [remote-connection][ExtensionHost][39eca…][reconnect] resolving connection...
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:144   ERR [remote-connection][Management   ][57cf6…][reconnect] A RemoteAuthorityResolverError occurred while trying to reconnect. Will give up now! Error:
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:144   ERR Error: No remote extension installed to resolve test.
    at ExtensionHostManager.resolveAuthority (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/extensionHostManager.js:226)
    at async ExtensionService._resolveAuthorityAgain (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/extensionService.js:187)
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/abstractExtensionService.js:353 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/abstractExtensionService.js:353
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:144   ERR [remote-connection][ExtensionHost][39eca…][reconnect] A RemoteAuthorityResolverError occurred while trying to reconnect. Will give up now! Error:
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:144   ERR Error: No remote extension installed to resolve test.
    at ExtensionHostManager.resolveAuthority (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/extensionHostManager.js:226)
    at async ExtensionService._resolveAuthorityAgain (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/extensionService.js:187)
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:179 Extension Host
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:180 Waiting for the debugger to disconnect...
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/abstractExtensionService.js:353 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/abstractExtensionService.js:353
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js:144   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.vscode-test-resolver, PKief.material-icon-theme, zhuangtongfa.material-theme
vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/notifications/notificationsAlerts.js:30 Extension host terminated unexpectedly.
onDidChangeNotification @ vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/notifications/notificationsAlerts.js:30
bootstrap-window.js:259 [uncaught exception]: Error: This socket has been ended by the other party
onUnexpectedError @ bootstrap-window.js:259
bootstrap-window.js:262 Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/code/electron-browser/workbench/net.js:455)
    at NodeSocket.write (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:46)
    at ProtocolWriter._writeNow (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:268)
    at ProtocolWriter.flush (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:228)
    at ProtocolWriter.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:215)
    at Object.dispose (lifecycle.js:77)
    at PersistentProtocol.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:538)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:475
onUnexpectedError @ bootstrap-window.js:262
events.js:292 Uncaught Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/code/electron-browser/workbench/net.js:455)
    at NodeSocket.write (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:46)
    at ProtocolWriter._writeNow (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:268)
    at ProtocolWriter.flush (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:228)
    at ProtocolWriter.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:215)
    at Object.dispose (lifecycle.js:77)
    at PersistentProtocol.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:538)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:475
log.js:144   ERR No remote extension installed to resolve test.: Error: No remote extension installed to resolve test.
    at ExtensionHostManager.resolveAuthority (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/extensionHostManager.js:226:23)
    at async ExtensionService._resolveAuthorityAgain (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/extensionService.js:187:32)
```

**Comment by aeschli** [comment]
Looks like the setup to run a server out of sources needs more work.

The `TestResolver` runs he server with `./resources/server/bin-dev/server.sh`. That's also how your would start the server by hand from the command line. That uses the node-modules from `./remote/node_modues`. which typically gets installed by our regular `yarn` in the repo root.

Is there anything special needed when running `yarn` on MacOS ARM?

@bpasero Assigning to you as that isn't TestResolver specific. I don't have access to a MacOS ARM machine.

**Comment by bpasero** [comment]
Moving to @deepak1556 for Apple Si tasks, I leave you Martin assigned to assist him.
