### ISSUE TITLE
Notebook output rendering broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115293]
* open any GH issue notebook
* run a cell
* 🐛 no output, the console shows this error

```
  ERR Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:355:149
    at Map.forEach (<anonymous>)
    at OutputContainer._updateOutputs (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:349:32)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:214:22
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.js:44:42
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at NotebookCellTextModel.spliceNotebookCellOutputs (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.js:106:38)
    at NotebookTextModel._spliceNotebookCellOutputs (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:574:22)
    at NotebookTextModel.applyEdits (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:288:34)
    at MainThreadNotebooks.$spliceNotebookCellOutputs (file:///Users/jrieken/Code/vscode/out/vs/workbench/api/browser/mainThreadNotebook.js:476:23)
    at RPCProtocol._doInvokeHandler (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:341:27)
    at RPCProtocol._invokeHandler (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:326:45)
    at RPCProtocol._receiveRequest (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:253:32)
    at RPCProtocol._receiveOneMessage (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:181:26)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:65:52
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at BufferedEmitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at PersistentProtocol._receiveMessage (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
    at file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:510:83
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at ProtocolReader.acceptChunk (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
    at file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:158:61
    at Socket.listener (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/node/ipc.net.js:17:40)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by jrieken** [comment]
caused by d42bed7957a709307ef12970d046c01ce90b0a40

**Comment by jrieken** [comment]
@rebornix I have revert the bad commit
