### ISSUE TITLE
Search smoke test failing

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#115244]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=102321&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=b4255493-5d6b-5e5c-80d7-ebab0307fbf4

```
1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Search
           dismisses result & checks for correct result number:
     Error: Timeout: get text content '.search-view .messages .message>span' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by JacksonKearl** [comment]
Tried locally a few times and couldn't get a repro. Any ideas @roblourens ?

**Comment by roblourens** [comment]
Same, I ran it many times and it passed 100%

**Comment by JacksonKearl** [comment]
Going to reenable, 8a3a5d9b74723c4167d8415ae6228997c80fb108 may have fixed.

**Comment by meganrogge** [comment]
Seeing this 

`
      Search
** Timeout!
page.evaluate: Evaluation failed: Error: Active element not found. Current active element is 'HTML > BODY.windows.web'. Looking for .search-view .search-widget .search-container .monaco-inputbox textarea
    at BrowserWindowDriver.isActiveElement (http://localhost:9888/static/out/vs/platform/driver/browser/baseDriver.js:63:23)
    at eval (eval at evaluate (:300:31), <anonymous>:1:15)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:300:31)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Connection.sendMessageToServer (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\channelOwner.js:44:61)
    at C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\frame.js:157:48
    at Frame._wrapApiCall (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\channelOwner.js:72:34)
    at Frame.evaluate (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\frame.js:156:21)
    at C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\page.js:344:60
    at Page._attributeToPage (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\page.js:205:20)
    at Page.evaluate (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\page.js:344:21)
    at Proxy.isActiveElement (C:\Users\merogge\repos\vscode\test\automation\out\playwrightDriver.js:72:55)
    at Proxy.<anonymous> (C:\Users\merogge\repos\vscode\test\automation\out\code.js:208:39)
        √ searches for body & checks for correct result number
        √ searches only for *.js files & checks for correct result number
        - dismisses result & checks for correct result number
        √ replaces first search result with a replace term
      Quick Access
        √ quick access search produces correct result
        √ quick access respects fuzzy matching
      Notebooks
        - moves focus in and out of output
        - cell action execution
      Language Features
        √ verifies quick outline
        √ verifies problems view
        √ verifies settings
      Editor
        √ shows correct quick outline
      Statusbar
        √ verifies presence of all default status bar elements
        √ verifies that 'quick input' opens when clicking on status bar elements
        √ verifies that 'Problems View' appears when clicking on 'Problems' status element
        - verifies that 'Tweet us feedback' pop-up appears when clicking on 'Feedback' icon
        √ checks if 'Go to Line' works if called from the status bar
        √ verifies if changing EOL is reflected in the status bar
      Extensions
        - install and enable vscode-smoketest-check extension`
when testing #119524

**Comment by meganrogge** [comment]
Seeing this

using `yarn smoketest --build <path to latest version> --stable-build <path to stable version>`

pending - `dismisses result & checks for correct result number` due to timeout with this error

```
** Timeout!
Error: Active element not found. Current active element is 'HTML > BODY.windows > DIV.file-icons-enabled.monaco-workbench.windows.chromium.nopanel.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.horizontal > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible >
DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical.separator-border > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV.editor-instance > DIV.monaco-scrollable-element > DIV.welcomePageFocusElement'. Looking for .quick-input-widget .quick-input-box input
    at g.isActiveElement (file:///C:/Users/merogge/insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:570:78242)
    at v.call (file:///C:/Users/merogge/insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2792:63919)
    at w.onPromise (file:///C:/Users/merogge/insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:75:68877)
    at w.onRawMessage (file:///C:/Users/merogge/insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:75:68236)
    at file:///C:/Users/merogge/insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:75:67489
    at c.fire (file:///C:/Users/merogge/insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at EventEmitter.N (file:///C:/Users/merogge/insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60411)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:117:979)
```

**Comment by meganrogge** [comment]
On remote, 

`  1) shows results from all folders` is failing with this message:


 ```
 1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Multiroot
           shows results from all folders:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (C:\Users\merogge\repos\vscode\test\automation\out\code.js:173:19)
      at async Code.waitForElements (C:\Users\merogge\repos\vscode\test\automation\out\code.js:250:16)
      at async QuickInput.waitForQuickInputElements (C:\Users\merogge\repos\vscode\test\automation\out\quickinput.js:24:9)
      at async Context.<anonymous> (out\areas\multiroot\multiroot.test.js:39:13)

```

**Comment by JacksonKearl** [comment]
Those look like errors from the quick input rather than search?

**Comment by bpasero** [comment]
@JacksonKearl depends on https://github.com/microsoft/vscode/issues/128479. We are happy for any help we can get, the item is up for grab.

**Comment by Tyriar** [comment]
Just reported this again in https://github.com/microsoft/vscode/issues/138552

**Comment by Tyriar** [comment]
Another failure: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145908&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=173

```
  4 failing

  1) VSCode Smoke Tests (Web)
       Language Features
         verifies quick outline:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:48:19)
      at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:152:16)
      at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
      at async QuickAccess.openQuickAccessAndWait (D:\a\1\s\test\automation\out\quickaccess.js:46:13)
      at async QuickAccess.openFile (D:\a\1\s\test\automation\out\quickaccess.js:74:9)
      at async Context.<anonymous> (out\areas\languages\languages.test.js:16:13)

  2) VSCode Smoke Tests (Web)
       Language Features
         verifies problems view:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:48:19)
      at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:152:16)
      at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
      at async QuickAccess.openQuickAccessAndWait (D:\a\1\s\test\automation\out\quickaccess.js:46:13)
      at async QuickAccess.openFile (D:\a\1\s\test\automation\out\quickaccess.js:74:9)
      at async Context.<anonymous> (out\areas\languages\languages.test.js:22:13)

  3) VSCode Smoke Tests (Web)
       Language Features
         verifies settings:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:48:19)
      at async Code.waitForElement (D:\a\1\s\test\automation\out\code.js:156:16)
      at async Context.<anonymous> (out\areas\languages\languages.test.js:33:13)

  4) VSCode Smoke Tests (Web)
       Editor
         shows correct quick outline:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:48:19)
      at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:152:16)
      at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
      at async QuickAccess.openQuickAccessAndWait (D:\a\1\s\test\automation\out\quickaccess.js:46:13)
      at async QuickAccess.openFile (D:\a\1\s\test\automation\out\quickaccess.js:74:9)
      at async Context.<anonymous> (out\areas\editor\editor.test.js:15:13)
```

**Comment by Tyriar** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146345&view=results

**Comment by Tyriar** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146305&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=144

**Comment by bpasero** [comment]
Trend looks pretty good lately:

![image](https://user-images.githubusercontent.com/900690/146527585-4a61ea86-4883-4c29-ad02-be3ee4035f88.png)

I am also refactoring how `openQuickAccessAndWait` works in https://github.com/microsoft/vscode/commit/38f026eb35735f22602d1919a87a785b561e6dcc so maybe we should close this one until we see it happening again?

**Comment by Tyriar** [comment]
If it hasn't failed in a week, we can call this fixed 🎉 

Thanks for the fixes @roblourens @bpasero
