### ISSUE TITLE
Remote-SSH plug-in fails with IPv6 host

### ISSUE THREAD

**Issue by iamGavinJ** [microsoft/vscode#115356]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. Configure the OpenSSH config file (`~/.ssh/config`) with a host entry containing `AddressFamily inet6`.
2. Connect to remote host.
3. Plug-in attempts to port forward to `127.0.0.1` instead of `::1`

Does this issue occur when all extensions are disabled?: Yes/No

```
[16:47:55.477] Log Level: 2
[16:47:55.479] remote-ssh@0.63.0
[16:47:55.479] darwin x64
[16:47:55.481] SSH Resolver called for "ssh-remote+<<REDACTED>>", attempt 1
[16:47:55.482] "remote.SSH.useLocalServer": true
[16:47:55.482] "remote.SSH.sshPath": undefined
[16:47:55.482] "remote.SSH.sshConfigurationFile": undefined
[16:47:55.482] "remote.SSH.useFlock": true
[16:47:55.482] "remote.SSH.lockfilesInTmp": false
[16:47:55.482] "remote.SSH.localServerDownload": auto
[16:47:55.483] "remote.SSH.remoteServerListenOnSocket": false
[16:47:55.483] "remote.SSH.showLoginTerminal": false
[16:47:55.484] SSH Resolver called for host: <<REDACTED>>
[16:47:55.484] Setting up SSH remote "<<REDACTED>>"
[16:47:55.489] Acquiring local install lock: /var/folders/lt/1zrxht0x433cw94wrc1fx5cm0004w9/T/vscode-remote-ssh-bot-install.lock
[16:47:55.491] Looking for existing server data file at /Users/<<REDACTED>>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-bot-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.63.0/data.json
[16:47:55.491] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[16:47:55.494] Install and start server if needed
[16:47:55.504] Checking ssh with "ssh -V"
[16:47:55.519] > OpenSSH_8.1p1, LibreSSL 2.7.3

[16:47:55.524] askpass server listening on /var/folders/lt/1zrxht0x433cw94wrc1fx5cm0004w9/T/vscode-ssh-askpass-70e15e357da8cb66947a5f595aa9dff30d7ca60f.sock
[16:47:55.524] Spawning local server with {"ipcHandlePath":"/var/folders/lt/1zrxht0x433cw94wrc1fx5cm0004w9/T/vscode-ssh-askpass-f108752e03e97a7f7dfdf394a0ed665c22f0cf0d.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","58308","-o","ConnectTimeout=15","<<REDACTED>>"],"dataFilePath":"/Users/<<REDACTED>>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-bot-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.63.0/data.json"}
[16:47:55.524] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/<<REDACTED>>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/<<REDACTED>>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/lt/1zrxht0x433cw94wrc1fx5cm0004w9/T/vscode-ssh-askpass-70e15e357da8cb66947a5f595aa9dff30d7ca60f.sock"}
[16:47:55.530] Spawned 39238
[16:47:55.680] > local-server> Spawned ssh: 39239
[16:47:55.687] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[16:47:57.483] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:<<REDACTED>>
[16:47:57.484] stderr> Warning: Permanently added '<<REDACTED>>.australiaeast.cloudapp.azure.com' (ECDSA) to the list of known hosts.
[16:47:58.310] stderr> Authenticated to <<REDACTED>>.australiaeast.cloudapp.azure.com ([2603:<<REDACTED>>]:22).
[16:47:59.076] > Welcome to Ubuntu 20.10 (GNU/Linux 5.8.0-1019-azure x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Fri Jan 29 00:47:58 UTC 2021
> 
>   System load:                      0.05
>   Usage of /:                       15.2% of 28.90GB
>   Memory usage:                     61%
>   Swap usage:                       14%
>   Processes:                        145
>   Users logged in:                  1
>   IPv4 address for br-78d9075adc98: <<REDACTED>>
>   IPv6 address for br-78d9075adc98: <<REDACTED>>
>   IPv4 address for docker0:         <<REDACTED>>
>   IPv6 address for docker0:         <<REDACTED>>
>   IPv4 address for eth0:            <<REDACTED>>
>   IPv6 address for eth0:            <<REDACTED>>
> 
>  * Introducing self-healing high availability clusters in MicroK8s.
>    Simple, hardened, Kubernetes for production, from RaspberryPi to DC.
> 
>      https://microk8s.io/high-availability
> 
> 1 update can be installed immediately.
> 0 of these updates are security updates.
> To see these additional updates run: apt list --upgradable
> 
> 
> *** System restart required ***
[16:47:59.238] > ready: f63cf079dbfc
[16:47:59.405] > Linux 5.8.0-1019-azure #21-Ubuntu SMP Fri Jan 15 14:39:23 UTC 2021
[16:47:59.405] Platform: linux
[16:47:59.903] > f63cf079dbfc: running
[16:47:59.944] > Acquiring lock on /home/<<REDACTED>>/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/vscode-remote-lock.<<REDACTED>>.ea3859d4ba2f3e577a159bc91e3074c5d85c0523
[16:47:59.966] > Found existing installation at /home/<<REDACTED>>/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523...
> Checking /home/<<REDACTED>>/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log and /home/<<REDACTED>>/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.pid for a running server
> Looking for server with pid: 277209
[16:47:59.976] > Found running server...
[16:47:59.977] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[16:47:59.991] > Checking server status on port 42437 with wget
[16:48:00.007] > f63cf079dbfc: start
> sshAuthSock==/tmp/<<REDACTED>>==
> webUiAccessToken====
> listeningOn==42437==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==<<REDACTED>>==
> f63cf079dbfc: end
[16:48:00.008] Received install output: 
sshAuthSock==/tmp/<<REDACTED>>==
webUiAccessToken====
listeningOn==42437==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==<<REDACTED>>==

[16:48:00.008] Remote server is listening on 42437
[16:48:00.008] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":42437},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/<<REDACTED>>","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"<<REDACTED>>"},"installUnpackCode":""}
[16:48:00.009] Persisting server connection details to /Users/<<REDACTED>>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-bot-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.63.0/data.json
[16:48:00.011] Starting forwarding server. localPort 58326 -> socksPort 58308 -> remotePort 42437
[16:48:00.011] Forwarding server listening on 58326
[16:48:00.011] Waiting for ssh tunnel to be ready
[16:48:00.012] Tunneled 42437 to local port 58326
[16:48:00.012] Resolved "ssh-remote+<<REDACTED>>" to "127.0.0.1:58326"
[16:48:00.013] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/<<REDACTED>>" "/run/user/1000/vscode-ssh-auth-sock-583949784"
[16:48:00.013] Using cwd: vscode-remote://ssh-remote%2B<<REDACTED>>/
[16:48:00.013] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1000/vscode-ssh-auth-sock-583949784"}
[16:48:00.014] [Forwarding server 58326] Got connection 0
[16:48:00.016] Failed to set up socket for dynamic port forward to remote port 42437: connect ECONNREFUSED 127.0.0.1:58308. Is the remote port correct?
[16:48:00.021] ------




[16:48:00.099] [Forwarding server 58326] Got connection 1
[16:48:00.102] [Forwarding server 58326] Got connection 2
[16:48:00.103] Failed to set up socket for dynamic port forward to remote port 42437: connect ECONNREFUSED 127.0.0.1:58308. Is the remote port correct?
[16:48:00.103] Failed to set up socket for dynamic port forward to remote port 42437: connect ECONNREFUSED 127.0.0.1:58308. Is the remote port correct?
[16:50:00.727] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
[16:50:00.735] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Looks like a dup of https://github.com/microsoft/vscode-remote-release/issues/2355
