### ISSUE TITLE
Can't reconnect to remote server after 2 hours

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#115502]
Version: 1.53.0-insider (Universal)
Commit: 861a88ebadb4335df92251faf6420b598440e082
Date: 2021-01-29T22:40:25.646Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.2.0

I worked on my ssh box this morning until 9.15 am PT from my laptop.  Then I closed my laptop. I reopened the lid at around 11.15am PT. The connection was down less than 3 hours. I use autosave so the window communicated with the server right until I left. So, I'd have expected a smooth resume, but I got: 

![image](https://user-images.githubusercontent.com/4674940/106395309-726ee500-63b6-11eb-84b9-4b6bc0b6401e.png)

The local extension host is up and running. 

This the window log:

```
[2021-01-30 12:23:59.585] [renderer2] [error] Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled)
    at o.doReadAsFileStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48643)
[2021-01-30 12:24:18.917] [renderer2] [error] spawn git ENOENT: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-01-30 12:24:38.136] [renderer2] [error] spawn git ENOENT: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-01-31 08:57:54.225] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 08:57:54.226] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] resolving connection...
[2021-01-31 08:57:54.226] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] connecting to 127.0.0.1:60323...
[2021-01-31 08:57:54.227] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 08:57:54.229] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] resolving connection...
[2021-01-31 08:57:54.473] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] reconnected!
[2021-01-31 08:57:57.788] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] connecting to 127.0.0.1:51773...
[2021-01-31 08:57:57.939] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] reconnected!
[2021-01-31 08:57:58.527] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 08:57:58.527] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] resolving connection...
[2021-01-31 08:57:58.527] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] connecting to 127.0.0.1:51773...
[2021-01-31 08:57:58.683] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] reconnected!
[2021-01-31 08:57:59.885] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 08:57:59.886] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] resolving connection...
[2021-01-31 08:57:59.887] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 08:57:59.887] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] resolving connection...
[2021-01-31 08:58:02.429] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] connecting to 127.0.0.1:51794...
[2021-01-31 08:58:02.429] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] connecting to 127.0.0.1:51794...
[2021-01-31 08:58:02.577] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] reconnected!
[2021-01-31 08:58:02.656] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] reconnected!
[2021-01-31 08:58:12.836] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 08:58:12.836] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] resolving connection...
[2021-01-31 08:58:12.837] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] connecting to 127.0.0.1:51794...
[2021-01-31 08:58:12.837] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 08:58:12.838] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] resolving connection...
[2021-01-31 09:03:44.969] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] A temporarily not available error occurred while trying to reconnect, will try again...
[2021-01-31 09:03:44.970] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] waiting for 5 seconds before reconnecting...
[2021-01-31 09:03:49.993] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] resolving connection...
[2021-01-31 09:04:03.812] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] connecting to 127.0.0.1:51884...
[2021-01-31 09:04:03.966] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] reconnected!
[2021-01-31 11:04:08.111] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-31 11:04:08.117] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] resolving connection...
[2021-01-31 11:04:08.486] [renderer2] [error] [remote-connection] The time limit has been reached for a connection. Error:
[2021-01-31 11:04:08.486] [renderer2] [error] Error: Time limit reached
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:118204
[2021-01-31 11:04:08.486] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] A network error occurred while trying to reconnect, will try again...
[2021-01-31 11:04:08.486] [renderer2] [info] [remote-connection][ExtensionHost][d3a53…][reconnect] waiting for 5 seconds before reconnecting...
[2021-01-31 11:04:10.624] [renderer2] [info] [remote-connection][Management   ][47523…][reconnect] connecting to 127.0.0.1:51960...
[2021-01-31 11:04:10.912] [renderer2] [error] [remote-connection][Management   ][47523…][reconnect][127.0.0.1:51960] received error control message when negotiating connection. Error:
[2021-01-31 11:04:10.912] [renderer2] [error] Error: Connection error: Unknown reconnection token
    at P (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:118617)
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:109681
    at u.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at o.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:106113
    at u.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:104730)
[2021-01-31 11:04:10.912] [renderer2] [error] [remote-connection][Management   ][47523…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2021-01-31 11:04:10.912] [renderer2] [error] Error: Connection error: Unknown reconnection token
    at P (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:118617)
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:109681
    at u.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at o.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:106113
    at u.fire (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:104730)
[2021-01-31 11:04:15.076] [renderer2] [error] [remote-connection][ExtensionHost][d3a53…][reconnect] permanent failure occurred while running the reconnecting loop.
[2021-01-31 11:16:57.864] [renderer2] [error] Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled)
    at o.doReadAsFileStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48643)
[2021-01-31 11:17:35.995] [renderer2] [error] Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled)
    at o.doReadAsFileStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48643)
[2021-01-31 11:17:43.728] [renderer2] [error] Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled)
    at o.doReadAsFileStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48643)
[2021-01-31 11:19:47.159] [renderer2] [error] [remote-connection][ExtensionHost][d3a53…][reconnect][127.0.0.1:51794] socketFactory.connect() failed. Error:
[2021-01-31 11:19:47.159] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:105385)
[2021-01-31 11:21:24.757] [renderer2] [error] Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://ssh-remote+az-devbox/datadrive/kieferrm/projects/aaaaaaaa/file.md' (Canceled: Canceled)
    at o.doReadAsFileStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///Users/kieferrm/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48643)
```

**Comment by alexdima** [comment]
@kieferrm Did you by any chance use multiple machines to connect to the same SSH server? The server-side waiting time is reduced to 5 minutes as soon as a server receives a new connection. So if any new connection reached the server between 9.15 and 11.10, the server would have cleaned up the resources it had lingering around. The assumption is that if you can connect to the server with any client, it means that you are actually not offline, but intentionally chose to disconnect like e.g. closing the lid.

**Comment by kieferrm** [comment]
There was no access from any other box. Also, pls see https://github.com/microsoft/vscode-remote-release/issues/4389. They might all be the same underlying issue.

**Comment by alexdima** [comment]
@kieferrm Can you please also attach the server-side logs. Those would help clear things up.
