### ISSUE TITLE
Could not establish connection to "<IP address>": Permission denied (publickey).

### ISSUE THREAD

**Issue by shreyagupta30** [microsoft/vscode#115622]
- VSCode Version: 1.52.1
- OS Version: macOS Big Sur v11.1, apple silicon(M1)

Steps to Reproduce:

1. I am trying to ssh into my VM that's hosted on Google cloud platform from VS code constantly gets the error 
``` Could not establish connection to "<IP address>": Permission denied (publickey). ```
In order to check whether if my key is correct, I logged in from the terminal using `ssh-keygen` and it's working fine. 

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
How does it find your key when connecting from the terminal? Are you using an ssh config, command line parameter, ssh agent, or does the key have a default name/location that is checked automatically?

**Comment by shreyagupta30** [comment]
> How does it find your key when connecting from the terminal? Are you using an ssh config, command line parameter, ssh agent, or does the key have a default name/location that is checked automatically?

Hi @roblourens , I used `ssh config`. It asked to append all info on a ssh config file when I first tried to setup the connection.

**Comment by shubhank-saxena** [comment]
The replicated steps having same issue - #115733

**Comment by roblourens** [comment]
Can you both share the log from the Remote-SSH output channel, and also the generated ssh config?

**Comment by shreyagupta30** [comment]
Remote-SSH output is here
```
[23:29:24.970] Log Level: 2
[23:29:24.975] remote-ssh@0.63.0
[23:29:24.975] darwin x64
[23:29:24.977] SSH Resolver called for "ssh-remote+35.213.182.1", attempt 1
[23:29:24.978] "remote.SSH.useLocalServer": true
[23:29:24.978] "remote.SSH.sshPath": undefined
[23:29:24.978] "remote.SSH.sshConfigurationFile": undefined
[23:29:24.978] "remote.SSH.useFlock": true
[23:29:24.978] "remote.SSH.lockfilesInTmp": false
[23:29:24.978] "remote.SSH.localServerDownload": auto
[23:29:24.978] "remote.SSH.remoteServerListenOnSocket": false
[23:29:24.978] "remote.SSH.showLoginTerminal": false
[23:29:24.979] SSH Resolver called for host: 35.213.182.1
[23:29:24.979] Setting up SSH remote "35.213.182.1"
[23:29:24.985] Acquiring local install lock: /var/folders/j8/2nzz29zn0439c37m5klxf9mh0000gn/T/vscode-remote-ssh-35.213.182.1-install.lock
[23:29:25.013] Looking for existing server data file at /Users/shreya/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-35.213.182.1-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.63.0/data.json
[23:29:25.014] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[23:29:25.025] Install and start server if needed
[23:29:25.047] Checking ssh with "ssh -V"
[23:29:25.073] > OpenSSH_8.1p1, LibreSSL 2.7.3

[23:29:25.082] askpass server listening on /var/folders/j8/2nzz29zn0439c37m5klxf9mh0000gn/T/vscode-ssh-askpass-92866da2f5d41798a6dc1aa9762d1a801243eea9.sock
[23:29:25.082] Spawning local server with {"ipcHandlePath":"/var/folders/j8/2nzz29zn0439c37m5klxf9mh0000gn/T/vscode-ssh-askpass-109bb631b06273711855d1c7aa8b16e730da6440.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52802","-o","ConnectTimeout=15","35.213.182.1"],"dataFilePath":"/Users/shreya/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-35.213.182.1-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.63.0/data.json"}
[23:29:25.082] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/private/var/folders/j8/2nzz29zn0439c37m5klxf9mh0000gn/T/AppTranslocation/6DE8A6DA-5464-45F6-B988-96176CE40CD9/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/j8/2nzz29zn0439c37m5klxf9mh0000gn/T/vscode-ssh-askpass-92866da2f5d41798a6dc1aa9762d1a801243eea9.sock"}
[23:29:25.094] Spawned 6305
[23:29:25.351] > local-server> Spawned ssh: 6306
[23:29:25.366] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[23:29:25.902] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:eNGkIV54ydcQeCLMaZrBiJkwT7RQbN6z3rIFr1j/Jqg
[23:29:26.242] stderr> no such identity: vm_projects: No such file or directory
[23:29:26.242] stderr> shreya@35.213.182.1: Permission denied (publickey).
[23:29:26.247] > local-server> ssh child died, shutting down
[23:29:26.250] Local server exit: 0
[23:29:26.250] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:eNGkIV54ydcQeCLMaZrBiJkwT7RQbN6z3rIFr1j/Jqg
no such identity: vm_projects: No such file or directory
shreya@35.213.182.1: Permission denied (publickey).

[23:29:26.264] Resolver error: Error: Permission denied (publickey).
	at Function.Create (/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:64027)
	at /Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:62260
	at Object.t.handleInstallOutput (/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:62543)
	at Object.t.tryInstallWithLocalServer (/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:405034)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:310329
	at async Object.t.withShowDetailsEvent (/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:405790)
	at async /Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:403558
	at async S (/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:400326)
	at async Object.t.resolveWithLocalServer (/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:403185)
	at async Object.t.resolve (/Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:314332)
	at async /Users/shreya/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:127:110333
[23:29:26.274] ------
```
And this is my ssh config
```
Host 35.213.182.1
HostName 35.213.182.1
IdentityFile vm_projects
User shreya
```

**Comment by roblourens** [comment]
Here is the error: `no such identity: vm_projects: No such file or directory`

This is resolved relative to the current directory, so in your ssh config it should probably be an absolute path.
