### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by spiftire** [microsoft/vscode#115605]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.2

**Steps to reproduce crash**
1. added debug config from https://deno.land/manual@v1.7.1/getting_started/debugging_your_code#vscode
2. started debugger

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:105102:161)
    at resolveModuleNamesWorker (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:105340:26)
    at resolveModuleNamesReusingOldState (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:105530:19)
    at processImportedModules (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:106941:35)
    at findSourceFileWorker (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:106713:17)
    at findSourceFile (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:106575:26)
    at /home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:106532:85
    at getSourceFileFromReferenceWorker (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:106499:34)
    at processSourceFile (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:106532:13)
    at processRootFile (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:106342:13)
    at /home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:105207:60
    at Object.forEach (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:105207:16)
    at synchronizeHostData (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:146570:26)
    at Proxy.getProgram (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:146662:13)
    at InferredProject.Project.updateGraphWorker (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:151524:53)
    at InferredProject.Project.updateGraph (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:151457:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:153585:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:155111:26)
    at /home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:155385:97
    at Object.flatMap (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:155385:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:156403:46)
    at /home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:158276:88
    at IOSession.Session.executeWithRequestId (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:158267:28)
    at IOSession.Session.executeCommand (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:158276:33)
    at IOSession.Session.onMessage (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:158300:35)
    at Interface.<anonymous> (/home/steffen/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/node_modules/typescript/lib/tsserver.js:160510:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.97GB free)|
|Process Argv|. --crash-reporter-id 2c3ca2e3-77cd-4fa0-8b4c-d72e49e9eb63|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|12.40GB (8.28GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.1.0
remote-containers|ms-|0.155.1
remote-wsl|ms-|0.52.0
material-icon-theme|PKi|4.5.0
vscode-deno|den|2.3.3
prettier-vscode|esb|5.8.0
vscode-yarn|gam|1.7.1
vscode-pull-request-github|Git|0.22.0
latex-workshop|Jam|8.15.0
vscode-docker|ms-|1.9.1
vscode-git-flow|Psy|0.4.2
comment-ts|sal|1.0.20
complete-statement|wea|0.0.2016

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by mjbvz** [comment]
Please file this issue against the Deno extension
