### ISSUE TITLE
Download for vscode-server.tar.gz isn't following redirects

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#115795]
- VSCode Version: 1.53
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Remote-SSH into a machine after updating to 1.53
2. Watch the Remote-SSH logs for the following:

```
[14:58:18.185] Log Level: 2
[14:58:18.212] remote-ssh@0.63.0
[14:58:18.213] win32 x64
[14:58:18.216] SSH Resolver called for "ssh-remote+computer", attempt 1
[14:58:18.220] "remote.SSH.useLocalServer": false
[14:58:18.220] "remote.SSH.showLoginTerminal": false
[14:58:18.221] "remote.SSH.remotePlatform": {"computer":"linux","other_computer":"linux"}
[14:58:18.222] "remote.SSH.sshPath": undefined
[14:58:18.223] "remote.SSH.sshConfigurationFile": undefined
[14:58:18.223] "remote.SSH.useFlock": true
[14:58:18.224] "remote.SSH.lockfilesInTmp": false
[14:58:18.224] "remote.SSH.localServerDownload": auto
[14:58:18.224] "remote.SSH.remoteServerListenOnSocket": false
[14:58:18.225] "remote.SSH.showLoginTerminal": false
[14:58:18.226] SSH Resolver called for host: computer
[14:58:18.227] Setting up SSH remote "computer"
[14:58:18.292] Using commit id "8490d3dde47c57ba65ec40dd192d014fd2113496" and quality "stable" for server
[14:58:18.304] Install and start server if needed
[14:58:18.321] Checking ssh with "ssh -V"
[14:58:18.804] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[14:58:18.834] Running script with connection command: ssh -T -D 49766 computer bash
[14:58:18.842] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:58:19.316] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[14:58:19.316] Got some output, clearing connection timeout
[14:58:19.583] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[14:58:21.410] > user@computer's password: 
[14:58:21.411] Showing password prompt
[14:58:25.536] Got password response
[14:58:25.536] "install" wrote data to terminal: "********"
[14:58:25.567] > 
> 
[14:58:26.365] > d30a5b351b67: running
> 
[14:58:26.382] > Acquiring lock on /home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d0
> 14fd2113496/vscode-remote-lock.user.8490d3dde47c57ba65ec40dd192d014fd2113496 
> 
[14:58:26.394] > Installing to /home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd
> 2113496...
> 
[14:58:26.415] > d30a5b351b67%%1%%    
> Downloading with wget
> 
[14:58:26.859] > wget download failed
> GnuTLS: Error in the pull function. Unable to establish SSL connection.
> 
[14:58:26.873] > printenv:
>     SHELL=/bin/bash
>     PWD=/home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd211349
> 6
>     LOGNAME=user
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/user
>     VSCODE_AGENT_FOLDER=/home/user/.vscode-server
>     SSH_CONNECTION=10.8.214.242 49768 10.114.5.205 22
>     XDG_SESSION_CLASS=user
>     USER=user
>     SHLVL=0
>     XDG_SESSION_ID=10
>     XDG_RUNTIME_DIR=/run/user/1264905
>     SSH_CLIENT=10.8.214.242 49768 22
>     PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1264905/bus
[14:58:26.877] > 
>     OLDPWD=/home/user
>     _=/usr/bin/printenv
> 
[14:58:26.891] > Trigger local server download
> d30a5b351b67:trigger_server_download
> platform==linux==
[14:58:26.895] > 
> vscodeArch==x64==
> destFolder==/home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd21
> 13496==
> d30a5b351b67:trigger_server_download_end
[14:58:26.899] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd2113496"}
[14:58:26.900] Downloading VS Code server locally...
[14:58:26.904] > 
> Waiting for client to transfer server archive...
> Waiting for /home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd21
> 13496/vscode-scp-done.flag and vscode-server.tar.gz to exist
> 
[14:58:27.892] Downloaded VS Code server to c:\Users\user\AppData\Local\Temp\3e7eb552-1039-4710-8859-28916eaf6919
[14:58:27.927] Renamed VS Code server to c:\Users\user\AppData\Local\Temp\vscode_server_1612472307892\vscode-server.tar.gz
[14:58:27.939] Checking ssh with "ssh -V"
[14:58:28.356] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[14:58:28.375] Testing scp with "scp"
[14:58:28.753] scp exited with code: 1
[14:58:28.754] Got stderr from scp: usage: scp [-346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program] source ... target
[14:58:28.757] Copying file to remote with scp "vscode-server.tar.gz" "vscode-scp-done.flag" computer:"/home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd2113496"
[14:58:28.758] Using cwd: file:///c%3A/Users/user/AppData/Local/Temp/vscode_server_1612472307892
[14:58:28.758] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:58:29.174] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[14:58:29.183] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[14:58:31.173] > user@computer's password: 
[14:58:31.174] Showing password prompt
[14:58:35.987] Got password response
[14:58:35.988] "Copy server to host" wrote data to terminal: "********"
[14:58:36.017] > 
> 
[14:58:36.869] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[14:58:37.027] > vscode-server.tar.gz                          100%   16KB  81.8KB/s   00:00    
[14:58:37.036] > 
> 
[14:58:37.176] > vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[14:58:37.318] > vscode-scp-done.flag                          100%    9     0.1KB/s   00:00    
[14:58:37.336] > 
> 
[14:58:40.591] "Copy server to host" terminal command done
[14:58:40.610] > Found flag and server on host
> 
[14:58:40.618] > d30a5b351b67%%2%%
> tar --version:
[14:58:40.648] > 
> tar (GNU tar) 1.32
> Copyright (C) 2019 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>. 
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
[14:58:40.649] > 
> 
> Written by John Gilmore and Jay Fenlason.
[14:58:40.658] > 
> ERROR: /home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd2113496
> /node or /home/user/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd21134
> 96/server.sh don't exist
> Already attempted local download, failing
> d30a5b351b67: start
> exitCode==37==
[14:58:40.666] > 
> listeningOn====
> osReleaseId==fedora==
> arch==x86_64==
> tmpDir==/run/user/1264905==
> platform==linux==
[14:58:40.674] > 
> unpackResult==missingFiles==
> didLocalDownload==1==
> downloadTime====
> installTime==7==
> extInstallTime====
[14:58:40.684] > 
> serverStartTime====
> d30a5b351b67: end
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
[14:58:40.685] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==fedora==
arch==x86_64==
tmpDir==/run/user/1264905==
platform==linux==
unpackResult==missingFiles==
didLocalDownload==1==
downloadTime====
installTime==7==
extInstallTime====
serverStartTime====

[14:58:40.701] Resolver error: Error: Failed to install the VS Code Server
	at Function.ServerInstallError (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:63958)
	at c (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:58925)
	at Object.t.handleInstallOutput (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62799)
	at k (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
[14:58:40.707] > 
> mv: cannot stat 'vscode-server*/*': No such file or directory
[14:58:40.708] > 
> 
[14:58:40.723] ------




[14:58:44.474] "install" terminal command done
[14:58:44.475] Install terminal quit with output: mv: cannot stat 'vscode-server*/*': No such file or directory
[14:58:51.445] Unhandled rejection: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[14:58:51.463] Unhandled rejection: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Does this issue occur when all extensions are disabled?: Yes

The errors being reported in the logs are baffling because seemingly the download of vscode-server.tar.gz succeeded, but tar and mv fail. I tried deleting .vscode-server/ on the remote machine and tried rebooting it. The remote machine is a Fedora 32 instance.

**Comment by tristan957** [comment]
I was able to successfully scp vscode-server.tar.gz over using Window's scp from OpenSSH.

**Comment by tristan957** [comment]
```
$ tar --list -f vscode-server.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

This seems pretty wrong.

**Comment by tristan957** [comment]
A `cat` of the `vscode-server.tar.gz` reports:

```
<!--samlchecks_get.html --><!DOCTYPE html><html><head><title>Welcome To Zscaler Directory Authentication</title><meta name="viewport" content="width=device-width, initial-scale=1"><style type="text/css">body {    background-color: #FFF;    font-family: Arial, sans-serif;    font-size: 12px;    text-align: center;    color: #4B4F54;    overflow: hidden;    margin: 0;}a {    color: #009dd0;    cursor: pointer;    text-decoration: none;}form {    width: 100%;    height: 100%;    margin: 0;    padding: 0;}input {    font-family: Arial;    font-size: 100%;    margin: 0;    width: 100%;    vertical-align: top;    color: #424242;    display: inline-block;    border: none;    padding: 0;    text-align: left;    height: 100%;    width: calc(100% -35px);}table {    margin-top: 10px;    text-align: center;    background-color: white;}table.table-company-logo {    background-color: #e3e3e3;}table.table-upper {    border-radius: 10px;}table.table-lower {    border-bottom-left-radius: 10px;    border-bottom-right-radius: 10px;    background-color: #f3f3f3;}table.table-field-label {    margin-bottom: 2px;}table.table-field-input div.input-wrapper {    display: block;    border-color: #2a2c30;;    width: inherit;    padding-left: 10px;}table.table-field-input .input-wrapper.disabled {    border-color: #cfd0d1;}table.zsc-company {    border-bottom-left-radius: 10px;    border-bottom-right-radius: 10px;    background-color: #f3f3f3;}table.zsc-company td {    border-bottom-left-radius: 10px;    border-bottom-right-radius: 10px;    font-size: 11px;    color: #939393;}.table-half-column-fixed {    width: 356px;}table + table, td table {    margin-top: 0;}td.td-field-label {    font-size: 16px;    color: black;}td.td-field-act {    font-size: 13px;    color: #009dd0;}td.td-field-act img {    vertical-align: middle;}img {    max-height: 80px;    max-width: 430px;}img.act-icon {    padding-right:3px;}.or {    background: #ff9500;}.gr {    background: #e3e3e3;}.gy {    background: #939597;}.yl {    background: #ffc800;}.red {    background: #c20000;}.pg {    position: absolute;    top: 0;    bottom: 0;    left: 0;    right: 0;    white-space: nowrap;    height: 100%;    overflow: auto;}.pg:before {    content: "";    display: inline-block;    height: 100%;    vertical-align: middle;}.pg_cont {    display: inline-block;    vertical-align: middle;    width: 100%;}.m_tbl {    width: 90%;    min-width: 600px;    max-width: 758px;    max-height: 258px;    background: #FFF;    white-space: normal;    border: 3px solid #399c1d;    border-radius: 10px;}.m_tbl.tbl_error {    border-color: #77797c;}.eu_h.tbl_error {    color: #77797c;}.eu_h {    vertical-align: middle;    font-weight: bold;    border-radius: 10px;    font-size: 24px;    color: #399c1d;    font-weight: normal;    padding: 20px 20px 0 20px;}.sm {    font-size: 20px;    color: #696A6D;    font-weight: normal;}.eu_co {    font-size: 14px;    color: #696A6D;    white-space: normal;    padding: 0 20px;}.eu_co.bsubmit {    padding: 0 20px 20px 20px;}.eu_l {    width: 500px;    overflow: hidden;    text-overflow: ellipsis;    margin: 0 auto;    line-height: normal;}.eu_l a {    color: #0069AA;    word-break: break-word;}.bh {    min-height: 40px;    display: block;    max-height: 80px;    color: #0076A9;    font-size: 32px;    overflow: hidden;    padding-bottom: 15px;}.btn {    background: #009dd0;    color: #FFFFFF;    border-radius: 5px;    border: 2px solid #009dd0;    cursor: pointer;    display: inline-block;    height: 30px;    margin: 15px 0 15px;    font-size: 18px;    line-height: 26px;    width: auto;    padding: 0 20px;}.btn:focus, input:focus {    outline: none;}.btn:hover {    background: #fff;    color: #0076A9;}.fo {    height: 40px;    line-height: 40px;    font-size: 11px;    padding-bottom: 0px;    background-color: #f3f3f3;    width: 100%;    border-bottom-left-radius: 7px;    border-bottom-right-radius: 7px;    padding-left: 25px;}.ln {    font-size: 13px;    padding: 0 0 35px;    font-style: italic;}.pb20 {    padding-bottom: 20px;}.pb35 {    padding-bottom: 35px;}.eu_co.st {    font-size: 12px;    padding: 10px 0;    line-height: 20px;    position: relative;}.ie-label {    display: none;}.w-sp {    -webkit-animation: spinner .8s linear infinite;    animation: spinner .8s linear infinite;    border: 2.5px solid #c6c6c6;    border-radius: 100%;    display: inline-block;    height: 13px;    position: relative;    width: 13px;    vertical-align: middle;    top: -2px;    margin-right: 6px;}.w-sp.grn {    border-top-color: #399c1d;}.w-sp.gry {    border-top-color: #77797c;}@-webkit-keyframes spinner {    to {        -webkit-transform: rotate(360deg);    }}@keyframes spinner {    to {        transform: rotate(360deg);    }}.not {    color: #fd4239;    font-size: 16px;    padding-left: 0;    padding-top: 0;}.demo-icon {    color: green;}.s_img {    vertical-align: bottom;    padding-right: 5px;    background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAMCAYAAAAzmK6YAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyhpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNi1jMTExIDc5LjE1ODMyNSwgMjAxNS8wOS8xMC0wMToxMDoyMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTUgKE1hY2ludG9zaCkiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MDg4M0FBNkZBODFFMTFFNUI3RkJGMDcxMjM1MjFGQjUiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MDg4M0FBNzBBODFFMTFFNUI3RkJGMDcxMjM1MjFGQjUiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDowODgzQUE2REE4MUUxMUU1QjdGQkYwNzEyMzUyMUZCNSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDowODgzQUE2RUE4MUUxMUU1QjdGQkYwNzEyMzUyMUZCNSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PkDA4BkAAANHSURBVHja1JZpSBVhFIaveevaQpGRqaVkC5UWSiutkCVtRlaWtlhRli3+CPtREBFFBUULoVBhEYVYtEALEgZmC4ZEJBFEciuznVKIdjW098BzZbqo+c/64HGcmW++Oed873nnBjQ0NLhs5OTkuJoY8WK5GCn6CI94K26Io+K+6x8ZmZmZLd53+51bMtGiXswXax33noqzokh8FJ/aOLcBxPm8NZPd7GZnHXaLZaK735wf4oJ4IdqLUHGzjZO0OArEF9T21xGQnZ3tIZHEZuZY1b6LR2IvCY8WE0WEqBGPxUVR4nhukujL83X2LlEh7ok5Ik68F1doB1+rjBNV4hL3O4kkMYh5l0UHUSnyRJoYIyazKVcl48Zd1ibavTBLNIN+a258FltYdIVYSUXtehBS9zB3s9jH/ydEMhKPINGD9lIxTbwRw8QzMZwiWqtUix5Ici7rDCGxaIp5TJwWS0VvnrV26kkxRhBjHgUvaac/i1pI8rWYKo6ICSQ3Wwyl8hZglBWO+Sb/GP5fQ8Db2dXzwsv7TEFTRCpKyCTJdRRlFV5gwW4TY8USUS66ivHiJ3MtyR0ikneFiwSSNFmnmCJsR58gC/9RzQNlrewb25l+YrE4w7VNYr84LDaKWBKwAnwT18QukSu6NRGHyXuro3i2sycpboiw2OfRVr9YwzwkG3VlScaHfGZU3kyiWY4kB4uZ9GYves5c+DbHGSRZKx6KQF6WhtxPOdY1OfanT5NZz86LHXNCkHgRMaRwXihe4Se3xED6Pp3WiCCG6axT7HTdA2IWwfnGHXogCjksFB39CpGA1Hyjgl72Yhi25nURzK6Y7K26D8QGkkliV0OR8mp2MRkzCsboInnWVPOSXrzLMYZet4KtRyFxKNLb6Lr2g0HOlMpCoVy3Pvog8lmgpVGJQZmbfuWlBbhxIK7ppo/MODJwTTOP42KPWECvheHqO9m9c2IUPV5KL8dT0EQ+hbmo6R1ml8/nr1SyTf8jUWw4HL2HYBCFrUjSi6zK/L7NboLzjXaYh4vggqh4rWOOfcu7UOAGx/VQnvX9QAni6FvPw5rVSqxOeQQwp0bn9U0l6p9ELK7lwXnjcLw6ql7AZ6nqf/gJ+FuAAQDyhegdUpDo7QAAAABJRU5ErkJggg==") no-repeat;    width: 55px;    height: 17px;    display: inline-block;}.f_btn + .f_btn {    margin-left: 5px;}.f_btn {    display: inline-block;}.arrow-box {    padding: 15px;    position: absolute;    background: white;    text-align: left;    line-height: 16px;    width: 295px;    top: -40px;    display: none;    z-index: 10;    border: 1px solid #c2a200;    border-radius: 5px;    padding: 15px;    color: #c2a200;    font-size: 13px;}.arrow-box li {    list-style-type: none;    color: #2a2c30;}.arrow-box-left {    top: -10px;    left: -335px;}.arrow-box-left:after, .arrow-box-left:before {    left: 100%;    top: 53px;    border: solid transparent;    content: " ";    height: 0;    width: 0;    position: absolute;}.arrow-box-left:after {    border-color: transparent;    border-left-color: #FFFFFF;    border-width: 5px;    margin-top: -34px;}.arrow-box-left:before {    border-color: transparent;    border-left-color: #c2a200;    border-width: 6px;    margin-top: -35px;}.arrow-box-right {    right: -335px;    top: -20px;}.arrow-box-right:after, .arrow-box-right:before {    right: 100%;    top: 53px;    border: solid transparent;    content: " ";    height: 0;    width: 0;    position: absolute;    pointer-events: none;}.arrow-box-right:after {    border-color: transparent;    border-right-color: #FFFFFF;    border-width: 5px;    margin-top: -24px;}.arrow-box-right:before {    border-color: transparent;    border-right-color: #c2a200;    border-width: 6px;    margin-top: -25px;}.input-wrapper {    height: 30px;    line-height: 30px;    margin-bottom: 10px;    border: 1px solid #b0b0b0;    position: relative;    display: block;    width: inherit;    padding-left: 10px;}.input-wrapper div.input-wrapper-div-text {    text-align: left;    color: #b0b0b0;    max-width: 334px;    overflow: hidden;    text-overflow: ellipsis;}.input-image {    width: 17px;    display: inline-block;    vertical-align: middle;    height: auto;    float: left;    position: absolute;    top: 5px;    width: 20px;    height: 20px;    left: 7px;}.input-wrapper.dotted-border {    border: none;    border-bottom: 1px dotted #77797C;}.error-content {    overflow-y: auto;    height: auto;}.error-content li {    list-style-type: none;}.text-label-link {    height: 32px;    line-height: 32px;    margin-bottom: 10px;    text-align: left;    padding-left: 10px;    position: absolute;    top: 0px;    right: -100px;}.text-label-link.pwd {    right: -140px;}.text-label-link:before {    content: "<<";    letter-spacing: -0.15em;    padding-right: 2px;    font-size: 8px;    line-height: 11px;    color: #3892B8;    vertical-align: middle;}.username {    width: calc(100% -35px);    display: inline-block;    vertical-align: top;    color: #424242;    position: relative;    overflow: hidden;}.button-link {    width: auto;    height: auto;    background: none;    color: #0076A9;    text-decoration: underline;    cursor: pointer;    vertical-align: middle;}.hide {    display: none;}.err-tri {    width: 0;    height: 0;    border-top: 15px solid transparent;    border-bottom: 15px solid transparent;    position: absolute;    top: 40px;}.err-tri-to-left {    border-right: 15px solid #FF9130;    left: -15px;}.err-tri-to-right {    border-left: 15px solid #FF9130;    right: -15px;}.err-tri-new {    display: none;    -ms-transform: rotate(45deg);    -webkit-transform: rotate(45deg);    transform: rotate(45deg);    width: 16px;    height: 16px;    /*right: -9px;    top: 47px;*/    right: -14px;    top: 6px;    position: absolute;    border: 1px solid #c2a200;}.username_placeholder {    font: 14px/normal sans-serif;    left: 7px;    top: 8px;    width: 332px;    height: 20px;    position: absolute;    overflow-x: hidden;    font-size-adjust: none;    font-stretch: normal;    text-align: left;    color: #939393;}.username_input {    position: relative;    top: 6px;    height: 20px;    left: -27px;    z-index:15;}input.username_input {    width: 295px;}.table-left-column, .table-right-column {    width: 50%;    display: inline-block;}.table-left-column table {    padding-right: 10px;}.table-right-column table {    padding-left: 10px;}.separator {    height: 14px;    margin-left: 8px;    margin-right: 8px;    border-left: 1px #cfd0d1 solid;}hr {    background-color: #cfd0d1;    margin-top: 16px;    margin-bottom: 16px;}.eu_sh {    font-size: 16px;    color: #929496;    vertical-align: middle;    padding: 10px 20px 0 23px;}.eu_h_t {    padding-left: 23px;    font-size: 16px;    color: #2a2c30;}.eu_h_t span {    color: #009dd0;}.eu_co_aup_txt {    font-size: 13px;    color: #2a2c30;    padding: 0 20px 0 23px;}.eu_co_aup_txt div {    max-width:715px;    word-wrap: break-word;    overflow-x: hidden;}.eu_h_t_sub {    font-size: 16px;    color: #77797c;    padding: 0 0 0 23px;    display: inline-block;    padding-bottom: 15px;    margin-right: -15px;}.eu_h_t_sub_a {    padding-left: 0;    padding-bottom: 15px;    display: inline-block;    text-align: left;}.eu_h_t_sub_a a {    font-size: 16px;    color: #009dd0;    padding: 0 0 0 23px;    width: 215px;}.otp {    background-color: white;    padding-left: 0;    padding-top: 16px;    font-size:11px;}@media only screen and (max-width:640px) {    .eu_l {        width: 250px;    }    .input-wrapper {        width: 100%;    }    .arrow-box {        background: #FFFFFF;        border: 1px solid #c2a200;        width: 524px;    }    .arrow-box-right {        top: -140px;        left: -1px;    }    .arrow-box-left {        top: -80px;        left: -3px;    }    .arrow-box-left:after, .arrow-box-left:before,    .arrow-box-right:after, .arrow-box-right:before {        top: 117%;        left: 48%;        border: solid transparent;        content: " ";        height: 0;        width: 0;        position: absolute;    }    .arrow-box-right:after {        border-color: transparent;        border-top-color: #FFFFFF;        border-width: 15px;        margin-left: -15px;        margin-top: -20px;    }    .arrow-box-right:before {        border-color: transparent;        border-top-color: #c2a200;        border-width: 16px;        margin-left: -16px;        margin-top: -20px;    }    .arrow-box-left:after {        border-color: transparent;        border-top-color: #FFFFFF;        border-width: 15px;        margin-left: -15px;        margin-top: -9px;    }    .arrow-box-left:before {        border-color: transparent;        border-top-color: #c2a200;        border-width: 16px;        margin-left: -16px;        margin-top: -9px;    }    .text-label-link, .text-label-link.pwd {        right: 0;        top: 25px;    }    .table-left-column, .table-right-column {        width: 100%;        display: block;    }    .table-left-column table, .table-right-column table {        padding-left: 0;        padding-right: 0;    }    .eu_co_aup_txt div {        white-space: normal;        word-wrap: break-word;    }}@media only screen and (max-width: 480px) {    .table-half-column-fixed {        width: inherit;    }    input.username_input {        left: -2px;        width: 100%;    }    .eu_co_aup_txt div {        white-space: normal;        word-wrap: break-word;    }    .m_tbl {        min-width: 300px;    }    .pg_cont {        position: relative;        left: -3px;    }    .fo {        text-align: center;    }}</style></head><body><div class="pg gr"><div class="pg_cont"><table class="table-company-logo" width="100%" cellspacing="0" cellpadding="0"><tr><td class="bh"><img id="cmpy_info" src="https://login.zscloud.net:443/__zsig/7HHn0q0PjRZ6J"></td></tr></table><table class="m_tbl tbl_error" cellpadding="0" cellspacing="0" align="center"><tbody><tr><td valign="top"><div id="flashform"  style="display:block;"><form name="uform" method="get" action="https://login.zscloud.net:443/smsamlq" id="uform"><input type="hidden" name="urlosfc" size="25" value="origurl=https%3A%2F%2Fupdate%2ecode%2evisualstudio%2ecom%2fcommit%253A8490d3dde47c57ba65ec40dd192d014fd2113496%2fserver%2dlinux%2dx64%2fstable&amp;wexps=1&amp;_ordtok=6343WV5J3Lsrrf4tQjnZRHNr6j"><input type="hidden" name="urlodmn" size="25" value="https%3A%2F%2Fupdate%2ecode%2evisualstudio%2ecom%2fcommit%253A8490d3dde47c57ba65ec40dd192d014fd2113496%2fserver%2dlinux%2dx64%2fstable"><input type="hidden" name="saml_id" size="25" value="Mqq4kVZhZZnW6"><input type="hidden" name="samlidp" size="16" value="0000000000000000"><input type="hidden" name="jscript" size="4" value="0set"><table class="table-upper" width="100%" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td align="left" class="eu_h_t" style="padding-bottom:15px; padding-top:15px;">Please wait a moment while we launch our security service.</td></tr></tbody></table></form></div></td></tr></tbody></table></div></div><script type="text/javascript">if (document.forms && document.forms[0] && document.forms[0].jscript) {document.forms[0].jscript.value = "1set";}document.forms[0].submit();</script></body></html>
```

Which if I put in an html file and open in my browser finally downloads the actual tar.gz file.

So this seems to be a weird interaction between VSCode and my corporate networking environment where some sort of proxy checks to make sure that urls aren't blacklisted. Hmmm.....

**Comment by tristan957** [comment]
![image](https://user-images.githubusercontent.com/11936772/106956272-ff3dd980-66fb-11eb-8db0-970032fd70c0.png)

**Comment by tristan957** [comment]
File is grabbed on host machine Windows 10 which has this network proxy as seen in the previous picture.

**Comment by tristan957** [comment]
For anyone else hitting this issue, follow the steps here: https://medium.com/@debugger24/installing-vscode-server-on-remote-machine-in-private-network-offline-installation-16e51847e275. If there is an offical doc on code.visualstudio.com, someone should link that instead.

**Comment by tristan957** [comment]
Changed the name to more accurately reflect the issue as I see it currently.

**Comment by tristan957** [comment]
Of note this hasn't affected in previous versions of VSCode.

**Comment by roblourens** [comment]
Nothing has changed in how the download works. Do you know whether it was successfully downloaded on the remote side before of whether it always downloaded locally and copied it to the remote?

On the local side we just invoke `_workbench.downloadResource`, did anything change there, I think @sandy081?

**Comment by tristan957** [comment]
@roblourens it seems that it downloaded "successfully" server side, meaning it downloaded the HTML file instead of the redirect. This HTML file was then saved as vscode-server.tar.gz. It was then successfully scped onto the server, but since it was actually an HTML file, tar failed to extract.

**Comment by sandy081** [comment]
I am not aware of any changes there.

**Comment by tristan957** [comment]
This affected me again today on the point release. Haven't had time to go back to 1.52 to check, yet.

**Comment by tristan957** [comment]
I was not affected by this for the 1.54 update. I think best the course of action should be to close the issue and if it happens again I can re-open. Not sure if something changed in my corporate network or what.

**Comment by roblourens** [comment]
Thanks for the update
