### ISSUE TITLE
Integration tests: No tree view with id 'test.treeId' registered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115746]
Running integration tests, I think from 

https://github.com/microsoft/vscode/blob/376716d1aeef7f64002068308ea45a91fab25a96/extensions/vscode-api-tests/src/singlefolder-tests/rpc.test.ts#L87-L87

```
No tree view with id 'test.treeId' registered.: Error: No tree view with id 'test.treeId' registered.
    at ExtHostTreeViews.$hasResolve (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/api/common/extHostTreeViews.ts:131:10)
    at RPCProtocol._doInvokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/services/extensions/common/rpcProtocol.ts:417:17)
    at RPCProtocol._invokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/services/extensions/common/rpcProtocol.ts:402:32)
    at RPCProtocol._receiveRequest (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/services/extensions/common/rpcProtocol.ts:318:19)
    at RPCProtocol._receiveOneMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/services/extensions/common/rpcProtocol.ts:245:10)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/services/extensions/common/rpcProtocol.ts:110:42
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/common/event.ts:622:16)
    at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/ipc/common/ipc.net.ts:468:19)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts:198:22
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/common/event.ts:622:16)
    at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/ipc/common/ipc.net.ts:468:19)
    at PersistentProtocol._receiveMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/ipc/common/ipc.net.ts:821:22)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/ipc/common/ipc.net.ts:660:73
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/common/event.ts:622:16)
    at ProtocolReader.acceptChunk (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/ipc/common/ipc.net.ts:241:21)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/ipc/common/ipc.net.ts:202:51
    at Socket.listener (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/file:/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/ipc/node/ipc.net.ts:32:38)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by lszomoru** [comment]
@jrieken, I am seeing the following error in the OSS console and I believe that it is related to this fix:
_vscode.vscode-api-tests]: property `name` is mandatory and must be of type `string`_

**Comment by jrieken** [comment]
Thanks for that @lszomoru. Seems like the package.json isn't validated properly
