### ISSUE TITLE
potential listener LEAK detected, having 400 listeners

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115749]
Seeing this when running the notebook integration tests out of sources ('vscode-notebook-tests'):

```
[05b] potential listener LEAK detected, having 400 listeners already. MOST frequent listener (1):", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js (366)
[27503:0204/133051.360141:INFO:CONSOLE(367)] "    at new View (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/view/viewImpl.js:20:41)
    at CodeEditorWidget._createView (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:1196:26)
    at CodeEditorWidget._attachModel (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:1117:46)
    at CodeEditorWidget.setModel (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:253:18)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/renderers/codeCell.js:47:41", s
```

Might not be a leak at all but simply opening too many things. Still frustrating to see in the test output

//cc @alexdima

**Comment by rebornix** [comment]
This was already resolved.
