### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by therealgilles** [microsoft/vscode#116013]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.0-dev.20210201

**Steps to reproduce crash**
I have no idea, it just occurred in VSCode. Btw I'm running VSCode 1.54.0-insider on Mac OS 11.3 Beta.

**TS Server Log**
❗️Server logging disabled.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at Object.releaseDocumentWithKey (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122438:13)
    at Object.onReleaseOldSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149005:34)
    at Object.createProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:106487:26)
    at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:148973:26)
    at Proxy.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149065:13)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153950:53)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153880:42)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154848:63)
    at updateProjectIfDirty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155361:45)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157544:29)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157879:97
    at Object.flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157879:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158934:46)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160818:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160809:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160818:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160844:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:163507:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by therealgilles** [comment]
The error only showed up once. I have no way to know how to reproduce it.

**Comment by mjbvz** [comment]
Can you please share which extensions you have enabled when it happened? Not sure if one of them caused this

**Comment by therealgilles** [comment]
I don't think I had just enabled a new extension. Do you want a list of all my extensions? (and if so, is there an easy way to get that out of VSCode?)

**Comment by mjbvz** [comment]
In the extensions view, search `@installed`. You can also run `code --list-extensions` on the command line

**Comment by therealgilles** [comment]
Here you go. Lots of extensions:

```shell
> code --list-extensions
akamud.vscode-theme-onedark
alefragnani.project-manager
bmewburn.vscode-intelephense-client
bradlc.vscode-tailwindcss
codezombiech.gitignore
dbaeumer.vscode-eslint
donjayamanne.git-extension-pack
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
emilast.LogFileHighlighter
emmanuelbeziat.vscode-great-icons
esbenp.prettier-vscode
felixfbecker.php-debug
felixfbecker.php-intellisense
felixfbecker.php-pack
fisheva.eva-theme
GraphQL.vscode-graphql
humao.rest-client
Janne252.fontawesome-autocomplete
karye.prettier-php
linyang95.php-symbols
michelemelluso.code-beautifier
mikestead.dotenv
ms-azuretools.vscode-docker
ms-python.python
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
mshr-h.veriloghdl
msjsdiag.debugger-for-chrome
PKief.material-icon-theme
pnp.polacode
pranaygp.vscode-css-peek
quicktype.quicktype
streetsidesoftware.code-spell-checker
tht13.python
vscode-icons-team.vscode-icons
WallabyJs.quokka-vscode
wayou.file-icons-mac
wayou.vscode-icons-mac
wayou.vscode-todo-highlight
wix.vscode-import-cost
Yummygum.city-lights-icon-vsc
yzhang.markdown-all-in-one
zh9528.file-size
zhouronghui.propertylist
zhuangtongfa.material-theme
Zignd.html-css-class-completion
ziyasal.vscode-open-in-github
```

**Comment by mjbvz** [comment]
Have you see this issue with extensions disabled?

**Comment by therealgilles** [comment]
I have not. I don't run VSCode with extensions disabled. The issue only happened once. I only reported it because it prompted me too. Sorry for not being able to be more helpful.

**Comment by mjbvz** [comment]
Without more information, I have to assume this is caused by an extension. If you see this happen again and extensions are disabled, then please let us know
