### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by levani** [microsoft/vscode#116219]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:35:15.302Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.91GB free)|
|Process Argv|--crash-reporter-id c98f3a22-2ed7-43bf-89fe-cd320d76ddb2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
json-tools|eri|1.0.2
auto-close-tag|for|0.5.10
code-runner|for|0.11.2
vscode-graphql|Gra|0.3.15
todo-tree|Gru|0.0.196
rest-client|hum|0.24.4
vscode-peacock|joh|3.9.1
vscode-styled-components|jpo|1.5.0
git-graph|mhu|1.28.0
dotenv|mik|1.0.1
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.3
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.3.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
material-theme|zhu|3.9.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by mjbvz** [comment]
@sheetalkamat @DanielRosenwasser This looks like it may be related to the changes in 4.1.4

**Comment by sheetalkamat** [comment]
What is tsconfig file? Plugin needs to have name. so we are not checking for undefined name but we could

**Comment by daniel-white** [comment]
https://github.com/microsoft/TypeScript/issues/42712

**Comment by mjbvz** [comment]
@sheetalkamat https://github.com/microsoft/vscode/issues/116233 has a server log. I think the issue are entries like this:

```json
"plugins": [
   {
    "transform": "rbxts-transformer-t"
   },
   {
    "transform": "rbxts-transform-env"
   }
  ],
```

**Comment by upupming** [comment]
temporary fix works for me(add the `name` field): 
![image](https://user-images.githubusercontent.com/24741764/107459298-d6509500-6b90-11eb-981f-896fa8f9ab10.png)

**Comment by alopix** [comment]
Fix is to downgrade to 1.53.0 as well. https://code.visualstudio.com/updates/v1_53 has the direct download links which have the version in it, which can be changed back to the .0 release.

**Comment by ChrisCHuboo** [comment]
q

**Comment by leeahoward** [comment]
> Fix is to downgrade to 1.53.0 as well. https://code.visualstudio.com/updates/v1_53 has the direct download links which have the version in it, which can be changed back to the .0 release.

https://update.code.visualstudio.com/1.53.0/darwin/stable

**Comment by mjbvz** [comment]
This is fixed with TypeScript 4.1.5, which should go out with VS Code 1.53.2 tomorrow.

Until then, either add a fake `name` as @upupming [suggests](https://github.com/microsoft/vscode/issues/116219#issuecomment-776407990) or [switch your workspace to use TypeScript 4.1.5](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

**Comment by HolgerJeromin** [comment]
This will not get in a TS 3.9.x hotfix?
@sheetalkamat @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
3.9.9 should have the fix - are you not seeing that?

**Comment by HolgerJeromin** [comment]
> 3.9.9 should have the fix - are you not seeing that?

I was on my mobile browser and too blind to find the release. Sorry for the noise and thanks a lot!
