### ISSUE TITLE
Settings Sync commands are not visible in Accounts & Settings Gear dropdown

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#116295]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/10746682/107489944-84f0d780-6b89-11eb-9964-f304d6371647.png">

<img width="362" alt="image" src="https://user-images.githubusercontent.com/10746682/107489959-89b58b80-6b89-11eb-9b21-6f4b411c3b19.png">

**Comment by sandy081** [comment]
After some investigation, it seems accounts are not getting initialized in core.

**Comment by sandy081** [comment]
Seems to be caused by this commit - 71e56891549fdd3ff8d61d6bd6c588a450358aba

**Comment by sandy081** [comment]
It seems not just commands are not available but also settings sync is completely broken ie., sync is not happening at all because that account is not initialized.

**Comment by sandy081** [comment]
Seeing following error in the window log

```
[2021-02-10 11:22:31.399] [renderer1] [error] Error: No authentication provider 'microsoft' is currently registered.
    at AuthenticationService.getSessions (file:///Users/sandy081/work/vscode/out/vs/workbench/services/authentication/browser/authenticationService.js:569:23)
    at async UserDataSyncWorkbenchService.getAccounts (file:///Users/sandy081/work/vscode/out/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.js:131:30)
    at async UserDataSyncWorkbenchService.update (file:///Users/sandy081/work/vscode/out/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.js:119:34)
    at async UserDataSyncWorkbenchService.initialize (file:///Users/sandy081/work/vscode/out/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.js:107:13)
    at async UserDataSyncWorkbenchService.waitAndInitialize (file:///Users/sandy081/work/vscode/out/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.js:88:17)
[2021-02-10 11:22:31.400] [renderer1] [warning] Settings Sync: Accounts are not initialized
```

**Comment by sandy081** [comment]
@RMacfarlane reverted the commit (71e5689) that is causing this. Revert commit - 48e10bedc9ecc35b472e80d81ecd916576e32562. Did not build the new insiders and wait for your call.

**Comment by RMacfarlane** [comment]
The issue I was originally trying to fix is that when the codespaces extension is loading a codespace, at resolve time, it tries to  use the authentication providers. The `getSession` call is meant to activate the auth extension if it's not already active, so we send an activation event to it. The problem is that normally, the service sending this event will block on all extension hosts being up first, so it just hangs for codespaces. We have a flag that can be used to instead send the activation event eagerly, to extension hosts that already exist.

I changed to using this flag, but then settings sync also requests auth information at start up and needs to actually wait for all extension hosts to be up.

So, now am using the flag if the request to the auth service is coming from an extension, and to use the blocking call if the request is from core

**Comment by olegoid** [comment]
This one also affects Live Share.
