### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by fabio-510** [microsoft/vscode#116284]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
All I need to do is start VSCode and open my project workspace

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`c:\Users\FabiodosSantosFranco\AppData\Roaming\Code\logs\20210209T215450\exthost7\vscode.typescript-language-features\tsserver-log-8Df6ON\tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155055:44)
    at c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155395:97
    at Object.flatMap (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156413:46)
    at c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158277:28)
    at IOSession.Session.executeCommand (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158286:33)
    at IOSession.Session.onMessage (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158310:35)
    at Interface.<anonymous> (c:\Users\FabiodosSantosFranco\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (9.29GB free)|
|Process Argv|--crash-reporter-id 75990eb9-84f8-47aa-ad31-0e33692f2a78|
|Screen Reader|no|
|VM|31%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
openmatchingfiles|bca|0.5.0
armview|ben|0.4.5
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
template-generator-vscode|Den|0.4.1
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.15
vscode-element-helper|Ele|0.5.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.1
cloudcode|goo|1.8.0
vscode-test-explorer|hbe|2.19.5
rest-client|hum|0.24.4
kubernetes-snippets|ipe|0.1.9
vue-autoimport|ish|1.0.5
jenkinsfile-support|ivo|1.1.0
cypher-query-language|jak|1.0.2
docthis|joe|0.7.1
solidity|Jua|0.0.107
chat|kar|0.35.0
kite|kit|0.138.0
vsls-whiteboard|los|0.0.12
code-groovy|mar|0.1.2
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.11.0
vscode-azurevirtualmachines|ms-|0.3.0
vscode-docker|ms-|1.9.1
vscode-dotnet-runtime|ms-|1.0.0
vscode-edge-devtools|ms-|1.1.3
vscode-kubernetes-tools|ms-|1.2.4
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.53.3
azure-account|ms-|0.9.5
azurecli|ms-|0.5.0
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.6.0
vscode-node-azure-pack|ms-|0.1.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.14.1
debugger-for-edge|msj|1.0.15
vetur|oct|0.32.0
vscode-versionlens|pfl|1.0.9
vscode-yaml|red|0.14.0
sass-indented|rob|1.5.1
vscode-jest-test-adapter|rtb|0.2.0
rust|rus|0.7.8
jenkinsfile-support|sec|0.1.0
indenticator|Sir|0.7.0
element-ui-snippets|SS|0.7.2
vscode-rustfmt|sta|0.1.0
autoimport|ste|1.5.3
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.13

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by fabio-510** [comment]
Duplicate of #116219
