### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by tobylockley** [microsoft/vscode#116239]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
1. Open VS Code

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/home/toby/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.36GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/toby/github/dreamweavers-live --remote=wsl+Ubuntu --crash-reporter-id ada1c93b-4209-47ae-80c0-0fa4d503670f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|12.37GB (8.55GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
dotenv|mik|1.0.1
remote-containers|ms-|0.158.0
remote-wsl|ms-|0.53.3
mdx|sil|0.1.0
vscode-icons|vsc|11.1.0
vscode-apollo|apo|1.18.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.1
vscode-docker|ms-|1.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244:30250195
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by tobylockley** [comment]
Closed due to duplicate
