### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by ProtoCh4os** [microsoft/vscode#116317]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
1. Open a typescript project/file

The error pops after VScode tries to start TS/JS extensions.
Tried disabling all extensions, it didn't work. Since it happened literally overnight, I believe it is linked to the latest version (1.53.1).

**TS Server Log**

Info 0    [09:02:50.873] Starting TS Server
Info 1    [09:02:50.873] Version: 4.1.4
Info 2    [09:02:50.873] Arguments: /snap/code/54/usr/share/code/code /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/6761a1f53a0aa00a05c4/tscancellation-c1b74c97067756b1e610.tmp* --logVerbosity verbose --logFile /home/vcunha/.config/Code/logs/20210210T085902/exthost1/vscode.typescript-language-features/tsserver-log-Tz6Guz/tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /snap/code/54/usr/share/code/resources/app/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [09:02:50.873] Platform: linux NodeVersion: 12 CaseSensitive: true
Info 4    [09:02:50.873] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [09:02:50.887] Binding...
Info 6    [09:02:50.923] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true,"includePackageJsonAutoImports":"auto"},"watchOptions":{}}}
Info 7    [09:02:50.925] Host information vscode
Info 8    [09:02:50.925] Host watch options changed to undefined, it will be take effect for next watches.
Info 9    [09:02:50.925] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 10   [09:02:50.927] 0::configure: async elapsed time (in milliseconds) 3.4200
Info 11   [09:02:50.927] request:
    {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2016","jsx":"preserve","strictFunctionTypes":true,"sourceMap":true,"allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"resolveJsonModule":true}}}
Info 12   [09:02:50.928] Scheduled: *ensureProjectForOpenFiles*
Perf 13   [09:02:50.928] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 1.0637
Info 14   [09:02:50.928] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 15   [09:02:50.928] request:
    {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"file.ts","fileContent":"//content","projectRootPath":"/root","scriptKindName":"TS"}]}}
Info 16   [09:02:50.930] Search path: /root/api/controllers
Info 17   [09:02:50.931] ConfigFilePresence:: Current Watches: :: File: /root/api/controllers/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: file.ts Status: File added to open files impacted by this config file
Info 18   [09:02:50.931] ConfigFilePresence:: Current Watches: :: File: /root/api/controllers/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: file.ts Status: File added to open files impacted by this config file
Info 19   [09:02:50.931] ConfigFilePresence:: Current Watches: :: File: /root/api/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: file.ts Status: File added to open files impacted by this config file
Info 20   [09:02:50.931] ConfigFilePresence:: Current Watches: :: File: /root/api/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: file.ts Status: File added to open files impacted by this config file
Info 21   [09:02:50.932] ConfigFilePresence:: Current Watches: :: File: /root/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: file.ts Status: File added to open files impacted by this config file
Info 22   [09:02:50.932] For info: file.ts :: Config file name: /root/tsconfig.json
Info 23   [09:02:50.932] Opened configuration file /root/tsconfig.json
Info 24   [09:02:50.934] FileWatcher:: Added:: WatchInfo: /root/tsconfig.json 2000 undefined Project: /root/tsconfig.json WatchType: Config file
Info 25   [09:02:50.935] event:
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/root/tsconfig.json","reason":"Creating possible configured project for file.ts to open"}}
Info 26   [09:02:51.072] Config: /root/tsconfig.json : {
 "rootNames": [
     // scrubbed
 ],
 "options": {
  "target": 5,
  "module": 99,
  "moduleResolution": 2,
  "lib": [
   "lib.esnext.d.ts",
   "lib.es2018.asynciterable.d.ts",
   "lib.dom.d.ts"
  ],
  "typeRoots": [
   "/root/node_modules/@types",
   "/root/@types"
  ],
  "esModuleInterop": true,
  "allowJs": true,
  "importHelpers": true,
  "sourceMap": true,
  "allowUnusedLabels": true,
  "strict": true,
  "noEmit": true,
  "allowSyntheticDefaultImports": true,
  "experimentalDecorators": true,
  "baseUrl": "/root",
  "paths": {
   "~/*": [
    "./*"
   ],
   "@/*": [
    "./*"
   ]
  },
  "types": [
   "@types/node",
   "@nuxt/types",
   "@nuxtjs/axios",
   "@nuxtjs/vuetify"
  ],
  "plugins": [
   {
    "transform": "typescript-transform-paths"
   }
  ],
  "pathsBasePath": "/root",
  "configFilePath": "/root/tsconfig.json"
 }
}
Info 27   [09:02:51.073] DirectoryWatcher:: Added:: WatchInfo: /root 1 undefined Project: /root/tsconfig.json WatchType: Wild card directory
Info 28   [09:02:54.219] Elapsed:: 3145.9287499999627ms DirectoryWatcher:: Added:: WatchInfo: /root 1 undefined Project: /root/tsconfig.json WatchType: Wild card directory
Info 29   [09:02:54.219] Enabling plugin undefined from candidate paths: /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..,/snap/code/54/usr/share/code/resources/app/extensions/typescript-language-features
Err 30    [09:02:54.339] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"file.ts","fileContent":"//file","projectRootPath":"/root","scriptKindName":"TS"}]}}:

    Cannot read property 'indexOf' of undefined

    TypeError: Cannot read property 'indexOf' of undefined
        at Object.parsePackageName (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
        at ConfiguredProject.Project.enablePlugin (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
        at ConfiguredProject.enablePluginsWithOptions (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
        at ProjectService.loadConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
        at ProjectService.createAndLoadConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
        at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
        at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
        at /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:97
        at Object.flatMap (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
        at ProjectService.applyChangesInOpenFiles (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
        at /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:88
        at IOSession.Session.executeWithRequestId (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
        at IOSession.Session.executeCommand (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
        at IOSession.Session.onMessage (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
        at Interface.<anonymous> (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:329:10)
        at Interface._normalWrite (readline.js:474:12)
        at Socket.ondata (readline.js:186:10)
        at Socket.emit (events.js:315:20)
        at addChunk (_stream_readable.js:295:12)
        at readableAddChunk (_stream_readable.js:271:9)
        at Socket.Readable.push (_stream_readable.js:212:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
Info 31   [09:02:54.340] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":2,"success":false,"message":"Error processing request. Cannot read property 'indexOf' of undefined\nTypeError: Cannot read property 'indexOf' of undefined\n    at Object.parsePackageName (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:39472:30)\n    at ConfiguredProject.Project.enablePlugin (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:151962:24)\n    at ConfiguredProject.enablePluginsWithOptions (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152477:30)\n    at ProjectService.loadConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154206:25)\n    at ProjectService.createAndLoadConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154145:22)\n    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154150:36)\n    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155055:44)\n    at /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:97\n    at Object.flatMap (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)\n    at ProjectService.applyChangesInOpenFiles (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:41)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156413:46)\n    at /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:88\n    at IOSession.Session.executeWithRequestId (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158277:28)\n    at IOSession.Session.executeCommand (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:33)\n    at IOSession.Session.onMessage (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158310:35)\n    at Interface.<anonymous> (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160520:27)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:329:10)\n    at Interface._normalWrite (readline.js:474:12)\n    at Socket.ondata (readline.js:186:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)"}
Info 32   [09:02:54.342] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":17323}}
Info 33   [09:02:54.342] Running: *ensureProjectForOpenFiles*
Info 34   [09:02:54.342] Before ensureProjectForOpenFiles:
Info 35   [09:02:54.342] Project '/root/tsconfig.json' (Configured)
Info 35   [09:02:54.343] 	Files (0) InitialLoadPending

Info 35   [09:02:54.343] -----------------------------------------------
Info 35   [09:02:54.343] Open files: 
Info 35   [09:02:54.343] 	FileName: file.ts ProjectRootPath: /root
Info 35   [09:02:54.343] 		Projects: 

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/snap/code/54/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:30:54.166Z)
OS version: Linux x64 5.8.0-43-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 4, 3|
|Memory (System)|11.56GB (3.68GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 69a5a1c6-2741-4779-9ad1-0fb2fdb79915|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
prettier-vscode|esb|5.9.1
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
shell-format|fox|7.0.1
vscode-env|Iro|0.1.0
vscode-docker|ms-|1.9.1
vsliveshare|ms-|1.0.3629
debugger-for-chrome|msj|4.12.12
vetur|oct|0.32.0
material-icon-theme|PKi|4.5.0
quicktype|qui|12.0.46
vscode-yaml|red|0.14.0
sass-indented|syl|1.8.15
quokka-vscode|Wal|1.0.342
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by ProtoCh4os** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/116219
