### ISSUE TITLE
Pylance: Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by jajcayn** [microsoft/vscode#116448]
- VS Code Version: 1.53.1; Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
- OS Version: macOS Catalina 10.15.7 (19H512)

Steps to Reproduce:

1. open python workspace in VSCode with pylance as the language server
2. I have only three open files and already getting this error

Does this issue occur when all extensions are disabled?: Yes/No
No, since this is happening with pylance, however, pylance was not recently updated, but VSCode was, so I think it's a VSCode issue

full error:
```
[Error - 1:12:16 PM] An internal error occurred while parsing file "/Users/nikola/work-dev/neurolib/tests/test_collections.py": Error: EMFILE: too many open files, scandir '/Users/nikola/work-dev/neurolib'
    at Object.readdirSync (fs.js:959:3)
    at Object.e.readdirSync (electron/js2c/asar_bundle.js:5:10231)
    at h.readdirEntriesSync (/Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:609711)
    at B._getFilesInDirectory (/Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:160020)
    at B.resolveAbsoluteImport (/Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:152915)
    at B._resolveBestAbsoluteImport (/Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:155203)
    at B.resolveImport (/Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:147689)
    at t.SourceFile._resolveImports (/Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:254912)
    at /Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:247540
    at i.timeOperation (/Users/nikola/.vscode/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:631349)
```

I started getting this error yesterday, after update to VSCode 1.53.1; before it was fine. At first I tried to exclude folder like `logs` or `build` from search etc, but this didn't help. Before yesterday, I could open much larger workspace without any problems, no set excludes, everything just worked. Now even for rather small workspaces I am getting this error.

Thanks!

**Comment by jajcayn** [comment]
I am sorry, right now I found the same issue directly in the Pylance repository (https://github.com/microsoft/pylance-release/issues/936)
Closing this issue as it relates to pylance
