### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by borko-rajkovic** [microsoft/vscode#116447]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.7.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"c:/Users/User/Desktop/Projects/crm-core-api","hostCurrentDirectory":"C:/Users/User/AppData/Local/Programs/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"c:/Users/User/Desktop/Projects/crm-core-api","hostCurrentDirectory":"C:/Users/User/AppData/Local/Programs/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:137724:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:137710:29)
    at ProjectService.getOrCreateOpenScriptInfo (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:138113:33)
    at ProjectService.applyChangesInOpenFiles (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:138332:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:139212:46)
    at c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:140861:28)
    at IOSession.Session.executeCommand (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:140870:33)
    at IOSession.Session.onMessage (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:140893:35)
    at Interface.<anonymous> (c:\Users\User\Desktop\Projects\crm-core-api\node_modules\typescript\lib\tsserver.js:142208:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.91GB (12.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.15
prettier-vscode|esb|5.9.1
shell-format|fox|7.0.1
angular2-switcher|inf|0.3.3
jenkins-declarative-support|jmM|0.1.0
git-graph|mhu|1.28.0
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.3.3
typescript-hero|rbb|3.0.0
java|red|0.74.0
vscode-yaml|red|0.15.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
twig|wha|1.0.2
change-case|wma|1.0.0
vscode-proto3|zxh|0.5.3

</details>

**Comment by mjbvz** [comment]
Closing as this is an old TypeScript version. Let us know if you still see this using TS 4.1+
