### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by iamanshugupta** [microsoft/vscode#116471]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.0-dev.20210210

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:106348:161)
    at resolveModuleNamesWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:106598:26)
    at resolveModuleNamesReusingOldState (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:106771:19)
    at processImportedModules (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108146:35)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107948:17)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108123:21
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at processLibReferenceDirectives (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:108118:16)
    at findSourceFileWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107945:21)
    at findSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107809:26)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:85
    at getSourceFileFromReferenceWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107728:34)
    at processSourceFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107761:13)
    at processRootFile (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:107571:13)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:106453:67
    at Object.forEach (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:190:30)
    at Object.createProgram (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:106453:16)
    at synchronizeHostData (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:149068:26)
    at Proxy.getProgram (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:149160:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:154045:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:153975:42)
    at ConfiguredProject.updateGraph (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:154947:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:156697:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:157638:44)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:157978:97
    at Object.flatMap (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:157978:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:159033:46)
    at c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:160917:88
    at IOSession.Session.executeWithRequestId (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:160908:28)
    at IOSession.Session.executeCommand (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:160917:33)
    at IOSession.Session.onMessage (c:\Users\Anshu Gupta\.vscode\extensions\ms-vscode.vscode-typescript-next-4.3.20210210\node_modules\typescript\lib\tsserver.js:160943:35)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.03GB free)|
|Process Argv|--crash-reporter-id cb9ea819-06fe-49d4-9fb0-4f67dc3d111e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-deno|den|2.3.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.1
vscode-typescript-next|ms-|4.3.20210210
vscode-xml|red|0.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244:30250195
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce  with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically try disabling the  Deno extension
