### ISSUE TITLE
Cannot use GH issue notebook extension in web selfhost

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116534]
Steps to Reproduce:

1. selfhost on web locally
2. install GH issue notebook extension (installs fine)
3. click on a GH issue notebook from our repo

=> 🐛  `Activating extension 'ms-vscode.vscode-github-issue-notebooks' failed: Unexpected token '.'`

Visually I see:

![image](https://user-images.githubusercontent.com/900690/107754886-63772380-6d22-11eb-81d2-d2db3a685bcb.png)

Maybe related to auth?

**Comment by jrieken** [comment]
Works just fine with 0.0.62

**Comment by jrieken** [comment]
ping @sandy081 maybe the transition from web-enabled to not-web-enabled isn't working smoothly

**Comment by bpasero** [comment]
Yeah I was suspecting an issue like that and I think previously I had this extension explicitly installed in the remote and now it probably installs in the web worker? not sure how I can control that from the extensions viewlet...

**Comment by sandy081** [comment]
@jrieken Can you please check if you are still publishing this extension as web extension?

**Comment by jrieken** [comment]
Not doing that

**Comment by jrieken** [comment]
Has actually nothing to do with web. The extension tries to activate in the correct extension but it seems the nodejs version doesn't support the outputed JavaScript. This is the full error

```
SyntaxError: Unexpected token '.'
	at wrapSafe (internal/modules/cjs/loader.js:1053:16)
	at Module._compile (internal/modules/cjs/loader.js:1101:27)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
	at Module.load (internal/modules/cjs/loader.js:985:32)
	at Function.Module._load (internal/modules/cjs/loader.js:878:14)
	at Function.Module._load (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:37:33)
	at Function.load (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostExtensionService.js:23:37)
	at Function.load [as _load] (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/proxyResolver.js:331:37)
	at Module.require (internal/modules/cjs/loader.js:1025:19)
	at require (internal/modules/cjs/helpers.js:72:18)
	at Function.nodeRequire [as __$__nodeRequire] (/Users/jrieken/Code/vscode/out/vs/loader.js:1000:24)
	at ExtHostExtensionService._loadCommonJSModule (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostExtensionService.js:79:29)
	at ExtHostExtensionService._doActivateExtension (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionService.js:214:22)
	at ExtHostExtensionService._activateExtension (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionService.js:188:25)
	at Object.actualActivateExtension (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionService.js:56:33)
	at ExtensionsActivator._activateExtension (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionActivator.js:251:57)
	at /Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionActivator.js:236:58
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionActivator.js:236:42)
	at ExtensionsActivator.activateByEvent (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionActivator.js:127:25)
	at ExtHostExtensionService._activateByEvent (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionService.js:104:36)
	at /Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostExtensionService.js:521:33
```
