### ISSUE TITLE
Notebook smoke tests failing

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116535]
```
  24 passing (2m)
  4 pending
  1 failing

  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           inserts/edits markdown cell:
     Error: Timeout: get element '.notebook-editor .monaco-list-row.focused .monaco-editor' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:187:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)


```

**Comment by jrieken** [comment]
@roblourens this is likely due to the recent changes but I don't even know where to start investigating here...
