### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by cembreyfarquhar** [microsoft/vscode#116681]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:109644:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:109679:29)
    at Map.forEach (<anonymous>)
    at clearPerDirectoryResolutions (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:109416:50)
    at Object.finishCachingPerDirectoryResolution (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:109421:13)
    at ConfiguredProject.Project.updateGraphWorker (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151532:38)
    at ConfiguredProject.Project.updateGraph (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:151463:42)
    at ConfiguredProject.updateGraph (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152422:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154151:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/private/var/folders/dq/qtg4w1js4txb8ws2g0zjp2c80000gp/T/AppTranslocation/2B54507B-B999-4A1C-B0BA-7C75FA56546B/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|../ --crash-reporter-id d436caf5-233e-480b-87cb-5522b07f03a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-deno|den|2.3.3
prettier-vscode|esb|5.9.2
haml|vay|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by mjbvz** [comment]
Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Specifically try disabling the deno extension
