### ISSUE TITLE
Windows integration test core dump

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116671]
Noticed our windows integration tests to core dump today:

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=104970&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328

```
[main 2021-02-15T05:20:49.128Z] TypeError: Error processing argument at index 0, conversion failure from 
    at detachGuest (electron/js2c/browser_init.js:185:1419)
    at Object.<anonymous> (electron/js2c/browser_init.js:185:2838)
    at Object.onceWrapper (events.js:422:26)
    at Object.emit (events.js:327:22)
```

Dump:

[31678fdf-8204-4db5-a753-f4852b437a8e.dmp.zip](https://github.com/microsoft/vscode/files/5979857/31678fdf-8204-4db5-a753-f4852b437a8e.dmp.zip)

**Comment by deepak1556** [comment]
```
Crash reason:  Unhandled C++ Exception
Crash address: 0x7fff7bc84f38
Process uptime: 4 seconds

Thread 0 (crashed)
 0  KERNELBASE.dll!RaiseException + 0x68
    rax = 0x00007ff65ea667e4   rdx = 0x0000000000000000
    rcx = 0x0000000000000000   rbx = 0x00007fff587c1ad0
    rsi = 0x0000008efa3fdc70   rdi = 0x0000008efa3fb060
    rbp = 0x0000008efa3fb010   rsp = 0x0000008efa3faed0
     r8 = 0x0000000000000000    r9 = 0x0000000000000000
    r10 = 0x0000000000000000   r11 = 0x0000000000000000
    r12 = 0x0000008efa3fb1e0   r13 = 0x0000000000000000
    r14 = 0x0000008efa3fc4b8   r15 = 0x0000000000000000
    rip = 0x00007fff7bc84f38
    Found by: given as instruction pointer in context
 1  keytar.node + 0xa319
    rbx = 0x00007fff587c1ad0   rbp = 0x0000008efa3fb010
    rsp = 0x0000008efa3fafb0   r12 = 0x0000008efa3fb1e0
    r13 = 0x0000000000000000   r14 = 0x0000008efa3fc4b8
    r15 = 0x0000000000000000   rip = 0x00007fff587aa319
    Found by: call frame info
 2  keytar.node + 0x1ad0
    rbp = 0x0000008efa3fe010   rsp = 0x0000008efa3fb020
    rip = 0x00007fff587a1ad0
    Found by: previous frame's frame pointer
 3  0x1a91c31a8f0
    rbp = 0x0000008efa3fe120   rsp = 0x0000008efa3fe020
    rip = 0x000001a91c31a8f0
    Found by: previous frame's frame pointer
 4  Code - Insiders.exe!node::InternalCallbackScope::Close() [callback.cc : 146 + 0xd]
    rbp = 0x0000008efa3fe120   rsp = 0x0000008efa3fe030
    rip = 0x00007ff65fe1069c
    Found by: stack scanning
```

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/111288

**Comment by bpasero** [comment]
@deepak1556 did we by accident maybe enable an integration test that was disabled before for this reason?
