### ISSUE TITLE
 Error: Not supported.at OverlayContextKeyService.createScoped 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116686]
* open a notebook
* double click a markdown cell so edit it
* 🐛 

```
ERR Not supported.: Error: Not supported.
    at OverlayContextKeyService.createScoped (file:///Users/jrieken/Code/vscode/out/vs/platform/contextkey/browser/contextKeyService.js:444:19)
    at new CodeEditorWidget (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:126:72)
    at InstantiationService._createInstance (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at StatefulMarkdownCell.viewUpdateEditing (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/markdownCell.js:253:50)
    at StatefulMarkdownCell.viewUpdate (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/markdownCell.js:210:22)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/markdownCell.js:107:26
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at MarkdownCellViewModel.triggerfoldingStateChange (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/markdownCellViewModel.js:88:36)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.js:308:26
    at Array.forEach (<anonymous>)
    at NotebookViewModel.updateFoldingRanges (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.js:306:29)
    at FoldingController._updateEditorFoldingRanges (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/contrib/fold/folding.js:73:44)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/contrib/fold/folding.js:32:26
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at FoldingModel.recompute (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/contrib/fold/foldingModel.js:206:45)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/contrib/fold/folding.js:24:91
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at NotebookEventDispatcher.emit (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/eventDispatcher.js:58:52)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/markdownCellViewModel.js:46:33
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at MarkdownCellViewModel.set editState [as editState] (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.js:67:36)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:107:37
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:44:93
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
    at HTMLDivElement.fn (file:///Users/jrieken/Code/vscode/out/vs/base/browser/event.js:10:35)
```

**Comment by jrieken** [comment]
doesn't repro anymore
