### ISSUE TITLE
Rename File Disables File Tree

### ISSUE THREAD

**Issue by jkassis** [microsoft/vscode#116625]
https://github.com/microsoft/vscode/issues/95315

is happening in 1.53.1

![image](https://user-images.githubusercontent.com/3630156/107863333-7106d900-6e08-11eb-924d-80e7477deee3.png)

**Comment by isidorn** [comment]
@jkassis thanks for filling this, I can reproduce.

**Comment by isidorn** [comment]
Actually I can no longer reproduce. My steps where:
1. Type something in explorer to get the orange Filter
2. While the orange filter is shown click on the New File button -> nothing shows up

But I can no longer reproduce this.
Now just from time to time I can get this exception but nothing seems broken

@jkassis Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, do you have exact steps to reproduce? And do you see some error if you F1 > developer tools > console

```
Can't run recursive splices.: Error: Can't run recursive splices.
    at ListView.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:265:23)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:962:67
    at EventBufferer.bufferEvents (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:631:23)
    at TreeNodeList.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:962:32)
    at TreeNodeList.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:862:19)
    at Object.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:273:22)
    at IndexTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:300:23)
    at ObjectTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:157:24)
    at CompressedObjectTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:235:24)
    at CompressibleObjectTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:381:31)
    at CompressibleObjectTree.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1130:24)
    at TypeFilterController.updateOptions (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:491:23)
    at CompressibleObjectTree.updateOptions (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:997:43)
    at CompressibleObjectTree.updateOptions (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTree.js:128:19)
    at WorkbenchCompressibleAsyncDataTree.updateOptions (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:797:23)
    at ExplorerView.setEditable (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:205:31)
    at ExplorerService.setEditable (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/explorerService.js:147:29)
    at Object.onFinish (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/fileActions.js:751:39)
    at Object.<anonymous> (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerViewer.js:300:34)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/functional.js:18:25
    at HTMLInputElement.<anonymous> (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerViewer.js:338:21)
    at InputBox.focus (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/inputbox/inputBox.js:151:24)
    at FilesRenderer.renderInputBox (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerViewer.js:292:22)
    at FilesRenderer.renderElement (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerViewer.js:201:55)
    at CompressibleAsyncDataTreeRenderer.renderElement (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:741:27)
    at CompressibleRenderer.renderElement (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTree.js:64:31)
    at TreeRenderer.renderElement (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:235:27)
    at PipelineRenderer.renderElement (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:750:26)
    at ListView.insertItemInDOM (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:549:26)
    at ListView._splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:354:30)
    at ListView.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:269:29)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:962:67
    at EventBufferer.bufferEvents (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:631:23)
    at TreeNodeList.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:962:32)
    at TreeNodeList.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:862:19)
    at Object.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:273:22)
    at IndexTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:300:23)
    at ObjectTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:157:24)
    at CompressedObjectTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:235:24)
    at CompressibleObjectTreeModel.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:381:31)
    at CompressibleObjectTree.refilter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1130:24)
    at TypeFilterController.onDidSpliceModel (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:632:23)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:482:41)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:44:93
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:479:38)
    at IndexTreeModel.spliceSimple (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:165:31)
    at IndexTreeModel.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:62:22)
    at ObjectTreeModel._setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:68:24)
    at ObjectTreeModel.setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:31:18)
    at CompressedObjectTreeModel._setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:158:24)
    at CompressedObjectTreeModel.setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:119:18)
    at CompressibleObjectTreeModel.setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:319:24)
    at CompressibleObjectTree.setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTree.js:122:24)
    at WorkbenchCompressibleAsyncDataTree.render (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:647:23)
    at WorkbenchCompressibleAsyncDataTree.render (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:843:19)
    at WorkbenchCompressibleAsyncDataTree.refreshAndRenderNode (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:467:18)
    at async WorkbenchCompressibleAsyncDataTree._updateChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:320:13)
    at async WorkbenchCompressibleAsyncDataTree.updateChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:309:13)
    at async ExplorerView.setEditable (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:210:13)
    at async ExplorerService.setEditable (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/explorerService.js:147:13)
    at async openExplorerAndCreate (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/fileActions.js:747:9)
    at async handler (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/fileActions.js:761:13)
```

**Comment by jeanp413** [comment]
@isidorn created a PR https://github.com/microsoft/vscode/pull/117654 fixing the error shown in your comment https://github.com/microsoft/vscode/issues/116625#issuecomment-779250352

**Comment by isidorn** [comment]
@jeanp413 awesome, thanks
