### ISSUE TITLE
bootstrap-node.js

### ISSUE THREAD

**Issue by martinowren** [microsoft/vscode#116684]
- VS Code Version: 1.53.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
I do not know if it is a reproducible error as I cannot record doing anything special. 

Does this issue occur when all extensions are disabled?: Yes

Nothing updated etc, and this happened this morning. I have tried to upgrade and update ubuntu without any luck
```
/home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/bootstrap-node.js:1

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/cli.js:1:229)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Comment by martinowren** [comment]
Hi @aeschli !
Are you able to help me out? I have figured out that it works sometimes after rebooting the whole computer, but that is only sometimes.

**Comment by aeschli** [comment]
What are the steps that lead to this? You open a remote window?

**Comment by aeschli** [comment]
Can you run `VSCODE_WSL_DEBUG_INFO=true code .` to get more information?

**Comment by martinowren** [comment]
Yes, ofc! 
Here is the output:
```
VSCODE_WSL_DEBUG_INFO=true code .
+ COMMIT=622cb03f7e070a9670c94bae1a45d78d7181fbd4
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ DATAFOLDER=.vscode
+ realpath /mnt/s/VSCODE/bin/code
+ dirname /mnt/s/VSCODE/bin/code
+ dirname /mnt/s/VSCODE/bin
+ VSCODE_PATH=/mnt/s/VSCODE
+ ELECTRON=/mnt/s/VSCODE/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-18.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:
+ wslpath -m /mnt/s/VSCODE/resources/app/out/cli.js
+ CLI=S:/VSCODE/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/s/VSCODE/Code.exe S:/VSCODE/resources/app/out/cli.js --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\Martin\.vscode\extensions\ms-vscode-remote.remote-wsl-0.53.4
+ [ -n c:\Users\Martin\.vscode\extensions\ms-vscode-remote.remote-wsl-0.53.4 ]
+ wslpath -u c:\Users\Martin\.vscode\extensions\ms-vscode-remote.remote-wsl-0.53.4
+ WSL_CODE=/mnt/c/Users/Martin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.53.4/scripts/wslCode.sh
+ /mnt/c/Users/Martin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.53.4/scripts/wslCode.sh 622cb03f7e070a9670c94bae1a45d78d7181fbd4 stable /mnt/s/VSCODE/Code.exe code .vscode .
+ [ -z .vscode ]
+ echo .vscode
+ sed -e s/.vscode/.vscode-server/g
+ DATAFOLDER=.vscode-server
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/martinow/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu-18.04 ]
+ AUTHORITY=wsl+Ubuntu-18.04
+ [ ! -d /home/martinow/.vscode-server ]
+ dirname /mnt/c/Users/Martin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.53.4/scripts/wslCode.sh
+ /mnt/c/Users/Martin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.53.4/scripts/wslDownload.sh 622cb03f7e070a9670c94bae1a45d78d7181fbd4 stable /home/martinow/.vscode-server/bin
+ [ ! -d /home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4 ]
+ RC=0
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.jhpXtN
+ env
+ dirname /mnt/c/Users/Martin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.53.4/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/s/VSCODE/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/Martin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.53.4/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu-18.04 VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.jhpXtN VSCODE_STDIN_FILE_PATH= VSCODE_AGENT_FOLDER=/home/martinow/.vscode-server WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w: /home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/bin/code .
/home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/bootstrap-node.js:1



SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/cli.js:1:229)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
+ exit 1
```

**Comment by martinowren** [comment]
Was this enough information? @aeschli

**Comment by aeschli** [comment]
Sorry, I have no clue. I'm also not aware of any similar reports.
Maybe the install got corrupted. can you close VSCode, open a WSL shell and delete the remote server install folder: `rm -r /home/martinow/.vscode-server/bin`
