### ISSUE TITLE
Event found found onDidChangeGlobalStorage

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#116695]
Start VS Code out of source: notice exception in the dev console

fyi @bpasero

```
Event not found: onDidChangeGlobalStorage: Error: Event not found: onDidChangeGlobalStorage
    at GlobalStorageDatabaseChannel.listen (/Users/isidor/Development/vscode/out/vs/platform/storage/node/storageIpc.js:84:19)
    at ChannelServer.onEventListen (/Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.js:287:35)
    at ChannelServer.onRawMessage (/Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.js:231:33)
    at /Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.js:171:73
    at Emitter.fire (/Users/isidor/Development/vscode/out/vs/base/common/event.js:479:38)
    at /Users/isidor/Development/vscode/out/vs/base/common/event.js:44:93
    at Emitter.fire (/Users/isidor/Development/vscode/out/vs/base/common/event.js:479:38)
    at /Users/isidor/Development/vscode/out/vs/base/common/event.js:56:106
    at Emitter.fire (/Users/isidor/Development/vscode/out/vs/base/common/event.js:479:38)
    at IpcMainImpl.fn (/Users/isidor/Development/vscode/out/vs/base/common/event.js:257:44)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init
```

**Comment by bpasero** [comment]
`git clean -xfd && yarn && yarn watch`
