### ISSUE TITLE
Running integration tests: Error processing argument at index 0, conversion failure from 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116789]
* run `scripts/test-integration.sh`
* notice the following error printed eventually:

```
[main 2021-02-16T16:56:49.043Z] [uncaught exception in main]: TypeError: Error processing argument at index 0, conversion failure from 
[main 2021-02-16T16:56:49.043Z] TypeError: Error processing argument at index 0, conversion failure from 
    at detachGuest (electron/js2c/browser_init.js:177:1419)
    at Object.<anonymous> (electron/js2c/browser_init.js:177:2838)
    at Object.onceWrapper (events.js:422:26)
    at Object.emit (events.js:327:22)
```

**Comment by bpasero** [comment]
Not using webviews anymore.
