### ISSUE TITLE
 ERR MISSING extHostDocument for notebook cell:

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116711]
* config `"extensions.webWorker": true`
* open GH issue notebook
* run a cell
* save when it becomes dirty
* undo from GIT view
* run same cell again
* save, conflict prompt shows
* select revert
* 💥 the error below shows

~~Saw the error below in dev tools. No steps but must be investigated~~

```
 ERR MISSING extHostDocument for notebook cell: vscode-notebook-cell:/Users/jrieken/Code/vscode/.vscode/notebooks/my-work.github-issues#ch0000009: Error: MISSING extHostDocument for notebook cell: vscode-notebook-cell:/Users/jrieken/Code/vscode/.vscode/notebooks/my-work.github-issues#ch0000009
	at D.get cell [as cell] (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:30783)
	at file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:30082
	at Array.map (<anonymous>)
	at asApiEvent (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:30073)
	at Array.map (<anonymous>)
	at f._spliceNotebookCells (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:34591)
	at file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:33390
	at Array.forEach (<anonymous>)
	at f.acceptModelChanged (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:33239)
	at u.$acceptModelChanged (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:197696)
	at l._doInvokeHandler (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:77:77223)
	at l._invokeHandler (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:77:76915)
	at l._receiveRequest (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:77:75585)
	at l._receiveOneMessage (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:77:74387)
	at file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:77:72496
	at _.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:55:1836)
	at MessagePort.g.port1.onmessage (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:85:3488)
```

**Comment by jrieken** [comment]
To generate the API change event we need to convert the internal objects into API objects (remove, added vscode.NotebookCell-instances). This cannot be done at the same time but must happen _before_ remove deleted cell documents and _after_ inserting added cell documents.
