### ISSUE TITLE
SuggestWidget listener leak

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116773]
Running integration tests out of sources:

```
"[284] potential listener LEAK detected, having 551 listeners already. MOST frequent listener (25):", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js (366)
[93944:0216/145956.860378:INFO:CONSOLE(367)] "    at new SuggestWidget (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/contrib/suggest/suggestWidget.js:167:49)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/contrib/suggest/suggestController.js:83:59
    at IdleValue._executor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:673:35)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:682:59", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js (367)
```

**Comment by jrieken** [comment]
Not a leak. This is the theme service which seems to require zillions of listeners so that theming works. Assigning back to you and @aeschli to consider a solution that doesn't need hundreds of listeners

**Comment by jrieken** [comment]
The limit is already at 400 https://github.com/microsoft/vscode/blob/684f61b4567ade085e320d9c686ae3d25c60209a/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L123

**Comment by aeschli** [comment]
Every UI component that depends on a themable color also needs to listen to theme changes. We have lots of UI part so > 400 listeners is feasible. I don't think there's a problem with that and refactoring the code just to keep that number down is not a must.

The number of listeners alone can not be the reason alone for a LEAK warning. Does it also check that the number always rises, over a long period of time?

Perfect would be if we can detect that the listener is the reference that prevents an object from being collected.

**Comment by jrieken** [comment]
> Does it also check that the number always rises, over a long period of time?

It is not a leak, the number doesn't rise only over the months as we add more features

>  I don't think there's a problem with that and refactoring the code just to keep that number down is not a must.

I disagree. There is obviously no right number but if you have 400 listeners and each listener takes 1ms to do its thing then you have a severe perf problem. Today (didn't count listener) it takes ~100ms on my machine. 

I would say that 99% of the theme listeners adjust a color or a border-style, so this my random idea: the theme service could support css variables for which it knows what theme color defines the respective values. When a theme changes it can simply update those variable values, like a better supported variant of things like [this](https://github.com/microsoft/vscode/blob/63cbe73b2f5d363326c4bea74457edd07dc8bd63/src/vs/workbench/browser/parts/compositeBarActions.ts#L180)

**Comment by aeschli** [comment]
Yes, css-variables could help in some cases to reduce the number of listeners and are a good idea. 

If you go through our theming code you will see that many places logic is needed: If a certain color is set, use color, if not set border of that some width and color. An example for that is in the code that you linked to. 
I don't know how much is possible there with css variables.

Also I don't know that from a performance standpoint, if it is faster to use CSS variables or directly set colors/borders on dom nodes..

Also the evaluation of CSS variables can not be free for the renderer and might have to happen on every stylesheet change, vs the current solution where we only do work when when the user changes a theme or customizes a color.
