### ISSUE TITLE
ICellRange uses -1 for start and end

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116751]
The new `NotebookCellRange` asserts that start and end are position. This fails because the renderer is sending a bad range ({start: -1, end: -1}).

**Comment by jrieken** [comment]
@rebornix I have pushed a workaround but we should really get these basics right

**Comment by rebornix** [comment]
@jrieken can you please provide a call stack for this? Asking as I'm not able to reproduce locally unfortunately.

**Comment by jrieken** [comment]
Sorry, no more stack available... Let's re-enable the assertion in March wait for it to fail. Maybe the recent work in selection land has fixed this

**Comment by jrieken** [comment]
Turns out this fails when running integration tests, so should be easy to repro

1. enable the assertion [here](https://github.com/microsoft/vscode/blob/bd74308b5abbbb2f5a5df0f0d8a3bef606652d36/src/vs/workbench/api/common/extHostTypes.ts#L2909-L2910)
2. 💥 

```
Illegal argument: start must be positive: Error: Illegal argument: start must be positive
    at Object.illegalArgument (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/errors.ts:167:10)
    at new NotebookCellRange (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/common/extHostTypes.ts:2911:10)
    at /Users/jrieken/Code/vscode/out/vs/workbench/api/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/common/extHostNotebookEditor.ts:181:44
    at Array.map (<anonymous>)
    at ExtHostNotebookEditor._acceptSelections (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/common/extHostNotebookEditor.ts:181:33)
    at ExtHostNotebookController.$acceptEditorPropertiesChanged (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/common/extHostNotebook.ts:592:18)
    at RPCProtocol._doInvokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:417:17)
    at RPCProtocol._invokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:402:32)
    at RPCProtocol._receiveRequest (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:318:19)
    at RPCProtocol._receiveOneMessage (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:245:10)
    at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:110:42
    at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/event.ts:622:16)
    at BufferedEmitter.fire (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:468:19)
    at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts:198:22
    at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/event.ts:622:16)
    at BufferedEmitter.fire (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:468:19)
    at PersistentProtocol._receiveMessage (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:821:22)
    at /Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:660:73
    at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/event.ts:622:16)
    at ProtocolReader.acceptChunk (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:241:21)
    at /Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:202:51
    at Socket.listener (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/node/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/node/ipc.net.ts:32:38)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```
