### ISSUE TITLE
potential listener LEAK: TestingDecorations.attachModel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116775]
Running integration tests out of sources:

```
[93944:0216/145954.928145:INFO:CONSOLE(366)] "[7fh] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js (366)
[93944:0216/145954.928206:INFO:CONSOLE(367)] "    at TestingDecorations.attachModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/testing/browser/testingDecorations.js:46:41)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/testing/browser/testingDecorations.js:29:67
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at CodeEditorWidget.setModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:262:36)
    at NativeTextFileEditor.setInput (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/files/browser/editors/textFileEditor.js:88:28)
    at async EditorControl.doSetInput (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorControl.js:130:17)
    at async EditorControl.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorControl.js:48:35)
    at async file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:735:40
    at async EditorGroupView.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:653:48)
    at async EditorService.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/editor/browser/editorService.js:409:52)
    at async MainThreadTextEditors.$tryShowTextDocument (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadEditors.js:113:28)"
```

**Comment by bpasero** [comment]
Still seeing this:

```
[57940:0223/131931.524366:INFO:CONSOLE(366)] "[f24] potential listener LEAK detected, having 247 listeners already. MOST frequent listener (24):", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js (366)
[57940:0223/131931.524424:INFO:CONSOLE(367)] "    at new TestingOutputPeekController (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/testing/browser/testingOutputPeek.js:101:40)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at new CodeEditorWidget (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:152:69)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at CodeCellRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.js:581:47)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:46
    at Array.map (<anonymous>)
    at PipelineRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:35)
    at RowCache.alloc (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/rowCache.js:33:47)
    at ListView.insertItemInDOM (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:527:78)
    at ListView._splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:346:30)
    at ListView.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:269:29)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:67
    at EventBufferer.bufferEvents (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:631:23)
    at NotebookCellList.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:32)
    at NotebookCellList.splice2 (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:396:19)
    at NotebookCellList.attachViewModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:305:18)
    at NotebookEditorWidget._attachModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:874:24)
    at async NotebookEditorWidget.setModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:505:17)
    at async NotebookEditor.setInput (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditor.js:136:13)
    at async EditorControl.doSetInput (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorControl.js:130:17)
    at async EditorControl.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorControl.js:48:35)
    at async file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:737:40
    at async EditorGroupView.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:655:48)
```

**Comment by connor4312** [comment]
I'm not sure why it's still leaking there -- that's a registration in the constructor of an IEditorContribution, which I register in a disposable.

https://github.com/microsoft/vscode/blob/cb3a048f5af37002dd5a57f89b28de80937c1cba/src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts#L179

Is there something extra I need to do to deal with disposal in editor contributions?

**Comment by bpasero** [comment]
There is a possibility that this is not a leak but just a test creating so many of your editor contributions that we hit our limits. That limit is configurable though in code.

**Comment by connor4312** [comment]
247 listeners seems rather high for that... though I don't hit this on my machine running OSS this morning. I did find one potential leak but I doubt that any tests are hitting that.

**Comment by connor4312** [comment]
I no longer see this in CI, e.g. https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_apis/build/builds/110581/logs/427
