### ISSUE TITLE
Cannot build latest main from source

### ISSUE THREAD

**Issue by jarl-dk** [microsoft/vscode#116925]
- VS Code Version: latest main (commit 6eaef7d42f982a0e9b22ac465245fc2c27721fd0)
- OS Version: Ubuntu 20.04.2

Steps to Reproduce:

1. Checkout source code accoriding to https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run
2. Build according to https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run, that is 
```
yarn
```

This will result in
```
error /home/jarl/projects/vscode/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/jarl/projects/vscode/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python"
gyp http GET https://electronjs.org/headers/v11.2.3/node-v11.2.3-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v11.2.3/node-v11.2.3-headers.tar.gz
gyp http GET https://electronjs.org/headers/v11.2.3/SHASUMS256.txt
gyp http 200 https://electronjs.org/headers/v11.2.3/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jarl/projects/vscode/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jarl/.cache/node-gyp/11.2.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jarl/.cache/node-gyp/11.2.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/jarl/.cache/node-gyp/11.2.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/jarl/projects/vscode/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-65-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/jarl/projects/vscode/node_modules/native-keymap

```

Workaround:
It seems like this command prior to the build command (`yarn`) resolves the problem:
```
pip3 install git+https://chromium.googlesource.com/external/gyp
```

**Comment by joaomoreno** [comment]
I'm not so sure why you needed to install gyp. I'm glad it works on your system. But it seems this was something very specific to your system, since the setup works on everyone else's. Thanks for the workaround.
