### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by juslin03** [microsoft/vscode#116908]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at Object.releaseDocumentWithKey (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120762:35)
    at Object.onReleaseOldSourceFile (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146604:34)
    at Object.createProgram (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105260:26)
    at synchronizeHostData (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146572:26)
    at Proxy.getProgram (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146664:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151530:53)
    at InferredProject.Project.updateGraph (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151463:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153595:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155121:26)
    at c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155395:97
    at Object.flatMap (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156413:46)
    at c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158277:28)
    at IOSession.Session.executeCommand (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158286:33)
    at IOSession.Session.onMessage (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158310:35)
    at Interface.<anonymous> (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.04GB free)|
|Process Argv|. --crash-reporter-id cd8600c7-520e-4ba5-8e17-ecc3c5a80eae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.4.1
laravel-blade-vscode|ami|2.0.3
tailwindcss-extension-pack|and|1.1.4
blade-ui-kit|aur|1.3.0
tailwind-docs|aus|1.4.0
vscode-intelephense-client|bme|1.6.3
vscode-tailwindcss|bra|0.5.9
livewire-vscode|cie|0.2.8
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer|Coe|1.0.61
vs-phpclassgen|dam|0.1.1
vscode-eslint|dba|2.1.14
vscode-faker|dee|1.5.0
vscode-deno|den|2.3.3
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
vscode-jasmine-test-adapter|hbe|1.7.1
vscode-mocha-test-adapter|hbe|2.9.1
vscode-test-explorer|hbe|2.19.5
headwind|hey|1.7.0
adonisjs-snippets|Hri|1.0.2
rest-client|hum|0.24.4
asciimoticons|ina|1.0.1
edge|luo|0.3.2
tailwind-sass-syntax|mac|1.2.1
vscode-php-refactoring|mar|1.2.1
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-docker|ms-|1.10.0
vscode-language-pack-fr|MS-|1.53.2
mssql|ms-|1.10.1
remote-wsl|ms-|0.53.4
vscode-typescript-next|ms-|4.3.20210216
vuejs-extension-pack|mub|1.2.1
color-highlight|nau|2.3.0
back-n-forth|nic|3.1.0
vetur|oct|0.32.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.11.0
vscode-jest|Ort|3.2.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.24.0
vscode-manifest-yaml|Piv|1.24.0
vscode-spring-boot|Piv|1.24.0
material-icon-theme|PKi|4.5.0
polacode|pnp|0.3.4
java|red|0.75.0
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.27
vue-vscode-snippets|sdr|2.2.0
laravel-goto-controller|ste|0.0.12
svelte-vscode|sve|104.4.1
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.6.1
JavaScriptSnippets|xab|1.8.0
emmet-live|yse|1.0.0
material-theme|zhu|3.9.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by mjbvz** [comment]
This specific error is usually caused by the deno extension. Do you see it with the deno extension fully disabled?

/needsMoreInfo
