### ISSUE TITLE
[Fail to Settings Sync] https://vscode-sync.trafficmanager.net/ response 502

### ISSUE THREAD

**Issue by albinsun** [microsoft/vscode#116995]
Hi Guys,

Since I found that my vscode settings is not synced among my devices, and I noticed the auto sync is failed.
Today I tried manual "Settings Sync" on VSCode, it still fail with response code 502 from vscode-sync.trafficmanager.net

### My VSCode env
![vscode_env](https://user-images.githubusercontent.com/2773781/108448744-40f28680-729d-11eb-831d-91c17d1fd0fb.png)

### Detail Log
`
[2021-02-19 10:04:07.050] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2021-02-19 10:04:07.050] [userDataSync] [info] Auto Sync is disabled.
[2021-02-19 10:04:27.192] [userDataSync] [info] Did reset the local sync state.
[2021-02-19 10:04:27.864] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2021-02-19 10:04:27.873] [userDataSync] [info] Settings: Updated last synchronized settings
[2021-02-19 10:04:27.874] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
[2021-02-19 10:04:27.878] [userDataSync] [info] Keybindings: Updated last synchronized keybindings
[2021-02-19 10:04:27.879] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2021-02-19 10:04:27.884] [userDataSync] [info] Snippets: Updated last synchronized snippets
[2021-02-19 10:04:28.082] [userDataSync] [info] GlobalState: Updated remote ui state
[2021-02-19 10:04:28.090] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2021-02-19 10:04:28.091] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2021-02-19 10:04:28.096] [userDataSync] [info] Extensions: Updated last synchronized extensions
[2021-02-19 10:04:28.103] [userDataSync] [info] Auto Sync: Started
[2021-02-19 10:04:28.103] [userDataSync] [info] Auto Sync: Triggered by Interval
[2021-02-19 10:06:38.680] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/machines/latest","status":502}
[2021-02-19 10:06:38.680] [userDataSync] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 502
    at E.request (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:174253)
    at async E.read (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:169208)
    at async qe.readMachinesData (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:133107)
    at async qe.getMachines (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:131762)
    at async t.doSync (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:145956)
[2021-02-19 10:06:38.680] [userDataSync] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 502
    at E.request (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:174253)
    at async E.read (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:169208)
    at async qe.readMachinesData (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:133107)
    at async qe.getMachines (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:131762)
    at async t.doSync (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:145956)

Any Comment?

**Comment by albinsun** [comment]
I found https://vscode-sync.trafficmanager.net seems block/ not reached in my local network, will check it first, thanks.
