### ISSUE TITLE
[uncaught exception in sharedProcess]: disposed: Error: disposed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117012]
Saw this crash running out of sources (macOS, ARM) simply quitting VSCode right after it started:

```
[11445:0219/083545.381187:INFO:CONSOLE(206)] "%c  ERR color: #f33 [uncaught exception in sharedProcess]: disposed: Error: disposed
    at Client.requestPromise (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.cp.js:56:39)
    at Object.call (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.cp.js:47:33)
    at Proxy.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:844:58)
    at LocalPtyService._disposePtyHost (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/terminal/electron-browser/localPtyService.js:135:29)
    at Object.dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/terminal/electron-browser/localPtyService.js:64:26)
    at dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:77:27)
    at DisposableStore.clear (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:137:17)
    at DisposableStore.dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:130:18)
    at LocalPtyService.dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:171:25)
    at LocalPtyService.dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/terminal/electron-browser/localPtyService.js:97:19)
    at dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:77:27)
    at DisposableStore.clear (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:137:17)
    at DisposableStore.dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:130:18)
    at SharedProcessMain.dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:171:25)
    at EventEmitter.onExit (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:20:39)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js (206)
```

**Comment by bpasero** [comment]
I cannot reproduce this anymore, @Tyriar feel free to close if you think this is fine

**Comment by Tyriar** [comment]
I'll double check
