### ISSUE TITLE
Error output during notebook integration tests

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117300]
Tests pass but I see this repeated many times in integration test output

https://github.com/microsoft/vscode/runs/1956972277#step:13:260

```
Cannot read property 'start' of undefined: TypeError: Cannot read property 'start' of undefined
    at NotebookCellOutline._recomputeState (file:///home/runner/work/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.js:324:63)
    at file:///home/runner/work/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.js:256:22
    at Emitter.fire (file:///home/runner/work/vscode/vscode/out/vs/base/common/event.js:479:38)
    at file:///home/runner/work/vscode/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditor.js:110:110
    at Emitter.fire (file:///home/runner/work/vscode/vscode/out/vs/base/common/event.js:479:38)
    at NotebookEditorWidget.set viewModel [as viewModel] (file:///home/runner/work/vscode/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:153:36)
    at NotebookEditorWidget._attachModel (file:///home/runner/work/vscode/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:775:28)
    at async NotebookEditorWidget.setModel (file:///home/runner/work/vscode/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:505:17)
    at async NotebookEditor.setInput (file:///home/runner/work/vscode/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditor.js:136:13)
    at async EditorControl.doSetInput (file:///home/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:130:17)
    at async EditorControl.openEditor (file:///home/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:48:35)
    at async file:///home/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:737:40
    at async EditorGroupView.openEditor (file:///home/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:655:48)
    at async EditorService.openEditor (file:///home/runner/work/vscode/vscode/out/vs/workbench/services/editor/browser/editorService.js:451:52)
```

**Comment by jrieken** [comment]
That means we don't have a selection: https://github.com/microsoft/vscode/blob/5e067109a3c88c397e52083664f3db10fc2830e0/src/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.ts#L392
