### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117378]
Output from integration test run

```
[57940:0223/131925.879298:INFO:CONSOLE(366)] "[6ga] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js (366)
[57940:0223/131925.879348:INFO:CONSOLE(367)] "    at DebugEditorContribution.registerListeners (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/browser/debugEditorContribution.js:189:51)
    at new DebugEditorContribution (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/browser/debugEditorContribution.js:148:18)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at new CodeEditorWidget (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:152:69)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at CodeCellRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.js:581:47)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:46
    at Array.map (<anonymous>)
    at PipelineRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:35)
    at RowCache.alloc (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/rowCache.js:33:47)
    at ListView.insertItemInDOM (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:527:78)
    at ListView._splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:346:30)
    at ListView.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:269:29)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:67
    at EventBufferer.bufferEvents (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:631:23)
    at NotebookCellList.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:32)
    at NotebookCellList.splice2 (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:396:19)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:258:30
    at Array.forEach (<anonymous>)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:243:41
```

**Comment by bpasero** [comment]
Also:

```
[57940:0223/131931.427925:INFO:CONSOLE(367)] "    at BreakpointEditorContribution.registerListeners (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/browser/breakpointEditorContribution.js:237:51)
    at new BreakpointEditorContribution (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/browser/breakpointEditorContribution.js:126:18)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at new CodeEditorWidget (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:152:69)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at CodeCellRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.js:581:47)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:46
    at Array.map (<anonymous>)
    at PipelineRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:35)
    at RowCache.alloc (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/rowCache.js:33:47)
    at ListView.insertItemInDOM (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:527:78)
    at ListView._splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:346:30)
    at ListView.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:269:29)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:67
    at EventBufferer.bufferEvents (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:631:23)
    at NotebookCellList.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:32)
    at NotebookCellList.splice2 (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:396:19)
    at NotebookCellList.attachViewModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:305:18)
    at NotebookEditorWidget._attachModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:874:24)
    at async NotebookEditorWidget.setModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:505:17)
```

**Comment by bpasero** [comment]
And:

```
[57940:0223/131931.442698:INFO:CONSOLE(367)] "    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:67:118
    at Array.map (<anonymous>)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:67:105
    at new CallStackEditorContribution (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/browser/callStackEditorContribution.js:101:156)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at new CodeEditorWidget (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:152:69)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at CodeCellRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.js:581:47)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:46
    at Array.map (<anonymous>)
    at PipelineRenderer.renderTemplate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:757:35)
    at RowCache.alloc (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/rowCache.js:33:47)
    at ListView.insertItemInDOM (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:527:78)
    at ListView._splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:346:30)
    at ListView.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:269:29)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:67
    at EventBufferer.bufferEvents (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:631:23)
    at NotebookCellList.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:974:32)
    at NotebookCellList.splice2 (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:396:19)
    at NotebookCellList.attachViewModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:305:18)
    at NotebookEditorWidget._attachModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:874:24)
    at async NotebookEditorWidget.setModel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:505:17)
    at async NotebookEditor.setInput (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/notebook/browser/notebookEditor.js:136:13)
    at async EditorControl.doSetInput (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorControl.js:130:17)
    at async EditorControl.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorControl.js:48:35)
    at async file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:737:40
    at async EditorGroupView.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:655:48)
```

**Comment by isidorn** [comment]
These stack traces make no sense and I am not sure what action can I do.
All of them lead to code like this            ` this.toDispose.push(this.debugService.onDidChangeState((state) => {`
And I do not see how that can throw an exception

I will wait for @rebornix to fix his integration tests exceptions as they might potentially cause these false alarms.

**Comment by bpasero** [comment]
@isidorn they are all related to our leak detector:

`potential listener LEAK detected`

**Comment by rebornix** [comment]
With https://github.com/microsoft/vscode/commit/cb3a048f5af37002dd5a57f89b28de80937c1cba, I'm not seeing above leaks anymore locally. Let's see if CI is good.

**Comment by isidorn** [comment]
@bpasero thanks however, I still do not understand how a listener leak can happen.
I have an editor contribution that in the constructor adds a bunch of listeners.
It has a dispose(), in the dispose I dispose all the listeners.

The only explanation I have is that this is a false positive and that too many editors were being created or somehitng

@rebornix ok that makes sense. If the CI is good feel free to close this one

**Comment by rebornix** [comment]
@isidorn you are 100% correct. The monaco editors are created quickly (around 30ish) but not disposed when notebook editors are closed, thus it generated hundreds of event listeners during notebook tests. My fix disposes the editor which then clears listeners bind on it so the event listeners amount is reasonable again.

The leak protection can be false negative sometimes when there are many (20+) tiny editors open but for this case, we should dispose editors as early as possible. Previously we have 10 individual event emitters on a cell, which can also lead to this exception by even just opening a single notebook document, which will then slow down the file opening as this leak protection prints call stack. To fix this, we merge most event emitters on the cell to a single emitter. This is `false negative` but something to be aware of as it might hurt due to call stack printing.

**Comment by rebornix** [comment]
From latest CI https://github.com/microsoft/vscode/runs/1963179551, notebook test is slient now.

**Comment by isidorn** [comment]
Thanks for fixing and for writing an explanation.
