### ISSUE TITLE
Integration test failure in tasks

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117446]
```
 1) vscode API - tasks
       Tasks
         CustomExecution task should start and shutdown successfully:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: 0 == 1
      + expected - actual

      -0
      +1

      at D:\a\vscode\vscode\extensions\vscode-api-tests\src\singlefolder-tests\workspace.tasks.test.ts:58:13
      at Emitter.fire (d:\a\vscode\vscode\out\vs\base\common\file:\D:\a\vscode\vscode\src\vs\base\common\event.ts:622:16)
      at ExtHostTerminalService.$acceptTerminalProcessData (d:\a\vscode\vscode\out\vs\workbench\api\common\file:\D:\a\vscode\vscode\src\vs\workbench\api\common\extHostTerminalService.ts:372:33)
      at RPCProtocol._doInvokeHandler (d:\a\vscode\vscode\out\vs\workbench\services\extensions\common\file:\D:\a\vscode\vscode\src\vs\workbench\services\extensions\common\rpcProtocol.ts:417:17)
      at RPCProtocol._invokeHandler (d:\a\vscode\vscode\out\vs\workbench\services\extensions\common\file:\D:\a\vscode\vscode\src\vs\workbench\services\extensions\common\rpcProtocol.ts:402:32)
      at RPCProtocol._receiveRequest (d:\a\vscode\vscode\out\vs\workbench\services\extensions\common\file:\D:\a\vscode\vscode\src\vs\workbench\services\extensions\common\rpcProtocol.ts:318:19)
      at RPCProtocol._receiveOneMessage (d:\a\vscode\vscode\out\vs\workbench\services\extensions\common\file:\D:\a\vscode\vscode\src\vs\workbench\services\extensions\common\rpcProtocol.ts:245:10)
      at d:\a\vscode\vscode\out\vs\workbench\services\extensions\common\file:\D:\a\vscode\vscode\src\vs\workbench\services\extensions\common\rpcProtocol.ts:110:42
      at Emitter.fire (d:\a\vscode\vscode\out\vs\base\common\file:\D:\a\vscode\vscode\src\vs\base\common\event.ts:622:16)
      at BufferedEmitter.fire (d:\a\vscode\vscode\out\vs\base\parts\ipc\common\file:\D:\a\vscode\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:468:19)
      at d:\a\vscode\vscode\out\vs\workbench\services\extensions\node\file:\D:\a\vscode\vscode\src\vs\workbench\services\extensions\node\extensionHostProcessSetup.ts:198:22
      at Emitter.fire (d:\a\vscode\vscode\out\vs\base\common\file:\D:\a\vscode\vscode\src\vs\base\common\event.ts:622:16)
      at BufferedEmitter.fire (d:\a\vscode\vscode\out\vs\base\parts\ipc\common\file:\D:\a\vscode\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:468:19)
      at PersistentProtocol._receiveMessage (d:\a\vscode\vscode\out\vs\base\parts\ipc\common\file:\D:\a\vscode\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:821:22)
      at d:\a\vscode\vscode\out\vs\base\parts\ipc\common\file:\D:\a\vscode\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:660:73
      at Emitter.fire (d:\a\vscode\vscode\out\vs\base\common\file:\D:\a\vscode\vscode\src\vs\base\common\event.ts:622:16)
      at ProtocolReader.acceptChunk (d:\a\vscode\vscode\out\vs\base\parts\ipc\common\file:\D:\a\vscode\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:241:21)
      at d:\a\vscode\vscode\out\vs\base\parts\ipc\common\file:\D:\a\vscode\vscode\src\vs\base\parts\ipc\common\ipc.net.ts:202:51
      at Socket.listener (d:\a\vscode\vscode\out\vs\base\parts\ipc\node\file:\D:\a\vscode\vscode\src\vs\base\parts\ipc\node\ipc.net.ts:32:38)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.push (_stream_readable.js:212:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

From: https://github.com/microsoft/vscode/runs/1963674590#step:15:448

**Comment by alexr00** [comment]
@Tyriar since there haven't been many tasks changes recently.

**Comment by Tyriar** [comment]
From @alexr00: 

> it doesn't look like this is coming from ExtHostTerminalService. Instead, it looks like onDidWriteTerminalData is occuring before onDidOpenTerminal.

**Comment by bpasero** [comment]
Test is disabled now.

**Comment by alexr00** [comment]
@Tyriar is there any case where `onDidWriteTerminalData` should occur before `onDidOpenTerminal`? Is this something I should be trying to fix in tasks?

**Comment by Tyriar** [comment]
Maybe if it's from another terminal, from the terminal launched in the test no.

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/commit/c8fc575275d561f1f8cb85787a8546a6508df0c4, improved the tests in https://github.com/microsoft/vscode/commit/f8c41a80b0de335456cf2738a4095254075164a8 and https://github.com/microsoft/vscode/commit/88d9e2b46b7cfbbf3480c5f28db2c46a484ad033
