### ISSUE TITLE
Notebook API tests integration test fails

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117611]
https://github.com/microsoft/vscode/runs/1971338717?check_suite_focus=true

```
 1) Notebook API tests
       editor open/close event:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

[main 2021-02-24T15:50:57.213Z] [uncaught exception in main]: TypeError: Error processing argument at index 0, conversion failure from 
[main 2021-02-24T15:50:57.214Z] TypeError: Error processing argument at index 0, conversion failure from 
    at detachGuest (electron/js2c/browser_init.js:177:1419)
    at Object.<anonymous> (electron/js2c/browser_init.js:177:2838)
    at Object.onceWrapper (events.js:422:26)
    at Object.emit (events.js:327:22)
```

**Comment by rebornix** [comment]
The code has been changed significantly since then and we haven't seen this one failing recently. Closing now and we can reopen when we see it again.
