### ISSUE TITLE
potential listener LEAK detected: StatefullMarkdownCell

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117675]
While editing release notes I saw leak warnings. All invocations of [viewUpdate](https://github.com/microsoft/vscode/blob/a8c82939a7a9ab3ea1d44bf0d51bfc1a516c376f/src/vs/workbench/contrib/notebook/browser/view/renderers/markdownCell.ts#L156-L156), without resetting the local disposables is bogous. I'd say it is best to to clear the disposables inside the bind function

```
[0c3] potential listener LEAK detected, having 263 listeners already. MOST frequent listener (58):
check @ workbench.desktop.main.js:formatted:9500
workbench.desktop.main.js:formatted:9501     at i.bindEditorListeners (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2108:115608)
    at i.viewUpdateEditing (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2108:112800)
    at i.viewUpdate (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2108:112226)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2108:109969
    at a.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1246:6265
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:578:14197
    at a.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
```

<img width="1131" alt="Screenshot 2021-02-25 at 13 07 05" src="https://user-images.githubusercontent.com/1794099/109151428-73ebbd00-776a-11eb-99b8-8d3b53d5d4bd.png">

**Comment by jrieken** [comment]
@mjbvz ping for [`// first time, readonly mode`](https://github.com/microsoft/vscode/blob/6b3313141de8b7196e671129ea97c6bc15e5201a/src/vs/workbench/contrib/notebook/browser/view/renderers/markdownCell.ts#L81-L81). There seems to be a misunderstanding because you can enter this branch repeatedly. I believe 6b3313141de8b7196e671129ea97c6bc15e5201a fixes all issues here but please take a look at the  web view rendering which might be subject to the same leakage

**Comment by mjbvz** [comment]
I think this looks good. I've removed the the comment since it was incorrect
