### ISSUE TITLE
Mismatched vscode engine between vscode-pylance and vscode-jupyter

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#117986]
@mlcdf commented on [Tue Mar 02 2021](https://github.com/microsoft/vscode-jupyter/issues/4992)

Hello,

I have the following error when I try to install vscode-pylance on my machine (VS Code 1.53.2):

[2021-03-02 12:07:18.629] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.","    at [redacted]/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostAgent.js:107:91185","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]

I think this is due to this commit : https://github.com/microsoft/vscode-jupyter/pull/4883/files

Workaround: I downgraded to vscode-jupyter to v2021.2.0 and vscode-pylance to v2021.2.3 and it works.

---

@DonJayamanne commented on [Tue Mar 02 2021](https://github.com/microsoft/vscode-jupyter/issues/4992#issuecomment-789031065)

Thanks for filing this issue.
Did you attempt to install the pylance extension from the marketplace? or did you download the extensions.
Do you have the Python extension installed, & did you install that form the marketplace?

---

@zdog234 commented on [Tue Mar 02 2021](https://github.com/microsoft/vscode-jupyter/issues/4992#issuecomment-789042466)

I'm having the same issue trying to install from the marketplace (WSL 2 ubuntu 20.04)

Install works on windows side, but getting the above error when installing into WSL using marketplace GUI or `code --install-extension`

checking if the workaround will work for me

---

@zdog234 commented on [Tue Mar 02 2021](https://github.com/microsoft/vscode-jupyter/issues/4992#issuecomment-789048041)

hmm,
I have jupyter `2021.2.0` installed in windows and WSL, and pylance `2021.2.3` is installed in windows, but when I try to install pylance in WSL (using the marketplace GUI), I'm getting `Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.`

Should I try downloading a pylance version and installing it locally? (Can I just install it from WSL, or should it be a two-step process of `code --install-extension` in windows first, then WSL?)

Sors for the walls of text

---

@DonJayamanne commented on [Tue Mar 02 2021](https://github.com/microsoft/vscode-jupyter/issues/4992#issuecomment-789058038)

We're looking into this issue. 
# Temporary Work around
As a temporary work around, please download this Jupyter extension and install it https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.2.603412351/vspackage

The link above is from the marketplace and points to a version thats compatible with the stable version of VS Code.

**Comment by mlcdf** [comment]
> Did you attempt to install the pylance extension from the marketplace? or did you download the extensions.

Yes I tried to install the pylance extension from the marketplace

> Do you have the Python extension installed, & did you install that form the marketplace?

Yes, I do have the Python extension installed and it was installed from the marketplace.

I should add I didn't manage to use the workaround I described to install the pylance extension on a remote server (since from the marketplace, there is no way to select the extension version you want to install on the remote server).

**Comment by sandy081** [comment]
@DonJayamanne / @mlcdf Thanks for filing the issue. I am sorry that it is not clear to me what is the issue and how to reproduce it? I quickly tried to install the pylance extension on my desktop and everything seems to fine. Can you please provide me the steps to repro?

**Comment by jakebailey** [comment]
I think this has something to do with the Jupyter extension's insiders, which marks its engine as `1.54.0-insiders`.

**Comment by jakebailey** [comment]
But, I'm not sure that this is even a problem, because it says in the logs that the user's VS Code version is 1.53.2, and if the version the jupyter extension wants is 1.54.0-insiders, then it will fail to install, and this manifests as a Pylance installation failure because Pylance depends on Python which depends on Jupyter...

**Comment by ROGERDJQ** [comment]
Same problem happened in remote ssh

**Comment by mlcdf** [comment]
> But, I'm not sure that this is even a problem, because it says in the logs that the user's VS Code version is 1.53.2, and if the version the jupyter extension wants is 1.54.0-insiders, then it will fail to install, and this manifests as a Pylance installation failure because Pylance depends on Python which depends on Jupyter...

This is my take too. This is not a VS Code problem, this is related to the jupyter extension requiring 1.54.0-insiders while the pylance extension (and the python extension ?) does not. Hence the issue title and where it was originally submitted.

Here's my setup:

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to reproduce:
- Install Python extension v2021.2.582707922. This will also install the Jupyter extension v2021.2.603412351
- Try to install the Pylance extension v2021.3.0

```
[2021-03-04 10:00:49.695] [renderer1] [error] Error while installing 'ms-python.vscode-pylance' extension in the remote server. getaddrinfo ENOTFOUND ms-python.gallery.vsassets.io
[2021-03-04 10:00:49.695] [renderer1] [info] Trying to download 'ms-python.vscode-pylance' extension locally and install
[2021-03-04 10:01:36.900] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.","    at [redacted]/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostAgent.js:107:91185","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-04 10:01:36.929] [renderer1] [error] ["downloading: getaddrinfo ENOTFOUND ms-python.gallery.vsassets.io","    at K.downloadInstallableExtension (/[redacted]/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostAgent.js:107:97006)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-04 10:01:36.982] [renderer1] [error] getaddrinfo ENOTFOUND ms-python.gallery.vsassets.io: downloading: getaddrinfo ENOTFOUND ms-python.gallery.vsassets.io
    at K.downloadInstallableExtension (/[redacted]/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostAgent.js:107:97006)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-04 10:02:45.900] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
```
I assume the download errors are noise: I'm behind a proxy and have set https_proxy and http_proxy correctly and can install other extensions without issue.

**Comment by jakebailey** [comment]
How is it the case that you installed the Python extension successfully, though? Wouldn't the same check been made there? What's special about installing Pylance that makes it fail, versus a direct dep?

**Comment by zdog234** [comment]
Does pylance depend on jupyter directly? Or only through python?

**Comment by mlcdf** [comment]
@jakebailey: I didn't try to uninstall the Python extension and reinstall it. The Python extension was already installed (for a long time) when I tried to install the Pylance extension. But yeah, it seems weird. Maybe the upgrade process is different than the first install process?

**Comment by jakebailey** [comment]
> Does pylance depend on jupyter directly? Or only through python?

Only through Python.

**Comment by mlcdf** [comment]
Updating to VS Code 1.54 fixed this issue. I manage to install the Pylance extension and update the Python and Jupyter extension to their last version.

**Comment by sandy081** [comment]
@DonJayamanne I am closing this issue in VS Code. I would request to investigate from the extension side and let us know if there is something not working as expected in VS Code. It would be great if you can also provide steps to repro in that case. Thanks.

**Comment by DonJayamanne** [comment]
@sandy081 Not sure how you want me to investigate this, as we are not in control of installing extensions and VS Code is responsible for this (i.e. there's absolutely no extension code involved here).

Also the error message is one that's returned by VS Code, hence VS Code is what's falling over.

FYI - we also have users reporting this issue in our marketplace https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details

Please could you reopen this issue, else please provide details of the logs you need form us.

**Comment by ROGERDJQ** [comment]
I have upgraded to 1.54.2, however, on my remote(ssh)  machine，with python extension v2021.2.636928669, and jupyter v2021.3.619093157,  I have failure on installion of  pylance2021.3.1. The error message is "[error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.2'.""

**Comment by sandy081** [comment]
@DonJayamanne You are right that VS Code owns installing extensions and validating the engine. I was not able to reproduce this on Desktop and assumed probably an issue with the set up or something. 

Can you please provide steps to reproduce it?

**Comment by karmadog** [comment]
I have vscode version 1.53.2 (I think it was latest stable when I downloaded it) and I have downloaded the .vsix file for remote ssh and python, and both give me the error that they are incompatible when I try to install from the files.  I can't use the marketplace, I have to install from files.  Should I change to a different version of vscode?

**Comment by mlcdf** [comment]
@karmadog upgrading to VS Code 1.54.x solved the issue for me.

**Comment by karmadog** [comment]
@mlcdf it worked for me too! Thanks

**Comment by DonJayamanne** [comment]
@sandy081 Looks like the problem was users having older VS Code engines.
Closing this for now.

**Comment by nhtrnm** [comment]
I have this error when I try to install Python extension on my remote:

Error (from Log (Window)):
```
[2021-03-16 12:42:16.337] [renderer1] [error] Error while installing 'ms-python.python' extension in the remote server. self signed certificate in certificate chain
[2021-03-16 12:42:16.337] [renderer1] [info] Trying to download 'ms-python.python' extension locally and install
[2021-03-16 12:42:21.403] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.1'.","    at /u/nguyenh/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:97446","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-16 12:42:21.418] [renderer1] [error] ["downloading: self signed certificate in certificate chain","    at Ee.downloadInstallableExtension (/u/nguyenh/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:103265)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-16 12:42:21.448] [renderer1] [error] self signed certificate in certificate chain: downloading: self signed certificate in certificate chain
    at Ee.downloadInstallableExtension (/u/nguyenh/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:103265)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Version (from Help->About):
```
Version: 1.54.1 (system setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

I managed to install Python extension version 2021.2.633441544 from VSIX which installed Jupyter version 2021.3.619093157. The extension bar then notified me that I should update Python extension to version 2021.2.636928669 which I failed to do with the aforementioned error.

**Comment by passionsfrucht** [comment]
I hope that this seems not like a simple "me too" report, but I am having the same issue.

I have a setup of using vscode from windows hosts and a mac as well. Locally everything is fine, at least on the mac and IIRC yesterday on the windows host, too. But when accessing the Linux remote via SSH I run into the same error:

```
[2021-03-20 23:09:46.133] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.","    at /home/[XXX]/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:97447","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-20 23:09:46.186] [renderer1] [error] Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.: Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.
    at /home/[XXX]/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:97447
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I think I have seen it locally on the windows host on WSL, too.

Happy to provide logs, if you like.

And it does not look like it is solved for me. Those and I think all extensions are installed via the marketplace.

Not sure if it matters, but I sync my extensions and further settings with `shan.code-settings-sync`, so this might influence version solving?

**Comment by sandy081** [comment]
Please follow #119073 for further discussion on this. There is some active discussion about the issue and what could have caused it there.
