### ISSUE TITLE
Git Commit -m automatically fails upon using it in a third split terminal

### ISSUE THREAD

**Issue by fineon** [microsoft/vscode#117995]
- VS Code Version: 1.53.2
- OS Version: Windows 10, ver. 18363.1379

Steps to Reproduce:

1. Open 3 terminals in VS Code
2. Enter `git add` -> then `git commit -m `
3. Upon entering a quotation mark for the commit message "", terminal will warn me this error:
```
Oops, something went wrong.  Please report this bug with the details below.       
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 25 Keys:
 g i t Space a d d Space . Enter
 g i t Space c o m m i t Space - m Space 
"

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)   
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I believe this is fixed by installing the preview version of the PS extension https://github.com/PowerShell/PSReadLine/issues/1306
