### ISSUE TITLE
Testing Context menu, Can not able to click the Context Menu of CustomTreeItem

### ISSUE THREAD

**Issue by neelima2012** [microsoft/vscode#117958]
Package.json file has below menu Item
```json
"menus": {
      "view/item/context": [
        {
          "command": "createDL",
          "when": "viewItem == createDL",
          "group": "navigation"
        }
}
```

In Test script:
openContextMenu() of CustomTreeItem showing the menu and am getting the below exception, Not executing next lines of code

```
Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-menu-container"}
  (Session info: chrome=83.0.4103.122)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Mac OS X 10.15.7 x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /Users/nekoppol/edge-components/vscode_extension/node_modules/selenium-webdriver/lib/http.js:441:30
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.findElement(By(css selector, .monaco-menu-container))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/monaco-page-objects/out/components/AbstractElement.js:39:48)
      at new Menu (node_modules/monaco-page-objects/out/components/menu/Menu.js:17:1)
      at new ContextMenu (node_modules/monaco-page-objects/out/components/menu/ContextMenu.js:20:9)
      at CustomTreeItem.<anonymous> (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:44:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:5:58)
      at runMicrotasks (<anonymous>)
```

Help me to solve this issue

**Comment by aeschli** [comment]
Sorry I clue how and if VSCode is involved here.
Is it maybe a problem in https://github.com/redhat-developer/vscode-extension-tester#readme

**Comment by alexr00** [comment]
> In Test script:

Can you share your test script?
