### ISSUE TITLE
TerminalInstanceService.getTerminalLayoutInfo: Error: Method not implemented

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117953]
Run `yarn web` out of sources:

```
  ERR Method not implemented.: Error: Method not implemented.
    at TerminalInstanceService.getTerminalLayoutInfo (http://localhost:8080/static/out/vs/workbench/contrib/terminal/browser/terminalInstanceService.js:69:19)
    at TerminalService._reconnectToLocalTerminals (http://localhost:8080/static/out/vs/workbench/contrib/terminal/browser/terminalService.js:130:68)
    at new TerminalService (http://localhost:8080/static/out/vs/workbench/contrib/terminal/browser/terminalService.js:78:56)
    at InstantiationService._createInstance (http://localhost:8080/static/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at http://localhost:8080/static/out/vs/platform/instantiation/common/instantiationService.js:202:63
    at IdleValue._executor (http://localhost:8080/static/out/vs/base/common/async.js:689:35)
    at http://localhost:8080/static/out/vs/base/common/async.js:698:59
```

**Comment by Tyriar** [comment]
This may get fixed as a result of https://github.com/microsoft/vscode/issues/117257.

**Comment by Tyriar** [comment]
This looks like it's already fixed, I also pushed a change to prevent a terminal being created in `yarn web` which was causing another log. The only other one I see is a known issue that happens in all windows to be fixed in March https://github.com/microsoft/vscode/issues/119200

**Comment by bpasero** [comment]
When I click into terminal panel, out and back in I still see this though:

```
ERR Could not create terminal when process support is not registered: Error: Could not create terminal when process support is not registered
    at TerminalService.createTerminal (http://localhost:8080/static/out/vs/workbench/contrib/terminal/browser/terminalService.js:783:23)
    at http://localhost:8080/static/out/vs/workbench/contrib/terminal/browser/terminalView.js:87:51
    at Emitter.fire (http://localhost:8080/static/out/vs/base/common/event.js:479:38)
    at TerminalViewPane.setVisible (http://localhost:8080/static/out/vs/workbench/browser/parts/views/viewPane.js:143:53)
    at http://localhost:8080/static/out/vs/workbench/browser/parts/views/viewPaneContainer.js:495:37
    at Array.map (<anonymous>)
    at ViewPaneContainer.setVisible (http://localhost:8080/static/out/vs/workbench/browser/parts/views/viewPaneContainer.js:495:18)
    at PaneContainerPanel.setVisible (http://localhost:8080/static/out/vs/workbench/browser/panecomposite.js:35:83)
    at PanelPart.showComposite (http://localhost:8080/static/out/vs/workbench/browser/parts/compositePart.js:171:23)
    at PanelPart.doOpenComposite (http://localhost:8080/static/out/vs/workbench/browser/parts/compositePart.js:76:18)
```
