### ISSUE TITLE
Finding installed ssh failed: spawn ENOTDIR

### ISSUE THREAD

**Issue by initial-wu** [microsoft/vscode#118164]
- VS Code Version: 1.54.1
- OS Version: macOS Big Sur

Steps to Reproduce:

1. update VS Code to 1.54.1
2. connect to the ssh remote server

```
[12:19:55.078] Log Level: 2
[12:19:55.079] remote-ssh@0.65.0
[12:19:55.079] darwin x64
[12:19:55.080] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22646576436c6f7564227d", attempt 1
[12:19:55.080] "remote.SSH.useLocalServer": true
[12:19:55.080] "remote.SSH.sshPath": undefined
[12:19:55.080] "remote.SSH.sshConfigurationFile": undefined
[12:19:55.080] "remote.SSH.useFlock": true
[12:19:55.080] "remote.SSH.lockfilesInTmp": false
[12:19:55.081] "remote.SSH.localServerDownload": auto
[12:19:55.081] "remote.SSH.remoteServerListenOnSocket": false
[12:19:55.081] "remote.SSH.showLoginTerminal": false
[12:19:55.081] "remote.SSH.defaultExtensions": []
[12:19:55.081] SSH Resolver called for host: devCloud
[12:19:55.081] Setting up SSH remote "devCloud"
[12:19:55.083] Acquiring local install lock: /var/folders/33/rdh80fdx5tx9dllx9pm_rgh80000gn/T/vscode-remote-ssh-devCloud-install.lock
[12:19:55.089] Looking for existing server data file at /Users/initialwu/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-devCloud-f30a9b73e8ffc278e71575118b6bf568f04587c8-0.65.0/data.json
[12:19:55.089] Using commit id "f30a9b73e8ffc278e71575118b6bf568f04587c8" and quality "stable" for server
[12:19:55.091] Install and start server if needed
[12:19:55.094] Checking ssh with "ssh -V" /
[12:19:55.096] Finding installed ssh failed: spawn ENOTDIR
[12:19:55.099] Resolver error: Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at Object.spawn (child_process.js:557:9)
	at /Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:141963
	at new Promise (<anonymous>)
	at k (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:141856)
	at I (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:141807)
	at /Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:145955
	at _ (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:146020)
	at C (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:141586)
	at Object.t.getSshCommandPath (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:144740)
	at Function.create (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:262422)
	at async Object.t.tryInstallWithLocalServer (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:387826)
	at async /Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:293745
	at async Object.t.withShowDetailsEvent (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:407000)
	at async /Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:387151
	at async S (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:383919)
	at async Object.t.resolveWithLocalServer (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:386778)
	at async Object.t.resolve (/Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:1:297757)
	at async /Users/initialwu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.0/out/extension.js:127:110485
[12:19:55.101] ------
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by initial-wu** [comment]
I got the same error when i tried to uninstall the Remote Development extension pack

![image](https://user-images.githubusercontent.com/17722900/110067073-e1709c80-7dad-11eb-917e-0fc81be7f77d.png)

**Comment by omeraloni** [comment]
Got the same issue as well, macOS Big Sur 11.2.2

VSCode
- Version: 1.54.0
- Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
- Date: 2021-03-03T02:17:59.499Z
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Darwin x64 20.3.0

Seems also to be affected on remote containers.

**Comment by omeraloni** [comment]
Confirming that downgrade to [1.53.2](https://code.visualstudio.com/updates/v1_53) solved the issue for both SSH and containers.

**Comment by noce2** [comment]
I'm having the same `spawn ENOTDIR` error when I try to open Jupyter notebooks. My setup is:

Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**Comment by brunogoossens** [comment]
I Got the same issue. Same versions as above. Fixed it with downgrading

**Comment by leandroyalet** [comment]
ty @tamuratak, I cleaned my PATH variable and now the error is gone

> I cannot reproduce this issue. However, this issue might occur when the `PATH` environment variable includes a file, not a directory. See [microsoft/pylance-release/issues/1021](https://github.com/microsoft/pylance-release/issues/1021). Other environment variables including a file, not a directory, might be the cause.

**Comment by roblourens** [comment]
Can you clarify what you changed in your PATH?

**Comment by roblourens** [comment]
And, can someone clarify what the error is for Remote-Containers and share whatever screenshot or log might look useful?
