### ISSUE TITLE
Python extension does not install

### ISSUE THREAD

**Issue by siweiwang24** [microsoft/vscode#118298]
- VS Code Version: 1.54.1
- OS Version:  19042.844

I'm unable to update to the latest Python extension (2021.2.625869727) when using VS Code with WSL through Remote-WSL. 

Remote-Server Logs
```text
[2021-03-06 00:34:06.366] [remoteagent] [info] [::ffff:172.17.48.1][fc5438f9][ManagementConnection] New connection established.
[2021-03-06 00:34:06.367] [remoteagent] [info] [::ffff:172.17.48.1][20b8bdb8][ExtensionHostConnection] New connection established.
[2021-03-06 00:34:06.373] [remoteagent] [info] [::ffff:172.17.48.1][20b8bdb8][ExtensionHostConnection] <12098> Launched Extension Host Process.
[2021-03-06 00:35:13.456] [remoteagent] [trace] Started scanning user extensions
[2021-03-06 00:35:13.474] [remoteagent] [trace] Scanned user extensions: 14
[2021-03-06 00:35:13.822] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/siwei/AppData/Local/Temp/76eeddcd-d407-4408-8fcf-6a63a0dce7dd
```

Window Logs
```text
[2021-03-06 00:36:05.730] [renderer1] [trace] CommandService#executeCommand setContext
[2021-03-06 00:36:09.022] [renderer1] [trace] Download 'ms-python.python' extension locally and install
[2021-03-06 00:36:09.101] [renderer1] [trace] RequestService#request https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2021.2.625869727/1614990784004/Microsoft.VisualStudio.Code.Manifest
[2021-03-06 00:36:09.111] [renderer1] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-03-06 00:36:09.176] [renderer1] [trace] RequestService#request https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2021.4.625511240/1614979825331/Microsoft.VisualStudio.Code.Manifest
[2021-03-06 00:36:09.179] [renderer1] [trace] ExtensionGalleryService#download ms-toolsai.jupyter
[2021-03-06 00:36:09.180] [renderer1] [trace] RequestService#request https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter/2021.4.625511240/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&update=true
[2021-03-06 00:36:11.094] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.1'.","    at /home/siweiw/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:97446","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-06 00:36:11.118] [renderer1] [error] Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.1'.: Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.1'.
    at /home/siweiw/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:97446
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-06 00:36:12.923] [renderer1] [trace] CommandService#executeCommand notification.clear
```

**Comment by sandy081** [comment]
/duplicate

#117986
