### ISSUE TITLE
Uncaught errors (from Git extension?) causing test failures in vscode-test

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#118253]
- VS Code Version: 1.54.1 (I think?)
- OS Version: OS X test pipeline

Recently our build pipelines for the Docker extension have all begun failing on Mac specifically (Linux and Windows do not show this misbehavior). I think the failures began when 1.54.0 was released yesterday--older commits of our code, which built fine before, now fail in exactly the same way. What's strange is only some of our tests are failing, but it is somewhat consistent which...

The error:

```
     Uncaught Error: read ENOTCONN
  	at tryReadStart (net.js:573:20)
  	at Socket._read (net.js:584:5)
  	at Socket.Readable.read (_stream_readable.js:467:10)
  	at Socket.read (net.js:624:39)
  	at new Socket (net.js:376:12)
  	at Object.Socket (net.js:267:41)
  	at createSocket (internal/child_process.js:314:14)
  	at ChildProcess.spawn (internal/child_process.js:437:23)
  	at Object.spawn (child_process.js:557:9)
  	at t.Git.spawn (.vscode-test/vscode-darwin-1.54.1/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:89263)
  	at t.Git._exec (.vscode-test/vscode-darwin-1.54.1/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:88431)
  	at t.Git.exec (.vscode-test/vscode-darwin-1.54.1/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:88272)
  	at t.Git.getRepositoryRoot (.vscode-test/vscode-darwin-1.54.1/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:87521)
  	at g.openRepository (.vscode-test/vscode-darwin-1.54.1/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:10:406906)
  	at n (.vscode-test/vscode-darwin-1.54.1/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:24277)
  	at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

The build logs are public and can be viewed here: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=31684&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b7b7a6e6-b49b-50ea-fca3-f91483add993

**Comment by ejizba** [comment]
Fwiw we saw these errors, too. I got it working again by downgrading the agent from "macOS-latest" to "macOS-10.14". Not sure if that means the agent was the problem or if there's still some underlying VS Code issue...

**Comment by bwateratmsft** [comment]
Good to know, I'll try that.

**Comment by patroza** [comment]
The same error occurs just on my Mac starting VSCode on certain repositories.

**Comment by ashgti** [comment]
I believe this error is happening because the child process output streams do not have an `.on('error')` handler registered.

I had the same type of stack trace occur for child processes spawned by my extension.

**Comment by ashgti** [comment]
I believe you could add an `on('error')` handler to `child.stdout` and `child.stderr` here https://github.com/microsoft/vscode/blob/a699ffaee62010c4634d301da2bbdb7646b8d1da/extensions/git/src/git.ts#L214-L229 to fix this issue.
