### ISSUE TITLE
Cannot use Remote Explorer - SSH client

### ISSUE THREAD

**Issue by ivo-urbanek** [microsoft/vscode#118403]
- VS Code Version: 1.54.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code
2. Clict to Remote Exploerer -> Connect to Host in New Window -> Select my Linux host and path to some place

VS Code did not open path, the error message is shown: **"d.getRemoteAuthority is not a function"**

Does this issue occur when all extensions are disabled?: I need extensions. 
Uninstall and new install today tried. New SSH server container (`~/vscode-server` folder) also installed by your extension.

Before last release everything worked.

Thank to resolve it.

**Comment by roblourens** [comment]
Where do you see that error? Any other details that you can share?

**Comment by ivo-urbanek** [comment]
The error is shown in the right bottom corner. 

1. I am using system installer downloaded from https://code.visualstudio.com/docs/?dv=win64
2. Connection: VS Code on Windows 10 - developer machine with Ubuntu 2004 (both are x64 platforms)
3. On the Linux machine the folder `~/vscode-server` has been deleted

Follow these steps:

## Step 1 - use Explorer for connection to the remote machine
![image](https://user-images.githubusercontent.com/20557185/110382086-b363b480-805a-11eb-92ec-bede23eb126a.png)

## Step 2 - choose a path
![image](https://user-images.githubusercontent.com/20557185/110382137-c4142a80-805a-11eb-86fa-f954ac3281b5.png)

## Step 3 - Error
![image](https://user-images.githubusercontent.com/20557185/110382162-cfffec80-805a-11eb-861d-42c060cffab2.png)

Please let me know if you need more details (and specify them).
Thank you for your attention.

**Comment by roblourens** [comment]
Thanks. Does the window reload between step 2 and step 3? Or that notification just shows up when clicking OK?

Can you check the developer tools console (Help > Toggle Dev Tools) for that error? Hopefully it has a stack trace with it.

Does it work to open a folder directly from the remote explorer (one of the ones that says php, react, etc)

**Comment by ivo-urbanek** [comment]
You welcome. 
* The window does not reload, notification shows up immediately after the button is clicked. 

The error stack trace is here:
```
  | onDidChangeNotification | @ | notificationsAlerts.ts:38
  | (anonymous) | @ | notificationsAlerts.ts:26
  | fire | @ | event.ts:622
  | addNotification | @ | notifications.ts:206
  | error | @ | notificationService.ts:58
  | (anonymous) | @ | actions.ts:98
  | async function (async) |   |  
  | (anonymous) | @ | actions.ts:96
  | invokeFunction | @ | instantiationService.ts:61
  | _tryExecuteCommand | @ | commandService.ts:84
  | (anonymous) | @ | commandService.ts:73
  | Promise.then (async) |   |  
  | executeCommand | @ | commandService.ts:73
  | open | @ | openerService.ts:47
  | open | @ | openerService.ts:178
  | async function (async) |   |  
  | open | @ | openerService.ts:171
  | (anonymous) | @ | viewPane.ts:555
  | fire | @ | event.ts:622
  | (anonymous) | @ | button.ts:103
```

* If I try to open remote folder directly, it fails too but without any visible notification. At console I found:
```
  ERR d.getRemoteAuthority is not a function: TypeError: d.getRemoteAuthority is not a function
    at Je.doResolveRemoteOpenable (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:56:41211)
    at Je.resolveOpenable (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:56:41089)
    at Je.doExtractPathsFromAPI (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:56:38734)
    at Je.getPathsToOpen (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:56:37800)
    at Je.open (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:56:31023)
    at nt.doOpenWindow (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:50:45203)
    at nt.openWindow (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:50:45073)
    at Object.call (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:21:8153)
    at m.onPromise (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:8424)
    at m.onRawMessage (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:7783)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:7036
    at b.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1836)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:45878
    at b.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1836)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:46044
    at b.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1836)
    at IpcMainImpl.G (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:47661)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9210)
    at Object.emit (events.js:315:20)
``` 
Problematic function is at `windowsMainService.ts` on the line 833 - maybe, it looks fine.
(https://github.com/microsoft/vscode/blob/main/src/vs/platform/windows/electron-main/windowsMainService.ts#L833)

I hope you have got more information about the issue.

**Comment by bpasero** [comment]
@roblourens the owner of remote is @aeschli
