### ISSUE TITLE
Remote-container: "Error: Port Not Found"

### ISSUE THREAD

**Issue by minilia75** [microsoft/vscode#118534]
Hi there,

When starting a container with remote-container I get "Error: Port not found" after this following step:
Run in container: /home/vscode/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/server.sh --force-disable-user-env --use-host-proxy --port 0 --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --start-server

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

Here is the complete log:

[22 ms] Remote-Containers 0.163.1 in VS Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8).
[1539 ms] Start: Resolving Remote
[1542 ms] Setting up container for folder or workspace: c:\Users\Lenovo\Documents\Nck_research\Nck_workspace.code-workspace
[1547 ms] Start: Check Docker is running
[1547 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2348 ms] Server API version: 1.41
[2366 ms] Start: Run: git rev-parse --show-cdup
[2373 ms] findLocalWindowsExecutable: Exectuable 'git' not found on PATH 'C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_2004.2021.222.0_x64__79rhkp1fndgsc;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps;C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Lenovo\AppData\Roaming\npm'.
[2377 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\Lenovo\Documents\Nck_research --filter label=vsch.quality=stable
[3059 ms] Start: Run: docker inspect --type container 3e3f11c4af66
[3779 ms] Start: Starting container
[3780 ms] Start: Run: docker start 3e3f11c4af669ae83024e769596c2414ec569674dd3dec6d02473dad4c38899c
[5462 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\Lenovo\Documents\Nck_research --filter label=vsch.quality=stable
[6211 ms] Start: Run: docker inspect --type container 3e3f11c4af66
[6873 ms] Start: Inspecting container
[6874 ms] Start: Run: docker inspect --type container 3e3f11c4af669ae83024e769596c2414ec569674dd3dec6d02473dad4c38899c
[7565 ms] Start: Run: docker exec -i -u vscode -e VSCODE_REMOTE_CONTAINERS_SESSION=6da79aea-9bcf-467f-97f9-cf85714c7d8a1615287802684 3e3f11c4af669ae83024e769596c2414ec569674dd3dec6d02473dad4c38899c /bin/sh
[7580 ms] Start: Run in container: uname -m
[8201 ms] x86_64
[8201 ms] 
[8202 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[8206 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[8207 ms] 
[8207 ms] Start: Run in container: cat /etc/passwd
[8216 ms] Start: Setup shutdown monitor
[8217 ms] Forking shutdown monitor: c:\Users\Lenovo\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.1\dist\shutdown\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-c44ff4033313e180ac9d1093e32c660be8e0dfd1-sock singleContainer Info c:\Users\Lenovo\AppData\Roaming\Code\logs\20210309T120214\exthost1\ms-vscode-remote.remote-containers 1615287806035
[8235 ms] Start: Run in container: test -d /home/vscode/.vscode-server
[8241 ms] 
[8242 ms] 
[8242 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[8267 ms] 
[8267 ms] 
[8268 ms] Exit code 2
[8268 ms] Start: Run in container: cat /home/vscode/.vscode-server/data/Machine/settings.json
[8275 ms] {
        "terminal.integrated.shell.linux": "/bin/bash",
        "python.pythonPath": "/usr/local/bin/python",
        "python.linting.enabled": true,
        "python.linting.pylintEnabled": true,
        "python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
        "python.formatting.blackPath": "/usr/local/py-utils/bin/black",
        "python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
        "python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
        "python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
        "python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
        "python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
        "python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
        "python.linting.pylintPath": "/usr/local/py-utils/bin/pylint"
}
[8276 ms] 
[8277 ms] Start: Run in container: test -d /home/vscode/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8
[8284 ms] 
[8284 ms] 
[8284 ms] Start: Run in container: test -d /vscode/vscode-server/bin/x64/f30a9b73e8ffc278e71575118b6bf568f04587c8
[8289 ms] 
[8290 ms] 
[8290 ms] Start: Run: docker exec -i -u root 3e3f11c4af669ae83024e769596c2414ec569674dd3dec6d02473dad4c38899c /bin/sh
[8291 ms] Start: Launching Remote-Containers helper.
[8292 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[8305 ms] Start: Run in container: touch '/vscode/vscode-server/bin/x64/f30a9b73e8ffc278e71575118b6bf568f04587c8'
[8313 ms] findLocalWindowsExecutable: Exectuable 'gpgconf' not found on PATH 'C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_2004.2021.222.0_x64__79rhkp1fndgsc;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps;C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Lenovo\AppData\Roaming\npm'.
[8318 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-889d90c40eebce81e3adfbe4210d35b9b30abaf0.js' >/tmp/vscode-remote-containers-889d90c40eebce81e3adfbe4210d35b9b30abaf0.js
[8341 ms] 
[8341 ms] 
[8341 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-889d90c40eebce81e3adfbe4210d35b9b30abaf0.js' >/tmp/vscode-remote-containers-server-889d90c40eebce81e3adfbe4210d35b9b30abaf0.js
[8358 ms] 
[8358 ms] 
[8358 ms] Start: Run: docker exec -i -u vscode -e REMOTE_CONTAINERS_SOCKETS=["/tmp/vscode-ssh-auth-889d90c40eebce81e3adfbe4210d35b9b30abaf0.sock"] -e REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-889d90c40eebce81e3adfbe4210d35b9b30abaf0.sock 3e3f11c4af669ae83024e769596c2414ec569674dd3dec6d02473dad4c38899c /home/vscode/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node /tmp/vscode-remote-containers-server-889d90c40eebce81e3adfbe4210d35b9b30abaf0.js
[9008 ms] 
[9008 ms] 
[9009 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { /home/vscode/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node /tmp/vscode-remote-containers-889d90c40eebce81e3adfbe4210d35b9b30abaf0.js $*; }; f' || true
[9025 ms] 
[9025 ms] 
[9025 ms] Start: Preparing Extensions
[9026 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[9045 ms] 
[9046 ms] 
[9046 ms] Exit code 2
[9052 ms] Start: Run in container: test -d /home/vscode/.vscode-server/extensionsCache && ls /home/vscode/.vscode-server/extensionsCache || true
[9078 ms] grapecity.gc-excelviewer-3.0.41
ms-azuretools.vscode-docker-1.10.0
ms-python.python-2021.1.502429796
ms-python.python-2021.2.576481509
ms-python.python-2021.2.582707922
ms-python.python-2021.2.625869727
ms-toolsai.jupyter-2020.12.414227025
ms-toolsai.jupyter-2021.2.576440691
ms-toolsai.jupyter-2021.2.603412351
[9078 ms] 
[9079 ms] Start: Run in container: test -d /vscode/vscode-server/extensionsCache && ls /vscode/vscode-server/extensionsCache || true
[9096 ms] grapecity.gc-excelviewer-3.0.41
ms-azuretools.vscode-docker-1.10.0
ms-python.python-2021.1.502429796
ms-python.python-2021.2.576481509
ms-python.python-2021.2.582707922
ms-python.python-2021.2.625869727
ms-toolsai.jupyter-2020.12.414227025
ms-toolsai.jupyter-2021.2.576440691
ms-toolsai.jupyter-2021.2.603412351
[9096 ms] 
[9097 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[9273 ms] Start: Starting VS Code Server
[9274 ms] Start: Run in container: /home/vscode/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/server.sh --force-disable-user-env --use-host-proxy --port 0 --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --start-server
[9357 ms] Error: Port not found
        at kj (c:\Users\Lenovo\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.1\dist\extension\extension.js:129:911)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async zn (c:\Users\Lenovo\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.1\dist\extension\extension.js:102:6698)
        at async Ag (c:\Users\Lenovo\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.1\dist\extension\extension.js:186:9372)
        at async PP (c:\Users\Lenovo\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.1\dist\extension\extension.js:186:6756)
        at async lV (c:\Users\Lenovo\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.1\dist\extension\extension.js:167:7710)

**Comment by chrmarti** [comment]
Could you try removing the `vscode-server/bin/x64/f30a9b73e8ffc278e71575118b6bf568f04587c8` folder from the `vscode` Docker volume? It appears that install somehow got corrupted.
