### ISSUE TITLE
Listener leak in Ports view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#118544]
To repro, cause the Ports view to rerender several times. This can be done by trying to set a label and escaping out about 8 times. 

```
event.ts:487 [b1g] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:487
_event @ event.ts:565
Menu @ menuService.ts:70
createMenu @ menuService.ts:30
renderActionBarItem @ tunnelView.ts:371
renderElement @ tunnelView.ts:342
renderElement @ tableWidget.ts:78
renderElement @ listWidget.ts:1025
insertItemInDOM @ listView.ts:768
_splice @ listView.ts:522
splice @ listView.ts:426
(anonymous) @ splice.ts:17
splice @ splice.ts:17
(anonymous) @ listWidget.ts:1331
bufferEvents @ event.ts:792
splice @ listWidget.ts:1331
splice @ tableWidget.ts:224
rerender @ tunnelView.ts:707
(anonymous) @ tunnelView.ts:730
fire @ event.ts:622
setEditable @ remoteExplorerService.ts:721
(anonymous) @ tunnelView.ts:867
(anonymous) @ tunnelView.ts:864
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
_doDispatch @ abstractKeybindingService.ts:262
_dispatch @ abstractKeybindingService.ts:179
(anonymous) @ keybindingService.ts:260
event.ts:488     at new Menu (file:///D:/repos/Microsoft/vscode/out/vs/platform/actions/common/menuService.js:63:53)
    at MenuService.createMenu (file:///D:/repos/Microsoft/vscode/out/vs/platform/actions/common/menuService.js:30:20)
    at ActionBarRenderer.renderActionBarItem (file:///D:/repos/Microsoft/vscode/out/vs/workbench/contrib/remote/browser/tunnelView.js:304:67)
    at ActionBarRenderer.renderElement (file:///D:/repos/Microsoft/vscode/out/vs/workbench/contrib/remote/browser/tunnelView.js:278:26)
    at TableListRenderer.renderElement (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/table/tableWidget.js:45:26)
    at PipelineRenderer.renderElement (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:762:26)
    at ListView.insertItemInDOM (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:539:26)
    at ListView._splice (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:349:26)
    at ListView.splice (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:269:29)
    at file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:989:67
    at EventBufferer.bufferEvents (file:///D:/repos/Microsoft/vscode/out/vs/base/common/event.js:631:23)
    at List.splice (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:989:32)
    at WorkbenchTable.splice (file:///D:/repos/Microsoft/vscode/out/vs/base/browser/ui/table/tableWidget.js:147:23)
    at rerender (file:///D:/repos/Microsoft/vscode/out/vs/workbench/contrib/remote/browser/tunnelView.js:592:47)
    at file:///D:/repos/Microsoft/vscode/out/vs/workbench/contrib/remote/browser/tunnelView.js:610:17
    at Emitter.fire (file:///D:/repos/Microsoft/vscode/out/vs/base/common/event.js:479:38)
    at RemoteExplorerService.setEditable (file:///D:/repos/Microsoft/vscode/out/vs/workbench/services/remote/common/remoteExplorerService.js:611:39)
    at file:///D:/repos/Microsoft/vscode/out/vs/workbench/contrib/remote/browser/tunnelView.js:754:47
    at new Promise (<anonymous>)
    at file:///D:/repos/Microsoft/vscode/out/vs/workbench/contrib/remote/browser/tunnelView.js:751:28
    at InstantiationService.invokeFunction (file:///D:/repos/Microsoft/vscode/out/vs/platform/instantiation/common/instantiationService.js:44:24)
    at CommandService._tryExecuteCommand (file:///D:/repos/Microsoft/vscode/out/vs/workbench/services/commands/common/commandService.js:74:59)
    at file:///D:/repos/Microsoft/vscode/out/vs/workbench/services/commands/common/commandService.js:64:47
```

**Comment by jrieken** [comment]
@alexr00 is this a bad leak? Like does it leak just 1 listener per interaction or does it grow faster than that?

**Comment by isidorn** [comment]
No more leak, works as expected -> verified
