### ISSUE TITLE
Error while updating extension. Please check the log for more details.

### ISSUE THREAD

**Issue by daridimas** [microsoft/vscode#118706]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Cannot update

Error while updating extension. Please check the log for more details.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.44GB (3.98GB free)|
|Process Argv|--crash-reporter-id dadcd87f-1a34-4452-8cd0-625e3f752277|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
beautify|Hoo|1.5.0
jupyter|ms-|2021.2.576440691
java|red|0.75.0
vscode-spotify|shy|3.2.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-icons|vsc|11.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by daridimas** [comment]
Sore for late respond

this log..

`[2021-03-27 10:24:03.472] [renderer1] [error] XHR failed: downloading: XHR failed
    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)
    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)
[2021-03-27 12:28:54.059] [renderer1] [error] getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
[2021-03-27 12:33:19.754] [renderer1] [error] ["downloading: XHR failed","    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)","    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)"]
[2021-03-27 12:33:19.758] [renderer1] [error] XHR failed: downloading: XHR failed
    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)
    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)
[2021-03-27 12:33:29.494] [renderer1] [error] ["downloading: XHR failed","    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)","    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)"]
[2021-03-27 12:33:29.516] [renderer1] [error] ["downloading: XHR failed","    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)","    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)"]
[2021-03-27 12:33:29.518] [renderer1] [error] XHR failed: downloading: XHR failed
    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)
    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)
[2021-03-27 12:49:35.755] [renderer1] [error] XHR failed: downloading: XHR failed
    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)
    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)
[2021-03-27 12:55:16.380] [renderer1] [error] XHR failed: downloading: XHR failed
    at G.downloadInstallableExtension (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211806)
    at async G.doInstallFromGallery (file:///C:/Users/dimas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)
[2021-03-27 12:58:53.229] [renderer1] [error] getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

`

**Comment by sandy081** [comment]
```
XHR failed: downloading: XHR failed
```

It seems you have some network issues connecting to the Marketplace to download extensions, please check that.

Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
