### ISSUE TITLE
Potential leak when folding and unfolding notebook cells

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#118782]
## Repro
1. In a notebook
2. Create a markdown cell with a  `h1` and multiple markdown cells below that are being edited
3. Now rapidly fold and unfold the h1 cell to hide and then show the cells being edited

## Bug
```
[b84] potential listener LEAK detected, having 400 listeners already. MOST frequent listener (1)
event.ts:488     at new View (file:///Users/matb/projects/vscode/out/vs/editor/browser/view/viewImpl.js:20:41)
    at CodeEditorWidget._createView (file:///Users/matb/projects/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1209:26)
    at CodeEditorWidget._attachModel (file:///Users/matb/projects/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1122:46)
    at CodeEditorWidget.setModel (file:///Users/matb/projects/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:253:18)
    at file:///Users/matb/projects/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/markdownCell.js:291:33
```

**Comment by mjbvz** [comment]
@roblourens I'm not very familiar how notebook code editors work so could you please take a look?

**Comment by mjbvz** [comment]
This may be as simple as adding a call to `editor.dispose` in `StatefulMarkdownCell`
