### ISSUE TITLE
Smoke test failure: replaces first search result with a replace term:

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#118729]
```
VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           replaces first search result with a replace term:
     Error: Timeout: get text content '.search-view .messages .message' after 20 seconds.
      at poll (/Users/isidor/Development/vscode/test/automation/out/code.js:173:19)
      at async Code.waitForTextContent (/Users/isidor/Development/vscode/test/automation/out/code.js:234:16)
      at async Search.waitForResultText (/Users/isidor/Development/vscode/test/automation/out/search.js:86:9)
      at async Context.<anonymous> (out/areas/search/search.test.js:48:13)
```

**Comment by isidorn** [comment]
False alarm, my smoke test setup was incorrect ,sorry!
