### ISSUE TITLE
Change keybindings smoke test failure

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#118728]
```
changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:
     Error: Timeout: click '.keybindings-table-container .monaco-list-row .command[title="View: Toggle Side Bar Position (workbench.action.toggleSidebarPosition)"]' after 20 seconds.
      at poll (/Users/isidor/Development/vscode/test/automation/out/code.js:173:19)
      at async Code.waitAndClick (/Users/isidor/Development/vscode/test/automation/out/code.js:238:9)
      at async KeybindingsEditor.updateKeybinding (/Users/isidor/Development/vscode/test/automation/out/keybindings.js:22:9)
      at async Context.<anonymous> (out/areas/preferences/preferences.test.js:20:13)
```

**Comment by isidorn** [comment]
False alarm, my smoke test setup was incorrect ,sorry!
