### ISSUE TITLE
VS Code tries to read 'range' field from TextEdit which is null

### ISSUE THREAD

**Issue by mniewrzal** [Microsoft/vscode#11876]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:34:58.760Z)
- OS Version: Linux x64 4.7.2-201.fc24.x86_64

Steps to Reproduce:

After sending CompletionItem[] as a response for 'textDocument/completion' nothing is happening, no proposals. Developer tools console shows error.

Response for method: 'textDocument/completion':
```
Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 187

{"jsonrpc":"2.0","id":1,"result":[{"label":"abstract","kind":14,"detail":null,"documentation":null,"sortText":null,"filterText":null,"insertText":"abstract","textEdit":null,"data":null}]}
```

Developer tools console shows:
```
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:121 Cannot read property 'range' of null: TypeError: Cannot read property 'range' of null
    at asTextEdit (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:100:46)
    at /home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:95:67
    at set (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:83:13)
    at asCompletionItem (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:95:9)
    at Array.map (native)
    at asCompletionResult (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:76:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#95
