### ISSUE TITLE
Cannot read property 'setTerminalLayoutInfo' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118819]
Navigate away from our web playground:

```
Cannot read property 'setTerminalLayoutInfo' of undefined: TypeError: Cannot read property 'setTerminalLayoutInfo' of undefined
    at w._onWillShutdown (https://vscode-web-test-playground.azurewebsites.net/static-insider-06b54543d660353a04cdab6554d1f27266a537fd/out/vs/workbench/workbench.web.api.js:2746:7696)
    at https://vscode-web-test-playground.azurewebsites.net/static-insider-06b54543d660353a04cdab6554d1f27266a537fd/out/vs/workbench/workbench.web.api.js:2746:1884
    at c.fire (https://vscode-web-test-playground.azurewebsites.net/static-insider-06b54543d660353a04cdab6554d1f27266a537fd/out/vs/workbench/workbench.web.api.js:57:1836)
    at E.doShutdown (https://vscode-web-test-playground.azurewebsites.net/static-insider-06b54543d660353a04cdab6554d1f27266a537fd/out/vs/workbench/workbench.web.api.js:1748:2689)
    at E.onBeforeUnload (https://vscode-web-test-playground.azurewebsites.net/static-insider-06b54543d660353a04cdab6554d1f27266a537fd/out/vs/workbench/workbench.web.api.js:1748:1994)
    at https://vscode-web-test-playground.azurewebsites.net/static-insider-06b54543d660353a04cdab6554d1f27266a537fd/out/vs/workbench/workbench.web.api.js:1748:1762
```

**Comment by Tyriar** [comment]
Similar to https://github.com/microsoft/vscode/issues/119322, we don't have a `IPtyService` in yarn web. Probably a bad `!` or lacking `| undefined` somewhere.
