### ISSUE TITLE
Select Default Shell shows up in yarn web

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118978]
Running it gives this error which is expected, we should not show the command when no process support exists.

```
ERR NotSupported: Error: NotSupported
	at WorkerExtHostTerminalService.$getAvailableShells (http://localhost:8081/static/out/vs/workbench/api/common/extHostTerminalService.js:624:19)
	at RPCProtocol._doInvokeHandler (http://localhost:8081/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
	at RPCProtocol._invokeHandler (http://localhost:8081/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
	at RPCProtocol._receiveRequest (http://localhost:8081/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
	at RPCProtocol._receiveOneMessage (http://localhost:8081/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
	at http://localhost:8081/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
	at Emitter.fire (http://localhost:8081/static/out/vs/base/common/event.js:479:38)
	at MessagePort.ExtensionWorker.channel.port1.onmessage (http://localhost:8081/static/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:76:25)
```

**Comment by rzhao271** [comment]
The option still seems to show up for me when I ran `yarn web` on the latest distro.

<img src="https://user-images.githubusercontent.com/7199958/112389477-0459e680-8cb2-11eb-9501-572d39599189.PNG" alt="proof" height=200>

**Comment by Tyriar** [comment]
Ah, the fix got eaten by a merge conflict
