### ISSUE TITLE
Exception printed after running extension tests 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#119065]
- vscode from sources
- create a hello world app with `yo code` and compile it
- run the tests with
`.\scripts\code.bat --extensionDevelopmentPath=C:\Users\martinae\workspaces\testing\hello --extensionTestsPath=C:\Users\martinae\workspaces\testing\hello\out\test\suite\index`

Output:
```
 Extension Test Suite
    ? Sample test
  1 passing (1s)
[17264:0316/110057.060:INFO:CONSOLE(260)] "[uncaught exception]: Error: This socket has been ended by the other party", source: file:///C:/Users/martinae/workspaces/vscode/out/bootstrap-window.js (260)
[17264:0316/110057.060:INFO:CONSOLE(263)] "Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455:14)
    at NodeSocket.write (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/node/ipc.net.js:46:29)
    at ProtocolWriter._writeNow (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:268:26)
    at ProtocolWriter.flush (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:228:18)
    at ProtocolWriter.dispose (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:215:22)
    at dispose (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/common/lifecycle.js:77:27)
    at PersistentProtocol.dispose (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:538:63)
    at file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:480:26", source: file:///C:/Users/martinae/workspaces/vscode/out/bootstrap-window.js (263)
[17264:0316/110057.060:INFO:CONSOLE(292)] "Uncaught Error: This socket has been ended by the other party", source: events.js (292)
```

Similar when running the extension tests from sources (./scripts/test-integration.sh/bat), 

Windows:
```
[22944:0316/094045.079:INFO:CONSOLE(260)] "[uncaught exception]: Error: This socket has been ended by the other party", source: file:///C:/Users/martinae/workspaces/vscode/out/bootstrap-window.js (260)
[22944:0316/094045.079:INFO:CONSOLE(263)] "Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455:14)
    at NodeSocket.write (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/node/ipc.net.js:46:29)
    at ProtocolWriter._writeNow (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:268:26)
    at ProtocolWriter.flush (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:228:18)
    at ProtocolWriter.dispose (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:215:22)
    at dispose (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/common/lifecycle.js:77:27)
    at PersistentProtocol.dispose (file:///C:/Users/martinae/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.net.js:538:63)
    at file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js:480:26", source: file:///C:/Users/martinae/workspaces/vscode/out/bootstrap-window.js (263)
[22944:0316/094045.079:INFO:CONSOLE(292)] "Uncaught Error: This socket has been ended by the other party", source: events.js (292)
[main 2021-03-16T08:40:45.088Z] [uncaught exception in main]: TypeError: Error processing argument at index 0, conversion failure from
[main 2021-03-16T08:40:45.088Z] TypeError: Error processing argument at index 0, conversion failure from
    at detachGuest (electron/js2c/browser_init.js:177:1419)
    at Object.<anonymous> (electron/js2c/browser_init.js:177:2838)
    at Object.onceWrapper (events.js:422:26)
    at Object.emit (events.js:327:22)
 ```

Linux:
```
[192259:0316/095951.770923:INFO:CONSOLE(260)] "[uncaught exception]: Error: read ECONNRESET", source: file:///home/martin/workspaces/vscode/out/bootstrap-window.js (260)
[192259:0316/095951.770989:INFO:CONSOLE(263)] "Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:205:27)", source: file:///home/martin/workspaces/vscode/out/bootstrap-window.js (263)
[192259:0316/095951.771021:INFO:CONSOLE(292)] "Uncaught Error: read ECONNRESET", source: events.js (292)
[main 2021-03-16T08:59:51.782Z] [uncaught exception in main]: TypeError: Error processing argument at index 0, conversion failure from 
[main 2021-03-16T08:59:51.782Z] TypeError: Error processing argument at index 0, conversion failure from 
    at detachGuest (electron/js2c/browser_init.js:177:1419)
    at Object.<anonymous> (electron/js2c/browser_init.js:177:2838)
    at Object.onceWrapper (events.js:422:26)
    at Object.emit (events.js:327:22)
```

**Comment by rzhao271** [comment]
Still shows up for me when running the command from Windows Terminal:
![test-pipe](https://user-images.githubusercontent.com/7199958/112390023-e50f8900-8cb2-11eb-8062-f72b9480dd33.PNG)
