### ISSUE TITLE
Sanity test failure for arm32v7/ubuntu 

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#119008]
```
[3592 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[3758 ms] Remote-Containers server: /root/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[3767 ms] Remote-Containers server terminated (code: 127, signal: null).
[4706 ms] Start: Starting VS Code Server
[4706 ms] Start: Run in container: /root/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/server.sh --force-disable-user-env --use-host-proxy --port 0 --extensions-download-dir /root/.vscode-server/extensionsCache --start-server
[4710 ms] Error: stream is closed
        at /home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:12:4122
        at i (/home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:12:2234)
        at EventEmitter.t.<computed> [as exec] (/home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:12:1959)
        at u (/home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:88:1014)
        at new Promise (<anonymous>)
        at /home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:88:992
        at Tr (/home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:129:1953)
        at kj (/home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:129:384)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async zn (/home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:102:6698)
        at async iq (/home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:202:1646)
        at async /home/connor/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.2/dist/extension/extension.js:232:1328

```

**Comment by connor4312** [comment]
SteVen said this is known. Feel free to close if this is already tracked elsewhere
