### ISSUE TITLE
$getAvailableProfiles exception

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119200]
Seeing this in Insiders when I create a terminal:

```
ERR NotSupported: Error: NotSupported
	at u.$getAvailableProfiles (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:42536)
	at u._doInvokeHandler (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:77970)
	at u._invokeHandler (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:77654)
	at u._receiveRequest (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:76321)
	at u._receiveOneMessage (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:75107)
	at file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:73208
	at v.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:57:1836)
	at MessagePort.m.port1.onmessage (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:87:3503)
```

It's probably because we're allowing requests go through to non-primary extension hosts (like the web worker ext host).

**Comment by meganrogge** [comment]
Isn't this line preventing that though?

https://github.com/microsoft/vscode/blob/e8e6d64105b27603127193f04dd8ab52464f7d1a/src/vs/workbench/api/browser/mainThreadTerminalService.ts#L353-L353

**Comment by meganrogge** [comment]
Similar to the handling here, 

https://github.com/microsoft/vscode/blob/e8e6d64105b27603127193f04dd8ab52464f7d1a/src/vs/workbench/api/common/extHostTerminalService.ts#L774-L775

should I just return `new Promise(() => []))` here?

https://github.com/microsoft/vscode/blob/e8e6d64105b27603127193f04dd8ab52464f7d1a/src/vs/workbench/api/common/extHostTerminalService.ts#L782-L784
