### ISSUE TITLE
Flaky integration test:  Notebook API tests - edit API (replaceMetadata):

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#119300]
```
  1) Notebook API tests
       edit API (replaceMetadata):
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\vscode-api-tests\out\singlefolder-tests\notebook.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

https://github.com/microsoft/vscode/runs/2146598017?check_suite_focus=true

**Comment by roblourens** [comment]
Seems likely that we will get rid of this API right?

**Comment by rebornix** [comment]
We have made quite some refactoring with the API, it's green now.
