### ISSUE TITLE
cannot find my vscode extension in Extension Development Host

### ISSUE THREAD

**Issue by javadmokhtari** [microsoft/vscode#119386]
- VS Code Version: 1.54.3
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new extension project based on [documentation](https://code.visualstudio.com/api/get-started/your-first-extension)
2. Open project, press F5 and search your extension name in command palette.

Does this issue occur when all extensions are disabled?: Yes

My Project:
![image](https://user-images.githubusercontent.com/28118126/111873676-b342ad80-89a6-11eb-8ea3-b539e1b257d4.png)

Console log:
```
Loaded softwaredotcom.music-time v2.1.20
c:\Users\Javad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
swdc-vscode: Loaded softwaredotcom.swdc-vscode v2.5.3
c:\Users\Javad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
swdc-tracker initialized and ready to send events to com-software-prod1.collector.snplow.net
c:\Users\Javad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
[CodeTime] websockets connection open
c:\Users\Javad\.vscode\extensions\softwaredotcom.swdc-vscode-2.5.3\dist\extension.js:281
[CodeTime] received websocket message:  {"type":"info","body":"connected to codemetrics websockets server","userId":334124}
c:\Users\Javad\.vscode\extensions\softwaredotcom.swdc-vscode-2.5.3\dist\extension.js:281
[CodeTime] connected to codemetrics websockets server
c:\Users\Javad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
(node:9112) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'end' of 'r' as it is undefined.
	at c:\Users\Javad\.vscode\extensions\softwaredotcom.swdc-vscode-2.5.3\dist\extension.js:406:221548
	at Generator.next (<anonymous>)
	at o (c:\Users\Javad\.vscode\extensions\softwaredotcom.swdc-vscode-2.5.3\dist\extension.js:406:220634)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
c:\Users\Javad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
(node:9112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
c:\Users\Javad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
(node:9112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sandy081** [comment]
Seems to be related to running of extension.

**Comment by alexdima** [comment]
@javadmokhtari There is an error notification in the bottom right corner: "Activating extension ... failed". Can you please expand that and read the error message?
