### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by horodnicdragos** [Microsoft/vscode#11931]
- VSCode Version: 1.5.2
- OS Version: Windows 10.0.10586 N/A Build 10586

Steps to Reproduce:

1. Fresh install of VS Code
2. Cannot install some extensions

Examples:
"JS Refactoring"
"jshint"

**Comment by horodnicdragos** [comment]
From CLI I get the following:

C:\Users\dragossh>code --install-extension jshint                                                                                                                                                             
TypeError: Cannot read property 'firstPage' of undefined                                                                                                                                                      
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMai                                                                                                                  
n.js:7:22427                                                                                                                                                                                                  
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\                                                                                                                  
code\node\cli.js:4:29437)                                                                                                                                                                                     
    at Object.J.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\no                                                                                                                  
de\cli.js:5:1511)                                                                                                                                                                                             
    at r.Class.define._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\co                                                                                                                  
de\node\cli.js:5:2832)                                                                                                                                                                                        
    at r.Class.define._chainedError (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:2191)                                                                                   
    at r (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:14)                                                                                                                
    at r.Class.define.then (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:3641)                                                                                            
    at Object.N.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:83)                                                                                                   
    at r.Class.define._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:2832)                                                                                            
    at r.Class.define._setCompleteValue (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:2526)

**Comment by pawel-misiewicz-rtbhouse** [comment]
Same error here:

- VSCode Version: 1.5.2
- OS Version: openSUSE 42.1 Leap

`
~> code --install-extension java
TypeError: Cannot read property 'firstPage' of undefined                                                                                                                                     
    at /usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:7:22427                                                                                                              
    at Object.v [as _notify] (/usr/share/code/resources/app/out/vs/code/node/cli.js:4:29437)                                                                                                 
    at Object.J.enter (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:1511)                                                                                                         
    at r.Class.define._run (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:2832)                                                                                                    
    at r.Class.define._chainedError (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:2191)                                                                                           
    at r (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:14)                                                                                                                        
    at r.Class.define.then (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:3641)                                                                                                    
    at Object.N.enter (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:83)                                                                                                           
    at r.Class.define._run (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:2832)                                                                                                    
    at r.Class.define._setCompleteValue (/usr/share/code/resources/app/out/vs/code/node/cli.js:5:2526)                                                                                       
`

**Comment by joaomoreno** [comment]
@horodnicdragos If you are behind a proxy, make sure you [configure it](https://code.visualstudio.com/docs/setup/setup-overview#_proxy-server-support).

**Comment by tinganho** [comment]
I cannot install any extensions at all too.

VSCode Version: 1.5.3 on Mac

**Comment by Tyriar** [comment]
Verified via CR
