### ISSUE TITLE
Integration tests: Notebook API tests #115855 onDidSaveNotebookDocument

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#119437]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=109848&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=dccbe8b6-2cf2-56ce-ca99-720e7791a9c0

```
  1) Notebook API tests
       #115855 onDidSaveNotebookDocument:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/notebook.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

```

**Comment by jrieken** [comment]
Closing, should be good now
