### ISSUE TITLE
Error related to ssh after upgrading to 1.54.3

### ISSUE THREAD

**Issue by hyunsik-yoon** [microsoft/vscode#119441]
- VS Code Version: 1.54.3
- OS Version: Code on Windows 10 Enterprise. (19041.804) to edit files on Ubuntu box (18.04) using 'Remote - SSH' extension

I have used Windows VSCode with SSH-Extension to connect to my Ubuntu machine. I also have VSCode on Ubuntu box. 

Previous it worked perfectly, but after upgrading to 1.54.3 on Windows, VSCode started to fail. After some trials, I decided from clean env... by uninstalling VS Code on Windows and Ubuntu, removed ".vscode" and ".vscode-server" directories, and installing 1.54.3 on both machines. However, I'm still experiencing errors.

I am not sure if this is a bug or not but I started to experience right after upgrading my VS Code so I'd like to report it here. Could someone help me?

FYI, My ssh seems work fine. 
```
PS C:\Users\hyunsik.yoon> "echo Hello" | ssh -T -D 60435 eric@10.113.221.155 bash
eric@10.113.221.155's password:
Hello
```

**Case 1) First instance of VS Code** 
When I run VSCode, it showed me previous project name on the [Explorer] view and asks me to enter password then the following error will occur:
![image](https://user-images.githubusercontent.com/63768207/111946005-1014a400-8b1e-11eb-9554-f3117f838942.png)

```
[17:05:20.567] Resolver error: Error: Running the contributed command: '_workbench.downloadResource' failed.
```

Detailed log is here:
<details>

```

[17:04:42.100] Log Level: 2
[17:04:42.109] remote-ssh@0.65.1
[17:04:42.109] win32 x64
[17:04:42.111] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2231302e3131332e3232312e313535222c2275736572223a2265726963227d", attempt 1
[17:04:42.111] "remote.SSH.useLocalServer": false
[17:04:42.111] "remote.SSH.showLoginTerminal": false
[17:04:42.112] "remote.SSH.remotePlatform": {"10.113.221.155":"linux"}
[17:04:42.112] "remote.SSH.sshPath": undefined
[17:04:42.112] "remote.SSH.sshConfigurationFile": undefined
[17:04:42.112] "remote.SSH.useFlock": true
[17:04:42.112] "remote.SSH.lockfilesInTmp": false
[17:04:42.112] "remote.SSH.localServerDownload": auto
[17:04:42.112] "remote.SSH.remoteServerListenOnSocket": false
[17:04:42.112] "remote.SSH.showLoginTerminal": false
[17:04:42.112] "remote.SSH.defaultExtensions": []
[17:04:42.113] SSH Resolver called for host: eric@10.113.221.155
[17:04:42.113] Setting up SSH remote "10.113.221.155"
[17:04:42.141] Using commit id "2b9aebd5354a3629c3aba0a5f5df49f43d6689f8" and quality "stable" for server
[17:04:42.145] Install and start server if needed
[17:04:42.165] Checking ssh with "ssh -V"
[17:04:42.365] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[17:04:42.676] Running script with connection command: ssh -T -D 54949 "eric@10.113.221.155" bash
[17:04:42.679] Terminal shell path: C:\windows\System32\cmd.exe
[17:04:43.146] > eric@10.113.221.155's password:]0;C:\windows\System32\cmd.exe
[17:04:43.147] Got some output, clearing connection timeout
[17:04:43.148] Showing password prompt
[17:04:51.990] Got password response
[17:04:51.990] "install" wrote data to terminal: "***********"
[17:04:52.005] > 
[17:04:52.320] > dee9c184d651: running
[17:04:52.389] > Acquiring lock on /home/eric/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f4
> 3d6689f8/vscode-remote-lock.eric.2b9aebd5354a3629c3aba0a5f5df49f43d6689f8       
[17:04:52.423] > Installing to /home/eric/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d66
> 89f8...
> dee9c184d651%%1%%
> Downloading with wget
[17:04:59.473] > wget download failed
> failed: Connection timed out.
> printenv:
>     LC_MEASUREMENT=ko_KR.UTF-8
>     SSH_CONNECTION=10.113.112.74 54951 10.113.221.155 22
>     LC_PAPER=ko_KR.UTF-8
>     LC_MONETARY=ko_KR.UTF-8
>     LANG=en_US.UTF-8
>     LC_NAME=ko_KR.UTF-8
>     XDG_SESSION_ID=89
>     USER=eric
>     PWD=/home/eric/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
>     HOME=/home/eric
>     SSH_CLIENT=10.113.112.74 54951 22
>     LC_ADDRESS=ko_KR.UTF-8
>     LC_NUMERIC=ko_KR.UTF-8
>     MAIL=/var/mail/eric
>     PAPERSIZE=a4
>     SHELL=/bin/bash
>     SHLVL=2
>     LANGUAGE=en
[17:04:59.474] > 
>     LC_TELEPHONE=ko_KR.UTF-8
>     VSCODE_AGENT_FOLDER=/home/eric/.vscode-server
>     LOGNAME=eric
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     XDG_RUNTIME_DIR=/run/user/1000
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> :/usr/local/games:/snap/bin
>     LC_IDENTIFICATION=ko_KR.UTF-8
>     LC_TIME=ko_KR.UTF-8
>     _=/usr/bin/printenv
>     OLDPWD=/home/eric
> Trigger local server download
> dee9c184d651:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/eric/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689
> f8==
> dee9c184d651:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/eric/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689
> f8/vscode-scp-done.flag and vscode-server.tar.gz to exist
[17:04:59.475] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/eric/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8"}
[17:04:59.475] Downloading VS Code server locally...
[17:04:59.485] > 
> 
[17:05:20.567] Resolver error: Error: Running the contributed command: '_workbench.downloadResource' failed.
	at S._executeContributedCommand (c:\Users\hyunsik.yoon\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:103934)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:139049
	at async Object.t.downloadAndCopyToHost (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:138964)
	at async c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:295868
	at async q (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:296086)
	at async c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:294221
	at async Object.t.withShowDetailsEvent (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async Object.t.resolve (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297912)
	at async c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
[17:05:20.574] ------


```

</details>

**Case 2) Using "Remote-SSH: Connect to Host" command**
F1 key -> "Remote-SSH: Connect to Host" -> I entered "eric@10.113.221.155" and then password

![image](https://user-images.githubusercontent.com/63768207/111946476-e9a33880-8b1e-11eb-8440-163750e7aef9.png)

```
[17:08:07.703] Resolver error: Error: 
```

Detailed log is here:
<details>

```
[17:07:58.118] Log Level: 2
[17:07:58.126] remote-ssh@0.65.1
[17:07:58.126] win32 x64
[17:07:58.128] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2231302e3131332e3232312e313535222c2275736572223a2265726963227d", attempt 1
[17:07:58.128] "remote.SSH.useLocalServer": false
[17:07:58.129] "remote.SSH.showLoginTerminal": false
[17:07:58.129] "remote.SSH.remotePlatform": {"10.113.221.155":"linux"}
[17:07:58.129] "remote.SSH.sshPath": undefined
[17:07:58.129] "remote.SSH.sshConfigurationFile": undefined
[17:07:58.129] "remote.SSH.useFlock": true
[17:07:58.129] "remote.SSH.lockfilesInTmp": false
[17:07:58.129] "remote.SSH.localServerDownload": auto
[17:07:58.130] "remote.SSH.remoteServerListenOnSocket": false
[17:07:58.130] "remote.SSH.showLoginTerminal": false
[17:07:58.130] "remote.SSH.defaultExtensions": []
[17:07:58.130] SSH Resolver called for host: eric@10.113.221.155
[17:07:58.130] Setting up SSH remote "10.113.221.155"
[17:07:58.144] Using commit id "2b9aebd5354a3629c3aba0a5f5df49f43d6689f8" and quality "stable" for server
[17:07:58.148] Install and start server if needed
[17:07:58.153] Checking ssh with "ssh -V"
[17:07:58.329] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[17:07:58.677] Running script with connection command: ssh -T -D 55013 "eric@10.113.221.155" bash
[17:07:58.680] Terminal shell path: C:\windows\System32\cmd.exe
[17:07:59.100] > eric@10.113.221.155's password:]0;C:\windows\System32\cmd.exe
[17:07:59.101] Got some output, clearing connection timeout
[17:07:59.102] Showing password prompt
[17:08:06.464] Got password response
[17:08:06.464] "install" wrote data to terminal: "***********"
[17:08:06.465] > eric@10.113.221.155's password:
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[17:08:06.465] Showing password prompt
[17:08:07.698] "install" terminal command done
[17:08:07.699] Install terminal quit with output: eric@10.113.221.155's password:
[17:08:07.699] Received install output: eric@10.113.221.155's password:
[17:08:07.699] Stopped parsing output early. Remaining text: eric@10.113.221.155's password:
[17:08:07.699] Failed to parse remote port from server output
[17:08:07.703] Resolver error: Error: 
	at Function.Create (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:64328)
	at Object.t.handleInstallOutput (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:63022)
	at q (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:296373)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:294221
	at async Object.t.withShowDetailsEvent (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async Object.t.resolve (c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297912)
	at async c:\Users\hyunsik.yoon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
[17:08:07.707] ------




[17:08:09.026] Password dialog canceled
[17:08:09.026] "install" terminal command canceled
[17:08:09.026] > 
[17:08:09.027] > e30077993bf5: running
[17:08:09.027] > Acquiring lock on /home/eric/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/vscode-remote-lock.eric.2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
[17:08:09.027] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> e30077993bf5: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> e30077993bf5: end

```

</details>

Does this issue occur when all extensions are disabled?: Yes/No  --> This is related to SSH extension authored by Microsoft, so extension should be enabled to reproduce

**Comment by hyunsik-yoon** [comment]
It turned out the company network current has an network problem to access http://update.code.visualstudio.com
and some we suspect that `wget` failure is related to this.

Let me keep opening this issue and update the status later.

**Comment by hyunsik-yoon** [comment]
Manual downloading of a required file from http://update.code.visualstudio.com and untarred it into Ubuntu box solved this issue.
Let me close this issue.
