### ISSUE TITLE
Editor: ERR Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119632]
Testing #119545

* install selfhost test provider
* open `src/vs/workbench/test/browser/api/extHostApiCommands.test.ts`
* move mouse over the imports
* 💥 the console is flooded with errors (two types)

A: `ERR Illegal value for lineNumber: Error: Illegal value for lineNumber`

```
ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at TextModel.getLineMaxColumn (file:///Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:598:23)
    at ViewModelDecorations._getOrCreateViewModelDecoration (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelDecorations.js:49:156)
    at ViewModelDecorations._getDecorationsViewportData (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelDecorations.js:81:48)
    at ViewModelDecorations.getDecorationsViewportData (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelDecorations.js:64:61)
    at ViewModel.getViewLineRenderingData (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:480:58)
    at ViewportData.getViewLineRenderingData (file:///Users/jrieken/Code/vscode/out/vs/editor/common/viewLayout/viewLinesViewportData.js:24:32)
    at ViewLine.renderLine (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/viewParts/lines/viewLine.js:126:43)
    at ViewLayerRenderer._finishRendering (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewLayer.js:429:47)
    at ViewLayerRenderer.render (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewLayer.js:330:18)
    at VisibleLinesCollection.renderLines (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewLayer.js:263:37)
    at ViewLines.renderText (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/viewParts/lines/viewLines.js:427:32)
    at View._actualRender (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:246:33)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:218:40
    at safeInvokeNoArg (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:372:20)
    at View._renderNow (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:218:13)
    at View._flushAccumulatedAndRenderNow (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:111:18)
    at View._onRenderScheduled (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:215:18)
    at AnimationFrameQueueItem.execute (file:///Users/jrieken/Code/vscode/out/vs/base/browser/dom.js:147:22)
    at animationFrameRunner (file:///Users/jrieken/Code/vscode/out/vs/base/browser/dom.js:183:21)
```

B: `ERR Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

```
ERR Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ViewLayerRenderer._removeLinesAfter (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewLayer.js:371:34)
    at ViewLayerRenderer.render (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewLayer.js:326:26)
    at VisibleLinesCollection.renderLines (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewLayer.js:263:37)
    at ViewLines.renderText (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/viewParts/lines/viewLines.js:427:32)
    at View._actualRender (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:246:33)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:218:40
    at safeInvokeNoArg (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:372:20)
    at View._renderNow (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:218:13)
    at View._flushAccumulatedAndRenderNow (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:111:18)
    at Object.visibleRangeForPosition (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:139:26)
    at HitTestContext.visibleRangeForPosition (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseTarget.js:222:37)
    at Function.createMouseTargetFromHitTestPosition (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseTarget.js:540:38)
    at Function._hitTestViewLines (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseTarget.js:485:43)
    at Function._createMouseTarget (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseTarget.js:337:51)
    at MouseTargetFactory.createMouseTarget (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseTarget.js:303:46)
    at TouchHandler._createMouseTarget (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:101:44)
    at TouchHandler._onMouseMove (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:124:30)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:37:102
    at invokeHandler (file:///Users/jrieken/Code/vscode/out/vs/base/browser/dom.js:227:17)
    at HTMLDivElement.<anonymous> (file:///Users/jrieken/Code/vscode/out/vs/base/browser/dom.js:235:21)
```

**Comment by jrieken** [comment]
I cannot link this to testing via stacktraces but this doesn't happen when disabling the test selfhost provider

**Comment by jrieken** [comment]
Given this is throwing soo many errors I would really prefer a short term fix (workaround) and not wait for a feature request

**Comment by connor4312** [comment]
Ok, I can take care of it

**Comment by connor4312** [comment]
I'll still mark as a duplicate but move the other issue into this iteration -- fixing it is a feature/api tweak that will result in this bug being fixed (we need a `bugture` label).

**Comment by alexdima** [comment]
I want to keep this to track the problem that the editor throws. The editor should not throw, even with bad inputs. I have tracked this down to a decoration with a range `[undefined,0;undefined,1]`. Right now, the editor validates that into `[0,1;0,1]` which is incorrect.
