### ISSUE TITLE
Opening Jupyter notebook when starting a remote VS connection

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode#119686]
- VS Code Version: 1.54.3
- OS Version: Darwin x64 20.3.0

Steps to Reproduce:

1. Implement vscode.RemoteAuthorityResolver 
2. Inside the resolve() function, open a .ipynb file using `vscode.window.showTextDocument([fileUri])`

We expect to see the notebook editor UI but we only see the JSON contents of the file.

Our use case is that the user is connecting to a remote machine to edit a notebook file (an Azure Machine Learning compute instance) and we want to open that notebook file as soon as the connection is made. Previously using the above steps resulted in the webview jupyter notebook editor, but now the user only sees the JSON contents of the file.

We've been advised to use `vscode.commands.executeCommand('vscode.openWith', fileUri, 'jupyter-notebook');` to open the file using the native notebook editor. However, we're not seeing the native notebook editor appear at all using this command. I suspect this is because we're calling this before the remote workspace or extension host have loaded yet (since this is during the resolve function). The `showTextDocument` API properly queues the file open to happen after the connection is made, but it appears that `openWith` does not do this. Unfortunately the remote resolver API does not provide any events to know when the workspace and extension host have finished connecting, so we don't have a way of opening the notebook file later on. 

Does this issue occur when all extensions are disabled?: No (Question pertains to extension API)

**Comment by rebornix** [comment]
@jrieken any idea?

**Comment by jrieken** [comment]
> Inside the resolve() function, open a .ipynb file using vscode.window.showTextDocument([fileUri])

@tbombach Are you really calling `showTEXTDocument` and not `showNotebookDocument` or is that typo?

**Comment by SiddhanthUnnithan** [comment]
Hey @jrieken I just checked the code and it looks like we're calling the following:

void vscode.window.showTextDocument(fileUri, {preserveFocus: false, preview: false});

**Comment by jrieken** [comment]
Well, if you ask for a text document than you get one. Try to use `showNotebookDocument` instead.

**Comment by SiddhanthUnnithan** [comment]
Great, will try showNotebookDocument and then let you know if that fixes it

**Comment by shsuman** [comment]
Hey @jrieken, We tried doing it with showNotebookDocument and got the error: 

stack trace: Error: Notebook Editor creation failure for documenet undefined
    at m.$tryShowNotebookDocument (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2091:18139)

This is the uri we are using:
vscode-remote://amlext/home/azureuser/cloudfiles/code//Users/shsuman/MachineLearningNotebooks/how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb

**Comment by shsuman** [comment]
Also, an Untitled-1.ipynb is trying to be opened in the VSCode window which fails with this error:

Unable to open 'Untitled-1': r.NotebookCellMetadata is not a constructor.

**Comment by shsuman** [comment]
Getting this error with latest insiders:

stack trace: Error: Missing viewType for 'vscode-remote://amlext/home/azureuser/cloudfiles/code//Users/shsuman/MachineLearningNotebooks/how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb'
    at ra.resolve (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2162:100781)
    at m.$tryOpenDocument (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2176:13894)
    at o._doInvokeHandler (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1589:11903)
    at o._invokeHandler (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1589:11587)
    at o._receiveRequest (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1589:10257)
    at o._receiveOneMessage (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1589:9043)
    at file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1589:7144
    at c.fire (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at s.fire (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16186)
    at i._receiveMessage (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21444)
    at file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18330
    at c.fire (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at u.acceptChunk (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13551)
    at file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12899
    at Socket.k (file:///C:/Users/shsuman/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2792:52556)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by rebornix** [comment]
cc @roblourens

**Comment by roblourens** [comment]
I can repro this and basically we need to wait for notebook extensions to be activated before we try to resolve a viewType.

**Comment by SiddhanthUnnithan** [comment]
Hey @roblourens is it possible for us to wait for the Notebook extension to be activated in the resolver code? What's the right approach for us to take (API usage wise) to do that?

**Comment by roblourens** [comment]
This needs a fix in vscode, I will look into it. Otherwise probably the only thing you can do is `setTimeout` :)

**Comment by SiddhanthUnnithan** [comment]
Thanks for the quick fix @roblourens ! What would be the best way for us to test this?

Cc/ @sevillal

**Comment by roblourens** [comment]
The fix will be in tomorrow's Insiders build

**Comment by jrieken** [comment]
Thanks @roblourens

**Comment by sevillal** [comment]
@roblourens thanks for the quick fix.

We were able to test it this morning and the notebook is open and rendered correctly, but we are having issues running cells or saving changes in the notebook. I have created https://github.com/microsoft/vscode/issues/119891 with the details.

cc @SiddhanthUnnithan

**Comment by rebornix** [comment]
> We were able to test it this morning and the notebook is open and rendered correctly

Added `z-author-verified`.
