### ISSUE TITLE
Quick input smoke test failure/timeouts

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#119818]
when testing #119524
Running the smoke tests on windows, I'm seeing a few quick input test timeouts/failures.

using `yarn smoketest --build <path to latest version> --stable-build <path to stable version>`

`  1) shows results from all folders` is failing with this message:

 ```
 1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Multiroot
           shows results from all folders:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (C:\Users\merogge\repos\vscode\test\automation\out\code.js:173:19)
      at async Code.waitForElements (C:\Users\merogge\repos\vscode\test\automation\out\code.js:250:16)
      at async QuickInput.waitForQuickInputElements (C:\Users\merogge\repos\vscode\test\automation\out\quickinput.js:24:9)
      at async Context.<anonymous> (out\areas\multiroot\multiroot.test.js:39:13)

```

----

using `yarn smoketest --web --browser chromium`

`
** Timeout!
page.evaluate: Evaluation failed: Error: Active element not found. Current active element is 'HTML > BODY.windows.web'. Looking for .search-view .search-widget .search-container .monaco-inputbox textarea
    at BrowserWindowDriver.isActiveElement (http://localhost:9888/static/out/vs/platform/driver/browser/baseDriver.js:63:23)
    at eval (eval at evaluate (:300:31), <anonymous>:1:15)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:300:31)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Connection.sendMessageToServer (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\channelOwner.js:44:61)
    at C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\frame.js:157:48
    at Frame._wrapApiCall (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\channelOwner.js:72:34)
    at Frame.evaluate (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\frame.js:156:21)
    at C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\page.js:344:60
    at Page._attributeToPage (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\page.js:205:20)
    at Page.evaluate (C:\Users\merogge\repos\vscode\node_modules\playwright\lib\client\page.js:344:21)
    at Proxy.isActiveElement (C:\Users\merogge\repos\vscode\test\automation\out\playwrightDriver.js:72:55)
    at Proxy.<anonymous> (C:\Users\merogge\repos\vscode\test\automation\out\code.js:208:39)`

**Comment by TylerLeonhardt** [comment]
So the first issue I couldn't repro and the second one I did hit but it passed on retry. @meganrogge can you try running the tests again?

**Comment by Tyriar** [comment]
@TylerLeonhardt we'd want to fix any flakiness

**Comment by TylerLeonhardt** [comment]
So I think the second issue should be moved to #115244 and then the first issue... I've run the smoke tests so many times and can't repro :(

**Comment by chrmarti** [comment]
Saw the following once when running desktop smoke test. Curiously that did not fail the test. This happened when the same multiroot test as above was running:
```
** Timeout!
Error: Active element not found. Current active element is 'HTML > BODY.windows > DIV.file-icons-enabled.monaco-workbench.windows.chromium.nopanel.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.horizontal > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical.separator-border > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV.editor-instance > DIV.gettingStartedContainer.height-constrained.animationReady > DIV.gettingStarted.showDetails > DIV.gettingStartedSlideDetails.gettingStartedSlide.detail > DIV.monaco-scrollable-element.full-height-scrollable > DIV.gettingStartedDetailsContent > DIV.getting-started-detail-columns > DIV.getting-started-detail-left > DIV.monaco-scrollable-element.full-height-scrollable > DIV.getting-started-detail-container > BUTTON.getting-started-task.expanded'. Looking for .quick-input-widget .quick-input-box input
/out/vs/workbench/workbench.desktop.main.js:570:78507)
    at v.call (file:///C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2793:64099)
    at w.onPromise (file:///C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:75:68877)
    at w.onRawMessage (file:///C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:75:68236)
    at file:///C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:75:67489
    at c.fire (file:///C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at EventEmitter.N (file:///C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60411)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:117:979)
        √ shows results from all folders
        √ shows workspace name in title
```

**Comment by bpasero** [comment]
@TylerLeonhardt I suggest to close this issue and monitor newer builds, there were many changes around quick pick recently. Specifically I am tweaking how retry works:

https://github.com/microsoft/vscode/commit/38f026eb35735f22602d1919a87a785b561e6dcc

Besides, I cannot find `shows results from all folders` in the list of failing tests lately: https://monacotools.visualstudio.com/DefaultCollection/Monaco/_test/analytics?definitionId=111&contextType=build
