### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 3 === 1. Registered script kind should match new script kind.

### ISSUE THREAD

**Issue by YSHIDM** [microsoft/vscode#120073]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind.
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:146647:34)
    at tryReuseStructureFromOldProgram (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:105641:28)
    at Object.createProgram (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:105167:29)
    at synchronizeHostData (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:146570:26)
    at Proxy.getProgram (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:146662:13)
    at InferredProject.Project.updateGraphWorker (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:151524:53)
    at InferredProject.Project.updateGraph (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:151457:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:153585:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:155111:26)
    at /Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:155385:97
    at Object.flatMap (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:155385:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:156403:46)
    at /Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:158276:88
    at IOSession.Session.executeWithRequestId (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:158267:28)
    at IOSession.Session.executeCommand (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:158276:33)
    at IOSession.Session.onMessage (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:158300:35)
    at Interface.<anonymous> (/Users/lcy/Project/new_git/assist-server-2.0/node_modules/typescript/lib/tsserver.js:160510:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.79GB free)|
|Process Argv|-psn_0_14781976 --crash-reporter-id e565a6e3-e5c1-4b9a-a303-2042977140b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (119)</summary>

Extension|Author (truncated)|Version
---|---|---
smartmate-bpmn-editor|adr|0.0.8
markdown-toc|Ala|1.5.6
project-manager|ale|12.0.1
electron-snippets|ant|1.0.3
eggjs|ati|0.3.1
vscode-database|baj|2.2.3
shell|bbe|0.3.0
typo3-typoscript|ben|0.2.0
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.1.6
pgformatter|bra|1.17.0
graphql-snippets|chr|0.0.3
vscode-postgres|cko|1.1.17
EnglishChineseDictionary|Cod|1.0.1
systemd-unit-file|coo|1.0.6
markdown-table-prettify|dar|3.3.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.19
vscode-faker|dee|1.5.0
vscode-hasher|dee|1.0.1
vscode-pandoc|Dou|0.0.8
eslint-disable-snippets|drK|1.3.0
vscode-wasm|dts|1.3.1
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.18
egg-jump-definition|egg|0.0.16
vscode-great-icons|emm|2.1.72
prettier-vscode|esb|6.3.1
vscode-open-in-marketplace|fab|1.2.7
markdown-table-formatter|fcr|2.1.4
code-runner|for|0.11.3
terminal|for|0.0.10
shell-format|fox|7.0.1
vscode-lombok|Gab|1.0.1
graphviz-markdown-preview|gee|0.0.8
lintlens|ghm|3.0.0
mdmath|goe|2.5.1
vscode-graphql|Gra|0.3.15
todo-tree|Gru|0.0.209
beautify|Hoo|1.5.0
JSDocTagComplete|Hoo|0.0.2
rest-client|hum|0.24.4
comment-translate|int|1.4.2
path-autocomplete|ion|1.17.1
yuml|Jai|3.5.1
nginx-log-highlighter|jak|1.1.0
vscode-edit-csv|jan|0.5.6
markdown-extended|jeb|1.0.19
Lua-Nginx-Snippets|jie|0.0.4
nbpreviewer|jit|1.2.2
vscode-graphviz|joa|0.0.6
svg|joc|1.4.5
webdav|jor|0.0.11
vscode-markdown-mindmap-preview|jos|1.1.0
thymeleaf|juh|1.0.3
vscode-gutter-preview|kis|0.27.1
quickjs-debug|kou|0.0.15
ts-extension-pack|loi|0.2.0
regexp-preview|Lou|0.1.5
marp-vscode|mar|0.17.3
javascript-docstrings|Mas|1.1.1
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.8.1
git-graph|mhu|1.29.0
sort-typescript-imports|mic|1.4.1
mongodb-vscode|mon|0.5.0
vscode-json5|mrm|1.0.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-docker|ms-|1.11.0
vscode-language-pack-zh-hans|MS-|1.54.2
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
hexeditor|ms-|1.4.0
vscode-typescript-next|ms-|4.3.20210328
vscode-json-editor|nic|0.3.0
kill-process|nir|0.2.0
remote-github|niu|0.3.0
graphql-to-rest-queries|ora|0.0.2
VSNotebooks|pav|1.4.4
jsdoc-live-preview|Per|2.0.0
ejs-language-support|Qas|0.0.1
vscode-xml|red|0.15.0
vscode-yaml|red|0.17.0
reader|ren|1.1.6
ts-interface-builder|rik|0.0.2
mongo-snippets-for-node-js|roe|1.3.5
vs-code-bpmn-io|sal|0.6.1
yo|sam|0.9.3
vant-typescript-snippets|san|1.0.0
markdown-preview-enhanced|shd|0.5.17
java-generate-setters-getters|soh|7.0.2
vscode-mindmap|Sou|0.0.5
move-ts|str|1.12.0
language-stylus|sys|1.11.0
hyper-javascript-snippets|t7y|3.0.0
open-in-browser|tec|2.0.0
vscode-nginx-format|tec|0.0.6
vscode-markdown-paste-image|tel|0.12.3
lammps|ThF|1.4.6
vscode-input-sequence|tom|0.2.0
vscode-mermaid-editor|tom|0.10.1
terminal-tabs|Tyr|0.2.0
sensitive-replace|vil|0.1.1
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-maven|vsc|0.28.0
sneak-mark|wan|0.0.6
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
java-snippet|Wsc|0.0.6
JavaScriptSnippets|xab|1.8.0
ooxml-viewer|yue|1.1.0
markdown-all-in-one|yzh|3.4.0
openapi-preview|zoe|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
wslfolderdoc:30280164
vscoresta800cf:30279782
vspre833cf:30267465
vsdfh931cf:30280410
vshan820cf:30276953

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
