### ISSUE TITLE
Integration tests: Error: Could not find pty with id "6"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120010]
Seeing this output when running integration tests (macOS, ARM):

```
Could not find pty with id "6": Error: Could not find pty with id "6"
    at PtyService._throwIfNoPty (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:180:23)
    at PtyService.shutdown (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:101:25)
    at Object.call (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:813:39)
    at Server.onPromise (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:253:35)
    at Server.onRawMessage (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:226:33)
    at /Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:171:73
    at Emitter.fire (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:479:38)
    at process.fn (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:257:44)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[26140:0327/100747.829341:INFO:CONSOLE(206)] "%c  ERR color: #f33 [uncaught exception in sharedProcess]: Could not find pty with id "6": Error: Could not find pty with id "6"
    at PtyService._throwIfNoPty (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:180:23)
    at PtyService.shutdown (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:101:25)
    at Object.call (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:813:39)
    at Server.onPromise (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:253:35)
    at Server.onRawMessage (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:226:33)
    at /Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:171:73
    at Emitter.fire (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:479:38)
    at process.fn (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:257:44)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)", source: file:///Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/log/common/log.js (206)
[26140:0327/100749.148752:INFO:CONSOLE(206)] "%c  ERR color: #f33 [uncaught exception in sharedProcess]: Could not find pty with id "7": Error: Could not find pty with id "7"
    at PtyService._throwIfNoPty (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:180:23)
    at PtyService.shutdown (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:101:25)
    at Object.call (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:813:39)
    at Server.onPromise (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:253:35)
    at Server.onRawMessage (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:226:33)
    at /Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:171:73
    at Emitter.fire (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:479:38)
    at process.fn (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:257:44)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)", source: file:///Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/log/common/log.js (206)
Could not find pty with id "7": Error: Could not find pty with id "7"
    at PtyService._throwIfNoPty (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:180:23)
    at PtyService.shutdown (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/platform/terminal/node/ptyService.js:101:25)
    at Object.call (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:813:39)
    at Server.onPromise (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:253:35)
    at Server.onRawMessage (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:226:33)
    at /Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/parts/ipc/common/ipc.js:171:73
    at Emitter.fire (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:479:38)
    at process.fn (/Users/bpasero/Development/Microsoft/bpasero-vscode/out/vs/base/common/event.js:257:44)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Comment by pwsses** [comment]
I have same issue on SSH
