### ISSUE TITLE
Behavior of require is different in development and production modes and causes problems for extension authors

### ISSUE THREAD

**Issue by DavidAnson** [microsoft/vscode#120150]
- VS Code Version: 1.54.3
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Test extension using `require.resolve.paths` on multiple platforms/architectures
   - Reference: https://nodejs.org/dist/latest-v14.x/docs/api/modules.html#modules_require_resolve_paths_request
1. Works great
1. Publish extension and test one last time
1. KABOOM, `require` behaves differently for extensions in the Marketplace
   - But you already knew that, @alexdima partially fixed this same problem a couple of months ago in https://github.com/microsoft/vscode/issues/114172

However, Alex's patch only seems to help with the `require.resolve(request, options)` scenario and not the `require.resolve.paths()` scenario. The latter is valuable because it lets one include an *additional* path when resolving - which does not seem possible using resolve+options which *replaces* the default paths.

Ideally, extension authors would not need to know this and would be able to test with the same `require` behavior their users see. 

```
[10:07:25 PM] ERROR: Exception while linting:
TypeError: r.resolve.paths is not a function or its return value is not iterable
	at v (/Users/david/.vscode/extensions/davidanson.vscode-markdownlint-0.40.0/bundle.js:31:864)
	at /Users/david/.vscode/extensions/davidanson.vscode-markdownlint-0.40.0/bundle.js:31:948
	at Array.map (<anonymous>)
	at w (/Users/david/.vscode/extensions/davidanson.vscode-markdownlint-0.40.0/bundle.js:31:940)
	at C (/Users/david/.vscode/extensions/davidanson.vscode-markdownlint-0.40.0/bundle.js:31:2496)
	at async T (/Users/david/.vscode/extensions/davidanson.vscode-markdownlint-0.40.0/bundle.js:31:5542)
```

Does this issue occur when all extensions are disabled?: No, but this is not an extension bug

**Comment by DavidAnson** [comment]
@jrieken who was also referenced in the linked issue above.

**Comment by DavidAnson** [comment]
FYI, in my scenario, it _appears_ the dependency with the call to `require.resolve.paths` can get away without that call, so this _should_ be able to work with the existing change to VS Code (in >= January 2021/1.53 builds). It would still be great to resolve this inconsistency, tho.

- https://github.com/DavidAnson/markdownlint-cli2/commit/b68117d669f4e3720ff47e3b3ef0816821b6a03d
- https://github.com/DavidAnson/markdownlint-cli2/commit/37d590865f20e18f0593e6e176f2c4c8951a2821

**Comment by DavidAnson** [comment]
Yay!!

**Comment by DavidAnson** [comment]
@alexdima @chrmarti Thanks for fixing this! It turns out I need the call to `paths` in some cases (globally installed packages). Looking forward to the April release...
