### ISSUE TITLE
Webview does not survive a window reload (running out of sources)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120157]
Steps to Reproduce:

1. running out of sources
2. open a markdown file with `Hello World` as content
3. open a markdown preview to the side
4. reload window

=> 🐛 

![image](https://user-images.githubusercontent.com/900690/112948481-672b0200-9138-11eb-92f6-ac0989a7d4ad.png)

```
ERR Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
	at MarkdownPreviewManager.deserializeWebviewPanel (/Users/bpasero/Development/Microsoft/monaco/extensions/markdown-language-features/out/features/previewManager.js:106:49)
	at ExtHostWebviewPanels.$deserializeWebviewPanel (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostWebviewPanels.js:220:30)
	at RPCProtocol._doInvokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
	at RPCProtocol._invokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
	at RPCProtocol._receiveRequest (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
	at RPCProtocol._receiveOneMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
	at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:146:41
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
	at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
	at PersistentProtocol._receiveMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:510:83
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
	at ProtocolReader.acceptChunk (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:158:61
	at Socket.listener (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by mjbvz** [comment]
This happens when the preview previously failed to serialize itself and then tries to restore itself on reload. I have not seen it happen in production. It usually seems caused by having local changes that break some element of webview sterilization logic

Let me know if you see this in insiders or in OSS while working on unrelated code

**Comment by bpasero** [comment]
I literally do this:
* explorer right click on a markdown file -> open preview
* reload window

It fails to restore.

What is so specific about running out of sources?

**Comment by mjbvz** [comment]
I can't reproduce this:


https://user-images.githubusercontent.com/12821956/116345958-0bd34a80-a79e-11eb-8da4-148c2b53cda0.mov

This is running code with `./scripts/code.sh`. I've tried both window reloads and killing the process and then restarting

**Comment by bpasero** [comment]
So weird and now I cannot reproduce anymore...
