### ISSUE TITLE
TS Server fatal error:  Cannot destructure property 'name' of 'object null' as it is null.

### ISSUE THREAD

**Issue by LuisdelaVega** [microsoft/vscode#120252]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.8.3-pnpify

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot destructure property 'name' of 'object null' as it is null.
    at getPackageInformation (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.pnp.js:45301:5)
    at Object.getPackageInformation (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.pnp.js:45644:20)
    at getPnpTypeRoots (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28763:42)
    at getDefaultTypeRoots (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28779:24)
    at getEffectiveTypeRoots (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28732:20)
    at Object.getAutomaticTypeDirectiveNames (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:28909:29)
    at Object.createProgram (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:97895:56)
    at synchronizeHostData (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:135345:26)
    at Proxy.getProgram (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:135437:13)
    at InferredProject.Project.updateGraphWorker (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:139913:53)
    at InferredProject.Project.updateGraph (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:139856:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:141832:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:143259:26)
    at /Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:143523:107
    at Object.mapDefined (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:143523:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:144387:46)
    at /Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146130:88
    at IOSession.Session.executeWithRequestId (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146121:28)
    at IOSession.Session.executeCommand (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146130:33)
    at IOSession.Session.onMessage (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:146154:35)
    at IOSession.onMessage (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/sdks/typescript/lib/tsserver.js:90:32)
    at Interface.<anonymous> (/Users/luisdelavegalopez/Documents/MAI/Repos/workflow-ui/.yarn/cache/typescript-patch-44be79f87b-2.zip/node_modules/typescript/lib/tsserver.js:147469:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by IllusionMH** [comment]
Trace suggests that something wrongs happens within TS version for PnP.
Looks same as https://github.com/yarnpkg/berry/issues/1189
