### ISSUE TITLE
Remote test failure

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#120213]
```
I [Error]: Unable to read file '/__w/1/s/extensions/notebook-markdown-extensions/notebook-out/katex.js' (Error: Unable to resolve non-existing file '/__w/1/s/extensions/notebook-markdown-extensions/notebook-out/katex.js')
    at a.doReadFileStream (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:28:20883)
    at async L (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:48:20461)
    at async g (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:48:21380)
    at async yt.handleWebviewResourceRequest (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:48:30842) {
  fileOperationResult: 1,
  options: { etag: undefined }
}
I [Error]: Unable to read file '/__w/1/s/extensions/notebook-markdown-extensions/notebook-out/emoji.js' (Error: Unable to resolve non-existing file '/__w/1/s/extensions/notebook-markdown-extensions/notebook-out/emoji.js')
    at a.doReadFileStream (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:28:20883)
    at async L (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:48:20461)
    at async g (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:48:21380)
    at async yt.handleWebviewResourceRequest (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:48:30842) {
  fileOperationResult: 1,
  options: { etag: undefined }
}
```

Even though the remote tests pass, we were seeing tons of above errors.

**Comment by rebornix** [comment]
I think this might share the same root cause as the browser integration failure.

**Comment by mjbvz** [comment]
What are you running to see these errors? I don't see them with `./scripts/test-ingegration` or with the remote integration tests

**Comment by mjbvz** [comment]
I pushed a change to the test script to build these files (I added an additional `gulp` task to the test script)

Kicking off a private build not to confirm that it is fixed

**Comment by mjbvz** [comment]
I believe this has been fixed. Here  are the logs from a full test run: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=115710&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=41d9f3a8-af10-5350-1c03-229d27a4a1b6

I no longer see the errors about `katex`. 

Please let me know if you still see this somewhere
