### ISSUE TITLE
VS Code hangs when update dependencies

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/vscode#12042]
- VSCode Version: 1.5.2
- OS Version: Windows 10 (AU)

Steps to Reproduce:
1. Open a proyect fresh cloned.
2. Run `npm install` in a (external) terminal.

VS Code stop responding. I ran it with the integrated terminal and an external one with the same results. 

Edit typo.

**Comment by bpasero** [comment]
@michaeljota does this produce a top level node_modules folder? can you share your settings?

**Comment by michaeljota** [comment]
I notice this with top level node_modules only. Have not tried with any other. What settings do you need? I don't have settings changed from the editor, just few extensions. 

I got Sync Settings, I can give you the gist url, but it's just the list of extensions.

**Comment by bpasero** [comment]
I am wondering if this is file event related and you changed the built in `files.watcherExclude` setting in any way?

**Comment by michaeljota** [comment]
It happens to me with differents projects, not just one.

**Comment by bpasero** [comment]
@michaeljota can you share your user settings and workspace settings or at least see if you once configured this setting `files.watcherExclude`?

**Comment by michaeljota** [comment]
I don't have any user settings not workspace settings. I have not configured `files.watcherExclude`.

You can see my settings [here](https://gist.github.com/michaeljota/0d34130753d9d61b7165)

**Comment by bpasero** [comment]
@michaeljota does this reproduce with any kind of npm install? I am wondering if the amount of modules getting installed has an impact. E.g. can we try with a small package.json that maybe only has one dependency to see if it reproduces?

**Comment by michaeljota** [comment]
With this files hangs
```json
{
  "name": "angular2",
  "version": "0.0.1",
  "dependencies": {
    "@angular/common": "2.0.0-rc.7",
    "@angular/compiler": "2.0.0-rc.7",
    "@angular/core": "2.0.0-rc.7",
    "@angular/forms": "2.0.0-rc.7",
    "@angular/http": "2.0.0-rc.7",
    "@angular/platform-browser": "2.0.0-rc.7",
    "@angular/platform-browser-dynamic": "2.0.0-rc.7",
    "@angular/router": "3.0.0-rc.3",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  }
}
```

Let me try something smaller.

**Comment by bpasero** [comment]
@michaeljota 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by fibric** [comment]
I have the same issue. When running `npm i` VScode freezes and npm fails because of file/folder lock caused by VScode.

npm complains about insuficient permissions because it can't rename/move files&folders at the finishing stage.
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\denny.trebbin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! path C:\code\js\products\sfi.sebn.com\backend\node_modules\.staging\ajv-keywords-38f0ca98
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\code\js\products\sfi.sebn.com\backend\node_modules\.staging\ajv-keywords-38f0ca98' -> 'C:\code\js\products\sfi.sebn.com\backend\node_modules\ajv-keywords'
npm ERR!     at destStatted (C:\Users\denny.trebbin\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\code\js\products\sfi.sebn.com\backend\node_modules\.staging\ajv-keywords-38f0ca98' -> 'C:\code\js\products\sfi.sebn.com\backend\node_modules\ajv-keywords'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\code\js\products\sfi.sebn.com\backend\node_modules\.staging\ajv-keywords-38f0ca98' -> 'C:\code\js\products\sfi.sebn.com\backend\node_modules\ajv-keywords'
npm ERR!     at destStatted (C:\Users\denny.trebbin\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\code\js\products\sfi.sebn.com\backend\node_modules\.staging\ajv-keywords-38f0ca98' -> 'C:\code\js\products\sfi.sebn.com\backend\node_modules\ajv-keywords'
npm ERR!     at Error (native) parent: 'sfi_backend' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\code\js\products\sfi.sebn.com\backend\npm-debug.log
```

VSCode locked a lot of files.
![VScode locked a lot of files](https://cloud.githubusercontent.com/assets/623932/18632207/8c52f01c-7e76-11e6-9033-7171456590e9.png)

Process Explorer shows interesting stuff.
![Process Explorer shows how much CPU time VScode consumes](https://cloud.githubusercontent.com/assets/623932/18632243/b71aa3e4-7e76-11e6-9d15-1ec731e40954.png)

**Comment by bpasero** [comment]
@fibric can you hover over the processes in process explorer to find out their command line arguments? this would help finding out which process is hogging CPU

**Comment by fibric** [comment]
@bpasero sorry, it took me a while; I have no Windows machine at home.
![1](https://cloud.githubusercontent.com/assets/623932/18666718/a619038a-7f2d-11e6-8948-3201cff25cc5.png)
![2](https://cloud.githubusercontent.com/assets/623932/18666719/a61be76c-7f2d-11e6-8fb7-9d3d7b09d8e0.png)
![3](https://cloud.githubusercontent.com/assets/623932/18666720/a61c45fe-7f2d-11e6-9b1c-7c5f77caecd0.png)
![4](https://cloud.githubusercontent.com/assets/623932/18666723/a6243822-7f2d-11e6-9fb7-0f6ca67ce70d.png)
![5](https://cloud.githubusercontent.com/assets/623932/18666722/a61fc350-7f2d-11e6-950f-0fac39f95a21.png)
![6](https://cloud.githubusercontent.com/assets/623932/18666721/a61f46be-7f2d-11e6-9c5a-a8a970c25a27.png)
![7](https://cloud.githubusercontent.com/assets/623932/18666724/a62ebab8-7f2d-11e6-9c8b-491122d97a79.png)
![8](https://cloud.githubusercontent.com/assets/623932/18666725/a632614a-7f2d-11e6-9449-02b4e6a136aa.png)
![9](https://cloud.githubusercontent.com/assets/623932/18666726/a635abca-7f2d-11e6-9d7d-6c62401febc8.png)
![10](https://cloud.githubusercontent.com/assets/623932/18666727/a6365336-7f2d-11e6-8cec-0a89338d9ed3.png)

**Comment by bpasero** [comment]
@michaeljota you still there?

@fibric in those screenshots I am not seeing a process with high CPU though? you say you cannot reproduce in insiders?

**Comment by fibric** [comment]
Oh well, I forgot about it.
I took the before pictures but forgot about the when-it's-happinging pictures. I'll do that on Monday when I'm in office again.

**Comment by michaeljota** [comment]
@bpasero I'm here, but I don't know what program is that. Witch you would recommend me?

**Comment by bpasero** [comment]
@michaeljota a tool to see the full command line arguments of the processes (https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx?f=255&MSPPError=-2147217396). it would allow us to find the process that consumes so much CPU for you.

**Comment by fibric** [comment]
I have only two processes which steal a lot of CPU time while running `npm i`. The freeze+hang situation seems to be gone now. 

![100](https://cloud.githubusercontent.com/assets/623932/18832819/c774ef84-83ed-11e6-8e32-b9f0c7af19e2.png)
![101](https://cloud.githubusercontent.com/assets/623932/18832820/c795b53e-83ed-11e6-8f14-b0eef1cf701d.png)

In the user preferences, I found a search option

```typescript
{
...,
  // Configure glob patterns of file paths to exclude from file watching. Changing this setting requires a restart. When you experience Code consuming lots of CPU time on startup, you can exclude large folders to reduce the initial load.
  "files.watcherExclude": {
    "**/.git/objects/**": true
  },
...,
  // Configure glob patterns for excluding files and folders in searches. Inherits all glob patterns from the files.exclude setting.
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },
...
}
```
I added `"**/node_modules": true,` to `files.watcherExclude` just to be save. The CPU consumption is still very high but VScode doesn't freeze&hang anymore; it's just a bit unresponsive while `npm i` runs.

**Comment by bpasero** [comment]
@fibric yes you definitely want to have node_modules in the excludes and they are by default (maybe you configured it once when it was not yet):

```
"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/node_modules/**": true
	}
```

**Comment by fibric** [comment]
On my VScode installation, `node_modules` isn't defined by default.
![image](https://cloud.githubusercontent.com/assets/623932/18835578/fb8745b6-83fb-11e6-8670-86e67c88a072.png)
![image](https://cloud.githubusercontent.com/assets/623932/18835589/0e6d315e-83fc-11e6-8087-85a846bf6221.png)

**Comment by bpasero** [comment]
@fibric sorry you are right, we only exclude it on Mac and Linux where our file watcher is not very efficient for large folders. We do not have seen this issue on Windows yet.

**Comment by bpasero** [comment]
@michaeljota 
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by fibric** [comment]
I experienced another hang situation.
![image](https://cloud.githubusercontent.com/assets/623932/18953366/64f82052-864e-11e6-9b93-06bc3837872e.png)

This time, I opened a huge file with 16000+ LoC.

**Comment by bpasero** [comment]
@fibric ok, now you are forking this issue into something else I think because this originally was about hang when running "npm install". please create a new issue for your CPU issue when opening a large file.

**Comment by bpasero** [comment]
Closing due to inactivity of @michaeljota

**Comment by michaeljota** [comment]
I have this in my todo list. Just been busy. I'm sorry.

**Comment by bpasero** [comment]
Thats fine, reopening.

**Comment by michaeljota** [comment]
OK. Just try to `npm install` and in VS Code `1.5.3` this is not longer an issue. Seems to be fixed to me. If someone else can confirm would be better, but I'm not able to reproduce this again.

**Comment by bpasero** [comment]
OK please report back then if it happens again. However since this seems to happen sporadically, it seems like an indeterministic issue.

**Comment by michaeljota** [comment]
Sure. Thanks! Sorry for the delay.

**Comment by michaeljota** [comment]
@bpasero I'm sorry, but I'm having this same issue with lastes stable Code (1.7.1).

You can run `npm install` with this repo to reproduce the issue. [angular2-ultimate-starter](https://github.com/michaeljota/angular2-ultimate-starter).

The screens from `Process Explorer`:
![captura de pantalla 31](https://cloud.githubusercontent.com/assets/10507776/20484712/f26bba4e-afce-11e6-9224-796e93771504.png)
![captura de pantalla 32](https://cloud.githubusercontent.com/assets/10507776/20484713/f2700cc0-afce-11e6-8514-ed1c431479aa.png)
![captura de pantalla 33](https://cloud.githubusercontent.com/assets/10507776/20484714/f273a1b4-afce-11e6-9a3c-92b1b8dba3dc.png)
![captura de pantalla 34](https://cloud.githubusercontent.com/assets/10507776/20484715/f278fb50-afce-11e6-85d6-1febea50c4cd.png)
![captura de pantalla 35](https://cloud.githubusercontent.com/assets/10507776/20484716/f27cf4a8-afce-11e6-8df8-69485dc4961b.png)
![captura de pantalla 36](https://cloud.githubusercontent.com/assets/10507776/20484717/f28105c0-afce-11e6-8194-1fb969f1317e.png)
![captura de pantalla 37](https://cloud.githubusercontent.com/assets/10507776/20484718/f28508c8-afce-11e6-9ed5-d0a108fe5ab6.png)
![captura de pantalla 38](https://cloud.githubusercontent.com/assets/10507776/20484719/f28e35f6-afce-11e6-8d83-632c65d2eb64.png)
![captura de pantalla 39](https://cloud.githubusercontent.com/assets/10507776/20484720/f2905638-afce-11e6-9df7-f8aadfcecdd1.png)
![captura de pantalla 40](https://cloud.githubusercontent.com/assets/10507776/20484721/f291b794-afce-11e6-8a57-f3bf3b1f5e7d.png)
![captura de pantalla 41](https://cloud.githubusercontent.com/assets/10507776/20484722/f295e710-afce-11e6-8e86-31304307400e.png)
![captura de pantalla 42](https://cloud.githubusercontent.com/assets/10507776/20484723/f299fdd2-afce-11e6-8f0c-295b18aaeb74.png)
![captura de pantalla 43](https://cloud.githubusercontent.com/assets/10507776/20484724/f29e95d6-afce-11e6-92ac-a9bbf179d5b6.png)

User config: 
```json
// Coloque su configuración en este archivo para sobrescribir la configuración predeterminada.
{
    "editor.fontFamily": "Hasklig, Consolas, 'Courier New', monospace"
}
```
 Workspace config:
```json
{
  "typescript.tsdk": "node_modules/typescript/lib/",
  "auto-close-tag.activationOnLanguage": [
    "html"
  ],
  "typescriptHero.resolver.multiLineWrapThreshold": 100
}
```
Extensions: (Installed. Recommended in workspace as well)
```json
{
  // See http://go.microsoft.com/fwlink/?LinkId=827846
  // for the documentation about the extensions.json format
  "recommendations": [
    // Extension identifier format: ${publisher}.${name}. Example: vscode.csharp

    "abusaidm.html-snippets",
    "christian-kohler.path-intellisense",
    "EditorConfig.EditorConfig",
    "eg2.tslint",
    "formulahendry.auto-close-tag",
    "formulahendry.auto-rename-tag",
    "joelday.docthis",
    "johnpapa.Angular2",
    "msjsdiag.debugger-for-chrome",
    "natewallace.angular2-inline",
    "rbbit.typescript-hero"
  ]
}
```

**Comment by michaeljota** [comment]
If you need anything else, I'll try to help you. This issue is really edge, but with this configuration for some reason keeps happing. I work with that seed in my projects, and in everyone of them it's the same. I have to close VSCode when I'm going to install.

**Comment by bpasero** [comment]
@michaeljota 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by michaeljota** [comment]
@bpasero it is still reproducible.

**Comment by bpasero** [comment]
@michaeljota I tried to reproduce and could not. in your screen shots I am also not seeing a CPU spending high cycles in some task, how does the lag show to you then? does VS Code freeze? Also can you share your settings with me?

**Comment by michaeljota** [comment]
I already share them, settings and extension set,  just after my set of pictures. The VSCode freeze and ask for reload.

**Comment by michaeljota** [comment]
@bpasero Hi! I reproduce this with another, and smaller, project. 

Steps: 
- Open project
- Small styles edit to the first file that opens
- (in an external console) `npm install nodemon -D`. Maybe it's worth to notice how many dependencies `nodemon` has.
- Comeback to VSCode to see it freeze.

`package.json`
```json
{
  "name": "graphql-postgres",
  "version": "1.0.0",
  "description": "An example GraphQL server using a PostgreSQL DB",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "tsc": "tsc"
  },
  "author": "Michael De Abreu",
  "license": "MIT",
  "dependencies": {
    "express": "^4.14.0",
    "express-graphql": "^0.6.1",
    "faker": "^3.1.0",
    "graphiql": "^0.8.1",
    "graphql": "^0.8.2",
    "pg": "^6.1.2",
    "pg-hstore": "^2.3.2",
    "sequelize": "^3.29.0",
    "ts-node": "^2.0.0",
    "typescript": "^2.1.5"
  },
  "devDependencies": {
    "@types/express": "^4.0.35",
    "@types/express-graphql": "0.0.33",
    "@types/faker": "^3.1.32",
    "@types/graphql": "^0.8.6",
    "@types/node": "^6.0.60",
    "@types/pg": "^6.1.34",
    "@types/sequelize": "^4.0.39",
    "nodemon": "^1.11.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}
```
`tsconfig.json` (for reasons)
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": {
    },
    "lib": [
      "dom",
      "es6",
      "es2017"
    ],
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true
  }
}
```
User `settings.json`
```json
// Coloque su configuración en este archivo para sobrescribir la configuración predeterminada.
{
    "editor.fontFamily": "Hasklig, Consolas, 'Courier New', monospace",
}
```
Workspace `settings.json`
```json
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```
Extensions
```
johnpapa.Angular2
natewallace.angular2-inline
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
msjsdiag.debugger-for-chrome
joelday.docthis
EditorConfig.EditorConfig
christian-kohler.path-intellisense
eg2.tslint
rbbit.typescript-hero
```
It's literally a five files project. 
[graphql-postgres.zip](https://github.com/Microsoft/vscode/files/719388/graphql-postgres.zip)

Explorer Process Screens
![captura de pantalla 50](https://cloud.githubusercontent.com/assets/10507776/22149824/5ba0594c-deec-11e6-9db6-185ef3120d00.png)
![captura de pantalla 51](https://cloud.githubusercontent.com/assets/10507776/22149826/5ba1cff2-deec-11e6-8308-e975441031f5.png)
![captura de pantalla 52](https://cloud.githubusercontent.com/assets/10507776/22149825/5ba16184-deec-11e6-84fb-a6147e484c30.png)
![captura de pantalla 53](https://cloud.githubusercontent.com/assets/10507776/22149828/5ba2fa76-deec-11e6-88c8-408b6bac47f1.png)
![captura de pantalla 54](https://cloud.githubusercontent.com/assets/10507776/22149829/5ba3b4b6-deec-11e6-990f-be1c5063a952.png)
![captura de pantalla 55](https://cloud.githubusercontent.com/assets/10507776/22149827/5ba2d4d8-deec-11e6-81b9-2d3d72c5978d.png)
![captura de pantalla 56](https://cloud.githubusercontent.com/assets/10507776/22149830/5bb082fe-deec-11e6-979a-608863be698d.png)
![captura de pantalla 57](https://cloud.githubusercontent.com/assets/10507776/22149834/5bb625c4-deec-11e6-92f6-c1003bc858c8.png)
![captura de pantalla 58](https://cloud.githubusercontent.com/assets/10507776/22149831/5bb4d138-deec-11e6-8e51-70805d80ffdd.png)
![captura de pantalla 59](https://cloud.githubusercontent.com/assets/10507776/22149832/5bb524d0-deec-11e6-9d3b-e8963e6f5d23.png)
![captura de pantalla 60](https://cloud.githubusercontent.com/assets/10507776/22149833/5bb60af8-deec-11e6-8641-9b1e9ee16396.png)
![captura de pantalla 61](https://cloud.githubusercontent.com/assets/10507776/22149835/5bb75502-deec-11e6-9dd8-742ecf5043cc.png)
![captura de pantalla 62](https://cloud.githubusercontent.com/assets/10507776/22149836/5bc16cae-deec-11e6-8103-6e811d0ca4c6.png)
![captura de pantalla 63](https://cloud.githubusercontent.com/assets/10507776/22149837/5bc68a5e-deec-11e6-93fd-32ba0652f0cb.png)
![captura de pantalla 64](https://cloud.githubusercontent.com/assets/10507776/22149838/5bc6b27c-deec-11e6-804d-7f5a9cca3b38.png)
![captura de pantalla 65](https://cloud.githubusercontent.com/assets/10507776/22149839/5bc8d3cc-deec-11e6-82fe-5c8bf3dce2da.png)
![captura de pantalla 66](https://cloud.githubusercontent.com/assets/10507776/22149840/5bc961b6-deec-11e6-848a-33a38a6d2d22.png)

VSCode frozen
![captura de pantalla 67](https://cloud.githubusercontent.com/assets/10507776/22149853/6a407388-deec-11e6-80fd-1eabeab47081.png)

**Comment by bpasero** [comment]
@michaeljota I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
@michaeljota  is this still happening with our latest insider build? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by michaeljota** [comment]
I see what you did there. I'll test it and report. 👍

**Comment by bpasero** [comment]
Let's merge into https://github.com/Microsoft/vscode/issues/3998
