### ISSUE TITLE
Integration web tests print: Server stderr: Error: Not supported

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120547]
Run the web integration tests and notice a stack right in the beginning:

```
Server stderr: Error: Not supported: $onProcessBinary
    at RemoteTerminalChannel.listen (/Users/bpasero/Development/Microsoft/monaco/out/vs/server/remoteTerminalChannel.js:102:19)
    at ChannelServer.onEventListen (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:287:35)
    at ChannelServer.onRawMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:231:33)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:171:73
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at PersistentProtocol._receiveMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:510:83
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at ProtocolReader.acceptChunk (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:158:61
    at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:395:42
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8)
```

**Comment by bpasero** [comment]
Anyone?

**Comment by Tyriar** [comment]
This is probably actually a bug that would cause some mouse events not to work in remote terminals.

**Comment by Tyriar** [comment]
@meganrogge figured it out, remote mouse events now work 🎉.  See linked commits for what the issue was.

**Comment by Tyriar** [comment]
To verifier:

1. Connect to remote Linux/macOS box
2. Open a file in vim
3. esc, `:set mouse=a`
4. Try to move the cursor/select inside vim

**Comment by bpasero** [comment]
I verified that my exception no longer prints when running web integration tests.
