### ISSUE TITLE
Unit test "moveEditor with context (across groups)" prints exceptions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120614]
The `moveEditor with context (across groups)` prints these exceptions:

```
"Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js:153:34)
    at TabsTitleControl.getEditorActions (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/titleControl.js:142:51)
    at TabsTitleControl.updateEditorActionsToolbar (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/titleControl.js:103:101)
    at TabsTitleControl.updateEditorActionsToolbar (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/tabsTitleControl.js:248:19)
    at TabsTitleControl.setActive (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/tabsTitleControl.js:345:18)
    at EditorGroupView.setActive (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:536:35)
    at TestEditorPart.doSetGroupActive (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorPart.js:416:19)
    at TestEditorPart.activateGroup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorPart.js:207:18)
    at EditorGroupView.doOpenEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:716:31)
    at EditorGroupView.openEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:647:25)
    at EditorGroupView.doMoveOrCopyEditorAcrossGroups (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:894:20)
    at EditorGroupView.moveEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/editor/editorGroupView.js:851:22)
    at Context.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/editor/test/browser/editorGroupsService.test.js:952:24)", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/lifecycle.js (153)
```

Moving to April because I am not sure this is a bug with the test or the code. I can also assist as needed.

**Comment by lramos15** [comment]
Seemed to have been caused by empty groups getting disposed of when they had no inputs in them. Fixed it by adding an input to the test that doesn't move around so there was always two groups. :+1:

**Comment by bpasero** [comment]
Hm, I wonder if you found an actual issue with empty groups. Any idea for how to reproduce locally without a test?

**Comment by lramos15** [comment]
I'm not able to reproduce it doing similar things from the test. My guess is that it defaults to closing empty groups, but my variable still has a reference to that since closed empty group. While in the editor we know that this empty group has been closed and therefore don't keep the dirty reference and instead make a new group when one is opened.
