### ISSUE TITLE
Notebook cell metadata not saved during edit operation.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#120760]
- VS Code Version: Insiders
- OS Version: All

Steps to Reproduce:

0. Occurs from within the .NET Interactive extension.
1. Clone https://github.com/dotnet/interactive
2. cd src/dotnet-interactive-vscode/insiders
3. npm i
4. code-insiders .
5. Open src/common/vscode/extension.ts
6. Set a breakpoint on line 212.
7. F5

Expected:
Cell metadata should be set to the new value.

Result:
The custom metadata is not set.  The result of `applyEdit` was `false`, but no visible error was produced.

`newMetadata`:
![image](https://user-images.githubusercontent.com/926281/113933897-fb850c80-97a9-11eb-9eed-3de02f5edde1.png)

`cell.metadata` after update:
![image](https://user-images.githubusercontent.com/926281/113933974-1061a000-97aa-11eb-9169-83865c7b663e.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> The custom metadata is not set. The result of applyEdit was false, but no visible error was produced.

There is no guarantee that an edit will success and when `false` is returned it didn't success. This is caused by a concurrent modification. Do by any change have another edit that runs in parallel and isn't await'ed?

**Comment by brettfo** [comment]
I just set breakpoints everywhere we have `new vscode.WorkspaceEdit()` and we don't have any overlapping ones.

**Comment by jrieken** [comment]
Today's insiders should print a message in the window log why this happens. That should reveal more information

**Comment by brettfo** [comment]
I cleared all logs, tried to update cell metadata, then got this from the `Log (Window)` output channel:

```
[2021-04-09 11:26:16.175] [renderer3] [error] Error: CANNOT open a cell-uri as notebook. Tried with vscode-notebook-cell:Untitled-1.ipynb#ch0000003untitled
    at S.resolve (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2280:60052)
    at v.apply (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:993:29456)
    at o._performCellEdits (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2280:28754)
    at o.perform (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2280:28033)
    at s.apply (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2280:30270)
    at v.$tryApplyWorkspaceEdit (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2256:24797)
    at s._doInvokeHandler (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1628:11977)
    at s._invokeHandler (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1628:11661)
    at s._receiveRequest (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1628:10331)
    at s._receiveOneMessage (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1628:9117)
    at file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1628:7218
    at c.fire (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at r.fire (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16186)
    at i._receiveMessage (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21444)
    at file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18330
    at c.fire (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at u.acceptChunk (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13551)
    at file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12899
    at Socket.D (file:///C:/Users/brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2820:55286)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
[2021-04-09 11:26:16.176] [renderer3] [warning] IGNORING workspace edit {}
```

From that log I was able to determine my problem, I need to make this change:

``` diff
-edit.replaceNotebookCellMetadata(cell.uri, cell.index, newMetadata);
+edit.replaceNotebookCellMetadata(notebook.uri, cell.index, newMetadata);
```

Closing this as it's fixed, but maybe the parameter to the function could be renamed from `uri` to `notebookUri` or a doc comment added?

Either way, thank you for adding the log, this is exactly what I needed.
