### ISSUE TITLE
Terminal tabs panel issues

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#120906]
Some early feedback since I accidentally enabled this with the setting:

- [x] Left pane needs a higher minimum width, or a better overflow behavior. You can even remove the left padding from each row, to get more space there.
- [x] Growing/shrinking the splitview should not use the proportional resizing. We should use [different layout priorities](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/browser/ui/splitview/splitview.ts#L40-L47) to make sure the left pane doesn't shrink when the entire workbench shrinks, unless absolutely necessary, similar to the workbench sidebar.
- [x] We should probably use the new [`selectionNavigation`](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/platform/list/browser/listService.ts#L196-L196) setting to prevent focus from being different from selection
- [x] Right click on list, `New Terminal`, 🐛 all list items are selected. Same if you toggle the setting off/on.

![recording (1)](https://user-images.githubusercontent.com/22350/114147138-3d5aa380-98cd-11eb-9571-6f1a670d5166.gif)

**Comment by joaomoreno** [comment]
Also not sure to repro, but just by using it it was easy to find some error stack traces in devtools:

```
  ERR TreeError [TerminalTabsTree] Tree element not found: [object Object]: Error: TreeError [TerminalTabsTree] Tree element not found: [object Object]
    at ObjectTreeModel.getNode (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:165:23)
    at file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1178:56
    at Array.map (<anonymous>)
    at TerminalTabsWidget.setFocus (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1178:36)
    at file:///home/joao/Work/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsWidget.js:53:26
    at Emitter.fire (file:///home/joao/Work/vscode/out/vs/base/common/event.js:479:38)
    at TerminalService.setActiveInstanceByIndex (file:///home/joao/Work/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:520:42)
    at TerminalService.createTerminal (file:///home/joao/Work/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:875:22)
    at file:///home/joao/Work/vscode/out/vs/workbench/contrib/terminal/browser/terminalView.js:76:55
    at Emitter.fire (file:///home/joao/Work/vscode/out/vs/base/common/event.js:479:38)
    at TerminalViewPane.setVisible (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/views/viewPane.js:143:53)
    at file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:493:37
    at Array.map (<anonymous>)
    at ViewPaneContainer.setVisible (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:493:18)
    at PaneContainerPanel.setVisible (file:///home/joao/Work/vscode/out/vs/workbench/browser/panecomposite.js:35:83)
    at PanelPart.showComposite (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/compositePart.js:168:23)
    at PanelPart.doOpenComposite (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/compositePart.js:75:18)
    at PanelPart.openComposite (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/compositePart.js:47:25)
    at PanelPart.doOpenPanel (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:347:25)
    at PanelPart.openPanel (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:351:29)
    at ViewsService.openComposite (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/views/viewsService.js:120:42)
    at ViewsService.openView (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/views/viewsService.js:227:50)
    at OpenViewAction.run (file:///home/joao/Work/vscode/out/vs/workbench/browser/parts/views/viewsService.js:406:42)
    at handler (file:///home/joao/Work/vscode/out/vs/platform/actions/common/actions.js:355:52)
    at InstantiationService.invokeFunction (file:///home/joao/Work/vscode/out/vs/platform/instantiation/common/instantiationService.js:44:24)
    at CommandService._tryExecuteCommand (file:///home/joao/Work/vscode/out/vs/workbench/services/commands/common/commandService.js:74:59)
    at file:///home/joao/Work/vscode/out/vs/workbench/services/commands/common/commandService.js:64:47
```

**Comment by Tyriar** [comment]
Yeah a little early for feedback, we're pushing early while it's still rough to minimize the amount of merge conflicts between us. Thanks for the insights around layout priority and selection navigation though, will look into them.

**Comment by Tyriar** [comment]
And the overflow behavior will be better, you can see the mockups what we will be going for here https://github.com/microsoft/vscode/issues/10546#issuecomment-800286034

**Comment by meganrogge** [comment]
Also fixed by some work by @Tyriar

**Comment by meganrogge** [comment]
Still seeing some weirdness with multiple items getting selected
