### ISSUE TITLE
code-oss not starting in Manjaro Ornara

### ISSUE THREAD

**Issue by BishopWolf** [microsoft/vscode#121047]
- VS Code Version: 1.54.3
- OS Version: Manjaro 21.0.1 Ornara

Steps to Reproduce:

1. Install code-oss from package  manager
2. run code

Does this issue occur when all extensions are disabled?: Yes

```
[alex@alex-b450aoruselite ~]$ code --disable-extensions --verbose
(electron:6878): Gtk-WARNING **: 15:19:06.613: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[6906:0411/151906.903262:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Error: /usr/lib/code/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at v (/usr/lib/code/out/vs/loader.js:3:12287)
    at bindings (/usr/lib/code/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/lib/code/out/vs/loader.js:3:12841)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at t (/usr/lib/code/out/vs/loader.js:4:101)
    at r.load (/usr/lib/code/out/vs/loader.js:3:13249)
    at r.load (/usr/lib/code/out/vs/loader.js:3:10262)
    at c (/usr/lib/code/out/vs/loader.js:4:10314)
    at Object.errorback (/usr/lib/code/out/vs/loader.js:4:10435)
    at r.triggerErrorback (/usr/lib/code/out/vs/loader.js:3:10626)
    at /usr/lib/code/out/vs/loader.js:3:10332
    at r.load (/usr/lib/code/out/vs/loader.js:3:13266)
    at r.load (/usr/lib/code/out/vs/loader.js:3:10262)
    at c (/usr/lib/code/out/vs/loader.js:4:10314)
    at r._loadModule (/usr/lib/code/out/vs/loader.js:4:10444)
    at r._resolve (/usr/lib/code/out/vs/loader.js:5:452)
    at r.defineModule (/usr/lib/code/out/vs/loader.js:4:6145)
    at r._relativeRequire (/usr/lib/code/out/vs/loader.js:4:6831)
    at n (/usr/lib/code/out/vs/loader.js:4:9420)
    at L.E (/usr/lib/code/out/vs/code/electron-main/main.js:29:4689)
    at new Promise (<anonymous>)
    at L (/usr/lib/code/out/vs/code/electron-main/main.js:29:4669)
    at n._createSpdLogLogger (/usr/lib/code/out/vs/code/electron-main/main.js:29:5602)
    at new n (/usr/lib/code/out/vs/code/electron-main/main.js:29:5418)
    at /usr/lib/code/out/vs/code/electron-main/main.js:58:1945
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async j.startup (/usr/lib/code/out/vs/code/electron-main/main.js:58:1760) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[main 2021-04-11T13:19:06.940Z] TypeError: L.ipcMain.handle is not a function
    at ut.registerListeners (/usr/lib/code/out/vs/code/electron-main/main.js:56:55968)
    at new ut (/usr/lib/code/out/vs/code/electron-main/main.js:56:52041)
    at k._createInstance (/usr/lib/code/out/vs/code/electron-main/main.js:26:26880)
    at k.createInstance (/usr/lib/code/out/vs/code/electron-main/main.js:26:26299)
    at /usr/lib/code/out/vs/code/electron-main/main.js:58:2081
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async j.startup (/usr/lib/code/out/vs/code/electron-main/main.js:58:1760)
[main 2021-04-11T13:19:06.940Z] Lifecycle#kill()
```

**Comment by BishopWolf** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [vscode freezing on centos7 (#119031)](https://www.github.com/microsoft/vscode/issues/119031)

Not the same issue, I have tried also code-git (version 1.56) from AUR. The build is sucessful but the error persists.

**Comment by BishopWolf** [comment]
I have tried removing electron completely, then reinstall code and everything works now!
