### ISSUE TITLE
ssh: could not resolve the hostname 

### ISSUE THREAD

**Issue by nodirg** [microsoft/vscode#121158]
Issue Type: <b>Bug</b>

I have a VM instance on Google Cloud Platform. 
I configured SSH using gcloud command:
  gcloud --project google.com:chromecompute compute config-ssh
and I am able to connect to the VM with just
  ssh crbug-1193375.us-central1-b.google.com:chromecompute 

However, when I try to connect to it via VSCode Remote, it fails with "Could not resolve hostname" error.

----------

Log:
[23:59:16.619] Log Level: 2
[23:59:16.621] remote-ssh@0.65.1
[23:59:16.621] linux x64
[23:59:16.623] SSH Resolver called for "ssh-remote+crbug-1193375.us-central1-b.google.com:chromecompute", attempt 1
[23:59:16.623] "remote.SSH.useLocalServer": true
[23:59:16.623] "remote.SSH.sshPath": undefined
[23:59:16.623] "remote.SSH.sshConfigurationFile": undefined
[23:59:16.624] "remote.SSH.useFlock": true
[23:59:16.624] "remote.SSH.lockfilesInTmp": false
[23:59:16.624] "remote.SSH.localServerDownload": auto
[23:59:16.624] "remote.SSH.remoteServerListenOnSocket": false
[23:59:16.624] "remote.SSH.showLoginTerminal": false
[23:59:16.624] "remote.SSH.defaultExtensions": []
[23:59:16.625] SSH Resolver called for host: crbug-1193375.us-central1-b.google.com:chromecompute
[23:59:16.625] Setting up SSH remote "crbug-1193375.us-central1-b.google.com:chromecompute"
[23:59:16.628] Acquiring local install lock: /tmp/vscode-remote-ssh-crbug-1193375.us-central1-b.google.com:chromecompute-install.lock
[23:59:16.634] Looking for existing server data file at /home/nodir/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-crbug-1193375.us-central1-b.google.com:chromecompute-c185983a683d14c396952dd432459097bc7f757f-0.65.1/data.json
[23:59:16.635] Using commit id "c185983a683d14c396952dd432459097bc7f757f" and quality "stable" for server
[23:59:16.639] Install and start server if needed
[23:59:16.647] Checking ssh with "ssh -V"
[23:59:16.666] > OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021

[23:59:16.675] askpass server listening on /run/user/235496/vscode-ssh-askpass-d4af14fa7ecac1fca578f8772443a0ef810c64e8.sock
[23:59:16.675] Spawning local server with {"ipcHandlePath":"/run/user/235496/vscode-ssh-askpass-3806b9a720203ca5c72f2210a41d9193924e0d2c.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","38507","-o","ConnectTimeout=15","crbug-1193375.us-central1-b.google.com:chromecompute"],"dataFilePath":"/home/nodir/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-crbug-1193375.us-central1-b.google.com:chromecompute-c185983a683d14c396952dd432459097bc7f757f-0.65.1/data.json"}
[23:59:16.675] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/235496/vscode-ssh-askpass-d4af14fa7ecac1fca578f8772443a0ef810c64e8.sock"}
[23:59:16.678] Spawned 183786
[23:59:16.760] > local-server> Spawned ssh: 183794
[23:59:16.762] stderr> OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021
[23:59:16.763] stderr> ssh: Could not resolve hostname crbug-1193375.us-central1-b.google.com:chromecompute: Name or service not known
[23:59:16.763] > local-server> ssh child died, shutting down
[23:59:16.765] Local server exit: 0
[23:59:16.766] Received install output: OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021
ssh: Could not resolve hostname crbug-1193375.us-central1-b.google.com:chromecompute: Name or service not known

[23:59:16.773] Resolver error: Error: Could not resolve hostname
	at Function.Offline (/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64379)
	at /home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:61814
	at Object.t.handleInstallOutput (/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:62301)
	at Object.t.tryInstallWithLocalServer (/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:388682)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:293749
	at async Object.t.withShowDetailsEvent (/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:407055)
	at async /home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387177
	at async N (/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:386804)
	at async Object.t.resolve (/home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:297790)
	at async /home/nodir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:127:110485
[23:59:16.785] ------

[00:01:06.805] Picking SSH host
[00:01:08.798] Selected crbug-1193375.us-central1-b.google.com:chromecompute

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.10.19-1rodete1-amd64
Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname
Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname
Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname
Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 3195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (0.98GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id b128ad96-db6c-4690-b8f9-35ff71b863df|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|

Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname

Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname

Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname

Fetching remote diagnostics for 'SSH' failed: Could not resolve hostname
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30286881

```

</details>

**Comment by roblourens** [comment]
Interesting. Is this in your ssh config? The `:chromecompute` at the end is suspicious to me, I would not expect to see something after `.com`.

**Comment by nodirg** [comment]
Yes, I have `crbug-1193375.us-central1-b.google.com:chromecompute` in my `~/.ssh/config`:

```
Host crbug-1193375.us-central1-b.google.com:chromecompute
    HostName 104.155.241.189
    IdentityFile /home/nodir/.ssh/google_compute_engine
    UserKnownHostsFile=/home/nodir/.ssh/google_compute_known_hosts
    HostKeyAlias=compute.3773847346536285089
    IdentitiesOnly=yes
    CheckHostIP=no
```

I am pretty sure `google.com:chromecompute` here is the Google Cloud project id (that's the project ID. Projects in organization `foo.com` starts with `foo.com:`).

I am not an expert in SSH, but it seems like in SSH world, a connectable-host does not have to be a valid domain name, and it seems like VSCode assumes that it is always a valid domain name.

**Comment by roblourens** [comment]
vscode doesn't assume anything, the error is coming from SSH. Either it is not finding the Host, could you change the name to something like `test` to check? I don't know if I need to escape the `:` the way I launch or something.

Or, it is not finding your ssh config file, I don't know why that would happen but you can get more info in the log if you set `"remote.SSH.logLevel": "trace"`
