### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by tianyinggang** [microsoft/vscode#121290]
error log:

make: *** [Release/obj.target/keymapping/src/keymapping.o] Error 1
make: Leaving directory `/root/vscode_web/vscode/node_modules/native-keymap/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 3.10.0-1160.11.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/vscode_web/vscode/node_modules/native-keymap

**Comment by tianyinggang** [comment]
i try the #116925 issues  answer ,but  still don ‘t build：

all error log：
[root@VM-0-7-centos vscode]# yarn
yarn install v1.22.10
$ node build/npm/preinstall.js
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.1: The platform "linux" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-ca-certs@0.3.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.3: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-foreground-love@0.2.0: The platform "linux" is incompatible with this module.
info "windows-foreground-love@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.3.0: The platform "linux" is incompatible with this module.
info "windows-mutex@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.3.0: The platform "linux" is incompatible with this module.
info "windows-process-tree@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".
warning " > gulp-tsb@4.0.6" has incorrect peer dependency "typescript@^3.0.0".
[4/4] Building fresh packages...
[6/14] â¡€ nsfw
[7/14] â¡€ spdlog
[3/14] â¡€ native-keymap
[9/14] â¡€ vscode-sqlite3
error /root/vscode_web/vscode/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /root/vscode_web/vscode/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.22.1 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/vscode_web/vscode/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/11.4.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/11.4.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/11.4.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/vscode_web/vscode/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
make: Entering directory `/root/vscode_web/vscode/node_modules/native-keymap/build'
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/keymapping/src/string_conversion.o
  CXX(target) Release/obj.target/keymapping/src/keymapping.o
In file included from /root/.cache/node-gyp/11.4.2/include/node/v8.h:30:0,
                 from /root/.cache/node-gyp/11.4.2/include/node/node.h:67,
                 from ../src/keymapping.cc:6:
/root/.cache/node-gyp/11.4.2/include/node/v8-internal.h: In function â€˜void v8::internal::PerformCastCheck(T*)â€™:
/root/.cache/node-gyp/11.4.2/include/node/v8-internal.h:418:33: error: â€˜remove_cv_tâ€™ is not a member of â€˜stdâ€™
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                 ^
/root/.cache/node-gyp/11.4.2/include/node/v8-internal.h:418:33: error: â€˜remove_cv_tâ€™ is not a member of â€˜stdâ€™
/root/.cache/node-gyp/11.4.2/include/node/v8-internal.h:418:50: error: template argument 2 is invalid
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                                  ^
/root/.cache/node-gyp/11.4.2/include/node/v8-internal.h:418:61: error: â€˜::Performâ€™ has not been declared
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                                             ^
In file included from /root/.cache/node-gyp/11.4.2/include/node/node.h:67:0,
                 from ../src/keymapping.cc:6:
/root/.cache/node-gyp/11.4.2/include/node/v8.h: At global scope:
/root/.cache/node-gyp/11.4.2/include/node/v8.h:1658:58: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
                                 Local<Value> export_value);
                                                          ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:1840:74: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
     StreamedSource(ExternalSourceStream* source_stream, Encoding encoding);
                                                                          ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:3121:21: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   bool IsExternal() const;
                     ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:3437:23: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   Local<Value> Name() const { return Description(); }
                       ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5255:76: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                            ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5302:21: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   bool IsExternal() const;
                     ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5329:24: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   Contents Externalize();
                        ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5339:70: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void Externalize(const std::shared_ptr<BackingStore>& backing_store);
                                                                      ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5350:24: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   Contents GetContents();
                        ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5738:76: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                            ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5787:76: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                            ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5796:21: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   bool IsExternal() const;
                     ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5812:24: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   Contents Externalize();
                        ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5822:70: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void Externalize(const std::shared_ptr<BackingStore>& backing_store);
                                                                      ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:5837:24: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   Contents GetContents();
                        ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7182:28: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   size_t code_range_size() const { return code_range_size_ / kMB; }
                            ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7184:46: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void set_code_range_size(size_t limit_in_mb) {
                                              ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7188:38: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   size_t max_semi_space_size_in_kb() const;
                                      ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7190:56: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void set_max_semi_space_size_in_kb(size_t limit_in_kb);
                                                        ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7192:31: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   size_t max_old_space_size() const { return max_old_generation_size_ / kMB; }
                               ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7194:49: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void set_max_old_space_size(size_t limit_in_mb) {
                                                 ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7198:31: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   size_t max_zone_pool_size() const { return max_zone_pool_size_; }
                               ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7200:43: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void set_max_zone_pool_size(size_t bytes) { max_zone_pool_size_ = bytes; }
                                           ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:7384:53: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
 typedef void (*MicrotasksCompletedCallback)(Isolate*);
                                                     ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:8791:59: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
                                     MeasureMemoryMode mode);
                                                           ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:8854:36: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   Local<Context> GetEnteredContext();
                                    ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:9138:22: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void RunMicrotasks() { PerformMicrotaskCheckpoint(); }
                      ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:9182:75: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                           ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:9190:78: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                              ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:9430:54: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
       AllowCodeGenerationFromStringsCallback callback);
                                                      ^
/root/.cache/node-gyp/11.4.2/include/node/v8.h:9790:75: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   static bool TryHandleSignal(int signal_number, void* info, void* context);
                                                                           ^
In file included from /root/.cache/node-gyp/11.4.2/include/node/node.h:72:0,
                 from ../src/keymapping.cc:6:
/root/.cache/node-gyp/11.4.2/include/node/v8-platform.h:251:38: warning: â€˜deprecatedâ€™ attribute directive ignored [-Wattributes]
   virtual size_t GetMaxConcurrency() const { return 0; }
                                      ^
make: *** [Release/obj.target/keymapping/src/keymapping.o] Error 1
make: Leaving directory `/root/vscode_web/vscode/node_modules/native-keymap/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 3.10.0-1160.11.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/vscode_web/vscode/node_modules/native-keymap




^C
[root@VM-0-7-centos vscode]# pwd
/root/vscode_web/vscode
[root@VM-0-7-centos vscode]# ls
build            cgmanifest.json  extensions   LICENSE.txt   package.json       product.json  remote     scripts      src   ThirdPartyNotices.txt  yarn-error.log
cglicenses.json  CONTRIBUTING.md  gulpfile.js  node_modules  package-lock.json  README.md     resources  SECURITY.md  test  tsfmt.json             yarn.lock
[root@VM-0-7-centos vscode]#
