### ISSUE TITLE
Build Error: vscode-sqlite3

### ISSUE THREAD

**Issue by KagaJiankui** [microsoft/vscode#121307]
- VS Code Version: Code-OSS 1.55.2
- OS Version: Windows 10 20H2

Steps to Reproduce:
1.Download the source code ZIP file and build in the source directory with Powershell:
```bash
> yarn
```
2.Error output:
```bash
error E:\VSCode-Web\node_modules\vscode-sqlite3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: E:\VSCode-Web\node_modules\vscode-sqlite3
Output:
E:\VSCode-Web\node_modules\vscode-sqlite3>if not defined npm_config_node_gyp (node "D:\Node.js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "E:\nodejs\nodejs_modules\node_modules\npm\global_modules\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@14.3.0 | win32 | x64
gyp info find Python using Python version 3.8.8 found at "D:\Anaconda\python.exe"
gyp info find VS using VS2019 (16.9.31205.134) found at:
gyp info find VS "D:\Visual Studio\2019\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn D:\Anaconda\python.exe
gyp info spawn args [
gyp info spawn args   'E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\VSCode-Web\\node_modules\\vscode-sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\desol\\AppData\\Local\\node-gyp\\Cache\\11.4.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\desol\\AppData\\Local\\node-gyp\\Cache\\11.4.2',
gyp info spawn args   '-Dnode_gyp_dir=E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\desol\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\11.4.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\VSCode-Web\\node_modules\\vscode-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\VSCode-Web\\node_modules\\vscode-sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn D:\Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln', 
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo', 
gyp info spawn args   '/p:Configuration=Release;Platform=x64' 
gyp info spawn args ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  unpack_sqlite_dep
  python: can't open file './extract.py': [Errno 2] No such file or directory
D:\Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: “..\..\deps\sqlite-autoconf-3280000.tar.gz”的自定义生成已退出，代码为 2。 [E:\VSCode-Web\node_modules\vscode-sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `D:\Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nodejs\nodejs_modules\node_modules\npm\global_modules\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "D:\\Node.js\\node.exe" "E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\VSCode-Web\node_modules\vscode-sqlite3
```

The build of vscode-sqlite3 fails with output:
```
python: can't open file './extract.py': [Errno 2] No such file or directory
```

But there is no non-Unicode characters in my source directory:
```
E:\VSCode-Web\node_modules\vscode-sqlite3\deps
```
and my python version is 3.8.8 with Anaconda, which is already in path.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by KagaJiankui** [comment]
Use `node-gyp` to build the `vscode-sqlite3` independently in its directory produces identical error:
```bash
cd E:\VSCode-Web\node_modules\vscode-sqlite3
node-gyp rebuild
```
Error is identical to the full build by yarn:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@14.3.0 | win32 | x64
gyp info find Python using Python version 3.8.8 found at "D:\Anaconda\python.exe"
gyp http GET https://nodejs.org/download/release/v14.3.0/node-v14.3.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.3.0/node-v14.3.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.3.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.3.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v14.3.0/win-arm64/node.lib
gyp http GET https://nodejs.org/download/release/v14.3.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.3.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.3.0/win-x64/node.lib
gyp http 404 https://nodejs.org/download/release/v14.3.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.3.0/win-x86/node.lib
gyp info find VS using VS2019 (16.9.31205.134) found at:
gyp info find VS "D:\Visual Studio\2019\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn D:\Anaconda\python.exe
gyp info spawn args [
gyp info spawn args   'E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\VSCode-Web\\node_modules\\vscode-sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\desol\\AppData\\Local\\node-gyp\\Cache\\14.3.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\desol\\AppData\\Local\\node-gyp\\Cache\\14.3.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\desol\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.3.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\VSCode-Web\\node_modules\\vscode-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\VSCode-Web\\node_modules\\vscode-sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn D:\Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  unpack_sqlite_dep
  python: can't open file './extract.py': [Errno 2] No such file or directory
D:\Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: “..\..\
deps\sqlite-autoconf-3280000.tar.gz”的自定义生成已退出，代码为 2。 [E:\VSCode-Web\node_modules\vscode-sqlite3\build\deps\action_befor
e_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `D:\Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nodejs\nodejs_modules\node_modules\npm\global_modules\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "D:\\Node.js\\node.exe" "E:\\nodejs\\nodejs_modules\\node_modules\\npm\\global_modules\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\VSCode-Web\node_modules\vscode-sqlite3
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v8.0.0
gyp ERR! not ok
```
Maybe this issue is related to the **cwd** since the return cwd is `E:\VSCode-Web\node_modules\vscode-sqlite3` rather than `E:\VSCode-Web\node_modules\vscode-sqlite3\deps` that contains the `extract.py` file.
