### ISSUE TITLE
Locally built VS Code freezes on launch

### ISSUE THREAD

**Issue by hantatsang** [microsoft/vscode#121810]
- VS Code Version: The latest `main` branch
- OS Version: Windows 10
- Node: 14.14.0
- Yarn: 1.22.10

Steps to Reproduce:

1. Clone `vscode` repo
2. Run `yarn`
3. Run `yarn watch` or `yarn watchd`
4. Launch VSCode by running `scripts\code` or by using _"Launch VS Code"_ task in a VSCode instance that's opening `vscode` repo
5. Observe launched VSCode starts and freeze

![2021-04-21 21_17_31-](https://user-images.githubusercontent.com/11912225/115545694-70e2f800-a2e7-11eb-869d-352a850d513c.png)

Tried on a different Windows 10 machine and the issue still persists.

Does this issue occur when all extensions are disabled?: Yes

## `scripts\code` log:

<details>
  <summary>Click to expand:</summary>
  
```log
.\scripts\code
yarn run v1.22.10
$ node build/lib/electron
Done in 0.44s.
[21:15:47] Syncronizing built-in extensions...
[21:15:47] You can manage built-in extensions with the --builtin flag
[21:15:47] [marketplace] ms-vscode.node-debug@1.44.26 ✔︎
[21:15:47] [marketplace] ms-vscode.node-debug2@1.42.6 ✔︎
[21:15:47] [marketplace] ms-vscode.references-view@0.0.78 ✔︎
[21:15:47] [marketplace] ms-vscode.js-debug-companion@1.0.11 ✔︎
[21:15:47] [marketplace] ms-vscode.js-debug@1.56.0 ✔︎
[21:15:47] [marketplace] ms-vscode.vscode-js-profile-table@0.0.16 ✔︎
[21:15:47] [marketplace] ms-vscode.remotehub@0.1.2 ✔︎
[21:15:47] [marketplace] ms-vscode.remotehub@0.1.2 ✔︎

Error: The module '\\?\S:\microsoft\vscode\node_modules\spdlog\build\Release\spdlog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (S:\microsoft\vscode\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (S:\microsoft\vscode\node_modules\spdlog\index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (S:\microsoft\vscode\out\vs\loader.js:1022:24)
    at NodeScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:816:39)
    at OnlyOnceScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:607:32)
    at loadNextPath (S:\microsoft\vscode\out\vs\loader.js:1628:41)
    at Object.errorback (S:\microsoft\vscode\out\vs\loader.js:1636:25)
    at OnlyOnceScriptLoader.triggerErrorback (S:\microsoft\vscode\out\vs\loader.js:620:36)
    at S:\microsoft\vscode\out\vs\loader.js:607:151
    at NodeScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:819:21)
    at OnlyOnceScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:607:32)
    at loadNextPath (S:\microsoft\vscode\out\vs\loader.js:1628:41)
    at ModuleManager._loadModule (S:\microsoft\vscode\out\vs\loader.js:1640:13)
    at ModuleManager._resolve (S:\microsoft\vscode\out\vs\loader.js:1725:26)
    at ModuleManager.defineModule (S:\microsoft\vscode\out\vs\loader.js:1372:18)
    at ModuleManager._relativeRequire (S:\microsoft\vscode\out\vs\loader.js:1406:18)
    at result (S:\microsoft\vscode\out\vs\loader.js:1580:30)
    at _spdlog (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:12:74)
    at new Promise (<anonymous>)
    at createSpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:12:35)
    at SpdLogLogger._createSpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:67:20)
    at new SpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:57:48)
    at S:\microsoft\vscode\out\vs\code\electron-main\main.js:52:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CodeMain.startup (S:\microsoft\vscode\out\vs\code\electron-main\main.js:43:17) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous2===' ]
}
[main 2021-04-21T11:15:48.603Z] Error: The module '\\?\S:\microsoft\vscode\node_modules\windows-mutex\build\Release\CreateMutex.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (S:\microsoft\vscode\node_modules\windows-mutex\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (S:\microsoft\vscode\node_modules\windows-mutex\index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.nodeRequire [as __$__nodeRequire] (S:\microsoft\vscode\out\vs\loader.js:1022:24)
    at CodeApplication.afterWindowOpen (S:\microsoft\vscode\out\vs\code\electron-main\app.js:740:50)
    at S:\microsoft\vscode\out\vs\code\electron-main\app.js:342:69
    at InstantiationService.invokeFunction (S:\microsoft\vscode\out\vs\platform\instantiation\common\instantiationService.js:45:24)
    at CodeApplication.startup (S:\microsoft\vscode\out\vs\code\electron-main\app.js:342:37)
    at async CodeMain.startup (S:\microsoft\vscode\out\vs\code\electron-main\main.js:43:17)
[22716:0421/211548.787:INFO:CONSOLE(33)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: electron/js2c/renderer_init.js (33)
Error: The module '\\?\S:\microsoft\vscode\node_modules\spdlog\build\Release\spdlog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (S:\microsoft\vscode\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (S:\microsoft\vscode\node_modules\spdlog\index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (S:\microsoft\vscode\out\vs\loader.js:1022:24)
    at NodeScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:816:39)
    at OnlyOnceScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:607:32)
    at loadNextPath (S:\microsoft\vscode\out\vs\loader.js:1628:41)
    at Object.errorback (S:\microsoft\vscode\out\vs\loader.js:1636:25)
    at OnlyOnceScriptLoader.triggerErrorback (S:\microsoft\vscode\out\vs\loader.js:620:36)
    at S:\microsoft\vscode\out\vs\loader.js:607:151
    at NodeScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:819:21)
    at OnlyOnceScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:607:32)
    at loadNextPath (S:\microsoft\vscode\out\vs\loader.js:1628:41)
    at ModuleManager._loadModule (S:\microsoft\vscode\out\vs\loader.js:1640:13)
    at ModuleManager._resolve (S:\microsoft\vscode\out\vs\loader.js:1725:26)
    at ModuleManager.defineModule (S:\microsoft\vscode\out\vs\loader.js:1372:18)
    at ModuleManager._relativeRequire (S:\microsoft\vscode\out\vs\loader.js:1406:18)
    at result (S:\microsoft\vscode\out\vs\loader.js:1580:30)
    at _spdlog (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:12:74)
    at new Promise (<anonymous>)
    at createSpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:12:35)
    at SpdLogLogger._createSpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:67:20)
    at new SpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:57:48)
    at S:\microsoft\vscode\out\vs\code\electron-main\main.js:52:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CodeMain.startup (S:\microsoft\vscode\out\vs\code\electron-main\main.js:43:17) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous2===' ]
}
[22716:0421/211550.521:INFO:CONSOLE(266)] "%c[Extension Host] %cdebugger listening on port 5870 color: blue color:", source: file:///D:/code/fork/microsoft/vscode/out/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.js (266)
Error: The module '\\?\S:\microsoft\vscode\node_modules\spdlog\build\Release\spdlog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (S:\microsoft\vscode\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (S:\microsoft\vscode\node_modules\spdlog\index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (S:\microsoft\vscode\out\vs\loader.js:1022:24)
    at NodeScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:816:39)
    at OnlyOnceScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:607:32)
    at loadNextPath (S:\microsoft\vscode\out\vs\loader.js:1628:41)
    at Object.errorback (S:\microsoft\vscode\out\vs\loader.js:1636:25)
    at OnlyOnceScriptLoader.triggerErrorback (S:\microsoft\vscode\out\vs\loader.js:620:36)
    at S:\microsoft\vscode\out\vs\loader.js:607:151
    at NodeScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:819:21)
    at OnlyOnceScriptLoader.load (S:\microsoft\vscode\out\vs\loader.js:607:32)
    at loadNextPath (S:\microsoft\vscode\out\vs\loader.js:1628:41)
    at ModuleManager._loadModule (S:\microsoft\vscode\out\vs\loader.js:1640:13)
    at ModuleManager._resolve (S:\microsoft\vscode\out\vs\loader.js:1725:26)
    at ModuleManager.defineModule (S:\microsoft\vscode\out\vs\loader.js:1372:18)
    at ModuleManager._relativeRequire (S:\microsoft\vscode\out\vs\loader.js:1406:18)
    at result (S:\microsoft\vscode\out\vs\loader.js:1580:30)
    at _spdlog (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:12:74)
    at new Promise (<anonymous>)
    at createSpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:12:35)
    at SpdLogLogger._createSpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:67:20)
    at new SpdLogLogger (S:\microsoft\vscode\out\vs\platform\log\node\spdlogLog.js:57:48)
    at S:\microsoft\vscode\out\vs\code\electron-main\main.js:52:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CodeMain.startup (S:\microsoft\vscode\out\vs\code\electron-main\main.js:43:17) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous2===' ]
}
```
</details>

**Comment by leemun1** [comment]
I think I ran into this a couple days ago too.

Below are the steps I took to resolve it:

#### 1. Checkout the latest main branch
```
cd vscode
git checkout main
git pull https://github.com/microsoft/vscode.git main
```

#### 2. Remove all installed dependencies, if any
```
rm -rf node_modules
```

#### 3. Re-install all dependencies
```
yarn
```

#### 4. Build
```
yarn watch
```

#### 5. Once build is complete, run it
```
# windows
.\scripts\code.bat

# mac
./scripts/code.sh
```

**Comment by hantatsang** [comment]
Thanks vm @leemun1 . That fixes it!
