### ISSUE TITLE
`yo code` fails to run

### ISSUE THREAD

**Issue by camerontbelt** [microsoft/vscode#121961]
- VS Code Version: 1.55.2
- OS Version: Windows_NT x64 10.0.18363

Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Follow this guide https://code.visualstudio.com/api/get-started/your-first-extension
2. Open a terminal in VS Code
3. Type `yo code`
4. I get the following errors
`Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
        at new Errlop (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\errlop\edition-es5\index.js:61:18)
        at Object.errtion (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\util.js:23:14)
        at isCompatibleEngines (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:183:19)
        at isCompatibleEdition (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:250:10)
        at determineEdition (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:287:4)
        at determineEdition (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:312:12)
        at solicitEdition (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:350:16)
        at Object.requirePackage (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\editions\edition-es5\index.js:364:9)
        at Object.<anonymous> (C:\Users\cbelt\AppData\Roaming\npm\node_modules\yo\node_modules\istextorbinary\index.cjs:4:38)
        at Module._compile (node:internal/modules/cjs/loader:1108:14) {
      klass: [Function: Errlop] {
        create: [Function (anonymous)],
        isErrlop: [Function (anonymous)],
        ensure: [Function (anonymous)]
      },
      parent: undefined,
      ancestors: [],
      orphanStack: 'Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment\n' +
        '    at new Errlop (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\errlop\\edition-es5\\index.js:61:18)\n' +
        '    at Object.errtion (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\editions\\edition-es5\\util.js:23:14)\n' +
        '    at isCompatibleEngines (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\editions\\edition-es5\\index.js:183:19)\n' +
        '    at isCompatibleEdition (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\editions\\edition-es5\\index.js:250:10)\n' +
        '    at determineEdition (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\editions\\edition-es5\\index.js:287:4)\n' +
        '    at determineEdition (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\editions\\edition-es5\\index.js:312:12)\n' +
        '    at solicitEdition (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\editions\\edition-es5\\index.js:350:16)\n' +
        '    at Object.requirePackage (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\editions\\edition-es5\\index.js:364:9)\n' +
        '    at Object.<anonymous> (C:\\Users\\cbelt\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\istextorbinary\\index.cjs:4:38)\n' +
        '    at Module._compile (node:internal/modules/cjs/loader:1108:14)',
      code: 'editions-autoloader-invalid-engines'
    }
  ],`

I get so many of these that it actually cuts off the top part of the terminal.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by camerontbelt** [comment]
This does not work with version 16 of nodejs. I uninstalled v16 and installed v14, this resolved the issue.
