### ISSUE TITLE
ERR Cannot read property 'apiNotebook' of undefined:

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121921]
Seeing this when reloading with a notebook open

```
 ERR Cannot read property 'apiNotebook' of undefined: TypeError: Cannot read property 'apiNotebook' of undefined
	at ExtHostNotebookKernels.$acceptSelection (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostNotebookKernels.js:165:98)
	at RPCProtocol._doInvokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
	at RPCProtocol._invokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
	at RPCProtocol._receiveRequest (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
	at RPCProtocol._receiveOneMessage (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
	at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
	at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
	at BufferedEmitter.fire (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
	at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:146:41
	at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
	at BufferedEmitter.fire (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
	at PersistentProtocol._receiveMessage (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
	at /Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:510:83
	at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:479:38)
	at ProtocolReader.acceptChunk (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
	at /Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:158:61
	at Socket.listener (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by jrieken** [comment]
This was some in-between state. There are two listeners for notebooks being added and the one that sync's the extension host was first...
