### ISSUE TITLE
vscode server cli: extension is installed and enabled when installed by server cli

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122172]
```
1 failing
  1) vscode server cli
       extension is installed and enabled when installed by server cli:
     AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(vscode.extensions.getExtension(extension))

      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/extensions.test.ts:22:10)
      at processImmediate (internal/timers.js:461:21)

```

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=115573&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&s=d26761af-f5e8-5e3e-3ed3-ef1ee2069094&t=07088cf7-fede-5f74-0d50-155edd53af7d&l=432

**Comment by sandy081** [comment]
I do not see any this is failing recently. Would like to wait for next instance.
