### ISSUE TITLE
can't install jupyter ext

### ISSUE THREAD

**Issue by almohress** [microsoft/vscode#122247]
I got this error while installing Jupyter ext on vscode:
```
[2021-04-26 18:47:03.665] [renderer1] [error] too many bytes in the stream. expected 2488828. got at least 2489041: extracting: too many bytes in the stream. expected 2488828. got at least 2489041
    at y.extractAtLocation (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:203893)
    at async y.extractUserExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:200880)
    at async H.extractAndInstall (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:218647)
    at async H.doInstallFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:215184)
```
vscode recommends to install it manually. 
I also tried that, but another error occurred:
```
Command 'Extensions: Install from VSIX...' resulted in an error (Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.55.2'.)
```

**Comment by sandy081** [comment]
If you downloaded the vsix from Marketplace then you would have downloaded the latest version which is not compatible with stable version of VS Code.

May I know when installing from extension UI, how often are you hitting this issue? Is it reproducbile consistently?
