### ISSUE TITLE
Error: Can't apply edits to unknown notebook model: fake-fs:/lquddc.vsctestnb

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122271]
Running integration tests out of sources, eventually:

```
Error: Can't apply edits to unknown notebook model: fake-fs:/lquddc.vsctestnb
    at MainThreadNotebookDocuments.$applyEdits (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadNotebookDocuments.js:108:23)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:510:83
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:158:61
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by jrieken** [comment]
This comes out of cell execution, it's this test: ['document execute command takes arguments'](https://github.com/microsoft/vscode/blob/ed52d777ef62881dcaa917e140b8c6a98e80eb41/extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts#L708-L708), but I am not sure why...

**Comment by roblourens** [comment]
It's not breaking the test, is it? I think for some reason, I can't wait until the extension is done applying edits, so we might close the notebook first, but it seems ok.

**Comment by bpasero** [comment]
> It's not breaking the test, is it?

No, but we have a "no stacktraces in tests" policy.

**Comment by jrieken** [comment]
> No, but we have a "no stacktraces in tests" policy.

Well, I don't think there is team consensus on that

**Comment by roblourens** [comment]
This seems like something that could happen during normal usage of a notebook so I will do something about it.

**Comment by jrieken** [comment]
> so we might close the notebook first, but it seems ok.

Was thinking about that. Your test doesn't really open the notebook. It just uses the command to open a notebook editor but once that editor closes the notebook document is being nuked immediately. You can keep it alive when using `openNotebookDocument`

**Comment by roblourens** [comment]
I think the execution task should have a reference to the document

**Comment by roblourens** [comment]
This shouldn't happen anymore after January refactorings
