### ISSUE TITLE
Linux web smoketest timeout

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#122444]
Testing #122184

When running the web smoketests on Linux, they all pass but I get the following timeout 

```
** Timeout!
page.evaluate: Evaluation failed: Error: Active element not found. Current active element is 'HTML > BODY.linux.web > DIV.monaco-workbench.linux.web.chromium.fullscreen.vs.vscode-theme-defaults-themes-light_plus-json.file-icons-enabled > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.horizontal > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical.separator-border > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV.editor-instance > DIV.monaco-editor.no-user-select.showUnused.showDeprecated.vs.focused > DIV.overflow-guard > TEXTAREA.inputarea.monaco-mouse-cursor-text'. Looking for .quick-input-widget .quick-input-box input
    at O.isActiveElement (http://localhost:8000/static/out/vs/workbench/workbench.web.api.js:570:74301)
    at eval (eval at evaluate (:300:31), <anonymous>:1:15)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:300:31)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Connection.sendMessageToServer (/home/parallels/vscode/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/home/parallels/vscode/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /home/parallels/vscode/node_modules/playwright/lib/client/frame.js:157:48
    at Frame._wrapApiCall (/home/parallels/vscode/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.evaluate (/home/parallels/vscode/node_modules/playwright/lib/client/frame.js:156:21)
    at /home/parallels/vscode/node_modules/playwright/lib/client/page.js:344:60
    at Page._attributeToPage (/home/parallels/vscode/node_modules/playwright/lib/client/page.js:205:20)
    at Page.evaluate (/home/parallels/vscode/node_modules/playwright/lib/client/page.js:344:21)
    at Proxy.isActiveElement (/home/parallels/vscode/test/automation/out/playwrightDriver.js:72:55)
    at Proxy.<anonymous> (/home/parallels/vscode/test/automation/out/code.js:208:39)

```

**Comment by alexdima** [comment]
This looks very similar to https://github.com/microsoft/vscode/issues/122317

**Comment by JacksonKearl** [comment]
It doesn't appear to be the case that the welcome page is stealing focus here, the focus is in a monaco editor, I'll look into it more.

**Comment by alexdima** [comment]
@lramos15 The smoketest did not fail for me on Linux. Could you please let us know which test was failing? Then we can track down the test owner and ask them to investigate.

**Comment by lramos15** [comment]
@alexdima It says all the test pass, but still prints that giant timeout to console so I just opened an issue as I feel we might be missing something if there is a timeout. The timeout gets printed and then right after we print 
```
        ✓ install and enable vscode-smoketest-check extension
Server stdout: [08:08:10] [::1][137d118c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.

```

**Comment by alexdima** [comment]
cc @sandy081 ⬆️

**Comment by sandy081** [comment]
If it is about 

```
Server stdout: [08:08:10] [::1][137d118c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
```

It seems server is printing this info when connection is disposed. Seems legitimate.

**Comment by alexdima** [comment]
@sandy081 I don't think this issue is about the "The client has disconnected gracefully" message, but about this error:

```
page.evaluate: Evaluation failed: Error: Active element not found. Current active element is 'HTML > BODY.linux.web > DIV.monaco-workbench.linux.web.chromium.fullscreen.vs.vscode-theme-defaults-themes-light_plus-json.file-icons-enabled > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.horizontal > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical.separator-border > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV.editor-instance > DIV.monaco-editor.no-user-select.showUnused.showDeprecated.vs.focused > DIV.overflow-guard > TEXTAREA.inputarea.monaco-mouse-cursor-text'. Looking for .quick-input-widget .quick-input-box input
    at O.isActiveElement (http://localhost:8000/static/out/vs/workbench/workbench.web.api.js:570:74301)
    at eval (eval at evaluate (:300:31), <anonymous>:1:15)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:300:31)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Connection.sendMessageToServer (/home/parallels/vscode/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/home/parallels/vscode/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /home/parallels/vscode/node_modules/playwright/lib/client/frame.js:157:48
    at Frame._wrapApiCall (/home/parallels/vscode/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.evaluate (/home/parallels/vscode/node_modules/playwright/lib/client/frame.js:156:21)
    at /home/parallels/vscode/node_modules/playwright/lib/client/page.js:344:60
    at Page._attributeToPage (/home/parallels/vscode/node_modules/playwright/lib/client/page.js:205:20)
    at Page.evaluate (/home/parallels/vscode/node_modules/playwright/lib/client/page.js:344:21)
    at Proxy.isActiveElement (/home/parallels/vscode/test/automation/out/playwrightDriver.js:72:55)
    at Proxy.<anonymous> (/home/parallels/vscode/test/automation/out/code.js:208:39)
```

Since there are no test failures, it is not clear which test is causing this error. But the immediately next test after the error is :

```
✓ install and enable vscode-smoketest-check extension
```

So the assumption is that the error message might come from this test.

**Comment by JacksonKearl** [comment]
I'm not sure why I'm assigned here, but going to move out to May as it does not seem to be causing any actual failures. 

cc @alexdima and @TylerLeonhardt as the owners of the two components listed in the error message (`monaco-editor  textarea` and `.quick-input-widget input`)

**Comment by alexdima** [comment]
@joaomoreno Do you have any idea what to do here? No test failures, yet @lramos15 sees assertion errors in the output.

**Comment by joaomoreno** [comment]
I'm not going to jump on this since we're trying to spread responsibility of the smoketest across the team. @lramos15 please investigate and let me know if I can help in some specific way.

**Comment by lramos15** [comment]
Running these smoketests for the 1.56.2 release I didn't see this error. Very strange. Will close for now and keep an eye out.
