### ISSUE TITLE
terminalTabsWidget: Cannot read property 'instanceId' of null

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122662]
I do not have steps sorry. However I was playing around with the terminal tabs widget and after some time I noticed the following exception in the console:

```

Cannot read property 'instanceId' of null: TypeError: Cannot read property 'instanceId' of null
    at Object.getId (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsWidget.js:32:35)
    at Trait.onDidModelSplice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:776:50)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:949:36
    at EventBufferer.bufferEvents (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:631:23)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:947:36
    at file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:52:86
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:479:38)
    at IndexTreeModel.spliceSimple (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:165:31)
    at IndexTreeModel.splice (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:62:22)
    at ObjectTreeModel._setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:68:24)
    at ObjectTreeModel.setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:31:18)
    at TerminalTabsWidget.setChildren (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/objectTree.js:21:24)
    at TerminalTabsWidget._render (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsWidget.js:115:18)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsWidget.js:47:65
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:479:38)
    at TerminalService.createTerminal (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:879:38)
    at Object.run (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/terminal/browser/terminalActions.js:1491:52)
    at handler (file:///Users/isidor/Development/vscode/out/vs/platform/actions/common/actions.js:361:52)
    at InstantiationService.invokeFunction (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:45:24)
    at CommandService._tryExecuteCommand (file:///Users/isidor/Development/vscode/out/vs/workbench/services/commands/common/commandService.js:74:59)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/commands/common/commandService.js:64:47
    at async ActionRunner.runAction (file:///Users/isidor/Development/vscode/out/vs/base/common/actions.js:115:13)
    at async ActionRunner.run (file:///Users/isidor/Development/vscode/out/vs/base/common/actions.js:107:17)

```

**Comment by Tyriar** [comment]
I have hit this before as well, at which point the terminal was broken completely. I think I was messing with moving location left/right at the time.

**Comment by isidorn** [comment]
I did not do left / right. But I might have hid it and shown it again

**Comment by meganrogge** [comment]
fixed https://github.com/microsoft/vscode/commit/a7dcfd1e2c3b970c44e124a68aa7666c0b71e488

**Comment by isidorn** [comment]
Let me assign to this milestone...

**Comment by isidorn** [comment]
Did not see this today, adding verified. If I see again I will let you know
