### ISSUE TITLE
textModel.getMode is not a function

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12268]
* run the integration tests and notice the error below showing on the console

```
textModel.getMode is not a function: TypeError: textModel.getMode is not a function
    at EditorStatus.onModeChange (file:////Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorStatus.js:424:42)
    at EditorStatus.onEditorsChanged (file:////Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorStatus.js:384:18)
    at file:////Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorStatus.js:241:84
    at CallbackList.invoke (file:////Users/jrieken/Code/vscode/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (file:////Users/jrieken/Code/vscode/out/vs/base/common/event.js:88:40)
    at file:////Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:306:45
    at Object.notifySuccess [as _notify] (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)", source: file:////Users/jrieken/Code/vscode/out/vs/workbench/electron-browser/shell.js (243)
```

**Comment by bpasero** [comment]
Wth, still happens...

**Comment by jrieken** [comment]
No, I don't see [that](https://github.com/Microsoft/vscode/issues/12268#issuecomment-248011339). Did you interact with the shell window during test running by any chance?

**Comment by bpasero** [comment]
@jrieken cannot reproduce anymore 👍

**Comment by ramya-rao-a** [comment]
Marking as verified as per https://github.com/Microsoft/vscode/issues/12268#issuecomment-248234252
