### ISSUE TITLE
TS Server fatal error:  No Project.

### ISSUE THREAD

**Issue by tgyou** [microsoft/vscode#122615]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.3-pnpify

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: No Project.
    at Object.ThrowNoProject (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:152312:23)
    at ScriptInfo.getDefaultProject (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:153136:46)
    at ProjectService.telemetryOnOpenFile (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:158134:42)
    at /Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:158216:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:158216:37)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:159280:46)
    at /Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:161164:88
    at IOSession.Session.executeWithRequestId (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:161155:28)
    at IOSession.Session.executeCommand (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:161164:33)
    at IOSession.Session.onMessage (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:161190:35)
    at IOSession.onMessage (/Users/tgyou/Sites/pay-mini-web/.yarn/sdks/typescript/lib/tsserver.js:104:32)
    at Interface.<anonymous> (/Users/tgyou/Sites/pay-mini-web/.yarn/cache/typescript-patch-5ca75e76e6-a8956044aa.zip/node_modules/typescript/lib/tsserver.js:163851:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.56.0-insider (19cda32aafccb88db45622e7ae9be90cb71c9744, 2021-04-27T17:46:45.458Z)
OS version: Darwin arm64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 737429c9-842b-4b70-a3cb-8cf0332867c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-database|baj|2.2.3
dart-code|Dar|3.21.1
vscode-eslint|dba|2.1.20
javascript-ejs-support|Dig|1.3.1
fileheadercomment|doi|0.0.5
eslint-disable-snippets|drK|1.3.0
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
url-encode|fle|1.1.0
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
swift|Kas|0.2.0
vscode-gist|ken|3.0.3
jsdoc|lll|1.0.3
vscode-language-babel|mgm|0.0.31
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.794159387
remote-containers|ms-|0.172.0
vscode-typescript-next|ms-|4.3.20210428
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
docthis|oou|0.8.2
swift-playgrounds|pie|0.1.1
material-icon-theme|PKi|4.6.0
ruby|reb|0.28.1
addDocComments|ste|0.0.8
ayu|tea|0.20.1
babelrc|wad|1.0.0
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255cf:30295351
vscgsv2:30286872

```

</details>

**Comment by tgyou** [comment]
The issue was not reproduced when VSCode was restarted.
