### ISSUE TITLE
Terminal tabs: Cannot read property 'instanceId' of null

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122608]
Issue Type: <b>Bug</b>

1. On MacOS
1. Right click in terminal tabs to create a new terminal from a profile
1. Select `sh` from the list

**Bug**
The terminal opens but in the dev tools I see:

```
Cannot read property 'instanceId' of null: TypeError: Cannot read property 'instanceId' of null
    at Object.getId (file:///Users/matb/projects/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsWidget.js:32:35)
    at Trait.onDidModelSplice (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:776:50)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:949:36
    at EventBufferer.bufferEvents (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:631:23)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:947:36
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:52:86
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:479:38)
    at IndexTreeModel.spliceSimple (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:165:31)
    at IndexTreeModel.splice (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:62:22)
    at ObjectTreeModel._setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:68:24)
    at ObjectTreeModel.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:31:18)
    at TerminalTabsWidget.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTree.js:21:24)
    at TerminalTabsWidget._render (file:///Users/matb/projects/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsWidget.js:115:18)
    at file:///Users/matb/projects/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsWidget.js:47:65
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:479:38)
    at TerminalService.createTerminal (file:///Users/matb/projects/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:879:38)
    at TerminalService.showProfileQuickPick (file:///Users/matb/projects/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:769:37)
    at async Object.run (file:///Users/matb/projects/vscode/out/vs/workbench/contrib/terminal/browser/terminalActions.js:170:36)
    at async ActionRunner.runAction (file:///Users/matb/projects/vscode/out/vs/base/common/actions.js:115:13)
    at async ActionRunner.run (file:///Users/matb/projects/vscode/out/vs/base/common/actions.js:107:17)
    at async NativeContextMenuService.runAction (file:///Users/matb/projects/vscode/out/vs/workbench/services/contextmenu/electron-sandbox/contextmenuService.js:156:17)
```

VS Code version: Code - OSS Dev 1.56.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
docs-view|bie|0.0.9
vscode-eslint|dba|2.1.20
typescript-notebook|don|1.2.0
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.25.1
latex-workshop|Jam|8.17.0
svg|joc|1.4.5
template-string-converter|meg|0.4.7
git-graph|mhu|1.30.0
vscode-language-pack-de|MS-|1.55.2
vscode-dotnet-runtime|ms-|1.0.0
vscode-edge-devtools|ms-|1.1.7
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.770905982
remote-containers|ms-|0.170.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
azure-account|ms-|0.9.8
cpptools|ms-|1.3.1
hexeditor|ms-|1.5.0
vscode-github-issue-notebooks|ms-|0.0.82
vscode-markdown-notebook|ms-|0.0.18
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
shader-toy|ste|0.10.15

</details>

**Comment by meganrogge** [comment]
Perhaps just adding 

```
e?.instanceId
e?.title
```

here https://github.com/microsoft/vscode/blob/a8a1b0f6db12c7e1fd7d5b02d429f25a3eabc648/src/vs/workbench/contrib/terminal/browser/terminalTabsWidget.ts#L63-L67

would prevent this error from throwing?
