### ISSUE TITLE
Flaky notebook test: set outputs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122851]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=116579&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=b2ac4860-fb3b-5a51-42a7-7423ead0721b&l=363

```
1) Notebook API tests
       set outputs on interrupt:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=116584&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=357
```
  1 failing
  1) Notebook API tests
       set outputs on cancel:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  [
+   'my output'
-   'Canceled'
  ]
      + expected - actual

       [
      -  "my output"
      +  "Canceled"
       ]
      
      at D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\notebook.test.ts:819:11
      at withEvent (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\notebook.test.ts:57:2)
      at Context.<anonymous> (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\notebook.test.ts:812:3)
```

**Comment by jrieken** [comment]
Feeling lucky...  Closing because we are using more strict API now and there is more assertions that should tell us more about why/how this fails (if this fails again)
