### ISSUE TITLE
run vscode with black window in ubuntu14

### ISSUE THREAD

**Issue by vivisherlock** [microsoft/vscode#122997]
Hi, everyone.
When I start VS Code I get the freeze screen(not working and responding, but showing the welccome page). I try the one of solutions is to run VS code by "code --disable-gpu". 

it can't solve question by  https://github.com/Microsoft/vscode/issues/6379 or removing root authority by "cd ~/.config" & "sudo rm -rf ./Code/" as well.
i have found duplicates similar question but some don't solve yet(https://github.com/microsoft/vscode/issues/122201). some question aren't same ubuntu version. 

this is my ubuntu & vscode version
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty
vscode version 1.55.2

i post the info as many as possible. if it is necessary for more pls tell me ORZ.
---------INFO1---------

> 
INFO1: code --verbose
[main 2021-05-05T09:21:51.210Z] [uncaught exception in main]: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
[main 2021-05-05T09:21:51.210Z] Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at v (/usr/share/code/resources/app/out/vs/loader.js:4:694)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/vscode-sqlite3/lib/sqlite3.js:1:77)
    at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1248)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at t (/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1656)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/code/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/code/resources/app/out/vs/loader.js:3:10626)
    at /usr/share/code/resources/app/out/vs/loader.js:3:10332
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1673)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/code/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/code/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/code/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/code/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/code/resources/app/out/vs/loader.js:5:9420)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31711
    at new Promise (<anonymous>)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31691
    at new Promise (<anonymous>)
    at y.doConnect (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31671)
    at y.connect (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31117)
    at new y (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:28457)
    at m.doCreate (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:9829)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:8715
    at m.init (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:9057)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:12529
[main 2021-05-05T09:21:51.210Z] [uncaught exception in main]: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
[main 2021-05-05T09:21:51.210Z] Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at v (/usr/share/code/resources/app/out/vs/loader.js:4:694)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/vscode-sqlite3/lib/sqlite3.js:1:77)
    at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1248)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at t (/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1656)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/code/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/code/resources/app/out/vs/loader.js:3:10626)
    at /usr/share/code/resources/app/out/vs/loader.js:3:10332
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1673)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/code/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/code/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/code/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/code/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/code/resources/app/out/vs/loader.js:5:9420)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31711
    at new Promise (<anonymous>)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31691
    at new Promise (<anonymous>)
    at y.doConnect (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31671)
    at y.connect (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31117)
    at new y (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:28457)
    at m.doCreate (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:9829)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:8715
    at m.init (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:9057)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:12529
[main 2021-05-05T09:21:51.266Z] SharedProcess: IPC ready
[26232:0505/172151.275594:INFO:CONSOLE(26)] "Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (26)
[main 2021-05-05T09:21:51.276Z] Main->SharedProcess#connect: connection established
/usr/share/code/code: /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0: no version information available (required by /usr/share/code/code)
[26232:0505/172151.299262:INFO:CONSOLE(26)] "Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (26)
[26232:0505/172151.300748:INFO:CONSOLE(25)] "%cTRACE color: #888 sharedProcess configuration {"machineId":"697c19e2b96e3bd412decf8f5e12b9313864b03a9bb2e4f62499f17ef6671adc","windowId":2,"appRoot":"/usr/share/code/resources/app","nodeCachedDataDir":"/home/vivi/.config/Code/CachedData/3c4e3df9e89829dce27b7b5c24508306b151f30d","backupWorkspacesPath":"/home/vivi/.config/Code/Backups/workspaces.json","userEnv":{"VSCODE_IPC_HOOK":"/run/user/1000/vscode-10f03b6b-1.55.2-main.sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}"},"args":{"_":[],"diff":false,"add":false,"goto":false,"new-window":false,"reuse-window":false,"wait":false,"help":false,"list-extensions":false,"show-versions":false,"version":false,"verbose":true,"status":false,"prof-startup":false,"prof-v8-extensions":false,"disable-extensions":false,"disable-gpu":true,"telemetry":false,"debugRenderer":false,"logExtensionHostCommunication":false,"skip-release-notes":false,"disable-telemetry":false,"disable-updates":false,"disable-keytar":false,"disable-crash-reporter":false,"crash-reporter-id":"da42a552-ec4b-4fa2-8b4c-cfe2de23baec","skip-add-to-recently-opened":false,"unity-launch":false,"open-url":false,"file-write":false,"file-chmod":false,"driver-verbose":false,"force":false,"do-not-sync":false,"trace":false,"force-user-env":false,"force-disable-user-env":false,"open-devtools":false,"__sandbox":false,"no-proxy-server":false,"nolazy":false,"force-renderer-accessibility":false,"ignore-certificate-errors":false,"allow-insecure-localhost":false,"logsPath":"/home/vivi/.config/Code/logs/20210505T172150"},"logLevel":0}", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
[26232:0505/172151.303815:INFO:CONSOLE(25)] "%cTRACE color: #888 Started scanning user extensions", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
[26232:0505/172151.314600:INFO:CONSOLE(626)] "%cTRACE color: #888 Settings Sync: Initializing accounts", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (626)
[26232:0505/172151.315095:INFO:CONSOLE(626)] "%cTRACE color: #888 Settings Sync: Getting accounts for microsoft", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (626)
[main 2021-05-05T09:21:51.315Z] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/stable/3c4e3df9e89829dce27b7b5c24508306b151f30d
[main 2021-05-05T09:21:51.316Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[26232:0505/172151.325358:INFO:CONSOLE(25)] "%cTRACE color: #888 Started scanning system extensions", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
[26232:0505/172151.325463:INFO:CONSOLE(25)] "%cTRACE color: #888 Started scanning user extensions", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
[26232:0505/172151.325516:INFO:CONSOLE(26)] "Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (26)
[main 2021-05-05T09:21:51.325Z] SharedProcess: Overall ready
[26232:0505/172151.327039:INFO:CONSOLE(25)] "%cTRACE color: #888 Extension VSIX downlads cache dir does not exist", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
[26232:0505/172151.334820:INFO:CONSOLE(626)] "%cTRACE color: #888 StartupGettingStarted: undefined", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (626)
[26232:0505/172151.385640:INFO:CONSOLE(2786)] "Extension Host", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (2786)
[26232:0505/172151.386022:INFO:CONSOLE(25)] "%cTRACE color: #888 Scanned user extensions: 0", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
[26232:0505/172151.386325:INFO:CONSOLE(2786)] "%c/usr/share/code/code: /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0: no version information available (required by /usr/share/code/code)
 color: red", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (2786)
[26232:0505/172151.386499:INFO:CONSOLE(25)] "%cTRACE color: #888 Scanned user extensions: 0", source: file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
[26232:0505/172151.386745:INFO:CONSOLE(2786)] "console.groupEnd", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (2786)
[26232:0505/172151.387942:INFO:CONSOLE(626)] "%cTRACE color: #888 [File Watcher (node.js)] [ADDED] /home/vivi/.config/Code/logs/20210505T172150/output_1_20210505T172150", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (626)
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at v (/usr/share/code/resources/app/out/vs/loader.js:4:694)
    at bindings (/usr/share/code/resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1248)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at t (/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1656)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/code/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/code/resources/app/out/vs/loader.js:3:10626)
    at /usr/share/code/resources/app/out/vs/loader.js:3:10332
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1673)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/code/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/code/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/code/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/code/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/code/resources/app/out/vs/loader.js:5:9420)
    at D.E (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:4705)
    at new Promise (<anonymous>)
    at D (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:4685)
    at n._createSpdLogLogger (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:5618)
    at new n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:5434)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:58:2009
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async K.startup (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:58:1819) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}

---------INFO2---------

> 
INFO2 : code --verbose --use-gl=swiftshade:
[main 2021-05-05T09:16:27.380Z] [uncaught exception in main]: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
[main 2021-05-05T09:16:27.380Z] Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at v (/usr/share/code/resources/app/out/vs/loader.js:4:694)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/vscode-sqlite3/lib/sqlite3.js:1:77)
    at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1248)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at t (/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1656)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/code/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/code/resources/app/out/vs/loader.js:3:10626)
    at /usr/share/code/resources/app/out/vs/loader.js:3:10332
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1673)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/code/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/code/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/code/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/code/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/code/resources/app/out/vs/loader.js:5:9420)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31711
    at new Promise (<anonymous>)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31691
    at new Promise (<anonymous>)
    at y.doConnect (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31671)
    at y.connect (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:31117)
    at new y (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:28457)
    at m.doCreate (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:9829)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:8715
    at m.init (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:9057)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:50:12529
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at v (/usr/share/code/resources/app/out/vs/loader.js:4:694)
    at bindings (/usr/share/code/resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1248)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at t (/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1656)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/code/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/code/resources/app/out/vs/loader.js:3:10626)
    at /usr/share/code/resources/app/out/vs/loader.js:3:10332
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:4:1673)
    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)
    at l (/usr/share/code/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/code/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/code/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/code/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/code/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/code/resources/app/out/vs/loader.js:5:9420)
    at D.E (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:4705)
    at new Promise (<anonymous>)
    at D (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:4685)
    at n._createSpdLogLogger (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:5618)
    at new n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:5434)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:58:2009
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async K.startup (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:58:1819) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/115784

Please install gcc-5 or higher toolchain to fix the issue.
