### ISSUE TITLE
Localization: starts with 'DE' locale and verifies title and viewlets text is in German

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123083]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=117286&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&s=d26761af-f5e8-5e3e-3ed3-ef1ee2069094&t=2912d057-d0f3-5270-1d09-777eeaba2eea&l=78

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:173:19)
      at async Code.waitForTextContent (/Users/runner/work/1/s/test/automation/out/code.js:234:16)
      at async Search.waitForTitle (/Users/runner/work/1/s/test/automation/out/viewlet.js:12:9)
      at async Context.<anonymous> (out/areas/workbench/localization.test.js:26:13)
```

Note: this is from remote smoke test it seems.

**Comment by joaomoreno** [comment]
Related https://github.com/microsoft/vscode/issues/122629

**Comment by dbaeumer** [comment]
@bpasero can I somehow detect that we run remote smoke tests. I would then disable the test for remote for now until I understand why they fail.

**Comment by bpasero** [comment]
Yeah I think we already have some code that depends on the `remote` option for the smoke tests, e.g. here:

https://github.com/microsoft/vscode/blob/ac0008a25b8f0d2e056c8eb84fcb1497864bbbf3/test/automation/src/application.ts#L149-L151
