### ISSUE TITLE
v1.56.0 broke remote SSH on Ubuntu 20.04

### ISSUE THREAD

**Issue by bmakan** [microsoft/vscode#123073]
- VS Code Version: 1.56.0
- OS Version:

>  Operating System: Ubuntu 20.04.2 LTS
>            Kernel: Linux 5.8.0-50-generic

Steps to Reproduce:

1. Upgrade to 1.56.0
2. Connect via SSH remotely

Does this issue occur when all extensions are disabled?: Yes

SSH Output:
```
[08:09:34.167] Log Level: 2
[08:09:34.171] remote-ssh@0.63.0
[08:09:34.171] linux x64
[08:09:34.173] SSH Resolver called for "ssh-remote+[hostname]", attempt 1
[08:09:34.174] "remote.SSH.useLocalServer": true
[08:09:34.174] "remote.SSH.sshPath": undefined
[08:09:34.174] "remote.SSH.sshConfigurationFile": undefined
[08:09:34.174] "remote.SSH.useFlock": true
[08:09:34.175] "remote.SSH.lockfilesInTmp": false
[08:09:34.175] "remote.SSH.localServerDownload": auto
[08:09:34.175] "remote.SSH.remoteServerListenOnSocket": false
[08:09:34.175] "remote.SSH.showLoginTerminal": false
[08:09:34.176] SSH Resolver called for host: [hostname]
[08:09:34.176] Setting up SSH remote "[hostname]"
[08:09:34.179] Acquiring local install lock: /tmp/vscode-remote-ssh-[hostname]-install.lock
[08:09:34.213] Looking for existing server data file at /home/bmakan/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-[hostname]-cfa2e218100323074ac1948c885448fdf4de2a7f-0.63.0/data.json
[08:09:34.215] Using commit id "cfa2e218100323074ac1948c885448fdf4de2a7f" and quality "stable" for server
[08:09:34.220] Install and start server if needed
[08:09:34.232] Checking ssh with "ssh -V"
[08:09:34.245] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020

[08:09:34.250] askpass server listening on /run/user/1000/vscode-ssh-askpass-d91df350bb80d4fd586b4a629850cbe2a2a0a40f.sock
[08:09:34.250] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-aff2b6e2a48470fed2e8623e295040257c658e9d.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","41435","-o","ConnectTimeout=15","[hostname]"],"dataFilePath":"/home/bmakan/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-[hostname]-cfa2e218100323074ac1948c885448fdf4de2a7f-0.63.0/data.json"}
[08:09:34.250] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/63/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-d91df350bb80d4fd586b4a629850cbe2a2a0a40f.sock"}
[08:09:34.266] Spawned 12108
[08:09:34.428] > local-server> Spawned ssh: 12116
[08:09:34.433] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
[08:09:34.783] stderr> events.js:292
[08:09:34.783] stderr>       throw er; // Unhandled 'error' event
[08:09:34.783] stderr>       ^
[08:09:34.784] stderr> 
[08:09:34.784] stderr> Error [ERR_STREAM_WRITE_AFTER_END]: write after end
[08:09:34.784] stderr>     at writeAfterEnd (_http_outgoing.js:668:15)
[08:09:34.784] stderr>     at ServerResponse.end (_http_outgoing.js:789:7)
[08:09:34.784] stderr>     at Object.onRequest (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/localServer.js:1:2599)
[08:09:34.785] stderr>     at Server.<anonymous> (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/localServer.js:1:1914)
[08:09:34.785] stderr>     at Server.emit (events.js:315:20)
[08:09:34.785] stderr>     at parserOnIncoming (_http_server.js:874:12)
[08:09:34.785] stderr>     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
[08:09:34.785] stderr> Emitted 'error' event on ServerResponse instance at:
[08:09:34.785] stderr>     at writeAfterEndNT (_http_outgoing.js:727:7)
[08:09:34.785] stderr>     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
[08:09:34.785] stderr>   code: 'ERR_STREAM_WRITE_AFTER_END'
[08:09:34.785] stderr> }
[08:09:34.789] Local server exit: 1
[08:09:34.790] Received install output: OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ServerResponse.end (_http_outgoing.js:789:7)
    at Object.onRequest (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/localServer.js:1:2599)
    at Server.<anonymous> (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/localServer.js:1:1914)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:727:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

[08:09:34.791] Stopped parsing output early. Remaining text: OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020events.js:292      throw er; // Unhandled 'error' event      ^Error [ERR_STREAM_WRITE_AFTER_END]: write after end    at writeAfterEnd (_http_outgoing.js:668:15)    at ServerResponse.end (_http_outgoing.js:789:7)    at Object.onRequest (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/localServer.js:1:2599)    at Server.<anonymous> (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/localServer.js:1:1914)    at Server.emit (events.js:315:20)    at parserOnIncoming (_http_server.js:874:12)    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)Emitted 'error' event on ServerResponse instance at:    at writeAfterEndNT (_http_outgoing.js:727:7)    at processTicksAndRejections (internal/process/task_queues.js:81:21) {  code: 'ERR_STREAM_WRITE_AFTER_END'}
[08:09:34.791] Failed to parse remote port from server output
[08:09:34.793] Resolver error: Error: 
	at Function.Create (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:64027)
	at Object.t.handleInstallOutput (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:62766)
	at Object.t.tryInstallWithLocalServer (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:405034)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:310329
	at async Object.t.withShowDetailsEvent (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:405790)
	at async /home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:403558
	at async S (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:400326)
	at async Object.t.resolveWithLocalServer (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:403185)
	at async Object.t.resolve (/home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:314332)
	at async /home/bmakan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:127:110333
[08:09:34.798] ------




[08:09:36.642] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
[08:09:36.653] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I tried to remove the /home/[user]/.vscode-server folder but it didn't help.

I downloaded and installed 1.55.2 separately and it works without issues.

**Comment by roblourens** [comment]
This was already fixed, but it looks like you have an old version of the SSH extension installed, 0.63.0. Please make sure you have updated to the latest.

**Comment by bmakan** [comment]
Yup, that helped! Thanks.
