### ISSUE TITLE
Error: Terminal with ID 3 does not exist (has it already been disposed?)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123088]
Seeing this in my console, running out of sources. I created a couple of terminals and shutdown:

```
Terminal with ID 3 does not exist (has it already been disposed?): Error: Terminal with ID 3 does not exist (has it already been disposed?)
    at TerminalService._getIndexFromId (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:642:23)
    at TerminalService.setActiveInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:440:48)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:91:43
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:44:93
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:623:34
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at SelectionTrait._set (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:114:28)
    at SelectionTrait.set (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:105:25)
    at TerminalTabList.setSelection (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:1068:28)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:46:26
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:482:41)
    at HTMLTextAreaElement.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:480:74)
    at t.focus (/Users/bpasero/Development/Microsoft/monaco/node_modules/xterm/lib/xterm.js:1:42969)
    at e.focus (/Users/bpasero/Development/Microsoft/monaco/node_modules/xterm/lib/xterm.js:1:79489)
    at TerminalInstance.focus (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:744:29)
    at TerminalService._removeTab (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:371:36)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:70:46
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:482:41)
    at TerminalGroup._onInstanceDisposed (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalGroup.js:305:34)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalGroup.js:276:73
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at TerminalInstance.dispose (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:718:34)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:322:65
    at Array.forEach (<anonymous>)
    at TerminalService._onWillShutdown (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:322:36)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:64:55
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at NativeLifecycleService.handleWillShutdown (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.js:114:34)
    at EventEmitter.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.js:65:28)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:93:925)", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js (206)
```

**Comment by acotty** [comment]
Seeing similar errors in https://github.com/microsoft/vscode/issues/123040

**Comment by acotty** [comment]
Did you delete the terminal by the old terminal dropdown or the new tab? Try to delete the terminal via the old drop down and see if the error still occurs.
