### ISSUE TITLE
TypeError: userAssociations is not iterable

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123078]
Seeing this stack running out of sources:

```
ERR color: #f33 userAssociations is not iterable: TypeError: userAssociations is not iterable
    at EditorOverrideService.cacheContributionPoints (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/editor/browser/editorOverrideService.js:444:39)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/editor/browser/editorOverrideService.js:34:22
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at NativeStorageService.flush (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/storage/common/storage.js:226:35)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/workbench.js:156:36
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:56:106
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:67:143
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:44:93
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:56:106
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at handler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:465:46)
    at ChannelClient.onResponse (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:534:17)
    at ChannelClient.onBuffer (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:523:33)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:358:73
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:479:38)
    at EventEmitter.fn (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:257:44)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:93:925)", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js (206)
```

**Comment by bpasero** [comment]
My user settings:

```
    "workbench.editorAssociations": {
        "*.js": "hexEditor.hexedit"
    }
```

**Comment by lramos15** [comment]
Closing for now as I believe what happened is you tried out the new setting and then switched back to main before main could handle it.
