### ISSUE TITLE
External terminals cannot be opened on the latest insiders

### ISSUE THREAD

**Issue by andfoy** [microsoft/vscode#123172]
- VS Code Version: 1.57.0-insider
- OS Version: Ubuntu 20.04 snap

Steps to Reproduce:

1. Try to use the shortcut to open an external terminal, in my case, <kbd>Ctrl+Shift+C</kbd>
2. The output console logs the following error
```js
[2021-05-06 12:54:37.459] [renderer3] [error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at Je.spawnTerminal (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:32:630)
    at Je.openTerminal (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:31:618)
    at Object.call (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:21:8182)
    at f.onPromise (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:20:7475)
    at f.onRawMessage (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:20:6834)
    at /snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:20:6087
    at E.fire (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:16:1836)
    at /snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:14:46730
    at E.fire (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:16:1836)
    at /snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:14:46896
    at E.fire (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:16:1836)
    at IpcMainImpl.C (/snap/code-insiders/705/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:14:48517)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)
```
This feature was working on the previous insiders version.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

/duplicate
