### ISSUE TITLE
TypeError: Cannot read property 'uri' of undefined     at ExtHostNotebookKernels.$acceptSelection

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#123268]
Has seen happening in integration tests and when running out of sources. This means we select a controller for a notebook that has been disposed in the meantime...

```
Cannot read property 'uri' of undefined: TypeError: Cannot read property 'uri' of undefined
    at ExtHostNotebookKernels.$acceptSelection (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/common/extHostNotebookKernels.ts:207:45)
    at RPCProtocol._doInvokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:417:17)
    at RPCProtocol._invokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:402:32)
    at RPCProtocol._receiveRequest (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:318:19)
    at RPCProtocol._receiveOneMessage (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:245:10)
    at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:110:42
    at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/event.ts:622:16)
    at BufferedEmitter.fire (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/file:/Users/jrieken/Code/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:468:19)
    at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts:198:22
```

**Comment by jrieken** [comment]
Fun bug: when a notebook document is closed we (1) remove it from the extension host and (2) unselect it from a kernel. Both are driven from the same event it order matters... I will add an `onWillRemove` event for clean-up that still needs the notebook.
