### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 4 === 3. Registered script kind should match new script kind.

### ISSUE THREAD

**Issue by noobshow** [microsoft/vscode#123401]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. Expected 4 === 3. Registered script kind should match new script kind.
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:149163:34)
    at tryReuseStructureFromOldProgram (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:106900:28)
    at Object.createProgram (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:106431:29)
    at synchronizeHostData (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:149086:26)
    at Proxy.getProgram (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:149178:13)
    at InferredProject.Project.updateGraphWorker (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:154091:53)
    at InferredProject.Project.updateGraph (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:154021:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:156193:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:157750:26)
    at /home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:158024:97
    at Object.flatMap (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:158024:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:159079:46)
    at /home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:160963:88
    at IOSession.Session.executeWithRequestId (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:160954:28)
    at IOSession.Session.executeCommand (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:160963:33)
    at IOSession.Session.onMessage (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:160989:35)
    at Interface.<anonymous> (/home/samson/.vscode-server-insiders/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/extensions/node_modules/typescript/lib/tsserver.js:163650:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.56.0-insider (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:56:48.403Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (4.57GB free)|
|Process Argv|--crash-reporter-id 795e2a72-0df2-427f-9fe3-c33aeb7bb611|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2 x 2711)|
|Memory (System)|3.84GB (2.36GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.1.1
remote-wsl|ms-|0.56.1
sublime-keybindings|ms-|4.0.9
html-to-jsx|ria|0.0.1

</details>

**Comment by noobshow** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [TS Server fatal error:  Debug Failure. Expected 3 === 1. Registered script kind should match new script kind. (#120073)](https://www.github.com/microsoft/vscode/issues/120073)
> * [TS Server fatal error:  Debug Failure. Expected 3 === 1. Registered script kind should match new script kind. (#122291)](https://www.github.com/microsoft/vscode/issues/122291)
> * [TS Server fatal error:  No Project. (#122615)](https://www.github.com/microsoft/vscode/issues/122615)
> * [TS Server fatal error:  Debug Failure. False expression. (#121318)](https://www.github.com/microsoft/vscode/issues/121318)
> * [TS Server fatal error:  Debug Failure. False expression. (#118909)](https://www.github.com/microsoft/vscode/issues/118909)

line-by-line comparison seems to make the function calls look similar, but using different ts server makes me doubt they are truly similar

**Comment by mjbvz** [comment]
Duplicate of microsoft/TypeScript#42613 (as found by duplicate bot)
