### ISSUE TITLE
ERR unknown text editor: 415ed667-a322-4c86-8b8c-c2e159083856

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#123563]
* open a notebook
* f1 > restart extension host
* click inside the notebook cells
* 💥  the error below happens

```
ERR unknown text editor: 415ed667-a322-4c86-8b8c-c2e159083856. known editors:  : Error: unknown text editor: 415ed667-a322-4c86-8b8c-c2e159083856. known editors:  
	at ExtHostNotebookController.$acceptEditorPropertiesChanged (/Users/jrieken/Code/vscode/out/vs/workbench/api/common/extHostNotebook.js:333:23)
	at RPCProtocol._doInvokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
	at RPCProtocol._invokeHandler (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
	at RPCProtocol._receiveRequest (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
	at RPCProtocol._receiveOneMessage (/Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
	at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
	at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:490:38)
	at BufferedEmitter.fire (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
	at /Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:146:41
	at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:490:38)
	at BufferedEmitter.fire (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
	at PersistentProtocol._receiveMessage (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
	at /Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:510:83
	at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:490:38)
	at ProtocolReader.acceptChunk (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
	at /Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:158:61
	at Socket.listener (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by rzhao271** [comment]
@jrieken is it expected for the notebook tab to just close upon running the command to restart the extension host?

**Comment by jrieken** [comment]
Yeah, that's the new thing. We don't know when (iff ever) the extension returns so we play save and close all notebook editors from that extension
