### ISSUE TITLE
Cannot have two contributions with the same id editor.contrib.acceptChangesButton

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123543]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=118059&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=41d9f3a8-af10-5350-1c03-229d27a4a1b6&l=123

```
Cannot have two contributions with the same id editor.contrib.acceptChangesButton: Error: Cannot have two contributions with the same id editor.contrib.acceptChangesButton
    at new ln (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:652:76088)
    at h._createInstance (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at h.createInstance (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at Nt._createInnerEditor (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:683:26284)
    at Nt._createLeftHandSideEditor (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:683:23189)
    at new Nt (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:683:20180)
    at h._createInstance (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at h.createInstance (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at qo.createEditorControl (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:31335)
    at qo.createEditor (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:26647)
    at qo.create (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1440:57758)
    at u.doCreateEditorPane (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:134287)
    at u.doShowEditorPane (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:133862)
    at u.openEditor (file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:133386)
    at async file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2462:15867
    at async file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:44880

```

**Comment by nrayburn-tech** [comment]
A check for duplicate Ids was added in 5dcc4222997f6c691647c14db8be70aa2d2b0946, a few days ago.

**Comment by alexdima** [comment]
@joaomoreno Thanks for fixing :heart:
