### ISSUE TITLE
Tutorial for creating extension does not seem to work.

### ISSUE THREAD

**Issue by juli1** [microsoft/vscode#123609]
- VS Code Version: 1.56.1
- OS Version: Mac OS X Big Sur 11.3

Steps to Reproduce:

1. Follow instructions on https://code.visualstudio.com/api/get-started/your-first-extension
2. Traceback appears

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/vscode@^1.56.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/julien/.npm/_logs/2021-05-11T20_59_54_332Z-debug.log
```

I follow exactly the instructions from the tutorial (same package name, etc).

The log file contains the following content:

```
40 timing command:install Completed in 371ms
41 verbose type range
42 verbose stack @types/vscode: No matching version found for @types/vscode@^1.56.0.
42 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
42 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:945:19)
42 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:891:11)
42 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
42 verbose stack     at async Promise.all (index 1)
42 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
42 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:137:5)
43 verbose cwd /Users/julien/tmp/helloworld
44 verbose Darwin 20.4.0
45 verbose argv "/usr/local/Cellar/node/15.0.1/bin/node" "/usr/local/bin/npm" "install" "--cache-min" "86400"
46 verbose node v15.0.1
47 verbose npm  v7.11.1
48 error code ETARGET
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by juli1** [comment]
Removing my local `$USER/.npm` directory fixed the problem.
