### ISSUE TITLE
Notebook integration tests failing

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#123655]
Two different build runs, two different failures.

```
1) Notebook Document
       notebook open/close, notebook ready when cell-document open event is fired:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\notebook.document.test.ts:108:10)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

```
1) Notebook API tests
       set outputs on interrupt:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  [
+   'my output'
-   'Interrupted'
  ]
      + expected - actual

       [
      -  "my output"
      +  "Interrupted"
       ]
      
      at D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\notebook.test.ts:867:11
      at withEvent (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\notebook.test.ts:57:2)
      at Context.<anonymous> (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\notebook.test.ts:860:3)

```

**Comment by jrieken** [comment]
@roblourens Adding you for the "set outputs on interrupt" failure. I have added quite some assertions over the last weeks that ensure that the right kernel is being used. Unsure what else is going wrong, maybe it is the debouncing of output of executions 🤷

**Comment by roblourens** [comment]
If `'my output'` is showing up, doesn't that still mean it's using the wrong kernel?

**Comment by jrieken** [comment]
[This should assert](https://github.com/microsoft/vscode/blob/2b8d74c4a827b7099add6ad035b64411af394981/extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts#L840) that the right kernel is used... Unsure where the output comes from. Is there some default output or is it always the kernel?

**Comment by roblourens** [comment]
Seems like the only place it could come from is the default kernel

**Comment by roblourens** [comment]
I repeated the test by itself 1000 times, and saw a failure but a different one.

```
  1) Notebook API tests
       set outputs on interrupt (iteration 519):
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Notebook API tests
       set outputs on interrupt (iteration 797):
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) Notebook API tests
       set outputs on interrupt (iteration 943):
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

where `onDidChangeCellOutputs` doesn't fire. But never saw the failure we see in CI. So I wonder if there is something leaking between individual test runs.

**Comment by roblourens** [comment]
I don't think this has randomly failed recently, right? We saw it with some regularity a couple weeks ago...
