### ISSUE TITLE
Smoke test failures

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#123621]
```
  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           searches for body & checks for correct result number:
     Error: Timeout: click '.search-view .search-widget .search-container .monaco-inputbox textarea' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:173:19)
      at async Code.waitAndClick (/Users/runner/work/1/s/test/automation/out/code.js:238:9)
      at async Search.waitForInputFocus (/Users/runner/work/1/s/test/automation/out/search.js:95:13)
      at async Search.openSearchViewlet (/Users/runner/work/1/s/test/automation/out/search.js:38:9)
      at async Context.<anonymous> (out/areas/search/search.test.js:18:13)

  2) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           searches only for *.js files & checks for correct result number:
     Error: Timeout: click '.search-view .search-widget .search-container .monaco-inputbox textarea' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:173:19)
      at async Code.waitAndClick (/Users/runner/work/1/s/test/automation/out/code.js:238:9)
      at async Search.waitForInputFocus (/Users/runner/work/1/s/test/automation/out/search.js:95:13)
      at async Search.searchFor (/Users/runner/work/1/s/test/automation/out/search.js:41:9)
      at async Context.<anonymous> (out/areas/search/search.test.js:24:13)

  3) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           replaces first search result with a replace term:
     Error: Timeout: click '.search-view .search-widget .search-container .monaco-inputbox textarea' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:173:19)
      at async Code.waitAndClick (/Users/runner/work/1/s/test/automation/out/code.js:238:9)
      at async Search.waitForInputFocus (/Users/runner/work/1/s/test/automation/out/search.js:95:13)
      at async Search.searchFor (/Users/runner/work/1/s/test/automation/out/search.js:41:9)
      at async Context.<anonymous> (out/areas/search/search.test.js:40:13)

  4) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Extensions
           install and enable vscode-smoketest-check extension:
     Error: Timeout: is active element 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-editor textarea' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:173:19)
      at async Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/out/code.js:258:9)
      at async Extensions.openExtensionsViewlet (/Users/runner/work/1/s/test/automation/out/extensions.js:20:9)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:14:13)
```

**Comment by roblourens** [comment]
This test `Preferences changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it` breaks opening viewlets, leaves these errors behind


```
  ERR Invalid index: Error: Invalid index
    at BranchNode.addChild (file:///datadrive/vscode/out/vs/base/browser/ui/grid/gridview.js:232:23)
    at GridView.addView (file:///datadrive/vscode/out/vs/base/browser/ui/grid/gridview.js:670:27)
    at SerializableGrid._addView (file:///datadrive/vscode/out/vs/base/browser/ui/grid/grid.js:222:27)
    at SerializableGrid.addViewAt (file:///datadrive/vscode/out/vs/base/browser/ui/grid/grid.js:218:18)
    at SerializableGrid.moveViewTo (file:///datadrive/vscode/out/vs/base/browser/ui/grid/grid.js:261:22)
    at Workbench.setSideBarPosition (file:///datadrive/vscode/out/vs/workbench/browser/layout.js:298:36)
    at Workbench.doUpdateLayoutConfiguration (file:///datadrive/vscode/out/vs/workbench/browser/layout.js:250:22)
    at file:///datadrive/vscode/out/vs/workbench/browser/layout.js:181:90
    at Emitter.fire (file:///datadrive/vscode/out/vs/base/common/event.js:490:38)
    at WorkspaceService.triggerConfigurationChange (file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:752:48)
    at WorkspaceService.onLocalUserConfigurationChanged (file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:526:18)
    at WorkspaceService.reloadLocalUserConfiguration (file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:438:22)
    at async Promise.all (index 0)
    at async Object.settled (file:///datadrive/vscode/out/vs/base/common/async.js:946:28)
    at async WorkspaceService.updateValue (file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:224:13)
log.ts:296   ERR Invalid grid element: Error: Invalid grid element
    at indexInParent (file:///datadrive/vscode/out/vs/base/browser/ui/grid/grid.js:99:19)
    at getGridLocation (file:///datadrive/vscode/out/vs/base/browser/ui/grid/grid.js:123:23)
    at SerializableGrid.getViewLocation (file:///datadrive/vscode/out/vs/base/browser/ui/grid/grid.js:332:20)
    at SerializableGrid.getViewSize (file:///datadrive/vscode/out/vs/base/browser/ui/grid/grid.js:277:35)
    at Workbench.setSideBarPosition (file:///datadrive/vscode/out/vs/workbench/browser/layout.js:291:63)
    at Workbench.doUpdateLayoutConfiguration (file:///datadrive/vscode/out/vs/workbench/browser/layout.js:250:22)
    at file:///datadrive/vscode/out/vs/workbench/browser/layout.js:181:90
    at Emitter.fire (file:///datadrive/vscode/out/vs/base/common/event.js:490:38)
    at WorkspaceService.triggerConfigurationChange (file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:752:48)
    at WorkspaceService.onLocalUserConfigurationChanged (file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:526:18)
    at file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:61:107
    at Emitter.fire (file:///datadrive/vscode/out/vs/base/common/event.js:490:38)
    at file:///datadrive/vscode/out/vs/workbench/services/configuration/browser/configuration.js:22:171
```

I am not sure whether this is legit or not, but devops is telling me that this first happened on a build in your PR @lszomoru, https://github.com/microsoft/vscode/pull/123110/files can you take a look?
