### ISSUE TITLE
VS-Code Insiders - Not opening jupyter notebook in Ubuntu 20.04 after latest update of Insider version

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#123763]
After double-clicking on an .ipynb file its opening in a text format.

My VS-Code version details

```
Version: 1.57.0-insider
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:12:59.200Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic
```

Have tried uninstalling-and-reinstalling Python and vscode-jupyter extensions, didn't help.

After enabling Developer-Tool getting these details when double-clicking on an .ipynb file.

```
ERR command 'npm.packageManager' not found: Error: command 'npm.packageManager' not found
    at u._tryExecuteCommand (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1752:3364)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1752:3245
```

**Comment by rebornix** [comment]
@rohan-paul can you check the latest Insiders and see if it works?

**Comment by rohan-paul** [comment]
Yes its working after updating vscode-jupyter extension. Thanks very much.
