### ISSUE TITLE
sftp fail 

### ISSUE THREAD

**Issue by zhangyaoci** [microsoft/vscode#123759]
(internal/streams/transform.js:205:10)
    at SFTPStream._read (c:\Users\****\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)

**Comment by gjsjohnmurray** [comment]
/causedByExtension

See #122325
