### ISSUE TITLE
error in running program

### ISSUE THREAD

**Issue by dddeschua** [microsoft/vscode#123863]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Github output error :

Visual Studio Code GitHub Extension
git symbolic-ref -q HEAD
git --version
git for-each-ref --format='%(upstream)' 'refs/heads/master'
git config --local --get remote.origin.url
git config --local --get-regexp ^remote.*.url
Command failed with exit code 1: git config --local --get remote.origin.url
Error: Command failed with exit code 1: git config --local --get remote.origin.url
	at makeError (c:\Users\Chua Dhor Heng\.vscode\extensions\knisterpeter.vscode-github-0.30.6\node_modules\execa\lib\error.js:59:11)
	at handlePromise (c:\Users\Chua Dhor Heng\.vscode\extensions\knisterpeter.vscode-github-0.30.6\node_modules\execa\index.js:114:26)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)

Your configuration contains an invalid remoteName. Consider setting the `github.remoteName` setting with one of these:

name

Failed to connect to provider "Command failed with exit code 1: git config --local --get remote.origin.url"
git branch
git symbolic-ref -q HEAD
git for-each-ref --format='%(upstream)' 'refs/heads/master'
git config --local --get remote.origin.url
git config --local --get-regexp ^remote.*.url
Command failed with exit code 1: git config --local --get remote.origin.url
Error: Command failed with exit code 1: git config --local --get remote.origin.url
	at makeError (c:\Users\Chua Dhor Heng\.vscode\extensions\knisterpeter.vscode-github-0.30.6\node_modules\execa\lib\error.js:59:11)
	at handlePromise (c:\Users\Chua Dhor Heng\.vscode\extensions\knisterpeter.vscode-github-0.30.6\node_modules\execa\index.js:114:26)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)

Your configuration contains an invalid remoteName. Consider setting the `github.remoteName` setting with one of these:

name

Python error on typing python manage.py runserver: 

PS D:\v0.02j\JW> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner        
    self.run()
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 53, 
in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 76, 
in raise_last_exception
    raise _exception[1]
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 53, 
in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 91, in 
populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module  
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth'
Traceback (most recent call last):
  File "D:\v0.02j\JW\manage.py", line 22, in <module>
    main()
  File "D:\v0.02j\JW\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 
330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 
371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 96, in handle
    self.run(**options)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 614, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 599, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 314, in run
    self.run_loop()
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 320, in run_loop
    next(ticker)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 360, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 376, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 274, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1204, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\Chua Dhor Heng\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'     
PS D:\v0.02j\JW>

**Comment by lramos15** [comment]
This sounds like an error with your code or environment and not VS code since we do not change the way your code runs. Please feel free to reopen if you're still having issues
