### ISSUE TITLE
extension tests not working in 1.56.2

### ISSUE THREAD

**Issue by gitlab-vscode** [microsoft/vscode#123855]
Does this issue occur when all extensions are disabled?: No (it affects extension tests

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0

(it also happens on Linux)

This issue affects (to my best knowledge) all extension tests. (e.g. [this failing pipeline](https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/jobs/1261887746))

Steps to Reproduce:

1. Create a new extension `npx yo generator-code`
   - What type of extension do you want to create? New Extension (TypeScript)
   - What's the name of your extension? integration-tests
   - Bundle the source code with webpack? No
   - Which package manager to use? npm
2. Try to run tests `cd integration-tests && npm test`

This issue started with the release of `1.56.2` this morning.

There is no useful information in the logs:

<details>
<summary>Logs from running npm test</summary>

```
~/w/t/integratin-test ❯❯❯ npm run test                                                                  ✘ 127 

> integratin-test@0.0.1 pretest /Users/tomas/workspace/tmp/integratin-test
> npm run compile && npm run lint


> integratin-test@0.0.1 compile /Users/tomas/workspace/tmp/integratin-test
> tsc -p ./


> integratin-test@0.0.1 lint /Users/tomas/workspace/tmp/integratin-test
> eslint src --ext ts


> integratin-test@0.0.1 test /Users/tomas/workspace/tmp/integratin-test
> node ./out/test/runTest.js

Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 851954/109376110 (1%Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 3833852/109376110 (4Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 11501560/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 20004849/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 28819447/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 37388284/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 45694961/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 54640639/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 63258609/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 71630834/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 80052224/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 88326135/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 97042419/109376110 (Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: 106233842/109376110 Downloading VS Code 1.56.2 from https://update.code.visualstudio.com/1.56.2/darwin/stable: complete
Downloaded VS Code 1.56.2 into .vscode-test/vscode-darwin-1.56.2
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2021-05-14T07:57:30.368Z] Running extension tests from the command line is currently only supported if no other instance of Code is running.

[main 2021-05-14T07:57:30.370Z] Error: Running extension tests from the command line is currently only supported if no other instance of Code is running.
    at Z.claimInstance (/Users/tomas/workspace/tmp/integratin-test/.vscode-test/vscode-darwin-1.56.2/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:59:4914)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/tomas/workspace/tmp/integratin-test/.vscode-test/vscode-darwin-1.56.2/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:59:1950
    at async Z.startup (/Users/tomas/workspace/tmp/integratin-test/.vscode-test/vscode-darwin-1.56.2/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:59:1821)

Exit code:   1
Done

Failed to run tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integratin-test@0.0.1 test: `node ./out/test/runTest.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the integratin-test@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomas/.npm/_logs/2021-05-14T07_57_30_406Z-debug.log
```

</details>

**Comment by gitlab-vscode** [comment]
I can't now reproduce the issue with the generated new extension. I'm going to close the issue before I'm sure the error is not on my side.
