### ISSUE TITLE
Can't open any file

### ISSUE THREAD

**Issue by AndreaBoom** [microsoft/vscode#123917]
Issue Type: <b>Bug</b>

Open the editor 
try to open a file 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.59GB free)|
|Process Argv|--crash-reporter-id 3f9006c3-b042-4a43-87c2-f83ebce0145a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
vscode-firefox-debug|fir|2.9.4
vscode-lombok|Gab|1.0.1
vscode-pull-request-github|Git|0.26.0
gc-excelviewer|Gra|3.0.41
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.12.1
vscode-edge-devtools|ms-|1.1.8
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.4.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-manifest-yaml|Piv|1.25.1
vscode-spring-boot|Piv|1.25.1
java|red|0.79.1
vscode-yaml|red|0.19.0
sonarlint-vscode|Son|1.22.0
vscodeintellicode|Vis|1.2.13
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
vscode-icons|vsc|11.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943:30300582
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by Alucard4635** [comment]
This is all I see in the developer tool
> (node:452) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
S @ workbench.desktop.main.js:sourcemap:62
workbench.desktop.main.js:sourcemap:62 [Extension Host] [vscode-icons] v11.4.0 activated!
3workbench.desktop.main.js:sourcemap:627   ERR h is not iterable: TypeError: h is not iterable
    at Tn.cacheContributionPoints (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:18608)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:10261
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at w.flush (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:6738)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2509:61901
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58821
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58966
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58655
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58821
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at X (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:3423)
    at _.onResponse (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4399)
    at _.onBuffer (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4239)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:1817
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at EventEmitter.V (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60442)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:121:1082)
workbench.desktop.main.js:sourcemap:627   ERR h is not iterable: TypeError: h is not iterable
    at Tn.cacheContributionPoints (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:18608)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:10261
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at w.flush (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:6738)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:4405

**Comment by ian-byrne** [comment]
I am having the same issue with no files opening on an m1 mbp, Big Sur 11.3.1. 

I have the filter is not a function log as well as:
`ERR h is not iterable: TypeError: h is not iterable workbench.desktop.main.js:627 `
along with file references much like the above.

**Comment by Alucard4635** [comment]
I have these errors too:
> console.ts:137 [Extension Host] extension activation failed TypeError: o.getConfiguration(...).get(...).find is not a function
	at new m (c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:682923)
	at Object.t.resolveInstance (c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:238445)
	at c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:237650
	at Object.t.resolve (c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:237913)
	at c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:229010
	at e._get (c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:228776)
	at e.get (c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:227488)
	at a.get (c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:90:508810)
	at c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:271101
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:37:823700
	at async t.activate (c:\Users\andre\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:37:823387)
	at async Promise.all (index 0)
	at async Promise.all (index 95)
	at async Promise.all (index 1)

This is legated to the python extension, if I disable it there problem still remain.

Meanwhile,
> ERR h is not iterable: TypeError: h is not iterable
    at Tn.cacheContributionPoints (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:18608)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:10261
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at w.flush (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:6738)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2509:61901
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58821
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58966
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58655
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58821
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at X (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:3423)
    at _.onResponse (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4399)
    at _.onBuffer (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4239)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:1817
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at EventEmitter.V (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60442)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:121:1082)
log.ts:296   ERR h is not iterable: TypeError: h is not iterable
    at Tn.cacheContributionPoints (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:18608)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:10261
    at a.fire (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at w.flush (file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:6738)
    at file:///C:/Users/andre/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:4405
    
There appers after a while.

**Comment by oliversalzburg** [comment]
In case it helps. It seems to me like it's hitting https://github.com/microsoft/vscode/blob/22fc27d4cf7bb44d4d846642f98e32f098538f4b/src/vs/workbench/services/editor/browser/editorOverrideService.ts#L196 and receives a hash, in my case `{*.ipynb: "jupyter.notebook.ipynb"}`, which obviously isn't an array.

**Comment by ChinYoung** [comment]
Having the same issue.

**Comment by Cow258** [comment]
# Unable to F12 "Go to Definition"

## Dev Tool Log
```
  ERR h is not iterable: TypeError: h is not iterable
    at Tn.cacheContributionPoints (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2164:18608)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2164:10261
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at w.flush (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:637:6738)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2509:61901
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:58821
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:58966
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:58655
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:58821
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at X (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:3423)
    at _.onResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:4399)
    at _.onBuffer (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:4239)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:1817
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at EventEmitter.V (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:60442)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:121:1082)
4workbench.desktop.main.js:627   
ERR h is not iterable: TypeError: h is not iterable
    at Tn.cacheContributionPoints (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2164:18608)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2164:10261
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at w.flush (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:637:6738)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:637:4405
3workbench.desktop.main.js:627   
ERR (this.configurationService.getValue(...) || []).filter is not a function: TypeError: (this.configurationService.getValue(...) || []).filter is not a function
    at Tn.getAssociationsForResource (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2164:12327)
    at Tn.getContributionPoint (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2164:13461)
    at Tn.resolveEditorOverride (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2164:11179)
    at A.openEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2290:16803)
    at C.doOpenCodeEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1448:20479)
    at C.openCodeEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1448:19962)
    at U._openReference (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:730:32000)
    at U._onResult (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:730:31737)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:730:31339
```

## Screenshot

![image](https://user-images.githubusercontent.com/14261588/118426035-08781280-b6fd-11eb-814e-aad5d366a5c8.png)

## VS Code Version
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (4 days ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

## Computer Information 

CPUs | Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 3, 3
Memory (System) | 16.00GB (0.41GB free)
Process Argv | --crash-reporter-id 9609139e-ff14-47e1-9dd4-a8b2bc3ee096
Screen Reader | no
VM | 0%



## Extension

Extension | Author (truncated) | Version
-- | -- | --
Handlebars | and | 0.4.1
vscode-svgviewer | css | 2.0.0
vscode-eslint | dba | 2.1.20
gitlens | eam | 11.4.1
auto-rename-tag | for | 0.1.6
vscode-mysql | for | 0.4.0
template-string-converter | meg | 0.4.7
vscode-filesize | mkx | 3.1.0
vscode-scss | mrm | 0.10.0
vscode-docker | ms- | 1.12.1
python | ms- | 2021.5.842923320
vscode-pylance | ms- | 2021.5.2
jupyter | ms- | 2021.6.832593372
cordova-tools | msj | 2.2.1
indent-rainbow | ode | 7.5.0
material-icon-theme | PKi | 4.6.0
vscode-yaml | red | 0.19.0
vscode-sass-format | sas | 1.1.7
js-jsx-snippets | sky | 10.1.0
vscode-import-cost | wix | 2.15.0

**Comment by egamma** [comment]
closing in favor of https://github.com/microsoft/vscode/issues/123993
