### ISSUE TITLE
Unable to open files

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#123993]
Issue Type: <b>Bug</b>

When I try to open a file from the file explorer panel, nothing happens.

When I try to open a file through the keyboard shortcut, this error is printed in the devtools console of Code:
```
  ERR (this.configurationService.getValue(...) || []).filter is not a function: TypeError: (this.configurationService.getValue(...) || []).filter is not a function
    at Tn.getAssociationsForResource (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:12327)
    at Tn.getContributionPoint (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:13461)
    at Tn.resolveEditorOverride (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2164:11179)
    at A.openEditor (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:16803)
    at oi.openAnything (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2264:16981)
    at Object.accept (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2264:16269)
    at file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:43044
    at a.fire (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:568:40992
    at a.fire (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at HTMLDivElement.<anonymous> (file:///C:/Users/oliver/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:568:51547)
```

I initially noticed this issue in WSL, but it reproduces (as the system info should indicate) on Windows with all extensions disabled.

Insiders (Commit: 40d5e6796fbc32d67dd0009e5b0027003803fd7e) works as expected even in WSL with all extensions enabled.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (26.20GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/projects/cbc-kitten-scientists --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by oliversalzburg** [comment]
Assuming duplicate of #123917

**Comment by egamma** [comment]
reopening in favor of #123917

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/123749

**Comment by ian-byrne** [comment]
All the issues related to this I see are now closed, however, in the standard VS Code I still cannot open any files. Insiders is working as expected. This error appeared after I turned off all extensions and tried to open several .py files and my vscode settings .json. No idea if this could be it though on my end. 

`DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/054a9295330880ed74ceaedda236253b4f39a335/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout`

**Comment by lramos15** [comment]
@ian-byrne It's most likely due to your `settings.json` syncing a new `editorAssociations` setting from insiders to stable. My suggestion would be to use insiders for now or erase the editor association setting and then sync it to stable. The error message you posted is different than everyone else's. Let me know if that doesn't work.

**Comment by ian-byrne** [comment]
@lramos15 Yes, that appeared to be the issue, thank you! The editor associations were not in array format.

**Comment by changkun** [comment]
@lramos15 Thanks!
