### ISSUE TITLE
TerminalProfiles tests failures on my machine

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#124257]
Running `.\scripts\test.bat` on my Windows machine results in test failures.
Could it be that the Tests depend on what's installed on my machine ( I have WSL installed)?

```
 1) Workbench - TerminalProfiles
       detectAvailableProfiles
         should detect Git Bash and provide login args:

      AssertionError [ERR_ASSERTION]: Actual: Git Bash,Ubuntu (WSL)
Expected: Git Bash
      + expected - actual

      -2
      +1

      at profilesEqual (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:13:34)
      at Context.<anonymous> (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:60:21)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Workbench - TerminalProfiles
       detectAvailableProfiles
         should allow source to have args:
     AssertionError [ERR_ASSERTION]: Expected profile PowerShell not found
      at profilesEqual (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:16:29)
      at Context.<anonymous> (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:80:21)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) Workbench - TerminalProfiles
       detectAvailableProfiles
         configured args should override default source ones:

      AssertionError [ERR_ASSERTION]: Actual: Git Bash,Ubuntu (WSL)
Expected: Git Bash
      + expected - actual

      -2
      +1

      at profilesEqual (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:13:34)
      at Context.<anonymous> (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:98:21)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) Workbench - TerminalProfiles
       detectAvailableProfiles
         pwsh source detection/fallback
           should prefer pwsh 7 to Windows PowerShell:
     AssertionError [ERR_ASSERTION]: Expected profile PowerShell not found
      at profilesEqual (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:16:29)
      at Context.<anonymous> (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:121:25)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) Workbench - TerminalProfiles
       detectAvailableProfiles
         pwsh source detection/fallback
           should prefer pwsh 7 to pwsh 6:
     AssertionError [ERR_ASSERTION]: Expected profile PowerShell not found
      at profilesEqual (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:16:29)
      at Context.<anonymous> (file:///C:/Users/martinae/workspaces/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:134:25)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Tyriar** [comment]
Still happens https://github.com/microsoft/vscode/issues/125559#issue-911816707:

```
  6924 passing (2m)
  43 pending
  3 failing

  1) Workbench - TerminalProfiles
       detectAvailableProfiles
         should allow source to have args:

      AssertionError [ERR_ASSERTION]: Actual: 
Expected: PowerShell
      + expected - actual

      -0
      +1

      at profilesEqual (file:///D:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:13:18)
      at Context.<anonymous> (file:///D:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:67:21)

  2) Workbench - TerminalProfiles
       detectAvailableProfiles
         pwsh source detection/fallback
           should prefer pwsh 7 to Windows PowerShell:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'C:\\Users\\Daniel\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe'
- 'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
      + expected - actual

      -C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe
      +C:\Program Files\PowerShell\7\pwsh.exe

      at profilesEqual (file:///D:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:18:22)
      at Context.<anonymous> (file:///D:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:110:25)

  3) Workbench - TerminalProfiles
       detectAvailableProfiles
         pwsh source detection/fallback
           should prefer pwsh 7 to pwsh 6:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'C:\\Users\\Daniel\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe'
- 'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
      + expected - actual

      -C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe
      +C:\Program Files\PowerShell\7\pwsh.exe

      at profilesEqual (file:///D:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:18:22)
      at Context.<anonymous> (file:///D:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:124:25)
```
