### ISSUE TITLE
Error when saving file when switching editor

### ISSUE THREAD

**Issue by zgh0711** [microsoft/vscode#124319]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2 (user setup)
- OS Version: Windows_NT x64 10.0.19042

I have an extension developed based on webview. It worked normally before vscode version 1.56, but after vscode was upgraded to version 1.56, the extension had some problems.

The extension is actually a custom editor for xml files, and the main body is a web program developed based on vue.js.

In the extension, I used `vscode.commands.executeCommand('workbench.action.toggleEditorType')` to make a switch editor function, which will switch between the xml editor that comes with vscode and our editor .

When I modify the content of the file in the xml editor and click the switch button without saving it, vscode will prompt whether to save the changes. After selecting save, vscode will report an error, and then the xml file can’t open. Of course, you can open the xml file after closing the folder and reopening it.

```text
request.ts:42 GET https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json net::ERR_TIMED_OUT

log.ts:296   ERR Unable to read file 'vscode-userdata:/c:/Users/rtt/AppData/Roaming/Code/Backups/b177f3302cc06835f0ab5749bd24b28e/file/3ea12c37' (Error: Unable to resolve non-existing file 'vscode-userdata:/c:/Users/rtt/AppData/Roaming/Code/Backups/b177f3302cc06835f0ab5749bd24b28e/file/3ea12c37'): Error: Unable to read file 'vscode-userdata:/c:/Users/rtt/AppData/Roaming/Code/Backups/b177f3302cc06835f0ab5749bd24b28e/file/3ea12c37' (Error: Unable to resolve non-existing file 'vscode-userdata:/c:/Users/rtt/AppData/Roaming/Code/Backups/b177f3302cc06835f0ab5749bd24b28e/file/3ea12c37')
    at o.doReadFileStream (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:17601)
    at async ni.resolve (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2239:8774)
    at async Vr.resolveFromBackup (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2288:96734)
    at async Vr.doResolve (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2288:96029)
    at async n.resolve (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2296:35641)
    at async createModelReference (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2288:109858)
    at async file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1972:52884
    at async Object.resolveWebview (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:50154)
    at async i.tryRevive (file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2152:11249)
    at async file:///D:/Program Files/IDE/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2152:11357

notificationsAlerts.ts:40 Unable to open 'main.xml': Unable to read file 'vscode-userdata:/c:/Users/rtt/AppData/Roaming/Code/Backups/b177f3302cc06835f0ab5749bd24b28e/file/3ea12c37' (Error: Unable to resolve non-existing file 'vscode-userdata:/c:/Users/rtt/AppData/Roaming/Code/Backups/b177f3302cc06835f0ab5749bd24b28e/file/3ea12c37').
```

You can use the `Switch editor` command or click the button in the picture below to switch the editor.

![switch](https://user-images.githubusercontent.com/15401997/118974219-27003700-b9a5-11eb-8b01-7114c4f4e6c3.png)

## Extension and sample project
The problems mentioned above only appeared under the vscode 1.56 version, and there were no such problems before. I can't solve these problems now, and hope to tell me how to solve them.

My extension and an example project are attached below:
[NewProject.zip](https://github.com/microsoft/vscode/files/6515659/NewProject.zip)

**Comment by zgh0711** [comment]
And I will upload a debug extension later. Please wait

**Comment by mjbvz** [comment]
The zip doesn't seem to contain any extension code

Closing as we need more info to investigate
