### ISSUE TITLE
npe of settings editor toc

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#124605]
Issue Type: <b>Bug</b>

```
ERR Cannot read property 'children' of undefined: TypeError: Cannot read property 'children' of undefined
    at TOCTreeModel.get children [as children] (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/tocTree.js:40:43)
    at createTOCIterator (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/tocTree.js:117:37)
    at SettingsEditor2.refreshTOCTree (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:874:80)
    at SettingsEditor2.triggerSearch (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:936:26)
    at SettingsEditor2.onSearchInputChanged (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:888:24)
    at file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:347:22
    at Emitter.fire (file:///Users/penlv/code/vscode/out/vs/base/common/event.js:490:38)
    at file:///Users/penlv/code/vscode/out/vs/workbench/contrib/codeEditor/browser/suggestEnabledInput/suggestEnabledInput.js:78:44
    at file:///Users/penlv/code/vscode/out/vs/editor/common/model/textModel.js:216:56
    at Emitter.fire (file:///Users/penlv/code/vscode/out/vs/base/common/event.js:490:38)
    at DidChangeContentEmitter.endDeferredEmit (file:///Users/penlv/code/vscode/out/vs/editor/common/model/textModel.js:2708:39)
    at TextModel.pushEditOperations (file:///Users/penlv/code/vscode/out/vs/editor/common/model/textModel.js:931:36)
    at Cursor.executeEdits (file:///Users/penlv/code/vscode/out/vs/editor/common/controller/cursor.js:437:44)
    at file:///Users/penlv/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:742:69
    at ViewModel._withViewEventsCollector (file:///Users/penlv/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:817:17)
    at ViewModel._executeCursorEdit (file:///Users/penlv/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:739:18)
    at ViewModel.executeEdits (file:///Users/penlv/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:742:18)
    at CodeEditorWidget.executeEdits (file:///Users/penlv/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:809:39)
    at SuggestEnabledInput.setValue (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/codeEditor/browser/suggestEnabledInput/suggestEnabledInput.js:120:30)
    at SettingsEditor2._setOptions (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:205:35)
    at SettingsEditor2.setInput (file:///Users/penlv/code/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:167:18)
    at async EditorControl.doSetInput (file:///Users/penlv/code/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:157:17)
    at async EditorControl.openEditor (file:///Users/penlv/code/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:65:35)
    at async file:///Users/penlv/code/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:745:40
```

VS Code version: Code - OSS Dev 1.57.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.74GB free)|
|Process Argv|. --disable-gpu --enable-proposed-api ms-vsliveshare.vsliveshare --enable-proposed-api rebornix.better-jupyter-errors|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Do you know what you did when you saw this?

**Comment by rebornix** [comment]
@roblourens I realized there are such errors after the settings editor is closed.

**Comment by roblourens** [comment]
Have also seen

```
Cannot read property 'root' of undefined: TypeError: Cannot read property 'root' of undefined
    at SettingsEditor2.refreshTree (file:///datadrive/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:858:99)
    at SettingsEditor2.renderTree (file:///datadrive/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:849:22)
    at file:///datadrive/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:87:22
    at Emitter.fire (file:///datadrive/vscode/out/vs/base/common/event.js:490:38)
    at WorkspaceTrustManagementService.updateWorkspaceTrust (file:///datadrive/vscode/out/vs/workbench/services/workspaces/common/workspaceTrust.js:197:36)
    at async file:///datadrive/vscode/out/vs/workbench/services/workspaces/common/workspaceTrust.js:86:17
```

after reloading the window

**Comment by roblourens** [comment]
To verify, add to keybindings.json

```
{
        "key": "cmd+,",
        "command": "workbench.action.openSettings",
        "args": "@modified"
},
```

Press cmd+, when the settings editor is closed and verify that you don't see an error in the console
