### ISSUE TITLE
Element already has context attribute: output

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#124661]
* have a cell that prints must output (I am using a for-loop with my nodejs nodebook)
* repeatedly run the cell
* notice errors on the console: `Element already has context attribute: output`

After a few times you'll also see leak warnings from the context key service. It seems that scoped context key services leak and I wonder if that's caused by the reuse of it attribute. The debugger tells me that the existing service is disposed only after the first has been created (and conflicted)

```
<div tabindex="-1" class="console-message-wrapper console-from-api console-error-level console-selected" role="treeitem" aria-expanded="true" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; border-top-color: var(--error-border-color); border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(204, 222, 245); background-color: rgb(236, 241, 248); --error-text-color:  rgb(200 0 0); color: rgb(48, 57, 66); font-family: menlo, monospace; font-size: 11px; font-variant-ligatures: normal; orphans: 2; widows: 2; text-decoration-thickness: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size:  11px; --monospace-font-family:  menlo, monospace; --source-code-font-size:  11px; --source-code-font-family:  menlo, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">
ScopedContextKeyService | @ | contextKeyService.js:353
-- | -- | --
&nbsp; | createScoped | @ | contextKeyService.js:236
&nbsp; | CellOutputElement | @ | cellOutput.js:35
&nbsp; | _createInstance | @ | instantiationService.js:90
&nbsp; | createInstance | @ | instantiationService.js:61
&nbsp; | _renderOutput | @ | cellOutput.js:484
&nbsp; | render | @ | cellOutput.js:348
&nbsp; | CodeCell | @ | codeCell.js:180
&nbsp; | _createInstance | @ | instantiationService.js:90
&nbsp; | createInstance | @ | instantiationService.js:61
&nbsp; | renderElement | @ | cellRenderer.js:747
&nbsp; | renderElement | @ | listWidget.js:764
&nbsp; | insertItemInDOM | @ | listView.js:541
&nbsp; | render | @ | listView.js:497
&nbsp; | updateElementHeight | @ | listView.js:258
&nbsp; | updateElementHeight2 | @ | notebookCellList.js:697
&nbsp; | relayout | @ | notebookEditorWidget.js:1468
&nbsp; | (anonymous) | @ | notebookEditorWidget.js:1483
&nbsp; | execute | @ | dom.js:147
&nbsp; | animationFrameRunner | @ | dom.js:183
&nbsp; | requestAnimationFrame (async) | &nbsp; | &nbsp;
&nbsp; | doRequestAnimationFrame | @ | dom.js:131
&nbsp; | exports.scheduleAtNextAnimationFrame | @ | dom.js:192
&nbsp; | layoutNotebookCell | @ | notebookEditorWidget.js:1474
&nbsp; | (anonymous) | @ | notebookEditorWidget.js:1006
&nbsp; | fire | @ | event.js:490
&nbsp; | _fireOnDidChangeLayout | @ | codeCellViewModel.js:214
&nbsp; | layoutChange | @ | codeCellViewModel.js:211
&nbsp; | spliceOutputHeights | @ | codeCellViewModel.js:328
&nbsp; | (anonymous) | @ | cellOutput.js:430
&nbsp; | _updateOutputs | @ | cellOutput.js:429
&nbsp; | (anonymous) | @ | cellOutput.js:325
&nbsp; | fire | @ | event.js:490
&nbsp; | (anonymous) | @ | codeCellViewModel.js:50
&nbsp; | fire | @ | event.js:490
&nbsp; | spliceNotebookCellOutputs | @ | notebookCellTextModel.js:168
&nbsp; | _spliceNotebookCellOutputs | @ | notebookTextModel.js:680
&nbsp; | _spliceNotebookCellOutputs2 | @ | notebookTextModel.js:673
&nbsp; | _doApplyEdits | @ | notebookTextModel.js:361
&nbsp; | applyEdits | @ | notebookTextModel.js:272
&nbsp; | $applyEdits | @ | mainThreadNotebookDocuments.js:142
&nbsp; | _doInvokeHandler | @ | rpcProtocol.js:348
&nbsp; | _invokeHandler | @ | rpcProtocol.js:333
&nbsp; | _receiveRequest | @ | rpcProtocol.js:260
&nbsp; | _receiveOneMessage | @ | rpcProtocol.js:188
&nbsp; | (anonymous) | @ | rpcProtocol.js:69
&nbsp; | fire | @ | event.js:490
&nbsp; | fire | @ | ipc.net.js:375
&nbsp; | _receiveMessage | @ | ipc.net.js:654
&nbsp; | (anonymous) | @ | ipc.net.js:510
&nbsp; | fire | @ | event.js:490
&nbsp; | acceptChunk | @ | ipc.net.js:189
&nbsp; | (anonymous) | @ | ipc.net.js:158
&nbsp; | listener | @ | ipc.net.js:33
&nbsp; | emit | @ | events.js:315
&nbsp; | addChunk | @ | internal/streams/readable.js:309
&nbsp; | readableAddChunk | @ | internal/streams/readable.js:284
&nbsp; | Readable.push | @ | internal/streams/readable.js:223
&nbsp; | onStreamRead | @ | internal/stream_base_commons.js:188

</span></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-from-api console-error-level" role="treeitem" aria-expanded="false" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-color: transparent; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: transparent; background-color: rgb(255, 240, 240); color: rgb(48, 57, 66); font-family: menlo, monospace; font-size: 11px; font-variant-ligatures: normal; orphans: 2; widows: 2; text-decoration-thickness: initial;"><br class="Apple-interchange-newline"></div>
```

---

?context key service leak?
```
[018] potential listener LEAK detected, having 313 listeners already. MOST frequent listener (139):
check @ event.js:377
_event @ event.js:438
_updateParentChangeListener @ contextKeyService.js:359
ScopedContextKeyService @ contextKeyService.js:346
createScoped @ contextKeyService.js:236
CellOutputElement @ cellOutput.js:35
_createInstance @ instantiationService.js:90
createInstance @ instantiationService.js:61
_renderOutput @ cellOutput.js:484
(anonymous) @ cellOutput.js:458
_updateOutputs @ cellOutput.js:449
(anonymous) @ cellOutput.js:325
fire @ event.js:490
(anonymous) @ codeCellViewModel.js:50
fire @ event.js:490
spliceNotebookCellOutputs @ notebookCellTextModel.js:168
_spliceNotebookCellOutputs @ notebookTextModel.js:680
_doApplyEdits @ notebookTextModel.js:358
applyEdits @ notebookTextModel.js:272
$applyEdits @ mainThreadNotebookDocuments.js:142
_doInvokeHandler @ rpcProtocol.js:348
_invokeHandler @ rpcProtocol.js:333
_receiveRequest @ rpcProtocol.js:260
_receiveOneMessage @ rpcProtocol.js:188
(anonymous) @ rpcProtocol.js:69
fire @ event.js:490
fire @ ipc.net.js:375
_receiveMessage @ ipc.net.js:654
(anonymous) @ ipc.net.js:510
fire @ event.js:490
acceptChunk @ ipc.net.js:189
(anonymous) @ ipc.net.js:158
listener @ ipc.net.js:33
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
Show 8 more frames
event.js:378     at ScopedContextKeyService._updateParentChangeListener (file:///Users/jrieken/Code/vscode/out/vs/platform/contextkey/browser/contextKeyService.js:359:61)
    at new ScopedContextKeyService (file:///Users/jrieken/Code/vscode/out/vs/platform/contextkey/browser/contextKeyService.js:346:18)
    at ScopedContextKeyService.createScoped (file:///Users/jrieken/Code/vscode/out/vs/platform/contextkey/browser/contextKeyService.js:236:20)
    at new CellOutputElement (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:35:77)
    at InstantiationService._createInstance (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:90:20)
    at InstantiationService.createInstance (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:61:31)
    at CellOutputContainer._renderOutput (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:484:78)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:458:43
    at Array.forEach (<anonymous>)
    at CellOutputContainer._updateOutputs (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:449:39)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.js:325:22
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:490:38)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.js:50:42
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:490:38)
    at NotebookCellTextModel.spliceNotebookCellOutputs (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.js:168:42)
    at NotebookTextModel._spliceNotebookCellOutputs (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:680:18)
    at NotebookTextModel._doApplyEdits (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:358:34)
    at NotebookTextModel.applyEdits (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:272:22)
    at MainThreadNotebookDocuments.$applyEdits (file:///Users/jrieken/Code/vscode/out/vs/workbench/api/browser/mainThreadNotebookDocuments.js:142:27)
    at RPCProtocol._doInvokeHandler (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
    at RPCProtocol._invokeHandler (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
    at RPCProtocol._receiveRequest (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
    at RPCProtocol._receiveOneMessage (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:490:38)
    at BufferedEmitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
    at PersistentProtocol._receiveMessage (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
    at file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:510:83
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:490:38)
    at ProtocolReader.acceptChunk (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
    at file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.net.js:158:61
    at Socket.listener (file:///Users/jrieken/Code/vscode/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by rebornix** [comment]
We are not creating scoped context key service for cell output anymore.
