### ISSUE TITLE
Notebook run action not visible on Windows but visible on Mac

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#124768]
Trying to figure if this is native notebook bug or a jupyter extension bug. I'm currently trying capture the end to end experience for opening a notebook file in VS Code.

![image](https://user-images.githubusercontent.com/35271042/119859850-9bb60280-beca-11eb-9c22-d17d66f0e049.png)

1. Open VS Code with an empty data & extensions directory
2. Open a notebook file
3. Install the recommended extension (Jupyter)
4. Re-open file
5. Trust notebook
6. :bug: Run a cell, run action is not visible

However on macOS, the run actions DOES show up, so there is some weird behavior here:

![image](https://user-images.githubusercontent.com/35271042/119859892-a7092e00-beca-11eb-8ac5-86e7cc3e668d.png)

Python     2.7.15
Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎24/‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

Version: 1.57.0-insider (user setup)
Commit: 1082913dd012e21cc5f35a06f15c480ca447f67f
Date: 2021-05-27T06:55:24.593Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

cc @claudiaregio

**Comment by rchiodo** [comment]
I believe this is caused by the jupyter extension not returning the kernels yet. They should appear if you wait.

**Comment by IanMatthewHuff** [comment]
@misolori If you don't see the run button and kernel selections after a wait (look to see if during the wait the Python extension is trying to load that's the usual slowdown point) could you grab our logging info?

In vscode settings put Jupyter->Logging->Level to 'debug' and re-run the scenario. We then have a bunch of logging info in the Jupyter output window that we can look at to help debug.

**Comment by misolori** [comment]
I've left the window open for several minutes and nothing changed, don't see any progress in the status bar or anywhere else. Here are the logs when I re-run the scenario:

```json
Info 2021-05-27 09:21:58: Checking if notebook is trusted
Info 2021-05-27 09:21:58: Check if Notebook is Trusted, Class name = p, completed in 64ms, has a truthy return value, Return Value: true
Info 2021-05-27 09:21:58: notebook communications already initialized for editor file:///c%3A/Users/misolori/Documents/GitHub/notebooks/data-vizualization.ipynb
Info 2021-05-27 09:21:58: Attempting to start a server because of preload conditions ...
Info 2021-05-27 09:21:58: Find kernel spec, Class name = D, completed in 7ms, has a falsy return value, Arg 1: <Uri:c:\Users\misolori\Documents\GitHub\notebooks\data-vizualization.ipynb>, Arg 2: {"interpreter":{"hash":"0f3fc1f477b7b6e8a98505e87c3377c352684999b9cf604b9f6bec26ac37c02d"},"kernelspec":{"display_name":"Python 3.7.3 64-bit","language":"python","name":"python37364bit1b59b820878d42b59aebf362a9f522c1"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.2"},"metadata":{"interpreter":{"hash":"0f3fc1f477b7b6e8a98505e87c3377c352684999b9cf604b9f6bec26ac37c02d"}}}, Arg 3: {"_isCancelled":false,"_emitter":null}, Return Value: undefined
Error 2021-05-27 09:22:03: Failed to convert application/vnd.bokehjs_exec.v0+json output from a buffer object,  [SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at M (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:31338)
	at c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:32418
	at Array.reduceRight (<anonymous>)
	at R (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:32388)
	at Array.map (<anonymous>)
	at c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:27258
	at Object.t.createJupyterCellFromVSCNotebookCell (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:27307)
	at c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:229702
	at Array.map (<anonymous>)
	at l.getCellsWithId (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:229657)
	at y.getNotebookLines (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:52:461853)
	at y.checkNotebook (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:52:462803)
	at y.c.value (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:1:100537)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)]
Error 2021-05-27 09:22:03: Failed to convert application/vnd.bokehjs_exec.v0+json output from a buffer object,  [SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at M (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:31338)
	at c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:32418
	at Array.reduceRight (<anonymous>)
	at R (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:32388)
	at Array.map (<anonymous>)
	at c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:27258
	at Object.t.createJupyterCellFromVSCNotebookCell (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:27307)
	at c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:229702
	at Array.map (<anonymous>)
	at l.getCellsWithId (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:229657)
	at h.checkNotebook (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:90:154393)
	at h.c.value (c:\Users\misolori\code-profiles\ext\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:1:100537)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)]
```

**Comment by misolori** [comment]
Not sure if it was obvious by my repro steps + screenshots, but i specifically **did not install** the Python extension. This behavior differs from what I see on macOS.

**Comment by rchiodo** [comment]
The error you're showing sounds like this fix here:
https://github.com/microsoft/vscode-jupyter/commit/eeeaa6cc9a62b26749d3150043056d96ab80c1f4

What's your version of Jupyter Extension? Don should have fixed that with a release last night.

**Comment by IanMatthewHuff** [comment]
Looks like Miguel is on 855 so that should be current. From the log it's "from a buffer" not "to a buffer" so it would actually be the function above the fix from Don.

Miguel could you share out the file?

**Comment by misolori** [comment]
Yea I'm on `v2021.6.881596855`, [here's a link to the file i'm using](https://github.com/misolori/notebooks/blob/main/data-vizualization.ipynb).

**Comment by DonJayamanne** [comment]
@rchiodo @IanMatthewHuff the problem is the mime type `application/vnd.bokehjs_load.v0+json` didn't contain json data.  Looks like we'll need to inspect the data to see of it's json or not instead of just looking for the word json in mine type.

Eg if typeof data === object and object.keys(data).length > 0 or similar before we convert to bytes. And we might want to add some metadata that also take is that it's a real json so that we can deserialize it in renderer

**Comment by DonJayamanne** [comment]
Ie the bug is at our end in Jupyter extension

**Comment by IanMatthewHuff** [comment]
@DonJayamanne I agree. I'll look into it after the API renames. My only concern here is the following:

- The code for this error should catch and just return back empty, it shouldn't be a full crash from what I see. 
- Miguel is seeing the run button issue on Windows and not on Mac. Mime type issue should be present on either OS.

So I believe there is the mime issue that we need to resolve, but I believe that it's possibly a red herring for the run button issue. 

I'm on Mac so I'm not sure if I can verify myself. @misolori Apologies if we are asking too much here. But on windows with your repro steps do you also not see a run button if you open a notebook that is blank or has no output in it? Just tying to isolate if there is one issue here (mime issue) or two (mime issue + windows issue with loading controllers).
