### ISSUE TITLE
Dev Container: port forwarding throws error

### ISSUE THREAD

**Issue by azazdeaz** [microsoft/vscode#124845]
Issue Type: <b>Bug</b>

Hi There,

When I try to forward a port it throws:
`TypeError: Cannot read property 'port' of null`

Steps A:
1. on the ports tab click "Forward a Port"
2. type in a number and press enter
Nothing happens. In the developer console it throws:
```sh
remoteExplorerService.ts:890 setting edit [object Object]
remoteExplorerService.ts:890 setting edit null
log.ts:296   ERR Cannot read property 'port' of null: TypeError: Cannot read property 'port' of null
    at m.waitForReady (file:///snap/code-insiders/724/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2844:1471)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async P.forward (file:///snap/code-insiders/724/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:26348)
```

Steps B:
1. add a `"forwardPorts": [1234]` field to the devcontainer.json
2. run "Reopen in Container" 
<details>
<summary>logs</summary>
<pre>
[59 ms] Remote-Containers 0.180.0 in VS Code 1.57.0-insider (a18ea9c9ec25c59e599ba3c2eb668315546dd269).
[58 ms] Start: Resolving Remote
[67 ms] Setting up container for folder or workspace: /home/azazdeaz/repos/test/python-slam-test
[69 ms] Start: Check Docker is running
[70 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[115 ms] Server API version: 1.41
[123 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/azazdeaz/repos/test/python-slam-test --filter label=vsch.quality=insider
[157 ms] Start: Run: docker inspect --type image azazdeaz/gb
[194 ms] Start: Run: docker -v
[228 ms] Start: Run: docker events --format {{json .}} --filter event=start
[232 ms] Start: Starting container
[232 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=/home/azazdeaz/repos/test/python-slam-test,target=/catkin_ws/src/,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/home/azazdeaz/repos/test/python-slam-test -l vsch.quality=insider -l vsch.remote.devPort=0 -e DISPLAY -e QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/localtime:/etc/localtime:ro -v /dev/input:/dev/input --rm --privileged --runtime=nvidia --entrypoint /bin/sh azazdeaz/gb -c echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done
Container started
[749 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/azazdeaz/repos/test/python-slam-test --filter label=vsch.quality=insider
[836 ms] Start: Run: docker inspect --type container 053a4935e1e5
[912 ms] Start: Inspecting container
[912 ms] Start: Run: docker inspect --type container 053a4935e1e58910a80bbaffd533af77d74c472760bbc573353fd8770949aee3
[965 ms] Start: Run in container: /bin/sh
[971 ms] Start: Run in container: uname -m
[1069 ms] x86_64
[1069 ms] 
[1069 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1080 ms] NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[1080 ms] 
[1081 ms] Start: Run in container: cat /etc/passwd
[1083 ms] Start: Updating configuration state
[1086 ms] Start: Setup shutdown monitor
[1087 ms] Forking shutdown monitor: /home/azazdeaz/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.180.0/dist/shutdown/shutdownMonitorProcess /run/user/1000/vscode-remote-containers-5d59339633214b8213025586b20c532dfe37a57c.sock singleContainer Debug /home/azazdeaz/.config/Code - Insiders/logs/20210526T191028/exthost7/ms-vscode-remote.remote-containers 1622216012933
[1092 ms] Start: Run in container: test -d /root/.vscode-server-insiders
[1093 ms] 
[1093 ms] 
[1093 ms] Exit code 1
[1094 ms] Start: Run in container: test -d /root/.vscode-remote
[1095 ms] 
[1095 ms] 
[1095 ms] Exit code 1
[1095 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.patchEtcProfileMarker' ; } 2> /dev/null
[1098 ms] 
[1098 ms] 
[1098 ms] Start: Run in container: sed -i -E 's/((^|\s)PATH=)([^\$]*)$/\1${PATH:-\3}/g' /etc/profile || true
[1101 ms] 
[1101 ms] 
[1102 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[1103 ms] 
[1103 ms] 
[1104 ms] Start: Run in container: mkdir -p '/root/.vscode-server-insiders/data/Machine' && cat >'/root/.vscode-server-insiders/data/Machine/settings.json' <<'settingsJSON'
[1106 ms] 
[1106 ms] 
[1106 ms] Start: Run in container: test -d /root/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269
[1107 ms] 
[1108 ms] 
[1108 ms] Exit code 1
[1108 ms] Start: Run in container: test -d /vscode/vscode-server-insiders/bin/x64/a18ea9c9ec25c59e599ba3c2eb668315546dd269-insider
[1109 ms] 
[1109 ms] 
[1109 ms] Start: Run in container: mkdir -p '/root/.vscode-server-insiders/bin' && ln -s '/vscode/vscode-server-insiders/bin/x64/a18ea9c9ec25c59e599ba3c2eb668315546dd269-insider' '/root/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269'
[1112 ms] 
[1112 ms] 
[1112 ms] Start: Run in container: touch '/vscode/vscode-server-insiders/bin/x64/a18ea9c9ec25c59e599ba3c2eb668315546dd269-insider'
[1113 ms] Start: Launching Remote-Containers helper.
[1114 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[1119 ms] 
[1119 ms] 
[1120 ms] /run/user/1000/gnupg/S.gpg-agent.extra
[1120 ms] 
[1121 ms] Start: Run in container: gpgconf --list-dir agent-socket
[1122 ms] /root/.gnupg/S.gpg-agent
[1122 ms] 
[1123 ms] Start: Run in container: gpgconf --list-dir homedir
[1126 ms] /root/.gnupg
[1126 ms] 
[1126 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[1128 ms] 
[1128 ms] 
[1128 ms] Exit code 2
[1129 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[1130 ms] userEnvProbe: loginInteractiveShell (default)
[1131 ms] 
[1131 ms] 
[1131 ms] Start: Run: gpgconf --list-dir homedir
[1136 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-fb5c6fa3838f23ab5d3725fb43bb1b5d47fe3e65.js' >/tmp/vscode-remote-containers-fb5c6fa3838f23ab5d3725fb43bb1b5d47fe3e65.js
[1137 ms] /home/azazdeaz/.gnupg
[1137 ms] 
[1138 ms] 
[1138 ms] 
[1138 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[1140 ms] 
[1140 ms] 
[1140 ms] Start: Run in container: gpgconf --list-dir homedir
[1142 ms] /root/.gnupg
[1142 ms] 
[1142 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-fb5c6fa3838f23ab5d3725fb43bb1b5d47fe3e65.js' >/tmp/vscode-remote-containers-server-fb5c6fa3838f23ab5d3725fb43bb1b5d47fe3e65.js
[1144 ms] 
[1145 ms] 
[1145 ms] Start: Run in container: # Copy /home/azazdeaz/.ssh/known_hosts to /root/.ssh/known_hosts
[1145 ms] Start: Run in container: /root/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269/node /tmp/vscode-remote-containers-server-fb5c6fa3838f23ab5d3725fb43bb1b5d47fe3e65.js
[1156 ms] 
[1156 ms] 
[1156 ms] Start: Run in container: # Test for /root/.gnupg/pubring.kbx and gpg
[1158 ms] 
[1158 ms] 
[1159 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { /root/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269/node /tmp/vscode-remote-containers-fb5c6fa3838f23ab5d3725fb43bb1b5d47fe3e65.js $*; }; f' || true
[1161 ms] 
[1161 ms] 
[1161 ms] Start: Run in container: # Copy /home/azazdeaz/.gnupg/pubring.kbx to /root/.gnupg/pubring.kbx
[1162 ms] Start: Preparing Extensions
[1164 ms] 
[1164 ms] 
[1164 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[1166 ms] 
[1166 ms] 
[1166 ms] Start: Run in container: # Test for /root/.gnupg/trustdb.gpg and gpg
[1170 ms] Extensions cache, install extensions: ms-python.python, ms-vscode.cmake-tools, ms-vscode.cpptools
[1171 ms] 
[1171 ms] 
[1171 ms] Start: Run in container: test -d /root/.vscode-server-insiders/extensionsCache && ls /root/.vscode-server-insiders/extensionsCache || true
[1172 ms] 
[1172 ms] 
[1172 ms] Start: Run in container: # Copy /home/azazdeaz/.gnupg/trustdb.gpg to /root/.gnupg/trustdb.gpg
[1174 ms] 
[1175 ms] 
[1175 ms] Start: Run in container: test -d /vscode/vscode-server-insiders/extensionsCache && ls /vscode/vscode-server-insiders/extensionsCache || true
[1175 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[1180 ms] eamodio.gitlens-11.4.0
eamodio.gitlens-11.4.1
huber-baste.msgpack-0.0.7
ms-python.python-2021.3.680753044
ms-python.python-2021.4.765268190
ms-python.python-2021.5.829140558
ms-python.python-2021.5.842923320
ms-python.vscode-pylance-2021.5.1
ms-python.vscode-pylance-2021.5.3
ms-python.vscode-pylance-2021.5.4
ms-toolsai.jupyter-2021.4.641214696
ms-toolsai.jupyter-2021.5.685944597
ms-toolsai.jupyter-2021.5.689556049
ms-toolsai.jupyter-2021.5.697286501
ms-toolsai.jupyter-2021.5.702919634
ms-toolsai.jupyter-2021.6.718745073
ms-toolsai.jupyter-2021.6.723987413
ms-toolsai.jupyter-2021.6.728949111
ms-toolsai.jupyter-2021.6.732501275
ms-toolsai.jupyter-2021.6.740555125
ms-toolsai.jupyter-2021.6.744171703
ms-toolsai.jupyter-2021.6.747718990
ms-toolsai.jupyter-2021.6.751425733
ms-toolsai.jupyter-2021.6.755784270
ms-toolsai.jupyter-2021.6.770087802
ms-toolsai.jupyter-2021.6.773625886
ms-toolsai.jupyter-2021.6.777186939
ms-toolsai.jupyter-2021.6.780948196
ms-toolsai.jupyter-2021.6.788523236
ms-toolsai.jupyter-2021.6.790799743
ms-toolsai.jupyter-2021.6.794159387
ms-toolsai.jupyter-2021.6.795492900
ms-toolsai.jupyter-2021.6.811652604
ms-toolsai.jupyter-2021.6.819764235
ms-toolsai.jupyter-2021.6.828932339
ms-toolsai.jupyter-2021.6.831144556
ms-toolsai.jupyter-2021.6.870847776
ms-toolsai.jupyter-2021.6.881596855
ms-toolsai.jupyter-2021.6.885080120
ms-vscode.cmake-tools-1.6.0
ms-vscode.cmake-tools-1.7.0
ms-vscode.cmake-tools-1.7.1
ms-vscode.cmake-tools-1.7.2
ms-vscode.cmake-tools-1.7.3
ms-vscode.cpptools-1.2.2
ms-vscode.cpptools-1.3.0
ms-vscode.cpptools-1.3.1
ms-vscode.cpptools-1.4.0
twxs.cmake-0.0.17
[1180 ms] 
[1181 ms] Extensions cache, link in container: ms-python.python-2021.3.680753044, ms-python.python-2021.4.765268190, ms-python.python-2021.5.829140558, ms-python.python-2021.5.842923320, ms-vscode.cmake-tools-1.6.0, ms-vscode.cmake-tools-1.7.0, ms-vscode.cmake-tools-1.7.1, ms-vscode.cmake-tools-1.7.2, ms-vscode.cmake-tools-1.7.3, ms-vscode.cpptools-1.2.2, ms-vscode.cpptools-1.3.0, ms-vscode.cpptools-1.3.1, ms-vscode.cpptools-1.4.0
[1181 ms] Start: Run in container: mkdir -p '/root/.vscode-server-insiders/extensionsCache' && ln -s '/vscode/vscode-server-insiders/extensionsCache'/* '/root/.vscode-server-insiders/extensionsCache' || true
[1184 ms] 
[1184 ms] 
[1185 ms] Start: Run in container: cd /vscode/vscode-server-insiders/extensionsCache && touch 'ms-python.python-2021.3.680753044' 'ms-python.python-2021.4.765268190' 'ms-python.python-2021.5.829140558' 'ms-python.python-2021.5.842923320' 'ms-vscode.cmake-tools-1.6.0' 'ms-vscode.cmake-tools-1.7.0' 'ms-vscode.cmake-tools-1.7.1' 'ms-vscode.cmake-tools-1.7.2' 'ms-vscode.cmake-tools-1.7.3' 'ms-vscode.cpptools-1.2.2' 'ms-vscode.cpptools-1.3.0' 'ms-vscode.cpptools-1.3.1' 'ms-vscode.cpptools-1.4.0'
[1190 ms] 
[1190 ms] 
[1191 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[1233 ms] Start: Starting VS Code Server
[1233 ms] Start: Run in container: /root/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269/server.sh --log debug --force-disable-user-env --use-host-proxy --port 0 --extensions-download-dir /root/.vscode-server-insiders/extensionsCache --install-extension ms-python.python --install-extension ms-vscode.cmake-tools --install-extension ms-vscode.cpptools --start-server
[1394 ms] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 42341

[1395 ms] Start: Run in container: echo 42341 >/root/.vscode-server-insiders/data/Machine/.devport
[1397 ms] 
[1397 ms] 
</pre></details>
```sh
[1398 ms] Port forwarding for container port 42341 starts listening on local port.
[1398 ms] Port forwarding local port 42341 to container port 42341
[1404 ms] userEnvProbe PATHs:
Probe:     '/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Container: '/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[1412 ms] TypeError: Cannot read property 'port' of null
    at m.waitForReady (file:///snap/code-insiders/724/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2844:1471)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async P.forward (file:///snap/code-insiders/724/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:26348)
    at async S.$openTunnel (file:///snap/code-insiders/724/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:35965)
```

It was working perfectly earlier. I think it started behaving like this after I updated the `forwardPorts` field in the `devcontainers.json`. Now I have no idea how to get it working again.

Thanks for your help!

VS Code version: Code - Insiders 1.57.0-insider (a18ea9c9ec25c59e599ba3c2eb668315546dd269, 2021-05-26T05:15:29.995Z)
OS version: Linux x64 5.8.0-53-generic snap
Remote OS version: Linux arm 5.10.17-v7l+
Remote OS version: Linux x64 5.8.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|15.52GB (0.17GB free)|
|Process Argv|--force-user-env --unity-launch --crash-reporter-id 922a379c-5993-4d2e-b825-5608950d619c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.50.234|
|OS|Linux arm 5.10.17-v7l+|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 600)|
|Memory (System)|1.77GB (1.06GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 5.8.0-53-generic|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3400)|
|Memory (System)|15.52GB (0.17GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
remote-containers|ms-|0.179.0
remote-ssh|ms-|0.65.6
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.3
vscode-remote-extensionpack|ms-|0.21.0
proto|pet|0.0.2
material-icon-theme|PKi|4.7.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.885080120
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by azazdeaz** [comment]
And, with the new version, it just started working again :D
Thanks for your work! :clap: :heart:

Version: 1.57.0-insider
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:51:40.777Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-53-generic snap
