### ISSUE TITLE
Proposed API checks fail due to nullExtensionDescription when symlinks (`npm link`) is used (doc needed?)

### ISSUE THREAD

**Issue by sam-mccall** [microsoft/vscode#124820]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
```
Version: 1.57.0-insider
Commit: 1082913dd012e21cc5f35a06f15c480ca447f67f
Date: 2021-05-27T06:55:34.773Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.28-1rodete1-amd64
```
- OS Version:
Debian-derived (non-public)

Use case here is wanting to modify an extension + an npm package it depends on.
In my case, modified vscode-clangd extension with modified vscode-languageclient package.

Steps to Reproduce:
1. Clone extension ([vscode-clangd](https://github.com/clangd/vscode-clangd)) and library ([vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node)) and install dependencies.
2. Link vscode-clangd to the checked-out vscode-languageclient in the vscode-languageserver-node repo: `cd ~/src/vscode-languageserver-node/client; npm link; cd ~/src/vscode-clangd; npm link vscode-languageclient`. This creates a symlink `~/src/vscode-clangd/node_modules/vscode-languageclient --> ~/src/vscode-languageserver-node/client`.
3. Modify the extension to use proposed API indirectly via the vscode-languageclient package (e.g. call `client.registerProposedFeatures()` on the language client)
4. Add `enableProposedApi` to the extension's package.json & run under the extension debugger in VSCode Insiders.
5. Extension fails to activate due to failed proposed-API check.

Error message:
```
Activating extension 'llvm-vs-code-extensions.vscode-clangd' failed: [nullExtensionDescription]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api nullExtensionDescription.
```

Relevant extension host log:
```
[2021-05-28 10:27:30.556] [exthost] [error] Activating extension llvm-vs-code-extensions.vscode-clangd failed due to an error:
[2021-05-28 10:27:30.556] [exthost] [error] Error: [nullExtensionDescription]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api nullExtensionDescription
	at p (/home/sammccall/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:78741)
	at d (/home/sammccall/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:78688)
	at Object.get openEditors [as openEditors] (/home/sammccall/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:32523)
	at openEditorsHandler (/home/sammccall/src/vscode-languageserver-node/client/lib/common/proposed.diagnostic.js:36:48)
	at new EditorTracker (/home/sammccall/src/vscode-languageserver-node/client/lib/common/proposed.diagnostic.js:40:9)
	at new DiagnosticFeature (/home/sammccall/src/vscode-languageserver-node/client/lib/common/proposed.diagnostic.js:371:30)
	at Object.createAll (/home/sammccall/src/vscode-languageserver-node/client/lib/common/commonClient.js:59:13)
	at ClangdLanguageClient.registerProposedFeatures (/home/sammccall/src/vscode-languageserver-node/client/lib/common/commonClient.js:28:48)
	at ClangdContext.<anonymous> (/home/sammccall/src/vscode-clangd/out/src/clangd-context.js:138:25)
	at Generator.next (<anonymous>)
	at fulfilled (/home/sammccall/src/vscode-clangd/out/src/clangd-context.js:5:58)
```

Per discussion of #118812 and #118562 the proposed-API permission check uses a lookup based on the path of the source file, and `realpath()` is used, so the symlinks are lost and VSCode loses track of the fact that `vscode-languageclient`was loaded as part of this extension. Thus "nullExtensionDescription" appears rather than the actual extension name, which was the only hint what was going wrong here.

I have no idea if a different mechanism is feasible. If not maybe this limitation could be documented. This is a standard workflow when working with npm libraries, from the outside it wasn't obvious what was going wrong or how to debug, and the error messages were misleading.

**Comment by sam-mccall** [comment]
(I've set up webpack and confirmed this fixes the problem with no other changes to the extension or way i'm launching it)
