### ISSUE TITLE
Mac OS Smoke test failures 

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#124811]
In today Insider build a lot of Mac OS smoke tests failed all with 

```
Error: Active element not found. Current active element is 'HTML > BODY.mac > DIV.monaco-workbench.mac.chromium.nopanel.file-icons-enabled.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-dialog-modal-block.dimmed > DIV.dialog-shadow > DIV.monaco-dialog-box > DIV.dialog-buttons-row > DIV.dialog-buttons.centered > A.monaco-button.monaco-description-button.monaco-text-button'. Looking for .quick-input-widget .quick-input-box input
    at w.isActiveElement (file:///Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:570:85418)
    at t.call (file:///Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:570:87456)
    at E.onPromise (file:///Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:75:66129)
    at E.onRawMessage (file:///Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:75:65488)
    at file:///Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:75:64741
    at o.fire (file:///Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at EventEmitter.W (file:///Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:60805)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:121:1082)
```

The build is here: 

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=120711&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

I will rerun the test to see if this is a hick-up or a general problem.

**Comment by dbaeumer** [comment]
Seems related to https://github.com/microsoft/vscode/issues/124674.

Assigning some owners.
