### ISSUE TITLE
website not responding

### ISSUE THREAD

**Issue by Ankit17028** [microsoft/vscode#124959]
We have written the ne
Issue Type: <b>Bug</b>

Traceback (most recent call last):
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1867, in handle_exception      
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request 
    rv = self.handle_user_exception(e)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception 
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request 
    rv = self.dispatch_request()
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1936, in dispatch_request      
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Ankit\Desktop\TypingDNA-Implementation-main\TypingDNA Starter Code\website\auth.py", line 12, in api_login        
    user = User.query.filter_by(email=email).first()
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\orm\query.py", line 2750, in first      
    return self.limit(1)._iter().first()
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\orm\query.py", line 2834, in _iter      
    result = self.session.execute(
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\orm\session.py", line 1677, in execute  
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\sql\elements.py", line 320, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_    
    raise exception
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.typing_id
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.typing_id AS user_typing_id        
FROM user
WHERE user.email = ?
 LIMIT ? OFFSET ?]
[parameters: ('ankitbansod2000@gmail.com', 1, 0)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
127.0.0.1 - - [31/May/2021 11:33:28] "GET /sign-up HTTP/1.1" 200 -

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (0.97GB free)|
|Process Argv|--crash-reporter-id 011c2fc8-d8c2-4e91-91a7-df06e9fbcee2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.4
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.4.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

eded data into your clipboard because it was too large to send. Please paste.

**Comment by dbaeumer** [comment]
This looks like a problem with Python.
