### ISSUE TITLE
Latest update frequently "not responding; force quit" (reopening of #122659)

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#125411]
Does this issue occur when all extensions are disabled?: I don't know. Since it doesn't happen right away, I cannot afford to sit and wait while I cannot use VS Code due to having no extensions installed.

This is a re-reporting of #122659 since my requests there are being ignored.

This is still happening.  I have to force-quit Code many times a day.  https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues does not seem relevant as it's not a crash.  It's a hang.

**Comment by brianjmurrell** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Latest update frequently "not responding; force quit" (#122659)](https://www.github.com/microsoft/vscode/issues/122659)

It is, but that issue is closed and not getting any more attention including a request to reopen it.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by brianjmurrell** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

I have code-insiders-1.57.0-1622700756.el8.x86_64 installed on my Fedora 33 machine, and I tried to use it, but it shares none of the configuration from the non-insiders installation.  That means it has none of my extensions, settings, etc., which pretty much puts it in the same category as the question "Does this issue occur when all extensions are disabled?".  It's not practically usable due to the lack of tools extensions and settings.

Surely there has got to be a more concrete method of debugging this than just trying other builds, yes?

**Comment by bpasero** [comment]
@brianjmurrell you can get there via settings sync easily: https://code.visualstudio.com/docs/editor/settings-sync

**Comment by brianjmurrell** [comment]
@bpasero Interesting.  I didn't know about that.  However on trying to enable it on stable I got an error:

```
[2021-06-04 04:54:08.554] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2021-06-04 04:54:08.554] [settingssync] [info] Auto Sync is disabled.
[2021-06-04 05:16:02.486] [settingssync] [info] Did reset the local sync state.
[2021-06-04 05:16:03.302] [settingssync] [info] Settings: Updated remote settings
[2021-06-04 05:16:03.306] [settingssync] [info] Settings: Updated last synchronized settings
[2021-06-04 05:16:03.403] [settingssync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/keybindings","status":409,"execution-id":"771da02f-7ebc-4ba3-bd14-80bb24975f8b","operation-id":"6c49e6b40f734af98b20d261c4d0a1a4"}
[2021-06-04 05:16:03.404] [settingssync] [error] Conflict (UserDataSyncError) syncResource:unknown operationId:6c49e6b40f734af98b20d261c4d0a1a4: POST request 'https://vscode-sync.trafficmanager.net/v1/resource/keybindings' failed because of Conflict (409). There is new data for this resource. Make the request again with latest data.
    at d.request (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:189508)
    at async d.write (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:186533)
    at async D.updateRemoteUserData (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:64166)
    at async D.applyResult (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:97166)
    at async D.doApply (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:58731)
    at async D.apply (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:52785)
    at async r.apply (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:165915)
    at async T.call (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:171637)
[2021-06-04 05:16:03.413] [settingssync] [info] Keybindings: Stopped synchronizing keybindings.
[2021-06-04 05:16:03.414] [settingssync] [info] Snippets: Stopped synchronizing snippets.
[2021-06-04 05:16:03.417] [settingssync] [info] GlobalState: Stopped synchronizing globalstate.
[2021-06-04 05:16:03.421] [settingssync] [info] Extensions: Stopped synchronizing extensions
```

I tried a second time and it told me I synced from a different machine (which I didn't of course) and that I needed to merge settings.  I did that and then turned it on again.  Seems maybe it's working this time.

Seems I got insiders settings synced.  Neat.  I will try this build and report back.

**Comment by bpasero** [comment]
Thanks 👍

**Comment by brianjmurrell** [comment]
ARE YOU KIDDING ME?  IT'S BEEN A WHOLE TOTAL OF EIGHT DAYS SINCE I OPENED THIS ISSUE AND IT'S BEING CLOSED ALREADY?  HOW ABOUT GIVING SOME REASONABLE AMOUNT OF TIME TO TRY TO REPRODUCE AN ISSUE!?!?!?

NOT EVERY ISSUE IS REPRODUCIBLE IN 1 HOUR.

VERY ANNOYING!
