### ISSUE TITLE
Unit tests fail when ran from source on my Windows 10 machine

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125559]
* `scripts\test.bat`
```
  6921 passing (1m)
  43 pending
  3 failing

  1) Workbench - TerminalProfiles
       detectAvailableProfiles
         should allow source to have args:

      AssertionError [ERR_ASSERTION]: Actual:
Expected: PowerShell
      + expected - actual

      -0
      +1

      at profilesEqual (file:///C:/Alex/src/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:13:18)
      at Context.<anonymous> (file:///C:/Alex/src/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:67:21)

  2) Workbench - TerminalProfiles
       detectAvailableProfiles
         pwsh source detection/fallback
           should prefer pwsh 7 to Windows PowerShell:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'
- 'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
      + expected - actual

      -C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      +C:\Program Files\PowerShell\7\pwsh.exe

      at profilesEqual (file:///C:/Alex/src/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:18:22)
      at Context.<anonymous> (file:///C:/Alex/src/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:110:25)

  3) Workbench - TerminalProfiles
       detectAvailableProfiles
         pwsh source detection/fallback
           should prefer pwsh 7 to pwsh 6:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'
- 'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
      + expected - actual

      -C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      +C:\Program Files\PowerShell\7\pwsh.exe

      at profilesEqual (file:///C:/Alex/src/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:18:22)
      at Context.<anonymous> (file:///C:/Alex/src/vscode/out/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.js:124:25)



errorlevel: 1
```

**Comment by Tyriar** [comment]
Can repro, reopening https://github.com/microsoft/vscode/issues/124257
