### ISSUE TITLE
Timeout of install and enable vscode-smoketest-check extension on web

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#125555]
```
PS C:\Users\merogge\repos\vscode> yarn smoketest --build C:\server\vscode-server-win32-x64-web --web --browser chromium
yarn run v1.22.10
$ cd test/smoke && yarn compile && node test/index.js --build C:\server\vscode-server-win32-x64-web --web --browser chromium
$ yarn --cwd ../automation compile && tsc
$ npm run copy-driver && npm run copy-driver-definition && tsc

> vscode-automation@1.54.0 copy-driver C:\Users\merogge\repos\vscode\test\automation
> cpx src/driver.js out/


> vscode-automation@1.54.0 copy-driver-definition C:\Users\merogge\repos\vscode\test\automation
> node tools/copy-driver-definition.js

Running web smoke tests against C:\server\vscode-server-win32-x64-web


*** Test data: C:\Users\merogge\AppData\Local\Temp\t89241XJIvyY4iV0Y
*** Preparing smoketest setup...
*** Cloning test project repository...
*** Running yarn...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
*** Smoketest setup done!

  VSCode Smoke Tests (Web)
    VSCode Smoke Tests (Web)
Starting built server from 'C:\server\vscode-server-win32-x64-web\server.cmd'
Server stdout: 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 8000


Server stderr: Ignoring option browser: not supported for server.

Server stdout: Web UI available at http://localhost:8000/?tkn=24b4a29c-136a-46cf-9d3a-b8015abbd94f

Server stdout: [12:49:46] Extension host agent started.

Server stdout: [12:49:49] [::1][93e28eb9][ManagementConnection] New connection established.

Server stdout: [12:49:51] [::1][91fb8de6][ExtensionHostConnection] New connection established.

Server stdout: [12:49:51] [::1][91fb8de6][ExtensionHostConnection] <17440> Launched Extension Host Process.

      Search
        - has a tooltp with a keybinding
        √ searches for body & checks for correct result number
        √ searches only for *.js files & checks for correct result number
        - dismisses result & checks for correct result number
        √ replaces first search result with a replace term
      Quick Access
        √ quick access search produces correct result
        √ quick access respects fuzzy matching
      Notebooks
        - moves focus in and out of output
        - cell action execution
      Language Features
        √ verifies quick outline
        √ verifies problems view
        √ verifies settings
      Editor
        √ shows correct quick outline
      Statusbar
        √ verifies presence of all default status bar elements
        √ verifies that 'quick input' opens when clicking on status bar elements
        √ verifies that 'Problems View' appears when clicking on 'Problems' status element
        √ verifies that 'Tweet us feedback' pop-up appears when clicking on 'Feedback' icon
        √ checks if 'Go to Line' works if called from the status bar
        √ verifies if changing EOL is reflected in the status bar
      Extensions
Server stdout: [12:50:16] Installing extension: michelkaporin.vscode-smoketest-check

Server stdout: [12:50:17] Downloaded extension: michelkaporin.vscode-smoketest-check c:\Users\merogge\AppData\Local\Temp\t89241XJIvyY4iV0Y\d\data\CachedExtensionVSIXs\michelkaporin.vscode-smoketest-check-0.0.1

Server stdout: [12:50:17] Extracted extension to C:\Users\merogge\AppData\Local\Temp\t89241XJIvyY4iV0Y\extensions-dir\.0a8f15be-37ba-4836-9622-e0631d06944c: michelkaporin.vscode-smoketest-check

Server stdout: [12:50:17] Renamed to C:\Users\merogge\AppData\Local\Temp\t89241XJIvyY4iV0Y\extensions-dir\michelkaporin.vscode-smoketest-check-0.0.1

Server stdout: [12:50:17] Installation completed. michelkaporin.vscode-smoketest-check

Server stdout: [12:50:17] Extensions installed successfully: michelkaporin.vscode-smoketest-check

        1) install and enable vscode-smoketest-check extension
Server stdout: [12:51:15] [::1][93e28eb9][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.



  15 passing (2m)
  4 pending
  1 failing

  1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Extensions
           install and enable vscode-smoketest-check extension:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\merogge\repos\vscode\test\smoke\out\main.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)



error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\merogge\repos\vscode> 
```

**Comment by sandy081** [comment]
Seems to be running fine now.
