### ISSUE TITLE
Cannot read property 'scheme' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125518]
In latest insiders:
* make changes to a image file (`pic1.png`)
* click on the change in the SCM view

```
Cannot read property 'scheme' of undefined: TypeError: Cannot read property 'scheme' of undefined
    at Object.v [as globMatchesResource] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1518:40455)
    at ai.findMatchingContributions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2309:13634)
    at ai.doHandleConflictingDefaults (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2309:15883)
    at ai.resolveEditorOverride (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2309:11785)
    at async x.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2518:25078)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2470:44765
```

**Comment by bpasero** [comment]
This looks like a ESBuild minification issue to me. Here is the original source code with a `return` when the editor is `DiffEditorInput`:

https://github.com/microsoft/vscode/blob/bcdfe884a3c1ffd4f795d19eb86657bb96050722/src/vs/workbench/services/editor/browser/editorOverrideService.ts#L303-L309

And here the minified code where the `return` is hit but the method does not exit:

![image](https://user-images.git@joaomoreno ercontent.com/900690/120820848-3068d200-c555-11eb-8beb-5467e874ecd8.png)

//cc @joao

**Comment by alexdima** [comment]
@bpasero maybe you can report this against `esbuild`. They are incredibly responsive.

**Comment by bpasero** [comment]
I bet this is fixed by this https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0122

**Comment by lramos15** [comment]
Just bumped the esbuild to the latest version. Will update this issue if that fixes the error.

**Comment by lramos15** [comment]
Updating to esbuild 0.12.6 didn't seem to solve the issue.

**Comment by lramos15** [comment]
Upstream issue filed https://github.com/evanw/esbuild/issues/1350
