### ISSUE TITLE
TS Server fatal error:  Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames

### ISSUE THREAD

**Issue by WickedWizard3588** [microsoft/vscode#125677]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames
    at getTextOfPropertyName (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:14198:33)
    at /snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:14740:32
    at Array.filter (<anonymous>)
    at getPropertyAssignment (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:14738:41)
    at getTsConfigPropArray (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:14772:36)
    at Object.getTsConfigPropArrayElementValue (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:14763:32)
    at fileIncludeReasonToRelatedInformation (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108616:41)
    at processReason (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108556:58)
    at Array.forEach (<anonymous>)
    at createDiagnosticExplainingFile (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108536:91)
    at /snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106596:51
    at Array.forEach (<anonymous>)
    at Object.createProgram (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106593:121)
    at synchronizeHostData (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149086:26)
    at Proxy.getProgram (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149178:13)
    at ConfiguredProject.Project.updateGraphWorker (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154091:53)
    at ConfiguredProject.Project.updateGraph (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154021:42)
    at ConfiguredProject.updateGraph (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:154993:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156743:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157684:44)
    at /snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158024:97
    at Object.flatMap (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:158024:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159079:46)
    at /snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160963:88
    at IOSession.Session.executeWithRequestId (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160954:28)
    at IOSession.Session.executeCommand (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160963:33)
    at IOSession.Session.onMessage (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160989:35)
    at Interface.<anonymous> (/snap/code/65/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:163650:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-55-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 2, 1|
|Memory (System)|7.66GB (1.16GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch /mnt/Data Files/Chintu/Coding/Javascript/Private/Xyborg --no-sandbox --crash-reporter-id 02673f44-714a-4c31-989b-590ec6be4020|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
inf|bag|0.0.1
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
auto-rename-tag|for|0.1.6
codespaces|Git|0.10.5
vscode-pull-request-github|Git|0.26.0
go|gol|0.25.1
beautify|Hoo|1.5.0
discord-vscode|icr|5.6.3
reg|ion|1.0.3
l13-built-in-extensions|L13|0.13.1
vscode-language-babel|mgm|0.0.31
mongodb-vscode|mon|0.5.0
vscode-docker|ms-|1.13.0
remote-containers|ms-|0.177.2
remote-wsl|ms-|0.56.4
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
material-product-icons|PKi|1.0.4
vscode-thunder-client|ran|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
LiveServer|rit|5.6.1
yagpdb-cc|Spe|1.1.2
vscode-choosealicense|ult|0.4.0
vscode-wakatime|Wak|12.0.0
txt-syntax|xsh|0.1.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehovct:30309550
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by WickedWizard3588** [comment]
Issue created by mistake by VSCode, sorry for the inconveinence
