### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by javadbat** [microsoft/vscode#125732]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure.
    at getDisplayName (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40464:129)
    at a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40572:102
    at Object.forEach (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:190:30)
    at declareSymbol (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40570:28)
    at bindPotentiallyNewExpandoMemberToNamespace (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43015:13)
    at bindPropertyAssignment (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43026:13)
    at bindStaticPropertyAssignment (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42950:13)
    at bindSpecialPropertyAssignment (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42940:17)
    at bindWorker (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42482:29)
    at bind (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42343:13)
    at bindExpressionStatement (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41367:13)
    at bindChildren (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40831:21)
    at bind (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42354:21)
    at a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40767:94
    at Object.forEach (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:190:30)
    at bindEach (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40774:16)
    at bindEachFunctionsFirst (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40767:13)
    at bindChildren (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40878:21)
    at bindContainer (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40724:17)
    at bind (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42357:21)
    at bindSourceFile (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40329:17)
    at Object.bindSourceFile (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40266:9)
    at initializeTypeChecker (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:79478:20)
    at Object.createTypeChecker (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44420:9)
    at Object.getTypeChecker (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107156:79)
    at synchronizeHostData (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149096:21)
    at Proxy.getProgram (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149178:13)
    at InferredProject.Project.updateGraphWorker (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154091:53)
    at InferredProject.Project.updateGraph (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154021:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156193:25)
    at ProjectService.assignProjectToOpenedScriptInfo (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157750:26)
    at a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158024:97
    at Object.flatMap (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158024:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159079:46)
    at a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160963:88
    at IOSession.Session.executeWithRequestId (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160954:28)
    at IOSession.Session.executeCommand (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160963:33)
    at IOSession.Session.onMessage (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160989:35)
    at Interface.<anonymous> (a:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:163650:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (6.10GB free)|
|Process Argv|--crash-reporter-id 2b722e70-48c0-4307-8d0f-1f80d57136d2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.4
project-manager|ale|12.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
npm-intellisense|chr|1.3.1
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.42.0
vscode-eslint|dba|2.1.20
git-extension-pack|don|0.1.3
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.4.1
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.22
vscode-solution-explorer|fer|0.4.3
vscode-drawio|hed|1.4.0
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
search-node-modules|jas|1.3.0
csharpextensions|jch|1.3.1
svg|joc|1.4.6
docthis|joe|0.7.1
vscode-icon-theme|jtl|1.6.6
efcore-snippets|jul|0.0.5
vscode-github|Kni|0.30.6
sln-support|log|0.0.1
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
node-debug2|ms-|1.42.7
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.7.0
drawio-preview|pur|0.0.3
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
html5-boilerplate|sid|1.1.1
addDocComments|ste|0.0.8
es-quotes|vil|0.2.6
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehovct:30309550
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Please also try to fill in the issue template

/needsMoreInfo

**Comment by javadbat** [comment]
this issue filled by vscode itself and I don't fill it  by myself
I'm not even use typescript in my project

**Comment by mjbvz** [comment]
We file a template issue that you then need to fill in. Without more info, just submitting the template is generally not useful
