### ISSUE TITLE
"Open New External Terminal" doesn't work if no terminal settings are present

### ISSUE THREAD

**Issue by hugonasciutti** [microsoft/vscode#125985]
Issue Type: <b>Bug</b>

To reproduce the error just run `"Open New External Terminal"` from the command palette.

I tried to trace the error and it seems to be here: [src/vs/platform/externalTerminal/node/externalTerminalService.ts:318](https://github.com/microsoft/vscode/blob/1.57.0/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L318) (v1.57.0)

This is the Output from `Log (Window)`:
```
[2021-06-11 00:13:12.312] [renderer1] [error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at Ze.spawnTerminal (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:32:630)
    at Ze.openTerminal (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:613)
    at Object.call (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:8293)
    at h.onPromise (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:20:7775)
    at h.onRawMessage (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:20:7134)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:20:6387
    at k.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:14:46850
    at k.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:14:47016
    at k.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at IpcMainImpl.z (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:14:48719)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)
```

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.8.0-55-generic (Ubuntu 20.04.2 LTS)
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (5.78GB free)|
|Process Argv|--unity-launch --crash-reporter-id bd0b1a29-4ec2-492b-aa2e-e79c19fc6675|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by hugonasciutti** [comment]
Confirmed this same behavior testing in vscode-insiders:

Output from Log (Window):
```
[2021-06-11 00:27:52.922] [renderer4] [error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at Ze.spawnTerminal (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:32:630)
    at Ze.openTerminal (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:31:613)
    at Object.call (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:21:8293)
    at h.onPromise (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:20:7775)
    at h.onRawMessage (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:20:7134)
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:20:6387
    at k.fire (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:14:46850
    at k.fire (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:14:47016
    at k.fire (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at IpcMainImpl.z (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:14:48719)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)
```

Version: 1.57.0-insider
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T10:36:57.548Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-55-generic

**Comment by fbasilico** [comment]
Same in windows

[2021-06-11 08:16:04.900] [renderer1] [error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at Je.spawnTerminal (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:30:77670)
    at Je.openTerminal (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:30:77587)
    at Object.call (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:21:8293)
    at h.onPromise (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:7775)
    at h.onRawMessage (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:7134)
    at C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:6387
    at k.fire (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1835)
    at C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:46850
    at k.fire (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1835)
    at C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:47016
    at k.fire (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1835)
    at IpcMainImpl.z (C:\Users\Franco\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:48719)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)

**Comment by ivangonzalezg** [comment]
Same here

Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

**Comment by meganrogge** [comment]
Is this happening every time you run that command?

**Comment by Pranav-B23** [comment]
Confirming the same behavior. 

ERR Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at Je.spawnTerminal (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:30:77670)
    at Je.openTerminal (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:30:77587)
    at Object.call (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:21:8293)
    at h.onPromise (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:7775)
    at h.onRawMessage (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:7134)
    at C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:20:6387
    at k.fire (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1835)
    at C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:46850
    at k.fire (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1835)
    at C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:47016
    at k.fire (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1835)
    at IpcMainImpl.z (C:\Users\PRANAV\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:48719)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)


> Is this happening every time you run that command?

Yes , This happens every time I try to open the external terminal from vscode.

**Comment by meganrogge** [comment]
And no external terminal is opened, correct?

**Comment by hugonasciutti** [comment]
> And no external terminal is opened, correct?

Yes. The same error is printed every time I run it.

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by hugonasciutti** [comment]
> Can you share your settings.json file?

Sure.

settings.json
```json
{
    "atomKeymap.promptV3Features": true,
    "editor.rulers": [100],
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "workbench.iconTheme": "material-icon-theme",
    "trailing-spaces.trimOnSave": true,
    "git.enableSmartCommit": true,
    "git.autofetch": true,
    "workbench.colorCustomizations": {
        "editorError.foreground": "#ff0000"
    },
    "git.confirmSync": false,
    "editor.tabSize": 2,
    "explorer.confirmDelete": false,
    "workbench.startupEditor": "newUntitledFile",
    "explorer.confirmDragAndDrop": false,
    "javascript.updateImportsOnFileMove.enabled": "never",
    "cSpell.language": "en, pt-BR",
    "cSpell.userWords": [],
    "window.zoomLevel": 0,
    "breadcrumbs.enabled": true,
    "editor.renderControlCharacters": false,
    "editor.renderWhitespace": "none",
    "explorer.compactFolders": false,
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "diffEditor.renderSideBySide": true,
    "splitHTMLAttributes.closingBracketOnNewLine": true,
    "editor.semanticHighlighting.enabled": false,
    "files.associations": {
        "*.svg": "html"
    },
    "extensions.ignoreRecommendations": false,
    "typescript.tsdk": ""
}
```

**Comment by hugonasciutti** [comment]
@Tyriar I updated to the v1.57.1 and the fix worked, thank you!

**Comment by Tyriar** [comment]
Good to hear!
