### ISSUE TITLE
NotebookKernel: set outputs on cancel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126022]
```
1) NotebookKernel
       set outputs on cancel:
     TypeError: call.getFileName is not a function
      at getErrMessage (assert.js:279:25)
      at innerOk (assert.js:370:17)
      at Function.ok (assert.js:390:3)
      at Context.<anonymous> (file:///Users/runner/work/vscode/vscode/out/vs/workbench/test/browser/api/extHostNotebookKernel.test.js:202:20)
```

https://github.com/microsoft/vscode/runs/2801405433?check_suite_focus=true#step:10:8470

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/126054
