### ISSUE TITLE
`NotebookKernel - set outputs on cancel` unit test failure

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#126054]
Thank you for the change for https://github.com/microsoft/vscode/issues/125665 to convert it to a unit test, but unfortunately now the unit tests are failing randomly. I have seen this test fail randomly multiple times:

e.g. https://github.com/microsoft/vscode/runs/2800873453#step:11:7565 on macOS / browser unit test

```
  1) NotebookKernel
       set outputs on cancel:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (file:///Users/runner/work/vscode/vscode/out/vs/workbench/test/browser/api/extHostNotebookKernel.test.js:202:20)
```

e.g. https://github.com/microsoft/vscode/runs/2803567669?check_suite_focus=true#step:10:8466 on macOS / Electron unit test
```
  6949 passing (3m)
  48 pending
  1 failing

  1) NotebookKernel
       set outputs on cancel:
     TypeError: call.getFileName is not a function
      at getErrMessage (assert.js:279:25)
      at innerOk (assert.js:370:17)
      at Function.ok (assert.js:390:3)
      at Context.<anonymous> (file:///Users/runner/work/vscode/vscode/out/vs/workbench/test/browser/api/extHostNotebookKernel.test.js:202:20)
```

e.g. https://github.com/microsoft/vscode/runs/2802891558?check_suite_focus=true#step:11:7567 on macOS / Browser unit test
```
  5940 passing (2m)
  24 pending
  1 failing

  1) NotebookKernel
       set outputs on cancel:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (file:///Users/runner/work/vscode/vscode/out/vs/workbench/test/browser/api/extHostNotebookKernel.test.js:202:20)
```

**Comment by alexdima** [comment]
I have pushed https://github.com/microsoft/vscode/commit/edba477349fbf7b7caee6ed553f511eb5754d923 to skip the test until we figure out what is wrong.

**Comment by jrieken** [comment]
There was some foul timeout logic because we cannot await cancellation tokens... I have added an explicit barrier which should resolve this.

**Comment by alexdima** [comment]
Thank you!
