### ISSUE TITLE
Launch External Terminal Not Working

### ISSUE THREAD

**Issue by benjaminmillhouse** [microsoft/vscode#126043]
Issue Type: <b>Bug</b>

Launching an External Terminal no longer works for me after updating to the latest version of VS Code

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 5cfbddac-9f50-4279-b6f8-c3b0882f871e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.22
xml|Dot|2.5.1
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
code-runner|for|0.11.4
json2csv|kha|0.0.1
csharp|ms-|1.23.12
mssql|ms-|1.10.1
azure-account|ms-|0.9.8
material-icon-theme|PKi|4.7.0
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by benjaminmillhouse** [comment]
This looks like the error that's happening:

[2021-06-11 08:28:03.435] [renderer1] [error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at It.spawnTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:31:151)
    at It.openTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:30:79128)
    at Object.call (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:8293)
    at h.onPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:7775)
    at h.onRawMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:7134)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:6387
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:46850
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:47016
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at IpcMainImpl.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:48719)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)
