### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by PickaxeHit** [microsoft/vscode#126173]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.57.0
- OS Version:Linux (arm64)

When I try to build vscode :yarn
It failed and showed:
root@localhost:~/vscode# yarn                                                    yarn install v1.22.10
$ node build/npm/preinstall.js                                                   [1/4] Resolving packages...
[2/4] Fetching packages...                                                       info fsevents@2.3.1: The platform "linux" is incompatible with this module.      info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.                                                   info vscode-windows-ca-certs@0.3.0: The platform "linux" is incompatible with this module.                                                                        info "vscode-windows-ca-certs@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.                                    info fsevents@2.1.1: The platform "linux" is incompatible with this module.      info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.                                                   info fsevents@1.2.13: The platform "linux" is incompatible with this module.     info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.                                                  info fsevents@2.1.3: The platform "linux" is incompatible with this module.      info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.                                                   info vscode-windows-registry@1.0.3: The platform "linux" is incompatible with this module.                                                                        info "vscode-windows-registry@1.0.3" is an optional dependency and failed compatibility check. Excluding it from installation.                                    info windows-mutex@0.4.1: The platform "linux" is incompatible with this module. info "windows-mutex@0.4.1" is an optional dependency and failed compatibility check. Excluding it from installation.                                              info windows-process-tree@0.3.0: The platform "linux" is incompatible with this module.                                                                           info "windows-process-tree@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.                                       [3/4] Linking dependencies...                                                    warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".      warning " > gulp-tsb@4.0.6" has incorrect peer dependency "typescript@^3.0.0".   [4/4] Building fresh packages...                                                 [13/15] ⠄ playwright                                                             [15/15] ⡀ windows-foreground-love                                                [11/15] ⡀ electron                                                               [7/15] ⡀ spdlog                                                                  error /root/vscode/node_modules/electron: Command failed.                        Exit code: 1                                                                     Command: node install.js                                                         Arguments:                                                                       Directory: /root/vscode/node_modules/electron                                    Output:                                                                          Error: Generated checksum for "electron-v12.0.9-linux-arm64.zip" did not match expected checksum.                                                                     at Hash.hasher.on (/root/vscode/node_modules/sumchecker/index.js:133:20)         at Hash.emit (events.js:198:13)
 

My network is in good condition, and I don't know why the checksum failed.
Help me , please.

**Comment by PickaxeHit** [comment]
Sorry, I didn't notice that build it requires x64 systems.
