### ISSUE TITLE
[test api] contribute external test results caused "unknown task in updateState" error

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#126186]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.58.0-insider (Universal)
- OS Version: MacOS 11.4

Hi @connor4312,

I am testing the proposed test API and bump into the error mentioned below. Not sure if I misuse the API.... Here is our use case: the tests are trigger and reported via external runs (jest watch mode). In order to update the test results that are not triggered by the `runTest()` API, I manually created the `vscode.TestRunRequest` then call `vscode.createTestRun` for the TestItems correctly discovered and shown in the test explorer. Maybe that is not how these API was intended to be used? Is there another way to report external test results?

Steps to Reproduce:

1. create some TestItem during discovery
2. then trigger the method that manually create a `vscode.TestRunRequest` with these TestItem for `vscode.createTestRun`
3. call setState for the items, then close the run `run.end()`

I can see the outputs from `run.appendOutput()` fine, but then see errors like this:

```
ERR Unknown task bcd1c91e-b703-4abc-9a37-a8c95186396f in updateState: Error: Unknown task bcd1c91e-b703-4abc-9a37-a8c95186396f in updateState
    at r.mustGetTaskIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1228:24848)
    at r.updateState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1228:22798)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:81339
    at v.withLiveRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:82813)
    at v.$updateTestStateInRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:81320)
    at r._doInvokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:11905)
    at r._invokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:11597)
    at r._receiveRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:10259)
    at r._receiveOneMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:9257)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:7166
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16487)
    at d._receiveMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21745)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:18631
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at S.acceptChunk (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13848)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13196
    at Socket.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2803:132996)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by connor4312** [comment]
Thanks for trying it out! Doesn't sound like you're doing anything wrong; that error _should_ be impossible to hit. Can you share a code sample of what you're doing or your extension so I can see what's going on?

**Comment by connectdotz** [comment]
sure, here is a WIP local repo: https://github.com/connectdotz/vscode-jest/tree/test-provider, the relevant code is [updateTestStates](https://github.com/connectdotz/vscode-jest/blob/d3aac37434d92dd8a56b40ec65fca765f3c7c3f5/src/test-provider/test-item-dats.ts#L302), which is triggered either through `resolverHandler` or when new test result is available `onTestSuiteChanged `

**Comment by connor4312** [comment]
Ok, cool. I'll look at that tomorrow

**Comment by connectdotz** [comment]
/verified 

thx!
