### ISSUE TITLE
Smoketest failure: install and enable vscode-smoketest-check extension

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#126253]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=123090&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=aaa04083-6c0b-5a33-e907-3d845b07f0b5

```
 1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Extensions
           install and enable vscode-smoketest-check extension:
     Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:176:19)
      at async Code.waitForElement (/__w/1/s/test/automation/out/code.js:257:16)
      at async Extensions.installExtension (/__w/1/s/test/automation/out/extensions.js:39:9)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:19:13)

```

**Comment by bpasero** [comment]
Please note that I just pushed a change that will disable the getting started page (which is a complex iframe). It is possible that this editor has caused a couple of issues.

**Comment by sandy081** [comment]
I don't reproduce it anymore. Hence closing it.
