### ISSUE TITLE
Clear all notification is not working

### ISSUE THREAD

**Issue by changavila** [microsoft/vscode#126363]
1. open Bell icon in the notifications
2. click the `clear all` icon

expected: clear all notifications
actual: notification are not cleared after click

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your VS Code version? And what notifications are not closed?

**Comment by changavila** [comment]
Oh sorry my bad, 
version: 1.56.0-insiders

Please see video below:
https://user-images.githubusercontent.com/13307287/122056322-0ef0cb80-ce1c-11eb-88a5-0335667bff18.mov

The Jira and Bitbucket Official Extension are the notifications that did not disappear.

**Comment by IllusionMH** [comment]
Yep, these are not "in-progress" notifications and also observed this with other extension. No errors in console.

`>Notifications: Clear All Notifications` in Command Palette worked as expected.

**Comment by changavila** [comment]
Ah yes. I see, But its the clear notification button is the issue here. Not the command `>Notifications: Clear All Notifications`
The close button for notification also doesn't respond as well. 


https://user-images.githubusercontent.com/13307287/122062973-7578e800-ce22-11eb-93ef-04c7145541c8.mov

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by IllusionMH** [comment]
I don't deny that button doesn't work, your report is correct

Just provided more info that command works as expected and nothing strange in console.

However on closer look it's an exception

```
TypeError: Cannot read property 'original' of undefined
    at d.runAction (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:743:211252)
    at d.run (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:30840)
    at v.onClick (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:34054)
    at Immediate._onImmediate (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:33578)
    at processImmediate (internal/timers.js:461:21)
```
in this line https://github.com/microsoft/vscode/blob/8509f4854344f526892bd6d13bc39b4757b25330/src/vs/workbench/browser/parts/notifications/notificationsActions.ts#L176


`context` (`D` in minified code) is just `{"preserveFocus": false}` without `message`.

@bpasero it's report from Insiders build

**Comment by bpasero** [comment]
Ok thanks, probably a regression from the additional telemetry @isidorn added.
