### ISSUE TITLE
Lot's of `promise not handled within 1 second` when shutting down VS Code

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#126345]
I see a lot of these exceptions now when shutting down VS Code with a debugger attached to the extension host:

```
rejected promise not handled within 1 second: Canceled: Canceled
/home/dirkb/Projects/mseng/VSCode/vscode/out/bootstrap-fork.js:166
stack trace: Canceled: Canceled
	at Object.canceled (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/errors.js:109:23)
	at RPCProtocol._remoteCall (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:352:46)
	at Proxy.<anonymous> (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:150:41)
	at _.<anonymous> (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/api/common/extHostCommands.js:99:37)
	at _.dispose (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/api/common/extHostTypes.js:56:78)
	at Object.dispose (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/lifecycle.js:77:27)
	at ExtHostExtensionService._deactivate (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/api/common/extHostExtensionService.js:183:29)
	at /home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/api/common/extHostExtensionService.js:102:33
	at Array.map (<anonymous>)
	at ExtHostExtensionService.deactivateAll (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/api/common/extHostExtensionService.js:101:51)
	at ExtensionHostMain.terminate (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/extensions/common/extensionHostMain.js:82:66)
	at onTerminate (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:279:53)
	at Socket.<anonymous> (/home/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:131:21)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
	at Pipe.callbackTrampoline (internal/async_hooks.js:131:14)
```

I debugged it a little and this happens since commands get un-registered during shutdown but the RPC communication to the renderer is already closed.

**Comment by alexdima** [comment]
@dbaeumer I can't reproduce this anymore. Before heading out I saw a change about reducing logging of Cancellation errors, but I can't find it right now:

![image](https://user-images.githubusercontent.com/5047891/130210192-1d25756c-aa13-4ea5-8648-9d83372af8a9.png)
