### ISSUE TITLE
VS Code fails to launch no macOS Big Sur 11.3.1

### ISSUE THREAD

**Issue by mitch3ls** [microsoft/vscode#126367]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
1.57.0
b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
x64
```
- OS Version: `macOS Big Sur 11.3.1`

Steps to Reproduce:

1. work with VS Code
2. try launching it the next day
3. observe VS Code failing to launch

Diagnostics:

```shell
$ code --verbose
[main 2021-06-15T11:01:47.907Z] Error: connect EACCES /Users/michael/Library/Application Support/Code/1.57.0-main.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[main 2021-06-15T11:01:47.909Z] Lifecycle#kill()

$ code --verbose --disable-extensions
Warning: 'disabled-extensions' is not in the list of known options, but still passed to Electron/Chromium.
[main 2021-06-15T10:55:19.365Z] Error: connect EACCES /Users/michael/Library/Application Support/Code/1.57.0-main.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[main 2021-06-15T10:55:19.366Z] Lifecycle#kill()
```

```shell
$ ls -l "/Users/michael/Library/Application Support/Code/1.57.0-main.sock"
srwxr-xr-x  1 root  staff  0 12 Jun 21:25 /Users/michael/Library/Application Support/Code/1.57.0-main.sock
```

```shell
$ cat "/Users/michael/Library/Application Support/Code/1.57.0-main.sock"
cat: /Users/michael/Library/Application Support/Code/1.57.0-main.sock: Permission denied

$ sudo cat "/Users/michael/Library/Application Support/Code/1.57.0-main.sock"
Password:
cat: /Users/michael/Library/Application Support/Code/1.57.0-main.sock: Connection refused
```

```shell
$ ls "/Users/michael/Library/Application Support/Code"
1.56.2-main.sock           Network Persistent State
1.57.0-main.sock           Preferences
Backups                    QuotaManager
Cache                      QuotaManager-journal
CachedConfigurations       Service Worker
CachedData                 Session Storage
CachedExtensionVSIXs       TransportSecurity
CachedExtensions           User
Code Cache                 Workspaces
Cookies                    blob_storage
Cookies-journal            databases
Crashpad                   languagepacks.json
CrashpadMetrics-active.pma logs
CrashpadMetrics.pma        machineid
Dictionaries               rapid_render.json
GPUCache                   storage.json
Local Storage              webrtc_event_logs
```

**Comment by bpasero** [comment]
If `1.57.0-main.sock` is owned by `root` it means you possibly started VSCode once via `sudo`?
