### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by xu810536913** [microsoft/vscode#126459]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.5.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"d:/work/app项目/client(log日志版本)","hostCurrentDirectory":"C:/Users/cuixu/AppData/Local/Programs/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"d:/work/app项目/client(log日志版本)","hostCurrentDirectory":"C:/Users/cuixu/AppData/Local/Programs/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:128625:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:128611:29)
    at ProjectService.getOrCreateOpenScriptInfo (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:129005:33)
    at ProjectService.applyChangesInOpenFiles (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:129210:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:129980:46)
    at d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:131662:28)
    at IOSession.Session.executeCommand (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:131671:33)
    at IOSession.Session.onMessage (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:131693:35)
    at Interface.<anonymous> (d:\work\app项目\client(log日志版本)\node_modules\typescript\lib\tsserver.js:132984:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.80GB free)|
|Process Argv|--crash-reporter-id 02138b29-a789-4618-9154-861e90ce8d6d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|12.0.5
vscode-browser-preview|auc|0.7.1
antd-snippets|ban|1.2.0
vscode-custom-css|be5|5.0.3
npm-intellisense|chr|1.3.1
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.13.0
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
vscode-great-icons|emm|2.1.77
prettier-vscode|esb|6.4.0
vscode-npm|fkn|3.3.0
vs-code-http-server-and-html-preview|Fli|2.2.2
code-runner|for|0.11.4
vscode-yarn|gam|1.7.1
vscode-flutter-files|gor|3.1.2
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
vue-snippets|hol|1.0.4
vscode-angular2-emmet|jak|2.0.3
vue|jcb|0.1.5
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
svn-scm|joh|2.13.6
intellij-idea-keybindings|k--|1.4.5
vscode-codemetrics|kis|1.24.0
git-graph|mhu|1.30.0
Angular-BeastCode|Mik|10.0.3
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-language-pack-zh-hans|MS-|1.57.1
azure-account|ms-|0.9.8
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-for-node-js-development-pack|nod|2.0.1
angular-console|nrw|17.5.0
vetur|oct|0.34.1
docthis|oou|0.8.2
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.21
vscode-npm-scripts|tra|0.2.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
quokka-vscode|Wal|1.0.380
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehovct:30309550
vscod805:30301674

```

</details>

**Comment by mjbvz** [comment]
Closing as this is a quite old TS version. Let us know if you see this on TS 4.3+
