### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by HeisenbergRoc** [microsoft/vscode#126443]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.(node:9720) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)

2.JSON5: invalid end of input at 1:1    at O (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:24206)    at x (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:24063)    at Object.start (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:22341)    at Object.t.default [as parse] (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:15616)    at l (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:68889)    at u (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:68469)    at t.tsConfigLoader (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:69325)    at s (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:67173)    at Object.t.loadConfig (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:67635)    at c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:63341    at c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:63710    at D (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:60243)%c    at Timeout._onTimeout (c:\Users\wkiwi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.27.1\dist\extension.js:1:58208)%c    at listOnTimeout (internal/timers.js:554:17)%c    at processTimers (internal/timers.js:497:7) {%c  lineNumber: 1,%c  columnNumber: 1%c}
![error](https://user-images.githubusercontent.com/45787359/122167323-62f7c080-cead-11eb-92aa-02620995f37c.png)

3. When I open the editor， this error will pop up and my editor won't work properly

**Comment by HeisenbergRoc** [comment]
the problem may be my configuration yapi, then i uninstall this global extensions ,the editor will work on

**Comment by HeisenbergRoc** [comment]
i uninstall yapi and del all the folder the issus dialog again
