### ISSUE TITLE
Support changes in vscode-nls-dev that allow hint comments in package.nls.json

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#126408]
In the following change: https://github.com/microsoft/vscode-nls-dev/commit/e2447e4e0c839db8aa5a7a96439be6ec1a2ab62c
Support for hint comments was added to package.nls.json, as described here: https://github.com/microsoft/vscode-nls-dev/pull/33

This works properly to get the hint comment into the exported XLF for localization purposes.  However, VS Code appears to be failing to read from package.nls.json when this format is used, resulting in an exception thrown when the settings UI is opened.  It looks like this change requires a change to VS Code to support the new schema.

**Comment by Colengms** [comment]
@dbaeumer This appears to not be fully addressed.  With 1.58.2, doing this with the description of a setting, I get no tooltip when hovering over the setting name in `settings.json`.

I get the following error when I open the settings UI, and no settings at all are displayed.

```
log.ts:296   ERR (x.description || x.markdownDescription || "").split is not a function: TypeError: (x.description || x.markdownDescription || "").split is not a function
    at d.parseSettings (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:18950)
    at d.parseConfig (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:18453)
    at vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:17052
    at Array.reduce (<anonymous>)
    at d.getRegisteredGroups (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:17029)
    at d.parse (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16758)
    at d.initialize (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16675)
    at d.getSettingsGroups (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16596)
    at s.get settingsGroups [as settingsGroups] (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:13279)
    at Zt.onConfigUpdate (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2301:53484)
    at Zt.setInput (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2301:39364)
    at async u.doSetInput (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2355:131518)
    at async u.openEditor (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2355:129942)
    at async vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2567:15994
    at async Object.accept (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:641:3988)
```
My entry in `package.nls.json` was defined like so:

```
    "c_cpp.configuration.formatting.description": { 
            "message": "Configures the formatting engine",
            "comment": [ "test comment" ]
    },
```

And referenced like do in `package.json`:

```
          "description": "%c_cpp.configuration.formatting.description%",
```

**Comment by sean-mcmanus** [comment]
When I reproed the bug, I got none of our extension's settings displayed, but the built-in ones appeared.

Also, if this is fixed, please make sure markdownDescription is also supported.

**Comment by dbaeumer** [comment]
Missed one place where we read package.nls.json files. Fixed it.
