### ISSUE TITLE
Error when drag and drop invalid element into terminal

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#126552]
- VS Code Version: stable and from sources

Steps to Reproduce:
![terminal_dnd_error](https://user-images.githubusercontent.com/25115070/122332473-1091c080-cefc-11eb-9abf-cd3c59d2e1ce.gif)

```
  ERR Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined
    at TerminalInstanceDragAndDropController.onDrop (vscode-file://vscode-app/home/jeanpierre/gitrepos/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1765:93)
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/home/jeanpierre/gitrepos/vscode/out/vs/workbench/browser/dnd.js:367:32)
```

**Comment by jeanp413** [comment]
Created PR #126553 fixing this
