### ISSUE TITLE
Notebook Clipboard

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126564]
https://github.com/microsoft/vscode/runs/2846575572?check_suite_focus=true#step:14:11969

```
5 failing

  1) Notebook Clipboard
       Cut multiple selected cells:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:37:24
      at Object.withTestNotebook (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/test/testNotebookEditor.js:222:27)
      at Context.<anonymous> (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:26:40)

  2) Notebook Clipboard
       Cut should take folding info into account:

      AssertionError: 7 === 5
      + expected - actual

      -7
      +5
      
      at file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:65:24
      at Object.withTestNotebook (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/test/testNotebookEditor.js:222:27)
      at Context.<anonymous> (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:44:40)

  3) Notebook Clipboard
       Copy should take folding info into account:

      AssertionError: 7 === 9
      + expected - actual

      -7
      +9
      
      at file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:97:24
      at Object.withTestNotebook (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/test/testNotebookEditor.js:222:27)
      at Context.<anonymous> (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:71:40)

  4) Notebook Clipboard
       #119773, cut last item should not focus on the top first cell:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:112:24
      at Object.withTestNotebook (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/test/testNotebookEditor.js:222:27)
      at Context.<anonymous> (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:102:40)

  5) Notebook Clipboard
       #119771, undo paste should restore selections:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:137:24
      at Object.withTestNotebook (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/test/testNotebookEditor.js:222:27)
      at Context.<anonymous> (file:///D:/a/vscode/vscode/out/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.js:118:40)
```

**Comment by rebornix** [comment]
this is a duplicate and we disabled the tests now as they rely on active element.
