### ISSUE TITLE
Wrong active tab restored in datamigration smoke test

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#126613]
On Linux, this test failed several times in a row. No data loss, the readme.md and "hello from untitled" files were both restored with their changes, but the untitled file instead of the readme file was active

```
  1) VSCode Smoke Tests (Electron)
       Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
         Datamigration
           verifies that 'hot exit' works for dirty files:
     Error: Timeout: get element '.tabs-container div.tab.active.dirty[aria-selected="true"][data-resource-name$="readme.md"]' after 20 seconds.
      at poll (/datadrive/vscode/test/automation/out/code.js:174:19)
      at async Code.waitForElement (/datadrive/vscode/test/automation/out/code.js:255:16)
      at async Editors.waitForActiveTab (/datadrive/vscode/test/automation/out/editors.js:33:9)
      at async Context.<anonymous> (out/areas/workbench/data-migration.test.js:63:13)
```

**Comment by bpasero** [comment]
I cannot reproduce, just tried on Linux ARM64. Are you sure you did a clean run, meaning:
* everything is compiled
* `cd test/automation && tsc`
* `cd test/smoke && tsc`

**Comment by roblourens** [comment]
Yes, naturally I can't reproduce it today though.
