### ISSUE TITLE
code runner

### ISSUE THREAD

**Issue by janisbunkss** [microsoft/vscode#126773]
document is not defined

**Comment by janisbunkss** [comment]
I am trying to use  VSC extention Code Runner in coding, but it seems useless, because it blocks logging, if built in functions are included. For example: 
Variable defined in js as:    let saveEl = document.getElementById("save-el")
If I try to log variable:       console.log(saveEl)
code runner  does not recognize document.getElementById("save-el") and gives in output following announcements:

[Running] node "c:\Users\....trenins.js"
c:\Users\ma\Desktop\tasks\trenins.js:2
let saveEl = document.getElementById("save-el")             ^

ReferenceError: document is not defined
    at Object.<anonymous> (c:\Users\ma\Desktop\tasks\trenins.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
[Done] exited with code=1 in 0.15 seconds

More over  if abovementioned expression is included at the beginning of js code it blocks all other attempts to log anything.
 Only solution is comment- them out. Script tags are placed correctly at the  bottom of body.
