### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Handler already set!)

### ISSUE THREAD

**Issue by Rachel-King** [microsoft/vscode#126857]
Unable to connect to home directory when signing into hpc - occurs 95% of the time.

**Comment by nahidakbar** [comment]
+1

**Comment by nahidakbar** [comment]
Using Windows 10

```
[2021-06-22 15:40:52.298] [renderer1] [error] Handler already set!: Error: Handler already set!
    at n.setHandler (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:5169)
    at d.registerListeners (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39805)
    at new d (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39603)
    at p._createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at new Y (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:27087)
    at p._createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3551
    at P._executor (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18550)
    at P.get value [as value] (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18743)
    at Object.get (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3652)
    at Dn.get isMultiSessionView [as isMultiSessionView] (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2463:3179)
    at new Dn (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:66272)
    at p._createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at O.createView (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:35407)
    at O.onDidAddViewDescriptors (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:36831)
    at file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:32748
    at n.fire (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at g.triggerOnDidAddVisibleViewDescriptors (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2466:9818)
    at g.onDidChangeContext (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2466:13965)
    at file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2466:6674
    at n.fire (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:59092
    at m.fire (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at m.fire (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:2784)
    at o.setContext (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:120700)
    at set (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:118989)
    at new d (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39758)
    at p._createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at new Y (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:27087)
    at p._createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3551
    at P._executor (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18550)
    at P.get value [as value] (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18743)
    at Object.get (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3652)
    at D.registerListeners (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:50081)
    at new D (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:49996)
    at p._createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at b.safeCreateInstance (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1850:6069)
    at b.doInstantiateByPhase (file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1850:5856)
    at file:///C:/Users/civil/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1850:5698

```

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by nahidakbar** [comment]
If I reload window a bunch of times it works once. Although every time a new window is opened, its a russian roulette.

**Comment by LoranKloeze** [comment]
+1

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/126339
