### ISSUE TITLE
Loaded source not supported exception

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#126924]
1. VS Code out of source
2. Open mock debug repo, choose Extension + Server launch config
3. Press F5
4. Notice error in developer tools console in the original window

```
 ERR loadedSources not supported: Error: loadedSources not supported
    at RawDebugSession.loadedSources (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/rawDebugSession.js:366:35)
    at DebugSession.getLoadedSources (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/debugSession.js:511:45)
    at addSourcePathsToSession (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/loadedScriptsView.js:415:45)
    at vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/loadedScriptsView.js:493:75
    at Array.forEach (<anonymous>)
    at LoadedScriptsView.renderBody (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/loadedScriptsView.js:493:56)
    at LoadedScriptsView.render (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/paneview.js:160:18)
    at LoadedScriptsView.render (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewPane.js:165:19)
    at DebugViewPaneContainer.onDidAddViewDescriptors (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:587:22)
    at vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:382:97
    at Emitter.fire (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/event.js:439:38)
    at ViewContainerModel.triggerOnDidAddVisibleViewDescriptors (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/views/common/viewContainerModel.js:349:50)
    at ViewContainerModel.onDidChangeContext (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/views/common/viewContainerModel.js:512:22)
    at vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/views/common/viewContainerModel.js:242:136
    at Emitter.fire (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/event.js:439:38)
    at vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/event.js:54:106
    at PauseableEmitter.fire (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/event.js:439:38)
    at PauseableEmitter.resume (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/event.js:482:27)
    at ContextKeyService.bufferChangeEvents (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/platform/contextkey/browser/contextKeyService.js:229:42)
    at ViewModel.setFocus (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/common/debugViewModel.js:48:36)
    at DebugService.focusStackFrame (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/debugService.js:671:28)
    at DebugService.launchOrAttachToSession (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/debugService.js:444:32)
    at async DebugService.doCreateSession (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/debugService.js:402:17)
    at async Promise.all (index 1)
    at async DebugService.startDebugging (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/debugService.js:243:36)
    at async handler (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/debugCommands.js:335:13)
    at async ActionRunner.runAction (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/actions.js:115:13)
    at async ActionRunner.run (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/actions.js:107:17)
```

**Comment by weinand** [comment]
@isidorn I cannot reproduce this. Both processes start fine and debugging works (and no errors show up in the dev console).

However, there are a couple of other issues:
- since a problemmatcher is missing (because https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher is not installed), we are seeing the "npm: watch" error. This is expected.
- when dismissing the error dialog with "debug anyway" the extension starts up fine but the "debug toolbar" disappears.
- when starting mock debugging in the new window, a breakpoint is hit and the debug toolbar becomes visible again.
- stopping the extension from the debug toolbar doesn't close the window.

**Comment by isidorn** [comment]
@weinand good catch, I have tackled that via 8396858d7af

The loaded scripts issue seems to be that the Loaded Scripts view on start for each session wants to add a source path [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/loadedScriptsView.ts#L614).
If the session does not support loaded sources this will cause the exception.
it seems like the right fix is to check if the session supports loaded scripts before adding sources for that session?
Feel free to assign back to me if you would like me to tackle the loaded scripts exception
