### ISSUE TITLE
Jupyter notebook not able to run on Conda environments

### ISSUE THREAD

**Issue by sravanpannala** [microsoft/vscode#127275]
Issue Type: <b>Bug</b>

I installed Ipykernel and jupyter packages in a Conda environment. I then selected that environment as Kernel. I tried to run a simple code in a cell
```
x = 5
y = 4
x+y 
```
The kernel does load and I get this error:
> Kernel died with exit code 1. C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.
  warn(
C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2151: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'f87c5fd3-18f2-4a8c-bac4-41774c9a79b3' instead of 'b"f87c5fd3-18f2-4a8c-bac4-41774c9a79b3"'.
  warn(
Traceback (most recent call last):
  File "C:\Users\spannala\Miniconda3\envs\NDS\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\spannala\Miniconda3\envs\NDS\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\traitlets\config\application.py", line 844, in launch_instance
    app.initialize(argv)
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\traitlets\config\application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\ipykernel\kernelapp.py", line 577, in initialize
    self.write_connection_file()
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\ipykernel\kernelapp.py", line 230, in write_connection_file
    write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\jupyter_client\connect.py", line 136, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\spannala\Miniconda3\envs\NDS\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\spannala\AppData\Roaming\Python\Python39\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.

VS Code version: Code - Insiders 1.58.0-insider (49e1f9919880c1c96004f9b6ad91bcee7a94a1bd, 2021-06-25T05:14:20.119Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.28GB free)|
|Process Argv|--crash-reporter-id 6fbbf8cb-b568-4b3b-9ae7-493a124a6e21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.5.1
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
vscode-pull-request-github|Git|0.27.1
git-graph|mhu|1.30.0
gather|ms-|2021.6.0
python|ms-|2021.7.969414671-dev
vscode-pylance|ms-|2021.6.4-pre.1
jupyter|ms-|2021.7.970869158
vscode-github-issue-notebooks|ms-|0.0.102
best-dark-themes-pack|the|1.0.2
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
material-theme|zhu|3.10.14

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692

```

</details>

**Comment by sravanpannala** [comment]
The same error is occurring with [poetry](https://python-poetry.org/) virtual environments. Only [pipenv](https://pypi.org/project/pipenv/) virtual environments seem to work.
