### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by danwhitston** [microsoft/vscode#127327]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.4.5

**Steps to reproduce crash**
1. Open a particular TS project structured like a directed acyclic graph with several thousand functions, most of which take a single shared parameter. Sadly the project is closed-source.
2. Try to edit the project, move between files etc.
3. Wait for the inevitable stream of crashes from SonarLint. And apparently the occasional crash from TSServer as well.

I've enabled verbose logging and will submit full logs if this happens again.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/home/daniel/calculator/engine","hostCurrentDirectory":"/mnt/c/Users/dan/AppData/Local/Programs/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/home/daniel/calculator/engine","hostCurrentDirectory":"/mnt/c/Users/dan/AppData/Local/Programs/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:127446:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:127432:29)
    at ProjectService.getOrCreateOpenScriptInfo (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:127826:33)
    at ProjectService.applyChangesInOpenFiles (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:128031:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:128801:46)
    at /home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/home/daniel/calculator/engine/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (2.09GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/daniel/calculator/engine --remote=wsl+Ubuntu --crash-reporter-id 836ce656-bf4a-4886-aefb-3379a3886b1c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.26GB (6.52GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.26GB (6.52GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.183.0
remote-wsl|ms-|0.56.5
vscode-ruby|win|0.28.0
solargraph|cas|0.23.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
vscode-mocha-test-adapter|hbe|2.12.1
vscode-test-explorer|hbe|2.20.4
ruby-rubocop|mis|0.8.5
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
test-adapter-converter|ms-|0.0.10
ruby|reb|0.28.1
fabric8-analytics|red|0.3.3
java|red|0.79.2
vscode-commons|red|0.0.6
sonarlint-vscode|Son|2.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by mjbvz** [comment]
Closing as this is an outdated TS version. Let us know if you see this with TS 4.3+
