### ISSUE TITLE
No file system provider found for resource 'vscode-notebook-cell:...'

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127478]
Testing #127355

- Open GitHub issues notebook.
- Run command `Hex Editor: Open Active File in Hex Editor`.
- The issues notebook stays and the below error is shown:

![image](https://user-images.githubusercontent.com/9205389/123813439-30aa8200-d8f5-11eb-8171-43d45e1c2950.png)

```
No file system provider found for resource 'vscode-notebook-cell:/Users/chrmarti/Development/repos/vscode/.vscode/searches/foo.github-issues#ch0000002': Unavailable (FileSystemError): No file system provider found for resource 'vscode-notebook-cell:/Users/chrmarti/Development/repos/vscode/.vscode/searches/foo.github-issues#ch0000002'
    at _handleError (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:167446)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.getFileSize (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode.hexeditor-1.7.1/out/src/fileSystemAdaptor.js:23:21)
    at Function.create (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode.hexeditor-1.7.1/out/src/hexDocument.js:68:26)
    at HexEditorProvider.openCustomDocument (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode.hexeditor-1.7.1/out/src/hexEditorProvider.js:28:26)
    at w.$createCustomDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:71011)
log.ts:296   ERR Unavailable (FileSystemError): No file system provider found for resource 'vscode-notebook-cell:/Users/chrmarti/Development/repos/vscode/.vscode/searches/foo.github-issues#ch0000002'
    at _handleError (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:167446)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.getFileSize (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode.hexeditor-1.7.1/out/src/fileSystemAdaptor.js:23:21)
    at Function.create (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode.hexeditor-1.7.1/out/src/hexDocument.js:68:26)
    at HexEditorProvider.openCustomDocument (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode.hexeditor-1.7.1/out/src/hexEditorProvider.js:28:26)
    at w.$createCustomDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:71011)
```

**Comment by lramos15** [comment]
This is a bug of the hex editor and not of VS Code. The issue is that VS Code does not have an API to get the `URI` of the active tab. I attempt to use the text documents to figure this out and I guess it returns a cell URI in this case. I know @eamodio was working on an active tab API awhile ago but don't know what happened with that.

**Comment by bpasero** [comment]
Maybe you mean this proposed API:

https://github.com/microsoft/vscode/blob/339ff8d463fd9ecd769138bd9f23f1887da627aa/src/vs/vscode.proposed.d.ts#L2485-L2496
