### ISSUE TITLE
Error logged saving new issues notebook

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127484]
Testing #127355

Using Save All with several new and untitled issues notebooks:
```
Cannot register more than one working copy with the same resource untitled:Untitled-12.github-issues?github-issues and type notebook/github-issues.: Error: Cannot register more than one working copy with the same resource untitled:Untitled-12.github-issues?github-issues and type notebook/github-issues.
    at E.registerWorkingCopy (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2345:14135)
    at new Kr (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2396:35352)
    at v.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2402:54055)
    at A.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2402:57635)
    at Pn.load (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2396:4342)
    at Zi.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1505:784)
    at async vr.setInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1806:19941)
    at async h.doSetInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2346:131356)
    at async h.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2346:129781)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2558:16039
    at async x.save (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2396:31904)
    at async oe (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2617:3449)
```

The files seem to be saved correctly.

**Comment by chrmarti** [comment]
I used the `New GitHub Issue Notebook` to create about 10 new unsaved notebooks and then did Save All.
