### ISSUE TITLE
Some mac smoketests failing (electron)

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#127682]
Testing #127395 on MacOS

Just confirming, I ran the command:
`yarn smoketest --build "/Users/sana/code/smoketest/insiders/Visual Studio Code - Insiders.app" --stable-build "/Users/sana/code/smoketest/stable/Visual Studio Code.app"`

I see 17 passing, 7 pending, 8 failing, using the `cc528230987ce3ac61fc4f094ae247d5ff24db3c` insiders commit. 

Failing tests:
```
1) VSCode Smoke Tests (Electron)
       Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
         Datamigration
           verifies opened editors are restored:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitForActiveElement (/Users/sana/code/current/vscode/test/automation/out/code.js:262:9)
      at async QuickInput.waitForQuickInputOpened (/Users/sana/code/current/vscode/test/automation/out/quickinput.js:22:9)
      at async QuickInput.selectQuickInputElement (/Users/sana/code/current/vscode/test/automation/out/quickinput.js:31:9)
      at async QuickAccess.runCommand (/Users/sana/code/current/vscode/test/automation/out/quickaccess.js:52:9)
      at async Context.<anonymous> (out/areas/workbench/data-migration.test.js:27:13)

  2) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Preferences
           turns off editor line numbers and verifies the live change:
     Error: Timeout: is active element '.editor-instance .monaco-editor[data-uri$="app.js"] textarea' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitForActiveElement (/Users/sana/code/current/vscode/test/automation/out/code.js:262:9)
      at async Editors.waitForEditorFocus (/Users/sana/code/current/vscode/test/automation/out/editors.js:30:9)
      at async Editors.selectTab (/Users/sana/code/current/vscode/test/automation/out/editors.js:22:9)
      at async Context.<anonymous> (out/areas/preferences/preferences.test.js:18:13)

  3) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Preferences
           changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:
     Error: Timeout: is active element '.defineKeybindingWidget .monaco-inputbox input' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitForActiveElement (/Users/sana/code/current/vscode/test/automation/out/code.js:262:9)
      at async KeybindingsEditor.updateKeybinding (/Users/sana/code/current/vscode/test/automation/out/keybindings.js:26:9)
      at async Context.<anonymous> (out/areas/preferences/preferences.test.js:24:13)

  4) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           verifies problems view:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitForElement (/Users/sana/code/current/vscode/test/automation/out/code.js:258:16)
      at async Problems.hideProblemsView (/Users/sana/code/current/vscode/test/automation/out/problems.js:19:9)
      at async Context.<anonymous> (out/areas/languages/languages.test.js:27:13)

  5) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           verifies settings:
     Error: Timeout: click ' .monaco-editor[data-uri$="settings.json"] .view-lines > .view-line:nth-child(1)' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitAndClick (/Users/sana/code/current/vscode/test/automation/out/code.js:242:9)
      at async Editor.waitForEditorFocus (/Users/sana/code/current/vscode/test/automation/out/editor.js:75:9)
      at async SettingsEditor.addUserSetting (/Users/sana/code/current/vscode/test/automation/out/settings.js:20:9)
      at async Context.<anonymous> (out/areas/languages/languages.test.js:31:13)

  6) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Statusbar
           verifies that 'quick input' opens when clicking on status bar elements:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitForActiveElement (/Users/sana/code/current/vscode/test/automation/out/code.js:262:9)
      at async QuickInput.waitForQuickInputOpened (/Users/sana/code/current/vscode/test/automation/out/quickinput.js:22:9)
      at async Context.<anonymous> (out/areas/statusbar/statusbar.test.js:34:13)

  7) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Statusbar
           checks if 'Go to Line' works if called from the status bar:
     Error: Timeout: get element '.monaco-editor .view-overlays>:nth-child(15) .current-line' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitForElement (/Users/sana/code/current/vscode/test/automation/out/code.js:258:16)
      at async Editor.waitForHighlightingLine (/Users/sana/code/current/vscode/test/automation/out/editor.js:47:13)
      at async Context.<anonymous> (out/areas/statusbar/statusbar.test.js:72:13)

  8) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Statusbar
           verifies if changing EOL is reflected in the status bar:
     Error: Timeout: get text content '.statusbar-item[id="status.editor.eol"]' after 20 seconds.
      at poll (/Users/sana/code/current/vscode/test/automation/out/code.js:177:19)
      at async Code.waitForTextContent (/Users/sana/code/current/vscode/test/automation/out/code.js:238:16)
      at async Context.<anonymous> (out/areas/statusbar/statusbar.test.js:80:13)
```

**Comment by bpasero** [comment]
Smoke tests are sensitive to the window being in front and having focus, did you maybe run the smoke test in the background?

**Comment by chrmarti** [comment]
Reran them on my machine to verify the data migration tests pass.
