### ISSUE TITLE
notebook type 'jupyter-notebook' ALREADY EXISTS

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127744]
1. Latest out of source
2. Have python extension installed
3. Notice error in devtools console

I can not reproduce this easily, but I hope the stack trace might help.
If this is not useful feel free to just close

```
  ERR notebook type 'jupyter-notebook' ALREADY EXISTS: Error: notebook type 'jupyter-notebook' ALREADY EXISTS
    at NotebookProviderInfoStore.add (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/notebook/browser/notebookServiceImpl.js:146:23)
    at NotebookService.registerContributedNotebookType (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/contrib/notebook/browser/notebookServiceImpl.js:374:57)
    at MainThreadNotebooks.$registerNotebookSerializer (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/api/browser/mainThreadNotebook.js:103:55)
    at RPCProtocol._doInvokeHandler (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
    at RPCProtocol._invokeHandler (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
    at RPCProtocol._receiveRequest (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
    at RPCProtocol._receiveOneMessage (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
    at vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
    at Emitter.fire (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/event.js:439:38)
    at BufferedEmitter.fire (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:380:35)
    at PersistentProtocol._receiveMessage (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:659:41)
    at vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:515:83
    at Emitter.fire (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/common/event.js:439:38)
    at ProtocolReader.acceptChunk (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:194:37)
    at vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:163:61
    at Socket.listener (vscode-file://vscode-app/Users/isidor/Development/vscode/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by joyceerhl** [comment]
We recently ported the Jupyter extension to use `registerNotebookSerializer` instead of `registerContentProvider`. Perhaps we are registering twice?

@isidorn can you share the rest of the log?

**Comment by isidorn** [comment]
@joyceerhl there is not rest of the log, that is the whole exception that I got :)

**Comment by rebornix** [comment]
@joyceerhl jupyter should not pass in the last argument when it has static contributions in the package.json https://github.com/microsoft/vscode-jupyter/blob/94a5d167441105db1f3285f33480ca1cc79ee52f/src/client/common/application/notebook.ts#L118-L119
