### ISSUE TITLE
Localization smoke test failing

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127777]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=125888&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d

```
 1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           "before all" hook for "starts with 'DE' locale and verifies title and viewlets text is in German":
     Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:177:19)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:258:16)
      at async Extensions.installExtension (/Users/runner/work/1/s/test/automation/out/extensions.js:39:9)
      at async Context.<anonymous> (out/areas/workbench/localization.test.js:19:13)
```

**Comment by dbaeumer** [comment]
Actually this doesn't fail because of me. It is related to the installing of extensions. Assigning to @sandy to comment on why this now fails.

**Comment by sandy081** [comment]
Checked the logs and it seems downloading the extension has not finished probably due to network issue on the build machine. Hence closing this as there is no further action can be taken.
