### ISSUE TITLE
Unable to resolve resource walkThrough://vscode_getting_started_page

### ISSUE THREAD

**Issue by Leon-pan** [microsoft/vscode#127741]
Issue Type: <b>Bug</b>

when I open vscode it is happen

[2021-07-01 13:54:13.429] [renderer3] [error] Error: Unable to resolve resource walkThrough://vscode_getting_started_page
    at s.doCreateReferencedObject (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2516:109892)
    at s.doCreateReferencedObject (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2516:109855)
    at async g.createModelReference (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2516:111507)
    at async ur.resolve (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2026:45998)
    at async Jo.setInput (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:90098)
    at async u.doSetInput (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:132720)
    at async u.openEditor (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:131131)
    at async file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2680:16248
[2021-07-01 13:54:13.500] [renderer3] [error] Unable to resolve resource walkThrough://vscode_getting_started_page: Error: Unable to resolve resource walkThrough://vscode_getting_started_page
    at s.doCreateReferencedObject (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2516:109892)
    at s.doCreateReferencedObject (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2516:109855)
    at async g.createModelReference (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2516:111507)
    at async ur.resolve (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2026:45998)
    at async Jo.setInput (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:90098)
    at async u.doSetInput (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:132720)
    at async u.openEditor (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:131131)
    at async file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2680:16248
[2021-07-01 13:55:13.189] [renderer3] [warning] UNRESPONSIVE extension host, 'CoenraadS.bracket-pair-colorizer' took 100% of 5073.922ms, saved PROFILE here: 'file:///c%3A/Users/panjl/AppData/Local/Temp/exthost-2e3909.cpuprofile' [{"id":"CoenraadS.bracket-pair-colorizer","total":5073678,"percentage":100}]

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.47GB free)|
|Process Argv|--crash-reporter-id f432ec1e-6bb6-4b6d-baf6-46860196ef37|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-nginx-conf|ahm|0.1.3
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.5.1
vscode-html-css|ecm|1.10.2
shell-format|fox|7.1.0
vscode-nginx-conf-hint|han|0.1.0
vscode-language-pack-zh-hans|MS-|1.57.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
nginx-formatter|ray|0.0.13
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.8.1
vscode-icons|vsc|11.5.0
vscode-nginx|wil|0.7.2
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by Leon-pan** [comment]
![image](https://user-images.githubusercontent.com/37100346/124073289-8d807680-da74-11eb-9607-89e234a764cc.png)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate which extension is causing the problem.

**Comment by Leon-pan** [comment]
![image](https://user-images.githubusercontent.com/37100346/124089718-bb6eb680-da86-11eb-849e-63f2064a3e55.png)

I disabled all my extensions and the problem still exists

**Comment by JacksonKearl** [comment]
Do you have the setting `editorAssociations: {'*': 'default'}` set anywhere in your settings.json? 

Probably duplicate of https://github.com/microsoft/vscode/issues/127206

**Comment by Leon-pan** [comment]
> 您是否`editorAssociations: {'*': 'default'}`在 settings.json 的任何位置设置了设置？
> 
> 可能与#127206重复[](https://github.com/microsoft/vscode/issues/127206)

![image](https://user-images.githubusercontent.com/37100346/124205551-0be02580-db14-11eb-8341-ddb4bf4b4a90.png)

After I deleted the settings other than the default, the problem was solved. Thank you.

But I have never modified this setting, it may be related to the Jupyter extension I installed.

**Comment by Leon-pan** [comment]
> Do you have the setting `editorAssociations: {'*': 'default'}` set anywhere in your settings.json?
> 
> Probably duplicate of #127206

I deleted all the editorAssociations configuration and the problem disappeared. Thank you.
