### ISSUE TITLE
Notebook API test failures

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127872]
A few tests failed when running a build today:

### Windows

1) Notebook API tests
       edit API batch edits:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Notebook API tests
       notebook workspace edit and undo redo:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=126062&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=354d3e13-3534-5793-0b68-b00f8c1d36f3&s=40b405d8-d9ea-5f38-8ab3-8db0b216e2d0

### Windows32

1) Notebook API tests
       editor move command - event and move cells will not recreate cells in ExtHost (#98126):
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) vscode API - webview
       webviews should have real view column after they are created, #56097:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\webview.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=126062&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=db518bcd-8ed0-56a4-45e1-3d82dd101e35&s=40b405d8-d9ea-5f38-8ab3-8db0b216e2d0

**Comment by roblourens** [comment]
Sorry that I'm just seeing this now, there have probably been lots of changes since then...
