### ISSUE TITLE
Web smoke tests are flaky

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127854]
1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Editor
           shows correct quick outline:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:177:19)
      at async Code.waitForElements (/Users/runner/work/1/s/test/automation/out/code.js:254:16)
      at async QuickInput.waitForQuickInputElements (/Users/runner/work/1/s/test/automation/out/quickinput.js:25:9)
      at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:42:9)
      at async Context.<anonymous> (out/areas/editor/editor.test.js:15:13)

**Comment by bpasero** [comment]
@isidorn when filing test issues I typically put a link into the description for the CI run that failed because that tells about the OS running and possible other failures and output.

**Comment by isidorn** [comment]
Sorry about that. I usually do this, but today forgot about it https://dev.azure.com/monacotools/Monaco/_build/results?buildId=126045&view=results

**Comment by bpasero** [comment]
I cannot reproduce running locally.

@joaomoreno @lszomoru thoughts what to do in this case? Things that would help:
* in all error messages also print the current active element (e.g. if it is some welcome editor or custom editor sneaking in, or even a dialog)
* pro: attach screenshots of the run or when it fails

**Comment by bpasero** [comment]
I feel web smoke tests are just overly flaky:

```


  2) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Language Features
           verifies problems view:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:177:19)
      at async Code.waitForElements (/Users/runner/work/1/s/test/automation/out/code.js:254:16)
      at async QuickInput.waitForQuickInputElements (/Users/runner/work/1/s/test/automation/out/quickinput.js:25:9)
      at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:42:9)
      at async Context.<anonymous> (out/areas/languages/languages.test.js:22:13)

  3) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Language Features
           verifies settings:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:177:19)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:258:16)
      at async Context.<anonymous> (out/areas/languages/languages.test.js:33:13)

  4) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Editor
           shows correct quick outline:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:177:19)
      at async Code.waitForElements (/Users/runner/work/1/s/test/automation/out/code.js:254:16)
      at async QuickInput.waitForQuickInputElements (/Users/runner/work/1/s/test/automation/out/quickinput.js:25:9)
      at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:42:9)
      at async Context.<anonymous> (out/areas/editor/editor.test.js:15:13)
```

from https://dev.azure.com/monacotools/Monaco/_build/results?buildId=126070&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab&l=68

So we should find solutions that help diagnosing further.

**Comment by joaomoreno** [comment]
I suggest we proceed with https://github.com/microsoft/vscode/pull/128061 so we get tooling for post-morten diagnosis.

**Comment by bpasero** [comment]
Yeah that was my plan. once we merge that PR and get a failing web smoke test, we can see if the trace helps.

**Comment by bpasero** [comment]
@joaomoreno nevertheless, maybe the error could still indicate the current active element?

**Comment by bpasero** [comment]
Caught a search smoke test failure:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=126708&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab&l=67

Related trace: 
[playwright-trace-1.zip](https://github.com/microsoft/vscode/files/6784942/playwright-trace-1.zip)

It really looks like the search is just timing out:

![recording](https://user-images.githubusercontent.com/900690/124932764-a1dbea80-e003-11eb-89e8-f5257d5b8046.gif)

It is hard to see because you don't really know when the test times out and the next one starts. I wonder if we should even partition each individual smoke test to a separate run to be able to diagnose further...

**Comment by bpasero** [comment]
Looks decent lately:

![image](https://user-images.githubusercontent.com/900690/128543026-d9126b7c-ba06-4d2d-9284-b730a297df29.png)

I suggest we resort back to investigating individual issues again using the tracing options.
