### ISSUE TITLE
Emmet test failure

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#127985]
https://github.com/microsoft/vscode/actions/runs/1000341948

```
 1) Tests for Emmet actions on html tags
       update image css with multiple cursors in css file:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected ... Lines skipped

  '\n' +
    '\t\t.one {\n' +
...
    '\t\t.two {\n' +
    '\t\t\tbackground-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);\n' +
+   '\t\t\theight: 42px;\n' +
+   '\t\t}\n' +
+   '\t\t.three {\n' +
+   '\t\t\tbackground-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);\n' +
+   '\t\t\twidth: 42px;\n' +
-   '\t\t\twidth: 1024px;\n' +
-   '\t\t\theight: 1024px;\n' +
-   '\t\t}\n' +
-   '\t\t.three {\n' +
-   '\t\t\tbackground-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);\n' +
-   '\t\t\theight: 1024px;\n' +
-   '\t\t\twidth: 1024px;\n' +
    '\t\t}\n' +
    '\t'
      + expected - actual

       			height: 1024px;
       		}
       		.two {
       			background-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);
      -			height: 42px;
      +			width: 1024px;
      +			height: 1024px;
       		}
       		.three {
       			background-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);
      -			width: 42px;
      +			height: 1024px;
      +			width: 1024px;
       		}
       	
      
      at /Users/runner/work/vscode/vscode/extensions/emmet/src/test/updateImageSize.test.ts:58:12
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by rzhao271** [comment]
I'll close this issue for now, since it seems to be a rare non-critical failure.
I was not able to reproduce the failure locally, or by re-running the GitHub actions on your change.
