### ISSUE TITLE
Unescaped space in path node debug

### ISSUE THREAD

**Issue by VPelt** [microsoft/vscode#128463]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (3 wks ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:

1. npm run start (from terminal)
Error: Cannot find module '"/Users/me/Library/Application'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:602:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

What i've tried
turning on and off preview debugger as described here https://github.com/microsoft/vscode/issues/102433 has no effect

**Comment by VPelt** [comment]
I was running node 10 (in the app/through nvm)

no sure how this issue caused this, but after de-installing node 10 it was fixed
