### ISSUE TITLE
new version broke my script

### ISSUE THREAD

**Issue by stevenm100** [microsoft/vscode#128509]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Hey, im not a tech wizz, so i dont know how to reliably explain what has happened, but i run similar code on google colab and nothing changed there (all works fine), but VSC stopped working when it moved to the latest version.

I use yfinance module with pandas_datareader module to download data from yahoo finance to my machine. Now when I run it, I get an error message that is not tractable to my level of expertise.
```
import yfinance as yf
from pandas_datareader import data as pdr
import pandas as pd
import os
from tqdm import tqdm
import datetime
import time
from dateutil.relativedelta import relativedelta

yf.pdr_override()
DATADIR = 'c:/loc1/
DATADIRpre = 'c:/loc2/

watchlist = ['^GSPC',]

for symbol in watchlist:
    print(symbol)
    data = pdr.get_data_yahoo(symbol, period='7d',  interval='1m', prepost=True ) #
    fname = f'{symbol}.csv'
```

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.95GB free)|
|Process Argv|--crash-reporter-id a4f9548d-74d5-42c4-a2cf-f795e3dd73d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by claudiaregio** [comment]
Hi @stevenm100, is this code you are running in a Jupyter notebook? Could you update to the latest versions of the Python/Jupyter extensions and let us know if this problem persists?

**Comment by claudiaregio** [comment]
@stevenm100 After expanding the extensions, I see you are on the latest versions. Could you paste the error you saw?

**Comment by stevenm100** [comment]
Hi @claudiaregio . The error I see is below:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\base.py", line 156, in history
    data = data.json()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


I get the same error on another machine running python 3.7:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool  
    return callee(*args, **kwargs)
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\yfinance\multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\yfinance\base.py", line 155, in history
    data = data.json()
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\slmatthe\AppData\Local\Programs\Python\Python37\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kieferrm** [comment]
\extPython
