### ISSUE TITLE
aitocomplete stop working and vscode.typescript.features has crash

### ISSUE THREAD

**Issue by victorfernandesraton** [microsoft/vscode#128606]
Issue Type: <b>Bug</b>

When i see terminal Extensions Log, i find this log

[2021-07-14 01:13:01.180] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2021-07-14 01:13:01.181] [exthost] [error] Error: <semantic> TypeScript Server Error (4.4.0-dev.20210713)
Debug Failure.
Error: Debug Failure.
    at rehydrateCachedInfo (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:123196:66)
    at Array.map (<anonymous>)
    at /home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:123141:33
    at Map.forEach (<anonymous>)
    at Object.forEach (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:123139:28)
    at /home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126829:32
    at resolvingModuleSpecifiers (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:125450:26)
    at collectAutoImports (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126828:17)
    at getGlobalCompletions (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126740:17)
    at tryGetGlobalSymbols (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126646:25)
    at getCompletionData (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126418:22)
    at Object.getCompletionsAtPosition (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:125515:34)
    at Proxy.getCompletionsAtPosition (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:156208:35)
    at /home/victor/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.14/node_modules/@vsintellicode/typescript-intellicode-plugin/lib/index.js:2:3222
    at Object.l.getCompletionsAtPosition (/home/victor/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.14/node_modules/@vsintellicode/typescript-intellicode-plugin/lib/index.js:2:8139)
    at IOSession.Session.getCompletions (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:167632:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:166483:61)
    at /home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168281:88
    at IOSession.Session.executeWithRequestId (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168272:28)
    at IOSession.Session.executeCommand (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168281:33)
    at IOSession.Session.onMessage (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168307:35)
    at Interface.<anonymous> (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:170906:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
    at Function.create (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:75833)
    at dispatchResponse (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:69697)
    at dispatchMessage (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:68556)
    at /usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:68046
    at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at g.onLengthData (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:434643)
    at Socket.<anonymous> (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:434291)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2567)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|7.66GB (0.60GB free)|
|Process Argv|--unity-launch --crash-reporter-id c2847dae-fa16-42a5-9b24-009e909c7c5d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
vscode-node-debug-process-picker|apr|1.0.0
path-intellisense|chr|2.3.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.7
vscode-pull-request-github|Git|0.28.0
go|gol|0.26.0
vscode-graphql|Gra|0.3.16
json2ts|Gre|0.0.6
vscode-test-explorer|hbe|2.20.4
npm-dependency-links|her|1.2.0
vscode-jest-test-adapter|kav|0.8.1
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
vscode-bicep|ms-|0.4.63
vscode-docker|ms-|1.14.0
vscode-dotnet-runtime|ms-|1.2.0
cpptools|ms-|1.5.1
js-debug-nightly|ms-|2021.7.917
live-server|ms-|0.2.2
test-adapter-converter|ms-|0.0.13
vscode-github-issue-notebooks|ms-|0.0.102
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4568
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.5.2
vscode-jest|Ort|4.0.3
material-icon-theme|PKi|4.8.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.14
vscode-arduino|vsc|0.4.3
glean|wix|5.2.2
stylable-intelligence|wix|0.7.5
vscode-import-cost|wix|2.15.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by fsevenm** [comment]
I also got this issue. It's a typescript issue I think. I was using 4.4.x-dev when I got that issue, but after downgraded it to 4.2.4, autocomplete go fine again.
