### ISSUE TITLE
TypeError: Cannot read property 'getRepositoryRoot' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12884]
Got this when switching folders with a dirty file:

```
[16364:0928/143348:INFO:CONSOLE(26)] "TypeError: Cannot read property 'getRepositoryRoot' of null
    at OpenInDiffAction.isEnabled (file:////Users/bpasero/Development/monaco/out/vs/workbench/parts/git/browser/gitActions.contribution.js:47:52)
    at OpenInDiffAction.set [as input] (file:////Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/editor/baseEditor.js:433:37)
    at file:////Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/editor/baseEditor.js:331:34
    at Array.forEach (native)
    at FileEditorActionContributor.EditorInputActionContributor.getActions (file:////Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/editor/baseEditor.js:330:31)
    at file:////Users/bpasero/Development/monaco/out/vs/workbench/browser/actionBarRegistry.js:242:61
    at Array.forEach (native)
    at ActionBarRegistry.getActionBarActionsForContext (file:////Users/bpasero/Development/monaco/out/vs/workbench/browser/actionBarRegistry.js:239:41)
    at TabsTitleControl.TitleControl.getEditorActionsForContext (file:////Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/editor/titleControl.js:231:77)
    at TabsTitleControl.TitleControl.getEditorActions (file:////Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/editor/titleControl.js:204:47)", source: file:///Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/bootstrap/index.js (26)

```

**Comment by joaomoreno** [comment]
This happens during workbench disposal.
