### ISSUE TITLE
NPE when editing file

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12882]
I get this NPE every time I edit a TS file in our repo, with the latest Insiders:

```
shell.ts:441 Cannot read property 'uri' of null: TypeError: Cannot read property 'uri' of null
    at e._onMarkerChanges (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:73:9505)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:73:9242
    at e.invoke (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:20883)
    at e.fire (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:31454)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:29714
```

![image](https://cloud.githubusercontent.com/assets/22350/18913416/f096b460-8587-11e6-91e8-5220d46ef1b2.png)

**Comment by joaomoreno** [comment]
Seems to come from https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/browser/quickFixModel.ts#L28

**Comment by jrieken** [comment]
Looks like an editor without a model

![screen shot 2016-09-28 at 14 39 08](https://cloud.githubusercontent.com/assets/1794099/18913676/5dbf3e8a-8589-11e6-8ea0-ebfc987f6498.png)

**Comment by jrieken** [comment]
**steps**:

* install tslint
* open a typescript file
* open peek editor (find reference, preview declaration)
* close peek
* make code to add or remove a marker 💥
