### ISSUE TITLE
Tasks unit tests are failing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#128816]
```
1) Tasks version 2.0.0
       Build workspace task:
     AssertionError [ERR_ASSERTION]: group
      at assertTask (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:381:16)
      at file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:368:13
      at Array.forEach (<anonymous>)
      at assertConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:364:20)
      at testConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:295:9)
      at Context.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:1307:13)

  2) Tasks version 2.0.0
       Global group build:
     AssertionError [ERR_ASSERTION]: group
      at assertTask (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:381:16)
      at file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:368:13
      at Array.forEach (<anonymous>)
      at assertConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:364:20)
      at testConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:295:9)
      at Context.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:1336:13)

  3) Tasks version 2.0.0
       Global group default build:

      AssertionError [ERR_ASSERTION]: group
      + expected - actual

       {
         "_id": "build"
      -  "isDefault": true
      +  "isDefault": false
       }
      
      at assertTask (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:381:16)
      at file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:368:13
      at Array.forEach (<anonymous>)
      at assertConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:364:20)
      at testConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:295:9)
      at Context.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:1352:13)

  4) Tasks version 2.0.0
       Local group build:
     AssertionError [ERR_ASSERTION]: group
      at assertTask (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:381:16)
      at file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:368:13
      at Array.forEach (<anonymous>)
      at assertConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:364:20)
      at testConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:295:9)
      at Context.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:1391:13)

  5) Tasks version 2.0.0
       Local group default build:

      AssertionError [ERR_ASSERTION]: group
      + expected - actual

       {
         "_id": "build"
      -  "isDefault": true
      +  "isDefault": false
       }
      
      at assertTask (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:381:16)
      at file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:368:13
      at Array.forEach (<anonymous>)
      at assertConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:364:20)
      at testConfiguration (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:295:9)
      at Context.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/tasks/test/common/configuration.test.js:1412:13)
```

I have skipped them temporarily.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/3d5b13265dbdb5f09929ced2eccdf7e6b5e7a14a
