### ISSUE TITLE
TS Server fatal error:  Cannot read property 'charCount' of undefined

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#128804]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.7

**Steps to reproduce crash**
Occurred after a save, which formatted the document incorrectly (lost some text), after which I did an undo.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:150250:44)
    at LineIndex.edit (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:150138:31)
    at ScriptVersionCache._getSnapshot (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:149928:47)
    at ScriptVersionCache.lineOffsetToPosition (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:149947:29)
    at TextStorage.lineOffsetToPosition (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:142065:33)
    at ScriptInfo.lineOffsetToPosition (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:142413:41)
    at /Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:147801:56
    at Object.next (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:579:33)
    at ProjectService.applyChangesToFile (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:146949:46)
    at ProjectService.applyChangesInOpenFiles (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:146916:30)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:147792:46)
    at /Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:149555:88
    at IOSession.Session.executeWithRequestId (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:149546:28)
    at IOSession.Session.executeCommand (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:149555:33)
    at IOSession.Session.onMessage (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:149579:35)
    at Interface.<anonymous> (/Users/stephenweatherford/repos/vscode-azurearmtools/node_modules/typescript/lib/tsserver.js:150895:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.59.0-insider (50b3811fdc5b5c80ca516a2edfffedcbd464b033, 2021-07-15T05:12:24.272Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
bracket-select|chu|2.0.2
bracket-pair-colorizer-2|Coe|0.2.1
kusto|don|0.3.5
brackethighlighter|Dur|2.2.4
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.28.0
todo-tree|Gru|0.0.213
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-bicep|ms-|0.4.412
vscode-cosmosdb|ms-|0.17.0
vscode-docker|ms-|1.14.0
vscode-language-pack-de|MS-|1.58.8
csharp|ms-|1.23.13
dotnet-interactive-vscode|ms-|1.0.2357011
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1033311975
azure-account|ms-|0.9.8
powershell|ms-|2021.6.2
vscode-github-issue-notebooks|ms-|0.0.102
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.0
vscode-versionlens|pfl|1.0.9
vscode-todo-highlight|way|1.0.4

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe the same underlying cause as #128730?

**Comment by mjbvz** [comment]
Do you see this when using TS 4.3+?
