### ISSUE TITLE
TS Server fatal error:  Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by TAKaiser** [microsoft/vscode#129049]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `diagnostics`
```
TypeError: Cannot read property 'forEach' of undefined
    at Object.clearMap (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:18608:13)
    at ProjectService.stopWatchingWildCards (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161007:20)
    at ConfiguredProject.releaseParsedConfig (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159119:37)
    at c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159223:34
    at Map.forEach (<anonymous>)
    at ConfiguredProject.close (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159222:66)
    at ProjectService.removeProject (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160276:25)
    at c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162098:86
    at Map.forEach (<anonymous>)
    at ProjectService.removeOrphanConfiguredProjects (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162098:44)
    at ProjectService.cleanupAfterOpeningFile (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162042:22)
    at ProjectService.applyChangesInOpenFiles (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162246:26)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:163293:46)
    at c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165210:88
    at IOSession.Session.executeWithRequestId (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165201:28)
    at IOSession.Session.executeCommand (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165210:33)
    at IOSession.Session.onMessage (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165236:35)
    at Interface.<anonymous> (c:\Users\akt\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.91GB (13.95GB free)|
|Process Argv|--crash-reporter-id ced1f55d-84b0-482d-82fc-c4e95bc00119|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.2
yaml2json|ahe|0.0.3
classdiagram-ts|Ale|0.1.43
aws-toolkit-vscode|ama|1.27.0
swagger-viewer|Arj|3.1.2
whitespace-plus|dav|0.0.5
vscode-eslint|dba|2.1.23
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
code-runner|for|0.11.5
todo-tree|Gru|0.0.213
terraform|has|2.13.2
vscode-test-explorer|hbe|2.20.4
docthis|joe|0.7.1
kite|kit|0.147.0
vscode-mocha-sidebar|mat|0.22.2
rainbow-csv|mec|1.9.1
vscode-docker|ms-|1.15.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
powershell|ms-|2021.6.2
test-adapter-converter|ms-|0.0.13
indent-rainbow|ode|7.5.0
tsimporter|pmn|2.0.1
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.1
vscode-javascript-booster|sbu|14.0.1
markdown-preview-enhanced|shd|0.5.22
prettier-vscode|Sim|2.0.7
spectral|sto|0.2.5
serverless-ide-vscode|Thr|0.5.31
remove-empty-lines|use|0.0.7
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by TAKaiser** [comment]
Sorry for the confusion, i just clicked the button that popped up. Im under time pressure. Restart VSCode helpes, so just close this.
