### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by EKashpersky** [microsoft/vscode#129032]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.5.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/ekashpersky/Documents/Projects/mobileapp","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-1","currentDirectory":"/Users/ekashpersky/Documents/Projects/mobileapp","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:128625:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:128611:29)
    at ProjectService.getOrCreateOpenScriptInfo (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:129005:33)
    at ProjectService.applyChangesInOpenFiles (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:129210:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:129980:46)
    at /Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:131662:28)
    at IOSession.Session.executeCommand (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:131671:33)
    at IOSession.Session.onMessage (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:131693:35)
    at Interface.<anonymous> (/Users/ekashpersky/Documents/Projects/mobileapp/node_modules/typescript/lib/tsserver.js:132984:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|--crash-reporter-id d0defd28-46db-41eb-83b0-4a1912158557|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
code-gnu-global|aus|0.2.2
vscode-custom-css|be5|6.0.0
vscode-svgviewer|css|2.0.0
githistory|don|0.6.17
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
code-runner|for|0.11.5
selected-lines-count|gur|1.4.0
c-cpp-flylint|jbe|1.9.3
vscode-scss|mrm|0.10.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4583
copy-json-path|nid|0.2.0
java|red|0.80.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.22
selectline-statusbar|tom|0.0.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Closing this is an out of date TS version
