### ISSUE TITLE
[Bug] Typing suggestion is failing

### ISSUE THREAD

**Issue by htndev** [microsoft/vscode#129124]
- VS Code Version: 1.59.0-insider (Universal), 1.58.2
- OS Version: macOS Big Sur 11.4

Error:
```
Cannot read property 'program' of undefined: TypeError: Cannot read property 'program' of undefined
    at Object.getFunctionCalls (/Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/parser.js:74:57)
    at /Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:90:30
    at Generator.next (<anonymous>)
    at /Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:3:12)
    at createDecorations (/Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:85:12)
    at /Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:75:47
    at Generator.next (<anonymous>)
    at /Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:3:12)
    at run (/Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:56:12)
    at Timeout._onTimeout (/Users/alexandrvanilchuk/.vscode/extensions/lannonbr.vscode-js-annotations-0.11.0/out/extension.js:39:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

In another file (but Insiders):

```
Cannot read property 'start' of undefined: TypeError: Cannot read property 'start' of undefined
    at Object.<anonymous> (/Users/alexandrvanilchuk/.vscode-insiders/extensions/lannonbr.vscode-js-annotations-0.11.0/out/parser.js:236:71)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alexandrvanilchuk/.vscode-insiders/extensions/lannonbr.vscode-js-annotations-0.11.0/out/parser.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Steps to Reproduce:
1. Open javascript file.
2. Try to type.

[Video](https://user-images.githubusercontent.com/29665511/126533071-c642ccbe-b810-4275-abaa-d631faf0f718.mov)

**Comment by mjbvz** [comment]
Please file this against the lannonbr.vscode-js-annotations extension
