### ISSUE TITLE
TS Server fatal error:  ENOENT: no such file or directory, open '/Users/rmagyerramov/VSCodeProjects/customer-data-filters/target/bpm-packages/asset-bender-ffde989b/lodash@1.3/modules.manifest.json'

### ISSUE THREAD

**Issue by Romag** [microsoft/vscode#129163]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.2-hubspot

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: ENOENT: no such file or directory, open '/Users/rmagyerramov/VSCodeProjects/customer-data-filters/target/bpm-packages/asset-bender-ffde989b/lodash@1.3/modules.manifest.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at parseModulesManifest (/Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/ModuleManifest.js:209:37)
    at Function.manifestForPackage (/Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/ModuleManifest.js:72:41)
    at /Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/module-manifest-resolver.js:15:68
    at Array.forEach (<anonymous>)
    at setModuleManifestsForArchivePackages (/Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/module-manifest-resolver.js:14:14)
    at Object.createModuleManifestState (/Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/module-manifest-resolver.js:118:5)
    at Object.createCompleteResolverStateAsync (/Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/complete-resolver.js:46:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createResolverState (/Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/reactor-client.js:82:27)
    at async registerPath (/Users/rmagyerramov/.bpm/packages/hs-typescript/static-1.6/node_modules/@hs/asset-bender-client/lib/reactor-client.js:108:34)
    at async Promise.all (index 0)
```

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|--crash-reporter-id af608de6-82c9-4f02-b3a9-fe4ea2a5572c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
github-enterprise|Cod|11.0.13
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.0.1
hubspot-frontend-vscode|hub|0.0.18-HEAD
vscode-stylelint|sty|0.86.0
sass-indented|syl|1.8.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30340755
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Please file this against hubspot
