### ISSUE TITLE
TS Server fatal error:  Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by Plash-jindal** [microsoft/vscode#129251]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.5

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`/Users/plashjindal/Library/Application Support/Code/logs/20210723T124448/exthost8/vscode.typescript-language-features/tsserver-log-BKSnHR/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:608:37)
    at Buffer.toString (buffer.js:805:14)
    at readFileWorker (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:7512:31)
    at Object.readFile (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:7516:28)
    at getText (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156877:92)
    at TextStorage.getFileTextAndSize (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156889:32)
    at TextStorage.reloadWithFileText (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156800:31)
    at TextStorage.getOrLoadText (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156913:26)
    at TextStorage.getSnapshot (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156838:57)
    at ScriptInfo.getSnapshot (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156999:41)
    at ConfiguredProject.Project.getScriptSnapshot (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157668:39)
    at HostCache.createEntry (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152814:44)
    at new HostCache (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:152809:22)
    at synchronizeHostData (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153110:29)
    at Proxy.getProgram (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153308:13)
    at ConfiguredProject.Project.updateGraphWorker (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158256:53)
    at ConfiguredProject.Project.updateGraph (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158184:42)
    at ConfiguredProject.updateGraph (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159145:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160860:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:161898:44)
    at /private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162238:97
    at Object.flatMap (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162238:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:163293:46)
    at /private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165210:88
    at IOSession.Session.executeWithRequestId (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165201:28)
    at IOSession.Session.executeCommand (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165210:33)
    at IOSession.Session.onMessage (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165236:35)
    at Interface.<anonymous> (/private/var/folders/kn/sdspwbbs49l9r3gd001sg2g80000gn/T/AppTranslocation/84F32AC2-118E-4A90-9749-B5B7CB9986E3/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by mjbvz** [comment]
Does your project contain a really long file? Can you share a small project that demonstrates the issue?
