### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by ganeshp0001** [microsoft/vscode#129292]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.4.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-3","currentDirectory":"/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-3","currentDirectory":"/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular","hostCurrentDirectory":"/","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:127446:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:127432:29)
    at ProjectService.getOrCreateOpenScriptInfo (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:127826:33)
    at ProjectService.applyChangesInOpenFiles (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:128031:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:128801:46)
    at /Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/Users/ganeshpatil/Desktop/projects/HIHFS_2/hihfs_angular/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 6, 5|
|Memory (System)|8.00GB (1.94GB free)|
|Process Argv|--crash-reporter-id 21c50841-b5f9-49cb-ba9d-e581e8871fdf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
dart-code|Dar|3.24.2
flutter|Dar|3.24.0
prettier-vscode|esb|8.0.1
vscode-angular-html|gha|1.7.0
handlebars-preview|Gre|1.2.1
todo-tree|Gru|0.0.213
vscode-edit-csv|jan|0.6.0
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|1.9.1
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
awesome-flutter-snippets|Nas|3.0.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.1
language-stylus|sys|1.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Closing as outdated TS version
