### ISSUE TITLE
Remote SSH not working after the recent update. 

### ISSUE THREAD

**Issue by VIGNESHinZONE** [microsoft/vscode#129438]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Ubuntu 20.04
- Server: AWS EC2 instance

```
[23:13:13.855] askpass server listening on /run/user/1000/vscode-ssh-askpass-c4640e9241142c793b7dd57fd94c16f79294a09c.sock
[23:13:13.856] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-df5bf7a31613b1814e0c34e73d82922880aaacb4.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45689","-o","ConnectTimeout=15","ec2-3-113-14-118.ap-northeast-1.compute.amazonaws.com"],"dataFilePath":"/home/vignesh/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ec2-3-113-14-118.ap-northeast-1.compute.amazonaws.com-c3f126316369cd610563c75b1b1725e0679adfb3-0.65.7/data.json"}
[23:13:13.856] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-c4640e9241142c793b7dd57fd94c16f79294a09c.sock"}
[23:13:13.862] Spawned 27273
[23:13:13.977] > local-server-1> Spawned ssh, pid=27282
[23:13:13.980] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
[23:13:30.865] Terminating local server
[23:13:30.875] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64785)
	at Timeout._onTimeout (/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:264709)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[23:13:30.887] Local server exit: 15
[23:13:30.903] ------

```

This error has started only since today. I'm able to connect via ssh on my command line but not on VS code.
I had installed the latest updates yesterday and I have also reinstalled VS code twice to verify.

**Comment by roblourens** [comment]
Nothing changed on our end. Does a command like `echo "echo hello" | ssh -v -o ConnectTimeout=15 -T -D 45689 <your host>` work?
