### ISSUE TITLE
Tensor is disposed exception

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129590]
Testing #129436

1. Turn on `"workbench.editor.untitled.experimentalLanguageDetection": true`
2. Open a new untitled file, slowly start typing the following file character by character
3. Notice exception in developer tools console

```
 ERR Tensor is disposed.: Error: Tensor is disposed.
    at Tensor.throwIfDisposed (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3900:19)
    at Tensor.dataSync (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3845:14)
    at getParamValue (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:276:27)
    at executeOp$i (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6531:24)
    at /Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6632:56
    at /Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4529:22
    at Engine.scopedRun (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4539:23)
    at Engine.tidy (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4528:21)
    at Object.tidy (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:10277:19)
    at /Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6632:30
    at executeOp$j (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6648:7)
    at _loop_1 (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7406:31)
    at GraphExecutor.processStack (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7432:13)
    at GraphExecutor.<anonymous> (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7358:41)
    at step (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:81:23)
    at Object.next (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:62:53)
    at /Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:55:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:51:12)
    at GraphExecutor.executeWithControlFlow (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7327:16)
    at GraphExecutor.<anonymous> (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7277:51)
    at step (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:81:23)
    at Object.next (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:62:53)
    at /Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:55:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:51:12)
    at GraphExecutor._executeAsync (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7264:16)
    at GraphExecutor.<anonymous> (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7242:44)
    at step (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:81:23)
    at Object.next (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:62:53)
    at /Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-converter/dist/t
```

**Comment by TylerLeonhardt** [comment]
>     at Tensor.throwIfDisposed (/Users/isidor/.vscode-insiders/extensions/tylerleonhardt.auto-language-0.0.5/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3900:19)


@isidorn that's from my extension again.

**Comment by isidorn** [comment]
Sorry about that. Uninstalled it now.
