### ISSUE TITLE
Potential listener leak detected

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129527]
Testing #129161

@yuehuang010, @xisui-MSFT 

1. Start debugging
2. Open disassembly view, open developer console and notice a listener leak warning

It seems like we are not properly disposing listeners when an element gets disposed in a list.

```
potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:448
_event._event @ event.ts:523
renderElement @ disassemblyView.ts:413
renderElement @ tableWidget.ts:78
renderElement @ listWidget.ts:1081
insertItemInDOM @ listView.ts:781
render @ listView.ts:723
onScroll @ listView.ts:946
fire @ event.ts:579
(anonymous) @ scrollableElement.ts:187
fire @ event.ts:577
_setState @ scrollable.ts:371
setScrollPositionNow @ scrollable.ts:285
setScrollPosition @ scrollableElement.ts:579
setScrollTop @ listView.ts:870
reveal @ listWidget.ts:1702
reveal @ tableWidget.ts:336
(anonymous) @ disassemblyView.ts:138
Promise.then (async)
(anonymous) @ disassemblyView.ts:136
fire @ event.ts:577
(anonymous) @ scrollableElement.ts:187
fire @ event.ts:577
_setState @ scrollable.ts:371
setScrollPositionNow @ scrollable.ts:285
setScrollPositionSmooth @ scrollable.ts:291
_onMouseWheel @ scrollableElement.ts:432
S @ scrollableElement.ts:353
event.ts:449     at zo.renderElement (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1967:28244)
    at D.renderElement (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:71747)
    at U.renderElement (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:1753)
    at p.insertItemInDOM (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:124:18410)
    at p.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:124:17465)
    at p.onScroll (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:124:23460)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1732)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:120:16147
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at D._setState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:51586)
    at D.setScrollPositionNow (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:50013)
    at a.setScrollPosition (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:120:23532)
    at p.setScrollTop (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:124:20413)
    at G.reveal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:12527)
    at z.reveal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:146:734)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1967:22870
```

**Comment by xisui-MSFT** [comment]
@xisui-MSFT will fix this.

**Comment by xisui-MSFT** [comment]
@isidorn I think the listeners are not leaking, but there are a lot of them (actual number differs based on the size of the screen). So when you scroll up and down, you will see the same warning message repetitively. Although the number varies, it never grows infinitely. I.e., you got a ~175 listeners warning, it would unlikely reach a number higher than 200.

The line the warning complains:
https://github.com/microsoft/vscode/blob/adf904df67195448cc1afb6fe36d45ab5ed31688/src/vs/workbench/contrib/debug/browser/disassemblyView.ts#L413

It's disposed here:
https://github.com/microsoft/vscode/blob/adf904df67195448cc1afb6fe36d45ab5ed31688/src/vs/workbench/contrib/debug/browser/disassemblyView.ts#L440

However, I don't really know why similar issues are not complained elsewhere, so probably I missed something. Any suggestions?

**Comment by isidorn** [comment]
The problem is that most of those listeners should be added when you create a template and dispose when you dispose a template. Since they can be shared across elements.
Can you please try doing on the template level? When you do that much less listeners will be added / disposed, and they will not have to be re-added when you scroll.

**Comment by isidorn** [comment]
This is still happening if you follow my original steps. Thus reopening.
I suggest instead of having 
`this._disassemblyView.onDidChangeStackFrame(() => this.rerenderDebugStackframe(icon, currentElement.element)),`
inside each template that you simple listen from the outside and on `changeStackFrame` to refresh the whole tree

**Comment by tjx666** [comment]
[1f3] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:453


at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:45806
    at Array.map (<anonymous>)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:45799
    at new we (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2904:13550)
    at S._createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:574:1354)
    at S.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:574:773)
    at new fe (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2904:14317)
    at S._createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:574:1354)
    at S.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:574:773)
    at renderTemplate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2914:5006)
    at I.renderTemplate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:14914)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:1741
    at Array.map (<anonymous>)
    at H.renderTemplate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:1732)
    at R.alloc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…p/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:84:819)
    at d.insertItemInDOM (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:18042)
    at d.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:17630)
    at d.onScroll (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:23687)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1732)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:130:16190
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at k._setState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:20963)
    at k.setScrollDimensions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:18972)
    at o.setScrollDimensions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:130:18475)
    at d.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:17039)
    at $.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:9549)
    at V.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:18550)
    at Z.layoutBody (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2977:5250)
    at Z.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:191:18269)
    at a.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:20491)
    at r.layoutViews (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:33641)
    at relayout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:31706)
    at r.onViewChange (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:28552)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:159:29793
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at Z.setExpanded (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:191:16231)
    at Z.setExpanded (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:20245)
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:191:17894)

**Comment by mifi** [comment]
I also got this error. Resolved by removing from my workspace a super-folder that also has a sub-folder that was included as a folder in workspace. e.g this directory structure:

```
📁 super-folder <-- included as a workspace folder
  📁 sub-folder <-- included as a workspace folder
  📁 other-sub-folder
📁 other-folder
```

**Comment by tjx666** [comment]
happen when I open the extensions view:

![image](https://user-images.githubusercontent.com/41773861/151420244-3c61169f-aeff-412b-b8fb-0a531c2b3e19.png)
