### ISSUE TITLE
Large files crash language detection

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129597]
Refs: https://github.com/microsoft/vscode/issues/129436

1. Paste the following file in the new untitled file https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/checker.ts
2. Exception

I think we can easily solve this by just sending a part of the file to be detected. For example we can cap it at a 500 000 characters which should be enough for the detection algorithm

```
  ERR Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at Xe (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:22892)
    at Object.kernelFunc (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:105789)
    at o (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:242459)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:243406
    at y.scopedRun (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:240964)
    at y.runKernelFunc (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:243158)
    at y.runKernel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:241470)
    at stringSplit_ (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:437551)
    at Object.stringSplit__op [as stringSplit] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:392714)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:212953
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:213212
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:240843
    at y.scopedRun (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:240964)
    at y.tidy (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:240777)
    at Module.f (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:256518)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:212600
    at ar (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:215253)
    at hr.processStack (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:224679)
    at hr.executeWithControlFlow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:223909)
    at async hr._executeAsync (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:222881)
    at async Nt (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:187687)
    at async Promise.all (index 0)
    at async hr.executeWithControlFlow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:223941)
    at async hr._executeAsync (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:222881)
    at async fr.executeAsync (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/@vscode/vscode-languagedetection/dist/lib/index.js:2:230456)
```

**Comment by TylerLeonhardt** [comment]
This starts to fail around the 126,000 character count. To be a bit cautious, I'll set the max to 100,000

**Comment by TylerLeonhardt** [comment]
Interestingly if I take like... 100000 characters of that file, it thinks it's Julia with 98% confidence.

**Comment by TylerLeonhardt** [comment]
Ahh... I guess the first 100000 characters together the guess is Julia... if I do a random chunk of 100000 it does yield TS... maybe we should chunk it and run it and then average out the results?

**Comment by isidorn** [comment]
@TylerLeonhardt averaging out the results sounds fancy, we can try it out. Though I would first start simple, take some random chunk of 100 000 characters and just classify based on them. For this particular example I see you created an issue on the model, so let's see what they say.

**Comment by TylerLeonhardt** [comment]
ok I took the last 100000 of that same file and it thought it was C# lol so I'm just gonna take the first 100000 and see what feedback we get. My guess is that TypeScript in the TypeScript repo is not like "normal TypeScript".

**Comment by isidorn** [comment]
Does not crash -> verified.
Though as you say now it is identified as "Julia". We'll have to fine tune this next milestone.
