### ISSUE TITLE
invalid response: 501 not implemented in interactive window

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode#129674]
Issue Type: <b>Bug</b>

i have a .py file i run in an interactive window with cells
first i start a jupyter server in a WSL, then connect to it
when i try to run any cell, i get the error "Invalid response: 501 Not Implemented"

the server is started in the exact same working directory as the visual studio workspace

this doesnt always happen, i have a second jupyter server running in a different directory serving a different workspace and i can run interactive files no problem. Both use the same WSL and kernel within it

VS Code version: Code - Insiders 1.59.0-insider (e437d424c5e6de97632f5513229c7ebc2cf27a32, 2021-07-28T05:13:47.114Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (1.06GB free)|
|Process Argv|--crash-reporter-id 4285aea8-8024-49ba-97f2-9d60622a70f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|8.1.0
kite|kit|0.147.0
python|ms-|2021.8.1054534874-dev
vscode-pylance|ms-|2021.7.6-pre.1
jupyter|ms-|2021.8.1070546638
remote-containers|ms-|0.189.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
powershell-preview|ms-|2021.7.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by ghylander** [comment]
here the output for the 501 not implemented error:

```
Error 2021-07-28 11:11:13: DataScience Error [_ [Error]: 
	at new o (c:\Users\gus_h\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.1070546638\out\client\extension.js:16:23818)
	at new _ (c:\Users\gus_h\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.1070546638\out\client\extension.js:24:118194)
	at c:\Users\gus_h\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.1070546638\out\client\extension.js:90:236764
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 501 Not Implemented
	at c:\Users\gus_h\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.1070546638\out\client\node_modules\@jupyterlab\services.js:3:545096
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.SessionManager.startNew (c:\Users\gus_h\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.1070546638\out\client\node_modules\@jupyterlab\services.js:3:536620)] {
  category: 'unknown',
  originalException: [t [Error]: Invalid response: 501 Not Implemented
  	at c:\Users\gus_h\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.1070546638\out\client\node_modules\@jupyterlab\services.js:3:545096
  	at runMicrotasks (<anonymous>)
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
  	at async t.SessionManager.startNew (c:\Users\gus_h\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.1070546638\out\client\node_modules\@jupyterlab\services.js:3:536620)] {
    response: N [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    }
  }
}
```

here a screenshot of the not working workspace with the interactive window and error message, i tried to run the very first cell with the imports:

![image](https://user-images.githubusercontent.com/74593034/127296666-3e846b57-6701-4dd8-8ef8-84fc9f04f847.png)

Here a screenshot of the working worksapce with an executed cell:

![image](https://user-images.githubusercontent.com/74593034/127297139-3f6f2be2-90fb-4962-b1ac-207fea580ca2.png)
