### ISSUE TITLE
[Mac OSX 11.5] Cannot launch code after build from source on a case sensitive partition

### ISSUE THREAD

**Issue by swinder0161** [microsoft/vscode#129665]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: origin/main -> 762f213a29109d70e89b54d4232de97f51f8187c
- OS Version: MacOS 11.5

Steps to Reproduce:

1. Create a disk image and format as case sensitive APFS
2. git clone the main branch of vscode on new case sensitive volume
3. Build and run code with ./scripts/code.sh
4. Observer below log

Log:
`$ ./scripts/code.sh
yarn run v1.22.10
$ node build/lib/electron
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /Volumes/Data/code/vscode/resources/darwin/Bower.icns (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Volumes/Data/code/vscode/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:514:26)
    at Glob.emit (node:events:394:28)
    at Glob._finish (/Volumes/Data/code/vscode/node_modules/glob-stream/node_modules/glob/glob.js:197:8)
    at done (/Volumes/Data/code/vscode/node_modules/glob-stream/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Volumes/Data/code/vscode/node_modules/glob-stream/node_modules/glob/glob.js:688:12)
    at /Volumes/Data/code/vscode/node_modules/glob-stream/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Volumes/Data/code/vscode/node_modules/glob-stream/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Volumes/Data/code/vscode/node_modules/glob-stream/node_modules/glob/glob.js:764:12)
    at RES (/Volumes/Data/code/vscode/node_modules/inflight/inflight.js:31:16)
Emitted 'error' event on DestroyableTransform instance at:
    at Pumpify.emit (node:events:394:28)
    at Pumpify.Duplexify._destroy (/Volumes/Data/code/vscode/node_modules/duplexify/index.js:191:15)
    at /Volumes/Data/code/vscode/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by swinder0161** [comment]
I had to copy the files with correct name after build to make it working from case sensitive partition

![image](https://user-images.githubusercontent.com/397543/127323993-75674fcb-cf8f-4959-86e5-6db162766473.png)

**Comment by swinder0161** [comment]
@deepak1556 @meganrogge  please help to review and merge the PR #129987 to solve this problem.

**Comment by swinder0161** [comment]
@deepak1556 Please review and merge my change

**Comment by WiseCrohn** [comment]
I also hit this problem.  For me, @swinder0161 's fix doesn't work.  Renaming html.icns doesn't work because one part of the build looks for lower-case and another part looks for upper-case.
I think @LeuisKen 's fix (#130886) is more correct, especially because if you look at the comments (e.g. https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts#L26) it says that the icon parameter should be lower-cased before use - but it isn't - so looks like a straight bug.
However @LeuisKen 's fix is somewhat incomplete - you can't just change the typescript because the javascript for it doesn't seem to be generated as part of the build.  In fact electron.js (in same folder) has been checked into git (but, confusingly, is invisible when the folder is viewed in VSCode).  So you need to re-generate, or similarly edit, the javascript.

**Comment by deepak1556** [comment]
🤖 Thanks for the report. This was fixed in https://github.com/microsoft/vscode/commit/bfb7af52e543 and shipped in VS Code 1.91.0 — the `darwinBundleDocumentType` helper now lowercases the icon name before constructing the path, so the build works correctly on case-sensitive macOS volumes.

If you still see a problem on the latest build, please open a new issue with updated repro steps.
