### ISSUE TITLE
Smoke test failure: go to line

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129679]
Assigning to @hediet since Alex is out.

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=129290&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d

```
  1) VSCode Smoke Tests (Electron)
       Statusbar
         checks if 'Go to Line' works if called from the status bar:
     Error: Timeout: get element '.monaco-editor .view-overlays>:nth-child(15) .current-line' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:178:19)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:259:16)
      at async Editor.waitForHighlightingLine (/Users/runner/work/1/s/test/automation/out/editor.js:47:13)
```

**Comment by hediet** [comment]
Is this flaky? Which commit caused this failure?

**Comment by isidorn** [comment]
Unrelated commit https://github.com/Microsoft/vscode/compare/e437d42...e105383
I am not sure if there were some commits before that

**Comment by isidorn** [comment]
This just happened again https://dev.azure.com/monacotools/Monaco/_build/results?buildId=130598&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9

**Comment by hediet** [comment]
Do you have ideas how this can be debugged?

**Comment by bpasero** [comment]
For desktop based smoke tests we currently have no good way of checking why the test is flaky other than reviewing the code. Things that would probably help:
* being able to capture a screenshot upon failure (I suggested this to @joaomoreno and there is an option for it but it does not seem to work?)
* migrating to playwright even for electron based smoke tests and enabling the tracing option

**Comment by hediet** [comment]
Is this still relevant?
