### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by juanexpunker** [microsoft/vscode#129993]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/home/sistemas/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/node_modules/typescript/lib/tsserver.js:162223:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/sistemas/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/node_modules/typescript/lib/tsserver.js:163293:46)
    at /home/sistemas/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/node_modules/typescript/lib/tsserver.js:165210:88
    at IOSession.Session.executeWithRequestId (/home/sistemas/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/node_modules/typescript/lib/tsserver.js:165201:28)
    at IOSession.Session.executeCommand (/home/sistemas/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/node_modules/typescript/lib/tsserver.js:165210:33)
    at IOSession.Session.onMessage (/home/sistemas/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/node_modules/typescript/lib/tsserver.js:165236:35)
    at Interface.<anonymous> (/home/sistemas/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/node_modules/typescript/lib/tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.81GB (6.65GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/m/Proyectos%20plataforma%20visualMI6/visualMI6-react --remote=wsl+Ubuntu-18.04 --crash-reporter-id babdb02b-151b-4c05-8010-85b1b50aa8f6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|19.81GB (6.67GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|19.81GB (6.65GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-es|MS-|1.58.8
remote-wsl|ms-|0.58.2
debugger-for-chrome|msj|4.12.12
vscode-icons|vsc|11.6.0
rainbow-brackets|2gu|0.0.6
vscode-intelephense-client|bme|1.7.1
vscode-eslint|dba|2.1.23
php-debug|fel|1.17.0
php-intellisense|fel|2.3.14
vscode-phpfmt|kok|1.0.30
vscode-language-pack-es|MS-|1.58.8
indent-rainbow|ode|7.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
