### ISSUE TITLE
VS Code not opening in Ubuntu 20.04

### ISSUE THREAD

**Issue by jobic10** [microsoft/vscode#129978]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1
- OS Version: Ubuntu 20.04

Recently, I boot my laptop and launched VS Code (from the terminal). I even launched Emulator from within the editor which I used for Flutter.
Thereafter, I closed VS Code and tried opening another project, only to see nothing.
I disabled all extensions but still, same.

When I `code . --verbose`, I got :

```
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
(code:289448): Gtk-WARNING **: 17:25:40.420: Theme parsing error: gtk.css:1511:23: 'font-feature-settings' is not a valid property name
(code:289448): Gtk-WARNING **: 17:25:40.425: Theme parsing error: gtk.css:3437:25: 'font-feature-settings' is not a valid property name
(code:289448): Gtk-WARNING **: 17:25:40.426: Theme parsing error: gtk.css:3899:23: 'font-feature-settings' is not a valid property name
[289480:0802/172540.557655:ERROR:angle_platform_impl.cc(43)] Display.cpp:832 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[289480:0802/172540.558269:ERROR:gl_surface_egl.cc(774)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[289480:0802/172540.558633:ERROR:gl_surface_egl.cc(1329)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[289480:0802/172540.561106:ERROR:angle_platform_impl.cc(43)] Display.cpp:832 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[289480:0802/172540.561743:ERROR:gl_surface_egl.cc(774)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[289480:0802/172540.562131:ERROR:gl_surface_egl.cc(1329)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[289480:0802/172540.562467:ERROR:gl_initializer_linux_x11.cc(182)] GLSurfaceEGL::InitializeOneOff failed.
[289480:0802/172540.567492:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
libva error: dlopen of /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so failed: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so)
libva error: dlopen of /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so failed: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
[main 2021-08-02T16:25:40.656Z] [File Watcher (node.js)] Failed to watch /home/unknown/.config/Code/User for changes using fs.watch() (Error: ENOSPC: System limit for number of file watchers reached, watch '/home/unknown/.config/Code/User')
[main 2021-08-02T16:25:40.661Z] [File Watcher (node.js)] Failed to watch /home/unknown/.config/Code/User/settings.json for changes using fs.watch() (Error: ENOSPC: System limit for number of file watchers reached, watch '/home/unknown/.config/Code/User/settings.json')
[main 2021-08-02T16:25:40.693Z] Starting VS Code
[main 2021-08-02T16:25:40.694Z] from: /snap/code/70/usr/share/code/resources/app
[main 2021-08-02T16:25:40.694Z] args: {
  _: [ '/home/unknown/Documents/Flutter/sign_up_login_ui' ],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'cb38fdc7-3d56-46f5-afab-ae608927e29a',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/unknown/.config/Code/logs/20210802T172540'
}
[main 2021-08-02T16:25:40.697Z] Resolving machine identifier...
[main 2021-08-02T16:25:40.697Z] Resolved machine identifier: d592eb5ccfcc126764b2eb0f48054c950b09e251eb8a3ca0e06c7fbacef7fe7c
[main 2021-08-02T16:25:40.698Z] Main->SharedProcess#connect
[main 2021-08-02T16:25:40.744Z] update#setState idle
[main 2021-08-02T16:25:40.751Z] Error: ENOSPC: System limit for number of file watchers reached, watch '/snap/code'
    at FSWatcher.<computed> (internal/original-fs/watchers.js:218:26)
    at Object.watch (original-fs.js:1525:34)
    at new y (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:58:20816)
    at i._createInstance (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:1371)
    at i._createServiceInstance (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:3772)
    at i._createServiceInstanceWithOwner (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:3288)
    at i._createAndCacheServiceInstance (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:2963)
    at i._safeCreateAndCacheServiceInstance (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:2161)
    at i._getOrCreateServiceInstance (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:1882)
    at Object.get (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:450)
    at Pe.initChannels (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:59:63218)
    at /snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:59:58764
    at invokeFunction (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:29:319)
    at Pe.startup (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:59:58740)
    at async se.startup (/snap/code/70/usr/share/code/resources/app/out/vs/code/electron-main/main.js:61:1899)
[main 2021-08-02T16:25:40.751Z] Lifecycle#kill()

```

I have no idea what it means. 
If I should restart my PC and try again, VS code will work. And If I close it, and tried opening it up again, it will not come up.

**Comment by jobic10** [comment]
Seems this is not VS code issue.

Running `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` fixed it.
[Ref](https://github.com/gatsbyjs/gatsby/issues/11406)
