### ISSUE TITLE
Close document when cell is executing throws error

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#130054]
Issue Type: <b>Bug</b>

When a cell is still running and we close the notebook document, it throws an error
```
Failed to update output Error: Can't apply edits to unknown notebook model: file:///c%3A/Users/rebor/code/personal/notebooks/bugs/perf.dib
    at b.$applyExecutionEdits (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1544:28283)
    at r._doInvokeHandler (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:11989)
    at r._invokeHandler (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:11673)
    at r._receiveRequest (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:10335)
    at r._receiveOneMessage (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:9122)
    at vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:7218
    at l.fire (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at n.fire (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16477)
    at u._receiveMessage (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21743)
    at vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18621
    at l.fire (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at b.acceptChunk (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13838)
    at vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13186
    at Socket.T (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2899:159022)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) (at console.e.<computed> [as error] (c:\Users\rebor\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\microsoft-authentication\dist\extension.js:1:170797))
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

VS Code version: Code - Insiders 1.59.0-insider (ba0df885e9d6b0f0ccf2cc714c3fa31423572205, 2021-07-31T00:41:55.692Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Fetching remote diagnostics for 'codespaces+rebornix-microsoft-vscode-wr7p' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (11.49GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'codespaces+rebornix-microsoft-vscode-wr7p' timed out.
</details>

**Comment by rebornix** [comment]
Even after the document is closed, currently the .NET Interactive extension keeps sending outputs and trigger hundreds of similar errors.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/122271 and https://github.com/microsoft/vscode/issues/125668 too I guess
