### ISSUE TITLE
Creating an integrated terminal from a task causes the new terminal to hang

### ISSUE THREAD

**Issue by Mojachieee** [microsoft/vscode#130121]
Issue Type: <b>Bug</b>

Running a simple task that creates an integrated terminal fails on OSX. 

Steps to reproduce:
1. Copy the following task
2. Open command pallete and type "Tasks: Run task"
3. Select "Open terminal"
4. Observe that terminal does not open. 

Task: 
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Open terminal",
            "dependsOrder": "sequence",
            "dependsOn": [
                "OpenTerminal1",
            ],
            "problemMatcher": []
        },
        {
            "label": "OpenTerminal1",
            "command": "${command:workbench.action.terminal.new}",
            "type": "shell",
            "args": []
        },
    ],
}
```

This is the error that happens:
```
[2021-08-04 16:38:45.170] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.new
[2021-08-04 16:38:45.171] [renderer1] [trace] terminalInstance#ctor (instanceId: 2) ["${command:workbench.action.terminal.new}","/Users/auser/dev/arepo"]
[2021-08-04 16:38:45.337] [renderer1] [error] IShellLaunchConfig.executable not set: Error: IShellLaunchConfig.executable not set
    at Se._validateExecutable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:12:37766)
    at Se.start (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:12:37159)
    at S.start (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:12:53166)
    at y.start (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:12:47055)
    at Object.call (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:8338)
    at y.onPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:10:49795)
    at y.onRawMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:10:49154)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:10:48407
    at T.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:8:1726)
    at process.U (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:6:31321)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

These are the terminal profiles I have set:
```
 "terminal.integrated.defaultProfile.osx": "zsh",
 "terminal.integrated.profiles.osx": {
        "bash": {
            "path": "bash",
            "args": [
                "-l"
            ],
            "icon": "terminal-bash"
        },
        "zsh": {
            "path": "zsh",
            "args": [
                "-l"
            ],
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
    },
```

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.83GB free)|
|Process Argv|--log trace c2 --crash-reporter-id 719ba257-4dfc-42a8-ab54-1afaa72201f0|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472
bridge0723:30346310

```

</details>

The terminal never finishes opening and just hangs like this:
![Screenshot 2021-08-04 at 17 16 37](https://user-images.githubusercontent.com/16799580/128216978-3b8dc665-8678-475f-9425-cf8df624e2e4.png)

**Comment by meganrogge** [comment]
cc @alexr00

**Comment by alexr00** [comment]
Tasks could provide a better error here, but this is expected.
```
            "command": "${command:workbench.action.terminal.new}",
```
In the above, `${command:workbench.action.terminal.new}` doesn't resolve to anything. Task authors that use `${}` variable substitution need to be careful to only use `${}` variables that resolve to a string, or to make sure that if the variable doesn't resolve to a string that it will be safe (ex. use ` "command": "echo ${command:workbench.action.terminal.new}"` instead).
