### ISSUE TITLE
code insiders freezing on workspace trust screen

### ISSUE THREAD

**Issue by hkennyv** [microsoft/vscode#130299]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.60.0-insider
- OS Version: Mac OS 11.4 (Big Sur, M1 Macbook Air 2020)

```
khuynh@kmba:~ $ code-insiders --version
1.60.0-insider
a4eb4d688477fb9f2176bb2ed932b0b1726caed3
arm64
```

Steps to Reproduce:

1. launch vscode with the following: `code-insiders --verbose --log debug --disable-extensions . > vscode.log` (to be clear, it still freezes when launching without the extra option flags).
2. The resulting window is frozen and only shows the spinning rainbow wheel (not captured in screenshot)

![image](https://user-images.githubusercontent.com/29909203/128576636-6c62945c-3479-4883-8ad8-ab2f04df4583.png)

The resulting log file:
[vscode.log](https://github.com/microsoft/vscode/files/6948163/vscode.log)

It seems like the issue is related to:

```
Error: dlopen(/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node, 1): no suitable image found.  Did find:
>   /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: mach-o, but wrong architecture
>   /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: mach-o, but wrong architecture
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1185:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:698)
    at bindings (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at r.load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1722)
    at r.load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:10249)
    at l (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:10613)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:10319
    at r.load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1739)
    at r.load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:10249)
    at l (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:6145)
```

Very strange, as it was just working earlier today. 🤔

**Comment by hkennyv** [comment]
It looks like just re-downloading code insiders works. I'll close this issue I suppose and re-open if it happens again
