### ISSUE TITLE
Integration tests: several new exceptions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130316]
Run `scripts/test-integration.sh` and see several new stacks:

```
[15399:0807/075712.251982:INFO:CONSOLE(241)] "[uncaught exception]: TypeError: Cannot read property 'takeOwnership' of undefined", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/bootstrap-window.js (241)
[15399:0807/075712.252044:INFO:CONSOLE(244)] "TypeError: Cannot read property 'takeOwnership' of undefined
    at InlineCompletionsModel.trigger (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:94:42)
    at InlineCompletionsModel.startSessionIfTriggered (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:87:18)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:55:22", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/bootstrap-window.js (244)
[15399:0807/075712.252068:INFO:CONSOLE(94)] "Uncaught TypeError: Cannot read property 'takeOwnership' of undefined", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js (94)
```

and

```
Cannot read property 'getWordAtPosition' of null: TypeError: Cannot read property 'getWordAtPosition' of null
    at getDefaultRange (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:504:28)
    at provideInlineCompletions (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:513:37)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:278:36
    at createCancelablePromise (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/async.js:15:26)
    at InlineCompletionsSession.update (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:275:65)
    at RunOnceScheduler.runner (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.js:130:86)
    at RunOnceScheduler.doRun (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/async.js:616:22)
    at RunOnceScheduler.onTimeout (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/async.js:611:22)
```

and many of:

```
[15399:0807/075714.808236:INFO:CONSOLE(176)] "Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:176:34)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/suggest/suggestController.js:84:33
    at IdleValue._executor (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/async.js:769:35)
    at IdleValue.get value [as value] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/async.js:786:22)
    at SuggestController.stopForceRenderingAbove (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/suggest/suggestController.js:466:25)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/contrib/inlineCompletions/suggestWidgetAdapterModel.js:65:39
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:130:17
    at Object.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/functional.js:18:25)
    at dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:153:18)
    at SuggestWidgetAdapterModel.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:195:25)
    at dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:153:18)
    at GhostTextModel.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:195:25)
    at dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:153:18)
    at ActiveGhostTextController.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:195:25)
    at MutableDisposable.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:236:26)
    at dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:153:18)
    at GhostTextController.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:195:25)
    at CodeEditorWidget.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/editor/browser/widget/codeEditorWidget.js:192:53)
    at dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:160:17)
    at CodeCellRenderer.disposeTemplate (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.js:800:38)
    at PipelineRenderer.disposeTemplate (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/browser/ui/list/listWidget.js:820:26)
    at ListView.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/browser/ui/list/listView.js:1029:38)
    at dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:153:18)
    at NotebookCellList.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/browser/ui/list/listWidget.js:1368:30)
    at NotebookCellList.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/platform/list/browser/listService.js:213:19)
    at NotebookCellList.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:1057:19)
    at NotebookEditorWidget.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:2101:24)
    at NotebookEditorWidgetService._disposeWidget (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/notebook/browser/notebookEditorServiceImpl.js:90:20)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/notebook/browser/notebookEditorServiceImpl.js:45:30
```

**Comment by hediet** [comment]
Related to #130282. Caused by https://github.com/microsoft/vscode/pull/130037. Will investigate.

**Comment by bpasero** [comment]
To clarify: these are not causing any tests to fail, it is just noisy output.

**Comment by hediet** [comment]
[The log of a recent run of Electron Integration Tests](https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_apis/build/builds/130720/logs/92) does not contain `inlineCompletions` anymore.

I guess my fix was successful.
