### ISSUE TITLE
Extensions are disabled after update on nightly

### ISSUE THREAD

**Issue by Dzejkop** [microsoft/vscode#130373]
After the recent update all my extensions are disabled
![image](https://user-images.githubusercontent.com/5088647/128647097-2d857f94-f0ec-4c96-9717-f6bd72b9ae2c.png)

I cannot reenable them.

Does this issue occur when all extensions are disabled?: NA

- VS Code Version: 1.60.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:
???

**Comment by Dzejkop** [comment]
Reinstalling an extension does not help

Logs from `Log (Extension Host)`:
```
[2021-08-09 00:13:06.863] [exthost] [info] extension host terminating: renderer closed the socket
[2021-08-09 00:13:06.875] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
	at Object.n [as canceled] (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1157)
	at h._remoteCall (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12893)
	at Proxy.w.<computed>.E.charCodeAt.w.<computed> (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9388)
	at E.resolveProxy (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:36763)
	at Object.resolveProxy (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:57697)
	at useProxySettings (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:159:16)
	at c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:107:13
	at c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:335:13
	at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[2021-08-09 00:13:06.881] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
	at Object.n [as canceled] (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1157)
	at h._remoteCall (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12893)
	at Proxy.w.<computed>.E.charCodeAt.w.<computed> (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9388)
	at E.resolveProxy (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:36763)
	at Object.resolveProxy (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:57697)
	at useProxySettings (c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:159:16)
	at c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:107:13
	at c:\Users\Dzejkop\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:335:13
	at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[2021-08-09 00:13:07.879] [exthost] [info] exiting with code 0
[2021-08-09 00:13:08.662] [exthost] [info] extension host started
[2021-08-09 00:13:08.663] [exthost] [info] Skipping acquiring lock for c:\Users\Dzejkop\AppData\Roaming\Code - Insiders\User\workspaceStorage\9565f955fbd2ce26774bfc0ce4b5a8d6.
[2021-08-09 00:13:08.832] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-08-09 00:13:08.832] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-08-09 00:13:08.848] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-08-09 00:13:08.848] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/debug-auto-launch/dist/extension
[2021-08-09 00:13:08.853] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-09 00:13:08.853] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/git/dist/main
[2021-08-09 00:13:09.082] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-08-09 00:13:09.082] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-08-09 00:13:09.385] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-09 00:13:09.386] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github/dist/extension.js
[2021-08-09 00:13:09.398] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-08-09 00:13:09.398] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github-authentication/dist/extension.js
[2021-08-09 00:13:09.438] [exthost] [info] eager extensions activated
[2021-08-09 00:13:09.462] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-08-09 00:13:09.462] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-08-09 00:13:09.473] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-08-09 00:13:09.473] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-08-09 00:13:09.477] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl-recommender","_lower":"ms-vscode-remote.remote-wsl-recommender"},"activationEvent":"onStartupFinished"}
[2021-08-09 00:13:09.477] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Dzejkop/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender/dist/extension.js
```
