### ISSUE TITLE
Something went wrong activating IntelliCode support for Python

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/vscode#130533]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open VS Code
2. it show the dialog
![image](https://user-images.githubusercontent.com/17985592/128959341-daf58a81-0340-4f32-aa40-1f0f4b67a672.png)

3. VS IntelliCode log:
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at g._tryExecuteCommand (vscode-file://vscode-app/d:/programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1525:3364)
    at vscode-file://vscode-app/d:/programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1525:3245
Error while activating Python: {}

**Comment by rzhao271** [comment]
If you check the Python extension in the extensions viewlet, does it say something like "reload required"?
I'm not sure whether the extension is outdated or disabled in your case.
