### ISSUE TITLE
Turning on Settings Sync results in "Overlapping edit" error

### ISSUE THREAD

**Issue by gusbmurphy** [microsoft/vscode#130595]
I'm attempting to enable Settings Sync, but immediately get the following error in my log:

```
[2021-08-11 11:41:45.096] [settingssync] [info] Did reset the local sync state.
[2021-08-11 11:41:45.211] [settingssync] [error] Error: Overlapping edit
    at E (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:3123)
    at p (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:88347)
    at b (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:87152)
    at g (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:85846)
    at R.generateSyncPreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:91804)
    at async R.doGenerateSyncResourcePreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:43514)
```

I wasn't able to find others having this same issue.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: macOS 11.7

**Comment by sandy081** [comment]
@gusbmurphy May I know if you are still able to reproduce this issue? If so can you please share following logs while reproducing

- F1 > Open View > Log (Settings Sync)

**Comment by sandy081** [comment]
Please reopen the issue with requested information
