### ISSUE TITLE
vscode doesn't open without the --disable-crash-reporter flag

### ISSUE THREAD

**Issue by victormamede** [microsoft/vscode#130572]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
1.59.0
x64

- OS Version:
      Operating System: Solus 4.3 Fortitude
      Kernel: Linux 5.13.8-191.current
      Architecture: x86-64

Log with --verbose flag:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: submitURL must be specified when uploadToServer is true
    at CrashReporter.start (electron/js2c/browser_init.js:41:472)
    at configureCrashReporter (/usr/share/vscode/resources/app/out/main.js:427:17)
    at Object.<anonymous> (/usr/share/vscode/resources/app/out/main.js:61:2)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
    at Module._load (internal/modules/cjs/loader.js:747:15)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[10454:0811/093820.734615:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by bpasero** [comment]
Looks like https://github.com/microsoft/vscode/issues/130087

**Comment by deepak1556** [comment]
Can you confirm from where did you install vscode ? Also please provide the contents of `~/.vscode/argv.json`
