### ISSUE TITLE
Issues with updating Outputs via Notebook Cell Execution task

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#130788]
**Please use**
* Latest VS Code Insiders
* Custom branch of Jupyter extension (se below)
	PR in Jupyter extension https://github.com/microsoft/vscode-jupyter/pull/7100
	* Use the VSIX generated in the above PR (one of the assets in the CI is the Jupyter VSIX)
	* Or use the corresponding branch of the above PR

**Steps to repro**
* Create a Notebook with a single cell & run this cell.
* Output will not complete, notebook API seems to fall over & outputs are not updated.

**Please note:**
As we're no longer awaiting on the promises, any errors thrown will be ignored completely.
We don't even await on `<Execution Task>.end`

```python
import sys
import os
sys.stdout.write(f"Line1{os.linesep}")
sys.stdout.flush()
sys.stdout.write(os.linesep)
sys.stdout.flush()
sys.stdout.write(f"Line3{os.linesep}")
sys.stdout.flush()
sys.stdout.write("Line4")
```

Error in console window
```
ERR model index out of range -1: Error: model index out of range -1
    at n._assertIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1178:28502)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1178:17816
    at Array.map (<anonymous>)
    at n._doApplyEdits (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1178:17610)
    at n.applyEdits (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1178:17232)
    at S._applyExecutionEdits (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1180:36086)
    at S.update (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1180:35913)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1479:28841
    at Array.forEach (<anonymous>)
    at b.$updateExecutions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1479:28761)
    at n._doInvokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1486:11989)
    at n._invokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1486:11673)
    at n._receiveRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1486:10335)
    at n._receiveOneMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1486:9122)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1486:7218
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at r.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16477)
    at h._receiveMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21743)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:18621
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at b.acceptChunk (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13838)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13186
    at Socket.T (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2844:159359)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

@roblourens /cc

**Comment by roblourens** [comment]
I think it was fixed with #130789
