### ISSUE TITLE
Closing notebook while executing causes: Cannot read property 'pushStackElement' of null 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#130733]
Issue Type: <b>Bug</b>

1. Create a Jupyter notebook with a cell:

```py
for i in range(0,1000000):
    print(i)
```

2. Start running it
3. Before it finishes, close the notebook without saving

**Bug**
In the developer tools, see

```
ERR Cannot read property 'pushStackElement' of null: TypeError: Cannot read property 'pushStackElement' of null
    at NotebookTextModel.pushStackElement (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:274:36)
    at NotebookTextModel.applyEdits (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:292:18)
    at CellExecution._applyExecutionEdits (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/notebook/browser/notebookExecutionServiceImpl.js:110:33)
    at CellExecution.update (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/notebook/browser/notebookExecutionServiceImpl.js:101:18)
    at vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/api/browser/mainThreadNotebookKernels.js:195:31
    at Array.forEach (<anonymous>)
    at MainThreadNotebookKernels.$updateExecutions (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/api/browser/mainThreadNotebookKernels.js:188:28)
    at RPCProtocol._doInvokeHandler (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
```

VS Code version: Code - OSS Dev 1.60.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
@rebornix I believe this was introduced by fab260d2c18f1c652b5ddfeeab766f91daa69b89
