### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by MarcGilbertSparte** [microsoft/vscode#130755]
Issue Type: <b>Bug</b>

Every time I open my project, since I upgraded to Angular 9. No idea why

To add info : I updated Windows 10 last night as well, might be unrelated to the Angular upgrade. I'm reinstalling vs code right now, I'll see if it fixes it.

Update: reinstalling did not fix it. Still seeing the issue.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.10GB free)|
|Process Argv|--crash-reporter-id cf125283-1d12-416a-957d-180fe3eb77f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.6.0
vscode-projects-plus|fab|1.23.4
auto-rename-tag|for|0.1.8
vscode-pull-request-github|Git|0.29.1
angular2-switcher|inf|0.3.4
graphql-for-vscode|kum|1.15.3
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4673
debugger-for-chrome|msj|4.12.12
angular-console|nrw|17.8.0
typescript-hero|rbb|3.0.0
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.4
unique-window-colors|stu|1.0.51
vscode-icons|vsc|11.6.0
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748

```

</details>

**Comment by MarcGilbertSparte** [comment]
If I toggle Developer tools here are the errors I got :

```
ERR write EPIPE: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at v.write (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:511049)
    at d.write (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:499430)
    at d.sendRequest (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:501845)
    at d.sendNextRequests (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:501626)
    at d.executeImpl (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:501471)
    at h.execute (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:502704)
    at g.executeImpl (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:505941)
    at w.executeImpl (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:546433)
    at w.execute (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:545946)
    at m.flush (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:487164)
    at m.beforeCommand (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:486935)
    at S.beforeCommand (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:492817)
    at w.executeImpl (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:546394)
    at w.execute (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:545946)
    at d.updateStatus (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:524914)
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1732)
    at a.onDidChangeActiveTextEditor (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:550754)
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1732)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:59858
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at P.acceptDocumentsAndEditorsDelta (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:151623)
    at P.$acceptDocumentsAndEditorsDelta (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:149716)
    at h._doInvokeHandler (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
    at h._invokeHandler (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
    at h._receiveRequest (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11159)
    at h._receiveOneMessage (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at c.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at c.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
    at r._receiveMessage (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at v.acceptChunk (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
    at Socket.w (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

```
[Extension Host] Error: An extension called process.exit() and this was prevented.    at process.exit (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:28184)    at gracefulExit (c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\winston\lib\winston\exception-handler.js:194:17)    at c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\async\internal\once.js:12:16    at iteratorCallback (c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\async\eachOf.js:60:13)    at c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\async\internal\onlyOnce.js:12:16    at onetime (c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\one-time\index.js:23:16)    at File.<anonymous> (c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\winston\lib\winston\exception-handler.js:213:11)    at Object.onceWrapper (events.js:422:26)    at File.emit (events.js:327:22)    at File.EventEmitter.emit (domain.js:467:12)    at File.logged (c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\winston\lib\winston\transports\file.js:130:12)    at afterWrite (c:\Users\Marc\.vscode\extensions\rbbit.typescript-hero-3.0.0\node_modules\readable-stream\lib\_stream_writable.js:491:3)    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

```
ERR Could not create TS service. Service state:{"type":0}: Error: Could not create TS service. Service state:{"type":0}
    at w.service (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:537883)
    at w.executeImpl (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:546416)
    at w.execute (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:545946)
    at c.provideFoldingRanges (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:423324)
    at he.provideFoldingRanges (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:181213)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:198832
    at We._withAdapter (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:185649)
    at We.$provideFoldingRanges (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:198809)
    at h._doInvokeHandler (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
    at h._invokeHandler (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
    at h._receiveRequest (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11107)
    at h._receiveOneMessage (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at c.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at c.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
    at r._receiveMessage (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
    at d.fire (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at v.acceptChunk (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
    at c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
    at Socket.w (c:\Users\Marc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

The last one is logged again and again and again.

**Comment by MarcGilbertSparte** [comment]
It works now, I don't know why or how, I just fixed all my issues with my Angular upgrade. So it might have been related.

I'll close the issue !
