### ISSUE TITLE
TS Server fatal error:  Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by JeanJPNM** [microsoft/vscode#130870]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.5

**Steps to reproduce crash**
1. Clone the @sveltejs/kit repository
2. Open multiple files from different subrepositories (packages/*) and the test apps packages/kit/test/apps/**/*
4. Wait for the js language server to crash

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2024:20)
    at isNodeModulesOrScopedPackageDirectory (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19297:65)
    at guessDirectorySymlink (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19285:17)
    at Object.discoverProbableSymlinks (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19273:22)
    at ConfiguredProject.Project.getSymlinkCache (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157610:61)
    at Object.getSymlinkCache (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111783:29)
    at Object.host.compilerHost.realpath (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111842:36)
    at realPath (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40699:42)
    at Object.resolveTypeReferenceDirective (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40069:74)
    at c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158951:112
    at Object.map (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:451:29)
    at Function.AutoImportProviderProject.getRootFileNames (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158951:42)
    at Function.AutoImportProviderProject.create (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158984:38)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158792:77)
    at ConfiguredProject.Project.updateGraph (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158222:26)
    at ConfiguredProject.updateGraph (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159145:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160860:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161898:44)
    at c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162238:97
    at Object.flatMap (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162238:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:163293:46)
    at c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165210:88
    at IOSession.Session.executeWithRequestId (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165201:28)
    at IOSession.Session.executeCommand (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165210:33)
    at IOSession.Session.onMessage (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165236:35)
    at Interface.<anonymous> (c:\Users\jeanj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.23GB free)|
|Process Argv|--crash-reporter-id dc66333d-8084-4ae6-a346-72634e5bdd1a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
remotehub|Git|0.13.3
todo-tree|Gru|0.0.213
vscode-dependency-cruiser|jua|0.0.1
vscode-language-pack-pt-BR|MS-|1.59.3
vs-code-prettier-eslint|rve|3.0.4
vscode-status-bar-format-toggle|tom|2.0.0
vscode-icons|vsc|11.6.0
codesandbox|yes|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by JeanJPNM** [comment]
The issue cannot be repruced on the latest VS code insiders build.
