### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by inurdin** [microsoft/vscode#131022]
I tried to install on my 16" MBP, runs Catalina (10.15.7), but failedi with the following error.
VSCode just reinstalled using the most updated download.

[2021-08-17 17:18:17.753] **[renderer1] [error] Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found: unknown: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found**
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:16434
    at Array.reduce (<anonymous>)
    at P (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:16420)
    at T.joinAllSettled (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:9230)
    at async T.installExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:6775)

I have tried using direct install, CLI and VSIX installs. Outcome is all the same. Strangely, when I checked the VSIX file using unzip -t, the files are fine.

Regards,
Iman

**Comment by matthewmanley8451** [comment]
I can confirm, I am also having this issue. It effects multiple extensions. Not quite sure what causes one extension to work over another, but I have compiled a "short" list of extensions that do and do not work.

The following are some of the extensions I have tested and are not working:
https://marketplace.visualstudio.com/items?itemName=ms-python.python
https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
https://marketplace.visualstudio.com/items?itemName=redhat.java
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions
https://marketplace.visualstudio.com/items?itemName=ms-vscode.azurecli
https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

But these extensions seem to install perfectly fine:
https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker
https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2
https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

**Comment by KalyanMudundi** [comment]
> I can confirm, I am also having this issue. Running 16" MBP, Big Sur 11.5.2. I have tried multiple version of vscode, including the insider build, but none of them seem to work. I think it might be related to being on a corporate network or software, but I am the only person on my team who is having the issue.
> 
> It effects multiple extensions. Not quite sure what causes one extension to work over another, but I have compiled a "short" list of extensions that do and do not work.
> 
> The following are some of the extensions I have tested and are not working:
> https://marketplace.visualstudio.com/items?itemName=ms-python.python
> https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance
> https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
> https://marketplace.visualstudio.com/items?itemName=redhat.java
> https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
> https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions
> https://marketplace.visualstudio.com/items?itemName=ms-vscode.azurecli
> https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
> 
> But these extensions seem to install perfectly fine:
> https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
> https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
> https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker
> https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2
> https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

I am facing this exact same issue. Does anyone have any solution please?

**Comment by KalyanMudundi** [comment]
@joaomoreno  Can you please help us on this issue?

**Comment by joaomoreno** [comment]
What extension are you trying to install? inurdin

**Comment by sandy081** [comment]
Can you please point to a fresh user data dir and try again? To do this, you can launch code from command line as follows:
`code --user-data-dir <temp folder>`

**Comment by KalyanMudundi** [comment]
> Can you please point to a fresh user data dir and try again? To do this, you can launch code from command line as follows:
> `code --user-data-dir <temp folder>`

Hi @sandy081  I have tried using the above code and I am still facing the same issue. The error happens when installing python from extensions tab and also through VSIX file. As @matthewmanley8451  mentioned, this is happening only with certain extensions as he mentioned above. I was also able to install docker successfully. I am behind corporate netowrk/firewall.

**Comment by sandy081** [comment]
We download the VSIXes to a cached folder here `<user-data-dir>/CachedExtensionVSIXs`. Please check that the downloaded VSIXes are good. Also delete these VSIXes and try again?

**Comment by KalyanMudundi** [comment]
> We download the VSIXes to a cached folder here `<user-data-dir>/CachedExtensionVSIXs`. Please check that the downloaded VSIXes are good. Also delete these VSIXes and try again?

Hi @sandy081 Thanks for getting back. I see the VISXEs in that folder. I deleted and downloaded VSIXes numerous times but to no luck. For some reason those set of extensions are failing but extensions like are docker are working when behind corporate firewall/network. Any help to get this resolved is appreciated

**Comment by sandy081** [comment]
Can you please share those downloaded VSIXs? Can you also try downloading the same from Marketplace web site directly?

**Comment by KalyanMudundi** [comment]
> Can you please share those downloaded VSIXs? Can you also try downloading the same from Marketplace web site directly?

When I try to download from marketplace website its taking me directly to the marketplace in the vscode application(Which fails)

When I am trying to upload the downloaded VSIXs its "saying something went really wrong and we can't process that file", but here is the link to VSIX i'm trying to install https://marketplace.visualstudio.com/items?itemName=ms-python.python. 

When this is downloaded from vscode app it downloads a single VSIX file ms-python.python-2021.8.1159798656.vsix of size 16,355 KB

If I go to cacheExtensions directory I see two files ms-toolsai.jupyter-2021.8.1236758218 with size 10,384 KB and ms-python.python-2021.9.1191016588 with size 5,952 KB. 

Hope this helps.

**Comment by sandy081** [comment]
> When I try to download from marketplace website its taking me directly to the marketplace in the vscode application(Which fails)

I think you are trying to install from the marketplace web site. But you can download the vsix from there:

![Screenshot 2021-09-06 at 16 22 01](https://user-images.githubusercontent.com/10746682/132231292-e8b7ee6e-4954-4bc1-bdc0-210a032e7910.png)

**Comment by KalyanMudundi** [comment]
I missed that. Thank you @sandy081. This ones size is  15,838 KB. I was hoping it work as its a bit bigger in size compared to the downloads from VSIX, but it failed unfortunately :(. here is the error.

[2021-09-06 09:33:17.112] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at _.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/e062613/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196354)
    at async _.doRun (vscode-file://vscode-app/c:/Users/e062613/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195331)

**Comment by sandy081** [comment]
Can you please repeat it and share us following logs

`> F1 > Open View > Log (Shared)`

**Comment by KalyanMudundi** [comment]
Hi @sandy081 Here is the output:

[2021-09-06 10:03:21.394] [sharedprocess] [info] WSL is not installed, so could not detect WSL profiles
[2021-09-06 10:03:30.119] [sharedprocess] [info] Installing extension: ms-python.python
[2021-09-06 10:03:31.421] [sharedprocess] [info] Installing extension: ms-toolsai.jupyter
[2021-09-06 10:03:31.421] [sharedprocess] [info] Installing extension: ms-python.vscode-pylance
[2021-09-06 10:03:31.805] [sharedprocess] [info] Downloaded extension: ms-toolsai.jupyter drive:\\\xxx\xxx\xxx\xxx\xx\CachedExtensionVSIXs\ms-toolsai.jupyter-2021.8.1236758218
[2021-09-06 10:03:31.843] [sharedprocess] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-09-06 10:03:31.844] [sharedprocess] [error] validating: Corrupt ZIP: end of central directory record signature not found
    at _.downloadInstallableExtension (vscode-file://vscode-app/drive:///xxxx/xxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196354)
    at async _.doRun (vscode-file://vscode-app /drive://xxxx/xxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195331)
[2021-09-06 10:03:31.968] [sharedprocess] [info] Removed the extension from uninstalled list: ms-python.python
[2021-09-06 10:03:55.055] [sharedprocess] [info] Deleted from disk ms-python.python drive:\\\xxxx\xxxx\.vscode\extensions\ms-python.python-2021.9.1191016588

**Comment by KalyanMudundi** [comment]
Hi @sandy081  I think the issue is with Downloaded extension: ms-toolsai.jupyter <-- When I tried another extension with pylance, the same extension failed, not sure why they combine both python and jupyter.

**Comment by KalyanMudundi** [comment]
I followed ZhouqyCH  answer on  https://github.com/microsoft/vscode/issues/131232 and installed it via command line and it worked. Thanks a ton ZhouqyCH

**Comment by sandy081** [comment]
It would be great to share us following logs if you are reproducing it still, so that we can see what is wrong and fix it

`> F1 > Open View > Log (Shared)`

**Comment by matthewmanley8451** [comment]
Here is the log from that when I try to install the python extension.
```
[2021-09-14 11:05:10.022] [sharedprocess] [info] Installing extension: ms-python.python
[2021-09-14 11:05:10.292] [sharedprocess] [info] Downloaded extension: ms-python.python /Users/m812673/Library/Application Support/Code - Insiders/CachedExtensionVSIXs/ms-python.python-2021.9.1230869389
[2021-09-14 11:05:10.313] [sharedprocess] [error] Error while installing the extension: ms-python.python
[2021-09-14 11:05:10.313] [sharedprocess] [error] validating: Corrupt ZIP: end of central directory record signature not found
    at z.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:197442)
    at async z.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196419)
[2021-09-14 11:05:10.314] [sharedprocess] [error] Failed to install extension: ms-python.python Corrupt ZIP: end of central directory record signature not found
```

**Comment by sandy081** [comment]
Can you please delete the VSIX from her `/Users/m812673/Library/Application Support/Code - Insiders/CachedExtensionVSIXs/ms-python.python-2021.9.1230869389` and try again?

**Comment by lpanichi** [comment]
I have the same problem but I'm using a portable vs-code.
I described mi issue here : https://github.com/microsoft/vscode-python/issues/17491

**Comment by sandy081** [comment]
@matthewmanley8451 Please try deleting the vsix and try again

**Comment by matthewmanley8451** [comment]
Deleting the VSIX does not fix the issue unfortunately

**Comment by sandy081** [comment]
It could be that other VSIX is causing it, lets start from clean slate. Please delete all VSIXs in that folder `/Users/m812673/Library/Application Support/Code - Insiders/CachedExtensionVSIXs` and try.

Enable the log level to trace using command `Set Log Level` before retrying and provide us with following logs if you see the error

` F1 > Open View > Log (Shared)`
