### ISSUE TITLE
TS Server fatal error:  Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by nijo-sokowatch** [microsoft/vscode#131169]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'forEach' of undefined
    at Object.clearMap (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:18608:13)
    at ProjectService.stopWatchingWildCards (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161007:20)
    at ConfiguredProject.releaseParsedConfig (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159119:37)
    at /snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159223:34
    at Map.forEach (<anonymous>)
    at ConfiguredProject.close (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159222:66)
    at ProjectService.removeProject (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160276:25)
    at /snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162098:86
    at Map.forEach (<anonymous>)
    at ProjectService.removeOrphanConfiguredProjects (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162098:44)
    at ProjectService.cleanupAfterOpeningFile (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162042:22)
    at ProjectService.applyChangesInOpenFiles (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162246:26)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:163293:46)
    at /snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165210:88
    at IOSession.Session.executeWithRequestId (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165201:28)
    at IOSession.Session.executeCommand (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165210:33)
    at IOSession.Session.onMessage (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165236:35)
    at Interface.<anonymous> (/snap/code/71/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.11.0-25-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 3090)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 2|
|Memory (System)|7.54GB (0.36GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch /home/nijojacob/Documents/Docs/Work/Sokowatch/repo/wms/wms-rewrite/fmcg-wms-wui --crash-reporter-id 5c025c4b-b726-475e-865a-a37be7fa2e72|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.2.0
atlascode|atl|2.9.1
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
turbo-console-log|Cha|2.1.6
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
vscode-docker|ms-|1.16.0
csharp|ms-|1.23.14
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
cpptools|ms-|1.5.1
debugger-for-chrome|msj|4.12.12
quicktype|qui|12.0.46
ruby|reb|0.28.1
java|red|0.81.0
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
slim|sia|0.1.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.2
vscode-maven|vsc|0.32.2
vscode-icons|vsc|11.6.0
vscode-ruby|win|0.28.0

</details>

**Comment by nijo-sokowatch** [comment]
seems like a duplicate
