### ISSUE TITLE
Flaky test: vscode - untitled automatic language detection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#131268]
```
  1 failing
  1) vscode - untitled automatic language detection
       test automatic language detection works:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:554:17)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=131883&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=378

**Comment by TylerLeonhardt** [comment]
This should be fixed in the next version of tfjs...
