### ISSUE TITLE
Installing extension on remote host takes forever

### ISSUE THREAD

**Issue by AkshayRoyal** [microsoft/vscode#131242]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58 and 1.59
- OS Version: RHEL 8.4

Steps to Reproduce:

1. ssh to some remote web server (in my case it is my academic institution's High power computing server)
2. once the vs code is initialized for the server, go to extensions and try installing any extension on the remote host. On clicking install on <host>, it shows installing for a very long time.
3. I tried installing python extensions, C++ extensions, all of them take too long time. So, long that I have to close the host connection.
4.  Upon reestablishing the connection I can see the extensions installed(sometimes but not always)

**Comment by sandy081** [comment]
Can you please provide following logs while you reproduce the issue?

- View -> Open View… -> Log (Shared)
- View -> Open View… -> Log (Window)
- - View -> Open View… -> Log (Remote)

**Comment by AkshayRoyal** [comment]
@sandy081 

log(window) is empty

log(main)
```
[2021-08-20 14:18:57.708] [main] [info] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[2021-08-20 14:18:57.742] [main] [info] update#setState idle
[2021-08-20 14:19:03.878] [main] [info] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[2021-08-20 14:19:27.744] [main] [info] update#setState checking for updates
[2021-08-20 14:19:27.827] [main] [info] update#setState idle
[2021-08-20 14:24:30.570] [main] [info] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
```

log(shared) 
```[2021-08-20 14:19:08.626] [sharedprocess] [info] [logs cleanup]: Starting to clean up old logs.
[2021-08-20 14:19:08.627] [sharedprocess] [info] [logs cleanup]: Removing log folders '20210820T121451, 20210820T121615'
[2021-08-20 14:19:28.626] [sharedprocess] [info] [code cache cleanup]: Starting to clean up old code cache folders.
[2021-08-20 14:19:28.626] [sharedprocess] [info] [storage cleanup]: Starting to clean up storage folders.
[2021-08-20 14:19:28.627] [sharedprocess] [info] [storage cleanup]: Deleting storage folder 1629443346825.
[2021-08-20 14:19:28.627] [sharedprocess] [info] [storage cleanup]: Deleting storage folder 1629444230994.
[2021-08-20 14:19:28.627] [sharedprocess] [info] [storage cleanup]: Deleting storage folder 1629444464283.
[2021-08-20 14:19:28.628] [sharedprocess] [info] [storage cleanup]: Deleting storage folder 1629444469957.
[2021-08-20 14:19:28.628] [sharedprocess] [info] [storage cleanup]: Deleting storage folder 1629444751249.
[2021-08-20 14:19:28.628] [sharedprocess] [info] [storage cleanup]: Deleting storage folder 1629444755415.
[2021-08-20 14:19:28.628] [sharedprocess] [info] [storage cleanup]: Deleting storage folder 1629444780441.
[2021-08-20 14:19:38.626] [sharedprocess] [info] [language pack cache cleanup]: Starting to clean up unused language packs.
```

logs(remote server)
```
[2021-08-20 14:24:45.308] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2021-08-20 14:24:45.308] [remoteagent] [info] Extension host agent started.
[2021-08-20 14:24:45.548] [remoteagent] [info] [127.0.0.1][e10b9382][ManagementConnection] New connection established.
[2021-08-20 14:24:45.565] [remoteagent] [info] [127.0.0.1][972019e4][ExtensionHostConnection] New connection established.
[2021-08-20 14:24:45.570] [remoteagent] [info] [127.0.0.1][972019e4][ExtensionHostConnection] <12127> Launched Extension Host Process.

```

logs(extension host)

```
[2021-08-20 14:24:31.470] [exthost] [info] extension host started
[2021-08-20 14:24:31.483] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"},"activationEvent":"onResolveRemoteAuthority:ssh-remote"}
[2021-08-20 14:24:31.483] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/private/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension
[2021-08-20 14:24:46.420] [exthost] [info] eager extensions activated
[2021-08-20 14:24:46.425] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-08-20 14:24:46.425] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-08-20 14:24:46.432] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"},"activationEvent":"onStartupFinished"}
[2021-08-20 14:24:46.432] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/private/.vscode/extensions/ms-vscode-remote.remote-containers-0.191.1/dist/extension/extension
[2021-08-20 14:24:46.450] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onStartupFinished"}
[2021-08-20 14:24:46.450] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/private/.vscode/extensions/ms-vscode-remote.remote-wsl-0.58.2/dist/extension
[2021-08-20 14:24:46.929] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-08-20 14:24:46.929] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
```

log(Remote extension host)
```
[2021-08-20 14:24:46.573] [exthost] [info] extension host started
[2021-08-20 14:24:46.648] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-08-20 14:24:46.648] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/maths/private/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/extensions/debug-auto-launch/dist/extension
[2021-08-20 14:24:46.658] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-20 14:24:46.658] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/maths/private/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/extensions/git/dist/main
[2021-08-20 14:24:46.757] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":true,"extensionId":{"value":"ms-vscode.cpptools","_lower":"ms-vscode.cpptools"},"activationEvent":"*"}
[2021-08-20 14:24:46.757] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/maths/private/.vscode-server/extensions/ms-vscode.cpptools-1.5.1/dist/main
[2021-08-20 14:24:47.113] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-08-20 14:24:47.113] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/maths/private/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/extensions/ms-vscode.js-debug/src/extension.js
[2021-08-20 14:24:47.390] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":false,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-20 14:24:47.390] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/maths/private/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/extensions/github/dist/extension.js
[2021-08-20 14:24:56.889] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-08-20 14:24:56.890] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/maths/private/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/extensions/emmet/dist/node/emmetNodeMain
[2021-08-20 14:24:56.919] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-08-20 14:24:56.919] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/maths/private/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/extensions/merge-conflict/dist/mergeConflictMain

```

There is some vscode merge conflict in logs (remote extension). I cannot comprehend what it is but I guess it has something to do with the issue.

**Comment by sandy081** [comment]
Have you tried installing the extension when these logs are captured? It seems there is no activity of installing extensions.

**Comment by AkshayRoyal** [comment]
Yes, I was installing the Python extension while I was copying the logs, I noted the time when I clicked the install button but nothing was added to logs after that time instance.

**Comment by sandy081** [comment]
Weird, is the connection to remote active? Are there any errors in the devtool/console?

**Comment by AkshayRoyal** [comment]
Yes, the connection with the remote is active and all the logs are getting updated in the .vscode-server directory on the host

**Comment by sandy081** [comment]
Do you have this setting set - `remote.downloadExtensionsLocally` ?

**Comment by AkshayRoyal** [comment]
That option wasn't checked earlier but I checked it and retried everything. This time I can see the log for extension installation

logs(Remote Server)
```
[2021-08-20 16:06:32.621] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2021-08-20 16:06:32.622] [remoteagent] [info] Extension host agent started.
[2021-08-20 16:06:33.489] [remoteagent] [info] [127.0.0.1][7d303744][ManagementConnection] New connection established.
[2021-08-20 16:06:33.519] [remoteagent] [info] [127.0.0.1][d25bf354][ExtensionHostConnection] New connection established.
[2021-08-20 16:06:33.525] [remoteagent] [info] [127.0.0.1][d25bf354][ExtensionHostConnection] <12111> Launched Extension Host Process.
[2021-08-20 16:08:41.939] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-20 16:08:43.217] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-20 16:08:50.463] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-20 16:10:49.284] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-python.python
[2021-08-20 16:10:49.288] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-20 16:10:49.289] [remoteagent] [error] Failed to install extension: ms-python.python connect ETIMEDOUT 13.107.42.18:443
[2021-08-20 16:10:50.432] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-python.vscode-pylance
[2021-08-20 16:10:50.432] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-20 16:10:50.433] [remoteagent] [error] Failed to install extension: ms-python.vscode-pylance connect ETIMEDOUT 13.107.42.18:443
[2021-08-20 16:10:58.994] [remoteagent] [info] Extracted extension to /home/maths/integrated/mt6130583/.vscode-server/extensions/.bf0359ef-936d-4cff-8785-fbeb716de151: ms-toolsai.jupyter
[2021-08-20 16:10:59.023] [remoteagent] [info] Renamed to /home/maths/integrated/mt6130583/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-20 16:10:59.030] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-20 16:10:59.040] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
```

**Comment by sandy081** [comment]
It seems like your remote has network connection issues, so I would recommend to check above setting so that extensions are downloaded locally and streamed to remote. 

> Error while preparing to install dependencies and extension packs of the extension: ms-python.python
Above error is already fixed and available in next release - https://github.com/microsoft/vscode/issues/130962

**Comment by AkshayRoyal** [comment]
@sandy081  did you check the IP address mentioned in the logs? 13.107.42.18
it belongs to Microsoft and if you try to reach it, it shows 
```
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0FIofYQAAAABP7/H30+eeQr0v4iSmgqOyREVMMDFFREdFMDMxMQBFZGdl
```

So, are you sure that there is issue at my host's network?

**Comment by sandy081** [comment]
May be with your DNS as I do not think Marketplace service is up and running. So can you please check if the remote machine has any proxy set up or DNS resolving to wrong IP addresses.
