### ISSUE TITLE
Cannot open folder from command line when VS Code update is pending

### ISSUE THREAD

**Issue by hforeste** [microsoft/vscode#131202]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Wait until VS Code has an update
2. In Windows Terminal, type `code` in a directory

Output:
```
D:\Development\MyProject>code .
internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

Issue https://github.com/microsoft/vscode/issues/129072 is somewhat similar but after the update is done I can successfully open a folder from command line.

**Comment by jcmrva** [comment]
I experienced this for the first time today. 
- Update 1.73.1 was pending.
- I got the same error as above.
- I opened Code from the taskbar & ran the update.
- `code .` still failed the same way.
- Fixed by uninstall/reinstall.

**Comment by dmitrivMS** [comment]
@hforeste @jcmrva Has this ever happened with recent VS Code updates?

**Comment by jcmrva** [comment]
@dmitrivMS No, I haven't seen this since I mentioned it here.

**Comment by dmitrivMS** [comment]
Ok, thanks. We've had quite a few changes since this was last updated, so I'll close and please ping me if it reoccurs.
