### ISSUE TITLE
Blazor dotnet watch run in devcontainer crashes extension host after saving file

### ISSUE THREAD

**Issue by biltongza** [microsoft/vscode#131305]
Issue Type: <b>Bug</b>

I am trying to work on my website in a dev container and every time I save a file, even if I don't make any changes, VSCode tells me the window has disconnected and I need to reload it. Opening the developer tools shows me the extension host has experienced multiple errors and then says the container is no longer running.

```console.ts:137 [Extension Host] Error: stream ended with:4 but wanted:9    at u (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57708)    at c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57889    at s (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5302)    at Socket.<anonymous> (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5472)    at Socket.emit (events.js:327:22)    at endReadableNT (internal/streams/readable.js:1327:12)    at processTicksAndRejections (internal/process/task_queues.js:80:21)
S @ console.ts:137
console.ts:137 [Extension Host] Exception thrown by PacketStream substream end handler Error: stream ended with:4 but wanted:9
    at u (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57708)
    at c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57889
    at s (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5302)
    at Socket.<anonymous> (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5472)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
S @ console.ts:137
console.ts:137 [Extension Host] Error: stream ended with:4 but wanted:9    at u (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57708)    at c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57889    at s (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5302)    at Socket.<anonymous> (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5472)    at Socket.emit (events.js:327:22)    at endReadableNT (internal/streams/readable.js:1327:12)    at processTicksAndRejections (internal/process/task_queues.js:80:21)
S @ console.ts:137
console.ts:137 [Extension Host] Exception thrown by PacketStream substream end handler Error: stream ended with:4 but wanted:9
    at u (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57708)
    at c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57889
    at s (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5302)
    at Socket.<anonymous> (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5472)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
S @ console.ts:137
console.ts:137 [Extension Host] Error: stream ended with:4 but wanted:9    at u (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57708)    at c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:7:57889    at s (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5302)    at Socket.<anonymous> (c:\Users\logan.dam\.vscode\extensions\ms-vscode-remote.remote-containers-0.191.1\dist\extension\extension.js:12:5472)    at Socket.emit (events.js:327:22)    at endReadableNT (internal/streams/readable.js:1327:12)    at processTicksAndRejections (internal/process/task_queues.js:80:21)
S @ console.ts:137
log.ts:301   ERR [remote-connection][Management   ][6e7b6…][reconnect] A RemoteAuthorityResolverError occurred while trying to reconnect. Will give up now! Error:
log.ts:301   ERR Error: Container is no longer running.
    at br.resolveAuthority (extensionHostManager.ts:289)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async tl._resolveAuthorityAgain (extensionService.ts:319)
abstractExtensionService.ts:615 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:615
log.ts:301   ERR [remote-connection][ExtensionHost][a0f21…][reconnect] A RemoteAuthorityResolverError occurred while trying to reconnect. Will give up now! Error:
log.ts:301   ERR Error: Container is no longer running.
    at br.resolveAuthority (extensionHostManager.ts:289)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async tl._resolveAuthorityAgain (extensionService.ts:319)
console.ts:137 [Extension Host] Shell server terminated (code: 137, signal: null)```

Steps to reproduce:
1. Clone my repo and open a razor file in `client/`
2. Open a terminal and run `dotnet watch run`
3. Save the razor file

Expected results: the file saves properly.
Actual results: VSCode window crashes.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Fetching remote diagnostics for 'Dev Container: C# (.NET)' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (16.62GB free)|
|Process Argv|--folder-uri vscode-remote://dev-container%2B633a5c6465765c6c64616d2e636f2e7a61/workspaces/ldam.co.za --crash-reporter-id c2eb1839-92da-4408-96c4-14d4c8c4a2a3|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'Dev Container: C# (.NET)' failed: Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30351387
vstre464cf:30350173
bridge0723:30353136
vsdyn321cf:30354108

```

</details>

<!-- generated by issue reporter -->

**Comment by isidorn** [comment]
Probably an extension issue, however first forwarding to @stuartleeks and feel free close as "caused by extension"
