### ISSUE TITLE
Failing web view integration test

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#131477]
```
vscode API - webview
       webviews with retainContextWhenHidden should preserve their page position when hidden:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\webview.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=132202&view=logs&j=24a3b84e-db50-5143-6e9a-d87cf4b12ca4&t=515e2e19-21a7-551c-6258-85858dc9a660

**Comment by mjbvz** [comment]
I believe this test is enabled already on desktop

Still disabled on web though along with the rest of the webview tests. That's tracked by #131622
