### ISSUE TITLE
cann't install extension offline

### ISSUE THREAD

**Issue by LForgit** [microsoft/vscode#131472]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.1
- OS Version: win10 17663.379

Steps to Reproduce:

1.code --install-extension XXX.vsix
2.log below
nstalling extensions...
(node:13544) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
connect ETIMEDOUT 13.107.42.18:443
Failed Installing Extensions: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/bin/ms-python.python-2021.7.1060902895.vsix
(node:13544) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at D (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1157)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:60398
    at U.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:8:1712)
    at F.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:8:5928)
    at R.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:8:6469)
    at Object.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:60531)
    at ie.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:15:25392)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:15:16154
    at Array.forEach (<anonymous>)
    at x.installExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:15:16132)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async b.installVSIX (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:10:260)
    at async c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:9:10268
    at async Promise.all (index 0)
    at async b.installExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:9:10222)
    at async c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:35192
    at async Object.M [as main] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:38625)
    at async N (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:12:13842)
(node:13544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 1)
(node:13544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by isidorn** [comment]
Here's the original duplicate issue https://github.com/microsoft/vscode/issues/82524
