### ISSUE TITLE
Flaky tests in extHostDocumentSaveParticipant.test.ts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13148]
Our latest release candidate commit 602155b saw these tests succeed once but fail on a second run, in our internal build:

```
2016-10-03T06:10:29.5817675Z   1) ExtHostDocumentSaveParticipant event delivery, overall timeout:
2016-10-03T06:10:29.5817675Z       AssertionError: false == true
2016-10-03T06:10:29.5817675Z       + expected - actual
2016-10-03T06:10:29.5817675Z       -false
2016-10-03T06:10:29.5817675Z       +true
2016-10-03T06:10:29.5817675Z       
2016-10-03T06:10:29.5817675Z       at D:\work\3\s\out-build\vs\workbench\test\node\api\extHostDocumentSaveParticipant.test.js:151:24
2016-10-03T06:10:29.5817675Z       at Object.notifySuccess [as _notify] (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1170:59)
2016-10-03T06:10:29.5817675Z       at Object.enter (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:852:30)
2016-10-03T06:10:29.5817675Z       at Promise_ctor._run (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1068:29)
2016-10-03T06:10:29.5817675Z       at Promise_ctor._completed (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1036:18)
2016-10-03T06:10:29.5817675Z       at D:\work\3\s\out-build\vs\base\common\async.js:317:17
2016-10-03T06:10:29.5974615Z       at CompletePromise_done [as done] (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1524:34)
2016-10-03T06:10:29.5974615Z       at Object.notifySuccess [as _notify] (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1180:48)
2016-10-03T06:10:29.5974615Z       at Object.enter (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:852:30)
2016-10-03T06:10:29.5974615Z       at _run (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1068:29)
2016-10-03T06:10:29.5974615Z       at _completed (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1036:18)
2016-10-03T06:10:29.5974615Z       at CompletePromise_ctor.CompletePromise_then [as then] (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1566:49)
2016-10-03T06:10:29.5974615Z       at Object.enter (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:747:28)
2016-10-03T06:10:29.5974615Z       at _run (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1068:29)
2016-10-03T06:10:29.5974615Z       at _setCompleteValue (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1052:18)
2016-10-03T06:10:29.5974615Z       at Object.notifySuccess [as _notify] (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1170:28)
2016-10-03T06:10:29.5974615Z       at Object.enter (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:901:30)
2016-10-03T06:10:29.5974615Z       at Promise_ctor._run (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1068:29)
2016-10-03T06:10:29.5974615Z       at Promise_ctor._error (D:\work\3\s\out-build\vs\base\common\winjs.base.raw.js:1041:18)
2016-10-03T06:10:29.5974615Z       at Timeout._onTimeout (D:\work\3\s\out-build\vs\workbench\api\node\extHostDocumentSaveParticipant.js:107:62)
```

**Comment by jrieken** [comment]
it's weird...

**Comment by bpasero** [comment]
I see this test failing a couple of times per day, reopening. E.g. https://travis-ci.org/Microsoft/vscode/jobs/176670300
