### ISSUE TITLE
Python and Pylance extensions failing to install on remote host

### ISSUE THREAD

**Issue by lauracosgrove** [microsoft/vscode#131547]
Issue Type: <b>Bug</b>

With the following settings on a remote host with no internet access, I am not able to install python and pylance extensions due to the jupyter extension file already existing. 

    "remote.SSH.localServerDownload": "always",
    "remote.downloadExtensionsLocally": true,

Log:

[2021-08-24 09:16:48.854] [remoteagent] [info] [127.0.0.1][82fc4f69][ExtensionHostConnection] <84979> Launched Extension Host Process.
[2021-08-24 09:33:29.290] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:31.069] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:37.608] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:37.844] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:38.130] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:38.334] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:38.691] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:39.302] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:39.632] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:39.778] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:40.651] [remoteagent] [info] Deleted from disk ms-toolsai.jupyter /users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-24 09:33:41.209] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:41.392] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:41.820] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:43.435] [remoteagent] [info] Extracted extension to /users/a/.vscode-server/extensions/.6f1da5ef-699e-4143-97cb-538aa40610d3: ms-toolsai.jupyter
[2021-08-24 09:33:43.450] [remoteagent] [info] Renamed to /users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-24 09:33:43.454] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-24 09:33:43.460] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
[2021-08-24 09:33:44.979] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:45.178] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:45.315] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:45.977] [remoteagent] [info] Deleted from disk ms-toolsai.jupyter /users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-24 09:33:46.018] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:46.121] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:46.250] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:46.404] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:46.726] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:47.107] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:48.993] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:49.111] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-24 09:33:50.260] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-24 09:33:51.226] [remoteagent] [info] Extracted extension to /users/a/.vscode-server/extensions/.13efd12e-2377-4a0c-9a9c-962bb0e65a80: ms-toolsai.jupyter
[2021-08-24 09:33:51.241] [remoteagent] [info] Renamed to /users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-24 09:33:51.246] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-24 09:33:51.253] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
[2021-08-24 09:33:51.495] [remoteagent] [info] Extracted extension to /users/a/.vscode-server/extensions/.affb66a9-ecfd-46c1-8b26-951f8a2dd4d7: ms-toolsai.jupyter
[2021-08-24 09:33:51.926] [remoteagent] [info] Rename failed because of EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.affb66a9-ecfd-46c1-8b26-951f8a2dd4d7' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'. Deleted from extracted location /users/a/.vscode-server/extensions/.affb66a9-ecfd-46c1-8b26-951f8a2dd4d7
[2021-08-24 09:33:51.927] [remoteagent] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-08-24 09:33:51.929] [remoteagent] [error] EEXIST: EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.affb66a9-ecfd-46c1-8b26-951f8a2dd4d7' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'
    at y.rename (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:81014)
    at async y.extractUserExtension (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:77848)
    at async Q.extract (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:90124)
[2021-08-24 09:33:51.930] [remoteagent] [error] Failed to install extension: ms-toolsai.jupyter EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.affb66a9-ecfd-46c1-8b26-951f8a2dd4d7' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'
[2021-08-24 09:33:51.977] [remoteagent] [info] Extracted extension to /users/a/.vscode-server/extensions/.f12caf38-183c-4fa2-9d93-9d6f203d8a57: ms-toolsai.jupyter
[2021-08-24 09:33:52.442] [remoteagent] [info] Rename failed because of EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.f12caf38-183c-4fa2-9d93-9d6f203d8a57' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'. Deleted from extracted location /users/a/.vscode-server/extensions/.f12caf38-183c-4fa2-9d93-9d6f203d8a57
[2021-08-24 09:33:52.442] [remoteagent] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-08-24 09:33:52.442] [remoteagent] [error] EEXIST: EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.f12caf38-183c-4fa2-9d93-9d6f203d8a57' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'
    at y.rename (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:81014)
    at async y.extractUserExtension (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:77848)
    at async Q.extract (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:90124)
[2021-08-24 09:33:52.442] [remoteagent] [error] Failed to install extension: ms-toolsai.jupyter EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.f12caf38-183c-4fa2-9d93-9d6f203d8a57' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'
[2021-08-24 09:33:53.469] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-24 09:33:53.553] [remoteagent] [info] Extracted extension to /users/a/.vscode-server/extensions/.2e245d30-a61c-414b-afe1-3dc176becb31: ms-toolsai.jupyter
[2021-08-24 09:33:54.090] [remoteagent] [info] Rename failed because of EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.2e245d30-a61c-414b-afe1-3dc176becb31' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'. Deleted from extracted location /users/a/.vscode-server/extensions/.2e245d30-a61c-414b-afe1-3dc176becb31
[2021-08-24 09:33:54.090] [remoteagent] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-08-24 09:33:54.091] [remoteagent] [error] EEXIST: EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.2e245d30-a61c-414b-afe1-3dc176becb31' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'
    at y.rename (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:81014)
    at async y.extractUserExtension (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:77848)
    at async Q.extract (/had/home/a/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostAgent.js:116:90124)
[2021-08-24 09:33:54.091] [remoteagent] [error] Failed to install extension: ms-toolsai.jupyter EEXIST: file already exists, rename '/users/a/.vscode-server/extensions/.2e245d30-a61c-414b-afe1-3dc176becb31' -> '/users/a/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'

VS Code version: Code 1.59.1 (Universal) (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.49.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (4.28GB free)|
|Process Argv|--crash-reporter-id 374fef7b-70d5-4a1f-bc8a-01773fb43c52|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxx.xxx.com (removed for privacy)|
|OS|Linux x64 3.10.0-1062.49.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (72 x 2700)|
|Memory (System)|754.33GB (19.14GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
hive-sql|jos|0.0.4
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-sql-formatter|adp|1.4.4
hive-sql|jos|0.0.4
vscode-sshfs|Kel|1.21.2
jupyter|ms-|2021.8.1236758218
autodocstring|njp|0.5.4
vscode-yaml|red|0.22.0
indenticator|Sir|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173
bridge0723:30353136
vsdyn478:30356813

```

</details>

**Comment by lauracosgrove** [comment]
Hi, apologies, I'm unable to do that as I'm on a restricted machine.

**Comment by sandy081** [comment]
I am mostly sure that I have fixed this issue in insiders. So please wait for next stable release and if it still reproduces reopen the issue.
