### ISSUE TITLE
Error: a text search provider for the scheme 'file' is already registered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#131632]
This is just noise in the web integration tests, but I thought I would report it anyway. 

Steps:
* run `resources/server/test/test-web-integration.sh`

```
a text search provider for the scheme 'file' is already registered: Error: a text search provider for the scheme 'file' is already registered
	at NativeExtHostSearch.registerTextSearchProvider (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostSearch.js:37:23)
	at NativeExtHostSearch._registerEHSearchProviders (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostSearch.js:35:18)
	at NativeExtHostSearch.$enableExtensionHostSearch (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostSearch.js:31:18)
	at RPCProtocol._doInvokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:399:27)
	at RPCProtocol._invokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:384:45)
	at RPCProtocol._receiveRequest (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:311:32)
	at RPCProtocol._receiveOneMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:234:26)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:115:52
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:435:38)
	at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:380:35)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:152:41
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:435:38)
	at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:380:35)
	at PersistentProtocol._receiveMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:659:41)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:515:83
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:435:38)
	at ProtocolReader.acceptChunk (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:194:37)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:163:61
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:435:38)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:410:42
	at afterWrite (internal/streams/writable.js:466:5)
	at onwrite (internal/streams/writable.js:446:7)
	at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
	at Zlib.processCallback (zlib.js:586:8)
```

**Comment by roblourens** [comment]
Thanks, this error shows in every remote window (only in Insiders where the forceExtensionHostSearch setting is enabled)
