### ISSUE TITLE
Smoke tests are failing due to quick pick

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#131617]
```
1) VSCode Smoke Tests (Electron)
       Quick Access
         quick access search produces correct result:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:178:19)
      at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:258:16)
      at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
      at async Context.<anonymous> (out\areas\search\search.test.js:78:13)

  2) VSCode Smoke Tests (Electron)
       Language Features
         verifies quick outline:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:178:19)
      at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:258:16)
      at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
      at async QuickAccess.openFile (D:\a\1\s\test\automation\out\quickaccess.js:42:9)
      at async Context.<anonymous> (out\areas\languages\languages.test.js:16:13)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=132359&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=316b23c8-21ca-5aab-3515-3225235af7bb

Failing tests are always not same but those tests which are failing are always due to quick pick widget

**Comment by bpasero** [comment]
If this is from changes in `gettingStarted.ts` I wonder if our CLI argument to disable any welcome content in tests is not working anymore. I.e. I would not expect any welcome/getting-started etc. to interfer with smoke or integration tests.
