### ISSUE TITLE
Corporate Proxy Errors (Self Signed Certificate in Chain) (Everything used to work before)

### ISSUE THREAD

**Issue by jkruer01** [Microsoft/vscode#13171]
- VSCode Version: 1.5.0
- OS Version: Windows 7

Steps to Reproduce:
1. Open Visual Studio Code

An error pops up saying 

> "Error: self signed certificate in certificate chain"

When I open developer tools, the following info is displayed:

```
keybindingResolver.ts:189 Conflict detected, command `cursorUpSelect` cannot be triggered by ctrl+shift+up due to fsharp.MoveFileUp
keybindingResolver.ts:189 Conflict detected, command `cursorDownSelect` cannot be triggered by ctrl+shift+down due to fsharp.MoveFileDown
threadService.ts:217 [Extension Host] vscode-icons is active!
threadService.ts:217 [Extension Host] Spell and Grammar checker active...
threadService.ts:217 [Extension Host] Default Settings
threadService.ts:217 [Extension Host] Code Actons Registering for: markdown
threadService.ts:217 [Extension Host] Code Actons Registering for: plaintext
messageService.ts:119 self signed certificate in certificate chain: Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket._finishInit (_tls_wrap.js:593:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:425:38)e.doShow @ messageService.ts:119e.show @ messageService.ts:103e.onError @ extensionsWorkbenchService.ts:474(anonymous function) @ extensionsWorkbenchService.ts:299n.Class.define.done @ winjs.base.raw.js:1378m @ winjs.base.raw.js:1224B.enter @ winjs.base.raw.js:901n.Class.define._run @ winjs.base.raw.js:1068n.Class.define._chainedError @ winjs.base.raw.js:1031n @ winjs.base.raw.js:736m @ winjs.base.raw.js:1209B.enter @ winjs.base.raw.js:901n.Class.define._run @ winjs.base.raw.js:1068n.Class.define._error @ winjs.base.raw.js:1041(anonymous function) @ async.ts:135n.Class.define.done @ winjs.base.raw.js:1378m @ winjs.base.raw.js:1224B.enter @ winjs.base.raw.js:901n.Class.define._run @ winjs.base.raw.js:1068n.Class.define._chainedError @ winjs.base.raw.js:1031n @ winjs.base.raw.js:736n.Class.define.then @ winjs.base.raw.js:1436R.enter @ winjs.base.raw.js:747n.Class.define._run @ winjs.base.raw.js:1068n.Class.define._setCompleteValue @ winjs.base.raw.js:1052m @ winjs.base.raw.js:1209B.enter @ winjs.base.raw.js:901n.Class.define._run @ winjs.base.raw.js:1068n.Class.define._chainedError @ winjs.base.raw.js:1031n @ winjs.base.raw.js:736m @ winjs.base.raw.js:1209B.enter @ winjs.base.raw.js:901n.Class.define._run @ winjs.base.raw.js:1068n.Class.define._error @ winjs.base.raw.js:1041emitOne @ events.js:90emit @ events.js:182socketErrorListener @ _http_client.js:295emitOne @ events.js:90emit @ events.js:182emitErrorNT @ net.js:1253_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
threadService.ts:217 [Extension Host] [IONIDE-FSAC-SIG] started message? true
threadService.ts:217 [Extension Host] [I] 2016-10-03T20:52:09.4901172Z: listener started in 22.000 ms with binding 127.0.0.1:8184 [Suave.Tcp.tcpIpServer]
```

I have the following settings in my user settings:

```
// Place your settings in this file to overwrite the default settings
{
    // Controls auto save of dirty files. Accepted values:  "off", "afterDelay", "onFocusChange". If set to "afterDelay" you can configure the delay in "files.autoSaveDelay".
    "files.autoSave": "onFocusChange",

    //-------- HTTP configuration --------

    // // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
    "http.proxy": "http://usproxy.es.***.com:8080",
    "https.proxy": "http://usproxy.es.***.com:8080",

    // // Whether the proxy server certificate should be verified against the list of supplied CAs.
    "http.proxyStrictSSL": false,

    "eslint.enable": true,
    "eslint.options": {
                    "rules": {
                        "eqeqeq": [2, "allow-null"]
                    }
                },

    "editor.wrappingColumn": 0
}
```

I am able to make bower work on my same computer with the same corporate firewall using these settings in .bowerrc

```
{
  "directory": "bower_components",
  "proxy":"http://usproxy.es.***.com:8080",
  "https-proxy":"http://usproxy.es.***.com:8080",
  "strict-ssl": false
}
```

I am also able to make npm work on my same computer with the same corporate firewall using these settings in .npmrc

```
proxy=http://usproxy.es.***.com:8080/
https-proxy=http://usproxy.es.***.com:8080/
strict-ssl=false
```

Also, when I try to go to the extension gallery I get the following error:

> "Error: Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.

The developer tools shows the following information:

```
6messageService.ts:119 Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.: Error: Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.
    at Object._ [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:34:29245)
    at t.onError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.js:4:16408)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.js:4:13184
    at n.Class.define.done (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:18833)
    at Object.m [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:13621)
    at Object.B.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:16953)
    at n.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:18274)
    at n.Class.define._chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:17633)
    at n (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:15456)
    at Object.m [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:13448)
```

I know for a fact that this used to work and I was able to successfully install extensions from behind my corporate firewall/proxy.  However, after some update to VS Code (not sure which one) this stopped working.  

Any help would be appreciated.

Thanks!

**Comment by joaomoreno** [comment]
Can you try with [the latest Insiders release](http://code.visualstudio.com/Insiders)?

Nothing really changed in this area recently, so confirm that your proxy is really up and running.

**Comment by garoyeri** [comment]
I tried this with the Insiders release:
- Version 1.7.0-insider
- Commit 9e7d70052908b633e0d4f71e70b26714bd1d2f10
- Date 2016-11-02T05:39:07.207Z
- Shell 1.3.8
- Renderer 52.0.2743.82
- Node 6.5.0

I was trying to get the C# extension running and it said it was downloading OmniSharp and the C# Debugger.  

[self-signed-certificate.txt](https://github.com/Microsoft/vscode/files/567812/self-signed-certificate.txt)

**Comment by joaomoreno** [comment]
Oh I see. Setting `http.proxyStrictSsl = false` is the right thing to do. If an extension reaches out to the Internet but fails to do so due to a proxy... you'll have to file an issue with that extension.
