### ISSUE TITLE
vscode was trying to write to indexeddb and failed for some reason which was causing it to spin 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#132102]
@srivatsn says:

is github.dev working for anyone? I'm seeing it stuck in loading and get random 404s and 504s from vscode cdn urls..

I cleared my browser local state and then it worked.. This was the error I was seeing in console before cleaning:

```
workbench.web.api.js:628 Uncaught (in promise) Error: Unable to write file 'vscode-log:/20210809T101508/userDataSync.log' (InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.)
    at ci.writeFile (workbench.web.api.js:638)
    at async Object.factory (workbench.web.api.js:632)
k @ workbench.web.api.js:628
writeFile @ workbench.web.api.js:638
Promise.then (async)
consume @ workbench.web.api.js:68
(anonymous) @ workbench.web.api.js:68
queue @ workbench.web.api.js:68
_log @ workbench.web.api.js:631
error @ workbench.web.api.js:631
_log @ workbench.web.api.js:631
error @ workbench.web.api.js:631
error @ workbench.web.api.js:748
getLastSyncUserData @ workbench.web.api.js:748
async function (async)
getLastSyncUserData @ workbench.web.api.js:748
doTriggerLocalChange @ workbench.web.api.js:748
(anonymous) @ workbench.web.api.js:748
doRun @ workbench.web.api.js:68
onTimeout @ workbench.web.api.js:68
setTimeout (async)
schedule @ workbench.web.api.js:68
triggerLocalChange @ workbench.web.api.js:748
onFileChanges @ workbench.web.api.js:748
(anonymous) @ workbench.web.api.js:748
fire @ workbench.web.api.js:60
onDidChangeFile @ workbench.web.api.js:638
(anonymous) @ workbench.web.api.js:638
fire @ workbench.web.api.js:60
onDidStorageChange @ workbench.web.api.js:628
S @ workbench.web.api.js:628
workbench.web.api.js:631   ERR Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.: Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at o (https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:628:17879)
    at new Promise (<anonymous>)
    at a.readFile (https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:628:17837)
    at https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:638:46305
    at ci.readFileUnbuffered (https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:638:46529)
    at ci.doReadFileStream (https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:638:45012)
    at ci.doReadFile (https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:638:44454)
    at Object.factory (https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:638:44369)
    at d.consume (https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:68:16061)
    at https://vscodeweb.azureedge.net/insider/1ee61f368ee0570feeb220605578a8768d99e762/out/vs/workbench/workbench.web.api.js:68:15876
```

**Comment by sandy081** [comment]
Seems like indexedDB FSP is reading / writing into the DB that is getting closed - We shall check it during these transactions. But not sure if it is causing the spin.

**Comment by sandy081** [comment]
There has been no further reports about this. Hence closing it.
