### ISSUE TITLE
Interactive window doesn't open in the latest insiders

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#132274]
`interactive.open` command in VS Code seems to be throwing errors.
```
rror Jupyter Extension: 2021-09-03 08:28:18: DataScience Error Error: Running the contributed command: 'interactive.open' failed.
    at P._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111117)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InteractiveWindow.createReadyPromise (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/interactive-window/interactiveWindow.ts:176:38)
    at InteractiveWindowProvider.getOrCreate (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/interactive-window/interactiveWindowProvider.ts:93:9)
    at CodeWatcher.addCode (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/editor-integration/codewatcher.ts:992:45)
    at CodeWatcher.runMatchingCell (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/editor-integration/codewatcher.ts:1052:17)
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-fork.js:5
Error Jupyter Extension: 2021-09-03 08:28:49: DataScience Error Error: Running the contributed command: 'interactive.open' failed.
    at P._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111117)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InteractiveWindow.createReadyPromise (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/interactive-window/interactiveWindow.ts:176:38)
    at InteractiveWindowProvider.getOrCreate (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/interactive-window/interactiveWindowProvider.ts:93:9)
    at CodeWatcher.addCode (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/editor-integration/codewatcher.ts:992:45)
    at CodeWatcher.runMatchingCell (/Users/donjayamanne/Desktop/Development/vsc/vscode-jupyter/src/client/datascience/editor-integration/codewatcher.ts:1052:17) {
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-fork.js:5
```

**Comment by psobolewskiPhD** [comment]
Same issue here.
Jupyter notebooks work fine, but Interactive Window won't open from command palette nor by running #%% cells.
Tried to roll back Jupyter and Python extensions one by one or together, but no effect.

Quite annoying and a real lesson not to upgrade mid stream! Derp!

```
Version: 1.61.0-insider
Commit: aec6ee09fa1021cb59c7f4f4d000b027febc967d
Date: 2021-09-03T05:23:57.182Z
Electron: 13.2.3
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0
```

**Comment by psobolewskiPhD** [comment]
This has been fixed for me with this mornings update:
```
Version: 1.61.0-insider
Commit: 87260247dc7b912db6e6a21a366e6f50dca759ba
Date: 2021-09-03T21:02:57.202Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0
```
