### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by 522422474** [microsoft/vscode#132247]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.4.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure.
    at c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19293:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19293:21)
    at Object.createDetachedDiagnostic (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19309:20)
    at parseErrorAtPosition (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30704:42)
    at parseErrorAt (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30711:13)
    at parseErrorAtCurrentToken (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30698:13)
    at parseErrorForInvalidName (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30936:17)
    at parseErrorForMissingSemicolonAfter (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30905:21)
    at parseExpressionOrLabeledStatement (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34798:21)
    at parseStatement (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35035:20)
    at parseListElement (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31487:20)
    at parseList (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31472:31)
    at parseSourceFileWorker (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30440:30)
    at Object.parseSourceFile (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30274:26)
    at Object.createSourceFile (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30072:29)
    at Object.createLanguageServiceSourceFile (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156318:29)
    at acquireOrUpdateDocument (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129076:37)
    at Object.acquireDocumentWithKey (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129042:20)
    at getOrCreateSourceFileByPath (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156721:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156668:24)
    at findSourceFileWorker (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:113090:29)
    at findSourceFile (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:113000:26)
    at c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:112952:85
    at getSourceFileFromReferenceWorker (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:112919:34)
    at processSourceFile (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:112952:13)
    at processRootFile (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:112759:13)
    at c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111624:67
    at Object.forEach (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:194:30)
    at Object.createProgram (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111624:16)
    at synchronizeHostData (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156598:26)
    at Proxy.getProgram (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156730:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161726:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161655:42)
    at ConfiguredProject.updateGraph (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162637:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164361:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165444:44)
    at c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165784:97
    at Object.flatMap (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165784:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166942:46)
    at c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168873:88
    at IOSession.Session.executeWithRequestId (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168864:28)
    at IOSession.Session.executeCommand (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168873:33)
    at IOSession.Session.onMessage (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168899:35)
    at Interface.<anonymous> (c:\Users\fdh_1\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171504:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.61.0-insider (aec6ee09fa1021cb59c7f4f4d000b027febc967d, 2021-09-03T05:14:10.486Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (4.51GB free)|
|Process Argv|--crash-reporter-id d41918fc-6f20-4442-9cfb-7c8357d7b4ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
TypeScriptImport|kev|1.17.0
vscode-language-pack-zh-hans|MS-|1.60.2
gulptasks|nic|1.3.1
vscode-gulp|tan|0.0.4
vscode-icons|vsc|11.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vshan820:30294714
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
vsccppwtct:30312693
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
javagetstartedt:30350119
pydsgst2:30361790

```

</details>

**Comment by hy08** [comment]
I have the same problem
