### ISSUE TITLE
Cannot read property 'getStatus' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1323]
Just saw this in my dev logs:

[1674:1215/113350:INFO:CONSOLE(332)] "Cannot read property 'getStatus' of null: TypeError: Cannot read property 'getStatus' of null
    at DirtyDiffModelDecorator.getOriginalContents (file:////Users/bpasero/Development/monaco/out/vs/workbench/parts/git/browser/gitWorkbenchContributions.js:131:35)
    at DirtyDiffModelDecorator.diffOriginalContents (file:////Users/bpasero/Development/monaco/out/vs/workbench/parts/git/browser/gitWorkbenchContributions.js:114:25)
    at file:////Users/bpasero/Development/monaco/out/vs/workbench/parts/git/browser/gitWorkbenchContributions.js:109:53
    at Throttler.queue (file:////Users/bpasero/Development/monaco/out/vs/base/common/async.js:87:34)
    at ThrottledDelayer.task (file:////Users/bpasero/Development/monaco/out/vs/base/common/async.js:192:93)
    at file:////Users/bpasero/Development/monaco/out/vs/base/common/async.js:147:40
    at Object.notifySuccess [as _notify] (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_success_notify.enter (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1127:30)
    at Promise_ctor.WinJS.Class.define._run (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1343:29)
    at Promise_ctor.WinJS.Class.define._completed (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1311:18)", source:

**Comment by joaomoreno** [comment]
This is OK. It was during a shutdown.
