### ISSUE TITLE
Error: submitURL must be specified when uploadToServer is true

### ISSUE THREAD

**Issue by oskude** [microsoft/vscode#132433]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: Arch Linux kernel 5.13.13

Steps to Reproduce:

1. `git clone https://github.com/microsoft/vscode.git`
2. `cd vscode`
3. `HOME=$PWD/.home yarn`
4. `HOME=$PWD/.home ./scripts/code.sh`

more info:

with latest commit as time of writing, i get following error:

```
$ HOME=$PWD/.home ./scripts/code.sh 
yarn run v1.22.11
$ node build/lib/electron
Done in 0.17s.
[09:55:18] Syncronizing built-in extensions...
[09:55:18] You can manage built-in extensions with the --builtin flag
[09:55:18] [marketplace] ms-vscode.references-view@0.0.81 ✔︎
[09:55:18] [marketplace] ms-vscode.js-debug-companion@1.0.15 ✔︎
[09:55:18] [marketplace] ms-vscode.js-debug@1.60.1 ✔︎
[09:55:18] [marketplace] ms-vscode.vscode-js-profile-table@0.0.18 ✔︎
App threw an error during load
Error: submitURL must be specified when uploadToServer is true
    at CrashReporter.start (electron/js2c/browser_init.js:41:472)
    at configureCrashReporter (/data/upstream/vscode/out/main.js:413:16)
    at Object.<anonymous> (/data/upstream/vscode/out/main.js:48:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at loadApplicationPackage (/data/upstream/vscode/.build/electron/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/data/upstream/vscode/.build/electron/resources/default_app.asar/main.js:222:9)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
    at Module._load (internal/modules/cjs/loader.js:747:15)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
A JavaScript error occurred in the main process
Uncaught Exception:
Error: submitURL must be specified when uploadToServer is true
    at CrashReporter.start (electron/js2c/browser_init.js:41:472)
    at configureCrashReporter (/data/upstream/vscode/out/main.js:413:16)
    at Object.<anonymous> (/data/upstream/vscode/out/main.js:48:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at loadApplicationPackage (/data/upstream/vscode/.build/electron/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/data/upstream/vscode/.build/electron/resources/default_app.asar/main.js:222:9)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
    at Module._load (internal/modules/cjs/loader.js:747:15)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[826:0906/095518.497263:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

i then found https://github.com/microsoft/vscode/issues/127585 and tried following:

```
$ HOME=$PWD/.home ./scripts/code-cli.sh --verbose --log debug --disable-crash-reporter --disable-extensions
# same error...
```

> nitpick: `ctrl+c`'ing the above command does not kill code-oss process(es)...

then changed `.home/.vscode-oss-dev/argv.json` to this:

```
{
	"disable-color-correct-rendering": true,
	"enable-crash-reporter": false
}
```

and run:

```
$ HOME=$PWD/.home ./scripts/code.sh
# same error...
```

seems like nothing is disabling the crash reporter?

what can i try now?

ps. `HOME=$PWD/.home` is cause my home is only 512 MB, and vscode wants 1.8GB there...

**Comment by oskude** [comment]
aha! comparing `out/main.js` and `src/main.js` i see that they are not the same files! (seems i had old builds in out dir...)

dammit, was my fault not reading the docs past `yarn`... we need `yarn watch` (or for single run `yarn compile`, takes less ram!) to update the out files...

obviously works, sorry for the noise >.<*
