### ISSUE TITLE
Can't create a language status item that is file path specific

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#132570]
Trying to do so results in:

```
  ERR LanguageStatusItem with id '[object Object]' ALREADY exists: Error: LanguageStatusItem with id '[object Object]' ALREADY exists
    at D.createLanguageStatusItem (c:\Users\dirkb.EUROPE\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:208205)
    at Object.createLanguageStatusItem (c:\Users\dirkb.EUROPE\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:27540)
    at _RichNavService.registerProviders (c:\Users\dirkb.EUROPE\Projects\mseng\VSCode\vscode-remotehub\dist\webpack:\remotehub\src\codeNavigation\richNavService.ts:1827:16)
    at openHandler (c:\Users\dirkb.EUROPE\Projects\mseng\VSCode\vscode-remotehub\dist\webpack:\remotehub\src\codeNavigation\richNavService.ts:1630:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
log.ts:301   ERR Cannot read property 'exclusive' of undefined: TypeError: Cannot read property 'exclusive' of undefined
    at w (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:585:3765)
    at f._updateScores (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:585:5093)
    at f._orderedForEach (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:585:4678)
    at f.ordered (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:585:4454)
    at D.getLanguageStatus (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1515:14384)
    at Mi._createViewModel (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1689:22614)
    at Mi._update (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1689:22758)
    at l.fire (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1732)
    at L.doHandleActiveEditorChangeEvent (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2422:19547)
    at L.handleActiveEditorChange (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2422:19340)
    at vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2422:19698
    at l.fire (vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at vscode-file://vscode-app/c:/Users/dirkb.EUROPE/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2587:17019
```

The selector I use looks like this:

```
		const filter: vscode.DocumentFilter = {
			scheme: this.repository.uri.scheme,
			pattern: document.uri.fsPath,
			language: document.languageId,
			exclusive: true,
		};
		const selector: vscode.DocumentSelector = [filter];

```

**Comment by dbaeumer** [comment]
Even creating two for the language ID TypeScript fails with 

```
ERR Cannot read property 'exclusive' of undefined: TypeError: Cannot read property 'exclusive' of undefined
```

**Comment by jrieken** [comment]
hmm.. this doesn't reproduce for me. do you have a full code snippet

**Comment by dbaeumer** [comment]
Tried it again and here is the code I use to make it fail:

```ts
			const lsi = vscode.languages.createLanguageStatusItem([
				{
					scheme: 'vscode-vfs',
					language: 'typescript'
				}
			]);
			lsi.severity = vscode.LanguageStatusSeverity.Error;
			lsi.text = 'Rich Navigation';
			disposables.push(lsi);
```

Using Insider 

Version: 1.61.0-insider (user setup)
Commit: 34861b8c8aa76b517f203743ad5b5d72ef5fcd81
Date: 2021-09-08T05:17:18.073Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by dbaeumer** [comment]
OK. My fault. The proposed API changed :-(
