### ISSUE TITLE
Latest Insiders update broke RemoteSSH again

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#132553]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.61.0-insider (bb9491d9f2c65510226dcc920a6efbf6501d5943, 2021-09-07T05:17:08.586Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30361752
pydsgst2:30361790

```

</details>

Log message:

```
[15:07:41.834] Log Level: 2
[15:07:41.844] remote-ssh-nightly@2021.8.42660
[15:07:41.845] win32 x64
[15:07:41.890] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2242616c6c7a227d", attempt 1
[15:07:41.890] "remote.SSH.useLocalServer": false
[15:07:41.891] "remote.SSH.showLoginTerminal": false
[15:07:41.891] "remote.SSH.remotePlatform": {xxxx}
[15:07:41.891] "remote.SSH.path": undefined
[15:07:41.892] "remote.SSH.configFile": undefined
[15:07:41.892] "remote.SSH.useFlock": true
[15:07:41.892] "remote.SSH.lockfilesInTmp": false
[15:07:41.892] "remote.SSH.localServerDownload": off
[15:07:41.893] "remote.SSH.remoteServerListenOnSocket": false
[15:07:41.893] "remote.SSH.showLoginTerminal": false
[15:07:41.893] "remote.SSH.defaultExtensions": ["kevinkyang.auto-comment-blocks","ms-vscode.cpptools","xaver.clang-format","cschlosser.doxdocgen","usernamehw.errorlens","mfery.gitexplorer","fabiospampinato.vscode-git-history","donjayamanne.githistory","shyykoserhiy.git-autoconfig","codezombiech.gitignore","eamodio.gitlens","ziyasal.vscode-open-in-github","jeff-hykin.polacode-2019","alefragnani.project-manager","ms-python.python","lextudio.restructuredtext","stkb.rewrap","Gruntfuggly.todo-tree","georgewfraser.vscode-tree-sitter","eetami.whitespace-formatter","redhat.vscode-yaml","streetsidesoftware.code-spell-checker","acarreiro.calculate","GrapeCity.gc-excelviewer","mhutchie.git-graph","nhoizey.gremlins","ctf0.macros","yzhang.markdown-all-in-one","DavidAnson.vscode-markdownlint","mechatroner.rainbow-csv","Tino.simple-rest-client","hangxingliu.vscode-systemd-support","TabNine.tabnine-vscode","jbenden.c-cpp-flylint","Atishay-Jain.All-Autocomplete","CoenraadS.bracket-pair-colorizer-2"]
[15:07:41.894] "remote.SSH.loglevel": 2
[15:07:41.894] SSH Resolver called for host: Ballz
[15:07:41.894] Setting up SSH remote "Ballz"
[15:07:41.901] Using commit id "bb9491d9f2c65510226dcc920a6efbf6501d5943" and quality "insider" for server
[15:07:41.909] Install and start server if needed
[15:07:41.920] Checking ssh with "ssh -V"
[15:07:42.023] > OpenSSH
[15:07:42.023] > _for_Windows_8.1p1, LibreSSL 3.0.2

[15:07:42.036] Running script with connection command: ssh -T -D 63325 "Ballz" bash
[15:07:42.040] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:07:59.043] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\aburakov\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.8.42660\out\extension.js:1:397167)
	at Timeout._onTimeout (c:\Users\aburakov\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.8.42660\out\extension.js:1:488075)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[15:07:59.048] ------
```

**Comment by alexmbits** [comment]
I have the same problem as you, my logs:

```[16:55:08.137] Log Level: 2
[16:55:08.139] remote-ssh@0.65.7
[16:55:08.139] win32 x64
[16:55:08.157] SSH Resolver called for "ssh-remote+vmware-debian10", attempt 1
[16:55:08.157] "remote.SSH.useLocalServer": false
[16:55:08.157] "remote.SSH.showLoginTerminal": false
[16:55:08.158] "remote.SSH.remotePlatform": {"vmware-debian10":"linux","asyncal-debian10":"linux"}
[16:55:08.158] "remote.SSH.path": undefined
[16:55:08.158] "remote.SSH.configFile": undefined
[16:55:08.158] "remote.SSH.useFlock": true
[16:55:08.158] "remote.SSH.lockfilesInTmp": false
[16:55:08.158] "remote.SSH.localServerDownload": auto
[16:55:08.158] "remote.SSH.remoteServerListenOnSocket": false
[16:55:08.159] "remote.SSH.showLoginTerminal": false
[16:55:08.159] "remote.SSH.defaultExtensions": []
[16:55:08.159] "remote.SSH.loglevel": 2
[16:55:08.159] SSH Resolver called for host: vmware-debian10
[16:55:08.159] Setting up SSH remote "vmware-debian10"
[16:55:08.181] Using commit id "bb9491d9f2c65510226dcc920a6efbf6501d5943" and quality "insider" for server
[16:55:08.184] Install and start server if needed
[16:55:08.188] Checking ssh with "ssh -V"
[16:55:08.229] > OpenSSH_for_Windo
[16:55:08.229] > ws_8.1p1, LibreSSL 3.0.2

[16:55:08.236] Running script with connection command: ssh -T -D 51910 "vmware-debian10" bash
[16:55:08.238] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:56:15.244] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\aleksa\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\aleksa\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[16:56:15.251] ------```

**Comment by mc-christian** [comment]
I'm having the same problem

**Comment by htjain** [comment]
Same here

**Comment by BMWestrich** [comment]
Having the same issue (Windows -> Linux Remote SSH).

Plain ssh on PS is working.

**Comment by bbangert** [comment]
Yep, Windows -> Linux SSH is broken. It's times like these I really wish Insiders had a rollback function...

**Comment by duanehutchins** [comment]
Same here. The SSH extension isn't recognizing the response for some reason, and it thinks the connection timed out. Same command in command prompt works as expected.

**Comment by NoevilMe** [comment]
same problem

**Comment by arita2b** [comment]
same problem , is there any existing solution?

**Comment by rafipiccolo** [comment]
I now use vscode. Not insider. And it works.

**Comment by arita2b** [comment]
> I now use vscode. Not insider. And it works.

Is that the blue one or the purple one?
I installed the purple one, but I can't find the extension in it.

**Comment by anatolyburakov** [comment]
> I now use vscode. Not insider. And it works.

dealing with bugs is kind of the point of Insiders version. If you don't want to deal with occasional breaking bugs like this one, don't use the Insiders version - let me and others test it for you beforehand :)

For now, i've also switched to release channel, but i plan to switch back to Insiders once this issue is fixed.

> Is that the blue one or the purple one?

please don't confuse Visual Studio with Visual Studio Code. they are entirely different beasts. VSCode is the blue one, not the purple one :)

**Comment by ThiefMaster** [comment]
> dealing with bugs is kind of the point of Insiders version

Sure, that's the point. I don't mind that and I like having bleeding-edge features. But there should be a way to say "hey, this is a bug that's breaking everything, let me go back to the previous build and stick with it for a while". One that doesn't involve finding the old insiders installer or copying the installation from another computer.

**Comment by anatolyburakov** [comment]
> But there should be a way to say "hey, this is a bug that's breaking everything, let me go back to the previous build and stick with it for a while". One that doesn't involve finding the old insiders installer or copying the installation from another computer.

I agree, but it seems that VSCode dev team thinks this is not worth the time investment. there probably is a way to get the old version because we get them from *somewhere*. However, unless you specifically depend on bleeding edge functionality, falling back to stable is an acceptable compromise IMO.

**Comment by ThiefMaster** [comment]
I disagree, you need to manually copy the settings etc since insiders and stable don't share config (or does config sync work there?)

Anyway, they don't really need to have builtin functionality. Just having a list somewhere with download links for the last n days of insiders builds would be enough...

**Comment by anatolyburakov** [comment]
> you need to manually copy the settings etc since insiders and stable don't share config (or does config sync work there?)

right, but you can automate that by just writing a quick power shell script, so that "manually copying" settings isn't actually manual. so, while it's not ideal, it's not really all that bad either!

> Anyway, they don't really need to have builtin functionality. Just having a list somewhere with download links for the last n days of insiders builds would be enough...

i wish that were the case, but i don't see that happening. this is a sentiment VSCode team has expressed time and time again.

**Comment by Officeyutong** [comment]
Same problem. Hoping for a workaround.

**Comment by duanehutchins** [comment]
I figured out how to roll back VSCode Insider!

Get your VSCode Insider download link (from https://code.visualstudio.com/insiders/), and change the hash in the link to the hash from the last working commit (nightly build). The last working commit was `997228d528d687fd17cbf3ba117a0d4f668c1393`

So the download links for Windows (64 bit) are:

* User Installer: https://az764295.vo.msecnd.net/insider/997228d528d687fd17cbf3ba117a0d4f668c1393/VSCodeUserSetup-x64-1.61.0-insider.exe
* System Installer: https://az764295.vo.msecnd.net/insider/997228d528d687fd17cbf3ba117a0d4f668c1393/VSCodeSetup-x64-1.61.0-insider.exe
* .zip: https://az764295.vo.msecnd.net/insider/997228d528d687fd17cbf3ba117a0d4f668c1393/VSCode-win32-x64-1.61.0-insider.zip

I tested and confirmed rolling back to `997228d528d687fd17cbf3ba117a0d4f668c1393` fixes the SSH issue.

**Comment by anatolyburakov** [comment]
@duanehutchins yep, that worked for me, however there's on important caveat: sometimes you have to update the version string as well (e.g. `1.60.0-insider` in place of `1.61.0-insider`).
Is there a list of commit ID's for nightlies? Surely they don't build _every_ commit?..

**Comment by duanehutchins** [comment]
@anatolyburakov  Look at the commit history in git, and it shows when each day changed. The last commit of the day seems to always work when I tested it.

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/132519 and a fix is on the way. Probably would have been on top of it quicker if it wasn't for the 3 day weekend and vacations. Yes, Insiders will sometimes be unstable but we try really hard to keep it at least functional. Thanks to everyone who uses Insiders and helps us find these issues!

**Comment by htjain** [comment]
Working with latest insider release.

```
Version: 1.61.0-insider (user setup)
Commit: 23cffa27b806f9e1733e15d611ec251dcdba2c42
Date: 2021-09-10T17:05:11.199Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by anatolyburakov** [comment]
Confirmed as working on my end.

**Comment by htjain** [comment]
It stopped working again :( 

```
Version: 1.61.0-insider (user setup)
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
Date: 2021-09-20T07:28:25.574Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by anatolyburakov** [comment]
Can confirm. Last working version: a0af58197e4a1d3e82fbe3048e0549e622d19f4f

**Comment by duanehutchins** [comment]
Track in current ticket: #133436
