### ISSUE TITLE
Unexpected token in JSON at position 262140 when activating extension

### ISSUE THREAD

**Issue by almohress** [microsoft/vscode#132777]
## Environment data

-   VS Code version: 1.59.1
-   Extension version (available under the Extensions sidebar): v2021.8.1159798656
-   OS and version: Linux x64 5.13.11-1-MANJARO
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenvwrapper
-   Relevant/affected Python-related VS Code extensions and their versions: pylance v2021.8.3, jupyter v2021.8.1236758218, Visual Studio IntelliCode v1.2.14
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Extension loads successfuly

## Actual behaviour

Extension does not load, console reports "Unexpected token ' in JSON at position 262140"
## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Load the extension by clicking a .py file

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
[2021-08-30 17:03:56.733] [exthost] [info] extension host started
[2021-08-30 17:03:56.733] [exthost] [info] Skipping acquiring lock for /home/almohress/.config/Code/User/workspaceStorage/6db1ff554e3658be722c7f27b6e6654e.
[2021-08-30 17:03:57.009] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-08-30 17:03:57.009] [exthost] [info] ExtensionService#loadCommonJSModule file:///opt/visual-studio-code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-08-30 17:03:57.030] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"extensionId":{"value":"ms-python.vscode-pylance","_lower":"ms-python.vscode-pylance"},"activationEvent":"onLanguage:python"}
[2021-08-30 17:03:57.030] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/almohress/.vscode/extensions/ms-python.python-2021.8.1159798656/out/client/extension
[2021-08-30 17:03:57.194] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter {"startup":false,"extensionId":{"value":"ms-toolsai.jupyter","_lower":"ms-toolsai.jupyter"},"activationEvent":"onLanguage:python"}
[2021-08-30 17:03:57.194] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/almohress/.vscode/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension
[2021-08-30 17:03:57.465] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode {"startup":false,"extensionId":{"value":"VisualStudioExptTeam.vscodeintellicode","_lower":"visualstudioexptteam.vscodeintellicode"},"activationEvent":"onLanguage:python"}
[2021-08-30 17:03:57.465] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/almohress/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.14/dist/intellicode
[2021-08-30 17:03:57.503] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-08-30 17:03:57.503] [exthost] [info] ExtensionService#loadCommonJSModule file:///opt/visual-studio-code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-08-30 17:03:57.506] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-30 17:03:57.506] [exthost] [info] ExtensionService#loadCommonJSModule file:///opt/visual-studio-code/resources/app/extensions/git/dist/main
[2021-08-30 17:03:57.682] [exthost] [error] Activating extension ms-python.python failed due to an error:
[2021-08-30 17:03:57.682] [exthost] [error] SyntaxError: Unexpected token 	 in JSON at position 262140
    at JSON.parse (<anonymous>)
    at D._getValue (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:42922)
    at D.$getValue (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:42795)
    at r._doInvokeHandler (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:11989)
    at r._invokeHandler (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:11673)
    at r._receiveRequest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:10335)
    at r._receiveOneMessage (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:9122)
    at vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1549:7218
    at l.fire (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at n.fire (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16477)
    at u._receiveMessage (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21743)
    at vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18621
    at l.fire (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at b.acceptChunk (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13838)
    at vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13186
    at Socket.T (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:2897:159022)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

```

</p>
</details>

**Comment by alexdima** [comment]
@bpasero FYI - This looks like some JSON stored via the `IStorageService` became corrupt. The JSON is written a few lines lower, so it is unexpected that the value is corrupted. This might indicate some kind of bug in the storage layer.

@jrieken I don't remember writing that code, did you perhaps write that? Do you think it is so important such to fail extension activation when the JSON is corrupt, or should we catch that exception [maybe here](https://github.com/microsoft/vscode/blob/525a813883690495fffd46c5303c9fcb5c52747e/src/vs/workbench/api/browser/mainThreadStorage.ts#L53) and return `undefined`?

**Comment by bpasero** [comment]
I would suggest to be more resilient in extension activation as you suggest and fallback to an empty object here if any error rises from `$getValue` but log it as error:

https://github.com/microsoft/vscode/blob/3cca8288130cb5e0df113571b51c5b62142bb5b0/src/vs/workbench/api/common/extHostMemento.ts#L30-L33

This is the first time I hear about a problem with persisting data into SQLite. However, seeing `OS and version: Linux x64 5.13.11-1-MANJARO` makes me think that this is not an officially supported Linux distribution.

**Comment by bpasero** [comment]
@almohress curious if you could share the following 2 files with me (via e-mail is fine: find it on https://github.com/bpasero).

Steps:
* open the VSCode window where this issue happens
* View > Command Palette => Log Storage Database Contents
* Help > Toggle Dev Tools
* Find the 2 paths for the DBs
  * `Storage: Workspace (path: /Users/bpasero/Library/Application Support/code-oss-dev/User/workspaceStorage/a97bd3f7ce96ec26be36e076b940ef3e/state.vscdb)`
  * `Storage: Global (path: /Users/bpasero/Library/Application Support/code-oss-dev/User/globalStorage)`
* send both files to me

**Comment by andrea8moro** [comment]
I can still see the original issue in vscode-insiders v1.61.0-insider

**Comment by bpasero** [comment]
@andrea8moro whats the exact version you are on? And is it the issue that the extension fails to activate?

**Comment by andrea8moro** [comment]
Version: 1.61.0-insider (user setup)
Commit: da10782b86bd9d895ccb20be4514b19728036951
Date: 2021-09-16T08:31:28.161Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22454

python extension: v2021.9.1230869389

Error 2021-09-16 17:51:12: Error discovering pytest tests:
 [SyntaxError: Unexpected token S in JSON at position 53776
	at JSON.parse (<anonymous>)
	at a.runTestDiscovery (PATH\.vscode-insiders\extensions\ms-python.python-2021.9.1230869389\out\client\extension.js:59:841449)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
	at async _.refreshTestData (PATH\.vscode-insiders\extensions\ms-python.python-2021.9.1230869389\out\client\extension.js:59:852780)
	at async v.refreshTestDataInternal (PATH\.vscode-insiders\extensions\ms-python.python-2021.9.1230869389\out\client\extension.js:59:844322)] {
  stdout: '[{"rootid": ".", "root": "...

**Comment by bpasero** [comment]
I fixed the issue as reported in https://github.com/microsoft/vscode/issues/132777#issuecomment-912408628 that extensions fail to activate when the contents in storage fail to get parsed. What you report here seems different to me. Looks like the python extension is calling `JSON.parse` on something that is not valid JSON? Have you asked the Python extension what this could be?

**Comment by andrea8moro** [comment]
I see, I'll create a new issue. thanks
