### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by florin-talarian** [microsoft/vscode#132728]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.0-dev.20210907

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:55969:22)
    at getPropertyOfType (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:56619:24)
    at tryGetQualifiedNameAsValue (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:48496:26)
    at resolveEntityName (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:48553:133)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:48476:24)
    at getTargetOfImportEqualsDeclaration (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:47945:28)
    at getTargetOfAliasDeclaration (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:48295:28)
    at resolveAlias (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:48344:30)
    at resolveSymbol (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:48334:67)
    at mergeSymbol (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:46710:42)
    at /home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:46825:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:46823:20)
    at mergeSymbol (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:46734:21)
    at /home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:46825:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:46823:20)
    at initializeTypeChecker (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:83343:21)
    at Object.createTypeChecker (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:46487:9)
    at Object.getTypeChecker (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:112462:79)
    at synchronizeHostData (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:157071:21)
    at Object.getProgram (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:157192:13)
    at AutoImportProviderProject.Project.updateGraphWorker (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:162190:53)
    at AutoImportProviderProject.Project.updateGraph (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:162119:42)
    at AutoImportProviderProject.updateGraph (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:162964:70)
    at Object.updateProjectIfDirty (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:163601:45)
    at InferredProject.Project.getPackageJsonAutoImportProvider (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:162739:32)
    at InferredProject.Project.updateGraph (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:162157:26)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:164296:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:165985:26)
    at /home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:166259:97
    at Object.flatMap (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:166259:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:167417:46)
    at /home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:169348:88
    at IOSession.Session.executeWithRequestId (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:169339:28)
    at IOSession.Session.executeCommand (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:169348:33)
    at IOSession.Session.onMessage (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:169374:35)
    at Interface.<anonymous> (/home/florin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20210907/node_modules/typescript/lib/tsserver.js:171979:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.11.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (4 x 2591)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|5.75GB (1.21GB free)|
|Process Argv|--crash-reporter-id a9a63b44-cfc1-4622-8c54-c4ff4b2edc0a|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
githistory|don|0.6.18
prettier-vscode|esb|8.1.0
vscode-docker|ms-|1.16.1
remote-containers|ms-|0.191.1
vscode-typescript-next|ms-|4.5.20210908
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
javagetstartedt:30351793
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by mjbvz** [comment]
Please share the file/project that causes this

/needsMoreInfo
