### ISSUE TITLE
search.exclude not working

### ISSUE THREAD

**Issue by pzuraq** [Microsoft/vscode#13321]
- VSCode Version: 1.5.3
- OS Version: OSX 10.11.6

When I try to use the open quickly menu, my computer searches for a while (find processes appear in the activity monitor, eating up three cores) and then it stops with this error:

```
ipc.cp.ts:139 [IPC Library: Search] Uncaught Exception:  RangeError: Invalid string length(anonymous function) @ ipc.cp.ts:139emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
ipc.cp.ts:139 [IPC Library: Search] RangeError: Invalid string length
    at Array.join (native)
    at e.decodeData (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:25:14592)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:25:14370)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)(anonymous function) @ ipc.cp.ts:139emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
ipc.cp.ts:139 [IPC Library: Search] Uncaught Exception:  RangeError: Invalid string length(anonymous function) @ ipc.cp.ts:139emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
ipc.cp.ts:139 [IPC Library: Search] RangeError: Invalid string length
    at Array.join (native)
    at e.decodeData (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:25:14592)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:25:14370)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)(anonymous function) @ ipc.cp.ts:139emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
ipc.cp.ts:139 [IPC Library: Search] Uncaught Exception:  RangeError: Invalid string length(anonymous function) @ ipc.cp.ts:139emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
ipc.cp.ts:139 [IPC Library: Search] RangeError: Invalid string length
    at Array.join (native)
    at e.decodeData (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:25:14592)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:25:14370)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)(anonymous function) @ ipc.cp.ts:139emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
internal/process/next_tick.js:103 GET file:///Users/pzuraq/.vscode/extensions/pzuraq.theme-oceanic-reef-0.0.1/preview.png net::ERR_FILE_NOT_FOUND_tickCallback @ internal/process/next_tick.js:103
```

Steps to Reproduce:

1. press cmd+p
2. type a search value and wait

**Comment by pzuraq** [comment]
Seems like it might be because find is not ignore excluded directories. Using open quickly in smaller projects is working.

My settings are:

```
// Place your settings in this file to overwrite the default settings
{
  "search.exclude": {
    "**/tmp": true,
    "**/dist": true,
    "**/bower_components": true,
    "**/node_modules": true,
    "**/vendor": true,
    "**/prodbuild": true,
    "**/public": true
  }
}
```

**Comment by pzuraq** [comment]
Confirmed, it's because `search.exclude` is not respecting the `"**/tmp"` rule

**Comment by chrmarti** [comment]
This particular case is fixed in the latest insiders builds and the upcoming 1.6. (https://github.com/Microsoft/vscode/commit/50bb7aad57cbf1924e28472de52734be49645558)

**Comment by pzuraq** [comment]
awesome, good to know. Thanks for the quick response!
