### ISSUE TITLE
Git log shows vscode asking git if a file, "${workspaceFolder}\package-lock.json" is a git repository

### ISSUE THREAD

**Issue by mjz19910** [microsoft/vscode#133328]
Issue Type: <b>Bug</b>

Avoid asking git if files are repositories!

VS Code version: Code - Insiders 1.61.0-insider (da10782b86bd9d895ccb20be4514b19728036951, 2021-09-16T08:31:28.161Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.10GB free)|
|Process Argv|--crash-reporter-id 591c8147-3794-4858-b51c-0f9c83cdcdca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
rtf|ale|2.3.0
shell|bbe|0.3.0
vscode-zonefile|Com|0.0.4
vscode-eslint|dba|2.1.25
xml|Dot|2.5.1
reasonml|fre|1.0.38
pegjs-syntax|fut|0.1.1
codespaces|Git|1.0.5
remotehub|Git|0.14.0
gc-excelviewer|Gra|3.0.44
beautify|Hoo|1.5.0
better-shellscript-syntax|jef|1.1.0
vscode-graphviz|joa|0.0.6
vscode-github|Kni|0.30.6
rust-analyzer|mat|0.2.743
jupyter|ms-|2021.9.1001244851
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.9.1517
vscode-typescript-next|ms-|4.5.20210915
run-as|ply|1.8.27
markdown-preview-enhanced|shd|0.6.0
vscode-zipexplorer|sle|0.3.1
vscode-terminal-here|Tyr|0.2.4
vscode-lldb|vad|1.6.6
vscodeintellicode|Vis|1.2.14
vscode-java-pack|vsc|0.18.4
JavaScriptSnippets|xab|1.8.0
vscode-proto3|zxh|0.5.4

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedc:30350118
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by mjz19910** [comment]
```log
Opening repository for path='${workspaceFolder}\package-lock.json' failed; ex=spawn C:\Program Files\...\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Program Files\...\git.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)```
