### ISSUE TITLE
TS opens many documents upon receiving diagnostics

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133325]
* use `"typescript.tsserver.experimental.enableProjectDiagnostics": true`, e.g I do it in https://github.com/microsoft/vscode-anycode
* very soon you seen leak warnings which all root in[`$tryOpenDocument`](https://github.com/microsoft/vscode/blob/8f8634b7747aec26d8c4f676c54c3e265e4fb0c8/src/vs/workbench/api/browser/mainThreadDocuments.ts#L212-L212) (see below)
* Debugging the extension host shows that TS call openTextDocument whenever diagnostics are delivered for a file

<img width="1184" alt="Screen Shot 2021-09-17 at 14 35 48" src="https://user-images.githubusercontent.com/1794099/133784671-3ce90351-48ff-44a9-99c9-a65f53b70d0e.png">

I am actually unsure why the leak warning appears, it might that the [BoundModelReferenceCollection](https://github.com/microsoft/vscode/blob/8f8634b7747aec26d8c4f676c54c3e265e4fb0c8/src/vs/workbench/api/browser/mainThreadDocuments.ts#L25-L25) is too relaxed

```
workbench.desktop.main.js:formatted:10121 [2b2] potential listener LEAK detected, having 251 listeners already. MOST frequent listener (80):
check @ workbench.desktop.main.js:formatted:10121
_event._event @ workbench.desktop.main.js:formatted:10145
registerListeners @ workbench.desktop.main.js:formatted:321055
bs @ workbench.desktop.main.js:formatted:321051
_createInstance @ workbench.desktop.main.js:formatted:74627
createInstance @ workbench.desktop.main.js:formatted:74608
resolve @ workbench.desktop.main.js:formatted:327970
doCreateReferencedObject @ workbench.desktop.main.js:formatted:321503
createReferencedObject @ workbench.desktop.main.js:formatted:321488
acquire @ workbench.desktop.main.js:formatted:4510
acquire @ workbench.desktop.main.js:formatted:4533
createModelReference @ workbench.desktop.main.js:formatted:321576
_handleAsResourceInput @ workbench.desktop.main.js:formatted:326597
$tryOpenDocument @ workbench.desktop.main.js:formatted:326587
_doInvokeHandler @ workbench.desktop.main.js:formatted:205281
_invokeHandler @ workbench.desktop.main.js:formatted:205267
_receiveRequest @ workbench.desktop.main.js:formatted:205217
_receiveOneMessage @ workbench.desktop.main.js:formatted:205140
(anonymous) @ workbench.desktop.main.js:formatted:205066
fire @ workbench.desktop.main.js:formatted:10167
fire @ workbench.desktop.main.js:formatted:25513
_receiveMessage @ workbench.desktop.main.js:formatted:25742
(anonymous) @ workbench.desktop.main.js:formatted:25626
fire @ workbench.desktop.main.js:formatted:10167
acceptChunk @ workbench.desktop.main.js:formatted:25371
(anonymous) @ workbench.desktop.main.js:formatted:25348
k @ workbench.desktop.main.js:formatted:381529
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
Show 2 more frames
workbench.desktop.main.js:formatted:10122     at bs.registerListeners (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2424:99439)
    at new bs (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2424:99274)
    at f._createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:600:1374)
    at f.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:600:793)
    at a.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2435:35609)
    at s.doCreateReferencedObject (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2424:113832)
    at s.createReferencedObject (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2424:113334)
    at s.acquire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:14417)
    at i.acquire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:14768)
    at d.createModelReference (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2424:115774)
    at r._handleAsResourceInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2429:74531)
    at r.$tryOpenDocument (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2429:73881)
```

**Comment by jrieken** [comment]
@mjbvz I believe you simply workaround the lack of an API that returns a language given a path/suffix, right?

**Comment by mjbvz** [comment]
Yes, we could check common file extensions (`.js`, `.ts`) but can't handle custom file `files.associations` without having a text document right now

**Comment by jrieken** [comment]
Debugged this - there is a total of 296 documents being opened (which don't leak). Today, the bound model collection goes by age (3min) and total weight (~80MB) which isn't reached here. In addition, there should also be a cap on the total count of documents opened by the extension host
