### ISSUE TITLE
JS Debugger fails to run or display any output

### ISSUE THREAD

**Issue by AaronHarris** [microsoft/vscode#133340]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1
- OS Version: Darwin x64 19.6.0

![movie](https://user-images.githubusercontent.com/1575236/133827051-27474756-22e0-49bd-a9f5-2fd534056876.gif)

Steps to Reproduce:

1. I am using the Remote - SSH extension  to connect to an Amazon Linux 2 EC2 host running a Typescript CDK project in workspace mode. 
2. I setup the launch configuration as shown and the debugger shows the controls for a split-second before disappearing, and the only output is in the Log (Window) which shows that the debugger has crashed. There is nothing printed in the Debug Console at all.
3. NOTE: I have a separate window open using the same setup (Remote - SSH) extension to another (much older) Amazon Linux 2012 EC2 host for a similar project using the exact same launch configuration (save for the path) and the debugger works as expected. (It shows that it starts running the command `/usr/local/bin/node -r ./node_modules/ts-node/register/transpile-only ./bin/app.js /local/home/myuser/path/to/project/`)

Launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program transpile",
            "program": "${workspaceFolder}/packages/cdk/dist/app.js",
            "request": "launch",
            "runtimeArgs": [
                "-r", "./node_modules/ts-node/register/transpile-only"
            ],
            "skipFiles": [
                "<node_internals>/**"
            ],
            "args": [
                "${workspaceFolder}/"
            ],
            "type": "pwa-node",
         }
   ]
}
```

Error:
```
ERR No debugger available, can not send 'exception breakpoints': Error: No debugger available, can not send 'exception breakpoints'
    at O.sendExceptionBreakpoints (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1943:41545)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1982:48879
    at K (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1982:51803)
    at j.sendExceptionBreakpoints (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1982:48666)
    at j.sendAllBreakpoints (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1982:47504)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1943:49704
```

**Comment by AaronHarris** [comment]
So I manually ran the command

```
node -r ./node_modules/ts-node/register/transpile-only.js packages/cdk/dist/app.js
```
 from a regular remote terminal with a breakpoint in VS Code active and the debugger automatically attaches and stops at the breakpoint. So it looks like something is broken with the launch part of the debugger? Wish there was some output I could use to figure out what's wrong.

**Comment by hawkeye64** [comment]
I am having the exact same issue. I can run from the command-line, but can't start with vs code.

```
Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:06:57.931Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-34-generic snap
```

I am wondering if it has anything to do with installing with `snap` (with `--classic` param)?

My launch config:

```json
{
      "name": "Launch Program",
      "program": "${workspaceFolder}/index.js",
      "request": "launch",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "pwa-node"
    }
    ```

**Comment by hawkeye64** [comment]
I uninstalled the snap installed version and installed the deb version and everything is working as expected again - for me.

**Comment by roblourens** [comment]
@AaronHarris can you set `"trace": true` in your launch config, try again, and see whether you get a path to a log printed in the debug console? It might be failing too early for that in which case I might have you try setting a breakpoint.

**Comment by AaronHarris** [comment]
Yeah I tried "trace": true but I don't get any output. How do I set a breakpoint on the debugger launching?

**Comment by roblourens** [comment]
As a test can you try with a different launch config, maybe something simpler just without the runtimeArgs?

@connor4312 any idea what might be going on? One clue is that it only fails at the point of sending exception breakpoints, but we would have sent other breakpoints before that point

https://github.com/microsoft/vscode/blob/a91a307436c31831705a19a7c862a367145b1e11/src/vs/workbench/contrib/debug/browser/debugService.ts#L1016-L1023

**Comment by connor4312** [comment]
Hm, not sure. js-debug will always print the command it's running before the debug session starts so it doesn't even get there. @AaronHarris are there any errors that are shown before the one in your gif?

**Comment by smcallis** [comment]
I'm seeing this as well, I had chrome setup to run as my debugger.  I set down what I was doing for a week or so and came back and chrome no longer launches.  My launch.json is even simpler:

```
 {
   "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome Debugger",
            "url": "http://localhost:1234",
            "webRoot": "${workspaceFolder}",
            "preLaunchTask": "start",
        }
    ]
}
 
```
