### ISSUE TITLE
unable to install python extension

### ISSUE THREAD

**Issue by mkniswonger** [microsoft/vscode#133443]
Issue Type: <b>Bug</b>

attempt to install -- it says, no download it -- i always have to do that -- i do, and it says install from visx, and usually this would work, but with python, it blows up:

[2021-09-20 09:10:19.065] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found: unknown: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17341
    at Array.reduce (<anonymous>)
    at g (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17327)
    at O.joinAllSettled (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:9895)
    at async O.installExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:7440)
[2021-09-20 09:10:57.139] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at F.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)
    at async F.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)

I have tried this repeatedly, and now have python uninstalled, which i thought might help. Now i simply cannot get it back no matter what. I tried disabling all other extensions, and that made no difference. I dont understand why this suddenly stopped working. I have not tried uninstalling vscode completely, but i feel like thats the next step.

suggestions? I write python code, so this is a really impt function to have!

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.70GB free)|
|Process Argv|--crash-reporter-id b9ffdf3f-7569-4b8d-ae9e-753543c87c8c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by sandy081** [comment]
Please follow these steps and provide us info:

- Enable log level to trace `F1 > Set Log Level... > Trace`
- Repeat installing python extension
- Open shared process log `F1 > Open View... > Log (Shared)`
- Share this log with us.

**Comment by mkniswonger** [comment]
it will not allow me to attach a text file...

**Comment by mkniswonger** [comment]
[2021-09-20 12:18:10.385] [sharedprocess] [info] Deleted from disk ms-toolsai.jupyter-keymap /Users/userid/.vscode/extensions/ms-toolsai.jupyter-keymap-1.0.0
[2021-09-20 12:18:11.323] [sharedprocess] [info] Deleted from disk ms-python.python /Users/userid/.vscode/extensions/ms-python.python-2021.9.1230869389
[2021-09-20 12:18:12.591] [sharedprocess] [info] Installing extension: esbenp.prettier-vscode
[2021-09-20 12:18:13.979] [sharedprocess] [info] Downloaded extension: esbenp.prettier-vscode /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/esbenp.prettier-vscode-9.0.0
[2021-09-20 12:18:14.849] [sharedprocess] [info] Extracted extension to /Users/userid/.vscode/extensions/.c082a719-11b6-40b5-a581-dfb7d42a7876: esbenp.prettier-vscode
[2021-09-20 12:18:14.880] [sharedprocess] [info] Renamed to /Users/userid/.vscode/extensions/esbenp.prettier-vscode-9.0.0
[2021-09-20 12:18:14.883] [sharedprocess] [info] Extracting completed. esbenp.prettier-vscode
[2021-09-20 12:18:14.902] [sharedprocess] [info] Extension installed successfully: esbenp.prettier-vscode
[2021-09-20 12:18:19.735] [sharedprocess] [info] [logs cleanup]: Starting to clean up old logs.
[2021-09-20 12:18:19.741] [sharedprocess] [info] [logs cleanup]: Removing log folders '20210824T144559'
[2021-09-20 12:18:39.736] [sharedprocess] [info] [code cache cleanup]: Starting to clean up old code cache folders.
[2021-09-20 12:18:39.736] [sharedprocess] [info] [storage cleanup]: Starting to clean up storage folders.
[2021-09-20 12:18:49.737] [sharedprocess] [info] [language pack cache cleanup]: Starting to clean up unused language packs.
[2021-09-20 13:25:48.234] [sharedprocess] [info] Installing extension: ms-azuretools.vscode-docker
[2021-09-20 13:25:49.268] [sharedprocess] [info] Downloaded extension: ms-azuretools.vscode-docker /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-azuretools.vscode-docker-1.17.0
[2021-09-20 13:25:49.573] [sharedprocess] [info] Extracted extension to /Users/userid/.vscode/extensions/.304795f6-c9c3-44dc-82f4-139ed45728f4: ms-azuretools.vscode-docker
[2021-09-20 13:25:49.583] [sharedprocess] [info] Renamed to /Users/userid/.vscode/extensions/ms-azuretools.vscode-docker-1.17.0
[2021-09-20 13:25:49.586] [sharedprocess] [info] Extracting completed. ms-azuretools.vscode-docker
[2021-09-20 13:25:49.603] [sharedprocess] [info] Extension installed successfully: ms-azuretools.vscode-docker
[2021-09-20 14:51:51.737] [sharedprocess] [info] Installing extension: davidanson.vscode-markdownlint
[2021-09-20 14:51:52.355] [sharedprocess] [info] Downloaded extension: davidanson.vscode-markdownlint /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/davidanson.vscode-markdownlint-0.44.1
[2021-09-20 14:51:52.399] [sharedprocess] [info] Extracted extension to /Users/userid/.vscode/extensions/.792f7f46-ae31-4073-8b8d-eb79377fe057: davidanson.vscode-markdownlint
[2021-09-20 14:51:52.410] [sharedprocess] [info] Renamed to /Users/userid/.vscode/extensions/davidanson.vscode-markdownlint-0.44.1
[2021-09-20 14:51:52.412] [sharedprocess] [info] Extracting completed. davidanson.vscode-markdownlint
[2021-09-20 14:51:52.434] [sharedprocess] [info] Extension installed successfully: davidanson.vscode-markdownlint
[2021-09-20 14:52:30.394] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:30.394] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:30.394] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:30.394] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:30.473] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:30.476] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:30.523] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:30.537] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:37.091] [sharedprocess] [trace] RequestService#request https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2021.9.1230869389/1631566013742/Microsoft.VisualStudio.Code.Manifest
[2021-09-20 14:52:37.097] [sharedprocess] [info] Installing extension: ms-python.python
[2021-09-20 14:52:37.097] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:37.097] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:37.145] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:37.175] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:37.176] [sharedprocess] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-09-20 14:52:37.220] [sharedprocess] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-09-20 14:52:37.297] [sharedprocess] [trace] RequestService#request https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2021.8.2041215044/1631139280151/Microsoft.VisualStudio.Code.Manifest
[2021-09-20 14:52:37.369] [sharedprocess] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-09-20 14:52:37.420] [sharedprocess] [trace] RequestService#request https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter-keymap/1.0.0/1629490473618/Microsoft.VisualStudio.Code.Manifest
[2021-09-20 14:52:37.458] [sharedprocess] [trace] RequestService#request https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/vscode-pylance/2021.9.2/1631829122076/Microsoft.VisualStudio.Code.Manifest
[2021-09-20 14:52:37.620] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:37.620] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:37.655] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:37.683] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:37.684] [sharedprocess] [info] Installing extension: ms-toolsai.jupyter
[2021-09-20 14:52:37.685] [sharedprocess] [info] Installing extension: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:37.685] [sharedprocess] [info] Installing extension: ms-python.vscode-pylance
[2021-09-20 14:52:37.685] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:37.685] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:37.685] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:37.685] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:37.685] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:37.685] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:37.768] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:37.769] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:37.772] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:37.833] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:37.833] [sharedprocess] [trace] Started downloading extension: ms-python.python
[2021-09-20 14:52:37.834] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:37.834] [sharedprocess] [trace] Started downloading extension: ms-toolsai.jupyter
[2021-09-20 14:52:37.834] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:37.834] [sharedprocess] [trace] Started downloading extension: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:37.835] [sharedprocess] [info] Downloaded extension: ms-toolsai.jupyter /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-2021.8.2041215044
[2021-09-20 14:52:37.839] [sharedprocess] [info] Downloaded extension: ms-python.python /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-python.python-2021.9.1230869389
[2021-09-20 14:52:37.839] [sharedprocess] [info] Downloaded extension: ms-toolsai.jupyter-keymap /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-keymap-1.0.0
[2021-09-20 14:52:37.845] [sharedprocess] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-09-20 14:52:37.846] [sharedprocess] [error] validating: Corrupt ZIP: end of central directory record signature not found
    at F.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)
    at async F.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)
[2021-09-20 14:52:37.850] [sharedprocess] [error] Error while installing the extension: ms-python.python
[2021-09-20 14:52:37.850] [sharedprocess] [error] validating: Corrupt ZIP: end of central directory record signature not found
    at F.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)
    at async F.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)
[2021-09-20 14:52:37.859] [sharedprocess] [trace] Started extracting the extension from /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-keymap-1.0.0 to /Users/userid/.vscode/extensions/.66fd5558-4e76-4b0b-bf5e-c8400bc15aae
[2021-09-20 14:52:37.871] [sharedprocess] [info] Extracted extension to /Users/userid/.vscode/extensions/.66fd5558-4e76-4b0b-bf5e-c8400bc15aae: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:37.879] [sharedprocess] [info] Renamed to /Users/userid/.vscode/extensions/ms-toolsai.jupyter-keymap-1.0.0
[2021-09-20 14:52:37.880] [sharedprocess] [info] Extracting completed. ms-toolsai.jupyter-keymap
[2021-09-20 14:52:37.889] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:37.909] [sharedprocess] [trace] Scanned user extensions: 25
[2021-09-20 14:52:37.914] [sharedprocess] [info] Rollback: Uninstalled extension ms-toolsai.jupyter-keymap
[2021-09-20 14:52:37.914] [sharedprocess] [error] Failed to install extension: ms-python.python Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found
[2021-09-20 14:52:37.922] [sharedprocess] [trace] [File Watcher (node.js)] [CHANGED] /Users/userid/.vscode/extensions/.obsolete
[2021-09-20 14:52:38.023] [sharedprocess] [trace] [File Watcher (node.js)] [DELETED] /Users/userid/.vscode/extensions/.66fd5558-4e76-4b0b-bf5e-c8400bc15aae
[2021-09-20 14:52:38.023] [sharedprocess] [trace] [File Watcher (node.js)] [ADDED] /Users/userid/.vscode/extensions/ms-toolsai.jupyter-keymap-1.0.0
[2021-09-20 14:52:38.226] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [DELETED] /Users/userid/.vscode/extensions/.66fd5558-4e76-4b0b-bf5e-c8400bc15aae
[2021-09-20 14:52:38.226] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /Users/userid/.vscode/extensions/.obsolete
[2021-09-20 14:52:38.227] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [ADDED] /Users/userid/.vscode/extensions/ms-toolsai.jupyter-keymap-1.0.0
[2021-09-20 14:52:38.227] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:38.251] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:54.038] [sharedprocess] [trace] ExtensionManagementService#install file:///Users/userid/Downloads/ms-python.python-2021.9.1230869389%20%281%29.vsix
[2021-09-20 14:52:54.049] [sharedprocess] [info] Installing extension: ms-python.python
[2021-09-20 14:52:54.049] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:54.049] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:54.085] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:54.111] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:54.112] [sharedprocess] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-09-20 14:52:54.161] [sharedprocess] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-09-20 14:52:54.241] [sharedprocess] [trace] RequestService#request https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2021.8.2041215044/1631139280151/Microsoft.VisualStudio.Code.Manifest
[2021-09-20 14:52:54.246] [sharedprocess] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-09-20 14:52:54.285] [sharedprocess] [trace] RequestService#request https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter-keymap/1.0.0/1629490473618/Microsoft.VisualStudio.Code.Manifest
[2021-09-20 14:52:54.288] [sharedprocess] [trace] RequestService#request https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/vscode-pylance/2021.9.2/1631829122076/Microsoft.VisualStudio.Code.Manifest
[2021-09-20 14:52:54.290] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:54.291] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:54.322] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:54.350] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:54.351] [sharedprocess] [info] Installing extension: ms-toolsai.jupyter
[2021-09-20 14:52:54.351] [sharedprocess] [info] Installing extension: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:54.351] [sharedprocess] [info] Installing extension: ms-python.vscode-pylance
[2021-09-20 14:52:54.351] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:54.352] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:54.352] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:54.352] [sharedprocess] [trace] Started scanning system extensions
[2021-09-20 14:52:54.352] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:54.428] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:54.429] [sharedprocess] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-09-20 14:52:54.431] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:54.435] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:54.479] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:54.479] [sharedprocess] [trace] Started downloading extension: ms-toolsai.jupyter
[2021-09-20 14:52:54.480] [sharedprocess] [info] Downloaded extension: ms-toolsai.jupyter /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-2021.8.2041215044
[2021-09-20 14:52:54.480] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:54.481] [sharedprocess] [trace] Started downloading extension: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:54.481] [sharedprocess] [info] Downloaded extension: ms-toolsai.jupyter-keymap /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-keymap-1.0.0
[2021-09-20 14:52:54.488] [sharedprocess] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-09-20 14:52:54.488] [sharedprocess] [error] validating: Corrupt ZIP: end of central directory record signature not found
    at F.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)
    at async F.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)
[2021-09-20 14:52:54.495] [sharedprocess] [trace] Started extracting the extension from /Users/userid/Downloads/ms-python.python-2021.9.1230869389 (1).vsix to /Users/userid/.vscode/extensions/.a87ba23a-fd72-40a8-a388-f787f9ebfaf2
[2021-09-20 14:52:54.498] [sharedprocess] [trace] Removing the extension from uninstalled list: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:54.504] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:54.515] [sharedprocess] [trace] [File Watcher (node.js)] [CHANGED] /Users/userid/.vscode/extensions/.obsolete
[2021-09-20 14:52:54.528] [sharedprocess] [trace] Scanned user extensions: 25
[2021-09-20 14:52:54.535] [sharedprocess] [info] Removed the extension from uninstalled list: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:54.615] [sharedprocess] [trace] [File Watcher (node.js)] [ADDED] /Users/userid/.vscode/extensions/.a87ba23a-fd72-40a8-a388-f787f9ebfaf2
[2021-09-20 14:52:54.817] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /Users/userid/.vscode/extensions/.obsolete
[2021-09-20 14:52:54.817] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [ADDED] /Users/userid/.vscode/extensions/.a87ba23a-fd72-40a8-a388-f787f9ebfaf2
[2021-09-20 14:52:54.817] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:54.842] [sharedprocess] [trace] Scanned user extensions: 25
[2021-09-20 14:52:59.285] [sharedprocess] [info] Extracted extension to /Users/userid/.vscode/extensions/.a87ba23a-fd72-40a8-a388-f787f9ebfaf2: ms-python.python
[2021-09-20 14:52:59.307] [sharedprocess] [info] Renamed to /Users/userid/.vscode/extensions/ms-python.python-2021.9.1230869389
[2021-09-20 14:52:59.309] [sharedprocess] [info] Extracting completed. ms-python.python
[2021-09-20 14:52:59.316] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:59.316] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:59.359] [sharedprocess] [trace] Scanned user extensions: 26
[2021-09-20 14:52:59.361] [sharedprocess] [trace] Scanned user extensions: 26
[2021-09-20 14:52:59.375] [sharedprocess] [info] Rollback: Uninstalled extension ms-toolsai.jupyter-keymap
[2021-09-20 14:52:59.375] [sharedprocess] [info] Rollback: Uninstalled extension ms-python.python
[2021-09-20 14:52:59.375] [sharedprocess] [error] Failed to install extension: ms-python.python Corrupt ZIP: end of central directory record signature not found
[2021-09-20 14:52:59.424] [sharedprocess] [trace] [File Watcher (node.js)] [CHANGED] /Users/userid/.vscode/extensions/.obsolete
[2021-09-20 14:52:59.424] [sharedprocess] [trace] [File Watcher (node.js)] [DELETED] /Users/userid/.vscode/extensions/.a87ba23a-fd72-40a8-a388-f787f9ebfaf2
[2021-09-20 14:52:59.424] [sharedprocess] [trace] [File Watcher (node.js)] [ADDED] /Users/userid/.vscode/extensions/ms-python.python-2021.9.1230869389
[2021-09-20 14:52:59.631] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [DELETED] /Users/userid/.vscode/extensions/.a87ba23a-fd72-40a8-a388-f787f9ebfaf2
[2021-09-20 14:52:59.631] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /Users/userid/.vscode/extensions/.obsolete
[2021-09-20 14:52:59.631] [sharedprocess] [trace] [File Watcher (node.js)] >> normalized [ADDED] /Users/userid/.vscode/extensions/ms-python.python-2021.9.1230869389
[2021-09-20 14:52:59.632] [sharedprocess] [trace] Started scanning user extensions
[2021-09-20 14:52:59.657] [sharedprocess] [trace] Scanned user extensions: 24
[2021-09-20 14:52:59.657] [sharedprocess] [info] Detected extension removed from another source ms-toolsai.jupyter-keymap
[2021-09-20 14:53:31.273] [sharedprocess] [trace] profile not validated fish ["fish"]
[2021-09-20 14:53:31.289] [sharedprocess] [trace] profile not validated tmux ["tmux"]
[2021-09-20 14:53:31.308] [sharedprocess] [trace] profile not validated pwsh ["pwsh"]
[2021-09-20 14:53:33.211] [sharedprocess] [trace] profile not validated fish ["fish"]
[2021-09-20 14:53:33.218] [sharedprocess] [trace] profile not validated tmux ["tmux"]
[2021-09-20 14:53:33.224] [sharedprocess] [trace] profile not validated pwsh ["pwsh"]
[2021-09-20 14:53:40.967] [sharedprocess] [trace] profile not validated fish ["fish"]
[2021-09-20 14:53:40.974] [sharedprocess] [trace] profile not validated tmux ["tmux"]
[2021-09-20 14:53:40.980] [sharedprocess] [trace] profile not validated pwsh ["pwsh"]
[2021-09-20 14:53:42.961] [sharedprocess] [trace] profile not validated fish ["fish"]
[2021-09-20 14:53:42.967] [sharedprocess] [trace] profile not validated tmux ["tmux"]
[2021-09-20 14:53:42.974] [sharedprocess] [trace] profile not validated pwsh ["pwsh"]

**Comment by sandy081** [comment]
```
[2021-09-20 14:52:54.479] [sharedprocess] [trace] Started downloading extension: ms-toolsai.jupyter
[2021-09-20 14:52:54.480] [sharedprocess] [info] Downloaded extension: ms-toolsai.jupyter /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-2021.8.2041215044
[2021-09-20 14:52:54.480] [sharedprocess] [trace] Scanned system extensions: 83
[2021-09-20 14:52:54.481] [sharedprocess] [trace] Started downloading extension: ms-toolsai.jupyter-keymap
[2021-09-20 14:52:54.481] [sharedprocess] [info] Downloaded extension: ms-toolsai.jupyter-keymap /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-keymap-1.0.0
[2021-09-20 14:52:54.488] [sharedprocess] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-09-20 14:52:54.488] [sharedprocess] [error] validating: Corrupt ZIP: end of central directory record signature not found
at F.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196400)
at async F.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195377)
```

Can you please clear all vsixs in this folder `/Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/`and retry?

**Comment by shanff** [comment]
Clearing the VSIXs in the AppData/Roaming/Code/CachedExtensionVSIXs folder on Windows did it for me.  Thanks!  Had the same issue.

**Comment by mkniswonger** [comment]
Oh WOW! I was able to get the extension installed by doing the following:

1. close current workspace
2. exit vsCode
3. remove all files from folder /Users/userid/Library/Application Support/Code/CachedExtensionVSIXs/
4. empty trash
5. reopen vsCode
6. use install from VSIX option in extensions to pick the already-downloaded file.

thank you for the pointers!

**Comment by mkniswonger** [comment]
all set now

**Comment by GeckoEidechse** [comment]
For Linux the location is `~/.config/Code/CachedExtensionVSIXs`. Closing vscode, deleting all files in that directorym and reopening vscode allowed me to install the extension that was previously failing.

It might be sensible to force redownloading/bypassing cache if installing a (cached) extension fails with checksum errors.
