### ISSUE TITLE
Can not execute the ./script/code.sh

### ISSUE THREAD

**Issue by tanyx95** [microsoft/vscode#133705]
- VS Code Version: 1.24.1
- OS Version: macOS Big Sur Version 11.5.2
- Node: 8.17.0
- Python: 2.7.11

Steps to Reproduce:

1. ./script/code.sh

I want to execute ./script/code.sh, but I got this return

```
[18:09:10] Using gulpfile ~/Yusys/vscode-1.24.1/gulpfile.js
[18:09:10] Starting 'clean-electron'...
[18:09:10] Finished 'clean-electron' after 4.41 ms
[18:09:10] Starting 'electron'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.

Error: end of central directory record signature not found
    at /Users/baozi/Yusys/vscode-1.24.1/node_modules/yauzl/index.js:183:14
    at /Users/baozi/Yusys/vscode-1.24.1/node_modules/yauzl/index.js:622:5
    at /Users/baozi/Yusys/vscode-1.24.1/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
[18:09:11] Syncronizing built-in extensions...
[18:09:11] You can manage built-in extensions with the --builtin flag
[18:09:11] [marketplace] ms-vscode.node-debug@1.24.0 ✔︎
[18:09:11] [marketplace] ms-vscode.node-debug2@1.24.2 ✔︎
```

I try to find the similar issue like [#100624](https://github.com/microsoft/vscode/issues/100624)
but I can't find the gulp-electron-cache folder in my tmp folder.

**Comment by gjsjohnmurray** [comment]
Please update to the current release of VS Code. Then re-test.

**Comment by tanyx95** [comment]
I try to delete the contents of `~/Library/Caches/node-gyp/`
and then I run `yarn cache clean`
It works for me.
