### ISSUE TITLE
Unable to install stable version of extension in WSL

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#133777]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.2
- OS Version: Windows (WSL2)

Steps to Reproduce:

1. Install Jupyter extension 2021.8.2041215044 (this is tied to engine 1.60, stable version)
2. Some how during the installation a new extension (renderer extension gets pulled, 
	*  Renderer extension https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers
	* The renderer extension is a separate extension included in the insider version of Jupyter extension. 
	* The latest insider version of Jupyter extension is published to the marketplace & tied to engine 1.61
	* However it seems VSCode is somehow getting things mixed up and pulling extensions that are not relevant
3. As a result @jflam cannot install the Jupyter extension in Stable vscode.

Please see logs below
@sandy081 /cc

Logs
```
[2021-09-24 07:28:20.294] [renderer1] [info] Creating lazy extension host: contains 1 extension(s): GitHub.vscode-pull-request-github.

[2021-09-24 07:28:22.734] [renderer1] [info] Downloading the 'ms-python.vscode-pylance' extension locally and install

[2021-09-24 07:28:24.209] [renderer1] [info] Downloading the workspace dependencies and packed extensions of 'ms-python.vscode-pylance' locally and install

[2021-09-24 07:28:24.209] [renderer1] [info] Downloaded extension: ms-python.python /c:/Users/jlam/AppData/Local/Temp/41a9ae12-157e-47c4-bb55-e4849a4aa64d

[2021-09-24 07:28:30.385] [renderer1] [info] Successfully installed 'ms-python.python' extension

[2021-09-24 07:28:30.501] [renderer1] [info] Downloaded extension: ms-toolsai.jupyter /c:/Users/jlam/AppData/Local/Temp/0d770c87-2d69-4a2a-98d3-75efe6bda868

[2021-09-24 07:28:32.923] [renderer1] [info] Successfully installed 'ms-toolsai.jupyter' extension

[2021-09-24 07:28:32.999] [renderer1] [error] Unable to install extension 'ms-toolsai.jupyter-renderers' as it is not compatible with VS Code '1.60.2'.: Error: Unable to install extension 'ms-toolsai.jupyter-renderers' as it is not compatible with VS Code '1.60.2'.

    at a.downloadCompatibleAndInstall (vscode-file://vscode-app/c:/Users/jlam/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2872:133252)

    at async a.downloadAndInstall (vscode-file://vscode-app/c:/Users/jlam/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2872:132847)

    at async a.installFromGallery (vscode-file://vscode-app/c:/Users/jlam/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2872:131878)

    at async Promise.all (index 0)

    at async Object.V [as settled] (vscode-file://vscode-app/c:/Users/jlam/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:77:21987)

    at async ps.installFromGallery (vscode-file://vscode-app/c:/Users/jlam/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2867:19777)

 

This happened right after I installed from the VSIX that you suggested (and every time I try to uninstall Jupyter). In this case, you can see it downloads the latest versions of pylance, python and Jupyter and then it tries to install Jupyter-renderers. I don’t understand how references between extensions are expressed so I don’t know where to look for what is pulling in Jupyter-renderers – should any production extension be referencing this new extension?

 

Yes it’s appearing consistently for me – code is effectively broken for Python on this machine. Also note that I’m using WSL2 as well.

 ```

![image](https://user-images.githubusercontent.com/1948812/134739361-f7d69c5e-5f0b-4f72-9fec-5b18888bba30.png)

**Comment by jflam** [comment]
That was quick. Thanks @sandy081 and @DonJayamanne!

**Comment by rchiodo** [comment]
@sandy081 @DonJayamanne In order to verify this, do we need to test this on stable VS code? And then create an extension pack that references insider only extensions and try to install it?

**Comment by sandy081** [comment]
You can also test on insiders by having an extension (that is included in the pack) with newer version not compatible but one of the older versions is.

**Comment by DonJayamanne** [comment]
Sorry, but i was never able to repro this issue, even John wasn't able to repro this issue in insiders. it was only broken in stable for him, hence I don't see how we can test this (i.e. i  couldn't repro in stable except for John).

**Comment by sandy081** [comment]
To verify:

- Open any remote folder (WSL or SSH or DevContainer)
- Enable `remote.downloadExtensionsLocally` setting to `true`
- Search for `sandy081.999-test-pack` extension
- Install and make sure Install succeeds and `sandy081.998-test-incompatible` is not installed.

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/135987189-c7ba3608-f1ae-4373-9514-a6de90b59f21.png)
