### ISSUE TITLE
Can't launch integrated terminal

### ISSUE THREAD

**Issue by danedang** [Microsoft/vscode#13374]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  输出 Ctrl + ~
2.  错误详情:workbench.main.js:93 通过退出代码 1 终止的终端进程e.doShow @ workbench.main.js:93
workbench.main.js:118 [Extension Host] Unhandled Rejection at: Promise  Object  reason:  TypeError: Cannot read property 'isEqual' of undefined
    at ModeHandler.<anonymous> (C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:436:58)
    at next (native)
    at C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:7:65
    at __awaiter (C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:3:12)
    at ModeHandler.vscode.window.onDidChangeTextEditorSelection (C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:419:61)
    at e.invoke (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:13653)
    at e.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:15829)
    at t.$acceptSelectionsChanged (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:19957)
    at t.e.handle (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:22905)
    at s (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30449)
workbench.main.js:118 [Extension Host] Unhandled Rejection at: Promise  Object  reason:  TypeError: Cannot read property 'isEqual' of undefined
    at ModeHandler.<anonymous> (C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:436:58)
    at next (native)
    at C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:7:65
    at __awaiter (C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:3:12)
    at ModeHandler.vscode.window.onDidChangeTextEditorSelection (C:\Users\xxx\.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:419:61)
    at e.invoke (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:13653)
    at e.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:15829)
    at t.$acceptSelectionsChanged (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:19957)
    at t.e.handle (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:22905)
    at s (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30449)

**Comment by ZCShou** [comment]
文件名是中文的？

**Comment by rebornix** [comment]
Repro steps from @danedang 

1. Press `ctrl+~`
2. `workbench.main.js:93 `, exit code 1. Call stack: 
```
e.doShow @ workbench.main.js:93 workbench.main.js:118 [Extension Host] Unhandled Rejection at: Promise Object reason: TypeError: Cannot read property 'isEqual' of undefined at ModeHandler. (C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:436:58) at next (native) at C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:7:65 at __awaiter (C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:3:12) at ModeHandler.vscode.window.onDidChangeTextEditorSelection (C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:419:61) at e.invoke (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:13653) at e.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:15829) at t.$acceptSelectionsChanged (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:19957) at t.e.handle (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:22905) at s (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30449) workbench.main.js:118 [Extension Host] Unhandled Rejection at: Promise Object reason: TypeError: Cannot read property 'isEqual' of undefined at ModeHandler. (C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:436:58) at next (native) at C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:7:65 at __awaiter (C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:3:12) at ModeHandler.vscode.window.onDidChangeTextEditorSelection (C:\Users\xxx.vscode\extensions\vscodevim.vim-0.2.0\out\src\mode\modeHandler.js:419:61) at e.invoke (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:13653) at e.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:15829) at t.$acceptSelectionsChanged (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:19957) at t.e.handle (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:22905) at s (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30449)
```

**Comment by Tyriar** [comment]
Looks like it's related to the Vim extension, please file there https://github.com/VSCodeVim/Vim
