### ISSUE TITLE
Razor.VSCode version 6.0.0-preview.5.21358.6 -------------------------------------------------------------------------------- Razor's trace level is currently set to 'Off'  - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.  - To report issues invoke the 'Report a Razor issue' command via the command palette.

### ISSUE THREAD

**Issue by oledran** [microsoft/vscode#134014]
Issue Type: <b>Bug</b>

[Error - 10:31:46] Server initialization failed.
  Message: Internal Error - System.UnauthorizedAccessException: Access to the path 'c:\Arquivos de Programas' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath) in System.Private.CoreLib.dll:token 0x6005e91+0x4b
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext() in System.Private.CoreLib.dll:token 0x6005e96+0x0
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in System.Private.CoreLib.dll:token 0x6006875+0x85
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions) in System.Private.CoreLib.dll:token 0x6005912+0x0
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption) in System.Private.CoreLib.dll:token 0x6005911+0x0
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.GetExistingConfigurationFiles(String workspaceDirectory) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 119
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.StartAsync(String workspaceDirectory, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 56
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorFileChangeDetectorManager.InitializedAsync() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetectorManager.cs:line 46
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorLanguageServer.<>c__DisplayClass9_0.<<CreateAsync>b__2>d.MoveNext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs:line 103
--- End of stack trace from previous location ---
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InternalInitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle(InternalInitializeParams request, CancellationToken token) in OmniSharp.Extensions.LanguageServer.dll:token 0x6000032+0x96d
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in OmniSharp.Extensions.LanguageServer.dll:token 0x60000a0+0x2a6
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in OmniSharp.Extensions.LanguageServer.dll:token 0x600009f+0x0
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000058+0x0
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000056+0x0
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000053+0x0
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000053+0x25c
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x600004a+0x0
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x600004a+0x1cd
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|5_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger) in OmniSharp.Extensions.JsonRpc.dll:token 0x600022a+0xfc
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000221+0x622
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext() in OmniSharp.Extensions.JsonRpc.dll:token 0x60010

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22463
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.91GB free)|
|Process Argv|--crash-reporter-id f66f5d7b-8694-4a4b-a46f-a4760d7fe71f|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.1.25
vscode-npm-script|eg2|0.3.22
php-debug|fel|1.19.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.4
vscode-pull-request-github|Git|0.30.0
go|gol|0.28.1
file-downloader|min|1.0.11
vscode-docker|ms-|1.17.0
vscode-language-pack-pt-BR|MS-|1.60.4
csharp|ms-|1.23.15
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-wsl|ms-|0.58.2
debugger-for-chrome|msj|4.13.0
vscode-yaml|red|0.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792

```

</details>

**Comment by oledran** [comment]
Valeu!!! obrigado.

Em ter., 28 de set. de 2021 às 11:27, VS Code Issue Triage Bot <
***@***.***> escreveu:
