### ISSUE TITLE
A `win32-x64` targeting extension shows "install" on WSL ubuntu

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#134089]
Testing #133868

![image](https://user-images.githubusercontent.com/3840081/135210466-9826101a-4e1a-4ce7-b34c-34672c2f83fc.png)

Install however fails with: 
![image](https://user-images.githubusercontent.com/3840081/135210566-b0a3ff0c-c508-4712-a7d9-57d005c1ab7e.png)

Logs:
```
[2021-09-28 22:27:55.961] [renderer5] [info] Starting extension host with pid 24212.
[2021-09-28 22:27:55.961] [renderer5] [info] [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 26 ms.
[2021-09-28 22:28:04.519] [renderer5] [info] Installing UI dependencies and packed extensions of 'ms-toolsai.jupyter' locally
[2021-09-28 22:28:32.609] [renderer5] [info] Starting extension host with pid 7188.
[2021-09-28 22:28:32.609] [renderer5] [info] [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 26 ms.
[2021-09-28 22:45:48.281] [renderer5] [info] Starting extension host with pid 20280.
[2021-09-28 22:45:48.290] [renderer5] [info] [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 29 ms.
[2021-09-28 22:46:35.494] [renderer5] [error] Error while installing 'karthiknadigtest.kanadig-platform-ext-test-2' extension in the remote server. The 'karthiknadigtest.kanadig-platform-ext-test-2' extension is not available in Visual Studio Code - Insiders for Linux 64 bit.
[2021-09-28 22:46:35.495] [renderer5] [info] Downloading the 'karthiknadigtest.kanadig-platform-ext-test-2' extension locally and install
[2021-09-28 22:46:35.566] [renderer5] [error] Error: Unable to install extension 'karthiknadigtest.kanadig-platform-ext-test-2' as it is not compatible with VS Code '1.61.0-insider'.
    at d.checkAndGetCompatible (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2924:135956)
    at async downloadAndInstall (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2924:134890)
    at async doInstallFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2924:134678)
    at async d.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2924:134239)
    at async Promise.all (index 0)
    at async Object.z [as settled] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:77:22863)
    at async Bs.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2919:19789)
[2021-09-28 22:46:35.569] [renderer5] [error] ["validating: The 'karthiknadigtest.kanadig-platform-ext-test-2' extension is not available in Visual Studio Code - Insiders for Linux 64 bit.","    at N.installFromGallery (/home/kanadig/.vscode-server-insiders/bin/214ac689ca9874a8a4be386f73d5cb60e15af25e/out/vs/server/remoteExtensionHostAgent.js:110:3063)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)"]
[2021-09-28 22:46:35.573] [renderer5] [error] The 'karthiknadigtest.kanadig-platform-ext-test-2' extension is not available in Visual Studio Code - Insiders for Linux 64 bit.: validating: The 'karthiknadigtest.kanadig-platform-ext-test-2' extension is not available in Visual Studio Code - Insiders for Linux 64 bit.
    at N.installFromGallery (/home/kanadig/.vscode-server-insiders/bin/214ac689ca9874a8a4be386f73d5cb60e15af25e/out/vs/server/remoteExtensionHostAgent.js:110:3063)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by sandy081** [comment]
Install Action is enabled because it is compatible with Windows and VS Code client platform is Windows. When installing we check the extension kind and install it at the proper location (client / remote). Since we do not know location info upfront we cannot disable the action. This is known limitation in the Remote Set up.

**Comment by sandy081** [comment]
Anyways, fixed the error prompt. It now shows that the extension is incompatible instead of download prompt.

**Comment by karthiknadig** [comment]
I am still seeing this prompt:
![image](https://user-images.githubusercontent.com/3840081/135679628-c61f09ae-63fe-4f6b-a509-f71b49db90bf.png)

Version: 1.61.0-insider (system setup)
Commit: c9e8266ee24f34107ff52d836a4e8f533afb93c5
Date: 2021-10-01T14:45:54.159Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
