### ISSUE TITLE
"Extension host terminated unexpectedly" in Ubuntu 21.04

### ISSUE THREAD

**Issue by neophiliac** [microsoft/vscode#134177]
Issue Type: <b>Bug</b>

1. Start VS Code
2. Note the dialog that says "Extension host terminated unexpectedly"

The Insiders version does the same thing. 

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:01:43.795Z)
OS version: Linux x64 5.11.0-37-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.30GB (0.47GB free)|
|Process Argv|--unity-launch --crash-reporter-id 48da3c8d-4861-47e2-a22f-f645a4541fc2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797

```

</details>

**Comment by alexdima** [comment]
@neophiliac This might be an issue specific to your environment, as I cannot reproduce. 

Could you please do the following:
1. Install VS Code Insiders (there is a change where logging is better around crashes in Insiders)
2. Reproduce the crash
3. Attach here window logs (`F1 > Developer: Show Logs > Window`)
4. Attach here extension host logs  (`F1 > Developer: Show Logs > Window`)
5. Attach here developer tools logs (`Help > Toggle Developer Tools`)

**Comment by neophiliac** [comment]
(F1 > Developer: Show Logs > Window)
[2021-10-02 11:12:16.302] [renderer1] [info] Starting extension host with pid 237274.
[2021-10-02 11:12:16.748] [renderer1] [error] [Extension Host] (node:237274) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code-insiders --trace-deprecation ...` to show where the warning was created)
[2021-10-02 11:12:18.954] [renderer1] [error] A system error occurred (read ECONNRESET): Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)
[2021-10-02 11:12:18.955] [renderer1] [info] Extension host with pid 237274 exited with code: null, signal: SIGSEGV.
[2021-10-02 11:12:18.957] [renderer1] [error] Extension host (LocalProcess) terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.debug-auto-launch, vscode.git, vscode.github, ms-vscode.js-debug
[2021-10-02 11:12:18.975] [renderer1] [error] Canceled: Canceled
    at Object.f [as canceled] (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1157)
    at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1505:8357
    at Array.forEach (<anonymous>)
    at g.dispose (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1505:8305)
    at $r.dispose (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1552:6049)
    at Gl.stopExtensionHosts (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:149905)
    at Gl._onExtensionHostCrashed (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:150790)
    at Gl._onExtensionHostCrashed (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2924:6711)
    at Gl._onExtensionHostCrashOrExit (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:150546)
    at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:150306
    at l.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at K._onExtHostProcessExit (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:187563)
    at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:182173
    at l.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at ChildProcess.<anonymous> (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:603:28756)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
[2021-10-02 11:12:18.976] [renderer1] [warning] Settings Sync: Accounts are not initialized

(Use `code-insiders --trace-deprecation ...` to show where the warning was created)
Starts, prints "Warning: 'trace-deprecation' is not in the list of known options, but still passed to Electron/Chromium.", draws window, then the window goes away.

I purged code-insiders, deleted the config directory (~/.config/Code - Insiders) and reinstalled. Same behavior; it spawns Electron, which draws its window and immediately dies. Because it's not attached to the original process, `strace` doesn't tell me anything and it dies before I can find the process ID and attach to it. The non-insider vscode launches fine and I still get the "Extension host terminated unexpectedly" dialog.

What's the next step?

**Comment by deepak1556** [comment]
Can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by neophiliac** [comment]
One run produced two dmp files. They're both in this zip.

[chromium-renderer-minidump-.zip](https://github.com/microsoft/vscode/files/7280558/chromium-renderer-minidump-.zip)

**Comment by deepak1556** [comment]
Thanks for the crash log, it indicates `SIGSEGV` in `libjemalloc`. VSCode which is built on top of chromium has its own custom memory allocator https://chromium.googlesource.com/chromium/src/+/HEAD/base/allocator/partition_allocator/PartitionAlloc.md , so it is incorrect that `libjemalloc` is getting loaded in the extension host process. Can you confirm if you have `LD_PRELOAD` set ?

**Comment by neophiliac** [comment]
I just took that preload out and VS Code starts without errors. That used to be a "best practice" for Ruby, which I haven't used in a few years.

Is that part of any error that I could have seen? I have seen a lot of issues about this error and most seem to be closed without resolution. If I had seen "jemalloc" in a stack dump or error message, I would probably have tried removing the preload. 

Thanks for your help!

**Comment by deepak1556** [comment]
> Is that part of any error that I could have seen? I have seen a lot of issues about this error and most seem to be closed without resolution.

Unfortunately it is not straightforward, the devtools log can help with identifying whether it is a native exception or not. After that we have to inspect the crash logs to understand what is happening.

**Comment by alexdima** [comment]
@deepak1556 Should we unset `LD_PRELOAD` when launching extension hosts?

**Comment by deepak1556** [comment]
@alexdima yup it would be good thing to do. Also I think the variable deletion can be moved to `bootstrap-fork` so that all our node child processes benefit from it.

**Comment by alexdima** [comment]
Actually, moving the variable deletion to `bootstrap-fork` would be too late, as `bootstrap-fork` executes inside the spawned child process and the crash might happen even before that JS has a chance to execute.
