### ISSUE TITLE
Unable to install vscode extensions

### ISSUE THREAD

**Issue by Jeffronworks** [microsoft/vscode#134325]
I just recently installed vscode today, however, I'm having issues installing vscode extensions, as I keep getting this error.

[2021-10-02 14:40:59.834] [renderer1] [error] Error: XHR failed
    at XMLHttpRequest.w.onerror (vscode-file://vscode-app/c:/Users/HP/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:24532)
[2021-10-02 14:41:46.136] [renderer1] [error] Error: XHR failed
    at XMLHttpRequest.w.onerror (vscode-file://vscode-app/c:/Users/HP/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:24532)
[2021-10-02 14:41:46.139] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.w.onerror (vscode-file://vscode-app/c:/Users/HP/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:24532)

I've tried changing DNS settings and using flushdns but that didn't seem to help.
![image](https://user-images.githubusercontent.com/37477585/135719222-f0b49e30-0da2-49cd-9400-dec33f4fda72.png)

**Comment by sandy081** [comment]
Can you please retry and provide following:

1. `F1 > Developer: Toggle Shared Process`
2. Click on console tab
3. Retry installing extension
4. Share the errors from the console
