### ISSUE TITLE
debug view stays empty in remote container

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#134488]
Version: 1.61.0-insider
Commit: 71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32
Date: 2021-10-05T01:25:24.263Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic

- clone https://github.com/microsoft/vscode-tools
- open in a dev container
- open the debug view

all empty, no controls to run

![image](https://user-images.githubusercontent.com/6461412/136185542-ef8c89dc-99e3-4e0b-b915-ece6fc12e195.png)

Dev tools shows (not sure if related)
```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: command 'extension.js-debug.clearAutoAttachVariables' not found
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
(anonymous) @ browserSocketFactory.ts:197
fire @ event.ts:577
_fileReader.onload @ browserSocketFactory.ts:81
load (async)
y @ browserSocketFactory.ts:77
create @ browserSocketFactory.ts:181
connect @ browserSocketFactory.ts:243
r @ remoteAgentConnection.ts:191
n @ remoteAgentConnection.ts:232
o @ remoteAgentConnection.ts:309
c @ remoteAgentConnection.ts:351
C @ remoteAgentConnection.ts:421
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
C @ remoteAgentConnection.ts:420
(anonymous) @ remoteExtensionHost.ts:129
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ remoteExtensionHost.ts:105
$r @ extensionHostManager.ts:123
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
p @ extensionHostManager.ts:57
(anonymous) @ abstractExtensionService.ts:618
_startExtensionHosts @ abstractExtensionService.ts:617
_initialize @ abstractExtensionService.ts:514
(anonymous) @ extensionService.ts:107
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1004
(anonymous) @ extensionService.ts:106
Promise.then (async)
Gl @ extensionService.ts:104
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:449
(anonymous) @ workbench.ts:206
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:200
startup @ workbench.ts:132
open @ shared.desktop.main.ts:112
async function (async)
open @ shared.desktop.main.ts:103
w @ desktop.main.ts:40
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:174
i._invokeFactory @ loader.js:1156
i.complete @ loader.js:1166
i._onModuleComplete @ loader.js:1792
i._onModuleComplete @ loader.js:1804
i._resolve @ loader.js:1752
i.defineModule @ loader.js:1395
p @ loader.js:1842
define @ loader.js:1920
(anonymous) @ extensionService.ts:575
(anonymous) @ fake:1
console.ts:137 [Extension Host] stack trace: Error: command 'extension.js-debug.clearAutoAttachVariables' not found    at f._tryExecuteCommand (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1479:3364)    at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1479:3245
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
(anonymous) @ browserSocketFactory.ts:197
fire @ event.ts:577
_fileReader.onload @ browserSocketFactory.ts:81
load (async)
y @ browserSocketFactory.ts:77
create @ browserSocketFactory.ts:181
connect @ browserSocketFactory.ts:243
r @ remoteAgentConnection.ts:191
n @ remoteAgentConnection.ts:232
o @ remoteAgentConnection.ts:309
c @ remoteAgentConnection.ts:351
C @ remoteAgentConnection.ts:421
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
C @ remoteAgentConnection.ts:420
(anonymous) @ remoteExtensionHost.ts:129
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ remoteExtensionHost.ts:105
$r @ extensionHostManager.ts:123
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
p @ extensionHostManager.ts:57
(anonymous) @ abstractExtensionService.ts:618
_startExtensionHosts @ abstractExtensionService.ts:617
_initialize @ abstractExtensionService.ts:514
(anonymous) @ extensionService.ts:107
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1004
(anonymous) @ extensionService.ts:106
Promise.then (async)
Gl @ extensionService.ts:104
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:449
(anonymous) @ workbench.ts:206
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:200
startup @ workbench.ts:132
open @ shared.desktop.main.ts:112
async function (async)
open @ shared.desktop.main.ts:103
w @ desktop.main.ts:40
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:174
i._invokeFactory @ loader.js:1156
i.complete @ loader.js:1166
i._onModuleComplete @ loader.js:1792
i._onModuleComplete @ loader.js:1804
i._resolve @ loader.js:1752
i.defineModule @ loader.js:1395
p @ loader.js:1842
define @ loader.js:1920
(anonymous) @ extensionService.ts:575
(anonymous) @ fake:1
log.ts:301   ERR command 'extension.js-debug.clearAutoAttachVariables' not found: Error: command 'extension.js-debug.clearAutoAttachVariables' not found
    at f._tryExecuteCommand (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1479:3364)
    at vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1479:3245
```

**Comment by aeschli** [comment]
Does not reproduce with a fresh user data dir. Must be extensions related. Investigating...

**Comment by weinand** [comment]
@roblourens this issue is already solved by https://github.com/microsoft/vscode/issues/136450, correct?

**Comment by roblourens** [comment]
Yes thanks
