### ISSUE TITLE
Error: Bad progress location: platformio-ide.projectTasks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#134892]
Couldn't be de-minified but this is fairly high in errors for v1.61.0:

```
Error: Bad progress location: platformio-ide.projectTasks
at o.withProgress (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1714:1048)
at w.$startProgress (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1498:29184)
at g._doInvokeHandler (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1505:13095)
at g._invokeHandler (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1505:12779)
at g._receiveRequest (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1505:11441)
at g._receiveOneMessage (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1505:10119)
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1505:8215
at l.fire (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:69:1712)
at a.fire (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:85:16680)
at c._receiveMessage (vscode-file://vscode-app/out/vs/wor
```

**Comment by Tyriar** [comment]
This still happens in 1.63.2:

https://vscode.dev/github/microsoft/vscode/blob/899d46d82c4c95423fb7e10e68eba52050e30ba3/src/vs/workbench/services/progress/browser/progressService.ts#L63:10

```
Deminified Stack
Error: Bad progress location: platformio-ide.projectTasks
at r.withProgress in src/vs/workbench/services/progress/browser/progressService.ts:63:10
at C.$startProgress in src/vs/workbench/api/browser/mainThreadProgress.ts:56:25
at u._doInvokeHandler in src/vs/workbench/services/extensions/common/rpcProtocol.ts:472:17
at u._invokeHandler in src/vs/workbench/services/extensions/common/rpcProtocol.ts:457:32
at u._receiveRequest in src/vs/workbench/services/extensions/common/rpcProtocol.ts:373:19
at u._receiveOneMessage in src/vs/workbench/services/extensions/common/rpcProtocol.ts:295:10
at out/vs/workbench/workbench.desktop.main.js:1506:8236
at a.fire in src/vs/base/common/event.ts:577:16
at o.fire in src/vs/base/parts/ipc/common/ipc.net.ts:638:19
at d._receiveMessage in src/vs/base/parts/ipc/common/ipc.net.ts:958:23
at out/vs/workbench/workbench.desktop.main.js:85:21746
at a.fire in src/vs/base/common/event.ts:577:16
at s.acceptChunk in src/vs/base/parts/ipc/common/ipc.net.ts:382:21
at out/vs/workbench/workbench.desktop.main.js:85:15589
at Socket.P in src/vs/base/parts/ipc/node/ipc.net.ts:60:4
at Socket.emit in events.js:315:20
at addChunk in internal/streams/readable.js:309:12
at readableAddChunk in internal/streams/readable.js:284:9
at Socket.Readable.push in internal/streams/readable.js:223:10
at Pipe.onStreamRead in internal/stream_base_commons.js:188:23
```
