### ISSUE TITLE
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#135002]
`scripts/test-integration.sh`

```
Terminal
      ✓ sendText immediately after createTerminal should not throw
[78804:1013/165356.037453:INFO:CONSOLE(176)] "Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:176:34)
    at TerminalInstance._register (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:201:32)
    at TerminalInstance._createXterm (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:516:18)", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js (176)
[78804:1013/165356.037497:INFO:CONSOLE(176)] "Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:176:34)
    at TerminalInstance._register (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:201:32)
    at TerminalInstance._createXterm (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:517:18)", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js (176)
[78804:1013/165356.037911:INFO:CONSOLE(176)] "Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:176:34)
    at TerminalInstance._register (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js:201:32)
    at TerminalInstance._createXterm (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:522:41)", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-11.x/out/vs/base/common/lifecycle.js (176)

```

**Comment by bpasero** [comment]
Any update?

**Comment by Tyriar** [comment]
Plan is November

**Comment by bpasero** [comment]
I would appreciate a speedy fix, I am seeing through tons of test output and log files these days in an attempt to make our tests less flaky.

**Comment by Tyriar** [comment]
Doesn't seem to happen when the suite is run in isolation. Problem line is:

https://github.com/Microsoft/vscode/blob/fc9167052f5167d27866f95f2a0420abb58d20b4/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L619

**Comment by Tyriar** [comment]
Included the fix in https://github.com/microsoft/vscode/pull/136522

**Comment by bpasero** [comment]
Thanks 🤝
