### ISSUE TITLE
test automatic language detection works

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#135157]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=138998&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=832

```
  1 failing
 INFO color: #33f   %d failing 1
  1) vscode - automatic language detection
       test automatic language detection works:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by TylerLeonhardt** [comment]
These are skipped... likely forever since I got push back on their existence.
