### ISSUE TITLE
`window.withProgress` targeting `ProgressLocation.SourceControl` fails to display progress badge if SCM view was previously moved into another ViewContainer

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#135215]
Issue Type: <b>Bug</b>

1. Launch Insiders with a fresh user-data-dir
2. Clone [my branch of vscode-extension-samples](https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-ProgressLocation.SourceControl-failure) in which progress-sample has been modified to target `ProgressLocation.SourceControl` rather than `ProgressLocation.Notification`.
3. Build the extension (npm install) and launch it in Extension Host from 'Run and Debug'.
4. In EH Command Palette use the 'Show Progress' command that the extension contributes. Confirm that the clock decoration appears for around 5 seconds on the Source Control icon in Activity Bar.
5. Drag the Source Control icon over the Explorer icon, then onto the Explorer view container when its contents appear.
6. Drag the SOURCE CONTROL header from Explorer view back onto Activity Bar.
7. Re-run the 'Show Progress' command. Observe that the clock decoration fails to appear :bug:
8. To recover the correct behaviour, run the 'View: Reset View Locations' command. Now when you run 'Show Progress' the clock appears for 5 seconds as expected.

VS Code version: Code - Insiders 1.62.0-insider (34eeebdd66033633ac22efd5fab928ae37916168, 2021-10-15T05:16:57.817Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by lszomoru** [comment]
@sbatten, I have taken the changes from your sample fix but they end up with the following error:
```
  ERR Bad progress location: workbench.scm: Error: Bad progress location: workbench.scm
    at handleStringLocation (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/services/progress/browser/progressService.js:46:23)
    at ProgressService.withProgress (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/services/progress/browser/progressService.js:66:28)
    at MainThreadProgress.$startProgress (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadProgress.js:46:35)
    at RPCProtocol._doInvokeHandler (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:399:27)
    at RPCProtocol._invokeHandler (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:384:45)
    at RPCProtocol._receiveRequest (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:311:32)
    at RPCProtocol._receiveOneMessage (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:234:26)
    at vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:115:52
    at Listener.invoke (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/common/event.js:420:27)
    at Emitter.fire (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/common/event.js:559:34)
    at BufferedEmitter.fire (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:478:35)
    at PersistentProtocol._receiveMessage (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:726:45)
    at vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:612:83
    at Listener.invoke (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/common/event.js:420:27)
    at Emitter.fire (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/common/event.js:559:34)
    at ProtocolReader.acceptChunk (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:269:37)
    at vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:236:61
    at Socket.listener (vscode-file://vscode-app/Users/lszomoru/Desktop/github/microsoft/vscode/out/vs/base/parts/ipc/node/ipc.net.js:41:17)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by sbatten** [comment]
@lszomoru branch?

**Comment by lszomoru** [comment]
@sbatten - https://github.com/microsoft/vscode/tree/lszomoru/scm-progress

**Comment by lszomoru** [comment]
Thanks @sbatten! I have tested and checked in the changes.
