### ISSUE TITLE
Search: replaces first search result with a replace term

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#135359]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=139338&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9

```
1) VSCode Smoke Tests (Electron)
       Search
         replaces first search result with a replace term:
     Error: Timeout: get text content '.search-view .messages .message' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:178:19)
      at async Code.waitForTextContent (D:\a\1\s\test\automation\out\code.js:242:16)
      at async Search.waitForResultText (D:\a\1\s\test\automation\out\search.js:91:9)
      at async Context.<anonymous> (out\areas\search\search.test.js:60:13)

```

**Comment by bpasero** [comment]
Another failure showed this image:
![VSCode_Smoke_Tests__Electron__Search_replaces_first_search_result_with_a_replace_term](https://user-images.githubusercontent.com/900690/137866140-597ee77b-0e1c-41c2-9e13-395969adcd98.png)
