### ISSUE TITLE
Debugger: runInTerminal request fails if the path has "ł" character in it

### ISSUE THREAD

**Issue by polak7gt** [microsoft/vscode#135432]
## Environment data

-   VS Code version: 1.60.2
-   Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS and version: Microsoft Windows 10 Pro, 10.0.19043 Build 19043
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): I do not know
-   Relevant/affected Python packages and their versions:
-   Relevant/affected Python-related VS Code extensions and their versions: 
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Debugger should work, when my script is in any folder.

## Actual behaviour

Debugger doesn't work, when my scripts are localized in a folder, which name contains character "ł" (polish letter).

This is what appears in the terminal after pressing F5 (it starts debugging):
```
> PS C:\Users\Szymon\OneDrive - Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie\AGH\Programowanie\python_scripts\MealPlanner>  c:; cd 'c:\Users\Szymon\OneDrive - Akademia Górniczo-Hutnicza im. Stanisawa Staszica w Krakowie\AGH\Programowanie\python_scripts\MealPlanner'; & 'C:\Program Files\Python39\python.exe' 'c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\pythonFiles\lib\python\debugpy\launcher' '8387' '--' 'c:\Users\Szymon\OneDrive - Akademia Górniczo-Hutnicza im. Stanisawa Staszica w Krakowie\AGH\Programowanie\python_scripts\MealPlanner\main.py' 
cd : Cannot find path 'C:\Users\Szymon\OneDrive - Akademia Górniczo-Hutnicza im. Stanisawa Staszica w Krakowie\AGH\Programowanie\python_scripts\MealPlanner' because it does not exist.
At line:1 char:6

> +  c:; cd 'c:\Users\Szymon\OneDrive - Akademia Górniczo-Hutnicza im. St ...

> +      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   

>  + CategoryInfo          : ObjectNotFound: (C:\Users\Szymon...pts\MealPlanner:String) [Set-Location], ItemNotFoundException

    

> + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

> Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Program Files\Python39\lib\runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Python39\lib\runpy.py", line 237, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\Szymon\\OneDrive - Akademia Górniczo-Hutnicza im. Stanisawa Staszica w Krakowie\\AGH\\Programowanie\\python_scripts\\MealPlanner\\main.py'
```
It can be seen, that the correct path is:

> C:\Users\Szymon\OneDrive - Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie\AGH\Programowanie\python_scripts\MealPlanner

However, when debugging starts, the path is changed to:

> c:\Users\Szymon\OneDrive - Akademia Górniczo-Hutnicza im. Stanisawa Staszica w Krakowie\AGH\Programowanie\python_scripts\MealPlanner

One character is missing, the letter 'ł' disappeared from the word 'Stanisława'. I don't know why this is happening.
When I normally run a script without debugging, then everything works fine.

If I run a script from a folder, which does not contain a letter "ł", then debugger works fine.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a folder whose name contains the letter "ł, for example: "Stanisława"
2. Create any python script in this folder
3. Start debugging the script

## Logs
```
<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
Error 2021-10-03 14:32:52: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\Szymon\Desktop\stanisława\MealPlanner\.vscode\settings.json' (Error: Unable to resolve non-existing file 'c:\Users\Szymon\Desktop\stanisława\MealPlanner\.vscode\settings.json')
	at _handleError (c:\Users\Szymon\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:160087)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\out\client\extension.js:9:314351)
	at async p.doesFileNeedToBeFixed (c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\out\client\extension.js:59:823969)
	at async c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\out\client\extension.js:59:823096
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\out\client\extension.js:59:823042)
	at async p.updateTestSettings (c:\Users\Szymon\.vscode\extensions\ms-python.python-2021.9.1246542782\out\client\extension.js:59:822669)] {
  code: 'FileNotFound'
}
Python interpreter path: C:\Program Files\Python39\python.exe
Starting Pylance language server.
> conda --version

</p>
</details>
```

**Comment by polak7gt** [comment]
Thank you for reply.
karthiknadig transferred the issue, hence if I understand correctly, I do not have to do anything else?

**Comment by roblourens** [comment]
Seems to be working for me. Please let me know if you still see this.

**Comment by polak7gt** [comment]
Still have this problem. The version of my VSC is 1.73.

**Comment by int19h** [comment]
As noted earlier, it's quite likely that this requires specific locale settings to repro - e.g. having a non-Unicode codepage active in the terminal which does not have "ł" in it. It did not repro for me using UTF-8.

**Comment by roblourens** [comment]
What do you get if you run `chcp` in a terminal @polak7gt?

**Comment by polak7gt** [comment]
> What do you get if you run `chcp` in a terminal @polak7gt?

It gives me:
Active code page: 850

**Comment by DaveScream** [comment]
@karthiknadig why not planned without any comments?
https://github.com/microsoft/vscode/issues/235573
