### ISSUE TITLE
can't run recursive splices error when renaming a terminal tab

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#135596]
```
[10068:1021/132135.948:INFO:CONSOLE(206)] "%c  ERR color: #f33 Can't run recursive splices.: Error: Can't run recursive splices.
    at ListView.splice (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listView.js:284:23)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listWidget.js:1060:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/event.js:683:23)
    at TerminalTabList.splice (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listWidget.js:1060:32)
    at TerminalTabList.refresh (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:132:18)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:54:75
    at Emitter.fire (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/event.js:435:38)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/event.js:438:41)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:961:46
    at Emitter.fire (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/event.js:435:38)
    at TerminalLabelComputer.refreshLabel (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:2109:40)
    at TerminalInstance.refreshTabLabels (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1517:34)
    at TerminalInstance.rename (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1845:22)
    at Object.onFinish (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalActions.js:832:48)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:333:34
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/functional.js:18:25
    at HTMLInputElement.<anonymous> (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:367:21)
    at InputBox.focus (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/inputbox/inputBox.js:165:24)
    at TerminalTabsRenderer._renderInputBox (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:325:22)
    at TerminalTabsRenderer.renderElement (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:299:22)
    at PipelineRenderer.renderElement (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listWidget.js:815:26)
    at ListView.insertItemInDOM (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listView.js:558:26)
    at ListView._splice (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listView.js:368:26)
    at ListView.splice (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listView.js:288:29)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listWidget.js:1060:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/event.js:683:23)
    at TerminalTabList.splice (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/ui/list/listWidget.js:1060:32)
    at TerminalTabList.refresh (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:132:18)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:54:75
    at Emitter.fire (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/event.js:435:38)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/event.js:438:41)
    at TerminalInstance.refreshTabLabels (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1524:38)
    at TerminalInstance.rename (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1845:22)
    at Object.onFinish (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalActions.js:832:48)
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:333:34
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/common/functional.js:18:25
    at vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/workbench/contrib/terminal/browser/terminalTabsList.js:357:25
    at HTMLInputElement.<anonymous> (vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/base/browser/dom.js:52:20)", source: vscode-file://vscode-app/c:/Users/merogge/repos/vscode/out/vs/platform/log/common/log.js (206)
```

**Comment by jeanp413** [comment]
Created PR #136177 fixing it
