### ISSUE TITLE
Sync with extensions checkbox didnt started

### ISSUE THREAD

**Issue by noi4eg** [microsoft/vscode#135863]
Issue Type: <b>Bug</b>

Try so start syncing with extensions checkbox returns errors even I disable all extensions:

[2021-10-26 18:50:21.329] [settingssync] [info] Settings: Stopped synchronizing settings.
[2021-10-26 18:50:21.329] [settingssync] [info] Keybindings: Stopped synchronizing keybindings.
[2021-10-26 18:50:21.330] [settingssync] [info] Snippets: Stopped synchronizing snippets.
[2021-10-26 18:50:21.332] [settingssync] [info] GlobalState: Stopped synchronizing globalstate.
[2021-10-26 18:52:18.147] [settingssync] [info] Did reset the local sync state.
[2021-10-26 18:52:19.107] [settingssync] [error] TypeError: g.toLowerCase is not a function
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:18901
    at Array.map (<anonymous>)
    at T.getIgnoredExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:18892)
    at ht.generateSyncPreview (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:54211)
    at async ht.doGenerateSyncResourcePreview (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:44762)
[2021-10-26 18:52:19.112] [settingssync] [info] Settings: Stopped synchronizing settings.
[2021-10-26 18:52:19.112] [settingssync] [info] Keybindings: Stopped synchronizing keybindings.
[2021-10-26 18:52:19.113] [settingssync] [info] Snippets: Stopped synchronizing snippets.
[2021-10-26 18:52:19.115] [settingssync] [info] GlobalState: Stopped synchronizing globalstate.
[2021-10-26 18:52:53.645] [settingssync] [info] Did reset the local sync state.
[2021-10-26 18:52:54.687] [settingssync] [error] TypeError: g.toLowerCase is not a function
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:18901
    at Array.map (<anonymous>)
    at T.getIgnoredExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:18892)
    at ht.generateSyncPreview (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:54211)
    at async ht.doGenerateSyncResourcePreview (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:44762)
[2021-10-26 18:52:54.691] [settingssync] [info] Settings: Stopped synchronizing settings.
[2021-10-26 18:52:54.692] [settingssync] [info] Keybindings: Stopped synchronizing keybindings.
[2021-10-26 18:52:54.693] [settingssync] [info] Snippets: Stopped synchronizing snippets.
[2021-10-26 18:52:54.694] [settingssync] [info] GlobalState: Stopped synchronizing globalstate.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.47GB free)|
|Process Argv|--crash-reporter-id b9226ddf-a53b-4482-865a-a32b5c747479|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.2
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by sandy081** [comment]
Are you saying, sync starts if you disable syncing extensions?

**Comment by noi4eg** [comment]
How it looks like
https://user-images.githubusercontent.com/6738874/140592994-c2e60268-16fd-4c7f-a2b5-ee99c53e6f0e.mp4

**Comment by sandy081** [comment]
Got it, can you please uninstall extension by extension and let us know which extension is causing the error?

**Comment by noi4eg** [comment]
https://user-images.githubusercontent.com/6738874/140978022-e0a429db-4f56-443d-9dc0-7b2f077353f5.mp4

I think no one of them )

**Comment by sandy081** [comment]
Hmm, I am guessing you already have some remote state which might be causing this? 

- Turn on settings sync again by disabling syncing extensions
- After settings sync is on, open Settings Sync data view using command `F1 > Settings Sync: Show Synced Data`
- Go to Sync Activity (Remote) view and go to the first Extensions entry and open `extensions.json` file under it
- It opens the diff editor and can you please provide me the content in the right hand side of the editor?

**Comment by noi4eg** [comment]
Uh, maybe I dont understand you, but here is no extension.json
![image](https://user-images.githubusercontent.com/6738874/142361680-b68f12eb-7e0b-4d73-8414-9563df1ee459.png)

**Comment by noi4eg** [comment]
And I find a way to sync on with extension checkbox, but in logs still sync error and sync extensions setting dont work )

`[2021-11-18 11:03:33.575] [settingssync] [error] TypeError: m.toLowerCase is not a function`

**Comment by sandy081** [comment]
> Uh, maybe I dont understand you, but here is no extension.json

It seems, no extensions exist in the remote and seems like you are syncing first time.

can you please try following steps:

- Start VSCode using new user data dir and extensions dir. From CLI (command line) run following
  - code --user-data-dir <path_to_new_dir> --extensions-dir <path_to_new_dir>
- This opens VS Code as a fresh install
- Try settings sync and let me know if it works there?

**Comment by noi4eg** [comment]
With "fresh install" user (w\o any extension, default state) sync work well, but after adding some extensions I get the same error.
zip with logs from new user path VSCode\users\logs
[20211124T212224.zip](https://github.com/microsoft/vscode/files/7597291/20211124T212224.zip)
.

**Comment by noi4eg** [comment]
Im delete all date from AppData\Roaming\Code on both PC, and sync is working now ^^

**Comment by sandy081** [comment]
Glad that sync is working now. 

> but after adding some extensions I get the same error.

May I know which extension is causing it?

**Comment by noi4eg** [comment]
Unfortunately I didnt check.. 
Just install few extensions like python and gitlense. I think problem was not in some specific extension but in "main" config files.
