### ISSUE TITLE
Please add support for  FreeBSD

### ISSUE THREAD

**Issue by mike-pt** [Microsoft/vscode#1359]
I was testing build on FreeBSD but the code.sh script is failing when building electron:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: No asset for version 0.34.5, platform freebsd and arch x64 found
    at /usr/home/miguelc/gitstuff/vscode/node_modules/gulp-atom-electron/src/download.js:79:15
    at /usr/home/miguelc/gitstuff/vscode/node_modules/gulp-atom-electron/node_modules/github-releases/lib/github.js:44:16
    at Request._callback (/usr/home/miguelc/gitstuff/vscode/node_modules/gulp-atom-electron/node_modules/github-releases/lib/github.js:87:16)
    at Request.self.callback (/usr/home/miguelc/gitstuff/vscode/node_modules/gulp-atom-electron/node_modules/github-releases/node_modules/request/request.js:129:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/home/miguelc/gitstuff/vscode/node_modules/gulp-atom-electron/node_modules/github-releases/node_modules/request/request.js:873:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/home/miguelc/gitstuff/vscode/node_modules/gulp-atom-electron/node_modules/github-releases/node_modules/request/request.js:824:12)
./scripts/code.sh: line 32: ./.build/electron/electron: No such file or directory
```

**Comment by mike-pt** [comment]
Hum.. just after posting I realised this:
```
Error: No asset for version 0.34.5, platform freebsd and arch x64 found
    at /usr/home/miguelc/gitstuff/vscode/node_modules/gulp-atom-electron/src/download.js:79:15
```

So I guess this needs to be fixed on gulp-atom-electron first.

**Comment by joaomoreno** [comment]
This needs to be fixed in [atom/electron](https://github.com/atom/electron), which *apparently* needs to ship a FreeBSD release.

Related to joaomoreno/gulp-atom-electron#27

**Comment by joaomoreno** [comment]
Oh, wait. He just wants to build Code in FreeBSD. We should check whether that works...

**Comment by joaomoreno** [comment]
Not supported unfortunately.

**Comment by dch** [comment]
BTW it appears others have this working - https://github.com/prash-wghats/VSCode-For-FreeBSD

**Comment by lbmn** [comment]
Any progress with official support for FreeBSD?

**Comment by tangorri** [comment]
We WANT BSD support, MS used a lot of BSD code for Windows this would be a cool reward.
