### ISSUE TITLE
Remote terminal error: Command $setUnicodeVersion not found

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#136170]
```
  ERR IPC Command $setUnicodeVersion not found: Error: IPC Command $setUnicodeVersion not found
    at RemoteTerminalChannel.call (/home/jeanpierre/gitrepos/vscode/out/vs/server/remoteTerminalChannel.js:96:19)
    at ChannelServer.onPromise (/home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.js:259:35)
    at ChannelServer.onRawMessage (/home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.js:232:33)
    at /home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.js:177:73
    at Emitter.fire (/home/jeanpierre/gitrepos/vscode/out/vs/base/common/event.js:435:38)
    at BufferedEmitter.fire (/home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.net.js:380:35)
    at PersistentProtocol._receiveMessage (/home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.net.js:659:41)
    at /home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.net.js:515:83
    at Emitter.fire (/home/jeanpierre/gitrepos/vscode/out/vs/base/common/event.js:435:38)
    at ProtocolReader.acceptChunk (/home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.net.js:194:37)
    at /home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/common/ipc.net.js:163:61
    at Emitter.fire (/home/jeanpierre/gitrepos/vscode/out/vs/base/common/event.js:435:38)
    at /home/jeanpierre/gitrepos/vscode/out/vs/base/parts/ipc/node/ipc.net.js:423:42
    at afterWrite (internal/streams/writable.js:466:5)
    at onwrite (internal/streams/writable.js:446:7)
    at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
    at Zlib.processCallback (zlib.js:586:8)
```

**Comment by jeanp413** [comment]
Created PR #136171 fixing this
