### ISSUE TITLE
Cannot read property 'tabs' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#136270]
I ran out of sources to open a "test resolver" window:

```
[85272:1102/074053.940748:INFO:CONSOLE(206)] "%c  ERR color: #f33 Cannot read property 'tabs' of undefined: TypeError: Cannot read property 'tabs' of undefined
    at RemoteTerminalChannelClient.setTerminalLayoutInfo (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/common/remoteTerminalChannel.js:199:30)
    at RemoteTerminalService.setTerminalLayoutInfo (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/remoteTerminalService.js:247:48)
    at TerminalService._onWillShutdown (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:539:57)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/terminal/browser/terminalService.js:128:55
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:435:38)
    at NativeLifecycleService.handleWillShutdown (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.js:90:34)
    at EventEmitter.<anonymous> (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.js:47:28)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/platform/log/common/log.js (206)
```

**Comment by Tyriar** [comment]
No longer repro's, @meganrogge fixed this in 5fa4c888e648
