### ISSUE TITLE
VisualStudio Code does not work with network accounts (macOS)

### ISSUE THREAD

**Issue by GreatOmm** [microsoft/vscode#136341]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: macOS 10.14.6 Build 18G9323

Steps to Reproduce:
1. Login to your Mac using a network account (Active Directory)
2. Start Visual Studio Code

The program does exit immediately. If a local user account is used it works without any issues.
Since we want to use Visual Studio Code with our students it is no option to use a local account.

Using Terminal I see an exception:
<pre>
$ cd /Applications/Visual Studio Code.app/Contents/MacOS
$ ./Electron 
2021-11-03 09:38:56.224 Electron[961:25260] isPrefsCreateCacheFromEnabledAndDefaultInputSources - can't find anything from GetInputSourceEnabledPrefs, use defaultASCIIKeyLayoutDict = <CFBasicHash 0x7f9546660fd0 [0x7fff920ac920]>{type = mutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff92117818 [0x7fff920ac920]>{contents = "InputSourceKind"} = <CFString 0x7fff9215cd58 [0x7fff920ac920]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff92148e98 [0x7fff920ac920]>{contents = "KeyboardLayout ID"} = <CFNumber 0x96a95a6dca1959d5 [0x7fff920ac920]>{value = +3, type = kCFNumberSInt64Type}
	9 : <CFString 0x7fff92112518 [0x7fff920ac920]>{contents = "KeyboardLayout Name"} = German
}
GVA info: Successfully connected to the Intel plugin, offline Gen95 
[main 2021-11-03T08:38:56.352Z] Error: listen ENOTSUP: operation not supported on socket /home/USERNAME/Library/Application Support/Code/1.61.2-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1463:5)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:71:31426
    at new Promise (<anonymous>)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:71:31359)
    at J.claimInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:79:4603)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:79:2282
    at invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:29:319)
    at J.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:79:2149)
</pre>

**Comment by GreatOmm** [comment]
The Network home directory is mounted via SMB:
<pre>
$ mount
//USERNAME@DOMAIN/XXX/HomeFolder/XXX/`USERNAME ` on /home/USERNAME (smbfs, nodev, nosuid, automounted, nobrowse, mounted by USERNAME)
</pre>

**Comment by deepak1556** [comment]
This is a limitation of our current desktop application architecture, please use our remote tunnels feature as alternative https://code.visualstudio.com/docs/remote/tunnels#_getting-started
