### ISSUE TITLE
[smoke test fail] Dataloss: verifies that 'hot exit' works for dirty files:

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#136499]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=141562&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725

**Comment by bpasero** [comment]
These are remote tests and I think we fail to get search results via extension host. The remote server log is quite full of errors, not sure if any are related:

[logs-windows-x64-1.zip](https://github.com/microsoft/vscode/files/7490521/logs-windows-x64-1.zip)

E.g.:

```
[2021-11-05 08:03:49.673] [exthost] [error] Activating extension vscode.npm failed due to an error:
[2021-11-05 08:03:49.673] [exthost] [error] Canceled: Canceled
	at Object.i [as canceled] (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1157)
	at d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9064
	at Array.forEach (<anonymous>)
	at t.dispose (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9012)
	at b.terminate (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:694)
	at o (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:32681)
	at Socket.<anonymous> (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:30296)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```

**Comment by bpasero** [comment]
Latest with full logs: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=142197&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9&l=80
