### ISSUE TITLE
Debug configuration lost after computer wake up

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#136747]
Issue Type: <b>Bug</b>

This happens randomly after computer wake up from sleep.
The debug dropdown shows "no configurations", however when clicking "Open "lanuch.json" button, it opens launch.json file with all the settings still available. Adding/changing anything in launch.json do not reflect in debug dropdown. Only relaunching VSCode fixes it.
![image](https://user-images.githubusercontent.com/511517/140924408-d4321567-831d-4bfc-95e3-c90020e8cf64.png)

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (30.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-userscript|adp|1.3.2
autolispext|Aut|1.5.0
vscode-intelephense-client|bme|1.7.1
insert-unicode|bru|0.13.1
bracket-pair-colorizer-2|Coe|0.2.1
autoit|Dam|1.0.6
copy-directory-path|dan|1.0.2
jshint|dba|0.11.0
xml|Dot|2.5.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
LogFileHighlighter|emi|2.13.0
vscode-great-icons|emm|2.1.79
vscode-macros|EXC|1.2.0
php-debug|fel|1.22.0
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.32.0
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
reg|ion|1.0.3
elastic-tabstops-mono|isr|1.0.0
tabsanity|jed|0.0.11
auto-comment-blocks|kev|1.0.1
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-babel|mgm|0.0.35
git-graph|mhu|1.30.0
vscode-edge-devtools|ms-|1.4.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
test-adapter-converter|ms-|0.1.4
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
vscode-auto-scroll|pej|1.0.4
material-product-icons|PKi|1.1.1
vscode-phpunit|rec|2.0.76
format-html-in-php|rif|1.7.0
regexworkbench|ste|2.0.5
tabnine-vscode|Tab|3.4.34
regexhighlighter|Tat|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-backup|Wes|0.0.6
local-history|xyz|1.8.1
json-color-token|yec|1.3.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
When this happens, can you check for errors in the dev tools? (Help > Toggle Developer Tools). Also, do you notice anything else broken/missing in vscode when this is happening/

**Comment by vanowm** [comment]
When this happens the VSCode looses connection to the folder of the opened project (it's on remote computer mapped to a network drive)
```log
21:51:38.835 log.ts:301   ERR [File Watcher (node.js)] Failed to watch z:\www\htdocs\experiments\tcone\.vscode for changes using fs.watch() (Error: ECONNRESET: connection reset by peer, watch, undefined)
21:51:38.837 log.ts:301   ERR [File Watcher (node.js)] Failed to watch z:\www\htdocs\experiments\tcone\.vscode\launch.json for changes using fs.watch() (Error: ECONNRESET: connection reset by peer, watch, undefined)
21:51:38.838 log.ts:301   ERR [Extension Host] Error: ECONNRESET: connection reset by peer, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
21:51:38.838 console.ts:137 [Extension Host] Error: ECONNRESET: connection reset by peer, watch    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
21:51:38.839 log.ts:301   ERR [Extension Host] Error: ECONNRESET: connection reset by peer, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
21:51:38.840 console.ts:137 [Extension Host] Error: ECONNRESET: connection reset by peer, watch    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
21:51:38.841 log.ts:295  WARN [File Watcher (nsfw)] Watcher shutdown because watched path got deleted (path: z:\www\htdocs\experiments\tcone)
21:51:38.849 log.ts:301   ERR [File Watcher (nsfw)] Unexpected error: Service shutdown unexpectedly (EUNKNOWN) (path: z:\www\htdocs\experiments\tcone)
21:51:38.850 log.ts:301   ERR [File Watcher (node.js)] Failed to watch z:\www\htdocs\experiments\tcone\.vscode\settings.json for changes using fs.watch() (Error: ECONNRESET: connection reset by peer, watch, undefined)
21:51:39.653 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
21:51:39.654 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
21:51:39.654 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
21:51:39.672 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
21:51:39.673 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
21:51:39.673 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
06:33:20.502 localProcessExtensionHost.ts:332 Extension Host
06:33:20.503 localProcessExtensionHost.ts:333 Debugger attached.
06:33:21.389 console.ts:137 [Extension Host] Error: getaddrinfo ENOTFOUND default.exp-tas.com
06:33:21.390 console.ts:137 [Extension Host] Error: getaddrinfo ENOTFOUND default.exp-tas.com
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

I've also have seen error message popup about missing `php.exe` after computer woke up from sleep (which is located where VSCode itself is on local hard drive).

**Comment by roblourens** [comment]
That's a useful detail, thanks. Do you know anything about this @bpasero?

**Comment by vanowm** [comment]
Some clarification, VSCode by itself doesn't lose connection to remove folder, Windows itself does (if I have opened remote folder, on wake-up Windows shows popup that folder is not accessible...super annoying, because it shows the popup even if previous popup still opened)
So, VSCode just kills the process, instead of temporary suspending it.

**Comment by bpasero** [comment]
It is possible that in those cases we assume the files got deleted on disk in case the file watcher (here actually node.js itself) reports a delete. This could then bubble up to debug that probably assumes the launch configs are gone. But we have no way to distinguish between a mapped network drive getting disconnected and files getting deleted on disk in those cases. 

To proof that point you could run with `--verbose` and filter to watcher in the console and search for delete events when this happens.

**Comment by vanowm** [comment]
Here is with `--verbose`
```log
01:12:20.897 log.ts:301   ERR [File Watcher (node.js)] Failed to watch z:\www\htdocs\experiments\tcone\.vscode\launch.json for changes using fs.watch() (Error: ECONNRESET: connection reset by peer, watch, undefined)
01:12:20.898 log.ts:301   ERR [File Watcher (node.js)] Failed to watch z:\www\htdocs\experiments\tcone\.vscode\settings.json for changes using fs.watch() (Error: ECONNRESET: connection reset by peer, watch, undefined)
01:13:23.905 log.ts:301   ERR [File Watcher (node.js)] Failed to watch z:\www\htdocs\experiments\tcone\.vscode for changes using fs.watch() (Error: ECONNRESET: connection reset by peer, watch, undefined)
01:13:23.905 log.ts:301   ERR [Extension Host] Error: ECONNRESET: connection reset by peer, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
01:13:23.906 console.ts:137 [Extension Host] Error: ECONNRESET: connection reset by peer, watch    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28) (at FSWatcher.<anonymous> (e:\Program Files\VSCode\resources\app\extensions\git\dist\main.js:2:1017378))
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
01:13:23.906 log.ts:301   ERR [Extension Host] Error: ECONNRESET: connection reset by peer, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
01:13:23.906 console.ts:137 [Extension Host] Error: ECONNRESET: connection reset by peer, watch    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28) (at FSWatcher.<anonymous> (e:\Program Files\VSCode\resources\app\extensions\git\dist\main.js:2:1017378))
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
01:13:23.909 log.ts:295  WARN [File Watcher (nsfw)] Watcher shutdown because watched path got deleted (path: z:\www\htdocs\experiments\tcone)
01:13:23.914 log.ts:277 TRACE [File Watcher (nsfw)]  >> normalized [DELETED] z:\www\htdocs\experiments\tcone
01:13:23.916 log.ts:301   ERR [File Watcher (nsfw)] Unexpected error: Service shutdown unexpectedly (EUNKNOWN) (path: z:\www\htdocs\experiments\tcone)
01:13:24.013 log.ts:277 TRACE Error while resolving configuration file 'file:///z%3A/www/htdocs/experiments/tcone/.vscode/settings.json': Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json')
01:13:24.014 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
01:13:24.014 log.ts:277 TRACE Error while resolving configuration file 'file:///z%3A/www/htdocs/experiments/tcone/.vscode/launch.json': Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json')
01:13:24.015 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
01:13:24.016 log.ts:277 TRACE Error while resolving configuration file 'file:///z%3A/www/htdocs/experiments/tcone/.vscode/tasks.json': Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json')
01:13:24.016 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
01:13:24.017 log.ts:283 DEBUG Configuration keys changed in WORKSPACE target editor.tabSize intelephense.environment.documentRoot launch.version launch.configurations
01:13:24.033 log.ts:277 TRACE Error while resolving configuration file 'file:///z%3A/www/htdocs/experiments/tcone/.vscode/settings.json': Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json')
01:13:24.033 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\settings.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\settings.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
01:13:24.034 log.ts:277 TRACE Error while resolving configuration file 'file:///z%3A/www/htdocs/experiments/tcone/.vscode/tasks.json': Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json')
01:13:24.034 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\tasks.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
01:13:24.034 log.ts:277 TRACE Error while resolving configuration file 'file:///z%3A/www/htdocs/experiments/tcone/.vscode/launch.json': Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json')
01:13:24.034 log.ts:301   ERR Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json'): Error: Unable to read file 'z:\www\htdocs\experiments\tcone\.vscode\launch.json' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'z:\www\htdocs\experiments\tcone\.vscode\launch.json')
    at yi.doReadFileStream (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at async yi.doReadFile (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/e:/Program%20Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
01:13:24.070 log.ts:277 TRACE CommandService#executeCommand setContext
01:13:24.072 log.ts:277 TRACE CommandService#executeCommand setContext
01:13:34.629 log.ts:277 TRACE [File Watcher (node.js)] [CHANGED] e:\Program Files\VSCode\data\user-data\User\globalStorage
01:13:34.830 log.ts:277 TRACE [File Watcher (node.js)] >> normalized [CHANGED] e:\Program Files\VSCode\data\user-data\User\globalStorage
01:13:34.830 log.ts:283 DEBUG User data changed
```

at 01:12:20.897 I've disconnected network on remote computer, 1 minute later VSCode removed debug configuration for the project. Perhaps there is a way check if a file not available (deleted) or entire drive is unreachable?

**Comment by bpasero** [comment]
This sounds a bit like https://github.com/microsoft/vscode/issues/136673 to me which I recently fixed for insiders.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by vanowm** [comment]
@bpasero I've had VSCode insiders running for 1 week and debugger never lost it's configuration.
Thank you.
