### ISSUE TITLE
Unable to resolve filesystem provider with relative file path vscode-notebook

### ISSUE THREAD

**Issue by jdrake** [microsoft/vscode#136784]
## Environment data

-   VS Code version: 1.62.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1001414422
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: MacOS Catalina 10.15.7
-   Python and/or Anaconda version: Python 3.6.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local

## Expected behaviour

Close an unsaved editor of a .ipynb file

## Actual behaviour

```
Unable to open '***.ipynb': Unable to resolve filesystem provider with relative file path 'vscode-notebook:file:///Users/jdrake/***/***.ipynb'.
```

## Steps to reproduce:

Unclear how the editor got in this situation. The .ipynb file exists and can be opened in a separate editor.

## Logs

No Jupyter logs. Error shows up in Log (Window).

<details>

<summary>Output for <code>Log (Window)</code> in the <code>Output</code> panel </summary>

<p>

```
[2021-11-09 12:54:01.741] [renderer1] [critical] FAILED to destory notebook {"fileOperationResult":8}
[2021-11-09 12:54:01.745] [renderer1] [error] Error: Unable to resolve filesystem provider with relative file path 'vscode-notebook:file:///Users/jdrake/talos/notebooks/data-pipeline/glue.ipynb'
    at yi.withProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:21816)
    at yi.withReadProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:22115)
    at yi.readFileStream (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:26966)
    at Ds.resolveFromFile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2388:56459)
    at Ds.doResolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2388:55031)
    at async f.doResolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2388:72343)
    at async sr.load (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2379:4655)
    at async u.createReferencedObject (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2388:81781)
    at async c.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2388:84080)
    at async wn.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1936:816)
    at async Ss.setInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1938:75643)
    at async n.doSetInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2342:34632)
    at async n.doOpenEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2342:33032)
    at async n.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2342:32680)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2544:16967
    at async Bi.doHandleDirtyClosing (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2544:22528)
    at async Bi.handleDirtyClosing (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2544:21883)
    at async Bi.closeEditors (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2544:23125)
    at async Promise.all (index 0)
```

</p>
</details>

**Comment by jmugan** [comment]
I'm getting this as well. Ubuntu and file extension .ipynb

**Comment by fridiculous** [comment]
I'm seeing this issue as well

**Comment by fridiculous** [comment]
Ok I was able to resolve the issue by manually overriding the sqllite database specific record for in the workspace.


Using macOS, within `/Users/username/Library/Application Support/Code/User/workspaceStorage`, under the relevant workspace folder, open `state.vscdb` in sqllite.

Under the key, `memento/workbench.editors.files.textFileEditor` you'll have a value of 

```json
{
    "editorpart.state": {
        "serializedGrid": {
            "root": {
                "type": "branch",
                "data": [
                    {
                        "type": "leaf",
                        "data": {
                            "id": 0,
                            "editors": [
                                {
                                    "id": "workbench.input.notebook",
                                    "value": "{\"resource\":{\"$mid\":1,\"fsPath\":\"file:///Users/username/my_script.ipynb\",\"external\":\"vscode-notebook:file%3A///Users/username/my_script.ipynb\",\"path\":\"file:///Users/username/my_script.ipynb\",\"scheme\":\"vscode-notebook\"},\"viewType\":\"jupyter-notebook\",\"options\":{\"startDirty\":true}}"
                                }
                            ],
                            "mru": [
                                0
                            ]
                        },
                        "size": 955
                    }
                ],
                "size": 1411
            },
            "orientation": 0,
            "width": 1411,
            "height": 955
        },
        "activeGroup": 0,
        "mostRecentActiveGroups": [
            0
        ]
    }
}
```  

The problematic file `file:///Users/username/my_script.ipynb` is the first item in the editors list.  If you re-write that 1 item and delete mru field, VS Code will open next time without the un-closable file.

**Comment by jdrake** [comment]
@fridiculous That worked for me! Awesome, thank you.
