### ISSUE TITLE
Smoke test: git smoke test

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#136737]
```
git smoke test
[File Watcher (parcel)] Unexpected error: inotify_add_watch failed: No such file or directory (EUNKNOWN) (path: /tmp/tmp.LmnxCc3K5P)
[File Watcher (parcel)] restarting watcher after error: inotify_add_watch failed: No such file or directory
[4069:1109/052240.663851:INFO:CONSOLE(29)] "%c WARN color: #993 SharedProcess: createWorker found an existing worker that will be terminated (window: 1, moduleId: vs/platform/files/node/watcher/parcel/watcherApp)", source: vscode-file://vscode-app/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[4069:1109/052240.669782:INFO:CONSOLE(29)] "%c INFO color: #33f Worker process with pid 4198 terminated normally (type: watcherServiceParcelSharedProcess, window: 1).", source: vscode-file://vscode-app/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[4069:1109/052240.676925:INFO:CONSOLE(29)] "%c INFO color: #33f Starting worker process with pid 4235 (type: watcherServiceParcelSharedProcess, window: 1).", source: vscode-file://vscode-app/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
RunAutomaticTasks: Trying to run tasks.
RunAutomaticTasks: Checking if automatic tasks should run.
Error while registering log channel file:///__w/1/s/.build/logs/integration-tests/renderer1.log Timed out while waiting for file to be created
    1) "before all" hook for "reflects working tree changes"
  23 passing (1m)
  1 failing
  1) git smoke test
       "before all" hook for "reflects working tree changes":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/git/out/test/smoke.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

```

**Comment by bpasero** [comment]
These steps sometimes fail to succeed:

https://github.com/microsoft/vscode/blob/025fcaf6114e0e56f1975a5937c9f09ca7f0406f/extensions/git/src/test/smoke.test.ts#L42-L66

Specifically the line: `await eventToPromise(git.onDidOpenRepository)`

Since we first create all the files and then activate git, a repository should eventually open.

**Comment by joaomoreno** [comment]
@bpasero Given that you have seen this locally and/or seen it in CI, what's the workbench state when this happens? Specifically, a screenshot would be awesome.

**Comment by joaomoreno** [comment]
Oh this isn't Playright. It's the git smoke tests. Which are extension tests.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/136348#issue-1043482531 is an interesting one because I see no error message from Parcel.
