### ISSUE TITLE
Installing remote server via scp doesn't work anymore

### ISSUE THREAD

**Issue by ponchofiesta** [microsoft/vscode#136775]
- VSCode Version: 1.62.0
- Local OS Version: Windows 10 Enterprise 20H2
- Remote OS Version: Kubuntu 20.04 / CentOS 7
- Remote Extension/Connection Type: SSH
- Logs:
```
[10:44:16.026] Log Level: 2
[10:44:16.027] remote-ssh@0.66.0
[10:44:16.027] win32 x64
[10:44:16.038] SSH Resolver called for "ssh-remote+ubuntu-vm", attempt 1
[10:44:16.038] "remote.SSH.useLocalServer": false
[10:44:16.038] "remote.SSH.showLoginTerminal": false
[10:44:16.038] "remote.SSH.remotePlatform": {"XXX":"linux","XXX":"linux","XXX":"linux","ubuntu-vm":"linux","XXX":"linux","XXX":"linux","XXX":"linux"}
[10:44:16.038] "remote.SSH.path": C:\Users\XXX\bin\ssh.exe
[10:44:16.038] "remote.SSH.configFile": undefined
[10:44:16.039] "remote.SSH.useFlock": true
[10:44:16.039] "remote.SSH.lockfilesInTmp": false
[10:44:16.039] "remote.SSH.localServerDownload": always
[10:44:16.039] "remote.SSH.remoteServerListenOnSocket": false
[10:44:16.039] "remote.SSH.showLoginTerminal": false
[10:44:16.039] "remote.SSH.defaultExtensions": []
[10:44:16.039] "remote.SSH.loglevel": 2
[10:44:16.039] SSH Resolver called for host: ubuntu-vm
[10:44:16.040] Setting up SSH remote "ubuntu-vm"
[10:44:16.044] Using commit id "b3318bc0524af3d74034b8bb8a64df0ccf35549a" and quality "stable" for server
[10:44:16.047] Install and start server if needed
[10:44:16.050] Checking ssh with "C:\Users\XXX\bin\ssh.exe -V"
[10:44:16.123] > OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

[10:44:16.129] Running script with connection command: "C:\Users\XXX\bin\ssh.exe" -T -D 56333 "ubuntu-vm" bash
[10:44:16.131] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:44:17.517] > ]0;C:\WINDOWS\System32\cmd.exe
[10:44:17.517] Got some output, clearing connection timeout
[10:44:18.424] > agent key RSA SHA256:XXX returned incorr
> ect signature type
[10:44:18.788] > agent key RSA SHA256:XXX returned incorrect signature typ
> e
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[10:44:19.556] > ca08f70aa8fa: running
[10:44:19.605] > Acquiring lock on /home/XXX/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/vscod
> e-remote-lock.XXX.b3318bc0524af3d74034b8bb8a64df0ccf35549a
[10:44:19.612] > Found old VS Code install 83bd43bc519d15e50c4272c6cf5c1479df196a4d, attempting to clean up
[10:44:19.621] > Deleting old install from /home/XXX/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a
> 4d
[10:44:19.721] > Deleting old log file from /home/XXX/.vscode-server/.83bd43bc519d15e50c4272c6cf5c1479df196a4d
> .log
[10:44:19.727] > Installing to /home/XXX/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a...
> Trigger local server download
> ca08f70aa8fa:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/XXX/.vscode-server/bin/==
> destFolder2==b3318bc0524af3d74034b8bb8a64df0ccf35549a==
> ca08f70aa8fa:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/XXX/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/vscode-scp-
> done.flag and vscode-server.tar.gz to exist
> 
[10:44:19.727] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/XXX/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a"}
[10:44:19.727] Downloading VS Code server locally...
[10:44:21.735] Resolver error: Error: XHR failed
    at XMLHttpRequest.C.onerror (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:24735)
[10:44:21.738] ------
```

Steps to Reproduce:

1. Open SSH Connection to remote server (tested Ubuntu 20.04 and CentOS 7 - both worked before)
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by tanhakabir** [comment]
@alexdima do you have an idea what could cause this error in the resolver?

```
Resolver error: Error: XHR failed
    at XMLHttpRequest.C.onerror (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:24735)
```

**Comment by alexdima** [comment]
@tanhakabir It looks to me that the SSH resolver decides to download the vscode server locally and then fails to download it. I don't know why the download would fail, maybe the internet got briefly disconnected while downloading 🤷 . But this is not a core remote problem, it is the SSH resolver extension that downloads the vscode server. Maybe it should retry a few times before giving up?

**Comment by ponchofiesta** [comment]
@alexdima All of my servers do not have internet access. I did set `"remote.SSH.localServerDownload": always` to enforce scp download.

**Comment by alexdima** [comment]
@ponchofiesta yes, the log shows this:
```
[10:44:19.727] Downloading VS Code server locally...
[10:44:21.735] Resolver error: Error: XHR failed
    at XMLHttpRequest.C.onerror (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:24735)
[10:44:21.738] ------
```

But 2 seconds later there is an `XHR failed` error, which I presume means that the download failed. I am sorry, but I don't know what might be causing the download to fail. cc @roblourens @tanhakabir perhaps to log more info or retry downloading in case of failure.
