### ISSUE TITLE
Smoke test: install and enable vscode-smoketest-check extension

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#136833]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=142153&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d&l=80

```
1) VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: get element 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[data-extension-id="ms-vscode.vscode-smoketest-check"]' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:178:19)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:262:16)
      at async Extensions.searchForExtension (/Users/runner/work/1/s/test/automation/out/extensions.js:28:9)
      at async Extensions.installExtension (/Users/runner/work/1/s/test/automation/out/extensions.js:38:9)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:19:13)

```

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/141070371-32802967-2589-4fcd-9288-d6cd374f74dc.png)

**Comment by sandy081** [comment]
There seems to be network connectivity issue on the machine this was run.
