### ISSUE TITLE
Buffer deprecated warning

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#136874]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.63.0-insider (user setup)
Commit: a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8
Date: 2021-11-08T05:14:49.440Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:
1. Run VS Code or VS Code Insiders with the flag --disable-extensions
2. Observe developer tools console

Expected: No error messages or warnings

Actual: `(node:22768) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use Code - Insiders --trace-deprecation ... to show where the warning was created).`

Running `code-insiders --trace-deprecation` results in this message: `Warning: 'trace-deprecation' is not in the list of known options, but still passed to Electron/Chromium.`

According to one of Live Share's commenters, this is where the issue may be coming from: https://github.com/MicrosoftDocs/live-share/issues/3331#issuecomment-912250615

![image](https://user-images.githubusercontent.com/22576531/141138182-fb2f1d09-5882-4dc7-8ab0-df86d0a55b1e.png)

**Comment by MrNossiom** [comment]
Try to pass --trace-deprecation as an `NODE_OPTION`. Like this: 

`$env:NODE_ENV="--trace-deprecation" code-insiders`

I saw you were on Windows, but for Linux it is just `NODE_OPTIONS="--trace-deprecation" code-insiders`

**Comment by alyssajotice** [comment]
```
$ set NODE_ENV="--trace-deprecation" code-insiders
$ NODE_ENV="--trace-deprecation" code-insiders
$ set NODE_OPTION="--trace-deprecation" code-insiders
$ code-insiders --trace-deprecation
Warning: 'trace-deprecation' is not in the list of known options, but still passed to Electron/Chromium.
```
Is there something else I should try?

**Comment by MrNossiom** [comment]
Well if any of these don't work, idk.

**Comment by bpasero** [comment]
Probably https://github.com/microsoft/vscode/issues/82524

**Comment by sandy081** [comment]
I do not think it is related to #82524 because in the other, warning is shown only while installing the extension.

**Comment by bpasero** [comment]
Adding `process.traceDeprecation = true;` to the beginning of `exensionHostProcess` reveals this:

```
ERR [Extension Host] (node:3777) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:194:11)
    at new Buffer (buffer.js:281:3)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/ftp/lib/connection.js:52:17)
    at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1316)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/get-uri/dist/ftp.js:16:31)
    at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1316)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/get-uri/dist/index.js:10:31)
    at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1316)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/agent.js:17:35)
    at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1316)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:40:30)
    at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1316)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at e.load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1723)
    at e.load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:10695)
    at d (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:10300)
    at i._loadModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:10430)
    at i._resolve (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:452)
    at i.defineModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:6142)
    at v (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:1702)
    at g (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:2557)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:58294)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:116:32793)
    at e._createAndEvalScript (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:2601)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:2240
    at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:4192)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:4386
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

**Comment by bpasero** [comment]
@chrmarti maybe we can fix this in our `vscode-proxy-agent`

**Comment by chrmarti** [comment]
Also tracked as https://github.com/TooTallNate/node-get-uri/issues/18 and https://github.com/mscdex/node-ftp/issues/255.

**Comment by kanlukasz** [comment]
Some time ago your bot closed my issue about this (I still don't know why ...)
Here ---> https://github.com/microsoft/vscode/issues/123180

**Comment by Angelo-yu** [comment]
[error] [Extension Host] (node:61654) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)

I have also encountered the same problem, I am using a Macbook Pro with M1 chip, the system is the latest macOS Monterey 12.0.1 (21A559) VS Code version 1.62.3, I tried to delete all the extensions, but the problem still exists.
My English is not very good, I used the translation tool to translate the above text, if there is inaccurate expression, please forgive me!

**Comment by Angelo-yu** [comment]
![截屏2021-11-24 14 52 59](https://user-images.githubusercontent.com/52949307/143189615-92d0120d-33a1-4be0-a5bb-3ef3d915d9ba.png)

**Comment by jasonwilliams** [comment]
> Also tracked as [TooTallNate/node-get-uri#18](https://github.com/TooTallNate/node-get-uri/issues/18) and [mscdex/node-ftp#255](https://github.com/mscdex/node-ftp/issues/255).

Looks like that node-ftp project is dead. Despite there being a fix and PR, nothing has been merged since 2015

**Comment by chrmarti** [comment]
Looking closer, we might not actually need `node-get-uri`. I'll investigate.

**Comment by bpasero** [comment]
👏 👏 👏
