### ISSUE TITLE
v1.62.0 v1.62.1 cannot install extension from remote ssh

### ISSUE THREAD

**Issue by copdips** [microsoft/vscode#136859]
- VS Code Version: v1.62.0 v1.62.1
- OS Version: Windows 10 then remote ssh to Redhat v7.5

Once I downgrade the VSCode to previous versions, e.g. v1.60 or v1.61, the extension installation works again. I tried to reboot my server, same issue.

BTW the way, the extension installation from Windows works always for all the VSCode versions, only from remote ssh it sucks for new versions. I dont think it shoul be a network issue because old verions work well.

Steps to Reproduce:

1. install or update an extension when VSCode is in remote ssh mode

Error:

```bash
[2021-11-10 14:11:51.602] [renderer1] [error] ["Error: getaddrinfo ENOTFOUND golang.gallery.vsassets.io","    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)"]
[2021-11-10 14:11:51.637] [renderer1] [error] getaddrinfo ENOTFOUND golang.gallery.vsassets.io: Error: getaddrinfo ENOTFOUND golang.gallery.vsassets.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/136710
