### ISSUE TITLE
Typescript files containing invalid code crash the TS server and prevent it from loading upon restart.

### ISSUE THREAD

**Issue by barca-reddit** [microsoft/vscode#136996]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: Ubuntu 20.04

Additional info:

```
Version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:56:50.217Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-90-generic
```

Steps to Reproduce:

I have tested this both on my daily Linux system, and on a separate clean install on a virtual machine.

1. Download VSCode.
2. Install the `.deb` package either by using `apt`, or alternatively just install VSCode with snap. The but is reproducible either way.
3. Install TypeScript globally via `npm`
4. Make a directory and create two files inside - `crash.ts` and `empty.ts`, then Open that folder with VSCode.

```shell
wget https://az764295.vo.msecnd.net/stable/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/code_1.62.1-1636111026_amd64.deb
apt install ./code_1.62.1-1636111026_amd64.deb
npm i -g typescript
mkdir typescript-bug && cd typescript-bug && touch crash.ts empty.ts && code .
```

5. Open both `crash.ts` and `empty.ts` in two separate tabs inside the editor, then paste the following text inside `crash.ts`:

```
Property 'toUppercase' does not exist on type 'string'
```

![](https://i.imgur.com/knf9oBE.png)

6. To reproduce crashing the TS Server, simply click on the `empty.ts` tab to switch to it, you don't have to necessarily save `crash.ts` before doing so.

![](https://i.imgur.com/8bSHkuy.png)

7. Finally, to reproduce the server crashing upon launch, simply save the `crash.ts` file, then reload VSCode.

![](https://thumbs.gfycat.com/FortunateHastyAoudad-size_restricted.gif)

---

Error log:

```
Info 0    [22:56:17.513] Starting TS Server
Info 1    [22:56:17.513] Version: 4.4.3
Info 2    [22:56:17.513] Arguments: /usr/share/code/code /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/41cb87bc88cc60f7d51f/tscancellation-bc34ad5d28180b17cbaf.tmp* --logVerbosity verbose --logFile /home/tsc-vbox/.config/Code/logs/20211111T225448/exthost1/vscode.typescript-language-features/tsserver-log-5ZFcPh/tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /usr/share/code/resources/app/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --validateDefaultNpmLocation
Info 3    [22:56:17.513] Platform: linux NodeVersion: 14 CaseSensitive: true
Info 4    [22:56:17.513] ServerMode: 1 syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [22:56:17.572] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true,"includePackageJsonAutoImports":"auto"},"watchOptions":{}}}
Info 6    [22:56:17.572] Host information vscode
Info 7    [22:56:17.573] Host watch options changed to undefined, it will be take effect for next watches.
Info 8    [22:56:17.573] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 9    [22:56:17.574] 0::configure: async elapsed time (in milliseconds) 1.3780
Info 10   [22:56:17.574] request:
    {"seq":1,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/home/tsc-vbox/Desktop/typescript-bug/crash.ts","fileContent":"Property 'toUppercase' does not exist on type 'string'","projectRootPath":"/home/tsc-vbox/Desktop/typescript-bug","scriptKindName":"TS"},{"file":"/home/tsc-vbox/Desktop/typescript-bug/empty.ts","fileContent":"","projectRootPath":"/home/tsc-vbox/Desktop/typescript-bug","scriptKindName":"TS"}]}}
Info 11   [22:56:17.576] Loading global plugin typescript-vscode-sh-plugin
Info 12   [22:56:17.576] Enabling plugin typescript-vscode-sh-plugin from candidate paths: /usr/share/code/resources/app/extensions/typescript-language-features,/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
Info 13   [22:56:17.576] Loading typescript-vscode-sh-plugin from /usr/share/code/resources/app/extensions/typescript-language-features (resolved to /usr/share/code/resources/app/extensions/typescript-language-features/node_modules)
Info 14   [22:56:17.589] typescript-vscode-sh-plugin active for version < 4.2 and JS/JSX files. Current version : 4.4.3
Info 15   [22:56:17.589] Intercepting getEncodedSemanticClassifications and getEncodedSyntacticClassifications.
Info 16   [22:56:17.589] Plugin validation succeeded
Info 17   [22:56:17.590] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Err 18    [22:56:17.739] Exception on executing command {"seq":1,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/home/tsc-vbox/Desktop/typescript-bug/crash.ts","fileContent":"Property 'toUppercase' does not exist on type 'string'","projectRootPath":"/home/tsc-vbox/Desktop/typescript-bug","scriptKindName":"TS"},{"file":"/home/tsc-vbox/Desktop/typescript-bug/empty.ts","fileContent":"","projectRootPath":"/home/tsc-vbox/Desktop/typescript-bug","scriptKindName":"TS"}]}}:

    Debug Failure.

    Error: Debug Failure.
        at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19293:89
        at String.replace (<anonymous>)
        at formatStringFromArgs (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19293:21)
        at Object.createDetachedDiagnostic (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19309:20)
        at parseErrorAtPosition (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30704:42)
        at parseErrorAt (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30711:13)
        at parseErrorAtCurrentToken (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30698:13)
        at parseErrorForInvalidName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30936:17)
        at parseErrorForMissingSemicolonAfter (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30908:21)
        at parseExpressionOrLabeledStatement (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:34798:21)
        at parseStatement (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:35035:20)
        at parseListElement (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31487:20)
        at parseList (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31472:31)
        at parseSourceFileWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30440:30)
        at Object.parseSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30274:26)
        at Object.createSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30072:29)
        at Object.createLanguageServiceSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156325:29)
        at acquireOrUpdateDocument (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:129083:37)
        at Object.acquireDocumentWithKey (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:129049:20)
        at getOrCreateSourceFileByPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156728:41)
        at Object.getOrCreateSourceFile [as getSourceFile] (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156675:24)
        at findSourceFileWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:113090:29)
        at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:113000:26)
        at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112952:85
        at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112919:34)
        at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112952:13)
        at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112759:13)
        at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:111624:67
        at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:194:30)
        at Object.createProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:111624:16)
        at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156605:26)
        at Proxy.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156737:13)
        at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161733:53)
        at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161662:42)
        at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:163828:25)
        at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165517:26)
        at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165791:97
        at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:519:25)
        at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165791:41)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:166949:46)
        at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:88
        at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168871:28)
        at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:33)
        at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168906:35)
        at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171511:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 19   [22:56:17.740] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":1,"success":false,"message":"Error processing request. Debug Failure.\nError: Debug Failure.\n    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19293:89\n    at String.replace (<anonymous>)\n    at formatStringFromArgs (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19293:21)\n    at Object.createDetachedDiagnostic (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19309:20)\n    at parseErrorAtPosition (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30704:42)\n    at parseErrorAt (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30711:13)\n    at parseErrorAtCurrentToken (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30698:13)\n    at parseErrorForInvalidName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30936:17)\n    at parseErrorForMissingSemicolonAfter (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30908:21)\n    at parseExpressionOrLabeledStatement (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:34798:21)\n    at parseStatement (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:35035:20)\n    at parseListElement (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31487:20)\n    at parseList (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31472:31)\n    at parseSourceFileWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30440:30)\n    at Object.parseSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30274:26)\n    at Object.createSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30072:29)\n    at Object.createLanguageServiceSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156325:29)\n    at acquireOrUpdateDocument (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:129083:37)\n    at Object.acquireDocumentWithKey (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:129049:20)\n    at getOrCreateSourceFileByPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156728:41)\n    at Object.getOrCreateSourceFile [as getSourceFile] (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156675:24)\n    at findSourceFileWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:113090:29)\n    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:113000:26)\n    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112952:85\n    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112919:34)\n    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112952:13)\n    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:112759:13)\n    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:111624:67\n    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:194:30)\n    at Object.createProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:111624:16)\n    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156605:26)\n    at Proxy.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:156737:13)\n    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161733:53)\n    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161662:42)\n    at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:163828:25)\n    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165517:26)\n    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165791:97\n    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:519:25)\n    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165791:41)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:166949:46)\n    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:88\n    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168871:28)\n    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:33)\n    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168906:35)\n    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171511:31)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:337:10)\n    at Interface._normalWrite (readline.js:482:12)\n    at Socket.ondata (readline.js:194:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}
```

---

Now a logical question one might ask here is, why on earth would someone save a file with such weird contents that aren't even valid TypeScript code. The answer here is very simple, by accident. As a matter of fact, this exact sentence that breaks the TS server - `Property 'toUppercase' does not exist on type 'string'. Did you mean 'toUpperCase'?` is taken directly from the [TypeScript docs website](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html).

![](https://i.imgur.com/o2Z9aWN.png)

The code box lets you select everything, and that includes the error message, which ironically caused the problem here as well. I do not know exactly why that exact text causes these issues, but for example the following code, even though is still invalid does not cause the same crashes:

```typescript
names.forEach((s) => {
  Property 'toUppercase' does not exist on type // <= this is fine
  Lorem ipsum dolor sit amet, consectetur adipiscing elit... // <= and so is this
});
```

**EDIT**: I forgot to mention that the problem can be reproduced on Windows 10 as well, using the same steps as the ones described above.

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that fix the issue?

**Comment by barca-reddit** [comment]
Hey @mjbvz, thank you for reaching out. Yes indeed, it does appear that this makes the issue go away, tried reproducing this with the extension installed and the TS server doesn't crash on launch or when switching editor tabs.

May I ask you though, what is the reason for that? Is it because these Nightly builds are using an upcoming version of TypeScript (I am seeing that it's using `4.6.0-dev.....`) where this bug is already fixed, or is it because of something else and I have to use this extension as a permanent solution for this problem?

Forgive my ignorance and if I am mistaken about something, but if I'm understanding correctly the Nightly builds are using all the latest and greatest, while the downside being potential bugs, where I would prefer stable builds, at least in the long-term.
