### ISSUE TITLE
help,  vscode-ripgrep: Command failed.

### ISSUE THREAD

**Issue by lichangwei123** [microsoft/vscode#136935]
[4/4] Building fresh packages...
[11/19] ⠈ vscode-ripgrep
[16/19] ⠈ vscode-windows-registry
[17/19] ⠁ windows-foreground-love
[18/19] ⠁ windows-mutex
error D:\site\xinchengkeji\vscode\node_modules\vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: D:\site\xinchengkeji\vscode\node_modules\vscode-ripgrep
Output:
Finding release for v13.0.0-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-2
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.169.195.247:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',

**Comment by lichangwei123** [comment]
I have the proxy on, Can you help me see what I can do

**Comment by roblourens** [comment]
Can you access that `api.github.com...` URL through your proxy?

**Comment by lichangwei123** [comment]
> Can you access that `api.github.com...` URL through your proxy? Do you have the HTTP_PROXY environment vars set?

can't access that `api.github.com...` URL through my proxy, How to set HTTP_PROXY environment

**Comment by roblourens** [comment]
> can't access that api.github.com... URL through my proxy

I'm not sure what the problem would be but I can't help you with your proxy, sorry
