### ISSUE TITLE
vscode web showing error/notification "create workspace"

### ISSUE THREAD

**Issue by ashwin31** [microsoft/vscode#136959]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0-dev
- OS Version: ubuntu 20.04

Steps to Reproduce:

1. I followed https://github.com/Microsoft/vscode/wiki/How-to-Contribute#run to run vscode in my browser 
2. git clone https://github.com/microsoft/vscode.git .
3. sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev python-is-python3
4. yarn
5. yarn watch
6. yarn watch-web
5. yarn web
everything is good except that I am not able add extensions or use terminal. 
The notification message says that I need to create workspace.
Can anyone tell me how to create and add workspace for vscode to run in my browser

**Comment by ashwin31** [comment]
![Screenshot from 2021-11-11 19-18-12](https://user-images.githubusercontent.com/365610/141312225-de6f3696-5114-442e-8197-2c0e87e9f3d0.png)

**Comment by bpasero** [comment]
The `yarn web` command brings up a very lightweight web instance that does not support terminals. If you use `resources/server/bin-dev/server.sh` instead and click on the link that is printed, you get a more functional web instance.

//cc @aeschli

**Comment by ashwin31** [comment]
@bpasero do I need to run any other commands after installing packages with yarn and running the command you told?

Here is the error I got
➜  vscode git:(main) resources/server/bin-dev/server.sh
yarn run v1.22.15
$ node build/lib/builtInExtensions.js
[19:42:52] Syncronizing built-in extensions...
[19:42:52] You can manage built-in extensions with the --builtin flag
[19:42:52] Downloading extension: ms-vscode.references-view@0.0.81 ...
[19:42:52] Downloading extension: ms-vscode.js-debug-companion@1.0.15 ...
[19:42:52] Downloading extension: ms-vscode.js-debug@1.62.0 ...
[19:42:52] Downloading extension: ms-vscode.vscode-js-profile-table@0.0.18 ...
[19:42:52] [marketplace] ms-vscode.references-view ✔︎
[19:42:52] [marketplace] ms-vscode.js-debug-companion ✔︎
[19:42:52] [marketplace] ms-vscode.vscode-js-profile-table ✔︎
[19:42:54] [marketplace] ms-vscode.js-debug ✔︎
Done in 3.10s.
yarn run v1.22.15
$ node --max_old_space_size=8192 ./node_modules/gulp/bin/gulp.js node
[19:43:00] Using gulpfile ~/git-prjs/vscode/gulpfile.js
[19:43:00] Starting 'node'...
[19:43:07] Finished 'node' after 6.97 s
Done in 12.31s.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/ashwin/git-prjs/vscode/out/vs/server/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by ashwin31** [comment]
@bpasero Thank you. It worked.

I pulled fresh code and ran the following commands.
1. yarn
2. yarn watch
3. resources/server/bin-dev/server.sh

Then I got terminal. May I know how to load extensions too. Now the extensions are empty even after I search in the extensions panel.
