### ISSUE TITLE
Cannot build VSCode on latest master

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#136978]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Master
- OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000
- Node Version: 14.18.1

Gist: https://gist.github.com/jasonwilliams/7d12786309486bc3b728bb8938c901b7

Things I've tried:
- remove the ~/.node-gyp folder
- run yarn cache clean
- Set the correct `PYTHON` path 
- Followed https://github.com/nodejs/node-gyp#on-windows
- Followed https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites

Any help is appreciated

**Comment by joaomoreno** [comment]
Related https://github.com/microsoft/vscode/issues/130947

@deepak1556 Any clues?

**Comment by deepak1556** [comment]
@dbaeumer is working on a refactor for the windows installation process to avoid this corrupt cache issue https://github.com/microsoft/vscode/blob/dbaeumer/prefetchHeaders,

As a temporary workaround, can you try the following and see if it helps

```
* Delete `%LOCALAPPDATA%/node-gyp`
* cd vscode
* git clean -xfd
* yarn
```

**Comment by dbaeumer** [comment]
Actually the changes are already in main and above steps should bring you back into business.

**Comment by jasonwilliams** [comment]
Thanks it seems i can get past the yarn stage. However running the code.bat gives me (and a blank window pop up)

```
[main 2021-12-16T22:19:06.807Z] ExtensionHostStarterWorker created
[9932:1216/221906.996:INFO:CONSOLE(250)] "[uncaught exception]: Error: [object Event]", source: vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/bootstrap-window.js (250)
[9932:1216/221906.996:INFO:CONSOLE(253)] "Error: [object Event]
    at Object.ensureError (vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:256:22)
    at ModuleManager._createLoadError (vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:1508:33)
    at ModuleManager._onLoadError (vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:1519:30)
    at loadNextPath (vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:1665:27)
    at Object.errorback (vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:1685:25)
    at OnlyOnceScriptLoader.triggerErrorback (vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:632:36)
    at vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:619:151
    at HTMLScriptElement.errorEventListener (vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/vs/loader.js:655:17)", source: vscode-file://vscode-app/c:/Users/jasew/workspace/vscode/out/bootstrap-window.js (253)
```

**Comment by jasonwilliams** [comment]
This is my task manager whn running the "VS Code" debug option after building.
I don't know what its doing but looks like its doing a lot of searching!

nothing happens in VSCode it just spins and waits.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/936006/146458846-84b562d2-e7df-467a-a30d-8994a0120126.png">

**Comment by jasonwilliams** [comment]
I did a complete deletion of the VSCode folder and started again from scratch and now it builds. 
I can do:
- yarn
- ctrl + shift + b
- Launch VSCode

I have the child window.

I think the issue was my vscode folder was corrupt and needed a complete wipe, or something fixed it
