### ISSUE TITLE
vscode-ripgrep: Command failed.

### ISSUE THREAD

**Issue by lichangwei123** [microsoft/vscode#137015]
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[8/9] ⠁ vscode-windows-registry
[6/9] ⠁ vscode-windows-ca-certs
[3/9] ⠁ node-pty
[9/9] ⠂ windows-process-tree
error D:\site\xinchengkeji\vscode\remote\node_modules\vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: D:\site\xinchengkeji\vscode\remote\node_modules\vscode-ripgrep
Output:
Finding release for v13.0.0-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-2
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.169.195.247:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS D:\site\xinchengkeji\vscode>

**Comment by lichangwei123** [comment]
![1636688151](https://user-images.githubusercontent.com/46671582/141404734-b2811172-3e8f-45c5-b7e9-769963d497be.png)

**Comment by roblourens** [comment]
Do you have a proxy? Is it set up correctly in this shell? Can you access that URL?
