### ISSUE TITLE
Git operations fail due to empty VSCODE_GIT_ASKPASS_EXTRA_ARGS

### ISSUE THREAD

**Issue by tpambor** [microsoft/vscode#137183]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Debian 12

Steps to Reproduce:

1. Run `env | grep VSCODE_GIT_ASKPASS_EXTRA_ARGS` returns `VSCODE_GIT_ASKPASS_EXTRA_ARGS=`
2. Move to a git repository and run `git fetch` returns: `remote: HTTP Basic: Access denied`
3. Run `export VSCODE_GIT_ASKPASS_EXTRA_ARGS="--ms-enable-electron-run-as-node"`
4. Running `git fetch` then works.

`VSCODE_GIT_ASKPASS_EXTRA_ARGS` should be set to `--ms-enable-electron-run-as-node`.

Output of `process.versions` in debug console:
```
ares: "1.16.1"
brotli: "1.0.9"
chrome: "91.0.4472.164"
electron: "13.5.2"
icu: "68.1"
llhttp: "2.1.3"
microsoft-build: "10663358"
modules: "89"
napi: "7"
nghttp2: "1.41.0"
node: "14.16.0"
openssl: "1.1.1"
unicode: "13.0"
uv: "1.40.0"
v8: "9.1.269.39-electron.0"
zlib: "1.2.11"
```

**Comment by tpambor** [comment]
The same problem is also present in 1.62.1. 1.62.0 is the last working version.

**Comment by vasudev-gm** [comment]
Facing the same issue. Had to revert to 1.62.0 which fixed the issue. I'm using Xubuntu 20.04.3.

**Comment by x07** [comment]
@lszomoru I ran into the same issue on version `1.62.2`, using `Ubuntu 20.04 LTS`. Setting the envvar as above fixed it

**Comment by tpambor** [comment]
> This issue should be fixed in `1.62.2`. Can you please confirm that you are able to reproduce the issue with the latest version?

I can confirm it happens with `1.62.2` and `1.62.1` and all extensions disabled as well.

**Comment by a-samir97** [comment]
I have the same issue happens with the latest version `1.62.2`

**Comment by deepak1556** [comment]
I am unable to repro with snap version of vscode following the steps at https://github.com/microsoft/vscode/issues/137183#issue-1053060480. Can anyone please share a screen capture with exact steps to repro the issue ? Thanks!

Also it would be great if you can start with `NODE_DEBUG="child_process" code --verbose` and attach the log when the failure happens.

**Comment by tpambor** [comment]
I am using the deb package `https://packages.microsoft.com/repos/vscode stable/main amd64 code amd64 1.62.2-1636665017`.

![vscode](https://user-images.githubusercontent.com/1379478/141780279-f6a687b0-5c45-4d5b-ba64-26d1a171b667.png)

[code.log](https://github.com/microsoft/vscode/files/7538585/code.log)

**Comment by tpambor** [comment]
The problem is not limited to the terminal, builtin git operations fail as well.

![vscode2](https://user-images.githubusercontent.com/1379478/141789322-277e152c-ba86-49d4-b278-8fb2c30103b6.png)

**Comment by deepak1556** [comment]
Thanks for the steps, we were able to narrow down the root cause. I will ping here again once the fix is rolled into our insiders for testing.

**Comment by vasudev-gm** [comment]
Thanks @deepak1556 and @tpambor 
Just added "git.terminalAuthentication": false to .vscode/settings.json which allows auth creds to be passed via terminal.
Once the fix is released, "git.terminalAuthentication" in settings.json to true which is the default value or even removed to avoid confusion.

**Comment by uberkaz** [comment]
facing the same issue in version `1.62.2` Setting the envvar as above fixed it. thanks for this

**Comment by Pinche-Dev** [comment]
The same problem is present in INSIDER build also

**Comment by alexr00** [comment]
Closing for verification.

**Comment by deepak1556** [comment]
Fix is now available with latest insiders Version: 1.63.0-insider (d450b04c783dfa6f83dc439017767acccd4e9fac) and will be shipped with recovery release `1.62.3` this week. Please give it a try and sorry for the breakage!

**Comment by tpambor** [comment]
I can confirm that the insider build is working now. Thanks @deepak1556 and others involved!

**Comment by MichelVarela** [comment]
> 3\. export VSCODE_GIT_ASKPASS_EXTRA_ARGS="--ms-enable-electron-run-as-node"

me devuelve este error

help me

Missing or invalid credentials.
Error: connect ECONNREFUSED /run/user/1000/vscode-git-c0839b2070.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/run/user/1000/vscode-git-c0839b2070.sock'
}
Missing or invalid credentials.
Error: connect ECONNREFUSED /run/user/1000/vscode-git-c0839b2070.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/run/user/1000/vscode-git-c0839b2070.sock'
}
remote: No anonymous write access.
fatal: Autenticación falló para

**Comment by gjsjohnmurray** [comment]
@MichelVarela what exact version number of VS Code are you running?

**Comment by Leigh-M** [comment]
My issue was closed and was pointed back to this issue, which is supposed to be fixed in 1.62.3.  However this issue is still not fixed for me in 1.62.3, Ubuntu 21.04

On any git command, eg a:  git fetch:

```
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/some-repo.git/'
```

**Comment by KorigamiK** [comment]
> My issue was closed and was pointed back to this issue, which is supposed to be fixed in 1.62.3. However this issue is still not fixed for me in 1.62.3, Ubuntu 21.04
> 
> On any git command, eg a: git fetch:
> 
> ```
> remote: Repository not found.
> fatal: Authentication failed for 'https://github.com/some-repo.git/'
> ```

[Does this reply](https://github.com/microsoft/vscode/issues/137183#issuecomment-968941578)

solve anything for you?

**Comment by maxisam** [comment]
@deepak1556 with WSL, it is still not working, tried  "git.terminalAuthentication": false as well
