### ISSUE TITLE
Unable to sync settings with Microsoft account

### ISSUE THREAD

**Issue by Jademalo** [microsoft/vscode#137281]
Issue Type: <b>Bug</b>

After a while, I'll get an error saying 
> Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing

After signing back in it seems to work for a while, but then eventually I get the same error again.
There are no issues with my account, and it has worked fine for weeks. This is only since the most recent update.

```[2021-11-16 05:51:48.232] [settingssync] [info] Auto Sync: Started
[2021-11-16 05:51:48.232] [settingssync] [info] Auto Sync: Triggered by Interval
[2021-11-16 05:51:48.305] [settingssync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":401,"execution-id":"e8724172-63c6-4e2a-8930-9adca6428d19"}
[2021-11-16 05:51:48.305] [settingssync] [info] Auto Sync: Suspended until auth token is available.
[2021-11-16 05:51:48.305] [settingssync] [info] Auto sync: Cancelled sync that is in progress
[2021-11-16 05:51:48.305] [settingssync] [info] Auto Sync: Stopped
[2021-11-16 05:51:48.305] [settingssync] [error] Unauthorized (UserDataSyncError) syncResource:unknown operationId:unknown: Request 'https://vscode-sync.trafficmanager.net/v1/manifest' failed because of Unauthorized (401).
    at p.request (vscode-file://vscode-app/c:/Users/Scotty/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:174848)
    at async p.manifest (vscode-file://vscode-app/c:/Users/Scotty/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:172045)
    at async u.createSyncTask (vscode-file://vscode-app/c:/Users/Scotty/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:142912)
    at async a.doSync (vscode-file://vscode-app/c:/Users/Scotty/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:137299)
```

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.46GB free)|
|Process Argv|--crash-reporter-id 75d2bff3-b4ef-4cb2-9b19-e7eeeba2b392|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)|
|Memory (System)|7.69GB (6.01GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|1.5.2
remote-wsl|ms-|0.58.5
material-icon-theme|PKi|4.10.0
material-theme|zhu|3.13.2
tasks|act|0.9.0
githistory|don|0.6.19
git-commits|Exe|3.10.2
vscode-pull-request-github|Git|0.32.0
poryscript|kar|2.2.1
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
pin-up|sae|1.4.1
vscode-taskexplorer|spm|2.5.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377
vscexrecpromptt2:30400062

```

</details>

**Comment by sandy081** [comment]
/duplicate

#133201
