### ISSUE TITLE
Electron 15: TypeError: performance.getEntriesByType is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137366]
Steps to Reproduce:

1. `git co electron-16.x.y`
2. `yarn && yarn watch`
3. `scripts/code.sh`

```
[main 2021-11-17T12:35:07.230Z] TypeError: performance.getEntriesByType is not a function or its return value is not iterable
    at getMarks (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/base/common/performance.js:65:39)
    at WindowsMainService.openInBrowserWindow (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/platform/windows/electron-main/windowsMainService.js:956:55)
    at WindowsMainService.doOpenFolderOrWorkspace (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/platform/windows/electron-main/windowsMainService.js:424:25)
    at /Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/platform/windows/electron-main/windowsMainService.js:349:40
    at Array.forEach (<anonymous>)
    at WindowsMainService.doOpen (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/platform/windows/electron-main/windowsMainService.js:342:34)
    at WindowsMainService.open (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/platform/windows/electron-main/windowsMainService.js:152:72)
    at CodeApplication.openFirstWindow (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/code/electron-main/app.js:588:39)
    at /Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/code/electron-main/app.js:256:85
    at InstantiationService.invokeFunction (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/platform/instantiation/common/instantiationService.js:44:24)
    at CodeApplication.startup (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/code/electron-main/app.js:256:53)
    at async CodeMain.startup (/Users/bpasero/Development/Microsoft/vscode-electron-15.x/out/vs/code/electron-main/main.js:43:17)
```

The underlying issue seems to be that starting with node.js 16 there is a global `performance` defined and our checks in `performance.js` confuse that with the DOM `performance` type.

//cc @deepak1556

**Comment by bpasero** [comment]
Deepak suggested to maybe probe on [`performance.nodeTiming`](https://nodejs.org/dist/latest-v16.x/docs/api/perf_hooks.html#performancenodetiming) to detect node.js

**Comment by deepak1556** [comment]
Fix pushed in the above branch https://github.com/microsoft/vscode/pull/137241/commits/34520c0920489650a7ba0d306b5cd55fad4bdf87

**Comment by jrieken** [comment]
So bizare... With electron fiddle this seems OK

<img width="1024" alt="Screen Shot 2021-11-17 at 16 38 18" src="https://user-images.githubusercontent.com/1794099/142231673-954282f2-0e37-4b14-8427-f1428db7a658.png">

**Comment by deepak1556** [comment]
@jrieken the error is thrown from the main process where only the node performance object is present.

**Comment by jrieken** [comment]
ah, I see. Thanks for clarifying

**Comment by jrieken** [comment]
@deepak1556 I have cherry-picked your commit onto main. Thanks!
