### ISSUE TITLE
Electron 15: UnhandledPromiseRejectionWarning in extensions/emmet/test-workspace integration tests

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#137416]
Steps to Reproduce:

```
1) git co electron-16.x.y
2) yarn && yarn watch
3) scripts/test-integration.sh
```

```
(node:10567) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at canceled (/Users/demohan/github/vscode/out/vs/base/common/errors.js:109:23)
    at Delayer.cancel (/Users/demohan/github/vscode/out/vs/base/common/async.js:247:57)
    at Delayer.dispose (/Users/demohan/github/vscode/out/vs/base/common/async.js:259:18)
    at ThrottledDelayer.dispose (/Users/demohan/github/vscode/out/vs/base/common/async.js:287:26)
    at dispose (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:153:18)
    at FileWatcher.dispose (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:195:25)
    at FileWatcher.dispose (/Users/demohan/github/vscode/out/vs/platform/files/node/watcher/nodejs/watcherService.js:103:19)
    at dispose (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:153:18)
    at dispose (/Users/demohan/github/vscode/out/vs/base/common/lifecycle.js:115:17)
    at DiskFileSystemProviderChannel.unwatch (/Users/demohan/github/vscode/out/vs/platform/files/node/diskFileSystemProviderIpc.js:158:41)
    at DiskFileSystemProviderChannel.call (/Users/demohan/github/vscode/out/vs/platform/files/node/diskFileSystemProviderIpc.js:39:45)
    at ChannelServer.onPromise (/Users/demohan/github/vscode/out/vs/base/parts/ipc/common/ipc.js:259:35)
    at ChannelServer.onRawMessage (/Users/demohan/github/vscode/out/vs/base/parts/ipc/common/ipc.js:232:33)
    at /Users/demohan/github/vscode/out/vs/base/parts/ipc/common/ipc.js:177:73
    at Emitter.fire (/Users/demohan/github/vscode/out/vs/base/common/event.js:435:38)
    at /Users/demohan/github/vscode/out/vs/base/common/event.js:43:93
    at Emitter.fire (/Users/demohan/github/vscode/out/vs/base/common/event.js:435:38)
    at /Users/demohan/github/vscode/out/vs/base/common/event.js:54:106
    at Emitter.fire (/Users/demohan/github/vscode/out/vs/base/common/event.js:435:38)
    at IpcMainImpl.fn (/Users/demohan/github/vscode/out/vs/base/common/event.js:237:44)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:10567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by deepak1556** [comment]
@bpasero I am assigning it to you as a start since the trace has file watcher paths.
