### ISSUE TITLE
VSCode integrated terminal closes when clicking on it

### ISSUE THREAD

**Issue by finnborchers** [microsoft/vscode#137576]
What I basically tried to do is changing the bundle name of a flutter project.
Then I clicked on a button which said something like "kill terminal" or something like that, because I tried to navigate in the terminal which did not work so I pressed this button.

Now, when I go to Terminal (Next to Window) and then click on new Terminal, the window opens where you can also see the debug and output field. But this only lasts for about one second and then this whole window closes again.

I'm on macOS Catalina 10.15.7.
I installed the newest version of VSCode.

This is the error I get when I restart VSCode:

<img width="566" alt="Bildschirmfoto 2021-11-20 um 16 45 44" src="https://user-images.githubusercontent.com/64986067/142732493-f1dc2b5d-c3cc-4720-b6ab-d788fc9e4b23.png">

What I also did: I deleted the settings.json file from VSCode because I read about it but this didn't work out.

 Also if I click here:

<img width="148" alt="Bildschirmfoto 2021-11-20 um 16 49 57" src="https://user-images.githubusercontent.com/64986067/142732625-c388a8ba-75d5-4a0a-a1c8-4b2b838c808d.png">

I see this:
<img width="1049" alt="Bildschirmfoto 2021-11-20 um 16 50 31" src="https://user-images.githubusercontent.com/64986067/142732643-cdf619f5-002f-43c8-852c-eca61b7ee1c3.png">

But when I now click on TERMINAL this whole thing closes again.

EDIT: I launched the project in AndroidStudio and there is the same problem, the terminal opens for about one second, then closes and disappears.

This is the log trace from VSCode:

[2021-11-21 13:29:48.118] [renderer1] [trace] CommandService#executeCommand workbench.actions.view.toggleProblems
[2021-11-21 13:29:49.289] [renderer1] [trace] terminalInstance#ctor (instanceId: 4) {}
[2021-11-21 13:29:49.422] [renderer1] [debug] Terminal process ready (shellProcessId: 69567)
[2021-11-21 13:29:49.937] [renderer1] [debug] Terminal process exit (instanceId: 4) with code undefined
[2021-11-21 13:29:49.938] [renderer1] [debug] Terminal process exit (instanceId: 4) state 6
[2021-11-21 13:29:49.939] [renderer1] [trace] terminalInstance#dispose (instanceId: 4)

Also, I created a new Apple user account on my machine and tried launching VSCode from the other account.
This seems to work fine. VSCode works normal there, but not on my main account.

For testing purposes I also created a new Flutter project and got this trace log here:

[2021-11-21 14:20:37.147] [renderer1] [info] Starting extension host with pid 72508.
[2021-11-21 14:20:37.147] [renderer1] [info] [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 18 ms.
[2021-11-21 14:20:37.746] [renderer1] [error] [Extension Host] (node:72508) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
[2021-11-21 14:20:51.243] [renderer1] [error] Could not find pty with id "1": Error: Could not find pty with id "1"
    at a._throwIfNoPty (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:17:5466)
    at a.updateIcon (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:17:2230)
    at Object.call (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:13:8419)
    at S.onPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:12:4939)
    at S.onRawMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:12:4298)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:12:3551
    at R.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:8:1712)
    at process.D (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:6:32686)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

I hope this leads to a solution

**Comment by meganrogge** [comment]
try setting `terminal.integrated.useWslProfiles` to false

**Comment by finnborchers** [comment]
Hi, thanks for your answer. This did not work unfortunately.

**Comment by finnborchers** [comment]
> try setting `terminal.integrated.useWslProfiles` to false

Any ideas what else I could try? Otherwise I will reset my Mac.
