### ISSUE TITLE
Sometimes the kill terminal command doesn't work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137514]
Repro:

1. Open a terminal
2. Close the panel
3. Reload the window
4. Run build task (might not be needed)
5. Toggle terminal
6. Run kill terminal command

Likely related to state problems with revived terminals

![recording (1)](https://user-images.githubusercontent.com/2193314/142638740-c52d78d9-ec82-416a-b1f9-5db05fb14397.gif)

**Comment by meganrogge** [comment]
can't repro this 🤔

**Comment by Tyriar** [comment]
More related problems on weekend:

Repro I think was to restart VS Code when there is 1 terminal (to be revived) and the panel is closed; there isn't an active terminal and toggle terminal doesn't work properly as the terminal doesn't end up getting focused:
![recording (7)](https://user-images.githubusercontent.com/2193314/144855688-d21cce62-3176-4a0c-b8d7-9078f03aa198.gif)

Similar repro led to this:
![recording (8)](https://user-images.githubusercontent.com/2193314/144855777-540245f0-54ac-4cc3-8a70-d138aef2356e.gif)

**Comment by meganrogge** [comment]
still can't repro - but right after this recording, the pty host became unresponsive

![recording - 2021-12-06T150412 543](https://user-images.githubusercontent.com/29464607/144936819-096582f1-52fa-4acd-b513-367959b091d1.gif)

**Comment by meganrogge** [comment]
I can imagine that this is a bug though because here we fallback to the last recorded terminal if it doesn't have focus

https://github.com/microsoft/vscode/blob/f86e5d14afe60ceddb339ebc73bbd501f5029312/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L93

but I don't see us setting that anywhere (when the revive happens)

**Comment by meganrogge** [comment]
`activeInstance` is undefined here on restart

https://github.com/microsoft/vscode/blob/f86e5d14afe60ceddb339ebc73bbd501f5029312/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L420-L426

**Comment by Tyriar** [comment]
Can no longer reproduce either 🤷

**Comment by Tyriar** [comment]
This happened again on a workspace I hadn't opened in a long time, maybe older versions used a different format and it throws during revive or something 🤔 

Will keep closed until I get more info as it's hard to repro.

**Comment by Tyriar** [comment]
Happened this morning, this is what I did:

1. Boot up Windows
2. Open VS Code
3. Close some windows I didn't care about anymore so only microsoft/vscode was open
4. Open the panel

![image](https://user-images.githubusercontent.com/2193314/146948634-07cd0741-9238-4799-a48a-0f25dd46bc42.png)

No logs in console.

Logs for shared process:

```
INFO Starting worker process with pid 16456 (type: parcelWatcher, window: 3).
sharedProcessMain.js:29  INFO Starting worker process with pid 16492 (type: parcelWatcher, window: 4).
sharedProcessMain.js:29  INFO Starting worker process with pid 16540 (type: parcelWatcher, window: 2).
sharedProcessMain.js:29  INFO Starting worker process with pid 16596 (type: parcelWatcher, window: 1).
sharedProcessMain.js:18 [IPC Library: Pty Host]  INFO Persistent process "3": Replaying 3487 chars and 1 size events
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
sharedProcessMain.js:18 [IPC Library: Pty Host]  INFO Persistent process "4": Replaying 3483 chars and 1 size events
sharedProcessMain.js:18 [IPC Library: Pty Host]  INFO Persistent process "7": Replaying 12216 chars and 1 size events
sharedProcessMain.js:18 [IPC Library: Pty Host]  INFO Persistent process "10": Replaying 5498 chars and 1 size events
sharedProcessMain.js:29  INFO Getting Manifest... github.vscode-pull-request-github
sharedProcessMain.js:29  INFO Installing extension: github.vscode-pull-request-github
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
sharedProcessMain.js:29  INFO Downloaded extension: github.vscode-pull-request-github c:\Users\Daniel\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\github.vscode-pull-request-github-0.34.2
sharedProcessMain.js:29  INFO Extracted extension to c:\Users\Daniel\.vscode-insiders\extensions\.7f7d9477-451f-4b2e-ae8c-b1d8dd9102c9: github.vscode-pull-request-github
sharedProcessMain.js:29  INFO Renamed to c:\Users\Daniel\.vscode-insiders\extensions\github.vscode-pull-request-github-0.34.2
sharedProcessMain.js:29  INFO Extracting completed. github.vscode-pull-request-github
sharedProcessMain.js:29  INFO Extension installed successfully: github.vscode-pull-request-github
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
sharedProcessMain.js:29  INFO Worker process with pid 16492 terminated normally (type: parcelWatcher, window: 4).
sharedProcessMain.js:18 [IPC Library: Pty Host] Uncaught Exception:  Error: read EPIPE
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)
D @ sharedProcessMain.js:18
sharedProcessMain.js:29  INFO Worker process with pid 16456 terminated normally (type: parcelWatcher, window: 3).
sharedProcessMain.js:29  INFO Worker process with pid 16540 terminated normally (type: parcelWatcher, window: 2).
sharedProcessMain.js:18 [IPC Library: Pty Host] Uncaught Exception:  Error: read EPIPE
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)
D @ sharedProcessMain.js:18
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
v @ bootstrap-window.js:1
bootstrap-window.js:1 [uncaught exception]: TypeError: setTimeout(...).unref is not a function
v @ bootstrap-window.js:1
(anonymous) @ bootstrap-window.js:1
emit @ events.js:315
window.onerror @ electron/js2c/renderer_init.js:105
bootstrap-window.js:1 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\applicationinsights\out\Library\Sender.js:100)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
```

DOM state:

![image](https://user-images.githubusercontent.com/2193314/146948845-2e15edd5-d1ae-498d-8ea8-24c1966d4119.png)

Notice how toggle terminal and the rendering of the tabs behaves differently depends on which is the active terminal:

![recording (10)](https://user-images.githubusercontent.com/2193314/146948973-a8cb6520-2fb1-452d-888f-bec7c23ad3ef.gif)

**Comment by Tyriar** [comment]
`TerminalTabsList.refresh`:

![image](https://user-images.githubusercontent.com/2193314/146949455-66826b7f-ccd8-450d-8a39-94488d9a3f35.png)

**Comment by Tyriar** [comment]
When calling toggleTerminal that doesn't do anything:
![image](https://user-images.githubusercontent.com/2193314/146951548-27a90db3-3010-4556-b7f7-4c30878ff304.png)

**Comment by Tyriar** [comment]
Inside focus call the group shows the active instance index as -1:

![image](https://user-images.githubusercontent.com/2193314/146952022-9ee55675-9806-4d49-8c1e-a38366c5cd63.png)

That's likely the issue.

![image](https://user-images.githubusercontent.com/2193314/146952293-abe41019-6629-4c24-b975-6b8ed7ba73ad.png)

**Comment by Tyriar** [comment]
The active group isn't tracking the active instance, so it never gets focused, so the toggle command never changes state.

**Comment by Tyriar** [comment]
Once focusing the bad terminal group via click everything is fixed, which makes sense given above.

**Comment by Tyriar** [comment]
Think I fixed it, this will be hard to verify as the repro case isn't solid. I'll mark as verified pre-emptively and reopen if I see it again.
