### ISSUE TITLE
VSCode on Mac OS does not launch when user's home directory is on ExFAT filesystem

### ISSUE THREAD

**Issue by nileshtrivedi** [microsoft/vscode#137602]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2, 3a6960b964327f0e3882ce18fcebd07ed191b316, x64
- OS Version: Mac OS Monterey 12.0.1 (Intel)

Steps to Reproduce:

I have a Mac user with home directory set to a folder on external hard drive which is formatted as ExFAT. This means all files are readable and writable by all users. Launching VS Code either from command line or from the Dock/Launchpad fails. `--verbose` shows the following message:

```
$ code --verbose
[main 2021-11-21T09:26:53.832Z] [File Watcher (node.js)] Refusing to watch /Volumes/SEAGATE/nileshmacuser/Library/Application Support/Code/User for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
[main 2021-11-21T09:26:53.846Z] Error: listen EINVAL: invalid argument /Volumes/SEAGATE/nileshmacuser/Library/Application Support/Code/1.62.2-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1463:5)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:71:31429
    at new Promise (<anonymous>)
    at r (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:71:31362)
    at Q.claimInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:79:4608)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:79:2283
    at invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:29:319)
    at Q.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/m[main 2021-11-21T09:26:53.847Z] Lifecycle#kill()
ain.js:79:2149)
```

**Comment by bpasero** [comment]
The `1.62.2-main.sock` file is used for a second instance talking to the first instance. Would be interesting to figure out if `requestSingleInstanceLock` has the same issue.

**Comment by joaomoreno** [comment]
This is an unsupported scenario. You must have the user data directory in a file system which supports UNIX sockets. You can override it with `--user-data-dir DIR`.
