### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Target-design** [microsoft/vscode#137604]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 s \ R U P A S H Space K U L K A R N I \ O n e D r i v e \ D a t a Space S t r u c t u r e s Space a n d Space A l g o r i t h m s \ p y t h . p y " Enter
 c l e a r Enter
 c d Space " c : \ U s e r s \ R U P A S H Space K U L K A R N I \ O n e D r i v e \ D a t a Space S t r u c t u r e s Space a n d Space A l g o r i t h m s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space t e s t . c p p Space - o Space t e s t Space } Space ; Space i f Space ( $ ? ) Space { Space . \ t e s t Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by gjsjohnmurray** [comment]
I think this needs to be reported to the repo mentioned in the message you pasted.
