### ISSUE TITLE
Integration test failure: Recursive Watcher (parcel) basics

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137732]
This test flaked 6 times in the past month.

![image](https://user-images.githubusercontent.com/2193314/143062670-1166b456-03a4-4710-87e4-8929cabd6fa5.png)

```
Error: Unexpected file event: unexpected-event-from-stat
    at file:///Users/runner/work/1/s/out-build/vs/platform/files/test/node/recursiveWatcher.integrationTest.js:83:40
    at Emitter.fire (file:///Users/runner/work/1/s/out-build/vs/base/common/event.js:435:38)
    at TestParcelWatcherService.emitEvents (file:///Users/runner/work/1/s/out-build/vs/platform/files/node/watcher/parcel/parcelWatcherService.js:277:35)
    at TestParcelWatcherService.onParcelEvents (file:///Users/runner/work/1/s/out-build/vs/platform/files/node/watcher/parcel/parcelWatcherService.js:251:18)
    at parcelWatcher.subscribe.backend (file:///Users/runner/work/1/s/out-build/vs/platform/files/node/watcher/parcel/parcelWatcherService.js:229:22)
```

Example failing build: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=142406&view=results

I notice we also have it already wrapped in `flakySuite` a month ago but they remain flaky:

https://github.com/microsoft/vscode/blob/3a81c25c7abd5b1ebf76fb10e8b3b7a27aef9000/src/vs/platform/files/test/node/recursiveWatcher.integrationTest.ts#L18

I looked through the 6 failing builds and noticed this fails on macOS so you might be able to remove flakySuite for other platforms and action only for macOS.

**Comment by bpasero** [comment]
Disabled these asserts on macOS, the main interest is actually to ensure we get no event from Windows when statting because there exists `ReadDirectoryChangesW` flags that would fire even on read access.
