### ISSUE TITLE
Terminal Tabs: should do nothing when join tabs is run with only one terminal

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137798]
```
1) VSCode Smoke Tests (Web)
       Terminal Tabs
         should do nothing when join tabs is run with only one terminal:
     Error: Timeout: get element '.terminal.xterm.focus' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:181:19)
      at async Code.waitForElement (D:\a\1\s\test\automation\out\code.js:283:16)
      at async Terminal._waitForTerminal (D:\a\1\s\test\automation\out\terminal.js:181:9)
      at async Terminal.runCommand (D:\a\1\s\test\automation\out\terminal.js:57:20)
      at async Context.<anonymous> (out\areas\terminal\terminal-tabs.test.js:83:13)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144206&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9302e8c4-de85-5274-34fa-935ce79d4e8d&l=134

**Comment by meganrogge** [comment]
this is failing for justifiable reasons - rn when you run join tabs with nothing selected, it still shows a quickpick (with no options)
