### ISSUE TITLE
Smoke test flake: VSCode Smoke Tests (Electron) Dataloss verifies that 'hot exit' works for dirty files

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137729]
This test flaked 33 times in the past month:

![image](https://user-images.githubusercontent.com/2193314/143059564-793041e7-0460-48fe-be5a-3a06cd5a8997.png)

Example failed run: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=144008&view=results

```
Error: Timeout: get window ids after 20 seconds.
    at poll (D:\a\1\s\test\automation\out\code.js:181:19)
    at async Code.waitForWindowIds (D:\a\1\s\test\automation\out\code.js:226:9)
    at async Application.checkWindowReady (D:\a\1\s\test\automation\out\application.js:93:9)
    at async Application.reload (D:\a\1\s\test\automation\out\application.js:64:9)
    at async Context.<anonymous> (out\areas\workbench\data-loss.test.js:23:13)
```

**Comment by bpasero** [comment]
This seems unrelated to the smoke test in particular but around the application reporting back whether it is ready or not (I assume): `waitForWindowIds`

**Comment by joaomoreno** [comment]
@bpasero I am not the owner of this smoketest.
