### ISSUE TITLE
Smoke test flake: VSCode Smoke Tests (Electron) Quick Access quick access search produces correct result

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137728]
This test flaked 35 times in the last month:

![image](https://user-images.githubusercontent.com/2193314/143059176-269a36a9-11ec-483b-aefa-799075a541ba.png)

Example failed run: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=143928&view=results

```
Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
    at poll (D:\a\1\s\test\automation\out\code.js:181:19)
    at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:261:16)
    at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
    at async Context.<anonymous> (out\areas\search\search.test.js:77:13)
```

**Comment by TylerLeonhardt** [comment]
Looks like this is a search smoke test

**Comment by roblourens** [comment]
Goes along with https://github.com/microsoft/vscode/issues/137733, I'm looking at it
