### ISSUE TITLE
"Invalid: extension/package.json not found inside zip." when installing the Python extension on Windows

### ISSUE THREAD

**Issue by fbs2016** [microsoft/vscode#137739]
### VS Code version

1.62.3

### Extension version

v2021.11.1422169775

### OS type

Windows

### OS version

windows 10

### Python distribution

Operating system

### Python version

3.10.0

### Language server

Default

### Expected behaviour

Install python extension on VS code success on Windows host

### Actual behaviour

Install failed:
[2021-11-23 20:40:51.435] [renderer1] [error] ["Invalid: extension/package.json not found inside zip.","    at q.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/bfu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:200682)","    at async q.doRun (vscode-file://vscode-app/c:/Users/bfu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:199396)"]
[2021-11-23 20:40:51.459] [renderer1] [error] extension/package.json not found inside zip.: Invalid: extension/package.json not found inside zip.
    at q.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/bfu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:200682)
    at async q.doRun (vscode-file://vscode-app/c:/Users/bfu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:199396)

### Steps to reproduce

Find python extension in VSC, then click install button to install it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fbs2016** [comment]
I try online installation and offline vsix installation, both of them failed with same err.

**Comment by fbs2016** [comment]
Can't install cmake tools extension, and download vsix file from repo and install success.

**Comment by sandy081** [comment]
Can you please provide us the shared process logs using following command

`F1 > Open View... > Log (Shared)`

Try to repro the issue and share us the log.
