### ISSUE TITLE
tsserver throwing errors during extension tests

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#13785]
- VSCode Version: 1.6.1
- OS Version: All

Typescript server throws errors during test run when extension contains no typescript:

```javascript
{ seq: 0,
  type: 'response',
  command: 'projectInfo',
  request_seq: 116,
  success: false,
  message: 'Error processing request. No Project.\nError: No Project.\n    at Errors (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:50793:32)\n    at ts.server.ts.server (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:50795:11)\n    at ts (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:51775:7)\n    at Object.<anonymous> (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:51776:3)\n    at Module._compile (module.js:556:32)\n    at Object.Module._extensions..js (module.js:565:10)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)' }
```

message:
```
Error processing request. No Project.
Error: No Project.
    at Errors (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:50793:32)
    at ts.server.ts.server (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:50795:11)
    at ts (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:51775:7)
    at Object.<anonymous> (/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test/VSCode-linux-x64/resources/app/extensions/typescript/server/typescript/lib/tsserver.js:51776:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

The same error presents on Appveyor as well. 

See:
https://ci.appveyor.com/project/HookyQR/vscodebeautify/build/1.0.47
https://travis-ci.org/HookyQR/VSCodeBeautify/jobs/167755781

**Comment by bpasero** [comment]
Same in our builds: https://travis-ci.org/Microsoft/vscode/jobs/167740336#L6698

**Comment by bpasero** [comment]
@waderyan fyi

**Comment by dbaeumer** [comment]
@jrieken I assume this is the projectInfo request send by the JS status line light bulb.

**Comment by dbaeumer** [comment]
The tsserver doesn't send this request in other situations.

**Comment by aeschli** [comment]
verified in code
