### ISSUE TITLE
 VSC remote development parse ssh config file error

### ISSUE THREAD

**Issue by jxliaocb** [microsoft/vscode#137823]
in windows10  family Version, using  VSC remote development to open ssh connection ,  After selecting the file and saving the config to Known_hosts file. the connection OK. But when I open remote Folder /home/changbing.liao/fat3/fat2,  there is a error. The follwoing text it the error message from the output window.

```
[06:43:27.199] Log Level: 2
[06:43:27.205] remote-ssh@0.66.1
[06:43:27.205] win32 x64
[06:43:27.223] SSH Resolver called for "ssh-remote+172.16.40.121", attempt 1
[06:43:27.223] "remote.SSH.useLocalServer": false
[06:43:27.224] "remote.SSH.showLoginTerminal": false
[06:43:27.224] "remote.SSH.remotePlatform": {"172.16.40.121":"linux"}
[06:43:27.224] "remote.SSH.path": undefined
[06:43:27.224] "remote.SSH.configFile": c:\users\jxlia\.ssh\Known_hosts
[06:43:27.224] "remote.SSH.useFlock": true
[06:43:27.224] "remote.SSH.lockfilesInTmp": false
[06:43:27.224] "remote.SSH.localServerDownload": auto
[06:43:27.225] "remote.SSH.remoteServerListenOnSocket": false
[06:43:27.225] "remote.SSH.showLoginTerminal": false
[06:43:27.225] "remote.SSH.defaultExtensions": []
[06:43:27.225] "remote.SSH.loglevel": 2
[06:43:27.225] SSH Resolver called for host: 172.16.40.121
[06:43:27.225] Setting up SSH remote "172.16.40.121"
[06:43:27.248] Using commit id "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" and quality "stable" for server
[06:43:27.253] Install and start server if needed
[06:43:27.257] Checking ssh with "ssh -V"
[06:43:27.331] > O
[06:43:27.332] > penSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[06:43:27.339] Using SSH config file "c:\users\jxlia\.ssh\Known_hosts"
[06:43:27.339] Running script with connection command: ssh -T -D 54036 -F "c:\users\jxlia\.ssh\Known_hosts" "172.16.40.121" bash
[06:43:27.343] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[06:43:27.604] > ]0;C:\WINDOWS\System32\cmd.exe
[06:43:27.604] Got some output, clearing connection timeout
[06:43:27.615] > c:\\users\\jxlia\\.ssh\\Known_hosts line 3: garbage at end of line; "ecdsa-sha2-
> nistp256".
> The process tried to write to a nonexistent pipe.
> 
[06:43:28.895] "install" terminal command done
[06:43:28.896] Install terminal quit with output: nistp256".
[06:43:28.896] Received install output: nistp256".
[06:43:28.898] Failed to parse remote port from server output
[06:43:28.900] Resolver error: Error: 
	at Function.Create (c:\Users\jxlia\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:429193)
	at Object.t.handleInstallOutput (c:\Users\jxlia\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:427836)
	at Object.t.tryInstall (c:\Users\jxlia\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:521703)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\jxlia\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:485356
	at async Object.t.withShowDetailsEvent (c:\Users\jxlia\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:488706)
	at async Object.t.resolve (c:\Users\jxlia\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:486435)
	at async c:\Users\jxlia\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:560057
[06:43:28.906] ------
```

The content of Known_hosts file

```
Host 172.16.40.121
  HostName 172.16.40.121
  User changbing.liao 172.16.40.121 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPykygFAC68lvdKoPt5e7364AVPsogVU2GDiA53YKII8dBf7Qf9J10PsqAaW6Q+QgTt/ZNdVQzEyoaR0z7al6vg=
```

**Comment by roblourens** [comment]
The SSH config goes in `~/.ssh/config`. known_hosts is a different file that is written to by ssh in a different format. You shouldn't update that file manually.
