### ISSUE TITLE
Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 1

### ISSUE THREAD

**Issue by SMores** [microsoft/vscode#137815]
Issue Type: <b>Bug</b>

I can reproduce this consistently in a closed source project; I haven't yet figured out exactly what causes it, but it seems tied to complex inferred Typescript types. In a file that makes heavy use of several layers of inferred conditional types (sample types listed below):

1. Open the file, wait for "Initializing JS/TS language features" to finish
2. Make any change in the file
3. Observe an extension host error in the Log (Remote|Local Extension Host Output panel:

```
[2021-11-24 18:44:38.003] [exthost] [error] Error: <semantic> TypeScript Server Error (4.4.4-sdk)
Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 1, !entry: false
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 1, !entry: false
    at getDocumentRegistryEntry (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:129272:22)
    at Object.releaseDocumentWithKey (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:129348:25)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:156933:46)
    at tryReuseStructureFromOldProgram (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:112175:28)
    at Object.createProgram (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:111691:29)
    at synchronizeHostData (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:156816:26)
    at Proxy.getProgram (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:156948:13)
    at ConfiguredProject.Project.updateGraphWorker (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:161944:53)
    at ConfiguredProject.Project.updateGraph (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:161873:42)
    at ConfiguredProject.updateGraph (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:162855:63)
    at Object.updateProjectIfDirty (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:163378:45)
    at ConfiguredProject.Project.getLanguageService (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:161491:28)
    at IOSession.Session.getEncodedSemanticClassifications (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:167911:32)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:167379:61)
    at /workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:169148:88
    at IOSession.Session.executeWithRequestId (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:169139:28)
    at IOSession.Session.executeCommand (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:169148:33)
    at IOSession.Session.onMessage (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:169174:35)
    at IOSession.onMessage (/workspaces/scoop-oak/.yarn/sdks/typescript/lib/tsserver.js:150:32)
    at Interface.<anonymous> (/workspaces/scoop-oak/.yarn/cache/typescript-patch-d95d140154-bd629ad0da.zip/node_modules/typescript/lib/tsserver.js:171787:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
	at Function.create (/vscode/vscode-server/bin/linux-x64/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/typescript-language-features/dist/extension.js:1:460359)
	at dispatchResponse (/vscode/vscode-server/bin/linux-x64/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/typescript-language-features/dist/extension.js:1:454195)
	at dispatchMessage (/vscode/vscode-server/bin/linux-x64/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/typescript-language-features/dist/extension.js:1:453052)
	at /vscode/vscode-server/bin/linux-x64/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/typescript-language-features/dist/extension.js:1:452537
	at l.fire (/vscode/vscode-server/bin/linux-x64/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at m.onLengthData (/vscode/vscode-server/bin/linux-x64/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/typescript-language-features/dist/extension.js:1:463288)
	at Socket.<anonymous> (/vscode/vscode-server/bin/linux-x64/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/typescript-language-features/dist/extension.js:1:462935)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Accompanying this error log, syntax highlighting and underlining compiler errors break.

Sample of conditional types that seem to be tied to the issue:

```typescript
/**
 * For a given config, return the type of its value.
 *
 * e.g. MetadataFieldValue<typeof slug> === string
 */
export type MetadataFieldValue<Config> = Config extends BaseFieldConfig<string, infer Value>
  ? Value
  : never;

/**
 * For a given config, return the type of its name. This will be a string literal type.
 * If given a string, just return that.
 *
 * e.g. MetadataFieldValue<typeof slug> === 'slug';
 */
export type MetadataFieldName<Config> = Config extends BaseFieldConfig<infer Name, any>
  ? Name
  : Config extends string
  ? Config
  : never;

/**
 * Given a union of field configs and a specific config name (string literal type),
 * return the value type of the config with that name.
 *
 * e.g. MetadataFieldValueFor<'addendums', typeof slug | typeof addendums> === Addendums
 */
export type MetadataFieldValueFor<Name extends string, Config> = Config extends BaseFieldConfig<
  Name,
  infer Type
>
  ? Type
  : never;
```

Before adding these types to the codebase, this file (which was always written completely in typescript) was editable with no issues.

Please let me know if there's more info I can provide; in the meantime I will see if I can make a minimal reproduction in on open source repo to link to this issue!

VS Code version: Code 1.62.1 (Universal) (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:23:14.144Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.47-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|64.00GB (27.29GB free)|
|Process Argv|--crash-reporter-id 0b636e11-a5a0-44e7-b01c-941a143f4290|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js|
|OS|Linux x64 5.10.47-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|15.64GB (5.19GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-drawio|hed|1.6.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
sublime-keybindings|ms-|4.0.10
fish-vscode|sky|0.2.1
vscode-zipfs|arc|2.3.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
autoscrolldown|fox|1.2.1
terraform|has|2.16.0
jsonnet|hep|0.1.0
vscode-docker|ms-|1.18.0
vsliveshare|ms-|1.0.5090
opa|tsa|0.9.0

(1 theme extensions excluded)

</details>

**Comment by SMores** [comment]
I'm realizing that this would likely make more sense in the [microsoft/Typescript](microsoft/Typescript) repo, since it _seems_ to be an issue with `tsserver` (we were able to reproduce with emacs' typescript lsp as well)
