### ISSUE TITLE
New JS files cause completion error

### ISSUE THREAD

**Issue by royaldark** [Microsoft/vscode#13791]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Every time I create a new JS file in my project, when I begin editing it, an error is thrown in the TypeScript console and Intellisense completions fail to work in that file. Restarting VS Code fixes the issue.

Steps to Reproduce:
1. Create project with at least one JS file and Intellisense enabled
2. Create new empty JS source file (ctrl + N, save)
3. Begin typing

**Stack trace:**

```
[Error - 11:39:35 PM] 'completions' request failed with error.
Error processing request. Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:52031:37)
    at IOSession.Session.getCompletions (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51466:53)
    at Session.handlers.ts.createMap._a.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:50859:50)
    at IOSession.Session.executeCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51729:28)
    at IOSession.Session.onMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51746:35)
    at Interface.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:53940:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
```

**jsconfig.json**

```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules/"
    ]
}
```

**Comment by waderyan** [comment]
@royaldark thank you for opening this issue. I cannot see this happening with the latest build (possibly this was an error in 1.6 but has now been fixed). Can you download the [Insiders build](https://code.visualstudio.com/insiders) and try and reproduce on your end? 

Thank you very much!

**Comment by royaldark** [comment]
I am unable to reproduce in 1.7.1, so I'm closing this issue.
