### ISSUE TITLE
Can't sync settings

### ISSUE THREAD

**Issue by noyidoit** [microsoft/vscode#137966]
Issue Type: <b>Bug</b>

Steps:
1. Turn on Settings Sync
2. Sign in & Turn on
3. choose an Signed in account -> vscode says Turning on, and ERROR it is

here's log:
```
[2021-11-27 11:45:43.908] [settingssync] [info] Did reset the local sync state.
[2021-11-27 11:45:46.801] [settingssync] [error] Canceled: Canceled
    at Object.i [as canceled] (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:5:1157)
    at de (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:2852)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:4796
    at Object.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:6:6908)
    at h (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:4509)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:4697
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:4796
    at Object.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:6:6908)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:4727
    at Set.forEach (<anonymous>)
    at p.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:4714)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:5419
    at m.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:1712)
    at MessagePort.W (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:47236)
[2021-11-27 11:45:46.807] [settingssync] [info] Settings: Stopped synchronizing settings.
```

here's console info
```
  ERR Canceled: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Canceled
    at Function.w [as toUserDataSyncError] (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:786:37483)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:786:146610
    at async Object.call (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:786:149662)
    at async C.preview (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:786:149979)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1933:14050
notificationsAlerts.ts:42 Error while turning on Settings Sync. Please check logs for more details.
```

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.11.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics (16 x 2190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|27.31GB (15.11GB free)|
|Process Argv|--unity-launch --crash-reporter-id 588e8d60-7146-4ffc-81d7-15e2895df0d0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
cpptools|ms-|1.7.1
vetur|oct|0.35.0
vim|vsc|1.21.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246:30401890
pythonvs932cf:30404740
vscexrecpromptt2:30404948
vscop804cf:30404767
vscop940:30404999

```

</details>

**Comment by sandy081** [comment]
`choose an Signed in account` - did you pick the account that is signed in already or did you sign in?
Can you also provide the window log?
