### ISSUE TITLE
Redo of rename Java Class name has no effect

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137968]
```
1) vscode API - workspace
       issue #107739 - Redo of rename Java Class name has no effect:
     Error: cannot open fak2e-fs:/k. Detail: Unable to resolve resource fak2e-fs:/k
      at vscode-file://vscode-app/__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2362:75636
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144512&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=41d9f3a8-af10-5350-1c03-229d27a4a1b6&l=594

**Comment by egamma** [comment]
@isidorn might also have insight into this test.

**Comment by alexdima** [comment]
This has to do with using such a pattern:
```
		const file = await createRandomFile('hello');
		const fileName = basename(file.fsPath);
		const newFile = vscode.Uri.parse(file.toString().replace(fileName, `${fileName}2`));
```

The above pattern backfires if the `fileName` is a substring of the scheme e.g. `fak`. That leads to the `newFile` being constructed with an incorrect scheme, which leads to the error we see:
```
No file system provider found for resource 'fak2e-fs:/k'
IGNORING workspace edit {
  name: 'ENOPRO',
  message: "No file system provider found for resource 'fak2e-fs:/k'"
}
```

@bpasero Thank you for reporting this!

@jrieken Has kindly agreed to change this usage together with 2 others from the same file. ❤️
