### ISSUE TITLE
Bug: installing @types/node fails with typescript not implemented error

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#137971]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- 1.59 + including insider..
- OS Version:
ubuntu next

Steps to Reproduce:

1. Install vscode
2. create a typescript project
3. ```import https from 'https'````
4. right click on the https and click install ```@types/node```

you will get https://github.com/microsoft/TypeScript/issues/46932

```
<semantic> TypeScript Server Error (4.4.3)
Not implemented
Error: Not implemented
    at Object.notImplemented [as installPackage] (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:1567:15)
    at TypingsCache.installPackage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160811:39)
    at ConfiguredProject.Project.installPackage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161065:42)
    at applySingleCodeActionCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157139:24)
    at Proxy.applyCodeActionCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157133:125)
    at IOSession.Session.applyCodeActionCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168600:50)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167217:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168871:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168906:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171511:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Insiders is using TypeScript 4.5. Make sure you are using VS Code's version of TypeScript and not your workspace version

**Comment by frank-dspeed** [comment]
@mjbvz there is no nightly ts extension installed and i also verifyed tsdk settings of the user and workspace and every other setting that i know.

I am sure i am using the correct typescript version also my current error shows that 

```
<semantic> TypeScript Server Error (4.4.3)
Not implemented
Error: Not implemented
```

```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Datum: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Betriebssystem: Linux x64 5.11.0-41-lowlatency
```

**Comment by frank-dspeed** [comment]
I will simply close the issue as no one else has trouble
