### ISSUE TITLE
vscode can't work in my linux pc

### ISSUE THREAD

**Issue by afsoe** [microsoft/vscode#137909]
ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Error: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)

**Comment by egamma** [comment]
/needsMoreInfo please provide more details about your Linux setup (distro, etc.). 

Add the info that is inserted when reporting an issue from inside vscode using Help>Report Issue.

**Comment by afsoe** [comment]
Version of VS Code is 1.63.0-insider.
Platform is ubuntu for arm64.
Installed extension  is  python.
When i click button "Run Python File" ,it don't work .
the error showed on bash is:
[301:1126/164536.346326:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Error: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1185:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:699)
    at bindings (/usr/share/code-insiders/resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1316)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:101)
    at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1723)
    at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:3:10695)
    at d (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:10300)
    at Object.errorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:10421)
    at e.triggerErrorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:3:11059)
    at /usr/share/code-insiders/resources/app/out/vs/loader.js:3:10765
    at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1740)
    at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:3:10695)
    at d (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:10300)
    at i._loadModule (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:10430)
    at i._resolve (/usr/share/code-insiders/resources/app/out/vs/loader.js:6:452)
    at i.defineModule (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:6142)
    at i._relativeRequire (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:6828)
    at r (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:9406)
    at M.m (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:32:4111)
    at new Promise (<anonymous>)
    at M (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:32:4091)
    at r._createSpdLogLogger (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:32:4925)
    at new r (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:32:4732)
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:2498
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ie.startup (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:2184) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous2===' ]
}

**Comment by vengelhardt** [comment]
I found this issue : https://stackoverflow.com/questions/43070900/version-glibcxx-3-4-22-not-found

Did it help ?
