### ISSUE TITLE
SmokeTest Fail: Editor: shows correct quick outline:

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138045]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144638&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

**Comment by bpasero** [comment]
The error appears to be not being able to open a file via quick pick:

```
Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:41:19)
      at async Code.waitForElements (/Users/runner/work/1/s/test/automation/out/code.js:145:16)
      at async QuickInput.waitForQuickInputElements (/Users/runner/work/1/s/test/automation/out/quickinput.js:25:9)
      at async QuickAccess.openQuickAccessAndWait (/Users/runner/work/1/s/test/automation/out/quickaccess.js:46:13)
      at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:75:9)
      at async Context.<anonymous> (out/areas/editor/editor.test.js:15:13)
```

The [playwright trace](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144638&view=artifacts&pathAsName=false&type=publishedArtifacts) hints at quick open search never returning anything:
![recording](https://user-images.githubusercontent.com/900690/143874111-962b24bb-8575-4157-b91c-ce2ca43f582c.gif)
