### ISSUE TITLE
TerminalCommandTracker

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138273]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145030&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0130b579-6834-5f43-f91f-f53497a6d032&l=8955

```

  2) Workbench - TerminalCommandTracker
       Commands
         should select to the next and previous commands:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

23 !== 10

      + expected - actual

      -23
      +10
      
      at Context.<anonymous> (file:///Users/runner/work/1/s/out-build/vs/workbench/contrib/terminal/test/browser/terminalCommandTracker.test.js:82:24)

  3) Workbench - TerminalCommandTracker
       Commands
         should select to the next and previous lines & commands:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

13 !== 10

      + expected - actual

      -13
      +10
      
      at Context.<anonymous> (file:///Users/runner/work/1/s/out-build/vs/workbench/contrib/terminal/test/browser/terminalCommandTracker.test.js:105:24)

```

**Comment by bpasero** [comment]
Also:

```
  1) Workbench - TerminalCommandTracker
       Commands
         "before each" hook for "should scroll to the next and previous commands":

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

https://github.com/microsoft/vscode/runs/4388223729?check_suite_focus=true#step:13:8953

**Comment by Tyriar** [comment]
Seems to fail in both GH actions and ADO, on Windows and Mac (at least)

**Comment by Tyriar** [comment]
New failure: https://github.com/microsoft/vscode/runs/4473870728?check_suite_focus=true

The timeout message wasn't hit, new theory is the compute is really slow so the 10 awaits that end up triggering async requests on the renderer take too long and cause the timeout. Changing to a single await to setup the test instead.
