### ISSUE TITLE
Terminal profiles: should set the default profile

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138238]
```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Profiles
           should set the default profile:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:41:19)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:149:16)
      at async QuickInput.waitForQuickInputClosed (/Users/runner/work/1/s/test/automation/out/quickinput.js:28:9)
      at async Terminal.runCommandWithValue (/Users/runner/work/1/s/test/automation/out/terminal.js:73:9)
      at async Context.<anonymous> (out/areas/terminal/terminal-profiles.test.js:35:13)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144921&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab&l=109

**Comment by meganrogge** [comment]
only failed on mac/linux so running locally on mac to see if this is because of the recent change I made (selecting powershell on windows and not providing a value for the others)

**Comment by meganrogge** [comment]
cannot repro the failure locally
