### ISSUE TITLE
TernarySearchTree: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#138284]
https://github.com/microsoft/vscode/runs/4384271749?check_suite_focus=true#step:17:238

**Comment by gabrieldonadel** [comment]
Same here, it's preventing me from using my shortcuts

**Comment by bpasero** [comment]
I have seen this stack a few times, but never understood more about it. @jrieken can you chime in:

```
Cannot read property '1' of undefined: TypeError: Cannot read property '1' of undefined
    at TernarySearchTree._delete (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/map.js:564:67)
    at TernarySearchTree.delete (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/map.js:458:25)
    at vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/platform/files/common/fileService.js:865:57
    at vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/lifecycle.js:130:17
    at Object.dispose (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/functional.js:18:25)
    at dispose (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/lifecycle.js:153:18)
    at dispose (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/lifecycle.js:115:17)
    at EditorService.handleVisibleEditorsChange (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/services/editor/browser/editorService.js:145:45)
    at vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/services/editor/browser/editorService.js:65:70
    at Emitter.fire (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/event.js:435:38)
    at vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/services/editor/browser/editorService.js:112:57
    at Emitter.fire (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/base/common/event.js:435:38)
    at EditorGroupView.doCloseActiveEditor (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:1138:40)
    at EditorGroupView.doCloseAllEditors (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:1380:22)
    at EditorGroupView.closeAllEditors (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:1367:18)
    at async Promise.all (index 2)
    at async CloseAllEditorsAction.doCloseAll (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/browser/parts/editor/editorActions.js:557:13)
    at async Object.triggerAndDisposeAction (vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/common/actions.js:84:17)
    at async vscode-file://vscode-app/Users/runner/work/vscode/vscode/out/vs/workbench/common/actions.js:64:21
```

**Comment by bpasero** [comment]
Wait, but this stack trace did not result in any test failure. 

The actual source location of the type error is:

https://github.com/microsoft/vscode/blob/1492ce2ad07deafe3a3b5f07e078a7ec39388f88/src/vs/base/common/map.ts#L613

Probably an issue with the ternary search tree for the relatively new rebalancing?

**Comment by jrieken** [comment]
Moved to December to get a better understanding of the issue

**Comment by meganrogge** [comment]
not sure how to verify this

**Comment by jrieken** [comment]
This would happen whenever the root of the TST would be removed. Then the rotation to balance would fail. The fix comes with a few unit tests and I believe that's enough to mark it as verified
