### ISSUE TITLE
Restarting JS debugger

### ISSUE THREAD

**Issue by jasonzuvela-wywm** [microsoft/vscode#138377]
Issue Type: <b>Bug</b>

in line with the previous issues I have reported about the JS debugger not finding a session when restarting, I just double tapped the Restart Debugger button and this notification came up:

```
Error processing launch: Error: Ambiguous match found for serviceIdentifier: Symbol(ISourcePathResolver)
	at /home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:465158
	at g (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:465172)
	at y (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:465347)
	at /home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:465881
	at Array.forEach (<anonymous>)
	at /home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:465860
	at Array.forEach (<anonymous>)
	at y (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:465407)
	at Object.t.plan (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:466326)
	at /home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:457512
	at e._get (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:457421)
	at e.getAll (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:456318)
	at t.Binder.getLaunchers (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:1225375)
	at t.Binder._boot (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:1226449)
	at /home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:1224812
	at t.default._onMessage (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:1319102)
	at /home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:1317549
	at i.fire (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:1252302)
	at Socket._handleData (/home/jasonzuvela/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/extensions/ms-vscode.js-debug/src/extension.js:2:1324941)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (3.64GB free)|
|Process Argv|--crash-reporter-id 9d1b4a74-6c23-44d3-9db5-383def926efe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2207)|
|Memory (System)|24.92GB (2.49GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
remote-containers|ms-|0.202.5
remote-wsl|ms-|0.58.5
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
restore-terminals|Eth|1.1.6
vscode-graphql|Gra|0.3.26
vscode-docker|ms-|1.18.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.35.0
prisma|Pri|3.5.0
indenticator|Sir|0.7.0
language-stylus|sys|1.14.1
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246:30401890
pythonvs932cf:30404740
vscop804:30404766
vs360cf:30404996

```

</details>

**Comment by connor4312** [comment]
I wasn't able to reproduce this particular issue, but sessions can 'leak' if I spam the restart button. I think the editor should guard against this.

@roblourens my initial thought is to add a new `Stopping` state to the `State` used in IDebugSession and disable stop/restart commands when the session is in that state. Does that sound reasonable?

**Comment by roblourens** [comment]
Makes sense

**Comment by connor4312** [comment]
This seems resolved with my lifecycle improvements in js-debug https://github.com/microsoft/vscode-js-debug/pull/1619
