### ISSUE TITLE
Cannot exit, onWillShutdown is taking a long time, pending operations: join.closeStorage

### ISSUE THREAD

**Issue by gnowland** [microsoft/vscode#138305]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
    Version: 1.62.3 (Universal)
    Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
    Date: 2021-11-17T07:59:13.865Z
    Electron: 13.5.2
    Chrome: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Darwin x64 19.6.0
- OS Version: macOS Catalina 10.15.7 (19H1519)

Steps to Reproduce:

1. Open VSCode
2. Leave open for some time
3. Click on window close button

Clicking on the close button has no effect. File -> Exit and CTRL+Q do not work as well. This also happens on fresh installation without any extension and anything opened, same as issue #119451.

Window Log:

```
[2021-12-01 16:04:46.583] [renderer3] [error] Socket is closed: Error [ERR_SOCKET_CLOSED]: Socket is closed
	at Socket._writeGeneric (net.js:775:8)
	at Socket._write (net.js:797:8)
	at doWrite (internal/streams/writable.js:377:12)
	at clearBuffer (internal/streams/writable.js:529:7)
	at Socket.Writable.uncork (internal/streams/writable.js:317:7)
	at ClientRequest._flushOutput (_http_outgoing.js:909:10)
	at ClientRequest._flush (_http_outgoing.js:878:22)
	at _http_client.js:325:47
	at callSocketMethod (_http_client.js:834:7)
	at ClientRequest.onSocket (_http_client.js:839:7)
	at Object.onceWrapper (events.js:422:26)
	at ClientRequest.emit (events.js:327:22)
	at tickOnSocket (_http_client.js:778:7)
	at onSocketNT (_http_client.js:817:5)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2021-12-01 16:16:05.142] [renderer3] [error] Error: XHR failed
    at XMLHttpRequest.C.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:24735)
[2021-12-01 16:16:05.144] [renderer3] [error] Error: XHR failed
    at XMLHttpRequest.C.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:24735)
[2021-12-01 16:19:00.573] [renderer3] [warning] [lifecycle] onWillShutdown is taking a long time, pending operations: join.closeStorage
[2021-12-01 16:34:46.167] [renderer3] [error] Socket is closed: Error [ERR_SOCKET_CLOSED]: Socket is closed
	at Socket._writeGeneric (net.js:775:8)
	at Socket._write (net.js:797:8)
	at doWrite (internal/streams/writable.js:377:12)
	at clearBuffer (internal/streams/writable.js:529:7)
	at Socket.Writable.uncork (internal/streams/writable.js:317:7)
	at ClientRequest._flushOutput (_http_outgoing.js:909:10)
	at ClientRequest._flush (_http_outgoing.js:878:22)
	at _http_client.js:325:47
	at callSocketMethod (_http_client.js:834:7)
	at ClientRequest.onSocket (_http_client.js:839:7)
	at Object.onceWrapper (events.js:422:26)
	at ClientRequest.emit (events.js:327:22)
	at tickOnSocket (_http_client.js:778:7)
	at onSocketNT (_http_client.js:817:5)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gnowland** [comment]
Will do. I've also [completely wiping vscode from my machine](https://stackoverflow.com/a/47561948/2764290) and done a fresh install in pursuit of a theory that it is indicative of an underlying permissions issue.

**Comment by bpasero** [comment]
Thanks

**Comment by gnowland** [comment]
OK, I re-installed from scratch and have been running both production and insiders with all extensions on and about the same tabs open. I've been programming in production, insiders sat idle. Production hits the bug, same as before, insiders does not.

**Comment by bpasero** [comment]
Would be interesting to figure out what change fixed this, if any. Are you using VSCode with a remote or is it all local dev?

**Comment by gnowland** [comment]
I would assume the change is that whatever is causing the bug in stable is fixed in insiders? Stable is still throwing the error and unable to close windows after the re-install.

All local dev.

**Comment by bpasero** [comment]
Ok, insiders will transition to stable next week.

**Comment by gnowland** [comment]
Hey I wanted to add to this that when the bug is hit I also cannot OPEN new projects, neither from File > Open..., Open Folder..., or Open Workspace from File...
