### ISSUE TITLE
Tests for Emmet actions on html tags

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138499]
https://github.com/microsoft/vscode/runs/4428941407?check_suite_focus=true#step:15:1116

```
1) Tests for Emmet actions on html tags
       update image css with multiple cursors in css file:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected ... Lines skipped

  '\n' +
    '\t\t.one {\n' +
...
    '\t\t.two {\n' +
    '\t\t\tbackground-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);\n' +
+   '\t\t\theight: 42px;\n' +
+   '\t\t}\n' +
+   '\t\t.three {\n' +
+   '\t\t\tbackground-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);\n' +
+   '\t\t\twidth: 42px;\n' +
-   '\t\t\twidth: 1024px;\n' +
-   '\t\t\theight: 1024px;\n' +
-   '\t\t}\n' +
-   '\t\t.three {\n' +
-   '\t\t\tbackground-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);\n' +
-   '\t\t\theight: 1024px;\n' +
-   '\t\t\twidth: 1024px;\n' +
    '\t\t}\n' +
    '\t'
      + expected - actual

       			height: 1024px;
       		}
       		.two {
       			background-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);
      -			height: 42px;
      +			width: 1024px;
      +			height: 1024px;
       		}
       		.three {
       			background-image: url(https://raw.githubusercontent.com/microsoft/vscode/master/resources/linux/code.png);
      -			width: 42px;
      +			height: 1024px;
      +			width: 1024px;
       		}
       	
      
      at /Users/runner/work/vscode/vscode/extensions/emmet/src/test/updateImageSize.test.ts:58:12
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by rzhao271** [comment]
I plan on skipping that suite for now, and then refactoring it.
