### ISSUE TITLE
No student can install extensions

### ISSUE THREAD

**Issue by bauhausng** [microsoft/vscode#138498]
We are a school and would like to use C# (omnisharp) in Visual Studio code. All students are provided with a server-stored home directory. 

Installed is the system-wide installation of Visual Studio Code. Our problem: No student can install extensions.

Can anyone explain the following error message to me?

Is this a rights issue? The students do not have write permissions in the Visual Studio Code installation directory (C:\Program Files\Microsoft VS Code\...).

```
[2021-12-06 11:20:42.962] [renderer1] [error] ["Extract: EEXIST: file already exists, mkdir 'H:\\vscode\\extensions\\.819a7632-05f1-4909-b81c-aaf7c669f02b\\.debugger\\cs'","    at s.extractAtLocation (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:188875)","    at async s.extractUserExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:185594)","    at async q.extract (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:198974)","    at async q.doRun (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:199612)"]
[2021-12-06 11:20:42.988] [renderer1] [error] EEXIST: file already exists, mkdir 'H:\vscode\extensions\.819a7632-05f1-4909-b81c-aaf7c669f02b\.debugger\cs': Extract: EEXIST: file already exists, mkdir 'H:\vscode\extensions\.819a7632-05f1-4909-b81c-aaf7c669f02b\.debugger\cs'
    at s.extractAtLocation (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:188875)
    at async s.extractUserExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:185594)
    at async q.extract (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:198974)
    at async q.doRun (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:199612)
```

**Comment by sandy081** [comment]
Does all users of this instance share this dir - `H:\vscode\extensions\` ?

Can you please enable log level to trace - `F1 > Set Log Level.. `
Try installing any other extension and share us logs from here - `F1 > Open View... > Log (Shared)`
