### ISSUE TITLE
Smoke test flake: VSCode Smoke Tests (Web) Language Features verifies problems view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138552]
Failed 3 times in last 30 days:

![image](https://user-images.githubusercontent.com/2193314/144920815-d0554ea3-cdb0-48b6-9d86-9347baea91e5.png)

Failure: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=145085&view=results

```
Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 40 seconds.
    at poll (D:\a\1\s\test\automation\out\code.js:41:19)
    at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:145:16)
    at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
    at async QuickAccess.openQuickAccessAndWait (D:\a\1\s\test\automation\out\quickaccess.js:46:13)
    at async QuickAccess.openFile (D:\a\1\s\test\automation\out\quickaccess.js:75:9)
    at async Context.<anonymous> (out\areas\languages\languages.test.js:22:13)
```

@sandy081 re-enabled this in cd97629c4458c05b16a1fd444d21c61295ba2529

**Comment by Tyriar** [comment]
`VSCode Smoke Tests (Web) Language Features verifies quick outline` and `VSCode Smoke Tests (Web) Language Features verifies settings` also failed on these builds

**Comment by bpasero** [comment]
The underlying symptome is that search does not return results in time. I think it is not the smoke test itself that is causing the issue but the fact that a file cannot be opened.

Similar: https://github.com/microsoft/vscode/issues/115244

**Comment by sandy081** [comment]
Marking it as dup of #115244
