### ISSUE TITLE
TS Server fatal error:  Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by replybotadmin** [microsoft/vscode#138646]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.4.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:2064:20)
    at isNodeModulesOrScopedPackageDirectory (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:19715:65)
    at guessDirectorySymlink (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:19703:17)
    at processResolution (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:19692:22)
    at /home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:19683:162
    at Map.forEach (<anonymous>)
    at Object.setSymlinksFromResolutions (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:19683:123)
    at ConfiguredProject.Project.getSymlinkCache (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:161084:35)
    at Object.getSymlinkCache (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:114006:29)
    at Object.host.compilerHost.realpath (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:114071:36)
    at realPath (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:41680:42)
    at Object.resolveTypeReferenceDirective (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:41044:74)
    at /home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:162443:112
    at Object.map (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:455:29)
    at Function.AutoImportProviderProject.getRootFileNames (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:162443:42)
    at Function.AutoImportProviderProject.create (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:162475:38)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:162277:77)
    at ConfiguredProject.Project.updateGraph (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:161700:26)
    at ConfiguredProject.updateGraph (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:162644:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:164368:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:165451:44)
    at /home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:165791:97
    at Object.flatMap (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:165791:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:166949:46)
    at /home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:168871:28)
    at IOSession.Session.executeCommand (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:168880:33)
    at IOSession.Session.onMessage (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:168906:35)
    at Interface.<anonymous> (/home/ubuntu/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/tsserver.js:171511:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-162-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.68GB free)|
|Process Argv|--crash-reporter-id bfbadfd7-f10f-4eaf-9917-ac765db0e74a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ibm.secuvy.com|
|OS|Linux x64 4.15.0-162-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (8 x 2600)|
|Memory (System)|31.41GB (23.33GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
node-snippets|chr|1.3.3
es7-react-js-snippets|dsz|3.1.1
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
JavaScriptSnippets|xab|1.8.0
vscode-postgres|cko|1.1.19
gitlens|eam|11.7.0
sqltools|mtx|0.23.0
vscode-thunder-client|ran|1.9.1
vs-code-prettier-eslint|rve|3.0.4
sap-hana-driver-for-sqltools|SAP|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932cf:30408637
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
