### ISSUE TITLE
Smoke test: timeout fetching code stable

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138659]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146069&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=aaa04083-6c0b-5a33-e907-3d845b07f0b5&l=17

```
  1) "before all" hook in "{root}"

  0 passing (2m)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

The new logging hints to the [`versionReq`](https://github.com/microsoft/vscode/blob/18cba4882d5b6eb8844e848a73dbd6ca282eca47/test/smoke/src/main.ts#L246) call hanging for 120 seconds:

```
[2021-12-08T16:05:15.049Z] Test data: /tmp/vscsmoke
[2021-12-08T16:05:15.049Z] Preparing smoketest setup...
[2021-12-08T16:05:15.067Z] Starting operation 'versionReq... <------
[2021-12-08T16:05:15.067Z] Starting operation 'ensureStableCode...
[2021-12-08T16:07:15.121Z] Starting operation 'rimraf(testDataPath)...
[2021-12-08T16:07:15.123Z] Finished operation 'rimraf(testDataPath)' successfully after 2ms
```

**Comment by joaomoreno** [comment]
Update server was down temporarily.
