### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by HsuHninWai-airitech** [microsoft/vscode#138798]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:57005:22)
    at getPropertyOfType (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:57665:24)
    at resolveESModuleSymbol (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49811:54)
    at getTargetOfNamespaceImport (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:48996:28)
    at getTargetOfAliasDeclaration (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49230:28)
    at resolveAlias (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49275:30)
    at getSymbol (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47833:38)
    at resolveNameHelper (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:48125:34)
    at resolveName (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:48108:20)
    at resolveEntityName (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49447:42)
    at getTargetOfExportSpecifier (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49187:17)
    at getTargetOfAliasDeclaration (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49237:28)
    at resolveAlias (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49275:30)
    at resolveSymbol (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:49265:67)
    at mergeSymbol (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47619:42)
    at /home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47734:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47732:20)
    at mergeSymbol (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47643:21)
    at /home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47734:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47732:20)
    at initializeTypeChecker (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:84991:21)
    at Object.createTypeChecker (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:47390:9)
    at Object.getTypeChecker (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:114385:79)
    at synchronizeHostData (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:159863:21)
    at Object.getProgram (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:159984:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:164998:53)
    at ConfiguredProject.Project.updateGraph (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:164927:42)
    at ConfiguredProject.updateGraph (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:165920:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:167644:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:168727:44)
    at /home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:169067:97
    at Object.flatMap (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:169067:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:170225:46)
    at /home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172158:88
    at IOSession.Session.executeWithRequestId (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172149:28)
    at IOSession.Session.executeCommand (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172158:33)
    at IOSession.Session.onMessage (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:172184:35)
    at Interface.<anonymous> (/home/hsuhninwai/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/extensions/node_modules/typescript/lib/tsserver.js:174789:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (0.31GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/hsuhninwai/kcs-project/kcs-motion-next/web --remote=wsl+Ubuntu --crash-reporter-id 3180d87e-30c6-4b18-b463-30d77850beaa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.78GB (0.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.78GB (0.31GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.13
vue|jcb|0.1.5
Angular2|joh|12.0.0
vscode-peacock|joh|4.0.0
remote-wsl|ms-|0.63.4
debugger-for-chrome|msj|4.13.0
vscode-github|Kni|0.30.7
vuetify-pug-snippet|luc|0.6.0
vetur|oct|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315:30406435
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30405999
vscexrecpromp3t1:30407762

```

</details>

**Comment by hippo2cat** [comment]
error occured at typescript@4.5.2, when i use typescript@4.1.6, everything becomes normal
