### ISSUE TITLE
Can't attach vscode to remote docker container over remote ssh anymore 

### ISSUE THREAD

**Issue by fehrlich** [microsoft/vscode#138735]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.63
- OS Version: Windows 11 x64

Required Extensions: Remote Docker, Remote SSH

Steps to Reproduce:

1. Attach vscode to a remote server running Docker 
2. Try to attach vscode to a running docker container (whitin the remote server) -> get an rejected message

This occurs since the update to 1.63. I got it working again when downgrading to 1.62.3 and uninstall/install Remote Docker and Remote SSH.

**Comment by fehrlich** [comment]
This is the whole output for `Dev container`:
```
 was created)
[1307 ms] Host server: (node:2673181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2673181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1342 ms] Host server: (node:2673181) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[1343 ms] Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[1378 ms] Start: Run in Host: docker inspect --type container /tsm_apptorch_run_74118ff9d231
[1402 ms] Host server: (node:2673181) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:2673181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1425 ms] Host server: (node:2673181) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

and following message is shown:
![grafik](https://user-images.githubusercontent.com/7313884/145380914-868775fd-30a0-4d3f-b474-39b5b2bc3d2c.png)

Maybe worth mentioning: I i click `more actions` and `choose containers` it only shows my local containers and not the remote containers anymore.

**Comment by fehrlich** [comment]
this allready seemed to be reported to the docker remote extension: https://github.com/microsoft/vscode-remote-release/issues/6023
