### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by Serbiaguy96** [microsoft/vscode#138751]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.0-dev.20211208

Hi, my JS/TS extension suddenly stopped working due to this error bellow. I can't tell what happened.

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`c:\Users\lukal\AppData\Roaming\Code\logs\20211209T132012\exthost1\vscode.typescript-language-features\tsserver-log-TomLdY\tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:57040:22)
    at getPropertyOfType (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:57700:24)
    at resolveESModuleSymbol (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49830:54)
    at getTargetOfNamespaceImport (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49015:28)
    at getTargetOfAliasDeclaration (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49249:28)
    at resolveAlias (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49294:30)
    at getSymbol (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47849:38)
    at resolveNameHelper (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:48142:34)
    at resolveName (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:48125:20)
    at resolveEntityName (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49466:42)
    at resolveEntityName (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49474:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49426:24)
    at getTargetOfImportEqualsDeclaration (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:48878:28)
    at getTargetOfAliasDeclaration (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49245:28)
    at resolveAlias (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49294:30)
    at resolveSymbol (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:49284:67)
    at mergeSymbol (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47635:42)
    at c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47750:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47748:20)
    at mergeSymbol (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47659:21)
    at c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47750:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47748:20)
    at mergeModuleAugmentation (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47764:17)
    at initializeTypeChecker (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:85139:25)
    at Object.createTypeChecker (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:47406:9)
    at Object.getTypeChecker (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:114570:79)
    at synchronizeHostData (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:160250:21)
    at Proxy.getProgram (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:160371:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:165386:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:165315:42)
    at ConfiguredProject.updateGraph (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:166308:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:168032:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:169115:44)
    at c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:169455:97
    at Object.flatMap (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:502:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:169455:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:170613:46)
    at c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:172546:88
    at IOSession.Session.executeWithRequestId (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:172537:28)
    at IOSession.Session.executeCommand (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:172546:33)
    at IOSession.Session.onMessage (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:172572:35)
    at Interface.<anonymous> (c:\Users\lukal\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211208\node_modules\typescript\lib\tsserver.js:175177:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.14GB free)|
|Process Argv|--crash-reporter-id 8a60c245-bb29-4391-8e96-2b2ad7649c94|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
cypress-snippets|and|1.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
codespaces|Git|1.4.1
vscode-styled-components|jpo|1.6.6
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.209.3
vscode-typescript-next|ms-|4.6.20211208
material-icon-theme|PKi|4.11.0
vscode-thunder-client|ran|1.9.1
vscode-yaml|red|1.2.2
vscode-cy-helper|She|1.2.2
ReactSnippetsStandard|Tim|1.1.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by rbelando** [comment]
I had the same issue. I don't know what's wrong

workaround:
Remove the 1.63 version and install the 1.62.3 and the problem is gone.

**Comment by Serbiaguy96** [comment]
> 

Thanks for the fast response! I tried to remove node modules and install them again...looks like that fixed my problem.

**Comment by Serbiaguy96** [comment]
Removing node_modules and yarn.lock file and install them again with yarn fixed my problem.
