### ISSUE TITLE
Error: Encountered errors while disposing of store. Errors: [TypeError: d.dispose is not a function, TypeError: d.dispose is not a function]

### ISSUE THREAD

**Issue by Deroc-z** [microsoft/vscode#138804]
OS：macOS Monterey 12.0.1
vs code：version 1.63

[2021-12-10 10:33:29.693] [exthost] [error] Error: Encountered errors while disposing of store. Errors: [TypeError: d.dispose is not a function, TypeError: d.dispose is not a function]
    at f (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:14:5037)
    at v._deactivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:11648)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:10061
    at Array.map (<anonymous>)
    at v.deactivateAll (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:10049)
    at p.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:735)
    at r (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:36400)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)

**Comment by jrieken** [comment]
This seems to originate from here: https://github.com/microsoft/vscode/blob/9fd6ee7095e76a304556c06bbef16fc4f05cf697/src/vs/workbench/api/common/extHostExtensionService.ts#L295. Likely an extension that something non-disposable into the disposable store. 

@Deroc-z Can you attach the list of extension you are using. Also, if this reproduces reliably try bisecting the extension like so: 

* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by alexdima** [comment]
I've pushed a change to also log the extension id that is causing the exception.
