### ISSUE TITLE
Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\main'

### ISSUE THREAD

**Issue by Bluscream** [microsoft/vscode#138893]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: can't check without it starting
- OS Version: win10

Steps to Reproduce:

1. start vs code
2. not profit

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\main'
    at Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:261:863)
    at Object.<anonymous> (electron/js2c/browser_init.js:197:3342)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:197:3586)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:35:9)

[OK]
```

**Comment by gjsjohnmurray** [comment]
Maybe an antivirus product removed part of VS Code.

**Comment by mjbvz** [comment]
Yes try re-installing. Your current install has become corrupted somehow. Often times misbehaving antivirus programs can cause this
