### ISSUE TITLE
Search Browser Smoke Test failure

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#138841]
Hit this smoke test failure with the PR https://github.com/microsoft/vscode/pull/138793

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146295&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5

```

 1) VSCode Smoke Tests (Web)
       Search
         dismisses result & checks for correct result number:
     Error: Timeout: get text content '.search-view .messages' after 1 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForTextContent (D:\a\1\s\test\automation\out\code.js:168:16)
      at async Search.waitForNoResultText (D:\a\1\s\test\automation\out\search.js:99:9)
      at async retry (D:\a\1\s\test\automation\out\search.js:18:13)
      at async Search.clearSearchResults (D:\a\1\s\test\automation\out\search.js:33:9)
      at async Search.searchFor (D:\a\1\s\test\automation\out\search.js:49:9)
      at async Context.<anonymous> (out\areas\search\search.test.js:45:13)

  2) VSCode Smoke Tests (Web)
       Search
         replaces first search result with a replace term:
     Error: Timeout: get text content '.search-view .messages' after 1 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForTextContent (D:\a\1\s\test\automation\out\code.js:168:16)
      at async Search.waitForNoResultText (D:\a\1\s\test\automation\out\search.js:99:9)
      at async retry (D:\a\1\s\test\automation\out\search.js:18:13)
      at async Search.clearSearchResults (D:\a\1\s\test\automation\out\search.js:33:9)
      at async Search.searchFor (D:\a\1\s\test\automation\out\search.js:49:9)
      at async Context.<anonymous> (out\areas\search\search.test.js:51:13)

  3) VSCode Smoke Tests (Web)
       Quick Open
         quick open search produces correct result:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:184:16)
      at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
      at async QuickAccess.openQuickAccessAndWait (D:\a\1\s\test\automation\out\quickaccess.js:46:13)
      at async Context.<anonymous> (out\areas\search\search.test.js:77:13)

  4) VSCode Smoke Tests (Web)
       Editor
         shows correct quick outline:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:184:16)
      at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
      at async QuickAccess.openQuickAccessAndWait (D:\a\1\s\test\automation\out\quickaccess.js:46:13)
      at async QuickAccess.openFile (D:\a\1\s\test\automation\out\quickaccess.js:74:9)
      at async Context.<anonymous> (out\areas\editor\editor.test.js:15:13)

```

Here is a screenshot from the first test, it looks like the search operation gets canceled:

![image](https://user-images.githubusercontent.com/5047891/145560432-166adda8-3fc0-48ec-95bf-9448808cca13.png)

**Comment by roblourens** [comment]
I think I fixed the first two. The others have an open issue.
