### ISSUE TITLE
Terminal Tabs should update color of the tab in the tabs list

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139081]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146758&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=98

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Tabs
           should update color of the tab in the tabs list:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForActiveElement (D:\a\1\s\test\automation\out\code.js:192:9)
      at async QuickInput.waitForQuickInputOpened (D:\a\1\s\test\automation\out\quickinput.js:22:9)
      at async Terminal.runCommandWithValue (D:\a\1\s\test\automation\out\terminal.js:75:9)
      at async Context.<anonymous> (out\areas\terminal\terminal-tabs.test.js:33:13)
```

**Comment by Tyriar** [comment]
Changing the color happens before the icon shows up:

![image](https://user-images.githubusercontent.com/2193314/146043334-b532aced-bb88-46db-967d-eaa2225c3348.png)

After splitting the terminal we should wait for it to initialize (ie. waitForTerminal)
