### ISSUE TITLE
Notebook showNotebookDocument / Active/Visible Editor tests failures

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139078]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146750&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=412

```
1) Notebook Editor
       showNotebookDocment:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.editor.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Notebook Editor
       Active/Visible Editor:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.editor.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

```

**Comment by bpasero** [comment]
I think every Windows integration test run (Firefox) is failing:

```
Notebook Editor
    1) showNotebookDocment
    - notebook editor has viewColumn
    - Opening a notebook should fire activeNotebook event changed only once
Playwright ERROR: HTTP status 504 for https://a2382879-790f-4a81-9c4e-a1e73efae79c.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/index.html?id=81a414af-caa4-4826-8318-043c5162477a&swVersion=3&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=http%3A%2F%2Flocalhost%3A9888&purpose=notebookRenderer
    2) Active/Visible Editor
    √ Notebook Editor Event - onDidChangeVisibleNotebookEditors on open/close (9084ms)
Playwright ERROR: HTTP status 504 for https://470909a4-736f-4b91-8135-17ab3317fd45.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/index.html?id=5603453b-0566-4462-8202-c8fd2e4b914d&swVersion=3&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=http%3A%2F%2Flocalhost%3A9888&purpose=notebookRenderer
    3) Notebook Editor Event - onDidChangeVisibleNotebookEditors on two editor groups
  Notebook API tests
    - correct cell selection on undo/redo of cell creation
Playwright ERROR: HTTP status 504 for https://feba333d-c20a-45e9-975c-c1390f069e95.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/main.js
Request Failed https://feba333d-c20a-45e9-975c-c1390f069e95.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/main.js NS_ERROR_CORRUPTED_CONTENT
    4) editor editing event
Playwright ERROR: HTTP status 504 for https://851b48b9-17f3-45e5-85dc-5004cbddff10.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/main.js
Request Failed https://851b48b9-17f3-45e5-85dc-5004cbddff10.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/main.js NS_ERROR_CORRUPTED_CONTENT
    5) edit API batch edits
    √ edit API batch edits undo/redo (2468ms)
Playwright ERROR: HTTP status 504 for https://4e05962c-b6b5-46ff-9e9c-65faf01b0a36.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/main.js
Request Failed https://4e05962c-b6b5-46ff-9e9c-65faf01b0a36.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/main.js NS_ERROR_CORRUPTED_CONTENT
    6) #98841, initialzation should not emit cell change events.
Playwright ERROR: HTTP status 504 for https://c0831949-8b55-4c25-8bf6-524e5eb2385d.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/index.html?id=596bba91-cf8c-4f5c-91ab-b3bdcac3573a&swVersion=3&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=http%3A%2F%2Flocalhost%3A9888&purpose=notebookRenderer
    7) notebook open
Playwright ERROR: HTTP status 504 for https://dc69b307-aba8-49f0-b1ae-c1f22bbe1ec3.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/index.html?id=bdd5f0ea-268d-453c-9097-9f4bf24eec6e&swVersion=3&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=http%3A%2F%2Flocalhost%3A9888&purpose=notebookRenderer
    8) notebook cell actions
Playwright ERROR: HTTP status 504 for https://c47008fc-faa7-4cbf-9175-41d858c394c7.vscode-webview.net/insider/69df0500a8963fc469161c038a14a39384d5a303/out/vs/workbench/contrib/webview/browser/pre/fake.html?id=567871a0-8f5a-4888-956e-501289625e9d
```

Maybe related to a webview change @mjbvz

**Comment by bpasero** [comment]
Skipped via https://github.com/microsoft/vscode/commit/bb39ae82cfdea744117aca693691a5ec13390036#diff-d5db4d2e295f803a58c5e7babea3494703197438818dba084d398f6d7f4ab5b8R47

**Comment by rebornix** [comment]
The function has been tested by multiple tests so I'm going to remove this skipped test.

**Comment by joyceerhl** [comment]
Reopening as these just failed on main: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=182533&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9bc48eac-eb66-52c8-7250-d6490c5f3a15&l=409

**Comment by mjbvz** [comment]
Closing this as out of date
