### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted&TS Server fatal error:  Cannot read property 'flags' of undefined。

### ISSUE THREAD

**Issue by EscaRgotsZy** [microsoft/vscode#139252]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57011:22)
    at getPropertyOfType (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57671:24)
    at resolveESModuleSymbol (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49817:54)
    at getTargetOfNamespaceImport (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49236:28)
    at resolveAlias (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at getSymbol (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47838:38)
    at resolveNameHelper (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48131:34)
    at resolveName (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48114:20)
    at resolveEntityName (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49453:42)
    at getTargetOfAliasLikeExpression (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49210:29)
    at getTargetOfExportAssignment (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49199:28)
    at getTargetOfAliasDeclaration (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49246:28)
    at resolveAlias (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49271:67)
    at resolveExternalModuleSymbol (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49763:36)
    at getTargetOfNamespaceExportDeclaration (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49186:28)
    at getTargetOfAliasDeclaration (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49248:28)
    at resolveAlias (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49271:67)
    at mergeSymbol (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47624:42)
    at e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47737:20)
    at initializeTypeChecker (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:85010:21)
    at Object.createTypeChecker (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47395:9)
    at Object.getTypeChecker (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114404:79)
    at synchronizeHostData (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159898:21)
    at Object.getProgram (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168762:44)
    at e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:97
    at Object.flatMap (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170260:46)
    at e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> (e:\Vscode\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by EscaRgotsZy** [comment]
which issue？
