### ISSUE TITLE
Notebooks inserts/edits code cell

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139216]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147018&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d&l=73

```
1) VSCode Smoke Tests (Electron)
       Notebooks
         inserts/edits code cell:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:65:19)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:188:16)
      at async QuickInput.waitForQuickInputClosed (/Users/runner/work/1/s/test/automation/out/quickinput.js:28:9)
      at async QuickInput.selectQuickInputElement (/Users/runner/work/1/s/test/automation/out/quickinput.js:37:13)
      at async QuickAccess.runCommand (/Users/runner/work/1/s/test/automation/out/quickaccess.js:84:9)
      at async Notebook.openNotebook (/Users/runner/work/1/s/test/automation/out/notebook.js:15:9)
      at async Context.<anonymous> (out/areas/notebook/notebook.test.js:26:13)

```

**Comment by bpasero** [comment]
Also:

```
1) VSCode Smoke Tests (Electron)
       Notebooks
         moves focus in and out of output:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForActiveElement (D:\a\1\s\test\automation\out\code.js:192:9)
      at async QuickInput.waitForQuickInputOpened (D:\a\1\s\test\automation\out\quickinput.js:22:9)
      at async QuickInput.selectQuickInputElement (D:\a\1\s\test\automation\out\quickinput.js:31:9)
      at async QuickAccess.runCommand (D:\a\1\s\test\automation\out\quickaccess.js:84:9)
      at async Notebook.focusFirstCell (D:\a\1\s\test\automation\out\notebook.js:24:9)
      at async Notebook.openNotebook (D:\a\1\s\test\automation\out\notebook.js:17:9)
      at async Context.<anonymous> (out\areas\notebook\notebook.test.js:52:13)

  2) VSCode Smoke Tests (Electron)
       Notebooks
         cell action execution:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForActiveElement (D:\a\1\s\test\automation\out\code.js:192:9)
      at async QuickInput.waitForQuickInputOpened (D:\a\1\s\test\automation\out\quickinput.js:22:9)
      at async QuickInput.selectQuickInputElement (D:\a\1\s\test\automation\out\quickinput.js:31:9)
      at async QuickAccess.runCommand (D:\a\1\s\test\automation\out\quickaccess.js:84:9)
      at async Notebook.insertNotebookCell (D:\a\1\s\test\automation\out\notebook.js:56:13)
      at async Context.<anonymous> (out\areas\notebook\notebook.test.js:61:13)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147020&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725&l=68

**Comment by rebornix** [comment]
@roblourens It seems we can't find the command contributed by the extension, which is weird.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/876920/146239423-e68ba652-246c-4a55-a822-18c734630274.png">

**Comment by rebornix** [comment]
I wonder if the output focus issue is the same the execution one. From the screenshot, there is no output generated from the first cell. (related fix we did before https://github.com/microsoft/vscode/issues/113882 )

**Comment by roblourens** [comment]
![cell_action_execution](https://user-images.githubusercontent.com/323878/146282908-733d292d-0089-43fc-814e-d25281b943f8.png)
![moves_focus_in_and_out_of_output](https://user-images.githubusercontent.com/323878/146282982-b4002168-7075-4b6f-9a09-93aaf5267757.png)

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/146617282-1e03042a-4a96-4607-ae74-d55a06aa2dec.png)

This is weird that the content on disk somehow changes.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/139672
