### ISSUE TITLE
Notebooks moves focus in and out of output

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139268]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147037&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725&l=68

```
1) VSCode Smoke Tests (Electron)
       Notebooks
         moves focus in and out of output:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForActiveElement (D:\a\1\s\test\automation\out\code.js:192:9)
      at async QuickInput.waitForQuickInputOpened (D:\a\1\s\test\automation\out\quickinput.js:22:9)
      at async QuickInput.selectQuickInputElement (D:\a\1\s\test\automation\out\quickinput.js:31:9)
      at async QuickAccess.runCommand (D:\a\1\s\test\automation\out\quickaccess.js:84:9)
      at async Notebook.focusFirstCell (D:\a\1\s\test\automation\out\notebook.js:24:9)
      at async Notebook.openNotebook (D:\a\1\s\test\automation\out\notebook.js:17:9)
      at async Context.<anonymous> (out\areas\notebook\notebook.test.js:52:13)
```

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/139672
