### ISSUE TITLE
vscode API - debug - start debugging failure fails when a JS file is added

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139205]
```
1) vscode API - debug
       start debugging failure:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\vscode-api-tests\out\singlefolder-tests\debug.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://github.com/microsoft/vscode/runs/4534695229?check_suite_focus=true#step:18:413

It seems to me this started happening after my commit https://github.com/microsoft/vscode/commit/8f7589750a2ca4872c1fe65ddbb0b40fbb4795dd. That commit adds a new API test that ends up creating a new file `far-copy.js` in the workspace.

**Comment by bpasero** [comment]
I cannot reproduce, but pushed a change to not add a `.js` file to the workspace but a file with `.txt`, maybe debug is actually falling over the JS file which is empty.

**Comment by bpasero** [comment]
Ok the test is no longer failing, so it is probably dependent on the files in the test workspace. I leave it up to you whether the test should be made more robust 👍
