### ISSUE TITLE
Notebook Editor Event - onDidChangeVisibleNotebookEditors on two editor groups

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139266]
https://github.com/microsoft/vscode/runs/4541821400?check_suite_focus=true#step:18:365

```
1) Notebook Editor
       Notebook Editor Event - onDidChangeVisibleNotebookEditors on two editor groups:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\vscode-api-tests\out\singlefolder-tests\notebook.editor.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by rebornix** [comment]
We have recently turned on all tests and let's keep an eye on if this still fails.
