### ISSUE TITLE
Notebooks moves focus in and out of output / cell action execution

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139270]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147117&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725&l=73

```
 1) VSCode Smoke Tests (Electron)
       Notebooks
         moves focus in and out of output:
     Error: Timeout: is active element 'webview, .webview' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForActiveElement (D:\a\1\s\test\automation\out\code.js:192:9)
      at async Notebook.focusInCellOutput (D:\a\1\s\test\automation\out\notebook.js:64:9)
      at async Context.<anonymous> (out\areas\notebook\notebook.test.js:54:13)

  2) VSCode Smoke Tests (Electron)
       Notebooks
         cell action execution:
     Error: Timeout: get element '.notebook-editor .monaco-list-row.focused' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForElement (D:\a\1\s\test\automation\out\code.js:188:16)
      at async Notebook.openNotebook (D:\a\1\s\test\automation\out\notebook.js:16:9)
      at async Context.<anonymous> (out\areas\notebook\notebook.test.js:60:13)
```

**Comment by bpasero** [comment]
Pushed a change to skip them, given more failures:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147191&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=69

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147193&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=69
