### ISSUE TITLE
Browser integration test failure: provideCellStatusBarItems called on metadata change

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#139308]
Please see https://github.com/microsoft/vscode/runs/4550160925?check_suite_focus=true#step:16:563

```
  222 passing (3m)
  67 pending
  1 failing
  1) statusbar
       provideCellStatusBarItems called on metadata change:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:131:11)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/126371#issuecomment-994185142
