### ISSUE TITLE
provideCellStatusBarItems called on metadata change

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139324]
```
 1) statusbar
       provideCellStatusBarItems called on metadata change:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:131:11)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by bpasero** [comment]
Skipped via https://github.com/microsoft/vscode/commit/f2f509ba614c1c11ea5f3d2b69aa191cddef0b81

**Comment by roblourens** [comment]
Same error as we are looking at in https://github.com/microsoft/vscode/issues/126371#issuecomment-994185142
