### ISSUE TITLE
Auto replies should automatically reply to a custom entry

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139349]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147273&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=500500fc-d3cc-5138-3a2a-6935e05fea33&l=97

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Input
           Auto replies
             should automatically reply to a custom entry:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:65:19)
      at async Code.waitForTerminalBuffer (/__w/1/s/test/automation/out/code.js:200:9)
      at async Terminal.waitForTerminalText (/__w/1/s/test/automation/out/terminal.js:192:13)
      at async Context.<anonymous> (out/areas/terminal/terminal-input.test.js:33:17)
```

**Comment by bpasero** [comment]
I have set it back to `itSkipOnFail`

**Comment by Tyriar** [comment]
Thanks 👍

**Comment by Tyriar** [comment]
Tracking in https://github.com/microsoft/vscode/issues/139083
