### ISSUE TITLE
Terminal should automatically reply to default "Terminate batch job

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139353]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147307&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=500500fc-d3cc-5138-3a2a-6935e05fea33&l=102

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Input
           Auto replies
             should automatically reply to default "Terminate batch job (Y/N)":
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:65:19)
      at async Code.waitForTerminalBuffer (/__w/1/s/test/automation/out/code.js:200:9)
      at async Terminal.waitForTerminalText (/__w/1/s/test/automation/out/terminal.js:192:13)
      at async Context.<anonymous> (out/areas/terminal/terminal-input.test.js:28:17)

```

**Comment by bpasero** [comment]
Skip on fail via https://github.com/microsoft/vscode/commit/7141436baa709c89c947bc253280bdf77a0f4d9d

**Comment by Tyriar** [comment]
Fixed in the other issue tracking this suite
