### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by lfriveraco** [microsoft/vscode#139428]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.0-dev.20211216

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_2 (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:167591:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:167599:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:169265:26)
    at /Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:169539:97
    at Object.flatMap (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:502:25)
    at ProjectService.applyChangesInOpenFiles (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:169539:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:170697:46)
    at /Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:172630:88
    at IOSession.Session.executeWithRequestId (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:172621:28)
    at IOSession.Session.executeCommand (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:172630:33)
    at IOSession.Session.onMessage (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:172656:35)
    at Interface.<anonymous> (/Users/lfriveraco/.vscode/extensions/ms-vscode.vscode-typescript-next-4.6.20211216/node_modules/typescript/lib/tsserver.js:175261:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:13.580Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 8, 9|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id f41fdc59-a51e-4d11-8749-3b2ace402021|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
ruby-and-rails-snippets|Cja|1.0.0
codestream|Cod|12.4.0
vscode-ruby-test-adapter|con|0.9.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-graphql|Gra|0.3.41
ruby|gro|0.1.0
vscode-test-explorer|hbe|2.21.1
ruby-linter|hoo|1.0.0
endwise|kai|1.5.1
rspec-snippets|kar|0.0.4
vscode-codemetrics|kis|1.24.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.209.6
test-adapter-converter|ms-|0.1.5
vscode-typescript-next|ms-|4.6.20211216
angular-console|nrw|17.13.3
prisma|Pri|3.6.0
ruby|reb|0.28.1
rails-snippets|Ven|0.5.0
simple-ruby-erb|vor|0.2.1
vscode-wakatime|Wak|17.1.0
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by Madvinking** [comment]
same with all versions of typescript 4.5 (4.5.2, 4.5.3, 4.5.4)
