### ISSUE TITLE
CellBreakpoints: model index out of range -1

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#139541]
```
Error: model index out of range -1 
at s._assertIndex (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1190:32090) 
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1190:21099 
at Array.map (<anonymous>) 
at s._doApplyEdits (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1190:20988) 
at s.applyEdits (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1190:20631) 
at v.editIsPaused (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1913:19451) 
at v.onDidChangeCallStack (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1913:19200) 
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1913:18814 
at o.fire (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:69:1712) 
at P.clearThreads (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1728:13379) 
at P.shutdown (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1739:29685) 
at P.onDidExitAdapter (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1739:29379) 
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1739:29237 
at o.fire (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:69:1712) 
at a.fireAdapterExitEvent (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1002:35615) 
at a.stopAdapter (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1002:35321) 
at runMicrotasks (<anonymous>) 
at processTicksAndRejections (internal/process/task_queues.js:93:5) 

```

We are using `handle` for updating cell internal metadata but the cell no longer exists anymore. We may want to filter out deleted cells when applying edits on the notebook text model.

**Comment by rebornix** [comment]
Pushed temporary fix to avoid flooding the error telemetry, better fix should be updating `this._pausedCells` at the same time.

**Comment by roblourens** [comment]
Should be fixed with execution changes

**Comment by roblourens** [comment]
No verification needed
