### ISSUE TITLE
$updateExecutions cell not found

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#139555]
Error from telemetry, it seems the cell no longer exists but we still attempt to update its execution status.

```
Error: Cell not found: 1 
at I.update (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1190:88411) 
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1499:27428 
at Array.forEach (<anonymous>) 
at v.$updateExecutions (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1499:27348) 
at u._doInvokeHandler (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1506:13113) 
at u._invokeHandler (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1506:12797) 
at u._receiveRequest (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1506:11459) 
at u._receiveOneMessage (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1506:10336) 
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:1506:8233 
at s.fire (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:69:1712) 
at r.fire (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:85:19622) 
at d._receiveMessage (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:85:24203) 
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:85:21737 
at s.fire (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:69:1712) 
at acceptChunk (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:85:16453) 
at vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:85:15583 
at Socket.N (vscode-file://vscode-app/out/vs/workbench/workbench.desktop.main.js:2989:8466) 
at Socket.emit (events.js:315:20) 
at addChunk (internal/streams/readable.js:309:12) 
at readableAddChunk (internal/streams/readable.js:284:9) 
at Socket.Readable.push (internal/streams/readable.js:223:10) 
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) 
```

**Comment by roblourens** [comment]
This can happen as a result of normal usage when deleting executing cells. It's all different in my execution refactor branch though.

**Comment by roblourens** [comment]
This should be fixed with the new execution code
