### ISSUE TITLE
Smoke test flake: Data Loss (insiders -> insiders): verifies that auto save triggers on shutdown:

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139647]
This test seemed to fail waiting for the remote connection to be established.

```
  1 failing

  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies that auto save triggers on shutdown:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/test/smoke/out/main.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

```
[2021-12-22T14:09:20.745Z] getElements .monaco-workbench
[2021-12-22T14:09:20.972Z] getElements .monaco-workbench .statusbar-item[id="status.host"]
[2021-12-22T14:10:18.693Z] 
[2021-12-22T14:10:18.693Z] >>> !!! FAILURE !!! Test end: 'verifies that auto save triggers on shutdown' !!! FAILURE !!! <<<
```

**Comment by bpasero** [comment]
This indicates a timeout in checking for remote being connected. I will add more logging for this case.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/b2e79a699f11d501c39bb778cdaeefae51de0afe
