### ISSUE TITLE
TypeError: arg is not iterable

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139631]
```
[89164:1222/115023.156687:INFO:CONSOLE(48)] "TypeError: arg is not iterable
	at dispose (/Users/bpasero/Development/Microsoft/monaco/extensions/github/out/util.js:14:34)
	at /Users/bpasero/Development/Microsoft/monaco/extensions/github/out/extension.js:78:36
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:464:38)
	at ExtensionDescriptionRegistry.deltaExtensions (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/extensionDescriptionRegistry.js:70:31)
	at ExtHostExtensionService.$deltaExtensions (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostExtensionService.js:588:28)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadExtensionService.js (48)
```

Found this running out of sources with a fresh user data dir

//cc @alexr00 @TylerLeonhardt

**Comment by bpasero** [comment]
Seems to be from:

https://github.com/microsoft/vscode/blob/ffda3a18cc91411bd11396b62396f7ccc5d04388/extensions/github/src/util.ts#L8-L16

**Comment by TylerLeonhardt** [comment]
github -> @joaomoreno 
github-authentication -> @TylerLeonhardt

**Comment by bpasero** [comment]
This is our number 1 and 2 error reported:

![image](https://user-images.githubusercontent.com/900690/148192337-60929a7b-32a2-4192-88f9-778bade365b4.png)

**Comment by joaomoreno** [comment]
**Verification:**

1. Open workbench, with devtools
2. Disable built-in git extension
3. Reload
4. Enable git extension

There should be no error in devtools
