### ISSUE TITLE
Notebooks  inserts/edits code cell

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139672]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147845&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=f99521cb-b554-56f1-45de-e2bc176b0ad3&l=72

```
  1) VSCode Smoke Tests (Electron)
       Notebooks
         inserts/edits code cell:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForElement (D:\a\1\s\test\automation\out\code.js:184:16)
      at async QuickInput.waitForQuickInputClosed (D:\a\1\s\test\automation\out\quickinput.js:32:9)
      at async QuickInput.selectQuickInputElement (D:\a\1\s\test\automation\out\quickinput.js:41:13)
      at async QuickAccess.runCommand (D:\a\1\s\test\automation\out\quickaccess.js:146:9)
      at async Notebook.openNotebook (D:\a\1\s\test\automation\out\notebook.js:15:9)
      at async Context.<anonymous> (out\areas\notebook\notebook.test.js:26:13)
```

Screenshot reveals that the command cannot be found? Is there a missing extension activation?

![inserts_edits_code_cell](https://user-images.githubusercontent.com/900690/147201186-710dac0f-dd5b-41d5-a787-8f77b4b25787.png)

**Comment by bpasero** [comment]
Skipped via https://github.com/microsoft/vscode/commit/b2e9e87c2e17ed9d1b8cc70068623edd013c2b1b, seeing more failures:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147869&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9&l=74

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147871&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=fff0fe4e-512d-573e-9d0b-0e9f3e677ab7&l=75

**Comment by roblourens** [comment]
Just a couple weird things between https://github.com/microsoft/vscode/issues/140575 and this issue. The before/after hooks were failing, even though these tests only use the generic before hook, and nothing unusual in the after. 

I think the issue in the screenshot above is probably due to the extension failing to be installed, or failing to activate. I also don't know why that would happen. Installing the test notebook extension works the same as the test resolver. I want to reenable these and see what happens.

**Comment by roblourens** [comment]
The error in the screenshot still happens on Linux, and I can actually repro this on my Linux machine. I think that we open a vscode window and immediately search for a command that comes from an extension, and the command palette does not guarantee that all extensions will be loaded before showing results. If I dismiss the command palette and try again, the command shows up.

@bpasero anything I can wait on for when all extensions are loaded? Or should I add a retry to the command palette for this? I think that would do it for us.

**Comment by roblourens** [comment]
Now that an ipynb serializer is built in, maybe we could actually get rid of the custom extension and open some .ipynb file.

Can we add a .ipynb file to https://github.com/microsoft/vscode-smoketest-express?

**Comment by bpasero** [comment]
Yes feel free to add a new file to the smoke test, but keep in mind that this might need changes to other tests that e.g. count the number of files in the explorer.

**Comment by roblourens** [comment]
> Good catch with the fact that the command might only come in later, I thought we had something to wait on extensions load, but maybe not for smoke tests...

I thought that too but apparently not.

Got one PR to add a .ipynb to the smoketest repo: https://github.com/microsoft/vscode-smoketest-express/pull/11 I tested that it doesn't break the search tests or any others.

And another to enable tests and delete the extension (gotta fix the repo url, I'm watching the CI https://github.com/microsoft/vscode/pull/159521))

**Comment by roblourens** [comment]
@mjbvz The notebook editor is failing to load in the smoketest on Linux. Works locally. Some of the last output looks like this

```
[2022-08-30 22:51:25.205] [renderer1] [debug] Webview(5fc9dd96-e51f-4229-b873-0ef95905d5ed): will update content
[2022-08-30 22:51:25.280] [renderer1] [debug] Webview(5fc9dd96-e51f-4229-b873-0ef95905d5ed): webview ready
[2022-08-30 22:51:25.356] [renderer1] [trace] MainThreadTimeline#emitChangeEvent: id=git-history, uri=undefined
[2022-08-30 22:51:25.414] [renderer1] [debug] loadLocalResource - begin. requestUri=file:///mnt/vss/_work/1/s/out/vs/loader.js
[2022-08-30 22:51:25.414] [renderer1] [debug] loadLocalResource - found resource to load. requestUri=file:///mnt/vss/_work/1/s/out/vs/loader.js, resourceToLoad=file:///mnt/vss/_work/1/s/out/vs/loader.js
[2022-08-30 22:51:25.431] [renderer1] [debug] loadLocalResource - begin. requestUri=file:///mnt/vss/_work/1/s/extensions/markdown-language-features/notebook-out/index.js
[2022-08-30 22:51:25.431] [renderer1] [debug] loadLocalResource - found resource to load. requestUri=file:///mnt/vss/_work/1/s/extensions/markdown-language-features/notebook-out/index.js, resourceToLoad=file:///mnt/vss/_work/1/s/extensions/markdown-language-features/notebook-out/index.js
[2022-08-30 22:51:25.433] [renderer1] [debug] loadLocalResource - Error using fileReader. requestUri=file:///mnt/vss/_work/1/s/extensions/markdown-language-features/notebook-out/index.js
```

Any idea what that implies? This is normal local desktop, not web or remote.

**Comment by roblourens** [comment]
Is this because the Transpile CI step for smoke test https://dev.azure.com/vscode/VSCode/_build/results?buildId=72383&view=logs&j=15f6beb8-c39c-5fa4-f1fe-6e73c89d1002&t=d8f7ee5e-c9b1-5cc1-1796-88242b4b4c5a doesn't actually build that part of the extensions, as it does here, but I assume this got cleaned https://dev.azure.com/vscode/VSCode/_build/results?buildId=72383&view=logs&j=c7493abb-a1f4-533f-2d24-71780a69f247&t=9396f75f-d8ed-59a9-3621-c73d785709ab&l=85

**Comment by roblourens** [comment]
@TylerLeonhardt do you know about this build config for smoketests? The notebook stuff I need is built in the `compile-extension-media-build` task, how can we make sure that gets built for smoketest?

**Comment by joaomoreno** [comment]
This might have just been overlooked when we decoupled the Test stages from the Compile stage. We need to have the Smoke Test stage run `compile-extension-media-build`. PR: https://github.com/microsoft/vscode/pull/159872

**Comment by roblourens** [comment]
Thanks. We got `Error: Command failed: /opt/hostedtoolcache/node/16.17.0/x64/bin/node /mnt/vss/_work/1/s/extensions/simple-browser/esbuild-preview.js --outputRoot /mnt/vss/_work/1/s/.build/extensions/simple-browser` and I have no clue why since pretty much the same change in my PR fixed it: https://github.com/microsoft/vscode/pull/159521/commits/4150c81b97eac8d365f3b28063ba081f10a2e7aa

**Comment by roblourens** [comment]
Broke in the real build because I only added the build step under the OSS quality...

**Comment by lszomoru** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=376355&view=logs&j=e352877c-ff47-5dec-32e2-b206099d9704&t=65ec82f4-0572-5637-164d-da46c15920ac 

```
  1) VSCode Smoke Tests (Electron)
       Notebooks
         inserts/edits code cell:
     Error: Timeout: get element '.notebook-editor .monaco-list-row' after 20 seconds.
      at Code.poll (/Users/cloudtest/vss/_work/1/s/test/automation/out/code.js:286:23)
      at async Code.waitForElement (/Users/cloudtest/vss/_work/1/s/test/automation/out/code.js:242:16)
      at async Notebook.openNotebook (/Users/cloudtest/vss/_work/1/s/test/automation/out/notebook.js:24:9)
      at async Context.<anonymous> (out/areas/notebook/notebook.test.js:76:13)
```
