### ISSUE TITLE
Saving a file sometimes takes ~1 minute

### ISSUE THREAD

**Issue by BrunnerLivio** [Microsoft/vscode#13989]
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.06

Steps to Reproduce:

1. Open file
2. Edit content
3. Save (CTRL+S)

This problem occurs just sometimes. Can't actually figure out when. The files are normal/small size  (~1.00kb - 10.00kb). It does not always occur on the same file.

Here's the log of the Google Chrome Devtools
```
[Extension Host] Starting new check on: /home/users/brunnel6/workspace/molior-web/static/app/common/build-options-input/build-options-input.directive.js [plaintext]
2shell.ts:441Illegal argument: character must be positive: Error: Illegal argument: character must be positive
    at Object.f [as illegalArgument] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:3881)
    at new e (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:9:21410)
    at e.translate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:9:23072)
    at TagManager.updatePairedTag (/home/users/brunnel6/.vscode/extensions/formulahendry.auto-rename-tag-0.0.7/out/src/tagManager.js:72:47)
    at vscode.workspace.onDidChangeTextDocument.event (/home/users/brunnel6/.vscode/extensions/formulahendry.auto-rename-tag-0.0.7/out/src/tagManager.js:13:18)
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:6321)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:14643)
    at t.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:5970)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:11474)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:2033)
    at p (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:2710)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:441
threadService.ts:222[Extension Host] Starting new check on: /home/users/brunnel6/workspace/molior-web/static/app/common/build-options-input/build-options-input.tmp.html [plaintext]
threadService.ts:222[Extension Host] Starting new check on: /home/users/brunnel6/workspace/molior-web/static/app/common/build-options-input/build-options-input.directive.js [plaintext]
threadService.ts:222[Extension Host] Starting new check on: /home/users/brunnel6/workspace/molior-web/static/app/common/build-options-input/build-options-input.tmp.html [plaintext]
12mainThreadEditorsTracker.ts:285setDecorations on invisible editor
39mainThreadEditorsTracker.ts:285 setDecorations on invisible editor
threadService.ts:222 [Extension Host] Starting new check on: /home/users/brunnel6/workspace/molior-web/static/app/common/build-options-input/build-options-input.directive.js [plaintext]
6mainThreadEditorsTracker.ts:285 setDecorations on invisible editor
```

**Comment by roblourens** [comment]
What extensions do you have installed?

**Comment by jrieken** [comment]
I see `formulahendry.auto-rename-tag-0.0.7` but the stack trace is about changing a document, not saving. 

@BrunnerLivio Please try to reproduce this without extensions (`code --disableExtensions`) and also report above exception against the afore mentioned extension.

**Comment by BrunnerLivio** [comment]
@roblourens 
I have installed

- Cordova Tools
- Spelling and Grammar Checker
- yo
- Sass
- View in Browser
- seti-icons
- Debugger for Chrome
- C#
- PowerShell
- Go
- Angular 1 JavaScript and TypeScript Snippets
- PHP Debug
- TSLint
- Python
- jQuery Code Snippets
- Git History
- Bower
-Jasmine ES5 Code Snippets
- jshint
- Path Intellisense
- Nomo Dark Icon Theme
- Color Picker
- Indenticator
- PHP Code Format
- Output Colorizer
- beautify

@jrieken 
I think you are right. As far as I can remember, it always occured when I was editing a HTML file, or at least the editing of it caused the problem in the end. 

I run VSCode without `formulahendry.auto-rename-tag-0.0.7` now and I'll give feedback soon.

**Comment by BrunnerLivio** [comment]
Seems like the problem was indeed the extension.

Thanks for helping!
