### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by Jeson-gk** [microsoft/vscode#139830]
**TypeScript Version:** 4.6.0-dev.20211227

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\xxxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:57057:22)
    at getPropertyOfType (c:\Users\xxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:57727:24)
    at resolveESModuleSymbol (c:\Users\xxxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:49830:54)
    at getTargetOfNamespaceImport (c:\Users\xxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:49015:28)
    at getTargetOfAliasDeclaration (c:\Users\xxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:49249:28)
    at resolveAlias (c:\Users\xxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:49294:30)
    at getSymbol (c:\Users\xxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:47849:38)
    at resolveNameHelper (c:\Users\xxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:48142:34)
    at resolveName (c:\Users\xxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:48125:20)
    at resolveEntityName (c:\Users\xxxxx\.vscode\extensions\ms-vscode.vscode-typescript-next-4.6.20211227\node_modules\typescript\lib\tsserver.js:49466:42)
    at getTargetOfAliasLikeExpression

**Comment by IllusionMH** [comment]
I think it's same as #139833 and other duplicates of https://github.com/microsoft/TypeScript/issues/47179 but reproduced in nightly
