### ISSUE TITLE
Notebook Editor Event - onDidChangeVisibleNotebookEditors on open/close

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139958]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=148199&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=ad0cf992-b66d-54d3-7b97-28b0a2304eda&l=409

```
Notebook Editor
       Notebook Editor Event - onDidChangeVisibleNotebookEditors on open/close:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.editor.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

```

**Comment by bpasero** [comment]
Skipped via https://github.com/microsoft/vscode/commit/0f265a3651ab227764e30dfe50ae967d34e5890d

**Comment by rebornix** [comment]
Reenabled.
