### ISSUE TITLE
TS Server fatal error:  Cannot read property 'charCount' of undefined

### ISSUE THREAD

**Issue by Musbell** [microsoft/vscode#139986]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165941:68)
    at LineIndex.edit (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165822:31)
    at ScriptVersionCache._getSnapshot (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165612:47)
    at ScriptVersionCache.lineOffsetToPosition (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165631:29)
    at TextStorage.lineOffsetToPosition (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:156864:33)
    at ScriptInfo.lineOffsetToPosition (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157228:41)
    at /private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:163302:56
    at Object.next (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:629:33)
    at ProjectService.applyChangesToFile (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162258:46)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162225:30)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:163293:46)
    at /private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165210:88
    at IOSession.Session.executeWithRequestId (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165201:28)
    at IOSession.Session.executeCommand (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165210:33)
    at IOSession.Session.onMessage (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165236:35)
    at Interface.<anonymous> (/private/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/AppTranslocation/43D91435-BDB6-4AB5-B67B-D494E0E22B60/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.58.0 (Universal) (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 5|
|Memory (System)|12.00GB (1.42GB free)|
|Process Argv|--crash-reporter-id 392445c5-6aca-4efc-9b62-ef657ea61fa5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.9
svelte-intellisense|ard|0.7.1
gitkraken-glo|axo|1.1.1
vscode-database|baj|2.2.3
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
vscode-github-actions|csc|0.21.2
vscode-database-client2|cwe|4.4.0
githistory|don|0.6.19
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
gitlens-insiders|eam|2021.10.2305
vscode-npm-script|eg2|0.3.23
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|8.1.0
git-project-manager|fel|1.7.1
vscode-yarn|gam|2.0.0
copilot|Git|1.7.4421
vscode-graphql|Gra|0.3.41
vue-snippets|hol|1.0.4
rest-client|hum|0.24.6
vue|jcb|0.1.5
volar|joh|0.30.1
vscode-typescript-vue-plugin|joh|0.30.1
vscode-map-preview|jum|0.5.8
kite|kit|0.147.0
jsdoc|lll|1.0.3
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.18.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
vscode-react-native|msj|1.8.1
short-js-doc|mya|0.2.0
vetur|oct|0.35.0
vscode-jest|Ort|4.0.3
material-icon-theme|PKi|4.11.0
prisma|Pri|3.7.0
prisma-insider|Pri|31.0.460
vscode-thunder-client|ran|1.9.1
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.2.1
svelte-vscode|sve|105.8.0
gitblame|wad|8.1.0
nextjs|Wil|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614
py55gd98cf:30411515
vscexrecpromp3t3:30407764

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

> VS Code version: Code 1.58.0

This version is an old one. Is it reproducible in the latest available version 1.63.2?
https://code.visualstudio.com/Download
