### ISSUE TITLE
Cannot open merge conflicted file

### ISSUE THREAD

**Issue by SpiraMira** [microsoft/vscode#140014]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.6.3.2
- OS Version: macOS 12.01

Steps to Reproduce:

1. select a branch to merge from
2. perform merge
3. some files cannot be opened with following error:

**Cannot read property 'scheme' of null: TypeError: Cannot read property 'scheme' of null  
at yi.resolveEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1482:5955)
    at M.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2360:24395)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2323:55747
    at y.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:574:319)
    at y._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3496)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3245
    at async Tt.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2331:50361) - log.ts.313**

![Uploading Screen Shot 2022-01-02 at 2.03.28 PM.png…]()

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No

/needsMoreInfo
