### ISSUE TITLE
The TypeScript language service died unexpectedly. TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by oosharma** [microsoft/vscode#140042]
**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1. Opening up my workplaces project seems to be crashing the TS server
2. I recently installed React Testing Library on a new project after which this started happening on my workplace's project. I also installed ESLint globally.

I no longer have access to the TypeScript features on my project.

I followed many other issues on "The TypeScript language service died unexpectedly" and tried reinstalling VSCode, tried different versions of VSCode, even the insider's edition, tried disabling plugins, and even installing TypeScript Nightly plugin, but nothing seems to work.  

The following is the error I get on my workplace's project. 

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at resolveEntityName (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49232:28)
    at resolveAlias (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47648:21)
    at /private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeModuleAugmentation (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47753:17)
    at initializeTypeChecker (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85046:25)
    at Object.createTypeChecker (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Object.getProgram (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

3. If I open a new VSCode window with test.tsx as its name, the TS server doesn't crash there, but still in the output window I see  this 

[Info  - 16:09:12.484] Starting TS Server 
[Info  - 16:09:12.484] Using tsserver from: /private/var/folders/xf/3v1v0g1j2md7kjnk03s1rp2c0000gn/T/AppTranslocation/13BEEC37-C22D-4ACE-8090-455B892D4F71/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 16:09:12.485] <syntax> Forking...
[Info  - 16:09:12.486] <syntax> Starting...
[Info  - 16:09:12.487] <semantic> Forking...
[Info  - 16:09:12.488] <semantic> Starting...

**Comment by oosharma** [comment]
Okay, this seemed to have been solved.

Here is what I did:

1) Installed JavaScript TypeScript Nightly. 
2) Created a .vscode folder in root directory
3) Added a settings.json to .vscode directory with the following code: 
```
{
    "typescript.tsdk": "./node_modules/typescript/lib"
 }
```
4) Opened Command Pallete with cmd + p and entered the following
>TypeScript
5) Select TypeScript version: Use WorkSpace version 3.7.3
6) >Developer: Reload window

This solved the issue.
