### ISSUE TITLE
Flake smoke test: vscode API - terminal Terminal environmentVariableCollection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140111]
Still flaky tests:

- vscode API - terminal Terminal environmentVariableCollection should have collection variables apply to environment variables that don't exist
- vscode API - terminal Terminal environmentVariableCollection should respect deleting entries

Example failures:

```
Error: Timeout: ~b2~ should be printed after 20 seconds.
Did not pass accept function
    at poll (D:\a\1\s\extensions\vscode-api-tests\src\utils.ts:167:10)
    at Context.<anonymous> (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:833:5)
```

```
Error: Timeout: ~c2~ should be printed after 20 seconds.
Did not pass accept function
    at poll (D:\a\1\s\extensions\vscode-api-tests\src\utils.ts:167:10)
    at Context.<anonymous> (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:751:5)
```

**Comment by Tyriar** [comment]
Disabled in https://github.com/microsoft/vscode/commit/79ed98edc92d62aca259c26f2bb74092abf270f8
