### ISSUE TITLE
Flaky smoke test: vscode API - tasks Tasks ShellExecution dependsOn task should start with a different processId

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140110]
This test failed 12 times in the past month:

![image](https://user-images.githubusercontent.com/2193314/148100691-fb413abd-c782-4008-8307-a9f001d166d6.png)

```
Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\workspace.tasks.test.js)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

https://github.com/microsoft/vscode/wiki/Dealing-with-Test-Flakiness

**Comment by Tyriar** [comment]
Skipped this test
