### ISSUE TITLE
Variable value hover tooltips in debugger is jumbled up

### ISSUE THREAD

**Issue by inderjeet-a2j** [microsoft/vscode#140251]
Issue Type: <b>Bug</b>

When debugging node.js code, the hover tooltip values in debug mode is all jumbled up when you are inspecting an object. The object can be expanded be clicking on arrow. 

Variables in watch window also cannot be expanded. I have disabled all the extensions and problem still exists.

It seems to work if I use Nov 15th version of insider edition of VS Code. After updating with yesterday's (Jan 5th, 2022) build, it has stopped working.

VS Code version: Code - Insiders 1.64.0-insider (9afbea7caab9dd06592ddd98aa4161b43b126d3f, 2022-01-06T05:15:20.409Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 6, 5|
|Memory (System)|16.00GB (1.17GB free)|
|Process Argv|--crash-reporter-id 0d95cdb4-3b01-47e6-bd20-9f4be833ddbb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
js-debug-companion|ms-|1.0.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30419156
vscop804:30404766
vscop940:30404999
vsclayoutctrc:30405799
py55gd98:30408621
vscexrecpromp3c:30407757
azactmsalcf:30409288

```

</details>

![Debugg-issue](https://user-images.githubusercontent.com/46508707/148488262-36e79813-0e9b-4a12-9f37-24526ae574a8.png)

**Comment by eamodio** [comment]
I haven't seen it overlapped like that, but I only see a single line at the top.

**Comment by aladdin-add** [comment]
overlapped issue was from the ext: gitlens. see https://github.com/microsoft/vscode/issues/140264#issuecomment-1007259450

**Comment by weinand** [comment]
@connor4312 

A git-bisect showed this commit as the culprit: https://github.com/microsoft/vscode/commit/259c20e8d110af32925fb154c47c1d771ef1afa4

When running out of source I'm seeing this error:

[65921:0110/145010.353870:INFO:CONSOLE(231)] "%c  ERR color: #f33 variable.parent.toDebugProtocolObject is not a function: TypeError: variable.parent.toDebugProtocolObject is not a function
    at getVariablesContext (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/workbench/contrib/debug/browser/variablesView.js:169:36)
    at VariablesRenderer.renderActionBar (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/workbench/contrib/debug/browser/variablesView.js:329:29)
    at VariablesRenderer.renderElement (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/workbench/contrib/debug/browser/baseDebugView.js:124:22)
    at AsyncDataTreeRenderer.renderElement (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:60:27)
    at TreeRenderer.renderElement (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:255:27)
    at PipelineRenderer.renderElement (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/list/listWidget.js:826:26)
    at ListView.insertItemInDOM (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/list/listView.js:568:26)
    at ListView.render (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/list/listView.js:524:26)
    at ListView.onScroll (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/list/listView.js:699:22)
    at Emitter.fire (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/common/event.js:482:41)
    at vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:115:32
    at Emitter.fire (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/common/event.js:479:38)
    at Scrollable._setState (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/common/scrollable.js:234:28)
    at Scrollable.setScrollDimensions (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/common/scrollable.js:127:18)
    at SmoothScrollableElement.setScrollDimensions (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:186:30)
    at ListView.layout (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/list/listView.js:505:40)
    at TreeNodeList.layout (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/list/listWidget.js:1147:23)
    at ObjectTree.layout (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1121:23)
    at WorkbenchAsyncDataTree.layout (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:320:23)
    at DebugHoverWidget.layoutTreeAndContainer (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/workbench/contrib/debug/browser/debugHover.js:241:23)
    at DebugHoverWidget.doShow (vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/workbench/contrib/debug/browser/debugHover.js:228:18)", source: vscode-file://vscode-app/Users/weinand/MS/Projects/vscode/out/vs/platform/log/common/log.js (231)
