### ISSUE TITLE
after pausing, breakpoint is not hit

### ISSUE THREAD

**Issue by collintime** [Microsoft/vscode#14023]
- VSCode Version: 1.6.1
- OS Version: 10.11.6
- Node Version: 5.2 through 6.8.1 (at least)

Steps to (maybe) Reproduce:

1. add some breakpoints to your app
2. launch

Normally, the breakpoints are triggered and execution stops. A yellow line appears on the screen where the code is stopped. Playback controls appear. Sometimes this will NOT work correctly--execution stops, playback controls appear but WITHOUT the yellow line. You can click Play/StepOver/StepInto which may or may not cause VSCode to stop correctly at the next breakpoint in the series.

The worst part is that it's unreproducible. The same breakpoints will work for hours and then stop working suddenly.

Steps to mitigate the problem:

1. Less likely to happen if you have MORE breakpoints, especially on any lines that return promises. 
2. Sometimes you can persuade VSCode to find the next breakpoint if you click StepInto two or three times and then press play

I wish I could add more details to this issue. It's affected me for months but I was hesitant to create an issue because of my lack of data. If this is a known problem please let me know and I'll contribute in any way I can to the discussion.

**Comment by roblourens** [comment]
So it pauses, but the yellow line doesn't appear? Is it pausing in the right place? When you say the buttons may or may not cause it to stop correctly at the next breakpoint, you mean it skips the breakpoint, or it pauses there but has the same issue with the yellow line? Can you get the yellow line to appear by closing/reopening the file, or clicking around in the call stack? Do you see the green line if you click a higher frame in the call stack?

**Comment by collintime** [comment]
Thanks for the response, yes, a pause but without a yellow line. I've tried clicking up and down the stack but it never appears (i'll try again next time it happens). Even with one faulty breakpoint i've attempted to use the debug console with no success. I assume it is pausing in the right place but I cant tell. The buttons will advance execution but with no guarantee that a yellow line will appear at the next breakpoint--sometimes it works. 

I'll look for a green line and I'll open and close the file next time.

**Comment by roblourens** [comment]
If you are targeting Node 6.3+ you could try with `"type": "node2"`, our new experimental Node debugger, just to see if it shows up there. When this happens you could also check for errors in the console in 'Help > Developer Tools'

**Comment by collintime** [comment]
Call Stack reports: "No call stack available (vscode_backtrace: Internal error: TypeError: Cannot read property '0' of undefined)."

I'll post the last 3 errors from the console in Help > Developer Tools, however if I clear the console and re-run, no errors are output and the issue happens again.

3) exception
Path must be a string. Received null
e.doShow @ messageService.ts:128

2) logged object
{
  command: "projectInfo",
  message: "Error processing request. No Project.
Error: No Project.
    at Errors (/Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/server/typescript/lib/tsserver.js:50793:32)
    at ts.server.ts.server (/Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/server/typescript/lib/tsserver.js:50795:11)
    at ts (/Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/server/typescript/lib/tsserver.js:51775:7)
    at Object.<anonymous> (/Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/server/typescript/lib/tsserver.js:51776:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)"
}

1) exception
messageService.ts:128 Unable to open 'blah.js': File not found (/blah/v1/blah/blah.js).: Error: Unable to open 'blah.js': File not found (/blah/v1/blah/blah.js).
    at Object.f [as create] (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:18882)
    at t.doHandleSetInputError (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117:13594)
    at file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117:13288
    at Object.v [as _notify] (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:8549)
    at Object.enter (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:12054)
    at _run (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:13375)
    at _chainedError (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:12734)
    at n (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:10557)
    at then (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:14184)
    at Object.enter (file:////Users/xxx/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:10626)e.doShow @ messageService.ts:128

**Comment by collintime** [comment]
example snippet:

```js
{
  return somePromise()
    .then(result => {
      console.log(result)
   })
}
```

steps:

1) breakpoint was on line 3, issue triggered 5+ times in a row.
2) added breakpoint to line 1, issue did not trigger
3) removed breakpoint from line 1, issue DID NOT trigger on the next run

**Comment by collintime** [comment]
looks related to https://github.com/Microsoft/vscode/issues/7683

**Comment by roblourens** [comment]
That error in the call stack would be the problem. I think it is exactly #7683. Glad to hear that it doesn't repro with node2 though.
