### ISSUE TITLE
Notebook API tests editor editing event

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140200]
```
1) Notebook API tests
       editor editing event:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/vscode/vscode/extensions/vscode-api-tests/out/singlefolder-tests/notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://github.com/microsoft/vscode/runs/4721311082?check_suite_focus=true#step:16:526

**Comment by roblourens** [comment]
#126371

reenabling this since I skipped all these tests in the browser, which is the only place they are flaky
