### ISSUE TITLE
Notebook API tests multiple tabs: dirty + clean

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140285]
```
  1) Notebook API tests
       multiple tabs: dirty + clean:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode/vscode/extensions/vscode-api-tests/out/singlefolder-tests/notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://github.com/microsoft/vscode/runs/4739717778?check_suite_focus=true#step:16:348

**Comment by roblourens** [comment]
I disabled all the notebook integration tests in web, this is the same issue as in https://github.com/microsoft/vscode/issues/126371
