### ISSUE TITLE
Cannot install extensions and remove files if building with electron-16

### ISSUE THREAD

**Issue by PF4Public** [microsoft/vscode#140330]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.64.0
- Commit: 61c35c63c34afaac1e90c1d68013583bc85c25a2
- Datum: 2022-01-08T12:36:30.699Z
- Electron: 16.0.6
- Chromium: 96.0.4664.110
- Node.js: 16.9.1
- V8: 9.6.180.21-electron.0
- Betriebssystem: Linux x64 5.15.11-gentoo

Steps to Reproduce:

* Try updating language packs
* Try removing any file in EXPLORER panel

The results are:

```js
ERR Der vorhandene Ordner "/home/*****/.vscode-oss/extensions/ms-ceintl.vscode-language-pack-de-1.64.2" konnte während der Installation der Erweiterung "ms-ceintl.vscode-language-pack-de" nicht gelöscht werden. Löschen Sie den Ordner manuell, und versuchen Sie es noch mal.: Delete: Der vorhandene Ordner "/home/*****/.vscode-oss/extensions/ms-ceintl.vscode-language-pack-de-1.64.2" konnte während der Installation der Erweiterung "ms-ceintl.vscode-language-pack-de" nicht gelöscht werden. Löschen Sie den Ordner manuell, und versuchen Sie es noch mal.
    at a.extractUserExtension (vscode-file://vscode-app/usr/lib64/vscode/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:194405)
    at async $.extract (vscode-file://vscode-app/usr/lib64/vscode/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:208071)
    at async $.doRun (vscode-file://vscode-app/usr/lib64/vscode/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:208898)
```

and:

```js
ERR Error: ENOTDIR: not a directory, rmdir '*****': EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, rmdir '*****'
    at a (/usr/lib64/vscode/out/vs/code/electron-main/main.js:28:4013)
    at o.toFileSystemProviderError (/usr/lib64/vscode/out/vs/code/electron-main/main.js:31:46651)
    at o.delete (/usr/lib64/vscode/out/vs/code/electron-main/main.js:31:44378)
```
It works without issues with electron-13

There might be other yet undiscovered issues related to the inability of deleting files.

**Comment by PF4Public** [comment]
Ooops, sorry for the spurious issue. Building from the branch `electron-16.x.y` fixes it.
