### ISSUE TITLE
SCM view is not showing any changes

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#140492]
![image](https://user-images.githubusercontent.com/10746682/148946129-a7d1dd45-d580-450e-aa8d-7f6b76db1340.png)

I am seeing following error in the console

```
 Invalid comparison: Error: Invalid comparison
    at Re.compare (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2330:15021)
    at Object.compare (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:87972)
    at Object.compare (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:78790)
    at Array.sort (<anonymous>)
    at M.preserveCollapseState (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:79729)
    at M.setChildren (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:78998)
    at o._setChildren (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:85317)
    at o.setChildren (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:84435)
    at f.setChildren (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:88828)
    at Q.setChildren (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:192:8635)
    at xe.refresh (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2330:27199)
    at xe._onDidChangeVisibleRepositories (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2330:24882)
    at xe.setVisible (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2330:26005)
    at o.fire (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1732)
    at kt.setVisible (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1689:19631)
    at vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2543:63500
    at Array.map (<anonymous>)
    at m.setVisible (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2543:63491)
    at P.setVisible (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2543:84224)
    at yl.showComposite (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1689:11780)
    at yl.doOpenComposite (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1689:9807)
    at yl.openComposite (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1689:9360)
    at yl.doOpenViewlet (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2615:4903)
    at yl.openPaneComposite (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2615:4262)
    at openPaneComposite (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2615:49461)
    at u.openComposite (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2615:56438)
    at u.openView (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2615:58351)
    at Object.run (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2615:62016)
    at handler (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:638:12833)
    at E.invokeFunction (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:573:319)
    at E._tryExecuteCommand (vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1481:3496)
    at vscode-file://vscode-app/private/var/folders/4f/jm7yhn6j36z4296yzq2_b77c0000gn/T/AppTranslocation/52F4120D-7F39-4379-848B-07EC8A986982/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1481:3245
```

**Comment by sandy081** [comment]
Sorry, was on old build. Closing this.
