### ISSUE TITLE
Integration test timeout: Notebook API tests (metadata) custom metadata should be supported:

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140574]
```
  1 failing
  1) Notebook API tests (metadata)
       custom metadata should be supported:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode/vscode/extensions/vscode-api-tests/out/singlefolder-tests/notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by roblourens** [comment]
Skipping the rest of the tests in browser, #126371
