### ISSUE TITLE
Integration test failure: "git smoke test"

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140573]
https://github.com/microsoft/vscode/actions/runs/1686659292

Integration tests (browser, firefox)

```
  git smoke test
    √ reflects working tree changes (5366ms)
    √ opens diff editor (308ms)
    1) stages correctly
Switched to branch 'test'
    2) stages, commits changes and verifies outgoing change
    3) rename/delete conflict
  25 passing (2m)
  3 failing
  1) git smoke test
       stages correctly:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\git\out\test\smoke.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) git smoke test
       stages, commits changes and verifies outgoing change:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\git\out\test\smoke.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) git smoke test
       rename/delete conflict:
     Failed to execute git
```

**Comment by Tyriar** [comment]
nit: Little weird that there's a git integration test called git smoke test

**Comment by joaomoreno** [comment]
There are no SCM/git smoke tests since February 2020: https://github.com/microsoft/vscode/commit/16c7551f3664b713835b39faeb6c2db859c87647#diff-613e3170e904ceaf0d429547a7c51e16e4fe2d464b0878c45c0cadda8758ee44

There are only the git extension integration tests, which are regular extension tests.

**Comment by lszomoru** [comment]
I have not seen this failure since the issue has been filed so I will go ahead and close it.
