### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by replace5** [microsoft/vscode#140554]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49453:42)
    at getTargetOfExportSpecifier (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49193:17)
    at getTargetOfAliasDeclaration (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49243:28)
    at resolveAlias (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47624:42)
    at /Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47648:21)
    at /Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47737:20)
    at initializeTypeChecker (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:85010:21)
    at Object.createTypeChecker (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:159898:21)
    at Proxy.getProgram (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:168762:44)
    at /Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:170260:46)
    at /Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/Users/chen/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|36, 16, 14|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id f9966fb7-7ab7-416e-95e0-a8cedc6e7990|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|13.2.2
project-manager|ale|12.4.0
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.4.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.0.0
file-icons|fil|1.0.29
code-runner|for|0.11.6
copilot|Git|1.7.3862
todo-tree|Gru|0.0.214
vue-snippets|hol|1.0.4
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.2
theme-monokai-pro-vscode|mon|1.1.19
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.17.0
vscode-language-pack-zh-hans|MS-|1.61.5
remote-containers|ms-|0.202.4
sublime-keybindings|ms-|4.0.10
vscode-typescript-tslint-plugin|ms-|1.3.3
vetur|oct|0.35.0
material-icon-theme|PKi|4.10.0
vscode-thunder-client|ran|1.9.1
LiveServer|rit|5.6.1
vscode-nginx|sha|0.6.0
markdown-preview-enhanced|shd|0.6.0
open-in-browser|tec|2.0.0
material-theme|zhu|3.13.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by IllusionMH** [comment]
Please try to install https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next and see if problem is still reproducible.

Fix should be in latest TS Nightly version.
