### ISSUE TITLE
RangeError: Maximum call stack size exceeded     at QuickInputList.setElements

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#140854]
* use the `big.js`-file from https://github.com/microsoft/vscode/issues/140661
* wait for outline/breakcrumbs to show
* trigger quick outline
* 💥 Maximum call stack size exceeded

```
ERR Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at QuickInputList.setElements (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/parts/quickinput/browser/quickInputList.js:353:37)
    at QuickPick.update (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/parts/quickinput/browser/quickInput.js:735:30)
    at QuickPick.set items [as items] (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/parts/quickinput/browser/quickInput.js:356:18)
    at updatePickerItems (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/contrib/quickAccess/gotoSymbolQuickAccess.js:122:38)
```

**Comment by jrieken** [comment]
Rooted here: https://github.com/microsoft/vscode/blob/cc04113a70c23c2524ed4b6fb5ea4ccccbe72c2a/src/vs/base/parts/quickinput/browser/quickInputList.ts#L525-L526. Don't use argument spread but a good old for-loop
