### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by yibuwang83** [microsoft/vscode#140890]
We have written the needed data into your clipboard because it was too large to send. Please paste.❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4
vscode inside
**Steps to reproduce crash**
1. install new vscode inside
2. sync plugins
3. open project ( typescript react project)
![image](https://user-images.githubusercontent.com/51268652/149901092-892afe1b-6bb5-46ab-a5b8-66ccdc1fba4c.png)

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49453:42)
    at getTargetOfAliasLikeExpression (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49210:29)
    at getTargetOfExportAssignment (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49199:28)
    at getTargetOfAliasDeclaration (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49246:28)
    at resolveAlias (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49271:67)
    at resolveExternalModuleSymbol (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49763:36)
    at getTargetOfNamespaceExportDeclaration (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49186:28)
    at getTargetOfAliasDeclaration (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49248:28)
    at resolveAlias (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:47624:42)
    at /Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:47737:20)
    at initializeTypeChecker (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:85010:21)
    at Object.createTypeChecker (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:159898:21)
    at Proxy.getProgram (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:168762:44)
    at /Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:170260:46)
    at /Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/Users/ww/.nvm/versions/node/v14.18.1/lib/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by IllusionMH** [comment]
/duplicate

In the meantime you can use Nightly TS version that contains fix: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next
