### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by Keyan-Wang** [microsoft/vscode#140953]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57011:22)
    at getPropertyOfType (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57671:24)
    at resolveESModuleSymbol (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49817:54)
    at getTargetOfNamespaceImport (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49236:28)
    at resolveAlias (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at getSymbol (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47838:38)
    at resolveNameHelper (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48131:34)
    at resolveName (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48114:20)
    at resolveEntityName (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49453:42)
    at getTargetOfAliasLikeExpression (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49210:29)
    at getTargetOfExportAssignment (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49199:28)
    at getTargetOfAliasDeclaration (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49246:28)
    at resolveAlias (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49271:67)
    at resolveExternalModuleSymbol (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49763:36)
    at getTargetOfNamespaceExportDeclaration (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49186:28)
    at getTargetOfAliasDeclaration (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49248:28)
    at resolveAlias (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49271:67)
    at mergeSymbol (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47624:42)
    at d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47737:20)
    at initializeTypeChecker (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:85010:21)
    at Object.createTypeChecker (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47395:9)
    at Object.getTypeChecker (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114404:79)
    at synchronizeHostData (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159898:21)
    at Object.getProgram (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168762:44)
    at d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:97
    at Object.flatMap (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170260:46)
    at d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> (d:\Users\wangkeyan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.38GB free)|
|Process Argv|--crash-reporter-id 4e8b7b19-baa0-41cc-8000-e7a9e4bf935b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
tslint|eg2|1.0.47
pdf|fri|0.0.6
vue|liu|0.1.5
jsdoc|lll|1.0.3
code-beautifier|mic|2.3.3
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
csslint|ray|0.0.11
vscode-stylelint|sty|1.2.1
vscode-icons-mac|way|7.25.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30416614

```

</details>

**Comment by IllusionMH** [comment]
/duplicate

In the meantime you can use Nightly TS version that contains fix: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next
