### ISSUE TITLE
On CI we get errors Error: NO notebook document for 'vscode-interactive:Interactive-2.interactive',

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#140947]
```
Error: NO notebook document for 'vscode-interactive:Interactive-2.interactive'
/vs/workbench/api/common/extHostNotebook.ts#136:18
/vs/workbench/api/common/extHostNotebookKernels.ts#260:25
/vs/workbench/services/extensions/common/rpcProtocol.ts#472:16
/vs/workbench/services/extensions/common/rpcProtocol.ts#457:31
/vs/workbench/services/extensions/common/rpcProtocol.ts#373:18
/vs/workbench/services/extensions/common/rpcProtocol.ts#295:9
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:8910 
/vs/base/common/event.ts#611:15
/vs/base/parts/ipc/common/ipc.net.ts#636:4
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34332 
/vs/base/common/event.ts#611:15
/vs/base/parts/ipc/common/ipc.net.ts#636:4
/vs/base/parts/ipc/common/ipc.net.ts#956:34
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21011 
/vs/base/common/event.ts#611:15
/vs/base/parts/ipc/common/ipc.net.ts#380:17
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:14857 
/vs/base/parts/ipc/node/ipc.net.ts#60:3
at Socket.emit (events.js
at addChunk (internal/streams/readable.js:309:12) 
at readableAddChunk (internal/streams/readable.js:284:9) 
at Socket.Readable.push (internal/streams/readable.js:223:10) 
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Error from telemetry. I ran into this as well sometimes when opening a second IW.

**Comment by joaomoreno** [comment]
@amunger `triage-needed` is used only when an issue isn't yet assigned to its rightful owner.

**Comment by amunger** [comment]
this repros every time an interactive window with a specific name is created for the first time - we haven't created the document for that IW yet. But then the same $acceptNotebookAssociation is fired again after creating that document anyway
