### ISSUE TITLE
StreamDebugAdapter (SocketDebugAdapter) can initialize a connection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141071]
Build: https://github.com/microsoft/vscode/actions/runs/1723430523
Changes: https://github.com/microsoft/vscode/compare/7cde8b9...13461f8

```
  1 failing

  1) Debug - StreamDebugAdapter
       StreamDebugAdapter (SocketDebugAdapter) can initialize a connection:
     Uncaught Error: listen EADDRINUSE: address already in use :::8084
      at Server.setupListenHandle [as _listen2] (net.js:1331:16)
      at listenInCluster (net.js:1379:12)
      at Server.listen (net.js:1465:7)
      at Context.<anonymous> (out/vs/workbench/contrib/debug/test/node/streamDebugAdapter.test.js:65:67)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by bpasero** [comment]
👏  for such a prompt fix
