### ISSUE TITLE
Cannot open terminal within WSL Ubuntu multi-root workspace

### ISSUE THREAD

**Issue by CactusPuppy** [microsoft/vscode#141115]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Install WSL and the Ubuntu distro, if necessary. 
2. Install the "Remote - WSL" extension into VSCode, if necessary. 
3. Create a multi-root workspace within a WSL-enabled VSCode window hosted in the Ubuntu distro.
4. Attempt to open a terminal in a specific root folder (either via the `Terminal: Create New Terminal` command or the `New Terminal` button on the Terminal tab).
5. At this point, I expected a new terminal in the specified root folder to open. However, I actually saw the new terminal window freeze without fully launching. 

Relevant section of Window log file:
```log
[2022-01-20 14:17:15.312] [renderer1] [trace] KeybindingService#dispatch Ctrl+Shift+` workbench.action.terminal.new
[2022-01-20 14:17:15.312] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.new
[2022-01-20 14:17:15.312] [renderer1] [trace] CommandService#executeCommand _workbench.pickWorkspaceFolder
[2022-01-20 14:17:17.439] [renderer1] [trace] terminalInstance#ctor (instanceId: 4) {"cwd":{"$mid":1,"fsPath":"\\home\\cactuspuppy\\test1","_sep":1,"external":"vscode-remote://wsl%2Bubuntu/home/cactuspuppy/test1","path":"/home/cactuspuppy/test1","scheme":"vscode-remote","authority":"wsl+ubuntu"}}
[2022-01-20 14:17:17.533] [renderer1] [trace] Webgl was loaded
[2022-01-20 14:17:17.543] [renderer1] [error] No terminal backend registered for remote authority 'wsl+ubuntu': Error: No terminal backend registered for remote authority 'wsl+ubuntu'
    at R.createProcess (vscode-file://vscode-app/c:/Users/Cactu/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1707:14152)
    at _i._createProcess (vscode-file://vscode-app/c:/Users/Cactu/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2784:103856)
    at async vscode-file://vscode-app/c:/Users/Cactu/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2784:83252
```

VS Code version: Code - Insiders 1.64.0-insider (0c6d1e9f7ef648cfa50733abb62388bc0791856a, 2022-01-20T06:30:46.042Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.52GB free)|
|Process Argv|--disable-extensions --remote=wsl+Ubuntu --crash-reporter-id cd5da0de-c398-4079-9337-7f8713f209d9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.27GB (6.49GB free)|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vscop804cf:30404767
vscop341:30404997
vsclayoutctrc:30405799
azactmsal:30409287
pythonvsnew555cf:30426299
vsbas813:30426126

```

</details>

**Comment by CactusPuppy** [comment]
Notably, this issue does not occur within the other Linux distribution I tested (`kali-linux`).

**Comment by tdack** [comment]
I'm seeing the same issue (VSCode 1.63.2),

One terminal is available when first launched, and this can be split to give a second (third, fourth, etc) terminal. The split terminal can be moved to the editor area and then back to the Terminal panel and remains functional.

**Comment by Tyriar** [comment]
Can reproduce:

![image](https://user-images.githubusercontent.com/2193314/150829441-fea98f6e-1547-40a9-a933-6e05a5b5073d.png)
