### ISSUE TITLE
macOS notarize failed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141129]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=151308&view=logs&j=af0dc8b4-cfa3-5b7d-c786-c94be5e90de5&t=ab3d1ee5-839d-5f24-00e3-a512cd3cbc43&l=292

```
1 files failed.
List of failed files:
Failed OperationId: ce51b20c-0a64-4208-b235-d41574edb0a8, Status: FailDoNotRetry, FilePath:/Users/runner/work/1/VSCode-darwin-universal.zip, Error: {"code":"MacSignFailed","details":{"errorDetails":""},"innerError":null}
**************************
CleanupStorage:: account prodgatewayv2eastp233.blob.core.windows.net blob 86ff82c5-df8e-4776-bb53-40d4b742d225/df326249-f869-49f5-ad21-4e7ff414d726.zip returned True
CleanupStorage:: account prodgatewayv2eastp239.blob.core.windows.net blob 50565d94-e223-4870-b1c4-a6a7ab207fad/a5dfa662-2722-4678-90eb-5c4814b69b6a.zip returned False

 | Operation Id                         | Status         | Size     | Upload(sec) | Submit(sec) | SignnWait(sec) | Download (sec) | Retry Count | 
 |--------------------------------------|----------------|----------|-------------|-------------|----------------|----------------|-------------|
 | ce51b20c-0a64-4208-b235-d41574edb0a8 | FailDoNotRetry | 337.46MB | 9.05        | 0.34        | 757.05         | 0              | 0           | 

Total Time: 00:13:09.9772440
ProcessExecutionComplete:Newtonsoft.Json.JsonSerializerSettings
[2] {"Timestamp":"2022-01-21T06:30:44.649513+00:00","ProviderName":"esrpcli","Level":2,"Keywords":0,"Payload":{"Message":"{\"ver\":\"2.1\",\"name\":\"MS.Ess.EsrpClient.ProcessExecutionComplete\",\"time\":\"2022-01-21T06:30:44.6261210Z\",\"epoch\":\"3527\",\"seqNum\":3,\"flags\":512,\"os\":\"Unix\",\"osVer\":\"20.6.0.0\",\"appId\":\"esrpcli\",\"appVer\":\"2.0.106+Branch.master.Sha.50891193c0e7aeb6bee97010eb12e03052c89676\",\"ext\":{\"cloud\":{\"name\":null,\"role\":null,\"roleInstance\":\"Mac-1642738730184\",\"location\":null,\"environment\":null,\"deploymentUnit\":null,\"fullEnvName\":\";;3527\"},\"sll\":{\"libVer\":\"4.0.15238.1\",\"level\":2}},\"data\":{\"exitCode\":1,\"totalFileCount\":1,\"totalFileSizeInBytes\":353854542,\"totalSignDurationMs\":757400.81,\"totalUploadDurationMs\":9046.36,\"handlerStartedAt\":\"2022-01-21T06:17:32.283744+00:00\",\"sessionStartedAt\":\"2022-01-21T06:17:32.283744+00:00\",\"configInfo\":{\"esrpApiBaseUri\":\"https://api.esrp.microsoft.com/api/v2\",\"esrpSessionTimeoutInSec\":7200,\"maxDegreeOfParallelism\":24,\"exponentialRetryCount\":5,\"signConfigType\":\"inlineSignParams\"},\"handlerExecutionContext\":{\"throttleCount\":0,\"throttledTimeInSec\":0,\"workflowSubType\":\"EmbedSignAzure\",\"sourceLocationType\":1,\"destinationLocationType\":1},\"requestSigningCertificateThumbprint\":\"3A46A86DDA341D17E702EF70F67EB091AA67054E\",\"isSuccess\":false,\"operationStartedAt\":\"2022-01-21T06:17:34.634055+00:00\",\"operationEndedAt\":\"2022-01-21T06:30:44.624535+00:00\",\"operationDurationMS\":790035,\"processName\":\"dotnet\",\"processVersion\":\"0.0.0.0\",\"customerCorrelationId\":\"77cb7fd3-f736-4935-ac1a-581e9707eb19\",\"esrpClientSessionGuid\":\"a2075f04-8d60-4555-8d62-7355de7c2dc1\",\"indentity\":\"runner\",\"clientId\":\"***\",\"apiBaseUrl\":\"https://api.esrp.microsoft.com/api/v2\",\"handlerWorkflow\":\"sign\",\"policyInfo\":{\"intent\":\"\",\"contentType\":\"\",\"contentOrigin\":\"\",\"productState\":\"\",\"audience\":\"\",\"version\":\"1.0.0\"},\"submissionRequest\":{\"contextData\":{\"builD_BUILDID\":\"151308\",\"builD_BUILDNUMBER\":\"20220121.20\",\"builD_QUEUEDBY\":\"Microsoft.VisualStudio.Services.TFS\",\"builD_REASON\":\"Schedule\",\"builD_REQUESTEDFOREMAIL\":\"\",\"systeM_TEAMFOUNDATIONCOLLECTIONURI\":\"https://dev.azure.com/monacotools/\",\"agenT_NAME\":\"Hosted Agent\",\"osVersion\":\"Unix 20.6.0.0\",\"tF_BUILD\":\"True\",\"systeM_TEAMPROJECT\":\"Monaco\",\"systeM_PULLREQUEST_ISFORK\":\"False\",\"systeM_HOSTTYPE\":\"build\",\"systeM_DEFINITIONID\":\"111\",\"systeM_COLLECTIONID\":\"341001b6-62a6-4d7e-aa61-779aea3de100\",\"builD_REPOSITORY_GIT_SUBMODULECHECKOUT\":\"False\",\"builD_SOURCEVERSION\":\"be7ec0fed2492d17984ab4e3764fe3f685e6ddc4\",\"builD_SOURCEBRANCHNAME\":\"main\",\"builD_SOURCEBRANCH\":\"refs/heads/main\",\"builD_REQUESTEDFORID\":\"00000002-0000-8888-8000-000000000000\",\"builD_REQUESTEDFOR\":\"Microsoft.VisualStudio.Services.TFS\",\"builD_REPOSITORY_PROVIDER\":\"GitHub\",\"builD_REPOSITORY_NAME\":\"microsoft/vscode\",\"builD_QUEUEDBYID\":\"00000002-0000-8888-8000-000000000000\",\"builD_DEFINITIONVERSION\":\"94\",\"builD_DEFINITIONNAME\":\"VS Code\",\"agenT_MACHINENAME\":\"Mac-1642738730184\"},\"copsId\":9997,\"folderPath\":\"/Users/runner/work/1\",\"pattern\":\"VSCode-darwin-universal.zip\"},\"osVersion\":\"Unix 20.6.0.0\"}}","EventId":0}}
ESRP failed
Error: Command failed: dotnet /Users/runner/hostedtoolcache/esrpclient/2.0.106/x64/netcoreapp2.1/esrpcli.dll vsts.sign -a *** -k /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-3526-oJ4XNMrI7K2Y -z /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-3526-se4XmPdmWZWk -f /Users/runner/work/1 -p /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-3526-ZMQzmOP2j7PK -u false -x regularSigning -b input.json -l AzSecPack_PublisherPolicyProd.xml -y inlineSignParams -j /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-3526-FC1MCgBQU17H -c 9997 -t 120 -g 10 -v Tls12 -s https://api.esrp.microsoft.com/api/v1 -m 0 -o Microsoft -i https://www.microsoft.com -n 5 -r true -e /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-3526-ycJhtEKxLfLC
    at checkExecSyncError (child_process.js:790:11)
    at Object.execFileSync (child_process.js:827:15)
    at main (/Users/runner/work/1/s/build/azure-pipelines/common/sign.js:73:12)
    at Object.<anonymous> (/Users/runner/work/1/s/build/azure-pipelines/common/sign.js:83:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3527,
  stdout: null,
  stderr: null
}
```

Not sure whether this task would be another one for retry?

**Comment by joaomoreno** [comment]
The error says `FailDoNotRetry`, so retrying is the wrong thing to do. There's nothing to do here but to wait for the service to be back up.
