### ISSUE TITLE
Blocked on enabling settings sync on vscode.dev

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#141246]
Went to a github repo and typed "." and attempted to turn on settings sync and ran into this issue with no way to resolve:

First it signed me out of all other sessions:
<img width="484" src="https://user-images.githubusercontent.com/35271042/150691921-6bb0e5c4-ff19-4b82-8b46-8ec3d8fdd0d7.png">

Then it fails to turn on because it can't find an extension (Mock Debug):
<img width="484" src="https://user-images.githubusercontent.com/35271042/150691913-a665d9b4-3ed0-461a-bb99-4255c186a58b.png">

I even attempted to go to another machine with Settings Sync turned on to remove that extension and have no luck so I am blocked on turning on Settings Sync. I assume that [Mock Debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mock-debug) changed publishers?

```log
[2022-01-23 10:08:25.600] [settingssync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2022-01-23 10:08:25.708] [settingssync] [info] Auto Sync is enabled.
[2022-01-23 10:08:25.732] [settingssync] [info] Auto Sync: Suspended until auth token is available.
[2022-01-23 10:08:37.224] [settingssync] [info] Auto Sync: Started
[2022-01-23 10:08:37.277] [settingssync] [info] Auto Sync: Triggered by Interval
[2022-01-23 10:08:37.685] [settingssync] [error] TurnedOff (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot sync because syncing is turned off on this machine from another machine.
    at v.doSync (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:788:139332)
[2022-01-23 10:08:37.952] [settingssync] [info] Auto Sync: Disabled.
[2022-01-23 10:08:38.007] [settingssync] [info] Auto Sync: Stopped
[2022-01-23 10:08:38.034] [settingssync] [info] Did reset the local sync state.
[2022-01-23 10:08:38.147] [settingssync] [info] Auto Sync: Turned off sync because sync is turned off in the cloud
[2022-01-23 10:08:49.684] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-01-23 10:08:51.653] [settingssync] [info] Did reset the local sync state.
[2022-01-23 10:08:53.566] [settingssync] [error] Error: Error while fetching package.json for extension 'andreweinand.mock-debug' from the location 'https://andreweinand.vscode-unpkg.net/andreweinand/mock-debug/0.46.11/extension/package.json'. Error
    at P.toScannedExtension (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:16101)
    at async https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:14342
    at async Promise.all (index 27)
    at async P.scanInstalledExtensions (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:14297)
    at async P.scanUserExtensions (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:11888)
    at async S.getInstalled (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:1735)
    at async Promise.all (index 0)
    at async h.getInstalled (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3053:103801)
    at async Gr.generateSyncPreview (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:788:56307)
    at async Gr.doGenerateSyncResourcePreview (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:788:47540)
[2022-01-23 10:08:53.683] [settingssync] [info] Did reset the local sync state.
```

**Comment by hello-smile6** [comment]
> Went to a github repo and typed "." and attempted to turn on settings sync and ran into this issue with no way to resolve:
> 
> First it signed me out of all other sessions: <img alt="" width="484" src="https://user-images.githubusercontent.com/35271042/150691921-6bb0e5c4-ff19-4b82-8b46-8ec3d8fdd0d7.png">
> 
> Then it fails to turn on because it can't find an extension (Mock Debug): <img alt="" width="484" src="https://user-images.githubusercontent.com/35271042/150691913-a665d9b4-3ed0-461a-bb99-4255c186a58b.png">
> 
> I even attempted to go to another machine with Settings Sync turned on to remove that extension and have no luck so I am blocked on turning on Settings Sync. I assume that [Mock Debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mock-debug) changed publishers?
> 
> ```
> [2022-01-23 10:08:25.600] [settingssync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
> [2022-01-23 10:08:25.708] [settingssync] [info] Auto Sync is enabled.
> [2022-01-23 10:08:25.732] [settingssync] [info] Auto Sync: Suspended until auth token is available.
> [2022-01-23 10:08:37.224] [settingssync] [info] Auto Sync: Started
> [2022-01-23 10:08:37.277] [settingssync] [info] Auto Sync: Triggered by Interval
> [2022-01-23 10:08:37.685] [settingssync] [error] TurnedOff (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot sync because syncing is turned off on this machine from another machine.
>     at v.doSync (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:788:139332)
> [2022-01-23 10:08:37.952] [settingssync] [info] Auto Sync: Disabled.
> [2022-01-23 10:08:38.007] [settingssync] [info] Auto Sync: Stopped
> [2022-01-23 10:08:38.034] [settingssync] [info] Did reset the local sync state.
> [2022-01-23 10:08:38.147] [settingssync] [info] Auto Sync: Turned off sync because sync is turned off in the cloud
> [2022-01-23 10:08:49.684] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
> [2022-01-23 10:08:51.653] [settingssync] [info] Did reset the local sync state.
> [2022-01-23 10:08:53.566] [settingssync] [error] Error: Error while fetching package.json for extension 'andreweinand.mock-debug' from the location 'https://andreweinand.vscode-unpkg.net/andreweinand/mock-debug/0.46.11/extension/package.json'. Error
>     at P.toScannedExtension (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:16101)
>     at async https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:14342
>     at async Promise.all (index 27)
>     at async P.scanInstalledExtensions (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:14297)
>     at async P.scanUserExtensions (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:11888)
>     at async S.getInstalled (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3054:1735)
>     at async Promise.all (index 0)
>     at async h.getInstalled (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:3053:103801)
>     at async Gr.generateSyncPreview (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:788:56307)
>     at async Gr.doGenerateSyncResourcePreview (https://vscodeweb.azureedge.net/insider/23664355e61f3fb614932a5cb16613b4d987cfb7/out/vs/workbench/workbench.web.api.js:788:47540)
> [2022-01-23 10:08:53.683] [settingssync] [info] Did reset the local sync state.
> ```

Try running a server on localhost that mirrors that server and returns a different extension when that one is requested, then using `/etc/hosts` to send requests to that server to yours. It's messy, but it might work.

**Comment by misolori** [comment]
I ended up using the "Reset User Data" command in the web to reset everything as the old extension was cached after the initial sync, then removed it from another machine that was already synced, and re-synced on the web. If I didn't have access to the other machine, I'd need to permanently wipe my data and start over because I don't see another way to do this.

**Comment by hello-smile6** [comment]
> I ended up using the "Reset User Data" command in the web to reset everything as the old extension was cached after the initial sync, then removed it from another machine that was already synced, and re-synced on the web. If I didn't have access to the other machine, I'd need to permanently wipe my data and start over because I don't see another way to do this.

Oh. That's good.

**Comment by sandy081** [comment]
/duplicate

@misolori It seems you have mock-debug extension with version `0.46.11` installed which does not exist in Marketplace. These are the versions from the Marketplace for this extension

![image](https://user-images.githubusercontent.com/10746682/150836152-ad0b07cf-4a0e-40f6-9826-b4ca5ba87ad8.png)

Any idea how you installed this extension in web?

Irrespective of how it got installed, settings sync should not fail - I already have an issue tracking this - https://github.com/microsoft/vscode/issues/134224

Hence marking this as duplicate

**Comment by misolori** [comment]
No idea how it ever got installed but agree on that follow up issue that it should just ignore that extension.
