### ISSUE TITLE
Turning on Settings Sync results in 'Overlapping edit' error

### ISSUE THREAD

**Issue by hector-sanchez** [microsoft/vscode#141309]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
1.63.2
- OS Version:
macOS Monterey v.12.0.1

Steps to Reproduce:

1. On a fresh install, attempt to turn on Sync with all options to sync selected
2. I get the following error:

```[2022-01-24 12:16:29.841] [settingssync] [error] Error: Overlapping edit```
```
    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:3124)
    at f (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:94844)
    at m (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:93649)
    at v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:92350)
    at l.generateSyncPreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:98700)
    at async l.doGenerateSyncResourcePreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:48990)
```

I found [this thread](https://github.com/microsoft/vscode/issues/130595) but I am not sure what was the resolution there.

**Comment by hector-sanchez** [comment]
@sandy081 
My Settings Sync logs:

```[2022-01-24 12:52:09.584] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-01-24 12:52:09.584] [settingssync] [info] Auto Sync is disabled.
[2022-01-24 12:52:30.561] [settingssync] [info] Did reset the local sync state.
[2022-01-24 12:52:30.892] [settingssync] [error] Error: Overlapping edit
    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:3124)
    at f (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:94844)
    at m (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:93649)
    at v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:92350)
    at l.generateSyncPreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:98700)
    at async l.doGenerateSyncResourcePreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:48990)
[2022-01-24 13:32:35.140] [settingssync] [info] Did reset the local sync state.
[2022-01-24 13:32:35.367] [settingssync] [error] Error: Overlapping edit
    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:3124)
    at f (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:94844)
    at m (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:93649)
    at v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:92350)
    at l.generateSyncPreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:98700)
    at async l.doGenerateSyncResourcePreview (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:48990)
```

**Comment by sandy081** [comment]
Can you please provide following information:

- Provide the content of your user settings.json file
- F1 > Settings Sync: Show Synced Data
- Go to `...` menu on the top, expand views and enable Trouble Shoot View
- Go to `Sync Activity (Remote) view and select the first settings.json entry
- This opens the diff editor and provide us with the content in the right hand side editor of diff editor
- Go to Trouble shoot view and provide us with the content of Last Sync settings entry

Feel free to mail to me if you think it has sensitive info that cannot be shared here

**Comment by hector-sanchez** [comment]
I ran out of patience with this and decided to start all over.
