### ISSUE TITLE
Cannot have two actions with the same id editor.action.goToReferences

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141535]
Running our unit tests I see tons of exceptions printed like this one:

```
Error: Cannot have two actions with the same id editor.action.nextSelectionMatchFindAction
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:168:53
    at Array.forEach (<anonymous>)
    at new CodeEditorWidget (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:166:76)
    at new TestCodeEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/test/browser/testCodeEditor.js:11:13)
    at TestInstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at TestInstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at instantiateTestCodeEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/test/browser/testCodeEditor.js:134:45)
    at _withTestCodeEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/test/browser/testCodeEditor.js:77:40)
    at withAsyncTestCodeEditor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/test/browser/testCodeEditor.js:59:16)
    at Context.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/contrib/find/test/findController.test.js:429:64)
    at callFn (file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:21827:22)
    at Test.Runnable.run (file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:21813:6)
    at Runner.runTest (file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:23466:11)
    at file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:23597:13
    at next (file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:23374:15)
    at file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:23384:8
    at next (file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:23259:15)
    at file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:23351:6
    at timeslice (file:///Users/bpasero/Development/Microsoft/monaco/node_modules/mocha/mocha.js:29607:28)", source: /Users/bpasero/Development/Microsoft/monaco/test/unit/electron/renderer.js (191)
```

**Comment by alexdima** [comment]
@bpasero Are you running the tests somehow special? I don't see these messages when launching with `./scripts/test.sh`.

**Comment by bpasero** [comment]
Sorry I cannot reproduce anymore. Maybe I had bad compilation artefacts. I was running `scripts/test.sh > out.txt` to filter away the expected Mocha output from the unexpected spam we still have in tests. Stacktraces were appearing a lot in that case, but not anymore.
