### ISSUE TITLE
Running VSCode on a remote machine (remote display)

### ISSUE THREAD

**Issue by pansk** [Microsoft/vscode#14160]
- VSCode Version:

test@test:~$ code --version

1.6.1
9e4e44c19e393803e2b05fe2323cf4ed7e36880e

- OS Version:

test@test:~$ uname -a

Linux test 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Install vscode on a headless Linux machine
2. Install XMing Server on a Windows machine
3. connect to the Linux machine and export the display properly (test with xterm or any other X11 app)
4. Run vscode --verbose

Output:
[6492:1021/154155:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[6492:1021/154158:WARNING:audio_manager.cc(314)] Multiple instances of AudioManager detected
[6492:1021/154158:WARNING:audio_manager.cc(275)] Multiple instances of AudioManager detected
[6634:1021/154158:ERROR:gl_surface_glx.cc(386)] GLX 1.3 or later is required.
[6634:1021/154158:ERROR:gl_surface_x11.cc(252)] GLSurfaceGLX::InitializeOneOff failed.
[6634:1021/154158:ERROR:gpu_child_thread.cc(369)] Exiting GPU process due to errors during initialization
{ Error: ENOENT: no such file or directory, open '/home/test/.config/Code/storage.json'
    at Error (native)
    at Object.fs.openSync (original-fs.js:640:18)
    at Object.fs.readFileSync (original-fs.js:508:33)
    at e.load (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:9:2059)
    at e.getItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:9:1597)
    at e.handleUpdated (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:9:11350)
    at new e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:9:11251)
    at v (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:28052)
    at t._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:13168)
    at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:14143)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/test/.config/Code/storage.json' }
[main 3:41:58 PM] Starting VS Code in verbose mode
[main 3:41:58 PM] from: /usr/share/code/resources/app
[main 3:41:58 PM] args: { _: [],
  paths: [],
  performance: false,
  verbose: true,
  debugPluginHost: undefined,
  debugBrkPluginHost: undefined,
  logExtensionHostCommunication: false,
  'new-window': false,
  'reuse-window': false,
  goto: false,
  diff: false,
  extensionHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  'disable-extensions': false,
  'open-url': undefined,
  locale: undefined,
  wait: false }
[6492:1021/154158:ERROR:browser_main_parts.cc(126)] X IO error received (X server probably went away)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3451
