### ISSUE TITLE
Bad credentials is shown when the github extension fails to fetch repositories

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#141846]
```
HttpError: Bad credentials
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/github/dist/extension.js:2:24207
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at p.GithubRemoteSourceProvider.getUserRemoteSources (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/github/dist/extension.js:2:383837)
    at async Promise.all (index 1)
    at p.GithubRemoteSourceProvider.getRemoteSources (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/github/dist/extension.js:2:383623)
    at u.query (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git-base/dist/extension.js:1:9885)
```

My guess is that this could be a SAML issue... in which case you wanna re-request getSession() with the option: `forceNewSession` and try again.

The repro steps for this is hard... I think it's determined by how many SAML sessions you have active.... So if I had to guess... I think it would be:
* Sign in to github extension in VS Code Desktop
* Sign in to probably 10+ github* extensions across VS Code Desktop or vscode.dev (this is essentially invalidating the SAML session from bullet point 1 because you can only have a certain number of SAML sessions I think
* Try to use the github extension from bullet point 1

**Comment by jameskyker** [comment]
This is a SAML issue on my side. I saw it after re-authorizing my 2-factor on my cred in Github. Now, no matter what I do, re-install etc., I cannot use this plug-in.

**Comment by jameskyker** [comment]
To fix this, I edited that file in a hex editor and did a find/replace on _vscode-pull-request_ and replaced it with junk. The next time I opened up VSCode, it let me start the login over again and problem solved.

**Comment by Xunnamius** [comment]
Hello from the future. Thanks to @jameskyker's advice I was able to fix this strange issue. Ended up just deleting the `state.vscdb` file and redoing my custom UI and status bar changes before re-syncing vscode settings.

**Comment by tvanhove-gnrc** [comment]
I deleted my state.vscdb file to resolve these issues. I think it came up when our company started the organization in GitHub and then switched to SSO. I think that switch is when this broke.

**Comment by CSharpFiasco** [comment]
> I deleted my state.vscdb file to resolve these issues. I think it came up when our company started the organization in GitHub and then switched to SSO. I think that switch is when this broke.

This worked for me too. I found it here C:\Users\<username>\AppData\Roaming\Code\User\globalStorage

**Comment by lszomoru** [comment]
@TylerLeonhardt, let's chat about this as I would love to get this issue sorted out. Thanks!

**Comment by orlein** [comment]
I've tried `sign out` and `sign in` github in vscode, and everything works fine.
