### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by Asen-LoungeLogic** [microsoft/vscode#141992]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at getTargetOfExportSpecifier (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49193:17)
    at getTargetOfAliasDeclaration (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49243:28)
    at resolveAlias (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47648:21)
    at /Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at initializeTypeChecker (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85010:21)
    at Object.createTypeChecker (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Object.getProgram (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/Users/asennikolov/Visual Studio Code 2.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 11, 11|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 47f9855a-a626-42c9-8d1a-96c0d357c8df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-standardjs|che|1.4.1
mustache|daw|1.1.1
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
sass-lint|gle|1.0.7
json2csv|kha|0.0.1
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|2.0.0
xml-format|mik|1.1.2
vscode-android-webview-debug|mpo|1.2.0
remote-containers|ms-|0.209.6
debugger-for-chrome|msj|4.13.0
docthis|oou|0.8.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.3.0
gitconfig|sid|2.0.1
mdx|sil|0.1.0
autoimport|ste|1.5.4
tizentv|tiz|1.2.5
tizentvwasm|Tiz|1.1.1
vscode-ide-brightscript|wil|1.3.5
vscode-mdx-preview|xyc|0.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by IllusionMH** [comment]
/duplicate

Should be fixed in January 2022 release. In the meantime you can use Nightly TS version that contains fix: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next
