### ISSUE TITLE
ERR Cannot read properties of undefined (reading 'ordered')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141981]
I am using [exploration builds](https://builds.code.visualstudio.com/builds/exploration) which already have our latest code from `main` and TypeScript is broken in this build, pretty much nothing works in the editor other than syntax highlight and editing. The devtools shows:

```
 ERR Cannot read properties of undefined (reading 'ordered'): TypeError: Cannot read properties of undefined (reading 'ordered')
    at h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:35779)
    at w._compute (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:36704)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:36087
    at E (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:75:11024)
    at new C (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:36078)
    at new w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:36648)
    at T (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:37228)
    at R._run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:40964)
    at R._onPositionChanged (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:40170)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:783:37964
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1712)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:735:18497
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1712)
    at _emitOutgoingEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:203:119469)
    at _.endEmitViewEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:203:120165)
    at u._withViewEventsCollector (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:733:5417)
    at u.setCursorStates (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:733:2199)
    at R.runCoreEditorCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:679:25150)
    at A.moveTo (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:679:52769)
    at A.dispatchMouse (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:679:52580)
    at p._dispatchMouse (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:643:20064)
    at p.start (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:643:17816)
    at v._onMouseDown (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:643:15604)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:643:12890
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:640:32111)
```

I think the origin is: https://github.com/microsoft/vscode/blob/aa5e35f7f2ae4ed3b237c8de97bd9188478dd7d1/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L45

**Comment by jrieken** [comment]
The problem is that abstract `OccurenceAtPositionRequest` invokes _compute in its constructor, making it hard to sub-typed to initialize more fields

<img width="741" alt="Screen Shot 2022-02-02 at 09 51 28" src="https://user-images.githubusercontent.com/1794099/152122181-3af07ebd-608d-4525-9642-f27b17b86f48.png">
