### ISSUE TITLE
'omnisharp:fixscripts' errored  ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by dove-young** [Microsoft/vscode#142]
Environment is Fedora 22 x86-64 Python 2.7.10

download and unpack 0.10.1 source code
````
cd ~/tmp/vscode-0.10.1
sudo npm install -g mocha gulp
./scripts/npm.sh install --arch=x64
````
then you'll get into this error after a few minutes
````
> csharp-o@0.1.0 postinstall /home/dove/tmp/vscode-0.10.1/extensions/csharp-o
> node ./node_modules/gulp/bin/gulp.js omnisharp

[11:45:17] Using gulpfile /home/dove/tmp/vscode-0.10.1/extensions/csharp-o/gulpfile.js
[11:45:17] Starting 'omnisharp:clean'...
[11:45:17] Finished 'omnisharp:clean' after 5.84 ms
[11:45:17] Starting 'omnisharp:fetch'...
[gulp] Downloading https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.5.6/omnisharp.tar.gz... 1% 4% 17% 48% 71% 97% Done
[11:45:27] Finished 'omnisharp:fetch' after 10 s
[11:45:27] Starting 'omnisharp:fixscripts'...
[11:45:27] 'omnisharp:fixscripts' errored after 174 μs
[11:45:27] ReferenceError: Promise is not defined
    at /home/dove/tmp/vscode-0.10.1/extensions/csharp-o/gulpfile.js:40:14
    at Array.map (native)
    at Gulp.<anonymous> (/home/dove/tmp/vscode-0.10.1/extensions/csharp-o/gulpfile.js:39:37)
    at module.exports (/home/dove/tmp/vscode-0.10.1/extensions/csharp-o/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/dove/tmp/vscode-0.10.1/extensions/csharp-o/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/dove/tmp/vscode-0.10.1/extensions/csharp-o/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /home/dove/tmp/vscode-0.10.1/extensions/csharp-o/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/home/dove/tmp/vscode-0.10.1/extensions/csharp-o/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /home/dove/tmp/vscode-0.10.1/extensions/csharp-o/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/home/dove/tmp/vscode-0.10.1/extensions/csharp-o/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
npm ERR! weird error 1
npm ERR! not ok code 0
npm ERR! weird error 1
npm ERR! not ok code 0


````

**Comment by WanderWang** [comment]
node v4.0.0 support Promise . please upgrade your node

**Comment by jrieken** [comment]
Correct, a recent version of nodejs is required.

**Comment by jrieken** [comment]
Will add a requirement to `package.json`
