### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by s-lipatov** [microsoft/vscode#142070]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at getTargetOfAliasLikeExpression (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49210:29)
    at getTargetOfExportAssignment (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49199:28)
    at getTargetOfAliasDeclaration (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49246:28)
    at resolveAlias (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at resolveExternalModuleSymbol (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49763:36)
    at getTargetOfNamespaceExportDeclaration (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49186:28)
    at getTargetOfAliasDeclaration (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49248:28)
    at resolveAlias (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at initializeTypeChecker (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85010:21)
    at Object.createTypeChecker (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Object.getProgram (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-27-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-5545M APU with Radeon(tm) HD Graphics (4 x 1696)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|6, 7, 6|
|Memory (System)|14.83GB (2.42GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 3f589526-df46-42ca-b61b-7ce8b40af17a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
svg|joc|1.4.15
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.209.6
vscode-react-native|msj|1.9.0
docker-compose|p1c|0.3.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
wslgetstartedc:30426334
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by IllusionMH** [comment]
/duplicate

Should be fixed in January 2022 release. In the meantime you can use Nightly TS version that contains fix: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next
