### ISSUE TITLE
Error building Visual Studio Code on Linux (dependencies)

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#14205]
- VSCode Version: code-oss-dev@1.7.0 (source from Oct 22nd)
- OS Version: Linux Mint 17.3 Rosa

Steps to Reproduce:

- [x] Following [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute)
- [x] Install prerequisites :thumbsup:
    - [x] Git v1.9.1
    - [x] Node v6.6.0
    - [x] Python v2.7
    - [x] g++
    - [x] libx11-dev
    - [x] fakeroot
    - [x] rpm
- [ ] Install dependencies: `./scripts/npm.sh install` :thumbsdown:

As you can see below, there is a problem with the TypeScript postinstall.  I have no idea why.  Note that `/home/jez/Development/vscode/extensions/typescript/node_modules` exists, but `/home/jez/Development/vscode/extensions/typescript/node_modules/typescript` doesn't:

```
jez@jez-MINT-PC ~/Development/vscode $ ./scripts/npm.sh install
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> code-oss-dev@1.7.0 preinstall /home/jez/Development/vscode
> node build/npm/preinstall.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> code-oss-dev@1.7.0 postinstall /home/jez/Development/vscode
> node build/npm/postinstall.js


> vscode-api-tests@0.0.1 postinstall /home/jez/Development/vscode/extensions/vscode-api-tests
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: *
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/vscode.d.ts
vscode.d.ts successfully installed!


> vscode-colorize-tests@0.0.1 postinstall /home/jez/Development/vscode/extensions/vscode-colorize-tests
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: *
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/vscode.d.ts
vscode.d.ts successfully installed!


> json@0.1.0 postinstall /home/jez/Development/vscode/extensions/json
> cd server && npm install

npm WARN vscode-json-languageserver@1.0.0 No repository field.
npm WARN json@0.1.0 No description
npm WARN json@0.1.0 No repository field.
npm WARN json@0.1.0 No license field.
npm WARN configuration-editing@0.0.1 No description
npm WARN configuration-editing@0.0.1 No repository field.
npm WARN configuration-editing@0.0.1 No license field.

> extension-editing@0.0.1 postinstall /home/jez/Development/vscode/extensions/extension-editing
> node ./postinstall

npm WARN extension-editing@0.0.1 No description
npm WARN extension-editing@0.0.1 No repository field.
npm WARN extension-editing@0.0.1 No license field.
npm WARN vscode-markdown@0.2.0 No repository field.
npm WARN vscode-markdown@0.2.0 No license field.

> typescript@0.10.1 postinstall /home/jez/Development/vscode/extensions/typescript
> node ./bin/postinstall

fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/jez/Development/vscode/extensions/typescript/node_modules/typescript/lib'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.<anonymous> (/home/jez/Development/vscode/extensions/typescript/bin/postinstall.js:13:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)

npm WARN typescript@0.10.1 No repository field.
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/opt/node-v6.6.0-linux-x64/bin/node" "/opt/node-v6.6.0-linux-x64/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v4.0.0
npm ERR! code ELIFECYCLE
npm ERR! typescript@0.10.1 postinstall: `node ./bin/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript@0.10.1 postinstall script 'node ./bin/postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls typescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jez/Development/vscode/extensions/typescript/npm-debug.log
npm WARN php@0.1.0 No description
npm WARN php@0.1.0 No repository field.
npm WARN php@0.1.0 No license field.
npm WARN javascript@0.1.0 No description
npm WARN javascript@0.1.0 No repository field.
npm WARN javascript@0.1.0 No license field.

> css@0.1.0 postinstall /home/jez/Development/vscode/extensions/css
> cd server && npm install

npm WARN vscode-css-languageserver@1.0.0 No repository field.
npm WARN css@0.1.0 No description
npm WARN css@0.1.0 No repository field.
npm WARN css@0.1.0 No license field.

> html@0.1.0 postinstall /home/jez/Development/vscode/extensions/html
> cd server && npm install

npm WARN vscode-html-languageserver@1.0.0 No repository field.
npm WARN html@0.1.0 No description
npm WARN html@0.1.0 No repository field.
npm WARN html@0.1.0 No license field.
```

**Comment by roblourens** [comment]
I'd recommend running `git clean` to delete all node_modules and running install again in case it got into a corrupted state

**Comment by jez9999** [comment]
I did better than that - I cloned it from scratch and it still gave me the same error.

**Comment by roblourens** [comment]
Are there any node_modules in `extensions/typescript`? What if you run `npm install` from that folder?

**Comment by joaomoreno** [comment]
Can you try with npm 3.10.8?

**Comment by jez9999** [comment]
@joaomoreno I'm already using npm v4.0.0.

@roblourens There is a `node_modules` in the `typescript` dir, but not `typescript` (why would `typescript` contain itself in `node_modules`?)  An `npm install` from that folder gives me:

```
jez@jez-MINT-PC ~/Development/vscode/extensions/typescript $ npm install

> typescript@0.10.1 postinstall /home/jez/Development/vscode/extensions/typescript
> node ./bin/postinstall

fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/jez/Development/vscode/extensions/typescript/node_modules/typescript/lib'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.<anonymous> (/home/jez/Development/vscode/extensions/typescript/bin/postinstall.js:13:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)

npm WARN typescript@0.10.1 No repository field.
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/opt/node-v6.6.0-linux-x64/bin/node" "/opt/node-v6.6.0-linux-x64/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v4.0.0
npm ERR! code ELIFECYCLE
npm ERR! typescript@0.10.1 postinstall: `node ./bin/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript@0.10.1 postinstall script 'node ./bin/postinstall'.
```

**Comment by joaomoreno** [comment]
Please try 3.10.8.

**Comment by jez9999** [comment]
Seriously?  How am I meant to downgrade?

**Comment by joaomoreno** [comment]
`npm install -g npm@3.10.8`

**Comment by jez9999** [comment]
OK it works with npm `3.10.8`.  So there's a regression in npm `4.0.0`.

**Comment by joaomoreno** [comment]
I'll close since we don't support npm 4 yet. Once we get there let's hope the issue is resolved or fix it.
