### ISSUE TITLE
Python kernel dies whenever I stop a cell from executing after installing cuDNN and CUDA

### ISSUE THREAD

**Issue by eduardoftdo** [microsoft/vscode#142271]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:
After installing CUDA 11.5.2 and cuDNN 8.3.2 I can see my GPU listed and can use it to train models, but whenever I try to stop a cell from executing, the Python kernel dies. Is it possible to use those libraries in VS Code?

Error log:
```
Info 11:02:10: Raw session started and connected
Started kernel Python 3.9.10 64-bit
Info 11:02:10: Finished connecting e8c4b286-bcfd-4202-85e9-4ba660c54a9d
Info 11:02:10: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 11:02:10: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 11:02:10: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = 'Untitled-1.ipynb'\n%con
Info 11:02:10: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = 'Untitled-1.ipynb'\n%con
Info 11:02:10: Waiting for idle on (kernel): 06fe8f6a-ff35-405e-8445-1a7356662d15 -> idle
Info 11:02:10: Finished waiting for idle on (kernel): 06fe8f6a-ff35-405e-8445-1a7356662d15 -> idle
Info 11:07:05: Execute Cells request 0
Info 11:07:05: Execute Cell 0 untitled:Untitled-1.ipynb?jupyter-notebook
Info 11:07:07: Cell 0 executed with state Success
Info 11:07:08: Execute Cells request 1
Info 11:07:08: Execute Cell 1 untitled:Untitled-1.ipynb?jupyter-notebook
Info 11:07:08: Cell 1 executed with state Success
Info 11:07:10: Restart requested untitled:Untitled-1.ipynb?jupyter-notebook
Info 11:07:10: Restart kernel execution
Info 11:07:10: Cancel pending cells
Info 11:07:10: Starting raw kernel Python 3.9.10 64-bit
Info 11:07:10: installMissingDependencies ~\AppData\Local\Programs\Python\Python39\python.exe
Info 11:07:10: IPykernel found previously in this environment ~\AppData\Local\Programs\Python\Python39\python.exe
Info 11:07:10: Restarting 06fe8f6a-ff35-405e-8445-1a7356662d15
Info 11:07:10: Kernel launching with ports 9005,9006,9007,9008,9009. Start port is 9000
Info 11:07:10: No custom variables for Kernel as interpreter is not conda, but is Global
Info 11:07:10: Process Execution: > ~\AppData\Local\Programs\Python\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\AppData\Local\Programs\Python\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 11:07:10: Process Execution: > ~\AppData\Local\Programs\Python\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"1612b373-3967-4262-8175-bb6c383558cc" --shell=9007 --transport="tcp" --iopub=9009 --f=C:\Users\Eduardo\AppData\Local\Temp\tmp-20800MvmEelBBmUJ4.json
> ~\AppData\Local\Programs\Python\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"1612b373-3967-4262-8175-bb6c383558cc" --shell=9007 --transport="tcp" --iopub=9009 --f=C:\Users\Eduardo\AppData\Local\Temp\tmp-20800MvmEelBBmUJ4.json
Info 11:07:10: Process Execution: cwd: c:\Users\Eduardo\OneDrive\Documentos\Code
cwd: c:\Users\Eduardo\OneDrive\Documentos\Code
Info 11:07:10: ipykernel version 6.8.0 for ~\AppData\Local\Programs\Python\Python39\python.exe
Info 11:07:10: ipykernel location ~\AppData\Roaming\Python\Python39\site-packages\ipykernel\__init__.py for ~\AppData\Local\Programs\Python\Python39\python.exe
Warn 11:07:11: StdErr from Kernel Process C:\Users\Eduardo\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

Warn 11:07:11: StdErr from Kernel Process C:\Users\Eduardo\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1612b373-3967-4262-8175-bb6c383558cc' instead of 'b"1612b373-3967-4262-8175-bb6c383558cc"'.
  warn(

Info 11:07:11: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing C:\Users\Eduardo\AppData\Local\Temp\tmp-20800MvmEelBBmUJ4.json

Info 11:07:11: Got new session 227ad9c5-41a1-4ada-a7ec-1554cc2d9743
Info 11:07:11: Started new restart session
Info 11:07:11: Dispose Kernel process
Info 11:07:11: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 11:07:11: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 11:07:11: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = 'Untitled-1.ipynb'\n%con
Info 11:07:11: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = 'Untitled-1.ipynb'\n%con
Info 11:07:11: Waiting for idle on (kernel): 227ad9c5-41a1-4ada-a7ec-1554cc2d9743 -> idle
Info 11:07:11: Finished waiting for idle on (kernel): 227ad9c5-41a1-4ada-a7ec-1554cc2d9743 -> idle
Info 11:07:14: Execute Cells request 0
Info 11:07:14: Execute Cell 0 untitled:Untitled-1.ipynb?jupyter-notebook
Info 11:07:14: Interrupt requested untitled:Untitled-1.ipynb?jupyter-notebook
Info 11:07:14: Interrupt requested & sent for untitled:Untitled-1.ipynb?jupyter-notebook in notebookEditor.
Info 11:07:14: Interrupt kernel execution
Info 11:07:14: Cancel pending cells
Info 11:07:14: Interrupting kernel: python3910jvsc74a57bd0d1923312bdd1ecdaed4c03ef9f030b61bfc0be630f081d4aef47785cf6a28ea0
Info 11:07:14: Interrupting kernel via Signals
Error 11:07:14: Disposing session as kernel process died ExitCode: 1, Reason: C:\Users\Eduardo\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
C:\Users\Eduardo\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1612b373-3967-4262-8175-bb6c383558cc' instead of 'b"1612b373-3967-4262-8175-bb6c383558cc"'.
  warn(

Info 11:07:14: Dispose Kernel process
Error 11:07:14: Raw kernel process exited code: 1
Error 11:07:14: Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:51:432353)
    at c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:66:307599
    at Map.forEach (<anonymous>)
    at y._clearKernelState (c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:66:307585)
    at y.dispose (c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:66:301017)
    at c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:51:194444
    at t.swallowExceptions (c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:16:2495)
    at dispose (c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:51:194423)
    at t.RawSession.dispose (c:\Users\Eduardo\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:113:303296)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Info 11:07:14: Cancel all remaining cells true || Success
Info 11:07:14: Cancel pending cells
Info 11:07:14: Cell 0 executed with state Success
```

**Comment by Chellio** [comment]
I also started having the same issues just today.  Following this in the hopes of finding a solution.
