### ISSUE TITLE
Source control is empty 

### ISSUE THREAD

**Issue by polouis** [microsoft/vscode#142259]
My source control is empty.
I can see that my source control repository is listed and the count badge showing the number of pending changes properly.
I have theses errors in the console : 
```
ERR Invalid comparison: Error: Invalid comparison
    at ke.compare (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:2350:15111)
    at Object.compare (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:87569)
    at Object.compare (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:78387)
    at Array.sort (<anonymous>)
    at M.preserveCollapseState (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:79326)
    at M.setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:78595)
    at l._setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:84914)
    at l.setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:84032)
    at g.setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:88425)
    at Q.setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:192:8634)
log.ts:313   ERR Unknown compressed tree node: Error: Unknown compressed tree node
    at l.setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:84142)
    at g.setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:70:88425)
    at Q.setChildren (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:192:8634)
    at Be.refresh (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:2350:27372)
    at Be._onDidSpliceGroup (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:2350:25889)
    at https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:2350:25406
    at l.fire (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:69:1712)
    at v.splice (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:1527:33602)
    at d.$spliceGroupResourceStates (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:1527:36415)
    at n.$spliceResourceStates (https://vscodeweb.azureedge.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/workbench.web.api.js:1527:38659)
```

This looks like #138734 which is fixed in 1.64 but my vscode embeded in codespace is in 1.63.2. 

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
Embedder: codespaces

**Comment by AriPerkkio** [comment]
I'm also seeing this issue in some of my Codespaces. It's a bit weird that Source Control of some Codespaces still work properly even though all of them have the same VSCode version `1.63.2`. I'm not sure what's triggering this error. 

Any known work-arounds for this? Is there a way to downgrade VSCode version in Github Codespaces?

**Comment by polouis** [comment]
VSCode has been updated to Version: 1.64.2 and the problem is solved. Thanks !
