### ISSUE TITLE
Debugger "internalConsole" broken in 1.64

### ISSUE THREAD

**Issue by CynicalBusiness** [microsoft/vscode#142292]
Issue Type: <b>Bug</b>

When attempting to start the debugger, both with `node/launch` and `chrome/attach`, the `internalConsole` does not function. The application still start/attaches successfully, just without a working console; the console simply displays old output from before upgrading to 1.64.

This previously worked without issue in 1.63.x. For `node/launch`, changing the console to `integratedTerminal` works (though not ideal), but that doesn't help me for `chrome/attach`.

The output shows an error when the debugger is started:
<details>
<summary>Log (Window)</summary>

```
[2022-02-05 21:14:26.527] [renderer1] [error] TreeError [DebugRepl] Tree element not found: [object Object]: Error: TreeError [DebugRepl] Tree element not found: [object Object]
    at A.getElementLocation (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:82:20311)
    at A.isCollapsed (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:82:19448)
    at I.isCollapsed (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:201:676)
    at K.setChildren (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:201:21791)
    at K.doRefreshNode (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:201:20918)
    at async K.doRefreshSubTree (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:201:20470)
    at async K.refreshAndRenderNode (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:201:20022)
    at async K._updateChildren (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:201:17119)
    at async K.setInput (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:201:16562)
    at async hr.selectSession (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1852:1074)
    at async hr.onDidFocusSession (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1844:5822)
```
My username has been replaced with `user`
</details>

<details>
<summary>Current `launch.json`</summary>

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "app",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}/packages/app",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
            },
            "env": {
                "DEBUG": "horizon:*"
            },
            "outFiles": ["${workspaceFolder}/packages/app/lib/**/*.js"],
            "autoAttachChildProcesses": true,
            "sourceMaps": true,
            "runtimeArgs": ["--remote-debugging-port=9333"],
            "args": ["./lib/main.js", "--enableDevTools", "--profile", "Debug"],
            "presentation": {
                "hidden": false,
                "group": "proc",
                "order": 1
            }
        },
        {
            "name": "client",
            "type": "chrome",
            "request": "attach",
            "port": 9333,
            "timeout": 60000,
            "webRoot": "${workspaceFolder}",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///./~/*": "${workspaceFolder}/node_modules",
                "webpack:///./*": "${workspaceFolder}/*",
                "webpack:///*": "*"
            },
            "presentation": {
                "hidden": false,
                "group": "proc",
                "order": 2
            }
        }
    ]
}
```
</details>

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (6.02GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 4e827929-147b-4b09-b497-92eb6ff064f6|
|Screen Reader|no|
|VM|0%|
</details>
Extensions disabled
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by CynicalBusiness** [comment]
@connor4312 I went to capture the GIF for you but am no longer able to reproduce the issue anymore, it seems. It may likely be an edge case between our app's logging and VSC (and not entirely be VSC's fault), as our logger has been changed a bit since then to be more simple.

Can probably close the issue for now, and I'll either re-open or file a new issue if it crops up again.

**Comment by connor4312** [comment]
Sounds good, thanks for the issue!
