### ISSUE TITLE
Version 1.64.0 breaks remote container development

### ISSUE THREAD

**Issue by nikhilogic** [microsoft/vscode#142235]
Issue Type: <b>Bug</b>

Version 1.64.0 breaks remote container development. 
Opening a folder in the container fails as vscode server is unable to be downloaded.
See below error for terminal:
[823 ms] Start: Run in container: test -d /root/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9
[825 ms] 
[826 ms] 
[826 ms] Exit code 1
[826 ms] Installing VS Code Server for commit 5554b12acf27056905806867f251c859323ff7e9
[826 ms] Start: Downloading VS Code Server
[826 ms] 5554b12acf27056905806867f251c859323ff7e9 linux-x64 stable 
[1387 ms] Error: Client network socket disconnected before secure TLS connection was established
        at connResetException (internal/errors.js:607:14)
        at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
        at TLSSocket.emit (events.js:327:22)
        at endReadableNT (internal/streams/readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
[1387 ms] Exit code ECONNRESET

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_475252 --crash-reporter-id 507e6318-2d7f-43d6-aa3b-dda35c936790|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-peacock|joh|4.0.0
vscode-docker|ms-|1.19.0
vscode-edge-devtools|ms-|1.4.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-concourse|Piv|1.31.0
vscode-manifest-yaml|Piv|1.31.0
vscode-spring-boot|Piv|1.31.0
java|red|1.3.0
svg-preview|Sim|2.8.3
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0

</details>

**Comment by nikhilogic** [comment]
Issue Referenced by these : 
 #142201 #142324  #142207

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/142201.
