### ISSUE TITLE
When clicked a link that terminal showed with pressing cmd key, it happened nothing

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#142363]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.65.0-insider (Universal) (62de8dc3f78b8bef1eb62deeb093164a8d76c254)
- OS Version: Darwin x64 21.2.0

Steps to Reproduce:

1. Install GitHub Pull Request extension (github.vscode-pull-request-github)
2. some branch push to github
3. click links to create new pull request

![github-ext](https://user-images.githubusercontent.com/1955233/152712536-72ac60ed-673f-4d5e-ac3f-f87b2d9442f9.gif)

It works with the stable version, so I think it was something that was changed in VS Code Insider, but what about it?
I tried extension v0.34.3 and v0.36.0 (current) and preview, but all broken on insiders.

I'm checking the PR of link and terminal now.

`Log (Window)` showed below logs.

```
[2022-02-07 10:52:22.549] [renderer3] [error] No matching opener for link type "[object Object]": Error: No matching opener for link type "[object Object]"
    at u._openLink (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1709:11398)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1709:11119
    at c.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1826)
    at C._activateCallback (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1202:7492)
    at C.activate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1202:4311)
    at t._onClick (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:28563)
```

**Comment by Tyriar** [comment]
I saw this happen once, not sure how to reproduce though. To workaround I think you can just move the cursor up/down the terminal and it'll probably work, if not try close/open the panel.

**Comment by yamachu** [comment]
> you can just move the cursor up/down the terminal and it'll probably work, if not try close/open the panel.

This workaround is not worked.

<img width="1550" alt="スクリーンショット 2022-02-08 12 18 02" src="https://user-images.githubusercontent.com/1955233/152911874-a4cf404c-56e0-43c2-9816-51dc2d3593c6.png">

I used a debugger to check the values ​​passed.
A value that is compatible with ITerminalExternalLinkType is passed, but it seems that it is crashing because the Oepner corresponding to _oepner is not passed.
https://github.com/microsoft/vscode/blob/0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L88-L92
It seems that it is set here, but where will the Opener added by the extension be set?

**Comment by Tyriar** [comment]
@yamachu thanks for looking into it. I think guess the `{ id: ... }` link type isn't handled properly yet.

**Comment by yamachu** [comment]
I checked this issue on Version: 1.65.0-insider (Universal) Commit: d09aeab62c1f93acf4a89b93e9a8a82419d6249a .
It worked properly, thanks!

**Comment by Tyriar** [comment]
@yamachu thanks for verifying
