### ISSUE TITLE
regexp execution crashes during debugging

### ISSUE THREAD

**Issue by thqby** [microsoft/vscode#142332]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (system setup)
- OS Version: Windows_NT x64 10.0.22000

When I was debugging the LSP plug-in, it crashed when I step through the regexp.
```typescript
// const classexp = /^\s*((class\s+(\w|[^\x00-\xff])+\s+)?(extends)|class)\s/i;
if (temp = classexp.exec(lt)) {
}
```
This is error output:
```
rejected promise not handled within 1 second: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
stack trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at Socket.write (internal/streams/writable.js:294:11)
	at e:\Documents\Code\vscode-autohotkey2-lsp\node_modules\vscode-jsonrpc\lib\node\ril.js:90:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (e:\Documents\Code\vscode-autohotkey2-lsp\node_modules\vscode-jsonrpc\lib\node\ril.js:80:16)
	at SocketMessageWriter.doWrite (e:\Documents\Code\vscode-autohotkey2-lsp\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:100:33)
	at e:\Documents\Code\vscode-autohotkey2-lsp\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:91:29
```
and [Extension Development Host]'s error output: `Connection to server is erroring. Shutting down server.`

**Comment by weinand** [comment]
This is an exception thrown in the program you are debugging and not a VS Code problem.
