### ISSUE TITLE
Terminal Issue

### ISSUE THREAD

**Issue by Aero2003** [microsoft/vscode#142480]
terminated with exit code: 3221225477.

 Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.MulticastDelegate.CombineImpl(Delegate follow)
   at System.AppDomain.add_DomainUnload(EventHandler value)
   at System.Threading.Tasks.TaskExceptionHolder.EnsureADUnloadCallbackRegistered()
   at System.Threading.Tasks.Task.AddException(Object exceptionObject, Boolean representsCancellation)
   at System.Threading.Tasks.Task.HandleException(Exception unhandledException)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)        
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by alexr00** [comment]
@Aero2003 can you provide steps to reproduce your issue?
