### ISSUE TITLE
code update caused inability to start code 

### ISSUE THREAD

**Issue by jodyhey** [microsoft/vscode#142643]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  (see below)
- OS Version:    Ubuntu 18.04.4 LTS  in windows WSL,   Windows  version 2004 OS Build 19041.1415)

Steps to Reproduce:  - SEE what happened below when code updated 

1.
2.

I  was using code all morning,  and then closed out.   I went to restart and typed 'code .' at the command line and this happened (complete command line history below):

(base) jodyhey:/mnt/h/genemod/human_ancestral/refseq_ids_ravi_patel/jhwork$ code .
Installing VS Code Server for x64 (5554b12acf27056905806867f251c859323ff7e9)
Downloading: 100%
Unpacking: 100%
Unpacked 2158 files and folders to /home/jodyhey/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9.
/mnt/c/Users/jodyhey/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /mnt/c/Users/jodyhey/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: /home/jodyhey/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found
(base) jodyhey:/mnt/h/genemod/human_ancestral/refseq_ids_ravi_patel/jhwork$ code .
/mnt/c/Users/jodyhey/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /mnt/c/Users/jodyhey/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: /home/jodyhey/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found
(base) jodyhey:/mnt/h/genemod/human_ancestral/refseq_ids_ravi_patel/jhwork$ cd ~
(base) jodyhey:~$ code .
/mnt/c/Users/jodyhey/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /mnt/c/Users/jodyhey/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: /home/jodyhey/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found

**Comment by jodyhey** [comment]
Sorry if I was not clear.   Code is not running,  and cannot be started (because it can't be found presumably)   Not sure what it means to disable extensions in this context.

**Comment by eevmanu** [comment]
After running `code-insiders` command with `--disable-extensions` and `--verbose`, the only thing I found that could give any clue is:

```bash
/usr/share/code-insiders/code-insiders --disable-extensions --verbose --enable-crashpad: symbol lookup error: 
/usr/share/code-insiders/resources/app/node_modules.asar.unpacked/vscode-encrypt/build/Release/vscode-encrypt-native.node: undefined symbol: SHA256_Init
```

not sure if it helps though

**Comment by mkikets99** [comment]
additional info:
It is working, but not shown... if check running processes its still running, but maybe GUI crashed.

A some parts of verbose from my VS Code Insiders:
```
[90m[main 2022-02-09T17:17:07.335Z][0m [File Watcher (node.js)] Request to start watching: /home/mkikets/.config/Code - Insiders/User (excludes: <none>),/home/mkikets/.config/Code - Insiders/User/settings.json (excludes: <none>)
[90m[main 2022-02-09T17:17:07.358Z][0m Starting VS Code
[90m[main 2022-02-09T17:17:07.359Z][0m from: /usr/share/code-insiders/resources/app
[90m[main 2022-02-09T17:17:07.359Z][0m args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '4f0789cf-a168-418e-b126-db3d01136a67',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/mkikets/.config/Code - Insiders/logs/20220209T191707'
}
[90m[main 2022-02-09T17:17:07.360Z][0m Resolving machine identifier...
[90m[main 2022-02-09T17:17:07.361Z][0m Resolved machine identifier: 238dc951913cae5d59463b773698eb76101dfd4714dc89dce52d2e1acb70508f
[90m[main 2022-02-09T17:17:07.362Z][0m Main->SharedProcess#connect
[90m[main 2022-02-09T17:17:07.366Z][0m [File Watcher (node.js)] Started watching: '/home/mkikets/.config/Code - Insiders/User'
[90m[main 2022-02-09T17:17:07.367Z][0m [File Watcher (node.js)] Started watching: '/home/mkikets/.config/Code - Insiders/User/settings.json'
[90m[main 2022-02-09T17:17:07.373Z][0m StorageMainService: creating global storage
[90m[main 2022-02-09T17:17:07.381Z][0m lifecycle (main): phase changed (value: 2)
[90m[main 2022-02-09T17:17:07.382Z][0m windowsManager#open
[90m[main 2022-02-09T17:17:07.387Z][0m windowsManager#open pathsToOpen [
  {
    workspace: { id: '2e301ae9bbde43b6f87332728e3e3e15', configPath: [h] },
    type: 1,
    exists: true,
    remoteAuthority: undefined,
    transient: undefined
  },
  {
    workspace: { id: 'b4f64cfdc6c74e5e33d6d9b94d6a7e24', uri: [h] },
    type: 2,
    exists: true
  },
  {
    workspace: { id: '78b412bcabf3baf12063581d19177ce5', uri: [h] },
    type: 2,
    exists: true
  },
  {
    workspace: { id: '1ed3474b00603e5415781ac51c8dd820', uri: [h] },
    type: 2,
    exists: true
  },
  {
    workspace: { id: '78b412bcabf3baf12063581d19177ce5', uri: [h] },
    type: 2,
    exists: true
  }
]
[90m[main 2022-02-09T17:17:07.388Z][0m windowsManager#doOpenFolderOrWorkspace {
  folderOrWorkspace: {
    workspace: { id: '2e301ae9bbde43b6f87332728e3e3e15', configPath: [h] },
    type: 1,
    exists: true,
    remoteAuthority: undefined,
    transient: undefined
  },
  filesToOpen: undefined
```
```
[7155:0209/191712.649564:INFO:CONSOLE(71)] "%c[Extension Host] %cactivating extension %c(at Object.<anonymous> (/home/mkikets/.vscode-insiders/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:39266:21)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.649615:INFO:CONSOLE(71)] "%c[Extension Host] %cstarting language server %c(at Object.<anonymous> (/home/mkikets/.vscode-insiders/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:39277:17)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.651543:INFO:CONSOLE(1)] "[uncaught exception]: TypeError: setTimeout(...).unref is not a function", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/bootstrap-window.js (1)
[7155:0209/191712.651775:INFO:CONSOLE(1)] "TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (/usr/share/code-insiders/resources/app/node_modules.asar/applicationinsights/out/Library/Sender.js:100:117)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/bootstrap-window.js (1)
[7155:0209/191712.653594:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 Webview(459306bb-cb1e-408c-900c-791de9d83184): will update content", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.656060:INFO:CONSOLE(605)] "%cTRACE color: #888 Settings Sync: Updated accounts for microsoft", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.656120:INFO:CONSOLE(605)] "%cTRACE color: #888 Settings Sync: Getting accounts for github", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.709424:INFO:CONSOLE(29)] "%cTRACE color: #888 Scanned system extensions: 87", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[7155:0209/191712.814200:INFO:CONSOLE(29)] "%cTRACE color: #888 Started scanning system extensions", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[7155:0209/191712.814237:INFO:CONSOLE(29)] "%cTRACE color: #888 Started scanning user extensions", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[7155:0209/191712.820132:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/bootstrap.min.css", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.820423:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/bootstrap.min.css, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.822760:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/main.css", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.822817:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/main.css, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.823168:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/codicon.css", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.824083:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/codicon.css, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.824134:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/jquery-3.5.1.slim.min.js", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.824161:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/jquery-3.5.1.slim.min.js, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.824218:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/jquery.lazy.min.js", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.824754:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/jquery.lazy.min.js, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.825874:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/popper.min.js", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.825968:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/popper.min.js, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.826494:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/bootstrap.min.js", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.826538:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/bootstrap.min.js, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.827373:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/gifffer.js", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.827417:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/gifffer.js, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.827766:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/main.js", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.827803:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/main.js, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.828281:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/images/logo.svg", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.828463:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/images/logo.svg, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.829072:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.829113:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.829418:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - begin. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/youtube.png", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.829473:INFO:CONSOLE(605)] "%cDEBUG background: #eee; color: #888 loadLocalResource - found resource to load. requestUri=file:///home/mkikets/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.443/media/youtube.png, resourceToLoad=undefined", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.830218:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.830407:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.830876:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.830911:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.832289:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.832379:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.832441:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.832465:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.832490:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.832512:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.833068:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.833157:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.833736:INFO:CONSOLE(605)] "%c  ERR color: #f33 [Extension Host] Failed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.833777:INFO:CONSOLE(71)] "%c[Extension Host] %cFailed to load message bundle for file /home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension %c(at Object.loadMessageBundle (/home/mkikets/.vscode-insiders/extensions/ms-edgedevtools.vscode-edge-devtools-1.4.3/out/extension.js:82963:13)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (71)
[7155:0209/191712.859784:INFO:CONSOLE(605)] "%cTRACE color: #888 [DEBOUNCE: Folding] for file:///home/mkikets/arduinos/musicalButton/MusicalButtonWifi/src/main.cpp is 200ms", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.872736:INFO:CONSOLE(605)] "%cTRACE color: #888 lifecycle: phase changed (value: 4)", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[7155:0209/191712.873427:INFO:CONSOLE(605)] "%cTRACE color: #888 RequestService#request https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
/usr/share/code-insiders/code-insiders --verbose --enable-crashpad: symbol lookup error: /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/vscode-encrypt/build/Release/vscode-encrypt-native.node: undefined symbol: SHA256_Init
```

**Comment by marcsandusky** [comment]
[VSCode Insiders failure log](https://github.com/microsoft/vscode/files/8036576/VSCode.Insiders.failure.log)

**Comment by deepak1556** [comment]
For others facing issue with insiders, please follow https://github.com/microsoft/vscode/issues/142574 for updates. Thanks!

**Comment by aeschli** [comment]
@jodyhey Your issue has to do with Remote-WSL extension not yet updated.

Make sure you have v0.64.2 of the Remote-WSL extension then close all VS Code Windows and start VS Code again.
