### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: /Volumes/Coding/playground/t/tauri-search/packages/tauri-search/node_modules/dotenv/lib/main.d.ts linked to nonexistent file /Volumes/Coding/playground/t/tauri-search/node_modules/.pnpm/dotenv@14.3.2/node_modules/dotenv/lib/main.d.ts

### ISSUE THREAD

**Issue by ksnyde** [microsoft/vscode#142689]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression: /Volumes/Coding/playground/t/tauri-search/packages/tauri-search/node_modules/dotenv/lib/main.d.ts linked to nonexistent file /Volumes/Coding/playground/t/tauri-search/node_modules/.pnpm/dotenv@14.3.2/node_modules/dotenv/lib/main.d.ts
    at realPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42243:18)
    at tryResolve (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42220:32)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42194:69
    at Object.forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:197:30)
    at nodeModuleNameResolverWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42194:25)
    at nodeModuleNameResolver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42176:16)
    at Object.resolveModuleName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:41916:30)
    at resolveModuleName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118226:36)
    at resolveNamesWithLocalCache (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118304:38)
    at Object.resolveModuleNames (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118381:20)
    at ConfiguredProject.Project.resolveModuleNames (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164474:45)
    at actualResolveModuleNamesWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113602:153)
    at resolveModuleNamesWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113871:26)
    at resolveModuleNamesReusingOldState (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114047:19)
    at processImportedModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115457:35)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115240:17)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115096:26)
    at processImportedModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115492:25)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115240:17)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115096:26)
    at processImportedModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115492:25)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115240:17)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115096:26)
    at processImportedModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115492:25)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115240:17)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115096:26)
    at processImportedModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115492:25)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115240:17)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115096:26)
    at processImportedModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115492:25)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115240:17)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115096:26)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115048:85
    at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115014:34)
    at processSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115048:13)
    at processRootFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114849:13)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113711:67
    at Object.forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:197:30)
    at Object.createProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113711:16)
    at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159889:26)
    at Proxy.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160021:13)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165035:53)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164964:42)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165957:63)
    at updateProjectIfDirty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:166446:45)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:168769:29)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169104:97
    at Object.flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169104:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170262:46)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172195:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172186:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172195:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172221:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174826:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.65.0-insider (97c1e76d668d23d568044feb31083407f4c4b1ed, 2022-02-07T08:54:27.868Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2170B CPU @ 2.50GHz (28 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|128.00GB (41.29GB free)|
|Process Argv|--crash-reporter-id 3f3eef0e-7e0c-4dc0-9fee-a3a1048f4692|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
project-manager|ale|12.5.0
vscode-sqlite|ale|0.14.0
aws-toolkit-vscode|ama|1.35.0
vscode-color|ans|0.4.5
browse-lite|ant|0.2.16
iconify|ant|0.2.2
icons-carbon|ant|0.2.4
vite|ant|0.2.5
vscode-blink-mind|awe|0.0.10
markdown-emoji|bie|0.2.1
markdown-mermaid|bie|1.13.2
mermaid-markdown-syntax-highlighting|bpr|1.2.2
vscode-toggle-quotes|Bri|0.3.6
better-toml|bun|0.3.2
postcss|css|1.0.9
vscode-eslint|dba|2.2.2
serverlessconsole|dev|0.7.6
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
vscode-great-icons|emm|2.1.82
prettier-vscode|esb|9.2.0
vscode-firefox-debug|fir|2.9.6
vscode-monorepo-workspace|fol|1.3.1
vscode-pull-request-github|Git|0.36.0
vscode-graphql|Gra|0.3.41
mermaid-export|Gru|0.0.8
todo-tree|Gru|0.0.215
textusm|har|0.10.2
vscode-dynamodb|har|0.0.1
vscode-test-explorer|hbe|2.21.1
docker-linter|hen|0.5.0
npm-dependency-links|her|1.2.0
search-node-modules|jas|1.3.0
svg|joc|1.4.17
volar|joh|0.31.2
vscode-typescript-vue-plugin|joh|0.31.2
firebase-explorer|jsa|0.3.3
i18n-ally|lok|2.8.1
rust-analyzer|mat|0.2.932
git-graph|mhu|1.30.0
sort-typescript-imports|mic|1.4.1
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-docker|ms-|1.19.0
vscode-kubernetes-tools|ms-|1.3.6
remote-containers|ms-|0.219.0
live-server|ms-|0.2.12
test-adapter-converter|ms-|0.1.5
vscode-js-profile-flame|ms-|0.0.24
debugger-for-chrome|msj|4.13.0
color-highlight|nau|2.5.0
cargo|pan|0.2.3
vscode-yaml|red|1.4.0
postcss|ric|2.0.0
snippet-creator|rya|0.1.3
vscode-open|san|0.1.0
crates|ser|0.5.10
mdx|sil|0.1.0
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.14.2
tauri-vscode|tau|0.1.3
html-preview-vscode|tht|0.2.5
vue-docs|tit|1.0.2
vsfire|tob|1.4.1
vscode-sort-package-json|uni|1.2.2
gitflow|vec|1.2.1
windicss-intellisense|voo|0.21.6
vscode-icons|vsc|11.8.0
snippet|vsc|0.8.1
quokka-vscode|Wal|1.0.443
wallaby-vscode|Wal|1.0.325
markdown-all-in-one|yzh|3.4.0
cuesheet|zgm|0.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30421358
vs360cf:30404996
vsclayoutctrt:30405800
vscop841cf:30434590
pythonvspyt640:30426300
vscscmwlcmc:30428972
azactmsal:30432848
vscgsvidc:30433759

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Insiders includes a new TypeScript version: 4.6
