### ISSUE TITLE
`TreeError [myTreeDataProvider] Data tree node not found` when selecting and deleting last child element in tree item

### ISSUE THREAD

**Issue by katsoohoo** [microsoft/vscode#142700]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.1
- OS Version: macOS 11.6

Steps to Reproduce:

Sample extension with steps 1 - 3 available at https://github.com/katsoohoo/treeview-extension
1. Build an extension with a tree view
1. In the tree view, create a collapsible root and one child to the root element
1. Create a VS Code command to delete the child element
1. When running the extension, select the child element and run the delete command
1. The root element becomes non-collapsible and the following error occurs in the console:
    ```
    rejected promise not handled within 1 second: Error: TreeError [myTreeDataProvider] Data tree node not found: [object Object]
    /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112
    stack trace: Error: TreeError [myTreeDataProvider] Data tree node not found: [object Object]
        at se.getDataNode ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:19917]())
        at se.getNode ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:17566]())
        at fe ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:655:34927]())
        at [vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4675]()
        at [vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4808]()
        at Array.forEach (<anonymous>)
        at r.bufferEvents ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4797]())
        at v.setCollapsible ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:10582]())
        at v.spliceSimple ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:9606]())
        at v.splice ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:7530]())
        at A._setChildren ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:17603]())
        at A.setChildren ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:17005]())
        at I.setChildren ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:6680]())
        at se.render ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:23336]())
        at se.refreshAndRenderNode ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:20057]())
        at processTicksAndRejections (internal[/process/task_queues.js:93:5]())
        at async se._updateChildren ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:17119]())
        at async se.updateChildren ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:16785]())
        at async Promise.all (index 0)
        at async pe.doRefresh ([vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2587:15187]())
    ```
![bug](https://user-images.githubusercontent.com/5027555/153343920-25c8dc87-977d-46d6-baba-f4d133a28e44.gif)

Notes:
- The error only occurs if there is only one child in an element and the child element is the current selection
- When firing a change without specifying an element (`this.onDidChangeTreeDataEmitter.fire()`), the error does not occur

**Comment by katsoohoo** [comment]
We have a temporarily workaround  where we focus on the parent node before removing the last child node. Specifically, we call [`TreeView.reveal()`](https://code.visualstudio.com/api/references/vscode-api) with `focus: true`. The `select` option doesn't matter in this case.

**Comment by alexr00** [comment]
Thank you for the clear sample! I tried it out, and I can reproduce the issue in 1.64.*, but not in insiders. @katsoohoo would you be able to try out[ VS Code Insiders](https://code.visualstudio.com/insiders/) and see if you can reproduce the issue there?

**Comment by katsoohoo** [comment]
Hi @alexr00, thanks for confirming. I cannot reproduce the error in `1.65.0-insider`. Do you have an estimate on when the fix will be in the stable release?

**Comment by alexr00** [comment]
We're about to start our endgame, so maybe next week: https://github.com/microsoft/vscode/issues/143606
