### ISSUE TITLE
VSCode did not sync my settings/extensions on my job laptop, now it unsynced everything on my personal laptop

### ISSUE THREAD

**Issue by joaocasarin** [microsoft/vscode#142797]
So, everything was working, I had settings/extensions sync working, all of them were installed in my vscode, the settings.json was ok. I tried signing in my account on vscode on my job laptop, and expected to have everything synced. However, it just didn't sync the stuffs. Now, on my personal laptop, everything just disappeared... my extensions, themes, icon themes, settings etc... I haven't even used the software today to make some mistake, it was all vscode fault.

I don't remember the stuffs I have configured and extensions I have installed to re-do everything.

**Comment by sandy081** [comment]
We are very sorry about that.

>  I tried signing in my account on vscode on my job laptop, and expected to have everything synced. However, it just didn't sync the stuffs

This seems to be fishy, can you please shed more light on this? Is it possible to get settings sync log when that happened? To find older logs, go to settings sync data view using command `Settings Sync: Show Synced Data` and enable TroubleShooting view and you can find them there.

As @gjsjohnmurray mentioned, you can restore your data by following the mentioned link.

**Comment by joaocasarin** [comment]
So, I'm trying to resync my stuffs on my second notebook, but a lot of settings and extensions are not being synced. I get These XML request errors:

```sh
[2022-02-11 11:17:50.010] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-02-11 11:17:50.010] [settingssync] [info] Auto Sync is disabled.
[2022-02-11 11:18:44.519] [settingssync] [info] Did reset the local sync state.
[2022-02-11 11:18:51.974] [settingssync] [info] Settings: Updated local settings
[2022-02-11 11:18:51.988] [settingssync] [info] Settings: Updated last synchronized settings
[2022-02-11 11:18:52.001] [settingssync] [info] Keybindings: Updated local keybindings
[2022-02-11 11:18:52.008] [settingssync] [info] Keybindings: Updated last synchronized keybindings
[2022-02-11 11:18:52.012] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-02-11 11:18:52.022] [settingssync] [info] Snippets: Updated last synchronized snippets
[2022-02-11 11:18:52.035] [settingssync] [info] Tasks: Updated local tasks
[2022-02-11 11:18:52.047] [settingssync] [info] Tasks: Updated last synchronized tasks
[2022-02-11 11:18:52.062] [settingssync] [info] GlobalState: Updated global state ["Comments.hidden","ces/skipSurvey","commandPalette.mru.cache","commandPalette.mru.counter","cpp.1.sessionCount","expandSuggestionDocs","extensionTips/promptedExecutableTips","extensionsAssistant/fileExtensionsSuggestionIgnore","extensionsAssistant/importantRecommendationsIgnore","extensionsAssistant/languagePackSuggestionIgnore","fileBasedRecommendations/promptedRecommendations","github-joaocasarin","java.2.sessionCount","javascript.1.editedCount","javascript.1.editedDate","javascript.1.isCandidate","javascript.1.lastSessionDate","javascript.1.sessionCount","javascript.1.skipVersion","memento/workbench.editor.keybindings","nps/isCandidate","nps/skipVersion","remote.explorerType","terminal.integrated.showTerminalConfigPrompt","typescript.1.editedCount","typescript.1.editedDate","typescript.1.isCandidate","typescript.1.lastSessionDate","typescript.1.sessionCount","typescript.1.skipVersion","workbench.view.extension.dockerView.state.hidden","workbench.view.extension.gitlens.state.hidden","workbench.view.extension.liveshare.state.hidden","workbench.view.extension.test.state.hidden","workbench.view.extension.thunder-client-sidebar-view.state.hidden","workbench.view.extension.thunder-client.state.hidden","workbench.view.extension.wallaby.state.hidden","workbench.view.extensions.state.hidden","workbench.view.remote.state.hidden","workbench.view.sync.state.hidden","workbench.welcomePage.hiddenCategories","workbench.welcomePage.walkthroughMetadata","colorThemeData","memento/gettingStartedService","nps/lastSessionDate","nps/sessionCount","workbench.activity.pinnedViewlets2","workbench.explorer.views.state.hidden","workbench.panel.pinnedPanels","workbench.scm.views.state.hidden","workbench.statusbar.hidden"]
[2022-02-11 11:18:52.063] [settingssync] [info] GlobalState: Updated local ui state
[2022-02-11 11:18:52.069] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-02-11 11:18:53.236] [settingssync] [info] Extensions: Disabled extension usernamehw.errorlens 3.4.1
[2022-02-11 11:18:54.410] [settingssync] [info] Extensions: Installed extension. ms-vscode-remote.remote-wsl 0.64.2
[2022-02-11 11:18:55.244] [settingssync] [info] Extensions: Installed extension. ecmel.vscode-html-css 1.11.0
[2022-02-11 11:18:55.266] [settingssync] [info] Extensions: Installed extension. ms-azuretools.vscode-docker 1.19.0
[2022-02-11 11:18:55.891] [settingssync] [info] Extensions: Installed extension. esbenp.prettier-vscode 9.2.0
[2022-02-11 11:18:56.433] [settingssync] [info] Extensions: Installed extension. pkief.material-icon-theme 4.13.0
[2022-02-11 11:18:58.402] [settingssync] [info] Extensions: Installed extension. ritwickdey.liveserver 5.7.4
[2022-02-11 11:19:01.196] [settingssync] [info] Extensions: Installed extension. ms-python.python 2022.0.1814523869
[2022-02-11 11:19:04.913] [settingssync] [info] Extensions: Installed extension. ms-python.vscode-pylance 2022.2.1
[2022-02-11 11:19:35.730] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:35.730] [settingssync] [info] Extensions: Skipped synchronizing extension Better Comments
[2022-02-11 11:19:35.731] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:35.731] [settingssync] [info] Extensions: Skipped synchronizing extension ES7+ React/Redux/React-Native snippets
[2022-02-11 11:19:35.731] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:35.731] [settingssync] [info] Extensions: Skipped synchronizing extension Markdown Emoji
[2022-02-11 11:19:35.732] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:35.732] [settingssync] [info] Extensions: Skipped synchronizing extension Dracula Official
[2022-02-11 11:19:36.040] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.040] [settingssync] [info] Extensions: Skipped synchronizing extension Visual Studio IntelliCode
[2022-02-11 11:19:36.056] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.056] [settingssync] [info] Extensions: Skipped synchronizing extension ESLint
[2022-02-11 11:19:36.057] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.057] [settingssync] [info] Extensions: Skipped synchronizing extension GitLens — Git supercharged
[2022-02-11 11:19:36.133] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.134] [settingssync] [info] Extensions: Skipped synchronizing extension GitHub Copilot
[2022-02-11 11:19:36.197] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.197] [settingssync] [info] Extensions: Skipped synchronizing extension Template String Converter
[2022-02-11 11:19:36.259] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.259] [settingssync] [info] Extensions: Skipped synchronizing extension CodeSnap
[2022-02-11 11:19:36.415] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.415] [settingssync] [info] Extensions: Skipped synchronizing extension Split HTML Attributes (Vue, React, Angular)
[2022-02-11 11:19:36.479] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.479] [settingssync] [info] Extensions: Skipped synchronizing extension Thunder Client
[2022-02-11 11:19:36.556] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.557] [settingssync] [info] Extensions: Skipped synchronizing extension EditorConfig for VS Code
[2022-02-11 11:19:36.601] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.601] [settingssync] [info] Extensions: Skipped synchronizing extension Beautify
[2022-02-11 11:19:36.602] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.602] [settingssync] [info] Extensions: Skipped synchronizing extension JavaScript (ES6) code snippets
[2022-02-11 11:19:36.602] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.602] [settingssync] [info] Extensions: Skipped synchronizing extension Error Lens
[2022-02-11 11:19:36.603] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.603] [settingssync] [info] Extensions: Skipped synchronizing extension Git History
[2022-02-11 11:19:36.617] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.617] [settingssync] [info] Extensions: Skipped synchronizing extension Python Docstring Generator
[2022-02-11 11:19:36.633] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.633] [settingssync] [info] Extensions: Skipped synchronizing extension Python Indent
[2022-02-11 11:19:36.634] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.634] [settingssync] [info] Extensions: Skipped synchronizing extension Live Share
[2022-02-11 11:19:36.697] [settingssync] [error] Error: XHR failed
    at XMLHttpRequest.E.onerror (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:26628)
[2022-02-11 11:19:36.697] [settingssync] [info] Extensions: Skipped synchronizing extension indent-rainbow
[2022-02-11 11:19:36.711] [settingssync] [info] Extensions: Updated last synchronized extensions. Skipped: ["aaron-bond.better-comments","dsznajder.es7-react-js-snippets","bierner.markdown-emoji","dracula-theme.theme-dracula","visualstudioexptteam.vscodeintellicode","dbaeumer.vscode-eslint","eamodio.gitlens","github.copilot","meganrogge.template-string-converter","adpyke.codesnap","dannyconnell.split-html-attributes","rangav.vscode-thunder-client","editorconfig.editorconfig","hookyqr.beautify","xabikos.javascriptsnippets","usernamehw.errorlens","donjayamanne.githistory","njpwerner.autodocstring","kevinrose.vsc-python-indent","ms-vsliveshare.vsliveshare","oderwat.indent-rainbow"].
[2022-02-11 11:19:36.718] [settingssync] [info] Auto Sync: Started
[2022-02-11 11:19:36.718] [settingssync] [info] Auto Sync: Triggered by Interval
[2022-02-11 11:19:37.497] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-02-11 11:19:37.504] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-02-11 11:19:37.509] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-02-11 11:19:37.512] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-02-11 11:19:38.356] [settingssync] [info] GlobalState: Updated remote ui state
[2022-02-11 11:19:38.362] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-02-11 11:19:38.426] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-02-11 11:19:38.428] [settingssync] [info] Sync done. Took 946ms
[2022-02-11 11:19:39.210] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-02-11 11:19:39.538] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-02-11 11:19:39.542] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-02-11 11:19:39.546] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-02-11 11:19:39.548] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-02-11 11:19:39.552] [settingssync] [info] GlobalState: No changes found during synchronizing ui state.
[2022-02-11 11:19:39.616] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-02-11 11:19:39.618] [settingssync] [info] Sync done. Took 87ms
[2022-02-11 11:19:57.114] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-02-11 11:19:57.440] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-02-11 11:19:57.446] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-02-11 11:19:57.449] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-02-11 11:19:57.452] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-02-11 11:19:58.178] [settingssync] [info] GlobalState: Updated remote ui state
[2022-02-11 11:19:58.192] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-02-11 11:19:58.241] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-02-11 11:19:58.243] [settingssync] [info] Sync done. Took 818ms
```

I tried to restore to a working extension/setting backup, but the vscode doesn't load that data.

**Comment by sandy081** [comment]
May I know this happened (removing extensions locally) when you are turning on sync or the sync was on already on this machine? 

Can you also please check which machine of your has removed the extensions. You can find it by opening the **Sync Activity (Remote)** view using the command `Settings Sync: Show Synced Data` . Check the first `extensions.json` entry from top in the tree where the extensions are removed when compared to the previous entry. This will let you know which machine has removed the extensions.

**Comment by joaocasarin** [comment]
Hi @sandy081 
It happened when the sync was already on.

I'm afraid I can't get those logs, I can't find it.

For the last error, I uninstalled the VSCode a few days ago and have just tried it again today. But now I'm getting a different error:
```sh
[2022-02-15 14:25:54.695] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-02-15 14:25:54.696] [settingssync] [info] Auto Sync is disabled.
[2022-02-15 14:26:18.403] [settingssync] [info] Did reset the local sync state.
[2022-02-15 14:28:42.271] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/snippets/latest
[2022-02-15 14:28:42.271] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/snippets/latest'.
    at m.request (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:195985)
    at async m.read (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:192434)
    at async h.getRemoteUserData (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:58928)
    at async h._sync (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:49476)
    at async r.getPreviews (vscode-file://vscode-app/c:/Users/jcasarin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:173999)
[2022-02-15 14:28:42.297] [settingssync] [info] Settings: Stopped synchronizing settings.
[2022-02-15 14:28:42.299] [settingssync] [info] Keybindings: Stopped synchronizing keybindings.
[2022-02-15 14:28:42.308] [settingssync] [info] Did reset the local sync state.
```

I'm still with the VSCode opened, so if you need anything int order to fix this I can provide that.

**Comment by sandy081** [comment]
> [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/snippets/latest'.

When you are seeing this error, can you please check the shared process console to get more info about this error.

`F1 > Developer: Toggle Shared Process`
