### ISSUE TITLE
Test Failure: Statusbar verifies that 'quick input' opens when clicking on status bar elements

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#142745]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155280&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab
```
  1) VSCode Smoke Tests (Electron)
       Statusbar
         verifies that 'quick input' opens when clicking on status bar elements:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/src/code.ts:109:10)
      at Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/src/code.ts:268:3)
      at QuickInput.waitForQuickInputOpened (/Users/runner/work/1/s/test/automation/src/quickinput.ts:20:3)
      at Context.<anonymous> (src/areas/statusbar/statusbar.test.ts:53:4)
```

**Comment by JacksonKearl** [comment]
Seems to be a new flake

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155415&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

```
  1) VSCode Smoke Tests (Electron)
       Statusbar
         verifies that 'quick input' opens when clicking on status bar elements:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/src/code.ts:109:10)
      at Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/src/code.ts:268:3)
      at QuickInput.waitForQuickInputOpened (/Users/runner/work/1/s/test/automation/src/quickinput.ts:20:3)
      at Context.<anonymous> (src/areas/statusbar/statusbar.test.ts:53:4)
```

**Comment by bpasero** [comment]
I cannot explain the recent failures, I pushed https://github.com/microsoft/vscode/commit/5911ead4c63a4a011fe7977d250a57551b739cdd to open a markdown file instead of a JS file because I noticed that opening a JS file activates the TS/JS extension which shows a spinning progress indicator in the status bar which goes away at a random time. Maybe this causes the click to fail sometimes 🤞

**Comment by bpasero** [comment]
@jrieken @daviddossett is this spinning indicator at the language status indicator a new thing?

![image](https://user-images.githubusercontent.com/900690/153700305-ba3fbdd9-6769-46d5-80b4-519a00c2cf0b.png)

**Comment by bpasero** [comment]
Hm, no seems to be relatively old: https://github.com/microsoft/vscode/commit/6b2aa3abfda6255ae89335bdc27d907a26ddb957

**Comment by JacksonKearl** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155699&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

```
  1) VSCode Smoke Tests (Electron)
       Statusbar
         verifies that 'quick input' opens when clicking on status bar elements:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/src/code.ts:109:10)
      at Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/src/code.ts:268:3)
      at QuickInput.waitForQuickInputOpened (/Users/runner/work/1/s/test/automation/src/quickinput.ts:20:3)
      at Context.<anonymous> (src/areas/statusbar/statusbar.test.ts:53:4)
```

**Comment by JacksonKearl** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155747&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=79e950e2-ae58-5fea-a241-0229f56d23a3

  1) VSCode Smoke Tests (Electron)
       Statusbar
         verifies that 'quick input' opens when clicking on status bar elements:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at poll (/__w/1/s/test/automation/src/code.ts:109:10)
      at Code.waitForActiveElement (/__w/1/s/test/automation/src/code.ts:268:3)
      at QuickInput.waitForQuickInputOpened (/__w/1/s/test/automation/src/quickinput.ts:20:3)
      at Context.<anonymous> (src/areas/statusbar/statusbar.test.ts:53:4)

**Comment by bpasero** [comment]
@JacksonKearl all those builds are from a time before my change, you can tell by looking at the screenshot that is attached on failure still showing `app.js` being opened.
