### ISSUE TITLE
remote code-server fails to start (exit code 32) when license agreement is shown

### ISSUE THREAD

**Issue by niderhoff** [microsoft/vscode#142833]
Issue Type: <b>Bug</b>

VS Code Insiders Remote SSH connection fails to start because the remote code-server exists with exit code 32.
The log shows the following lines:

```
server.sh is being replaced by 'bin/code-server-insiders'. Please migrate to the new command and adopt the following new default behaviors:
* connection token is mandatory unless --without-connection-token is used
* host defaults to `localhost`
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Do you accept the terms in the License Agreement?
```

When I manually start server.sh and accept the license agreement using stdin, the code-server starts.

VS Code version: Code - Insiders 1.65.0-insider (bb221a61d29deabd99ee9431736d04f2175cb596, 2022-02-11T05:19:13.554Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Connection to 'SSH' could not be established  The VS Code Server failed to start

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (2.89GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bwsl/xxx --crash-reporter-id b0028fb3-2acb-47bc-9608-99d43c9fb879|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  The VS Code Server failed to start
</details>Extensions: none

My full log from the Remote - SSH Extension:

```
[12:30:41.499] Log Level: 1
[12:30:41.512] remote-ssh@0.70.0
[12:30:41.512] win32 x64
[12:30:41.527] SSH Resolver called for "ssh-remote+wsl", attempt 1
[12:30:41.527] "remote.SSH.useLocalServer": true
[12:30:41.527] "remote.SSH.path": C:/Program Files/Git/usr/bin/ssh.exe
[12:30:41.528] "remote.SSH.configFile": undefined
[12:30:41.528] "remote.SSH.useFlock": true
[12:30:41.528] "remote.SSH.lockfilesInTmp": false
[12:30:41.528] "remote.SSH.localServerDownload": auto
[12:30:41.528] "remote.SSH.remoteServerListenOnSocket": false
[12:30:41.528] "remote.SSH.showLoginTerminal": false
[12:30:41.528] "remote.SSH.defaultExtensions": []
[12:30:41.528] "remote.SSH.loglevel": 1
[12:30:41.529] "remote.SSH.serverPickPortsFromRange": {}
[12:30:41.529] "remote.SSH.enableDynamicForwarding": false
[12:30:41.529] "remote.SSH.serverInstallPath": {}
[12:30:41.529] SSH Resolver called for host: wsl
[12:30:41.529] Setting up SSH remote "wsl"
[12:30:41.534] Acquiring local install lock: C:\Users\niderhof\AppData\Local\Temp\vscode-remote-ssh-2db75989-install.lock
[12:30:41.539] Looking for existing server data file at c:\Users\niderhof\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-2db75989-bb221a61d29deabd99ee9431736d04f2175cb596-0.70.0\data.json
[12:30:41.539] Using commit id "bb221a61d29deabd99ee9431736d04f2175cb596" and quality "insider" for server
[12:30:41.543] Install and start server if needed
[12:30:41.546] Checking ssh with "C:/Program Files/Git/usr/bin/ssh.exe -V"
[12:30:41.805] > OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021

[12:30:41.814] Using SSH config file "C:\Users\niderhof\.ssh\config"
[12:30:41.815] askpass server listening on \\.\pipe\vscode-ssh-askpass-e462907c36a61cf1a95ad90433f33f4d5e0059f3-sock
[12:30:41.816] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-32513d4500b20d7504044656e8523a117068ade1-sock","sshCommand":"C:/Program Files/Git/usr/bin/ssh.exe","sshArgs":["-v","-T","-D","60078","-F","C:\\Users\\niderhof\\.ssh\\config","wsl","bash"],"dataFilePath":"c:\\Users\\niderhof\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-2db75989-bb221a61d29deabd99ee9431736d04f2175cb596-0.70.0\\data.json"}
[12:30:41.816] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\niderhof\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-0.70.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\niderhof\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\Code - Insiders.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\niderhof\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-0.70.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-e462907c36a61cf1a95ad90433f33f4d5e0059f3-sock"}
[12:30:41.829] Spawned 40340
[12:30:41.992] > local-server-1> Spawned ssh, pid=15552
[12:30:42.085] stderr> OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021
[12:30:42.097] stderr> debug1: Reading configuration data C:\\xxxxxxxxxxxxx
[12:30:42.098] stderr> debug1: C:\\xxxxxxxxxxxxx line yy: Applying options for wsl
[12:30:42.120] stderr> debug1: Connecting to xxx.xxx.xxx.xxx [xxx.xxx.xxx.xxx] port yyyy.
[12:30:42.121] stderr> debug1: Connection established.
[12:30:42.123] stderr> debug1: identity file C:\\xxxxxxxxxxxxxxx type 3
[12:30:42.124] stderr> debug1: identity file C:\\xxxxxxxxxxxxxxx type -1
[12:30:42.124] stderr> debug1: Local version string SSH-2.0-OpenSSH_8.5
[12:30:42.128] stderr> debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
[12:30:42.128] stderr> debug1: compat_banner: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.4 pat OpenSSH* compat 0x04000000
[12:30:42.128] stderr> debug1: Authenticating to 123.123.123.123:1234 as 'xxx'
[12:30:42.129] stderr> debug1: load_hostkeys: fopen /c/Users/niderhof/.ssh/known_hosts2: No such file or directory
[12:30:42.130] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[12:30:42.130] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[12:30:42.130] stderr> debug1: SSH2_MSG_KEXINIT sent
[12:30:42.130] stderr> debug1: SSH2_MSG_KEXINIT received
[12:30:42.131] stderr> debug1: kex: algorithm: curve25519-sha256
[12:30:42.131] stderr> debug1: kex: host key algorithm: ssh-ed25519
[12:30:42.131] stderr> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[12:30:42.131] stderr> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[12:30:42.132] stderr> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
[12:30:42.137] stderr> debug1: SSH2_MSG_KEX_ECDH_REPLY received
[12:30:42.137] stderr> debug1: Server host key: ssh-ed25519 SHA256:1sStR7EYZakp4XF40adqao8Cc8qgsTEfjGCW2WDCKEI
[12:30:42.138] stderr> debug1: load_hostkeys: fopen /c/Users/niderhof/.ssh/known_hosts2: No such file or directory
[12:30:42.138] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[12:30:42.139] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[12:30:42.139] stderr> debug1: Host '[123.123.123.123]:1234' is known and matches the ED25519 host key.
[12:30:42.139] stderr> debug1: Found key in /c/Users/niderhof/.ssh/known_hosts:70
[12:30:42.143] stderr> debug1: rekey out after 134217728 blocks
[12:30:42.144] stderr> debug1: SSH2_MSG_NEWKEYS sent
[12:30:42.144] stderr> debug1: expecting SSH2_MSG_NEWKEYS
[12:30:42.144] stderr> debug1: SSH2_MSG_NEWKEYS received
[12:30:42.144] stderr> debug1: rekey in after 134217728 blocks
[12:30:42.144] stderr> debug1: Will attempt key: C:\\xxxxxxxxxxxxx ED25519 SHA256:cVFrYYt0D0rOVEwFAE1wLuL2L45ckZzAvxUH067yIxc explicit
[12:30:42.144] stderr> debug1: SSH2_MSG_EXT_INFO received
[12:30:42.144] stderr> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
[12:30:42.144] stderr> debug1: SSH2_MSG_SERVICE_ACCEPT received
[12:30:42.152] stderr> debug1: Authentications that can continue: publickey,password
[12:30:42.152] stderr> debug1: Next authentication method: publickey
[12:30:42.153] stderr> debug1: Offering public key: C:\\xxxxx ED25519 SHA256:cVFrYYt0D0rOVEwFAE1wLuL2L45ckZzAvxUH067yIxc explicit
[12:30:42.153] stderr> debug1: Server accepts key: C:\\xxxxxx ED25519 SHA256:cVFrYYt0D0rOVEwFAE1wLuL2L45ckZzAvxUH067yIxc explicit
[12:30:42.169] stderr> debug1: Authentication succeeded (publickey).
[12:30:42.169] stderr> Authenticated to 123.123.123.123 ([123.123.123.123.]:1234).
[12:30:42.169] stderr> debug1: Local connections to LOCALHOST:60078 forwarded to remote address socks:0
[12:30:42.170] stderr> debug1: Local forwarding listening on ::1 port 60078.
[12:30:42.170] stderr> debug1: channel 0: new [port listener]
[12:30:42.170] stderr> debug1: Local forwarding listening on 127.0.0.1 port 60078.
[12:30:42.170] stderr> debug1: channel 1: new [port listener]
[12:30:42.170] stderr> debug1: channel 2: new [client-session]
[12:30:42.170] stderr> debug1: Requesting no-more-sessions@openssh.com
[12:30:42.170] stderr> debug1: Entering interactive session.
[12:30:42.170] stderr> debug1: pledge: filesystem full
[12:30:42.417] stderr> debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
[12:30:42.417] stderr> debug1: client_input_hostkeys: searching /c/Users/niderhof/.ssh/known_hosts for [123.123.123.123.]:1234/ (none)
[12:30:42.421] stderr> debug1: client_input_hostkeys: searching /c/Users/niderhof/.ssh/known_hosts2 for [123.123.123.123]:1234/ (none)
[12:30:42.421] stderr> debug1: client_input_hostkeys: hostkeys file /c/Users/niderhof/.ssh/known_hosts2 does not exist
[12:30:42.421] stderr> debug1: client_input_hostkeys: host key found matching a different name/address, skipping UserKnownHostsFile update
[12:30:42.421] stderr> debug1: Remote: /home/xxx/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
[12:30:42.457] stderr> debug1: Remote: /home/xxx/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
[12:30:42.457] stderr> debug1: Sending command: bash
[12:30:42.460] > ready: 758939cb4996
[12:30:42.462] > Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
[12:30:42.462] Platform: linux
[12:30:42.469] > 758939cb4996: running
[12:30:42.483] > Acquiring lock on /home/xxx/.vscode-server-insiders/bin/bb221a61d29deabd99ee9431736d04f2175cb596/vscode-remote-lock.xxx.bb221a61d29deabd99ee9431736d04f2175cb596
[12:30:42.486] > Found existing installation at /home/xxx/.vscode-server-insiders/bin/bb221a61d29deabd99ee9431736d04f2175cb596...
> Checking /home/xxx/.vscode-server-insiders/.bb221a61d29deabd99ee9431736d04f2175cb596.log and /home/xxx/.vscode-server-insiders/.bb221a61d29deabd99ee9431736d04f2175cb596.pid for a running server
[12:30:42.486] > Looking for server with pid: 10351
[12:30:42.490] > Starting server with command... /home/xxx/.vscode-server-insiders/bin/bb221a61d29deabd99ee9431736d04f2175cb596/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0    &> "/home/xxx/.vscode-server-insiders/.bb221a61d29deabd99ee9431736d04f2175cb596.log" < /dev/null
> printenv:
[12:30:42.491] >     SHELL=/bin/bash
>     PWD=/home/xxx
>     LOGNAME=xxx
>     MOTD_SHOWN=pam
>     HOME=/home/xxx
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/home/xxx/.vscode-server-insiders
>     SSH_CONNECTION=123.123.123.123 50965 123.123.123.123 1234
>     USER=xxx
>     SHLVL=1
>     SSH_CLIENT=123.123.123.123 50965 1234
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     _=/usr/bin/printenv
[12:30:42.494] > Spawned remote server: 11899
[12:30:42.496] > Waiting for server log...
[12:30:42.528] > Waiting for server log...
[12:30:42.561] > Waiting for server log...
[12:30:42.593] > Waiting for server log...
[12:30:42.625] > Waiting for server log...
[12:30:42.658] > Waiting for server log...
[12:30:42.691] > Waiting for server log...
[12:30:42.724] > Waiting for server log...
[12:30:42.756] > Waiting for server log...
[12:30:42.789] > Waiting for server log...
[12:30:42.822] > Waiting for server log...
[12:30:42.858] > Waiting for server log...
[12:30:42.893] > Waiting for server log...
[12:30:42.926] > Waiting for server log...
[12:30:42.958] > Waiting for server log...
[12:30:42.991] > Waiting for server log...
[12:30:43.024] > Waiting for server log...
[12:30:43.057] > Waiting for server log...
[12:30:43.094] > Waiting for server log...
[12:30:43.130] > Waiting for server log...
[12:30:43.167] > Waiting for server log...
[12:30:43.200] > Waiting for server log...
[12:30:43.234] > Waiting for server log...
[12:30:43.266] > Waiting for server log...
[12:30:43.301] > Waiting for server log...
[12:30:43.333] > Waiting for server log...
[12:30:43.366] > Waiting for server log...
[12:30:43.398] > Waiting for server log...
[12:30:43.431] > Waiting for server log...
[12:30:43.463] > Waiting for server log...
[12:30:43.501] > Waiting for server log...
[12:30:43.538] > Waiting for server log...
[12:30:43.576] > Waiting for server log...
[12:30:43.609] > Waiting for server log...
[12:30:43.642] > Waiting for server log...
[12:30:43.675] > Waiting for server log...
[12:30:43.707] > Waiting for server log...
[12:30:43.741] > Waiting for server log...
[12:30:43.773] > Waiting for server log...
[12:30:43.805] > Waiting for server log...
[12:30:43.838] > Waiting for server log...
[12:30:43.871] > Waiting for server log...
[12:30:43.903] > Waiting for server log...
[12:30:43.936] > Waiting for server log...
[12:30:43.969] > Waiting for server log...
[12:30:44.002] > Waiting for server log...
[12:30:44.034] > Waiting for server log...
[12:30:44.067] > Waiting for server log...
[12:30:44.100] > Waiting for server log...
[12:30:44.133] > Waiting for server log...
[12:30:44.166] > Waiting for server log...
[12:30:44.199] > Waiting for server log...
[12:30:44.232] > Waiting for server log...
[12:30:44.265] > Waiting for server log...
[12:30:44.298] > Waiting for server log...
[12:30:44.330] > Waiting for server log...
[12:30:44.369] > Waiting for server log...
[12:30:44.402] > Waiting for server log...
[12:30:44.434] > Waiting for server log...
[12:30:44.467] > Waiting for server log...
[12:30:44.500] > Waiting for server log...
[12:30:44.532] > Waiting for server log...
[12:30:44.564] > Waiting for server log...
[12:30:44.597] > Waiting for server log...
[12:30:44.629] > Waiting for server log...
[12:30:44.661] > Waiting for server log...
[12:30:44.694] > Waiting for server log...
[12:30:44.727] > Waiting for server log...
[12:30:44.760] > Waiting for server log...
[12:30:44.798] > Waiting for server log...
[12:30:44.837] > Waiting for server log...
[12:30:44.870] > Waiting for server log...
[12:30:44.902] > Waiting for server log...
[12:30:44.935] > Waiting for server log...
[12:30:44.968] > Waiting for server log...
[12:30:45.000] > Waiting for server log...
[12:30:45.033] > Waiting for server log...
[12:30:45.067] > Waiting for server log...
[12:30:45.099] > Waiting for server log...
[12:30:45.132] > Waiting for server log...
[12:30:45.165] > Waiting for server log...
[12:30:45.197] > Waiting for server log...
[12:30:45.230] > Waiting for server log...
[12:30:45.263] > Waiting for server log...
[12:30:45.295] > Waiting for server log...
[12:30:45.328] > Waiting for server log...
[12:30:45.361] > Waiting for server log...
[12:30:45.393] > Waiting for server log...
[12:30:45.426] > Waiting for server log...
[12:30:45.458] > Waiting for server log...
[12:30:45.491] > Waiting for server log...
[12:30:45.524] > Waiting for server log...
[12:30:45.558] > Waiting for server log...
[12:30:45.591] > Waiting for server log...
[12:30:45.624] > Waiting for server log...
[12:30:45.656] > Waiting for server log...
[12:30:45.689] > Waiting for server log...
[12:30:45.722] > Waiting for server log...
[12:30:45.760] > Waiting for server log...
[12:30:45.795] > Waiting for server log...
[12:30:45.828] > Waiting for server log...
[12:30:45.861] > Waiting for server log...
[12:30:45.900] > Waiting for server log...
[12:30:45.932] > Waiting for server log...
[12:30:45.965] > Waiting for server log...
[12:30:45.997] > Waiting for server log...
[12:30:46.030] > Waiting for server log...
[12:30:46.062] > Waiting for server log...
[12:30:46.095] > Waiting for server log...
[12:30:46.128] > Waiting for server log...
[12:30:46.161] > Waiting for server log...
[12:30:46.193] > Waiting for server log...
[12:30:46.225] > Waiting for server log...
[12:30:46.258] > Waiting for server log...
[12:30:46.291] > Waiting for server log...
[12:30:46.324] > Waiting for server log...
[12:30:46.356] > Waiting for server log...
[12:30:46.389] > Waiting for server log...
[12:30:46.422] > Waiting for server log...
[12:30:46.454] > Waiting for server log...
[12:30:46.487] > Waiting for server log...
[12:30:46.520] > Waiting for server log...
[12:30:46.552] > Waiting for server log...
[12:30:46.585] > Waiting for server log...
[12:30:46.617] > Waiting for server log...
[12:30:46.650] > Waiting for server log...
[12:30:46.683] > Waiting for server log...
[12:30:46.716] > Waiting for server log...
[12:30:46.749] > Waiting for server log...
[12:30:46.783] > Waiting for server log...
[12:30:46.815] > Waiting for server log...
[12:30:46.848] > Waiting for server log...
[12:30:46.880] > Waiting for server log...
[12:30:46.913] > Waiting for server log...
[12:30:46.946] > Waiting for server log...
[12:30:46.979] > Waiting for server log...
[12:30:47.012] > Waiting for server log...
[12:30:47.044] > Waiting for server log...
[12:30:47.077] > Waiting for server log...
[12:30:47.110] > Waiting for server log...
[12:30:47.148] > Waiting for server log...
[12:30:47.180] > Waiting for server log...
[12:30:47.213] > Waiting for server log...
[12:30:47.246] > Waiting for server log...
[12:30:47.279] > Waiting for server log...
[12:30:47.312] > Waiting for server log...
[12:30:47.351] > Waiting for server log...
[12:30:47.384] > Waiting for server log...
[12:30:47.416] > Waiting for server log...
[12:30:47.449] > Waiting for server log...
[12:30:47.481] > Waiting for server log...
[12:30:47.514] > Waiting for server log...
[12:30:47.547] > Waiting for server log...
[12:30:47.579] > Waiting for server log...
[12:30:47.611] > Waiting for server log...
[12:30:47.644] > Waiting for server log...
[12:30:47.681] > Waiting for server log...
[12:30:47.717] > Waiting for server log...
[12:30:47.749] > Waiting for server log...
[12:30:47.782] > Waiting for server log...
[12:30:47.815] > Waiting for server log...
[12:30:47.847] > Waiting for server log...
[12:30:47.879] > Waiting for server log...
[12:30:47.912] > Waiting for server log...
[12:30:47.944] > Waiting for server log...
[12:30:47.982] > Waiting for server log...
[12:30:48.021] > Waiting for server log...
[12:30:48.054] > Waiting for server log...
[12:30:48.086] > Waiting for server log...
[12:30:48.118] > Waiting for server log...
[12:30:48.151] > Waiting for server log...
[12:30:48.189] > Waiting for server log...
[12:30:48.222] > Waiting for server log...
[12:30:48.261] > Waiting for server log...
[12:30:48.294] > Waiting for server log...
[12:30:48.327] > Waiting for server log...
[12:30:48.359] > Waiting for server log...
[12:30:48.392] > Waiting for server log...
[12:30:48.430] > Waiting for server log...
[12:30:48.469] > Waiting for server log...
[12:30:48.502] > Waiting for server log...
[12:30:48.535] > Waiting for server log...
[12:30:48.567] > Waiting for server log...
[12:30:48.600] > Waiting for server log...
[12:30:48.633] > Waiting for server log...
[12:30:48.665] > Waiting for server log...
[12:30:48.698] > Waiting for server log...
[12:30:48.731] > Waiting for server log...
[12:30:48.763] > Waiting for server log...
[12:30:48.796] > Waiting for server log...
[12:30:48.829] > Waiting for server log...
[12:30:48.861] > Waiting for server log...
[12:30:48.894] > Waiting for server log...
[12:30:48.926] > Waiting for server log...
[12:30:48.959] > Waiting for server log...
[12:30:48.991] > Waiting for server log...
[12:30:49.023] > Waiting for server log...
[12:30:49.055] > Waiting for server log...
[12:30:49.088] > Waiting for server log...
[12:30:49.121] > Waiting for server log...
[12:30:49.153] > Waiting for server log...
[12:30:49.185] > Waiting for server log...
[12:30:49.224] > Waiting for server log...
[12:30:49.256] > Waiting for server log...
[12:30:49.289] > Waiting for server log...
[12:30:49.322] > Waiting for server log...
[12:30:49.355] > Waiting for server log...
[12:30:49.388] > Waiting for server log...
[12:30:49.427] > Waiting for server log...
[12:30:49.466] > Waiting for server log...
[12:30:49.505] > Waiting for server log...
[12:30:49.538] > Waiting for server log...
[12:30:49.571] > Waiting for server log...
[12:30:49.604] > Waiting for server log...
[12:30:49.636] > Waiting for server log...
[12:30:49.669] > Waiting for server log...
[12:30:49.702] > Waiting for server log...
[12:30:49.736] > Waiting for server log...
[12:30:49.768] > Waiting for server log...
[12:30:49.801] > Waiting for server log...
[12:30:49.834] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[12:30:49.838] > Server did not start successfully. Full server log at /home/xxx/.vscode-server-insiders/.bb221a61d29deabd99ee9431736d04f2175cb596.log >>>
[12:30:49.838] > server.sh is being replaced by 'bin/code-server-insiders'. Please migrate to the new command and adopt the following new default behaviors:
> * connection token is mandatory unless --without-connection-token is used
> * host defaults to `localhost`
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> Do you accept the terms in the License Agreement? 
[12:30:49.839] > <<< End of server log
> 758939cb4996: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7341==
> 758939cb4996: end
[12:30:49.839] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7341==

[12:30:49.840] Terminating local server
[12:30:49.843] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430359)
	at u (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:424682)
	at Object.t.handleInstallOutput (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429101)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:469079)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:486771
	at async Object.t.withShowDetailsEvent (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:467603
	at async E (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:467218)
	at async Object.t.resolve (c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488171)
	at async c:\Users\niderhof\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[12:30:49.846] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"ubuntu","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"0","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"ExitCode","exitCodeLabel":"ServerFailedToStart"},"measures":{"exitCode":32,"resolveAttempts":1,"retries":1,"timing.totalResolveTime":8315,"timing.preSshTime":289,"timing.establishSshTime":653}}
[12:30:49.848] ------




[12:30:49.850] Local server exit: null
```

**Comment by niderhoff** [comment]
sorry, I put in the "code server license agreement" into the Issues Search and it didn't come up, so that's on github, I guess.
