### ISSUE TITLE
Unable to "Install Another Version..." of extension that uses platform-specific VSIX's, in Remote WSL workspace

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#142890]
Version: 1.65.0-insider (user setup)
Commit: bb221a61d29deabd99ee9431736d04f2175cb596
Date: 2022-02-11T05:19:13.554Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Install an extension (such as the C/C++ extension) that uses platform-specific VSIX's in the marketplace.
2. Open a Remote WSL workspace.
3.  Install that extension into the remote.
4. From the extension UI for the instance installed remotely, try to select "Install Another Version..." or "Install Another Prerelease Version..."

This results in an error:

![image](https://user-images.githubusercontent.com/49173979/153684487-05c8c004-aa4f-435f-8fc1-974585b11abc.png)

(There is a similar error in latest non-insider version, 1.64.2)

**Comment by Colengms** [comment]
When this repro's, I see the following in `Log (Remote Server)`:

```
[2022-02-22 13:58:55.922] [remoteagent] [error] Failed to install extension. ms-vscode.cpptools
[2022-02-22 13:58:55.924] [remoteagent] [error] Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).
    at z.checkAndGetCompatibleVersion (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:11880)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async z.installFromGallery (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:2933)
```

`Log (Window)` is similar:

```
[2022-02-22 13:58:55.940] [renderer1] [error] ["Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).","    at z.checkAndGetCompatibleVersion (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:11880)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async z.installFromGallery (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:2933)"]
[2022-02-22 13:58:55.941] [renderer1] [error] Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).: Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).
    at z.checkAndGetCompatibleVersion (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:11880)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async z.installFromGallery (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:2933)
```

`Log (Shared)` was not logged to for this repro.

**Comment by Colengms** [comment]
Log (Shared):
```
[2022-03-03 11:27:13.640] [sharedprocess] [info] Starting worker process with pid 23148 (type: fileWatcher, window: 1).
[2022-03-03 11:27:18.427] [sharedprocess] [info] Worker process with pid 23148 terminated normally (type: fileWatcher, window: 1).
[2022-03-03 11:27:21.132] [sharedprocess] [info] Starting worker process with pid 23868 (type: fileWatcher, window: 1).
[2022-03-03 11:27:55.846] [sharedprocess] [debug] User data changed
[2022-03-03 11:28:03.264] [sharedprocess] [trace] SharedProcess: disposeWorker (window: 1, moduleId: vs/platform/files/node/watcher/watcherMain)
[2022-03-03 11:28:03.265] [sharedprocess] [info] Worker process with pid 23868 terminated normally (type: fileWatcher, window: 1).
[2022-03-03 11:28:03.387] [sharedprocess] [debug] User data changed
[2022-03-03 11:28:04.193] [sharedprocess] [trace] SharedProcess: createWorker (window: 1, moduleId: vs/platform/files/node/watcher/watcherMain)
[2022-03-03 11:28:04.198] [sharedprocess] [trace] SharedProcess (worker, fileWatcher): Forking worker process (env: {})
[2022-03-03 11:28:04.198] [sharedprocess] [trace] Started scanning system extensions
[2022-03-03 11:28:04.199] [sharedprocess] [trace] Started scanning user extensions
[2022-03-03 11:28:04.206] [sharedprocess] [info] Starting worker process with pid 24856 (type: fileWatcher, window: 1).
[2022-03-03 11:28:04.207] [sharedprocess] [trace] SharedProcess: createWorker sending message port back to window (window: 1, moduleId: vs/platform/files/node/watcher/watcherMain)
[2022-03-03 11:28:04.242] [sharedprocess] [trace] Started scanning system extensions
[2022-03-03 11:28:04.242] [sharedprocess] [trace] Started scanning user extensions
[2022-03-03 11:28:04.280] [sharedprocess] [trace] Scanned user extensions: 17
[2022-03-03 11:28:04.291] [sharedprocess] [debug] User data changed
[2022-03-03 11:28:04.341] [sharedprocess] [trace] Scanned user extensions: 17
[2022-03-03 11:28:04.407] [sharedprocess] [trace] Scanned system extensions: 87
[2022-03-03 11:28:04.428] [sharedprocess] [trace] Scanned system extensions: 87
[2022-03-03 11:28:05.684] [sharedprocess] [trace] Started scanning system extensions
[2022-03-03 11:28:05.685] [sharedprocess] [trace] Started scanning user extensions
[2022-03-03 11:28:05.705] [sharedprocess] [trace] Started scanning system extensions
[2022-03-03 11:28:05.706] [sharedprocess] [trace] Started scanning user extensions
[2022-03-03 11:28:05.709] [sharedprocess] [trace] Started scanning system extensions
[2022-03-03 11:28:05.710] [sharedprocess] [trace] Started scanning user extensions
[2022-03-03 11:28:05.741] [sharedprocess] [trace] Scanned user extensions: 17
[2022-03-03 11:28:05.789] [sharedprocess] [trace] Scanned user extensions: 17
[2022-03-03 11:28:05.799] [sharedprocess] [trace] Scanned user extensions: 17
[2022-03-03 11:28:05.891] [sharedprocess] [trace] Scanned system extensions: 87
[2022-03-03 11:28:05.916] [sharedprocess] [trace] Scanned system extensions: 87
[2022-03-03 11:28:05.934] [sharedprocess] [trace] Scanned system extensions: 87
[2022-03-03 11:28:06.619] [sharedprocess] [debug] User data changed
[2022-03-03 11:28:07.140] [sharedprocess] [debug] User data changed
[2022-03-03 11:28:07.231] [sharedprocess] [trace] Started scanning user extensions
[2022-03-03 11:28:07.263] [sharedprocess] [trace] Scanned user extensions: 17
[2022-03-03 11:28:08.061] [sharedprocess] [debug] User data changed
[2022-03-03 11:28:17.387] [sharedprocess] [debug] User data changed
```

Log (Windows):
```
[2022-03-03 11:27:12.653] [renderer1] [info] IExtensionHostStarter.start() took 467 ms.
[2022-03-03 11:27:12.727] [renderer1] [critical] Extension 'ms-vscode-remote.remote-ssh' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, terminalDataWriteEvent, contribViewsRemote, telemetry
product.json (WINS): resolvers, terminalDataWriteEvent, contribViewsRemote
[2022-03-03 11:27:12.727] [renderer1] [critical] Extension 'ms-vscode.azure-sphere-tools-ui CANNOT USE these API proposals 'resolvers'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-03-03 11:27:13.153] [renderer1] [error] [Extension Host] (node:28308) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-03-03 11:27:19.717] [renderer1] [info] IExtensionHostStarter.start() took 47 ms.
[2022-03-03 11:27:20.151] [renderer1] [error] [Extension Host] (node:24040) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-03-03 11:27:20.192] [renderer1] [critical] Extension 'ms-vscode-remote.remote-ssh' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, terminalDataWriteEvent, contribViewsRemote, telemetry
product.json (WINS): resolvers, terminalDataWriteEvent, contribViewsRemote
[2022-03-03 11:27:20.193] [renderer1] [critical] Extension 'ms-vscode.azure-sphere-tools-ui CANNOT USE these API proposals 'resolvers'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-03-03 11:27:20.326] [renderer1] [info] Invoking resolveAuthority(wsl)
[2022-03-03 11:27:21.640] [renderer1] [info] resolveAuthority(wsl) returned '127.0.0.1:54475' after 1311 ms
[2022-03-03 11:27:22.581] [renderer1] [critical] Extension 'ms-vscode.azure-sphere-tools-ui CANNOT USE these API proposals 'resolvers'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-03-03 11:27:23.389] [renderer1] [warning] No search provider registered for scheme: vscode-remote, waiting
[2022-03-03 11:27:25.006] [renderer1] [error] [Extension Host] (node:462) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2022-03-03 11:27:55.793] [renderer1] [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
[2022-03-03 11:27:55.796] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\coleng\AppData\Roaming\Code\User\globalStorage
[2022-03-03 11:27:55.797] [renderer1] [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
[2022-03-03 11:27:55.797] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\coleng\AppData\Roaming\Code\User\globalStorage
[2022-03-03 11:27:55.846] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\coleng\AppData\Roaming\Code\User\globalStorage
[2022-03-03 11:27:55.847] [renderer1] [debug] User data changed
[2022-03-03 11:27:57.948] [renderer1] [trace] CommandService#executeCommand workbench.action.closeEditorsInGroup
[2022-03-03 11:27:57.972] [renderer1] [trace] [text file model] dispose() vscode-remote://wsl+ubuntu-20.04/home/colen/repos/VS/src/vc/designtime/vscode/Common/exec_win.cpp
[2022-03-03 11:27:57.974] [renderer1] [trace] [backup tracker] discarding backup vscode-remote://wsl+ubuntu-20.04/home/colen/repos/VS/src/vc/designtime/vscode/Common/exec_win.cpp 
[2022-03-03 11:27:57.975] [renderer1] [trace] [text file model] dispose() git:/home/colen/repos/VS/src/vc/designtime/vscode/Common/exec_win.cpp.git?{"path":"/home/colen/repos/VS/src/vc/designtime/vscode/Common/exec_win.cpp","ref":""}
[2022-03-03 11:27:57.975] [renderer1] [trace] [backup tracker] discarding backup git:/home/colen/repos/VS/src/vc/designtime/vscode/Common/exec_win.cpp.git?{"path":"/home/colen/repos/VS/src/vc/designtime/vscode/Common/exec_win.cpp","ref":""} 
[2022-03-03 11:28:02.444] [renderer1] [trace] KeybindingService#dispatch Ctrl+Shift+P workbench.action.showCommands
[2022-03-03 11:28:02.444] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2022-03-03 11:28:02.703] [renderer1] [trace] KeybindingService#dispatch R undefined
[2022-03-03 11:28:02.761] [renderer1] [trace] KeybindingService#dispatch E undefined
[2022-03-03 11:28:02.819] [renderer1] [trace] KeybindingService#dispatch L undefined
[2022-03-03 11:28:02.942] [renderer1] [trace] KeybindingService#dispatch O undefined
[2022-03-03 11:28:03.051] [renderer1] [trace] KeybindingService#dispatch A undefined
[2022-03-03 11:28:03.110] [renderer1] [trace] KeybindingService#dispatch D undefined
[2022-03-03 11:28:03.202] [renderer1] [trace] CommandService#executeCommand workbench.action.reloadWindow
[2022-03-03 11:28:03.205] [renderer1] [trace] [lifecycle] onBeforeUnload (reason: 3)
[2022-03-03 11:28:03.209] [renderer1] [trace] [lifecycle] onBeforeUnload continues without veto
[2022-03-03 11:28:03.209] [renderer1] [trace] [lifecycle] onWillUnload (reason: 3)
[2022-03-03 11:28:03.220] [renderer1] [trace] terminalInstance#dispose (instanceId: 1)
[2022-03-03 11:28:03.228] [renderer1] [debug] Terminal process exit (instanceId: 1) with code undefined
[2022-03-03 11:28:03.228] [renderer1] [debug] Terminal process exit (instanceId: 1) state 3
[2022-03-03 11:28:03.228] [renderer1] [trace] terminalInstance#dispose (instanceId: 1)
[2022-03-03 11:28:04.206] [renderer1] [info] IExtensionHostStarter.start() took 31 ms.
[2022-03-03 11:28:04.617] [renderer1] [error] [Extension Host] (node:10232) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-03-03 11:28:04.662] [renderer1] [critical] Extension 'ms-vscode-remote.remote-ssh' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, terminalDataWriteEvent, contribViewsRemote, telemetry
product.json (WINS): resolvers, terminalDataWriteEvent, contribViewsRemote
[2022-03-03 11:28:04.662] [renderer1] [critical] Extension 'ms-vscode.azure-sphere-tools-ui CANNOT USE these API proposals 'resolvers'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-03-03 11:28:04.805] [renderer1] [info] Invoking resolveAuthority(wsl)
[2022-03-03 11:28:05.118] [renderer1] [info] resolveAuthority(wsl) returned '127.0.0.1:54475' after 313 ms
[2022-03-03 11:28:05.898] [renderer1] [critical] Extension 'ms-vscode.azure-sphere-tools-ui CANNOT USE these API proposals 'resolvers'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-03-03 11:28:08.440] [renderer1] [error] [Extension Host] (node:1011) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2022-03-03 11:28:17.015] [renderer1] [error] ["Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).","    at z.checkAndGetCompatibleVersion (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:11880)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async z.installFromGallery (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:2933)"]
[2022-03-03 11:28:17.016] [renderer1] [error] Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).: Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).
    at z.checkAndGetCompatibleVersion (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:11880)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async z.installFromGallery (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:2933)
```

Log (Remote Server):
```
[2022-03-03 11:27:21.516] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2022-03-03 11:27:21.516] [remoteagent] [info] Extension host agent started.
[2022-03-03 11:27:21.796] [remoteagent] [info] [127.0.0.1][01d8f0c7][ManagementConnection] New connection established.
[2022-03-03 11:27:22.212] [remoteagent] [info] [127.0.0.1][31e2de6f][ExtensionHostConnection] New connection established.
[2022-03-03 11:27:22.618] [remoteagent] [info] [127.0.0.1][31e2de6f][ExtensionHostConnection] <462> Launched Extension Host Process.
[2022-03-03 11:28:03.250] [remoteagent] [info] [127.0.0.1][01d8f0c7][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-03-03 11:28:03.356] [remoteagent] [info] [127.0.0.1][31e2de6f][ExtensionHostConnection] <462> Extension Host Process exited with code: 0, signal: null.
[2022-03-03 11:28:05.240] [remoteagent] [info] [127.0.0.1][a038c785][ManagementConnection] New connection established.
[2022-03-03 11:28:05.251] [remoteagent] [trace] Started scanning system extensions
[2022-03-03 11:28:05.251] [remoteagent] [trace] Started scanning user extensions
[2022-03-03 11:28:05.546] [remoteagent] [info] [127.0.0.1][c5042f8b][ExtensionHostConnection] New connection established.
[2022-03-03 11:28:05.552] [remoteagent] [info] [127.0.0.1][c5042f8b][ExtensionHostConnection] <1011> Launched Extension Host Process.
[2022-03-03 11:28:17.004] [remoteagent] [error] Failed to install extension. ms-vscode.cpptools
[2022-03-03 11:28:17.006] [remoteagent] [error] Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).
    at z.checkAndGetCompatibleVersion (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:11880)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async z.installFromGallery (/home/colen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js:108:2933)
```

Log (Remote Extension Host):
```
[2022-03-03 11:28:06.598] [exthost] [info] Extension host with pid 1011 started
[2022-03-03 11:28:06.613] [exthost] [info] Lock '/home/colen/.vscode-server/data/User/workspaceStorage/39b6cb3f5b08c65f88d370739fcd133a/vscode.lock': Lock acquired.
[2022-03-03 11:28:06.782] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-03-03 11:28:06.789] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.github
[2022-03-03 11:28:06.798] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cmake-tools, startup: true, activationEvent: 'workspaceContains:CMakeLists.txt'
[2022-03-03 11:28:07.166] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-03-03 11:28:07.229] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-03-03 11:28:07.802] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-03-03 11:28:07.817] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-03-03 11:28:07.821] [exthost] [info] Eager extensions activated
[2022-03-03 11:28:07.981] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: false, activationEvent: 'api', root cause: ms-vscode.cmake-tools
```

Please re-open.

Please don't block waiting for me to provide information.  This bug is extremely easy to reproduce.

**Comment by Colengms** [comment]
@sandy081 Please re-open.

**Comment by sandy081** [comment]
To verify:

- Open a remote window (make sure local and remote are on different Operating Systems)
- Install C++ extension 
- Install another version of C++ extension (right click on the extension and you will see this action)
- Make sure another version is installed.
