### ISSUE TITLE
ESLint crashes with conflicting configuration detrection in monorepo

### ISSUE THREAD

**Issue by samuelhulla** [microsoft/vscode#143189]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.64.2 (Universal) [LTS] ✅ 
- OS Version: OS: Darwin arm64 21.3.0

## Issue description 📔 

Hey, I've got a monorepo set up with multiple eslint configurations, however since the latest update I am unable to get my local vscode build of ESLint to work 

- *Anecdotally, the same configuration does work on WebStorm my colleagues are using*, which makes me presume this is an issue with vscode eslint detecting incorrect configuration in the monorepo.
- Running the react application via `yarn start` does run on node correctly, including ESLint warning and Errors. They just fail to compile inside VSCode.

The repo directory is set up in the following way:

```
.eslintrc
package.json
src/
   -- files
web/
   .eslintrc
   .packagejson
   -- files
```

However since the latest merge I can't get my ESLint to run locally in VSCode. Producing the following error:

> Error - 11:59:38 AM] Error: Plugin "@typescript-eslint" was conflicted between ".eslintrc#overrides[0]" and "../.eslintrc#overrides[0]".
    at mergePlugins (/Users/samuel/Coding/staffers/web/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1673:19)
    at createConfig (/Users/samuel/Coding/staffers/web/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1776:9)
    at ConfigArray.extractConfig (/Users/samuel/Coding/staffers/web/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1952:33)
    at CLIEngine.isPathIgnored (/Users/samuel/Coding/staffers/web/node_modules/eslint/lib/cli-engine/cli-engine.js:991:18)
    at CLIEngine.executeOnText (/Users/samuel/Coding/staffers/web/node_modules/eslint/lib/cli-engine/cli-engine.js:900:38)
    at ESLint.lintText (/Users/samuel/Coding/staffers/web/node_modules/eslint/lib/eslint/eslint.js:607:23)
    at /Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:178563
    at Ce (/Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:184511)
    at /Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:178521
    at /Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:179798

## What I tried 🔎 

 - Setting the parameter `"root": true` in the base `.eslintrc` in the project
 - Changing the working directory settings to
 
```bash
# .vscode/settings.json
{
  "eslint.workingDirectories": [
    "web",
    "src",
  ]
}
```

- Adding detection mode to auto in global vscode settings

```bash
# Code/User/settings.json
{
   ...
   "eslint.workingDirectories": [{ "mode": "auto" }]
}
```

However none of these helped and I still keep getting the error. Any idea how should i continue?

**Comment by IllusionMH** [comment]
/causedByExtesnion

This functionality provided by ESLint extension and should be reported in that repo (is there are no reports for this problem already). https://github.com/microsoft/vscode-eslint/issues
