### ISSUE TITLE
vscode.dev unexpected error, have to reload page

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#143166]
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:24.333Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43
```

This happened to me a couple of times today where I was editing a (private) repository through vscode.dev/github, committed a change, tried to close the >browser< tab and was prompted by the browser that something was dirty and did I really want to leave the site.

I said no, then closed the two open editors, one the Markdown file I was editing and the other being the Markdown Preview (opened side by side).

When closing the Markdown file, I got this error:

![image](https://user-images.githubusercontent.com/1487073/154184822-d51c3e53-b060-45c5-9bd3-291bff5c1182.png)

Looking in the dev tools console, quite some errors writing to log files:

![image](https://user-images.githubusercontent.com/1487073/154184910-3a671ca3-172b-4a60-bea9-701e2fd85d47.png)

Raw output copied from Console...

```
api.github.com/repos/chrisdias/asApp/git/extract-ref/HEAD:1 
       Failed to load resource: the server responded with a status of 404 ()
main.js:1 
        
       HttpError: Not Found
    at /static/main.js:1:14952
(anonymous) @ main.js:1
workbench.web.api.js:578  WARN Ignoring the error while validating workspace folder vscode-vfs://github/chrisdias/asApp - No file system provider found for resource 'vscode-vfs://github/chrisdias/asApp'
workbench.web.api.js:578 CRITI Extension 'ms-vscode.azure-repos' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): extensionRuntime, fileSearchProvider, resolvers, textSearchProvider
product.json (WINS): fileSearchProvider, textSearchProvider
ms-vsliveshare.vscode-unpkg.net/MS-vsliveshare/vsliveshare/1.0.5330/extension/remoteSettings.json:1 
        
       Failed to load resource: the server responded with a status of 404 ()
workbench.web.api.js:1927 
        
       Activating extension 'GitHub.remotehub' failed: Extension 'ms-vscode.azure-repos' CANNOT use API proposal: extensionRuntime.
Its package.json#enabledApiProposals-property declares: fileSearchProvider, textSearchProvider but NOT extensionRuntime.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode.azure-repos.
$onExtensionActivationError @ workbench.web.api.js:1927
ms-python.vscode-unpkg.net/ms-python/vscode-pylance/2022.2.1/extension/package.nls.en-us.json:1 
        
       Failed to load resource: the server responded with a status of 404 ()
asApp:1 
        
       Tracking Prevention blocked access to storage for https://vortex.data.microsoft.com/collect/v1.
workbench.web.api.js:578  INFO [lifecycle] onBeforeUnload triggered and handled with veto support
3workbench.web.api.js:75 
        
       Uncaught (in promise) Canceled: Canceled
    at l.cancel (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:75:14167)
    at l.dispose (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:75:14296)
    at s.dispose (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:75:14558)
    at E.dispose (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:83:30388)
    at n (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:17:30028)
    at d.clear (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:17:30547)
    at dispose (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:17:30485)
    at no.dispose (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:17:31086)
    at no.close (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:590:22212)
    at https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:2970:87530
workbench.web.api.js:578 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/window.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:578:37975)
    at async Object.factory (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:579:3)
455workbench.web.api.js:578 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/exthost/webWorker/output_logging_20220215T174554/4-GitHub Repositories.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:578:37975)
    at async Object.factory (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:579:3)
workbench.web.api.js:578  INFO [lifecycle] onBeforeUnload triggered and handled with veto support
workbench.web.api.js:578 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/window.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:578:37975)
    at async Object.factory (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:579:3)
workbench.web.api.js:590 
        
       Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed
    at c.updateItems (https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:590:24361)
workbench.web.api.js:578  WARN [backup tracker] suspended, ignoring unregister event vscode-vfs://github/chrisdias/asApp/AsAppropriate.md 
workbench.web.api.js:578  WARN [backup tracker] suspended, ignoring unregister event github://github/chrisdias/asApp/AsAppropriate.md 
2workbench.web.api.js:578 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/window.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:578:37975)
    at async Object.factory (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:579:3)
3workbench.web.api.js:578 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/exthost/webWorker/output_logging_20220215T174554/4-GitHub Repositories.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:578:37975)
    at async Object.factory (vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/workbench/workbench.web.api.js:579:3)
DevTools failed to load source map: Could not load content for https://ms-vsliveshare.vscode-unpkg.net/MS-vsliveshare/vsliveshare/1.0.5330/extension/out/prod/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/node_modules/@microsoft/applicationinsights-web/dist/applicationinsights-web.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/node_modules/vscode-textmate/release/main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://vscodeweb.azureedge.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/node_modules/tas-client-umd/lib/tas-client-umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/markdown-language-features/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/npm/dist/browser/npmBrowserMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/microsoft-authentication/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/github-authentication/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/extension-editing/dist/browser/extensionEditingBrowserMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/markdown-math/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/emmet/dist/browser/emmetBrowserMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/merge-conflict/dist/browser/mergeConflictMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/core/vs/workbench/workbench.web.api.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ms-python.vscode-unpkg.net/ms-python/python/2022.0.1814523869/extension/dist/extension.browser.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/core/vs/workbench/services/keybinding/browser/keyboardLayouts/layout.contribution.darwin.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
6workbench.web.api.js:574 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/exthost/webWorker/output_logging_20220215T174554/4-GitHub Repositories.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (workbench.web.api.js:578:37975)
    at async Object.factory (workbench.web.api.js:579:3)
D @ workbench.web.api.js:574
writeFile @ workbench.web.api.js:578
Promise.then (async)
consume @ workbench.web.api.js:75
(anonymous) @ workbench.web.api.js:75
queue @ workbench.web.api.js:75
_log @ workbench.web.api.js:578
info @ workbench.web.api.js:578
_log @ workbench.web.api.js:578
info @ workbench.web.api.js:578
E @ workbench.web.api.js:578
$log @ workbench.web.api.js:1534
_doInvokeHandler @ workbench.web.api.js:1541
_invokeHandler @ workbench.web.api.js:1541
_receiveRequest @ workbench.web.api.js:1541
_receiveOneMessage @ workbench.web.api.js:1541
(anonymous) @ workbench.web.api.js:1541
fire @ workbench.web.api.js:67
N.onmessage @ workbench.web.api.js:1598
workbench.web.api.js:578   ERR Error: IndexedDB database 'vscode-web-db' is not opened.
    at I.runInTransaction (workbench.web.api.js:564:2242)
    at m.readFile (workbench.web.api.js:574:22387)
    at workbench.web.api.js:578:41145
    at m.readFileUnbuffered (workbench.web.api.js:578:41365)
    at m.doReadFileStream (workbench.web.api.js:578:39768)
    at m.doReadFile (workbench.web.api.js:578:39152)
    at m.readFile (workbench.web.api.js:578:38884)
    at async Object.factory (workbench.web.api.js:3053:113843)
workbench.web.api.js:574 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/window.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (workbench.web.api.js:578:37975)
    at async Object.factory (workbench.web.api.js:579:3)
D @ workbench.web.api.js:574
writeFile @ workbench.web.api.js:578
Promise.then (async)
consume @ workbench.web.api.js:75
(anonymous) @ workbench.web.api.js:75
queue @ workbench.web.api.js:75
_log @ workbench.web.api.js:578
error @ workbench.web.api.js:578
error @ workbench.web.api.js:578
_log @ workbench.web.api.js:578
error @ workbench.web.api.js:578
(anonymous) @ workbench.web.api.js:3053
await in (anonymous) (async)
consume @ workbench.web.api.js:75
(anonymous) @ workbench.web.api.js:75
queue @ workbench.web.api.js:75
withWebExtensions @ workbench.web.api.js:3053
readInstalledExtensions @ workbench.web.api.js:3053
scanInstalledExtensions @ workbench.web.api.js:3053
scanUserExtensions @ workbench.web.api.js:3053
await in scanUserExtensions (async)
getInstalled @ workbench.web.api.js:3054
(anonymous) @ workbench.web.api.js:3053
getInstalled @ workbench.web.api.js:3053
(anonymous) @ workbench.web.api.js:3044
Promise.then (async)
checkForMaliciousExtensions @ workbench.web.api.js:3044
loopCheckForMaliciousExtensions @ workbench.web.api.js:3044
(anonymous) @ workbench.web.api.js:3044
6workbench.web.api.js:574 
        
       Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220215T174546/exthost/webWorker/output_logging_20220215T174554/4-GitHub Repositories.log' (Error: IndexedDB database 'vscode-web-db' is not opened.)
    at m.writeFile (workbench.web.api.js:578:37975)
    at async Object.factory (workbench.web.api.js:579:3)
```

**Comment by joyceerhl** [comment]
```
 HttpError: Not Found
    at /static/main.js:1:14952
```
This is a spurious error which appears whenever the embedder attempts to validate a private repo ref without authentication, and can be ignored


```
Activating extension 'GitHub.remotehub' failed: Extension 'ms-vscode.azure-repos' CANNOT use API proposal: extensionRuntime.
Its package.json#enabledApiProposals-property declares: fileSearchProvider, textSearchProvider but NOT extensionRuntime.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode.azure-repos.
$onExtensionActivationError @ workbench.web.api.js:1927
```

Our release/0.24 branch shows that we requested `extensionRuntime` proposal access in our latest stable release of Azure Repos, not sure how this error is possible, perhaps outdated workbench? cc @lszomoru

**Comment by bpasero** [comment]
This dialog appears when the workbench enters the `onWillShutdown` phase at which components have been disposed and it would be dangerous to allow to e.g. create untitled files that would never be backed up (= data loss). In other words, when this phase starts, we block the user from doing anything meaningful.

The dialog appears slightly delayed (3 seconds) and only when we detect user interaction with the page. This is done as a measure to prevent the dialog from showing up when you reload the page and that takes a long time. 

Anyway, what is interesting is that the page did not close even after 3 seconds when you confirmed to not save the files.

**Comment by chrisdias** [comment]
@bpasero  what info is needed?

**Comment by bpasero** [comment]
Oh, somehow I thought this was about a desktop client connected to a remote, but if this is browser, then I am not sure what this could be.

To clarify: in web, if any component signals back that leaving the site is at risk of data loss, this generic dialog appears (from the browser):

![image](https://user-images.githubusercontent.com/900690/156230050-70ba3b9a-cf04-4a41-acc7-72e1a4343e02.png)

We cannot change it, the browser owns this experience. However, if you press "Cancel", my understanding is that this prevents the closing of the tab entirely. What you show here however behaves as if shutdown proceeds normally in the background (= workbench is getting disposed) even though you pressed "Cancel".

Is this reproducible in any way? Can you give it more testing on insiders.vscode.dev?

**Comment by chrisdias** [comment]
i'll try to use `insiders.` by default and see if I can get anything.
