### ISSUE TITLE
Test failure: Cannot find module '../bin/linux/x64.m49.node'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14327]
Elementary OS Freya

NodeJs v5.12.0

The integration test on my machine are failing with (./scripts/test-integration.sh)

Error: Cannot find module '../bin/linux/x64.m49.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aeschli/workspaces/vscode/node_modules/pty.js/lib/pty.js:18:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Cannot find module '../build/Release/pty.node'
[1384:1024/230133:INFO:CONSOLE(84)] "The terminal process terminated with exit code: 1", source: file:////home/aeschli/workspaces/vscode/out/vs/workbench/services/message/browser/messageService.js (84)
[1384:1024/230133:INFO:CONSOLE(84)] "The terminal process terminated with exit code: 1", source: file:////home/aeschli/workspaces/vscode/out/vs/workbench/services/message/browser/messageService.js (84)
module.js:442
    throw err;
    ^

Error: Cannot find module '../bin/linux/x64.m49.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aeschli/workspaces/vscode/node_modules/pty.js/lib/pty.js:18:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
[1384:1024/230133:INFO:CONSOLE(84)] "The terminal process terminated with exit code: 1", source: file:////home/aeschli/workspaces/vscode/out/vs/workbench/services/message/browser/messageService.js (84)
[1384:1024/230133:INFO:CONSOLE(252)] "ExtHostTerminal {
  _name: undefined,
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Fu == ExtHostTerminal {
  _name: 'foo',
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Functi: AssertionError: ExtHostTerminal {
  _name: undefined,
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Fu == ExtHostTerminal {
  _name: 'foo',
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Functi
    at /home/aeschli/workspaces/vscode/extensions/vscode-api-tests/src/window.test.ts:330:11
    at CallbackList.invoke (/home/aeschli/workspaces/vscode/out/vs/base/common/file:/home/aeschli/workspaces/vscode/src/vs/base/common/callbackList.ts:63:27)
    at Emitter.fire (/home/aeschli/workspaces/vscode/out/vs/base/common/file:/home/aeschli/workspaces/vscode/src/vs/base/common/event.ts:117:27)
    at ExtHostTerminalService.$acceptTerminalClosed (/home/aeschli/workspaces/vscode/out/vs/workbench/api/node/file:/home/aeschli/workspaces/vscode/src/vs/workbench/api/node/extHostTerminalService.ts:121:28)
    at ExtHostThreadService.AbstractThreadService.handle (/home/aeschli/workspaces/vscode/out/vs/workbench/services/thread/common/file:/home/aeschli/workspaces/vscode/src/vs/workbench/services/thread/common/abstractThreadService.ts:34:17)
    at invokeHandler (/home/aeschli/workspaces/vscode/out/vs/platform/extensions/common/file:/home/aeschli/workspaces/vscode/src/vs/platform/extensions/common/ipcRemoteCom.ts:269:40)
    at receiveOneMessage (/home/aeschli/workspaces/vscode/out/vs/platform/extensions/common/file:/home/aeschli/workspaces/vscode/src/vs/platform/extensions/common/ipcRemoteCom.ts:226:26)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)", source: file:////home/aeschli/workspaces/vscode/out/vs/workbench/electron-browser/shell.js (252)
[1384:1024/230133:INFO:CONSOLE(252)] "ExtHostTerminal {
  _name: undefined,
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Fu == ExtHostTerminal {
  _name: undefined,
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Fu: AssertionError: ExtHostTerminal {
  _name: undefined,
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Fu == ExtHostTerminal {
  _name: undefined,
  _queuedRequests: [],
  _proxy: 
   { '$createTerminal': [Function],
     '$dispose': [Fu
    at /home/aeschli/workspaces/vscode/extensions/vscode-api-tests/src/window.test.ts:330:11
    at CallbackList.invoke (/home/aeschli/workspaces/vscode/out/vs/base/common/file:/home/aeschli/workspaces/vscode/src/vs/base/common/callbackList.ts:63:27)
    at Emitter.fire (/home/aeschli/workspaces/vscode/out/vs/base/common/file:/home/aeschli/workspaces/vscode/src/vs/base/common/event.ts:117:27)
    at ExtHostTerminalService.$acceptTerminalClosed (/home/aeschli/workspaces/vscode/out/vs/workbench/api/node/file:/home/aeschli/workspaces/vscode/src/vs/workbench/api/node/extHostTerminalService.ts:121:28)
    at ExtHostThreadService.AbstractThreadService.handle (/home/aeschli/workspaces/vscode/out/vs/workbench/services/thread/common/file:/home/aeschli/workspaces/vscode/src/vs/workbench/services/thread/common/abstractThreadService.ts:34:17)
    at invokeHandler (/home/aeschli/workspaces/vscode/out/vs/platform/extensions/common/file:/home/aeschli/workspaces/vscode/src/vs/platform/extensions/common/ipcRemoteCom.ts:269:40)
    at receiveOneMessage (/home/aeschli/workspaces/vscode/out/vs/platform/extensions/common/file:/home/aeschli/workspaces/vscode/src/vs/platform/extensions/common/ipcRemoteCom.ts:226:26)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)", source: file:////home/aeschli/workspaces/vscode/out/vs/workbench/electron-browser/shell.js (252)
    1) terminal, processId immediately after createTerminal should fetch the pid

**Comment by Tyriar** [comment]
Looking into it

**Comment by aeschli** [comment]
I still get this.

Did a an git clean -xdf, ./scripts/npm install, new build...
'''
Cannot find module '../build/Release/pty.node'
module.js:442
    throw err;
    ^

Error: Cannot find module '../bin/linux/x64.m49.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aeschli/workspaces/vscode/node_modules/pty.js/lib/pty.js:18:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
[15408:1027/111540:INFO:CONSOLE(84)] "The terminal process terminated with exit code: 1", source: file:////home/aeschli/workspaces/vscode/out/vs/workbench/services/message/browser/messageService.js (84)
module.js:442
    throw err;
    ^
'''

**Comment by aeschli** [comment]
Ah, sorry, I lied, ' git clean -xdf' did the trick!

**Comment by qknight** [comment]
i just had a similar error using https://github.com/sourcelair/xterm.js:

```
node demo/app.js 
Cannot find module '../build/Release/pty.node'
module.js:471
    throw err;
    ^

Error: Cannot find module '../bin/linux/x64.m48.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/joachim/Desktop/projects/nixcloud/xterm.js/node_modules/node-pty/lib/pty.js:18:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

and i needed to rebuild it:

    cd node_modules/node-pty 
    npm install

and then it rebuilt the source:

```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> node-pty@0.4.1 install /home/joachim/Desktop/projects/nixcloud/xterm.js/node_modules/node-pty
> node scripts/install.js

make: Verzeichnis „/home/joachim/Desktop/projects/nixcloud/xterm.js/node_modules/node-pty/build“ wird betreten
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Verzeichnis „/home/joachim/Desktop/projects/nixcloud/xterm.js/node_modules/node-pty/build“ wird verlassen


> node-pty@0.4.1 postinstall /home/joachim/Desktop/projects/nixcloud/xterm.js/node_modules/node-pty
> node scripts/post-install.js

node-pty@0.4.1 /home/joachim/Desktop/projects/nixcloud/xterm.js/node_modules/node-pty
├─┬ mocha@1.17.1 
│ ├── commander@2.0.0 
│ ├─┬ debug@3.0.0 
│ │ └── ms@2.0.0 
│ ├── diff@1.0.7 
│ ├─┬ glob@3.2.3 
│ │ ├── graceful-fs@2.0.3 
│ │ ├── inherits@2.0.3 
│ │ └─┬ minimatch@0.2.14 
│ │   ├── lru-cache@2.7.3 
│ │   └── sigmund@1.0.1 
│ ├── growl@1.7.0 
│ ├─┬ jade@0.26.3 
│ │ ├── commander@0.6.1 
│ │ └── mkdirp@0.3.0 
│ └── mkdirp@0.3.5 
└── nan@2.2.1 
```

afterwards the error was gone.

**Comment by hktalent** [comment]
me too
@qknight  @aeschli

**Comment by qknight** [comment]
@hktalent what is the matter?
