### ISSUE TITLE
`tasks.json`: `isDefault` can only be set to `true`?

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode#143376]
Does this issue occur when all extensions are disabled?: Yes/No
```none
$ code --disable-extensions .
sh: 0: getcwd() failed: No such file or directory
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at setupCurrentWorkingDirectory (/usr/share/code/resources/app/out/bootstrap-node.js:1:155)
    at Object.<anonymous> (/usr/share/code/resources/app/out/bootstrap-node.js:1:260)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/share/code/resources/app/out/cli.js:1:97)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

- VS Code Version:
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
- OS Version:
OS: Linux x64 5.15.15-76051515-generic

Steps to Reproduce:

1. Enter the following into `tasks.json`

```json
            "group": {
                "kind": "build",
                "isDefault": false
            },
```

2. Review warning
```
Value is not accepted. Valid values: {"kind":"build","isDefault":true}, {"kind":"test","isDefault":true}, "build", "test", "none".(1)
```

I assume that you must elide the `isDefault` parameter to get the equivalent `"isDefault":false` behavior, but that is not obvious. I would much rather explicitly state my intention.

**Comment by zfields** [comment]
It appears the correct answer is to replace the entire object with the string "build", which is neither intuitive or obvious.

```json
            "group":"build",
```
