### ISSUE TITLE
Settings are not syncing - Request Failed

### ISSUE THREAD

**Issue by marr** [microsoft/vscode#143382]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.64.2 (Universal)
- OS Version: OSX 10.15.7 (Catalina)

Steps to Reproduce:

1. Start with a fresh install of vscode.
2. Sync settings via the "Get started" tab.
3. See error when trying to connect:
> Request failed https://vscode-sync.trafficmanager.net/v1/resource/tasks/latest

I did see a merge conflict, and tried to accept the remote, since there was nothing from the fresh install I needed. There was only a default color theme set in the local config. When I accepted remote things seemed to proceed but I have tried a few times now and not been able to complete the sync. The error I see is:
`[error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request`

**Comment by marr** [comment]
I was able to get around this issue through the instructions defined here https://code.visualstudio.com/docs/editor/settings-sync.
However, I don't see any extensions. Should those be installed after syncing?

**Comment by sandy081** [comment]
If you are able to reproduce it, can you please provide the complete Log (Settings Sync) log?

**Comment by burnumd** [comment]
I'm experiencing the same problem on VS Code Version: 1.64.2 (Universal) on Mac OS Version: 12.2.1 (Monterey). Here are my sync logs:

```
[2022-02-22 13:33:28.773] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-02-22 13:33:28.773] [settingssync] [info] Auto Sync is disabled.
[2022-02-22 13:33:40.696] [settingssync] [info] Did reset the local sync state.
[2022-02-22 13:36:02.190] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/settings/latest
[2022-02-22 13:36:02.191] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/settings/latest'.
    at m.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:195985)
    at async m.read (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:192434)
    at async y.getRemoteUserData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:58928)
    at async y._sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:49476)
    at async r.getPreviews (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:173999)
[2022-02-22 13:36:02.210] [settingssync] [info] Did reset the local sync state.
```

**Comment by burnumd** [comment]
Unfortunately (or fortunately, depending on your perspective), I can no longer reproduce the issue and the sync completed successfully as of 2022-02-24.

**Comment by sandy081** [comment]
@marr How about you? Can you please provide requested info?
