### ISSUE TITLE
TS Server fatal error:  Cannot read property 'charCount' of undefined

### ISSUE THREAD

**Issue by ghyath5** [microsoft/vscode#143452]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172924:68)
    at LineIndex.edit (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172805:31)
    at ScriptVersionCache._getSnapshot (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172595:47)
    at ScriptVersionCache.lineOffsetToPosition (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172614:29)
    at TextStorage.lineOffsetToPosition (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:163635:33)
    at ScriptInfo.lineOffsetToPosition (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:163999:41)
    at c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170271:56
    at Object.next (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:636:33)
    at ProjectService.applyChangesToFile (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169124:46)
    at ProjectService.applyChangesInOpenFiles (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169091:30)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170262:46)
    at c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172195:88
    at IOSession.Session.executeWithRequestId (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172186:28)
    at IOSession.Session.executeCommand (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172195:33)
    at IOSession.Session.onMessage (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172221:35)
    at Interface.<anonymous> (c:\Users\ghyat\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174826:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.89GB free)|
|Process Argv|--crash-reporter-id 946ba327-7e87-4826-a6ed-1cf5da6e72a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
quasar-snippets|abd|1.0.0
html-snippets|abu|0.2.1
svelte-intellisense|ard|0.7.1
sqf|Arm|2.0.3
atlascode|atl|2.10.9
vscode-tailwindcss|bra|0.7.7
postcss|css|1.0.9
dart-code|Dar|3.34.0
flutter|Dar|3.34.0
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.2.0
auto-close-tag|for|0.5.14
go|gol|0.31.1
vue-snippets|hol|1.0.4
vue|jcb|0.1.5
graphql-for-vscode|kum|1.15.3
smalise|Loy|0.0.12
edge|luo|0.3.2
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
cpptools|ms-|1.8.4
powershell|ms-|2021.12.0
vscode-react-native|msj|1.9.1
vetur|oct|0.35.0
arma-dev|ole|0.0.20
material-icon-theme|PKi|4.13.0
prisma|Pri|3.9.2
vscode-yaml|red|1.4.0
apklab|Sur|1.6.0
svelte-vscode|sve|105.12.1
import-to-require|tle|0.7.0
pdf|tom|1.2.0
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-maven|vsc|0.35.0
vuetify-vscode|vue|0.2.0
save-as-root|yy0|1.3.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30438799
helix:30440343

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides the built-in JS/TS one)?
