### ISSUE TITLE
TS Server fatal error:  Debug Failure / No Project errors

### ISSUE THREAD

**Issue by justjake** [microsoft/vscode#143426]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.5

**Steps to reproduce crash**
1. Produce a Typescript monorepo with the followint structure:
```
├── src
│   ├── cli
│   │   ├── package.json
│   │   └── tsconfig.json
│   ├── front
│   │   ├── node_modules
│   │   ├── package.json
│   │   └── tsconfig.json
│   ├── server
│   │   ├── package.json
│   │   └── tsconfig.json
│   ├── shared
│   │   ├── package.json
│   │   └── tsconfig.json
├── node_modules
├── package-lock.json
├── package.json
├── tsconfig.base.json
├── tsconfig.json
```

2. Open files in several different projects
3. Hover over word and wait for definition to appear. TSServer may crash.

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:

```
Info 0    [14:48:36.887] Starting TS Server
Info 1    [14:48:36.887] Version: 4.5.5
Info 2    [14:48:36.887] Arguments: /Users/jitl/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/6f/y7zxg6h56r38gv53tqxxcwv00000gq/T/vscode-typescript503/4ccf805d3065fc640363/tscancellation-10a2da868168d0700250.tmp* --logVerbosity verbose --logFile /Users/jitl/Library/Application Support/Code/logs/20220218T084700/exthost1/vscode.typescript-language-features/tsserver-log-DgcnRV/tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [14:48:36.887] Platform: darwin NodeVersion: 14 CaseSensitive: false
Info 4    [14:48:36.887] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [14:48:36.891] Binding...
Info 6    [14:48:36.895] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true,"includePackageJsonAutoImports":"auto"},"watchOptions":{}}}
Info 7    [14:48:36.895] Host information vscode
Info 8    [14:48:36.895] Host watch options changed to undefined, it will be take effect for next watches.
Info 9    [14:48:36.895] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 10   [14:48:36.895] 0::configure: async elapsed time (in milliseconds) 0.6777
Info 11   [14:48:36.895] request:
    {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2020","jsx":"preserve","strictFunctionTypes":true,"sourceMap":true,"allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"resolveJsonModule":true}}}
Perf 12   [14:48:36.895] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.1308
Info 13   [14:48:36.895] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 14   [14:48:36.896] request:
    {"seq":2,"type":"request","command":"configurePlugin","arguments":{"pluginName":"@monodon/typescript-nx-imports-plugin","configuration":{"externalFiles":[]}}}
Info 15   [14:48:36.896] response:
    {"seq":0,"type":"response","command":"configurePlugin","request_seq":2,"success":true}
Perf 16   [14:48:36.896] 2::configurePlugin: async elapsed time (in milliseconds) 0.0720
Info 17   [14:48:36.896] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":53832}}
Info 18   [14:48:36.932] request:
    {"seq":3,"type":"request","command":"geterr","arguments":{"delay":0,"files":["/Users/jitl/src/notion/src/front/shared/XXXXXXXXXXXXXXXXX.ts","/Users/jitl/src/notion/.eslintrc.js","/Users/jitl/src/notion/src/shared/frontApiTypes.ts","/Users/jitl/src/notion/src/server/apis/index.ts","/Users/jitl/src/notion/src/front/components/ZZZZZZZZZZZZZ/YYYYYYYYYYYYYYYYYYY.tsx","/Users/jitl/src/notion/src/cli/commands/VVVVVVVVVVVV.ts","/Users/jitl/src/notion/src/front/components/RichText.tsx"]}}
Perf 19   [14:48:36.933] 3::geterr: async elapsed time (in milliseconds) 0.5438
Info 20   [14:48:36.941] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":3}}
Info 21   [14:48:37.846] request:
    {"seq":4,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":405,"startOffset":32,"endLine":405,"endOffset":32}}
Err 22    [14:48:37.846] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 23    [14:48:37.856] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 24    [14:48:37.856] Exception on executing command {"seq":4,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":405,"startOffset":32,"endLine":405,"endOffset":32}}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)
        at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)
        at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)
        at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)
        at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)
        at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)
        at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88
        at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)
        at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)
        at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)
        at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 25   [14:48:37.856] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":4,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)\n    at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)\n    at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)\n    at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)\n    at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)\n    at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88\n    at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)\n    at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)\n    at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)\n    at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:337:10)\n    at Interface._normalWrite (readline.js:482:12)\n    at Socket.ondata (readline.js:194:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}
Info 26   [14:48:38.658] request:
    {"seq":5,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":397,"startOffset":7,"endLine":397,"endOffset":7}}
Err 27    [14:48:38.659] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 28    [14:48:38.659] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 29    [14:48:38.659] Exception on executing command {"seq":5,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":397,"startOffset":7,"endLine":397,"endOffset":7}}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)
        at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)
        at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)
        at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)
        at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)
        at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)
        at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88
        at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)
        at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)
        at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)
        at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 30   [14:48:38.659] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":5,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)\n    at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)\n    at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)\n    at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)\n    at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)\n    at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88\n    at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)\n    at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)\n    at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)\n    at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:337:10)\n    at Interface._normalWrite (readline.js:482:12)\n    at Socket.ondata (readline.js:194:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}
Info 31   [14:49:02.658] request:
    {"seq":6,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":396,"startOffset":16,"endLine":396,"endOffset":16}}
Err 32    [14:49:02.658] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 33    [14:49:02.658] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 34    [14:49:02.658] Exception on executing command {"seq":6,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":396,"startOffset":16,"endLine":396,"endOffset":16}}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)
        at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)
        at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)
        at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)
        at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)
        at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)
        at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88
        at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)
        at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)
        at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)
        at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 35   [14:49:02.658] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":6,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)\n    at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)\n    at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)\n    at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)\n    at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)\n    at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88\n    at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)\n    at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)\n    at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)\n    at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:337:10)\n    at Interface._normalWrite (readline.js:482:12)\n    at Socket.ondata (readline.js:194:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}
Info 36   [14:49:03.684] request:
    {"seq":7,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":397,"startOffset":7,"endLine":397,"endOffset":7}}
Err 37    [14:49:03.685] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 38    [14:49:03.685] Could not find file "/Users/jitl/src/notion/src/front/components/RichText.tsx".
All files are: []
Err 39    [14:49:03.685] Exception on executing command {"seq":7,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/jitl/src/notion/src/front/components/RichText.tsx","startLine":397,"startOffset":7,"endLine":397,"endOffset":7}}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)
        at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)
        at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)
        at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)
        at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)
        at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)
        at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88
        at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)
        at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)
        at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)
        at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 40   [14:49:03.685] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":7,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:163027:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166863:131)\n    at ProjectService.ensureDefaultProjectForFile (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:166858:75)\n    at IOSession.Session.getFileAndProjectWorker (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171383:87)\n    at IOSession.Session.getFileAndProject (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171366:29)\n    at IOSession.Session.getApplicableRefactors (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:171825:31)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170536:61)\n    at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88\n    at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)\n    at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)\n    at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)\n    at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:337:10)\n    at Interface._normalWrite (readline.js:482:12)\n    at Socket.ondata (readline.js:194:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}
Info 41   [14:49:04.075] request:
    {"seq":8,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"/Users/jitl/src/notion/src/front/components/RichText.tsx","textChanges":[{"newText":"\n\t","start":{"line":397,"offset":8},"end":{"line":397,"offset":8}}]}],"closedFiles":[],"openFiles":[]}}
Err 42    [14:49:04.075] Exception on executing command {"seq":8,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"/Users/jitl/src/notion/src/front/components/RichText.tsx","textChanges":[{"newText":"\n\t","start":{"line":397,"offset":8},"end":{"line":397,"offset":8}}]}],"closedFiles":[],"openFiles":[]}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at ProjectService.applyChangesInOpenFiles (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:169089:34)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170262:46)
        at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88
        at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)
        at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)
        at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)
        at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 43   [14:49:04.075] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":8,"success":false,"message":"Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at ProjectService.applyChangesInOpenFiles (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:169089:34)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170262:46)\n    at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88\n    at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)\n    at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)\n    at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)\n    at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:337:10)\n    at Interface._normalWrite (readline.js:482:12)\n    at Socket.ondata (readline.js:194:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}

```

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:169089:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:170262:46)
    at /Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:88
    at IOSession.Session.executeWithRequestId (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172186:28)
    at IOSession.Session.executeCommand (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172195:33)
    at IOSession.Session.onMessage (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:172221:35)
    at Interface.<anonymous> (/Users/jitl/src/notion/node_modules/typescript/lib/tsserver.js:174826:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 7|
|Memory (System)|64.00GB (0.08GB free)|
|Process Argv|. --crash-reporter-id 40d8761f-b9fd-401c-8346-b9160bf201bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.23.0
texinfo|cis|0.2.4
doxdocgen|csc|1.3.2
mustache|daw|1.1.1
vscode-eslint|dba|2.2.2
vscode-styled-jsx-languageserver|Div|1.3.0
vscode-styled-jsx-syntax|Div|1.3.0
vscode-wasm|dts|1.3.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
file-icons|fil|1.0.29
flow-for-vscode|flo|2.0.0
kotlin|fwc|0.2.23
copilot|Git|1.7.5067
vscode-pull-request-github|Git|0.36.2
base16-generator|gol|1.15.0
terraform|has|2.19.0
better-cpp-syntax|jef|1.15.13
theme-karyfoundation-themes|kar|25.2.3
rust-analyzer|mat|0.2.940
theme-monokai-pro-vscode|mon|1.1.20
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
angular-console|nrw|17.14.1
material-icon-theme|PKi|4.13.0
prisma|Pri|3.9.2
seti-icons|qin|0.1.3
ruby|reb|0.28.1
mdx|sil|0.1.0
vscode-fileutils|sle|3.5.0
swift-lang|ssw|0.2.0
code-spell-checker|str|2.1.7
ayu|tea|1.0.5
shellcheck|tim|0.18.8
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscode-icons|vsc|11.10.0
vim|vsc|1.22.1
gitblame|wad|8.1.0
vscode-ruby|win|0.28.0

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30438341
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaac:30438847

```

</details>

**Comment by mjbvz** [comment]
Does this also reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
If so, please also just share a minimal project instead of describing its structure. It saves us from  having to waste time recreating it for testing
