### ISSUE TITLE
[DEP0005] DeprecationWarning

### ISSUE THREAD

**Issue by aGensinger** [microsoft/vscode#143535]
Issue Type: <b>Bug</b>

steps:  
1.start VSCODE
2.view log(window) as follow:
[2022-02-21 18:31:23.540] [renderer1] [info] IExtensionHostStarter.start() took 1149 ms.
[2022-02-21 18:31:24.027] [renderer1] [error] [Extension Host] (node:14496) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)

actual result: outline panel no symbols found in document

expect result: outline works fine

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.16299
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (5.40GB free)|
|Process Argv|--crash-reporter-id 6771778a-37c2-4f54-967d-7e3066f8ecf1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-works-outline|Kic|0.1.7
cpptools|ms-|1.8.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30438801
helix:30440343

```

</details>

**Comment by aGensinger** [comment]
with disable all extensions

**Comment by gjsjohnmurray** [comment]
/duplicate #136874 and maybe fixed in upcoming 1.65. Can you test with [Insiders](https://code.visualstudio.com/insiders)?

**Comment by aGensinger** [comment]
@gjsjohnmurray 

> /duplicate #136874 and maybe fixed in upcoming 1.65. Can you test with [Insiders](https://code.visualstudio.com/insiders)?

![image](https://user-images.githubusercontent.com/63466072/154948501-d2be8e5b-da2b-436e-bd4a-40f88c857935.png)
Thanks for you reply! Insiders still display error about [Extension Host] .

**Comment by aGensinger** [comment]
and in /duplicate #136874, some operations is confusing for me.
![image](https://user-images.githubusercontent.com/63466072/154949830-f9521e51-f0a5-4871-acd9-e6b5b5a0c730.png)

**Comment by aGensinger** [comment]
@gjsjohnmurray @vscode-triage-bot Maybe it's because of my software environment，could u help me to analyze it?

**Comment by gjsjohnmurray** [comment]
pinging @chrmarti

**Comment by chrmarti** [comment]
@bpasero Is there a simpler way than changing code to enable tracing for deprecations (https://github.com/microsoft/vscode/issues/136874#issuecomment-966442845) in the extension host?

**Comment by aGensinger** [comment]
@vscode-triage-bot @bpasero @gjsjohnmurray @chrmarti 
[2022-02-23 10:47:59.405] [renderer1] [info] IExtensionHostStarter.start() took 1243 ms.
[2022-02-23 10:47:59.819] [renderer1] [error] [Extension Host] (node:10132) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-02-23 10:48:56.991] [renderer1] [error] Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at v.next (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:71662)
    at v.reset (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:71548)
    at d._delete (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:76997)
    at d._delete (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:77386)
    at delete (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:76907)
    at vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:573:41773
    at o.fire (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1712)
    at x.triggerConfigurationChange (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:42557)
    at x.onLocalUserConfigurationChanged (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:35757)
    at x.reloadLocalUserConfiguration (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:33039)
    at async Promise.all (index 0)
    at async Object.X [as settled] (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:23186)
    at async x.updateValue (vscode-file://vscode-app/c:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:27260)
[2022-02-23 11:02:34.101] [renderer1] [warning] {}
[2022-02-23 11:04:59.897] [renderer1] [info] IExtensionHostStarter.start() took 1292 ms.
[2022-02-23 11:05:00.461] [renderer1] [error] [Extension Host] (node:25708) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:194:11)
    at new Buffer (buffer.js:281:3)
    at Object.<anonymous> (c:\Microsoft VS Code\resources\app\node_modules.asar\ftp\lib\connection.js:52:17)
    at Module.u._compile (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Microsoft VS Code\resources\app\node_modules.asar\get-uri\dist\ftp.js:16:31)
    at Module.u._compile (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Microsoft VS Code\resources\app\node_modules.asar\get-uri\dist\index.js:10:31)
    at Module.u._compile (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:17:35)
    at Module.u._compile (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:40:30)
    at Module.u._compile (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (c:\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
    at e.load (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1720)
    at e.load (c:\Microsoft VS Code\resources\app\out\vs\loader.js:3:10695)
    at d (c:\Microsoft VS Code\resources\app\out\vs\loader.js:5:10300)
    at i._loadModule (c:\Microsoft VS Code\resources\app\out\vs\loader.js:5:10430)
    at i._resolve (c:\Microsoft VS Code\resources\app\out\vs\loader.js:6:452)
    at i.defineModule (c:\Microsoft VS Code\resources\app\out\vs\loader.js:5:6142)
    at v (c:\Microsoft VS Code\resources\app\out\vs\loader.js:6:1702)
    at g (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:2554)
    at Object.<anonymous> (c:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:108:58092)
    at Object.<anonymous> (c:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:36664)
    at e._createAndEvalScript (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:2598)
    at c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:2237
    at h (c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:4189)
    at c:\Microsoft VS Code\resources\app\out\vs\loader.js:4:4262
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

**Comment by chrmarti** [comment]
@aGensinger This appears to be from an older version. Could you retry with the latest VS Code Insiders version?
