### ISSUE TITLE
ERR Cannot read properties of undefined (reading 'dispose')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143609]
Saw this trying the steps in https://github.com/microsoft/vscode/issues/134180#issuecomment-1047153230. Code looks fishy, using `!` to override strict null: `this._modelTrackers.get(modelUrl)!.dispose();`

```
ERR Cannot read properties of undefined (reading 'dispose'): TypeError: Cannot read properties of undefined (reading 'dispose')
    at MainThreadDocuments.handleModelRemoved (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadDocuments.js:169:46)
    at Array.forEach (<anonymous>)
    at MainThreadDocumentsAndEditors._onDelta (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadDocumentsAndEditors.js:270:34)
    at MainThreadDocumentAndEditorStateComputer._onDidChangeState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadDocumentsAndEditors.js:218:92)
    at MainThreadDocumentAndEditorStateComputer._updateState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadDocumentsAndEditors.js:176:22)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadDocumentsAndEditors.js:96:228
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:420:27)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:559:34)
    at BooleanEventEmitter.setValue (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:1325:41)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:142:41
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:420:27)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:559:34)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/editor/browser/widget/codeEditorWidget.js:1506:32
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:420:27)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:559:34)
    at HTMLDivElement.onFocus (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/dom.js:795:38)
```

**Comment by jrieken** [comment]
> Code looks fishy, using ! to override strict null:

Only at first sight, but `set` and `delete` on `_modelTrackers` just be the same as on `_modelIsSynced` and therefore the guard to catch it... There is an asymmetry with disposing tho - my guess is that the object is disposed but that someone is still talking to it...
