### ISSUE TITLE
Connection error shown incorrectly when the remote extension host crashes

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode#143645]
- VSCode Version:

```
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

- Local OS Version: `Windows 10`
- Remote OS Version: `RHEL 8`
- Remote Extension/Connection Type: SSH
- Logs: (pasted at the end)

Steps to Reproduce:

1. Connected to SSH Remote via VSCode, with all extensions disabled.
2. Open a new file, select file language to be `Markdown`
3. Paste following text

```
http://localhost:8081

操
```

![demo](https://user-images.githubusercontent.com/7172560/154193555-fe0bc9af-288a-4cc1-a390-18930edea4d1.gif)

NOTE: If paste with text without Chinese charactor, it doesn't crash.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No
Does this issue occur when you try this remotely and all extensions are disabled?: Yes

Log: (it's all repeating log messages like 100 times before crash, so only pasting last few messages)

```
[2022-02-15 22:39:09.250] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:34.924] [exthost] [info] extension host terminating: renderer closed the socket
[2022-02-15 22:39:34.926] [exthost] [info] Extension host with pid 13744 exiting with code 0
```

**Comment by tigerinus** [comment]
> I cannot reproduce this. If I use the command `F1 > Developer: Reload With Extensions Disabled` while in a SSH remote window, then the window reloads and the user installed extensions are disabled for me.

Did you install the gistpad extension?

**Comment by roblourens** [comment]
> Resolver extensions are excluded

@sandy081  I'm talking about normal extensions in the remote EH

**Comment by alexdima** [comment]
An extension that can be used to test this:
* `package.json`
```json
{
    "publisher": "alex",
    "name": "crashing",
    "engines": {
        "vscode": "^1.0.0"
    },
    "version": "0.0.0",
    "activationEvents": [
        "*"
    ],
    "main": "./index.js",
    "dependencies": {
        "native-watchdog": "1.3.0"
    },
    "contributes": {
        "commands": [{
            "command": "crashing.crashNow",
            "title": "Crash now!"
        }]
    }
}
```
* `index.js`:
```json

const vscode = require('vscode');
const nativeWatchdog = require('native-watchdog');

exports.activate = function() {
    vscode.commands.registerCommand('crashing.crashNow', () => {
        nativeWatchdog.exit(-1);
    })
};
```

The error currently looks like this:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/5047891/155736566-91a5762c-97c7-452a-9e50-61d5aef23bc5.png">


```
ERR Error: Connection error: Unknown reconnection token (seen before)
    at getErrorFromMessage (remoteAgentConnection.js:578)
    at remoteAgentConnection.js:226
    at Listener.invoke (event.js:420)
    at Emitter.fire (event.js:559)
    at BufferedEmitter.fire (ipc.net.js:478)
    at PersistentProtocol._receiveMessage (ipc.net.js:732)
    at ipc.net.js:671
    at Listener.invoke (event.js:420)
    at Emitter.fire (event.js:559)
    at ProtocolReader.acceptChunk (ipc.net.js:269)
    at ipc.net.js:236
    at browserSocketFactory.js:150
    at Listener.invoke (event.js:420)
    at Emitter.fire (event.js:559)
    at FileReader.BrowserWebSocket._fileReader.onload (browserSocketFactory.js:31)
```
