### ISSUE TITLE
TypeError: Cannot read property 'activateByEvent' of undefinedon

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1437]
Just got this (somehow) running out of dev:

```
[uncaught exception]: TypeError: Cannot read property 'activateByEvent' of undefinedonError @ index.html:24
index.html:27 TypeError: Cannot read property 'activateByEvent' of undefined
    at PluginWorkbenchKeybindingService._invokeHandler (file:////Users/bpasero/Development/monaco/out/vs/workbench/services/keybinding/electron-browser/pluginKeybindingService.js:430:39)
    at PluginWorkbenchKeybindingService.KeybindingService._dispatch (file:////Users/bpasero/Development/monaco/out/vs/platform/keybinding/browser/keybindingServiceImpl.js:183:22)
    at file:////Users/bpasero/Development/monaco/out/vs/platform/keybinding/browser/keybindingServiceImpl.js:99:23
    at wrapHandler (file:////Users/bpasero/Development/monaco/out/vs/base/browser/dom.js:245:13)
    at EventEmitter.ipc.sendSync (/Users/bpasero/Development/monaco/.build/electron/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at Object.exports.getCurrentWindow (/Users/bpasero/Development/monaco/.build/electron/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:222:16)
    at WindowService.getWindowId (file:////Users/bpasero/Development/monaco/out/vs/workbench/services/window/electron-browser/windowService.js:28:27)
    at LifecycleService.registerListeners (file:////Users/bpasero/Development/monaco/out/vs/workbench/services/lifecycle/electron-browser/lifecycleService.js:22:47)
    at new LifecycleService (file:////Users/bpasero/Development/monaco/out/vs/workbench/services/lifecycle/electron-browser/lifecycleService.js:18:18)
    at WorkbenchShell.initInstantiationService (file:////Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/shell.js:147:36)onError @ index.html:27
//Users/bpasero/Development/monaco/out/vs/workbench/services/keybinding/electron-browser/pluginKeybindingService.js:430 Uncaught TypeError: Cannot read property 'activateByEvent' of undefined
```

**Comment by alexandrudima** [comment]
Already fixed in master
