### ISSUE TITLE
Python extension fails to activate for missing API proposal entry that is actually not missing   

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#143834]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.65.0-insider
- OS Version: Windows 11
The Python extension is failing to activate in the latest insiders build, and the error says it's because it's trying to use an API proposal that wasn't declared but it actually is. Specifically, it complains about `testObserver` but it's declared here: https://github.com/microsoft/vscode-python/blob/84a5a04ae416d794ca9a03b7d705ee5f8aecb834/package.json#L21

Steps to Reproduce:
1. Download the latest version of the Python insiders build (run the "Python: Switch to Insiders Weekly" command, we will migrate to the pre-release mechanism shortly)
2. Open a Python file to activate the extension (or run the "Python: Select Interpreter" command)
2. Open the Python channel in the Output panel 
3. See the error below:

```
[ERROR 2022-1-23 16:1:48.161]: Failure during activation. [Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at _ (c:\Users\luabud\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:64832)
	at Object.get testResults [as testResults] (c:\Users\luabud\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:33817)
	at w.activate (c:\Users\luabud\.vscode-insiders\extensions\ms-python.python-2022.1.1884760391-dev\out\client\extension.js:85:74911)
	at c:\Users\luabud\.vscode-insiders\extensions\ms-python.python-2022.1.1884760391-dev\out\client\extension.js:67:87919
	at Array.map (<anonymous>)
	at f.activateWorkspace (c:\Users\luabud\.vscode-insiders\extensions\ms-python.python-2022.1.1884760391-dev\out\client\extension.js:67:87910)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
[ERROR 2022-1-23 16:1:48.162]: sendStartupTelemetry() failed. [Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at _ (c:\Users\luabud\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:64832)
	at Object.get testResults [as testResults] (c:\Users\luabud\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:33817)
	at w.activate (c:\Users\luabud\.vscode-insiders\extensions\ms-python.python-2022.1.1884760391-dev\out\client\extension.js:85:74911)
	at c:\Users\luabud\.vscode-insiders\extensions\ms-python.python-2022.1.1884760391-dev\out\client\extension.js:67:87919
	at Array.map (<anonymous>)
	at f.activateWorkspace (c:\Users\luabud\.vscode-insiders\extensions\ms-python.python-2022.1.1884760391-dev\out\client\extension.js:67:87910)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]

```

**Comment by TylerLeonhardt** [comment]
I'm guessing this is because said API was just finalized? But maybe I'm wrong.

**Comment by Startouf** [comment]
I'm having a similar error on 
os: macOS Big Sur 11.6.1
Version: 1.65.0-insider
Commit: 8440b8f47231147823ba9696913d642e5f2d9d58

It is rather severely breaking my experience on python and DBT. I will have to switch back to the non-insider build if this is not resolved soon

**Comment by jrieken** [comment]
Sorry for that. There is a typo in the allow list. It says `"python.python"` instead of `"ms-python.python"`
