### ISSUE TITLE
Fails to load under WSL

### ISSUE THREAD

**Issue by liborty** [microsoft/vscode#143990]
Does this issue occur when all extensions are disabled?:  Yes and extensions all fail to load as well and extensions bisect does not run either

- VS Code Version: Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

- OS Version: Windows 11 Home: Version	10.0.22000 Build 22000

Steps to Reproduce:

1. Run code either under WSL or from WIndows
2. Code comes up but is stuck in an infinite loop, failing to load "remote WSL", i.e. previously working WSL folder

**Comment by aeschli** [comment]
If you disable all extension, does the Remote WSL window come up?
- close all VS Code windows
- from a WSL terminal: `code --disable-extensions .`

If not, can you paste the WSL log here (Command: `Remote-WSL: Show Log`

**Comment by liborty** [comment]
Thanks. It gets stuck in an infinite loop "opening remote connection" and that Remote-WSL command does not exist.

**Comment by liborty** [comment]
However, I did find some ordinary log that may be relevant:
[2022-03-01 11:20:50.812] [exthost] [info] Extension host with pid 10144 started
[2022-03-01 11:20:50.812] [exthost] [info] Skipping acquiring lock for c:\Users\libor\AppData\Roaming\Code\User\workspaceStorage\9bb9bd6cf2e378d9095b13851f18df4d.
[2022-03-01 11:20:50.836] [exthost] [info] $getCanonicalURI invoked for authority (wsl)
[2022-03-01 11:20:50.843] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onResolveRemoteAuthority:wsl'
[2022-03-01 11:20:50.914] [exthost] [info] $resolveAuthority invoked for authority (wsl)

**Comment by liborty** [comment]
When I then restart it from WSL bash in the local directory, it gets stuck again, presumably because that WSL extension, when active,  is totally failing to read any WSL directories.

**Comment by liborty** [comment]
The wsl remote extension is stuck, it only shows the uninstall option but will not uninstall or do anything. I have tried several times uninstalling and reinstalling Code and its remote server but none of it makes any difference. Is there any way of cleaning up this wsl remote extension directly?

**Comment by aeschli** [comment]
Can you paste a screenshot of the 'useless state'?

**Comment by liborty** [comment]
[2022-03-02 15:23:10.532] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2022-03-02 15:23:10.988] [renderer1] [info] IExtensionHostStarter.start() took 57 ms.
[2022-03-02 15:23:11.628] [renderer1] [error] [Extension Host] (node:13016) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-03-02 15:23:11.922] [renderer1] [info] Invoking resolveAuthority(wsl)
[2022-03-02 15:23:12.145] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2022-03-02 15:23:24.132] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2022-03-02 15:23:39.336] [renderer1] [error] Unable to write to Folder Settings because no resource is provided.: Error: Unable to write to Folder Settings because no resource is provided.
    at w.toConfigurationEditingError (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:12622)
    at w.validate (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:16299)
    at w.doWriteConfiguration (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:9369)
    at Object.factory (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:9203)
    at D.consume (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:16521)
    at vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:16336
    at new Promise (<anonymous>)
    at D.queue (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:16260)
    at writeConfiguration (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:9188)
    at x.writeConfigurationValue (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:41576)
    at vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:27299
    at Array.map (<anonymous>)
    at x.updateValue (vscode-file://vscode-app/c:/Users/libor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:27287)
[2022-03-02 15:24:07.459] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2022-03-02 15:24:14.995] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2022-03-02 15:24:20.984] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings

**Comment by aeschli** [comment]
What I still would like to see is the WSL Log. It's a tab in the terminal.

You can set `"remote.WSL.debug": true` to make sure it is shown.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/156356019-5a013901-9640-469c-8665-2aa2da6c460e.png)

**Comment by liborty** [comment]
Sorry, it says nothing, just 'session contents restored', after I close the remote connection and try to open a folder. Until then, it is just trying to open the connection.

**Comment by liborty** [comment]
Thanks for trying (unsuccessfully) to help. 
I have now uninstalled code, WSL and Windows.
I have only so much time for these deep mysteries.

**Comment by aeschli** [comment]
ok, sorry for that but, thanks for your help.
