### ISSUE TITLE
Web: running out of sources prints tons of errors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#144025]
I am following the vscode-dev setup (https://github.com/microsoft/vscode-dev#development) and serve files from a local `vscode` file that is from `main`. Opening http://localhost:3000/?vscode-quality=dev I see many errors printed:

```
console.js:104 [Extension Host] SyntaxError: Unexpected token '<'    at new Function (<anonymous>)    at ExtHostExtensionService._loadCommonJSModule (/vs/workbench/api/worker/file:/Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/worker/extHostExtensionService.ts:86:4)    at async Promise.all (index 0)    at async Promise.all (index 0)    at async Promise.all (index 0)
log @ console.js:104
notificationsAlerts.js:29 SyntaxError: Unexpected token '<'
    at new Function (<anonymous>)
    at ExtHostExtensionService._loadCommonJSModule (:3000/vs/workbench/api/worker/file:/Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/worker/extHostExtensionService.ts:86:4)
    at async Promise.all (:3000/index 0)
    at async Promise.all (:3000/index 0)
    at async Promise.all (:3000/index 0)
onDidChangeNotification @ notificationsAlerts.js:29
log.js:231   ERR [Extension Host] Loading code for extension vscode.github-authentication failed: Unexpected token '<'
```

**Comment by bpasero** [comment]
Duplicate of https://github.com/microsoft/vscode-dev/issues/529
