### ISSUE TITLE
Extension failing on start

### ISSUE THREAD

**Issue by FultonBrowne** [microsoft/vscode#144121]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

On launch of VS-code I get this error and no extension functionality
![bug-report](https://user-images.githubusercontent.com/50185337/156024070-f5756c0d-822e-477d-af13-34b32ad98a71.png)

### VS Code Version

Version: 1.64.2 Commit: f80445acd5a3dadef24aa209168452a3d97cc326 Date: 2022-02-10T22:49:45+00:00 Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Linux x64 5.14.21-210.current

### Jupyter Extension Version

v2022.1.1301854968

### Jupyter logs

```shell
Visual Studio Code (1.64.2, undefined, desktop)
Jupyter Extension Version: 2022.1.1301854968.
Python Extension Version: 2022.0.1814523869.
Info 10:54:36: ZMQ install verified.
Error 10:54:36: extension activation failed [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookEditor.
Its package.json#enabledApiProposals-property declares:  but NOT notebookEditor.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at checkProposedApiEnabled (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47580:19)
	at Object.onDidChangeCellMetadata (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:69592:62)
	at u.addEventHandlers (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:795058)
	at new u (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:793723)
	at Object.t.resolveInstance (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:237383)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236588
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:237153)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236588
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:235536
	at Array.map (<anonymous>)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:235508
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:237153)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236588
	at Object.t.resolve (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236851)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:227948
	at e._get (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:227714)
	at e.get (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:226426)
	at a.get (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:124:61150)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:275368
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:51:785282
	at async t.activate (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:51:784961)]
Error 10:54:36: Failed to active the Jupyter Extension [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookEditor.
Its package.json#enabledApiProposals-property declares:  but NOT notebookEditor.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at checkProposedApiEnabled (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47580:19)
	at Object.onDidChangeCellMetadata (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:69592:62)
	at u.addEventHandlers (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:795058)
	at new u (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:793723)
	at Object.t.resolveInstance (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:237383)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236588
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:237153)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236588
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:235536
	at Array.map (<anonymous>)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:235508
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:237153)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236588
	at Object.t.resolve (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:236851)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:227948
	at e._get (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:227714)
	at e.get (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:226426)
	at a.get (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:124:61150)
	at /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:275368
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:51:785282
	at async t.activate (/home/fulton/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:51:784961)]
```

### Coding Language and Runtime Version

Python 3.9.9,  $ jupyter --version Selected Jupyter core packages... IPython          : 8.1.0 ipykernel        : 6.9.1 ipywidgets       : not installed jupyter_client   : 7.1.2 jupyter_core     : 4.9.2 jupyter_server   : 1.13.5 jupyterlab       : 3.2.9 nbclient         : 0.5.11 nbconvert        : 6.4.2 nbformat         : 5.1.3 notebook         : 6.4.8 qtconsole        : not installed traitlets        : 5.1.1

### Language Extension Version (if applicable)

Python v2022.0.1814523869

### Running Jupyter locally or remotely?

Local

**Comment by greazer** [comment]
Apparently the Python extension is suffering a similar (if not duplicate) issue

**Comment by DonJayamanne** [comment]
Probably similar to https://github.com/microsoft/vscode/issues/143834

**Comment by DonJayamanne** [comment]
@jrieken 
this isn't a duplicate. on this case the extension id is different, the other issues was related to the python extension.
dinner hours this is taking in stable vscode using the attached version of the extension.

reopening as is not a duplicate

**Comment by jrieken** [comment]
Thanks for clarifying.. Tho, now I am really puzzled, stable is out since quite a while and I am sure that there is more than one user... Also, for 1.64 the `product.json`-file spells out the correct proposals. @FultonBrowne Is this VS Code the product and a different build like Codium?

**Comment by FultonBrowne** [comment]
This the OSS build packaged for Solus Linux. You can check [this](https://dev.getsol.us/source/vscode/) out for more info on the build they use

**Comment by jrieken** [comment]
Ok, thanks for clarifying. Please raise this issue against them. Allowing extensions to use proposed API is a product configuration and it seems this didn't happen for the flavour that you are using.
