### ISSUE TITLE
TS Server fatal error:  Cannot read property 'getSourceFiles' of undefined

### ISSUE THREAD

**Issue by ahules** [microsoft/vscode#144337]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.1-rc

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'getSourceFiles' of undefined
    at ConfiguredProject.Project.getScriptInfos (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:166585:44)
    at ProjectService.sendProjectTelemetry (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169448:66)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167802:37)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169522:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170605:44)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170945:97
    at Object.flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170945:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172104:46)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174040:88
    at IpcIOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174031:28)
    at IpcIOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174040:33)
    at IpcIOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174066:35)
    at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176701:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

VS Code version: Code - Insiders 1.65.0-insider (b7730c807c1e0fdacdcc91a854bb963715b2a89b, 2022-02-28T14:38:07.627Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id 5a441443-6769-4689-8276-adf6a4907190|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.1.7
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.3
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
gitkraken-authentication|git|1.0.3
go|gol|0.31.1
vue|jcb|0.1.5
better-cpp-syntax|jef|1.15.13
dotenv|mik|1.0.1
vscode-docker|ms-|1.20.0
cmake-tools|ms-|1.10.0
cpptools|ms-|1.9.1
vetur|oct|0.35.0
vs-code-prettier-eslint|rve|4.1.0
autoimport|ste|1.5.4
sass-indented|syl|1.8.19
cmake|twx|0.0.17
highlight-matching-tag|vin|0.10.1
vue|Wsc|1.0.26
vue-language-features|znc|0.9.7

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vsbas813:30436447
vscscmwlcmt:30428973
azactmsal:30432848
vscgsvidc:30433759
cppdebug:30437091
dockersurvey3:30438168
pynewfile477:30443519
vsnot107cf:30443615

```

</details>

**Comment by ahules** [comment]
How i can provide you required info?

**Comment by mjbvz** [comment]
Please fill  issue template with steps to reproduce the problem so we can investigate it
