### ISSUE TITLE
The VS Code remote Server failed to start

### ISSUE THREAD

**Issue by hhbaieb** [microsoft/vscode#144374]
When updating VSCode to 1.65.0 version, the remote server can never start : 

Version: 1.65.0 (system setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

The issue persist after removing the directory ~/.vscode-server from remote host.

Remote OS :
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

Vscode logs :
[09:19:22.001] > 7f3511b98b81: running
> 
[09:19:23.040] > Acquiring lock on ~/.vscode-server/bin/b5205cc8eb4fbaa726835538cd823
> 72cc0222d43/vscode-remote-lock.hhbaieb.b5205cc8eb4fbaa726835538cd82372cc0222d43 
> 
[09:19:24.000] > Found existing installation at ~/.vscode-server/bin/b5205cc8eb4fbaa7
> 26835538cd82372cc0222d43...
> Checking ~/.vscode-server/.b5205cc8eb4fbaa726835538cd82372cc0222d43.
> log and ~/.vscode-server/.b5205cc8eb4fbaa726835538cd82372cc0222d43.p
> id for a running server
> Looking for server with pid: 20131
> 
[09:19:24.999] > Starting server with command... ~/.vscode-server/bin/b5205cc8eb4fbaa
> 726835538cd82372cc0222d43/server.sh --start-server --host=127.0.0.1 --enable-rem
> ote-auto-shutdown --port=0    &> "~/.vscode-server/.b5205cc8eb4fbaa7
> 26835538cd82372cc0222d43.log" < /dev/null
> printenv:
>     MANPATH=/opt/quest/man:
>     XDG_SESSION_ID=6643
>     SHELL=/bin/sh
>     SSH_CLIENT=137.202.188.43 50922 22
>     USER=hhbaieb
>     VSCODE_AGENT_FOLDER=~/.vscode-server
>     PATH=/usr/local/bin:/usr/bin
>     MAIL=/var/mail/hhbaieb
>     PWD=~
>     HOME=~
>     SHLVL=2
>     LOGNAME=hhbaieb
>     SSH_CONNECTION=137.202.188.43 50922 10.102.54.214 22
>     XDG_RUNTIME_DIR=/run/user/58144
>     _=/usr/bin/printenv
> Spawned remote server: 22728
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
[09:19:26.010] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
[09:19:27.016] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
[09:19:27.845] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:19:27.871] > 
> Waiting for server log...
> 
[09:19:27.927] > Waiting for server log...
> 
[09:19:27.943] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
[09:19:27.958] > Waiting for server log...
> Waiting for server log...
> 
[09:19:28.018] > Waiting for server log...
> 
[09:19:28.041] > Waiting for server log...
> 
[09:19:28.078] > Waiting for server log...
> 
[09:19:28.137] > Waiting for server log...
> 
[09:19:28.158] > Waiting for server log...
> 
[09:19:28.257] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
[09:19:28.353] > Waiting for server log...
> 
[09:19:28.437] > Waiting for server log...
> Waiting for server log...
[09:19:28.443] > 
> Waiting for server log...
> Waiting for server log...
> 
[09:19:28.484] > Waiting for server log...
> 
[09:19:28.493] > Waiting for server log...
> 
[09:19:28.538] > Waiting for server log...
> 
[09:19:28.555] > Waiting for server log...
> 
[09:19:28.589] > Waiting for server log...
> 
[09:19:28.625] > Waiting for server log...
> 
[09:19:28.667] > Waiting for server log...
> 
[09:19:28.727] > Waiting for server log...
> 
[09:19:28.761] > Waiting for server log...
> 
[09:19:28.773] > Waiting for server log...
> 
[09:19:28.811] > Waiting for server log...
> 
[09:19:28.829] > Waiting for server log...
> 
[09:19:28.877] > Waiting for server log...
> 
[09:19:28.911] > Waiting for server log...
> 
[09:19:28.918] > Waiting for server log...
> 
[09:19:28.995] > Waiting for server log...
> 
[09:19:29.024] > Waiting for server log...
> 
[09:19:29.045] > Waiting for server log...
> 
[09:19:29.078] > Waiting for server log...
> 
[09:19:29.090] > Waiting for server log...
> 
[09:19:29.150] > Waiting for server log...
> 
[09:19:29.156] > Waiting for server log...
> 
[09:19:29.248] > Waiting for server log...
> 
[09:19:29.281] > Waiting for server log...
> 
[09:19:29.339] > Waiting for server log...
> Waiting for server log...
> 
[09:19:29.381] > Waiting for server log...
> 
[09:19:29.394] > Waiting for server log...
> 
[09:19:29.441] > Waiting for server log...
> Waiting for server log...
[09:19:29.500] > 
> 
[09:19:29.505] > Waiting for server log...
> 
[09:19:29.570] > Waiting for server log...
> 
[09:19:29.573] > Waiting for server log...
> 
[09:19:29.577] > Waiting for server log...
> 
[09:19:29.635] > Waiting for server log...
> Waiting for server log...
[09:19:29.641] > 
> 
[09:19:29.674] > Waiting for server log...
> 
[09:19:29.707] > Waiting for server log...
> 
[09:19:29.739] > Waiting for server log...
> 
[09:19:29.775] > Waiting for server log...
> 
[09:19:29.804] > Waiting for server log...
> 
[09:19:29.833] > Waiting for server log...
> 
[09:19:29.874] > Waiting for server log...
> 
[09:19:29.912] > Waiting for server log...
> 
[09:19:29.939] > Waiting for server log...
> 
[09:19:29.972] > Waiting for server log...
> 
[09:19:30.008] > Waiting for server log...
> 
[09:19:30.037] > Waiting for server log...
> 
[09:19:30.091] > Waiting for server log...
> 
[09:19:30.106] > Waiting for server log...
> 
[09:19:30.137] > Waiting for server log...
> 
[09:19:30.180] > Waiting for server log...
> 
[09:19:30.204] > Waiting for server log...
> 
[09:19:30.240] > Waiting for server log...
> 
[09:19:30.277] > Waiting for server log...
> 
[09:19:30.304] > Waiting for server log...
> 
[09:19:30.374] > Waiting for server log...
> 
[09:19:30.388] > Waiting for server log...
> 
[09:19:30.421] > Waiting for server log...
> 
[09:19:30.450] > Waiting for server log...
> 
[09:19:30.477] > Waiting for server log...
> 
[09:19:30.511] > Waiting for server log...
> 
[09:19:30.558] > Waiting for server log...
> 
[09:19:30.587] > Waiting for server log...
> 
[09:19:30.615] > Waiting for server log...
> 
[09:19:30.653] > Waiting for server log...
> 
[09:19:30.684] > Waiting for server log...
> 
[09:19:30.719] > Waiting for server log...
> 
[09:19:30.750] > Waiting for server log...
> 
[09:19:30.785] > Waiting for server log...
> 
[09:19:30.823] > Waiting for server log...
> 
[09:19:30.851] > Waiting for server log...
> 
[09:19:30.888] > Waiting for server log...
> 
[09:19:30.924] > Waiting for server log...
> 
[09:19:30.944] > Waiting for server log...
> 
[09:19:30.983] > Waiting for server log...
> 
[09:19:31.013] > Waiting for server log...
> 
[09:19:31.053] > Waiting for server log...
> 
[09:19:31.089] > Waiting for server log...
> 
[09:19:31.119] > Waiting for server log...
> 
[09:19:31.158] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
[09:19:31.171] > 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> 
[09:19:31.205] > Server did not start successfully. Full server log at ~/.vscode-serv
> er/.b5205cc8eb4fbaa726835538cd82372cc0222d43.log >>>
> server.sh is being replaced by 'bin/code-server'. Please migrate to the new comm
> and and adopt the following new default behaviors:
> * connection token is mandatory unless --without-connection-token is used       
> * host defaults to `localhost`
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> atement).
> *
> To accept the license terms, start the server with --accept-server-license-terms
> 
> <<< End of server log
> 
[09:19:31.223] > 7f3511b98b81: start
> exitCode==32==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/58144==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7109==
> 7f3511b98b81: end
> 
[09:19:31.225] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/58144==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7109==

[09:19:31.228] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:431037)
	at d (c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:425272)
	at Object.t.handleInstallOutput (c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:428349)
	at Object.t.tryInstall (c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:524958)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:487817
	at async Object.t.withShowDetailsEvent (c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:491162)
	at async Object.t.resolve (c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:488896)
	at async c:\Users\hhbaieb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.71.2021121615\out\extension.js:1:565038
[09:19:31.236] ------

[09:19:33.125] "install" terminal command done
[09:19:33.125] Install terminal quit with output:

**Comment by shampoonator** [comment]
Got the same issue with ubuntu as a remote server.

**Comment by pierrelouisbescond** [comment]
Probably a similar issue on my side: "Installing VS Code server on xxxxx" fails after numerous retries

**Comment by shampoonator** [comment]
After downgrading to 1.64.2 it works again.

**Comment by pierrelouisbescond** [comment]
> After downgrading to 1.64.2 it works again.

Some of my team members are still in 1.64 and do not experience any issue so I'll think I will downgrade. However, this issue still needs to be fixed.

**Comment by MangelFdz** [comment]
Same problem here... after downgrading to 1.64.2 the connection works again

**Comment by pierrelouisbescond** [comment]
1.64.2 version did solve the issue

**Comment by shawnye1994** [comment]
Got the same issue. Local OS: mac os Monterey, Remote OS: Fedora 28.
Downgrading to 1.64.2 solves the problem.

**Comment by codingcampbell** [comment]
Hi all, can confirm I have the same issue on 1.65.0. I have a workaround for you in case you cannot downgrade.

For me, adding the `--accept-server-license-terms` flag to the final line of `~/.vscode-server/{HASH}server.sh` fixed it. Like so:

```
"$ROOT/node" ${INSPECT:-} "$ROOT/out/server-main.js" --compatibility=1.63 --accept-server-license-terms "$@" 
```

For me {HASH} is `b5205cc8eb4fbaa726835538cd82372cc0222d43` - if you're not sure, check your log or just remove all folders and let it generate a single one again in ~/.vscode-server/bin

**Comment by codingcampbell** [comment]
Good call, I forget this feature is an extension. I was on 0.70. The new 0.76.1 version works fine without having to change the remote scripts

**Comment by shampoonator** [comment]
Thx @aeschli. Updating the extensions helps.. I updated to the newest version from 0.65.1?? Now it works out of the box. 
I deactivated auto updates some time ago, because I had some issues with some extension (can't remember which)

**Comment by hhbaieb** [comment]
I deactivated extensions auto updates a wile ago, because I had some issues with C/C++ IntelliSense.
Remote-SSH extension was 0.71.0. The new 0.76.1 version works well.

**Comment by dersnek** [comment]
> Hi all, can confirm I have the same issue on 1.65.0. I have a workaround for you in case you cannot downgrade.
> 
> For me, adding the `--accept-server-license-terms` flag to the final line of `~/.vscode-server/{HASH}server.sh` fixed it. Like so:
> 
> ```
> "$ROOT/node" ${INSPECT:-} "$ROOT/out/server-main.js" --compatibility=1.63 --accept-server-license-terms "$@" 
> ```
> 
> For me {HASH} is `b5205cc8eb4fbaa726835538cd82372cc0222d43` - if you're not sure, check your log or just remove all folders and let it generate a single one again in ~/.vscode-server/bin

this issue just happened for me on 1.65.2 and this solution helped.

**Comment by bilalghanem** [comment]
I have the same problem in 1.66, but I can't find this file `~/.vscode-server/{HASH}server.sh`.

**Comment by tanhakabir** [comment]
@bilalghanem could you file a separate issue with your logs?

**Comment by frboyer** [comment]
I had to update both "Remote - SSH" and "Remote - WSL" extensions to correct the issue.

**Comment by onionhead0708** [comment]
> For me, adding the --accept-server-license-terms flag to the final line of ~/.vscode-server/{HASH}server.sh fixed it. 

I have the same problem and did what dersnek commented and resolved the issue.
to be precise, the file is "server.sh" which under the ~/.vscode-server/{HASH} folder
