### ISSUE TITLE
TS Server fatal error:  Cannot read property 'getSourceFiles' of undefined

### ISSUE THREAD

**Issue by GeekyMonkey** [microsoft/vscode#144307]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.5

**Steps to reproduce crash**
1. Open a bunch of .ts files
2. Become dismayed at the error popup
3. Cry into my coffee

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'getSourceFiles' of undefined
    at ConfiguredProject.Project.getScriptInfos (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164786:44)
    at ProjectService.sendProjectTelemetry (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167607:66)
    at ConfiguredProject.updateGraph (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165961:37)
    at updateProjectIfDirty (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166446:45)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168769:29)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169104:97
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169104:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170262:46)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172195:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172186:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172195:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172221:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174826:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.40GB free)|
|Process Argv|--crash-reporter-id 59e642ff-fb1f-4bbf-a95e-41c62fb297d9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.35.0
vscode-fake-virtual-space|Ant|0.1.3
npm-intellisense|chr|1.4.1
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.0.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
gitkraken-authentication|git|1.0.3
cloudcode|goo|1.17.0
svgeditor|hen|2.9.0
npm|ide|0.5.4
volar|joh|0.32.1
vscode-fix-checksums|leh|1.1.0
json-to-ts|Mar|1.7.5
git-graph|mhu|1.30.0
sort-typescript-imports|mic|1.4.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
vscode-edge-devtools|ms-|1.4.5
vscode-kubernetes-tools|ms-|1.3.6
remote-containers|ms-|0.224.2
remote-wsl|ms-|0.64.2
azurecli|ms-|0.5.0
powershell|ms-|2021.12.0
vs-keybindings|ms-|0.2.1
debugger-for-chrome|msj|4.13.0
indent-rainbow|ode|8.2.2
vscode-versionlens|pfl|1.0.9
vscode-thunder-client|ran|1.12.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
synthwave-vscode|Rob|0.1.11
scss-style-tag|sis|0.1.0
code-spell-checker|str|2.1.7
code-spell-checker-medical-terms|str|1.0.14
sass-indented|syl|1.8.19
vscodeintellicode|Vis|1.2.17
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
vue-language-features|znc|0.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaac:30438847
vsnot107:30443614

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
