### ISSUE TITLE
Can no longer scroll in the overview ruler of the diff editor

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#144584]
Scrolling by moving the scrollbox no longer works as shown below

![image](https://user-images.githubusercontent.com/172399/157035029-1422d5aa-4d93-4d5e-a45d-00ae2e40b871.png)

**Comment by alexdima** [comment]
@egamma I'm having trouble reproducing, does this happen all the time for you or only after certain steps?

**Comment by alexdima** [comment]
Here are some stacks I got from @jrieken 

```
bootstrap-window.js:251 [uncaught exception]: NotFoundError: Failed to execute 'setPointerCapture' on 'Element': No active pointer with the given id is found.
onUnexpectedError @ bootstrap-window.js:251
(anonymous) @ bootstrap-window.js:52
emit @ node:events:390
window.onerror @ node:electron/js2c/renderer_init:73
platform_1.globals.onerror @ errorTelemetry.ts:20
bootstrap-window.js:254 Error: Failed to execute 'setPointerCapture' on 'Element': No active pointer with the given id is found.
    at GlobalPointerMoveMonitor.startMonitoring (globalPointerMoveMonitor.ts:87:18)
    at GlobalEditorPointerMoveMonitor.startMonitoring (editorDom.ts:268:34)
    at MouseDownOperation.start (mouseHandler.ts:426:27)
    at TouchHandler._onMouseDown (mouseHandler.ts:268:29)
    at mouseHandler.ts:118:83
    at HTMLDivElement.<anonymous> (editorDom.ts:169:4)
onUnexpectedError @ bootstrap-window.js:254
(anonymous) @ bootstrap-window.js:52
emit @ node:events:390
window.onerror @ node:electron/js2c/renderer_init:73
platform_1.globals.onerror @ errorTelemetry.ts:20
globalPointerMoveMonitor.ts:87 Uncaught DOMException: Failed to execute 'setPointerCapture' on 'Element': No active pointer with the given id is found.
    at GlobalPointerMoveMonitor.startMonitoring (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/globalPointerMoveMonitor.js:55:28)
    at GlobalEditorPointerMoveMonitor.startMonitoring (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/browser/editorDom.js:193:44)
    at MouseDownOperation.start (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:290:40)
    at TouchHandler._onMouseDown (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:176:42)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:50:93
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/browser/editorDom.js:121:17)
```

**Comment by bpasero** [comment]
Also our top stack from error telemetry in insiders:

<img width="1565" alt="image" src="https://user-images.githubusercontent.com/900690/159165500-c906b6a7-d71e-4d02-ab3f-3aabe90cf1a2.png">

**Comment by alexdima** [comment]
Verified via https://github.com/microsoft/vscode/issues/145613#issuecomment-1076486155
