### ISSUE TITLE
set VSCODE_DEV is not 1, code-server.sh will broken by spdlog

### ISSUE THREAD

**Issue by godkite** [microsoft/vscode#144657]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: macos 10.15.7

I want ot run vscode web with server in my local mahine:

Steps to Reproduce:

1. modify `vscode/scripts/code-server.sh:25`, set `VSCODE_DEV=1 \` to `VSCODE_DEV='' \` or delete this line
2. on bash, run `./scripts/code-server.sh`, will get below error 
3. if do not modify `vscode/scripts/code-server.sh:25`, start is ok

```shell
Starting server: /Users/kite/work/code/vscode/out/server-main.js --connection-token 3272015600 --host localhost --port 9888
Server bound to 127.0.0.1:9888 (IPv4)
Extension host agent listening on 9888

Error: Module did not self-register: '/Users/kite/work/code/vscode/node_modules/spdlog/build/Release/spdlog.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/Users/kite/work/code/vscode/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/kite/work/code/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (/Users/kite/work/code/vscode/out/vs/loader.js:1071:24)
    at NodeScriptLoader.load (/Users/kite/work/code/vscode/out/vs/loader.js:865:39)
    at OnlyOnceScriptLoader.load (/Users/kite/work/code/vscode/out/vs/loader.js:619:32)
    at loadNextPath (/Users/kite/work/code/vscode/out/vs/loader.js:1677:41)
    at Object.errorback (/Users/kite/work/code/vscode/out/vs/loader.js:1685:25)
    at OnlyOnceScriptLoader.triggerErrorback (/Users/kite/work/code/vscode/out/vs/loader.js:632:36)
    at /Users/kite/work/code/vscode/out/vs/loader.js:619:151
    at NodeScriptLoader.load (/Users/kite/work/code/vscode/out/vs/loader.js:868:21)
    at OnlyOnceScriptLoader.load (/Users/kite/work/code/vscode/out/vs/loader.js:619:32)
    at loadNextPath (/Users/kite/work/code/vscode/out/vs/loader.js:1677:41)
    at ModuleManager._loadModule (/Users/kite/work/code/vscode/out/vs/loader.js:1689:13)
    at ModuleManager._resolve (/Users/kite/work/code/vscode/out/vs/loader.js:1774:26)
    at ModuleManager.defineModule (/Users/kite/work/code/vscode/out/vs/loader.js:1421:18)
    at ModuleManager._relativeRequire (/Users/kite/work/code/vscode/out/vs/loader.js:1455:18)
    at result (/Users/kite/work/code/vscode/out/vs/loader.js:1629:30)
    at _spdlog (/Users/kite/work/code/vscode/out/vs/platform/log/node/spdlogLog.js:12:74)
    at new Promise (<anonymous>)
    at createSpdLogLogger (/Users/kite/work/code/vscode/out/vs/platform/log/node/spdlogLog.js:12:35)
    at SpdLogLogger._createSpdLogLogger (/Users/kite/work/code/vscode/out/vs/platform/log/node/spdlogLog.js:63:34)
    at new SpdLogLogger (/Users/kite/work/code/vscode/out/vs/platform/log/node/spdlogLog.js:53:48)
    at setupServerServices (/Users/kite/work/code/vscode/out/vs/server/node/serverServices.js:18:46)
    at createServer (/Users/kite/work/code/vscode/out/vs/server/node/remoteExtensionHostAgentServer.js:534:103)
    at async Server.<anonymous> (/Users/kite/work/code/vscode/out/server-main.js:144:3) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous2===' ]
}
Web UI available at http://localhost:9888/?tkn=3272015600
[17:16:39] Extension host agent started.
```

**Comment by tanhakabir** [comment]
Why are you setting the `VSCODE_DEV` variable manually?

**Comment by godkite** [comment]
> Why are you setting the `VSCODE_DEV` variable manually?

Because I want to run vscode-web on production env. When`VSCODE_DEV=1`, some config will be add '-dev', like `.vscode-server-oss-dev` `.vscode-oss-dev`.

So what else can I do?

**Comment by aeschli** [comment]
You can customize that folder with `--server-data-dir`. Or as you are running from sources, change it in the source code :-)
When running from sources, `VSCODE_DEV=1` needs to be set for finding the node modules matching the remote.

**Comment by aeschli** [comment]
What's wrong with `workbench-dev.html` ? It (should be) the same as `workbench.html` except for a different way of loading resources.
