### ISSUE TITLE
Error: ILayoutService.container is not available in the standalone editor!

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#144649]
The [GH CI build](https://github.com/microsoft/vscode/runs/5461077400?check_suite_focus=true) fails with the error:
```
Error: ILayoutService.container is not available in the standalone editor!
    at StandaloneLayoutService.get container [as container] (http://127.0.0.1:8562/out/vs/editor/standalone/browser/standaloneLayoutService.js:3[9](https://github.com/microsoft/monaco-editor/runs/5460618985?check_suite_focus=true#step:18:9):15)
    at updateRootClasses (http://127.0.0.1:8562/out/vs/platform/accessibility/browser/accessibilityService.js:58:33)
    at AccessibilityService.initReducedMotionListeners (http://127.0.0.1:8562/out/vs/platform/accessibility/browser/accessibilityService.js:61:9)
    at new AccessibilityService (http://127.0.0.1:8562/out/vs/platform/accessibility/browser/accessibilityService.js:47:14)
    at InstantiationService._createInstance (http://127.0.0.1:8562/out/vs/platform/instantiation/common/instantiationService.js:92:16)
    at InstantiationService._createServiceInstance (http://127.0.0.1:8562/out/vs/platform/instantiation/common/instantiationService.js:199:25)
    at InstantiationService._createServiceInstanceWithOwner (http://127.0.0.1:8562/out/vs/platform/instantiation/common/instantiationService.js:187:25)
    at InstantiationService._createAndCacheServiceInstance (http://127.0.0.1:8562/out/vs/platform/instantiation/common/instantiationService.js:177:43)
    at InstantiationService._safeCreateAndCacheServiceInstance (http://127.0.0.1:8562/out/vs/platform/instantiation/common/instantiationService.js:130:25)
    at InstantiationService._getOrCreateServiceInstance (http://127.0.0.1:8562/out/vs/platform/instantiation/common/instantiationService.js:[11](https://github.com/microsoft/monaco-editor/runs/5460618985?check_suite_focus=true#step:18:11)7:25)
```

This is because `ILayoutService.container` is not available in the standalone editor. The backstory is that, unfortunately, there has been a design decision to introduce the concept of a single container to our code base, but that is an invalid assumption for the standalone editor. In the standalone editor case, there can be multiple editors instantiated on a page, and therefore there are multiple containers in that case, which can mutate as editors are instantiated / disposed.

**Comment by alexdima** [comment]
@JacksonKearl I've pushed a change to unblock things.

**Comment by JacksonKearl** [comment]
Thank you for that fix!
