### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by nonameolsson** [microsoft/vscode#144815]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_2 (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169001:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169009:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170675:26)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170949:97
    at Object.flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170949:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172108:46)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174044:88
    at IpcIOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174035:28)
    at IpcIOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174044:33)
    at IpcIOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174070:35)
    at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176705:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

VS Code version: Code - Insiders 1.66.0-insider (Universal) (f407da25ec62fc82d8f038eb4ae0df1fe8ff246a, 2022-03-10T05:16:49.675Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 11, 9|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 372b0727-6a9f-4b74-9883-aa3b3859e937|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.3.4
snaz|aka|2.0.2
project-manager|ale|12.5.0
find-related|eam|0.9.0
tailwind-docs|aus|1.4.0
docs-view|bie|0.0.9
vscode-tailwindcss|bra|0.7.7
npm-intellisense|chr|1.4.1
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
codestream|Cod|12.12.0
gitignore|cod|0.7.0
simple-icons|com|0.1.1
vscode-github-actions|csc|0.22.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.3
prettier-vscode|esb|9.3.0
vscode-todo-plus|fab|4.18.4
vscode-jest-runner|fir|0.4.48
vscode-monorepo-workspace|fol|1.3.1
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
codespaces|Git|1.5.5
copilot|Git|1.7.5250
remotehub|Git|0.26.0
vscode-pull-request-github|Git|0.38.0
gitkraken-authentication|git|1.0.3
go|gol|0.32.0
vscode-test-explorer|hbe|2.21.1
stylelint-plus|hex|0.56.6
iridium-database|ide|0.4.1
npm|ide|0.5.4
search-node-modules|jas|1.3.0
svg|joc|1.4.17
vscode-jest-test-adapter|kav|0.8.1
devtoys|kej|1.5.0
tailwindcss-intellisense-twin|lig|0.12.2
i18n-ally|lok|2.8.1
scratchpad|mac|0.0.3
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
vscode-edge-devtools|ms-|1.4.5
remote-containers|ms-|0.226.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
live-server|ms-|0.2.12
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
sqltools-driver-mssql|mtx|0.2.0
color-highlight|nau|2.5.0
angular-console|nrw|17.14.1
material-icon-theme|PKi|4.14.1
vscode-thunder-client|ran|1.12.5
vscode-yaml|red|1.5.1
vscode-sort-json|ric|1.20.0
vscode-quick-open-related-files|sch|1.0.0
mdx|sil|0.1.0
snyk-vulnerability-scanner|sny|1.2.8
vscode-vuln-cost|sny|1.7.1
vscode-styled-components|sty|1.7.3
vscode-stylelint|sty|1.2.2
ayu|tea|1.0.5
io|Tru|0.2.1
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0
quokka-vscode|Wal|1.0.450
browserslist|web|1.1.0
vscode-webhint|web|1.6.5
vscode-jumpy|wma|0.3.1
tailwind-snippets|Zar|1.0.1
vscode-open-in-github|ziy|1.3.6

(14 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvsnew555:30438690
vsbas813:30436447
vscscmwlcmc:30428972
vscgsvid1:30433757
dockersurvey3cf:30438169
pynewfile477cf:30443520

```

</details>

**Comment by mjbvz** [comment]
Please share steps to reproduce this issue or a project that triggers it

/needsMoreInfo
