### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by lampofaladdin** [microsoft/vscode#144887]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_2 (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:169001:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:169009:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:170675:26)
    at /home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:170949:97
    at Object.flatMap (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:170949:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:172108:46)
    at /home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:174044:88
    at IpcIOSession.Session.executeWithRequestId (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:174035:28)
    at IpcIOSession.Session.executeCommand (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:174044:33)
    at IpcIOSession.Session.onMessage (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:174070:35)
    at process.<anonymous> (/home/aladdin/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/extensions/node_modules/typescript/lib/tsserver.js:176705:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (36.29GB free)|
|Process Argv|--crash-reporter-id 73fda03a-3a2c-4831-91b0-b4718e7c5a72|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3792)|
|Memory (System)|50.15GB (40.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3792)|
|Memory (System)|50.15GB (40.34GB free)|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
gitkraken-authentication|git|1.0.3
vscode-language-pack-zh-hans|MS-|1.65.2
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
debugger-for-chrome|msj|4.13.0
vscode-icons|vsc|11.10.0
material-theme|zhu|3.13.20
vscode-intelephense-client|bme|1.8.2
vscode-tailwindcss|bra|0.7.7
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|12.0.3
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
vscode-jest-runner|fir|0.4.48
gitkraken-authentication|git|1.0.3
go|gol|0.32.0
jenkinsfile-support|ivo|1.1.0
svg|joc|1.4.17
umijs-plugin-model|lit|0.0.5
json-to-ts|Mar|1.7.5
rust-analyzer|mat|0.2.964
vscode-docker|ms-|1.20.0
vscode-language-pack-zh-hans|MS-|1.65.2
vscode-js-profile-flame|ms-|1.0.0
angular-console|nrw|17.14.1
vetur|oct|0.35.0
any-rule|rus|0.3.13
rust|rus|0.7.8
sass-indented|syl|1.8.19
vscode-counter|uct|3.0.3
vscode-lldb|vad|1.6.10
change-case|wma|1.0.0
php-debug|xde|1.25.0
php-pack|xde|1.0.3
markdown-all-in-one|yzh|3.4.0
php-intellisense|zob|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvsnew555:30450902
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
pynewfile477cf:30450039

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
