### ISSUE TITLE
VSCode for web freezes, then crashes (refreshes the page) shortly after opening or creating a file

### ISSUE THREAD

**Issue by Windzyboy** [microsoft/vscode#144848]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.65.1, Commit `8908a9ca0f221f36507231afb39d2d8d1e182702`
- OS Version: ChromeOS Version 101.0.4918.0 (Official Build) dev (64-bit)
  - Modified Chrome(OS) Flags
    - `#temporary-unexpire-flags-m100` = Enabled
    - `#enable-reader-mode` = Enabled in Settings
    - `#enable-gpu-rasterization` = Enabled
    - `#dark-light-mode` = Enabled
    - `#crostini-gpu-support` = Enabled
    - `#productivity-launcher` = Enabled
    - `#productivity-reorder-apps` = Enabled
    - `#enable-lens-region-search` = Disabled
    - `#enable-holding-space-in-progress-downloads-integration` = Enabled

Steps to Reproduce:

*skip steps 1-5 if you have an instance of VSCode web without any data*

1. Navigate to vscode.dev and prepare the "clear site data" menu in a different tab/window
3. Close the vscode.dev tab/window
4. Refresh the "clear site data" menu and clear the data
5. Again navigate to vscode.dev
6. Close the "Anytime, anywhere" widget at the top of the viewport
7. Select "Open File" in the "Get Started" tab (in VSCode)
9. Select and open any file in the file browser (tested with .svg and .json)
10. Issue occurs.

The issue can also be triggered by skipping steps 7-9 and creating a new file.

I can't use VSCode anymore, and I need to for my projects both for personal and organizational use.

**Comment by Windzyboy** [comment]
Update 2: Restarting my computer and clearing data no longer fixes the issue. Here's the browser log:
```
Access to fetch at 'https://vscodeweb.azureedge.net/stable/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/vs/loader.js' from origin 'https://vscode.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
sw.js:1                  Uncaught (in promise) TypeError: Failed to fetch
    at sw.js:1:2385
    at Generator.next (<anonymous>)
    at i (sw.js:1:148)
(anonymous) @ sw.js:1
i @ sw.js:1
​ Cross-Origin Read Blocking (CORB) blocked cross-origin response https://vortex.data.microsoft.com/collect/v1 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
u @ applicationinsights-web.min.js:5
c.triggerSend @ applicationinsights-web.min.js:5
c.onunloadFlush @ applicationinsights-web.min.js:5
i @ applicationinsights-web.min.js:5
(anonymous) @ applicationinsights-web.min.js:5
ve @ applicationinsights-web.min.js:5
(anonymous) @ applicationinsights-web.min.js:5
ve @ applicationinsights-web.min.js:5
vs.onunloadFlush @ applicationinsights-web.min.js:5
t @ applicationinsights-web.min.js:5
Navigated to https://vscode.dev/
```

**Comment by Windzyboy** [comment]
Update again: Restarting my computer fixed it again. It's happened too many times to pass off now, and I can't pinpoint the cause.
