### ISSUE TITLE
Terminal does not load when multiple folders open in the workspace

### ISSUE THREAD

**Issue by davidmnoriega** [microsoft/vscode#145168]
Issue Type: <b>Bug</b>

I'm using vscode with wsl2, when I have a workspace that has more than one folder, I am unable to open a terminal. No errors, just an empty panel. Closing out the additional folders until there is one, then the terminal loads. Attempting to spawn an additional terminal with "+" does not work, same behavior 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.64GB free)|
|Process Argv|--crash-reporter-id 2c833a45-a7cd-4fb4-a5f0-d73c3424a0c5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (6 x 2712)|
|Memory (System)|19.55GB (18.28GB free)|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
rewrap|stk|1.16.3
vscode-icons|vsc|11.10.0
gitlens|eam|12.0.4
gc-excelviewer|Gra|4.2.53
vscode-kubernetes-tools|ms-|1.3.7
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
ansible|red|0.8.1
fabric8-analytics|red|0.3.5
java|red|1.4.0
vscode-commons|red|0.0.6
vscode-xml|red|0.19.1
vscode-yaml|red|1.5.1
code-spell-checker|str|2.1.7
shellcheck|tim|0.18.9
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.0
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
cppdebug:30451566
pynewfile477:30450038

```

</details>

**Comment by meganrogge** [comment]
Can you reproduce this in insiders? I've been working in a multi repo workspace in insiders all day and have had no issues with terminals

**Comment by davidmnoriega** [comment]
My current vscode:
![image](https://user-images.githubusercontent.com/1319376/158885298-1af01e7b-8d7c-4eb8-8296-4ee33d0a7fb2.png)

A fresh insiders install with the remote wsl extension installed
![image](https://user-images.githubusercontent.com/1319376/158885861-01a3ca95-e3d3-4b49-bb0d-ee7171045681.png)

Version: 1.66.0-insider (user setup)
Commit: db0525ff4ba814780e901a5b9e399aaf596b9b20
Date: 2022-03-17T05:16:00.499Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

<details>
<summary>System Info</summary>
CPUs | Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.73GB (17.33GB free)
Process Argv |  
Screen Reader | no
VM | 0%
</details><details><summary>Extensions (31)</summary>
Extension | Author (truncated) | Version
-- | -- | --
remote-wsl | ms-
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vscscmwlcmc:30428972
vscgsvid2:30433758
dockersurvey3cf:30438169
vscaac:30438845
pynewfile477:30451556
```

</details>

**Comment by meganrogge** [comment]
Thanks for the images.


Can you share your settings.json?

**Comment by davidmnoriega** [comment]
<details>
<summary>Remote wsl settings</summary>

```json
{
    "ansible.python.interpreterPath": "/home/dnoriega/.virtualenvs/ansible/bin/python",
    "java.completion.favoriteStaticMembers": [

        "org.junit.Assert.*",
        "org.junit.Assume.*",
        "org.junit.jupiter.api.Assertions.*",
        "org.junit.jupiter.api.Assumptions.*",
        "org.junit.jupiter.api.DynamicContainer.*",
        "org.junit.jupiter.api.DynamicTest.*",
        "org.mockito.Mockito.*",
        "org.mockito.ArgumentMatchers.*",
        "org.mockito.Answers.*"
    ],
    "metals.javaHome": "/usr/lib/jvm/java-8-openjdk-amd64",
    "java.configuration.runtimes": [        
        {
            "name": "JavaSE-1.8",
            "path": "/usr/lib/jvm/java-8-openjdk-amd64",
            
        },
        {
            "name": "JavaSE-11",
            "path": "/usr/lib/jvm/java-11-openjdk-amd64",
            "default": true
        }
    ],
    "maven.terminal.customEnv": [
        {
            "environmentVariable": "JAVA_HOME",
            "value": "/usr/lib/jvm/java-11-openjdk-amd64"
        }
    ],
    "maven.executable.options": "-B -T8 -Dmaven.artifact.threads=50 -DskipTests -Dmaven.clover.skip=true",
    "maven.view": "hierarchical",
    "python.defaultInterpreterPath": "/bin/python3",
}
```

</details>

<details>
<summary>Windows settings</summary>

```json
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.minimap.enabled": false,
    "workbench.iconTheme": "vscode-icons",
    "editor.tabSize": 2,
    "editor.rulers": [80,120],
    "[markdown]": {
        "rewrap.autoWrap.enabled": true
    },
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "github-enterprise.uri": "https://x.x.x.x",
    "ansible.ansible.useFullyQualifiedCollectionNames": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "redhat.telemetry.enabled": true,
    "java.configuration.runtimes": [

    ],
    "files.watcherExclude": {
        "**/.bloop": true,
        "**/.metals": true,
        "**/.ammonite": true
    },
    "remote.SSH.remotePlatform": {
        "db52.dev.ut1.omniture.com": "linux"
    },
    "vs-kubernetes": {
        "vscode-kubernetes.helm-path.windows": "C:\\Users\\dnoriega\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vscode-kubernetes.minikube-path.windows": "C:\\Users\\dnoriega\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe"
    },
    "editor.fontFamily": "Source Code Pro, Consolas, 'Courier New', monospace",
    "markdown.preview.fontFamily": "Source Code Pro, -apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', system-ui, 'Ubuntu', 'Droid Sans', sans-serif",
    "gitlens.hovers.currentLine.over": "line",
    "files.autoSave": "afterDelay",
    "files.associations": {
        "*.yml": "ansible"
    },
    "terraform-ls.terraformExecPath": "C:\\Users\\dnoriega\\terraform.exe",
    "git.allowForcePush": true,
    "git.confirmSync": false,
    "cSpell.enabled": true,
    "cSpell.enableFiletypes": [
        "shellscript"
    ],
    "files.trimTrailingWhitespace": true,
    "gitlens.blame.ignoreWhitespace": true,
}
```

</details>

**Comment by davidmnoriega** [comment]
<details>
<summary>dev tools console</summary>

```
log.ts:301  INFO Invoking resolveAuthority(wsl)
log.ts:301  INFO resolveAuthority(wsl) returned '127.0.0.1:59839' after 1430 ms
abstractExtensionService.ts:938 [redhat.vscode-commons]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:938
abstractExtensionService.ts:938 [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:938
abstractExtensionService.ts:938 [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:938
abstractExtensionService.ts:938 [vscjava.vscode-maven]: Cannot register 'maven.executable.path'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:938
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.windows as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.windows as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.windows as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.mac as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.mac as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.mac as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.linux as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.linux as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.linux as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.windows as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.windows as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.windows as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.mac as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.mac as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.mac as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.linux as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.linux as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.linux as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.windows as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.windows as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.windows as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.mac as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.mac as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.mac as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.linux as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.linux as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.linux as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/dnoriega/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu-20.04/home/dnoriega/.vscode-server/extensions/redhat.vscode-yaml-1.5.1/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
log.ts:307  WARN No search provider registered for scheme: vscode-remote, waiting
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.windows as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.windows as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.windows as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.mac as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.mac as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.mac as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.linux as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.linux as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.linux as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.windows as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.windows as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.windows as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.mac as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.mac as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.mac as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.linux as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.linux as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.linux as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.windows as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.windows as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.windows as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.mac as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.mac as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.mac as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.kubectl-path.linux as vscode-kubernetes.kubectl-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.helm-path.linux as vscode-kubernetes.helm-path is ""
(anonymous) @ configurationModels.ts:246
configurationModels.ts:246 Conflict in default settings: Ignoring vscode-kubernetes.minikube-path.linux as vscode-kubernetes.minikube-path is ""
(anonymous) @ configurationModels.ts:246
mainThreadExtensionService.ts:107 Activating extension 'vscode-icons-team.vscode-icons' failed: ENOENT: no such file or directory, open 'C:\home\dnoriega\workspace\argo-cd\ui-test\package.json'.
$onExtensionActivationError @ mainThreadExtensionService.ts:107
log.ts:313   ERR [Extension Host] Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
	at k (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:16164)
	at new b (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:16984)
	at new d (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:18632)
	at d.with (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:17678)
	at _a (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:458:28684)
	at Object.isFile (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:458:27990)
	at gw (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:197:320)
	at mA (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:197:1082)
	at ub (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:419:12253)
	at o3 (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:525:8468)
	at c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:524:12810
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
console.ts:137 [Extension Host] Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character	at k (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:16164)	at new b (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:16984)	at new d (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:18632)	at d.with (c:\Users\dnoriega\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:17678)	at _a (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:458:28684)	at Object.isFile (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:458:27990)	at gw (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:197:320)	at mA (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:197:1082)	at ub (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:419:12253)	at o3 (c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:525:8468)	at c:\Users\dnoriega\.vscode\extensions\ms-vscode-remote.remote-containers-0.224.3\dist\extension\extension.js:524:12810	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
I @ console.ts:137
log.ts:313   ERR No terminal backend registered for remote authority 'wsl+ubuntu-20.04': Error: No terminal backend registered for remote authority 'wsl+ubuntu-20.04'
    at R.createProcess (vscode-file://vscode-app/c:/Users/dnoriega/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1922:9923)
    at Ci._createProcess (vscode-file://vscode-app/c:/Users/dnoriega/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2820:5494)
    at vscode-file://vscode-app/c:/Users/dnoriega/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2818:106065
```

</details>

**Comment by Tyriar** [comment]
Can repro, this is the problem:

```
ERR No terminal backend registered for remote authority 'wsl+ubuntu': Error: No terminal backend registered for remote authority 'wsl+ubuntu'
    at R.createProcess (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2098:10040)
    at bi._createProcess (vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2988:5494)
    at vscode-file://vscode-app/c:/Users/Daniel/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2986:106517
```

**Comment by Tyriar** [comment]
This is caused by casing problems:

![image](https://user-images.githubusercontent.com/2193314/160455914-61fc6f70-db47-4614-8e32-6844bed8a47a.png)

**Comment by TylerLeonhardt** [comment]
@Tyriar / @meganrogge any verification steps?

**Comment by meganrogge** [comment]
@TylerLeonhardt open multiple folders in a WSL window. verify that a terminal loads
