### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by Aviortheking** [microsoft/vscode#145216]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.2

**Steps to reproduce crash**
1. launch liveshare
2. launch JS projet
3. Crash the world

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.assignProjectToOpenedScriptInfo (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170674:30)
    at d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170949:97
    at Object.flatMap (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170949:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172108:46)
    at d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174044:88
    at IpcIOSession.Session.executeWithRequestId (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174035:28)
    at IpcIOSession.Session.executeCommand (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174044:33)
    at IpcIOSession.Session.onMessage (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174070:35)
    at process.<anonymous> (d:\Program Files\vscode-insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176705:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.66.0-insider (3e5c7e2c570a729e664253baceaf443b69e82da6, 2022-03-14T05:15:38.097Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.58GB free)|
|Process Argv|--crash-reporter-id 7f49e5f3-3c87-44be-801d-501022db6a44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.4
discord-vscode|icr|5.8.0
fluent-icons|mig|0.0.17
remote-containers|ms-|0.226.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.66.0
vsliveshare|ms-|1.0.5418
code-stats-vscode|riu|1.0.18
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|11.10.0
twig|wha|1.0.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
