### ISSUE TITLE
Cannot read properties of undefined (reading 'dragStartDisposable')

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#145356]
Issue Type: <b>Bug</b>

1. Open settings editor to side
2. Go to `workbench.editorAssociations`
3. Focus a cell in the setting table
4. Close the editor using the keyboard (cmd+w)

**bug**
In the dev tools, I see:
 
```
 ERR Cannot read properties of undefined (reading 'dragStartDisposable'): TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
    at ListView._splice (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:318:22)
    at ListView.splice (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:303:29)
    at vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/listWidget.js:1086:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/event.js:796:23)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/listWidget.js:1086:32)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:929:19)
    at IndexTreeModel._setListNodeCollapseState (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:266:23)
    at IndexTreeModel._setCollapseState (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:237:33)
    at vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:233:63
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/event.js:796:23)
    at IndexTreeModel.setCollapsed (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:233:39)
    at ObjectTreeModel.setCollapsed (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:155:31)
    at TOCTree.collapseAll (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1197:24)
    at SettingsEditor2.triggerSearch (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1000:34)
    at SettingsEditor2.onSearchInputChanged (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:946:24)
    at vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:355:60
    at vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/async.js:276:32
```

VS Code version: Code - Insiders 1.66.0-insider (Universal) (db0525ff4ba814780e901a5b9e399aaf596b9b20, 2022-03-17T05:18:05.656Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rzhao271** [comment]
Reopening because my fix caused a regression. I reverted the fix yesterday.

**Comment by mikelle-rogers** [comment]
I am atatempting .NET Core Attach debugging in C# and there is a popup that looks like this: 
![image](https://user-images.githubusercontent.com/45022607/163459129-4fd0bca1-4100-4a56-9def-5202d38be895.png)
I did some research, tried starting VS Code again, tried it in VS Code Insiders and it still happened.

**Comment by rzhao271** [comment]
@mikelle-rogers that seems like a separate issue. If it has to do with the extension, please file it in that extension's repository. Otherwise, please file a separate issue in VS Code.

**Comment by rzhao271** [comment]
I'm not seeing this error anymore.

**Comment by mjbvz** [comment]
I still see this in the latest insiders. However I also see a different error when clicking on any entries after the first in the table:

```
   ERR ListError [SettingsTree] Invalid index 2: Error: ListError [SettingsTree] Invalid index 2
    at z.setFocus (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:10522)
    at z.setFocus (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:543:66674)
    at H.onViewPointer (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:138:44184)
    at H.onViewPointer (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:543:65127)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:81:23814
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at l.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2266)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:1844)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:81:23462
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at l.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2266)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:1844)
    at HTMLDivElement.I (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:10266)
```
```
workbench.desktop.main.js:603   ERR Cannot read properties of undefined (reading 'dragStartDisposable'): TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
    at g._splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:138:13315)
    at g.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:138:13014)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3:198112
    at Array.forEach (<anonymous>)
    at t.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3:198099)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:8806
    at m.bufferEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:5182)
    at z.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:8773)
    at z.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:543:66267)
    at C._setListNodeCollapseState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:30911)
    at C._setCollapseState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:30416)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:30292
    at m.bufferEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:5182)
    at C.setCollapsed (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:30270)
    at R.setCollapsed (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:39013)
    at g.collapseAll (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:524)
    at Qt.triggerSearch (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2710:85376)
    at Qt.onSearchInputChanged (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2710:83638)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2710:66810
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:13461
```

**Comment by mjbvz** [comment]
Closing as I'm not longer seeing this in the current insiders builds

**Comment by rzhao271** [comment]
I'll reopen the latest error-telemetry issue because there's probably another way to cause the same error.
