### ISSUE TITLE
Today's VS Code Insiders server fails on Darwin

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#145413]
I noticed in the launcher that today's Darwin server has a nested subdirectory, `vscode-server-darwin`. This broke our launcher (I initially assumed we changed something), and after checking I noticed that it also causes remote ssh to fail since the binaries are no longer in the expected locations:

```
local-server-1> ssh child died, shutting down

[10:38:15.018] Failed to parse remote port from server output
[10:38:15.019] Resolver error: Error: 
	at Function.Create (/Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:586041)
	at Object.t.handleInstallOutput (/Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (/Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:625033)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:644070
	at async Object.t.withShowDetailsEvent (/Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:647817)
	at async /Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:623505
	at async b (/Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:623120)
	at async Object.t.resolve (/Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:645427)
	at async /Users/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:722867
```

On the launcher side I can verify that pulling in yesterday's version by adding `?vscode-version=db0525ff4ba814780e901a5b9e399aaf596b9b20` to the vscode.dev URL fixes the issue

**Comment by connor4312** [comment]
Looks like the SSH issue was a separate local problem. Looking at the directories, the contents seem mostly the same structure wise. Not sure why it's extracting differently, since it _does not_ seem to affect remote SSH. Looking into it.

**Comment by connor4312** [comment]
Okay, that was a fun investigation. Yesterday's server's download path was 

```
https://az764295.vo.msecnd.net/insider/db0525ff4ba814780e901a5b9e399aaf596b9b20/vscode-server-darwin.zip
```

But today's was

```
https://az764295.vo.msecnd.net/insider/d572d6e9d1282b352227916cb8f95bb2b03ddcaa/vscode-server-darwin-x64.zip
```

We would only pop off the first segment of the path when unzipping if it matched the zip name. While the zip was renamed, its nested directory was not, and therefore we would end up with an extra segment in the path. I'll change our logic to just always pop off the first segment, though I think having the zip name match any nested directory is pretty standard so I'll leave this open in case this is worth a tweak.

**Comment by tanhakabir** [comment]
Related to https://github.com/microsoft/vscode/pull/145226 and https://github.com/microsoft/vscode-remote-release/issues/4069
