### ISSUE TITLE
TS Server fatal error:  Cannot read property 'getSourceFile' of undefined

### ISSUE THREAD

**Issue by oananistor01** [microsoft/vscode#145556]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'getSourceFile' of undefined
    at Function.AutoImportProviderProject.getRootFileNames (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148984:61)
    at Function.AutoImportProviderProject.create (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149006:38)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148822:77)
    at ConfiguredProject.Project.updateGraph (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148248:26)
    at ConfiguredProject.updateGraph (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149145:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150849:25)
    at ProjectService.assignProjectToOpenedScriptInfo (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151747:44)
    at d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152070:97
    at Object.flatMap (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153089:46)
    at d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:28)
    at IOSession.Session.executeCommand (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:33)
    at IOSession.Session.onMessage (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154986:35)
    at Interface.<anonymous> (d:\Visual Studio Code 1.51.1\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (19.25GB free)|
|Process Argv|--crash-reporter-id a1a846a3-6042-407c-9c4b-c8f92d49535c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.8.0
auto-rename-tag|for|0.1.10
vue-snippets|hol|1.0.4
vetur|oct|0.31.3
vue-vscode-snippets|sdr|3.1.1
sonarlint-vscode|Son|1.21.0
es6-string-html|Tob|2.12.0
vue-language-features|znc|0.8.0

</details>

**Comment by mjbvz** [comment]
Closing as this is an old TS version and the issue was likely already fixed
