### ISSUE TITLE
Running tests with coverage causes some tests to fail

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode#145600]
Running `test.[sh|bat] --coverage` causes a number of tests to fail. These all pass just fine without the --coverage option.

```
←[92m ←[0m←[32m 7769 passing←[0m←[90m (2m)←[0m
←[36m ←[0m←[36m 36 pending←[0m
←[31m  9 failing←[0m

←[0m  1) Workbench - Test Results Service
       service
         keeps ongoing tests on top:

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  [
+   LiveTestResult {
+     _completedAt: 1647885518142,
+     changeEmitter: Emitter {
+       _disposed: false,
+       _event: [Function (anonymous)],
+       _leakageMon: undefined,
+       _listeners: LinkedList {
+         _first: Node {
+           element: Listener {
+             callback: [Function: fire],
+             callbackThis: Emitter {
+               _disposed: false,
+               _event: [Function (anonymous)],
+               _leakageMon: undefined,
+               _options: undefined,
+               _perfMon: undefined
+             },
+             stack: undefined,
+             subscription: SafeDisposable {
+               dispose: [Function (anonymous)],
+               isset: [Function (anonymous)],
+               unset: [Function (anonymous)]
+             }
+           },
+           next: Node {
...
-   TestLiveTestResult {
-     changeEmitter: Emitter {
-       _deliveryQueue: LinkedList {
-         _first: Node {
-           element: undefined,
-           next: undefined,
-           prev: undefined
-         },
-         _last: Node {
-           element: undefined,
-           next: undefined,
-           prev: undefined
-         },
-         _size: 0
-       },
-       _disposed: false,
-       _event: [Function (anonymous)],
-       _leakageMon: undefined,
-       _listeners: LinkedList {
-         _first: <ref *1> Node {
-           element: Listener {
-             callback: [Function (anonymous)],
-             callbackThis: undefined,
-             stack: undefined,
-             subscription: SafeDisposable {
...←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

←[0m←[90m
      at Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/contrib/testing/test/common/testResultService.test.js:208:24)
←[0m
←[0m  2) EditorsObserver
       basics (multi group):

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true
←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

      ←[31m-false←[0m
      ←[32m+true←[0m
      ←[0m←[90m
      at Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/services/editor/test/browser/editorsObserver.test.js:147:20)
←[0m
←[0m  3) EditorsObserver
       hasEditor/hasEditors - side by side editor support:

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true
←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

      ←[31m-false←[0m
      ←[32m+true←[0m
      ←[0m←[90m
      at Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/services/editor/test/browser/editorsObserver.test.js:200:20)
←[0m
←[0m  4) EditorsObserver
       copy group:

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true
←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

      ←[31m-false←[0m
      ←[32m+true←[0m
      ←[0m←[90m
      at Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/services/editor/test/browser/editorsObserver.test.js:249:20)
←[0m
←[0m  5) CellOperations
       Join cell with below - single cell:

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  ResourceTextEdit {
    metadata: undefined,
...
        startLineNumber: 1
      },
+     text: '\n'
-     text: '\nvar c = 3;'
    },
    versionId: undefined
  }←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

             "endLineNumber": 1
             "startColumn": 11
             "startLineNumber": 1
           }
      ←[31m-    "text": "\n"←[0m
      ←[32m+    "text": "\nvar c = 3;"←[0m
         }
         "versionId": "[undefined]"
       }
      ←[0m←[90m
      at file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:180:24
      at async withTestNotebook (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/testNotebookEditor.js:244:21)
      at async Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:170:13)
←[0m
←[0m  6) CellOperations
       Join cell with above - single cell:

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  ResourceTextEdit {
    metadata: undefined,
...
        startLineNumber: 1
      },
+     text: '\n'
-     text: '\nvar c = 3;'
    },
    versionId: undefined
  }←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

             "endLineNumber": 1
             "startColumn": 11
             "startLineNumber": 1
           }
      ←[31m-    "text": "\n"←[0m
      ←[32m+    "text": "\nvar c = 3;"←[0m
         }
         "versionId": "[undefined]"
       }
      ←[0m←[90m
      at file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:202:24
      at async withTestNotebook (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/testNotebookEditor.js:244:21)
      at async Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:192:13)
←[0m
←[0m  7) CellOperations
       Join cell with below - multiple cells:

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  ResourceTextEdit {
    metadata: undefined,
...
        startLineNumber: 1
      },
+     text: '\n\n'
-     text: '\nvar b = 2;\nvar c = 3;'
    },
    versionId: undefined
  }←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

             "endLineNumber": 1
             "startColumn": 11
             "startLineNumber": 1
           }
      ←[31m-    "text": "\n\n"←[0m
      ←[32m+    "text": "\nvar b = 2;\nvar c = 3;"←[0m
         }
         "versionId": "[undefined]"
       }
      ←[0m←[90m
      at file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:222:24
      at async withTestNotebook (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/testNotebookEditor.js:244:21)
      at async Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:214:13)
←[0m
←[0m  8) CellOperations
       Join cell with above - multiple cells:

      ←[31mAssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  ResourceTextEdit {
    metadata: undefined,
...
        startLineNumber: 1
      },
+     text: '\n\n'
-     text: '\nvar b = 2;\nvar c = 3;'
    },
    versionId: undefined
  }←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

             "endLineNumber": 1
             "startColumn": 11
             "startLineNumber": 1
           }
      ←[31m-    "text": "\n\n"←[0m
      ←[32m+    "text": "\nvar b = 2;\nvar c = 3;"←[0m
         }
         "versionId": "[undefined]"
       }
      ←[0m←[90m
      at file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:242:24
      at async withTestNotebook (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/testNotebookEditor.js:244:21)
      at async Context.<anonymous> (file:///C:/src/vscode/out/vs/workbench/contrib/notebook/test/browser/cellOperations.test.js:234:13)
←[0m
←[0m  9) Unexpected Errors & Loader Errors
       assertCleanState - check that registries are clean and objects are disposed at the end of test running:

      ←[31mAssertionError [ERR_ASSERTION]: No leaking LanguagesRegistry←[0m
      ←[32m+ expected←[0m ←[31m- actual←[0m

      ←[31m-4←[0m
      ←[32m+0←[0m
      ←[0m←[90m
      at assertCleanState (file:///C:/src/vscode/out/vs/workbench/test/common/utils.js:18:16)
      at Context.<anonymous> (C:\src\vscode\test\unit\electron\renderer.js:198:6)
←[0m
```

**Comment by connor4312** [comment]
We may fix this eventually, perhaps for self-hosting purposes when I add code coverage to built-in VS Code testing. But right now code coverage is not something that we have great interest in.
