### ISSUE TITLE
Missing dnd items

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145686]
Testing #145577

* take the dummy below
* I don't see `application/vnd.code.tree.footree` item being dropped, but they are set on drag
* on the flip-side I do see some "empty" items being dropped

```ts

	const dragAndDropController = new class implements vscode.TreeDragAndDropController<string> {

		dropMimeTypes: string[] = ['Files', 'resourceurls', 'text/plain', 'codeeditors', 'application/vnd.code.tree.footree', 'tree-dnd'];

		dragMimeTypes: string[] = this.dropMimeTypes;

		handleDrag(source: string[], treeDataTransfer: vscode.DataTransfer<vscode.DataTransferItem>, token: vscode.CancellationToken): void | Thenable<void> {
			console.log('DID DRAG...')
			treeDataTransfer.set('application/vnd.code.tree.footree', new vscode.DataTransferItem(source))
			treeDataTransfer.forEach(async (value, key) => {
				console.log(`DRAG ITEM with ${key} -> ${await value.asString()}`)
			})
		}

		handleDrop(target: string, source: vscode.DataTransfer<vscode.DataTransferItem>, token: vscode.CancellationToken): void | Thenable<void> {

			console.log(`DID DROP onto ${target}`);

			source.forEach(async (value, key) => {
				console.log(`DROP ITEM with ${key} -> ${await value.asString()}`)
			})
		}
	}

	const treeDataProvider = new class implements vscode.TreeDataProvider<string> {

		#data: string[] = ['zap', 'globe', 'sync', 'archive', 'arrow-swap', 'azure-devops', 'arrow-down', 'book', 'arrow-small-up']

		getTreeItem(element: string): vscode.TreeItem {
			const item = new vscode.TreeItem(element)
			item.iconPath = new vscode.ThemeIcon(element);
			return item;
		}

		getChildren(element?: string): vscode.ProviderResult<string[]> {
			if (!element) {
				return this.#data;
			}
			const idx = this.#data.indexOf(element);
			return this.#data.slice(idx + 1).concat(this.#data.slice(0, idx));
		}
	}


	const tree = vscode.window.createTreeView('footree', {
		treeDataProvider,
		dragAndDropController
	})
```

**Comment by jrieken** [comment]
This is what's being printed

```
[Extension Host] DID DRAG... (at Object.handleDrag (/Users/jrieken/Code/_samples/dummy/index.js:60:15))
console.ts:137 [Extension Host] DRAG ITEM with application/vnd.code.tree.footree -> ["sync"] (at /Users/jrieken/Code/_samples/dummy/index.js:63:17)
console.ts:137 [Extension Host] DID DROP onto archive (at Object.handleDrop (/Users/jrieken/Code/_samples/dummy/index.js:67:15))
console.ts:137 [Extension Host] DROP ITEM with codeeditors ->  (at /Users/jrieken/Code/_samples/dummy/index.js:69:17)
console.ts:137 [Extension Host] DROP ITEM with resourceurls ->  (at /Users/jrieken/Code/_samples/dummy/index.js:69:17)
```

**Comment by jrieken** [comment]
This starts to work when I set `dragMimeTypes` to the empty array (`[]`)
