### ISSUE TITLE
Tree item dnd item for `text/plain` reveal it id

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145687]
Testing #145577

* have the code below
* drag a item of the tree onto the tree itself
* two dnd items are being dropped: `application/vnd.code.tree.footree` and `text/plain`
* the value of the latter is the internal tree id (`0/0:globe`) and I am unsure how useful that is. Maybe the label of the tree item is a better value?

```ts

	const dragAndDropController = new class implements vscode.TreeDragAndDropController<string> {

		dropMimeTypes: string[] = ['Files', 'resourceurls', 'text/plain', 'codeeditors', 'application/vnd.code.tree.footree', 'tree-dnd'];

		// dragMimeTypes: string[] = this.dropMimeTypes;
		dragMimeTypes: string[] = [];

		handleDrag(source: string[], treeDataTransfer: vscode.DataTransfer<vscode.DataTransferItem>, token: vscode.CancellationToken): void | Thenable<void> {
			console.log('DID DRAG...')
			treeDataTransfer.set('application/vnd.code.tree.footree', new vscode.DataTransferItem(source))
			treeDataTransfer.forEach(async (value, key) => {
				console.log(`DRAG ITEM with ${key} -> ${await value.asString()}`)
			})
		}

		handleDrop(target: string, source: vscode.DataTransfer<vscode.DataTransferItem>, token: vscode.CancellationToken): void | Thenable<void> {

			console.log(`DID DROP onto ${target}`);

			source.forEach(async (value, key) => {
				console.log(`DROP ITEM with ${key} -> ${await value.asString()}`)
			})
		}
	}

	const treeDataProvider = new class implements vscode.TreeDataProvider<string> {

		#data: string[] = ['zap', 'globe', 'sync', 'archive', 'arrow-swap', 'azure-devops', 'arrow-down', 'book', 'arrow-small-up']

		getTreeItem(element: string): vscode.TreeItem {
			const item = new vscode.TreeItem(element)
			item.iconPath = new vscode.ThemeIcon(element);
			return item;
		}

		getChildren(element?: string): vscode.ProviderResult<string[]> {
			if (!element) {
				return this.#data;
			}
			const idx = this.#data.indexOf(element);
			return this.#data.slice(idx + 1).concat(this.#data.slice(0, idx));
		}
	}


	const tree = vscode.window.createTreeView('footree', {
		treeDataProvider,
		dragAndDropController
	})
```

**Comment by jrieken** [comment]
console output

```
onsole.ts:137 [Extension Host] DID DRAG... (at Object.handleDrag (/Users/jrieken/Code/_samples/dummy/index.js:60:15))
console.ts:137 [Extension Host] DRAG ITEM with application/vnd.code.tree.footree -> ["globe"] (at /Users/jrieken/Code/_samples/dummy/index.js:63:17)
console.ts:137 [Extension Host] DID DROP onto sync (at Object.handleDrop (/Users/jrieken/Code/_samples/dummy/index.js:67:15))
console.ts:137 [Extension Host] DROP ITEM with text/plain -> 0/0:globe (at /Users/jrieken/Code/_samples/dummy/index.js:69:17)
console.ts:137 [Extension Host] DROP ITEM with application/vnd.code.tree.footree -> ["globe"] (at /Users/jrieken/Code/_samples/dummy/index.js:69:17)
```

**Comment by jrieken** [comment]
Yeah, maybe not change but drop/filter it. I feel that we should curate the items that extensions see - once for clarity and for not "leaking" internals to them
