### ISSUE TITLE
Tests in FileService/TextFileModel are flaky on Linux

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14596]
https://monacotools.visualstudio.com/Monaco/_build/explorer?favDefinitionId=54&_a=summary&buildId=24583

```
2016-10-27T06:11:03.391Z:   FileService
2016-10-27T06:11:03.431Z:     ✓ resolveContents
2016-10-27T06:11:13.456Z:     2) createFile
2016-10-27T06:11:13.509Z: Error: ENOENT: no such file or directory, stat '/tmp/vsctests/service/3134f92c-ab6e-4371-8f4a-3694f2699aa5/test.txt'
2016-10-27T06:11:13.509Z:     at Error (native)
2016-10-27T06:11:13.510Z:     3) "after each" hook
2016-10-27T06:11:13.512Z: WARNING: Promise with no error callback:26
2016-10-27T06:11:13.539Z: { exception: null,
2016-10-27T06:11:13.539Z:   error: 
2016-10-27T06:11:13.539Z:    { Error: ENOENT: no such file or directory, stat '/tmp/vsctests/service/3134f92c-ab6e-4371-8f4a-3694f2699aa5/test.txt'
2016-10-27T06:11:13.539Z:        at Error (native)
2016-10-27T06:11:13.539Z:      errno: -2,
2016-10-27T06:11:13.539Z:      code: 'ENOENT',
2016-10-27T06:11:13.539Z:      syscall: 'stat',
2016-10-27T06:11:13.539Z:      path: '/tmp/vsctests/service/3134f92c-ab6e-4371-8f4a-3694f2699aa5/test.txt',
2016-10-27T06:11:13.539Z:      uncaught: true },
2016-10-27T06:11:13.539Z:   promise: 
2016-10-27T06:11:13.539Z:    Promise_ctor {
2016-10-27T06:11:13.539Z:      _oncancel: null,
2016-10-27T06:11:13.539Z:      _nextState: null,
2016-10-27T06:11:13.539Z:      _state: 
2016-10-27T06:11:13.540Z:       { name: 'error',
2016-10-27T06:11:13.540Z:         enter: [Function: enter],
2016-10-27T06:11:13.540Z:         cancel: [Function: _],
2016-10-27T06:11:13.540Z:         done: null,
2016-10-27T06:11:13.540Z:         then: null,
2016-10-27T06:11:13.540Z:         _completed: [Function: _],
2016-10-27T06:11:13.540Z:         _error: [Function: _],
2016-10-27T06:11:13.540Z:         _notify: [Function: notifyError],
2016-10-27T06:11:13.540Z:         _progress: [Function: _],
2016-10-27T06:11:13.540Z:         _setCompleteValue: [Function: _],
2016-10-27T06:11:13.540Z:         _setErrorValue: [Function: _] },
2016-10-27T06:11:13.540Z:      _listeners: null,
2016-10-27T06:11:13.540Z:      _value: 
2016-10-27T06:11:13.540Z:       { Error: ENOENT: no such file or directory, stat '/tmp/vsctests/service/3134f92c-ab6e-4371-8f4a-3694f2699aa5/test.txt'
2016-10-27T06:11:13.540Z:           at Error (native)
2016-10-27T06:11:13.540Z:         errno: -2,
2016-10-27T06:11:13.541Z:         code: 'ENOENT',
2016-10-27T06:11:13.541Z:         syscall: 'stat',
2016-10-27T06:11:13.541Z:         path: '/tmp/vsctests/service/3134f92c-ab6e-4371-8f4a-3694f2699aa5/test.txt',
2016-10-27T06:11:13.541Z:         uncaught: true },
2016-10-27T06:11:13.541Z:      _isException: false,
2016-10-27T06:11:13.541Z:      _errorId: 26,
2016-10-27T06:11:13.541Z:      done: [Function: ErrorPromise_done],
2016-10-27T06:11:13.541Z:      then: [Function: ErrorPromise_then] },
2016-10-27T06:11:13.541Z:   handler: undefined,
2016-10-27T06:11:13.541Z:   id: 26,
2016-10-27T06:11:13.541Z:   parent: undefined }
2016-10-27T06:11:13.542Z: 
2016-10-27T06:11:13.542Z:   Stat Resolver
2016-10-27T06:11:13.544Z:     4) createFolder
2016-10-27T06:11:13.546Z:     5) "before each" hook for "createFolder"
2016-10-27T06:11:13.546Z: 
2016-10-27T06:11:13.547Z: 
2016-10-27T06:11:13.547Z:   1824 passing (28s)
2016-10-27T06:11:13.547Z:   5 failing
2016-10-27T06:11:13.548Z: 
2016-10-27T06:11:13.549Z:   1) Extfs writeFileAndFlush:
2016-10-27T06:11:13.549Z:      Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
2016-10-27T06:11:13.549Z:   
2016-10-27T06:11:13.549Z: 
2016-10-27T06:11:13.549Z:   2) FileService createFile:
2016-10-27T06:11:13.549Z:      Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
2016-10-27T06:11:13.549Z:   
2016-10-27T06:11:13.550Z: 
2016-10-27T06:11:13.550Z:   3) FileService "after each" hook:
2016-10-27T06:11:13.550Z:      Uncaught Error: ENOENT: no such file or directory, stat '/tmp/vsctests/service/3134f92c-ab6e-4371-8f4a-3694f2699aa5/test.txt'
2016-10-27T06:11:13.550Z:       at Error (native)
2016-10-27T06:11:13.550Z: 
2016-10-27T06:11:13.550Z:   4) FileService createFolder:
2016-10-27T06:11:13.550Z:      TypeError: Cannot read property 'call' of undefined
2016-10-27T06:11:13.551Z:   
2016-10-27T06:11:13.551Z: 
2016-10-27T06:11:13.551Z:   5) FileService "before each" hook for "createFolder":
2016-10-27T06:11:13.551Z:      TypeError: Cannot read property 'call' of undefined
2016-10-27T06:11:13.551Z:   
2016-10-27T06:11:13.551Z: 
2016-10-27T06:11:13.551Z: 
```

**Comment by bpasero** [comment]
Added more output and done handler.

**Comment by bpasero** [comment]
Also: 

```
2016-10-28T11:16:53.931Z: WARNING: Promise with no error callback:122
2016-10-28T11:16:53.960Z: { exception: 
2016-10-28T11:16:53.960Z:    { AssertionError: false == true
2016-10-28T11:16:53.960Z:        at /vso/work/2/s/out-build/vs/workbench/services/textfile/test/textFileEditorModel.test.js:176:28
2016-10-28T11:16:53.960Z:        at Object.notifySuccess [as _notify] (/vso/work/2/s/out-build/vs/base/common/winjs.base.raw.js:1170:59)
2016-10-28T11:16:53.960Z:        at Object.enter (/vso/work/2/s/out-build/vs/base/common/winjs.base.raw.js:852:30)
2016-10-28T11:16:53.961Z:        at Promise_ctor._run (/vso/work/2/s/out-build/vs/base/common/winjs.base.raw.js:1068:29)
2016-10-28T11:16:53.961Z:        at Promise_ctor._completed (/vso/work/2/s/out-build/vs/base/common/winjs.base.raw.js:1036:18)
2016-10-28T11:16:53.961Z:        at tryOnTimeout (timers.js:232:11)
2016-10-28T11:16:53.961Z:        at Timer.listOnTimeout (timers.js:202:5)
2016-10-28T11:16:53.961Z:      name: 'AssertionError',
2016-10-28T11:16:53.961Z:      actual: false,
2016-10-28T11:16:53.961Z:      expected: true,
2016-10-28T11:16:53.961Z:      operator: '==',
2016-10-28T11:16:53.961Z:      message: 'false == true',
2016-10-28T11:16:53.961Z:      generatedMessage: true },
2016-10-28T11:16:53.961Z:   error: null,
2016-10-28T11:16:53.961Z:   promise: 

```

Refs: https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/explorer?_a=summary&buildId=24631

**Comment by bpasero** [comment]
Haven't seen this in a while, will reopen when we get another fail and then see if my output reveals something.
