### ISSUE TITLE
No `text/uri-list` item when dropping from explorer or tab

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#146031]
* have tree below
* debug log level
* drop an file from the explorer and/or tab
* the debug view says `text/uri-list` and `text/plain`
* :bug: the drop handler doesn't receive the `text/uri-list`

```
ACTIVE
index.js:42
DID DROP onto globe
index.js:58
DROP ITEM with text[/plain]() -> [/Users/jrieken/Code/_samples/abc/test.less]() undefined
```

```ts
const dragAndDropController = new class implements vscode.TreeDragAndDropController<string> {

		dropMimeTypes: string[] = ['text/plain', 'text/uri-list', 'application/vnd.code.tree.footree'];
		// dropMimeTypes: string[] = [];

		dragMimeTypes: string[] = this.dropMimeTypes;
		// dragMimeTypes: string[] = [];

		// handleDrag(source: string[], treeDataTransfer: vscode.DataTransfer, token: vscode.CancellationToken): void | Thenable<void> {
		// 	console.log('DID DRAG...')
		// 	treeDataTransfer.set('application/vnd.code.tree.footree', new vscode.DataTransferItem(source))
		// 	treeDataTransfer.forEach(async (value, key) => {
		// 		console.log(`DRAG ITEM with ${key} -> ${await value.asString()}`)
		// 	})
		// }

		handleDrop(target: string, source: vscode.DataTransfer, token: vscode.CancellationToken): void | Thenable<void> {
			console.log(`DID DROP onto ${target}`);
			source.forEach(async (value, key) => {
				console.log(`DROP ITEM with ${key} -> ${await value.asString()}`, value.value)
			})
		}
	}

	const treeDataProvider = new class implements vscode.TreeDataProvider<string> {

		#data: string[] = ['zap', 'globe', 'sync', 'archive', 'arrow-swap', 'azure-devops', 'arrow-down', 'book', 'arrow-small-up']

		getTreeItem(element: string): vscode.TreeItem {
			const item = new vscode.TreeItem(element)
			item.iconPath = new vscode.ThemeIcon(element);
			return item;
		}

		getChildren(element?: string): vscode.ProviderResult<string[]> {
			if (!element) {
				return this.#data;
			}
			const idx = this.#data.indexOf(element);
			return this.#data.slice(idx + 1).concat(this.#data.slice(0, idx));
		}
	}

	const tree = vscode.window.createTreeView('footree', {
		treeDataProvider,
		dragAndDropController,
		canSelectMany: true
	})
```

**Comment by alexr00** [comment]
I'm not able to reproduce this:
```
[Extension Host] DID DROP onto arrow-swap (at Object.handleDrop (c:\Users\alros\.vscode-oss-dev\extensions\helloworld-sample\src\extension.ts:34:21))
console.ts:137 [Extension Host] DROP ITEM with text/plain -> D:\repos\alexr00\playground\test2.js undefined (at c:\Users\alros\.vscode-oss-dev\extensions\helloworld-sample\src\extension.ts:36:25)
console.ts:137 [Extension Host] DROP ITEM with text/uri-list -> file:///D:/repos/alexr00/playground/test2.js undefined (at c:\Users\alros\.vscode-oss-dev\extensions\helloworld-sample\src\extension.ts:36:25)
console.ts:137 [Extension Host] DID DROP onto archive (at Object.handleDrop (c:\Users\alros\.vscode-oss-dev\extensions\helloworld-sample\src\extension.ts:34:21))
console.ts:137 [Extension Host] DROP ITEM with text/plain -> D:\repos\alexr00\playground\cat.pawdraw
D:\repos\alexr00\playground\catPic.jpg
D:\repos\alexr00\playground\no_extension
D:\repos\alexr00\playground\test2.js undefined (at c:\Users\alros\.vscode-oss-dev\extensions\helloworld-sample\src\extension.ts:36:25)
```
