### ISSUE TITLE
C/C++ extension installation failed

### ISSUE THREAD

**Issue by MicSG-dev** [microsoft/vscode#146005]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2 (user setup);
- Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
- Date: 2022-03-10T14:33:55.248Z
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Under extensions look for the C/C++ extension;
2. Click install. The extension is v1.9.7 ([link](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools));
3. The error "Error while installing 'C/C++' extension. Please check the [log](command:workbench.action.showWindowLog) for more details." will appear; 
OUTPUT: [2022-03-24 16:46:56.011] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/c:/Users/cliente/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:27625)
[2022-03-24 16:46:59.506] [renderer1] [error] Error: XHR failed
    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/c:/Users/cliente/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:27625)
[2022-03-24 16:46:59.606] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/c:/Users/cliente/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:27625)

**Comment by MicSG-dev** [comment]
The problem was somehow related to the server. I had already reported this issue in #145978.
Now the download extensions are working again.
