### ISSUE TITLE
TS Server fatal error:  Cannot read property 'getSourceFiles' of undefined

### ISSUE THREAD

**Issue by victorlmneves** [microsoft/vscode#146107]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.3

**Steps to reproduce crash**
1. Open any project that uses Typescript

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'getSourceFiles' of undefined
    at ConfiguredProject.Project.getScriptInfos (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:166614:44)
    at ProjectService.sendProjectTelemetry (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:169477:66)
    at ConfiguredProject.updateGraph (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:167831:37)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:169551:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:170634:44)
    at /Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:170974:97
    at Object.flatMap (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:170974:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:172133:46)
    at /Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174069:88
    at IpcIOSession.Session.executeWithRequestId (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174060:28)
    at IpcIOSession.Session.executeCommand (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174069:33)
    at IpcIOSession.Session.onMessage (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174095:35)
    at process.<anonymous> (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:176730:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|156, 67, 40|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id f44da19d-6f59-4732-8d39-f15f3439850d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
sonarqube-status|adi|1.1.0
project-manager|ale|12.5.0
html-end-tag-labels|ant|0.8.0
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.8.0
regex|chr|0.4.0
cssrem|cip|2.7.1
vscode-plugin|cod|0.4.2
language-postcss|cpy|1.1.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.2
vscode-axe-linter|deq|4.4.0
githistory|don|0.6.19
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.4.0
git-project-manager|fel|1.8.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.9.5350
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
path-autocomplete|ion|1.19.1
volar|joh|0.33.9
vscode-typescript-vue-plugin|joh|0.33.9
vscode-colorize|kam|0.11.1
vscode-vitest-runner|kin|0.0.3
inline-parameters|lia|0.2.1
copilot-vscode|Met|1.3.0
document|min|2.1.5
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5449
emoji|Per|1.0.1
tsimporter|pmn|2.0.1
polacode|pnp|0.3.4
ponicode|Pon|0.67.1
vscode-css-peek|pra|4.2.0
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
comment-ts|sal|1.0.21
vscode-javascript-booster|sbu|14.0.1
vscode-scss-formatter|sib|2.4.0
vsc-quokka-statusbar|ske|1.3.6
sonarlint-vscode|Son|3.3.3
autoimport|ste|1.5.4
addDocComments|ste|0.0.8
code-spell-checker|str|2.1.7
vscode-stylelint|sty|1.2.2
sass-indented|syl|1.8.19
vscode-status-bar-format-toggle|tom|3.0.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0
quokka-vscode|Wal|1.0.451
vscode-js-console-utils|wht|0.7.0
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0
vitest-explorer|Zix|0.1.10
vue-language-features|znc|0.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
pynewfile477cf:30450039

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by victorlmneves** [comment]
@mjbvz meanwhile I discover the problem. It's not from VS Code. It's caused by an extension (vue-language-features) at least after doing a clean install and starting adding them one by one, it was when I saw it starting with this error
