### ISSUE TITLE
internal/modules/cjs/loader.js:1109

### ISSUE THREAD

**Issue by cristoph143** [microsoft/vscode#146150]
Issue Type: <b>Bug</b>

[2022-03-28 00:04:22.842] internal/modules/cjs/loader.js:1109
[2022-03-28 00:04:22.842]     throw err;
[2022-03-28 00:04:22.842]     ^
[2022-03-28 00:04:22.842] 
[2022-03-28 00:04:22.842] SyntaxError: /home/cristoph143/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/product.json: Unexpected end of JSON input
[2022-03-28 00:04:22.842]     at parse (<anonymous>)
[2022-03-28 00:04:22.842]     at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
[2022-03-28 00:04:22.842]     at Module.load (internal/modules/cjs/loader.js:928:32)
[2022-03-28 00:04:22.842]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[2022-03-28 00:04:22.842]     at Module.require (internal/modules/cjs/loader.js:952:19)
[2022-03-28 00:04:22.842]     at require (internal/modules/cjs/helpers.js:88:18)
[2022-03-28 00:04:22.842]     at Object.<anonymous> (/home/cristoph143/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/server-main.js:1:106)
[2022-03-28 00:04:22.842]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[2022-03-28 00:04:22.842]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[2022-03-28 00:04:22.842]     at Module.load (internal/modules/cjs/loader.js:928:32)
[2022-03-28 00:04:22.843] VS Code Server for WSL closed unexpectedly.
[2022-03-28 00:04:22.843] For help with startup problems, go to
[2022-03-28 00:04:22.843] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2022-03-28 00:04:22.870] WSL Daemon exited with code 0

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Connection to 'WSL: Debian' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
Connection to 'WSL: Debian' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
Connection to 'WSL: Debian' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.30GB free)|
|Process Argv|--crash-reporter-id 79a90699-3037-44da-9136-556b869dbb04|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Debian' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

Connection to 'WSL: Debian' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

Connection to 'WSL: Debian' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
pynewfile477:30450038

```

</details>

**Comment by aeschli** [comment]
Can you check what's the content of `/home/cristoph143/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/product.json` ? Is it a valid JSON file?

Maybe the install got corrupted. You 
- delete all VS Code windows
- delete `/home/cristoph143/.vscode-server/bin/` and all its contents.
- restart VS Code.

**Comment by cristoph143** [comment]
Thank you :)
