### ISSUE TITLE
Leak is reported on console and CPU ramps up to 100%

### ISSUE THREAD

**Issue by mapio** [microsoft/vscode#146170]
Issue Type: <b>Performance Issue</b>

While editing a few Jupyter Notebook files the CPU ramps up and the editor became unusable.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-37-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3050)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|31.15GB (0.26GB free)|
|Process Argv|--verbose E06.ipynb --enable-proposed-api genuitecllc.codetogether --crash-reporter-id b7a8e658-5841-410c-b238-68977988cc60|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    6	   191	 62339	code main
    0	    32	 62342	   zygote
    1	   128	 62374	     gpu-process
    0	    32	 62343	   zygote
    0	     0	 62345	     zygote
    0	   128	 62440	       window (undefined)
    0	    96	 63716	       window (undefined)
    0	   128	 66002	       window (undefined)
    0	    64	 69592	       issue-reporter
    0	    32	 62378	   utility-network-service
    0	   255	 62402	   window (● E06.ipynb - Visual Studio Code)
    0	   415	 62425	   extensionHost
    0	   159	 62516	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.3/dist/server.bundle.js --cancellationReceive=file:d48bce59d1382aa02ffd7a0fc2953146c7d9cb60f9 --node-ipc --clientProcessId=62425
    0	    96	 62578	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=62425
    0	   159	 62590	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.3/dist/server.bundle.js --cancellationReceive=file:46da0a6f785c70946d4a0ac55cec7345b08164b862 --node-ipc --clientProcessId=62425
    0	    64	 62767	     electron_node Vhul.js 
    0	   159	 62458	   shared-process
    0	    64	 62476	     ptyHost
    0	    64	 62498	     fileWatcher
    0	    64	 63692	     fileWatcher
    0	    64	 65773	     fileWatcher
    0	     0	 69612	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 69613	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   287	 63611	   window (L06.py - drafts - Visual Studio Code)
    0	   447	 63637	   extensionHost
    0	   159	 63787	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.3/dist/server.bundle.js --cancellationReceive=file:15c0e6bf200db8b4443415f14bd1beca17b382eb0d --node-ipc --clientProcessId=63637
    0	    64	 63806	     /home/santini/.local/share/virtualenvs/named-let-liblet/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"d2571af4-325a-4c38-89e4-f67e039f8ed6" --shell=9007 --transport="tcp" --iopub=9009 --f=/tmp/tmp-636379L9G2KIXcYr7.json
    0	   223	 63862	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.3/dist/server.bundle.js --cancellationReceive=file:53fc2580cb5266482953df7a28176c26383eb8f68c --node-ipc --clientProcessId=63637
    0	    96	 63901	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=63637
   10	  1308	 65730	   window (● examples.ipynb - liblet - Visual Studio Code)
    5	  1116	 65756	   extensionHost
    4	    96	 65885	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=65756
    0	   255	 65927	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.3/dist/server.bundle.js --cancellationReceive=file:b8bce5d80e190e1b5ba2d14d1174dece233b082d8e --node-ipc --clientProcessId=65756
    5	   223	 66018	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.3/dist/server.bundle.js --cancellationReceive=file:53d7d566c632e0a4890d279d4b2eac68010d15492c --node-ipc --clientProcessId=65756
    0	    64	 66031	     electron_node wyNrN.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● examples.ipynb - liblet - Visual Studio Code)
|  Window (L06.py - drafts - Visual Studio Code)
|    Folder (liblet): 118 files
|      File types: py(18) pyc(13) txt(8) html(7) svg(7) yml(4) png(4) rst(4)
|                  ipynb(3) gitignore(2)
|      Conf files: github-actions(1) settings.json(1)
|    Folder (drafts): 36 files
|      File types: ipynb(14) json(2) jar(2) envrc(1) gitattributes(1)
|                  gitignore(1) py(1) pyc(1) rst(1) txt(1)
|      Conf files: devcontainer.json(1) settings.json(1) dockerfile(1);
```

</details>
<details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-sievehighlight|adz|1.0.6
vscode-sqlite|ale|0.14.0
asciidoctor-vscode|asc|2.9.8
spellright|ban|3.0.60
emojisense|bie|0.9.0
mermaid-markdown-syntax-highlighting|bpr|1.2.3
path-intellisense|chr|2.8.0
gitlens|eam|12.0.5
myst-highlight|Exe|0.11.0
codetogether|gen|2022.1.3
codespaces|Git|1.5.7
copilot|Git|1.9.5350
vscode-pull-request-github|Git|0.38.1
gitpod-desktop|git|0.0.29
mdmath|goe|2.7.4
go|gol|0.32.0
latex-workshop|Jam|8.23.0
vscode-edit-csv|jan|0.6.8
bats|jet|0.1.9
plantuml|jke|1.8.1
restructuredtext|lex|183.0.0
rainbow-csv|mec|2.2.0
git-graph|mhu|1.30.0
vscode-antlr4|mik|2.2.4
language-gettext|mro|0.2.0
vscode-docker|ms-|1.21.0
vscode-language-pack-it|MS-|1.65.3
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
azure-account|ms-|0.10.1
cpptools|ms-|1.9.7
gradle-language|nac|0.2.3
gremlins|nho|0.26.0
vetur|oct|0.35.0
vscode-print|pdc|0.9.14
polacode|pnp|0.3.4
vscode-data-preview|Ran|2.3.0
java|red|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.1
llvm|RRe|0.1.1
scala|sca|0.5.5
jshelleasy|Sen|1.0.1
vscode-table-formatter|shu|1.2.1
rewrap|stk|1.16.3
html-preview-vscode|tht|0.2.5
simple-rst|tro|1.5.2
vscodeintellicode|Vis|1.2.17
vscode-gradle|vsc|3.11.0
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.1
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vscode-mermaid-preview|vst|1.6.2
clang-format|xav|1.9.0
latex-input|yel|1.0.0
FilterText|yhi|0.0.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
cppdebugcf:30451567
pynewfile477cf:30450039

```

</details>

**Comment by mapio** [comment]
Here is some console output 
```
[62339:0328/092408.177990:INFO:CONSOLE(65)] "[gga] potential listener LEAK detected, having 10911 listeners already. MOST frequent listener (9205):", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (65)
[62339:0328/092408.178031:INFO:CONSOLE(65)] "Error
    at Function.create (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:65:53179)
    at r._event._event [as onDidChange] (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1003)
    at Y (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:731:6731)
    at new Ti (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:731:6796)
    at K (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:731:4094)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:731:4344
    at f.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at f.createModel (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:731:1095)
    at fe.provideTextContent (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2815:456)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async c.resolveTextModelContent (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2399:78495)
    at async c.doCreateReferencedObject (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2399:77386)
    at async h.acquire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:17:32618)
    at async d.createModelReference (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2399:79232)
    at async s._handleAsResourceInput (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2404:77384)
    at async s.$tryOpenDocument (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2404:76807)", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (65)
[62339:0328/092408.196663:INFO:CONSOLE(605)] "%cTRACE color: #888 [text file model] dispose() file:///home/santini/Documents/Activities/Teaching/Courses/let/liblet/.vscode/settings.json", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.196852:INFO:CONSOLE(605)] "%cTRACE color: #888 [backup tracker] discarding backup file:///home/santini/Documents/Activities/Teaching/Courses/let/liblet/.vscode/settings.json ", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.196898:INFO:CONSOLE(605)] "%cTRACE color: #888 [text file model] dispose() file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L06.ipynb", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.197127:INFO:CONSOLE(605)] "%cTRACE color: #888 [backup tracker] discarding backup file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L06.ipynb ", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.197165:INFO:CONSOLE(605)] "%cTRACE color: #888 [text file model] dispose() file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L03.ipynb", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.197390:INFO:CONSOLE(605)] "%cTRACE color: #888 [backup tracker] discarding backup file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L03.ipynb ", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.197427:INFO:CONSOLE(605)] "%cTRACE color: #888 [text file model] dispose() file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L05.ipynb", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.197649:INFO:CONSOLE(605)] "%cTRACE color: #888 [backup tracker] discarding backup file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L05.ipynb ", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.200100:INFO:CONSOLE(605)] "%cTRACE color: #888 [stored file working copy] dispose() file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L03.ipynb notebook/jupyter-notebook", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
[62339:0328/092408.200291:INFO:CONSOLE(605)] "%cTRACE color: #888 [stored file working copy] dispose() file:///home/santini/Documents/Activities/Teaching/Courses/let/handouts/L03.ipynb notebook/jupyter-notebook", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (605)
```

**Comment by mapio** [comment]
This is also probably related to https://github.com/microsoft/pylance-release/issues/2530

As I told in other reports, the bug is a show stopper and I'm planning to abandon vscode (that I love so much), until the bug is fixed.

So I'm willing to provide any info needed to track this down. Ask and I'll do my best to comply.
