### ISSUE TITLE
Extensions fail to fetch.

### ISSUE THREAD

**Issue by proJM1** [microsoft/vscode#146279]
Does this issue occur when all extensions are disabled?: Yes/No
This issue happens with extensions disabled and enabled.

- VS Code Version:1.65.2
- OS Version: Chrome os

When I try to install an extension it will pop up with an error and not install. In the console, you can see that all of the extension files failed to fetch. In the previous version, this would not happen and the extension would work perfectly fine. Does anyone know why?

**Comment by proJM1** [comment]
This is also the web version of vs code. https://vscode.dev/

**Comment by sandy081** [comment]
>  In the console, you can see that all of the extension files failed to fetch.

Can you please share these failures?

**Comment by proJM1** [comment]
I have tried with other extensions and I get the same sort of errors. Also, some of the links will send me to an XML tree others will say the file can't be opened and it might have been deleted or moved. Here is the log:
[2022-04-05 16:47:02.277] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.300] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.460] [window] [info] Ignoring additional builtin extension github.codespaces because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/codespaces/1.5.9/extension'. Failed to fetch
[2022-04-05 16:47:02.532] [window] [info] Ignoring additional builtin extension github.remotehub because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/remotehub/0.30.0/extension'. Failed to fetch
[2022-04-05 16:47:02.612] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.696] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.713] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.720] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.729] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.737] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.754] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.766] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.776] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.785] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.800] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:02.826] [window] [info] Ignoring additional builtin extension ms-vscode.anycode because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode/0.0.62/extension'. Failed to fetch
[2022-04-05 16:47:02.838] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-java because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-java/0.0.3/extension'. Failed to fetch
[2022-04-05 16:47:02.882] [window] [info] Ignoring additional builtin extension ms-vscode.azure-repos because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/azure-repos/0.8.0/extension'. Failed to fetch
[2022-04-05 16:47:02.895] [window] [info] Ignoring additional builtin extension ms-vscode.remote-repositories because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.4.0/extension'. Failed to fetch
[2022-04-05 16:47:02.908] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-php because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-php/0.0.4/extension'. Failed to fetch
[2022-04-05 16:47:03.898] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-c-sharp because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-c-sharp/0.0.3/extension'. Failed to fetch
[2022-04-05 16:47:06.193] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-typescript because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-typescript/0.0.3/extension'. Failed to fetch
[2022-04-05 16:47:10.250] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-go because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-go/0.0.3/extension'. Failed to fetch
[2022-04-05 16:47:10.393] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-cpp because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-cpp/0.0.3/extension'. Failed to fetch
[2022-04-05 16:47:10.524] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-python because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-python/0.0.3/extension'. Failed to fetch
[2022-04-05 16:47:10.609] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-rust because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-rust/0.0.3/extension'. Failed to fetch
[2022-04-05 16:47:10.663] [window] [info] Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
[2022-04-05 16:47:26.384] [window] [info] Getting Manifest... ms-vsliveshare.vsliveshare
[2022-04-05 16:47:26.425] [window] [info] Installing extension: ms-vsliveshare.vsliveshare
[2022-04-05 16:47:26.923] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-04-05 16:47:27.553] [window] [error] Error while installing the extension: ms-vsliveshare.vsliveshare
[2022-04-05 16:47:27.593] [window] [error] Failed to install extension. ms-vsliveshare.vsliveshare
[2022-04-05 16:47:27.611] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vsliveshare.vscode-unpkg.net/MS-vsliveshare/vsliveshare/1.0.5449/extension'. Failed to fetch
    at x.toWebExtension (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3117:113285)
    at async x.addExtensionFromGallery (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3117:110694)
    at async S.doRun (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3118:4877)
[2022-04-05 16:47:27.640] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vsliveshare.vscode-unpkg.net/MS-vsliveshare/vsliveshare/1.0.5449/extension'. Failed to fetch
    at x.toWebExtension (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3117:113285)
    at async x.addExtensionFromGallery (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3117:110694)
    at async S.doRun (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3118:4877)
[2022-04-05 16:47:27.657] [window] [error] Cannot find the package.json from the location 'https://ms-vsliveshare.vscode-unpkg.net/MS-vsliveshare/vsliveshare/1.0.5449/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://ms-vsliveshare.vscode-unpkg.net/MS-vsliveshare/vsliveshare/1.0.5449/extension'. Failed to fetch
    at x.toWebExtension (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3117:113285)
    at async x.addExtensionFromGallery (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3117:110694)
    at async S.doRun (https://vscodeweb.azureedge.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/workbench/workbench.web.main.js:3118:4877)

**Comment by proJM1** [comment]
I have updated to the latest version but I still get the errors.

**Comment by proJM1** [comment]
I restarted my computer and updated to the latest version again and now it´s working! Thanks for your help :)
