### ISSUE TITLE
Smoke tests that need to install extensions became flaky

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146800]
```
 1) VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Extension ms-vscode.vscode-smoketest-check is not found
      at Extensions.searchForExtension (/__w/1/s/test/automation/src/extensions.ts:47:9)
      at Extensions.installExtension (/__w/1/s/test/automation/src/extensions.ts:60:3)
      at Context.<anonymous> (src/areas/extensions/extensions.test.ts:19:4)

```

This test is starting to flake with `playwright` for smoke tests:
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164953&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9302e8c4-de85-5274-34fa-935ce79d4e8d&l=125
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164914&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5&l=118
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164864&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9302e8c4-de85-5274-34fa-935ce79d4e8d&l=113
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164876&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5&l=115

Interestingly this is always in `remote`, never local. And seems to happen on Windows and Linux.

I could not find anything looking in the logs, so the ask here is whether we can add more diagnostics what is going on. It is unclear to me for example whether the search for extensions starts or not, though the progress badge over the extensions view indicates as such, or is that a different indicator?

**Comment by bpasero** [comment]
[playwright-trace-1-install_and_enable_vscode-smoketest-check_extension.zip](https://github.com/microsoft/vscode/files/8415820/playwright-trace-1-install_and_enable_vscode-smoketest-check_extension.zip)

Trace for https://trace.playwright.dev/

**Comment by bpasero** [comment]
[logs-linux-x64-1.zip](https://github.com/microsoft/vscode/files/8415822/logs-linux-x64-1.zip)

Full logs.

**Comment by sandy081** [comment]
Looked into this and I see following frame through out

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/10746682/161740457-8e7fd2d9-02e5-4755-b4b8-31bfd3cd3945.png">

It seems the results are taking time to load, either Marketplace is responding slow or network connectivity is slow. I doubt that MP is slow. I also have retry logic - retry 10 times.

**Comment by sandy081** [comment]
The last two errors are different that what is reported. It seems Uninstall button is not shown after extension is installed

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/10746682/161903571-02e39d98-005d-43d9-a304-f49a92418cf6.png">

**Comment by bpasero** [comment]
Yeah you are right. Interestingly now for once I saw another test fail that needs extension installation to work:

```
  1) VSCode Smoke Tests (Electron)
       Localization
         starts with "DE" locale and verifies title and viewlets text is in German:
     Error: Extension ms-ceintl.vscode-language-pack-de is not found
      at Extensions.searchForExtension (/__w/1/s/test/automation/src/extensions.ts:47:9)
      at Extensions.installExtension (/__w/1/s/test/automation/src/extensions.ts:60:3)
      at Context.<anonymous> (src/areas/workbench/localization.test.ts:19:4)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165302&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=d61c32fd-93f0-5126-b44d-dcf4920dede7&l=70

Can we add some more logging whether this is really waiting for a HTTP response or has some error?

I have extracted the relevant log: https://gist.github.com/bpasero/e75b3623df073fd2b01d3fa5ffcb7af1

I did not see some suspicious output from the renderer though. Interestingly our retry logic seems to be to refresh the viewlet:

```
[2022-04-05T23:10:14.626Z] click div.part.sidebar.left[id="workbench.parts.sidebar"] .codicon.codicon-extensions-refresh
[2022-04-05T23:10:14.626Z] getElementXY div.part.sidebar.left[id="workbench.parts.sidebar"] .codicon.codicon-extensions-refresh
```

Is that still accurate to get it going?

**Comment by sandy081** [comment]
Above issue is very much related to the main issue reported here.

**Comment by bpasero** [comment]
> May I know if the smoke tests can run in verbose mode?

Yeah we have an option for that. To clarify, you want `--verbose` passed to the VSCode client right?

**Comment by sandy081** [comment]
Yes, can we enable this for smoke tests always? I would like to add some trace statements for MP search requests.

**Comment by bpasero** [comment]
@sandy081 good point, it was actually not supported thus far. I pushed a change to allow `--verbose` for the smoke test to set `--log trace` for client and servers. We now run with `--verbose` for all smoke tests, but I would probably remove that again once we have figured out more 👍

**Comment by bpasero** [comment]
@sandy081 we have our first run on Windows with `--verbose` and failing, entire logs folder:

[logs-windows-x64-1.zip](https://github.com/microsoft/vscode/files/8426100/logs-windows-x64-1.zip)

I already notice some interesting things:
* settings sync seems enabled (?)
* experiments are fetched

**Comment by bpasero** [comment]
Opened https://github.com/microsoft/vscode/tree/ben/146800 and enabled again.

**Comment by sandy081** [comment]
Thanks for enabling the verbose logs. I will do the exploration in the above branch.

**Comment by bpasero** [comment]
👍 , just pushed a change to set `--sync=off`, though not sure that helps. Will actually try now to run these smoke tests on Windows against a real build to see if this reproduces locally 🤔

**Comment by bpasero** [comment]
A pattern that I see is that when the request just hangs, the services for the shared process have not finished initializing:

```
[2022-04-08 08:56:20.509] [sharedprocess] [trace] Started scanning system extensions
[2022-04-08 08:56:20.509] [sharedprocess] [trace] Started scanning user extensions
[2022-04-08 08:56:20.510] [sharedprocess] [trace] Started scanning system extensions
[2022-04-08 08:56:20.510] [sharedprocess] [trace] Started scanning user extensions
[2022-04-08 08:56:20.510] [sharedprocess] [info] %%% getExtensionsControlManifest: creating new promise because this.extensionsControlManifest===undefined
[2022-04-08 08:56:20.510] [sharedprocess] [trace] ExtensionManagementService.refreshReportedCache 3
[2022-04-08 08:56:20.510] [sharedprocess] [info] ??? getExtensionsControlManifest before request
[2022-04-08 08:56:20.511] [sharedprocess] [trace] RequestService#request https://az764295.vo.msecnd.net/extensions/marketplace.json
[2022-04-08 08:56:20.511] [sharedprocess] [info] &&& Request trace: request begin: {"type":"GET","url":"https://az764295.vo.msecnd.net/extensions/marketplace.json","proxyAuthorization":null}
[2022-04-08 08:56:20.511] [sharedprocess] [info] &&& Request trace: onloadstart
[2022-04-08 08:56:20.511] [sharedprocess] [trace] Started scanning system extensions
[2022-04-08 08:56:20.511] [sharedprocess] [trace] Started scanning user extensions
[2022-04-08 08:56:20.512] [sharedprocess] [debug] ComputeTargetPlatform: win32-x64
[2022-04-08 08:56:20.517] [sharedprocess] [trace] [File Watcher (node.js)] Request to start watching: c:\Users\CLOUDT~1\AppData\Local\Temp\vscsmoke\extensions-dir (excludes: <none>, includes: <all>)
[2022-04-08 08:56:24.706] [sharedprocess] [trace] sharedProcess configuration {"machineId":"190392021b3a154a9c1a79ebaa81fd938c04b9d62a6885ca093de07fd9c9c64b","windowId":2,"appRoot":
```

As you can see only 4 seconds after the request, the shared process config is printed:

https://github.com/microsoft/vscode/blob/a6180a732e480d4698ef10379b9628ee71ad7689/src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts#L151

**Comment by bpasero** [comment]
Enabled the tests again today and now they seem to succeed 🤯

**Comment by bpasero** [comment]
Ok starting to fail again and things are getting really interesting: since I had pushed changes to separate the log files per test run, I now see that when this error occurs, there is no `sharedprocess.log` 🔥 

This either means, shared process did not startup, or is unhealthy. I would need to add more logging around the shared process to figure out more, but this seems to be the actual problem (and not a hanging request).

**Comment by bpasero** [comment]
Hm, another possibility is that we simply did not log anything, I notice that even for normal runs the only entries are:

```
[2022-04-11 16:50:39.889] [sharedprocess] [info] RequestService#request (browser) - begin https://az764295.vo.msecnd.net/extensions/marketplace.json
[2022-04-11 16:50:39.936] [sharedprocess] [info] RequestService#request (browser) - success https://az764295.vo.msecnd.net/extensions/marketplace.json
[2022-04-11 16:50:40.642] [sharedprocess] [info] Starting worker process with pid 17803 (type: fileWatcher, window: 1).
```

I would have at least expected an entry for the file watcher though...

**Comment by sandy081** [comment]
Is it with `verbose` mode? otherwise above logs are expected.

**Comment by bpasero** [comment]
I had removed `verbose` again and now run with selected logging set to `info`, specifically:
* all request service usage
* the info message in shared process on startup to figure out if the process is alive

Interestingly all the past tests have succeeded. This really makes me feel it is time-of-day dependent.

**Comment by bpasero** [comment]
My latest theory is that https://github.com/microsoft/vscode/issues/146785 also causes this here: the shared process window waiting on a IPC call to return. I have pushed a mitigation change to `main` to see if that helps.

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/146785
