### ISSUE TITLE
Error: Decoration has no range

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#146816]
```
Version: 1.67.0-insider
Commit: 5467c8c4413be3a69960fe418d2c345bfbdf2b55
Date: 2022-04-04T05:29:30.893Z
```

I'm just typing in various files, not doing anything too special and noticed a lot of these stack traces in the console:

```
ERR Decoration has no range: Error: Decoration has no range
    at I.updateRanges (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:794:2494)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:793:198676
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at c.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:18423
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at _emitOutgoingEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:203:120288)
    at _.emitOutgoingEvent (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:203:119851)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:739:43177
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at le.endDeferredEmit (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:734:23549)
    at Ti.deltaDecorations (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:734:5038)
    at rn.deltaDecorations (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:11602)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:794:2166
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30342
    at Object.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:9:7704)
    at i (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30055)
    at clear (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30574)
    at c.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30512)
    at I.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:31113)
    at u.set value [as value] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:31452)
    at u.clear (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:31508)
    at o.clear (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:794:46009)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:793:198590
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30342
    at Object.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:9:7704)
    at i (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30055)
    at clear (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30574)
    at c.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30512)
    at p.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:31113)
    at u.set value [as value] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:31452)
    at u.clear (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:31508)
    at m.hide (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:793:197174)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:793:195808
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at c.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:18107
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at _emitOutgoingEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:203:120288)
    at _.endEmitViewEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:203:120984)
    at m._withViewEventsCollector (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:740:4898)
    at m.setCursorStates (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:740:2150)
    at G.runCoreEditorCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:686:41932)
    at A._wordSelectDrag (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:686:53981)
    at A.dispatchMouse (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:686:52440)
    at S._dispatchMouse (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:650:20283)
    at S._onMouseDownThenMove (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:650:16932)
    at A._pointerMoveCallback (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:650:18169)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:72:1530
    at gt (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:71:30402)
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:71:30510)
```

**Comment by alexdima** [comment]
Deminified using https://github.com/alexdima/vscode-stack-beautifier

ERR&nbsp;Decoration&nbsp;has&nbsp;no&nbsp;range:&nbsp;Error:&nbsp;Decoration&nbsp;has&nbsp;no&nbsp;range<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts:595:22`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L595)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts:256:21`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L256)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1651:39`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1651)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:64:17`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/viewModelEventDispatcher.ts#L64)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:39:7`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/viewModelEventDispatcher.ts#L39)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModel/viewModelImpl.ts:463:25`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/viewModel/viewModelImpl.ts#L463)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/model/textModel.ts:2626:17`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/model/textModel.ts#L2626)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/model/textModel.ts:1671:32`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/model/textModel.ts#L1671)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1289:31`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1289)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts:577:10`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L577)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:170:3`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L170)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/functional.ts:17:14`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/functional.ts#L17)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:139:7`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L139)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:214:3`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L214)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:199:7`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L199)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:255:14`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L255)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:289:15`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L289)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:297:15`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L297)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/inlineCompletions/browser/ghostTextModel.ts:162:13`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/contrib/inlineCompletions/browser/ghostTextModel.ts#L162)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts:251:14`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L251)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:170:3`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L170)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/functional.ts:17:14`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/functional.ts#L17)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:139:7`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L139)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:214:3`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L214)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:199:7`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L199)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:255:14`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L255)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:289:15`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L289)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:297:15`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/lifecycle.ts#L297)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts:189:25`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L189)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts:88:10`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L88)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1635:37`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1635)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:64:17`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/viewModelEventDispatcher.ts#L64)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:109:7`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/viewModelEventDispatcher.ts#L109)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModel/viewModelImpl.ts:1060:25`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/viewModel/viewModelImpl.ts#L1060)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModel/viewModelImpl.ts:955:14`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/common/viewModel/viewModelImpl.ts#L955)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/coreCommands.ts:1410:13`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/coreCommands.ts#L1410)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/view/viewController.ts:259:40`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/view/viewController.ts#L259)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/view/viewController.ts:174:11`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/view/viewController.ts#L174)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/controller/mouseHandler.ts:561:23`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/controller/mouseHandler.ts#L561)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/controller/mouseHandler.ts:359:8`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/controller/mouseHandler.ts#L359)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/controller/mouseHandler.ts:431:16`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./editor/browser/controller/mouseHandler.ts#L431)<br/>&nbsp;&nbsp;at&nbsp;[`./base/browser/globalPointerMoveMonitor.ts:107:9`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/browser/globalPointerMoveMonitor.ts#L107)<br/>&nbsp;&nbsp;at&nbsp;[`./base/browser/dom.ts:330:3`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/browser/dom.ts#L330)<br/>&nbsp;&nbsp;at&nbsp;[`./base/browser/dom.ts:341:4`](https://github.com/Microsoft/vscode/blob/5467c8c4413be3a69960fe418d2c345bfbdf2b55/src/vs/./base/browser/dom.ts#L341)<br/>

**Comment by meganrogge** [comment]
I don't see this when I type in files and the fix LGTM
