### ISSUE TITLE
WorkspaceEdit fails when creating then writing to file if file is open in the editor and is not empty

### ISSUE THREAD

**Issue by EhabY** [microsoft/vscode#146964]
Per the [LSP specifications](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit), one form of a common request would be create a file then write some content to it. If that file already exists then it is overwritten.

> So a workspace edit for example can consist of the following two changes: (1) create file a.txt and (2) a text document edit which insert text into file a.txt

However, this does not work if the file contains something. Because overwriting the file causes it to change which causes the next `TextDocumentEdit` to not be applied.

I was able to reproduce this with the following example:
```javascript
const we = new vscode.WorkspaceEdit();
we.createFile(uri, { overwrite: true, ignoreIfExists: false });
we.set(uri, [new vscode.TextEdit(new vscode.Range(new vscode.Position(0,0), new vscode.Position(0,0)), "SOME TEXT")]);
const isSuccessful = await vscode.workspace.applyEdit(we);
```

The following code will result in an empty file with `isSuccessful === false`. When executing it again with an empty file (or no file) it will work as expected since the file wasn't changed.

Having to delete the file (or empty it) before applying the `WorkspaceEdit` defeats the purpose of using a `WorkspaceEdit` to begin with.

**Comment by jrieken** [comment]
Using your sample (see below) works just fine for me. Can you check the output from the renderer log: F1 > Show Logs > Window

```
	vscode.commands.registerCommand('dummy', async () => {

		const uri = vscode.Uri.file('/Users/jrieken/Code/_samples/abc/test2.txt')
		const we = new vscode.WorkspaceEdit();
		we.createFile(uri, { overwrite: true, ignoreIfExists: false });
		we.set(uri, [new vscode.TextEdit(new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), "SOME TEXT")]);
		const isSuccessful = await vscode.workspace.applyEdit(we);
		console.log(isSuccessful)
	})
```

**Comment by EhabY** [comment]
For reference, I am using VS Code 1.66.0 on Windows 10. All the extensions are disabled.

```
[2022-04-07 11:39:37.284] [renderer3] [error] Error: file:///c%3A/sample-ext/test2.txt has changed in the meantime
    at i._validateBeforePrepare (vscode-file://vscode-app/c:/Users/ehaba/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:893:19404)
    at i.apply (vscode-file://vscode-app/c:/Users/ehaba/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:893:20155)
    at u._performTextEdits (vscode-file://vscode-app/c:/Users/ehaba/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:96950)
    at u.perform (vscode-file://vscode-app/c:/Users/ehaba/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:96219)
    at async apply (vscode-file://vscode-app/c:/Users/ehaba/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:98420)
[2022-04-07 11:39:37.285] [renderer3] [warning] IGNORING workspace edit {}
```

Again, if you apply the command after the failure then it work once (because the file is empty).

**Comment by jrieken** [comment]
`Error: file:///c%3A/sample-ext/test2.txt has changed in the meantime`

Applying the file create operation and making the text edits isn't atomic. In your setup there must be something that modifies the newly created file in-between these two operation. That's why the text edit fails. So, now the question is what that file. What's the kind of file you are creating? Does you extension use some `onWill` listeners?

**Comment by EhabY** [comment]
I created a new empty extension (using `yo code`) and tested the code on a newly generated file. In this case, the extension only contains the sample code I provided. Unless Windows is somehow modifying the file I have no idea.

**Comment by jrieken** [comment]
What other extensions do you have running?

**Comment by jrieken** [comment]
You have any "on save" settings? Like insert final new line etc?

**Comment by EhabY** [comment]
Nothing of the sort

**Comment by EhabY** [comment]
I just tested it on a freshly installed Windows 10 and a freshly installed Linux (Ubuntu) and the same issue happens. Both OSes use VS Code version 1.66.0. In both cases no settings were altered and nothing was installed besides VS Code and node.

If I run this command twice, the second time is not applied (It empties the file but causes the rest of the operations to fail)
```javascript
vscode.commands.registerCommand('dummy', async () => {
    const uri = vscode.Uri.file('/home/ehab/Documents/test2.txt');
    const we = new vscode.WorkspaceEdit();
    we.createFile(uri, { overwrite: true, ignoreIfExists: false });
    we.set(uri, [new vscode.TextEdit(new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), "SOME TEXT")]);
    const isSuccessful = await vscode.workspace.applyEdit(we);
    if(isSuccessful) {
        await vscode.workspace.openTextDocument(uri).then(document => document.save());
    }
    console.log(isSuccessful);
});
```

Error in Linux:
```
[2022-04-09 17:26:04.592] [renderer7] [error] Error: file:///home/ehab/Documents/test2.txt has changed in the meantime
    at i._validateBeforePrepare (vscode-file://vscode-app/snap/code/93/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:893:19404)
    at i.apply (vscode-file://vscode-app/snap/code/93/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:893:20155)
    at u._performTextEdits (vscode-file://vscode-app/snap/code/93/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:96950)
    at u.perform (vscode-file://vscode-app/snap/code/93/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:96219)
    at async apply (vscode-file://vscode-app/snap/code/93/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:98420)
[2022-04-09 17:26:04.593] [renderer7] [warning] IGNORING workspace edit {}
```

**Comment by jrieken** [comment]
Thanks for continued patience. We are now at the bottom of this. The gist is that the file needs to exist and must not be empty. I have added minimal steps down below this comment. The issue is that `createFile(uri, { overwrite: true, ignoreIfExists: false });` clears the model - that is a text operation and appears as concurrent modification. I can see what I can do here
---

* create and save `/home/ehab/Documents/test2.txt'` with some contents
* run the snippet below
* the operation fails

```ts
vscode.commands.registerCommand('dummy', async () => {
    const uri = vscode.Uri.file('/home/ehab/Documents/test2.txt');
    const we = new vscode.WorkspaceEdit();
    we.createFile(uri, { overwrite: true, ignoreIfExists: false });
    we.set(uri, [new vscode.TextEdit(new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), "SOME TEXT")]);
    const isSuccessful = await vscode.workspace.applyEdit(we);
    if(isSuccessful) {
        await vscode.workspace.openTextDocument(uri).then(document => document.save());
    }
    console.log(isSuccessful);
});
```
