### ISSUE TITLE
Opening VSCode results in a mostly blank window with some GUI outlines

### ISSUE THREAD

**Issue by g3ner1c** [microsoft/vscode#147086]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.66.1, commit 8dfae7a
- OS Version: Windows 10 Home Build 19044.1586

After updating to 1.66.1, opening VSCode results in a window with GUI outlines and boxes but no text:

![image](https://user-images.githubusercontent.com/74469257/162445526-c35a3b54-67ec-46ad-b89a-f7b793daf113.png)

Uninstalling through Windows Settings and completely removing `%appdata%\Code` then reinstalling using the user installer **works fine on the first launch and even with extensions after syncing settings, but breaks again after closing and reopening the window.**

Running without GPU and extensions with `code --disable-gpu --verbose --disable-extensions` in powershell returns:

```
[main 2022-04-08T13:43:10.288Z] [File Watcher (node.js)] Request to start watching: c:\Users\Generic\AppData\Roaming\Code\User (excludes: <none>),c:\Users\Generic\AppData\Roaming\Code\User\settings.json (excludes: <none>)
[main 2022-04-08T13:43:10.336Z] Starting VS Code
[main 2022-04-08T13:43:10.336Z] from: c:\Users\Generic\AppData\Local\Programs\Microsoft VS Code\resources\app
[main 2022-04-08T13:43:10.336Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-gpu': true,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '9ebcb2e2-12d2-4ded-8340-a07a76fa6828',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  logsPath: 'C:\\Users\\Generic\\AppData\\Roaming\\Code\\logs\\20220408T094310'
}
[main 2022-04-08T13:43:10.343Z] Resolving machine identifier...
[main 2022-04-08T13:43:10.344Z] Resolved machine identifier: fb6a7eefb72ace69186e724def265844f1c27b67f38b5e7e485cb256e7748119
[main 2022-04-08T13:43:10.347Z] Main->SharedProcess#connect
[main 2022-04-08T13:43:10.384Z] [File Watcher (node.js)] Started watching: 'c:\Users\Generic\AppData\Roaming\Code\User'
[main 2022-04-08T13:43:10.386Z] StorageMainService: creating global storage
[main 2022-04-08T13:43:10.398Z] lifecycle (main): phase changed (value: 2)
[main 2022-04-08T13:43:10.400Z] windowsManager#open
[main 2022-04-08T13:43:10.400Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\Generic\\AppData\\Roaming\\Code\\Backups\\1649425054117',
    remoteAuthority: undefined
  }
]
[main 2022-04-08T13:43:10.401Z] windowsManager#doOpenEmpty {
  restore: true,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: true
}
[main 2022-04-08T13:43:10.403Z] IPC Object URL: Registered new channel vscode:5e698aab-282f-4afb-9ccb-355ee277b287.
[main 2022-04-08T13:43:10.403Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 306, y: 78, width: 1032, height: 776 }
[main 2022-04-08T13:43:10.403Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1504, height: 1003 }
[main 2022-04-08T13:43:10.404Z] window#ctor: using window state { mode: 1, x: 306, y: 78, width: 1032, height: 776 }
[main 2022-04-08T13:43:10.488Z] window#load: attempt to load window (id: 1)
[main 2022-04-08T13:43:10.501Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2022-04-08T13:43:10.502Z] lifecycle (main): phase changed (value: 3)
[main 2022-04-08T13:43:10.513Z] update#setState idle
[main 2022-04-08T13:43:10.514Z] resolveShellEnv(): skipped (Windows)
[main 2022-04-08T13:43:10.562Z] [File Watcher (node.js)] Started watching: 'c:\Users\Generic\AppData\Roaming\Code\User\settings.json'
[main 2022-04-08T13:43:10.564Z] ExtensionHostStarterWorker created
[main 2022-04-08T13:43:10.687Z] [File Watcher (node.js)] [raw] ["change"] globalStorage
[main 2022-04-08T13:43:10.688Z] [File Watcher (node.js)] [CHANGED] c:\Users\Generic\AppData\Roaming\Code\User\globalStorage
[main 2022-04-08T13:43:10.690Z] [File Watcher (node.js)] [raw] ["change"] globalStorage
[main 2022-04-08T13:43:10.690Z] [File Watcher (node.js)] [CHANGED] c:\Users\Generic\AppData\Roaming\Code\User\globalStorage
[main 2022-04-08T13:43:10.697Z] resolveShellEnv(): skipped (Windows)
[main 2022-04-08T13:43:10.741Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\Generic\AppData\Roaming\Code\User\globalStorage
[9224:0408/094311.223:INFO:CONSOLE(1)] "[uncaught exception]: RangeError: Incorrect locale information provided", source: vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/bootstrap-window.js (1)
[9224:0408/094311.223:INFO:CONSOLE(1)] "RangeError: Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1062:14587
    at Function.i._invokeFactory (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:1626)
    at i.complete (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:1821)
    at i._onModuleComplete (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:6:991)
    at i._resolve (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:6:510)
    at i.defineModule (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:5:6142)
    at v (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:6:1702)
    at define (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:6:3234)
    at vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1062:14267
    at vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:14484", source: vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/bootstrap-window.js (1)
```

Same issue when using VSCode Insiders

Similar issue with #114459 but in this case, parts of the GUI is visible while #114459 seems to be completely blank.

**Comment by g3ner1c** [comment]
#146571 seems to be similar but on Windows 7 with a [comment experiencing problems on 1.66.0 on Windows 10](https://github.com/microsoft/vscode/issues/146571#issuecomment-1086472934):
![image](https://user-images.githubusercontent.com/74469257/162452493-022378d3-28b6-4854-a8ce-bff1414d7ef7.png)

@Spirtea if you don't mind, have you found a consistent fix to this?

**Comment by deepak1556** [comment]
Can you provide the output of `code-insiders --verbose` as well

**Comment by g3ner1c** [comment]
`code-insiders --verbose` on a fresh install of VSCode Insiders after closing the initial launch window to reproduce the bug:
```
[main 2022-04-08T15:41:56.710Z] [File Watcher (node.js)] Request to start watching: c:\Users\Generic\AppData\Roaming\Code - Insiders\User (excludes: <none>, includes: <all>),c:\Users\Generic\AppData\Roaming\Code - Insiders\User\settings.json (excludes: <none>, includes: <all>)
[main 2022-04-08T15:41:56.739Z] Starting VS Code
[main 2022-04-08T15:41:56.740Z] from: c:\Users\Generic\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app
[main 2022-04-08T15:41:56.740Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'e65cd47b-a607-4945-a7f9-c629853ac646',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  logsPath: 'C:\\Users\\Generic\\AppData\\Roaming\\Code - Insiders\\logs\\20220408T114156'
}
[main 2022-04-08T15:41:56.743Z] Resolving machine identifier...
[main 2022-04-08T15:41:56.744Z] Resolved machine identifier: fb6a7eefb72ace69186e724def265844f1c27b67f38b5e7e485cb256e7748119
[main 2022-04-08T15:41:56.746Z] Main->SharedProcess#connect
[main 2022-04-08T15:41:56.770Z] [File Watcher (node.js)] Started watching: 'c:\Users\Generic\AppData\Roaming\Code - Insiders\User'
[main 2022-04-08T15:41:56.777Z] [File Watcher (node.js)] Started watching: 'c:\Users\Generic\AppData\Roaming\Code - Insiders\User\settings.json'
[main 2022-04-08T15:41:56.780Z] StorageMainService: creating global storage
[main 2022-04-08T15:41:56.790Z] lifecycle (main): phase changed (value: 2)
[main 2022-04-08T15:41:56.792Z] windowsManager#open
[main 2022-04-08T15:41:56.792Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\Generic\\AppData\\Roaming\\Code - Insiders\\Backups\\1649432500382',
    remoteAuthority: undefined
  }
]
[main 2022-04-08T15:41:56.794Z] windowsManager#doOpenEmpty {
  restore: true,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: true
}
[main 2022-04-08T15:41:56.796Z] IPC Object URL: Registered new channel vscode:0e52c059-56ca-476a-9235-31041b1a3ec2.
[main 2022-04-08T15:41:56.797Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 240, y: 118, width: 1024, height: 770 }
[main 2022-04-08T15:41:56.797Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1504, height: 1003 }
[main 2022-04-08T15:41:56.798Z] window#ctor: using window state { mode: 1, x: 240, y: 118, width: 1024, height: 770 }[main 2022-04-08T15:41:56.883Z] window#load: attempt to load window (id: 1)
[main 2022-04-08T15:41:56.899Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2022-04-08T15:41:56.899Z] lifecycle (main): phase changed (value: 3)
[main 2022-04-08T15:41:56.910Z] update#setState idle
[main 2022-04-08T15:41:56.916Z] resolveShellEnv(): skipped (Windows)
[main 2022-04-08T15:41:56.976Z] ExtensionHostStarterWorker created
[main 2022-04-08T15:41:57.093Z] resolveShellEnv(): skipped (Windows)
[main 2022-04-08T15:41:57.113Z] [File Watcher (node.js)] [raw] ["change"] globalStorage
[main 2022-04-08T15:41:57.114Z] [File Watcher (node.js)] [CHANGED] c:\Users\Generic\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2022-04-08T15:41:57.115Z] [File Watcher (node.js)] [raw] ["change"] globalStorage
[main 2022-04-08T15:41:57.115Z] [File Watcher (node.js)] [CHANGED] c:\Users\Generic\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2022-04-08T15:41:57.172Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\Generic\AppData\Roaming\Code - Insiders\User\globalStorage
[3216:0408/114157.663:INFO:CONSOLE(1)] "[uncaught exception]: RangeError: Incorrect locale information provided", source: vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/bootstrap-window.js (1)
[3216:0408/114157.664:INFO:CONSOLE(1)] "RangeError: Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1062:14614
    at Function.i._invokeFactory (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/loader.js:5:1626)
    at i.complete (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/loader.js:5:1821)
    at i._onModuleComplete (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/loader.js:6:991)
    at i._resolve (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/loader.js:6:510)
    at i.defineModule (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/loader.js:5:6142)
    at v (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/loader.js:6:1702)
    at define (vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/loader.js:6:3234)
    at vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1062:14294
    at vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3146:14443", source: vscode-file://vscode-app/c:/Users/Generic/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/bootstrap-window.js (1)
```
![image](https://user-images.githubusercontent.com/74469257/162477034-2a0ca36d-d06e-4176-a0c3-37ff533218a2.png)

**Comment by bpasero** [comment]
Thanks for analysis Deepak 👍
