### ISSUE TITLE
/usr/bin/env: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by wangxudong-cq** [microsoft/vscode#147191]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.66.1(8dfae7a5cd50421d10cd99cb873990460525a898)
- OS Version:8dfae7a5cd50421d10cd99cb873990460525a898

Steps to Reproduce:

1.connect to ubuntu 18.04 via ssh-remote

Log:

```
[09:42:13.327] Log Level: 2
[09:42:13.329] remote-ssh@0.78.0
[09:42:13.329] win32 x64
[09:42:13.334] SSH Resolver called for "ssh-remote+ubuntu@106.55.40.102", attempt 1
[09:42:13.335] "remote.SSH.useLocalServer": false
[09:42:13.335] "remote.SSH.showLoginTerminal": false
[09:42:13.335] "remote.SSH.remotePlatform": {"ubuntu18.04":"linux","Azurengine.site":"linux","221.4.216.35":"linux","ubuntu18.04_wang":"linux","ubuntu18.04_ubuntu":"linux","192.168.2.115":"linux"}
[09:42:13.335] "remote.SSH.path": undefined
[09:42:13.335] "remote.SSH.configFile": undefined
[09:42:13.335] "remote.SSH.useFlock": true
[09:42:13.336] "remote.SSH.lockfilesInTmp": false
[09:42:13.336] "remote.SSH.localServerDownload": auto
[09:42:13.336] "remote.SSH.remoteServerListenOnSocket": false
[09:42:13.336] "remote.SSH.showLoginTerminal": false
[09:42:13.336] "remote.SSH.defaultExtensions": []
[09:42:13.336] "remote.SSH.loglevel": 2
[09:42:13.336] "remote.SSH.enableDynamicForwarding": true
[09:42:13.336] "remote.SSH.enableRemoteCommand": false
[09:42:13.336] "remote.SSH.serverPickPortsFromRange": {}
[09:42:13.336] "remote.SSH.serverInstallPath": {}
[09:42:13.351] SSH Resolver called for host: ubuntu@106.55.40.102
[09:42:13.351] Setting up SSH remote "106.55.40.102"
[09:42:13.355] Using commit id "8dfae7a5cd50421d10cd99cb873990460525a898" and quality "stable" for server
[09:42:13.360] Install and start server if needed
[09:42:16.830] Checking ssh with "ssh -V"
[09:42:16.857] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[09:42:16.860] Running script with connection command: ssh -T -D 51534 "ubuntu@106.55.40.102" bash
[09:42:16.863] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:42:17.058] > ]0;C:\WINDOWS\System32\cmd.exe
[09:42:17.058] Got some output, clearing connection timeout
[09:42:17.650] > 86385d398685: running
[09:42:17.673] > Acquiring lock on /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-remote-lock.ubuntu.8dfae7a5cd50421d10cd99cb873990460525a898
> Found existing installation at /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898...
> Checking /home/ubuntu/.vscode-server/.8dfae7a5cd50421d10cd99cb873990460525a898.log and /home/ubuntu/.vscode-server/.8dfae7a5cd50421d10cd99cb873990460525a898.pid for a running server
> Looking for server with pid: 12618
[09:42:17.690] > Starting server with command... /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/ubuntu/.vscode-server/.8dfae7a5cd50421d10cd99cb873990460525a898.log" < /dev/null
> printenv:
>     CONDA_SHLVL=2
>     CONDA_EXE=/usr/local/anaconda3/bin/conda
>     SSH_CONNECTION=58.250.250.99 51545 172.16.1.159 22
>     CONDA_PREFIX=/usr/local/anaconda3/envs/ubuntu
>     _CE_M=
>     XDG_SESSION_ID=195214
>     USER=ubuntu
>     CONDA_PREFIX_1=/usr/local/anaconda3
>     PWD=/home/ubuntu
>     HOME=/home/ubuntu
>     CONDA_PYTHON_EXE=/usr/local/anaconda3/bin/python
>     SSH_CLIENT=58.250.250.99 51545 22
>     _CE_CONDA=
>     CONDA_PROMPT_MODIFIER=(ubuntu) 
>     MAIL=/var/mail/ubuntu
>     SHELL=/bin/bash
>     SHLVL=2
>     VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server
>     LOGNAME=ubuntu
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/500/bus
>     XDG_RUNTIME_DIR=/run/user/500
>     PATH=/usr/local/anaconda3/envs/ubuntu/bin:/usr/local/anaconda3/condabin:/usr
> r/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/g
> games:/snap/bin
>     CONDA_DEFAULT_ENV=ubuntu
>     _=/usr/bin/printenv
> Removing old logfile at /home/ubuntu/.vscode-server/.8dfae7a5cd50421d10cd99cb873
> 3990460525a898.log
> Spawned remote server: 18791
[09:42:17.697] > 
> Waiting for server log...
[09:42:17.706] > 
[09:42:17.730] > Waiting for server log...
[09:42:17.762] > Waiting for server log...
[09:42:17.795] > Waiting for server log...
[09:42:17.828] > Waiting for server log...
[09:42:17.862] > Waiting for server log...
[09:42:17.896] > Waiting for server log...
[09:42:17.948] > Waiting for server log...
[09:42:18.055] > Waiting for server log...
> Waiting for server log...
[09:42:18.071] > Waiting for server log...
> Waiting for server log...
[09:42:18.123] > 
[09:42:18.130] > Waiting for server log...
> Waiting for server log...
[09:42:18.149] > 
[09:42:18.169] > Waiting for server log...
[09:42:18.194] > Waiting for server log...
[09:42:18.224] > Waiting for server log...
[09:42:18.258] > Waiting for server log...
[09:42:18.290] > Waiting for server log...
[09:42:18.322] > Waiting for server log...
[09:42:18.328] > 
[09:42:18.356] > Waiting for server log...
[09:42:18.390] > Waiting for server log...
[09:42:18.422] > Waiting for server log...
[09:42:18.455] > Waiting for server log...
[09:42:18.488] > Waiting for server log...
[09:42:18.520] > Waiting for server log...
[09:42:18.553] > Waiting for server log...
[09:42:18.589] > Waiting for server log...
[09:42:18.619] > Waiting for server log...
[09:42:18.651] > Waiting for server log...
[09:42:18.685] > Waiting for server log...
[09:42:18.718] > Waiting for server log...
[09:42:18.750] > Waiting for server log...
[09:42:18.784] > Waiting for server log...
[09:42:18.816] > Waiting for server log...
[09:42:18.848] > Waiting for server log...
[09:42:18.881] > Waiting for server log...
[09:42:18.918] > Waiting for server log...
[09:42:18.948] > Waiting for server log...
[09:42:18.981] > Waiting for server log...
[09:42:19.013] > Waiting for server log...
[09:42:19.051] > Waiting for server log...
[09:42:19.080] > Waiting for server log...
[09:42:19.114] > Waiting for server log...
[09:42:19.146] > Waiting for server log...
[09:42:19.180] > Waiting for server log...
[09:42:19.212] > Waiting for server log...
[09:42:19.248] > Waiting for server log...
[09:42:19.280] > Waiting for server log...
[09:42:19.314] > Waiting for server log...
[09:42:19.346] > Waiting for server log...
[09:42:19.379] > Waiting for server log...
[09:42:19.412] > Waiting for server log...
[09:42:19.445] > Waiting for server log...
[09:42:19.478] > Waiting for server log...
[09:42:19.510] > Waiting for server log...
[09:42:19.544] > Waiting for server log...
[09:42:19.577] > Waiting for server log...
[09:42:19.609] > Waiting for server log...
[09:42:19.643] > Waiting for server log...
[09:42:19.673] > Waiting for server log...
[09:42:19.707] > Waiting for server log...
[09:42:19.742] > Waiting for server log...
[09:42:19.774] > Waiting for server log...
[09:42:19.806] > Waiting for server log...
[09:42:19.843] > Waiting for server log...
[09:42:19.871] > Waiting for server log...
[09:42:19.905] > Waiting for server log...
[09:42:19.937] > Waiting for server log...
[09:42:19.969] > Waiting for server log...
[09:42:20.003] > Waiting for server log...
[09:42:20.040] > Waiting for server log...
[09:42:20.069] > Waiting for server log...
[09:42:20.101] > Waiting for server log...
[09:42:20.136] > Waiting for server log...
[09:42:20.169] > Waiting for server log...
[09:42:20.202] > Waiting for server log...
[09:42:20.237] > Waiting for server log...
[09:42:20.267] > Waiting for server log...
[09:42:20.303] > Waiting for server log...
[09:42:20.336] > Waiting for server log...
[09:42:20.368] > Waiting for server log...
[09:42:20.402] > Waiting for server log...
[09:42:20.435] > Waiting for server log...
[09:42:20.467] > Waiting for server log...
[09:42:20.501] > Waiting for server log...
[09:42:20.533] > Waiting for server log...
[09:42:20.567] > Waiting for server log...
[09:42:20.599] > Waiting for server log...
[09:42:20.634] > Waiting for server log...
[09:42:20.664] > Waiting for server log...
[09:42:20.700] > Waiting for server log...
[09:42:20.731] > Waiting for server log...
[09:42:20.737] > 
[09:42:20.765] > Waiting for server log...
[09:42:20.797] > Waiting for server log...
[09:42:20.831] > Waiting for server log...
[09:42:20.864] > Waiting for server log...
[09:42:20.895] > Waiting for server log...
[09:42:20.931] > Waiting for server log...
[09:42:20.964] > Waiting for server log...
[09:42:20.998] > Waiting for server log...
[09:42:21.028] > Waiting for server log...
[09:42:21.061] > Waiting for server log...
[09:42:21.095] > Waiting for server log...
[09:42:21.127] > Waiting for server log...
[09:42:21.161] > Waiting for server log...
[09:42:21.195] > Waiting for server log...
[09:42:21.229] > Waiting for server log...
[09:42:21.259] > Waiting for server log...
[09:42:21.291] > Waiting for server log...
[09:42:21.326] > Waiting for server log...
[09:42:21.361] > Waiting for server log...
[09:42:21.392] > Waiting for server log...
[09:42:21.422] > Waiting for server log...
[09:42:21.457] > Waiting for server log...
[09:42:21.489] > Waiting for server log...
[09:42:21.523] > Waiting for server log...
[09:42:21.557] > Waiting for server log...
[09:42:21.588] > Waiting for server log...
[09:42:21.622] > Waiting for server log...
[09:42:21.655] > Waiting for server log...
[09:42:21.688] > Waiting for server log...
[09:42:21.721] > Waiting for server log...
[09:42:21.755] > Waiting for server log...
[09:42:21.785] > Waiting for server log...
[09:42:21.821] > Waiting for server log...
[09:42:21.852] > Waiting for server log...
[09:42:21.883] > Waiting for server log...
[09:42:21.919] > Waiting for server log...
[09:42:21.951] > Waiting for server log...
[09:42:21.984] > Waiting for server log...
[09:42:22.018] > Waiting for server log...
[09:42:22.049] > Waiting for server log...
[09:42:22.082] > Waiting for server log...
[09:42:22.116] > Waiting for server log...
[09:42:22.149] > Waiting for server log...
[09:42:22.180] > Waiting for server log...
[09:42:22.215] > Waiting for server log...
[09:42:22.249] > Waiting for server log...
[09:42:22.280] > Waiting for server log...
[09:42:22.315] > Waiting for server log...
[09:42:22.346] > Waiting for server log...
[09:42:22.380] > Waiting for server log...
[09:42:22.414] > Waiting for server log...
[09:42:22.446] > Waiting for server log...
[09:42:22.479] > Waiting for server log...
[09:42:22.510] > Waiting for server log...
[09:42:22.544] > Waiting for server log...
[09:42:22.579] > Waiting for server log...
[09:42:22.609] > Waiting for server log...
[09:42:22.617] > 
[09:42:22.641] > Waiting for server log...
[09:42:22.676] > Waiting for server log...
[09:42:22.708] > Waiting for server log...
[09:42:22.742] > Waiting for server log...
[09:42:22.773] > Waiting for server log...
[09:42:22.806] > Waiting for server log...
[09:42:22.840] > Waiting for server log...
[09:42:22.872] > Waiting for server log...
[09:42:22.904] > Waiting for server log...
[09:42:22.937] > Waiting for server log...
[09:42:22.971] > Waiting for server log...
[09:42:23.002] > Waiting for server log...
[09:42:23.039] > Waiting for server log...
[09:42:23.071] > Waiting for server log...
[09:42:23.103] > Waiting for server log...
[09:42:23.135] > Waiting for server log...
[09:42:23.169] > Waiting for server log...
[09:42:23.201] > Waiting for server log...
[09:42:23.233] > Waiting for server log...
[09:42:23.265] > Waiting for server log...
[09:42:23.299] > Waiting for server log...
[09:42:23.334] > Waiting for server log...
[09:42:23.367] > Waiting for server log...
[09:42:23.401] > Waiting for server log...
[09:42:23.431] > Waiting for server log...
[09:42:23.464] > Waiting for server log...
[09:42:23.471] > 
[09:42:23.497] > Waiting for server log...
[09:42:23.532] > Waiting for server log...
[09:42:23.563] > Waiting for server log...
[09:42:23.596] > Waiting for server log...
[09:42:23.631] > Waiting for server log...
[09:42:23.662] > Waiting for server log...
[09:42:23.695] > Waiting for server log...
[09:42:23.730] > Waiting for server log...
[09:42:23.762] > Waiting for server log...
[09:42:23.793] > Waiting for server log...
[09:42:23.829] > Waiting for server log...
[09:42:23.861] > Waiting for server log...
[09:42:23.867] > 
[09:42:23.895] > Waiting for server log...
[09:42:23.926] > Waiting for server log...
[09:42:23.960] > Waiting for server log...
[09:42:23.993] > Waiting for server log...
[09:42:24.024] > Waiting for server log...
[09:42:24.056] > Waiting for server log...
[09:42:24.092] > Waiting for server log...
[09:42:24.123] > Waiting for server log...
[09:42:24.157] > Waiting for server log...
[09:42:24.189] > Waiting for server log...
[09:42:24.223] > Waiting for server log...
[09:42:24.258] > Waiting for server log...
[09:42:24.294] > Waiting for server log...
[09:42:24.320] > Waiting for server log...
[09:42:24.355] > Waiting for server log...
[09:42:24.389] > Waiting for server log...
[09:42:24.421] > Waiting for server log...
[09:42:24.455] > Waiting for server log...
[09:42:24.487] > Waiting for server log...
[09:42:24.519] > Waiting for server log...
[09:42:24.553] > Waiting for server log...
[09:42:24.584] > Waiting for server log...
[09:42:24.621] > Waiting for server log...
[09:42:24.651] > Waiting for server log...
[09:42:24.658] > 
[09:42:24.683] > Waiting for server log...
[09:42:24.719] > Waiting for server log...
[09:42:24.749] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> Server did not start successfully. Full server log at /home/ubuntu/.vscode-serve
> er/.8dfae7a5cd50421d10cd99cb873990460525a898.log >>>
> main: /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/b
> bin/code-server: /usr/bin/env: bad interpreter: No such file or directory        
> <<< End of server log
> 86385d398685: start
> exitCode==32==
> listeningOn====
[09:42:24.755] > 
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/500==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7059==
> 86385d398685: end
[09:42:24.755] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/500==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7059==

[09:42:24.756] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:585975)
	at p (c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:579824)
	at Object.t.handleInstallOutput (c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:583109)
	at Object.t.tryInstall (c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:681924)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:644564
	at async Object.t.withShowDetailsEvent (c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:647909)
	at async Object.t.resolve (c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:645643)
	at async c:\Users\huaih\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:722950
[09:42:24.760] ------




[09:42:25.148] > 
[09:42:26.044] "install" terminal command done
[09:42:26.045] Install terminal quit with output: 

```

**Comment by roblourens** [comment]
> /usr/bin/env: bad interpreter: No such file or directory   

Haven't seen that one before. Does /usr/bin/env exist?

**Comment by meister-reservoir** [comment]
I have the exact same issue, and both client and servers have /usr/bin/env

**Comment by Hesamp** [comment]
This problem occurs in the current version and if you downgrade to the previous version, the problem will be solved.

**Comment by alessio4tech** [comment]
Same here with a variation on a theme. Reverting to 1.65 solved the issue.

[20:13:28.027] Server installation process already in progress - waiting and retrying
[20:13:29.035] Running script with connection command: ssh -T -D 52017 xxxx bash
[20:13:29.038] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:13:29.306] > ]0;C:\WINDOWS\System32\cmd.exe
[20:13:29.306] Got some output, clearing connection timeout
[20:13:30.063] "install" terminal command done
[20:13:30.063] Install terminal quit with output: 
[20:13:31.034] > f167f9970bd1: running
[20:13:31.045] > Acquiring lock on /home/centos/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61ae
> e4b6d56977/vscode-remote-lock.centos.dfd34e8260c270da74b5c2d86d61aee4b6d56977   
> \ln /home/centos/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/vsc
> ode-remote-lock.centos.dfd34e8260c270da74b5c2d86d61aee4b6d56977.target /home/cen
> tos/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/vscode-remote-lo
> ck.centos.dfd34e8260c270da74b5c2d86d61aee4b6d56977
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFloc
> k setting
> ln: failed to create hard link ‘/home/centos/.vscode-server/bin/dfd34e8260c270da
> 74b5c2d86d61aee4b6d56977/vscode-remote-lock.centos.dfd34e8260c270da74b5c2d86d61a
> ee4b6d56977’: File exists
> f167f9970bd1: start
> exitCode==24==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> f167f9970bd1: end
[20:13:31.046] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[20:13:31.046] Server installation process already in progress - waiting and retrying

**Comment by roblourens** [comment]
@alessio4tech that's not this issue

**Comment by roblourens** [comment]
@meister-reservoir that also doesn't sound like the same issue necessarily since the server actually started in your case.

**Comment by wangxudong-cq** [comment]
> > /usr/bin/env: bad interpreter: No such file or directory
> 
> Haven't seen that one before. Does /usr/bin/env exist?

sorry,/usr/bin/env not exist!
"sudo apt-get install --reinstall coreutils"
The file usr/bin/env has been restored through the above command, and the this issue has been solved, thank you all!
