### ISSUE TITLE
Crash when opening notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147262]
```
"[uncaught exception]: TypeError: setTimeout(...).unref is not a function", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/bootstrap-window.js (1)
[74516:0411/160346.319935:INFO:CONSOLE(1)] "TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/applicationinsights/out/Library/Sender.js:100:117)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/bootstrap-window.js (1)
[main 2022-04-11T23:03:52.191Z] CodeWindow: detected unresponsive


#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 188720663
#
#
#
#FailureMessage Object: 0x7ff7b96e24e00   Electron Framework                  0x0000000112576b39 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 7271913
1   Electron Framework                  0x00000001124da873 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 6632227
2   Electron Framework                  0x0000000113d4879d v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 32248397
3   Electron Framework                  0x00000001137b6e31 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 26409185
4   Electron Framework                  0x00000001113c15aa v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray(int, v8::internal::AllocationType) + 266
5   Electron Framework                  0x00000001115e960f v8::internal::ElementsKindToByteSize(v8::internal::ElementsKind) + 80991
6   Electron Framework                  0x00000001115e7f31 v8::internal::ElementsKindToByteSize(v8::internal::ElementsKind) + 75137
7   Electron Framework                  0x000000011183a1b5 v8::internal::RegExp::CompileForTesting(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::RegExpFlag, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool) + 12405
8   ???                                 0x0000003c07f0a938 0x0 + 257831250232
[0411/160356.198650:ERROR:directory_reader_posix.cc(42)] opendir /Users/roblou/Library/Application Support/Code - Insiders/Crashpad/attachments/554cf3f5-aac4-47cb-8b72-fa2f87453698: No such file or directory (2)
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[main 2022-04-11T23:03:56.401Z] CodeWindow: renderer process crashed (reason: crashed, code: 5)
[main 2022-04-11T23:03:56.586Z] Extension host with pid 74990 exited with code: 0, signal: null.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:169:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:165:2494)
    at w.send (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:10312)
    at c.sendBuffer (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:5206)
    at c.send (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:5146)
    at c.sendResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:5001)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:340
    at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:145)
    at C.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:2271)
    at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1849)
    at p._handleEventMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:18:40888)
    at p._handleMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:18:39868)
    at p.handleMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:18:39661)
    at Worker.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:18:41470)
    at Worker.emit (node:events:390:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:169:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:165:2494)
    at w.send (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:10312)
    at c.sendBuffer (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:5206)
    at c.send (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:5146)
    at c.sendResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:5001)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:340
    at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:145)
    at C.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:2271)
    at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1849)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:54618
    at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:145)
    at C.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:2271)
    at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1849)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:53590
    at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:145)
    at C.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:2271)
    at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1849)
    at App._ (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:55318)
    at App.emit (node:events:402:35)
    at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:37:560)
    at BrowserWindow.emit (node:events:390:28)
```

**Comment by roblourens** [comment]
> [0411/160356.198650:ERROR:directory_reader_posix.cc(42)] opendir /Users/roblou/Library/Application Support/Code - Insiders/Crashpad/attachments/554cf3f5-aac4-47cb-8b72-fa2f87453698: No such file or directory (2)


I think I don't have a crash dump? Where else should I look?

**Comment by bpasero** [comment]
The `setTimeout.unref` is not new, see: https://github.com/microsoft/vscode/issues/140624

As for crash dumps, refer to: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

**Comment by roblourens** [comment]
Oh yeah. Dumps:
[Archive.zip](https://github.com/microsoft/vscode/files/8475484/Archive.zip)

**Comment by deepak1556** [comment]
Crash due to FATAL check with array allocation https://source.chromium.org/chromium/chromium/src/+/main:v8/src/heap/factory-base.cc;l=102-105, array length on 64 bit system is (1024 MB / pointer size), from the error there seems to be attempt to OOB array allocation.

```
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 188720663
#
```

From the stack trace it seems to happen after a file read operation, to narrow down the issue next step would be to take a memory allocation profile.

**Comment by roblourens** [comment]
Sorry, how do I do that? A snapshot through devtools or something else?

**Comment by roblourens** [comment]
Ok, but since the window crashes, I think I can't retrieve that profile

**Comment by deepak1556** [comment]
Does it crash for any cell execution even on a simple notebook or does it depend on the size of the output ?

**Comment by roblourens** [comment]
Size of the output doesn't matter, it seems like any output will trigger it.
