### ISSUE TITLE
Updating Extension from Command Line Throws Error

### ISSUE THREAD

**Issue by navneethc** [microsoft/vscode#147215]
Issue Type: <b>Bug</b>

I wish to update extensions from the command line using the `code` command. 

## Steps to reproduce
1. Open terminal emulator (Windows Terminal running WSL Ubuntu 20.04)
2. Run `code --install-extension --force <ext-id>` 

Examples:

```
❮ code --install-extension --force matklad.rust-analyzer
The factory method of "vs/server/node/server.cli" has thrown an exception
TypeError: F.install-extension?.forEach is not a function
    at j (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/server/node/server.cli.js:12:4313)
    at Object.<anonymous> (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/server/node/server.cli.js:12:8193)
    at Function.i._safeInvokeFunction (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1337)
    at Function.i._invokeFactory (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1584)
    at i.complete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1821)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:991)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._resolve (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:510)
    at i.defineModule (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:6142)
    at o (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:10603)
    at Object._ (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:6868)
    at Function.i._safeInvokeFunction (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1337)
    at Function.i._invokeFactory (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1584)
    at i.complete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1821)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:991)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._resolve (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:510)
    at i.defineModule (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:6142)
    at v (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1702)
    at g (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/server/node/server.cli.nls.js:3:61)
    at e._createAndEvalScript (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:4:2598)
    at /home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:4:2237
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  phase: 'factory',
  moduleId: 'vs/server/node/server.cli'
}
~
```

```
❯ code --install-extension --force ms-python.python
The factory method of "vs/server/node/server.cli" has thrown an exception
TypeError: F.install-extension?.forEach is not a function
    at j (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/server/node/server.cli.js:12:4313)
    at Object.<anonymous> (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/server/node/server.cli.js:12:8193)
    at Function.i._safeInvokeFunction (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1337)
    at Function.i._invokeFactory (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1584)
    at i.complete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1821)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:991)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._resolve (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:510)
    at i.defineModule (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:6142)
    at o (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:10603)
    at Object._ (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:6868)
    at Function.i._safeInvokeFunction (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1337)
    at Function.i._invokeFactory (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1584)
    at i.complete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:1821)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:991)
    at i._onModuleComplete (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1235)
    at i._resolve (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:510)
    at i.defineModule (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:5:6142)
    at v (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:6:1702)
    at g (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/server/node/server.cli.nls.js:3:61)
    at e._createAndEvalScript (/home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:4:2598)
    at /home/navneethc/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/vs/loader.js:4:2237
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  phase: 'factory',
  moduleId: 'vs/server/node/server.cli'
}
```

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|12.36GB (11.88GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.66.0
material-icon-theme|PKi|4.15.0
vim|vsc|1.22.2
rust-analyzer|mat|0.2.1002
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
vscode-thunder-client|ran|1.14.4
vscode-fileutils|sle|3.5.0

(2 theme extensions excluded)

</details>

**Comment by KangOxford** [comment]
I have the same problem

**Comment by aeschli** [comment]
You need to list the extension name behind `--install-extension`:
`code --install-extension ms-python.python --force`

**Comment by navneethc** [comment]
> You need to list the extension name behind `--install-extension`:
> `code --install-extension ms-python.python --force`

Thanks, this works! It would help if this requirement was made explicit in the man page. 

```
--install-extension <ext-id | path> Installs or updates an extension. The argument is either an extension id or a path to a VSIX. The identifier of an extension is '${publisher}.${name}'. Use '--force' argument to update to latest version. To install a specific version provide '@${version}'. For example: 'vscode.csharp@1.2.3'.
```

**Comment by aeschli** [comment]
I created #150714 to give a warning when using `--install-extension` without an argument,

**Comment by meganrogge** [comment]
Is this not released yet @aeschli ? I don't see a warning when I run 

`code --install-extension --force` or `code-insiders --install-extension --force`

**Comment by joyceerhl** [comment]
Works as expected for me, no error thrown and I also see the warning:

![image](https://user-images.githubusercontent.com/30305945/171906806-77ee03ee-55b2-497a-ac4b-22729b971cd2.png)
