### ISSUE TITLE
Language identifiers are sometimes `string[]` and not `string`

### ISSUE THREAD

**Issue by mahish** [microsoft/vscode#147284]
Issue Type: <b>Bug</b>

The issue does happen in single project only. I cannot identify since when it is happening (whether the last vscode update or some extension install) but it worked with any problems for several months until last week or two. Developer tools returns an error on opening the "Go to file" dialog as well as for any subsequent keystrokes within the dialog. The returned error message: `C.replace is not a function: TypeError: C.replace is not a function vscode` 

See short video here https://gyazo.com/7243dcc3b71a9348496d0543bb0480ea

I tried to disable the most recently installed extensions (mostly related to container development). Restarted vscode. Neither has helped.

Thanks.

VS Code version: Code 1.66.1 (Universal) (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:47.400Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.90GB free)|
|Process Argv|--crash-reporter-id c6d65d1b-1afa-4134-bed6-0f2f4d2a60ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
pug|ama|1.0.1
icons-carbon|ant|0.2.4
atlascode|atl|2.10.11
unique-lines|bib|1.0.0
better-toml|bun|0.3.2
visubezier|chr|1.4.0
vscode-sql-beautify|cla|0.3.5
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
json-tools|eri|1.0.2
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
soot-theme|han|0.1.3
minify|Hoo|0.4.3
vscode-react-typescript|inf|1.3.1
vscode-env|Iro|0.1.0
vscode-placeholder-images|Jak|0.1.0
ts|Jeo|0.0.1
vscode-peacock|joh|4.0.1
scss-bem-support|jol|0.0.6
vscode-phpfmt|kok|1.0.31
nunjucks-vscode-snippets|luw|0.0.7
CamelCase|Mar|1.0.5
twig-language-2|mbl|0.9.2
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.17
vscode-duplicate|mrm|1.2.1
vscode-json5|mrm|1.0.0
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
remote-containers|ms-|0.231.5
remote-ssh|ms-|0.78.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.5449
language-liquid|nei|0.1.1
vs-slug|nep|1.0.1
uuid-generator|net|0.0.5
vscode-nunjucks-formatter|oki|0.1.3
es6-css-minify|olb|3.3.3
open-html-in-browser|pea|2.1.9
material-product-icons|PKi|1.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
nunjucks|ron|0.3.1
ActiveFileInStatusBar|Ros|1.0.3
partial-diff|ryu|1.4.3
html5-boilerplate|sid|1.1.1
js-jsx-snippets|sky|11.0.0
vscode-fileutils|sle|3.5.0
printtimestamp|sno|0.1.0
addDocComments|ste|0.0.8
svelte-vscode|sve|105.15.0
open-in-browser|tec|2.0.0
pdf|tom|1.2.0
vscode-typescript-destructure-plugin|tus|0.0.10
lorem-ipsum|Tyr|1.3.1
todo-md|use|2.9.2
gitblame|wad|8.1.0
vscode-todo-highlight|way|1.0.5
twig|wha|1.0.2
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.26.0
php-pack|xde|1.0.3
json|Zai|2.0.2
php-intellisense|zob|1.0.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
vscaat:30438848
pynewfile477:30463512

```

</details>

**Comment by mahish** [comment]
I tried to disable all extensions. Did not help.

**Comment by mahish** [comment]
@bpasero Thanks for reply. Here it is:
```
ERR C.replace is not a function: TypeError: C.replace is not a function
    at v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:610:98737)
    at D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:610:98259)
    at vi.createAnythingPick (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2647:16110)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2647:9777
    at Array.map (<anonymous>)
    at vi.getEditorHistoryPicks (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2647:9765)
    at vi.doGetPicks (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2647:8597)
    at vi._getPicks (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2647:8273)
    at S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:610:78639)
    at vi.provide (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:610:79608)
    at vi.provide (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2647:7229)
    at v.doShowOrPick (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:616:35399)
    at v.show (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:616:34178)
    at handler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:796:35656)
    at I.handler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:587:7667)
    at v.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:607:319)
    at v._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1680:3664)
    at v.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1680:3021)
    at Hn._doDispatch (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:609:7211)
    at Hn._dispatch (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:609:4977)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1711:3535
```

**Comment by bpasero** [comment]
Using @alexdima nice stack tool, this is the stack:

ERR C.replace is not a function: TypeError: C.replace is not a function
  at [./editor/common/services/getIconClasses.ts:114:12](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/editor/common/services/getIconClasses.ts#L114)
  at [./editor/common/services/getIconClasses.ts:67:20](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/editor/common/services/getIconClasses.ts#L67)
  at [./workbench/contrib/search/browser/anythingQuickAccess.ts:898:31](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L898)
  at [./workbench/contrib/search/browser/anythingQuickAccess.ts:438:62](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L438)
  at [./workbench/contrib/search/browser/anythingQuickAccess.ts:438:43](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L438)
  at [./workbench/contrib/search/browser/anythingQuickAccess.ts:344:34](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L344)
  at [./workbench/contrib/search/browser/anythingQuickAccess.ts:319:14](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L319)
  at [./platform/quickinput/browser/pickerQuickAccess.ts:125:30](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/quickinput/browser/pickerQuickAccess.ts#L125)
  at [./platform/quickinput/browser/pickerQuickAccess.ts:266:2](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/quickinput/browser/pickerQuickAccess.ts#L266)
  at [./workbench/contrib/search/browser/anythingQuickAccess.ts:236:24](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L236)
  at [./platform/quickinput/browser/quickAccess.ts:132:28](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/quickinput/browser/quickAccess.ts#L132)
  at [./platform/quickinput/browser/quickAccess.ts:40:7](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/quickinput/browser/quickAccess.ts#L40)
  at [./workbench/browser/actions/quickAccessActions.ts:139:32](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/browser/actions/quickAccessActions.ts#L139)
  at [./platform/commands/common/commands.ts:90:11](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/commands/common/commands.ts#L90)
  at [./platform/instantiation/common/instantiationService.ts:61:10](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/instantiation/common/instantiationService.ts#L61)
  at [./workbench/services/commands/common/commandService.ts:95:45](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/services/commands/common/commandService.ts#L95)
  at [./workbench/services/commands/common/commandService.ts:60:16](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/services/commands/common/commandService.ts#L60)
  at [./platform/keybinding/common/abstractKeybindingService.ts:296:25](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L296)
  at [./platform/keybinding/common/abstractKeybindingService.ts:187:14](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L187)
  at [./workbench/services/keybinding/browser/keybindingService.ts:261:37](https://github.com/Microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L261)

@alexdima can you take a look, it is unclear to me how this code could return something that is not a `string`:

https://github.com/microsoft/vscode/blob/8dfae7a5cd50421d10cd99cb873990460525a898/src/vs/editor/common/services/getIconClasses.ts#L65-L68

@mahish is this a standard VSCode installation or patched somehow?

**Comment by mahish** [comment]
@bpasero Standard one.

**Comment by bpasero** [comment]
@mahish if you still have access to that workspace, can we attempt to debug the problem? You already had dev tools opened, so all you need is to:
* open the "Sources" tab
* open the file `getIconClasses.ts`
* add a breakpoint into the method `cssEscape`
* check what type the passed in value is

I guess you could also break on error and get the same result.

**Comment by mahish** [comment]
@bpasero Thanks for the instructions. I found an array. Please see another short video https://gyazo.com/130368d8fd60ffd679a4aa1a0fda4650 or the screenshot below.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/3687943/163379196-5837e78c-b19a-4d90-91e6-e6aed20ca0ec.png">

**Comment by bpasero** [comment]
@mahish thanks!

@alexdima this means, any of the following methods return a `string[]` and not a `string`:
* `ILanguageService.getLanguageIdByMimeType`
* `ITextModel.getLanguageId`
* `ILanguageService.guessLanguageIdByFilepathOrFirstLine`

From [`detectLanguageId`](https://github.com/microsoft/vscode/blob/318f04c7dace7414c63fdf213001ff5259e1c8dd/src/vs/editor/common/services/getIconClasses.ts#L79).

**Comment by alexdima** [comment]
I'm able to reproduce this using an invalid configuration e.g. 
```
"files.associations": {
	"*.html": ["html", "twig"]
},
```
It doesn't look like we validate anywhere the user configured settings and that is how a `string[]` sneaks in as a `string`. I did recently some refactorings in this area, which maybe cause this invalid setting to manifest as a runtime error.

**Comment by mahish** [comment]
@alexdima I can confirm it. Im having this settings in several projects for some reason. Only the one throws the error tho. It has started working again once I removed the settings. Thank you:)

<img width="935" alt="image" src="https://user-images.githubusercontent.com/3687943/164996918-a91b8323-87b3-4c83-ab58-9c6b41e16c9e.png">

<img width="284" alt="image" src="https://user-images.githubusercontent.com/3687943/164996926-b85b361b-c7b4-4f73-943a-7a8410952270.png">
