### ISSUE TITLE
`UserSettings` file watcher get disposed and not reinstalled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147499]
Follow up from https://github.com/microsoft/vscode/issues/146335

In my testing, the file watcher installed here:

https://github.com/microsoft/vscode/blob/502b9fe644c01cabbd0f11aee8713c109eb76bdd/src/vs/platform/configuration/common/configurationModels.ts#L439

Is immediately getting disposed after startup.

The dispose happens from this stack and the watcher is not reinstalled:

```
Error
    at Object.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/configuration/common/configurationModels.js:374:44)
    at dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:166:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:153:18)
    at UserSettings.dispose (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:201:25)
    at MutableDisposable.set value [as value] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:230:26)
    at UserConfiguration.reload (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/configuration/browser/configuration.js:120:42)
    at async WorkspaceService.reloadLocalUserConfiguration (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:451:27)
```

**Comment by sandy081** [comment]
> Is immediately getting disposed after startup.

Yes this is expected. I load only user settings in the beginning and after start up, I load user + task configurations, during this I dispose the former. 

I am not sure what is wrong here?

**Comment by bpasero** [comment]
Yeah nevermind and feel free to close if I misunderstood, I think as long as https://github.com/microsoft/vscode/issues/146335 is still there we can proceed there.
