### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by BeRay31** [microsoft/vscode#147512]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.7.0-dev.20220408

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`c:\Users\LENOVO\AppData\Roaming\Code\logs\20220415T213152\exthost1\vscode.typescript-language-features\tsserver-log-9GdUhM\tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at parseSourceFileWorker (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:31412:22)
    at Object.parseSourceFile (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:31245:26)
    at Object.createSourceFile (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:31043:29)
    at Object.createLanguageServiceSourceFile (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:163530:29)
    at acquireOrUpdateDocument (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:134937:37)
    at Object.acquireDocumentWithKey (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:134878:20)
    at getOrCreateSourceFileByPath (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:163938:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:163885:24)
    at findSourceFileWorker (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:117687:29)
    at findSourceFile (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:117585:26)
    at c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:117537:85
    at getSourceFileFromReferenceWorker (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:117503:34)
    at processSourceFile (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:117537:13)
    at processRootFile (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:117338:13)
    at c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:116193:67
    at Object.forEach (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:183:30)
    at Object.createProgram (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:116193:16)
    at synchronizeHostData (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:163815:26)
    at Object.getProgram (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:163947:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:168999:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:168927:42)
    at ConfiguredProject.updateGraph (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:169989:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:171714:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:172799:44)
    at c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:173139:97
    at Object.flatMap (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:173139:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:174271:46)
    at c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:176311:88
    at IOSession.Session.executeWithRequestId (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:176302:28)
    at IOSession.Session.executeCommand (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:176311:33)
    at IOSession.Session.onMessage (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:176337:35)
    at Interface.<anonymous> (c:\Users\LENOVO\.vscode\extensions\ms-vscode.vscode-typescript-next-4.7.20220408\node_modules\typescript\lib\tsserver.js:178942:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.14GB free)|
|Process Argv|--crash-reporter-id d811fa16-a2ef-4ea7-9e83-255467f366c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
browse-lite|ant|0.2.16
vite|ant|0.2.5
turbo-console-log|Cha|2.1.7
vscode-svgviewer|css|2.0.0
gitlens|eam|11.7.0
prettier-vscode|esb|9.5.0
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.10
go|gol|0.32.0
todo-tree|Gru|0.0.215
discord-vscode|icr|5.7.0
svg|joc|1.4.17
volar|joh|0.34.6
vscode-cudacpp|kri|0.1.1
vscode-language-babel|mgm|0.0.36
mongodb-vscode|mon|0.9.2
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.78.0
remote-wsl|ms-|0.63.13
cpptools|ms-|1.9.7
vscode-typescript-next|ms-|4.7.20220408
vsliveshare|ms-|1.0.5527
vscode-react-native|msj|1.9.2
color-highlight|nau|2.5.0
clips-lang|ner|1.0.2
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.15.0
vscode-thunder-client|ran|1.16.2
fabric8-analytics|red|0.3.5
java|red|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
vscode-coverage-gutters|rya|2.9.1
code-spell-checker|str|2.1.11
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.19
windicss-intellisense|voo|0.21.6
vscode-arduino|vsc|0.4.11
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.1
vscode-maven|vsc|0.35.1
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
vscaac:30438847

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
