### ISSUE TITLE
Remote Development using SSH - riscv64 arch Support 

### ISSUE THREAD

**Issue by yuzibo** [microsoft/vscode#147751]
Hello, 
I try remote develop to Unmatched board using SSH, but it reports:

Unsupported architecture: riscv64

[16:15:51.924] Unsupported architecture
[16:15:51.925] Resolver error: Error: The remote host's architecture is not supported
	at Function.ServerInstallError (c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:585975)
	at p (c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:579264)
	at Object.t.handleInstallOutput (c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:583109)
	at Object.t.tryInstall (c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:681924)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:644564
	at async Object.t.withShowDetailsEvent (c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:647909)
	at async Object.t.resolve (c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:645643)
	at async c:\Users\vimer\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:722950
Is there plan to support the feature or I can do somethong for it?

**Comment by LarsRefsgaard** [comment]
Probably belongs in the respective repository of remote development extension: https://github.com/microsoft/vscode-remote-release

**Comment by yuzibo** [comment]
Ok,
The request has been there:
https://github.com/microsoft/vscode-remote-release/issues/4802
thank you.
