### ISSUE TITLE
Smoke test fail on all platforms

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#147749]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=167371&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=f55266f2-bc6d-5d84-0c09-e0cb5a30f53b

```
  1) VSCode Smoke Tests (Web)
       Language Features
         verifies quick outline (css):
     Error: Quick open file search was unable to find 'style.css' after 10 attempts, giving up.
      at QuickAccess.openFileQuickAccessAndWait (D:\a\_work\1\s\test\automation\src\quickaccess.ts:105:11)
      at QuickAccess.openFile (D:\a\_work\1\s\test\automation\src\quickaccess.ts:124:3)
      at Context.<anonymous> (src\areas\languages\languages.test.ts:27:4)

  2) VSCode Smoke Tests (Web)
       Language Features
         verifies problems view (css):
     Error: Quick open file search was unable to find 'style.css' after 10 attempts, giving up.
      at QuickAccess.openFileQuickAccessAndWait (D:\a\_work\1\s\test\automation\src\quickaccess.ts:105:11)
      at QuickAccess.openFile (D:\a\_work\1\s\test\automation\src\quickaccess.ts:124:3)
      at Context.<anonymous> (src\areas\languages\languages.test.ts:36:4)

  3) VSCode Smoke Tests (Web)
       Language Features
         verifies settings (css):
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:254:11)
      at Code.waitForElement (D:\a\_work\1\s\test\automation\src\code.ts:207:10)
      at Context.<anonymous> (src\areas\languages\languages.test.ts:51:4)

**Comment by joaomoreno** [comment]
First known red build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=167185&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5

Hard to find the culprit commit since breakage happend during Marketplace downtime.

**Comment by joaomoreno** [comment]
I ran the smoketest locally on latest `main` and immediately saw this dialog in the "Language Features" suite:

![image](https://user-images.githubusercontent.com/22350/164184905-6c1d58e3-a799-4ee2-a3b6-4e5b84fdce78.png)
