### ISSUE TITLE
Cannot start VS Code on 64bit ARM, Mac M1

### ISSUE THREAD

**Issue by nise** [microsoft/vscode#148002]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
```
dfd34e8260c270da74b5c2d86d61aee4b6d56977
arm64
```
- OS Version: Mac OS, 64bit arm, M1, Version 11.4

Steps to Reproduce:

1. start from mac os dock or terminal: ` /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code -s --disable-extensions`
2. See the terminal output:

```
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code -s           
[main 2022-04-24T13:04:38.345Z] Error: listen EINVAL: invalid argument /Volumes/DATA0/nise/Library/Application Support/Code/1.66.2-main.sock
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1480:5)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:69:18661
    at new Promise (<anonymous>)
    at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:69:18594)
    at X.claimInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:4648)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:2294
    at P.invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:29:319)
    at X.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:2161)
```

**Comment by deepak1556** [comment]
Unable to setup singleton instance socket on the user data path, can you provide the output of `NODE_DEBUG="net" code --verbose`

**Comment by nise** [comment]
Sorry, but I do not see any reason why this issue should be duplicate. Please provide any hint.

Here is the requesters verbose output:

```
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code -s --disable-extensions --user-data ~/.vscode
Warning: 'user-data' is not in the list of known options, but still passed to Electron/Chromium.
[main 2022-04-26T06:19:40.734Z] Error: listen EINVAL: invalid argument /Volumes/DATA0/nise/Library/Application Support/Code/1.66.2-main.sock
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1480:5)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:69:18661
    at new Promise (<anonymous>)
    at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:69:18594)
    at X.claimInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:4648)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:2294
    at P.invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:29:319)
    at X.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:2161)
(base) nise@ab Thunderbird % /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code -s --disable-extensions NODE_DEBUG="net" code --verbose
[main 2022-04-26T06:20:47.178Z] Error: listen EINVAL: invalid argument /Volumes/DATA0/nise/Library/Application Support/Code/1.66.2-main.sock
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1480:5)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:69:18661
    at new Promise (<anonymous>)
    at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out[main 2022-04-26T06:20:47.173Z] [File Watcher (node.js)] Request to start watching: /Volumes/DATA0/nise/Library/Application Support/Code/User (excludes: <none>),/Volumes/DATA0/nise/Library/Application Support/Code/User/settings.json (excludes: <none>)
[main 2022-04-26T06:20:47.178Z] Lifecycle#kill()
[main 2022-04-26T06:20:47.178Z] Lifecycle#onWillShutdown.fire()
[main 2022-04-26T06:20:47.179Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Volum/vs/code/electron-main/main.js:69:18594)
    at X.claimInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:4648)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:2294
    at P.invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:29:319)
    at X.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/maines/DATA0/nise/Library/Application Support/Code/User/settings.json'
.js:77:2161)

```

It seems to be an issue with a wrong path.

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues/137602#issuecomment-975501718
