### ISSUE TITLE
Null Extension Description showing up as the extension name in a few places

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#148043]
After installing an extension, you see "Null Extension Description":
![image](https://user-images.githubusercontent.com/2644648/165100019-40378e0e-2aec-42ee-aaf3-7b188609c531.jpeg)

I tried this with both Az Static Web Apps and Live share… same behavior:
- First install, the extension’s displayName is “Null Extension Description”
- Reload fixes it

Interestingly in the console:

```
ERR [x4sDR][นั้Extension 'nullExtensionDescription' CANNOT use API proposal: terminalDataWriteEvent.
Its package.json#enabledApiProposals-property declares: [] but NOT terminalDataWriteEvent.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api nullExtensionDescription: Error: Extension 'nullExtensionDescription' CANNOT use API proposal: terminalDataWriteEvent.
```
(sorry I have Pseudo language pack on right now)

so it seems like there’s a bad reference of the extension floating around API land.

The exact text seems to be here:
https://github.com/microsoft/vscode/blob/e7bc9bb5fc05d2cf9e468c359f634ecc2cc5e8bb/src/vs/workbench/services/extensions/common/extensions.ts#L20

@sandy081 said Seems to be caused by these changes - https://github.com/microsoft/vscode/pull/147761

**Comment by digitarald** [comment]
Just had the same when installing C++ and Python on Insiders:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/8599/165134301-46f43129-7e7d-4d64-94d3-233bf31828bb.png">

From the UI, both extensions seem installed. The only error I see in the console is

```
  ERR a DebugAdapterDescriptorFactory can only be registered from the extension that defines the 'python' debugger.: Error: a DebugAdapterDescriptorFactory can only be registered from the extension that defines the 'python' debugger.
	at E.registerDebugAdapterDescriptorFactory (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:9889)
	at Object.registerDebugAdapterDescriptorFactory (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:51122)
	at registerDebugAdapterDescriptorFactory (/private/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T/cleanvsi/ext-09-35-40/ms-python.python-2022.5.11111003/out/client/extension.js:2:105002)
	at d.activate (/private/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T/cleanvsi/ext-09-35-40/ms-python.python-2022.5.11111003/out/client/extension.js:2:329040)
	at /private/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T/cleanvsi/ext-09-35-40/ms-python.python-2022.5.11111003/out/client/extension.js:2:1788
	at Array.map (<anonymous>)
	at f.activate (/private/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T/cleanvsi/ext-09-35-40/ms-python.python-2022.5.11111003/out/client/extension.js:2:1778)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
