### ISSUE TITLE
Right click functionality

### ISSUE THREAD

**Issue by holyoaks** [microsoft/vscode#148143]
Issue Type: <b>Bug</b>

Starting yesterday, as soon as I open my Docker container app in VS Code, the right-click functionality on variables, class names, etc. disappears, and I'm left with just the standard `Change all Occurrences` menu option. I'm seeing warnings and errors in several logs. For example, the Log (Remote Server) shows a warning `[remoteagent] [warning] No ptyHost heartbeat after 6 seconds`. I'm also seeing multiple errors as shown below in the Log (Window):

```
[2022-04-26 07:28:49.742] [renderer1] [error] [Extension Host] Error: Unexpected SIGPIPE
	at process.<anonymous> (/root/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap.js:1:370)
	at process.emit (node:events:390:28)
```
This is making VS Code nearly unusable. Please help!

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.104-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id fb4199e6-8396-4083-9fce-d910eccdbdc3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container tv8_trivie (tv8_trivie_1)|
|OS|Linux x64 5.10.104-linuxkit|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (4 x 1996)|
|Memory (System)|3.84GB (0.32GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.3.0
jquerysnippets|don|0.0.1
terraform|has|2.22.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
mako|tom|0.2.0
JavaScriptSnippets|xab|1.8.0
gitlens|eam|12.0.6
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
sqltools|mtx|0.23.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by holyoaks** [comment]
I should also add that code completion no longer works, so no recognition of imports, etc. Formatters and linters still sort of work, so saving a file will highlight issues such as variable declared but not used, but not invalid imports, unknown methods, etc. Black will properly reformat the python files.

**Comment by holyoaks** [comment]
This morning I received an actual message from VS Code stating `The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.` I guess I know what the problem is now? I'm also seeing the following multiple times in Log(Remote Extension Host):

```[2022-04-27 12:40:50.515] [exthost] [error] [ms-python.python] provider FAILED
[2022-04-27 12:40:50.515] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:145778)
	at Object.dispose (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:155505)
	at S.handleConnectionClosed (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:155717)
	at S.handleConnectionClosed (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:32:10622)
	at t (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:153810)
	at invoke (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:281735)
	at o.fire (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:282496)
	at X (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:135140)
	at invoke (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:281735)
	at o.fire (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:282496)
	at d.fireClose (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:125209)
	at ChildProcess.<anonymous> (/root/.vscode-server/extensions/ms-python.python-2022.4.1/out/client/extension.js:24:277465)
	at ChildProcess.emit (node:events:402:35)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Socket.emit (node:domain:475:12)
	at Pipe.<anonymous> (node:net:687:12)
```

**Comment by holyoaks** [comment]
I downgraded to the Python extension 2022.4.0, and so far, it has stayed up/ not crashed.
