### ISSUE TITLE
Problems with selection and horizontal bracket pair guides if editor.inlayHints.toggle used. 

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#148207]
Issue Type: <b>Bug</b>

Related to  #148040

Code:
```js
console.log('Before', document.location);
```

Noticed problem that if you restart VS Code with `"editor.inlayHints.toggle": "show"` (and **before** showing inlay hints) try to do selection with mouse or keyboard then you have problem with putting cursor inside of parens and selection part of arguments.

https://user-images.githubusercontent.com/1312662/165385215-8dd6508a-0845-4cbc-8f97-75d98ddbe36f.mp4

and there is spam of this error in DevTools
<details>
<summary>Stacktrace</summary>

```
 ERR Cannot read properties of null (reading 'left'): TypeError: Cannot read properties of null (reading 'left')
    at S.prepareRender (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:674:55120)
    at y.prepareRender (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:586:74402)
    at W._actualRender (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:686:63457)
    at vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:686:62611
    at z (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:686:65875)
    at W._renderNow (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:686:62600)
    at W._flushAccumulatedAndRenderNow (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:686:59977)
    at W._onRenderScheduled (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:686:62555)
    at P.execute (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:71:29557)
    at Xe (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:71:29775)
```
</details>

Changing it to `hide` will make selections off until you reload window, but there are no error in dev tools.

----

For `"editor.inlayHints.toggle": "show"` if you put cursor inside of parenthesis while/after showing hints - selection - wrong length of horizontal guide will be preserved between putting cursor inside and outside of parenthesis until you edit code.
![image](https://user-images.githubusercontent.com/1312662/165386643-d5d4307c-53b2-40b1-a459-52d7e5639b1f.png)

----

VS Code version: Code - Insiders 1.67.0-insider (ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af, 2022-04-26T05:15:54.133Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (15.65GB free)|
|Process Argv|--crash-reporter-id 19aedffb-5c29-4248-9110-b5b20040c42f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Unable to reproduce after latest Insiders update update.
May be fixed in #148215 or in some other way.
