### ISSUE TITLE
Using the Back button and then trying to reload the enviorment causes perpetual loading. 

### ISSUE THREAD

**Issue by Tolure** [microsoft/vscode#148282]
After acidentally clicking the back button on my mouse and navigating to the previous page, I can't seem to get my enviroment to work. Each section (terminal, coding section, ...) is stuck on perpetual loading. 
I've prevously done the same mistake of hitting the back button but my enviorment loaded back in without a problem.

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Embedder: codespaces

**Comment by Tolure** [comment]
I've tried clearing my cach and reloading to no avail. 
I've let it run for a while to get a promt saying "Cannot reconnect. Please reload the window." Clicking the reload button does not solve the issue and just gets me back in the infinite loading loop.

**Comment by Tolure** [comment]
In the Chrome Dev Tools I see this error popping up. 

```
workbench.web.main.js:8 Uncaught (in promise) Canceled: Canceled
    at Object.v [as canceled] (https://main.vscode-cdn.net/stable/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/workbench.web.main.js:8:1172)
    at Object.call (https://main.vscode-cdn.net/stable/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/workbench.web.main.js:83:1927)
    at https://main.vscode-cdn.net/stable/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/workbench.web.main.js:83:7205
```

And in networking I see a periodic request for 'diagnostics' with the same return
```
{"ipv":false,"pvm":null,"rej":0,"bln":0,"acc":4,"efi":[]}
```

**Comment by Tolure** [comment]
On another computer it seems to work (I was able to execute the code "ls" and see files and folders) but soon after it gave me the warning "Remote Extension host terminated unexpectedly 3 times witin the last 5 minutes."

**Comment by Tolure** [comment]
Can't create a connection with github using Visual studio Code when I try to open codespace in VS Code.

**Comment by Tolure** [comment]
After a while I had the option to update and after another restart I was allowed back in.
