### ISSUE TITLE
VSCode fails scripts\npm install on windows and node 7

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#14828]
```
$ scripts\npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:bpasero/fsevents#vscode (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\github\vscode\npm-debug.log
```

**Comment by nojvek** [comment]
```
$ gulp
[16:41:36] Using gulpfile D:\github\vscode\gulpfile.js
[16:41:36] Starting 'clean-client'...
[16:41:36] Starting 'clean-extension:configuration-editing'...
[16:41:36] Starting 'clean-extension:css-client'...
[16:41:36] Starting 'clean-extension:css-server'...
[16:41:36] Starting 'clean-extension:extension-editing'...
[16:41:36] Starting 'clean-extension:html-client'...
[16:41:36] Starting 'clean-extension:html-server'...
[16:41:36] Starting 'clean-extension:javascript'...
[16:41:36] Starting 'clean-extension:json-client'...
[16:41:36] Starting 'clean-extension:json-server'...
[16:41:36] Starting 'clean-extension:markdown'...
[16:41:36] Starting 'clean-extension:php'...
[16:41:36] Starting 'clean-extension:python'...
[16:41:36] Starting 'clean-extension:typescript-test-colorize-fixtures'...
[16:41:36] Starting 'clean-extension:typescript'...
[16:41:36] Starting 'clean-extension:vscode-api-tests'...
[16:41:36] Starting 'clean-extension:vscode-colorize-tests'...
[16:41:36] Finished 'clean-extension:typescript-test-colorize-fixtures' after 9.88 ms
[16:41:36] Starting 'compile-extension:typescript-test-colorize-fixtures'...
[16:41:36] Starting compilation...
[16:41:36] Finished compilation with 0 errors after 19 ms
[16:41:36] Finished 'compile-extension:typescript-test-colorize-fixtures' after 43 ms
[16:41:36] Finished 'clean-extension:configuration-editing' after 85 ms
[16:41:36] Starting 'compile-extension:configuration-editing'...
[16:41:36] Starting compilation...
[16:41:36] Finished 'clean-extension:css-client' after 88 ms
[16:41:36] Starting 'compile-extension:css-client'...
[16:41:36] Finished 'clean-extension:css-server' after 91 ms
[16:41:36] Starting 'compile-extension:css-server'...
[16:41:36] Finished 'clean-extension:extension-editing' after 98 ms
[16:41:36] Starting 'compile-extension:extension-editing'...
[16:41:36] Finished 'clean-extension:html-client' after 101 ms
[16:41:36] Starting 'compile-extension:html-client'...
[16:41:36] Finished 'clean-extension:html-server' after 104 ms
[16:41:36] Starting 'compile-extension:html-server'...
[16:41:36] Finished 'clean-extension:markdown' after 105 ms
[16:41:36] Starting 'compile-extension:markdown'...
[16:41:36] Finished 'clean-extension:json-client' after 108 ms
[16:41:36] Starting 'compile-extension:json-client'...
[16:41:36] Finished 'clean-extension:python' after 108 ms
[16:41:36] Starting 'compile-extension:python'...
[16:41:36] Finished 'clean-extension:vscode-api-tests' after 111 ms
[16:41:36] Starting 'compile-extension:vscode-api-tests'...
[16:41:36] Finished 'clean-extension:vscode-colorize-tests' after 113 ms
[16:41:36] Starting 'compile-extension:vscode-colorize-tests'...
[16:41:36] Finished 'clean-extension:javascript' after 170 ms
[16:41:36] Starting 'compile-extension:javascript'...
[16:41:36] Finished 'clean-extension:json-server' after 172 ms
[16:41:36] Starting 'compile-extension:json-server'...
[16:41:36] Finished 'clean-extension:typescript' after 173 ms
[16:41:36] Starting 'compile-extension:typescript'...
[16:41:36] Finished 'clean-extension:php' after 285 ms
[16:41:36] Starting 'compile-extension:php'...
[16:41:39] Finished 'compile-extension:extension-editing' after 3.64 s
[16:41:39] Finished 'compile-extension:python' after 3.62 s
[16:41:39] Finished 'compile-extension:configuration-editing' after 3.66 s
[16:41:39] Finished 'compile-extension:markdown' after 3.64 s
[16:41:39] Finished 'compile-extension:json-client' after 3.64 s
[16:41:40] Finished 'compile-extension:css-client' after 4.07 s
[16:41:40] Finished 'compile-extension:html-client' after 4.06 s
[16:41:40] Finished 'compile-extension:vscode-colorize-tests' after 4.04 s
[16:41:40] Finished 'compile-extension:css-server' after 4.58 s
[16:41:40] Finished 'compile-extension:html-server' after 4.57 s
[16:41:40] Finished 'clean-client' after 4.69 s
[16:41:40] Starting 'compile-client'...
[16:41:41] Finished 'compile-extension:javascript' after 5.65 s
[16:41:42] Finished 'compile-extension:json-server' after 6.29 s
[16:41:42] Finished 'compile-extension:vscode-api-tests' after 6.36 s
[16:41:42] Finished 'compile-extension:php' after 6.2 s
[16:41:42] Finished 'compile-extension:typescript' after 6.38 s
[16:41:42] Starting 'compile-extensions'...
[16:41:42] Finished 'compile-extensions' after 44 μs
[16:42:14] Error: D:/github/vscode/extensions/configuration-editing/src/extension.ts(9,27): Cannot find module 'jsonc-parser'.
[16:42:14] Error: D:/github/vscode/extensions/css/client/src/typings/ref.d.ts(11,1): File 'D:/github/vscode/extensions/css/node_modules/vscode-languageclient/lib/main.d.ts' not found.
[16:42:14] Error: D:/github/vscode/extensions/css/client/src/cssMain.ts(10,128): Cannot find module 'vscode-languageclient'.
[16:42:14] Error: D:/github/vscode/extensions/css/client/src/cssMain.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/css/server/src/languageModelCache.ts(7,28): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/css/server/src/cssServerMain.ts(10,8): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/css/server/src/cssServerMain.ts(12,132): Cannot find module 'vscode-css-languageservice'.
[16:42:14] Error: D:/github/vscode/extensions/html/client/src/typings/ref.d.ts(11,1): File 'D:/github/vscode/extensions/html/node_modules/vscode-languageclient/lib/main.d.ts' not found.
[16:42:14] Error: D:/github/vscode/extensions/html/client/src/htmlMain.ts(10,83): Cannot find module 'vscode-languageclient'.
[16:42:14] Error: D:/github/vscode/extensions/html/client/src/htmlMain.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/html/server/src/languageModelCache.ts(7,28): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/html/server/src/htmlServerMain.ts(7,96): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/html/server/src/htmlServerMain.ts(9,98): Cannot find module 'vscode-html-languageservice'.
[16:42:14] Error: D:/github/vscode/extensions/html/server/src/htmlServerMain.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/json/client/src/typings/ref.d.ts(11,1): File 'D:/github/vscode/extensions/json/node_modules/vscode-languageclient/lib/main.d.ts' not found.
[16:42:14] Error: D:/github/vscode/extensions/json/client/src/jsonMain.ts(10,114): Cannot find module 'vscode-languageclient'.
[16:42:14] Error: D:/github/vscode/extensions/json/client/src/jsonMain.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/packageJSONContribution.ts(9,26): Cannot find module 'request-light'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/packageJSONContribution.ts(10,24): Cannot find module 'jsonc-parser'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/packageJSONContribution.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/jsonContributions.ts(7,75): Cannot find module 'jsonc-parser'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/jsonContributions.ts(11,26): Cannot find module 'request-light'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/bowerJSONContribution.ts(9,26): Cannot find module 'request-light'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/bowerJSONContribution.ts(10,24): Cannot find module 'jsonc-parser'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/features/bowerJSONContribution.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/javascriptMain.ts(9,30): Cannot find module 'request-light'.
[16:42:14] Error: D:/github/vscode/extensions/javascript/src/javascriptMain.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/projectJSONContribution.ts(7,64): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/projectJSONContribution.ts(9,54): Cannot find module 'request-light'. [16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/projectJSONContribution.ts(10,70): Cannot find module 'vscode-json-languageservice'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/projectJSONContribution.ts(11,19): Cannot find module 'request-light'.

[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/projectJSONContribution.ts(13,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/projectJSONContribution.ts(122,11): No best common type exists among return expressions.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/globPatternContribution.ts(7,64): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/globPatternContribution.ts(9,70): Cannot find module 'vscode-json-languageservice'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/globPatternContribution.ts(11,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/fileAssociationContribution.ts(7,64): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/fileAssociationContribution.ts(9,70): Cannot find module 'vscode-json-languageservice'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsoncontributions/fileAssociationContribution.ts(11,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/languageModelCache.ts(7,28): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsonServerMain.ts(10,8): Cannot find module 'vscode-languageserver'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsonServerMain.ts(12,95): Cannot find module 'request-light'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsonServerMain.ts(18,78): Cannot find module 'vscode-json-languageservice'.
[16:42:14] Error: D:/github/vscode/extensions/json/server/src/jsonServerMain.ts(24,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/typescript/src/utils/projectStatus.ts(10,33): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/typescript/src/typescriptServiceClient.ts(24,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/typescript/src/typescriptMain.ts(16,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/php/src/features/validationProvider.ts(14,22): Cannot find module 'vscode-nls'.
[16:42:14] Error: D:/github/vscode/extensions/php/src/phpMain.ts(14,22): Cannot find module 'vscode-nls'.
[16:42:14] Finished compilation with 49 errors after 38019 ms
[16:42:14] [monaco.d.ts] Starting monaco.d.ts generation
[16:42:17] [monaco.d.ts] Finished monaco.d.ts generation
[16:42:17] 'compile-client' errored after 37 s
[16:42:17] Error: monaco.d.ts is no longer up to date. Please run gulp watch and commit the new file.
    at formatError (c:\Users\mapatel\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (c:\Users\mapatel\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (D:\github\vscode\node_modules\orchestrator\index.js:264:8)
    at D:\github\vscode\node_modules\orchestrator\index.js:275:23
    at finish (D:\github\vscode\node_modules\orchestrator\lib\runTask.js:21:8)
    at Stream.<anonymous> (D:\github\vscode\node_modules\orchestrator\lib\runTask.js:52:4)
    at Stream.f (D:\github\vscode\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at emitOne (events.js:101:20)
```

**Comment by joaomoreno** [comment]
As per our [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) guide, please use Node 6 with NPM >= 3.10.8.

**Comment by mdahamiwal** [comment]
I am hitting the same issue in `scripts\npm install` even with NPM 3.10.8. I have tried it on three different machines with no luck. 

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\manishda\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\manishda\Documents\sources\vscode\npm-debug.log
```

**Comment by joaomoreno** [comment]
Can you open a new issue for this and show me the full log?

**Comment by verysimplenick** [comment]
Same issue, full log file not created

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\verysimplenick\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Q:\commits\vscode\npm-debug.log
```

**Comment by mdahamiwal** [comment]
@verysimplenick, check if #15095 logs matches your logs. If it does, installing C++ tools should work.

**Comment by verysimplenick** [comment]
@mdahamiwal 
I has C++ + Platform SDK with VS2015, I try run `scripts\npm install` from `VS2015 x64 Native Tools Command Prompt` (for cl.exe) and get error. After this, I check another issue #807 and found reason: I have installed msys2. Need setup python path in npm (in PATH variable I already has this path):
```
npm config set python C:\Python27\python.exe
```
Now run's without errors.
