### ISSUE TITLE
Expanded list of nested files incorrectly updated if `explorer.fileNesting.expand` is `false`

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#148218]
Issue Type: <b>Bug</b>

Relies on default `"tsconfig.json": "tsconfig.*.json"`.

Steps to reproduce:

0. Set `explorer.fileNesting.expand` to `false`
1. Click on "New file" button and create `tsconfig.json` - no twistie(?) (as expected)
2. Click on "New file" button and create `tsconfig.1.json` - twistie appers (`tsconfig.json` still collapsed)
3. Expand `tsconfig.json` - see nested `tsconfig.1.json`

**Bug 1:**

4. Click on "New file" button and create `tsconfig.2.json` - fille not show in explorer even if you collapse and then expand `tsconfig.json`, only nested file displayed is `tsconfig.1.json`
5. Click on "Refresh Explorer"  - `tsconfig.json` remains expanded, but now you can see both nested `tsconfig.1.json` and `tsconfig.2.json`

**Bug 2:** (this one looks same as #147987)

6. Remove any of nested files (e.g.  `tsconfig.2.json`) - now all nested files aren't visible, however twistie is shown, but collapsing/expanding doesn't show nested files.
7. Click on "Refresh Explorer"  - `tsconfig.json` remains expanded and now you canse see `tsconfig.1.json`.

I think month ago I saw exceptions in console, but now there are no exceptions in console but there are caught exceptions e.g.
<details>
<summary>Stack: Error: TreeError [FileExplorer] Tree element not found: [object Object]</summary>

```
Error: TreeError [FileExplorer] Tree element not found: [object Object]
    at s.getCompressedNode (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:73:25008)
    at s.getParentNodeLocation (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:73:23881)
    at l.getParentNodeLocation (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:73:27273)
    at vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:218:34178
    at Array.forEach (<anonymous>)
    at I._onDidChangeActiveNodes (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:218:34123)
    at I.onDidChangeNodeTwistieState (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:218:32666)
    at m.invoke (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:65:49314
    at m.invoke (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at m.invoke (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:65:49314
    at vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:5091
    at vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:5224
    at Array.forEach (<anonymous>)
    at v.bufferEvents (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:5213)
    at C.setCollapsible (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:73:10582)
    at R.setCollapsible (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:73:19400)
    at setCollapsible (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:73:24384)
    at l.setCollapsible (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:73:27670)
    at S.setCollapsible (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:219:623)
    at Z.render (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:219:23484)
    at Z.render (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:219:27922)
    at Z.refreshAndRenderNode (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:219:20037)
    at async Z._updateChildren (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:219:17099)
    at async Z.updateChildren (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:219:16765)
    at async vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3032:70741
    at async vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:64606
    at async Promise.all (index 0)
    at async Ho.onDidRunOperation (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1709:64481)
```
</details>

Also one of error breakpoints shows `Unable to read file 'path\to\workspace\tsconfig.2.json' (Error: File not modified since)` in case `tsconfig.1.json` was removed.

**Bug 3:**

8. Rename nested `tsconfig.1.json` to `1.json` - `1.json` is shown separately and twistie is gone for  `tsconfig.json`
9. Press <kbd>Ctrl</kbd>+<kbd>Z</kbd> or rename file to something that will be nested again (e.g. `tsconfig.upd.json`) - twistie appears again, looks expanded, but `tsconfig.1.json`/`tsconfig.upd.json` is not visible until you use "Refresh Explorer"

![image](https://user-images.githubusercontent.com/1312662/165402880-73a3f029-d835-4aba-8ea1-4ca556e765ed.png)

VS Code version: Code - Insiders 1.67.0-insider (ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af, 2022-04-26T05:15:54.133Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (13.72GB free)|
|Process Argv|--crash-reporter-id 19aedffb-5c29-4248-9110-b5b20040c42f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by JacksonKearl** [comment]
Thanks for the great repro steps! Should be fixed now. 

I'm not absolutely in love with the fix because it involves some extra work by forcing a recursive refresh of nodes (when nesting is enabled), but I've lost count of the number of hours I've dumped in to finding a better approach, and I don't want to make too significant of changes this late in the iteration.

**Comment by IllusionMH** [comment]
Yep, unable to reproduce cases mentioned above 👍 

Found 1 or 2 small inconsistencies (nothing serious in comparison with bug(s) above), probably tied to `explorer.autoReveal` or looks like file that no longer has nested files "remembers" it's expanded/collapsed position, but requires more investigation.
