### ISSUE TITLE
ts-server throw error 

### ISSUE THREAD

**Issue by sanmmm** [microsoft/vscode#148498]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest version
- OS Version: win 10

ts-server throw an error when vscode try to requestion completioninfo

log info:
`[Trace  - 02:26:40.444] <semantic> Response received: completionInfo (3546). Request took 68 ms. Success: false . Message: Error processing request. Cannot read property 'close' of undefined
TypeError: Cannot read property 'close' of undefined
    at Object.close (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:6873:33)
    at Object.close (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170028:37)
    at Object.close (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170044:33)
    at c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171465:186
    at Map.forEach (<anonymous>)
    at Object.clear (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171465:142)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166922:47)
    at ConfiguredProject.Project.updateGraph (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166767:42)
    at ConfiguredProject.updateGraph (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167802:63)
    at Object.updateProjectIfDirty (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168291:45)
    at ConfiguredProject.Project.getLanguageService (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166381:28)
    at IpcIOSession.Session.getCompletions (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173395:43)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172237:61)
    at c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174044:88
    at IpcIOSession.Session.executeWithRequestId (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174035:28)
    at IpcIOSession.Session.executeCommand (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174044:33)
    at IpcIOSession.Session.onMessage (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174070:35)
    at process.<anonymous> (c:\Users\mypc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176705:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)`

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
