### ISSUE TITLE
ERR ListError [SettingsTree] Invalid index 4

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148439]
Noticed this when testing watcher excludes:

![Recording 2022-04-29 at 17 49 59](https://user-images.githubusercontent.com/900690/165979848-e8351f22-ae79-487f-87f0-8e904f0b857e.gif)

```
ERR ListError [SettingsTree] Invalid index 4: Error: ListError [SettingsTree] Invalid index 4
    at M.setFocus (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:157:10290)
    at M.setFocus (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:219:46934)
    at L.onViewPointer (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:132:43625)
    at L.onViewPointer (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:219:45404)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:65:49648
    at m.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:65:49314
    at m.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at HTMLDivElement.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:10239)
```

//cc @joaomoreno

**Comment by rzhao271** [comment]
Verification steps:
1. Search for the `@id:files.watcherExclude` setting. Only one list setting should show up.
2. Open devtools.
3. Click on the last item of the setting.
4. The above error shouldn't show up in the console.
