### ISSUE TITLE
$ref 'definitions/colorGroup' in 'vscode://schemas/textmate-colors' can not be resolved.

### ISSUE THREAD

**Issue by 2A5F** [microsoft/vscode#148512]
Does this issue occur when all extensions are disabled?: No

How to check which extension is causing the problem?

Issue Type: <b>Bug</b>

1. open vscode
2. open package.json

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.48GB free)|
|Process Argv|--crash-reporter-id f518c2b6-14d7-45fe-8f42-e01565edc55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (121)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
vscode-ron|a5h|0.9.0
better-comments|aar|3.0.0
vscode-css-formatter|aes|1.0.2
vscode-nginx-conf|ahm|0.1.3
auto-add-brackets|ali|0.12.0
preview-mp4|ana|0.0.1
vscode-zipfs|arc|3.0.0
vscode-database|baj|2.2.3
toml|be5|0.6.0
cargo-inspect|car|0.1.0
rescript-vscode|che|1.2.1
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
glsl-canvas|cir|0.2.15
gitignore|cod|0.7.0
vscode-test-explorer-status-bar|con|1.2.0
marshal-command-code|din|1.1.2
vscode-styled-jsx-languageserver|Div|1.3.1
githistory|don|0.6.19
vscode-wasm|dts|1.3.1
vscode-gitignore-syntax|dun|0.1.2
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
git-project-manager|fel|1.8.2
file-icons|fil|1.0.29
vscode-firefox-debug|fir|2.9.6
vscode-jest-runner|fir|0.4.48
provision-lens|Foo|4.0.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.40.0
gitkraken-authentication|git|1.0.3
gc-excelviewer|Gra|4.2.54
testdocs|gvj|0.1.2
vscode-mocha-test-adapter|hbe|2.13.3
vscode-test-explorer|hbe|2.21.1
vscode-power-mode|hoo|3.0.2
emotionsnippets|iJS|1.1.2
Ionide-FAKE|Ion|1.2.3
Ionide-Paket|Ion|2.0.0
highlight-string-code|iuy|0.4.5
mysql-syntax|jak|1.3.1
rainbow-end|jdu|0.7.12
vscode-nuget-package-manager|jmr|1.1.6
svg|joc|1.4.17
volar|joh|0.34.11
vscode-typescript-vue-plugin|joh|0.34.11
csharpsortusings|jon|0.0.6
vscode-icon-theme|jtl|1.6.6
vscode-map-preview|jum|0.5.9
theme-karyfoundation-themes|kar|25.2.3
vscode-jest-test-adapter|kav|0.8.1
cargo-toml-snippets|kev|0.1.1
node-module-intellisense|lei|1.5.0
rust-analyzer|mat|0.2.1030
cbstyle|Meo|0.0.1
git-graph|mhu|1.30.0
vscode-checkpoints|mic|1.3.2
vscode-filesize|mkx|3.1.0
localize-lens|mma|1.0.0
fsharp-fsl-fsy|mnx|0.0.1
theme-monokai-pro-vscode|mon|1.1.20
hg|mrc|1.8.1
vscode-scss|mrm|0.10.0
vscode-language-pack-zh-hans|MS-|1.66.3
vscode-edge-devtools|ms-|1.4.8
data-workspace-vscode|ms-|0.2.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-remote-extensionpack|ms-|0.21.0
github-issues-prs|ms-|0.9.3
hexeditor|ms-|1.9.6
mono-debug|ms-|0.16.2
powershell|ms-|2021.12.0
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5527
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.16.0
wgsl|Pol|0.1.12
postal|pos|1.0.0
vscode-css-peek|pra|4.2.0
quantum-devkit-vscode|qua|0.24.208024
webgl-glsl-editor|rac|1.3.0
subtle-brackets|raf|3.0.0
nginx-formatter|ray|0.0.13
tsserver-live-reload|rbu|1.0.1
java|red|1.5.0
vscode-xml|red|0.20.0
vscode-yaml|red|1.7.0
vscode-statusbar-json-path|ric|1.4.5
gi|rub|0.2.11
crates|ser|0.5.10
vscode-scss-formatter|sib|2.4.2
shader|sle|1.1.5
vscode-zipexplorer|sle|0.3.1
vscode-styled-components|sty|1.7.4
svelte-vscode|sve|105.16.0
vscode-rust-test-adapter|Swe|0.11.0
unity-tools|Tob|1.2.12
cmake|twx|0.0.17
errorlens|use|3.4.2
vscode-lldb|vad|1.7.0
windicss-intellisense|voo|0.21.6
vscode-icons|vsc|11.11.0
debug|web|0.26.0
highlight-bad-chars|wen|0.0.6
vscode-nxunit-test-adapter|wgh|0.1.3
vscode-nginx|wil|0.7.2
bracket-lens|wra|1.5.1
map-replace-js|Yuk|0.2.2
file-size|zh9|1.0.0
material-theme|zhu|3.13.24
html-css-class-completion|Zig|1.20.0

(29 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by aeschli** [comment]
I can not see that error. Do you see it also after a restart?
vscode://schemas/textmate-colors is provided internally, so it should always be there.
Anything in the logs (`Developer: Open Log File... Window)

`definitions/colorGroup'` is referenced when the settings file is opened, not `package.json`

**Comment by 2A5F** [comment]
Happens every time I open vscode
but after closing package.json and reopening it disappears

<details>
<summary>Log</summary>

```
[2022-05-02 19:21:06.267] [renderer1] [warning] [c:\Users\Aditr\.vscode\extensions\equinusocio.vsc-community-material-theme-1.4.4]: property `extensionKind` can be defined only if property `main` is also defined.
[2022-05-02 19:21:06.268] [renderer1] [warning] [c:\Users\Aditr\.vscode\extensions\fisheva.eva-theme-1.8.2]: property `extensionKind` can be defined only if property `main` is also defined.
[2022-05-02 19:21:06.279] [renderer1] [warning] [c:\Users\Aditr\.vscode\extensions\ms-vscode-remote.vscode-remote-extensionpack-0.21.0]: property `extensionKind` can be defined only if property `main` is also defined.
[2022-05-02 19:21:06.401] [renderer1] [critical] Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletions, inlineCompletionsNew, inlineCompletionsAdditions
product.json (WINS): inlineCompletions, textDocumentNotebook
[2022-05-02 19:21:06.402] [renderer1] [critical] Extension 'TabNine.tabnine-vscode CANNOT USE these API proposals 'inlineCompletions'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-05-02 19:21:06.426] [renderer1] [info] Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
[2022-05-02 19:21:06.453] [renderer1] [warning] [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
[2022-05-02 19:21:06.534] [renderer1] [info] [GitHub.vscode-pull-request-github]: `remoteHub/pullRequest` is not a valid menu identifier
[2022-05-02 19:21:06.722] [renderer1] [info] Creating lazy extension host: contains 1 extension(s): wengerk.highlight-bad-chars.
[2022-05-02 19:21:06.724] [renderer1] [info] Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
[2022-05-02 19:21:07.628] [renderer1] [info] Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
[2022-05-02 19:21:08.893] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.894] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.894] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.894] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.894] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.895] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.895] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.895] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\Aditr\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.8\out\extension
[2022-05-02 19:21:08.897] [renderer1] [error] [Extension Host] (node:26156) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-05-02 19:21:35.242] [renderer1] [error] ENOENT: no such file or directory, stat 'rendererLog': Error: ENOENT: no such file or directory, stat 'rendererLog'
    at statSync (node:fs:1536:3)
    at Object.e.statSync (node:electron/js2c/asar_bundle:5:4527)
    at updateSize (c:\Users\Aditr\.vscode\extensions\zh9528.file-size-1.0.0\extension.js:31:19)
    at c:\Users\Aditr\.vscode\extensions\zh9528.file-size-1.0.0\extension.js:52:9
    at u.invoke (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:66000
    at u.invoke (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at E.acceptDocumentsAndEditorsDelta (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:75931)
    at E.$acceptDocumentsAndEditorsDelta (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:74020)
    at i._doInvokeHandler (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (c:\Users\Aditr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

</details>

**Comment by haliphax** [comment]
I have this plugin installed to show errors and warnings inline. Not sure if it's related.

https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

**Comment by aeschli** [comment]
I don't know if it's related. But yes, can you start with all extensions disabled to see if this is caused by an extension?
To do that, use the command: `Developer: Reload with Extensions Disabled`

**Comment by 2A5F** [comment]
This is also in my settings.json
But disabling errorlens has no effect

**Comment by aeschli** [comment]
What about when running with all extensions disabled? (command: Developer: Reload with Extensions Disabled)

**Comment by 2A5F** [comment]
> Does this issue occur when all extensions are disabled?: No

**Comment by 2A5F** [comment]
I wonder if there is any way to find out what extension is causing the problem without manually enabling and disabling the extension
Because I have a lot of extensions and I also need to use them

**Comment by aeschli** [comment]
Use `Help: Start Extension Bisect`. It does the enabling and disabling for you.

**Comment by 2A5F** [comment]
Great, caused by https://marketplace.visualstudio.com/items?itemName=wraith13.bracket-lens

**Comment by 2A5F** [comment]
https://github.com/wraith13/bracket-lens-vscode/issues/19
