### ISSUE TITLE
Extension relative path not loaded properly

### ISSUE THREAD

**Issue by Thavarajan** [Microsoft/vscode#14915]
- VSCode Version:
1.6.1 
- OS Version:
Linux Mint 18

Steps to Reproduce:

1. Vscode ionic 2 extension installed
2.  workperfectly in  windows 10
in linux the following problem happens
```

[Extension Host] Activating extension `Thavarajan.ionic2` failed:  Cannot find module './Commands/Ion-platformbase'

[Extension Host] Here is the error stack:  Error: Cannot find module './Commands/Ion-platformbase'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.N.n._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:19970)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sg/.vscode/extensions/Thavarajan.ionic2-2.3.0/out/src/Ionic_Command.js:6:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

```

**Comment by joaomoreno** [comment]
I was about to move this to [Thavarajan/vscode-ionic2-Extension](https://github.com/Thavarajan/vscode-ionic2-Extension) until I saw you are the extension's developer.

I had to install the extension and look at the files for myself, since your repository is hidden away in TFS.

Your problem is that the file is actually called `ion-platformbase.js`, not `Ion-platformbase.js`. Note the uppercase `I`. Linux is a case **sensitive** file system, so make sure you always use the exact name for the files that you require.

**Comment by Thavarajan** [comment]
sorry @joaomoreno,
  But thanks for the help, i didn't know that Linux file system is case sensitive, new thing learned

**Comment by Thavarajan** [comment]
hi @joaomoreno 
I found this not sure a bug or not,
i already change my extenstion file to capital name but the out folder doesn't apply the nesscary change,
while building the extension with vsce it is just package the out folder i think i am not sure here,

any way deleting all the out files manually and recreate it now the files names are in correct case
