### ISSUE TITLE
Interactive window sometimes counted as dirty file

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#149275]
I can't yet provide a repro for this since I haven't found a pattern that causes this consistently. VS Code occasionally considers an IW to have unsaved changes and shows the corresponding blue counter below the explorer icon in the side bar even though no unsaved changes in actual files exist.

![Screen Shot 2022-05-11 at 10 54 45](https://user-images.githubusercontent.com/30958850/167823212-6ba16292-a78e-49c4-827b-8488b7e20de8.png)

This has been happening for a while (maybe 2 months).
Jupyter Extension Version: 2022.4.1011282140.
Python Extension Version: 2022.6.0.
Python: 3.9 + 3.10

Will post more details as I notice them.

**Comment by wduminy** [comment]
While investigating a similar issue in one of my workspaces where a file is incorrectly marked as unsaved when I open the workspace, I found this error in the logs.  It could be related to the problem reported here.

I am running version:
```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 20.6.0
```
```
[2022-08-24 07:33:53.599] [exthost] [error] An error occurred when deactivating the subscriptions for extension 'Gruntfuggly.todo-tree':
[2022-08-24 07:33:53.601] [exthost] [error] Error: Encountered errors while disposing of store. Errors: [TypeError: s.dispose is not a function, TypeError: s.dispose is not a function]
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:12400)
	at w._deactivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13297)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:10622
	at Array.map (<anonymous>)
	at w._deactivateAll (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:10609)
	at w.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:10993)
	at w.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:620)
	at m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:19088)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:17016
	at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at b.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at i._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:23593)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:21127
	at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at b.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15837)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:14967
	at Socket.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:26303)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

I removed the `Gruntfuggly.todo-tree` and got similar errors with other extensions.

**Comment by wduminy** [comment]
My comment could also be related to #158709

**Comment by janosh** [comment]
@amunger This is still happening to me on a regular basis. Now running VS Code 1.73.1 and Jupyter extension v2022.9.1303220346.

**Comment by amunger** [comment]
should go away in insiders, and the next release now that the Interactive window implements a scratchpad working copy

**Comment by janosh** [comment]
That's great! Looking forward to next release.

**Comment by roblourens** [comment]
@janosh would appreciate if you can try this in the latest VS Code Insiders build and check whether it still shows up

@amunger anything else we can do to verify?

**Comment by amunger** [comment]
[insiders download link](https://code.visualstudio.com/insiders/)

It's not clear to me how this ever occurred and I never heard of anyone on the team seeing it. The dirty property is handled more explicitly now, so just opening an IW and not seeing a dirty indicator might be enough for verification.

**Comment by janosh** [comment]
Very busy today and tomorrow. Can try Insiders do over the weekend.

**Comment by rzhao271** [comment]
I'll mark this issue as verified for now; I don't even see a flicker of the IW showing up as a dirty file.
Please let us know if the issue still reproduces for you.
