### ISSUE TITLE
Error in Developer Tools on startup

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#149351]
Issue Type: <b>Bug</b>

Launch VS Code, lookin in Developer tools console. See error

```
log.ts:313   ERR Cannot read properties of undefined (reading 'getRuntimeValue'): TypeError: Cannot read properties of undefined (reading 'getRuntimeValue')
    at N.isVisible (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:22965)
    at nr.showOrHideViewContainer (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2966:518)
    at nr.onDidRegisterPanels (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2959:43423)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2966:1048
    at p.invoke (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at s.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at s.registerComposite (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:797:70608)
    at s.registerPaneComposite (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2959:37952)
    at m.registerPaneComposite (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:66311)
    at m.onDidRegisterViewContainer (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:56992)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:55473
    at Array.forEach (<anonymous>)
    at new m (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:55457)
    at b._createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:1332)
    at b._createServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:3729)
    at b._createServiceInstanceWithOwner (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:3245)
    at b._createAndCacheServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:2920)
    at b._safeCreateAndCacheServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:2122)
    at b._getOrCreateServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:1843)
    at b._createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:937)
    at b.createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:773)
    at new d (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2743:32870)
    at b._createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:1332)
    at b.createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:773)
    at new us (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2743:40467)
    at new m (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2743:51181)
    at b._createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:1332)
    at b._createServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:3729)
    at b._createServiceInstanceWithOwner (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:3245)
    at b._createAndCacheServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:2920)
    at b._safeCreateAndCacheServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:2122)
    at b._getOrCreateServiceInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:1843)
    at b._createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:937)
    at b.createInstance (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:773)
    at O.acquireInstantiationService (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2672:29682)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:69989
    at b.invokeFunction (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:591:319)
    at N.initServices (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:69850)
    at N.startup (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3037:69075)
    at Y.open (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3094:53471)
    at async vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/bootstrap-window.js:1:3156
log.ts:319 CRITI Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookDocumentEvents' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
```

VS Code version: Code - Insiders 1.68.0-insider (624bbc4fb966bfa34e9486e320a64a138ac337fd, 2022-05-12T05:20:55.891Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.59GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
TabOut|alb|0.2.1
ng-template|Ang|13.3.3
sync-scroll|dqi|1.3.0
vs-code-xml-format|fab|0.1.5
csharpextensions|kre|1.7.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
csharp|ms-|1.24.4
azure-account|ms-|0.10.1
hexeditor|ms-|1.9.6
material-icon-theme|PKi|4.17.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.16.3
hl7tools|Rob|1.13.2
msbuild-project-tools|tin|0.4.3
vscodeintellicode|Vis|1.2.20

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebug:30475216
vsclangdf:30480126

```

</details>

**Comment by sinux-l5d** [comment]
I'm having the same issue on a lower version: 
```
$ code --version                                                           
1.67.1
da15b6fd3ef856477bf6f4fb29ba1b7af717770d
x64
```

So I can't use Live Share anymore

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/149438
