### ISSUE TITLE
Smoke test: Terminal shell integration failures

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#149324]
The terminal shell integration tests now assume a compatible shell to be available on Linux/macOS, but they fail on a system which uses `/bin/sh` as the default shell.

https://dev.azure.com/vscode/VSCode/_build/results?buildId=63999&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=ba1f49f8-ebc8-5fce-d4f0-c3f72b5807bc

![playwright-screenshot-3-Error](https://user-images.githubusercontent.com/22350/168009922-465efaa1-bbda-442d-8e9a-43ad9bf403dc.png)

```
  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Shell integration
             Decorations
               Should show default icons
                 Placeholder:
     Error: Timeout: get elements '.terminal-command-decoration.codicon-circle-outline' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:254:11)
      at Code.waitForElements (/__w/1/s/test/automation/src/code.ts:203:10)
      at Terminal.assertCommandDecorations (/__w/1/s/test/automation/src/terminal.ts:219:4)
      at Context.<anonymous> (src/areas/terminal/terminal-shellIntegration.test.ts:32:7)

  2) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Shell integration
             Decorations
               Should show default icons
                 Success:
     Error: Timeout: get elements '.terminal-command-decoration.codicon-circle-outline' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:254:11)
      at Code.waitForElements (/__w/1/s/test/automation/src/code.ts:203:10)
      at Terminal.assertCommandDecorations (/__w/1/s/test/automation/src/terminal.ts:219:4)
      at Context.<anonymous> (src/areas/terminal/terminal-shellIntegration.test.ts:37:7)

  3) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Shell integration
             Decorations
               Should show default icons
                 Error:
     Error: Timeout: get elements '.terminal-command-decoration.codicon-circle-outline' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:254:11)
      at Code.waitForElements (/__w/1/s/test/automation/src/code.ts:203:10)
      at Terminal.assertCommandDecorations (/__w/1/s/test/automation/src/terminal.ts:219:4)
      at Context.<anonymous> (src/areas/terminal/terminal-shellIntegration.test.ts:42:7)

  4) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Shell integration
             Decorations
               Custom configuration
                 Should update and show custom icons:
     Error: Timeout: get elements '.terminal-command-decoration.codicon-circle-outline' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:254:11)
      at Code.waitForElements (/__w/1/s/test/automation/src/code.ts:203:10)
      at Terminal.assertCommandDecorations (/__w/1/s/test/automation/src/terminal.ts:219:4)
      at Context.<anonymous> (src/areas/terminal/terminal-shellIntegration.test.ts:48:7)
```

cc @lszomoru

**Comment by Tyriar** [comment]
@joaomoreno thanks a bunch for looking into it

**Comment by meganrogge** [comment]
if we use `bash` explicitly on linux, that will catch issues like #150320 for us

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/150192
