### ISSUE TITLE
Cant type `>` after `{` if `{}` and `<>` are defined as 'brackets'

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#149460]
I am unexpectedly unable to type `>` on a newline after a `{` if both `{}` and `<>` are defined as 'brackets' in `language-configuration.json`

Create a new plain text file and change the assigned language to something that has both `{}` and `<>` defined as 'brackets'
possible options are `vb` or `handlebars` (or make your own)
![image](https://user-images.githubusercontent.com/33529441/167288562-f6fe35bf-a3cc-4987-b871-eff61fc92e0c.png)
type a single `{` at the top of the file and press enter
now try to type `>`
notice how nothing happens
![image](https://user-images.githubusercontent.com/33529441/167288304-2573d6a6-5a81-40bd-b606-4137306dc964.png)
typing `<` and `.` work prefectly fine
and if there is non-whitespace character between the start of the line and where you're typing; it also works fine

Enviro: `VSCode-win32-ia32-1.67.0` & `VSCode-win32-x64-1.67.1`
Report moved from: https://github.com/microsoft/vscode-textmate/issues/175

**Comment by alexdima** [comment]
`vscode-bisect` points to https://github.com/microsoft/vscode/compare/b84feecf9231d404a766e251f8a37c730089511b...fcaeb69ec8e96057423f7dadd52e116e29b80cae

<img width="598" alt="image" src="https://user-images.githubusercontent.com/5047891/168289829-dabf15fc-562b-4999-b4d1-35afbb4597c8.png">


```
Cannot read properties of undefined (reading 'closes'): TypeError: Cannot read properties of undefined (reading 'closes')
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsImpl.js:93:172
    at lastIndex (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/arrays.js:369:17)
    at findLast (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/arrays.js:359:21)
    at BracketPairsTextModelPart.findMatchingBracketUp (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsImpl.js:93:59)
    at Function._typeInterceptorElectricChar (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/cursor/cursorTypeOperations.js:674:50)
    at Function.typeWithInterceptors (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/cursor/cursorTypeOperations.js:826:32)
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/cursor/cursor.js:442:90
    at CursorsController._executeEdit (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/cursor/cursor.js:404:17)
    at CursorsController.type (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/cursor/cursor.js:433:18)
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:779:69
    at ViewModel._withViewEventsCollector (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:825:24)
    at ViewModel._executeCursorEdit (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:767:18)
    at ViewModel.type (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:779:18)
    at CodeEditorWidget._type (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:760:39)
    at CodeEditorWidget.trigger (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:701:26)
    at EditorHandlerCommand.runCommand (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/coreCommands.js:1523:20)
    at handler (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/editorExtensions.js:52:51)
    at idOrCommand.handler (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/commands/common/commands.js:35:28)
    at InstantiationService.invokeFunction (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:44:24)
    at CommandService._tryExecuteCommand (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/services/commands/common/commandService.js:81:59)
    at CommandService.executeCommand (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/services/commands/common/commandService.js:50:33)
    at Object.type (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1257:46)
    at ViewController.type (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/view/viewController.js:20:34)
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/controller/textAreaHandler.js:224:42
    at Listener.invoke (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:420:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:592:38)
    at Emitter.fire (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:557:37)
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/editor/browser/controller/textAreaInput.js:229:34
    at Listener.invoke (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:420:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:592:38)
    at Emitter.fire (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:557:37)
    at HTMLTextAreaElement.handler (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/browser/dom.js:118:39)
```
