### ISSUE TITLE
Cannot read properties of undefined (reading 'getRuntimeValue')

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#149438]
On launch, the following stack trace appears:

```
ERR Cannot read properties of undefined (reading 'getRuntimeValue'): TypeError: Cannot read properties of undefined (reading 'getRuntimeValue')
    at Workbench.isVisible (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/layout.js:679:45)
    at PanelPart.showOrHideViewContainer (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:236:40)
    at PanelPart.onDidRegisterPanels (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:153:22)
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:261:70
    at Listener.invoke (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:420:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:592:38)
    at Emitter.fire (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/base/common/event.js:557:37)
    at PaneCompositeRegistry.registerComposite (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/composite.js:211:33)
    at PaneCompositeRegistry.registerPaneComposite (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/panecomposite.js:141:19)
    at ViewsService.registerPaneComposite (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/parts/views/viewsService.js:505:86)
    at ViewsService.onDidRegisterViewContainer (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/parts/views/viewsService.js:76:18)
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/parts/views/viewsService.js:36:85
    at Array.forEach (<anonymous>)
    at new ViewsService (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/parts/views/viewsService.js:36:55)
    at InstantiationService._createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService._createServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:196:29)
    at InstantiationService._createServiceInstanceWithOwner (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:184:29)
    at InstantiationService._createAndCacheServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:174:47)
    at InstantiationService._safeCreateAndCacheServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:127:29)
    at InstantiationService._getOrCreateServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:114:29)
    at InstantiationService._createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:70:36)
    at InstantiationService.createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at new TextFileEditorModelManager (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/services/textfile/common/textFileEditorModelManager.js:61:78)
    at InstantiationService._createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService.createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at new AbstractTextFileService (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/services/textfile/browser/textFileService.js:43:67)
    at new NativeTextFileService (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/services/textfile/electron-sandbox/nativeTextFileService.js:20:13)
    at InstantiationService._createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:89:20)
    at InstantiationService._createServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:196:29)
    at InstantiationService._createServiceInstanceWithOwner (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:184:29)
    at InstantiationService._createAndCacheServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:174:47)
    at InstantiationService._safeCreateAndCacheServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:127:29)
    at InstantiationService._getOrCreateServiceInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:114:29)
    at InstantiationService._createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:70:36)
    at InstantiationService.createInstance (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:60:31)
    at WorkspaceService.acquireInstantiationService (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:333:69)
    at vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/workbench.js:119:42
    at InstantiationService.invokeFunction (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:44:24)
    at Workbench.initServices (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/workbench.js:114:34)
    at Workbench.startup (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/browser/workbench.js:61:51)
    at DesktopMain.open (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/workbench/electron-sandbox/desktop.main.js:54:52)
    at async vscode-file://vscode-app/Users/alex/src/vscode/out/bootstrap-window.js:183:6
```

`git bisect` points to 3dff256a53deeb7a42a7193d78b02de1baeb69d9:
```
3dff256a53deeb7a42a7193d78b02de1baeb69d9 is the first bad commit
commit 3dff256a53deeb7a42a7193d78b02de1baeb69d9
Author: SteVen Batten <6561887+sbatten@users.noreply.github.com>
Date:   Wed May 11 00:28:18 2022 -0700

    fixes #148899 (#149182)

 src/vs/workbench/browser/parts/panel/panelPart.ts | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)
```

**Comment by joaomoreno** [comment]
I get this 100% of the time starting Code OSS. Even after wiping my user data dir.
