### ISSUE TITLE
Cell shortcuts don't work after changing tab

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#149606]
## Environment data

-   VS Code version: 1.67.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1011282140
-   Python Extension version (available under the Extensions sidebar): v2022.6.1
-   OS (Windows | Mac | Linux distro) and version: MacOS Big Sur
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Cell shortcuts (a to add above, b to add below, etc) work even after changing tabs.

## Actual behaviour

If I change from another tab to my notebook tab (by clicking on it) cell shortcuts don't work afterwards, even if there is a selected cell (one marked with a thin line at its very left). I have to enter edit mode for the cell, then escape from it and only then shortcuts work again. Weirdly enough if I change tabs using Ctrl-Tab shortcuts work fine.

## Steps to reproduce:

1. Create a notebook and add a cell
2. Open a file in a new tab and select that tab
3. Go back to the notebook tab _by clicking on it_ 
4. Press `a`

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.67.1, undefined, desktop)
Jupyter Extension Version: 2022.4.1021342353.
Python Extension Version: 2022.6.2.
Workspace folder /Users/carlos/Documents/Jampp/Predex
info 9:22:16.353: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 9:22:19.336: Starting Notebook id = .jvsc74a57bd04cde68caf1bfab4168b5fc7a789e2f62521666dc763453355116f1fd4104d6f7./Users/carlos/.venv/bayes/python./Users/carlos/.venv/bayes/python.-m#ipykernel_launcher for /Users/carlos/Desktop/PyMC Scratch.ipynb (disableUI=true)
info 9:22:19.343: Creating raw notebook for /Users/carlos/Desktop/PyMC Scratch.ipynb
info 9:22:19.343: Computing working directory /Users/carlos/Desktop/PyMC Scratch.ipynb
info 9:22:19.343: Starting Notebook id = .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher for /Users/carlos/Desktop/Bayesian Explore.ipynb (disableUI=true)
info 9:22:19.343: Creating raw notebook for /Users/carlos/Desktop/Bayesian Explore.ipynb
info 9:22:19.343: Computing working directory /Users/carlos/Desktop/Bayesian Explore.ipynb
info 9:22:19.344: Starting Notebook id = .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher for /Users/carlos/Desktop/Jampp Scratch.ipynb (disableUI=true)
info 9:22:19.344: Creating raw notebook for /Users/carlos/Desktop/Jampp Scratch.ipynb
info 9:22:19.344: Computing working directory /Users/carlos/Desktop/Jampp Scratch.ipynb
info 9:22:19.377: Starting raw kernel bayes (Python 3.9.12) for interpreter /Users/carlos/.venv/bayes/bin/python
info 9:22:19.383: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
info 9:22:19.383: Starting raw kernel jampp (Python 3.9.12) for interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:19.435: Kernel launching with ports 9008,9009,9010,9011,9012. Start port is 9000
info 9:22:19.435: Starting raw kernel jampp (Python 3.9.12) for interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:19.451: Kernel launching with ports 9016,9017,9018,9019,9020. Start port is 9000
info 9:22:19.892: Process Execution: > ~/.venv/jampp/bin/python -m pip list
> ~/.venv/jampp/bin/python -m pip list
info 9:22:19.901: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 9:22:19.921: Process Execution: > ~/.venv/jampp/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/.venv/jampp/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 9:22:19.926: Process Execution: > ~/.venv/jampp/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/.venv/jampp/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 9:22:20.190: Process Execution: > ~/.venv/bayes/bin/python -m pip list
> ~/.venv/bayes/bin/python -m pip list
info 9:22:22.213: ipykernel version 6.13.0 for /Users/carlos/.venv/jampp/bin/python
info 9:22:22.213: ipykernel location ~/.venv/jampp/lib/python3.9/site-packages/ipykernel/__init__.py for /Users/carlos/.venv/jampp/bin/python
info 9:22:22.215: ipykernel version 6.13.0 for /Users/carlos/.venv/jampp/bin/python
info 9:22:22.215: ipykernel location ~/.venv/jampp/lib/python3.9/site-packages/ipykernel/__init__.py for /Users/carlos/.venv/jampp/bin/python
info 9:22:22.222: Adding env Variable PYTHONNOUSERSITE to /Users/carlos/.venv/jampp/bin/python
info 9:22:22.222: Adding env Variable PYTHONNOUSERSITE to /Users/carlos/.venv/jampp/bin/python
info 9:22:22.235: Process Execution: > ~/.venv/jampp/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"00370bcb-26cd-4dd4-8730-0c30a558eca0" --shell=9010 --transport="tcp" --iopub=9012 --f=/Users/carlos/Library/Jupyter/runtime/kernel-62330e7ro7O4zwULN.json
> ~/.venv/jampp/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"00370bcb-26cd-4dd4-8730-0c30a558eca0" --shell=9010 --transport="tcp" --iopub=9012 --f=/Users/carlos/Library/Jupyter/runtime/kernel-62330e7ro7O4zwULN.json
info 9:22:22.235: Process Execution: cwd: ~/Desktop
cwd: ~/Desktop
info 9:22:22.405: Process Execution: > ~/.venv/jampp/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9019 --control=9017 --hb=9016 --Session.signature_scheme="hmac-sha256" --Session.key=b"7aa7c4da-bef9-49ae-a449-f5b7418396e5" --shell=9018 --transport="tcp" --iopub=9020 --f=/Users/carlos/Library/Jupyter/runtime/kernel-62330BV5ql4Ba7icE.json
> ~/.venv/jampp/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9019 --control=9017 --hb=9016 --Session.signature_scheme="hmac-sha256" --Session.key=b"7aa7c4da-bef9-49ae-a449-f5b7418396e5" --shell=9018 --transport="tcp" --iopub=9020 --f=/Users/carlos/Library/Jupyter/runtime/kernel-62330BV5ql4Ba7icE.json
info 9:22:22.405: Process Execution: cwd: ~/Desktop
cwd: ~/Desktop
info 9:22:22.484: Process Execution: > ~/.venv/bayes/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/.venv/bayes/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 9:22:22.485: Adding env Variable PYTHONNOUSERSITE to /Users/carlos/.venv/bayes/bin/python
info 9:22:22.494: Process Execution: > ~/.venv/bayes/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"b3576d3b-9111-404e-8e1d-e0e7fec2660b" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/carlos/Library/Jupyter/runtime/kernel-623308sO92QLtAKON.json
> ~/.venv/bayes/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"b3576d3b-9111-404e-8e1d-e0e7fec2660b" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/carlos/Library/Jupyter/runtime/kernel-623308sO92QLtAKON.json
info 9:22:22.494: Process Execution: cwd: ~/Desktop
cwd: ~/Desktop
info 9:22:22.511: Registering dummy command feature
info 9:22:22.634: Preferred Remote kernel for /Users/carlos/Desktop/PyMC Scratch.ipynb is undefined
info 9:22:22.634: Find preferred kernel for /Users/carlos/Desktop/PyMC Scratch.ipynb with metadata {"interpreter":{"hash":"4cde68caf1bfab4168b5fc7a789e2f62521666dc763453355116f1fd4104d6f7"},"kernelspec":{"display_name":"Python 3.9.12 ('bayes')","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.9.12"},"orig_nbformat":4} & preferred interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:22.636: Preferred Remote kernel for /Users/carlos/Desktop/Jampp Scratch.ipynb is undefined
info 9:22:22.636: Find preferred kernel for /Users/carlos/Desktop/Jampp Scratch.ipynb with metadata {"interpreter":{"hash":"b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0"},"kernelspec":{"display_name":"Python 3.9.12 ('jampp')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"}} & preferred interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:22.682: Preferred Remote kernel for /Users/carlos/Desktop/Bayesian Explore.ipynb is undefined
info 9:22:22.682: Find preferred kernel for /Users/carlos/Desktop/Bayesian Explore.ipynb with metadata {"interpreter":{"hash":"b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0"},"kernelspec":{"display_name":"Python 3.9.12 ('jampp')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"}} & preferred interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:22.698: Preferred Remote kernel for /Users/carlos/Desktop/PyMC Scratch.ipynb is undefined
info 9:22:22.698: Preferred kernel .jvsc74a57bd04cde68caf1bfab4168b5fc7a789e2f62521666dc763453355116f1fd4104d6f7./Users/carlos/.venv/bayes/python./Users/carlos/.venv/bayes/python.-m#ipykernel_launcher is exact match
info 9:22:22.699: Preferred Remote kernel for /Users/carlos/Desktop/Jampp Scratch.ipynb is undefined
info 9:22:22.699: Preferred kernel .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher is exact match
info 9:22:22.733: Preferred Remote kernel for /Users/carlos/Desktop/Bayesian Explore.ipynb is undefined
info 9:22:22.733: Preferred kernel .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher is exact match
info 9:22:22.737: PreferredConnection: .jvsc74a57bd04cde68caf1bfab4168b5fc7a789e2f62521666dc763453355116f1fd4104d6f7./Users/carlos/.venv/bayes/python./Users/carlos/.venv/bayes/python.-m#ipykernel_launcher found for NotebookDocument: /Users/carlos/Desktop/PyMC Scratch.ipynb
info 9:22:22.737: TargetController found ID: .jvsc74a57bd04cde68caf1bfab4168b5fc7a789e2f62521666dc763453355116f1fd4104d6f7./Users/carlos/.venv/bayes/python./Users/carlos/.venv/bayes/python.-m#ipykernel_launcher for document /Users/carlos/Desktop/PyMC Scratch.ipynb
info 9:22:22.737: PreferredConnection: .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher found for NotebookDocument: /Users/carlos/Desktop/Jampp Scratch.ipynb
info 9:22:22.737: TargetController found ID: .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher for document /Users/carlos/Desktop/Jampp Scratch.ipynb
info 9:22:22.738: PreferredConnection: .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher found for NotebookDocument: /Users/carlos/Desktop/Bayesian Explore.ipynb
info 9:22:22.738: TargetController found ID: .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher for document /Users/carlos/Desktop/Bayesian Explore.ipynb
info 9:22:23.309: Registering dummy command feature
info 9:22:24.55: ipykernel version 6.13.0 for /Users/carlos/.venv/bayes/bin/python
info 9:22:24.55: ipykernel location ~/.venv/bayes/lib/python3.9/site-packages/ipykernel/__init__.py for /Users/carlos/.venv/bayes/bin/python
warn 9:22:26.933: StdErr from Kernel Process /Users/carlos/.venv/bayes/lib/python3.9/site-packages/traitlets/traitlets.py:2389: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/Users/carlos/.venv/bayes/lib/python3.9/site-packages/traitlets/traitlets.py:2343: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'b3576d3b-9111-404e-8e1d-e0e7fec2660b' instead of 'b"b3576d3b-9111-404e-8e1d-e0e7fec2660b"'.
  warn(

info 9:22:26.969: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-623308sO92QLtAKON.json

warn 9:22:27.46: StdErr from Kernel Process /Users/carlos/.venv/jampp/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/Users/carlos/.venv/jampp/lib/python3.9/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '00370bcb-26cd-4dd4-8730-0c30a558eca0' instead of 'b"00370bcb-26cd-4dd4-8730-0c30a558eca0"'.
  warn(

info 9:22:27.84: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-62330e7ro7O4zwULN.json

info 9:22:28.126: Started kernel bayes (Python 3.9.12), (Raw session started and connected)
info 9:22:28.127: Finished connecting 08f4fcea-9012-4d70-86e7-2427fceb8e29
warn 9:22:28.129: StdErr from Kernel Process /Users/carlos/.venv/jampp/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/Users/carlos/.venv/jampp/lib/python3.9/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '7aa7c4da-bef9-49ae-a449-f5b7418396e5' instead of 'b"7aa7c4da-bef9-49ae-a449-f5b7418396e5"'.
  warn(

info 9:22:28.129: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-62330BV5ql4Ba7icE.json

error 9:22:28.661: Failed to connect raw kernel session: Error: Interrupted system call
warn 9:22:28.729: Error occurred while trying to start the kernel, options.disableUI=true [r [Error]: 
	at new r (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:999024)
	at Function.from (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:999102)
	at m.createNotebook (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:432309)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async m.start (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:425898)
	at async Function.wrapKernelMethodImpl (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:458065)

Error: Interrupted system call
	at l.generateChannel (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:545788)
	at l.generateChannels (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:546478)
	at new t.RawSocket (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:544848)
	at new l (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:538034)
	at v._createSocket (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1332075)
	at new v (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1333801)
	at p (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:538179)
	at new t.RawSession (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:540491)
	at _.postStartRawSession (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:532592)
	at /Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:532526
	at Function.wrapAndReportProgress (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1042373)
	at _.startRawSession (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:532431)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)] {
  category: 'unknown',
  originalException: [Error: Interrupted system call
  	at l.generateChannel (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:545788)
  	at l.generateChannels (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:546478)
  	at new t.RawSocket (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:544848)
  	at new l (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:538034)
  	at v._createSocket (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1332075)
  	at new v (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1333801)
  	at p (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:538179)
  	at new t.RawSession (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:540491)
  	at _.postStartRawSession (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:532592)
  	at /Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:532526
  	at Function.wrapAndReportProgress (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1042373)
  	at _.startRawSession (/Users/carlos/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:532431)
  	at runMicrotasks (<anonymous>)
  	at processTicksAndRejections (node:internal/process/task_queues:96:5)] {
    errno: 4,
    code: 'EINTR',
    address: 'tcp://127.0.0.1:9009'
  }
}
info 9:22:28.758: Started kernel jampp (Python 3.9.12), (Raw session started and connected)
info 9:22:28.758: Finished connecting 08f4fcea-9012-4d70-86e7-2427fceb8e29
info 9:22:30.41: UpdateWorkingDirectoryAndPath in Kernel
info 9:22:30.42: UpdateWorkingDirectoryAndPath in Kernel
info 9:22:30.42: Initialize matplotlib for /Users/carlos/Desktop/PyMC Scratch.ipynb
info 9:22:30.42: Initialize matplotlib for /Users/carlos/Desktop/Jampp Scratch.ipynb
info 9:22:30.42: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/carlos/Desktop"\nif os.getcwd() not in sys.path:\nsys.path.insert
info 9:22:30.42: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/carlos/Desktop"\nif os.getcwd() not in sys.path:\nsys.path.insert
info 9:22:30.362: Preferred Remote kernel for /Users/carlos/Desktop/PyMC Scratch.ipynb is undefined
info 9:22:30.362: Find preferred kernel for /Users/carlos/Desktop/PyMC Scratch.ipynb with metadata {"interpreter":{"hash":"4cde68caf1bfab4168b5fc7a789e2f62521666dc763453355116f1fd4104d6f7"},"kernelspec":{"display_name":"Python 3.9.12 ('bayes')","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.9.12"},"orig_nbformat":4} & preferred interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:30.363: Preferred Remote kernel for /Users/carlos/Desktop/Jampp Scratch.ipynb is undefined
info 9:22:30.363: Find preferred kernel for /Users/carlos/Desktop/Jampp Scratch.ipynb with metadata {"interpreter":{"hash":"b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0"},"kernelspec":{"display_name":"Python 3.9.12 ('jampp')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"}} & preferred interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:30.364: Preferred Remote kernel for /Users/carlos/Desktop/Bayesian Explore.ipynb is undefined
info 9:22:30.364: Find preferred kernel for /Users/carlos/Desktop/Bayesian Explore.ipynb with metadata {"interpreter":{"hash":"b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0"},"kernelspec":{"display_name":"Python 3.9.12 ('jampp')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"}} & preferred interpreter /Users/carlos/.venv/jampp/bin/python
info 9:22:30.365: Preferred Remote kernel for /Users/carlos/Desktop/PyMC Scratch.ipynb is undefined
info 9:22:30.366: Preferred kernel .jvsc74a57bd04cde68caf1bfab4168b5fc7a789e2f62521666dc763453355116f1fd4104d6f7./Users/carlos/.venv/bayes/python./Users/carlos/.venv/bayes/python.-m#ipykernel_launcher is exact match
info 9:22:30.367: Preferred Remote kernel for /Users/carlos/Desktop/Jampp Scratch.ipynb is undefined
info 9:22:30.367: Preferred kernel .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher is exact match
info 9:22:30.368: Preferred Remote kernel for /Users/carlos/Desktop/Bayesian Explore.ipynb is undefined
info 9:22:30.368: Preferred kernel .jvsc74a57bd0b258a29ec3c18e2306cd4399cfd5a11854811f6b153278738a88f4812cc24ba0./Users/carlos/.venv/jampp/python./Users/carlos/.venv/jampp/python.-m#ipykernel_launcher is exact match
info 9:22:33.423: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/carlos/Desktop"\nif os.getcwd() not in sys.path:\nsys.path.insert
info 9:22:33.424: Waiting for idle on (kernel): 30b9880e-3d43-401e-b024-de5d6c7755e3 -> idle
info 9:22:33.424: Finished waiting for idle on (kernel): 30b9880e-3d43-401e-b024-de5d6c7755e3 -> idle
info 9:22:33.524: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/carlos/Desktop"\nif os.getcwd() not in sys.path:\nsys.path.insert
info 9:22:33.524: Waiting for idle on (kernel): 360ffe3e-16c9-4bf7-9635-e6b16b60ef52 -> idle
info 9:22:33.524: Finished waiting for idle on (kernel): 360ffe3e-16c9-4bf7-9635-e6b16b60ef52 -> idle
error 9:25:21.957: Live Notebook not available for /Users/carlos/Desktop/Bayesian Explore.ipynb

```

</p>
</details>

**Comment by roblourens** [comment]
This is technically from https://github.com/microsoft/vscode/commit/8632e9c4096eab5773958b9fb3f45f92efba74a8#diff-20e3a694a85df85603ec2c2ff18a925c290d4cc6bcaffccd437e4e2368bb5915R1828 @rebornix. document.body has the focus at this point. hasEditorFocus resets the editor focus context key to false. Then we focus the list element. Seems like that should trigger the focusTracker focus event, but it doesn't. So the context key is left at 'false'.
