### ISSUE TITLE
Unable to open files on FUSE-Drive | [main] [error] Error: write EPIPE

### ISSUE THREAD

**Issue by mbedded** [microsoft/vscode#149646]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version:  Linux Mint 20.3 Cinnamon

Steps to Reproduce:

1. Mount your Cryptomator vault (using FUSE)
2. Open a Textfile using VS Code
3. Application freezes and process has to be killed by hand

Logs:
```
[2022-05-16 17:20:40.203] [main] [error] [uncaught exception in main]: Error: write EPIPE
[2022-05-16 17:20:40.203] [main] [error] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.warn (node:internal/console/constructor:364:26)
    at p.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:3118)
    at m.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:5333)
    at St.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:61862)
    at v.unexpectedErrorHandler (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59135)
    at v.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:354)
    at D (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:615)
    at process.<anonymous> (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59216)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
[2022-05-16 17:20:40.203] [main] [error] [uncaught exception in main]: Error: write EPIPE
[2022-05-16 17:20:40.203] [main] [error] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.warn (node:internal/console/constructor:364:26)
    at p.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:3118)
    at m.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:5333)
    at St.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:61862)
    at v.unexpectedErrorHandler (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59135)
    at v.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:354)
    at D (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:615)
    at process.<anonymous> (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59216)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
[2022-05-16 17:20:40.203] [main] [error] [uncaught exception in main]: Error: write EPIPE
[2022-05-16 17:20:40.203] [main] [error] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.warn (node:internal/console/constructor:364:26)
    at p.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:3118)
    at m.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:5333)
    at St.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:61862)
    at v.unexpectedErrorHandler (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59135)
    at v.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:354)
    at D (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:615)
    at process.<anonymous> (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59216)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
[2022-05-16 17:20:40.203] [main] [error] [uncaught exception in main]: Error: write EPIPE
[2022-05-16 17:20:40.203] [main] [error] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.warn (node:internal/console/constructor:364:26)
    at p.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:3118)
    at m.error (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:31:5333)
    at St.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:61862)
    at v.unexpectedErrorHandler (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59135)
    at v.onUnexpectedError (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:354)
    at D (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:5:615)
    at process.<anonymous> (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:75:59216)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
```

EDIT/Additions:

- Other tools like vi, nano, xed or an IDE like Rider don't have such issues. They can open/read/write files without any issues
- The issue started around 1-2 months ago. Before that time VS Code had no issues to open my decrypted files

**Comment by mbedded** [comment]
Hello all,

today I opened a text-file from my cryptomator fault with the current version of VS Code.
It worked without any issues. The issue described above does not occur anymore. I don't know the source of this issue.

Because the Editor is working again as expected, I will close the issue.
Thank you and have a good day.
