### ISSUE TITLE
Invoking deltaDecorations recursively could lead to leaking decorations

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#149755]
Seeing this in the dev tools console

```
  ERR Invoking deltaDecorations recursively could lead to leaking decorations.: Error: Invoking deltaDecorations recursively could lead to leaking decorations.
    at rn.deltaDecorations (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:734:5005)
    at sn.deltaDecorations (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:11478)
    at U._doUpdate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2251:13391)
    at U.updateHover (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2251:11177)
    at G.onEditorMouseMove (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2251:17259)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2251:16615
    at p.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at l.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:18248
    at p.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at _emitOutgoingEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:204:127719)
    at _.emitOutgoingEvent (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:204:127282)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:739:43537
    at p.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at ne.endDeferredEmit (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:734:19073)
    at rn.deltaDecorations (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:734:5215)
    at sn.deltaDecorations (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:11478)
    at c.deltaDecorations (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:789:5077)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:789:4206
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30342
    at Object.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:9:8137)
    at i (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30055)
    at l.clear (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30574)
    at l.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:30512)
    at so._setVisibleData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:789:6489)
    at so.hide (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:789:7671)
    at ro.hide (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:789:2881)
    at mo._hideWidgets (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:790:125336)
    at mo._onEditorMouseMove (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:790:125057)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:790:123267
    at p.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at l.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at t.re.onMouseMove (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:20437)
    at t.emitMouseMove (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:161:13830)
    at R.emitMouseMove (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:687:55174)
    at C._onMouseMove (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:651:15033)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:651:12463
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:648:38919)
```

**Comment by alexdima** [comment]
Deminified using https://github.com/alexdima/vscode-stack-beautifier

ERR&nbsp;Invoking&nbsp;deltaDecorations&nbsp;recursively&nbsp;could&nbsp;lead&nbsp;to&nbsp;leaking&nbsp;decorations.:&nbsp;Error:&nbsp;Invoking&nbsp;deltaDecorations&nbsp;recursively&nbsp;could&nbsp;lead&nbsp;to&nbsp;leaking&nbsp;decorations.<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/model/textModel.ts:1620:22`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/common/model/textModel.ts#L1620)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1289:31`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1289)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/contrib/comments/browser/commentsEditorContribution.ts:244:30`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./workbench/contrib/comments/browser/commentsEditorContribution.ts#L244)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/contrib/comments/browser/commentsEditorContribution.ts:166:8`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./workbench/contrib/comments/browser/commentsEditorContribution.ts#L166)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/contrib/comments/browser/commentsEditorContribution.ts:382:33`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./workbench/contrib/comments/browser/commentsEditorContribution.ts#L382)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/contrib/comments/browser/commentsEditorContribution.ts:369:65`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./workbench/contrib/comments/browser/commentsEditorContribution.ts#L369)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1651:39`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1651)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:64:17`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/common/viewModelEventDispatcher.ts#L64)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:39:7`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/common/viewModelEventDispatcher.ts#L39)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModel/viewModelImpl.ts:463:25`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/common/viewModel/viewModelImpl.ts#L463)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/model/textModel.ts:2339:17`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/common/model/textModel.ts#L2339)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/model/textModel.ts:1625:32`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/common/model/textModel.ts#L1625)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1289:31`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1289)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/contentHover.ts:294:23`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/contentHover.ts#L294)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/contentHover.ts:246:38`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/contentHover.ts#L246)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:170:3`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/lifecycle.ts#L170)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/functional.ts:17:14`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/functional.ts#L17)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:139:7`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/lifecycle.ts#L139)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:214:3`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/lifecycle.ts#L214)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/lifecycle.ts:199:7`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/lifecycle.ts#L199)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/contentHover.ts:390:33`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/contentHover.ts#L390)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/contentHover.ts:443:8`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/contentHover.ts#L443)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/contentHover.ts:167:15`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/contentHover.ts#L167)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/hover.ts:206:23`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/hover.ts#L206)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/hover.ts:189:7`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/hover.ts#L189)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/hover/browser/hover.ts:81:78`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/contrib/hover/browser/hover.ts#L81)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:575:16`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L575)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:779:21`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L779)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:740:23`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./base/common/event.ts#L740)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1756:61`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1756)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/view/viewUserInputEvents.ts:55:8`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/view/viewUserInputEvents.ts#L55)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/view/viewController.ts:305:23`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/view/viewController.ts#L305)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/controller/mouseHandler.ts:216:22`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/controller/mouseHandler.ts#L216)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/controller/mouseHandler.ts:82:82`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/controller/mouseHandler.ts#L82)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/editorDom.ts:182:63`](https://github.com/Microsoft/vscode/blob/c23f0305dbf82b2319b198f4dbf3c5d5bc522f15/src/vs/./editor/browser/editorDom.ts#L182)<br/>
