### ISSUE TITLE
host.getGlobalTypingsCacheLocation is not a function

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#149961]
```
 ERR <semantic> TypeScript Server Error (4.8.0-dev.20220518)
host.getGlobalTypingsCacheLocation is not a function
TypeError: host.getGlobalTypingsCacheLocation is not a function
    at isNotShadowedByDeeperNodeModulesPackage (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129231:45)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129124:83
    at Array.filter (<anonymous>)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129124:51
    at Map.forEach (<anonymous>)
    at Object.search (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129119:28)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133499:32
    at resolvingModuleSpecifiers (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:131556:26)
    at collectAutoImports (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133498:17)
    at getGlobalCompletions (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133402:17)
    at tryGetGlobalSymbols (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133300:25)
    at getCompletionData (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133044:22)
    at Object.getCompletionsAtPosition (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:131625:34)
    at Object.getCompletionsAtPosition (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:164721:35)
    at Proxy.getCompletionsAtPosition (/Users/yutengjing/.vscode-insiders/extensions/vue.vscode-typescript-vue-plugin-0.34.15/out/index.js:92152:47)
    at Object.apply (/Users/yutengjing/.vscode-insiders/extensions/vue.vscode-typescript-vue-plugin-0.34.15/out/index.js:92419:27)
    at IpcIOSession.Session.getCompletions (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:176511:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:175186:61)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177243:88
    at IpcIOSession.Session.executeWithRequestId (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177234:28)
    at IpcIOSession.Session.executeCommand (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177243:33)
    at IpcIOSession.Session.onMessage (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177269:35)
    at process.<anonymous> (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:179904:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21): Error: <semantic> TypeScript Server Error (4.8.0-dev.20220518)
host.getGlobalTypingsCacheLocation is not a function
TypeError: host.getGlobalTypingsCacheLocation is not a function
    at isNotShadowedByDeeperNodeModulesPackage (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129231:45)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129124:83
    at Array.filter (<anonymous>)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129124:51
    at Map.forEach (<anonymous>)
    at Object.search (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:129119:28)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133499:32
    at resolvingModuleSpecifiers (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:131556:26)
    at collectAutoImports (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133498:17)
    at getGlobalCompletions (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133402:17)
    at tryGetGlobalSymbols (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133300:25)
    at getCompletionData (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:133044:22)
    at Object.getCompletionsAtPosition (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:131625:34)
    at Object.getCompletionsAtPosition (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:164721:35)
    at Proxy.getCompletionsAtPosition (/Users/yutengjing/.vscode-insiders/extensions/vue.vscode-typescript-vue-plugin-0.34.15/out/index.js:92152:47)
    at Object.apply (/Users/yutengjing/.vscode-insiders/extensions/vue.vscode-typescript-vue-plugin-0.34.15/out/index.js:92419:27)
    at IpcIOSession.Session.getCompletions (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:176511:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:175186:61)
    at /Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177243:88
    at IpcIOSession.Session.executeWithRequestId (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177234:28)
    at IpcIOSession.Session.executeCommand (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177243:33)
    at IpcIOSession.Session.onMessage (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:177269:35)
    at process.<anonymous> (/Users/yutengjing/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220518/node_modules/typescript/lib/tsserver.js:179904:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
	at Function.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:505537)
	at dispatchResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:499385)
	at dispatchMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:498253)
	at ChildProcess.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:497738)
	at ChildProcess.emit (node:events:390:28)
	at emit (node:internal/child_process:917:12)
	at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

versions:

```
MacOS: 12.3.1
VSCode: 1.68.0-insider
Typescript: 4.6.4
```

**Comment by tjx666** [comment]
@mjbvz
