### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Cannot resolve authority)

### ISSUE THREAD

**Issue by killshot13** [microsoft/vscode#150169]
Issue Type: <b>Bug</b>

Scenario: Reviewing/editing user-level VSCode settings in the `settings.json` file (`C:\Users\%USERPROFILE%\AppData\Roaming\Code\User\settings.json`) from <b>within a WSL window</b>.
Possibly related to #135021

Steps to Reproduce: 
1. Open `settings.json` and make some edits without saving them.
2. Open Extensions in the primary sidebar.
3. Find and install a new extension that "Requires Reload" after installing.
4. Without saving the `settings.json` file, click `Requires Reload` and let the window reload.
5. Wait until you see the pop-up stating, "Could not automatically save because the file's contents are newer."
<button>Review</button><button>Overwrite</button>
6. Overwrite the file by selecting the option in the pop-up.
7. Wait until you see the model stating "Lost connection to host server."
<button>Wait</button><button>Close & Reopen/Reload</button>
8. Force reopen the WSL window by selecting the reopen/reload option in the model.

Actual Results: Lower left-hand corner displays `⚠️ Disconnected from WSL`, and a pop-up in the lower right-hand corner reads as follows.

>Failed to connect to the remote extension host server (Error: Cannot resolve authority)

Expected: VSCode reopens after (presumably) saving the changes to the `setting.json` file. The new WSL window renders based on the latest changes made to the user settings.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: Yes

Extensions: none<details>

<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

![devtools-console-main-error-feed(2)](https://user-images.githubusercontent.com/47695475/169800190-ae17f778-307c-40f6-86dc-ee2d19e19fc5.png)
![devtools-console-main-error-feed](https://user-images.githubusercontent.com/47695475/169800196-e20cda93-3fb4-42d5-921c-d1bc36201a49.png)
![editor_view](https://user-images.githubusercontent.com/47695475/169800201-feef061f-c397-4d03-b138-7e6f04775332.png)
![preload-fetch-error-invalid-channel](https://user-images.githubusercontent.com/47695475/169800203-af31e124-5561-4993-87c9-8885919ca593.png)

**Comment by killshot13** [comment]
I've only been able to reproduce my bug twice. Both times I was inside of a workspace, so that may have been a contributing factor. Good  I had not thought of that before.

However I know there are other workspace related issues; the File Watcher constantly loses focus within an open workspace, for example, so its definitely worth looking into.

I'll attempt to repro with just a regular folder open vs a workspace if I get the chance.

**Comment by sjohnsonaz** [comment]
I figured it out.  I receive `Error: Handler already set!` when I have the **Call Stack** placed inside the **Secondary Side Bar**.  If I move the **Call Stack** back to its original location, everything works correctly.

**Comment by aeschli** [comment]
Good catch! I can reproduce by putting the Call Stack in the secondary side bar.
```
  ERR Handler already set!: Error: Handler already set!
    at m.setHandler (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1704:26222)
    at v.registerListeners (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1759:18461)
    at new v (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1759:17732)
    at S._createInstance (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:594:1332)
    at S.createInstance (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:594:773)
    at new J (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2161:60479)
    at S._createInstance (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:594:1332)
    at vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:594:3508
    at W._executor (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:71:20675)
    at W.get value [as value] (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:71:20872)
    at Object.get (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:594:3609)
    at $.renderBody (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2158:9888)
    at $.render (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:219:18106)
    at $.render (vscode-file://vscode-app/c:/Users/martinae/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2117:29001)
    at P.onDidAddViewDescriptors (vscode-file://vscode-
```

**Comment by roblourens** [comment]
I suspect this is the same as https://github.com/microsoft/vscode/issues/148593, cool

**Comment by Fasteroid** [comment]
This seems to also happen for me whenever I try to remote SSH into my server with a local window open.  Weird.

**Comment by sbatten** [comment]
I believe this issue no longer reproduces in latest insiders.

**Comment by sbatten** [comment]
@elranu are you using the latest insiders?
