### ISSUE TITLE
Shell integration failed warning when tasks are run

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#150194]
We should make sure not telemetry gets sent in this case as task (and debug) terminals are special in that they never inject shell integration.

![image](https://user-images.githubusercontent.com/2193314/169848531-ce8b0bcd-391e-407b-82bf-0d2e0e3edc97.png)

**Comment by meganrogge** [comment]
we should probably not create the addon for any of these (besides options.enabled) https://github.com/microsoft/vscode/blob/5357dcfc04ddfce12661dca80ae9a104640a2c7e/src/vs/platform/terminal/node/terminalEnvironment.ts#L113

**Comment by Tyriar** [comment]
I think we should still create it, just not send failure telemetry. Consider the manual setup route where someone injects the script themselves. We should light up shell integration command decorations, etc. regardless of the type of terminal if the user runs the script themselves.

**Comment by meganrogge** [comment]
```
[47781:0523/140306.974060:INFO:CONSOLE(104)] "%c[IPC Library: Pty Host] %cUncaught Exception:  color: blue color:  TypeError: this._logService.warn is not a function
    at Timeout._onTimeout (/Users/meganrogge/Repos/vscode/out/vs/platform/terminal/common/xterm/shellIntegrationAddon.js:220:38)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)", source: vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/base/common/console.js (104)

  "%c[IPC Library: Pty Host] %cUncaught Exception:  color: blue color:  TypeError: this._logService.debug is not a function
    at CommandDetectionCapability.handleCommandFinished (/Users/meganrogge/Repos/vscode/out/vs/platform/terminal/common/capabilities/commandDetectionCapability.js:323:30)
    at ShellIntegrationAddon._doHandleVSCodeSequence (/Users/meganrogge/Repos/vscode/out/vs/platform/terminal/common/xterm/shellIntegrationAddon.js:157:71)
    at ShellIntegrationAddon._handleVSCodeSequence (/Users/meganrogge/Repos/vscode/out/vs/platform/terminal/common/x
```

Seeing these - not sure if it's a new issue

**Comment by joyceerhl** [comment]
I think I just reproed this https://github.com/microsoft/vscode/issues/151163 feel free to close that one in favor of this issue

**Comment by meganrogge** [comment]
This was about whether or not the failure warning shows up in the console. I'll fix that issue separately and reopen if you see the error in the picture above.
