### ISSUE TITLE
FileSystemError when git tries to read config from a remote folder

### ISSUE THREAD

**Issue by chemelli74** [microsoft/vscode#150137]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.67.2
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Open a remote folder via `\\hostname\folder1\folder2`
2. Check you have a `.git` folder inside
3. Go to Source Control
4. The folder currently open doesn't have a git reporsitory

I noticed using F1 -> Developer Tools that there is a extra <host> in the path:

Unknown (FileSystemError) (FileSystemError): Error: UNKNOWN: unknown error, stat '**\\\hostname\hostname**\homeassistant\config\.git\config'
	at Function._handleError (c:\Users\login\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:90763)
	at Object.stat (c:\Users\login\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:88691)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)	at async Object.isFile (c:\Users\login\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\extension\extension.js:391:30873)
	at async mw (c:\Users\login\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\extension\extension.js:201:312)
	at async sT (c:\Users\login\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\extension\extension.js:201:1076)
	at async sb (c:\Users\login\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\extension\extension.js:372:4638)
	at async zV (c:\Users\login\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\extension\extension.js:459:8570)
	at async c:\Users\login\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\extension\extension.js:458:12794

Simone

**Comment by chemelli74** [comment]
Any progress ?

Thank you,

Simone

**Comment by lszomoru** [comment]
@chemelli74, are you able to reproduce this with the latest Stable version (1.70)?

**Comment by chemelli74** [comment]
Confirmed to be working now.

Thx for fixing!

Simone
