### ISSUE TITLE
Improve setting sync experience with more error handing

### ISSUE THREAD

**Issue by guluguru** [microsoft/vscode#150252]
Syncing setting will failed and no hint while keybindings.json has an error, for example:
```json
{}
```
> It should be an array, such as []

There is no hint told you need to fix your keybindings, it only says "o is not iterable", after seeing [this](https://github.com/microsoft/vscode/issues/103839#issuecomment-670012275) I found what iccur such an error, but most time people may think that is a bug.

**Comment by TIMONz1535** [comment]
Yeah
I don't have any **User tasks**. VS Code tries to synchronize them and does it every minute! The servers says "I'm a spammer" and denied everything off.
Two weeks later, I find out that the synchronization just fell off...... >:(
When connecting, I was asked only three options
- do you want to replace your own with a cloud?
- want to merge?
- cancel.

Of course, I don't want to replace my data with old cloud data, and I clicked the only one not fatal "merge" and **a lot of garbage returned to my work environment**.

**GREAT EXPERIENCE** 👍👍👍👍👍👍👍

**Comment by sandy081** [comment]
@TIMONz1535 Can you please file a separate issue for your scenario and please provide us steps to reproduce.

**Comment by sandy081** [comment]
@guluguru It is expected to show following notification when there are errors in the files while syncing

<img width="466" alt="image" src="https://user-images.githubusercontent.com/10746682/170841044-e4b6ec6c-42e0-4179-b969-db04d8527551.png">

It seems, in this particular case, this is not being shown. Fixed it [here](https://github.com/microsoft/vscode/pull/150615)

**Comment by joyceerhl** [comment]
When I set the contents of the user settings.json to `[]`, I get this in the logs but no obvious error notification, is that expected?

```
[2022-06-02 13:55:52.658] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-06-02 13:55:52.750] [settingssync] [error] LocalInvalidContent (UserDataSyncError) syncResource:settings operationId:unknown: Üñæþlë tø sÿñç sëttïñgs æs thërë ærë ërrørs/wærñïñg ïñ sëttïñgs fïlë.
    at w.validateContent (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:112771)
    at w.generateSyncPreview (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:107189)
    at async w.doGenerateSyncResourcePreview (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:56974)
```

**Comment by sandy081** [comment]
You shall see the error notification, but you have to close the `settings.json` file to get this notification.

**Comment by joyceerhl** [comment]
👍 I see the error notification 
![image](https://user-images.githubusercontent.com/30305945/171957037-da03443f-8440-475a-ae18-12a38279eca4.png)
