### ISSUE TITLE
[CustomTextEditor Web extensions] "EntryNotFound (FileSystemError): File does not exist" after reloading vscode.dev and reopening untitled document in custom text editor

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode#150359]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: Chrome

[CustomTextEditor Web extensions] "EntryNotFound (FileSystemError): File does not exist" after reloading vscode.dev and reopening untitled document in custom text editor

Steps to Reproduce:

1. Go to https://vscode.dev and install some CustomTextEditor extension like [Pipeline Editor](https://marketplace.visualstudio.com/items?itemName=Cloud-pipelines.pipeline-editor-vscode) (or Draw.io)
2. Create new untitled tab an add `{}` content
3. Press F5 to reload the page
4. Observe that the Untitled-1 tab has reloaded and the `{}` content was preserved
5. Right-click on tab and choose "Reopen Editor with..." and select "Cloud Pipeline Editor"
6. ! The tab shows "... unexpected error: File does not exist"
7. Reload the page again
8. Observe that the the Untitled-1 tab is now gone along with the data

```
[window] [error] File does not exist: EntryNotFound (FileSystemError): File does not exist
    at n (https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/workbench/workbench.web.main.js:590:15674)
    at https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/workbench/workbench.web.main.js:590:28471
    at Function.i._invokeFactory (https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js:5:1626)
    at i.complete (https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js:5:1821)
    at i._onModuleComplete (https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js:6:991)
    at i._resolve (https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js:6:510)
    at i.defineModule (https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js:5:6142)
    at v (https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js:6:1702)
    at https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/workbench/workbench.web.main.js:590:28239
    at https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/workbench/workbench.web.main.js:3187:11239
```

![image](https://user-images.githubusercontent.com/1829149/170238724-46b97d30-c128-4c98-9cc7-1657f168ae2a.png)

https://user-images.githubusercontent.com/1829149/170239268-72bd934e-225c-4060-ade9-31d56c028d39.mp4

**Comment by ThereWeGo** [comment]
same issue to me
