### ISSUE TITLE
TS Server fatal error:  Cannot read properties of undefined (reading 'Symbol(#readFile)')

### ISSUE THREAD

**Issue by Lance1997** [microsoft/vscode#150311]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.7.1-rc

**Steps to reproduce crash**
1. Launch vscode-insiders with a new project from `npx imba create hello-world`

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
TypeError: Cannot read properties of undefined (reading 'Symbol(#readFile)')
    at readFile (/home/lance/.vscode-insiders/extensions/scrimba.vsimba-3.1.14/node_modules/typescript-imba-plugin/dist/index.js:13046:7233)
    at Object.projectService.host.readFile (/home/lance/.vscode-insiders/extensions/svelte.svelte-vscode-105.16.1/node_modules/typescript-svelte-plugin/dist/src/svelte-snapshots.js:282:24)
    at getText (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168187:92)
    at TextStorage.getFileTextAndSize (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168199:32)
    at TextStorage.getFileTextAndSize (/home/lance/.vscode-insiders/extensions/scrimba.vsimba-3.1.14/node_modules/typescript-imba-plugin/dist/index.js:13046:6064)
    at TextStorage.reloadWithFileText (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168110:31)
    at TextStorage.getOrLoadText (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168223:26)
    at TextStorage.getSnapshot (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168148:57)
    at ScriptInfo.getSnapshot (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168309:41)
    at ScriptInfo.getSnapshot (/home/lance/.vscode-insiders/extensions/scrimba.vsimba-3.1.14/node_modules/typescript-imba-plugin/dist/index.js:13046:5962)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168987:39)
    at HostCache.createEntry (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164016:44)
    at HostCache.getOrCreateEntryByPath (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164039:58)
    at getOrCreateSourceFileByPath (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164466:66)
    at Object.getOrCreateSourceFile [as getSourceFile] (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164459:24)
    at findSourceFileWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:118041:29)
    at findSourceFile (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:117939:26)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:117891:85
    at getSourceFileFromReferenceWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:117857:34)
    at processSourceFile (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:117891:13)
    at processRootFile (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:117692:13)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:116537:25
    at Object.forEach (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:183:30)
    at Object.createProgram (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:116536:24)
    at synchronizeHostData (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164389:26)
    at Proxy.getProgram (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164521:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169589:53)
    at InferredProject.Project.updateGraph (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:169517:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171819:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173511:26)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173785:97
    at Object.flatMap (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173785:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174920:46)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177109:88
    at IpcIOSession.Session.executeWithRequestId (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177100:28)
    at IpcIOSession.Session.executeCommand (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177109:33)
    at IpcIOSession.Session.onMessage (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177135:35)
    at process.<anonymous> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179770:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.68.0-insider (17c75e11805103026b943c8dc4d50a35f245f76f, 2022-05-20T05:16:13.965Z)
OS version: Linux x64 5.10.106-15290-g6e9d70c8a9b4
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|6.49GB (6.47GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0506bdf0-9ff9-4ef0-a423-9205fc2dbe4e|
|Screen Reader|no|
|VM|33%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
packer|4op|0.3.0
better-comments|aar|3.0.0
laravel-extra-intellisense|ami|0.6.2
ng-template|Ang|13.3.4
vscode-intelephense-client|bme|1.8.2
tailwindshades|bou|0.0.5
vscode-tailwindcss|bra|0.8.4
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.7
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.3
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.23.5969
go|gol|0.33.1
terraform|has|2.22.0
better-cpp-syntax|jef|1.15.14
solidity|Jua|0.0.139
tailwind-sass-syntax|mac|1.3.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.22.0
python|ms-|2022.7.11441011
vscode-pylance|ms-|2022.5.2
azure-account|ms-|0.10.1
cmake-tools|ms-|1.10.5
cpptools|ms-|1.10.3
cpptools-extension-pack|ms-|1.2.0
makefile-tools|ms-|0.5.0
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.17.0
prisma|Pri|3.14.0
vscode-thunder-client|ran|1.16.4
vsimba|scr|3.1.14
markdown-preview-enhanced|shd|0.6.3
laravel-goto-controller|ste|0.0.15
autoimport|ste|1.5.4
svelte-vscode|sve|105.16.1
es6-string-html|Tob|2.12.0
pdf|tom|1.2.0
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
php-debug|xde|1.26.1
php-pack|xde|1.0.3
php-intellisense|zob|1.0.8

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506

```

</details>

**Comment by mjbvz** [comment]
This is caused by the `typescript-imba-plugin` (or whatever extension contributes it)

Please file the issue against them
