### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by soumyaarao17** [microsoft/vscode#150337]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57011:22)
    at getPropertyOfType (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57671:24)
    at resolveESModuleSymbol (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49817:54)
    at getTargetOfNamespaceImport (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49236:28)
    at resolveAlias (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at getSymbol (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47838:38)
    at resolveNameHelper (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48131:34)
    at resolveName (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48114:20)
    at resolveEntityName (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49453:42)
    at resolveEntityName (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49461:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49413:24)
    at getTargetOfImportEqualsDeclaration (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48865:28)
    at getTargetOfAliasDeclaration (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49232:28)
    at resolveAlias (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49281:30)
    at resolveSymbol (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49271:67)
    at mergeSymbol (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47624:42)
    at /private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeSymbol (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47648:21)
    at /private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47737:20)
    at mergeModuleAugmentation (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47753:17)
    at initializeTypeChecker (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85046:25)
    at Object.createTypeChecker (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47395:9)
    at Object.getTypeChecker (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114404:79)
    at synchronizeHostData (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159898:21)
    at Object.getProgram (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:168762:44)
    at /private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:97
    at Object.flatMap (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170260:46)
    at /private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> (/private/var/folders/mk/41m8dhrx2rx22b9wgv2gys6w0000gn/T/AppTranslocation/287ED086-1C29-4D2C-86ED-6E593A1244AD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by mjbvz** [comment]
Closing as this is an old TS version
