### ISSUE TITLE
Terminal shell integration smoke tests flaky

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#150478]
Probably due to https://github.com/microsoft/vscode/pull/150469, I can only test on macOS atm.

**Comment by Tyriar** [comment]
Other ones failing too 😭 

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=172255&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5&l=139

**Comment by Tyriar** [comment]
The screenshot taken in the [macOS success test failure](https://dev.azure.com/vscode/VSCode/_build/results?buildId=64973&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=4ab01ce0-1b21-5f68-4297-21a317863be2&l=137) actually shows command decorations worked fine, why did the assertion fail?

```
  56 passing (7m)
  8 pending
  1 failing

  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Shell integration
             Decorations
               Should show default icons
                 Success:
     Error: Timeout: get elements '.terminal-command-decoration.codicon-circle-outline' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:254:11)
      at Code.waitForElements (/Users/runner/work/1/s/test/automation/src/code.ts:203:10)
      at Terminal.assertCommandDecorations (/Users/runner/work/1/s/test/automation/src/terminal.ts:219:4)
      at Context.<anonymous> (src/areas/terminal/terminal-shellIntegration.test.ts:41:7)
```

![image](https://user-images.githubusercontent.com/2193314/171881738-ec070799-b658-4728-b4b2-65dfcc98b834.png)

**Comment by Tyriar** [comment]
Very hard to reproduce this with my prompt setup but if I remove that and go to the bash default I ended up getting 5 decorations, 2 for ls at the top, 3 for the placeholder at the bottom. Resizing added even more.

**Comment by Tyriar** [comment]
What's written to the terminal when these 5 decorations appear:

```
xterm.js: parsing data "l"
xterm.js: parsing data "s"
xterm.js: parsing data "
"
xterm.js: parsing data "]633;C"
xterm.js: parsing data "]633;D;0]633;P;Cwd=/Users/daimms/dev/Microsoft/vscode"
xterm.js: parsing data "[?2004h]633;A]633;A]0;daimms@Daniels-MacBook-Pro: ~/dev/Microsoft/vscodebash-5.1$ ]633;B]633;B"
xterm.js: parsing data "ls
[?2004l
"
xterm.js: parsing data "]633;C"
xterm.js: parsing data "CONTRIBUTING.md		out
LICENSE.txt		package.json
README.md		product.json
SECURITY.md		remote
ThirdPartyNotices.txt	resources
build			scripts
cglicenses.json		src
cgmanifest.json		test
extensions		tsfmt.json
gulpfile.js		yarn.lock
node_modules
"
xterm.js: parsing data "]633;D;0]633;P;Cwd=/Users/daimms/dev/Microsoft/vscode"
xterm.js: parsing data "[?2004h]633;A]633;A]633;A]0;daimms@Daniels-MacBook-Pro: ~/dev/Microsoft/vscodebash-5.1$ ]633;B]633;B]633;B"
```

I see 2 A/B sequences at the top and 3 A/B sequences at the bottom
