### ISSUE TITLE
Flaky: Terminal Smoke Tests (Web)  Shell integration

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#150742]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=172426&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=63d40075-f8bd-5843-b20c-bf914eb0111d

```
  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Shell integration
             Decorations
               Should show default icons
                 Error:
     Error: Timeout: get elements '.terminal-command-decoration.codicon-circle-outline' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:254:11)
      at Code.waitForElements (/Users/runner/work/1/s/test/automation/src/code.ts:203:10)
      at Terminal.assertCommandDecorations (/Users/runner/work/1/s/test/automation/src/terminal.ts:219:4)
      at Context.<anonymous> (src/areas/terminal/terminal-shellIntegration.test.ts:46:7)
```

**Comment by Tyriar** [comment]
Disabling in #150846, moving proper fix to June
