### ISSUE TITLE
Merge editor: Error: Model is disposed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150817]
Testing #150389

Steps:
* open a merge editor
* switch to 3 column layout
* accept a change by clicking checkbox
* unaccept a change by clicking the same checkbox
* close the editor without saving

```
 ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/model/textModel.js:243:23)
    at TextModel.getLineContent (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/model/textModel.js:539:18)
    at LineDiff.getModifiedLines (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model.js:160:52)
    at LineDiff.getLineEdit (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model.js:152:58)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:96:68
    at Array.map (<anonymous>)
    at MergeEditorModel.computeState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:96:55)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:70:42
    at transaction (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/audioCues/browser/observable.js:45:13)
    at MergeEditorModel.recomputeState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:65:42)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:60:22
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:420:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:592:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:557:37)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:156:49
```

**Comment by hediet** [comment]
I also observed this. @jrieken can you look into this?

**Comment by jrieken** [comment]
Full (source) stack trace

```
ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:243:23)
    at TextModel.getLineContent (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:539:18)
    at LineRange.getLines (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/model.js:109:35)
    at LineDiff.getModifiedLines (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/model.js:183:39)
    at LineDiff.getLineEdit (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/model.js:177:58)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:106:68
    at Array.map (<anonymous>)
    at MergeEditorModel.computeState (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:106:55)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:71:42
    at transaction (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/audioCues/browser/observable.js:45:13)
    at MergeEditorModel.recomputeState (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:66:42)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:60:22
    at Listener.invoke (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:420:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:592:38)
    at Emitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:557:37)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.js:205:49
```

**Comment by jrieken** [comment]
The underlying issue that the [`resultTextModel`](https://github.com/microsoft/vscode/blob/30aa8cc0fb7482d2e0c7fc3516b5dd4c0cd76ff4/src/vs/workbench/contrib/mergeEditor/browser/mergeEditorModel.ts#L328) is disposed, still firing event, but not readable anymore. The listener is definitly leaking but it also should fire anymore

<img width="736" alt="Screenshot 2022-06-09 at 12 11 15" src="https://user-images.githubusercontent.com/1794099/172823357-980323de-086e-41b2-878c-0f36b665c289.png">
