### ISSUE TITLE
Closing Interactive window opens terminal

### ISSUE THREAD

**Issue by hookxs** [microsoft/vscode#150881]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Since one of the latest updates whenever I close the Interactive window (by clicking the X of the tab, not by ctrl+f4) a new terminal window is opened (unless it already exists).

### VS Code Version

Version: 1.67.1 (user setup) Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d Date: 2022-05-06T12:37:03.389Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.4.1011282140

### Jupyter logs

```shell
Visual Studio Code (1.67.1, undefined, desktop)
Jupyter Extension Version: 2022.4.1011282140.
Python Extension Version: 2022.6.1.
Workspace folder c:\Users\xxx\Box Sync\Python\ais
error 12:32:2.952: Exception while attempting zmq : [Error: The specified module could not be found.
\\?\c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node
	at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
	at Object.Module._extensions..node (node:internal/modules/cjs/loader:1246:18)
	at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:32307)
	at Function.b._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:28750)
	at Function._._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:61719)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at load (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\node-gyp-build\index.js:1:628)
	at Object.<anonymous> (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\zeromq\lib\native.js:1:198)
	at Module.u._compile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:32307)
	at Function.b._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:28750)
	at Function._._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:61719)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.<anonymous> (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\zeromq\lib\index.js:1:144)
	at Module.u._compile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:32307)
	at Function.b._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:28750)
	at Function._._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:61719)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.92747 (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4028080)
	at __webpack_require__ (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4801729)
	at u.zmqSupported (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:539428)
	at u.isSupportedForLocalLaunch (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:539171)
	at u.get isSupported [as isSupported] (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:539081)
	at t.registerTypes (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:551117)
	at c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4806637
	at c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4807386
	at c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4807394
	at e.activate (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4807516)
	at Function._callActivateOptional (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:17454)
	at Function._callActivate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:17119)
	at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:14937
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _activate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8122)
	at async _initialize (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:7486)] {
  code: 'ERR_DLOPEN_FAILED'
}
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 12:32:3.226: Old kernelSpecs (created by Jupyter extension) stored in directory C:\Users\xxx\AppData\Roaming\jupyter\kernels\__old_vscode_kernelspecs
info 12:32:3.232: Attempting to start a server because of preload conditions ...
info 12:32:3.255: Checking for server existence.
info 12:32:3.255: Checking for server usability.
info 12:32:3.256: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 12:32:3.970: Process Execution: > ~\miniconda3\envs\ais\python.exe -m pip list
> ~\miniconda3\envs\ais\python.exe -m pip list
info 12:32:3.972: Process Execution: > ~\miniconda3\envs\ais\python.exe -c "import jupyter"
> ~\miniconda3\envs\ais\python.exe -c "import jupyter"
info 12:32:3.975: Process Execution: > ~\miniconda3\envs\ais\python.exe -c "import notebook"
> ~\miniconda3\envs\ais\python.exe -c "import notebook"
info 12:32:4.210: Process Execution: > ~\miniconda3\envs\ais\python.exe -m jupyter kernelspec --version
> ~\miniconda3\envs\ais\python.exe -m jupyter kernelspec --version
info 12:32:4.589: Starting notebook server.
info 12:32:4.589: Connecting to server
info 12:32:4.589: Launching server
info 12:32:4.589: Starting Notebook
info 12:32:4.611: Generating custom default config at C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py
info 12:32:4.611: Starting Jupyter Notebook
Starting Jupyter from ~\miniconda3\envs\ais\python.exe with command line --no-browser --notebook-dir="c:\\Users\\xxx\\Box Sync\\Python\\ais" --config=C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 12:32:4.634: Creating daemon pool for c:\Users\xxx\miniconda3\envs\ais\python.exe with env variables count 68
info 12:32:4.637: Process Execution: > ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
> ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
info 12:32:4.639: Process Execution: > ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
> ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
info 12:32:4.642: Process Execution: > ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
> ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
info 12:32:4.927: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) -m jupyter notebook --no-browser --notebook-dir="c:\\Users\\xxx\\Box Sync\\Python\\ais" --config=C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~\miniconda3\envs\ais\python.exe (daemon) -m jupyter notebook --no-browser --notebook-dir="c:\\Users\\xxx\\Box Sync\\Python\\ais" --config=C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 12:32:4.928: Waiting for Jupyter Notebook
c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
info 12:32:5.762: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(

[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
info 12:32:6.190: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais

[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
info 12:32:6.190: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:

[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
info 12:32:6.190: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db

info 12:32:6.191: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
info 12:32:6.192: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db

info 12:32:6.193: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
[I 12:32:06.189 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 12:32:6.193: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

[C 12:32:06.195 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///C:/Users/xxx/AppData/Roaming/jupyter/runtime/nbserver-12832-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
     or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
info 12:32:6.196: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:32:06.195 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///C:/Users/xxx/AppData/Roaming/jupyter/runtime/nbserver-12832-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
     or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db

info 12:32:6.591: Connecting to process server
info 12:32:6.591: Connecting server kernel http://localhost:8888/
info 12:32:6.591: Creating server with url : http://localhost:8888/
info 12:32:6.608: Connection complete server
info 12:32:6.608: Server started.
info 12:32:6.670: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
info 12:32:6.670: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
info 12:32:41.274: Starting interactive window for resoruce 
info 12:32:41.355: Attempting to start a server because of preload conditions ...
info 12:32:41.359: TargetController found ID: .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher (Interactive) for document Interactive-1.interactive
info 12:32:41.474: Starting Notebook id = .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher for Interactive-1.interactive (disableUI=false)
[I 12:32:41.480 NotebookApp] Creating new notebook in 
info 12:32:41.513: installMissingDependencies c:\Users\xxx\miniconda3\envs\ais\python.exe, ui.disabled=false for resource 
info 12:32:41.582: Process Execution: > ~\miniconda3\envs\ais\python.exe -c "import ipykernel"
> ~\miniconda3\envs\ais\python.exe -c "import ipykernel"
info 12:32:41.714: Registering dummy command feature
info 12:32:41.919: Spec argv[0] updated from 'c:\Users\xxx\miniconda3\envs\ais\python.exe' to 'c:\Users\xxx\miniconda3\envs\ais\python.exe'
info 12:32:41.927: Adding env Variable PYTHONNOUSERSITE to c:\Users\xxx\miniconda3\envs\ais\python.exe
[I 12:32:42.016 NotebookApp] Kernel started: 9c2683dc-d244-4036-ac76-e7b292b8cf8f, name: python399jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b
info 12:32:42.29: Waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> unknown
[W 12:32:42.036 NotebookApp] delete /default-13131fc0-dfcd-4655-afc6-7f7a2bdd0ce5.ipynb
info 12:32:43.58: Finished waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> idle
info 12:32:43.58: Started session for kernel .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher
info 12:32:43.59: Finished connecting kernel .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher
info 12:32:43.67: Executing silently Code (idle) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
info 12:32:43.95: Executing silently Code (completed) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
info 12:32:43.95: Waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> idle
info 12:32:43.95: Finished waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> idle
info 12:32:45.672: Disposing kernel .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher for notebook Interactive-1.interactive due to selection of another kernel or closing of the notebook
info 12:32:45.672: Dispose kernel vscode-interactive:Interactive-1.interactive
info 12:32:45.675: Closing interactive window: vscode-interactive:Interactive-1.interactive
[I 12:32:45.679 NotebookApp] Kernel shutdown: 9c2683dc-d244-4036-ac76-e7b292b8cf8f
```

### Coding Language and Runtime Version

python 3.9

### Running Jupyter locally or remotely?

Local

**Comment by Tyriar** [comment]
I cannot reproduce and have no ideas on how this could possibly happen in VS Code. The trace log doesn't show anything useful either. Because of this I believe it's related to some extension. I have created https://github.com/microsoft/vscode/issues/151207 to improve the logging situation, when that gets done it should be easy to determine the source of the terminal.

**Comment by chmielcode** [comment]
Same problem here. Disabling all extensions except Python/Jupyter and commenting out my whole settings.json file did not work. 

```
info 8:1:15.160: Adding hash for 1 = e5fa44f2b31c with 1 lines
debug 8:1:15.163: IKernel Status change to busy
debug 8:1:15.173: IKernel Status change to idle
info 8:1:15.173: Cell 1 executed with state Success
info 8:1:19.854: Disposing kernel .jvsc74a57bd0681cc63fbb6c9402ba6aad6ee1dea865595e02d3f92ab45e92012aa48b3b30a4.c:\...\Scripts\python.exe.c:\...\Scripts\python.exe.-m#ipykernel_launcher for notebook Interactive-1.interactive due to selection of another kernel or closing of the notebook
info 8:1:19.854: Dispose kernel untitled:Untitled-1
info 8:1:19.854: Cancel pending cells
debug 8:1:19.854: Shutdown session - current session
debug 8:1:19.854: shutdownSession a03f67a1-307a-406e-995a-0f4af1acc7fa, .jvsc74a57bd0681cc63fbb6c9402ba6aad6ee1dea865595e02d3f92ab45e92012aa48b3b30a4.c:\...\Scripts\python.exe.c:\...\Scripts\python.exe.-m#ipykernel_launcher - start
debug 8:1:19.854: Session can be shutdown .jvsc74a57bd0681cc63fbb6c9402ba6aad6ee1dea865595e02d3f92ab45e92012aa48b3b30a4.c:\...\Scripts\python.exe.c:\...\Scripts\python.exe.-m#ipykernel_launcher
info 8:1:19.855: Dispose Kernel process
info 8:1:19.855: kill daemon
debug 8:1:19.855: Kernel got disposed, hence there is no longer a kernel associated with Interactive-1.interactive
info 8:1:19.855: Closing interactive window: vscode-interactive:Interactive-1.interactive
debug 8:1:19.856: shutdownSession a03f67a1-307a-406e-995a-0f4af1acc7fa, .jvsc74a57bd0681cc63fbb6c9402ba6aad6ee1dea865595e02d3f92ab45e92012aa48b3b30a4.c:\...\Scripts\python.exe.c:\...\Scripts\python.exe.-m#ipykernel_launcher - shutdown complete
debug 8:1:19.856: Shutdown session - get restart session
debug 8:1:19.856: IKernel Status change to dead
debug 8:1:19.856: Shutdown session -- complete
debug 8:1:19.856: KernelProcess Exit Exit - undefined c:\...\lib\site-packages\traitlets\traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\...\lib\site-packages\traitlets\traitlets.py:2346: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'b8fe5f06-3aed-4667-b7a7-0e3762aae7e5' instead of 'b"b8fe5f06-3aed-4667-b7a7-0e3762aae7e5"'.
  warn(

debug 8:1:19.857: Python Daemon (pid: 10140): Execute rpc method kill_kernel in DS Daemon
debug 8:1:19.857: Python Daemon (pid: 10140): Execute rpc method kill_kernel from c:\...\Scripts\python.exe
debug 8:1:19.857: Python Daemon (pid: 10140): Kill kernel in DS Kernel Interrupt Daemon
debug 8:1:21.881: Found 2 cached controllers
debug 8:1:21.881: Creating 2 controllers
debug 8:1:21.883: Hiding default kernel spec 'Python 3 (ipykernel)', 'python3104jvsc74a57bd0681cc63fbb6c9402ba6aad6ee1dea865595e02d3f92ab45e92012aa48b3b30a4', python
debug 8:1:21.885: Hiding default kernel spec 'Python 3 (ipykernel)', 'python3104jvsc74a57bd0681cc63fbb6c9402ba6aad6ee1dea865595e02d3f92ab45e92012aa48b3b30a4', python
debug 8:1:21.887: Found 2 non-cached controllers
debug 8:1:21.887: Creating 2 controllers
```
![Recording_terminal](https://user-images.githubusercontent.com/45938987/171987031-3415a3c7-8baf-43b8-ad58-b1a96c851c08.gif)

**Comment by MikuAuahDark** [comment]
Same issue in here too. Also happends on Jupyter Notebooks. List of enabled extensions:

* Python (ms-python.python) v2022.6.3
* PyLance (ms-python.vscode-pylance) v2022.6.0
* Jupyter (ms-toolsai.jupyter) v2022.4.1021342353

Disabling Jupyter extension alone prevents the issue from happening.

Version: 1.67.2 (system setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by chmielcode** [comment]
It appears to be fixed in the latest release. Thank you.
