### ISSUE TITLE
npm install fails at `scripts\npm install`  step

### ISSUE THREAD

**Issue by mdahamiwal** [Microsoft/vscode#15095]
@joaomoreno, here are the version details and console logs:

- OS Version:
windows_NT 10.0.14393

- Visual Studio: 
  2015 preview 3

- NPM , NodeJS
  v3.10.8 , v6.9.1

```
97444 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:bpasero/fsevents#vscode (node_modules\chokidar\node_modules\fsevents):
97445 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
97446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
97446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
97446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
97446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
97447 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules\fsevents):
97448 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
97449 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
97449 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
97449 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
97449 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
97450 verbose stack Error: oniguruma@6.1.1 install: `node-gyp rebuild`
97450 verbose stack Exit status 1
97450 verbose stack     at EventEmitter.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
97450 verbose stack     at emitTwo (events.js:106:13)
97450 verbose stack     at EventEmitter.emit (events.js:191:7)
97450 verbose stack     at ChildProcess.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
97450 verbose stack     at emitTwo (events.js:106:13)
97450 verbose stack     at ChildProcess.emit (events.js:191:7)
97450 verbose stack     at maybeClose (internal/child_process.js:877:16)
97450 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
97451 verbose pkgid oniguruma@6.1.1
97452 verbose cwd C:\Users\Documents\sources\vscode
97453 error Windows_NT 10.0.14393
97454 error argv "D:\\nodejs\\node.exe" "C:\\Users\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
97455 error node v6.9.1
97456 error npm  v3.10.8
97457 error code ELIFECYCLE
97458 error oniguruma@6.1.1 install: `node-gyp rebuild`
97458 error Exit status 1
97459 error Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
97459 error Make sure you have the latest version of node.js and npm installed.
97459 error If you do, this is most likely a problem with the oniguruma package,
97459 error not with npm itself.
97459 error Tell the author that this fails on your system:
97459 error     node-gyp rebuild
97459 error You can get information on how to open an issue for this project with:
97459 error     npm bugs oniguruma
97459 error Or if that isn't available, you can get their info via:
97459 error     npm owner ls oniguruma
97459 error There is likely additional logging output above.
97460 verbose exit [ 1, true ]
```

**Comment by joaomoreno** [comment]
Please provide the **entire** npm output.

**Comment by mdahamiwal** [comment]
@joaomoreno , here is the [npm-debug.txt](https://github.com/Microsoft/vscode/files/577722/npm-debug.txt)

thanks for your help. :)

**Comment by joaomoreno** [comment]
Could you run without extra verbosity? Clean your repository with `git clean -xfd .` and run `.\scripts\npm.bat install`.

**Comment by mdahamiwal** [comment]
Okay, npm-debug.log is auto-generated without I mention any verbosity. I tried again with redirecting console output to a file try [npmlog.txt](https://github.com/Microsoft/vscode/files/578007/npmlog.txt) .

**Comment by joaomoreno** [comment]
Cool, thanks for this, it's much easier to figure out what is happening. Here's line 25:

```
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\<user>\Documents\sources\vscode\node_modules\oniguruma\build\oniguruma.vcxproj]
```

Do you have Visual Studio installed? Our docs say you need:

> Visual Studio 2013 for Windows Desktop or Visual Studio 2015, make sure to select the option to install all C++ tools and the Windows SDK

**Comment by mdahamiwal** [comment]
Aha, I think I was missing c++ tools. Thanks for pointing out. works for me now. :)
