### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by caipang** [microsoft/vscode#151083]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.when I was tryssh to self-made linux system,Remote ssh  has been occured wrong message in the blew.

           [17:57:50.368] Failed to parse remote port from server output
          [17:57:50.369] Resolver error: Error: 
	          at Function.Create (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	          at Object.t.handleInstallOutput (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584441)
	          at Object.t.tryInstall (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	          at processTicksAndRejections (node:internal/process/task_queues:96:5)
	          at async c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	          at async Object.t.withShowDetailsEvent (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	          at async Object.t.resolve (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	          at async c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
 
If you recovary me ,I will appreciate

**Comment by roblourens** [comment]
Please share the full log from the Remote-SSH output channel
