### ISSUE TITLE
Typescript: Debug Failure. False expression: position cannot precede the beginning of the file Error

### ISSUE THREAD

**Issue by nfMalde** [microsoft/vscode#151215]
### Info
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000
Typescript Version: 4.5.5

Extensions: 
Angular Language Service - 13.3.4

### Error
```
<semantic> TypeScript Server Error (4.5.5) Debug Failure.
 False expression: position cannot precede the beginning of the file Error: Debug Failure. 
 False expression: position cannot precede the beginning of the file at computeLineOfPosition (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:9978:22) 
 at computeLineAndCharacterOfPosition (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:9956:26) 
 at Object.getLineAndCharacterOfPosition (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:9997:16) 
 at formatDiagnosticToProtocol (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:169774:60) 
 at c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:170709:93 at Object.map (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:458:29) 
 at IOSession.Session.defaultEventHandler (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:170709:45) at ProjectService.eventHandler (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:170615:77) 
 at ProjectService.sendConfigFileDiagEvent (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:167962:22) at ProjectService.assignProjectToOpenedScriptInfo (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:168801:38) 
 at c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:169104:97 at Object.flatMap (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:522:25) 
 at ProjectService.applyChangesInOpenFiles (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:169104:41) at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:170262:46) 
 at c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:172195:88 at IOSession.Session.executeWithRequestId (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:172186:28) 
 at IOSession.Session.executeCommand (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:172195:33) at IOSession.Session.onMessage (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:172221:35) 
 at Interface.<anonymous> (c:\Work\Projects\CMS\Web\CMSSys\ClientApp\node_modules\typescript\lib\tsserver.js:174826:31) 
 at Interface.emit (node:events:390:28) at Interface._onLine (node:readline:487:10) 
 at Interface._normalWrite (node:readline:661:12) 
 at Socket.ondata (node:readline:269:10) 
 at Socket.emit (node:events:390:28) 
 at addChunk (node:internal/streams/readable:315:12) 
 at readableAddChunk (node:internal/streams/readable:289:9) 
 at Socket.Readable.push (node:internal/streams/readable:228:10) 
 at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

Followed by message:
![image](https://user-images.githubusercontent.com/5366984/171871765-92707d98-5a09-486a-b46f-8e2a109afc9e.png)

### Description
I was working my ng app (Angular 13) - after a short break (closed VS Code) the error above happened out of nowhere when I started  VSCode.

I then tried the following (without success):
- Switching TS Version from 4.6.x (VSCode) to Workspace (4.5.5) 
- Uninstalling global ts version and reinstalling it (4.5.5)
- Disabling ext.  TypeScript and JavaScript Language Features
- Restarting VSCode
- Re-Enabling TypeScript and JavaScript Language Features
- Restarting VSCode again
- Restart whole computer

All without success.

Then I followed instruction by https://code.visualstudio.com/docs/setup/uninstall for an clean reinstall and deleted all  ".vscode" folders in my project.

Still no success.

I saw the bug was reported for older versions of VSCode - but the suggested solution "Installing TS globally" or switching to certain versions didnt helped.

Any suggestions what to do?

Best,

Malte

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Make sure you are using at least TypeScript 4.7+

**Comment by nfMalde** [comment]
Hi! Thanks for the fast response.

### Code Insider Build (Latest) with no Extensions enabled
- Typescript Version 4.5.x - Works
- Typescript Version 4.6.x - Works
- 4.7 is not supported by ng13 so I couldn test it.

### Code Insider Build (Latest) with Angular Language Service enabled
- Version 14.x. breaks intellisense but syntax highlighting still works
- Version 13.x works as expected.
**Note:** Maybe cause of ng language service v14 is not compatible with TS4.5/ng13


Tried same again with stable version of vscode - same error.
Seems to be fixed in code-inisder version.

**Comment by mjbvz** [comment]
If this only happens with the Angular Language Service enabled, it is cause by the Angular Language Service. Please file the issue against them

**Comment by nfMalde** [comment]
Its not caused by angular language service like I wrote above. 
It works WITH and WITHOUT angular language service in Code Insider Build and **NOT** in current stable build.

In stable build it doesnt matter if I enable ng lang or disable it .

**Comment by mjbvz** [comment]
Are you sure it's not just different configuration (settings, extension) between insiders and stable?

But if it does work in insiders but not stable, this is not relevant anyways as the issue as already been fixed

**Comment by nfMalde** [comment]
Can confirm its fixed now. Fact it was broken after installing angular language service. Something went wrong even after disabling it. Maybe something broke in my user profile folder of vscode... Fixed.  Thanks for the help :-)
