### ISSUE TITLE
cannot read properties of undefined (reading 'marker')

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151225]
1. with shell integration on macOS with pwsh, run some commands and clear the terminal
2. 
```
, source: vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/platform/log/common/log.js (221)
[31944:0603/084904.575887:INFO:CONSOLE(231)] "%c  ERR color: #f33 Cannot read properties of undefined (reading 'marker'): TypeError: Cannot read properties of undefined (reading 'marker')
    at e._getKey (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/node_modules/xterm/lib/xterm.js:1:369197)
    at e.delete (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/node_modules/xterm/lib/xterm.js:1:286006)
    at vscode-file://vscode-app/Users/meganrogge/Repos/vscode/node_modules/xterm/lib/xterm.js:1:369972
    at e.fire (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/node_modules/xterm/lib/xterm.js:1:234872)
    at t.dispose (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/node_modules/xterm/lib/xterm.js:1:372512)
    at DecorationAddon.clearDecorations (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.js:104:34)
    at DecorationAddon._dispose (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.js:98:18)
    at vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.js:46:69
    at vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/base/common/lifecycle.js:130:17
    at Object.dispose (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/base/common/functional.js:18:25)
    at dispose (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/base/common/lifecycle.js:166:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/out/vs/base/common/lifecycle.js:153:18)
    at DecorationAddon.dispose (vscode-
```

**Comment by tjx666** [comment]
Still reproduce sometime when close debug task:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/177049989-c47ab2dc-dbb6-4ee5-81f4-34fe4b66197e.png">


Version:

```
 Version: 1.69.0-insider (Universal)
Commit: 0b3574dcef8f35fec4ee4f83dc958c1f16ef6fce
Date: 2022-07-01T05:16:52.086Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

**Comment by Tyriar** [comment]
Line in the screenshot above:

https://github.com/xtermjs/xterm.js/blob/e77a0ec886355d560e7a93fa2b354449694ed668/src/common/services/DecorationService.ts#L22

Triggered from:

https://github.com/xtermjs/xterm.js/blob/e77a0ec886355d560e7a93fa2b354449694ed668/src/common/services/DecorationService.ts#L44

**Comment by tjx666** [comment]
I can stiil occur this issue:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/178146695-bc7c368d-7db4-4582-a9ab-87ad7da6e18e.png">

```
workbench.desktop.main.js:808 TypeError: Cannot read properties of undefined (reading 'marker')
    at e._getKey (DecorationService.ts:22:90)
    at e.delete (SortedList.ts:41:14)
    at DecorationService.ts:44:33
    at e.fire (EventEmitter.ts:55:16)
    at t.dispose (DecorationService.ts:136:21)
    at a.clearDecorations (workbench.desktop.main.js:1713:9965)
    at a._dispose (workbench.desktop.main.js:1713:9707)
    at workbench.desktop.main.js:1713:8035
    at workbench.desktop.main.js:19:30348
    at Object.dispose (workbench.desktop.main.js:11:8937)
    at i (workbench.desktop.main.js:19:30061)
    at l.clear (workbench.desktop.main.js:19:30580)
    at l.dispose (workbench.desktop.main.js:19:30518)
    at a.dispose (workbench.desktop.main.js:19:31119)
    at e._wrappedAddonDispose (AddonManager.ts:53:25)
    at a.t.dispose (AddonManager.ts:33:35)
    at e.dispose (AddonManager.ts:22:32)
    at e.dispose (Terminal.ts:207:24)
    at i (workbench.desktop.main.js:19:30061)
    at Ki.clear (workbench.desktop.main.js:19:30580)
    at Ki.dispose (workbench.desktop.main.js:19:30518)
    at Fi.dispose (workbench.desktop.main.js:3064:793)
    at workbench.desktop.main.js:3170:31736
    at new Promise (<anonymous>)
    at z.safeDisposeTerminal (workbench.desktop.main.js:3170:31700)
    at a.run (workbench.desktop.main.js:3061:68538)
    at handler (workbench.desktop.main.js:697:13150)
    at m.invokeFunction (workbench.desktop.main.js:599:325)
    at m._tryExecuteCommand (workbench.desktop.main.js:1685:3664)
    at m.executeCommand (workbench.desktop.main.js:1685:3021)
    at Io.run (workbench.desktop.main.js:697:12232)
    at k.runAction (workbench.desktop.main.js:82:17056)
    at k.run (workbench.desktop.main.js:82:16959)
    at f.onClick (workbench.desktop.main.js:803:24250)
    at HTMLLIElement.<anonymous> (workbench.desktop.main.js:177:15792)
onDidChangeNotification @ workbench.desktop.main.js:808

```

**Comment by Tyriar** [comment]
@tjx666 can you paste in version info from Help > About?

**Comment by tjx666** [comment]
```
Version: 1.70.0-insider (Universal)
Commit: 3104db414c8fedcf6e4493f14da7df0b7413853a
Date: 2022-07-08T05:16:29.757Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```
@Tyriar

**Comment by tjx666** [comment]
I think this issue should be reopen. This issue occur very often. @Tyriar
