### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by masonmark** [microsoft/vscode#151382]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.4

**Steps to reproduce crash**
1. Use the GitHub side panel to review a pull request.
2. Click on a few TypeScript files in succession, to see the diffs in the PR.
3. It happens every time, after a minute or two.

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`/Users/mason/Library/Application Support/Code/logs/20220607T100946/exthost1/vscode.typescript-language-features/tsserver-log-g9S4eu/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_2 (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:169024:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:169032:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:170698:26)
    at /Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:170972:97
    at Object.flatMap (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:170972:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:172131:46)
    at /Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:174067:88
    at IpcIOSession.Session.executeWithRequestId (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:174058:28)
    at IpcIOSession.Session.executeCommand (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:174067:33)
    at IpcIOSession.Session.onMessage (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:174093:35)
    at process.<anonymous> (/Users/mason/Documents/SORACOM/user-console-monorepo-ALT/node_modules/typescript/lib/tsserver.js:176728:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 27, 19|
|Memory (System)|64.00GB (32.27GB free)|
|Process Argv|--crash-reporter-id eeecaea7-40df-4a0a-9442-1aac126ee809|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
ng-template|Ang|14.0.0
dart-code|Dar|3.42.1
flutter|Dar|3.42.0
vscode-eslint|dba|2.2.2
binary-plist|dni|0.8.0
gitlens|eam|12.0.7
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
vscode-jest-runner|fir|0.4.48
code-runner|for|0.11.7
vscode-pull-request-github|Git|0.42.0
applescript|idl|0.21.1
file-ext-switcher|Joh|3.2.0
Angular2|joh|13.0.0
theme-karyfoundation-themes|kar|25.2.3
rainbow-csv|mec|2.4.0
vscode-postcss-sorting|mrm|3.0.1
python|ms-|2022.6.3
vscode-pylance|ms-|2022.6.0
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
debugger-for-edge|msj|1.0.15
vscode-paste-image|mus|1.0.4
angular-console|nrw|17.18.1
java|red|1.7.0
easysass|spo|0.0.6
code-spell-checker|str|2.2.0
intellicode-api-usage-examples|Vis|0.1.1
vscodeintellicode|Vis|1.2.21
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.23.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Make sure you using TypeScript 4.7+ too when testing
