### ISSUE TITLE
ssh to a remote Linux server

### ISSUE THREAD

**Issue by XiaofengZhu** [microsoft/vscode#151381]
Issue Type: <b>Bug</b>

remote ssh error: Failed to parse remote port from server output

> ]0;C:\windows\System32\cmd.exe
[17:54:22.704] Got some output, clearing connection timeout
[17:54:24.694] "install" terminal command done
[17:54:24.695] Install terminal quit with output: ]0;C:\windows\System32\cmd.exe
[17:54:24.695] Received install output: ]0;C:\windows\System32\cmd.exe
[17:54:24.696] Failed to parse remote port from server output
[17:54:24.697] Resolver error: Error: 
	at Function.Create (c:\Users\Xena.zhu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	at Object.t.handleInstallOutput (c:\Users\Xena.zhu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584441)
	at Object.t.tryInstall (c:\Users\Xena.zhu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\Xena.zhu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	at async Object.t.withShowDetailsEvent (c:\Users\Xena.zhu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async Object.t.resolve (c:\Users\Xena.zhu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	at async c:\Users\Xena.zhu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
[17:54:24.706] ------

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Connection to 'SSH' could not be established  No remote extension installed to resolve ssh-remote.
Connection to 'SSH' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  No remote extension installed to resolve ssh-remote.

Connection to 'SSH' could not be established 
</details>Extensions: none

**Comment by AlexHex7** [comment]
I have met this problem so many times. After wating for several hours, this problem disappears. It may be the network problem?

...  How to solve it?
