### ISSUE TITLE
VSCode Smoke Tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#151710]
```
  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Tabs
           should update icon of the tab in the tabs list:
     Error: Timeout: get element '.tabs-list .monaco-list-row[data-index="1"] .terminal-tabs-entry .codicon-symbol-method' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:254:11)
      at Code.waitForElement (D:\a\_work\1\s\test\automation\src\code.ts:207:10)
      at Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\src\terminal.ts:197:5)
      at Terminal.assertTerminalGroups (D:\a\_work\1\s\test\automation\src\terminal.ts:151:6)
      at Context.<anonymous> (src\areas\terminal\terminal-tabs.test.ts:60:4)
```

**Comment by Tyriar** [comment]
Maybe related to my recent change https://github.com/microsoft/vscode/issues/151639
