### ISSUE TITLE
Terminal integration tests failing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#151786]
Maybe caused by https://github.com/microsoft/vscode/pull/151753?

https://dev.azure.com/vscode/VSCode/_build/results?buildId=65627&view=logs&j=a8b516b9-5c25-5ad9-505a-b03d38bc1dad&t=73b6fc11-6cca-5aa2-b201-677def4d2b1c&l=677

```

           should have collection variables apply to terminals immediately after setting:
     Error: Timeout: ~a2~ should be printed after 20 seconds.
Did not pass accept function
      at poll (extensions/vscode-api-tests/src/utils.ts:167:10)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts:707:5)

  5) vscode API - terminal
       Terminal
         environmentVariableCollection
           should have collection variables apply to environment variables that don't exist:
     Error: Timeout: ~a2~ should be printed after 20 seconds.
Did not pass accept function
      at poll (extensions/vscode-api-tests/src/utils.ts:167:10)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts:752:5)

  6) vscode API - terminal
       Terminal
         environmentVariableCollection
           should respect clearing entries:
     Error: Timeout: ~a1~ should be printed after 20 seconds.
Did not pass accept function
      at poll (extensions/vscode-api-tests/src/utils.ts:167:10)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts:794:5)

  7) vscode API - terminal
       Terminal
         environmentVariableCollection
           should respect deleting entries:
     Error: Timeout: ~a1~ should be printed after 20 seconds.
Did not pass accept function
      at poll (extensions/vscode-api-tests/src/utils.ts:167:10)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts:835:5)

  8) vscode API - tasks
       Tasks
         ShellExecution
           Execution from onDidEndTaskProcess and onDidStartTaskProcess are equal to original:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/workspace.tasks.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

  9) vscode API - tasks
       Tasks
         ShellExecution
           dependsOn task should start with a different processId (#118256):
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/workspace.tasks.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

**Comment by Tyriar** [comment]
First build to fail seems to be https://github.com/microsoft/vscode/pull/151531 😕

**Comment by Tyriar** [comment]
Fixed with revert https://github.com/microsoft/vscode/pull/151792
