### ISSUE TITLE
having issues with setting interpeter python path

### ISSUE THREAD

**Issue by fislysandi** [microsoft/vscode#151898]
- VS Code Version:latest version

- OS Version: Windows 10 19042 Build

Steps to Reproduce:

1.fresh install of vscode
2.install python
3.get this while setting the path to the interpreter
[Info  - 02:04:05] (3288) Pylance language server 2022.6.10 (pyright bbc42826) starting
[Info  - 02:04:05] (3288) Server root directory: c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.vscode-pylance-2022.6.10\dist
Notebook support: Legacy
[Info  - 02:04:42] (12544) Pylance language server 2022.6.10 (pyright bbc42826) starting
[Info  - 02:04:42] (12544) Server root directory: c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.vscode-pylance-2022.6.10\dist
Notebook support: Legacy
[Info  - 02:04:42] (1500) Pylance language server 2022.6.10 (pyright bbc42826) starting
[Info  - 02:04:42] (1500) Server root directory: c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.vscode-pylance-2022.6.10\dist
Notebook support: Legacy
[Error - 02:04:42] Server initialization failed.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (c:\Users\angryteapodthebonedo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:60904)
	at Object.registerCommand (c:\Users\angryteapodthebonedo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:30995)
	at t.ExecuteCommandFeature.register (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2221484)
	at t.ExecuteCommandFeature.initialize (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2221063)
	at S.initializeFeatures (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2172994)
	at S.doInitialize (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2160644)
	at async S.start (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2157659)
	at async h.start (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:35320)
[Error - 02:04:42] Pylance client: couldn't create connection to server.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (c:\Users\angryteapodthebonedo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:60904)
	at Object.registerCommand (c:\Users\angryteapodthebonedo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:30995)
	at t.ExecuteCommandFeature.register (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2221484)
	at t.ExecuteCommandFeature.initialize (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2221063)
	at S.initializeFeatures (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2172994)
	at S.doInitialize (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2160644)
	at async S.start (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:2157659)
	at async h.start (c:\Users\angryteapodthebonedo\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:35320)

also getting the (pyright,createtypestub)

**Comment by fislysandi** [comment]
also getting issues with unable to write into user settings.
