### ISSUE TITLE
Unable to open Release Notes - cannot read property replace of null

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#15183]
- VSCode Version: Code - Insiders 1.8.0-insider (44901c208cf8a3bdaa22762937d223dd9c30310a, 2016-11-08T07:55:03.135Z)
- OS Version: Darwin x64 16.1.0

---

Steps to Reproduce:

1. Got "New update available" top bar
2. Clicked Read Release Notes
3. 
![image](https://cloud.githubusercontent.com/assets/1723815/20106414/0c70bcb8-a5a3-11e6-9c5d-68326b0d3649.png)

```
workbench.main.js:92 Unable to open 'Release Notes: VSCode': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..: Error: Unable to open 'Release Notes: VSCode': Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked..
    at t.doHandleSetInputError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:118:15892)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:118:15498
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:32:17435)
    at t.doSetInput (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:118:15246)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:118:13133
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:32:18059)
    at t.doOpenEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:118:13105)
    at t.openEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:118:12384)
    at e.doOpenEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:105:13762)
    at e.openEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:105:13192)
```

**Comment by joaomoreno** [comment]
This was fixed by my latest merge from the `update` branch.

**Comment by ad05bzag** [comment]
I got the same error today: 

VS info:
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

OS: 
4.4.0-51-generic #72~14.04.1-Ubuntu SMP Thu Nov 24 19:22:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

steps to reproduce:
1. Got "New update available" top bar
2. Clicked Read Release Notes

**Comment by gregzuro** [comment]
Got this today:

Version 1.10.0-insider
ad605ea39a832e4be2cbf77670781654056ef027
2017-02-06T07:02:27.982Z

on OSX 10.12.3

Just clicked "Read Release Notes"


Have been getting this error with each new release.

**Comment by joaomoreno** [comment]
@gregzuro Update to the latest. 👍

**Comment by BartoszBaczek** [comment]
Got this today. My spec:

![image](https://cloud.githubusercontent.com/assets/11254976/23251331/2fe7ae3c-f9ad-11e6-8b95-1af2a7310698.png)
