### ISSUE TITLE
Setting BP - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#15194]
I keep seeing this in Insiders when trying to set a BP.

```
shell.ts:451 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at o (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:120:27174)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:120:28788
    at Array.map (native)
    at t.sendToOneOrAllProcesses (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:120:28765)
    at t.sendBreakpoints (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:120:27693)
    at t.addBreakpoints (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:120:14308)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:110:11605
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:30609
    at o (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:23360)
    at t.e._emitToSpecificTypeListeners (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:25601)e.onUnexpectedError @ shell.ts:451(anonymous function) @ shell.ts:364e.onUnexpectedError @ errors.ts:68r @ errors.ts:83o @ eventEmitter.ts:305e._emitToSpecificTypeListeners @ eventEmitter.ts:182e._emitEvents @ eventEmitter.ts:201e.emit @ eventEmitter.ts:216(anonymous function) @ commonCodeEditor.ts:803o @ eventEmitter.ts:303e._emitToBulkListeners @ eventEmitter.ts:190e._emitEvents @ eventEmitter.ts:196e.emit @ eventEmitter.ts:216e.emitMouseDown @ viewController.ts:300t._onMouseDown @ mouseHandler.ts:321(anonymous function) @ mouseHandler.ts:178(anonymous function) @ editorDom.ts:66_wrapHandler @ dom.ts:196
```

**Comment by isidorn** [comment]
@roblourens I can not reproduce this - how do you set the breakpoint, in what type of file?
This minimized stack trace is not a lot of use to me - you could open developer tools > pause on exceptions > format minimized code and send the screenshot on where you break.

Also you could try reproudcing with out of source

**Comment by roblourens** [comment]
In Javascript, usually after a couple debugging sessions in the editor. Goes away for awhile if I restart it.

![image](https://cloud.githubusercontent.com/assets/323878/20146494/f49b9dd6-a658-11e6-9f92-b6f3aa81d77a.png)

`t.cachedCallStack` is undefined.
![image](https://cloud.githubusercontent.com/assets/323878/20146506/fe73d8be-a658-11e6-8c94-372470c42517.png)
