### ISSUE TITLE
[error] ENOENT: no such file or directory (installing Spring boot tools)

### ISSUE THREAD

**Issue by Osolemio44** [microsoft/vscode#152019]
- VS Code Version: 1.68.0    4af164ea3a06f701fe3e89a2bcbb421d2026b68f       x64
- OS Version: Windows 10 Enterprise 21H2 19044.1741

Trying to install Spring Boot Tools V1.34.0

Steps to Reproduce:
1. Install Spring boot tools

On my computer I do not have administrator permissions. user only. I have VSCode installed in user mode. I have exported the settings profile from another vscode and inported in this one. Everything worked fine. (I mention it in case it is a relevant fact). But today several updates have arrived and Spring Boot Tools won't let me update or install.
I have deleted the `.vscode` folder but still have the same problem. 
All other extension installed well.

error:
```
[2022-06-14 08:36:34.483] [renderer1] [error] ENOENT: no such file or directory, open 'c:\Users\xxxxxxxxxx\.vscode\extensions\.8174eecb-64ac-4e49-8050-f9ea85bb33fc\language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html': Extract: ENOENT: no such file or directory, open 'c:\Users\xxxxxxxxxx\.vscode\extensions\.8174eecb-64ac-4e49-8050-f9ea85bb33fc\language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html'
    at F.extractAtLocation (vscode-file://vscode-app/c:/Users/xxxxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213215)
    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/xxxxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210606)
    at async $.extract (vscode-file://vscode-app/c:/Users/xxxxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217251)
    at async $.doRun (vscode-file://vscode-app/c:/Users/xxxxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218192)
```

**Comment by Osolemio44** [comment]
It was and issue from Spring. Resolved: https://github.com/spring-projects/sts4/issues/784
