### ISSUE TITLE
Terminal smoke tests fail wtih EADDRINUSE

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#152090]
This failed on an unrelated change from me, with the following error:

```
1) VSCode Smoke Tests (Web)
       Terminal
         "before all" hook in "Terminal":
     Error: [16:10:28] Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1520:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8000
}

      at Socket.<anonymous> (/__w/1/s/test/automation/src/playwrightBrowser.ts:164:12)
      at Socket.emit (node:events:527:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

```

**Comment by Tyriar** [comment]
Looks like a flake in playwright, perhaps the previous test isn't torn down right or something 🤔 

```
at Socket.<anonymous> (/__w/1/s/test/automation/src/playwrightBrowser.ts:164:12)
```

**Comment by Tyriar** [comment]
@bpasero any ideas what could be causing this around the playwright setup?

**Comment by bpasero** [comment]
Whats the build link for the full test runner log?
