### ISSUE TITLE
Intellisense not working - tsserver saying "LanguageService is disabled"

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#15206]
- VSCode Version: 1.7.1#02611b, and 1.8.0-insider#a3e85d
- OS Version: Windows 10

.. I am sure this has something to do with my code and/or config in this particular (large) app, because it works fine in other applications, but I can't figure out what's wrong here. When VSCode first loads, I see "2.0.8" in the status bar indicating tsserver is runnning, then it disappears.

After starting VS code & typing something, this is the log

[Info  - 3:03:30 PM] Using tsserver from location: d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js
[Error - 3:03:36 PM] 'quickinfo' request failed with error.
Error processing request. LanguageService is disabled
Error: LanguageService is disabled
    at Object.throwLanguageServiceIsDisabledError (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:5423:19)
    at IOSession.Session.getQuickInfoWorker (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:54867:62)
    at Session.handlers.ts.createMap._a.(anonymous function) (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:54174:61)
    at IOSession.Session.executeCommand (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:55283:28)
    at IOSession.Session.onMessage (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:55303:35)
    at Interface.<anonymous> (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:56384:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
[Error - 3:03:44 PM] 'completions' request failed with error.
Error processing request. LanguageService is disabled
Error: LanguageService is disabled
    at Object.throwLanguageServiceIsDisabledError (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:5423:19)
    at IOSession.Session.getCompletions (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:54971:64)
    at Session.handlers.ts.createMap._a.(anonymous function) (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:54216:61)
    at IOSession.Session.executeCommand (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:55283:28)
    at IOSession.Session.onMessage (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:55303:35)
    at Interface.<anonymous> (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:56384:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
[Error - 3:03:45 PM] 'completions' request failed with error.
Error processing request. LanguageService is disabled
Error: LanguageService is disabled
    at Object.throwLanguageServiceIsDisabledError (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:5423:19)
    at IOSession.Session.getCompletions (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:54971:64)
    at Session.handlers.ts.createMap._a.(anonymous function) (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:54216:61)
    at IOSession.Session.executeCommand (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:55283:28)
    at IOSession.Session.onMessage (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:55303:35)
    at Interface.<anonymous> (d:\Users\{User}\code\AppRoot\node_modules\typescript\lib\tsserver.js:56384:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)

**Comment by jamietre** [comment]
Think I found the cause - project is too big, and tsserver is just shutting down. I found a [related issue](https://github.com/Microsoft/TypeScript/issues/11888).

This was resolved by explicitly including `src` and excluding `node_modules` in jsconfig.js.  I am closing since there is arleady in issue about VS Code providing better.

This seems like a problem with vscode since it's hard to understand what happened. The issue linked above definitely covers this, not sure if there's a VS Code aspect to this as well.
