### ISSUE TITLE
Many `L.authority.toLowerCase is not a function: TypeError: L.authority.toLowerCase is not a function`

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#152099]
Version: 1.69.0-insider (Universal)
Commit: d8823e67a907b3fa176068ad802682ccd74f8083
Date: 2022-06-14T10:34:01.122Z
Electron: 18.3.2
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

When connecting to a remote window (I used SSH) I saw many errors of this form:
```
[2022-06-14 11:07:31.279] [renderer1] [error] L.authority.toLowerCase is not a function: TypeError: L.authority.toLowerCase is not a function
    at F.findFormatting (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2108:11710)
    at F.getHostLabel (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2108:14380)
    at ri.updateRemoteStatusIndicator (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2120:78047)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2120:75823
    at v.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:145)
    at s.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:2266)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1844)
    at F.registerFormatter (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2108:14974)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2104:55127
```

I also saw this error while working on a custom remote extension.

**Comment by tanhakabir** [comment]
Can't repro anymore
