### ISSUE TITLE
Failed to connect to the remote extension host server

### ISSUE THREAD

**Issue by acebot712** [microsoft/vscode#152154]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

I can't connect to remote host even though I can connect through my terminal using `ssh 10.9.8.6`
My custom settings are these:-
```
{
    "terminal.integrated.fontFamily": "MesloLGS NF",
    "terminal.integrated.persistentSessionReviveProcess": "never",
    "terminal.integrated.enablePersistentSessions": false,
    "jupyter.kernels.filter": [],
    "python.defaultInterpreterPath": "/opt/anaconda3/envs/data_science/bin/python",
    "terminal.integrated.inheritEnv": false,
    "python.languageServer": "Jedi",
    "editor.minimap.enabled": false,
    "security.workspace.trust.enabled": false
}
```
Steps to Reproduce:

1. Install Version: 1.68.0 (Universal) VS Code
2. Install remote ssh extension
3. Try connecting to remote host

The following is shown when I opened developer tools to debug:-
[Screenshot](https://drive.google.com/file/d/1RYM_nv2trasOmGkMbotxr4xkvDhPzWzn/view?usp=sharing)

The following is my debug log.
```
[13:04:00.548] Log Level: 2
[13:04:00.550] remote-ssh@0.82.1
[13:04:00.550] darwin x64
[13:04:00.556] SSH Resolver called for "ssh-remote+10.9.8.8", attempt 1
[13:04:00.556] "remote.SSH.useLocalServer": true
[13:04:00.557] "remote.SSH.path": undefined
[13:04:00.557] "remote.SSH.configFile": undefined
[13:04:00.557] "remote.SSH.useFlock": true
[13:04:00.558] "remote.SSH.lockfilesInTmp": false
[13:04:00.558] "remote.SSH.localServerDownload": auto
[13:04:00.562] "remote.SSH.remoteServerListenOnSocket": false
[13:04:00.562] "remote.SSH.showLoginTerminal": false
[13:04:00.562] "remote.SSH.defaultExtensions": []
[13:04:00.562] "remote.SSH.loglevel": 2
[13:04:00.563] "remote.SSH.enableDynamicForwarding": true
[13:04:00.563] "remote.SSH.enableRemoteCommand": false
[13:04:00.563] "remote.SSH.serverPickPortsFromRange": {}
[13:04:00.564] "remote.SSH.serverInstallPath": {}
[13:04:00.579] SSH Resolver called for host: 10.9.8.8
[13:04:00.580] Setting up SSH remote "10.9.8.8"
[13:04:00.584] Acquiring local install lock: /var/folders/0k/b2v7y55s06xckjv0dhkfzjpc29cbcz/T/vscode-remote-ssh-5c1e8ac5-install.lock
[13:04:00.588] Looking for existing server data file at /Users/abhijoy.sarkar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5c1e8ac5-4af164ea3a06f701fe3e89a2bcbb421d2026b68f-0.82.1/data.json
[13:04:00.589] Using commit id "4af164ea3a06f701fe3e89a2bcbb421d2026b68f" and quality "stable" for server
[13:04:00.593] Install and start server if needed
[13:04:00.597] PATH: /Users/abhijoy.sarkar/.krew/bin:/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
[13:04:00.597] Checking ssh with "ssh -V"
[13:04:00.626] > OpenSSH_8.6p1, LibreSSL 3.3.6

[13:04:00.630] askpass server listening on /var/folders/0k/b2v7y55s06xckjv0dhkfzjpc29cbcz/T/vscode-ssh-askpass-290de3dea67eec56d49dabb3447f90160e780daf.sock
[13:04:00.631] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/0k/b2v7y55s06xckjv0dhkfzjpc29cbcz/T/vscode-ssh-askpass-2903c392bbddfd31810de522ea0d8720f792ef36.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61764","-o","ConnectTimeout=15","10.9.8.8"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/abhijoy.sarkar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5c1e8ac5-4af164ea3a06f701fe3e89a2bcbb421d2026b68f-0.82.1/data.json"}
[13:04:00.631] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.EEwvCwZzIF/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/abhijoy.sarkar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/abhijoy.sarkar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/0k/b2v7y55s06xckjv0dhkfzjpc29cbcz/T/vscode-ssh-askpass-290de3dea67eec56d49dabb3447f90160e780daf.sock"}
[13:04:00.634] Spawned 57930
[13:04:00.931] > local-server-1> Spawned ssh, pid=57941
[13:04:00.939] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[13:04:01.676] stderr> Warning: Permanently added '10.19.128.60' (RSA) to the list of known hosts.
[13:04:02.091] stderr> *__________________________________________*
[13:04:02.091] stderr> * You`re passing through Jumphost Tunnels. *
[13:04:02.091] stderr> *------------------------------------------*
[13:04:04.134] stderr> debug1: Server host key: ssh-ed25519 SHA256:I5mJAJHkzbGYtk8e+W14JnJBTAG40BWRQnFGYTkai54
[13:04:04.134] stderr> Warning: Permanently added '10.9.8.8' (ED25519) to the list of known hosts.
[13:04:05.285] stderr> Authenticated to 10.9.8.8 (via proxy).
[13:04:05.788] > Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-1036-azure x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   Get cloud support with Ubuntu Advantage Cloud Guest:
>     http://www.ubuntu.com/business/services/cloud
> 
> 204 packages can be updated.
> 148 updates are security updates.
> 
[13:04:05.889] > ready: d6be4b057e76
[13:04:06.075] > Linux 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018
[13:04:06.075] Platform: linux
[13:04:06.247] > /bin/bash
[13:04:06.248] Shell: bash
[13:04:06.248] Creating bash subshell inside "bash"
[13:04:06.426] > bash version:  4.3.48(1)-release
[13:04:06.536] > bash version:  4.3.48(1)-release
> bash version:  4.3.48(1)-release
[13:04:07.107] > bash version:  4.3.48(1)-release
[13:04:07.390] > d6be4b057e76: running
[13:04:07.498] > Acquiring lock on /home/abhijoy.sarkar/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/vscode-remote-lock.abhijoy.sarkar.4af164ea3a06f701fe3e89a2bcbb421d2026b68f
> Installing to /home/abhijoy.sarkar/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f...
> d6be4b057e76%%1%%
> Downloading with wget
[13:04:14.731] > wget download failed
> failed: Connection timed out.
[13:04:14.731] > printenv:
>     XDG_SESSION_ID=131940
>     HOSTNAME=voice-dev8
>     SHELL=/bin/bash
>     SSH_CLIENT=10.52.242.47 50894 22
>     VAULT_ADDR=http://active.vault.service.consul.liv.ai:8200
>     USER=abhijoy.sarkar
>     RG=FK-Voice-User-RG-Dev
>     VSCODE_AGENT_FOLDER=/home/abhijoy.sarkar/.vscode-server
>     PATH=/home/abhijoy.sarkar/bin:/home/abhijoy.sarkar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     MAIL=/var/mail/abhijoy.sarkar
>     PWD=/home/abhijoy.sarkar/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f
>     LANG=en_US.UTF-8
>     PUBLIC_IP=
>     HOME=/home/abhijoy.sarkar
>     SHLVL=2
>     VM=1
>     LOGNAME=abhijoy.sarkar
>     SSH_CONNECTION=10.52.242.47 50894 10.9.8.8 22
>     XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
>     XDG_RUNTIME_DIR=/run/user/155610
>     PRIVATE_IP=10.9.8.8
>     _=/usr/bin/printenv
>     OLDPWD=/home/abhijoy.sarkar
[13:04:14.840] > Trigger local server download
> d6be4b057e76:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/abhijoy.sarkar/.vscode-server/bin/==
> destFolder2==4af164ea3a06f701fe3e89a2bcbb421d2026b68f==
> d6be4b057e76:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/abhijoy.sarkar/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[13:04:14.841] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/abhijoy.sarkar/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f"}
[13:04:14.841] Downloading VS Code server locally...
[13:04:15.222] Terminating local server
[13:04:15.225] Resolver error: Error: Server returned 404
    at v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:622:38476)
    at k.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:623:1592)
[13:04:15.230] ------




[13:04:15.231] Local server exit: 15

```

**Comment by JoseManuelLascasas** [comment]
Hello

I had the same issue, i uninstalled vscode and install the last version of his page again

Now it is working, hope it helps

**Comment by roblourens** [comment]
We had a server-side issue last Friday that caused this error message. Did you file this issue right after seeing the problem (ie you saw it after this past weekend)?

```
[13:04:14.841] Downloading VS Code server locally...

[13:04:15.225] Resolver error: Error: Server returned 404
```
