### ISSUE TITLE
Language Features smoke failures

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152227]
Related: https://github.com/microsoft/vscode/issues/147749

No playwright trace because it's Linux?

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=174438&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a671546b-2469-5fb1-b2c9-08e628dcad6d&l=136

```
  1) VSCode Smoke Tests (Electron)
       Language Features
         verifies quick outline (js):
     Error: Timeout: get text content '.quick-input-widget .quick-input-list .monaco-list-row.focused .monaco-highlighted-label' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:255:11)
      at Code.waitForTextContent (/__w/1/s/test/automation/src/code.ts:187:10)
      at QuickInput.waitForQuickInputElementFocused (/__w/1/s/test/automation/src/quickinput.ts:28:3)
      at QuickAccess.runCommand (/__w/1/s/test/automation/src/quickaccess.ts:179:3)
      at QuickAccess.openFileQuickAccessAndWait (/__w/1/s/test/automation/src/quickaccess.ts:25:3)
      at QuickAccess.openFile (/__w/1/s/test/automation/src/quickaccess.ts:124:3)
      at Context.<anonymous> (src/areas/languages/languages.test.ts:18:4)

  2) VSCode Smoke Tests (Electron)
       Language Features
         verifies quick outline (css):
     keyboard.down: Target page, context or browser has been closed
      at Proxy.dispatchKeybinding (/__w/1/s/test/automation/src/playwrightDriver.ts:148:30)
      at Proxy.<anonymous> (/__w/1/s/test/automation/src/code.ts:120:24)
      at Code.dispatchKeybinding (/__w/1/s/test/automation/src/code.ts:135:21)
      at QuickAccess.openQuickAccessWithRetry (/__w/1/s/test/automation/src/quickaccess.ts:149:22)
      at QuickAccess.runCommand (/__w/1/s/test/automation/src/quickaccess.ts:176:14)
      at QuickAccess.openFileQuickAccessAndWait (/__w/1/s/test/automation/src/quickaccess.ts:25:14)
```

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/173891191-2b835dab-f941-4cac-bd45-7a43217dd3a8.png)
