### ISSUE TITLE
Build succeeded after failed npm install for an extension

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#15230]
In today's insiders build on Windows:

![image](https://cloud.githubusercontent.com/assets/5047891/20131771/d5c955cc-a65f-11e6-8a18-a3b904cc3127.png)

I get the following error on startup:
```
extensionHost.ts:289[Extension Host] Activating extension `vscode.extension-editing` failed: Cannot find module 'typescript'.x.logExtensionHostMessage @ extensionHost.ts:289
extensionHost.ts:289[Extension Host] Activating extension `vscode.extension-editing` failed:  Cannot find module 'typescript'x.logExtensionHostMessage @ extensionHost.ts:289
extensionHost.ts:289[Extension Host] Here is the error stack:  Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.N.f._load (c:\Alex\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:24608)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Alex\Programs\Microsoft VS Code Insiders\resources\app\extensions\extension-editing\out\extension.js:7:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
mainThreadExtensionService.ts:103Activating extension `vscode.extension-editing` failed: Cannot find module 'typescript'.
```

Indeed, the bundled extension `vscode.extension-editing` misses the `node_modules` folder and there is an npm-debug.log in there:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly fetchPackageMetaData typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz
17 silly fetchOtherPackageData typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz
18 silly cache add args [ 'typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
18 silly cache add   null ]
19 verbose cache add spec typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz
20 silly cache add parsed spec Result {
20 silly cache add   raw: 'typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
20 silly cache add   scope: null,
20 silly cache add   name: 'typescript',
20 silly cache add   rawSpec: 'https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
20 silly cache add   spec: 'https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
20 silly cache add   type: 'remote' }
21 silly mapToRegistry name typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz
22 silly mapToRegistry using default registry
23 silly mapToRegistry registry https://registry.npmjs.org/
24 silly mapToRegistry data Result {
24 silly mapToRegistry   raw: 'typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
24 silly mapToRegistry   scope: null,
24 silly mapToRegistry   name: 'typescript',
24 silly mapToRegistry   rawSpec: 'https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
24 silly mapToRegistry   spec: 'https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
24 silly mapToRegistry   type: 'remote' }
25 silly mapToRegistry uri https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz
26 verbose addRemoteTarball https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz not in flight; adding
27 verbose addRemoteTarball [ 'https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
27 verbose addRemoteTarball   null ]
28 info retry fetch attempt 1 at 7:04:51 AM
29 info attempt registry request try #1 at 7:04:51 AM
30 http fetch GET https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz
31 verbose request id e6988adc42b3335a
32 http fetch 200 https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz
33 info retry will retry, error on last attempt: Error: read ECONNRESET
34 info retry will retry, error on last attempt: Error: read ECONNRESET
35 silly fetchAndShaCheck shasum 10bc540017160b9d44e9ba8dfe50ba31fb860407
36 verbose addTmpTarball C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\registry.npmjs.org\typescript\-\typescript-1.8.10.tgz not in flight; adding
37 verbose correctMkdir C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
38 verbose addTmpTarball validating metadata from C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\registry.npmjs.org\typescript\-\typescript-1.8.10.tgz
39 verbose tar unpack C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\registry.npmjs.org\typescript\-\typescript-1.8.10.tgz
40 verbose tar unpacking to C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\unpack-b63a27f0
41 silly gentlyRm C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\unpack-b63a27f0 is being purged
42 verbose gentlyRm don't care about contents; nuking C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\unpack-b63a27f0
43 silly gunzTarPerm modes [ '777', '666' ]
44 silly gunzTarPerm extractEntry package.json
45 error tar.unpack unzip error C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\registry.npmjs.org\typescript\-\typescript-1.8.10.tgz
46 silly gunzTarPerm extractEntry .npmignore
47 silly gunzTarPerm extractEntry README.md
48 error tar.unpack untar error C:\Windows\SERVIC~2\LOCALS~1\AppData\Local\Temp\npm-5244-c2934cd2\registry.npmjs.org\typescript\-\typescript-1.8.10.tgz
49 silly fetchPackageMetaData Error: unexpected end of file
49 silly fetchPackageMetaData     at Zlib._handle.onerror (zlib.js:363:17)
49 silly fetchPackageMetaData  error for typescript@https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz { [Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR' }
50 silly rollbackFailedOptional Starting
51 silly rollbackFailedOptional Finishing
52 silly runTopLevelLifecycles Starting
53 silly runTopLevelLifecycles Finishing
54 silly install printInstalled
55 verbose stack Error: unexpected end of file
55 verbose stack     at Zlib._handle.onerror (zlib.js:363:17)
56 verbose cwd D:\work\3\s\extensions\extension-editing
57 error Windows_NT 6.3.9600
58 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
59 error node v5.10.1
60 error npm  v3.8.3
61 error code Z_BUF_ERROR
62 error errno -5
63 error unexpected end of file
64 error If you need help, you may report this error at:
64 error     <https://github.com/npm/npm/issues>
65 verbose exit [ -5, true ]

```

**Comment by joaomoreno** [comment]
Great catch @alexandrudima, I am very surprised how we never hit this before.
