### ISSUE TITLE
No intelli-sense is provided for the properties or methods of a TypeScript object

### ISSUE THREAD

**Issue by n-s-russell** [Microsoft/vscode#15238]
- VSCode Version: 1.7.1
- OS Version: OS X 10.11.6 (El Capitan)

Steps to Reproduce:

1. declare a variable, and initialise with the value of {} within a .ts file
2. type the name of the variable followed by a period

**Comment by gsipos** [comment]
I have the same problem, it seem to be something with Typescript version.
I have intellisense with TS@2.0.3, but it doesn't work with 2.0.6,2.0.7,2.0.8 versions of Typescript

**Comment by lafe** [comment]
The same issue is present in the current 1.8.0-insider build (Commit a28dc215af3146...) with TypeScript 2.0.8 and 2.1.1. TypeScript 2.0.3 works. It also affects highlighting errors, code navigation, etc. It seems that the compiler service does not work/does not provide any information, so VSCode thinks everything is good. If I switch back to 2.0.3 the complete TypeScript experience with IntelliSense, error highlighting, etc. is back on.

The interesting thing is that this issue does not affect all projects. My current main codebase (medium sized project) is affected whereas another project (small size) works with 2.0.8.

**Comment by waderyan** [comment]
Thank you for the comments here. Let me see if I am seeing the same thing as you are...

Here is my code.

```
var x = {};
x.
```

This is what I see:

![image](https://cloud.githubusercontent.com/assets/2449568/20232214/863b3fb2-a81b-11e6-9993-5835ec7ab877.png)

What are you expecting to see?

**Comment by gsipos** [comment]
This is what I see with TS@2.0.3(works as expected):
![intellisense203](https://cloud.githubusercontent.com/assets/4602237/20238030/1821c68c-a8e2-11e6-97ef-45b893284aa8.png)

And this is what I see with TS@2.0.7, no completion for `bar`:
![intellisense207](https://cloud.githubusercontent.com/assets/4602237/20238031/1822cb5e-a8e2-11e6-9737-636bd66ac181.png)

With `TSS_LOG=verbose` command I see the following exception in the logfile:
```
Info 4    Search path: e:/GitHub/aodocs-angular-ui/src/app/directives/document/property/category
Info 5    Config file name: e:/GitHub/aodocs-angular-ui/tsconfig.json
Err 6     Exception on executing command {"seq":3,"type":"request","command":"open","arguments":{"file":"e:/GitHub/aodocs-angular-ui/src/app/directives/document/property/category/noIntellisense.ts","fileContent":"interface Foo {\r\n\tbar: any;\r\n}\r\n\r\nvar x: Foo;\r\nx.\r\n"}}:
Cannot read property 'enableAutoDiscovery' of undefined
TypeError: Cannot read property 'enableAutoDiscovery' of undefined
    at LSHost.resolveModuleName (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:51778:57)
    at LSHost.resolveNamesWithLocalCache (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:51810:68)
    at LSHost.resolveModuleNames (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:51844:29)
    at Object.compilerHost.resolveModuleNames (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:46977:104)
    at resolveModuleNamesWorker (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:38922:93)
    at processImportedModules (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:39667:35)
    at findSourceFile (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:39590:17)
    at processSourceFile (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:39500:27)
    at processTypeReferenceDirective (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:39625:21)
    at Object.createProgram (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:38945:21)
Err 7     Exception on executing command {"seq":5,"type":"request","command":"completions","arguments":{"file":"e:/GitHub/aodocs-angular-ui/src/app/directives/document/property/category/noIntellisense.ts","line":6,"offset":3}}:
No Project.
Error: No Project.
    at Object.ThrowNoProject (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:5308:23)
    at IOSession.Session.getFileAndProjectWorker (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:54787:42)
    at IOSession.Session.getFileAndProject (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:54777:29)
    at IOSession.Session.getCompletions (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:54931:31)
    at Session.handlers.ts.createMap._a.(anonymous function) (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:54179:61)
    at IOSession.Session.executeCommand (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:55246:28)
    at IOSession.Session.onMessage (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:55266:35)
    at Interface.<anonymous> (e:\GitHub\aodocs-angular-ui\node_modules\typescript\lib\tsserver.js:56323:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
```

I hope its helpful.

**Comment by lafe** [comment]
I debugged my VSCode instance as well (did not know about the TSS_LOG environment variable before) and for me the issue was an issue with the tsconfig.json - one referenced file was missing and TypeScript 2.0.3 seems to ignore the issue whereas later versions break.
I added a Feature Request (#15445) to maybe include better handling of such issues in VS Code, because right now you do not get any information that the language service has crashed (aside from "it's not working") and why it crashed.

**Comment by waderyan** [comment]
@gsipos can you share your workspace and tsconfig.json file?

**Comment by gsipos** [comment]
I've found the problem in my tsconfig.json. It had `"outDir": ".",`  compiler option, after removing it, everything seems to work with ts@2.0.7

**Comment by waderyan** [comment]
Cool. Closing now.
