### ISSUE TITLE
[BUG] Using `pre-commit` with VS Code `git` extension/plugin and `conda` does something weird

### ISSUE THREAD

**Issue by sugatoray** [microsoft/vscode#153037]
Does this issue occur when all extensions are disabled?: Yes/No

- System Information:

  ```sh
  Version: 1.68.1
  Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
  Date: 2022-06-15T02:58:26.441Z
  Electron: 17.4.7
  Chromium: 98.0.4758.141
  Node.js: 16.13.0
  V8: 9.8.177.13-electron.0
  OS: Linux x64 5.13.0-51-generic snap
  ```

Starting VS Code from a conda environment leads to the `git` extension/plugin using that same environment with `pre-commit`. Expected behavior should be: `git` extension must use the python interpreter defined by `python.defaultInterpreterPath` in `.vscode/settings.json`.

Steps to Reproduce:

1. Assumption: using conda environment 

1. Clone `unionml` repo and start vscode.

   ```sh
   git clone https://github.com/unionai-oss/unionml
   cd unionml && code .
   ```

1. Create a conda environment for `unionml` repository.

   ```sh
   conda create -n unionml_env python=3.8 -yq
   conda activate unionml_env
   pip install \
       -r requirements.txt \
       -r requirements-dev.txt \
       -r requirements-docs.txt
   pip install -e "."
   pre-commit install
   pre-commit run --all
   ```

1. Now when I try using the VS Code UI to add some files to `staging` and then commit them using the UI as well, I get something like this:

   ```sh
   > git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - -S
   flake8...................................................................Passed
   black....................................................................Passed
   isort....................................................................Passed
   check yaml...........................................(no files to check)Skipped
   fix end of files.........................................................Passed
   trim trailing whitespace.................................................Passed
   shellcheck...........................................(no files to check)Skipped
   mypy.....................................................................Passed
   convert myst markdown to jupyter notebooks...............................Failed
   - hook id: convert-myst-to-ipynb
   - exit code: 1
   
   Traceback (most recent call last):
     File "/home/sugatoray/miniconda3/envs/build_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
       return _run_code(code, main_globals, None,
     File "/home/sugatoray/miniconda3/envs/build_env/lib/python3.8/runpy.py", line 87, in _run_code
       exec(code, run_globals)
     File "/home/sugatoray/Documents/Codeplex/Git/GitHub/unionml/scripts/myst_to_ipynb.py", line 14, in <module>
       import jupytext
   ModuleNotFoundError: No module named 'jupytext'
   ```

## Summary

If I start VS Code from a conda environment (`build_env`) and after starting VS Code set up the `python.defaultInterpreterPath` to some other conda environment (`unionml_env`), that does not seem to work with `pre-commit` + `vscode git extension`.

The `git` extension seems to use the conda environment (`build_env`) that VS Code was originally started from, instead of the intended environment, `unionml_env`. 

I also tested with starting VS Code from `unionml_env` and then using `git` plugin/extension to commit files, and it ran without any complaints.

Please fix this.

**Comment by sugatoray** [comment]
@lszomoru Thank you, for your reply. Is there any vscode settings parameter that could enable VSCode to reload safely (by saving any unsaved changes *may be*)? If that's the case, then once you add the `python.defaultInterpreterPath` to `settings.json`, a reload should fix this for now.

**Comment by brettcannon** [comment]
This is actually a duplicate of https://github.com/microsoft/vscode-python/issues/10165 .
