### ISSUE TITLE
browserType.launch: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153214]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=175659&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=4c50b82f-3f48-5844-7225-93b0027cedfd

**Comment by bpasero** [comment]
Reported as https://github.com/microsoft/playwright/issues/15127, I hope we can get some level of logging in playwright that helps us further.

I have to check why logs are not attached on Windows to our CI run, that seems weird...

**Comment by bpasero** [comment]
Oh here you go:

```
System.IO.IOException: The process cannot access the file 'D:\a\_work\1\s\.build\logs\integration-tests-browser\remoteagent.log' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.VisualStudio.Services.Content.Common.FileStreamUtils.OpenFileStreamForAsync(String filePath, FileMode mode, FileAccess fileAccess, FileShare fileShare, FileOptions extraOptions)
   at Microsoft.VisualStudio.Services.Content.Common.FileSystem.OpenStreamForFile(String fileFullPath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   at Microsoft.VisualStudio.Services.BlobStore.Common.ChunkerHelper.CreateFromFileAsync(IFileSystem fileSystem, String path, CancellationToken cancellationToken, Boolean configureAwait)
   at Microsoft.VisualStudio.Services.BlobStore.Common.FileBlobDescriptor.CalculateAsync(IFileSystem fileSystem, String rootDirectory, Boolean chunkDedup, String relativePath, FileBlobType fileBlobType, Boolean shouldPreserveSymbolicLink, Boolean shouldPreservePermissionValue, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, Boolean shouldPreserveSymbolicLink, Boolean shouldPreservePermissionValue, PageItem pageItem, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.ExceptionExtensions.ReThrow(Exception ex)
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, Boolean shouldPreserveSymbolicLink, Boolean shouldPreservePermissionValue, PageItem pageItem, CancellationToken cancellationToken)
   at Microsoft.
```

The problem is that the extension host is still running at that time holding on to log files...
