### ISSUE TITLE
"Kill" button does nothing on one task terminal

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#153486]
I have been testing the task shell integration (running some tasks, resizing the terminal to see if the decoration stayed in the right place) and now one of my task terminals is unkillable:

![Recording 2022-06-28 at 16 06 42](https://user-images.githubusercontent.com/38270282/176199341-8efc411a-b58a-4a5a-9467-1fe33fd90317.gif)

I had just killed 2 other task terminals without issue.

**Comment by alexr00** [comment]
This seems like something that might be un-reproducible so I tried to debug a bit. The `TerminalInstance` has `this._isDisposed` set to `true`, which is probably not very helpful information since I don't know how that happened.

Error in Log (Window):

```
[2022-06-28 16:02:48.418] [renderer2] [error] Cannot read properties of undefined (reading 'marker'): TypeError: Cannot read properties of undefined (reading 'marker')
    at e._getKey (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:370555)
    at e.delete (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:287197)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:371330
    at e.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:236063)
    at t.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:373870)
    at h.clearDecorations (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:9959)
    at h._dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:9701)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:8029
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:30348
    at Object.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:11:8937)
    at i (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:30061)
    at u.clear (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:30580)
    at u.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:30518)
    at h.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:31119)
    at e._wrappedAddonDispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:352979)
    at h.t.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:352692)
    at e.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:352536)
    at e.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:103965)
    at i (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:30061)
    at ji.clear (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:30580)
    at ji.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:30518)
    at Bi.dispose (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3064:832)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:31736
    at new Promise (<anonymous>)
    at U.safeDisposeTerminal (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:31700)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2236:3176
    at U._runForSelectionOrInstance (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2236:3457)
    at A.q [as _actionCallback] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2236:3122)
    at A.run (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:82:16604)
    at k.runAction (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:82:17056)
    at k.run (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:82:16959)
    at i.onClick (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:177:16236)
    at HTMLLIElement.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:177:15792)
```

**Comment by Tyriar** [comment]
Maybe caused by https://github.com/microsoft/vscode/pull/152791?

**Comment by alexr00** [comment]
Is that issue about terminal editors? I never moved the terminal into an editor.
