### ISSUE TITLE
VS Code extension host napi crash

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#153878]
* Follow steps in https://github.com/microsoft/vscode-jupyter/issues/10485#issuecomment-1171527504
* Run All cells against a Python 3.9 kernel 
* napi error throw and VS Code prompts to ask for saving the file

```
localProcessExtensionHost.ts:299 FATAL ERRO
R: Error::New napi_get_last_error_info 
1: 00007FF6D8A21486 node::Buffer::New+50438 
2: 00007FF6D8A2168F node::OnFatalError+463 
3: 00007FF6D8A214B9 node::Buffer::New+50489 
4: 00007FF6D8F5685A napi_fatal_error+154 
5: 00007FFC59D52B09 napi_register_module_v1+62067 
6: 00007FFC59D680F4 napi_register_module_v1+149598 
7: 00007FFC59D68725 napi_register_module_v1+151183 
8: 00007FFC59D7D963 napi_register_module_v1+237773 
9: 00007FFC59D748F3 napi_register_module_v1+2007971
0: 00007FF6D95A7276 napi_is_detached_arraybuffer+5341
1: 00007FF6D9F591CA v8::EmbedderStateScope::~EmbedderStateScope+1017221
2: 00007FF65FECD77C 
```

From then the notebook UI can be rendered any more as we got tons of Text Editor errors.

```
  ERR unknown text editor: 13fbb921-db59-4173-a6b6-c5e6c2d4ca3c. known editors:  : Error: unknown text editor: 13fbb921-db59-4173-a6b6-c5e6c2d4ca3c. known editors:  
	at S.getEditorById (../../../vs/workbench/api/worker/extensionHostWorker.js:71:91071)
	at U.$acceptEditorPropertiesChanged (../../../vs/workbench/api/worker/extensionHostWorker.js:67:43530)
	at s._doInvokeHandler (../../../vs/workbench/api/worker/extensionHostWorker.js:71:211846)
	at s._invokeHandler (../../../vs/workbench/api/worker/extensionHostWorker.js:71:211528)
	at s._receiveRequest (../../../vs/workbench/api/worker/extensionHostWorker.js:71:210285)
	at s._receiveOneMessage (../../../vs/workbench/api/worker/extensionHostWorker.js:71:208976)
	at eval (../../../vs/workbench/api/worker/extensionHostWorker.js:71:207080)
	at A.invoke (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/base/worker/workerMain.js:16:145)
	at u.deliver (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/base/worker/workerMain.js:16:2270)
	at p.fire (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/base/worker/workerMain.js:16:1848)
	at MessagePort.d.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:78:3970)
```

**Comment by deepak1556** [comment]
@rebornix we are unable to repro the crash on both my machine as well as on @rzhao271 , can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports. If you are unable to repro, check for existing reports from your previous runs at %APPDATA%\Code - Insiders\Crashpad\reports`

This looks like a crash from native module used with the python/jupyter extension.

**Comment by rebornix** [comment]
@deepak1556 thanks for the info! Turned out to be a duplicate of https://github.com/microsoft/vscode-jupyter/issues/10386. It's weird that the crash brought down the extension host and the notebook UI can't function properly. Will follow up in that issue.
