### ISSUE TITLE
Git changes don't load anymore since latest update

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#1539]
Since the latest update I can't see any changes in my Git repositories. 
I can see the amount of changed files in the repository indicated by the number below the git icon in the navigation bar. I can also see the changed files listed when I click on the icon. But when I want to see the changes then it never finishes loading.

The Git ouptut shows nothing special:

```
git fetch
git show HEAD:Source/AFile.txt
git show HEAD:Source/AFile.txt
```

Once I saw this error on the command line. I think it was related to this problem:

```
Uncaught Exception:  TypeError: Unknown encoding: windows1252
TypeError: Unknown encoding: windows1252
    at Buffer.slowToString (buffer.js:363:17)
    at Buffer.toString (buffer.js:375:31)
    at Socket.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\parts\git\electron-browser\gitApp.js:6:24085)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
Uncaught Exception:  TypeError: Unknown encoding: windows1252
TypeError: Unknown encoding: windows1252
    at Buffer.slowToString (buffer.js:363:17)
    at Buffer.toString (buffer.js:375:31)
    at Socket.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\parts\git\electron-browser\gitApp.js:6:24085)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I'm running on Windows 10 with the latest updates. Having Git 2.6.4 (64 Bit) installed via Chocolatey. I'm on a german system and my files are usually encoded in Windows1252. But even changes on UTF8 encoded files can't be displayed in Visual Studio Code.

**Comment by bpasero** [comment]
@joaomoreno fyi

**Comment by joaomoreno** [comment]
@bpasero should we be using a different buffer to string conversion than [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/node/git.lib.ts#L47)? Git is also using the `files.encoding` setting, per your suggestion, but the native Buffer doesn't seem to support all encodings that the file service does (or at least, `windows1252`). Where and how do you use this configuration value to convert bytes?

**Comment by bpasero** [comment]
@joaomoreno with node 4 iconv can no longer overwrite the toString() method so you need to use iconv manually as shown here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/textSearch.ts#L161

There is also a way to pipe iconv using a stream if you can use it.

**Comment by joaomoreno** [comment]
Great catch by the way :+1:.
