### ISSUE TITLE
i have install nodejs and when i was trying to create an react project i was getting this error 

### ISSUE THREAD

**Issue by Amitpandey241** [microsoft/vscode#154135]
**

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

I have installed nodejs and i was trying to create an react app by using this command npx create-react-app appname
but i am getting an error which,goes like this
Creating a new React app in C:\Users\ACER\desktop\reactCourse\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

Aborting installation.
Unexpected error. Please report it as a bug:
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:692:9)
    at spawn (C:\Users\ACER\AppData\Local\npm-cache\_npx\c67e74de0542c87c\node_modules\cross-spawn\index.js:12:24)
    at C:\Users\ACER\AppData\Local\npm-cache\_npx\c67e74de0542c87c\node_modules\create-react-app\createReactApp.js:383:19
    at new Promise (<anonymous>)
    at install (C:\Users\ACER\AppData\Local\npm-cache\_npx\c67e74de0542c87c\node_modules\create-react-app\createReactApp.js:334:10)
    at C:\Users\ACER\AppData\Local\npm-cache\_npx\c67e74de0542c87c\node_modules\create-react-app\createReactApp.js:461:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Deleting generated file... package.json
Deleting my-app/ from C:\Users\ACER\desktop\reactCourse
Done.

**Comment by Amitpandey241** [comment]
I have tryed creating project in different folders also but it won't work. The error remains the same.

**Comment by mjbvz** [comment]
This doesn't sound VS Code related to me
