### ISSUE TITLE
Show language service issues in VS Code

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#15445]
There were some issues in the past (e.g. #15238 or #13575) that caused the TypeScript service to crash. Unfortunately, VS Code itself did not show any information that the language service has crashed and you have to manually trace the issue. It would be great if VS Code can inform the user that the language service has a sever issue that requires the user to look into it and give a description of the error.

**Comment by waderyan** [comment]
@lafe this is a good idea. 

@dbaeumer what are your thoughts on sending this information up to the user? Possibly in the status bar? I'm imagining something like what you have done with ESLint. 

![image](https://cloud.githubusercontent.com/assets/2449568/20283581/5d52d4ca-aa6e-11e6-99be-4f0e2e19c662.png)

This would have a positive benefit of helping us track down issues quickly.

**Comment by dbaeumer** [comment]
@waderyan we discussed the status bar item back and force and and one point decided to not add one for TS. But since linters and other Language extensions have one now we should reconsider this.

If the TS server crashes we restart the server automatically. If this doesn't happen then we have a bug. If the server crashes more than 5 times then we show a window message to the user. So in the describe scenario a message should have been visible. 

@lafe have you steps to reproduce the case where the server dies and we don't show a window message

**Comment by lafe** [comment]
@dbaeumer Unfortunately, I do not have a project that is publicly available that can reproduce the issue I had. Maybe the following information can help:

tsconfig.json:
```JSON
{
  "version": "2.0.0",
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": "src/",
    "sourceMap": true,
    "target": "es5",
    "module": "amd",
    "moduleResolution": "classic",
    "declaration": false,
    "noImplicitAny": false,
    "noResolve": true,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictNullChecks": true
  },
  "include": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./typings/**/*.d.ts",
    "./jspm_packages/**/*.d.ts"
  ],
  "exclude": [
    "node_modules",
    "./typings/globals/angular-protractor/*"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
```

TSC Log of the issue, when I tried to get IntelliSense after I typed "this." (I had to remove all identifying comments; hopefully it is still enough; Log is from TypeScript 2.1.1 but the issue and log are the same with TypeScript 2.0.8):
```
Info 0    Binding...
Info 1    request: {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode"}}
Info 2    Host information vscode
Info 3    response: {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 4    0::configure: async elapsed time (in milliseconds) 2.5745
Info 5    request: {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"CommonJS","target":"ES6","allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"allowJs":true}}}
Perf 6    1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.9561
Info 7    response: {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 8    request: {"seq":2,"type":"request","command":"open","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","fileContent":"<removed>"}}
Info 9    Search path: c:/Code/<ProjectFolder>/src/Services/<Service>
Info 10   Config file name: c:/Code/<ProjectFolder>/tsconfig.json
Err 11    Exception on executing command {"seq":2,"type":"request","command":"open","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","fileContent":"<removed>"}}:
Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
Error: Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:5949:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62857:42)
    at ConfiguredProject.Project.getScriptInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62862:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62228:51)
    at c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:84
    at Object.map (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:338:29)
    at ModuleBuilder.getReferencedFileInfos (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:31)
    at ModuleBuilder.updateFileReferences (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62382:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62367:30)
    at ModuleBuilder.onProjectUpdateGraph (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62358:22)
Info 12   response: {"seq":0,"type":"response","command":"open","request_seq":2,"success":false,"message":"Error processing request. Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'\nError: Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'\n    at Object.ThrowProjectDoesNotContainDocument (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:5949:23)\n    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62857:42)\n    at ConfiguredProject.Project.getScriptInfo (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62862:29)\n    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62228:51)\n    at c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62353:84\n    at Object.map (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:338:29)\n    at ModuleBuilder.getReferencedFileInfos (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62353:31)\n    at ModuleBuilder.updateFileReferences (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62382:42)\n    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62367:30)\n    at ModuleBuilder.onProjectUpdateGraph (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62358:22)"}
Info 13   request: {"seq":3,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts"]}}
Perf 14   3::geterr: async elapsed time (in milliseconds) 1.8190
Err 15    Exception on executing command syntactic check:
Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
Error: Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:5949:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62857:42)
    at ConfiguredProject.Project.getScriptInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62862:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62228:51)
    at c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:84
    at Object.map (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:338:29)
    at ModuleBuilder.getReferencedFileInfos (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:31)
    at ModuleBuilder.updateFileReferences (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62382:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62367:30)
    at ModuleBuilder.onProjectUpdateGraph (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62358:22)
Info 16   request: {"seq":4,"type":"request","command":"change","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":59,"offset":62,"endLine":59,"endOffset":62,"insertString":"\r\n        "}}
Perf 17   4::change: async elapsed time (in milliseconds) 2.2058
Info 18   request: {"seq":5,"type":"request","command":"configure","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","formatOptions":{"tabSize":4,"indentSize":4,"convertTabsToSpaces":true,"newLineCharacter":"\n","insertSpaceAfterCommaDelimiter":true,"insertSpaceAfterSemicolonInForStatements":true,"insertSpaceBeforeAndAfterBinaryOperators":true,"insertSpaceAfterKeywordsInControlFlowStatements":true,"insertSpaceAfterFunctionKeywordForAnonymousFunctions":true,"insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis":false,"insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets":false,"insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces":false,"insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces":false,"placeOpenBraceOnNewLineForFunctions":false,"placeOpenBraceOnNewLineForControlBlocks":false}}}
Info 19   Host configuration update for file c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts
Info 20   response: {"seq":0,"type":"response","command":"configure","request_seq":5,"success":true}
Perf 21   5::configure: async elapsed time (in milliseconds) 0.9572
Err 22    Exception on executing command semantic check:
Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
Error: Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:5949:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62857:42)
    at ConfiguredProject.Project.getScriptInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62862:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62228:51)
    at c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:84
    at Object.map (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:338:29)
    at ModuleBuilder.getReferencedFileInfos (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:31)
    at ModuleBuilder.updateFileReferences (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62382:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62367:30)
    at ModuleBuilder.onProjectUpdateGraph (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62358:22)
Info 23   request: {"seq":6,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts"]}}
Perf 24   6::geterr: async elapsed time (in milliseconds) 0.3530
Info 25   request: {"seq":7,"type":"request","command":"change","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":9,"endLine":60,"endOffset":9,"insertString":"t"}}
Perf 26   7::change: async elapsed time (in milliseconds) 1.0348
Info 27   request: {"seq":9,"type":"request","command":"change","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":10,"endLine":60,"endOffset":10,"insertString":"h"}}
Perf 28   9::change: async elapsed time (in milliseconds) 0.4290
Info 29   request: {"seq":10,"type":"request","command":"change","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":11,"endLine":60,"endOffset":11,"insertString":"i"}}
Perf 30   10::change: async elapsed time (in milliseconds) 0.2429
Info 31   request: {"seq":11,"type":"request","command":"change","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":12,"endLine":60,"endOffset":12,"insertString":"s"}}
Perf 32   11::change: async elapsed time (in milliseconds) 0.1849
Info 33   request: {"seq":12,"type":"request","command":"change","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":13,"endLine":60,"endOffset":13,"insertString":"."}}
Perf 34   12::change: async elapsed time (in milliseconds) 0.1928
Info 35   request: {"seq":13,"type":"request","command":"completions","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":14}}
Err 36    Exception on executing command {"seq":13,"type":"request","command":"completions","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":14}}:
Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
Error: Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:5949:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62857:42)
    at ConfiguredProject.Project.getScriptInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62862:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62228:51)
    at c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:84
    at Object.map (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:338:29)
    at ModuleBuilder.getReferencedFileInfos (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:31)
    at ModuleBuilder.updateFileReferences (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62382:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62367:30)
    at ModuleBuilder.onProjectUpdateGraph (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62358:22)
Info 37   response: {"seq":0,"type":"response","command":"completions","request_seq":13,"success":false,"message":"Error processing request. Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'\nError: Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'\n    at Object.ThrowProjectDoesNotContainDocument (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:5949:23)\n    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62857:42)\n    at ConfiguredProject.Project.getScriptInfo (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62862:29)\n    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62228:51)\n    at c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62353:84\n    at Object.map (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:338:29)\n    at ModuleBuilder.getReferencedFileInfos (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62353:31)\n    at ModuleBuilder.updateFileReferences (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62382:42)\n    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62367:30)\n    at ModuleBuilder.onProjectUpdateGraph (c:\\Code\\<ProjectFolder>\\node_modules\\typescript\\lib\\tsserver.js:62358:22)"}
Info 38   request: {"seq":14,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts"]}}
Perf 39   14::geterr: async elapsed time (in milliseconds) 0.6005
Info 40   request: {"seq":15,"type":"request","command":"formatonkey","arguments":{"file":"c:/Code/<ProjectFolder>/src/Services/<Service>/Service.ts","line":60,"offset":9,"key":"\n"}}
Perf 41   15::formatonkey: elapsed time (in milliseconds) 112.4660
Info 42   response: {"seq":0,"type":"response","command":"formatonkey","request_seq":15,"success":true,"body":[]}
Err 43    Exception on executing command syntactic check:
Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
Error: Project 'c:/Code/<ProjectFolder>/tsconfig.json' does not contain document 'c:/Code/<ProjectFolder>/typings/globals/angular-protractor/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:5949:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62857:42)
    at ConfiguredProject.Project.getScriptInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62862:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62228:51)
    at c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:84
    at Object.map (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:338:29)
    at ModuleBuilder.getReferencedFileInfos (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62353:31)
    at ModuleBuilder.updateFileReferences (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62382:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62367:30)
    at ModuleBuilder.onProjectUpdateGraph (c:\Code\<ProjectFolder>\node_modules\typescript\lib\tsserver.js:62358:22)
```
This is only an excerpt of the log but the following entries are the same. I tried multiple times to get the auto completion for "this.", so that I get the notification message you mentioned. Unfortunately, the message never appeared.

Based on the log, I am not sure if the TS server really crashed (as in exited), because the first ten log entries appear only once at the start. After the exception occurred, it is "business as usual" and the TS server seems to continue to work.

BTW: Issue has been gone after I removed the exclude for the "angular-protractor" typings from the file.

**Comment by waderyan** [comment]
@bowdenk7 can I get your eyes on OP's tsconfig above? He sent the TS log and from what I can tell it looks like there is an error in parsing the file.

**Comment by lafe** [comment]
Why has this issue been closed when there were no further questions and it was part of the backlog?
