### ISSUE TITLE
Markdown preview fails

### ISSUE THREAD

**Issue by DrShushen** [microsoft/vscode#154655]
Type: <b>Bug</b>

To reproduce:
* Open any markdown `.md` file.
* Click on "Open Preview to the Side (Ctrl+K V)"
* Preview doesn't open and you see a message "command 'markdown.showPreviewToSide' not found".

From Log (Extension Host):
```
[2022-07-09 21:36:32.364] [exthost] [error] Activating extension vscode.markdown-language-features failed due to an error:
[2022-07-09 21:36:32.364] [exthost] [error] Error: Cannot find module '/snap/code-insiders/1044/usr/share/code-insiders/resources/app/extensions/markdown-language-features/dist/extension.node'
Require stack:
- /snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/loader.js
- /snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/bootstrap-amd.js
- /snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
	at Function.o._resolveFilename (node:electron/js2c/utility_node_init:17:876)
	at Module._load (node:internal/modules/cjs/loader:832:27)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14538)
	at Function.v._load (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62234)
	at Function.w._load (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61602)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/loader.js:5:101)
	at b._loadCommonJSModule (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:63692)
	at b._doActivateExtension (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14752)
	at b._activateExtension (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13700)
	at async w._activate (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async w._waitForDepsThenActivate (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async w._initialize (/snap/code-insiders/1044/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
```

My vscode-insiders information:
```
Version: 1.70.0-insider
Commit: 3104db414c8fedcf6e4493f14da7df0b7413853a
Date: 2022-07-08T05:18:19.214Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-40-generic snap
```

VS Code version: Code - Insiders 1.70.0-insider (3104db414c8fedcf6e4493f14da7df0b7413853a, 2022-07-08T05:18:19.214Z)
OS version: Linux x64 5.15.0-40-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 1500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|62.71GB (54.58GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 5e036db4-7975-4920-936d-345ce33b1cab|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.4.0
gitlens-insiders|eam|2022.7.817
language-cython|guy|0.0.7
vscode-edit-csv|jan|0.7.1
vscode-docker|ms-|1.22.0
python|ms-|2022.11.11891004
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.7.1001902022
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.242.0
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
autodocstring|njp|0.6.1
code-spell-checker|str|2.3.0
even-better-toml|tam|0.16.4
simple-rst|tro|1.5.2
zoombar-vscode|wra|1.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506

```

</details>

**Comment by DrShushen** [comment]
I found this is a duplicate issue.

**Comment by klsetzer** [comment]
> 

Can you point us to the original?

**Comment by DrShushen** [comment]
https://github.com/microsoft/vscode/issues/154653
Fixed by
https://github.com/microsoft/vscode/pull/154656

**Comment by klsetzer** [comment]
> https://github.com/microsoft/vscode/issues/154653
> 
> Fixed by
> 
> https://github.com/microsoft/vscode/pull/154656

Thank you so much.
