### ISSUE TITLE
parameterHintsWidget: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154750]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=f894412d-8943-8c38-2f3d-b3a9d75d0578):
```
TypeError: Cannot read properties of undefined (reading 'length')
[at Uo.getParameterLabelOffsets in src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts:330:27](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L330:27)
[at Uo.renderParameters in src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts:309:29](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L309:29)
[at Uo.render in src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts:222:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L222:9)
[at <anonymous> in src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts:77:10](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L77:10)
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24)
[at m.doTrigger in src/vs/editor/contrib/parameterHints/browser/parameterHintsModel.ts:222:26](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/contrib/parameterHints/browser/parameterHintsModel.ts#L222:26)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mjbvz** [comment]
This is most likely caused by an extension giving us bad data. Our other type converter don't do runtime validation so not thinking we want to add it just for this case
