### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154757]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=bc352612-56be-777a-b559-9e145b8593e6):
```
TypeError: Cannot read properties of null (reading 'value')
[at T in src/vs/base/browser/markdownRenderer.ts:452:23](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/markdownRenderer.ts#L452:23)
at pc.getHover in out/vs/workbench/workbench.desktop.main.js:2966:19879
[at pc.renderElement in src/vs/workbench/browser/parts/views/treeView.ts:1018:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/browser/parts/views/treeView.ts#L1018:22)
[at renderElement in src/vs/base/browser/ui/tree/asyncDataTree.ts:108:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L108:17)
[at T.renderElement in src/vs/base/browser/ui/tree/abstractTree.ts:408:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/abstractTree.ts#L408:17)
[at H.renderElement in src/vs/base/browser/ui/list/listWidget.ts:1110:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listWidget.ts#L1110:13)
[at c.insertItemInDOM in src/vs/base/browser/ui/list/listView.ts:815:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listView.ts#L815:13)
[at c._splice in src/vs/base/browser/ui/list/listView.ts:565:10](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listView.ts#L565:10)
[at c.splice in src/vs/base/browser/ui/list/listView.ts:467:16](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listView.ts#L467:16)
[at <anonymous> in src/vs/base/browser/ui/list/splice.ts:17:35](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/splice.ts#L17:35)
at Array.forEach (<anonymous>)
[at t.splice in src/vs/base/browser/ui/list/splice.ts:17:20](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/splice.ts#L17:20)
[at <anonymous> in src/vs/base/browser/ui/list/listWidget.ts:1431:57](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listWidget.ts#L1431:57)
[at v.bufferEvents in src/vs/base/common/event.ts:1065:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L1065:13)
[at M.splice in src/vs/base/browser/ui/list/listWidget.ts:1431:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/list/listWidget.ts#L1431:22)
[at M.splice in src/vs/base/browser/ui/tree/abstractTree.ts:1244:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/abstractTree.ts#L1244:9)
[at S.spliceSimple in src/vs/base/browser/ui/tree/indexTreeModel.ts:305:14](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/indexTreeModel.ts#L305:14)
[at S.splice in src/vs/base/browser/ui/tree/indexTreeModel.ts:156:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/indexTreeModel.ts#L156:9)
[at A._setChildren in src/vs/base/browser/ui/tree/objectTreeModel.ts:122:14](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/objectTreeModel.ts#L122:14)
[at A.setChildren in src/vs/base/browser/ui/tree/objectTreeModel.ts:71:8](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/objectTreeModel.ts#L71:8)
[at D.setChildren in src/vs/base/browser/ui/tree/objectTree.ts:63:14](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/objectTree.ts#L63:14)
[at de.render in src/vs/base/browser/ui/tree/asyncDataTree.ts:944:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L944:13)
[at de.refreshAndRenderNode in src/vs/base/browser/ui/tree/asyncDataTree.ts:715:8](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L715:8)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
[at async de._updateChildren in src/vs/base/browser/ui/tree/asyncDataTree.ts:514:3](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L514:3)
[at async de.updateChildren in src/vs/base/browser/ui/tree/asyncDataTree.ts:500:3](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L500:3)
at async Promise.all (index 0)
[at async ge.doRefresh in src/vs/workbench/browser/parts/views/treeView.ts:802:4](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/browser/parts/views/treeView.ts#L802:4)
```

**Comment by mjbvz** [comment]
I believe this is because a bad markdown string is passed into `markdownRenderer.ts`

**Comment by alexr00** [comment]
It looks like this may come from an extension setting a tree item tooltip to `null`, especially since it's only hitting on ~100 machines. The API doesn't support `null` here, but we don't validate that the objects passed in to the API are as expected. I will add validation for the tree view, but I don't think we can throw if the object isn't valid since that may break existing extensions.

**Comment by alexr00** [comment]
I've added some console logs for when extensions provide bad tree items. Let's wait a release or two to give extensions a chance to clean this up then I'll add a throw so that we don't get error telemetry anymore.
