### ISSUE TITLE
SyntaxError: Invalid regular expression: /^/s*{/*/s*#?region/b.**/}/: Nothing to repeat

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154766]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=b549a04a-6906-c4f8-fc89-8550e3e8dbe7):
```
SyntaxError: Invalid regular expression: /^/s*{/*/s*#?region/b.**/}/: Nothing to repeat
at new RegExp (<anonymous>)
[at r._handleConfig in src/vs/workbench/contrib/codeEditor/browser/languageConfigurationExtensionPoint.ts:399:33](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/codeEditor/browser/languageConfigurationExtensionPoint.ts#L399:33)
[at r._loadConfigurationsForMode in src/vs/workbench/contrib/codeEditor/browser/languageConfigurationExtensionPoint.ts:125:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/codeEditor/browser/languageConfigurationExtensionPoint.ts#L125:9)
```

**Comment by mjbvz** [comment]
It's unclear to me which language is producing this error. Doesn't seem like one of our built-in ones from a quick search, but could be wrong?
