### ISSUE TITLE
Error: Unable to read file 'vscode-userdata:/.config/Code/User/settings.json' (Error: File not modified since)

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154751]
Sounds like a non-error situation that should not be logged?

[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=cc8566c4-669f-d9eb-bb47-e30270b73770):
```
Error: Unable to read file 'vscode-userdata:/.config/Code/User/settings.json' (Error: File not modified since)
[at h.doReadFileStream in src/vs/platform/files/common/fileService.ts:571:11](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/platform/files/common/fileService.ts#L571:11)
[at async p.doRead in src/vs/workbench/services/textfile/browser/textFileService.ts:220:19](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/textfile/browser/textFileService.ts#L220:19)
[at async p.readStream in src/vs/workbench/services/textfile/browser/textFileService.ts:199:35](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/textfile/browser/textFileService.ts#L199:35)
[at async Ir.resolveFromFile in src/vs/workbench/services/textfile/common/textFileEditorModel.ts:433:20](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L433:20)
[at async in src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts:369:8](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L369:8)
```

**Comment by bpasero** [comment]
From my memory I had thought we exclude all errors from file system by now, but maybe we missed a case or are not doing this in web? Moving to Logan who did this.

**Comment by lramos15** [comment]
Closing for now as I believe this is properly excluded now, I do not see it in any of our recent tables
