### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'uri')

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154764]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=0a807dbd-9b2b-fa14-7fc2-d23c2c075844):
```
TypeError: Cannot read properties of null (reading 'uri')
at <anonymous> in out/vs/workbench/workbench.desktop.main.js:2300:40290
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24)
[at a.set input [as input] in src/vs/workbench/api/browser/mainThreadComments.ts:39:26](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/api/browser/mainThreadComments.ts#L39:26)
at <anonymous> in out/vs/workbench/workbench.desktop.main.js:2300:39690
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17)
[at deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24)
[at G.setValue in src/vs/editor/browser/widget/codeEditorWidget.ts:1888:28](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/widget/codeEditorWidget.ts#L1888:28)
[at <anonymous> in src/vs/editor/browser/widget/codeEditorWidget.ts:326:28](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/widget/codeEditorWidget.ts#L326:28)
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24)
[at <anonymous> in src/vs/editor/browser/widget/codeEditorWidget.ts:2135:19](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/widget/codeEditorWidget.ts#L2135:19)
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24)
[at HTMLDivElement.Ze in src/vs/base/browser/dom.ts:963:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/dom.ts#L963:22)
[at d.setSelectionRange in src/vs/editor/browser/controller/textAreaInput.ts:791:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/controller/textAreaInput.ts#L791:13)
[at A.writeToTextArea in src/vs/editor/browser/controller/textAreaState.ts:71:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/controller/textAreaState.ts#L71:13)
[at b._setAndWriteTextAreaState in src/vs/editor/browser/controller/textAreaInput.ts:603:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/controller/textAreaInput.ts#L603:17)
[at b.writeScreenReaderContent in src/vs/editor/browser/controller/textAreaInput.ts:613:8](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/controller/textAreaInput.ts#L613:8)
[at b._setHasFocus in src/vs/editor/browser/controller/textAreaInput.ts:588:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/controller/textAreaInput.ts#L588:9)
[at b.focusTextArea in src/vs/editor/browser/controller/textAreaInput.ts:558:8](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/controller/textAreaInput.ts#L558:8)
[at c.focusTextArea in src/vs/editor/browser/controller/textAreaHandler.ts:603:23](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/controller/textAreaHandler.ts#L603:23)
[at z.focus in src/vs/editor/browser/view.ts:480:25](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/view.ts#L480:25)
[at h.focus in src/vs/editor/browser/widget/codeEditorWidget.ts:1430:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/browser/widget/codeEditorWidget.ts#L1430:24)
[at r.focusCommentEditor in src/vs/workbench/contrib/comments/browser/commentReply.ts:148:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentReply.ts#L148:22)
[at u.focusCommentEditor in src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts:266:23](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts#L266:23)
[at n._refresh in src/vs/workbench/contrib/comments/browser/commentThreadZoneWidget.ts:414:31](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentThreadZoneWidget.ts#L414:31)
[at n.show in src/vs/workbench/contrib/comments/browser/commentThreadZoneWidget.ts:459:8](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentThreadZoneWidget.ts#L459:8)
[at n.display in src/vs/workbench/contrib/comments/browser/commentThreadZoneWidget.ts:329:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentThreadZoneWidget.ts#L329:9)
[at $.displayCommentThread in src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts:689:14](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts#L689:14)
[at <anonymous> in src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts:901:10](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts#L901:10)
at Array.forEach (<anonymous>)
[at <anonymous> in src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts:891:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts#L891:17)
at Array.forEach (<anonymous>)
[at $.setComments in src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts:885:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts#L885:22)
[at <anonymous> in src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts:452:9](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts#L452:9)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by alexr00** [comment]
I think it's coming from here: https://github.com/microsoft/vscode/blob/72208d7bbb0e151a54f012ffb382095f0f4c5ba4/src/vs/workbench/contrib/comments/browser/commentReply.ts#L222-L223
