### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'innerText')

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154754]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=1f948a91-d348-e9cc-6fdd-90863095a43f):
```
TypeError: Cannot set properties of undefined (setting 'innerText')
at t.renderRows in vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:179118
at t._renderRows in vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:199553
at e._renderCallback in vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:197172
at e._innerRefresh in vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:37313
at <anonymous> in vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:37029
```

**Comment by meganrogge** [comment]
this is the only reference of `innerText` I see, but `element` is checked there so not sure how this could be happening

https://github.com/meganrogge/xterm.js/blob/fcf378b172c4d076f556ef68e8098c8d606edd32/src/browser/AccessibilityManager.ts#L265

**Comment by Tyriar** [comment]
This one's stale, too hard to see where the problem is and whether it's been fixed or not.
