### ISSUE TITLE
"Error"

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154763]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=de82e894-284a-0996-4d94-7fcde4a65738):
```
Error
[at o.handleErrorResponse in src/vs/workbench/contrib/debug/browser/rawDebugSession.ts:755:18](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L755:18)
[at <anonymous> in src/vs/workbench/contrib/debug/browser/rawDebugSession.ts:731:49](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L731:49)
[at async o.next in src/vs/workbench/contrib/debug/browser/rawDebugSession.ts:324:20](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L324:20)
[at async F.next in src/vs/workbench/contrib/debug/browser/debugSession.ts:621:3](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/debug/browser/debugSession.ts#L621:3)
[at async y in src/vs/workbench/contrib/debug/browser/debugCommands.ts:128:3](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L128:3)
```

**Comment by weinand** [comment]
A DAP error response received from the DAP `next` request.
