### ISSUE TITLE
Error: TreeError [FileExplorer] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154749]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=322e620c-2dc3-446f-5266-ca1975436648):
```
Error: TreeError [FileExplorer] Tree element not found: [object Object]
[at s.getCompressedNode in src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts:343:10](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts#L343:10)
[at s.isCollapsed in src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts:297:31](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts#L297:31)
[at c.isCollapsed in src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts:520:21](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts#L520:21)
[at m.isCollapsed in src/vs/base/browser/ui/tree/abstractTree.ts:1622:21](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/abstractTree.ts#L1622:21)
[at ie.setChildren in src/vs/base/browser/ui/tree/asyncDataTree.ts:844:33](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L844:33)
[at ie.doRefreshNode in src/vs/base/browser/ui/tree/asyncDataTree.ts:779:16](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L779:16)
[at async ie.doRefreshSubTree in src/vs/base/browser/ui/tree/asyncDataTree.ts:745:30](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L745:30)
```

**Comment by lramos15** [comment]
@joaomoreno Similar to https://github.com/microsoft/vscode/issues/154744 let me know if you have any ideas

**Comment by joaomoreno** [comment]
Basically the FileExplorer is reaching out to a node which doesn't exist. So you get an exception. Best you can do here is attempt to repro this bad usage of the tree widget.

**Comment by lramos15** [comment]
@joaomoreno Got a repro today when trying to #155131. 

Everything seems ok with the explorer. From my understanding it's `getInput` from the asyncData tree that is returning me the workspace root (in this case vscode-hexeditor) which is not a folder within the explorer but instead is the parent folder that I have open. This means when I ask `compressedObjectTreeModel` for this node it is not a node in the explorer because it is the open workspace and the nodes are what is inside that folder. This leads to the root `TInput` returned by `getInput` being an item that I cannot call `tree.isCollapsed(input)` on. This is especially tricky because to guard against this I check for `hasNode` but `hasNode` also has a check to say true if it's the root element even if it's not a node on the tree.

```
	hasNode(element: TInput | T): boolean {
		return element === this.root.element || this.nodes.has(element as T);
	}
```

<img width="813" alt="image" src="https://user-images.githubusercontent.com/4544166/179052977-c227a5cf-f8bd-4ca8-95df-34314f9a11c4.png">

Hopefully that makes sense, it feels like at tree bug but feel free to let me know if not and I will try to investigate further why this is breaking

**Comment by joaomoreno** [comment]
@lramos15 What are the steps so I can repro myself?

**Comment by lramos15** [comment]
> @lramos15 What are the steps so I can repro myself?

Set a breakpoint on https://github.com/microsoft/vscode/blob/e225afee30d7c11ba2d8d1cb394849a539370d71/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L81-L82 and then toggle a top level node's collapsed state. The error telemetry has similar errors for other trees so I'm not sure if other trees might also be using the tree widget incorrectly.

**Comment by joaomoreno** [comment]
@lramos15 I've followed these steps:

1. Open a new window
2. Open dev tools
3. Add a folder to the workspace
4. Add another folder to the workspace
5. Collapse/expand root nodes

I still see no errors in devtools. Can you provide exact steps so I can repro the exception?

**Comment by lramos15** [comment]
I think I fixed my repro via https://github.com/microsoft/vscode/pull/155334 so I'm closing this for now. Will reopen if Error continues to flow but I can no longer repro locally
