### ISSUE TITLE
ReferenceError: WebAssembly is not defined

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154752]
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=716989aa-79dd-5db5-3109-d23204a8edaa):
```
ReferenceError: WebAssembly is not defined
at z in https://main.vscode-cdn.net/stable/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/node_modules/vscode-oniguruma/release/main.js:1:7821
at Object.n [as default] in https://main.vscode-cdn.net/stable/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/node_modules/vscode-oniguruma/release/main.js:1:6044
at <anonymous> in https://main.vscode-cdn.net/stable/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/node_modules/vscode-oniguruma/release/main.js:1:4636
at n.loadWASM in https://main.vscode-cdn.net/stable/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/node_modules/vscode-oniguruma/release/main.js:1:4868
[at k._doGetVSCodeOniguruma in src/vs/workbench/services/textMate/browser/abstractTextMateService.ts:410:25](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L410:25)
at async Promise.all (index 1)
[at async k._getOrCreateGrammarFactory in src/vs/workbench/services/textMate/browser/abstractTextMateService.ts:229:45](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L229:45)
[at async Object.createTokenizationSupport in src/vs/workbench/services/textMate/browser/abstractTextMateService.ts:264:29](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L264:29)
[at async R._create in src/vs/editor/common/tokenizationRegistry.ts:146:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/common/tokenizationRegistry.ts#L146:17)
[at async A.getOrCreate in src/vs/editor/common/tokenizationRegistry.ts:72:3](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/editor/common/tokenizationRegistry.ts#L72:3)
```

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/155494
