### ISSUE TITLE
Terminal Profiles smoke test failures

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154811]
[Build failure](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=177645&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=f6fa0c76-88f1-5f6f-9d18-af6cffee8180&l=181):
```
  52 passing (9m)
  11 pending
  4 failing

  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Profiles
           should set the default profile to a contributed one:
     Error: Timeout: get element '.terminal.xterm.focus' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:255:11)
      at Code.waitForElement (D:\a\_work\1\s\test\automation\src\code.ts:208:10)
      at Terminal._waitForTerminal (D:\a\_work\1\s\test\automation\src\terminal.ts:276:3)
      at Terminal.runCommand (D:\a\_work\1\s\test\automation\src\terminal.ts:92:5)
      at Terminal.createTerminal (D:\a\_work\1\s\test\automation\src\terminal.ts:133:3)
      at Context.<anonymous> (src\areas\terminal\terminal-profiles.test.ts:36:4)
```

**Comment by Tyriar** [comment]
May have been introduced by https://github.com/microsoft/vscode/pull/154474?
