### ISSUE TITLE
install error on CentOS 6.7

### ISSUE THREAD

**Issue by rwhenderson** [Microsoft/vscode#15480]
- VSCode Version: 7.1.0
- OS Version: CentOS 6.7
- node.js Version: 6.9.1
- npm Version 3.10.8
- Python Version 2.7.8
- gcc Version: 5.2.1 (Red Hat 5.2.1-2)
- X11 Version: libX11-devel-1.6.3-2.el6.x86_64

Steps to Reproduce:

1. ./scripts/npm.sh install --arch=x64

root@neawanna-cent6 vscode]# ./scripts/npm.sh install --arch=x64
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN lifecycle code-oss-dev@1.8.0~preinstall: cannot run in wd %s %s (wd=%s) code-oss-dev@1.8.0 node build/npm/preinstall.js /apps/vscode

> oniguruma@6.1.1 install /apps/vscode/node_modules/oniguruma
> node-gyp rebuild

gyp WARN EACCES user "randall" does not have permission to access the dev dir "/root/.electron-gyp/.node-gyp/iojs-1.3.8"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/apps/vscode/node_modules/oniguruma/.node-gyp"
Traceback (most recent call last):
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 263, in LoadOneBuildFile
    aux_data, includes, check)
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 300, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 243, in LoadOneBuildFile
    None)
  File "/apps/vscode/node_modules/oniguruma/.node-gyp/iojs-1.3.8/common.gypi", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-573.el6.x86_64
gyp ERR! command "/usr/lib/nodejs/node-v6.9.1/bin/node" "/usr/lib/nodejs/node-v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /apps/vscode/node_modules/oniguruma
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
code-oss-dev@1.8.0 /apps/vscode
`-- gulp-tslint@4.3.5
  `-- rcloader@0.2.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:bpasero/fsevents#vscode (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 (node_modules/windows-foreground-love):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-foreground-love@0.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-mutex@0.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 2.6.32-573.el6.x86_64
npm ERR! argv "/usr/lib/nodejs/node-v6.9.1/bin/node" "/usr/lib/nodejs/node-v6.9.1/bin/npm" "install" "--arch=x64"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /apps/vscode/npm-debug.log

**Comment by rwhenderson** [comment]
SOLVED, by setting $PYTHON e.g. `export PYTHON=/usr/local/bin/python2.7`. Don't know why that's necessary since `/usr/local/bin/python` is already a softlink to `/usr/local/bin/python2.7`, and `python -- version` from the command line returns 2.7?
