### ISSUE TITLE
issue with formatter

### ISSUE THREAD

**Issue by bigsbug** [microsoft/vscode#155154]
Issue Type: <b>Bug</b>

Formatters are hanging when trying to format on save 
that formatters : all of the available formatters

screenshot:
![image](https://user-images.githubusercontent.com/56682030/178936932-ff8f868e-b4dd-4d45-976e-0174e53a657a.png)

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:28:29.328Z)
OS version: Linux x64 5.10.0-15-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3287)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.69GB (0.39GB free)|
|Process Argv|. --crash-reporter-id c66046d1-45d1-4792-9f7a-3f78f2cb21ea|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vscode-html-css|ecm|1.13.0
vsc-python-indent|Kev|1.17.0
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1101950301
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
autodocstring|njp|0.6.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.22
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdf:30486550

```
</details><details>
<summary>Console Logs</summary>

```
workbench.desktop.main.js:2272 [[object Object]]Cannot read properties of undefined (reading 'text')
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2272 TypeError: Cannot read properties of undefined (reading 'text')
	at PythonExtension._onChange (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/out/client/src/pythonMain.js:85:23)
	at w.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at I.$acceptDirtyStateChanged (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:12298)
	at I.$acceptModelSaved (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:12041)
	at s._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13708)
	at s._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13390)
	at s._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:12159)
	at s._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10853)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:8957
	at w.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:34679
	at w.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at r._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:21097
	at w.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:14937
	at Socket.R (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2272 [[object Object]]Channel closed
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2272 Error: Channel closed
	at new NodeError (node:internal/errors:371:5)
	at ChildProcess.target.send (node:internal/child_process:721:16)
	at IPCMessageWriter.write (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-jsonrpc/lib/messageWriter.js:34:22)
	at Object.sendNotification (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-jsonrpc/lib/main.js:180:27)
	at Object.didChangeTextDocument (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:55:70)
	at Delayer.<anonymous> (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:373:28)
	at Delayer.forceDelivery (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/utils/async.js:45:27)
	at LanguageClient.forceDocumentSync (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:385:39)
	at LanguageClient.doSendRequest (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:166:18)
	at vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:160:30
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2272 [[object Object]]Channel closed
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2272 Error: Channel closed
	at new NodeError (node:internal/errors:371:5)
	at ChildProcess.target.send (node:internal/child_process:721:16)
	at IPCMessageWriter.write (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-jsonrpc/lib/messageWriter.js:34:22)
	at vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-jsonrpc/lib/main.js:195:31
	at new Promise (<anonymous>)
	at Object.sendRequest (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-jsonrpc/lib/main.js:186:20)
	at Object.sendRequest (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:43:66)
	at LanguageClient.doSendRequest (vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:167:31)
	at vscode-file://vscode-app/home/nova/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:160:30
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

```

</details>

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by bigsbug** [comment]
hi @jrieken I tried again to format my file, and it's working correctly, I don't know its a good thing or not, but if it's happened again I following your instruction
