### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by TemitopeAgbaje** [microsoft/vscode#155202]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.7.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_3 (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171897:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171905:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173574:26)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173848:97
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173848:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174983:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:88
    at IpcIOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177163:28)
    at IpcIOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:33)
    at IpcIOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177198:35)
    at process.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179833:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.13.0-52-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 2665)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.33GB (0.48GB free)|
|Process Argv|--unity-launch --crash-reporter-id c9c374c3-27f8-488e-a415-e4fec1a7e2a4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
commit-message-editor|ada|0.19.7
project-manager|ale|12.6.0
ng-template|Ang|14.0.1
markdown-preview-github-styles|bie|1.0.1
gitignore|cod|0.8.0
vscode-eslint|dba|2.2.6
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.1.2
gitlens-insiders|eam|2022.7.1305
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
auto-close-tag|for|0.5.14
docker-explorer|for|0.1.7
docker-run|geo|1.1.0
codespaces|Git|1.9.2
remotehub|Git|0.36.0
vscode-pull-request-github|Git|0.46.0
todo-tree|Gru|0.0.215
docker-linter|hen|0.5.0
vscode-git-tags|how|1.4.4
RelativePath|jak|1.5.0
csharpextensions|jch|1.3.1
Angular2|joh|13.0.0
vscode-gutter-preview|kis|0.30.0
kite|kit|0.147.0
vscode-github|Kni|0.30.7
gitignore|mic|1.0.1
snapcode|moy|1.1.0
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
remote-containers|ms-|0.241.3
remote-repositories|ms-|0.12.0
vsliveshare|ms-|1.0.5641
debugger-for-chrome|msj|4.13.0
angular-console|nrw|17.18.8
docker-compose|p1c|0.3.5
material-icon-theme|PKi|4.19.0
vscode-manage-user-secrets|Rep|1.0.4
LiveServer|rit|5.7.5
code-settings-sync|Sha|3.4.3
prettier-vscode|Sim|2.0.7
prettier-plus|svi|4.2.2
vscode-gitandgithub-pack|vin|2.0.1
quokka-vscode|Wal|1.0.489
vscode-open-in-github|ziy|1.3.6
tslint-snippets|zuo|1.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
