### ISSUE TITLE
VS code remote connection: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by zhenglilei** [microsoft/vscode#155380]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.1
- OS Version: Darwin arm64 21.5.0

Steps to Reproduce:
1. Keep the remote connection in VScode
2. AFK (away from keyboard)
3. When the connection naturally breaks, then retry to connect
4. The error message will occur.

``` bash
[18:33:55.749] Resolver error: TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.a [as sanitizeConnectionToken] (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:691806)
    at Object.C [as findRunningServer] (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:626542)
    at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622510
    at async T (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
    at async Object.t.resolveWithLocalServer (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
    at async Object.t.resolve (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
    at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[18:33:55.751] ------
```
I found that one solution is to remove VScode cache at `/Users/username/Library/Application\ Support/Code`

But this is definitely not the right way, any one knows the root cause and how to solve it?

**Comment by janus-zheng** [comment]
https://stackoverflow.com/questions/73003558/vs-code-remote-connection-cannot-read-properties-of-undefined-reading-replace/73030483?noredirect=1#comment129002557_73030483

Some one reported that this is related to the remote ssh extension. And the solution is to use the pre-release version.
