### ISSUE TITLE
Task smoke test failures (remote)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155573]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=68898&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=14ed1606-36dc-5825-3696-4fa85826ef84&l=89

```
1) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon only:
     Error: Quick open file search was unable to find 'tasks.json' after 10 attempts, giving up.
      at QuickAccess.openFileQuickAccessAndWait (/Users/runner/work/1/s/test/automation/src/quickaccess.ts:105:11)
      at Task.configureTask (/Users/runner/work/1/s/test/automation/src/task.ts:57:3)
      at Context.<anonymous> (src/areas/task/task-quick-pick.test.ts:44:5)

  2) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - color only:
     Error: Quick open file search was unable to find 'tasks.json' after 10 attempts, giving up.
      at QuickAccess.openFileQuickAccessAndWait (/Users/runner/work/1/s/test/automation/src/quickaccess.ts:105:11)
      at Task.configureTask (/Users/runner/work/1/s/test/automation/src/task.ts:57:3)
      at Context.<anonymous> (src/areas/task/task-quick-pick.test.ts:49:5)

  3) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon & color:
     Error: Quick open file search was unable to find 'tasks.json' after 10 attempts, giving up.
      at QuickAccess.openFileQuickAccessAndWait (/Users/runner/work/1/s/test/automation/src/quickaccess.ts:105:11)
      at Task.configureTask (/Users/runner/work/1/s/test/automation/src/task.ts:57:3)
      at Context.<anonymous> (src/areas/task/task-quick-pick.test.ts:54:5)

```

**Comment by meganrogge** [comment]
all runs in a 40 minute time span succeeded here https://dev.azure.com/vscode/VSCode/_build/results?buildId=73213&view=logs&j=15f6beb8-c39c-5fa4-f1fe-6e73c89d1002&t=96ed0de4-fc9b-50ae-c3cf-4e9e83914ed9 so should be safe to close this
