### ISSUE TITLE
`vscode.window.showNotebookDocument` throws if the active document is changed too quickly.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#155778]
Initially reported in dotnet/interactive#2144, but I've traced the actual exception to [this line](https://github.com/dotnet/interactive/blob/7a4c82e250bd2d957607621441bd5a683324c177/src/dotnet-interactive-vscode-common/src/commands.ts#L238).

The exception returned is:

```
Error: Notebook Editor creation failure for document [object Object]
    at S.$tryShowNotebookDocument (vscode-file://vscode-app/c:/Users/brettfo/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1704:30167)
{
  name: 'Error',
  message: 'Notebook Editor creation failure for document [object Object]',
  stack:
  'Error: Notebook Editor creation failure for document [object Object]
   at S.$tryShowNotebookDocument (vscode-file://vscode-app/c:/Users/brettfo/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1704:30167)'
}
```

**Comment by jrieken** [comment]
Yeah, that's how it works. Opening an editor is async and there can only be one editor per group. We don't sequentialise "competing" open requests but the fastest wins. When this happens the API calls error - because they fail to open the desired editor

**Comment by jrieken** [comment]
fyi @bpasero
