### ISSUE TITLE
Smoke tests: verifies that auto save triggers on shutdown:

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#155838]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178923&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=5f0e9dbb-0df0-5bb0-f10b-78953999773d

**Comment by bpasero** [comment]
Wow this really misses a file we expect to restore `README.md`:

![image](https://user-images.githubusercontent.com/900690/180213760-f9c06ca1-f27e-4af4-a3f1-86d49e4d20d4.png)

**Comment by bpasero** [comment]
I verified that I get a crash dump for when I run `process.crash` from a smoke test, so this crash simply did not produce anything meaningful. I suspect an unhealthy CI machine given logs such as:

```
[2022-07-21T12:14:37.338Z] Starting operation 'stop tracing...
[2022-07-21T12:14:37.463Z] Starting operation 'Code#exit()...
[2022-07-21T12:14:37.541Z] Starting operation 'Application#restart()...
[2022-07-21T12:14:47.557Z] Smoke test exit call did not terminate process after 10s, forcefully exiting the application...
[2022-07-21T12:14:48.606Z] Failed to kill Electron process tree: undefined
[2022-07-21T12:14:48.781Z] [electron] stderr: [65438:0721/121448.609809:ERROR:gpu_process_host.cc(979)] GPU process exited unexpectedly: exit_code=15

[2022-07-21T12:14:48.787Z] [electron] stderr: [65438:0721/121448.786782:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.

[2022-07-21T12:14:48.984Z] [electron] stdout: [90m[main 2022-07-21T12:14:48.794Z][0m UtilityProcess<1>: terminated unexpectedly with code 15.

[2022-07-21T12:14:49.350Z] [electron] stdout: [90m[main 2022-07-21T12:14:49.065Z][0m Extension host with pid 65656 exited with code: 15, signal: .
[90m[main 2022-07-21T12:14:49.066Z][0m UtilityProcess<1>: received exit event with code 0.
[90m[main 2022-07-21T12:14:49.066Z][0m Extension host with pid 65656 exited with code: 0, signal: .
[90m[main 2022-07-21T12:14:49.089Z][0m UtilityProcess<1>: Waiting for extension host with pid undefined to exit.

[2022-07-21T12:14:49.953Z] [electron] stderr: [91m[main 2022-07-21T12:14:49.069Z][0m CodeWindow: renderer process crashed (reason: killed, code: 15)
[91m[main 2022-07-21T12:14:49.083Z][0m [uncaught exception in main]: Error: SharedProcess: crashed (detail: killed, code: 15)
[91m[main 2022-07-21T12:14:49.084Z][0m Error: SharedProcess: crashed (detail: killed, code: 15)
    at /Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:77:77396
    at b.invoke (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:145)
    at I.deliver (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:2272)
    at w.fire (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:1850)
    at /Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:17:19798
    at b.invoke (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:145)
    at I.deliver (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:2272)
    at w.fire (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:1850)
    at EventEmitter.<anonymous> (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:74:84726)
    at EventEmitter.emit (node:events:402:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:173:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:169:2494)
    at g.send (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:74:82537)
    at g.onWillShutdown (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:74:82140)
    at /Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:74:81039
    at b.invoke (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:145)
    at I.deliver (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:2272)
    at w.fire (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:19:1850)
    at bt.fireOnWillShutdown (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:40:9542)
    at App.E (/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:40:8850)
    at App.emit (node:events:390:28)

[2022-07-21T12:14:50.322Z] Playwright (Electron) ERROR: page crash
[2022-07-21T12:14:50.646Z] Playwright (Electron): page close
```

This seems not actionable to me. The underlying problem here is that we:
* open 3 editors as preparation
* quit the application
* start again to verify the 3 editors

However, since quitting seems to crash the window, we have no chance to persist UI state and when we open again, the editors are not restoring. One idea would be to implement custom logic for quitting by enforcing a flush of storage service but to be honest, this would make smoke tests run different from what a normal user would see which is something I do not really like.
