### ISSUE TITLE
Task Quick Pick

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155817]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178883&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=525606ab-8bc1-59bd-2d29-e98f94fa71fe&l=109

```
1) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           "after each" hook for "hide property - undefined":
     Error: Timeout: get elements '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:256:11)
      at Code.waitForElements (D:\a\_work\1\s\test\automation\src\code.ts:205:10)
      at Terminal.runCommand (D:\a\_work\1\s\test\automation\src\terminal.ts:96:5)
      at Context.<anonymous> (src\areas\task\task-quick-pick.test.ts:23:4)
```

**Comment by Tyriar** [comment]
Flaking on this which is a little strange, kill all isn't killing all?

https://github.com/microsoft/vscode/blob/0cf530cd3cc29d1695dd60a67082e413698990f1/test/automation/src/terminal.ts#L95-L97

No trace seemed to have got uploaded.
