### ISSUE TITLE
Cannot read property 'activeParameter' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15621]
Clicked around (running out of sources) in a HTML file that includes JS (file below):

```
Cannot read property 'activeParameter' of null: TypeError: Cannot read property 'activeParameter' of null
    at asSignatureHelp (/Users/bpasero/Development/Microsoft/monaco/extensions/html/node_modules/vscode-languageclient/lib/protocolConverter.js:107:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)WorkbenchShell.onUnexpectedError @ shell.js:311(anonymous function) @ shell.js:244ErrorHandler.onUnexpectedError @ errors.js:42onUnexpectedError @ errors.js:56notifyError @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041notifyError @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041(anonymous function) @ async.js:325ErrorPromise_done @ winjs.base.raw.js:1378notifyError @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041LazyPromise.resolveErr @ ipcRemoteCom.js:76receiveOneMessage @ ipcRemoteCom.js:144_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

```html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<link rel="stylesheet" href="qunit/qunit2.css" type="text/css" media="screen" />
		<script>
			console.log("Find");
			if (!Function.prototype.bind) {
				Function.prototype.bind = (function () {
					var slice = Array.prototype.slice;
					return function () {
						var originalFunc = this, thisArg = arguments[0], boundArgs = slice.call(arguments, 1);
						return function () {
							return originalFunc.apply(thisArg, slice.call(boundArgs, 0).concat(slice.call(arguments, 0)));
						};
					};
				})();
			}
		</script>
		<script src="qunit/loader.js"></script>
		<script src="lib/Base.js"></script>
		<script src="qunit/qunit.js"></script>
		<script src="qunit/selfhosting-reporting.js"></script>
		<!-- the actual tests to execute -->
		<script type="text/javascript" src="lib/Base.tests.js"></script>
	</head>
	<body>
		<h1 id="qunit-header">Mankala Tests</h1>
		<h2 id="qunit-banner"></h2>
		<div id="qunit-testrunner-toolbar"></div>
		<h2 id="qunit-userAgent"></h2>
		<ol id="qunit-tests"></ol>
		<div id="qunit-fixture">test markup, will be hidden</div>
	</body>

</html>⁄
```

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode-languageserver-node/commit/c5e4194d92b22d6060b97a951aad8919704263c9
