### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by abrahamsaanchez** [microsoft/vscode#156415]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.7.3

I got an error saying that the typescript server died 5 times in the last 5 minutes. I don't know how to reproduce it.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_3 (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171897:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171905:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173574:26)
    at c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173848:97
    at Object.flatMap (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173848:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174983:46)
    at c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177172:88
    at IpcIOSession.Session.executeWithRequestId (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177163:28)
    at IpcIOSession.Session.executeCommand (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177172:33)
    at IpcIOSession.Session.onMessage (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177198:35)
    at process.<anonymous> (c:\Users\Abraham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179833:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (4.73GB free)|
|Process Argv|--crash-reporter-id 34ca6002-129d-4d10-8f02-9abd2d4044a7|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.1.0
emojisense|bie|0.9.1
vscode-intelephense-client|bme|1.8.2
vscode-tailwindcss|bra|0.8.6
postcss|css|1.0.9
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
auto-rename-tag|for|0.1.10
php-cs-fixer|jun|0.3.1
vscode-docker|ms-|1.22.1
angular-console|nrw|17.19.0
material-icon-theme|PKi|4.19.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30534093

```

</details>

**Comment by abrahamsaanchez** [comment]
Seems to be a GitLens problem. Close the issue.
