### ISSUE TITLE
Illegal value for lineNumber: Error: Illegal value for lineNumber

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156616]
Testing #156175

1. Enable sticky scrolling
2. Open a TS file 
3. Open `vscode.d.ts` and scroll down in the file
4. Close `vscode.d.ts`  so that the originally opened file is now visible 

**Bug**

```
  ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at _n.getLineContent (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:738:5507)
    at u._renderStickyScroll (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:701:14389)
    at u._update (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:701:12689)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:701:11999
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:752:17923
    at S.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at s.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at A._emitOutgoingEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:584:75266)
    at A.endEmitViewEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:584:75962)
    at m._withViewEventsCollector (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:750:4911)
    at m.restoreCursorState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:750:2942)
    at tn.restoreViewState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:752:7678)
    at g.setInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2723:94889)
    at async a.doSetInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2721:6429)
    at async a.doOpenEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2721:4791)
    at async a.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2721:3783)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2928:16842
```

**Comment by alexdima** [comment]
Deminified using https://github.com/alexdima/vscode-stack-beautifier

ERR&nbsp;Illegal&nbsp;value&nbsp;for&nbsp;lineNumber:&nbsp;Error:&nbsp;Illegal&nbsp;value&nbsp;for&nbsp;lineNumber<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/model/textModel.ts:790:9`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/common/model/textModel.ts#L790)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/stickyScroll/browser/stickyScroll.ts:213:32`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/contrib/stickyScroll/browser/stickyScroll.ts#L213)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/stickyScroll/browser/stickyScroll.ts:101:7`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/contrib/stickyScroll/browser/stickyScroll.ts#L101)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/contrib/stickyScroll/browser/stickyScroll.ts:69:68`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/contrib/stickyScroll/browser/stickyScroll.ts#L69)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:622:16`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./base/common/event.ts#L622)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:824:21`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./base/common/event.ts#L824)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:785:23`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./base/common/event.ts#L785)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1652:29`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1652)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:622:16`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./base/common/event.ts#L622)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:824:21`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./base/common/event.ts#L824)<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:785:23`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./base/common/event.ts#L785)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:64:17`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/common/viewModelEventDispatcher.ts#L64)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModelEventDispatcher.ts:109:7`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/common/viewModelEventDispatcher.ts#L109)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModel/viewModelImpl.ts:1056:25`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/common/viewModel/viewModelImpl.ts#L1056)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/viewModel/viewModelImpl.ts:984:7`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/common/viewModel/viewModelImpl.ts#L984)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/widget/codeEditorWidget.ts:1030:31`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1030)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/contrib/files/browser/editors/textFileEditor.ts:127:13`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./workbench/contrib/files/browser/editors/textFileEditor.ts#L127)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/browser/parts/editor/editorPanes.ts:353:3`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./workbench/browser/parts/editor/editorPanes.ts#L353)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/browser/parts/editor/editorPanes.ts:222:33`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./workbench/browser/parts/editor/editorPanes.ts#L222)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/browser/parts/editor/editorPanes.ts:126:10`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./workbench/browser/parts/editor/editorPanes.ts#L126)<br/>&nbsp;&nbsp;at&nbsp;[`./workbench/browser/parts/editor/editorGroupView.ts:1081:48`](https://github.com/Microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/./workbench/browser/parts/editor/editorGroupView.ts#L1081)<br/>
