### ISSUE TITLE
vscode.dev share url does not load

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#156627]
Testing #156153

<img width="1540" alt="CleanShot 2022-07-28 at 13 07 38@2x" src="https://user-images.githubusercontent.com/35271042/181627791-22dd2cec-067c-4923-8cb2-564922b83d7c.png">

Steps:
1. open notebook in desktop
2. copy share URL 
3. paste in browser
4. :bug: nothing loads

Relading the URL doesn't appear to fix it. This is the URL I tried loading: https://insiders.vscode.dev/github/misolori/notebooks/blob/51e863f1f4fd0e350507e26a92fa832a0abe9657/data-cleaning.ipynb#C3:L1

```log
sw.js:1 SW Preloading workbench: Object
api.github.com/repos/misolori/notebooks/git/extract-ref/51e863f1f4fd0e350507e26a92fa832a0abe9657/data-cleaning.ipynb:1          Failed to load resource: the server responded with a status of 404 ()
main.js:1 HttpError: No ref found
    at main.js:1:14940
(anonymous) @ main.js:1
api.github.com/repos/misolori/notebooks/git/extract-ref/51e863f1f4fd0e350507e26a92fa832a0abe9657/data-cleaning.ipynb:1          Failed to load resource: the server responded with a status of 404 ()
main.js:1 HttpError: No ref found
    at main.js:1:14940
(anonymous) @ main.js:1
log.ts:307  WARN Ignoring the error while validating workspace folder vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a322c226964223a2235316538363366316634666430653335303530376532366139326661383332613061626539363537227d7d/misolori/notebooks - No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a322c226964223a2235316538363366316634666430653335303530376532366139326661383332613061626539363537227d7d/misolori/notebooks'
webWorkerExtensionHost.ts:143 Unrecognized feature: 'serial'.
_startInsideIframe @ webWorkerExtensionHost.ts:143
mobile.events.data.microsoft.com/OneCollector/1.0:1          Failed to load resource: the server responded with a status of 415 (Content-Type=[] not supported)
log.ts:319 CRITI Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookDocumentEvents' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:313   ERR [ms-vscode.remote-repositories]: notebook/cell/executePrimary is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["notebookEditor"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vscode.remote-repositories
log.ts:313   ERR [ms-vscode.vscode-js-profile-flame]: Menu item references a command `extension.js-debug.startProfile` which is not defined in the 'commands' section.
log.ts:301  INFO Migrating workspace extension storage from github.codespaces to GitHub.codespaces...
log.ts:301  INFO Migrated workspace extension storage from github.codespaces to GitHub.codespaces
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: https://redhat.vscode-unpkg.net/redhat/vscode-yaml/1.9.1/extension/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:47
log.ts:301  INFO Migrating workspace extension storage from GitHub.remotehub-insiders to GitHub.remotehub...
log.ts:301  INFO Migrated workspace extension storage from GitHub.remotehub-insiders to GitHub.remotehub
log.ts:301  INFO Migrating workspace extension storage from github.vscode-pull-request-github to GitHub.vscode-pull-request-github...
log.ts:301  INFO Migrated workspace extension storage from github.vscode-pull-request-github to GitHub.vscode-pull-request-github
xhr.js:166 Refused to set unsafe header "User-Agent"
setRequestHeader @ xhr.js:166
sw.js:1 SW Garbage collecting 871 entries...
sw.js:1 SW Caching 867 entries...
log.ts:301  INFO Getting Manifest... github.vscode-pull-request-github
log.ts:301  INFO Getting Manifest... github.remotehub
log.ts:301  INFO Getting Manifest... github.codespaces
log.ts:301  INFO Getting Manifest... ms-vscode.remote-repositories
log.ts:301  INFO Getting Manifest... ms-vscode.azure-repos
log.ts:301  INFO Getting Manifest... eamodio.gitlens-insiders
log.ts:301  INFO Getting Manifest... ms-toolsai.jupyter
log.ts:301  INFO Getting Manifest... ms-vscode.hexeditor
ms-python.vscode-unpkg.net/ms-python/vscode-pylance/2022.7.40/extension/package.nls.en-us.json:1          Failed to load resource: the server responded with a status of 404 ()
log.ts:313   ERR [Extension Host] Error: 'importScripts' has been blocked
    at self.importScripts (../../../vs/workbench/api/worker/extensionHostWorker.js:78:2120)
    at Object.et.f.i (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35030)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:33748)
    at Array.reduce (<anonymous>)
    at Function.et.e (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:33726)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:50373)
    at Generator.next (<anonymous>)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35895)
    at new Promise (<anonymous>)
    at d (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35715)
    at dy (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:50319)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:51158)
    at Generator.next (<anonymous>)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35895)
    at new Promise (<anonymous>)
    at d (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35715)
    at fy (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:51120)
    at hy.a [as _clientFactory] (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:8663)
    at hy.instantiateAppender (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:905)
    at gy.updateUserOptStatus (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:2673)
    at new py (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:2128)
    at new gy (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:8758)
    at JR (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1306:4624)
    at f._activate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8181)
    at f._waitForDepsThenActivate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8123)
    at f._initialize (../../../vs/workbench/api/worker/extensionHostWorker.js:69:7487)
console.ts:137 [Extension Host] Error: 'importScripts' has been blocked
    at self.importScripts (../../../vs/workbench/api/worker/extensionHostWorker.js:78:2120)
    at Object.et.f.i (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35030)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:33748)
    at Array.reduce (<anonymous>)
    at Function.et.e (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:33726)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:50373)
    at Generator.next (<anonymous>)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35895)
    at new Promise (<anonymous>)
    at d (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35715)
    at dy (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:50319)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:51158)
    at Generator.next (<anonymous>)
    at eval (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35895)
    at new Promise (<anonymous>)
    at d (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1124:35715)
    at fy (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1131:51120)
    at hy.a [as _clientFactory] (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:8663)
    at hy.instantiateAppender (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:905)
    at gy.updateUserOptStatus (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:2673)
    at new py (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:2128)
    at new gy (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1133:8758)
    at JR (https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.47.2022072711/extension/dist/browser/extension.js#vscode-extension:1306:4624)
    at f._activate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8181)
    at f._waitForDepsThenActivate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8123)
    at f._initialize (../../../vs/workbench/api/worker/extensionHostWorker.js:69:7487)
y @ console.ts:137
log.ts:301  INFO Installing extension: github.vscode-pull-request-github
log.ts:301  INFO Installing extension: github.remotehub
log.ts:301  INFO Installing extension: github.codespaces
log.ts:301  INFO Installing extension: ms-toolsai.jupyter
log.ts:301  INFO Installing extension: eamodio.gitlens-insiders
log.ts:301  INFO Installing extension: ms-vscode.remote-repositories
log.ts:301  INFO Installing extension: ms-vscode.hexeditor
log.ts:301  INFO Installing extension: ms-vscode.azure-repos
log.ts:301  INFO Migrating workspace extension storage from pkief.material-icon-theme to PKief.material-icon-theme...
log.ts:301  INFO Migrated workspace extension storage from pkief.material-icon-theme to PKief.material-icon-theme
console.ts:137 [Extension Host] highlight-bad-chars decorator is activated with configuration Object
console.ts:137 [Extension Host] TypeError: i.TextEncoder is not a constructor
    at eval (https://zhuangtongfa.vscode-unpkg.net/zhuangtongfa/Material-theme/3.15.2/extension/out/web/extension.js#vscode-extension:3:19448)
    at Generator.throw (<anonymous>)
    at u (https://zhuangtongfa.vscode-unpkg.net/zhuangtongfa/Material-theme/3.15.2/extension/out/web/extension.js#vscode-extension:3:18942)
sw.js:1 SW Done garbage collecting
log.ts:313   ERR Cannot read properties of undefined (reading 'dispose'): TypeError: Cannot read properties of undefined (reading 'dispose')
    at M.onDidRemoveViewDescriptors (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:2994:45852)
    at https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:2994:41154
    at S.invoke (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:79:145)
    at r.deliver (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:79:2266)
    at c.fire (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:79:1844)
    at h.broadCastRemovedVisibleViewDescriptors (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:2723:41810)
    at h.updateVisibility (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:2723:36590)
    at https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:2723:34317
    at S.invoke (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:79:145)
    at r.deliver (https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/out/vs/workbench/workbench.web.main.js:79:2266)
sw.js:1 SW Done caching workbench
log.ts:301  INFO Extension installed successfully: github.vscode-pull-request-github
log.ts:301  INFO Extension installed successfully: github.remotehub
log.ts:301  INFO Extension installed successfully: github.codespaces
log.ts:301  INFO Extension installed successfully: eamodio.gitlens-insiders
log.ts:301  INFO Extension installed successfully: ms-vscode.remote-repositories
log.ts:301  INFO Extension installed successfully: ms-vscode.azure-repos
log.ts:301  INFO Extension installed successfully: ms-toolsai.jupyter
log.ts:301  INFO Extension installed successfully: ms-vscode.hexeditor
DevTools failed to load source map: Could not load content for https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/node_modules/vscode-textmate/release/main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/node_modules/@microsoft/applicationinsights-core-js/browser/applicationinsights-core-js.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/node_modules/@microsoft/1ds-post-js/dist/ms.post.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/node_modules/@microsoft/dynamicproto-js/lib/dist/umd/dynamicproto-js.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/node_modules/@microsoft/1ds-core-js/dist/ms.core.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://main.vscode-cdn.net/insider/b4d5b4ed69af953901051b1f049851b9dca3563e/node_modules/tas-client-umd/lib/tas-client-umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/core/vs/workbench/services/keybinding/browser/keyboardLayouts/layout.contribution.darwin.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ms-python.vscode-unpkg.net/ms-python/python/2022.10.1/extension/dist/extension.browser.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/microsoft-authentication/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/git-base/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/npm/dist/browser/npmBrowserMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/ipynb/dist/browser/ipynbMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/json-language-features/client/dist/browser/jsonClientMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/configuration-editing/dist/browser/configurationEditingMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/github-authentication/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/typescript-language-features/dist/browser/extension.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/merge-conflict/dist/browser/mergeConflictMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/emmet/dist/browser/emmetBrowserMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/b4d5b4ed69af953901051b1f049851b9dca3563e/extensions/json-language-features/server/dist/browser/jsonServerMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by misolori** [comment]
Tried this on another repo that wasn't mine and that worked. but what I noticed about [this repo](https://github.com/misolori/notebooks) that this issue references is there are pending changes that need to be pushed, not sure if this affects the URL that gets loaded:

<img width="248" alt="CleanShot 2022-07-28 at 13 19 49@2x" src="https://user-images.githubusercontent.com/35271042/181630062-65b8f6d3-8bfb-49d1-8cb5-1568ef9486ce.png">

**Comment by alexr00** [comment]
Somehow we got a commit that doesn't exist in your repo: 51e863f1f4fd0e350507e26a92fa832a0abe9657.
