### ISSUE TITLE
Issue working with company proxy on 1.69.2, [error] XHR failed

### ISSUE THREAD

**Issue by ryblogs** [microsoft/vscode#156625]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: macOS 12.5 (Monterey)

Steps to Reproduce:

1. Launch VS Code while connected to company's VPN
2. Open Extensions sidebar
3. Click on an extension that hasn't been installed, and the extension browser fails to load (XHR failed)

Issue does not occur on 1.68.1 or earlier versions.
Issue does not occur on 1.69.2 on a Windows machine on the same network.

Log (Window) output:

```
[2022-07-29 09:02:00.926] [renderer1] [error] RequestService#request (browser) - error https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2022.6.1201981810/1657905744422/Microsoft.VisualStudio.Code.Manifest {}
[2022-07-29 09:02:01.012] [renderer1] [error] RequestService#request (browser) - error https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter/2022.6.1201981810/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
[2022-07-29 09:02:01.013] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.m.onerror (vscode-file://vscode-app/private/var/folders/cf/524q4p595v32z4f5typgmj000000gr/T/AppTranslocation/5183C4E5-F6C1-45F3-96D8-BFD65B517714/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:9062)
[2022-07-29 09:02:06.005] [renderer1] [error] RequestService#request (browser) - error https://eamodio.gallerycdn.vsassets.io/extensions/eamodio/gitlens/12.1.2/1657684924460/Microsoft.VisualStudio.Code.Manifest {}
[2022-07-29 09:02:06.115] [renderer1] [error] RequestService#request (browser) - error https://eamodio.gallery.vsassets.io/_apis/public/gallery/publisher/eamodio/extension/gitlens/12.1.2/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
[2022-07-29 09:02:06.115] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.m.onerror (vscode-file://vscode-app/private/var/folders/cf/524q4p595v32z4f5typgmj000000gr/T/AppTranslocation/5183C4E5-F6C1-45F3-96D8-BFD65B517714/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:9062)
```

**Comment by ryblogs** [comment]
Apparently my workplace needed to change their network backend to allow for the user_agent string changes from 1.69.2 and above. This issue was isolated to my workplace, closing out.
