### ISSUE TITLE
Linux: Smoke test failure from native crash

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#156996]
(failed while building https://github.com/microsoft/vscode/pull/156994). 

See https://dev.azure.com/vscode/VSCode/_build/results?buildId=70208&view=logs&j=15f6beb8-c39c-5fa4-f1fe-6e73c89d1002&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=96ed0de4-fc9b-50ae-c3cf-4e9e83914ed9&l=78

```
  27 passing (3m)
  11 pending
  1 failing

  1) VSCode Smoke Tests (Electron)
       Multiroot
         "before all" hook for "shows results from all folders":
     electronApplication.firstWindow: Electron application closed
      at launchElectron (/mnt/vss/_work/1/s/test/automation/src/playwrightElectron.ts:38:46)
      at launch (/mnt/vss/_work/1/s/test/automation/src/playwrightElectron.ts:20:38)
      at measureAndLog (/mnt/vss/_work/1/s/test/automation/src/logger.ts:52:9)
      at launch (/mnt/vss/_work/1/s/test/automation/src/code.ts:91:39)
      at Application.startApplication (/mnt/vss/_work/1/s/test/automation/src/application.ts:107:29)
      at Application._start (/mnt/vss/_work/1/s/test/automation/src/application.ts:82:16)
      at Application.start (/mnt/vss/_work/1/s/test/automation/src/application.ts:67:3)
      at Context.<anonymous> (src/utils.ts:110:3)
```

**Comment by bpasero** [comment]
There seems to be a native crash, maybe @deepak1556 could symbolify:

[crash.zip](https://github.com/microsoft/vscode/files/9250966/crash.zip)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/153181
