### ISSUE TITLE
Terminal profiles smoke tests failure

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156961]
```
Terminal
2022-08-02T15:55:57.6710399Z          Terminal Profiles
2022-08-02T15:55:57.6711207Z            should set the default profile to a contributed one:
2022-08-02T15:55:57.6712391Z [0m[31m     Error: Timeout: get element '.quick-input-widget' after 20 seconds.[0m[90m
2022-08-02T15:55:57.6713202Z       at Code.poll (/mnt/vss/_work/1/s/test/automation/src/code.ts:256:11)
2022-08-02T15:55:57.6714065Z       at Code.waitForElement (/mnt/vss/_work/1/s/test/automation/src/code.ts:209:10)
2022-08-02T15:55:57.6714824Z       at QuickInput.waitForQuickInputClosed (/mnt/vss/_work/1/s/test/automation/src/quickinput.ts:45:3)
2022-08-02T15:55:57.6715898Z       at Terminal.runCommandWithValue (/mnt/vss/_work/1/s/test/automation/src/terminal.ts:123:3)
2022-08-02T15:55:57.6717086Z       at Context.<anonymous> (src/areas/terminal/terminal-profiles.test.ts:35:4)
2022-08-02T15:55:57.6718142Z [0m
2022-08-02T15:55:57.6718891Z [0m  2) VSCode Smoke Tests (Web)
2022-08-02T15:55:57.6719480Z        Terminal
2022-08-02T15:55:57.6719999Z          Terminal Profiles
2022-08-02T15:55:57.6720661Z            should use the default contributed profile on panel open and for splitting:
2022-08-02T15:55:57.6721943Z [0m[31m     Error: Timeout: get element '.quick-input-widget' after 20 seconds.[0m[90m
2022-08-02T15:55:57.6722788Z       at Code.poll (/mnt/vss/_work/1/s/test/automation/src/code.ts:256:11)
2022-08-02T15:55:57.6723562Z       at Code.waitForElement (/mnt/vss/_work/1/s/test/automation/src/code.ts:209:10)
2022-08-02T15:55:57.6724489Z       at QuickInput.waitForQuickInputClosed (/mnt/vss/_work/1/s/test/automation/src/quickinput.ts:45:3)
2022-08-02T15:55:57.6725402Z       at Terminal.runCommandWithValue (/mnt/vss/_work/1/s/test/automation/src/terminal.ts:123:3)
2022-08-02T15:55:57.6726593Z       at Context.<anonymous> (src/areas/terminal/terminal-profiles.test.ts:41:4)
2022-08-02T15:55:57.6727436Z [0m
2022-08-02T15:55:57.6728190Z [0m  3) VSCode Smoke Tests (Web)
2022-08-02T15:55:57.6728754Z        Terminal
2022-08-02T15:55:57.6729282Z          Terminal Profiles
2022-08-02T15:55:57.6729957Z            createWithProfile command should create a terminal with a contributed profile:
2022-08-02T15:55:57.6730999Z [0m[31m     Error: Timeout: get element '.quick-input-widget' after 20 seconds.[0m[90m
2022-08-02T15:55:57.6731797Z       at Code.poll (/mnt/vss/_work/1/s/test/automation/src/code.ts:256:11)
2022-08-02T15:55:57.6732575Z       at Code.waitForElement (/mnt/vss/_work/1/s/test/automation/src/code.ts:209:10)
2022-08-02T15:55:57.6733427Z       at QuickInput.waitForQuickInputClosed (/mnt/vss/_work/1/s/test/automation/src/quickinput.ts:45:3)
2022-08-02T15:55:57.6734321Z       at Terminal.runCommandWithValue (/mnt/vss/_work/1/s/test/automation/src/terminal.ts:123:3)
2022-08-02T15:55:57.6735474Z       at Context.<anonymous> (src/areas/terminal/terminal-profiles.test.ts:66:4)
2022-08-02T15:55:57.6736301Z [0m
2022-08-02T15:55:57.6737042Z [0m  4) VSCode Smoke Tests (Web)
2022-08-02T15:55:57.6737634Z        Terminal
2022-08-02T15:55:57.6738180Z          Terminal Profiles
2022-08-02T15:55:57.6738865Z            createWithProfile command should create a split terminal with a contributed profile:
2022-08-02T15:55:57.6739971Z [0m[31m     Error: Timeout: get element '.quick-input-widget' after 20 seconds.[0m[90m
2022-08-02T15:55:57.6740772Z       at Code.poll (/mnt/vss/_work/1/s/test/automation/src/code.ts:256:11)
2022-08-02T15:55:57.6741518Z       at Code.waitForElement (/mnt/vss/_work/1/s/test/automation/src/code.ts:209:10)
2022-08-02T15:55:57.6742338Z       at QuickInput.waitForQuickInputClosed (/mnt/vss/_work/1/s/test/automation/src/quickinput.ts:45:3)
2022-08-02T15:55:57.6743211Z       at Terminal.runCommandWithValue (/mnt/vss/_work/1/s/test/automation/src/terminal.ts:123:3)
2022-08-02T15:55:57.6744349Z       at Context.<anonymous> (src/areas/terminal/terminal-profiles.test.ts:79:4)
```

https://dev.azure.com/vscode/VSCode/_build/results?buildId=70006&view=logs&j=574ac27d-2fea-586d-e37c-945189154073&t=a338d4eb-96a0-5819-3b4b-8756b1eb86fc&l=190

**Comment by Tyriar** [comment]
Was skipped in https://github.com/microsoft/vscode/pull/156906
