### ISSUE TITLE
Notebook ERR_ASSERTION

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#157067]
Output in `scripts/test-integration.sh`:

```
should be set to Executing: AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: should be set to Executing
    at /Users/bpasero/Development/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:310:12
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at ExtHostNotebookKernels.$cellExecutionChanged (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/common/extHostNotebookKernels.ts:351:40)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:455:17)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:440:32)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:370:19)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:296:10)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:644:19)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/node/extensionHostProcess.ts:251:22
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:644:19)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:975:23)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:848:73
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:388:21)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:344:51
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/node/ipc.net.ts:70:4)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
should be set to Idle: AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: should be set to Idle
    at /Users/bpasero/Development/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:313:12
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at ExtHostNotebookKernels.$cellExecutionChanged (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/common/extHostNotebookKernels.ts:351:40)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:455:17)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:440:32)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:370:19)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:296:10)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:644:19)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/node/extensionHostProcess.ts:251:22
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:644:19)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:975:23)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:848:73
    at Listener.invoke (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:622:17)
    at PrivateEventDeliveryQueue.deliver (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:824:22)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/event.ts:785:24)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:388:21)
    at file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/common/ipc.net.ts:344:51
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/base/parts/ipc/node/ipc.net.ts:70:4)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by bpasero** [comment]
Probably not related, but a bit above:

```
Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/common/extHostNotebookKernels.ts:215:12)
    at Kernel._runCell (/Users/bpasero/Development/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:67:32)
    at Kernel._execute (/Users/bpasero/Development/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:60:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExtHostNotebookKernels.$executeCells (file:///Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/api/common/extHostNotebookKernels.ts:305:4)
```
