### ISSUE TITLE
Unable to resolve resource vscode-vfs://github/MaheshtheDev/DataScience_Bot

### ISSUE THREAD

**Issue by MaheshtheDev** [microsoft/vscode#157109]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: web browser Chrome in MacOS

Steps to Reproduce:

1. I am trying to open vscode.dev for an repository. So i clicked `.` on my public repository Data Science Bot. And i got this error
`Unable to resolve resource vscode-vfs://github/MaheshtheDev/DataScience_Bot`. I am not able to open any repository, not even other people repo's.
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/38828053/182901536-5330b3d3-b6d6-4ec5-acb8-95daddd20472.png">

**Comment by joyceerhl** [comment]
@MaheshtheDev If you search for @builtin in the extensions view, do you see `GitHub Repositories` there? Can you also share the contents of the developer tools log? Thank you!

**Comment by MaheshtheDev** [comment]
I don't know how but it's resolved now. Anyways, Thanks @joyceerhl

**Comment by Koziah-Sylvester** [comment]
I'm actually experiencing a similar problem. I do not see GitHub Repositories in the builtin extensions. When I go to install it I get an error saying that it cannot be installed.

**Comment by joyceerhl** [comment]
@Koziah-Sylvester could you please share your list of installed extensions and the contents of the "Log (Worker Extension Host)" output channel?

**Comment by Koziah-Sylvester** [comment]
Good morning. It seems like when I go to install any extension it simply gives a vague error. 
`
Error while installing 'GitHub Repositories' extension.
`
This means I am unable to install any extensions at all.

Also, I have found I was able to create and edit a file but I am not able to move, save or push to any of my repos on github. Without extensions it's basically a text editor

I did a bit of looking and I might have found it but I am not 100% sure this is what you would have wanted.

`
[2022-08-30 09:06:44.155] [exthost] [info] Extension host started
[2022-08-30 09:06:44.185] [exthost] [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
[2022-08-30 09:06:44.220] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-08-30 09:06:44.261] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*'
[2022-08-30 09:06:44.273] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-08-30 09:06:44.285] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
[2022-08-30 09:06:44.292] [exthost] [info] Eager extensions activated
[2022-08-30 09:06:44.301] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-08-30 09:06:44.326] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-08-30 09:06:44.330] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-08-30 09:06:44.936] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-08-30 09:06:44.951] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-08-30 09:06:44.962] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'

`

I am looking for ways to be able to use online IDEs.  I have used VScode in the past and am looking for an online replacement.

![image](https://user-images.githubusercontent.com/112087322/187386138-3d792afc-d8a6-4131-8be2-dd43581daff1.png)

**Comment by joyceerhl** [comment]
@Koziah-Sylvester Are you using github.dev, vscode.dev, or something else? Could you share your list of installed extensions? If you open the Log (Window) output channel, do you see any useful information there?

**Comment by Koziah-Sylvester** [comment]
I am using github.dev.

I am not able to install any extensions. This also means I do not have any extensions installed. 

This is the Log (Window). All the errors and warnings seem to start to come from a missing "package.json". I have no idea what it is referring to or how to fix it.
```
[2022-09-01 09:07:12.615] [window] [warning] Ignoring the error while validating workspace folder vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev - No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev'
[2022-09-01 09:07:15.011] [window] [error] ENOPRO: No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev'
    at h.withProvider (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:12467)
    at async h.doWatch (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:26229)
    at async https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:26095
[2022-09-01 09:07:17.481] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.492] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.498] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.502] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.506] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.514] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.518] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.526] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.530] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.534] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.539] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.541] [window] [info] Ignoring additional builtin extension github.vscode-pull-request-github because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.48.1/extension'. Failed to fetch
[2022-09-01 09:07:17.545] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.554] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.558] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.565] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.569] [window] [info] Ignoring additional builtin extension ms-vscode.anycode because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode/0.0.69/extension'. Failed to fetch
[2022-09-01 09:07:17.572] [window] [info] Ignoring additional builtin extension github.github-vscode-theme because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/github-vscode-theme/6.3.2/extension'. Failed to fetch
[2022-09-01 09:07:17.580] [window] [info] Ignoring additional builtin extension github.codespaces because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/codespaces/1.10.4/extension'. Failed to fetch
[2022-09-01 09:07:17.584] [window] [info] Ignoring additional builtin extension ms-vscode.remote-repositories because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
[2022-09-01 09:07:17.589] [window] [info] Ignoring additional builtin extension github.remotehub because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/remotehub/0.40.0/extension'. Failed to fetch
[2022-09-01 09:07:17.594] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-kotlin because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-kotlin/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.598] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-cpp because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-cpp/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.604] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-java because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-java/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.610] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-python because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-python/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.613] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-php because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-php/0.0.6/extension'. Failed to fetch
[2022-09-01 09:07:17.619] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-rust because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-rust/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.624] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-go because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-go/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.629] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-c-sharp because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-c-sharp/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.638] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-typescript because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-typescript/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:23.254] [window] [error] Error while registering log channel file:///20220901T090712/ptyhost.log Timed out while waiting for file to be created
[2022-09-01 09:09:51.679] [window] [info] Getting Manifest... github.remotehub
[2022-09-01 09:09:51.685] [window] [info] Installing extension: github.remotehub
[2022-09-01 09:09:52.149] [window] [info] Getting Manifest... ms-vscode.remote-repositories
[2022-09-01 09:09:52.665] [window] [info] Installing extension: ms-vscode.remote-repositories
[2022-09-01 09:09:52.755] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:09:52.864] [window] [error] Error while installing the extension: ms-vscode.remote-repositories
[2022-09-01 09:09:52.868] [window] [error] Failed to install extension. github.remotehub
[2022-09-01 09:09:52.872] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:52.876] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:52.880] [window] [error] Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:56.836] [window] [info] Getting Manifest... github.remotehub
[2022-09-01 09:09:57.308] [window] [info] Installing extension: github.remotehub
[2022-09-01 09:09:57.946] [window] [info] Getting Manifest... ms-vscode.remote-repositories
[2022-09-01 09:09:58.407] [window] [info] Installing extension: ms-vscode.remote-repositories
[2022-09-01 09:09:58.465] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:09:58.592] [window] [error] Error while installing the extension: ms-vscode.remote-repositories
[2022-09-01 09:09:58.632] [window] [error] Failed to install extension. github.remotehub
[2022-09-01 09:09:58.652] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:58.656] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:58.661] [window] [error] Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:10:01.641] [window] [info] Getting Manifest... github.remotehub
[2022-09-01 09:10:01.646] [window] [info] Installing extension: github.remotehub
[2022-09-01 09:10:02.240] [window] [info] Getting Manifest... ms-vscode.remote-repositories
[2022-09-01 09:10:02.248] [window] [info] Installing extension: ms-vscode.remote-repositories
[2022-09-01 09:10:02.318] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:10:02.452] [window] [error] Error while installing the extension: ms-vscode.remote-repositories
[2022-09-01 09:10:02.456] [window] [error] Failed to install extension. github.remotehub
[2022-09-01 09:10:02.459] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:10:02.463] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:10:02.469] [window] [error] Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:21:28.283] [window] [error] No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev/.vscode': ENOPRO: No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev/.vscode'
    at h.withProvider (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:12467)
    at async h.exists (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:15062)
    at async https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:2322:7642
    at async Promise.all (index 0)
    at async D._initWorkspaceFolderSnippets (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:2322:7807)

```
