### ISSUE TITLE
Unable to install extensions on remote host

### ISSUE THREAD

**Issue by lotsofone** [microsoft/vscode#157612]
Type: <b>Bug</b>

Steps to Reproduce:
- 1 ssh to some remote server (my server is on Tencent cloud)
- 2 go to extensions and try to install any extension. For example, I searched for cmake and clicked "Install", and then the button changed to "Installing", and then the "Installing" stayed forever. I also tried to install React Native Tools, the button was "Install in SSH: x.x.x.x", but it's not clickable.
I also tried to reinstall the OS on my cloud server and still could not install extensions.

Log (Shared):
```
[2022-08-09 16:07:19.648] [sharedprocess] [info] Starting worker process with pid 17832 (type: fileWatcher, window: 1).
[2022-08-09 16:07:20.117] [sharedprocess] [info] WSL is not installed, so could not detect WSL profiles
[2022-08-09 16:07:27.699] [sharedprocess] [info] Starting worker process with pid 3336 (type: fileWatcher, window: 3).
```
Log (Window):
```
[2022-08-09 16:07:27.559] [renderer3] [info] [attempt 1] Invoking resolveAuthority(ssh-remote)
[2022-08-09 16:07:29.227] [renderer3] [error] [Extension Host] (node:9944) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-08-09 16:07:29.235] [renderer3] [info] [attempt 1] resolveAuthority(ssh-remote) returned '127.0.0.1:61309' after 1675 ms
[2022-08-09 16:07:30.021] [renderer3] [error] [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
```
Log (Remote Server):
```
[2022-08-09 15:44:38.639] [remoteagent] [info] Extension host agent started.
[2022-08-09 15:44:38.853] [remoteagent] [info] [127.0.0.1][149d3ab5][ManagementConnection] New connection established.
[2022-08-09 15:44:38.925] [remoteagent] [info] [127.0.0.1][35e7c2a0][ExtensionHostConnection] New connection established.
[2022-08-09 15:44:38.932] [remoteagent] [info] [127.0.0.1][35e7c2a0][ExtensionHostConnection] <3747> Launched Extension Host Process.
[2022-08-09 15:44:59.764] [remoteagent] [info] Getting Manifest... golang.go
[2022-08-09 15:45:00.384] [remoteagent] [info] Installing extension: golang.go
[2022-08-09 15:45:00.478] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 15:45:00.676] [remoteagent] [info] Installing extension: msjsdiag.vscode-react-native
[2022-08-09 15:48:35.142] [remoteagent] [info] [127.0.0.1][35e7c2a0][ExtensionHostConnection] <3747> Extension Host Process exited with code: 0, signal: null.
[2022-08-09 15:48:35.142] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-08-09 15:49:29.683] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-08-09 15:49:29.683] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-08-09 15:49:29.900] [remoteagent] [info] [127.0.0.1][f2087f84][ManagementConnection] New connection established.
[2022-08-09 15:49:30.084] [remoteagent] [info] [127.0.0.1][ae6c7bfe][ExtensionHostConnection] New connection established.
[2022-08-09 15:49:30.105] [remoteagent] [info] [127.0.0.1][ae6c7bfe][ExtensionHostConnection] <5112> Launched Extension Host Process.
[2022-08-09 15:49:30.781] [remoteagent] [info] [127.0.0.1][149d3ab5][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-08-09 15:49:30.783] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/lighthouse/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/out/vs/server/node/server.main.js:145:7922)
    at process.emit (node:events:390:28)
[2022-08-09 15:50:33.624] [remoteagent] [info] Downloaded extension: golang.go /home/lighthouse/.vscode-server/data/CachedExtensionVSIXs/golang.go-0.35.1
[2022-08-09 15:50:33.734] [remoteagent] [info] Extracted extension to /home/lighthouse/.vscode-server/extensions/.afb79b0a-bf79-4fdf-89e5-553550b13caf: golang.go
[2022-08-09 15:50:33.745] [remoteagent] [info] Renamed to /home/lighthouse/.vscode-server/extensions/golang.go-0.35.1
[2022-08-09 15:50:33.748] [remoteagent] [info] Extracting completed. golang.go
[2022-08-09 15:50:33.750] [remoteagent] [info] Extension installed successfully: golang.go
[2022-08-09 15:54:29.683] [remoteagent] [info] New EH opened, aborting shutdown
[2022-08-09 15:55:06.968] [remoteagent] [info] Getting Manifest... golang.go
[2022-08-09 15:55:07.180] [remoteagent] [info] Installing extension: golang.go
[2022-08-09 15:55:07.409] [remoteagent] [info] Extension installed successfully: golang.go
[2022-08-09 15:55:15.004] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 15:55:15.031] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 15:56:10.750] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 15:56:10.927] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 15:58:11.897] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 15:58:12.057] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 15:59:00.709] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 15:59:00.841] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 15:59:38.247] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 15:59:38.425] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 15:59:39.438] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 15:59:39.493] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:00:41.548] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:00:41.548] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:00:41.548] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:00:41.548] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:00:41.548] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:00:41.548] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:00:41.609] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:00:41.612] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:00:41.615] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:00:41.617] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:00:41.618] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:00:41.620] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:03:16.172] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:03:16.286] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:03:16.307] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:03:16.336] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:03:16.432] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:03:16.459] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:06:57.430] [remoteagent] [info] [127.0.0.1][ae6c7bfe][ExtensionHostConnection] <5112> Extension Host Process exited with code: 0, signal: null.
[2022-08-09 16:06:57.431] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-08-09 16:07:29.094] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-08-09 16:07:29.094] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-08-09 16:07:29.307] [remoteagent] [info] [127.0.0.1][149d3ab5][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2022-08-09 16:07:29.308] [remoteagent] [info] [127.0.0.1][75dd1e72][ManagementConnection] New connection established.
[2022-08-09 16:07:29.395] [remoteagent] [info] [127.0.0.1][95c44b0e][ExtensionHostConnection] New connection established.
[2022-08-09 16:07:29.403] [remoteagent] [info] [127.0.0.1][95c44b0e][ExtensionHostConnection] <9077> Launched Extension Host Process.
[2022-08-09 16:07:29.806] [remoteagent] [info] [127.0.0.1][f2087f84][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-08-09 16:07:29.807] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/lighthouse/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/out/vs/server/node/server.main.js:145:7922)
    at process.emit (node:events:390:28)
[2022-08-09 16:08:30.813] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:08:30.840] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:08:45.550] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:08:45.634] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:08:46.076] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:08:46.095] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:08:46.221] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:08:46.243] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:08:49.891] [remoteagent] [info] Getting Manifest... msjsdiag.vscode-react-native
[2022-08-09 16:08:49.937] [remoteagent] [info] Extensions is already requested to install msjsdiag.vscode-react-native
[2022-08-09 16:12:18.428] [remoteagent] [info] Getting Manifest... ms-vscode.cmake-tools
[2022-08-09 16:12:29.094] [remoteagent] [info] New EH opened, aborting shutdown
[2022-08-09 16:12:29.507] [remoteagent] [info] [127.0.0.1][149d3ab5][ManagementConnection] The reconnection short grace time of 5m has expired, so the connection will be disposed.
[2022-08-09 16:13:16.061] [remoteagent] [info] Installing extension: ms-vscode.cmake-tools
[2022-08-09 16:13:24.397] [remoteagent] [info] Getting Manifest... twxs.cmake
[2022-08-09 16:13:26.964] [remoteagent] [info] Installing extension: twxs.cmake
```

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Remote OS version: Linux x64 4.18.0-348.7.1.el8_5.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9350KF CPU @ 4.00GHz (4 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.45GB free)|
|Process Argv|--crash-reporter-id 7656db13-88d1-4dc0-ab85-548188d9ff0d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 43.142.194.45|
|OS|Linux x64 4.18.0-348.7.1.el8_5.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz (2 x 2494)|
|Memory (System)|1.68GB (0.49GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
JavaScriptSnippets|xab|1.8.0
go|gol|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by lotsofone** [comment]
I set "remote.SSH.localServerDownload" to "always" and "remote.downloadExtensionsLocally" to true, and successfully installed extensions on remote server.
But it is still a problem. I didn't find error logs like "dial https://marketplace.visualstudio.com/xxx time out", it's difficult to troubleshoot.

**Comment by sandy081** [comment]
I suspect there are some network issues on your remote machine and you can figure this by enabling log level to trace using command `F1 > Set Log Level` and retry the action.

Setting `remote.downloadExtensionsLocally` to true allows VS Code to download the extension locally and install it on the remote.
