### ISSUE TITLE
Markdown preview is not showing up

### ISSUE THREAD

**Issue by jgc128** [microsoft/vscode#157795]
The "Open preview on the side" button opens the preview tab on the right but it's completely blank.

Not sure if it's related or not, but the extensions details in the extension store also do not show up. There's just a blank "details" tab. The "changelog" tab is also empty, while all other tabs work correctly. 

I'm using VS Code Server running on Windows as "code-server serve-local --host 0.0.0.0"

Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1336.2
Embedder: server-distro

**Comment by mjbvz** [comment]
If you run Developer: Toggle developer tools, you see any errors in the developer console?

**Comment by jgc128** [comment]
I don't have this option in the command list:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/669142/184058000-2c6043b8-ec0d-48e0-bdb7-12a73e1e5bb5.png">

This is my VS Code Server version - it just updated itself but the preview still does not work:

Version: 1.70.1
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T05:53:19.491Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1336.2

**Comment by mjbvz** [comment]
Oh since you're on web, just use the normal browser developer tools to check

**Comment by jgc128** [comment]
Ah okay :D 

Yeah, there's an error popping out immediately as I click the "preview" button:

> ERR Can't compute sha-256: Error: Can't compute sha-256
    at t (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:808:93423)
    at new M (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:1359:8386)
    at p._createInstance (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:596:1346)
    at p.createInstance (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:596:779)
    at I.createWebviewElement (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:1359:22081)
    at w.show (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:1300:40254)
    at w.claim (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:1300:38401)
    at Ua.claimWebview (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:1754:3064)
    at Ua.setInput (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:1754:2975)
    at async a.doSetInput (http://10.161.108.103:8000/stable-6d9b74a70ca9c7733b29f0456fd8195364076dda/static/out/vs/workbench/workbench.web.main.js:2736:6428)

The same error appears when I open an extension page in the store

**Comment by simonneutert** [comment]
in my case I had the wrong `language mode` selected 😮‍💨 

`crtl + shift + P` and `change language mode` I then selected Markdown for `.md` files and all was good! maybe it helps you, too :v:

**Comment by jgc128** [comment]
I checked and it is set to markdown 😞 Still getting the same error 😞
