### ISSUE TITLE
Can't connect to remote server in MacOS but can with Windows

### ISSUE THREAD

**Issue by jinzcdev** [microsoft/vscode#157856]
Type: <b>Bug</b>

I found that when I use remote-ssh to connect to the server, I can connect successfully in Windows, but it fails in MacOS.

I got the following error message: `Failed to parse remote port from server output`.

```shell

[10:41:46.056] Log Level: 2
[10:41:46.057] remote-ssh@0.84.0
[10:41:46.057] darwin x64
[10:41:46.063] SSH Resolver called for "ssh-remote+zjut.48.pmf", attempt 1
[10:41:46.064] "remote.SSH.useLocalServer": true
[10:41:46.064] "remote.SSH.path": undefined
[10:41:46.065] "remote.SSH.configFile": undefined
[10:41:46.065] "remote.SSH.useFlock": true
[10:41:46.065] "remote.SSH.lockfilesInTmp": false
[10:41:46.066] "remote.SSH.localServerDownload": auto
[10:41:46.066] "remote.SSH.remoteServerListenOnSocket": false
[10:41:46.066] "remote.SSH.showLoginTerminal": false
[10:41:46.067] "remote.SSH.defaultExtensions": []
[10:41:46.067] "remote.SSH.loglevel": 2
[10:41:46.067] "remote.SSH.enableDynamicForwarding": true
[10:41:46.068] "remote.SSH.enableRemoteCommand": false
[10:41:46.068] "remote.SSH.serverPickPortsFromRange": {}
[10:41:46.068] "remote.SSH.serverInstallPath": {}
[10:41:46.081] SSH Resolver called for host: zjut.48.pmf
[10:41:46.081] Setting up SSH remote "zjut.48.pmf"
[10:41:46.084] Acquiring local install lock: /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-remote-ssh-f46263c7-install.lock
[10:41:46.085] Looking for existing server data file at /Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json
[10:41:46.086] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[10:41:46.089] Install and start server if needed
[10:41:46.092] PATH: /Users/jinzcdev/opt/anaconda3/envs/pytorch/bin:/Users/jinzcdev/opt/anaconda3/condabin:/usr/local/opt/m4/bin:/usr/local/opt/node@12/bin:/usr/local/opt/openjdk@11/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Library/Apple/usr/bin:/usr/local/opt/gradle/bin
[10:41:46.093] Checking ssh with "ssh -V"
[10:41:46.100] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:41:46.104] askpass server listening on /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-b4be6e1b116ed865cc50581c44e99445de4b4a9c.sock
[10:41:46.104] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-cef4f51b23424c8fcdab0edf5e40a38aba5d9b5f.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","58877","-o","ConnectTimeout=15","zjut.48.pmf"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json"}
[10:41:46.104] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.5XV07TUAB5/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-b4be6e1b116ed865cc50581c44e99445de4b4a9c.sock"}
[10:41:46.106] Spawned 33353
[10:41:46.345] > local-server-1> Spawned ssh, pid=33378
[10:41:46.349] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:41:46.409] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
[10:41:46.463] stderr> Authenticated to 10.12.41.48 ([10.12.41.48]:22).
[10:41:46.548] stderr> Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
[10:41:46.548] stderr> Bytes per second: sent 37070.6, received 35117.0
[10:41:46.549] > local-server-1> ssh child died, shutting down
[10:41:46.553] Local server exit: 0
[10:41:46.553] Received install output: local-server-1> Spawned ssh, pid=33378
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
Authenticated to 10.12.41.48 ([10.12.41.48]:22).
Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
Bytes per second: sent 37070.6, received 35117.0
local-server-1> ssh child died, shutting down

[10:41:46.554] Failed to parse remote port from server output
[10:41:46.555] Resolver error: Error: 
	at Function.Create (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[10:41:46.559] ------




[10:41:46.618] ------




[10:41:46.618] SSH Resolver called for "ssh-remote+zjut.48.pmf", attempt 2, (Reconnection)
[10:41:46.619] SSH Resolver called for host: zjut.48.pmf
[10:41:46.619] Setting up SSH remote "zjut.48.pmf"
[10:41:46.620] Acquiring local install lock: /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-remote-ssh-f46263c7-install.lock
[10:41:46.620] Looking for existing server data file at /Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json
[10:41:46.621] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[10:41:46.622] Install and start server if needed
[10:41:46.625] askpass server listening on /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-c2dafb8ce27f4369bfb6a149bdda8e14354ed721.sock
[10:41:46.625] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-3b55f089ed274ee288caf99893e3a34a1c520493.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","58883","-o","ConnectTimeout=15","zjut.48.pmf"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json"}
[10:41:46.625] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.5XV07TUAB5/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-c2dafb8ce27f4369bfb6a149bdda8e14354ed721.sock"}
[10:41:46.626] Spawned 33412
[10:41:46.730] > local-server-2> Spawned ssh, pid=33441
[10:41:46.733] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:41:46.785] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
[10:41:46.840] stderr> Authenticated to 10.12.41.48 ([10.12.41.48]:22).
[10:41:46.926] stderr> Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
[10:41:46.927] stderr> Bytes per second: sent 36849.3, received 34907.4
[10:41:46.927] > local-server-2> ssh child died, shutting down
[10:41:46.932] Local server exit: 0
[10:41:46.932] Received install output: local-server-2> Spawned ssh, pid=33441
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
Authenticated to 10.12.41.48 ([10.12.41.48]:22).
Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
Bytes per second: sent 36849.3, received 34907.4
local-server-2> ssh child died, shutting down

[10:41:46.933] Failed to parse remote port from server output
[10:41:46.933] Resolver error: Error: 
	at Function.Create (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[10:41:46.935] ------




[10:41:46.944] ------




[10:41:46.944] SSH Resolver called for "ssh-remote+zjut.48.pmf", attempt 3, (Reconnection)
[10:41:46.945] SSH Resolver called for host: zjut.48.pmf
[10:41:46.945] Setting up SSH remote "zjut.48.pmf"
[10:41:46.946] Acquiring local install lock: /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-remote-ssh-f46263c7-install.lock
[10:41:46.946] Looking for existing server data file at /Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json
[10:41:46.947] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[10:41:46.948] Install and start server if needed
[10:41:46.952] askpass server listening on /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-21bc1eb1eb357ce8cf50f70641ebe4823931c8f5.sock
[10:41:46.953] Spawning local server with {"serverId":3,"ipcHandlePath":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-141f95296b229927c434738c6221d7e3a1734560.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","58885","-o","ConnectTimeout=15","zjut.48.pmf"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json"}
[10:41:46.953] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.5XV07TUAB5/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-21bc1eb1eb357ce8cf50f70641ebe4823931c8f5.sock"}
[10:41:46.954] Spawned 33459
[10:41:47.062] > local-server-3> Spawned ssh, pid=33485
[10:41:47.065] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:41:47.117] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
[10:41:47.172] stderr> Authenticated to 10.12.41.48 ([10.12.41.48]:22).
[10:41:47.271] stderr> Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
[10:41:47.271] stderr> Bytes per second: sent 31728.2, received 30056.2
[10:41:47.271] > local-server-3> ssh child died, shutting down
[10:41:47.276] Local server exit: 0
[10:41:47.276] Received install output: local-server-3> Spawned ssh, pid=33485
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
Authenticated to 10.12.41.48 ([10.12.41.48]:22).
Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
Bytes per second: sent 31728.2, received 30056.2
local-server-3> ssh child died, shutting down

[10:41:47.276] Failed to parse remote port from server output
[10:41:47.277] Resolver error: Error: 
	at Function.Create (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[10:41:47.278] ------




[10:41:47.282] ------




[10:41:47.283] SSH Resolver called for "ssh-remote+zjut.48.pmf", attempt 4, (Reconnection)
[10:41:47.283] SSH Resolver called for host: zjut.48.pmf
[10:41:47.284] Setting up SSH remote "zjut.48.pmf"
[10:41:47.284] Acquiring local install lock: /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-remote-ssh-f46263c7-install.lock
[10:41:47.284] Looking for existing server data file at /Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json
[10:41:47.285] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[10:41:47.286] Install and start server if needed
[10:41:47.289] askpass server listening on /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-abdbdf376f3d4cf2154ec3e59a794ebef3d25609.sock
[10:41:47.289] Spawning local server with {"serverId":4,"ipcHandlePath":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-eb7d4de6a82e78c5cc46db974525096a541bab6c.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","58887","-o","ConnectTimeout=15","zjut.48.pmf"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json"}
[10:41:47.289] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.5XV07TUAB5/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-abdbdf376f3d4cf2154ec3e59a794ebef3d25609.sock"}
[10:41:47.290] Spawned 33511
[10:41:47.396] > local-server-4> Spawned ssh, pid=33541
[10:41:47.399] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:41:47.450] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
[10:41:47.504] stderr> Authenticated to 10.12.41.48 ([10.12.41.48]:22).
[10:41:47.586] stderr> Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
[10:41:47.586] stderr> Bytes per second: sent 38656.5, received 36619.3
[10:41:47.586] > local-server-4> ssh child died, shutting down
[10:41:47.590] Local server exit: 0
[10:41:47.591] Received install output: local-server-4> Spawned ssh, pid=33541
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
Authenticated to 10.12.41.48 ([10.12.41.48]:22).
Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
Bytes per second: sent 38656.5, received 36619.3
local-server-4> ssh child died, shutting down

[10:41:47.591] Failed to parse remote port from server output
[10:41:47.591] Resolver error: Error: 
	at Function.Create (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[10:41:47.592] ------




[10:41:47.602] ------




[10:41:47.602] SSH Resolver called for "ssh-remote+zjut.48.pmf", attempt 5, (Reconnection)
[10:41:47.603] SSH Resolver called for host: zjut.48.pmf
[10:41:47.603] Setting up SSH remote "zjut.48.pmf"
[10:41:47.604] Acquiring local install lock: /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-remote-ssh-f46263c7-install.lock
[10:41:47.604] Looking for existing server data file at /Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json
[10:41:47.605] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[10:41:47.606] Install and start server if needed
[10:41:47.609] askpass server listening on /var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-45befc94ba7e4aa759802ea228e376054d62ebcb.sock
[10:41:47.609] Spawning local server with {"serverId":5,"ipcHandlePath":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-3f588f91e61b105ade0a77be7de1468a4244f22d.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","58892","-o","ConnectTimeout=15","zjut.48.pmf"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jinzcdev/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f46263c7-6d9b74a70ca9c7733b29f0456fd8195364076dda-0.84.0/data.json"}
[10:41:47.609] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.5XV07TUAB5/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/yr/0y6s6svn3nj6v_y84z3s9n5h0000gn/T/vscode-ssh-askpass-45befc94ba7e4aa759802ea228e376054d62ebcb.sock"}
[10:41:47.610] Spawned 33575
[10:41:47.711] > local-server-5> Spawned ssh, pid=33585
[10:41:47.714] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:41:47.765] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
[10:41:47.819] stderr> Authenticated to 10.12.41.48 ([10.12.41.48]:22).
[10:41:47.915] stderr> Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
[10:41:47.915] stderr> Bytes per second: sent 32848.8, received 31117.7
[10:41:47.915] > local-server-5> ssh child died, shutting down
[10:41:47.919] Local server exit: 0
[10:41:47.919] Received install output: local-server-5> Spawned ssh, pid=33585
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tJysYNqnKLJ90kcTHAjhMFB89AfDNFVaFA7ZLD/Q8eo
Authenticated to 10.12.41.48 ([10.12.41.48]:22).
Transferred: sent 3112, received 2948 bytes, in 0.1 seconds
Bytes per second: sent 32848.8, received 31117.7
local-server-5> ssh child died, shutting down

[10:41:47.919] Failed to parse remote port from server output
[10:41:47.920] Resolver error: Error: 
	at Function.Create (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (/Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/jinzcdev/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[10:41:47.921] ------


```

VS Code version: Code 1.70.1 (Universal) (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin x64 20.6.0
Modes:
Connection to 'SSH' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 7fae5c7a-b061-4e88-926b-c65a9268e173|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253

```

</details>

**Comment by jinzcdev** [comment]
I found that this problem can be solved after `Remote.SSH: Use Local Server` was unchecked. Strangely, however, It still works when I check this item again.

**Comment by hediet** [comment]
So this issue is no longer reproducible?
