### ISSUE TITLE
autocomplete :Stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by ShiYu-Yang** [Microsoft/vscode#15789]
- VSCode Version:1.7.1
- OS Version:Ubuntu 16.04

Language :Golang 1.7

Now，I work with vscode meeting a problem.Our team has an errcode file and it has a log of constants.When I use vscode and autocomplete this package.It doesn't work! I debug it and find such error in console 

[Extension Host] rejected promise not handled within 1 second
workbench.main.js:126 stdout maxBuffer exceeded: Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:271:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)e.onUnexpectedError @ workbench.main.js:126(anonymous function) @ workbench.main.js:126e.onUnexpectedError @ workbench.main.js:29r @ workbench.main.js:29t.onUnexpectedExtHostError @ workbench.main.js:101e.handle @ workbench.main.js:100s @ workbench.main.js:49f @ workbench.main.js:49_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
 
so,how can it work nicely?

Thank you!
 
Steps to Reproduce:

1. I work with golang . So it can produce a large go package with a lot of constants
2. Import it and autocomplete from this package

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#640
