### ISSUE TITLE
Notebook cell execute in Interactive Window Test Fails on MacOS

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#157826]
From https://dev.azure.com/monacotools/Monaco/_build/results?buildId=181369&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=5e43d7ff-5b8d-51b4-ea10-68cb35d0fdb0
```
2) Interactive Window
       Interactive window scrolls after execute:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: execute failed
      + expected - actual

      -0
      +1
      
      at addCellAndRun (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:39:9)
      at Context.<anonymous> (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:83:4)

  3) Interactive Window
       Interactive window has the correct kernel:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: execute failed
      + expected - actual

      -0
      +1
      
      at addCellAndRun (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:39:9)
      at Context.<anonymous> (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:103:3)

```

**Comment by rebornix** [comment]
@roblourens from the call stack `notebook.cell.execute` doesn't get us the output udpates after `await` even if we specify the cell range. I wonder if putting notebook uri in the param could help.

```
async function addCellAndRun(code: string, notebook: vscode.NotebookDocument, i: number) {
	const cell = await addCell(code, notebook);
	await vscode.commands.executeCommand('notebook.cell.execute', { start: i, end: i + 1 });
	assert.strictEqual(cell.outputs.length, 1, 'execute failed');
	return cell;
}
```

**Comment by roblourens** [comment]
We need to wait for a document update to get the updates, I think we do that in other tests
