### ISSUE TITLE
TypeError: Kill signal must be a string or number

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#157978]
Found this stack while scanning through some failing smoke test runs

```
[2022-08-12T01:05:52.019Z] [electron] stderr: [91m[main 2022-08-12T01:05:52.017Z][0m TypeError: Kill signal must be a string or number
    at sanitizeKillSignal (node:electron/js2c/browser_init:153:1833)
    at UtilityProcess.kill (node:electron/js2c/browser_init:153:1889)
    at c.waitForExit (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:74:51634)
    at async Promise.all (index 0)
    at async Object.L [as settled] (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21:22620)
    at async Promise.all (index 3)
    at async Object.L [as settled] (/__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21:22620)
    at async /__w/1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:40:9646
```

From Deepak:

> We expect an argument for kill, looks like we don't provide that here https://github.com/microsoft/vscode/blob/0abc5761ca6f03e9c6455f20c6ff696b59683261/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L282 but that should use SIGTERM by default, not sure why the error is thrown. Will check.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by bpasero** [comment]
I did check logs last week and could no longer find this.
