### ISSUE TITLE
Trouble installing the Python extension on a remote server.

### ISSUE THREAD

**Issue by kalyani7195** [microsoft/vscode#158193]
Type: <b>Bug</b>

VS Code Version: 1.70.1 (Universal)
OS Version: macos catalina version: 10.15.7

1. Download the VS code version mentioned above on the macos catalina 10.15.7.
2. Connect to a remote server using SSH
3. Try to install python extension

The error thrown on UI: Error while installing 'Python' extension. Please check the log for more details.
![image](https://user-images.githubusercontent.com/13524848/184584106-aa18274b-b4f5-43be-bb80-557fb7f2589a.png)

Error thrown in the output log:
[renderer4] [error] Unknown system error -122: Unknown system error -122, write: Extract: Unknown system error -122: Unknown system error -122, write
at de.extractAtLocation (/mmfs1/home/user/.vscode-server/bin/xyz/out/vs/server/node/server.main.js:137:98555)
at async de.extractUserExtension (/mmfs1/home/user/.vscode-server/bin/xyz/out/vs/server/node/server.main.js:137:95911)
at async U.extract (/mmfs1/home/user/.vscode-server/bin/xyz/out/vs/server/node/server.main.js:137:102952)
at async U.doRun (/mmfs1/home/user/.vscode-server/bin/xyz/out/vs/server/node/server.main.js:137:106558)

Note: I can install the Python extension on my local machine.
Any help would be greatly appreciated!
Thank you!

Extension version: 2022.12.0
VS Code version: Code 1.70.1 (Universal) (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin x64 19.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 758ff498-1191-4971-a509-9e55832e9e08|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyonecf:30545436

```

</details>

**Comment by kalyani7195** [comment]
Hello!! I am still facing the issue and would be great if you could help! 
Thanks,
Kalyani

**Comment by kalyani7195** [comment]
log (Remote server)

[2022-08-25 10:00:18.025] [remoteagent] [info] Rollback: Uninstalled extension ms-toolsai.jupyter-renderers
[2022-08-25 10:00:18.025] [remoteagent] [info] Rollback: Uninstalled extension ms-python.python
[2022-08-25 10:00:18.026] [remoteagent] [error] Failed to install extension. ms-python.python
[2022-08-25 10:00:18.028] [remoteagent] [error] Extract: Unknown system error -122: Unknown system error -122, write
    at de.extractAtLocation (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:98555)
    at async de.extractUserExtension (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:95911)
    at async z.extract (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:102952)
    at async z.doRun (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:104230)
[2022-08-25 10:00:18.913] [remoteagent] [error] Extract: Unknown system error -122: Unknown system error -122, write
    at de.extractAtLocation (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:98555)
    at async de.extractUserExtension (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:95911)
    at async z.extract (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:102952)
    at async z.doRun (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/server/node/server.main.js:137:104230)


log (window):
[2022-08-25 09:59:54.001] [renderer1] [error] Could not find pty on pty host: ErrorNoTelemetry: Could not find pty on pty host
    at d._throwIfNoPty (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:24:29654)
    at d.updateIcon (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:24:25490)
    at Object.call (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:16:8327)
    at a.onPromise (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:15:4892)
    at a.onRawMessage (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:15:4275)
    at /mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:15:3561
    at f.invoke (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at N.deliver (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at I.fire (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.Q (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:9:20673)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[2022-08-25 09:59:54.002] [renderer1] [error] Could not find pty on pty host: ErrorNoTelemetry: Could not find pty on pty host
    at d._throwIfNoPty (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:24:29654)
    at d.updateTitle (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:24:25430)
    at Object.call (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:16:8327)
    at a.onPromise (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:15:4892)
    at a.onRawMessage (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:15:4275)
    at /mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:15:3561
    at f.invoke (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at N.deliver (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at I.fire (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.Q (/mmfs1/home/kmarathe/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/platform/terminal/node/ptyHostMain.js:9:20673)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[2022-08-25 09:59:54.478] [renderer1] [error] SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at y.$getPassword (vscode-file://vscode-app/private/var/folders/cm/tp6y0cr567bd3fm1dtyz02880000gn/T/AppTranslocation/86DB41E9-6566-4A5C-B316-717DBA12999C/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:49637)
[2022-08-25 10:00:04.092] [renderer1] [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}

**Comment by sandy081** [comment]
Can you please check if you have enough disk space on the remote? Can you please try installing a smaller extension for eg ESLint and check if it works?

**Comment by kalyani7195** [comment]
Thanks for your reply! Yes, there is at least 8 GB space on the remote server and I could successfully install ESLint there.

**Comment by sandy081** [comment]
Unknown system error -122 - implies something weird with underlying disk. Can you please manually download the extension on the remote machine manually and try to unzip and see if it works?

**Comment by kalyani7195** [comment]
I clicked on install today and it got installed surprisingly!! No idea how and why. Thanks for your help. I will reach out to you if I face any issues again in the future! Thank you!
