### ISSUE TITLE
[renderer1] [error] XHR failed: Error: XHR failed

### ISSUE THREAD

**Issue by jaddel** [microsoft/vscode#158338]
Does this issue occur when all extensions are disabled?: (The question does not apply in this case)

- VS Code Version: 1.70.1
- OS Version: Win11 

Problem: VSCode won't install any extension but downloading them manually and using VSIX install still works.

Setup: A fesh windows 11 Installation. I'm not behind a proxy, vpn, or corporate network. I don't have this issue on an other machine running windows 10. 

Probably related to this: When I tried to install Visual Studio the installer wouldn't download the installation files. Adding `93.184.215.201 download.visualstudio.microsoft.com` to `C:\Windows\System32\drivers\etc\hosts`. Fixed the installer for me.

What I've done already: I tried different dns settings and used `ipconfig /flushdns` afterwards. I removed the change I've done to the windows `hosts` file.

VSCode Log:
```
[2022-08-17 07:51:16.236] [renderer1] [error] RequestService#request (browser) - error https://vsciot-vscode.gallerycdn.vsassets.io/extensions/vsciot-vscode/vscode-arduino/0.4.12/1651605198750/Microsoft.VisualStudio.Code.Manifest {}
[2022-08-17 07:51:16.598] [renderer1] [error] RequestService#request (browser) - error https://vsciot-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/vsciot-vscode/extension/vscode-arduino/0.4.12/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
[2022-08-17 07:51:16.598] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.p.onerror (vscode-file://vscode-app/c:/Users/Max/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:8827)
[2022-08-17 07:51:24.808] [renderer1] [error] RequestService#request (browser) - error https://vsciot-vscode.gallerycdn.vsassets.io/extensions/vsciot-vscode/vscode-arduino/0.4.12/1651605198750/Microsoft.VisualStudio.Code.Manifest {}
[2022-08-17 07:51:24.816] [renderer1] [error] RequestService#request (browser) - error https://vsciot-vscode.gallerycdn.vsassets.io/extensions/vsciot-vscode/vscode-arduino/0.4.12/1651605198750/Microsoft.VisualStudio.Code.Manifest {}
[2022-08-17 07:51:24.986] [renderer1] [error] RequestService#request (browser) - error https://vsciot-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/vsciot-vscode/extension/vscode-arduino/0.4.12/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
[2022-08-17 07:51:24.993] [renderer1] [error] Error: XHR failed
    at XMLHttpRequest.p.onerror (vscode-file://vscode-app/c:/Users/Max/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:8827)
[2022-08-17 07:51:24.995] [renderer1] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.p.onerror (vscode-file://vscode-app/c:/Users/Max/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:8827)
[2022-08-17 07:51:25.119] [renderer1] [error] RequestService#request (browser) - error https://vsciot-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/vsciot-vscode/extension/vscode-arduino/0.4.12/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
```

VS Code is also not loading any addon pictures or discriptions:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/46263124/185561696-9a456a25-1270-4db8-a4e9-1388a6a70cec.png">

**Comment by sandy081** [comment]
Seems network related. Hence assigning to @deepak1556

**Comment by deepak1556** [comment]
Does the issue happen with latest insiders https://code.visualstudio.com/insiders/ ?

**Comment by bphd** [comment]
People say it's about a bad registry thing, but I find nothing to apply to correct that, and it used to work
