### ISSUE TITLE
extHostConfiguration.ts breaks on invalid configuration

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15834]
Configuration:

```
    "formatOnSave": true,
    "formatOnSave.extensions": [
      "ts"
    ]
```

insert() ended up trying to write on 'true' which throws. Introduced by #15552

/cc @alexandrudima

**Comment by jrieken** [comment]
@chrmarti Unsure what you are pointing at? Please add steps etc. I have added a unit test that checks if we forward this to the backend properly and it does but then the descriptions leaves much room for interpretation

**Comment by chrmarti** [comment]
@jrieken:
- add this snippet to your workspace configuration:
```
"formatOnSave": true,
"formatOnSave.extensions": [
      "ts"
    ]
```
- reload workbench
- trigger extension loading
-> exception in extHostConfiguration.ts

**Comment by chrmarti** [comment]
```
//Users/chrmarti/Development/repos/vscode/out/vs/workbench/electron-browser/extensionHost.js:239 [Extension Host] TypeError: Cannot create property 'extensions' on boolean 'true'
    at insert (/Users/chrmarti/Development/repos/vscode/out/vs/workbench/api/node/extHostConfiguration.js:39:25)
    at createUsefulConfiguration (/Users/chrmarti/Development/repos/vscode/out/vs/workbench/api/node/extHostConfiguration.js:45:17)
    at new ExtHostConfiguration (/Users/chrmarti/Development/repos/vscode/out/vs/workbench/api/node/extHostConfiguration.js:59:35)
    at Object.createApiFactory (/Users/chrmarti/Development/repos/vscode/out/vs/workbench/api/node/extHost.api.impl.js:29:107)
    at new ExtensionHostMain (/Users/chrmarti/Development/repos/vscode/out/vs/workbench/node/extensionHostMain.js:29:46)
    at /Users/chrmarti/Development/repos/vscode/out/vs/workbench/node/extensionHostProcess.js:97:33
    at Object.notifySuccess [as _notify] (/Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (/Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (/Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (/Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)ExtensionHostProcessWorker.logExtensionHostMessage @ //Users/chrmarti/Development/repos/vscode/out/vs/workbench/electron-browser/extensionHost.js:239ExtensionHostProcessWorker.onMessaage @ //Users/chrmarti/Development/repos/vscode/out/vs/workbench/electron-browser/extensionHost.js:181(anonymous function) @ //Users/chrmarti/Development/repos/vscode/out/vs/workbench/electron-browser/extensionHost.js:123emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
//Users/chrmarti/Development/repos/vscode/out/vs/workbench/services/message/browser/messageService.js:84 Activating extension `vscode.configuration-editing` failed: Unknown actor eExtHostExtensionService.WorkbenchMessageService.doShow @ //Users/chrmarti/Development/repos/vscode/out/vs/workbench/services/message/browser/messageService.js:84WorkbenchMessageService.show @ //Users/chrmarti/Development/repos/vscode/out/vs/workbench/services/message/browser/messageService.js:66MainProcessExtensionService.$localShowMessage @ //Users/chrmarti/Development/repos/vscode/out/vs/workbench/api/node/mainThreadExtensionService.js:78MainProcessExtensionService._showMessage @ //Users/chrmarti/Development/repos/vscode/out/vs/workbench/api/node/mainThreadExtensionService.js:101(anonymous function) @ //Users/chrmarti/Development/repos/vscode/out/vs/platform/extensions/common/abstractExtensionService.js:170notifyError @ //Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1209enter @ //Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:901_run @ //Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1068_error @ //Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1041LazyPromise.resolveErr @ //Users/chrmarti/Development/repos/vscode/out/vs/platform/extensions/common/ipcRemoteCom.js:76receiveOneMessage @ //Users/chrmarti/Development/repos/vscode/out/vs/platform/extensions/common/ipcRemoteCom.js:144_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by jrieken** [comment]
Thanks
