### ISSUE TITLE
Interactive window integration test timeout

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#158425]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=182182&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=5e43d7ff-5b8d-51b4-ea10-68cb35d0fdb0&l=507

```
2) Interactive Window
       Interactive window scrolls after execute:
     Error: asPromise TIMEOUT reached
      at asPromise (/Users/runner/work/1/s/extensions/vscode-api-tests/src/utils.ts:128:16)
      at addCellAndRun (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:38:25)
      at Context.<anonymous> (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:90:4)

  3) Interactive Window
       Interactive window has the correct kernel:
     Error: asPromise TIMEOUT reached
      at asPromise (/Users/runner/work/1/s/extensions/vscode-api-tests/src/utils.ts:128:16)
      at addCellAndRun (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:38:25)
      at Context.<anonymous> (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:110:3)

```

**Comment by amunger** [comment]
Not much to go off from the current output, but perhaps has the same underlying issue as https://github.com/microsoft/vscode-jupyter/issues/11089.
Looks like it only failed once.
