### ISSUE TITLE
Broken VSIX Install Package

### ISSUE THREAD

**Issue by zi0Black** [microsoft/vscode#158870]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The VSIX package seems to be broken.

VS Code logs (logs from the manual package installation in the Jupyter logs section):
```
[2022-08-23 10:27:25.983] [sharedprocess] [info] Getting Manifest... ms-toolsai.jupyter
[2022-08-23 10:27:25.996] [sharedprocess] [info] Installing extension: ms-toolsai.jupyter
[2022-08-23 10:27:26.323] [sharedprocess] [error] Error while installing the extension: ms-toolsai.jupyter
[2022-08-23 10:27:26.324] [sharedprocess] [error] Failed to install extension. ms-toolsai.jupyter
[2022-08-23 10:27:26.324] [sharedprocess] [error] Download: XHR failed
    at x.downloadExtension (vscode-file://vscode-app/c:/Users/<User>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170149)
    at async x.doRun (vscode-file://vscode-app/c:/Users/<User>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169280)
```
Download link: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.8.1002361045/vspackage

Thanks :)

### VS Code Version

1.71.0-Insider

### Jupyter Extension Version

2022.8.1002361045

### Jupyter logs

```shell
23/08/2022 10:31:01 - Microsoft VSIX Installer
23/08/2022 10:31:01 - -------------------------------------------
23/08/2022 10:31:01 - vsixinstaller.exe version:
23/08/2022 10:31:01 - 16.11.57
23/08/2022 10:31:01 - -------------------------------------------
23/08/2022 10:31:01 - Command line parameters:
23/08/2022 10:31:01 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\<User>\Downloads\ms-toolsai.jupyter-2022.8.1002361045.vsix
23/08/2022 10:31:01 - -------------------------------------------
23/08/2022 10:31:01 - Microsoft VSIX Installer
23/08/2022 10:31:01 - -------------------------------------------
23/08/2022 10:31:02 - Skipping product Microsoft.VisualStudio.Product.BuildTools (0634e0ac) since it does not support extensions
23/08/2022 10:31:02 - Initializing Install...
23/08/2022 10:31:02 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package. ---> System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
```


### Coding Language and Runtime Version

_No response_

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

_No response_

**Comment by ryihan** [comment]
I have same issue.

**Comment by roblourens** [comment]
Works fine for me. Are you sure the file downloaded successfully? Are you behind a proxy/vpn/corporate network that could be corrupting the download? If you name the vsix with .zip and unzip it, does it look like there are legit files in it? What's the file size of the vsix?

**Comment by zi0Black** [comment]
After restarting VS Code, the installation worked directly from the packet manager. Still on VS Code 1.71.0-Insider. Sorry for disturbing you, folks.

**Comment by 1985312383** [comment]
Good job!The latest package version is wrong.
