### ISSUE TITLE
Cannot continue edit session in remote repositories

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#158991]
Trying to test https://github.com/microsoft/vscode/issues/158409...

1. Open a repo on vscode-dev (for me, https://insiders.vscode.dev/github/connor4312/mopidy-azure)
2. Make some changes in the readme.md
3. "Continue Edit Session" and "Reopen in Desktop"
4. The repository on desktop VS Code opens, but edit session changes are not applied

**Comment by connor4312** [comment]
Update: I see it's actually in the Edit Sessions view, just not continued automatically by the protocol activation. I can manually resume the edit session once desktop opens and the changes appear.

**Comment by joyceerhl** [comment]
Ah, do you have `"workbench.experimental.editSessions.autoResume": "onReload"` configured in settings?

**Comment by connor4312** [comment]
I do not

**Comment by joyceerhl** [comment]
That will be why--the auto resume behavior requires that setting to be configured in the destination workspace for now, otherwise it would still be a manual step.

**Comment by DonJayamanne** [comment]
Tried this and doesn't work for me, do I need a new version of some extension?

**Comment by joyceerhl** [comment]
@DonJayamanne you need to have the pre-releases of [Remote Repositories](marketplace.visualstudio.com/items?itemName=ms-vscode.remote-repositories) and [GitHub Repositories](http://marketplace.visualstudio.com/items?itemName=github.remotehub) installed in the latest VS Code Insiders. If it doesn't work for you, could you please share the contents of the "Log (Edit Sessions)" output channel?

**Comment by DonJayamanne** [comment]
Yes, on pre-release of both of those extensions (in web and desktop).
There's nothing in the `Log (Edit Sessions)` output,

However there are errors in the console window
<details>
  <summary>Logs</summary>

```
log.ts:301  INFO Electron sandbox mode is enabled!
log.ts:307  WARN Ignoring the error while validating workspace folder vscode-vfs://github/DonJayamanne/typescript-notebook - No file system provider found for resource 'vscode-vfs://github/DonJayamanne/typescript-notebook'
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.julia.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/julia/syntaxes/julia.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/julialang.language-julia-1.7.6/syntaxes/julia_vscode.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/ms-toolsai.vscode-ai-0.16.0/syntaxes/yaml/tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.r.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/r/syntaxes/r.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/reditorsupport.r-2.5.2/syntax/r.json
register @ TMScopeRegistry.ts:47
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, scandir '/DonJayamanne/typescript-notebook' (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
y @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, scandir '/DonJayamanne/typescript-notebook' (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
y @ console.ts:137
log.ts:313   ERR ENOENT: no such file or directory, scandir '/DonJayamanne/typescript-notebook': Error: ENOENT: no such file or directory, scandir '/DonJayamanne/typescript-notebook'
mainThreadExtensionService.ts:111 Activating extension 'vscode-icons-team.vscode-icons' failed: ENOENT: no such file or directory, open '/DonJayamanne/typescript-notebook/package.json'.
$onExtensionActivationError @ mainThreadExtensionService.ts:111
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: command '_codespaces.setActiveRepository' not found (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
y @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: command '_codespaces.setActiveRepository' not found
    at m._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:3532)
    at m.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:3414) (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
y @ console.ts:137
log.ts:313   ERR command '_codespaces.setActiveRepository' not found: Error: command '_codespaces.setActiveRepository' not found
    at m._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:3532)
    at m.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:3414)
```

</details>

**Comment by joyceerhl** [comment]
Hm, those errors are all spurious.

Do you have the following version of VS Code:

Version: 1.71.0-insider (system setup)
Commit: 9529e11f6481ae53bba821b05e34549491b9415e
Date: 2022-08-25T13:00:37.808Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

Or equivalently do you have the following settings
```
  "workbench.experimental.editSessions.enabled": true,
  "workbench.experimental.editSessions.autoResume": "onReload",
```

**Comment by DonJayamanne** [comment]
> Do you have the following version of VS Code:

Yes

> Or equivalently do you have the following settings

Yes, 
<img width="353" alt="Screen Shot 2022-08-26 at 13 58 47" src="https://user-images.githubusercontent.com/1948812/186815233-cbdf02b2-48ea-4105-86a1-e0df6480b6b2.png">

**Comment by joyceerhl** [comment]
Oh--have you run the `Edit Sessions: Sign In` command on desktop VS Code before? If not, could you try doing that and then checking to see if the following flow works for you?

https://user-images.githubusercontent.com/30305945/186822783-57af717b-b130-4537-bc2e-805d96f35f7e.mp4

We probably need some settings sync-ed memento state to communicate that we should ask for auth here.
