### ISSUE TITLE
How to properly fail startup for LanguageClient extension?

### ISSUE THREAD

**Issue by rix0rrr** [Microsoft/vscode#15906]
- VSCode Version: 1.7.1
- OS Version: Mac OS X 10.10.5

I'm building an extension for my custom language, called GCL: https://github.com/rix0rrr/gcl-vscode.

I'm basing my extension on this one: https://github.com/jonathandturner/rls_vscode, which works by launching the language server as a subprocess and communicating with it over stdin/stdout.

So far, so good, and everything works. 

Now I want to produce a useful error message when the actual executable for the language server (which should be installed via `pip`) is not available. The relevant code looks like this:

		serverOptions = () => new Promise<child_process.ChildProcess>((resolve, reject) => {
			function spawnServer(...args: string[]): child_process.ChildProcess {
				let childProcess = child_process.spawn("gcls");
				childProcess.stderr.on('data', data => {
					console.log(data.toString());
				});
				childProcess.on('error', err => {
					console.warn(err.message);
					console.warn('Error running "gcls" command. Code insight is not available.');
					console.warn('Please run "pip install gcl-language-server" or check your PATH.')
				});
				return childProcess; // Uses stdin/stdout for communication
			}

			resolve(spawnServer())
		});

However, when I now run the extension with the executable missing, I get the following output:

    GCL Extension Started
    spawn gcls ENOENT
    Error running "gcls" command. Code insight is not available.
    Please run "pip install gcl-language-server" or check your PATH.
    TypeError: Cannot read property 'dispose' of null
        at LanguageClient.cleanUp (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:631:30)
        at LanguageClient.stop (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:605:14)
        at LanguageClient.handleConnectionError (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:866:18)
        at errorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:728:19)
        at /Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:47:42
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
        at writeErrorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/main.js:113:22)
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    TypeError: Cannot read property 'dispose' of null
        at LanguageClient.cleanUp (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:631:30)
        at LanguageClient.stop (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:605:14)
        at LanguageClient.handleConnectionError (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:866:18)
        at errorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:728:19)
        at /Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:47:42
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
        at writeErrorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/main.js:113:22)
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    TypeError: Cannot read property 'dispose' of null
        at LanguageClient.cleanUp (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:631:30)
        at LanguageClient.stop (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:605:14)
        at LanguageClient.handleConnectionError (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:866:18)
        at errorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:728:19)
        at /Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:47:42
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
        at writeErrorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/main.js:113:22)
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    TypeError: Cannot read property 'dispose' of null
        at LanguageClient.cleanUp (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:631:30)
        at LanguageClient.stop (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:605:14)
        at LanguageClient.handleConnectionError (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:866:18)
        at errorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:728:19)
        at /Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-languageclient/lib/main.js:47:42
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
        at writeErrorHandler (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/main.js:113:22)
        at CallbackList.invoke (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
        at Emitter.fire (/Users/rix0rrr/Dev/gcl/gcl-vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)

i.e., the error message that I expect followed by the same `TypeError` 4 times. It seems to be happening because the `cleanUp()` function is called multiple times, but after the 1st time the `_diagnostics` attribute has been reset and all subsequent calls fail. Relevant piece of code:

    LanguageClient.prototype.cleanUp = function (diagnostics) {
        if (diagnostics === void 0) { diagnostics = true; }
        if (this._listeners) {
            this._listeners.forEach(function (listener) { return listener.dispose(); });
            this._listeners = null;
        }
        if (this._providers) {
            this._providers.forEach(function (provider) { return provider.dispose(); });
            this._providers = null;
        }
        if (diagnostics) {
            this._diagnostics.dispose();
            this._diagnostics = null;
        }
    };

How am I supposed to cleanly report errors from this subprocess object, and make sure it gets shut down after the first call?

**Comment by dbaeumer** [comment]
You need to reject the promise when the start failed. You always complete the promise with `resolve(spawnServer())`. In node when spawning a child process errors are reported in two ways: async via the error emit and sync by childProcess.pid being undefined if the spawn fails directly (which I guess happens in our case).
