### ISSUE TITLE
IdentityFile with UNC path

### ISSUE THREAD

**Issue by TWART016** [microsoft/vscode#159286]
I login with ssh and a private key. I use it on multiple clients and want to have a single config file. Therefore I want the IdentityFile as a UNC path to store the key on a single location.

**Comment by TylerLeonhardt** [comment]
When you say you "login with ssh" are you referring to the Remote SSH extension?

**Comment by TWART016** [comment]
Yes. The name is ```Remote - SSH```
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

**Comment by tanhakabir** [comment]
The SSH extension uses OpenSSH that's the default SSH client already installed on your machine. What happens now if you use a UNC path?

**Comment by TWART016** [comment]
With UNC path configured I get an error (translated):
`a connection to "MYIP" could not be established `
There are 3 buttons: Close Remote, additional Actions, Retry.

It is the same bahavior than a wrong private key.

In the Log I see that:
```[13:51:39.199] SSH Resolver called for "ssh-remote+MYIP", attempt 3, (Reconnection)
[13:51:39.201] SSH Resolver called for host: MYIP
[13:51:39.201] Setting up SSH remote "MYIP"
[13:51:39.203] Using commit id "e4503b30fc78kfdklfieömb76ff5547662" and quality "stable" for server
[13:51:39.210] Install and start server if needed
[13:51:43.936] Running script with connection command: ssh -T -D 53330 "MYIP" bash
[13:51:43.940] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:51:46.325] > ]0;C:\WINDOWS\System32\cmd.exe
[13:51:46.325] Got some output, clearing connection timeout
[13:51:46.531] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[13:51:46.558] > @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Permissions for '\\\\nas1\\Backup\\Oracle\\Test01\\ssh-key-2022-08-27.key' are t
> oo open.
> It is required that your private key files are NOT accessible by others.        
> This private key will be ignored.
> Load key "\\\\nas1\\Backup\\Oracle\\Test01\\ssh-key-2022-08-27.key": bad permiss
> ions
> ubuntu@MYIP: Permission denied (publickey).
> Ein Prozess hat versucht, zu einer nicht bestehenden Pipe zu schreiben.
>        
[13:51:47.877] "install" terminal command done
[13:51:47.879] Install terminal quit with output:        
[13:51:47.879] Received install output:        
[13:51:47.881] Resolver error: Error: 
	at Function.Create (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585222)
	at c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:583101
	at Object.t.handleInstallOutput (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:583796)
	at Object.t.tryInstall (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:643908
	at async Object.t.withShowDetailsEvent (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:647224)
	at async Object.t.resolve (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:644958)
	at async c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:727082
[13:51:47.896] ```

**Comment by tanhakabir** [comment]
What happens now if you use a UNC path in your IdentityFile and connect with your termnial or PowerShell?

**Comment by TWART016** [comment]
In Powershell I get also an error. It seems like a permission problem with the public key.
