### ISSUE TITLE
Settings sync disabled itself in github.dev

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#159302]
I opened https://github.dev/microsoft/vscode/pull/159276 and saw my theme get changed to the default. I suspected that something went wrong with settings sync, and it appears to have been disabled.

Logs:

```
[2022-08-26 15:21:22.618] [settingssync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2022-08-26 15:21:22.626] [settingssync] [info] Auto Sync is disabled.
[2022-08-26 15:21:24.084] [settingssync] [info] Disabling extension firefox-devtools.vscode-firefox-debug
[2022-08-26 15:21:24.108] [settingssync] [info] Disabling extension ms-edgedevtools.vscode-edge-devtools
[2022-08-26 15:21:24.320] [settingssync] [info] Disabling extension ms-vscode-remote.remote-ssh-nightly
[2022-08-26 15:21:24.339] [settingssync] [info] Disabling extension ms-vscode.github-browser
[2022-08-26 15:21:24.346] [settingssync] [info] Disabling extension vscode-samples.proposed-api-sample
[2022-08-26 15:21:24.350] [settingssync] [info] Disabling extension vscode-samples.task-provider-samples
[2022-08-26 15:21:24.354] [settingssync] [info] Disabling extension ms-vscode.powershell
[2022-08-26 15:21:24.361] [settingssync] [info] Disabling extension dart-code.dart-code
[2022-08-26 15:21:25.418] [settingssync] [error] Unsupported: Cannot install the 'ESLint' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:25.926] [settingssync] [error] Unsupported: Cannot install the 'Remote - WSL' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:26.400] [settingssync] [error] Unsupported: Cannot install the 'Remote - Containers' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:26.895] [settingssync] [error] Unsupported: Cannot install the 'Remote - SSH' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:27.392] [settingssync] [error] Unsupported: Cannot install the 'Remote - SSH: Editing Configuration Files' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:27.914] [settingssync] [error] Unsupported: Cannot install the '[Deprecated] Debugger for Chrome' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:28.458] [settingssync] [error] Unsupported: Cannot install the 'PowerShell' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:29.000] [settingssync] [error] Unsupported: Cannot install the 'Dart' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:29.499] [settingssync] [error] Unsupported: Cannot install the 'Debugger for Firefox' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:30.162] [settingssync] [error] Unsupported: Cannot install the 'German Language Pack for Visual Studio Code' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:30.606] [settingssync] [error] Unsupported: Cannot install the 'Microsoft Edge Tools for VS Code' extension because it is not available in this setup.
    at b.installFromGallery (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:3201:135167)
    at async W.initialize (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:118686)
    at async https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113892
    at async Promise.all (index 1)
    at async N.initializeExtensions (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:113122)
    at async Promise.allSettled (index 1)
    at async N.initializeOtherResources (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:112935)
    at async x.initializeOtherResource (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:2725:119874)
[2022-08-26 15:21:32.392] [settingssync] [info] Installed extension. ms-vscode.vscode-js-profile-table

```

Version info:
Version: 1.71.0-insider
Commit: 35b971c92d210face8c446a1c6f1e470ad2bcb54
Date: 2022-08-26T09:17:26.667Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

<details><summary>Console output in case it's useful:</summary>
```
 INFO Settings Sync: Updated current session github-session-sync-service
log.ts:301  INFO Skipping initializing tasks because local tasks exist.
log.ts:301  INFO Initialized User Tasks
log.ts:301  INFO Created snippet snips.code-snippets
log.ts:301  INFO Initialized User Snippets
log.ts:301  INFO Initialized Keyboard Shortcuts
log.ts:301  INFO Migrating global extension storage from github.codespaces to GitHub.codespaces...
log.ts:301  INFO Migrated global extension storage from github.codespaces to GitHub.codespaces
log.ts:301  INFO Migrating workspace extension storage from github.codespaces to GitHub.codespaces...
log.ts:301  INFO Migrated workspace extension storage from github.codespaces to GitHub.codespaces
log.ts:301  INFO Migrating global extension storage from github.vscode-pull-request-github to GitHub.vscode-pull-request-github...
log.ts:301  INFO Migrated global extension storage from github.vscode-pull-request-github to GitHub.vscode-pull-request-github
log.ts:301  INFO Migrating workspace extension storage from github.vscode-pull-request-github to GitHub.vscode-pull-request-github...
log.ts:301  INFO Migrated workspace extension storage from github.vscode-pull-request-github to GitHub.vscode-pull-request-github
log.ts:301  INFO Migrating global extension storage from github.remotehub to GitHub.remotehub...
log.ts:301  INFO Migrated global extension storage from github.remotehub to GitHub.remotehub
log.ts:301  INFO Migrating workspace extension storage from github.remotehub to GitHub.remotehub...
log.ts:301  INFO Migrated workspace extension storage from github.remotehub to GitHub.remotehub
xhr.js:166 
        
       Refused to set unsafe header "User-Agent"
setRequestHeader @ xhr.js:166
xhr.js:166 
        
       Refused to set unsafe header "User-Agent"
setRequestHeader @ xhr.js:166
xhr.js:166 
        
       Refused to set unsafe header "User-Agent"
setRequestHeader @ xhr.js:166
main.js:1 
        
       Loading vscode-nls-web-data failed. Are you running this outside of VS Code? If so, you may need to intercept the import call with your bundled NLS data.
189 @ main.js:1
abstractTaskService.ts:2294 
        
       Custom workspace tasks are not supported.
_computeWorkspaceFolderTasks @ abstractTaskService.ts:2294
log.ts:301  INFO Getting Manifest... ms-vscode.vscode-js-profile-table
log.ts:301  INFO Installing extension: ms-vscode.vscode-js-profile-table
log.ts:301  INFO Installing the extension without checking dependencies and pack ms-vscode.vscode-js-profile-table
log.ts:301  INFO Extension installed successfully: ms-vscode.vscode-js-profile-table
log.ts:313   ERR [ms-vscode.remote-repositories]: notebook/cell/executePrimary is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["notebookEditor"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vscode.remote-repositories
18abstractTaskService.ts:2294 
        
       Custom workspace tasks are not supported.
_computeWorkspaceFolderTasks @ abstractTaskService.ts:2294
log.ts:313   ERR Error while registering log channel file:///20220826T152121/ptyhost.log Timed out while waiting for file to be created
extHostLanguages.ts:89 
        
       Uncaught (in promise) Error: LanguageStatusItem with id 'info' ALREADY exists
    at E.createLanguageStatusItem (extHostLanguages.ts:89:10)
    at Object.createLanguageStatusItem (extHost.api.impl.ts:579:29)
    at _showStatusAndInfo (anycode.extension.browser.js:26093:40)
    at eval (anycode.extension.browser.js:26215:5)
async.ts:357 
        
       Uncaught (in promise) Canceled: Canceled
    at c.cancel (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:84:13728)
    at r.cancel (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:84:14087)
    at o.unwatch (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:1998:8012)
    at https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:1998:9803
    at S.invoke (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:80:145)
    at o.deliver (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:80:2266)
    at l.fire (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:80:1844)
    at _n.dispose (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:733:16875)
    at S.destroyModel (https://main.vscode-cdn.net/insider/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/workbench.web.main.js:747:1250)
```
</details>

**Comment by alexr00** [comment]
It has just happened again in a Codespace.

**Comment by alexr00** [comment]
This was my own error as I was using github.dev on another machine where I hadn't enabled settings sync before. Sorry for the noise!
