### ISSUE TITLE
Quick Find File-Search Takes 10-15 Seconds With On-Network Remote SSH Connection

### ISSUE THREAD

**Issue by WDC** [microsoft/vscode#159303]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2 (Universal)
- OS Version: macOS 12.4

Steps to Reproduce:

1. Connect to an SSH Remote (CentOS 8 Stream, local network, tested 700MB/s and 13ms ping) and open a remote folder.
2. Notice that the remote folder has ~11 files and no symbolic links.
3. Attempt to search for a file using `Command + P`. 
4. Notice that it takes 10-19 seconds to return the first results.
5. Open a new window with a local directory.
6. Attempt to search for a file using `Command + P`.
7. Notice that searching takes ~100ms, almost instant.

I have disabled all extensions, I have reinstalled VS Code from scratch, I have used the "Nightly" version of `Remote - SSH` extension, I have created 1-file remote directories, I have inspected the `--verbose` output (no mention of `rg` commands or similar), and I have tested with another macOS computer. I simply cannot get the Quick Find functionality to return results in a reasonable amount of time.

I have ensured my "Exclude" settings cover various library directories (like `node_modules`) and unchecked the "Follow Symlink" checkbox. 

What should be my next step to diagnosing this issue with the `Remote - SSH` extension, that prior to 3 weeks ago had never had an issue with Quick Find.

Please [view this short screen capture](https://user-images.githubusercontent.com/1221004/186916595-c9d10f8a-7552-4def-8c5b-eabd96c415fc.mov) showing the performance issue on an M1 Max MacBook Pro.

Thank you!

https://user-images.githubusercontent.com/1221004/186916595-c9d10f8a-7552-4def-8c5b-eabd96c415fc.mov

**Comment by WDC** [comment]
@roblourens I am begging for some help with this, as it has completely stalled my development workflow. Is there any debugging tips you can provide for diagnosing an issue with `Remote - SSH`?

**Comment by WDC** [comment]
@roblourens I am still begging. This issue has gotten significantly worse, with file-searches now taking upwards of 45 seconds. 

I will donate $100 to the project or to you if you can help me.

**Comment by roblourens** [comment]
Sorry, I don't understand your screen recording. It's 6s long, you entered the query at 4s and the results showed up right away.

Also, please share the trace-level logs from `Log (Window)` and `Log (Remote Extension host)` output channels.

**Comment by WDC** [comment]
Sorry about the video, it got cut incorrectly.

Please look at this video: https://imgur.com/a/vX77FpP

In each instance, I begin typing just as soon as the pop-up appears, and you can see it takes a significant amount of time to even open the pop-up after using `Command + P`, much less display the typed text or show files results.

Thank you.

Here are the logs, including the `rg` command itself:
```[2022-09-14 08:05:22.456] [exthost] [error] TypeError: vscode.window.showWarningMessage is not a constructor
	at activate (/root/.vscode-server/extensions/peakchen90.vue-beautify-2.0.4/extension.js:15:5)
	at Function._callActivateOptional (/root/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:97:17473)
	at Function._callActivate (/root/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:97:17131)
	at /root/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:97:14942
	at async v._activate (/root/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async v._waitForDepsThenActivate (/root/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async v._initialize (/root/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
[2022-09-14 08:05:22.456] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-09-14 08:05:22.903] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-09-14 08:05:22.906] [exthost] [info] Eager extensions activated
[2022-09-14 08:08:46.855] [exthost] [trace] [vscode.merge-conflict] INVOKE provider 'Q=>Q.provideCodeLenses(d.URI.revive($),K)'
[2022-09-14 08:08:46.856] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2022-09-14 08:08:46.857] [exthost] [trace] [vscode.merge-conflict] provider DONE after 2ms
[2022-09-14 08:08:49.975] [exthost] [trace] [vscode.merge-conflict] INVOKE provider 'Q=>Q.provideCodeLenses(d.URI.revive($),K)'
[2022-09-14 08:08:49.976] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2022-09-14 08:08:49.977] [exthost] [trace] [vscode.merge-conflict] provider DONE after 2ms
[2022-09-14 08:08:56.091] [exthost] [trace] [vscode.merge-conflict] INVOKE provider 'Q=>Q.provideCodeLenses(d.URI.revive($),K)'
[2022-09-14 08:08:56.092] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2022-09-14 08:08:56.092] [exthost] [trace] [vscode.merge-conflict] provider DONE after 1ms
[2022-09-14 08:09:01.403] [exthost] [debug] ExtHostSearch /root/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/node_modules/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/node_modules/**/*' -g '!**/public' -g '!**/public/**' -g '!**/vendor' -g '!**/vendor/**' -g '!**/node_modules/**' -g '!**/bower_components' -g '!**/*.code-search' -g '!**/.git/**' -g '!**/vendor/**/vendor' --no-config
 - cwd: /usr/share/nginx/html/project-apollo-web-app
 - Sibling clauses: {}
 ```

When I execute only the `rg` command in the approprirate directory, the results take roughly 0.01s:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/1221004/190149966-dbcd2fe5-824e-4cc4-8155-31463af8e03e.png">

**Comment by roblourens** [comment]
Oh I see, there is a hang in the window while you are actually typing. Have you updated to the latest release? We actually fixed a related issue recently. You could also try with the Insiders build.

If it still reproes, please get a perf trace while doing this (Help > Toggle Developer Tools > Performance tab, record)

**Comment by WDC** [comment]
Maximum success! I can't believe that an update immediately fixed this... I have been updating Code as often as it prompted me, but this last one resolved the issue, and now the file-searches take a whopping ~75ms.

Thank you so much!
