### ISSUE TITLE
TypeScript server not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by makuolgo** [Microsoft/vscode#15963]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-47-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|java|redhat|0.0.6|

---

Hi Microsoft!

I'm very happy with vscode in general - good work!
However, I'm unable to get embedded TypeScript server to work on Ubuntu 16.04 with Node.js. vscode was installed using the .deb file.

Steps to Reproduce:

1. Install node.js version 6.9.1 LTS
2. npm init
3: npm install express --save
4: Create .js file and import any core module (for instance 'express' or 'fs'.

Recieving the following error in output:

[Info  - 3:14:09 PM] Using tsserver from location: /usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js
[Error - 3:14:22 PM] 'completions' request failed with error.
Error processing request. Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at getCompletionEntriesFromTypings (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:48215:79)
    at getCompletionEntriesForNonRelativeModules (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:48094:17)
    at getStringLiteralCompletionEntriesFromModuleNames (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:47985:31)
    at getStringLiteralCompletionEntries (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:47889:28)
    at Object.getCompletionsAtPosition (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:47773:24)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:54974:64)
    at Session.handlers.ts.createMap._a.(anonymous function) (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:54219:61)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:55286:28)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:55306:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:56389:27)

**Comment by mjbvz** [comment]
I believe this issue was fixed on the TS side by https://github.com/Microsoft/TypeScript/commit/6ea5c227603efd14d379170af2efa5642219f8b7 which is not present in TS 2.0.10 . We should pick it up in ts 2.1.x  (I confirmed that it is already in 2.1.1).

**Comment by makuolgo** [comment]
So fixed in next release of VSCode then?

**Comment by mjbvz** [comment]
Yes, we are waiting on the release of TS 2.1.3. Adopting it is being traced by  #15535.
