### ISSUE TITLE
Invoking Continue Working On stores edit session even if no destination was selected

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#159690]
1. Have edit sessions enabled in settings
2. Run Continue Working On command
3. Don't pick a destination, esc to dismiss the quickpick
4. Run Show Edit Sessions command
5. :bug: edit session was created anyway

**Comment by meganrogge** [comment]
is it expected to not see options here in an untrusted workspace?
![Screen Shot 2022-09-29 at 10 52 06 AM](https://user-images.githubusercontent.com/29464607/193105952-c78910f8-2881-4489-a881-094e7c4aab36.png)

**Comment by meganrogge** [comment]
```
VM8 workbench.web.main.js:84 
        
       Uncaught (in promise) Canceled: Canceled
    at https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:84:11404
    at f.invoke (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:80:145)
    at o.deliver (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:80:2266)
    at d.fire (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:80:1844)
    at _.cancel (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:80:20330)
    at k.cancel (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:80:20871)
    at Object.cancel (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:84:11562)
    at C.dispose (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:807:2013)
    at c.dispose (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:19:31486)
    at h (https://main.vscode-cdn.net/insider/2c801254ebf547baaee771b99aa76d202f999622/out/vs/workbench/workbench.web.main.js:19:29833)
​   ERR [text file model] handleSaveError(7) - exit - resulted in a save error: Error: Unable to write file '/vscode/extensions/git/src/terminal.ts' (Unavailable (FileSystemError): Error: Insufficient permissions. Please retry and allow the operation.) file:///vscode/extensions/git/src/terminal.ts
​ 
        
       Failed to save 'terminal.ts': Unable to write file '/vscode/extensions/git/src/terminal.ts' (Unavailable (FileSystemError): Error: Insufficient permissions. Please retry and allow the operation.)
```

**Comment by meganrogge** [comment]
worked in https://insiders.vscode.dev/github/microsoft/vscode
