### ISSUE TITLE
CodeWindow: renderer process crashed (reason: crashed, code: -36861)

### ISSUE THREAD

**Issue by bbarry** [microsoft/vscode#159601]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.70.2 (user setup)
- Commit: e4503b30fc78200f846c62cf8091b76ff5547662
- Date: 2022-08-16T05:35:13.448Z
- Electron: 18.3.5
- Chromium: 100.0.4896.160
- Node.js: 16.13.2
- V8: 10.0.139.17-electron.0
- OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. not really sure; open VsCode?
2. wait?

I'm repeatedly getting a popup  that says VsCode crashed with error -36861 and I don't know what is causing it...

The error is showing up in my main log:

```
[2022-08-30 09:53:00.265] [main] [info] update#setState idle
[2022-08-30 09:53:12.675] [main] [info] Starting extension host with pid 247668 (fork() took 3782 ms).
[2022-08-30 09:53:29.779] [main] [info] Enabling inspect port on extension host with pid 247668.
[2022-08-30 09:53:30.274] [main] [info] update#setState checking for updates
[2022-08-30 09:53:30.934] [main] [error] Error: net::ERR_CERT_COMMON_NAME_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:7047)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
[2022-08-30 09:53:30.963] [main] [info] update#setState idle
[2022-08-30 09:54:08.194] [main] [info] Starting extension host with pid 256244 (fork() took 2025 ms).
[2022-08-30 09:55:18.563] [main] [info] Enabling inspect port on extension host with pid 256244.
[2022-08-30 09:55:19.097] [main] [info] Enabling inspect port on extension host with pid 256244.
[2022-08-30 10:14:38.966] [main] [info] Starting extension host with pid 282232 (fork() took 935 ms).
[2022-08-30 10:53:30.266] [main] [info] update#setState checking for updates
[2022-08-30 10:53:30.833] [main] [info] update#setState idle
[2022-08-30 11:53:30.226] [main] [info] update#setState checking for updates
[2022-08-30 11:53:30.888] [main] [info] update#setState idle
[2022-08-30 12:53:30.203] [main] [info] update#setState checking for updates
[2022-08-30 12:53:31.160] [main] [info] update#setState idle
[2022-08-30 12:57:58.068] [main] [error] CodeWindow: renderer process crashed (reason: crashed, code: -36861)
[2022-08-30 12:57:58.290] [main] [info] Extension host with pid 282232 exited with code: 0, signal: null.
[2022-08-30 12:58:33.333] [main] [info] Starting extension host with pid 318512 (fork() took 2530 ms).
[2022-08-30 12:58:38.742] [main] [info] update#setState checking for updates
[2022-08-30 12:58:39.478] [main] [info] update#setState idle
[2022-08-30 12:58:45.188] [main] [info] Enabling inspect port on extension host with pid 318512.
[2022-08-30 13:01:42.671] [main] [info] Extension host with pid 256244 exited with code: 0, signal: null.
[2022-08-30 13:01:47.838] [main] [info] Starting extension host with pid 303304 (fork() took 4125 ms).
[2022-08-30 13:02:02.434] [main] [info] Enabling inspect port on extension host with pid 303304.
[2022-08-30 13:04:16.610] [main] [info] Extension host with pid 318512 exited with code: 0, signal: null.
[2022-08-30 13:05:21.749] [main] [info] Starting extension host with pid 323572 (fork() took 8413 ms).
[2022-08-30 13:05:33.333] [main] [info] Enabling inspect port on extension host with pid 323572.
[2022-08-30 13:53:30.175] [main] [info] update#setState checking for updates
[2022-08-30 13:53:30.851] [main] [info] update#setState idle
[2022-08-30 14:08:58.149] [main] [error] CodeWindow: renderer process crashed (reason: crashed, code: -36861)
[2022-08-30 14:08:58.165] [main] [error] [uncaught exception in main]: Error: SharedProcess: crashed (detail: crashed, code: -36861)
[2022-08-30 14:08:58.165] [main] [error] Error: SharedProcess: crashed (detail: crashed, code: -36861)
    at C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:77421
    at b.invoke (C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:19:145)
    at I.deliver (C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:19:2272)
    at m.fire (C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:19:1850)
    at C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:17:19798
    at b.invoke (C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:19:145)
    at I.deliver (C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:19:2272)
    at m.fire (C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:19:1850)
    at EventEmitter.<anonymous> (C:\Users\bbarry\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:85281)
    at EventEmitter.emit (node:events:402:35)
[2022-08-30 14:08:58.604] [main] [info] Extension host with pid 303304 exited with code: 0, signal: null.
[2022-08-30 14:09:42.741] [main] [info] Starting extension host with pid 307276 (fork() took 2254 ms).
[2022-08-30 14:10:01.775] [main] [info] Enabling inspect port on extension host with pid 307276.
[2022-08-30 14:10:01.838] [main] [info] Enabling inspect port on extension host with pid 307276.
```

I am not sure what url is causing the cert error but my employer has most of the internet blocked and redirecting to a page that causes a cert error so I am expecting that (would be nice if the log here had the url of the failure when a network request fails... I think that is a separate issue though). I cannot seem to use the **Report Issue**  menu item because of this as well I am guessing (it doesn't seem to do anything).

**Comment by bbarry** [comment]
It hasn't happened since yesterday afternoon and I cannot find a value -36861 or ffff7003 in the code here so I am not sure what to look for to trigger it again or come up with something reproducable.

I'm ok with closing as "something messed up in user environment outside of VsCode." It would be nice to have a little info and direction where I might look to figure out what was/is wrong though.

**Comment by deepak1556** [comment]
If it happens again, please try to get the crash report using the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports.
