### ISSUE TITLE
[error] net::ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by agfn** [microsoft/vscode#159751]
Type: <b>Bug</b>

can not check update or view extension market

- open vscode with `code --disable-extensions`
- Log(Window)

```
[2022-09-01 19:13:08.086] [renderer3] [error] net::ERR_PROXY_CONNECTION_FAILED: Error: net::ERR_PROXY_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:7047)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
[2022-09-01 19:13:08.185] [renderer3] [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {}
[2022-09-01 19:13:10.279] [renderer3] [error] RequestService#request (browser) - error https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json {}
```

- Log(Main)

```
[2022-09-01 19:07:56.570] [main] [info] update#setState idle
[2022-09-01 19:07:57.518] [main] [info] Starting extension host with pid 68186 (fork() took 2 ms).
[2022-09-01 19:08:26.579] [main] [info] update#setState checking for updates
[2022-09-01 19:08:26.654] [main] [error] UpdateService error: 无法连接服务器。
[2022-09-01 19:08:26.654] [main] [info] update#setState idle
[2022-09-01 19:12:53.133] [main] [info] Extension host with pid 68186 exited with code: 0, signal: null.
[2022-09-01 19:13:07.900] [main] [info] Starting extension host with pid 69397 (fork() took 2 ms).
```
in extensions market, search extension, Log(Window) output:

```
[2022-09-01 19:35:01.287] [renderer3] [error] Error: XHR failed
    at XMLHttpRequest.p.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:8827)
[2022-09-01 19:35:03.132] [renderer3] [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {}
[2022-09-01 19:35:03.132] [renderer3] [error] Error: XHR failed
    at XMLHttpRequest.p.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:70:8827)
```

but i can visit the url using curl

```
$ curl https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery   
{"count":1,"value":{"Message":"The requested resource does not support http method 'GET'."}}%                                                                                         
```

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:38:59.695Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|32.00GB (2.86GB free)|
|Process Argv|--log-net-log=netlog.json --crash-reporter-id b70edc19-7b22-4b26-965d-abddf461babb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by agfn** [comment]
i'm so sorry that it's my fault. i'm using whistle which configures proxy global, but the only thing i have checked is proxy environment.
