### ISSUE TITLE
OverflowError: in method 'SBInstructionList_GetInstructionAtIndex'

### ISSUE THREAD

**Issue by PerMildner** [Microsoft/vscode#16012]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|vscode-lldb|vadimcn|0.3.1|
|debug|webfreak|0.12.3|

---

Steps to Reproduce:

1. On OS X, launched a C program using "type":"lldb", tried to step or some such (just getting started with vscode). Suddenly debugee hung and vscode "Continue" button does nothing. Debug Console showed the following error message:

[11:13:32 debugsession] Internal debugger error:
Traceback (most recent call last):
  File "./adapter/debugsession.py", line 695, in handle_message
    result = handler(args)
  File "./adapter/debugsession.py", line 407, in DEBUG_stackTrace
    dasm = disassembly.Disassembly(pc_sbaddr, self.target)
  File "./adapter/disassembly.py", line 62, in __init__
    last_instr = self.instructions[len(self.instructions)-1]
  File "/Applications/Xcode_8_1.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 5267, in __getitem__
    return self.GetInstructionAtIndex(key)
  File "/Applications/Xcode_8_1.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 5236, in GetInstructionAtIndex
    return _lldb.SBInstructionList_GetInstructionAtIndex(self, *args)
OverflowError: in method 'SBInstructionList_GetInstructionAtIndex', argument 2 of type 'uint32_t'

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-cpptools#372
