### ISSUE TITLE
Error thrown in notebook editor open

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#160239]
I ran into the _notebook editor fail to open_ issue again, and this time I only got this error

```
ERR unknown text editor: 16a9ad35-8158-470f-ba73-a1a89f6aeba7. known editors:  : Error: unknown text editor: 16a9ad35-8158-470f-ba73-a1a89f6aeba7. known editors:  
	at ExtHostNotebookController.getEditorById (c:\Users\rebor\code\vscode\out\vs\workbench\api\common\extHostNotebook.js:62:23)
	at ExtHostNotebookKernels.$acceptKernelMessageFromRenderer (c:\Users\rebor\code\vscode\out\vs\workbench\api\common\extHostNotebookKernels.js:286:50)
	at RPCProtocol._doInvokeHandler (c:\Users\rebor\code\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:381:27)
	at RPCProtocol._invokeHandler (c:\Users\rebor\code\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:366:45)
	at RPCProtocol._receiveRequest (c:\Users\rebor\code\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:307:32)
	at RPCProtocol._receiveOneMessage (c:\Users\rebor\code\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:234:26)
	at c:\Users\rebor\code\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:115:52
	at Listener.invoke (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:457:27)
	at PrivateEventDeliveryQueue.deliver (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:627:38)
	at Emitter.fire (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:592:37)
	at BufferedEmitter.fire (c:\Users\rebor\code\vscode\out\vs\base\parts\ipc\common\ipc.net.js:480:35)
	at c:\Users\rebor\code\vscode\out\vs\workbench\api\node\extensionHostProcess.js:188:41
	at Listener.invoke (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:457:27)
	at PrivateEventDeliveryQueue.deliver (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:627:38)
	at Emitter.fire (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:592:37)
	at BufferedEmitter.fire (c:\Users\rebor\code\vscode\out\vs\base\parts\ipc\common\ipc.net.js:480:35)
	at PersistentProtocol._receiveMessage (c:\Users\rebor\code\vscode\out\vs\base\parts\ipc\common\ipc.net.js:746:45)
	at c:\Users\rebor\code\vscode\out\vs\base\parts\ipc\common\ipc.net.js:624:83
	at Listener.invoke (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:457:27)
	at PrivateEventDeliveryQueue.deliver (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:627:38)
	at Emitter.fire (c:\Users\rebor\code\vscode\out\vs\base\common\event.js:592:37)
	at ProtocolReader.acceptChunk (c:\Users\rebor\code\vscode\out\vs\base\parts\ipc\common\ipc.net.js:271:37)
	at c:\Users\rebor\code\vscode\out\vs\base\parts\ipc\common\ipc.net.js:238:61
	at Socket.listener (c:\Users\rebor\code\vscode\out\vs\base\parts\ipc\node\ipc.net.js:50:17)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

This reminds me of the investigation we did in https://github.com/microsoft/vscode/issues/123270#issuecomment-1207093418 but since we have changes to that issue, I'm not sure if it's still related.

**Comment by rebornix** [comment]
I think this is resolved with recent editor service changes.
