### ISSUE TITLE
Listener leak or over-listening in `SessionsRenderer`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#160382]
While using VS Code for a while the listener leak below is frequently generated. This is triggered by the event listener [here in the `callStackView#SessionRenderer`](https://github.com/microsoft/vscode/blob/eed1b6ac4907e125fa9188e7a3253bc94cf7aac1/src/vs/workbench/contrib/debug/browser/callStackView.ts#L598)

This is either a real leak or a case of over-listening, e.g it seems that every call stack element uses the same menu and instead of a menu per rendered element a single shared menu can be used. 

```
workbench.desktop.main.js:formatted:24615 [d7f] potential listener LEAK detected, having 498 listeners already. MOST frequent listener (308):
workbench.desktop.main.js:formatted:24616 Error
    at i.create (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:81:28257)
    at _event._event [as onDidChange] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:1056)
    at Object.v [as onFirstListenerAdd] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:809:197908)
    at _event._event [as onDidChange] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:974)
    at bl.doRenderElement (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2137:15696)
    at bl.renderCompressedElements (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2137:15105)
    at E.renderCompressedElements (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:25672)
    at I.renderElement (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:7592)
    at R.renderElement (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:543:52730)
    at q.renderElement (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:1932)
    at g.insertItemInDOM (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:138:18964)
    at g._splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:138:14777)
    at g.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:138:12996)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3:198667
    at Array.forEach (<anonymous>)
    at t.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3:198654)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:8788
    at v.bufferEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:5207)
    at z.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:163:8755)
    at z.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:543:66265)
    at Object.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:45087)
    at b.spliceSimple (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:28899)
    at b.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:26948)
    at A._setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:36984)
    at A.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:36386)
    at r._setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:42698)
    at r.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:41826)
    at o.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:134:46191)
    at S.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:8609)
    at ae.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:23617)
    at ae.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:28049)
    at ae.refreshAndRenderNode (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:20099)
    at async ae._updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:17119)
    at async ae.updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:16794)
    at async M.runner (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2137:8107)
```

**Comment by boltex** [comment]
I'm an extension developer, and i've noticed that 'potential listener LEAK detected' started to appear in the console a few days ago..

i've looked at all the 'on Did... ' clauses (onDidChangeVisibility, onDidCollapseElement, etc... )in my code and cannot find anything different or problematic. 

I wish this error message would print out which object has all those listeners so we could see from which extension, or part of the codebase, those extra listeners are being tacked on. 

(sorry if this is irrelevant i'm quite a newb with all this.)

Thanks

**Comment by roblourens** [comment]
Wow - when `renderCompressedElements` was added, `disposeCompressedElements` was not added, so these have never been disposed...

**Comment by roblourens** [comment]
I looked through all the usages and the same mistake was made in search this past month. Seems like all other usages get it right.
