### ISSUE TITLE
Cannot sync settings

### ISSUE THREAD

**Issue by asg0451** [microsoft/vscode#160341]
Type: <b>Bug</b>

> Sync now

Hangs. I see this in the sync log:

[2022-09-07 14:29:17.884] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/settings/latest
[2022-09-07 14:29:17.885] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/settings/latest'.
    at R.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:146108)
    at async R.readResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:142525)
    at async f.getRemoteUserData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:31520)
    at async f._sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:21873)
    at async f.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:20973)
    at async r.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:120886)
[2022-09-07 14:29:17.885] [settingssync] [error] settings: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/settings/latest'.
[2022-09-07 14:29:17.900] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.13.0-1027-gcp
Remote OS version: Linux x64 5.13.0-1027-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 27a3d0db-9236-42b5-b822-bc0d17ee513e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 5.13.0-1027-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (16 x 2199)|
|Memory (System)|58.86GB (47.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 5.13.0-1027-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (16 x 2199)|
|Memory (System)|58.86GB (47.79GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
default-keys-windows|smc|0.0.9
emacs|vsc|0.1.3
vscode-ruby|win|0.28.0
vscode-bazel|Baz|0.5.0
vscode-markdownlint|Dav|0.48.1
gitlens|eam|12.2.2
vscode-highlight|fab|1.6.0
foam-vscode|foa|0.19.5
copilot|Git|1.43.6621
vscode-pull-request-github|Git|0.50.0
go|gol|0.35.2
jsonnet|hep|0.1.0
magit|kah|0.6.32
center-editor-window|kai|2.3.0
vscode-typescript-next|ms-|4.9.20220905
go-doc|msy|1.0.1
vscode-paste-image|mus|1.0.4
rust-analyzer|rus|0.3.1194
trailing-spaces|sha|0.4.1
org-mode|vsc|1.0.0
markdown-all-in-one|yzh|3.4.3
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by sandy081** [comment]
Connection to the server is refused.

**Comment by asg0451** [comment]
har file attached (ext changed to txt for github)

console:

```
Access to XMLHttpRequest at 'https://vscode-sync.trafficmanager.net/v1/manifest'[vscode-app.txt](https://github.com/microsoft/vscode/files/9528347/vscode-app.txt) from origin 'vscode-file://vscode-app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
log.ts:313   ERR RequestService#request (browser) - error https://vscode-sync.trafficmanager.net/v1/manifest Error: XHR failed
    at E.onerror (request.ts:30:29)
vscode-sync.trafficmanager.net/v1/manifest:1          Failed to load resource: net::ERR_FAILED
sharedProcess.html:1 Access to XMLHttpRequest at 'https://vscode-sync.trafficmanager.net/v1/manifest' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
log.ts:313   ERR RequestService#request (browser) - error https://vscode-sync.trafficmanager.net/v1/manifest Error: XHR failed
    at E.onerror (request.ts:30:29)
vscode-sync.trafficmanager.net/v1/manifest:1          Failed to load resource: net::ERR_FAILED
bootstrap-window.js:252 [uncaught exception]: Error: read ECONNRESET
b @ bootstrap-window.js:252
bootstrap-window.js:255 Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
b @ bootstrap-window.js:255
sharedProcess.html:1 Access to XMLHttpRequest at 'https://vscode-sync.trafficmanager.net/v1/manifest' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
log.ts:313   ERR RequestService#request (browser) - error https://vscode-sync.trafficmanager.net/v1/manifest Error: XHR failed
    at E.onerror (request.ts:30:29)
vscode-sync.trafficmanager.net/v1/manifest:1          Failed to load resource: net::ERR_FAILED
```

**Comment by asg0451** [comment]
[vscode-app.txt](https://github.com/microsoft/vscode/files/9528350/vscode-app.txt)

**Comment by asg0451** [comment]
[vscode-app2.txt](https://github.com/microsoft/vscode/files/9528364/vscode-app2.txt)

**Comment by Tyriar** [comment]
@sandy081 I wasn't expecting CORS to be used here, does something weird happen when connected to a remote?

**Comment by sandy081** [comment]
Settings Sync does not run on remote. It runs on local client on the shared process.

@deepak1556 Any insights why these requests have failed?

**Comment by Francois-Bergeron** [comment]
Same error on my end. Tried syncing again, but did not work. Tried to log in with Edge, Chrome and FF.
