### ISSUE TITLE
TS Server fatal error:  The "interval" argument must be of type number. Received undefined

### ISSUE THREAD

**Issue by TeshaneCrawford** [microsoft/vscode#160624]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.9.0-dev.20220908

**Steps to reproduce crash**
1. Start development server
2. Make changes to React TS/TSX files
3. Error prompt occurs (Random)

**Global TS Server Plugins**

- `@astrojs/ts-plugin`
- `@monodon/typescript-nx-imports-plugin`
- `typescript-styled-plugin`
- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`
- `typescript-vue-plugin-forward`
- `typescript-lit-html-plugin`
- `@vuedx/typescript-plugin-vue`

**TS Server Log**
❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError [ERR_INVALID_ARG_TYPE]: The "interval" argument must be of type number. Received undefined
    at StatWatcher.<computed> (node:internal/fs/watchers:116:3)
    at Object.watchFile (node:fs:2316:39)
    at fsWatchFileWorker (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:7307:21)
    at /home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6882:133
    at createSingleWatcherPerName (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6432:26)
    at pollingWatchFile (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6882:20)
    at watchFile (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6763:28)
    at watchMissingFileSystemEntry (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6991:24)
    at fsWatchHandlingExistenceOnHost (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6896:17)
    at /home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6885:168
    at createSingleWatcherPerName (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6432:26)
    at fsWatch (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6885:20)
    at Object.watchFile (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:6769:28)
    at Object.watchFile (/home/teshane/.vscode-server/extensions/znck.vue-language-features-0.10.4/node_modules/@vuedx/typescript-plugin-vue/lib/standalone.js:687:13099)
    at watchFile (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:117435:90)
    at Object.watchFile (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:117461:34)
    at /home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:175471:44
    at ProjectService.forEachConfigFileLocation (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:175521:38)
    at ProjectService.startWatchingConfigFilesForInferredProjectRoot (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:175460:22)
    at InferredProject.addRoot (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:173655:37)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:175201:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:176899:26)
    at /home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:177173:97
    at Object.flatMap (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:177173:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:178546:46)
    at /home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:180738:96
    at IpcIOSession.Session.executeWithRequestId (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:180729:28)
    at IpcIOSession.Session.executeCommand (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:180738:41)
    at IpcIOSession.Session.onMessage (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:180766:35)
    at process.<anonymous> (/home/teshane/.vscode-server/extensions/ms-vscode.vscode-typescript-next-4.9.20220908/node_modules/typescript/lib/tsserver.js:184918:31)
    at process.emit (node:events:526:28)
    at process.emit (node:domain:475:12)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.99GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/teshane/ProjectsTc/t.crawford --crash-reporter-id d37e77d8-5055-40fd-b359-c8d9ddac852b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|Memory (System)|3.75GB (0.60GB free)|
|VM|0%|
</details><details><summary>Extensions (143)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
es7-react-js-snippets|dsz|4.4.3
sweet-vscode-icons|Eli|0.0.1
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-graphql-syntax|Gra|1.0.4
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.1
feather-vscode|mel|1.0.1
emoji-icons|mig|1.2.1
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-azurevirtualmachines|ms-|0.6.2
vscode-edge-devtools|ms-|2.1.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
awesome-flutter-snippets|Nas|3.0.3
material-icon-theme|PKi|4.20.0
material-product-icons|PKi|1.4.0
nextjs-snippets|Pul|0.0.5
vscode-rapidapi-client|Rap|1.5.0
flutter-riverpod-snippets|rob|1.1.1
bootstrap-product-icons|rub|1.0.2
vue-vscode-snippets|sdr|3.1.1
bunker|sld|1.1.6
swdc-vscode|sof|2.6.33
errorlens|use|3.6.0
JavaScriptSnippets|xab|1.8.0
flutter-provider-snippets|Zar|1.5.0
codesnap|adp|1.3.4
vscode-angular2-files|ale|1.6.4
better-tests|and|0.3.1
ng-template|Ang|14.2.0
astro-vscode|ast|0.24.4
armview|ben|0.4.6
dart-data-class-generator|Ben|0.5.5
vscode-tailwindcss|bra|0.8.6
simple-react-snippets|bur|1.2.6
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
ccs-flutter-color|cir|1.0.2
dart-code|Dar|3.48.3
flutter|Dar|3.48.0
vscode-markdownlint|Dav|0.48.1
composer-php-vscode|DEV|1.14.10477
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|12.2.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.8.0
pubspec-dependency-search|eve|1.1.0
vue-format|feb|0.1.8
bloc|Fel|6.6.1
vscode-jest-runner|fir|0.4.55
flutter-mobx|Flu|0.0.6
code-runner|for|0.11.8
get-snippets|get|4.3.0
copilot|Git|1.44.6735
copilot-labs|Git|0.2.221
vscode-pull-request-github|Git|0.50.0
live-sass|gle|5.5.1
go|gol|0.35.2
vscode-test-explorer|hbe|2.21.1
headwind|hey|1.7.0
rest-client|hum|0.25.1
angular2-switcher|inf|0.4.0
ionic|Ion|1.9.5
Ionide-fsharp|Ion|7.1.0
search-node-modules|jas|1.3.0
pubspec-assist|jer|2.3.2
firebase-explorer|jsa|0.3.3
fast-snippets|kin|1.6.2
vscode-gutter-preview|kis|0.30.0
vscode-lottie|lot|1.0.5
flutter-tree|mar|1.0.0
ts-error-translator|mat|0.5.1
dart-barrel-file-generator|miq|4.0.0
mongodb-vscode|mon|0.9.3
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.2.0
vscode-azureappservice|ms-|0.24.3
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.5
vscode-azurestaticwebapps|ms-|0.11.2
vscode-azurestorage|ms-|0.14.2
vscode-azurevirtualmachines|ms-|0.6.2
vscode-bicep|ms-|0.10.13
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
dotnet-interactive-vscode|ms-|1.0.3452020
vscode-dotnet-pack|ms-|1.0.9
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
vscode-postgresql|ms-|0.3.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
azure-account|ms-|0.11.1
azurecli|ms-|0.5.0
live-server|ms-|0.4.0
powershell|ms-|2022.8.5
test-adapter-converter|ms-|0.1.6
vscode-node-azure-pack|ms-|1.1.0
vscode-typescript-next|ms-|4.9.20220909
vsliveshare|ms-|1.0.5711
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.7
vscode-react-native|msj|1.9.3
sqltools|mtx|0.24.0
angular-console|nrw|17.21.0
remove-comments|pli|1.2.2
tsimporter|pmn|2.0.1
prisma|Pri|4.3.1
vscode-thunder-client|ran|1.18.7
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.14
autoimport|ste|1.5.4
move-ts|str|1.12.0
vscode-styled-components|sty|1.7.4
sass-indented|syl|1.8.22
icons|tal|3.5.0
intellicode-api-usage-examples|Vis|0.2.2
vscodeintellicode|Vis|1.2.25
volar|Vue|0.40.13
vscode-typescript-vue-plugin|Vue|0.40.13
WebTemplateStudio-dev-nightly|WAS|0.7.2117301
literally-html|web|0.1.3
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.3
vue|znc|0.10.4
vue-language-features|znc|0.10.4

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

You have a bunch of TS server plugins enabled which could be causing this

**Comment by TeshaneCrawford** [comment]
I Okay so I haven't had any failure after a day of testing with just the built-in extensions. I deleted some of them, systems seem to be bloated by them.
