### ISSUE TITLE
Build client: Egress is over the account limit

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160766]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=184963&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=74a6ab88-b179-5f14-59e8-d1f703aecfb9

```
$ node --max_old_space_size=8192 ./node_modules/gulp/bin/gulp.js vscode-darwin-x64-min-ci
[05:11:35] Using gulpfile ~/work/1/s/gulpfile.js
[05:11:35] Starting 'vscode-darwin-x64-min-ci'...
[05:11:35] Starting clean-vscode-darwin-x64 ...
[05:11:35] Finished clean-vscode-darwin-x64 after 3 ms
[05:11:35] Starting vscode-darwin-x64-min-ci ...

[05:11:53] 'vscode-darwin-x64-min-ci' errored after 18 s
[05:11:53] HTTPError: Response code 503 (Egress is over the account limit.)
    at EventEmitter.<anonymous> (/Users/runner/work/1/s/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:552:15)
    at module.exports (/Users/runner/work/1/s/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/runner/work/1/s/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:552:15)
    at ClientRequest.origin.emit (/Users/runner/work/1/s/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:674:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Bash exited with code '1'.
Finishing: Build client
```

**Comment by sbatten** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=189413&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=fa9f62b9-64aa-5c0b-1afc-7ebad86eca0c

Saw this with ^^

**Comment by lszomoru** [comment]
@bpasero, any reason why this was assigned to me? I am not familiar with the failing gulp task.

**Comment by bpasero** [comment]
No, feel free to move on as appropiate.

**Comment by lszomoru** [comment]
@joaomoreno, any idea who would be right owner here? Thanks!

**Comment by joaomoreno** [comment]
I assume this is downloading Electron. I don't see any option other than replicating Electron bits to our own storage and pay for it ourselves. I suggest to close this or otherwise measure how often this really happens.
