### ISSUE TITLE
cannot add a decoration for a command undefined with no marker

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#160839]
```
 ERR cannot add a decoration for a command undefined with no marker: Error: cannot add a decoration for a command undefined with no marker
    at c.registerCommandDecoration (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1934:14829)
    at c.registerMarkDecoration (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1934:11613)
    at vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1934:11322
    at p.invoke (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at l.deliver (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2266)
    at d.fire (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:1844)
    at m.addMark (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:656:1889)
    at Ui.addBufferMarker (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3081:6583)
    at vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:37176
    at p.invoke (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at l.deliver (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2266)
    at d.fire (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:1844)
    at i.tryFinish (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:34851)
    at i.processLineInternal (vscode-file://vscode-app/Users/meganrogge/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1697:33723)
```

**Comment by meganrogge** [comment]
repro is to run the VS Code build task and open the dev tools console. You shouldn't see this error
