### ISSUE TITLE
(Web) Extensions install and enable vscode-smoketest-check extension

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#160830]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=185049&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=5f0e9dbb-0df0-5bb0-f10b-78953999773d&l=156

```
  1) VSCode Smoke Tests (Web)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: is active element 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-editor textarea' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:275:11)
      at Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/src/code.ts:232:3)
      at Extensions.searchForExtension (/Users/runner/work/1/s/test/automation/src/extensions.ts:34:3)
      at Extensions.installExtension (/Users/runner/work/1/s/test/automation/src/extensions.ts:60:3)
      at Context.<anonymous> (src/areas/extensions/extensions.test.ts:19:4)
```

**Comment by sandy081** [comment]
Pretty sure that this was random because the check that failed should not have failed unless someone in between would have taken the focus. So assuming that something would have come up in the machine during this and took the focus away.
