### ISSUE TITLE
icon, title, and resize error

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#160847]
```
  ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at h._throwIfNoPty (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:23:36849)
    at h.resize (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:23:33720)
    at Object.call (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)
    at u.onPromise (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at u.onRawMessage (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at _.invoke (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at A.deliver (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at F.fire (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.X (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:9:20708)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
workbench.desktop.main.js:606   ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at h._throwIfNoPty (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:23:36849)
    at h.updateIcon (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:23:32643)
    at Object.call (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)
    at u.onPromise (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at u.onRawMessage (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at _.invoke (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at A.deliver (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at F.fire (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.X (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:9:20708)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
workbench.desktop.main.js:606   ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at h._throwIfNoPty (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:23:36849)
    at h.updateTitle (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:23:32581)
    at Object.call (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)
    at u.onPromise (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at u.onRawMessage (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at _.invoke (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at A.deliver (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at F.fire (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.X (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/platform/terminal/node/ptyHostMain.js:9:20708)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

```

**Comment by Tyriar** [comment]
What's the repro for this? Try clearing `out` and rebuilding to make sure it's just a stale output problem related to the recent setIcon change.

**Comment by rzhao271** [comment]
Is this issue verifiable?

**Comment by Tyriar** [comment]
Doesn't look a change was made
