### ISSUE TITLE
provideCellStatusBarItems called on metadata change

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161090]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=185525&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9bc48eac-eb66-52c8-7250-d6490c5f3a15&l=587

```
 1 failing
  1) statusbar
       provideCellStatusBarItems called on metadata change:
     Error: asPromise TIMEOUT reached
      at asPromise (extensions/vscode-api-tests/src/utils.ts:128:16)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/notebook.api.test.ts:280:34)
      at processImmediate (node:internal/timers:466:21)
```

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/157828
