### ISSUE TITLE
Cannot read properties of undefined (reading 'length'): 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#161618]
* have an empty settings file
* paste the contents below
* 💥 an error happens

```
{
    // Editor
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.folding": true,
    "editor.smoothScrolling": false,
    "editor.formatOnPaste": true,
    "[json]": {
        "editor.formatOnSave": false,
        "editor.formatOnPaste": true
    },
    // Workbench
    "workbench.colorCustomizations": {
        "focusBorder": "#F3F3F3",
        "inputOption.activeBackground": "#007acc1f",
        "editorLineNumber.activeForeground": "#2b91af",
        "list.focusHighlightForeground": "#fff",
        "activityBar.activeBorder": "#2c2c2c",
        "sideBarSectionHeader.border": "#0000",
        "list.activeSelectionBackground": "#3399FF",
        "list.highlightForeground": "#0066BF",
        // "list.activeSelectionIconForeground": "#fff",
    },
    // Terminal
    "terminal.integrated.fontFamily": "Menlo",
    "terminal.integrated.fontSize": 13,
    "terminal.integrated.lineHeight": 1.4,
    // Misc
    "git.confirmSync": false,
    "git.showActionButton": {
        "commit": false,
        "publish": false,
        "sync": false
    },
    "extensions.autoUpdate": true,
    "git.enableSmartCommit": true,
    "problems.decorations.enabled": true,
    "explorer.decorations.colors": false,
    "explorer.confirmDragAndDrop": false,
    "git.autofetch": true,
    "extensions.ignoreRecommendations": true,
    "editor.find.globalFindClipboard": false,
    "git.showInlineOpenFileAction": false,
    "git.ignoreLimitWarning": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "git.inputValidationSubjectLength": 500,
    "workbench.tree.renderIndentGuides": "none",
    "editor.renderWhitespace": "none",
    "gulp.autoDetect": "off",
    "scm.defaultViewMode": "list",
    "terminal.integrated.windowsEnableConpty": false,
    "javascript.updateImportsOnFileMove.enabled": "never",
    "debug.onTaskErrors": "debugAnyway",
    "explorer.confirmDelete": false,
    "terminal.integrated.enablePersistentSessions": false,
    "workbench.editor.untitled.hint": "hidden",
    "hediet.vscode-drawio.local-storage": "eyIuZHJhd2lvLWNvbmZpZyI6IntcImxhbmd1YWdlXCI6XCJcIixcImN1c3RvbUZvbnRzXCI6W10sXCJsaWJyYXJpZXNcIjpcImdlbmVyYWxcIixcImN1c3RvbUxpYnJhcmllc1wiOltcIkwuc2NyYXRjaHBhZFwiXSxcInBsdWdpbnNcIjpbXSxcInJlY2VudENvbG9yc1wiOltdLFwiZm9ybWF0V2lkdGhcIjowLFwiY3JlYXRlVGFyZ2V0XCI6ZmFsc2UsXCJwYWdlRm9ybWF0XCI6e1wieFwiOjAsXCJ5XCI6MCxcIndpZHRoXCI6ODI3LFwiaGVpZ2h0XCI6MTE2OX0sXCJzZWFyY2hcIjp0cnVlLFwic2hvd1N0YXJ0U2NyZWVuXCI6dHJ1ZSxcImdyaWRDb2xvclwiOlwiI2QwZDBkMFwiLFwiZGFya0dyaWRDb2xvclwiOlwiIzZlNmU2ZVwiLFwiYXV0b3NhdmVcIjp0cnVlLFwicmVzaXplSW1hZ2VzXCI6bnVsbCxcIm9wZW5Db3VudGVyXCI6MCxcInZlcnNpb25cIjoxOCxcInVuaXRcIjoxLFwiaXNSdWxlck9uXCI6ZmFsc2UsXCJ1aVwiOlwiXCJ9In0=",
    "workbench.welcomePage.experimental.extensionContributions": true,
    "notebook.dragAndDropEnabled": false,
    "editor.bracketPairColorization.enabled": true,
    "eslint.codeAction.showDocumentation": {
        "enable": false
    },
    "explorer.compactFolders": false,
    "git.showUnpublishedCommitsButton": "never",
    "workbench.experimental.sidePanel.enabled": true,
    "window.restoreFullscreen": true,
    "editor.dragAndDrop": false,
    "typescript.implementationsCodeLens.enabled": true,
    "debug.internalConsoleOptions": "neverOpen",
    "workbench.startupEditor": "none",
    "git.closeDiffOnOperation": true,
    "timeline.activeSource": "timeline.localHistory",
    "workbench.experimental.dragAndDropIntoEditor.enabled": true,
    "editor.formatOnSave": true,
    "editor.guides.indentation": false,
    "[powershell]": {
        "files.encoding": "cp437",
        "editor.wordWrap": "on"
    },
    "workbench.editor.closeEmptyGroups": false,
    "git.timeline.showUncommitted": true,
    "[hlsl]": {
        "files.encoding": "cp850"
    },
    "workbench.editor.enablePreviewFromQuickOpen": true,
    "security.workspace.trust.untrustedFiles": "open",
    "window.titleMenu": true,
    "terminal.integrated.shellIntegration.enabled": true,
    "window.newWindowDimensions": "inherit",
    "explorer.copyRelativePathSeparator": "\\",
    "git.experimental.mergeEditor": true,
    "files.watcherExclude": {
        "*.js": true,
        "bar": true,
        "bar/index.js": true,
        "index.js": true
    },
    "remoteHub.commitDirectlyWarning": "off",
    "editor.fontSize": 13,
    "diffEditor.renderIndicators": false,
    "editor.minimap.autohide": true,
    "editor.minimap.enabled": false,
    "workbench.experimental.settingsProfiles.enabled": true,
    "editor.codeLens": false,
    "git.mergeEditor": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "breadcrumbs.enabled": false,
    "editor.contrib.experimental.codeActionWidget.enabled": true,
    "workbench.editor.pinnedTabSizing": "shrink",
    "window.commandCenter": true,
    "git.postCommitCommand": "push",
    "workbench.editor.enablePreview": false,
    "window.zoomLevel": 1,
    "workbench.editor.highlightModifiedTabs": true,
    "workbench.colorTheme": "Default Light+",
    "workbench.transparency": true
}
```

**Comment by jrieken** [comment]
```
ERR Cannot read properties of undefined (reading 'length'): TypeError: Cannot read properties of undefined (reading 'length')
    at ConfigKeysIterator.next (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/map.js:79:43)
    at ConfigKeysIterator.reset (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/map.js:70:25)
    at TernarySearchTree._delete (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/map.js:463:37)
    at TernarySearchTree._delete (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/map.js:511:26)
    at TernarySearchTree.delete (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/map.js:457:25)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/platform/contextkey/browser/contextKeyService.js:104:48
    at Listener.invoke (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:461:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:631:38)
    at Emitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:596:37)
    at WorkspaceService.triggerConfigurationChange (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:868:48)
    at WorkspaceService.onLocalUserConfigurationChanged (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:627:18)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:67:107
    at Listener.invoke (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:461:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:631:38)
    at Emitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:596:37)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/services/configuration/browser/configuration.js:100:206
```

**Comment by bpasero** [comment]
👏
