### ISSUE TITLE
Test Syncing Settings Profiles

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#161785]
Refs: https://github.com/microsoft/vscode/issues/154243

- [x] win @rebornix
- [x] linux @roblourens
- [x] mac @isidorn

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161785%0A%0A&assignees=sandy081)

---

You can now sync settings profiles using settings sync. Test that profiles are getting synced correctly

Note: You can open VS Code Insiders on two different user data directories and extension directories and test syncing between these two instances.

- Creating/Updating/Removing a profile is getting synced
- Data in the profile is getting synced (Settings, Keyboard Shortcuts, Snippets, Extensions, Tasks & UI State)
- You can disable syncing profiles by unchecking `Settings Profiles` entry after running the command `Settings Sync: Configure`
- Test handling and resolving any conflicts in profiles data. You can create conflicts using following steps
  - Disable syncing Settings on one machine
  - Change the theme in different profiles
  - Change the theme to different value in other machine also
  - Enable syncing settings on first machine
  - This shall trigger conflicts
- Please do exploratory testing by thinking about other scenarios

**Comment by isidorn** [comment]
I updated the assignees so I get the mac, since my win machine is not corp joined so I can not login and turn on settings sync. Hope that is fine 😊

**Comment by isidorn** [comment]
Works well. This issue makes the experience very hard for me https://github.com/microsoft/vscode/issues/161955

**Comment by rebornix** [comment]
I'm testing across machines (Windows as my main device) but I didn't seem to get the settings to be synced. This is what I did

* Create a profile on Windows
* Change some settings
* Switch to macOS
* Force setting sync
* Profile is fetched successfully, everything sets to default

Now that on my macOS, I have a fresh state but the settings changes on Windows are not synced to macOS, or vice versa. @sandy081 did I miss anything here?

**Comment by roblourens** [comment]
This worked fine once, but I'm mainly blocked on #162051

**Comment by sandy081** [comment]
@rebornix I am wondering if you have hit the same issue as @roblourens in the issue he created #162051. I just tried your steps (Windows <-> Mac) and sync worked for me. I think there could be an issue with settings sync server at that moment, can you please try to reproduce by enabling log level to trace and provide following logs

- Settings Sync log
- Shared Process network requests (see if there are any requests to settings sync server are hanging?)

**Comment by rebornix** [comment]
@sandy081  I got this 405 error saying `Last sync resource does not exist` for my custom profile.

```
[2022-09-28 12:29:02.483] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-09-28 12:29:02.484] [settingssync] [info] Sync started.
[2022-09-28 12:29:02.605] [settingssync] [info] Profiles: No changes found during synchronizing profiles.
[2022-09-28 12:29:02.643] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-09-28 12:29:02.650] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-09-28 12:29:02.657] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-09-28 12:29:02.663] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-09-28 12:29:02.669] [settingssync] [info] GlobalState: No changes found during synchronizing ui state.
[2022-09-28 12:29:02.671] [settingssync] [info] Syncing profile. jupyter-notebook
[2022-09-28 12:29:02.673] [settingssync] [info] Settings (jupyter-notebook): Not synced yet. Last sync resource does not exist.
[2022-09-28 12:29:02.731] [settingssync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/collection/0eb4a354-436d-4e40-b8a2-4d41ff366584/resource/settings/latest","status":405,"execution-id":"b8139f6f-74a4-4ee4-8208-d16ddf474316"}
[2022-09-28 12:29:02.736] [settingssync] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 405
    at y.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:169412)
    at async y.readResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:163672)
    at async d.getRemoteUserData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:32311)
    at async d._sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:22423)
    at async d.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:21523)
    at async p.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:145440)
    at async l.syncProfile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135807)
    at async l.syncRemoteProfiles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135314)
    at async l.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:134810)
[2022-09-28 12:29:02.736] [settingssync] [error] settings: Server returned 405
[2022-09-28 12:29:02.738] [settingssync] [info] Keybindings (jupyter-notebook): Not synced yet. Last sync resource does not exist.
[2022-09-28 12:29:02.799] [settingssync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/collection/0eb4a354-436d-4e40-b8a2-4d41ff366584/resource/keybindings/latest","status":405,"execution-id":"b8139f6f-74a4-4ee4-8208-d16ddf474316"}
[2022-09-28 12:29:02.800] [settingssync] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 405
    at y.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:169412)
    at async y.readResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:163672)
    at async d.getRemoteUserData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:32311)
    at async d._sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:22423)
    at async d.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:21523)
    at async p.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:145440)
    at async l.syncProfile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135807)
    at async l.syncRemoteProfiles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135314)
    at async l.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:134810)
[2022-09-28 12:29:02.800] [settingssync] [error] keybindings: Server returned 405
[2022-09-28 12:29:02.802] [settingssync] [info] Snippets (jupyter-notebook): Not synced yet. Last sync resource does not exist.
[2022-09-28 12:29:02.931] [settingssync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/collection/0eb4a354-436d-4e40-b8a2-4d41ff366584/resource/snippets/latest","status":405,"execution-id":"b8139f6f-74a4-4ee4-8208-d16ddf474316"}
[2022-09-28 12:29:02.932] [settingssync] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 405
    at y.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:169412)
    at async y.readResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:163672)
    at async S.getRemoteUserData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:32311)
    at async S._sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:22423)
    at async S.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:21523)
    at async p.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:145440)
    at async l.syncProfile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135807)
    at async l.syncRemoteProfiles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135314)
    at async l.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:134810)
[2022-09-28 12:29:02.932] [settingssync] [error] snippets: Server returned 405
[2022-09-28 12:29:02.935] [settingssync] [info] Tasks (jupyter-notebook): Not synced yet. Last sync resource does not exist.
[2022-09-28 12:29:02.999] [settingssync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/collection/0eb4a354-436d-4e40-b8a2-4d41ff366584/resource/tasks/latest","status":405,"execution-id":"b8139f6f-74a4-4ee4-8208-d16ddf474316"}
[2022-09-28 12:29:03.000] [settingssync] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 405
    at y.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:169412)
    at async y.readResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:163672)
    at async v.getRemoteUserData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:32311)
    at async v._sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:22423)
    at async v.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:21523)
    at async p.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:145440)
    at async l.syncProfile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135807)
    at async l.syncRemoteProfiles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135314)
    at async l.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:134810)
[2022-09-28 12:29:03.000] [settingssync] [error] tasks: Server returned 405
[2022-09-28 12:29:03.002] [settingssync] [info] GlobalState (jupyter-notebook): Not synced yet. Last sync resource does not exist.
[2022-09-28 12:29:03.171] [settingssync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/collection/0eb4a354-436d-4e40-b8a2-4d41ff366584/resource/globalState/latest","status":405,"execution-id":"b8139f6f-74a4-4ee4-8208-d16ddf474316"}
[2022-09-28 12:29:03.172] [settingssync] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 405
    at y.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:169412)
    at async y.readResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:163672)
    at async vt.getRemoteUserData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:32311)
    at async vt._sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:22423)
    at async vt.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:21523)
    at async p.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:145440)
    at async l.syncProfile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135807)
    at async l.syncRemoteProfiles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135314)
    at async l.sync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:134810)
[2022-09-28 12:29:03.173] [settingssync] [error] globalState: Server returned 405
[2022-09-28 12:29:03.173] [settingssync] [info] Sync done. Took 690ms

```

**Comment by sandy081** [comment]
@Tyriar May I know what does this mean

> "https://vscode-sync-insiders.trafficmanager.net/v1/collection/0eb4a354-436d-4e40-b8a2-4d41ff366584/resource/settings/latest

405 implies method does not exist.

**Comment by Tyriar** [comment]
@sandy081 that means either the manifest or the collection does not exist for the user

**Comment by sandy081** [comment]
I am not sure if this can be possible. @rebornix Lets sync directly to see if I can unblock you for testing.
