### ISSUE TITLE
Hard to tell that Edit Sessions were turned on with two different auth providers

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#162025]
Testing #161875

1. open a repo in insiders.dev and make a change in a file
2. `Continue on` desktop
:bug: no changes 

![continueOn](https://user-images.githubusercontent.com/2019016/192595803-abd1ad99-cd1b-4fae-b904-16dfea8e9ba6.gif)

**Comment by joyceerhl** [comment]
@amunger is your local VS Code Insiders instance on:

Version: 1.72.0-insider (user setup)
Commit: 36b1398cfbabbe91d695717d76b818a788f7b7d9
Date: 2022-09-27T05:18:12.318Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes


If it is not, could you please try updating your Insiders build and try again? If it is, would you mind sharing the `Log (Edit Sessions)` output channel contents?

**Comment by amunger** [comment]
there was another update available, but after that update, same thing happened

Version: 1.72.0-insider (user setup)
Commit: 36b1398cfbabbe91d695717d76b818a788f7b7d9
Date: 2022-09-27T05:18:12.318Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

```
[2022-09-27 10:44:20.688] [editsessions] [info] Resuming edit session, reason: edit sessions enabled...
[2022-09-27 10:44:20.689] [editsessions] [info] Resuming edit session...
[2022-09-27 10:44:20.689] [editsessions] [info] Searching for existing authentication session with ID 72f988bf-86f1-41af-91ab-2d7cd011db47/5a6355c5-3f15-4654-b204-5ec7e57d791d/3ffb786f-192e-47b7-8a84-81307cfbc927
[2022-09-27 10:44:33.836] [editsessions] [info] Found existing authentication session with ID 72f988bf-86f1-41af-91ab-2d7cd011db47/5a6355c5-3f15-4654-b204-5ec7e57d791d/3ffb786f-192e-47b7-8a84-81307cfbc927
[2022-09-27 10:44:34.135] [editsessions] [info] Aborting resuming edit session as no edit session content is available to be applied from ref undefined.
[2022-09-27 10:44:35.513] [editsessions] [info] Resuming edit session, reason: edit sessions enabled...
[2022-09-27 10:44:35.513] [editsessions] [info] Resuming edit session...
[2022-09-27 10:44:36.625] [editsessions] [info] Searching for existing authentication session with ID 72f988bf-86f1-41af-91ab-2d7cd011db47/5a6355c5-3f15-4654-b204-5ec7e57d791d/3ffb786f-192e-47b7-8a84-81307cfbc927
[2022-09-27 10:44:57.488] [editsessions] [info] Found existing authentication session with ID 72f988bf-86f1-41af-91ab-2d7cd011db47/5a6355c5-3f15-4654-b204-5ec7e57d791d/3ffb786f-192e-47b7-8a84-81307cfbc927
[2022-09-27 10:44:57.812] [editsessions] [info] Aborting resuming edit session as no edit session content is available to be applied from ref undefined.
```

**Comment by amunger** [comment]
Same thing for the other direction, edit on desktop > Continue on vscode.dev

`Could not resume edit session contents for ID fa8df090-19b3-4d8a-8632-13f539878c03.`

```
[2022-09-27 11:03:35.224] [editsessions] [info] Resuming edit session, reason: found editSessionId fa8df090-19b3-4d8a-8632-13f539878c03 in environment service...
[2022-09-27 11:03:35.357] [editsessions] [info] Resuming edit session with ref fa8df090-19b3-4d8a-8632-13f539878c03...
[2022-09-27 11:03:35.415] [editsessions] [info] Searching for existing authentication session with ID 626eddda-9b1e-453b-a76f-78b1363419e0
[2022-09-27 11:03:35.478] [editsessions] [info] Found existing authentication session with ID 626eddda-9b1e-453b-a76f-78b1363419e0
[2022-09-27 11:03:35.539] [editsessions] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/editSessions/fa8df090-19b3-4d8a-8632-13f539878c03","status":404,"execution-id":"55cdc01b-2dab-4bd2-bdf7-b366d00a1e12"}
[2022-09-27 11:03:35.598] [editsessions] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 404
    at T.request (https://main.vscode-cdn.net/insider/36b1398cfbabbe91d695717d76b818a788f7b7d9/out/vs/workbench/workbench.web.main.js:811:156458)
    at async T.resolveResourceContent (https://main.vscode-cdn.net/insider/36b1398cfbabbe91d695717d76b818a788f7b7d9/out/vs/workbench/workbench.web.main.js:811:149671)
    at async Hn.read (https://main.vscode-cdn.net/insider/36b1398cfbabbe91d695717d76b818a788f7b7d9/out/vs/workbench/workbench.web.main.js:2154:6982)
    at async go.resumeEditSession (https://main.vscode-cdn.net/insider/36b1398cfbabbe91d695717d76b818a788f7b7d9/out/vs/workbench/workbench.web.main.js:3105:131736)
    at async https://main.vscode-cdn.net/insider/36b1398cfbabbe91d695717d76b818a788f7b7d9/out/vs/workbench/workbench.web.main.js:3105:126677
[2022-09-27 11:03:35.614] [editsessions] [info] Aborting resuming edit session as no edit session content is available to be applied from ref fa8df090-19b3-4d8a-8632-13f539878c03.
```

**Comment by joyceerhl** [comment]
Interesting. Are you using the same account for Edit Sessions in the source and destination? What does the edit session log say in the source (from web to desktop as well as desktop to web)?

**Comment by joyceerhl** [comment]
If you use the `Show Edit Sessions` command that should pull up a view to visualize any edit sessions that you have stored on the server.

**Comment by amunger** [comment]
desktop source logs:

```[2022-09-27 11:11:10.884] [editsessions] [info] Storing edit session...
[2022-09-27 11:11:11.090] [editsessions] [info] Stored edit session with ref 9979a2ee-6509-423b-8acb-a0d51a5711cd.
[2022-09-27 11:11:11.091] [editsessions] [info] Opening https://insiders.vscode.dev/github/amunger/draftday/blob/master-8632-13f539878c03/draftday-1/scraper/urlBuilder.js?editSessionId%3D9979a2ee-6509-423b-8acb-a0d51a5711cd%26continueOn%3D1#L10
[2022-09-27 11:11:16.465] [editsessions] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/editSessions/fa8df090-19b3-4d8a-8632-13f539878c03","status":404,"execution-id":"be52e916-94bf-4b6d-93d0-5d63bc93c108"}
[2022-09-27 11:11:16.465] [editsessions] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 404
    at T.request (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:813:127644)
    at async T.resolveResourceContent (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:813:120857)
    at async Hn.read (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2120:6981)
    at async I.readFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1054:54882)
    at async I.stat (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1054:55273)
    at async u.doResolveFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:15271)
    at async u.resolve (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:14864)
    at async u.validateReadFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:21350)
    at async u.doReadFileStream (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:19512)
    at async v.doRead (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2779:42787)
    at async v.readStream (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2779:42462)
    at async Rr.resolveFromFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2768:68671)
    at async vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2779:36966
[2022-09-27 11:11:41.099] [editsessions] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/editSessions/fa8df090-19b3-4d8a-8632-13f539878c03","status":404,"execution-id":"84c764d5-bd31-426d-8867-3c8ca0828672"}
[2022-09-27 11:11:41.125] [editsessions] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 404
    at T.request (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:813:127644)
    at async T.resolveResourceContent (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:813:120857)
    at async Hn.read (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2120:6981)
    at async I.readFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1054:54882)
    at async I.stat (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1054:55273)
    at async u.doResolveFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:15271)
    at async u.resolve (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:14864)
    at async u.validateReadFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:21350)
    at async u.doReadFileStream (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:608:19512)
    at async v.doRead (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2779:42787)
    at async v.readStream (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2779:42462)
    at async Rr.resolveFromFile (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2768:68671)
    at async vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2779:36966
```

I can see the edit session on the desktop (source), but not in insiders.vscode.dev (destination)

**Comment by amunger** [comment]
insiders.vscode.dev source logs:

```
[2022-09-27 11:13:33.076] [editsessions] [info] Storing edit session...
[2022-09-27 11:13:33.323] [editsessions] [info] Stored edit session with ref 6b00107d-e4a3-445c-8a7f-b40bd951f519.
[2022-09-27 11:13:33.387] [editsessions] [info] Opening vscode-insiders://ms-vscode.remote-repositories/open?url%3Dhttps%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-jupyter%2Ftree%2Fmain%26continueOn%3D1%26editSessionId%3D6b00107d-e4a3-445c-8a7f-b40bd951f519%26continueOn%3D1
```

no edit sessions on the desktop, but they show up in insiders.vscode.dev

**Comment by joyceerhl** [comment]
Just to confirm, did you turn on Edit Sessions with the same account in web and desktop? If you pick different accounts (e.g. Microsoft and GitHub), they're different identities and can't access edits from each other.

**Comment by amunger** [comment]
I was signed in with microsoft email, after struggling quite a bit to sign into github, it works successfully

**Comment by joyceerhl** [comment]
Got it, I'll rename this item to reflect that the Continue On flow should ideally make it hard to use the wrong identity when turning on Edit Sessions. @sandy081 how do we deal with this for settings sync, btw?

**Comment by sandy081** [comment]
Settings Sync shows last used identity like below

![image](https://user-images.githubusercontent.com/10746682/192710130-a6d526cb-5fa0-40cf-a465-6cd6f18dc35e.png)

**Comment by joyceerhl** [comment]
@sandy081 is that Last Used with Sync indicator machine specific or does it apply across machines?

**Comment by sandy081** [comment]
It is machine specific
