### ISSUE TITLE
Nothing happens after `Clone Repository Locally and Open on Desktop` when in RemoteHub repo on desktop

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162235]
I still see the problem. Nothing happens after `Clone Repository Locally and Open on Desktop`
(Remote Repositories v0.21.2022092801)

Dev tools show:

console.ts:137 [Extension Host] Git installation not found. (at console.<anonymous> (/home/aeschli/Downloads/code-insider-x64-1664343998/VSCode-linux-x64/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:142292))
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: command '_codespaces.setActiveRepository' not found (at console.<anonymous> (/home/aeschli/Downloads/code-insider-x64-1664343998/VSCode-linux-x64/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:142292))
console.ts:137 [Extension Host] stack trace: Error: command '_codespaces.setActiveRepository' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3532)
    at S.executeCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3414) (at console.<anonymous> (/home/aeschli/Downloads/code-insider-x64-1664343998/VSCode-linux-x64/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:142292))
log.ts:313   ERR command '_codespaces.setActiveRepository' not found: Error: command '_codespaces.setActiveRepository' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3532)
    at S.executeCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3414)

_Originally posted by @aeschli in https://github.com/microsoft/vscode/issues/123492#issuecomment-1261066541_

**Comment by joyceerhl** [comment]
@aeschli what does the `Git` output channel say for you and what is your repro setup? I see the following in the output channel when I attempt a clone without git in a local window on Windows over RDP: 

```
[2022-09-28T17:33:05.037Z] Log level: Trace
[2022-09-28T17:33:05.051Z] [info] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-09-28T17:33:05.072Z] [info] Validating found git in: C:\Program Files (x86)\Git\cmd\git.exe
[2022-09-28T17:33:05.074Z] [info] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-09-28T17:33:05.075Z] [info] Validating found git in: C:\Users\azureuser\AppData\Local\Programs\Git\cmd\git.exe
[2022-09-28T17:33:05.081Z] [info] GitProtocolHandler.handleUri(vscode-insiders://vscode.git/clone?url%3Dhttps%3A%2F%2Fgithub.com%2Fjoyceerhl%2Fjupyterlite%26editSessionId%3D048176ef-069b-454c-a8d8-6e61daf15c5b%26continueOn%3D1)
[2022-09-28T17:33:05.117Z] [error] Could not complete git clone operation as git installation was not found.
[2022-09-28T17:33:05.175Z] [warning] Git installation not found.

```

**Comment by aeschli** [comment]
I tested on Linux and to test, I renamed the git symbolic link: `sudo mv /usr/bin/git /usr/bin/git2`

[2022-09-28T19:50:20.696Z] Log level: Info
[2022-09-28T19:50:20.725Z] [info] Validating found git in: git
[2022-09-28T19:50:20.800Z] [warning] Git installation not found.

**Comment by joyceerhl** [comment]
Oh, are you using RemoteHub in desktop VS Code and then doing Clone Locally (as opposed to starting in the browser with vscode.dev/github.dev)?

**Comment by aeschli** [comment]
Yes.
Let me test the other scenario as well....

**Comment by aeschli** [comment]
I works nicely with vscode.dev. 
![image](https://user-images.githubusercontent.com/6461412/192880028-ff71e74a-e1eb-46e5-a2fa-15c42f2ac139.png)

**Comment by joyceerhl** [comment]
Thanks! I missed that we also need to handle this for desktop RemoteHub to desktop git clone, will use this issue to track that.
