### ISSUE TITLE
build: Egress is over the account limit.

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#162201]
```
[13:23:42] 'vscode-win32-x64-min-ci' errored after 11 s
[13:23:42] HTTPError: Response code 503 (Egress is over the account limit.)
    at EventEmitter.<anonymous> (D:\a\_work\1\s\node_modules\got\source\as-stream.js:35:24)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:552:15)
    at module.exports (D:\a\_work\1\s\node_modules\got\source\get-response.js:22:10)
    at ClientRequest.handleResponse (D:\a\_work\1\s\node_modules\got\source\request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:552:15)
    at ClientRequest.origin.emit (D:\a\_work\1\s\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:674:27)
error Command failed with exit code 1.
```

Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=186983&view=results

**Comment by deepak1556** [comment]
Another run https://dev.azure.com/monacotools/Monaco/_build/results?buildId=187176&view=results, slightly different error

```
RequestError: connect ETIMEDOUT 185.199.108.133:443
    at ClientRequest.<anonymous> (/Users/runner/work/1/s/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.origin.emit (/Users/runner/work/1/s/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
```

**Comment by joaomoreno** [comment]
This seems to be a GH problem. We're already passing along a PAT so we don't get rate limited. Not sure what can be done here.
