### ISSUE TITLE
Resolver error: Error: Connecting with SSH timed out

### ISSUE THREAD

**Issue by CarDiliki** [microsoft/vscode#162351]
[22:00:13.232] Log Level: 2
[22:00:13.234] remote-ssh@0.84.0
[22:00:13.234] win32 x64
[22:00:13.248] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2243617244696c696b69227d", attempt 1
[22:00:13.249] "remote.SSH.useLocalServer": false
[22:00:13.249] "remote.SSH.showLoginTerminal": true
[22:00:13.250] "remote.SSH.remotePlatform": {"local":"linux"}
[22:00:13.250] "remote.SSH.path": undefined
[22:00:13.250] "remote.SSH.configFile": C:\Users\11657\.ssh\config
[22:00:13.250] "remote.SSH.useFlock": true
[22:00:13.251] "remote.SSH.lockfilesInTmp": false
[22:00:13.251] "remote.SSH.localServerDownload": auto
[22:00:13.251] "remote.SSH.remoteServerListenOnSocket": false
[22:00:13.252] "remote.SSH.showLoginTerminal": true
[22:00:13.252] "remote.SSH.defaultExtensions": []
[22:00:13.252] "remote.SSH.loglevel": 2
[22:00:13.252] "remote.SSH.enableDynamicForwarding": true
[22:00:13.253] "remote.SSH.enableRemoteCommand": false
[22:00:13.253] "remote.SSH.serverPickPortsFromRange": {}
[22:00:13.253] "remote.SSH.serverInstallPath": {}
[22:00:13.296] SSH Resolver called for host: CarDiliki
[22:00:13.296] Setting up SSH remote "CarDiliki"
[22:00:13.324] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[22:00:13.329] Install and start server if needed
[22:00:17.437] Checking ssh with "ssh -V"
[22:00:17.506] > OpenSSH_for_Windows_8.1p1, LibreS
[22:00:17.507] > SL 3.0.2

[22:00:17.512] Using SSH config file "C:\Users\11657\.ssh\config"
[22:00:17.512] Running script with connection command: ssh -T -D 61622 -F "C:\Users\11657\.ssh\config" "CarDiliki" bash
[22:00:17.516] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[22:00:49.519] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\11657\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\11657\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[22:00:49.530] ------

[22:00:49.593] ------

[22:00:49.594] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2243617244696c696b69227d", attempt 2, (Reconnection)
[22:00:49.596] SSH Resolver called for host: CarDiliki
[22:00:49.597] Setting up SSH remote "CarDiliki"
[22:00:49.601] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[22:00:49.607] Install and start server if needed
[22:00:57.670] getPlatformForHost was canceled
[22:00:57.672] Resolver error: Error: Connecting was canceled
	at g.Canceled (c:\Users\11657\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585418)
	at c:\Users\11657\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:643820
	at async t.withShowDetailsEvent (c:\Users\11657\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:647224)
	at async t.resolve (c:\Users\11657\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:644958)
	at async c:\Users\11657\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:727082
[22:00:57.676] ------

[22:00:57.687] ------

[22:00:57.687] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2243617244696c696b69227d", attempt 3, (Reconnection)
[22:00:57.688] SSH Resolver called for host: CarDiliki
[22:00:57.688] Setting up SSH remote "CarDiliki"
[22:00:57.690] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[22:00:57.692] Install and start server if needed

**Comment by CarDiliki** [comment]
how to do aaaaaa
