### ISSUE TITLE
Error: object must be from this instance

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162341]
I clicked on this action in the merge editor dropdown:

![image](https://user-images.githubusercontent.com/900690/193036305-7cbb6161-67b1-4146-b228-18f807294290.png)

```
Error: object must be from this instance
    at MergeEditorModel.getState (mergeEditorModel.js:287:23)
    at Derived.computeFn (conflictActions.js:65:47)
    at Derived.get (derived.js:75:39)
    at Derived.endUpdate (derived.js:126:26)
    at TransactionImpl.finish (base.js:100:26)
    at transaction (base.js:65:16)
    at ObservableValue.set (base.js:123:17)
    at MergeEditor.toggleShowNonConflictingChanges (mergeEditor.js:569:44)
    at ShowNonConflictingChanges.run (commands.js:193:34)
    at handler (actions.js:376:52)
    at InstantiationService.invokeFunction (instantiationService.js:46:24)
    at CommandService._tryExecuteCommand (commandService.js:81:59)
    at CommandService.executeCommand (commandService.js:50:33)
    at MenuItemAction.run (actions.js:317:41)
    at EditorCommandsContextActionRunner.runAction (actions.js:114:26)
    at EditorCommandsContextActionRunner.run (actions.js:106:28)
    at EditorCommandsContextActionRunner.run (titleControl.js:34:26)
    at NativeContextMenuService.runAction (contextmenuService.js:196:43)
    at Object.click (contextmenuService.js:174:30)
    at EventEmitter.onClickChannelHandler (contextmenu.js:16:25)
    at Object.onceWrapper (node:events:646:26)
    at EventEmitter.emit (node:events:526:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:746)
```

**Comment by hediet** [comment]
Fixed in todays main.
