### ISSUE TITLE
The HTML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by rwatts3** [Microsoft/vscode#16237]
- VSCode Version: 1.8.0-insider
- OS Version: Win 7

Steps to Reproduce:

1. Open lengthy html file with divs and inline script tags.
2. Attempt to write code within first couple key strokes intellisense fails and the titled error appears.

**Comment by chrmarti** [comment]
Does this occur with any 'lengthy' html file or just one? Could you attach one?

What does the console in the devtools show (Help > Toggle Developer Tools)?

**Comment by rwatts3** [comment]
Sorry I can't attach code as it is corporate policy.  However its any file that I open which contains script blocks. Handlebars like syntax

**Comment by aeschli** [comment]
What version of VSCode? Likely this was fixed by a603e8a.

**Comment by rwatts3** [comment]
Yes for the most part that did fix the issue.  But the error comes back
when dealing with the larger file.  Ill test more but I'm not sure if the
size of the file has anything to do with the error.  Its hard to determine
the actual cause.

**Comment by aeschli** [comment]
Closing for now. Please reopen with details

**Comment by Alonski** [comment]
Hey I am also getting this.
In Handlebars templates with latest Insiders Build
![image](https://cloud.githubusercontent.com/assets/452199/23498502/a9f538ec-ff30-11e6-99de-9ef1d60c6f75.png)
The file is a .hbs file with 66 lines of code
Log from HTML Language Server Console
`module.js:457
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\html\server\out\modes\javascriptMode.js:9:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 10:08:16 AM] Connection to server got closed. Server will restart.
module.js:457
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\html\server\out\modes\javascriptMode.js:9:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 10:08:18 AM] Connection to server got closed. Server will restart.
module.js:457
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\html\server\out\modes\javascriptMode.js:9:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 10:08:19 AM] Connection to server got closed. Server will restart.
module.js:457
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\html\server\out\modes\javascriptMode.js:9:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 10:08:21 AM] Connection to server got closed. Server will restart.
module.js:457
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\html\server\out\modes\javascriptMode.js:9:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Error - 10:08:23 AM] Connection to server got closed. Server will not be restarted.
`

Dev Tools
![image](https://cloud.githubusercontent.com/assets/452199/23498627/302fd28c-ff31-11e6-936f-a92da4555f59.png)

**Comment by aeschli** [comment]
@Alonski Thats unrelated. I created https://github.com/Microsoft/vscode/issues/21743

**Comment by Alonski** [comment]
Thanks!
