### ISSUE TITLE
Error after disabling settings sync

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#162464]
Was verifying an issue
- Disabled settings sync
- Reenabled it but on the Stable service
- Changed profiles a few times
- Disabled Settings sync

Got an error poupup, here is the stack from the window log

```
[2022-09-30 12:06:10.032] [renderer1] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: h.with is not a function
    at u.C [as toUserDataSyncError] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:808:40284)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:110971
    at async w.getRemoteSyncResourceHandles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:112541)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:49047
    at async Promise.all (index 0)
    at async N.getRoots (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:47536)
    at async N.getChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:47035)
    at async Object.getChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3018:7181)
[2022-09-30 12:06:10.053] [renderer1] [error] h.with is not a function: Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: h.with is not a function
    at u.C [as toUserDataSyncError] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:808:40284)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:110971
    at async w.getRemoteSyncResourceHandles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:112541)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:49047
    at async Promise.all (index 0)
    at async N.getRoots (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:47536)
    at async N.getChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:47035)
    at async Object.getChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3018:7181)
[2022-09-30 12:06:10.233] [renderer1] [error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: h.with is not a function
    at u.C [as toUserDataSyncError] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:808:40284)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:110971
    at async w.getRemoteSyncResourceHandles (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:112541)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:49047
    at async Promise.all (index 0)
    at async N.getRoots (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:47536)
    at async N.getChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3145:47035)
    at async Object.getChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3018:7181)
```

```
[2022-09-30 12:06:05.402] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-09-30 12:06:05.402] [settingssync] [info] Sync started.
[2022-09-30 12:06:05.501] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-09-30 12:06:05.538] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-09-30 12:06:05.548] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-09-30 12:06:05.554] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-09-30 12:06:05.809] [settingssync] [info] GlobalState: Updated remote ui state
[2022-09-30 12:06:05.874] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-09-30 12:06:06.061] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-09-30 12:06:06.066] [settingssync] [info] Sync done. Took 669ms
[2022-09-30 12:06:10.014] [settingssync] [info] Auto Sync: Disabled.
[2022-09-30 12:06:10.014] [settingssync] [info] Auto Sync: Stopped
[2022-09-30 12:06:10.027] [settingssync] [info] Did reset the local sync state.
```

**Comment by sandy081** [comment]
Do you have settings sync views enabled?

**Comment by sandy081** [comment]
@roblourens Can you please verify this on latest insiders?
