### ISSUE TITLE
Empty signature box and TypeError exception in console

### ISSUE THREAD

**Issue by wiz** [Microsoft/vscode#16257]
- VSCode Version: 1.7.2
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Ask a language server for signature help
2. LS emits following JSON:
    ```json
    {
    "result": {
        "signatures": [
        {
            "documentation": "param? I hardly knew it.",
            "parameters": [
            {
                "documentation": "something",
                "label": "this"
            },
            {
                "label": "that"
            }
            ],
            "label": "param"
        }
        ]
    },
    "jsonrpc": "2.0",
    "id": 13
    }
    ```
3. Editor shows a tiny empty box hovering, without any signatures

There's an exception logged in console:
```
workbench.main.js:126 Cannot read property 'parameters' of undefined: TypeError: Cannot read property 'parameters' of undefined
    at e.render (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:72:8261)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:72:6011
    at e.invoke (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29:22801)
    at e.fire (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:1364)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:72:4479
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:10217)
    at Object.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:13795)
    at _run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:15623)
    at _completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:15064)
    at then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:17056)
```

Offending code in workbench.main.js (unminified):

```javascript
                    this.docs.innerHTML = "";
                    var t = this.hints.signatures[this.currentSignature]
                      , i = r.append(this.signature, b(".code"))
                      , o = t.parameters.length > 0
                      , a = this.editor.getConfiguration().fontInfo;
```

`this.currentSignature` is undefined as per [SignatureHelp result](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#signature-help-request) (`activeSignature` is optional there).

**Comment by chrmarti** [comment]
Related to #16256? @joaomoreno You were the last to change that line, not sure if that introduced the issue.

**Comment by joaomoreno** [comment]
@dbaeumer [`activeSignature`] isn't optional in our API.

**Comment by dbaeumer** [comment]
@wiz   you need to provide an `activeSignature` and an `activeParameter`. I will update the protocol.

**Comment by wiz** [comment]
Thanks, good to know.
