### ISSUE TITLE
After update of Insiders version, "Error: cannot load entry script from outisde the application"

### ISSUE THREAD

**Issue by rdbisme** [microsoft/vscode#162533]
Type: <b>Bug</b>

After recently I've updated to latest Insiders, nothing works anymore. I tried resetting from scratch, disabling all extensions and removing all custom settings, but nothing works. I can't even enable settings sync. 
The following results are form basically a brand new insider version (installed using `scoop`)

<details>
<summary> Window logs </summary>

```
[2022-10-02 22:53:30.157] [renderer1] [info] Electron sandbox mode is enabled!
[2022-10-02 22:53:30.582] [renderer1] [error] Error received from starting extension host (kind: LocalProcess)
[2022-10-02 22:53:30.582] [renderer1] [error] ["Error: Cannot load entry script from outisde the application.","    at new UtilityProcess (node:electron/js2c/browser_init:153:1206)","    at a.start (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:80:50098)","    at Ut.start (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:80:46042)","    at Object.call (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:24:8334)","    at l.onPromise (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:23:5812)","    at l.onRawMessage (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:23:5207)","    at C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:23:4499","    at y.invoke (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:145)","    at S.deliver (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:2269)","    at C.fire (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:1847)","    at C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:17:19380","    at y.invoke (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:145)","    at S.deliver (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:2269)","    at C.fire (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:1847)","    at C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:17:19564","    at y.invoke (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:145)","    at S.deliver (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:2269)","    at C.fire (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:19:1847)","    at Y (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:17:21502)","    at IpcMainImpl.u (C:\\Users\\ruben\\scoop\\apps\\vscode-insiders\\nightly-20221002\\resources\\app\\out\\vs\\code\\electron-main\\main.js:16:50233)","    at IpcMainImpl.emit (node:events:526:28)","    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:169:11345)","    at EventEmitter.emit (node:events:526:28)"]
[2022-10-02 22:53:36.010] [renderer1] [error] Timed out waiting for authentication provider to register
[2022-10-02 22:53:36.011] [renderer1] [warning] Settings Sync: Accounts are not initialized
```
</details>

<details>
<summary>Settings sync logs</summary>

```
[2022-10-02 22:53:30.955] [settingssync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2022-10-02 22:53:30.955] [settingssync] [info] Auto Sync is disabled.
```
</details>

VS Code version: Code - Insiders 1.72.0-insider (bcb6c9b7e0e795bdf65ea440025d204060e4bfc8, 2022-09-30T10:53:16.316Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30568093
i5d37513:30580093
vscccc:30564267
pyindex848cf:30577859

```

</details>

PS: there's a typo in the log text *outisde* instead of **outside**

Steps to reproduce: 
1. Open `vscode`.

**Comment by deepak1556** [comment]
Thanks for creating the issue, please set the following setting `"window.experimental.useSandbox": false` until this issue is resolved.

**Comment by rdbisme** [comment]
> "window.experimental.useSandbox": false

Thanks for answer. I did it in User settings, but I'm still experiencing the same problem :(

**Comment by rdbisme** [comment]
Hello @deepak1556, I'm on the latest insider, but I'm still experiencing the same problem: 

```
2022-11-03 20:04:43.893 [error] Error received from starting extension host (kind: LocalProcess)
2022-11-03 20:04:43.893 [error] Error: Cannot load entry script from outisde the application.
    at new UtilityProcess (node:electron/js2c/browser_init:153:1206)
    at l.start (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:79:50754)
    at Ut.start (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:79:46695)
    at Object.call (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:25:5837)
    at a.onPromise (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:23:5824)
    at a.onRawMessage (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:23:5214)
    at C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:23:4504
    at w.invoke (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:145)
    at v.deliver (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:2270)
    at g.fire (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:1848)
    at C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:17:19601
    at w.invoke (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:145)
    at v.deliver (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:2270)
    at g.fire (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:1848)
    at C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:17:19787
    at w.invoke (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:145)
    at v.deliver (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:2270)
    at g.fire (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:19:1848)
    at B (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:17:21726)
    at IpcMainImpl.f (C:\Users\ruben\scoop\apps\vscode-insiders\nightly-20221103\resources\app\out\vs\code\electron-main\main.js:16:57956)
    at IpcMainImpl.emit (node:events:538:35)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:169:11345)
    at EventEmitter.emit (node:events:526:28)
2022-11-03 20:04:44.131 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
2022-11-03 20:04:46.390 [info] [perf] Render performance baseline is 22ms
2022-11-03 20:04:49.451 [error] Timed out waiting for authentication provider to register
2022-11-03 20:04:49.452 [warning] Settings Sync: Accounts are not initialized
2022-11-03 20:05:16.154 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-11-03 20:05:16.155 [warning] SettingsEditor2: Settings not included in settingsLayout.ts: application.experimental.rendererProfiling
2022-11-03 20:05:31.273 [error] this._core._renderService?._onIntersectionChange is not a function: TypeError: this._core._renderService?._onIntersectionChange is not a function
    at zi.forceUnpause (vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:1971:27069)
    at Hi._resizeNow (vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:3121:3652)
    at Hi._resize (vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:3121:2736)
    at vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:6:42864
2022-11-03 20:06:02.667 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-11-03 20:06:14.349 [error] command 'remote-wsl.newWindow' not found: Error: command 'remote-wsl.newWindow' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:1723:3532)
    at S.executeCommand (vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:1723:3414)
2022-11-03 20:07:15.996 [error] command 'remote-wsl.newWindow' not found: Error: command 'remote-wsl.newWindow' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:1723:3532)
    at S.executeCommand (vscode-file://vscode-app/c:/Users/ruben/scoop/apps/vscode-insiders/nightly-20221103/resources/app/out/vs/workbench/workbench.desktop.main.js:1723:3414)
```

**Comment by deepak1556** [comment]
I am not familiar with how scoop maintains the symlink but from the error it looks like you are still using an older version of the runtime. Can you try uninstalling the insiders and try again. Thanks!

**Comment by rdbisme** [comment]
Uninstalling / reinstalling fixed the problems. Thanks @deepak1556
