### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached, watch '/snap/code'

### ISSUE THREAD

**Issue by jesusjimsa** [microsoft/vscode#162565]
Does this issue occur when all extensions are disabled?: It doesn't open, I can't disable them.

- VS Code Version: 1.71.2
- OS Version: Ubuntu 22.04.1 LTS

Steps to Reproduce:

1. Try to open VS Code with the icon (fails).
2. Try to open with command `code --verbose`. Fails with this output:
```
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
(code:3736668): Gtk-WARNING **: 11:52:05.277: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name
(code:3736668): Gtk-WARNING **: 11:52:05.281: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name
(code:3736668): Gtk-WARNING **: 11:52:05.282: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 11:52:05.314: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:52:05.316: Failed to load module "canberra-gtk-module"
[3736668:1003/115205.376656:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[3736987:1003/115205.378704:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3736987:1003/115205.378791:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3736987:1003/115205.378829:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3736987:1003/115205.379094:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3736987:1003/115205.379166:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3736987:1003/115205.379236:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3736987:1003/115205.379298:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[3736987:1003/115205.380375:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[3737024:1003/115205.403017:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737024:1003/115205.403140:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737024:1003/115205.403176:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3737024:1003/115205.403435:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737024:1003/115205.403484:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737024:1003/115205.403519:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3737024:1003/115205.403549:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[3737024:1003/115205.404589:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[3737076:1003/115205.445854:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737076:1003/115205.445939:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737076:1003/115205.445968:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3737076:1003/115205.446228:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737076:1003/115205.446277:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737076:1003/115205.446308:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3737076:1003/115205.446333:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[3737076:1003/115205.447316:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[main 2022-10-03T10:52:05.451Z] [File Watcher (node.js)] Request to start watching: /home/jesusjimsa/.config/Code/User (excludes: <none>, includes: <all>),/home/jesusjimsa/.config/Code/User/settings.json (excludes: <none>, includes: <all>)
[3737098:1003/115205.460453:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737098:1003/115205.460562:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737098:1003/115205.460605:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3737098:1003/115205.460995:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737098:1003/115205.461053:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737098:1003/115205.461096:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3737098:1003/115205.461130:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[3737098:1003/115205.462324:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[main 2022-10-03T10:52:05.471Z] Starting VS Code
[main 2022-10-03T10:52:05.471Z] from: /snap/code/108/usr/share/code/resources/app
[main 2022-10-03T10:52:05.471Z] args: {
  _: [],
  diff: false,
  merge: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '779203a6-106b-4900-902f-f4c74b2ed189',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  '__enable-file-policy': false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  'profile-temp': false,
  logsPath: '/home/jesusjimsa/.config/Code/logs/20221003T115205'
}
[main 2022-10-03T10:52:05.473Z] Resolving machine identifier...
[main 2022-10-03T10:52:05.474Z] Resolved machine identifier: 86c58d2618a3125c1aa3089763407c010b28dda1b583c68ef4ed84157ac65809
[main 2022-10-03T10:52:05.474Z] Main->SharedProcess#connect
[main 2022-10-03T10:52:05.479Z] [File Watcher (node.js)] Failed to watch /home/jesusjimsa/.config/Code/User for changes using fs.watch() (Error: ENOSPC: System limit for number of file watchers reached, watch '/home/jesusjimsa/.config/Code/User')
[main 2022-10-03T10:52:05.480Z] [File Watcher (node.js)] Failed to watch /home/jesusjimsa/.config/Code/User/settings.json for changes using fs.watch() (Error: ENOSPC: System limit for number of file watchers reached, watch '/home/jesusjimsa/.config/Code/User/settings.json')
[main 2022-10-03T10:52:05.483Z] StorageMainService: creating application storage
[3737132:1003/115205.484233:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737132:1003/115205.484323:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737132:1003/115205.484355:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3737132:1003/115205.484633:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737132:1003/115205.484682:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737132:1003/115205.484723:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3737132:1003/115205.484750:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[main 2022-10-03T10:52:05.485Z] update#setState idle
[3737132:1003/115205.485868:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[main 2022-10-03T10:52:05.486Z] Error: ENOSPC: System limit for number of file watchers reached, watch '/snap/code'
    at FSWatcher.<computed> (node:internal/original-fs/watchers:244:19)
    at watch (node:original-fs:2251:34)
    at new g (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:74:29529)
    at C._createInstance (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:1346)
    at C._createServiceInstance (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:3757)
    at C._createServiceInstanceWithOwner (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:3267)
    at C._createAndCacheServiceInstance (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:2942)
    at C._safeCreateAndCacheServiceInstance (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:2140)
    at C._getOrCreateServiceInstance (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:1861)
    at Object.get (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:455)
    at Ct.initChannels (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:77:70922)
    at /snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:77:65013
    at C.invokeFunction (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:325)
    at Ct.startup (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:77:64989)
    at async Me.startup (/snap/code/108/usr/share/code/resources/app/out/vs/code/electron-main/main.js:79:5842)
[main 2022-10-03T10:52:05.487Z] Lifecycle#kill()
[main 2022-10-03T10:52:05.487Z] Lifecycle#onWillShutdown.fire()
[main 2022-10-03T10:52:05.488Z] storageMainService#onWillShutdown()
[main 2022-10-03T10:52:05.490Z] [File Watcher (node.js)] Request to stop watching: /home/jesusjimsa/.config/Code/User,/home/jesusjimsa/.config/Code/User/settings.json
[main 2022-10-03T10:52:05.490Z] [File Watcher (node.js)] stopping file watcher on /home/jesusjimsa/.config/Code/User
[main 2022-10-03T10:52:05.490Z] [File Watcher (node.js)] stopping file watcher on /home/jesusjimsa/.config/Code/User/settings.json
[main 2022-10-03T10:52:05.490Z] StorageMainService: closed application storage
[3737150:1003/115205.498145:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737150:1003/115205.498232:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737150:1003/115205.498274:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3737150:1003/115205.498559:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737150:1003/115205.498599:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libGLdispatch.so.0)
[3737150:1003/115205.498631:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3737150:1003/115205.498659:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[3737150:1003/115205.499758:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```

I have tried increasing the number of watches, but that didn't help:
```
~$ cat /proc/sys/fs/inotify/max_user_watches
524288
```

It will only open after I restart the computer.

**Comment by jesusjimsa** [comment]
Opened with vscode (after restarting my computer) in #162567

**Comment by Juggern4ut** [comment]
You closed this issue but I see no solution. I have the exact same problem. What did you do to solve it?
