### ISSUE TITLE
All builtin extensions fail to install on github.dev

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162802]
I am using github.dev.

I am not able to install any extensions. This also means I do not have any extensions installed. Opening the list of extensions only reveals recommended and popular extensions.

This is the Log (Window). All the errors and warnings seem to start to come from a missing "package.json". I have no idea what it is referring to or how to fix it.
```
[2022-09-01 09:07:12.615] [window] [warning] Ignoring the error while validating workspace folder vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev - No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev'
[2022-09-01 09:07:15.011] [window] [error] ENOPRO: No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev'
    at h.withProvider (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:12467)
    at async h.doWatch (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:26229)
    at async https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:26095
[2022-09-01 09:07:17.481] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.492] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.498] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.502] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.506] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.514] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.518] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.526] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.530] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.534] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.539] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.541] [window] [info] Ignoring additional builtin extension github.vscode-pull-request-github because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.48.1/extension'. Failed to fetch
[2022-09-01 09:07:17.545] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.554] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.558] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.565] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:07:17.569] [window] [info] Ignoring additional builtin extension ms-vscode.anycode because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode/0.0.69/extension'. Failed to fetch
[2022-09-01 09:07:17.572] [window] [info] Ignoring additional builtin extension github.github-vscode-theme because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/github-vscode-theme/6.3.2/extension'. Failed to fetch
[2022-09-01 09:07:17.580] [window] [info] Ignoring additional builtin extension github.codespaces because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/codespaces/1.10.4/extension'. Failed to fetch
[2022-09-01 09:07:17.584] [window] [info] Ignoring additional builtin extension ms-vscode.remote-repositories because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
[2022-09-01 09:07:17.589] [window] [info] Ignoring additional builtin extension github.remotehub because there is an error while converting it into web extension Cannot find the package.json from the location 'https://github.vscode-unpkg.net/GitHub/remotehub/0.40.0/extension'. Failed to fetch
[2022-09-01 09:07:17.594] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-kotlin because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-kotlin/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.598] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-cpp because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-cpp/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.604] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-java because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-java/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.610] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-python because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-python/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.613] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-php because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-php/0.0.6/extension'. Failed to fetch
[2022-09-01 09:07:17.619] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-rust because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-rust/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.624] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-go because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-go/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.629] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-c-sharp because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-c-sharp/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:17.638] [window] [info] Ignoring additional builtin extension ms-vscode.anycode-typescript because there is an error while converting it into web extension Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/anycode-typescript/0.0.5/extension'. Failed to fetch
[2022-09-01 09:07:23.254] [window] [error] Error while registering log channel file:///20220901T090712/ptyhost.log Timed out while waiting for file to be created
[2022-09-01 09:09:51.679] [window] [info] Getting Manifest... github.remotehub
[2022-09-01 09:09:51.685] [window] [info] Installing extension: github.remotehub
[2022-09-01 09:09:52.149] [window] [info] Getting Manifest... ms-vscode.remote-repositories
[2022-09-01 09:09:52.665] [window] [info] Installing extension: ms-vscode.remote-repositories
[2022-09-01 09:09:52.755] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:09:52.864] [window] [error] Error while installing the extension: ms-vscode.remote-repositories
[2022-09-01 09:09:52.868] [window] [error] Failed to install extension. github.remotehub
[2022-09-01 09:09:52.872] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:52.876] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:52.880] [window] [error] Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:56.836] [window] [info] Getting Manifest... github.remotehub
[2022-09-01 09:09:57.308] [window] [info] Installing extension: github.remotehub
[2022-09-01 09:09:57.946] [window] [info] Getting Manifest... ms-vscode.remote-repositories
[2022-09-01 09:09:58.407] [window] [info] Installing extension: ms-vscode.remote-repositories
[2022-09-01 09:09:58.465] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:09:58.592] [window] [error] Error while installing the extension: ms-vscode.remote-repositories
[2022-09-01 09:09:58.632] [window] [error] Failed to install extension. github.remotehub
[2022-09-01 09:09:58.652] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:58.656] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:09:58.661] [window] [error] Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.19.2022081801/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:10:01.641] [window] [info] Getting Manifest... github.remotehub
[2022-09-01 09:10:01.646] [window] [info] Installing extension: github.remotehub
[2022-09-01 09:10:02.240] [window] [info] Getting Manifest... ms-vscode.remote-repositories
[2022-09-01 09:10:02.248] [window] [info] Installing extension: ms-vscode.remote-repositories
[2022-09-01 09:10:02.318] [window] [warning] Error while fetching extension resources list Failed to fetch
[2022-09-01 09:10:02.452] [window] [error] Error while installing the extension: ms-vscode.remote-repositories
[2022-09-01 09:10:02.456] [window] [error] Failed to install extension. github.remotehub
[2022-09-01 09:10:02.459] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:10:02.463] [window] [error] Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:10:02.469] [window] [error] Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.18.0/extension'. Failed to fetch
    at U.toWebExtension (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:118335)
    at async U.addExtensionFromGallery (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3197:115106)
    at async a.doRun (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:3198:6585)
[2022-09-01 09:21:28.283] [window] [error] No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev/.vscode': ENOPRO: No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/github/dev/.vscode'
    at h.withProvider (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:12467)
    at async h.exists (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:599:15062)
    at async https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:2322:7642
    at async Promise.all (index 0)
    at async D._initWorkspaceFolderSnippets (https://main.vscode-cdn.net/stable/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/workbench.web.main.js:2322:7807)

```

_Originally posted by @Koziah-Sylvester in https://github.com/microsoft/vscode/issues/157109#issuecomment-1233925938_

**Comment by joyceerhl** [comment]
@Koziah-Sylvester sorry for the delayed follow up on this. It looks like all the builtin extensions we rely on to deliver the github.dev experience are failing to be fetched from our CDN. Can you provide some details on your network setup, e.g. do you have a network proxy configured?

**Comment by Koziah-Sylvester** [comment]
Good evening. This was an internal issue with our network security. Very sorry for the hassle. 

We have mimecast setup on our network and it protects users from insecure websites and links for example this one: https://protect-eu.mimecast.com/s/2i02CM9Exi2ZOZEIwLnft?domain=github.com

Since I am a new employee my mimecast was not setup correctly and I was having internet related issue throughout the month. However, this problem seems to be fixed now. I am able to access our code.

Thank you very much for your help.
![image](https://user-images.githubusercontent.com/112087322/194368060-6f2b92ce-78fb-4e50-bd63-44ccedff5fa1.png)

**Comment by joyceerhl** [comment]
Glad to hear and I will close this issue since you were able to get unblocked --again apologies for the delayed response!
