### ISSUE TITLE
Error Seen when Syncing Settings in VS Code

### ISSUE THREAD

**Issue by martinpeck** [microsoft/vscode#162825]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2 (Universal)
- OS Version: MacOS 12.6

I had noticed that some of my synced settings had been lost (specifically related to dotfiles). On investigation, I looked at the logs for sync and on at least one of my devices I'm seeing intermittent errors. The result is that settings sync is not reliable (sometimes works, sometimes doesn't).

I see the errors on one particular machine. ~~On my other laptop (same version of VS Code, same version of MacOS) I don't see these errors in the logs~~. **UPDATE**: I see this error on both devices (I hadn't waited long enough on the 2nd device to see one occur)

I use github for settings sync

The following sync logs included some logs from before and after the error, for context. Logs taken from an instance of VS Code launched with `code --disable-extensions`:

```
[2022-10-06 10:26:12.349] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-06 10:26:12.446] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-10-06 10:26:12.450] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-10-06 10:26:12.453] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-10-06 10:26:12.455] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-10-06 10:26:12.461] [settingssync] [info] GlobalState: No changes found during synchronizing ui state.
[2022-10-06 10:26:12.560] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-10-06 10:26:12.561] [settingssync] [info] Sync done. Took 125ms
[2022-10-06 10:26:35.201] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-06 10:28:29.068] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-10-06 10:28:29.073] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-10-06 10:28:29.077] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-10-06 10:28:29.080] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-10-06 10:28:29.092] [settingssync] [info] GlobalState: No changes found during synchronizing ui state.
[2022-10-06 10:28:29.197] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-10-06 10:28:29.198] [settingssync] [info] Sync done. Took 141ms
[2022-10-06 10:29:06.809] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-06 10:31:16.824] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2022-10-06 10:31:16.824] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at R.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:146108)
    at async R.manifest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:143819)
    at async r.createSyncTask (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:119470)
    at async r.doSync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:115960)
[2022-10-06 10:31:16.825] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at R.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:146108)
    at async R.manifest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:143819)
    at async r.createSyncTask (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:119470)
    at async r.doSync (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:115960)
[2022-10-06 10:34:32.013] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-06 10:34:32.331] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-10-06 10:34:32.338] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-10-06 10:34:32.343] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-10-06 10:34:32.347] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-10-06 10:34:32.683] [settingssync] [info] GlobalState: Updated remote ui state
[2022-10-06 10:34:32.705] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-10-06 10:34:32.811] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-10-06 10:34:32.813] [settingssync] [info] Sync done. Took 499ms
[2022-10-06 10:35:06.422] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-06 10:35:06.665] [settingssync] [info] Settings: No changes found during synchronizing settings.
[2022-10-06 10:35:06.671] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-10-06 10:35:06.675] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-10-06 10:35:06.678] [settingssync] [info] Tasks: No changes found during synchronizing tasks.
[2022-10-06 10:35:07.004] [settingssync] [info] GlobalState: Updated remote ui state
[2022-10-06 10:35:07.026] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-10-06 10:35:07.142] [settingssync] [info] Extensions: No changes found during synchronizing extensions.
[2022-10-06 10:35:07.143] [settingssync] [info] Sync done. Took 510ms
```

VS Code Version information:

```
Version: 1.71.2 (Universal)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (3 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

**Comment by martinpeck** [comment]
I had settings for Remote Containers, related to dotfiles. These had been set up, and were working, on my device.
They've since disappeared, and I had suspected that this error was the cause, or that another device had over-written these settings (back to being unset) because of this sync error.

Is there any way to see the stored settings against my profile, and to see the history of their values?

**Comment by martinpeck** [comment]
Specifically: 

remote.containers.dotfiles.installCommand
remote.containers.dotfiles.repository
remote.containers.dotfiles.targetPath

**Comment by sandy081** [comment]
> Is there any way to see the stored settings against my profile, and to see the history of their values?

Yes. You can browse the history/activity of your data on the server using the command `Settings Sync: Show Synced Data`. There using the **Sync Activity (Remote)** view you can see which machine has updated/removed these settings.

**Comment by martinpeck** [comment]
When I try this, I get errors in the UI that look very similar (Connection refused for the request) and none of the nodes in the tree view expand.

I see spinners...

![image](https://user-images.githubusercontent.com/1524451/194342867-4f76f283-a4ef-4b1e-ab15-08f8dc1075a4.png)

... and errors...

![image](https://user-images.githubusercontent.com/1524451/194342911-5ad0b962-7243-4fa4-bdcd-cf195d62736b.png)

**Comment by martinpeck** [comment]
The expanded error: 
![image](https://user-images.githubusercontent.com/1524451/194343041-28119b90-9ea5-4bdb-8dd7-b48618142cc2.png)

**Comment by martinpeck** [comment]
FYI after a restart the connection errors and spinners in the UI are now resolved.

Thanks, @sandy081 , for the guidance on where to look at the settings and which machine contributed to the issue. I've done some digging and will keep an eye on it.

I'm happy to help if you want to track down why I was seeing the UI issues mentioned above (you're welcome to contact me via my microsoft alias), but if you'd like to close this for now that's also fine with me.

**Comment by sandy081** [comment]
These are network issues, probably got resolved after restart. Please reopen if you see them again
