### ISSUE TITLE
Extension sync not working in vscode server web 

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#163005]
- VS Code Version:  stable from sources

Regression in current september release

Steps to Reproduce:

1. Run server, open workbench in browser
2. Enable settings sync
3. Install some extension
4. Check remote server logs

```
[2022-10-07 21:19:32.337] [remoteagent] [error] ENOPRO: No file system provider found for resource 'vscode-userdata:/User/extensions.json'
    at f.withProvider (/ide/out/vs/server/node/server.main.js:87:18410)
    at async f.withReadProvider (/ide/out/vs/server/node/server.main.js:87:18533)
    at async f.readFile (/ide/out/vs/server/node/server.main.js:87:23097)
    at async Object.factory (/ide/out/vs/server/node/server.main.js:89:1822)
```

cc @sandy081

**Comment by MEDVEDEFFIZZAMUZZIC1996** [comment]
> 
> 
> - VS Code Version:  stable from sources
> 
> Regression in current september release
> 
> Steps to Reproduce:
> 
> 1. Run server, open workbench in browser
> 2. Enable settings sync
> 3. Install some extension
> 4. Check remote server logs
> 
> ```
> [2022-10-07 21:19:32.337] [remoteagent] [error] ENOPRO: No file system provider found for resource 'vscode-userdata:/User/extensions.json'
>     at f.withProvider (/ide/out/vs/server/node/server.main.js:87:18410)
>     at async f.withReadProvider (/ide/out/vs/server/node/server.main.js:87:18533)
>     at async f.readFile (/ide/out/vs/server/node/server.main.js:87:23097)
>     at async Object.factory (/ide/out/vs/server/node/server.main.js:89:1822)
> ```
> 
> cc @sandy081 
>
