### ISSUE TITLE
Resuming edit session keeps loading

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#163155]
![image](https://user-images.githubusercontent.com/10746682/194832194-e5c07422-96d0-4c4d-9796-809e8a21be27.png)

**Comment by sandy081** [comment]
And then it failed with following error

```
[2022-10-10 11:06:09.675] [editsessions] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/editSessions/latest'.
    at T.request (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:125676)
    at async T.readResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:815:122114)
    at async Hn.read (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2123:7148)
    at async Pr.resumeEditSession (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3097:131764)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3097:126858
[2022-10-10 11:06:09.676] [editsessions] [info] Aborting resuming edit session as no edit session content is available to be applied from ref undefined.
```

I wonder why the session is being resumed - I am on Desktop, opened a repo (distro) and I do not do any action to resume/store the session

**Comment by Tyriar** [comment]
> are we aware of any connectivity issues to the server?

Yes, there were some issues that have since been fixed

**Comment by joyceerhl** [comment]
Closing as I believe this should be addressed with the improvements to the settings sync server that @Tyriar mentions.
