### ISSUE TITLE
Fail to etablish a ssh connextion after a reload done while a three is loading 

### ISSUE THREAD

**Issue by colas31** [microsoft/vscode#163427]
Type: <b>Bug</b>

Hello,

I notice an issue with the new version of VSCode 1.72.1.
Step to reproduce:
- Connect VSCode to an host
- Install private extension manager + configure it
- Focus on the private extension manager view
- while the view is loading, run the command reload the windows

**VSCode fails to reconnect to the host. See logs below**

I'm using the latest version of "private extension manager" released 10 month ago

Running the same step on the previous version of VSCode 1.71.2 doesn't generate the same issue. 

VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:22:48.346Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cds|ama|1.0.22
vscode-cds-installer|ama|1.0.92
private-extension-manager|gar|1.8.0
private-extension-manager-remote-helper|gar|1.8.0
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0

</details>

logs
`[14:40:27.308] Log Level: 2
[14:40:27.309] remote-ssh@0.90.1
[14:40:27.310] win32 x64
[14:40:27.310] SSH Resolver called for "ssh-remote+dev6425", attempt 1
[14:40:27.311] "remote.SSH.useLocalServer": false
[14:40:27.311] "remote.SSH.showLoginTerminal": false
[14:40:27.311] "remote.SSH.remotePlatform": {"dev6425":"linux"}
[14:40:27.311] "remote.SSH.path": undefined
[14:40:27.312] "remote.SSH.configFile": undefined
[14:40:27.312] "remote.SSH.useFlock": true
[14:40:27.312] "remote.SSH.lockfilesInTmp": true
[14:40:27.312] "remote.SSH.localServerDownload": auto
[14:40:27.312] "remote.SSH.remoteServerListenOnSocket": false
[14:40:27.312] "remote.SSH.showLoginTerminal": false
[14:40:27.312] "remote.SSH.defaultExtensions": ["colas.post-startup-hook"]
[14:40:27.312] "remote.SSH.loglevel": 2
[14:40:27.312] "remote.SSH.enableDynamicForwarding": true
[14:40:27.312] "remote.SSH.enableRemoteCommand": false
[14:40:27.312] "remote.SSH.serverPickPortsFromRange": {}
[14:40:27.312] "remote.SSH.serverInstallPath": {}
[14:40:27.316] SSH Resolver called for host: dev6425
[14:40:27.316] Setting up SSH remote "dev6425"
[14:40:27.322] Using commit id "129500ee4c8ab7263461ffe327268ba56b9f210d" and quality "stable" for server
[14:40:27.327] Install and start server if needed
[14:40:27.330] Checking ssh with "ssh -V"
[14:40:27.386] > OpenSSH_for_Windows_8.1p1, L
[14:40:27.386] > ibreSSL 3.0.2

[14:40:27.390] Running script with connection command: ssh -T -D 51220dev6425 bash
[14:40:27.392] Terminal shell path: C:\windows\System32\cmd.exe
[14:40:44.400] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\ndelmas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\ndelmas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[14:40:44.408] ------

[14:40:44.503] ------

[14:40:44.503] SSH Resolver called for "ssh-remote+dev6425", attempt 2, (Reconnection)
[14:40:44.505] SSH Resolver called for host: dev6425
[14:40:44.505] Setting up SSH remote "ncerndobedev6425"
[14:40:44.508] Using commit id "129500ee4c8ab7263461ffe327268ba56b9f210d" and quality "stable" for server
[14:40:44.514] Install and start server if needed
[14:40:44.518] Running script with connection command: ssh -T -D 51224 dev6425 bash
[14:40:44.522] Terminal shell path: C:\windows\System32\cmd.exe
`

**Comment by pavel-francirek** [comment]
Happens to me without private-extension-manager. Rollback to version 1.72.0 didn't help (same time out error). Rollback to 1.71.2 did help.

**Comment by ljloo2** [comment]
The first time you can connect to the remote server directory, after debugging the program, close vscode. This issue occurs by opening vscode to reconnect to the same directory. And I can connect to the upper directories and subdirectories of that directory, only that directory cannot be connected again.
