### ISSUE TITLE
My VSCode stopped working all of a sudden,

### ISSUE THREAD

**Issue by IamCurrentlyLearningPython** [microsoft/vscode#163652]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: 22H2

- Error Message:
- Traceback (most recent call last):
  File "c:\Users\schul\Desktop\yes.py", line 6, in <module>
    import discord
  File "C:\Users\schul\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\__init__.py", line 23, in <module>
    from .client import *
  File "C:\Users\schul\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 49, in <module>
    from .user import User, ClientUser
  File "C:\Users\schul\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\user.py", line 29, in <module>
    import discord.abc
  File "C:\Users\schul\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\abc.py", line 54, in <module>
    from .permissions import PermissionOverwrite, Permissions
ImportError: cannot import name 'PermissionOverwrite' from 'discord.permissions' (C:\Users\schul\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\permissions.py)

It worked perfectly fine yesterday.

**Comment by IamCurrentlyLearningPython** [comment]
I cannot repro the issue, but something is wrong with the permissions from the discord.py addon.

**Comment by IamCurrentlyLearningPython** [comment]
Same happens with sublime text, is there something wrong with the discord and/or python addon?

**Comment by IamCurrentlyLearningPython** [comment]
FIXED:
It was a fake addon called 'discord' not 'discord.py'.
