### ISSUE TITLE
'Cannot read property 'element' of undefined' in code completion widget

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16364]
1.8 from master

- have a file package.json with the following content:
```json
{
	"contributes": {
		"grammars": [

			{
				"language": "id",
				"scopeName": "source.id",
				"path": "./syntaxes/id.tmLanguage."
			},


		],
}
```
- do code assist on the empty line after grammar. do it at the location with the same indent as the { on the next line
- there's a single proposal. Pick it with a mouse click on the proposal

In the debugger and see that this.items is empty, but the element of index 0 is requested.
setFocus is called with index 0.

```
shell.js:326 Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at ListView.element (file:////home/aeschli/workspaces/vscode/out/vs/base/browser/ui/list/listView.js:98:37)
    at file:////home/aeschli/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:403:95
    at Array.map (native)
    at List.toListEvent (file:////home/aeschli/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:403:58)
    at file:////home/aeschli/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:195:119
    at file:////home/aeschli/workspaces/vscode/out/vs/base/common/event.js:277:72
    at CallbackList.invoke (file:////home/aeschli/workspaces/vscode/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (file:////home/aeschli/workspaces/vscode/out/vs/base/common/event.js:88:40)
    at FocusTrait.Trait.set (file:////home/aeschli/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:72:28)
    at file:////home/aeschli/workspaces/vscode/out/vs/base/browser/ui/list/listWidget.js:298:65WorkbenchShell.onUnexpectedError @ shell.js:326(anonymous function) @ shell.js:259ErrorHandler.onUnexpectedError @ errors.js:42onUnexpectedError @ errors.js:60CallbackList.invoke @ callbackList.js:60Emitter.fire @ event.js:88Trait.set @ listWidget.js:72(anonymous function) @ listWidget.js:298EventBufferer.bufferEvents @ event.js:267List.setFocus @ listWidget.js:297Controller.onPointer @ listWidget.js:128(anonymous function) @ listWidget.js:110ListView.fireScopedEvent @ listView.js:188handler @ listView.js:175DomListener._wrapHandler @ dom.js:166
```

**Comment by joaomoreno** [comment]
Can't seem to repro.
