### ISSUE TITLE
Running `code.sh` script during container setup results in an error

### ISSUE THREAD

**Issue by Voodu** [microsoft/vscode#163785]
- VS Code Version:
```
Version: 1.73.0-insider (user setup)
Commit: 7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c
Date: 2022-10-14T05:17:07.227Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
Sandboxed: Yes
```
- OS Version: Windows 11 Pro Version 10.0.22623 Build 22623 (Insider, Beta channel)

The problem is related to the container setup. I tried setting up my environment using all three approaches mentioned in [the tutorial](https://github.com/microsoft/vscode/blob/main/.devcontainer/README.md) and all of them ended up with an error shown below.

Additional information:
- For local container setup I used the latest Docker for Windows (4.12.0) with WSL 2 backend
- For Codespaces + browser and Codespaces + local VSCode I used the default size
- To try out the Codespaces,  I forked the repo in a Codespaces-enabled organization
- `yarn install` seems to work okay

## Steps to Reproduce:

1. Follow the [tutorial for container setup](https://github.com/microsoft/vscode/blob/main/.devcontainer/README.md)
2. At the "Try it" step and executing `bash scripts/code.sh` the following error appears:
```
@Voodu ➜ /workspaces/vscode $ bash scripts/code.sh
yarn run v1.22.19
$ node build/lib/electron
Done in 0.20s.
[15:38:01] Synchronizing built-in extensions...
[15:38:01] You can manage built-in extensions with the --builtin flag
[15:38:01] [github] ms-vscode.js-debug-companion@1.0.18 ✔︎
[15:38:02] [github] ms-vscode.js-debug@1.72.0 ✔︎
[15:38:02] [github] ms-vscode.vscode-js-profile-table@1.0.3 ✔︎
[27369:1016/153802.254015:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[27456:1016/153802.360016:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[27456:1016/153802.360169:ERROR:gl_context_egl.cc(136)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[27456:1016/153802.362121:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[27456:1016/153802.362228:ERROR:gl_surface_egl.cc(2250)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[27456:1016/153802.362286:ERROR:gpu_info_collector.cc(80)] gl::GLContext::CreateOffscreenGLSurface failed
[27456:1016/153802.362334:ERROR:gpu_info_collector.cc(342)] Could not create surface for info collection.
[27456:1016/153802.362383:ERROR:gpu_init.cc(86)] CollectGraphicsInfo failed.
[27456:1016/153802.388392:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[27511:1016/153802.496773:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[27511:1016/153802.496909:ERROR:gl_context_egl.cc(136)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[27511:1016/153802.497960:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[27511:1016/153802.498032:ERROR:gl_surface_egl.cc(2250)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[27511:1016/153802.498083:ERROR:gpu_info_collector.cc(80)] gl::GLContext::CreateOffscreenGLSurface failed
[27511:1016/153802.498143:ERROR:gpu_info_collector.cc(342)] Could not create surface for info collection.
[27511:1016/153802.498195:ERROR:gpu_init.cc(86)] CollectGraphicsInfo failed.
[27511:1016/153802.499923:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[27561:1016/153802.599881:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[27561:1016/153802.603359:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[27369:1016/153804.299486:INFO:CONSOLE(252)] "[uncaught exception]: Error: [object Event]", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (252)
[27369:1016/153804.299543:INFO:CONSOLE(255)] "Error: [object Event]
    at Object.ensureError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:256:22)
    at ModuleManager._createLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1508:33)
    at ModuleManager._onLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1519:30)
    at loadNextPath (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1665:27)
    at Object.errorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1685:25)
    at OnlyOnceScriptLoader.triggerErrorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:631:36)
    at vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:618:151
    at HTMLScriptElement.errorEventListener (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:654:17)", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (255)
```

**Comment by yume-chan** [comment]
I have also reported a similar issue microsoft/vscode-remote-release/issues/7296

**Comment by Voodu** [comment]
I guess that might be a duplicate then. I'll leave the decision to the maintainers, though, as I don't know if it's the exact same problem

**Comment by lramos15** [comment]
I'll mark it as a duplicate for now since Christof is the right person and they sound like the same problem.
