### ISSUE TITLE
NPE when editing settings.json

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16372]
I was just in the middle of typing in settings.json and got this:

```
shell.ts:526 Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at CopySettingActionRenderer.createSettingDecoration (file:///C:/Alex/src/vscode/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:725:64)
    at CopySettingActionRenderer.createDecorations (file:///C:/Alex/src/vscode/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:709:47)
    at file:///C:/Alex/src/vscode/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:698:98
    at file:///C:/Alex/src/vscode/out/vs/editor/common/model/textModelWithDecorations.js:98:30
    at file:///C:/Alex/src/vscode/out/vs/editor/common/model/textModelWithDecorations.js:230:34
    at safeInvokeNoArg (file:///C:/Alex/src/vscode/out/vs/base/common/eventEmitter.js:240:20)
    at Model.EventEmitter.deferredEmit (file:///C:/Alex/src/vscode/out/vs/base/common/eventEmitter.js:179:26)
    at Model.TextModelWithDecorations._withDeferredEvents (file:///C:/Alex/src/vscode/out/vs/editor/common/model/textModelWithDecorations.js:224:25)
    at Model.TextModelWithDecorations.changeDecorations (file:///C:/Alex/src/vscode/out/vs/editor/common/model/textModelWithDecorations.js:78:25)
    at CopySettingActionRenderer.render (file:///C:/Alex/src/vscode/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:697:24)
```

**Comment by bpasero** [comment]
Marking as verified based on the fact that we have not seen this exception again for a while.
