### ISSUE TITLE
Cannot install extensions due to "Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by pronebird** [Microsoft/vscode#16384]
- VSCode Version: 1.7.2 (1.7.2)
- OS Version:  macOS 10.12.1

Steps to Reproduce:

1. Open extensions tab
2. See error "Cannot read property 'call' of undefined"
3. Search for any extension (works)
4. Tap install
5. See error "Cannot read property 'call' of undefined"

As a workaround I install things via console, i.e.:
> $ code --install-extension saviorisdead.RustyCode

**Comment by chrmarti** [comment]
@pronebird Could you copy the Console's content in the devtools (Help > Toggle Developer Tools) here when this occurred?

**Comment by pronebird** [comment]
```
VM253:1 Console was cleared
undefined
messageService.ts:128 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:6:22955),    at e.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:6:22792),    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:6:22585,    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:4:27602),    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:5510),    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:6:26733,    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:4:27602),    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:5510),    at Socket.i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:6:13345),    at emitOne (events.js:96:13),    at Socket.emit (events.js:188:7)e.doShow @ messageService.ts:128e.show @ messageService.ts:107t.onError @ extensionsViewlet.ts:397(anonymous function) @ extensionsViewlet.ts:219done @ winjs.base.raw.js:1378v @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_chainedError @ winjs.base.raw.js:1031n @ winjs.base.raw.js:736v @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041(anonymous function) @ async.ts:135done @ winjs.base.raw.js:1378v @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041(anonymous function) @ async.ts:358done @ winjs.base.raw.js:1378v @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_chainedError @ winjs.base.raw.js:1031n @ winjs.base.raw.js:736v @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041t.handlers.(anonymous function) @ ipc.ts:230e.onMessage @ ipc.ts:295(anonymous function) @ ipc.ts:182e.invoke @ callbackList.ts:63e.fire @ event.ts:117(anonymous function) @ ipc.net.ts:46e.invoke @ callbackList.ts:63e.fire @ event.ts:117o @ event.ts:12emitOne @ events.js:96emit @ events.js:188readableAddChunk @ _stream_readable.js:176Readable.push @ _stream_readable.js:134onread @ net.js:543
```

**Comment by joaomoreno** [comment]
You seem to have a broken installation. Does it reproduce after restarting your machine? Or reinstalling Code?

**Comment by pronebird** [comment]
@joaomoreno I just replaced existing VSCode app with the one downloaded from website and it didn't help.

**Comment by pronebird** [comment]
Problem disappeared after restarting my mac. Thanks everyone for suggestions.

**Comment by Nitive** [comment]
I had the same problem and it also disappeared after restartring my mac.
Maybe some macOS-specific problem.
