### ISSUE TITLE
wsl remote can't open bash

### ISSUE THREAD

**Issue by cl1933404370** [microsoft/vscode#163991]
Type: <b>Bug</b>

open a bash is white

VS Code version: Code - Insiders 1.73.0-insider (7ea2788a43a4c35d8da63a419725ba2485de395b, 2022-10-19T05:28:16.879Z)
OS version: Windows_NT x64 10.0.25217
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.68.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (8.52GB free)|
|Process Argv|--crash-reporter-id bec8631b-db86-4595-8087-fe4f83e59785|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-Preview|
|OS|Linux x64 5.15.68.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 2894)|
|Memory (System)|7.45GB (6.53GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.16.1
vscode-language-pack-zh-hans|MS-|1.72.10121008
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.260.0
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
remote-explorer|ms-|0.1.2022092609
remote-repositories|ms-|0.23.2022101802
remote-server|ms-|0.1.2022092009
vscode-bazel|Baz|0.6.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.48.1
EditorConfig|Edi|0.16.4
copilot-nightly|Git|1.53.7065
vscode-pull-request-github|Git|0.52.0
file-downloader|min|1.0.12
vscode-language-pack-zh-hans|MS-|1.72.10121008
extension-manifest-editor|ms-|0.1.5
vscode-dotnet-runtime|ms-|1.5.0
black-formatter|ms-|2022.5.12791008
gather|ms-|2022.3.2
isort|ms-|2022.3.12911018
pylint|ms-|2022.5.12851049
python|ms-|2022.17.12911022
vscode-pylance|ms-|2022.10.21
jupyter|ms-|2022.10.1102931121
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-powertoys|ms-|0.0.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
github-issues-prs|ms-|0.9.3
makefile-tools|ms-|0.6.0
vscode-github-issue-notebooks|ms-|0.0.124
vscode-markdown-notebook|ms-|0.0.26
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.5
vscodeintellicode|Vis|1.2.28
vscodeintellicode-completions|Vis|1.0.20
vscodeintellicode-insiders|Vis|1.1.10

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
pyind367cf:30587848
vscccc:30564267
pyindex848:30577858
nodejswelcome1:30587009

```

</details>

**Comment by yume-chan** [comment]
All integrated terminal is broken for me

```text
 ERR this._core._renderService?._onIntersectionChange is not a function: TypeError: this._core._renderService?._onIntersectionChange is not a function
    at Wi.forceUnpause (vscode-file://vscode-app/c:/Users/simon/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1968:27067)
    at Ui._resizeNow (vscode-file://vscode-app/c:/Users/simon/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3118:3652)
    at Ui._resize (vscode-file://vscode-app/c:/Users/simon/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3118:2736)
    at vscode-file://vscode-app/c:/Users/simon/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6:42860
```

Looks like it's from xterm.js  @Tyriar @meganrogge

**Comment by Librazy** [comment]
integrated terminal is somehow working but the size is fixed at 80 cols and 30 lines regardless of the actual size of terminal

![image](https://user-images.githubusercontent.com/2211542/196633705-cf2c4d43-dbf9-4b17-9d77-99748a39f86e.png)

**Comment by meganrogge** [comment]
already fixed with https://github.com/microsoft/vscode/commit/d105e09d00411a18c99b09be2359487e898f157b

which you'll see in insider's tomorrow

**Comment by furai** [comment]
Can confirm that it's fixed. Was actually fixed yesterday for me.
