### ISSUE TITLE
VSCode is not turning on Sync

### ISSUE THREAD

**Issue by AleTheTwin** [microsoft/vscode#164075]
Type: <b>Bug</b>

I tried to turn on sycn, but it does not sync anything, the output of the log is this:
```
[2022-10-19 15:38:35.641] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-10-19 15:38:35.641] [settingssync] [info] Auto Sync is disabled.
[2022-10-19 15:38:46.236] [settingssync] [info] Sync started.
[2022-10-19 15:38:46.822] [settingssync] [info] Did reset the local sync state.
[2022-10-19 15:38:46.833] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:39:51.469] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:39:51.692] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:39:52.025] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:40:16.650] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:40:41.811] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/settings/latest
[2022-10-19 15:41:25.693] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:41:25.745] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:41:28.553] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:48:16.751] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:48:21.374] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:48:41.655] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:48:45.435] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:49:56.596] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:51:45.188] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:52:11.421] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:52:32.274] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 15:59:56.943] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 16:00:20.819] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 16:00:51.212] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 16:01:52.013] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 16:03:01.556] [settingssync] [info] Keybindings: Not synced yet. Last sync resource does not exist.
[2022-10-19 16:04:03.037] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 16:04:10.628] [settingssync] [info] Keybindings: Not synced yet. Last sync resource does not exist.
[2022-10-19 16:05:24.805] [settingssync] [info] Keybindings: Not synced yet. Last sync resource does not exist.
```
 
If it helps, I'm loging in with GitHub.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:55.763Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 864fec2c-f4cd-48c5-a22f-44fa394c103f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
prettier-vscode|esb|9.9.0
vscode-iterm2-theme-sync|tus|0.1.3
volar|Vue|1.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by myvscodesync** [comment]
Hi, I am facing the same problem, even creating a brand new account it fails.

[2022-10-19 17:24:18.670] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-10-19 17:24:18.670] [settingssync] [info] Auto Sync is enabled.
[2022-10-19 17:24:18.670] [settingssync] [info] Auto Sync: Suspended until auth token is available.
[2022-10-19 17:24:19.261] [settingssync] [info] Auto Sync: Triggered by Interval
[2022-10-19 17:24:19.261] [settingssync] [info] Sync started.
[2022-10-19 17:25:42.479] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:25:42.480] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:25:42.480] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:25:42.480] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:25:42.480] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:25:42.480] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:26:18.623] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:26:18.624] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:26:18.624] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:26:18.624] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:26:18.624] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:27:03.102] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/settings
[2022-10-19 17:27:03.103] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/tasks
[2022-10-19 17:27:03.119] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/machines/latest
[2022-10-19 17:27:47.142] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:27:47.494] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:27:47.750] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:27:49.850] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:27:59.283] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2022-10-19 17:27:59.283] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:27:59.284] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:27:59.284] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-19 17:27:59.284] [settingssync] [info] Sync started.
[2022-10-19 17:28:00.917] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:28:04.363] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:28:12.389] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 17:28:46.774] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2022-10-19 17:28:46.774] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:28:46.774] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:28:46.775] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-19 17:28:46.775] [settingssync] [info] Sync started.
[2022-10-19 17:32:46.965] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2022-10-19 17:32:46.965] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:32:46.966] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:32:46.966] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-19 17:32:46.966] [settingssync] [info] Sync started.
[2022-10-19 17:33:52.504] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2022-10-19 17:33:52.504] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:33:52.504] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:37:33.035] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-19 17:37:33.036] [settingssync] [info] Sync started.
[2022-10-19 17:38:36.361] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2022-10-19 17:38:36.361] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:38:36.361] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.
    at y.request (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.manifest (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:165229)
    at async l.createSyncTask (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:133064)
    at async o.doSync (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:101510)
[2022-10-19 17:38:42.005] [settingssync] [info] Auto Sync: Triggered by Activity
[2022-10-19 17:38:42.005] [settingssync] [info] Sync started.
[2022-10-19 17:39:09.040] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.

**Comment by joaotextor** [comment]
I can confirm this. But I'm on Windows 11. Logging in with Github.

**Comment by hao-joey-zhang** [comment]
Experienced same issue on windows 11.

**Comment by sandy081** [comment]
All, can you please try the feature again and let us know if it is still not working. We made some recent improvements to our settings sync server to scale up. If you are seeing errors, please share us the settings sync log completely. Thanks.

**Comment by AleTheTwin** [comment]
> All, can you please try the feature again and let us know if it is still not working. We made some recent improvements to our settings sync server to scale up. If you are seeing errors, please share us the settings sync log completely. Thanks.

I tried again and it works now

**Comment by joaotextor** [comment]
Working as intended since Friday.
