### ISSUE TITLE
Settings sync fails!

### ISSUE THREAD

**Issue by ryancollins-dev** [microsoft/vscode#164103]
Type: <b>Bug</b>

Can't sync settings, server refuses connection 

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.91GB (11.64GB free)|
|Process Argv|--crash-reporter-id 81708ac6-2268-43b6-8217-81110da8e145|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848cf:30577861
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by ryancollins-dev** [comment]
[2022-10-19 23:46:18.710] [settingssync] [error] tasks: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/tasks/latest'.

**Comment by ryancollins-dev** [comment]
[2022-10-19 23:44:12.156] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-10-19 23:44:12.156] [settingssync] [info] Auto Sync is disabled.
[2022-10-19 23:44:17.935] [settingssync] [info] Sync started.
[2022-10-19 23:45:02.239] [settingssync] [info] Sync started.
[2022-10-19 23:45:02.409] [settingssync] [info] Did reset the local sync state.
[2022-10-19 23:45:02.445] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:45:02.534] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:45:02.664] [settingssync] [info] Keybindings: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:45:02.767] [settingssync] [info] Snippets: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:45:02.866] [settingssync] [info] Tasks: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:45:44.022] [settingssync] [info] Did reset the local sync state.
[2022-10-19 23:45:44.026] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:46:18.708] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/tasks/latest
[2022-10-19 23:46:18.710] [settingssync] [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/tasks/latest'.
    at y.request (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:167499)
    at async y.readResource (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:163937)
    at async v.getRemoteUserData (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:32311)
    at async v._sync (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:22423)
    at async p.sync (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:145537)
    at async l.syncProfile (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:135807)
    at async l.sync (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:134638)
    at async w.call (vscode-file://vscode-app/c:/Users/R/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:149776)
[2022-10-19 23:46:18.710] [settingssync] [error] tasks: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/resource/tasks/latest'.
[2022-10-19 23:46:18.713] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:47:53.894] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:48:20.413] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:49:05.184] [settingssync] [info] Sync done. Took 242950ms
[2022-10-19 23:49:05.186] [settingssync] [info] Auto Sync: Triggered by Interval
[2022-10-19 23:49:05.187] [settingssync] [info] Sync started.
[2022-10-19 23:49:05.464] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:49:05.680] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:49:44.115] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/resource/settings/latest
[2022-10-19 23:50:59.367] [settingssync] [info] Settings: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:50:59.541] [settingssync] [info] Settings: Updated local settings
[2022-10-19 23:50:59.548] [settingssync] [info] Settings: Updated last synchronized settings
[2022-10-19 23:50:59.552] [settingssync] [info] Keybindings: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:50:59.679] [settingssync] [info] Keybindings: No changes found during synchronizing keybindings.
[2022-10-19 23:50:59.691] [settingssync] [info] Keybindings: Updated last synchronized keybindings
[2022-10-19 23:50:59.694] [settingssync] [info] Snippets: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:50:59.776] [settingssync] [info] Snippets: No changes found during synchronizing snippets.
[2022-10-19 23:50:59.795] [settingssync] [info] Snippets: Updated last synchronized snippets
[2022-10-19 23:50:59.802] [settingssync] [info] Tasks: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:50:59.932] [settingssync] [info] Tasks: Updated local tasks
[2022-10-19 23:50:59.939] [settingssync] [info] Tasks: Updated last synchronized tasks
[2022-10-19 23:50:59.945] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:00.051] [settingssync] [info] GlobalState: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:00.201] [settingssync] [info] GlobalState: Updated global state ["ces/skipSurvey","commandPalette.mru.cache","commandPalette.mru.counter","cpp.1.editedCount","cpp.1.editedDate","cpp.1.lastSessionDate","cpp.1.sessionCount","extensionTips/promptedExecutableTips","fileBasedRecommendations/promptedFileExtensions","fileBasedRecommendations/promptedRecommendations","java.2.lastSessionDate","java.2.sessionCount","javascript.1.editedCount","javascript.1.editedDate","javascript.1.isCandidate","javascript.1.lastSessionDate","javascript.1.sessionCount","javascript.1.skipVersion","memento/notebookGettingStarted2","memento/workbench.editor.keybindings","nps/isCandidate","nps/skipVersion","remote.explorerType","tabs-list-width-horizontal","terminal.integrated.showTerminalConfigPrompt","typescript.1.editedCount","typescript.1.editedDate","typescript.1.lastSessionDate","typescript.1.sessionCount","workbench.activityBar.hidden","workbench.auxiliarybar.pinnedPanels","workbench.panel.alignment","workbench.sideBar.position","workbench.statusBar.hidden","workbench.view.extension.dockerView.state.hidden","workbench.view.extension.flutter.state.hidden","workbench.view.extension.github-pull-request.state.hidden","workbench.view.extension.github-pull-requests.state.hidden","workbench.view.extension.gitlens.state.hidden","workbench.view.extension.gitlensPanel.state.hidden","workbench.view.extension.jupyter-variables.state.hidden","workbench.view.extension.objectExplorer.state.hidden","workbench.view.extension.references-view.state.hidden","workbench.view.extension.test.state.hidden","workbench.view.extensions.state.hidden","workbench.view.remote.state.hidden","workbench.view.sync.state.hidden","workbench.welcomePage.walkthroughMetadata","github-ryancollins-dev","snippets.usageTimestamps","workbench.view.extension.cmake__viewContainer.state.hidden","workbench.view.extension.dotnet-interactive-panel.state.hidden","views.customizations","workbench.view.extension.jupyter.state.hidden","typescript.1.isCandidate","typescript.1.skipVersion","colorThemeData","memento/gettingStartedService","nps/lastSessionDate","nps/sessionCount","workbench.activity.pinnedViewlets2","workbench.explorer.views.state.hidden","workbench.panel.pinnedPanels","workbench.panel.repl.hidden","workbench.scm.views.state.hidden","workbench.statusbar.hidden","workbench.welcomePage.hiddenCategories"]
[2022-10-19 23:51:00.201] [settingssync] [info] GlobalState: Updated local ui state
[2022-10-19 23:51:00.208] [settingssync] [info] GlobalState: Updated last synchronized ui state
[2022-10-19 23:51:00.212] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:00.778] [settingssync] [info] Extensions: Disabled extension ms-vscode.cpptools-themes 1.0.0
[2022-10-19 23:51:00.781] [settingssync] [info] Extensions: Disabled extension enkia.tokyo-night 0.9.4
[2022-10-19 23:51:00.802] [settingssync] [info] Extensions: Disabled extension jeff-hykin.better-cpp-syntax 1.16.1
[2022-10-19 23:51:00.814] [settingssync] [info] Extensions: Disabled extension ms-vscode-remote.remote-wsl 0.72.0
[2022-10-19 23:51:00.825] [settingssync] [info] Extensions: Disabled extension ms-dotnettools.dotnet-interactive-vscode 1.0.3519011
[2022-10-19 23:51:00.827] [settingssync] [info] Extensions: Disabled extension icsharpcode.ilspy-vscode 0.13.1
[2022-10-19 23:51:00.828] [settingssync] [info] Extensions: Disabled extension humao.rest-client 0.25.1
[2022-10-19 23:51:00.830] [settingssync] [info] Extensions: Disabled extension ms-dotnettools.vscode-dotnet-runtime 1.5.0
[2022-10-19 23:51:00.843] [settingssync] [info] Extensions: Disabled extension ms-vscode-remote.remote-ssh 0.90.1
[2022-10-19 23:51:00.845] [settingssync] [info] Extensions: Disabled extension ms-vscode.cpptools-extension-pack 1.3.0
[2022-10-19 23:51:00.848] [settingssync] [info] Extensions: Disabled extension ms-vscode-remote.remote-ssh-edit 0.84.0
[2022-10-19 23:51:00.856] [settingssync] [info] Extensions: Disabled extension tintoy.msbuild-project-tools 0.4.9
[2022-10-19 23:51:00.858] [settingssync] [info] Extensions: Disabled extension cschlosser.doxdocgen 1.4.0
[2022-10-19 23:51:00.861] [settingssync] [info] Extensions: Disabled extension ms-toolsai.jupyter-keymap 1.0.0
[2022-10-19 23:51:00.867] [settingssync] [info] Extensions: Disabled extension ms-toolsai.jupyter-renderers 1.0.10
[2022-10-19 23:51:00.871] [settingssync] [info] Extensions: Disabled extension ms-toolsai.vscode-jupyter-slideshow 0.1.5
[2022-10-19 23:51:00.875] [settingssync] [info] Extensions: Disabled extension juanblanco.solidity 0.0.141
[2022-10-19 23:51:00.885] [settingssync] [info] Extensions: Disabled extension twxs.cmake 0.0.17
[2022-10-19 23:51:00.889] [settingssync] [info] Extensions: Disabled extension ms-toolsai.vscode-jupyter-cell-tags 0.1.6
[2022-10-19 23:51:00.895] [settingssync] [info] Extensions: Disabled extension ms-dotnettools.csharp 1.25.0
[2022-10-19 23:51:00.897] [settingssync] [info] Extensions: Disabled extension ms-vscode-remote.vscode-remote-extensionpack 0.21.0
[2022-10-19 23:51:00.898] [settingssync] [info] Extensions: Disabled extension ritwickdey.liveserver 5.7.9
[2022-10-19 23:51:00.900] [settingssync] [info] Extensions: Disabled extension angular.ng-template 14.2.0
[2022-10-19 23:51:00.912] [settingssync] [info] Extensions: Disabled extension ms-python.vscode-pylance 2022.10.30
[2022-10-19 23:51:00.919] [settingssync] [info] Extensions: Disabled extension ms-vscode.cmake-tools 1.12.27
[2022-10-19 23:51:01.062] [settingssync] [info] Extensions: Disabled extension ms-vscode-remote.remote-containers 0.255.4
[2022-10-19 23:51:01.071] [settingssync] [info] Extensions: Disabled extension ms-python.python 2022.16.1
[2022-10-19 23:51:01.131] [settingssync] [info] Extensions: Disabled extension ms-toolsai.jupyter 2022.9.1202862440
[2022-10-19 23:51:01.145] [settingssync] [info] Extensions: Disabled extension ms-vscode.cpptools 1.12.4
[2022-10-19 23:51:01.772] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:02.710] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:04.046] [settingssync] [info] Extensions: Installed extension. ms-vscode.cpptools-extension-pack 1.3.0
[2022-10-19 23:51:04.063] [settingssync] [info] Extensions: Installed extension. editorconfig.editorconfig 0.16.4
[2022-10-19 23:51:04.115] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:04.425] [settingssync] [info] Extensions: Installed extension. enkia.tokyo-night 0.9.4
[2022-10-19 23:51:04.439] [settingssync] [info] Extensions: Installed extension. jeff-hykin.better-cpp-syntax 1.16.1
[2022-10-19 23:51:04.501] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:04.559] [settingssync] [info] Extensions: Installed extension. visualstudioexptteam.intellicode-api-usage-examples 0.2.6
[2022-10-19 23:51:04.628] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:04.905] [settingssync] [info] Extensions: Installed extension. sdras.night-owl 2.0.1
[2022-10-19 23:51:04.907] [settingssync] [info] Extensions: Installed extension. bradlc.vscode-tailwindcss 0.9.1
[2022-10-19 23:51:04.959] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:05.231] [settingssync] [info] Extensions: Installed extension. dbaeumer.vscode-eslint 2.2.6
[2022-10-19 23:51:05.284] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:05.858] [settingssync] [info] Extensions: Installed extension. esbenp.prettier-vscode 9.9.0
[2022-10-19 23:51:05.903] [settingssync] [info] Extensions: Installed extension. ms-vscode-remote.remote-ssh 0.90.1
[2022-10-19 23:51:05.968] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:06.289] [settingssync] [info] Extensions: Installed extension. dsznajder.es7-react-js-snippets 4.4.3
[2022-10-19 23:51:06.375] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:07.135] [settingssync] [info] Extensions: Installed extension. msjsdiag.vscode-react-native 1.9.3
[2022-10-19 23:51:07.190] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:07.309] [settingssync] [info] Extensions: Installed extension. pkief.material-icon-theme 4.21.0
[2022-10-19 23:51:07.427] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:09.790] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:09.928] [settingssync] [info] Extensions: Installed extension. adpyke.codesnap 1.3.4
[2022-10-19 23:51:09.990] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:10.659] [settingssync] [info] Extensions: Installed extension. ms-toolsai.vscode-jupyter-cell-tags 0.1.6
[2022-10-19 23:51:10.711] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:10.828] [settingssync] [info] Extensions: Installed extension. ms-vscode.cpptools-themes 1.0.0
[2022-10-19 23:51:10.880] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:11.605] [settingssync] [info] Extensions: Installed extension. ms-vscode.vscode-typescript-next 4.9.20221018
[2022-10-19 23:51:11.657] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:11.889] [settingssync] [info] Extensions: Installed extension. ms-vscode-remote.remote-containers 0.255.4
[2022-10-19 23:51:11.993] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:13.370] [settingssync] [info] Extensions: Installed extension. ms-vscode.cmake-tools 1.12.27
[2022-10-19 23:51:13.452] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:14.839] [settingssync] [info] Extensions: Installed extension. ms-dotnettools.vscode-dotnet-runtime 1.5.0
[2022-10-19 23:51:14.891] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:16.734] [settingssync] [info] Extensions: Installed extension. ms-vscode-remote.vscode-remote-extensionpack 0.21.0
[2022-10-19 23:51:16.788] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:17.272] [settingssync] [info] Extensions: Installed extension. ms-dotnettools.dotnet-interactive-vscode 1.0.3519011
[2022-10-19 23:51:17.330] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:17.546] [settingssync] [info] Extensions: Installed extension. formulahendry.auto-rename-tag 0.1.10
[2022-10-19 23:51:17.603] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:18.246] [settingssync] [info] Extensions: Installed extension. ms-toolsai.jupyter-keymap 1.0.0
[2022-10-19 23:51:18.300] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:18.347] [settingssync] [info] Extensions: Installed extension. ms-toolsai.vscode-jupyter-slideshow 0.1.5
[2022-10-19 23:51:18.399] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:18.462] [settingssync] [info] Extensions: Installed extension. ms-vscode-remote.remote-ssh-edit 0.84.0
[2022-10-19 23:51:18.557] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:20.535] [settingssync] [info] Extensions: Installed extension. ms-vscode-remote.remote-wsl 0.72.0
[2022-10-19 23:51:20.628] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:23.371] [settingssync] [info] Extensions: Installed extension. ms-python.python 2022.16.1
[2022-10-19 23:51:23.422] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:23.714] [settingssync] [info] Extensions: Installed extension. humao.rest-client 0.25.1
[2022-10-19 23:51:23.801] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:24.794] [settingssync] [info] Extensions: Installed extension. ms-toolsai.jupyter 2022.9.1202862440
[2022-10-19 23:51:24.846] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:24.958] [settingssync] [info] Extensions: Installed extension. ms-python.vscode-pylance 2022.10.30
[2022-10-19 23:51:25.055] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:25.668] [settingssync] [info] Extensions: Installed extension. cschlosser.doxdocgen 1.4.0
[2022-10-19 23:51:25.733] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:27.256] [settingssync] [info] Extensions: Installed extension. ritwickdey.liveserver 5.7.9
[2022-10-19 23:51:27.308] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:27.423] [settingssync] [info] Extensions: Installed extension. visualstudioexptteam.vscodeintellicode 1.2.29
[2022-10-19 23:51:27.501] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:31.925] [settingssync] [info] Extensions: Installed extension. twxs.cmake 0.0.17
[2022-10-19 23:51:31.997] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:32.456] [settingssync] [info] Extensions: Installed extension. icsharpcode.ilspy-vscode 0.13.1
[2022-10-19 23:51:32.510] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:32.630] [settingssync] [info] Extensions: Installed extension. streetsidesoftware.code-spell-checker 2.10.1
[2022-10-19 23:51:32.686] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:33.195] [settingssync] [info] Extensions: Installed extension. angular.ng-template 14.2.0
[2022-10-19 23:51:33.261] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:34.057] [settingssync] [info] Extensions: Installed extension. ms-vscode.cpptools 1.12.4
[2022-10-19 23:51:34.146] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:34.625] [settingssync] [info] Extensions: Installed extension. nomicfoundation.hardhat-solidity 0.5.5
[2022-10-19 23:51:34.683] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:37.298] [settingssync] [info] Extensions: Installed extension. ms-toolsai.jupyter-renderers 1.0.10
[2022-10-19 23:51:37.363] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:39.731] [settingssync] [info] Extensions: Installed extension. tintoy.msbuild-project-tools 0.4.9
[2022-10-19 23:51:39.785] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:49.277] [settingssync] [info] Extensions: Installed extension. juanblanco.solidity 0.0.141
[2022-10-19 23:51:49.331] [settingssync] [info] Extensions: Not synced yet. Last sync resource does not exist.
[2022-10-19 23:51:49.730] [settingssync] [info] Extensions: Installed extension. ms-dotnettools.csharp 1.25.0
[2022-10-19 23:51:49.739] [settingssync] [info] Extensions: Updated last synchronized extensions.
[2022-10-19 23:51:49.750] [settingssync] [info] Sync done. Took 164562ms

**Comment by ryancollins-dev** [comment]
sync completed just now, no idea why it kept failing been trying for a few hours now, this never happened before.

**Comment by Mateusnasciment** [comment]
Problema resolvido no Linux, instalando gnome-keyring!

**Comment by ryancollins-dev** [comment]
> 

There is no gnome-keyring in Windows 11!

**Comment by Anonymous-User-c4676** [comment]
> Windows 11中没有侏儒密钥！

**Comment by sandy081** [comment]
This could be due to the scalability of settings sync server. We did some fixes/improvements to settings sync server to improve the scalability. Hopefully these get fixed with this. Please let us know if you still see connectivity errors. When you see them, please share us the settings sync log.

**Comment by ryancollins-dev** [comment]
> 

Thank you
