### ISSUE TITLE
Cannot install extension because of version mismatch in Marketplace

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#164680]
Testing #164452

Several extensions fail to install, e.g.:

```
2022-10-26 10:23:00.857 [info] Electron sandbox mode is enabled!
2022-10-26 10:23:01.601 [info] [vscode.typescript-language-features]: Command `typescript.sortImports` appears multiple times in the `commands` section.
2022-10-26 10:23:01.601 [info] [vscode.typescript-language-features]: Command `javascript.sortImports` appears multiple times in the `commands` section.
2022-10-26 10:23:01.601 [info] [vscode.typescript-language-features]: Command `typescript.removeUnusedImports` appears multiple times in the `commands` section.
2022-10-26 10:23:01.601 [info] [vscode.typescript-language-features]: Command `javascript.removeUnusedImports` appears multiple times in the `commands` section.
2022-10-26 10:23:03.881 [info] [perf] Render performance baseline is 17ms
2022-10-26 10:23:48.993 [error] Invalid: Cannot install 'nagab.todo-tree' extension because of version mismatch in Marketplace
    at $.checkAndGetCompatibleVersion (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:96873)
    at async $.installFromGallery (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:86770)
2022-10-26 10:23:48.995 [error] Cannot install 'nagab.todo-tree' extension because of version mismatch in Marketplace: Invalid: Cannot install 'nagab.todo-tree' extension because of version mismatch in Marketplace
    at $.checkAndGetCompatibleVersion (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:96873)
    at async $.installFromGallery (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:86770)
```

Also: Many extensions are not found when searching in the Extensions viewlet. E.g., searching for "azure" in the Extensions viewlet shows no results.

```
Version: 1.73.0-insider
Commit: a887d72e8de27cf9042745fb09a9b9e9f451ebc0
Date: 2022-10-26T05:25:13.711Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux arm64 5.15.0-52-generic
Sandboxed: Yes
```

**Comment by chrmarti** [comment]
Same with the armhf server (the above was with arm64 desktop).

**Comment by sandy081** [comment]
This is expected since the extension is indeed incompatible.

**Comment by joyceerhl** [comment]
I also ran into this. Should version compatibility be surfaced in the extension's overview page upfront?

**Comment by sandy081** [comment]
Yeah we can, but it can be expensive as we have to get all versions of the extension.
