### ISSUE TITLE
Failed to install extension: Signature: EACCES

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#164705]
Testing #164452

* Configure
```
"extensions.verifySignature": true,
"_extensionsGallery.enablePPE": true
```
* Try to install `nikhgup1.component-creator`
* I get the following error:
```
2022-10-26 14:07:38.343 [error] Error while installing the extension: nikhgup1.component-creator
2022-10-26 14:07:38.343 [error] Failed to install extension. nikhgup1.component-creator
2022-10-26 14:07:38.343 [error] Signature: EACCES
    at pt.download (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:113204)
    at async x.doRun (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199243)
2022-10-26 14:07:38.344 [error] [uncaught exception in sharedProcess]: EACCES: Signature: EACCES
    at pt.download (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:113204)
    at async x.doRun (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199243)
```

```
Version: 1.73.0-insider
Commit: c3eebaead9d3bf1cb961b91fca1b8af31990d328
Date: 2022-10-26T09:30:42.684Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux arm64 5.15.0-52-generic
Sandboxed: Yes
```

**Comment by sandy081** [comment]
@dtivel Is EACCES error coming from the vsce-sign exe?

**Comment by dtivel** [comment]
Is vsce-sign present?  If so, I suspect it's an issue with file permissions.  Do file permissions need to be set during install?  I tried setting them during [preinstall](https://github.com/microsoft/node-vsce-sign/commit/52281e2ca1049d120b31217d8dc69052a8b992b8), which worked locally.

**Comment by sandy081** [comment]
It's present and here is the exe access levels in Linux ARM 64

```
-rwxrw-r-- 1 root root 14853557 Oct 26 07:20 vsce-sign
```

It's also same in Mac ARM 64

```
-rwxr--r--  1 sandy081  staff  30494992 Oct 26 12:04 vsce-sign
```

It worked in Mac but not in Linux. When I changed the exe's access in Linux ARM 64 to 777, it worked. 

Not sure if Linux ARM 64 needs spl access
