### ISSUE TITLE
Signature: UnknownError

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#164726]
Testing #164452

```
2022-10-26 16:43:48.609 [info] Extension host agent started.
2022-10-26 16:43:51.256 [error] [172.17.0.1][ddd63f6d][ExtensionHostConnection] Unknown reconnection token (never seen).
2022-10-26 16:43:51.280 [error] [172.17.0.1][7d248857][ManagementConnection] Unknown reconnection token (never seen).
2022-10-26 16:43:54.628 [warning] No ptyHost heartbeat after 6 seconds
2022-10-26 16:43:57.487 [info] [172.17.0.1][75f1ef47][ManagementConnection] New connection established.
2022-10-26 16:43:57.751 [info] [172.17.0.1][d79102fd][ExtensionHostConnection] New connection established.
2022-10-26 16:43:57.813 [info] [172.17.0.1][d79102fd][ExtensionHostConnection] <1285> Launched Extension Host Process.
2022-10-26 16:44:03.637 [warning] No ptyHost heartbeat after 6 seconds
2022-10-26 16:44:04.241 [warning] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
2022-10-26 16:46:24.186 [info] Getting Manifest... nikhgup1.component-creator
2022-10-26 16:46:24.893 [info] Installing extension: nikhgup1.component-creator
2022-10-26 16:46:36.746 [error] Error while installing the extension: nikhgup1.component-creator
2022-10-26 16:46:36.825 [error] Failed to install extension. nikhgup1.component-creator
2022-10-26 16:46:36.857 [error] Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152)
2022-10-26 16:46:37.899 [error] Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152)
```

```
Version: 1.73.0-insider
Commit: c3eebaead9d3bf1cb961b91fca1b8af31990d328
Date: 2022-10-26T09:14:47.017Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.52
```

(Using VS Code Server armhf build in a Docker container with armhf hardware emulation.)

**Comment by chrmarti** [comment]
The server console also shows `Unsupported ioctl: cmd=0x5441`:

```
[16:46:24] Getting Manifest... nikhgup1.component-creator
[16:46:24] Installing extension: nikhgup1.component-creator
Unsupported ioctl: cmd=0x5441
[16:46:36] Error while installing the extension: nikhgup1.component-creator
[16:46:36] Failed to install extension. nikhgup1.component-creator
[16:46:36] Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152) {
  code: 'Signature'
}
rejected promise not handled within 1 second: Signature: UnknownError
stack trace: Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152)
[16:46:37] Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152) {
  code: 'Signature'
}
```

**Comment by chrmarti** [comment]
Installing `libsecret` helped:
```
[17:02:08] Getting Manifest... nikhgup1.component-creator
[17:02:09] Installing extension: nikhgup1.component-creator
[17:02:41] Verified extension: nikhgup1.component-creator true
[17:02:44] Extracted extension to /root/.vscode-server-insiders/extensions/.1fdfbfdf-5094-4749-8ba6-2a0c89cd57f0: nikhgup1.component-creator
[17:02:44] Renamed to /root/.vscode-server-insiders/extensions/nikhgup1.component-creator-1.0.0
[17:02:44] Extracting completed. nikhgup1.component-creator
[17:02:44] Extension installed successfully: nikhgup1.component-creator
```

**Comment by sandy081** [comment]
CC @dtivel 

This is in linux arm 32 platform

**Comment by chrmarti** [comment]
My last comment was too optimistic. Seeing this again with the next extension:
```
[17:09:14] Getting Manifest... nikhgup1.xml1298
[17:09:16] Installing extension: nikhgup1.xml1298
[17:09:21] No ptyHost heartbeat after 6 seconds
[17:10:17] Error while installing the extension: nikhgup1.xml1298
[17:10:17] Failed to install extension. nikhgup1.xml1298
[17:10:17] Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152) {
  code: 'Signature'
}
rejected promise not handled within 1 second: Signature: UnknownError
stack trace: Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152)
[17:10:18] Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152) {
  code: 'Signature'
}
[17:12:43] Getting Manifest... nikhgup1.xml1298
[17:12:44] Installing extension: nikhgup1.xml1298
[17:12:56] Error while installing the extension: nikhgup1.xml1298
[17:12:56] Failed to install extension. nikhgup1.xml1298
[17:12:56] Signature: UnknownError
    at Sn.download (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:90:4035)
    at async V.doRun (/root/vscode-server-linux-armhf-web/out/vs/server/node/server.main.js:146:92152) {
  code: 'Signature'
}
```

**Comment by chrmarti** [comment]
A few others now worked. `nikhgup1.xml1298` again failed.

**Comment by sandy081** [comment]
@isidorn Is this being worked on or shall I move this to next milestone?

**Comment by isidorn** [comment]
@sandy081 it is being worked on. There is an email thread between Damon, Christof and you with more details. 
I suggest to leave to this milestone for now. And if we see that Damon is blocked we can move it to December.
Thanks!

**Comment by brettcurtis** [comment]
I'm seeing this in the insider build, any W/A while it's being worked on?

![image](https://user-images.githubusercontent.com/1610100/204917412-bbd54501-518b-416c-8ddb-1cb412560129.png)

**Comment by isidorn** [comment]
**Workaround** set `extensions.verifySignature` to `false` in your `settings.json`.

**Comment by manastalukdar** [comment]
Workaround did not help:

- Tooltip on `settings.json`: Unknown configuration setting.
- Same/similar error preventing extensions from upgrading:

```plaintext
2022-12-02 10:03:38.260 [error] UnknownError: Signature: UnknownError
    at pt.download (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1169/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92674)
    at async Y.h (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1169/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167162)
```

Version: 1.74.0-insider
Commit: 493a541735b84de36b628750ba716a430669cb7f
Date: 2022-12-02T05:26:38.457Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.10-300.fc37.x86_64 snap
Sandboxed: Yes

**Comment by isidorn** [comment]
You might need to reload VS Code.

**Comment by manastalukdar** [comment]
Tried both reloading and explicit restarting. No luck.

**Comment by ViniciusRed** [comment]
I'm having the same problem

![image](https://user-images.githubusercontent.com/81523685/205400266-be41c7ee-f28a-405c-aab5-d4d9b60fd371.png)


Versão: 1.74.0-insider
Commit: 493a541735b84de36b628750ba716a430669cb7f
Data: 2022-12-02T05:26:38.457Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
SO: Linux x64 6.0.10-arch2-1
Em área restrita: Yes

**Comment by wrenparismoe** [comment]
@ViniciusRed I have an identical error log. Haven't been able to find a fix. This started within the last day or two for me.

**Comment by lavjamanxd** [comment]
> Workaround did not help:
> 
>     * Tooltip on `settings.json`: Unknown configuration setting.
> 
>     * Same/similar error preventing extensions from upgrading:
> 
> 
> ```
> 2022-12-02 10:03:38.260 [error] UnknownError: Signature: UnknownError
>     at pt.download (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1169/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92674)
>     at async Y.h (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1169/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167162)
> ```
> 
> Version: 1.74.0-insider Commit: [493a541](https://github.com/microsoft/vscode/commit/493a541735b84de36b628750ba716a430669cb7f) Date: 2022-12-02T05:26:38.457Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Linux x64 6.0.10-300.fc37.x86_64 snap Sandboxed: Yes

i put that into my devcontainer.json's setting object instead of settings.json and it worked for me

**Comment by Paro131** [comment]
Ivan

**Comment by d2r2** [comment]
Have same issue:
![Unsaved Image 124](https://user-images.githubusercontent.com/710233/205496803-edceaeb5-c672-4d09-86fe-8cadd523bd0c.jpg)
My vs code version:
```
Version: 1.74.0-insider
Commit: d0e44be43287acadb13f7c2808332e00fe52568d
Date: 2022-11-25T08:00:14.076Z
Electron: 19.1.6
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.11-arch1-1
Sandboxed: Yes
```
Updating the JSON setting `extensions.verifySignature` to `false` helped!

**Comment by manastalukdar** [comment]
Any update? The workaround does not work for me and as a result most of my key extensions are now out-of-date.

**Comment by isidorn** [comment]
@manastalukdar are you sure you applied the `extensions.verifySignature` to `false` in the right setting file. What is the error that you get when you have this setting set?

**Comment by manastalukdar** [comment]
@isidorn : https://github.com/microsoft/vscode/issues/164726#issuecomment-1335630704

**Comment by brettcurtis** [comment]
The workaround doesn't work for me either:

![image](https://user-images.githubusercontent.com/1610100/206819926-20d3e2ee-6510-4976-baa1-39e229fe05e7.png)

I only see issues updating extensions in my WSL Distros

**Comment by brubrant** [comment]
The workaround worked for me. I'm using Manjaro as OS. Added the setting on
my user settings and was able to update my extensions.

Em sex., 9 de dez. de 2022 21:52, Brett Curtis ***@***.***>
escreveu:

**Comment by brettcurtis** [comment]
Weird, I hopped back onto the stable release for now. I don't see any problems there.

**Comment by hypeitnow** [comment]
> extensions.verifySignature

What version are you using on manjaro? 

I tried 

![image](https://user-images.githubusercontent.com/47086634/206870515-bd9977ac-5cdc-4b7d-b28c-63449e37cf8b.png)

but no avail

**Comment by brubrant** [comment]
I install and update VSCO de using the following command:

pamac build visual-studio-code-insiders-bin


Em sáb., 10 de dez. de 2022 15:42, hypeit ***@***.***>
escreveu:

**Comment by ViniciusRed** [comment]
Update worked by adding `"extensions.verifySignature": true` but still happens

Versão: 1.75.0-insider
Commit: f076d553210e9ea65e7bccbfa2f7a786c10fcab2
Data: 2022-12-09T09:09:03.185Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
SO: Linux x64 6.0.11-arch1-1
Em área restrita: Yes

**Comment by MatiasDuhalde** [comment]
I started getting the same error a few days ago:

```
2022-12-13 11:27:53.785 [error] Signature: UnknownError
    at yt.download (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92965)
    at async V.h (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:169726)
2022-12-13 11:27:53.788 [error] UnknownError: Signature: UnknownError
    at yt.download (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92965)
    at async V.h (vscode-file://vscode-app/opt/visual-studio-code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:169726)

```

The proposed workaround does not work for me either.

Version: 1.75.0-insider
Commit: d7b1e2a1c892511a125e4ceb9758ec8ddf907775
Date: 2022-12-12T12:40:10.825Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.12-arch1-1
Sandboxed: Yes

**Comment by DrShushen** [comment]
I had the same issue today. Setting to `"extensions.verifySignature": false` in user settings **fixes the issue** for me.

<details>
  <summary>All debug info</summary>

#### About
```
Version: 1.75.0-insider
Commit: 11238faea62d570d77afe6edfe05c8b732c44a2b
Date: 2022-12-13T05:22:26.937Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: Yes
```

#### System info
CPUs | Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3400)
-- | --
GPU Status | 2d_canvas: unavailable_software canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: disabled_software multiple_raster_threads: enabled_on opengl: disabled_off rasterization: disabled_software raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: unavailable_software webgl2: unavailable_software webgpu: disabled_off
Load (avg) | 2, 1, 1
Memory (System) | 62.71GB (55.84GB free)
Process Argv | --no-sandbox --force-user-env --unity-launch --crash-reporter-id 5e036db4-7975-4920-936d-345ce33b1cab
Screen Reader | no
VM | 0%

#### Enabled extensions
Extension | Author (truncated) | Version
-- | -- | --
vscode-postgres | cko | 1.4.0
gitlens-insiders | eam | 2022.12.1304
language-cython | guy | 0.0.7
vscode-systemd-support | han | 1.0.1
vscode-edit-csv | jan | 0.7.2
vscode-docker | ms- | 1.23.2
isort | ms- | 2022.9.13271012
python | ms- | 2022.21.13431008
vscode-pylance | ms- | 2022.12.20
jupyter | ms- | 2023.1.1003441034
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.12
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-slideshow | ms- | 0.1.5
remote-containers | ms- | 0.267.0
remote-ssh | ms- | 0.94.0
remote-ssh-edit | ms- | 0.84.0
remote-wsl | ms- | 0.72.0
vscode-remote-extensionpack | ms- | 0.23.0
remote-explorer | ms- | 0.0.3
autodocstring | njp | 0.6.1
code-spell-checker | str | 2.12.0
even-better-toml | tam | 0.19.0
simple-rst | tro | 1.5.2
zoombar-vscode | wra | 1.4.2

#### A/B experiment info
```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474
pythonsymbol12:30622696
fim-prod:30623723
```

</details>

**Comment by sandy081** [comment]
Sorry that, we are not clear with our instructions for the workaround. This setting has to be placed in two different files, based on your set up:

1. If you are using VS Code **without connecting to remote** and seeing this issue, please set this setting `"extensions.verifySignature": false` in User Settings file.

<img width="702" alt="Screenshot 2022-12-14 at 08 30 51" src="https://user-images.githubusercontent.com/10746682/207533779-aa4e7209-bdf3-4f72-9e2d-e77dbdacd8b6.png">


2. If you are using VS Code **with connecting to remote** and seeing this issue, please set this setting `"extensions.verifySignature": false` in Remote Settings file.

<img width="710" alt="Screenshot 2022-12-14 at 08 34 14" src="https://user-images.githubusercontent.com/10746682/207533912-b0538e93-5666-4b25-bd69-6ee5900492e1.png">

**Comment by kramer04** [comment]
`extensions.verifySignature` is unknown.
I'm on Ubuntu 22.04 LTS

```
Version: 1.75.0-insider
Commit: 1a908707b491de77cc8408ca6d5bf626cf435736
Date: 2022-12-15T05:24:55.968Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: Yes
```
![vscode_insider1](https://user-images.githubusercontent.com/29018157/207814362-90336feb-5a6e-4b4a-8ae0-a9dcedb688f7.png)
![vscode-insider2](https://user-images.githubusercontent.com/29018157/207814393-97f375d0-a078-4dc9-ace7-fd440dd3f91c.png)

**Comment by sandy081** [comment]
It is an internal setting and thats why it is shown unknown. That's not an issue.

**Comment by omrihar** [comment]
It means you can use it, but the settings editor doesn't explicitly show it as a setting you can use. But if you type it in and save it, it should work.

**Comment by kramer04** [comment]
Thanks now i understand and it works for me

**Comment by MatiasDuhalde** [comment]
> After setting the `"extensions.verifySignature": false` in your settings, note that reloading the window via the command palette does not work. You have to restart vscode.

Thanks, I was only using the command palette, I thought it would have been enough.

**Comment by zS1L3NT** [comment]
`"extensions.verifySignature": false,` is not working for me, I get a mix of `Signature: UnknownError` and `UnkonwnError: Signature: UnknownError` in the logs. This is making development on Linux impossible for me

**Comment by omrihar** [comment]
Did you put it in the user settings or the workspace settings? I put it initially in the workspace settings and it didn't work, then put it in the user sittings which did the trick.

**Comment by Nexus6** [comment]
I've had this exact problem for at least a week now. Acting on the suggestions above, I edited
~/.config/Code\ -\ Insiders/User/settings.json
... added the work-around setting, restarted vscode, and the formerly-failing extension updates completed successfully. Thanks for the help.

**Comment by Nexus6** [comment]
I'm running:

Version: 1.75.0-insider
Commit: 6ed4d436a9b6ae131732f4e2a723868231f4473a
Date: 2022-12-23T05:28:27.642Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: Yes

In my User/settings.json file, I commented-out the extensions.verifySignature setting and restarted VSCode.  I had to wait for some extension updates to become available and eventually a few MS+Python-related ones came up.  Upon trying to apply the updates, I'm getting the "[error] UnknownError: Signature: UnknownError" message in the logs and seeing error popups in the UI again.  Does this Snap not have the fix in it? If so, what would be the least-painful way of getting a build with the fix?

**Comment by isidorn** [comment]
@Nexus6 that snap does not have a fix in it. I suggest to just get an insiders build from this year 2023 and you should be good. It should be available from our site.
For example this one  https://az764295.vo.msecnd.net/insider/6d40104789d03d41b8866a1e57847dae14c5cf0d/code-insider-x64-1673503516.snap
