### ISSUE TITLE
Verifying signed extension fails

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#164707]
Testing #164452

* win arm64 VM
* try to install any extensions
* see the error below

```
2022-10-26 13:34:39.322 [error] Invalid: Cannot install 'mayankmaheshwari.prettier-vscode1' extension because of version mismatch in Marketplace
    at $.checkAndGetCompatibleVersion (vscode-file://vscode-app/c:/Users/jrieken/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:96873)
    at async $.installFromGallery (vscode-file://vscode-app/c:/Users/jrieken/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:86770)
```

**Comment by gjsjohnmurray** [comment]
Similar to #164680

**Comment by jrieken** [comment]
Invalid: used the wrong extension to test this
