### ISSUE TITLE
Should verifying signed extensions work in the web?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164732]
Testing #164452

1. Install [nikhgup1.vscode-pull-request-github123](https://marketplace.vsallin.net/items?itemName=nikhgup1.vscode-pull-request-github123) in insiders.vscode.dev
2. :bug: extension fails to install
```
2022-10-26 10:55:03.971 [error] Cannot find the package.json from the location 'https://nikhgup1.vscode-unpkg.net/nikhgup1/vscode-pull-request-github123/0.53.2022102420/extension'. Error: Error: Cannot find the package.json from the location 'https://nikhgup1.vscode-unpkg.net/nikhgup1/vscode-pull-request-github123/0.53.2022102420/extension'. Error
    at H.toWebExtension (https://main.vscode-cdn.net/insider/c3eebaead9d3bf1cb961b91fca1b8af31990d328/out/vs/workbench/workbench.web.main.js:3244:119305)
    at async H.addExtensionFromGallery (https://main.vscode-cdn.net/insider/c3eebaead9d3bf1cb961b91fca1b8af31990d328/out/vs/workbench/workbench.web.main.js:3244:115681)
    at async g.doRun (https://main.vscode-cdn.net/insider/c3eebaead9d3bf1cb961b91fca1b8af31990d328/out/vs/workbench/workbench.web.main.js:3245:7804)
```

**Comment by sandy081** [comment]
We do not support verifying signed extensions in web, they will be installed without being verified. You are seeing this error because PPE is not supported in web.
