### ISSUE TITLE
Remote tunnel timed out looking for socket

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164830]
I turned on tunnel access, copied the insiders.vscode.dev link, and pasted it to the browser. I then saw this in the browser logs (and the whole time the explorer was spinning):

```
workbench.web.main.js:606   ERR [remote-connection][ExtensionHost][c4895…][initial][tunneling+DESKTOP-DF7ANEQ:443] socketFactory.connect() failed or timed out. Error:
workbench.web.main.js:606   ERR Error: WrappedError(WrappedError { message: "timed out looking for socket", original: "deadline has elapsed" })
    at Object.resolve (webOpener.js:1:71465)
    at webOpener.js:1:71032
workbench.web.main.js:606   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:606   ERR Error: WrappedError(WrappedError { message: "timed out looking for socket", original: "deadline has elapsed" })
    at Object.resolve (webOpener.js:1:71465)
    at webOpener.js:1:71032
workbench.web.main.js:606   ERR Error while registering log channel file:///20221027T141617/ptyhost.log Timed out while waiting for file to be created
workbench.web.main.js:3246 
        
       The customer named _initialize has been holding on to the lock for 30s. This might be a problem.
(anonymous) @ workbench.web.main.js:3246
workbench.web.main.js:606   ERR [remote-connection][ExtensionHost][e9368…][initial][tunneling+DESKTOP-DF7ANEQ:443] socketFactory.connect() failed or timed out. Error:
workbench.web.main.js:606   ERR Error: WrappedError(WrappedError { message: "timed out looking for socket", original: "deadline has elapsed" })
    at Object.resolve (webOpener.js:1:71465)
    at webOpener.js:1:71032
workbench.web.main.js:606   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:606   ERR Error: WrappedError(WrappedError { message: "timed out looking for socket", original: "deadline has elapsed" })
    at Object.resolve (webOpener.js:1:71465)
    at webOpener.js:1:71032
workbench.web.main.js:606   ERR Error received from starting extension host (kind: Remote)
workbench.web.main.js:606   ERR The remote extenion host took longer than 60s to send its ready message.
```

Reloading the page fixed things.

**Comment by aeschli** [comment]
The stack trace doesn't help me much here. Let's see if we get it again. Closing for now.
