### ISSUE TITLE
Error: t.headers is not iterable

### ISSUE THREAD

**Issue by nikelborm** [microsoft/vscode#164819]
installed extension, opened folder, curiously tried to open any github repo from vs code command `Remote repositories: Open remote repository...` and then chose `open repository`
and then saw this error

![Screenshot_20221023_121011](https://user-images.githubusercontent.com/29357907/197384177-a8acf776-346d-405c-b74d-1b845ca96fa5.png)

**Comment by joyceerhl** [comment]
From the callstack in https://github.com/RapidAPI/feedback/issues/72 and https://github.com/microsoft/vscode/issues/163214#issuecomment-1274498175 it looks like this is related to the built-in GitHub extension.

```
ERR [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
workbench.desktop.main.js:87 [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
```

@nikelborm you should be able to get unblocked by temporarily disabling `RapidAPI.vscode-rapidapi-client`.

**Comment by Rafeqm** [comment]
I confirm this solve the issue. Thanks.

**Comment by nikelborm** [comment]
I also confirm that disabling rapidapi helps

**Comment by estruyf** [comment]
On Monday, we released an update that replaces the dependency causing this issue. Once you got `1.7.0` installed, you should not be experiencing this issue anymore.

**Comment by nikelborm** [comment]
Great! Thank you!

**Comment by lszomoru** [comment]
Closing this based on [this comment](https://github.com/microsoft/vscode/issues/164819#issuecomment-1299825958).
