### ISSUE TITLE
After VS code  1.72.2 update, remote SSH not working with any of my remote machines.

### ISSUE THREAD

**Issue by santhoshcameo** [microsoft/vscode#164930]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.72.2 
- OS Version: Mac OS Monterey, 12.6 (21G115)
- Remote - SSH Version `v0.90.1`
- Detailed info:
         

                    -         Version: 1.72.2 (Universal)
                    -         Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
                    -         Date: 2022-10-12T22:16:30.254Z (2 wks ago)
                    -         Electron: 19.0.17
                    -         Chromium: 102.0.5005.167
                    -         Node.js: 16.14.2
                    -         V8: 10.2.154.15-electron.0
                    -         OS: Darwin x64 21.6.0
                    -         Sandboxed: No

Steps to Reproduce:

1.  I was using 1.65 including remote ssh extension without any issues
2.  received an update requets today and update the vs code
3.  The remote SSH is no more working, but I can ssh into them via terminal as usual, just the remote SSH extension not working

### my settings.json

```
{
    "python.formatting.provider": "black",
    "editor.formatOnSave": true,
    "window.zoomLevel": 2,
    "python.formatting.autopep8Path": "",
    "terminal.integrated.profiles.osx": "/bin/sh",
    "files.autoSave": "afterDelay",
    "remote.SSH.connectTimeout": 60,
    "terminal.integrated.profiles.linux": "/bin/bash",
    "editor.defaultFormatter": "ms-python.python",
    "[vue]": {
        "editor.defaultFormatter": "octref.vetur"
    },
    "debug.allowBreakpointsEverywhere": true,
    "[python]": {
        "editor.defaultFormatter": "ms-python.python"
    },
    "redhat.telemetry.enabled": true,
    "workbench.colorTheme": "Visual Studio Light",
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "remote.extensionKind": {

        "pub.name": [
            "ui"
        ]
    },
    "remote.portsAttributes": {
    

    

    

        "443": {
            "protocol": "https"
        },
        "8443": {
            "protocol": "https"
        }
    },
    "remote.SSH.remoteServerListenOnSocket": true,
    "remote.SSH.useLocalServer": true,
    "remote.autoForwardPorts": false
}
```

### **LOG**

it shows like setting up SSH host:  <ip> initialising VS code server, then i am getting could not establish connection error

```
[00:07:28.606] Log Level: 2
[00:07:28.607] remote-ssh@0.90.1
[00:07:28.607] darwin x64
[00:07:28.611] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 1
[00:07:28.612] "remote.SSH.useLocalServer": false
[00:07:28.612] "remote.SSH.showLoginTerminal": false
[00:07:28.612] "remote.SSH.remotePlatform": {"test-fl-fastapi-dev":"linux"}
[00:07:28.612] "remote.SSH.path": undefined
[00:07:28.612] "remote.SSH.configFile": undefined
[00:07:28.612] "remote.SSH.useFlock": true
[00:07:28.612] "remote.SSH.lockfilesInTmp": false
[00:07:28.613] "remote.SSH.localServerDownload": auto
[00:07:28.613] "remote.SSH.remoteServerListenOnSocket": true
[00:07:28.613] "remote.SSH.showLoginTerminal": false
[00:07:28.613] "remote.SSH.defaultExtensions": []
[00:07:28.613] "remote.SSH.loglevel": 2
[00:07:28.613] "remote.SSH.enableDynamicForwarding": true
[00:07:28.613] "remote.SSH.enableRemoteCommand": false
[00:07:28.613] "remote.SSH.serverPickPortsFromRange": {}
[00:07:28.613] "remote.SSH.serverInstallPath": {}
[00:07:28.622] SSH Resolver called for host: 10.128.129.75
[00:07:28.622] Setting up SSH remote "10.128.129.75"
[00:07:28.625] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:07:28.628] Install and start server if needed
[00:07:30.953] PATH: /opt/anaconda3/bin:/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
[00:07:30.953] Checking ssh with "ssh -V"
[00:07:30.958] > OpenSSH_8.6p1, LibreSSL 3.3.6

[00:07:30.960] Running script with connection command: ssh -T -D 57438 -o ConnectTimeout=60 '10.128.129.75' bash
[00:08:10.465] > client_loop: send disconnect: Broken pipe
[00:08:10.465] Got some output, clearing connection timeout
[00:08:10.676] "install" terminal command done
[00:08:10.677] Install terminal quit with output: client_loop: send disconnect: Broken pipe
[00:08:10.677] Received install output: client_loop: send disconnect: Broken pipe
[00:08:10.678] Failed to parse remote port from server output
[00:08:10.679] Resolver error: Error: 
	at g.Create (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585222)
	at t.handleInstallOutput (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:583874)
	at t.tryInstall (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643908
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:08:10.683] ------




[00:08:10.772] ------




[00:08:10.772] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 2, (Reconnection)
[00:08:10.774] SSH Resolver called for host: 10.128.129.75
[00:08:10.774] Setting up SSH remote "10.128.129.75"
[00:08:10.774] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:08:10.778] Install and start server if needed
[00:08:14.479] getPlatformForHost was canceled
[00:08:14.479] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:08:14.481] ------




[00:08:14.507] ------




[00:08:14.507] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 3, (Reconnection)
[00:08:14.508] SSH Resolver called for host: 10.128.129.75
[00:08:14.508] Setting up SSH remote "10.128.129.75"
[00:08:14.509] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:08:14.511] Install and start server if needed
[00:09:57.539] getPlatformForHost was canceled
[00:09:57.540] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:09:57.541] ------




[00:09:57.544] ------




[00:09:57.544] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 4, (Reconnection)
[00:09:57.545] SSH Resolver called for host: 10.128.129.75
[00:09:57.545] Setting up SSH remote "10.128.129.75"
[00:09:57.546] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:09:57.548] Install and start server if needed
[00:09:58.864] getPlatformForHost was canceled
[00:09:58.864] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:09:58.865] ------




[00:09:58.868] ------




[00:09:58.868] SSH Resolver called for "ssh-remote+10.128.129.75", attempt 5, (Reconnection)
[00:09:58.869] SSH Resolver called for host: 10.128.129.75
[00:09:58.869] Setting up SSH remote "10.128.129.75"
[00:09:58.869] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:09:58.871] Install and start server if needed
[00:09:59.342] getPlatformForHost was canceled
[00:09:59.342] Resolver error: Error: Connecting was canceled
	at g.Canceled (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585418)
	at /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643820
	at async t.withShowDetailsEvent (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/e230-admin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[00:09:59.343] ------



```

**Comment by schae211** [comment]
I have the same issue.
