### ISSUE TITLE
Missing localization holds up filesystem provider activation

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#165359]
1. Configure pseudolang as preferred language
2. Load insiders.vscode.dev/github/microsoft/vscode
3. :bug: see a big stall in workbench loading, 504s from unpkg service, the whole time the explorer is spinning

Logs
```
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.powershell/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.hlsl/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.html-language-features/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.theme-monokai-dimmed/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.php/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.xml/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.dart/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.perl/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.builtin-notebook-renderers/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.less/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.ini/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.typescript-language-features/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.typescript/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.julia/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.search-result/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.git-base/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.vscode-theme-seti/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.theme-abyss/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.media-preview/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.lua/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.python/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.theme-kimbie-dark/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.ruby/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.theme-defaults/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.npm/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.yaml/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.markdown-math/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
package:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 504 ()
workbench.web.main.js:608  INFO Request to 'https://www.vscode-unpkg.net/_lp/86f0f9bfa268fe21af7efae37d8f0da1dba8137f/1.74.0-insider/qps-ploc/vscode.scss/package' failed with status code 504
workbench.web.main.js:608   ERR Error
    at C.readExtensionResource (workbench.web.main.js:808:6441)
    at async i.localizeManifest (workbench.web.main.js:1592:5105)
    at async workbench.web.main.js:1592:4613
```

**Comment by TylerLeonhardt** [comment]
I think there's two parts to this:
1. I could be faster in the unpkg service. I actually found some 404s that were thrown that will be fixed with https://github.com/microsoft/vscode/pull/165436 which caused slow down... but I don't know why 504s are happening. @joaomoreno what does this typically symbolize in unpkg land?
2. @sandy081 could defer localizing manifests until later maybe

**Comment by TylerLeonhardt** [comment]
The `/_lp` route is quite faster now and is caching things better.

**Comment by sandy081** [comment]
> could defer localizing manifests until later maybe

@TylerLeonhardt Not sure what you mean by later here? Is there a specific time point you have in mind?

**Comment by TylerLeonhardt** [comment]
@sandy081 I'm not sure, honestly. Right now, we don't even see the workbench so I would expect to at least see that instead of an empty shell of a window.

**Comment by TylerLeonhardt** [comment]
I think we've done what we wanted to with this issue. I'm just going to close it unless @sandy081 you feel otherwise. The original issue (with the errors) is long gone... and we've made incremental progress here over the past 6months.

**Comment by TylerLeonhardt** [comment]
For verification:
* load insiders.vscode.dev
* set your display language to something else
* the reload should be relatively fast (it'll likely be slower as there is some additional computation to do.. but not too long) and you shouldn't see these errors in the Dev Tools.
