### ISSUE TITLE
Is the diff editor broken?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#165388]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Open a diff editor. In this case I opened a modified file from the SCM view.
2. Press F7 to go to the next change.
3. :bug: The diff editor disappeared, and I get a view of a single patch instead. The view still has red and green lines to indicate the diff, but it seems different from the diff view I'm used to seeing with two split editors.

![Screenshot showing the single patch view](https://user-images.githubusercontent.com/7199958/199774840-9e9caa2b-bb33-4a07-b9de-ba6a3b03dc00.png)

**Comment by rzhao271** [comment]
Potentially relevant console error messages:
```
ERR Model is disposed!: Error: Model is disposed!
    at An._assertNotDisposed (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:746:449)
    at An.getVersionId (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:748:3286)
    at i (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1382:10244)
    at Ts.provideCodeActions (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1382:9088)
    at async vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:707:95356
    at async Promise.all (index 5)
    at async a (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:707:95782)
```

```
 ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at An.getLineContent (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:748:5471)
    at qi._renderLine (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:743:12605)
    at qi._renderSection (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:743:11990)
    at qi._render (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:743:10142)
    at vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:743:3024
    at f.invoke (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at l.deliver (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:2266)
    at c.fire (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1844)
    at vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:762:18289
    at f.invoke (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:2266)
    at c.fire (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:1844)
    at R._emitOutgoingEvents (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:586:62875)
    at R.endEmitViewEvents (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:586:63571)
    at v._withViewEventsCollector (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:760:4911)
    at v.restoreCursorState (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:760:2942)
    at sn.restoreViewState (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:762:7660)
    at ni.restoreViewState (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:762:55820)
    at nc.restoreTextDiffEditorViewState (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2745:11853)
    at nc.setInput (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2745:11309)
    at async a.doSetInput (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2743:6429)
    at async a.doOpenEditor (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2743:4791)
    at async a.openEditor (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2743:3783)
    at async vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2970:16742
```

**Comment by rzhao271** [comment]
I think I know what happened. I ran `editor.action.diffReview.next` instead of `workbench.action.editor.nextChange`. Maybe the latter command can also be put into the command palette?

**Comment by hediet** [comment]
@rzhao271 did this change recently?

**Comment by rzhao271** [comment]
No. It doesn't seem to be a regression, because I can repro in 1.63.
I think it's a view that I haven't seen before. The view also has a close button at the top-right, but I didn't see it immediately.
![Screenshot of patch-like diff view showing close button at the top-right corner](https://user-images.githubusercontent.com/7199958/200025080-b409aab9-c7d4-4a57-a2c4-fc733c6907e7.png)

**Comment by alexdima** [comment]
This is the diff review experience built especially for screen readers. In this experience, we loop through diff hunks when pressing F7.
