### ISSUE TITLE
Timeline provider NPE

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#165362]
1. Load https://insiders.vscode.dev/github/microsoft/vscode
2. Open devtools
3. :bug: see this log message:

```
workbench.web.main.js:2596 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'renderHeight')
    at get pageSize [as pageSize] (workbench.web.main.js:2596:41502)
    at ie.clear (workbench.web.main.js:2596:44110)
    at ie.loadTimeline (workbench.web.main.js:2596:44669)
    at ie.onProvidersChanged (workbench.web.main.js:2596:43164)
    at f.invoke (workbench.web.main.js:80:145)
    at r.deliver (workbench.web.main.js:80:2559)
    at c.fire (workbench.web.main.js:80:2137)
    at I.registerTimelineProvider (workbench.web.main.js:1311:24734)
    at I.$registerTimelineProvider (workbench.web.main.js:1748:67892)
    at v._doInvokeHandler (workbench.web.main.js:1755:12970)
```

**Comment by lszomoru** [comment]
🤔 I am unable to repro this anymore. Do you still have a repro? Thanks!

**Comment by joyceerhl** [comment]
:shrug: no repro now.
