### ISSUE TITLE
verifies that auto save triggers on shutdown

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#165564]
```
 VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies that auto save triggers on shutdown:
     electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window"
      at /Users/runner/work/1/s/test/automation/src/playwrightElectron.ts:38:52
      at measureAndLog (/Users/runner/work/1/s/test/automation/src/logger.ts:52:15)
      at launchElectron (/Users/runner/work/1/s/test/automation/src/playwrightElectron.ts:38:36)
      at launch (/Users/runner/work/1/s/test/automation/src/playwrightElectron.ts:20:38)
      at measureAndLog (/Users/runner/work/1/s/test/automation/src/logger.ts:52:9)
      at launch (/Users/runner/work/1/s/test/automation/src/code.ts:85:39)
      at Application.startApplication (/Users/runner/work/1/s/test/automation/src/application.ts:107:29)
      at Application._start (/Users/runner/work/1/s/test/automation/src/application.ts:82:16)
      at Application.start (/Users/runner/work/1/s/test/automation/src/application.ts:67:3)
      at Context.testHotExit (src/areas/workbench/data-loss.test.ts:91:4)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=191895&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=82df682a-a732-590f-d041-2bbd067871c9&l=120

**Comment by bpasero** [comment]
Moving into https://github.com/microsoft/vscode-internalbacklog/issues/3272
