### ISSUE TITLE
frequent crashes [TypeScript and JavaScript Language Features]

### ISSUE THREAD

**Issue by xBoyMinemc** [microsoft/vscode#166007]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0 %8fa188b2b301d36553cbc9ce1b0a146ccb93351f %x64  

- OS Version:  21H2 for home %19044.1889  

Steps to Reproduce:  

1. open my work,some ts file
2. Press ctrl and click on some variable, or just mouse over, to see information about the variable (Indefinite time, sometimes a few minutes, sometimes longer)  
3. ![image](https://user-images.githubusercontent.com/86919167/200857654-275ad924-5dbb-4c14-9228-e9be24482f25.png)
4. Prompt to crash five times, no more restarts

normal ： ![image](https://user-images.githubusercontent.com/86919167/200858799-b5765e15-46bd-4580-9ba7-e3fc4f95f801.png)  

crash ： 
![image](https://user-images.githubusercontent.com/86919167/200859400-539dded2-d032-4227-aeff-e2c8a648d6eb.png)  
![image](https://user-images.githubusercontent.com/86919167/200859941-7d2bf88b-c793-4b2f-93a7-10aec2fec14d.png)

**Comment by xBoyMinemc** [comment]
![image](https://user-images.githubusercontent.com/86919167/201114673-81023e5b-5b6f-4f5a-8eb2-713fa2c24877.png)
Thanks, just finished the update, I'll program and wait for it happen again

**Comment by xBoyMinemc** [comment]
![image](https://user-images.githubusercontent.com/86919167/201115176-f9706859-508f-4240-9d22-7e7cf59b98b4.png)

![image](https://user-images.githubusercontent.com/86919167/201115150-7aeb58bd-a792-4754-b7eb-27b85efc490c.png)

  
maybe restart again？

**Comment by xBoyMinemc** [comment]
https://user-images.githubusercontent.com/86919167/201116082-0b80a17d-0a38-462a-a248-100701f38a41.mp4

  
Please teach me how to provide more information

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by xBoyMinemc** [comment]
> 

yes, 1.17.31 Updated eight hours ago,and disable all extensions, Even includes language adaptation packages

How can I provide more useful information next?

-------

**Comment by xBoyMinemc** [comment]
maybe reinstall？
i updataed by VS Code setting.

**Comment by mjbvz** [comment]
Please test in VS Code insiders. This should be VS Code 1.74

**Comment by xBoyMinemc** [comment]
funny,look this ,but before 4.8.4
![image](https://user-images.githubusercontent.com/86919167/201317866-1c7c2d86-efd7-42ea-8e67-bde8543a3bee.png)
  i just do no thing and ready to Update in VS Code insiders.

OHHH
VS Code insiders work well, but I'll watch for a few days

--thanks

**Comment by xBoyMinemc** [comment]
ohhh,funny again
![image](https://user-images.githubusercontent.com/86919167/201321303-e237be26-0f22-4efb-bad4-4213ad49d297.png)
VS Code insiders work wrong :(  
i just want to finsh my toys

**Comment by xBoyMinemc** [comment]
TS Server fatal error:  path.charCodeAt is not a function

Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.9.2-rc

**Steps to reproduce crash**

1.i do no thing  
2.just open my VSC  with my working files
3.https://github.com/microsoft/vscode/issues/166007  

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
TypeError: path.charCodeAt is not a function
    at getEncodedRootLength (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7693:24)
    at getRootLength (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7770:26)
    at combinePaths (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7964:26)
    at getPathComponents (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7875:16)
    at getNormalizedPathComponents (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8003:37)
    at Object.getNormalizedAbsolutePath (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8007:42)
    at normalizeNonListOptionValue (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42889:24)
    at normalizeOptionValue (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42885:16)
    at c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42878:70
    at Object.map (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:460:29)
    at normalizeOptionValue (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42878:37)
    at Object.onSetValidOptionKeyValueInParent (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42702:46)
    at _loop_4 (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41961:56)
    at convertObjectLiteralExpressionToJson (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41979:17)
    at convertPropertyValueToJson (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42038:46)
    at _loop_4 (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41948:29)
    at convertObjectLiteralExpressionToJson (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41979:17)
    at convertPropertyValueToJson (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42038:46)
    at convertToObjectWorker (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41920:16)
    at convertConfigFileToObject (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41900:16)
    at parseOwnConfigOfJsonSourceFile (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42723:20)
    at parseConfig (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42619:13)
    at parseJsonConfigFileContentWorker (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42435:28)
    at Object.parseJsonSourceFileConfigFileContent (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42398:22)
    at ProjectService.ensureParsedConfigUptoDate (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177091:44)
    at ProjectService.loadConfiguredProject (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177036:52)
    at ProjectService.createAndLoadConfiguredProject (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177017:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177022:36)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178108:44)
    at c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178448:97
    at Object.flatMap (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178448:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179820:46)
    at c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182013:96
    at Session.executeWithRequestId (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182004:28)
    at Session.executeCommand (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182013:41)
    at Session.onMessage (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182041:35)
    at process.<anonymous> (c:\Users\云梦\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:186197:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.74.0-insider (ef415578d1b1019db585718968a303eeca4b8979, 2022-11-11T05:19:14.666Z)
OS version: Windows_NT x64 10.0.19044
Modes: Unsupported
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.36GB (6.22GB free)|
|Process Argv|--crash-reporter-id cc0b8585-06d6-4f4a-a213-2b30959be61a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30602959
pylantcb52:30590116
vsccc:30564266
pyindex848:30577858
nodejswelcome1:30587009
gswce1:30602633
34cci188:30599831
pyind779cf:30600160
dbltrim-noruby:30604474

```

</details>

**Comment by xBoyMinemc** [comment]
and>>>
![image](https://user-images.githubusercontent.com/86919167/201323864-62cb2789-aa95-42be-bc49-d3875a091d18.png)
![image](https://user-images.githubusercontent.com/86919167/201323884-bbe572c0-195d-4045-9b90-55c66afc0437.png)
what's happen?  CPU BOOM

after kill it:
![image](https://user-images.githubusercontent.com/86919167/201324029-aac7b2dc-1155-4a29-9f07-3d4fd83d622e.png)

**Comment by xBoyMinemc** [comment]
any some body here?

Can't work by this for six days   ):

**Comment by ahilmathew** [comment]
Having the same issue - 
![image](https://user-images.githubusercontent.com/17005535/201644601-2251aa3e-ca08-4acf-bd75-0cc39b0a9333.png)
