### ISSUE TITLE
Settings Sync reset the profile state after updating VS Code

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#166101]
After restarting VS Code today for update, settings sync reset profile state of one of my profiles.  I do not know how it happened, but one suspicion is that it can happen if storage service does not return proper data.

**Comment by bpasero** [comment]
@sandy081 you can figure out if an in-memory storage is used by checking for presence of `path` on `IStorageMain`:

https://github.com/microsoft/vscode/blob/edccbd1307ef8055f26778c5a86f9eef885bc6ff/src/vs/platform/storage/electron-main/storageMain.ts#L66-L69

If there is no path on disk it means the storage is in-memory. We should then disable syncing.

**Comment by zhGio** [comment]
I also have issues with settings syncing.
1. whatever I change i just get instantly reverted back to the last state i had after i close settings.json
2. i can't disable & clear synced cloud data, sync logs saying `Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/collection","status":404}` 
```
[error] Unknown (UserDataSyncError) syncResource:unknown operationId:unknown: Server returned 404
    at E.request (vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:174752)
    at async E.deleteCollection (vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167237)
    at async E.clear (vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:171115)
    at async a.resetRemote (vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:142670)
    at async a.reset (vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:142574)
    at async C.turnOff (vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:91558)
```

any ideas on how i could clear my cloud settings in another way?

**Comment by sandy081** [comment]
@zhGio I think your issue is not related to this. Can you please file a separate issue and provide us clear information of the bug and how to reproduce ?

**Comment by sandy081** [comment]
@bpasero It seems `path` may not be `undefined` when the storage is in-memory

https://github.com/microsoft/vscode/blob/dbc3941061693865e9dcc1f146900d9e7d719b3c/src/vs/platform/storage/electron-main/storageMain.ts#L267-L272

From above code, path is always set unless `useInMemoryStorage` option is set to `true`. But it can happen that in memory storage can be active when there is an error creating sqlite storage. 

May I also know when VS Code can be started with `useInMemoryStorage` option?

**Comment by bpasero** [comment]
@sandy081 did you try? I think it should be fine because here it returns `undefined`:

https://github.com/microsoft/vscode/blob/3a52e79cead6fa54139f5d0098c3380c6546ab4a/src/vs/platform/storage/electron-main/storageMain.ts#L419-L421

**Comment by bpasero** [comment]
Good catch, looks like some changes are needed there.

**Comment by bpasero** [comment]
@sandy081 https://github.com/microsoft/vscode/pull/167298 adds a `isInMemory` method based on a new `StorageHint.STORAGE_IN_MEMORY`. This hint is set when:
* options demand in-memory storage
* we fail to init storage and keep using the initial in-memory storage

**Comment by zhGio** [comment]
> @zhGio I think your issue is not related to this. Can you please file a separate issue and provide us clear information of the bug and how to reproduce ?

Alright, but could I to remedy this somehow, force delete all my remote settings (or can i post a ticket somewhere so someone else does it) so I could have a fresh start?

**Comment by sandy081** [comment]
@zhGio You can use this link https://code.visualstudio.com/docs/editor/settings-sync#_how-do-i-delete-my-data to delete all your data on server.

**Comment by sandy081** [comment]
I have not seeing this issue any more. Hence closing this.

**Comment by TylerLeonhardt** [comment]
I haven't seen this either. Marking as verified.
