### ISSUE TITLE
OSError: [WinError 4393] The tag present in the reparse point buffer is invalid:

### ISSUE THREAD

**Issue by vincent-gonzales** [microsoft/vscode#166127]
This just started last night. I do not remeber any updates but it could have happened. I was writing code and debugging a deciosion tree but not sure that mattered. When I saw the error I created a new py script locally on the desktop but still got the error in debug. I even made a very simple program on my desktop (see below) and the same thing happens. Just running script is fine but debug I get the error below.

running simple py script
print("hi")
print("hi2")

Just running code by hitting triangle
PS C:\Users\vincent-gonzales> & C:/Users/vincent-gonzales/AppData/Local/Programs/Python/Python310/python.exe c:/Users/vincent-gonzales/Desktop/tmp.py
hi
hi2
PS C:\Users\vincent-gonzales> 

works fine but putting a breakpoint and running it in debug I get the following. I did see that the break point did not matter if it was there or not. It also is immediate.

PS C:\Users\vincent-gonzales\Desktop>
PS C:\Users\vincent-gonzales\Desktop>  c:; cd 'c:\Users\vincent-gonzales\Desktop'; & 'C:\Users\vincent-gonzales\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '62762' '--' 'c:\Users\vincent-gonzales\Desktop\tmp.py' 
Traceback (most recent call last):
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 831, in get_abs_path_real_path_and_base_from_file
    return NORM_PATHS_AND_BASE_CONTAINER[filename]
KeyError: 'c:\\Users\\vincent-gonzales\\OneDrive - University of Tulsa\\classes\\CS-6863-01 ST Stat Lrn & Nrl Ntwks\\hmwk\\testing\\dt.v.1.0.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 385, in _abs_and_canonical_path
    return NORM_PATHS_CONTAINER[filename]
KeyError: 'c:\\Users\\vincent-gonzales\\OneDrive - University of Tulsa\\classes\\CS-6863-01 ST Stat Lrn & Nrl Ntwks\\hmwk\\testing\\dt.v.1.0.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vincent-gonzales\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 660, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 4393] The tag present in the reparse point buffer is invalid: 'c:\\Users\\vincent-gonzales\\OneDrive - University of Tulsa\\classes\\CS-6863-01 ST Stat 
Lrn & Nrl Ntwks\\hmwk\\testing\\dt.v.1.0.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 252, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 193, in process_net_command_json
    cmd = on_request(py_db, request)
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 785, in on_setbreakpoints_request
    result = self.api.add_breakpoint(
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 484, in add_breakpoint
    translated_absolute_filename = pydevd_file_utils.absolute_path(translated_filename)
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 372, in absolute_path
    return get_abs_path_real_path_and_base_from_file(filename)[0]
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 852, in get_abs_path_real_path_and_base_from_file
    abs_path, canonical_normalized_filename = _abs_and_canonical_path(f)
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 411, in _abs_and_canonical_path
    real_path = _apply_func_and_normalize_case(filename, os_path_real_path, isabs, normalize)
  File "c:\Users\vincent-gonzales\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 438, in _apply_func_and_normalize_case
    r = func(filename)
  File "C:\Users\vincent-gonzales\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 666, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\vincent-gonzales\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 614, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 4393] The tag present in the reparse point buffer is invalid: 'c:\\Users\\vincent-gonzales\\OneDrive - University of Tulsa\\classes\\CS-6863-01 ST Stat 
Lrn & Nrl Ntwks\\hmwk\\testing\\dt.v.1.0.py'

**Comment by roblourens** [comment]
This sounds like a OneDrive issue, maybe try making sure onedrive is logged in, has the files downloaded, search for that `The tag present in the reparse point buffer is invalid` error message, or copy the files to a local folder.

If that doesn't help, please open an issue on the Python extension repo
