### ISSUE TITLE
Flaky Interactive Window

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#166291]
These tests seem to depend on the window being focused, when the window is in the background they fail (macOS):

```
1) Interactive Window
       Interactive window scrolls after execute:
     Error: asPromise TIMEOUT reached
      at asPromise (extensions/vscode-api-tests/src/utils.ts:128:16)
      at addCellAndRun (extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:38:25)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:90:4)

  2) Interactive Window
       Interactive window has the correct kernel:
     Error: asPromise TIMEOUT reached
      at asPromise (extensions/vscode-api-tests/src/utils.ts:128:16)
      at addCellAndRun (extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:38:25)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:110:3)
```

**Comment by amunger** [comment]
hopefully fixed with that change - verified by forcing IW blur when running locally and it did repro without the change.
