### ISSUE TITLE
VSCode gdb debugging throw System.ArgumentNullException

### ISSUE THREAD

**Issue by Wulgryn** [microsoft/vscode#166401]
- VS Code Version: 
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64

- OS Version: Windows 11 Pro 21H2 22000.1219

I made a launch.json with gdb debug, and everything worked fine _(enviroment-cd still can't use UTF-8 / UNICODE characters)_ ,then saw on stackoverflow that i can turn on Beta: UTF-8 pack in Date and regions and tried if it can solvethe "enviroment-cd" problem. But it made it worse. Now i get an error what i can't even solve even turned off that beta setting and it's still the same.

The trace:
```
1: (73) LaunchOptions{"name":"Vsc Launch1","type":"cppdbg","request":"launch","program":"C:\\Users\\User\\Desktop\\Google Drive\\Code\\C++\\.VSCode\\sol/.bin/main/App.exe","cwd":"C:\\Users\\User\\Desktop\\Google Drive\\Code\\C++\\.VSCode\\sol","MIMode":"gdb","miDebuggerPath":"C:\\msys64\\mingw64\\bin\\gdb.exe","logging":{"trace":true,"engineLogging":true,"exceptions":true,"moduleLoad":true,"programOutput":true,"traceResponse":false},"externalConsole":false,"internalConsoleOptions":"openOnSessionStart","setupCommands":[{"description":"show charset"},{"description":"show charset"},{},{}],"__configurationTarget":6,"__sessionId":"ed74270e-d779-4007-a093-6e1d47e0d6fd"}
1: (132) EXCEPTION: System.ArgumentNullException
1: (132) EXCEPTION:    at MICore.LaunchCommand..ctor(String commandText, String description, Boolean ignoreFailures, Action`1 failureHandler, Func`2 successHandler, Func`2 successResultsHandler)
1: (132) EXCEPTION:    at MICore.LaunchCommand.<>c.<CreateCollection>b__17_0(SetupCommand x)
1: (132) EXCEPTION:    at System.Linq.Enumerable.SelectListIterator`2.ToList()
1: (132) EXCEPTION:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
1: (132) EXCEPTION:    at MICore.LaunchCommand.CreateCollection(List`1 source)
1: (132) EXCEPTION:    at MICore.LaunchOptions.InitializeCommonOptions(BaseOptions options)
1: (132) EXCEPTION:    at MICore.LocalLaunchOptions.CreateFromJson(JObject parsedOptions)
1: (132) EXCEPTION:    at MICore.LaunchOptions.GetInstance(HostConfigurationStore configStore, String exePath, String args, String dir, String options, Boolean noDebug, IDeviceAppLauncherEventCallback eventCallback, TargetEngine targetEngine, Logger logger)
1: (132) EXCEPTION:    at Microsoft.MIDebugEngine.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngineLaunch2.LaunchSuspended(String pszServer, IDebugPort2 port, String exe, String args, String dir, String env, String options, enum_LAUNCH_FLAGS launchFlags, UInt32 hStdInput, UInt32 hStdOutput, UInt32 hStdError, IDebugEventCallback2 ad7Callback, IDebugProcess2& process)
1: (134) Send Event AD7MessageEvent
```
What should i do?

**Comment by Wulgryn** [comment]
I managed to solve it:

```
{
        "type": "cppdbg",
        "request": "launch",
        "name": "Launch gdb",
        "program": "${workspaceFolder}/.bin/main/App.exe",
        "args": [],
        "cwd": "${workspaceFolder}",
        "preLaunchTask": "Build apps",
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
        "externalConsole": false,
        "setupCommands": [
            {
                "description": "show charset",
                //"text": "set target-charset UTF-16"
            },
            {
                "description": "show charset",
                //"text": "set host-charset UTF-16"
            },
            {
                "text": "--enable-pretty-printing"
            }
        ]
    }
```

The issue was the _setupCommands_ section. In that where it only had a description, it searched for a "text" too but it couldn't find it so returned an ArgumentNullException.

**But i still think it's an issue without proper warning.**

**Comment by roblourens** [comment]
If you think there's an issue here, please open an issue on the cppdbg extension
