### ISSUE TITLE
Flaky smoke test: verifies quick outline

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#166502]
macOS Electron smoke tests

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=193221&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=ed595fa9-bdca-5f35-a51a-12f92e4d7421&l=83

```
  1) VSCode Smoke Tests (Electron)
       Language Features
         verifies quick outline (js):
     Error: Timeout: get text content '.quick-input-widget .quick-input-list .monaco-list-row .monaco-highlighted-label' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:269:11)
      at runNextTicks (node:internal/process/task_queues:61:5)
      at processTimers (node:internal/timers:499:9)
      at Code.waitForTextContent (/Users/runner/work/1/s/test/automation/src/code.ts:201:10)
      at QuickAccess.openQuickOutline (/Users/runner/work/1/s/test/automation/src/quickaccess.ts:193:17)
      at Context.<anonymous> (src/areas/languages/languages.test.ts:20:4)
```

**Comment by joaomoreno** [comment]
Similar to https://github.com/microsoft/vscode/issues/138045
