### ISSUE TITLE
The mark 'input/start' does not exist

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#166800]
Seeing this in playwright smoke tests:

```
Playwright (Electron): window.on('console') [%c  ERR color: #f33 Failed to execute 'measure' on 'Performance': The mark 'input/start' does not exist.: Error: Failed to execute 'measure' on 'Performance': The mark 'input/start' does not exist.
    at s (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3:202560)
    at Object.C [as onKeyDown] (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3:201752)
    at vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:553:1454
    at u.invoke (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at n.deliver (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:2559)
    at h.fire (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:2137)
    at HTMLTextAreaElement.D (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:10798)]
```

**Comment by Tyriar** [comment]
I couldn't reproduce, I also looked over the code and it's not clear how that could happen. Let me know if you see it again.
