### ISSUE TITLE
ERR Cannot read properties of undefined (reading 'completion')

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#167548]
VS Code Insiders, macOS

1. New user profile
2. Open any typescript file. For example `editor.ts`
3. write `this.` -> exception in the dev tools console 🐛 

```
 ERR Cannot read properties of undefined (reading 'completion'): TypeError: Cannot read properties of undefined (reading 'completion')
    at i (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:770:149590)
    at C.m (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:770:148877)
    at C.l (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:770:148670)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:770:148450
    at u.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at s.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at d.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:770:122434
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:89:16881
```

**Comment by jrieken** [comment]
I can only reproduce with 

0. configure `"editor.suggest.selectQuickSuggestions": false`

**Comment by isidorn** [comment]
Thanks for fixing. Somehow that setting was still applied even though I was using a new profile...
