### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167536]
Testing #167439

Saw this when playing with the setting, not sure if related:

```
openEditorsView.ts:100 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at N.a (openEditorsView.ts:100:34)
    at N.h (async.ts:886:8)
    at N.g (async.ts:881:9)
```

**Comment by bpasero** [comment]
Follow up: https://github.com/microsoft/vscode/issues/172141
