### ISSUE TITLE
Event listener leak in `onDidChangeEnablement`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167535]
```
4cf] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
event.ts:658 Error
    at i.create (event.ts:671:25)
    at l.l [as onDidChangeEnablement] (event.ts:795:25)
    at event.ts:155:97
    at Array.map (<anonymous>)
    at event.ts:155:84
    at new Pc (extensionsActions.ts:433:88)
    at l.j (instantiationService.ts:119:18)
    at l.createInstance (instantiationService.ts:85:18)
    at new ge (extensionsActions.ts:530:26)
    at l.j (instantiationService.ts:119:18)
    at l.createInstance (instantiationService.ts:85:18)
    at n.renderTemplate (extensionsList.ts:124:11)
    at E.renderTemplate (listPaging.ts:36:23)
    at listWidget.ts:1114:28
    at Array.map (<anonymous>)
    at Y.renderTemplate (listWidget.ts:1114:17)
    at L.alloc (rowCache.ts:40:34)
    at f.W (listView.ts:794:29)
    at f.Q (listView.ts:576:10)
    at f.splice (listView.ts:478:16)
    at splice.ts:17:25
    at Array.forEach (<anonymous>)
    at t.splice (splice.ts:17:10)
    at listWidget.ts:1442:36
    at v.bufferEvents (event.ts:1197:13)
    at q.splice (listWidget.ts:1442:10)
    at set model [as model] (listPaging.ts:204:10)
    at ae.Wc (extensionsViews.ts:992:11)
    at extensionsViews.ts:267:10
```

**Comment by sandy081** [comment]
This event is no longer being used.
