### ISSUE TITLE
Notebook ends up corrupted after switching profiles

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#167644]
Testing #167161

1. Open a `.github-issues` notebook and make an edit so that the notebook is dirty (make sure auto save is disabled)
3. Create a new blank profile (or switch to a profile that doesn't have the GitHub issues notebook extension installed)

**Bug**
The notebook remains open but we also see an alert about saving it:

![Screenshot 2022-11-29 at 2 40 01 PM](https://user-images.githubusercontent.com/12821956/204664347-491a0aa1-7570-4adc-96c4-1f066674738c.png)

Before you accept anything in the modal, the profile is switched and the notebook ends up going into a corrupt state. In the dev tools I see lots of errors like the following:

```
  ERR unknown text editor: d29be57b-7f28-4c18-b6a1-42f1323683c2. known editors:  : Error: unknown text editor: d29be57b-7f28-4c18-b6a1-42f1323683c2. known editors:  
	at f.getEditorById (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:78486)
	at A.$acceptEditorPropertiesChanged (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:42135)
	at u.N (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
	at u.M (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
	at u.H (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10019)
	at u.G (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:9000)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
	at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at w.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
	at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at w.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13960)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
```

And

```
ERR unknown text editor: d29be57b-7f28-4c18-b6a1-42f1323683c2. known editors:  : Error: unknown text editor: d29be57b-7f28-4c18-b6a1-42f1323683c2. known editors:  
	at l.getEditorById (../../../vs/workbench/api/worker/extensionHostWorker.js:78:78486)
	at L.$acceptEditorPropertiesChanged (../../../vs/workbench/api/worker/extensionHostWorker.js:76:41724)
	at d.N (../../../vs/workbench/api/worker/extensionHostWorker.js:78:183185)
	at d.M (../../../vs/workbench/api/worker/extensionHostWorker.js:78:182903)
	at d.H (../../../vs/workbench/api/worker/extensionHostWorker.js:78:181996)
	at d.G (../../../vs/workbench/api/worker/extensionHostWorker.js:78:180977)
	at eval (../../../vs/workbench/api/worker/extensionHostWorker.js:78:179765)
	at _.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:16:145)
	at v.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:16:2033)
	at F.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:16:1671)
	at r.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:85:3965)
```

**Comment by sandy081** [comment]
@rebornix When switching profile, I take down ext host and restart so that it starts with new set of extensions. Not sure if notebooks might be depending on something or not disposing stuff. Can you please investigate first from your side and let me know if there is anything that can be done from my side?

**Comment by rebornix** [comment]
@sandy081 I'm not sure if taking down ext host is the right thing, but this also happens when we reload/navigate on .dev, let's track this issue in https://github.com/microsoft/vscode/issues/156459

**Comment by sandy081** [comment]
Otherwise, I have to reload window and I think it is not a good user experience. Restarting an extension host is not something new and we do it for other features like workspace trust and we also have a command to do that. IMO all components shall be prepared for this.
