### ISSUE TITLE
Long running searches with many matched files do not include all files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16760]
#16416

- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T17:07:24.668Z)
- OS Version: Linux x64 4.8.0-28-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|typescript-javascript-grammar|ms-vscode|0.0.10|
|sass-indented|robinbentley|1.2.1|
|dark-plus-material|vangware|0.1.4|

---

Steps to Reproduce:

1. Open vscode repo
2. Search for `t`
3. Wait
4. Wait
5. View "complete" list, it only contains a handful of files

Related: https://github.com/Microsoft/vscode/issues/16759

**Comment by Tyriar** [comment]
A whole bunch of IPC errors in console:

```
ipc.cp.ts:145 [IPC Library: Search] Uncaught Exception:  Error: Cannot read property 'cancel' of undefined

TypeError: Cannot read property 'cancel' of undefined,    at e.cancel (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:16105),    at e.call (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:19996),    at t.e.onCommonRequest (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:7909),    at t.e.onMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:7745),    at /usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:7538,    at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:4:28010),    at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:5:745),    at process.i (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:2825),    at emitTwo (events.js:106:13),    at process.emit (events.js:191:7)(anonymous function) @ ipc.cp.ts:145e.invoke @ callbackList.ts:63e.fire @ event.ts:117r @ event.ts:12emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
ipc.cp.ts:145 [IPC Library: Search] Error: Cannot read property 'cancel' of undefined

TypeError: Cannot read property 'cancel' of undefined,    at e.cancel (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:16105),    at e.call (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:19996),    at t.e.onCommonRequest (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:7909),    at t.e.onMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:7745),    at /usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:7538,    at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:4:28010),    at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:5:745),    at process.i (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/worker/searchWorkerApp.js:6:2825),    at emitTwo (events.js:106:13),    at process.emit (events.js:191:7)
    at Timeout._onTimeout (/usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/searchApp.js:23:15082)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```
