### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by chulgyun** [microsoft/vscode#167697]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20221117

**Steps to reproduce crash**
1.
2.
3.

**Global TS Server Plugins**

- `typescript-deno-plugin`
- `@twind/typescript-plugin`
- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`

**TS Server Log**
❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:107383:13)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:107482:21)
    at Map.forEach (<anonymous>)
    at Object.startCachingPerDirectoryResolution (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:107074:44)
    at InferredProject2.updateGraphWorker (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:153237:28)
    at InferredProject2.updateGraph (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:153178:34)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:155211:15)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:156594:14)
    at /Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:156825:66
    at flatMap (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:2953:19)
    at _ProjectService.applyChangesInOpenFiles (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:156825:26)
    at updateOpen (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:157908:31)
    at /Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:160072:71
    at IpcIOSession.executeWithRequestId (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:160064:16)
    at IpcIOSession.executeCommand (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:160072:31)
    at IpcIOSession.onMessage (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:160100:53)
    at process.<anonymous> (/Users/cg.roh/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202211170/node_modules/typescript/lib/tsserver.js:161659:16)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 2251e8af-e727-48de-8a3a-7c7ee33e13db|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.15.9
ng-template|Ang|15.0.1
clojure|avl|0.13.2
npm-intellisense|chr|1.4.3
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
vscode-deno|den|3.14.1
gitlens|eam|13.1.1
prettier-vscode|esb|9.9.0
comment-anchors|Exo|1.10.1
remotehub|Git|0.46.0
nodejs-repl|los|0.5.15
Kotlin|mat|1.7.1
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.23.0
vscode-language-pack-ko|MS-|1.73.11090913
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.2
remote-repositories|ms-|0.24.0
vscode-typescript-next|ms-|5.0.202211170
vscode-react-native|msj|1.10.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.40.0
material-icon-theme|PKi|4.22.0
java|red|1.12.0
vscode-yaml|red|1.10.1
twind-intellisense|sas|0.2.1
type-doc-vscode|Tre|0.0.35
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.0
vscode-spring-boot-dashboard|vsc|0.9.0
vscode-spring-initializr|vsc|0.11.1
vim|vsc|1.24.3

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
