### ISSUE TITLE
Command 'Create new jupyter notebook' resulted in an error

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167779]
Testing microsoft/vscode-jupyter#11963

This is familiar, there might be an issue for this, but I'm not sure and can't find it

I just ran the command and closed the  new untitled notebook over and over then got this

<img width="559" alt="image" src="https://user-images.githubusercontent.com/323878/204915962-d3a58a66-3809-4ac6-81a3-7289222545c5.png">

```
2022-11-30 15:50:58.937 [error] NO notebook document for 'untitled:Untitled-2.ipynb?jupyter-notebook': Error: NO notebook document for 'untitled:Untitled-2.ipynb?jupyter-notebook'
    at f.getNotebookDocument (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:96:78756)
    at k.$acceptDirtyStateChanged (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:86:107708)
    at u.N (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
    at u.M (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
    at u.H (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:104:10019)
    at u.G (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:104:9000)
    at /home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
    at d.invoke (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at v.deliver (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at /home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
    at d.invoke (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at v.deliver (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at c.y (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:72:17324)
    at /home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:72:15795
    at d.invoke (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at v.deliver (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at g.acceptChunk (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:72:12045)
    at /home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:72:11332
    at d.invoke (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at v.deliver (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at g.t (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:72:25895)
```

**Comment by rebornix** [comment]
From the log it seems related to our model syncing

```
at f.getNotebookDocument (/home/roblou/.vscode-server-insiders/bin/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/out/vs/workbench/api/node/extensionHostProcess.js:96:78756)
    at k.$acceptDirtyStateChanged
```

**Comment by rebornix** [comment]
A dup of https://github.com/microsoft/vscode/issues/148368
