### ISSUE TITLE
Revoking workspace trust with untitled Jupyter notebook open breaks notebook

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167877]
1. Create new untitled Jupyter notebook view New File... menu 
2. Revoke workspace trust for current folder
3. :bug: notebook breaks and can't be closed/saved
![image](https://user-images.githubusercontent.com/30305945/205155645-489741e6-f86f-400b-8182-501d2247751a.png)

Stack trace:

```
Error: Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed and enabled.
    at Vr.setInput (notebookEditor.ts:219:11)
    at async n.H (editorPanes.ts:353:4)
    at async n.y (editorPanes.ts:222:34)
    at async n.openEditor (editorPanes.ts:126:11)
    at async editorGroupView.ts:1074:49
    at async en.Ib (editorGroupView.ts:1547:4)
    at async en.Hb (editorGroupView.ts:1466:11)
    at async en.closeEditors (editorGroupView.ts:1636:16)
log.ts:310  WARN [perf] Renderer reported VERY LONG TASK (772ms), starting profiling session '58b72e8f-cc56-4052-8be7-190ed12b8f81'
log.ts:310  WARN Settings pattern "keyboard.*" doesn't match any settings
log.ts:316   ERR Error: Unexpected type
    at l (types.ts:90:9)
    at Ns.revert (notebookEditorModel.ts:502:3)
    at Bn.revert (notebookEditorInput.ts:230:24)
    at en.Ib (editorGroupView.ts:1596:19)
    at async en.Hb (editorGroupView.ts:1466:11)
    at async en.closeEditors (editorGroupView.ts:1636:16)
log.ts:316   ERR Unexpected type: Error: Unexpected type
    at l (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1485)
    at Ns.revert (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2482:3023)
    at Bn.revert (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1199:634)
    at en.Ib (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2676:17576)
    at async en.Hb (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2676:16523)
    at async en.closeEditors (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2676:17790)
notebookEditor.ts:292 TypeError: Cannot read properties of undefined (reading 'onDidChangeContent')
    at Vr.setInput (notebookEditor.ts:222:30)
    at async n.H (editorPanes.ts:353:4)
    at async n.y (editorPanes.ts:222:34)
    at async n.openEditor (editorPanes.ts:126:11)
    at async editorGroupView.ts:1074:49
    at async en.Ib (editorGroupView.ts:1547:4)
    at async en.Hb (editorGroupView.ts:1466:11)
    at async en.Cb (editorGroupView.ts:1319:16)
    at async $.run (editorActions.ts:466:5)
    at async O.runAction (actions.ts:192:3)
    at async O.run (actions.ts:183:4)
Unexpected type: Error: Unexpected type
    at l (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1485)
    at Ns.load (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2482:3851)
```

**Comment by rebornix** [comment]
From the call stack, when we switch from trusted to non-trusted state, extension host is stopped, thus the notebook serializers are disposed, which will lead to the dispose of notebook editor model.

**Comment by Paro131** [comment]
Thank y

**Comment by DonJayamanne** [comment]
No longer able to repro.

**Comment by anthonykim1** [comment]
I think this is resolved.
Creating untitled jupyter notebook file and then revoking workspace trust now shows a notification and Im prompted if I want to save the untitled notebook file.

<img width="464" alt="Image" src="https://github.com/user-attachments/assets/d7045092-cc92-40cb-93e9-64150c2b77b2" />
