### ISSUE TITLE
TS Server fatal error:  Cannot read properties of undefined (reading 'configFileSpecs')

### ISSUE THREAD

**Issue by doterax** [microsoft/vscode#167842]
Type: <b>Bug</b>

**TypeScript Version:** 4.9.3

**Steps to reproduce crash**
1. Start using plugin typescript-tslint-plugin
2. Possible rename existing file, that used in imports in other files

**Global TS Server Plugins**

- `typescript-tslint-plugin`

**TS Server Log**
❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read properties of undefined (reading 'configFileSpecs')
    at ConfiguredProject.updateErrorOnNoInputFiles (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:175434:120)
    at ProjectService.reloadFileNamesOfConfiguredProject (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:177258:25)
    at ConfiguredProject.updateGraph (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:175280:54)
    at updateProjectIfDirty (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:175781:45)
    at ProjectService.assignProjectToOpenedScriptInfo (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:178113:29)
    at d:\Work\my_project\node_modules\typescript\lib\tsserver.js:178448:97
    at Object.flatMap (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:178448:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:179820:46)
    at d:\Work\my_project\node_modules\typescript\lib\tsserver.js:182013:96
    at Session.executeWithRequestId (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:182004:28)
    at Session.executeCommand (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:182013:41)
    at Session.onMessage (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:182041:35)
    at process.<anonymous> (d:\Work\my_project\node_modules\typescript\lib\tsserver.js:186197:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (19.79GB free)|
|Process Argv|--folder-uri file:///d%3A/Work/my_project --crash-reporter-id a2588ac5-1805-41b7-8761-35aa1d6a80e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
prettier-vscode|esb|9.10.3
gc-excelviewer|Gra|4.2.56
vscode-meta|hub|0.0.1
Kotlin|mat|1.7.1
vscode-typescript-tslint-plugin|ms-|1.3.4
shader|sle|1.1.5
code-spell-checker|str|2.11.1
code-spell-checker-russian|str|2.0.6
code-spell-checker-ukrainian|str|1.0.0
vscode-icons|vsc|12.0.1
cocos-effect|Yaj|0.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by mjbvz** [comment]
This sounds like an issue with `typescript-tslint-plugin`. Please file an issue against that plugin (although it is deprecated so this likely will not be fixed)
