### ISSUE TITLE
Something gets lost when the browser redirects back to VS Code during auth flow

### ISSUE THREAD

**Issue by bordera-randy** [microsoft/vscode#168338]
Type: <b>Bug</b>

When clicking on sign in , nothing happens 
or  a browser will open then go to the background without completing the login process 

I have uninstalled the ext and reinstalled it - no change 
generated a token on github.com/settings/tokens and manually added to user settings - no change 

Extension version: 0.54.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (15.25GB free)|
|Process Argv|--crash-reporter-id 11a13aa1-894f-45d3-91dd-3a68469b18a3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce2:30605431
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by TylerLeonhardt** [comment]
Ok let's try to wade through all of this because when we're talking about different platforms, it could very well be very distinct issues.

@detox3r how did you install VS Code? There have been some other issues reported around CentOS 7, but for those, they talk about VS Code actually crashing completely. Do you see that or do you see what others have described above.

@dr-travis can you share your logs? Do you get a notification that says "having trouble? try a different way" and have you tried that alternative way? If that alternative way fails have you tried the 3rd way?

@sknth something I'm thinking about is maybe it's redirecting to the wrong VS Code window which would for sure be a problem. When you did this, did you have multiple VS Code windows open? If you really wanna be helpful, you could grab my [Open External](https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.open-external) extension and run the "Open an external uri" command and then choose "Trigger uri handler" to see if the round trip actually works (you should see a notification if it does)

**Comment by dr-travis** [comment]
@TylerLeonhardt Upgraded to vscode 1.74.0. In short, problem solved but logged in via github authentication code.

Long story short: normal login to ghes, failed -> asked me to try a different way, failed agained -> asked me to try another way, succeeded (popped up a one-time 6-digit code and redirected me to github page to enter the code).

Here are the logs for your reference:

```log
2022-12-08 16:29:16.877 [info] Getting sessions for all scopes...
2022-12-08 16:29:16.877 [info] Got 0 sessions for ...
2022-12-08 16:29:18.265 [info] Logging in for the following scopes: read:user repo user:email
2022-12-08 16:29:18.266 [info] Trying without local server... (read:user repo user:email)
2022-12-08 16:29:38.664 [info] Getting sessions for all scopes...
2022-12-08 16:29:38.664 [info] Got 0 sessions for ...
2022-12-08 16:29:40.046 [info] Logging in for the following scopes: read:user repo user:email
2022-12-08 16:29:40.046 [info] Trying without local server... (read:user repo user:email)
2022-12-08 16:29:58.431 [info] Getting sessions for all scopes...
2022-12-08 16:29:58.431 [info] Got 0 sessions for ...
2022-12-08 16:29:59.819 [info] Logging in for the following scopes: read:user repo user:email
2022-12-08 16:29:59.819 [info] Trying without local server... (read:user repo user:email)
2022-12-08 16:30:12.231 [error] User Cancelled
2022-12-08 16:30:12.231 [error] Cancelled
2022-12-08 16:30:12.231 [error] Cancelled
2022-12-08 16:30:12.256 [error] Error: Cancelled
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1302922)
	at async t.GitHubServer.login (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1303347)
	at async t.GitHubAuthenticationProvider.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1299643)
2022-12-08 16:30:12.271 [error] Error: Cancelled
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1302922)
	at async t.GitHubServer.login (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1303347)
	at async t.GitHubAuthenticationProvider.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1299643)
2022-12-08 16:30:12.274 [error] Error: Cancelled
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1302922)
	at async t.GitHubServer.login (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1303453)
	at async t.GitHubAuthenticationProvider.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1299643)
2022-12-08 16:30:13.333 [error] Error: Cancelled
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1302922)
	at async t.GitHubServer.login (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1303347)
	at async t.GitHubAuthenticationProvider.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1299643)
2022-12-08 16:30:13.336 [error] Error: Cancelled
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1302922)
	at async t.GitHubServer.login (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1303453)
	at async t.GitHubAuthenticationProvider.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1299643)
2022-12-08 16:30:14.000 [error] Error: Cancelled
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1302922)
	at async t.GitHubServer.login (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1303453)
	at async t.GitHubAuthenticationProvider.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1299643)
2022-12-08 16:30:15.674 [info] Getting sessions for all scopes...
2022-12-08 16:30:15.674 [info] Got 0 sessions for ...
2022-12-08 16:30:17.350 [info] Logging in for the following scopes: read:user repo user:email
2022-12-08 16:30:17.351 [info] Trying without local server... (read:user repo user:email)
2022-12-08 16:30:28.223 [info] Exchanging code for token...
2022-12-08 16:31:32.083 [error] GitHubTokenExchangeError: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0dHaRYwAAAACAd/zkN+pTQ50pknw9DTBCU1lEMDNFREdFMTgxNwA0YzRkOWNmMS03NmEzLTQ2NGEtOGE4OC01NWY3M2IwOTgzN2U=</span></div></div></body></html>
	at t.GitHubServer.u (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1309015)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1304423
2022-12-08 16:31:45.262 [info] Trying with local server... (read:user repo user:email)
2022-12-08 16:31:46.141 [info] Exchanging code for token...
2022-12-08 16:32:47.028 [error] GitHubTokenExchangeError: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0wnaRYwAAAAAoLuohCHO8Ra6h8DXXNAFZU1lEMDNFREdFMTIxOAA0YzRkOWNmMS03NmEzLTQ2NGEtOGE4OC01NWY3M2IwOTgzN2U=</span></div></div></body></html>
	at t.GitHubServer.u (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1309015)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1305597
2022-12-08 16:33:14.536 [info] Trying device code flow... (read:user repo user:email)
2022-12-08 16:33:41.913 [info] Getting user info...
2022-12-08 16:33:42.060 [info] Got account info!
2022-12-08 16:33:42.062 [info] Storing 1 sessions...
2022-12-08 16:33:42.142 [info] Reading sessions from keychain...
2022-12-08 16:33:42.142 [info] Stored 1 sessions!
2022-12-08 16:33:42.142 [info] Login success!
2022-12-08 16:33:42.147 [info] Getting sessions for read:user,repo,user:email,workflow...
2022-12-08 16:33:42.148 [info] Got stored sessions!
2022-12-08 16:33:42.148 [info] Got 1 verified sessions.
2022-12-08 16:33:42.148 [info] Got 0 sessions for read:user,repo,user:email,workflow...
2022-12-08 16:33:42.149 [info] Getting sessions for read:user,repo,user:email...
2022-12-08 16:33:42.149 [info] Got 1 sessions for read:user,repo,user:email...
2022-12-08 16:33:56.764 [info] Getting sessions for all scopes...
2022-12-08 16:33:56.764 [info] Got 1 sessions for ...

**Comment by sknth** [comment]
> something I'm thinking about is maybe it's redirecting to the wrong VS Code window which would for sure be a problem. When you did this, did you have multiple VS Code windows open? If you really wanna be helpful, you could grab my [Open External](https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.open-external) extension and run the "Open an external uri" command and then choose "Trigger uri handler" to see if the round trip actually works (you should see a notification if it does)

@TylerLeonhardt sometimes I had multiple windows open and other times I had only one window open. I'd tried both combinations while hitting the issue.
I installed your extension and tried trigger uri handler. I receive a notification as expected when I have a single vscode window or multiple windows open.

**Comment by TylerLeonhardt** [comment]
#169076 should improve things by no longer having you folks using Remote SSH go through that second flow with the port number.

However, the other question still remains: "Why doesn't the first flow work in the remote case?" Because it should.

So let me ask these clarifying questions:
* Do you experience the same problem when logging in for a github.com repo?
* What version of GitHub Enterprise Server is your company using?

let me know if you need any assistants finding that.

also cc'ing @notatallshaw-gts who opened a detailed issue I duped to this issue

**Comment by notatallshaw-gts** [comment]
> * Do you experience the same problem when logging in for a github.com repo?

For me it doesn't appear to work at all connecting to github.com, where as at least connecting to github enterprise it eventually works. I went through the whole flow but instead being provided a code to copy and paste at the end I get: "Error Signing in to Github - Try Again?".

I hadn't tried it before because:
1. PRs on github.com requires manual approvals internally
2. I am sitting behind the usual corporate proxies which require SSPI authentication from my Desktop (VS Code Client) and certain CAs to be set-up correctly on my Dev machine (VS Code Server) so I typically don't expect random tools that connecting to the internet to work unless they support flows and/or I have to configure them carefully.

> * What version of GitHub Enterprise Server is your company using?

3.4

**Comment by notatallshaw-gts** [comment]
I'd be happy to test again on VS Code 1.45.1 but I'm not sure how to clear the existing authentication to retest?

**Comment by TylerLeonhardt** [comment]
It's been a while since this issue and we've made a lot of code changes in this space... I'm going to close this. If you are still experiencing issues, please open a new issue and make sure you provide the:
  * `GitHub Authentication` Output channel
  * `Window` Output channel
  * `Main` Output channel

**Comment by notatallshaw-gts** [comment]
FYI, I've not been experiencing this issue in some time.
