### ISSUE TITLE
JS/TS language features crashes

### ISSUE THREAD

**Issue by alex-rantos** [microsoft/vscode#168304]
Type: <b>Bug</b>

No repro steps. I just open VSCode and linting does not work.
I have observed in Activity Monitor that Code Helper is running and eating up to 4-5GB of memory then crashes, then it's reinitiated and then crashes etc etc.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 11, 9|
|Memory (System)|64.00GB (35.05GB free)|
|Process Argv|--crash-reporter-id 619e58d5-8da3-4c02-ad01-a97199f409b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
prettier-vscode|esb|9.10.3
copilot|Git|1.62.7527
import-sorter|mik|3.3.1
vscode-graphql|ors|0.3.18
teams-dyson|tea|0.0.2022102501
alphabetical-sorter|ue|2.0.1
vscode-icons|vsc|12.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by alex-rantos** [comment]
Sometimes I switch repos, linting works for couple of minutes and then stops after 4-5' (I guess after the first time that CodeHelper crashes in activity monitor)

**Comment by alex-rantos** [comment]
Seems that somehow my Max TS Server Memory was reseted to 3GBs. Bumping it up seems to solve the issue for now 
![image](https://user-images.githubusercontent.com/22919198/206198445-0d1f2c50-b574-4bfd-bcab-d9ef5044edde.png)

**Comment by alex-rantos** [comment]
Increasing the TSServer memory just made the server stay alive a few minutes more.

@mjbvz I found this error on TSserver logs:
same issue happens for me on VSCode Insiders but I haven't checked the logs there yet.

```
Info 26   [20:09:54.928] Failed to load module 'tsec' from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules: Error: Could not resolve JS module 'tsec' starting at '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules'. Looked in: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/tsec/package.json, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/tsec.js, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/tsec.jsx, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/tsec/index.js, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/tsec/index.jsx, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/tsec/package.json, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/tsec.js, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/tsec.jsx, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/tsec/index.js, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/tsec/index.jsx, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/tsec/package.json, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/tsec.js, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/tsec.jsx, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/tsec/index.js, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/tsec/index.jsx, /Applications/Visual Studio Code.app/Contents/node_modules/tsec/package.json, /Applications/Visual Studio Code.app/Contents/node_modules/tsec.js, /Applications/Visual Studio Code.app/Contents/node_modules/tsec.jsx, /Applications/Visual Studio Code.app/Contents/node_modules/tsec/index.js, /Applications/Visual Studio Code.app/Contents/node_modules/tsec/index.jsx, /Applications/Visual Studio Code.app/node_modules/tsec/package.json, /Applications/Visual Studio Code.app/node_modules/tsec.js, /Applications/Visual Studio Code.app/node_modules/tsec.jsx, /Applications/Visual Studio Code.app/node_modules/tsec/index.js, /Applications/Visual Studio Code.app/node_modules/tsec/index.jsx, /Applications/node_modules/tsec/package.json, /Applications/node_modules/tsec.js, /Applications/node_modules/tsec.jsx, /Applications/node_modules/tsec/index.js, /Applications/node_modules/tsec/index.jsx, /node_modules/tsec/package.json, /node_modules/tsec.js, /node_modules/tsec.jsx, /node_modules/tsec/index.js, /node_modules/tsec/index.jsx
    at Object.resolveJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:43760:19)
    at sys.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183928:49)
    at Project.resolveModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:171636:35)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172778:36
    at Object.firstDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:222:26)
    at Project.beginEnablePluginSync (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172777:41)
    at ProjectService.requestEnablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176958:49)
    at Project.enablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172841:37)
    at ConfiguredProject.enablePluginsWithOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173510:30)
    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175226:25)
    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175178:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175183:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176269:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176609:97
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:525:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176609:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177982:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:180174:96
    at Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:180165:28)
    at Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:180174:41)
    at Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:180202:35)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184368:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
    ```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, `tsec` suggests you are using either a TS plugin or modified TS compiler. Is that the case?

**Comment by alex-rantos** [comment]
Repro from latest insiders build
```
Info 26   [11:25:37.109] Failed to load module 'tsec' from /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/node_modules: Error: Could not resolve JS module 'tsec' starting at '/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/node_modules'. Looked in: /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/node_modules/tsec/index.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/node_modules/tsec/package.json, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/node_modules/tsec.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/node_modules/tsec.jsx, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/node_modules/tsec/index.js, /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/node_modules/tsec/index.jsx, /private/var/folders/f2/node_modules/tsec/package.json, /private/var/folders/f2/node_modules/tsec.js, /private/var/folders/f2/node_modules/tsec.jsx, /private/var/folders/f2/node_modules/tsec/index.js, /private/var/folders/f2/node_modules/tsec/index.jsx, /private/var/folders/node_modules/tsec/package.json, /private/var/folders/node_modules/tsec.js, /private/var/folders/node_modules/tsec.jsx, /private/var/folders/node_modules/tsec/index.js, /private/var/folders/node_modules/tsec/index.jsx, /private/var/node_modules/tsec/package.json, /private/var/node_modules/tsec.js, /private/var/node_modules/tsec.jsx, /private/var/node_modules/tsec/index.js, /private/var/node_modules/tsec/index.jsx, /private/node_modules/tsec/package.json, /private/node_modules/tsec.js, /private/node_modules/tsec.jsx, /private/node_modules/tsec/index.js, /private/node_modules/tsec/index.jsx, /node_modules/tsec/package.json, /node_modules/tsec.js, /node_modules/tsec.jsx, /node_modules/tsec/index.js, /node_modules/tsec/index.jsx
    at Object.resolveJSModule (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:44257:19)
    at sys.require (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185757:49)
    at Project.resolveModule (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173466:35)
    at /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174613:36
    at Object.firstDefined (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:221:26)
    at Project.beginEnablePluginSync (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174612:41)
    at ProjectService.requestEnablePlugin (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178797:49)
    at Project.enablePlugin (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174676:37)
    at ConfiguredProject.enablePluginsWithOptions (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175347:30)
    at ProjectService.loadConfiguredProject (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177065:25)
    at ProjectService.createAndLoadConfiguredProject (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177017:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177022:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178108:44)
    at /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178448:97
    at Object.flatMap (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178448:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179820:46)
    at /private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182013:96
    at Session.executeWithRequestId (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182004:28)
    at Session.executeCommand (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182013:41)
    at Session.onMessage (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182041:35)
    at process.<anonymous> (/private/var/folders/f2/s168y_6j46xc2b3tzf_y4gk00000gn/T/AppTranslocation/41F7F182-7521-4D83-80AD-78A1952322E0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:186197:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Info 27   [11:25:37.109] Couldn't find tsec
```

**Comment by alex-rantos** [comment]
Also on `tsec` it's just a dependency on our project. No clue how initializing tsserver is conflicting with that.

I have this in VSCode 
<img width="898" alt="image" src="https://user-images.githubusercontent.com/22919198/206463958-4ebfd59b-a5f8-40b1-9c6f-896e457487f3.png">

**Comment by mjbvz** [comment]
Thanks for testing. This sounds like an issue with your project setup and where tsec is located in it. Try looking into that or file an issue against the tscec plugin 

Closing as external
