### ISSUE TITLE
Stepping into code that is skipped via skipFiles looks like it's running when it's actually paused

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16848]
- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:04:22.691Z)
- OS Version: Linux x64 4.8.0-27-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|Go|lukehoban|0.6.50|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|java|redhat|0.0.7|
|annotator|ryu1kn|0.10.1|

---

1. Clone and open https://github.com/Microsoft/vscode-smoketest-express.git
2. Created the launch.json:

```js
    {
        // Use IntelliSense to learn about possible Node.js debug attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program",
                "program": "${workspaceRoot}/bin/www",
                "cwd": "${workspaceRoot}",
                "skipFiles": [
                    "node_modules/**"
                ]
            },
            {
                "type": "node",
                "request": "attach",
                "name": "Attach to Process",
                "port": 5858
            }
        ]
    }
    ```

3. Put a breakpoint at `bin/www:28` on `server.listen`
4. Start debugging
5. Hit the breakpoint
6. Step in, I assumed that the program continued because the pause button was back for ~20-30 seconds until `node_modules` was exited (see #16847)

**Comment by weinand** [comment]
On macOS the 'stepin' takes about 0.5sec and then stops on line 29. So I do not see any unexpected behaviour.

**Comment by Tyriar** [comment]
On Ubuntu it took around 30 seconds to stop on the following line. While it was working the (non-disabled) pause button was at the top which is typically the indicator for me that the program has continued.

**Comment by Eli-Goldberg** [comment]
I'm having a similar issue - stepping in brings me to a line called: "1007",
and the editor does nothing.

If I try to F5 to continue, a timeout message appears and this is printed in the console: 

Error processing "setBreakpoints": Error: Set breakpoints request timed out
    at Timeout.setTimeout (/usr/share/code/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/utils.js:54:24)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
