### ISSUE TITLE
Illegal argument: connectionToken

### ISSUE THREAD

**Issue by YDisa** [microsoft/vscode#168548]
Type: <b>Bug</b>

hi,

I tried to use the "remote-tunnel"

I turned on the remote on my Mac.
And I tried to access remote by turning on a different vcode window

But it doesn't connect, it only pops up during the connection

And the following error is displayed on the console

-----
 INFO [attempt 1] Invoking resolveAuthority(tunnel)
workbench.desktop.main.js:616   ERR [attempt 1] resolveAuthority(tunnel) returned an error after 402 ms Error: Illegal argument: connectionToken
	at P (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1129)
	at new Y (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:17352)
	at C.resolve (vscode-file://vscode-app/Users/yoodongsin/.vscode/extensions/ms-vscode.remote-server-1.0.0/dist/node/extension.js:2:945327)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:18208)
workbench.desktop.main.js:616  INFO [attempt 2] Invoking resolveAuthority(tunnel)
workbench.desktop.main.js:616   ERR [attempt 2] resolveAuthority(tunnel) returned an error after 4 ms Error: Illegal argument: connectionToken
	at P (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1129)
	at new Y (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:17352)
	at C.resolve (vscode-file://vscode-app/Users/yoodongsin/.vscode/extensions/ms-vscode.remote-server-1.0.0/dist/node/extension.js:2:945327)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:18208)

-----

VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No
Connection to 'vscode-remote' could not be established  Illegal argument: connectionToken

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.86GB free)|
|Process Argv|--crash-reporter-id 1e802665-f08b-4ad6-8ba6-8dc6008bbd04|
|Screen Reader|no|
|VM|0%|

Connection to 'vscode-remote' could not be established  Illegal argument: connectionToken
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by YDisa** [comment]
It was uploaded incorrectly.

I'll create an issue to remote - tunnel
