### ISSUE TITLE
Install extension fails in remote container

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#168525]
![Recording 2022-12-08 at 14 41 22 (1)](https://user-images.githubusercontent.com/31675041/206582592-b4332e97-79a9-41cb-ac0f-31b84085f7f0.gif)

I'm getting an ENOENT error when trying to install Live Preview in a remote container.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/31675041/206582704-01240529-2a83-4fbc-92e0-506b945ac20d.png">

**Comment by chrmarti** [comment]
Works with an Ubuntu container, but fails with Alpine. Maybe the Alpine one is missing something?
```
2022-12-09 16:07:33.576 [debug] Remote Install Error Name Signature
2022-12-09 16:07:34.246 [error] Signature: ENOENT
    at Cn.download (/vscode/vscode-server-insiders/bin/alpine-arm64/b92894493e6f971a3c71912d823e699d3a05d643-insider/out/vs/server/node/server.main.js:92:1603)
    at async j.h (/vscode/vscode-server-insiders/bin/alpine-arm64/b92894493e6f971a3c71912d823e699d3a05d643-insider/out/vs/server/node/server.main.js:148:89931)
2022-12-09 16:07:34.275 [error] ENOENT: Signature: ENOENT
    at Cn.download (/vscode/vscode-server-insiders/bin/alpine-arm64/b92894493e6f971a3c71912d823e699d3a05d643-insider/out/vs/server/node/server.main.js:92:1603)
    at async j.h (/vscode/vscode-server-insiders/bin/alpine-arm64/b92894493e6f971a3c71912d823e699d3a05d643-insider/out/vs/server/node/server.main.js:148:89931)
```

**Comment by sandy081** [comment]
CC @isidorn 

Signing related.

**Comment by sandy081** [comment]
@isidorn/@dtivel Any updates on this?

**Comment by dtivel** [comment]
This should be resolved with latest Insiders via https://github.com/microsoft/vscode/pull/169777.  If it isn't, please let us know with your version info.

**Comment by isidorn** [comment]
Closing as fixed then.

**Comment by roblourens** [comment]
Wrong milestone?
