### ISSUE TITLE
`Code - OSS` doesn't launch when using Dev Container locally or in codespaces

### ISSUE THREAD

**Issue by Bassadin** [microsoft/vscode#168655]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0 (also happens on Codespaces)
- OS Version: Windows 11; Version 10.0.22621 Build 22621 (also happens on Codespaces)

I was trying to get a development VS Code OSS build running with dev containers. After following the steps from https://github.com/microsoft/vscode/tree/main/.devcontainer, I only got the following error when trying to execute `bash scripts/code.sh`:

```bash
@Bassadin ➜ /workspaces/vscode $ bash scripts/code.sh
yarn run v1.22.19
$ node build/lib/electron
Downloading ffmpeg: [====================================================================================================] 100% ETA: 0.0 seconds 
Downloading ffmpeg: [====================================================================================================] 100% ETA: 0.0 seconds 
Done in 4.49s.
yarn run v1.22.19
$ node --max_old_space_size=4095 ./node_modules/gulp/bin/gulp.js compile
[19:22:43] Using gulpfile /workspaces/vscode/gulpfile.js
[19:22:43] Starting 'compile'...
[19:22:43] Starting monaco-typecheck ...
[19:22:43] Starting clean-out ...
[19:22:43] Starting clean-extension-authentication-proxy ...
[19:22:43] Starting clean-extension-configuration-editing-build ...
[19:22:43] Starting clean-extension-configuration-editing ...
[19:22:43] Starting clean-extension-css-language-features-client ...
[19:22:43] Starting clean-extension-css-language-features-server ...
[19:22:43] Starting clean-extension-debug-auto-launch ...
[19:22:43] Starting clean-extension-debug-server-ready ...
[19:22:43] Starting clean-extension-emmet ...
[19:22:43] Starting clean-extension-extension-editing ...
[19:22:43] Starting clean-extension-git ...
[19:22:43] Starting clean-extension-git-base ...
[19:22:43] Starting clean-extension-github-authentication ...
[19:22:43] Starting clean-extension-github ...
[19:22:43] Starting clean-extension-grunt ...
[19:22:43] Starting clean-extension-gulp ...
[19:22:43] Starting clean-extension-html-language-features-client ...
[19:22:43] Starting clean-extension-html-language-features-server ...
[19:22:43] Starting clean-extension-ipynb ...
[19:22:43] Starting clean-extension-jake ...
[19:22:43] Starting clean-extension-json-language-features-client ...
[19:22:43] Starting clean-extension-json-language-features-server ...
[19:22:43] Starting clean-extension-markdown-language-features-preview-src ...
[19:22:43] Starting clean-extension-markdown-language-features-server ...
[19:22:43] Starting clean-extension-markdown-language-features ...
[19:22:43] Starting clean-extension-markdown-math ...
[19:22:43] Starting clean-extension-media-preview ...
[19:22:43] Starting clean-extension-merge-conflict ...
[19:22:43] Starting clean-extension-microsoft-authentication ...
[19:22:43] Starting clean-extension-npm ...
[19:22:43] Starting clean-extension-php-language-features ...
[19:22:43] Starting clean-extension-search-result ...
[19:22:43] Starting clean-extension-references-view ...
[19:22:43] Starting clean-extension-simple-browser ...
[19:22:43] Starting clean-extension-typescript-language-features-test-workspace ...
[19:22:43] Starting clean-extension-typescript-language-features-web ...
[19:22:43] Starting clean-extension-typescript-language-features ...
[19:22:43] Starting clean-extension-vscode-api-tests ...
[19:22:43] Starting clean-extension-vscode-colorize-tests ...
[19:22:43] Starting clean-extension-vscode-test-resolver ...
[19:22:43] Starting compile-extension-media ...
[19:22:43] Finished clean-out after 80 ms
[19:22:43] Starting build-web-node-paths ...
[19:22:44] Finished build-web-node-paths after 46 ms
[19:22:44] Starting compile-api-proposal-names ...
[19:22:44] Starting compilation api-proposal-names...
[19:22:44] Finished clean-extension-authentication-proxy after 160 ms
[19:22:44] Starting compile-extension:authentication-proxy ...
[19:22:44] Starting compilation extensions...
[19:22:44] Finished clean-extension-configuration-editing-build after 981 ms
[19:22:44] Starting compile-extension:configuration-editing-build ...
[19:22:44] Finished clean-extension-configuration-editing after 1005 ms
[19:22:44] Starting compile-extension:configuration-editing ...
[19:22:44] Finished clean-extension-css-language-features-client after 1024 ms
[19:22:44] Starting compile-extension:css-language-features-client ...
[19:22:44] Finished clean-extension-css-language-features-server after 1039 ms
[19:22:44] Starting compile-extension:css-language-features-server ...
[19:22:44] Finished clean-extension-debug-auto-launch after 1047 ms
[19:22:44] Starting compile-extension:debug-auto-launch ...
[19:22:44] Finished clean-extension-debug-server-ready after 1063 ms
[19:22:44] Starting compile-extension:debug-server-ready ...
[19:22:45] Finished clean-extension-emmet after 1081 ms
[19:22:45] Starting compile-extension:emmet ...
[19:22:45] Finished clean-extension-extension-editing after 1120 ms
[19:22:45] Starting compile-extension:extension-editing ...
[19:22:45] Finished clean-extension-git after 1132 ms
[19:22:45] Starting compile-extension:git ...
[19:22:45] Finished clean-extension-git-base after 1157 ms
[19:22:45] Starting compile-extension:git-base ...
[19:22:45] Finished clean-extension-github-authentication after 1170 ms
[19:22:45] Starting compile-extension:github-authentication ...
[19:22:45] Finished clean-extension-github after 1188 ms
[19:22:45] Starting compile-extension:github ...
[19:22:45] Finished clean-extension-grunt after 1204 ms
[19:22:45] Starting compile-extension:grunt ...
[19:22:45] Finished clean-extension-gulp after 1219 ms
[19:22:45] Starting compile-extension:gulp ...
[19:22:45] Finished clean-extension-html-language-features-client after 1232 ms
[19:22:45] Starting compile-extension:html-language-features-client ...
[19:22:45] Finished clean-extension-html-language-features-server after 1244 ms
[19:22:45] Starting compile-extension:html-language-features-server ...
[19:22:45] Finished clean-extension-ipynb after 1262 ms
[19:22:45] Starting compile-extension:ipynb ...
[19:22:45] Finished clean-extension-jake after 1276 ms
[19:22:45] Starting compile-extension:jake ...
[19:22:45] Finished clean-extension-json-language-features-client after 1287 ms
[19:22:45] Starting compile-extension:json-language-features-client ...
[19:22:45] Finished clean-extension-json-language-features-server after 1301 ms
[19:22:45] Starting compile-extension:json-language-features-server ...
[19:22:45] Finished clean-extension-markdown-language-features-preview-src after 1310 ms
[19:22:45] Starting compile-extension:markdown-language-features-preview-src ...
[19:22:45] Finished clean-extension-markdown-language-features-server after 1316 ms
[19:22:45] Starting compile-extension:markdown-language-features-server ...
[19:22:45] Finished clean-extension-markdown-language-features after 1325 ms
[19:22:45] Starting compile-extension:markdown-language-features ...
[19:22:45] Finished clean-extension-markdown-math after 1352 ms
[19:22:45] Starting compile-extension:markdown-math ...
[19:22:45] Finished clean-extension-media-preview after 1368 ms
[19:22:45] Starting compile-extension:media-preview ...
[19:22:45] Finished clean-extension-merge-conflict after 1385 ms
[19:22:45] Starting compile-extension:merge-conflict ...
[19:22:45] Finished clean-extension-microsoft-authentication after 1417 ms
[19:22:45] Starting compile-extension:microsoft-authentication ...
[19:22:45] Finished clean-extension-npm after 1435 ms
[19:22:45] Starting compile-extension:npm ...
[19:22:45] Finished clean-extension-php-language-features after 1453 ms
[19:22:45] Starting compile-extension:php-language-features ...
[19:22:45] Finished clean-extension-search-result after 1475 ms
[19:22:45] Starting compile-extension:search-result ...
[19:22:45] Finished clean-extension-references-view after 1488 ms
[19:22:45] Starting compile-extension:references-view ...
[19:22:45] Finished clean-extension-simple-browser after 1505 ms
[19:22:45] Starting compile-extension:simple-browser ...
[19:22:45] Finished clean-extension-typescript-language-features-test-workspace after 1515 ms
[19:22:45] Starting compile-extension:typescript-language-features-test-workspace ...
[19:22:45] Finished clean-extension-typescript-language-features-web after 1518 ms
[19:22:45] Starting compile-extension:typescript-language-features-web ...
[19:22:45] Finished clean-extension-typescript-language-features after 1521 ms
[19:22:45] Starting compile-extension:typescript-language-features ...
[19:22:45] Finished clean-extension-vscode-api-tests after 1561 ms
[19:22:45] Starting compile-extension:vscode-api-tests ...
[19:22:45] Finished clean-extension-vscode-colorize-tests after 1594 ms
[19:22:45] Starting compile-extension:vscode-colorize-tests ...
[19:22:45] Finished clean-extension-vscode-test-resolver after 1607 ms
[19:22:45] Starting compile-extension:vscode-test-resolver ...
[19:22:51] Finished compile-extension:authentication-proxy after 7074 ms
[19:22:51] Finished compile-extension:typescript-language-features-test-workspace after 5711 ms
[19:22:51] Finished esbuilding extension media /workspaces/vscode/extensions/markdown-math/esbuild.js with 0 errors.
[19:22:51] Finished esbuilding extension media /workspaces/vscode/extensions/markdown-language-features/esbuild-notebook.js with 0 errors.
[19:22:51] Finished esbuilding extension media /workspaces/vscode/extensions/simple-browser/esbuild-preview.js with 0 errors.
[19:22:51] Finished esbuilding extension media /workspaces/vscode/extensions/ipynb/esbuild.js with 0 errors.
[19:22:51] Finished esbuilding extension media /workspaces/vscode/extensions/notebook-renderers/esbuild.js with 0 errors.
[19:22:51] Finished esbuilding extension media /workspaces/vscode/extensions/markdown-language-features/esbuild-preview.js with 0 errors.
[19:22:51] Finished compile-extension-media after 7226 ms
[19:22:55] Finished compile-extension:configuration-editing-build after 10195 ms
[19:22:55] Finished compile-extension:typescript-language-features-web after 9647 ms
[19:22:58] Finished compile-extension:debug-auto-launch after 13917 ms
[19:22:58] Finished compile-extension:debug-server-ready after 13902 ms
[19:22:58] Finished compile-extension:grunt after 13758 ms
[19:22:58] Finished compile-extension:gulp after 13743 ms
[19:22:58] Finished compile-extension:jake after 13686 ms
[19:22:58] Finished compile-extension:markdown-math after 13618 ms
[19:23:05] Finished compile-extension:search-result after 19778 ms
[19:23:05] Finished monaco-typecheck after 21274 ms
[19:23:05] Finished compile-extension:vscode-colorize-tests after 19661 ms
[19:23:06] Finished compile-extension:vscode-test-resolver after 20549 ms
[19:23:09] Finished compile-extension:extension-editing after 23963 ms
[19:23:09] Finished compile-extension:simple-browser after 23580 ms
[19:23:14] Finished compile-extension:configuration-editing after 29326 ms
[19:23:15] Finished compile-extension:css-language-features-client after 30504 ms
[19:23:15] Finished compile-extension:markdown-language-features-preview-src after 30223 ms
[19:23:15] Finished compile-extension:json-language-features-client after 30248 ms
[19:23:15] Finished compile-extension:html-language-features-client after 30331 ms
[19:23:15] Finished compile-extension:json-language-features-server after 30262 ms
[19:23:15] Finished compile-extension:git-base after 30412 ms
[19:23:15] Finished compile-extension:php-language-features after 30125 ms
[19:23:17] Finished compile-extension:media-preview after 32182 ms
[19:23:17] Finished compile-extension:merge-conflict after 32165 ms
[19:23:17] Finished compile-extension:references-view after 32070 ms
[19:23:17] Finished compile-extension:npm after 32129 ms
[19:23:17] Finished compile-extension:ipynb after 32308 ms
[19:23:17] Finished compile-extension:microsoft-authentication after 32165 ms
[19:23:17] Finished compile-extension:github after 32398 ms
[19:23:17] Finished compile-extension:css-language-features-server after 32552 ms
[19:23:17] Finished compile-extension:markdown-language-features-server after 32269 ms
[19:23:17] Finished compile-extension:github-authentication after 32419 ms
[19:23:25] Finished compilation api-proposal-names with 0 errors after 41811 ms
[19:23:25] Finished compile-api-proposal-names after 41843 ms
[19:23:25] Starting compile-client ...
[19:23:27] Starting compilation...
[19:23:28] Finished compile-extension:vscode-api-tests after 42633 ms
[19:23:28] Finished compile-extension:git after 43113 ms
[19:23:28] Finished compile-extension:emmet after 43167 ms
[19:23:28] Finished compile-extension:html-language-features-server after 43009 ms
[19:23:31] Finished compile-extension:markdown-language-features after 46377 ms
[19:23:31] Finished compilation extensions with 0 errors after 46896 ms
[19:23:31] Finished compile-extension:typescript-language-features after 46478 ms
[19:23:31] Starting compile-extensions ...
[19:23:31] Finished compile-extensions after 0 ms
[19:25:28] Finished compilation with 0 errors after 121180 ms
[19:25:28] Finished compile-client after 123052 ms
[19:25:28] Starting compile ...
[19:25:28] Finished compile after 0 ms
[19:25:28] Finished 'compile' after 2.75 min
Done in 174.63s.
[19:25:29] Synchronizing built-in extensions...
[19:25:29] You can manage built-in extensions with the --builtin flag
[19:25:30] Downloading extension from GH: ms-vscode.js-debug-companion@1.0.18 ...
[19:25:30] Downloading extension from GH: ms-vscode.js-debug@1.74.1 ...
[19:25:30] Downloading extension from GH: ms-vscode.vscode-js-profile-table@1.0.3 ...
[19:25:32] [github] ms-vscode.js-debug-companion ✔︎
[19:25:32] [github] ms-vscode.vscode-js-profile-table ✔︎
[19:25:32] [github] ms-vscode.js-debug ✔︎
[12206:1209/192535.689600:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[14235:1209/192536.106642:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[14235:1209/192536.107883:ERROR:gl_context_egl.cc(136)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[14235:1209/192536.197046:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[14235:1209/192536.197131:ERROR:gl_surface_egl.cc(2250)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[14235:1209/192536.197187:ERROR:gpu_info_collector.cc(80)] gl::GLContext::CreateOffscreenGLSurface failed
[14235:1209/192536.197237:ERROR:gpu_info_collector.cc(342)] Could not create surface for info collection.
[14235:1209/192536.197291:ERROR:gpu_init.cc(86)] CollectGraphicsInfo failed.
[14235:1209/192536.199205:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[14308:1209/192536.311447:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[14308:1209/192536.311640:ERROR:gl_context_egl.cc(136)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[14308:1209/192536.312720:ERROR:gl_surface_egl.cc(804)] No suitable EGL configs found.
[14308:1209/192536.312791:ERROR:gl_surface_egl.cc(2250)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[14308:1209/192536.312839:ERROR:gpu_info_collector.cc(80)] gl::GLContext::CreateOffscreenGLSurface failed
[14308:1209/192536.312912:ERROR:gpu_info_collector.cc(342)] Could not create surface for info collection.
[14308:1209/192536.312967:ERROR:gpu_init.cc(86)] CollectGraphicsInfo failed.
[14308:1209/192536.314948:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[14337:1209/192536.419315:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[14337:1209/192536.422261:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[14288:1209/192536.424718:ERROR:command_buffer_proxy_impl.cc(126)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[12206:1209/192538.149982:INFO:CONSOLE(261)] "[uncaught exception]: Error: [object Event]", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (261)
[12206:1209/192538.150191:INFO:CONSOLE(264)] "Error: [object Event]
    at Object.ensureError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:256:22)
    at ModuleManager._createLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1508:33)
    at ModuleManager._onLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1519:30)
    at loadNextPath (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1665:27)
    at Object.errorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1685:25)
    at OnlyOnceScriptLoader.triggerErrorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:631:36)
    at vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:618:151
    at HTMLScriptElement.errorEventListener (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:654:17)", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (264)
[12206:1209/192538.150405:INFO:CONSOLE(261)] "[uncaught exception]: Error: [object Event]", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (261)
[12206:1209/192538.150459:INFO:CONSOLE(264)] "Error: [object Event]
    at Object.ensureError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:256:22)
    at ModuleManager._createLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1508:33)
    at ModuleManager._onLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1519:30)
    at loadNextPath (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1665:27)
    at Object.errorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1685:25)
    at OnlyOnceScriptLoader.triggerErrorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:631:36)
    at vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:618:151
    at HTMLScriptElement.errorEventListener (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:654:17)", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (264)
[12206:1209/192538.150711:INFO:CONSOLE(261)] "[uncaught exception]: Error: [object Event]", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (261)
[12206:1209/192538.150763:INFO:CONSOLE(264)] "Error: [object Event]
    at Object.ensureError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:256:22)
    at ModuleManager._createLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1508:33)
    at ModuleManager._onLoadError (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1519:30)
    at loadNextPath (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1665:27)
    at Object.errorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:1685:25)
    at OnlyOnceScriptLoader.triggerErrorback (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:631:36)
    at vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:618:151
    at HTMLScriptElement.errorEventListener (vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js:654:17)", source: vscode-file://vscode-app/workspaces/vscode/out/bootstrap-window.js (264)
```

My `yarn` / `yarn install` command beforehand runs without errors.

The noVNC web interface shows this:

![image](https://user-images.githubusercontent.com/1810902/206783050-66256037-bf86-4a00-b70d-adf740638557.png)

**Comment by bpasero** [comment]
Maybe Christoph could advice how to setup the container to allow to run VS Code given his work in this field.

**Comment by Bassadin** [comment]
I was going to setup my dev environment the "normal" way, but then I noticed the dev container config and thought it would be cool to try that out :) Thanks in advance for helping!

**Comment by chrmarti** [comment]
@alexdima Not sure how to debug this, there is an empty event object coming from https://github.com/microsoft/vscode/blame/d735856fd9e156d46f11bff0a7cf5ed5c9610ddc/src/vs/loader.js#L654 for many or all script files.

**Comment by rsmaximiliano** [comment]
Hi! I have the same issue

OS VERSION:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎07/‎05/‎2022
OS build	22621.900
Experience	Windows Feature Experience Pack 1000.22638.1000.0

VS CODE:
commit a606c86868801bdd6a3f4ddd3ba6253d068d0ed5 (grafted, HEAD -> main, origin/main, origin/HEAD)

**Comment by Bassadin** [comment]
Is there anything that can be done about this or is there an ETA for when? I'd love to get started with solving issues for the VSCode project :D
Otherwise, I can also try to get the "usual" way to develop it locally to run but I'd love to use dev containers :)

**Comment by chrmarti** [comment]
Needs further investigation. We will also add a simpler configuration that should hopefully be more robust as part of https://github.com/microsoft/vscode/issues/170969.

**Comment by chrmarti** [comment]
@bpasero @deepak1556 The following is burried in all the other log messages, could this be the root cause? Interestingly the Insiders build works in the container.

```
[27833:0120/163520.451837:INFO:CONSOLE(163)] "Failed trying to load default language strings Error: [object Event]", source: vscode-file://vscode-app/workspaces/vscode/out/vs/nls.js (163)
[27833:0120/163520.451860:INFO:CONSOLE(276)] "Loading "vs/css!vs/workbench/workbench.desktop.main" failed", source: vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js (276)
[27833:0120/163520.451876:INFO:CONSOLE(277)] "Error: Could not find vscode-file://vscode-app/workspaces/vscode/out/vs/workbench/workbench.desktop.main.css.", source: vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js (277)
[27833:0120/163520.451894:INFO:CONSOLE(278)] "Here are the modules that depend on it:", source: vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js (278)
[27833:0120/163520.451909:INFO:CONSOLE(279)] "===anonymous1===", source: vscode-file://vscode-app/workspaces/vscode/out/vs/loader.js (279)
```

**Comment by bpasero** [comment]
I am not sure I follow, isnt this about running VSCode out of sources in a container? How is insiders related?

**Comment by chrmarti** [comment]
I don't know if it is relevant, but the problem when running out of sources doesn't reproduce with Insiders when run in the same container.

**Comment by chrmarti** [comment]
@deepak1556 I have run Git bisect on this:

1044556d8b2935bc5045128c2596d26cc1e6d1b2 is the first bad commit
Date:   Mon Mar 21 02:36:00 2022 +0900
    chore: bump electron@18.0.0-beta.4

**Comment by ruffsl** [comment]
Still encountering this from `Code - OSS with X11/Wayland` devcontainer via vscode remote ssh using windows desktop client:

https://github.com/microsoft/vscode/blob/b547b58db642cac86c6a869cd025713f4e2cac9f/.devcontainer/devcontainer.json#L2

See following stdout, however for X11 forwarding, the `Code - OSS` window never even renders on the local running Xserver.

<details>
<summary>stdout</summary>

```
node ➜ /workspaces/vscode $ bash scripts/code.sh 
yarn run v1.22.19
$ node build/lib/electron
Done in 0.13s.
[21:14:52] Synchronizing built-in extensions...
[21:14:52] You can manage built-in extensions with the --builtin flag
[21:14:52] [github] ms-vscode.js-debug-companion@1.0.18 ✔︎
[21:14:52] [github] ms-vscode.js-debug@1.77.2 ✔︎
[21:14:52] [github] ms-vscode.vscode-js-profile-table@1.0.3 ✔︎
[1930:0410/211500.556127:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1930:0410/211500.556217:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1930:0410/211501.170293:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1930:0410/211501.170361:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1930:0410/211501.620011:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[Error: ENOENT: no such file or directory, open '/workspaces/vscode/out/vs/code/electron-main/main.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/workspaces/vscode/out/vs/code/electron-main/main.js',
  phase: 'loading',
  moduleId: 'vs/code/electron-main/main',
  neededBy: [ '===anonymous1===' ]
}
[2087:0410/211505.871722:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[2174:0410/211508.581943:WARNING:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
[2174:0410/211508.584937:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

</details>


Using the prebuilt `Code - OSS with VNC` devcontainer produces the same result for me as already reported.

https://github.com/microsoft/vscode/blob/b547b58db642cac86c6a869cd025713f4e2cac9f/.devcontainer/prebuilt/devcontainer.json#L2

Not being able to open the file descriptor wouldn't be related to docker's changing default for LimitNOFILE would it?

- https://github.com/containerd/containerd/pull/7566
- https://answers.ros.org/question/413528/odd-docker-roscoreroslaunch-delays-with-linux-kernel-61/?answer=413770#post-id-413770

My system info if at all helpful:

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.19.0-38-generic
Remote OS version: Linux x64 5.19.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.82GB (21.35GB free)|
|Process Argv|--crash-reporter-id f6e42113-8e2e-4e15-9049-d5be30db15b8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: foo.bar.baz|
|OS|Linux x64 5.19.0-38-generic|
|CPUs|AMD Ryzen 9|
|Memory (System)|125.70GB (84.67GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Code - OSS with X11/Wayland @ ssh://foo.bar.baz|
|OS|Linux x64 5.19.0-38-generic|
|CPUs|AMD Ryzen 9|
|Memory (System)|125.70GB (84.67GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-empy|dir|0.1.1
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.0.0
vscode-eslint|dba|2.4.0
resourcemonitor|mut|1.0.7


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
pythonb192cf:30669361
functionswalk:30687959
pythonms35:30701012
pythonclientmvcf:30708686

```

</details>
