### ISSUE TITLE
Can't connect to tunnel from desktop VSCode

### ISSUE THREAD

**Issue by johnw42** [microsoft/vscode#168679]
- VS Code Version: 1.74.0
- OS Version: Windows 11

Disabling extensions wasn't helpful because I need an extension to connect to a tunnel.

I have a tunnel I can connect to from vscode.dev. I expect the same result from the desktop app, but it doesn't work.  When I try to connect, I can see the name I assigned to the server. After clicking it, the status bar briefly shows "Opening remote" in the bottom left, but then it changes to "Disconnected from vscode-remote". Meanwhile there are three popups in the bottom right that say "Connecting to workstation" that don't seem to ever go away. (The name of my server is "workstation".)

Here's the full log from Remote - Runnels with trace-level logging enabled:

```
2022-12-09 15:19:27.186 [info] Resolving tunnel+workstation...
2022-12-09 15:19:27.337 [info] Creating new tunnel proxy server
2022-12-09 15:19:28.790 [info] [proxy] Found tunnel (ID=jg833p8h, Cluster=usw2)
2022-12-09 15:19:28.794 [info] Remote resolution completed
2022-12-09 15:19:28.843 [info] Resolving tunnel+workstation...
2022-12-09 15:19:28.869 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:19:28.873 [info] Remote resolution completed
2022-12-09 15:19:29.231 [info] Resolving tunnel+workstation...
2022-12-09 15:19:29.236 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:19:29.240 [info] Remote resolution completed
2022-12-09 15:19:29.394 [info] Resolving tunnel+workstation...
2022-12-09 15:19:29.396 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:19:29.401 [info] Remote resolution completed
2022-12-09 15:19:29.566 [info] Resolving tunnel+workstation...
2022-12-09 15:19:29.568 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:19:29.572 [info] Remote resolution completed
2022-12-09 15:20:00.305 [info] Resolving tunnel+workstation...
2022-12-09 15:20:00.420 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:20:00.427 [info] Remote resolution completed
2022-12-09 15:20:00.589 [info] Resolving tunnel+workstation...
2022-12-09 15:20:00.591 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:20:00.592 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.594 [info] Remote resolution completed
2022-12-09 15:20:00.612 [info] Resolving tunnel+workstation...
2022-12-09 15:20:00.614 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:20:00.615 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.616 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.618 [info] Remote resolution completed
2022-12-09 15:20:00.622 [info] Resolving tunnel+workstation...
2022-12-09 15:20:00.623 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:20:00.624 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.625 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.625 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.627 [info] Remote resolution completed
2022-12-09 15:20:00.651 [info] Resolving tunnel+workstation...
2022-12-09 15:20:00.653 [info] Found running server in \\.\pipe\vscode-tunneling-workstation-8c433acce720178a8ec49fc85a7ad3722c7af803-sock
2022-12-09 15:20:00.654 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.654 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.654 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.655 [debug] [proxy] Server connection from:   null   null
2022-12-09 15:20:00.657 [info] Remote resolution completed
```

Reporting an issue from VS Code didn't work--the "Create on GitHub" does nothing--so here is the additional info from the dialog:

<html>
<body>

CPUs | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) |  
Memory (System) | 31.59GB (14.54GB free)
Process Argv | --disable-extensions --crash-reporter-id 371c0d5f-2a9f-4a9f-a5e4-fe89f6ab376b
Screen Reader | no
VM | 0%

</body>
</html>

<html>
<body>

Remote | vscode-remote
-- | --
  | Connection to 'vscode-remote' could not be established Illegal argument: connectionToken

</body>
</html>

vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

**Comment by aburgett87** [comment]
I have the same issue and found some additional information

```
 INFO [attempt 1] Invoking resolveAuthority(tunnel)
 ERR [attempt 1] resolveAuthority(tunnel) returned an error after 2115 ms Error: Illegal argument: connectionToken
	at P (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1129)
	at new Y (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:17352)
	at C.resolve (c:\Users\AlexBurgett\.vscode\extensions\ms-vscode.remote-server-1.1.2022120609\dist\node\extension.js:2:945336)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:18208)
INFO [attempt 2] Invoking resolveAuthority(tunnel)
ERR [attempt 2] resolveAuthority(tunnel) returned an error after 25 ms Error: Illegal argument: connectionToken
	at P (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1129)
	at new Y (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:17352)
	at C.resolve (c:\Users\AlexBurgett\.vscode\extensions\ms-vscode.remote-server-1.1.2022120609\dist\node\extension.js:2:945336)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:18208)
INFO [attempt 3] Invoking resolveAuthority(tunnel)
ERR [attempt 3] resolveAuthority(tunnel) returned an error after 16 ms Error: Illegal argument: connectionToken
	at P (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1129)
	at new Y (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:17352)
	at C.resolve (c:\Users\AlexBurgett\.vscode\extensions\ms-vscode.remote-server-1.1.2022120609\dist\node\extension.js:2:945336)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:18208)
INFO [attempt 4] Invoking resolveAuthority(tunnel)
lERR [attempt 4] resolveAuthority(tunnel) returned an error after 21 ms Error: Illegal argument: connectionToken
	at P (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1129)
	at new Y (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:17352)
	at C.resolve (c:\Users\AlexBurgett\.vscode\extensions\ms-vscode.remote-server-1.1.2022120609\dist\node\extension.js:2:945336)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:18208)
INFO [attempt 5] Invoking resolveAuthority(tunnel)
ERR [attempt 5] resolveAuthority(tunnel) returned an error after 8 ms Error: Illegal argument: connectionToken
	at P (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1129)
	at new Y (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:17352)
	at C.resolve (c:\Users\AlexBurgett\.vscode\extensions\ms-vscode.remote-server-1.1.2022120609\dist\node\extension.js:2:945336)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (c:\Users\AlexBurgett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:18208)
log.ts:316   ERR Error received from starting extension host (kind: Remote)
```

**Comment by Yarden-zamir** [comment]
Related to https://github.com/microsoft/vscode-remote-release/issues/7680

**Comment by connor4312** [comment]
Duplicates
