### ISSUE TITLE
Cursor missing

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [microsoft/vscode#168850]
Type: <b>Bug</b>

Cursor is not showing in the editor. The breadcrumbs show that there is a change, and the cursor position and input also works. The cursor in the Terminal is showing correctly.

```
log.ts:316   ERR Cannot read properties of undefined (reading 'length'): TypeError: Cannot read properties of undefined (reading 'length')
    at new ee (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:11:8173)
    at b.p (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:80410)
    at b.prepareRender (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:79018)
    at y.prepareRender (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:548:30251)
    at U.I (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:671:100981)
    at vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:671:100346
    at H (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:671:102829)
    at U.G (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:671:100335)
    at U.v (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:671:98445)
    at Object.getLineWidth (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:671:99198)
    at f.getLineWidth (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:667:59069)
    at s.u (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:6082)
    at s.o (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:4944)
    at s.g (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:2023)
    at s.createMouseTarget (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:1459)
    at C.p (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:13637)
    at C.u (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:13972)
    at vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:668:11399
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/<home>/AppData/Local/Programs/Microsoft%20VS%20Code%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:665:40200)
```

VS Code version: Code - Insiders 1.75.0-insider (250a8f36c93721830b0ef2e39dc065d6944d9912, 2022-12-12T05:22:29.428Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5875U with Radeon Graphics      (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|46.80GB (30.63GB free)|
|Process Argv|--log-net-log=netlog.json --ignore-certificate-error --crash-reporter-id 5f9e326c-2a01-458b-95a4-f411641d6f56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
iconify|ant|0.4.2
icons-carbon|ant|0.2.6
atlascode|atl|2.10.12
markdown-shiki|bie|0.1.1
path-intellisense|chr|2.8.3
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
typescript-notebook|don|2.0.6
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.86
prettier-vscode|esb|9.10.3
syntax-highlighter|evg|0.5.0
vscode-firefox-debug|fir|2.9.8
gitlab-workflow|Git|3.57.2
vscode-graphql|Gra|0.8.4
vscode-graphql-execution|Gra|0.1.6
vscode-graphql-syntax|Gra|1.0.5
ts-error-translator|mat|0.5.1
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.1.2022121209
angular-console|nrw|17.27.0
vscode-twoslash-queries|Ort|1.1.0
git-file-history|pom|1.0.1
vscode-yaml|red|1.10.1
just|ske|2.0.0
sass-indented|syl|1.8.23
vscodeintellicode|Vis|1.2.29
vscode-conventional-commits|viv|1.24.4
volar|Vue|1.0.13
vscode-typescript-vue-plugin|Vue|1.0.12
change-case|wma|1.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474
vscrp:30624060
pythonsymbol12:30622696
fim-prod:30623723

```

</details>

**Comment by sschneider-ihre-pvs** [comment]
I redownloaded and reinstalled and now it seems to work.

**Comment by sschneider-ihre-pvs** [comment]
Oh that was already a rollback :D thanks
