### ISSUE TITLE
Extraneous error message when running scripts\test.bat --coverage

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16926]
2577 passing (26s)

Error: Could not find source map for: "C:\Alex\src\vscode\out\vs\base\common\winjs.base.js"
    at C:\Alex\src\vscode\node_modules\remap-istanbul\lib\remap.js:213:11
    at Array.forEach (native)
    at C:\Alex\src\vscode\node_modules\remap-istanbul\lib\remap.js:192:22
    at Array.forEach (native)
    at remap (C:\Alex\src\vscode\node_modules\remap-istanbul\lib\remap.js:191:12)
    at process.<anonymous> (C:\Alex\src\vscode\test\all.js:117:27)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:146:15)
    at done (C:\Alex\src\vscode\node_modules\mocha\bin\_mocha:417:32)
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by bpasero** [comment]
@alexandrudima fyi I pushed a while ago a change to add some ignores to remap: https://github.com/Microsoft/vscode/commit/ccd59d2c75fa181d0fd2db4964eb3b259f8d1150

**Comment by alexandrudima** [comment]
backslashes ?

**Comment by bpasero** [comment]
Yeah probably...
