### ISSUE TITLE
Unable to preview markdown

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16924]
```
workbench.main.js:formatted:94050Unable to open 'Preview 'v1_8.md'': Invalid editor input..: Error: Unable to open 'Preview 'v1_8.md'': Invalid editor input..
    at t.doHandleSetInputError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:4015)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:3621
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18878)
    at t.doSetInput (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:3367)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:1246
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19502)
    at t.doOpenEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:1218)
    at t.openEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:495)
    at e.doOpenEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:114:194)
    at e.openEditor (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:113:31649)
```

**Comment by jrieken** [comment]
@joaomoreno I explodes here: `return o._textModelResolverService.createModelReference(e).then(function(t) {`

**Comment by joaomoreno** [comment]
Steps?

**Comment by jrieken** [comment]
write release notes

**Comment by jrieken** [comment]
pretty sure this happens when showing preview, not showing preview for 3 minutes, showing preview again.

**Comment by joaomoreno** [comment]
Oh. This is not related to Release Notes, but to any Markdown file.

**Comment by joaomoreno** [comment]
Nope that's still not it.

**Comment by bpasero** [comment]
I think @sandy081 saw it too

**Comment by sandy081** [comment]
Yes I got this too.. and I had to refresh VS Code to get the preview

**Comment by jrieken** [comment]
step to reproduce:

* open md file
* open preview in place/the same slot
* wait 3 minutes and a few seconds
* open preview to the side
* 💥
