### ISSUE TITLE
diff editor: `Uncaught Error: Assertion Failed` when enabling `editor.ignoreTrimWhitespace`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#169552]
Version: 1.75.0 from main

- set "diffEditor.ignoreTrimWhitespace": false

- File 1, using 4 spaces as indentation
```
if True:
    print(2)
```
- File 2, using tab as indentation
```
if True:
	print(2)  
```

- Select both files and invoke `Compare Selected`

Dev tools pop up on debugger statement
```
Uncaught Error: Assertion Failed

Error: Assertion Failed
    at assertFn (../../../vs/base/common/assert.js:48:45)
    at SmartLinesDiffComputer.computeDiff (../../../vs/editor/c…ffComputer.js:52:35)
    at EditorSimpleWorker.computeDiff (../../../vs/editor/c…pleWorker.js:250:42)
    at EditorSimpleWorker.computeDiff (../../../vs/editor/c…pleWorker.js:244:39)
    at SimpleWorkerServer._handleMessage (../../../vs/base/com…pleWorker.js:365:69)
    at Object.handleMessage (../../../vs/base/com…pleWorker.js:350:55)
    at SimpleWorkerProtocol._handleRequestMessage (../../../vs/base/com…pleWorker.js:156:42)
    at SimpleWorkerProtocol._handleMessage (../../../vs/base/com…pleWorker.js:125:33)
    at SimpleWorkerProtocol.handleMessage (../../../vs/base/com…pleWorker.js:118:18)
    at SimpleWorkerServer.onmessage (../../../vs/base/com…pleWorker.js:355:28)
    at eval (../../../vs/base/common/errors.js:19:31)
bootstrap-window.js:261 [uncaught exception]: null
````

**Comment by alexdima** [comment]
@aeschli I'm having trouble reproducing. Have you customized other settings?

<img width="866" alt="image" src="https://user-images.githubusercontent.com/5047891/208471347-256c033a-7e66-4519-829b-4e5f7031dea0.png">

**Comment by aeschli** [comment]
Blocks https://github.com/microsoft/vscode/pull/169555

**Comment by alexdima** [comment]
I can reproduce when typing a `<space>` in one of the sides:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/5047891/208472426-6934caa4-11eb-4f67-ae2d-96eed584628d.png">

**Comment by alexdima** [comment]
It looks like this was an incorrect assertion introduced via https://github.com/microsoft/vscode/commit/c2cc481940d538a41c311411484ffc909b8054b8

I will comment out the assertion for now.

**Comment by aeschli** [comment]
You are correct, there needs to be additional spaces in file 2 after `print(2)`. Sorry for that. I fixed the description
```
if True:
	print(2)  
```
