### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by jayeshtcpl** [microsoft/vscode#169728]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20221220

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `@monodon/typescript-nx-imports-plugin`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression.
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:157084:15)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:158460:12)
    at c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:158691:64
    at flatMap (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:2975:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:158691:24)
    at updateOpen (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:159774:29)
    at c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:161945:69
    at IpcIOSession.executeWithRequestId (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:161937:14)
    at IpcIOSession.executeCommand (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:161945:29)
    at IpcIOSession.onMessage (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:161973:51)
    at process.<anonymous> (c:\Users\ShindeJ\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202212200\node_modules\typescript\lib\tsserver.js:163396:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.87GB free)|
|Process Argv|. --crash-reporter-id a700adaa-2838-4f12-9a17-d1c6c944b1ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
prettier-vscode|esb|9.10.3
vscode-jest-runner|fir|0.4.59
gitless|maa|11.7.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.3
vscode-typescript-next|ms-|5.0.202212200
angular-console|nrw|17.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

You have a TS Server plugin enabled which could cause this
