### ISSUE TITLE
VSC does not start on VM, GLX 1.3 is requied - 

### ISSUE THREAD

**Issue by kazaroff** [Microsoft/vscode#16994]
- VSCode Version: code-1.7.2-1479766213.el7.x86_64
- OS Version: CentOS x86_64 (running on VM, remote X2GO session, local X11 runs under Ubuntu 14.04)

A fresh install fails to start:

> code --verbose
[6500:1209/181546:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[6520:1209/181546:ERROR:gl_surface_glx.cc(386)] GLX 1.3 or later is required.
[6520:1209/181546:ERROR:gl_surface_x11.cc(252)] GLSurfaceGLX::InitializeOneOff failed.
[6520:1209/181546:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process.
[6520:1209/181546:ERROR:gpu_child_thread.cc(369)] Exiting GPU process due to errors during initialization
{ Error: ENOENT: no such file or directory, open '/home/daqoncall/.config/Code/storage.json'
    at Error (native)
    at Object.fs.openSync (original-fs.js:640:18)
    at Object.fs.readFileSync (original-fs.js:508:33)
    at e.load (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:7178)
    at e.getItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:6716)
    at e.handleUpdated (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:9:6346)
    at new e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:9:6247)
    at v (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:29399)
    at t._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:16379)
    at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:17354)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/daqoncall/.config/Code/storage.json' }

Can GLX 1.3 requirement be fulfilled on a VM?

It looks I need to find a way to upgrade GLX on my x2go server:
> glxinfo
name of display: :81
display: :81  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.2

**Comment by kazaroff** [comment]
Seems to be a duplicate, workaround is available:
https://github.com/Microsoft/vscode/issues/3451#issuecomment-227197582
