### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#170852]
```javascript
TypeError: Cannot read properties of undefined (reading 'replace')
at E in src/vs/base/common/labels.ts:410:16
at Ft.bb in out/vs/code/electron-main/main.js:83:23743
at Ft.U in src/vs/platform/menubar/electron-main/menubar.ts:652:22
at <anonymous> in src/vs/platform/menubar/electron-main/menubar.ts:503:24
at Array.forEach (<anonymous>)
at Ft.L in src/vs/platform/menubar/electron-main/menubar.ts:478:9
at <anonymous> in src/vs/platform/menubar/electron-main/menubar.ts:484:10
at Array.forEach (<anonymous>)
at Ft.L in src/vs/platform/menubar/electron-main/menubar.ts:478:9
at Ft.M in src/vs/platform/menubar/electron-main/menubar.ts:514:9
at Ft.I in src/vs/platform/menubar/electron-main/menubar.ts:377:9
at Ft.H in src/vs/platform/menubar/electron-main/menubar.ts:270:9
at new Ft in src/vs/platform/menubar/electron-main/menubar.ts:97:8
at b.j in src/vs/platform/instantiation/common/instantiationService.ts:119:18
at b.createInstance in src/vs/platform/instantiation/common/instantiationService.ts:85:18
at M.e in src/vs/platform/menubar/electron-main/menubarMainService.ts:35:36
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=727d2d32aea02baf7d13fa38787e8ed64dd858d0&bH=0e42c422-3cb8-0050-60ad-b5b86472cb31)

**Comment by bpasero** [comment]
I checked and this can only be happening from the dynamic labels from this menu:

https://github.com/microsoft/vscode/blob/fe436d3f1359675c38963a271864b42e34f5ce5d/src/vs/platform/menubar/electron-main/menubar.ts#L60

So I wonder if from the renderer we send down potentially null unsafe properties.

**Comment by rzhao271** [comment]
Doesn't seem to show up on the errors site anymore. Closing as stale.
