### ISSUE TITLE
Error al ejecutar Aplicaciones GUI de Java

### ISSUE THREAD

**Issue by k-kurt** [microsoft/vscode#170973]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  version web
- OS Version: Windows 10 Pro

Steps to Reproduce:
Me salta este error cuando quiero ejecutar aplicaciones GUI de Java y no puedo instalar nada en la PC ya que es del trabajo
El mensaje es: 
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at marcoCuadroTexto.<init>(video86.java:23)
        at video86.main(video86.java:15)

![image](https://user-images.githubusercontent.com/81799020/211592367-2aebf950-8b08-4148-b078-fdb6cba3de83.png)

**Comment by roblourens** [comment]
This is probably an issue with your system or configuration. If you think it's an issue with the Java extension, you can file an issue on their repo.

**Comment by k-kurt** [comment]
La documentación que se presenta en la pagina de Microsoft sobre Visual Studio Code es suficiente para resolver este problema? por que la gran mayoría esta enfocado a la Visual Studio Code Desktop
