### ISSUE TITLE
ERR Cannot read properties of undefined (reading 'dragStartDisposable')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#171041]
Found this in devtools, I played a bit with settings:

```
ERR Cannot read properties of undefined (reading 'dragStartDisposable'): TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
    at ListView._splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:334:22)
    at ListView.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:319:29)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:1105:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:939:23)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:1105:32)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1075:19)
    at IndexTreeModel._setListNodeCollapseState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:266:23)
    at IndexTreeModel._setCollapseState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:237:33)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:233:63
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:939:23)
    at IndexTreeModel.setCollapsed (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:233:39)
    at ObjectTreeModel.setCollapsed (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:155:31)
    at TOCTree.collapseAll (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1353:24)
    at SettingsEditor2.triggerSearch (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1089:34)
    at SettingsEditor2.onSearchInputChanged (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1032:24)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:383:60
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js:276:32
```

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/900690/211766630-58611cad-a485-4ed3-bdbc-60d6aca79c9f.png">

**Comment by joaomoreno** [comment]
@rzhao271 Let me know if you can repro and find out the issue is deep in the list/tree.

**Comment by joaomoreno** [comment]
@rzhao271 Got you repro steps!

1. Make the workbench window rather small.
2. Go into 2x2 editor layout, so you get even smaller editors
3. Press <kbd>Cmd ,</kbd> to open the Settings Editor in one of the editor groups
4. Search for `sash`
5. Press <kbd>Cmd W</kbd> to close the Settings Editor

🐛 That exception shows up!


https://github.com/microsoft/vscode/assets/22350/c5e21e7c-f3b2-4325-9414-358b77598b72
