### ISSUE TITLE
Interactive window scrolls after execute

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#171270]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=199417&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=5e43d7ff-5b8d-51b4-ea10-68cb35d0fdb0

```
stack trace: Error: onDidOpenNotebookEditor TIMEOUT reached
    at Timeout._onTimeout (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/notebook.editor.test.ts:28:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
onDidOpenNotebookEditor TIMEOUT reached: Error: onDidOpenNotebookEditor TIMEOUT reached
    at Timeout._onTimeout (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/notebook.editor.test.ts:28:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by amunger** [comment]
closing for a more recent failure issue https://github.com/microsoft/vscode/issues/175729#event-8634400757
