### ISSUE TITLE
LocalEnv variables empty in .devcontainer.json using WSL2

### ISSUE THREAD

**Issue by Tobulus** [microsoft/vscode#171517]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Try to open a container with the provided `.devcontainer.json` using the WSL2 backend (its basically an Ubuntu 20 image) on Windows.
2. The start fails due to `localEnv` variables not being resolved/empty.

I also tried to add the used `localEnv` variables into the `.bashrc` or `.profile`, but they stay empty. If I echo those variables in the bash where I start VS Code, these variables are set. I found multiple issues on github with kind of the same problem which are already closed/fixed, but for me this is still not working. Is there a error in my setup or is this a bug?

.devcontainer.json
```
{
    "name": "foobar-builder",
    "image": "myurl/foobar-builder:latest",
    "remoteUser": "${localEnv:USER}",
    "overrideCommand": false,
    "extensions": [
        "ms-vscode.cpptools",
        "ms-vscode.cmake-tools",
        "cheshirekow.cmake-format",
        "webfreak.debug",
        "xaver.clang-format",
        "cschlosser.doxdocgen",
        "gruntfuggly.todo-tree"
    ],
    "runArgs": ["-t", "-v", "${localEnv:HOME}/.conan:${localEnv:HOME}/.conan"],
    "mounts": [
        "source=${localEnv:HOME}/.ssh,target=${localEnv:HOME}/.ssh,type=bind,consistency=cached",
        "source=${localEnv:HOME}/.bashrc,target=${localEnv:HOME}/.bashrc,type=bind,consistency=cached"
    ],
    "containerEnv": {
        "http_proxy":http://172.17.0.1:3128/,
        "https_proxy": http://172.17.0.1:3128/,
        "USERID": "${localEnv:UID}",
        "USERNAME": "${localEnv:USER}",
        "USERHOME": "${localEnv:HOME}"
    }
}
```
Log:
```
[74 ms] Dev Containers 0.266.1 in VS Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534).

[73 ms] Start: Run: wsl -d FOOBAR -e wslpath -u \\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev\foo-bar-dev.code-workspace

[75 ms] Start: Run: wsl -d FOOBAR -e wslpath -u \\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev\foo-bar-dev.code-workspace

[76 ms] Start: Run: wsl -d FOOBAR -e wslpath -u \\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev\foo-bar-dev.code-workspace

[786 ms] Start: Run: wsl -d FOOBAR -e wslpath -u \\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev\foo-bar-dev.code-workspace

[1337 ms] Start: Resolving Remote

[1352 ms] Start: Run: wsl -d FOOBAR -e wslpath -u \\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev

[2065 ms] Start: Run: wsl -d FOOBAR -e /bin/sh -c cd '/home/user/dev/foo-bar-dev' && /bin/sh

[2089 ms] Start: Run in host: id -un

[2452 ms] user

[2453 ms]

[2453 ms] Start: Run in host: cat /etc/passwd

[2455 ms] Start: Run in host: echo ~

[2456 ms] /home/user

[2457 ms]

[2458 ms] Start: Run in host: test -x '/home/user/.vscode-remote-containers/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node'

[2459 ms]

[2459 ms]

[2459 ms] Exit code 1

[2460 ms] Start: Run in host: test -x '/home/user/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node'

[2461 ms]

[2461 ms]

[2462 ms] Start: Run in host: test -f '/home/user/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node_modules/node-pty/package.json'

[2463 ms]

[2463 ms]

[2463 ms] Start: Run in host: test -f '/home/user/.vscode-remote-containers/dist/vscode-remote-containers-server-0.266.1.js'

[2464 ms]

[2465 ms]

[2468 ms] userEnvProbe: loginInteractiveShell (default)

[2469 ms] userEnvProbe shell: /bin/bash

[4473 ms] Start: Run in Host: /bin/sh

[4478 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "

[4973 ms] userEnvProbe is taking longer than 2 seconds. Process tree:

  13168: /bin/bash -lic echo -n d909758c75f5677d8238ad31167882f5; cat /proc/self/environ; echo -n d909758c75f5677d8238ad31167882f5

[12481 ms] userEnvProbe is taking longer than 10 seconds. Avoid waiting for user input in your shell's startup scripts. Continuing.

[12483 ms] Setting up container for folder or workspace: /home/user/dev/foo-bar-dev/foo-bar-dev.code-workspace

[12497 ms] Start: Check Docker is running

[12498 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}

[12534 ms] Server API version: 1.41

[12535 ms] Start: Run in Host: docker volume ls -q

[12571 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev --filter label=vsch.quality=stable

[12600 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev

[12632 ms] Start: Run in Host: /home/user/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node /home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/user/dev/foo-bar-dev --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev --log-level debug --log-format json --config /home/user/dev/foo-bar-dev/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true

[12853 ms] (node:14168) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

[12853 ms] (Use `node --trace-deprecation ...` to show where the warning was created)

[12857 ms] @devcontainers/cli 0.25.2. Node.js v16.14.2. linux 5.15.79.1-microsoft-standard-WSL2 x64.

[12856 ms] Start: Run: docker buildx version

[12936 ms] [github.com/docker/buildx](http://github.com/docker/buildx) v0.9.1-docker ed00243a0ce2a0aee75311b06e32d33b44729689

[12937 ms]

[12937 ms] Start: Resolving Remote

[12941 ms] Start: Run: git rev-parse --show-cdup

[12946 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev

[12974 ms] Start: Run: docker inspect --type image [foobar-builder:latest](foobar-builder:latest)

[13000 ms] local container features stored at: /home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/node_modules/vscode-dev-containers/container-features

[13002 ms] Start: Run: tar --no-same-owner -x -f -

[13034 ms] Start: Run: docker -v

[13061 ms] Start: Run: docker events --format {{json .}} --filter event=start

[13064 ms] Start: Starting container

[13064 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/user/dev/foo-bar-dev,target=/workspaces/foo-bar-dev --mount source=/etc/apt/sources.list.d/nd-artifactory-https.list,target=/etc/apt/sources.list.d/nd-artifactory-https.list,type=bind,consistency=cached --mount source=/.ssh,target=/.ssh,type=bind,consistency=cached --mount source=/.bashrc,target=/.bashrc,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev -e http_proxy=http://172.17.0.1:3128/ -e https_proxy=http://172.17.0.1:3128/ -e USERID= -e USERNAME= -e USERHOME= -t -v /.conan:/.conan --entrypoint /bin/sh -l devcontainer.metadata=[{"customizations":{"vscode":{"extensions":["ms-vscode.cpptools","ms-vscode.cmake-tools","cheshirekow.cmake-format","webfreak.debug","xaver.clang-format","cschlosser.doxdocgen","gruntfuggly.todo-tree"]}},"mounts":["source=/etc/apt/sources.list.d/nd-artifactory-https.list,target=/etc/apt/sources.list.d/nd-artifactory-https.list,type=bind,consistency=cached","source=${localEnv:HOME}/.ssh,target=${localEnv:HOME}/.ssh,type=bind,consistency=cached","source=${localEnv:HOME}/.bashrc,target=${localEnv:HOME}/.bashrc,type=bind,consistency=cached"],"containerEnv":{"http_proxy":http://172.17.0.1:3128/,"https_proxy":http://172.17.0.1:3128/,"USERID":"${localEnv:UID}","USERNAME":"${localEnv:USER}","USERHOME":"${localEnv:HOME}"},"remoteUser":"${localEnv:USER}","overrideCommand":false}] [builder:latest](builder:latest) -c echo Container started

docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /.ssh.

See 'docker run --help'.

[13098 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev

[13120 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/user/dev/foo-bar-dev,target=/workspaces/foo-bar-dev --mount source=/etc/apt/sources.list.d/nd-artifactory-https.list,target=/etc/apt/sources.list.d/nd-artifactory-https.list,type=bind,consistency=cached --mount source=/.ssh,target=/.ssh,type=bind,consistency=cached --mount source=/.bashrc,target=/.bashrc,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev -e http_proxy=http://172.17.0.1:3128/ -e https_proxy=http://172.17.0.1:3128/ -e USERID= -e USERNAME= -e USERHOME= -t -v /.conan:/.conan --entrypoint /bin/sh -l devcontainer.metadata=[{"customizations":{"vscode":{"extensions":["ms-vscode.cpptools","ms-vscode.cmake-tools","cheshirekow.cmake-format","webfreak.debug","xaver.clang-format","cschlosser.doxdocgen","gruntfuggly.todo-tree"]}},"mounts":["source=/etc/apt/sources.list.d/nd-artifactory-https.list,target=/etc/apt/sources.list.d/nd-artifactory-https.list,type=bind,consistency=cached","source=${localEnv:HOME}/.ssh,target=${localEnv:HOME}/.ssh,type=bind,consistency=cached","source=${localEnv:HOME}/.bashrc,target=${localEnv:HOME}/.bashrc,type=bind,consistency=cached"],"containerEnv":{"http_proxy":http://172.17.0.1:3128/,"https_proxy":http://172.17.0.1:3128/,"USERID":"${localEnv:UID}","USERNAME":"${localEnv:USER}","USERHOME":"${localEnv:HOME}"},"remoteUser":"${localEnv:USER}","overrideCommand":false}] [builder:latest](builder:latest) -c echo Container started

[13121 ms] trap "exit 0" 15

[13121 ms] exec "$@"

[13121 ms] while sleep 1 & wait $!; do :; done - /runasuser.sh /bin/bash

[13121 ms]     at Aoe (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1355)

[13122 ms]     at uT (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1291)

[13122 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)

[13122 ms]     at async Poe (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:2128)

[13122 ms]     at async Zf (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:3278)

[13122 ms]     at async aue (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15276)

[13122 ms]     at async oue (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15030)

[13125 ms] Exit code 1

[13130 ms] Command failed: /home/user/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node /home/user/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/user/dev/foo-bar-dev --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\FOOBAR\home\user\dev\foo-bar-dev --log-level debug --log-format json --config /home/user/dev/foo-bar-dev/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true

[13131 ms] Exit code 1
```

**Comment by Tobulus** [comment]
Found the problem: was starting a service in my .profile which is probably also creating the logs `
[12481 ms] userEnvProbe is taking longer than 10 seconds`
