### ISSUE TITLE
Statusbar Timeout (Smoke Test - Windows/MacOS)

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#171641]
From windows error:
```
 1) VSCode Smoke Tests (Electron)
       Statusbar
         verifies presence of all default status bar elements:
     Error: Timeout: get element '.statusbar-item[id^="status.scm."] .codicon.codicon-git-branch' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:269:11)
      at Code.waitForElement (D:\a\_work\1\s\test\automation\src\code.ts:222:10)
      at StatusBar.waitForStatusbarElement (D:\a\_work\1\s\test\automation\src\statusbar.ts:27:3)
      at Context.<anonymous> (src\areas\statusbar\statusbar.test.ts:18:4)

  2) VSCode Smoke Tests (Electron)
       Statusbar
         verifies that 'quick input' opens when clicking on status bar elements:
     Error: Timeout: click '.statusbar-item[id^="status.scm."] .codicon.codicon-git-branch' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:269:11)
      at Code.waitAndClick (D:\a\_work\1\s\test\automation\src\code.ts:210:3)
      at StatusBar.clickOn (D:\a\_work\1\s\test\automation\src\statusbar.ts:31:3)
      at Context.<anonymous> (src\areas\statusbar\statusbar.test.ts:35:4)
```
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=199870&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=d3816dfe-5f5f-5b74-f77f-0a43291213b6

**Comment by andreamah** [comment]
might be from https://github.com/microsoft/vscode/commit/9276e10764c160d1a65f8634f10d9d7adf072d3e?
