### ISSUE TITLE
MacOS Smoke Test - vscode-smoketest-check extension timeout

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#171644]
```
  1) VSCode Smoke Tests (Web)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:269:11)
      at Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/src/code.ts:226:3)
      at QuickInput.waitForQuickInputOpened (/Users/runner/work/1/s/test/automation/src/quickinput.ts:20:3)
      at QuickInput.selectQuickInputElement (/Users/runner/work/1/s/test/automation/src/quickinput.ts:49:3)
      at QuickAccess.runCommand (/Users/runner/work/1/s/test/automation/src/quickaccess.ts:182:3)
      at Context.<anonymous> (src/areas/extensions/extensions.test.ts:25:4)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=199862&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=dc7a7a05-ae89-521b-55db-0cb2ded34668

**Comment by joyceerhl** [comment]
This failed again https://dev.azure.com/monacotools/Monaco/_build/results?buildId=201480&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=b073af95-e680-56c1-96ee-800a8717d462

**Comment by sandy081** [comment]
This is no longer happening. Hence closing
