### ISSUE TITLE
"Revert Selected Ranges" not working- m.getChanges is not a function

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#171863]
- Open https://github.com/microsoft/vscode/blob/3d2e10fa6ee6c30cbc72647dff512bf16cc94403/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
- Do "organize imports"
- Select all the imports and run "Revert Selected Ranges"

<img width="558" alt="image" src="https://user-images.githubusercontent.com/323878/213789508-757506b7-014c-42cc-a654-4046ab0f6f5f.png">

```
2023-01-20 13:32:25.877 [error] TypeError: m.getChanges is not a function
    at cc.$getDiffInformation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2301:14870)
    at m.N (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:15147)
    at m.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:14865)
    at m.H (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:13958)
    at m.G (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:12939)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:11727
    at p.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at r.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:553:15221)
    at q.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1671:1489) git.revertSelectedRanges {"value":"vscode.git","c":"vscode.git"}
```

**Comment by DFelten** [comment]
I think on mac there is the same problem. When I try to revert a change within a file, there is a git error. But the git output is empty (or at least nothing new appears after trying to revert a change).

<img width="698" alt="CleanShot 2023-01-22 at 14 07 10@2x" src="https://user-images.githubusercontent.com/1169185/213917432-2011b08a-c240-4232-a51e-1fe044eaa172.png">

<img width="295" alt="CleanShot 2023-01-22 at 14 05 23@2x" src="https://user-images.githubusercontent.com/1169185/213917358-baade0bb-adc9-4517-a5f0-b4420c925e71.png">

**Comment by lszomoru** [comment]
@alexr00, it looks like this is a regression that was introduced with [this commit](https://github.com/microsoft/vscode/commit/50bf559c22e1719d74d75bb27e3c450e876cdb86). 
In that commit the `getChanges()` method has been removed which unfortunately is used here: https://github.com/microsoft/vscode/blob/1278cb5e744d6abf8467a199585d26ce5a53034d/src/vs/workbench/api/browser/mainThreadEditors.ts#L271-L272

I do not have full contact on why the `as any` cast is being used here. @joaomoreno do you have any context?

**Comment by lszomoru** [comment]
I have investigated some other issues and it looks like that commit might have a broader impact as the stage/revert  changes commands also seem to be broken. The root cause is that the `vscode.git` extension is expecting `LineChange[]` while it gets `LabeledChange[]`. Let's get together first thing tomorrow morning to get to the bottom of this. Thanks!

**Comment by lszomoru** [comment]
Thank you very much @alexr00 🎉

**Comment by kamenminkov** [comment]
That was fixed so quickly that I didn't have time to complain :D
Thank you!
