### ISSUE TITLE
on linux, running debug results in error

### ISSUE THREAD

**Issue by bedenko** [Microsoft/vscode#17192]
- VSCode Version: 1.7.2
- OS Version: xubuntu 16.10 4.8.0-30-generic
- Extension: ms-vscode.csharp

Steps to Reproduce:

1. follow [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet) article
2. on running **Debug (F5)** following error displays: 
> ERROR: Debug adapter process has terminated unexpectedly

If i run *code --verbose*, i get following output:

> 
> [911:1214/201407:INFO:CONSOLE(34)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (34)
> [911:1214/201407:INFO:CONSOLE(34)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (34)
> [911:1214/201407:INFO:CONSOLE(34)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (34)
> [911:1214/201407:INFO:CONSOLE(34)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (34)
> [911:1214/201407:INFO:CONSOLE(5)] "[uncaught exception]: Error: read ECONNRESET", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
> [911:1214/201407:INFO:CONSOLE(5)] "Error: read ECONNRESET
>     at exports._errnoException (util.js:1026:11)
>     at Pipe.onread (net.js:564:26)", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
> [911:1214/201407:INFO:CONSOLE(160)] "Uncaught Error: read ECONNRESET", source: events.js (160)
> [911:1214/201407:INFO:CONSOLE(90)] "Debug adapter process has terminated unexpectedly", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (90)
> [911:1214/201407:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (121)
> [911:1214/201407:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (121)
> [911:1214/201407:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js (121)

From bash, command **dotnet run** executes correctly.

**Comment by bedenko** [comment]
Found a solution.
Looks like [bug](https://github.com/OmniSharp/omnisharp-vscode/issues/1009) in omnisharp-vscode debugger.
