### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by thiagozanetti** [microsoft/vscode#172104]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.9.4

**Steps to reproduce crash**

1. Open a vanilla fresh project in VS Code;
2. Open any ts file in the editor.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-deno-plugin`
- `@twind/typescript-plugin`
- `typescript-svelte-plugin`

**TS Server Log**

[tsserver.log](https://github.com/microsoft/vscode/files/10485816/tsserver.log)

The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124485:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124593:29)
    at Map.forEach (<anonymous>)
    at Object.startCachingPerDirectoryResolution (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124171:50)
    at Project.updateGraphWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174206:38)
    at Project.updateGraph (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174135:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:176493:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:178185:26)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:97
    at Object.flatMap (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179831:46)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.75.0-insider (f1b09237cd400d92987cf7a9681995e8011ef54c, 2023-01-23T11:51:34.518Z)
OS version: Linux x64 5.15.0-59-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2942)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (8.25GB free)|
|Process Argv|. --crash-reporter-id d229837b-f7fc-449e-84b5-a71ccbd219db|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
atlascode|atl|3.0.1
emojisense|bie|0.9.1
markdown-emoji|bie|0.3.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
language-postcss|cpy|1.1.0
vscode-eslint|dba|2.3.3
vscode-deno|den|3.16.0
xml|Dot|2.5.1
gitlens|eam|2023.1.2204
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
codespaces|Git|1.13.6
vscode-pull-request-github|Git|0.57.2023012309
gitlab-workflow|Git|3.59.2
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.23.3
isort|ms-|2022.9.13271012
python|ms-|2023.1.10232135
vscode-pylance|ms-|2023.1.31
remote-containers|ms-|0.272.0
js-debug-nightly|ms-|2023.1.2317
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5808
vetur|oct|0.36.1
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.11.10112022
postcss|ric|2.0.0
rust-analyzer|rus|0.4.1378
twind-intellisense|sas|0.2.1
scss-style-tag|sis|0.1.0
autoimport|ste|1.5.4
svelte-vscode|sve|107.0.1
sass-indented|syl|1.8.23
mako|tom|0.2.0
vscode-icons|vsc|12.2.0
vscode-import-cost|wix|3.3.0
php-debug|xde|1.30.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30622696
a9j8j154:30646983

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

You have multiple TS server plugins enabled which might be causing this issue

**Comment by thiagozanetti** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> You have multiple TS server plugins enabled which might be causing this issue

It seems related to one of the extensions as you've mentioned. (Also mentioned by VS Code but I was not paying much attention. Sorry).
