### ISSUE TITLE
Exception when switching problems view to table mode

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#172310]
Type: <b>Bug</b>

1. In a workspace that has a few problems showing in the problems view
2. Switch the problems view into `table` mode

**bug**
The view goes blank

Here's the relevant exception:

```
 annot read properties of undefined (reading 'dispose'): TypeError: Cannot read properties of undefined (reading 'dispose')
    at ResourceMarkersRenderer.disposeTemplate (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/markers/browser/markersTreeViewer.js:116:33)
    at TreeRenderer.disposeTemplate (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:299:27)
    at PipelineRenderer.disposeTemplate (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/listWidget.js:866:26)
    at ListView.dispose (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:1085:38)
    at dispose (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/lifecycle.js:96:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/lifecycle.js:188:17)
    at DisposableStore.dispose (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/lifecycle.js:172:18)
    at TreeNodeList.dispose (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/list/listWidget.js:1427:30)
    at MarkersTree.dispose (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1521:23)
    at MarkersTree.dispose (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/markers/browser/markersView.js:818:19)
    at dispose (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/lifecycle.js:96:27)
    at DisposableStore.clear (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/lifecycle.js:188:17)
    at MarkersView.onDidChangeViewMode (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/markers/browser/markersView.js:410:40)
    at vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/markers/browser/markersView.js:55:80
    at Listener.invoke (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/event.js:523:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/event.js:697:38)
    at Emitter.fire (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/event.js:662:37)
    at set viewMode [as viewMode] (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/markers/browser/markersTreeViewer.js:630:39)
    at MarkersView.setViewMode (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/markers/browser/markersView.js:336:44)
    at ViewAction.runInView (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/contrib/markers/browser/markers.contribution.js:164:18)
    at ViewAction.run (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/browser/parts/views/viewPane.js:536:29)
    at handler (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/platform/actions/common/actions.js:384:52)
    at InstantiationService.invokeFunction (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:46:24)
    at CommandService._tryExecuteCommand (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/services/commands/common/commandService.js:81:59)
    at CommandService.executeCommand (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/workbench/services/commands/common/commandService.js:50:33)
    at MenuItemAction.run (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/platform/actions/common/actions.js:325:41)
    at ActionRunner.runAction (vscode-file://vscode-app/Users/matb/projects/vscode/out/vs/base/common/actions.js:114:26)
```

VS Code version: Code - Insiders 1.75.0-insider (Universal) (0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6, 2023-01-24T05:22:43.874Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.66GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Will submit a PR for this
