### ISSUE TITLE
Reverting notebook change doesn't update cell editor content

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#172593]
From @joyceerhl 

>  I am now seeing a different problem where the notebook model doesn't update at all after making a change and reverting it from the scm view:

https://user-images.githubusercontent.com/30305945/214960591-08668ea9-a83b-4fdb-937f-d1a8b6a148fc.mp4

_Originally posted by @joyceerhl in https://github.com/microsoft/vscode/issues/172426#issuecomment-1405728709_

**Comment by joyceerhl** [comment]
Maybe related in console:
```
2023-01-26 13:57:20.158 [error] Cannot read properties of undefined (reading 'reset'): TypeError: Cannot read properties of undefined (reading 'reset')
    at https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:1964:88021
    at s.bufferChangeEvents (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:606:71894)
    at https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:1964:87925
    at g.invoke (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:83:145)
    at n.deliver (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:83:2029)
    at a.fire (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:83:1667)
    at T.z (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2331:99811)
    at T.y (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2331:99719)
    at https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2331:99267
    at g.invoke (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:83:145)
```

**Comment by rebornix** [comment]
Not a recent regression, if we insert new cells and then revert, the newly inserted cell will be removed, however the existing cell content will not be reverted. @roblourens any idea?

**Comment by rebornix** [comment]
@joyceerhl that error is from https://github.com/microsoft/vscode/issues/172305

**Comment by joyceerhl** [comment]
Possibly related to this error, if I reload the window I get this:

![image](https://user-images.githubusercontent.com/30305945/214973584-f276ca5d-e310-4045-b2ee-e5317fecb999.png)

```
2023-01-26 15:28:26.099 [error] Error: Element is already detached from the DOM tree
    at vl.kb (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:1911:567)
    at vl.createWebview (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:1898:915)
    at _i.Eb (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2290:14361)
    at _i.setInput (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2290:12643)
    at async o.M (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2320:23027)
    at async o.D (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2320:21622)
    at async o.openEditor (https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2320:20488)
    at async https://main.vscode-cdn.net/insider/07d6f5b35fac559504dec65e3073d796b2d25a55/out/vs/workbench/workbench.web.main.js:2502:13441
```
