### ISSUE TITLE
Extension installation doesn't complete on mac os Ventura

### ISSUE THREAD

**Issue by digfish** [microsoft/vscode#172655]
When trying to install the version above on the mac mini m2 the extensions fails to install with the following error at the console:
```
 2023-01-27 17:24:29.341 [error] XHR failed,XHR failed,XHR failed: Error: XHR failed,XHR failed,XHR failed
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88554
    at Array.reduce (<anonymous>)
    at u (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88540)
    at Z.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:79894)
    at async Z.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:77428)
    at async Z.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:73871)
```
Even installing the last version from the marketplace ( `2023.1.10271009`) fails also.
Tried all the four versions on the marketplace. None worked :( .

**Comment by sandy081** [comment]
@digfish May I know installing any extension fails or only particular extensions? 

Can you also please share following while you reproduce the issue

- F1 > Open View... > Shared

**Comment by digfish** [comment]
@sandy081 just the 'Python' extension.
Wake up this morning with the problem magically solved :).
Here is the output of shared.log anyway:
```01-30 11:58:36.951 [info] Starting worker process with pid 10322 (type: fileWatcher, window: 1).
2023-01-30 11:58:37.119 [info] Deleted from disk mark-wiemer.vscode-autohotkey-plus-plus /Users/sam/.vscode/extensions/mark-wiemer.vscode-autohotkey-plus-plus-3.1.0
2023-01-30 12:02:03.711 [info] Worker process with pid 10322 terminated normally (type: fileWatcher, window: 1).
2023-01-30 12:02:04.200 [info] Starting worker process with pid 10395 (type: fileWatcher, window: 1).
2023-01-30 12:03:16.668 [info] Worker process with pid 10395 terminated normally (type: fileWatcher, window: 1).
2023-01-30 12:03:17.695 [info] Starting worker process with pid 10407 (type: fileWatcher, window: 1).
2023-01-30 12:05:45.313 [info] Getting Manifest... ms-python.python
2023-01-30 12:05:45.320 [info] Installing extension: ms-python.python
2023-01-30 12:05:45.960 [info] Getting Manifest... ms-toolsai.jupyter
2023-01-30 12:05:46.760 [info] Getting Manifest... ms-toolsai.jupyter-keymap
2023-01-30 12:05:47.359 [info] Getting Manifest... ms-toolsai.jupyter-renderers
2023-01-30 12:05:47.956 [info] Getting Manifest... ms-toolsai.vscode-jupyter-cell-tags
2023-01-30 12:05:48.543 [info] Getting Manifest... ms-toolsai.vscode-jupyter-slideshow
2023-01-30 12:05:49.132 [info] Getting Manifest... ms-python.vscode-pylance
2023-01-30 12:05:49.299 [info] Getting Manifest... ms-python.isort
2023-01-30 12:05:49.946 [info] Installing extension: ms-toolsai.jupyter ms-python.python
2023-01-30 12:05:49.946 [info] Installing extension: ms-toolsai.jupyter-renderers ms-python.python
2023-01-30 12:05:49.946 [info] Installing extension: ms-toolsai.vscode-jupyter-cell-tags ms-python.python
2023-01-30 12:05:49.946 [info] Installing extension: ms-toolsai.vscode-jupyter-slideshow ms-python.python
2023-01-30 12:05:49.946 [info] Installing extension: ms-python.vscode-pylance ms-python.python
2023-01-30 12:05:49.946 [info] Installing extension: ms-python.isort ms-python.python
2023-01-30 12:05:50.107 [info] Extracted extension to /Users/sam/.vscode/extensions/.39c9b97a-0567-489f-89ee-3935dc5700d9: ms-toolsai.vscode-jupyter-slideshow
2023-01-30 12:05:50.112 [info] Renamed to /Users/sam/.vscode/extensions/ms-toolsai.vscode-jupyter-slideshow-0.1.5
2023-01-30 12:05:50.113 [info] Extracting completed. ms-toolsai.vscode-jupyter-slideshow
2023-01-30 12:05:50.114 [info] Extracted extension to /Users/sam/.vscode/extensions/.539014e3-4272-4d85-a4fc-7113db2f7592: ms-toolsai.vscode-jupyter-cell-tags
2023-01-30 12:05:50.119 [info] Renamed to /Users/sam/.vscode/extensions/ms-toolsai.vscode-jupyter-cell-tags-0.1.6
2023-01-30 12:05:50.119 [info] Extracting completed. ms-toolsai.vscode-jupyter-cell-tags
2023-01-30 12:06:02.201 [info] Extracted extension to /Users/sam/.vscode/extensions/.fbab5b3b-b6e3-4cdd-897e-78263244acc1: ms-toolsai.jupyter-renderers
2023-01-30 12:06:02.205 [info] Renamed to /Users/sam/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.14
2023-01-30 12:06:02.206 [info] Extracting completed. ms-toolsai.jupyter-renderers
2023-01-30 12:06:16.802 [info] Extracted extension to /Users/sam/.vscode/extensions/.e31f92c5-91e7-4649-baa4-777de4702acc: ms-python.python
2023-01-30 12:06:16.809 [info] Renamed to /Users/sam/.vscode/extensions/ms-python.python-2022.20.2
2023-01-30 12:06:16.811 [info] Extracting completed. ms-python.python
2023-01-30 12:06:16.941 [info] Extracted extension to /Users/sam/.vscode/extensions/.5517344f-747e-45e7-816b-b35b5d0bb0c7: ms-toolsai.jupyter
2023-01-30 12:06:16.946 [info] Renamed to /Users/sam/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109
2023-01-30 12:06:16.951 [info] Extracting completed. ms-toolsai.jupyter
2023-01-30 12:06:20.564 [info] Extracted extension to /Users/sam/.vscode/extensions/.cb1f95ea-d38e-4622-8ac9-b8d095850ac4: ms-python.isort
2023-01-30 12:06:20.568 [info] Renamed to /Users/sam/.vscode/extensions/ms-python.isort-2022.8.0
2023-01-30 12:06:20.569 [info] Extracting completed. ms-python.isort
2023-01-30 12:06:26.888 [info] Extracted extension to /Users/sam/.vscode/extensions/.aa44e68c-7922-4261-a58a-55d4205b20ec: ms-python.vscode-pylance
2023-01-30 12:06:26.909 [info] Renamed to /Users/sam/.vscode/extensions/ms-python.vscode-pylance-2023.1.40
2023-01-30 12:06:26.910 [info] Extracting completed. ms-python.vscode-pylance
2023-01-30 12:06:26.917 [info] Extension installed successfully: ms-toolsai.vscode-jupyter-slideshow
2023-01-30 12:06:26.917 [info] Extension installed successfully: ms-toolsai.vscode-jupyter-cell-tags
2023-01-30 12:06:26.917 [info] Extension installed successfully: ms-toolsai.jupyter-renderers
2023-01-30 12:06:26.917 [info] Extension installed successfully: ms-python.python
2023-01-30 12:06:26.917 [info] Extension installed successfully: ms-toolsai.jupyter
2023-01-30 12:06:26.917 [info] Extension installed successfully: ms-python.isort
2023-01-30 12:06:26.917 [info] Extension installed successfully: ms-python.vscode-pylance```

**Comment by sandy081** [comment]
Which version of VS Code are you on?

**Comment by digfish** [comment]
Hi,
version 1.74.3 .

2023-02-02 18:30 GMT, Sandeep Somavarapu ***@***.***>:
