### ISSUE TITLE
If bashrc executes fish shell at the last line, VSCode SSH Remote  would fails to connect the Server. 

### ISSUE THREAD

**Issue by 2catycm** [microsoft/vscode#172770]
Type: <b>Bug</b>

Fish shell is an alternative to bash. Sometimes without root, we cannot set fish to be the default shell on Linux. In this case, "/path/to/fish" is often appended to the last line of bash to make it default. 
However, with this line appened, VSCode would report 
```log
[19:47:32.161] > fish: Unsupported use of '='. In fish, please use 'set VSC_TMP "${XDG_RUNTIME_DIR:-`echo /tmp`}"'.
[19:47:33.443] "install" terminal command done
[19:47:33.444] Install terminal quit with output: fish: Unsupported use of '='. In fish, please use 'set VSC_TMP "${XDG_RUNTIME_DIR:-`echo /tmp`}"'.
[19:47:33.444] Received install output: fish: Unsupported use of '='. In fish, please use 'set VSC_TMP "${XDG_RUNTIME_DIR:-`echo /tmp`}"'.
[19:47:33.444] Failed to parse remote port from server output
[19:47:33.445] Resolver error: Error: 
	at g.Create (c:\Users\YeCanming\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.95.2023012415\out\extension.js:1:584147)
	at t.handleInstallOutput (c:\Users\YeCanming\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.95.2023012415\out\extension.js:1:582761)
	at t.tryInstall (c:\Users\YeCanming\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.95.2023012415\out\extension.js:1:680758)
	at async c:\Users\YeCanming\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.95.2023012415\out\extension.js:1:643114
	at async t.withShowDetailsEvent (c:\Users\YeCanming\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.95.2023012415\out\extension.js:1:646432)
	at async t.resolve (c:\Users\YeCanming\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.95.2023012415\out\extension.js:1:644164)
	at async c:\Users\YeCanming\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.95.2023012415\out\extension.js:1:721759
```
It seems the syntax is different. 

VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:21:57.802Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes
Connection to 'SSH: QiMingSuperComputer' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.86GB (21.07GB free)|
|Process Argv|--crash-reporter-id 135a1468-6737-4ded-8158-9295063b87c0|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: QiMingSuperComputer' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! Which remote extension are you using?

**Comment by 2catycm** [comment]
I am using  
Published
5/3/2019, 02:40:34
Last released
1/24/2023, 23:18:45
Last updated
1/30/2023, 16:13:17
Identifier
ms-vscode-remote.remote-ssh

**Comment by eleanorjboyd** [comment]
Hello again! The extension actually requires the use of bash- are you trying to use the extension via fish or open a fish terminal after the connection finishes?
