### ISSUE TITLE
The Hosts file is not applied in the network proxy.

### ISSUE THREAD

**Issue by fxzxmic** [microsoft/vscode#172886]
Does this issue occur when all extensions are disabled?: Maybe NO? But this is a bug related to VScode.

- VS Code Version: 1.74.3
- OS Version: Linux(WSL)

Steps to Reproduce:

1. Set /etc/hosts:
```
192.168.138.1   Proxy.local
fe80::192.168.138.1     Proxy.local
```
2. Set proxy:
```
export ALL_PROXY=Socks://Proxy.local:1080
export HTTP_PROXY=$ALL_PROXY
export HTTPS_PROXY=$ALL_PROXY
```
3. Start VScode and error occurred:
```
2023-01-31 11:35:30.627 [error] Failed to establish a socket connection to proxies: ["SOCKS Proxy.local:1080"]: Error: Failed to establish a socket connection to proxies: ["SOCKS Proxy.local:1080"]
	at _PacProxyAgent.<anonymous> (/home/Dev/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node_modules/vscode-proxy-agent/out/agent.js:140:19)
	at Generator.throw (<anonymous>)
	at rejected (/home/Dev/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node_modules/vscode-proxy-agent/out/agent.js:6:65)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
4. When I set it this way, everything is normal:
```
export ALL_PROXY=Socks://[fe80::192.168.138.1]:1080
export HTTP_PROXY=$ALL_PROXY
export HTTPS_PROXY=$ALL_PROXY
```

**One more thing, VScode does not support the ALL_PROXY environment variable. Is this a bug or a deliberate design?**

**Comment by fxzxmic** [comment]
It still exists in version 1.76.1.

**Comment by fxzxmic** [comment]
Oh, it hasn't been fixed yet.
