### ISSUE TITLE
DisposableStore leak in CustomizedMenuWorkbenchToolBar.setActions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#172950]
Seeing this in insiders:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/2193314/215860682-65916ba9-a4ba-4e79-8ba1-007da1481ab3.png">

Not clear on repro

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (lifecycle.ts:270:18)
    at CustomizedMenuWorkbenchToolBar.setActions (toolbar.ts:169:29)
    at CustomizedMenuWorkbenchToolBar.updateToolbar (inlineSuggestionHintsWidget.ts:287:8)
    at CustomizedMenuWorkbenchToolBar.setAdditionalSecondaryActions (inlineSuggestionHintsWidget.ts:292:8)
    at InlineSuggestionHintsContentWidget.update (inlineSuggestionHintsWidget.ts:220:16)
    at InlineSuggestionHintsWidget.update (inlineSuggestionHintsWidget.ts:57:16)
    at inlineSuggestionHintsWidget.ts:50:61
    at Listener.invoke (event.ts:701:17)
    at EventDeliveryQueue.deliver (event.ts:908:22)
    at Emitter.fire (event.ts:869:24)
    at codeEditorWidget.ts:300:35
    at Listener.invoke (event.ts:701:17)
    at PrivateEventDeliveryQueue.deliver (event.ts:908:22)
    at Emitter.fire (event.ts:869:24)
    at EditorConfiguration._recomputeOptions (editorConfiguration.ts:101:21)
    at EditorConfiguration.updateOptions (editorConfiguration.ts:157:8)
    at CodeEditorWidget.updateOptions (codeEditorWidget.ts:438:23)
    at TextResourceEditor.updateEditorControlOptions (textCodeEditor.ts:50:23)
    at TextResourceEditor.updateEditorConfiguration (textEditor.ts:280:9)
    at textEditor.ts:172:59
    at Listener.invoke (event.ts:701:17)
    at EventDeliveryQueue.deliver (event.ts:908:22)
    at Emitter.fire (event.ts:869:24)
    at CodeEditorWidget.setModel (codeEditorWidget.ts:516:26)
    at codeEditorWidget.ts:1606:57
    at Listener.invoke (event.ts:701:17)
    at PrivateEventDeliveryQueue.deliver (event.ts:908:22)
    at Emitter.fire (event.ts:869:24)
    at TextModel.dispose (textModel.ts:371:23)
    at WorkbenchModelService.destroyModel (modelService.ts:533:19)
    at UntitledTextEditorModel.dispose (textEditorModel.ts:236:22)
    at textEditorService.ts:159:57
    at event.ts:94:21
    at Listener.invoke (event.ts:701:17)
    at PrivateEventDeliveryQueue.deliver (event.ts:908:22)
    at Emitter.fire (event.ts:869:24)
    at UntitledTextEditorInput.dispose (editorInput.ts:313:24)
    at UntitledTextEditorInput.dispose (untitledTextEditorInput.ts:179:9)
    at untitledTextEditorInput.ts:58:47
    at Listener.invoke (event.ts:701:17)
    at PrivateEventDeliveryQueue.deliver (event.ts:908:22)
    at Emitter.fire (event.ts:869:24)
    at UntitledTextEditorModel.revert (untitledTextEditorModel.ts:274:21)
    at NativeTextFileService.revert (textFileService.ts:655:18)
    at UntitledTextEditorInput.revert (textResourceEditorInput.ts:71:30)
    at EditorGroupView.doHandleCloseConfirmation (editorGroupView.ts:1597:19)
    at async EditorGroupView.handleCloseConfirmation (editorGroupView.ts:1467:11)
    at async EditorGroupView.closeEditors (editorGroupView.ts:1637:16)
    at async editorCommands.ts:811:5
    at async Promise.all (index 0)
```

Version: 1.75.0-insider (user setup)
Commit: 0615c4f98b07b51d3be6a357e22afec119490c5a
Date: 2023-01-31T00:03:50.170Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by hediet** [comment]
Probably fixed with the inline completions rewrite.
