### ISSUE TITLE
Getting Error Unstrusted while trying to switch extension to a pre realease version

### ISSUE THREAD

**Issue by tomaxsas** [microsoft/vscode#173006]
Type: <b>Bug</b>

Tried with 3 different extensions. Python, pylance, gitlens. All behave the same. After clicking switch to pre release version, i'm getting untrusted popup and nothing happens. 

VS Code version: Code - Insiders 1.75.0-insider (0615c4f98b07b51d3be6a357e22afec119490c5a, 2023-01-31T00:03:50.170Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (10.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS9-stream|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2711)|
|Memory (System)|15.50GB (13.81GB free)|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
LogFileHighlighter|emi|2.16.0
vscode-systemd-support|han|1.0.1
remote-containers|ms-|0.274.0
remote-ssh|ms-|0.95.2023012415
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.1.2023012309
sublime-keybindings|ms-|4.0.10
material-icon-theme|PKi|4.23.1
shellman|Rem|5.6.0
shebang-snippets|rpi|0.1.4
errorlens|use|3.6.0
vscode-icons|vsc|12.2.0
vscode-nginx-conf|ahm|0.1.3
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.17.4
markdown-preview-github-styles|bie|1.0.1
markdown-shiki|bie|0.1.1
markdown-yaml-preamble|bie|0.1.0
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.49.0
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
opensslutils|ffa|1.1.1
code-runner|for|0.12.0
shell-format|fox|7.2.2
gitlab-workflow|Git|3.59.2
todo-tree|Gru|0.0.222
vscode-guid|hea|1.7.0
rest-client|hum|0.25.1
path-autocomplete|ion|1.22.1
vscode-swissknife|lui|1.7.0
bash-ide-vscode|mad|1.32.0
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
ecdc|mit|1.8.0
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.23.3
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.40
jupyter|ms-|2023.1.2000312134
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
hexeditor|ms-|1.9.11
live-server|ms-|0.4.4
linesinfostatusbar|pet|0.0.9
vscode-versionlens|pfl|1.0.14
vscode-regolint|ple|0.2.0
ansible|red|1.1.34
vscode-commons|red|0.0.6
vscode-xml|red|0.24.0
vscode-yaml|red|1.11.0
vscode-coverage-gutters|rya|2.10.3
jinjahtml|sam|0.20.0
vscode-fileutils|sle|3.10.0
vscode-taskexplorer|spm|2.13.2
code-spell-checker|str|2.15.0
tabnine-vscode|Tab|3.6.38
even-better-toml|tam|0.19.0
shellcheck|tim|0.29.3
opa|tsa|0.12.1
vscode-counter|uct|3.2.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
markdown-all-in-one|yzh|3.5.0

</details>

**Comment by tomaxsas** [comment]
This is what seen in console 
```
Signature: Untrusted
    at Pn.download (/home/zalent/.vscode-server-insiders/bin/0615c4f98b07b51d3be6a357e22afec119490c5a/out/vs/server/node/server.main.js:113:1922)
    at async U.h (/home/zalent/.vscode-server-insiders/bin/0615c4f98b07b51d3be6a357e22afec119490c5a/out/vs/server/node/server.main.js:149:90589)
c @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
addNotification @ notifications.ts:204
error @ notificationService.ts:130
lc @ extensionEditor.ts:1765
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
(anonymous) @ event.ts:139
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
(anonymous) @ event.ts:118
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
(anonymous) @ actionbar.ts:120
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
run @ actions.ts:188
await in run (async)
onClick @ actionViewItems.ts:170
(anonymous) @ actionViewItems.ts:150
log.ts:404   ERR Untrusted: Signature: Untrusted
    at Pn.download (/home/zalent/.vscode-server-insiders/bin/0615c4f98b07b51d3be6a357e22afec119490c5a/out/vs/server/node/server.main.js:113:1922)
    at async U.h (/home/zalent/.vscode-server-insiders/bin/0615c4f98b07b51d3be6a357e22afec119490c5a/out/vs/server/node/server.main.js:149:90589)
```

**Comment by hakula139** [comment]
Hi there, I have exactly the same issue. How did you fix it?

**Comment by tomaxsas** [comment]
it just worked after a while. i assume bug on my side, cause it was freshly installed system.
