### ISSUE TITLE
Timeout: click ' .monaco-editor[data-uri$="settings.json"] .view-lines > .view-line:nth-child(1)'

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#173077]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=201861
Changes: https://github.com/Microsoft/vscode/compare/b8968e9...9b8548e

```
  1) VSCode Smoke Tests (Electron)
       Language Features
         verifies settings (css):
     Error: Timeout: click ' .monaco-editor[data-uri$="settings.json"] .view-lines > .view-line:nth-child(1)' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:269:11)
      at Code.waitAndClick (/__w/1/s/test/automation/src/code.ts:210:3)
      at Editor.waitForEditorFocus (/__w/1/s/test/automation/src/editor.ts:83:3)
      at SettingsEditor.openUserSettingsFile (/__w/1/s/test/automation/src/settings.ts:54:3)
      at SettingsEditor.addUserSetting (/__w/1/s/test/automation/src/settings.ts:22:3)
      at Context.<anonymous> (src/areas/languages/languages.test.ts:48:4)

```

**Comment by aeschli** [comment]
Looks like this was a one-off. Next builds went through. Closing.
