### ISSUE TITLE
Can't open ipynb file in a Codespace even with Jupyter installed

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#173098]
![image](https://user-images.githubusercontent.com/8599/216223236-4252045e-a977-41e8-854e-09319e934977.png)

```
  ERR Error: Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed and enabled.
    at jr.setInput (workbench.web.main.js:1703:72646)
    at async o.M (workbench.web.main.js:2320:23027)
    at async o.D (workbench.web.main.js:2320:21622)
    at async o.openEditor (workbench.web.main.js:2320:20488)
    at async workbench.web.main.js:2502:13441
    at async workbench.web.main.js:2552:63788
```

Before that I uninstalled Polyglot Notebooks, as it required me to install .NET (how on a Codespace?)

Version: 1.75.0-insider
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70
Embedder: codespaces

**Comment by LiyanJin** [comment]
Hi guys, have you find the solution?   I have met the same problem. Thanks for the answer.

**Comment by Husseinghosn** [comment]
anyone solve this problem yet?
