### ISSUE TITLE
"Error: Corrupt zip" issue stopping extensions for installing. Persists after reinstall and wiping all cache.

### ISSUE THREAD

**Issue by GlobalMin** [microsoft/vscode#173187]
**System**: Windows 10
**Computer**: HP EliteBook 850 G7 Notebook PC
**VSCode** version: 1.74.3
**Extension that demonstrates issue**: ms-python.python-2022.20.2

**The behavior I need to fix:**
When I tried to install the Python extension from the GUI I get an error and this log output.
```
[2023-02-02 13:57:46.876] [renderer1] [error] ["Error: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found","at vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:102492","at Array.reduce (<anonymous>)","at a (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:102478)","at j.joinAllSettled (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:92540)","at async j.installExtension (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:89742)","at async j.installFromGallery (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:85461)"]
[2023-02-02 13:57:46.879] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found: Error: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found
at vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:102492
at Array.reduce (<anonymous>)
at a (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:102478)
at j.joinAllSettled (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:92540)
at async j.installExtension (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:89742)
at async j.installFromGallery (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:86:85461)
```
**What I've tried**
I've searched around for any help on this issue and I found a number of similar problems where most fixes don't seem to do anything. I have reinstalled VSCode, tried VSCode Insiders, an older verson, and finally followed [this existing issue](https://github.com/microsoft/vscode/issues/84869) and the advice the user was given. Nothing seems to change the error unfortunately.

So I'm at a point where I think there is clearly a persistent source to this that isn't affected by reinstalls and wiping all VSCosde related folders. It might be connected to electron or some other language that is brought into VSCode? I just don't know how to proceed or what to try. My workflow and ability to code is now completely hindered.

**Comment by sandy081** [comment]
Can you please try use different user-data-dir and try if it works? You can do this from CLI like following

`code --user-data-dir <different-dir-path>`

**Comment by GlobalMin** [comment]
Unfortunately that didn't work. Log below after running that command and trying to install the Python extension.
```

2023-02-07 07:49:49.283 [error] SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at y.$getPassword (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1566:45049)
2023-02-07 07:49:49.951 [error] SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at y.$getPassword (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1566:45049)
2023-02-07 07:49:50.978 [info] [perf] Render performance baseline is 56ms
2023-02-07 07:50:38.325 [error] Error: UnhandledException,UnhandledException,Corrupt ZIP: end of central directory record signature not found,UnhandledException,Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found
    at vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89578
    at Array.reduce (<anonymous>)
    at E (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89564)
    at ne.D (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:80916)
    at async ne.z (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:78417)
    at async ne.installFromGallery (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:74855)
2023-02-07 07:50:38.359 [error] UnhandledException,UnhandledException,Corrupt ZIP: end of central directory record signature not found,UnhandledException,Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found: Error: UnhandledException,UnhandledException,Corrupt ZIP: end of central directory record signature not found,UnhandledException,Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found
    at vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89578
    at Array.reduce (<anonymous>)
    at E (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:89564)
    at ne.D (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:80916)
    at async ne.z (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:78417)
    at async ne.installFromGallery (vscode-file://vscode-app/c:/Users/jastillw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:74855)
```

For what it's worth, I'm on a work laptop and I wonder if my PATH env variable is messed up after so many reinstalls? Another detail that might help is I have Python 3.9/3.10 installed but I don't think VSCode is taking the path I'm giving it for the Python interpreter.

`   "python.defaultInterpreterPath": "C:\\Program Files\\\Python39\\python.exe",`

**Comment by sandy081** [comment]
/duplicate

> UnhandledException,UnhandledException,Corrupt ZIP: end of central directory record signature not found,UnhandledException
