### ISSUE TITLE
Notebook Editor  Active/Visible Editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173125]
```
1 failing
  1) Notebook Editor
       Active/Visible Editor:
     Error: Unexpected type
      at assertType (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/base/common/types.js:67:19)
      at SimpleNotebookEditorModel.load (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/contrib/notebook/common/notebookEditorModel.js:121:35)
      at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async NotebookModelReferenceCollection.createReferencedObject (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.js:58:28)
      at async NotebookModelResolverServiceImpl.resolve (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.js:175:31)
      at async MainThreadNotebookDocuments.$tryOpenNotebook (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/api/browser/mainThreadNotebookDocuments.js:117:25)
```

**Comment by bpasero** [comment]
Skipping the suite in https://github.com/microsoft/vscode/pull/173124

**Comment by rebornix** [comment]
Merging into https://github.com/microsoft/vscode/issues/139078
