### ISSUE TITLE
OverlayWebview is disposed

### ISSUE THREAD

**Issue by samdenty** [microsoft/vscode#173291]
Steps to Reproduce:

1. Open a file (not an image)
2. Quickly open an image and press <kbd>COMMAND-BACKSPACE</kbd> to delete it
3. You get the error `OverlayWebview is disposed`

This error only seems to happen if the webview doesn't load quickly enough.

https://user-images.githubusercontent.com/13242392/216598874-1480e1ed-9e32-4313-8722-ff577b684964.mp4

**Comment by mjbvz** [comment]
Error stack:

```
  ERR Error: OverlayWebview is disposed
    at OverlayWebview._show (overlayWebview.ts:185:10)
    at OverlayWebview.claim (overlayWebview.ts:116:8)
    at WebviewEditor.claimWebview (webviewEditor.ts:179:17)
    at WebviewEditor.setInput (webviewEditor.ts:170:10)
    at async EditorPanes.doSetInput (editorPanes.ts:422:4)
    at async EditorPanes.doOpenEditor (editorPanes.ts:252:34)
    at async EditorPanes.openEditor (editorPanes.ts:129:11)
    at async editorGroupView.ts:1075:49
    at async explorerView.ts:486:6
```

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/234956824-bccf0178-2dc7-4c61-808b-dafc8fcd1605.png)

I had to do this super super fast on web and repro'd maybe 1/5 times... but if I'm fast enough, the Explorer no longer is responsive. I click on files and they do not open in the editor.

**Comment by mjbvz** [comment]
@TylerLeonhardt If you test this again, can you also make sure to disable that chrome extension? It's the source of the `MutationObserver` errors
