### ISSUE TITLE
docker compose build fails after vs code latest update

### ISSUE THREAD

**Issue by nick-rbzk** [microsoft/vscode#173311]
Type: <b>Bug</b>

Steps to  reproduce:
1. Create Dev Container
2. Chose Python and PostGres
3. Pres Launch or Debug
Failure code
docker compose failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No
Connection to 'Dev Container' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 2448)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|30.73GB (23.55GB free)|
|Process Argv|. --crash-reporter-id a8764413-b917-4364-b2f0-79d7302c6eef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

Connection to 'Dev Container' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by nick-rbzk** [comment]
This is a full error code that takes place in the vs code when i try to run it in a devcontainer:

```
 => preparing layers for inline cache                                      0.0s
failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
[2071 ms] unexpected EOF => preparing layers for inline cache                                      0.0s
failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
[2071 ms] unexpected EOF

[2071 ms] Docker events terminated (code: 1, signal: null).
[2275 ms] Error: Command failed: docker compose --project-name back_devcontainer -f /home/g1tomer/Music/only-data/back/.devcontainer/docker-compose.yml -f /home/g1tomer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1675456260142.yml build
[2276 ms]     at gF (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1872:412)
[2276 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2276 ms]     at async rie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1872:2381)
[2277 ms]     at async tie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1854:2396)
[2277 ms]     at async Fie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:2266)
[2277 ms]     at async Vf (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2277 ms]     at async eoe (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2277 ms]     at async Qse (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2281 ms] Exit code 1
[2286 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/g1tomer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-a5f3a6a0-3551-436d-a045-26215f6d10fd1675456257666 --workspace-folder /home/g1tomer/Music/only-data/back --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/g1tomer/Music/only-data/back --id-label devcontainer.config_file=/home/g1tomer/Music/only-data/back/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/g1tomer/Music/only-data/back/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2286 ms] Exit code 1

[2071 ms] Docker events terminated (code: 1, signal: null).
[2275 ms] Error: Command failed: docker compose --project-name back_devcontainer -f /home/g1tomer/Music/only-data/back/.devcontainer/docker-compose.yml -f /home/g1tomer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1675456260142.yml build
[2276 ms]     at gF (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1872:412)
[2276 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2276 ms]     at async rie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1872:2381)
[2277 ms]     at async tie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1854:2396)
[2277 ms]     at async Fie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:2266)
[2277 ms]     at async Vf (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2277 ms]     at async eoe (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2277 ms]     at async Qse (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2281 ms] Exit code 1
[2286 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/g1tomer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-a5f3a6a0-3551-436d-a045-26215f6d10fd1675456257666 --workspace-folder /home/g1tomer/Music/only-data/back --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/g1tomer/Music/only-data/back --id-label devcontainer.config_file=/home/g1tomer/Music/only-data/back/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/g1tomer/Music/only-data/back/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2286 ms] Exit code 1
```

**Comment by nick-rbzk** [comment]
Here is a full error code extract from vs code when i try to run it in a devcontainer



```
 => CACHED [dev_container_auto_added_stage_label 4/4] RUN pip3 --disable-  0.0s
 => preparing layers for inline cache                                      0.0s
failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
[2071 ms] unexpected EOF

[2071 ms] Docker events terminated (code: 1, signal: null).
[2275 ms] Error: Command failed: docker compose --project-name back_devcontainer -f /home/g1tomer/Music/only-data/back/.devcontainer/docker-compose.yml -f /home/g1tomer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1675456260142.yml build
[2276 ms]     at gF (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1872:412)
[2276 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2276 ms]     at async rie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1872:2381)
[2277 ms]     at async tie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1854:2396)
[2277 ms]     at async Fie (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:2266)
[2277 ms]     at async Vf (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2277 ms]     at async eoe (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2277 ms]     at async Qse (/home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2281 ms] Exit code 1
[2286 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/g1tomer/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/g1tomer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-a5f3a6a0-3551-436d-a045-26215f6d10fd1675456257666 --workspace-folder /home/g1tomer/Music/only-data/back --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/g1tomer/Music/only-data/back --id-label devcontainer.config_file=/home/g1tomer/Music/only-data/back/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/g1tomer/Music/only-data/back/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2286 ms] Exit code 1
```

**Comment by tipy01** [comment]
I got the same error without using compose on a Node.js project:

```
[269 ms] Dev Containers 0.277.0 in VS Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164).
[268 ms] Start: Resolving Remote
[276 ms] Setting up container for folder or workspace: /home/XXX/devl/web/project-xxx
[281 ms] Start: Check Docker is running
[281 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[344 ms] Server API version: 1.42
[345 ms] Start: Run: docker volume ls -q
[419 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/XXX/devl/web/project-xxx --filter label=vsch.quality=stable
[477 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/XXX/devl/web/project-xxx --filter label=devcontainer.config_file=/home/XXX/devl/web/project-xxx/.devcontainer/devcontainer.json
[535 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/XXX/devl/web/project-xxx
[592 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/XXX/devl/web/project-xxx
[652 ms] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/XXX/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-9f77f74d-3dc9-4710-ad52-d92afe8c073b1675691967010 --workspace-folder /home/XXX/devl/web/project-xxx --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/XXX/devl/web/project-xxx --id-label devcontainer.config_file=/home/XXX/devl/web/project-xxx/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/XXX/devl/web/project-xxx/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[877 ms] (node:113895) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[877 ms] (Use `code --trace-deprecation ...` to show where the warning was created)
[878 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.15.0-58-generic x64.
[878 ms] Start: Run: docker buildx version
[958 ms] github.com/docker/buildx v0.10.2 00ed17d
[958 ms] 
[958 ms] Start: Resolving Remote
[963 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/XXX/devl/web/project-xxx --filter label=devcontainer.config_file=/home/XXX/devl/web/project-xxx/.devcontainer/devcontainer.json
[1021 ms] Start: Run: docker inspect --type image node:19.6-bullseye-slim
[3042 ms] local container features stored at: /home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/node_modules/vscode-dev-containers/container-features
[3043 ms] Start: Run: tar --no-same-owner -x -f -
[3066 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-XXX/container-features/0.29.0-1675691970507/Dockerfile-with-features -t vsc-project-xxx-d1adeb3cf1c783ef8092b6a7251b1d8a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/XXX/devl/web/project-xxx
[+] Building 1.2s (19/20)                                                       
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.68kB                                     0.0s
 => [internal] load metadata for docker.io/library/node:19.6-bullseye-sli  1.1s
 => [internal] load build context                                          0.0s
 => => transferring context: 3.89kB                                        0.0s
 => [dev_container_auto_added_stage_label  1/15] FROM docker.io/library/n  0.0s
 => CACHED [dev_container_auto_added_stage_label  2/15] RUN apt-get updat  0.0s
 => CACHED [dev_container_auto_added_stage_label  3/15] RUN pip3 install   0.0s
 => CACHED [dev_container_auto_added_stage_label  4/15] RUN apt-get updat  0.0s
 => CACHED [dev_container_auto_added_stage_label  5/15] RUN echo node ALL  0.0s
 => CACHED [dev_container_auto_added_stage_label  6/15] WORKDIR /backend_  0.0s
 => CACHED [dev_container_auto_added_stage_label  7/15] COPY ./docker/sep  0.0s
 => CACHED [dev_container_auto_added_stage_label  8/15] COPY ./docker/sep  0.0s
 => CACHED [dev_container_auto_added_stage_label  9/15] COPY ./docker/sep  0.0s
 => CACHED [dev_container_auto_added_stage_label 10/15] COPY ./docker/sep  0.0s
 => CACHED [dev_container_auto_added_stage_label 11/15] COPY ./docker/sep  0.0s
 => CACHED [dev_container_auto_added_stage_label 12/15] COPY ./docker/sep  0.0s
 => CACHED [dev_container_auto_added_stage_label 13/15] COPY ./docker/sep  0.0s
 => CACHED [dev_container_auto_added_stage_label 14/15] WORKDIR /etc       0.0s
 => CACHED [dev_container_auto_added_stage_label 15/15] COPY ./.devcontai  0.0s
 => preparing layers for inline cache                                      0.1s
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
[4788 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-XXX/container-features/0.29.0-1675691970507/Dockerfile-with-features -t vsc-project-xxx-d1adeb3cf1c783ef8092b6a7251b1d8a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/XXX/devl/web/project-xxx
[4788 ms]     at pie (/home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js:1916:1698)
[4789 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[4789 ms]     at async vF (/home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js:1915:1972)
[4790 ms]     at async P7 (/home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js:1915:901)
[4790 ms]     at async Fie (/home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[4790 ms]     at async Vf (/home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[4791 ms]     at async eoe (/home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[4791 ms]     at async Qse (/home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[4806 ms] Exit code 1
[4819 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/XXX/.vscode/extensions/ms-vscode-remote.remote-containers-0.277.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/XXX/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-9f77f74d-3dc9-4710-ad52-d92afe8c073b1675691967010 --workspace-folder /home/XXX/devl/web/project-xxx --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/XXX/devl/web/project-xxx --id-label devcontainer.config_file=/home/XXX/devl/web/project-xxx/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/XXX/devl/web/project-xxx/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[4819 ms] Exit code 1
```

<details>
<summary>System Info</summary>

CPUs | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3726)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 1, 2, 2
Memory (System) | 15.44GB (5.90GB free)
Process Argv | --crash-reporter-id 09cedaff-7201-4ba3-b14d-68acff032c2f
Screen Reader | no
VM | 0%

</details>

Extensions: 

Name: Dev Containers
Id: ms-vscode-remote.remote-containers
Description: Open any folder or repository inside a Docker container and take advantage of Visual Studio Code's full feature set.
Version: 0.277.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

<details>
<summary>A/B Experiments</summary>
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982

</details>

**Comment by tipy01** [comment]
I upgraded on Friday along with VS Code, I have got:

```bash
grep " install " /var/log/dpkg.log
2023-02-03 17:59:47 install libllvm15:amd64 <none> 1:15.0.6-3~ubuntu0.22.04.2
2023-02-03 17:59:55 install docker-buildx-plugin:amd64 <none> 0.10.2-1~ubuntu.20.04~focal
2023-02-03 17:59:59 install docker-compose-plugin:amd64 <none> 2.15.1-1~ubuntu.20.04~focal
```

I removed this new docker-buildx-plugin deb package  and now it works well again. 

Maybe it is somehow linked with this issue: https://github.com/docker/buildx/issues/1598

**Comment by nick-rbzk** [comment]
Did you use apt to uninstall `docker-buildx-plugin` ? If not, how did you uninstall it?

**Comment by nick-rbzk** [comment]
Worked for me as well!!! 
All i did was, 
`sudo apt remove docker-buildx-plugin`
Thank you!!!!

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/7958. Another workaround that was suggested is to set `"BUILDKIT_INLINE_CACHE": "0"` (see https://github.com/microsoft/vscode-remote-release/issues/7958#issuecomment-1416777679, applied in your docker-compose.yml or devcontainer.json when not using Compose).
