### ISSUE TITLE
NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#173496]
```javascript
Error: NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
at h.getNotebookDocument in src/vs/workbench/api/common/extHostNotebook.ts:130:10
at C.$cancelCells in src/vs/workbench/api/common/extHostNotebookKernels.ts:387:42
at l.N in src/vs/workbench/services/extensions/common/rpcProtocol.ts:455:17
at l.M in src/vs/workbench/services/extensions/common/rpcProtocol.ts:440:32
at l.H in src/vs/workbench/services/extensions/common/rpcProtocol.ts:370:19
at l.G in src/vs/workbench/services/extensions/common/rpcProtocol.ts:296:10
at <anonymous> in src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42
at f.invoke in src/vs/base/common/event.ts:701:17
at g.deliver in src/vs/base/common/event.ts:908:22
at d.fire in src/vs/base/common/event.ts:869:24
at p.fire in src/vs/base/parts/ipc/common/ipc.net.ts:671:19
at <anonymous> in src/vs/workbench/api/node/extensionHostProcess.ts:247:22
at f.invoke in src/vs/base/common/event.ts:701:17
at g.deliver in src/vs/base/common/event.ts:908:22
at d.fire in src/vs/base/common/event.ts:869:24
at p.fire in src/vs/base/parts/ipc/common/ipc.net.ts:671:19
at MessagePortMain.<anonymous> in src/vs/workbench/api/node/extensionHostProcess.ts:126:41
at MessagePortMain.emit (node:events:526:28)
at MessagePortMain._internalPort.emit (node:<REDACTED: user-file-path>:5:364)
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=e2816fe719a4026ffa1ee0189dc89bdfdbafb164&bH=a1bb42bd-26af-bbc4-4ccf-90c0b0c47e1e)

**Comment by DonJayamanne** [comment]
@charlesAttend noticed you upvoted this issue, wanted to check if you were running into this at your end?

**Comment by CharlesAttend** [comment]
Hi @DonJayamanne, thank for contributing to vscode 
I upvoted this a long time ago, I don't even remember of this bug. I may have been patch quickly.
I don't have more debug information for you sorry.

**Comment by DonJayamanne** [comment]
Closing this issue for now, possible these have been resolved since.
