### ISSUE TITLE
Jupyter Notebook Code Cell Shrunk to 1 Line or Expanded to Many Lines

### ISSUE THREAD

**Issue by bash-j** [microsoft/vscode#173604]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I've been having this issue for a while now. It's intermittent. When scrolling a notebook, the view will shrink the code cell to 1 and a bit lines with a large gap of nothing between the next cell. It also sometimes expands the code cell past the last line over the top of the next cells. Usually scrolling up and down a bit clears the issue. But today I'm having a problem with a notebook where it keeps reappearing.
![cell bug 1](https://user-images.githubusercontent.com/3195567/216864480-e23cf96f-31f8-4048-9b2b-7ef0938f5e33.PNG)
![cell bug 2](https://user-images.githubusercontent.com/3195567/216864484-d36bb9df-6ab4-4afa-9712-53463989698b.PNG)

### VS Code Version

Version: 1.75.0 (user setup) Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:23:45.584Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2023.1.2000312134

### Jupyter logs

```shell
Visual Studio Code (1.75.0, undefined, desktop)
Jupyter Extension Version: 2023.1.2000312134.
Python Extension Version: 2023.2.0.
Workspace folder c:\Users\__removed__\
info 12:17:16.355: LSP Notebooks experiment is disabled -- not using Pylance
info 12:17:21.878: Find preferred kernel for c:\Users\__removed__\
Impact Cause.ipynb with metadata {"kernelspec":{"display_name":"base","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.15"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"72004fb22f205acd462c660f50c4715047339b1f1571f06f31dad607eb6d2809"}}} & preferred interpreter c:\Users\__removed__\Anaconda3\python.exe
info 12:17:21.947: Find preferred kernel for c:\Users\__removed__\.ipynb with metadata {"kernelspec":{"display_name":"base","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.15"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"72004fb22f205acd462c660f50c4715047339b1f1571f06f31dad607eb6d2809"}}} & preferred interpreter c:\Users\__removed__\Anaconda3\python.exe
info 12:17:21.948: Preferred kernel .jvsc74a57bd072004fb22f205acd462c660f50c4715047339b1f1571f06f31dad607eb6d2809.c:\Users\__removed__\Anaconda3\python.exe.c:\Users\__removed__\Anaconda3\python.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], true, false)
info 12:17:21.948: PreferredConnection: .jvsc74a57bd072004fb22f205acd462c660f50c4715047339b1f1571f06f31dad607eb6d2809.c:\Users\__removed__\Anaconda3\python.exe.c:\Users\__removed__\Anaconda3\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\__removed__\.ipynb
info 12:17:22.432: Registering dummy command feature
info 12:17:24.006: Process Execution: > ~\Anaconda3\python.exe -m pip list
> ~\Anaconda3\python.exe -m pip list
info 12:17:28.156: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd072004fb22f205acd462c660f50c4715047339b1f1571f06f31dad607eb6d2809.c:\Users\__removed__\Anaconda3\python.exe.c:\Users\__removed__\Anaconda3\python.exe.-m#ipykernel_launcher (Python Path: c:\Users\__removed__\Anaconda3, EnvType: Conda, EnvName: 'base', Version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:39:05) [MSC v.1929 64 bit (AMD64)]) for 'c:\Users\__removed__\.ipynb' (disableUI=false)
info 12:17:28.171: Process Execution: > ~\Anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\Anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 12:17:28.216: Process Execution: > ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.1.2000312134\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 8908
> ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.1.2000312134\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 8908
info 12:17:28.216: Process Execution: cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2023.1.2000312134\pythonFiles\vscode_datascience_helpers
cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2023.1.2000312134\pythonFiles\vscode_datascience_helpers
info 12:17:28.366: Process Execution: > ~\Anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f3eeb18d-c403-4fd7-a400-83896247d121" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\__removed__\AppData\Roaming\jupyter\runtime\kernel-v2-8908SgAoZTmZLzsh.json
> ~\Anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f3eeb18d-c403-4fd7-a400-83896247d121" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\__removed__\AppData\Roaming\jupyter\runtime\kernel-v2-8908SgAoZTmZLzsh.json
info 12:17:28.366: Process Execution: cwd: ~\__removed__
cwd: ~\__removed__
info 12:17:28.501: ipykernel version & path 6.21.0, ~\Anaconda3\lib\site-packages\ipykernel\__init__.py for c:\Users\__removed__\Anaconda3\python.exe
info 12:17:29.873: Started Kernel base (Python 3.9.15) (pid: 20892)
info 12:17:29.923: Process Execution: > ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.1.2000312134\pythonFiles\printJupyterDataDir.py
> ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.1.2000312134\pythonFiles\printJupyterDataDir.py
warn 12:17:30.024: Got a non-existent Jupyer Data Dir file:///c%3A/Users/__removed__/AppData/Roaming/Python/share/jupyter
```

### Coding Language and Runtime Version

Python 3.9.15

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Local

**Comment by hbsmith** [comment]
Also been having this problem for a few months. Happy to provide my settings/info if that's useful.

**Comment by rebornix** [comment]
@bash-j when this happens, can you help run command "Toggle Developer Tools" and share if there is any error in the dev tools?

**Comment by bash-j** [comment]
@rebornix 

```workbench.desktop.main.js:627   ERR Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, terminalDataWriteEvent
product.json (WINS): inlineCompletionsAdditions
workbench.desktop.main.js:627   ERR Extension 'ms-toolsai.datawrangler CANNOT USE these API proposals 'notebookDeprecated'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
workbench.desktop.main.js:627  INFO [perf] Render performance baseline is 101ms
notebookWebviewPreloads.js:3 '_allOutputItems' is proposed API. DO NOT ship an extension that depends on it!
get _allOutputItems @ notebookWebviewPreloads.js:3
workbench.desktop.main.js:627   ERR [Extension Host] 2023-08-22T06:46:00.905Z [ERROR] [RefactorsProvider] RefactorsProvider: getDocumentableNodeIfOnIdentifierWithTelemetry failed: (TypeError) Cannot read properties of null (reading 'children')
workbench.desktop.main.js:129 [Extension Host] 2023-08-22T06:46:00.905Z [ERROR] [RefactorsProvider] RefactorsProvider: getDocumentableNodeIfOnIdentifierWithTelemetry failed: (TypeError) Cannot read properties of null (reading 'children')
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:627   ERR [Extension Host] 2023-08-22T06:46:00.908Z [ERROR] [RefactorsProvider] RefactorsProvider: getDocumentableNodeIfOnIdentifierWithTelemetry failed: (TypeError) Cannot read properties of null (reading 'children')
workbench.desktop.main.js:129 [Extension Host] 2023-08-22T06:46:00.908Z [ERROR] [RefactorsProvider] RefactorsProvider: getDocumentableNodeIfOnIdentifierWithTelemetry failed: (TypeError) Cannot read properties of null (reading 'children')
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:129 [Extension Host] Starting WebSocket: RAW/api/kernels/fe4fd498-cec5-49c6-baf1-0336c3b80af6
workbench.desktop.main.js:1628 Extension Host
workbench.desktop.main.js:1628 Starting WebSocket: RAW/api/kernels/fe4fd498-cec5-49c6-baf1-0336c3b80af6

workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/c:/Users/_/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
workbench.desktop.main.js:129 [Extension Host] Embeddings for settingEmbeddings calculated in 2649ms
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/_/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/preload.js.map: Connection error: net::ERR_CONNECTION_CLOSED
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/_/.vscode/extensions/ms-toolsai.jupyter-2023.7.1002162226-win32-x64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_CONNECTION_CLOSED
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/_/.vscode/extensions/ms-toolsai.jupyter-2023.7.1002162226-win32-x64/out/webviews/webview-side/ipywidgetsRenderer/ipywidgetsRenderer.js.map: Connection error: net::ERR_CONNECTION_CLOSED
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/_/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/builtinRendererHooks.js.map: Connection error: net::ERR_CONNECTION_CLOSED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/6c3e3dba23e8fadc360aed75ce363ba185c49794/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```

**Comment by bash-j** [comment]
If I rerun the cell which causes the blank cell proceeding it to expand I consistently get this error:

```ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/c:/Users/_/AppData/Local/Programs/Microsoft…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235```

**Comment by hbsmith** [comment]
Here's what I get in the developer tools when I encounter the same annoying rendering issue:
```
workbench.desktop.main.js:129 [Extension Host] Starting WebSocket: RAW/api/kernels/e11a2d26-f385-4623-8697-14eafccbbe0c
14:12:40.932 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:14:06.691 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:14:09.654 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:14:32.651 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:10.438 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:13.945 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:15.377 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:18.561 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:20.197 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:22.226 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:23.886 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:15:25.578 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:16:09.803 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:16:11.037 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:16:13.742 workbench.desktop.main.js:627   ERR Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.: Error: Failed to execute 'postMessage' on 'Worker': (E,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:594:47235
14:16:24.075 DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002banarres.vscode-resource.vscode-cdn.net/Users/anarres/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/preload.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
14:16:24.075 DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002banarres.vscode-resource.vscode-cdn.net/Users/anarres/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-darwin-x64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
14:16:24.086 DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002banarres.vscode-resource.vscode-cdn.net/Users/anarres/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/markdown.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
14:16:24.087 DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002banarres.vscode-resource.vscode-cdn.net/Users/anarres/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/builtinRendererHooks.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
14:16:25.814 DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/6c3e3dba23e8fadc360aed75ce363ba185c49794/node_modules/@vscode/vscode-languagedetection/dist/lib/index.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
14:16:54.097 DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/6c3e3dba23e8fadc360aed75ce363ba185c49794/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```

**Comment by hbsmith** [comment]
@rebornix Anymore updates on plans for this to be addressed? Or if the devs can repro? This is a significant bug that prevents vscode from being a reliable jupyter replacement.

**Comment by bash-j** [comment]
Hello, any progress on this issue? It's not intermittent, it happens constantly. Would be amazing to fix this issue after such a long time of having to deal with this very frustrating problem.

![image](https://github.com/microsoft/vscode/assets/3195567/e8dea689-7343-4750-8fbb-d55acab3b99d)

https://github.com/microsoft/vscode/issues/194841

https://github.com/microsoft/vscode-jupyter/issues/13843

![image](https://github.com/microsoft/vscode/assets/3195567/6c1c0a29-c8e0-4b67-a6e1-795f5abe7c20)

![image](https://github.com/microsoft/vscode/assets/3195567/b26d35fd-a0a3-4d59-81a4-4f98be1ca7bf)

**Comment by Yoyokrazy** [comment]
/duplicate [#194841](https://github.com/microsoft/vscode/issues/194841)

**Comment by hbsmith** [comment]
Why was the newer issue kept open, while the older one was closed, if they are duplicates of each other?
