### ISSUE TITLE
Git: Open Repository command stopped working

### ISSUE THREAD

**Issue by axtschmied** [microsoft/vscode#173789]
Repositories can not be opened manually using the open repository command. I only experience this since updating to the latest VSCode release. I have not checked insider releases.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. Try to open a repository with Ctrl+Shift+P --> "Git: Open Repository"
2. The repository is not added to the list in the Source Control Panel.

**Comment by axtschmied** [comment]
Additional info: I closed and reopened the workspace I had open, and it is working now. But before that even restarting VSCode (without closing the workspace) did not solve the issue. I have no idea why this could have happened.

**Comment by louga31** [comment]
I just got the error too, here is the error stacktrace:
```2023-02-10 21:37:32.883 [info] ExtensionService#_doActivateExtension ms-vscode.remote-repositories, startup: false, activationEvent: 'onCommand:remoteHub.continueOn.openRepository'
2023-02-10 21:37:32.951 [error] Activating extension ms-vscode.remote-repositories failed due to an error:
2023-02-10 21:37:32.951 [error] TypeError: this.a.logEvent is not a function
    at E.i (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:38636)
    at E.logUsage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:38711)
    at S.internalSendTelemetryEvent (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:25:957)
    at S.sendTelemetryEvent (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:25:1030)
    at Object.publicLog2 (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:255:3499)
    at registerNavigationServiceProviders (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:405:9546)
    at activate (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:405:7606)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at v.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:7006)
    at v.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6969)
    at v.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6426)
2023-02-10 21:37:32.958 [error] TypeError: this.a.logEvent is not a function
    at E.i (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:38636)
    at E.logUsage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:38711)
    at S.internalSendTelemetryEvent (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:25:957)
    at S.sendTelemetryEvent (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:25:1030)
    at Object.publicLog2 (c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:255:3499)
    at c:\Users\louga31\.vscode\extensions\ms-vscode.remote-repositories-0.28.0\dist\extension.js:276:25125
    at s.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:107622)
    at s.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:108311)
    at u.N (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:11208)
    at u.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:10926)
    at u.H (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:10019)
    at u.G (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:9000)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:7788
    at d.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at w.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2029)
    at g.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1667)
    at h.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14314)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:15804
    at d.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at w.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2029)
    at g.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1667)
    at h.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14314)
    at c.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:17324)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:15795
    at d.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at w.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2029)
    at g.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1667)
    at g.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:12045)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:11332
    at Socket.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:19792)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) remoteHub.continueOn.openRepository {"value":"ms-vscode.remote-repositories","c":"ms-vscode.remote-repositories"}```
