### ISSUE TITLE
Exception in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173838]
Steps:
* fresh user data dir
* remove all views from explorer except for files
* move it to the second sidebar
* move it to the panel
* 🐛 notice how the second sidebar still shows the explorer icon
* now move the files view back to side bar
* now move the files view into the second sidebar

```
bootstrap-window.js:264 TypeError: Cannot read properties of undefined (reading 'element')
    at getOverlayBounds (viewPaneContainer.ts:423:55)
    at Object.onDragEnter (viewPaneContainer.ts:444:14)
    at Object.onDragEnter (dnd.ts:509:17)
    at HTMLDivElement.<anonymous> (dom.ts:1700:19)
```

Video:

![Recording 2023-02-08 at 17 49 48](https://user-images.githubusercontent.com/900690/217596867-7ad78860-6327-4fa8-bebf-fe8e1e4c8525.gif)

**Comment by lramos15** [comment]
![Recording 2023-02-09 at 09 34 49](https://user-images.githubusercontent.com/4544166/217877879-9b63ec1a-8b39-41e0-a34e-577f85d02cd9.gif)
Not sure why the icon stays, but this is reproducible with any view. Here's search for example

**Comment by benibenj** [comment]
Reverting #198526 as it caused #199537

**Comment by bpasero** [comment]
This still reproduces but I cannot move the explorer next to the terminal anymore (maybe this is another issue?). It reproduces when doing this with the search view instead that can still be dropped next to the terminal.
