### ISSUE TITLE
Decoration has no range: Error: Decoration has no range

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#173958]
```
Decoration has no range: Error: Decoration has no range
    at SynchronizedInlineCompletionsCache.updateRanges (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsModel.js:545:53)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsModel.js:194:35
    at Listener.invoke (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:523:27)
    at EventDeliveryQueue.deliver (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:697:38)
    at Emitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:662:37)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/browser/widget/codeEditorWidget.js:1196:57
    at Listener.invoke (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:523:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:697:38)
    at Emitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:662:37)
    at ViewModelEventDispatcher._emitOutgoingEvents (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/viewModelEventDispatcher.js:46:31)
    at ViewModelEventDispatcher.endEmitViewEvents (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/viewModelEventDispatcher.js:85:18)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/viewModel/viewModelImpl.js:279:43
    at vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/model/textModel.js:142:90
    at Listener.invoke (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:523:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:697:38)
    at Emitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/base/common/event.js:662:37)
    at DidChangeContentEmitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/model/textModel.js:1871:31)
    at TextModel._emitContentChangedEvent (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/model/textModel.js:260:32)
    at TextModel._setValueFromTextBuffer (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/model/textModel.js:303:18)
    at TextModel.setValue (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/common/model/textModel.js:268:18)
    at InputModeWidget.getInput (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/contrib/inputMode/browser/inputModeWidget.js:173:30)
    at InputModelZoneWidget.getInput (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/contrib/inputMode/browser/inputModeWidget.js:309:38)
    at InputModeController.run (vscode-file://vscode-app/Users/jrieken/Code/vscode-distro/out/vs/editor/contrib/inputMode/browser/inputModeWidget.js:411:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by hediet** [comment]
Fixed by @jrieken
