### ISSUE TITLE
[perf] readFontInfo

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#174041]
re https://github.com/microsoft/vscode/issues/170954

* stable 1.75.0
* checking the `monacoworkbench/unresponsive.sample`-event

<div style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><br><br>

Fn | Callers | dcount_VSCodeMachineId | avg_TotalTime
-- | -- | -- | --
b#workbench.desktop.main.js:551:51632 | b#workbench.desktop.main.js:551:51632<s#workbench.desktop.main.js:553:1244<(anonymous)#workbench.desktop.main.js:552:1343<invoke#workbench.desktop.main.js:86:127<deliver#workbench.desktop.main.js:86:1967<fire#workbench.desktop.main.js:86:1551<ie#workbench.desktop.main.js:84:29612 | 23 | 2358.1142857142859
g#workbench.desktop.main.js:72:10326 | read#workbench.desktop.main.js:72:9415<D#workbench.desktop.main.js:72:10437<j#workbench.desktop.main.js:604:78182<readFontInfo#workbench.desktop.main.js:604:77254<w#workbench.desktop.main.js:609:59171<u#workbench.desktop.main.js:609:58384<t#workbench.desktop.main.js:609:58274<(anonymous)#workbench.desktop.main.js:609:58149<invoke#workbench.desktop.main.js:86:127<deliver#workbench.desktop.main.js:86:1967<fire#workbench.desktop.main.js:86:1551<clearAllFontInfos#workbench.desktop.main.js:604:76791<(anonymous)#workbench.desktop.main.js:1586:10820<invoke#workbench.desktop.main.js:86:127<deliver#workbench.desktop.main.js:86:1967<fire#workbench.desktop.main.js:86:1551<Z#workbench.desktop.main.js:553:791<t#workbench.desktop.main.js:553:1510<s#workbench.desktop.main.js:553:1251<(anonymous)#workbench.desktop.main.js:552:1339<invoke#workbench.desktop.main.js:86:127<deliver#workbench.desktop.main.js:86:1967<fire#workbench.desktop.main.js:86:1551<re#workbench.desktop.main.js:84:25779<(anonymous)<emit#sandbox_bundle:124:3395<onMessage#sandbox_bundle:49:656 | 22 | 2266.7195121951218

</div>

**Comment by jrieken** [comment]
Reading help 📖 

* The `Fn` column is the function that the profiler identified as slow (see `avg_TotalTime` for the avg durations and `dcount...` for the number of affected machines)
* The `Callers` column is the "heaviest" call-stack into that function, each calling function is separated by the `<` character (kusto escape gymnastics...)

**Comment by alexdima** [comment]
@jrieken I've added support for this format in https://github.com/alexdima/vscode-stack-beautifier

It's not perfect, but after some manual adjustment (adding "base") here are the stack traces for the two rows you wrote above:

## First row:
Deminified using https://github.com/alexdima/vscode-stack-beautifier

Error: Slow Stack
at b (workbench.desktop.main.js:551:51632)
at s (workbench.desktop.main.js:553:1244)
at (anonymous) (workbench.desktop.main.js:552:1343)
at invoke (workbench.desktop.main.js:86:127)
at deliver (workbench.desktop.main.js:86:1967)
at fire (workbench.desktop.main.js:86:1551)
at ie (workbench.desktop.main.js:84:29612)

Error:&nbsp;Slow&nbsp;Stack<br/>&nbsp;&nbsp;at&nbsp;`reader`&nbsp;([`./parts/ipc/common/ipc.ts:301:28`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/base/parts/ipc/common/ipc.ts#L301))<br/>&nbsp;&nbsp;at&nbsp;`message`&nbsp;([`./parts/ipc/common/ipc.ts:713:18`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/base/parts/ipc/common/ipc.ts#L713))<br/>&nbsp;&nbsp;at&nbsp;`msg`&nbsp;([`./parts/ipc/common/ipc.ts:549:50`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/base/parts/ipc/common/ipc.ts#L549))<br/>&nbsp;&nbsp;at&nbsp;`e`&nbsp;([`./common/event.ts:700:8`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/base/common/event.ts#L700))<br/>&nbsp;&nbsp;at&nbsp;[`./common/event.ts:904:1`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/base/common/event.ts#L904)<br/>&nbsp;&nbsp;at&nbsp;`event`&nbsp;([`./common/event.ts:852:6`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/base/common/event.ts#L852))<br/>&nbsp;&nbsp;at&nbsp;[`./common/event.ts:458:13`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/base/common/event.ts#L458)<br/>

## Second row

Error: Slow Stack
at read (workbench.desktop.main.js:72:9415)
at D (workbench.desktop.main.js:72:10437)
at j (workbench.desktop.main.js:604:78182)
at readFontInfo (workbench.desktop.main.js:604:77254)
at w (workbench.desktop.main.js:609:59171)
at u (workbench.desktop.main.js:609:58384)
at t (workbench.desktop.main.js:609:58274)
at workbench.desktop.main.js:609:58149
at invoke (workbench.desktop.main.js:86:127)
at deliver (workbench.desktop.main.js:86:1967)
at fire (workbench.desktop.main.js:86:1551)
at clearAllFontInfos (workbench.desktop.main.js:604:76791)
at workbench.desktop.main.js:1586:10820
at invoke (workbench.desktop.main.js:86:127)
at deliver (workbench.desktop.main.js:86:1967)
at fire (workbench.desktop.main.js:86:1551)
at Z (workbench.desktop.main.js:553:791)
at t (workbench.desktop.main.js:553:1510)
at s (workbench.desktop.main.js:553:1251)
at workbench.desktop.main.js:552:1339
at invoke (workbench.desktop.main.js:86:127)
at deliver (workbench.desktop.main.js:86:1967)
at fire (workbench.desktop.main.js:86:1551)
at re (workbench.desktop.main.js:84:25779)


Error:&nbsp;Slow&nbsp;Stack<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/config/charWidthReader.ts:50:8`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/charWidthReader.ts#L50)<br/>&nbsp;&nbsp;at&nbsp;`DomCharWidthReader`&nbsp;([`./editor/browser/config/charWidthReader.ts:141:20`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/charWidthReader.ts#L141))<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/config/fontMeasurements.ts:136:5`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/fontMeasurements.ts#L136)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/config/fontMeasurements.ts:56:8`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/fontMeasurements.ts#L56)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/config/editorConfiguration.ts:174:6`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/editorConfiguration.ts#L174)<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/config/editorConfiguration.ts:116:3`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/editorConfiguration.ts#L116)<br/>&nbsp;&nbsp;at&nbsp;`fontInfo`&nbsp;([`./editor/browser/config/editorConfiguration.ts:112:13`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/editorConfiguration.ts#L112))<br/>&nbsp;&nbsp;at&nbsp;[`./editor/browser/config/editorConfiguration.ts:106:99`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/browser/config/editorConfiguration.ts#L106)<br/>&nbsp;&nbsp;at&nbsp;`e`&nbsp;([`./base/common/event.ts:700:8`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L700))<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:904:1`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L904)<br/>&nbsp;&nbsp;at&nbsp;`event`&nbsp;([`./base/common/event.ts:852:6`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L852))<br/>&nbsp;&nbsp;at&nbsp;[`./editor/common/config/fontInfo.ts:233:11`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./editor/common/config/fontInfo.ts#L233)<br/>&nbsp;&nbsp;at&nbsp;<unknown><br/>&nbsp;&nbsp;at&nbsp;`e`&nbsp;([`./base/common/event.ts:700:8`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L700))<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:904:1`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L904)<br/>&nbsp;&nbsp;at&nbsp;`event`&nbsp;([`./base/common/event.ts:852:6`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L852))<br/>&nbsp;&nbsp;at&nbsp;`emitter`&nbsp;([`./base/parts/ipc/common/ipc.ts:672:51`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/parts/ipc/common/ipc.ts#L672))<br/>&nbsp;&nbsp;at&nbsp;`response`&nbsp;([`./base/parts/ipc/common/ipc.ts:734:6`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/parts/ipc/common/ipc.ts#L734))<br/>&nbsp;&nbsp;at&nbsp;[`./base/parts/ipc/common/ipc.ts:714:2`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/parts/ipc/common/ipc.ts#L714)<br/>&nbsp;&nbsp;at&nbsp;[`./base/parts/ipc/common/ipc.ts:549:40`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/parts/ipc/common/ipc.ts#L549)<br/>&nbsp;&nbsp;at&nbsp;`e`&nbsp;([`./base/common/event.ts:700:8`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L700))<br/>&nbsp;&nbsp;at&nbsp;[`./base/common/event.ts:904:1`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L904)<br/>&nbsp;&nbsp;at&nbsp;`event`&nbsp;([`./base/common/event.ts:852:6`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/event.ts#L852))<br/>&nbsp;&nbsp;at&nbsp;`removeDangerousEnvVariables`&nbsp;([`./base/common/processes.ts:134:0`](https://github.com/Microsoft/vscode/blob/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/src/vs/./base/common/processes.ts#L134))<br/>
