### ISSUE TITLE
Community Server Connector doesn't start

### ISSUE THREAD

**Issue by diorgeneseugenio** [microsoft/vscode#174108]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.75.1
- OS Version: Mac OS Ventura 13.2

Steps to Reproduce:

1. Start the Community Server Connector
2. Community Server Connect Stops

On the extension host output, I got this:

```
2023-02-10 21:11:09.168 [error] Error: Connection got disposed.
    at Object.dispose (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/vscode-jsonrpc/lib/main.js:825:25)
    at RSPClient.disconnect (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/rsp-client/lib/src/client.js:73:25)
    at ServerExplorer.disposeRSPProperties (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/out/src/serverExplorer.js:712:29)
    at EventEmitter.<anonymous> (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/out/src/extensionApi.js:56:31)
    at EventEmitter.emit (node:events:526:28)
    at Socket.<anonymous> (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/rsp-client/lib/src/client.js:38:30)
    at Socket.emit (node:events:538:35)
    at TCP.<anonymous> (node:net:687:12)
2023-02-10 21:11:09.168 [error] Error: Connection got disposed.
    at Object.dispose (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/vscode-jsonrpc/lib/main.js:825:25)
    at RSPClient.disconnect (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/rsp-client/lib/src/client.js:73:25)
    at ServerExplorer.disposeRSPProperties (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/out/src/serverExplorer.js:712:29)
    at EventEmitter.<anonymous> (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/out/src/extensionApi.js:56:31)
    at EventEmitter.emit (node:events:526:28)
    at Socket.<anonymous> (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/rsp-client/lib/src/client.js:38:30)
    at Socket.emit (node:events:538:35)
    at TCP.<anonymous> (node:net:687:12)
2023-02-10 21:11:16.662 [error] Error: Failed to register client capabilities in time
    at Timeout._onTimeout (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/rsp-client/lib/src/util/common.js:18:24)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2023-02-10 21:11:16.663 [error] Error: Failed to get server handles in time
    at Timeout._onTimeout (/Users/diorgeneseugenio/.vscode/extensions/redhat.vscode-rsp-ui-0.23.13/node_modules/rsp-client/lib/src/util/common.js:18:24)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by alexdima** [comment]
The shared stack traces contain to the `redhat.vscode-rsp-ui` extension. I suggest to create an issue there.
