### ISSUE TITLE
`XHR failed` on `Downloading VS Code Server`

### ISSUE THREAD

**Issue by PayamPouryousefi** [microsoft/vscode#174243]
Type: <b>Bug</b>

This is not an open repo, but here are the steps:
1. install Docker version 23.0.1, build a5ee5b1 following instructins on https://www.hostinger.com/tutorials/how-to-install-docker-on-ubuntu on an ubuntu 20.04 vps
1.1. sudo apt-get install curl apt-transport-https ca-certificates software-properties-common
1.2. curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
1.3. sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
1.4. apt-cache policy docker-ce
1.5. sudo apt install docker-ce
2. install Code-Server 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015 on the server: `curl -fsSL https://code-server.dev/install.sh | sh`
I don't remember if I had used `code-server` or `sudo systemctl start code-server@$USER` and `sudo systemctl enable --now code-server@$USER` to enable the service but it's running:
```
>>> ps aux | grep -i code-server
root         703  0.0  1.1 611236 46772 ?        Ssl  Feb11   0:00 /usr/lib/code                                   -server/lib/node /usr/lib/code-server
root        1190  0.0  1.1 611104 48028 ?        Sl   Feb11   0:02 /usr/lib/code                                   -server/lib/node /usr/lib/code-server
root       74757  0.0  0.8 587776 34732 ?        Sl   12:15   0:00 /root/.vscode                                   -server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node /root/.vscode-remote-c                                   ontainers/dist/vscode-remote-containers-server-0.275.1.js
root       76415  0.0  0.0   8164  2584 pts/0    R+   12:29   0:00 grep --color=                                   auto -i code-server
```
In VS Code: 
3. Install Remote - SSH extension and Remote - SSH: Editing Configuration Files
4. Open the press F1, `user@hostname` enter password/setup ssh key ...
5. Install Dev Containers
6. Dev Containers: Reopen in Container
And here's the log:
[3745 ms] Dev Containers 0.275.1 in VS Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164).
[3744 ms] Start: Resolving Remote
[3784 ms] Start: Run: ssh 82.115.16.116 /bin/sh
[3813 ms] Start: Run in host: id -un
[22185 ms] root
[22185 ms] 
[22186 ms] Start: Run in host: cat /etc/passwd
[22314 ms] Start: Run in host: echo ~
[22443 ms] /root
[22443 ms] 
[22445 ms] Start: Run in host: test -x '/root/.vscode-remote-containers/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node'
[22571 ms] 
[22571 ms] 
[22573 ms] Exit code 1
[22575 ms] Start: Run in host: test -x '/root/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node'
[22701 ms] 
[22702 ms] 
[22702 ms] Start: Run in host: test -f '/root/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node_modules/node-pty/package.json'
[22829 ms] 
[22829 ms] 
[22829 ms] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.275.1.js'
[22958 ms] 
[22958 ms] 
[23088 ms] userEnvProbe: loginInteractiveShell (default)
[23091 ms] userEnvProbe: not found in cache
[23091 ms] userEnvProbe shell: /bin/bash
[23479 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[23613 ms] Setting up container for folder or workspace: /root/Development/factorio-learning-environment-1
[23613 ms] Host: ssh://82.115.16.116
[23615 ms] Start: Check Docker is running
[23616 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[23887 ms] Server API version: 1.42
[23888 ms] Start: Run in Host: docker volume ls -q
[24166 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=/root/Development/factorio-learning-environment-1 --filter label=vsch.quality=stable
[24437 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/root/Development/factorio-learning-environment-1 --filter label=devcontainer.config_file=/root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json
[24710 ms] Start: Run in Host: docker inspect --type container c15e1cbc44fe
[24992 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/root/Development/factorio-learning-environment-1
[25263 ms] Start: Run in Host: docker inspect --type container c15e1cbc44fe
[25807 ms] Start: Run in Host: /root/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-722aa87c-f48f-4782-a939-74e55d1314551676290519590 --workspace-folder /root/Development/factorio-learning-environment-1 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/root/Development/factorio-learning-environment-1 --id-label devcontainer.config_file=/root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json --log-level debug --log-format json --config /root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[26094 ms] (node:74937) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[26094 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[28495 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.4.0-139-generic x64.
[28495 ms] Start: Run: docker buildx version
[28557 ms] github.com/docker/buildx v0.10.2 00ed17d
[28557 ms] 
[28558 ms] Start: Resolving Remote
[28560 ms] Start: Run: git rev-parse --show-cdup
[28563 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/root/Development/factorio-learning-environment-1 --filter label=devcontainer.config_file=/root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json
[28602 ms] Start: Run: docker inspect --type container c15e1cbc44fe
[28640 ms] Start: Inspecting container
[28640 ms] Start: Run: docker inspect --type container c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4
[28680 ms] Start: Run in container: /bin/sh
[28682 ms] Start: Run in container: uname -m
[28758 ms] x86_64
[28758 ms] 
[28758 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[28759 ms] PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[28759 ms] 
[28759 ms] Start: Run in container: cat /etc/passwd
[28761 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[28762 ms] 
[28762 ms] 
[28762 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[28763 ms] 
[28763 ms] 
[26368 ms] Start: Run in Host: docker inspect --type container c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4
[26908 ms] Start: Run in Host: /root/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /root/Development/factorio-learning-environment-1 --id-label devcontainer.local_folder=/root/Development/factorio-learning-environment-1 --id-label devcontainer.config_file=/root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json --container-id c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4 --log-level debug --log-format json --config /root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json --mount-workspace-git-root true
[27191 ms] (node:75113) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[27191 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[29593 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.4.0-139-generic x64.
[29593 ms] Start: Run: git rev-parse --show-cdup
[29598 ms] Start: Run: docker inspect --type container c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4
[27502 ms] Start: Run in Host: /root/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /root/Development/factorio-learning-environment-1 --id-label devcontainer.local_folder=/root/Development/factorio-learning-environment-1 --id-label devcontainer.config_file=/root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json --container-id c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4 --log-level debug --log-format json --config /root/Development/factorio-learning-environment-1/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[27787 ms] (node:75147) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[27791 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[30191 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.4.0-139-generic x64.
[30191 ms] Start: Run: git rev-parse --show-cdup
[30196 ms] Start: Run: docker inspect --type container c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4
[27844 ms] Start: Inspecting container
[27844 ms] Start: Run in Host: docker inspect --type container c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4
[28136 ms] Start: Run in Host: docker exec -i -u vscode -e VSCODE_REMOTE_CONTAINERS_SESSION=722aa87c-f48f-4782-a939-74e55d1314551676290519590 c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4 /bin/sh
[28274 ms] Start: Run in container: uname -m
[28407 ms] x86_64
[28407 ms] 
[28407 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[29003 ms] PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[29003 ms] 
[29004 ms] Start: Run in container: cat /etc/passwd
[29134 ms] Start: Setup shutdown monitor
[29135 ms] Forking shutdown monitor: c:\Users\payam\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\shutdown\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-5440aeadd1043ecfa289c48a34301dcec4b493f9-sock singleContainer Debug c:\Users\payam\AppData\Roaming\Code\logs\20230213T101743\window1\exthost\ms-vscode-remote.remote-containers 1676290521815
[29332 ms] Start: Run in container: test -d /home/vscode/.vscode-server
[29466 ms] 
[29466 ms] 
[29467 ms] Start: Run in container: test ! -f '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[29716 ms] 
[29716 ms] 
[29716 ms] Exit code 1
[29717 ms] Start: Run in container: cat /home/vscode/.vscode-server/data/Machine/settings.json
[29847 ms] {
        "python.defaultInterpreterPath": "/home/vscode/.pyenv/versions/3.8.12/bin/python",
        "python.formatting.provider": "black",
        "python.formatting.blackArgs": [
                "--no-color"
        ],
        "python.linting.enabled": true,
        "python.linting.mypyEnabled": true,
        "python.linting.pylintEnabled": true,
        "python.terminal.activateEnvironment": false
}
[29847 ms] 
[29848 ms] Start: Run in container: test -d /home/vscode/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164
[29976 ms] 
[29976 ms] 
[29976 ms] Exit code 1
[29976 ms] Start: Run in container: test -d /vscode/vscode-server/bin/linux-x64/e2816fe719a4026ffa1ee0189dc89bdfdbafb164
[30106 ms] 
[30107 ms] 
[30107 ms] Exit code 1
[30108 ms] Installing VS Code Server for commit e2816fe719a4026ffa1ee0189dc89bdfdbafb164
[30108 ms] Start: Run in Host: docker exec -i -u root c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4 /bin/sh
[30246 ms] Start: Downloading VS Code Server
[30246 ms] e2816fe719a4026ffa1ee0189dc89bdfdbafb164 linux-x64 stable 
[50550 ms] read ECONNRESET
[50551 ms] Retrying to download VS Code Server.
[90929 ms] Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/payam/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
[1338450 ms] Start: Run in Host: docker stop -t 0 c15e1cbc44fea34db82f4aba4572b97d633672ecbcedab263e565664af1196e4
[1357654 ms] Host server: Connection reset by HostName port 22
[1357698 ms] Host server terminated (code: 255, signal: null).

Note: I've changed the ip to HostName in the line before last line.
Error: `XHR failed`

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No
Connection to 'Dev Container: FLE Workspace @ ssh://82.115.16.116' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.92GB (3.64GB free)|
|Process Argv|--crash-reporter-id 795b12bb-1457-4935-a103-40b1a7091def|
|Screen Reader|no|
|VM|0%|

Connection to 'Dev Container: FLE Workspace @ ssh://82.115.16.116' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30660300
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30657576
89544117:30613380
pythonsymbol12:30657548

```

</details>

**Comment by torstenmaul** [comment]
Same here.

Trying to rebuild devcontainer fails with:
```
Installing VS Code Server for commit 441438abd1ac652551dbe4d408dfcec8a499b8bf
Start: Run in container: /bin/sh
Start: Downloading VS Code Server
441438abd1ac652551dbe4d408dfcec8a499b8bf linux-x64 stable 
getaddrinfo ENOTFOUND update.code.visualstudio.com
Retrying to download VS Code Server.
Start: Run: docker rm -f 0e4bc43f2b368ae32d3313c4692ce226dea061e8297f331a66d8540a28c71fcf
Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/xyz/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
Container server terminated (code: 137, signal: null).
```

**Comment by chrmarti** [comment]
Dev Containers falls back to using Electron for downloading the server if using Node's https fails. Here both failed which might indicate a temporary issue with the connection or the server. Could you retry and confirm the problem persists?
