### ISSUE TITLE
Failed to load message bundle for language en

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#174848]
**Steps:**
* insiders today
* configure runtime arguments (`argv.json` file) to have `"locale": "en"`
* restart

```
workbench.js:2493 Failed to load message bundle for language en. Falling back to the default language: Error: [object Event]
    at Object.m [as ensureError] (workbench.js:553:22)
    at a._createLoadError (workbench.js:1805:33)
    at a._onLoadError (workbench.js:1816:30)
    at l (workbench.js:1962:27)
    at Object.errorback (workbench.js:1982:25)
    at e.triggerErrorback (workbench.js:928:36)
    at workbench.js:915:151
    at HTMLScriptElement.l (workbench.js:951:17)
```

**Comment by rzhao271** [comment]
Here's an error message with a path

```
workbench.desktop.main.js:1670 Extension Host
workbench.desktop.main.js:1670 Failed to load message bundle for language en. Falling back to the default language: [Error: ENOENT: no such file or directory, open 'c:\Users\raymondzhao\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.nls.en.js'] {  errno: -4058,  code: 'ENOENT',  syscall: 'open',  path: 'c:\\Users\\raymondzhao\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\out\\vs\\workbench\\api\\node\\extensionHostProcess.nls.en.js',  phase: 'loading',  moduleId: 'vs/workbench/api/node/extensionHostProcess.nls.en',  neededBy: [ '===anonymous2===' ]}
```

There's `out/vs/workbench/api/node/extensionHostProcess.nls.js`, but there's no `extensionHostProcess.nls.en.js`.
