### ISSUE TITLE
Test profiles in remotes

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#174866]
Refs: https://github.com/microsoft/vscode/issues/165247

- [x] win @karthiknadig
- [x] mac @DonJayamanne
- [x] linux @andreamah
- [x] web @ulugbekna (codespaces)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174866%0A%0A&assignees=sandy081)

---

## Set up

Please install following extensions for the platform you are testing.

windows - use wsl -> `ms-vscode-remote.remote-wsl`
mac - use ssh -> `ms-vscode-remote.remote-ssh` - Follow this [link](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#macos) to use your own machine as remote using SSH 
linux - use dev container -> `ms-vscode-remote.remote-containers` - Try a dev container sample
web - create a codespace

## Testing

Profiles are now supported in remote workspaces. 

- Switch to new/existing profile to remote workspace and make sure remote extensions are switched as expected. 
- Install and uninstall extensions in the remote window and make sure switching profiles are working as expected. For eg: 
  - Install a workspace extension (eg: ESLint) in the remote window that is in a non-default profile. Make sure the extension is installed remotely in that profile. Switching to default profile shall not have this workspace extension installed.
  - Make sure uninstalling a remote extension in a remote window with non default profile is uninstalled only in that remote profile.
- Make sure switching profile in remote window to a profile that does not has the supported remote extension, will automatically installs the remote extension in that profile.

**Comment by karthiknadig** [comment]
Worked as expected. 

One thing to note that, when installing certain extension, it used to fail. The one thing about this particular extension is that it is platform specific and contains platform specific binaries. Extensions that are universal installed fine.

```
2023-02-21 14:36:08.626 [error] EACCES: EACCES: permission denied, rename '/home/kanadig/.vscode-server-insiders/extensions/.23ac8db6-5fd4-418e-a7a3-537ca86ba37a' -> '/home/kanadig/.vscode-server-insiders/extensions/charliermarsh.ruff-2023.6.0-linux-x64'
    at V.v (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:88146)
    at async V.extractUserExtension (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:85203)
    at async te.u (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91691)
    at async te.x (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:93276)
    at async te.h (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91340)
2023-02-21 14:36:08.722 [error] EACCES: permission denied, rename '/home/kanadig/.vscode-server-insiders/extensions/.23ac8db6-5fd4-418e-a7a3-537ca86ba37a' -> '/home/kanadig/.vscode-server-insiders/extensions/charliermarsh.ruff-2023.6.0-linux-x64': EACCES: EACCES: permission denied, rename '/home/kanadig/.vscode-server-insiders/extensions/.23ac8db6-5fd4-418e-a7a3-537ca86ba37a' -> '/home/kanadig/.vscode-server-insiders/extensions/charliermarsh.ruff-2023.6.0-linux-x64'
    at V.v (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:88146)
    at async V.extractUserExtension (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:85203)
    at async te.u (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91691)
    at async te.x (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:93276)
    at async te.h (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91340)
2023-02-21 15:02:02.535 [error] EACCES: EACCES: permission denied, rename '/home/kanadig/.vscode-server-insiders/extensions/.23ac8db6-5fd4-418e-a7a3-537ca86ba37a' -> '/home/kanadig/.vscode-server-insiders/extensions/charliermarsh.ruff-2023.6.0-linux-x64'
    at V.v (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:88146)
    at async V.extractUserExtension (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:85203)
    at async te.u (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91691)
    at async te.x (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:93276)
    at async te.h (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91340)
2023-02-21 15:02:02.601 [error] EACCES: permission denied, rename '/home/kanadig/.vscode-server-insiders/extensions/.23ac8db6-5fd4-418e-a7a3-537ca86ba37a' -> '/home/kanadig/.vscode-server-insiders/extensions/charliermarsh.ruff-2023.6.0-linux-x64': EACCES: EACCES: permission denied, rename '/home/kanadig/.vscode-server-insiders/extensions/.23ac8db6-5fd4-418e-a7a3-537ca86ba37a' -> '/home/kanadig/.vscode-server-insiders/extensions/charliermarsh.ruff-2023.6.0-linux-x64'
    at V.v (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:88146)
    at async V.extractUserExtension (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:85203)
    at async te.u (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91691)
    at async te.x (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:93276)
    at async te.h (/home/kanadig/.vscode-server-insiders/bin/5454665328aa30aeb989abfc195e7a7aacd94edf/out/vs/server/node/server.main.js:149:91340)
```

**Comment by sandy081** [comment]
@karthiknadig Thanks for reporting this. Can you please check in the extension installation folder if there is a folder already with `charliermarsh.ruff-2023.6.0-linux-x64`?
