### ISSUE TITLE
problems installing python extension in vscode.please someone assist

### ISSUE THREAD

**Issue by Gitongakennedy** [microsoft/vscode#174964]

**Comment by sandy081** [comment]
@Gitongakennedy Are you getting the error same as mentioned by @sfjkastello ?

**Comment by pryan-pro** [comment]
Hi there,

I am seeing the similar issue on fresh mac build and vscode install. Upon disabling the extension signature verification, I receive the following error upon install:

`2023-02-22 13:12:20.483 [error] Extract: invalid distance code
    at K.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:166889)
    at async K.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:164379)
    at async $.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:170215)
    at async $.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171432)
2023-02-22 13:12:20.498 [error] invalid distance code: Extract: invalid distance code
    at K.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:166889)
    at async K.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:164379)
    at async $.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:170215)
    at async $.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171432)
`

**Comment by sandy081** [comment]
@pryan-pro It seems your issue is not same as this, because the user has not provided any description. In your case, the download VSIX is corrupted. Can you please open cached extensions vsix folder and delete the VSIXs and retry.  To open cached extensions vsix folder - Run command - `F1 > Developer: Open User Data Folder` and open `CachedExtensionVSIXs` folder.

**Comment by pryan-pro** [comment]
@sandy081 I have tried installing after removing from the vsix cache folder as well as after cleaning via appcleaner and removing all code files. On a fresh install, I get the error above both from the standard extension install method and installing the downloaded vsix directly. 

Thank you

**Comment by sandy081** [comment]
> installing the downloaded vsix directly

How are you downloading the VSIX? What is the link you used? Can you please share the downloaded VSIX and also the link?

**Comment by sandy081** [comment]
I speculate that the downloaded VSIX is corrupted. Can you please try with a fresh user data dir and extensions dir from CLI and see if you can repro?

`code --user-data-dir <folder1> --extensions-dir <folder2>`
