### ISSUE TITLE
SSh works but not vscode, authentication failure aws

### ISSUE THREAD

**Issue by bibinvargheset** [microsoft/vscode#175459]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: No

- VS Code Version: 1.75.1
- OS Version:  ubuntu 22.04
- remote os : ubuntu 20.04 AWS

Steps to Reproduce:

1. 
2. 

[19:20:46.564] Log Level: 2
[19:20:46.584] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2252656e6b6f227d", attempt 1
[19:20:46.585] "remote.SSH.useLocalServer": true
[19:20:46.586] "remote.SSH.path": undefined
[19:20:46.587] "remote.SSH.configFile": /home/bibin/.ssh/config
[19:20:46.587] "remote.SSH.useFlock": true
[19:20:46.588] "remote.SSH.lockfilesInTmp": false
[19:20:46.588] "remote.SSH.localServerDownload": auto
[19:20:46.589] "remote.SSH.remoteServerListenOnSocket": false
[19:20:46.589] "remote.SSH.showLoginTerminal": false
[19:20:46.590] "remote.SSH.defaultExtensions": []
[19:20:46.590] "remote.SSH.loglevel": 2
[19:20:46.590] "remote.SSH.enableDynamicForwarding": true
[19:20:46.591] "remote.SSH.enableRemoteCommand": false
[19:20:46.591] "remote.SSH.serverPickPortsFromRange": {}
[19:20:46.591] "remote.SSH.serverInstallPath": {}
[19:20:46.598] VS Code version: 1.75.1
[19:20:46.598] Remote-SSH version: remote-ssh@0.96.0
[19:20:46.599] linux x64
[19:20:46.603] SSH Resolver called for host: Renko
[19:20:46.604] Setting up SSH remote "Renko"
[19:20:46.610] Acquiring local install lock: /tmp/vscode-remote-ssh-8200c884-install.lock
[19:20:46.613] Looking for existing server data file at /home/bibin/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-8200c884-441438abd1ac652551dbe4d408dfcec8a499b8bf-0.96.0/data.json
[19:20:46.616] Using commit id "441438abd1ac652551dbe4d408dfcec8a499b8bf" and quality "stable" for server
[19:20:46.640] Install and start server if needed
[19:20:46.654] PATH: /home/bibin/.pyenv/shims:/home/bibin/.pyenv/bin:/home/bibin/.pyenv/bin:/home/bibin/.local/bin:/home/bibin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
[19:20:46.654] Checking ssh with "ssh -V"
[19:20:46.674] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020

[19:20:46.680] Using SSH config file "/home/bibin/.ssh/config"
[19:20:46.681] askpass server listening on /run/user/1000/vscode-ssh-askpass-6132b26ef3defcd4babcf5222721181d8abe00e1.sock
[19:20:46.681] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-3664d74b4a7cbef6770fc5403e11f9ba73036f60.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","39607","-o","ConnectTimeout=15","-F","/home/bibin/.ssh/config","Renko"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/bibin/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-8200c884-441438abd1ac652551dbe4d408dfcec8a499b8bf-0.96.0/data.json"}
[19:20:46.681] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/119/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-6132b26ef3defcd4babcf5222721181d8abe00e1.sock"}
[19:20:46.689] Spawned 232741
[19:20:46.865] > local-server-1> Running ssh connection command: "-v -T -D 39607 -o ConnectTimeout=15 -F /home/bibin/.ssh/config Renko"
[19:20:46.871] > local-server-1> Spawned ssh, pid=232749
[19:20:46.875] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
[19:20:47.143] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pMoRBmE0hFKlDScXPG0j/roftq0ePM1NRVyoJXtubH8
[19:20:48.522] stderr> Received disconnect from 3.109.132.10 port 22:2: Too many authentication failures
[19:20:48.523] stderr> Disconnected from 3.109.132.10 port 22
[19:20:48.524] > local-server-1> ssh child died, shutting down
[19:20:48.541] Local server exit: 0
[19:20:48.542] Received install output: local-server-1> Running ssh connection command: "-v -T -D 39607 -o ConnectTimeout=15 -F /home/bibin/.ssh/config Renko"
local-server-1> Spawned ssh, pid=232749
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pMoRBmE0hFKlDScXPG0j/roftq0ePM1NRVyoJXtubH8
Received disconnect from 3.109.132.10 port 22:2: Too many authentication failures
Disconnected from 3.109.132.10 port 22
local-server-1> ssh child died, shutting down

[19:20:48.552] Resolver error: Error: Too many authentication failures
	at g.Create (/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:584147)
	at /home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:582166
	at t.handleInstallOutput (/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:582683)
	at Object.e [as tryInstallWithLocalServer] (/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:623419)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:642712
	at async t.withShowDetailsEvent (/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:646432)
	at async /home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:621891
	at async T (/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:618397)
	at async t.resolveWithLocalServer (/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:621506)
	at async t.resolve (/home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:644040)
	at async /home/bibin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:721750

**Comment by lszomoru** [comment]
@bibinvargheset, sorry for not getting back to you on this.
Are you still able to reproduce this with the latest version of VS Code? Thanks!

**Comment by bibinvargheset** [comment]
The issue is resolved now, I don't remember how it was solved, but due to other reasons, I had to reinstall Zorin in august maybe then, I don't exactly remember the solution anyway.

**Comment by lszomoru** [comment]
@bibinvargheset, thanks for the update. I will go ahead and close this issue.
