### ISSUE TITLE
Cannot read properties of undefined (reading 'startLineNumber')

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#175512]
```javascript
TypeError: Cannot read properties of undefined (reading 'startLineNumber')
at <anonymous> in src/vs/editor/contrib/codelens/browser/codelens.ts:69:22
at Array.sort (<anonymous>)
at S in src/vs/editor/contrib/codelens/browser/codelens.ts:67:32
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=441438abd1ac652551dbe4d408dfcec8a499b8bf&bH=b74729c1-cdd5-ccc9-3a7c-b42ea93d7f99)

**Comment by dmitrivMS** [comment]
Similar to https://github.com/microsoft/vscode/issues/233159
Likely already addressed by https://github.com/microsoft/vscode/pull/236353
If this is still present, a new issue will be filed from error telemetry.
