### ISSUE TITLE
Build: process artefacts

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#175500]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=204504&view=logs&j=cf443a0b-eb78-5c24-80e4-94acc0eb47c1&t=1866d99e-8502-588e-dc20-fdb63426c87c&l=945

```
Creating asset...
Size: 119280477
SHA1: 3d5504cfeed12f5409fc46276499006cc506ae93
SHA256: 57ea0b066b05c64cfed5fd05f64c73161fd5205873d173a4959a16652d590029
CredentialUnavailableError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/5aee1d83-7e4e-46a6-8aaa-1aa19b216510/v2.0/.well-known/openid-configuration
    at MsalClientSecret.handleError (/mnt/vss/_work/1/s/build/node_modules/@azure/identity/dist/index.js:699:28)
    at MsalClientSecret.doGetToken (/mnt/vss/_work/1/s/build/node_modules/@azure/identity/dist/index.js:1803:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async trace (/mnt/vss/_work/1/s/build/node_modules/@azure/identity/dist/index.js:253:24)
    at async tryGetAccessToken (/mnt/vss/_work/1/s/build/node_modules/@azure/core-http/dist/index.js:3744:32)
    at async beginRefresh (/mnt/vss/_work/1/s/build/node_modules/@azure/core-http/dist/index.js:3752:17)
    at async BearerTokenAuthenticationPolicy.sendRequest (/mnt/vss/_work/1/s/build/node_modules/@azure/core-http/dist/index.js:3873:31)
    at async StorageRetryPolicy.attemptSendRequest (/mnt/vss/_work/1/s/build/node_modules/@azure/storage-blob/dist/index.js:14086:24)
    at async StorageClientContext.sendOperationRequest (/mnt/vss/_work/1/s/build/node_modules/@azure/core-http/dist/index.js:4695:31)
Exception: /mnt/vss/_work/1/s/build/azure-pipelines/win32/exec.ps1:22
```

**Comment by joaomoreno** [comment]
This has happened a few times in the last week. It's an error on the identity service. AFAIK there's nothing we can do about it other than hope they fix the issue upstream. I've seen it on public Azure as well as on Mooncake. Let's hope this goes down.
