### ISSUE TITLE
Interactive window scrolls after execute

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#175729]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=204773&view=results

```
1) Interactive Window
       Interactive window scrolls after execute:
     Error: asPromise TIMEOUT reached
      at asPromise (extensions/vscode-api-tests/src/utils.ts:136:16)
      at addCellAndRun (extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:38:25)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/interactiveWindow.test.ts:90:4)
```

**Comment by amunger** [comment]
Looks like this only failed once.
I made some updates and added more diagnostic info for test failures to help troubleshoot if this fails again, closing for now
