### ISSUE TITLE
"Signature: PackageIsUnreadable" error when attempting to install extensions on Insiders 1.77

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [microsoft/vscode#175912]
## Issue

Whenever I attempt to install extensions in Insiders 1.77, I get a `Signature: PackageIsUnreadable` error.

Does this issue occur when all extensions are disabled?: n/a I think

## Current Versions

Version: 1.77.0-insider
Commit: 155cd6db223feb1f8c734ca70e108b9efec7b054
Date: 2023-03-02T12:46:14.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

## Steps to Reproduce:

1. Open Insiders 1.77 application
2. Go to extensions tab and search for an extension (e.g. App Service or Azure Functions) and click the install button
3. Watch installation fail

Here's a snippet of some logs:

```
2023-03-02 10:57:38.945 [error] Signature: PackageIsUnreadable
    at ki.download (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:468)
    at async Q.x (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:20769)
    at async Q.h (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:18910)
```

**Comment by gaoqiangz** [comment]
Same problem.

**Comment by sandy081** [comment]
CC @dtivel

**Comment by qwe813874700** [comment]
I have encountered the same problem, is there a solution?

**Comment by kiekio** [comment]
same problem too,can not install any package, i select to reinstall it,,,

**Comment by kiekio** [comment]
same problem,this is version information
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

and the debug level log is that:
2023-03-20 10:11:30.964 [info] Starting worker process with pid 13632 (type: fileWatcher, window: 1).
2023-03-20 10:11:31.407 [info] WSL is not installed, so could not detect WSL profiles
2023-03-20 10:11:34.685 [info] Getting Manifest... ms-ceintl.vscode-language-pack-zh-hans
2023-03-20 10:11:34.686 [info] Getting Manifest... ms-vscode.cpptools
2023-03-20 10:11:34.687 [info] Getting Manifest... shd101wyy.markdown-preview-enhanced
2023-03-20 10:11:34.693 [info] Installing extension: ms-ceintl.vscode-language-pack-zh-hans
2023-03-20 10:11:34.694 [info] Installing extension: ms-vscode.cpptools
2023-03-20 10:11:34.695 [info] Installing extension: shd101wyy.markdown-preview-enhanced
2023-03-20 10:11:35.542 [error] Error while installing the extension: ms-ceintl.vscode-language-pack-zh-hans
2023-03-20 10:11:35.542 [error] Failed to install extension. ms-ceintl.vscode-language-pack-zh-hans
2023-03-20 10:11:35.542 [error] Signature: PackageIsUnreadable
    at yt.download (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-20 10:11:35.542 [error] [uncaught exception in sharedProcess]: PackageIsUnreadable: Signature: PackageIsUnreadable
    at yt.download (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-20 10:11:35.874 [error] Error while installing the extension: shd101wyy.markdown-preview-enhanced
2023-03-20 10:11:35.874 [error] Failed to install extension. shd101wyy.markdown-preview-enhanced
2023-03-20 10:11:35.874 [error] Signature: PackageIsUnreadable
    at yt.download (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-20 10:11:35.874 [error] [uncaught exception in sharedProcess]: PackageIsUnreadable: Signature: PackageIsUnreadable
    at yt.download (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-20 10:11:38.075 [error] Error while installing the extension: ms-vscode.cpptools
2023-03-20 10:11:38.075 [error] Failed to install extension. ms-vscode.cpptools
2023-03-20 10:11:38.075 [error] Signature: PackageIsUnreadable
    at yt.download (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-20 10:11:38.076 [error] [uncaught exception in sharedProcess]: PackageIsUnreadable: Signature: PackageIsUnreadable
    at yt.download (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/XXX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-20 10:12:13.713 [error] [uncaught exception in sharedProcess]: A system error occurred (ENOTEMPTY: directory not empty, rmdir 'C:\Users\XXX\AppData\Roaming\Code\CachedData\30d9c6cd9483b2cc586687151bcbcd635f373630\chrome\wasm'): Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\XXX\AppData\Roaming\Code\CachedData\30d9c6cd9483b2cc586687151bcbcd635f373630\chrome\wasm'

**Comment by lesomnus** [comment]
I can install some pakcages but got same error when Im trying to install `dbaeumer.vscode-eslint`.
```
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
Host OS is windows, but Im working on the remote container runs on the remote machine which is linux.

**Comment by sandy081** [comment]
Can you (those who subscribed) please verify if this issue still exists?

- Remove the setting `extensions.verifySignature` if you have set it
- Restart VS Code
- Set Log Level to Trace - `F1 > Developer: Set Log Level > Trace`
- Install an extension
- Share the output - `F1 > Show View... > Shared`

**Comment by kiekio** [comment]
no problem now. thank you.

**Comment by sandy081** [comment]
Closing this as I do not see any reports after my previous comment.
