### ISSUE TITLE
[PerfSampleError] `drawImage`

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#176261]
```javascript
[PerfSampleError] by <<renderer>> in drawImage
at drawImage
at _drawChars in vscode-file://vscode-app/node_modules.asar/xterm-addon-canvas/lib/xterm-addon-canvas.js:1:7048
at <anonymous> in vscode-file://vscode-app/node_modules.asar/xterm-addon-canvas/lib/xterm-addon-canvas.js:1:27574
at _forEachCell in vscode-file://vscode-app/node_modules.asar/xterm-addon-canvas/lib/xterm-addon-canvas.js:1:25926
at _drawForeground in vscode-file://vscode-app/node_modules.asar/xterm-addon-canvas/lib/xterm-addon-canvas.js:1:27545
at handleGridChanged in vscode-file://vscode-app/node_modules.asar/xterm-addon-canvas/lib/xterm-addon-canvas.js:1:27625
at renderRows in vscode-file://vscode-app/node_modules.asar/xterm-addon-canvas/lib/xterm-addon-canvas.js:1:12323
at _renderRows in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:100341
at <anonymous> in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:98340
at _innerRefresh in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:19145
at <anonymous> in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:19104
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=92da9481c0904c6adfe372c12da3b7748d74bdcb&bH=c0157533-b588-c20e-f9ca-725b4ada8252)

**Comment by Tyriar** [comment]
This code no longer exists 🎉
