### ISSUE TITLE
[PerfSampleError] `localProcessExtensionHost.postMessage`

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#176255]
```javascript
[PerfSampleError] by <<renderer>> in postMessage
at postMessage
at message in src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts:620:12
at O in src/vs/workbench/services/extensions/common/rpcProtocol.ts:458:10
at P.<computed>.F.charCodeAt.P.<computed> in src/vs/workbench/services/extensions/common/rpcProtocol.ts:252:21
at event in src/vs/workbench/api/browser/mainThreadFileSystemEventService.ts:48:51
at invoke in out/vs/workbench/workbench.desktop.main.js:86:127
at deliver in out/vs/workbench/workbench.desktop.main.js:86:2004
at fire in out/vs/workbench/workbench.desktop.main.js:86:1588
at changes in src/vs/platform/files/common/fileService.ts:66:52
at invoke in out/vs/workbench/workbench.desktop.main.js:86:127
at deliver in out/vs/workbench/workbench.desktop.main.js:86:2004
at fire in out/vs/workbench/workbench.desktop.main.js:86:1588
at changes in src/vs/platform/files/common/diskFileSystemProvider.ts:105:5
at changes in src/vs/workbench/services/files/electron-sandbox/diskFileSystemProvider.ts:139:37
at changes in src/vs/platform/files/common/watcher.ts:175:48
at invoke in out/vs/workbench/workbench.desktop.main.js:86:127
at deliver in out/vs/workbench/workbench.desktop.main.js:86:2004
at fire in out/vs/workbench/workbench.desktop.main.js:86:1588
at invoke in out/vs/workbench/workbench.desktop.main.js:86:127
at deliver in out/vs/workbench/workbench.desktop.main.js:86:2004
at fire in out/vs/workbench/workbench.desktop.main.js:86:1588
at res in src/vs/base/parts/ipc/common/ipc.ts:672:30
at t in src/vs/base/parts/ipc/common/ipc.ts:733:10
at s in src/vs/base/parts/ipc/common/ipc.ts:713:10
at msg in src/vs/base/parts/ipc/common/ipc.ts:549:51
at invoke in out/vs/workbench/workbench.desktop.main.js:86:127
at deliver in out/vs/workbench/workbench.desktop.main.js:86:2004
at fire in out/vs/workbench/workbench.desktop.main.js:86:1588
at ie in src/vs/base/common/event.ts:471:14
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=92da9481c0904c6adfe372c12da3b7748d74bdcb&bH=1b215bf5-215e-7249-a903-496b96deba80)

**Comment by jrieken** [comment]
not actionable
