### ISSUE TITLE
OpenAnythingHandler throws errors

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1763]
```
Unable to instanciate quick open handler vs/workbench/parts/search/browser/openAnythingHandler - OpenSymbolHandler: {}e.onUnexpectedError @ workbench.main.js:91
workbench.main.js:67 Unable to instanciate quick open handler vs/workbench/parts/search/browser/openAnythingHandler - OpenSymbolHandler: {}: Error: Unable to instanciate quick open handler vs/workbench/parts/search/browser/openAnythingHandler - OpenSymbolHandler: {}
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:22731
    at __dirname.undefined.t.Class.define.done (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:6:23141)
    at t.onType (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:22533)
    at Object.quickOpenWidget.quickOpenWidget.d.QuickOpenWidget.onType (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:20126)
    at e.doShowWithPrefix (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:26:18036)
    at e.show (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:26:17864)
    at t.show (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:20648)
    at t.run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:64:31858)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:64:14730
    at __dirname.undefined.t.Class.define.then (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:6:24063)
```

**Comment by bpasero** [comment]
@jrieken i am not seeing this, I am on 92a51bcfdcb9cb52a86529a2da46f413729415fd

Steps?

**Comment by jrieken** [comment]
Same version. Step is press `Cmd+T`
