### ISSUE TITLE
VSCode Won't Open In WSL When I'm Offline But Does So When I'm Online

### ISSUE THREAD

**Issue by Primepoke** [microsoft/vscode#176513]
Type: <b>Bug</b>

When I'm online (connected to the internet) and I turn on vscode in WSL, it opens well. But the minute I'm offline and open vscode in wsl, it does not open the folder/files I'm working on. When I try starting vscode when offline, it displays the following:

"The editor could not be opened due to an unexpected error: ENOPRO: Np file system provider found for resource 'vscode-remote://wsl%2Bubuntu-22.04/mnt/c/...path/to/file'

When I check the log, it shows many lines of error, notable among them is:

[2023-03-08 13:01:06.864] Error: Unable to retrieve mac address (unexpected format)
[2023-03-08 13:01:06.864]
[2023-03-08 13:01:06.864] Error: Unable to retrieve mac address (unexpected format)
[2023-03-08 13:01:06.864] at S (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:63:3251)
[2023-03-08 13:01:06.864] at v (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8276)
[2023-03-08 13:01:06.864] at async /home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8133
[2023-03-08 13:01:06.864] at Timeout._onTimeout (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:8:12)
[2023-03-08 13:01:06.864] at listOnTimeout (node:internal/timers:559:17)
[2023-03-08 13:01:06.864] at processTimers (node:internal/timers:502:7)
[2023-03-08 13:01:06.864] VS Code Server for WSL closed unexpectedly.
[2023-03-08 13:01:07.063] Download in background is enabled
[2023-03-08 13:01:08.945] WSL Daemon exited with code 0

STEPS TO REPRODUCE
1. Turn of internet connection
2. Start VSCode.

wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 1

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Connection to 'WSL: Ubuntu-22.04' could not be established  Browser is offline

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.85GB (0.64GB free)|
|Process Argv|--crash-reporter-id ef41cfd8-6f89-407e-af40-e7769f5e9b7d|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu-22.04' could not be established  Browser is offline
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850
pythonb192:30669360

```

</details>

**Comment by aeschli** [comment]
We have a fix coming for this: https://github.com/microsoft/vscode/issues/175878

Marking as duplicate

**Comment by Primepoke** [comment]
Great. The fix from https://github.com/microsoft/vscode/issues/175878 (#175878) worked.
