### ISSUE TITLE
Extension host terminated in Angular app

### ISSUE THREAD

**Issue by lopatiuka** [microsoft/vscode#176511]
Type: <b>Bug</b>

Extension host terminated when entering styles.scss in angular app created by CLI. How can i fix it?

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by deepak1556** [comment]
Can you paste the error from `Extension host` logs ?

**Comment by lopatiuka** [comment]
yes, sure 

2023-03-09 16:22:13.503 [error] Error: Import "~@angular/material/prebuilt-themes/indigo-pink.css" could not be resolved.
	at u.load (c:\Users\santy\.vscode\extensions\naumovs.color-highlight-2.5.0\dist\extension-node.js:1:39610)
	at c:\Users\santy\.vscode\extensions\naumovs.color-highlight-2.5.0\dist\extension-node.js:1:40002
	at FSReqCallback.oncomplete (node:fs:198:21)

**Comment by lopatiuka** [comment]
> Can you paste the error from `Extension host` logs ?

yes, sure

2023-03-09 16:22:12.563 [info] Not activating extension 'Dart-Code.dart-code': Timed out while searching for 'workspaceContains' pattern /pubspec.yaml,//pubspec.yaml,.dart,/.dart,//.dart
2023-03-09 16:22:12.563 [info] Not activating extension 'ritwickdey.live-sass': Timed out while searching for 'workspaceContains' pattern **/.s[ac]ss
2023-03-09 16:22:13.503 [error] Error: Import "~@angular/material/prebuilt-themes/indigo-pink.css" could not be resolved.
at u.load (c:\Users\santy.vscode\extensions\naumovs.color-highlight-2.5.0\dist\extension-node.js:1:39610)
at c:\Users\santy.vscode\extensions\naumovs.color-highlight-2.5.0\dist\extension-node.js:1:40002
at FSReqCallback.oncomplete (node:fs:198:21)

**Comment by lopatiuka** [comment]
solved this issue by replacing 
@import '~@angular/material/prebuilt-themes/indigo-pink.css';
with
@import '../node_modules/@angular/material/prebuilt-themes/indigo-pink.css';
