### ISSUE TITLE
Flaky smoke test: verifies settings (css)

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#176691]
```
1) VSCode Smoke Tests (Electron)
       Language Features
         verifies settings (css):
     Error: Timeout: click ' .monaco-editor[data-uri$="settings.json"] .view-lines > .view-line:nth-child(1)' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:269:11)
      at Code.waitAndClick (/__w/1/s/test/automation/src/code.ts:210:3)
      at Editor.waitForEditorFocus (/__w/1/s/test/automation/src/editor.ts:83:3)
      at SettingsEditor.openUserSettingsFile (/__w/1/s/test/automation/src/settings.ts:54:3)
      at SettingsEditor.addUserSetting (/__w/1/s/test/automation/src/settings.ts:22:3)
      at Context.<anonymous> (src/areas/languages/languages.test.ts:48:4)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=205963&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a3fc59e7-8555-5b77-66bd-36e3741aa013

**Comment by bpasero** [comment]
[Archive.zip](https://github.com/microsoft/vscode/files/10940292/Archive.zip)

There are crashes.

**Comment by rzhao271** [comment]
[symbolicated-2e.log](https://github.com/microsoft/vscode/files/10946228/symbolicated-2e.log)
[symbolicated-c8.log](https://github.com/microsoft/vscode/files/10946230/symbolicated-c8.log)

For 2e, the crash seems to come from a GPU fail: `code-insiders!content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess(
)`
For c8, the crash seems to come from vscode-sqlite3, but I don't know how to obtain symbols for it.

**Comment by deepak1556** [comment]
Closing as crash has not been seen since Electron 25 update.
