### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by Nikba-Creative-Studio** [microsoft/vscode#176624]
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes.

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.15GB free)|
|Process Argv|--crash-reporter-id 0e74b731-9fbe-4e48-bb6a-0a50b438cd38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
pug|ama|1.0.1
vscode-twig-pack|baj|1.1.0
phpserver|bra|3.0.2
simple-react-snippets|bur|1.2.7
react-redux-react-router-snippets|dis|0.4.29
es7-react-js-snippets|dsz|4.4.3
vscode-npm-script|eg2|0.3.29
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot|Git|1.77.9225
live-sass|gle|6.0.3
php-snippets|heb|0.0.3
beautify|Hoo|1.5.0
ftp-simple|hum|0.7.6
path-autocomplete|ion|1.23.1
twig-language-2|mbl|0.9.2
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
vscode-typescript-tslint-plugin|ms-|1.3.4
sftp|Nat|1.16.1
vetur|oct|0.37.3
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.7.9
code-snapshot|rob|0.2.1
vscode-sass-format|sas|1.1.7
js-jsx-snippets|sky|11.0.1
sass-indented|syl|1.8.26
vscode-icons|vsc|12.2.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
php-debug|xde|1.32.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
funwalk2cf:30676044

```

</details>

**Comment by JonathanMSifleet** [comment]
I am getting the same issue since the update the other day.

**Comment by Nikba-Creative-Studio** [comment]
It seems that the issue is related to using the copilot extension.
It is possible that this could be a temporary problem.

**Comment by leonardonadin** [comment]
Same problem, checked with Bisect and for me its Copilot too

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by leonardonadin** [comment]
I follow the steps and cant found any .dmp file, just this:
/attachments (empty)
/reports (empty)
settings.dat

How reproduce:
Using Copilot looks like it fails and then seems all extensions are reloaded

Using:
WSL: 1.1.3.0
Windows: 10.0.22621.1265
VSCode: 1.76.0
Github Copilot: v1.77.9225

I found this on logs (Developer: Show Logs... > Window):
2023-03-09 13:59:46.395 [info] [remote-connection][ExtensionHost][221d8…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-03-09 13:59:46.395 [error] {"isTrusted":true}
2023-03-09 13:59:46.395 [info] [remote-connection][ExtensionHost][221d8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-03-09 13:59:46.395 [info] [remote-connection][ExtensionHost][221d8…][reconnect] resolving connection...
2023-03-09 13:59:46.395 [info] [remote-connection][ExtensionHost][221d8…][reconnect] connecting to 127.0.0.1:56862...
2023-03-09 13:59:46.396 [info] Creating a socket (renderer-ExtensionHost-221d89f9-70d2-404f-83db-2980228ade9a)...
2023-03-09 13:59:46.529 [info] Creating a socket (renderer-ExtensionHost-221d89f9-70d2-404f-83db-2980228ade9a) was successful after 134 ms.
2023-03-09 13:59:46.541 [error] [remote-connection][ExtensionHost][221d8…][reconnect][127.0.0.1:56862] received error control message when negotiating connection. Error:
2023-03-09 13:59:46.541 [error] Error: Connection error: Unknown reconnection token (seen before)
    at $ (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:58150)
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:48775
    at g.invoke (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at a.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:15221)
    at E (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:19321)
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:18466
    at g.invoke (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at f.acceptChunk (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12952)
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12239
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:38972
    at g.invoke (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at i.onload (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:37239)
2023-03-09 13:59:46.542 [error] [remote-connection][ExtensionHost][221d8…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
2023-03-09 13:59:46.542 [error] Error: Connection error: Unknown reconnection token (seen before)
    at $ (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:58150)
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:48775
    at g.invoke (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at a.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:15221)
    at E (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:19321)
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:18466
    at g.invoke (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at f.acceptChunk (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12952)
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12239
    at vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:38972
    at g.invoke (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at i.onload (vscode-file://vscode-app/c:/Users/leona/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:37239)
2023-03-09 13:59:46.590 [error] Extension host (Remote) terminated unexpectedly with code 7.
2023-03-09 13:59:46.590 [error] Extension host (Remote) terminated unexpectedly. The following extensions were running: vscode.emmet, mechatroner.rainbow-csv, Vue.volar, vscode.php-language-features, amiralizadeh9480.laravel-extra-intellisense, bmewburn.vscode-intelephense-client, codingyu.laravel-goto-view, glitchbl.laravel-create-view, vscode.git-base, redhat.vscode-yaml, EditorConfig.EditorConfig, IHunte.laravel-blade-wrapper, WakaTime.vscode-wakatime, vscode.npm, vscode.git, vscode.github, ryannaddy.laravel-artisan, redhat.fabric8-analytics, atlassian.atlascode, vscode.configuration-editing, vscode.json-language-features, vscode.typescript-language-features, rvest.vs-code-prettier-eslint, streetsidesoftware.code-spell-checker, vscode.debug-auto-launch, vscode.merge-conflict, esbenp.prettier-vscode, GitHub.copilot, ms-vsliveshare.vsliveshare, streetsidesoftware.code-spell-checker-portuguese-brazilian, naoray.laravel-goto-components, onecentlin.laravel-blade, shufo.vscode-blade-formatter


Hope this helps, if I help with anything else let me know.

**Comment by leonardonadin** [comment]
Today i tried investigating again and (at least for me) the problem can be related with PHP available for Copilot.
I use asdf and for PHP haven't set a global version (in logs i see "[error] No version is set for command php" repeated message). But with Nodejs, Python and Go this error message does not occur (have their global versions defined).
Setting global version for PHP in asdf then Copilot stopped failing. I don't know exactly, maybe Copilot is executed in another folder who doesn't have PHP defined.
I will keep monitoring.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/176562
