### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by BAKHYOGYEONG** [microsoft/vscode#177035]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.9.5

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
RangeError: Maximum call stack size exceeded
    at Object.parseJSDocComment (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:38307:43)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32478:123
    at Object.mapDefined (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:621:30)
    at addJSDocComment (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32478:28)
    at withJSDoc (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32473:31)
    at parseFunctionDeclaration (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:37408:20)
    at parseStatement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:37112:28)
    at parseListElement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33524:20)
    at parseList (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33509:31)
    at parseBlock (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36667:34)
    at parseStatement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:37103:28)
    at parseIfStatement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36717:33)
    at parseStatement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:37116:28)
    at parseIfStatement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36718:82)
    at parseStatement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:37116:28)
    at parseListElement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33524:20)
    at parseList (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33509:31)
    at parseBlock (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36667:34)
    at parseFunctionBlock (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36694:25)
    at parseFunctionExpression (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36630:24)
    at parsePrimaryExpression (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36501:28)
    at parseMemberExpressionOrHigher (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35979:30)
    at parseLeftHandSideExpressionOrHigher (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35923:103)
    at parseUpdateExpression (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35858:30)
    at parseUnaryExpressionOrHigher (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35733:40)
    at parseBinaryExpressionOrHigher (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35605:31)
    at parseAssignmentExpressionOrHigher (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35195:24)
    at parseAssignmentExpressionOrHigher (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:35209:69)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36589:67
    at doOutsideOfContext (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32651:20)
    at allowInAnd (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32673:20)
    at parseObjectLiteralElement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36589:35)
    at parseListElement (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33524:20)
    at parseDelimitedList (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33828:34)
    at parseObjectLiteralExpression (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:36604:30)
    at Object.parseJsonText (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32343:44)
    at Object.parseJsonText (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32102:23)
    at Object.parseConfigFileTextToJson (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41749:33)
    at readJsonOrUndefined (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19533:25)
    at Object.readJson (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19538:16)
    at getPackageJsonInfo (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44782:41)
    at loadNodeModuleFromDirectory (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44631:49)
    at nodeLoadModuleByRelativeName (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44453:20)
    at tryResolve (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44390:34)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44353:69
    at Object.forEach (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:191:30)
    at nodeModuleNameResolverWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44353:25)
    at nodeModuleNameResolver (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44323:16)
    at Object.resolveModuleName (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:44050:30)
    at resolveModuleName (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124225:36)
    at resolveNamesWithLocalCache (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124311:38)
    at Object.resolveModuleNames (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124389:20)
    at Project.resolveModuleNames (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173642:45)
    at actualResolveModuleNamesWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119374:153)
    at resolveModuleNamesWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119677:26)
    at resolveModuleNamesReusingOldState (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119775:24)
    at processImportedModules (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121306:35)
    at findSourceFileWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121086:17)
    at findSourceFile (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120932:26)
    at processImportedModules (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121341:25)
    at findSourceFileWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121086:17)
    at findSourceFile (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120932:26)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120881:85
    at getSourceFileFromReferenceWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120847:34)
    at processSourceFile (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120881:13)
    at processRootFile (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120682:13)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119483:67
    at Object.forEach (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:191:30)
    at Object.createProgram (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119483:16)
    at synchronizeHostData (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168926:26)
    at Object.getProgram (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169040:13)
    at Project.updateGraphWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174217:53)
    at Project.updateGraph (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174145:42)
    at ConfiguredProject.updateGraph (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:175311:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177044:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178129:44)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178469:97
    at Object.flatMap (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178469:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179841:46)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182034:96
    at Session.executeWithRequestId (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182025:28)
    at Session.executeCommand (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182034:41)
    at Session.onMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182062:35)
    at process.<anonymous> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:186218:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, please share an example file which causes this issue
