### ISSUE TITLE
Auto-import of import suggestion does not work. TypeScript Server Error.

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#177244]
I'm on an Ionic/Angular (v14) project and simply trying to import e.g. `FormArray`. I'm not sure if this is a VS Code issue or [TypeScript](https://github.com/microsoft/TypeScript) bug. I just tired of this and want to find out. A workaround is to restart VSCode. But that doesn't fix it for long. A few minutes later, I've this behavior again. I type e.g. `FormArray` and select the entry of the IntelliSense suggestions to import. But nothing work. No feedback / no error. But the dev tools console of VS Code shows the following. I hope this helps to either fix it or decide if this is somewhat for the TypeScript issue tracker.

<details>
  <summary>Console log error (click to view)</summary>
  
  ```
ERR <semantic> TypeScript Server Error (4.9.5)
Debug Failure.
Error: Debug Failure.
    at Object.getImportCompletionAction (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156503:22)
    at getCompletionEntryCodeActionsAndSourceDisplay (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:136327:33)
    at Object.getCompletionEntryDetails (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:136266:30)
    at getCompletionEntryDetails (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169156:35)
    at c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8356
    at l.getCompletionEntryDetails (c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8456)
    at c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8356
    at l.getCompletionEntryDetails (c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8456)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181347:57
    at Object.mapDefined (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:621:30)
    at Session.getCompletionEntryDetails (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181345:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179982:61)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182034:96
    at Session.executeWithRequestId (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182025:28)
    at Session.executeCommand (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182034:41)
    at Session.onMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182062:35)
    at process.<anonymous> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:186218:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21): Error: <semantic> TypeScript Server Error (4.9.5)
Debug Failure.
Error: Debug Failure.
    at Object.getImportCompletionAction (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156503:22)
    at getCompletionEntryCodeActionsAndSourceDisplay (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:136327:33)
    at Object.getCompletionEntryDetails (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:136266:30)
    at getCompletionEntryDetails (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169156:35)
    at c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8356
    at l.getCompletionEntryDetails (c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8456)
    at c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8356
    at l.getCompletionEntryDetails (c:\Users\user\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8456)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181347:57
    at Object.mapDefined (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:621:30)
    at Session.getCompletionEntryDetails (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181345:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179982:61)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182034:96
    at Session.executeWithRequestId (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182025:28)
    at Session.executeCommand (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182034:41)
    at Session.onMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182062:35)
    at process.<anonymous> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:186218:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
	at c.h (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:109138)
  ```
</details>

This bug exists since years. But not sure if always the same reason/error. Let me know if you need more info.

Version: 1.76.1 (user setup)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Closing for now but if you see this again, please try collecting the TS Server logs so we can investigate. To do this:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
