### ISSUE TITLE
Can not open jupyter notebook file in remote

### ISSUE THREAD

**Issue by Yikai-coder** [microsoft/vscode#177379]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I try to open a `.ipynb` file in remote, but the file kept loading and can not open. 
But when I try to open a `.ipynb` file locally, the remote file can also open simultaneously.

https://user-images.githubusercontent.com/54537903/225573057-6cb0fe1b-3bf5-40aa-bb48-ccf0b0a1096e.mp4

### VS Code Version

1.76.2

### Jupyter Extension Version

v2023.3.1000762246

### Jupyter logs

```shell
Visual Studio Code (1.76.2, ssh-remote, desktop)
Jupyter Extension Version: 2023.3.1000762246.
Python Extension Version: 2023.4.1.
Workspace folder /home/li/data/power/pvcompete
warn 16:16:21.455: Exception while attempting zmq : /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/li/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/out/node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node)
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 16:16:21.744: Attempting to start a server because of preload conditions ...
info 16:16:21.760: LSP Notebooks experiment is enabled
info 16:16:21.789: Checking for server existence.
warn 16:16:23.359: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.361: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.361: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.362: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.363: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.403: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.404: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.405: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.405: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.406: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.407: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.407: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
warn 16:16:23.408: No interpreter with path /usr/bin/python3 found in Python API, will convert Uri path to string as Id file:///usr/bin/python3
info 16:16:23.850: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/miniconda3/envs/ai_lab/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 16:16:23.955: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -m pip list
> ~/miniconda3/envs/ai_lab/bin/python -m pip list
info 16:16:23.976: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/miniconda3/envs/ai_lab/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 16:16:24.025: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -m jupyter kernelspec --version
> ~/miniconda3/envs/ai_lab/bin/python -m jupyter kernelspec --version
info 16:16:24.237: Connecting to server
info 16:16:24.237: Launching server
info 16:16:24.239: Starting Notebook
info 16:16:24.245: Generating custom default config at /tmp/48d21820-c808-497c-874d-57ca00018c73/jupyter_notebook_config.py
Starting Jupyter from ~/miniconda3/envs/ai_lab/bin/python with arguments --no-browser --notebook-dir="/home/li/data/power/pvcompete" --config=/tmp/48d21820-c808-497c-874d-57ca00018c73/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 16:16:24.277: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -m jupyter notebook --no-browser --notebook-dir="/home/li/data/power/pvcompete" --config=/tmp/48d21820-c808-497c-874d-57ca00018c73/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~/miniconda3/envs/ai_lab/bin/python -m jupyter notebook --no-browser --notebook-dir="/home/li/data/power/pvcompete" --config=/tmp/48d21820-c808-497c-874d-57ca00018c73/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
/home/li/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2389: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/li/data/power/pvcompete' instead of '"/home/li/data/power/pvcompete"' if you require traitlets >=5.
  warn(
[I 16:16:24.953 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:16:24.954 NotebookApp] Serving notebooks from local directory: /home/li/data/power/pvcompete
[I 16:16:24.954 NotebookApp] Jupyter Notebook 6.4.11 is running at:
[I 16:16:24.954 NotebookApp] http://localhost:8889/?token=1cb5d3a22387321c770f6114f994da4dcd5e4e3ae8624ee5
[I 16:16:24.954 NotebookApp]  or http://127.0.0.1:8889/?token=1cb5d3a22387321c770f6114f994da4dcd5e4e3ae8624ee5
[I 16:16:24.954 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 16:16:24.976: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/miniconda3/envs/ai_lab/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[C 16:16:24.956 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/li/.local/share/jupyter/runtime/nbserver-76302-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=1cb5d3a22387321c770f6114f994da4dcd5e4e3ae8624ee5
     or http://127.0.0.1:8889/?token=1cb5d3a22387321c770f6114f994da4dcd5e4e3ae8624ee5
info 16:16:25.005: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/miniconda3/envs/ai_lab/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 16:16:25.557: Connecting local server kernel http://localhost:8889/
info 16:16:25.558: Creating server with url : http://localhost:8889/
info 16:16:25.586: Server started.
info 16:17:00.772: Ending debug session 5c4523b6-5e93-41da-b915-cc40c4b707e0
info 16:17:00.772: Ending debug session 5c4523b6-5e93-41da-b915-cc40c4b707e0
info 16:37:37.871: Ending debug session 949d5dcd-71e3-47c7-9a3a-aabbd11baeee
info 16:37:37.871: Ending debug session 949d5dcd-71e3-47c7-9a3a-aabbd11baeee
info 16:51:49.167: Ending debug session b5b5b664-e258-4a18-892e-303b6a3bcbc0
info 16:51:49.167: Ending debug session b5b5b664-e258-4a18-892e-303b6a3bcbc0
info 16:52:27.755: Ending debug session faa0b428-dbcd-4b38-8cae-1f74d9e31ad7
info 16:52:27.755: Ending debug session faa0b428-dbcd-4b38-8cae-1f74d9e31ad7
info 16:54:10.416: Ending debug session 518ac930-6faf-42f6-987b-4360fafb3ba1
info 16:54:10.416: Ending debug session 518ac930-6faf-42f6-987b-4360fafb3ba1
info 16:54:33.672: Attempting to start a server because of preload conditions ...
info 16:54:33.700: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd00ceb20c7a23b156221f8b7fca236cb052527d962cc0712ab4813e02736225f49./home/li/miniconda3/envs/ai_lab/python./home/li/miniconda3/envs/ai_lab/python.-m#ipykernel_launcher (Python Path: /home/li/miniconda3/envs/ai_lab, EnvType: Conda, EnvName: 'ai_lab', Version: 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0]) for '/home/li/data/power/pvcompete/test.ipynb' (disableUI=true)
[I 16:54:33.743 NotebookApp] Creating new notebook in 
info 16:54:34.023: installMissingDependencies /home/li/miniconda3/envs/ai_lab/bin/python, ui.disabled=true for resource '/home/li/data/power/pvcompete/test.ipynb'
info 16:54:34.726: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -m pip list
> ~/miniconda3/envs/ai_lab/bin/python -m pip list
info 16:54:35.171: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/miniconda3/envs/ai_lab/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
[I 16:54:35.403 NotebookApp] Kernel started: 44e946ca-903e-47a9-836a-3d4004795cee, name: pythonjvsc74a57bd00ceb20c7a23b156221f8b7fca236cb052527d962cc0712ab4813e02736225f49
[W 16:54:35.428 NotebookApp] delete /test-jvsc-240e3362-d0be-46b1-9b54-6d3312a10214839a66b6-0ae5-4b74-8b10-fd147ce573fa.ipynb
info 16:54:36.051: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd00ceb20c7a23b156221f8b7fca236cb052527d962cc0712ab4813e02736225f49./home/li/miniconda3/envs/ai_lab/python./home/li/miniconda3/envs/ai_lab/python.-m#ipykernel_launcher
info 16:54:36.212: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/pythonFiles/printJupyterDataDir.py
> ~/miniconda3/envs/ai_lab/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/pythonFiles/printJupyterDataDir.py
info 16:57:56.804: Starting interactive window for resource 'Untitled-1' with controller '.jvsc74a57bd00ceb20c7a23b156221f8b7fca236cb052527d962cc0712ab4813e02736225f49./home/li/miniconda3/envs/ai_lab/python./home/li/miniconda3/envs/ai_lab/python.-m#ipykernel_launcher (Interactive)'
info 16:57:56.902: Attempting to start a server because of preload conditions ...
info 16:57:57.208: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd00ceb20c7a23b156221f8b7fca236cb052527d962cc0712ab4813e02736225f49./home/li/miniconda3/envs/ai_lab/python./home/li/miniconda3/envs/ai_lab/python.-m#ipykernel_launcher (Python Path: /home/li/miniconda3/envs/ai_lab, EnvType: Conda, EnvName: 'ai_lab', Version: 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0]) for '/Interactive-1.interactive' (disableUI=false)
[I 16:57:57.218 NotebookApp] Creating new notebook in 
info 16:57:57.623: installMissingDependencies /home/li/miniconda3/envs/ai_lab/bin/python, ui.disabled=false for resource 'Untitled-1'
info 16:57:57.656: Process Execution: > ~/miniconda3/envs/ai_lab/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/miniconda3/envs/ai_lab/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
[I 16:57:58.725 NotebookApp] Kernel started: 4b74e91a-41fa-464f-bb15-2c7341d8e7fd, name: pythonjvsc74a57bd00ceb20c7a23b156221f8b7fca236cb052527d962cc0712ab4813e02736225f49
[W 16:57:58.760 NotebookApp] delete /Untitled-1-jvsc-8af50554-9508-4619-8b6a-37584b1e3ec99d969513-a536-40c2-8baf-58316f50193c.ipynb
info 16:57:59.302: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd00ceb20c7a23b156221f8b7fca236cb052527d962cc0712ab4813e02736225f49./home/li/miniconda3/envs/ai_lab/python./home/li/miniconda3/envs/ai_lab/python.-m#ipykernel_launcher
info 16:58:16.877: Generated code for 1 = <ipython-input-1-c4d0ec3982b3> with 3 lines
info 16:58:16.891: start debugging
info 16:58:16.891: enable debugger attach
info 16:58:16.908: Appending paths: undefined
info 16:58:17.169: connected to notebook during debugging
info 16:58:17.446: import startup: undefined
info 16:58:21.432: Dispose Kernel '/Interactive-1.interactive' associated with 'Untitled-1'
info 16:58:21.458: Dispose Kernel '/Interactive-1.interactive' associated with 'Untitled-1'
info 16:58:21.463: Cancel all remaining cells true || Idle || undefined
[I 16:58:21.474 NotebookApp] Kernel shutdown: 4b74e91a-41fa-464f-bb15-2c7341d8e7fd
error 16:58:22.290: Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (/home/li/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/out/extension.node.js:2:32419)
    at s.onIOPub (/home/li/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/out/extension.node.js:24:6334)
    at t.KernelShellFutureHandler._handleIOPub (/home/li/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/out/extension.node.js:2:33111)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.KernelShellFutureHandler.handleMsg (/home/li/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/out/extension.node.js:2:32763)
    at v._handleMessage (/home/li/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000762246/out/extension.node.js:2:28728)
warn 16:58:22.292: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
warn 16:58:22.294: Unhandled message found: execute_reply
[I 16:58:22.460 NotebookApp] Starting buffering for 4b74e91a-41fa-464f-bb15-2c7341d8e7fd:36542cb2-0ecb-4657-8efc-c1821c0bc05b
info 16:58:22.607: Ending debug session de9acf28-986b-4204-8ea1-8ecef0f34f89
info 16:58:22.608: Ending debug session de9acf28-986b-4204-8ea1-8ecef0f34f89
```

### Coding Language and Runtime Version

Python 3.8.13

### Anaconda Version (if applicable)

conda 22.11.0

### Running Jupyter locally or remotely?

Remote

**Comment by rebornix** [comment]
@Yikai-coder can you please help follow below steps to capture more logs for us

* Open Output Panel, switch to Window channel
* Clear the outputs
* F1 -> Developer: Set Log Level, change it to Trace
* Try open the notebook

Wait for a couple of seconds, and then copy the logs in the Output channel with us. Thanks in advance!

**Comment by mjbvz** [comment]
Duplicate of #166860

@Yikai-coder Does your ssh config file happen to contain any non-english characters, specifically in the hostname?

**Comment by Yikai-coder** [comment]
> Duplicate of #166860
> 
> @Yikai-coder Does your ssh config file happen to contain any non-english characters, specifically in the hostname?

Thank you, moving away all the non-English character in ssh config file can solve the problem.
