### ISSUE TITLE
SSH Agent Forwarding broken in terminal after upgrade to 1.76.2

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [microsoft/vscode#177368]
Does this issue occur when all extensions are disabled?: yes, all but ms-vscode-remote.vscode-remote-extensionpack

- VS Code Version: 
```
Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```
- OS Version: 
  - Local: `macOS Monterey 12.6 (21G115)` 
  - Remote: `Debian GNU/Linux 11 (bullseye)`

Config:
* agent forwarding is enabled in Code
* `ForwardAgent yes` is set in .ssh/config (local machine)

Steps to Reproduce:

1. Use vs code git integration to pull from a repository over ssh (works) 
2. Try using git or ssh directly in the terminal - doesn't work, agent has no identities

Things tried:
* triggered reconnecting, reloading the window, restarting the remote machine - no luck
* downgrading Code to `Version: 1.75.1 Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf` - works

Might be connected to https://github.com/microsoft/vscode/issues/177193

**Comment by lszomoru** [comment]
@Tyriar, @meganrogge could one of you please take a look? Thanks!

**Comment by eleanorjboyd** [comment]
@meganrogge, Im not sure I didn't think so either. @tomasz-sodzawiczny could you include logs from the remote-ssh and extension output? You can find the logs by going to `view` in the menu bar, then selecting `output`, and finally once the bottom window pops up select  `remote-ssh` from the dropdown on the right (and select windows to include extension host logs). Thanks!

**Comment by Redoubts** [comment]
contemporaneous window log:

```
2023-03-28 11:00:51.211 [info] Invoking resolveAuthority(ssh-remote)...
2023-03-28 11:00:51.212 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2023-03-28 11:00:51.212 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
2023-03-28 11:00:51.303 [error] [Extension Host] (node:18210) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
2023-03-28 11:00:51.309 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][97ms] returned 127.0.0.1:63958
2023-03-28 11:00:51.309 [info] resolveAuthority(ssh-remote) returned '127.0.0.1:63958' after 98 ms
2023-03-28 11:00:51.310 [info] Creating a socket (renderer-Management-19cd16a7-5c7b-4264-a302-e7f099c229ff)...
2023-03-28 11:00:51.311 [info] Creating a socket (renderer-ExtensionHost-74ae037e-fc99-4691-8873-bf3e254f5e31)...
2023-03-28 11:00:51.333 [info] Creating a socket (renderer-Management-19cd16a7-5c7b-4264-a302-e7f099c229ff) was successful after 23 ms.
2023-03-28 11:00:51.358 [info] Creating a socket (renderer-ExtensionHost-74ae037e-fc99-4691-8873-bf3e254f5e31) was successful after 46 ms.
2023-03-28 11:00:51.780 [warning] [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2023-03-28 11:00:52.273 [error] No terminal backend registered for remote authority 'ssh-remote+$COLO-$USER1': Error: No terminal backend registered for remote authority 'ssh-remote+$COLO-$USER1'
    at P.createProcess (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:20321)
    at async Ki.Sc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2519:4945)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2517:33069
2023-03-28 11:00:52.451 [error] Cannot get default system shell when there is no backend for remote authority 'ssh-remote+$COLO-$USER1': Error: Cannot get default system shell when there is no backend for remote authority 'ssh-remote+$COLO-$USER1'
    at Object.getDefaultSystemShell (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1702:6416)
    at async i.v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:18520)
    at async i.r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:17783)
    at async i.getDefaultProfile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:17114)
    at async i.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:15825)
2023-03-28 11:00:52.492 [error] Cannot get default system shell when there is no backend for remote authority 'ssh-remote+$COLO-$USER1': Error: Cannot get default system shell when there is no backend for remote authority 'ssh-remote+$COLO-$USER1'
    at Object.getDefaultSystemShell (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1702:6416)
    at async i.v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:18520)
    at async i.r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:17783)
    at async i.getDefaultProfile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:17114)
    at async Promise.all (index 0)
    at async a.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1694:46700)
2023-03-28 11:00:55.138 [info] [perf] Render performance baseline is 39ms
```

**Comment by eleanorjboyd** [comment]
@Tyriar and @meganrogge I am seeing this in the logs which I have seen come up in past terminal issues:
`2023-03-28 11:00:52.273 [error] No terminal backend registered for remote authority 'ssh-remote+$COLO-$USER1': Error: No terminal backend registered for remote authority 'ssh-remote+$COLO-$USER1'`

**Comment by Redoubts** [comment]
Also, since I saw it again today (with logs at this pastebin, but there's nothing new https://pastebin.com/8czqT1GM), I see

`[10:07:49.952] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1808/vscode-ssh-auth-sock-441265074"}`, which is also in the `env`. But that symlink no longer exists `ls: cannot access '/run/user/1808/vscode-ssh-auth-sock-441265074': No such file or directory`. Presumably this extension should be re-establishing a connection in this condition? In this case, this was first thing in the morning after waking from suspend.


There seem to be plenty of others for some reason...

```
% ls -l /run/user/1808/vscode-ssh-auth-sock-*        
lrwxrwxrwx 1 $USER users 31 Mar 28 18:45 /run/user/1808/vscode-ssh-auth-sock-116089242 -> /tmp/ssh-eOThVVz0pW/agent.87315
lrwxrwxrwx 1 $USER users 31 Mar 29 10:08 /run/user/1808/vscode-ssh-auth-sock-13876616 -> /tmp/ssh-8Guf9BjcDR/agent.67102
lrwxrwxrwx 1 $USER users 31 Mar 29 10:10 /run/user/1808/vscode-ssh-auth-sock-172462719 -> /tmp/ssh-8Guf9BjcDR/agent.67102
lrwxrwxrwx 1 $USER users 31 Mar 28 19:41 /run/user/1808/vscode-ssh-auth-sock-231123099 -> /tmp/ssh-z5zhkcOBxm/agent.80699
lrwxrwxrwx 1 $USER users 31 Mar 29 10:08 /run/user/1808/vscode-ssh-auth-sock-237667389 -> /tmp/ssh-8Guf9BjcDR/agent.67102
lrwxrwxrwx 1 $USER users 31 Mar 28 17:00 /run/user/1808/vscode-ssh-auth-sock-368378646 -> /tmp/ssh-eOThVVz0pW/agent.87315
lrwxrwxrwx 1 $USER users 31 Mar 28 10:19 /run/user/1808/vscode-ssh-auth-sock-402271406 -> /tmp/ssh-eOThVVz0pW/agent.87315
lrwxrwxrwx 1 $USER users 31 Mar 28 19:31 /run/user/1808/vscode-ssh-auth-sock-461934916 -> /tmp/ssh-z5zhkcOBxm/agent.80699
lrwxrwxrwx 1 $USER users 31 Mar 28 18:24 /run/user/1808/vscode-ssh-auth-sock-65026639 -> /tmp/ssh-eOThVVz0pW/agent.87315
lrwxrwxrwx 1 $USER users 31 Mar 27 21:32 /run/user/1808/vscode-ssh-auth-sock-800436374 -> /tmp/ssh-8zilTIrIo3/agent.49206
lrwxrwxrwx 1 $USER users 31 Mar 27 21:32 /run/user/1808/vscode-ssh-auth-sock-976009991 -> /tmp/ssh-8zilTIrIo3/agent.49206
lrwxrwxrwx 1 $USER users 31 Mar 28 17:33 /run/user/1808/vscode-ssh-auth-sock-9877332 -> /tmp/ssh-eOThVVz0pW/agent.87315
```

**Comment by eleanorjboyd** [comment]
One note on https://github.com/microsoft/vscode-remote-release/issues/8263 is that it does work occasionally if that provides any extra context.

**Comment by eleanorjboyd** [comment]
useful comment on [an issue dup](https://github.com/microsoft/vscode-remote-release/issues/8278#issuecomment-1493757744) of this problem was that:

"agent forwarding itself actually works great.  It's the terminal window restoration part that needs to make sure that SSH_AUTH_SOCK gets updated with the new socket path." from @florisvdg

**Comment by iraadit** [comment]
Workaround that worked for me :

```
SSH_AUTH_SOCK=$(ls -td /tmp/ssh**/* | head -n1)
ssh-add -l
``

**Comment by pragmatiker** [comment]
Can confirm same problem.
Terminal restored from previous session will not have the correct symlink to SSH_AUTH_SOCK
A newly spawned terminal works fine.
