### ISSUE TITLE
The extension host reports an error

### ISSUE THREAD

**Issue by llkeji** [microsoft/vscode#177320]
```
2023-03-16 13:39:13.731 [error] TypeError: Cannot read properties of undefined (reading 'dispose')
    at App.dispose (D:\.vscode\extensions\shenjiaolong.vue-helper-2.4.7\out\src\app.js:860:26)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
2023-03-16 13:39:13.735 [warning] {"name":"Canceled"}
2023-03-16 13:39:13.736 [warning] {"name":"Canceled"}
2023-03-16 13:39:13.737 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at D (e:\exe\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1467127)
    at f.invoke (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at m.deliver (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2066)
    at d.fire (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1704)
    at Object.m [as dispose] (e:\exe\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1481856)
    at e:\exe\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1485923
    at Array.forEach (<anonymous>)
    at g.dispose (e:\exe\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1485909)
    at C.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:12431)
    at C.dispose (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:12566)
    at C.<anonymous> (e:\exe\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1469257)
    at C.dispose (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:12566)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-16 13:39:13.743 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at c (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:978258)
    at ActionRunners._updateContextKeys (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:7346)
    at r (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5765)
    at RegisteredActionRunner.unregister (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5909)
    at RegisteredActionRunner.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:4574)
    at ActionRunners.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5351)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-16 13:39:13.743 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at c (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:978258)
    at ActionRunners._updateContextKeys (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:7346)
    at r (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5765)
    at RegisteredActionRunner.unregister (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5909)
    at RegisteredActionRunner.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:4574)
    at ActionRunners.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5351)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-16 13:39:13.743 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at c (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:978258)
    at ActionRunners._updateContextKeys (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:7346)
    at r (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5765)
    at RegisteredActionRunner.unregister (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5909)
    at RegisteredActionRunner.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:4574)
    at ActionRunners.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5351)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-16 13:39:13.744 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at c (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:978258)
    at ActionRunners._updateContextKeys (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:7346)
    at r (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5765)
    at RegisteredActionRunner.unregister (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5909)
    at RegisteredActionRunner.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:4574)
    at Object.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:6006)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-16 13:39:13.744 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at c (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:978258)
    at ActionRunners._updateContextKeys (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:7346)
    at r (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5765)
    at RegisteredActionRunner.unregister (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5909)
    at RegisteredActionRunner.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:4574)
    at Object.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:6006)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-16 13:39:13.745 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at c (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:978258)
    at ActionRunners._updateContextKeys (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:7346)
    at r (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5765)
    at RegisteredActionRunner.unregister (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:5909)
    at RegisteredActionRunner.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:4574)
    at Object.dispose (D:\.vscode\extensions\eamodio.gitlens-13.3.2\dist\gitlens.js:1:6006)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-16 13:39:13.746 [error] Canceled: Canceled
    at new l (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:88793)
    at a.O (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11260)
    at Proxy.V.<computed>.Q.charCodeAt.V.<computed> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:8550)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108198)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at N.registerCommand.description (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106867)
    at c.h (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
    at c.g (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
    at c.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
    at Object.executeCommand (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
    at Object.dispose (D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:72826)
    at D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:13435
    at Array.forEach (<anonymous>)
    at t.exports.dispose (D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:13422)
    at P.deactivate (D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:74093)
    at Object.dispose (D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:1096)
    at D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:13435
    at Array.forEach (<anonymous>)
    at t.exports.dispose (D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:13422)
    at h.deactivate (D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:3331)
    at Object.dispose (D:\.vscode\extensions\wallabyjs.quokka-vscode-1.0.528\dist\index.js:6:3406)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
```

**Comment by alexdima** [comment]
The `Canceled` errors are not real errors. The only real remaining stack is:

```
2023-03-16 13:39:13.731 [error] TypeError: Cannot read properties of undefined (reading 'dispose')
    at App.dispose (D:\.vscode\extensions\shenjiaolong.vue-helper-2.4.7\out\src\app.js:860:26)
    at k (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12074)
    at f.X (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11284)
    at e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9088
    at Array.map (<anonymous>)
    at f.Q (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9075)
    at f.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9347)
    at u.terminate (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:112:1397)
    at p (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:18592)
    at MessagePortMain.<anonymous> (e:\exe\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14731)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
```

This is an exception with the `shenjiaolong.vue-helper-2.4.7` extension.
