### ISSUE TITLE
Unable to read file 'vscode-userdata:/User/argv.json' 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#177531]
```
Error: Unable to read file 'vscode-userdata:/User/argv.json' (Error: Unable to resolve nonexistent file 'vscode-userdata:/User/argv.json')
    at o.w (workbench.web.main.js:612:16435)
    at o.v (workbench.web.main.js:612:16097)
    at async o.u (workbench.web.main.js:612:15379)
    at async C.h (workbench.web.main.js:1209:3485)
    at async C.getDefaultLogLevels (workbench.web.main.js:1209:2455)
    at async f.k (workbench.web.main.js:1700:32903)
    at async f.run (workbench.web.main.js:1700:32800)
    at async Object.accept (workbench.web.main.js:741:8127)
```

**Comment by sandy081** [comment]
When and where are you seeing this? Can you please provide more information and also steps to reproduce?
