### ISSUE TITLE
Cannot create new jupyter notebook

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177852]
Testing #177719

I was using this command to create a test notebook:

<img width="160" alt="image" src="https://user-images.githubusercontent.com/2193314/226695315-8da91126-c030-4e8f-b455-19fedb118bdf.png">

After playing with the `notebook.experimental.outputScrolling` setting a bit, I set it to false, closed my notebook and tried to create a new one and it fails consistently now with this error:

```
  ERR NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook': Error: NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
    at h.getNotebookDocument (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:86012)
    at l.$acceptDirtyStateChanged (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:15654)
    at c.N (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11655)
    at c.M (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11373)
    at c.H (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:10454)
    at c.G (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9432)
    at c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:8220
    at E.invoke (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at h.deliver (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
    at n.fire (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
    at p.fire (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14916)
    at c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:124:16654
    at E.invoke (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at h.deliver (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
    at n.fire (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
    at p.fire (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14916)
    at MessagePortMain.<anonymous> (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:124:14780)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
workbench.desktop.main.js:620   ERR NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook': Error: NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
    at m.h (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:126151)
```

Commenting out the setting doesn't fix it so I'm reloading.

**Comment by amunger** [comment]
I don't think this is due to the setting. More likely the `NotebookEditorModelResolverService` got into a bad state

**Comment by amunger** [comment]
likely fixed, I haven't seen any other issues on this.
