### ISSUE TITLE
'this.b.extensions is not iterable' on opening welcome page

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#177945]
Testing #177702

Not sure if actually caused by #177702

1. Open welcome page

**bug**
In dev tools, see:

```
this.b.extensions is not iterable: TypeError: this.b.extensions is not iterable
    at Or.l (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1199:3608)
    at async Or.getExtensions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1199:2961)
```

**Comment by bhavyaus** [comment]
I can't repro this on my mac. 
Please feel free to reopen this issue if you see this again on your machine.

**Comment by mjbvz** [comment]
Yes I still see this every time I open the welcome page. Maybe it's because of an extension I have installed that is getting parsed oddly or an experiment?

The exception is thrown here:

https://github.com/microsoft/vscode/blob/beb23739aa5fbb011124a39df83171fe4cbf51be/src/vs/workbench/contrib/welcomeGettingStarted/browser/featuredExtensionService.ts#L102
