### ISSUE TITLE
Ctrl+Shift+M broken

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1783]
Showing errors is broken in latest. Executing it results in 
```
[11348:0105/100024:INFO:CONSOLE(331)] "Cannot read property 'getControl' of undefined: TypeError: Cannot read property 'getControl' of undefined
    at MarkersHandler.getResults (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/quickopen/browser/markersHandler.js:137:39)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:551:40
    at Promise_ctor.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1826:49)
    at QuickOpenController.handleSpecificHandler (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:530:59)
    at QuickOpenController.onType (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:438:38)
    at Object.quickOpenWidget.quickOpenWidget_1.QuickOpenWidget.onType (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:324:61)
    at QuickOpenWidget.doShowWithPrefix (file:///P:/mseng/VSCode/vscode/out/vs/base/parts/quickopen/browser/quickOpenWidget.js:367:28)
    at QuickOpenWidget.show (file:///P:/mseng/VSCode/vscode/out/vs/base/parts/quickopen/browser/quickOpenWidget.js:356:22)
    at QuickOpenController.show (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:350:42)
    at GotoMarkerAction.QuickOpenAction.run (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/actions/quickOpenAction.js:33:35)", source: file:///P:/mseng/VSCode/vscode/out/vs/workbench/electron-browser/shell.js (331)
[11348:0105/100024:INFO:CONSOLE(85)] "Cannot read property 'getControl' of undefined: TypeError: Cannot read property 'getControl' of undefined
    at MarkersHandler.getResults (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/quickopen/browser/markersHandler.js:137:39)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:551:40
    at Promise_ctor.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1826:49)
    at QuickOpenController.handleSpecificHandler (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:530:59)
    at QuickOpenController.onType (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:438:38)
    at Object.quickOpenWidget.quickOpenWidget_1.QuickOpenWidget.onType (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:324:61)
    at QuickOpenWidget.doShowWithPrefix (file:///P:/mseng/VSCode/vscode/out/vs/base/parts/quickopen/browser/quickOpenWidget.js:367:28)
    at QuickOpenWidget.show (file:///P:/mseng/VSCode/vscode/out/vs/base/parts/quickopen/browser/quickOpenWidget.js:356:22)
    at QuickOpenController.show (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/quickopen/quickOpenController.js:350:42)
    at GotoMarkerAction.QuickOpenAction.run (file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/actions/quickOpenAction.js:33:35)", source: file:///P:/mseng/VSCode/vscode/out/vs/workbench/services/message/browser/messageService.js (85)
```

**Comment by dbaeumer** [comment]
@jrieken can you please have a look.

**Comment by dbaeumer** [comment]
Removing important flag. This only happens if no editor is open when Ctrl+Shift+M is pressed.
