### ISSUE TITLE
Unable to connect to Raspberry Pi After Fresh Isnstall

### ISSUE THREAD

**Issue by MrmHarting** [microsoft/vscode#178433]
I have been connecting to my raspberry Pi as a local server. I recently had to do a fresh install on it however and I am now unable to use the VS code remote server to connect to it. I can connect to it through terminal however, on and off VS Code. I have wasted so much time trying to resolve this. I even did a fresh install of VS Code to no avail. Here is the error message I continuously receive.

I use a mac to connect with also. Here is the error message. I would highly appreciate any help or guidance.

> *
> * Visual Studio Code Server
> *
[10:36:29.021] > * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[10:36:29.035] > Server did not start successfully. Full server log at /home/quantum-cadet/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884.log >>>
[10:36:29.036] > /home/quantum-cadet/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/bin/code-server: 12: /home/quantum-cadet/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node: not found
> <<< End of server log
> 42514c141656: start
> exitCode==32==
[10:36:29.040] > listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
[10:36:29.042] > extInstallTime====
> serverStartTime==14438==
> 42514c141656: end
[10:36:29.042] Received install output: 
exitCode==32==listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====extInstallTime====
serverStartTime==14438==

[10:36:29.043] Terminating local server
[10:36:29.046] Resolver error: Error: The VS Code Server failed to start
	at m.ServerInstallError (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:584079)
	at f (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:578136)
	at t.handleInstallOutput (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:581161)
	at Object.e [as tryInstallWithLocalServer] (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:623427)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:643396
	at async t.withShowDetailsEvent (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:647116)
	at async /Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:621899
	at async C (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:618405)
	at async t.resolveWithLocalServer (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:621514)
	at async t.resolve (/Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:644724)
	at async /Users/mharting/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032715/out/extension.js:1:720609
[10:36:29.052] ------

[10:36:29.053] Local server exit: 15

**Comment by eleanorjboyd** [comment]
closing in favor of this https://github.com/microsoft/vscode-remote-release/issues/2947 since that is a long-standing issue on this problem. I have been seeing this more recently as well- such as in https://github.com/microsoft/vscode-remote-release/issues/8264 if you want the newer conversation. fyi I will likely close 8264 in favor of 2947 soon. Thanks
