### ISSUE TITLE
VS Code doesn't run when /usr/data folder exists

### ISSUE THREAD

**Issue by ntqbit** [microsoft/vscode#178485]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2 ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 x64
- OS Version: 6.2.8-arch1-1

Steps to Reproduce:

1. Create folder /usr/data
2. Run vs code with --verbose flag
3. See window:
![image](https://user-images.githubusercontent.com/124562009/228230612-6baf4a1c-f5f7-460e-8e96-6817b801ae7b.png)
See error log:
```
Unable to create argv.json configuration file in /usr/data/argv.json, falling back to defaults (Error: EACCES: permission denied, open '/usr/data/argv.json')
[54122:0328/150551.836444:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[54122:0328/150551.901046:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/js
[54122:0328/150551.901089:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/js
[54122:0328/150551.901100:ERROR:simple_backend_impl.cc(755)] Simple Cache Backend: wrong file structure on disk: 1 path: /usr/data/user-data/Code Cache/js
[54122:0328/150551.901095:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/wasm
[54122:0328/150551.901141:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/wasm
[54122:0328/150551.901148:ERROR:simple_backend_impl.cc(755)] Simple Cache Backend: wrong file structure on disk: 1 path: /usr/data/user-data/Code Cache/wasm
[54122:0328/150551.901313:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/js
[54122:0328/150551.901355:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/js
[54122:0328/150551.901357:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/wasm
[54122:0328/150551.901362:ERROR:simple_backend_impl.cc(755)] Simple Cache Backend: wrong file structure on disk: 1 path: /usr/data/user-data/Code Cache/js
[54122:0328/150551.901381:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Code Cache/wasm
[54122:0328/150551.901384:ERROR:simple_backend_impl.cc(755)] Simple Cache Backend: wrong file structure on disk: 1 path: /usr/data/user-data/Code Cache/wasm
[54122:0328/150551.901487:ERROR:disk_cache.cc(196)] Unable to create cache
[54122:0328/150551.901502:ERROR:disk_cache.cc(196)] Unable to create cache
[main 2023-03-28T12:05:51.905Z] [File Watcher (node.js)] Request to start watching: /usr/data/user-data/User (excludes: <none>, includes: <all>),/usr/data/user-data/User/settings.json (excludes: <none>, includes: <all>)
[54157:0328/150551.944953:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Cache/Cache_Data
[54157:0328/150551.946495:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Cache/Cache_Data
[54157:0328/150551.946513:ERROR:simple_backend_impl.cc(755)] Simple Cache Backend: wrong file structure on disk: 1 path: /usr/data/user-data/Cache/Cache_Data
[54157:0328/150551.946772:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Cache/Cache_Data
[54157:0328/150551.946811:ERROR:simple_backend_impl.cc(79)] Failed to create directory: /usr/data/user-data/Cache/Cache_Data
[54157:0328/150551.946817:ERROR:simple_backend_impl.cc(755)] Simple Cache Backend: wrong file structure on disk: 1 path: /usr/data/user-data/Cache/Cache_Data
[54157:0328/150551.946844:ERROR:disk_cache.cc(196)] Unable to create cache
[main 2023-03-28T12:05:52.817Z] Error: EACCES: permission denied, mkdir '/usr/data/extensions'
[main 2023-03-28T12:05:52.817Z] Lifecycle#kill()
[main 2023-03-28T12:05:52.817Z] Lifecycle#onWillShutdown.fire()
[main 2023-03-28T12:05:52.820Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/usr/data/user-data/User'
[main 2023-03-28T12:05:52.820Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/usr/data/user-data/User/settings.json'
[main 2023-03-28T12:05:52.825Z] W [Error]: Unable to write file '/usr/data/user-data/User/globalStorage/storage.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/usr/data/user-data')
    at E.writeFile (/usr/lib/code/out/vs/code/electron-main/main.js:40:18095)
    at async d.k (/usr/lib/code/out/vs/code/electron-main/main.js:47:14715) {
  fileOperationResult: 6,
  options: undefined
}
```

I found why this happens. In [bootstrap-node.js](https://github.com/microsoft/vscode/blob/main/src/bootstrap-node.js) method `configurePortable` sets `VSCODE_PORTABLE` environment variable when VSCODE_ROOT_FOLDER/../../data exists. On Arch Linux VS code is installed at `/usr/lib/code`, therefore when folder `/usr/data` exists it treats it as portable installation, which then causes using invalid path when reading argv.json in main.js. See https://github.com/microsoft/vscode/blob/main/src/main.js#L331

Related to https://github.com/microsoft/vscode/issues/99558

**Comment by joaomoreno** [comment]
How important is having a `/usr/data` folder for you?

**Comment by ntqbit** [comment]
It's not importable for me to have `/usr/data` folder, I already deleted it.
I wanted to let you know what this issue exists and it might be a problem for someone who indeed need a `/usr/data` folder.
If it's a known issue and if it's not planned to do something with it, then you can close this issue.
