### ISSUE TITLE
The JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by jclepin** [microsoft/vscode#178690]
JS/TS service crash and so no IntelliSense works. (keep loading after service crash)

**TypeScript Version:** 5.1.0-dev.20230329

**Steps to reproduce crash**

1. open vscode
2. vscode try to initialize js/ts service
3. service crash

**TS Server Log**

`/Users/jeancedrick/Library/Application Support/Code/logs/20230330T155122/window1/exthost/vscode.typescript-language-features/tsserver-log-ncYqXu/tsserver.log`

The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**

Server: `semantic`

```
RangeError: Maximum call stack size exceeded
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33826:13)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33764:22)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33764:22)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33764:22)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
```

[20230330T155122.zip](https://github.com/microsoft/vscode/files/11112467/20230330T155122.zip)

**Comment by jclepin** [comment]
Note that the problem still appear when all extention are disabled
