### ISSUE TITLE
Bracket pair colorizer doesn't gracefully handle parse errors

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#178601]
I have a text file which I can share offline if needed which causes the parser to throw a bunch of errors. This prevents opening the file entirely. If I disable bracket pair colorization I can get the file to open, but my console is still filled with uncaught exceptions.

There seems to be some sort of recursive error going on here

Here's the call stack
```
RangeError: Maximum call stack size exceeded
    at Parser.tryReadChildFromCache (vscode-file://vscode-app/Users/lramos15/upstream/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/parser.js:75:30)
    at Parser.parseList (vscode-file://vscode-app/Users/lramos15/upstream/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/parser.js:56:34)
    at Parser.parseChild (vscode-file://vscode-app/Users/lramos15/upstream/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/parser.js:109:40)
    at Parser.parseList (vscode-file://vscode-app/Users/lramos15/upstream/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/parser.js:64:34)
    at Parser.parseChild (vscode-file://vscode-app/Users/lramos15/upstream/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/parser.js:109:40)
    at Parser.parseList (vscode-file://vscode-app/Users/lramos15/upstream/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/parser.js:64:34)
    at Parser.parseChild (vscode-file://vscode-app/Users/lramos15/upstream/vscode/out/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/parser.js:109:40)
```

It's surprising that the parse is called when I have the feature disabled.

**Comment by RedCMD** [comment]
disabling bracket pair colorization only disables the colour
but bracket pair matching still continues

**Comment by Morilli** [comment]
Just ran into the same problem. This can be easily reproduced by creating a file with just opening brackets, for example: 
[fail.txt](https://github.com/microsoft/vscode/files/11522991/fail.txt)
