### ISSUE TITLE
get crash when open a folder in Vscode On Ubuntu 

### ISSUE THREAD

**Issue by MajorTomMan** [microsoft/vscode#178771]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.77.0
- OS Version: 
    Linux version 5.4.0-84-generic (buildd@lcy01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #94~18.04.1-Ubuntu 
    SMP Thu Aug 26 23:17:46 UTC 2021
Steps to Reproduce:

1. install vscode on ubuntu
2. open vscode and cllck file->open a folder
3. get crash

**here is some log i got**
2023-03-31 14:18:58.299 [info] Electron sandbox mode is enabled!`
2023-03-31 14:18:58.315 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-31 14:18:58.316 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-31 14:18:58.316 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-31 14:18:58.316 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-31 14:19:01.254 [info] [perf] Render performance baseline is 29ms
2023-03-31 14:19:05.147 [error] Could not find category with ID: Setup: Error: Could not find category with ID: Setup
    at vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2548:53844
    at g.invoke (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at o.deliver (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2121)
    at l.fire (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1729)
    at B.progressStep (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:27216)
    at vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:27411
    at Set.forEach (<anonymous>)
    at B.progressByEvent (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:27395)
    at vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:22015
    at g.invoke (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at o.deliver (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2121)
    at l.fire (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1729)
    at w.k (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1570:13520)
    at w.executeCommand (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1570:13037)
    at Xc.nc (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2548:74633)
    at Xc.Sb (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2548:56959)
    at HTMLButtonElement.<anonymous> (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2548:55820)

**Comment by kokyriakidis** [comment]
I face the same issue

**Comment by gozuacik** [comment]
Is there any news/update about this issue? As a workaround I used to start VSCode from terminal such as "code ." That seems working for a temporary solution.

**Comment by MajorTomMan** [comment]
> Is there any news/update about this issue? As a workaround I used to start VSCode from terminal such as "code ." That seems working for a temporary solution.

no any process yet.. "code ." still working,but  maybe use the open folder tab is a better way. after all,this is more simplely i thought

**Comment by jaime-ez** [comment]
same issue

**Comment by bhavyaus** [comment]
> 2023-03-31 14:19:05.147 [error] Could not find category with ID: Setup: Error: Could not find category with ID: Setup
at vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2548:53844
at g.invoke (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
at o.deliver (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2121)
at l.fire (vscode-file://vscode-app/snap/code/123/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1729)
at B.progressStep (vscode-file://vscode-


This is related to https://github.com/microsoft/vscode/issues/178831#event-8910355355.

**Comment by bhavyaus** [comment]
As a workaround, you can close the "Welcome" page to prevent this crash from happening again. You can also disable the welcome page from showing on startup via
<img width="530" alt="image" src="https://user-images.githubusercontent.com/25044782/230231234-9a114afd-68f8-4085-af39-f3329e668dc3.png">

**Comment by bhavyaus** [comment]
However, this is the reason for the crash: https://github.com/microsoft/vscode/issues/178771

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178780

This is fixed in `1.77.1` released today, please update and give it a try.
