### ISSUE TITLE
Application crashes when using applications that modify the output of the terminal, such as peco

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#178753]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0-insider b1ad3f934ca87b76dac5cf3533fb172d1c30e6ba
- OS Version: macOS 13.3 M1 arch

Steps to Reproduce:

1. open integrated terminal
2. run: `$ echo foo bar buzz|tr ' ' '\n'|peco` 

output
```sh
# ~/Projects/github.com/yamachu/pokedex-net-webassembly-without-blazor $ [blazor-demo]
 echo foo bar buzz|tr ' ' '\n'|peco
panic: runtime error: index out of range [2] with length 0

goroutine 8 [running]:
github.com/nsf/termbox-go.SetCursor(0x7, 0x0)
        github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/api.go:214 +0x17c
github.com/peco/peco.(*Termbox).SetCursor(0x140001200c0, 0x7, 0x0)
        github.com/peco/peco/screen.go:38 +0x30
github.com/peco/peco.UserPrompt.Draw(0x1400005e0a0, 0x100f422ce, 0x6, 0x6, 0x14000119bca, 0x14000119880)
        github.com/peco/peco/layout.go:189 +0x290
github.com/peco/peco.(*BasicLayout).DrawPrompt(...)
        github.com/peco/peco/layout.go:672
github.com/peco/peco.(*BasicLayout).DrawScreen(0x1400000c060, 0x14000119880, 0x0)
        github.com/peco/peco/layout.go:688 +0xa0
github.com/peco/peco.(*View).drawScreen(0x1400000c078, 0x100fc94f8, 0x14000140720, 0x0)
        github.com/peco/peco/view.go:86 +0x70
github.com/peco/peco.(*View).Loop(0x1400000c078, 0x100fc9b18, 0x1400012cc40, 0x14000120570, 0x0, 0x0)
        github.com/peco/peco/view.go:66 +0x354
created by github.com/peco/peco.(*Peco).Run.func4
        github.com/peco/peco/peco.go:369 +0x194
```

previous version works fine.

**Comment by yamachu** [comment]
This is my repro.
https://user-images.githubusercontent.com/1955233/229217398-ad12449d-ce16-4b69-9782-e2a6f08033b7.mov

**Comment by yamachu** [comment]
peco worked fine when I used bash instead of zsh.
There were no diffs other than the zsh integration such as USER_ZDOTDIR set by VSCode.

**Comment by yamachu** [comment]
Upgrade Version: 1.78.0-insider Commit: d317fbf2970b8f28bd7c59f545c59532cd5b293c
This seems to be fixed.


https://user-images.githubusercontent.com/1955233/229825598-435e85f2-c14f-46c9-a56d-1546a46bf5f7.mov
