### ISSUE TITLE
Extension host terminating: renderer closed the MessagePort [error] Canceled: Canceled - Some extensions do not load

### ISSUE THREAD

**Issue by felipe-ds-lima** [microsoft/vscode#178726]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
- OS Version: Windows 11 22H2

Steps to Reproduce:

1. Install vscode
2. open any project with typescript

I'm suffering from a bug that does not open some extensions, as far as I've seen, the Extension Host crashes, even without any extensions installed (I removed them all), in a clean installation. This bug has been happening even in version 1.76.1

```
2023-03-30 18:49:09.728 [info] Extension host with pid 336 started
2023-03-30 18:49:09.728 [info] Skipping acquiring lock for c:\Users\felip\AppData\Roaming\Code\User\workspaceStorage\affaf1588bbef8cdd70d84e7e16032c7.
2023-03-30 18:49:09.772 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-03-30 18:49:09.777 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2023-03-30 18:49:09.797 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-03-30 18:49:09.825 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-03-30 18:49:09.891 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-03-30 18:49:10.029 [info] Eager extensions activated
2023-03-30 18:49:10.049 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-03-30 18:49:10.053 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-03-30 18:49:10.063 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
2023-03-30 18:49:10.332 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-03-30 18:49:10.398 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-03-30 18:49:16.172 [info] Extension host terminating: renderer closed the MessagePort
2023-03-30 18:49:16.179 [error] Canceled: Canceled
	at new l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:105190)
	at c.O (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11692)
	at G.<computed>.Q.charCodeAt.G.<computed> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:8967)
	at m.g (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:125211)
	at m.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:124587)
	at L.registerCommand.description (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:123880)
	at m.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:125797)
	at m.g (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:124687)
	at m.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:124587)
	at Object.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:23801)
	at D (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1467156)
	at E.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at h.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1481885)
	at c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1485952
	at Array.forEach (<anonymous>)
	at g.dispose (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1485938)
	at t.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:12398)
	at t.dispose (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:12533)
	at t.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1469286)
	at t.dispose (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:12533)
	at C (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12084)
	at E.Y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:11147)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:9131
	at Array.map (<anonymous>)
	at E.R (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:9118)
	at E.terminate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:9389)
	at d.terminate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:1544)
	at p (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:124:18690)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:124:14829)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-30 18:49:16.179 [info] Extension host with pid 336 exiting with code 0
2023-03-30 18:49:17.000 [info] Extension host with pid 8552 started
2023-03-30 18:49:17.000 [info] Skipping acquiring lock for c:\Users\felip\AppData\Roaming\Code\User\workspaceStorage\affaf1588bbef8cdd70d84e7e16032c7.
2023-03-30 18:49:17.025 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-03-30 18:49:17.030 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2023-03-30 18:49:17.042 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-03-30 18:49:17.057 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-03-30 18:49:17.097 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-03-30 18:49:17.274 [info] Eager extensions activated
2023-03-30 18:49:17.283 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-03-30 18:49:17.286 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-03-30 18:49:17.294 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
2023-03-30 18:49:17.427 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-03-30 18:49:17.474 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by felipe-ds-lima** [comment]
With the insiders version, the error is gone, but some extensions, like the styled-components extension still doesn't work well, regardless of the extension or vscode version, it stopped working out of nowhere when version 1.76.2 came out, but even installing older versions of vscode on my computer, some extensions don't work. Does the extension manager use any specific port? Could it be in conflict?

now, the extensions host output:
```bash
2023-03-31 13:43:04.639 [info] Extension host with pid 8532 started
2023-03-31 13:43:04.639 [info] Skipping acquiring lock for c:\Users\felip\AppData\Roaming\Code - Insiders\User\workspaceStorage\5b8a53957af22da204c4ba1ae3491ed1.
2023-03-31 13:43:04.728 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-03-31 13:43:04.738 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:typescript'
2023-03-31 13:43:04.939 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-03-31 13:43:04.943 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2023-03-31 13:43:04.986 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-03-31 13:43:05.012 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-03-31 13:43:05.651 [info] Eager extensions activated
2023-03-31 13:43:05.710 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-03-31 13:43:05.717 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-03-31 13:43:05.726 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
2023-03-31 13:43:05.744 [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
2023-03-31 13:43:05.767 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-03-31 13:43:05.825 [info] ExtensionService#_doActivateExtension PKief.material-icon-theme, startup: false, activationEvent: 'onStartupFinished'
2023-03-31 13:43:06.634 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-03-31 13:43:06.680 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-03-31 13:43:08.086 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2023-03-31 13:43:08.092 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
```

window output:
```bash
2023-03-31 13:43:03.804 [info] Electron sandbox mode is enabled!
2023-03-31 13:43:03.827 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-31 13:43:03.827 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-31 13:43:07.216 [info] [perf] Render performance baseline is 57ms
```

![image](https://user-images.githubusercontent.com/46056744/229181801-04dc4771-52ac-42ff-ac03-ef72c1debb88.png)

**Comment by bpasero** [comment]
I do not think that is related, but glad to see the error gone. I suggest to file issues to respective extensions if they do not work the same as before.
