### ISSUE TITLE
TextFileEditorModelManager disposes models it doesn't own

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#17888]
- VSCode Version: 1.9.0-Insiders
- OS Version: macOS

Steps to Reproduce:

1. Go to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/actions.ts#L56
2. Right click on `closeEditor`, click Find all references
3. `Cmd+Click` on references in `editorService`, the file containing that reference will be opened on the right side editor group.
4. Expand references tree, part of the references are rendered as blank somtimes

Gif demonstrating the steps:
![reference-blank](https://cloud.githubusercontent.com/assets/876920/21532696/75665eb8-cd07-11e6-9f37-0a7c9d95a101.gif)

It's not that easy to reproduce, you might need to run step 4 several times.

**Comment by jrieken** [comment]
The is some `textFileEditorManager` disposing the models I have references/locked via `createModelReference`. 


* insert the TS snippet below here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/browser/referencesModel.ts#L158
* open reference search as described above
* expand a view nodes 
* cmd click on an entry
* collapse/expand one of the open nodes -> node is empty

```ts
model.onDispose(() => {
	const {stack} = new Error();
	console.warn('DISPOSING MODEL FOR ' + this.uri);
	console.warn(stack);
});
```

```
DISPOSING MODEL FOR file:///Users/jrieken/Code/vscode/src/vs/workbench/parts/files/browser/editors/textFileEditor.ts
referencesModel.js:181 Error
    at file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/referenceSearch/browser/referencesModel.js:179:33
    at CallbackList.invoke (file:////Users/jrieken/Code/vscode/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (file:////Users/jrieken/Code/vscode/out/vs/base/common/event.js:88:40)
    at TextFileEditorModel.EditorModel.dispose (file:////Users/jrieken/Code/vscode/out/vs/workbench/common/editor.js:320:29)
    at TextFileEditorModel.BaseTextEditorModel.dispose (file:////Users/jrieken/Code/vscode/out/vs/workbench/common/editor/textEditorModel.js:146:38)
    at TextFileEditorModel.dispose (file:////Users/jrieken/Code/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:665:38)
    at TextFileEditorModelManager.disposeModelIfPossible (file:////Users/jrieken/Code/vscode/out/vs/workbench/services/textfile/common/textFileEditorModelManager.js:64:23)
    at file:////Users/jrieken/Code/vscode/out/vs/workbench/services/textfile/common/textFileEditorModelManager.js:356:58
    at Array.forEach (native)
    at TextFileEditorModelManager.disposeUnusedModels (file:////Users/jrieken/Code/vscode/out/vs/workbench/services/textfile/common/textFileEditorModelManager.js:356:18)
```

**Comment by bpasero** [comment]
Needs https://github.com/Microsoft/vscode/issues/17073 for file models.

**Comment by bpasero** [comment]
And actually blocked by https://github.com/Microsoft/vscode/issues/21709

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/5ecf0cda9a6c487acc1f0c75a3932954ca9211ef
