### ISSUE TITLE
TS Server fatal error:  Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.

### ISSUE THREAD

**Issue by YunsGeek** [microsoft/vscode#178953]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230401

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.
    at cast (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:3446:16)
    at Object.parenthesizeOperandOfPrefixUnary (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:21860:50)
    at Object.createPrefixUnaryExpression (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:23989:41)
    at parsePrefixUnaryExpression (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:33599:32)
    at parseSimpleUnaryExpression (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:33652:16)
    at parseUnaryExpressionOrHigher (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:33633:35)
    at parseBinaryExpressionOrHigher (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:33551:25)
    at parseAssignmentExpressionOrHigher (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:33224:18)
    at parseExpression (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:33190:16)
    at doOutsideOfContext (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:30880:12)
    at allowInAnd (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:30901:12)
    at parseExpressionOrLabeledStatement (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:34712:24)
    at parseStatement (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:34944:12)
    at parseListElement (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:31656:12)
    at parseList (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:31641:19)
    at parseSourceFileWorker (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:30696:24)
    at Object.parseSourceFile (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:30529:20)
    at createSourceFile (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:30364:21)
    at createLanguageServiceSourceFile (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:135779:22)
    at acquireOrUpdateDocument (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:132461:26)
    at Object.acquireDocumentWithKey (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:132386:12)
    at getOrCreateSourceFileByPath (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:136103:31)
    at Object.getOrCreateSourceFile (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:136083:14)
    at /Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:136015:42
    at Object.getSourceFileWithCache [as getSourceFile] (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:117515:24)
    at findSourceFileWorker (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:119847:23)
    at findSourceFile (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:119767:20)
    at /Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:119716:22
    at getSourceFileFromReferenceWorker (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:119685:26)
    at processSourceFile (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:119714:5)
    at processRootFile (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:119510:5)
    at /Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:118295:41
    at forEach (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:2313:22)
    at createProgram (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:118295:5)
    at synchronizeHostData (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:136039:15)
    at Object.getProgram (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:136111:5)
    at ConfiguredProject2.updateGraphWorker (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:172761:41)
    at ConfiguredProject2.updateGraph (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:172698:32)
    at ConfiguredProject2.updateGraph (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:173916:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:175527:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:176618:26)
    at /Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:176898:64
    at flatMap (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:2561:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:176898:24)
    at updateOpen (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:178046:29)
    at /Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:180597:69
    at IpcIOSession.executeWithRequestId (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:180589:14)
    at IpcIOSession.executeCommand (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:180597:29)
    at IpcIOSession.onMessage (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:180639:51)
    at process.<anonymous> (/Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230401/node_modules/typescript/lib/tsserver.js:182208:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:55:48.214Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 280f692d-db7c-47c6-b441-a12ad228b4dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
nestjs|ash|1.4.2
vscode-tailwindcss|bra|0.9.11
vscode-expo|byC|0.9.2
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme-icons|equ|2.7.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-typescript-next|ms-|5.1.20230401
vscode-react-native|msj|1.10.2
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.25.0
prisma|Pri|4.12.0
vscode-thunder-client|ran|2.5.3
LiveServer|rit|5.7.9
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.10
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by mjbvz** [comment]
Please share code which causes this issue
