### ISSUE TITLE
TS Server fatal error:  Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.

### ISSUE THREAD

**Issue by nil0006** [microsoft/vscode#179102]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230324

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Please review and upload this log file to help us diagnose this crash:

`c:\Users\NIL\AppData\Roaming\Code\logs\20230404T135038\window1\exthost\vscode.typescript-language-features\tsserver-log-4HlsEM\tsserver.log`

The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.
    at cast (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:3440:16)
    at Object.parenthesizeOperandOfPrefixUnary (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:21783:50)
    at Object.createPrefixUnaryExpression (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:23912:41)
    at parsePrefixUnaryExpression (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:33523:32)
    at parseSimpleUnaryExpression (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:33576:16)
    at parseUnaryExpressionOrHigher (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:33557:35)
    at parseBinaryExpressionOrHigher (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:33475:25)
    at parseAssignmentExpressionOrHigher (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:33148:18)
    at parseExpression (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:33114:16)
    at doOutsideOfContext (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:30803:12)
    at allowInAnd (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:30824:12)
    at parseExpressionOrLabeledStatement (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:34627:24)
    at parseStatement (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:34859:12)
    at parseListElement (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:31582:12)
    at parseList (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:31567:19)
    at parseBlock (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:34378:26)
    at parseStatement (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:34773:16)
    at parseListElement (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:31582:12)
    at parseList (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:31567:19)
    at parseSourceFileWorker (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:30619:24)
    at Object.parseSourceFile (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:30452:20)
    at createSourceFile (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:30287:21)
    at createLanguageServiceSourceFile (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:135671:22)
    at acquireOrUpdateDocument (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:132353:26)
    at Object.acquireDocumentWithKey (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:132278:12)
    at getOrCreateSourceFileByPath (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:135995:31)
    at Object.getOrCreateSourceFile (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:135975:14)
    at c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:135907:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:117434:24)
    at findSourceFileWorker (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:119767:23)
    at findSourceFile (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:119687:20)
    at c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:119636:22
    at getSourceFileFromReferenceWorker (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:119605:26)
    at processSourceFile (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:119634:5)
    at processRootFile (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:119430:5)
    at c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:118215:41
    at forEach (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:2307:22)
    at createProgram (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:118215:5)
    at synchronizeHostData (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:135931:15)
    at Object.getProgram (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:136003:5)
    at ConfiguredProject2.updateGraphWorker (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:172628:41)
    at ConfiguredProject2.updateGraph (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:172565:32)
    at ConfiguredProject2.updateGraph (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:173783:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:175394:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:176485:26)
    at c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:176765:64
    at flatMap (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:2555:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:176765:24)
    at updateOpen (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:177913:29)
    at c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:180464:69
    at IpcIOSession.executeWithRequestId (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:180456:14)
    at IpcIOSession.executeCommand (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:180464:29)
    at IpcIOSession.onMessage (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:180506:51)
    at process.<anonymous> (c:\Users\NIL\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230324\node_modules\typescript\lib\tsserver.js:182075:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by nil0006** [comment]
The JS/TS language service immediately crashed 5 times. The service will not be restarted.
