### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: d:/黑马教程/黑马就业班/react/react-demo/node_modules/@types/react/jsx-runtime.d.ts linked to nonexistent file D:/黑马教程/黑马就业班/react/react-demo/node_modules/_@types_react@18.0.33@@types/react/jsx-runtime.d.ts

### ISSUE THREAD

**Issue by CLHaoer** [microsoft/vscode#179522]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.8.2

**Steps to reproduce crash**
1.
2.
3.

**Global TS Server Plugins**

- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`
- `typescript-vue-plugin-forward`

**TS Server Log**
❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression: d:/黑马教程/黑马就业班/react/react-demo/node_modules/@types/react/jsx-runtime.d.ts linked to nonexistent file D:/黑马教程/黑马就业班/react/react-demo/node_modules/_@types_react@18.0.33@@types/react/jsx-runtime.d.ts
    at realPath (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43910:18)
    at tryResolve (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43873:32)
    at d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43847:69
    at Object.forEach (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:192:30)
    at nodeModuleNameResolverWorker (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43847:25)
    at nodeModuleNameResolver (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43820:16)
    at Object.resolveModuleName (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:43547:30)
    at resolveModuleName (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122843:36)
    at resolveNamesWithLocalCache (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122929:38)
    at Object.resolveModuleNames (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123007:20)
    at Project.resolveModuleNames (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171757:45)
    at actualResolveModuleNamesWorker (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118002:153)
    at resolveModuleNamesWorker (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118305:26)
    at resolveModuleNamesReusingOldState (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118483:19)
    at processImportedModules (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119928:35)
    at findSourceFileWorker (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119708:17)
    at findSourceFile (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119554:26)
    at d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119503:85
    at getSourceFileFromReferenceWorker (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119469:34)
    at processSourceFile (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119503:13)
    at processRootFile (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119304:13)
    at d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118111:67
    at Object.forEach (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:192:30)
    at Object.createProgram (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118111:16)
    at synchronizeHostData (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167050:26)
    at Object.getProgram (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167164:13)
    at Project.updateGraphWorker (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172331:53)
    at Project.updateGraph (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172259:42)
    at ConfiguredProject.updateGraph (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173421:63)
    at updateProjectIfDirty (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173910:45)
    at ProjectService.assignProjectToOpenedScriptInfo (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176240:29)
    at d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176575:97
    at Object.flatMap (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:525:25)
    at ProjectService.applyChangesInOpenFiles (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176575:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177948:46)
    at d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180140:96
    at Session.executeWithRequestId (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180131:28)
    at Session.executeCommand (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180140:41)
    at Session.onMessage (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180168:35)
    at process.<anonymous> (d:\vscoude\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184334:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.72.0-insider (c4722f1bb292284e0437eb7547808a5788fe6430, 2022-09-02T05:17:36.744Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.11GB free)|
|Process Argv|--crash-reporter-id 11ba4933-3b0f-43ca-a29c-5a1e18836719|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.4
macos-modern-theme|dav|2.3.18
es7-react-js-snippets|dsz|4.4.3
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot|Git|1.79.10634
copilot-labs|Git|0.12.791
eslint-rules-zh-plugin|mag|0.2.1
vscode-language-pack-zh-hans|MS-|1.72.10121008
indent-rainbow|ode|8.3.1
docthis|oou|0.8.2
material-icon-theme|PKi|4.25.0
LiveServer|rit|5.7.9
var-translation|sve|0.13.45
open-in-browser|tec|2.0.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
code-translate|w88|1.0.20

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192cf:30661257
functionswalk:30687959
pythonms35:30671666
pythonclientmv:30700173

```

</details>

**Comment by mjbvz** [comment]
Closing as this is an old VS Code, old TS, and a bunch of TS Server plugins are enabled. Please try with the latest VS Code
