### ISSUE TITLE
CANNOT use API proposal

### ISSUE THREAD

**Issue by kolserdav** [microsoft/vscode#179667]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.77.1
- OS Version:  Linux arch 6.2.8-arch1-1  SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 GNU/Linux

Do not working Python extension with latest version of code-oss. See https://github.com/microsoft/vscode-jupyter/issues/13237

Steps to Reproduce:

1.  Install extension 
`ms-python.python`
2.  Open or create any *.py file
3. See logs:
<details>
<summary>Open</summary>

<p>

```sh
workbench.desktop.main.js:747 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
workbench.desktop.main.js:615   ERR [Extension Host] extension activation failed Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at b (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at Mc.onDidChangeNotebookCellExecutionState (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:51922)
	at new PC (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:433687)
	at f (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:544291)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546181
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548728
	at Array.map (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548700
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545539
	at Array.reduce (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545511
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545838
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at t.resolve (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:550764)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519737
	at e._get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519106)
	at e._getButThrowIfAsync (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519166)
	at e.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:514861)
	at Ly.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:69994)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:552800
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
workbench.desktop.main.js:90 [Extension Host] extension activation failed Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at b (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at Mc.onDidChangeNotebookCellExecutionState (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:51922)
	at new PC (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:433687)
	at f (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:544291)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546181
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548728
	at Array.map (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548700
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545539
	at Array.reduce (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545511
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545838
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at t.resolve (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:550764)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519737
	at e._get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519106)
	at e._getButThrowIfAsync (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519166)
	at e.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:514861)
	at Ly.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:69994)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:552800
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
T	@	workbench.desktop.main.js:90
workbench.desktop.main.js:90 [Extension Host] rejected promise not handled within 1 second: Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
workbench.desktop.main.js:90 [Extension Host] stack trace: Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at b (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at Mc.onDidChangeNotebookCellExecutionState (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:51922)
	at new PC (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:433687)
	at f (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:544291)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546181
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548728
	at Array.map (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548700
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545539
	at Array.reduce (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545511
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545838
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at t.resolve (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:550764)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519737
	at e._get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519106)
	at e._getButThrowIfAsync (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519166)
	at e.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:514861)
	at Ly.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:69994)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:552800
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
workbench.desktop.main.js:1979 [[object Object]]Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
workbench.desktop.main.js:1979 Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at b (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at Mc.onDidChangeNotebookCellExecutionState (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:51922)
	at new PC (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:433687)
	at f (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:544291)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546181
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548728
	at Array.map (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548700
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545539
	at Array.reduce (<anonymous>)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545511
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:545838
	at t.resolveInstance (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:546208)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549240
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:549577
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548900
	at y (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548932)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:548794
	at t.resolve (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:550764)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519737
	at e._get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519106)
	at e._getButThrowIfAsync (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:519166)
	at e.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:2:514861)
	at Ly.get (/home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:69994)
	at /home/kol/.vscode-oss/extensions/ms-toolsai.jupyter-2023.3.100-universal/out/extension.node.js:24:552800
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
workbench.desktop.main.js:615  INFO [perf] Render performance baseline is 40ms
workbench.desktop.main.js:90 [Extension Host] rejected promise not handled within 1 second: Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
workbench.desktop.main.js:90 [Extension Host] stack trace: Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at b (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:33156)
	at E.activate (/home/kol/.vscode-oss/extensions/ms-python.python-2023.4.1-universal/out/client/extension.js:2:783139)
	at /home/kol/.vscode-oss/extensions/ms-python.python-2023.4.1-universal/out/client/extension.js:2:2386
	at Array.map (<anonymous>)
	at f.activateWorkspace (/home/kol/.vscode-oss/extensions/ms-python.python-2023.4.1-universal/out/client/extension.js:2:2376)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
workbench.desktop.main.js:1979 [[object Object]]Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
workbench.desktop.main.js:1979 Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at b (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:33156)
	at E.activate (/home/kol/.vscode-oss/extensions/ms-python.python-2023.4.1-universal/out/client/extension.js:2:783139)
	at /home/kol/.vscode-oss/extensions/ms-python.python-2023.4.1-universal/out/client/extension.js:2:2386
	at Array.map (<anonymous>)
	at f.activateWorkspace (/home/kol/.vscode-oss/extensions/ms-python.python-2023.4.1-universal/out/client/extension.js:2:2376)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
</p>

</details>

__Works with proprietary distribution.__

**Comment by gjsjohnmurray** [comment]
You need to raise this with whoever is responsible for building the archlinux packaging of Code OSS that you are wanting to use.
