### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:1 and sourceFile.scriptKind: 3, !entry: false

### ISSUE THREAD

**Issue by tyaginidhi** [microsoft/vscode#179839]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:1 and sourceFile.scriptKind: 3, !entry: false
    at getDocumentRegistryEntry (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:132012:11)
    at Object.releaseDocumentWithKey (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:132109:19)
    at getOrCreateSourceFileByPath (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135460:30)
    at Object.getOrCreateSourceFile (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135444:14)
    at c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135376:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117127:24)
    at findSourceFileWorker (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119460:23)
    at findSourceFile (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119380:20)
    at c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119329:22
    at getSourceFileFromReferenceWorker (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119313:69)
    at processSourceFile (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119327:5)
    at processRootFile (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119123:5)
    at c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117908:41
    at forEach (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2307:22)
    at createProgram (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117908:5)
    at synchronizeHostData (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135400:15)
    at Object.getProgram (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135472:5)
    at InferredProject2.updateGraphWorker (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172153:41)
    at InferredProject2.updateGraph (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172090:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174400:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176020:12)
    at c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176250:64
    at flatMap (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2555:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176250:24)
    at updateOpen (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177395:29)
    at c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179962:69
    at IpcIOSession.executeWithRequestId (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179954:14)
    at IpcIOSession.executeCommand (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179962:29)
    at IpcIOSession.onMessage (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180004:51)
    at process.<anonymous> (c:\Users\\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181571:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:939:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.78.0-insider (8f74fbfd1f2d8f6268a42df131726b218aafe511, 2023-04-05T05:24:15.380Z)
OS version: Windows_NT x64 10.0.23430
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.00GB free)|
|Process Argv|--crash-reporter-id bdc18285-1745-47f2-9af4-8750a76e8162|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot-nightly|Git|1.82.19

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
6233i204:30659907
vscodeenable:30660116
pythonb192cf:30661257
functionswalk:30687959
pythonms35:30671666
19089226:30680468
ecj1e332:30687743
pythonfmttext:30710679
pythonclientmv:30700173

```

</details>

**Comment by gjsjohnmurray** [comment]
Please update to the latest Insiders and see if you still get the problem.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
