### ISSUE TITLE
[Bug] stickyScroll error on typing: Uncaught (in promise) Canceled: Canceled

### ISSUE THREAD

**Issue by AndersMad** [microsoft/vscode#179863]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAKBAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzkkPG_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAeYKfLDdH8LkPzUBgZk1U7SLZC8tGbBa1yLVLtif8cDToHobxwkjz-4durD5j19ZYKDjFAIjO1pDjG-gKPz1nNNcBQyeXpJ5axNt-oumRBF61AZ-7xlfmuWvgCMKC8vpzhutnxFmnpKZ6PJvzfFaRPinZweRknYIg273LpUN4o36u1FBu20V5_FONoW-ET1jaU4im_CABmHIIvumxHw2YlSXDFbTt18WswTvZFcYjgza5c1GO7_-LZ1CA

### Monaco Editor Playground Code

```typescript
Any sample and add this to options: `stickyScroll: { enabled: true }`
```

### Reproduction Steps

1) Enable sticky scroll
1) Type `q w e`
1) Errors should spawn (with delay / debounce) in console

### Actual (Problematic) Behavior

Throws aync cancel error

```
async.ts:271 Uncaught (in promise) Canceled: Canceled
    at Delayer.cancel (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:45015:89)
    at Object.dispose (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:145333:94)
    at dispose (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:4885:27)
    at DisposableStore.clear (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:4968:17)
    at StickyModelProvider.<anonymous> (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:145328:29)
    at Generator.next (<anonymous>)
    at https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:102:71
    at new Promise (<anonymous>)
    at __awaiter (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:98:12)
    at StickyModelProvider.update (https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/dev/vs/editor/editor.main.js:145327:20)
```

### Additional Context

It **_IS_** reproducible in vscode.dev also! But I had to check it to be able to submit this form

**Comment by AndersMad** [comment]
@cardalda you are right! it's still yields a lot of errors - I was too fast when I saw the new version and updated vscode ref.

**Comment by cardalda** [comment]
@AndersMad , are you sure this bug shouldn't be filed at https://github.com/microsoft/monaco-editor ?

**Comment by AndersMad** [comment]
@cardalda I did - it was moved here by hediet the 13. of April (see "log" on this page).. it seems like it was fixed in vscode and made it to the vscode.dev site - and the monaco vscode ref was update after - but I spose the ref was for an "earlier" version :/

**Comment by AndersMad** [comment]
this is still an issue in version 0.41.0

**Comment by hediet** [comment]
@aiday-mar can you look into this? I think it should be easy to fix.

**Comment by aiday-mar** [comment]
Will do so now
