### ISSUE TITLE
The remote host cannot enable extension properly

### ISSUE THREAD

**Issue by hdright** [microsoft/vscode#180095]
Type: <b>Bug</b>

Although the extensions page shows that each extension (including python and jupyter) is enabled in SSH: 4090, vscode still cannot open the.ipynb file, and there is no information about the current python environment in the lower right corner of the interface. This means that the extension on the remote host is not actually enabled.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.23435
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.4.0-146-generic
Remote OS version: Linux x64 5.19.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.49GB free)|
|Process Argv|--crash-reporter-id 40eaa513-5a0f-4a56-b114-acd0106a8e7b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 3090|
|OS|Linux x64 5.4.0-146-generic|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 996)|
|Memory (System)|31.25GB (29.40GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 4090|
|OS|Linux x64 5.19.0-38-generic|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 799)|
|Memory (System)|251.50GB (232.30GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
snippets|221|0.1.38
arm|dan|1.7.4
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.7.5
better-cpp-syntax|jef|1.17.2
vscode-language-pack-zh-hans|MS-|1.77.2023040509
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.288.1
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
remote-explorer|ms-|0.4.0
devicetree|plo|0.1.1
vscode-icons|vsc|12.3.0
python|ms-|2023.7.11011538
vscode-pylance|ms-|2023.4.21
jupyter|ms-|2023.3.1201040234
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
pythonfmttext:30710681
f8hc8238:30694864

```

</details>

**Comment by hdright** [comment]
At the same time, an error message appears on the Server:
2023-04-17 14:07:28.267 [error] CodeExpectedError: Could not find pty on pty host
    at L (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:28:6849)
    at L.updateTitle (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:28:2630)
    at Object.call (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at g.s (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:15:5413)
    at g.q (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:15:4916)
    at /home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:15:4327
    at c.invoke (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at f.deliver (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:11:2125)
    at n.fire (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:11:1733)
    at process.T (/home/hdr/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/platform/terminal/node/ptyHostMain.js:9:21039)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

**Comment by hdright** [comment]
Thanks. Just add a proxy to the server.
