### ISSUE TITLE
Terminal window vertical scroll bar can't be selected

### ISSUE THREAD

**Issue by varadero** [Microsoft/vscode#18028]
- VSCode Version: 1.7.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open terminal window by pressing CTRL+`
2. Show vertical scroll bar by pressing ENTER key few times
3. Move the mouse over the vertical scroll bar

User cannot drag vertical scroll bar - it is draggable only if the mouse is over the right half of the scroll bar - only then the scroll bar is "highlighted" indicating that the user can now drag it. How "wide" the are that can be highlighted by moving the mouse over it depends on the width of VSCode window - sometimes the scroll bar becomes highlighted when the mouse is at the middle of the scroll bar but if now user resizes VSCode window width by few pixels, "highlighting" area becomes smaller and eventually for some VSCode window widths - the scroll bar cannot be highlighted at all.

**Comment by Tyriar** [comment]
@varadero could you see if you can reproduce this in the upstream project's demo? https://github.com/sourcelair/xterm.js

To get it running:

```
git clone https://github.com/sourcelair/xterm.js.git
cd xterm.js
npm i
npm start
```

Then open http://127.0.0.1:3000 in your browser

**Comment by varadero** [comment]
I tried xterm.js and got the following error after "npm i":
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\vscode-bugs\18028\xterm.js\npm-debug.log

D:\Projects\vscode-bugs\18028\xterm.js>npm start

> xterm@2.2.3 prestart D:\Projects\vscode-bugs\18028\xterm.js
> npm run build


> xterm@2.2.3 build D:\Projects\vscode-bugs\18028\xterm.js
> ./bin/build

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! xterm@2.2.3 build: `./bin/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@2.2.3 build script './bin/build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\vscode-bugs\18028\xterm.js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! xterm@2.2.3 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@2.2.3 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
```

Then I tried "npm start":
```
D:\Projects\vscode-bugs\18028\xterm.js>npm start

> xterm@2.2.3 prestart D:\Projects\vscode-bugs\18028\xterm.js
> npm run build


> xterm@2.2.3 build D:\Projects\vscode-bugs\18028\xterm.js
> ./bin/build

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! xterm@2.2.3 build: `./bin/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@2.2.3 build script './bin/build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\vscode-bugs\18028\xterm.js\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! xterm@2.2.3 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@2.2.3 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\vscode-bugs\18028\xterm.js\npm-debug.log
```

The content of npm-debug.log file is:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle xterm@2.2.3~prestart: xterm@2.2.3
6 verbose lifecycle xterm@2.2.3~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle xterm@2.2.3~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Projects\vscode-bugs\18028\xterm.js\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\CheckPoint\Endpoint Security Agent\Endpoint Common\bin;C:\Users\varadero\Downloads\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\CheckPoint\Endpoint Security Agent\Endpoint Common\bin;C:\Users\varadero\AppData\Local\Programs\Git\cmd;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\varadero\AppData\Roaming\npm
8 verbose lifecycle xterm@2.2.3~prestart: CWD: D:\Projects\vscode-bugs\18028\xterm.js
9 silly lifecycle xterm@2.2.3~prestart: Args: [ '/d /s /c', 'npm run build' ]
10 silly lifecycle xterm@2.2.3~prestart: Returned: code: 1  signal: null
11 info lifecycle xterm@2.2.3~prestart: Failed to exec prestart script
12 verbose stack Error: xterm@2.2.3 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:885:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid xterm@2.2.3
14 verbose cwd D:\Projects\vscode-bugs\18028\xterm.js
15 error Windows_NT 6.1.7601
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
17 error node v7.3.0
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error xterm@2.2.3 prestart: `npm run build`
20 error Exit status 1
21 error Failed at the xterm@2.2.3 prestart script 'npm run build'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the xterm package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs xterm
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls xterm
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by Tyriar** [comment]
Ah yeah, there are 2 PRs out right now that fix windows support. Sorry about the hassle.
