### ISSUE TITLE
Pasting lots of text fails in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180386]
* copy the contents of [422.log](https://github.com/microsoft/vscode/files/11282588/422.log)
* paste into a untitled editor

🐌 it takes seconds for me before the content appears, sometimes not at all
![Recording 2023-04-20 at 08 57 33](https://user-images.githubusercontent.com/900690/233285418-e2702d34-d55d-415b-af42-a4d92101e87f.gif)

**Comment by bpasero** [comment]
Oh, there is this in the console: `parser.ts:71 Uncaught RangeError: Maximum call stack size exceeded`

```
Uncaught RangeError: Maximum call stack size exceeded
    at b.g (parser.ts:71:10)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
    at b.g (parser.ts:89:18)
    at b.i (parser.ts:146:24)
```
