### ISSUE TITLE
Getting Error  for Feature "Android SDK" (ghcr.io/jarrodcolburn/features/android-sdk) 

### ISSUE THREAD

**Issue by rainfall-datta** [microsoft/vscode#180495]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open VSCode from command pallet say run in new devcontainer
2. Select Features Android SDK, Android tools
3. Select Feature flutter and Java SDK with Default versions
4 run devcontainer

Below is log,

```
#0 73.92 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#0 73.92 
#0 95.22 ./install.sh: 32: Syntax error: "(" unexpected
#0 95.22 ERROR: Feature "Android SDK" (ghcr.io/jarrodcolburn/features/android-sdk) failed to install!
------
error: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/android-sdk_4 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/android-sdk_4  && cd /tmp/dev-container-features/android-sdk_4  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/android-sdk_4]: exit code: 2
```

**Comment by roblourens** [comment]
This sounds like it could be an issue with your devcontainer?

**Comment by ganesh-rao** [comment]
I have the same error now. Any help is greatly appreciated.

Here is my devcontainer.json

```
{
	"name": "Ubuntu",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:focal",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"nodeGypDependencies": true,
			"version": "18"
		},
		"ghcr.io/devcontainers/features/ruby:1": {
			"version": "2.7"
		},
		"ghcr.io/devcontainers/features/java:1": {
			"version": "11",
			"jdkDistro": "open",
			"gradleVersion": "latest",
			"mavenVersion": "latest",
			"antVersion": "latest"
		},
		"ghcr.io/akhildevelops/devcontainer-features/android-cli:0": {},
		"ghcr.io/jarrodcolburn/features/android-sdk:0": {
			"emulator": true,
			"platforms": "33",
			"build-tools": "33.0.2"
		}
	},
	"customizations": {
		"vscode": {
			"extensions": [
				"amazonwebservices.aws-toolkit-vscode",
				"dbaeumer.vscode-eslint",
				"wix.vscode-import-cost",
				"VisualStudioExptTeam.vscodeintellicode",
				"VisualStudioExptTeam.intellicode-api-usage-examples",
				"msjsdiag.vscode-react-native"
			]
		}
	}
	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```
Here is the log output:

```
#0 40.64 ./install.sh: 32: Syntax error: "(" unexpected
#0 40.64 ERROR: Feature "Android SDK" (ghcr.io/jarrodcolburn/features/android-sdk) failed to install!
------
[2023-05-01T21:17:50.979Z] ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/android-sdk_5 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/android-sdk_5  && cd /tmp/dev-container-features/android-sdk_5  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/android-sdk_5]: exit code: 2
[2023-05-01T21:17:51.188Z] Stop (151895 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-username/container-features/0.35.0-1682975714464 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:focal --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-reactnative-a62a55658b6c6cf633e375e021d3af3858b701342dc7039277ce83969bec4242-features -f /tmp/devcontainercli-username/container-features/0.35.0-1682975714464/Dockerfile.extended /home/username/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-05-01T21:17:51.189Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-username/container-features/0.35.0-1682975714464 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:focal --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-reactnative-a62a55658b6c6cf633e375e021d3af3858b701342dc7039277ce83969bec4242-features -f /tmp/devcontainercli-username/container-features/0.35.0-1682975714464/Dockerfile.extended /home/username/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-05-01T21:17:51.189Z]     at bse (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js:1916:3264)
[2023-05-01T21:17:51.189Z]     at J7 (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js:1916:3200)
[2023-05-01T21:17:51.189Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-05-01T21:17:51.189Z]     at async $se (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js:1931:2626)
[2023-05-01T21:17:51.189Z]     at async Ah (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js:1931:3741)
[2023-05-01T21:17:51.189Z]     at async aae (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js:2059:17376)
[2023-05-01T21:17:51.189Z]     at async oae (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js:2059:17117)
[2023-05-01T21:17:51.194Z] Stop (157077 ms): Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/username/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-92d2b469-e02c-42c6-8438-2fda2601e9401682975713287 --workspace-folder /home/username/Code/project/docker/reactnative --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/username/Code/project/docker/reactnative --id-label devcontainer.config_file=/home/username/Code/project/docker/reactnative/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/username/Code/project/docker/reactnative/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-05-01T21:17:51.194Z] Exit code 1
[2023-05-01T21:17:51.196Z] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.288.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/username/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-92d2b469-e02c-42c6-8438-2fda2601e9401682975713287 --workspace-folder /home/username/Code/project/docker/reactnative --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/username/Code/project/docker/reactnative --id-label devcontainer.config_file=/home/username/Code/project/docker/reactnative/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/username/Code/project/docker/reactnative/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-05-01T21:17:51.196Z] Exit code 1
```
