### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#180540]
```javascript
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at D.g in src/vs/editor/browser/view/viewLayer.ts:504:18
at D.render in src/vs/editor/browser/view/viewLayer.ts:450:10
at R.renderLines in src/vs/editor/browser/view/viewLayer.ts:359:27
at a.renderText in src/vs/editor/browser/viewParts/lines/viewLines.ts:605:22
at j.I in src/vs/editor/browser/view.ts:406:20
at <anonymous> in src/vs/editor/browser/view.ts:364:30
at func in src/vs/editor/browser/view.ts:557:10
at safeInvokeNoArg in src/vs/editor/browser/view.ts:364:3
at j.v in src/vs/editor/browser/view.ts:230:8
at Object.getLineWidth in src/vs/editor/browser/view.ts:272:10
at d.getLineWidth in src/vs/editor/browser/controller/mouseTarget.ts:345:27
at n.u in src/vs/editor/browser/controller/mouseTarget.ts:787:25
at n.o in src/vs/editor/browser/controller/mouseTarget.ts:727:30
at n.g in src/vs/editor/browser/controller/mouseTarget.ts:549:41
at n.createMouseTarget in src/vs/editor/browser/controller/mouseTarget.ts:497:33
at S.p in src/vs/editor/browser/controller/mouseHandler.ts:250:34
at S.u in src/vs/editor/browser/controller/mouseHandler.ts:282:17
at <anonymous> in src/vs/editor/browser/controller/mouseHandler.ts:91:9
at callback in src/vs/editor/browser/editorDom.ts:182:64
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=704ed70d4fd1c6bd6342c436f1ede30d1cff4710&bH=5fc1c533-6208-c725-1a14-7f06e59fe3dc)

**Comment by lszomoru** [comment]
@sbatten, could you please help triage this issue, and reassign it? Thanks!

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/a131a88231e3152d34d1e03eb9c0b0eb36e749cc
