### ISSUE TITLE
jarvis ai voice assistent

### ISSUE THREAD

**Issue by yogesh14092002** [microsoft/vscode#180522]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by yogesh14092002** [comment]
Type: <b>Performance Issue</b>

program dosen't run 
PS C:\Users\91636\Downloads\MEmu Download\PyCharm Community Edition 2022.3.3> & "C:/Program Files/Python311/python.exe" c:/Users/91636/AppData/Roaming/Python/Python311/site-packages/wikipedia/__init__.py  
Traceback (most recent call last):
  File "c:\Users\91636\AppData\Roaming\Python\Python311\site-packages\wikipedia\__init__.py", line 1, in <module>
    from wikipedia import Page
  File "c:\Users\91636\AppData\Roaming\Python\Python311\site-packages\wikipedia\wikipedia.py", line 3, in <module>
    import requests
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\urllib3\__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 12, in <module>
    from .connection import (
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 10, in <module>
    import packages
ModuleNotFoundError: No module named 'packages'
PS C:\Users\91636\Downloads\MEmu Download\PyCharm Community Edition 2022.3.3> & "C:/Program Files/Python311/python.exe" c:/Users/91636/AppData/Roaming/Python/Python311/site-packages/wikipedia/__init__.py
Traceback (most recent call last):
  File "c:\Users\91636\AppData\Roaming\Python\Python311\site-packages\wikipedia\__init__.py", line 1, in <module>
    from wikipedia import Page
  File "c:\Users\91636\AppData\Roaming\Python\Python311\site-packages\wikipedia\wikipedia.py", line 3, in <module>
    import requests
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\urllib3\__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 12, in <module>
    from .connection import (
  File "C:\Users\91636\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 10, in <module>
    import packages
ModuleNotFoundError: No module named 'packages'

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.65GB (1.44GB free)|
|Process Argv|--crash-reporter-id 01471607-1733-47b5-9a56-c031c22a8d7b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   129	 18616	code main
    1	    92	  2864	window [2] (Issue Reporter)
    0	   197	  3324	window [1] (Untitled (Workspace) - Visual Studio Code)
    0	    26	  3440	   crashpad-handler
    0	   309	  3964	   gpu-process
    0	    40	  5884	   utility-network-service
    0	    89	  7220	fileWatcher [1]
    0	   206	 11280	extensionHost [1]
    0	    15	  3916	     c:\Users\91636\.vscode\extensions\ms-vscode.cpptools-1.14.5-win32-x64\bin\cpptools.exe
    0	    10	 18764	       console-window-host (Windows internal process)
    0	    84	 13232	     electron-nodejs ("C:\Users\91636\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\91636\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=11280)
    0	   119	 16856	     electron-nodejs ("C:\Users\91636\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\91636\.vscode\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js --node-ipc --clientProcessId=11280)
    0	    84	 17132	     electron-nodejs ("C:\Users\91636\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\91636\.vscode\extensions\ibm.db2forzosdeveloperextension-2.1.0\dist\server.js --node-ipc --clientProcessId=11280)
    0	    77	 18768	     "C:\Program Files\Python311\python.exe" c:\Users\91636\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\run-jedi-language-server.py
    0	    10	 11716	       console-window-host (Windows internal process)
    0	    29	 13108	       "C:\Program Files\Python311\python.exe" c:\Users\91636\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\jedilsp\jedi\inference\compiled\subprocess\__main__.py c:\Users\91636\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\jedilsp 3.11.3
    0	    10	  8204	         console-window-host (Windows internal process)
    0	    38	 19004	     "C:\Program Files (x86)\Eclipse Adoptium\jdk-8.0.362.9-hotspot\bin\java" -DwatchParentProcess=false -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\Users\91636\AppData\Roaming\Code\User\globalStorage\redhat.vscode-xml -noverify -Xmx64M -cp c:\Users\91636\.vscode\extensions\redhat.vscode-xml-0.25.0-win32-x64\server\org.eclipse.lemminx-0.25.0-uber.jar org.eclipse.lemminx.XMLServerLauncher
    0	    10	 19668	       console-window-host (Windows internal process)
    0	    83	 21564	shared-process
    0	    83	 12952	     ptyHost
    0	    97	  4292	       "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\91636\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    97	  7496	       "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\91636\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 13708	       console-window-host (Windows internal process)
    0	     6	 15436	       console-window-host (Windows internal process)
    0	   103	 17400	       "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\91636\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 22808	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled (Workspace) - Visual Studio Code)
|    Folder (PyCharm Community Edition 2022.3.3): 2 files
|      File types: json(1)
|      Conf files: launch.json(1)
|      Launch Configs: node(2) python;
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
askia-qexml-generator-extension|Ask|1.0.1
htmlplay|bia|0.0.10
vscode-markdownlint|Dav|0.49.0
vscode-deno|den|3.17.0
composer-php-vscode|DEV|1.33.12934
phptools-vscode|DEV|1.33.12934
profiler-php-vscode|DEV|1.33.12934
python-preview|don|0.0.4
xml|Dot|2.5.1
quick-components|fra|2.1.0
db2forzosdeveloperextension|IBM|2.1.0
vscode-docker|ms-|1.25.0
vscode-ros|ms-|0.9.3
python|ms-|2023.6.1
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.77.0
cmake-tools|ms-|1.14.30
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
phscript-sdk-formatter-vs|pho|1.0.1
vscode-xml|red|0.25.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscode-java-dependency|vsc|0.21.2
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>
