### ISSUE TITLE
sticky scroll: exception "model is disposed"

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#180702]
# Description

I get this sticky scroll exception (note how one of the callers is `computeStickyModel`): 

```javascript
 ERR Model is disposed!: Error: Model is disposed!
    at Vn.db (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:702:269)
    at Vn.getOptions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:704:1490)
    at b (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:77:123583)
    at D.compute (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:77:122594)
    at d.e (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:51084)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:48397
    at C (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:97:11319)
    at d.computeStickyModel (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:48388)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:47879
    at async g.update (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:47785)
    at async r.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:53132)
    at async r.update (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:52809)
```

# Reproduction

I don't have a better repro steps, sorry. But I have seen this error in other contexts as well, just don't have exact steps.

- With an editor open, switch between panel views fast. 

Here's the gif of me doing this

https://user-images.githubusercontent.com/16353531/234024611-daf3c4c3-1a1b-4eed-9bb7-2a9410c1af75.mov

# Version info 

```
Version: 1.78.0-insider (Universal)
Commit: 3a69e153f6c68b2b855fb2f1e5bdb798a16a1ee4
Date: 2023-04-24T05:23:27.796Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes
```

**Comment by aiday-mar** [comment]
Thanks for filing the issue, I'll look into it, when I have time.
