### ISSUE TITLE
ERR Cannot read properties of undefined (reading 'lastTask')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#181102]
Saw this in insiders after a window reload:

```
ERR Cannot read properties of undefined (reading 'lastTask'): TypeError: Cannot read properties of undefined (reading 'lastTask')
    at P.Bb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1516:17006)
    at P.Cb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1516:17101)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1516:20463
    at async P.Fb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1516:20483)
    at async P.xb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1516:8701)
```

Seems to be from:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/900690/235094148-9769b208-e020-44a9-8799-f2671f75664e.png">

**Comment by bhavyaus** [comment]
Seeing this a lot more since the last insiders update. 

Version: 1.79.0-insider (user setup)
Commit: 9233de805c8fb05fad4d9d1c15f22fbca85430ad
Date: 2023-05-16T10:44:42.423Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by meganrogge** [comment]
To verify, do a code review - here is where the `undefined` was throwing before https://github.com/microsoft/vscode/pull/182896/files#diff-5d6d50fef79440567acc5f9a977c908f45f59342bb4d5e19ef5b9ee25e02920cL1281
