### ISSUE TITLE
Merge editor looses conflict resolution lense actions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#181619]
After I did "Accept Combination" on the first conflict (I picked the left hand side), all actions are gone for resolving each conflict:

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/900690/236413507-fad1604c-20d8-4d52-ba1e-a407e8ff7dbf.png">

[state.json.zip](https://github.com/microsoft/vscode/files/11404534/state.json.zip)

**Comment by bpasero** [comment]
Maybe this log entry:

```
ERR Assertion Failed: Error: Assertion Failed
    at D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:11:9896)
    at new r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1041:10074)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1041:13755
    at Array.map (<anonymous>)
    at e.MergeDiffComputer.computeDiff (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1041:13748)
```

**Comment by bpasero** [comment]
There is also a git exception it seems:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/900690/236414059-d1d2ef60-056c-499c-85bd-d4b495804c18.png">

**Comment by bpasero** [comment]
Reproduces running out of sources, stack:

```
assertFn (assert.js:45)
DetailedLineRangeMapping (mapping.js:153)
(anonymous) (diffComputer.js:37)
computeDiff (diffComputer.js:37)
await in computeDiff (async)
recompute (textModelDiffs.js:58)
(anonymous) (textModelDiffs.js:27)
_runIfNeeded (autorun.js:76)
AutorunObserver (autorun.js:55)
autorun (autorun.js:10)
TextModelDiffs (textModelDiffs.js:25)
MergeEditorModel (mergeEditorModel.js:32)
_createInstance (instantiationService.js:91)
createInstance (instantiationService.js:62)
createInputModel (mergeEditorInputModel.js:210)
await in createInputModel (async)
resolve (mergeEditorInput.js:72)
setInput (mergeEditor.js:121)
await in setInput (async)
doSetInput (editorPanes.js:292)
doOpenEditor (editorPanes.js:166)
openEditor (editorPanes.js:65)
(anonymous) (editorGroupView.js:809)
doShowEditor (editorGroupView.js:829)
doOpenEditor (editorGroupView.js:794)
openEditor (editorGroupView.js:711)
openEditor (editorService.js:408)
await in openEditor (async)
run (commands.js:63)
handler (actions.js:358)
invokeFunction (instantiationService.js:46)
_tryExecuteCommand (commandService.js:81)
executeCommand (commandService.js:50)
$executeCommand (mainThreadCommands.js:75)
_doInvokeHandler (rpcProtocol.js:381)
_invokeHandler (rpcProtocol.js:366)
_receiveRequest (rpcProtocol.js:307)
_receiveOneMessage (rpcProtocol.js:234)
(anonymous) (rpcProtocol.js:115)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
fire (ipc.net.js:504)
port.onmessage (localProcessExtensionHost.js:452)
```

**Comment by hediet** [comment]
This seems to work now (did some bugfix for a different issue).
