### ISSUE TITLE
Global file search does not work.

### ISSUE THREAD

**Issue by akihikodaki** [microsoft/vscode#181693]
Type: <b>Bug</b>

1. Run: `git clone https://gitlab.com/qemu-project/qemu.git -b v8.0.0`
2. Run: `code qemu`
3. Press Ctrl-P
4. Type: `cpu.c`

This should list `cpu.c`, but it won't.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:08.887Z)
OS version: Linux arm64 6.2.0-asahi-11-1-edge-ARCH
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (8 x 2256)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|23.03GB (18.57GB free)|
|Process Argv|--unity-launch --crash-reporter-id e859d593-afd1-459d-9e9b-a4879e7a603d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clangd|llv|0.1.24
vscode-docker|ms-|1.25.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
wordcount|ms-|0.1.0
ruby-lsp|Sho|0.3.1
rbs-syntax|sou|0.2.0
code-spell-checker|str|2.20.4
cmake|twx|0.0.17
volar|Vue|1.6.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixshowwlkth:30730052
pythongtdpathcf:30731979

```

</details>

**Comment by akihikodaki** [comment]
Yes.

**Comment by andreamah** [comment]
Oh, I see you're running Asahi Linux. If you do the following, what logs do you get when you perform a search?
1. run `Developer: Set Log Level`  in the command palette and set `Trace`
2. do a search
3. In the bottom panel, check logs in the `Extension Host` channel in the `Outputs` tab

I think this might be a duplicate of https://github.com/microsoft/vscode/issues/179907

**Comment by akihikodaki** [comment]
Here are the logs:
```
2023-05-11 22:22:32.575 [info] Extension host with pid 21876 started
2023-05-11 22:22:32.575 [info] Skipping acquiring lock for /home/alarm/.config/Code/User/workspaceStorage/d1e536861f51614c264f81c24f8760d3.
2023-05-11 22:22:32.645 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-05-11 22:22:32.650 [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: true, activationEvent: 'workspaceContains:/.vscode/c_cpp_properties.json'
2023-05-11 22:22:32.830 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-05-11 22:22:32.839 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-05-11 22:22:32.935 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-05-11 22:22:32.993 [info] Eager extensions activated
2023-05-11 22:22:32.993 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:json'
2023-05-11 22:22:32.996 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:json'
2023-05-11 22:22:33.004 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2023-05-11 22:22:33.008 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-05-11 22:22:33.024 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:33.025 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:33.032 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:33.048 [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:33.138 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-05-11 22:22:33.264 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-05-11 22:22:40.130 [info] Extension host terminating: renderer closed the MessagePort
2023-05-11 22:22:40.138 [error] Canceled: Canceled
	at new l (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at D (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:1259661)
	at v.invoke (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at i.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:1274494)
	at /opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:1278940
	at Array.forEach (<anonymous>)
	at g.dispose (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:1278926)
	at t.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:12369)
	at t.dispose (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:12504)
	at t.<anonymous> (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:1261791)
	at t.dispose (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:12504)
	at T (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-11 22:22:40.144 [info] Extension host with pid 21876 exiting with code 0
2023-05-11 22:22:40.707 [info] Extension host with pid 22066 started
2023-05-11 22:22:40.707 [info] Skipping acquiring lock for /home/alarm/.config/Code/User/workspaceStorage/0f8b5389439ea956357cfabe3cd9213d.
2023-05-11 22:22:40.730 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-05-11 22:22:40.732 [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: true, activationEvent: 'workspaceContains:/.vscode/c_cpp_properties.json'
2023-05-11 22:22:40.773 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-05-11 22:22:40.782 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-05-11 22:22:40.785 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-05-11 22:22:40.994 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-05-11 22:22:41.008 [info] Eager extensions activated
2023-05-11 22:22:41.088 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:json'
2023-05-11 22:22:41.092 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:json'
2023-05-11 22:22:41.123 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2023-05-11 22:22:41.133 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:41.134 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:41.136 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:41.155 [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onStartupFinished'
2023-05-11 22:22:41.174 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-05-11 22:22:41.235 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-05-11 22:23:13.786 [debug] ExtHostSearch /opt/visual-studio-code/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/.ruby-lsp' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --no-ignore-parent --follow --no-config --no-ignore-global
 - cwd: /home/alarm/q/var/qemu
 - Sibling clauses: {}
```

I'm quite sure that the issue you pointed out is affecting my system, but somehow the log does not say `Unsupported system page size`.

**Comment by andreamah** [comment]
I think you might have cut it off before it returned its results. Did you wait a while after performing your search to collect the logs?

**Comment by akihikodaki** [comment]
Yes, but there is no output. I have just tried while a terminal emulator running `watch sh -c 'ps -aux | grep rg'` and it showed nothing so I guess `rg` terminates really quickly.

**Comment by andreamah** [comment]
If you invoke rg directly (I think the path is in the logs), what do you see?

**Comment by akihikodaki** [comment]
```
$ /opt/visual-studio-code/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/.ruby-lsp' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --no-ignore-parent --follow --no-config --no-ignore-global
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
Aborted (core dumped)
```
It says "Unsupported system page size".

**Comment by andreamah** [comment]
Ah ok, that should be a duplicate of https://github.com/microsoft/vscode/issues/179907 then. Thanks for the info!
