### ISSUE TITLE
[json] Error while computing completions with snippets

### ISSUE THREAD

**Issue by ijanos** [microsoft/vscode#181753]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:46.685Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.1-arch1-1
Sandboxed: No
```

I think this is a regression in 1.78, it used to work in previous versions. Reproduced it with `code --disable-extensions` and a minimal-ish test case included below. 

Steps to Reproduce:

1. Create a json schema with defaultSnippets
2. create a json file using that schema
3. try to use a snippet. json language server with error out.

```json
{
    "$id": "test.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "myarray": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/item"
            }
        }
    },
    "$defs": {
        "item": {
            "type": "object",
            "defaultSnippets": [
                {
                    "label": "new item",
                    "description": "",
                    "body": { }
                }
            ],
            "properties": {}
        }
    }
}

```

```json
{
    "$schema": "./test.schema.json",
    "myarray": [
     <PRESS CTRL SPACE HERE>  
    ]
}

```

error in JSON Language server output window: 
```
[Error - 12:50:00 PM] Error while computing completions for file:///home/[REDACTED]test.json: Unexpected token 'e', "new item" is not valid JSON
SyntaxError: Unexpected token 'e', "new item" is not valid JSON
    at JSON.parse (<anonymous>)
    at Et.getValueFromLabel (/opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:123619)
    at Object.add (/opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:118275)
    at /opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:121280
    at Array.forEach (<anonymous>)
    at Et.addDefaultValueCompletions (/opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:120848)
    at Et.addSchemaValueCompletions (/opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:119830)
    at Et.getValueCompletions (/opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:118517)
    at /opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:113629
```

**Comment by sandy081** [comment]
I see changes are merged into main and release branches. Hence closing.

**Comment by aeschli** [comment]
To verify:
- Create files `test.json` and `test.schema.json` in the same folder as described above
- Code complete in `test.json`

**Comment by rzhao271** [comment]
I get no error in the output view now, but I also get no code actions.

**Comment by aeschli** [comment]
I tested the example and I got the `new item` code completion
