### ISSUE TITLE
Git Project Manager no longer works on Insiders

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18187]
- VSCode Version: Code - Insiders 1.9.0-insider (80481edbdf1272a87ca54d4c48a829e0a134dffe, 2017-01-05T07:03:01.537Z)
- OS Version: Linux x64 4.8.0-30-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|Go|lukehoban|0.6.50|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.6.2|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.0.8|
|annotator|ryu1kn|0.10.1|

Not sure if this is an intentional breakage on our end or it's implemented badly?

Opening a project using [this extension](https://github.com/felipecaputo/git-project-manager) throws the following error:

```
shell.ts:423 vscode.commands.executeCommand(...).then(...).catch is not a function: TypeError: vscode.commands.executeCommand(...).then(...).catch is not a function
    at Object.exports.openProject (/home/daniel/.vscode-insiders/extensions/felipecaputo.git-project-manager-1.0.0/src/gitProjectManager.js:208:15)
    at onResolve (/home/daniel/.vscode-insiders/extensions/felipecaputo.git-project-manager-1.0.0/src/gitProjectManager.js:118:18)
    at Object.m [as _notify] (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:29915)
    at Object.enter (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:1483)
    at _run (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3311)
    at _completed (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:2752)
    at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9417
    at done (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:4612)
    at Object.m [as _notify] (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:30057)
    at Object.enter (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:1483)
    at _run (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3311)
    at _completed (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:2752)
    at e.resolveOk (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:7:12951)
    at p (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11433)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jrieken** [comment]
No breakage or anything. The extension assumes `executeCommand` returns a native ES6 promise which it doesn't. Therefore, you cannot call [`catch`](https://github.com/felipecaputo/git-project-manager/blob/master/src/gitProjectManager.js#L208)

**Comment by Tyriar** [comment]
Thanks I'll report it over there
