### ISSUE TITLE
Node.js debugging does not support reading from TTY

### ISSUE THREAD

**Issue by MitchK** [Microsoft/vscode#18193]
- VSCode Version: 1.8.1
- OS Version: MacOS 10.12.2

Steps to Reproduce:

1. Create Node.js script that reads from command line (install https://www.npmjs.com/package/readline-sync)
```
var readlineSync = require('readline-sync');

var input = readlineSync.question('Please enter your input');

console.log(input);
```
2. Create debug config:
```
        {
            "type": "node",
            "request": "launch",
            "name": "test",
            "program": "${workspaceRoot}/test.js",
            "cwd": "${workspaceRoot}"
        }
```

3. Debug crashes: 
```
 /dev/tty: Device not configured
stty: /dev/tty: Device not configured
/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/readline-sync.js:250
    if (res.error) { throw res.error; }
                     ^
Error: The current environment doesn't support interactive reading from TTY.
stty: /dev/tty: Device not configured
/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/read.sh: line 49: /dev/tty: Device not configured
stty: /dev/tty: Device not configured
    at readlineExt (/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/readline-sync.js:212:19)
    at tryExt (/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/readline-sync.js:249:15)
    at /Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/readline-sync.js:352:15
    at _readlineSync (/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/readline-sync.js:426:5)
    at getValidLine (/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/readline-sync.js:756:11)
    at Object.exports.question (/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/node_modules/readline-sync/lib/readline-sync.js:838:10)
    at Object.<anonymous> (/Users/i841712/repos/github.wdf.sap.corp/truerec/truerec-client/test.js:3:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by weinand** [comment]
@MitchK by default, node debugging uses the debug console which does not support reading input (because it is a REPL too). Please add a `console` attribute to your launch config and set it to either `integratedTerminal`or `integratedTerminal`.  See documentation: https://code.visualstudio.com/docs/editor/node-debugging#_node-console
