### ISSUE TITLE
TS Server fatal error:  UNC host '192.168.178.131' access is not allowed

### ISSUE THREAD

**Issue by badrenthe** [microsoft/vscode#182038]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.4

**Steps to reproduce crash**

1. start visual code vanaf een workspace link met hierin een not allowed allowedUNCHosts

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host '192.168.178.131' access is not allowed
    at Object.watchFile (node:fs:2342:14)
    at fsWatchFileWorker (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8594:11)
    at c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8243:15
    at createSingleWatcherPerName (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7764:16)
    at pollingWatchFile (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8238:12)
    at watchFile2 (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8073:16)
    at watchMissingFileSystemEntry (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8331:14)
    at fsWatchHandlingExistenceOnHost (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8262:72)
    at c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8252:15
    at createSingleWatcherPerName (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7764:16)
    at fsWatch (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8247:12)
    at Object.watchFile2 [as watchFile] (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8098:16)
    at watchFile (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116881:67)
    at Object.watchFile (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116900:284)
    at c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174627:164
    at _ProjectService.forEachConfigFileLocation (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174677:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174620:10)
    at InferredProject2.addRoot (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172893:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174418:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176043:12)
    at c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:64
    at flatMap (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:24)
    at updateOpen (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177418:29)
    at c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:69
    at IpcIOSession.executeWithRequestId (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179977:14)
    at IpcIOSession.executeCommand (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:29)
    at IpcIOSession.onMessage (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180027:51)
    at process.<anonymous> (c:\Tools\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181594:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.48GB free)|
|Process Argv|D:\\Data\\Documenten\\2023\\VisualCode\\lokaal\\uitslag.code-workspace --crash-reporter-id 6492cf66-980a-4b67-ae72-a7f58f2f48e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.25.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.78.4
php-debug|xde|1.32.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30730053
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052

```

</details>

**Comment by bpasero** [comment]
@badrenthe can you see if https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths helps?
