### ISSUE TITLE
TS Server fatal error:  UNC host 'raidrive-user' access is not allowed

### ISSUE THREAD

**Issue by naescolaDevs** [microsoft/vscode#182074]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230509

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host 'raidrive-user' access is not allowed
    at Object.watchFile (node:fs:2342:14)
    at fsWatchFileWorker (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8561:11)
    at c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8208:15
    at createSingleWatcherPerName (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:7729:16)
    at pollingWatchFile (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8203:12)
    at watchFile2 (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8038:16)
    at watchMissingFileSystemEntry (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8296:14)
    at fsWatchHandlingExistenceOnHost (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8227:72)
    at c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8217:15
    at createSingleWatcherPerName (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:7729:16)
    at fsWatch (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8212:12)
    at Object.watchFile2 [as watchFile] (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:8063:16)
    at watchFile (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:117607:67)
    at Object.watchFile (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:117626:282)
    at _AutoImportProviderProject.addMissingFileWatcher (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:174504:58)
    at c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:174385:35
    at c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:19805:21
    at Map.forEach (<anonymous>)
    at mutateMap (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:19803:10)
    at updateMissingFilePathsWatch (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:117499:3)
    at _AutoImportProviderProject.updateGraphWorker (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:174381:7)
    at _AutoImportProviderProject.updateGraph (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:174211:32)
    at _AutoImportProviderProject.updateGraph (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:175300:37)
    at updateProjectIfDirty (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:175917:35)
    at InferredProject2.getPackageJsonAutoImportProvider (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:174919:9)
    at InferredProject2.updateGraph (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:174237:12)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:176601:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:178219:12)
    at c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:178449:64
    at flatMap (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:2572:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:178449:24)
    at updateOpen (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:179629:29)
    at c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:182201:69
    at IpcIOSession.executeWithRequestId (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:182193:14)
    at IpcIOSession.executeCommand (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:182201:29)
    at IpcIOSession.onMessage (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:182243:51)
    at process.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230509\node_modules\typescript\lib\tsserver.js:183823:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.96GB free)|
|Process Argv|--crash-reporter-id afaf066a-15ba-4a87-93e9-e41a839b1057|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
xml|Dot|2.5.1
prettier-vscode|esb|9.12.0
code-runner|for|0.12.0
vscode-colorize|kam|0.11.1
vscode-language-babel|mgm|0.0.39
vscode-typescript-next|ms-|5.1.20230509
material-icon-theme|PKi|4.27.0
LiveServer|rit|5.7.9
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051
showsbindicator:30730056
pythongtdpathcf:30731979

```

</details>

**Comment by bpasero** [comment]
Beginning with VS Code `1.78.1` accessing any UNC path (those that begin with `\\`) on Windows is blocked to mitigate a security risk that is further explained in this [Security Advisory](https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr).

Please refer to https://aka.ms/vscode-windows-unc for more information how to make your specific UNC path work again.

**Comment by mjbvz** [comment]
Duplicate of #182070
