### ISSUE TITLE
Extensions cannot be installed if /tmp is on a different filesystem

### ISSUE THREAD

**Issue by jake-arkinstall** [microsoft/vscode#182029]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0 insider
- OS Version: NixOS 22.11

Steps to Reproduce:

1. Try to install an extension
2. See the following error:

```
[error] EXDEV: cross-device link not permitted, rename '/tmp/mdTslY7h' -> '/home/my-username/.vscode-insiders/extensions/github.copilot-nightly-1.86.86': EXDEV: EXDEV: cross-device link not permitted, rename '/tmp/mdTslY7h' -> '/home/my-username/.vscode-insiders/extensions/github.copilot-nightly-1.86.86'
    at e.ExtensionsScanner.u (/nix/store/z32xxgv0ixrysvwvpi9qlhq2i3w92ir0-vscode-latest/lib/vscode/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:88:15401)
    at async e.ExtensionsScanner.extractUserExtension (/nix/store/z32xxgv0ixrysvwvpi9qlhq2i3w92ir0-vscode-latest/lib/vscode/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:88:12624)
    at async ee.v (/nix/store/z32xxgv0ixrysvwvpi9qlhq2i3w92ir0-vscode-latest/lib/vscode/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:88:18556)
    at async ee.y (/nix/store/z32xxgv0ixrysvwvpi9qlhq2i3w92ir0-vscode-latest/lib/vscode/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:88:20167)
    at async ee.h (/nix/store/z32xxgv0ixrysvwvpi9qlhq2i3w92ir0-vscode-latest/lib/vscode/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:88:18131)
```

/tmp is on a different filesystem for me, so the file cannot simply be renamed as it was when extension installation was performed within the extension dir. I believe this was introduced by #181893 (I am not sure - this is my first insiders install)

**Comment by matusbielik** [comment]
I'm having the very same problem, on insiders build only, version `1.79.0`

**Comment by busybox11** [comment]
Same issue here:
```
Version: 1.79.0-insider
Commit: efb49cc271d6eea5634ac395e36e1e4cd108a447
Date: 2023-05-10T05:23:17.106Z
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.1-arch1-1
Sandboxed: Yes
```

**Comment by kennystrawnmusic** [comment]
Also affected — this time running the Snap version of code-insiders which I installed after having first installed snapd from the AUR (the reason why I’m not using [`visual-studio-code-insiders-bin`](https://aur.archlinux.org/packages/visual-studio-code-insiders-bin) is because it has this rather bizarre tendency to beg you to install updates even if the AUR helper you installed it with — in my case Paru — sees it as already up-to-date) on my Arch Linux machine. Sees “/tmp/XXXXX -> /var/lib/snapd/X” as an invalid cross-device link and system throws EXDEV because the downloaded extensions are being downloaded to /tmp instead of where they actually belong.

**Comment by furai** [comment]
I believe it was actually connected to unpacking VSIX cause I have downloaded the extensions manually and tried to update them using command line installation method: `code-insiders --install-extension path-to-extension.vsix` and it failed with same error.

Anyway, since that commit is reverted - now everything works again.
