### ISSUE TITLE
TS Server fatal error:  UNC host 'wsl.localhost' access is not allowed

### ISSUE THREAD

**Issue by domzack** [microsoft/vscode#182062]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️ 

**TypeScript Version:** 5.0.4

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host 'wsl.localhost' access is not allowed
    at Object.watchFile (node:fs:2342:14)
    at fsWatchFileWorker (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8594:11)
    at c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8243:15
    at createSingleWatcherPerName (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7764:16)
    at pollingWatchFile (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8238:12)
    at watchFile2 (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8073:16)
    at watchMissingFileSystemEntry (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8331:14)
    at fsWatchHandlingExistenceOnHost (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8262:72)
    at c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8252:15
    at createSingleWatcherPerName (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7764:16)
    at fsWatch (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8247:12)
    at Object.watchFile2 [as watchFile] (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8098:16)
    at watchFile (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116881:67)
    at Object.watchFile (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:116900:284)
    at c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174627:164
    at _ProjectService.forEachConfigFileLocation (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174677:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174620:10)
    at InferredProject2.addRoot (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172893:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174418:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176043:12)
    at c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:64
    at flatMap (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:24)
    at updateOpen (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177418:29)
    at c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:69
    at IpcIOSession.executeWithRequestId (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179977:14)
    at IpcIOSession.executeCommand (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:29)
    at IpcIOSession.onMessage (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180027:51)
    at process.<anonymous> (c:\Users\eusou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181594:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.85GB free)|
|Process Argv|--crash-reporter-id ef0d8f1f-7945-4db1-beed-7bcda98943f8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-browser-sync|jas|1.3.1
vscode-language-pack-pt-BR|MS-|1.78.2023051009
remote-wsl|ms-|0.78.4
live-server|ms-|0.4.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052
pythongtdpathcf:30731979

```

</details>

**Comment by bpasero** [comment]
Beginning with VS Code `1.78.1` accessing any UNC path (those that begin with `\\`) on Windows is blocked to mitigate a security risk that is covered in this [Security Advisory](https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr).

Please refer to https://aka.ms/vscode-windows-unc for more information how to make your specific UNC path work again.
