### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: r:/123rfnext/node_modules/@types/react/index.d.ts linked to nonexistent file //10.22.2.42/www/123rfnext/node_modules/@types/react/index.d.ts

### ISSUE THREAD

**Issue by Rynkato** [microsoft/vscode#182145]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.4

**Steps to reproduce crash**

1. Just start the app, and open a project.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: r:/123rfnext/node_modules/@types/react/index.d.ts linked to nonexistent file //10.22.2.42/www/123rfnext/node_modules/@types/react/index.d.ts
    at realPath (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42011:9)
    at getOriginalAndResolvedFileName (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40972:28)
    at createResolvedModuleWithFailedLookupLocationsHandlingSymlink (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40797:48)
    at nodeModuleNameResolverWorker (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41943:10)
    at nodeModuleNameResolver (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41878:10)
    at resolveModuleName (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41628:18)
    at resolveModuleName2 (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122831:27)
    at Object.resolve (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122858:47)
    at resolveNamesWithLocalCache (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122896:29)
    at Object.resolveModuleNameLiterals (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122981:12)
    at InferredProject2.resolveModuleNameLiterals (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171594:33)
    at resolveModuleNamesWorker (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118147:20)
    at resolveModuleNamesReusingOldState (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118243:14)
    at processImportedModules (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119779:27)
    at findSourceFileWorker (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119541:7)
    at findSourceFile (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119406:20)
    at c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119355:22
    at getSourceFileFromReferenceWorker (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119324:26)
    at processSourceFile (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119353:5)
    at processRootFile (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119149:5)
    at c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117934:41
    at forEach (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2308:22)
    at createProgram (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117934:5)
    at synchronizeHostData (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135422:15)
    at Object.getProgram (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135494:5)
    at InferredProject2.updateGraphWorker (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172176:41)
    at InferredProject2.updateGraph (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172113:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174423:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176043:12)
    at c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:64
    at flatMap (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:24)
    at updateOpen (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177418:29)
    at c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:69
    at IpcIOSession.executeWithRequestId (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179977:14)
    at IpcIOSession.executeCommand (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:29)
    at IpcIOSession.onMessage (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180027:51)
    at process.<anonymous> (c:\Users\Manraj Randhawa\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181594:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.90GB free)|
|Process Argv|--crash-reporter-id 5476289f-bca7-4f3d-aa82-562f9916be63|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.3
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
laravel-goto-view|cod|1.3.8
es7-react-js-snippets|dsz|4.4.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
chatgpt-vscode|gen|0.0.8
laravel-create-view|gli|0.0.6
laravel-blade-wrapper|IHu|1.0.1
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
csharp|ms-|1.25.7
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.0
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.34.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.17.0
swagger-php-annotation|qvt|1.1.1
vscode-yaml|red|1.12.2
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.20.14
autoimport|ste|1.5.4
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixhidewlkth:30730051
hidesbindicator:30730055

```

</details>

**Comment by dngda** [comment]
check pinned issue #182070.

try configure the host to be allowed via the `security.allowedUNCHosts` setting.
if in your context, then add `//10.22.2.42/`

**Comment by bpasero** [comment]
Just to clarify: the hostname is `10.22.2.42` to be added to the setting, excluding any slash or backslash!
