### ISSUE TITLE
Integrated terminal stops responding in Powershell on Ctrl+C

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#182134]
1. Open the integrated terminal with Powershell (7.2.11)
2. Press Ctrl+C
3. The terminal no longer responds to any input 🐛 

This does not happen with cmd.exe

**Comment by connor4312** [comment]
Relevant error:

```
workbench.desktop.main.js:sourcemap:688 Uncaught TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at s (workbench.desktop.main.js:sourcemap:688:4739)
    at e.ShellIntegrationAddon.u (workbench.desktop.main.js:sourcemap:688:2879)
    at e.ShellIntegrationAddon.r (workbench.desktop.main.js:sourcemap:688:2021)
    at t.OscHandler._handler (workbench.desktop.main.js:sourcemap:688:1334)
    at t.OscHandler.end (OscParser.ts:223:18)
    at t.OscParser.end (OscParser.ts:159:45)
    at c.parse (EscapeSequenceParser.ts:777:43)
    at E.parse (InputHandler.ts:485:35)
    at n._action (CoreTerminal.ts:145:99)
    at n._innerWrite (WriteBuffer.ts:164:27)
    at WriteBuffer.ts:124:29
```

**Comment by meganrogge** [comment]
The fix for this was merged today, afk at the moment but let us know if you see it tomorrow
