### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#182197]
Got this error when running out of sources and when closing the settings editor

```
 ERR Cannot read properties of undefined (reading 'dragStartDisposable'): TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
    at ListView._splice (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/list/listView.js:334:22)
    at ListView.splice (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/list/listView.js:319:29)
    at vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/list/listWidget.js:1121:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/common/event.js:1087:23)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/list/listWidget.js:1121:32)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/tree/abstractTree.js:1077:19)
    at IndexTreeModel._setListNodeCollapseState (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/tree/indexTreeModel.js:266:23)
    at IndexTreeModel._setCollapseState (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/tree/indexTreeModel.js:237:33)
    at vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/tree/indexTreeModel.js:233:63
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/common/event.js:1087:23)
    at IndexTreeModel.setCollapsed (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/tree/indexTreeModel.js:233:39)
    at ObjectTreeModel.setCollapsed (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/tree/objectTreeModel.js:181:31)
    at TOCTree.collapseAll (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/browser/ui/tree/abstractTree.js:1358:24)
    at SettingsEditor2.triggerSearch (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1085:34)
    at SettingsEditor2.onSearchInputChanged (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1028:24)
    at vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:377:60
    at vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/common/async.js:278:32
```

**Comment by joaomoreno** [comment]
@rzhao271 Let me know if it comes down to a tree issue.
