### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: y:/CodaExample/node_modules/coda-js/build/index.d.ts linked to nonexistent file //Arda/Ainu/CodaExample/node_modules/coda-js/build/index.d.ts

### ISSUE THREAD

**Issue by Amorano** [microsoft/vscode#182119]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.4

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: y:/CodaExample/node_modules/coda-js/build/index.d.ts linked to nonexistent file //Arda/Ainu/CodaExample/node_modules/coda-js/build/index.d.ts
    at realPath (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42011:9)
    at getOriginalAndResolvedFileName (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40972:28)
    at createResolvedModuleWithFailedLookupLocationsHandlingSymlink (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40797:48)
    at nodeModuleNameResolverWorker (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41943:10)
    at nodeModuleNameResolver (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41878:10)
    at resolveModuleName (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41628:18)
    at resolveModuleName2 (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122831:27)
    at Object.resolve (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122858:47)
    at resolveNamesWithLocalCache (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122896:29)
    at Object.resolveModuleNameLiterals (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122981:12)
    at InferredProject2.resolveModuleNameLiterals (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171594:33)
    at resolveModuleNamesWorker (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118147:20)
    at resolveModuleNamesReusingOldState (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118243:14)
    at processImportedModules (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119779:27)
    at findSourceFileWorker (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119541:7)
    at findSourceFile (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119406:20)
    at c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119355:22
    at getSourceFileFromReferenceWorker (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119324:26)
    at processSourceFile (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119353:5)
    at processRootFile (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119149:5)
    at c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117934:41
    at forEach (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2308:22)
    at createProgram (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117934:5)
    at synchronizeHostData (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135422:15)
    at Object.getProgram (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135494:5)
    at InferredProject2.updateGraphWorker (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172176:41)
    at InferredProject2.updateGraph (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172113:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174423:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176043:12)
    at c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:64
    at flatMap (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:24)
    at updateOpen (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177418:29)
    at c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:69
    at IpcIOSession.executeWithRequestId (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179977:14)
    at IpcIOSession.executeCommand (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:29)
    at IpcIOSession.onMessage (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180027:51)
    at process.<anonymous> (c:\Users\amora\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181594:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.68GB free)|
|Process Argv|Y:\\_junk\\_junk.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.25.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
remote-containers|ms-|0.292.0

</details>

**Comment by mjbvz** [comment]
The latest security release restricts access to network drives. See #182070 for details and how to workaround this
