### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: z:/home/eriscrypt/code/work/interport/api/node_modules/ethers/lib/index.d.ts linked to nonexistent file //wsl.localhost/Ubuntu/home/eriscrypt/code/work/interport/api/node_modules/ethers/lib/index.d.ts

### ISSUE THREAD

**Issue by eriscrypt** [microsoft/vscode#182420]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by eriscrypt** [comment]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.4

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: z:/home/eriscrypt/code/work/interport/api/node_modules/ethers/lib/index.d.ts linked to nonexistent file //wsl.localhost/Ubuntu/home/eriscrypt/code/work/interport/api/node_modules/ethers/lib/index.d.ts
    at realPath (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:42011:9)
    at getOriginalAndResolvedFileName (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40972:28)
    at createResolvedModuleWithFailedLookupLocationsHandlingSymlink (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:40797:48)
    at nodeModuleNameResolverWorker (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41943:10)
    at nodeModuleNameResolver (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41878:10)
    at resolveModuleName (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41628:18)
    at resolveModuleName2 (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122831:27)
    at Object.resolve (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122858:47)
    at resolveNamesWithLocalCache (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122896:29)
    at Object.resolveModuleNameLiterals (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122981:12)
    at InferredProject2.resolveModuleNameLiterals (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171594:33)
    at resolveModuleNamesWorker (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118147:20)
    at resolveModuleNamesReusingOldState (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118243:14)
    at processImportedModules (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119779:27)
    at findSourceFileWorker (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119541:7)
    at findSourceFile (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119406:20)
    at c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119355:22
    at getSourceFileFromReferenceWorker (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119324:26)
    at processSourceFile (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119353:5)
    at processRootFile (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119149:5)
    at c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117934:41
    at forEach (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2308:22)
    at createProgram (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117934:5)
    at synchronizeHostData (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135422:15)
    at Object.getProgram (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135494:5)
    at InferredProject2.updateGraphWorker (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172176:41)
    at InferredProject2.updateGraph (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172113:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174423:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176043:12)
    at c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:64
    at flatMap (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176273:24)
    at updateOpen (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177418:29)
    at c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:69
    at IpcIOSession.executeWithRequestId (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179977:14)
    at IpcIOSession.executeCommand (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179985:29)
    at IpcIOSession.onMessage (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180027:51)
    at process.<anonymous> (c:\Users\erisc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181594:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (6.55GB free)|
|Process Argv|--crash-reporter-id 080856fc-1c39-40cf-ae84-5905f9b50a6d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database-client2|cwe|6.4.5
dscodegpt|Dan|2.1.6
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.6.0
prettier-vscode|esb|9.12.0
copilot|Git|1.86.82
vscode-graphql|Gra|0.8.7
vscode-graphql-syntax|Gra|1.1.0
vue-snippets|hol|1.0.4
rest-client|hum|0.25.1
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.25.0
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.4
makefile-tools|ms-|0.7.0
remote-explorer|ms-|0.4.0
color-highlight|nau|2.5.0
hardhat-solidity|Nom|0.7.1
material-icon-theme|PKi|4.27.0
prisma|Pri|4.14.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
svg-preview|Sim|2.8.3
vscode-icons|vsc|12.4.0
volar|Vue|1.2.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
pythongtdpathcf:30739705

```

</details>
