### ISSUE TITLE
TS Server fatal error:  Can't open file: No file descriptors available

### ISSUE THREAD

**Issue by flex-junwoo** [microsoft/vscode#182585]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.4-sdk

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Libzip Error: Can't open file: No file descriptors available
    at ZipFS.makeLibzipError (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:124672:25)
    at new ZipFS (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:124647:20)
    at ZipOpenFS.getZipSync (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:126837:18)
    at ZipOpenFS.makeCallSync (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:126717:17)
    at ZipOpenFS.watchFile (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:126680:17)
    at VirtualFS.watchFile (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:125886:24)
    at PosixFS.watchFile (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:125886:24)
    at NodePathFS.watchFile (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:125886:24)
    at fsWatchFileWorker (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8597:11)
    at /Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8243:15
    at createSingleWatcherPerName (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:7764:16)
    at pollingWatchFile (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8238:12)
    at watchFile2 (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8073:16)
    at watchMissingFileSystemEntry (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8331:14)
    at fsWatchHandlingExistenceOnHost (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8262:72)
    at /Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8252:15
    at createSingleWatcherPerName (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:7764:16)
    at fsWatch (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8247:12)
    at Object.watchFile2 [as watchFile] (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:8098:16)
    at watchFile (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:117063:67)
    at Object.watchFile (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:117082:284)
    at ConfiguredProject2.watchAffectingFileLocation (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:171901:45)
    at createFileWatcherOfAffectingLocation (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:123351:106)
    at watchAffectingLocationsOfResolution (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:123317:7)
    at watchFailedLookupLocationOfResolution (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:123307:5)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:123383:19)
    at Map.forEach (<anonymous>)
    at Object.finishCachingPerDirectoryResolution (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:122965:42)
    at ConfiguredProject2.updateGraphWorker (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:172443:26)
    at ConfiguredProject2.updateGraph (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:172377:32)
    at ConfiguredProject2.updateGraph (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:173559:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:175190:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:176283:26)
    at /Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:176563:64
    at flatMap (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:176563:24)
    at updateOpen (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:177731:29)
    at /Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:180298:69
    at IpcIOSession.executeWithRequestId (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:180290:14)
    at IpcIOSession.executeCommand (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:180298:29)
    at IpcIOSession.onMessage (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:180340:51)
    at IpcIOSession.onMessage (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/sdks/typescript/lib/tsserver.js:201:32)
    at process.<anonymous> (/Users/junukim/Documents/junwoo/flex-frontend/.yarn/cache/typescript-patch-ecf29fafbd-d26b6ba97b.zip/node_modules/typescript/lib/tsserver.js:181915:14)
    at process.emit (node:events:513:28)
    at process.emit (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:131979:25)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 7, 11|
|Memory (System)|32.00GB (4.89GB free)|
|Process Argv|--crash-reporter-id 403fced0-605d-4615-9367-d294b7f4b8f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|3.0.0
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.1
githistory|don|0.6.20
gitlens|eam|13.6.0
prettier-vscode|esb|9.12.0
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-yarn|gam|2.1.0
copilot|Git|1.86.82
vscode-codeowners|jas|1.1.1
marp-vscode|mar|2.6.0
git-graph|mhu|1.30.0
gradle-language|nac|0.2.3
vscode-twoslash-queries|Ort|1.1.0
tsimporter|pmn|2.0.1
vscode-xml|red|0.25.0
vs-code-prettier-eslint|rve|5.1.0
code-spell-checker|str|2.20.4
move-ts|str|1.12.0
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.4.0
gitblame|wad|10.2.0
vscode-todo-highlight|way|1.0.5
pretty-ts-errors|yoa|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
pythongtdpathcf:30739705

```

</details>

**Comment by mjbvz** [comment]
> `ZipFS.makeLibzipError (/Users/junukim/Documents/junwoo/flex-frontend/.pnp.cjs:`

This indicates that an extension or TS server plugin is causing the issue (possibly zipfs?). Please file this issue against them
