### ISSUE TITLE
Remotes are broken: this.c.makeConnection is not a function

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#182596]
Version: 1.79.0-insider
Commit: 7a7d45793b76351a2783d266a381ae5ef450c08a
Date: 2023-05-16T05:23:57.470Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.14.0-1048-oem

- open a wsl or a dev containers window 
- fails with a notification:  
Could not fetch remote environment. this.c.makeConnection is not a function
```
ERR TypeError: this.c.makeConnection is not a function
	at e.ExtHostManagedSockets.$openRemoteSocket (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:84772)
	at s.N (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11620)
	at s.M (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11338)
	at s.H (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10431)
	at s.G (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9412)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:8200
	at w.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at u.deliver (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at i.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at b.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14863)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:32461
	at w.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at u.deliver (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at i.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at b.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14863)
	at MessagePortMain.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30587)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

**Comment by menzels** [comment]
I see the same error, yesterdays version worked fine.

**Comment by menzels** [comment]
and it is fixed: Version: 1.79.0-insider (user setup)
Commit: 9084e081d4e89ed8ab67fce340d573c4e1378939
Date: 2023-05-15T05:20:50.327Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by aeschli** [comment]
ERR this._factory.makeConnection is not a function: TypeError: this._factory.makeConnection is not a function
	at ExtHostManagedSockets.$openRemoteSocket (c:\Users\martinae\workspaces\vscode\out\vs\workbench\api\common\extHostManagedSockets.js:44:48)
	at RPCProtocol._doInvokeHandler (c:\Users\martinae\workspaces\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:381:27)
	at RPCProtocol._invokeHandler (c:\Users\martinae\workspaces\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:366:45)
	at RPCProtocol._receiveRequest (c:\Users\martinae\workspaces\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:307:32)
	at RPCProtocol._receiveOneMessage (c:\Users\martinae\workspaces\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:234:26)
	at c:\Users\martinae\workspaces\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:115:52
	at Listener.invoke (c:\Users\martinae\workspaces\vscode\out\vs\base\common\event.js:660:27)
	at PrivateEventDeliveryQueue.deliver (c:\Users\martinae\workspaces\vscode\out\vs\base\common\event.js:836:38)
	at Emitter.fire (c:\Users\martinae\workspaces\vscode\out\vs\base\common\event.js:800:37)
	at BufferedEmitter.fire (c:\Users\martinae\workspaces\vscode\out\vs\base\parts\ipc\common\ipc.net.js:504:35)
	at c:\Users\martinae\workspaces\vscode\out\vs\workbench\api\node\extensionHostProcess.js:180:41
	at Listener.invoke (c:\Users\martinae\workspaces\vscode\out\vs\base\common\event.js:660:27)
	at PrivateEventDeliveryQueue.deliver (c:\Users\martinae\workspaces\vscode\out\vs\base\common\event.js:836:38)
	at Emitter.fire (c:\Users\martinae\workspaces\vscode\out\vs\base\common\event.js:800:37)
	at BufferedEmitter.fire (c:\Users\martinae\workspaces\vscode\out\vs\base\parts\ipc\common\ipc.net.js:504:35)
	at MessagePortMain.<anonymous> (c:\Users\martinae\workspaces\vscode\out\vs\workbench\api\node\extensionHostProcess.js:77:57)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)

**Comment by Ashesh3** [comment]
@aeschli for me now the forwarded ports on remote hosts are broken: https://github.com/microsoft/vscode/issues/182749
