### ISSUE TITLE
Forwarded ports on Remote SSH host are not working

### ISSUE THREAD

**Issue by Ashesh3** [microsoft/vscode#182749]
Type: <b>Bug</b>

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "msedge",
            "request": "launch",
            "name": "Launch Edge against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
[Window Title]
Visual Studio Code - Insiders

[Content]
Unable to launch browser: "Timed out waiting for browser connection"

The above worked fine till last update and it works fine in current stable release.
A browser window opens but then i get the above timeout message.

Output of `Shared` console output:
```
2023-05-17 17:36:05.169 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at b.s (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:23:4987)
    at b.q (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:23:4387)
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:23:3776
    at E.invoke (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:145)
    at u.deliver (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:2121)
    at a.fire (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:1729)
    at MessagePortMain.X (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:17:23920)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-05-17 17:36:05.267 [info] [SharedProcessTunnelService] Created tunnel 9: localhost:53846 (local) to localhost:53846 (remote).
2023-05-17 17:36:05.366 [info] Creating a socket (renderer-Tunnel-b0b59687-fa67-4920-ac08-10e91060276d)...
2023-05-17 17:36:05.366 [error] [remote-connection][Tunnel       ][b0b59…][initial][[object Object]] socketFactory.connect() failed or timed out. Error:
2023-05-17 17:36:05.366 [error] TypeError: Cannot read properties of undefined (reading 'connect')
    at D (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:15984)
    at r (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:16746)
    at o (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:19510)
    at C (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:20917)
    at async a.l (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:74:12326)
2023-05-17 17:36:05.367 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'connect'): TypeError: Cannot read properties of undefined (reading 'connect')
    at D (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:15984)
    at r (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:16746)
    at o (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:19510)
    at C (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:37:20917)
    at async a.l (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:74:12326)
2023-05-17 17:36:09.908 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at b.s (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:23:4987)
    at b.q (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:23:4387)
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:23:3776
    at E.invoke (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:145)
    at u.deliver (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:2121)
    at a.fire (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:1729)
    at MessagePortMain.X (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:17:23920)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

VS Code version: Code - Insiders 1.79.0-insider (f1258a5fbed44b8f84a097c73c1799c13c5c3646, 2023-05-17T05:27:38.052Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux arm64 5.15.0-1030-oracle
Remote OS version: Linux arm64 5.15.0-1030-oracle

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (15.42GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B7b22686f73744e616d65223a22446576567073227d/root/ayushma_fe --crash-reporter-id 237e4d4d-2bd3-44c9-af74-00a1a231eec1|
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|SSH: DevVps|
|OS|Linux arm64 5.15.0-1030-oracle|
|CPUs|Neoverse-N1 (4 x 0)|
|Memory (System)|23.43GB (11.89GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: DevVps|
|OS|Linux arm64 5.15.0-1030-oracle|
|CPUs|Neoverse-N1 (4 x 0)|
|Memory (System)|23.43GB (11.89GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
helium-icon-theme|hel|1.0.0
vscode-edge-devtools|ms-|2.1.1
remote-ssh|ms-|0.103.2023051015
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.0
ayu|tea|1.0.5
python-extended-snippets|tus|0.0.1
vscode-django|bat|1.10.0
vscode-tailwindcss|bra|0.9.11
ruff|cha|2023.16.0
rescript-vscode|che|1.16.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.6.0
copilot-chat|Git|0.1.2023051701
copilot-labs|Git|0.14.884
copilot-nightly|Git|1.86.92
svg|joc|1.5.2
i18n-ally|lok|2.9.1
MagicPython|mag|1.1.0
ts-error-translator|mat|0.8.0
git-graph|mhu|1.30.0
black-formatter|ms-|2023.2.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
vsliveshare|ms-|1.0.5864
vscode-thunder-client|ran|2.6.2
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
sonarlint-vscode|Son|3.17.0
vscode-pets|ton|1.22.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
j16hj152:30680472
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by Ashesh3** [comment]
Seems like forwarded ports are not working at all. None of my manually forwarded ports work.

**Comment by winsonyeap94** [comment]
Facing the same issue on my VSCode Insiders as well. Was working fine on 16th May 2023, and the problem started yesterday (17th May 2023).

For me, this occurs when I am trying to port-forward a webpage loaded on my virtual machine to my local machine.

Below is a sample of the logs from the "Shared" Output tab. The same error related to the `socketFactor.connect()` is faced.

```
2023-05-18 08:55:49.743 [error] [remote-connection][Tunnel       ][f94ed…][initial][[object Object]] socketFactory.connect() failed or timed out. Error:
2023-05-18 08:55:49.743 [error] TypeError: Cannot read properties of undefined (reading 'connect')
    at D (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:15984)
    at r (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:16746)
    at o (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:19510)
    at C (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:20917)
    at async a.l (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:74:12326)
2023-05-18 08:55:49.743 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'connect'): TypeError: Cannot read properties of undefined (reading 'connect')
    at D (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:15984)
    at r (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:16746)
    at o (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:19510)
    at C (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:37:20917)
    at async a.l (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:74:12326)
```

**Comment by bamurtaugh** [comment]
@alexr00 @chrmarti I believe this is the issue I am encountering.

**Comment by kuoruan** [comment]
The latest work version: 1.79.0.20230515

SystemSetup: https://az764295.vo.msecnd.net/insider/9084e081d4e89ed8ab67fce340d573c4e1378939/VSCodeSetup-x64-1.79.0-insider.exe
UserSetup: https://az764295.vo.msecnd.net/insider/9084e081d4e89ed8ab67fce340d573c4e1378939/VSCodeUserSetup-x64-1.79.0-insider.exe

**Comment by alexr00** [comment]
Range of commits where this occurred: 
https://github.com/microsoft/vscode/compare/9084e081...9233de80

**Comment by alexr00** [comment]
@connor4312 or @alexdima I think this is related to https://github.com/microsoft/vscode/pull/180263, though I'm not sure how yet.

**Comment by connor4312** [comment]
Thanks for the detailed issue!
