### ISSUE TITLE
Export ipynb (to HTML or PDF) is broken

### ISSUE THREAD

**Issue by 0jrm** [microsoft/vscode#182773]
Type: <b>Bug</b>

VScode fails to export ipynb to HTML and PDF. Here are some details:

--Versions--
(base) sh-5.1$ pip show jupyter
pip show nbconvert
pip show jinja2
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /home/jrm22n/anaconda3/lib/python3.9/site-packages
Requires: ipykernel, ipywidgets, jupyter-console, nbconvert, notebook, qtconsole
Required-by: 
Name: nbconvert
Version: 6.4.4
Summary: Converting Jupyter Notebooks
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /home/jrm22n/anaconda3/lib/python3.9/site-packages
Requires: beautifulsoup4, bleach, defusedxml, entrypoints, jinja2, jupyter-core, jupyterlab-pygments, mistune, nbclient, nbformat, pandocfilters, pygments, testpath, traitlets
Required-by: jupyter, jupyter-server, notebook, spyder
Name: Jinja2
Version: 2.11.3
Summary: A very fast and expressive template engine.
Home-page: https://palletsprojects.com/p/jinja/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/jrm22n/anaconda3/lib/python3.9/site-packages
Requires: MarkupSafe
Required-by: anaconda-project, bokeh, conda-build, conda-verify, cookiecutter, distributed, Flask, intake, jinja2-time, jupyter-server, jupyterlab, jupyterlab-server, nbconvert, notebook, numpydoc, Sphinx

--HTML error--
11:20:24.769 [info] Process Execution: ~/anaconda3/bin/python -m jupyter nbconvert /tmp/89e7a9a4-d736-449e-a3a6-138edba59d7c/pendulum_backward_Euler.ipynb --to html --output tmp-154NwpFQoyMkMCn.html --output-dir /tmp --debug
11:20:28.837 [error] Export failed Error: [NbConvertApp] Searching ['~', '~/.jupyter', '~/.local/etc/jupyter', '~/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_config in ~
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~
[NbConvertApp] Converting notebook /tmp/89e7a9a4-d736-449e-a3a6-138edba59d7c/pendulum_backward_Euler.ipynb to html
[NbConvertApp] Notebook name is 'tmp-154NwpFQoyMkMCn'
[NbConvertApp] Template paths:
	~/.local/share/jupyter/nbconvert/templates/lab
	~/anaconda3/share/jupyter/nbconvert/templates/lab
	~/.local/share/jupyter/nbconvert/templates/base
	~/anaconda3/share/jupyter/nbconvert/templates/base
	~/.var/app/com.visualstudio.code/data/jupyter
	~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates
	~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates/compatibility
	~/.local/share/jupyter
	~/.local/share/jupyter/nbconvert/templates
	~/.local/share/jupyter/nbconvert/templates/compatibility
	~/anaconda3/share/jupyter
	~/anaconda3/share/jupyter/nbconvert/templates
	~/anaconda3/share/jupyter/nbconvert/templates/compatibility
	/usr/local/share/jupyter
	/usr/local/share/jupyter/nbconvert/templates
	/usr/local/share/jupyter/nbconvert/templates/compatibility
	/usr/share/jupyter
	/usr/share/jupyter/nbconvert/templates
	/usr/share/jupyter/nbconvert/templates/compatibility
	~/.local/share/jupyter/nbconvert/templates
	~/anaconda3/share/jupyter/nbconvert/templates
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: CSSHTMLHeaderPreprocessor
[NbConvertApp] Attempting to load template index.html.j2
[NbConvertApp]     template_paths: ~/.local/share/jupyter/nbconvert/templates/lab:~/anaconda3/share/jupyter/nbconvert/templates/lab:~/.local/share/jupyter/nbconvert/templates/base:~/anaconda3/share/jupyter/nbconvert/templates/base:~/.var/app/com.visualstudio.code/data/jupyter:~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates:~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates/compatibility:~/.local/share/jupyter:~/.local/share/jupyter/nbconvert/templates:~/.local/share/jupyter/nbconvert/templates/compatibility:~/anaconda3/share/jupyter:~/anaconda3/share/jupyter/nbconvert/templates:~/anaconda3/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:~/.local/share/jupyter/nbconvert/templates:~/anaconda3/share/jupyter/nbconvert/templates
Traceback (most recent call last):
  File "~/anaconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "~/anaconda3/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "~/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 369, in start
    self.convert_notebooks()
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 541, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 506, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 435, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 210, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 392, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 151, in template
    self._template_cached = self._load_template()
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 362, in _load_template
    return self.environment.get_template(template_file)
  File "~/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "~/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "~/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 426, in load
    return loader.load(environment, name, globals)
  File "~/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "~/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "~/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "~/anaconda3/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "~/.local/share/jupyter/nbconvert/templates/lab/index.html.j2", line 12, in template
    {% set nb_title = nb.metadata.get('title', resources['metadata']['name']) | escape_html_keep_quotes %}
jinja2.exceptions.TemplateAssertionError: no filter named 'escape_html_keep_quotes'

    at hw.executeCommand (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:309048)
    at Sw.export (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:312395)
    at Iw.exportToFormat (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:317425)
    at Iw.performNbConvertExport (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:317194)
    at Iw.performExport (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:316869)
    at Iw.exportImpl (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:316497)
    at Iw.export (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:316253)
    at K_.export (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:456281)
    at e.ExtHostCommands.h (/app/extra/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:125307)

--PDF error--
11:17:17.585 [info] Process Execution: ~/anaconda3/bin/python -m pip list
11:17:35.230 [info] Process Execution: ~/anaconda3/bin/python -m jupyter nbconvert /tmp/c521f3ee-4cca-4c89-9ccb-382d679dd4b6/pendulum_backward_Euler.ipynb --to pdf --output tmp-154lWcH9iWTDgCR.pdf --output-dir /tmp --debug
11:17:39.635 [error] Export failed Error: [NbConvertApp] Searching ['~', '~/.jupyter', '~/.local/etc/jupyter', '~/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_config in ~
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~
[NbConvertApp] Converting notebook /tmp/c521f3ee-4cca-4c89-9ccb-382d679dd4b6/pendulum_backward_Euler.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-154lWcH9iWTDgCR'
[NbConvertApp] Template paths:
	~/.local/share/jupyter/nbconvert/templates/latex
	~/anaconda3/share/jupyter/nbconvert/templates/latex
	~/.local/share/jupyter/nbconvert/templates/base
	~/anaconda3/share/jupyter/nbconvert/templates/base
	~/.var/app/com.visualstudio.code/data/jupyter
	~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates
	~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates/compatibility
	~/.local/share/jupyter
	~/.local/share/jupyter/nbconvert/templates
	~/.local/share/jupyter/nbconvert/templates/compatibility
	~/anaconda3/share/jupyter
	~/anaconda3/share/jupyter/nbconvert/templates
	~/anaconda3/share/jupyter/nbconvert/templates/compatibility
	/usr/local/share/jupyter
	/usr/local/share/jupyter/nbconvert/templates
	/usr/local/share/jupyter/nbconvert/templates/compatibility
	/usr/share/jupyter
	/usr/share/jupyter/nbconvert/templates
	/usr/share/jupyter/nbconvert/templates/compatibility
	~/.local/share/jupyter/nbconvert/templates
	~/anaconda3/share/jupyter/nbconvert/templates
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Attempting to load template index.tex.j2
[NbConvertApp]     template_paths: ~/.local/share/jupyter/nbconvert/templates/latex:~/anaconda3/share/jupyter/nbconvert/templates/latex:~/.local/share/jupyter/nbconvert/templates/base:~/anaconda3/share/jupyter/nbconvert/templates/base:~/.var/app/com.visualstudio.code/data/jupyter:~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates:~/.var/app/com.visualstudio.code/data/jupyter/nbconvert/templates/compatibility:~/.local/share/jupyter:~/.local/share/jupyter/nbconvert/templates:~/.local/share/jupyter/nbconvert/templates/compatibility:~/anaconda3/share/jupyter:~/anaconda3/share/jupyter/nbconvert/templates:~/anaconda3/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:~/.local/share/jupyter/nbconvert/templates:~/anaconda3/share/jupyter/nbconvert/templates
[NbConvertApp] Support files will be in tmp-154lWcH9iWTDgCR_files/
[NbConvertApp] Making directory ./tmp-154lWcH9iWTDgCR_files
[NbConvertApp] Writing 54003 bytes to support file ./tmp-154lWcH9iWTDgCR_files/tmp-154lWcH9iWTDgCR_6_1.png
[NbConvertApp] Making directory ./tmp-154lWcH9iWTDgCR_files
[NbConvertApp] Writing 55038 bytes to support file ./tmp-154lWcH9iWTDgCR_files/tmp-154lWcH9iWTDgCR_8_1.png
[NbConvertApp] Writing 31850 bytes to notebook.tex
[NbConvertApp] Building PDF
Traceback (most recent call last):
  File "~/anaconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "~/anaconda3/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "~/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 369, in start
    self.convert_notebooks()
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 541, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 506, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 435, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/pdf.py", line 183, in from_notebook_node
    self.run_latex(tex_file)
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/pdf.py", line 153, in run_latex
    return self.run_command(self.latex_command, filename,
  File "~/anaconda3/lib/python3.9/site-packages/nbconvert/exporters/pdf.py", line 110, in run_command
    raise OSError("{formatter} not found on PATH, if you have not installed "
OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.

    at hw.executeCommand (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:309048)
    at _w.export (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:312913)
    at Iw.exportToFormat (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:317366)
    at Iw.performNbConvertExport (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:317194)
    at Iw.performExport (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:316869)
    at Iw.exportImpl (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:316497)
    at Iw.export (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:316253)
    at K_.export (~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:456281)
    at e.ExtHostCommands.h (/app/extra/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:125307)
11:17:39.636 [error] If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:46.685Z)
OS version: Linux x64 5.19.0-41-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 1155)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|30.97GB (16.68GB free)|
|Process Argv|--extensions-dir=/home/jrm22n/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --crash-reporter-id 1aab71df-4c0b-4790-b6eb-aeef98ebdfb9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab-formatter|Aff|2.10.51
cppincludeguard|aki|1.6.0
preview-pdf|ana|1.0.0
zip-extract-all|Anc|1.2.0
matlab-interactive-terminal|apo|0.4.0
matlab-extension-pack|bat|0.1.0
vscode-django|bat|1.10.0
matlab-code-run|bra|1.0.2
doxdocgen|csc|1.4.0
vscode-office|cwe|3.1.4
conda-wingman|DJS|0.2.1
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
c-cpp-runner|fra|5.4.0
fortran|Gim|0.2.0
matlab|Gim|3.0.2
copilot|Git|1.86.82
conda-cheatsheet|joj|1.2.8
vsc-python-indent|Kev|1.18.0
vscode-language-pack-pt-BR|MS-|1.78.2023051009
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.5
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
remote-explorer|ms-|0.4.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
vscode-ipython|pan|0.5.0
vscode-paste-and-indent|Rub|0.0.8
markdown-preview-enhanced|shd|0.6.8
matlab-complete|Sla|1.1.1
vscode-zipexplorer|sle|0.3.1
cmake|twx|0.0.17
vscode-lldb|vad|1.9.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by 0jrm** [comment]
Reinstalling VSCode with the latest .dev version solved the issue.
