### ISSUE TITLE
cannot type in interactive chat

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#182892]
I have seen this a few times over the last several days. I run `Start Code Chat` and am unable to type in the input box.

https://github.com/microsoft/vscode/assets/29464607/86cebb13-3fd8-4e0c-ba31-14516109f2df

Output:

```
ERR Canceled: Canceled
    at new L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1519:67484)
    at p.O (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:15383)
    at P.<computed>.F.charCodeAt.P.<computed> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:12673)
    at Object.getOriginalResource (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1528:19261)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1067:9422
    at Array.map (<anonymous>)
    at e.QuickDiffService.getQuickDiffs (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1067:9294)
    at Ne (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1882:6972)
    at h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1900:1935)
    at u.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:619:360)
    at I.participate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1900:5762)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2013.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1851:11149
```

**Comment by meganrogge** [comment]
at the time, `editMode: preview` and here are the context keys

![Screenshot 2023-05-18 at 10 23 44 AM](https://github.com/microsoft/vscode/assets/29464607/eed22aa0-dca7-4bb0-8edb-43614bb418d5)
