### ISSUE TITLE
Support links to SCM diff view matching git status' "modified: ...."

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#182882]
Currently we support files links in git status output like this:

![image](https://github.com/microsoft/vscode/assets/2193314/02be60fd-4a4c-4dd2-80f6-6cf0c091d2b9)

When it starts with "modified:", we could either replace the entire line with a link that opens the diff or just the "modified:" part.

**Comment by Tyriar** [comment]
@lszomoru is there a trick to open a git diff URI? I tried just switching the schema to `git` and it didn't work:

![image](https://github.com/microsoft/vscode/assets/2193314/389677c5-6cc8-4924-ac16-10e9cc07c0ce)

```
ERR Error: Unable to read file 'git:/c:/Github/microsoft/vscode/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts' (SyntaxError: Unexpected end of JSON input)
    at FileService.restoreReadError (fileService.js:462:20)
    at FileService.doReadFileStream (fileService.js:451:28)
    at async NativeTextFileService.doRead (textFileService.js:151:32)
    at async NativeTextFileService.readStream (textFileService.js:132:45)
    at async TextFileEditorModel.resolveFromFile (textFileEditorModel.js:324:33)
    at async TextFileEditorModel.resolve (textFileEditorModel.js:206:13)
    at async TextFileEditorModelManager.doResolve (textFileEditorModelManager.js:332:17)
    at async FileEditorInput.doResolveAsText (fileEditorInput.js:235:17)
    at async TextFileEditor.setInput (textFileEditor.js:62:39)
    at async EditorPanes.doSetInput (editorPanes.js:292:17)
    at async EditorPanes.doOpenEditor (editorPanes.js:166:44)
    at async EditorPanes.openEditor (editorPanes.js:65:24)
    at async editorGroupView.js:809:65
    at async TerminalLocalFileLinkOpener.open (terminalLinkOpeners.js:31:13)
    at async TerminalLinkManager._openLink (terminalLinkManager.js:133:13)
```

**Comment by Tyriar** [comment]
@lszomoru https://github.com/microsoft/vscode/blob/e59910162247765078b09ed74ebf5349a17e15da/extensions/git/src/uri.ts#L30-L31 is a 404?

**Comment by lszomoru** [comment]
My bad:
* https://github.com/microsoft/vscode/blob/main/extensions/git/src/uri.ts#L30-L31
* https://github.com/microsoft/vscode/blob/main/extensions/git/src/repository.ts#LL505C6-L505C6

**Comment by Tyriar** [comment]
Closing as out of scope as this wouldn't be implemented in core due to no knowledge of the git ref. It could be implemented in the git extension side but maybe not worth it?
