### ISSUE TITLE
TypeScript: Error processing request. No Project

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18292]
I was running "out of sources" and undid a bit of changes in dirty files (including a moved typescript file). In the console I saw the following:

```
shell.js:232 Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:6143:23)
    at IOSession.Session.getFileAndProjectWorker (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:68155:42)
    at IOSession.Session.getFileAndProjectWithoutRefreshingInferredProjects (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:68149:29)
    at IOSession.Session.getCodeFixes (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:68551:31)
    at Session.handlers.ts.createMap._a.(anonymous function) (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:67620:61)
    at IOSession.Session.executeCommand (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:68657:28)
    at IOSession.Session.onMessage (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:68677:35)
    at Interface.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/node_modules/typescript/lib/tsserver.js:69829:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)

```

**Comment by nissoh** [comment]
I believe i'm experiencing the same thing. 
i think vscode is caching stuff and causing this error to be totally persistent. moving project folder around seems to fix this issue until it occurs again.

**Comment by nissoh** [comment]
Ok, it seemed that vscode doesn't like my `tslint.json` configuration

````
{
    "rules": {
        "align": [true,
            "parameters",
            "statements"],
        "ban": false,
        "class-name": true,
        "curly": true,
        "eofline": true,
        "forin": true,
        "indent": [true, 4],
        "interface-name": true,
        "jsdoc-format": true,
        "label-position": true,
        "label-undefined": true,
        "max-line-length": [true, 140],
        "member-ordering": [false,
            "public-before-private",
            "static-before-instance",
            "variables-before-functions"
        ],
        "no-arg": true,
        "no-any": false,
        "no-bitwise": true,
        "no-consecutive-blank-lines": false,
        "no-console": [true,
            "debug",
            "info",
            "log",
            "time",
            "timeEnd",
            "trace"
        ],
        "no-construct": true,
        "no-constructor-vars": false,
        "no-debugger": true,
        "no-duplicate-key": true,
        "no-duplicate-variable": true,
        "no-empty": false,
        "no-eval": true,
        "no-require-imports": false,
        "no-switch-case-fall-through": true,
        "no-trailing-whitespace": true,
        "no-unused-expression": true,
        "no-unused-variable": true,
        "no-unreachable": true,
        "no-use-before-declare": false,
        "no-var-requires": false,
        "one-line": [true,
            "check-open-brace",
            "check-catch",
            "check-else",
            "check-whitespace"
        ],
        "quotemark": false,
        "radix": true,
        "semicolon": true,
        "switch-default": true,
        "triple-equals": [true, "allow-null-check"],
        "typedef": [true,
            "call-signature",
            "parameter",
            "property-declaration",
            "member-variable-declaration"
        ],
        "typedef-whitespace": [true, {
            "call-signature": "nospace",
            "index-signature": "nospace",
            "parameter": "nospace",
            "property-declaration": "nospace",
            "variable-declaration": "nospace"
        }],
        "use-strict": false,
        "variable-name": false,
        "whitespace": [true,
            "check-branch",
            "check-decl",
            "check-operator",
            "check-module",
            "check-separator",
            "check-type"
        ]
    },
    "style": {
        "semicolon": [true, "always"]
    }
}

````

**Comment by nissoh** [comment]
I will also add that i have more then one `tsconfig.json` in my root folder.

**Comment by mjbvz** [comment]
I have not see this error with recent typescript versions. Typescript has fixed a number of bugs since this was reported so this may have been addressed. 

Please give the current vscode insiders with TypeScript 2.3.2 a try and let me know if you still see this error

**Comment by oojacoboo** [comment]
I'm having this same issue on 2.3.2 with VSCode

`'quickinfo' request failed with error. Error processing request. No Project.`

**Comment by OrbitalJeffL** [comment]
I also have this issue with Version 1.15.1 on windows. Please advise.
