### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false

### ISSUE THREAD

**Issue by Guitaricet** [microsoft/vscode#183044]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.2.0-dev.20230517

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false
    at getDocumentRegistryEntry (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:133171:11)
    at Object.releaseDocumentWithKey (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:133268:19)
    at getOrCreateSourceFileByPath (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:141946:30)
    at Object.getOrCreateSourceFile (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:141930:14)
    at /Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:141862:42
    at Object.getSourceFileWithCache [as getSourceFile] (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:117940:24)
    at findSourceFileWorker (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:120333:23)
    at findSourceFile (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:120253:20)
    at /Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:120202:22
    at getSourceFileFromReferenceWorker (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:120186:69)
    at processSourceFile (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:120200:5)
    at processRootFile (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:119997:5)
    at /Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:118752:41
    at forEach (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:2325:22)
    at createProgram (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:118752:5)
    at synchronizeHostData (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:141886:15)
    at Object.getProgram (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:141958:5)
    at InferredProject2.updateGraphWorker (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:174588:41)
    at InferredProject2.updateGraph (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:174440:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:176830:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:178448:12)
    at /Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:178678:64
    at flatMap (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:2573:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:178678:24)
    at updateOpen (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:179858:29)
    at /Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:182430:69
    at IpcIOSession.executeWithRequestId (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:182422:14)
    at IpcIOSession.executeCommand (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:182430:29)
    at IpcIOSession.onMessage (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:182472:51)
    at process.<anonymous> (/Users/vlialin/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.2.20230517/node_modules/typescript/lib/tsserver.js:184052:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (Universal) (2946b1ee55db1d406526d3fd1df49250b2f8322d, 2023-05-18T05:30:11.573Z)
OS version: Darwin arm64 22.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id aed8bf1c-3b17-4596-9f72-570f2c85b661|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
copilot-chat|Git|0.1.2023051803
copilot-nightly|Git|1.86.105
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
vscode-typescript-next|ms-|5.2.20230517

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
j16hj152:30680472
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by Guitaricet** [comment]
Didn't expect to create a GitHub issue via "bug report" functionality in vscode. Feel free to ignore.
