### ISSUE TITLE
Native function `getClientRects` being very slow on startup

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#183216]
# Description

I manually installed the latest insiders (May 23, 2023). The 1st and 2nd startups were very slow. On the 2nd startup, I managed to capture the errors and CPU profile. 

<details>
<summary>console log as text</summary>

```
 INFO Ignoring configured affinity for 'vscodevim.vim' because extension host(s) are already running. Reload window.
log.ts:421  INFO Placing extension(s) vscodevim.vim on a separate extension host.
log.ts:431  WARN [Vue.volar]: Cannot register 'typescript.tsdk'. This property is already registered.
textMateTokenizationSupport.ts:51 Time limit reached when tokenizing line: export class KeybindingsSearchWidget extends SearchWidget {
tokenizeEncoded @ textMateTokenizationSupport.ts:51
TaskQueue.ts:93 task queue exceeded allotted deadline by 82ms
_process @ TaskQueue.ts:93
log.ts:421  INFO [perf] Render performance baseline is 63ms
log.ts:431  WARN [perf] Renderer reported VERY LONG TASK (903ms), starting profiling session '3fbadad0-8134-412b-bdcb-3b3461424b9f'
log.ts:441   ERR [PerfSampleError]: [PerfSampleError] by <<renderer>> in getClientRects
	 at getClientRects
	 at d (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:72:18080)
	 at readHorizontalRanges (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:72:18678)
	 at j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:698:8191)
	 at h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:698:7874)
	 at getVisibleRangesForRange (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:698:7505)
	 at getVisibleRangesForRange (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:698:4619)
	 at J (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:30718)
	 at visibleRangeForPosition (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:30979)
	 at visibleRangeForPosition (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:72:16152)
	 at prepareRender (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:701:4356)
	 at I (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:702:21243)
	 at (anonymous) (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:702:21145)
	 at U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:702:23699)
	 at G (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:702:21140)
	 at v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:702:19214)
	 at F (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:702:21115)
	 at execute (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:97:27257)
	 at Ct (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:97:27425)
log.ts:441   ERR [PerfSampleError]: [PerfSampleError] by <<renderer>> in caretRangeFromPoint
	 at caretRangeFromPoint
	 at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:7794)
	 at v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:7272)
	 at B (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:9569)
	 at o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:4058)
	 at g (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:1697)
	 at createMouseTarget (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:1383)
	 at p (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:13809)
	 at u (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:14203)
	 at (anonymous) (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:699:11759)
	 at (anonymous) (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:694:40773)
log.ts:441   ERR [PerfSampleError]: [PerfSampleError] by <<renderer>> in postMessage
	 at postMessage
	 at send (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1636:1564)
	 at H (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:13920)
	 at G (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:12908)
	 at (anonymous) (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:11918)
	 at invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:93:127)
	 at deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:93:2059)
	 at fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:93:1588)
	 at fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:564:15072)
	 at ee.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1636:1492)
log.ts:421  INFO [perf] stored profile to DISK 'file:///var/folders/ws/lk9gx2fn7qx09jl2l5zf6jwr0000gn/T/renderer-6f3c30.cpuprofile' 3fbadad0-8134-412b-bdcb-3b3461424b9f
log.ts:431  WARN [perf] Renderer reported VERY LONG TASK (864ms), starting profiling session '37f768d6-bfaf-4bbd-af60-b160ca002b6b'
```

</details>

<details>
  <summary>Image</summary>
<img width="1362" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/82d2f2e5-28c5-48b1-9ab0-e6b1e5498004">

</details>

CPU profile: https://drive.google.com/file/d/1Ee70sdifMZVsEdhp1EuR9HKO7oEUKawd/view?usp=sharing

# Version info

```
Version: 1.79.0-insider
Commit: 91070deb061201d493794eb1cfabc553b1f6fa8f
Date: 2023-05-23T05:20:26.078Z
Electron: 22.5.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
```

# Notes

@jrieken noted that the baseline performance number (see the logs above - 63ms) is also very slow compared for my machine, which should be true because vscode 1.78.2 gives 19ms. 

cc @jrieken

**Comment by ulugbekna** [comment]
I think I was using intel vscode on silicon
sorry for the noise

**Comment by deepak1556** [comment]
@ulugbekna just for posterity, how did you confirm it was intel version ?

**Comment by ulugbekna** [comment]
I didn't confirm per se -- just the next day when I was downloading the insiders, I noticed that I used the wrong "button" on vscode builds to download the insiders 🥲

**Comment by deepak1556** [comment]
Gotcha, prefer the macOS Universal build to avoid downloading for wrong arch. You can confirm the arch type from terminal with following command `file <path-to>/Visual Studio Code.app/Contents/MacOS/Electron`
