### ISSUE TITLE
Error: EIO: i/o error, read When using github copilot chat

### ISSUE THREAD

**Issue by NickLiu635** [microsoft/vscode#183763]
Does this issue occur when all extensions are disabled?: No,

- VS Code Version: 
```
Version: 1.79.0-insider (user setup)
Commit: 784e72bc4486b7ea5ad3447c506e31d949848592
Date: 2023-05-30T05:20:59.861Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```
- OS Version: 
```
版本	Windows 11 企业版
版本	22H2
安装日期	‎2022/‎9/‎22
操作系统版本	22621.1778
体验	Windows Feature Experience Pack 1000.22642.1000.0

处理器	Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90 GHz
机带 RAM	32.0 GB (31.8 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

wsl --version
WSL 版本： 1.2.5.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.51
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22621.1778

wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```
Steps to Reproduce:

1. Chat in Github Copilot Chat
2. get `EIO: i/o error, read`
3. then get a lot of errors in output(window)
```log
2023-05-30 16:26:05.818 [error] [Extension Host] unhandledRejection {"code":"Unknown","name":"Unknown (FileSystemError) (FileSystemError)"}
2023-05-30 16:26:06.822 [error] Error: EROFS: read-only file system, mkdir '/home/user/.vscode-server-insiders/data/logs/20230530T145047/exthost3/output_logging_20230530T161952': Unknown (FileSystemError) (FileSystemError): Error: EROFS: read-only file system, mkdir '/home/user/.vscode-server-insiders/data/logs/20230530T145047/exthost3/output_logging_20230530T161952'
	at Function.c (/home/user/.vscode-server-insiders/bin/784e72bc4486b7ea5ad3447c506e31d949848592/out/vs/workbench/api/node/extensionHostProcess.js:102:28018)
	at Object.createDirectory (/home/user/.vscode-server-insiders/bin/784e72bc4486b7ea5ad3447c506e31d949848592/out/vs/workbench/api/node/extensionHostProcess.js:102:25675)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
![image](https://github.com/microsoft/vscode/assets/36353209/e3daff25-6e3b-44bc-a68f-6659ec8ddb38)

and
```
user@liuxiangtian01:~/.vscode-server-insiders/data/logs/20230530T145047/exthost3$ ll
total 28
drwxr-xr-x 5 user user 4096 May 30 15:08 ./
drwxr-xr-x 5 user user 4096 May 30 15:08 ../
drwxr-xr-x 2 user user 4096 May 30 15:08 output_logging_20230530T150831/
-rw-r--r-- 1 user user 4113 May 30 15:10 remoteexthost.log
drwxr-xr-x 2 user user 4096 May 30 15:08 vscode.git/
drwxr-xr-x 2 user user 4096 May 30 15:08 vscode.github/

```

**Comment by lszomoru** [comment]
@alexdima, could you please help with routing this issue? Thanks!

**Comment by NickLiu635** [comment]
This issue is no longer repeated in the new version.
