### ISSUE TITLE
Search ENAMETOOLONG with *any* exclusions (New Version?)

### ISSUE THREAD

**Issue by bradlitterell** [microsoft/vscode#184006]
Type: <b>Bug</b>

Select SearchTool
Enter "OSSL_INCLUDE_SUBDIR" into SEARCH box
set search options:

case-sensitive: false
whole-word: false
regex: false
files to include: ./
files to exclude: *.map
Enable exclude button: Clicked

Expected: Search results
Actual: "Error: A system error occurred (spawn ENAMETOOLONG)"

2023-05-31 17:37:13.882 [error] A system error occurred (spawn ENAMETOOLONG): Error: A system error occurred (spawn ENAMETOOLONG)
    at M (vscode-file://vscode-app/c:/Users/bradlit/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1836:6483)
    at vscode-file://vscode-app/c:/Users/bradlit/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1844:4256
    at async vscode-file://vscode-app/c:/Users/bradlit/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1844:2747
    at async e.SearchService.textSearch (vscode-file://vscode-app/c:/Users/bradlit/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1844:2022)
    at async e.SearchModel.H (vscode-file://vscode-app/c:/Users/bradlit/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2249:26700)

This happens with-or-without extension, and even if nothing is listed in the files-to-exclude box.  Merely checking the exclude option produces the problem.

Therefore, this appears to be different from https://github.com/microsoft/vscode/issues/98514

VS Code version: Code - Insiders 1.79.0-insider (b9a77b3c7b43f229a430b28070250d55e5d14858, 2023-05-31T16:31:59.161Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (9.03GB free)|
|Process Argv|--crash-reporter-id 2f3b771b-fd3e-4208-9190-23c3b96edf17|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30754469
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
0bg3d529:30680467
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887
welcomedialog:30756234

```

</details>

**Comment by bradlitterell** [comment]
never mind.  This is a dupe, of #98514.  Following the trace instructions there, I can see the exclusions list on my workspace file is VERY! long - because it contains a copy of my .gitignore exclusions, which were added in the past via the Hide .GitIgnored Extension.
