### ISSUE TITLE
Connection to WSL

### ISSUE THREAD

**Issue by bwassim** [microsoft/vscode#184426]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2 
- OS Version: Windows 10

I have this error: Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)
Steps to Reproduce:

1. Open VsCode
2. Output of the console 

log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:421  INFO Invoking resolveAuthority(wsl)...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][1267ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][2346ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][3249ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][4020ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][5164ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][6031ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][7001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][7863ms] returned 127.0.0.1:57011
log.ts:421  INFO resolveAuthority(wsl) returned '127.0.0.1:57011' after 7866 ms
log.ts:421  INFO Creating a socket (renderer-Management-1ec07570-9540-40d8-bf62-00c6e09f4631)...
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-162f95d9-7c97-47e7-9025-3c294cc6263f)...
browserSocketFactory.ts:79 WebSocket connection to 'ws://127.0.0.1:57011/stable-b3e4e68a0bc097f0ae7907b217c1119af9e03435?reconnectionToken=1ec07570-9540-40d8-bf62-00c6e09f4631&reconnection=false&skipWebSocketFrames=false' failed: 
v @ browserSocketFactory.ts:79
log.ts:421  INFO Creating a socket (renderer-Management-1ec07570-9540-40d8-bf62-00c6e09f4631) returned an error after 1006 ms.
log.ts:441   ERR [remote-connection][Management   ][1ec07…][initial][127.0.0.1:57011] socketFactory.connect() failed or timed out. Error:
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:165:20)
log.ts:441   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:165:20)
log.ts:421  INFO Invoking resolveAuthority(wsl)...

**Comment by bwassim** [comment]
Issue solved with wsl --shutdown
