### ISSUE TITLE
Cannot read properties of null (reading 'domNode')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#184494]
I was playing around with a GH issues notebook, changing between an empty profile without extensions and a profile where I was able to use the notebook. I think I was undoing changes from the changes view.

```
[79622:0607/133653.509806:INFO:CONSOLE(244)] "%c  ERR color: #f33 Cannot read properties of null (reading 'domNode'): TypeError: Cannot read properties of null (reading 'domNode')
    at NotebookCellListView.updateItemInDOM (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:638:22)
    at NotebookCellListView.render (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:547:26)
    at NotebookCellListView.render (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellListView.js:19:19)
    at NotebookCellListView.updateElementHeight (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:309:18)
    at NotebookCellList.updateElementHeight2 (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:983:34)
    at doLayout (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:1732:28)
    at NotebookEditorWidget.layoutNotebookCell (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:1743:17)
    at CellOutputContainer._relayoutCell (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.js:584:33)
    at CellOutputContainer.render (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.js:392:22)
    at new CodeCell (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/codeCell.js:76:43)
    at InstantiationService._createInstance (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/instantiation/common/instantiationService.js:91:28)
    at InstantiationService.createInstance (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/instantiation/common/instantiationService.js:62:31)
    at CodeCellRenderer.renderElement (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.js:262:83)
    at PipelineRenderer.renderElement (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:869:26)
    at NotebookCellListView.insertItemInDOM (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:610:23)
    at NotebookCellListView._splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:404:26)
    at NotebookCellListView.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:322:29)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:1121:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:1090:23)
    at NotebookCellList.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:1121:32)
    at NotebookCellList.splice2 (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:391:19)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:309:22
    at Array.forEach (<anonymous>)
    at NotebookCellList._updateElementsInWebview (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:291:33)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:257:26
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:660:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:836:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:800:37)
    at compute (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModelImpl.js:163:44)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModelImpl.js:200:25
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:660:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:836:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:800:37)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:199:46
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:660:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:836:38)
    at NotebookEventEmitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:800:37)
    at NotebookEventEmitter.resume (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:931:31)
    at NotebookTextModel.applyEdits (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:407:40)
    at NotebookTextModel.reset (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/common/model/notebookTextModel.js:309:18)
    at NotebookFileWorkingCopyModel.update (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/notebook/common/notebookEditorModel.js:210:33)
    at async StoredFileWorkingCopy.doUpdateModel (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.js:372:17)
    at async StoredFileWorkingCopy.resolveFromContent (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.js:345:17)
    at async StoredFileWorkingCopy.resolveFromFile (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.js:295:17)
    at async StoredFileWorkingCopyManager.doResolve (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopyManager.js:339:17)
    at async StoredFileWorkingCopyManager.reload (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopyManager.js:259:13)
    at async Object.factory (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopyManager.js:144:25
```

**Comment by rebornix** [comment]
Merging this issue into https://github.com/microsoft/vscode/issues/173500
