### ISSUE TITLE
potential listener LEAK detected when scrolling through notebook

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#184447]
Type: <b>Bug</b>

1. Open `vscode-dev.github-issues`
2. Scroll up and down in the file a few times

**Bug**
In the dev tools see two potential leaks reported:

```
[g39] potential listener LEAK detected, having 246 listeners already. MOST frequent listener (40):
event.ts:828 Error
    at i.create (event.ts:841:25)
    at l.l [as onDidChangeExecution] (event.ts:965:25)
    at new iu (executionStatusBarItemController.ts:115:46)
    at d.j (instantiationService.ts:119:18)
    at d.createInstance (instantiationService.ts:85:18)
    at u.f (executionStatusBarItemController.ts:91:101)
    at u.h (executionStatusBarItemController.ts:72:48)
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at y.i (notebookVisibleCellObserver.ts:73:33)
    at y.h (notebookVisibleCellObserver.ts:50:8)
    at notebookVisibleCellObserver.ts:41:88
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at notebookEditorWidget.ts:1394:31
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at H (notebookViewModelImpl.ts:233:31)
    at notebookViewModelImpl.ts:277:6
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at notebookTextModel.ts:260:30
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at h.fire (event.ts:1031:24)
    at h.resume (event.ts:1195:12)
    at zl.applyEdits (notebookTextModel.ts:522:27)
    at zl.reset (notebookTextModel.ts:397:8)
    at u.update (notebookEditorModel.ts:273:23)
    at async Io.Z (storedFileWorkingCopy.ts:673:4)
    at async Io.W (storedFileWorkingCopy.ts:636:4)
    at async Io.U (storedFileWorkingCopy.ts:577:4)
    at async e.StoredFileWorkingCopyManager.hb (storedFileWorkingCopyManager.ts:553:4)
    at async e.StoredFileWorkingCopyManager.gb (storedFileWorkingCopyManager.ts:445:3)
    at async Object.factory (storedFileWorkingCopyManager.ts:300:6)
```

```
[55f] potential listener LEAK detected, having 508 listeners already. MOST frequent listener (21):
event.ts:828 Error
    at i.create (event.ts:841:25)
    at l.l (event.ts:965:25)
    at new Er (suggestWidget.ts:271:39)
    at d.j (instantiationService.ts:119:18)
    at d.createInstance (instantiationService.ts:85:18)
    at suggestController.ts:147:46
    at V.a (async.ts:1205:
```

VS Code version: Code - Insiders 1.79.0-insider (Universal) (aee52551e25d98391f9064996196cd83a9fc8669, 2023-06-06T15:04:36.424Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 7, 5|
|Memory (System)|32.00GB (1.51GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
Notebook is a good place for catching memory leaks.

**Comment by Abkdtrr** [comment]
> Type: Bug
> 
> 1. Open `vscode-dev.github-issues`
> 2. Scroll up and down in the file a few times
> 
> **Bug** In the dev tools see two potential leaks reported:
> 
> ```
> [g39] potential listener LEAK detected, having 246 listeners already. MOST frequent listener (40):
> event.ts:828 Error
>     at i.create (event.ts:841:25)
>     at l.l [as onDidChangeExecution] (event.ts:965:25)
>     at new iu (executionStatusBarItemController.ts:115:46)
>     at d.j (instantiationService.ts:119:18)
>     at d.createInstance (instantiationService.ts:85:18)
>     at u.f (executionStatusBarItemController.ts:91:101)
>     at u.h (executionStatusBarItemController.ts:72:48)
>     at g.invoke (event.ts:862:17)
>     at r.deliver (event.ts:1075:22)
>     at s.fire (event.ts:1031:24)
>     at y.i (notebookVisibleCellObserver.ts:73:33)
>     at y.h (notebookVisibleCellObserver.ts:50:8)
>     at notebookVisibleCellObserver.ts:41:88
>     at g.invoke (event.ts:862:17)
>     at r.deliver (event.ts:1075:22)
>     at s.fire (event.ts:1031:24)
>     at notebookEditorWidget.ts:1394:31
>     at g.invoke (event.ts:862:17)
>     at r.deliver (event.ts:1075:22)
>     at s.fire (event.ts:1031:24)
>     at H (notebookViewModelImpl.ts:233:31)
>     at notebookViewModelImpl.ts:277:6
>     at g.invoke (event.ts:862:17)
>     at r.deliver (event.ts:1075:22)
>     at s.fire (event.ts:1031:24)
>     at notebookTextModel.ts:260:30
>     at g.invoke (event.ts:862:17)
>     at r.deliver (event.ts:1075:22)
>     at h.fire (event.ts:1031:24)
>     at h.resume (event.ts:1195:12)
>     at zl.applyEdits (notebookTextModel.ts:522:27)
>     at zl.reset (notebookTextModel.ts:397:8)
>     at u.update (notebookEditorModel.ts:273:23)
>     at async Io.Z (storedFileWorkingCopy.ts:673:4)
>     at async Io.W (storedFileWorkingCopy.ts:636:4)
>     at async Io.U (storedFileWorkingCopy.ts:577:4)
>     at async e.StoredFileWorkingCopyManager.hb (storedFileWorkingCopyManager.ts:553:4)
>     at async e.StoredFileWorkingCopyManager.gb (storedFileWorkingCopyManager.ts:445:3)
>     at async Object.factory (storedFileWorkingCopyManager.ts:300:6)
> ```
> 
>  ```
> [55f] potential listener LEAK detected, having 508 listeners already. MOST frequent listener (21):
> event.ts:828 Error
>     at i.create (event.ts:841:25)
>     at l.l (event.ts:965:25)
>     at new Er (suggestWidget.ts:271:39)
>     at d.j (instantiationService.ts:119:18)
>     at d.createInstance (instantiationService.ts:85:18)
>     at suggestController.ts:147:46
>     at V.a (async.ts:1205:
> ```
> 
> VS Code version: Code - Insiders 1.79.0-insider (Universal) ([aee5255](https://github.com/microsoft/vscode/commit/aee52551e25d98391f9064996196cd83a9fc8669), 2023-06-06T15:04:36.424Z) OS version: Darwin x64 22.5.0 Modes:
> 
> System Info
