### ISSUE TITLE
Terminal bug

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [microsoft/vscode#184709]
Type: <b>Bug</b>

Open terminal.
Resize it - make it highier.
Watch it does not re-render. 
Now it's completely unusable.
Error in console
```
Uncaught TypeError: Cannot read properties of undefined (reading 'fill')
    at E._resetBufferLine (InputHandler.ts:1156:10)
    at E.eraseInDisplay (InputHandler.ts:1194:16)
    at Array.<anonymous> (InputHandler.ts:231:68)
    at c.parse (EscapeSequenceParser.ts:680:38)
    at E.parse (InputHandler.ts:485:35)
    at n._action (CoreTerminal.ts:145:99)
    at n._innerWrite (WriteBuffer.ts:164:27)
    at WriteBuffer.ts:124:29
```

VS Code version: Code - Insiders 1.80.0-insider (db6bcdf309cc1565c502a54b73c33a63bdabfbd8, 2023-06-09T05:50:00.303Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 0c371d61-9c5f-4476-b10a-e0c314c08dd3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.6.0
EditorConfig|Edi|0.16.4
vscode-todo-plus|fab|4.19.1
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.66.0
vscode-random|jre|1.11.0
rainbow-csv|mec|3.7.0
dotenv|mik|1.0.1
remote-ssh|ms-|0.103.2023060715
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2023060509
test-adapter-converter|ms-|0.1.8
material-icon-theme|PKi|4.28.0
partial-diff|ryu|1.4.3
code-spell-checker|str|2.20.4
sort-lines|Tyr|1.10.1
intellicode-api-usage-examples|Vis|0.2.7
vim|vsc|1.25.2
pretty-ts-errors|yoa|0.4.1
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887
dh2dc718:30763024
pythonnosmt12:30757129
pythonidxpt:30763123
pythondjangots:30763122

```

</details>

**Comment by developer-ken** [comment]
I got the exactly same behavior on my two Windows laptop. This makes the terminal completely broken and not useable.
Same VSCode Insider verison and commit hash, OS: Windows_NT x64 10.0.19045. 

Oh while I type this, I tried to resize my terminal and use 'clear'. After resizing my terminal to make it higher and run 'clear', it freezed. The remote connection is still there, as I can still open different files. Just the terminal.

![image](https://github.com/microsoft/vscode/assets/59414439/bea7791e-2e00-424f-9c33-672a0c14bb8a)

Hope the information helpful for debugging.

**Comment by hazlema** [comment]
Can confirm, happens to me on the linux build of code insiders, using the latest build

You can fix it (sort of) by deleting the terminal and recreating

**Comment by villem** [comment]
Same thing in Mac. Saved terminal sessions are non responsive, need delete and recreate to get terminal sessions working.
Version: 1.80.0-insider (Universal)
Commit: 6cd5ac180a6362b45b415a624f62173caf7428a1
Date: 2023-06-09T18:30:28.759Z (1 day ago)
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.6.0

**Comment by talkingnews** [comment]
Hurrah - seems to be fixed in latest build:

Version: 1.80.0-insider (user setup)
Commit: ef6abe4cd1573689d070b8715e97019cfadaeb51
Date: 2023-06-12T05:21:26.842Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by meganrogge** [comment]
this has been fixed already

**Comment by hazlema** [comment]
Just grabbed the new insiders build, works for me now!
