### ISSUE TITLE
Refused to create a TrustedTypePolicy named 'diffEditorWidget2'

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#184755]
1. Try to open a diff editor in insiders.vscode.dev
2. :bug: see this in console

```
Refused to create a TrustedTypePolicy named 'diffEditorWidget2' because it violates the following Content Security Policy directive: "trusted-types amdLoader cellRendererEditorText defaultWorkerFactory diffEditorWidget diffReview domLineBreaksComputer dompurify editorGhostText editorViewLayer notebookRenderer stickyScrollViewLayer tokenizeToString".
y @ workbench.web.main.js:11
workbench.web.main.js:6  Uncaught Error: Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy "diffEditorWidget2" disallowed.

TypeError: Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy "diffEditorWidget2" disallowed.
    at y (workbench.web.main.js:11:1101)
    at workbench.web.main.js:611:16101
    at v._invokeFactory (vscode-internalbacklog:5:1491)
    at v.complete (vscode-internalbacklog:5:1706)
    at h._onModuleComplete (vscode-internalbacklog:6:1051)
    at h._resolve (vscode-internalbacklog:6:510)
    at h.defineModule (vscode-internalbacklog:5:5548)
    at m (vscode-internalbacklog:6:1770)
    at workbench.web.main.js:611:15869
    at workbench.web.main.js:2629:33571
    at workbench.web.main.js:8:12
```

**Comment by hediet** [comment]
@joao I thought I updated most html files. Where is the html file that defines the policies for vscode.dev?

**Comment by hediet** [comment]
Fixed by @jrieken, thanks!
