### ISSUE TITLE
Does the `require("fs")` in the VSCode extension code turn into `require("graceful-fs")` when using SSH remote?

### ISSUE THREAD

**Issue by sosukesuzuki** [microsoft/vscode#184887]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.79.0
- OS Version: WSL2?

Steps to Reproduce:

1. WSL2 remote ssh VSCode(1.79.0) uses [prettier-vscode](https://github.com/prettier/prettier-vscode) extension
2. `TypeError: Cannot read properties of undefined (reading 'uid')` happens (please see https://github.com/prettier/prettier-vscode/issues/3020 for more details)

error stack (original: https://github.com/prettier/prettier-vscode/issues/3019)

```
["ERROR" - 12:05:24 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 12:05:24 AM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/ziimakc/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:35221)
	at L (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:37052)
	at /home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36677
	at Function.e.exports [as sync] (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36723)
	at t.ModuleResolver.findPkg (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:3251)
	at t.default.format (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:13495)
	at async t.PrettierEditProvider.provideEdits (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:11367)
	at async U.provideDocumentFormattingEdits (/home/ziimakc/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:102:45790)
["ERROR" - 12:05:24 AM] Prettier could not be loaded. See previous logs for more information.
```

---

As a maintainer of the Prettier code formatter, I've been working on an issue that surfaced after updating to VSCode 1.79.0. Specifically, we've been receiving reports about prettier-vscode ceasing to function when used in VSCode over a remote SSH connection.

The problem was first mentioned in this issue: https://github.com/prettier/prettier-vscode/issues/3020

Upon further examination of the error stack posted in https://github.com/prettier/prettier-vscode/issues/3019, it seems that the original `require("fs")` function call is being replaced by `require("graceful-fs")` within the affected environment. This replacement is unexpected and is likely linked to the reported malfunctions.

I would like to know if the VSCode team has any ideas. Thank you.

**Comment by sosukesuzuki** [comment]
I don't know why this problem started in 1.79.0, but it seems that this commit in graceful-fs is not included in the version on which vscode remote depends

https://github.com/isaacs/node-graceful-fs/commit/e61a20a052b838f420b98195c232a824a6ac04ee

**Comment by sosukesuzuki** [comment]
@alexdima Hi, Is it possible to update the version of graceful-fs that VSCode depends on? Without it, prettier-vscode will remain broken. I also suspect that the VSCode Extension making the call to `fs.statSync(foo, { throwIfNoEntry: false })` will be broken as well.

**Comment by alexdima** [comment]
🤖 Thanks for the report and the graceful-fs pointer. This was addressed by updating the remote extension host dependency to graceful-fs 4.2.11 in commit 329cfd399977b30a36d79bb0031b37a2426db694 (https://github.com/microsoft/vscode/pull/186713), which shipped starting with 1.81.0. Current main still resolves the remote graceful-fs dependency to 4.2.11, so I believe this can be closed as completed.
