### ISSUE TITLE
Integration test failure on macOS 

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#185072]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=218532
Changes: https://github.com/Microsoft/vscode/compare/4f95907...4f95907

```
vscode API - workspace-watcher
MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: vscode.vscode-api-tests, path: watcherTest:/somePath/folder, recursive: true, session: 0.4398481045774034): EntryNotFound (FileSystemError): watcherTest:/somePath/folder
    ✔ createFileSystemWatcher
  260 passing (4m)
  16 pending
  1 failing
  1) vscode API - tasks
       Tasks
         CustomExecution
           sync task should flush all data on close:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/extensions/vscode-api-tests/out/singlefolder-tests/workspace.tasks.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

ENOPRO: No file system provider found for resource 'fake-fs:/1fe2f0a27cf14366': CodeExpectedError: ENOPRO: No file system provider found for resource 'fake-fs:/1fe2f0a27cf14366'
    at e.FileService.j (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:12371)
    at async e.FileService.exists (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:14796)
    at async js.tb (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2299:32349)
[main 2023-06-14T00:47:50.664Z] Extension host with pid 50455 exited with code: 0, signal: unknown.
##[error]Bash exited with code '1'.
Finishing: Run integration tests (Remote)
```

**Comment by meganrogge** [comment]
I'm confused because all of the tests are passing when I click on the link above. I think this was a fluke

**Comment by rzhao271** [comment]
Here's the raw log of the failed test run from Attempt #1, but it could be a flaky test that's been fixed since then:

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_apis/build/builds/218532/logs/980

**Comment by meganrogge** [comment]
thanks, i'm seeing this in that log, so seems maybe was a terminal issue that's since been fixed

` Exception occurred during xterm disposal {}`
