### ISSUE TITLE
[vscode.references-view] Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#185108]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.1
- OS Version: Ubuntu 23.04

### Screencast of the issue:

https://github.com/microsoft/vscode/assets/23744935/b7fb1f23-4c69-40c3-b085-91cbf01836a5

### Steps to Reproduce:

1. Open the Chrome Devtools project in VSCode (https://github.com/ChromeDevTools/devtools-frontend)
2. Clone the devtools frontend again inside the devtools-frontend folder (I'm not sure why, but I had a devtools-frontend folder inside the devtools-frontend folder)
3. Open `devtools-frontend/front_end/core/sdk/SDKModel.ts`
4. Right click, then click on "Find All References"
5. Wait a few seconds until the references for SDKModel show up
6. Open `devtools-frontend/devtools-frontend/front_end/core/sdk/ScreenCaptureModel.ts`
7. Inside the console, an error is shown: `[vscode.references-view]Cannot read properties of undefined (reading '0')`

```
ERR <main> TypeScript Server Error (5.1.3)
No Project.
Error: No Project.
    at Object.ThrowNoProject (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172511:11)
    at IpcIOSession.getProjects (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:181261:21)
    at IpcIOSession.getReferences (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:181325:27)
    at references (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179875:43)
    at /snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:69
    at IpcIOSession.executeWithRequestId (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182345:14)
    at IpcIOSession.executeCommand (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:29)
    at IpcIOSession.onMessage (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182395:51)
    at process.<anonymous> (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:183975:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/processError: <main> TypeScript Server Error (5.1.3)
No Project.
Error: No Project.
    at Object.ThrowNoProject (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:172511:11)
    at IpcIOSession.getProjects (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:181261:21)
    at IpcIOSession.getReferences (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:181325:27)
    at references (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179875:43)
    at /snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:69
    at IpcIOSession.executeWithRequestId (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182345:14)
    at IpcIOSession.executeCommand (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:29)
    at IpcIOSession.onMessage (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:182395:51)
    at process.<anonymous> (/snap/code/131/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:183975:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
	at n.create (/snap/code/131/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:2:782311)
	at h.w (/snap/code/131/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:2:777510)
	at h.u (/snap/code/131/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:2:776575)
	at ChildProcess.<anonymous> (/snap/code/131/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:2:776207)
	at ChildProcess.emit (node:events:513:28)
	at emit (node:internal/child_process:967:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
[vscode.references-view]Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
	at o.location (/snap/code/131/usr/share/code/resources/app/extensions/references-view/dist/extension.js:1:11043)
	at t.Navigation.e (/snap/code/131/usr/share/code/resources/app/extensions/references-view/dist/extension.js:1:6458)
	at /snap/code/131/usr/share/code/resources/app/extensions/references-view/dist/extension.js:1:6277
	at b.invoke (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at d.deliver (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at E.setSelection (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:62878)
	at d.$setSelection (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:59206)
	at s.N (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11717)
	at s.M (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11435)
	at s.H (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10516)
	at s.G (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9494)
	at /snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:8282
	at b.invoke (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at d.deliver (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at /snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:32461
	at b.invoke (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at d.deliver (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at MessagePortMain.<anonymous> (/snap/code/131/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30587)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

### Expected behaviour: 
Console output does not show a references view error

### Actual behaviour: 
Console output shows a reference view error `[vscode.references-view]Cannot read properties of undefined (reading '0')`

**Comment by jrieken** [comment]
This is actually a TS bug

**Comment by mjbvz** [comment]
@jrieken What's the bug?

@SimonSiefke Can you try putting together a minimal repo?

**Comment by SimonSiefke** [comment]
This seems to be fixed in version 1.80.1, I can only reproduce the issue in 1.79.1. Thanks!

**Comment by jrieken** [comment]
Right, we stopped on reveal/locate on selecting items. 

Sorry @mjbvz for the false blame, I only saw the top stack traces.

**Comment by jrieken** [comment]
@SimonSiefke thanks for following up on this
