### ISSUE TITLE
Error connecting to github codespaces

### ISSUE THREAD

**Issue by djmbritt** [microsoft/vscode#185123]
Type: <b>Bug</b>

Every time I try connecting to my codespaces with my Visual Studio code editor, it times out.
Not sure what the issue is. I've tried the following:
-  using VsCode-Insiders, VsCode Stable.
- switching to the pre-release version of the codespaces extension. 
- connecting from different networks.
- connecting with a fresh OS install and vscode install
- disabling all the extensions and only enabling the codespaces extension.

Nothing has worked, so far.
I am able to connect to my codespaces from within my browser, So I think there might be an issue with vscode somewhere. But no idea where.

Hope you can help me.

Here is a stack trace:

```
log.ts:441   ERR Extension 'github.copilot-nightly' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, terminalDataWriteEvent
product.json (WINS): inlineCompletionsAdditions
log.ts:421  INFO Invoking resolveAuthority(codespaces)...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][0ms] obtaining proxy...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][1ms] invoking...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][1001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][2001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][3001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][4001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][5001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][6001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][7032ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][8001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][9001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][10001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][11001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][12001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][13001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][14001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][15001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][16001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][17001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][18001ms] waiting...
extensionDescriptionRegistry.ts:358 The customer named _initialize has been holding on to the lock for 30s. This might be a problem.
(anonymous) @ extensionDescriptionRegistry.ts:358
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][19001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][20002ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][21001ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(codespaces,1)][22001ms] waiting...
log.ts:441   ERR [LocalProcess0][resolveAuthority(codespaces,1)][22774ms] returned an error Error: 
    at kr.<anonymous> (vscode-file://vscode-app/home/djmbritt/.vscode/extensions/github.codespaces-1.14.8/src/api/githubApiProvider.ts:79:19)
    at Generator.next (<anonymous>)
    at fulfilled (vscode-file://vscode-app/home/djmbritt/.vscode/extensions/github.codespaces-1.14.8/out/bundle/extension-node.js:329:81000)
log.ts:441   ERR resolveAuthority(codespaces) returned an error after 22774 ms CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Error received from starting extension host (kind: Remote)
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:431  WARN [ms-vscode.remote-server]: The viewsWelcome contribution in 'ms-vscode.remote-server' requires 'enabledApiProposals: ["contribViewsWelcome"]' in order to use the 'group' proposed property.
log.ts:441   ERR [fiazluthfi.bulma-snippets]: Unknown language in `contributes.bulma-snippets.language`. Provided value: vue
log.ts:441   ERR [fiazluthfi.bulma-snippets]: Unknown language in `contributes.bulma-snippets.language`. Provided value: vue-html
log.ts:441   ERR [sdras.vue-vscode-snippets]: Unknown language in `contributes.vue-vscode-snippets.language`. Provided value: vue
log.ts:441   ERR [sdras.vue-vscode-snippets]: Unknown language in `contributes.vue-vscode-snippets.language`. Provided value: vue-html
log.ts:441   ERR [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
log.ts:441   ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 4] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 5]  An error occurred in initial connection! It will be treated as a permanent error. Error:
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Cannot register remote filesystem provider. Error while fetching remote environment. CodeExpectedError
notificationsAlerts.ts:42 Failed to connect to the remote extension host server (Error: )
c @ notificationsAlerts.ts:42
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:431  WARN Ignoring the error while validating workspace folder vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao - ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao'
log.ts:441   ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao'
    at e.FileService.j (fileService.ts:140:18)
    at async e.FileService.W (fileService.ts:1110:20)
    at async fileService.ts:1095:24
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao/.git/config': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao/.git/config'
    at e.FileService.j (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:12371)
    at async e.FileService.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:14796)
    at async Promise.all (index 0)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao/pom.xml': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao/pom.xml'
    at e.FileService.j (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:12371)
    at async e.FileService.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:14796)
    at async Promise.all (index 0)
log.ts:441   ERR An unknown error occurred. Please consult the log for more details.: CodeExpectedError
    at e.NativeExtensionService.pb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:22361)
    at async e.NativeExtensionService.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:21627)
    at async e.NativeExtensionService.Mb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:12329)
    at async e.NativeExtensionService.hb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:19259)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao'
    at e.FileService.j (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:12371)
    at async e.FileService.n (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:13359)
    at async e.FileService.resolve (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:13120)
    at async e.WorkspacesFinderContribution.i (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1941:6368)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao/.vscode': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao/.vscode'
    at e.FileService.j (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:12371)
    at async e.FileService.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:14796)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2003:6681
    at async Promise.all (index 0)
    at async e.SnippetsService.v (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2003:6788)
log.ts:441   ERR An unknown error occurred. Please consult the log for more details.: CodeExpectedError
    at e.NativeExtensionService.pb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:22361)
    at async e.NativeExtensionService.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:21627)
    at async e.NativeExtensionService.Mb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:12329)
    at async e.NativeExtensionService.hb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:19259)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://codespaces%2Bdjmbritt-bookish-robot-rp9w55qrjjfjxx/workspaces/effect-dao'
    at e.FileService.j (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:12371)
    at async e.FileService.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:14796)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1844:2622
log.ts:441   ERR CodeExpectedError
    at e.NativeExtensionService.pb (abstractExtensionService.ts:620:9)
    at async e.NativeExtensionService.ob (abstractExtensionService.ts:581:19)
    at async e.NativeExtensionService.Mb (nativeExtensionService.ts:368:22)
    at async e.NativeExtensionService.hb (abstractExtensionService.ts:417:31)
log.ts:421  INFO [perf] Render performance baseline is 40ms
log.ts:441   ERR An unknown error occurred. Please consult the log for more details.: CodeExpectedError
    at e.NativeExtensionService.pb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:22361)
    at async e.NativeExtensionService.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:21627)
    at async e.NativeExtensionService.Mb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:12329)
    at async e.NativeExtensionService.hb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:19259)
```

VS Code version: Code - Insiders 1.80.0-insider (79c4092768e41b16fd823e80c874dbfafdc08f55, 2023-06-13T05:22:36.374Z)
OS version: Linux x64 6.2.6-76060206-generic
Modes: Restricted
Connection to 'Codespaces' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|38.93GB (24.49GB free)|
|Process Argv|--unity-launch --crash-reporter-id 968b016a-0127-4294-a187-6fb403fa6b44|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|

Connection to 'Codespaces' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showindicator:30766888
pythongtdpath:30726887
dh2dc718:30763024
pythonnosmt12:30757129
pythonidxpt:30763123
pythondjangots:30763122
pythonnoceb:30766855

```

</details>

**Comment by linuxgpt** [comment]
similar problem from ubuntu 22.04 
2023-06-15 02:26:38.474 [error] Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, terminalDataWriteEvent
product.json (WINS): inlineCompletionsAdditions
2023-06-15 02:26:40.457 [warning] [ms-vscode.remote-server]: The viewsWelcome contribution in 'ms-vscode.remote-server' requires 'enabledApiProposals: ["contribViewsWelcome"]' in order to use the 'group' proposed property.

**Comment by chrmarti** [comment]
@djmbritt Could you post your issue and log at https://github.com/orgs/community/discussions/categories/codespaces? (This is the VS Code issue tracker, the Codespaces experts are over there.) Thanks!

**Comment by djmbritt** [comment]
@chrmarti, Thank you, will do.
