### ISSUE TITLE
Settings search stopped working for me

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18557]
- VSCode Version: Code - Insiders 1.9.0-insider (2cdc2b3da8f0fd5322b48747241584cf9dd98f8f, 2017-01-13T07:03:18.620Z)
- OS Version: Linux x64 4.8.0-32-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|python|donjayamanne|0.5.5|
|gitlens|eamodio|1.4.1|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|Go|lukehoban|0.6.50|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.6.2|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.0.8|
|annotator|ryu1kn|0.10.1|

---

In console:

```
shell.ts:432t.toLowerCase is not a function: TypeError: t.toLowerCase is not a function
    at Object.a [as matchesContiguousSubString] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:9716)
    at f (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:90:3319)
    at t._findMatchesInSetting (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:90:3541)
    at t.doFilterSettings (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:90:2054)
    at t.filterSettings (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:90:8764)
    at t.filterPreferences (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:114:8733)
    at t.filterPreferences (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:114:1765)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:114:281
    at e.invoke (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26461)
    at e.fire (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:29773)
```

**Comment by sandy081** [comment]
I was not expecting null values in default settings and there was a new setting introduced yesterday with null value. Fixed the search to be null value aware.
