### ISSUE TITLE
Illegal argument

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#185521]
```javascript
Error: Illegal argument
at d in src/vs/base/common/errors.ts:191:10
at h in out/vs/workbench/workbench.desktop.main.js:641:21780
at _setupColorCommand in src/vs/editor/contrib/colorPicker/browser/color.ts:121:76
at fn in src/vs/platform/instantiation/common/instantiationService.ts:68:11
at e.CommandService.k in src/vs/workbench/services/commands/common/commandService.ts:95:46
at e.CommandService.executeCommand in src/vs/workbench/services/commands/common/commandService.ts:60:17
at e.MainThreadCommands.$executeCommand in src/vs/workbench/api/browser/mainThreadCommands.ts:91:31
at p.N in src/vs/workbench/services/extensions/common/rpcProtocol.ts:455:17
at p.M in src/vs/workbench/services/extensions/common/rpcProtocol.ts:440:32
at p.H in src/vs/workbench/services/extensions/common/rpcProtocol.ts:370:19
at p.G in src/vs/workbench/services/extensions/common/rpcProtocol.ts:296:10
at <anonymous> in src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42
at g.invoke in src/vs/base/common/event.ts:862:17
at r.deliver in src/vs/base/common/event.ts:1075:22
at s.fire in src/vs/base/common/event.ts:1031:24
at l.fire in src/vs/base/parts/ipc/common/ipc.net.ts:671:19
at ee.onmessage in src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts:583:40
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=695af097c7bd098fbf017ce3ac85e09bbc5dda06&bH=087d4e3a-2cbd-816c-60d9-4407ee28c196)

**Comment by aiday-mar** [comment]
Currently not able to reproduce. I know where the issue appears but I am not sure how the code gets there, which steps to take to reproduce. Will wait until an issue with clear steps to reproduce is opened.
