### ISSUE TITLE
Cannot build Linux package due to node-debug2

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18578]
Latest master

```
gulp vscode-linux-x64
...
[12:04:24] Starting 'vscode-linux-x64'...
error!
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (No such extension version: ms-vscode.node-debug2 @ 1.9.5)
    at DestroyableTransform.emit (events.js:163:17)
    at onwriteError (/home/daimms/dev/Microsoft/vscode/node_modules/gulp-flatmap/node_modules/readable-stream/lib/_str
eam_writable.js:250:10)
    at onwrite (/home/daimms/dev/Microsoft/vscode/node_modules/gulp-flatmap/node_modules/readable-stream/lib/_stream_w
ritable.js:268:5)
    at WritableState.onwrite (/home/daimms/dev/Microsoft/vscode/node_modules/gulp-flatmap/node_modules/readable-stream
/lib/_stream_writable.js:106:5)
    at afterTransform (/home/daimms/dev/Microsoft/vscode/node_modules/gulp-flatmap/node_modules/readable-stream/lib/_s
tream_transform.js:104:5)
    at TransformState.afterTransform (/home/daimms/dev/Microsoft/vscode/node_modules/gulp-flatmap/node_modules/readabl
e-stream/lib/_stream_transform.js:79:12)
    at Stream.<anonymous> (/home/daimms/dev/Microsoft/vscode/node_modules/gulp-flatmap/index.js:71:9)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at Timeout._onTimeout (/home/daimms/dev/Microsoft/vscode/build/lib/extensions.js:18:44)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by roblourens** [comment]
Should be straightened out now.
