### ISSUE TITLE
remote-ssh

### ISSUE THREAD

**Issue by xuzhou2016** [microsoft/vscode#186064]
Type: <b>Bug</b>

Hello:
    My host is windows 11 home edition, and vscode version is Version: 1.79.2.
When I install virtualbox7 for windows,  and start a virtual machine of ubuntu23.  By port forward, ( host port 22 -> virtual machin  port 22)  I can visit ubuntu23 using ssh.   But I cannot access ubuntu23 by vscode extension
-- Remote SSH,  please help me. 
Thanks

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'SSH' could not be established  Connecting was canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (18.48GB free)|
|Process Argv|--crash-reporter-id 8199e5a5-8d71-47d3-9d37-6000e41bcc5e|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  Connecting was canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
e440d664:30770001
pythonidxpt:30772539
pythondjangotscf:30772537
pythonnocebcf:30773527

```

</details>

**Comment by xuzhou2016** [comment]
By the way,  when using "remote ssh" extension, I can access remote Linux host machine(which is a real linux host of ubuntu22)

**Comment by BasilGuo** [comment]
+1
There is a similar problem with remote-ssh for me.

**Problem Description**: I COULD get into the remote Linux with remote-ssh but **FAILED to open a folder**. It would timeout when waiting to input the password. But I can input nothing even until it fails.

The VSCode information:

> Version: 1.79.2
> Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
> Date: 2023-06-14T08:57:04.379Z
> Electron: 22.5.7
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19044



The output when failed:
> [16:08:45.424] Log Level: 2
> [16:08:45.442] VS Code version: 1.79.2
> [16:08:45.442] Remote-SSH version: remote-ssh@0.102.0
> [16:08:45.442] win32 x64
> [16:08:45.449] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2255536572766572435031227d", attempt 1
> [16:08:45.449] "remote.SSH.useLocalServer": false
> [16:08:45.450] "remote.SSH.showLoginTerminal": true
> [16:08:45.450] "remote.SSH.remotePlatform": {"UServerCP1":"linux"} # I have removed something here that is not related to this remote machine.
> [16:08:45.451] "remote.SSH.path": undefined
> [16:08:45.451] "remote.SSH.configFile": undefined
> [16:08:45.451] "remote.SSH.useFlock": true
> [16:08:45.451] "remote.SSH.lockfilesInTmp": false
> [16:08:45.452] "remote.SSH.localServerDownload": auto
> [16:08:45.452] "remote.SSH.remoteServerListenOnSocket": false
> [16:08:45.452] "remote.SSH.showLoginTerminal": true
> [16:08:45.452] "remote.SSH.defaultExtensions": []
> [16:08:45.453] "remote.SSH.loglevel": 2
> [16:08:45.453] "remote.SSH.enableDynamicForwarding": true
> [16:08:45.453] "remote.SSH.enableRemoteCommand": false
> [16:08:45.453] "remote.SSH.serverPickPortsFromRange": {}
> [16:08:45.454] "remote.SSH.serverInstallPath": {}
> [16:08:45.459] SSH Resolver called for host: UServerCP1
> [16:08:45.459] Setting up SSH remote "UServerCP1"
> [16:08:45.464] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
> [16:08:45.472] Install and start server if needed
> [16:08:45.477] Checking ssh with "D:\DevOps\Languages\Python\Python310\Scripts\ssh.exe -V"
> [16:08:45.480] Got error from ssh: spawn D:\DevOps\Languages\Python\Python310\Scripts\ssh.exe ENOENT
> [16:08:45.480] Checking ssh with "D:\DevOps\Languages\Python\Python310\ssh.exe -V"
> [16:08:45.482] Got error from ssh: spawn D:\DevOps\Languages\Python\Python310\ssh.exe ENOENT
> [16:08:45.482] Checking ssh with "C:\Windows\system32\ssh.exe -V"
> [16:08:45.484] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
> [16:08:45.484] Checking ssh with "C:\Windows\ssh.exe -V"
> [16:08:45.485] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
> [16:08:45.486] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
> [16:08:45.487] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
> [16:08:45.488] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
> [16:08:45.490] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
> [16:08:45.490] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
> [16:08:45.568] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
> 
> [16:08:45.577] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 3125 "UServerCP1" bash
> [16:08:45.583] Terminal shell path: C:\Windows\System32\cmd.exe
> [16:09:47.585] Resolver error: Error: Connecting with SSH timed out
> 	at m.Timeout (c:\Users\basil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584271)
> 	at Timeout._onTimeout (c:\Users\basil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:680601)
> 	at listOnTimeout (node:internal/timers:559:17)
> 	at process.processTimers (node:internal/timers:502:7)
> [16:09:47.592] ------
> 
> 
> 
> 
> [16:09:48.376] > ]0;C:\Windows\System32\cmd.exe
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> [16:09:48.378] Got some output, clearing connection timeout
> [16:09:48.473] > sma@192.168.56.105's password: 


But it works well with remote-ssh in the following version. So I have to downgrade to the previous version which, however, cannot work with the Github Pull Requests and Issues extension.

> Version: 1.77.3
> Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
> Date: 2023-04-12T09:16:02.548Z
> Electron: 19.1.11
> Chromium: 102.0.5005.196
> Node.js: 16.14.2
> V8: 10.2.154.26-electron.0
> OS: Windows_NT x64 10.0.19044
> Sandboxed: Yes
