### ISSUE TITLE
TS Server fatal error:  UNC host 'wsl.localhost' access is not allowed

### ISSUE THREAD

**Issue by jozekjoubert** [microsoft/vscode#186478]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.3

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host 'wsl.localhost' access is not allowed
    at Object.watchFile (node:fs:2362:14)
    at fsWatchFileWorker (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8562:11)
    at c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8209:15
    at createSingleWatcherPerName (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7730:16)
    at pollingWatchFile (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8204:12)
    at watchFile2 (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8039:16)
    at watchMissingFileSystemEntry (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8297:14)
    at fsWatchHandlingExistenceOnHost (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8228:72)
    at c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8218:15
    at createSingleWatcherPerName (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7730:16)
    at fsWatch (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8213:12)
    at Object.watchFile2 [as watchFile] (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8064:16)
    at watchFile (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117633:67)
    at Object.watchFile (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117652:282)
    at c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176956:183
    at _ProjectService.forEachConfigFileLocation (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177006:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176949:10)
    at InferredProject2.addRoot (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:175209:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176747:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178370:12)
    at c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178600:64
    at flatMap (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2573:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178600:24)
    at updateOpen (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179780:29)
    at c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182353:69
    at IpcIOSession.executeWithRequestId (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182345:14)
    at IpcIOSession.executeCommand (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182353:29)
    at IpcIOSession.onMessage (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182395:51)
    at process.<anonymous> (c:\Users\Jozek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183975:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (0.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/jozek/projects/clear_access_website --remote=wsl+Ubuntu-22.04 --crash-reporter-id eadc08b2-5f92-427f-898d-803b47274bc7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|Memory (System)|7.61GB (3.69GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
vscode-docker|ms-|1.25.1
remote-wsl|ms-|0.79.5
cmake-tools|ms-|1.14.33
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
laravel-blade|one|1.34.0
cmake|twx|0.0.17
volar|Vue|1.8.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
dh2dc718:30770000
pythonidxpt:30772539
pythondjangotscf:30772537

```

</details>

**Comment by bpasero** [comment]
https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths
