### ISSUE TITLE
TS Server fatal error:  UNC host '192.168.9.100' access is not allowed

### ISSUE THREAD

**Issue by Rafael-fd** [microsoft/vscode#186552]
Nós escrevemos os dados necessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole.

**Comment by Rafael-fd** [comment]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.3

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host '192.168.9.100' access is not allowed
    at Object.watchFile (node:fs:2363:14)
    at fsWatchFileWorker (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8562:11)
    at c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8209:15
    at createSingleWatcherPerName (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7730:16)
    at pollingWatchFile (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8204:12)
    at watchFile2 (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8039:16)
    at watchMissingFileSystemEntry (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8297:14)
    at fsWatchHandlingExistenceOnHost (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8228:72)
    at c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8218:15
    at createSingleWatcherPerName (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7730:16)
    at fsWatch (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8213:12)
    at Object.watchFile2 [as watchFile] (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8064:16)
    at watchFile (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117633:67)
    at Object.watchFile (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117652:282)
    at c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176956:183
    at _ProjectService.forEachConfigFileLocation (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177006:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176949:10)
    at InferredProject2.addRoot (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:175209:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176747:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178370:12)
    at c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178600:64
    at flatMap (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2573:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178600:24)
    at updateOpen (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179780:29)
    at c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182353:69
    at IpcIOSession.executeWithRequestId (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182345:14)
    at IpcIOSession.executeCommand (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182353:29)
    at IpcIOSession.onMessage (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182395:51)
    at process.<anonymous> (c:\Users\rafa_\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183975:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.80.0-insider (4649b5333370139d161e7b5d4f78ca13741efa35, 2023-06-28T08:01:04.380Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (24.43GB free)|
|Process Argv|--crash-reporter-id 7121690e-9f81-48f7-a4ad-918dd2c65877|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
path-intellisense|chr|2.8.4
code-runner|for|0.12.0
vscode-test-explorer|hbe|2.21.1
vscode-language-pack-pt-BR|MS-|1.80.2023062809
atom-keybindings|ms-|3.3.0
test-adapter-converter|ms-|0.1.8
vscode-php-test-explorer|ren|1.0.2
LiveServer|rit|5.7.9
vscode-php-test-explorer-docker|sat|1.0.5
vscode-icons|vsc|12.4.0
php-intellisense|zob|1.1.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
gsofb:30778559
dh2dc718:30776458
pythonnosmt12:30773574
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
e537b577:30772214
asynctokenver:30776452
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by bpasero** [comment]
See https://aka.ms/vscode-windows-unc
