### ISSUE TITLE
Race condition when creating new untitled editor after saving one

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode#186736]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: Version: 1.80.0-insider (user setup)
Commit: da7f05a70eb760e4ce1fe230ae158ae214433341
Date: 2023-06-27T15:13:35.848Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Create an untitled text file with Ctrl+N
2. Type multiple lines and press Ctrl+S, a Windows file dialog appears
3. Type a new filename and press Enter
4. Immediately press Ctrl+N, error appears.
5. Press Ctrl+N, "Untitled-2" tab appears and is activated and works fine.

![image](https://github.com/microsoft/vscode/assets/1485998/3bac7721-146f-45f2-9128-871da31675b4)

**Comment by r3m0t** [comment]
Window logs

```
2023-06-30 13:51:12.279 [info] [perf] Render performance baseline is 63ms
2023-06-30 13:51:58.165 [error] Error: Unable to read file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e' (Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e')
    at e.$op.w (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16414)
    at e.$op.v (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16209)
    at async Vi.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2287:130310)
    at async ls.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2303:41721)
    at async lo.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1982:6120)
    at async kh.setInput (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:11156)
    at async e.$Kub.M (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:20301)
    at async e.$Kub.D (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:18969)
    at async e.$Kub.openEditor (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:17957)
    at async vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:12434
    at async handler (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2510:6981)
2023-06-30 13:52:03.481 [error] Error: Unable to read file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e' (Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e')
    at e.$op.w (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16414)
    at e.$op.v (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16209)
    at async Vi.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2287:130310)
    at async ls.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2303:41721)
    at async lo.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1982:6120)
    at async kh.setInput (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:11156)
    at async e.$Kub.M (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:20301)
    at async e.$Kub.D (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:18969)
    at async e.$Kub.openEditor (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:17957)
    at async vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:12434
    at async handler (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2510:6981)
2023-06-30 13:52:05.515 [error] Error: Unable to read file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e' (Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e')
    at e.$op.w (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16414)
    at e.$op.v (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16209)
    at async Vi.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2287:130310)
    at async ls.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2303:41721)
    at async lo.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1982:6120)
    at async kh.setInput (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:11156)
    at async e.$Kub.M (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:20301)
    at async e.$Kub.D (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:18969)
    at async e.$Kub.openEditor (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:17957)
    at async vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:12434
    at async handler (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2510:6981)
2023-06-30 13:53:48.705 [error] Error: Unable to read file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e' (Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/ther3/AppData/Roaming/Code - Insiders/Backups/8f93c3691b21436620349c79ec0c26cc/untitled/-7f9c1a2e')
    at e.$op.w (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16414)
    at e.$op.v (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:16209)
    at async Vi.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2287:130310)
    at async ls.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2303:41721)
    at async lo.resolve (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1982:6120)
    at async kh.setInput (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:11156)
    at async e.$Kub.M (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:20301)
    at async e.$Kub.D (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:18969)
    at async e.$Kub.openEditor (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:17957)
    at async vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:12434
    at async handler (vscode-file://vscode-app/c:/Users/ther3/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2510:6981)
```

**Comment by bpasero** [comment]
🤷 Windows being Windows and being slow I guess

**Comment by bpasero** [comment]
This issue uncovered some good race conditions that I think I was able to address via https://github.com/microsoft/vscode/commit/ce708a97cefe1571c8ae5f7ebd092095dc788df6 and https://github.com/microsoft/vscode/commit/480b4653ee4551d9a1e8c01421c8423f9edf5089
