### ISSUE TITLE
Github Authentication Problem

### ISSUE THREAD

**Issue by OcelotWalrus** [microsoft/vscode#186858]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0-1688136779 (VSCode Insiders on flathub)
- OS Version: Fedora 38

Steps to Reproduce:

1. Sign In using Github
2. Restart VSCode
3. No more signed in

I currently use VSCode Insider and I use Github authentication to sync settings and use GitHub Extensions. Everything works fine but every time I restart the application, it resets every thing and I have to sign in using GitHub in every extension all over again. it is very annoying since I use all these Github extensions every time I code. Also just so you know every thing worked fine some days ago.

So I have decided to try to create a new profile using the same settings as the older one. While creating the new profile, I got these three errors, I think it could help fixing my problem:
```
2023-07-02 16:59:46.142 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
2023-07-02 16:59:47.955 [error] Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at e.$I2b.decrypt (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:42:11603)
    at Object.call (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:25:4844)
    at R.s (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:23:5128)
    at R.q (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:23:4644)
    at o.value (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:23:4051)
    at v.w (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:18:1906)
    at v.x (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:18:1976)
    at v.fire (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:18:2192)
    at o.value (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:16:38645)
    at v.w (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:18:1906)
    at v.fire (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:18:2123)
    at o.value (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:16:38839)
    at v.w (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:18:1906)
    at v.fire (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:18:2123)
    at se (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:16:40982)
    at IpcMainImpl.f (/app/extra/vscode-insiders/resources/app/out/vs/code/electron-main/main.js:19:96301)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80979)
    at EventEmitter.emit (node:events:513:28)
2023-07-02 16:59:53.232 [info] [perf] Render performance baseline is 69ms
2023-07-02 17:08:38.861 [info] Settings Sync: Updated current session 5ff0faff57d08f38
2023-07-02 17:24:00.569 [info] Importing Profile (Default): No keybindings to apply...
2023-07-02 17:24:00.605 [info] Importing Profile (Default): No keybindings to apply...
2023-07-02 17:24:00.826 [info] Importing Profile (Default): No tasks to apply...
2023-07-02 17:24:00.836 [info] Importing Profile (Default): No tasks to apply...
2023-07-02 17:24:24.960 [info] Importing Profile (Default): No keybindings to apply...
2023-07-02 17:24:24.969 [info] Importing Profile (Default): No tasks to apply...
2023-07-02 17:25:04.172 [error] Cancelled: Error: Cancelled
    at r (/app/extra/vscode-insiders/resources/app/extensions/github-authentication/dist/extension.js:2:593362)
    at t.GitHubServer.login (/app/extra/vscode-insiders/resources/app/extensions/github-authentication/dist/extension.js:2:593831)
    at t.GitHubAuthenticationProvider.createSession (/app/extra/vscode-insiders/resources/app/extensions/github-authentication/dist/extension.js:2:590267)
2023-07-02 17:25:57.139 [info] Importing Profile (Default): No keybindings to apply...
2023-07-02 17:25:57.147 [info] Importing Profile (Default): No tasks to apply...
2023-07-02 17:25:59.588 [info] Importing Profile (Cromha): Ignoring global state key 'workbench.sideBar.position' because it is not a profile key.
2023-07-02 17:25:59.589 [info] Importing Profile (Cromha): Ignoring global state key 'workbench.activityBar.hidden' because it is not a profile key.
2023-07-02 17:25:59.589 [info] Importing Profile (Cromha): Ignoring global state key 'workbench.statusBar.hidden' because it is not a profile key.
2023-07-02 17:25:59.589 [info] Importing Profile (Cromha): Ignoring global state key 'remote.explorerType' because it is not a profile key.
2023-07-02 17:25:59.922 [info] Importing Profile (Cromha): Started installing extensions.
2023-07-02 17:27:35.551 [info] Importing Profile (Cromha): Finished installing extensions.
2023-07-02 17:27:36.783 [error] Extension 'github.vscode-pull-request-github' wants API proposal 'treeItemCheckbox' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-07-02 17:27:36.797 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
```

Thanks in advance.

**Comment by TylerLeonhardt** [comment]
Regardless of profile, you use the same auth state so let's try and figure out why your state isn't saving.

What desktop environment do you use?

Can you take a look at these docs for vscode insiders and give us the logs if that doesn't help:

https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#troubleshooting-keychain-issues

**Comment by OcelotWalrus** [comment]
First, thanks for responding to me that fast,

I use Fedora Workstation 38, 64-bit, with GNOME desktop and Wayland Windowing System. I also have the 6.3.10-200.fc38.x86_64 version of the Linux Kernel if that can help.

I runned VSCode Insiders using the `--verbose` and `--vmodule="*/components/os_crypt/*=1"` parameter but i still have the same issue. Here is the logs i got:
[code-insiders-log.txt](https://github.com/microsoft/vscode/files/11935992/code-insiders-log.txt)
I hope it will help.

**Comment by TylerLeonhardt** [comment]
So, interesting line in your log to me was:
```
[23:0703/124157.387414:VERBOSE1:key_storage_libsecret.cc(82)] OSCrypt generated a new password.
```
I know you've probably done this a million times now, but can you kill VS Code, and start it up again with those parameters and send me the logs once more?

What would be odd to me is if:
```
[23:0703/124157.387414:VERBOSE1:key_storage_libsecret.cc(82)] OSCrypt generated a new password.
```
is shown again. If that line continues to show up, that would explain:
```
Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
```
 because it's using a new key to decrypt the strings every time... which obviously won't work.

**Comment by OcelotWalrus** [comment]
Okay here is the logs after killing it and running again with the parameters you gave me:

[vscode-logs.txt](https://github.com/microsoft/vscode/files/11945013/vscode-logs.txt)

I looked inside and `OSCrypt generated a new password` appears again at line 665.

**Comment by OcelotWalrus** [comment]
Okay thanks!

**Comment by deepak1556** [comment]
Can you try the following steps,

1) Launch VSCode and login into GIthub
2) In system terminal run the following command, `sudo dnf install libsecret-tools`
3) Now in the same terminal run `secret-tool lookup application Code`, does this print a base64 encoded string ?
4) If yes for 3) then quit VSCode
5) Perform step 3) again and check the result is same as before
6) If no for step 3) then there is a bug in the runtime.

**Comment by OcelotWalrus** [comment]
Actually I have no more Authentication problem. I just updated my Visual Studio Code package and the problem was gone. Still thank you for responding to me.
