### ISSUE TITLE
Can't update extension

### ISSUE THREAD

**Issue by dorshinar** [microsoft/vscode#186984]
Type: <b>Bug</b>

For about a week now I have extensions installed that I am unable to update. They show the "install" button but throw an error when I click that. 

![image](https://github.com/microsoft/vscode/assets/17943918/9ba791f6-fe7c-482e-b711-65adce42c6f8)
![image](https://github.com/microsoft/vscode/assets/17943918/47bc97b3-5ada-410f-99ed-d16e019ae554)

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 8, 7|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|. --crash-reporter-id 1ebba2dd-ad1c-4bde-bf4b-3e47641a929c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
atlascode|atl|3.0.3
vscode-tailwindcss|bra|0.9.11
turbo-console-log|Cha|2.9.3
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.2
gitlens|eam|14.0.1
prettier-vscode|esb|9.16.0
figma-vscode-extension|fig|0.2.1
svg|joc|1.5.2
vscode-peacock|joh|4.2.2
playwright|ms-|1.0.13
color-highlight|nau|2.5.0
angular-console|nrw|18.2.1
vscode-jest|Ort|5.2.3
vscode-yaml|red|1.13.0
vscode-fileutils|sle|3.10.1
code-spell-checker|str|2.20.5
tabnine-vscode|Tab|3.6.60
vscode-icons|vsc|12.4.0
change-case|wma|1.0.0
pretty-ts-errors|yoa|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnocebcf:30776496

```

</details>

**Comment by mozhuanzuojing** [comment]
这个常见，最大可能是原插件的目录无法删除导致的。

**Comment by sandy081** [comment]
Can you please share the following log: `F1 > Open View... > Shared` ?

**Comment by dorshinar** [comment]
![image](https://github.com/microsoft/vscode/assets/17943918/8a2de63d-7962-475c-a38f-56599bccaddc)

<details><summary>Shared output</summary>
<p>
2023-07-05 12:45:29.729 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 12:45:29.732 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 12:45:32.377 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 12:45:32.381 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 12:45:35.081 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 12:45:35.081 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 12:45:38.357 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 12:45:38.357 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at E.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4949)
    at E.q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:4352)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:23:3752
    at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:145)
    at u.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:2121)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:19:1729)
    at MessagePortMain.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:17:23922)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-05 13:03:20.038 [info] Getting Manifest... chakrounanas.turbo-console-log
2023-07-05 13:03:20.040 [info] Getting Manifest... dbaeumer.vscode-eslint
2023-07-05 13:03:20.040 [info] Getting Manifest... esbenp.prettier-vscode
2023-07-05 13:03:20.041 [info] Getting Manifest... github.vscode-pull-request-github
2023-07-05 13:03:20.041 [info] Getting Manifest... jock.svg
2023-07-05 13:03:20.041 [info] Getting Manifest... ms-python.vscode-pylance
2023-07-05 13:03:20.041 [info] Getting Manifest... ms-toolsai.jupyter
2023-07-05 13:03:20.042 [info] Getting Manifest... nrwl.angular-console
2023-07-05 13:03:20.042 [info] Getting Manifest... prisma.prisma
2023-07-05 13:03:20.043 [info] Getting Manifest... rust-lang.rust-analyzer
2023-07-05 13:03:20.043 [info] Getting Manifest... sleistner.vscode-fileutils
2023-07-05 13:03:20.043 [info] Getting Manifest... zixuanchen.vitest-explorer
2023-07-05 13:03:20.048 [error] Failed to install extension. chakrounanas.turbo-console-log
2023-07-05 13:03:20.049 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.049 [error] Failed to install extension. dbaeumer.vscode-eslint
2023-07-05 13:03:20.049 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.049 [error] Failed to install extension. esbenp.prettier-vscode
2023-07-05 13:03:20.049 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.049 [error] Failed to install extension. github.vscode-pull-request-github
2023-07-05 13:03:20.050 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.050 [error] Failed to install extension. jock.svg
2023-07-05 13:03:20.050 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.050 [error] Failed to install extension. ms-python.vscode-pylance
2023-07-05 13:03:20.050 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.050 [error] Failed to install extension. ms-toolsai.jupyter
2023-07-05 13:03:20.050 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.050 [error] Failed to install extension. nrwl.angular-console
2023-07-05 13:03:20.050 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.050 [error] Failed to install extension. prisma.prisma
2023-07-05 13:03:20.050 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.050 [error] Failed to install extension. rust-lang.rust-analyzer
2023-07-05 13:03:20.051 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.051 [error] Failed to install extension. sleistner.vscode-fileutils
2023-07-05 13:03:20.051 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:03:20.051 [error] Failed to install extension. zixuanchen.vitest-explorer
2023-07-05 13:03:20.051 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:09:09.380 [info] Getting Manifest... esbenp.prettier-vscode
2023-07-05 13:09:09.385 [error] Failed to install extension. esbenp.prettier-vscode
2023-07-05 13:09:09.385 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:09:10.647 [info] Getting Manifest... esbenp.prettier-vscode
2023-07-05 13:09:10.650 [error] Failed to install extension. esbenp.prettier-vscode
2023-07-05 13:09:10.650 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.287 [info] Getting Manifest... chakrounanas.turbo-console-log
2023-07-05 13:13:14.290 [info] Getting Manifest... esbenp.prettier-vscode
2023-07-05 13:13:14.291 [info] Getting Manifest... github.vscode-pull-request-github
2023-07-05 13:13:14.291 [info] Getting Manifest... jock.svg
2023-07-05 13:13:14.292 [info] Getting Manifest... ms-python.vscode-pylance
2023-07-05 13:13:14.293 [info] Getting Manifest... nrwl.angular-console
2023-07-05 13:13:14.294 [info] Getting Manifest... prisma.prisma
2023-07-05 13:13:14.296 [info] Getting Manifest... rust-lang.rust-analyzer
2023-07-05 13:13:14.296 [info] Getting Manifest... sleistner.vscode-fileutils
2023-07-05 13:13:14.297 [info] Getting Manifest... tabnine.tabnine-vscode
2023-07-05 13:13:14.298 [info] Getting Manifest... zixuanchen.vitest-explorer
2023-07-05 13:13:14.306 [error] Failed to install extension. chakrounanas.turbo-console-log
2023-07-05 13:13:14.306 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.307 [error] Failed to install extension. esbenp.prettier-vscode
2023-07-05 13:13:14.308 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.308 [error] Failed to install extension. github.vscode-pull-request-github
2023-07-05 13:13:14.308 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.308 [error] Failed to install extension. jock.svg
2023-07-05 13:13:14.308 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.308 [error] Failed to install extension. ms-python.vscode-pylance
2023-07-05 13:13:14.308 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.308 [error] Failed to install extension. nrwl.angular-console
2023-07-05 13:13:14.309 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.309 [error] Failed to install extension. prisma.prisma
2023-07-05 13:13:14.309 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.309 [error] Failed to install extension. rust-lang.rust-analyzer
2023-07-05 13:13:14.309 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.310 [error] Failed to install extension. sleistner.vscode-fileutils
2023-07-05 13:13:14.310 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.310 [error] Failed to install extension. tabnine.tabnine-vscode
2023-07-05 13:13:14.310 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:14.310 [error] Failed to install extension. zixuanchen.vitest-explorer
2023-07-05 13:13:14.310 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:18.100 [info] Getting Manifest... sleistner.vscode-fileutils
2023-07-05 13:13:18.101 [error] Failed to install extension. sleistner.vscode-fileutils
2023-07-05 13:13:18.101 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:20.996 [info] Getting Manifest... nrwl.angular-console
2023-07-05 13:13:21.002 [error] Failed to install extension. nrwl.angular-console
2023-07-05 13:13:21.002 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-07-05 13:13:23.576 [info] Getting Manifest... chakrounanas.turbo-console-log
2023-07-05 13:13:23.583 [error] Failed to install extension. chakrounanas.turbo-console-log
2023-07-05 13:13:23.583 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
</p>
</details>

**Comment by dorshinar** [comment]
I'm not sure what happened but it seems to have been fixed over the weekend, as I was able to update extensions now. 
I'll close this issue.
