### ISSUE TITLE
Conpty causes pty host on remote to restart immediately

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#187084]
Repro:

1. Open OSS
2. Ensure conpty is enabled
3. Open new test resolver window
4. Close other windows
5. Open terminal
6. Close test resolver window
7. Open OSS, 🐛 pwsh will launch, then flicker and the prompt will be gone. Looking at the logs reveals the pty host almost immediately restarts because it exits, see `Pty Host exiting, code=1` below

Some extra logs showing traces below:

```
2023-07-05 13:00:56.076 [trace] node-pty.IPty#spawn C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe [] ...
2023-07-05 13:00:56.125 [trace] [RPC Event] PtyService#_onProcessReady.fire({"id":2,"event":{"pid":10176,"cwd":"C:\\Users\\Daniel","windowsPty":{"backend":"conpty","buildNumber":22621}}})
2023-07-05 13:00:56.126 [trace] [RPC Response] PtyService#start undefined
2023-07-05 13:00:56.142 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":2,"property":{"type":"title","value":"pwsh.exe"}})
2023-07-05 13:00:56.142 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":2,"property":{"type":"shellType"}})
2023-07-05 13:00:56.268 [trace] node-pty.IPty#onData [?25l[2J[m[HPowerShell 7.3.5
]0;C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.5.0_x64__8wekyb3d8bbwe\pwsh.exe[?25h
2023-07-05 13:00:56.286 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":2,"event":"\u001b[?25l\u001b[2J\u001b[m\u001b[HPowerShell 7.3.5\r\n\u001b]0;C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.3.5.0_x64__8wekyb3d8bbwe\\pwsh.exe\u0007\u001b[?25h"})
2023-07-05 13:00:56.333 [trace] node-pty.IPty#kill
2023-07-05 13:00:56.340 [trace] [RPC Event] PtyService#_onProcessExit.fire({"id":1,"event":0})
2023-07-05 13:00:56.414 [trace] Pty Host exiting, code=1
2023-07-05 13:00:56.414 [trace] TerminalProcess#shutdown 
    at TerminalProcess.shutdown (c:\Github\microsoft\vscode\out\vs\platform\terminal\node\terminalProcess.js:375:64)
    at PersistentTerminalProcess.shutdown (c:\Github\microsoft\vscode\out\vs\platform\terminal\node\ptyService.js:762:42)
    at c:\Github\microsoft\vscode\out\vs\platform\terminal\node\ptyService.js:89:25
    at c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:144:17
    at Object.dispose (c:\Github\microsoft\vscode\out\vs\base\common\functional.js:18:25)
    at dispose (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:96:27)
    at DisposableStore.clear (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:191:17)
    at DisposableStore.dispose (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:175:18)
    at PtyService.dispose (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:239:25)
    at process.<anonymous> (c:\Github\microsoft\vscode\out\vs\platform\terminal\node\ptyHostMain.js:68:24)
    at Object.onceWrapper (node:events:628:26)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:174:19)
2023-07-05 13:00:56.414 [trace] TerminalProcess#_queueProcessExit 
    at TerminalProcess._queueProcessExit (c:\Github\microsoft\vscode\out\vs\platform\terminal\node\terminalProcess.js:314:73)
    at TerminalProcess.shutdown (c:\Github\microsoft\vscode\out\vs\platform\terminal\node\terminalProcess.js:384:26)
    at PersistentTerminalProcess.shutdown (c:\Github\microsoft\vscode\out\vs\platform\terminal\node\ptyService.js:762:42)
    at c:\Github\microsoft\vscode\out\vs\platform\terminal\node\ptyService.js:89:25
    at c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:144:17
    at Object.dispose (c:\Github\microsoft\vscode\out\vs\base\common\functional.js:18:25)
    at dispose (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:96:27)
    at DisposableStore.clear (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:191:17)
    at DisposableStore.dispose (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:175:18)
    at PtyService.dispose (c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js:239:25)
    at process.<anonymous> (c:\Github\microsoft\vscode\out\vs\platform\terminal\node\ptyHostMain.js:68:24)
    at Object.onceWrapper (node:events:628:26)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:174:19)
```

Prompt briefly appears and then goes away:

![image](https://github.com/microsoft/vscode/assets/2193314/6610d38e-5faf-4934-9af3-6f3e6de0afe3)

**Comment by Tyriar** [comment]
Disabling seamless relaunch fixes the problem
