### ISSUE TITLE
ListView fails bad with large data

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18713]
* have a completion provider as shown below
* open a `foo.brutalo` file, trigger intellisense
* 💥 the ListView fails with a RangeError

```ts
  vscode.languages.registerCompletionItemProvider({ pattern: '**/*.brutalo' }, {
        provideCompletionItems(doc, pos) {
            // let count = 6313;
            let count = 20000;
            let result: vscode.CompletionItem[] = [];
            while (count-- >= 0) {
                result.push(new vscode.CompletionItem(String.fromCharCode(97 + (count % 26)) + Math.random().toString(16)));
            }
            return result;
        }
    });
```

```
shell.js:235 Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at ListView.splice (file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listView.js:73:41)
    at file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:240:42
    at EventBufferer.bufferEvents (file:////Users/jrieken/Code/vscode/out/vs/base/common/event.js:333:13)
    at List.splice (file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:237:32)
    at SuggestWidget.showSuggestions (file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/suggest/browser/suggestWidget.js:449:41)
    at file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/suggest/browser/suggestController.js:69:92
    at CallbackList.invoke (file:////Users/jrieken/Code/vscode/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (file:////Users/jrieken/Code/vscode/out/vs/base/common/event.js:88:40)
    at SuggestModel.onNewContext (file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/suggest/common/suggestModel.js:293:36)
    at file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/suggest/common/suggestModel.js:244:23
```

**Comment by joaomoreno** [comment]
Wow.

**Comment by jrieken** [comment]
I suspect that you running into max args issues. For instance something like `array.push(...anotherArray)` fails with a RangeError when `anotherArray` is too large. Every VM has a built-in limit of how many argument a function call accepts and with array destructuring you often effectively write `fn(a1, a2, a3, ... , a64588, a64599)`...

**Comment by joaomoreno** [comment]
That makes total sense!
