### ISSUE TITLE
Terminal integration test faliure

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#187139]
Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=221802&view=logs&j=b75cd74d-dc71-5264-f9b3-8ccaa79d0ed3&t=7316213f-42cf-52a6-c019-269c027a9900

```
 1) vscode API - terminal
       "before all" hook in "vscode API - terminal":
     Error: Unable to write to User Settings because of an internal error.
      at e.$sYb.y (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:45486)
      at e.$sYb.p (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:43253)
      at async e.$sYb.o (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:43101)
      at async e.$sYb.n (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:42761)
      at async Object.factory (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:42522)

ENOPRO: No file system provider found for resource 'fake-fs:/bd72b77d8f6b1d31': CodeExpectedError: ENOPRO: No file system provider found for resource 'fake-fs:/bd72b77d8f6b1d31'
    at e.$pp.j (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$pp.exists (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:627:13608)
    at async tr.sb (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2301:26340)

```

**Comment by Tyriar** [comment]
There was a recent change to writing files from the extension host, so it's likely related to that.

**Comment by bpasero** [comment]
Yup, that change ("atomic writes") was reverted again it seems.
