### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Not an authority that can be resolved!) on 1.80.0 but not on earlier versions

### ISSUE THREAD

**Issue by rwdzero** [microsoft/vscode#187202]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z (2 days ago)
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

Steps to Reproduce:

1. When I try to connect to a machine over ssh using a vs code remote url 

eg: `vscode://vscode-remote/ssh-remote+devzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects?windowId=_blank`

I get the following error message 

```
Failed to connect to the remote extension host server (Error: Not an authority that can be resolved!)
 ```

I can work around by either:

- downgrading vscode to May 2023 (version 1.79)

- manually adding entry to my ~/.ssh/config

working ssh config 

```
Host ybsvmibl.devinfra.dev0.run
	HostName ybsvmibl.devinfra.dev0.run
	User devzero
```
vscode dev console logs 

```
vscode-remote-resource?path=%2Fhome%2Fdevzero%2F.vscode-server%2Fextensions%2Feamodio.gitlens-14.0.1%2Fimages%2Fgitlens-icon.png:1          Failed to load resource: net::ERR_INVALID_URL
log.ts:421  INFO Invoking resolveAuthority(ssh-remote)...
log.ts:421  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
log.ts:421  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
log.ts:441   ERR [LocalProcess0][resolveAuthority(ssh-remote,1)][6ms] returned an error Error: Not an authority that can be resolved!
	at i.ob (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:16793)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:17528
	at Array.map (<anonymous>)
	at i.$resolveAuthority (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:17435)
	at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11199)
	at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10965)
	at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10046)
	at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9122)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:7952)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30341)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
log.ts:441   ERR resolveAuthority(ssh-remote) returned an error after 6 ms CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Error received from starting extension host (kind: Remote)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 4] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 5]  An error occurred in initial connection! It will be treated as a permanent error. Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Cannot register remote filesystem provider. Error while fetching remote environment. Not an authority that can be resolved!
notificationsAlerts.ts:42 Failed to connect to the remote extension host server (Error: Not an authority that can be resolved!)
c @ notificationsAlerts.ts:42
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:431  WARN Ignoring the error while validating workspace folder vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects - ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects'
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.vscode': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.vscode'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:13607)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1993:6258
    at async Promise.all (index 0)
    at async e.$ijb.v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1993:6365)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects'
    at e.$op.j (fileService.ts:140:18)
    at async e.$op.W (fileService.ts:1110:20)
    at async fileService.ts:1095:24
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.git/config': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.git/config'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:13607)
    at async Promise.all (index 0)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/pom.xml': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/pom.xml'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:13607)
    at async Promise.all (index 0)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:12190)
    at async e.$op.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:12018)
    at async e.$IXb.i (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:5269)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
 
```

**Comment by rwdzero** [comment]
possibly related? https://github.com/microsoft/vscode/pull/185169

**Comment by rwdzero** [comment]
I think i have a fix 

```
const remoteAuthorityChain = "ssh-remote+devzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects?windowId=_blank"
const chain = remoteAuthorityChain.split(/@|%40/g).filter(
  authorityChainCandidate => authorityChainCandidate.indexOf('+') != -1
);

console.log(chain)
```

**Comment by connor4312** [comment]
@roblourens what do you think of the approach here? This should only be a code path one could hit by manually opening an ssh url.

**Comment by roblourens** [comment]
What changed here @connor4312? Are you using the `@` for something?

Also @rwdzero you don't need the username when it's already in your ssh config. And when we create this sort of URI internally, we base64-encode the user+host rather than put special characters into the URI. Actually I'm sort of surprised that we parsed it correctly before.

**Comment by rwdzero** [comment]
Hey @roblourens thanks for the reply, I tried using vscode://vscode-remote/ssh-remote+ZGV2emVyb0Bnbmh2YXdxYi5kZXZpbmZyYS5kZXYwLnJ1bg/home/devzero/projects?windowId=_blank as a link and was not able to establish a connection but vscode://vscode-remote/ssh-remote+devzero@gnhvawqb.devinfra.dev0.run/home/devzero/projects?windowId=_blank  formatted link connected successfully, could you comment on how to format this correctly?

Thanks for the suggestion for including the user in the ssh config but unfortunately our use case depends on us not being able to modify this file. We based on our implementation on this issue https://github.com/microsoft/vscode-remote-release/issues/656#issuecomment-606131295

**Comment by connor4312** [comment]
Yea, the `@` sign is now used for nesting. So for example someone can do `wsl+Ubuntu@tunnel+my-desktop-pc` to connect to WSL via a tunnel. I checked all our remote extensions that they didn't use `@` in the remote authorities, but didn't realize that SSH users could create such a remote authority themselves to get parsed by remote-ssh.

**Comment by roblourens** [comment]
I see, and the fix is to not try to split it on `@` if it fails to resolve that second part, makes sense to me.

Ok, yeah @rwdzero the base64-encoded version is not a format that is really exposed to the user anywhere. If it helps in the short-term, the logic is like `Buffer.from(JSON.stringify({ hostName: 'myhost', user: 'username' }), 'utf8').toString('hex');`

**Comment by Viknet** [comment]
> Ok, yeah @rwdzero the base64-encoded version is not a format that is really exposed to the user anywhere. If it helps in the short-term, the logic is like `Buffer.from(JSON.stringify({ hostName: 'myhost', user: 'username' }), 'utf8').toString('hex');`

A little nitpick - this is not base64-encoding, but simple hex-encoding. And struct also includes `port` field.
