### ISSUE TITLE
Failing integration test: No expanding when html is excluded in the settings in completion list

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#187245]
Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=221996&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=276f2611-d3ce-56d9-1883-dac9028293d2

```
1) Tests for Expand Abbreviations (HTML)
       No expanding when html is excluded in the settings in completion list:
     Error: Unable to write to User Settings because of an internal error.
      at e.$tYb.y (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:45486)
      at e.$tYb.p (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:43253)
      at async e.$tYb.o (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:43101)
      at async e.$tYb.n (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:42761)
      at async Object.factory (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2271:42522)

 2) Tests for jsx, xml and xsl
       Expand abbreviation with no self closing tags for html:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'img'
- '<img src="" alt="">'
Exec: 
At D:\a\_work\1\s\build\azure-pipelines\win32\exec.ps1:22 char:3
      + expected - actual

      -img
      +<img src="" alt="">
      
      at D:\a\_work\1\s\extensions\emmet\src\test\abbreviationAction.test.ts:475:11


```

**Comment by alexr00** [comment]
Hit this again with https://dev.azure.com/monacotools/Monaco/_build/results?buildId=222059&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=276f2611-d3ce-56d9-1883-dac9028293d2

**Comment by joaomoreno** [comment]
Again: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=222202&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=17905631-e510-504a-3bfd-98d08e042b7e

**Comment by joaomoreno** [comment]
@sandy081 Is trying to get more details when this happens: https://github.com/microsoft/vscode/pull/187479

**Comment by joyceerhl** [comment]
Also saw this https://dev.azure.com/vscode/VSCode/_build/results?buildId=98071&view=logs&j=e5ed5edc-5ec6-5bfb-d1cb-ed7e8a6cb5eb&t=47853d69-0171-5aff-95e0-ddf2bd2b235d&l=867

```
  1) Tests for Emmet actions on html tags
       split/join tag in jsx with xhtml self closing tag:
     Error: Error while writing to User Settings. Unable to write file 'vscode-userdata:/c:/Users/CLOUDT~1/AppData/Local/Temp/vscodeuserfolder-13291-24.84/User/settings.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, rename 'c:\Users\CLOUDT~1\AppData\Local\Temp\vscodeuserfolder-13291-24.84\User\settings.json.vsctmp' -> 'c:\Users\CLOUDT~1\AppData\Local\Temp\vscodeuserfolder-13291-24.84\User\settings.json')
      at ConfigurationEditing.save (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/services/configuration/common/configurationEditing.js:157:23)
      at async ConfigurationEditing.updateConfiguration (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/services/configuration/common/configurationEditing.js:145:17)
      at async ConfigurationEditing.doWriteConfiguration (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/services/configuration/common/configurationEditing.js:124:17)
      at async Object.factory (vscode-file://vscode-app/d:/a/_work/1/s/out/vs/workbench/services/configuration/common/configurationEditing.js:109:21)
```

**Comment by sandy081** [comment]
This is because of atomic writing and in windows renaming is failing sometimes and I think this is because some other processes (defender 🤔  ) might be holding the file that has to be renamed. 

I have seen similar issues in extensions when I implemented atomic installation of extensions long time back, ie. extracting the zip to a temp file in the same folder and renaming it. I have to retry renaming multiple times to avoid this. 

I am not sure if this is the right solution for FS atomic write. So, I would wait for @bpasero, until then I will revert my atomic write changes.

**Comment by sandy081** [comment]
Check this issue - https://github.com/nodejs/node/issues/29481 

This is common in windows and it seems the workaround is to retry.

**Comment by alexr00** [comment]
Seems like they can probably be restored.
