### ISSUE TITLE
terminal reconnection isn't working

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#187282]
1. create some terminals and type in them
2. reload the window or restart VS Code
3. 🐛 they don't persist

Started happening in OSS on Wednesday July 5th

**Comment by meganrogge** [comment]
`layoutInfo` is undefined 
![Screenshot 2023-07-07 at 9 09 16 AM](https://github.com/microsoft/vscode/assets/29464607/64bf33ff-fdc5-4cec-9c63-d8f5490c2aeb)

**Comment by meganrogge** [comment]
it gets set to `undefined` 
![Screenshot 2023-07-07 at 9 10 01 AM](https://github.com/microsoft/vscode/assets/29464607/8e3f3f90-bf85-4a37-b127-e8a0d27223bc)

**Comment by Tyriar** [comment]
@meganrogge that's the return value (see `[RPC Response]`)

**Comment by meganrogge** [comment]
yes, true. but the `getTerminalLayoutInfo` call returns `undefined` so it's getting reset somewhere. not via `saveState` 
![Screenshot 2023-07-07 at 9 18 06 AM](https://github.com/microsoft/vscode/assets/29464607/4d5aa016-0bae-41b4-8d82-f04aba1cd3b2)

**Comment by Tyriar** [comment]
I'm on to the cause... The process is getting killed after detaching on reload, so reconnect breaks:

```
2023-07-07 09:19:10.623 [trace] [RPC Request] PtyService#setTerminalLayoutInfo({"workspaceId":"199b212e1c8d1b0f08747c4773181855","tabs":[{"isActive":false,"activePersistentProcessId":3,"terminals":[{"relativeSize":1,"terminal":3}]},{"isActive":true,"activePersistentProcessId":4,"terminals":[{"relativeSize":1,"terminal":4}]}]})
2023-07-07 09:19:10.624 [trace] [RPC Response] PtyService#setTerminalLayoutInfo undefined
2023-07-07 09:19:10.869 [trace] [RPC Request] PtyService#input(4, "b")
2023-07-07 09:19:10.869 [trace] node-pty.IPty#write b
2023-07-07 09:19:10.869 [trace] [RPC Response] PtyService#input undefined
2023-07-07 09:19:10.869 [trace] node-pty.IPty#onData b
2023-07-07 09:19:10.876 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":4,"event":"b"})
2023-07-07 09:19:11.064 [trace] [RPC Request] PtyService#input(4, "c")
2023-07-07 09:19:11.064 [trace] node-pty.IPty#write c
2023-07-07 09:19:11.064 [trace] [RPC Response] PtyService#input undefined
2023-07-07 09:19:11.064 [trace] node-pty.IPty#onData c
2023-07-07 09:19:11.069 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":4,"event":"c"})
2023-07-07 09:19:11.406 [info] Persistent process "1": The reconnection grace time of 1m has expired, shutting down pid "3210"
2023-07-07 09:19:11.407 [trace] TerminalProcess#shutdown 
    at TerminalProcess.shutdown (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/terminalProcess.js:377:68)
    at PersistentTerminalProcess.shutdown (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:762:42)
    at ProcessTimeRunOnceScheduler.runner (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:678:22)
    at ProcessTimeRunOnceScheduler.onInterval (/Users/daimms/dev/microsoft/vscode/out/vs/base/common/async.js:784:26)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
2023-07-07 09:19:11.407 [trace] node-pty.IPty#kill
2023-07-07 09:19:11.408 [trace] [RPC Event] PtyService#_onProcessExit.fire({"id":1,"event":0})
2023-07-07 09:19:11.408 [info] Persistent process "2": The reconnection grace time of 1m has expired, shutting down pid "3211"
2023-07-07 09:19:11.408 [trace] TerminalProcess#shutdown 
    at TerminalProcess.shutdown (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/terminalProcess.js:377:68)
    at PersistentTerminalProcess.shutdown (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:762:42)
    at ProcessTimeRunOnceScheduler.runner (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:678:22)
    at ProcessTimeRunOnceScheduler.onInterval (/Users/daimms/dev/microsoft/vscode/out/vs/base/common/async.js:784:26)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
2023-07-07 09:19:11.408 [trace] node-pty.IPty#kill
2023-07-07 09:19:11.409 [trace] [RPC Event] PtyService#_onProcessExit.fire({"id":2,"event":0})
2023-07-07 09:19:11.409 [trace] node-pty.IPty#onData [?2004l
2023-07-07 09:19:11.409 [trace] node-pty.IPty#onData [?2004l
2023-07-07 09:19:11.409 [trace] node-pty.IPty#onData [?2004h[?2004l


2023-07-07 09:19:11.409 [trace] node-pty.IPty#onData [?2004h[?2004l


2023-07-07 09:19:11.412 [trace] TerminalProcess#_queueProcessExit 
    at TerminalProcess._queueProcessExit (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/terminalProcess.js:314:77)
    at /Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/terminalProcess.js:285:22
    at EventEmitter2.fire (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/eventEmitter2.js:41:22)
    at PipeSocket.<anonymous> (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/terminal.js:93:76)
    at PipeSocket.emit (node:events:513:28)
    at Terminal.emit (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/terminal.js:155:34)
    at PipeSocket.<anonymous> (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/unixTerminal.js:98:27)
    at Object.onceWrapper (node:events:628:26)
    at PipeSocket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:757:14)
2023-07-07 09:19:11.412 [trace] TerminalProcess#_queueProcessExit 
    at TerminalProcess._queueProcessExit (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/terminalProcess.js:314:77)
    at /Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/terminalProcess.js:285:22
    at EventEmitter2.fire (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/eventEmitter2.js:41:22)
    at PipeSocket.<anonymous> (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/terminal.js:93:76)
    at PipeSocket.emit (node:events:513:28)
    at Terminal.emit (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/terminal.js:155:34)
    at PipeSocket.<anonymous> (/Users/daimms/dev/microsoft/vscode/node_modules/node-pty/lib/unixTerminal.js:98:27)
    at Object.onceWrapper (node:events:628:26)
    at PipeSocket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:757:14)
2023-07-07 09:19:54.405 [trace] [RPC Request] PtyService#detachFromProcess(3, false)
2023-07-07 09:19:54.406 [trace] TerminalProcess#shutdown 
    at TerminalProcess.shutdown (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/terminalProcess.js:377:68)
    at PersistentTerminalProcess.shutdown (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:762:42)
    at PersistentTerminalProcess.detach (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:720:22)
    at PtyService.detachFromProcess (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:245:43)
    at descriptor.<computed> (/Users/daimms/dev/microsoft/vscode/out/vs/platform/terminal/node/ptyService.js:30:35)
    at Object.call (/Users/daimms/dev/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:850:39)
    at ChannelServer.onPromise (/Users/daimms/dev/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:287:35)
    at ChannelServer.onRawMessage (/Users/daimms/dev/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:266:33)
    at UniqueContainer.value (/Users/daimms/dev/microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:217:73)
    at Emitter._deliver (/Users/daimms/dev/microsoft/vscode/out/vs/base/common/event.js:832:26)
    at Emitter._deliverQueue (/Users/daimms/dev/microsoft/vscode/out/vs/base/common/event.js:843:22)
    at Emitter.fire (/Users/daimms/dev/microsoft/vscode/out/vs/base/common/event.js:866:22)
    at MessagePortMain.fn (/Users/daimms/dev/microsoft/vscode/out/vs/base/common/event.js:413:44)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-07-07 09:19:54.406 [trace] node-pty.IPty#kill
2023-07-07 09:19:54.406 [trace] [RPC Event] PtyService#_onProcessExit.fire({"id":3,"event":0})
2023-07-07 09:19:54.406 [trace] [RPC Response] PtyService#detachFromProcess undefined
2023-07-07 09:19:54.406 [trace] [RPC Request] PtyService#detachFromProcess(4, false)
2023-07-07 09:19:54.406 [trace] [RPC Response] PtyService#detachFromProcess undefined
```

Revive after restart is working for me.

**Comment by Tyriar** [comment]
Ah found it:

```
2023-07-07 09:28:56.963 [trace] [RPC Request] PtyService#getTerminalLayoutInfo({"workspaceId":"199b212e1c8d1b0f08747c4773181855"})
2023-07-07 09:28:56.964 [info] Expanding terminal instance, old id 199b212e1c8d1b0f08747c4773181855-3 -> new id undefined
2023-07-07 09:28:56.964 [warning] Couldn't get layout info, a terminal was probably disconnected Could not find pty on pty host
2023-07-07 09:28:56.964 [info] Reattach to wrong terminal debug info - layout info by id {"relativeSize":1,"terminal":3}
2023-07-07 09:28:56.964 [info] Reattach to wrong terminal debug info - _revivePtyIdMap []
```

One of the sanity checks I put in place that didn't actually help fix the reattach problem caused it

**Comment by Tyriar** [comment]
Parsed state is null so reconnect stops here: https://github.com/microsoft/vscode/blob/4b2f5dcf6aa977e5d7f21a659a7da1976bb1cb2d/src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalBackend.ts#L320
