### ISSUE TITLE
Integration test failure: verifies settings (css) 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#187484]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=222296
Changes: https://github.com/Microsoft/vscode/compare/ccea02b...6d10668

```
  1) VSCode Smoke Tests (Electron)
       Language Features
         verifies settings (css):
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:273:11)
      at Code.waitForElement (D:\a\_work\1\s\test\automation\src\code.ts:222:10)
      at Context.<anonymous> (src\areas\languages\languages.test.ts:51:4)

```

**Comment by sandy081** [comment]
Could be due to Atomic write changes which I reverted.
