### ISSUE TITLE
yo code fails immediately

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#18756]
- VSCode Version: 1.8
- OS Version: Windows 10

Steps to Reproduce:

1. npm install -g yo
2. npm install -g generator-code
3. yo code

yo code
C:\Users\ray\AppData\Roaming\npm\node_modules\yo\node_modules\configstore\index.js:69
                                throw err;
                                ^

Error: EPERM: operation not permitted, rename 'C:\Users\ray\.config\configstore\insight-yo.json.4205171772' -> 'C:\Users\ray\.config\configstore\insight-yo.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at Function.writeFileSync [as sync] (C:\Users\ray\AppData\Roaming\npm\node_modules\yo\node_modules\write-file-atomic\index.js:95:8)
    at Object.set (C:\Users\ray\AppData\Roaming\npm\node_modules\yo\node_modules\configstore\index.js:62:21)
    at Object.Configstore.set (C:\Users\ray\AppData\Roaming\npm\node_modules\yo\node_modules\configstore\index.js:93:11)
    at Insight.set (C:\Users\ray\AppData\Roaming\npm\node_modules\yo\node_modules\insight\lib\index.js:50:15)
    at Object.<anonymous> (C:\Users\ray\AppData\Roaming\npm\node_modules\yo\lib\cli.js:184:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

This smells like a npm issue, not Yeoman or Microsoft's generator, but figured I'd start here. :)

**Comment by cfjedimaster** [comment]
So I ran yo code once in an admin terminal and then it ran fine elsewhere. So... maybe not an issue for VSC at all?

**Comment by bpasero** [comment]
No, likely not. In general, NEVER run this as admin.
