### ISSUE TITLE
Chat in editor disappears after being restored on a window reload

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187764]
1. Start a panel chat session
2. Reopen it as an editor
3. Reload the window
4. Chat history is preserved
5. :bug: Chat suddenly disappears, nothing in the logs when this happens

<img width="346" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/5e1e86ce-d596-444e-ad1a-3cec6ae2b243">

**Comment by joyceerhl** [comment]
If I close the editor tab then I see this 

```
Unknown session: 4c911df4-809f-44e1-9352-990ee38cc948: Error: Unknown session: 4c911df4-809f-44e1-9352-990ee38cc948
    at $.clearSession (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1354:11359)
    at Gi.dispose (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:771:6090)
    at bn.mb (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:7467)
    at bn.kb (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:7079)
    at s.value (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:6825)
    at d.w (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1902)
    at d.x (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1972)
    at d.fire (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:69:2188)
    at Pn.closeEditor (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1155:58319)
    at bn.Db (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:14889)
    at bn.Kb (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:17175)
    at bn.closeEditors (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2475:16747)
    at async vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2303:57894
    at async Promise.all (index 0)
    at async I.k (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:127:23965)
    at async I.run (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:127:23889)
```

**Comment by roblourens** [comment]
Haven't been able to repro
