### ISSUE TITLE
Suggest widget gets orphaned in editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187779]
I don't have exact steps but I believe the gist was:
1. be typing something that triggers the suggest widget
2. ctrl+shift+k to delete whole line
3. :bug: suggest widget gets misplaced

If I select one of the suggested items here it even tries to update where my cursor currently is, where the suggestion was never valid in the first place
<img width="704" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/f9e54cf8-483e-41bc-a456-272a095c4eb7">

**Comment by jrieken** [comment]
@joyceerhl any errors on the console when this happens? I can't reproduce and the code doesn't have any obvious signs why this would happen

**Comment by joyceerhl** [comment]
I can trivially repro, here's a recording. In the following scenario when I press ctrl+shift+k I would expect the suggest widget to be dismissed:

https://github.com/microsoft/vscode/assets/30305945/a33bcdfe-9aa4-4ef9-bbc2-5d93d62abf4a


Here are my settings FWIW
```json
{
    "editor.inlineSuggest.enabled": true,
    "github.copilot.advanced": {
        "slashCommands": {
            "*": true
        }
    },
    "typescript.inlayHints.propertyDeclarationTypes.enabled": true,
    "typescript.inlayHints.enumMemberValues.enabled": true,
    "typescript.inlayHints.functionLikeReturnTypes.enabled": true,
    "typescript.inlayHints.parameterNames.enabled": "all",
    "typescript.inlayHints.parameterTypes.enabled": true
}
```

And this is what dev tools says
```
[perf] Renderer reported VERY LONG TASK (3084ms), starting profiling session '86cbdfcd-d384-46f6-b5d0-96d210e8293f'
log.ts:441   ERR [PerfSampleError]: [PerfSampleError] by <<renderer>> in _deliver#event.js:822:17
	 at _deliver (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:822:17)
	 at fire (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:851:13)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.js:135:71)
	 at _deliver (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:822:17)
	 at _deliverQueue (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:839:22)
	 at fire (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:851:13)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1194:54)
	 at _deliver (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:822:17)
	 at fire (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:851:13)
	 at _emitOutgoingEvents (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/common/viewModelEventDispatcher.js:36:28)
	 at endEmitViewEvents (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/common/viewModelEventDispatcher.js:72:26)
	 at _withViewEventsCollector (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:850:33)
	 at _executeCursorEdit (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:789:27)
	 at executeEdits (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:797:21)
	 at executeEdits (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:833:21)
	 at insert (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/snippet/browser/snippetSession.js:498:15)
	 at _doInsert (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/snippet/browser/snippetController2.js:80:18)
	 at insert (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/snippet/browser/snippetController2.js:65:15)
	 at _insertSuggestion (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/suggest/browser/suggestController.js:219:26)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/suggest/browser/suggestController.js:96:56)
	 at _deliver (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:822:17)
	 at fire (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:851:13)
	 at fire (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:979:13)
	 at _select (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/suggest/browser/suggestWidget.js:251:16)
	 at _onListMouseDownOrTap (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/suggest/browser/suggestWidget.js:237:30)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/contrib/suggest/browser/suggestWidget.js:187:58)
	 at _deliver (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:822:17)
	 at fire (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:851:13)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:98:79)
	 at _deliver (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:822:17)
	 at fire (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/common/event.js:851:13)
	 at fn (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/browser/event.js:14:24)
log.ts:441   ERR [PerfSampleError]: [PerfSampleError] by <<renderer>> in getBoundingClientRect
	 at getBoundingClientRect
	 at getDomNodePagePosition (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/base/browser/dom.js:370:36)
	 at createEditorPagePosition (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/editorDom.js:68:38)
	 at EditorMouseEvent (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/editorDom.js:92:20)
	 at _create (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/editorDom.js:106:16)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/editorDom.js:135:67)
log.ts:441   ERR [PerfSampleError]: [PerfSampleError] by <<renderer>> in collect#viewPart.js:44:23
	 at collect (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/view/viewPart.js:44:23)
	 at mouseTargetIsWidget (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/controller/mouseTarget.js:365:28)
	 at _onMouseMove (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/controller/mouseHandler.js:168:21)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/controller/mouseHandler.js:22:81)
	 at (anonymous) (vscode-file://vscode-app/c:/Users/huer/Source/vscode/out/vs/editor/browser/editorDom.js:135:67)
```

**Comment by jrieken** [comment]
Thanks, I can now reproduce. This important part is the the cursor doesn't change, e.g the line below must be of equal or greater length so that the cursor stays put. We then do receive a model change event but positioning is again so that we don't cancel or update the current session. 

This is a fun bug and I believe something that have since multiple years

**Comment by jrieken** [comment]
This isn't fixed, I only pushed a failing/skipped test.
