### ISSUE TITLE
inno_updater.exe crashes every time I update VSCode-insiders.

### ISSUE THREAD

**Issue by adolfdaniel** [microsoft/vscode#187885]
Type: <b>Bug</b>

I get nightly updates on VSCode insiders and I get the crash on inno_updater.exe whenever I restart the app for updating it.

VS Code version: Code - Insiders 1.81.0-insider (2f1013a310bbd74410e74fad99497841edad0eda, 2023-07-13T05:33:32.822Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (42.42GB free)|
|Process Argv|--crash-reporter-id 0d7e94f8-13a8-49e9-871d-e0f29a922d60|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-chromium-vector-icons|ado|1.0.2
togglehs|bbe|0.1.2
gitlens|eam|2023.7.1305
copilot|Git|1.96.259
copilot-chat|Git|0.5.2023071304
mojom-language|Joe|0.0.1
vscode-webidl|keq|0.0.1
vscode-clangd|llv|0.1.24
cpplint|min|0.1.3
autopep8|ms-|2023.7.11941910
python|ms-|2023.13.11941005
vscode-pylance|ms-|2023.7.21
remote-ssh|ms-|0.103.2023071215
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.16.3
remote-explorer|ms-|0.5.2023062609
gnls|mse|0.1.4
java|red|1.21.2023071204
code-spell-checker|str|2.20.5
change-case|wma|1.0.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
bgfeh915:30780428
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30779712
asynctok:30783811
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by joaomoreno** [comment]
Any details on the crash? Any error messages? Any logs?

**Comment by adolfdaniel** [comment]
[inno_updater_crash.zip](https://github.com/microsoft/vscode/files/12059491/inno_updater_crash.zip)
@joaomoreno: I've attached the Crash Dump. 

**Note**: I used 7-zip to compress to 7z and then to zip (to make it smaller that GitHub allowed size and format).

**Comment by jmbockhorst** [comment]
The same thing has been happening to me.

**Comment by jineens** [comment]
This has been happening to me too. 
[vscode-inno-updater-1689700667.log](https://github.com/microsoft/vscode/files/12084099/vscode-inno-updater-1689700667.log)

**Comment by joaomoreno** [comment]
Thanks guys, I've confirmed the issue!

**Comment by joaomoreno** [comment]
Got a stack trace:

```
❯ cargo run -- "C:\Users\jomo\AppData\Local\Programs\Microsoft VS Code\Code.exe" false 
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target\i686-pc-windows-msvc\debug\inno_updater.exe "C:\Users\jomo\AppData\Local\Programs\Microsoft VS Code\Code.exe" false`
thread 'main' panicked at 'range end index 117 out of range for slice of length 113', src\model\filerec.rs:120:50
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\slice\index.rs:78
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\slice\index.rs:70
   4: core::slice::index::impl$4::index<u8>
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\slice\index.rs:411
   5: inno_updater::model::filerec::decode_strings
             at .\src\model\filerec.rs:120
   6: inno_updater::model::filerec::FileRec::rebase
             at .\src\model\filerec.rs:296
   7: inno_updater::patch_uninstdat::closure$1
             at .\src\main.rs:295
   8: core::iter::traits::iterator::Iterator::try_fold<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,tuple$<>,core::iter::adapters::map::map_try_fold::closure_env$0<ref$<inno_updater::model::filerec::FileRec>,enum2$<core::result::Result<inno_up
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\traits\iterator.rs:2304
   9: core::iter::traits::iterator::Iterator::try_fold<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,tuple$<>,core::iter::adapters::map::map_try_fold::closure_env$0<ref$<inno_updater::model::filerec::FileRec>,enum2$<core::result::Result<inno_up
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\traits\iterator.rs:2304
  10: core::iter::adapters::map::impl$2::try_fold<enum2$<core::result::Result<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > >,core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater:
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\map.rs:117
  11: core::iter::adapters::impl$0::try_fold<core::iter::adapters::map::Map<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater::patch_uninstdat::closure_env$1>,enum2$<core::result::Result<enum2$<core::convert::Infallible>,alloc::boxed::
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\mod.rs:195
  12: core::iter::adapters::impl$0::next<core::iter::adapters::map::Map<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater::patch_uninstdat::closure_env$1>,enum2$<core::result::Result<enum2$<core::convert::Infallible>,alloc::boxed::Box<
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\mod.rs:178
  13: alloc::vec::spec_extend::impl$0::spec_extend<inno_updater::model::filerec::FileRec,core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater::patch_uninstdat::closure_env$
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\alloc\src\vec\spec_extend.rs:17
  14: alloc::vec::spec_from_iter::impl$0::from_iter<inno_updater::model::filerec::FileRec,core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater::patch_uninstdat::closure_env
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\alloc\src\vec\spec_from_iter.rs:33
  15: core::iter::traits::iterator::Iterator::collect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\traits\iterator.rs:1896
  16: core::result::impl$25::from_iter::closure$0<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global>,alloc::vec::Vec<inno_updater::model::filerec::FileRec,alloc::alloc::Global>,core::iter::adapters::map::Map<c
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1969
  17: core::result::impl$25::from_iter<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global>,alloc::vec::Vec<inno_updater::model::filerec::FileRec,alloc::alloc::Global>,core::iter::adapters::map::Map<core::slice:
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1969
  18: inno_updater::patch_uninstdat
             at .\src\main.rs:291
  19: alloc::vec::spec_extend::impl$0::spec_extend<inno_updater::model::filerec::FileRec,core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater::patch_uninstdat::closure_env$
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\alloc\src\vec\spec_extend.rs:17
  20: alloc::vec::spec_from_iter::impl$0::from_iter<inno_updater::model::filerec::FileRec,core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater::patch_uninstdat::closure_env
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\alloc\src\vec\spec_from_iter.rs:33
  21: core::iter::traits::iterator::Iterator::collect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\traits\iterator.rs:1896
  22: core::result::impl$25::from_iter::closure$0<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global>,alloc::vec::Vec<inno_updater::model::filerec::FileRec,alloc::alloc::Global>,core::iter::adapters::map::Map<c
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1969
  23: core::result::impl$25::from_iter<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global>,alloc::vec::Vec<inno_updater::model::filerec::FileRec,alloc::alloc::Global>,core::iter::adapters::map::Map<core::slice:
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1969
  24: inno_updater::patch_uninstdat
             at .\src\main.rs:291
  25: alloc::vec::spec_from_iter::impl$0::from_iter<inno_updater::model::filerec::FileRec,core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::slice::iter::Iter<inno_updater::model::filerec::FileRec>,inno_updater::patch_uninstdat::closure_env
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\alloc\src\vec\spec_from_iter.rs:33
  26: core::iter::traits::iterator::Iterator::collect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\traits\iterator.rs:1896
  27: core::result::impl$25::from_iter::closure$0<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global>,alloc::vec::Vec<inno_updater::model::filerec::FileRec,alloc::alloc::Global>,core::iter::adapters::map::Map<c
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1969
  28: core::result::impl$25::from_iter<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global>,alloc::vec::Vec<inno_updater::model::filerec::FileRec,alloc::alloc::Global>,core::iter::adapters::map::Map<core::slice:
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1969
  29: inno_updater::patch_uninstdat
             at .\src\main.rs:291
  30: core::result::impl$25::from_iter<inno_updater::model::filerec::FileRec,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global>,alloc::vec::Vec<inno_updater::model::filerec::FileRec,alloc::alloc::Global>,core::iter::adapters::map::Map<core::slice:
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1969
  31: inno_updater::patch_uninstdat
             at .\src\main.rs:291
  32: inno_updater::do_update
             at .\src\main.rs:328
  33: inno_updater::update
             at .\src\main.rs:357
  34: inno_updater::_main
             at .\src\main.rs:409
  35: inno_updater::__main
             at .\src\main.rs:445
  36: inno_updater::main
             at .\src\main.rs:541
  37: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\i686-pc-windows-msvc\debug\inno_updater.exe "C:\Users\jomo\AppData\Local\Programs\Microsoft VS Code\Code.exe" false` (exit code: 101)
```

**Comment by joaomoreno** [comment]
Caused by https://github.com/microsoft/inno-updater/pull/18, namely:

- https://github.com/microsoft/inno-updater/pull/18/files#diff-c7622b93e61bf3ac2a8eb8b777168d7f065f6250bde21d3d14a551854761d1fcL98
- https://github.com/microsoft/inno-updater/pull/18/files#diff-c7622b93e61bf3ac2a8eb8b777168d7f065f6250bde21d3d14a551854761d1fcL101
