### ISSUE TITLE
HTTP request from WASM fails in extension host

### ISSUE THREAD

**Issue by pylasnier** [microsoft/vscode#187822]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0
- OS Version: Window 10

I'm trying to use Rust-built WASM in a VSCode extension, but there's an HTTP request call in the WASM that fails only in VSCode extension host, not in a normal Node instance. The specific error is:

```
Failure: Failed - builder error: JsValue(ReferenceError: Headers is not defined
ReferenceError: Headers is not defined
	at C:\Users\pascal\source\wasm-test\pkg\wasm_test.js:449:17
	at handleError (C:\Users\pascal\source\wasm-test\pkg\wasm_test.js:286:18)
	at module.exports.__wbg_new_1eead62f64ca15ce (C:\Users\pascal\source\wasm-test\pkg\wasm_test.js:448:65)
	at wasm://wasm/001a6756:wasm-function[51]:0x2592
	at wasm://wasm/001a6756:wasm-function[123]:0x2137d
	at wasm://wasm/001a6756:wasm-function[328]:0x2f24b
	at __wbg_adapter_26 (C:\Users\pascal\source\wasm-test\pkg\wasm_test.js:211:10)
	at real (C:\Users\pascal\source\wasm-test\pkg\wasm_test.js:196:20))
```

Steps to Reproduce:

1. I'm trying to use a crate called reqwest with some simple API for HTTP calls, with the Rust source looking like this:
```
#[wasm_bindgen]
pub async fn test_http() -> Result<String, String> {
    match reqwest::get("https://www.rust-lang.org").await {
        Ok(got) => {
            if let Ok(text) = got.text().await {
                Ok(text)
            }
            else {
                Err("No text".to_string())
            }
        },
        Err(e) => Err(format!("Failed - {}", e.to_string())),
    }
}
```
2. I'm then building it with `wasm-pack build --target nodejs` and adding it to my VSCode extension project using `npm link` in the WASM pkg directory, then `npm link wasm-test` in the extension project directory.
3. Running the extension and activating it, with the following code, fails with the above error message. Instead of panicking, the HTTP client builder running underneath seems to be catching and returning the error in the Rust code.
```
import * as vscode from 'vscode';
import { test_http } from 'wasm-test';

export function activate(context: vscode.ExtensionContext) {

    ...
    
    test_http().then(m => console.log(`Success: ${m}`))
        .catch(e => console.log(`Failure: ${String(e)}`));
}
```
If instead the `activate` function has its context argument removed then run in the top level scope using a manual `tsc` then `node .\out\extension.js`, it succeeds as expected. I'm struggling to get other HTTP client crates to compile to WASM, but reqwest is the most popular one and otherwise works just fine for me, so I would like to know what about the extension host is breaking it.

**Comment by alexdima** [comment]
🤖 Thanks for the report. Since VS Code 1.80, the bundled Electron (and thus Node.js) has been upgraded significantly — current VS Code ships Electron 42.5 with Node.js 22+, where `fetch`, `Headers`, `Request`, and `Response` are stable globals available in the extension host. The `Headers is not defined` error should no longer occur on any recent VS Code version.

If you're still seeing this on the latest VS Code, please open a new issue with updated reproduction steps. Closing as not reproducible against the current build.
