### ISSUE TITLE
Getting `setDecorations on invisible editor` warning

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#18797]
Have the following code in an extension, which will set decorations on visible editors every 100ms.

```typescript
setInterval(() => {
    const decoration = vscode.window.createTextEditorDecorationType({});
    vscode.window.visibleTextEditors.forEach(e => {
        e.setDecorations(decoration, []);
    })
}, 100);
```

If you click around the explorer and open up different files, you'll see `setDecorations on invisible editor` warnings in the dev tools. There's no apparent way I could avoid them.

---

A bit worse:

```typescript
setInterval(() => {
    const decoration = vscode.window.createTextEditorDecorationType({});
    vscode.window.visibleTextEditors.forEach(e => {
        e.document;
    })
}, 100);
```

Instead of a warning, there's an NPE error the console:

```
shell.ts:433 Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at /Users/joao/.vscode-insiders/extensions/cssho.vscode-svgviewer-1.3.0/out/src/extension.js:92:62
    at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:1151)
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:4638)
    at t.$acceptModelChanged (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:22027)
    at t.e.handle (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:10:24348)
    at s (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:28264)
    at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:28941)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jrieken** [comment]
@joaomoreno I see the warning but I cannot repo the NPE. Is there some secret step missing?

**Comment by jrieken** [comment]
Ok - I might push another change that we don't explode but make `editor.document` be `undefined` when the editor detached.

**Comment by CoenraadS** [comment]
I have a similar issue in my extension which is related to this issue.

Its hard to reproduce, but it happens when closing files. Very rarely an invalid document will returned by   vscode.window.visibleTextEditors that will have a lineCount of 0. So now my code looks like this:

```
vscode.window.visibleTextEditors.forEach((editor) => {
            if (editor.document && editor.document.lineCount !== 0 ) {
                
            }
        });
```

Maybe related to this issue, maybe I should make a new one?

**Comment by jrieken** [comment]
@CoenraadS steps to repo?

**Comment by CoenraadS** [comment]
It is very difficult to repo.

I created a branch of my extension stripped to the core as a kind of minimum repo scenario:  https://github.com/CoenraadS/BracketPair/tree/repo

I made a video of it occurring (happens at the end of video): https://youtu.be/IvDztPCKtVw

Basically open and close files until it occurs. But how long this takes is random since I don't know the exact trigger.

**Comment by CoenraadS** [comment]
I think I found the original cause: https://github.com/Microsoft/vscode/issues/20867

**Comment by aeschli** [comment]
Verified that 'Getting `setDecorations on invisible editor` warning' is gone. But I see now 'TextEditor disposed' messages.
@jrieken Is that ok?

**Comment by jrieken** [comment]
Yeah, that's part of a larger issue I have scheduled for March
