### ISSUE TITLE
Unable to start devcontainer when code resides on google drive

### ISSUE THREAD

**Issue by dss010101** [microsoft/vscode#187997]
I have recently moved most of all of my projects and code over to a google drive (which is mapped as the G: drive on my windows system). 

When building and restarting my dev container in vscode, i am not getting the below error.  This does not happen if switch back to my original location for the code.  Does anyone know what this error means and how to resolve?
```

Error:
Error response from daemon: Container d1b72f21cd2c769ded35ecfcd3bcb8c8ca508bf247
c9e5f29d9d11b4d8e440df is restarting, wait until the container is running
[2023-07-15T20:26:56.793Z] Stop (795 ms): Run: docker-compose --project-name ts_service_devcontainer -f g:\My Drive\Documents\Projects\ts_lab\ts_service\.devcontainer\docker-compose.yml -f c:\Users\tks0101\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1689452777838.yml -f c:\Users\tks0101\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.containerFeatures-1689452815997.yml up -d
[2023-07-15T20:26:56.798Z] Error: Command failed: docker-compose --project-name ts_service_devcontainer -f g:\My Drive\Documents\Projects\ts_lab\ts_service\.devcontainer\docker-compose.yml -f c:\Users\tks0101\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1689452777838.yml -f c:\Users\tks0101\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.containerFeatures-1689452815997.yml up -d
[2023-07-15T20:26:56.798Z]     at Tte (c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:1972:3061)
[2023-07-15T20:26:56.799Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-07-15T20:26:56.799Z]     at async Pte (c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:1954:3170)
[2023-07-15T20:26:56.799Z]     at async rre (c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:3833)
[2023-07-15T20:26:56.799Z]     at async Yf (c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:4775)
[2023-07-15T20:26:56.800Z]     at async Dne (c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:12193)
[2023-07-15T20:26:56.800Z]     at async Sne (c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:11934)
[2023-07-15T20:26:56.815Z] Stop (42168 ms): Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\tks0101\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-ba70dcef-505f-4354-86c9-d0d98cc22b681689452771140 --workspace-folder g:\My Drive\Documents\Projects\ts_lab\ts_service --workspace-mount-consistency cached --id-label devcontainer.local_folder=g:\My Drive\Documents\Projects\ts_lab\ts_service --id-label devcontainer.config_file=g:\My Drive\Documents\Projects\ts_lab\ts_service\.devcontainer\devcontainer.json --log-level debug --log-format json --config g:\My Drive\Documents\Projects\ts_lab\ts_service\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-1ebab04d-6759-48b7-a2d2-78be848e06a2.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-07-15T20:26:56.816Z] Exit code 1
**[2023-07-15T20:26:56.819Z] Command failed: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\tks0101\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\tks0101\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-ba70dcef-505f-4354-86c9-d0d98cc22b681689452771140 --workspace-folder g:\My Drive\Documents\Projects\ts_lab\ts_service --workspace-mount-consistency cached --id-label devcontainer.local_folder=g:\My Drive\Documents\Projects\ts_lab\ts_service --id-label devcontainer.config_file=g:\My Drive\Documents\Projects\ts_lab\ts_service\.devcontainer\devcontainer.json --log-level debug --log-format json --config g:\My Drive\Documents\Projects\ts_lab\ts_service\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-1ebab04d-6759-48b7-a2d2-78be848e06a2.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true**
[2023-07-15T20:26:56.819Z] Exit code 1
```

The docker-compose looks like this and the underlying docker image for ts_service is based on mcr.microsoft.com/devcontainers/python:3-bullseye
```
version: '3.8'

services:
  ts_service:
    container_name: ts_service
    image: ts_service
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    shm_size: 0.94gb

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:tks_db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  tks_db:
    #image: timescale/timescaledb:latest-pg15
    image: postgres
    restart: unless-stopped
    volumes:
      - ../../database/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ******
      POSTGRES_DB: tks_db
      POSTGRES_PASSWORD: ************
    ports: 
      - 5001:5000
      - 5433:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

```

**Comment by chrmarti** [comment]
Similar error: https://github.com/moby/moby/issues/40835
