### ISSUE TITLE
TypeError: arg is not iterable

### ISSUE THREAD

**Issue by davidevertuani** [microsoft/vscode#187905]
Type: <b>Bug</b>

I have tasks defined in my workspace folder, which have been working fine for years now.
Suddently, 'Run task' does not show any option to select from.

I am working on Windows, on a remote Linux host.

The 'Window' output section reports the following:

```
2023-07-14 09:18:37.814 [error] le.args is not iterable: TypeError: le.args is not iterable
    at q (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1516:77450)
    at Object.J [as from] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1516:76784)
    at Object.Y [as from] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1516:87073)
    at Object.ee [as from] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1516:90547)
    at x.f (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1517:55)
    at x.run (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1516:95185)
    at Object.K [as parse] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1517:1153)
    at e.TaskService.Qc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1911:6025)
    at e.TaskService.Oc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1911:5478)
    at e.TaskService.Jc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1911:3269)
    at async e.RunAutomaticTasks.h (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1516:60088)
```

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.0-101.103.2.1.el8uek.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.19GB free)|
|Process Argv|--crash-reporter-id 62a7911a-5053-4940-96e3-a8809dd2d4ef|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: REDACTED|
|OS|Linux x64 5.15.0-101.103.2.1.el8uek.x86_64|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2500)|
|Memory (System)|15.50GB (9.97GB free)|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
better-shellscript-syntax|jef|1.6.2
AWK|lug|0.0.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.79.5
remote-explorer|ms-|0.5.2023062109
shebang-snippets|rpi|0.1.4
multi-command|ryu|1.6.0
pdf|tom|1.2.2
vscode-icons|vsc|12.4.0
vscode-todo-highlight|way|1.0.5
material-theme|zhu|3.15.18
doxdocgen|csc|1.4.0
linter-gfortran|for|3.2.0
gitlab-workflow|Git|3.68.3
fracturedjsonvsc|j-b|3.1.0
gitlab-mr|jas|1.4.3
better-cpp-syntax|jef|1.17.2
svn-scm|joh|2.17.0
cmake-language-support-vscode|jos|0.0.9
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2023.10.1
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.20
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
vsliveshare|ms-|1.0.5873
vscode-print|pdc|0.11.15
vscode-xml|red|0.26.1
vscode-wl|shi|1.7.3
cmake|twx|0.0.17
gitblame|wad|10.3.0
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30789496
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200
dsvsc013cf:30789518

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by davidevertuani** [comment]
Vscode distribution is controlled by system admins, we have no ability to install anything on our machines.
Will try to have a hold of an IT guy next week, not sure whether I'll be able to try it out tho.

**Comment by meganrogge** [comment]
Pretty sure this is fixed in insiders. Lmk if not

**Comment by davidevertuani** [comment]
Yes, fixed in insiders.
