### ISSUE TITLE
Extension host terminating: renderer closed the MessagePort

### ISSUE THREAD

**Issue by ThePlenkov** [microsoft/vscode#188056]
Do you have any idea why I have such a message in my vs code log?

```
2023-07-17 12:31:50.478 [info] Eager extensions activated
2023-07-17 12:31:50.590 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
2023-07-17 12:31:50.628 [info] ExtensionService#_doActivateExtension ParthR2031.colorful-comments, startup: false, activationEvent: 'onLanguage:plaintext'
2023-07-17 12:31:50.636 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-07-17 12:31:50.698 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-07-17 12:32:50.199 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh, startup: false, activationEvent: '*', root cause: SAPOSS.app-studio-toolkit
2023-07-17 12:32:50.253 [info] ExtensionService#_doActivateExtension ms-vscode.remote-explorer, startup: false, activationEvent: 'onCommand:remote-internal.setActiveFolders'
2023-07-17 12:32:50.267 [info] ExtensionService#_doActivateExtension ms-vscode.remote-server, startup: false, activationEvent: 'onCommand:remote-tunnels.internal.isAuthenticated'
2023-07-17 12:34:11.690 [info] Extension host terminating: renderer closed the MessagePort
2023-07-17 12:34:11.709 [error] Canceled: Canceled
	at new h (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:42413)
	at t.O (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11236)
	at U.<computed>.q.charCodeAt.U.<computed> (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:8675)
	at e.$vL.g (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:63549)
	at e.$vL.executeCommand (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62973)
	at P.registerCommand.description (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62280)
	at e.$vL.h (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:64085)
	at e.$vL.g (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:63073)
	at e.$vL.executeCommand (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62973)
	at Object.executeCommand (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20971)
	at t.shutdown (c:\Users\pplenkov\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:646929)
	at e.deactivate (c:\Users\pplenkov\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:723956)
	at i.Z (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:10175)
	at c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8332
	at Array.map (<anonymous>)
	at i.S (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8319)
	at i.terminate (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8591)
	at u.terminate (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1532)
	at E (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:32236)
	at MessagePortMain.<anonymous> (c:\Users\pplenkov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28665)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
```

The real issue is message like this:
```
Cannot activate the 'SAP Business Application Studio toolkit' extension because it depends on the 'Remote - SSH: Editing Configuration Files' extension, which is not loaded. Would you like to reload the window to load the extension?
```
which is described here: https://github.com/SAP/app-studio-toolkit/issues/25 but I feel that that message is connected to the error mentioned above.

**Comment by kartikgupta-db** [comment]
The issue still seems to exist in v1.81 but not in the insiders build. When can the fix be rolled out?

**Comment by ThePlenkov** [comment]
in my case the issue was caused by the extension, It was fixed with a new reelease
