### ISSUE TITLE
test function so broken

### ISSUE THREAD

**Issue by QihangYao** [microsoft/vscode#188106]
Type: <b>Bug</b>

Just see the log:

2023-07-17 15:12:17.555 [info] Discover tests for workspace name: FIN-social - uri: /Users/kaichuan/Repos/FIN-social
2023-07-17 15:12:17.558 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear tests
2023-07-17 15:12:17.559 [info] cwd: .
2023-07-17 15:12:17.826 [error] Error discovering pytest tests:
 n [Error]: 
EnvironmentLocationNotFound: Not a conda environment: /Users/kaichuan/mambaforge/envs/fin/envs/fin

    at ChildProcess.<anonymous> (/Users/kaichuan/.vscode/extensions/ms-python.python-2023.12.0/out/client/extension.js:2:241817)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1121:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2023-07-17 15:12:27.936 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py -c "import pytest"
2023-07-17 15:12:28.101 [info] Send text to terminal: conda install --name fin pytest -y
2023-07-17 15:12:28.102 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py -c "import pytest"
2023-07-17 15:19:24.627 [info] > conda info --json
2023-07-17 15:19:46.486 [info] Discover tests for workspace name: FIN-social - uri: /Users/kaichuan/Repos/FIN-social
2023-07-17 15:19:46.489 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/printEnvVariables.py
2023-07-17 15:19:46.489 [info] shell: bash
2023-07-17 15:19:47.113 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear tests
2023-07-17 15:19:47.113 [info] cwd: .
2023-07-17 15:19:47.366 [error] Error discovering pytest tests:
 n [Error]: 
EnvironmentLocationNotFound: Not a conda environment: /Users/kaichuan/mambaforge/envs/fin/envs/fin

    at ChildProcess.<anonymous> (/Users/kaichuan/.vscode/extensions/ms-python.python-2023.12.0/out/client/extension.js:2:241817)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1121:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2023-07-17 15:19:50.185 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/printEnvVariables.py
2023-07-17 15:19:50.185 [info] shell: bash
2023-07-17 15:19:50.675 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py -c "import pytest"
2023-07-17 15:19:50.820 [info] > conda run -n fin --no-capture-output python ~/.vscode/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py -c "import pytest"
2023-07-17 15:19:50.933 [info] > conda info --json
2023-07-17 15:19:51.304 [info] Send text to terminal: conda activate fin
2023-07-17 15:19:51.810 [info] Send text to terminal: conda install --name fin pytest -y

Here are two pieces of log that I especially want to complain about:

EnvironmentLocationNotFound: Not a conda environment: /Users/kaichuan/mambaforge/envs/fin/envs/fin

2023-07-17 15:19:51.810 [info] Send text to terminal: conda install --name fin pytest -y

Here are some of my comments:
1. Why can't it locate the Python environment that I have, like all other extensions or functions of VSCode does?
2. How is the "conda install --name fin pytest -y" a good solution to the "EnvironmentLocationNotFound" error?
3. Please don't put "-y" after any "conda install" that you decide to initiate. You don't know what you can mess up.

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:58.115Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id e7641681-a248-4b39-b8fd-a92e2c3e5516|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.96.255
vscode-language-pack-zh-hans|MS-|1.80.2023071209
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.20
jupyter|ms-|2023.6.1101941928
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30789497
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013:30789517

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! We are in the process of releasing a new rewrite for testing which could possibly help your issue but will also become the default soon. I see from your logs that your machine is not in the experiment yet but you can enable it by going to your **user** settings and adding`"python.experiments.optInto": ["pythonTestAdapter"]`.  If you could send the logs when you have that setting turned on I can get it fixed for testing moving forward instead of the testing infrastructure we are phasing out. Thanks
