### ISSUE TITLE
after I accept a chat suggestion (fix with copilot), the chat won't go away

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#188208]
![Screenshot 2023-07-18 at 2 53 03 PM](https://github.com/microsoft/vscode/assets/29464607/568de410-e3f4-449c-a2c4-4a97849865ee)

**Comment by meganrogge** [comment]
in the console
```

workbench.desktop.main.js:sourcemap:627   ERR Model is disposed!: Error: Model is disposed!
    at Qn.cb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:710:262)
    at Qn.getTextBuffer (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:710:378)
    at s.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1860:27299)
    at u.w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1902)
    at u.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:2119)
    at me (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:44888)
```

**Comment by meganrogge** [comment]
![Screenshot 2023-07-18 at 2 56 17 PM](https://github.com/microsoft/vscode/assets/29464607/07cf75a1-dae4-4465-8f72-31897953a4d9)

**Comment by hediet** [comment]
Probably caused by me, will investigate tomorrow.

**Comment by hediet** [comment]
I cannot reproduce on main (in screen reader optimized mode).
