### ISSUE TITLE
Exception in new settings

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18828]
The search wasn't working, when I switched again the settings page crashed and gave me the error "Unable to open 'settings.json': t.toLowerCase is not a function."

```
shell.ts:433t.toLowerCase is not a function: TypeError: t.toLowerCase is not a function
    at Object.a [as matchesContiguousSubString] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:9723)
    at f (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:12104)
    at t._findMatchesInSetting (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:12326)
    at t.doFilterSettings (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:10839)
    at t.filterSettings (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:88:17549)
    at t.filterPreferences (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:111:18740)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:111:16522
    at e.invoke (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26468)
    at e.fire (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:29957)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:91:16925e.onUnexpectedError @ shell.ts:433
messageService.ts:126Unable to open 'settings.json': t.toLowerCase is not a function.: Error: Unable to open 'settings.json': t.toLowerCase is not a function.
    at t.doHandleSetInputError (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:124:14503)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:124:14109
    at Object.v [as _notify] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12410)
    at Object.enter (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15408)
    at _run (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17236)
    at _completed (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16677)
    at u (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20215)
    at Y.then.o.(anonymous function) (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20432)
    at Object.g [as _notify] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:11830)
    at Object.enter (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15408)
```

Can no longer open settings now.

**Comment by sandy081** [comment]
Duplicates #18557
