### ISSUE TITLE
Flaky integration test: window.onDidWriteTerminalData should listen to all future terminal data events

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188375]
macOS Run integration tests (Remote)

```
  271 passing (2m)
  16 pending
  1 failing
  1) vscode API - terminal
       Terminal
         window.onDidWriteTerminalData
           should listen to all future terminal data events:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.ok)(dataEvents.some(e => e.name === 'test1' && e.data === 'write1'))

      + expected - actual

      -false
      +true
      
      at t.value (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts:410:10)
      at p.w (out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
      at p.fire (out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
      at A.$acceptTerminalClosed (out/vs/workbench/api/node/extensionHostProcess.js:105:142065)
      at i.N (out/vs/workbench/api/node/extensionHostProcess.js:115:7983)
      at i.M (out/vs/workbench/api/node/extensionHostProcess.js:115:7749)
      at i.H (out/vs/workbench/api/node/extensionHostProcess.js:115:6830)
      at i.G (out/vs/workbench/api/node/extensionHostProcess.js:115:6045)
      at t.value (out/vs/workbench/api/node/extensionHostProcess.js:115:4736)
      at p.w (out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
      at p.fire (out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
      at k.fire (out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
      at t.value (out/vs/workbench/api/node/extensionHostProcess.js:131:30355)
      at p.w (out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
      at p.fire (out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
      at k.fire (out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
      at r.z (out/vs/workbench/api/node/extensionHostProcess.js:79:16996)
      at t.value (out/vs/workbench/api/node/extensionHostProcess.js:79:15448)
      at p.w (out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
      at p.fire (out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
      at t.acceptChunk (out/vs/workbench/api/node/extensionHostProcess.js:79:11705)
      at t.value (out/vs/workbench/api/node/extensionHostProcess.js:79:10992)
      at p.w (out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
      at p.fire (out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
      at p.u (out/vs/workbench/api/node/extensionHostProcess.js:131:19077)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=224232&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=efbaf268-cf98-50c2-bb3c-7950770fd6bc&l=682

**Comment by sandy081** [comment]
@Tyriar I skipped this test as it caused build failures quite often yesterday.
