### ISSUE TITLE
ExtensionHostManager: Trying to add a disposable to a DisposableStore that has already been disposed of

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188307]
Saw a bad dispose in CI - Run integration tests (Browser, Chromium)

https://dev.azure.com/vscode/VSCode/_build/results?buildId=98889&view=logs&j=a8a6689c-5a84-59c0-482a-7dd9f21eb2d8&t=6a176377-a7f9-5885-a44e-71e6c3076321

```
resolveCopyDestination
    ✔ Relative destinations should resolve next to document
    ✔ Destination starting with / should go to workspace root
    ✔ If there is no workspace root, / should resolve to document dir
    ✔ If path ends in /, we should automatically add the fileName
    ✔ Basic transform
    ✔ transforms should support capture groups
  Markdown Document links
    - Should navigate to markdown file
    - Should navigate to markdown file with leading ./
    - Should navigate to markdown file with leading /
    - Should navigate to markdown file without file extension
    - Should navigate to markdown file in directory
    - Should navigate to fragment by title in file
    - Should navigate to fragment by line
    - Should navigate to line number within non-md file
    - Should navigate to fragment within current file
    - Should navigate to fragment within current untitled file
  markdown.engine
    rendering
      ✔ Renders a document (160ms)
      ✔ Renders a string
    image-caching
      ✔ Extracts all images
  urlToUri
    ✔ Absolute File
    ✔ Relative File
    ✔ Http Basic
    ✔ Http Encoded Chars
Ignoring fetching additional builtin extensions from gallery as it is disabled.
  13 passing (241ms)
  10 pending
Error received from starting extension host (kind: LocalWebWorker)
Canceled
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (http://localhost:9888/oss-dev/static/out/vs/base/common/lifecycle.js:210:34)
    at ExtensionHostManager._register (http://localhost:9888/oss-dev/static/out/vs/base/common/lifecycle.js:237:32)
    at http://localhost:9888/oss-dev/static/out/vs/workbench/services/extensions/common/extensionHostManager.js:110:22 [
  'Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!\n' +
    '    at DisposableStore.add ([http://localhost:9888/oss-dev/static/out/vs/base/common/lifecycle.js:210:34)\n'](http://localhost:9888/oss-dev/static/out/vs/base/common/lifecycle.js:210:34)/n') +
    '    at ExtensionHostManager._register ([http://localhost:9888/oss-dev/static/out/vs/base/common/lifecycle.js:237:32)\n'](http://localhost:9888/oss-dev/static/out/vs/base/common/lifecycle.js:237:32)/n') +
    '    at http://localhost:9888/oss-dev/static/out/vs/workbench/services/extensions/common/extensionHostManager.js:110:22'
]
```

**Comment by jrieken** [comment]
This doesn't reproduce locally, I assume what happened is failure of starting the web EH but some setup code was still running (on the disposed EH manager)
