### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:1 and sourceFile.scriptKind: 2, !entry: false

### ISSUE THREAD

**Issue by RacketyWater7** [microsoft/vscode#188447]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.1-rc

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:1 and sourceFile.scriptKind: 2, !entry: false
    at getDocumentRegistryEntry (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133137:11)
    at Object.releaseDocumentWithKey (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133234:19)
    at getOrCreateSourceFileByPath (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141912:30)
    at Object.getOrCreateSourceFile (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141896:14)
    at /private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141828:42
    at Object.getSourceFileWithCache [as getSourceFile] (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117906:24)
    at findSourceFileWorker (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120299:23)
    at findSourceFile (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120219:20)
    at /private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120168:22
    at getSourceFileFromReferenceWorker (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120152:69)
    at processSourceFile (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120166:5)
    at processRootFile (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119963:5)
    at /private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118718:41
    at forEach (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2325:22)
    at createProgram (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118718:5)
    at synchronizeHostData (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141852:15)
    at Object.getProgram (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141924:5)
    at InferredProject2.updateGraphWorker (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174484:41)
    at InferredProject2.updateGraph (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174336:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176726:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178344:12)
    at /private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178574:64
    at flatMap (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2573:17)
    at _ProjectService.applyChangesInOpenFiles (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178574:24)
    at updateOpen (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179754:29)
    at /private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182326:69
    at IpcIOSession.executeWithRequestId (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182318:14)
    at IpcIOSession.executeCommand (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182326:29)
    at IpcIOSession.onMessage (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182368:51)
    at process.<anonymous> (/private/var/folders/_q/821qbhhs50j79nwzfzk76wv80000gr/T/AppTranslocation/69A1A70D-A288-4B61-BE00-9A2757699CD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183948:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (Universal) (2dfb838f494f035099e999f0cd0eff5f1f488a30, 2023-05-26T05:24:15.292Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id f869c42c-b2a2-4540-9544-a660d8af56b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
simple-react-snippets|bur|1.2.7
gltf-vscode|ces|2.4.0
turbo-console-log|Cha|2.9.6
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|9.19.0
vscode-yarn|gam|2.1.0
fish|gio|0.0.4
copilot|Git|1.98.277
copilot-chat|Git|0.3.2023060801
copilot-labs|Git|0.14.884
vscode-pull-request-github|Git|0.66.2
gc-excelviewer|Gra|4.2.57
vscode-graphql-syntax|Gra|1.2.2
solidity|Jua|0.0.165
fish-ide|lun|0.4.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.26.0
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2023.10.1
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.30
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.302.0
vscode-typescript-next|ms-|5.2.20230720
vsliveshare|ms-|1.0.5877
vscode-react-native|msj|1.11.1
material-icon-theme|PKi|4.29.0
LiveServer|rit|5.7.9
yarn-spinner|Sec|2.2.119
markdown-preview-enhanced|shd|0.6.8
fish-vscode|sky|0.2.1
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
2i9eh265:30646982
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30792625
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30792099
synctok:30783813
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by mjbvz** [comment]
Closing as this is an old TS version. TS 5.1.6 fixed one of these crashes already
