### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'clone')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188645]
Found this in the [smoke test logs](https://artprodeus21.artifacts.visualstudio.com/A341001b6-62a6-4d7e-aa61-779aea3de100/a6d41577-0fa3-498e-af22-257312ff0545/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21vbmFjb3Rvb2xzL3Byb2plY3RJZC9hNmQ0MTU3Ny0wZmEzLTQ5OGUtYWYyMi0yNTczMTJmZjA1NDUvYnVpbGRJZC8yMjQ4MjgvYXJ0aWZhY3ROYW1lL2xvZ3MtbGludXgteDY0LTE1/content?format=zip&subPath=%2Fsmoke-tests-electron%2F13_suite_Task), I think this is opening a `task.json` file in the editor:

```
[2023-07-24T05:44:56.773Z] Playwright (Electron): window.on('console') [%c  ERR color: #f33 Cannot read properties of null (reading 'clone'): TypeError: Cannot read properties of null (reading 'clone')
    at u (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:106785)
    at g.updateTokensUntilLine (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:102140)
    at a.forceTokenization (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:114993)
    at c.forceTokenization (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:109581)
    at h (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:30550)
    at y (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:46932)
    at r.m (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:640:277)
    at r.typeWithInterceptors (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:641:241)
    at vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:643:1626
    at g.H (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:643:960)
    at g.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:643:1516)
    at vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:3009
    at m.O (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:4005)
    at m.N (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:2804)
    at m.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:2997)
    at Sn.Lb (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:726:8027)
    at Sn.trigger (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:726:7228)
    at T.runCommand (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:663:36483)
    at handler (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:663:2010)
    at k.handler (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:618:11336)
    at d.invokeFunction (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:622:326)
    at y.k (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1509:12357)
    at y.executeCommand (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1509:11945)
    at Object.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:726:17361)
    at P.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:663:37331)
    at r.value (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:702:52067)
    at u.w (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1902)
    at u.fire (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:2119)
    at r.value (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:596:26833)
    at u.w (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1902)
    at u.x (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1972)
    at u.fire (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:2188)
    at HTMLTextAreaElement.k (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:7712)
    at P.typeInEditor (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:627:27855)
    at eval (eval at evaluate (:197:30), <anonymous>:1:38)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)]

[2023-07-24T05:44:56.774Z] Playwright (Electron): window.on('console') [%c  ERR color: #f33 Cannot set state before setting previous state: Error: Cannot set state before setting previous state
    at r.setEndState (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:104422)
    at g.updateTokensUntilLine (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:102250)
    at a.forceTokenization (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:114993)
    at c.forceTokenization (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:109581)
    at h (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:30550)
    at y (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:46932)
    at r.m (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:640:277)
    at r.typeWithInterceptors (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:641:241)
    at vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:643:1626
    at g.H (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:643:960)
    at g.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:643:1516)
    at vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:3009
    at m.O (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:4005)
    at m.N (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:2804)
    at m.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:724:2997)
    at Sn.Lb (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:726:8027)
    at Sn.trigger (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:726:7228)
    at T.runCommand (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:663:36483)
    at handler (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:663:2010)
    at k.handler (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:618:11336)
    at d.invokeFunction (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:622:326)
    at y.k (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1509:12357)
    at y.executeCommand (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1509:11945)
    at Object.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:726:17361)
    at P.type (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:663:37331)
    at r.value (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:702:52067)
    at u.w (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1902)
    at u.fire (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:2119)
    at r.value (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:596:26833)
    at u.w (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1902)
    at u.x (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1972)
    at u.fire (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:2188)
    at HTMLTextAreaElement.k (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:69:7712)
    at P.typeInEditor (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:627:27855)
    at eval (eval at evaluate (:197:30), <anonymous>:1:38)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)]
```

![image](https://github.com/microsoft/vscode/assets/900690/7fe46616-5e4b-463d-86dd-51f5009a05cf)

**Comment by hediet** [comment]
Will look into this later today, I think this is important.
Please let me know if someone managed to reproduce this locally (so far, I didn't).

**Comment by bpasero** [comment]
No sorry, just found it looking through a failing smoke test log.

**Comment by bpasero** [comment]
I assume there is no verification possible?

**Comment by hediet** [comment]
I guess so
