### ISSUE TITLE
Task Quick Pick: icon - icon only

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188662]
```
1) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon only:
     Error: Timeout: get text content ' .monaco-editor[data-uri$="tasks.json"] .view-lines' after 20 seconds.
      at Code.poll (/mnt/vss/_work/1/s/test/automation/src/code.ts:273:11)
      at Code.waitForTextContent (/mnt/vss/_work/1/s/test/automation/src/code.ts:201:10)
      at Editor.waitForTypeInEditor (/mnt/vss/_work/1/s/test/automation/src/editor.ts:100:3)
      at Task.configureTask (/mnt/vss/_work/1/s/test/automation/src/task.ts:79:4)
      at Context.<anonymous> (src/areas/task/task-quick-pick.test.ts:44:5)
```

**Comment by hediet** [comment]
Related: #188645

**Comment by meganrogge** [comment]
The logs reveal that `task` is `null` here 🤔 

https://github.com/microsoft/vscode/blob/cb38b1b567db09624b65b2f883f407c0cfed7e14/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1359

```
2023-07-24 10:04:11.199 [error] Cannot read properties of null (reading 'clone'): TypeError: Cannot read properties of null (reading 'clone')
    at u (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:106785)
    at f.updateTokensUntilLine (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:102140)
    at a.forceTokenization (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:114993)
    at c.forceTokenization (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:613:109581)
    at h (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:30550)
    at y (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:46932)
    at r.m (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:640:277)
    at r.typeWithInterceptors (vscode-file://vscode-app/mnt/vss/_work/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench
```

**Comment by meganrogge** [comment]
from the trace, there's not ask here 

![page@5f04c88b54cc783565f0d3e60929fdd8-1690193154 055301](https://github.com/microsoft/vscode/assets/29464607/f36f8cf7-07d1-409d-b74e-1ede7e9200ce)

**Comment by meganrogge** [comment]
so the typing in editor part is failing occasionally - don't think this is related to any task changes.

**Comment by meganrogge** [comment]
@hediet I think this can be closed as a duplicate of https://github.com/microsoft/vscode/issues/188645, reopen if i'm wrong
