### ISSUE TITLE
Tests: Error: Throttler is disposed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188929]
Seeing a lot of these errors in unit tests:

```
SettingsSync - Auto
    ✔ when settings file does not exist
    ✔ when settings file is empty and remote has no changes
    ✔ when settings file is empty and remote has changes
    ✔ when settings file is created after first sync
    ✔ sync for first time to the server
    ✔ do not sync machine settings
    ✔ do not sync machine settings when spread across file
[15902:0726/165037.294649:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.294712:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
    ✔ do not sync machine settings when spread across file - 2
    ✔ sync when all settings are machine settings
    ✔ sync when all settings are machine settings with trailing comma
[15902:0726/165037.302051:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.302101:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
    ✔ local change event is triggered when settings are changed
    ✔ do not sync ignored settings
    ✔ do not sync ignored and machine settings
[15902:0726/165037.309787:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.309836:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.309859:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.309876:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
    ✔ sync throws invalid content error
    ✔ sync throws invalid content error - content is an array
[15902:0726/165037.317046:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.317106:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
    ✔ sync when there are conflicts
[15902:0726/165037.330117:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.330190:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.330211:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.330228:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
    ✔ sync profile settings

  SettingsSync - Manual
    ✔ do not sync ignored settings

  SnippetsSync
    ✔ when snippets does not exist
    ✔ when snippet is created after first sync
    ✔ first time sync - outgoing to server (no snippets)
[15902:0726/165037.340539:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.340587:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.340606:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.340623:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
    ✔ first time sync - incoming from server (no snippets)
    ✔ first time sync when snippets exists
[15902:0726/165037.355693:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.355751:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.355874:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
[15902:0726/165037.355905:INFO:CONSOLE(150)] "Uncaught (in promise) Error: Throttler is disposed", source: file:///Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js (150)
```

**Comment by liuchintao** [comment]
I meet similar issue.

When I close browser, code-server print these in terminal

```log
[15:16:09] [127.0.0.1][cec36582][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] Error: Throttler is disposed
    at $ng.queue (/home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:19892:23)
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20076:48
    at /home/liujt/workspace/repos/microsoft/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:20030:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[15:16:09] [127.0.0.1][7b14e3eb][ExtensionHostConnection] <419476> Extension Host Process exited with code: 0, signal: null.
```
