### ISSUE TITLE
TS Server fatal error:  UNC host 'wsl.localhost' access is not allowed

### ISSUE THREAD

**Issue by zeru06** [microsoft/vscode#188919]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.6

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host 'wsl.localhost' access is not allowed
    at Object.watchFile (node:fs:2363:14)
    at fsWatchFileWorker (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8562:11)
    at c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8209:15
    at createSingleWatcherPerName (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7730:16)
    at pollingWatchFile (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8204:12)
    at watchFile2 (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8039:16)
    at watchMissingFileSystemEntry (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8297:14)
    at fsWatchHandlingExistenceOnHost (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8228:72)
    at c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8218:15
    at createSingleWatcherPerName (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7730:16)
    at fsWatch (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8213:12)
    at Object.watchFile2 [as watchFile] (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8064:16)
    at watchFile (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117630:67)
    at Object.watchFile (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117649:282)
    at c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176954:183
    at _ProjectService.forEachConfigFileLocation (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177004:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176947:10)
    at InferredProject2.addRoot (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:175207:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176745:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178368:12)
    at c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178598:64
    at flatMap (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2573:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178598:24)
    at updateOpen (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179778:29)
    at c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182351:69
    at IpcIOSession.executeWithRequestId (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182343:14)
    at IpcIOSession.executeCommand (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182351:29)
    at IpcIOSession.onMessage (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182393:51)
    at process.<anonymous> (c:\Users\Aklilu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183973:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.78GB free)|
|Process Argv|--crash-reporter-id f296961f-718b-4d61-b6e2-4b3929a949da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
vsc-material-theme|Equ|33.8.0
code-runner|for|0.12.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.30
remote-wsl|ms-|0.80.2
color-highlight|nau|2.5.0
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by bpasero** [comment]
Beginning with VS Code `1.78.1` accessing any UNC path (those that begin with `\\`) on Windows is blocked to mitigate a security risk that is further explained in this [Security Advisory](https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr).

Please refer to https://aka.ms/vscode-windows-unc for more information how to make your specific UNC path work again.
