### ISSUE TITLE
`WebviewEditor` ends up in `safeStringify`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188981]
This is quite bizarre, I am tracing the following stacktrace:

```
[25520:0726/224556.191733:INFO:CONSOLE(244)] "%c  ERR color: #f33 Method not found: toJSON: CodeExpectedError: Method not found: toJSON
    at Object.call (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:852:27)
    at ChannelServer.onPromise (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:287:35)
    at ChannelServer.onRawMessage (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:266:33)
    at UniqueContainer.value (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:217:73)
    at Emitter._deliver (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:833:26)
    at Emitter._deliverQueue (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:844:22)
    at Emitter.fire (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:867:22)
    at UniqueContainer.value (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:98:93)
    at Emitter._deliver (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:833:26)
    at Emitter.fire (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:862:22)
    at UniqueContainer.value (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:117:106)
    at Emitter._deliver (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:833:26)
    at Emitter.fire (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:862:22)
    at fn (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:413:44)
    at IpcMainImpl.wrappedListener (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/electron-main/ipcMain.js:25:21)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81053)
```

Which shows up on the terminal (reproduces running out of sources):
* install Luna Paint extension
* create a new untitled Luna Paint image
* 🐛 exception shows up

Further logging reveals that someone is trying to call the method `toJSON` on the `INativeHostService` which is proxied from the renderer and implemented in the main process.

Further debugging reveals that we actually trying to `safeStringify` an entire `WebviewEditor`:

![image](https://github.com/microsoft/vscode/assets/900690/47ece4f2-22e1-41ee-8942-c76540ee64dd)

Unfortunately, that is where I was not able to dig in further. I got the breakpoint hit by adding the following log statement:

```ts
if (propKey === 'toJSON') {
	console.log(`Call to ${String(propKey)} with ${args.length} arguments:`, args);
}
```

into here (right where the proxy method is implemented):

https://github.com/microsoft/vscode/blob/e3f25bfcb0cb714ec65232bc6f6d62e3413bdba1/src/vs/base/parts/ipc/common/ipc.ts#L1168

And then adding a breakpoint to the console log location.

Any clues?

//cc @Tyriar

**Comment by Tyriar** [comment]
I can't repro on Windows, I do this this which I guess is expected?

```
  ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'untitled:/c%3A/Github/microsoft/vscode/NewImage-1.png'
    at o.j (workbench.desktop.main.js:627:11395)
    at async o.W (workbench.desktop.main.js:627:22002)
    at async workbench.desktop.main.js:627:21897
```

**Comment by mjbvz** [comment]
I see this when running `new image` without opening a workspace
