### ISSUE TITLE
Smoke Test Failure

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#189019]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=225333
Changes: https://github.com/Microsoft/vscode/compare/9409462...525f0a6

```
VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies opened editors are restored:
     electronApplication.waitForEvent: Electron application closed
      at /mnt/vss/_work/1/s/test/automation/src/playwrightElectron.ts:41:47
      at measureAndLog (/mnt/vss/_work/1/s/test/automation/src/logger.ts:52:15)
      at launchElectron (/mnt/vss/_work/1/s/test/automation/src/playwrightElectron.ts:41:31)
      at launch (/mnt/vss/_work/1/s/test/automation/src/playwrightElectron.ts:20:38)
      at measureAndLog (/mnt/vss/_work/1/s/test/automation/src/logger.ts:52:9)
      at launch (/mnt/vss/_work/1/s/test/automation/src/code.ts:85:39)
      at Application.startApplication (/mnt/vss/_work/1/s/test/automation/src/application.ts:107:29)
      at Application._start (/mnt/vss/_work/1/s/test/automation/src/application.ts:82:16)
      at /mnt/vss/_work/1/s/test/automation/src/application.ts:74:4
      at measureAndLog (/mnt/vss/_work/1/s/test/automation/src/logger.ts:52:9)
      at Application.restart (/mnt/vss/_work/1/s/test/automation/src/application.ts:72:3)
      at Context.<anonymous> (src/areas/workbench/data-loss.test.ts:37:4)


```

**Comment by bpasero** [comment]
[b655864a-1637-45b2-8bad-f8a893a29e22.dmp.zip](https://github.com/microsoft/vscode/files/12180488/b655864a-1637-45b2-8bad-f8a893a29e22.dmp.zip)

**Comment by deepak1556** [comment]
Return of https://github.com/microsoft/vscode/issues/153181, same trace as https://github.com/microsoft/vscode/issues/153181#issuecomment-1175200681.

**Comment by deepak1556** [comment]
Changed milestone since this requires reacting to new logs from CI which might not be constrained to a single milestone.

**Comment by deepak1556** [comment]
We haven't seen reports since Electron 25 update, closing it optimistically. The debug logs are still in place, so we will have better insights next time it happens.
