### ISSUE TITLE
Failed to start Jupyter Kernel under remote tunnel: Cannot find module './351.node.js'

### ISSUE THREAD

**Issue by ischurov** [microsoft/vscode#189926]
Type: <b>Bug</b>

I am working with Python through Remote Tunnels in a remote Nix environment, i.e. I am logging in to remote machine, launching `nix develop` there, then launching `code --tunnel` (Code CLI was previously downloaded and installed manually, not through nix) and connecting to that tunnel from my local machine. Until recent update (1.81.0), everything worked fine. Today I discovered that I cannot run Jupyter kernels anymore. When I select Jupyter kernel (Python Environment → Select curent nix's Python interpreter), I get the following error message:

Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'

The relevant parts of Jupyter logs:

```
14:21:32.698 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0e4fabc1cd06fb8fff1d929d69412af48fee71891a739437be12672560b828fdd./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10.-m#ipykernel_launcher  (Python Path: /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10, Unknown, 3.10.12) for '~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb' (disableUI=false)
14:21:32.736 [info] Process Execution: /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:21:32.737 [error] Kernel Launcher. launch, Class name = sv, completed in 37ms, has a falsy return value, Arg 1: ".jvsc74a57bd0e4fabc1cd06fb8fff1d929d69412af48fee71891a739437be12672560b828fdd./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb", Arg 4: "~/tcm10/frustrations-eda", Arg 5: "" Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.o._load (~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/workbench/api/node/extensionHostProcess.js:131:28084)
    at Function.f._load (~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/workbench/api/node/extensionHostProcess.js:131:25418)
    at Function.C._load (~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/workbench/api/node/extensionHostProcess.js:95:19511)
    at Module.apply (node:internal/modules/cjs/loader:1028:19)
    at Module.require (~/.vscode-server/extensions/github.copilot-1.101.317/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.__webpack_require__.f.require (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1563875)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1563219
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1563179)
    at Function.findNextFreePort (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:104972)
    at sv.getConnectionPorts (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:105284) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js',
    '~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js',
    '~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js',
    '~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js'
  ]
}
14:21:32.738 [error] Failed to connect raw kernel session: Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:21:32.739 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:21:32.739 [warn] Kernel Error, context = start Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:21:32.783 [info] Process Execution: /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:21:33.251 [info] Dispose Kernel '~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb' associated with '~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb'
14:21:33.251 [error] Error in execution Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:21:33.252 [error] Error in execution (get message for cell) Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:21:33.305 [info] End cell 0 execution @ undefined, started @ undefined, elapsed time = 0s
14:30:54.256 [info] Handle Execution of Cells 0 for ~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb
14:30:54.262 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0e4fabc1cd06fb8fff1d929d69412af48fee71891a739437be12672560b828fdd./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10.-m#ipykernel_launcher  (Python Path: /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10, Unknown, 3.10.12) for '~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb' (disableUI=false)
14:30:54.266 [error] Kernel Launcher. launch, Class name = sv, completed in 2ms, has a falsy return value, Arg 1: ".jvsc74a57bd0e4fabc1cd06fb8fff1d929d69412af48fee71891a739437be12672560b828fdd./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10./nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb", Arg 4: "~/tcm10/frustrations-eda", Arg 5: "" Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.o._load (~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/workbench/api/node/extensionHostProcess.js:131:28084)
    at Function.f._load (~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/workbench/api/node/extensionHostProcess.js:131:25418)
    at Function.C._load (~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/workbench/api/node/extensionHostProcess.js:95:19511)
    at Module.apply (node:internal/modules/cjs/loader:1028:19)
    at Module.require (~/.vscode-server/extensions/github.copilot-1.101.317/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.__webpack_require__.f.require (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1563875)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1563219
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1563179)
    at Function.findNextFreePort (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:104972)
    at sv.getConnectionPorts (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:105284) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js',
    '~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js',
    '~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js',
    '~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js'
  ]
}
14:30:54.266 [error] Failed to connect raw kernel session: Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:30:54.267 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:30:54.267 [warn] Kernel Error, context = start Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:30:54.398 [warn] Failed to get activated env vars for /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10 in 134ms
14:30:54.448 [info] Process Execution: /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:30:54.457 [warn] Failed to get activated env vars for /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10 in 189ms
14:30:54.502 [info] Process Execution: /nix/store/nvfqgjlhgdcqnrvndl91s08511xcjkrk-python3-3.10.12-env/bin/python3.10 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:30:54.794 [info] Dispose Kernel '~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb' associated with '~/tcm10/frustrations-eda/vmc_vs_lbfgs_2023_08_04.ipynb'
14:30:54.795 [error] Error in execution Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:30:54.795 [error] Error in execution (get message for cell) Error: Failed to start the Kernel 'Python 3.10.12'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
    > at new ur (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1678847)
    > originalException = Error: Cannot find module './351.node.js'
Require stack:
- ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/vs/loader.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-amd.js
- ~/.vscode/cli/servers/Stable-6445d93c81ebe42c4cbd7a60712e0b17d9463e97/server/out/bootstrap-fork.js
14:30:54.859 [info] End cell 0 execution @ undefined, started @ undefined, elapsed time = 0s
```

I believe it may be an issue with my nix setup, as it is not reproduced when I use SSH Remote instead of Tunnel, do not use nix and use conda environment. At the same time, error message suggests that it is related to some parts of vscode.

Extension version: 2023.7.1002162226
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin x64 22.1.0
Modes:
Remote OS version: Linux x64 4.15.0-213-generic
Remote OS version: Linux x64 4.15.0-213-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 6268c79f-ba03-42d2-bf4d-cd2dfec6306c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|frustrations-eda|
|OS|Linux x64 4.15.0-213-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (16 x 1785)|
|Memory (System)|62.86GB (59.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: tcm-tunnel|
|OS|Linux x64 4.15.0-213-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (16 x 1200)|
|Memory (System)|125.86GB (123.38GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by ischurov** [comment]
I managed to solve the issue by removing `.vscode` and `.vscode-server` on the remote machine and creating a new clean tunnel. So, we can probably close it now.
