### ISSUE TITLE
Terminal often fails to load in OSS

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#189969]
1. Be on Windows and debug OSS
2. Reload the window a few times until the terminal doesn't load (happens the majority of the time for me)
3. Notice the following error:

```
ERR Failed to execute 'invoke' on 'CreateURLCallback': The provided callback is no longer runnable.: Error: Failed to execute 'invoke' on 'CreateURLCallback': The provided callback is no longer runnable.
    at BrowserScriptLoader.load (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:642:37)
    at OnlyOnceScriptLoader.load (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:581:23)
    at loadNextPath (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:1619:25)
    at ModuleManager._loadModule (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:1631:4)
    at ModuleManager._resolve (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:1714:11)
    at ModuleManager.defineModule (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:1368:9)
    at ModuleManager._relativeRequire (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:1402:9)
    at result (file:///C:/Users/conno/Github/vscode/src/vs/loader.js:1573:17)
    at vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/amdX.js:182:65
    at new Promise (<anonymous>)
    at importAMDNodeModule (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/amdX.js:182:26)
    at vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:503:72
    at vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/base/common/async.js:1168:27
    at new Promise (<anonymous>)
    at Object.withAsyncBody (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/base/common/async.js:1166:20)
    at TerminalInstance.getXtermConstructor (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:502:49)
    at TerminalInstance._createXterm (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:515:53)
    at new TerminalInstance (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:298:44)
    at InstantiationService._createInstance (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/platform/instantiation/common/instantiationService.js:91:28)
    at InstantiationService.createInstance (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/platform/instantiation/common/instantiationService.js:62:31)
    at TerminalInstanceService.createInstance (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstanceService.js:39:57)
    at TerminalGroup.addInstance (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalGroup.js:272:58)
    at new TerminalGroup (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalGroup.js:256:22)
    at InstantiationService._createInstance (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/platform/instantiation/common/instantiationService.js:91:28)
    at InstantiationService.createInstance (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/platform/instantiation/common/instantiationService.js:62:31)
    at TerminalGroupService.createGroup (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalGroupService.js:117:54)
    at TerminalService._createTerminal (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:948:58)
    at TerminalService.createTerminal (vscode-file://vscode-app/c:/Users/conno/Github/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:873:25)
```

**Comment by Tyriar** [comment]
Looks like a problem with the new loader

**Comment by jrieken** [comment]
What new loader?

**Comment by jrieken** [comment]
@connor4312 back to you -> https://github.com/microsoft/vscode/issues/164256

**Comment by connor4312** [comment]
😱 well at least now I have a semi-consistent repro, though with my luck it'll have fixed itself today
