### ISSUE TITLE
ssh to a remote linux failed

### ISSUE THREAD

**Issue by chengchengXu** [microsoft/vscode#190144]
Type: <b>Bug</b>

Hi,
Thank you for reading my issue.
I found after clicking to connect a remote linux, only 'Disconnected from vscode-remote' was what I got on the bottom Status Bar.
I wander whether my remote linux server is EulerOS.
I picked Error message in Developer Tools:

workbench.desktop.main.js:627  INFO Invoking resolveAuthority(ssh-remote)...
workbench.desktop.main.js:627  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
workbench.desktop.main.js:627   ERR Extension 'huaweicloud.vscode-codebot' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:627   ERR Extension 'ms-python.python' wants API proposal 'notebookEditor' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:627   ERR Extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:627   ERR Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:627  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][430ms] invoking...
workbench.desktop.main.js:627   ERR [LocalProcess0][resolveAuthority(ssh-remote,1)][439ms] returned an error Object
workbench.desktop.main.js:627   ERR resolveAuthority(ssh-remote) returned an error after 440 ms CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR Error received from starting extension host (kind: Remote)
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error:
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR [remote-connection][attempt 4] An error occurred in initial connection! Will retry... Error:
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR [remote-connection][attempt 5]  An error occurred in initial connection! It will be treated as a permanent error. Error:
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR Cannot register remote filesystem provider. Error while fetching remote environment. No remote extension installed to resolve ssh-remote.
workbench.desktop.main.js:627   ERR Error: Remote profiles service not available in the current window
    at i.getRemoteProfile (workbench.desktop.main.js:2292:45834)
    at async u.y (workbench.desktop.main.js:2292:47660)
    at async u.getInstalled (workbench.desktop.main.js:1352:9274)
    at async Promise.all (index 1)
    at async s.getInstalled (workbench.desktop.main.js:2615:95276)
    at async T.k (workbench.desktop.main.js:2615:92746)
workbench.desktop.main.js:627   ERR No remote extension installed to resolve ssh-remote.: CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:20056)
    at async G.nb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:19327)
    at async G.Lb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2617:11191)
    at async G.gb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR Remote profiles service not available in the current window: Error: Remote profiles service not available in the current window
    at i.getRemoteProfile (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:45834)
    at async u.y (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:47660)
    at async u.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1352:9274)
    at async Promise.all (index 1)
    at async s.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2615:95276)
workbench.desktop.main.js:627   ERR Remote profiles service not available in the current window: Error: Remote profiles service not available in the current window
    at i.getRemoteProfile (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:45834)
    at async u.y (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:47660)
    at async u.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1352:9274)
    at async Promise.all (index 1)
    at async s.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2615:95276)
    at async ai.db (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1835:55026)
workbench.desktop.main.js:627   ERR Remote profiles service not available in the current window: Error: Remote profiles service not available in the current window
    at i.getRemoteProfile (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:45834)
    at async u.y (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:47660)
    at async u.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1352:9274)
    at async Promise.all (index 1)
    at async s.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2615:95276)
    at async qr.k (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1362:2758)
    at async qr.getExtensions (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1362:2468)
workbench.desktop.main.js:627   ERR No remote extension installed to resolve ssh-remote.: CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:20056)
    at async G.nb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:19327)
    at async G.Lb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2617:11191)
    at async G.gb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:129 [Extension Host] Initializing tunnel extension
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR Remote profiles service not available in the current window: Error: Remote profiles service not available in the current window
    at i.getRemoteProfile (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:45834)
    at async u.y (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:47660)
    at async u.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1352:9274)
    at async Promise.all (index 1)
    at async s.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2615:95276)
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:627   ERR CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (workbench.desktop.main.js:2616:20056)
    at async G.nb (workbench.desktop.main.js:2616:19327)
    at async G.Lb (workbench.desktop.main.js:2617:11191)
    at async G.gb (workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:614 [vscodeintellicode]: Couldn't find message for key license.prompt.
$ @ workbench.desktop.main.js:614
workbench.desktop.main.js:614 [vscodeintellicode]: Couldn't find message for key license.seeTerms.
$ @ workbench.desktop.main.js:614
workbench.desktop.main.js:614 [vscodeintellicode]: Couldn't find message for key license.terms.
$ @ workbench.desktop.main.js:614
workbench.desktop.main.js:614 [vscodeintellicode]: Couldn't find message for key license.accept.
$ @ workbench.desktop.main.js:614
workbench.desktop.main.js:614 [vscodeintellicode]: Couldn't find message for key license.decline.
$ @ workbench.desktop.main.js:614
workbench.desktop.main.js:627   ERR No remote extension installed to resolve ssh-remote.: CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:20056)
    at async G.nb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:19327)
    at async G.Lb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2617:11191)
    at async G.gb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:129 [Extension Host]% Object
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:129 [Extension Host]% Object
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:627   ERR No remote extension installed to resolve ssh-remote.: CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at G.ob (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:20056)
    at async G.nb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:19327)
    at async G.Lb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2617:11191)
    at async G.gb (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:17108)
workbench.desktop.main.js:129 [Extension Host]% Object
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:129 [Extension Host]% Object
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:129 [Extension Host]% Object
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:129 [Extension Host]% Object
p @ workbench.desktop.main.js:129
workbench.desktop.main.js:129 [Extension Host]% {message: 'spawn docker ENOENT', name: 'Error', stack: 'Error: spawn docker ENOENT\n    at Process.ChildPro…ections (node:internal/process/task_queues:83:21)', code: 'ENOENT'}code: "ENOENT"message: "spawn docker ENOENT"name: "Error"stack: "Error: spawn docker ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)\n    at onErrorNT (node:internal/child_process:478:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"[[Prototype]]: Object
p @ workbench.desktop.main.js:129
$logExtensionHostMessage @ workbench.desktop.main.js:1533
N @ workbench.desktop.main.js:1533
M @ workbench.desktop.main.js:1533
H @ workbench.desktop.main.js:1533
G @ workbench.desktop.main.js:1533
(anonymous) @ workbench.desktop.main.js:1533
w @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:596
ne.onmessage @ workbench.desktop.main.js:1629
workbench.desktop.main.js:129 [Extension Host]% {message: 'spawn docker ENOENT', name: 'Error', stack: 'Error: spawn docker ENOENT\n    at Process.ChildPro…ections (node:internal/process/task_queues:83:21)', code: 'ENOENT'}code: "ENOENT"message: "spawn docker ENOENT"name: "Error"stack: "Error: spawn docker ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)\n    at onErrorNT (node:internal/child_process:478:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"[[Prototype]]: Object
p @ workbench.desktop.main.js:129
$logExtensionHostMessage @ workbench.desktop.main.js:1533
N @ workbench.desktop.main.js:1533
M @ workbench.desktop.main.js:1533
H @ workbench.desktop.main.js:1533
G @ workbench.desktop.main.js:1533
(anonymous) @ workbench.desktop.main.js:1533
w @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:596
ne.onmessage @ workbench.desktop.main.js:1629
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
workbench.desktop.main.js:627   ERR Remote profiles service not available in the current window: Error: Remote profiles service not available in the current window
    at i.getRemoteProfile (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:45834)
    at async u.y (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:47660)
    at async u.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1352:9274)
    at async Promise.all (index 1)
    at async s.getInstalled (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2615:95276)
    at async qr.k (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1362:2758)
    at async qr.getExtensions (vscode-file://vscode-app/d:/SOFTWARE/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1362:2468)

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Connection to 'vscode-remote' could not be established  No remote extension installed to resolve ssh-remote.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (9.61GB free)|
|Process Argv|--enable-proposed-api HuaweiCloud.vscode-codebot|
|Screen Reader|no|
|VM|0%|

Connection to 'vscode-remote' could not be established  No remote extension installed to resolve ssh-remote.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by chrmarti** [comment]
Make sure you are running the latest versions of VS Code and Remote-SSH.
