### ISSUE TITLE
Permission Issues when use User Account

### ISSUE THREAD

**Issue by ysd375** [microsoft/vscode#190555]
[16:31:33.320] Log Level: 2
[16:31:33.331] SSH Resolver called for "ssh-remote+192.168.0.130", attempt 1
[16:31:33.331] "remote.SSH.useLocalServer": false
[16:31:33.332] "remote.SSH.showLoginTerminal": false
[16:31:33.332] "remote.SSH.remotePlatform": {}
[16:31:33.332] "remote.SSH.path": undefined
[16:31:33.332] "remote.SSH.configFile": undefined
[16:31:33.332] "remote.SSH.useFlock": true
[16:31:33.332] "remote.SSH.lockfilesInTmp": false
[16:31:33.332] "remote.SSH.localServerDownload": auto
[16:31:33.332] "remote.SSH.remoteServerListenOnSocket": false
[16:31:33.332] "remote.SSH.showLoginTerminal": false
[16:31:33.333] "remote.SSH.defaultExtensions": []
[16:31:33.333] "remote.SSH.loglevel": 2
[16:31:33.333] "remote.SSH.enableDynamicForwarding": true
[16:31:33.333] "remote.SSH.enableRemoteCommand": false
[16:31:33.333] "remote.SSH.serverPickPortsFromRange": {}
[16:31:33.333] "remote.SSH.serverInstallPath": {}
[16:31:33.337] VS Code version: 1.81.1
[16:31:33.337] Remote-SSH version: remote-ssh@0.102.0
[16:31:33.337] win32 x64
[16:31:33.338] SSH Resolver called for host: 192.168.0.130
[16:31:33.338] Setting up SSH remote "192.168.0.130"
[16:31:33.342] Using commit id "6c3e3dba23e8fadc360aed75ce363ba185c49794" and quality "stable" for server
[16:31:33.345] Install and start server if needed
[16:31:45.130] Checking ssh with "C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe -V"
[16:31:45.133] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe ENOENT
[16:31:45.133] Checking ssh with "C:\Program Files\Python310\Scripts\ssh.exe -V"
[16:31:45.134] Got error from ssh: spawn C:\Program Files\Python310\Scripts\ssh.exe ENOENT
[16:31:45.135] Checking ssh with "C:\Program Files\Python310\ssh.exe -V"
[16:31:45.136] Got error from ssh: spawn C:\Program Files\Python310\ssh.exe ENOENT
[16:31:45.136] Checking ssh with "C:\Program Files\Python310\Lib\ssh.exe -V"
[16:31:45.137] Got error from ssh: spawn C:\Program Files\Python310\Lib\ssh.exe ENOENT
[16:31:45.137] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\ssh.exe -V"
[16:31:45.138] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\ssh.exe ENOENT
[16:31:45.138] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp\ssh.exe -V"
[16:31:45.139] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp\ssh.exe ENOENT
[16:31:45.139] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[16:31:45.140] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[16:31:45.140] Checking ssh with "C:\Windows\ssh.exe -V"
[16:31:45.141] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[16:31:45.141] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[16:31:45.142] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[16:31:45.142] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[16:31:45.144] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[16:31:45.144] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[16:31:45.185] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[16:31:45.190] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 51861 "192.168.0.130" bash
[16:31:45.192] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:31:45.639] > Bad permissions. Try removing permissions for user: frank-ibicom\\fyang (S-1-5-21-1410555023-2865039690-801846011-1001) on file C:/Users/User/.ssh/config.
> Bad owner or permissions on C:\\Users\\User/.ssh/config
> 프로세스에서 없는 파이프에 쓰려고 했습니다.
> ]0;C:\WINDOWS\System32\cmd.exe
[16:31:45.640] Got some output, clearing connection timeout
[16:31:46.900] "install" terminal command done
[16:31:46.900] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[16:31:46.901] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[16:31:46.901] Failed to parse remote port from server output
[16:31:46.902] Resolver error: Error: 
	at m.Create (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584145)
	at t.handleInstallOutput (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:582705)
	at t.tryInstall (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[16:31:46.907] ------

**Comment by roblourens** [comment]
> Bad permissions. Try removing permissions for user: frank-ibicom\fyang (S-1-5-21-1410555023-2865039690-801846011-1001) on file C:/Users/User/.ssh/config.

This is just an error coming from ssh
