### ISSUE TITLE
When building VSCode from source code on Windows10 32bit, something get wrong

### ISSUE THREAD

**Issue by Artorialover** [microsoft/vscode#190551]
Hi, i am building VSCode from the source code.
...............................................
OS: Win10 32bit 4GB RAM
Python: 3.10.2  32bit
NodeJS: 16.17.0  32bit
Source code version: tag 1.77.3
vs: 2017
...............................................
Step 1. i follow the official document.: git clone and execute 'yarn', and after sometime everything is success
Step 2. when i want to run ,execute " \scripts\code.bat" ,there are 2 issues:
First issue:
~~~
C:\Users\Administrator\Desktop\VSCode\vscode-1.77.3\node_modules\gulp-atom-electron\src\win32.js:23
    throw `There is no Windows 10 SDK installed at ${windowsSDKDir}.`;
    ^
There is no Windows 10 SDK installed at C:\Program Files (x86)\Windows Kits\10\bin\.
~~~
Second issue:
~~~
PS C:\Users\Administrator\Desktop\VSCode\vscode-1.77.3> .\scripts\code.bat
yarn run v1.22.19
$ node build/lib/electron
Done in 0.42s.
yarn run v1.22.19
$ node --max_old_space_size=4095 ./node_modules/gulp/bin/gulp.js compile

<--- Last few GCs --->

[1320:00D4C798]     1246 ms: Scavenge 9.9 (14.1) -> 9.6 (14.6) MB, 0.8 / 0.0 ms  (average mu = 0.986, current mu = 0.986) allocation failure
[1320:00D4C798]     1385 ms: Mark-sweep 25.6 (30.1) -> 25.2 (30.4) MB, 13.7 / 0.0 ms  (average mu = 0.971, current mu = 0.946) allocation failure GC in old space requestedpace requested


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 01B8A38F v8::internal::Heap::AllocateExternalBackingStore+1551
error Command failed with exit code 134.
~~~
Question 1------->As well as i know，Windows 32bit only support 4GB RAM, how can i solve the problem?

Question 2------->I try to build again on Win10 64bit , use "yarn gulp vscode-win32-ia32"，and everything is ok. But the release version cannot work on Win10 32bit. 
~~~
Error: \\?\D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\node_modules.asar.unpacked\@vscode\policy-watcher\build\Release\vscode-policy-watcher.node is not a valid Win32 application.
\\?\D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\node_modules.asar.unpacked\@vscode\policy-watcher\build\Release\vscode-policy-watcher.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\node_modules.asar\bindings\bindings.js:112:48)
    at Object.<anonymous> (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\node_modules.asar\@vscode\policy-watcher\index.js:6:44)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at nodeRequire2 (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1537:20)
    at NodeScriptLoader.load (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1364:31)
    at OnlyOnceScriptLoader.load (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1148:30)
    at loadNextPath (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:2046:34)
    at Object.errorback (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:2054:17)
    at OnlyOnceScriptLoader.triggerErrorback (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1161:32)
    at D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1148:114
    at NodeScriptLoader.load (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1366:15)
    at OnlyOnceScriptLoader.load (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1148:30)
    at loadNextPath (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:2046:34)
    at ModuleManager._loadModule (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:2058:11)
    at ModuleManager._resolve (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:2127:20)
    at ModuleManager.defineModule (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1836:16)
    at DefineFunc (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:2215:25)
    at localDefineFunc (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1405:37)
    at Object.<anonymous> (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\vs\code\electron-main\main.js:32962:1)
    at Object.<anonymous> (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\vs\code\electron-main\main.js:54156:4)
    at NodeScriptLoader._createAndEvalScript (D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1408:15)
    at D:\VSCode\vscode-1.77.3\VSCode-win32-ia32\resources\app\out\main.js:1390:35
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  code: 'ERR_DLOPEN_FAILED',
  phase: 'loading',
  moduleId: '@vscode/policy-watcher',
  neededBy: [ 'vs/platform/policy/node/nativePolicyService' ]
}
Here are the modules that depend on it:
[ 'vs/platform/policy/node/nativePolicyService' ]
[6740:0817/152821.175:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
~~~
In addition, i found VSCode 1.77.3 has Win32-ia32 version [Link is Here](https://update.code.visualstudio.com/1.77.3/win32-archive/stable)，Can you tell me how to build a VSCode-win32-ia32 version on Win10 x64 platform?
Thanks

**Comment by Artorialover** [comment]
solved. Set npm_arch_config=ia32
