### ISSUE TITLE
fix: JS/TS Language Service Has Crashed 5 times in the last 5 Minutes

### ISSUE THREAD

**Issue by petermetz** [microsoft/vscode#190527]
Type: <b>Bug</b>

No idea. I just got a pop-up while working on some PRs via the GH PR extension.

It said that the JS/TS extension has crashed 5+ times in the last 5 minutes and that I should probably report this as an issue.

## Screenshot of the pop-up

![Screenshot 2023-08-15 151551](https://github.com/microsoft/vscode/assets/1583231/54245bf0-351c-4e34-8c7e-dfff6d8dcbc9)

## Output of Extension Host with some stack traces that may or may not be related. (The Typescript output shows no stack traces)

```log
2023-08-14 11:19:31.488 [info] Extension host agent started.
2023-08-14 11:19:31.815 [info] [127.0.0.1][87aac152][ManagementConnection] New connection established.
2023-08-14 11:19:32.484 [info] [127.0.0.1][ecf8ecb5][ExtensionHostConnection] New connection established.
2023-08-14 11:19:32.488 [info] [127.0.0.1][ecf8ecb5][ExtensionHostConnection] <425> Launched Extension Host Process.
2023-08-14 14:19:38.133 [warning] No ptyHost heartbeat after 6 seconds
2023-08-15 08:32:38.944 [info] [127.0.0.1][ecf8ecb5][ExtensionHostConnection] The client has reconnected.
2023-08-15 08:32:39.234 [info] [127.0.0.1][87aac152][ManagementConnection] The client has reconnected.
2023-08-15 14:30:27.828 [info] Getting Manifest... ms-azuretools.vscode-docker
2023-08-15 14:30:27.879 [info] Installing extension: ms-azuretools.vscode-docker
2023-08-15 14:30:28.345 [warning] Extension signature verification failed with error 'ENOENT': ms-azuretools.vscode-docker
2023-08-15 14:30:28.432 [info] Extracted extension to file:///home/peter/.vscode-server/extensions/ms-azuretools.vscode-docker-1.26.0: ms-azuretools.vscode-docker
2023-08-15 14:30:28.440 [info] Renamed to /home/peter/.vscode-server/extensions/ms-azuretools.vscode-docker-1.26.0
2023-08-15 14:30:28.444 [info] Extracting extension completed. ms-azuretools.vscode-docker
2023-08-15 14:30:28.454 [info] Extension installed successfully: ms-azuretools.vscode-docker
2023-08-15 14:36:55.771 [info] [127.0.0.1][5321c2d9][ManagementConnection] New connection established.
2023-08-15 14:36:56.072 [info] [127.0.0.1][f85ddad1][ExtensionHostConnection] New connection established.
2023-08-15 14:36:56.076 [info] [127.0.0.1][f85ddad1][ExtensionHostConnection] <4452> Launched Extension Host Process.
2023-08-15 14:37:04.872 [info] [127.0.0.1][5321c2d9][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-08-15 14:37:04.873 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 14:37:04.874 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 14:37:04.874 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 14:37:04.919 [info] [127.0.0.1][f85ddad1][ExtensionHostConnection] <4452> Extension Host Process exited with code: 0, signal: null.
2023-08-15 14:40:45.705 [info] [127.0.0.1][510c4c06][ManagementConnection] New connection established.
2023-08-15 14:40:46.132 [info] [127.0.0.1][d953a46f][ExtensionHostConnection] New connection established.
2023-08-15 14:40:46.135 [info] [127.0.0.1][d953a46f][ExtensionHostConnection] <5691> Launched Extension Host Process.
2023-08-15 14:41:41.866 [info] [127.0.0.1][bb20e245][ManagementConnection] New connection established.
2023-08-15 14:41:42.350 [info] [127.0.0.1][3a976eaf][ExtensionHostConnection] New connection established.
2023-08-15 14:41:42.355 [info] [127.0.0.1][3a976eaf][ExtensionHostConnection] <6288> Launched Extension Host Process.
2023-08-15 15:00:43.465 [info] [127.0.0.1][bb20e245][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-08-15 15:00:43.466 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 15:00:43.467 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
2023-08-15 15:00:43.467 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
2023-08-15 15:00:43.531 [info] [127.0.0.1][3a976eaf][ExtensionHostConnection] <6288> Extension Host Process exited with code: 0, signal: null.
2023-08-15 15:00:46.227 [info] [127.0.0.1][510c4c06][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-08-15 15:00:46.228 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 15:00:46.228 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
2023-08-15 15:00:46.228 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
2023-08-15 15:00:46.282 [info] [127.0.0.1][d953a46f][ExtensionHostConnection] <5691> Extension Host Process exited with code: 0, signal: null.
2023-08-15 15:10:00.210 [info] [127.0.0.1][d9e79739][ManagementConnection] New connection established.
2023-08-15 15:10:00.714 [info] [127.0.0.1][456ed8dd][ExtensionHostConnection] New connection established.
2023-08-15 15:10:00.717 [info] [127.0.0.1][456ed8dd][ExtensionHostConnection] <22606> Launched Extension Host Process.
2023-08-15 15:13:27.113 [info] [127.0.0.1][d9e79739][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-08-15 15:13:27.115 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 15:13:27.117 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 15:13:27.117 [error] Error: Throttler is disposed
    at r.queue (/home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:13612)
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:15183
    at /home/peter/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/server/node/server.main.js:70:14822
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
2023-08-15 15:13:27.202 [info] [127.0.0.1][456ed8dd][ExtensionHostConnection] <22606> Extension Host Process exited with code: 0, signal: null.

```

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12850HX (24 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (8.09GB free)|
|Process Argv|--crash-reporter-id ea58db99-4fd5-49ef-8f73-28de6d2ad802|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12850HX (24 x 2419)|
|Memory (System)|15.44GB (9.99GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.1
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.0
vscode-openapi|42C|4.18.6
markdown-mermaid|bie|1.19.0
package-json-upgrade|cod|2.0.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
prettier-vscode|esb|10.1.0
vscode-pull-request-github|Git|0.70.0
plantuml|jeb|2.17.5
solidity|Jua|0.0.165
git-graph|mhu|1.30.0
vscode-docker|ms-|1.26.0
vscode-yaml|red|1.14.0
code-spell-checker|str|2.20.5
vscode-npm-scripts|tra|0.2.1
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by petermetz** [comment]
@mjbvz I'm guessing this was fixed by subsequent releases in the meantime because I haven't seen it for the past couple of months (I'm using stable, not insiders). Thank you for checking in on it!
