### ISSUE TITLE
Typescript server tries to read node_modules in parent directory

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#190774]
1. Open https://insiders.vscode.dev/github/microsoft/vscode/pull/190758/
2. Open dev tools
3. :bug: see the following
 
```
tsserver.web.js:6  Error: Could not read file outside of project root /vscode-vfs/github+7b2276223a312c22726566223a7b2274797065223a332c226964223a22313537227d7d/microsoft/node_modules
    at R (tsserver.web.js:6:2505223)
    at Object.watchDirectory (tsserver.web.js:6:2501229)
    at watchDirectory (tsserver.web.js:6:1244367)
    at tsserver.web.js:6:1245597
    at Object.watchDirectory (tsserver.web.js:6:1245531)
    at jhe.watchDirectoryOfFailedLookupLocation (tsserver.web.js:6:2137175)
    at Q (tsserver.web.js:6:1362400)
    at H (tsserver.web.js:6:1361742)
    at q (tsserver.web.js:6:1360300)
    at U (tsserver.web.js:6:1360568)
watchDirectory @ tsserver.web.js:6
gitlens.js:3  Uncaught (in promise) ReferenceError: window is not defined
	at t.onInit (gitlens.js:3:1096587)
	at t.e (gitlens.js:3:1092375)
	at t [as constructor] (gitlens.js:3:1096132)
	at new t (gitlens.js:3:1101969)
	at new OpenTelemetryProvider (gitlens.js:3:1147146)
	at TelemetryService.initializeTelemetry (gitlens.js:3:542535)
tsserver.web.js:6  Error: Could not read file outside of project root /vscode-vfs/github+7b2276223a312c22726566223a7b2274797065223a332c226964223a22313537227d7d/microsoft/node_modules/@types
    at R (tsserver.web.js:6:2505223)
    at Object.watchDirectory (tsserver.web.js:6:2501229)
    at watchDirectory (tsserver.web.js:6:1244367)
    at tsserver.web.js:6:1245597
    at Object.watchDirectory (tsserver.web.js:6:1245531)
    at jhe.watchTypeRootsDirectory (tsserver.web.js:6:2138336)
    at le (tsserver.web.js:6:1364322)
    at tsserver.web.js:1:675724
    at Map.forEach (<anonymous>)
    at Qx (tsserver.web.js:1:675689)
watchDirectory @ tsserver.web.js:6
workbench.web.main.js:626   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: vscode.typescript-language-features, path: vscode-vfs://github+7b2276223a312c22726566223a7b2274797065223a332c226964223a22313537227d7d/microsoft/vscode-remote-wsl/node_modules/@types, recursive: true, session: 0.07229913402707): EntryNotFound (FileSystemError): github://github+7b2276223a312c22726566223a7b2274797065223a332c226964223a22313537227d7d/microsoft/vscode-remote-wsl/node_modules/@types
```

**Comment by mjbvz** [comment]
This is expected. The error means the read isn't actually happening and we use this to signal back to ts not to try reading there again
