### ISSUE TITLE
cannot open settings

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19122]
on a fresh insiders install on a fresh VM (windows 8), *without* having a folder open, I see this:

![jan-24-2017 10-26-50](https://cloud.githubusercontent.com/assets/1794099/22241454/b47265fc-e21f-11e6-9eb8-712c3eb24abb.gif)

```
shell.ts:437Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at new t (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:5388)
    at g (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:23409)
    at t._createInstance (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:14239)
    at t.createInstance (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:13009)
    at t.createPreferencesRenderer (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:4749)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:3582
    at then (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19172)
    at t.onModelChanged (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:3537)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:3329
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:27507e.onUnexpectedError @ shell.ts:437
winjs.base.js:45WARNING: Promise with no error callback:82
winjs.base.js:46Object
winjs.base.js:48TypeError: Cannot read property 'toString' of null
    at new t (preferencesEditor.ts:590)
    at g (types.ts:168)
    at t._createInstance (instantiationService.ts:162)
    at t.createInstance (instantiationService.ts:78)
    at t.createPreferencesRenderer (preferencesEditor.ts:560)
    at preferencesEditor.ts:504
    at then (winjs.base.raw.js:1566)
    at t.onModelChanged (preferencesEditor.ts:502)
    at preferencesEditor.ts:494
    at event.ts:217
```

**Comment by kaiwood** [comment]
Dup of #19121 :P

**Comment by jrieken** [comment]
yep ;-). closing
