### ISSUE TITLE
Can't open settings in current insiders build

### ISSUE THREAD

**Issue by kaiwood** [Microsoft/vscode#19121]
- VSCode Version: 1.9.0-insider 61a56dbf6e80b6732381349e4654e3ae5f0710f4
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Open Code (Either normal or via code-insiders --disable-extensions)
2. Open Settings (via menu or shortcut)

I tried to open the settings today and now get the following error message:
 
`Unable to open 'settings.json': Cannot read property 'filterPreferences' of undefined.`

![screen shot 2017-01-24 at 10 10 24](https://cloud.githubusercontent.com/assets/7542/22240901/58bb09fa-e21d-11e6-9875-523f40dbbfe6.png)

Emptying or deleting the settings.json file doesn't change anything.

Full stack trace from the developer console:

    shell.ts:437 Cannot read property 'clearFocus' of undefined: TypeError: Cannot read property 'clearFocus' of undefined
        at Array.<anonymous> (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:117:27226)
        at e.invoke (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26950)
        at e.fire (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:30440)
        at t.clear (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:26026)
        at t.render (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:18962)
        at t.filterPreferences (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:10574)
        at t.filterPreferences (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:117:28011)
        at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:117:27266
        at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12333)
        at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)e.onUnexpectedError @     shell.ts:437(anonymous function) @ shell.ts:389e.onUnexpectedError @ errors.ts:68o @ errors.ts:88e.invoke @ callbackList.ts:65e.fire @ event.ts:118t.clear @     preferencesEditor.ts:1347t.render @ preferencesEditor.ts:1094t.filterPreferences @ preferencesEditor.ts:747t.filterPreferences @ preferencesEditor.ts:204(anonymous function) @     preferencesEditor.ts:177g @ winjs.base.raw.js:1170enter @ winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @ winjs.base.raw.js:1036u @ winjs.base.raw.js:1813Y.then.o.(anonymous     function) @ winjs.base.raw.js:1838g @ winjs.base.raw.js:1170enter @ winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @ winjs.base.raw.js:1036then @ winjs.base.raw.js:1566enter @     winjs.base.raw.js:747_run @ winjs.base.raw.js:1068_setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170enter @ winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @     winjs.base.raw.js:1036(anonymous function) @ modelBuilder.ts:134emitNone @ events.js:91emit @ events.js:185endReadableNT @ _stream_readable.js:974_combinedTickCallback @     internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
    messageService.ts:126 Unable to open 'settings.json': Cannot read property 'filterPreferences' of undefined.: Error: Unable to open 'settings.json': Cannot read property 'filterPreferences' of     undefined.
        at t.doHandleSetInputError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:131:20576)
        at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:131:20182
        at Object.v [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
        at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)
        at _run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17739)
        at _completed (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17180)
        at u (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20718)
        at Y.then.o.(anonymous function) (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20935)
        at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12333)
        at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)e.doShow @     messageService.ts:126e.show @ messageService.ts:105t.doHandleSetInputError @ editorPart.ts:500(anonymous function) @ editorPart.ts:480v @ winjs.base.raw.js:1209enter @     winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @ winjs.base.raw.js:1036u @ winjs.base.raw.js:1813Y.then.o.(anonymous function) @ winjs.base.raw.js:1838g @     winjs.base.raw.js:1170enter @ winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @ winjs.base.raw.js:1036then @ winjs.base.raw.js:1566enter @ winjs.base.raw.js:747_run @     winjs.base.raw.js:1068_setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170enter @ winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @ winjs.base.raw.js:1036    (anonymous function) @ modelBuilder.ts:134emitNone @ events.js:91emit @ events.js:185endReadableNT @ _stream_readable.js:974_combinedTickCallback @     internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
    shell.ts:437 Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
        at new t (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:5388)
        at g (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:23409)
        at t._createInstance (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:14239)
        at t.createInstance (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:13009)
        at t.createPreferencesRenderer (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:4749)
        at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:3582
        at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19172)
        at t.onModelChanged (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:3537)
        at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:3329
        at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:27507e.onUnexpectedError @ shell.ts:437(anonymous     function) @ shell.ts:389e.onUnexpectedError @ errors.ts:68o @ errors.ts:88(anonymous function) @ winjs.base.js:41(anonymous function) @ winjs.base.js:38
    winjs.base.js:45 WARNING: Promise with no error callback:123
    winjs.base.js:46 Object {exception: TypeError: Cannot read property 'toString' of null
        at new t (file:////Applications/Visual Studio…, error: null, promise: n.C…s.d…e.supportedForProcessing, handler: undefined, id: 123…}
    winjs.base.js:48 TypeError: Cannot read property 'toString' of null
        at new t (preferencesEditor.ts:590)
        at g (types.ts:168)
        at t._createInstance (instantiationService.ts:162)
        at t.createInstance (instantiationService.ts:78)
        at t.createPreferencesRenderer (preferencesEditor.ts:560)
        at preferencesEditor.ts:504
        at then (winjs.base.raw.js:1566)
        at t.onModelChanged (preferencesEditor.ts:502)
        at preferencesEditor.ts:494
        at event.ts:217

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.9.0-insider (c74d41044d7928c3a4916f2d8b2301f6129ab727, 2017-01-31T13:11:16.234Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|0.8.1|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.2.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.2|
|ghlink|dt|0.0.4|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.8.0|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|

Just seen, but does not reproduce:
```
shell.ts:437 Cannot read property 'clearFocus' of null: TypeError: Cannot read property 'clearFocus' of null
    at Array.<anonymous> (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:6917)
    at e.invoke (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26950)
    at e.fire (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:30440)
    at t.clear (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:6290)
    at t.render (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:31119)
    at t.filterPreferences (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:22731)
    at t.filterPreferences (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:7741)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:6957
    at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12333)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)e.onUnexpectedError @ shell.ts:437
messageService.ts:126 Unable to open 'settings.json': Cannot read property 'filterPreferences' of null.: Error: Unable to open 'settings.json': Cannot read property 'filterPreferences' of null.
    at t.doHandleSetInputError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:132:787)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:132:393
    at Object.v [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)
    at _run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17739)
    at _completed (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17180)
    at u (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20718)
    at Y.then.o.(anonymous function) (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20935)
    at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12333)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)e.doShow @ messageService.ts:126
```

**Comment by sandy081** [comment]
@chrmarti Thanks for reporting. 

This looks to me a separate issue and hence opened a new bug #19663. Moreover this is not blocking opening Settings editor and the error is shown in console.
