### ISSUE TITLE
open file failed on github.dev

### ISSUE THREAD

**Issue by AkaShark** [microsoft/vscode#191280]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:
When I use Github, I click `.` to open github.dev, i get this error 
<img width="1343" alt="CleanShot 2023-08-25 at 13 31 22@2x" src="https://github.com/microsoft/vscode/assets/26460192/e6562aea-8ef9-4b42-ba47-f6333822fcda">

Then I see  in output get this log
<img width="1136" alt="CleanShot 2023-08-25 at 13 37 18@2x" src="https://github.com/microsoft/vscode/assets/26460192/4e8bba17-e763-4190-9f12-f45200ef4e58">

===== log =====
2023-08-25 13:21:16.335 [info] Extension host started
2023-08-25 13:21:16.337 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*'
2023-08-25 13:21:16.338 [error] CodeExpectedError: ENOPRO: 未找到资源 "vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d6173746572227d7d/AkaShark/Obisidian" 的文件系统提供程序
    at r.j (https://assets.github.dev/stable/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/workbench.web.main.js:624:11015)
    at async r.exists (https://assets.github.dev/stable/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/workbench.web.main.js:624:13222)
    at async Promise.all (index 0)
    at async https://assets.github.dev/stable/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/workbench.web.main.js:1862:2483
2023-08-25 13:21:16.338 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-08-25 13:21:16.759 [error] No bundle location found for extension vscode.git-base
2023-08-25 13:21:16.762 [info] Eager extensions activated
2023-08-25 13:21:16.764 [error] No bundle location found for extension vscode.github-authentication
2023-08-25 13:21:16.766 [warning] Using default string since no string found in i18n bundle that has the key: url handler
2023-08-25 13:21:16.766 [warning] Using default string since no string found in i18n bundle that has the key: local server
2023-08-25 13:21:16.766 [warning] Using default string since no string found in i18n bundle that has the key: device code
2023-08-25 13:21:16.766 [warning] Using default string since no string found in i18n bundle that has the key: personal access token
2023-08-25 13:21:16.771 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-08-25 13:21:16.773 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-08-25 13:21:17.013 [error] No bundle location found for extension vscode.merge-conflict
2023-08-25 13:21:17.019 [warning] Using default string since no string found in i18n bundle that has the key: (Current Change)
2023-08-25 13:21:17.020 [warning] Using default string since no string found in i18n bundle that has the key: (Incoming Change)
2023-08-25 13:21:17.020 [error] No bundle location found for extension vscode.microsoft-authentication
2023-08-25 13:21:17.020 [warning] Using default string since no string found in i18n bundle that has the key: Microsoft Authentication
2023-08-25 13:21:17.022 [warning] Using default string since no string found in i18n bundle that has the key: Microsoft Authentication
2023-08-25 13:23:35.287 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-08-25 13:23:35.702 [error] No bundle location found for extension vscode.emmet

**Comment by AkaShark** [comment]
Some one can help

**Comment by yusancky** [comment]
第一个提示我倒是经常遇到，应该是下载时断连了，刷新几次就好了。后面的就不清楚了。

**Comment by joyceerhl** [comment]
@akashark there are a lot of messages in the logs you attached which suggest that we failed to download the builtin extensions that are required for github.dev to work. Are you behind a firewall or proxy that might prevent us connecting to vscode-unpkg.net? Can you open the Network tab in the developer tools console and share any blocked requests that you see when you try to load github.dev? Thanks!

**Comment by AkaShark** [comment]
> @AkaShark there are a lot of messages in the logs you attached which suggest that we failed to download the builtin extensions that are required for github.dev to work. Are you behind a firewall or proxy that might prevent us connecting to vscode-unpkg.net? Can you open the Network tab in the developer tools console and share any blocked requests that you see when you try to load github.dev? Thanks!

You were right, I resolved the issue! It seems that my company's network was the cause. Thank you!
