### ISSUE TITLE
Deserialize notebook kernel history failed

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#191578]
Going through the error logs showed the error below ⬇️. No steps but it is rooted at this line

https://github.com/microsoft/vscode/blob/5cd507ba17ec7a0d8a822c35bfcde8eca33de861/src/vs/workbench/contrib/notebook/browser/services/notebookKernelHistoryServiceImpl.ts#L95

```
Deserialize notebook kernel history failed TypeError: JSON.parse is not a function or its return value is not iterable
    at g.i (notebookKernelHistoryServiceImpl.ts:95:44)
    at o.value (notebookKernelHistoryServiceImpl.ts:40:9)
    at f.w (event.ts:1089:13)
    at f.fire (event.ts:1120:9)
    at o.value (event.ts:152:97)
    at u.w (event.ts:1089:13)
    at u.x (event.ts:1100:9)
    at u.fire (event.ts:1124:9)
    at u.resume (event.ts:1275:12)
    at S.t (storage.ts:494:27)
    at S.store (storage.ts:460:8)
    at g.h (notebookKernelHistoryServiceImpl.ts:85:25)
    at o.value (notebookKernelHistoryServiceImpl.ts:38:66)
    at f.w (event.ts:1089:13)
    at f.x (event.ts:1100:9)
    at f.fire (event.ts:1124:9)
    at S.flush (storage.ts:584:25)
    at o.value (workbench.ts:255:20)
    at f.w (event.ts:1089:13)
    at f.x (event.ts:1100:9)
    at f.fire (event.ts:1124:9)
    at event.ts:152:97
    at o.value (event.ts:168:117)
    at f.w (event.ts:1089:13)
    at f.fire (event.ts:1120:9)
    at o.value (event.ts:118:84)
    at f.w (event.ts:1089:13)
    at f.fire (event.ts:1120:9)
    at o.value (event.ts:152:97)
    at f.w (event.ts:1089:13)
    at f.fire (event.ts:1120:9)
    at Y (ipc.ts:672:60)
    at M.t (ipc.ts:740:48)
    at M.s (ipc.ts:729:17)
    at o.value (ipc.ts:549:63)
    at f.w (event.ts:1089:13)
    at f.x (event.ts:1100:9)
    at f.fire (event.ts:1124:9)
    at Function.ce (event.ts:528:41)
```

**Comment by amunger** [comment]
verification -
Perform a few actions in a notebook, add cells, run cells, close/reopen the tab, run more cells
Open the dev tools and ensure the `Deserialize notebook kernel history failed` error is not in the console
