### ISSUE TITLE
Smoke test failure (vscode-smoketest-check-extension/time out for search box)

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#191860]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=229931
Changes: https://github.com/Microsoft/vscode/compare/e2085fa...3217686

```
1) VSCode Smoke Tests (Web)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: is active element 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-editor textarea' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:273:11)
      at Code.waitForActiveElement (D:\a\_work\1\s\test\automation\src\code.ts:226:3)
      at Extensions.searchForExtension (D:\a\_work\1\s\test\automation\src\extensions.ts:34:3)
      at Extensions.installExtension (D:\a\_work\1\s\test\automation\src\extensions.ts:60:3)
      at Context.<anonymous> (src\areas\extensions\extensions.test.ts:19:4)
```

**Comment by bpasero** [comment]
@sandy081 there is always a `smoke-test-runner.log` attached to the logs artefacts and it contains the full output from the playwright driver.

Here it seems stuck:

```
[2023-08-30T22:56:13.492Z] getDriverHandle
[2023-08-30T22:56:13.595Z] isActiveElement div.extensions-viewlet[id="workbench.view.extensions"] .monaco-editor textarea
[2023-08-30T22:56:13.595Z] getDriverHandle
[2023-08-30T22:56:13.698Z] Timeout!
[2023-08-30T22:56:13.698Z] page.evaluate: Error: Active element not found. Current active element is 'HTML > BODY.linux.web'. Looking for div.extensions-viewlet[id="workbench.view.extensions"] .monaco-editor textarea
    at y.isActiveElement (http://localhost:9008/insider-3217686db153a4bf9ff11a74beb5288c102c41e4/static/out/vs/workbench/workbench.web.main.js:627:26454)
    at eval (eval at evaluate (:197:30), <anonymous>:1:32)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Proxy.isActiveElement (/mnt/vss/_work/1/s/test/automation/src/playwrightDriver.ts:199:20)
    at Code.poll (/mnt/vss/_work/1/s/test/automation/src/code.ts:278:14)
    at Code.waitForActiveElement (/mnt/vss/_work/1/s/test/automation/src/code.ts:226:3)
    at Extensions.searchForExtension (/mnt/vss/_work/1/s/test/automation/src/extensions.ts:34:3)
    at Extensions.installExtension (/mnt/vss/_work/1/s/test/automation/src/extensions.ts:60:3)
    at Context.<anonymous> (/mnt/vss/_work/1/s/test/smoke/src/areas/extensions/extensions.test.ts:19:4)
```

**Comment by TylerLeonhardt** [comment]
[Skipping this test](https://github.com/microsoft/vscode/pull/191936) since it has causes a few build failures.
