### ISSUE TITLE
When connected to a remote in two windows, closing the first window breaks the connection in the second

### ISSUE THREAD

**Issue by jkeech** [microsoft/vscode#191832]
Does this issue occur when all extensions are disabled?: No, needs a remote extension enabled for this scenario

- VS Code Version: 1.81.1
- OS Version: macOS 13.5.1

Steps to Reproduce:

1. Connect to a codespace from VS Code desktop
2. From the terminal, open a second window with `code <other-folder>`
3. With both windows connected, close the original window
4. 🐛 The second window goes into an endless reconnecting loop with the management socket seemingly in a bad state

Note that the order of the windows is important. If you close the second window, the first is unaffected. But closing the original window breaks the second window.

Window output logs from the second window that is trying to reconnect:
```
2023-08-30 10:32:14.378 [info] [remote-connection][Management   ][07e4f…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-08-30 10:32:14.378 [error] {"isTrusted":true}
2023-08-30 10:32:14.378 [info] [remote-connection][Management   ][07e4f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-08-30 10:32:14.378 [info] [remote-connection][Management   ][07e4f…][reconnect] resolving connection...
2023-08-30 10:32:14.378 [info] Invoking resolveAuthority(codespaces)...
2023-08-30 10:32:14.378 [info] [LocalProcess0][resolveAuthority(codespaces,2)][0ms] obtaining proxy...
2023-08-30 10:32:14.378 [info] [LocalProcess0][resolveAuthority(codespaces,2)][0ms] invoking...
2023-08-30 10:32:14.379 [info] [remote-connection][ExtensionHost][548ea…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-08-30 10:32:14.379 [error] {"isTrusted":true}
2023-08-30 10:32:14.379 [info] [remote-connection][ExtensionHost][548ea…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-08-30 10:32:14.379 [info] [remote-connection][ExtensionHost][548ea…][reconnect] resolving connection...
2023-08-30 10:32:15.361 [info] [LocalProcess0][resolveAuthority(codespaces,2)][1000ms] waiting...
2023-08-30 10:32:16.363 [info] [LocalProcess0][resolveAuthority(codespaces,2)][2002ms] waiting...
2023-08-30 10:32:16.557 [info] [LocalProcess0][resolveAuthority(codespaces,2)][2176ms] returned WebSocket(127.0.0.1:46401)
2023-08-30 10:32:16.557 [info] resolveAuthority(codespaces) returned 'WebSocket(127.0.0.1:46401)' after 2177 ms
2023-08-30 10:32:16.558 [info] [remote-connection][Management   ][07e4f…][reconnect] connecting to WebSocket(127.0.0.1:46401)...
2023-08-30 10:32:16.558 [info] Creating a socket (renderer-Management-07e4ff98-f77a-406f-9d3d-b1ca0b7b6bcd)...
2023-08-30 10:32:16.558 [info] [remote-connection][ExtensionHost][548ea…][reconnect] connecting to WebSocket(127.0.0.1:46401)...
2023-08-30 10:32:16.558 [info] Creating a socket (renderer-ExtensionHost-548ea276-0693-49cf-9922-e84798d60d6c)...
2023-08-30 10:32:16.559 [info] Creating a socket (renderer-Management-07e4ff98-f77a-406f-9d3d-b1ca0b7b6bcd) returned an error after 22 ms.
2023-08-30 10:32:16.559 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:658:2885)
2023-08-30 10:32:16.559 [error] [remote-connection][Management   ][07e4f…][reconnect][WebSocket(127.0.0.1:46401)] socketFactory.connect() failed or timed out. Error:
2023-08-30 10:32:16.559 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:658:2885)
2023-08-30 10:32:16.559 [info] [remote-connection][Management   ][07e4f…][reconnect] A temporarily not available error occurred while trying to reconnect, will try again...
2023-08-30 10:32:16.559 [info] [remote-connection][Management   ][07e4f…][reconnect] waiting for 5 seconds before reconnecting...
2023-08-30 10:32:16.570 [info] Creating a socket (renderer-ExtensionHost-548ea276-0693-49cf-9922-e84798d60d6c) returned an error after 32 ms.
2023-08-30 10:32:16.570 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:658:2885)
2023-08-30 10:32:16.570 [error] [remote-connection][ExtensionHost][548ea…][reconnect][WebSocket(127.0.0.1:46401)] socketFactory.connect() failed or timed out. Error:
2023-08-30 10:32:16.571 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:658:2885)
2023-08-30 10:32:16.571 [info] [remote-connection][ExtensionHost][548ea…][reconnect] A temporarily not available error occurred while trying to reconnect, will try again...
2023-08-30 10:32:16.571 [info] [remote-connection][ExtensionHost][548ea…][reconnect] waiting for 5 seconds before reconnecting...
```

Process tree after the first connection:

![Image](https://github.com/microsoft/vscode/assets/746020/74757c8c-101f-442e-ad74-26ce90ec64ac)

Process tree after the second connection:

![Image](https://github.com/microsoft/vscode/assets/746020/fad33f4a-b064-4b46-884f-3be7660e2ced)

Process tree after closing the first window (collected via SSH since all VS Code connections are disconnected):

![Image](https://github.com/microsoft/vscode/assets/746020/11a89f9e-c0ec-431b-8288-c44dbda2c855)

Performing a hard reload with `Reload window` succeeds, but we would like for the connection to not drop originally, or at least to automatically reconnect quickly.

cc @alexdima

**Comment by connor4312** [comment]
Potentially duplicates/duplicated by https://github.com/microsoft/vscode-remote-release/issues/8903

**Comment by connor4312** [comment]
Though just from the logs this looks like an issue with the codespaces extension trying to re-use a proxy process that gets killed when the spawner EH closes. Just looking through the codespaces extension code, it seems like it's trying to use the function `execAgent` to create this process and "unref[ing] so it can be a long running process", but this is not the correct way to keep the process alive as a background process. (Unrefing only affects whether the process spawning the child process will avoid exiting if the child is running.)

**Comment by connor4312** [comment]
Update from DM: this looks seems to be a different bug in the Codespaces extension.

@jkeech feel free to close the issue unless there's anything you think may be an issue on the vscode side!

**Comment by jkeech** [comment]
Confirmed this is related to how the local port forwarding was working and what the resolver was returning from both windows. This can be fixed within the Codespaces extension. Closing, thanks!
