### ISSUE TITLE
Error: listen EADDRINUSE /var/folders/rp/xjpqwtvs1q1gg1bb8ww0mtxr0000gn/T/vscode-b77.sock

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19188]
Just saw this running "out of sources":

```
~/Development/monaco/scripts> ./code.sh 
[8129:0124/140721:INFO:CONSOLE(153)] "%c[Extension Host] %cdebugger listening on port 5870", source: file:////Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/extensionHost.js (153)
[8129:0124/140721:INFO:CONSOLE(119)] "ERROR starting extension host", source: file:////Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/extensionHost.js (119)
[8129:0124/140721:INFO:CONSOLE(120)] "Error: listen EADDRINUSE /var/folders/rp/xjpqwtvs1q1gg1bb8ww0mtxr0000gn/T/vscode-b77.sock", source: file:////Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/extensionHost.js (120)
```

**Comment by jrieken** [comment]
hm, how random is random...

**Comment by jrieken** [comment]
@bpasero I have pushed a change to use more random pipe names to prevent such collision. Let me know if you still see this.

**Comment by bpasero** [comment]
Sometimes I see this now:

```
Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
```

This is with heavy reload, close, restart running "out of sources", not in selfhost. This stacktrace is quite useless I guess, but maybe we can add more error handling in this area for the extension host communication somehow?

**Comment by jrieken** [comment]
I'd say that is more likely #19176. Originally we had an empty `try-catch`-block around the write call. I removed that and yesterday I added a check if the socket is [destroyed](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/ipc/node/ipc.net.ts#L142) but that might not be enough. I might have to bite the dust and add the empty `try-catch` again...
