### ISSUE TITLE
Remote SSH forever keeps asking password

### ISSUE THREAD

**Issue by stevezhang1999** [microsoft/vscode#192091]
Does this issue occur when all extensions are disabled?: Yes/No

Platform 1
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Platform 2
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0

Steps to Reproduce:

On Platform 1, Windows
1. Delete all the `.vscode_server` and `.vscode` from the remote server.
2. The remote server is Ubuntu, using Andrew File System
3. Ctrl+Shift+P to "kill vscode server on host", if necessary
4. `Use Flock` is True. I cannot recall whether `Use Local Server` was True then - I suspect this is irrelevant.
5. Click the left-bottom "connect remote" icon and connect - either entering the credential in the prompt or configuring with a config file brings the same issue. 
6. The first time of connection will always (I believe) succeed. However, when I clicked "open folder", it keeps asking for password forever. The message is attached at the end of the thread.
7. When I failed to connect, I tried on Mac. The same thing happens.

On Platform 2, Mac
8. On Mac, I disabled `Use Flock`, doing step 1 and 3, it works!

On Platform 1, Windows
9. After successfully setting this up on Mac, with the original setting on Windows (`Use Flock` is True), I successfully connected to a folder using a cached link in the VScode Welcome - Recent page. That is, I didn't have the chance to connect to the root folder and see if it works.
10. When I disconnected and tried to connect again, the "forever password prompt" issue happens again.
11. Ctrl+Shift+P to "kill vscode server on host". Then I tried to connect to the folder, it works.  (Only once)
12. I repeated all steps of 11 but rather connecting to a folder from the link in VScode Welcome - Recent, it also works. (Only once)
13. I set "Use Flock" on my Windows to False without killing the server. The error persists.
14. I killed the server and kept "Use Flock" to False. It works - the error doesn't come again after disconnecting and re-connecting several times.
15. Message. This is the message from step 9, but I believe it's the same as in step 6.
One thing I would like to add is that other related issues have at least some kinds of error message, but the message I got didn't tell me what was failing.
```
[20:08:41.473] Log Level: 2
[20:08:41.480] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22474843227d", attempt 1
[20:08:41.481] "remote.SSH.useLocalServer": false
[20:08:41.481] "remote.SSH.showLoginTerminal": false
[20:08:41.481] "remote.SSH.remotePlatform": {"xxx.edu":"linux","org.edu":"linux","GHC":"linux"}
[20:08:41.481] "remote.SSH.path": undefined
[20:08:41.481] "remote.SSH.configFile": undefined
[20:08:41.481] "remote.SSH.useFlock": true
[20:08:41.481] "remote.SSH.lockfilesInTmp": false
[20:08:41.481] "remote.SSH.localServerDownload": auto
[20:08:41.481] "remote.SSH.remoteServerListenOnSocket": false
[20:08:41.482] "remote.SSH.showLoginTerminal": false
[20:08:41.482] "remote.SSH.defaultExtensions": []
[20:08:41.482] "remote.SSH.loglevel": 2
[20:08:41.482] "remote.SSH.enableDynamicForwarding": true
[20:08:41.482] "remote.SSH.enableRemoteCommand": false
[20:08:41.482] "remote.SSH.serverPickPortsFromRange": {}
[20:08:41.482] "remote.SSH.serverInstallPath": {}
[20:08:41.485] VS Code version: 1.81.1
[20:08:41.485] Remote-SSH version: remote-ssh@0.102.0
[20:08:41.485] win32 x64
[20:08:41.486] SSH Resolver called for host: GHC
[20:08:41.486] Setting up SSH remote "GHC"
[20:08:41.489] Using commit id "6c3e3dba23e8fadc360aed75ce363ba185c49794" and quality "stable" for server
[20:08:41.492] Install and start server if needed
[20:08:41.496] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[20:08:41.498] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[20:08:41.498] Checking ssh with "C:\Windows\ssh.exe -V"
[20:08:41.499] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[20:08:41.499] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[20:08:41.500] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[20:08:41.500] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[20:08:41.501] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[20:08:41.501] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[20:08:41.520] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[20:08:41.523] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 1873 "GHC" bash
[20:08:41.525] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:08:42.029] > user@org.edu's password:]0;C:\WINDOWS\System32\cmd.exe
[20:08:42.029] Got some output, clearing connection timeout
[20:08:42.029] Showing password prompt
[20:08:49.273] Got password response
[20:08:49.274] "install" wrote data to terminal: "****************"
[20:08:49.313] > 
[20:08:49.875] > c304672f0005: running
[20:08:49.937] > Acquiring lock on xxx.edu/usr4/user/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/vscode-remote-lock.user.6c3e3dba23e8fadc360aed75ce363ba185c49794
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> c304672f0005: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/2687500==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> c304672f0005: end
[20:08:49.939] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/2687500==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[20:08:49.942] Server installation process already in progress - waiting and retrying
[20:08:50.956] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 1873 "GHC" bash
[20:08:50.958] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:08:51.412] "install" terminal command done
[20:08:51.412] Install terminal quit with output: 
[20:08:51.465] > user@org.edu's password:]0;C:\WINDOWS\System32\cmd.exe
[20:08:51.465] Got some output, clearing connection timeout
[20:08:51.466] Showing password prompt
[20:10:06.345] Password dialog canceled
[20:10:06.345] "install" terminal command canceled
[20:10:06.347] Resolver error: Error: Connecting was canceled
	at m.Canceled (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584341)
	at c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681195
[20:10:06.352] ------
```

**Comment by roblourens** [comment]
> using Andrew File System

I suspect this is causing an issue with acquiring a lock on the fs. I assume that if you always delete the file referenced in `Acquiring lock on ...` then it should work?

**Comment by notatallshaw-gts** [comment]
I believe I am having the same error since 1.81.1, I tried deleting the entire `.vscode-server` directory but then I just got the issue again the next time I needed to reload VS Code.

I have downgraded to 1.81.0 and I am no longer experiencing this issue.

Let me know if there's any information I can provide to help debug this issue.

**Comment by zhiqiang-hhhh** [comment]
Same error after I upgrade vscode to 1.82 and RemoteSSH plugin

**Comment by roblourens** [comment]
Please open your own issues with the full log, if you are having trouble.

Closing due to no response from OP

**Comment by notatallshaw-gts** [comment]
FYI, upgrading directly to 1.83.0 fixed this for me.
