### ISSUE TITLE
Cannot find module 'minimist'

### ISSUE THREAD

**Issue by ChenHaoYan1234** [microsoft/vscode#192067]
Does this issue occur when all extensions are disabled?: Don't know

- VS Code Version: 1.82.0-insider
- OS Version: Windows 11 21H2 with WSL Ubuntu 23.10

Steps to Reproduce:

1. Open a file in WSL in vscode 
2. Get a error

Logs:
Loading "minimist" failed
Error: Cannot find module 'minimist'
Require stack:
- /home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at r (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:3:98)
    at n.load (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:2:1637)
    at c.load (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:1:10823)
    at u (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:3:9338)
    at Object.errorback (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:3:9457)
    at c.triggerErrorback (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:1:11117)
    at /home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:1:10868
    at n.load (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:2:1654)
    at c.load (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:1:10823)
    at u (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:3:9338)
    at d._loadModule (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:3:9466)
    at d._resolve (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:4:452)
    at d.defineModule (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:3:5561)
    at g (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:4:1741)
    at m (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:2:2448)
    at Object.<anonymous> (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/vs/server/node/server.cli.js:11:108028)
    at Object.<anonymous> (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/vs/server/node/server.cli.js:14:8795)
    at n._createAndEvalScript (/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:2:2492)
    at /home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js:2:2133
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/chenhaoyan/.vscode-server-insiders/bin/f1302be1e67e3af5fbeb8bbb2ea784de7bc96150/out/server-cli.js'
  ],
  phase: 'loading',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ]
}
Here are the modules that depend on it:
[ 'vs/platform/environment/node/argv' ]

**Comment by aeschli** [comment]
Related issue https://github.com/microsoft/vscode-remote-release/issues/6768

This very likely is caused by a corrupted installation.
Close all VS Code instances, open a WSL terminal and run `rm -r ~/.vscode-server-insiders/bin`
