### ISSUE TITLE
VS Code is not always able to parse Dart stacktraces

### ISSUE THREAD

**Issue by lukehutch** [microsoft/vscode#192263]
Does this issue occur when all extensions are disabled?: Yes

Sometimes when a Dart stacktrace is printed to the console, it is not parsed properly by VS Code. For example:

```console
#0      ProfileInfoEndpoint._getAllUserInfo (package:click_server/src/endpoints/profile_endpoint.dart:29:7)
<asynchronous suspension>
#1      ProfileInfoEndpoint.updateProfile (package:click_server/src/endpoints/profile_endpoint.dart:49:9)
<asynchronous suspension>
#2      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)
<asynchronous suspension>
#3      Server._handleRequest (package:serverpod/src/server/server.dart:243:18)
<asynchronous suspension>
```

For this stacktrace, the filename and line numbers are not identified and linked in the debug console by VS Code. They are treated simply as text.

I don't know if this should be reported against VS Code, or against Dart-Code -- @DanTup?

- VS Code Version: 1.81.1, 6c3e3dba23e8fadc360aed75ce363ba185c49794, x64
- OS Version: Fedora38

**Comment by lukehutch** [comment]
In this stacktrace, some of the lines are correctly linked back to source, and some are not:

```console
E/flutter (10117): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
E/flutter (10117): #1      _ProfilePhotoEditorListState._editCaption                profile_photo_editor_list.dart:246
E/flutter (10117): #2      _ProfilePhotoEditorListState._addPhoto.<anonymous closure>.<anonymous closure> 
     profile_photo_editor_list.dart:234
E/flutter (10117): #3      showPhotoCropper.<anonymous closure>.<anonymous closure>              photo_cropper_widget.dart:40
E/flutter (10117): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
E/flutter (10117): #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (10117): #6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (10117): #7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (10117): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by DanTup** [comment]
This should be filed in Dart-Code. Be sure to include whether this is in the Debug Console or the Terminal, as the way links work in each is a little different. Thanks!

**Comment by lukehutch** [comment]
Filed in Dart-Code -- thanks!
