### ISSUE TITLE
verifies that "hot exit" works for dirty files

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#192206]
```

  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies that "hot exit" works for dirty files (with delay):
     electron.launch: Browser closed.
==================== Browser output: ====================
<launching> /mnt/vss/_work/1/VSCode-linux-x64/code-insiders --inspect=0 --remote-debugging-port=0 /tmp/vscsmoke/vscode-smoketest-express --skip-release-notes --skip-welcome --disable-telemetry --no-cached-data --disable-updates --disable-keytar --crash-reporter-directory=/mnt/vss/_work/1/s/.build/crashes/smoke-tests-electron/4_suite_test_verifies_that_hot_exit_works_for_dirty_files_with_delay --disable-workspace-trust --extensions-dir=/tmp/vscsmoke/extensions-dir --user-data-dir=/tmp/vscsmoke/d-fypzz8ny --logsPath=/mnt/vss/_work/1/s/.build/logs/smoke-tests-electron/4_suite_test_verifies_that_hot_exit_works_for_dirty_files_with_delay --disable-dev-shm-usage --enable-smoke-test-driver
<launched> pid=158611
[pid=158611][err] Debugger listening on ws://127.0.0.1:34885/56639b89-3ddf-49f8-a872-d33695831100
[pid=158611][err] For help, see: https://nodejs.org/en/docs/inspector
[pid=158611][err] Debugger attached.
[pid=158611][out] Found --crash-reporter-directory argument. Setting crashDumps directory to be '/mnt/vss/_work/1/s/.build/crashes/smoke-tests-electron/4_suite_test_verifies_that_hot_exit_works_for_dirty_files_with_delay'
[pid=158611][err] 
[pid=158611][err] DevTools listening on ws://127.0.0.1:36971/devtools/browser/c3c8f51e-cc94-4fb3-9ccb-c6cf2a28b3e9
[pid=158611][err] [158645:0905/154009.199811:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
      at measureAndLog (/mnt/vss/_work/1/s/test/automation/src/logger.ts:52:9)
      at launchElectron (/mnt/vss/_work/1/s/test/automation/src/playwrightElectron.ts:32:19)
      at launch (/mnt/vss/_work/1/s/test/automation/src/playwrightElectron.ts:20:38)
      at measureAndLog (/mnt/vss/_work/1/s/test/automation/src/logger.ts:52:9)
      at launch (/mnt/vss/_work/1/s/test/automation/src/code.ts:85:39)
      at Application.startApplication (/mnt/vss/_work/1/s/test/automation/src/application.ts:107:29)
      at Application._start (/mnt/vss/_work/1/s/test/automation/src/application.ts:82:16)
      at /mnt/vss/_work/1/s/test/automation/src/application.ts:74:4
      at measureAndLog (/mnt/vss/_work/1/s/test/automation/src/logger.ts:52:9)
      at Application.restart (/mnt/vss/_work/1/s/test/automation/src/application.ts:72:3)
      at Context.testHotExit (src/areas/workbench/data-loss.test.ts:120:4)
```

Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=230497
Changes: https://github.com/Microsoft/vscode/compare/a3d328a...d697093

**Comment by bpasero** [comment]
@deepak1556 does the error ring a bell?

```
[158645:0905/154009.199811:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```

Should we be running with `disable-gpu`?

Besides, many crash dumps again, such as:

[crash-dump-linux-x64-smoke-1.zip](https://github.com/microsoft/vscode/files/12533597/crash-dump-linux-x64-smoke-1.zip)

**Comment by deepak1556** [comment]
Crashes are tracked in https://github.com/microsoft/vscode/issues/192175

As for GPU initialization failure, it could be due to various reasons depending on the hardware. Need additional logging to identify the cause `--enable-gpu-debugging`. I would suggest to disable gpu, since it is not worth addressing them for CI.
