### ISSUE TITLE
NotebookRendererMessaging unit test flake

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#192313]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=230723
Changes: https://github.com/Microsoft/vscode/compare/a4e1870...dc8730c

```
  1) NotebookRendererMessaging
       "after each" hook for "buffers and then plays events":
```

**Comment by rebornix** [comment]
Not sure how do I read the errors 

```
Error: These disposables were not disposed:
  Error: 
  	at $5S.trackDisposable (file:///mnt/vss/_work/1/s/out-build/vs/base/test/common/utils.js:55:21)
  	at trackDisposable (file:///mnt/vss/_work/1/s/out-build/vs/base/common/lifecycle.js:58:28)
  	at new $lb (file:///mnt/vss/_work/1/s/out-build/vs/base/common/lifecycle.js:261:13)
  	at new $e6 (file:///mnt/vss/_work/1/s/out-build/vs/editor/contrib/suggest/browser/suggestWidget.js:74:22)
  	at $59b.j (file:///mnt/vss/_work/1/s/out-build/vs/platform/instantiation/common/instantiationService.js:91:28)
  	at $59b.createInstance (file:///mnt/vss/_work/1/s/out-build/vs/platform/instantiation/common/instantiationService.js:62:31)
  	at file:///mnt/vss/_work/1/s/out-build/vs/editor/contrib/suggest/browser/suggestController.js:98:39
  	at $Tg.a (file:///mnt/vss/_work/1/s/out-build/vs/base/common/async.js:964:30)
  	at file:///mnt/vss/_work/1/s/out-build/vs/base/common/async.js:973:50
  --------------------
  
  Error: 
  	at $5S.trackDisposable (file:///mnt/vss/_work/1/s/out-build/vs/base/test/common/utils.js:55:21)
  	at trackDisposable (file:///mnt/vss/_work/1/s/out-build/vs/base/common/lifecycle.js:58:28)
  	at new $lb (file:///mnt/vss/_work/1/s/out-build/vs/base/common/lifecycle.js:261:13)
  	at new $e6 (file:///mnt/vss/_work/1/s/out-build/vs/editor/contrib/suggest/browser/suggestWidget.js:75:22)
  	at $59b.j (file:///mnt/vss/_work/1/s/out-build/vs/platform/instantiation/common/instantiationService.js:91:28)
  	at $59b.createInstance (file:///mnt/vss/_work/1/s/out-build/vs/platform/instantiation/common/instantiationService.js:62:31)
  	at file:///mnt/vss/_work/1/s/out-build/vs/editor/contrib/suggest/browser/suggestController.js:98:39
  	at $Tg.a (file:///mnt/vss/_work/1/s/out-build/vs/base/common/async.js:964:30)
  	at file:///mnt/vss/_work/1/s/out-build/vs/base/common/async.js:973:50

```

It's complaining about the `SuggestWidget` which is not used in this test, are these carried over from previous tests, especially there are hundreds of them @connor4312 ?

**Comment by connor4312** [comment]
This should be fixed one everyone's abort the disposable checker train: https://github.com/microsoft/vscode/issues/200091
