### ISSUE TITLE
Editor data loss smoke test flake

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#192357]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=230819&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=d37b6de0-ee32-5542-d5b1-fb041953e05d&l=40

![Image](https://github.com/microsoft/vscode/assets/30305945/0e831ccc-f564-442c-a354-80089305d7bd)

**Comment by bpasero** [comment]
Looks like an unhealthy CI run where the remote extension is not part of the build or not enabled:

```
[2023-09-06T22:02:19.120Z] Playwright (Electron): window.on('console') [%c  ERR color: #f33 CodeExpectedError: No remote extension installed to resolve test.
    at J.ob (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:20109)
    at async J.nb (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:19375)
    at async J.Lb (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2637:11279)
    at async J.gb (vscode-file://vscode-app/d:/a/_work/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:17139)]
```

Might be a one off.
