### ISSUE TITLE
Disposable leaks cause unit test failures

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#192585]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=231184
Changes: https://github.com/Microsoft/vscode/compare/8971983...35c2ce3

```

  (shared with 1/2 leaks) at $Fg (out-build/vs/base/common/async.js:389:16)
  (shared with 1/2 leaks) at /mnt/vss/_work/1/s/out-build/vs/base/common/async.js:387:33
  (shared with 1/2 leaks) at $sg (out-build/vs/base/common/async.js:15:26)
      - stacktraces of 1 other leaks continue with $sg (out-build/vs/base/common/async.js:16:25)
  (shared with 2/2 leaks) at Object.$Fg (out-build/vs/base/common/async.js:387:20)
  (shared with 2/2 leaks) at Context.<anonymous> (out-build/vs/base/test/common/async.test.js:613:45)
  (shared with 2/2 leaks) at process.processImmediate (node:internal/timers:476:21)
  ============================================================
  
  
  
  
  ==================== Leaking disposable 2/2: Object ====================
  (shared with 1/2 leaks) at $8S.trackDisposable (out-build/vs/base/test/common/utils.js:56:21)
  (shared with 1/2 leaks) at $db (out-build/vs/base/common/lifecycle.js:58:28)
  (shared with 1/2 leaks) at $kb (out-build/vs/base/common/lifecycle.js:143:22)
  (shared with 1/2 leaks) at MutableToken.q (out-build/vs/base/common/event.js:822:52)
  (shared with 1/2 leaks) at /mnt/vss/_work/1/s/out-build/vs/base/common/async.js:17:47
  (shared with 1/2 leaks) at new Promise (<anonymous>)
  (shared with 1/2 leaks) at $sg (out-build/vs/base/common/async.js:16:25)
      - stacktraces of 1 other leaks continue with $sg (out-build/vs/base/common/async.js:15:26)
  (shared with 2/2 leaks) at Object.$Fg (out-build/vs/base/common/async.js:387:20)
  (shared with 2/2 leaks) at Context.<anonymous> (out-build/vs/base/test/common/async.test.js:613:45)
  (shared with 2/2 leaks) at process.processImmediate (node:internal/timers:476:21)
  ============================================================
  
  
      at $8S.ensureNoLeakingDisposables (out-build/vs/base/test/common/utils.js:145:19)
      at Context.<anonymous> (out-build/vs/base/test/common/utils.js:170:25)
      at process.processImmediate (node:internal/timers:476:21)

```

**Comment by joaomoreno** [comment]
Will take a look. They passed in the PR: https://dev.azure.com/vscode/VSCode/_build/results?buildId=102880&view=logs&j=f3dd96f0-7bf9-51c6-1e87-22c4cfa2ad69&t=6f7d9d6d-0534-5128-fb37-653109c76813

**Comment by joaomoreno** [comment]
Reverted by @joyceerhl : https://github.com/microsoft/vscode/pull/192593

**Comment by joaomoreno** [comment]
Oh wow this is **very** interesting. The tests pass in a browser, but fail in node.
