### ISSUE TITLE
Exception in integration tests: `TypeError: Cannot read properties of undefined (reading 'StringLiteral')`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192814]
This does not cause a test failure though: https://dev.azure.com/vscode/VSCode/_build/results?buildId=103072&view=logs&j=a8a6689c-5a84-59c0-482a-7dd9f21eb2d8&t=edf7e3d3-8442-5d10-2aed-00cd86970dbb

```
2023-09-11T19:39:05.5015594Z   [32m  ✔[0m[90m diagnostics & CodeActionProvider[0m
2023-09-11T19:39:05.5202410Z Cannot read properties of undefined (reading 'StringLiteral'): TypeError: Cannot read properties of undefined (reading 'StringLiteral')
2023-09-11T19:39:05.5203786Z     at JSONCompletionItemProvider.isLast (/mnt/vss/_work/1/s/extensions/npm/out/features/jsonContributions.js:144:51)
2023-09-11T19:39:05.5204756Z     at JSONCompletionItemProvider.provideCompletionItems (/mnt/vss/_work/1/s/extensions/npm/out/features/jsonContributions.js:114:33)
2023-09-11T19:39:05.5207165Z     at CompletionsAdapter.provideCompletionItems (/mnt/vss/_work/1/s/out/vs/workbench/api/common/extHostLanguageFeatures.js:840:54)
2023-09-11T19:39:05.5207920Z     at /mnt/vss/_work/1/s/out/vs/workbench/api/common/extHostLanguageFeatures.js:1867:85
2023-09-11T19:39:05.5208572Z     at ExtHostLanguageFeatures._withAdapter (/mnt/vss/_work/1/s/out/vs/workbench/api/common/extHostLanguageFeatures.js:1609:28)
2023-09-11T19:39:05.5209248Z     at ExtHostLanguageFeatures.$provideCompletionItems (/mnt/vss/_work/1/s/out/vs/workbench/api/common/extHostLanguageFeatures.js:1867:25)
2023-09-11T19:39:05.5209707Z     at RPCProtocol._doInvokeHandler (/mnt/vss/_work/1/s/out/vs/workbench/services/extensions/common/rpcProtocol.js:408:27)
2023-09-11T19:39:05.5210162Z     at RPCProtocol._invokeHandler (/mnt/vss/_work/1/s/out/vs/workbench/services/extensions/common/rpcProtocol.js:394:45)
2023-09-11T19:39:05.5210605Z     at RPCProtocol._receiveRequest (/mnt/vss/_work/1/s/out/vs/workbench/services/extensions/common/rpcProtocol.js:334:32)
2023-09-11T19:39:05.5211082Z     at RPCProtocol._receiveOneMessage (/mnt/vss/_work/1/s/out/vs/workbench/services/extensions/common/rpcProtocol.js:257:30)
2023-09-11T19:39:05.5211542Z     at UniqueContainer.value (/mnt/vss/_work/1/s/out/vs/workbench/services/extensions/common/rpcProtocol.js:148:50)
2023-09-11T19:39:05.5211962Z     at Emitter._deliver (/mnt/vss/_work/1/s/out/vs/base/common/event.js:723:26)
2023-09-11T19:39:05.5212341Z     at Emitter.fire (/mnt/vss/_work/1/s/out/vs/base/common/event.js:742:22)
2023-09-11T19:39:05.5212731Z     at BufferedEmitter.fire (/mnt/vss/_work/1/s/out/vs/base/parts/ipc/common/ipc.net.js:489:35)
2023-09-11T19:39:05.5213150Z     at UniqueContainer.value (/mnt/vss/_work/1/s/out/vs/workbench/api/node/extensionHostProcess.js:173:41)
2023-09-11T19:39:05.5213548Z     at Emitter._deliver (/mnt/vss/_work/1/s/out/vs/base/common/event.js:723:26)
2023-09-11T19:39:05.5213899Z     at Emitter.fire (/mnt/vss/_work/1/s/out/vs/base/common/event.js:742:22)
2023-09-11T19:39:05.5214286Z     at BufferedEmitter.fire (/mnt/vss/_work/1/s/out/vs/base/parts/ipc/common/ipc.net.js:489:35)
2023-09-11T19:39:05.5214908Z     at MessagePortMain.<anonymous> (/mnt/vss/_work/1/s/out/vs/workbench/api/node/extensionHostProcess.js:76:55)
2023-09-11T19:39:05.5215249Z     at MessagePortMain.emit (node:events:513:28)
2023-09-11T19:39:05.5215616Z     at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

**Comment by aeschli** [comment]
This fails when reading `SyntaxKind.StringLiteral` which is a const enum and should have been inlined.

**Comment by aeschli** [comment]
Fix is to use the latest jsonc-parser which provides the enum constants not only in TypeScript source but also in the built JavaScript
