### ISSUE TITLE
Can't create new container in 1.82

### ISSUE THREAD

**Issue by GodNoden** [microsoft/vscode#192830]
Type: <b>Bug</b>

- Ctrl + Shitft + P -> New Dev Container
- Select any enviroment
- Output: 
Error: ```
Failed to download package for ghcr.io/devcontainers/templates/java-postgres
[155274 ms]     at o1 (c:\Users\noe20\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:604:6751)
[155274 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[155274 ms]     at async KeA (c:\Users\noe20\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:604:9683)
[155275 ms]     at async c:\Users\noe20\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:604:9118

```

**Comment by chrmarti** [comment]
Could you append the entire log?
