### ISSUE TITLE
Integration tests: `Error: notebook controller is DISPOSED`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192815]
This does not cause a test failure though:

https://dev.azure.com/vscode/VSCode/_build/results?buildId=103072&view=logs&j=a8a6689c-5a84-59c0-482a-7dd9f21eb2d8&t=edf7e3d3-8442-5d10-2aed-00cd86970dbb

```
2023-09-11T19:39:08.7165303Z   [32m  ✔[0m[90m cell execute command takes arguments 2[0m[31m (209ms)[0m
2023-09-11T19:39:08.7295700Z Error: notebook controller is DISPOSED
2023-09-11T19:39:08.7296670Z     at Object.createNotebookCellExecution (/mnt/vss/_work/1/s/out/vs/workbench/api/common/extHostNotebookKernels.js:192:31)
2023-09-11T19:39:08.7297575Z     at Kernel._runCell (/mnt/vss/_work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:67:32)
2023-09-11T19:39:08.7298540Z     at Kernel._execute (/mnt/vss/_work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:60:15)
2023-09-11T19:39:08.7298995Z     at ExtHostNotebookKernels.$executeCells (/mnt/vss/_work/1/s/out/vs/workbench/api/common/extHostNotebookKernels.js:330:17)
```

**Comment by DonJayamanne** [comment]
Still see these in `integration tests (Electron)`
https://dev.azure.com/vscode/VSCode/_build/results?buildId=159385&view=logs&j=23405bec-9cfd-5be8-f288-d2eb7a305a57&t=a51a9b4f-fc83-552a-726b-50518e818522&l=706
