### ISSUE TITLE
`BreadcrumbsControl.FileElement` remains even after closing editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192981]
I am using the new tool to detect disposable leaks in the workbench and I found it easiest to use keybindings for this, such as:

```json
{
    "key": "f5",
    "command": "workbench.action.startTrackDisposables"
},
{
    "key": "f6",
    "command": "workbench.action.snapshotTrackedDisposables"
},
{
    "key": "f7",
    "command": "workbench.action.stopTrackDisposables"
}
```

**Steps to Reproduce:**

0. run out of sources
1. have no editors open
2. open a file with breadcrumbs and wait for it to show
3. close the file
4. trigger `workbench.action.startTrackDisposables`
5. open the same file, wait for breadcrumbs, close the file
6. trigger `workbench.action.snapshotTrackedDisposables`
7. open the same file, wait for breadcrumbs, close the file
8. trigger `workbench.action.stopTrackDisposables`

In the editor I see many entries. These are disposables that were created at step 6. that are still present in the end and not cleaned up meanwhile:

```
==================== Leaking disposable 1/17: DisposableStore ====================
(shared with 3/17 leaks) at new DisposableStore (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:281:13)
(shared with 3/17 leaks) at new FileItem (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsControl.js:73:33)
(shared with 3/17 leaks) at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsControl.js:208:118
(shared with 3/17 leaks) at Array.map (<anonymous>)
(shared with 3/17 leaks) at UniqueContainer.updateBreadcrumbs [as value] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsControl.js:208:51)
(shared with 3/17 leaks) at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:891:26)
(shared with 3/17 leaks) at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:920:22)
(shared with 3/17 leaks) at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsModel.js:134:35
    - stacktraces of 3 other leaks continue with async Promise.all (index 0)
    - stacktraces of 4 other leaks continue with vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:1060:26
    - stacktraces of 1 other leaks continue with vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/contrib/codelens/browser/codelensController.js:135:41
    - stacktraces of 3 other leaks continue with DocumentSymbolsOutline._createOutline (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsOutline.js:299:22)
    - stacktraces of 3 other leaks continue with async UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:341:25)
============================================================
```

The `FileItem` is created here I believe:

https://github.com/microsoft/vscode/blob/d649d877f48664eee857dcb93dd4c331bd8908a1/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L305

Maybe the items are not disposed when an editor closes?

**Comment by bpasero** [comment]
There seems to be a similar one with `OutlineItem`:

```
==================== Leaking disposable 14/17: DisposableStore ====================
(shared with 1/17 leaks) at new DisposableStore (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:281:13)
(shared with 1/17 leaks) at new OutlineItem (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsControl.js:25:33)
(shared with 1/17 leaks) at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsControl.js:208:172
    - stacktraces of 3 other leaks continue with vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsControl.js:208:118
(shared with 4/17 leaks) at Array.map (<anonymous>)
(shared with 4/17 leaks) at UniqueContainer.updateBreadcrumbs [as value] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsControl.js:208:51)
(shared with 4/17 leaks) at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:891:26)
(shared with 4/17 leaks) at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:920:22)
(shared with 4/17 leaks) at UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsModel.js:136:94)
(shared with 4/17 leaks) at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:891:26)
(shared with 4/17 leaks) at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:920:22)
(shared with 4/17 leaks) at UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsOutline.js:257:43)
(shared with 4/17 leaks) at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:891:26)
(shared with 4/17 leaks) at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:920:22)
(shared with 4/17 leaks) at MarkerDecorationsService._updateDecorations (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/services/markerDecorationsService.js:73:41)
(shared with 4/17 leaks) at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/services/markerDecorationsService.js:47:26
(shared with 4/17 leaks) at Array.forEach (<anonymous>)
(shared with 4/17 leaks) at MarkerDecorationsService._handleMarkerChange (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/services/markerDecorationsService.js:44:30)
(shared with 4/17 leaks) at DebounceEmitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:891:26)
(shared with 4/17 leaks) at DebounceEmitter._deliverQueue (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:902:22)
(shared with 4/17 leaks) at DebounceEmitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:925:22)
(shared with 4/17 leaks) at DebounceEmitter.resume (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:1026:31)
(shared with 4/17 leaks) at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:1060:26
    - stacktraces of 3 other leaks continue with async Promise.all (index 0)
    - stacktraces of 1 other leaks continue with vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/contrib/codelens/browser/codelensController.js:135:41
    - stacktraces of 3 other leaks continue with DocumentSymbolsOutline._createOutline (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsOutline.js:299:22)
    - stacktraces of 3 other leaks continue with async UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:341:25)
    - stacktraces of 3 other leaks continue with vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/breadcrumbsModel.js:134:35
============================================================
```

**Comment by jrieken** [comment]
Pretty confident that this is OK. Breadcrumbs uses object pooling of rendered items because most often a very long prefix can be shared. Once updated unused items are [disposed](https://github.com/microsoft/vscode/blob/a8b25726159c5f4414012bcd292dc7fafcfce3a6/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L287)

**Comment by bpasero** [comment]
Thats fair, if these turn out not to be actual leaks, then maybe they could be marked in a way that the tracker ignores them.

**Comment by jrieken** [comment]
> then maybe they could be marked in a way that the tracker ignores them.

We can't really do that today.

**Comment by jrieken** [comment]
no plans to mark disposables as long lived, closing without action
