### ISSUE TITLE
Build: publish stage issues (Process artefacts)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193330]
Insiders today failed at this step:

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=232206&view=logs&j=43b54640-f671-5524-8f7b-714d77229de9&s=380ab8c6-4139-55ff-15c4-fb48260f4dca&t=93e2f8ab-3488-5e8e-d7d9-978a5cf7f65f&l=768

```
Asset successfully created
Processing artifact: 'vscode_web_darwin_arm64_archive-unsigned. Downloading from: https://artprodeus21.artifacts.visualstudio.com/A341001b6-62a6-4d7e-aa61-779aea3de100/a6d41577-0fa3-498e-af22-257312ff0545/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21vbmFjb3Rvb2xzL3Byb2plY3RJZC9hNmQ0MTU3Ny0wZmEzLTQ5OGUtYWYyMi0yNTczMTJmZjA1NDUvYnVpbGRJZC8yMzIyMDYvYXJ0aWZhY3ROYW1lL3ZzY29kZV93ZWJfZGFyd2luX2FybTY0X2FyY2hpdmUtdW5zaWduZWQ1/content?format=zip
Extracting artifact: '/mnt/vss/_work/_temp/vscode_web_darwin_arm64_archive-unsigned.zip'
Processing artifact with the following values:

Name                           Value
----                           -----
type                           archive-unsigned
arch                           arm64
os                             darwin
product                        web
asset                          vscode-server-darwin-arm64-web.zip

Creating asset...
Size: 59097566
SHA1: 2b1acb0f9fd4c25f2461f81d65020a5949f8c526
SHA256: a14f8423bb63af65dd544e3e20c8359a94da68a88f649803c66180758c399ed2
Uploading blobs to Azure storage (attempt 1)...
Blob successfully uploaded to Azure storage.
CredentialUnavailableError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/5aee1d83-7e4e-46a6-8aaa-1aa19b216510/v2.0/.well-known/openid-configuration
    at MsalClientSecret.handleError (/mnt/vss/_work/1/s/build/node_modules/@azure/identity/dist/index.js:452:28)
    at MsalClientSecret.doGetToken (/mnt/vss/_work/1/s/build/node_modules/@azure/identity/dist/index.js:2956:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.withSpan (/mnt/vss/_work/1/s/build/node_modules/@azure/identity/node_modules/@azure/core-tracing/dist/index.js:140:28)
    at async tryGetAccessToken (/mnt/vss/_work/1/s/build/node_modules/@azure/storage-blob/dist/index.js:14733:32)
    at async beginRefresh (/mnt/vss/_work/1/s/build/node_modules/@azure/storage-blob/dist/index.js:14741:17)
    at async StorageBearerTokenChallengeAuthenticationPolicy.sendRequest (/mnt/vss/_work/1/s/build/node_modules/@azure/storage-blob/dist/index.js:14887:28)
    at async StorageRetryPolicy.attemptSendRequest (/mnt/vss/_work/1/s/build/node_modules/@azure/storage-blob/dist/index.js:14396:24)
    at async StorageClientContext.sendOperationRequest (/mnt/vss/_work/1/s/build/node_modules/@azure/core-http/dist/index.js:4865:31)
    at async BlockBlobClient.getProperties (/mnt/vss/_work/1/s/build/node_modules/@azure/storage-blob/dist/index.js:19540:25)
Exception: /mnt/vss/_work/1/s/build/azure-pipelines/win32/exec.ps1:22
Line |
  22 |          throw ("Exec: " + $errorMessage)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exec: 
##[error]PowerShell exited with code '1'.
```

The trouble is that you cannot retrigger this step, I had noticed this already last week, it fails here:

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=232206&view=logs&j=fea29160-5990-5c88-2e93-497934de4ba6&t=c4f60be7-66be-5138-0524-9518e7249a3e&l=60

```
Creating asset...
Size: 59097566
SHA1: 2b1acb0f9fd4c25f2461f81d65020a5949f8c526
SHA256: a14f8423bb63af65dd544e3e20c8359a94da68a88f649803c66180758c399ed2
/mnt/vss/_work/1/s/build/azure-pipelines/common/createAsset.js:170
        uploadPromises.push(Promise.reject(new Error(`Blob ${quality}, ${blobName} already exists, not publishing again.`)));
                                           ^

Error: Blob insider, fa99dace5ee3b35a070ca4970422621af07c2781/vscode-server-darwin-arm64-web.zip already exists, not publishing again.
    at main (/mnt/vss/_work/1/s/build/azure-pipelines/common/createAsset.js:170:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1
Exception: /mnt/vss/_work/1/s/build/azure-pipelines/win32/exec.ps1:22
Line |
  22 |          throw ("Exec: " + $errorMessage)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exec: 
##[error]PowerShell exited with code '1'.
```

//cc @benibenj

**Comment by joaomoreno** [comment]
Not dupe, but sharing the same root cause: https://github.com/microsoft/vscode/issues/193330
