### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: /workspaces/tesi-platform/temporalio/node_modules/@prisma/client/index.d.ts linked to nonexistent file /workspaces/tesi-platform/temporalio/node_modules/.pnpm/@prisma+client@5.1.1_prisma@5.1.1/node_modules/@prisma/client/index.d.ts

### ISSUE THREAD

**Issue by pallapo** [microsoft/vscode#193345]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.2.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: /workspaces/tesi-platform/temporalio/node_modules/@prisma/client/index.d.ts linked to nonexistent file /workspaces/tesi-platform/temporalio/node_modules/.pnpm/@prisma+client@5.1.1_prisma@5.1.1/node_modules/@prisma/client/index.d.ts
    at realPath (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:42498:9)
    at getOriginalAndResolvedFileName (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:41429:28)
    at createResolvedModuleWithFailedLookupLocationsHandlingSymlink (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:41260:48)
    at nodeModuleNameResolverWorker (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:42421:10)
    at nodeModuleNameResolver (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:42358:10)
    at resolveModuleName (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:42108:18)
    at resolveModuleName2 (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:125651:27)
    at Object.resolve (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:125678:47)
    at resolveNamesWithLocalCache (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:125717:29)
    at Object.resolveModuleNameLiterals (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:125803:12)
    at ConfiguredProject2.resolveModuleNameLiterals (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:176285:33)
    at resolveModuleNamesWorker (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:120746:20)
    at resolveModuleNamesReusingOldState (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:120898:75)
    at processImportedModules (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122422:27)
    at findSourceFileWorker (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122152:7)
    at findSourceFile (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122017:20)
    at processImportedModules (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122446:11)
    at findSourceFileWorker (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122152:7)
    at findSourceFile (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122017:20)
    at processImportedModules (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122446:11)
    at findSourceFileWorker (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122152:7)
    at findSourceFile (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:122017:20)
    at /vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:121966:22
    at getSourceFileFromReferenceWorker (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:121935:26)
    at processSourceFile (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:121964:5)
    at processRootFile (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:121761:5)
    at /vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:120508:41
    at forEach (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:2352:22)
    at createProgram (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:120508:5)
    at synchronizeHostData (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:143907:15)
    at Object.getProgram (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:143981:5)
    at ConfiguredProject2.updateGraphWorker (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:176966:41)
    at ConfiguredProject2.updateGraph (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:176817:32)
    at ConfiguredProject2.updateGraph (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:178072:24)
    at updateProjectIfDirty (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:178525:35)
    at _ProjectService.assignProjectToOpenedScriptInfo (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:180785:11)
    at /vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:181062:64
    at flatMap (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:2600:17)
    at _ProjectService.applyChangesInOpenFiles (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:181062:24)
    at updateOpen (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:182242:29)
    at /vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:184838:69
    at IpcIOSession.executeWithRequestId (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:184830:14)
    at IpcIOSession.executeCommand (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:184838:29)
    at IpcIOSession.onMessage (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:184880:51)
    at process.<anonymous> (/vscode/vscode-server-insiders/bin/linux-arm64/bccfade64adb249f57c8fcf03cba41609f76ce5c-insider/extensions/node_modules/typescript/lib/tsserver.js:186461:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code - Insiders 1.83.0-insider (bccfade64adb249f57c8fcf03cba41609f76ce5c, 2023-09-15T05:38:00.328Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux arm64 5.15.49-linuxkit-pr

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 7d1dd8fd-1728-4f4a-bf43-e4202ffe87bb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: tesi imaging platform @ desktop-linux|
|OS|Linux arm64 5.15.49-linuxkit-pr|
|CPUs|unknown (4 x 0)|
|Memory (System)|7.67GB (1.69GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.1
vscode-graphql-syntax|Gra|1.2.2
Angular2|joh|16.0.1
remote-containers|ms-|0.311.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
pdf|tom|1.2.2
vscode-icons|vsc|12.5.0
vscode-todo-highlight|way|1.0.5
ng-template|Ang|16.1.8
markdown-mermaid|bie|1.19.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-drawio|hed|1.6.6
vscode-docker|ms-|1.26.0
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmhint1:30815193
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809

```

</details>

**Comment by mjbvz** [comment]
Please file this issue against pnpm
