### ISSUE TITLE
Cannot read properties of undefined (reading 'dragStartDisposable')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193648]
I closed all editor groups and settings editor was opened:

```
  ERR Cannot read properties of undefined (reading 'dragStartDisposable'): TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
    at ListView._splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:350:22)
    at ListView.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listView.js:335:29)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:1152:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:1235:23)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/list/listWidget.js:1152:32)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1072:19)
    at IndexTreeModel._setListNodeCollapseState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:266:23)
    at IndexTreeModel._setCollapseState (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:237:33)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:233:63
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:1235:23)
    at IndexTreeModel.setCollapsed (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:233:39)
    at ObjectTreeModel.setCollapsed (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:181:31)
    at TOCTree.collapseAll (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1361:24)
    at SettingsEditor2.triggerSearch (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1227:34)
    at SettingsEditor2.onSearchInputChanged (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1170:24)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:439:60
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/async.js:288:32
```

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/171041

cc @rzhao271
