### ISSUE TITLE
Explorer refresh not working for folders with same prefix

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode#19377]
- VSCode Version: 1.8.1
- OS Version: Windows 7 (64 bit)

Steps to Reproduce:

1. Ran Babel with new files in the source folder with output of new files to the output folder
2. Used the vscode explorer button to refresh, but did not see any new files in the output
3. I can the files with the windows explorer
4. If I shut down VSCODE and restart, I see the files.

File names are Counter.js, Counter.js.map

Here is the task that I am running to run Babel in watch mode:

```
{
	"version": "0.1.0",
	"command": "${workspaceRoot}/node_modules/.bin/babel.cmd",
	"isShellCommand": true,
	"tasks": [
		{
			"args": ["jsx-in", "--out-dir", "jsx", "-w", "--source-maps"],
			"taskName": "watch",
			"suppressTaskName": true,
			"isBuildCommand": true, // make this the F1 > Task: Run Build Task gesture
			"isWatching": true // tell VS Code not wait for this task to finish
		}
	]
}
```

I don't know if this is related: https://github.com/Microsoft/vscode/issues/7463

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by DrYSG** [comment]
This is the output from --verbose

```
G:\wwwroot\NodeWork>code --verbose

←[93m[main 1:46:10 PM]←[0m Starting VS Code in verbose mode
←[93m[main 1:46:10 PM]←[0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
←[93m[main 1:46:10 PM]←[0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
←[93m[main 1:46:18 PM]←[0m IPC#vscode-workbenchLoaded
[25392:0125/134623:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134623:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134623:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134623:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134623:INFO:CONSOLE(127)] "%c[Extension Host]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/e
ectron-browser/workbench.main.js (127)
[25392:0125/134623:INFO:CONSOLE(127)] "%c[Extension Host]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/e
ectron-browser/workbench.main.js (127)
[25392:0125/134623:INFO:CONSOLE(132)] "cannot open file:///g%3A/wwwroot/NodeWork/bower.json. Detail: File not found (g:\wwwroot\NodeWork\bower.json)"
 source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (132)
[25392:0125/134634:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134634:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134634:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134634:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134634:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134634:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
[25392:0125/134634:INFO:CONSOLE(93)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/elec
ron-browser/workbench.main.js (93)
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 40.84.189.107:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '40.84.189.107',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 65.55.44.109:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '65.55.44.109',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 65.55.44.109:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '65.55.44.109',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 40.84.189.107:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '40.84.189.107',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 40.84.189.107:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '40.84.189.107',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 65.55.44.109:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '65.55.44.109',
    port: 443 } ]
←[93m[main 1:47:37 PM]←[0m Lifecycle#window-before-close 1
←[93m[main 1:47:37 PM]←[0m Lifecycle#unload() 1
←[93m[main 1:47:37 PM]←[0m Lifecycle#window-before-close 1
[25392:0125/134737:INFO:CONSOLE(127)] "%c[Extension Host]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/e
ectron-browser/workbench.main.js (127)
←[93m[main 1:47:37 PM]←[0m Lifecycle#window-close 1
←[93m[main 1:47:37 PM]←[0m Lifecycle#window-all-closed
←[93m[main 1:47:37 PM]←[0m Lifecycle#before-quit
←[93m[main 1:47:37 PM]←[0m App#will-quit: disposing resources

G:\wwwroot\NodeWork>
```



This is what I get from the developer tools console. I don;t see any errors on pressing the refresh, so these were prior errors.

```
[Extension Host] WARNING: Promise with no error callback:3
extensionHost.ts:293[Extension Host] Object
shell.ts:541cannot open file:///g%3A/wwwroot/NodeWork/bower.json. Detail: File not found (g:\wwwroot\NodeWork\bower.json)e.onUnexpectedError @ shell.ts:541
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery Failed to load resource: net::ERR_TIMED_OUT
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
extensionHost.ts:293[Extension Host] ApplicationInsights:Sender Array[1]
```

**Comment by bpasero** [comment]
@DrYSG are you somehow able to share with me the workspace and how to reproduce with the exact same setup and files?

**Comment by DrYSG** [comment]
@bpasero , well if you are not hearing from others, it might have to do with the win7 and platform stuff, and not with the vscode app. But it is very easy to replicate what I have.

1. npm install babel-cli babel-reset-env babel-preset react

babel config below:

```
  "babel": {
    "presets": [
      "react",
      [
        "env",
        {
          "targets": {
            "chrome": 54
          }
        }
      ]
    ]
  }
```
Create two folders at the workspace root (jsx-in, jsx)

Put a simple hello-world.jsx in the jsx-in

Add the tasks.json to setup babel to watch the jsx-in folder (shown below)., and start it up.

touch the hello-world and save, and then watch the output folder (jsx) and you will not see vscode showing new files, but  the output and the windows explore will show new files.

```
{
	"version": "0.1.0",
	"command": "${workspaceRoot}/node_modules/.bin/babel.cmd",
	"isShellCommand": true,
	"tasks": [
		{
			"args": ["jsx-in", "--out-dir", "jsx", "-w", "--source-maps"],
			"taskName": "watch",
			"suppressTaskName": true,
			"isBuildCommand": true, // make this the F1 > Task: Run Build Task gesture
			"isWatching": true // tell VS Code not wait for this task to finish
		}
	]
}

```

**Comment by bpasero** [comment]
I can reproduce 👍

**Comment by bpasero** [comment]
To verify:
* have a simple folder with multiple folders where each have the same prefix (e.g. `jsx`, `jsx-in`)
* have some files in each and expand all
* outside vscode add/delete files in both folders
* verify you see the changes for both

Here is a video how it is broken in stable:

![panel-red](https://cloud.githubusercontent.com/assets/900690/22340560/2c7bb5b0-e3ee-11e6-96d7-ee76c312a205.gif)
