### ISSUE TITLE
Unexpected token : "file:///Use"... is not valid JSON

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193974]
I am seeing this on startup:

```
ERR Unexpected token 'i', "file:///Use"... is not valid JSON: SyntaxError: Unexpected token 'i', "file:///Use"... is not valid JSON
    at JSON.parse (<anonymous>)
    at TaskService._getFolderFromTaskKey (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tasks/browser/abstractTaskService.js:801:35)
    at TaskService.getSavedTasks (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tasks/browser/abstractTaskService.js:826:41)
    at TaskService._reconnectTasks (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tasks/browser/abstractTaskService.js:272:38)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tasks/browser/abstractTaskService.js:267:53
```

You are trying to parse a string of `"file:///Users/bpasero/Development/Microsoft/vscode|23cad063-3e4b-4931-ac2f-1aa0193c88ee|undefined"` as JSON.

![Image](https://github.com/microsoft/vscode/assets/900690/8e0c91b3-8243-4bbb-a081-b109841bc4d9)

**Comment by meganrogge** [comment]
Not sure what's going on there.... here's what I'm seeing - key is a parseable string.

![Screenshot 2023-09-29 at 2 58 52 PM](https://github.com/microsoft/vscode/assets/29464607/c6c88616-013d-47ee-bb37-2a11728e7843)

**Comment by bpasero** [comment]
Can I maybe manually clear that state, is it stored under one larger key?

**Comment by bpasero** [comment]
@meganrogge I tried this with todays insiders and the error comes back. I assume that this is a real bug not with old data but even with new data. My setup is a multi-root workspace with 3 folders:

```json
{
	"folders": [
		{
			"name": "vscode",
			"path": "vscode"
		},
		{
			"name": "vscode-distro",
			"path": "vscode-distro"
		},
		{
			"name": "vscode-docs",
			"path": "vscode-docs"
		}
	],
	"settings": {
		"files.exclude": {
			"vscode:package.json": true,
		},
		"files.associations": {
			"cglicenses.json": "jsonc"
		},
		"typescript.tsdk": "vscode/node_modules/typescript/lib",
		"emmet.excludeLanguages": [],
		"git.ignoreLimitWarning": true,
		"debug.node.autoAttach": "off"
	}
}
```

**Comment by meganrogge** [comment]
likely fixed by https://github.com/microsoft/vscode/pull/197381

**Comment by bpasero** [comment]
I still get it:

```
ERR Unexpected token 'i', "file:///Use"... is not valid JSON: SyntaxError: Unexpected token 'i', "file:///Use"... is not valid JSON
    at JSON.parse (<anonymous>)
    at x.bc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1943:11586)
    at x.getSavedTasks (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1943:12044)
    at x.Ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1943:4009)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1943:3926
```

**Comment by bpasero** [comment]
Can you please just put a try/catch around it, it blocks my ability to use tasks at work :-/

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/198924

**Comment by meganrogge** [comment]
Thanks @bpasero
