### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#193957]
* open a file from a pull request
* get an error saying id cannot be read from undefined

```
ERR Cannot read properties of undefined (reading 'id'): TypeError: Cannot read properties of undefined (reading 'id')
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:765:140066
    at Object.h [as map] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:12:10432)
    at h.next (<anonymous>)
    at P (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7:2275)
    at r.setActions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:765:140001)
    at d.Z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2412:20205)
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2412:20897)
    at b.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at b.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at b.resume (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:3188)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:3469
```

**Comment by jrieken** [comment]
this is a regression from https://github.com/microsoft/vscode/issues/193723

**Comment by DonJayamanne** [comment]
Yes, I too saw this when testing day before yesterday, but as soon as I updated this went away.
