### ISSUE TITLE
Chat view  `ERR Error: Invalid range: [1, 0)`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194373]
In one of my workspaces I see no more chat. The console shows the stacktraces below, the debugger stops like this

<img width="1302" alt="Screenshot 2023-09-28 at 10 26 44" src="https://github.com/microsoft/vscode/assets/1794099/0940db42-526f-4ac8-9066-78bf2ce5035c">

```
ERR Error: Invalid range: [1, 0)
    at new k (offsetRange.ts:48:10)
    at c.G (chatModel.ts:538:42)
    at chatModel.ts:525:65
    at Array.map (<anonymous>)
    at c.F (chatModel.ts:524:19)
    at new c (chatModel.ts:504:39)
    at g.j (instantiationService.ts:119:18)
    at g.createInstance (instantiationService.ts:85:18)
    at O (chatServiceImpl.ts:325:43)
    at O.getOrRestoreSession (chatServiceImpl.ts:404:15)
    at s.U (chatViewPane.ts:114:54)
    at s.render (paneview.ts:267:9)
    at s.render (viewPane.ts:286:9)
    at R.rb (viewPaneContainer.ts:778:9)
    at u.value (viewPaneContainer.ts:532:87)
    at c.z (event.ts:1138:13)
    at c.A (event.ts:1149:9)
    at c.fire (event.ts:1173:9)
    at b.I (viewContainerModel.ts:661:41)
    at b.H (viewContainerModel.ts:656:8)
    at u.value (viewContainerModel.ts:361:118)
    at c.z (event.ts:1138:13)
    at c.fire (event.ts:1169:9)
    at u.value (event.ts:152:97)
    at l.z (event.ts:1138:13)
    at l.A (event.ts:1149:9)
    at l.fire (event.ts:1173:9)
    at l.fire (event.ts:1335:11)
    at s.setContext (contextKeyService.ts:345:29)
    at u.reset (contextKeyService.ts:214:18)
    at new u (contextKeyService.ts:203:8)
    at s.createKey (contextKeyService.ts:290:10)
    at w (contextKeyService.ts:599:20)
    at g.invokeFunction (instantiationService.ts:68:11)
    at y.n (commandService.ts:95:46)
    at y.executeCommand (commandService.ts:60:17)
    at p.$executeCommand (mainThreadCommands.ts:91:31)
    at m.S (rpcProtocol.ts:456:17)
    at m.Q (rpcProtocol.ts:441:32)
    at m.M (rpcProtocol.ts:371:19)
    at m.L (rpcProtocol.ts:297:10)
    at u.value (rpcProtocol.ts:161:42)
    at c.z (event.ts:1138:13)
    at c.fire (event.ts:1169:9)
    at r.fire (ipc.net.ts:650:19)
    at Y.onmessage (localProcessExtensionHost.ts:581:40)
log.ts:441   ERR Invalid range: [1, 0): Error: Invalid range: [1, 0)
    at new k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:32662)
    at c.G (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1575:1173)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1575:827
    at Array.map (<anonymous>)
    at c.F (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1575:779)
    at new c (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1575:326)
    at g.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:640:1241)
    at g.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:640:733)
    at O (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1576:8061)
    at O.getOrRestoreSession (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1576:9336)
    at s.U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2551:20103)
    at s.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:65895)
    at s.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1669:11445)
    at R.rb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2537:37565)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2537:34403)
    at c.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.A (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at c.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at b.I (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2321:122034)
    at b.H (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2321:122006)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2321:116441)
    at c.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:49477)
    at l.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at l.A (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:3317)
    at s.setContext (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:638:35504)
    at u.reset (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:638:33917)
    at new u (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:638:33812)
    at s.createKey (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:638:34811)
    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:638:38446)
    at g.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:640:326)
    at y.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1528:12391)
    at y.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1528:11979)
    at p.$executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1537:552)
    at m.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1551:18856)
    at m.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1551:18622)
    at m.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1551:17715)
    at m.L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1551:16794)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1551:15597)
    at c.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:616:14335)
    at Y.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1652:1077)
```

**Comment by roblourens** [comment]
omg, 1-indexed vs 0-indexed ranges... That is the fix, thanks for saving me from candidate shame

**Comment by roblourens** [comment]
This would happen when a request body is empty. But probably the only way you would get in that state is if you had a session that was broken due to the issue that my original commit was fixing, which was broken chat session serialization. So I think the only way to verify it really is to check the window where you noticed the original issue. Or we can call it verified by code review.

**Comment by bhavyaus** [comment]
verified by code review
