### ISSUE TITLE
Pending comments in a thread are restored as new threads

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#194317]
Testing #193104

1. Have a PR comment
2. Reply to the PR comment, do not submit it 
3. Transfer that state to a different machine or reset your local state and then restore changes from cloud
4. :bug: the PR comment shows up as a new discussion thread rather than a reply to the existing comment

**Comment by alexr00** [comment]
Will be fixed by https://github.com/microsoft/vscode/pull/195260

**Comment by andreamah** [comment]
For this step:
> Reply to the PR comment, do not submit it

Does this mean to type the comment in the text box, but don't do anything further than that?

**Comment by andreamah** [comment]
Given that my assumption above is correct, when restoring the edit session on a codespace, I didn't see the comment in the text box.

Repro:
1. type a comment in a text box, don't submit/add it.
2. store the edit session.
3. connect to a codespace via vscode desktop that has the same repo.
4. restore the edit session.
5. comment isn't there :bug:

Logs:
```
2023-10-27 09:08:53.784 [info] Resuming cloud changes, reason: cloud changes enabled...
2023-10-27 09:08:53.784 [info] Checking for pending cloud changes...
2023-10-27 09:08:54.343 [info] Resuming cloud changes, reason: cloud changes enabled...
2023-10-27 09:08:54.556 [info] Searching for existing authentication session with ID 5506e18dca9e843b
2023-10-27 09:09:00.350 [info] Found existing authentication session with ID 5506e18dca9e843b
2023-10-27 09:09:00.868 [info] Checking for pending cloud changes...
2023-10-27 09:09:01.572 [info] Matching identity {"remote":"https://github.com/andreamah/dendron-notes.git","ref":"main","sha":"d9f27527217c9a7acdae55997b138faad72fd974"} against edit session folder identity {"remote":"https://github.com/andreamah/simple-web-proj","ref":"test1","sha":"6f57b50360910b461a7f9212abcbdebb0930cf89"}...
2023-10-27 09:09:01.574 [info] Skipping applying 1 changes from edit session with ref d26dd529-ecd7-49aa-a421-7b1048300463 as no matching workspace folder was found.
2023-10-27 09:09:01.976 [info] Resuming cloud changes, reason: cloud changes enabled...
2023-10-27 09:09:02.140 [info] Searching for existing authentication session with ID 5506e18dca9e843b
2023-10-27 09:09:17.070 [info] Resuming cloud changes, reason: cloud changes enabled...
2023-10-27 09:09:17.070 [info] Checking for pending cloud changes...
2023-10-27 09:09:17.070 [info] Searching for existing authentication session with ID 5506e18dca9e843b
2023-10-27 09:09:18.981 [info] Found existing authentication session with ID 5506e18dca9e843b
2023-10-27 09:09:20.572 [info] Matching identity {"remote":"https://github.com/andreamah/simple-web-proj","ref":"test1","sha":"6f57b50360910b461a7f9212abcbdebb0930cf89"} against edit session folder identity {"remote":"https://github.com/andreamah/simple-web-proj","ref":"test1","sha":"6f57b50360910b461a7f9212abcbdebb0930cf89"}...
2023-10-27 09:09:21.671 [info] Found existing authentication session with ID 5506e18dca9e843b
2023-10-27 09:09:22.107 [info] Matching identity {"remote":"https://github.com/andreamah/simple-web-proj","ref":"test1","sha":"6f57b50360910b461a7f9212abcbdebb0930cf89"} against edit session folder identity {"remote":"https://github.com/andreamah/simple-web-proj","ref":"test1","sha":"6f57b50360910b461a7f9212abcbdebb0930cf89"}...
2023-10-27 09:09:22.579 [info] Deleting edit session with ref d26dd529-ecd7-49aa-a421-7b1048300463 after successfully applying it to current workspace...
2023-10-27 09:09:22.751 [info] Deleted edit session with ref d26dd529-ecd7-49aa-a421-7b1048300463.
2023-10-27 09:09:39.739 [info] Storing edit session...
2023-10-27 09:10:07.788 [info] Stored edit session with ref a1b55215-4a43-4ad3-a295-8f6ed981675a.
2023-10-27 09:11:02.351 [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/workspaceState/7aa6efba-8b2f-4267-a803-3aa933b7bb9f","status":404,"execution-id":"5463f99c-8280-49a8-a092-7a68ab0e971a"} Not Found
2023-10-27 09:11:02.352 [error] NotFound (UserDataSyncError) syncResource:unknown operationId:unknown: GET request 'https://vscode-sync.trafficmanager.net/v1/resource/workspaceState/7aa6efba-8b2f-4267-a803-3aa933b7bb9f' failed because the requested resource is not found (404).
    at S.D (vscode-file://vscode-app/c:/Users/andreamah/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:767:73679)
    at async S.resolveResourceContent (vscode-file://vscode-app/c:/Users/andreamah/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:767:68631)
    at async b.read (vscode-file://vscode-app/c:/Users/andreamah/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1544:56450)
    at async u.apply (vscode-file://vscode-app/c:/Users/andreamah/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:58707)
    at async Ie.resumeEditSession (vscode-file://vscode-app/c:/Users/andreamah/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:69746)
    at async vscode-file://vscode-app/c:/Users/andreamah/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2616:63172
2023-10-27 09:11:02.353 [info] Deleting edit session with ref d26dd529-ecd7-49aa-a421-7b1048300463 after successfully applying it to current workspace...
2023-10-27 09:11:02.504 [info] Deleted edit session with ref d26dd529-ecd7-49aa-a421-7b1048300463.
2023-10-27 09:11:52.705 [info] Checking for pending cloud changes...
2023-10-27 09:11:53.059 [info] Matching identity {"remote":"https://github.com/andreamah/simple-web-proj","ref":"test1","sha":"6f57b50360910b461a7f9212abcbdebb0930cf89"} against edit session folder identity {"remote":"https://github.com/andreamah/simple-web-proj","ref":"test1","sha":"6f57b50360910b461a7f9212abcbdebb0930cf89"}...
2023-10-27 09:12:48.338 [info] Deleting edit session with ref a1b55215-4a43-4ad3-a295-8f6ed981675a after successfully applying it to current workspace...
2023-10-27 09:12:48.578 [info] Deleted edit session with ref a1b55215-4a43-4ad3-a295-8f6ed981675a.
```

**Comment by andreamah** [comment]
Nevermind, I noticed that the title of the issue says "Pending comments". Pending comments get restored fine.
