### ISSUE TITLE
computeDiff throws 'Illegal Value for LineNumber'

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#194469]
Observed this error in dev console 

```
  ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at U.getLineMaxColumn (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:731:116)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1069:13046
    at E (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:12:8975)
    at C.computeDiff (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1069:12382)
```

I was rebasing my branch on main if that matters and had a conflict opened in normal editor (ie not merge editor) 

```
Version: 1.83.0-insider
Commit: ba36ae4dcca57ba64a9b61e5f4eca88b6e0bc4db
Date: 2023-09-29T02:08:02.965Z
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by hediet** [comment]
https://github.com/microsoft/vscode/blob/4ab7cb4bade896b017c65571541f888889153fc0/src/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.ts#L86-L88

I think this is because the text model changed in the meantime.
