### ISSUE TITLE
Visual bugs after creating new terminal and adjusting secondary sidebar size

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#194438]
Type: <b>Bug</b>

Was looking at a terminal splitview, added a new terminal, and then resized my secondary sidebar. 

Initial realization that something was wrong came when I was getting incorrect rendering of currently active terminals at the upper right of the terminal view. (see small sc below)

logs from devtools are attached. 

<img width="115" alt="image" src="https://github.com/microsoft/vscode/assets/12552271/a98158ea-7367-4ef1-9d23-59582a29e44c">

<img width="2223" alt="image" src="https://github.com/microsoft/vscode/assets/12552271/4e1e025d-c2bd-4975-b00e-e47b430fbbe0">

```
console.ts:137 [Extension Host] (node:11200) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created) (at c:\Users\milively\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:112570)
$ @ console.ts:137
log.ts:441   ERR Cannot read properties of undefined (reading 'dimensions'): TypeError: Cannot read properties of undefined (reading 'dimensions')
    at get dimensions [as dimensions] (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:101930)
    at f.getFont (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2655:13914)
    at V.getFont (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1866:15868)
    at we.Cc (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:236224)
    at we.zc (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:235862)
    at we.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2559:1524)
    at i.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:213182)
    at o.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:18147)
    at n.U (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:30214)
    at n.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:23608)
    at h.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:212308)
    at d.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:217524)
    at vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1931:51034
    at Array.forEach (<anonymous>)
    at Object.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1931:51021)
    at o.layout (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:18147)
    at n.U (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:30214)
    at n.Q (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:28549)
    at n.removeView (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:21891)
    at m.R (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1931:49799)
    at u.value (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1931:49143)
    at c.z (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.A (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at c.fire (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at c.z (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at d.setActiveInstanceByIndex (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:216143)
    at d.O (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:215347)
    at d.N (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:215145)
    at u.value (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:214963)
    at c.z (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.A (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at c.fire (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at we.dispose (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558:852)
    at HTMLTextAreaElement.<anonymous> (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2558:7919)
log.ts:441   ERR Cant modify splitview: Error: Cant modify splitview
    at n.P (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:26689)
    at n.addView (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:227:21449)
    at m.ab (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1931:51207)
    at m.R (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1931:49686)
    at u.value (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1931:49143)
    at c.z (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.A (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at c.fire (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at c.z (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at d.addInstance (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:214387)
    at d.split (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2556:217224)
    at K.Zb (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2655:35762)
    at K.createTerminal (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2655:34510)
    at async R.Cb (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:16823)
    at async R.Fb (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:19557)
    at async R.xb (vscode-file://vscode-app/c:/Users/milively/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:8624)
    at async Promise.all (index 1)
```

VS Code version: Code - Insiders 1.83.0-insider (623feb6ddd360d97dc77e2ff577dd2c549ef442d, 2023-09-28T11:51:23.482Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (12.94GB free)|
|Process Argv|--crash-reporter-id 1cb7488a-bb2c-46a8-ac2f-3151dbb5b996|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tsl-problem-matcher|amo|0.6.2
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.20.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
gitlens|eam|2023.9.2805
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
copilot|Git|1.119.450
copilot-chat|Git|0.8.2023092701
remotehub|Git|0.61.2023092801
vscode-pull-request-github|Git|0.73.2023092809
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
theme-monokai-pro-vscode|mon|1.2.1
vscode-docker|ms-|1.26.1
remote-containers|ms-|0.314.0
remote-ssh|ms-|0.107.2023092715
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.6
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.37.2023092801
live-server|ms-|0.4.9
remote-explorer|ms-|0.5.2023092809
remote-repositories|ms-|0.39.2023092801
remote-server|ms-|1.5.2023092809
test-adapter-converter|ms-|0.1.8
vscode-github-issue-notebooks|ms-|0.0.130
vscode-selfhost-test-provider|ms-|0.3.18
vscode-typescript-next|ms-|5.3.20230927
vsliveshare|ms-|1.0.5883
markdown-preview-enhanced|shd|0.7.10
vscode-status-bar-format-toggle|tom|3.1.1
pdf|tom|1.2.2
pretty-ts-errors|yoa|0.5.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
synctok:30821570
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttype:30823781
pythonmypyww:30841056
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1cf:30841191
pythoncet0:30848247

```

</details>

**Comment by Tyriar** [comment]
Looks like this is also happening in integration tests: https://github.com/microsoft/vscode/issues/192816
