### ISSUE TITLE
Problem matcher only matches on restored PTY

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#194501]
I'm trying to fix an issue Alex mentioned (linked in a comment to this issue) by updating the esbuild problem matchers and am running into a very frustrating problem.

1. Have these problem matches (on main) https://github.com/connor4312/esbuild-problem-matchers
2. Run an esbuild task that produces errors
3. Notice no task errors are detected
4. Reload the window
5. Notice the task terminal is restored and problems are now reported

A naive guess is that esbuild lines are not coming all in a single terminal write and tasks don't match regexes correctly when that happens

**Comment by meganrogge** [comment]
do you know when this bug appeared? IE do you think it's a regression?

**Comment by meganrogge** [comment]
Thanks, not sure when I'll get to this honestly. I'll try for October

**Comment by hediet** [comment]
This is still so annoying...

![Image](https://github.com/microsoft/vscode/assets/2931520/e123f80d-d968-4594-a27e-5bf0ae570565)

**Comment by hediet** [comment]
I have to do it every second time:

![Image](https://github.com/microsoft/vscode/assets/2931520/ce82498c-1d58-4977-ac0c-ed43ab005a0f)

**Comment by alexdima** [comment]
@meganrogge I'm still running into this while selfhosting. Are you able to repro? I've added up-to-date repro steps at https://github.com/microsoft/vscode-copilot/issues/18332

**Comment by meganrogge** [comment]
Yes, I have seen this happen. It's not a consistent repro though.

https://github.com/user-attachments/assets/2d1a0efd-1394-40d2-af82-e67e1a51acd7

**Comment by meganrogge** [comment]
Output that isn't matched sometimes (until window reload):

```
[watch] build finished
File change detected: /Users/meganrogge/Repos/vscode-copilot/src/platform/networking/node/stream.ts
[watch] build started
✘ [ERROR] Invalid assignment target

    src/platform/networking/node/stream.ts:266:6:
      266 │             this.cancellationToken?.isCancellation...
          ╵             ^

1 error
[watch] Error: Build failed with 1 error:
src/platform/networking/node/stream.ts:266:6: ERROR: Invalid assignment target
    at failureErrorWithLog (/Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:1463:15)
    at /Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:924:25
    at runOnEndCallbacks (/Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:1303:45)
    at buildResponseToResult (/Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:922:7)
    at /Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:934:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:933:54)
    at handleRequest (/Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:626:17)
    at handleIncomingPacket (/Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:651:7)
    at Socket.readFromStdout (/Users/meganrogge/Repos/vscode-copilot/node_modules/esbuild/lib/main.js:579:7) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

**Comment by meganrogge** [comment]
@connor4312 could this `onRebuild` property have something to do with this?

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/f9780183-3b6a-46b1-8296-48e8c4f18e6c" />
