### ISSUE TITLE
terminal overlaid on terminal tabs

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#194626]
1. have two split terminals
2. run `exit 1` in the right terminal
3. 🐛 terminal xterm element overlaid upon terminal tabs

![Image](https://github.com/microsoft/vscode/assets/29464607/33fcce4c-0b34-4214-a5a3-227caeb73872)

```
  ERR Cannot read properties of undefined (reading 'dimensions'): TypeError: Cannot read properties of undefined (reading 'dimensions')
    at get dimensions [as dimensions] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:101930)
    at f.getFont (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2655:13914)
    at V.getFont (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1866:15868)
    at we.Cc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:236224)
    at we.zc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:235862)
    at we.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2559:1524)
    at i.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:213182)
    at o.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:18147)
    at n.U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:30214)
    at n.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:23608)
    at h.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:212308)
    at d.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:217524)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:51034
    at Array.forEach (<anonymous>)
    at Object.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:51021)
    at o.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:18147)
    at n.U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:30214)
    at n.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:28549)
    at n.removeView (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:227:21891)
    at m.R (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:49799)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:49143)
    at c.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.A (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at c.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at c.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at d.setActiveInstanceByIndex (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:216143)
    at d.O (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:215347)
    at d.N (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:215145)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2556:214963)
    at c.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.A (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at c.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at we.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2558:852)
    at we.Pc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders%2015.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2558:6712)
```

**Comment by meganrogge** [comment]
Resizing fixed it

**Comment by meganrogge** [comment]
in the `RenderService`, `this._renderer.value.dimensions` is called, but there's a check for if `this._renderer.value` is undefined before that, so not sure how this is possible

**Comment by meganrogge** [comment]
![Screenshot 2023-10-02 at 10 16 29 AM](https://github.com/microsoft/vscode/assets/29464607/5455ac02-a42c-4053-987a-1b584243cf87)

```
splitview.ts:1009 Uncaught Error: Cant modify splitview
    at n.resizeView (splitview.ts:1009:10)
    at m.layout (terminalTabbedView.ts:320:20)
    at B.W (terminalView.ts:234:29)
    at B.layout (paneview.ts:284:9)
    at o.layout (splitview.ts:278:13)
    at n.U (splitview.ts:1331:13)
    at n.layout (splitview.ts:854:8)
    at u.layout (paneview.ts:566:18)
    at R.layout (viewPaneContainer.ts:628:18)
    at O.layout (panecomposite.ts:55:27)
    at G.layout (compositePart.ts:487:25)
    at G.layout (panelPart.ts:699:9)
    at G.layout (panelPart.ts:1008:9)
    at n.y (gridview.ts:901:13)
    at n.layout (gridview.ts:884:8)
    at f.layout (splitview.ts:278:13)
    at n.U (splitview.ts:1331:13)
    at n.layout (splitview.ts:854:8)
    at c.layout (gridview.ts:487:18)
    at o.layout (splitview.ts:278:13)
    at n.U (splitview.ts:1331:13)
    at n.layout (splitview.ts:854:8)
    at c.layout (gridview.ts:487:18)
    at f.layout (splitview.ts:278:13)
    at n.U (splitview.ts:1331:13)
    at n.layout (splitview.ts:854:8)
    at c.layout (gridview.ts:487:18)
    at l.layout (gridview.ts:1165:13)
    at r.layout (grid.ts:334:17)
    at r.layout (grid.ts:803:9)
    at R.layout (layout.ts:1394:23)
    at fe.ob (window.ts:542:23)
    at window.ts:136:76
```

**Comment by meganrogge** [comment]
the above is the same error as https://github.com/microsoft/vscode/issues/192668

**Comment by meganrogge** [comment]
Unclear if the error with the dimensions leads to the error with the split view or the other way around 🤔
