### ISSUE TITLE
Search fails in folders having curly brackets groups in folder name (ie. '/{{cookiecutter.package_name}}')

### ISSUE THREAD

**Issue by tadams42** [microsoft/vscode#194701]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.3
- OS Version: Ubuntu 22.04.3 LTS

Steps to Reproduce:

1. create directory: `mkdir -p "foo/{{cookiecutter.package_name}}"`
2. add searchable file to new directory: `echo baz > "foo/{{cookiecutter.package_name}}/bar"`
3. start VSCode with all extensions disabled: `code --disable-extensions`
4. add created folder to VSCode: `code --add foo`
5. right click on `{{cookiecutter.package_name}}`, `Find in Folder...`
6. Enter "baz" into search field
7. Error appears: `Error parsing glob '/{{cookiecutter.package_name}}': nested alternate groups are not allowed`

Detailed VSCode and OS versions:

```
$ code --version
1.82.3
fdb98833154679dbaa7af67a5a29fe19e55c2b73
x64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

`Output` -> `Window`:

```log
2023-10-03 12:25:54.724 [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"/tmp/foo","external":"file:///tmp/foo","path":"/tmp/foo","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/Thumbs.db":true,".coverage":true,".coverage.*":true,"*.ipynb":true,"*.pos":true,"**/__pycache__":true,"**/.antlr/":true,"**/.benchmarks/":true,"**/.cache":true,"**/.cassandraWorkbench/":true,"**/.directory":true,"**/.dockerized_mongo_data/":true,"**/.eggs":true,"**/.external_pip_packages/":true,"**/.git/":true,"**/.hg/":true,"**/.idea/":true,"**/.ipynb_checkpoints":true,"**/.mypy_cache/":true,"**/.pyre/":true,"**/.pytest_cache/":true,"**/.pytype/":true,"**/.ruff_cache/":true,"**/.tox/":true,"**/.vagrant/":true,"**/.venv/":true,"**/.venv1/":true,"**/.venv2/":true,"**/.venv3/":true,"**/.vscode/":true,"**/*.a":true,"**/*.class":true,"**/*.egg-info":true,"**/*.log":true,"**/*.o":true,"**/*.pyc":true,"**/*.so":true,"**/build/":true,"**/dist/":true,"**/docs/_build/":true,"**/downloaded_deps/":true,"**/exported_data/":true,"**/htmlcov/":true,"**/libsokoengine/lib/":true,"**/metastore_db/":true,"**/spark_root/":true,"**/spark-warehouse/":true,"**/vendor/":true,"coverage.xml":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"disregardParentIgnoreFiles":true,"ignoreSymlinks":true,"includePattern":{"{{cookiecutter.package_name}}":true,"{{cookiecutter.package_name}}/**":true}}],"usingSearchPaths":true,"onlyOpenEditors":false,"maxResults":20000,"type":2,"contentPattern":{"pattern":"baz","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"notebookInfo":{"isInNotebookMarkdownInput":true,"isInNotebookMarkdownPreview":true,"isInNotebookCellInput":true,"isInNotebookCellOutput":true},"wordSeparators":"/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?-"},"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}
2023-10-03 12:25:54.735 [trace] SearchService#search: 8ms
2023-10-03 12:25:54.735 [trace] SearchService#searchError: Error parsing glob '/{{cookiecutter.package_name}}': nested alternate groups are not allowed
2023-10-03 12:25:54.747 [error] Error parsing glob '/{{cookiecutter.package_name}}': nested alternate groups are not allowed: Error: Error parsing glob '/{{cookiecutter.package_name}}': nested alternate groups are not allowed
    at P (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1847:5809)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1855:4351
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1855:2921
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1855:2313
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2280:25170
```

Tested also in insiders build on the web. 
In insiders build, no error appears, but search term `baz` is not found (and it should be found).

**Comment by andreamah** [comment]
This is interpreted as a nested alternate group, which is why that doesn't work. I'll keep this issue open as a way to potentially escape braces.
