### ISSUE TITLE
Cannot run out of sources anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#194790]
```
✨  Done in 0.35s.
[12:40:09] Synchronizing built-in extensions...
[12:40:09] You can manage built-in extensions with the --builtin flag
[12:40:09] [github] ms-vscode.js-debug-companion@1.1.2 ✔︎
[12:40:09] Downloading extension from GH: ms-vscode.js-debug@1.83.0 ...
[12:40:09] [github] ms-vscode.vscode-js-profile-table@1.0.3 ✔︎
/Users/bpasero/Development/Microsoft/vscode-electron-20.x/build/lib/fetch.js:77
            throw new Error(`Request ${ansiColors.magenta(url)} failed with status code: ${response.status}`);
                  ^

Error: Request https://api.github.com/repos/microsoft/vscode-js-debug/releases/tags/v1.83.0 failed with status code: 403
    at fetchUrl (/Users/bpasero/Development/Microsoft/vscode-electron-20.x/build/lib/fetch.js:77:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Stream instance at:
    at Stream.onerror (node:internal/streams/legacy:62:12)
    at Stream.emit (node:events:514:28)
    at Stream.emit (node:domain:489:12)
    at next (/Users/bpasero/Development/Microsoft/vscode-electron-20.x/node_modules/map-stream/index.js:75:19)
    at /Users/bpasero/Development/Microsoft/vscode-electron-20.x/node_modules/map-stream/index.js:85:7
    at /Users/bpasero/Development/Microsoft/vscode-electron-20.x/build/lib/fetch.js:30:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1
~/Development/Microsoft/vscode-electron-20.x> 
```

**Comment by bpasero** [comment]
I was GH rate limited, would be nice if the error indicates that.
