### ISSUE TITLE
Terminal is broken

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19480]
- VSCode Version: From source commit 6fba7f3
- OS Version: Windows

Steps to Reproduce:

1. Open VS Code using code.bat
2. Try to open a terminal using View -> Integrated Terminal

You get:
```
[19504:0127/090725:INFO:CONSOLE(84)] "No option with key "useFlowControl": Error: No option with key "useFlowControl"
    at Terminal.getOption (P:\mseng\VSCode\vscode\node_modules\xterm\lib\xterm.js:208:15)
    at TerminalInstance._setFlowControl (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:498:44)
    at TerminalInstance.updateConfig (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:491:18)
    at TerminalInstance.attachToElement (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:186:18)
    at new TerminalInstance (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:54:22)
    at create (file:///P:/mseng/VSCode/vscode/out/vs/base/common/types.js:163:14)
    at InstantiationService._createInstance (file:///P:/mseng/VSCode/vscode/out/vs/platform/instantiation/common/instantiationService.js:142:43)
    at InstantiationService.createInstance (file:///P:/mseng/VSCode/vscode/out/vs/platform/instantiation/common/instantiationService.js:70:29)
    at TerminalService.createInstance (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalService.js:78:63)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:72:48", source: file:///P:/mseng/VSCode/vscode/out/vs/workbench/services/message/browser/messageService.js (84)
```

**Comment by dbaeumer** [comment]
Fixed after npm install.
