### ISSUE TITLE
error on first IntilliSense invocation

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19493]
* open new document
* type something
* an error is printed to the console

```
Cannot read property 'isBefore' of null: TypeError: Cannot read property 'isBefore' of null
    at SuggestModel.onCursorChange (file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/suggest/common/suggestModel.js:198:36)
    at file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/suggest/common/suggestModel.js:86:23
    at file:////Users/jrieken/Code/vscode/out/vs/base/common/event.js:184:26
    at safeInvoke1Arg (file:////Users/jrieken/Code/vscode/out/vs/base/common/eventEmitter.js:255:20)
    at CodeEditor.EventEmitter._emitToSpecificTypeListeners (file:////Users/jrieken/Code/vscode/out/vs/base/common/eventEmitter.js:140:21)
    at CodeEditor.EventEmitter._emitEvents (file:////Users/jrieken/Code/vscode/out/vs/base/common/eventEmitter.js:156:22)
    at CodeEditor.EventEmitter.emit (file:////Users/jrieken/Code/vscode/out/vs/base/common/eventEmitter.js:170:22)
    at file:////Users/jrieken/Code/vscode/out/vs/editor/common/commonCodeEditor.js:667:39
    at safeInvoke1Arg (file:////Users/jrieken/Code/vscode/out/vs/base/common/eventEmitter.js:255:20)
    at Cursor.EventEmitter._emitToBulkListeners (file:////Users/jrieken/Code/vscode/out/vs/base/common/eventEmitter.js:147:17)
```

**Comment by dbaeumer** [comment]
Verified on master build from source.
