### ISSUE TITLE
notebook editor is blank

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#195016]
I was working with a notebook, switched tabs, and tried to switch back, now the editor is blank and my progress with the notebook is lost.

this seems to repro every time.

```
Error: Line numbers must be >= 1
    at ba.originalPositionFor (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:25:88869)
    at mE.originalPositionFor (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:82:8901)
    at c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:9450
    at Ta.guardSourceMapFn (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:94:6048)
    at pc.guardSourceMapFn (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:94:4646)
    at hr.getOptiminalOriginalPosition (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:9418)
    at hr._originalPositionForMap (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:8308)
    at hr._originalPositionFor (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:7846)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at hr.preferredUiLocation (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:6900)
    at c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:119:2825
    at async Promise.all (index 4)
    at Jt.scopes (c:\Users\aamunger\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug\src\extension.js:119:2020) 
```

**Comment by amunger** [comment]
stack is irrelevant, the issue can repro without any errors
