### ISSUE TITLE
Markdown outline throws

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19502]
When running Markdown outline on the smoke test readme.md, there is an exception in the console: https://raw.githubusercontent.com/Microsoft/vscode-smoketest-express/master/readme.md

```
Cannot read property 'references' of undefined: TypeError: Cannot read property 'references' of undefined
    at Array.reference (/usr/share/code-insiders/resources/app/extensions/markdown/node_modules/markdown-it/lib/rules_block/reference.js:182:23)
    at ParserBlock.tokenize (/usr/share/code-insiders/resources/app/extensions/markdown/node_modules/markdown-it/lib/parser_block.js:79:20)
    at ParserBlock.parse (/usr/share/code-insiders/resources/app/extensions/markdown/node_modules/markdown-it/lib/parser_block.js:118:8)
    at Array.block (/usr/share/code-insiders/resources/app/extensions/markdown/node_modules/markdown-it/lib/rules_core/block.js:14:20)
    at Core.process (/usr/share/code-insiders/resources/app/extensions/markdown/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/usr/share/code-insiders/resources/app/extensions/markdown/node_modules/markdown-it/lib/index.js:519:13)
    at MarkdownEngine.parse (/usr/share/code-insiders/resources/app/extensions/markdown/out/markdownEngine.js:65:28)
    at MDDocumentSymbolProvider.provideDocumentSymbols (/usr/share/code-insiders/resources/app/extensions/markdown/out/documentSymbolProvider.js:12:34)
    at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:18875
    at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9460
```

**Comment by joaomoreno** [comment]
The snippet that breaks it is:

```
[![TJ's Gratipay][gratipay-image-visionmedia]][gratipay-url-visionmedia]
```

**Comment by mjbvz** [comment]
I believe either #19417 fixed this by upgrading markdown it. #19411 also added some error handling for exceptions in markdown it
