### ISSUE TITLE
`yarn` fails on fresh clone of `vscode` in WSL2

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#195106]
Type: <b>Bug</b>

1. Clone `vscode` in WSL2.
2. Run `yarn`.

# Expected results
`yarn` completes successfully.

# Actual results
`yarn` fails.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (10.48GB free)|
|Process Argv|--crash-reporter-id 1fd71fd7-86f6-44c1-b5cb-45bbb457a8c1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4007)|
|Memory (System)|15.47GB (9.51GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4007)|
|Memory (System)|15.47GB (9.51GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.315.1
remote-wsl|ms-|0.81.7
vscode-tailwindcss|bra|0.10.0
vscode-eslint|dba|2.4.2
vscode-axe-linter|deq|4.7.4
gitlens|eam|14.3.0
prettier-vscode|esb|10.1.0
copilot|Git|1.123.0
copilot-chat|Git|0.8.0
vscode-github-actions|git|0.26.2
mypy|mat|0.2.3
autopep8|ms-|2023.6.0
pylint|ms-|2023.8.0
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-css-peek|pra|4.4.1
vs-code-prettier-eslint|rve|5.1.0
code-spell-checker|str|3.0.1
vscode-webhint|web|2.1.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by hamirmahal** [comment]
```
hamir@WSL2:~/repositories/vscode (main)$  pkg-config --version
0.29.2
hamir@WSL2:~/repositories/vscode (main)$  sudo apt-get install fakeroot rpm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fakeroot is already the newest version (1.28-1ubuntu1).
rpm is already the newest version (4.17.0+dfsg1-4build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hamir@WSL2:~/repositories/vscode (main)$  sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
g++ is already the newest version (4:11.2.0-1ubuntu1).
libsecret-1-dev is already the newest version (0.20.5-2).
libxkbfile-dev is already the newest version (1:1.1.0-1build3).
python-is-python3 is already the newest version (3.9.2-2).
libkrb5-dev is already the newest version (1.19.2-2ubuntu0.2).
libx11-dev is already the newest version (2:1.7.5-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hamir@WSL2:~/repositories/vscode (main)$  sudo apt install python3 python-is-python3 libsecret-1-dev libxss1 libx11-dev libxkbfile-dev libasound2 libgtk-3-0 libgdk-pixbuf2.0-0 libnss3 libxtst6 libxi6 libxdamage1 libxcursor1 libxcomposite1 libx11-xcb1 libgbm1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libasound2 is already the newest version (1.2.6.1-1ubuntu1).
libsecret-1-dev is already the newest version (0.20.5-2).
libxcomposite1 is already the newest version (1:0.4.5-1build2).
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxi6 is already the newest version (2:1.8-1build1).
libxkbfile-dev is already the newest version (1:1.1.0-1build3).
libxss1 is already the newest version (1:1.2.3-1build2).
libxtst6 is already the newest version (2:1.2.3-1build4).
python-is-python3 is already the newest version (3.9.2-2).
libgdk-pixbuf2.0-0 is already the newest version (2.40.2-2build4).
libgbm1 is already the newest version (23.0.4-0ubuntu1~22.04.1).
libgtk-3-0 is already the newest version (3.24.33-1ubuntu2).
libnss3 is already the newest version (2:3.68.2-0ubuntu1.2).
libx11-dev is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
python3 is already the newest version (3.10.6-1~22.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hamir@WSL2:~/repositories/vscode (main)$  node -v ; yarn -v
v18.18.0
1.22.19
```

**Comment by hamirmahal** [comment]
```
hamir@WSL2:~/repositories/vscode (main)$ git status && git clean -xfd && rm -rf ~/.cache/node-gyp && yarn cache clean && yarn
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Removing node_modules/
yarn cache v1.22.19
success Cleared cache.
Done in 2.51s.
yarn install v1.22.19
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@microsoft/1ds-core-js > @microsoft/applicationinsights-core-js@2.8.15" has unmet peer dependency "tslib@*".
warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/bazelisk@>=1.7.5".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[4/4] Building fresh packages...
[1/20] ⢀ @parcel/watcher
[11/20] ⢀ native-keymap
[9/20] ⢀ kerberos
[4/20] ⢀ @vscode/spdlog
error /home/hamir/repositories/vscode/node_modules/kerberos: Command failed.
Exit code: 1
Command: prebuild-install --runtime napi || node-gyp rebuild
Arguments: 
Directory: /home/hamir/repositories/vscode/node_modules/kerberos
Output:
prebuild-install warn This package does not support N-API version 25.8.4
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.18.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/hamir/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/repositories/vscode/node_modules/kerberos/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/.cache/node-gyp/25.8.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hamir/.cache/node-gyp/25.8.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/hamir/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hamir/.cache/node-gyp/25.8.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hamir/repositories/vscode/node_modules/kerberos',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/hamir/repositories/vscode/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
during RTL pass: dse2
In file included from ../node_modules/node-addon-api/napi.h:2981,
                 from ../src/kerberos.h:11,
                 from ../src/kerberos.cc:1:
../node_modules/node-addon-api/napi-inl.h: In static member function ‘static napi_value__* Napi::ObjectWrap<T>::StaticGetterCallbackWrapper(napi_env, napi_callback_info) [with T = node_kerberos::KerberosServer]’:
../node_modules/node-addon-api/napi-inl.h:4530:1: internal compiler error: Segmentation fault
 4530 | }
      | ^
0xe34ddb internal_error(char const*, ...)
        ???:0
0x127f80f df_analyze_problem(dataflow*, bitmap_head*, int*, int)
        ???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
make: *** [kerberos.target.mk:128: Release/obj.target/kerberos/src/kerberos.o] Error 1
make: Leaving directory '/home/hamir/repositories/vscode/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hamir/.config/yarn/global/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
gyp ERR! command "/home/hamir/.nvm/versions/node/v18.18.0/bin/node" "/home/hamir/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hamir/repositories/vscode/node_modules/kerberos
```

**Comment by hamirmahal** [comment]
<details>
<summary>Prerequisite version information</summary>
<br>

```
hamir@WSL2:~/repositories/vscode (main)$  pkg-config --version
0.29.2
hamir@WSL2:~/repositories/vscode (main)$  sudo apt-get install fakeroot rpm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fakeroot is already the newest version (1.28-1ubuntu1).
rpm is already the newest version (4.17.0+dfsg1-4build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hamir@WSL2:~/repositories/vscode (main)$  sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
g++ is already the newest version (4:11.2.0-1ubuntu1).
libsecret-1-dev is already the newest version (0.20.5-2).
libxkbfile-dev is already the newest version (1:1.1.0-1build3).
python-is-python3 is already the newest version (3.9.2-2).
libkrb5-dev is already the newest version (1.19.2-2ubuntu0.2).
libx11-dev is already the newest version (2:1.7.5-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hamir@WSL2:~/repositories/vscode (main)$  sudo apt install python3 python-is-python3 libsecret-1-dev libxss1 libx11-dev libxkbfile-dev libasound2 libgtk-3-0 libgdk-pixbuf2.0-0 libnss3 libxtst6 libxi6 libxdamage1 libxcursor1 libxcomposite1 libx11-xcb1 libgbm1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libasound2 is already the newest version (1.2.6.1-1ubuntu1).
libsecret-1-dev is already the newest version (0.20.5-2).
libxcomposite1 is already the newest version (1:0.4.5-1build2).
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxi6 is already the newest version (2:1.8-1build1).
libxkbfile-dev is already the newest version (1:1.1.0-1build3).
libxss1 is already the newest version (1:1.2.3-1build2).
libxtst6 is already the newest version (2:1.2.3-1build4).
python-is-python3 is already the newest version (3.9.2-2).
libgdk-pixbuf2.0-0 is already the newest version (2.40.2-2build4).
libgbm1 is already the newest version (23.0.4-0ubuntu1~22.04.1).
libgtk-3-0 is already the newest version (3.24.33-1ubuntu2).
libnss3 is already the newest version (2:3.68.2-0ubuntu1.2).
libx11-dev is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
python3 is already the newest version (3.10.6-1~22.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hamir@WSL2:~/repositories/vscode (main)$  node -v ; yarn -v
v18.18.0
1.22.19
```
</details>

**Comment by hamirmahal** [comment]
<details>
<summary>git log -1 && git status && git clean -xfd && rm -rf ~/.cache/node-gyp && yarn cache clean && yarn</summary>
<br>

```
hamir@WSL2:~/repositories/vscode (main)$ git log -1 && git status && git clean -xfd && rm -rf ~/.cache/node-gyp && yarn cache clean && yarn
commit ef9f5d7f6f53c69f8536057d49a7a476c48d1605 (HEAD -> main, origin/main, origin/HEAD)
Author: Rob Lourens <roblourens@gmail.com>
Date:   Fri Oct 6 21:15:22 2023 -0700

    Fix chat editor title (#195049)
    
    Oops, left over from refactoring last month
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
yarn cache v1.22.19
success Cleared cache.
Done in 0.04s.
yarn install v1.22.19
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
[3/4] Linking dependencies...
warning "@microsoft/1ds-core-js > @microsoft/applicationinsights-core-js@2.8.15" has unmet peer dependency "tslib@*".
warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/bazelisk@>=1.7.5".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[4/4] Building fresh packages...
[1/20] ⠄ @parcel/watcher
[2/20] ⠄ @vscode/policy-watcher
[9/20] ⠄ kerberos
[4/20] ⠄ @vscode/spdlog
error /home/hamir/repositories/vscode/node_modules/@vscode/policy-watcher: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/hamir/repositories/vscode/node_modules/@vscode/policy-watcher
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.18.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp http GET https://electronjs.org/headers/v25.8.4/node-v25.8.4-headers.tar.gz
gyp http 200 https://artifacts.electronjs.org/headers/v25.8.4/node-v25.8.4-headers.tar.gz?force_headers_dist=1
gyp http GET https://electronjs.org/headers/v25.8.4/SHASUMS256.txt
gyp http 200 https://artifacts.electronjs.org/headers/v25.8.4/SHASUMS256.txt?force_headers_dist=1
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/hamir/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/repositories/vscode/node_modules/@vscode/policy-watcher/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/.cache/node-gyp/25.8.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hamir/.cache/node-gyp/25.8.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/hamir/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hamir/.cache/node-gyp/25.8.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hamir/repositories/vscode/node_modules/@vscode/policy-watcher',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/hamir/repositories/vscode/node_modules/@vscode/policy-watcher/build'
  CXX(target) Release/obj.target/vscode-policy-watcher/src/main.o
  CXX(target) Release/obj.target/vscode-policy-watcher/src/linux/PolicyWatcher.o
  SOLINK_MODULE(target) Release/obj.target/vscode-policy-watcher.node
collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
compilation terminated.
make: *** [vscode-policy-watcher.target.mk:156: Release/obj.target/vscode-policy-watcher.node] Error 1
make: Leaving directory '/home/hamir/repositories/vscode/node_modules/@vscode/policy-watcher/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hamir/.config/yarn/global/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
gyp ERR! command "/home/hamir/.nvm/versions/node/v18.18.0/bin/node" "/home/hamir/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hamir/repositories/vscode/node_modules/@vscode/policy-watcher
```
</details>

**Comment by hamirmahal** [comment]
<details>
<summary>git log -1 && git status && git clean -xfd && rm -rf ~/.cache/node-gyp && yarn cache clean && yarn</summary>
<br>

```
hamir@WSL2:~/repositories/vscode (main)$ git log -1 && git status && git clean -xfd && rm -rf ~/.cache/node-gyp && yarn cache clean && yarn
commit ef9f5d7f6f53c69f8536057d49a7a476c48d1605 (HEAD -> main, origin/main, origin/HEAD)
Author: Rob Lourens <roblourens@gmail.com>
Date:   Fri Oct 6 21:15:22 2023 -0700

    Fix chat editor title (#195049)
    
    Oops, left over from refactoring last month
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Removing node_modules/
yarn cache v1.22.19
success Cleared cache.
Done in 2.43s.
yarn install v1.22.19
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@microsoft/1ds-core-js > @microsoft/applicationinsights-core-js@2.8.15" has unmet peer dependency "tslib@*".
warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/bazelisk@>=1.7.5".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[4/4] Building fresh packages...
[1/20] ⡀ @parcel/watcher
[11/20] ⡀ native-keymap
[9/20] ⡀ kerberos
[4/20] ⡀ @vscode/spdlog
error /home/hamir/repositories/vscode/node_modules/kerberos: Command failed.
Exit code: 1
Command: prebuild-install --runtime napi || node-gyp rebuild
Arguments: 
Directory: /home/hamir/repositories/vscode/node_modules/kerberos
Output:
prebuild-install warn This package does not support N-API version 25.8.4
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.18.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/hamir/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/repositories/vscode/node_modules/kerberos/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hamir/.cache/node-gyp/25.8.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hamir/.cache/node-gyp/25.8.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/hamir/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hamir/.cache/node-gyp/25.8.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hamir/repositories/vscode/node_modules/kerberos',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/hamir/repositories/vscode/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
  CXX(target) Release/obj.target/kerberos/src/unix/base64.o
  CXX(target) Release/obj.target/kerberos/src/unix/kerberos_gss.o
  CXX(target) Release/obj.target/kerberos/src/unix/kerberos_unix.o
In file included from /usr/include/c++/11/bits/move.h:57,
                 from /usr/include/c++/11/bits/stl_pair.h:59,
                 from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/memory:63,
                 from ../src/unix/kerberos_unix.cc:1:
/usr/include/c++/11/type_traits: In substitution of ‘template<bool _Cond, class _Tp> using __enable_if_t = typename std::enable_if::type [with bool _Cond = std::__is_swappable<_Tp>::value; _Tp = void]’:
/usr/include/c++/11/type_traits:2683:45:   required from here
/usr/include/c++/11/type_traits:2205:11: internal compiler error: in iterative_hash_template_arg, at cp/pt.c:1958
 2205 |     using __enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~~~
0xe34ddb internal_error(char const*, ...)
        ???:0
0xe2b903 fancy_abort(char const*, int, char const*)
        ???:0
0x10b1e1a tsubst(tree_node*, tree_node*, int, tree_node*)
        ???:0
0x109cd5a finish_template_type(tree_node*, tree_node*, int)
        ???:0
0x14a51e3 c_parse_file()
        ???:0
0x149493e c_common_parse_file()
        ???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
make: *** [kerberos.target.mk:128: Release/obj.target/kerberos/src/unix/kerberos_unix.o] Error 1
make: Leaving directory '/home/hamir/repositories/vscode/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hamir/.config/yarn/global/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
gyp ERR! command "/home/hamir/.nvm/versions/node/v18.18.0/bin/node" "/home/hamir/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hamir/repositories/vscode/node_modules/kerberos
```
</details>

**Comment by joaomoreno** [comment]
Can you still repro?

**Comment by hamirmahal** [comment]
I don't think I've experienced this problem lately.
