### ISSUE TITLE
Typescript breaks on startup

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19523]
I've seen this twice today,  opening a new instance of vscode.

I don't have a tsdk setting set. The output channel says `Using tsserver from location: undefined`. Error in console:

```
workbench.main.js:138 Path must be a string. Received undefined: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at servicePromise.error (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:305:79)
    at modulePath.then.then.modulePath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:301:35)
    at Object.m [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:30381)
    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:1957)
    at _run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3785)
    at _completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3226)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9892
    at done (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:5086)
    at Object.m [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:30523)
    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:1957)
    at _run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3785)
    at _completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3226)
    at e.resolveOk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:17657)
    at d (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:16129)
```

Then I reload the window and it works. Output channel says `Using tsserver from location: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js`

**Comment by mjbvz** [comment]
Good catch. Thanks Rob. 

I believe this was fixed by 850c163f49699d6d7b4adaea2b202f2cf224b816 which we also cherry picked in 1.9
