### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'text' in undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#195290]
```
Uncaught TypeError: Cannot use 'in' operator to search for 'text' in undefined
    at get title [as title] (chatModel.js:288:36)
    at ChatEditorInput.getName (chatEditorInput.js:63:30)
    at OpenEditorsAccessibilityProvider.getAriaLabel (openEditorsView.js:582:42)
    at AccessibiltyRenderer.renderElement (listWidget.js:933:58)
    at PipelineRenderer.renderElement (listWidget.js:907:26)
    at ListView.insertItemInDOM (listView.js:624:23)
    at ListView._splice (listView.js:418:26)
    at ListView.splice (listView.js:336:29)
    at splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (splice.js:14:30)
    at listWidget.js:1156:67
    at EventBufferer.bufferEvents (event.js:1235:23)
    at WorkbenchList.splice (listWidget.js:1156:32)
    at RunOnceScheduler.runner (openEditorsView.js:143:27)
    at RunOnceScheduler.doRun (async.js:788:26)
    at RunOnceScheduler.onTimeout (async.js:784:22)
```

Happens when opening a chat as editor when open editors view is visible.

**Comment by roblourens** [comment]
Thanks!
