### ISSUE TITLE
Unable to run Get-XDAuthentication (Citrix PowerShell SDK)

### ISSUE THREAD

**Issue by mezamoe** [microsoft/vscode#195477]
Hello, I've installed Citrix PowerShell SDK days ago and was working fine within VS Code. Then I did a reboot, and right after that I'm not able to run Get-XDAuthentication (Citrix PowerShell SDK) anymore. The same identical command in PowerShell ISE works flawlessly. I created a test profile in VS Code and installed only the PowerShell plugin, but same result. Running Get-XDAuthentication with verbose switch provides the output below:

PS E:\TOOLS\win-vmdeploy2>  Get-XDAuthentication -ErrorAction Stop -ProfileName "Rundeck" -Verbose
VERBOSE: __AllParameterSets
VERBOSE: Get-XDAuthentication: Enter
VERBOSE: invoking Get-XDAuthenticationEx: 
VERBOSE: __AllParameterSets
VERBOSE: Get-XDAuthenticationEx: Enter
VERBOSE: Get-XDAuthenticationEx: Using config environment: com
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: transactionId: 567583f8-081b-475e-afa7-98e15358d70d
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: ERROR: System.TypeInitializationException: The type initializer for 'Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient' threw an 
exception. ---> System.MissingMethodException: Method not found: 'Void System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.set_SerializerSettings(Newtonsoft.Json.JsonSerializerSettings)'.
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..cctor()
   --- End of inner exception stack trace ---
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, ConnectionSettings connectionSettings, RequestSettings settings, HttpMessageHandler handler, Boolean 
disposeHandler)
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, HttpMessageHandler handler, Boolean disposeHandler)
   at Citrix.Sdk.Proxy.Cmdlets.GetXDAuthenticationExCmdlet.<GetCwsTokenAsync>d__53.MoveNext() in 
C:\tc\work\16815f2b41abb80\Cloud\PoshSdkProxySnapIn\Components\Snapin\Cmdlets\GetXDAuthenticationEx.cs:line 686
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: transactionId: 03ed2421-cdce-4bb4-a621-84afb2528f40
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: ERROR: System.TypeInitializationException: The type initializer for 'Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient' threw an 
exception. ---> System.MissingMethodException: Method not found: 'Void System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.set_SerializerSettings(Newtonsoft.Json.JsonSerializerSettings)'.
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..cctor()
   --- End of inner exception stack trace ---
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, ConnectionSettings connectionSettings, RequestSettings settings, HttpMessageHandler handler, Boolean 
disposeHandler)
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, HttpMessageHandler handler, Boolean disposeHandler)
   at Citrix.Sdk.Proxy.Cmdlets.GetXDAuthenticationExCmdlet.<GetCwsTokenAsync>d__53.MoveNext() in 
C:\tc\work\16815f2b41abb80\Cloud\PoshSdkProxySnapIn\Components\Snapin\Cmdlets\GetXDAuthenticationEx.cs:line 686
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: transactionId: 7f5578aa-86fc-4467-b4c2-f21ff8743d42
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: ERROR: System.TypeInitializationException: The type initializer for 'Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient' threw an 
exception. ---> System.MissingMethodException: Method not found: 'Void System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.set_SerializerSettings(Newtonsoft.Json.JsonSerializerSettings)'.
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..cctor()
   --- End of inner exception stack trace ---
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, ConnectionSettings connectionSettings, RequestSettings settings, HttpMessageHandler handler, Boolean 
disposeHandler)
   at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, HttpMessageHandler handler, Boolean disposeHandler)
   at Citrix.Sdk.Proxy.Cmdlets.GetXDAuthenticationExCmdlet.<GetCwsTokenAsync>d__53.MoveNext() in 
C:\tc\work\16815f2b41abb80\Cloud\PoshSdkProxySnapIn\Components\Snapin\Cmdlets\GetXDAuthenticationEx.cs:line 686
VERBOSE: Get-XDAuthenticationEx: Exit
VERBOSE: Get-XDAuthentication: Exception: AuthenticationFailed
VERBOSE: Get-XDAuthentication: Exit
Get-XDAuthentication : AuthenticationFailed

**Comment by rebornix** [comment]
Please start an issue with the Powershell extension, thanks!
