### ISSUE TITLE
api-doc-json failing after commit 

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#19540]
After commit https://github.com/Microsoft/vscode/commit/a6435b1cbd1417b0d334ea9018f5371df198898f the vscode-docs gulp task api-doc-json is failing with exception:

[22:16:40] 'api-doc-json' errored after 4.78 s
[22:16:40] TypeError: Cannot read property 'toObject' of undefined
    at C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\types\reference.js:36:82
    at Array.map (native)
    at ReferenceType.toObject (C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\types\reference.js:36:55)
    at DeclarationReflection.toObject (C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\reflections\declaration.js:54:37)
    at C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\reflections\abstract.js:268:37
    at C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\reflections\container.js:26:17
    at Array.forEach (native)
    at DeclarationReflection.ContainerReflection.traverse (C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\reflections\container.js:25:27)
    at DeclarationReflection.traverse (C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\reflections\declaration.js:49:35)
    at DeclarationReflection.Reflection.toObject (C:\Users\gregvanl\vscode-docs\node_modules\typedoc\dist\lib\models\reflections\abstract.js:261:14)

Should 		 
onDidChangeCodeLenses?: Event<this>;
be 
onDidChangeCodeLenses?: Event<CodeLens>;

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/1162f8943089ef5a6be372aafa05fd35c0d7335a which changes `Event<this>` to `Event<void>` which the generation tooling can handle.
