### ISSUE TITLE
Cannot convert object to primitive value in applicationinsights code

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1956]
I see the following exception in the console. I believe it has to do with the exception thrown by the tslint extension (see https://github.com/Microsoft/vscode-tslint/issues/24)
- install ts lint extension (version 0.5.4)
- open a type script file, on the error dialog (tslint not installed) press cancel
```
TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (/home/martinae/VSCode-linux-x64/resources/app/node_modules/applicationinsights/Library/Client.js:67:25)
    at e.log (file:////home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:91:1573)
    at t.handleEvent (file:////home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:45:31420)
    at t.e.publicLog (file:////home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:45:28598)
    at t.e.flushErrorBuffer (file:////home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:45:26607)
    at file:////home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:45:26467
```

**Comment by SofianHn** [comment]
I can't seem to reproduce it, I am able to see the ts lint error thrown but not the one from AI. Can you add the TSLint error so I can make sure I am seeing the same thing?

**Comment by aeschli** [comment]
Sorry then it must have been a different error that I've been seeing. I don't have a reproducible example, but I keep my eyes open.

**Comment by aeschli** [comment]
@SofianHn Any suggestion how to verify? Maybe in code?

**Comment by SofianHn** [comment]
@aeschli Maybe just a code review. I removed the whole API that causes this. We report errors as custom telemetry events and no need to double reporting through the `trackException` API.

**Comment by aeschli** [comment]
Thanks Sofian. I verified that we no longer call trackException.
