### ISSUE TITLE
WSL2 2.0.4 Pre-release isn't working with "Connect to WSL"

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#195757]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.84.0-insider (user setup)
Commit: 0c36b92c82064882a228487040187cfc13669c0f
Date: 2023-10-16T05:35:39.577Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Install WSL 2.0.4
2. Open insiders
3. Connect to WSL

The editor gets stuck with "Opening remote..."
![image](https://github.com/microsoft/vscode/assets/461084/7e9de09e-264b-4167-893b-c3f2c677ddf2)
![image](https://github.com/microsoft/vscode/assets/461084/a55de6c0-2414-4486-a7bf-6036c7fdc9ad)

```
2023-10-17 01:08:25.906 [info] [LocalProcess0][resolveAuthority(wsl,1)][338ms] invoking...
2023-10-17 01:08:26.834 [info] [LocalProcess0][resolveAuthority(wsl,1)][1266ms] returned WebSocket(127.0.0.1:21102)
2023-10-17 01:08:26.834 [info] resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:21102)' after 1266 ms
2023-10-17 01:08:26.880 [info] Creating a socket (renderer-Management-088b17fc-b26b-4dd5-ad0e-877a555f32a8)...
2023-10-17 01:08:26.881 [info] Creating a socket (renderer-ExtensionHost-0c3cea73-f368-4734-a253-3d8f395713c3)...
2023-10-17 01:10:40.197 [info] Creating a socket (renderer-Management-088b17fc-b26b-4dd5-ad0e-877a555f32a8) returned an error after 133316 ms.
2023-10-17 01:10:40.197 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/Paulo/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3985)
2023-10-17 01:10:40.197 [error] [remote-connection][Management   ][088b1…][initial][WebSocket(127.0.0.1:21102)] socketFactory.connect() failed or timed out. Error:
2023-10-17 01:10:40.198 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/Paulo/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3985)
2023-10-17 01:10:40.198 [error] [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
2023-10-17 01:10:40.198 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/Paulo/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3985)
2023-10-17 01:10:40.199 [info] Invoking resolveAuthority(wsl)...
2023-10-17 01:10:40.199 [info] [LocalProcess0][resolveAuthority(wsl,2)][0ms] obtaining proxy...
2023-10-17 01:10:40.199 [info] [LocalProcess0][resolveAuthority(wsl,2)][1ms] invoking...
2023-10-17 01:10:40.202 [info] [LocalProcess0][resolveAuthority(wsl,2)][3ms] returned WebSocket(127.0.0.1:21102)
2023-10-17 01:10:40.202 [info] resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:21102)' after 3 ms
2023-10-17 01:10:40.202 [info] Creating a socket (renderer-Management-abbea1b1-fb3a-420b-ad15-892be8a56de2)...
```

**Comment by aeschli** [comment]
I just tested that `code-insiders` works on WSL 2.0.4.

Anything special in the WSL log?

Maybe restart WSL with `wsl --shutdown`?

**Comment by pocesar** [comment]
Ah, it's the `networkingMode=mirrored` + `dnsTunneling=true` that does this

**Comment by Berrysoft** [comment]
Is there any way to make vscode remote work with mirrored networking?
