### ISSUE TITLE
Keytar stopped working on recent VSCode update

### ISSUE THREAD

**Issue by GustavoASC** [microsoft/vscode#195945]
The extension "[Google Drive for VSCode](https://marketplace.visualstudio.com/items?itemName=GustavoASC.google-drive-vscode)" (version 1.3.5) has been working for more than a year in Mac, Linux, and Windows, and suddenly stopped working after a recent VSCode update, on non-Ubuntu OS. Now the version 1.3.5 only works in Ubuntu. Please notice the _(not a mach-o file)_ error that appears when I try to run the extension on MacOS.

The original build last year was made on Ubuntu machine, but was working on multiple OS, and suddenly stopped working for different OS rather than Ubuntu.
[This](https://github.com/GustavoASC/google-drive-vscode/blob/ce671c0d9759416d8a684c37f29c9d9c40222bea/src/drive/credentials/keytarCredentialsProvider.ts#L4) is the code that uses Keytar in the extension and stopped working:

```typescript
import { ICredentialsProvider } from "./credentialsManager";
import * as keytar from 'keytar';

export class KeytarCredentialsProvider implements ICredentialsProvider {
    
    getPassword(service: string, account: string): Promise<string | null> {
        return keytar.getPassword(service, account);
    }

    setPassword(service: string, account: string, password: string): Promise<void> {
        return keytar.setPassword(service, account, password);
    }

    deletePassword(service: string, account: string): Promise<boolean> {
        return keytar.deletePassword(service, account);
    }

}
```

Here's the output from Host Extension from VSCode:

> 2023-10-18 18:52:48.627 [error] Activating extension GustavoASC.google-drive-vscode failed due to an error:
2023-10-18 18:52:48.627 [error] Error: dlopen(/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/node_modules/keytar/build/Release/keytar.node, 0x0001): tried: '/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/node_modules/keytar/build/Release/keytar.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/node_modules/keytar/build/Release/keytar.node' (no such file), '/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/node_modules/keytar/build/Release/keytar.node' (not a mach-o file)
	at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
	at Module._extensions..node (node:internal/modules/cjs/loader:1401:18)
	at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1869)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at u._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5631)
	at c._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29196)
	at t._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35261)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/node_modules/keytar/lib/keytar.js:1:76)
	at u._compile (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at u._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5631)
	at c._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29196)
	at t._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35261)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/out/drive/credentials/keytarCredentialsProvider.js:4:16)
	at u._compile (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at u._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5631)
	at c._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29196)
	at t._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35261)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/out/drive/credentials/credentialsManager.js:5:37)
	at u._compile (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at u._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5631)
	at c._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29196)
	at t._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35261)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/out/auth/driveAuthenticator.js:14:30)
	at u._compile (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at u._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5631)
	at c._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29196)
	at t._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35261)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/Users/gustavo.cassel/.vscode/extensions/gustavoasc.google-drive-vscode-1.3.5/out/extension.js:19:30)
	at u._compile (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at u._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5631)
	at c._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29196)
	at t._load (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35261)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/Applications/VSCode.app/Contents/Resources/app/out/vs/loader.js:5:98)
	at s.vb (/Applications/VSCode.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:30375)
	at async Promise.all (index 0)

**Comment by IllusionMH** [comment]
Does this issue has any action items for the team?
Looks like you've found root cause https://github.com/GustavoASC/google-drive-vscode/issues/45#issuecomment-1769470435

And deprecation was first mentioned in early July https://code.visualstudio.com/updates/v1_80#_secretstorage-api-now-uses-electron-api-over-keytar

**Comment by GustavoASC** [comment]
Thanks! I was just going to comment here, that I was able to use the new SecretStorage API. We can close the issue.
