### ISSUE TITLE
1.83.1 ws1 cannot run `code .`

### ISSUE THREAD

**Issue by wisestmumbler** [microsoft/vscode#195914]
- VS Code Version: 1.83.1 (via custom chocolatey)
- OS Version: windows (windows server 2019 datacenter 10.0.17763 via amazon workspaces)
- Using WSL1 Ubuntu

Steps to Reproduce:

1. Using the env above: upgrade vscode from 1.80 to 1.83.1
2. From wsl1 ubuntu terminal: try to run `code path/to/workspace-file`
3. Error:
```
node:net:413
      throw errnoException(err, 'open');
      ^

Error: open EISDIR
    at new Socket (node:net:413:13)
    at createWritableStdioStream (node:internal/bootstrap/switches/is_main_thread:78:18)
    at process.getStderr [as stderr] (node:internal/bootstrap/switches/is_main_thread:170:12)
    at console.get (node:internal/console/constructor:220:44)
    at console.value (node:internal/console/constructor:347:50)
    at console.warn (node:internal/console/constructor:382:61)
    at Object.d [as onError] (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:7727)
    at g.onError (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:12590)
    at d._onLoadError (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:7877)
    at u (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:9082)
    at Object.errorback (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:9457)
    at c.triggerErrorback (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:13508)
    at C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:13259
    at n.load (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:2:1654)
    at c.load (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:13214)
    at u (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:9338)
    at Object.errorback (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:9457)
    at c.triggerErrorback (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:13508)
    at C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:13259
    at n.load (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:2:1654)
    at c.load (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1:13214)
    at u (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:9338)
    at d._loadModule (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:9466)
    at d._resolve (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:4:452)
    at d.defineModule (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:3:5561)
    at g (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:4:1741)
    at m (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:2:2448)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:31:28)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:31:27003)
    at n._createAndEvalScript (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:2:2492)
    at C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:2:2133
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open'
}

Node.js v18.15.0
```

NOTE: Expected to be fixed by #192506 but not

**Comment by aeschli** [comment]
Do you still see the issue?
