### ISSUE TITLE
cannot reconnect please reload the window

### ISSUE THREAD

**Issue by BigodF** [microsoft/vscode#196058]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
            Version: 1.83.1
            Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
            Date: 2023-10-10T23:45:31.402Z
            Electron: 25.8.4
            ElectronBuildId: 24154031
            Chromium: 114.0.5735.289
            Node.js: 18.15.0
            V8: 11.4.183.29-electron.0
            OS: Linux x64 5.15.77-amd64-desktop
- OS Version: Linux x64 5.15.77-amd64-desktop
- remote OS Version: 
            ubuntu (docker container: Linux huaweiyun20220320211 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
            openssh-client: 1:7.6p1-4ubuntu0.7
            openssh-server: 1:7.6p1-4ubuntu0.7
            openssh-sftp-server: 1:7.6p1-4ubuntu0.7
          
Steps to Reproduce:

It's always good before this bug happend. VScode open a window that showed "cannot reconnect please reload the window", and VScode show the windows again after I pushed the "reload window"  button. Sometimes I can open one remote windows, opening another remote window reproduced the bug. the possibility of bug is above 95% since it first happened.

my final solution is downgrading the remote ssh-server version to 1:7.6p1-4ubuntu0.5, and remove the vscode-server on the remote.
            openssh-client: 1:7.6p1-4ubuntu0.5
            openssh-server: 1:7.6p1-4ubuntu0.5
            openssh-sftp-server: 1:7.6p1-4ubuntu0.5

vscode local log (~/.config/Code/logs/20231020T102530/window3/renderer.log):
```log
2023-10-20 10:27:53.259 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-20 10:27:53.277 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-20 10:27:54.180 [info] Invoking resolveAuthority(ssh-remote)...
2023-10-20 10:27:54.180 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2023-10-20 10:27:54.181 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
2023-10-20 10:27:54.811 [error] [Extension Host] (node:13223) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
2023-10-20 10:27:54.825 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][645ms] returned WebSocket(127.0.0.1:36945)
2023-10-20 10:27:54.825 [info] resolveAuthority(ssh-remote) returned 'WebSocket(127.0.0.1:36945)' after 646 ms
2023-10-20 10:27:54.827 [info] Creating a socket (renderer-Management-610f9fde-bfc2-4fb5-96af-3e58f79fa6ed)...
2023-10-20 10:27:54.828 [info] Creating a socket (renderer-ExtensionHost-fc80840b-0553-4a88-90fe-2af136981023)...
2023-10-20 10:27:54.924 [info] Creating a socket (renderer-Management-610f9fde-bfc2-4fb5-96af-3e58f79fa6ed) was successful after 97 ms.
2023-10-20 10:27:54.949 [info] Creating a socket (renderer-ExtensionHost-fc80840b-0553-4a88-90fe-2af136981023) was successful after 120 ms.
2023-10-20 10:28:00.207 [info] [perf] Render performance baseline is 55ms
2023-10-20 10:28:00.610 [error] [Extension Host] (node:502358) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2023-10-20 10:28:01.883 [info] [remote-connection][Management   ][610f9…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-10-20 10:28:01.884 [error] {"isTrusted":true}
2023-10-20 10:28:01.884 [info] [remote-connection][Management   ][610f9…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-10-20 10:28:01.886 [info] [remote-connection][Management   ][610f9…][reconnect] resolving connection...
2023-10-20 10:28:01.887 [info] Invoking resolveAuthority(ssh-remote)...
2023-10-20 10:28:01.887 [info] [LocalProcess0][resolveAuthority(ssh-remote,2)][0ms] obtaining proxy...
2023-10-20 10:28:01.887 [info] [LocalProcess0][resolveAuthority(ssh-remote,2)][1ms] invoking...
2023-10-20 10:28:01.901 [info] [remote-connection][ExtensionHost][fc808…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-10-20 10:28:01.901 [error] {"isTrusted":true}
2023-10-20 10:28:01.901 [info] [remote-connection][ExtensionHost][fc808…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-10-20 10:28:01.902 [info] [remote-connection][ExtensionHost][fc808…][reconnect] resolving connection...
2023-10-20 10:28:02.522 [info] [LocalProcess0][resolveAuthority(ssh-remote,2)][636ms] returned WebSocket(127.0.0.1:40525)
2023-10-20 10:28:02.522 [info] resolveAuthority(ssh-remote) returned 'WebSocket(127.0.0.1:40525)' after 636 ms
2023-10-20 10:28:02.523 [info] [remote-connection][Management   ][610f9…][reconnect] connecting to WebSocket(127.0.0.1:40525)...
2023-10-20 10:28:02.523 [info] Creating a socket (renderer-Management-610f9fde-bfc2-4fb5-96af-3e58f79fa6ed)...
2023-10-20 10:28:02.524 [info] [remote-connection][ExtensionHost][fc808…][reconnect] connecting to WebSocket(127.0.0.1:40525)...
2023-10-20 10:28:02.524 [info] Creating a socket (renderer-ExtensionHost-fc80840b-0553-4a88-90fe-2af136981023)...
2023-10-20 10:28:02.625 [info] Creating a socket (renderer-Management-610f9fde-bfc2-4fb5-96af-3e58f79fa6ed) was successful after 103 ms.
2023-10-20 10:28:02.653 [info] Creating a socket (renderer-ExtensionHost-fc80840b-0553-4a88-90fe-2af136981023) was successful after 130 ms.
2023-10-20 10:28:02.700 [info] [remote-connection][Management   ][610f9…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-10-20 10:28:02.700 [error] {"isTrusted":true}
2023-10-20 10:28:02.703 [error] [remote-connection][Management   ][610f9…][reconnect][WebSocket(127.0.0.1:40525)] received error control message when negotiating connection. Error:
2023-10-20 10:28:02.703 [error] Error: Connection error: Unknown reconnection token (never seen)
    at x (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:23194)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:14766)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14393)
    at b.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:17492)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:16863)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at u.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:12167)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:11454
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:4916)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at j.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3300)
2023-10-20 10:28:02.704 [error] [remote-connection][Management   ][610f9…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
2023-10-20 10:28:02.704 [error] Error: Connection error: Unknown reconnection token (never seen)
    at x (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:23194)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:14766)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14393)
    at b.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:17492)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:16863)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at u.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:12167)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:11454
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:4916)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at j.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3300)
2023-10-20 10:28:02.714 [error] Error: Unable to read file 'vscode-remote://ssh-remote+10.133.168.176/data1/heran5/ChatGLM-6B/.vscode/settings.json' (Canceled: Canceled)
    at r.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16628)
    at r.D (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16423)
    at async r.C (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15735)
    at async Object.factory (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15664)
2023-10-20 10:28:02.714 [error] Error: Unable to read file 'vscode-remote://ssh-remote+10.133.168.176/data1/heran5/ChatGLM-6B/.vscode/tasks.json' (Canceled: Canceled)
    at r.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16628)
    at r.D (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16423)
    at async r.C (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15735)
    at async Object.factory (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15664)
2023-10-20 10:28:02.715 [error] Error: Unable to read file 'vscode-remote://ssh-remote+10.133.168.176/data1/heran5/ChatGLM-6B/.vscode/launch.json' (Canceled: Canceled)
    at r.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16628)
    at r.D (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16423)
    at async r.C (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15735)
    at async Object.factory (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15664)
2023-10-20 10:28:02.716 [error] Error: Unable to read file 'vscode-remote://ssh-remote+10.133.168.176/data1/heran5/ChatGLM-6B/.vscode/settings.json' (Canceled: Canceled)
    at r.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16628)
    at r.D (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16423)
    at async r.C (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15735)
    at async Object.factory (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15664)
2023-10-20 10:28:02.716 [error] Error: Unable to read file 'vscode-remote://ssh-remote+10.133.168.176/data1/heran5/ChatGLM-6B/.vscode/tasks.json' (Canceled: Canceled)
    at r.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16628)
    at r.D (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16423)
    at async r.C (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15735)
    at async Object.factory (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15664)
2023-10-20 10:28:02.716 [error] Error: Unable to read file 'vscode-remote://ssh-remote+10.133.168.176/data1/heran5/ChatGLM-6B/.vscode/launch.json' (Canceled: Canceled)
    at r.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16628)
    at r.D (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:16423)
    at async r.C (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15735)
    at async Object.factory (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15664)
2023-10-20 10:28:02.763 [info] [remote-connection][ExtensionHost][fc808…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-10-20 10:28:02.764 [error] {"isTrusted":true}
2023-10-20 10:28:02.764 [error] [remote-connection][ExtensionHost][fc808…][reconnect][WebSocket(127.0.0.1:40525)] received error control message when negotiating connection. Error:
2023-10-20 10:28:02.765 [error] Error: Connection error: Unknown reconnection token (never seen)
    at x (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:23194)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:14766)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14393)
    at b.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:17492)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:16863)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at u.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:12167)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:11454
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:4916)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at j.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3300)
2023-10-20 10:28:02.765 [error] [remote-connection][ExtensionHost][fc808…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
2023-10-20 10:28:02.765 [error] Error: Connection error: Unknown reconnection token (never seen)
    at x (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:23194)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:14766)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14393)
    at b.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:17492)
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:16863)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at u.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:12167)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:11454
    at u.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:4916)
    at c.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at j.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3300)
```

**Comment by BigodF** [comment]
My solution above is not a final solution.. This bug also shows, but not as frequent anymore. Another remote docker container with openssh-server: 1:7.6p1-4ubuntu0.4 doesn't show this bug, but I can't downgrade the bug remote to this version of openssh-server

**Comment by ductai199x** [comment]
potentially a duplicate of this issue here, no answers yet from vscode team: https://github.com/microsoft/vscode/issues/195617

**Comment by BigodF** [comment]
My solution is downgrading the jupyter extention to v2023.10.1002931100 (but I dont know my last jupyter version, just downloaded the second version from vscode office website), that works for me.
