### ISSUE TITLE
Cannot use Debug Console

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#196078]
I run quite often into this when debugging Code OSS, and it is very annoying, as I have to use the watch window:

![Image](https://github.com/microsoft/vscode/assets/2931520/44ac3f2c-575c-4ca8-8095-8329204a66eb)

```
ERR TreeError [DebugRepl] Tree element not found: [object Object]: Error: TreeError [DebugRepl] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:190:30937)
    at T.isCollapsed (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:190:30217)
    at w.isCollapsed (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:614:669)
    at ne.H (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:614:19411)
    at ne.E (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:614:18757)
    at async ne.D (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:614:18344)
    at async ne.B (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:614:17905)
    at async ne.z (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:614:15392)
    at async ne.updateChildren (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:614:15137)
    at async O.a (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2106:2734)
```

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/146002

Will try to look into this in debt week
