### ISSUE TITLE
[html] Cannot read property 'attributes' of undefined in htmlTags

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1960]
Found in the console:

TypeError: Cannot read property 'attributes' of undefined: TypeError: Cannot read property 'attributes' of undefined
    at Object.collectAttributes (file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlTags.js:220:60)
    at file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlWorker.js:231:26
    at Array.forEach (native)
    at HTMLWorker.collectAttributeSuggestions (file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlWorker.js:230:32)
    at HTMLWorker.doSuggest (file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlWorker.js:303:26)
    at HTMLWorker.AbstractModeWorker.suggest (file:///home/martinae/workspaces/vscode/out/vs/editor/common/modes/abstractModeWorker.js:73:25)
    at HTMLWorker.suggestHTML (file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlWorker.js:283:45)
    at file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlWorker.js:279:30
    at HTMLWorker._delegateToModeAtPosition (file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlWorker.js:72:20)
    at HTMLWorker.suggest (file:///home/martinae/workspaces/vscode/out/vs/languages/html/common/htmlWorker.js:275:25)

**Comment by aeschli** [comment]
To verify:
Complete attributes inside a custom element
<foo |complete here
