### ISSUE TITLE
TS Server fatal error:  UNC host 'starship' access is not allowed

### ISSUE THREAD

**Issue by rika-shirayanagi** [microsoft/vscode#196227]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.3.0-dev.20231021

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host 'starship' access is not allowed
    at Object.watchFile (node:fs:2405:14)
    at fsWatchFileWorker (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8579:11)
    at c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8226:15
    at createSingleWatcherPerName (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:7747:16)
    at pollingWatchFile (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8221:12)
    at watchFile2 (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8056:16)
    at watchMissingFileSystemEntry (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8314:14)
    at fsWatchHandlingExistenceOnHost (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8245:72)
    at c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8235:15
    at createSingleWatcherPerName (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:7747:16)
    at fsWatch (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8230:12)
    at Object.watchFile2 [as watchFile] (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:8081:16)
    at watchFile (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:120012:67)
    at Object.watchFile (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:120031:283)
    at c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:179590:183
    at _ProjectService.forEachConfigFileLocation (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:179640:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:179583:10)
    at InferredProject2.addRoot (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:177743:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:179381:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:181008:12)
    at c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:181238:64
    at flatMap (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:2597:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:181238:24)
    at updateOpen (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:182436:29)
    at c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:185038:69
    at IpcIOSession.executeWithRequestId (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:185030:14)
    at IpcIOSession.executeCommand (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:185038:29)
    at IpcIOSession.onMessage (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:185080:51)
    at process.<anonymous> (c:\Users\shirayanagi\.vscode\extensions\ms-vscode.vscode-typescript-next-5.3.20231021\node_modules\typescript\lib\tsserver.js:186662:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (16.33GB free)|
|Process Argv|--crash-reporter-id 20d14c28-174a-4a24-a389-ad2b0f548aee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.5
vscode-npm-script|eg2|0.3.29
live-sass|gle|6.1.1
git-graph|mhu|1.30.0
vscode-azureappservice|ms-|0.25.1
vscode-azureresourcegroups|ms-|0.7.5
vscode-docker|ms-|1.27.0
vscode-language-pack-ja|MS-|1.83.2023101109
csdevkit|ms-|0.5.150
csharp|ms-|2.7.25
vscode-dotnet-runtime|ms-|1.8.1
vscodeintellicode-csharp|ms-|0.1.26
remote-containers|ms-|0.315.1
remote-wsl|ms-|0.81.8
azure-account|ms-|0.11.6
powershell|ms-|2023.8.0
vscode-typescript-next|ms-|5.3.20231021
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
6c1a3589:30846784
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pyreplss1:30865275
pythoncet00cf:30866519
h48ei257:30867296
pythontbext0:30864172

```

</details>

**Comment by gjsjohnmurray** [comment]
Does https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths help?

**Comment by rika-shirayanagi** [comment]
Thank you, gjsjohnmurray.
Problem solved.
