### ISSUE TITLE
TS Server fatal error:  UNC host 'ubuntu' access is not allowed

### ISSUE THREAD

**Issue by jamesburley** [microsoft/vscode#196213]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.2.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host 'ubuntu' access is not allowed
    at Object.watchFile (node:fs:2405:14)
    at fsWatchFileWorker (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8602:11)
    at c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8249:15
    at createSingleWatcherPerName (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7770:16)
    at pollingWatchFile (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8244:12)
    at watchFile2 (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8079:16)
    at watchMissingFileSystemEntry (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8337:14)
    at fsWatchHandlingExistenceOnHost (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8268:72)
    at c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8258:15
    at createSingleWatcherPerName (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7770:16)
    at fsWatch (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8253:12)
    at Object.watchFile2 [as watchFile] (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8104:16)
    at watchFile (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119421:67)
    at Object.watchFile (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119440:283)
    at c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179417:183
    at _ProjectService.forEachConfigFileLocation (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179467:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179410:10)
    at InferredProject2.addRoot (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177667:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179208:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180832:12)
    at c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181062:64
    at flatMap (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2600:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181062:24)
    at updateOpen (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182242:29)
    at c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184838:69
    at IpcIOSession.executeWithRequestId (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184830:14)
    at IpcIOSession.executeCommand (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184838:29)
    at IpcIOSession.onMessage (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184880:51)
    at process.<anonymous> (c:\Users\Me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:186461:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700K (24 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (25.86GB free)|
|Process Argv|--crash-reporter-id dc6a0297-aad8-4efa-84c7-97a457e3f0f0|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythontestfixt:30866405
pyreplss1:30865275
pythoncet0:30866520
h48ei257:30867296
pythontbext0:30864172

```

</details>

**Comment by jamesburley** [comment]
Seems that the auto detected Language Model is JavaScript. However my script is written in JScript because it runs in Secure CRT. I'll have to see if another model exists for that. Changing the script file extension to JSC and selecting a different model for this script keeps the JS service from crashing.

**Comment by jamesburley** [comment]
So maybe it was just related to security.allowedUNCHosts. I had to re-open and allow host ubuntu every time, and it wasn't sticking. Adding it to allowed hosts list works. And now when I open the file with JS extension it works fine.

**Comment by jamesburley** [comment]
Yes the article you mentioned at https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths was exactly the issue. I did not have the drive mapped or the host specifically added to VSCode.
