### ISSUE TITLE
Error: TextModelPart is disposed!

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196378]
Refs: https://github.com/microsoft/vscode/issues/196327

1. Run some cells multiple times
2. You will notice in DevTools console the following error

Error is coming from here https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/model/textModelPart.ts#L17

```
ERR TextModelPart is disposed!: Error: TextModelPart is disposed!
    at f.g (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:121:22471)
    at f.getWordAtPosition (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:631:119005)
    at x.getWordAtPosition (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:736:9056)
    at p.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:760:68473)
    at new m (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:760:68348)
    at new p (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:760:69058)
    at D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:760:69756)
    at T.F (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:760:73872)
    at T.C (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:760:72739)
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:760:70301)
    at d.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at d.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at d.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:744:15864)
    at d.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at d.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at I.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:132:108103)
    at I.endEmitViewEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:132:108604)
    at m.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:4025)
    at m.restoreCursorState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:742:2679)
    at U.restoreViewState (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:744:6464)
    at c.R (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1580:128307)
    at c.attachTextEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1580:127152)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2152:18362
```

**Comment by amunger** [comment]
I'm not repro'ing, but from the beautified stack, this may be from @Yoyokrazy's changes

```
ERR TextModelPart is disposed!: Error: TextModelPart is disposed!
at [./editor/common/model/textModelPart.ts:17:9](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/common/model/textModelPart.ts#L17)
at [./editor/common/model/tokenizationTextModelPart.ts:208:7](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/common/model/tokenizationTextModelPart.ts#L208)
at [./editor/common/model/textModel.ts:1964:41](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/common/model/textModel.ts#L1964)
at [./editor/contrib/wordHighlighter/browser/wordHighlighter.ts:102:21](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L102)
at [./editor/contrib/wordHighlighter/browser/wordHighlighter.ts:87:25](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L87)
at [./editor/contrib/wordHighlighter/browser/wordHighlighter.ts:161:2](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L161)
at [./editor/contrib/wordHighlighter/browser/wordHighlighter.ts:234:9](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L234)
([./editor/contrib/wordHighlighter/browser/wordHighlighter.ts:666:25](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L666))
at [./editor/contrib/wordHighlighter/browser/wordHighlighter.ts:520:7](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L520)
at [./editor/contrib/wordHighlighter/browser/wordHighlighter.ts:292:8](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L292)
at [./base/common/event.ts:1140:12](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/base/common/event.ts#L1140)
at [./base/common/event.ts:1151:8](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/base/common/event.ts#L1151)
at [./base/common/event.ts:1175:8](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/base/common/event.ts#L1175)
at [./editor/browser/widget/codeEditorWidget.ts:1714:37](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/browser/widget/codeEditorWidget.ts#L1714)
at [./base/common/event.ts:1140:12](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/base/common/event.ts#L1140)
at [./base/common/event.ts:1171:8](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/base/common/event.ts#L1171)
at [./editor/common/viewModelEventDispatcher.ts:64:17](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/common/viewModelEventDispatcher.ts#L64)
at [./editor/common/viewModelEventDispatcher.ts:109:7](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/common/viewModelEventDispatcher.ts#L109)
at [./editor/common/viewModel/viewModelImpl.ts:1092:25](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/common/viewModel/viewModelImpl.ts#L1092)
at [./editor/common/viewModel/viewModelImpl.ts:1020:7](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/common/viewModel/viewModelImpl.ts#L1020)
at [./editor/browser/widget/codeEditorWidget.ts:1013:31](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/editor/browser/widget/codeEditorWidget.ts#L1013)
at [./workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts:342:21](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts#L342)
at [./workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts:238:8](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts#L238)
at [./workbench/contrib/notebook/browser/view/cellParts/codeCell.ts:189:18](https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/workbench/contrib/notebook/browser/view/cellParts/codeCell.ts#L189)
```

**Comment by Yoyokrazy** [comment]
:) yep that's me. fix incoming. Closing as dup of #196405
