### ISSUE TITLE
Can not debug in VSCode integrated terminal sometimes

### ISSUE THREAD

**Issue by Insdf** [microsoft/vscode#196460]
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: No. I need at least one extension to debug program, but I test C/C++ and Python, so it may not caused by extension.

# Contents

- Description
- Steps to Reproduce
- Version Information
- My JSON File
- Debug Console Information
- Developer Tools Console Information

# Description

At the first debug, in C/C++ it says "Unable to establish connection to GDB"; In Python it says "Time out waiting for launcher to connect". But the second time I debug the program, it works well. The problem disappears, but it will occur every few hours or after reboot.

I tried many other methods: Add VSCode installation folder to windows defender exclusion, run VSCode as adminstrator, disable git auto refresh in VSCode, use VSCode Insider and close antivirus on my PC, etc. But they all don't work.

Could you please help me? Thanks.

# Steps to Reproduce

1. Open a C/C++/Python program. In my case, even a hello world may cause the problem.

```c
#include <stdio.h>
int main(void) {
   printf("Hello, World!");
   return 0;
}
```

2. Modify keyboard shortcut of debug to, e.g. F6. In C/C++ it's C_Cpp.BuildAndDebugFile. Then press F6 for 1 second (or more?).

It may open about 10 integrated debug terminals and run well. But actually it may fail 3~4 terminals with "can not connect" problem.

In C/C++, if I set "externalConsole" in launch.json to true, it's ok to run 10 C programs with external cmd. 

But modify the default terminal profile to cmd (integrated terminal), the same problem is still there.

I also modify `serverLaunchTimeout` in launch.json to 60000, i.e. 60 seconds. But just pass 20~25 seconds, the problem occurs.

# Version Information

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)

OS version: Windows_NT x64 10.0.19045

# My JSON File

Below is my json settings:

launch.json

```json
{
    "configurations": [
      {
        "name": "C/C++: gcc.exe build and debug active file",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${fileDirname}",
        "environment": [],
        "externalConsole": false,
        "serverLaunchTimeout": 60000,
        "MIMode": "gdb",
        "logging": {
          "trace": true,
          "traceResponse": true,
          "engineLogging": true
        },
        "miDebuggerPath": "C:\\msys64\\ucrt64\\bin\\gdb.exe",
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          },
          {
            "description": "Set Disassembly Flavor to Intel",
            "text": "-gdb-set disassembly-flavor intel",
            "ignoreFailures": true
          }
        ],
        "preLaunchTask": "C/C++: gcc.exe build active file"
      }
    ],
    "version": "2.0.0"
}
```

tasks.json

```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe build active file",
            "command": "C:\\msys64\\ucrt64\\bin\\gcc.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",

                "${workspaceFolder}\\lib\\**.c",      
                
                "-I", 
                "${workspaceFolder}\\include",
                
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger.",
            "presentation": {
                "reveal": "silent",
                "close": true
            }
        }
    ],
    "version": "2.0.0"
}
```

# Debug Console Information

In my C project, I add

```json
"logging": {
    "trace": true,
    "traceResponse": true,
    "engineLogging": true
},
```

in launch.json. Here is the information of the failed program in debug console:

```
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (783) LaunchOptions{\"name\":\"C/C++: gcc.exe build and debug active file\",\"type\":\"cppdbg\",\"request\":\"launch\",\"program\":\"C:\\\\Users\\\\XX\\\\Desktop\\\\Project\\\\program.exe\",\"args\":[],\"stopAtEntry\":false,\"cwd\":\"C:\\\\Users\\\\XX\\\\Desktop\\\\Project\",\"environment\":[],\"externalConsole\":false,\"MIMode\":\"gdb\",\"logging\":{\"trace\":true,\"traceResponse\":true,\"engineLogging\":true},\"miDebuggerPath\":\"C:\\\\msys64\\\\ucrt64\\\\bin\\\\gdb.exe\",\"setupCommands\":[{\"description\":\"Enable pretty-printing for gdb\",\"text\":\"-enable-pretty-printing\",\"ignoreFailures\":true},{\"description\":\"Set Disassembly Flavor to Intel\",\"text\":\"-gdb-set disassembly-flavor intel\",\"ignoreFailures\":true}],\"preLaunchTask\":\"C/C++: gcc.exe build active file\",\"configSource\":\"workspaceFolder\",\"detail\":\"preLaunchTask: C/C++: gcc.exe build active file\",\"existing\":true,\"isDefault\":true,\"debuggerEvent\":\"playButton\",\"debugType\":\"run\",\"__sessionId\":\"3d81b850-ec95-48e4-9722-46d37c4dfd59\"}\r\n"},"seq":2}


1: (783) LaunchOptions{"name":"C/C++: gcc.exe build and debug active file","type":"cppdbg","request":"launch","program":"C:\\Users\\XX\\Desktop\\Project\\program.exe","args":[],"stopAtEntry":false,"cwd":"C:\\Users\\XX\\Desktop\\Project","environment":[],"externalConsole":false,"MIMode":"gdb","logging":{"trace":true,"traceResponse":true,"engineLogging":true},"miDebuggerPath":"C:\\msys64\\ucrt64\\bin\\gdb.exe","setupCommands":[{"description":"Enable pretty-printing for gdb","text":"-enable-pretty-printing","ignoreFailures":true},{"description":"Set Disassembly Flavor to Intel","text":"-gdb-set disassembly-flavor intel","ignoreFailures":true}],"preLaunchTask":"C/C++: gcc.exe build active file","configSource":"workspaceFolder","detail":"preLaunchTask: C/C++: gcc.exe build active file","existing":true,"isDefault":true,"debuggerEvent":"playButton","debugType":"run","__sessionId":"3d81b850-ec95-48e4-9722-46d37c4dfd59"}


--> C (runInTerminal-4): {"type":"request","command":"runInTerminal","arguments":{"kind":"integrated","title":"cppdbg: program.exe","cwd":"","args":["c:\\Users\\XX\\.vscode\\extensions\\ms-vscode.cpptools-1.18.0\\debugAdapters\\bin\\WindowsDebugLauncher.exe","--stdin=Microsoft-MIEngine-In-3mmsksdv.0hc","--stdout=Microsoft-MIEngine-Out-dr43zohu.lbe","--stderr=Microsoft-MIEngine-Error-dteiz1yb.cmg","--pid=Microsoft-MIEngine-Pid-2l2hdfzu.nfp","--dbgExe=C:\\msys64\\ucrt64\\bin\\gdb.exe","--interpreter=mi"],"env":{}},"seq":4}


--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1613) Wait for connection completion.\r\n"},"seq":6}


1: (1613) Wait for connection completion.


--> E (output): {"type":"event","event":"output","body":{"category":"stderr","output":"\r\n\r\n"},"seq":8}


--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (22383) Send Event AD7MessageEvent\r\n"},"seq":10}


1: (22383) Send Event AD7MessageEvent


--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/MIEngine/DebuggerAborted","data":{"VS.Diagnostics.Debugger.MIEngine.DebuggerName":"GDB","VS.Diagnostics.Debugger.MIEngine.LastSentCommandName":""}},"seq":12}


--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"17.4.30710.1","VS.Diagnostics.Debugger.HostVersion":"17.4.30710.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.ErrorCode":1005,"VS.Diagnostics.Debugger.Launch.IsError":true}},"seq":14}


--> R (launch-2): {"type":"response","request_seq":2,"success":false,"command":"launch","message":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information.","body":{"error":{"id":1005,"format":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information."}},"seq":16}
```

# Developer Tools Console Information

```
workbench.desktop.main.js:645  

WARN Via 'product.
json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.

workbench.desktop.main.js:645  

WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.

workbench.desktop.main.js:645   

ERR c.actions is not iterable: TypeError: c.actions is not iterable
    at i.f (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:778:24583)
    at i.c (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:778:24364)
    at d.a (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:778:24207)
    at d (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1530:1900)
    at d.setHandler (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1530:1773)
    at new i (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:778:24155)
    at g.j (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:1241)
    at g.createInstance (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:733)
    at new h (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1577:10971)
    at g.j (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:1241)
    at g.createInstance (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:640:733)
    at y.k (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1571:59409)
    at c (vscode-file://vscode-app/c:/Users/XX/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1571:59191)

workbench.desktop.main.js:645  

INFO [perf] Render performance baseline is 104ms

workbench.desktop.main.js:645  

INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session

workbench.desktop.main.js:149 

[Extension Host] activating extension

workbench.desktop.main.js:149 

[Extension Host] starting language server

DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/core/vs/base/worker/workerMain.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/core/vs/base/parts/sandbox/electron-sandbox/preload.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/core/vs/code/electron-sandbox/workbench/workbench.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/core/vs/workbench/workbench.desktop.main.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/vscode-textmate/release/main.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/xterm/lib/xterm.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/xterm-addon-canvas/lib/xterm-addon-canvas.js.map: Connection error: net::ERR_INTERNET_DISCONNECTED
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.80GB (1.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.40
cpptools|ms-|1.18.0

</details>

**Comment by roblourens** [comment]
Please file this on the repo for the extensions, thanks
