### ISSUE TITLE
Settings search sometimes stuck loading

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#196446]
Testing #196328

I find the search gets stuck every few searches. The below query is an example - I enter the query, I see the loading indicator at the top, but it never stops spinning:

![Image](https://github.com/microsoft/vscode/assets/25310137/b666f046-4e5d-4d7e-bde4-4dd8663240b1)

**Comment by bamurtaugh** [comment]
Even if I discard the search, the loading bar continues spinning:

![Image](https://github.com/microsoft/vscode/assets/25310137/c9e109b4-c62f-440e-ba2a-ea15f75d6aa2)

I can make it stop spinning by either completing another search or reloading.

**Comment by rzhao271** [comment]
Are there any devtools errors when that behaviour occurs?

**Comment by bamurtaugh** [comment]
Yes, looks like:

![Image](https://github.com/microsoft/vscode/assets/25310137/f33eb57f-1303-4255-ac5f-a5f927d23a39)

```
workbench.desktop.main.js:sourcemap:149 [Extension Host]% Object (at c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:168057)
w @ workbench.desktop.main.js:sourcemap:149
workbench.desktop.main.js:sourcemap:645  WARN Settings pattern "application.*" doesn't match any settings
workbench.desktop.main.js:sourcemap:645   ERR Cannot read properties of undefined (reading 'startLineNumber'): TypeError: Cannot read properties of undefined (reading 'startLineNumber')
    at n.i (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:133409)
    at vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:132436
    at Array.map (<anonymous>)
    at n.g (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:132424)
    at n.e (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:131592)
    at new n (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:131487)
    at D (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:130894)
    at s.filterSettings (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1670:1122)
    at s.searchModel (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:131053)
    at be.md (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2368:78144)
    at be.kd (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2368:76976)
    at be.hd (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2368:76747)
    at vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2368:76533
    at vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:149:14915
    at async be.dd (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2368:75074)
    at async be.ad (vscode-file://vscode-app/c:/Users/brmurtau/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2368:74147)
```

I'm able to repro this spinning behavior consistently with the query `i want my editor in a different color`.

**Comment by rzhao271** [comment]
No repro. Does the command `workbench.action.openRawDefaultSettings` work for you? If not, then I'm thinking that one of your extensions has a misconfigured setting that the Settings editor doesn't handle properly.

**Comment by bamurtaugh** [comment]
I just tried my typical repro `i want my editor in a different color`, and it did resolve successfully after ~5 seconds! Maybe this was a fleeting issue for a day or two for me. I'm going to close this for now, and I can report back if I experience it again.
