### ISSUE TITLE
Initializing JS/TS language features constantly dying and restarting

### ISSUE THREAD

**Issue by jjpepper** [microsoft/vscode#196528]
I have a WSL2 ts/js dev container with plugins disabled, but about 50 repos. I've spent so so many hours of looking at logs etc.  There is `Info` logs which look like errors saying: `Failed to load module `'ms-intellicode-typescript'` which I've pasted below.

If I blow away everything and start again, intellisense works again for about 10 minutes and then it goes back to dying constantly.  This is so frustrating and I have literally spent about 30 hours on this over the course of the last 2 years and never found anything that helps.

Is it just that I have too much code or something?

Any suggestions on how to diagnose or what I might look for in the logs would be appreciated.

My VS-code Help/About info:
```
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22635
```

"Error" log that is actually Info level.
```
Info 812  [04:50:43.747] Failed to load module 'ms-vsintellicode-typescript' from /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/node_modules: Error: Could not resolve JS module 'ms-vsintellicode-typescript' starting at '/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/node_modules'. Looked in: /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/ms-vsintellicode-typescript/package.json, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/ms-vsintellicode-typescript.js, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/ms-vsintellicode-typescript.jsx, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/ms-vsintellicode-typescript/index.js, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/ms-vsintellicode-typescript/index.jsx, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/node_modules/ms-vsintellicode-typescript/package.json, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/node_modules/ms-vsintellicode-typescript.js, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/node_modules/ms-vsintellicode-typescript.jsx, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/node_modules/ms-vsintellicode-typescript/index.js, /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/node_modules/ms-vsintellicode-typescript/index.jsx, /vscode/vscode-server/bin/linux-x64/node_modules/ms-vsintellicode-typescript/package.json, /vscode/vscode-server/bin/linux-x64/node_modules/ms-vsintellicode-typescript.js, /vscode/vscode-server/bin/linux-x64/node_modules/ms-vsintellicode-typescript.jsx, /vscode/vscode-server/bin/linux-x64/node_modules/ms-vsintellicode-typescript/index.js, /vscode/vscode-server/bin/linux-x64/node_modules/ms-vsintellicode-typescript/index.jsx, /vscode/vscode-server/bin/node_modules/ms-vsintellicode-typescript/package.json, /vscode/vscode-server/bin/node_modules/ms-vsintellicode-typescript.js, /vscode/vscode-server/bin/node_modules/ms-vsintellicode-typescript.jsx, /vscode/vscode-server/bin/node_modules/ms-vsintellicode-typescript/index.js, /vscode/vscode-server/bin/node_modules/ms-vsintellicode-typescript/index.jsx, /vscode/vscode-server/node_modules/ms-vsintellicode-typescript/package.json, /vscode/vscode-server/node_modules/ms-vsintellicode-typescript.js, /vscode/vscode-server/node_modules/ms-vsintellicode-typescript.jsx, /vscode/vscode-server/node_modules/ms-vsintellicode-typescript/index.js, /vscode/vscode-server/node_modules/ms-vsintellicode-typescript/index.jsx, /vscode/node_modules/ms-vsintellicode-typescript/package.json, /vscode/node_modules/ms-vsintellicode-typescript.js, /vscode/node_modules/ms-vsintellicode-typescript.jsx, /vscode/node_modules/ms-vsintellicode-typescript/index.js, /vscode/node_modules/ms-vsintellicode-typescript/index.jsx, /node_modules/ms-vsintellicode-typescript/package.json, /node_modules/ms-vsintellicode-typescript.js, /node_modules/ms-vsintellicode-typescript.jsx, /node_modules/ms-vsintellicode-typescript/index.js, /node_modules/ms-vsintellicode-typescript/index.jsx
    at resolveJSModule (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:42251:11)
    at Object.require (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:8500:30)
    at _Project.importServicePluginSync (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:176143:27)
    at _ProjectService.requestEnablePlugin (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:181331:44)
    at InferredProject2.enablePlugin (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:177401:25)
    at InferredProject2.enableGlobalPlugins (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:177397:12)
    at new InferredProject2 (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:177644:10)
    at _ProjectService.createInferredProject (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:180076:21)
    at _ProjectService.getOrCreateInferredProjectForProjectRootPathIfEnabled (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:180019:19)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:179200:26)
    at _ProjectService.assignProjectToOpenedScriptInfo (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:180832:12)
    at /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:181062:64
    at flatMap (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:2600:17)
    at _ProjectService.applyChangesInOpenFiles (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:181062:24)
    at updateOpen (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:182242:29)
    at /vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:184838:69
    at IpcIOSession.executeWithRequestId (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:184830:14)
    at IpcIOSession.executeCommand (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:184838:29)
    at IpcIOSession.onMessage (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:184880:51)
    at process.<anonymous> (/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/extensions/node_modules/typescript/lib/tsserver.js:186461:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Info 813  [04:50:43.747] Couldn't find ms-vsintellicode-typescript
```

**Comment by jjpepper** [comment]
@mjbvz I'm now getting the same behaviour (constantly restarting TS/JS language features) but I don't seen any "Failed to load module" in the logs whatsoever.

**Comment by LikeRudin** [comment]
Hello, sir. I fixed the same issue by removing improper types from my code. 
..
first of all sorry for my english, 

first , trying below 3 actions..
0. select typescript version as workspace version
1. Reinstalled VS Code.
2. Created a .vscode folder and configured the "typescript.tsdk" setting.
3. Deleted all extensions and reinstalled them.

Unfortunately, none of these actions had any effect for me.

 However, I noticed that when i opened other project, intelliSense is working well.

- only one project showed infinite loading
-in my project having error, sometimes IntelliSense worked, and changed to infinite loading state
 
 so i tried to find out what condition kills intelliSens

- now i fixed issue by below steps

1. close all the file in vscode
2. open file one by one , check intelliSense works (not infinite loading)
3. i found that opening a specific file triggers kill intellisens and change tooltip to "loading"...
4. fix unproper type on my interface

Upon closer inspection of my code in that "specific "file, 
 I discovered that I extends an undefined type . 
After removing it, my IntelliSense functionality was resurrected.


```
//"extends Text" code killed intellisense on project!

interface EditForm extends Text {
  email: string;
  phone: string;
  introduction: string;
  imagePath: string;
  password: string;
}
```

**Comment by jjpepper** [comment]
@LikeRudin I don't have the same issue.  I don't have any occurrence of `<syntax> Forking` in my log output.  @mjbvz any ideas?

**Comment by mjbvz** [comment]
Sorry this fell off my radar

Based on the call stack, this looks like it's caused by the IntelliCode plugin/extension. If you're still seeing the issue, please start by filing an issue against them
