### ISSUE TITLE
IPC handle is longer than 103 chars

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#196543]
Testing #196332

Not sure if this is an actual OS limitation (I'm on macOS):
```
Downloading VS Code insiders from https://update.code.visualstudio.com/latest/darwin-arm64/insider
Downloading VS Code [==============================] 100%
Downloaded VS Code into /Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders

Downloaded VS Code into /Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders
WARNING: IPC handle "/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/user-data/1.84-main.sock" is longer than 103 chars, try a shorter --user-data-dir
[main 2023-10-25T06:35:35.054Z] Could not delete obsolete instance handle Error: ENOENT: no such file or directory, unlink '/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/user-data/1.84-main.sock'
    at unlinkSync (node:original-fs:1829:3)
    at ye.e (/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:108:4085)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:108:1228
    at async ye.a (/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:108:1115) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/user-data/1.84-main.sock'
}
[main 2023-10-25T06:35:35.055Z] Error: ENOENT: no such file or directory, unlink '/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/user-data/1.84-main.sock'
    at unlinkSync (node:original-fs:1829:3)
    at ye.e (/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:108:4085)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:108:1228
    at async ye.a (/Users/chrmarti/Development/repos/vscode-extension-samples/helloworld-test-sample/.vscode-test/vscode-darwin-arm64-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:108:1115)
Exit code:   1
Failed
```

**Comment by chrmarti** [comment]
This seems to work on first run, but then fails on the second and later runs.

**Comment by chrmarti** [comment]
Deleting the `.vscode-test` folder works around it.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-test/issues/232
