### ISSUE TITLE
Error in Settings editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19663]
From @chrmarti 

- VSCode Version: Code - Insiders 1.9.0-insider (c74d41044d7928c3a4916f2d8b2301f6129ab727, 2017-01-31T13:11:16.234Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|0.8.1|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.2.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.2|
|ghlink|dt|0.0.4|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.8.0|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|

Just seen, but does not reproduce:
```
shell.ts:437 Cannot read property 'clearFocus' of null: TypeError: Cannot read property 'clearFocus' of null
    at Array.<anonymous> (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:6917)
    at e.invoke (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26950)
    at e.fire (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:30440)
    at t.clear (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:6290)
    at t.render (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:31119)
    at t.filterPreferences (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:22731)
    at t.filterPreferences (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:7741)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:118:6957
    at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12333)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)e.onUnexpectedError @ shell.ts:437
messageService.ts:126 Unable to open 'settings.json': Cannot read property 'filterPreferences' of null.: Error: Unable to open 'settings.json': Cannot read property 'filterPreferences' of null.
    at t.doHandleSetInputError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:132:787)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:132:393
    at Object.v [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)
    at _run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17739)
    at _completed (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17180)
    at u (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20718)
    at Y.then.o.(anonymous function) (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:20935)
    at Object.g [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12333)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15911)e.doShow @ messageService.ts:126
```

**Comment by sandy081** [comment]
@chrmarti Is there possibility to know how you get into this? Are you able to open the settings editor  after this? Where is this error shown? In the console or a message box ?

**Comment by chrmarti** [comment]
This was in both a message box and the console. The settings editor did not open with that attempt, but a retry succeeded without error, no reload/restart needed.

**Comment by sandy081** [comment]
Hmm strange. Not sure what and how could have caused this. May be some undisposed listeners. I am cleaning up the code to fix such cases.

**Comment by sandy081** [comment]
This would be fixed with latest refactorings

**Comment by bpasero** [comment]
Also have not seen this.
