### ISSUE TITLE
NO notebook document for 'file://*.ipynb'

### ISSUE THREAD

**Issue by andrew-weisman** [microsoft/vscode#196740]
Type: <b>Bug</b>

Can't reliably reproduce. When I'm working in a Jupyter notebook, in the past few days, after executing 1-20 cells, I'm getting the error "NO notebook document for 'file://*.ipynb'" and then the "Go To" button at the top keeps on spinning, hitting Interrupt does nothing, and Restart is grayed out. My only recourse is to restart VS Code completely. It happens even after rebooting my machine, fully updating WSL (I'm connecting to the WSL remote), and ensuring VS Code and its extensions are fully updated. This is very disruptive; please help! Thanks!

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.44GB (11.74GB free)|
|Process Argv|--crash-reporter-id a11beee0-9324-4740-85d9-6f0e82af3399|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|Memory (System)|15.36GB (13.40GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.81.8
vscode-markdownlint|Dav|0.52.0
todo-tree|Gru|0.0.226
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.41
jupyter|ms-|2023.9.1102792234
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
shiny-python|Pos|0.1.5
r|REd|2.8.2
pyshiny|rst|0.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30866519
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by Neclow** [comment]
Same issue here, I'm adding my Jupyter log just in case:

<html>
<body>


CPUs | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 31.71GB (22.23GB free)
Process Argv | --crash-reporter-id b8b3f4e6-6ec3-4cae-8b80-06694709bc3a
Screen Reader | no
VM | 0%


</body>
</html>

<html>
<body>


Remote | SSH
-- | --
OS | Linux x64 5.15.0-78-generic
CPUs | AMD Ryzen Threadripper PRO 5995WX 64-Cores (128 x 3991)
Memory (System) | 251.50GB (216.87GB free)
VM | 0%


</body>
</html>

```
Visual Studio Code (1.83.1, ssh-remote, desktop)
Jupyter Extension Version: 2023.9.1102792234.
Python Extension Version: 2023.18.0.
Platform: linux (x64).
Workspace folder ~/src/my_project, Home = /home/my_user/
21:00:09.563 [info] User belongs to experiment group 'NewJupyterSession'
21:00:14.898 [info] Start refreshing Kernel Picker (1698354014898)
21:00:14.943 [info] Using Pylance
21:00:18.675 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd07597a5efbd94c847325424dfc8686c4d158a7360d95467620d1c15956fe54889.~mambaforge/envs/phylo/python.~mambaforge/envs/phylo/python.-m#ipykernel_launcher  (Python Path: ~/mambaforge/envs/phylo/bin/python, Conda, phylo, 3.10.11) for '~/src/my_project/drafts.ipynb' (disableUI=true)
21:00:22.750 [info] End refreshing Kernel Picker (1698354014898)
21:00:49.168 [info] Process Execution: ~/mambaforge/envs/phylo/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
21:00:49.320 [info] Process Execution: ~/mambaforge/envs/phylo/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9013 --control=9011 --hb=9010 --Session.signature_scheme="hmac-sha256" --Session.key=b"112f0e50-6c10-4c71-88b5-244853ce0ce3" --shell=9012 --transport="tcp" --iopub=9014 --f=~.local/share/jupyter/runtime/kernel-v2-2387175TuBKqu1eZg8b.json
    > cwd: ~/src/my_project
21:00:52.526 [info] ipykernel version & path 6.19.2, ~/mambaforge/envs/phylo/lib/python3.10/site-packages/ipykernel/__init__.py for ~/mambaforge/envs/phylo/bin/python
21:00:53.351 [warn] StdErr from Kernel Process ~mambaforge/envs/phylo/lib/python3.10/site-packages/traitlets/traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
21:00:53.355 [warn] StdErr from Kernel Process ~mambaforge/envs/phylo/lib/python3.10/site-packages/traitlets/traitlets.py:2495: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '112f0e50-6c10-4c71-88b5-244853ce0ce3' instead of 'b"112f0e50-6c10-4c71-88b5-244853ce0ce3"'.
  warn(
21:00:53.579 [info] Process Execution: ~/mambaforge/envs/phylo/bin/python -m pip list
21:00:54.284 [info] Process Execution: ~/mambaforge/envs/phylo/bin/python ~.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/pythonFiles/printJupyterDataDir.py
21:00:57.185 [info] Handle Execution of Cells 0 for ~/src/my_project/drafts.ipynb
21:00:57.316 [info] Kernel acknowledged execution of cell 0 @ 1698354057314
21:01:08.327 [info] End cell 0 execution @ 1698354068326, started @ 1698354057314, elapsed time = 11.012s
...
21:04:47.310 [info] Handle Execution of Cells 55 for ~/src/my_project/drafts.ipynb
21:04:47.345 [info] Kernel acknowledged execution of cell 55 @ 1698354287344
21:04:56.233 [info] End cell 56 execution @ 1698354296233, started @ 1698354287344, elapsed time = 8.889s
21:05:02.892 [info] Dispose Kernel '~/src/my_project/drafts.ipynb' associated with '~/src/my_project/drafts.ipynb'
21:05:02.895 [info] Dispose Kernel process 2387391.
21:05:03.713 [error] Notebook not found for Cell ~src/my_project/drafts.ipynb
```

I'll note that I don't have to restart VSCode completely, but have to reload the window to relaunch my notebook.

**Comment by sanjeevg15** [comment]
Just faced this issue a few minutes ago. I realized that using the `autoreload` magic function is causing the issue for me. If I remove the magic function, it works fine. This is definitely not convenient but is a temporary workaround. No idea what the exact cause for this is.

Specifically, removing the following two lines of code helped: 

    %load_ext autoreload    
    %autoreload 2

**Comment by cmditch** [comment]
Also hitting this frequently.

**Comment by kgoebler** [comment]
yep same here... similar setup to andrew

**Comment by JackElsey** [comment]
I'm encountering this issue in a GitHub codespace.

**Comment by dummyindex** [comment]
A similar issue here when running VS Code locally and connect to a workstation via VSCode remote. Resources should not be an issue in my case. (128GB RAM remote with enough disk space)
"NO notebook document for ..."

Local: Windows 11 Pro
Remote: Ubuntu 22.04

**Comment by charchit7** [comment]
Same here.

**Comment by msukkari** [comment]
Hitting this as well since a couple hours ago. Very difficult to repro - but its happening to me when I add a new cell that calls the pytorch `conv2d` method. Not sure if the logic in the cell is relevant to the crash or not, it's just what I was doing in a new cell when I hit this issue

**Comment by charchit7** [comment]
Hi @msukkari @dummyindex @cmditch @JackElsey any workaround this you guys found? Please help.

**Comment by mathfather** [comment]
Same here; have tried to use an older version of Jupyter plugin (released in Sept.) and the same bug happened.

**Comment by charchit7** [comment]
Disabling pylance works. 
This could be a possible reason : any of you guys have the huggingface code completion llm-vscode enabled?
I was getting a side pop-up saying that the free-teir service has ended, maybe it's interrupting pylance and crashing!
Not 100% sure.

**Comment by mathfather** [comment]
> Disabling pylance works. This could be a possible reason : any of you guys have the huggingface code completion llm-vscode enabled? I was getting a side pop-up saying that the free-teir service has ended, maybe it's interrupting pylance and crashing! Not 100% sure.

Yeah it seems to be a pylance issue; switch to an older version of pylance solve this for now.

**Comment by gongwolf** [comment]
Same here, just happened recently.

**Comment by liuzheng-arctic** [comment]
Same here, within the last several hours. Turning off the pylance seems to help.

**Comment by thatmee** [comment]
> Disabling pylance works. This could be a possible reason : any of you guys have the huggingface code completion llm-vscode enabled? I was getting a side pop-up saying that the free-teir service has ended, maybe it's interrupting pylance and crashing! Not 100% sure.

This works for now, thank you!

**Comment by ddddavid-he** [comment]
Same annoying issue here

**Comment by lan2720** [comment]
Same issue starting today.

**Comment by ChainShoeTall** [comment]
Same issues on WSL

**Comment by HuipengXu** [comment]
same issue .....

**Comment by nVentis** [comment]
Getting this since a few hours, wasn't an issue before. Turning off Pylance as workaround seems to work

**Comment by DoManhQuang** [comment]
same issue :(

**Comment by MedAzizTousli** [comment]
Same here.

**Comment by codename5281** [comment]
Same issue here, deactivating pylance seems to have done the trick.

**Comment by jlins-ionos** [comment]
> Same here. How to downgrade pylance?

Go to Extensions > Pylance > Dropdown besides "Uninstall" > Install Another Version

**Comment by JnsLns** [comment]
> Same here. How to downgrade pylance?

Go to Extensions > Pylance > Dropdown besides "Uninstall" > Install Another Version

**Comment by jphme** [comment]
Same issue here. Switched to pylance `2023.10.40` from 2023.10.50, hopefully this will fix it (will report back after a while).

**Comment by miroblog** [comment]
- Install Another Version
> https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance 
> find 2023.10.40 download and put inside vscode
> right click, install vsix extension

**Comment by Brogis1** [comment]
The above solution works for me. Thanks a lot to all!

**Comment by loodvn** [comment]
Could someone please **open an associated issue on the Pylance repo**? https://github.com/microsoft/pylance-release 
I couldn't find any similar issues reported (searching issues for "NO notebook document for"), and I think it might be worth linking that issue to this thread since so many people are having the issue.

I've got a deadline today so can't gather all the logs/info and wait for the error again to file a proper issue (https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue), but can do this next week if no-one else gets to it 👍

**Comment by gyohng** [comment]
same issue

**Comment by knslee07** [comment]
Same issue

**Comment by cmditch** [comment]
> Hi @msukkari @dummyindex @cmditch @JackElsey any workaround this you guys found? Please help.

As mentioned above, rolling back pylance to the previous release (2023.10.40) has fixed the issue.

**Comment by eliasinul** [comment]
Inside VSCODE extension; rollbacking pylance to the previous release (2023.10.40) has proven to be a workaround !

**Comment by calebrob6** [comment]
Same issue

**Comment by batterylake** [comment]
Same issue

**Comment by Zhuifeng414** [comment]
The same thing happened to me starting yesterday. I have to restart VScode; sometimes, I add .copy() after the variable will solve this problem. But I'm confused about why this happened.

**Comment by jerrylin96** [comment]
Same thing happening to me

**Comment by cmendesfirmino** [comment]
Same thing here, started today

**Comment by gonzalezf** [comment]
Same issue here, since today

**Comment by cralbors** [comment]
Me too

**Comment by sqj-star** [comment]
Same issue，i try to downgrade

**Comment by tszslovewanpu** [comment]
Spend whole day restarting the kernel. Turns out there was a problem with the newly updated pylance. Rolling back to 2023.10.40 is effective~

**Comment by zc0616** [comment]
Same issue！

**Comment by hjerpe** [comment]
Same error.

**Comment by yukihiroK** [comment]
Same.
At first I didn't get that notification, so I waited forever for the added cell to start running.
Sometimes a reload window would fix it.

**Comment by niniack** [comment]
If only there was a button you could press to express that you're having the same issue...

Seriously, commenting "same" a million times helps nobody. It buries the comments trying to be helpful.

**Comment by PhenixZhang** [comment]
Same here! When I'm working in a Jupyter notebook, in the past few days, after executing 1-20 cells I'm getting the error "NO notebook document for 'file://*.ipynb'" and then the "Go To" button at the top keeps on spinning, hitting Interrupt does nothing, and Restart is grayed out. My only recourse is to restart VS Code completely, but the problem occured again. It's a real develop envirenment, so that's a wide problem?

**Comment by lemontealala** [comment]
Same issue here! I have restarted my jupyter many times today and it's annoying. And my pip list doesn't contain the 'pylance' module, so it should be another issue... What's wrong?

**Comment by hjerpe** [comment]
The solution to downgrade the VS code extension `Pylance` worked for me too.

As specified by [tszslovewanpu](https://github.com/tszslovewanpu):
_Spend whole day restarting the kernel. Turns out there was a problem with the newly updated pylance. Rolling back to 2023.10.40 is effective~_

**Comment by Irislucent** [comment]
Just don't use Notebooks. Everyday using ipynb and not pure py is a disaster...

**Comment by Matesanz** [comment]
:point_right:  **Visual solution to how to workaround this issue:**

1. Go to Extensions
2. Select `Pylance`
3. Dropdown on `uninstall` and select `Switch to another version`
4. Select `v2023.10.40`

![Dibujo (3)](https://github.com/microsoft/vscode/assets/44867923/e1851697-206a-446f-8dc5-ff4b28f45508)

:warning:  The solution has been already posted **multiple times** (thanks to contributors):

https://github.com/microsoft/vscode/issues/196740#issuecomment-1783747152,
https://github.com/microsoft/vscode/issues/196740#issuecomment-1783219049,
https://github.com/microsoft/vscode/issues/196740#issuecomment-1782913039,
https://github.com/microsoft/vscode/issues/196740#issuecomment-1783147505,
https://github.com/microsoft/vscode/issues/196740#issuecomment-1782800860,
https://github.com/microsoft/vscode/issues/196740#issuecomment-1782196400

:stop_sign:  So **PLEASE stop saying** `same issue here` (or similar)

**Comment by ian-jihoonpark** [comment]
This problem may be caused by the accumulated visualized outputs that you made.

Clear all outputs in your .ipynb!!

**Comment by rchiodo** [comment]
If anybody is having this issue, can you try the prerelease version of the Pylance extension: 2023.10.53. We think we've fixed the issue there (we were able to reproduce this problem with a codespace) and the issue no longer reproduces with 2023.10.53.

Thanks and sorry for the bug.

**Comment by hasush** [comment]
Confirm same symptoms and errors as well as disabling pylance fixes errors.

**Comment by rchiodo** [comment]
> Confirm same symptoms and errors as well as disabling pylance fixes errors.

@hasush Can you try upgrading pylance to 2023.10.53?

**Comment by jgbos** [comment]
@rchiodo I have updated to `2023.10.53` and I'm still getting this error.

**Comment by rchiodo** [comment]
@jgbos the output from the 'Python Language Server' output tab would help.

**Comment by jgbos** [comment]
@rchiodo Doesn't seem to be anything useful in that:

```
2023-10-30 14:57:47.200 [info] [Info  - 2:57:47 PM] (1914568) Pylance language server 2023.10.53 (pyright d7012d0d) starting
2023-10-30 14:57:47.205 [info] [Info  - 2:57:47 PM] (1914568) Server root directory: /home/justin/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.53/dist
2023-10-30 14:57:47.206 [info] [Info  - 2:57:47 PM] (1914568) Starting service instance "myenv"
2023-10-30 14:57:47.247 [info] [Info  - 2:57:47 PM] (1914568) Setting pythonPath for service "myenv": "/home/gridsan/JU17693/.conda/envs/othr/bin/python"
2023-10-30 14:57:47.247 [info] [Info  - 2:57:47 PM] (1914568) Setting environmentName for service "myenv": "3.11.5 (myenvconda)"
2023-10-30 14:57:47.289 [info] [Info  - 2:57:47 PM] (1914568) Assuming Python version 3.11
2023-10-30 14:57:47.638 [info] [Info  - 2:57:47 PM] (1914568) Found 80 source files
```

When I first load everything works as normal, after a few minutes this error pops up and I can no longer execute any notebooks.

I do see a `Dispose Kernel` message in the `Jupyter` output.

**Comment by rchiodo** [comment]
When we repro'd the problem locally we saw a number of debug assertions in the Pylance log. That was a known bug in 2023.10.50 and may not have had anything to do with the root cause of this problem.

**Comment by pupster90** [comment]
@rchiodo , Thanks for the fast bug fix! I updated to the latest pylance version (2023.10.53). So far, it seems to have resolved the problem. I've only been coding for about 1 hour, though. I put an updated of the "No file" problem comes back

**Comment by rebornix** [comment]
@jgbos when you reproduce this issue again, can you please open Dev Tools (F1 -> Toggle Developer Tools) and share the logs from the Dev Tools with us?

**Comment by ilgaribaldi** [comment]
@jgbos try removing pylance altogether instead of downgrading or downgrade to even older version, and see if you still get the issue. Make sure you reload vscode for the changes to make effect every time you install/uninstall/downgrade pylance.

**Comment by nVentis** [comment]
Can confirm 2023.10.53 fixes the issue, at least up to now.

**Comment by cralbors** [comment]
Switching to the pre-release version didn't fix the issue for me. Removing Pylance worked.

**Comment by pbower** [comment]
Same issue. Hate this. please fix.

**Comment by pupster90** [comment]
@rchiodo,  If possible, I'd recommend switching pylance, `v2023.10.53 ` from "Pre-Release" to "Release". You'd be helping out a lot of people.

**Comment by zc0616** [comment]
> If anybody is having this issue, can you try the prerelease version of the Pylance extension: [2023.10.53](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/vscode-pylance/2023.10.53/vspackage). We think we've fixed the issue there (we were able to reproduce this problem with a codespace) and the issue no longer reproduces with 2023.10.53.
> 
> Thanks and sorry for the bug.

It was fine in the morning when I changed it to 2023.10.53, but now the same error has reappeared.

**Comment by ConfessionBalloon** [comment]
Switched to pylance 2023.10.40 in vscode, it work for me

**Comment by tomalbrecht** [comment]
I have the same problem, but I have not pylance installed.

**Comment by StellaLiu-gogogo** [comment]
> Switched to pylance 2023.10.40 in vscode, it work for me

This also seems works for me.

**Comment by jgbos** [comment]
@ilgaribaldy

> @jgbos try removing pylance altogether instead of downgrading or downgrade to even older version, and see if you still get the issue. Make sure you reload vscode for the changes to make effect every time you install/uninstall/downgrade pylance.

It looks like reverting to an older version has fixed the problem.

**Comment by Cb1ock** [comment]
I have reverted to an older version of PyLance, and it did fix the problem. Thanks to @hjerpe and @Matesanz

**Comment by Juanmaria-rr** [comment]
I started to had the same problem today and just switched to PyLance 2023.10.40 and it solved the issue. Thanks!

**Comment by danieltudosiu** [comment]
I have the same issue. I tried to switch to pylance 2023.10.40 and it is still there. For me the issue is triggered by copy pasting content within and between cells.

**Comment by rchiodo** [comment]
I think the problem is related to URI conversions. I can't reproduce the message about the 'No notebook document' but I can get the kernel to stop running.

Reproduction steps:

1. Open VS code from WSL
2. Create notebook
3. Save to disk
4. Def a function in a cell
5. Call function from another cell
6. Run all the cells
7. Goto def for the function - new notebook should open that looks like the same tab
8. Run cells in the other notebook
9. Close the other notebook
10. Go back to running cells in the original tab
11. Cells don't run. You can then see this in the 'Jupyter' output tab:

19:35:14.592 [error] Notebook not found for Cell ~/test/test_pyright/test.ipynb

I believe this is caused by recent changes in Pylance to support virtual workspaces. We're testing a fix at the moment.

**Comment by brandonhoranSift** [comment]
Same issue here. Looking forward to the fix going forward rather than simply downgrading the Pylance extension

**Comment by cyclux** [comment]
To the ones who say they still have the issue in 2023.10.40: Check and make sure you are in the environment in which you downgraded. In my case, for example, I re-encountered the issue while being in another instance (Docker dev environment). First I thought the issue now also reappeared in 2023.10.40. Then however realized that I am in another environment and need to downgrade there as well. I can imagine this circumstance could also happen using different profiles.

**Comment by jacksimpsoncartesian** [comment]
Same issue here with WSL and VS Code - happening to be multiple times a day at the moment.

**Comment by lynn-1998** [comment]
> A similar issue here when running VS Code locally and connect to a workstation via VSCode remote. Resources should not be an issue in my case. (128GB RAM remote with sufficient disk space) "NO notebook document for ..."
> 
> Local: Windows 11 Pro Remote: Ubuntu 22.04 Start date: 10/26 EST, not sure if it is due to updates
> 
> Update: switching pylance version works for me. Extension -> pylance -> uninstall drop-down -> switch version (in my case pylance v2023.9.30). Thanks to @charchit7 for the solution below.

Same problem. It works for me.

**Comment by vatojavier** [comment]
Same, it's cracking my balls

**Comment by pleyad** [comment]
I upgraded to the pre-release (`v2023.10.53`) and the error still persists.
I am working on a server via Remote-SSH.

**Comment by opassos** [comment]
Although there are several reports of people fixing this by rolling to 2023.10.40. I remember having this issue before that was released.

**Comment by JingtongSu** [comment]
Downgrading to `v2023.10.40` works for me. I'm working on a server via Remote-SSH.

**Comment by jacksimpsoncartesian** [comment]
Hope there's a fix soon, I'm having to close and restart VS Code a couple of dozen times a day at the moment because of this issue.

**Comment by faering** [comment]
Same issue in Win11 and WSL Debian, reinstalling older version of pylance==v2023.10.30 has fixed the issue.

**Comment by oguzserbetci** [comment]
It works for me when I disable Pylance for the workspace.

**Comment by JohnGiorgi** [comment]
Also facing this issue working on a remote server via `Remote-SSH`. Disabling `pylance` and restarting VSCode immediately fixes the issue (didn't try downgrading `pylance` 🤷)

**Comment by Happy2Git** [comment]
@nVentis Thanks!

**Comment by jayleen-git** [comment]
I encounter the same issue when working on SSH. It's quite annoying that after disabling Pylance, I can't navigate to functions.

**Comment by rchiodo** [comment]
This should be fixed in the latest release for Pylance that went out last night.

**Comment by sungmin-hwang-cfm** [comment]
With 2023.11.11, I encountered the following errors. I am not sure this is related or not. 
```
Error: Debug Failure. Cell path not found for cell vscode-notebook-cell://ssh-remote%XXX/sim_gen.ipynb#X66sdnNjb2RlLXJlbW90ZQ%3D%3D
    at _0x5e8922.getNotebookCellPath (/XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:261668)
    at _0x8f195a.decodeTextDocumentUri (/XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:230980)
    at _0x45a7e7.onDidCloseTextDocument (/XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:901599)
    at /XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/pyright.bundle.js:1:1144202
    at /XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1234062
    at oe (/XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1234284)
    at /XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1230224
    at Immediate.<anonymous> (/XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1230244)
    at processImmediate (node:internal/timers:476:21)

2023-11-03 17:01:28.024 [info] [Error - 5:01:28 PM] Server process exited with code 1.
2023-11-03 17:01:28.026 [info] [Info  - 5:01:28 PM] Connection to server got closed. Server will restart.
2023-11-03 17:01:28.026 [info] true
2023-11-03 17:01:28.499 [info] [Info  - 5:01:28 PM] (9864) Pylance language server 2023.11.11 (pyright 64c9c3ff) starting
2023-11-03 17:01:28.499 [info] [Info  - 5:01:28 PM] (9864) Server root directory: /XXX/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist
2023-11-03 17:01:28.506 [info] [Error - 5:01:28 PM] Server initialization failed.
2023-11-03 17:01:28.506 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

----- [2809a1f5f679fe8602c339647a7242b44b9ec6790ed196d53b7e0d47ccd7cb23]

  Code: -32603 
```

**Comment by rchiodo** [comment]
Thanks for the feedback. That should be a dupe of this error:
https://github.com/microsoft/pylance-release/issues/5071
