### ISSUE TITLE
Nothing shows in the Settings

### ISSUE THREAD

**Issue by pertsevds** [microsoft/vscode#196852]
Type: <b>Bug</b>

Nothing shows in the Settings. Just black screen with only User and Workspace tabs.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (2.22GB free)|
|Process Argv|--crash-reporter-id cca31b91-28b7-4e4c-9a97-0ff3d7575112|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-toggle-quotes|Bri|0.3.6
multi-cursor-case-preserve|Car|1.0.5
vscode-dash|dee|2.4.0
gitlens|eam|14.4.1
shell-format|fox|7.2.5
go|gol|0.39.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.27.0
remote-containers|ms-|0.315.1
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
hexeditor|ms-|1.9.12
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
git-config-user-profiles|onl|1.2.0
shellcheck|tim|0.34.0
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by pertsevds** [comment]
![alt text](https://github.com/pertsevds/uploads/blob/d69c9d54877d2b267894b45e03a5f5d3d0b3a5ad/2023-10-27_22-06-15.png?raw=true)

**Comment by pertsevds** [comment]
Looks like a connectivity issue.
Logs:
```
2023-10-27 22:38:43.588 [error] XHR failed: Error: XHR failed
    at y.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:1261)
2023-10-27 22:39:29.742 [error] XHR failed: Error: XHR failed
    at y.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:1261)
```

**Comment by pertsevds** [comment]
Developer Tools log:
`Failed to load resource: net::ERR_CONNECTION_TIMED_OUT https://github.gallerycdn.vsassets.io/extensions/github/copilot/1.130.0/1698280927549/Microsoft.VisualStudio.Code.Manifest`

Hmm.
I'm from Russia and I can't open this link.
Well, with VPN it works.

**Comment by pertsevds** [comment]
Closing as it's not a VSCode issue.
