### ISSUE TITLE
Unable to unstage single file in SCM view

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#197012]
The SCM view seems frozen.
I'm seeing this issue on the latest Insiders on Windows with Copilot Chat enabled.

Devtools error logs

```
event.ts:1030 [hga] REFUSES to accept new listeners because it exceeded its threshold by far
q @ event.ts:1030
event.ts:1030 [000] REFUSES to accept new listeners because it exceeded its threshold by far
q @ event.ts:1030
event.ts:879 [000] potential listener LEAK detected, having 526 listeners already. MOST frequent listener (352):
check @ event.ts:879
event.ts:880 Error
    at i.create (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:55295)
    at x.q [as onMouseDown] (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:931)
    at new $ (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:631:524)
    at g._computeFn (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:736:25149)
    at g.v (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:14699)
    at g.get (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:14513)
    at g.reportChanges (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:7590)
    at g.endUpdate (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:12335)
    at g.endUpdate (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:15275)
    at g.endUpdate (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:15275)
    at y.finish (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:8713)
    at n.set (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:10151)
    at A.a (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:736:22148)
    at A.h (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:149:19201)
    at A.g (vscode-file://vscode-app/c:/Users/raymondzhao/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:149:19185)
check @ event.ts:880
log.ts:431  WARN [AiRelatedInformationService]: Related information provider timed out
```

Screencaps

![Screencap showing me clicking on a file to unstage it, but nothing happens](https://github.com/microsoft/vscode/assets/7199958/22a413fd-b05d-49a1-8f32-3870d0f6f95c)

**Comment by TylerLeonhardt** [comment]
To me, this looks like the Ext Host process is just spinning on something else.

**Comment by rzhao271** [comment]
That was probably it, then. Will see if I can repro it more today.

**Comment by rzhao271** [comment]
Closing as can't repro
