### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19706]
Just got this running "out of sources" opening a typescript file on latest:

```
//Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js:237 Cannot read property 'startsWith' of undefined: TypeError: Cannot read property 'startsWith' of undefined
    at TypeScriptServiceClient.asUrl (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/typescriptServiceClient.js:556:21)
    at LanguageProvider.configFileDiagnosticsReceived (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/typescriptMain.js:265:49)
    at TypeScriptServiceClientHost.configFileDiagnosticsReceived (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/typescriptMain.js:354:22)
    at TypeScriptServiceClient.dispatchMessage (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/typescriptServiceClient.js:670:31)
    at Reader.global.startService.modulePath.then.then.modulePath.servicePromise.electron.fork.reader.wireProtocol_1.Reader [as callback] (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/typescriptServiceClient.js:349:34)
    at Reader.onLengthData (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/utils/wireProtocol.js:139:18)
    at Socket.global.constructor.type.readable.on (/Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/utils/wireProtocol.js:115:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

```

**Comment by mjbvz** [comment]
I believe 63929e0d209c730960804264eebd970bd8712b45 fixed this. I'll don't see this error anymore after adding the extra null check.
