### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: /Users/josephcaburnay/Projects/kwartrack/node_modules/next/index.d.ts linked to nonexistent file /Users/josephcaburnay/Projects/kwartrack/node_modules/.pnpm/next@14.0.1_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0_sass@1.68.0/node_modules/next/index.d.ts

### ISSUE THREAD

**Issue by caburj** [microsoft/vscode#197102]
Type: <b>Bug</b>

**TypeScript Version:** 5.2.2

**Steps to reproduce crash**

I opened the file with lots of functions in it then vscode asked me to report the issue.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: /Users/josephcaburnay/Projects/kwartrack/node_modules/next/index.d.ts linked to nonexistent file /Users/josephcaburnay/Projects/kwartrack/node_modules/.pnpm/next@14.0.1_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0_sass@1.68.0/node_modules/next/index.d.ts
    at realPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42498:9)
    at getOriginalAndResolvedFileName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:41429:28)
    at resolveTypeReferenceDirective (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:41514:45)
    at Object.resolve (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120015:42)
    at resolveNamesWithLocalCache (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:125717:29)
    at Object.resolveTypeReferenceDirectiveReferences (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:125782:12)
    at ConfiguredProject2.resolveTypeReferenceDirectiveReferences (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176292:33)
    at resolveTypeReferenceDirectiveNamesWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120761:20)
    at resolveTypeReferenceDirectiveNamesReusingOldState (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120931:14)
    at processTypeReferenceDirectives (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122253:25)
    at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122147:9)
    at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122017:20)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121966:22
    at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121935:26)
    at processSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121964:5)
    at processRootFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121761:5)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120508:41
    at forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2352:22)
    at createProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120508:5)
    at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143907:15)
    at Object.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143981:5)
    at ConfiguredProject2.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176966:41)
    at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176817:32)
    at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178072:24)
    at updateProjectIfDirty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178525:35)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:180785:11)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:181062:64
    at flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2600:17)
    at _ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:181062:24)
    at updateOpen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182242:29)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184838:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184830:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184838:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184880:51)
    at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:186461:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code - Insiders 1.84.0-insider (Universal) (60182c7e1a666961ded4d0319c154f52d85daf30, 2023-10-30T23:42:50.732Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id d3a8a764-dc09-4b31-affd-7ab81061f640|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
rtf|ale|2.7.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.4.1
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
copilot|Git|1.132.0
copilot-chat|Git|0.8.0
odoo-dev-plugin|Jos|0.1.18
vscode-cython|ktn|0.3.10
edgedb|mag|0.1.6
reflow-markdown|mar|2.1.0
rainbow-csv|mec|3.8.0
black-formatter|ms-|2023.4.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.50
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
markdown-checkbox|PKi|1.9.0
excalidraw-editor|pom|3.6.1
vscode-thunder-client|ran|2.14.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
trailing-spaces|sha|0.4.1
pretty-ts-errors|yoa|0.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
6c1a3589:30846784
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
vscrp:30624060
a9j8j154:30646983
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30864172
accentitlementst:30870582

```

</details>

**Comment by mjbvz** [comment]
Based on the stack, this is caused by yarn's TS server plugin. Please file the issue against them
