### ISSUE TITLE
TypeError: A dynamic import callback was not specified.

### ISSUE THREAD

**Issue by qarlosalberto** [microsoft/vscode#197329]
I'm developing an extension using Pyodide (https://github.com/pyodide/pyodide). This is a Python distribution for the browser and Node.js based on WebAssembly.

When I run my extension in debug mode it works fine, there is no problem.

But when I pack it with `vsce  package` it fails:

```
TypeError: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:399:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at initNodeModules (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/pyodide/pyodide.js:9:802)
    at loadPyodide (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/pyodide/pyodide.js:9:9398)
    at Pyodide.load (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/teroshdl2/out/process/pyodide.js:54:34)
    at Pyodide.write_file_list (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/teroshdl2/out/process/pyodide.js:38:38)
```

Any idea what the problem could be? Here the issue in Pyodide repository: https://github.com/pyodide/pyodide/issues/4267

**Comment by roblourens** [comment]
Sorry, I think you will be on your own to debug it. You can check

- Compiling in a different mode for dev vs prod?
- Missing a file that should be included in the vsix package?

**Comment by qarlosalberto** [comment]
I see that VSCode is failing in all the dynamic imports. For example: https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L41
