### ISSUE TITLE
Git not working in visual studio code.

### ISSUE THREAD

**Issue by queston02** [Microsoft/vscode#19748]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Install Git
2. Install Visual Studio Code.
3. Open any folder which is a git repository.
4. Get following message "There was an issue running a git operation. Please review the output or use a console to check the state of your repository."
5. Output does not display anything.

Below is the error i can see in developer tools console.

messageService.ts:126There was an issue running a git operation. Please review the output or use a console to check the state of your repository.: Error: There was an issue running a git operation. Please review the output or use a console to check the state of your repository.
    at Object.g [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:24713)
    at t.wrapGitError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:108:28143)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:108:27830
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16418)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17739)
    at _chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17098)
    at n (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:14921)
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16418)e.doShow @ messageService.ts:126

**Comment by joaomoreno** [comment]
If you open the Git Output, like the error suggests, do you see something there?

If you open the Terminal in Code, can you run `git --version`?

Where is git installed?

**Comment by queston02** [comment]
Question :- If you open the Git Output, like the error suggests, do you see something there?
Answer :- Nope. Its completely empty.

Question :- If you open the Terminal in Code, can you run git --version?
Answer :- Yes. It get `git version 2.11.0.windows.1`

Question :- Where is git installed?
Answer :- "C:\\Program Files\\Git\bin\\git.exe"

**Comment by joaomoreno** [comment]
Just to confirm on the Git Output...

![image](https://cloud.githubusercontent.com/assets/22350/22641787/655aeb18-ec58-11e6-9896-00e214044ea3.png)

After the error appears, can you show me a screenshot of what comes after clicking here?

**Comment by queston02** [comment]
Hi,

Question :- Did it use to work on a previous version of Code?
Answer :- Nope.

Please find the screenshot attached.

![image](https://cloud.githubusercontent.com/assets/20847841/22664234/883e5078-ec64-11e6-8c1d-58b5e8e6f75f.png)

Thanks

**Comment by joaomoreno** [comment]
OK, the output doesn't appear to be _completely empty_.

If you modify a file, does it show up in the git view?

Can you commit?

Can you take a screenshot of the error when it happens?

**Comment by queston02** [comment]
Most of the time output appear to be completely empty.
Sometimes it have the message "git config --get commit.template"

Question :- If you modify a file, does it show up in the git view?
Answer :- Nope. I have attached the screenshot containing empty git view.

Question :- Can you commit?
Answer :- Nope. I see the error as soon as i do changes and save(Ctrl + S) the file.

![image](https://cloud.githubusercontent.com/assets/20847841/22767439/13f428dc-ee30-11e6-9ae5-c1ec93d5477e.png)

**Comment by joaomoreno** [comment]
Does it work if you set the `git.path` setting to `C:\Program Files\Git\bin\git.exe`?

**Comment by queston02** [comment]
Question :- Does it work if you set the git.path setting to C:\Program Files\Git\bin\git.exe?
Answer :- Nope. Please refer to the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/20847841/22796477/4dba4d06-eeaf-11e6-99b9-18ebe1db2509.png)

**Comment by joaomoreno** [comment]
This is strange, I'm running out of ideas.

**Comment by queston02** [comment]
Does the logs from Developer tool console helps?

messageService.ts:126There was an issue running a git operation. Please review the output or use a console to check the state of your repository.: Error: There was an issue running a git operation. Please review the output or use a console to check the state of your repository.
    at Object.g [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:24713)
    at t.wrapGitError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:108:27935)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:108:27622
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16418)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17739)
    at _chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17098)
    at n (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:14921)
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16418)e.doShow @ messageService.ts:126

**Comment by joaomoreno** [comment]
@queston02 Can you try out our [Insiders release](http://code.visualstudio.com/insiders)?

**Comment by queston02** [comment]
Just tried Insiders Release. Git is not working even in it.
Source control explorer is empty even though i have opened a Git based repository.
Developer tools is showing an error in console. Below is the text from it.

[Extension Host] Error: watch .git ENOENT
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at Object.watch (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\git\out\watch.js:11:24)
    at Model.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\git\out\model.js:508:76)
    at next (<anonymous>)
    at fulfilled (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\git\out\model.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)d.logExtensionHostMessage @ extensionHost.ts:282

![image](https://cloud.githubusercontent.com/assets/20847841/23825764/caeba0f2-0644-11e7-8d58-9c560d465d42.png)

**Comment by ChrisW123** [comment]
I'm also getting errors trying to use Git from VS Cdoe.  Is there any solution?  See image below of my developers tools Console.  It also happens with WebStorm.  However Git works fine with VS 2015 Community.  

![image](https://cloud.githubusercontent.com/assets/12971128/24053522/85ac6b00-0af6-11e7-9608-ab5e5f17a69a.png)

**Comment by joaomoreno** [comment]
@queston02 If you open a Command Prompt and `cd` to that workspace, what do you get when running `git status`?

**Comment by ChrisW123** [comment]
Thanks for replying.  I get this:

C:\NextGen\PSA-Projects\aus-tracking>git status
On branch MyBranch
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/aus-tracking/aus-tracking.html

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by ChrisW123** [comment]
Anyway, I figured it out.  Here's how I fixed it:

1) Uninstalled Git
2) Uninstalled GitHub gui app
3) Checked Windows credentials for GitHub password (probably not needed)
4) Reboot
5) Start VSCode (not sure if step is needed)
6) In Code, use Git icon. Still getting errors.  (not sure if step is needed)
7) Exit VSCode
8) Install Git from here: https://git-scm.com/download/win filename: Git-2.12.1-64-bit.exe
9) Restart VSCode to a local project folder. Git icon is working correctly now.

Not sure why this fixed it however.... I have uninstalled and reinstalled VSCode and Git several times before which didn't work.  Either step 2 and/or step 8 are probably the "key" steps.

**Comment by joaomoreno** [comment]
@queston02 Does this work for you? What does `git status` return for you?

**Comment by ChrisW123** [comment]
Did you not see my last two posts?  Yes it works now.  Thanks.

**Comment by joaomoreno** [comment]
I'm talking to @queston02

**Comment by queston02** [comment]
@joaomoreno yep `git status` works for me.
Here is what i get

```
C:\GitRepository\epps-cloudformation-amerihome>git status
On branch EPPSTR-252
Your branch is up-to-date with 'origin/EPPSTR-252'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   epps-rateparsing-create-stack.template
        modified:   epps-rateparsing-update-stack.template

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by queston02** [comment]
@joaomoreno i tried the steps mentioned by @ChrisW123 and it worked. yaaaaaaay!
Git is now working in VS Code for me.

Thank you @joaomoreno and @ChrisW123

**Comment by v-mane** [comment]
For me uninstall and install Git for windows did not worked, but seems to be an issue with my NodeJS installation. **I installed NodeJS LTS v6.10.1 and it worked!!!!!**
You can download NodeJS LTS from https://nodejs.org/en/download

**Comment by Windner** [comment]
Same issue on Mac, and resolved after install NodeJS LTS v6.10.1

**Comment by lordvlad** [comment]
Experiencing the same issue with node v8.3.0. I Could have sworn it worked with v8.1.x as well. Desn't VSCode bring its own node environment?

**Comment by lordvlad** [comment]
Experiencing a similar issue, but I just noticed that when I navigate to a different tab, then come back to the diff tab, it shows properly:
![vscode-git-issue](https://user-images.githubusercontent.com/1217769/29250412-5b01d194-8042-11e7-90e6-a03e0d78af41.gif)

**Comment by komali2** [comment]
Having this issue here, Node 6.11.4, I suspect it has something to do with using Bash on Ubuntu on Windows (Windows Subsystem for Linux, WSL), and using git installed in WSL (rather than git Windows version). 

God only knows what happen if I mix and match WSL git with Windows git. Anybody else in a similar boat figure this out?
