### ISSUE TITLE
automatic dotnet install script crashed, after I clicked Create .NET Project button

### ISSUE THREAD

**Issue by SignalMQ** [microsoft/vscode#197491]
Type: <b>Bug</b>

s-dotnettools.csharp requested to download the .NET Runtime.
ms-dotnettools.csharp requested to download the .NET Runtime.
ms-dotnettools.csharp tried to install .NET 7.0.13~x64 but that install had already been requested. No downloads or changes were made.
Downloading .NET version(s) 7.0.13~x64 ...... Error!
Please ensure that you are online: Request to https://dot.net/v1/dotnet-install.sh Failed: n[r].split is not a function.
If you are on a corporate proxy with a result of 400, you may need to manually set the proxy in our extension settings. Please see https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md for more details.
If your proxy requires credentials and the result is 407: we cannot currently handle your request, and you should configure dotnet manually following the above link.

Still downloading .NET version(s) 7.0.13~x64 ... Error!
Please ensure that you are online: Request to https://dot.net/v1/dotnet-install.sh Failed: n[r].split is not a function.
If you are on a corporate proxy with a result of 400, you may need to manually set the proxy in our extension settings. Please see https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md for more details.
If your proxy requires credentials and the result is 407: we cannot currently handle your request, and you should configure dotnet manually following the above link.

Still downloading .NET version(s) 7.0.13~x64 ... Error!
Failed to download .NET 7.0.13~x64:
Command failed: "/home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/sobirjon/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~x64" -Version 7.0.13 -Verbose -Runtime dotnet -Architecture x64
/bin/sh: 1: /home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0/dist/install scripts/dotnet-install.sh: Permission denied

 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/sobirjon/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~x64" -Version 7.0.13 -Verbose -Runtime dotnet -Architecture x64
/bin/sh: 1: /home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0/dist/install scripts/dotnet-install.sh: Permission denied

 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/sobirjon/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~x64" -Version 7.0.13 -Verbose -Runtime dotnet -Architecture x64
/bin/sh: 1: /home/sobirjon/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0/dist/install scripts/dotnet-install.sh: Permission denied

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:28:21.782Z)
OS version: Linux x64 6.2.0-36-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics (12 x 2271)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 1|
|Memory (System)|7.14GB (2.62GB free)|
|Process Argv|--unity-launch --crash-reporter-id 739bc478-8503-4bb3-b504-bf30f45da8eb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-avalonia|Ava|0.0.22
csdevkit|ms-|1.0.14
csharp|ms-|2.9.20
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
vscrp:30673768
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016:30880769
dsvsc018:30880894

```

</details>

**Comment by SignalMQ** [comment]
And I paste C# logs:
`Installing Razor Telemetry Version = 7.0.0-preview.23528.1...
Platform: linux, x86_64, name=ubuntu, version=22.04

Downloading package 'Razor Language Server Telemetry (Linux / x64)' (9091 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'Razor Language Server Telemetry (Linux / x64)'

Finished

Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
[Error - 23:53:43] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Could not resolve the dotnet path!
	at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/sobirjon/.vscode/extensions/ms-dotnettools.csharp-2.9.20-linux-x64/dist/extension.js:2:1430284)
	at Generator.next (<anonymous>)
	at s (/home/sobirjon/.vscode/extensions/ms-dotnettools.csharp-2.9.20-linux-x64/dist/extension.js:2:1428699)
`
