### ISSUE TITLE
vscode API - terminal environmentVariableCollection should respect deleting entries

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197720]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=242254&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=efbaf268-cf98-50c2-bb3c-7950770fd6bc&l=628

```
1 failing
  1) vscode API - terminal
       Terminal
         environmentVariableCollection
           should respect deleting entries:
     Error: Timeout: ~b2~ should be printed after 20 seconds.
Did not pass accept function
      at poll (/Users/runner/work/1/s/extensions/vscode-api-tests/src/utils.ts:176:10)
      at Context.<anonymous> (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts:882:5)
```

**Comment by Postpor** [comment]
Hello hi guys..like

**Comment by Tyriar** [comment]
I don't think this has happened any time recently
