### ISSUE TITLE
Inline diff-view sometimes hides deleted or changed lines

### ISSUE THREAD

**Issue by bradlitterell** [microsoft/vscode#198471]
Type: <b>Bug</b>

1. Select a file under source control (only tested with git).
2. modify the file.
3. select Source Control Panel
4. Observe file is listed under "Changes"
5. select file.
6. In the diff-viewer, select the upper "three-dots" button and ensure "inline view" is unchecked.
7. observe one side of the screen has the old version in red shading
8. and the other has the change in green
9. check "inline-view"
10. observe the difference is now shown as a single editor with both red and green areas.

Expected result:
always see both old and new values

Actual result:
Sometimes the old value is only highlighed in the mini map, and not shown in the actual text.  
This is intermittent and reloading the VS Code window seems to resolve this problem, but have not found a way to reset the view except by reloading VSC.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.25982
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (6.33GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/bradlit/stpm --remote=wsl+Ubuntu-22.04 --crash-reporter-id 599da817-f9ce-4935-b18c-03818c17620d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|Memory (System)|15.54GB (12.44GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-table-prettify|dar|3.6.0
vscode-markdownlint|Dav|0.52.0
filter-line|eve|2.0.1
git-graph|mhu|1.30.0
remote-containers|ms-|0.321.0
remote-wsl|ms-|0.81.8
hexeditor|ms-|1.9.12
powershell|ms-|2023.8.0
rewrap|stk|1.16.3
gitblame|wad|10.5.1
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by jon-nfc** [comment]
same issue. Debian 12


[Screencast from 2023-11-27 00-49-12.webm](https://github.com/microsoft/vscode/assets/8982109/51b790c8-4809-4010-b2a4-dd4e0b4b587a)

**Comment by THOUSAND-SKY** [comment]
Still seeing this happen on

```
1.85.0
af28b32d7e553898b2a91af498b1fb666fdebe0c
x64
```

I can see it on the minimap, gutter shows `-` icons, but the removed lines don't show.

**Comment by hediet** [comment]
@[THOUSAND-SKY](https://github.com/THOUSAND-SKY) can you share the dev tools log?

**Comment by THOUSAND-SKY** [comment]
You're talking about logs in the electron developer tools console, yes?

I can, but do I need to do something to trigger logs there? Toggling between inline/split doesn't produce any output. Going back & forth between the diff/some other file does produce gitlens errors.

I didn't try if this happens w/ extensions disabled. I think reloading the window (to disable extensions) may magically fix it though.

![image](https://github.com/microsoft/vscode/assets/104664691/9ff05fb2-710d-4593-b3ba-e0c615e0924d)

Any other logs I can give?

**Comment by hediet** [comment]
Are there other errors before that?

**Comment by THOUSAND-SKY** [comment]
This one was there, it was very far up the console though.

![Screenshot from 2023-12-12 16-22-13](https://github.com/microsoft/vscode/assets/104664691/cf062132-c27f-4089-94c3-1c4e2ee27660)

I already closed vscode since, so can't check if there was more than that.

**Comment by THOUSAND-SKY** [comment]
Damn, sorry, I only took a screenshot of it yesterday but didn't even post because I didn't think it was relevant since it was so far up in the console. So unfortunately cannot copy the stack trace, the commit id is already on my earlier post but here it is again

```
$ code --version
1.85.0
af28b32d7e553898b2a91af498b1fb666fdebe0c
x64
```

**Comment by hediet** [comment]
Without the actual text, I cannot do that much with the stack trace unfortunately :/
I need the full stack trace + vscode commit id to deminify it.

**Comment by THOUSAND-SKY** [comment]
Had it happen again.

```
Uncaught Error: Illegal value for lineNumber
    at q.getLineContent (textModel.ts:808:10) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/editor/common/model/textModel.ts
    at lineAlignment.ts:165:85 https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/editor/browser/widget/diffEditor/lineAlignment.ts
    at h._computeFn (derived.ts:85:11) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/derived.ts
    at h.w (derived.ts:242:22) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/derived.ts
    at h.get (derived.ts:219:10) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/derived.ts
    at h.reportChanges (base.ts:175:8) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/base.ts
    at h.get (derived.ts:204:9) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/derived.ts
    at h.reportChanges (base.ts:175:8) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/base.ts
    at g.endUpdate (autorun.ts:207:9) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/autorun.ts
    at h.endUpdate (derived.ts:299:7) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/derived.ts
    at h.endUpdate (derived.ts:299:7) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/derived.ts
    at h.endUpdate (derived.ts:299:7) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/derived.ts
    at i.finish (base.ts:329:13) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/base.ts
    at m.set (base.ts:495:9) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/observableInternal/base.ts
    at W.a (lineAlignment.ts:71:10) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/editor/browser/widget/diffEditor/lineAlignment.ts
    at W.h (async.ts:979:8) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/async.ts
    at W.g (async.ts:974:9) https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/async.ts
```

I couldn't copy it with the links but manually added them

<details><summary>Here is is again, without the links (from exported log file)</summary>
<p>


```
textModel.ts:808 Uncaught Error: Illegal value for lineNumber
    at q.getLineContent (textModel.ts:808:10)
    at lineAlignment.ts:165:85
    at h._computeFn (derived.ts:85:11)
    at h.w (derived.ts:242:22)
    at h.get (derived.ts:219:10)
    at h.reportChanges (base.ts:175:8)
    at h.get (derived.ts:204:9)
    at h.reportChanges (base.ts:175:8)
    at g.endUpdate (autorun.ts:207:9)
    at h.endUpdate (derived.ts:299:7)
    at h.endUpdate (derived.ts:299:7)
    at h.endUpdate (derived.ts:299:7)
    at i.finish (base.ts:329:13)
    at m.set (base.ts:495:9)
    at W.a (lineAlignment.ts:71:10)
    at W.h (async.ts:979:8)
    at W.g (async.ts:974:9)
```

</p>
</details> 

![image](https://github.com/microsoft/vscode/assets/104664691/3465ddfd-7fbb-4b2e-b0f7-9dbce06f7a50)

There was also a lot of this warning log:

```
event.ts:1038 [186] REFUSES to accept new listeners because it exceeded its threshold by far
q @ event.ts:1038 https://ticino.blob.core.windows.net/sourcemaps/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/core/vs/workbench/out-vscode/vs/workbench/file:/mnt/vss/_work/1/s/src/vs/base/common/event.ts
```

```
$ code --version
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64
```

**Comment by hediet** [comment]
Thanks! I think I understand the root cause of this bug now.
Basically, when the text model changes and the diff updates (but didn't update yet), the current diff data is stale and might point to out-of-bound lines (e.g. when lines in original got deleted).
This becomes a problem when some external event causes UI recomputation (e.g. when resizing the editor pane).

I managed to reproduce this by artificially slowing down the diff algorithm.

**Comment by benibenj** [comment]
ERR startLineNumber 1880 cannot be after endLineNumberExclusive 1820: Error: startLineNumber 1880 cannot be after endLineNumberExclusive 1820
    at new I (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:96:5655)
    at S.inverse (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:99:2506)
    at P (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:693:46854)
    at vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:693:49306
    at w (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:11236)
    at vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:693:49301
