### ISSUE TITLE
IntelliSense stoped work

### ISSUE THREAD

**Issue by lvendrame** [microsoft/vscode#198945]
- Version: 1.84.2 (user setup)
- Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
- Date: 2023-11-09T10:51:52.184Z
- Electron: 25.9.2
- ElectronBuildId: 24603566
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Windows_NT x64 10.0.19045

# Steps to Reproduce:

1. Start typing a component in React or press "Ctrl + Space"
2. The IntelliSense will only show snippets and previously used words.

PS.: I also tried with all the extensions disabled and with a downgraded version.

# Looking at the "Extension Host (Remote)", it shows the following error:

```shell
2023-11-23 14:58:51.693 [error] [vscode.typescript-language-features] provider FAILED
2023-11-23 14:58:51.693 [error] Error: <semantic> TypeScript Server Error (5.2.2)
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at isExportDefaultSymbol (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:19549:31)
    at getLocalSymbolForExportDefault (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:19541:8)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133555:23)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
    at getDefaultExportInfoWorker (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/node_modules/typescript/lib/tsserver.js:133564:14)
	at n.create (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/typescript-language-features/dist/extension.js:2:869102)
	at g.w (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/typescript-language-features/dist/extension.js:2:864426)
	at g.u (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/typescript-language-features/dist/extension.js:2:863509)
	at ChildProcess.<anonymous> (/home/lvendrame/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/extensions/typescript-language-features/dist/extension.js:2:863141)
	at ChildProcess.emit (node:events:513:28)
	at emit (node:internal/child_process:937:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by lvendrame** [comment]
It came back to life after I:
* deleted node_module folder
* fixed all versions on the package.json file
* reinstall all packages.

The funny part is, that it was affecting IntelliSense on other projects.
