### ISSUE TITLE
Development environment cannot be installed successfully

### ISSUE THREAD

**Issue by peterdaiweb** [microsoft/vscode#199135]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: macOS Sonoma 14.1.1  MacBook Pro Intel
- node: v18.18.2
- yarn: 1.22.21
- Python 3.7.3 (default, Apr 24 2020, 18:51:23)

Steps to Reproduce:

1. checkout vscode git repo
2. switch to branch 1.75.1
3. yarn

I have tried your propose in [How-to-Contribute](https://github.com/microsoft/vscode/wiki/How-to-Contribute) like delete ~/Library/Caches/node-gyp/, run yarn cache clean, install node-gyp -g. But they are still not worked.
Now i have to use my windows to do this and change vscode source code to build.

```
error /Users/dai/workspace/icbc/vscode/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/dai/workspace/icbc/vscode/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@18.18.2 | darwin | x64
gyp info find Python using Python version 3.7.3 found at "/Library/Developer/CommandLineTools/usr/bin/python3"

gyp WARN EACCES current user ("dai") does not have permission to access the dev dir "/Users/dai/Library/Caches/node-gyp/19.1.9"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/folders/ht/7slnr46n42v1968l1s_73l5h0000gn/T/.node-gyp"

gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args '/Users/dai/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/dai/workspace/icbc/vscode/node_modules/native-keymap/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/dai/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/var/folders/ht/7slnr46n42v1968l1s_73l5h0000gn/T/.node-gyp/19.1.9/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/var/folders/ht/7slnr46n42v1968l1s_73l5h0000gn/T/.node-gyp/19.1.9',
gyp info spawn args '-Dnode_gyp_dir=/Users/dai/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/var/folders/ht/7slnr46n42v1968l1s_73l5h0000gn/T/.node-gyp/19.1.9/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/dai/workspace/icbc/vscode/node_modules/native-keymap',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.



gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/keymapping/src/string_conversion.o
  CXX(target) Release/obj.target/keymapping/src/keymapping.o
  CXX(target) Release/obj.target/keymapping/src/keyboard_mac.o
In file included from ../src/keyboard_mac.mm:6:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:89:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:59:10: fatal error: 'SharedFileList/SharedFileList.h' file not found
#include <SharedFileList/SharedFileList.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/keymapping/src/keyboard_mac.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/Users/dai/.config/yarn/global/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Darwin 23.1.0
gyp ERR! command "/Users/dai/.nvm/versions/node/v18.18.2/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/dai/workspace/icbc/vscode/node_modules/native-keymap
```

**Comment by roblourens** [comment]
Seems like something is wrong with your npm or node-gyp setup. You will probably have to troubleshoot this yourself, sorry

> `gyp WARN EACCES current user ("dai") does not have permission to access the dev dir "/Users/dai/Library/Caches/node-gyp/19.1.9"`

**Comment by roblourens** [comment]
Maybe check that xcode and the command line tools are properly installed. And I'm wondering why you are trying to build the very old 1.75 branch

**Comment by tutuxxx** [comment]
Try update Xcode in System Settings - Software Update

**Comment by peterdaiweb** [comment]
> Try update Xcode in System Settings - Software Update

System Settings - Software Update is already the latest version
![Uploading WX20231204-155858@2x.png…]()

**Comment by peterdaiweb** [comment]
> Maybe check that xcode and the command line tools are properly installed. And I'm wondering why you are trying to build the very old 1.75 branch

Thanks for your answer. 

First, I get that my Mac system has been updated to the Sonoma version a few days ago, but XCode is not updated to 15.x. I update it and the question is solved.

Second, I am using this vscode version（1.75） because the internal application market of the company requires it. The same error happens when I use the main branch.

Finally, here is another error after I update XCode to 15.0.1:
```
error /Users/dai/workspace/icbc/vscode/node_modules/@vscode/ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: /Users/dai/workspace/icbc/vscode/node_modules/@vscode/ripgrep
Output:
Using cached download: /var/folders/ht/7slnr46n42v1968l1s_73l5h0000gn/T/vscode-ripgrep-cache-1.15.6/ripgrep-v13.0.0-10-x86_64-apple-darwin.tar.gz
Unzipping to /Users/dai/workspace/icbc/vscode/node_modules/@vscode/ripgrep/bin
x rg: truncated gzip input
tar: Error exit delayed from previous errors.
tar xvf exited with 1
Deleting invalid download
Downloading ripgrep failed: Error: tar xvf exited with 1
    at ChildProcess.<anonymous> (/Users/dai/workspace/icbc/vscode/node_modules/@vscode/ripgrep/lib/download.js:275:24)
```
