### ISSUE TITLE
Terminal stickyScroll

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#199268]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=246565&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=2a2f2929-c461-5864-dab6-43c08a82ca8a&l=136

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal stickyScroll
           "before each" hook for "should support multi-line prompt":
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:295:11)
      at Code.waitForTerminalBuffer (D:\a\_work\1\s\test\automation\src\code.ts:246:3)
      at Terminal.waitForTerminalText (D:\a\_work\1\s\test\automation\src\terminal.ts:292:4)
      at Terminal.createEmptyTerminal (D:\a\_work\1\s\test\automation\src\terminal.ts:156:3)
      at Context.<anonymous> (src\areas\terminal\terminal-stickyScroll.test.ts:55:4)
```

**Comment by Tyriar** [comment]
Stale, haven't seen recently
