### ISSUE TITLE
Cannot connect to remote with Linux client bits

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#199382]
Testing #199045

0. Setup an Ubuntu 22.04 VM
1. Install the x86_64 .deb from #199045
2. On another machine, use the Remote - Tunnels extension to allow other machines to connect to it
3. On the Ubuntu VM, try to connect to the machine from step 2.

```log
   ERR [Extension Host] Tunnel connection closed Error: StatusError(StatusError { url: "https://update.code.visualstudio.com/commit:21af479…/server-win32-x64/insider", status_code: 404, body: "Not Found" })
    at Object.resolve (/home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/proxyServer.js:2:544133)
    at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/proxyServer.js:2:542838
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
console.ts:137 [Extension Host] Tunnel connection closed Error: StatusError(StatusError { url: "https://update.code.visualstudio.com/commit:21af479…/server-win32-x64/insider", status_code: 404, body: "Not Found" })
    at Object.resolve (/home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/proxyServer.js:2:544133)
    at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/proxyServer.js:2:542838
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (at console.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:168637))
log.ts:441   ERR [Extension Host] Tunnel connection closed Error: 
	at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:888039
	at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:871837
	at i.fire (/home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:939436)
	at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:870330
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
console.ts:137 [Extension Host] Tunnel connection closed Error: 
	at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:888039
	at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:871837
	at i.fire (/home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:939436)
	at /home/alex/.vscode-insiders/extensions/ms-vscode.remote-server-1.5.0/dist/node/extension.js:2:870330
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (at console.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:168637))
browserSocketFactory.ts:80 WebSocket connection to 'ws://127.0.0.1:37759/insider-21af479f859a2b11e3687a84d89db06db755d83b?reconnectionToken=2f1f0923-780c-411f-879a-66e70c09ab0c&reconnection=false&skipWebSocketFrames=false' failed: 
log.ts:421  INFO Creating a socket (renderer-Management-2f1f0923-780c-411f-879a-66e70c09ab0c) returned an error after 1833 ms.
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:166:20)
log.ts:441   ERR [remote-connection][Management   ][2f1f0…][initial][WebSocket(127.0.0.1:37759)] socketFactory.connect() failed or timed out. Error:
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:166:20)
log.ts:441   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:166:20)
log.ts:421  INFO Invoking resolveAuthority(tunnel)...
log.ts:421  INFO [LocalProcess0][resolveAuthority(tunnel,2)][0ms] obtaining proxy...
log.ts:421  INFO [LocalProcess0][resolveAuthority(tunnel,2)][0ms] invoking...
log.ts:441   ERR [Extension Host] Tunnel connection closed undefined
console.ts:137 [Extension Host] Tunnel connection closed undefined (at console.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:168637))
browserSocketFactory.ts:80 WebSocket connection to 'ws://127.0.0.1:37759/insider-21af479f859a2b11e3687a84d89db06db755d83b?reconnectionToken=f4f51239-9fe0-461f-b52b-a778fbb95234&reconnection=false&skipWebSocketFrames=false' failed: 
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-f4f51239-9fe0-461f-b52b-a778fbb95234) returned an error after 1836 ms.
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:166:20)
log.ts:441   ERR [remote-connection][ExtensionHost][f4f51…][initial][WebSocket(127.0.0.1:37759)] socketFactory.connect() failed or timed out. Error:
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:166:20)
log.ts:441   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (browserSocketFactory.ts:166:20)
log.ts:421  INFO [LocalProcess0][resolveAuthority(tunnel,2)][1000ms] waiting...
log.ts:421  INFO [LocalProcess0][resolveAuthority(tunnel,2)][1833ms] returned WebSocket(127.0.0.1:44101)
log.ts:421  INFO resolveAuthority(tunnel) returned 'WebSocket(127.0.0.1:44101)' after 1835 ms
log.ts:421  INFO Creating a socket (renderer-Management-079ad8bb-4a20-4a25-967f-648b30cfd73d)...
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-3a344717-31f3-4347-bcc2-71688b3bcfa1)...
```

**Comment by deepak1556** [comment]
I haven't produced win32 server bits as part of commit, 404 error is from that. Would it be easier for you to use a docker container to test ? Otherwise I can trigger a new build with all bits created.

**Comment by alexr00** [comment]
I don't think I can use docker as I'm running Ubuntu in a VM on Windows.

**Comment by deepak1556** [comment]
Triggered new builds with all bits https://monacotools.visualstudio.com/Monaco/_build/results?buildId=246635&view=results. I will update here once the bits are available.

**Comment by deepak1556** [comment]
@alexr00 new build is available at [link](https://builds.code.visualstudio.com/builds/insider?commit=b047b7d0f8403dda8140a2a006f6621c66548825&dev=true) for testing.

**Comment by alexr00** [comment]
Tested. It works as expected!
