### ISSUE TITLE
Codespaces show "document already exists!" error

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#199650]
* open codespace
* open remote explorer
* select the gear icons
* :bug: see the following error on the console

```
 ERR document 'file:///workspaces/vscode-tree-sitter-query/.devcontainer/devcontainer.json already exists!': Error: document 'file:///workspaces/vscode-tree-sitter-query/.devcontainer/devcontainer.json already exists!'
    at i.acceptDocumentsAndEditorsDelta (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:143:11401)
    at i.$acceptDocumentsAndEditorsDelta (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:143:10970)
    at u.S (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:150:10829)
    at u.Q (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:150:10595)
    at u.M (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:150:9685)
    at u.L (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:150:8764)
    at f.value (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:150:7567)
    at n.y (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at o.fire (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
    at f.value (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:171:7903)
    at n.y (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at o.fire (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
    at d.z (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:103:17104)
    at f.value (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:103:15556)
    at n.y (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at f.acceptChunk (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:103:11813)
    at /vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:103:11100
    at Socket.E (/vscode/bin/linux-x64/c6b48c364dde70c12bf977f1da50acda0fd801e3-insider/out/vs/workbench/api/node/extensionHostProcess.js:168:12957)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by jrieken** [comment]
<img width="1463" alt="Screenshot 2023-11-30 at 11 41 30" src="https://github.com/microsoft/vscode/assets/1794099/3239e6c2-cfc0-4041-aa2a-9f44f556aeab">

Debugging shows that first a call to `$tryOpenDocument` _without_ an authority is received, later a call with authority happens (same path, scheme otherwise). Due to uri transformation both vscode-remote-uris will become the same file-uri which leads to the error above. 

So, there most be something on the calling side that makes us trip over this and there might some check missing, e.g because a URI isn't "instanceof-true" or because a remote-uri without authority is passed along. We should guard ourselves from both cases.

**Comment by osortega** [comment]
I created a minimal repro here:
https://github.com/osortega/vscode-extension

You can execute the `Hello World` command and the first time it will open the `devcontainer.json` file correctly, but after the second time executing the command I get this error in the console:


![Image](https://github.com/microsoft/vscode/assets/48293249/7ebded1b-8fd8-4860-a86e-4f95ca1846d2)

**Comment by bpasero** [comment]
@osortega what you are doing seems like a violation of the `vscode-remote` scheme which requires a `authority`. Jo and me think that we should even throw if you attempt to do so.

Why do you create a `vscode-remote` URI and not a `URI` that is resolved against the workspace root?

**Comment by bpasero** [comment]
Cool!

**Comment by bpasero** [comment]
Opened https://github.com/microsoft/vscode/issues/199844 to track throwing an error when this happens in the future.
