### ISSUE TITLE
Error: Model is disposed!

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#199665]
I have found the error below in my logs, very confident that this is from 

https://github.com/microsoft/vscode/blob/82af26f7068754312f5454175c45f8648a45eac1/src/vs/editor/browser/widget/diffEditor/workerBasedDocumentDiffProvider.ts#L44

(minified source reference for reference)

<img width="771" alt="Screenshot 2023-11-30 at 14 53 18" src="https://github.com/microsoft/vscode/assets/1794099/71a44fa9-60c2-4851-84b4-5b0d77b75e2f">

```
ERR Model is disposed!: Error: Model is disposed!
    at q.ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:728:263)
    at q.getLineCount (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:730:4302)
    at p.computeDiff (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:681:41595)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:681:47044
    at g._runFn (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:14193)
    at g.k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:15081)
    at g.endUpdate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:15420)
    at i.finish (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:11735)
    at p (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:11170)
    at o.trigger (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:21685)
    at W.a (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:681:44567)
    at W.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:149:19415)
    at W.g (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:149:19399)
```

**Comment by hediet** [comment]
Thanks for reporting!
The duplicates are not really duplicates btw., they just happen to throw the same error.
