### ISSUE TITLE
Error: Illegal value for lineNumber

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#199938]
I was switching between files, opened an empty file and got the error below

```
ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at TextModel.getLineContent (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:572:23)
    at LightBulbWidget.update (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/contrib/codeAction/browser/lightBulbWidget.js:170:78)
    at CodeActionController.update (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/contrib/codeAction/browser/codeActionController.js:98:42)
```

**Comment by jrieken** [comment]
I believe this happens with empty files
