### ISSUE TITLE
Smoke test failure: settings editor

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#200169]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=248024
Changes: https://github.com/Microsoft/vscode/compare/14f3868...e2e4466

```
 1) VSCode Smoke Tests (Electron)
       Settings editor
         shows a modified indicator on a modified setting:
     Error: Timeout: get elements '.settings-editor .settings-count-widget' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:289:11)
      at Code.waitForElements (D:\a\_work\1\s\test\automation\src\code.ts:226:10)
      at SettingsEditor.searchSettingsUI (D:\a\_work\1\s\test\automation\src\settings.ts:75:3)
      at Context.<anonymous> (src\areas\preferences\preferences.test.ts:45:4)

  2) VSCode Smoke Tests (Electron)
       Settings editor
         turns off editor line numbers and verifies the live change:
     Error: Timeout: get elements '.settings-editor .settings-count-widget' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:289:11)
      at Code.waitForElements (D:\a\_work\1\s\test\automation\src\code.ts:226:10)
      at SettingsEditor.searchSettingsUI (D:\a\_work\1\s\test\automation\src\settings.ts:75:3)
      at Context.<anonymous> (src\areas\preferences\preferences.test.ts:59:4)
```

**Comment by bhavyaus** [comment]
Recent failure in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=249645

```
VSCode Smoke Tests (Web)
       Settings editor
         turns off editor line numbers and verifies the live change:
     Error: Timeout: get elements '.line-numbers' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:202:23)
      at async Code.waitForElements (D:\a\_work\1\s\test\automation\out\code.js:158:16)
      at async Context.<anonymous> (out\areas\preferences\preferences.test.js:48:13)
```
