### ISSUE TITLE
Cell height renders incorrectly

### ISSUE THREAD

**Issue by rvanxer** [microsoft/vscode#200256]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

On many occasions, the cell height of my notebooks changes abruptly, sometimes stretching and at other times shrinking compared to their original height. This problem occurs only during scrolling the document, using either the arrow keys or the mouse. I haven't seen this exact issue arise on the GitHub issues page or other websites like Reddit and StackOverflow.

It is difficult to replicate this issue on demand, but there are a few patterns I've observed:
- This issue mostly occurs after running some code that uses RAM to a moderate degree, but I've observed it at other times too when I run generic simple code like defining functions (that doesn't take much memory).
- I mostly use Jupyter in Code remotely. Perhaps this problem might be because of that.

![Screenshot 2023-10-07 at 4 52 31 PM](https://github.com/microsoft/vscode-jupyter/assets/13570548/62eac52f-8f92-4914-a23b-a1af157061ee)

### VS Code Version

Version: 1.83.0 Commit: e7e037083ff4455cf320e344325dacb480062c3c Date: 2023-10-03T16:13:10.518Z Electron: 25.8.4 ElectronBuildId: 24154031 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 23.0.0

### Jupyter Extension Version

v2023.9.1102792234

### Jupyter logs

```shell
Visual Studio Code (1.83.0, ssh-remote, desktop)
Jupyter Extension Version: 2023.9.1102792234.
Python Extension Version: 2023.18.0.
Platform: linux (x64).
Workspace folder /home/umni2/a/umnilab/users/verma99/mk, Home = /home/bridge/c/verma99
17:14:17.963 [info] User belongs to experiment group 'NewJupyterSession'
17:14:18.332 [info] Start refreshing Kernel Picker (1696713258332)
17:14:18.342 [info] Using Pylance
17:14:19.713 [error] Failed to validate Password info h [FetchError]: request to http://localhost:5000/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:2:1634096)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
17:14:19.733 [error] Error fetching kernels from http://localhost:5000/ (TNET Python mk3.9): FetchError: request to http://localhost:5000/api/kernels?1696713259724 failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:2:1634096)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
17:14:19.735 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache FetchError: request to http://localhost:5000/api/kernels?1696713259724 failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:2:1634096)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
17:14:19.736 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
    at e.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:2:211828)
    at u.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:2:62940)
    at ks.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:2:2305689)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at Um.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:17:166163)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:17:163608
17:14:20.193 [warn] Password for http://localhost:8000/ was invalid.
17:14:20.215 [warn] Password for http://localhost:8000/ was invalid.
17:14:20.220 [warn] Password for http://localhost:8000/ was invalid.
17:14:20.272 [info] Loading webview. View is notset
17:14:20.273 [info] Loading web view...
17:14:20.274 [info] Webview panel created.
17:14:20.555 [info] Web view react rendered
17:14:22.513 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0bbbc881a3d2b362a3543a66f24b921db480122daf8c3959affec01aee9a271ec./home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/python./home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/python.-m#ipykernel_launcher  (Python Path: /home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/bin/python, Conda, mk11, 3.11.5) for '/home/umni2/a/umnilab/users/<username>/mk/spr_4711/code/POIs.ipynb' (disableUI=true)
17:14:22.831 [info] End refreshing Kernel Picker (1696713258332)
17:14:25.503 [info] Process Execution: /home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/bin/python -m pip list
17:14:25.567 [info] Process Execution: /home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
17:14:25.600 [info] Process Execution: /home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"d60222d0-6058-42e8-b965-ee9fed1d6eac" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-116465Qih337mo2EN1.json
    > cwd: /home/umni2/a/umnilab/users/<username>/mk/spr_4711/code
17:14:25.848 [info] ipykernel version & path 6.25.2, /home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/lib/python3.11/site-packages/ipykernel/__init__.py for /home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/bin/python
17:14:26.201 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
17:14:26.328 [warn] StdErr from Kernel Process [IPKernelApp] WARNING | Error in loading extension: sparkmonitor.kernelextension
Check your config files in ~/.ipython/profile_default
Traceback (most recent call last):
  File "/home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/lib/python3.11/site-packages/IPython/core/shellapp.py", line 282, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/lib/python3.11/site-packages/IPython/core/extensions.py", line 76, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/lib/python3.11/site-packages/IPython/core/extensions.py", line 91, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sparkmonitor'
17:14:26.656 [info] Process Execution: /home/umni2/a/umnilab/users/<username>/anaconda3/envs/mk11/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/pythonFiles/printJupyterDataDir.py
17:14:41.701 [info] Handle Execution of Cells 1,2,3,4,6 for /home/umni2/a/umnilab/users/<username>/mk/spr_4711/code/POIs.ipynb
17:14:41.734 [info] Kernel acknowledged execution of cell 1 @ 1696713281733
17:14:41.860 [info] End cell 1 execution @ 1696713281859, started @ 1696713281733, elapsed time = 0.126s
17:14:41.869 [info] Kernel acknowledged execution of cell 2 @ 1696713281869
17:14:44.045 [info] End cell 2 execution @ 1696713284045, started @ 1696713281869, elapsed time = 2.176s
17:14:44.051 [info] Kernel acknowledged execution of cell 3 @ 1696713284050
17:14:44.627 [info] End cell 3 execution @ 1696713284627, started @ 1696713284050, elapsed time = 0.577s
17:14:44.633 [info] Kernel acknowledged execution of cell 4 @ 1696713284632
17:14:46.844 [warn] StdErr from Kernel Process Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
17:14:47.017 [warn] StdErr from Kernel Process 23/10/07 17:14:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17:14:47.058 [warn] StdErr from Kernel Process 23/10/07 17:14:47 WARN SparkConf: Note that spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone/kubernetes and LOCAL_DIRS in YARN).
17:14:48.364 [info] End cell 4 execution @ 1696713288364, started @ 1696713284632, elapsed time = 3.732s
17:14:48.375 [info] Kernel acknowledged execution of cell 6 @ 1696713288375
17:14:48.415 [info] End cell 6 execution @ 1696713288414, started @ 1696713288375, elapsed time = 0.039s
```

### Coding Language and Runtime Version

Python 3.11.5

### Anaconda Version (if applicable)

conda 22.11.1

### Running Jupyter locally or remotely?

Remote

**Comment by kklot** [comment]
This seems to work for me so far...
> @rebornix @2-5 FWIW I've noticed that keeping the `"notebook.showCellStatusBar"` at its default of `"visible"` is a much more stable experience. I've typically had it on `"visibleAfterExecute"` and that causes misrenders frequently.
