### ISSUE TITLE
Can't open a folder

### ISSUE THREAD

**Issue by rose-sun** [microsoft/vscode#200313]
Type: <b>Feature Request</b>

When I select a directoty or drag a directory into VScode, showing this error: The file is not displayed in the text editor because it is a directory. What should I do? Thank you!

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19044

![image](https://github.com/microsoft/vscode/assets/74955202/30c0ece9-9d62-4af9-9657-7b1c847e193a)

**Comment by ruofengOvO** [comment]
I met the same problem, version Code 1.85.0(af28b32) Here are some los:

2023-12-08 16:21:50.521 Electron[10820:75118] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[main 2023-12-08T08:21:50.579Z] [File Watcher (node.js)] Request to start watching: /Users/rohlff/Library/Application Support/Code/User (excludes: <none>, includes: <all>, correlationId: <none>),/Users/rohlff/Library/Application Support/Code/User/settings.json (excludes: <none>, includes: <all>, correlationId: <none>)
[main 2023-12-08T08:21:50.584Z] Sending env to running instance...
[main 2023-12-08T08:21:50.587Z] [File Watcher (node.js)] Started watching: '/Users/rohlff/Library/Application Support/Code/User'
[main 2023-12-08T08:21:50.588Z] [File Watcher (node.js)] Started watching: '/Users/rohlff/Library/Application Support/Code/User/settings.json'
[main 2023-12-08T08:21:50.632Z] Sent env to running instance. Terminating...
[main 2023-12-08T08:21:50.632Z] Lifecycle#kill()
[main 2023-12-08T08:21:50.632Z] Lifecycle#onWillShutdown.fire()

**Comment by wendraw** [comment]
I have same problem

Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:17:50.719Z (1 day ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.85.0 Chrome/114.0.5735.289 Electron/25.9.7 Safari/537.36

2023-12-08 16:31:23.390 [error] Error: The file is not displayed in the text editor because it is a directory.
    at k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:148:781)
    at ee (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:769:59199)
    at M.fc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2148:24758)
    at M.setInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2148:24179)
    at async b.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2146:23046)
    at async b.L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2146:21637)
    at async b.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2146:20603)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2275:23005
    at async o.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2345:46909)

**Comment by rose-sun** [comment]
I did update the version to 1.85.0 today. Is this a problem caused by version update? How to solve it?

**Comment by iou90** [comment]
I fixed it by turning off "Explorer > File Nesting".
