### ISSUE TITLE
Enable to use any Language Pack

### ISSUE THREAD

**Issue by M1CK431** [microsoft/vscode#200332]
Does this issue occur when all extensions are disabled?: Yes (fresh install, so no extension installed at all)

- VS Code Version: 1.85.0
- OS Version: Archlinux (fully updated)

Steps to Reproduce:

1. Fresh install of `code` package from official repository (which is "Code OSS" in fact)
2. Nothing remains from previous installation (I have removed `~/.vscode` and `~/.config/Code\ -\ OSS/` like explained [here](https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall))
3. Start vscode from terminal by typing `code`
4. On the "welcome screen", click on "Mark Done"
5. Hit "Ctrl + Maj + P" and type "Display" and choose "Configure Display Language"
6. Choose "français" in the menu list
7. vscode install the extension then ask for restart => click on "Restart"
8. vscode close, then an "Electron" window open... 🤯 
![image](https://github.com/microsoft/vscode/assets/31622263/34b3eb9b-3ec1-4279-ab08-2b71301e3596)

After that, vscode never restart by itself (which was expected after clicking on a "Restart" button), and opening it manually (like in step 3) will start it in English, despite the French Language Pack is installed (visible in "Extensions" panel).

I join all vscode logs in a zip file (2 runs: first run after fresh install, second run started manually after step 8).
[logs.zip](https://github.com/microsoft/vscode/files/13613241/logs.zip)

The only relevant one, IMHO, is `sharedprocess.log` on the first run which have this content:
```
2023-12-08 11:54:02.506 [info] Started initializing default profile extensions in extensions installation folder. file:///home/mickael/.vscode-oss/extensions
2023-12-08 11:54:02.905 [info] Completed initializing default profile extensions in extensions installation folder. file:///home/mickael/.vscode-oss/extensions
2023-12-08 11:54:02.938 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/mickael/.vscode-oss/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/mickael/.vscode-oss/extensions/extensions.json.vsctmp'
    at r.create (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30056)
    at a (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30170)
    at s.fb (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36175)
    at s.stat (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:28621)
    at async E.stat (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:15732)
    at async Y.tb (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:111319)
2023-12-08 11:55:41.238 [info] Getting Manifest... ms-ceintl.vscode-language-pack-fr
2023-12-08 11:55:41.346 [info] Installing extension: ms-ceintl.vscode-language-pack-fr
2023-12-08 11:55:42.135 [info] Extension signature verification is not done: ms-ceintl.vscode-language-pack-fr
2023-12-08 11:55:42.228 [info] Extracted extension to file:///home/mickael/.vscode-oss/extensions/ms-ceintl.vscode-language-pack-fr-1.85.0-universal: ms-ceintl.vscode-language-pack-fr
2023-12-08 11:55:42.237 [info] Renamed to /home/mickael/.vscode-oss/extensions/ms-ceintl.vscode-language-pack-fr-1.85.0-universal
2023-12-08 11:55:42.239 [info] Extracting extension completed. ms-ceintl.vscode-language-pack-fr
2023-12-08 11:55:42.247 [info] Adding language packs from the extension ms-ceintl.vscode-language-pack-fr
2023-12-08 11:55:42.318 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/mickael/.vscode-oss/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/mickael/.vscode-oss/extensions/extensions.json.vsctmp'
    at r.create (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30056)
    at a (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30170)
    at s.fb (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36175)
    at s.stat (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:28621)
    at async E.stat (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:15732)
    at async Y.tb (/usr/lib/code/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:111319)
2023-12-08 11:55:42.321 [info] Extension installed successfully: ms-ceintl.vscode-language-pack-fr
```

Notice that I was able to use the French Language Pack long time ago, then it suddenly stop to works after some vscode update (around v1.81 or something IIRC). After that, never works again. Wasn't the time to look deeper until now, through.

Also, I'm opening this issue here because the same happens with others Language Pack as well (I tried with "Spanish", "Deutch" => same behavior).

**Comment by TylerLeonhardt** [comment]
Have you tried the `visual-studio-code-bin` flavor as talked about here: https://wiki.archlinux.org/title/Visual_Studio_Code
?

**Comment by alieonsido** [comment]
> Have you tried the `visual-studio-code-bin` flavor as talked about here: https://wiki.archlinux.org/title/Visual_Studio_Code ?

I had same issue as M1CK431, but the method is worked.
Thanks a lot for your help.

**Comment by M1CK431** [comment]
Thanks for you reply @TylerLeonhardt 🙏🏼 

> Have you tried the `visual-studio-code-bin` flavor as talked about here: https://wiki.archlinux.org/title/Visual_Studio_Code ?

No, I would like to use open source software as far as possible. After reading your comment and the feedback from @alieonsido, are languages packs supposed to be working only with the `visual-studio-code-bin` flavor?

**Comment by M1CK431** [comment]
This is very interesting, thanks a lot. I will open an issue at Archlinux side.

**Comment by M1CK431** [comment]
[UPDATE] This issue is now referenced here too: https://gitlab.archlinux.org/archlinux/packaging/packages/code/-/issues/2

**Comment by M1CK431** [comment]
[UPDATE] This bug is fixed now. See here for details: https://gitlab.archlinux.org/archlinux/packaging/packages/code/-/merge_requests/2

Closing this issue 🥲
