### ISSUE TITLE
Smoke Test Failure: Cannot find Stable VSCode at /var/folders/...

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#200348]
See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=248436&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&s=a56e7651-4213-56af-9488-c25fe636c10c&t=fb020c41-02a6-539b-31c1-63d55e575c1b&l=21

```
yarn run v1.22.19
$ cd test/smoke && node test/index.js --tracing --build '/Users/runner/work/1/VSCode-darwin-x64/Visual Studio Code - Insiders.app'


  1) "before all" hook in "{root}"

  0 passing (4s)
  1 failing

  1) "before all" hook in "{root}":
     Error: Cannot find Stable VSCode at /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/vscsmoke/s/vscode-darwin-1.85.0/Visual Studio Code.app.
      at ensureStableCode (src/main.ts:329:9)
      at measureAndLog (/Users/runner/work/1/s/test/automation/src/logger.ts:52:9)
      at setup (src/main.ts:343:3)
      at Context.<anonymous> (src/main.ts:372:2)

```

**Comment by bpasero** [comment]
I have not seen this before and I suspect an unhealthy CI, the log indicates a successful download to me:

```
[2023-12-08T12:21:35.206Z] Preparing smoketest setup...
[2023-12-08T12:21:35.206Z] Starting operation 'ensureStableCode'...
[2023-12-08T12:21:35.206Z] Starting operation 'versionReq'...
[2023-12-08T12:21:35.343Z] Finished operation 'versionReq' successfully after 137ms
[2023-12-08T12:21:35.344Z] Starting operation 'versionReq.json()'...
[2023-12-08T12:21:35.345Z] Finished operation 'versionReq.json()' successfully after 1ms
[2023-12-08T12:21:35.345Z] Found VS Code v1.86.0-insider, downloading previous VS Code version 1.85.0...
[2023-12-08T12:21:35.346Z] Starting operation 'download stable code'...
[2023-12-08T12:21:35.419Z] download stable code progress: resolvedVersion
[2023-12-08T12:21:35.422Z] download stable code progress: resolvingCDNLocation
[2023-12-08T12:21:35.586Z] download stable code progress: downloading (0/130942464)
[2023-12-08T12:21:38.509Z] download stable code progress: newInstallComplete
[2023-12-08T12:21:38.510Z] Finished operation 'download stable code' successfully after 3164ms
[2023-12-08T12:21:38.510Z] Finished operation 'ensureStableCode' with error Error: Cannot find Stable VSCode at /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/vscsmoke/s/vscode-darwin-1.85.0/Visual Studio Code.app. after 3304ms
[2023-12-08T12:21:38.514Z] Starting operation 'rimraf(testDataPath)'...
[2023-12-08T12:21:38.798Z] Finished operation 'rimraf(testDataPath)' successfully after 284ms
```

**Comment by joaomoreno** [comment]
We need to bump @vscode/test-electron to 2.3.8: https://github.com/microsoft/vscode-test/pull/248
