### ISSUE TITLE
Microphone icon not show

### ISSUE THREAD

**Issue by Hildorien** [microsoft/vscode#200493]
Type: <b>Bug</b>

After installing VS Code Speech, the mic icon is not shown in any chat prompt from Copilot.  Tried reloading vscode and even restarted after a clean installation.

Could not find anything similar on github issues. Microphone is picked up fine by other apps. It's like the extension does not exists. My vscode is installed as a snap package.

Context:

- OS: Ubuntu 22.04.3 LTS.
- Copilot version:  v1.141.0
- Info about vscode:
----------------------------------------------------------------------------------------
Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T22:27:05.695Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-37-generic snap
-------------------------------------------------------------------------------------------------

Extension version: 0.3.2023110115
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T22:27:05.695Z)
OS version: Linux x64 6.2.0-37-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics (12 x 3596)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|14.45GB (10.18GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 820b9794-3b50-42de-abdc-ea3ddad93176|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259

```

</details>

**Comment by bpasero** [comment]
Do you see the VS Code speech related output channel in the panel? Does it have anything?

**Comment by Hildorien** [comment]
> Do you see the VS Code speech related output channel in the panel? Does it have anything?

VS Code Speech is not even on the list in the output window dropdown. I'm also testing it on Windows and it works fine. The extension is also listed in the output command, however I don't see an output when I'm using it on my Windows PC. (Only in github copilot chat)

Going back to Ubuntu... It is really weird, as if VS Code is not recognizing the extension at all. I reinstalled my snap vscode package with all the extensions but the problem persists.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!

**Comment by Hildorien** [comment]
[main.log](https://github.com/microsoft/vscode/files/13640082/main.log)

I've did a clean install on the extension and opened copilot chat. Everything was logged. I've searched the extension folder and it was added correclty. The copilot chat extension does not show the microphone icon.

**Comment by bpasero** [comment]
Anything for the extension host?

<img width="1278" alt="image" src="https://github.com/microsoft/vscode/assets/900690/bf0eabb7-3f97-4dd2-84c2-9d13f6e91360">

**Comment by Hildorien** [comment]
> Anything for the extension host?
> 
> <img alt="image" width="1278" src="https://private-user-images.githubusercontent.com/900690/289650907-bf0eabb7-3f97-4dd2-84c2-9d13f6e91360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjM5MzUsIm5iZiI6MTcwMjMyMzYzNSwicGF0aCI6Ii85MDA2OTAvMjg5NjUwOTA3LWJmMGVhYmI3LTNmOTctNGRkMi04NGMyLTlkMTNmNmU5MTM2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxOTQwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDk5MjQ1OTg0NTllNGY3NWE5NzdhOGJmMjZhZjU5MzJlOTRmODc1M2I2ZGZmZDhhZTdmYTZjY2MwY2YzMDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f6HBiJHvk8LzWNE2oUUxYhSkW8JgkaHN1aPUc4bODEg">

Yes! Indeed the error is reported in that output:
`2023-12-11 16:11:04.758 [info] ExtensionService#_doActivateExtension ms-vscode.vscode-speech, startup: false, activationEvent: '*'
2023-12-11 16:11:04.759 [trace] ExtensionService#loadCommonJSModule file:///home/nacho/.vscode/extensions/ms-vscode.vscode-speech-0.2.0-linux-x64/dist/main.js
2023-12-11 16:11:04.759 [trace] ExtensionService#loadExtensionContext ms-vscode.vscode-speech
2023-12-11 16:11:04.765 [error] Activating extension ms-vscode.vscode-speech failed due to an error:
2023-12-11 16:11:04.765 [error] Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1401:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1869)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.c._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
    at Function.n._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
    at Function.t._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at Module.patchedRequire [as require] (/home/nacho/.vscode/extensions/github.copilot-1.141.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at h (/snap/code/147/usr/share/code/resources/app/out/vs/loader.js:4:647)
    at bindings (/home/nacho/.vscode/extensions/ms-vscode.vscode-speech-0.2.0-linux-x64/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/nacho/.vscode/extensions/ms-vscode.vscode-speech-0.2.0-linux-x64/node_modules/@vscode/node-speech/index.js:8:40)
    at Module.o._compile (/snap/code/147/usr/share/code/resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.c._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
    at Function.n._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
    at Function.t._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at Module.patchedRequire [as require] (/home/nacho/.vscode/extensions/github.copilot-1.141.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at h (/snap/code/147/usr/share/code/resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/home/nacho/.vscode/extensions/ms-vscode.vscode-speech-0.2.0-linux-x64/dist/main.js:1:232)
    at Module.o._compile (/snap/code/147/usr/share/code/resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.c._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
    at Function.n._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
    at Function.t._load (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at Module.patchedRequire [as require] (/home/nacho/.vscode/extensions/github.copilot-1.141.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Function.i [as __$__nodeRequire] (/snap/code/147/usr/share/code/resources/app/out/vs/loader.js:5:98)
    at f.vb (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:30730)
    at async Promise.all (index 0)`

**Comment by bpasero** [comment]
So the error seems to be: `version `GLIBC_2.33' not found`

@deepak1556 could you chime in, are we having a lower GLIBC version in our snaps compared to typical installations?

Azure Speech SDK requirements are stated here: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-csharp#platform-requirements

**Comment by deepak1556** [comment]
Yes we do, this will be addressed when we build speech extension with same toolchain as prod builds. I plan to make a change to `vscode-engineering` pipeline following the merge of https://github.com/microsoft/vscode/pull/192513 so that all extensions maintain the same glibc compatibility.

**Comment by deepak1556** [comment]
Once https://github.com/microsoft/vscode-engineering/pull/472 gets merged this should be good to go. I am working on getting the change merged this week.

**Comment by bpasero** [comment]
So in order to benefit from this, do I just release new versions of `node-speech` and `vscode-speech` extension?

**Comment by deepak1556** [comment]
Yes issue should be resolved with new versions of the extension.

**Comment by bpasero** [comment]
@Hildorien I just published a new prerelease of the Speech extension. If you could verify it works now by:
* installing VS Code insiders via Snap
* installing `ms-vscode.vscode-speech` version `v0.3.2024011810`
* seeing if it works now
