### ISSUE TITLE
VS Code Stable 1.9.0 - Extension does not get activated on Windows 7

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#20076]
- VSCode Version: 1.9.0
- OS Version: Windows 7

Steps to Reproduce:

1. Install VS Code 1.9
2. Install PowerShell extension 0.9.0
3. Create or open a PowerShell file (.ps1)
4. Notice that the extension does not activate and no extension commands are able to be executed (try "PowerShell: Run Selection").

A couple PowerShell extension users have reported that on Windows 7 and VS Code 1.9 the PowerShell extension no longer becomes activated when opening a .ps1 file (see PowerShell/vscode-powershell#488).  I have not personally been able to reproduce this issue so I'm looking for some ideas on what we can use to debug the problem.  Any ideas?

Thanks!

/cc @DerfOh @emmdeeess

**Comment by joaomoreno** [comment]
cc @sandy081 @bpasero Any ideas?

**Comment by bpasero** [comment]
@daviwil something in the console? 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by DerfOh** [comment]
```bash
code --verbose

←[93m[main 10:57:32 AM]←[0m Starting VS Code in verbose mode
←[93m[main 10:57:32 AM]←[0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
←[93m[main 10:57:32 AM]←[0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'new-window-if-not-first': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[12088:0208/155744:INFO:CONSOLE(70)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (70)
←[93m[main 10:57:44 AM]←[0m IPC#vscode-workbenchLoaded
[12088:0208/155748:INFO:CONSOLE(133)] "ERROR starting extension host", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (133)
[12088:0208/155748:INFO:CONSOLE(133)] "timeout", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (133)
ApplicationInsights:Sender [ { Error: unable to get local issuer certificate
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:584:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' } ]
ApplicationInsights:Sender [ { Error: unable to get local issuer certificate
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:584:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' } ]
←[93m[main 10:58:36 AM]←[0m Lifecycle#window-before-close 1
←[93m[main 10:58:36 AM]←[0m Lifecycle#unload() 1
←[93m[main 10:58:36 AM]←[0m Lifecycle#window-before-close 1
←[93m[main 10:58:36 AM]←[0m Lifecycle#window-close 1
←[93m[main 10:58:36 AM]←[0m Lifecycle#window-all-closed
←[93m[main 10:58:36 AM]←[0m Lifecycle#before-quit
←[93m[main 10:58:36 AM]←[0m App#will-quit: disposing resources

```

**Comment by bpasero** [comment]
@DerfOh do you get this as soon as you open a `*.ps1` file or actually right on startup?

**Comment by DerfOh** [comment]
This is right on startup with a ps1 file as one of the tabs saved using the hot exit feature. I will replicate this without the file being opened initially.

**Comment by sandy081** [comment]
@DerfOh Can you go to Extensions viewlet and see what it says for the installed extensions? Does the `reload` button is active?

**Comment by DerfOh** [comment]
@sandy081 PowerShell is the only active extension and it is at it's latest version (0.9.0) 
There is no option to reload the window.

**Comment by emmdeeess** [comment]
I had a chance to do some more testing today - The UNABLE_TO_GET_ISSUER_CERT_LOCALLY error occurs with or without "http.proxyStrictSSL": false set in 1.8 and 1.9. It still occurs even after I had Security put 191.238.172.191 into WebSense to exempt it from SSL MITM. The only new error in the console is:

[7568:0214/152620:INFO:CONSOLE(133)] "ERROR starting extension host", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (133)
[7568:0214/152620:INFO:CONSOLE(133)] "timeout", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (133)

Is there some further logging I can enable for the extension host to find out why it is failing?

**Comment by DerfOh** [comment]
Looks like some key endpoints were changed in 1.9 that were not accounted for in our firewall exception list. Closing as this issue has been resolved for us, thanks for your time @daviwil, @bpasero, @sandy081, and @joaomoreno :+1:

**Comment by joaomoreno** [comment]
Thanks for letting us know!
