### ISSUE TITLE
Issues when doing a find/replace with \n

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/vscode#20099]
![2017-02-07 13_33_34](https://cloud.githubusercontent.com/assets/15059605/22679081/6d8e6df4-ed3a-11e6-90ad-457d3d9173ed.gif)

**Comment by roblourens** [comment]
You will want to use `$` instead of `\n`. I'm seeing some other strange things though:

If I do a similar search,
![feb-07-2017 15-55-50](https://cloud.githubusercontent.com/assets/323878/22717113/2239f77e-ed4e-11e6-9d95-80040a5824ee.gif)

The error callstack is: 
```
Cannot read property 'replace' of null: TypeError: Cannot read property 'replace' of null
    at Object.escape (file:////Users/roblou/code/vscode/out/vs/base/common/strings.js:59:20)
    at SearchRenderer.renderContents (file:////Users/roblou/code/vscode/out/vs/workbench/parts/search/browser/searchResultsView.js:158:43)
    at SearchRenderer.ActionsRenderer.render (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/actionsRenderer.js:62:42)
    at SearchRenderer.LegacyRenderer.renderElement (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/treeDefaults.js:36:51)
    at ViewItem.render (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/treeView.js:230:39)
    at TreeView.refreshViewItem (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/treeView.js:893:18)
    at TreeView.onRefreshItem (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/treeView.js:883:18)
    at TreeView.HeightMap.onRemoveItems (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/treeViewModel.js:100:22)
    at TreeView.onItemChildrenRefreshed (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/treeView.js:743:34)
    at TreeView.onModelEvents (file:////Users/roblou/code/vscode/out/vs/base/parts/tree/browser/treeView.js:534:30)
Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at SearchViewlet.getSelectionFrom (file:////Users/roblou/code/vscode/out/vs/workbench/parts/search/browser/searchViewlet.js:927:69)
    at SearchViewlet.open (file:////Users/roblou/code/vscode/out/vs/workbench/parts/search/browser/searchViewlet.js:889:34)
    at file:////Users/roblou/code/vscode/out/vs/workbench/parts/search/browser/searchActions.js:500:35
    at CompletePromise_ctor.CompletePromise_then [as then] (file:////Users/roblou/code/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at ReplaceAction.run (file:////Users/roblou/code/vscode/out/vs/workbench/parts/search/browser/searchActions.js:492:64)
    at ActionRunner.run (file:////Users/roblou/code/vscode/out/vs/base/common/actions.js:202:52)
    at ActionItem.BaseActionItem.onClick (file:////Users/roblou/code/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:115:32)
    at file:////Users/roblou/code/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:98:55
```

**Comment by sandy081** [comment]
Firstly, multiline search is not supported yet for Search - See #13155. Issuse mentioned in the description needs multi line support. 

Issue mentioned in first comment is also related to multi line search. But it should not break the way it is now and has to be fixed to the current support. I would move that into a separate issue #20311 and fix it.

**Comment by sandy081** [comment]
Duplicates #13155
