### ISSUE TITLE
Can no longer search across all the files in the workspace

### ISSUE THREAD

**Issue by mikewguo** [microsoft/vscode#201138]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: vscode.dev

Search in workspace fails with: 'Unable to search with web worker text searcher'.
This is on a chromebook.

This used to work great, until a couple of weeks ago.
Please help / fix.  It's a great tool.

**Comment by andreamah** [comment]
Can you show a screen recording? Which browsers does this not work on?

**Comment by mikewguo** [comment]
Chrome browser on the chromebook.

**Comment by andreamah** [comment]
If you open the [chrome developer tools console](https://nira.com/chrome-developer-tools/), do you see any error messages?

**Comment by mikewguo** [comment]
ERR i.with is not a function: TypeError: i.with is not a function
    at v.getComparisonKey (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:146:8304)
    at S.c (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:1901:6010)
    at S.has (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:20:30478)
    at M (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:1901:2195)
    at y (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:1901:2793)
    at a.value (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:1901:8635)
    at u.y (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:87:1902)
    at u.fire (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:87:2119)
    at m.sendTextSearchMatch (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:1901:8047)
    at Object.handleMessage (https://main.vscode-cdn.net/stable/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/workbench.web.main.js:611:43479)

**Comment by mikewguo** [comment]
workbench.web.main.js:640   ERR i.with is not a function: TypeError: i.with is not a function

**Comment by andreamah** [comment]
Does this happen with other projects/repos also?

**Comment by mikewguo** [comment]
Happens to all project and reposGet Outlook for AndroidFrom: Andrea Mah ***@***.***>Sent: Monday, January 15, 2024 3:18:52 PMTo: microsoft/vscode ***@***.***>Cc: mikewguo ***@***.***>; Author ***@***.***>Subject: Re: [microsoft/vscode] Can no longer search across all the files in the workspace (Issue #201138)
Does this happen with other projects/repos also?

**Comment by andreamah** [comment]
@joyceerhl do you happen to know how we can test the `vscode.dev` on a chromebook (or know how we can try to repro this)?

**Comment by joyceerhl** [comment]
I cannot repro and I don't think any of us has a Chromebook, but it sounds like this was a recent regression. There hasn't been any change to how `getComparisonKey` in the call stack works https://github.com/microsoft/vscode/blob/078b98804ecf81cc7347a40604f63f4a494c9a71/src/vs/base/common/resources.ts#L161-L164, and it looks like we're trying to call `URI#with` on an object that doesn't actually have the `with` method. I'm wondering whether we might be passing an invalid URI to `getComparisonKey` somewhere in search, e.g. I think this can happen if the URI wasn't properly revived

**Comment by andreamah** [comment]
> Happens to all project and reposGet Outlook for AndroidFrom: Andrea Mah ***@***.***>Sent: Monday, January 15, 2024 3:18:52 PMTo: microsoft/vscode ***@***.***>Cc: mikewguo ***@***.***>; Author ***@***.***>Subject: Re: [microsoft/vscode] Can no longer search across all the files in the workspace (Issue #201138) Does this happen with other projects/repos also? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Does it happen if you open the vscode repo? https://github.com/microsoft/vscode Can you try that out?

**Comment by mikewguo** [comment]
yes, just tried on vscode repo.  Same problem: unable to search with web worker text search

**Comment by joyceerhl** [comment]
@mikewguo, are you opening the VS Code repo as a remote repository (i.e. https://vscode.dev/github/microsoft/vscode) or by using local file access to open files that are cloned to your machine?

**Comment by mikewguo** [comment]
by using local files, that are cloned to my machine.

**Comment by joyceerhl** [comment]
Ah, thanks for confirming. @andreamah this doesn't involve RemoteHub, so unassigning myself. I can repro btw:
1. Open vscode.dev
2. Open Folder > choose the VS Code repo locally 
3. Try to search for the string "foo", there are 6881 results when you do the same search on desktop
4. :bug: no results
