### ISSUE TITLE
Dev Container Attempts To Connect To Wayland-1 But Wayland-1 Does Not Exist

### ISSUE THREAD

**Issue by mcmah309** [microsoft/vscode#201402]
Vscode attempts to connect to `wayland-1` when starting a new dev container but `wayland-1` does not exist, should be `wayland-0`. I believe this issue is due to my laptop having 2 graphics card. An integrated intel and a dedicated nvidia. It seems vscode is getting confused.

Report
```
[2023-12-22T11:35:52.730Z] Dev Containers 0.327.0 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
[2023-12-22T11:35:52.730Z] Start: Resolving Remote
[2023-12-22T11:35:52.746Z] Setting up container for folder or workspace: /home/henry/work/testing/flutter_in_container
[2023-12-22T11:35:52.748Z] Start: Check Docker is running
[2023-12-22T11:35:52.748Z] Start: Run: podman version --format {{.Server.APIVersion}}
[2023-12-22T11:35:52.767Z] Stop (19 ms): Run: podman version --format {{.Server.APIVersion}}
[2023-12-22T11:35:52.767Z] Server API version: 4.8.1
[2023-12-22T11:35:52.767Z] Stop (19 ms): Check Docker is running
[2023-12-22T11:35:52.768Z] Start: Run: podman volume ls -q
[2023-12-22T11:35:52.789Z] Stop (21 ms): Run: podman volume ls -q
[2023-12-22T11:35:52.789Z] Start: Run: podman ps -q -a --filter label=vsch.local.folder=/home/henry/work/testing/flutter_in_container --filter label=vsch.quality=stable
[2023-12-22T11:35:52.811Z] Stop (22 ms): Run: podman ps -q -a --filter label=vsch.local.folder=/home/henry/work/testing/flutter_in_container --filter label=vsch.quality=stable
[2023-12-22T11:35:52.812Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --filter label=devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json
[2023-12-22T11:35:52.833Z] Stop (21 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --filter label=devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json
[2023-12-22T11:35:52.833Z] Start: Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:52.855Z] Stop (22 ms): Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:52.856Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container
[2023-12-22T11:35:52.881Z] Stop (25 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container
[2023-12-22T11:35:52.882Z] Start: Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:52.913Z] Stop (31 ms): Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:52.914Z] Start: Run: /nix/store/p25bs4m4j0v9ff5vchp6za94f4dg5hg9-vscode-1.85.1/lib/vscode/code --ms-enable-electron-run-as-node /home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --docker-path podman --workspace-folder /home/henry/work/testing/flutter_in_container --id-label devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --id-label devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --mount-workspace-git-root
[2023-12-22T11:35:52.933Z] [1222/063552.933120:WARNING:crashpad_client_linux.cc(364)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.033Z] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.5.13 x64.
[2023-12-22T11:35:53.033Z] Start: Run: git rev-parse --show-cdup
[2023-12-22T11:35:53.035Z] [1222/063553.035559:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.037Z] Stop (4 ms): Run: git rev-parse --show-cdup
[2023-12-22T11:35:53.038Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --filter label=devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json
[2023-12-22T11:35:53.039Z] [1222/063553.039330:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.060Z] Stop (22 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --filter label=devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json
[2023-12-22T11:35:53.060Z] Start: Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:53.062Z] [1222/063553.062055:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.083Z] Stop (23 ms): Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:53.086Z] Stop (172 ms): Run: /nix/store/p25bs4m4j0v9ff5vchp6za94f4dg5hg9-vscode-1.85.1/lib/vscode/code --ms-enable-electron-run-as-node /home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --docker-path podman --workspace-folder /home/henry/work/testing/flutter_in_container --id-label devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --id-label devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --mount-workspace-git-root
[2023-12-22T11:35:53.086Z] Start: Run: /nix/store/p25bs4m4j0v9ff5vchp6za94f4dg5hg9-vscode-1.85.1/lib/vscode/code --ms-enable-electron-run-as-node /home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/henry/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-20d38b7e-0333-4b53-a401-6bccdc6480e51703244952213 --workspace-folder /home/henry/work/testing/flutter_in_container --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --id-label devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-94a1815d-02e2-44a3-9738-d1fb92f8c7aa.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-22T11:35:53.106Z] [1222/063553.106580:WARNING:crashpad_client_linux.cc(364)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.209Z] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.5.13 x64.
[2023-12-22T11:35:53.209Z] Start: Run: podman buildx version
[2023-12-22T11:35:53.211Z] [1222/063553.211773:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.246Z] Stop (37 ms): Run: podman buildx version
[2023-12-22T11:35:53.246Z] buildah 1.33.2
[2023-12-22T11:35:53.247Z] 
[2023-12-22T11:35:53.247Z] Start: Resolving Remote
[2023-12-22T11:35:53.249Z] Start: Run: git rev-parse --show-cdup
[2023-12-22T11:35:53.250Z] [1222/063553.250484:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.252Z] Stop (3 ms): Run: git rev-parse --show-cdup
[2023-12-22T11:35:53.439Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --filter label=devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json
[2023-12-22T11:35:53.443Z] [1222/063553.442583:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.475Z] Stop (36 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --filter label=devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json
[2023-12-22T11:35:53.475Z] Start: Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:53.477Z] [1222/063553.477420:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.510Z] Stop (35 ms): Run: podman inspect --type container 945678af57c7
[2023-12-22T11:35:53.511Z] Start: Starting container
[2023-12-22T11:35:53.511Z] Start: Run: podman start 945678af57c7a2e968aba5a2f2c2002cfc1db2d958899a674cb5d1a52a9363e7
[2023-12-22T11:35:53.512Z] [1222/063553.512742:WARNING:crashpad_client_linux.cc(419)] prctl: Invalid argument (22)
[2023-12-22T11:35:53.607Z] Stop (96 ms): Run: podman start 945678af57c7a2e968aba5a2f2c2002cfc1db2d958899a674cb5d1a52a9363e7
[2023-12-22T11:35:53.608Z] Error: Command failed: podman start 945678af57c7a2e968aba5a2f2c2002cfc1db2d958899a674cb5d1a52a9363e7
[2023-12-22T11:35:53.608Z]     at J$ (/home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1253)
[2023-12-22T11:35:53.609Z]     at $J (/home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:997)
[2023-12-22T11:35:53.609Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-12-22T11:35:53.609Z]     at async tAA (/home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-12-22T11:35:53.609Z]     at async CC (/home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-12-22T11:35:53.609Z]     at async NeA (/home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2023-12-22T11:35:53.610Z]     at async MeA (/home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[2023-12-22T11:35:53.614Z] Stop (528 ms): Run: /nix/store/p25bs4m4j0v9ff5vchp6za94f4dg5hg9-vscode-1.85.1/lib/vscode/code --ms-enable-electron-run-as-node /home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/henry/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-20d38b7e-0333-4b53-a401-6bccdc6480e51703244952213 --workspace-folder /home/henry/work/testing/flutter_in_container --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --id-label devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-94a1815d-02e2-44a3-9738-d1fb92f8c7aa.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-22T11:35:53.615Z] Exit code 1
[2023-12-22T11:35:53.622Z] Command failed: /nix/store/p25bs4m4j0v9ff5vchp6za94f4dg5hg9-vscode-1.85.1/lib/vscode/code --ms-enable-electron-run-as-node /home/henry/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/henry/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-20d38b7e-0333-4b53-a401-6bccdc6480e51703244952213 --workspace-folder /home/henry/work/testing/flutter_in_container --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/henry/work/testing/flutter_in_container --id-label devcontainer.config_file=/home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/henry/work/testing/flutter_in_container/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-94a1815d-02e2-44a3-9738-d1fb92f8c7aa.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-22T11:35:53.622Z] Exit code 1'
```
Running the command from the logs locally:
```
podman start 945678af57c7a2e968aba5a2f2c2002cfc1db2d958899a674cb5d1a52a9363e7
```
output:
```
henry@nixos:~/work/testing/flutter_in_container/container (main)$ podman start 945678af57c7a2e968aba5a2f2c2002cfc1db2d958899a674cb5d1a52a9363e7
Error: unable to start container "945678af57c7a2e968aba5a2f2c2002cfc1db2d958899a674cb5d1a52a9363e7": crun: cannot stat `/run/user/1000/wayland-1`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```
More info:
```
henry@nixos:~/work/testing/flutter_in_container/container (main)$ l /run/user/1000/
total 8.0K
drwx------ 18 henry users 620 Dec 22 06:36 .
drwxr-xr-x  3 root  root   60 Dec 22 06:12 ..
drwx------  2 henry users  60 Dec 22 06:11 at-spi
srw-rw-rw-  1 henry users   0 Dec 22 06:11 bus
drwx------  7 henry users 140 Dec 22 06:15 containers
drwx------  2 henry users  40 Dec 22 06:37 crun
drwx------  3 henry users  60 Dec 22 06:11 dbus-1
drwx------  2 henry users  60 Dec 22 06:24 dconf
dr-x------  2 henry users   0 Dec 31  1969 doc
srwxr-xr-x  1 henry users   0 Dec 22 06:36 git-graph-askpass-nUVjW4jSQXs5H9eOq8XT35L1uSdiwkwU.sock
prw-r--r--  1 henry users   0 Dec 22 06:11 gnome-session-leader-fifo
drwx------  3 henry users  60 Dec 22 06:11 gnome-shell
drwx------  2 henry users 120 Dec 22 06:13 gnupg
dr-x------  2 henry users   0 Dec 22 06:11 gvfs
drwx------  2 henry users  40 Dec 22 06:24 gvfsd
-rw-------  1 henry users 314 Dec 22 06:11 ICEauthority
drwx------  2 henry users 120 Dec 22 06:13 keyring
drwx-----T  3 henry users  60 Dec 22 06:15 libpod
-rw-------  1 henry users  98 Dec 22 06:11 .mutter-Xwaylandauth.J3WOG2
srw-rw-rw-  1 henry users   0 Dec 22 06:11 pipewire-0
-rw-r-----  1 henry users   0 Dec 22 06:11 pipewire-0.lock
srw-rw-rw-  1 henry users   0 Dec 22 06:11 pipewire-0-manager
-rw-r-----  1 henry users   0 Dec 22 06:11 pipewire-0-manager.lock
drwxr-xr-x  2 henry users  60 Dec 22 06:11 podman
drwx------  2 henry users  80 Dec 22 06:11 pulse
drwxr-xr-x  7 henry users 180 Dec 22 06:11 systemd
srwxr-xr-x  1 henry users   0 Dec 22 06:13 vscode-5807d856-1.85-main.sock
srwxr-xr-x  1 henry users   0 Dec 22 06:36 vscode-git-29c980ecfd.sock
srwxr-xr-x  1 henry users   0 Dec 22 06:11 wayland-0
-rw-r-----  1 henry users   0 Dec 22 06:11 wayland-0.lock
drwx------  2 henry users  40 Dec 22 06:24 webkitgtk
henry@nixos:~/work/testing/flutter_in_container/container (main)$ echo $WAYLAND_DISPLAY
wayland-0
```
.devcontainer.json
```
{
    "name": "flutter_dev",
    "image": "flutter_dev",
    //"dockerFile": "../container/Containerfile",
    "customizations": {
      "vscode": {
        "extensions": [
          "dart-code.dart-code",
          "dart-code.flutter"
        ]
      }
    },
    "mounts": [
      "source=/dev/bus/usb,target=/dev/bus/usb,type=bind", 
      "source=./container/android_sdk,target=/opt/android-sdk,type=bind",
      "source=./container/gradle_caches,target=/root/.gradle/caches,type=bind",
      "source=./container/.bash_history,target=/root/.bash_history,type=bind"
    ],
    "runArgs": ["--net=host"]
  }
```
Running the container command from the command line works fine.
```
henry@nixos:~/work/testing/flutter_in_container (main)$ podman run -it --rm     -v /dev/bus/usb:/dev/bus/usb     -v $(pwd):/app     -v "$(pwd)/container/android_sdk:/opt/android-sdk"     -v "$(pwd)/container/gradle_caches:/root/.gradle/caches"     -v "$(pwd)/container/.bash_history:/root/.bash_history"     --net=host     localhost/flutter_dev bash
Image built at: Wed Dec 20 21:16:57 UTC 2023
root@c-nixos:/app (main)$ 
```

Steps to Reproduce:

1. Install Gnome on a nvidia prime device
2. Attempt to run a dev container in vscode

System:
```
henry@nixos:~/work/testing/flutter_in_container (main)$ inxi -bG
System:    Host: nixos Kernel: 6.5.13 x86_64 bits: 64 Desktop: GNOME 45.2 
           Distro: NixOS 24.05 (Uakari) 
Machine:   Type: Laptop System: System76 product: Adder WS v: addw3 
           serial: <superuser required> 
           Mobo: System76 model: Adder WS v: addw3 serial: <superuser required> 
           UEFI: coreboot v: 2023-09-19_16ef69c date: 09/15/2023 
Battery:   ID-1: BAT0 charge: 70.5 Wh (99.7%) condition: 70.7/70.8 Wh (99.8%) 
CPU:       Info: 16-Core 13th Gen Intel Core i9-13900HX [MT MCP] speed: 800 MHz 
           min/max: 800/5200 MHz 
Graphics:  Device-1: Intel Raptor Lake-S UHD Graphics driver: i915 v: kernel 
           Device-2: NVIDIA AD107M [GeForce RTX 4050 Max-Q / Mobile] driver: nvidia 
           v: 545.29.06 
           Device-3: Bison BisonCam NB Pro type: USB driver: uvcvideo 
           Display: wayland server: X.org 1.21.1.9 driver: loaded: nvidia 
           note: n/a (using device driver) resolution: <missing: xdpyinfo> 
           OpenGL: renderer: Mesa Intel Graphics (RPL-S) v: 4.6 Mesa 23.1.9 
Network:   Device-1: Intel driver: iwlwifi 
           Device-2: Intel driver: e1000e 
Drives:    Local Storage: total: 931.51 GiB used: 144.1 GiB (15.5%) 
Info:      Processes: 485 Uptime: N/A Memory: 62.65 GiB used: 3.37 GiB (5.4%) Shell: Bash 
           inxi: 3.3.04 
```

**Comment by mcmah309** [comment]
Also worth while mentioning, if I start the container from the command-line detached, I am able to attach vscode to the running container.

**Comment by chrmarti** [comment]
It passes `--mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-94a1815d-02e2-44a3-9738-d1fb92f8c7aa.sock` to the Dev Container CLI. I guess the container might be old and try to mount an old Wayland socket that no longer exists. Could you remove the container and retry?
