### ISSUE TITLE
Error: Cannot find module 'vscode' on Extension Host (remote)

### ISSUE THREAD

**Issue by miohtama** [microsoft/vscode#201874]
Does this issue occur when all extensions are disabled?: Irrelevant

- VS Code Version:  Version: 1.85.1 Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 Date: 2023-12-13T09:48:16.874Z (3 wks ago)
- OS Version:  Ubuntu 22.04.3 LTS

Steps to Reproduce:

1. Choose "Remote: Connect to SSH Host.."
2. Connect to a particular Ubuntu 22.04 server

Visual Studio Code Remote extension fails to load any plugins on a particular Linux server when connected using Remote - SSH. This is a server-specific issue, because the same Visual Studio Code (local) works with other servers. My suspect is that for some reason, due to OS configuration, shell configuration, missing Ubuntu packages or such, Visual Studio Code Remote development extension does not work correctly. However, Remote development extension fails to tell this to the user or detect that 1) it is corrupted 2) why it is corrupted, leading to a hard to diagnose problems in Visual Studio Code user interface, and thus user experience suffers.

When connected to a particular remote where Visual Studio Code encounters this issue, you will get the following error for the extensions in the Output > Extension host (Remote):

```
2024-01-05 09:04:18.179 [error] Activating extension ms-python.python failed due to an error:
2024-01-05 09:04:18.180 [error] Error: Cannot find module 'vscode'
Require stack:
- /root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js
- /root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/loader.js
- /root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/bootstrap-amd.js
- /root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 66828 (/root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:2631437)
	at __webpack_require__ (/root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:2977110)
	at 90209 (/root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:195419)
	at __webpack_require__ (/root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:2977110)
	at 69284 (/root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:679325)
	at __webpack_require__ (/root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:2977110)
	at /root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:2977979
	at /root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:2980546
	at Object.<anonymous> (/root/.vscode-server/extensions/ms-python.python-2023.22.1/out/client/extension.js:2:2980585)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at c._load (/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/loader.js:5:98)
	at f.vb (/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:168:30730)
	at async Promise.all (index 0)
```

(The error is repeated for each extension)

There does not seem to be no further context about the error, or hints how to fix this condition.

Plugins appear to be installed and do not have any error indicators on them. Plugin commands are still found in the command palette.

Choosing any extension command from the command palette will give you the error:

<img width="316" alt="image" src="https://github.com/microsoft/vscode/assets/49922/91c192b2-a67c-43a1-a9fb-bcfd6994f126">

```
Command 'Python: Select Interpreter' resulted in an error

command 'python.setInterpreter' not found
```

I already tried:

- Reinstall remote plugins
- Remove vscode files on the server: `rm -rf ~/..vscode-server`
- Kill all remote host processes: `pkill -f vscode`

[Related StackOverflow discussions](https://stackoverflow.com/questions/76823127/vs-code-not-activating-extensions-error-cannot-find-module-vscode).

**Comment by miohtama** [comment]
Now when looking the JavaScript stack trace, I suspect [Datadog](https://app.datadoghq.eu/account/login?next=%2F) is culprint and corrupts every JavaScript environment on the server.

**Comment by miohtama** [comment]
Removing Datadog fixes the issue, so I can confirm this be [an issue with Datadog and how it operates](https://github.com/DataDog/datadog-agent/issues/21882).
