### ISSUE TITLE
ListError [codeActionWidget] Invalid start index: 2

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#202009]
```javascript
Error: ListError [codeActionWidget] Invalid start index: 2
at ne.splice in src/vs/base/browser/ui/list/listWidget.ts:1539:10
at n.t in src/vs/platform/actionWidget/browser/actionList.ts:335:16
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2&bH=31f7428f-1b90-2689-a51f-865b87b532d2)

**Comment by justschen** [comment]
may be related to https://github.com/microsoft/vscode/issues/201812#issuecomment-1895376231

has the same stable release VS Code versions:

0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 
af28b32d7e553898b2a91af498b1fb666fdebe0c, 
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 
f1b07bd25dfad64b0167beb15359ae573aecd2cc
