### ISSUE TITLE
Sticky Scroll breaks for large Json files after roughly 50000 lines

### ISSUE THREAD

**Issue by zeroflag0** [microsoft/vscode#202138]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19045
```
Version: 1.86.0-insider (user setup)
Commit: fb769554405bee9be16e21ceb0a496bd29126941
Date: 2024-01-09T09:57:14.563Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```

Steps to Reproduce:

1. load json (?) file with more than 52632 (for one test, the next failed at 49xxx depending on the window-size) lines
2. scroll past line 52632 (or jump to end)

![image](https://github.com/microsoft/vscode/assets/11450358/bcf81d1f-404c-420c-a7a8-61c9f0e9f30d)

![image](https://github.com/microsoft/vscode/assets/11450358/b8b6a168-288d-44aa-aa60-908654de18b7)

**Comment by aeschli** [comment]
I see the same. the editor no longer renders the content.

Console shows:
```
  ERR TextModelPart is disposed!: Error: TextModelPart is disposed!
    at l.g (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:121:22482)
    at l.getWordAtPosition (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:642:122472)
    at U.getWordAtPosition (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:749:9052)
    at m.h (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:773:73328)
    at new f (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:773:73203)
    at new m (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:773:73784)
    at T (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:773:74584)
    at P.F (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:773:79173)
    at P.E (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:773:78908)
    at h.value (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:773:75352)
    at d.y (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at d.z (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at d.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2036)
    at h.value (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:757:15263)
    at d.y (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at d.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at E.s (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:106436)
    at E.emitOutgoingEvent (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:106190)
    at h.value (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:754:22176)
    at d.y (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at d.z (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at d.fire (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at I.n (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:17588)
    at I.setScrollDimensions (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:16330)
    at k.setScrollDimensions (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:112064)
    at w.n (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:114115)
    at w.onHeightMaybeChanged (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:113135)
    at w.changeWhitespace (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:115390)
    at $.changeWhitespace (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:755:3855)
    at p.changeViewZones (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:72557)
    at q.change (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:736:24055)
    at x.changeViewZones (vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:757:13688)

```

**Comment by connor4312** [comment]
![image](https://github.com/microsoft/vscode/assets/2230985/495e7fd3-f4fb-40f1-9f91-6c6a78f5b4df)

**Comment by connor4312** [comment]
@hediet this appears to have regressed following https://github.com/microsoft/vscode/pull/194712 based on a git bisect

**Comment by antlaij** [comment]
I have just updated to the following version.
That fixed this large file issue
![image](https://github.com/microsoft/vscode/assets/15242427/4b42bb03-79c3-47b1-8b3d-604482f9d8f9)

Thanks for the VS code team to fix this issue

**Comment by Aetherinox** [comment]
Came here looking for a solution, I am also having this issue, and the latest version does not correct it.

![ukIArlt](https://github.com/microsoft/vscode/assets/118329232/c2ada809-7495-4db2-846c-93df5e5ca239)

**Comment by connor4312** [comment]
@Aetherinox based on your screenshot, you are on an old Insiders version. Please update for the fix.

**Comment by Aetherinox** [comment]
Interesting, clicked update from within Insiders. I'll manually download again from the website and reinstall.

**Comment by Aetherinox** [comment]
Thanks, sorry about that. No idea why VSC didn't detect an update. Manually installing worked.
![wuFpV9r](https://github.com/microsoft/vscode/assets/118329232/752601d1-326c-46e7-9478-d2dba077278b)

Appreciate it.
