### ISSUE TITLE
TS Server fatal error:  UNC host 'wsl.localhost' access is not allowed

### ISSUE THREAD

**Issue by drescamarian** [microsoft/vscode#202260]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.3.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error [ERR_UNC_HOST_NOT_ALLOWED]: UNC host 'wsl.localhost' access is not allowed
    at Object.watchFile (node:fs:2405:14)
    at fsWatchFileWorker (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8590:11)
    at d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8237:15
    at createSingleWatcherPerName (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7758:16)
    at pollingWatchFile (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8232:12)
    at watchFile2 (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8067:16)
    at watchMissingFileSystemEntry (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8325:14)
    at fsWatchHandlingExistenceOnHost (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8256:72)
    at d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8246:15
    at createSingleWatcherPerName (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:7758:16)
    at fsWatch (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8241:12)
    at Object.watchFile2 [as watchFile] (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8092:16)
    at watchFile (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120258:67)
    at Object.watchFile (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120277:283)
    at d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179929:183
    at _ProjectService.forEachConfigFileLocation (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179979:22)
    at _ProjectService.startWatchingConfigFilesForInferredProjectRoot (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179922:10)
    at InferredProject2.addRoot (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178082:25)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179720:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181347:12)
    at d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181577:64
    at flatMap (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2597:17)
    at _ProjectService.applyChangesInOpenFiles (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181577:24)
    at updateOpen (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182775:29)
    at d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:69
    at IpcIOSession.executeWithRequestId (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185369:14)
    at IpcIOSession.executeCommand (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:29)
    at IpcIOSession.onMessage (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185419:51)
    at process.<anonymous> (d:\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187001:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i3-12100F (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.12GB free)|
|Process Argv|. --crash-reporter-id 14afb9ed-f2d0-4053-997a-f122ccfc6453|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
node-js-snippet|abd|1.1.3
npm-intellisense|chr|1.4.5
flask-snippets|cst|0.1.3
vscode-eslint|dba|2.4.2
emoji-snippets|dev|1.5.3
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.3.1
auto-rename-tag|for|0.1.10
codespaces|Git|1.16.6
copilot|Git|1.148.646
copilot-chat|Git|0.12.2023120701
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.78.1
live-sass|gle|6.1.2
vscode-drawio|hed|1.6.6
git-graph|mhu|1.30.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
vscode-serial-monitor|ms-|0.11.0
LiveServer|rit|5.7.9
pdf|tom|1.2.2
cmake|twx|0.0.17
errorlens|use|3.16.0
vscode-arduino|vsc|0.6.0
glean|wix|5.2.2
glean-react-refactor|Woo|4.8.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by bpasero** [comment]
Beginning with VS Code `1.78.1` accessing any UNC path (those that begin with `\\`) on Windows is blocked to mitigate a security risk that is further explained in this [Security Advisory](https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr).

Please refer to https://aka.ms/vscode-windows-unc for more information how to make your specific UNC path work again.
