### ISSUE TITLE
Error when updating decorations after deleting chat variable

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#202374]
- Open the chat sidebar
- Type `#`, pick `#file` from suggest widget
- Pick a file, so it reads eg `#file:foo.ts`
- Delete the full contents of the input with cmd+backspace
- Get this error

```
2024-01-12 16:53:53.671 [error] Invoking deltaDecorations recursively could lead to leaking decorations.: Error: Invoking deltaDecorations recursively could lead to leaking decorations.
    at TextModel.deltaDecorations (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/model/textModel.js:1236:53)
    at CodeEditorWidget.deltaDecorations (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:900:42)
    at CodeEditorWidget.setDecorationsByType (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:944:69)
    at InputEditorDecorations.updateInputEditorDecorations (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.js:112:41)
    at UniqueContainer.value (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.js:40:87)
    at Emitter._deliver (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:889:26)
    at Emitter._deliverQueue (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:900:22)
    at Emitter.fire (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:910:22)
    at UniqueContainer.value (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1249:57)
    at Emitter._deliver (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:918:22)
    at ViewModelEventDispatcher._emitOutgoingEvents (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModelEventDispatcher.js:46:31)
    at ViewModelEventDispatcher.endEmitViewEvents (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModelEventDispatcher.js:85:18)
    at ViewModelEventDispatcher.emitSingleViewEvent (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModelEventDispatcher.js:93:22)
    at UniqueContainer.value (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:342:39)
    at Emitter._deliver (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:918:22)
    at DidChangeDecorationsEmitter.doFire (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/model/textModel.js:1879:26)
    at DidChangeDecorationsEmitter.endDeferredEmit (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/model/textModel.js:1834:26)
    at TextModel.deltaDecorations (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/model/textModel.js:1242:46)
    at CodeEditorWidget.deltaDecorations (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:900:42)
    at CodeEditorWidget.setDecorationsByType (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:944:69)
    at ChatDynamicVariableModel.updateDecorations (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/workbench/contrib/chat/browser/contrib/chatDynamicVariables.js:78:37)
    at UniqueContainer.value (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/workbench/contrib/chat/browser/contrib/chatDynamicVariables.js:58:22)
    at Emitter._deliver (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:889:26)
    at Emitter._deliverQueue (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:900:22)
    at Emitter.fire (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:923:22)
    at UniqueContainer.value (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:1273:55)
    at Emitter._deliver (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/base/common/event.js:918:22)
    at ViewModelEventDispatcher._emitOutgoingEvents (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModelEventDispatcher.js:46:31)
    at ViewModelEventDispatcher.endEmitViewEvents (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModelEventDispatcher.js:85:18)
    at ViewModel._withViewEventsCollector (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:866:39)
    at ViewModel._executeCursorEdit (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:805:18)
    at ViewModel.executeEdits (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:808:18)
    at CodeEditorWidget.executeEdits (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:853:39)
    at DeleteAllLeftAction.run (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/contrib/linesOperations/browser/linesOperations.js:519:20)
    at DeleteAllLeftAction.runEditorCommand (vscode-file://vscode-app/Users/roblou/code/vscode/out/vs/editor/browser/editorExtensions.js:241:25)
```

I think I understand what's happening here. I have two `onDidChangeModelContent` listeners that each call `setDecorationsByType`. The first one runs, and after setting decorations, it calls `endDeferredEmit` to continue firing events, so my second listener runs, and also calls `setDecorationsByType`. And this is considered recursive because it happens before `_deltaDecorationCallCnt` was decremented but isn't "really" recursive, to me.

So is it bad practice to call `setDecorationsByType` synchronously inside `onDidChangeModelContent`? Or is there something else I should be doing differently? @hediet?

**Comment by hediet** [comment]
I think the actual problem is that `deltaDecorations` is used here:

https://github.com/microsoft/vscode/blob/0bf3670b5257a485071219048d692da7db3d4770/src/vs/editor/browser/widget/codeEditorWidget.ts#L1350
