### ISSUE TITLE
Markdown it plugin fails to load

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#202375]
On latest insiders
```
Could not load markdown it plugin TypeError: e.apply is not a function
	at S.use (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:191596)
	at Object.extendMarkdownIt (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-math/dist/extension.js:1:272578)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:645237
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:640595
	at async t.$n.g (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:640947)
	at async t.$n.tokenize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:641615) {stack: 'TypeError: e.apply is not a function
	at S.us…language-features/dist/extension.js:1:641615)', message: 'e.apply is not a function'}

```

**Comment by mjbvz** [comment]
I think I already fixed this. There was a issue with the katex plugin
