### ISSUE TITLE
TypeScript Inlay Hint Disappeared

### ISSUE THREAD

**Issue by E-uler** [microsoft/vscode#202311]
When I scroll to a certain position, the inlay hint disappeared.

<semantic> TypeScript Server Error (5.3.2)
Debug Failure. Unexpected node.
Node IndexSignature was unexpected.
Error: Debug Failure. Unexpected node.
Node IndexSignature was unexpected.
    at visitForDisplayParts (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165385:17)
    at d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165393:9
    at Array.forEach (<anonymous>)
    at visitDisplayPartList (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165389:13)
    at visitForDisplayParts (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165228:13)
    at typeToInlayHintParts (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165115:5)
    at visitVariableLikeDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164923:23)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164845:7)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInVariableDeclarationList (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30454:12)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInVariableStatement (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30451:59)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInBlock (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30704:10)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInIfStatement (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30460:51)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInIfStatement (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30460:93)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInBlock (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30704:10)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInMethodDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30306:354)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInClassDeclarationOrExpression (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30710:195)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInBlock (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30704:10)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInModuleDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30527:92)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInSourceFile (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30448:12)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at Object.provideInlayHints (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164821:3)
    at Object.provideInlayHints2 [as provideInlayHints] (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145846:34)
    at IpcIOSession.provideInlayHints (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184199:48)
    at provideInlayHints (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183358:43)
    at d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:69
    at IpcIOSession.executeWithRequestId (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185369:14)
    at IpcIOSession.executeCommand (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:29)
    at IpcIOSession.onMessage (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185419:51)
    at process.<anonymous> (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187001:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.3.2)
Debug Failure. Unexpected node.
Node IndexSignature was unexpected.
Error: Debug Failure. Unexpected node.
Node IndexSignature was unexpected.
    at visitForDisplayParts (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165385:17)
    at d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165393:9
    at Array.forEach (<anonymous>)
    at visitDisplayPartList (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165389:13)
    at visitForDisplayParts (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165228:13)
    at typeToInlayHintParts (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165115:5)
    at visitVariableLikeDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164923:23)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164845:7)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInVariableDeclarationList (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30454:12)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInVariableStatement (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30451:59)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInBlock (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30704:10)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInIfStatement (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30460:51)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInIfStatement (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30460:93)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInBlock (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30704:10)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInMethodDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30306:354)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInClassDeclarationOrExpression (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30710:195)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInBlock (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30704:10)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNode2 (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInModuleDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30527:92)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at visitNodes (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30235:22)
    at forEachChildInSourceFile (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30448:12)
    at forEachChild (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30744:35)
    at visitor (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164860:12)
    at Object.provideInlayHints (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164821:3)
    at Object.provideInlayHints2 [as provideInlayHints] (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145846:34)
    at IpcIOSession.provideInlayHints (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184199:48)
    at provideInlayHints (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183358:43)
    at d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:69
    at IpcIOSession.executeWithRequestId (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185369:14)
    at IpcIOSession.executeCommand (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:29)
    at IpcIOSession.onMessage (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185419:51)
    at process.<anonymous> (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187001:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
	at n.create (d:\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:474656)
	at v.w (d:\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:469981)
	at v.u (d:\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:469064)
	at ChildProcess.<anonymous> (d:\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:468696)
	at ChildProcess.emit (node:events:513:28)
	at emit (node:internal/child_process:937:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by E-uler** [comment]
I think I can fix this bug temporary:

1. Locate to "switch (node.kind)" in function "visitForDisplayParts()" => %VSCode Installed Directory%\resources\app\extensions\node_modules\typescript\lib\tsserver.js (line:165130)
2. insert the case 181 :
```js
case 181 /* IndexSignature */:
  const indexSignature = node;
    if (indexSignature.modifiers) {
      visitDisplayPartList(indexSignature.modifiers, " ");
    }
    parts.push({ text: "[" });
    visitDisplayPartList(indexSignature.parameters, ", ");
    parts.push({ text: "]" });
    if (indexSignature.type) {
      parts.push({ text: ": " });
      visitForDisplayParts(indexSignature.type);
    }
  break;
```
3. restart VSCode

**Comment by mjbvz** [comment]
Please share some example code which demonstrates the issue

**Comment by PraetorP** [comment]
> I think I can fix this bug temporary:
> 
> 1. Locate to "switch (node.kind)" in function "visitForDisplayParts()" => %VSCode Installed Directory%\resources\app\extensions\node_modules\typescript\lib\tsserver.js (line:165130)
> 2. insert the case 181 :
> 
> ```js
> case 181 /* IndexSignature */:
>   const indexSignature = node;
>     if (indexSignature.modifiers) {
>       visitDisplayPartList(indexSignature.modifiers, " ");
>     }
>     parts.push({ text: "[" });
>     visitDisplayPartList(indexSignature.parameters, ", ");
>     parts.push({ text: "]" });
>     if (indexSignature.type) {
>       parts.push({ text: ": " });
>       visitForDisplayParts(indexSignature.type);
>     }
>   break;
> ```
> 
> 3. restart VSCode

It didn't help ( at least for me).
```
2024-02-08 21:23:14.946 [error] [vscode.typescript-language-features] provider FAILED
2024-02-08 21:23:14.946 [error] Error: <semantic> TypeScript Server Error (5.3.2)
Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
Error: Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
    at visitForDisplayParts (/home/praetorp/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/extensions/node_modules/typescript/lib/tsserver.js:165398:17)
    at visitForDisplayParts (/home/praetorp/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/extensions/node_modules/typescript/lib/tsserver.js:165203:11)
    at /home/praetorp/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/extensions/node_modules/typescript/lib/tsserver.js:165406:9
    at Array.forEach (<anonymous>)
 ```

**Comment by mjbvz** [comment]
Closing as we can't investigate without a way to reproduce the problem

**Comment by E-uler** [comment]
The same problem applies to ThisType, refer to this code:
```ts
class A
{
    func()
    {
        let self = this;
    }
}
```
issues: variable self has not show inlay hint

**Comment by E-uler** [comment]
> > I think I can fix this bug temporary:
> > 
> > 1. Locate to "switch (node.kind)" in function "visitForDisplayParts()" => %VSCode Installed Directory%\resources\app\extensions\node_modules\typescript\lib\tsserver.js (line:165130)
> > 2. insert the case 181 :
> > 
> > ```js
> > case 181 /* IndexSignature */:
> >   const indexSignature = node;
> >     if (indexSignature.modifiers) {
> >       visitDisplayPartList(indexSignature.modifiers, " ");
> >     }
> >     parts.push({ text: "[" });
> >     visitDisplayPartList(indexSignature.parameters, ", ");
> >     parts.push({ text: "]" });
> >     if (indexSignature.type) {
> >       parts.push({ text: ": " });
> >       visitForDisplayParts(indexSignature.type);
> >     }
> >   break;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. restart VSCode
> 
> It didn't help ( at least for me).
> 
> ```
> 2024-02-08 21:23:14.946 [error] [vscode.typescript-language-features] provider FAILED
> 2024-02-08 21:23:14.946 [error] Error: <semantic> TypeScript Server Error (5.3.2)
> Debug Failure. Unexpected node.
> Node ObjectBindingPattern was unexpected.
> Error: Debug Failure. Unexpected node.
> Node ObjectBindingPattern was unexpected.
>     at visitForDisplayParts (/home/praetorp/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/extensions/node_modules/typescript/lib/tsserver.js:165398:17)
>     at visitForDisplayParts (/home/praetorp/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/extensions/node_modules/typescript/lib/tsserver.js:165203:11)
>     at /home/praetorp/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/extensions/node_modules/typescript/lib/tsserver.js:165406:9
>     at Array.forEach (<anonymous>)
> ```

I dont know which type about "ObjectBindingPattern", but I found the node kind of this type is 206.
You can bypass this error to enable the Inlay Hint function of the other context.
in step2, insert the case 206:
```js
        case 206 /* ObjectBindingPattern */:
          //todo
          parts.push({ text: "ObjectBindingPattern" });
          break;
```

**Comment by xxshady** [comment]
@mjbvz can you please reopen this issue, i'am able to reproduce it aswell with this code:

```ts
class Repro {
    public get repro() {
        return {
            get() {
                return 123
            }
        }
    }
}

const v = ({} as Repro).repro.get()
```

and settings:
```json
"typescript.inlayHints.functionLikeReturnTypes.enabled": true,
"typescript.inlayHints.variableTypes.enabled": true,
```

when you enable `typescript.inlayHints.functionLikeReturnTypes.enabled` this bug appears

![3-16-2024 (15-50-35)](https://github.com/microsoft/vscode/assets/54737754/a1a6d02b-5d9c-4406-a89f-b290d5306ba7)
