### ISSUE TITLE
Notebook Kernel API tests replaceOutput to different cell

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202498]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=251514&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=efbaf268-cf98-50c2-bb3c-7950770fd6bc&l=654

```
1) Notebook Kernel API tests
       replaceOutput to different cell:
     Error: asPromise TIMEOUT reached
      at asPromise (/Users/runner/work/1/s/extensions/vscode-api-tests/src/utils.ts:136:16)
      at withEvent (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:27:21)
      at Context.<anonymous> (/Users/runner/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts:469:9)
```

**Comment by rebornix** [comment]
Merging into https://github.com/microsoft/vscode/issues/183007
