### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isLocked')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202515]
Found this stack in my insiders, did some contribution move to such an early phase even before editors are created maybe?

```
Cannot read properties of undefined (reading 'isLocked'): TypeError: Cannot read properties of undefined (reading 'isLocked')
at [./workbench/services/editor/common/editorGroupFinder.ts:180:12](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/services/editor/common/editorGroupFinder.ts#L180)
([./workbench/services/editor/common/editorGroupFinder.ts:151:6](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/services/editor/common/editorGroupFinder.ts#L151))
([./workbench/services/editor/common/editorGroupFinder.ts:30:15](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/services/editor/common/editorGroupFinder.ts#L30))
([./platform/instantiation/common/instantiationService.ts:68:10](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/platform/instantiation/common/instantiationService.ts#L68))
at [./workbench/services/editor/browser/editorResolverService.ts:90:52](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/services/editor/browser/editorResolverService.ts#L90)
at [./workbench/services/editor/browser/editorResolverService.ts:111:45](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/services/editor/browser/editorResolverService.ts#L111)
at [./workbench/services/editor/browser/editorService.ts:521:59](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/services/editor/browser/editorService.ts#L521)
at [./workbench/contrib/welcomeGettingStarted/browser/startupPage.ts:193:22](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts#L193)
at [./workbench/contrib/welcomeGettingStarted/browser/startupPage.ts:96:14](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts#L96)
at [./workbench/contrib/welcomeGettingStarted/browser/startupPage.ts:82:7](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts#L82)
at [./platform/instantiation/common/instantiationService.ts:119:17](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/platform/instantiation/common/instantiationService.ts#L119)
at [./platform/instantiation/common/instantiationService.ts:85:17](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/platform/instantiation/common/instantiationService.ts#L85)
at [./workbench/common/contributions.ts:187:24](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/common/contributions.ts#L187)
at [./workbench/common/contributions.ts:125:11](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/common/contributions.ts#L125)
at [./workbench/common/contributions.ts:101:8](https://github.com/microsoft/vscode/blob/81725794264e4c0fddbc1b3b728013744ae90840/src/vs/workbench/common/contributions.ts#L101)
```

**Comment by bpasero** [comment]
I think from https://github.com/microsoft/vscode/pull/201844. Can we keep the phase and fix the issue https://github.com/microsoft/vscode/issues/193623 differently?
