### ISSUE TITLE
Unable to create workbench contribution ConfigurationTelemetryContribution

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202917]
Running out of sources:

```
ERR Unable to create workbench contribution ConfigurationTelemetryContribution. TypeError: Cannot read properties of undefined (reading 'tags')
    at new ConfigurationTelemetryContribution (configurationService.js:1093:28)
    at InstantiationService._createInstance (instantiationService.js:91:28)
    at InstantiationService.createInstance (instantiationService.js:62:31)
    at WorkbenchContributionsRegistry.safeCreateContribution (contributions.js:111:38)
    at instantiateSome (contributions.js:92:26)
```

**Comment by sandy081** [comment]
fixed
