### ISSUE TITLE
Speech provider with identifier ms-vscode.vscode-speech is already registered

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203172]
Testing #202926

Kept playing with "hey code", at one point the EH restarted (unsure why but likely due to speech). Anyways, the console showed the error below which likely means some `mainThreadXYZ` didn't dispose something. Once you are in this state speech is broken

```
2024-01-23 16:33:30.217 [error] Error: Speech provider with identifier ms-vscode.vscode-speech is already registered.
    at w.registerSpeechProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1108:6841)
    at v.$registerProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1584:31138)
    at $.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:13967)
    at $.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:13733)
    at $.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:12826)
    at $.L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:11905)
    at o.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:10692)
    at a.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:629:14452)
    at x.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1663:7749)
2024-01-23 16:33:30.541 [info] Eager extensions activated
```

**Comment by jrieken** [comment]
Steps

* open vscode, start speech
* F1 > restart EH
* error shows, speech is broken

**Comment by bpasero** [comment]
I always keep forgetting this in `mainThreadXY`, we should probably have some kind of lint rule...
