### ISSUE TITLE
inline chat UI stuck on error

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203173]
Got the trace below, this happens when PAUSE is enter as part of error handling which then also errors...

```
ERR Unexpected type: Error: Unexpected type
    at b (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:93:10132)
    at K.PAUSE (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:42819)
    at K.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33125)
```

**Comment by jrieken** [comment]
The error leading up to this is: 

```
2024-01-23 16:36:20.400 [error] Session already stored for vs.editor.ICodeEditor:1@file:///Users/jrieken/Code/vscode/src/vscode-dts/vscode.proposed.taskPresentationGroup.d.ts: Error: Session already stored for vs.editor.ICodeEditor:1@file:///Users/jrieken/Code/vscode/src/vscode-dts/vscode.proposed.taskPresentationGroup.d.ts
    at u.createSession (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1911:72922)
    at async K.CREATE_SESSION (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33692)
    at async K.R (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33226)
    at async K.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33046)
2024-01-23 16:36:20.400 [error] Unexpected type: Error: Unexpected type
```

**Comment by jrieken** [comment]
To verify

* start inline chat
* get it to make changes
* select ESC to hide inline chat
* select cmd+i to start inline chat again
