### ISSUE TITLE
Error when using plugin.

### ISSUE THREAD

**Issue by CaiusTSM** [Microsoft/vscode#2032]
TypeError: Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:19:2756
    at Object.p [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:2360)
    at Object.__dirname.undefined.L.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:5522)
    at __dirname.undefined.t.Class.define._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:7348)
    at __dirname.undefined.t.Class.define._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:6789)
    at runMicrotasksCallback (node.js:326:7)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by alexandrudima** [comment]
@CaiusTSM Can you please provide steps?

**Comment by alexandrudima** [comment]
@CaiusTSM Please reopen or file a new issue with reproducible steps.
