### ISSUE TITLE
Activating extension vscode.typescript-language-features failed due to an error EEXIST: file already exists

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#203335]
* I restarted my machine
* I had 4 windows opened
* In one window, I noticed that I could not go to definition in TS files anymore
* The extenion host log shows:
```
2024-01-24 14:10:48.760 [info] Extension host with pid 1184 started
2024-01-24 14:10:48.760 [info] Skipping acquiring lock for /Users/alex/Library/Application Support/Code - Insiders/User/workspaceStorage/c55b8be4c94bd887d58868b2cc82fcf5.
2024-01-24 14:10:48.760 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:typescript'
2024-01-24 14:10:48.760 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-01-24 14:10:48.771 [error] Activating extension vscode.typescript-language-features failed due to an error:
2024-01-24 14:10:48.771 [error] Error: EEXIST: file already exists, mkdir '/var/folders/bb/_8jjjyy971x2frm3nr3g7m4r0000gn/T/vscode-typescript501'
	at Object.mkdirSync (node:fs:1400:3)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:547693
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:547755
	at t.$td (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:547847)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:539898
	at t.activate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:294122)
	at z.ib (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:13232)
	at z.hb (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:12946)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:11081
	at async c.n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6256)
	at async c.m (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6219)
	at async c.l (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:5676)
2024-01-24 14:10:48.787 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
...
```

![image](https://github.com/microsoft/vscode/assets/5047891/c94107fb-3be7-485a-8bc8-2f2b5686a3d9)

```
Version: 1.86.0-insider
Commit: 1091f68d834974d78cd4f9769034b4ae4581ff2a
Date: 2024-01-24T05:46:06.517Z
Electron: 27.2.3
ElectronBuildId: 26378995
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
```

**Comment by mjbvz** [comment]
Likely not a regression so moving to next release to reduce chances of breaking things

**Comment by alexr00** [comment]
@mjbvz what's the best way to verify this?
