### ISSUE TITLE
Error: Trying to add a disposable to a DisposableStore that has already been disposed of.

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203437]
Seeing this in my logs (a lot)

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at f.add (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:37:1571)
    at f.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1890:9420)
    at f.registerExternalLinkProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1890:12800)
    at o.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2663:6603)
    at a.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at a.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at S.registerLinkProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1153:13025)
    at s.$startLinkProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1707:15974)
    at m.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1590:13967)
    at m.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1590:13733)
    at m.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1590:12826)
    at m.L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1590:11905)
    at o.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1590:10692)
    at a.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:628:14452)
    at x.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1662:7749)
```

**Comment by jrieken** [comment]
maybe/likely related to https://github.com/microsoft/vscode/issues/203435

**Comment by jrieken** [comment]
It seems that the `TerminalLinkManager` itself is disposed when this happens. It's also noteworthy that calling `registerExternalLinkProvider` piles ups data that the disposable it returns isn't ever freed, e.g `_externalLinkProviders` isn't cleaned-up and `_setupLinkDetector` writes to the store of link manager itself

**Comment by bpasero** [comment]
Fyi https://tools.code.visualstudio.com/stack-beautifier?version=3dea5cbbcb88d7f6dad71148f3d3f98b853ab836

```
at has
at [./base/common/lifecycle.ts:425:17](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/base/common/lifecycle.ts#L425)
at [./workbench/contrib/terminalContrib/links/browser/terminalLinkManager.ts:135:31](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkManager.ts#L135)
at [./workbench/contrib/terminalContrib/links/browser/terminalLinkManager.ts:359:35](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkManager.ts#L359)
at [./workbench/contrib/terminalContrib/links/browser/terminal.links.contribution.ts:69:16](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/contrib/terminalContrib/links/browser/terminal.links.contribution.ts#L69)
at [./base/common/event.ts:1127:12](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/base/common/event.ts#L1127)
at [./base/common/event.ts:1138:8](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/base/common/event.ts#L1138)
at [./base/common/event.ts:1162:8](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/base/common/event.ts#L1162)
at [./workbench/contrib/terminalContrib/links/browser/terminalLinkProviderService.ts:25:29](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkProviderService.ts#L25)
at [./workbench/api/browser/mainThreadTerminalService.ts:257:57](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/api/browser/mainThreadTerminalService.ts#L257)
at [./workbench/services/extensions/common/rpcProtocol.ts:458:16](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L458)
at [./workbench/services/extensions/common/rpcProtocol.ts:443:31](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L443)
at [./workbench/services/extensions/common/rpcProtocol.ts:373:18](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L373)
at [./workbench/services/extensions/common/rpcProtocol.ts:299:9](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L299)
at [./workbench/services/extensions/common/rpcProtocol.ts:161:41](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L161)
at [./base/common/event.ts:1127:12](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/base/common/event.ts#L1127)
at [./base/common/event.ts:1158:8](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/base/common/event.ts#L1158)
at [./base/parts/ipc/common/ipc.net.ts:650:18](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/base/parts/ipc/common/ipc.net.ts#L650)
at [./workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts:376:16](https://github.com/microsoft/vscode/blob/3dea5cbbcb88d7f6dad71148f3d3f98b853ab836/src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts#L376)
```
