### ISSUE TITLE
TextModelPart is disposed!: Error: TextModelPart is disposed!     

### ISSUE THREAD

**Issue by garg10may** [microsoft/vscode#203527]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2
- OS Version: Linux garg10may 6.5.0-14-generic 14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. When I press CTRL + J in the editor window
2. I have vim extension and various manual key binding like \t to open terminal. When I press CTRL + J being in terminal it hides it, but when in editor it does nothing. Using \t key binding I transfer myself to terminal. 
```
32024-01-26 18:20:10.174 [error] TextModelPart is disposed!: Error: TextModelPart is disposed!
    at f.g (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:121:22521)
    at f.getWordAtPosition (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:629:119736)
    at q.getWordAtPosition (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:736:9052)
    at L.h (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:68579)
    at new l (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:68454)
    at new L (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:69323)
    at P (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:69855)
    at T.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:74429)
    at T.E (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:74226)
    at new T (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:70825)
    at q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:75301)
    at o.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:75446)
    at u.y (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at x.setModel (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:744:400)
    at y.setInput (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2148:11654)
    at async y.setInput (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2152:6719)
2024-01-26 18:20:37.550 [error] TextModelPart is disposed!: Error: TextModelPart is disposed!
    at f.g (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:121:22521)
    at f.getWordAtPosition (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:629:119736)
    at q.getWordAtPosition (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:736:9052)
    at L.h (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:68579)
    at new l (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:68454)
    at new L (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:69323)
    at P (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:69855)
    at T.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:74429)
    at T.E (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:74164)
    at o.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:760:70608)
    at u.y (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at x.setModel (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:744:400)
    at y.setInput (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2148:11654)
    at async y.setInput (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2152:6719)

```

**Comment by meganrogge** [comment]
You can run `Developer: Toggle Keyboard Shortcuts Troubleshooting` to figure out what keybindings are happening for you.

**Comment by garg10may** [comment]
```
2024-01-27 14:43:19.975 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
    at /home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:139734
    at _0x1be708 (/home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:152918)
    at ve.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:53055)
2024-01-27 17:18:16.836 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
    at /home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:139734
    at _0x1be708 (/home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:152918)
    at ve.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:53055)
2024-01-27 17:56:47.051 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
    at /home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:139734
    at _0x1be708 (/home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:152918)
    at ve.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:53055)
2024-01-27 17:56:52.742 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2024-01-27 17:56:53.142 [info] Started local extension host with pid 1416552.
2024-01-27 17:56:56.802 [info] [perf] Render performance baseline is 27ms
2024-01-27 18:45:12.581 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
    at /home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:139734
    at _0x1be708 (/home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:152918)
    at ve.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:53055)
2024-01-27 18:51:46.059 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2024-01-27 18:51:46.433 [info] Started local extension host with pid 1511824.
2024-01-27 18:51:50.269 [info] [perf] Render performance baseline is 30ms
2024-01-27 18:52:32.097 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2024-01-27 18:52:32.507 [info] Started local extension host with pid 1513196.
2024-01-27 18:52:36.268 [info] [perf] Render performance baseline is 31ms
2024-01-27 19:03:27.201 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2024-01-27 19:03:27.581 [info] Started local extension host with pid 1532264.
2024-01-27 19:03:31.431 [info] [perf] Render performance baseline is 28ms
2024-01-27 19:20:10.073 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
    at /home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:139734
    at _0x1be708 (/home/garg10may/.vscode/extensions/ms-python.vscode-pylance-2023.12.1/dist/extension.bundle.js:1:152918)
    at ve.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:53055)
2024-01-27 22:08:53.537 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2024-01-27 22:08:53.862 [info] Started local extension host with pid 1851618.
2024-01-27 22:08:57.575 [info] [perf] Render performance baseline is 32ms
2024-01-27 22:13:36.202 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-01-27 22:13:36.203 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-01-27 22:13:36.203 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
2024-01-27 22:13:36.203 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
2024-01-27 22:13:36.204 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-01-27 22:13:36.330 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-01-27 22:13:36.330 [info] [KeybindingService]: | Resolving ctrl+[KeyC]
2024-01-27 22:13:36.331 [info] [KeybindingService]: \ From 7 keybinding entries, matched extension.vim_ctrl+c, when: editorTextFocus && vim.active && vim.overrideCtrlC && vim.use<C-c> && !inDebugRepl, source: user extension vscodevim.vim.
```
