### ISSUE TITLE
Remote SSH error: Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by KeepNaivety3** [microsoft/vscode#203807]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  
- OS Version: 

Copy from about:
```
版本: 1.85.2 (user setup)
提交: 8b3775030ed1a69b13e4f4c628c612102e30a681
日期: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```
Steps to Reproduce:

1. Create a new virtual machine and git pull one of my repositories from GitHub
2. Connect using Remote SSH and open the repository folder

I only have a couple of theme plugins installed on my client, and I still have the problem after disabling the plugins.

- Chinese (Simplified) (简体中文) Language Pack for Visual Studio Code v1.85.2024012409
- GitHub Theme v6.3.4
- IntelliCode v1.2.30 disabled, not install on remote
- IntelliCode API Usage Examples v0.2.8 disabled, not install on remote
- Prettier - Code formatter v10.1.0 disabled, not install on remote
- Remote - SSH v0.107.1
- Remote - SSH: Editing Configuration Files v0.86.0
- Remote Explorer v0.4.1
- vscode-icons v12.7.0
- YAML v1.14.0 disabled, not install on remote

vscode logs:
```
2024-01-30 23:58:26.568 [info] Automatically restarting the remote extension host.
2024-01-30 23:58:26.568 [info] Creating a socket (renderer-ExtensionHost-ffcbcaaa-f947-402a-a080-7d8224e8223b)...
2024-01-30 23:58:26.574 [info] Creating a socket (renderer-ExtensionHost-ffcbcaaa-f947-402a-a080-7d8224e8223b) was successful after 5 ms.
2024-01-30 23:58:28.791 [info] [remote-connection][ExtensionHost][ffcbc…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2024-01-30 23:58:28.791 [error] {"isTrusted":true}
2024-01-30 23:58:28.791 [info] [remote-connection][ExtensionHost][ffcbc…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2024-01-30 23:58:28.791 [info] [remote-connection][ExtensionHost][ffcbc…][reconnect] resolving connection...
2024-01-30 23:58:28.791 [info] [remote-connection][ExtensionHost][ffcbc…][reconnect] connecting to WebSocket(127.0.0.1:51631)...
2024-01-30 23:58:28.791 [info] Creating a socket (renderer-ExtensionHost-ffcbcaaa-f947-402a-a080-7d8224e8223b)...
2024-01-30 23:58:28.812 [info] Creating a socket (renderer-ExtensionHost-ffcbcaaa-f947-402a-a080-7d8224e8223b) was successful after 21 ms.
2024-01-30 23:58:28.817 [info] [remote-connection][ExtensionHost][ffcbc…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2024-01-30 23:58:28.817 [error] {"isTrusted":true}
2024-01-30 23:58:28.817 [error] [remote-connection][ExtensionHost][ffcbc…][reconnect][WebSocket(127.0.0.1:51631)] received error control message when negotiating connection. Error:
2024-01-30 23:58:28.817 [error] Error: Connection error: Unknown reconnection token (seen before)
    at x (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:23227)
    at o.value (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:14812)
    at u.y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14449)
    at b.z (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:17548)
    at o.value (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:16919)
    at u.y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at o.acceptChunk (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:12223)
    at vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:11510
    at o.value (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:4915)
    at u.y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at j.onload (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3306)
2024-01-30 23:58:28.817 [error] [remote-connection][ExtensionHost][ffcbc…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
2024-01-30 23:58:28.818 [error] Error: Connection error: Unknown reconnection token (seen before)
    at x (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:23227)
    at o.value (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:14812)
    at u.y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14449)
    at b.z (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:17548)
    at o.value (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:16919)
    at u.y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at o.acceptChunk (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:12223)
    at vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:11510
    at o.value (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:4915)
    at u.y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at j.onload (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:3306)
2024-01-30 23:58:28.823 [error] Extension host (Remote) terminated unexpectedly with code null.
2024-01-30 23:58:28.823 [error] Extension host (Remote) terminated unexpectedly. The following extensions were running: vscode.emmet, vscode.git-base, vscode.git, vscode.github, vscode.debug-auto-launch, vscode.merge-conflict
2024-01-31 00:00:07.268 [error] There are no commenting ranges at the current position.: Error: There are no commenting ranges at the current position.
    at O.addCommentAtLine (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2063:2555)
    at O.addOrToggleCommentAtLine (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2063:2087)
    at O.Y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2063:1793)
    at o.value (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2062:18489)
    at J.y (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at J.z (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at J.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at J.fire (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:744:19871)
    at Vb.he.onMouseUp (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:744:18171)
    at S.emitMouseUp (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:39512)
    at D.emitMouseUp (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:681:40889)
    at g.F (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:719:14420)
    at vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:719:12058
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/c:/Users/62592/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:714:30685)
```

**Comment by KeepNaivety3** [comment]
This problem disappeared after I completely reinstalled vscode.
I deleted these three folders after uninstalling vscode (these three folders are not deleted on uninstallation, but they contain plugins and configuration files and such) `C:\Users\*****\AppData\Local\Programs\Microsoft VS Code\` `C:\Users\*****\AppData\Roaming\Code\` `C:\Users\*****\.vscode`
After that I deleted `~/.vscode-server/` on the remote server and then I reinstalled vscode and the plugin.
I'm currently using remote ssh with no problems, and I recall that it was probably after installing `GitHub Copilot` during my previous use that I started having problems. Maybe adding an option to completely remove all preferences and cache when uninstalling vscode might help solve the problem?

**Comment by roblourens** [comment]
Sorry for the trouble, thanks for following that up. Good suggestion, will keep that in mind
