### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by BjoernRave** [microsoft/vscode#203992]
Type: <b>Bug</b>

I am not quite sure what causes this problem. It happens every now and then when working in my rather big monorepo. It is using turborepo, trpc across different workspaces inside that repo, maybe that causes the problem, since trpc is doing a lot of TS voodoo (which I believe should also get better in v11, but not sure).

**TypeScript Version:** 5.3.3

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression.
    at ConfiguredProject2.updateGraphWorker (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:177372:11)
    at ConfiguredProject2.updateGraph (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:177231:32)
    at ConfiguredProject2.updateGraph (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:178483:24)
    at updateProjectIfDirty (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:178942:35)
    at Array.forEach (<anonymous>)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:181337:29)
    at /Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:181575:64
    at flatMap (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:2597:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:181575:24)
    at updateOpen (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:182773:29)
    at /Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185375:69
    at IpcIOSession.executeWithRequestId (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185367:14)
    at IpcIOSession.executeCommand (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185375:29)
    at IpcIOSession.onMessage (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185417:51)
    at process.<anonymous> (/Users/bjoernrave/projects/tiqtours-mono/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:186999:14)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:11.933Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (2.36GB free)|
|Process Argv|--crash-reporter-id 4cc76a2b-0da9-4985-b1d7-47f9739eea35|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
biome|bio|2.1.2
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
gitlens|eam|14.7.0
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.156.685
copilot-chat|Git|0.12.2024013003
vscode-github-actions|git|0.26.2
json-to-ts|Mar|1.7.5
template-string-converter|meg|0.6.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
color-highlight|nau|2.5.0
vscode-versionlens|pfl|1.9.2
material-icon-theme|PKi|4.33.0
prisma|Pri|5.9.0
code-spell-checker|str|3.0.1
code-spell-checker-german|str|2.3.1
move-ts|str|1.12.0
pretty-ts-errors|Yoa|0.5.3
material-theme|zhu|3.16.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by mjbvz** [comment]
To help us investigate, please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
