### ISSUE TITLE
Markdown preview not rendering in notebooks

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#204020]
Steps to Reproduce:

1. Create an interactive window
2. Run a markdown cell

```
# %% [markdown]
# # Markdown
```

:bug: invisible cell is added

**Comment by mjbvz** [comment]
I see the following error in the logs:

```notebookWebviewPreloads.js:3 Uncaught (in promise) ReferenceError: t is not defined
    at new he (notebookWebviewPreloads.js:3:29317)
    at Object.g (notebookWebviewPreloads.js:3:26761)
    at Object.ensureMarkupCell (notebookWebviewPreloads.js:3:27088)
    at notebookWebviewPreloads.js:3:17672
```
