### ISSUE TITLE
Error with Continue on Codespace

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#204369]
* I went to https://github.dev/microsoft/monaco-editor/pull/4354
* I undid the changes in `package-lock.json`
* I chose "Continue Working in GitHub Codespaces"
* I chose to save my data with my GitHub account
> <img width="1477" alt="image" src="https://github.com/microsoft/vscode/assets/5047891/76522522-5cd5-421d-96d6-f0a2d36183d7">
* After landing in a CodeSpace I see the following errors
> <img width="1882" alt="image" src="https://github.com/microsoft/vscode/assets/5047891/e83e9863-0b66-4361-9465-585ed12bbcd1">

Errors from dev tools:
```
  ERR Cannot register two commands with the same id: workbench.action.focusCommentsPanel: Error: Cannot register two commands with the same id: workbench.action.focusCommentsPanel
    at h (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:680:19341)
    at y.R (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:2638:151851)
    at y.H (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:2638:146285)
    at l.value (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:2638:146030)
    at h.y (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:87:1902)
    at h.fire (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:87:2119)
    at n.add (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:2109:101906)
    at n.sb (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:2638:143259)
    at n.N (https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:2638:132971)
    at https://assets.github.dev/insider/81725794264e4c0fddbc1b3b728013744ae90840/out/vs/workbench/workbench.web.main.js:2638:133465
```

```
ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a2234333534227d7d/microsoft/monaco-editor/package-lock.json'
    at n.j (VM58 workbench.web.main.js:655:14870)
    at async n.m (VM58 workbench.web.main.js:655:14962)
    at async n.readFileStream (VM58 workbench.web.main.js:655:19328)
    at async r.M (VM58 workbench.web.main.js:2223:42883)
    at async r.readStream (VM58 workbench.web.main.js:2223:42640)
    at async D.Cb (VM58 workbench.web.main.js:2212:61483)
    at async D.resolve (VM58 workbench.web.main.js:2212:59930)
    at async s.W (VM58 workbench.web.main.js:2223:39034)
    at async s.ib (VM58 workbench.web.main.js:1944:41953)
    at async Promise.all (/index 1)
```

**Comment by joyceerhl** [comment]
This has to do with URIs in open editor state not being correctly transformed.
