### ISSUE TITLE
"Cannot read properties of undefined (reading 'includes')"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#204537]
This error came up many times in Insiders, right when the window stopped responding for several seconds. Don't know whether those two things are related but figured it was worth seeing if anyone can doing something with this.

Here's the deminified trace from the errors in the Window log below. I see https://github.com/microsoft/vscode/pull/183271/files near there somewhat recently.

```
at [./workbench/contrib/tasks/common/problemCollectors.ts:444:22](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L444)
at [./base/common/event.ts:1127:12](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L1127)
at [./base/common/event.ts:1158:8](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L1158)
at [./base/common/event.ts:268:15](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L268)
at [./base/common/event.ts:286:13](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L286)
at [./base/common/event.ts:1071:40](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L1071)
at [./base/common/event.ts:1057:63](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L1057)
([./base/common/lifecycle.ts:350:3](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/lifecycle.ts#L350))
at [./base/common/functional.ts:27:15](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/functional.ts#L27)
at [./workbench/contrib/tasks/common/problemCollectors.ts:442:20](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L442)
at [./base/common/event.ts:1127:12](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L1127)
at [./base/common/event.ts:1158:8](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L1158)
at [./base/common/event.ts:268:15](https://github.com/microsoft/vscode/blob/cf7ddbb51d0eaaed6dc25d2df137594254f3b790/src/vs/base/common/event.ts#L268)
```

```
2024-02-06 16:50:00.960 [error] Cannot read properties of undefined (reading 'includes'): TypeError: Cannot read properties of undefined (reading 'includes')
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:29577)
    at o.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at me (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:55893)
    at Object.onWillRemoveListener (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:56047)
    at o.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1327)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1209
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:37:1146
    at Object.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:12:9304)
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:29555)
    at o.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at me (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:55893)
2024-02-06 16:50:00.963 [warning] [perf] Renderer reported VERY LONG TASK (695ms), starting profiling session '6548632c-3586-4e24-8d25-333b10ebc982'
2024-02-06 16:51:43.952 [error] Cannot read properties of undefined (reading 'includes'): TypeError: Cannot read properties of undefined (reading 'includes')
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:29577)
    at o.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at me (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:55893)
    at Object.onWillRemoveListener (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:56047)
    at o.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1327)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1209
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:37:1146
    at Object.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:12:9304)
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:29555)
    at o.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at me (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:55893)
2024-02-06 16:51:43.992 [warning] [perf] Renderer reported VERY LONG TASK (2537ms), starting profiling session '162a37d7-99df-4428-b947-e581bbc5d454'
2024-02-06 16:51:57.611 [error] Cannot read properties of undefined (reading 'includes'): TypeError: Cannot read properties of undefined (reading 'includes')
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:29577)
    at o.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at me (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:55893)
    at Object.onWillRemoveListener (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:56047)
    at o.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1327)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1209
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:37:1146
    at Object.dispose (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:12:9304)
    at h.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1566:29555)
    at o.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at me (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:55893)
```

**Comment by roblourens** [comment]
And I think this happened right after doing some git operations that resulted in about 20 files becoming modified. I don't have any problems at the beginning or end of that but maybe there were some intermediate "problems" from somewhere
