### ISSUE TITLE
Installing smoketest extension times out

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#204771]
Seems to be a regression from https://github.com/microsoft/vscode/pull/204742

```
  1) VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: click '.tabs-container div.tab[title="Extension: vscode-smoketest-check"] div.tab-actions a.action-label.codicon.codicon-close' after 20 seconds.
      at Code.poll (/mnt/vss/_work/1/s/test/automation/out/code.js:202:23)
      at async Code.waitAndClick (/mnt/vss/_work/1/s/test/automation/out/code.js:152:9)
      at async Extensions.closeExtension (/mnt/vss/_work/1/s/test/automation/out/extensions.js:39:9)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:18:13)
```

[Ref](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=256236&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a3fc59e7-8555-5b77-66bd-36e3741aa013)

**Comment by benibenj** [comment]
#204836

**Comment by lramos15** [comment]
This repros again after https://github.com/microsoft/vscode/pull/204871 went in
