### ISSUE TITLE
Cross-compile for ARM fails from x64

### ISSUE THREAD

**Issue by stevedesmond-ca** [Microsoft/vscode#20494]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. `scripts/npm.sh install --arch=arm` from x64 machine
2. `gulp vscode-linux-arm-build-deb`
3. install deb on ARM machine
4. `code --verbose`
```
[27655:0211/221027:INFO:CONSOLE(4)] "Loading "gc-signals" failed", source: file:///usr/share/code/resources/app/out/vs/loader.js (4)
[27655:0211/221027:INFO:CONSOLE(4)] "Detail: ", source: file:///usr/share/code/resources/app/out/vs/loader.js (4)
[27655:0211/221027:INFO:CONSOLE(4)] "Error: /usr/share/code/resources/app/node_modules/gc-signals/build/Release/gcsignals.node: wrong ELF class: ELFCLASS64
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules/gc-signals/src/index.js:8:18)", source: file:///usr/share/code/resources/app/out/vs/loader.js (4)
[27655:0211/221027:INFO:CONSOLE(4)] "Here are the modules that depend on it:", source: file:///usr/share/code/resources/app/out/vs/loader.js (4)
[27655:0211/221027:INFO:CONSOLE(4)] "vs/workbench/api/node/mainThreadHeapService", source: file:///usr/share/code/resources/app/out/vs/loader.js (4)
```
Looks like `gc-signals` is ignoring the `--arch` flag and getting built for x64.

**Comment by stevedesmond-ca** [comment]
I think this is probably just a (lack of) documentation issue -- Microsoft/vscode-wiki#20 should take care of that.

There's also the possibility of automating the steps added to the wiki, which is very similar to how the dotnet repos do it. Let me know if this is worth considering and I can draft up a PR for that!
