### ISSUE TITLE
self-signed certificate in ceritificate chain when installing extension on Remote-SSH

### ISSUE THREAD

**Issue by Hemario** [microsoft/vscode#205071]
Type: <b>Bug</b>

I am running vsCode 1.86.1 and I can no longer install or update extensions installed on my remote host. Downgrading VsCode to 1.85.2 solves this problem.

2024-02-13 09:34:50.161 [info] Started local extension host with pid 3224.
2024-02-13 09:34:50.490 [info] Invoking resolveAuthority(ssh-remote)...
2024-02-13 09:34:50.490 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1ms] obtaining proxy...
2024-02-13 09:34:50.490 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1ms] invoking...
2024-02-13 09:34:51.496 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1006ms] waiting...
2024-02-13 09:34:52.492 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][2003ms] waiting...
2024-02-13 09:34:53.494 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][3004ms] waiting...
2024-02-13 09:34:53.649 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][3160ms] returned Managed(1)
2024-02-13 09:34:53.649 [info] resolveAuthority(ssh-remote) returned 'Managed(1)' after 3160 ms
2024-02-13 09:34:53.650 [info] Creating a socket (renderer-Management-b2e5d471-0752-48e7-b3f9-e76c6f7383ab)...
2024-02-13 09:34:53.650 [info] Creating a socket (renderer-ExtensionHost-6d0bfc11-222a-4c10-9587-42007338efe2)...
2024-02-13 09:34:53.703 [info] Creating a socket (renderer-Management-b2e5d471-0752-48e7-b3f9-e76c6f7383ab) was successful after 53 ms.
2024-02-13 09:34:53.706 [info] Creating a socket (renderer-ExtensionHost-6d0bfc11-222a-4c10-9587-42007338efe2) was successful after 56 ms.
2024-02-13 09:34:55.897 [info] [perf] Render performance baseline is 32ms
2024-02-13 09:35:01.019 [error] self-signed certificate in certificate chain: Failed: self-signed certificate in certificate chain
    at R.B (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:105286)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async R.z (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:102220)
    at async R.getExtensions (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:99271)
    at async _ (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:31003)
    at async te.N (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:31475)
    at async te.J (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:26286)
    at async /home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:24990
    at async Promise.allSettled (index 0)
    at async te.I (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:24937)
    at async te.installGalleryExtensions (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:23386)
    at async te.installFromGallery (/home/AD/$USER/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/out/vs/server/node/server.main.js:169:22669)

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.18.0-477.36.1.el8_8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5625U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.31GB (8.22GB free)|
|Process Argv|--crash-reporter-id 14dda9e0-a7d4-4bc9-b70d-0f0af35c4522|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ds-train|
|OS|Linux x64 4.18.0-477.36.1.el8_8.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (192 x 3700)|
|Memory (System)|3023.51GB (2418.98GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.160.0
copilot-chat|Git|0.12.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
win-ca|uko|3.5.1
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30962250
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
a89i1917:30961429
3ef8e399:30962115
e3gdj431:30958358

```

</details>

**Comment by chrmarti** [comment]
Are you behind a network proxy?

Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by Hemario** [comment]
Hey @chrmarti 

I did what you asked and here is the netlog.json
[netlog.json](https://github.com/microsoft/vscode/files/14278095/netlog.json)

I had downgraded to vscode 1.85.2 (unfortunately github copilot no longer works with that version of vscode) and maneged to install some basic extensions such as python, jupyter, black formatter, ...

However, when upgrading to vscode 1.86.1, all the extensions are no longer installed on the remote and installing them again gives me the above error messages.

**Comment by chrmarti** [comment]
@sandy081 It seems the server-side extension download fails, isn't there a fallback to download on the client? The code related to proxies and certificates has only minimal changes between 1.85 and 1.86, they don't explain the change in behavior here.

**Comment by Hemario** [comment]
I had tried setting: "remote.downloadExtensionsLocally": false in my settings.json, but didn't work either.

**Comment by mbbyn** [comment]
Same here, I noticed that many extensions failed to auto-update after updating VSCode to latest. (WSL 2, corporate proxy setup).

Although, I noticed some extensions are able to update just fine (Github Copilot). I do have win-ca extension installed, which helps trust the corporate proxy certificates automatically. But extensions such as Pylance and docker failed to update with self-signed certificate in chain error.

For now, I download the VISX files and install the extensions manually. That works fine.

**Comment by sandy081** [comment]
> It seems the server-side extension download fails, isn't there a fallback to download on the client? 

Yes there is. There is a fallback on the client to download and install only if server fails to download.

**Comment by Hemario** [comment]
How do I enable this fallback because the fallback doesn't trigger

**Comment by sandy081** [comment]
It triggers only if server fails to download. Please check your window log for more details

- F1 > Open View.. > Window

**Comment by Hemario** [comment]
```
2024-02-27 08:57:20.821 [error] Failed: self-signed certificate in certificate chain
    at R.B (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:105286)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async R.z (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:102220)
    at async R.getExtensions (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:99271)
    at async _ (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:31003)
    at async te.N (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:31475)
    at async te.J (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:26286)
    at async /home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:24990
    at async Promise.allSettled (index 0)
    at async te.I (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:24937)
    at async te.installGalleryExtensions (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:23386)
    at async te.installFromGallery (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:22669)
2024-02-27 08:57:20.844 [error] self-signed certificate in certificate chain: Failed: self-signed certificate in certificate chain
    at R.B (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:105286)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async R.z (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:102220)
    at async R.getExtensions (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:99271)
    at async _ (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:31003)
    at async te.N (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:31475)
    at async te.J (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:26286)
    at async /home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:24990
    at async Promise.allSettled (index 0)
    at async te.I (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:24937)
    at async te.installGalleryExtensions (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:23386)
    at async te.installFromGallery (/home/AD/$USER/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:22669)
```

**Comment by sandy081** [comment]
Can you please enable following setting and re-try?

`remote.downloadExtensionsLocally`

**Comment by Hemario** [comment]
I enabled the setting and started downloading postman.
```
024-02-27 16:15:56.788 [info] Downloading the 'postman.postman-for-vscode' extension locally and install
2024-02-27 16:15:57.010 [info] Downloaded extension: postman.postman-for-vscode /C:/Users/$USER/AppData/Roaming/Code/CachedExtensionVSIXs/postman.postman-for-vscode-0.18.0
```

The file is actually downloaded on my windows pc, however, the icon stays on installing and is hanging for several minutes now.

![image](https://github.com/microsoft/vscode/assets/14911473/b3497836-4bbe-41f2-8411-83ffaad98cac)

**Comment by mbbyn** [comment]
> Can you please enable following setting and re-try?
> 
> `remote.downloadExtensionsLocally`

This worked for my situation, downloaded Pylance and docker updates successfully now, thank you.

**Comment by sandy081** [comment]
> The file is actually downloaded on my windows pc, however, the icon stays on installing and is hanging for several minutes now.

This should upload the downloaded extension to your remote. Are not you seeing this?

**Comment by Hemario** [comment]
> This should upload the downloaded extension to your remote. Are not you seeing this?

No, I'm not seeing this.
```
2024-03-06 13:01:58.326 [info] Downloading the 'ms-toolsai.jupyter' extension locally and install
2024-03-06 13:01:58.542 [info] Downloading the workspace dependencies and packed extensions of 'ms-toolsai.jupyter' locally and install
2024-03-06 13:01:58.666 [info] Downloaded extension: ms-toolsai.jupyter-renderers /C:/Users/$USER/AppData/Roaming/Code/CachedExtensionVSIXs/ms-toolsai.jupyter-renderers-1.0.17
```

Nothing else happens

**Comment by sandy081** [comment]
Can you please enable log level to trace - F1 > Set Log Level... > Trace - and share following logs

F1 > Open View.. > Window
F1 > Open View.. > Server

**Comment by Hemario** [comment]
Window:

```
2024-03-07 14:14:55.803 [info] [perf] Render performance baseline is 34ms
2024-03-07 15:31:46.146 [info] Downloading the 'ms-azuretools.vscode-docker' extension locally and install
2024-03-07 15:31:46.569 [info] Downloaded extension: ms-azuretools.vscode-docker /C:/Users/$USER/AppData/Roaming/Code/CachedExtensionVSIXs/ms-azuretools.vscode-docker-1.29.0
```

Server has no recent logs, only from 1 hour ago:
```
2024-03-07 14:14:53.458 [info] [<unknown>][531a0695][ManagementConnection] New connection established.
2024-03-07 14:14:53.461 [info] [<unknown>][6930a919][ExtensionHostConnection] New connection established.
2024-03-07 14:14:53.471 [info] [<unknown>][6930a919][ExtensionHostConnection] <2046536> Launched Extension Host Process.
2024-03-07 14:19:53.809 [info] [<unknown>][6768d8ec][ExtensionHostConnection] <2043210> Extension Host Process exited with code: 0, signal: null.
```

**Comment by sandy081** [comment]
Looks like there is no activity on the server. What do you see in the extensions view? Can you please paste a screenshot?

**Comment by Hemario** [comment]
I have removed my `.vscode-server` from the remote (in order to start from scratch) and that seemed to have solved my issues.
With `remote.downloadExtensionsLocally` set to True and a clean vscode-server I can now successfully install extensions

Example:
```
2024-03-07 16:43:21.746 [info] Downloading the 'ms-azuretools.vscode-docker' extension locally and install
2024-03-07 16:43:22.271 [info] Downloaded extension: ms-azuretools.vscode-docker /C:/Users/$USER/AppData/Roaming/Code/CachedExtensionVSIXs/ms-azuretools.vscode-docker-1.29.0
2024-03-07 16:43:22.643 [info] Successfully installed 'ms-azuretools.vscode-docker' extension
```
