### ISSUE TITLE
Bug: `ERR Whitespace not found: Error: Whitespace not found`

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#205032]
repro: wip

stacktrace from OSS:
```ts
  ERR Whitespace not found: Error: Whitespace not found
    at NotebookCellsLayout.getWhitespacePosition (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellListView.js:130:23)
    at NotebookCellListView.getWhitespacePosition (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellListView.js:219:42)
    at NotebookViewZones._layoutZone (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewParts/notebookViewZones.js:126:43)
    at NotebookViewZones.layout (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewParts/notebookViewZones.js:92:22)
    at NotebookCellList.updateElementHeight2 (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:1044:28)
    at doLayout (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:1793:28)
    at NotebookEditorWidget.layoutNotebookCell (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:1804:17)
    at UniqueContainer.value (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:1192:26)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:870:26)
    at Emitter._deliverQueue (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:881:22)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:904:22)
    at MarkupCellViewModel.layoutChange (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/markupCellViewModel.js:198:37)
    at MarkupCellViewModel._updateTotalHeight (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/markupCellViewModel.js:152:22)
    at set editorHeight [as editorHeight] (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/markupCellViewModel.js:43:18)
    at MarkupCell.viewUpdateEditing (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/markupCell.js:320:40)
    at MarkupCell.viewUpdate (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/markupCell.js:206:22)
    at UniqueContainer.value (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/markupCell.js:94:26)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:870:26)
    at Emitter._deliverQueue (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:881:22)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:891:22)
    at MarkupCellViewModel.triggerFoldingStateChange (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/markupCellViewModel.js:148:36)
    at vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModelImpl.js:377:26
    at Array.forEach (<anonymous>)
    at NotebookViewModel.updateFoldingRanges (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModelImpl.js:375:29)
    at FoldingController._updateEditorFoldingRanges (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/controller/foldingController.js:75:16)
    at UniqueContainer.value (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/controller/foldingController.js:32:26)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:870:26)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:899:22)
    at FoldingModel.recompute (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/foldingModel.js:207:45)
    at UniqueContainer.value (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/controller/foldingController.js:24:45)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:870:26)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:899:22)
    at UniqueContainer.value (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:173:44)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:870:26)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:899:22)
    at NotebookEventDispatcher.emit (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/eventDispatcher.js:30:52)
    at UniqueContainer.value (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/markupCellViewModel.js:106:50)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:870:26)
    at Emitter._deliverQueue (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:881:22)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:904:22)
    at MarkupCellViewModel.updateEditState (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.js:463:36)
    at NotebookEditorWidget._setMarkupCellEditState (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:2398:22)
    at UniqueContainer.value (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.js:662:49)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:870:26)
    at Emitter.fire (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/base/common/event.js:899:22)
    at vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/webview/browser/webviewElement.js:146:33
    at vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/webview/browser/webviewElement.js:129:54
    at Set.forEach (<anonymous>)
    at _messagePort.onmessage (vscode-file://vscode-app/c:/Users/milively/Documents/_dev_work/vscode/out/vs/workbench/contrib/webview/browser/webviewElement.js:129:35)
```

**Comment by rebornix** [comment]
This should be fixed now.
