### ISSUE TITLE
`resolveCodeLens` invokes `validateRange` on disposed model

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#205289]
Got an error in dev console

```
ERR Model is disposed!: Error: Model is disposed!
    at F.ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:741:263)
    at F.validateRange (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:744:2567)
    at Object.resolveCodeLens (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1640:12619)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

I can try tackling this during debt week

cc @jrieken

**Comment by jrieken** [comment]
> I can try tackling this during debt week

👏 let me know if you need help
