### ISSUE TITLE
Notebook editor broken `Unknown decoration type key: 1-TextEditorDecorationType10`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#205291]
I had a notebook opened (just fine), then did some coding and when coming back to the notebook editor it was totally broken

```
  ERR Error: Unknown decoration type key: 1-TextEditorDecorationType10
    at w.resolveDecorationOptions (abstractCodeEditorService.ts:198:10)
    at h.getOptions (abstractCodeEditorService.ts:410:37)
    at w.resolveDecorationOptions (abstractCodeEditorService.ts:200:19)
    at c (notebookOptions.ts:287:43)
    at Array.forEach (<anonymous>)
    at w.n (notebookOptions.ts:311:48)
    at new w (notebookOptions.ts:200:33)
    at new Fe (notebookEditorWidget.ts:314:54)
    at b.j (instantiationService.ts:119:18)
    at b.createInstance (instantiationService.ts:85:18)
    at b.retrieveWidget (notebookEditorServiceImpl.ts:187:40)
    at b.invokeFunction (instantiationService.ts:68:11)
    at j.setInput (notebookEditor.ts:215:82)
    at g.S (editorPanes.ts:445:21)
    at g.L (editorPanes.ts:270:45)
    at g.openEditor (editorPanes.ts:146:23)
    at editorGroupView.ts:1124:71
    at te.Eb (editorGroupView.ts:1148:4)
    at te.Db (editorGroupView.ts:1106:33)
    at te.openEditor (editorGroupView.ts:1012:15)
    at P.openEditor (editorService.ts:563:16)
    at async Y.sb (anythingQuickAccess.ts:1038:4)
```

<img width="1551" alt="Screenshot 2024-02-15 at 15 30 56" src="https://github.com/microsoft/vscode/assets/1794099/94377cf1-371e-4444-a49a-6f99137c28b6">

**Comment by rebornix** [comment]
It's strange that 

```
this.codeEditorService.listDecorationTypes().forEach(onDidAddDecorationType);

...

const options = this.codeEditorService.resolveDecorationOptions(e, true);
```

throws. With that said, an exception should not break the whole notebook.
