### ISSUE TITLE
Malformed notebook layout

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#205221]
from developer console

This was while debugging the jupyter extension on the latest insiders

![image](https://github.com/microsoft/vscode/assets/2019016/e6bbb4ef-a38a-402c-9daf-6bf2934130f8)

```
ERR Cannot read properties of null (reading 'domNode'): TypeError: Cannot read properties of null (reading 'domNode')
    at T.bb (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:16360)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:14719)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1093:51219)
    at T.updateElementHeight (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:10818)
    at m.updateElementHeight2 (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1644:52122)
    at M.ye [as d] (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:22981)
    at M.execute (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31448)
    at It (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31721)
    at vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31933
log.ts:437   ERR Cannot read properties of null (reading 'domNode'): TypeError: Cannot read properties of null (reading 'domNode')
    at T.bb (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:16360)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:14719)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1093:51219)
    at T.updateElementHeight (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:10818)
    at m.updateElementHeight2 (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1644:52180)
    at M.ye [as d] (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:22981)
    at M.execute (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31448)
    at It (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31721)
    at vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31933
log.ts:437   ERR Cannot read properties of null (reading 'domNode'): TypeError: Cannot read properties of null (reading 'domNode')
    at T.bb (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:16360)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:14719)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1093:51219)
    at T.updateElementHeight (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:10818)
    at m.updateElementHeight2 (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1644:52180)
    at ye (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:22981)
    at Fe.layoutNotebookCell (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:23188)
    at c.value (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:11549)
    at d.y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at d.z (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at d.fire (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at d.fire (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:3317)
    at h.qb (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1640:134023)
    at h.layoutChange (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1640:133933)
    at h.updateOutputHeight (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1640:136678)
    at Fe.Qc (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:33706)
    at c.value (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1846:2046)
    at a.y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at a.fire (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1214:20327
    at vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1214:19983
    at Set.forEach (<anonymous>)
    at F.onmessage (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1214:19971)
log.ts:437   ERR Cannot read properties of null (reading 'domNode'): TypeError: Cannot read properties of null (reading 'domNode')
    at T.bb (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:16360)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:14719)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1093:51219)
    at T.updateElementHeight (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:10818)
    at m.updateElementHeight2 (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1644:52180)
    at M.ye [as d] (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:22981)
    at M.execute (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31448)
    at It (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31721)
    at vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31933
log.ts:437   ERR Cannot read properties of null (reading 'domNode'): TypeError: Cannot read properties of null (reading 'domNode')
    at T.bb (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:16360)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:14719)
    at T.Y (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1093:51219)
    at T.updateElementHeight (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:10818)
    at m.updateElementHeight2 (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1644:52122)
    at M.ye [as d] (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2670:22981)
    at M.execute (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31448)
    at It (vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31721)
    at vscode-file://vscode-app/c:/Users/aamunger/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:148:31933
```

**Comment by amunger** [comment]
repro steps -
1. Open a notebook with several cells and outputs
2. scroll down so that a cell is just above the viewpane (so that it isn't rendered)
3. reload vs code.

:bug: the listview attempts to update a cell DOM node that is not rendered.

**Comment by rebornix** [comment]
This should be fixed via https://github.com/microsoft/vscode/pull/205311
