### ISSUE TITLE
Cannot read properties of undefined (reading 'compileAG')

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#205595]
```javascript
TypeError: Cannot read properties of undefined (reading 'compileAG')
at l in vscode-file://vscode-app//node_modules.asar/vscode-textmate/release/main.js:1:24135
at <anonymous> in vscode-file://vscode-app//node_modules.asar/vscode-textmate/release/main.js:1:20316
at <anonymous> in vscode-file://vscode-app//node_modules.asar/vscode-textmate/release/main.js:1:20852
at y in vscode-file://vscode-app//node_modules.asar/vscode-textmate/release/main.js:1:21653
at Object.c [as _tokenizeString] in vscode-file://vscode-app//node_modules.asar/vscode-textmate/release/main.js:1:20047
at m._tokenize in vscode-file://vscode-app//node_modules.asar/vscode-textmate/release/main.js:1:7377
at m.tokenizeLine2 in vscode-file://vscode-app//node_modules.asar/vscode-textmate/release/main.js:1:6513
at p.tokenizeEncoded in src/vs/workbench/services/textMate/browser/tokenizationSupport/textMateTokenizationSupport.ts:54:40
at T.tokenizeEncoded in src/vs/workbench/services/textMate/browser/tokenizationSupport/tokenizationSupportWithLineLimit.ts:42:23
at o in src/vs/editor/common/model/textModelTokens.ts:427:28
at safeTokenize in src/vs/editor/common/model/textModelTokens.ts:69:14
at u.forceTokenization in src/vs/editor/common/model/tokenizationTextModelPart.ts:568:20
at u.tokenizeIfCheap in src/vs/editor/common/model/tokenizationTextModelPart.ts:582:9
at h.tokenizeIfCheap in src/vs/editor/common/model/tokenizationTextModelPart.ts:154:22
at w in src/vs/workbench/contrib/snippets/browser/commands/surroundWithSnippet.ts:23:21
at i.provideCodeActions in out/vs/workbench/workbench.desktop.main.js:1215:42589
at <anonymous> in src/vs/editor/contrib/codeAction/browser/codeAction.ts:124:47
at Array.map (<anonymous>)
at n in src/vs/editor/contrib/codeAction/browser/codeAction.ts:121:29
at <anonymous> in out/vs/workbench/workbench.desktop.main.js:693:78387
at callback in src/vs/base/common/async.ts:27:19
at i.h in out/vs/workbench/workbench.desktop.main.js:693:76228
at i.trigger in src/vs/editor/contrib/codeAction/browser/codeActionModel.ts:51:8
at <anonymous> in src/vs/editor/contrib/codeAction/browser/codeActionModel.ts:63:9
at runner in src/vs/base/common/async.ts:894:4
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=903b1e9d8990623e3d7da1df3d33db3e42d80eda&bH=89e97546-f7c8-7121-a9f6-e5be71ac3025)

**Comment by aiday-mar** [comment]
Error continues to appear on 1.91. Corresponding issue will be marked as triaged.
