### ISSUE TITLE
TypeError: re.args is not iterable

### ISSUE THREAD

**Issue by davidevertuani** [microsoft/vscode#205830]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows_NT x64 10.0.19045

Duplicate of closed issue #187905.
Unable to launch tasks from the command palette and from keyboard shortcuts; upon triggering of a task, the following log is written to _Output_.
This issue does not occur in Insiders.

Steps to reproduce:
1. From command palette -> _Tasks: Run Task_

_Output_ content for _Window_: 
```
2024-02-21 09:28:23.814 [error] re.args is not iterable: TypeError: re.args is not iterable
    at X (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:74988)
    at Object.ie [as from] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:74331)
    at Object.J [as from] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:84351)
    at Object.te [as from] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:87707)
    at H.f (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1543:57)
    at H.run (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:92351)
    at Object.x [as $a2b] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1543:1128)
    at q.Wc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1956:1239)
    at q.Uc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1956:760)
    at q.Oc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1955:3351)
    at async i.h (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:58691)
    at async vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:58296
```

**Comment by meganrogge** [comment]
This issue does not occur in Insiders.

If it doesn't reproduce in insider's it's been fixed.
