### ISSUE TITLE
Providing a code action for diagnostic which also has quick fix options doesn't work

### ISSUE THREAD

**Issue by tomi** [Microsoft/vscode#2059]
On a JS extension I'm developing using Code version Version 0.10.6 (0.10.6), it is not possible to provide a code action for diagnostic with error code 2304 (cannot find name). The extension code action seems to be rendered first (it can be seen if you're fast), but when quick fix options are available, they are shown instead which hides the extension's code action and this somehow fails to render. It is still possible to choose a quick fix option with keyboard.

## Extension code

```javascript
const fixProvider = {
    provideCodeActions: function(document, range, context, token) {
        return [{ title: "Command", command: "cursorUp" }];
    }
};

function activate(context) {
    const fixer = vscode.languages.registerCodeActionsProvider("javascript", fixProvider);
    context.subscriptions.push(fixer);
}
```

## Test code
```javascript
hello();
```

![code-action](https://cloud.githubusercontent.com/assets/10324676/12372551/4c9c6558-bc65-11e5-9be7-97f44bd95995.gif)

**Comment by jrieken** [comment]
There is an assertion failure happening

```
Assertion failed (item already registered: quickfix_#0): Error: Assertion failed (item already registered: quickfix_#0)
    at Object.ok (file:////Users/jrieken/Code/vscode/out/vs/base/common/assert.js:12:19)
    at ItemRegistry.register (file:////Users/jrieken/Code/vscode/out/vs/base/parts/tree/browser/treeModel.js:84:20)
    at new Item (file:////Users/jrieken/Code/vscode/out/vs/base/parts/tree/browser/treeModel.js:115:27)
    at file:////Users/jrieken/Code/vscode/out/vs/base/parts/tree/browser/treeModel.js:271:54
    at CompletePromise_ctor.CompletePromise_then [as then] (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1826:49)
    at Item.refreshChildren.doRefresh (file:////Users/jrieken/Code/vscode/out/vs/base/parts/tree/browser/treeModel.js:260:40)
    at file:////Users/jrieken/Code/vscode/out/vs/base/parts/tree/browser/treeModel.js:56:26
    at new Promise_ctor (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1901:17)
    at Lock.run (file:////Users/jrieken/Code/vscode/out/vs/base/parts/tree/browser/treeModel.js:51:20)
    at RootItem.Item.refreshChildren (file:////Users/jrieken/Code/vscode/out/vs/base/parts/tree/browser/treeModel.js:296:51)
```

**Comment by jrieken** [comment]
@tomi Thanks for the code sample, helped me a lot

**Comment by dbaeumer** [comment]
Verified that the above example doesn't cause any exception.

**Comment by dbaeumer** [comment]
Quick fix works as well:

![capture](https://cloud.githubusercontent.com/assets/1931590/12676887/9e371298-c695-11e5-9fee-97c8950da73d.png)
