### ISSUE TITLE
Error: Provider copilot already registered

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#206110]
https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/contrib/chat/common/chatServiceImpl.ts#L697:10

```
Deminified Stack
Error: Provider copilot already registered
[at R.registerProvider in src/vs/workbench/contrib/chat/common/chatServiceImpl.ts:697:10](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/contrib/chat/common/chatServiceImpl.ts#L697:10)
[at k.$registerChatProvider in src/vs/workbench/api/browser/mainThreadChat.ts:50:35](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/api/browser/mainThreadChat.ts#L50:35)
[at f.S in src/vs/workbench/services/extensions/common/rpcProtocol.ts:458:17](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L458:17)
[at f.Q in src/vs/workbench/services/extensions/common/rpcProtocol.ts:443:32](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L443:32)
[at f.M in src/vs/workbench/services/extensions/common/rpcProtocol.ts:373:19](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L373:19)
[at f.L in src/vs/workbench/services/extensions/common/rpcProtocol.ts:299:10](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L299:10)
[at l.value in src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L161:42)
[at o.y in src/vs/base/common/event.ts:1127:13](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/base/common/event.ts#L1127:13)
[at o.fire in src/vs/base/common/event.ts:1158:9](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/base/common/event.ts#L1158:9)
[at r.fire in src/vs/base/parts/ipc/common/ipc.net.ts:650:19](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/base/parts/ipc/common/ipc.net.ts#L650:19)
[at j.onmessage in src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts:376:17](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts#L376:17)
```

**Comment by Tyriar** [comment]
This one happens at the same time it seems:

https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/contrib/chat/common/chatProvider.ts#L84:10

```
Deminified Stack
Error: Chat response provider with identifier copilot is already registered.
[at I.registerChatResponseProvider in src/vs/workbench/contrib/chat/common/chatProvider.ts:84:10](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/contrib/chat/common/chatProvider.ts#L84:10)
[at c.$registerProvider in src/vs/workbench/api/browser/mainThreadChatProvider.ts:51:45](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/api/browser/mainThreadChatProvider.ts#L51:45)
[at f.S in src/vs/workbench/services/extensions/common/rpcProtocol.ts:458:17](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L458:17)
[at f.Q in src/vs/workbench/services/extensions/common/rpcProtocol.ts:443:32](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L443:32)
[at f.M in src/vs/workbench/services/extensions/common/rpcProtocol.ts:373:19](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L373:19)
[at f.L in src/vs/workbench/services/extensions/common/rpcProtocol.ts:299:10](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L299:10)
[at l.value in src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L161:42)
[at o.y in src/vs/base/common/event.ts:1127:13](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/base/common/event.ts#L1127:13)
[at o.fire in src/vs/base/common/event.ts:1158:9](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/base/common/event.ts#L1158:9)
[at r.fire in src/vs/base/parts/ipc/common/ipc.net.ts:650:19](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/base/parts/ipc/common/ipc.net.ts#L650:19)
[at j.onmessage in src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts:376:17](https://vscode.dev/github/microsoft/vscode/blob/a0b90ac5e04ea9a0733b68062253a469994e170e/src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts#L376:17)
```

**Comment by roblourens** [comment]
This should be gone now
