### ISSUE TITLE
Hover Does Not Hide

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#206266]
Related: #206023

![Image](https://github.com/microsoft/vscode/assets/2931520/d40a5998-2068-48c5-ada2-3415fe634d17)

```
 ERR Cannot read properties of undefined (reading 'includes'): TypeError: Cannot read properties of undefined (reading 'includes')
    at l.value (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:29574)
    at o.y (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at pe (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:53075)
    at Object.onWillRemoveListener (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:53229)
    at o.x (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1327)
    at vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1209
    at vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:1146
    at Object.dispose (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:12:9461)
    at l.value (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:29552)
    at o.y (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at pe (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:53075)
```

and

```
Uncaught Error: Illegal value for lineNumber
    at U.getLineMaxColumn (textModel.ts:854:10)
    at s.computeSync (markerHoverParticipant.ts:75:27)
    at R.computeSync (contentHover.ts:1092:39)
    at k.C (hoverOperation.ts:147:54)
    at B.a (hoverOperation.ts:67:89)
    at B.h (async.ts:1022:8)
    at B.g (async.ts:1017:9)
```

Version: 1.87.0-insider (user setup)
Commit: 1cc266cc82838981034c2baa637f357a83711d5d
Date: 2024-02-22T22:51:58.796Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by hediet** [comment]
Seems to be fixed.
