### ISSUE TITLE
Build failed: ID > getMac

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#206253]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=258869
Changes: https://github.com/Microsoft/vscode/compare/10ddce6...c6eed5d

```
  1) ID
       getMac:
     Error: Unable to retrieve mac address (unexpected format)
      at $in (out-build/vs/base/node/macAddress.js:30:15)
      at Context.<anonymous> (out-build/vs/base/test/node/id.test.js:23:53)
      at process.processImmediate (node:internal/timers:476:21)
```

**Comment by rzhao271** [comment]
Closing as stale
