### ISSUE TITLE
2024-03-01 16:31:40.812 [error] Error: Invalid debug adapter

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode#206598]
at v.m (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1553:95)
    at v.$acceptDAError (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1552:7629)
    at m.S (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:18889)
    at m.Q (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:18655)
    at m.M (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:17748)
    at m.L (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:16827)
    at o.value (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:15630)
    at u.y (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.fire (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14449)
    at x.onmessage (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:7802)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/196948
