### ISSUE TITLE
 exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode#206677]
2024-03-02 20:02:23.519 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\artist\.vscode\extensions\extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\artist\.vscode\extensions\extensions.json.vsctmp'
    at r.create (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30056)
    at a (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30170)
    at s.fb (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:36175)
    at s.stat (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:28621)
    at async E.stat (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:15732)
    at async Y.tb (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:100:111319)

**Comment by sandy081** [comment]
Can you please share the complete log?

**Comment by AlaricWeb** [comment]
2024-03-08 02:54:19.986 [info] Getting Manifest... vscodevim.vim
2024-03-08 02:54:19.994 [info] Installing extension: vscodevim.vim
2024-03-08 02:54:22.735 [info] Extension signature is verified: vscodevim.vim
2024-03-08 02:54:22.805 [info] Extracted extension to file:///c%3A/Users/artist/.vscode-insiders/extensions/vscodevim.vim-1.27.2: vscodevim.vim
2024-03-08 02:54:22.819 [info] Renamed to c:\Users\artist\.vscode-insiders\extensions\vscodevim.vim-1.27.2
2024-03-08 02:54:22.830 [info] Extracting extension completed. vscodevim.vim
2024-03-08 02:54:22.844 [info] Extension installed successfully: vscodevim.vim
2024-03-08 02:54:22.931 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\artist\.vscode-insiders\extensions\extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\artist\.vscode-insiders\extensions\extensions.json.vsctmp'
    at r.create (c:\dev\VSCode-win32-x64-1.88.0-insider\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30092)
    at a (c:\dev\VSCode-win32-x64-1.88.0-insider\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30207)
    at i.fb (c:\dev\VSCode-win32-x64-1.88.0-insider\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:36633)
    at i.stat (c:\dev\VSCode-win32-x64-1.88.0-insider\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:29079)
    at async v.stat (c:\dev\VSCode-win32-x64-1.88.0-insider\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:16225)
    at async K.sb (c:\dev\VSCode-win32-x64-1.88.0-insider\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:108261)
