### ISSUE TITLE
[Bug] Empty ending bracket in `"surroundingPairs"` results in bad selection range

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#206774]
add a bracket pair to `"surroundingPairs"` under `language-configuration.json`, with the end bracket being empty/blank
```json
"surroundingPairs": [
    [ "(", "" ]
]
```
Make a selection around some text and press `(`
![image](https://github.com/microsoft/vscode/assets/33529441/1f7ef380-a7ec-47b6-aa56-3378ff524b85)

Expected: ✅
resulting selection is still around `text`
![image](https://github.com/microsoft/vscode/assets/33529441/536a8113-169d-4138-857d-df63807e19ac)

Actual: ❌
resulting selection ends up being moved 1 to the left
![image](https://github.com/microsoft/vscode/assets/33529441/b322ebad-cab0-41b8-bafb-f968afc94f7c)

This could have been used as a workaround for https://github.com/microsoft/vscode/issues/202386

**Comment by RedCMD** [comment]
results in console error:
```
log.ts:456   ERR Cannot read properties of undefined (reading 'range'): TypeError: Cannot read properties of undefined (reading 'range')
    at SurroundSelectionCommand.computeCursorState (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/commands/surroundSelectionCommand.js:22:63)
    at vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/cursor/cursor.js:653:55
    at EditStack._computeCursorState (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/model/editStack.js:364:42)
    at EditStack.pushEditOperation (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/model/editStack.js:351:44)
    at TextModel._pushEditOperations (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/model/textModel.js:1055:37)
    at TextModel.pushEditOperations (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/model/textModel.js:977:25)
    at CommandExecutor._innerExecuteCommands (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/cursor/cursor.js:634:41)
    at CommandExecutor.executeCommands (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/cursor/cursor.js:601:29)
    at CursorsController._executeEditOperation (vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/cursor/cursor.js:289:40)
    at vscode-file://vscode-app/e:/repos/vscode/vscode-main/out/vs/editor/common/cursor/cursor.js:458:26
```

**Comment by RedCMD** [comment]
PR https://github.com/microsoft/vscode/pull/240609
