### ISSUE TITLE
Soft Assertion Failed

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#206807]
```javascript
Error: Soft Assertion Failed
at I (out/vs/workbench/workbench.desktop.main.js:12:8979)
at new s (out/vs/workbench/workbench.desktop.main.js:689:52399)
at <anonymous> (out/vs/workbench/workbench.desktop.main.js:689:46379)
at Array.map (<anonymous>)
at P (out/vs/workbench/workbench.desktop.main.js:689:46317)
at <anonymous> (out/vs/workbench/workbench.desktop.main.js:689:49319)
at m (out/vs/workbench/workbench.desktop.main.js:85:14950)
at <anonymous> (out/vs/workbench/workbench.desktop.main.js:689:49314)
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=019f4d1419fbc8219a181fab7892ebccf7ee29a2&bH=acdfb796-56d4-eb6e-79a8-f37f675ab20c)

**Comment by hediet** [comment]
Unreproducable.
