### ISSUE TITLE
SCM progress / VS Code PR Pinger failing, looping forever 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#206851]
1. I pushed to a PR
2. Saw some staged files that had no changes (yet showed up in the SCM view)
3. Hit revert on those 3 files so they'd disappear
4. See the progress bar in the SCM view continuing indefinitely
5. In dev tools, there are these errors that keep on getting logged

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: HttpError: fetch failed (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:59703))
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
j.onmessage @ localProcessExtensionHost.ts:376
console.ts:137 [Extension Host] stack trace: HttpError: fetch failed
    at /Applications/code-insiders-portable-data/extensions/jrieken.vscode-pr-pinger-0.0.6/node_modules/@octokit/request/dist-src/fetch-wrapper.js:96:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Timeout._onTimeout (/Applications/code-insiders-portable-data/extensions/jrieken.vscode-pr-pinger-0.0.6/src/extension.ts:90:24) (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:59703))
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
j.onmessage @ localProcessExtensionHost.ts:376
mainThreadExtensionService.ts:81 [jrieken.vscode-pr-pinger]fetch failed
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
j.onmessage @ localProcessExtensionHost.ts:376
mainThreadExtensionService.ts:82 HttpError: fetch failed
    at /Applications/code-insiders-portable-data/extensions/jrieken.vscode-pr-pinger-0.0.6/node_modules/@octokit/request/dist-src/fetch-wrapper.js:96:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Timeout._onTimeout (/Applications/code-insiders-portable-data/extensions/jrieken.vscode-pr-pinger-0.0.6/src/exten
```
https://github.com/microsoft/vscode/assets/29464607/8268351f-147c-4280-8a35-25317ceb20a6

**Comment by jrieken** [comment]
Not reproducible
