### ISSUE TITLE
Unable to run cells when opening an existing notebook and using pre-selected kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#207126]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  Open workspace folder, create an ipynb file on disc, save this, select a kernel and run a cell
2.  Reload VS Code 
3. The kernel will be automatically selected, 
4. We're unable to run cells, unless you  switch kernels

```
Error: notebook controller is NOT associated to notebook: file:///Users/donjayamanne/demo/sample.ipynb
    at Object.createNotebookCellExecution (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:213939)
    at KernelController.createNotebookCellExecution (/Users/donjayamanne/Development/vsc/vscode-jupyter/src/kernels/kernelController.ts:13:32)
    at Function.create (/Users/donjayamanne/Development/vsc/vscode-jupyter/src/kernels/execution/cellExecutionCreator.ts:152:24)
    at Function.getOrCreate (/Users/donjayamanne/Development/vsc/vscode-jupyter/src/kernels/execution/cellExecutionCreator.ts:121:50)
    at _VSCodeNotebookController.createCellExecutionIfNecessary (/Users/donjayamanne/Development/vsc/vscode-jupyter/src/notebooks/controllers/vscodeNotebookController.ts:515:53)
    at _VSCodeNotebookController.executeCell (/Users/donjayamanne/Development/vsc/vscode-jupyter/src/notebooks/controllers/vscodeNotebookController.ts:534:25)
    a
```

**Comment by DonJayamanne** [comment]
Given the PR has been reverted, this issue can be closed 
Besides the original issue is still open https://github.com/microsoft/vscode/issues/204416
