### ISSUE TITLE
Debug toolbar disappears sometimes (Invalid debug adapter)

### ISSUE THREAD

**Issue by DavidKirn** [microsoft/vscode#207148]
Type: <b>Bug</b>

When debugging my VS Code extension developed in Typscript, the debug toolbar
![grafik](https://github.com/microsoft/vscode/assets/65389717/126df509-cbd4-4380-afe5-9a4018ca6b2f)
sometimes disappears when the debug session is reloaded.
The toolbar only becomes visible again when a breakpoint is triggered.
The current debug session can often be restarted via Run -> Restart Debugging (Ctrl + Shift + F5) but sometimes it is no longer visible in vs code that a debug session is still running.

The following error occurs when the debug toolbar disappears:
```
2024-03-08 10:30:39.683 [error] Invalid debug adapter: Error: Invalid debug adapter
    at h.p (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1877:95)
    at h.$acceptDAError (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1876:15492)
    at g.S (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:13967)
    at g.Q (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:13733)
    at g.M (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:12826)
    at g.L (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:11905)
    at l.value (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:10692)
    at o.y (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:14439)
    at V.onmessage (vscode-file://vscode-app/c:/Users/david/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1632:7759)
```

This error occurs since the update to `1.86`

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.61GB free)|
|Process Argv|--crash-reporter-id e7269b28-84cb-4a8d-af5c-2be2bc08a6d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
path-intellisense|chr|2.8.5
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|2.4.4
EditorConfig|Edi|0.16.4
todo-tree|Gru|0.0.226
svn-scm|joh|2.17.0
vscode-language-pack-de|MS-|1.87.2024030609
remote-wsl|ms-|0.86.0
hexeditor|ms-|1.9.14
material-icon-theme|PKi|4.34.0
vscode-xml|red|0.26.1
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.8.11
svg-preview|Sim|2.8.3
reveal|smu|1.2.7
code-spell-checker|str|3.0.1
es6-string-html|Tob|2.14.1
vscodeintellicode|Vis|1.2.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30981707
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by connor4312** [comment]
Duplicates #203472
