### ISSUE TITLE
[html] support for base url

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#20729]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create an HTML document.
2. Add a `<base>` tag.
3. Add a link with a relative URL.
4. Try to follow the link with CTRL + Click.

```Html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Test</title>
    <meta charset="utf-8">
    <base href="../">
    <link rel="stylesheet" href="folder/file.css">
```

I'm not sure it's really a bug, maybe more a missing feature.

**Comment by Tyriar** [comment]
Given the following following layout:

![image](https://cloud.githubusercontent.com/assets/2193314/23285440/1d56db10-f9e6-11e6-82ce-bdb7d110587a.png)

Where t.html has the following content:

```html
<head>
    <title>Test</title>
    <meta charset="utf-8">
    <base href="../">
    <link rel="stylesheet" href="t2.html">
</head>
```

ctrl+clicking the `t2.html` opens the file but also shows this error message:

![image](https://cloud.githubusercontent.com/assets/2193314/23285469/43eb5c88-f9e6-11e6-9e9c-fd0ec0cdacc9.png)

```
Unable to open 't2.html': File not found (/home/daniel/playground/my-test-project/templates/views/t2.html).: Error: Unable to open 't2.html': File not found (/home/daniel/playground/my-test-project/templates/views/t2.html).
    at Object.g [as create] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:24752)
    at t.doHandleSetInputError (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:18730)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:134:18424
    at Object.v [as _notify] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:11161)
    at Object.enter (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:14666)
    at _run (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15987)
    at _chainedError (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15346)
    at n (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13169)
    at then (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16796)
    at Object.enter (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13238)
```
