### ISSUE TITLE
Unable to download symbols on Macbook: Sending request al/didChangeActiveDocument failed.

### ISSUE THREAD

**Issue by KPSDevelop** [microsoft/vscode#207281]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.1 (Universal)
- OS Version: Sonoma 14.1

Steps to Reproduce:

1. Just purchased a new M3 Macbook Pro yesterday
2. Installed Visual Studio Code and AL extension
3. Open a project cloned from DevOps that works fine on a Windows machine
4. The error message "Sending request al/didChangeActiveDocument failed." immediately appears with the output below

[Error - 11:34:42 AM] AL client: couldn't create connection to server.
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:795:9)
    at transports (/Users/xxxxx/.vscode/extensions/ms-dynamics-smb.al-12.6.936426/dist/webpack:/al/node_modules/vscode-languageclient/lib/node/main.js:426:46)
    at S.connection [as createConnection] (/Users/xxxxx/.vscode/extensions/ms-dynamics-smb.al-12.6.936426/dist/webpack:/al/node_modules/vscode-languageclient/lib/common/client.js:1052:15)
    at S.start (/Users/xxxxx/.vscode/extensions/ms-dynamics-smb.al-12.6.936426/dist/webpack:/al/node_modules/vscode-languageclient/lib/common/client.js:617:19)
[Error - 11:34:42 AM] Sending request al/didChangeActiveDocument failed.
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:795:9)
    at transports (/Users/xxxxx/.vscode/extensions/ms-dynamics-smb.al-12.6.936426/dist/webpack:/al/node_modules/vscode-languageclient/lib/node/main.js:426:46)
    at S.connection [as createConnection] (/Users/xxxxx/.vscode/extensions/ms-dynamics-smb.al-12.6.936426/dist/webpack:/al/node_modules/vscode-languageclient/lib/common/client.js:1052:15)
    at S.start (/Users/xxxxx/.vscode/extensions/ms-dynamics-smb.al-12.6.936426/dist/webpack:/al/node_modules/vscode-languageclient/lib/common/client.js:617:19)

**Comment by KPSDevelop** [comment]
I found the answer here immediately after posting: https://github.com/microsoft/AL/issues/7540
