### ISSUE TITLE
typescript service died

### ISSUE THREAD

**Issue by sfsm565826960** [Microsoft/vscode#20727]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

[Extension Host] typescript (vscode.typescript) uses PROPOSED API which is subject to change and removal without notice
workbench.main.js:133[Extension Host] rejected promise not handled within 1 second
workbench.main.js:138Service died.: Error: Service died.
    at Object.keys.forEach (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:499:45)
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:498:37)
    at ChildProcess.childProcess.on (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:346:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)e.onUnexpectedError @ workbench.main.js:138
Failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/core/vs\workbench\electron-browser\workbench.main.js.map

**Comment by mjbvz** [comment]
Two quick questions: Are you trying to open a folder from a network drive? Do you see any errors/warning messages in VSCode about a missing `typescript/...` file?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. Please try VSCode 1.10 insiders as well which includes a number of important fixes
