### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by oswaldoarana11** [microsoft/vscode#207380]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

**Comment by oswaldoarana11** [comment]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.2.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression.
    at parseVariableDeclarationList (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:35566:15)
    at parseVariableStatement (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:35592:29)
    at parseDeclarationWorker (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:35410:16)
    at parseDeclaration (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:35392:14)
    at parseStatement (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:35345:16)
    at parseListElement (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31985:12)
    at parseList (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31970:19)
    at parseSourceFileWorker (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31016:24)
    at Object.parseSourceFile (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30849:20)
    at createSourceFile (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30684:21)
    at createLanguageServiceSourceFile (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143637:22)
    at acquireOrUpdateDocument (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:134991:26)
    at Object.acquireDocumentWithKey (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:134916:12)
    at getOrCreateSourceFileByPath (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143973:31)
    at Object.getOrCreateSourceFile (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143952:14)
    at /private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143876:42
    at Object.getSourceFileWithCache [as getSourceFile] (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119693:24)
    at findSourceFileWorker (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122097:23)
    at findSourceFile (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122017:20)
    at /private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121966:22
    at getSourceFileFromReferenceWorker (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121935:26)
    at processSourceFile (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121964:5)
    at processRootFile (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121761:5)
    at /private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120508:41
    at forEach (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2352:22)
    at createProgram (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120508:5)
    at synchronizeHostData (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143907:15)
    at Object.getProgram (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143981:5)
    at InferredProject2.updateGraphWorker (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176966:41)
    at InferredProject2.updateGraph (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176817:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179213:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:180832:12)
    at /private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:181062:64
    at flatMap (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2600:17)
    at _ProjectService.applyChangesInOpenFiles (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:181062:24)
    at updateOpen (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182242:29)
    at /private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184838:69
    at IpcIOSession.executeWithRequestId (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184830:14)
    at IpcIOSession.executeCommand (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184838:29)
    at IpcIOSession.onMessage (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184880:51)
    at process.<anonymous> (/private/var/folders/6j/c_n0lwb108q14c4l44zlj96w0000gn/T/AppTranslocation/ECE48800-2C09-4C7D-877F-037E01C95BFC/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:186461:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 8, 5|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id 2a5a5908-df56-42ee-9deb-d8cb80c8bbcb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-es|MS-|1.84.2023111509
playwright|ms-|1.0.22


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by mjbvz** [comment]
Closing as this is an old VS Code version. Please make sure to upgrade to the latest release
