### ISSUE TITLE
Terminal is unusable after suggestions are displayed

### ISSUE THREAD

**Issue by bruno-ribeiro-mck** [microsoft/vscode#207403]
Type: <b>Bug</b>

When using the terminal and performing git operations, after entering the char `-` the suggestions tooltip is displayed and afterwards the terminal no longer accepts any input.

![image](https://github.com/microsoft/vscode/assets/145683618/3111e422-2634-445d-8795-a71f05c8d7ec)

**Exceptions:**
```
simpleSuggestWidget.ts:225 Uncaught TypeError: Cannot read properties of undefined (reading 'items')
    at l.showSuggestions (simpleSuggestWidget.ts:225:46)
    at a.P (terminalSuggestAddon.ts:467:25)
    at terminalSuggestAddon.ts:103:9
    at t.EventEmitter.fire (EventEmitter.ts:55:16)
    at EventEmitter.ts:72:23
    at t.EventEmitter.fire (EventEmitter.ts:55:16)
    at t.CoreService.triggerDataEvent (CoreService.ts:77:18)
    at P._keyPress (Terminal.ts:1155:22)
    at HTMLTextAreaElement.<anonymous> (Terminal.ts:380:100)
showSuggestions	@	simpleSuggestWidget.ts:225
P	@	terminalSuggestAddon.ts:467
(anonymous)	@	terminalSuggestAddon.ts:103
fire	@	EventEmitter.ts:55
(anonymous)	@	EventEmitter.ts:72
fire	@	EventEmitter.ts:55
triggerDataEvent	@	CoreService.ts:77
_keyPress	@	Terminal.ts:1155
(anonymous)	@	Terminal.ts:380

```

 ```
ERR Cannot read properties of undefined (reading 'items'): TypeError: Cannot read properties of undefined (reading 'items')
    at l.showSuggestions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1868:23723)
    at a.P (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1869:6590)
    at a.N (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1869:4819)
    at a.C (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1869:3010)
    at a.z (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1869:2379)
    at t.OscHandler._handler (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1869:2204)
    at t.OscHandler.end (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:255254)
    at t.OscParser.end (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:254573)
    at c.parse (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:252558)
    at k.parse (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:163236)
    at n._action (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:146068)
    at n._innerWrite (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:238374)
    at n.write (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:238097)
    at P.write (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:146198)
    at d.write (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/node_modules.asar/@xterm/xterm/lib/xterm.js:1:287777)
    at Pe.Oc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2852:51221)
    at l.value (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2852:40946)
    at o.y (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.z (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at l.value (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1851:23127)
    at o.y (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at l.value (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1853:4645)
    at o.y (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.z (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at S.handleData (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1144:3107)
    at l.value (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1868:11785)
    at o.y (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at o.y (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at le (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:727)
    at R.t (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:1513)
    at R.s (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:1407)
    at l.value (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:1332)
    at o.y (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.z (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at o.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at MessagePort.he (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:54936)
```

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (16.28GB free)|
|Process Argv|--crash-reporter-id 0ed2dc76-86cb-4e82-89ae-a98b71ec0a3f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.5
copilot|Git|1.172.0
copilot-chat|Git|0.13.0
vscode-github-actions|git|0.26.2
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.29.0
vscode-dotnet-runtime|ms-|2.0.2
vscode-edge-devtools|ms-|2.1.5
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
live-server|ms-|0.4.13
powershell|ms-|2024.0.0
vscode-thunder-client|ran|2.19.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30981707
cppperfcontrol:30979541
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30958157
dsvsc020:30976470

```

</details>

**Comment by meganrogge** [comment]
Looks like you're using some extension which does this, as this is not core VS Code behavior, so pls create an issue for that extension.

**Comment by bruno-ribeiro-mck** [comment]
@meganrogge could you provide a bit more guidance here? I can reproduce with all suggestions disabled

![image](https://github.com/microsoft/vscode/assets/145683618/e57fd1ed-134f-44e7-8c63-6a09fc267c8d)

and the stack trace seems to point to this function which is part of the product

https://github.com/microsoft/vscode/blob/e079f702c0754daf40b29bda45168bec4146614e/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts#L467

**Comment by Tyriar** [comment]
You should turn off the terminal suggest setting, we recently made it more obvious that it's experimental and should show a warning in the upcoming release.
