### ISSUE TITLE
"No Project" reported by TSServer.js. Autocompleting doesn't works.

### ISSUE THREAD

**Issue by TheAifam5** [Microsoft/vscode#20762]
- VSCode Version: 1.9.1
- OS Version: ArchLinux

I tried to restart, reload etc.. Nothings help. I can't say how to reproduce it.

Workspace:
[test.zip](https://github.com/Microsoft/vscode/files/781252/test.zip)

Logs from DevTools:
```
Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:6146:23)
    at IOSession.Session.getFileAndProjectWorker (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:68162:42)
    at IOSession.Session.getFileAndProjectWithoutRefreshingInferredProjects (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:68156:29)
    at IOSession.Session.getCodeFixes (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:68558:31)
    at Session.handlers.ts.createMap._a.(anonymous function) (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:67627:61)
    at IOSession.Session.executeCommand (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:68664:28)
    at IOSession.Session.onMessage (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:68684:35)
    at Interface.<anonymous> (/opt/visual-studio-code/resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:69836:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
```

**Comment by mjbvz** [comment]
Thanks for the report. I'm unable to repo this using the small example project you provided

To help us investigate this, can you please try collecting some logs from the TypeScript server when this occurs. Here's information on to do this using the TSS_LOG environment variable: https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging

From a command prompt, run something like:

```
$ export TSS_LOG="-level verbose -file /PATH_TO_HOME/.tslog"
$ code 
```

Reproduce the problem in VSCode and then share the `.tslog` file.

Let me know if you have any questions about this.

Thanks

**Comment by TheAifam5** [comment]
[tslog.zip](https://github.com/Microsoft/vscode/files/781706/tslog.zip)

**Comment by TheAifam5** [comment]
I can say that when i was starting this example, was everything ok (was fine, completion etc) but at the end when i tried to edit a ``webpack.config.ts`` i got no completion.

Found the problem. I tested everything. Clean project, everything rewrited (but without tsconfig.json) and was ok. I cleaned test project and copied "config.ts", "package.json", "tsconfig.json" and "webpack.config.ts"... and after restart was like before - no autocompletions... I decided to remove "tsconfig.json" and after "Reload Window" autocompletion was ok. Now i decided to copy again "tsconfig.json" to check if really is that a problem .. and yes! "tsconfig.json" makes that problem. Without "tsconfig.json" everything works fine.

I also checked every option which settings make that happened.

Exactly this make that bug:
```
"include": [
    "./src/**/*"
  ]
```
Also when is empty:
```
"include": []
```


But when is set to current directory, works everything fine:
```
"include": [ "." ]
```

Yea. Thats all what i found.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14135

**Comment by mjbvz** [comment]
Thanks @TheAifam5 . I've opened an issue against TypeScript so that they can look into this bug.

**Comment by TheAifam5** [comment]
@mjbvz Thank you.
