### ISSUE TITLE
VSCode compilation error tree_sitter_tsx_external_scanner_create

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#207689]
Does this issue occur when all extensions are disabled?: NA

- VS Code Version: 080f9685c02db0dde126e48c8cb3dac017693e2c (`main` from today)
- OS Version: RHEL 8

Steps to Reproduce:

1. Clone the VSCode repo
2. Run `yarn`
3. Press Ctrl-Shift-B

I get this error

```
[10:00:04] Starting compilation api-proposal-names...
Unhandled Rejection at: Promise Promise {
  <rejected> Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
      at reportUndefinedSymbols (/home/me/workspace/vscode/node_modules/web-tree-sitter/tree-sitter.js:1:19748)
      at postInstantiation (/home/me/workspace/vscode/node_modules/web-tree-sitter/tree-sitter.js:1:17027)
      at /home/me/workspace/vscode/node_modules/web-tree-sitter/tree-sitter.js:1:17752
      at async /home/me/workspace/vscode/node_modules/@vscode/l10n-dev/dist/main.js:329:10
      at async /home/me/workspace/vscode/node_modules/@vscode/l10n-dev/dist/main.js:318:22
} reason: Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
    at reportUndefinedSymbols (/home/me/workspace/vscode/node_modules/web-tree-sitter/tree-sitter.js:1:19748)
    at postInstantiation (/home/me/workspace/vscode/node_modules/web-tree-sitter/tree-sitter.js:1:17027)
    at /home/me/workspace/vscode/node_modules/web-tree-sitter/tree-sitter.js:1:17752
    at async /home/me/workspace/vscode/node_modules/@vscode/l10n-dev/dist/main.js:329:10
    at async /home/me/workspace/vscode/node_modules/@vscode/l10n-dev/dist/main.js:318:22
[10:00:04] The following tasks did not complete: watch-client
[10:00:04] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[deemon] Build daemon exited.
```

This is after `git clean -fxdd`. I'm using Node 18.17.1.

This issue is mentioned [here](https://github.com/microsoft/vscode/issues/166265) but that is closed and I couldn't follow the maze of issues. It doesn't seem to be fixed either way.

**Comment by Timmmm** [comment]
Ah wait... The issue is I was using `fnm` to set my node version and I did `fnm use 18.17.1` in VSCode's terminal, but when you press Ctrl-Shift-B that uses the *default* version, which was 19.something.

I changed the default version to 18.17.1 and then it works.

**Comment by Q1CHENL** [comment]
I still have the exact same issue after switching back to 18.17.1...
