### ISSUE TITLE
Mac integration test fail - TextEdit fail in workspace

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#208336]
```
 1) vscode API - workspace
       workspace.applyEdit drops the TextEdit if there is a RenameFile later #77735 (with opened editor):

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:

true !== false

      + expected - actual

      -true
      +false
      
      at test77735 (extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts:971:11)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts:927:3)
```
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=264110&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=e6d1c856-dd40-5946-2df0-58cb7c21b113

**Comment by bpasero** [comment]
Reopening https://github.com/microsoft/vscode/issues/206356
