### ISSUE TITLE
CodeLens exception when editor input changes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2084]
```
Canceled: Canceled: Canceled: Canceled
    at Object.state_canceling.enter (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1099:25)
    at Promise_ctor.WinJS.Class.define._run (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at Promise_ctor.WinJS.Class.define.cancel (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1239:18)
    at WinJS.Class.derive._cancelAction (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1567:77)
    at Object.state_canceled.enter (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1080:21)
    at WinJS.Class.define._run (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define.cancel (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1239:18)
    at WinJS.Class.derive._cancelAction (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1567:77)
    at Object.state_canceled.enter (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1080:21)
    at WinJS.Class.define._run (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)WorkbenchShell.onUnexpectedError @ shell.js:332(anonymous function) @ shell.js:214ErrorHandler.onUnexpectedError @ errors.js:42onUnexpectedError @ errors.js:56(anonymous function) @ codelens.js:20notifyError @ winjs.base.raw.js:1470state_error_notify.enter @ winjs.base.raw.js:1176WinJS.Class.define._run @ winjs.base.raw.js:1343WinJS.Class.define._error @ winjs.base.raw.js:1316r.handle @ ipcRemoteCom.js:56(anonymous function) @ threadService.js:35(anonymous function) @ threadService.js:148emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:685channel.onread @ internal/child_process.js:440
shell.js:332 Cannot read property 'getLineCount' of null: TypeError: Cannot read property 'getLineCount' of null
    at CodeLensContribution.renderCodeLensSymbols (file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/codelens/browser/codelens.js:395:56)
    at file:////Users/jrieken/Code/vscode/out/vs/editor/contrib/codelens/browser/codelens.js:312:31
    at Object.notifySuccess [as _notify] (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_success_notify.enter (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1127:30)
    at Promise_ctor.WinJS.Class.define._run (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at Promise_ctor.WinJS.Class.define._completed (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1311:18)
    at WinJS.Class.derive.join.argDone (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:2072:37)
    at WinJS.Class.derive.join.keys.forEach.Promise.then.errors.(anonymous function) (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:2097:78)
    at Object.notifySuccess [as _notify] (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_error_notify.enter (file:////Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
```

**Comment by bpasero** [comment]
@jrieken steps?

**Comment by jrieken** [comment]
open twice the same CS file, while things start to load, change on editor to another non CS file. should not throw
