### ISSUE TITLE
Run Without Debugging hangs

### ISSUE THREAD

**Issue by garretsimpson** [microsoft/vscode#208540]
Type: <b>Bug</b>

On Windows 11
- Install VS Code 1.87.2
- Install Node.js 20.11.1
- Create new folder
- Run 'code .'
- Create new file main.js
console.log("Hello, world!");
- Run > Start Debugging
Program works as expected.
- Run > Run Without Debugging
Program hangs.

The debugger controls appear.  Need to press stop twice to close them.
The Run and Debug view shows 1 process running.

Debug console shows:
C:\Program Files\nodejs\node.exe .\main.js

Output > Extension Host shows:
2024-03-24 14:08:53.906 [error] Error: Invalid debug adapter
    at h.p (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1877:95)
    at h.$acceptDAError (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1876:15492)
    at g.S (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:13967)
    at g.Q (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:13733)
    at g.M (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:12826)
    at g.L (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:11905)
    at l.value (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1609:10692)
    at o.y (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:14439)
    at V.onmessage (vscode-file://vscode-app/c:/Users/garre/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1632:7759)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (17.79GB free)|
|Process Argv|--crash-reporter-id 87e5a231-b7b4-4b2a-84fd-07809bcdd327|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30998029
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30993539
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838

```

</details>

**Comment by garretsimpson** [comment]
I tried insiders version 1.88.0.  It has the same behavior.

**Comment by garretsimpson** [comment]
Might be related:
https://stackoverflow.com/questions/78215653/vscode-run-without-debugging-hangs

**Comment by garretsimpson** [comment]
Installed the js-debug-nightly extension, and Run Without Debugging no longer hangs.

JavaScript Debugger (Nightly)
v2024.3.2217

**Comment by connor4312** [comment]
This is fixed in the latest release of VS Code

**Comment by garretsimpson** [comment]
Updated VSC to 1.88.0. Uninstalled debug-nightly.  Enabled JavaScript debugger 1.88.0.  Restarted VSC (required).
Confirmed that Run > Start Debugging and Run > Run Without Debugging both work.
