### ISSUE TITLE
Generating a commit message with Copilot does not work

### ISSUE THREAD

**Issue by jaanli** [microsoft/vscode#208688]
<img width="523" alt="image" src="https://github.com/microsoft/vscode/assets/5317244/5e4e659c-c7d7-4b54-a480-fbdfaff03ae5">

Steps to Reproduce:

1. Install visual studio code with homebrew
2. Make a commit to a repo
3. Click on source control
4. Click on generate a commit message
5. Nothing happens

Any ideas on how to debug this? Thank you!

**Comment by wChenonly** [comment]
I tested that vscode Insiders can work, but vscode stable+ Copilot Chat pre-release. or vscode stable + Copilot Chat can't work.

**Comment by wChenonly** [comment]
You can take a screenshot of the "Github Copilot Chat" channel first，post it and see

**Comment by Starfox64** [comment]
@lszomoru

This seems to happen when one of the following options is disabled in the GitHub settings:
![image](https://github.com/microsoft/vscode/assets/1530720/575dd0fb-d4a1-4c7c-b5f5-65e28f2c99b3)


The response from the API causes a JSON parsing error according to the logs:
```
2024-07-10 11:01:34.961 [info] [ModelMetadataFetcher] Failed to fetch models, SyntaxError: Unexpected token 'u', "unauthoriz"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (/home/starfox64/.vscode-server/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:66:28638)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UA._fetchModels (/home/starfox64/.vscode-server/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:3403)
    at UA.getEmbeddingsModel (/home/starfox64/.vscode-server/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:2685)
    at ZT.getEmbeddingsEndpoint (/home/starfox64/.vscode-server/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:6119)
    at sRe (/home/starfox64/.vscode-server/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1115:1436)
    at Kct (/home/starfox64/.vscode-server/extensions/github.copilot-chat-0.17.2024062801/dist/extension.js:1317:7703)
    at c.n (/home/starfox64/.vscode-server/bin/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/out/vs/workbench/api/node/extensionHostProcess.js:146:6384)
    at c.m (/home/starfox64/.vscode-server/bin/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/out/vs/workbench/api/node/extensionHostProcess.js:146:6347)
    at c.l (/home/starfox64/.vscode-server/bin/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/out/vs/workbench/api/node/extensionHostProcess.js:146:5804)
```

An improvement would be to display a pop up indicating that the feature is disabled in the user's GitHub settings.

**Comment by lramos15** [comment]
A UI piece has been added and will be present in the next release. Thanks for reporting!
