### ISSUE TITLE
Theme: default value for icon theme is "null"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20878]
![image](https://cloud.githubusercontent.com/assets/900690/23100203/23e12a6c-f67b-11e6-9cee-dfa82341fef4.png)

**Comment by bpasero** [comment]
Maybe related?

```
[15654:0219/081155:INFO:CONSOLE(231)] "Cannot read property 'startsWith' of null: TypeError: Cannot read property 'startsWith' of null
    at SettingsDocument.provideLanguageOverridesCompletionItems (/Users/bpasero/Development/Microsoft/monaco/extensions/configuration-editing/out/settingsDocumentHelper.js:146:95)
    at SettingsDocument.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/extensions/configuration-editing/out/settingsDocumentHelper.js:29:21)
    at Object.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/extensions/configuration-editing/out/extension.js:43:76)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:379:85
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:27:24
    at new Promise_ctor (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1641:17)
    at Object.asWinJsPromise (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:26:16)
    at SuggestAdapter.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:379:28)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:726:98
    at ExtHostLanguageFeatures._withAdapter (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:567:20)", source: file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js (231)

```

**Comment by aeschli** [comment]
That's correct, by default the icon theme is `null`, which means no icons.

The error in provideLanguageOverridesCompletionItems is not related. @sandy081 worked on that.

**Comment by bpasero** [comment]
I find it weird that such a technical term leaks into user experience. I am not aware of any other setting that has `null` as default value.

**Comment by aeschli** [comment]
There are 11 other settings that do that. Check out the default settings.
It's just one of the JSON types. `undefined` however is not valid JSON.
Alternative is the empty string or a name like 'No Icons'
