### ISSUE TITLE
unittest don't work

### ISSUE THREAD

**Issue by workhours** [microsoft/vscode#208903]
Type: <b>Bug</b>

I haven't used the testing function for some time. now I just found it's can't work and say 'No tests have been found in this workspace yet' and given 'Configure Python Test' and 'Install Additional Test Extensions', It used to work very well for long time. I can't remember what has beed changed except Python and Python Debugger plugins has been auto-updated.
anyway, I click 'Configure Python Test', then chose 'unit test' then '. Root directory' then '*test.py', finally I got 'Unittet Discovery Error' at side view, and error logs shown as following:

2024-03-27 21:21:41.647 [info] > C:\Python38\python.exe "c:\Users\My Name\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\unittestadapter\discovery.py" --udiscovery -v -s . -p *test.py
2024-03-27 21:21:41.648 [info] cwd: .
2024-03-27 21:21:42.136 [info] Discover tests for workspace name: script - uri: d:\xxx\script
2024-03-27 21:21:42.136 [info] Running discovery for unittest using the new test adapter.
2024-03-27 21:21:42.136 [error] Test discovery already in progress, not starting a new one.
2024-03-27 21:21:44.034 [info] Test server connected to a client.
2024-03-27 21:21:44.042 [error] Unittest test discovery error for workspace:  d:\xxx\script 
 Failed to import test module: cmd-relay.test
Traceback (most recent call last):
  File "C:\Python38\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Python38\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "d:\xxx\script\cmd-relay\test.py", line 1, in <module>
    import cmdclient
ModuleNotFoundError: No module named 'cmdclient'

Failed to import test module: collecting.test
Traceback (most recent call last):
  File "C:\Python38\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Python38\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "d:\xxx\script\collecting\test.py", line 10, in <module>
    df.to_csv(r'xxx/data/tushare/daily/'+dt+'.csv')
  File "C:\Python38\lib\site-packages\pandas\core\generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Python38\lib\site-packages\pandas\io\formats\format.py", line 1186, in to_csv
    csv_formatter.save()
  File "C:\Python38\lib\site-packages\pandas\io\formats\csvs.py", line 240, in save
    with get_handle(
  File "C:\Python38\lib\site-packages\pandas\io\common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "C:\Python38\lib\site-packages\pandas\io\common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'xxx\data\tushare\daily'

2024-03-27 21:21:44.043 [info] Test server connected to a client.
2024-03-27 21:21:44.044 [info] ResultResolver EOT received for discovery.

this message is very confusing and incrediable

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.65GB (50.68GB free)|
|Process Argv|--crash-reporter-id 0f5a028c-3324-4ba1-8c4c-0fa1816b0560|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.62.0
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
compare-folders|mos|0.24.2
autopep8|ms-|2023.8.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-repos|ms-|0.38.0
powershell|ms-|2024.0.0
remote-repositories|ms-|0.40.0
test-adapter-converter|ms-|0.1.9
postcode|roh|1.3.9
partial-diff|ryu|1.4.3
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by eleanorjboyd** [comment]
Hi! Could you give me some more info on your project structure and python path? The error message `"ModuleNotFoundError: No module named 'cmdclient'"` suggests that imports aren't working right in `File "d:\xxx\script\cmd-relay\test.py", line 1` so also sending me that whole file could help- thanks!

**Comment by workhours** [comment]
It's my fault that I have forgotten all my test files must be '*_test.py' suffixed and renamed all of them to '*.test.py' so that...
