### ISSUE TITLE
Build fails due to resource missing (404)

### ISSUE THREAD

**Issue by flagello** [Microsoft/vscode#20907]
- VSCode Version: Master
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. `git clone git@github.com:Microsoft/vscode.git`
2. `cd vscode`
3. `./scripts/npm.sh install`
```
> fsevents@0.3.8 install ~/dir/vscode/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v6.9.5/node-v6.9.5-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (~/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (~/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:954:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "~/.nvm/versions/node/v6.9.5/bin/node" "~/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/dir/vscode/node_modules/fsevents
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> oniguruma@6.1.1 install ~/dir/vscode/node_modules/oniguruma
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v6.9.5/node-v6.9.5-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (~/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (~/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:954:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "~/.nvm/versions/node/v6.9.5/bin/node" "~/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/dir/vscode/node_modules/oniguruma
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```
```
npm ERR! Darwin 16.4.0
npm ERR! argv "~/.nvm/versions/node/v6.9.5/bin/node" "~/.nvm/versions/node/v6.9.5/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
```
`curl -I https://atom.io/download/atom-shell/v6.9.5/node-v6.9.5-headers.tar.gz`
```
HTTP/1.1 302 Found
Server: Cowboy
Connection: keep-alive
Date: Mon, 20 Feb 2017 06:06:46 GMT
Status: 302 Found
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=631152000
Content-Security-Policy: default-src 'self'; connect-src 'self'; font-src https://github-atom-io-herokuapp-com.global.ssl.fastly.net; frame-src 'self' https://www.youtube.com; img-src https://* 'self' https://github-atom-io-herokuapp-com.global.ssl.fastly.net data:; media-src 'none'; object-src 'self' https://github-atom-io-herokuapp-com.global.ssl.fastly.net; script-src 'self' 'unsafe-inline' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com https://github-atom-io-herokuapp-com.global.ssl.fastly.net; style-src 'self' 'unsafe-inline' https://github-atom-io-herokuapp-com.global.ssl.fastly.net;
Location: https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v6.9.5/node-v6.9.5-headers.tar.gz
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 9330fe92-6732-41a3-838f-990b7fcd0447
X-Runtime: 0.017456
X-Rack-Cache: miss
Via: 1.1 vegur
```
`curl -I https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v6.9.5/node-v6.9.5-headers.tar.gz`
```
HTTP/1.1 404 Not Found
x-amz-request-id: A0B099C28B0B2F3E
x-amz-id-2: 90hmcdnkHz+zEhAZECJg/imH/PyVetaNnh2uwHjR7naCJPnXJXrwJSLIo/HplCJxnvdXcEGi5XM=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 20 Feb 2017 06:08:58 GMT
Server: AmazonS3
```

**Comment by joaomoreno** [comment]
Works OK here. Are you behind some proxy?

**Comment by flagello** [comment]
`curl -I https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/index.json`
```
HTTP/1.1 200 OK
x-amz-id-2: uMN5B9sLd2oywcPiFTE1VonUysb3IJKnQin5FoZfLn11vdFC8tJNbvvxjwB1qSdEE7vDZUu1SqY=
x-amz-request-id: 03EAB0DC9DFFCC61
Date: Tue, 21 Feb 2017 15:47:52 GMT
Last-Modified: Tue, 07 Feb 2017 02:23:12 GMT
ETag: "f7fa71ea4ebb449ff62a895fffbd8511"
Accept-Ranges: bytes
Content-Type: application/json
Content-Length: 41483
Server: AmazonS3
```

`curl -I https://gh-contractor-zcbenz.s3.amazonaws.com`
```
HTTP/1.1 200 OK
x-amz-id-2: wRcIVoc6iTh7dZbfMokg08n2dEmyhAuwYNoi8Py/IZGFOzbTU9o2wGnSRaYg/laTYn0Epscjsy0=
x-amz-request-id: 8E44BB2C25337561
Date: Tue, 21 Feb 2017 15:48:35 GMT
x-amz-bucket-region: us-east-1
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3
```

`curl -I https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v6.9.5/node-v6.9.5-headers.tar.gz`
```
HTTP/1.1 404 Not Found
x-amz-request-id: 385A4F84B910D37D
x-amz-id-2: t+JbHYmVYjRF8X+S2wxKPRLyB1SVROGJ1dIcrPDbNbyO0LXHYymI0B+zGH3Zs0DJwJ4E07OJkt0=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Tue, 21 Feb 2017 15:49:45 GMT
Server: AmazonS3
```

<img width="643" alt="screen shot 2017-02-21 at 16 52 35" src="https://cloud.githubusercontent.com/assets/649779/23172494/32429fc8-f856-11e6-86da-9deaf10d8564.png">

I'm not sure what's happening, but `atom-shell/dist/v6.9.5/node-v6.9.5-headers.tar.gz` just doesn't seem to be there.
