### ISSUE TITLE
Cannot Install Jupyter Extension in Remote SSH Server

### ISSUE THREAD

**Issue by kevgong** [microsoft/vscode#209992]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am trying to install the jupyter extension in a remote ssh but every time I get an error that says jupyter cannot be installed because it is not compatible with the current version of VSCode. I have tried installing many different versions of vscode and the jupyter extension (including the pre-release) but keep getting the same error. The jupyter extension installs without an issue on my local machine and other extensions like Python have installed fine on the remote ssh. 

### VS Code Version

1.88.0

### Jupyter Extension Version

v2024.3.0

### Jupyter logs

```shell
2024-04-09 13:37:05.318 [error] Can't install 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code (version 1.88.0).: Incompatible: Can't install 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code (version 1.88.0).
    at x.N (/home/ubuntu/.vscode-server/cli/servers/Stable-5c3e652f63e798a5ac2f31ffd0d863669328dc4c/server/out/vs/server/node/server.main.js:173:32008)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/ubuntu/.vscode-server/cli/servers/Stable-5c3e652f63e798a5ac2f31ffd0d863669328dc4c/server/out/vs/server/node/server.main.js:173:23109
    at async Promise.allSettled (index 0)
    at async x.installGalleryExtensions (/home/ubuntu/.vscode-server/cli/servers/Stable-5c3e652f63e798a5ac2f31ffd0d863669328dc4c/server/out/vs/server/node/server.main.js:173:23033)
    at async x.installFromGallery (/home/ubuntu/.vscode-server/cli/servers/Stable-5c3e652f63e798a5ac2f31ffd0d863669328dc4c/server/out/vs/server/node/server.main.js:173:22584)
```

### Coding Language and Runtime Version

Python v3.9

### Language Extension Version (if applicable)

v2024.4.0

### Running Jupyter locally or remotely?

Remote

**Comment by kevgong** [comment]
I just tried it again today and it worked (not sure what changed).
