### ISSUE TITLE
cmd + k, cmd + k = clear terminal not working

### ISSUE THREAD

**Issue by rirjkl19** [microsoft/vscode#209948]
Type: <b>Bug</b>

When clearing terminal before. I just call `cmd+ k` 2x and it would immediately clear the terminal.

But now it says its not recognized. I've checked my keyboard shortcut bindings and checked but I don't have any keyboard shortcut set or anything. Everything is in default. I've checked the Clear Terminal shortcut key but it says `cmd + k` still.

VS Code version: Code 1.88.0 (Universal) (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:28:18.899Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id cc0b80b0-ae7a-47f5-a1a5-d7d69995e0bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|13.5.0
vscode-apollo|apo|1.20.0
freezed|bla|0.9.6
vscode-intelephense-client|bme|1.10.4
mermaid-markdown-syntax-highlighting|bpr|1.6.0
ccs-flutter-color|cir|1.2.2
vscode-postgres|cko|1.4.3
gitignore|cod|0.9.0
file-tree-to-text-generator|d-k|1.4.0
dart-code|Dar|3.86.0
flutter|Dar|3.86.0
fastcompare|Dav|1.2.1
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|14.9.0
kotlin-formatter|esa|0.0.6
prettier-vscode|esb|10.4.0
bloc|Fel|6.6.6
shell-format|fox|7.2.5
kotlin|fwc|0.2.34
copilot|Git|1.178.0
copilot-chat|Git|0.14.0
vscode-pull-request-github|Git|0.86.1
go|gol|0.41.2
go-nightly|gol|2024.4.807
vscode-graphql|Gra|0.9.3
vscode-graphql-syntax|Gra|1.3.5
todo-tree|Gru|0.0.226
json-to-dart|hir|3.5.8
prettier-sql-vscode|inf|1.6.0
svg|joc|1.5.3
vscode-gutter-preview|kis|0.30.0
Kotlin|mat|1.7.1
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
graphql|mqu|0.1.2
vscode-docker|ms-|1.29.0
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5918
graphql-to-rest-queries|ora|0.0.2
material-icon-theme|PKi|4.34.0
vscode-yaml|red|1.14.0
dart-data-class-tools|ric|0.8.1
preview-vscode|sea|2.3.5
markdown-preview-enhanced|shd|0.8.13
svg-preview|Sim|2.8.3
vscode-graphql|stp|0.3.0
code-spell-checker|str|3.0.1
errorlens|use|3.16.0
dart-frog|Ver|0.2.3
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-mermaid-preview|vst|1.6.3
gitblame|wad|10.10.0
JavaScriptSnippets|xab|1.8.0
inserttimestamp|zvl|1.1.3
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
9c06g630:31013171

```

</details>

**Comment by meganrogge** [comment]
Do you have screen reader mode enabled? When I do, it doesn't work by design. Otherwise, it's working for me. Can you run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`, reproduce the issue, and share the logs?

**Comment by rirjkl19** [comment]
I'm getting a non-stop error 😨 

```
2024-04-09 23:00:54.827 [error] Cannot read properties of undefined (reading 'color'): TypeError: Cannot read properties of undefined (reading 'color')
    at t.default.provideDocumentColors (/Users/matt/.vscode/extensions/circlecodesolution.ccs-flutter-color-1.2.2/dist/extension.js:2:1281)
    at se.provideColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:113994)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:130551
    at Re.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:118853)
    at Re.$provideDocumentColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:130539)
    at h.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5502)
    at h.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5268)
    at h.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:4323)
    at h.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:3440)
    at a.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:2227)
    at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
    at a.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:8018)
    at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:6298)
    at MessagePortMain.emit (node:events:517:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
2024-04-09 23:00:56.860 [error] Cannot read properties of undefined (reading 'color'): TypeError: Cannot read properties of undefined (reading 'color')
    at t.default.provideDocumentColors (/Users/matt/.vscode/extensions/circlecodesolution.ccs-flutter-color-1.2.2/dist/extension.js:2:1281)
    at se.provideColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:113994)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:130551
    at Re.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:118853)
    at Re.$provideDocumentColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:130539)
    at h.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5502)
    at h.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5268)
    at h.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:4323)
    at h.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:3440)
    at a.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:2227)
    at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
    at a.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:8018)
    at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:6298)
    at MessagePortMain.emit (node:events:517:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
2024-04-09 23:00:57.539 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-04-09 23:00:57.540 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-04-09 23:00:57.540 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
2024-04-09 23:00:57.540 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
2024-04-09 23:00:57.540 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-04-09 23:00:57.762 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-04-09 23:00:57.762 [info] [KeybindingService]: | Resolving meta+[KeyA]
2024-04-09 23:00:57.762 [info] [KeybindingService]: \ From 4 keybinding entries, matched editor.action.selectAll, when: no when condition, source: built-in.
2024-04-09 23:00:57.762 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyA, keyCode: 65, key: a
2024-04-09 23:00:57.763 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyA, keyCode: 31 ('A')
2024-04-09 23:00:57.763 [info] [KeybindingService]: | Resolving meta+[KeyA]
2024-04-09 23:00:57.763 [info] [KeybindingService]: \ From 4 keybinding entries, matched editor.action.selectAll, when: no when condition, source: built-in.
2024-04-09 23:00:57.763 [info] [KeybindingService]: + Invoking command editor.action.selectAll.
```

This just kept on logging.

**Comment by meganrogge** [comment]
Try disabling all extensions, looks like that's your issue

**Comment by 15MariamS** [comment]
I'm having the same issue. I uninstalled my extensions and now CMD+K clears the _previous_ terminal content, but it no longer clears the current terminal line.

**Comment by anandncode** [comment]
In my case, the "cmd + k" is assigned to clear terminal.

**keybindings**
```
    {
        "key": "cmd+k",
        "command": "workbench.action.terminal.clear",
        "when": "terminalFocus"
    },
```

I even have below in my User settings
```
  "terminal.integrated.commandsToSkipShell": [
    "-workbench.action.terminal.clear"
  ],
```

Still `cmd + k` waits for the 2nd chord and is not directed to terminal.

Below is the keyboard inspector output on `cmd + k`

```
2024-05-07 15:30:38.426 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-05-07 15:30:38.426 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-05-07 15:30:38.427 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
2024-05-07 15:30:38.428 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
2024-05-07 15:30:38.428 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-05-07 15:30:39.042 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-05-07 15:30:39.042 [info] [KeybindingService]: | Resolving meta+[KeyK]
2024-05-07 15:30:39.043 [info] [KeybindingService]: \ From 106 keybinding entries, awaiting 1 more chord(s), when: no when condition, source: user.
2024-05-07 15:30:39.043 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyK, keyCode: 75, key: k
2024-05-07 15:30:39.043 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyK, keyCode: 41 ('K')
2024-05-07 15:30:39.043 [info] [KeybindingService]: | Resolving meta+[KeyK]
2024-05-07 15:30:39.043 [info] [KeybindingService]: \ From 106 keybinding entries, awaiting 1 more chord(s), when: no when condition, source: user.
2024-05-07 15:30:39.044 [info] [KeybindingService]: + Entering multi-chord mode...
2024-05-07 15:30:39.381 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-05-07 15:30:39.381 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-05-07 15:30:39.382 [info] [KeybindingService]: + Storing single modifier for possible chord meta.
2024-05-07 15:30:39.684 [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```
