### ISSUE TITLE
VSCode Extremely Slow after Upgrading

### ISSUE THREAD

**Issue by SamJbori** [microsoft/vscode#210296]
Type: <b>Performance Issue</b>

VSCode extremely slow and irrespoinsive after Upgrade 

Using VSCode installed on Windows 11 Pro Host and SSH to macOS 14.4.1 VM on vmware workstation 17.5

I tried resetting the extensions, settings, and I went as far as reinstalling everything clean, Windows VMWare, mac, everything.

I am getting this output from the SSH Console

<details><summary>Error Detail</summary>

```
[14:55:15.568] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[14:55:15.568] [server]     at i.ab (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:18984)
[14:55:15.568] [server]     at Timeout._onTimeout (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:18210)
[14:55:15.568] [server]     at listOnTimeout (node:internal/timers:569:17)
[14:55:15.569] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[14:55:15.569] [server] rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
[14:55:15.569] [server] stack trace: CodeExpectedError: Could not find pty on pty host
[14:55:15.569] [server]     at D.U (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
[14:55:15.569] [server]     at D.updateIcon (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27683)
[14:55:15.569] [server] [14:54:50] Error [CodeExpectedError]: Could not find pty on pty host
[14:55:15.569] [server]     at D.U (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
[14:55:15.570] [server]     at D.updateIcon (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27683)
[14:55:15.570] [server]     at j.<computed> (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:22875)
[14:55:15.570] [server]     at t.fire (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:29:882)
[14:55:15.570] [server] rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
[14:55:15.570] [server] stack trace: CodeExpectedError: Could not find pty on pty host
[14:55:15.570] [server]     at D.U (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
[14:55:15.570] [server]     at D.updateTitle (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27632)
[14:55:15.570] [server] [14:54:50] Error [CodeExpectedError]: Could not find pty on pty host
[14:55:15.570] [server]     at D.U (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
[14:55:15.570] [server]     at D.updateTitle (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27632)
[14:55:15.570] [server]     at j.<computed> (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:22875)
[14:55:15.570] [server] rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
[14:55:15.571] [server] stack trace: CodeExpectedError: Could not find pty on pty host
[14:55:15.571] [server]     at D.U (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
[14:55:15.571] [server]     at D.updateTitle (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27632)
[14:55:15.571] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[14:55:15.571] [server]     at i.ab (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:18984)
[14:55:15.571] [server]     at Timeout._onTimeout (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:18210)
[14:55:15.571] [server]     at listOnTimeout (node:internal/timers:569:17)
[14:55:15.571] [server] rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
[14:55:15.571] [server] stack trace: CodeExpectedError: Could not find pty on pty host
[14:55:15.571] [server]     at D.U (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
[14:55:15.571] [server]     at D.updateTitle (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27632)
[14:55:15.572] [server]     at D.updateTitle (/Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27632)
[14:55:15.595] Exec server for ssh-remote+7b22686f73744e616d65223a224d616e436176652e6d61634f53227d created and cached
[14:55:15.598] Opening exec server for ssh-remote+7b22686f73744e616d65223a224d616e436176652e6d61634f53227d
[14:55:15.607] Verified and reusing cached exec server for ssh-remote+7b22686f73744e616d65223a224d616e436176652e6d61634f53227d
[14:59:31.421] [server] New EH opened, aborting shutdown
[14:59:31.421] [server] [14:59:32] New EH opened, aborting shutdown
```
</details>

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.5.0-27-generic
Remote OS version: Darwin x64 23.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|95.46GB (52.30GB free)|
|Process Argv|--crash-reporter-id 9cb48004-b9b3-4f05-a8c8-c3741ada5a69|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: mancaveu.local|
|OS|Linux x64 6.5.0-27-generic|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (12 x 2995)|
|Memory (System)|15.57GB (9.53GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: ManCave.macOS|
|OS|Darwin x64 23.4.0|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (12 x 2856)|
|Memory (System)|16.00GB (8.55GB free)|
|VM|33%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	  6124	code main
    0	    46	  5188	   utility-network-service
    0	    98	  7328	fileWatcher [3]
    0	   151	  9700	extensionHost [2]
    0	    90	 26284	     electron-nodejs (server.js )
    0	    32	 16368	   crashpad-handler
    0	   248	 18112	   gpu-process
    0	   103	 21116	window [5] (Issue Reporter)
    0	   199	 22580	window [2] (Welcome - test [SSH: mancaveu.local] - Visual Studio Code)
    0	   203	 23736	window [3] (Welcome - Visual Studio Code)
    0	   158	 26816	extensionHost [3]
    0	    92	 25716	     electron-nodejs (server.js )
    0	    96	 28488	fileWatcher [2]
    0	   109	 28564	shared-process
    0	    95	 30104	ptyHost
    0	     8	 18092	     conpty-agent
    0	     4	 24812	     C:\Windows\System32\cmd.exe /c (type "C:\Users\SamJb\AppData\Local\Temp\vscode-linux-multi-line-command-mancaveu.local-95818347.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 59219 "mancaveu.local" bash) & exit /b 0
    0	     9	 26076	       "C:\Windows\System32\OpenSSH\ssh.exe"  -T -D 59219 "mancaveu.local" bash
    0	     8	 26800	     conpty-agent
    0	     4	 26904	     C:\Windows\System32\cmd.exe /c (type "C:\Users\SamJb\AppData\Local\Temp\vscode-linux-multi-line-command--an-ave.mac---929720930.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 59528 "ManCave.macOS" bash) & exit /b 0
    0	     9	  1532	       "C:\Windows\System32\OpenSSH\ssh.exe"  -T -D 59528 "ManCave.macOS" bash
    0	     8	 29940	     conpty-agent
    0	     4	 30100	     C:\Windows\System32\cmd.exe /c (type "C:\Users\SamJb\AppData\Local\Temp\vscode-linux-multi-line-command--an-ave.mac---269901256.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 59528 "ManCave.macOS" bash) & exit /b 0
    0	     9	 25528	       "C:\Windows\System32\OpenSSH\ssh.exe"  -T -D 59528 "ManCave.macOS" bash

Remote: SSH: mancaveu.local
CPU %	Mem MB	   PID	Process
    0	     0	 16829	remote agent
    0	     0	 17058	   ptyHost
    0	     0	 17762	     /bin/bash --init-file /home/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 26267	       npm exec expo run android
    0	     0	 26278	         sh -c expo run android
    0	     0	 26279	           node /home/wj/Projects/test/node_modules/.bin/expo run android
    0	     0	 28268	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 28269	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 28270	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 28281	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 28287	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 28293	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 28301	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 28308	             /home/wj/.nvm/versions/node/v20.12.2/bin/node /home/wj/Projects/test/node_modules/jest-worker/build/workers/processChild.js
    0	     0	 17410	   extension-host
    0	     0	 17727	     /home/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/node /home/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=17410
    0	     0	 17421	   fileWatcher
    0	     0	 28597	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 28598	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Remote: SSH: ManCave.macOS
CPU %	Mem MB	   PID	Process
    0	     0	   841	remote agent
    0	     0	   845	   extension-host
    0	     0	   934	     /Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/node /Users/wj/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=845
    0	     0	   846	   ptyHost
    0	     0	   931	     /bin/zsh --login
    0	     0	   994	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: mancaveu.local|    Folder (test): 2112 files|      File types: so(552) xml(138) flat(138) json(133) class(78) bin(71)
|                  png(65) js(49) len(36) jar(23)
|      Conf files: package.json(1) tsconfig.json(1)
|  Remote: SSH: ManCave.macOS;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
easy-snippet|inu|0.7.5
vscode-edge-devtools|ms-|2.1.5
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
f3je6385:31013174

```

</details>

**Comment by Zhangyanbo** [comment]
I have the same experiment even without SSH. Compare to using SSH, it just happen slower, but still need to restart VSCode to fix.

**Comment by KirstinHadler** [comment]
I get the notice "Remote Extension host terminated unexpectedly 3 times within the last 5 minutes." all the time and the extensions don't work properly. Also the search engine is very slow an doesn't get all locations. Downgrade to 1.87.2 solved the problem for now.

**Comment by KirstinHadler** [comment]
I just tried version 1.89 but the issue with the terminated remote extension still exists.

**Comment by torext** [comment]
Having the same continuous `CodeExpectedError: Could not find pty on pty host`error in my `Remote - SSH` console output. Running VSCode 1.89.0 and `Remote - SSH` extension `v0.110.1`.

**Comment by vqt123** [comment]
worked for me

![image](https://github.com/microsoft/vscode/assets/3741649/70d4cc0c-7903-4028-b64a-d51f12e96583)

**Comment by rzhao271** [comment]
Hi all, I saw this issue just now. Are these remote/server problems still occurring on VS Code 1.96 or later?
