### ISSUE TITLE
no commenting ranges error

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#210478]
1. open output channel in OSS with dev tools open
2. select some content
3. 🐛 see error thrown about commenting ranges

I'm not sure which of these steps are necessary to reproduce.

```
  ERR There are no commenting ranges at the current position.: Error: There are no commenting ranges at the current position.
    at CommentController.addCommentAtLine (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/workbench/contrib/comments/browser/commentsController.js:955:27)
    at CommentController.addOrToggleCommentAtLine (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/workbench/contrib/comments/browser/commentsController.js:927:26)
    at CommentController.onEditorMouseUp (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/workbench/contrib/comments/browser/commentsController.js:910:22)
    at UniqueContainer.value (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/workbench/contrib/comments/browser/commentsController.js:697:69)
    at InteractionEmitter._deliver (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/base/common/event.js:889:26)
    at InteractionEmitter._deliverQueue (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/base/common/event.js:900:22)
    at InteractionEmitter.fire (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/base/common/event.js:923:22)
    at InteractionEmitter.fire (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/editor/browser/widget/codeEditor/codeEditorWidget.js:1490:19)
    at viewUserInputEvents.onMouseUp (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/editor/browser/widget/codeEditor/codeEditorWidget.js:1358:68)
    at ViewUserInputEvents.emitMouseUp (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/editor/browser/view/viewUserInputEvents.js:43:29)
    at ViewController.emitMouseUp (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/editor/browser/view/viewController.js:251:34)
    at TouchHandler._onMouseUp (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/editor/browser/controller/mouseHandler.js:199:33)
    at vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/editor/browser/controller/mouseHandler.js:39:91
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Users/meganrogge/Repos/vscode/vscode/out/vs/editor/browser/editorDom.js:116:17)
```

<img width="1786" alt="Screenshot 2024-04-16 at 8 46 26 AM" src="https://github.com/microsoft/vscode/assets/29464607/3e687aa5-22b2-41c9-97af-8ba12cac8b6e">

**Comment by meganrogge** [comment]
This was the first time I saw the error. Feel free to close if cannot reproduce and I'll reopen if I see it again.
