### ISSUE TITLE
Cannot Find Module when extension is installed from Extension Marketplace

### ISSUE THREAD

**Issue by Thecmar7** [Microsoft/vscode#21043]
Our extension is acting different from the visual studio code extension Marketplace installation than from the development environment.

- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Download extension [https://marketplace.visualstudio.com/items?itemName=postal-team.postal](https://marketplace.visualstudio.com/items?itemName=postal-team.postal) it doesn't work.
2. Running git version [https://github.com/slichlyter12/Postal/tree/master/postal](https://github.com/slichlyter12/Postal/tree/master/postal) it does work. 

Running the installed version developer tools show: 

```
[Extension Host] Here is the error stack:  Error: Cannot find module 'find'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.V.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:30928)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user_name/.vscode/extensions/postal-team.postal-0.1.1/out/src/controller.js:7:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

The issue is happening when we try to use the 'find' module: 

``` 
var finder = require('find');
```

Our package.json dependencies:

```
    "dependencies": {
        "app": "^0.1.0",
        "find": "0.2.7",
        "browser-window": "^0.4.0",
        "child_process": "^1.0.2",
        "electron": "^1.4.14",
        "file-system": "^2.2.1",
        "open": "0.0.5",
        "vis": "^4.17.0"
    },
```

We are thinking it has something to do with the prepublish and compiling. Our prepublishing and compiling script is as follows:

```
    "scripts": {
        "vscode:prepublish": "tsc -p ./;",
        "compile": "tsc -watch -p ./",
        "postinstall": "node ./node_modules/vscode/bin/install;"
    },
```

**Comment by Thecmar7** [comment]
We figured it out we had to run `npm install` in the `lib/apps` folder within the extension.
