### ISSUE TITLE
terminal disapper when code a folder from wsl

### ISSUE THREAD

**Issue by game1991** [microsoft/vscode#210587]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
![image](https://github.com/microsoft/vscode/assets/31313896/4e09f6bf-845c-4837-8bc6-83a04deda8a4)

- OS Version:  
This is my wsl info:
$uname -a
Linux Game 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

Steps to Reproduce:

1. use vscode extension wsl connet to wsl2 centos7
2.  open terminal exec command `code folder` then this integrated terminal opening and disappear soon
3. The issue is steadily reproduced when opening a folder with git repository items, and the built-in terminal crashes

here my code log trace ~hope can help you find some question.

[2024-04-18-011633.txt](https://github.com/microsoft/vscode/files/15015383/2024-04-18-011633.txt)

**Comment by Tyriar** [comment]
This is all I can glean from the log:

```
2024-04-18 01:16:34.146 [trace] TerminalProcess#_queueProcessExit 
    at i.X (/root/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/out/vs/platform/terminal/node/ptyHostMain.js:47:18314)
    at /root/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/out/vs/platform/terminal/node/ptyHostMain.js:47:18092
    at EventEmitter2.fire (/root/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node_modules/node-pty/lib/eventEmitter2.js:41:22)
    at PipeSocket.<anonymous> (/root/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node_modules/node-pty/lib/terminal.js:93:76)
    at PipeSocket.emit (node:events:517:28)
    at Terminal.emit (/root/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node_modules/node-pty/lib/terminal.js:155:34)
    at onexit (/root/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node_modules/node-pty/lib/unixTerminal.js:102:19)
```

This means that the pty was shut down outside of VS Code:

https://github.com/microsoft/node-pty/blob/df1ae8c08a2fd3d4fe9c1e1a304cbe6e9ed41a3f/src/unixTerminal.ts#L115

@deepak1556 might know how to diagnose further but this is beyond my knowledge.

**Comment by game1991** [comment]
I recorded a gif demo of a terminal crash when a folder opened by code exists in a .git repository

This question is inevitable, and I hope it can help you find a way to solve it

![2024-04-18-22-56-10-ezgif com-resize](https://github.com/microsoft/vscode/assets/31313896/852d3573-7a65-4780-b5e6-a487416cfb5e)
