### ISSUE TITLE
Crash when debugging 'hello world' extension

### ISSUE THREAD

**Issue by bhainesva** [microsoft/vscode#210633]
Type: <b>Bug</b>

Steps to Reproduce:

1. Create a hello world extension using `npx --package yo --package generator-code -- yo code` and following the instructions from [Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension).
2. Run `Debug: Start Debugging` from the Command Palette.
3. Use the Command Palette in the debug window to run the exposed hello world command, this works as expected. 
4. Make a change to the extension code and reload the debug window with ⌘+r. 
5. Try to run the hello world command again through the command palette. This generally doesn't work, and after some time produces a popup saying `"Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue."`. Waiting and trying to reload again will sometimes work.
6. Continue trying to reload / execute the command, after a variable number of iterations the application crashes. 

Here are some videos demonstrating the crash. Sometimes there's an error message (cases 1 and 3) and sometimes the windows just close (cases 2 and 4). I don't have any extensions enabled, and these cases were all after doing a clean reinstall.
1. https://www.youtube.com/watch?v=FiWsu-AGlAI
2. https://www.youtube.com/watch?v=6Pl3ooR2rio
3. https://www.youtube.com/watch?v=LN24GaVdI9w
4. https://www.youtube.com/watch?v=meeT8k4_MDU

I've attempted to use the trace option in my `launch.json` configuration, but the files produced seem to be invalid. 
* Crash 3 - 
[vscode-debugadapter-7e311c66.json.gz](https://github.com/microsoft/vscode/files/15021855/vscode-debugadapter-7e311c66.json.gz)
* Crash 4 - 
[vscode-debugadapter-981551ba.json.gz](https://github.com/microsoft/vscode/files/15021859/vscode-debugadapter-981551ba.json.gz)

Similarly, I've tried using the `--crash-reporter-directory` flag, but after the crash the target directory only contains a `settings.dat` file and `pending`, `new`, `completed`, and `attachments` directories which are all empty. 

I did find one .dmp in `~/Library/Application Support/Code/Crashpad/completed` which I'll add here, but based on the edit time on the file, I think it was a separate instance than the four examples above: 
[abdac44c-b184-4b2a-9ed7-9b6d9d4839d0.dmp](https://github.com/microsoft/vscode/files/15021903/abdac44c-b184-4b2a-9ed7-9b6d9d4839d0.dmp)

I've zipped the contents of the `~/Library/Application Support/Code/logs` directories that appeared to be associated with crashes 3 and 4 in case that's helpful, but let me know if there's anything else I can provide. 
* Crash 3 logs - 
[20240418T024714.zip](https://github.com/microsoft/vscode/files/15021999/20240418T024714.zip)

* Crash 4 logs - 
[20240418T030231.zip](https://github.com/microsoft/vscode/files/15021922/20240418T030231.zip)

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin x64 21.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (7.65GB free)|
|Process Argv|--crash-reporter-id 935accc3-e091-4b15-9719-23bd29faaf4e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
da93g388:31013173

```

</details>

**Comment by bhainesva** [comment]
Trying to investigate some, I've run the dev version of vscode and the issue is still present at the tip of main (b847d7d55e9eb4b0d67462d01c6210196a3e0b43). I tried to use the chrome dev tools but it crashes before any exceptions trigger the debugger. 

Here are the logs after the crash for two different cases I've seen. I don't know if these represent two different underlying issues. 

I also noticed recent activity on [this other issue](https://github.com/microsoft/vscode/issues/186540) that deals with a code 15 crash, I don't know if it's potentially related. It's presumably not the exact same issue because I can reproduce my crash on a commit after the fix for that one was merged.

### Crash with no notification
This one I had the debugger breaking on all exceptions in both windows, which may have contributed to some of the 'unresponsive' logs. I've tried to understand why it was killed but it doesn't seem to be using an unusual amount of memory and I don't see any logs in `/var/logs` or dmesg.
 
<details><summary>Logs</summary>
<pre>
...
    at Emitter._deliver (vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/base/common/event.js:918:22)
    at BufferedEmitter.fire (vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/base/parts/ipc/common/ipc.net.js:484:35)
    at port.onmessage (vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js:270:39)", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (245)
[33089:0419/231019.241212:INFO:CONSOLE(178)] "%c[Extension Host] %cdebugger inspector at devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1 color: blue color:", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (178)
[33089:0419/231020.125006:INFO:CONSOLE(187)] "Extension Host", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (187)
[33089:0419/231020.125151:INFO:CONSOLE(188)] "%cDebugger attached.
 color: red", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (188)
[33089:0419/231020.125225:INFO:CONSOLE(189)] "console.groupEnd", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (189)
[33089:0419/231022.899231:INFO:CONSOLE(104)] "%c[Extension Host] %cCongratulations, your extension "helloworld" is now active! %c(at console.<anonymous> (/Users/bhaines/repo/vscode/out/vs/workbench/api/common/extHostConsoleForwarder.js:45:26)) color: blue color:  color: grey", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/base/common/console.js (104)
[main 2024-04-20T03:10:59.405Z] Extension host with pid 50610 exited with code: 0, signal: unknown.
[33089:0419/231104.765160:INFO:CONSOLE(225)] "%c INFO color: #33f Extension host (LocalProcess pid: 33206) is unresponsive.", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
[33089:0419/231105.138138:INFO:CONSOLE(187)] "Extension Host", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (187)
[33089:0419/231105.138246:INFO:CONSOLE(188)] "%cDebugger attached.
 color: red", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (188)
[33089:0419/231105.138316:INFO:CONSOLE(189)] "console.groupEnd", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (189)
[33089:0419/231115.996844:INFO:CONSOLE(244)] "%c[Extension Host] %cSTOPPED on first line for debugging on port 53310 color: blue color:", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (244)
(node:33089) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 child-process-gone listeners added to [App]. Use emitter.setMaxListeners() to increase limit
(Use `Electron --trace-warnings ...` to show where the warning was created)
[33089:0419/231116.022650:INFO:CONSOLE(225)] "%c INFO color: #33f Started local extension host with pid 55579.", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
[33089:0419/231127.093585:INFO:CONSOLE(178)] "%c[Extension Host] %cdebugger inspector at devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1 color: blue color:", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (178)
[33089:0419/231127.097445:INFO:CONSOLE(245)] "%c  ERR color: #f33 [LocalProcessExtensionHost]: Extension host did not start in 10 seconds (debugBrk: true)", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (245)
[33089:0419/231127.628430:INFO:CONSOLE(225)] "%c INFO color: #33f Loading development extension at /Users/bhaines/repo/helloworld", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
[33089:0419/231130.060441:INFO:CONSOLE(235)] "%c WARN color: #993 Creation of workbench contribution 'SCMActiveRepositoryContextKeyController' took 144ms.", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (235)
[33089:0419/231136.206901:INFO:CONSOLE(225)] "%c INFO color: #33f [perf] Render performance baseline is 30ms", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
zsh: killed     ./scripts/code.sh
</pre>
</details> 

### Crash with `The window terminated unexpectedly (reason: 'killed', code: '15')` alert

<details><summary>Logs</summary>
<pre>
...
[67667:0419/232919.237198:INFO:CONSOLE(225)] "%c INFO color: #33f Loading development extension at /Users/bhaines/repo/helloworld", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
[67667:0419/232924.313510:INFO:CONSOLE(225)] "%c INFO color: #33f [perf] Render performance baseline is 29ms", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
[67667:0419/232928.873311:INFO:CONSOLE(245)] "%c  ERR color: #f33 [LocalProcessExtensionHost]: Extension host did not start in 10 seconds (debugBrk: true)", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (245)
[main 2024-04-20T03:29:33.789Z] Extension host with pid 73588 exited with code: 0, signal: unknown.
[main 2024-04-20T03:29:33.790Z] [UtilityProcess id: 4, type: extensionHost, pid: 73588]: crashed with code 15 and reason 'killed'
[main 2024-04-20T03:29:33.793Z] [UtilityProcess id: 2, type: fileWatcher, pid: 73582]: crashed with code 15 and reason 'killed'
[main 2024-04-20T03:29:33.796Z] ptyHost terminated unexpectedly with code 15
[main 2024-04-20T03:29:33.796Z] [UtilityProcess type: ptyHost, pid: 67783]: unable to kill the process
Renderer process killed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[main 2024-04-20T03:29:33.803Z] CodeWindow: renderer process gone (reason: killed, code: 15)
[main 2024-04-20T03:29:34.132Z] [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown
[main 2024-04-20T03:29:34.132Z] [UtilityProcess id: 1, type: fileWatcher, pid: 67782]: crashed with code 15 and reason 'killed'
[main 2024-04-20T03:29:34.133Z] [UtilityProcess type: shared-process, pid: 67781]: crashed with code 15 and reason 'killed'
[main 2024-04-20T03:29:34.134Z] Extension host with pid 67780 exited with code: 15, signal: unknown.
[main 2024-04-20T03:29:34.134Z] [UtilityProcess id: 1, type: extensionHost, pid: 67780]: crashed with code 15 and reason 'killed'
[67667:0419/232934.138487:INFO:CONSOLE(245)] "%c  ERR color: #f33 [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (245)
[67667:0419/232934.139506:INFO:CONSOLE(245)] "%c  ERR color: #f33 [File Watcher (universal)] restarting watcher after error: terminated by itself unexpectedly with code 15, signal: unknown (ETERM)", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (245)
[67667:0419/232934.141926:INFO:CONSOLE(640)] "Extension host (LocalProcess pid: 67780) terminated unexpectedly. Code: 15, Signal: unknown", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js (640)
[67667:0419/232934.194752:INFO:CONSOLE(245)] "%c  ERR color: #f33 Extension host (LocalProcess pid: 67780) terminated unexpectedly. No extensions were activated.", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (245)
[67667:0419/232934.195186:INFO:CONSOLE(225)] "%c INFO color: #33f Automatically restarting the extension host.", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:83005)
    at _.send (node:electron/js2c/browser_init:2:69166)
    at CodeWindow.send (/Users/bhaines/repo/vscode/out/vs/platform/windows/electron-main/windowImpl.js:1063:43)
    at CodeWindow.sendWhenReady (/Users/bhaines/repo/vscode/out/vs/platform/windows/electron-main/windowImpl.js:1046:22)
    at WindowsMainService.sendToFocused (/Users/bhaines/repo/vscode/out/vs/platform/windows/electron-main/windowsMainService.js:1238:28)
    at CodeApplication.onUnexpectedError (/Users/bhaines/repo/vscode/out/vs/code/electron-main/app.js:356:42)
    at ErrorHandler.unexpectedErrorHandler (/Users/bhaines/repo/vscode/out/vs/code/electron-main/app.js:195:67)
    at ErrorHandler.onUnexpectedError (/Users/bhaines/repo/vscode/out/vs/base/common/errors.js:56:18)
    at onUnexpectedError (/Users/bhaines/repo/vscode/out/vs/base/common/errors.js:86:34)
    at process.<anonymous> (/Users/bhaines/repo/vscode/out/vs/code/electron-main/app.js:198:52)
    at process.emit (node:events:529:35)
    at process._fatalException (node:internal/process/execution:158:25)
[main 2024-04-20T03:29:34.336Z] [uncaught exception in main]: Error: Render frame was disposed before WebFrameMain could be accessed
[main 2024-04-20T03:29:34.336Z] Error: Render frame was disposed before WebFrameMain could be accessed
    at isAllowedVsCodeFileRequest (/Users/bhaines/repo/vscode/out/vs/code/electron-main/app.js:92:74)
    at Function.<anonymous> (/Users/bhaines/repo/vscode/out/vs/code/electron-main/app.js:125:26)
[67667:0419/232934.346971:INFO:CONSOLE(247)] "%c[Extension Host] %cdebugger listening on port 5870 color: blue color:", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.js (247)
[67667:0419/232934.383865:INFO:CONSOLE(225)] "%c INFO color: #33f Started local extension host with pid 75479.", source: vscode-file://vscode-app/Users/bhaines/repo/vscode/out/vs/platform/log/common/log.js (225)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:83005)
    at _.send (node:electron/js2c/browser_init:2:69166)
    at Protocol.send (/Users/bhaines/repo/vscode/out/vs/base/parts/ipc/common/ipc.electron.js:21:29)
    at ChannelServer.sendBuffer (/Users/bhaines/repo/vscode/out/vs/base/parts/ipc/common/ipc.js:252:31)
    at ChannelServer.send (/Users/bhaines/repo/vscode/out/vs/base/parts/ipc/common/ipc.js:248:25)
    at ChannelServer.sendResponse (/Users/bhaines/repo/vscode/out/vs/base/parts/ipc/common/ipc.js:238:44)
    at UniqueContainer.value (/Users/bhaines/repo/vscode/out/vs/base/parts/ipc/common/ipc.js:325:51)
    at Emitter._deliver (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter._deliverQueue (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:900:22)
    at Emitter.fire (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:923:22)
    at /Users/bhaines/repo/vscode/out/vs/base/common/event.js:333:29
    at /Users/bhaines/repo/vscode/out/vs/base/common/event.js:133:115
    at UniqueContainer.value (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:133:115)
    at Emitter._deliver (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter._deliverQueue (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:900:22)
    at Emitter.fire (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:923:22)
    at UniqueContainer.value (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:102:93)
    at Emitter._deliver (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:918:22)
    at UniqueContainer.value (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:121:106)
    at Emitter._deliver (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:918:22)
    at UniqueContainer.value (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:102:93)
    at Emitter._deliver (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter._deliverQueue (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:900:22)
    at Emitter.fire (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:923:22)
    at WindowsMainService.onWindowClosed (/Users/bhaines/repo/vscode/out/vs/platform/windows/electron-main/windowsMainService.js:1210:43)
    at /Users/bhaines/repo/vscode/out/vs/platform/windows/electron-main/windowsMainService.js:1099:89
    at UniqueContainer.value (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:80:37)
    at Emitter._deliver (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:918:22)
    at UniqueContainer.value (/Users/bhaines/repo/vscode/out/vs/platform/windows/electron-main/windowImpl.js:46:34)
    at Emitter._deliver (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:889:26)
    at Emitter.fire (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:918:22)
    at BrowserWindow.fn (/Users/bhaines/repo/vscode/out/vs/base/common/event.js:459:44)
    at BrowserWindow.emit (node:events:529:35)
</pre>
The `Error sending from webFrameMain...` and subsequent lines then repeat a few hundred times.
</details>

**Comment by bhainesva** [comment]
I've updated vscode to 1.89, and also updated MacOS to Sonoma 14.3, but I'm still experiencing the problem. 

Version: 1.89.0 (Universal)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:10.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.3.0

**Comment by deepak1556** [comment]
We are seeing a normal termination via SIGTERM for the child processes hence a crash dump will not be available. The logs indicate it as crashed but is more of the signal used when `process.kill` is called.

@bhainesva can you start the application with `code --disable-kill-after-bad-ipc --log trace`, check if the issue persists and attach the logs generated at `~/Library/Application Support/Code/logs`

**Comment by bhainesva** [comment]
After adding those flags the behavior seems slightly different. This time only the extension debugging window crashed, the main instance persisted. Anecdotally it took me longer to trigger than usual, but it's hard to say. 

Other strange behavior, I had enabled some extensions since it seemed like those weren't the source of the problem, but as I'm refreshing the extension window vim mode becomes unresponsive and I can't type until I disable the extension. 

logs here: [Archive.zip](https://github.com/microsoft/vscode/files/15244068/Archive.zip)

**Comment by deepak1556** [comment]
Thanks for the logs, the extension host and window are seeing errors from other extensions. I would like to confirm if they are triggering the process termination calls. Can you kill all VS Code processes and start the application with `code helloworld --disable-kill-after-bad-ipc --log trace --extensions-dir /tmp/helloworld-extension-test`, see if the issue persists.

**Comment by bhainesva** [comment]
Can reproduce on 1.90.2

```
Version: 1.90.2 (Universal)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:37:41.291Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 23.3.0
```

**Comment by bhainesva** [comment]
Since the last post I've gotten a new laptop (Apple Macbook Pro M2), but can unfortunately still reproduce. These have both been machines provisioned by my employer so I also checked with them to see if potentially this was caused by security software incorrectly detecting malicious behavior and killing the process. They don't think that's the cause. 

Current version
```
Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by bhainesva** [comment]
When the window crashes it appears to also crash the tracing window: https://www.youtube.com/watch?v=m4V6zLMDQpI.

**Comment by deepak1556** [comment]
Hmm, to rule out application sandbox can you confirm if the crash happens when launching the application with `--no-sandbox`

**Comment by bhainesva** [comment]
Yes it happens with `--no-sandbox`.
