### ISSUE TITLE
Persistent error : Could not find pty on pty host

### ISSUE THREAD

**Issue by TonyGravagno** [microsoft/vscode#210792]
VSCode over Windows 10, with Remote SSH extension to a remote Ubuntu v20. I've been running this configuration for many months. Remote extensions are acting a bit wonky. I can't tell if this is a recent issue, after an update, or within the last couple months. I'm just trying now to get extensions to work while installed remotely, and they are not, so I'm investigating causes.

While trying to diagnose that I found that on the every initial SSH connection that the Output : Window reports:

> [error] Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host

<details>
<summary>Detail from Output : Window</summary>

```log
2024-04-19 13:03:03.059 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][26305ms] waiting...
2024-04-19 13:03:04.066 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][27313ms] waiting...
2024-04-19 13:03:05.004 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][28250ms] returned Managed(1)
2024-04-19 13:03:05.004 [info] resolveAuthority(ssh-remote) returned 'Managed(1)' after 28252 ms
2024-04-19 13:03:05.030 [info] Creating a socket (renderer-Management-855038fc-c9f5-4b79-a305-73937542dd9a)...
2024-04-19 13:03:05.031 [info] Creating a socket (renderer-ExtensionHost-a739e94d-7d7f-402e-89d0-a31fdb2f8598)...
2024-04-19 13:03:05.197 [info] Creating a socket (renderer-ExtensionHost-a739e94d-7d7f-402e-89d0-a31fdb2f8598) was successful after 169 ms.
2024-04-19 13:03:05.199 [info] Creating a socket (renderer-Management-855038fc-c9f5-4b79-a305-73937542dd9a) was successful after 172 ms.
2024-04-19 13:03:07.121 [info] [perf] Render performance baseline is 32ms
2024-04-19 13:03:07.681 [error] Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at D.U (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
    at D.updateTitle (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27632)
    at j.<computed> (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:22875)
    at Object.call (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5137)
    at l.s (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5145)
    at l.q (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4647)
    at n.value (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4045)
    at t.y (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:29:665)
    at t.fire (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:29:882)
    at process.ue (/home/ubuntu/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:25:10030)
    at process.emit (node:events:517:28)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-19 13:03:32.240 [info] Extension host (Remote) is unresponsive.
2024-04-19 13:03:35.973 [info] Extension host (Remote) is responsive.
```

</details>

I believe this is the correct stack leading to that : [ptyHostMain](https://github.com/microsoft/vscode/blob/f86134162494bb2ff6dc3cfc849f5d3b7e056819/src/vs/platform/terminal/node/ptyHostMain.ts#L83) > [ptyService](https://github.com/microsoft/vscode/blob/f86134162494bb2ff6dc3cfc849f5d3b7e056819/src/vs/platform/terminal/node/ptyService.ts#L311) > [throw](https://github.com/microsoft/vscode/blob/f86134162494bb2ff6dc3cfc849f5d3b7e056819/src/vs/platform/terminal/node/ptyService.ts#L603)

I have been running the Release version of the Remote SSH extension but loaded the Pre-Release today to see if the issue was fixed. Nope.

It may or may not be related but I'm also struggling with SSH connection drops. The session will be fine for a long time, until "something changes" and then it goes into a reconnect state and cannot reconnect. I need to restart the connection. This also happens with no other extensions. I have other SSH sessions open to the same server:port/user and there are no drops. To my knowledge, only VSCode is experiencing issues.

The issues with extensions may or may not be related. My focus right now is only on this error from ptyHostMain. When this is resolved I'll move up the chain for the other challenges.

I do not see related issues noted in server logs but will activated and check debug logs if details are provided here.

The .vscode-server folder has been deleted and recreated many times. After closing the client-side app I've terminated the server pids.

Used/Max Ptys = 1/4096

Other settings from VSCode:

```json
// user
  "remote.SSH.connectTimeout": 120,
  "remote.SSH.enableRemoteCommand": true,
  "remote.SSH.enableX11Forwarding": false,
  "remote.SSH.localServerDownload": "auto",
  "remote.SSH.logLevel": "debug",
  "remote.SSH.showLoginTerminal": true,
// app
  "remote.SSH.useLocalServer": false, // was true, no difference
  "remote.SSH.connectTimeout": 120
```

```
# vscode_remote.config
  PreferredAuthentications publickey
  ServerAliveInterval 60
  ServerAliveCountMax 10
```

I researched this issue in Issues here, in StackOverflow, and with other googling, but found nothing close to this previously reported.

Dunno what else I can add. I have full access to client and server and will be eager to provide info, and load and test patches.

Thanks.

(I tried to post this from in-app Issue Reporter and the "Create on GitHub" button wasn't responsive. ( #134530 )

<details>
<summary>System Info</summary>

Version: 1.88.1 (system setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39 ( client and server agree )
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

CPUs | Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 31.82GB (15.59GB free)
Process Argv | --crash-reporter-id 3555131d-7d56-4887-a807-ceafc2556f0b
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
remote-ssh | ms- | 0.111.2024040515
remote-ssh-edit | ms- | 0.86.0
remote-explorer | ms- | 0.4.3

</details>

**Comment by torext** [comment]
Having the same continuous `CodeExpectedError: Could not find pty on pty host`error in my `Remote - SSH` console output. Running VSCode 1.89.0 and `Remote - SSH` extension `v0.110.1`.

**Comment by wzh4464** [comment]
I encounter the problem that when using remote ssh, no second terminal can be opened. When I check the log in the remote server, it also shows me "Could not find pty on pty host"

**Comment by AndSanAnd** [comment]
I am running into the same issue here, it used to work well but now I remote extensions are not working. I went through similar troubleshooting steps as OP with no solution.

**Comment by bkvaiude** [comment]
I am also facing a similar issue while working with a coder setup. I tried troubleshooting it to resolve the issue but I have not been able to do so. It seems to be related to the issue that is being discussed in this thread. Has anyone been able to find a solution for this issue? It would be great if you can help me out.

Here are version data from output console:
```
[20:42:47.458] Log Level: 2
[20:42:47.633] VS Code version: 1.90.1
[20:42:47.633] Remote-SSH version: remote-ssh@0.112.0
[20:42:47.634] win32 x64
```

**Comment by jzyrobert** [comment]
The same thing has been happening to me for a while. Currently on VS Code version `1.90.2` and Remote-SSH version `0.112.0`. But this has been happening since around version 1.88/1.89 of VS Code.

Already installed extensions tend to continue working but it causes any new installation attempts to hang indefinitely at "installing..." until I fully restart the remote server using `pkill vscode-server` and reload the window.

After searching around the github issues, one potential lead I have is related to the change introduced into `node-pty` here: https://github.com/microsoft/node-pty/pull/510

After this issue was raised: https://github.com/microsoft/node-pty/issues/512, it was supposedly fixed by https://github.com/microsoft/node-pty/pull/626 on Oct 4th 2023.

However, the version `1.1.0-beta5` released on Oct 2nd 2023: https://www.npmjs.com/package/node-pty/v/1.1.0-beta5 is the one in use by `xterm.js` version `5.6.0-beta17` here: https://github.com/xtermjs/xterm.js/blob/826c05704730ac51de4287451dddf4d3ddffe041/package.json,
which is then in use by VS Code 1.90 here: https://github.com/microsoft/vscode/blob/release/1.90/package.json so it is supposedly running the version without the subsequent fix.

@Tyriar any idea whether this could be the possible point of failure?

**Comment by kbrown1snl** [comment]
I'm having the same issue as several above. Any idea if someone can fix this?

**Comment by adn34** [comment]
I have the same issue with either password prompt showing every 20 seconds or vscode reconnecting every 20s when using an SSH key, opening developer tools shows "ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host".

**Comment by tim-lucera** [comment]
I have a different problem but it seems to have the same underlying cause (i.e. `Could not find pty on pty host`). Looks like it was introduced sometime after 1.87.2. See https://github.com/microsoft/vscode-remote-release/issues/10039 for more info

**Comment by nojaf** [comment]
Hello,

I'm trying to reproduce this locally with

![Image](https://github.com/user-attachments/assets/84976c6b-bd31-4d7a-b59b-1b4247311f2a)

Are there any particular extensions I need to install to trigger this behaviour?
I assume I should see the error log in the `Pty Host (Remote)` output.

Could anyone post some recent basic steps to reproduce?
Remote SSH only is not showing the problem for me.

**Comment by entin-hun** [comment]
My Intel-based MacBook has the same connection problem.. then stuck at banner exchange and times out until server reboot..

**Comment by grandrew** [comment]
I am seeing this error but with seemingly unimportant stuff, I see no degradation of experience:
(it says something around updating icon and updating title, which could be just aesthetics)

That's Win 11, no connection problems or any other problems whatsoever (except for forever classic crashes of python language server but that's almost certainly unrelated)


```
[13:12:53.968] [server] [13:12:56] [<unknown>][85e710e3][ExtensionHostConnection] <765947> Launched Extension Host Process.
[13:13:00.669] [server] rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
[13:13:00.679] [server] stack trace: CodeExpectedError: Could not find pty on pty host
[13:13:00.680] [server]     at k.U (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:30837)
[13:13:00.680] [server]     at k.updateIcon (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:26087)
[13:13:00.680] [server]     at D.<computed> (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:21308)
[13:13:00.681] [server]     at Object.call (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5378)
[13:13:00.681] [server]     at c.s (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5506)
[13:13:00.681] [server]     at c.q (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4947)
[13:13:00.681] [server]     at w.value (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4247)
[13:13:00.682] [server]     at i.B (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:741)
[13:13:00.682] [server]     at i.fire (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:958)
[13:13:00.682] [server]     at process.$e (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:25:27395)
[13:13:00.682] [server]     at process.emit (node:events:519:28)
[13:13:00.683] [server]     at emit (node:internal/child_process:951:14)
[13:13:00.683] [server]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[13:13:00.683] [server] [13:13:02] Error [CodeExpectedError]: Could not find pty on pty host
[13:13:00.683] [server]     at k.U (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:30837)
[13:13:00.684] [server]     at k.updateIcon (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:26087)
[13:13:00.684] [server]     at D.<computed> (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:21308)
[13:13:00.684] [server]     at Object.call (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5378)
[13:13:00.684] [server]     at c.s (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5506)
[13:13:00.684] [server]     at c.q (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4947)
[13:13:00.685] [server]     at w.value (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4247)
[13:13:00.685] [server]     at i.B (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:741)
[13:13:00.685] [server]     at i.fire (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:958)
[13:13:00.685] [server]     at process.$e (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:25:27395)
[13:13:00.685] [server]     at process.emit (node:events:519:28)
[13:13:00.686] [server]     at emit (node:internal/child_process:951:14)
[13:13:00.686] [server]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[13:13:00.686] [server] rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
[13:13:00.686] [server] stack trace: CodeExpectedError: Could not find pty on pty host
[13:13:00.687] [server]     at k.U (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:30837)
[13:13:00.687] [server]     at k.updateTitle (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:26037)
[13:13:00.687] [server]     at D.<computed> (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:21308)
[13:13:00.688] [server]     at Object.call (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5378)
[13:13:00.688] [server]     at c.s (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5506)
[13:13:00.688] [server]     at c.q (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4947)
[13:13:00.689] [server]     at w.value (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4247)
[13:13:00.689] [server]     at i.B (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:741)
[13:13:00.689] [server]     at i.fire (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:958)
[13:13:00.690] [server]     at process.$e (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:25:27395)
[13:13:00.690] [server]     at process.emit (node:events:519:28)
[13:13:00.690] [server]     at emit (node:internal/child_process:951:14)
[13:13:00.690] [server]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[13:13:00.691] [server] [13:13:02] Error [CodeExpectedError]: Could not find pty on pty host
[13:13:00.692] [server]     at k.U (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:30837)
[13:13:00.692] [server]     at k.updateTitle (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:26037)
[13:13:00.693] [server]     at D.<computed> (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:54:21308)
[13:13:00.693] [server]     at Object.call (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5378)
[13:13:00.694] [server]     at c.s (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5506)
[13:13:00.694] [server]     at c.q (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4947)
[13:13:00.694] [server]     at w.value (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4247)
[13:13:00.695] [server]     at i.B (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:741)
[13:13:00.695] [server]     at i.fire (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:30:958)
[13:13:00.695] [server]     at process.$e (/home/grandrew/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/platform/terminal/node/ptyHostMain.js:25:27395)
[13:13:00.696] [server]     at process.emit (node:events:519:28)
[13:13:00.696] [server]     at emit (node:internal/child_process:951:14)
[13:13:00.696] [server]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by nojaf** [comment]
Hi @Tyriar, I'm trying to debug this issue locally.

After cloning, building, and running VSCode, I successfully install the VSIX from https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh. 
Next, I attempt to connect via SSH to reproduce the problem while debugging. However, the VSCode server doesn't start. The SSH connection works, and the files are installed in `.vscode-server-oss`, but I keep getting `Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused)` in the developer console.

Is there any configuration needed to run the remote VSCode server with a locally built VSCode?

**Comment by jzyrobert** [comment]
> The same thing has been happening to me for a while. Currently on VS Code version `1.90.2` and Remote-SSH version `0.112.0`. But this has been happening since around version 1.88/1.89 of VS Code.
> 
> Already installed extensions tend to continue working but it causes any new installation attempts to hang indefinitely at "installing..." until I fully restart the remote server using `pkill vscode-server` and reload the window.
> 
> After searching around the github issues, one potential lead I have is related to the change introduced into `node-pty` here: [microsoft/node-pty#510](https://github.com/microsoft/node-pty/pull/510)
> 
> After this issue was raised: [microsoft/node-pty#512](https://github.com/microsoft/node-pty/issues/512), it was supposedly fixed by [microsoft/node-pty#626](https://github.com/microsoft/node-pty/pull/626) on Oct 4th 2023.
> 
> However, the version `1.1.0-beta5` released on Oct 2nd 2023: https://www.npmjs.com/package/node-pty/v/1.1.0-beta5 is the one in use by `xterm.js` version `5.6.0-beta17` here: https://github.com/xtermjs/xterm.js/blob/826c05704730ac51de4287451dddf4d3ddffe041/package.json, which is then in use by VS Code 1.90 here: https://github.com/microsoft/vscode/blob/release/1.90/package.json so it is supposedly running the version without the subsequent fix.
> 
> @Tyriar any idea whether this could be the possible point of failure?

Anecdotal, but since upgrading to 1.92.2 I don't seem to be experiencing these issues anymore. I can see that the packages I mentioned have been updated in both xterm.js and vscode, I wonder if that did end up being the cause.

**Comment by Crystal-RainSlide** [comment]
Note: This problem can be caused by an old but alive (for whatever reason) session of VSCode server. It will occupy some of current server's ports if it's remain alive. Although much less likely, this should also applies to other program occupying VSCode remote's ports.

If it's the case, kill the old VSCode server session (all the process located at `~/.vscode-server/`) / re-login your user on your server / or just restart your server's OS should fix it.

Ref: my own experience and https://github.com/microsoft/vscode/issues/177460#issuecomment-1477342030

* I got no clue about the reasons why the old remote server staying alive. Maybe if one suspend his client OS in a remote session for too long, the session will be expired, and the remote client will start a session without ask previous remote server to exit?

**Comment by mpzfm1** [comment]
im having the same issue... randomly i lost the connection... 

[error] CodeExpectedError: Could not find pty 2 on pty host

**Comment by llibetter** [comment]
when i debug python code, i lost connection.
![Image](https://github.com/user-attachments/assets/c645f48b-ada1-4dba-98c5-fcd1e95831cb)

**Comment by ampandey-1995** [comment]
I am having this same issue here. Can anyone suggest some workaround?

**Logs**

[log.txt](https://github.com/user-attachments/files/21559952/log.txt)
