### ISSUE TITLE
shell.js:231 SplitLinesCollection: attempt to access a 'newer' model

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21073]
```
shell.js:231 SplitLinesCollection: attempt to access a 'newer' model: Error: SplitLinesCollection: attempt to access a 'newer' model
    at SplitLinesCollection._ensureValidState (file:////Users/bpasero/Development/monaco/out/vs/editor/common/viewModel/splitLinesCollection.js:249:23)
    at SplitLinesCollection.getViewLineMinColumn (file:////Users/bpasero/Development/monaco/out/vs/editor/common/viewModel/splitLinesCollection.js:535:18)
    at ViewModel.getLineMinColumn (file:////Users/bpasero/Development/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:372:31)
    at ViewModel.getCenteredRangeInViewport (file:////Users/bpasero/Development/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:187:83)
    at ViewModel._onEvents (file:////Users/bpasero/Development/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:205:51)
    at ViewModel.onEvents (file:////Users/bpasero/Development/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:157:18)
    at file:////Users/bpasero/Development/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:73:23
    at CallbackList.invoke (file:////Users/bpasero/Development/monaco/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (file:////Users/bpasero/Development/monaco/out/vs/base/common/event.js:88:40)
    at Configuration.CommonEditorConfiguration._setOptions (file:////Users/bpasero/Development/monaco/out/vs/editor/common/config/commonEditorConfig.js:435:31)
```

Steps to Reproduce:

1. copy the entire contents of a file
2. press and hold paste to paste a lot

=> eventually you get this stack

**Comment by alexandrudima** [comment]
Nice find! This happens when the model gets more lines (i.e. from 999 to 1000) and the configuration changes as part of the viewModel handling events.
