### ISSUE TITLE
Extension updating issue

### ISSUE THREAD

**Issue by XCanG** [microsoft/vscode#210837]
Type: <b>Bug</b>

Recently VSCode added new way of updating extensions without reloading window, but this update broke my updating process.

My current setup is following: I'm a full stack developer, so I have backend opened in python (with python profile) and frontend opened in javascript (with js profile), so I **always have 2 windows** on the startup and during work.

Then when I receive update first window did get "loading" icon on extensions tab, while last window show number of updated extensions, I can reload them using new method or reload window - it's fine, but in first window they are not installed, if I open it by myself and click "Update" I would get an errors, the output in log would be:
```java
2024-04-20 21:25:55.864 [info] Started local extension host with pid 3776.
2024-04-20 21:25:58.793 [info] [perf] Render performance baseline is 29ms
2024-04-20 21:25:59.039 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-04-20 21:26:00.435 [error] Unknown error while installing extension pkief.material-icon-theme: Unknown: Unknown error while installing extension pkief.material-icon-theme
    at K.installFromGallery (d:\Prog\VSCode\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:59720)
2024-04-20 21:26:00.435 [error] Unknown error while installing extension quicktype.quicktype: Unknown: Unknown error while installing extension quicktype.quicktype
    at K.installFromGallery (d:\Prog\VSCode\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:59720)
2024-04-20 21:26:00.435 [error] Unknown error while installing extension snyk-security.snyk-vulnerability-scanner: Unknown: Unknown error while installing extension snyk-security.snyk-vulnerability-scanner
    at K.installFromGallery (d:\Prog\VSCode\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:59720)
2024-04-20 21:26:00.436 [error] Unknown error while installing extension usernamehw.errorlens: Unknown: Unknown error while installing extension usernamehw.errorlens
    at K.installFromGallery (d:\Prog\VSCode\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:59720)
2024-04-20 21:26:07.337 [error] Unknown: Unknown error while installing extension pkief.material-icon-theme
    at K.installFromGallery (d:\Prog\VSCode\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:59720)
2024-04-20 21:26:07.394 [error] Unknown error while installing extension pkief.material-icon-theme: Unknown: Unknown error while installing extension pkief.material-icon-theme
    at K.installFromGallery (d:\Prog\VSCode\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:59720)
```

Even if I reload window it wouldn't solve an issue, only full VSCode restart on the next load will show number of extensions to update instead of "loading" icon. I still would need to update them manually, but at least it would update after restart.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (9.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sqlite|ale|0.14.1
sort-editors|asw|2.0.1
vscode-custom-css|be5|7.2.1
ruff|cha|2024.20.0
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.86.1
discord-vscode|icr|5.8.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.0
vscode-language-pack-ru|MS-|1.88.2024041009
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
material-icon-theme|PKi|5.1.0
quicktype|qui|23.0.149
LiveServer|rit|5.7.9
jinjahtml|sam|0.20.0
markdown-preview-enhanced|shd|0.8.13
gitconfig|sid|2.0.1
even-better-toml|tam|0.19.2
mako|tom|0.2.0
errorlens|use|3.17.0
scss-to-css|yut|3.2.3
material-theme|zhu|3.17.0

</details>

**Comment by sandy081** [comment]
Can you please provide steps to reproduce? While you can reproduce can you please share following log?
- F1 > Open View... > Shared

**Comment by XCanG** [comment]
I will try when there would be an update released, but at this moment I cannot do that because all extensions are upgraded. Unless I can somehow downgrade them.

**Comment by XCanG** [comment]
Ok, so I've managed to capture this bug again, so this time I have 3 windows, 1st and 3rd were in one profile for backend and 2nd was in another profile for frontend.

The icon for addons looks like this and 2nd window is the one that have issue:
![image](https://github.com/microsoft/vscode/assets/4011523/28a6badf-048c-4fc5-9638-8f2fe2ae3f35)

Now, regarding log for `Shared` view, it's quite big so I put it into spoiler:
<details><summary>Logs</summary>

```c
2024-05-02 20:32:16.497 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.742 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.767 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.772 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.780 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.789 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.793 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.797 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.802 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.818 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.834 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.834 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.858 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.890 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.891 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.926 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:16.927 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.073 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.318 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.331 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.336 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.348 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.353 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.356 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.359 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.376 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:17.509 [info] Deleted uninstalled extension from disk quicktype.quicktype c:\Users\X4\.vscode\extensions\quicktype.quicktype-23.0.149
2024-05-02 20:32:17.919 [info] Deleted uninstalled extension from disk rangav.vscode-thunder-client c:\Users\X4\.vscode\extensions\rangav.vscode-thunder-client-2.21.10
2024-05-02 20:32:18.266 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:18.485 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:18.756 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:18.896 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:18.944 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:18.998 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:19.365 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:19.444 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:19.448 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:19.714 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:19.738 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:19.767 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:20.092 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:20.127 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:20.164 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:20.426 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:20.432 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:20.479 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:21.119 [info] Getting Manifest... eamodio.gitlens
2024-05-02 20:32:21.120 [info] Getting Manifest... ms-azuretools.vscode-docker
2024-05-02 20:32:21.121 [info] Getting Manifest... quicktype.quicktype
2024-05-02 20:32:21.122 [info] Getting Manifest... snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:21.123 [info] Getting Manifest... zhuangtongfa.material-theme
2024-05-02 20:32:21.209 [info] Getting Manifest... eamodio.gitlens
2024-05-02 20:32:21.211 [info] Getting Manifest... ms-azuretools.vscode-docker
2024-05-02 20:32:21.212 [info] Getting Manifest... quicktype.quicktype
2024-05-02 20:32:21.212 [info] Getting Manifest... snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:21.214 [info] Getting Manifest... zhuangtongfa.material-theme
2024-05-02 20:32:21.472 [info] Getting Manifest... eamodio.gitlens
2024-05-02 20:32:21.474 [info] Getting Manifest... ms-azuretools.vscode-docker
2024-05-02 20:32:21.474 [info] Getting Manifest... nrwl.angular-console
2024-05-02 20:32:21.475 [info] Getting Manifest... quicktype.quicktype
2024-05-02 20:32:21.475 [info] Getting Manifest... rangav.vscode-thunder-client
2024-05-02 20:32:21.476 [info] Getting Manifest... snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:21.476 [info] Getting Manifest... zhuangtongfa.material-theme
2024-05-02 20:32:21.570 [info] Installing extension: snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:21.570 [info] Extension is already requested to install snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:21.579 [info] Installing extension: ms-azuretools.vscode-docker
2024-05-02 20:32:21.579 [info] Installing extension: zhuangtongfa.material-theme
2024-05-02 20:32:21.580 [info] Installing extension: quicktype.quicktype
2024-05-02 20:32:21.580 [info] Extension is already requested to install zhuangtongfa.material-theme
2024-05-02 20:32:21.580 [info] Extension is already requested to install quicktype.quicktype
2024-05-02 20:32:21.583 [info] Extension is already requested to install ms-azuretools.vscode-docker
2024-05-02 20:32:21.583 [info] Installing extension: ms-azuretools.vscode-docker
2024-05-02 20:32:21.587 [info] Installing extension: eamodio.gitlens
2024-05-02 20:32:21.590 [info] Installing extension: eamodio.gitlens
2024-05-02 20:32:21.591 [info] Installing extension: quicktype.quicktype
2024-05-02 20:32:21.592 [info] Installing extension: snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:21.594 [info] Installing extension: zhuangtongfa.material-theme
2024-05-02 20:32:21.599 [info] Extension is already requested to install eamodio.gitlens
2024-05-02 20:32:21.792 [info] Installing extension: rangav.vscode-thunder-client
2024-05-02 20:32:21.793 [info] Installing extension: nrwl.angular-console
2024-05-02 20:32:22.160 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.231 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.266 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.331 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.386 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.425 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.457 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.461 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.475 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.480 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.491 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.495 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:22.978 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.074 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.165 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.286 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.352 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.356 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.459 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.483 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.488 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.512 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.532 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.569 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:23.977 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.057 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.098 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.125 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.220 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.246 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.265 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.469 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:24.677 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:25.903 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:26.052 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:30.649 [info] Extension signature is verified: snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:30.651 [info] Extension signature is verified: zhuangtongfa.material-theme
2024-05-02 20:32:30.651 [info] Extension signature is verified: quicktype.quicktype
2024-05-02 20:32:30.651 [info] Extension signature is verified: rangav.vscode-thunder-client
2024-05-02 20:32:30.652 [info] Extension signature is verified: eamodio.gitlens
2024-05-02 20:32:30.672 [info] Extension signature is verified: ms-azuretools.vscode-docker
2024-05-02 20:32:30.921 [info] Extracted extension to file:///c%3A/Users/X4/.vscode/extensions/rangav.vscode-thunder-client-2.21.18: rangav.vscode-thunder-client
2024-05-02 20:32:30.926 [info] Extracted extension to file:///c%3A/Users/X4/.vscode/extensions/zhuangtongfa.material-theme-3.17.2: zhuangtongfa.material-theme
2024-05-02 20:32:30.940 [info] Renamed to c:\Users\X4\.vscode\extensions\rangav.vscode-thunder-client-2.21.18
2024-05-02 20:32:30.944 [info] Renamed to c:\Users\X4\.vscode\extensions\zhuangtongfa.material-theme-3.17.2
2024-05-02 20:32:30.950 [info] Extracting extension completed. rangav.vscode-thunder-client
2024-05-02 20:32:30.965 [info] Extracting extension completed. zhuangtongfa.material-theme
2024-05-02 20:32:30.968 [info] Extension installed successfully: rangav.vscode-thunder-client
2024-05-02 20:32:30.972 [info] Extracted extension to file:///c%3A/Users/X4/.vscode/extensions/quicktype.quicktype-23.0.158: quicktype.quicktype
2024-05-02 20:32:30.975 [info] Marked extension as uninstalled rangav.vscode-thunder-client-2.21.13
2024-05-02 20:32:30.979 [info] Extracted extension to file:///c%3A/Users/X4/.vscode/extensions/ms-azuretools.vscode-docker-1.29.1: ms-azuretools.vscode-docker
2024-05-02 20:32:30.982 [info] Extension installed successfully: zhuangtongfa.material-theme
2024-05-02 20:32:30.983 [info] Extension installed successfully: zhuangtongfa.material-theme
2024-05-02 20:32:30.986 [info] Renamed to c:\Users\X4\.vscode\extensions\quicktype.quicktype-23.0.158
2024-05-02 20:32:30.994 [info] Extracting extension completed. quicktype.quicktype
2024-05-02 20:32:30.998 [info] Renamed to c:\Users\X4\.vscode\extensions\ms-azuretools.vscode-docker-1.29.1
2024-05-02 20:32:31.021 [info] Extension installed successfully: quicktype.quicktype
2024-05-02 20:32:31.021 [info] Extension installed successfully: quicktype.quicktype
2024-05-02 20:32:31.023 [info] Extracting extension completed. ms-azuretools.vscode-docker
2024-05-02 20:32:31.048 [info] Extension installed successfully: ms-azuretools.vscode-docker
2024-05-02 20:32:31.048 [info] Extension installed successfully: ms-azuretools.vscode-docker
2024-05-02 20:32:31.290 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:31.294 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:31.745 [info] Extracted extension to file:///c%3A/Users/X4/.vscode/extensions/eamodio.gitlens-14.9.1: eamodio.gitlens
2024-05-02 20:32:31.775 [info] Renamed to c:\Users\X4\.vscode\extensions\eamodio.gitlens-14.9.1
2024-05-02 20:32:31.785 [info] Extracting extension completed. eamodio.gitlens
2024-05-02 20:32:31.827 [info] Extension installed successfully: eamodio.gitlens
2024-05-02 20:32:31.827 [info] Extension installed successfully: eamodio.gitlens
2024-05-02 20:32:32.016 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:32.025 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:33.289 [info] Extension signature is verified: nrwl.angular-console
2024-05-02 20:32:34.389 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:34.510 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:34.886 [info] Extracted extension to file:///c%3A/Users/X4/.vscode/extensions/nrwl.angular-console-18.20.0: nrwl.angular-console
2024-05-02 20:32:34.905 [info] Renamed to c:\Users\X4\.vscode\extensions\nrwl.angular-console-18.20.0
2024-05-02 20:32:34.916 [info] Extracting extension completed. nrwl.angular-console
2024-05-02 20:32:34.928 [info] Extension installed successfully: nrwl.angular-console
2024-05-02 20:32:34.931 [info] Marked extension as uninstalled nrwl.angular-console-18.19.0
2024-05-02 20:32:35.145 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:35.150 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:37.081 [info] Extracted extension to file:///c%3A/Users/X4/.vscode/extensions/snyk-security.snyk-vulnerability-scanner-2.6.1: snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:37.100 [info] Renamed to c:\Users\X4\.vscode\extensions\snyk-security.snyk-vulnerability-scanner-2.6.1
2024-05-02 20:32:37.110 [info] Extracting extension completed. snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:37.140 [info] Extension installed successfully: snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:37.140 [info] Extension installed successfully: snyk-security.snyk-vulnerability-scanner
2024-05-02 20:32:37.314 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:37.388 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:37.640 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:37.748 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:49.729 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:49.852 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:32:53.769 [error] [uncaught exception in sharedProcess]: A system error occurred (ENOENT: no such file or directory, scandir 'C:\Users\X4\AppData\Roaming\Code\clp\7177ecdeeec6aeec60a225404afe43b3.ru'): Error: ENOENT: no such file or directory, scandir 'C:\Users\X4\AppData\Roaming\Code\clp\7177ecdeeec6aeec60a225404afe43b3.ru'
2024-05-02 20:33:02.670 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:33:02.786 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:33:32.223 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:33:32.345 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:33:49.969 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:33:50.098 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:34:24.021 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:34:24.134 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:37:18.592 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:37:18.871 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:37:18.925 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:39:24.704 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-05-02 20:39:24.814 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
```

</details>

@sandy081 please tell me if you need more info

**Comment by XCanG** [comment]
Also if I reload 2nd window while in this state, in logs the following lines will appear:

```c
2024-05-02 20:51:25.844 [info] Getting Manifest... eamodio.gitlens
2024-05-02 20:51:25.845 [info] Getting Manifest... ms-azuretools.vscode-docker
2024-05-02 20:51:25.846 [info] Getting Manifest... quicktype.quicktype
2024-05-02 20:51:25.847 [info] Getting Manifest... snyk-security.snyk-vulnerability-scanner
2024-05-02 20:51:25.847 [info] Getting Manifest... zhuangtongfa.material-theme
2024-05-02 20:51:25.858 [info] Extension is already requested to install ms-azuretools.vscode-docker
2024-05-02 20:51:25.862 [info] Extension is already requested to install eamodio.gitlens
2024-05-02 20:51:25.863 [info] Extension is already requested to install quicktype.quicktype
2024-05-02 20:51:25.863 [info] Extension is already requested to install snyk-security.snyk-vulnerability-scanner
2024-05-02 20:51:25.863 [info] Extension is already requested to install zhuangtongfa.material-theme
```

And clicking on `Update` button wont print new logs, but will show this popup:
![image](https://github.com/microsoft/vscode/assets/4011523/70f9a879-4734-4bf1-8a15-08add0481fba)

**Comment by sandy081** [comment]
@XCanG Thanks for the info. I have to look into the logs, understand and analyse why this is happening. Will get back to you after.

**Comment by andreamah** [comment]
@XCanG Can you check if this is fixed in the latest VS Code Insiders? Thanks!

@sandy081 are there any alternative verif steps that we can use?

**Comment by XCanG** [comment]
> @XCanG Can you check if this is fixed in the latest VS Code Insiders? Thanks!

It would be hard to test as it rely on add-on update. So it may take a week or more.

**Comment by sandy081** [comment]
To verify:

- Have two profiles A and B and open two windows one with Profile A and other with Profile B.
- Install `redhat.java` extension in both windows
- Install one older version of that extension in both windows
- Restart VS Code Insiders
- You should see Update on this extension in both windows
- Wait for 10s and Click on Update button in both windows at the same time
- Verify that extensions got updated.
