### ISSUE TITLE
Build failed: credscan completed with an Error

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#211027]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=269677
Changes: https://github.com/Microsoft/vscode/compare/348de48...fc50081

**Comment by joaomoreno** [comment]
Here's the full detail of the error:

```
The process cannot access the file 'D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\exthost.log' because it is being used by another process.
[WARNING] Asset D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\extensionTelemetry.log failed to get process
The process cannot access the file 'D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\extensionTelemetry.log' because it is being used by another process.


[WARNING] Asset D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\vscode.git\Git.log failed to get process
The process cannot access the file 'D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\vscode.git\Git.log' because it is being used by another process.

[WARNING] Asset D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\vscode.github\GitHub.log failed to get process
The process cannot access the file 'D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\vscode.github\GitHub.log' because it is being used by another process.

[WARNING] Asset D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\vscode.json-language-features\JSON Language Server.log failed to get process
The process cannot access the file 'D:\a\_work\1\s\.build\logs\smoke-tests-electron\5_suite_test_verifies_that_auto_save_triggers_on_shutdown\window1\exthost\vscode.json-language-features\JSON Language Server.log' because it is being used by another process.
```

This points to the fact that some process is still hanging on to the log files generated by the smoke tests.

**Comment by bpasero** [comment]
We log the processes that are still running after the smoke tests have finished:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=269677&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=c621e2c3-9be9-5e82-9df4-c1cfe6a15478

Here is the output:

```
2024-04-22T14:00:05.8404480Z ##[section]Starting: Diagnostics after smoke test run
2024-04-22T14:00:05.8409937Z ==============================================================================
2024-04-22T14:00:05.8410303Z Task         : PowerShell
2024-04-22T14:00:05.8410451Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2024-04-22T14:00:05.8410706Z Version      : 2.237.5
2024-04-22T14:00:05.8410844Z Author       : Microsoft Corporation
2024-04-22T14:00:05.8411073Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2024-04-22T14:00:05.8411338Z ==============================================================================
2024-04-22T14:00:06.8994903Z Generating script.
2024-04-22T14:00:06.9314089Z ========================== Starting Command Output ===========================
2024-04-22T14:00:06.9524961Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_work\_temp\01024d42-b38e-4512-8ae2-53d685db311f.ps1'"
2024-04-22T14:00:07.1347047Z 
2024-04-22T14:00:07.1348182Z D:\a\_work\1\s>echo "------------------------------------" 
2024-04-22T14:00:07.1348671Z "------------------------------------"
2024-04-22T14:00:07.1349655Z 
2024-04-22T14:00:07.1350039Z D:\a\_work\1\s>tasklist /V 
2024-04-22T14:00:07.1941086Z 
2024-04-22T14:00:07.1957089Z Image Name                     PID Session Name        Session#    Mem Usage Status          User Name                                              CPU Time Window Title                                                            
2024-04-22T14:00:07.1974285Z ========================= ======== ================ =========== ============ =============== ================================================== ============ ========================================================================
2024-04-22T14:00:07.1991406Z System Idle Process              0 Services                   0          8 K Unknown         NT AUTHORITY\SYSTEM                                     1:40:27 N/A                                                                     
2024-04-22T14:00:07.2005034Z System                           4 Services                   0        148 K Unknown         N/A                                                     0:01:58 N/A                                                                     
2024-04-22T14:00:07.2019108Z Secure System                   56 Services                   0     38,664 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2032628Z Registry                       100 Services                   0     92,480 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:02 N/A                                                                     
2024-04-22T14:00:07.2047431Z smss.exe                       484 Services                   0      1,216 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2073081Z csrss.exe                      644 Services                   0      5,248 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:03 N/A                                                                     
2024-04-22T14:00:07.2087633Z wininit.exe                    720 Services                   0      5,300 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2102863Z csrss.exe                      740 Console                    1      4,120 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2118509Z winlogon.exe                   808 Console                    1      8,620 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2133858Z services.exe                   864 Services                   0     15,600 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:02 N/A                                                                     
2024-04-22T14:00:07.2156837Z LsaIso.exe                     872 Services                   0      2,208 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2172154Z lsass.exe                      884 Services                   0     23,388 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:08 N/A                                                                     
2024-04-22T14:00:07.2187273Z svchost.exe                   1020 Services                   0      2,784 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2202633Z svchost.exe                     76 Services                   0     13,328 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2217585Z fontdrvhost.exe                572 Services                   0      2,972 K Unknown         Font Driver Host\UMFD-0                                 0:00:00 N/A                                                                     
2024-04-22T14:00:07.2240939Z fontdrvhost.exe                576 Console                    1      2,812 K Unknown         Font Driver Host\UMFD-1                                 0:00:00 N/A                                                                     
2024-04-22T14:00:07.2255632Z svchost.exe                    916 Services                   0     10,648 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:08 N/A                                                                     
2024-04-22T14:00:07.2270939Z svchost.exe                   1040 Services                   0      7,352 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2286302Z LogonUI.exe                   1136 Console                    1     41,540 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2300976Z dwm.exe                       1144 Console                    1     36,016 K Unknown         Window Manager\DWM-1                                    0:00:00 N/A                                                                     
2024-04-22T14:00:07.2324236Z svchost.exe                   1176 Services                   0     12,288 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.2338992Z svchost.exe                   1280 Services                   0      4,040 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2353514Z svchost.exe                   1320 Services                   0      6,876 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2368384Z svchost.exe                   1340 Services                   0      4,744 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2383271Z svchost.exe                   1380 Services                   0      3,912 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2406012Z svchost.exe                   1452 Services                   0     22,668 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:04 N/A                                                                     
2024-04-22T14:00:07.2420518Z svchost.exe                   1544 Services                   0      4,372 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2435382Z svchost.exe                   1572 Services                   0      7,496 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2450542Z svchost.exe                   1588 Services                   0      6,348 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2465319Z svchost.exe                   1604 Services                   0      4,756 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2488152Z svchost.exe                   1652 Services                   0      4,640 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2502951Z svchost.exe                   1660 Services                   0      4,556 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2517607Z svchost.exe                   1708 Services                   0      6,796 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2532498Z svchost.exe                   1764 Services                   0      9,716 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2548038Z svchost.exe                   1876 Services                   0      5,672 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2570785Z svchost.exe                   1900 Services                   0     17,104 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:03 N/A                                                                     
2024-04-22T14:00:07.2586350Z svchost.exe                   1916 Services                   0      4,136 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2601257Z svchost.exe                   1940 Services                   0      6,848 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2616554Z svchost.exe                   2032 Services                   0     13,440 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2631470Z svchost.exe                   1668 Services                   0      5,132 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2654655Z svchost.exe                   2024 Services                   0     10,948 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.2672854Z svchost.exe                   2088 Services                   0      7,932 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:01 N/A                                                                     
2024-04-22T14:00:07.2691277Z svchost.exe                   2152 Services                   0      4,316 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2709783Z svchost.exe                   2308 Services                   0     20,596 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:24 N/A                                                                     
2024-04-22T14:00:07.2728202Z svchost.exe                   2328 Services                   0      4,856 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2754728Z svchost.exe                   2428 Services                   0      7,640 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2771658Z svchost.exe                   2444 Services                   0      9,640 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2791114Z svchost.exe                   2480 Services                   0      7,068 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:01 N/A                                                                     
2024-04-22T14:00:07.2809605Z svchost.exe                   2644 Services                   0      8,608 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2828163Z svchost.exe                   2740 Services                   0      7,716 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2855087Z svchost.exe                   2752 Services                   0      6,920 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2874557Z svchost.exe                   2880 Services                   0      8,908 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2894690Z svchost.exe                   2944 Services                   0      7,780 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2909552Z svchost.exe                   1896 Services                   0     17,088 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.2927637Z svchost.exe                   3272 Services                   0      7,312 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:01 N/A                                                                     
2024-04-22T14:00:07.2954640Z spoolsv.exe                   3324 Services                   0     15,340 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2972289Z svchost.exe                   3408 Services                   0      9,224 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.2990607Z svchost.exe                   3416 Services                   0     10,352 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3009500Z IpOverUsbSvc.exe              3424 Services                   0     13,436 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3027711Z svchost.exe                   3452 Services                   0      9,788 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.3052702Z dockerd.exe                   3496 Services                   0     44,644 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:01 N/A                                                                     
2024-04-22T14:00:07.3069294Z svchost.exe                   3524 Services                   0      9,804 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3089126Z SMSvcHost.exe                 3580 Services                   0     25,004 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.3108600Z svchost.exe                   3608 Services                   0      3,892 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3128698Z mqsvc.exe                     3620 Services                   0     12,144 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.3158715Z sqlwriter.exe                 3652 Services                   0      6,396 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3176642Z svchost.exe                   3684 Services                   0      4,144 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3193271Z svchost.exe                   3720 Services                   0      7,104 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.3210474Z svchost.exe                   3728 Services                   0      8,872 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.3227745Z svchost.exe                   3784 Services                   0     11,384 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3254083Z MsMpEng.exe                   3876 Services                   0    129,756 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:02 N/A                                                                     
2024-04-22T14:00:07.3271355Z svchost.exe                   4308 Services                   0      6,324 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.3289776Z SMSvcHost.exe                 4568 Services                   0     14,948 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.3307532Z svchost.exe                   4808 Services                   0     10,932 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3327017Z svchost.exe                   4896 Services                   0      5,520 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3352151Z WaAppAgent.exe                4524 Services                   0     89,084 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:06 N/A                                                                     
2024-04-22T14:00:07.3369508Z WindowsAzureGuestAgent.ex     3032 Services                   0     62,556 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:06 N/A                                                                     
2024-04-22T14:00:07.3387639Z taskhostw.exe                 4932 Services                   0      6,156 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3405761Z svchost.exe                   2852 Services                   0      5,384 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.3422984Z WaSecAgentProv.exe            5972 Services                   0      2,512 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3448078Z conhost.exe                   5980 Services                   0      9,352 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3465702Z GenExtHealthMonitor.exe       5852 Services                   0      9,968 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3483043Z conhost.exe                   5872 Services                   0     10,784 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3503453Z svchost.exe                   3664 Services                   0      7,008 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.3521047Z MonAgentHost.exe              2808 Services                   0      7,860 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3547959Z conhost.exe                   1188 Services                   0     10,884 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:02 N/A                                                                     
2024-04-22T14:00:07.3566499Z MonAgentManager.exe           1256 Services                   0     16,556 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3585615Z CloudTest.Worker.exe          1632 Services                   0     93,408 K Unknown         cb5ae653c000001\cloudtest                               0:00:07 N/A                                                                     
2024-04-22T14:00:07.3604749Z MonAgentHost.exe              3448 Services                   0      7,728 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3623559Z MonAgentManager.exe           5156 Services                   0     26,852 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:01 N/A                                                                     
2024-04-22T14:00:07.3651195Z MonAgentCore.exe              5692 Services                   0     58,000 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:05 N/A                                                                     
2024-04-22T14:00:07.3669068Z DAExtension.exe               5836 Services                   0      6,436 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3687278Z AzurePerfCollectorExtensi     5032 Services                   0     15,400 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3705945Z AzureProfilerExtension.ex     3740 Services                   0     15,544 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3724392Z svchost.exe                   7080 Services                   0     13,212 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:01 N/A                                                                     
2024-04-22T14:00:07.3751111Z msdtc.exe                     6628 Services                   0     10,352 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:00 N/A                                                                     
2024-04-22T14:00:07.3768817Z svchost.exe                   6968 Services                   0     13,196 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3787579Z svchost.exe                   6760 Services                   0     23,692 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3806052Z svchost.exe                   6884 Services                   0     12,408 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.3824481Z svchost.exe                   5912 Services                   0      9,292 K Unknown         NT AUTHORITY\LOCAL SERVICE                              0:00:00 N/A                                                                     
2024-04-22T14:00:07.3852067Z MonAgentHost.exe              5320 Services                   0      7,748 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3870016Z MonAgentManager.exe           2772 Services                   0     25,288 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3888093Z MonAgentCore.exe              2660 Services                   0     57,996 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:03 N/A                                                                     
2024-04-22T14:00:07.3906264Z SecurityScanMgr.exe            976 Services                   0     10,228 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3924878Z EventDrivenScanner.exe        6772 Services                   0     11,620 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:12 N/A                                                                     
2024-04-22T14:00:07.3951845Z UserGroupScanner.exe          6696 Services                   0      7,576 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3967860Z NetworkSecurityScanner.ex     4960 Services                   0     11,536 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.3986276Z vmcompute.exe                 3332 Services                   0      7,528 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.4005120Z cmd.exe                       1172 Services                   0      4,584 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4024111Z conhost.exe                   1836 Services                   0     12,556 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4050976Z Agent.Listener.exe            6188 Services                   0     86,688 K Unknown         cb5ae653c000001\cloudtest                               0:00:02 N/A                                                                     
2024-04-22T14:00:07.4068026Z WmiPrvSE.exe                  6800 Services                   0     20,268 K Unknown         NT AUTHORITY\NETWORK SERVICE                            0:00:16 N/A                                                                     
2024-04-22T14:00:07.4086867Z Agent.Worker.exe              2596 Services                   0    130,344 K Unknown         cb5ae653c000001\cloudtest                               0:00:24 N/A                                                                     
2024-04-22T14:00:07.4104994Z conhost.exe                   6548 Services                   0     10,884 K Unknown         cb5ae653c000001\cloudtest                               0:00:01 N/A                                                                     
2024-04-22T14:00:07.4123782Z Agent.PluginHost.exe          2832 Services                   0     63,532 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4150414Z conhost.exe                   1404 Services                   0     10,820 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4170087Z svchost.exe                   7716 Services                   0     10,444 K Unknown         NT AUTHORITY\SYSTEM                                     0:00:00 N/A                                                                     
2024-04-22T14:00:07.4186866Z conhost.exe                   1204 Services                   0     11,048 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4205002Z git.exe                       8112 Services                   0        308 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4223127Z powershell.exe               11332 Services                   0    121,316 K Unknown         cb5ae653c000001\cloudtest                               0:00:01 N/A                                                                     
2024-04-22T14:00:07.4246264Z powershell.exe                9728 Services                   0     56,228 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4264139Z cmd.exe                       2868 Services                   0      8,292 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4281587Z tasklist.exe                  9488 Services                   0     10,280 K Unknown         cb5ae653c000001\cloudtest                               0:00:00 N/A                                                                     
2024-04-22T14:00:07.4324691Z 
2024-04-22T14:00:07.4325375Z D:\a\_work\1\s>echo "------------------------------------" 
2024-04-22T14:00:07.4325844Z "------------------------------------"
2024-04-22T14:00:07.5886474Z ##[section]Finishing: Diagnostics after smoke test run
```

At least I am not finding the code executable in this list or a node process.

**Comment by bpasero** [comment]
Could it not be the case that a previous CredScan step holds onto these files? For example, I see a `Guardian: AntiMalware Scanner` which goes into the folder that is locked: `Scanning D:\a\_work\1\s\.build\logs`

```
  Signature Update completed successfully.
  Start malware scan for -File D:\a\_work\1\s\.build\logs
  C:\ProgramData\Microsoft\Windows Defender\platform\4.18.24030.9-0\MpCmdRun.exe -Scan -ScanType 3 -DisableRemediation -File D:\a\_work\1\s\.build\logs
  Scan starting...
  Scan finished.
  Scanning D:\a\_work\1\s\.build\logs found no threats.
  Scan completed successfully for -File D:\a\_work\1\s\.build\logs.
```

**Comment by roblourens** [comment]
Same errors this time, and I also see other warnings before the ones about the log files https://dev.azure.com/monacotools/Monaco/_build/results?buildId=275518&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=16099419-18b4-5cbb-e9ba-0889f14ba93f

```
##[warning]Failed to install from source https://pkgs.dev.azure.com/monacotools/1ESPipelineTemplates/_packaging/Guardian/nuget/v3/index.json with exception System.InvalidOperationException: Package 'Microsoft.Security.CredScan.Client.win-x64 2.3.12.23' is not found in the following primary source(s): 'https://pkgs.dev.azure.com/monacotools/1ESPipelineTemplates/_packaging/Guardian/nuget/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly.
   at NuGet.PackageManagement.ResolverGather.GatherAsync(CancellationToken token)
   at NuGet.PackageManagement.ResolverGather.GatherAsync(GatherContext context, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.PreviewInstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, VersionRange versionRange, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.PreviewInstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at Microsoft.Guardian.Installers.NuGetSdkClient.Install(PackageConfig packageConfig, String outputDirectory)
```

**Comment by joaomoreno** [comment]
Same https://dev.azure.com/monacotools/Monaco/_build/results?buildId=276070&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=16099419-18b4-5cbb-e9ba-0889f14ba93f

**Comment by deepak1556** [comment]
Got a couple of runs from last week when I was build champ, link for ref

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=277802
https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=277710
https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=277351

**Comment by rzhao271** [comment]
@joaomoreno does this issue still occur?

**Comment by rzhao271** [comment]
I believe we currently have a workaround for this issue. Closing for now.
