### ISSUE TITLE
Debug: exception when "toggle skipping this file"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21112]
Steps to Reproduce:

1. debug a node application (in this case my standup app)
2. hit a "break on error" condition
3. right click into stack frame and pick "toggle skipping this file"

Console shows:

```
shell.ts:426 unrecognized request: Error: unrecognized request
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:95:2583
    at Object.v [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:11161)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:14666)
    at _run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15987)
    at _error (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15504)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:87:24010
    at g.e.dispatch (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:87:25361)
    at g.e.handleData (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:87:24869)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:87:23870)
    at emitOne (events.js:96:13)
```

**Comment by weinand** [comment]
"toggle skipping this file" is only implemented for node2 (protocol == inspector) .
node-debug does not (yet) implement this.
It should fail more gracefully.

**Comment by weinand** [comment]
The old node-debugger now shows an information message in the debug console:

![2017-02-22_18-58-08](https://cloud.githubusercontent.com/assets/1898161/23225084/ef83d9dc-f930-11e6-93dd-46bc7a26c27c.png)

The real fix is to implement "Toggle skipping this file". I've created: https://github.com/Microsoft/vscode/issues/21175
