### ISSUE TITLE
Large notebook trigger very many leak warnings 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#211112]
Testing #210961

[slow.ipynb.txt](https://github.com/microsoft/vscode/files/15079389/slow.ipynb.txt)

* open dev tools console
* open the notebook from above
* 😱 notice leak warnings from various places

This is critical: `REFUSES to accept new listeners because it exceeded its threshold by far` because it means a listener will never be used, meaning a feature is likely not working. 

This seems to be a widespread misconception and it seems each cell listens by itself. So, more cells,  more listener, leak warning and refusal to accept more listeners. Generally, listener should be used sparingly, e.g instead of each cell being a listener there should be one per notebook which dispatches onto cell.

**Comment by amunger** [comment]
One such case is for the new cellDiagnostics that I added (off by default).
https://insiders.vscode.dev/github/microsoft/vscode/blob/aamunger/focusEditor/src/vs/workbench/contrib/notebook/browser/contrib/cellDiagnostics/cellDiagnostics.ts#L62

**Comment by amunger** [comment]
need to check if these are still happening, I think I've taken care of most cases

**Comment by jrieken** [comment]
Just came across the notebook and there is still plenty of leak. Just scrolling in the notebook prints tons for leak warnings. This issue should really be prioritised because it can slow down all of vscode. Also, note that there is much related error telemetry like https://github.com/microsoft/vscode/issues/226057

**Comment by rebornix** [comment]
I think we can see if this is the same as https://github.com/microsoft/vscode/issues/211105 which renders too many toolbars.

**Comment by amunger** [comment]
got one recently 

```
  ERR [169] potential listener LEAK detected, having 177 listeners already. MOST frequent listener (2):: Error
    at Stacktrace.create (vscode-file://vscode-app/d:/src/vscode/out/vs/base/common/event.js:730:21)
    at PersistedMenuHideState._event [as onDidChange] (vscode-file://vscode-app/d:/src/vscode/out/vs/base/common/event.js:865:46)
    at Object.startLazyListener [as onWillAddFirstListener] (vscode-file://vscode-app/d:/src/vscode/out/vs/platform/actions/common/menuService.js:379:43)
    at MenuImpl._event [as onDidChange] (vscode-file://vscode-app/d:/src/vscode/out/vs/base/common/event.js:872:56)
    at CellOutputElement._attachToolbar (vscode-file://vscode-app/d:/src/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.js:284:42)
    at CellOutputElement.render (vscode-file://vscode-app/d:/src/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.js:172:18)
    at CellOutputContainer._doRender (vscode-file://vscode-app/d:/src/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.js:483:23)
    at CellOutputContainer.render (vscode-file://vscode-app/d:/src/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.js:460:18)
    at new CodeCell (vscode-file://vscode-app/d:/src/vscode/out/vs/workbench/contrib/notebook/browser/view/cellParts/codeCell.js:96:39)
    at InstantiationService._createInstance (vscode-file://vscode-app/d:/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:130:24)
```
