### ISSUE TITLE
Open editors smoke test flake

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#211270]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=270155&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a3fc59e7-8555-5b77-66bd-36e3741aa013&l=149

```
1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies opened editors are restored:
     Error: Timeout: click '.tabs-container div.tab[data-resource-name$="Untitled-1"]' after 20 seconds.
      at Code.poll (/mnt/vss/_work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitAndClick (/mnt/vss/_work/1/s/test/automation/out/code.js:154:9)
      at async Editors.selectTab (/mnt/vss/_work/1/s/test/automation/out/editors.js:28:13)
      at async Context.<anonymous> (out/areas/workbench/data-loss.test.js:34:13)
```

**Comment by bpasero** [comment]
Crashed natively: [crash-dump-linux-x64-smoke-1.zip](https://github.com/microsoft/vscode/files/15098500/crash-dump-linux-x64-smoke-1.zip)

**Comment by deepak1556** [comment]
```
Operating system: Linux
                  5.15.0 -1061-azure #70~20.04.1-Ubuntu SMP Mon Apr 8 15:38:58 UTC 2024 x86_64
CPU: amd64
     family 6 model 106 stepping 6
     4 CPUs

GPU: UNKNOWN

Crash reason:  SIGABRT
Crash address: 0x0
Process uptime: 49 seconds

Thread 0 (crashed)
 0  libc.so.6 + 0x4300b
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x00007f67e491200b   rbx = 0x00007f67e3baf0c0
    rsi = 0x00007ffd31c3a0b0   rdi = 0x0000000000000002
    rbp = 0x00007ffd31c3a310   rsp = 0x00007ffd31c3a0b0
     r8 = 0x0000000000000000    r9 = 0x00007ffd31c3a0b0
    r10 = 0x0000000000000008   r11 = 0x0000000000000246
    r12 = 0x0000000000000000   r13 = 0x0000025c016940f0
    r14 = 0x000055e1ba9802b0   r15 = 0x00007f67e4abc780
    rip = 0x00007f67e491200b
    Found by: given as instruction pointer in context
 1  code-insiders!node::OnFatalError(char const*, char const*) [node_errors.cc : 521 + 0x5]
    rbp = 0x00007ffd31c3a380   rsp = 0x00007ffd31c3a320
    rip = 0x000055e1b9f42e96
    Found by: previous frame's frame pointer
 2  code-insiders!napi_fatal_error [node_api.cc : 874 + 0x5]
    rbx = 0x00007f67354c9e5b   rbp = 0x00007ffd31c3a3e0
    rsp = 0x00007ffd31c3a390   r12 = 0x0000000000000000
    r14 = 0x0000000000000018   r15 = 0x00007f67354c75ec
    rip = 0x000055e1b9ee6c7a
    Found by: call frame info
 3  vscode-sqlite3.node!Napi::Error::Fatal(char const*, char const*) + 0x1a
    rbx = 0x00007ffd31c3a450   rbp = 0x00007ffd31c3a3f0
    rsp = 0x00007ffd31c3a3f0   r12 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000025c01683500
    rip = 0x00007f67356460ba
    Found by: call frame info
 4  vscode-sqlite3.node!Napi::Error::New(napi_env__*) + 0x159
    rbx = 0x00007ffd31c3a450   rbp = 0x00007ffd31c3a440
    rsp = 0x00007ffd31c3a400   r12 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000025c01683500
    rip = 0x00007f673564aa19
    Found by: call frame info
 5  vscode-sqlite3.node!Napi::Function::Call(napi_value__*, unsigned long, napi_value__* const*) const + 0x35
    rbx = 0x00007ffd31c3a450   rbp = 0x00007ffd31c3a490
    rsp = 0x00007ffd31c3a450   r12 = 0x0000000000000000
    r14 = 0x0000025c00c4b601   r15 = 0x0000025c01683500
    rip = 0x00007f673564ad55
    Found by: call frame info
 6  vscode-sqlite3.node!node_sqlite3::Statement::CleanQueue() + 0x53c
    rbx = 0x0000025c00efa420   rbp = 0x00007ffd31c3a580
    rsp = 0x00007ffd31c3a4a0   r12 = 0x0000000000000000
    r14 = 0x0000025c00c4b601   r15 = 0x0000025c01683500
    rip = 0x00007f673565a55c
    Found by: call frame info
 7  vscode-sqlite3.node!node_sqlite3::Statement::~Statement() + 0x2a
    rbx = 0x0000025c00efa420   rbp = 0x00007ffd31c3a5a0
    rsp = 0x00007ffd31c3a590   r12 = 0x00007ffd31c3a6b8
    r13 = 0x00007ffd31c3a6b0   r14 = 0x0000025c00c4b640
    r15 = 0x0000000000000000   rip = 0x00007f6735663eea
    Found by: call frame info
 8  vscode-sqlite3.node!node_sqlite3::Statement::~Statement() + 0xe
    rbx = 0x0000025c00efa420   rbp = 0x00007ffd31c3a5c0
    rsp = 0x00007ffd31c3a5b0   r12 = 0x00007ffd31c3a6b8
    r13 = 0x00007ffd31c3a6b0   r14 = 0x0000025c00c4b640
    r15 = 0x0000000000000000   rip = 0x00007f6735663fae
    Found by: call frame info
 9  vscode-sqlite3.node!Napi::ObjectWrap<node_sqlite3::Statement>::FinalizeCallback(napi_env__*, void*, void*) + 0x78
    rbx = 0x0000025c00efa420   rbp = 0x00007ffd31c3a630
    rsp = 0x00007ffd31c3a5d0   r12 = 0x00007ffd31c3a6b8
    r13 = 0x00007ffd31c3a6b0   r14 = 0x0000025c00c4b640
    r15 = 0x0000000000000000   rip = 0x00007f6735665a88
    Found by: call frame info
10  code-insiders!void node_napi_env__::CallbackIntoModule<true, void node_napi_env__::CallFinalizer<true>(void (*)(napi_env__*, void*, void*), void*, void*)::'lambda'(napi_env__*)>(void node_napi_env__::CallFinalizer<true>(void (*)(napi_env__*, void*, void*), void*, void*)::'lambda'(napi_env__*)&&) [node_api.cc : 48 + 0x5]
    rbx = 0x0000025c00c4b640   rbp = 0x00007ffd31c3a660
    rsp = 0x00007ffd31c3a640   r12 = 0x00007ffd31c3a6b8
    r13 = 0x00007ffd31c3a6b0   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x000055e1b9eead43
    Found by: call frame info
11  code-insiders!node_napi_env__::CallFinalizer(void (*)(napi_env__*, void*, void*), void*, void*) [node_api.cc : 47 + 0x8]
    rbx = 0x00007ffd31c3a690   rbp = 0x00007ffd31c3a6f0
    rsp = 0x00007ffd31c3a670   r12 = 0x00007ffd31c3a6b8
    r13 = 0x00007ffd31c3a6b0   r14 = 0x0000025c00c4b640
    r15 = 0x0000025c003563c0   rip = 0x000055e1b9ee5c6a
    Found by: call frame info
12  code-insiders!non-virtual thunk to v8impl::Reference::Finalize() [js_native_api_v8.cc : 679 + 0x6]
    rbx = 0x0000025c00dd52e8   rbp = 0x00007ffd31c3a720
    rsp = 0x00007ffd31c3a700   r12 = 0x0000025c00045020
    r13 = 0x00007ffd31c3aa10   r14 = 0x0000025c00dd52c0
    r15 = 0x0000000000000001   rip = 0x000055e1b9eeb61a
    Found by: call frame info
13  code-insiders!node_napi_env__::DeleteMe() [js_native_api_v8.h : 41 + 0x6]
    rbx = 0x0000025c00c4b640   rbp = 0x00007ffd31c3a740
    rsp = 0x00007ffd31c3a730   r12 = 0x0000025c00045020
    r13 = 0x00007ffd31c3aa10   r14 = 0x0000025c00364940
    r15 = 0x00007ffd31c3a758   rip = 0x000055e1b9ee58fd
    Found by: call frame info
14  code-insiders!node::CleanupQueue::Drain() [cleanup_queue.cc : 37 + 0x2]
    rbx = 0x0000025c00044fd8   rbp = 0x00007ffd31c3a7b0
    rsp = 0x00007ffd31c3a750   r12 = 0x0000025c00045020
    r13 = 0x00007ffd31c3aa10   r14 = 0x0000025c00364940
    r15 = 0x00007ffd31c3a758   rip = 0x000055e1b9e9f274
    Found by: call frame info
15  code-insiders!node::Environment::RunCleanup() [env.cc : 1022 + 0x8]
    rbx = 0x0000025c00364000   rbp = 0x00007ffd31c3aa00
    rsp = 0x00007ffd31c3a7c0   r12 = 0x0000025c002fc200
    r13 = 0x00007ffd31c3aa10   r14 = 0x0000025c00364938
    r15 = 0xaaaaaaaaaaaaaaaa   rip = 0x000055e1b9ece774
    Found by: call frame info
16  code-insiders!node::FreeEnvironment(node::Environment*) [environment.cc : 450 + 0x8]
    rbx = 0x0000025c00364000   rbp = 0x00007ffd31c3aa90
    rsp = 0x00007ffd31c3aa10   r12 = 0x0000025c002fc200
    r13 = 0x00007ffd31c3aa10   r14 = 0x0000025c00270000
    r15 = 0xaaaaaaaaaaaaaaaa   rip = 0x000055e1b9e8b44c
    Found by: call frame info
17  code-insiders!std::__Cr::__shared_ptr_pointer<node::Environment*, electron::NodeBindings::CreateEnvironment(v8::Local<v8::Context>, node::MultiIsolatePlatform*, std::__Cr::vector<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>, std::__Cr::allocator<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>>>, std::__Cr::vector<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>, std::__Cr::allocator<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>>>, std::__Cr::optional<base::RepeatingCallback<void ()>>)::$_1, std::__Cr::allocator<node::Environment>>::__on_zero_shared() [node_bindings.cc : 754 + 0x8]
    rbx = 0x0000025c0044b680   rbp = 0x00007ffd31c3aad0
    rsp = 0x00007ffd31c3aaa0   r12 = 0x0000025c0001cd00
    r13 = 0x0000000000000016   r14 = 0x0000025c00364000
    r15 = 0x00007ffd31c3aae0   rip = 0x000055e1b2dc15e9
    Found by: call frame info
18  code-insiders!electron::ElectronBrowserMainParts::PostMainMessageLoopRun() [shared_ptr.h : 173 + 0x9]
    rbx = 0x0000025c0044b680   rbp = 0x00007ffd31c3ab60
    rsp = 0x00007ffd31c3aae0   r12 = 0x0000025c0001cd00
    r13 = 0x0000000000000016   r14 = 0x000000000000002c
    r15 = 0x00007ffd31c3aae0   rip = 0x000055e1b2d185df
    Found by: call frame info
19  code-insiders!content::BrowserMainLoop::ShutdownThreadsAndCleanUp() [browser_main_loop.cc : 1145 + 0x5]
    rbx = 0x0000000000000000   rbp = 0x00007ffd31c3ac00
    rsp = 0x00007ffd31c3ab70   r12 = 0x0000025c00050840
    r13 = 0xaaaaaaaaaaaaaaaa   r14 = 0x00007ffd31c3ab00
    r15 = 0xaaaaaaaaaaaaaaaa   rip = 0x000055e1b5063c35
    Found by: call frame info
20  code-insiders!content::BrowserMainRunnerImpl::Shutdown() [browser_main_runner_impl.cc : 176 + 0x5]
    rbx = 0x0000025c000183c0   rbp = 0x00007ffd31c3ac40
    rsp = 0x00007ffd31c3ac10   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x00007ffd31c3ae00   r14 = 0x0000000000000000
    r15 = 0xaaaaaaaaaaaaaaaa   rip = 0x000055e1b50658fe
    Found by: call frame info
21  code-insiders!content::BrowserMain(content::MainFunctionParams) [browser_main.cc : 43 + 0x5]
    rbx = 0x0000000000000000   rbp = 0x00007ffd31c3acb0
    rsp = 0x00007ffd31c3ac50   r12 = 0x00007ffd31c3acc0
    r13 = 0x00007ffd31c3ae30   r14 = 0x0000025c000183c0
    r15 = 0x00007ffd31c3ac50   rip = 0x000055e1b5060fd8
    Found by: call frame info
22  code-insiders!content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) [content_main_runner_impl.cc : 713 + 0x8]
    rbx = 0x00007ffd31c3b2e0   rbp = 0x00007ffd31c3adb0
    rsp = 0x00007ffd31c3acc0   r12 = 0x00007ffd31c3acc0
    r13 = 0x00007ffd31c3ae30   r14 = 0x00007ffd31c3acf8
    r15 = 0x00007ffd31c3ad30   rip = 0x000055e1b2f4ed74
    Found by: call frame info
23  code-insiders!content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) [content_main_runner_impl.cc : 1302 + 0x8]
    rbx = 0x000017a000296530   rbp = 0x00007ffd31c3ae80
    rsp = 0x00007ffd31c3adc0   r12 = 0x00000000ffffffff
    r13 = 0x00007ffd31c3ae30   r14 = 0x00007ffd31c3ae90
    r15 = 0x00007ffd31c3adc0   rip = 0x000055e1b2f50560
    Found by: call frame info
24  code-insiders!content::ContentMainRunnerImpl::Run() [content_main_runner_impl.cc : 1152 + 0xf]
    rbx = 0x000017a000296530   rbp = 0x00007ffd31c3afa0
    rsp = 0x00007ffd31c3ae90   r12 = 0x00007ffd31c3af60
    r13 = 0xaaaaaaaaaaaaaaaa   r14 = 0x00007ffd31c3ae90
    r15 = 0x0000000000000000   rip = 0x000055e1b2f50349
    Found by: call frame info
25  code-insiders!content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) [content_main.cc : 333 + 0x8]
    rbx = 0x000017a000296530   rbp = 0x00007ffd31c3b200
    rsp = 0x00007ffd31c3afb0   r12 = 0x0000000000000000
    r13 = 0x00007ffd31c3b060   r14 = 0x0000000000000000
    r15 = 0x00007ffd31c3b091   rip = 0x000055e1b2f4dc3d
    Found by: call frame info
26  code-insiders!content::ContentMain(content::ContentMainParams) [content_main.cc : 346 + 0x8]
    rbx = 0x00007ffd31c3b280   rbp = 0x00007ffd31c3b270
    rsp = 0x00007ffd31c3b210   r12 = 0x00007ffd31c3b238
    r13 = 0x00007ffd31c3b440   r14 = 0x00007ffd31c3b230
    r15 = 0x00007ffd31c3b218   rip = 0x000055e1b2f4dd46
    Found by: call frame info
27  code-insiders!main [electron_main_linux.cc : 45 + 0x8]
    rbx = 0x00007ffd31c3b448   rbp = 0x00007ffd31c3b350
    rsp = 0x00007ffd31c3b280   r12 = 0x00007ffd31c3b2b0
    r13 = 0x00007ffd31c3b440   r14 = 0x00007ffd31c3b280
    r15 = 0x00007ffd31c3b2e0   rip = 0x000055e1b2c401d9
    Found by: call frame info
28  libc.so.6 + 0x24083
    rbx = 0x000055e1b2bdbb20   rbp = 0x0000000000000000
    rsp = 0x00007ffd31c3b360   r12 = 0x000055e1b284a000
    r13 = 0x00007ffd31c3b440   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f67e48f3083
    Found by: call frame info
29  code-insiders!ffi_closure_win64_inner + 0x330
    rsp = 0x00007ffd31c3b388   rip = 0x000055e1b2bdbb20
    Found by: stack scanning
30  ld-linux-x86-64.so.2 + 0x2f190
    rsp = 0x00007ffd31c3b3f8   rip = 0x00007f67e660a190
    Found by: stack scanning
31  code-insiders!_start + 0x2a
    rsp = 0x00007ffd31c3b430   rip = 0x000055e1b284a02a
    Found by: stack scanning
32  0x7ffd31c3b438
    rsp = 0x00007ffd31c3b438   rip = 0x00007ffd31c3b438
    Found by: call frame info
```

**Comment by deepak1556** [comment]
Crash when sqlite3 cleanup function is attempting to enter JS after Node.js environment has started shutdown. Maybe we a database call that is not destroyed before the process is exited leading to the above case. It would be ideal to fix this in the module but maybe we can ensure db calls are cleaned up before exiting the process ?

**Comment by bpasero** [comment]
We do guard against DB access when closing. I found one case which I am not sure would be the issue here, but will push a change anyway and then we need to monitor if this still happens.

https://github.com/microsoft/vscode/blob/bce484e4e4ab4315e5135f4fe1881791ed77ea46/src/vs/base/parts/storage/common/storage.ts#L296-L298
