### ISSUE TITLE
Panel chat UI glitches on scroll

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#211311]
Does this issue occur when all extensions are disabled?: Yes/No

I have seen UI issues after window reload in last few days, and this is on the latest Insiders so I wonder if it's a real regression. 

https://github.com/microsoft/vscode/assets/876920/91756c82-7e05-4f92-abb6-2d932c8d878d

**Comment by rebornix** [comment]
There is a lot of bad scroll event error 

listView.ts:1113 Got bad scroll event: Object
ib @ listView.ts:1113
listView.ts:1113 Got bad scroll event: Object
ib @ listView.ts:1113
listView.ts:1113 Got bad scroll event: Object
ib @ listView.ts:1113
listView.ts:1113 Got bad scroll event: Object
ib @ listView.ts:1113
log.ts:439   ERR Cannot read properties of undefined (reading 'length'): TypeError: Cannot read properties of undefined (reading 'length')
    at A (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:39695)
    at vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:805:18889
    at Array.some (<anonymous>)
    at vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:805:18872
    at i._computeFn (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:14503)
    at i.u (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:18524)
    at i.get (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:18338)
    at i.readObservable (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:19556)
    at i.read (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:14115)
    at i._computeFn (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:14510)
    at i.u (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:18524)
    at i.get (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:18338)
    at u.readObservable (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:13627)
    at i.read (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:14115)
    at u._runFn (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2392:75939)
    at u.k (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:12944)
    at new u (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:12650)
    at I (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:11435)
    at de.W (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2392:75920)
    at de.renderChatTreeItem (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2392:75011)
    at de.renderElement (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2392:73661)
    at A.renderElement (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:626:37111)
    at X.renderElement (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:240:2234)
    at m.Z (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:197:15986)
    at vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:197:15006
    at E.transact (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:7833)
    at m.Y (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:197:14879)
    at m.ib (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:197:20043)
    at n.y (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at n.z (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:729)
    at n.fire (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:945)
    at d.value (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:54112)
    at n.y (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at n.fire (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:876)
    at I.n (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:25627)
    at I.setScrollPositionNow (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:24625)
    at I.setScrollPositionSmooth (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:24688)
    at n.R (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:57755)
    at HTMLDivElement.$ (vscode-file://vscode-app/c:/Users/rebor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:193:56715)

**Comment by roblourens** [comment]
Should be fixed in https://github.com/microsoft/vscode/pull/211300
