### ISSUE TITLE
VS Code 中使用 Dockerfile 建立 image & container 錯誤; 一樣的 Dockerfile 內容，之前是可以成功建立

### ISSUE THREAD

**Issue by AlexYangGitHub** [microsoft/vscode#211393]
[9101 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/_5/kxgshz757k9f6zk8jmdkdvz00000gn/T/devcontainercli/container-features/0.58.0-1714082052132/Dockerfile-with-features -t vsc-readingproject-fecfab0f449ba1d49dd05429d5576c325e4aa0ac5e807dcd86d3940fb7b9884a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/Alex/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/configs/ReadingProject
[+] Building 3.6s (7/9)                                                         
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 806B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim-buster  3.4s
 => [dev_container_auto_added_stage_label 1/5] FROM docker.io/library/pyt  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 201B                                          0.0s
 => CACHED [dev_container_auto_added_stage_label 2/5] WORKDIR /app         0.0s
 => ERROR [dev_container_auto_added_stage_label 3/5] COPY requirements.tx  0.0s
------
 > [dev_container_auto_added_stage_label 3/5] COPY requirements.txt .:
------
ERROR: failed to solve: failed to compute cache key: "/requirements.txt" not found: not found
[13922 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/_5/kxgshz757k9f6zk8jmdkdvz00000gn/T/devcontainercli/container-features/0.58.0-1714082052132/Dockerfile-with-features -t vsc-readingproject-fecfab0f449ba1d49dd05429d5576c325e4aa0ac5e807dcd86d3940fb7b9884a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/Alex/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/configs/ReadingProject
[13923 ms]     at ptA (/Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:465:1933)
[13923 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[13923 ms]     at async Pm (/Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:464:1841)
[13923 ms]     at async kH (/Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:464:610)
[13923 ms]     at async UtA (/Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:481:3692)
[13923 ms]     at async $C (/Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[13923 ms]     at async QrA (/Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:661:13255)
[13924 ms]     at async urA (/Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:661:12996)
[13940 ms] Exit code 1
[13949 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/Alex/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/Alex/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-0f3df60c-a104-41c5-aa3a-6569cd46b0b31714082040830 --workspace-folder /Users/Alex/Documents/2024/ReadingProject --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/Alex/Documents/2024/ReadingProject --id-label devcontainer.config_file=/Users/Alex/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/configs/ReadingProject/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/Alex/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/configs/ReadingProject/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[13949 ms] Exit code 1

**Comment by AlexYangGitHub** [comment]
@chrmarti 
The same Dockerfile, I can build image via cmd successfully, so only problem occurs in VS code.

**Comment by AlexYangGitHub** [comment]
no follow up ?

**Comment by chrmarti** [comment]
The context is set to `/Users/Alex/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/configs/ReadingProject`. Does that folder contain a `requirements.txt`?
