### ISSUE TITLE
Crash when searching text in extension page

### ISSUE THREAD

**Issue by NeKzor** [microsoft/vscode#211413]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Linux x64 6.5.0-28-generic

Steps to Reproduce:

1. Go to extensions and search for anything
2. Click one extension in the list
3. Open search box with `CTRL+F` in the extension page and enter `asdf` as search text
4. Switch to another extension in the list
5. Observe crash when the second extension page loads

Here is what the crash looks like:

```gdb
[----------------------------------registers-----------------------------------]
RAX: 0xefefefefefefefef 
RBX: 0x21700023d100 --> 0x637b8d477830 --> 0x637b85bd6dc0 (push   rbp)
RCX: 0x1 
RDX: 0x7b3e771f0000 --> 0x0 
RSI: 0x217000efc200 --> 0xefefefefefefefef 
RDI: 0x217000efc200 --> 0xefefefefefefefef 
RBP: 0x7ffdc730fed0 --> 0x7ffdc730fef0 --> 0x7ffdc730ff40 --> 0x7ffdc730ffd0 --> 0x7ffdc7310040 --> 0x7ffdc7310060 (--> ...)
RSP: 0x7ffdc730fed0 --> 0x7ffdc730fef0 --> 0x7ffdc730ff40 --> 0x7ffdc730ffd0 --> 0x7ffdc7310040 --> 0x7ffdc7310060 (--> ...)
RIP: 0x637b8840cdeb (mov    eax,DWORD PTR [rax+0x10])
R8 : 0x20000008 
R9 : 0x0 
R10: 0x8003 
R11: 0x0 
R12: 0x217001e111c0 --> 0x0 
R13: 0x7ffdc730ff70 --> 0x217000240000 --> 0x2a9600000000 --> 0x40000 
R14: 0x217000efc200 --> 0xefefefefefefefef 
R15: 0x217000240000 --> 0x2a9600000000 --> 0x40000
EFLAGS: 0x10282 (carry parity adjust zero SIGN trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x637b8840cde0:	push   rbp
   0x637b8840cde1:	mov    rbp,rsp
   0x637b8840cde4:	mov    rax,QWORD PTR [rdi+0x110]
=> 0x637b8840cdeb:	mov    eax,DWORD PTR [rax+0x10]
   0x637b8840cdee:	pop    rbp
   0x637b8840cdef:	ret    
   0x637b8840cdf0:	push   rbp
   0x637b8840cdf1:	mov    rbp,rsp
[------------------------------------stack-------------------------------------]
0000| 0x7ffdc730fed0 --> 0x7ffdc730fef0 --> 0x7ffdc730ff40 --> 0x7ffdc730ffd0 --> 0x7ffdc7310040 --> 0x7ffdc7310060 (--> ...)
0008| 0x7ffdc730fed8 --> 0x637b85bfaf02 (mov    ebx,eax)
0016| 0x7ffdc730fee0 --> 0x101 
0024| 0x7ffdc730fee8 --> 0x21700023d100 --> 0x637b8d477830 --> 0x637b85bd6dc0 (push   rbp)
0032| 0x7ffdc730fef0 --> 0x7ffdc730ff40 --> 0x7ffdc730ffd0 --> 0x7ffdc7310040 --> 0x7ffdc7310060 --> 0x7ffdc73100c0 (--> ...)
0040| 0x7ffdc730fef8 --> 0x637b85bfc732 (test   rax,rax)
0048| 0x7ffdc730ff00 --> 0x217001e111c0 --> 0x0 
0056| 0x7ffdc730ff08 --> 0x0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x0000637b8840cdeb in ?? ()
gdb$ bt
#0  0x0000637b8840cdeb in  ()
#1  0x00007ffdc730fef0 in  ()
#2  0x0000637b85bfaf02 in  ()
#3  0x0000000000000101 in  ()
#4  0x000021700023d100 in  ()
#5  0x00007ffdc730ff40 in  ()
#6  0x0000637b85bfc732 in  ()
#7  0x0000217001e111c0 in  ()
#8  0x0000000000000000 in  ()
```

**Comment by NeKzor** [comment]
Duplicate: https://github.com/microsoft/vscode/issues/177046
