### ISSUE TITLE
Soft Assertion Failed

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#211616]
```javascript
Error: Soft Assertion Failed
at I in src/vs/base/common/assert.ts:43:21
at new r in out/vs/workbench/workbench.desktop.main.js:693:52249
at <anonymous> in src/vs/editor/browser/widget/diffEditor/diffEditorViewModel.ts:177:15
at Array.map (<anonymous>)
at M in src/vs/editor/browser/widget/diffEditor/diffEditorViewModel.ts:174:8
at updateUnchangedRegions in src/vs/editor/browser/widget/diffEditor/diffEditorViewModel.ts:308:5
at fn in src/vs/base/common/observableInternal/base.ts:282:3
at <anonymous> in out/vs/workbench/workbench.desktop.main.js:693:49164
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=e170252f762678dec6ca2cc69aba1570769a5d39&bH=858f65c8-50fe-d073-2e8e-fec58812e7dc)

**Comment by aiday-mar** [comment]
Error received over 200 times on 1.92 insiders. The corresponding issue will be marked as triaged in the error telemetry.
