### ISSUE TITLE
Notebook background broken after vscode restart

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#211841]
The whole notebook background is gray. I think after I relaunched vscode, but I don't have a specific repro. Please, feel free to close if this is not actionable. 

https://github.com/microsoft/vscode/assets/16353531/3206a7ec-f7ff-43df-99da-fb5c40c8ad0b

The dev console contains which must be relevant: 

```
  ERR Error: Notebook too large to backup
    at o.snapshot (notebookEditorModel.ts:282:12)
    at async h.backup (storedFileWorkingCopy.ts:816:14)
    at async workingCopyBackupTracker.ts:189:21
```

**Comment by rebornix** [comment]
@ulugbekna I'm responding to this issue late. Do you still have the notebook you were exploring at the time? Do you happen to have large outputs generated by execution?

**Comment by ulugbekna** [comment]
> Do you still have the notebook you were exploring at the time? 

I don't

>  Do you happen to have large outputs generated by execution?

Yes, one cell had very large output.
