### ISSUE TITLE
terminal smoke test failure

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#212288]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=272459
Changes: https://github.com/Microsoft/vscode/compare/89ee8b8...89ee8b8

```
1) VSCode Smoke Tests (Electron)
       Terminal
         Terminal Shell Integration
           Write data-based tests
             "after all" hook in "Write data-based tests":
     Error: Timeout: is active element ' .monaco-editor[data-uri$="settings.json"] textarea' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForActiveElement (D:\a\_work\1\s\test\automation\out\code.js:166:9)
      at async Editor.waitForEditorFocus (D:\a\_work\1\s\test\automation\out\editor.js:68:9)
      at async SettingsEditor.openUserSettingsFile (D:\a\_work\1\s\test\automation\out\settings.js:50:9)
      at async SettingsEditor.clearUserSettings (D:\a\_work\1\s\test\automation\out\settings.js:41:9)
      at async Context.<anonymous> (out\areas\terminal\terminal-shellIntegration.test.js:92:17)
```

**Comment by Tyriar** [comment]
This may have been related to early edit context work? Haven't seen any time recently.
