### ISSUE TITLE
Broken explorer view in vscode.dev with release/1.89

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#212244]
Extracted from https://github.com/microsoft/vscode/issues/211832#issuecomment-2099950572

```
ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-vfs://github/microsoft/vscode'
    at s.j (https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:14872)
    at async s.bb (https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:26064)
    at async https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:25772
workbench.web.main.js:653   ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-vfs://github/microsoft/vscode/.vscode/extensions'
    at s.j (https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:14872)
    at async s.bb (https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:26064)
    at async https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:25772
workbench.web.main.js:653   ERR ENOPRO: No file system provider found for resource 'vscode-vfs://github/microsoft/vscode': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-vfs://github/microsoft/vscode'
    at s.j (https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:14872)
    at async s.exists (https://main.vscode-cdn.net/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/workbench.web.main.js:655:17079)
    at async Promise.all (index 0)
    at async 
```

**Comment by deepak1556** [comment]
Hmm seems this happens with previous `1.89.0` commit as well, `https://vscode.dev/github/microsoft/vscode?vscode-version=b58957e67ee1e712cebf466b995adf4c5307b2bd`. So unrelated from the candidate changes. Passing to @joaomoreno for further triaging.
