### ISSUE TITLE
Windows: `node-gyp` install fails with latest node.js

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#212240]
This code needs `shell: true` to work in latest node.js versions:

https://github.com/microsoft/vscode/blob/df41a938ef73307844e58b8ad430a013f46d1514/build/npm/preinstall.js#L102-L106

But even adding it, fails for me with:

```
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.17s.
node:child_process:929
    throw err;
    ^

<ref *1> Error: spawnSync C:\Users\benjpas\vscode\build\npm\gyp\node_modules\.bin\node-gyp.cmd EINVAL
    at Object.spawnSync (node:internal/child_process:1117:20)
    at spawnSync (node:child_process:876:24)
    at Object.execFileSync (node:child_process:919:15)
    at installHeaders (C:\Users\benjpas\vscode\build\npm\preinstall.js:119:20)
    at Object.<anonymous> (C:\Users\benjpas\vscode\build\npm\preinstall.js:53:3)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawnSync C:\\Users\\benjpas\\vscode\\build\\npm\\gyp\\node_modules\\.bin\\node-gyp.cmd',
  path: 'C:\\Users\\benjpas\\vscode\\build\\npm\\gyp\\node_modules\\.bin\\node-gyp.cmd',
  spawnargs: [ 'list' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}

Node.js v18.20.2
```

**Comment by bpasero** [comment]
Oh wow, this even goes way beyond:

```
PS C:\Users\benjpas\vscode> yarn
yarn install v1.22.22
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@microsoft/1ds-core-js > @microsoft/applicationinsights-core-js@2.8.15" has unmet peer dependency "tslib@*".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/bazelisk@>=1.7.5".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[4/4] Building fresh packages...
[1/21] ⠠ @parcel/watcher
[2/21] ⠠ @vscode/policy-watcher
[3/21] ⠠ @vscode/windows-ca-certs
[4/21] ⠠ @vscode/ripgrep
error C:\Users\benjpas\vscode\node_modules\@parcel\watcher: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: C:\Users\benjpas\vscode\node_modules\@parcel\watcher
Output:
node:internal/child_process:414
    throw errnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at Object.spawn (node:child_process:761:9)
    at build (C:\Users\benjpas\vscode\node_modules\node-gyp-build\bin.js:29:8)
    at preinstall (C:\Users\benjpas\vscode\node_modules\node-gyp-build\bin.js:38:32)
    at Object.<anonymous> (C:\Users\benjpas\vscode\node_modules\node-gyp-build\bin.js:15:3)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
```

**Comment by bpasero** [comment]
I think we should just throw early when we detect this malformed version here:

https://github.com/microsoft/vscode/blob/df41a938ef73307844e58b8ad430a013f46d1514/build/npm/preinstall.js#L12-L20

**Comment by TobiasFaller** [comment]
> I think we should just throw early when we detect this unsupported version here:
> 
> https://github.com/microsoft/vscode/blob/df41a938ef73307844e58b8ad430a013f46d1514/build/npm/preinstall.js#L12-L20

The issue is present on latest Node.JS 20 LTS (v20.13.1) and latest Node.JS 18 LTS (v18.20.2).
Using Node.JS 18.14.2 and using VSCODE_SKIP_NODE_VERSION_CHECK resolved the issue for me.

**Comment by dbaeumer** [comment]
I have a fix ready for this in branch: dbaeumer/mighty-silverfish-ivory

But want to first get @deepak1556 opinion as well.

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/0e1e8fee84f8590e834547b29f87bde333270c33
