### ISSUE TITLE
vscode\node_modules\@vscode\policy-watcher\build\Release\vscode-policy-watcher.node is not a valid Win32 application

### ISSUE THREAD

**Issue by imp-oh** [microsoft/vscode#212533]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

[main 2024-05-12T05:24:04.395Z] Error: \\?\F:\Text\vscode\node_modules\@vscode\policy-watcher\build\Release\vscode-policy-watcher.node is not a valid Win32 application.
\\?\F:\Text\vscode\node_modules\@vscode\policy-watcher\build\Release\vscode-policy-watcher.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at bindings (F:\Text\vscode\node_modules\bindings\bindings.js:112:48)        
    at Object.<anonymous> (F:\Text\vscode\node_modules\@vscode\policy-watcher\index.js:6:44)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at nodeRequire (file:///F:/Text/vscode/src/vs/loader.js:1025:12)
    at NodeScriptLoader.load (file:///F:/Text/vscode/src/vs/loader.js:823:22)    
    at OnlyOnceScriptLoader.load (file:///F:/Text/vscode/src/vs/loader.js:581:23)
    at loadNextPath (file:///F:/Text/vscode/src/vs/loader.js:1620:25)
    at Object.errorback (file:///F:/Text/vscode/src/vs/loader.js:1628:7)
    at OnlyOnceScriptLoader.triggerErrorback (file:///F:/Text/vscode/src/vs/loader.js:594:24)
    at file:///F:/Text/vscode/src/vs/loader.js:581:107
    at NodeScriptLoader.load (file:///F:/Text/vscode/src/vs/loader.js:826:6)     
    at OnlyOnceScriptLoader.load (file:///F:/Text/vscode/src/vs/loader.js:581:23)
    at loadNextPath (file:///F:/Text/vscode/src/vs/loader.js:1620:25)
    at ModuleManager._loadModule (file:///F:/Text/vscode/src/vs/loader.js:1632:4)
    at ModuleManager._resolve (file:///F:/Text/vscode/src/vs/loader.js:1715:11)  
    at ModuleManager.defineModule (file:///F:/Text/vscode/src/vs/loader.js:1369:9)
    at ModuleManager._relativeRequire (file:///F:/Text/vscode/src/vs/loader.js:1403:9)
    at result (file:///F:/Text/vscode/src/vs/loader.js:1574:17)
    at F:\Text\vscode\out\vs\platform\policy\node\nativePolicyService.js:28:84   
    at new Promise (<anonymous>)
    at NativePolicyService._updatePolicyDefinitions (F:\Text\vscode\out\vs\platform\policy\node\nativePolicyService.js:28:45)
    at NativePolicyService.updatePolicyDefinitions (F:\Text\vscode\out\vs\platform\policy\common\policy.js:22:28)
    at PolicyConfiguration.updatePolicyDefinitions (F:\Text\vscode\out\vs\platform\configuration\common\configurations.js:116:42)
    at PolicyConfiguration.initialize (F:\Text\vscode\out\vs\platform\configuration\common\configurations.js:89:36)
    at ConfigurationService.initialize (F:\Text\vscode\out\vs\platform\configuration\common\configurationService.js:27:144)
    at CodeMain.initServices (F:\Text\vscode\out\vs\code\electron-main\main.js:160:38)
    at ModuleManager._onModuleComplete (file:///F:/Text/vscode/src/vs/loader.js:1773:12)
    at ModuleManager._onModuleComplete (file:///F:/Text/vscode/src/vs/loader.js:1773:12)
    at ModuleManager._onModuleComplete (file:///F:/Text/vscode/src/vs/loader.js:1773:12)
    at ModuleManager._onModuleComplete (file:///F:/Text/vscode/src/vs/loader.js:1773:12)
    at ModuleManager._resolve (file:///F:/Text/vscode/src/vs/loader.js:1719:10)
    at ModuleManager.defineModule (file:///F:/Text/vscode/src/vs/loader.js:1369:9)
    at ModuleManager._onLoad (file:///F:/Text/vscode/src/vs/loader.js:1448:10)
    at Object.callback (file:///F:/Text/vscode/src/vs/loader.js:1625:12)
    at OnlyOnceScriptLoader.triggerCallback (file:///F:/Text/vscode/src/vs/loader.js:587:24)
    at file:///F:/Text/vscode/src/vs/loader.js:581:65
    at NodeScriptLoader._createAndEvalScript (file:///F:/Text/vscode/src/vs/loader.js:873:5)
    at file:///F:/Text/vscode/src/vs/loader.js:852:26
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)

win11 x64  How to solve this problem

**Comment by imp-oh** [comment]
node-gyp rebuild --target_arch=ia32

**Comment by imp-oh** [comment]
Used in project command
```sh
node-gyp rebuild --target_arch=ia32
```
