### ISSUE TITLE
Bad chat layout after updating to latest Insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#212749]
Today I updated Insiders and got this chat layout:

![image](https://github.com/microsoft/vscode/assets/2230985/9efed5d3-e771-4a89-8352-43ec31228bd5)

There's no scrollbar to get to the chat box. Error stack:

```
splitview.ts:288 TypeError: Cannot read properties of undefined (reading 'length')
    at A (strings.ts:424:24)
    at chatAgents.ts:464:32
    at Array.some (<anonymous>)
    at chatAgents.ts:464:21
    at h._computeFn (base.ts:231:16)
    at h.get (derived.ts:226:24)
    at m (chatMarkdownDecorationsRenderer.ts:43:72)
    at chatMarkdownDecorationsRenderer.ts:90:68
    at b.invokeFunction (instantiationService.ts:106:11)
    at E.convertParsedRequestToMarkdown (chatMarkdownDecorationsRenderer.ts:90:41)
    at fe.renderChatTreeItem (chatListRenderer.ts:385:38)
    at fe.renderElement (chatListRenderer.ts:313:8)
    at A.renderElement (abstractTree.ts:418:17)
    at Q.renderElement (listWidget.ts:1249:13)
    at p.xb (listView.ts:1538:12)
    at p.wb (listView.ts:1439:23)
    at p.layout (listView.ts:840:10)
    at J.layout (listWidget.ts:1682:13)
    at Z.layout (abstractTree.ts:2758:13)
    at O.layout (chatWidget.ts:782:13)
    at p.X (chatViewPane.ts:206:16)
    at p.layout (paneview.ts:302:9)
    at l.layout (splitview.ts:285:14)
    at n.U (splitview.ts:1361:13)
    at n.layout (splitview.ts:877:8)
    at o.layout (paneview.ts:593:18)
    at A.layout (viewPaneContainer.ts:641:18)
    at O.layout (panecomposite.ts:57:27)
    at f.layout (compositePart.ts:504:25)
    at f.layout (paneCompositePart.ts:541:9)
    at f.layout (sidebarPart.ts:158:9)
    at n.y (gridview.ts:927:13)
    at n.layout (gridview.ts:910:8)
    at u.layout (splitview.ts:285:14)
    at n.U (splitview.ts:1361:13)
    at n.layout (splitview.ts:877:8)
    at a.layout (gridview.ts:494:18)
    at l.layout (splitview.ts:285:14)
    at n.U (splitview.ts:1361:13)
    at n.layout (splitview.ts:877:8)
    at a.layout (gridview.ts:494:18)
    at g.layout (gridview.ts:1196:13)
    at r.layout (grid.ts:338:17)
    at r.layout (grid.ts:853:9)
    at H.layout (layout.ts:1573:23)
    at window.ts:145:95
```

**Comment by roblourens** [comment]
Was fixed a couple days ago
