### ISSUE TITLE
error Error: https://github.com/microsoft/node-sqlite3/releases/download/v5.1.6-bins/sqlite3-v5.1.6-napi-v3-linux-x64.tar.gz: Request failed "404 Not Found"

### ISSUE THREAD

**Issue by IntegerAlex** [microsoft/vscode#213039]
- VS Code Version: 
- OS Version:  debian12

ON Building from source 
yarn
yarn install v1.22.22
$ node build/npm/preinstall.js
[1/4] Resolving packages...
Couldn't find any versions for "native-keymap" that matches "3.4.0"
? Please choose a version of "native-keymap" from this list: 3.3.3
Couldn't find any versions for "node-pty" that matches "^0.11.1"
? Please choose a version of "node-pty" from this list: 0.10.1
error Error: https://github.com/microsoft/node-sqlite3/releases/download/v5.1.6-bins/sqlite3-v5.1.6-napi-v3-linux-x64.tar.gz: Request failed "404 Not Found"
    at ResponseError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/usr/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:66750:16)
    at Request.emit (node:events:519:28)
    at module.exports.Request.onRequestResponse (/usr/lib/node_modules/yarn/lib/cli.js:142287:10)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:519:28)

**Comment by IntegerAlex** [comment]
There is no Downloads endpoint in [https://github.com/microsoft/node-sqlite3/releases/](https://github.com/microsoft/node-sqlite3/releases/download/) instead there is endpoint  ' tags ' [tags endpoint ](https://github.com/microsoft/vscode-node-sqlite3/releases/tag/v5.1.6-vscode)

**Comment by andreamah** [comment]
Does this happen on the latest main, even after you run a git clean? `git clean -xfd`

**Comment by andreamah** [comment]
Unfortunately, we don't support issues regarding building code-oss (source) in this issue tracker :( Perhaps you can look up the issue somewhere like StackOverflow? I haven't seen this, and I'm on node v20.13.1
