### ISSUE TITLE
VS Code node server crashes on remote Linux due to VS Code remote SSH PHP development

### ISSUE THREAD

**Issue by archon810** [microsoft/vscode#213173]
Does this issue occur when all extensions are disabled?: Unclear, due to issue happening sporadically, every few days.

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Have remote SSH extensions as well as PHP development extensions installed. Like PHP Debug (by xdebug), PHP Intelephense, Remote Development, Remote SSH.
2. Have VSC open with a decently large remote PHP project and leave it open for a few days.
3. Sometimes every day, sometimes every several days observe a node crash with a large 4.5GB core file on the remote Linux system. I tried installing as many debug symbols as I could to produce a gdb bt and got this:
```
gdb /home/archon810/.vscode-server/cli/servers/Stable-b58957e67ee1e712cebf466b995adf4c5307b2bd/server/node core.node.10*
GNU gdb (GDB; devel:gcc) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/archon810/.vscode-server/cli/servers/Stable-b58957e67ee1e712cebf466b995adf4c5307b2bd/server/node...

warning: Can't open file /var/run/nscd/db0KeEPE (deleted) during file-backed mapping note processing
[New LWP 10578]
[New LWP 10580]
[New LWP 10582]
[New LWP 10579]
[New LWP 10586]
[New LWP 10585]
[New LWP 10591]
[New LWP 10592]
[New LWP 10587]
[New LWP 10593]
[New LWP 10581]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/archon810/.vscode-server/cli/servers/Stable-b58957e67ee1e712cebf466b995ad'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fdb0bb07d2b in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7fdb0c0ba7c0 (LWP 10578))]
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.31-150300.63.1.x86_64
(gdb) bt
#0  0x00007fdb0bb07d2b in raise () from /lib64/libc.so.6
#1  0x00007fdb0bb093e5 in abort () from /lib64/libc.so.6
#2  0x0000000000b85bd1 in node::Abort() ()
#3  0x0000000000a94834 in node::OOMErrorHandler(char const*, bool) ()
#4  0x0000000000d66d10 in v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) ()
#5  0x0000000000d670b7 in v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) ()
#6  0x0000000000f447c5 in v8::internal::Heap::FatalProcessOutOfMemory(char const*) ()
#7  0x0000000000f456c8 in v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) ()
#8  0x0000000000f55bd3 in v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [clone .constprop.1331] ()
#9  0x0000000000f56a48 in v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) ()
#10 0x0000000000f59c15 in v8::internal::Heap::HandleGCRequest() ()
#11 0x0000000000ed7d6f in v8::internal::StackGuard::HandleInterrupts() ()
#12 0x00000000012b4fc3 in v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(v8::internal::Isolate*, int, v8::internal::RegExp::CallOrigin, unsigned long*, v8::internal::Code, unsigned long*, unsigned char const**, unsigned char const**) ()
#13 0x00000000015dfc7c in v8::internal::RegExpMacroAssemblerX64::CheckStackGuardState(unsigned long*, unsigned long, unsigned long) ()
#14 0x0000000007331c44 in ?? ()
#15 0x00007fff034a29e0 in ?? ()
#16 0x0000000000f3f012 in v8::internal::Heap::MonotonicallyIncreasingTimeInMs() const ()
#17 0x00000000012b51d2 in v8::internal::NativeRegExpMacroAssembler::Execute(v8::internal::String, int, unsigned char const*, unsigned char const*, int*, int, v8::internal::Isolate*, v8::internal::JSRegExp) ()
#18 0x00000000012b52e2 in v8::internal::NativeRegExpMacroAssembler::Match(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int*, int, int, v8::internal::Isolate*) ()
#19 0x00000000012c6618 in v8::internal::RegExpImpl::IrregexpExecRaw(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, int*, int) ()
#20 0x00000000012c6b3c in v8::internal::RegExpImpl::IrregexpExec(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::RegExpMatchInfo>, v8::internal::RegExp::ExecQuirks) ()
#21 0x00000000012ebe9e in v8::internal::Runtime_RegExpExec(int, unsigned long*, v8::internal::Isolate*) ()
#22 0x0000000001705b39 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit ()
#23 0x0000000001768923 in Builtins_RegExpPrototypeTestFast ()
#24 0x00000000075d5309 in ?? ()
#25 0x00000b9d3d364909 in ?? ()
#26 0x0000000000000000 in ?? ()
(gdb) quit
```

Any ideas? Apologies if I'm filing in the wrong place or without enough information.

**Comment by roblourens** [comment]
That seems likely. Thanks for checking that out, and filing an issue on intelephense. Looks like the process is running out of memory and unfortunately it is possible for extensions to crash the EH in that way.
