### ISSUE TITLE
[aah] REFUSES to accept new listeners because it exceeded its threshold by far (<REDACTED: user-file-path>). HINT: Stack shows most frequent listener (352-times)

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#213142]
```javascript
Error
at c.create in src/vs/base/common/event.ts:900:15
at v.q in src/vs/base/common/event.ts:1095:34
at j.kb in src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:448:52
at async j.lb in src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:487:15
at async j.createProcess in src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:333:19
at async Ie.reuseTerminal in src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1723:3
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=a48f464a3e01aad384703ec964018299b14bb7cf&bH=efc9c74d-57d2-d1c6-56bc-c1fe474e1e82)

**Comment by jrieken** [comment]
see https://vscodeteam.slack.com/archives/C03ERNTC03X/p1715871789199039 for what this means
