### ISSUE TITLE
Smoke Test failure [VSCode Smoke Tests (Web)]

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#213327]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=274866&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=0024786a-41a1-59f5-7639-5f9e1aa0058c

1) VSCode Smoke Tests (Web)
       Statusbar
         verifies presence of all default status bar elements:
     Error: Timeout: get element '.statusbar-item[id^="status.scm."] .codicon.codicon-git-branch' after 20 seconds.
      at Code.poll (/mnt/vss/_work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForElement (/mnt/vss/_work/1/s/test/automation/out/code.js:163:16)
      at async StatusBar.waitForStatusbarElement (/mnt/vss/_work/1/s/test/automation/out/statusbar.js:14:9)
      at async Context.<anonymous> (out/areas/statusbar/statusbar.test.js:16:13)

**Comment by hediet** [comment]
Seems like SCM related?

**Comment by deepak1556** [comment]
Another run https://dev.azure.com/monacotools/Monaco/_build/results?buildId=277802&view=results

**Comment by lszomoru** [comment]
Pushed a fix for this. Will keep an eye on build failures for the next couple of days.
