### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getViewLineMinColumn')

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#213371]
```javascript
TypeError: Cannot read properties of undefined (reading 'getViewLineMinColumn')
at b.getViewLineMinColumn in src/vs/editor/common/viewModel/viewModelLines.ts:735:62
at m.getLineMinColumn in src/vs/editor/common/viewModel/viewModelImpl.ts:681:22
at m.getVisibleRangesPlusViewportAboveBelow in src/vs/editor/common/viewModel/viewModelImpl.ts:527:30
at V.getVisibleRangesPlusViewportAboveBelow in src/vs/editor/browser/widget/codeEditor/codeEditorWidget.ts:515:36
at c.t in src/vs/editor/contrib/semanticTokens/browser/viewportSemanticTokens.ts:122:38
at x.a in src/vs/editor/contrib/semanticTokens/browser/viewportSemanticTokens.ts:51:75
at x.h in out/vs/workbench/workbench.desktop.main.js:152:20100
at x.g in src/vs/base/common/async.ts:1017:9
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=dc96b837cf6bb4af9cd736aa3af08cf8279f7685&bH=d344874c-8c36-a2e1-b44f-db420d6ec591)

**Comment by hediet** [comment]
* This is triggered by `RunOnceScheduler`
* `this._editor.hasModel()` seems to pass after that
* `modelLineProjections[startViewLineNumber  - 1]` does not seem to be defined?

This is very weird. Maybe one of the `setSemanticTokens` methods fires an event, where a listener resets the model/flushes the view?
