### ISSUE TITLE
f.actions.map is not a function

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#213368]
```javascript
TypeError: f.actions.map is not a function
at <anonymous> in src/vs/workbench/contrib/codeActions/common/codeActionsExtensionPoint.ts:91:26
at Array.map (<anonymous>)
at $.render in src/vs/workbench/contrib/codeActions/common/codeActionsExtensionPoint.ts:90:16
at U.u in src/vs/workbench/contrib/extensions/browser/extensionFeaturesTab.ts:451:45
at U.s in src/vs/workbench/contrib/extensions/browser/extensionFeaturesTab.ts:437:10
at new U in src/vs/workbench/contrib/extensions/browser/extensionFeaturesTab.ts:379:8
at b.o in src/vs/platform/instantiation/common/instantiationService.ts:159:18
at b.createInstance in src/vs/platform/instantiation/common/instantiationService.ts:125:18
at j.D in src/vs/workbench/contrib/extensions/browser/extensionFeaturesTab.ts:265:54
at d.value in src/vs/workbench/contrib/extensions/browser/extensionFeaturesTab.ts:201:10
at s.y in src/vs/base/common/event.ts:1156:13
at s.z in src/vs/base/common/event.ts:1167:9
at s.fire in src/vs/base/common/event.ts:1191:9
at <anonymous> in src/vs/base/common/event.ts:127:84
at d.value in src/vs/base/common/event.ts:1578:15
at s.y in src/vs/base/common/event.ts:1156:13
at s.fire in src/vs/base/common/event.ts:1187:9
at a.h in src/vs/base/browser/ui/list/listWidget.ts:184:18
at a.set in src/vs/base/browser/ui/list/listWidget.ts:171:15
at q.setSelection in src/vs/base/browser/ui/list/listWidget.ts:1696:18
at H.u in src/vs/base/browser/ui/list/listWidget.ts:781:14
at d.value in src/vs/base/common/event.ts:178:85
at s.y in src/vs/base/common/event.ts:1156:13
at s.fire in src/vs/base/common/event.ts:1187:9
at d.value in src/vs/base/common/event.ts:127:84
at s.y in src/vs/base/common/event.ts:1156:13
at s.fire in src/vs/base/common/event.ts:1187:9
at HTMLDivElement.C in src/vs/base/browser/event.ts:40:41
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=dc96b837cf6bb4af9cd736aa3af08cf8279f7685&bH=a658183a-20ae-da6d-059b-195448ced9b5)

**Comment by sandy081** [comment]
@mjbvz Rendering extension points in the extension editor is made contribution model. I have adopted it for your extension point. But it seems these extension points may be invalid. Can you please validate your contribution point rendering?
