### ISSUE TITLE
Test language model access API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#213552]
Refs: https://github.com/microsoft/vscode/issues/206265, https://github.com/microsoft/vscode/issues/204266

- [ ] anyOS
- [ ] anyOS

Complexity: 4

---

We have finalised an API to access language models so that chat request can be performed even outside of chat participation. This API is now finalised and you should make sure

* the API can just be used without enrolling into a proposal (use `npx vscode-dts main` to retrieve latest vscode.d.ts)
* the API is properly documented
* the API works as advertised and is straight-forward to use

You can start with https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample. Note that you also need copilot-chat installed for this to work but the API must not error when chat isn't installed/enabled.

**Comment by meganrogge** [comment]
@roblourens / @jrieken how would you suggest testing `onDidChangeChatModels`? I placed that at the top of the `activation`, with a `console.log` and am not seeing it - maybe because the models are already available by that time?

**Comment by roblourens** [comment]
When does your extension activate? Copilot Chat activates immediately so the models are probably available pretty quickly. You can check that or register new models with the `registerChatResponseProvider` API or hack vscode-copilot to slow down model registration

**Comment by meganrogge** [comment]
here's what I tried:

```
	vscode.lm.onDidChangeChatModels(async (e) => {
		const models = await vscode.lm.selectChatModels();
		console.log('Chat models changed', models);
	});
	const provider = {
		provideLanguageModelResponse(messages: vscode.LanguageModelChatMessage[], options: { [name: string]: any }, extensionId: string, progress: vscode.ChatResponseFragment, token: vscode.CancellationToken): Thenable<any> {
			return Promise.resolve();
		},
		provideTokenCount(text: string | vscode.LanguageModelChatMessage, token: vscode.CancellationToken): Thenable<number> {
			return Promise.resolve(3000);
		}
	};
	vscode.chat.registerChatResponseProvider(
		'chat-sample.cat2',
		provider,
		{}
	);
```
and am seeing 
```
ERR Chat response provider uses UNKNOWN vendor vscode-samples.chat-sample.: Error: Chat response provider uses UNKNOWN vendor vscode-samples.chat-sample.
    at i.registerLanguageModelChat (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1639:20606)
    at i.$registerLanguageModelProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1651:1412)
    at y.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:14598)
    at y.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:14364)
    at y.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:13397)
    at y.L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:12232)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:10928)
    at h.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at h.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:89:876)
    at r.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:615:14848)
    at U.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1673:8154)
```

how did you test `onDidChangeChatModels`?

**Comment by roblourens** [comment]
Looks like there is a static contribution point for language models, eg in vscode-copilot

```
"languageModels": {
	"vendor": "copilot"
},
```

and aren't you getting an error for the missing required props in `ChatResponseProviderMetadata`?

**Comment by meganrogge** [comment]
@roblourens i am out tomorrow, so this should probably have a different tester
