### ISSUE TITLE
Switching profile shows a progress badge on explorer that never ends

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#214203]
<img width="436" alt="image" src="https://github.com/microsoft/vscode/assets/900690/330ee053-1ff4-4959-a553-88911c8681e5">

I am in a multi-root workspace and switch to an empty profile.

**Comment by bpasero** [comment]
Maybe related to this? Its possible that some code triggers a long running op reporting progress on the explorer:

```
ERR Canceled: Canceled
    at new S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1644:52029)
    at y.U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:14635)
    at W.<computed>.F.charCodeAt.D.CharCode.DollarSign.W.<computed> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1658:11737)
    at f.getSessions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1644:64696)
    at i.getSessions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1637:13989)
    at U.Kb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2314:4414)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2314:2557
    at Array.map (<anonymous>)
    at U.Fb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2314:2544)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2314:2447
```

**Comment by sandy081** [comment]
@lramos15 I suppose this has to do with the Explorer, please take a look.

**Comment by bpasero** [comment]
Not seeing anymore.
