### ISSUE TITLE
Unit test: throw ListenerLeakError failure

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#214218]
Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=276696&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=c64bf68a-a40a-513c-efca-4af37a9b3e94

```
Error
at Stacktrace.create (D:\a\_work\1\s\out-build\vs\base\common\event.js:694:25)
at $ie.q (D:\a\_work\1\s\out-build\vs\base\common\event.js:839:50)
at Context.<anonymous> (D:\a\_work\1\s\out-build\vs\base\test\common\event.test.js:289:19)
at callFn (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:366:21)
at Runnable.run (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:354:5)
at Runner.runTest (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:666:10)
at D:\a\_work\1\s\node_modules\mocha\lib\runner.js:789:12
at next (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:581:14)
at D:\a\_work\1\s\node_modules\mocha\lib\runner.js:591:7
at next (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:474:14)
at cbHookRun (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:539:7)
at done (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:310:5)
at callFn (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:389:7)
at Runnable.run (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:354:5)
at next (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:498:10)
at cbHookRun (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:539:7)
at done (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:310:5)
at callFn (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:389:7)
at Runnable.run (D:\a\_work\1\s\node_modules\mocha\lib\runnable.js:354:5)
at next (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:498:10)
at Immediate._onImmediate (D:\a\_work\1\s\node_modules\mocha\lib\runner.js:559:5)
at process.processImmediate (node:internal/timers:478:21)
[0e1] REFUSES to accept new listeners because it exceeded its threshold by far (10 vs 3)
```

**Comment by jrieken** [comment]
Closing as fluke but might also have been unexpected output which by now is explicitly allowed for this test ([reference](https://github.com/microsoft/vscode/blob/0c7bdaaae9b654d97ee5b212bbf4b81bd871540f/test/unit/electron/renderer.js#L208))
