### ISSUE TITLE
Exception in fileActions.ts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#21460]
- VSCode Version: 1.10 b2a55bd66eb60af11c60ddd61b7581538b216051

**Repo Steps**
Not sure of the exact repo steps but this occurred while pasting text from one file to another

```
shell.ts:426 Cannot read property 'item' of undefined: TypeError: Cannot read property 'item' of undefined
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:128:17875
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17420)
    at t.pasteIntoFocusedFilesExplorerViewItem (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:128:17854)
    at t.invokeFunction (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:25305)
    at t._tryExecuteCommand (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:12482)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:12182
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17420)
    at t.executeCommand (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:12156)
    at t.e._dispatch (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:65:30806)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:103:14632
```

```
TypeError: Cannot read property 'item' of undefined
    at fileActions.ts:992
    at then (winjs.base.raw.js:1566)
    at t.pasteIntoFocusedFilesExplorerViewItem (fileActions.ts:991)
    at t.invokeFunction (instantiationService.ts:58)
    at t._tryExecuteCommand (commandService.ts:51)
    at commandService.ts:39
    at then (winjs.base.raw.js:1566)
    at t.executeCommand (commandService.ts:39)
    at t.e._dispatch (abstractKeybindingService.ts:163)
    at keybindingService.ts:162
```

**Comment by bpasero** [comment]
@mjbvz first of all, how did you manage to convert a minified stack-trace into readable form with the actual line numbers?

I pushed a fix for the NPE but still, this should not happen: It looks like you managed to trigger the paste action of the explorer even though as you say the explorer did not have focus (or did it?). If you can somehow reproduce this, please let me know how you triggered it. The paste action should only trigger if the explorer (files explorer) has focus.

**Comment by bpasero** [comment]
@mjbvz ah nevermind I can reproduce and funny that the deminified stacktrace shows up right below:

![image](https://cloud.githubusercontent.com/assets/900690/23350703/bb9efb76-fcbc-11e6-9bbe-41ad6236cfe8.png)

Steps:
* copy an item in the explorer
* unselect all items from the explorer (you should see the blue outline around the entire tree)
* paste

=> you get the exception
=> there is still a regression that pasting does not work in this case (it used to work). Filed https://github.com/Microsoft/vscode/issues/21469
