### ISSUE TITLE
Flaky Test: Terminal - Terminal Persistence - detach/attach - should persist buffer content

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#216464]
1) VSCode Smoke Tests (Electron)
       Terminal
         Terminal Persistence
           detach/attach
             should persist buffer content:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:163:16)
      at async QuickInput.waitForQuickInputClosed (/Users/runner/work/1/s/test/automation/out/quickinput.js:32:9)
      at async Terminal.runCommandWithValue (/Users/runner/work/1/s/test/automation/out/terminal.js:109:9)
      at async Context.<anonymous> (out/areas/terminal/terminal-persistence.test.js:64:17)

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=278997&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=dc7a7a05-ae89-521b-55db-0cb2ded34668

**Comment by meganrogge** [comment]
```
1) VSCode Smoke Tests (Electron)
       Terminal
         Terminal Persistence
           detach/attach
             should persist buffer content:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForTerminalBuffer (D:\a\_work\1\s\test\automation\out\code.js:175:9)
      at async Terminal.waitForTerminalText (D:\a\_work\1\s\test\automation\out\terminal.js:262:13)
      at async Context.<anonymous> (out\areas\terminal\terminal-persistence.test.js:68:17)

```

**Comment by meganrogge** [comment]
Fails on windows bc of line wrapping differences

Before detaching:

![Image](https://github.com/user-attachments/assets/b792c032-4b30-4fa9-8cb3-434008db4c6c)

After attaching:

![Image](https://github.com/user-attachments/assets/c6950dad-5053-4aef-8994-908c4beed672)

**Comment by meganrogge** [comment]
i think we should change the test so that it doesn't care about new lines

**Comment by meganrogge** [comment]
wondering if we also need to match `\r` for windows

**Comment by alexr00** [comment]
Looks like it's still failing. Skipping to unblock the build.

**Comment by meganrogge** [comment]
Thanks @alexr00

**Comment by meganrogge** [comment]
I'm out of ideas for how to fix this, think it should remain skipped to prevent build failures

**Comment by Tyriar** [comment]
Disabled in code atm, we'll do a push to clean up the smoke tests at some point.
