### ISSUE TITLE
Inline Chat - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#216693]
1. New untitled file
2. Open inline chat -> "/fix missing header"
3. Get an error "Cannot read properties of undefined (reading 'length')" 🐛 

![Image](https://github.com/user-attachments/assets/09468f9b-4ca8-4fd5-b255-9cab5c04bc71)

**Comment by jrieken** [comment]
Nice stack trace

```
TypeError: Cannot read properties of undefined (reading 'length')
    at getIndentLength (/Users/jrieken/Code/vscode-copilot/src/extension/prompts/node/inline/patchEditGeneration.tsx:204:18)
    at findEdit (/Users/jrieken/Code/vscode-copilot/src/extension/prompts/node/inline/patchEditGeneration.tsx:112:35)
    at Object.process (/Users/jrieken/Code/vscode-copilot/src/extension/prompts/node/inline/patchEditGeneration.tsx:344:18)
    at Fix3ReplyInterpreter.finish (/Users/jrieken/Code/vscode-copilot/src/extension/prompts/node/inline/inlineChatFix3Prompt.tsx:191:36)
    at CopilotInteractiveEditorSessionProvider.fetchResponse (/Users/jrieken/Code/vscode-copilot/src/extension/inlineChat/node/inlineChat.ts:587:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CopilotInteractiveEditorSessionProvider.provideInteractiveEditorResponse (/Users/jrieken/Code/vscode-copilot/src/extension/inlineChat/node/inlineChat.ts:256:20)
    at ChatAgents.handleCommonInlineChatRequest (/Users/jrieken/Code/vscode-copilot/src/extension/conversation/vscode-node/chatParticipants.ts:393:18)
```

**Comment by jrieken** [comment]
Thanks @isidorn
