### ISSUE TITLE
Flaky smoke test: Task Quick Pick

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#216639]
1) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon & color:
     Error: Timeout: get text content ' .monaco-editor[data-uri$="tasks.json"] .view-lines' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForTextContent (/Users/runner/work/1/s/test/automation/out/code.js:151:16)
      at async Editor.waitForTypeInEditor (/Users/runner/work/1/s/test/automation/out/editor.js:79:9)
      at async Task.configureTask (/Users/runner/work/1/s/test/automation/out/task.js:68:13)
      at async Context.<anonymous> (out/areas/task/task-quick-pick.test.js:52:17)

**Comment by meganrogge** [comment]
/duplicate [#216564](https://github.com/microsoft/vscode/issues/216564)
