### ISSUE TITLE
HTML language server broken in insiders

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21743]
Version 1.11.0-insider
Commit 4db944bc08e34fb15c5805927d9cb67470776606
Date 2017-03-02T07:25:36.875Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- open an HTML file

The HTML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/extensions/html/server/out/modes/javascriptMode.js:9:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 10:57:08 AM] Connection to server got closed. Server will restart.
modul

**Comment by varadero** [comment]
Version 1.11.0-insider
Commit 4db944bc08e34fb15c5805927d9cb67470776606
Date 2017-03-02T07:10:18.838Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

I observed a strange behavior - I often use ```tsc``` to compile the project - yesterday I used it a lot with stable VSCode version. Today after I have installed VSCode insiders, executing ```tsc``` or ```tsc -v``` caused the following error:
```
'tsc' is not recognized as an internal or external command
operable program or batch file.
```

Looks like VSCode insiders messes with current (global) typescript installation ? I needed to install typescript again with
```
npm install -g typescript
```


It happens if you open "clean" code-insiders (or open any folder and then select File-Close Folder), add new file, place only this inside it:
```html
<html>
</html>
```
And save it as index.html - the error happens immediately.
```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\html\server\out\modes\javascriptMode.js:9:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Error - 12:23:56] Connection to server got closed. Server will not be restarted.
```

Opening the same folder with stable VSCode version works as expected - no errors occur.

**Comment by aeschli** [comment]
@varadero VSCode contains its own bundled typescript node module. The error `Error: Cannot find module 'typescript'` has to do with that node module.
I doubt `'tsc' is not recognized as an internal or external command` is related to that.
