### ISSUE TITLE
IChatTask can't be serialized

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#217645]
IChatTask:

https://github.com/microsoft/vscode/blob/93a7382ecd63439a5bc507ef60e57610845ec05d/src/vs/workbench/api/browser/mainThreadChatAgents2.ts#L42

is a class with methods that don't get serialized, so the interface is inaccurate after reloading the window, and that caused some issues while trying to refactor things. We should figure out how to set this up so that the types are correct after it's deserialized. Maybe we can push a full object with methods to the model, but when reading the chat response value, you get a different simpler interface. Or maybe we need some custom deserialization logic for some types.

**Comment by roblourens** [comment]
I did some refactoring in https://github.com/microsoft/vscode/pull/248672 and this broke much harder. So refactoring a little here.

Verification steps for what I just fixed

- Use `@github #web` to trigger some search
- A couple times for good measure
- Reload the window
- Do more `@github #web`, and scroll around while the response is loading
- The chat view should not break

This was the error stack from the renderer throwing

```
2025-05-12 10:20:54.189 [error] [Window] e.isSettled is not a function: TypeError: e.isSettled is not a function
    at r9e.hasSameContent (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:840:54289)
    at upe.ib (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:862:14357)
    at upe.Z (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:862:8171)
    at upe.renderChatTreeItem (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:862:6717)
    at upe.renderElement (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:862:4565)
    at Nyt.renderElement (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:416:48843)
    at I7i.renderElement (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:322:2142)
    at wxi.eb (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:279:18431)
    at vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:279:17449
    at f7i.transact (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:279:5957)
```
