### ISSUE TITLE
Error: TextModel got disposed before DiffEditorWidget model got reset

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#218001]
I'm not able to find repro steps, but I saw multiple of these errors in the console. I was opening multi diff editors from the commit graph and changing branches.
```
ERR TextModel got disposed before DiffEditorWidget model got reset: Error: TextModel got disposed before DiffEditorWidget model got reset
    at d.value (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:785:84605)
    at l.B (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:93:732)
    at l.C (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:93:802)
    at l.fire (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1018)
    at U.dispose (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:750:5574)
    at f.destroyModel (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:764:1073)
    at P.dispose (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1682:13775)
    at P.dispose (vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2207:19528)
    at vscode-file://vscode-app/c:/Users/besimmonds/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2207:25083
```

**Comment by hediet** [comment]
Without an unminified stack trace, this issue is unactionable unfortunately.

**Comment by aiday-mar** [comment]
Error received around 200 times on Insiders 1.92. Corresponding issue in telemetry will be marked as triaged.
