### ISSUE TITLE
 Pending response rejected since connection got disposed

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#218109]
Testing #216888

added this to setting: `"editor.experimental.asyncTokenization": true`
then I saw this in my python logs whenever I reloaded:

```
2024-06-25 09:44:11.101 [error] sendStartupTelemetry() failed. s [Error]: Pending response rejected since connection got disposed


2024-06-25 09:44:11.101 [error] [
  'Failed to activate a workspace, Class name = m, completed in 4265ms, has a falsy return value, Arg 1: <Uri:/Users/eleanorboyd/vscode-python/.vscode/settings.json>, Arg 2: {"started":1719333846757}, Return Value: undefined',
  s [Error]: Pending response rejected since connection got disposed
      at Object.dispose (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1952454)
      at Object.dispose (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:2007991)
      at S.handleConnectionClosed (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:2008397)
      at S.handleConnectionClosed (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:2177176)
      at /Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:2008140
      at o.invoke (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1954192)
      at s.fire (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1954957)
      at ne (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1940677)
      at o.invoke (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1954192)
      at s.fire (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1954957)
      at d.fireClose (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1962952)
      at ChildProcess.<anonymous> (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.9.2024062506-darwin-arm64/out/client/extension.js:2:1975319)
      at ChildProcess.emit (node:events:526:35)
      at maybeClose (node:internal/child_process:1105:16)
      at Socket.<anonymous> (node:internal/child_process:457:11)
      at Socket.emit (node:events:514:28)
      at Pipe.<anonymous> (node:net:337:12) {
    code: -32097,
    data: undefined
  }
]
```

**Comment by hediet** [comment]
I'd be very surprised if this error depends on the value of the setting `asyncTokenization`, as it looks like an error in the python extension.
Can you try to set it to false and see if it still reproduces?

**Comment by eleanorjboyd** [comment]
yes you are right this is unrelated to f the setting `asyncTokenization`. I will transfer to the python team for review
