### ISSUE TITLE
Rename refactoring fails with "no result" on a TypeScript class in TSX

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#21888]
- VSCode Version: 1.10.1
- OS Version: Windows 10

I have a React component in `DiffView.tsx`, it looks like this:

```jsx
export default class DiffView extends React.Component<Props & ThemedProps, DiffState> {
    ...
}
```

Trying to rename the `DiffView` symbol to something else leads to "[info] No result" in the message bar and this in the TypeScript output panel:

```
[Info  - 13:11:33] Using tsserver from location: C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Error - 13:11:47] 'rename' request failed with error.
Error processing request. Debug Failure. False expression: 
Error: Debug Failure. False expression: 
    at Object.assert (C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:2844:23)
    at getDefaultImportName (C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:59059:26)
    at getReferencedSymbolsForNode (C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:59003:51)
    at Object.findReferencedSymbols (C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:58957:20)
    at findReferencedSymbols (C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:67613:41)
    at Object.findRenameLocations (C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:67600:37)
    at C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:72642:76
    at C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:70725:105
    at Array.reduce (native)
    at Object.combineProjectOutput (C:\Users\borek\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:70725:35)
```

The TypeScript version is 2.2.1 if that matters.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14445
