### ISSUE TITLE
Terminal Tabs: should reset the tab name to the default value when no name is provided

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#219329]
```
1) VSCode Smoke Tests (Electron)
       Terminal
         Terminal Tabs
           should reset the tab name to the default value when no name is provided:
     Error: Timeout: get element '.single-terminal-tab' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:163:16)
      at async Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\out\terminal.js:220:17)
      at async Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\out\terminal.js:158:9)
      at async Context.<anonymous> (out\areas\terminal\terminal-tabs.test.js:42:13)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=281359&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=9ab437b3-ee70-5588-b120-442542e6d570

**Comment by bpasero** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=281597&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=d3816dfe-5f5f-5b74-f77f-0a43291213b6&l=157

**Comment by alexr00** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=282094&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=d3816dfe-5f5f-5b74-f77f-0a43291213b6

**Comment by alexr00** [comment]
Failed again on rerun: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=282094&view=logs&j=3e5e1a76-3859-5bd3-9a69-c2b25b0ec996&t=6673c4a4-9bd6-5d3d-d7ba-7f2e55c00c39&s=40b405d8-d9ea-5f38-8ab3-8db0b216e2d0
