### ISSUE TITLE
`yarn test-extension` fails with `Error: spawn EINVAL`

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#219645]
After setting up a build of VSCode https://github.com/microsoft/vscode/wiki/How-to-Contribute
running the command `yarn test-extension` fails with error: 
```
yarn run v1.22.22
$ vscode-test
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at innerRunTests (E:\repos\vscode\vscode-main\node_modules\@vscode\test-electron\out\runTest.js:66:20)
    at Module.runTests (E:\repos\vscode\vscode-main\node_modules\@vscode\test-electron\out\runTest.js:45:12)
    at PreparedDesktopRun.run (file:///E:/repos/vscode/vscode-main/node_modules/@vscode/test-cli/out/cli/platform/desktop.mjs:90:25)
    at async runPreparedConfigs (file:///E:/repos/vscode/vscode-main/node_modules/@vscode/test-cli/out/bin.mjs:117:31)
    at async main (file:///E:/repos/vscode/vscode-main/node_modules/@vscode/test-cli/out/bin.mjs:33:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

caused by a Breaking Change in `NodeJS 20.12.2`

downgrading to `NodeJS 20.12.1` fixes the issue

related:
https://github.com/microsoft/vscode/issues/212888
https://github.com/microsoft/vscode/issues/212240
https://github.com/nodejs/node/issues/52554

- VS Code Version: latest main
- OS Version: Windows 11

**Comment by DanTup** [comment]
Maybe related:

- https://github.com/nodejs/node/issues/52554
- https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

> It is important to note that there has been a breaking change for Windows users who utilize `child_process.spawn` and `child_process.spawnSync`. Node.js will now error with `EINVAL` if a `.bat` or `.cmd` file is passed to `child_process.spawn` and `child_process.spawnSync` without the `shell` option set.

**Comment by quyenlv-unicloud** [comment]
it now shipped in to new stable release 1.92.0
```
mainThreadExtensionService.ts:79 Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at c:\Users\noname\.vscode\extensions\gaetschwartz.build-runner-0.8.0\out\extension.js:64:34
	at Generator.next (<anonymous>)
	at c:\Users\noname\.vscode\extensions\gaetschwartz.build-runner-0.8.0\out\extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\noname\.vscode\extensions\gaetschwartz.build-runner-0.8.0\out\extension.js:4:12)
	at c:\Users\noname\.vscode\extensions\gaetschwartz.build-runner-0.8.0\out\extension.js:61:38
	at new Promise (<anonymous>)
	at c:\Users\noname\.vscode\extensions\gaetschwartz.build-runner-0.8.0\out\extension.js:61:19
```

**Comment by DanTup** [comment]
@quyenlv-unicloud your issue is something that needs fixing in the gaetschwartz.build-runner extension. Although it's the same error, it's a different occurrence of the same problem.

There was a breaking change in NodeJS (see https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2) that was included in the latest VS Code release that means whenever you `spawn` a `.bat` or `.cmd` file, you _must_ pass `shell: true`. The stack trace you posted shows that the `gaetschwartz.build-runner` extension is calling spawn - possibly it's this code here:

https://github.com/gaetschwartz/build-runner/blob/feaa4f2f38fd33a03959519d546657f3623d988f/src/extension.ts#L65

I would recommend opening an issue at https://github.com/gaetschwartz/build-runner/issues and including these details.

**Comment by quyenlv-unicloud** [comment]
> I would recommend opening an issue at https://github.com/gaetschwartz/build-runner/issues and including these details.

yes thank you so much, I just found it and patched local plugin follow guide https://github.com/gitkraken/vscode-gitlens/issues/3387 . I think many plugins will have problem but it is CVE so no other way. Just hope authors have time to update 👍

**Comment by connor4312** [comment]
Long fixed in `@vscode/test-electron`
