### ISSUE TITLE
select a language  option is not working 

### ISSUE THREAD

**Issue by waleed-Amjad** [microsoft/vscode#219876]
Type: <b>Bug</b>

the select a language button on a new file is not working neither giving any output or giving any option to select the languages available

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.63GB free)|
|Process Argv|--crash-reporter-id 9573c142-cc88-42d4-9188-6be0e3f36307|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.3.61
uncanny-cognitive-complexity|Dab|1.2.0
copilot|Git|1.209.0
copilot-chat|Git|0.17.0
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
vscode-numpy-viewer|Per|0.1.8
cmake|twx|0.0.17
incredibly-in-your-face|Vir|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by asterg1122** [comment]
I have the same problem. My version is 1.91.0 (ea1445c, 2024-07-01T18:54:18.541Z) Mac Universal. In "OUTPUT - Window" it says:
`2024-07-04 02:17:24.671 [error] argument does not match one of these constraints: arg instanceof constraint, arg.constructor === constraint, nor constraint(arg) === true: Error: argument does not match one of these constraints: arg instanceof constraint, arg.constructor === constraint, nor constraint(arg) === true
    at s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:93:39890)
    at d (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:93:39641)
    at E.handler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:635:9226)
    at f.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:655:684)
    at v.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1656:23974)
    at v.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1656:23562)
    at B (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2208:25093)
    at Object.callback (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2208:24847)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:139:59251
    at HTMLAnchorElement.<anonymous> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:139:31282)`

**Comment by Endemark** [comment]
Verfying error while choosing "Select language" in vscode. 
It doesnt prompt or open up anything.

**Comment by EquilibriumTechx** [comment]
same issue here

**Comment by LuVaAcAn** [comment]
Same here. It doesn't open anything. Any ideas?

**Comment by EquilibriumTechx** [comment]
> Same here. It doesn't open anything. Any ideas?

I am
Using the Mac version so only keyboard shortcuts work 

Windows Ctrl+K M
Mac ⌘+K M

**Comment by BTGRCohen** [comment]
Same issue here in 1.91.0

**Comment by javs1979** [comment]
Same.

**Comment by vnmomodangnguyen7** [comment]
same.

**Comment by jonasruth** [comment]
same.

**Comment by RefueOG** [comment]
same

**Comment by srslysasquatch** [comment]
same for me

**Comment by kpirkoBLM** [comment]
Same here
