### ISSUE TITLE
TypeScript support on vscode.dev is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#221299]
1. Open https://vscode.dev/github/microsoft/vscode-vsce
2. Open any TS file

```
  ERR [Extension Host] Error processing request. Could not read file outside of project root /vscode-vfs/github/microsoft/node_modules/@typescript/lib-es5
Error: Could not read file outside of project root /vscode-vfs/github/microsoft/node_modules/@typescript/lib-es5
    at e.PathMapper.toResource (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:2562875)
    at Object.y [as realpath] (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:2568764)
    at https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:1399888
    at $ (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:1400319)
    at P (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:1398108)
    at j (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:1398383)
    at O (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:1397767)
    at Object.resolveLibrary (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:1392591)
    at gcA.resolveLibrary (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:2276820)
    at Rt (https://main.vscode-cdn.net/stable/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js:7:1345815)
```

![Image](https://github.com/user-attachments/assets/042bc4fe-0e64-4d1e-bfa3-71fa99b54e86)

**Comment by mjbvz** [comment]
Possibly still happening on VS Code.dev. Needs investigation

**Comment by mjbvz** [comment]
To verify: make sure that intellisense works. However you will see errors in the developer console. I'm following up with TS about these

**Comment by sandy081** [comment]
> To verify: make sure that intellisense works

Intellisense is not working neither. Loading intellisense status keeps spinning

![Image](https://github.com/user-attachments/assets/41411660-9601-4e0b-b02e-41372d08c4b2)

**Comment by alexr00** [comment]
I thought I saw the same as @sandy081, but it actually worked fine after almost 30 seconds.

**Comment by benada002** [comment]
👋 On https://vscode.dev I get the same as mentioned here https://github.com/microsoft/vscode/issues/221299?notification_referrer_id=NT_kwDOArrL0LQxMTQzODcxNTU3OTo0NTc5NjMwNA#issuecomment-2249568281, but on https://insiders.vscode.dev everything works fine. I also noticed that this is brokern on https://github.dev/ as well.
