### ISSUE TITLE
Watch task failed on NLS bundle

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#221389]
Today I was working and notice `yarn watch` had failed with:

```
[watch-client    ] [09:21:30] Starting compilation...
[watch-client    ] [09:21:30] 'watch-client' errored after 2.98 min
[watch-client    ] [09:21:30] Error: contents of /Users/connor/Github/vscode/src/vs/workbench/workbench.web.main.nls.js are not a buffer
[watch-client    ]     at /Users/connor/Github/vscode/build/lib/util.js:225:19
[watch-client    ]     at Stream.write (/Users/connor/Github/vscode/node_modules/event-stream/index.js:204:20)
[watch-client    ]     at stream.write (/Users/connor/Github/vscode/node_modules/through/index.js:26:11)
[watch-client    ]     at Stream.ondata (node:internal/streams/legacy:21:31)
[watch-client    ]     at Stream.emit (node:events:518:28)
[watch-client    ]     at Stream.emit (node:domain:551:15)
[watch-client    ]     at drain (/Users/connor/Github/vscode/node_modules/through/index.js:36:16)
[watch-client    ]     at stream.queue.stream.push (/Users/connor/Github/vscode/node_modules/through/index.js:45:5)
[watch-client    ]     at Stream.write (/Users/connor/Github/vscode/node_modules/through/index.js:14:43)
[watch-client    ]     at stream.write (/Users/connor/Github/vscode/node_modules/through/index.js:26:11)
[watch-client    ] error Command failed with exit code 1.
[watch-client    ] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "watch-client" exited with 1.
```

Related to ESM/NLS work?

**Comment by connor4312** [comment]
I haven't been able to get this to repro. Weird. And recent commits don't look especially related.

Maybe this is something in swc? 

Feel free to close if you don't have any suspects.

**Comment by bpasero** [comment]
The file is removed from our repo.
