### ISSUE TITLE
Fail to connect to Remote server due to .vscode-server js error

### ISSUE THREAD

**Issue by ZukaiMobby** [microsoft/vscode#221323]
Does this issue occur when all extensions are disabled?: Yes(but have to open ssh extension, so..)

- VS Code Version: 1.91.0
- OS Version: Windows NT x64 10.0.19045

### Steps to Reproduce:

1. Delete the vscode server from the remote, eg.
rm -rf /home/v100/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286

2. Connect to the server from local while specify a project folder.
3. You will get a prompt which tells you the vs code server is downloading, when finished, it will connect successfully but the vscode ouput window will throw an error same as below.
4. Close the vscode and relaunch, it fails to connect with this error
![image](https://github.com/microsoft/vscode/assets/30065158/dec7b79e-c7c8-44ef-923d-d6a5009b9a90)

### vs code server log
cat /home/v100/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/log.txt

[13:58:49] Installing extensions...
[13:58:49] Extension host agent started.
[13:58:49] [<unknown>][2f32ef45][ExtensionHostConnection] New connection established.
[13:58:50] SyntaxError: Expected ',' or '}' after property value in JSON at position 12288
    at JSON.parse (<anonymous>)
    at Object.factory (/home/v100/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/out/vs/server/node/server.main.js:174:44736)
[13:58:50] [<unknown>][ad478435][ManagementConnection] New connection established.
[13:58:50] Error while installing extensions: Expected ',' or '}' after property value in JSON at position 12288
[13:58:50] SyntaxError: Expected ',' or '}' after property value in JSON at position 12288
    at JSON.parse (<anonymous>)
    at Object.factory (/home/v100/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/out/vs/server/node/server.main.js:174:44736) {
  code: 'Scanning',
  name: 'Scanning'
}
[13:58:50] [<unknown>][2f32ef45][ExtensionHostConnection] <557281> Launched Extension Host Process.
New EH opened, aborting shutdown

**Comment by ZukaiMobby** [comment]
I have solve this issue. Because this is a pulic server someone might install a problematic extension, I just remove the extension folder in "/home/v100/.vscode-server" and reinstall extensions.
