### ISSUE TITLE
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#221455]
* todays insiders
* no steps, but see error below, it pointed to this line ⬇ 

https://github.com/microsoft/vscode/blob/0089a88a9702a48657c11ac6b7df860a5c09d857/src/vs/editor/contrib/hover/browser/markerHoverParticipant.ts#L238

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at r.add (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:40:1529)
    at y.B (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:40:2099)
    at y.addAction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:659:3756)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:794:80239
```

**Comment by aiday-mar** [comment]
Do you still see this happening? Recently there has been a commit which fixed disposable issues in the editor hover area. @ulugbekna filed the same issue above and mentioned he no longer sees this.
