### ISSUE TITLE
`Find all references` does not finish in Angular 2 / TypeScript project

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#22149]
- VSCode Version: 1.10.1
- OS Version: Windows 8.1 x64

Right click on the component class, select `Find all references`. `Loading...` never ends. The project is not that large. Previously haven't such issue.

![image](https://cloud.githubusercontent.com/assets/4777512/23661709/8869c1fc-035e-11e7-9c3a-e2030cfb685b.png)

**Comment by Pajn** [comment]
I experience this to for various things that uses the TypeScript server after upgrading to `1.10`.
This is in a React project and not Angular 2 so it seems to be unrelated to libraries.
After reloading the window it works again for a while.

**Comment by Pajn** [comment]
I tried to trace the Language Server but did not see much when it crashed, it sort of just did. But maybe it can help anyway.
```
[Trace - 11:20:09 AM] Sending request: occurrences (1873). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/rasmus/Development/documittu/ts-analyzer/src/__test__/cases.test.ts",
    "line": 7,
    "offset": 21
}
[Trace - 11:20:09 AM] Response received: occurrences (1873). Request took 10 ms. Success: true 
Result: [
    {
        "start": {
            "line": 1,
            "offset": 9
        },
        "end": {
            "line": 1,
            "offset": 16
        },
        "file": "/home/rasmus/Development/documittu/ts-analyzer/src/__test__/cases.test.ts",
        "isWriteAccess": true
    },
    {
        "start": {
            "line": 7,
            "offset": 14
        },
        "end": {
            "line": 7,
            "offset": 21
        },
        "file": "/home/rasmus/Development/documittu/ts-analyzer/src/__test__/cases.test.ts",
        "isWriteAccess": false
    }
]
[Trace - 11:20:09 AM] Sending request: change (1874). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/home/rasmus/Development/documittu/ts-analyzer/src/__test__/cases.test.ts",
    "line": 7,
    "offset": 21,
    "endLine": 7,
    "endOffset": 21,
    "insertString": "()"
}
[Trace - 11:20:10 AM] Sending request: signatureHelp (1875). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/rasmus/Development/documittu/ts-analyzer/src/__test__/cases.test.ts",
    "line": 7,
    "offset": 22
}
[Trace - 11:20:23 AM] TypeScript Service: canceled request with sequence number 1882
[Trace - 11:20:31 AM] TypeScript Service: canceled request with sequence number 1915
[Trace - 11:20:38 AM] TypeScript Service: canceled request with sequence number 1923
[Trace - 11:20:47 AM] TypeScript Service: canceled request with sequence number 1929
[Trace - 11:20:47 AM] TypeScript Service: canceled request with sequence number 1953
[Trace - 11:20:48 AM] TypeScript Service: canceled request with sequence number 1957
[Trace - 11:20:48 AM] TypeScript Service: canceled request with sequence number 1959
[Error - 11:20:54 AM] TSServer exited with code: unknown
[Error - 11:20:54 AM] 'signatureHelp' request failed with error.
Error: Service died.
    at Object.keys.forEach (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:504:45)
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:503:37)
    at ChildProcess.childProcess.on (/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:348:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 11:20:54 AM] Using tsserver from location: /home/rasmus/Development/documittu/node_modules/typescript/lib/tsserver.js
```
This is the file it died in
```typescript
import {analyze} from '../index'

describe('analyze', () => {
  describe('cases', () => {
    it('should emit boolean as boolean', () => {
      expect(analyze(__dirname + '/cases/booleans.ts')).toMatchSnapshot()
    })
  })
})
```
One interesting thing is that the imported file '../index' has never been a problem by itself, I have previously only seen this in other files. Maybe that's just by chance though but my point is that I don't think anything special in that is causing the problem.

Now, after the crash I get loads of `[Trace - 11:20:48 AM] TypeScript Service: canceled request with sequence number 1957` (updated time and number though).

**Comment by mjbvz** [comment]
Hey sorry for the lack of follow up on this issue.

Since this was reported, we've made a number of improvements to the TypeScript server to handle errors better and also improved how we recover from TypeScript server errors on the vscode side. Please give the [latest VSCode 1.13 insiders builds](https://code.visualstudio.com/insiders) a try and let me know if you still are running into this issue
