### ISSUE TITLE
Empty tabs constantly (re)appear.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#221509]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>No</td>
</tr></table>

<table><tr>
	<th> VS Code Version </th>
	<td> <code>code-insiders-1.92.0-1720677214.el8.src.rpm</code> </td>
</tr><tr>
	<th> OS Version </th>
	<td> <a href=''><code>cpe:/o:fedoraproject:fedora:40</code></a> </td>
</tr></table>

#### **Steps to Reproduce**

Paraphrased, as https://lemmy.ml/post/17832504/12189295 explains:

<blockQuote>

A few weeks ago, VSCode began to constantly recreate tabs. Notably, they are always considered to have been modified, so I have to confirm their closure.

I initially thought that the undermentioned log might be the cause:

> ```log
> 2024-07-10 13:50:43.340 [error] Unhandled method getIdAtPosition: Error: Unhandled method getIdAtPosition
>     at /home/RokeJulianLockhart/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:398068
>     at re (/home/RokeJulianLockhart/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:398362)
>     at /home/RokeJulianLockhart/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:393146
>     at Immediate.<anonymous> (/home/RokeJulianLockhart/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.8/dist/extension.js:2:393166)
>     at processImmediate (node:internal/timers:478:21)
>     at process.topLevelDomainCallback (node:domain:160:15)
>     at process.callbackTrampoline (node:internal/async_hooks:128:24)
> ```

...because another entry appeared to always occur each time I closed one of these tabs. However, it stopped appearing today, so I'm a loss for the cause.

The attached URI is [this video](https://imgur.com/a/0FzkJyI), which depicts the reappearance of the tabs.

---

<details>

> https://wim.nl.tab.digital/apps/tasks/#/collections/all/tasks/F0277DC5-F74B-4414-9CAF-39D78D8225A3.ics

</details>

</blockQuote>

**Comment by RokeJulianLockhart** [comment]
<blockQuote>
