### ISSUE TITLE
Cannot find module 'gc-signals' when running tests on windows

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#22177]
I synced after the fix for #22019 went in and now I get a different module error when trying to run tests.

OS: Windows 10
Steps to Reproduce:
* Sync latest (here I have the github repo in a remote named upstream and I pull from the master branch) and reinstall in case dependencies have changed, then open code
```
git pull upstream master
scripts\npm install
code .
```
* Use ctrl+b to run the build task. After it completes, terminate the task
* Open the command palette and "Run test task"

**Expected:** test task runs
**Actual:** Error
```
Starting 'test'...
{ errorCode: 'load',
  moduleId: 'gc-signals',
  neededBy: [ 'vs/workbench/api/node/mainThreadHeapService' ],
  ...
```

**Comment by ramya-rao-a** [comment]
cc @joaomoreno @bpasero and @chrmarti from the linked issue

**Comment by chrmarti** [comment]
Not sure what's going on here. `.\scripts\test.bat` runs to completion, but doesn't show any output. Running the task in VSCode show this error (same as above with additional details):
```
[14:38:03] Using gulpfile c:\devel\vscode\gulpfile.js
[14:38:03] Starting 'test'...
{ errorCode: 'load',
  moduleId: 'gc-signals',
  neededBy: [ 'vs/workbench/api/node/mainThreadHeapService' ],
  detail: 
   Error: %1 is not a valid Win32 application.
   \\?\c:\devel\vscode\node_modules\gc-signals\build\Release\gcsignals.node
       at Object.Module._extensions..node (module.js:598:18)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (c:\devel\vscode\node_modules\gc-signals\src\index.js:8:18)
       at Module._compile (module.js:571:32)
       at Object.Module._extensions..js (module.js:580:10)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at NodeScriptLoader.load (c:\devel\vscode\out\vs\loader.js:609:39)
       at OnlyOnceScriptLoader.load (c:\devel\vscode\out\vs\loader.js:519:37) }
```

**Comment by jrieken** [comment]
Build machines seem happy, run `git clean -xfd`, `./scripts/npm i `, and `./scripts/test.bat`

**Comment by joaomoreno** [comment]
`gc-signals` is built against the node version contained in the electron we ship with. It's a DLL which can only be loaded by a very specific node version.

Our tasks run `.\\node_modules\\.bin\\gulp`, which uses the system installed node executable, which can be any version.

Either we need to fix the task to use `ELECTRON_RUN_AS_NODE` and execute `electron.exe` (right fix) or you can just install Node 6.5.0 as your system node.

**Comment by hoovercj** [comment]
I switched to Node 6.5.0 (32bit), did a git clean, pulled from master, and re-ran the install script. I then built and tried to run the test task but had the same gc-signals failure.

I was able to run to the test script from the command line, though, so I am no longer blocked.

**Comment by jrieken** [comment]
gc-signals, like all other native modules, compiles against electron, not node. In consequence you must use electron, not node, to execute things.

**Comment by hoovercj** [comment]
Do I understand this correctly?

tasks.json is set to use gulp and defines a test task. The gulpfile doesn't specify a test task, but the package.json does (`mocha`), so selecting "run test task" from vscode will run mocha, but it will do so through node, not through electron, which won't work.

So then my question is: why is there a test task defined in tasks.json if it isn't possible to use it?

**Comment by joaomoreno** [comment]
@jrieken It actually compiles against the Node version of Electron. Node 6.5.0 should pick it up without any issues.

**Comment by joaomoreno** [comment]
@hoovercj Good question. Someone put it up, but no one really uses it.

**Comment by CoenraadS** [comment]
I am also having trouble running tests. I tried `7.10.0` & `6.5.0` but both give the same error 

```
[10:32:54] Using gulpfile d:\Downloads\vscode-fork\vscode\gulpfile.js
[10:32:54] Starting 'test'...
{ errorCode: 'load',
  moduleId: 'gc-signals',
  neededBy: [ 'vs/workbench/api/node/mainThreadHeapService' ],
  detail: 
   Error: %1 is not a valid Win32 application.
   \\?\d:\Downloads\vscode-fork\vscode\node_modules\gc-signals\build\Release\gcsignals.node
       at Error (native)
       at Object.Module._extensions..node (module.js:583:18)
       at Module.load (module.js:473:32)
       at tryModuleLoad (module.js:432:12)
       at Function.Module._load (module.js:424:3)
       at Module.require (module.js:483:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (d:\Downloads\vscode-fork\vscode\node_modules\gc-signals\src\index.js:8:18)
       at Module._compile (module.js:556:32)
       at Object.Module._extensions..js (module.js:565:10)
       at Module.load (module.js:473:32)
       at tryModuleLoad (module.js:432:12)
       at Function.Module._load (module.js:424:3)
       at Module.require (module.js:483:17)
       at require (internal/module.js:20:19)
       at NodeScriptLoader.load (d:\Downloads\vscode-fork\vscode\out\vs\loader.js:609:39) }
```

Is there something else needed?
