### ISSUE TITLE
Build: Failed to sign macOS

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#221771]
From yesterday's build : https://dev.azure.com/monacotools/Monaco/_build/results?buildId=283634&view=logs&j=af0dc8b4-cfa3-5b7d-c786-c94be5e90de5&t=5f9641b4-e677-5012-1e65-08d08facb66e

There is the following error:

```
OperationId: f88879da-ac26-4a43-9150-5c24ca929436 failed. Status: FailDoNotRetry Error: {"code":"MacSignFailed","details":{"errorDetails":"Client Id is not allowed for the specified KeyCode"},"innerError":null}

...

Total Time: 00:08:26.1943340
ProcessExecutionComplete:Newtonsoft.Json.JsonSerializerSettings
[2] {"Timestamp":"2024-07-15T18:21:50.584894+00:00","ProviderName":"esrpcli","Level":2,"Keywords":0,"Payload":{"Message":"{\"ver\":\"2.1\",\"name\":\"MS.Ess.EsrpClient.ProcessExecutionComplete\",\"time\":\"2024-07-15T18:21:50.5749070Z\",\"epoch\":\"5335\",\"seqNum\":3,\"flags\":512,\"os\":\"Unix\",\"osVer\":\"13.6.7\",\"appId\":\"esrpcli\",\"appVer\":\"2.0.121+Branch.master.Sha.8f3b635428fcfcfbc0d3e21364fdfd05853d6091\",\"ext\":{\"cloud\":{\"name\":null,\"role\":null,\"roleInstance\":\"Mac-1721065245833\",\"location\":null,\"environment\":null,\"deploymentUnit\":null,\"fullEnvName\":\";;5335\"},\"sll\":{\"libVer\":\"4.0.15238.1\",\"level\":2}},\"data\":{\"exitCode\":1,\"totalFileCount\":1,\"totalFileSizeInBytes\":449135180,\"totalSignDurationMs\":471035.98,\"totalUploadDurationMs\":12322.15,\"handlerStartedAt\":\"2024-07-15T18:13:23.382901+00:00\",\"sessionStartedAt\":\"2024-07-15T18:13:23.382901+00:00\",\"configInfo\":{\"esrpApiBaseUri\":\"[https://api.esrp.microsoft.com/api/v2\",\"esrpSessionTimeoutInSec\":7200,\"maxDegreeOfParallelism\":32,\"exponentialRetryCount\":5,\"signConfigType\":\"inlineSignParams\"},\"handlerExecutionContext\":{\"throttleCount\":0,\"throttledTimeInSec\":0,\"workflowSubType\":\"EmbedSignAzure\",\"sourceLocationType\":1,\"destinationLocationType\":1},\"requestSigningCertificateThumbprint\":\"AED5593BDC993D280AD247B64C935A9F594A8593\",\"isSuccess\":false,\"operationStartedAt\":\"2024-07-15T18:13:24.373618+00:00\",\"operationEndedAt\":\"2024-07-15T18:21:50.574205+00:00\",\"operationDurationMS\":506200,\"processName\":\"dotnet\",\"processVersion\":\"0.0.0.0\",\"customerCorrelationId\":\"8590007f-579b-4d24-9d88-91eda0c5d8d4\",\"esrpClientSessionGuid\":\"abba7062-5458-46fd-8247-5fe707e9d570\",\"indentity\":\"runner\",\"clientId\":\"***\",\"apiBaseUrl\":\"https://api.esrp.microsoft.com/api/v2\",\"handlerWorkflow\":\"sign\",\"policyInfo\":{\"intent\":\"\",\"contentType\":\"\",\"contentOrigin\":\"\",\"productState\":\"\",\"audience\":\"\",\"version\":\"1.0.0\"},\"submissionRequest\":{\"contextData\":{\"builD_BUILDID\":\"283634\",\"builD_BUILDNUMBER\":\"20240715.11](https://api.esrp.microsoft.com/api/v2/%22,/%22esrpSessionTimeoutInSec/%22:7200,/%22maxDegreeOfParallelism/%22:32,/%22exponentialRetryCount/%22:5,/%22signConfigType/%22:/%22inlineSignParams/%22%7D,/%22handlerExecutionContext/%22:%7B/%22throttleCount/%22:0,/%22throttledTimeInSec/%22:0,/%22workflowSubType/%22:/%22EmbedSignAzure/%22,/%22sourceLocationType/%22:1,/%22destinationLocationType/%22:1%7D,/%22requestSigningCertificateThumbprint/%22:/%22AED5593BDC993D280AD247B64C935A9F594A8593/%22,/%22isSuccess/%22:false,/%22operationStartedAt/%22:/%222024-07-15T18:13:24.373618+00:00/%22,/%22operationEndedAt/%22:/%222024-07-15T18:21:50.574205+00:00/%22,/%22operationDurationMS/%22:506200,/%22processName/%22:/%22dotnet/%22,/%22processVersion/%22:/%220.0.0.0/%22,/%22customerCorrelationId/%22:/%228590007f-579b-4d24-9d88-91eda0c5d8d4/%22,/%22esrpClientSessionGuid/%22:/%22abba7062-5458-46fd-8247-5fe707e9d570/%22,/%22indentity/%22:/%22runner/%22,/%22clientId/%22:/%22***/%22,/%22apiBaseUrl/%22:/%22https://api.esrp.microsoft.com/api/v2/%22,/%22handlerWorkflow/%22:/%22sign/%22,/%22policyInfo/%22:%7B/%22intent/%22:/%22/%22,/%22contentType/%22:/%22/%22,/%22contentOrigin/%22:/%22/%22,/%22productState/%22:/%22/%22,/%22audience/%22:/%22/%22,/%22version/%22:/%221.0.0/%22%7D,/%22submissionRequest/%22:%7B/%22contextData/%22:%7B/%22builD_BUILDID/%22:/%22283634/%22,/%22builD_BUILDNUMBER/%22:/%2220240715.11) (insider)\",\"builD_QUEUEDBY\":\"Microsoft.VisualStudio.Services.TFS\",\"builD_REASON\":\"ResourceTrigger\",\"builD_REQUESTEDFOREMAIL\":\"\",\"systeM_TEAMFOUNDATIONCOLLECTIONURI\":\"[https://dev.azure.com/monacotools/\",\"agenT_NAME\":\"Hosted](https://dev.azure.com/monacotools//%22,/%22agenT_NAME/%22:/%22Hosted) Agent\",\"osVersion\":\"Unix 13.6.7\",\"tF_BUILD\":\"True\",\"systeM_TEAMPROJECT\":\"Monaco\",\"systeM_PULLREQUEST_ISFORK\":\"False\",\"systeM_HOSTTYPE\":\"build\",\"systeM_DEFINITIONID\":\"111\",\"systeM_COLLECTIONID\":\"341001b6-62a6-4d7e-aa61-779aea3de100\",\"builD_REPOSITORY_GIT_SUBMODULECHECKOUT\":\"False\",\"builD_SOURCEVERSION\":\"5b8edf2b36bb318800dedb6bbc39cb25d3902a7d\",\"builD_SOURCEBRANCHNAME\":\"main\",\"builD_SOURCEBRANCH\":\"refs/heads/main\",\"builD_REQUESTEDFORID\":\"00000002-0000-8888-8000-000000000000\",\"builD_REQUESTEDFOR\":\"Microsoft.VisualStudio.Services.TFS\",\"builD_REPOSITORY_PROVIDER\":\"GitHub\",\"builD_REPOSITORY_NAME\":\"microsoft/vscode\",\"builD_QUEUEDBYID\":\"00000002-0000-8888-8000-000000000000\",\"builD_DEFINITIONVERSION\":\"100\",\"builD_DEFINITIONNAME\":\"⭐️ VS Code\",\"agenT_MACHINENAME\":\"Mac-1721065245833\"},\"copsId\":9997,\"folderPath\":\"/Users/runner/work/1/unsigned_vscode_client_darwin_universal_archive\",\"pattern\":\"VSCode-darwin-universal.zip\"},\"osVersion\":\"Unix 13.6.7\"}}","EventId":0}}
ESRP failed
Error: Command failed: dotnet /Users/runner/hostedtoolcache/esrpclient/2.0.121/x64/net6.0/esrpcli.dll vsts.sign -a *** -k /var/folders/1q/w28k7vpd4ln7kf4l0gfybp2h0000gn/T/a118b3fc8cef7fffcd05e2ca47a53712d327ec1d -z /var/folders/1q/w28k7vpd4ln7kf4l0gfybp2h0000gn/T/653331a8af37b39974f52da42b989f59775e93cb -f /Users/runner/work/1/unsigned_vscode_client_darwin_universal_archive -p /var/folders/1q/w28k7vpd4ln7kf4l0gfybp2h0000gn/T/1ddb42aaa702b1b29f4f996672dfbfb5b34d7c10 -u false -x regularSigning -b input.json -l AzSecPack_PublisherPolicyProd.xml -y inlineSignParams -j /var/folders/1q/w28k7vpd4ln7kf4l0gfybp2h0000gn/T/6b55639a18bfc071b0ba7db9a6fc55811e888813 -c 9997 -t 120 -g 10 -v Tls12 -s https://api.esrp.microsoft.com/api/v1 -m 0 -o Microsoft -i https://www.microsoft.com/ -n 5 -r true -e /var/folders/1q/w28k7vpd4ln7kf4l0gfybp2h0000gn/T/54276b1e3a7a92f64db76a023ac89e181893c961
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at main (/Users/runner/work/1/s/build/azure-pipelines/common/sign.js:160:12)
    at Object.<anonymous> (/Users/runner/work/1/s/build/azure-pipelines/common/sign.js:169:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5335,
  stdout: null,
  stderr: null
}
```

**Comment by aiday-mar** [comment]
Signing failing also in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=283717&view=logs&j=dd8a94ee-9cbf-51e6-7551-e11732794e5d&t=af1e435d-31cb-5f9e-18c3-3385161d61c9

**Comment by joaomoreno** [comment]
Created IcM.

**Comment by hediet** [comment]
This is resolved, right?
