### ISSUE TITLE
Copilot doesnt work 400 error and 500 error

### ISSUE THREAD

**Issue by bmorgulis** [microsoft/vscode#221777]
Type: <b>Bug</b>

keep getting 400 error and 500 error both in chat and in copilot 
 
500 Internal Server Error
unhandled status from server: 400 Bad Request

Failed to make request

**Comment by chugor** [comment]
on99 what 7 happening ?

**Comment by dfranq** [comment]
I'm getting a similar result. This happens when I highlight code and use the explain feature. After a long time of "Thinking" I get this result in the chat: "There was a problem completing your request. Please try again."

Here are the output logs:

```
Logging to: C:\Users\USER\AppData\Local\Temp\VSGitHubCopilotLogs\20240716_023318.347_VSGitHubCopilot.chat.log
[Conversations Information] Copilot chat version 0.2.889-beta+76e081c54a.RR (0.2.889.30432). VS: VisualStudio.17.Release/17.10.2+35004.147. Session: 51b7d577-e52b-439c-b59a-19ad733473cc. 
[Conversations Information] Need to get an auth token.
[Conversations Information] Status Code: 200, Reason Phrase: OK
[Conversations Information] Response Content: HasToken: True, ChatEnabled: True, ExpiresAt: 1721099003, RefreshIn: 1500, SKU: monthly_subscriber, CopilotExclusion: False
[Conversations Information] Obtained a token which is valid for 00:25:00.
[Conversations Information] Copilot badge status set to: OK
[ConversationsServiceManager Information] Out-of-process service finished initializing.
[CopilotClientManager Information] LSP: Activated (26556329)
[CopilotClientManager Information] LSP: Debug Server: http://localhost:8180
[CopilotClientManager Information] LSP: Process 1132
[CopilotClientManager Information] LSP: file:///C:/Users/USER/AppData/Local/Temp/VSLogs/VS33C476CA.LSPClient.Microsoft.VisualStudio.Completions.CopilotLanguageClient.WGHK.svclog
[CopilotClientManager Information] [agent] GitHub Copilot Language Server 1.181.0 initialized
[CopilotClientManager Information] Initial auth status: OK
[PersistedCopilotSessionRepository Information] Persisted sessions are stored under D:\PROJECTPATH
[CopilotSessionProvider Information] Begin sending message (ConversationId:52ffc7c3-b02a-4b7b-95d3-7005e673740a, CorrelationId:33a97a80-397d-490c-a03b-afc6de70764a, MessageId: 661ee25a-759d-4846-833c-6890669c0615)
[CopilotSessionProvider Information] Request content: "/explain"
[Conversations Error] [CopilotClient] Failed to talk to Copilot: Bad Request

[Conversations Warning] [CopilotClient] Issue with setting up the connection to 'https://api.githubcopilot.com/chat/completions', if you are using a proxy, check if HTTPS_PROXY is set correctly. https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient#http-proxy
[Conversations Error] [CopilotClient] Failed to talk to Copilot: Bad Request

[Conversations Warning] [CopilotClient] Issue with setting up the connection to 'https://api.githubcopilot.com/chat/completions', if you are using a proxy, check if HTTPS_PROXY is set correctly. https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient#http-proxy
[Conversations Error] [Conversations] Unhandled exception in AskInConversationAsync: System.Exception: Error occurred while invoking intent 'Explain'.
Bad Request

   at Conversations.Kernel.ConversationBase.AskAsync(CopilotRequest request, ActiveInteractions activeInteractions, IContextProviders context, IReadOnlyList`1 history, CancellationToken cancellation) in D:\a\_work\1\s\src\Copilot.Service.Kernel\ConversationBase.cs:line 77
   at Microsoft.VisualStudio.Conversations.Service.ServiceTarget.AskInConversationAsync(CopilotSessionId sessionId, CopilotRequest request, ActiveInteractions activeInteractions, IReadOnlyList`1 history, CancellationToken cancellation) in D:\a\_work\1\s\src\Copilot.Service\ServiceTarget.cs:line 174
```

**Comment by bmorgulis** [comment]
same

**Comment by bmorgulis** [comment]
They just updated the issue and it should work now. close and reopen vscode

**Comment by doublnt** [comment]
works now.

**Comment by bmorgulis** [comment]
Thanks
