### ISSUE TITLE
Fail to download VS Code Server when connecting to Windows 11 ARM64 SSH target using remote extension.

### ISSUE THREAD

**Issue by carl-woodward** [microsoft/vscode#221849]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91 x64 User Install
- OS Version: Microsoft Windows 11 Enterprise, 10.0.22621 Build 22621, 22H2[

Steps to Reproduce:

1. Start VS Vode 1.91 or VS Code Insiders 1.91.
2. Connect to ARM64 Windows 11 machine over SSH using "Connect to Host..."

Fail to download server for any and all SSH connections to ARM64 Windows 11.

Logs:
[11:38:43.953] Log Level: 2
[11:38:43.959] SSH Resolver called for "ssh-remote+ssh-machine-target, attempt 1
[11:38:43.959] "remote.SSH.useLocalServer": false
[11:38:43.959] "remote.SSH.useExecServer": true
[11:38:43.959] "remote.SSH.showLoginTerminal": false
[11:38:43.959] "remote.SSH.remotePlatform": {OMITTED}
[11:38:43.959] "remote.SSH.path": undefined
[11:38:43.959] "remote.SSH.configFile": undefined
[11:38:43.960] "remote.SSH.useFlock": true
[11:38:43.960] "remote.SSH.lockfilesInTmp": false
[11:38:43.960] "remote.SSH.localServerDownload": auto
[11:38:43.960] "remote.SSH.remoteServerListenOnSocket": false
[11:38:43.960] "remote.SSH.showLoginTerminal": false
[11:38:43.960] "remote.SSH.defaultExtensions": []
[11:38:43.960] "remote.SSH.loglevel": 2
[11:38:43.960] "remote.SSH.enableDynamicForwarding": true
[11:38:43.960] "remote.SSH.enableRemoteCommand": false
[11:38:43.960] "remote.SSH.serverPickPortsFromRange": {}
[11:38:43.960] "remote.SSH.serverInstallPath": {}
[11:38:43.965] VS Code version: 1.91.1
[11:38:43.965] Remote-SSH version: remote-ssh@0.112.0
[11:38:43.965] win32 x64
[11:38:43.967] SSH Resolver called for host: ssh-machine-target
[11:38:43.967] Setting up SSH remote "ssh-machine-target"
[11:38:43.971] Using commit id "f1e16e1e6214d7c44d078b1f0607b2388f29d729" and quality "stable" for server
[11:38:43.972] Install and start server if needed
[11:38:45.908] Checking ssh with "C:\Program Files\Amazon Corretto\jdk17.0.4_9\bin\ssh.exe -V"
[11:38:45.910] Got error from ssh: spawn C:\Program Files\Amazon Corretto\jdk17.0.4_9\bin\ssh.exe ENOENT
[11:38:45.910] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[11:38:45.911] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[11:38:45.911] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[11:38:45.912] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[11:38:45.912] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[11:38:45.913] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[11:38:45.913] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:38:45.914] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:38:45.914] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[11:38:45.940] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[11:38:45.943] Remote command length: 4920/8192 characters
[11:38:45.943] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 61524 "ssh-machine-target" powershell
[11:38:45.945] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:38:46.274] > The authenticity of host 'ssh-machine-target (IP OPMITTED)' can't be established.
> ED25519 key fingerprint is SHA256:??????????????????????????????????????????????.
> This key is not known by any other names
> Are you sure you want to continue connecting (yes/no/[fingerprint])?]0;C:\WINDOWS\System32\cmd.exe
[11:38:46.274] Got some output, clearing connection timeout
[11:38:46.274] Detected fingerprint confirmation message
[11:38:46.275] Showing fingerprint confirmation dialog
[11:38:49.333] Got fingerprint response: yes
[11:38:49.334] "install" wrote data to terminal: "yes"
[11:38:49.380] > yes
> Warning: Permanently added 'ssh-machine-target' (ED25519) to the list of known hosts.
[11:38:49.921] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindowsPS C:\Users\user> 
> PS C:\Users\user> $uuid="5ae65817c5f6"
> PS C:\Users\user> "${uuid}: running"
> 5ae65817c5f6: running
> PS C:\Users\user> "5ae65817c5f6: pauseLog"
> 5ae65817c5f6: pauseLog
[11:38:50.820] > 5ae65817c5f6: resumeLog
> PS C:\Users\user> main
[11:38:50.836] > 
[11:38:51.515] > Looking for existing CLI in C:\Users\user\.vscode-server
> Downloading cli ia32
> 5ae65817c5f6%%1%%
[11:38:51.804] > Download failed. - Not Found
> Trigger local server download
> 5ae65817c5f6:trigger_server_download
> artifact==cli-win32==
> destFolder==C:\Users\user\.vscode-server==
> destFolder2==/vscode-cli-f1e16e1e6214d7c44d078b1f0607b2388f29d729.zip==
> 5ae65817c5f6:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for C:\Users\user\.vscode-server\vscode-cli-f1e16e1e6214d7c44d078b1f060
> 07b2388f29d729.zip.done and vscode-cli-f1e16e1e6214d7c44d078b1f0607b2388f29d729.z
> zip to exist
[11:38:51.804] Got request to download on client for {"artifact":"cli-win32","destPath":"C:\\Users\\user\\.vscode-server/vscode-cli-f1e16e1e6214d7c44d078b1f0607b2388f29d729.zip"}
[11:38:51.805] Downloading VS Code server locally...
[11:38:51.819] > 
[11:38:51.946] Resolver error: Error: Failed to download VS Code Server (Server returned 404)
	at g.Create (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:499918)
	at c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:550571
	at async t.downloadAndCopyToHost (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:550071)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:620504
	at async t.tryInstall (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:620750)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:580730
	at async t.withShowDetailsEvent (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:584036)
	at async k (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:577649)
	at async t.resolve (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:581407)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:848023
[11:38:51.949] ------

**Comment by FragmentedPacket** [comment]
I'm not sure if there is a larger problem with a release process, but this seems to have occurred in recent releases as well.

https://github.com/microsoft/vscode/issues/223109

**Comment by roblourens** [comment]
I think this is https://github.com/microsoft/vscode-remote-release/issues/9677
