### ISSUE TITLE
Cannot read properties of undefined (reading 'domNode')

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#221870]
```javascript
TypeError: Cannot read properties of undefined (reading 'domNode')
at X.O in src/vs/editor/browser/view.ts:411:40
at X.handleEvents in src/vs/editor/browser/view.ts:355:8
at C.w in src/vs/editor/common/viewModelEventDispatcher.ts:151:18
at C.u in src/vs/editor/common/viewModelEventDispatcher.ts:136:9
at C.t in src/vs/editor/common/viewModelEventDispatcher.ts:129:9
at C.endEmitViewEvents in src/vs/editor/common/viewModelEventDispatcher.ts:106:10
at <anonymous> in src/vs/editor/common/viewModel/viewModelImpl.ts:386:27
at listener in src/vs/editor/common/model/textModel.ts:235:38
at l.B in src/vs/base/common/event.ts:1211:13
at l.C in src/vs/base/common/event.ts:1222:9
at l.fire in src/vs/base/common/event.ts:1246:9
at ne.endDeferredEmit in src/vs/editor/common/model/textModel.ts:2512:23
at U.applyEdits in src/vs/editor/common/model/textModel.ts:1424:23
at s.M in src/vs/workbench/contrib/output/common/outputChannelModel.ts:283:10
at <anonymous> in src/vs/workbench/contrib/output/common/outputChannelModel.ts:241:9
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=f1e16e1e6214d7c44d078b1f0607b2388f29d729&bH=d9c8a53b-2543-8ad7-891f-28c5cae93b85)

**Comment by alexdima** [comment]
Unfortunately the stack trace does not match the current source code anymore
