### ISSUE TITLE
[ModelMetadataFetcher] Failed to fetch models Error: Failed to fetch models: too many requests

### ISSUE THREAD

**Issue by alenakhineika** [microsoft/vscode#222067]
- VS Code Version: 1.92.0-insider
- OS Version: Sonoma 14.5

Steps to Reproduce:

1. Create a chat participant with `vscode.chat.createChatParticipant()` (the API is called once)
2. Check `Debug Console`
3. Observe about 300 identical errors. While they are being printed the chat UI hangs and does not react on submitting prompts

```
[ModelMetadataFetcher] Failed to fetch models Error: Failed to fetch models: too many requests

    at yA._fetchModels (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:14574)
    at processTicksAndRejections (/Users/alena.khineika/www/vscode/lib/internal/process/task_queues.js:95:5)
    at yA.getChatModel (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:13516)
    at bT.getChatEndpoint (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:17127)
    at W0 (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:2993)
    at Nx.chunkFileNaive (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:813)
    at tH.getBasicChunks (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:7193)
    at async Promise.all (index 55)
    at cf.getChunksToSearch (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:31007)
    at /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:32813
    at cf.tryPreInit (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:32313) {stack: 'Error: Failed to fetch models: too many reque…-0.18.2024071701/dist/extension.js:250:32313)', message: 'Failed to fetch models: too many requests
'}
arg2: Error: Failed to fetch models: too many requests\n\n    at yA._fetchModels (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:14574)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at yA.getChatModel (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:13516)\n    at bT.getChatEndpoint (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:17127)\n    at W0 (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:2993)\n    at Nx.chunkFileNaive (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:813)\n    at tH.getBasicChunks (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:7193)\n    at async Promise.all (index 55)\n    at cf.… …
f @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:6
e @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:47874
<anonymous> @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:47742
logIt @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:6600
<anonymous> @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:5843
logIt @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:5830
log @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:6966
error @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:135:7360
_fetchModels @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:14922
processTicksAndRejections @ internal/process/task_queues:95:5
◀ await ▶
processTicksAndRejections @ internal/process/task_queues:95:5
◀ await ▶
getChatModel @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:13527
getChatEndpoint @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:1300:17152
W0 @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:3009
yse @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:2833
chunkFileNaive @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:819
<anonymous> @ /Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.18.2024071701/dist/extension.js:250:7140
```

There is also another error that is printed once at the very beginning:

```
[RemoteAgents] Unable to fetch remote agents because user is not signed in.
```

**Comment by isidorn** [comment]
@alenakhineika I just tried reproducing this with the [Cat sample](https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample) and I could not. Are you trying with the Cat sample - does it work for you?

Is that the only call you do? You are not sending any requests to the model? Can you share a minimal reproducible code for this? Thanks

**Comment by alenakhineika** [comment]
I see the same errors with the cat sample.

<img width="1728" alt="Screenshot 2024-07-19 at 22 34 51" src="https://github.com/user-attachments/assets/c2916ac3-e4aa-41f2-9506-ffa0544dd697">

- I've verified that `vscode.chat.createChatParticipant()` is called only once.
- I am signed in to GitHub Copilot.
- Even with these errors in the Debug Console, I am able to chat with the model, but it hangs for a while unresponsive, and then after printing all these errors returns a message back.
- I am using `GitHub Copilot Chat v0.18.2024071901 (pre-release)`.

**Comment by roblourens** [comment]
Are you sure copilot chat works normally, not using your chat participant extension? It looks like we failed to fetch info about models which isn't even part of the extensibility code.

@lramos15 maybe semantic chunking ends up hitting `_fetchModels` and making many too many requests?

**Comment by alenakhineika** [comment]
You are actually right. I tried to use Copilot without the extension and it did not respond to my prompts.

<img width="597" alt="Screenshot 2024-07-21 at 11 15 20" src="https://github.com/user-attachments/assets/63783ca8-d985-4654-8c4f-b0eaf45a7acd">

Then I tried to run the `/help` command, and it replied with available actions. Then I tried with `Hi` again and Copilot sent `Hi` back.

I have seen a similar answer in our custom Copilot extension. I tried with the `gpt-4` model first and was consistently getting `Sorry, I can't assist with that` responses. I assumed that you don't support this model yet, and I switched to `gpt-3.5-turbo` which did work. Then I tried `gpt-4` again and it surprisingly worked this time. We were wondering if `gpt-4` is unreliable or something?

Now when the regular Copilot works, our extension also does not print `Failed to fetch models` in the debug console.

**Comment by isidorn** [comment]
@alenakhineika make sure to ask programming related questions when testing if something works (e.g. "write me a sorting function in python"). "Sorry, I can not assist with that" is a response when we classified the question as non programming related.

You mentioned that gpt-3.5.-turbo does not work. What are the errors you are seeing?

> Now when the regular Copilot works, our extension also does not print Failed to fetch models in the debug console.

So everything is fine then? If you still see some errors when Copilot works can you share some reproducible steps so we try to get the same state on our machines? Thanks

**Comment by alenakhineika** [comment]
Vise versa: `gpt-3.5.-turbo` consistently worked with the `vscode.chat.createChatParticipant()` API, while `gpt-4` sometimes responded with "Sorry, I can not assist with that" to any kind of questions programming related including.

When @roblourens asked to check if a copilot chat normally works, not using our chat participant extension, I also tried with different kinds of questions (programming including).

> So everything is fine then?

I will let you know if I see this error again.

**Comment by lramos15** [comment]
Thanks for the report, this is a known error I've been looking into it but cannot reproduce so I've made some speculative changes to possibly help.

The sorry I can't assist, and the other issues are a bit unrelated. What is happening is we're requesting a list of models we can use from the server and doing that way too much which then causes you to get rate limited by the server. 

What I cannot figure out is what causes people to get into this request loop as I personally cannot find a set of steps that hits this. I will try a chat participant as I have not done that 👍
