### ISSUE TITLE
Pty Host errors in Remote-SSH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#222323]
- Connect to my mac with Remote-SSH
- See these errors from the server in the log (Remote-SSH output channel)

```
[18:59:03.386] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[18:59:03.387] [server]     at i.ab (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:17128)
[18:59:03.387] [server]     at Timeout._onTimeout (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:16247)
[18:59:03.387] [server]     at listOnTimeout (node:internal/timers:573:17)
[18:59:03.387] [server]     at process.processTimers (node:internal/timers:514:7)
[18:59:03.414] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[18:59:03.414] [server]     at i.ab (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:17128)
[18:59:03.414] [server]     at Timeout._onTimeout (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:16247)
[18:59:03.414] [server]     at listOnTimeout (node:internal/timers:573:17)
[18:59:03.415] [server]     at process.processTimers (node:internal/timers:514:7)
[18:59:03.501] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[18:59:03.501] [server]     at i.ab (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:17128)
[18:59:03.501] [server]     at Timeout._onTimeout (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:16247)
[18:59:03.501] [server]     at listOnTimeout (node:internal/timers:573:17)
[18:59:03.501] [server]     at process.processTimers (node:internal/timers:514:7)
[18:59:03.761] "Update SSH_AUTH_SOCK" terminal command done
[18:59:10.489] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[18:59:10.489] [server]     at i.ab (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:17128)
[18:59:10.489] [server]     at Timeout._onTimeout (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:16247)
[18:59:10.489] [server]     at listOnTimeout (node:internal/timers:573:17)
[18:59:10.489] [server]     at process.processTimers (node:internal/timers:514:7)
[18:59:10.515] [server] [IPC Library: Pty Host] Uncaught Exception:  TypeError: Cannot read properties of undefined (reading 'replace')
[18:59:10.515] [server]     at i.ab (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:17128)
[18:59:10.515] [server]     at Timeout._onTimeout (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:16247)
```

doesn't seem to cause a problem but it's noisy and looks like an issue

**Comment by Tyriar** [comment]
@roblourens could you point me at which line this is? Our stack beautifier doesn't work on server code afaik

```
[18:59:03.501] [server]     at i.ab (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:17128)
[18:59:03.501] [server]     at Timeout._onTimeout (/Users/roblou/.vscode-server-insiders/cli/servers/Insiders-89690b9d76a88fab676d26651134a1ffa4562732/server/out/vs/platform/terminal/node/ptyHostMain.js:54:16247)
```

**Comment by roblourens** [comment]
I don't know which line it is, I only have that stack

**Comment by Tyriar** [comment]
It's this line:

https://github.com/microsoft/vscode/blob/a5fd194b90833cd26787d481db54e82e1a132917/src/vs/platform/terminal/node/terminalProcess.ts#L407

Somehow node-pty can return undefined for `.process` 🤔 

https://github.com/microsoft/node-pty/blob/efbf8ebbe7b09351548fa0a4ed07b36c5d2e539b/src/unixTerminal.ts#L271

Doesn't seem like it should be possible considering `'node'` or `'sh'` are the fallbacks for `_file`:

https://github.com/microsoft/node-pty/blob/efbf8ebbe7b09351548fa0a4ed07b36c5d2e539b/src/unixTerminal.ts#L224

**Comment by roblourens** [comment]
I'm seeing this on my own machine so could do some debugging if you want to add logs or something
