### ISSUE TITLE
Error JavaScript on startup coming from the main process "Error: watch EMFILE"

### ISSUE THREAD

**Issue by lemmel** [Microsoft/vscode#2223]
I get all the time, on startup that error message:
```
Uncaught Exception:
Error: watch EMFILE
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1247:11)
    at Object.fs.watch (fs.js:1273:11)
    at t.e.registerWatchers (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:18607)
    at t.e (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:17858)
    at new t (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:20553)
    at Object.<anonymous> (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:20864)
    at e._invokeFactory (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/loader.js:4:13773)
    at e._complete (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/loader.js:4:14012)
    at e.resolveDependency (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/loader.js:4:15066)
Uncaught Exception:
Error: watch EMFILE
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1247:11)
    at Object.fs.watch (fs.js:1273:11)
    at t.e.registerWatchers (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:18607)
    at t.e (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:17858)
    at new t (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:20553)
    at Object.<anonymous> (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:20864)
    at e._invokeFactory (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/loader.js:4:13773)
    at e._complete (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/loader.js:4:14012)
    at e.resolveDependency (/home/melidrissi/.root/Applications/VSCode-linux-x64/resources/app/out/vs/loader.js:4:15066)
```
I'm under Linux (debian testing) with kernel 4.2.0-1-amd64 #1 SMP Debian 4.2.6-1 (2015-11-10) x86_64.

dependencies  got with "ldd ./Code" and the distro packages, I get:
 ```
libc6:amd64: /lib/x86_64-linux-gnu/libpthread.so.0
libgtk2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
libgtk2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.28
libgtk2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0.2400.28
libgtk2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
libatk1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.21809.1
libatk1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
libpangocairo-1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.3800.1
libpangocairo-1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
libcairo2:amd64: /usr/lib/x86_64-linux-gnu/libcairo.so.2
libcairo2:amd64: /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.4
libpango-1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
libpango-1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.3800.1
libfreetype6:amd64: /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
libfreetype6:amd64: /usr/lib/x86_64-linux-gnu/libfreetype.so.6
libfontconfig1:amd64: /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0
libfontconfig1:amd64: /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
libnotify4:amd64: /usr/lib/x86_64-linux-gnu/libnotify.so.4
libnotify4:amd64: /usr/lib/x86_64-linux-gnu/libnotify.so.4.0.0
libgdk-pixbuf2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
libgdk-pixbuf2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3200.2
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4600.2
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4600.2
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
libdbus-1-3:amd64: /lib/x86_64-linux-gnu/libdbus-1.so.3
libdbus-1-3:amd64: /lib/x86_64-linux-gnu/libdbus-1.so.3.14.5
libx11-6:amd64: /usr/lib/x86_64-linux-gnu/libX11.so.6
libx11-6:amd64: /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
libxrandr2:amd64: /usr/lib/x86_64-linux-gnu/libXrandr.so.2
libxrandr2:amd64: /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
libxext6:amd64: /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
libxext6:amd64: /usr/lib/x86_64-linux-gnu/libXext.so.6
libgconf-2-4:amd64: /usr/lib/x86_64-linux-gnu/libgconf-2.so.4.1.5
libgconf-2-4:amd64: /usr/lib/x86_64-linux-gnu/libgconf-2.so.4
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4600.2
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
libc6:amd64: /lib/x86_64-linux-gnu/librt.so.1
libglib2.0-0:amd64: /lib/x86_64-linux-gnu/libglib-2.0.so.0.4600.2
libglib2.0-0:amd64: /lib/x86_64-linux-gnu/libglib-2.0.so.0
libnss3:amd64: /usr/lib/x86_64-linux-gnu/libnss3.so
libnss3:amd64: /usr/lib/x86_64-linux-gnu/libnssutil3.so
libnss3:amd64: /usr/lib/x86_64-linux-gnu/libsmime3.so
libnspr4:amd64: /usr/lib/x86_64-linux-gnu/libplc4.so
libnspr4:amd64: /usr/lib/x86_64-linux-gnu/libnspr4.so
libasound2:amd64: /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
libasound2:amd64: /usr/lib/x86_64-linux-gnu/libasound.so.2
libcups2:amd64: /usr/lib/x86_64-linux-gnu/libcups.so.2
libc6:amd64: /lib/x86_64-linux-gnu/libdl.so.2
libxi6:amd64: /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
libxi6:amd64: /usr/lib/x86_64-linux-gnu/libXi.so.6
libxcursor1:amd64: /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
libxcursor1:amd64: /usr/lib/x86_64-linux-gnu/libXcursor.so.1
libxfixes3:amd64: /usr/lib/x86_64-linux-gnu/libXfixes.so.3
libxfixes3:amd64: /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
libxrender1:amd64: /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
libxrender1:amd64: /usr/lib/x86_64-linux-gnu/libXrender.so.1
libxcomposite1:amd64: /usr/lib/x86_64-linux-gnu/libXcomposite.so.1
libxcomposite1:amd64: /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
libxdamage1:amd64: /usr/lib/x86_64-linux-gnu/libXdamage.so.1
libxdamage1:amd64: /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
libxtst6:amd64: /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
libxtst6:amd64: /usr/lib/x86_64-linux-gnu/libXtst.so.6
libexpat1:amd64: /lib/x86_64-linux-gnu/libexpat.so.1
libexpat1:amd64: /lib/x86_64-linux-gnu/libexpat.so.1.6.0
libstdc++6:amd64: /usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21-gdb.py
libstdc++6:amd64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6
libstdc++6:amd64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
libc6:amd64: /lib/x86_64-linux-gnu/libm.so.6
libgcc1:amd64: /lib/x86_64-linux-gnu/libgcc_s.so.1
libc6:amd64: /lib/x86_64-linux-gnu/libc.so.6
libpangoft2-1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
libpangoft2-1.0-0:amd64: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.3800.1
libxinerama1:amd64: /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
libxinerama1:amd64: /usr/lib/x86_64-linux-gnu/libXinerama.so.1
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4600.2
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
libpixman-1-0:amd64: /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
libpixman-1-0:amd64: /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.33.4
libpng12-0:amd64: /lib/x86_64-linux-gnu/libpng12.so.0
libpng12-0:amd64: /lib/x86_64-linux-gnu/libpng12.so.0.54.0
libpng12-0:amd64: /usr/lib/x86_64-linux-gnu/libpng12.so.0
libxcb-shm0:amd64: /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0
libxcb-shm0:amd64: /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
libxcb-render0:amd64: /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
libxcb-render0:amd64: /usr/lib/x86_64-linux-gnu/libxcb-render.so.0
libxcb1:amd64: /usr/lib/x86_64-linux-gnu/libxcb.so.1
libxcb1:amd64: /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
zlib1g:amd64: /lib/x86_64-linux-gnu/libz.so.1
zlib1g:amd64: /lib/x86_64-linux-gnu/libz.so.1.2.8
libthai0:amd64: /usr/lib/x86_64-linux-gnu/libthai.so.0.2.4
libthai0:amd64: /usr/lib/x86_64-linux-gnu/libthai.so.0
libselinux1:amd64: /lib/x86_64-linux-gnu/libselinux.so.1
libc6:amd64: /lib/x86_64-linux-gnu/libresolv.so.2
libffi6:amd64: /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
libffi6:amd64: /usr/lib/x86_64-linux-gnu/libffi.so.6
libsystemd0:amd64: /lib/x86_64-linux-gnu/libsystemd.so.0.13.0
libsystemd0:amd64: /lib/x86_64-linux-gnu/libsystemd.so.0
libdbus-glib-1-2:amd64: /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.2.2
libdbus-glib-1-2:amd64: /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
libpcre3:amd64: /lib/x86_64-linux-gnu/libpcre.so.3
libpcre3:amd64: /lib/x86_64-linux-gnu/libpcre.so.3.13.1
libnspr4:amd64: /usr/lib/x86_64-linux-gnu/libplds4.so
libgssapi-krb5-2:amd64: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
libgssapi-krb5-2:amd64: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
libgnutls-deb0-28:amd64: /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
libgnutls-deb0-28:amd64: /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.10
libavahi-common3:amd64: /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
libavahi-common3:amd64: /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
libavahi-client3:amd64: /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
libavahi-client3:amd64: /usr/lib/x86_64-linux-gnu/libavahi-client.so.3
libharfbuzz0b:amd64: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
libharfbuzz0b:amd64: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
libxau6:amd64: /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
libxau6:amd64: /usr/lib/x86_64-linux-gnu/libXau.so.6
libxdmcp6:amd64: /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
libxdmcp6:amd64: /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
libdatrie1:amd64: /usr/lib/x86_64-linux-gnu/libdatrie.so.1
libdatrie1:amd64: /usr/lib/x86_64-linux-gnu/libdatrie.so.1.3.3
liblzma5:amd64: /lib/x86_64-linux-gnu/liblzma.so.5
liblzma5:amd64: /lib/x86_64-linux-gnu/liblzma.so.5.0.0
libgcrypt20:amd64: /lib/x86_64-linux-gnu/libgcrypt.so.20
libgcrypt20:amd64: /lib/x86_64-linux-gnu/libgcrypt.so.20.0.4
libkrb5-3:amd64: /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
libkrb5-3:amd64: /usr/lib/x86_64-linux-gnu/libkrb5.so.3
libk5crypto3:amd64: /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
libk5crypto3:amd64: /usr/lib/x86_64-linux-gnu/libk5crypto.so.3
libcomerr2:amd64: /lib/x86_64-linux-gnu/libcom_err.so.2.1
libcomerr2:amd64: /lib/x86_64-linux-gnu/libcom_err.so.2
libkrb5support0:amd64: /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
libkrb5support0:amd64: /usr/lib/x86_64-linux-gnu/libkrb5support.so.0
libkeyutils1:amd64: /lib/x86_64-linux-gnu/libkeyutils.so.1.5
libkeyutils1:amd64: /lib/x86_64-linux-gnu/libkeyutils.so.1
libp11-kit0:amd64: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
libp11-kit0:amd64: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0
libtasn1-6:amd64: /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
libtasn1-6:amd64: /usr/lib/x86_64-linux-gnu/libtasn1.so.6
libnettle6:amd64: /usr/lib/x86_64-linux-gnu/libnettle.so.6.1
libnettle6:amd64: /usr/lib/x86_64-linux-gnu/libnettle.so.6
libhogweed4:amd64: /usr/lib/x86_64-linux-gnu/libhogweed.so.4
libhogweed4:amd64: /usr/lib/x86_64-linux-gnu/libhogweed.so.4.1
libgmp10:amd64: /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
libgmp10:amd64: /usr/lib/x86_64-linux-gnu/libgmp.so.10
libgraphite2-3:amd64: /usr/lib/x86_64-linux-gnu/libgraphite2.so.3
libgraphite2-3:amd64: /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
libgpg-error0:amd64: /lib/x86_64-linux-gnu/libgpg-error.so.0.16.0
libgpg-error0:amd64: /lib/x86_64-linux-gnu/libgpg-error.so.0
 ```

**Comment by bpasero** [comment]
@lemmel does this help: https://code.visualstudio.com/Docs/supporting/FAQ#_linux-error-enospc

**Comment by lemmel** [comment]
Sorry, I didn't see your message.

And sorry again, because I just used another tools the last few days, and testing today shows me that VSStudio run correctly (at least it starts).
And I can't be of no help because I updated some components on my host.

Thanks again.

**Comment by alexander255** [comment]
I've hit this error today and it turns out I was hitting the [`inotify` per-user instance limit](http://man.cx/inotify_init(2)#heading5). Very non-obvious problem unfortunately :disappointed: .

Only fix is to increase that limit:

```sh
echo 1024 | sudo tee /proc/sys/fs/inotify/max_user_instances
```
