### ISSUE TITLE
np.string_

### ISSUE THREAD

**Issue by AKMRizwan** [microsoft/vscode#223292]
Type: <b>Feature Request</b>

Traceback (most recent call last):
  File "d:\DAVIS\method_overrriding.py", line 7, in <module>
    arr2=np.array(['hello','world'],dtype=np.string_)
                                          ^^^^^^^^^^
  File "C:\Users\smith\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__init__.py", line 411, in __getattr__
    raise AttributeError(
AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.. Did you mean: 'strings'?

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by roblourens** [comment]
This sounds like an issue with your code or your system configuration
