### ISSUE TITLE
remove tab stop from inner tree of debug console output

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#223964]
cc @jooyoungseo

In the debug console output, there's a tree view within a tree view, which creates for a weird tab stopping experience. furthermore, when moving focus from the input box of the debug console to the tree view, the initially focused tree has a lengthy / verbose label. if we can remove that tab stop, it would be better.

also cc @isidorn who might know why this is the case

**Comment by meganrogge** [comment]
This is happening any time there's a link - because the link is a tab stop. 

For example, with the following output in the debug console, when I have my focus in the debug console input and `shift+tab`, the focus is moved to the link closest to the bottom, `/async_hooks:130:17`

```
Unhandled Promise Rejection:  Canceled: Canceled
    at Delayer.cancel (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/common/async.ts:388:20)
    at Client.requestPromise (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/parts/ipc/node/ipc.cp.ts:124:23)
    at Object.call (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/parts/ipc/node/ipc.cp.ts:107:17)
    at TelemetryAppenderClient.log (/Users/meganrogge/Repos/vscode/vscode/src/vs/platform/telemetry/common/telemetryIpc.ts:34:16)
    at /Users/meganrogge/Repos/vscode/vscode/src/vs/platform/telemetry/common/telemetryService.ts:140:34
    at Array.forEach (<anonymous>)
    at TelemetryService._log (/Users/meganrogge/Repos/vscode/vscode/src/vs/platform/telemetry/common/telemetryService.ts:140:19)
    at TelemetryService.publicLog (/Users/meganrogge/Repos/vscode/vscode/src/vs/platform/telemetry/common/telemetryService.ts:144:8)
    at CustomEndpointTelemetryService.publicLog (/Users/meganrogge/Repos/vscode/vscode/src/vs/platform/telemetry/node/customEndpointTelemetryService.ts:68:26)
    at Object.call (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/parts/ipc/common/ipc.ts:1141:23)
    at ChannelServer.onPromise (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/parts/ipc/common/ipc.ts:421:22)
    at ChannelServer.onRawMessage (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/parts/ipc/common/ipc.ts:396:17)
    at UniqueContainer.value (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/parts/ipc/common/ipc.ts:340:63)
    at Emitter._deliver (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/common/event.ts:1230:13)
    at Emitter._deliverQueue (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/common/event.ts:1241:9)
    at Emitter.fire (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/common/event.ts:1265:9)
    at MessagePortMain.fn (/Users/meganrogge/Repos/vscode/vscode/src/vs/base/common/event.ts:568:41)
    at MessagePortMain.emit (/Users/meganrogge/Repos/vscode/vscode/lib/events.js:519:28)
    at MessagePortMain._internalPort.emit (/Users/meganrogge/Repos/vscode/vscode/lib/electron/js2c/utility_init.js:2:2285)
    at Object.callbackTrampoline (node:internal/async_hooks:130:17) {name: 'Canceled', stack: 'Canceled: Canceled
    at Delayer.cancel (/Us…Trampoline (node:internal/async_hooks:130:17)', message: 'Canceled'}
```

**Comment by meganrogge** [comment]
that is another reason that the primary way a user should navigate this, as well as any tree, is via `ctrlCmd+up/downArrow`.
