### ISSUE TITLE
deprecated python linting settings in defaultSettings.json

### ISSUE THREAD

**Issue by llamafilm** [microsoft/vscode#224129]
Type: <b>Bug</b>

Every time I launch VS Code, I get a warning about deprecated python linting settings.  These settings are not in my user nor workspace settings; they are in defaultSettings.json.  As far as I know, this file is not user-editable so I can't fix it.  I've tried reinstalling the Python extensions and I'm up to date with the latest versions.  Not sure what else to do.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 3, 4|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|/Users/ebalsley/My Drive (ebalsley@netflix.com)/projects/Netbox/msenetbox --crash-reporter-id 11e589b2-48d6-4af6-9407-725f0132c526|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
aws-toolkit-vscode|ama|3.16.0
coder-remote|cod|1.3.1
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
EditorConfig|Edi|0.16.4
go|gol|0.42.0
vscode-home-assistant|kee|1.40.0
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.18.43
cpptools|ms-|1.21.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
netflix-ide-plugin-vscode-dropship|net|6.0.0
netflix-internal-goto-vscode|net|6.0.0
vscode-starlark|phg|0.3.1
webgl-glsl-editor|rac|1.3.8
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
river|rfr|0.1.0-alpha.2
shader|sle|1.1.5
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.1
cmake|twx|0.0.17
mib|Ver|0.0.4
pretty-ts-errors|Yoa|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactorc:31101458
ccpltc:31103427
pythonrstrctxt:31103193
hdi1a554:31097393

```

</details>

**Comment by llamafilm** [comment]
From the python log:
```
2024-07-28 10:17:35.159 [error] Reading directory to watch failed [Error: ENOENT: no such file or directory, scandir '/Users/ebalsley/projects/Netbox/msenetbox/.pixi/envs'
	at Object.readdirSync (node:fs:1515:3)
	at t.readdirSync (node:electron/js2c/node_init:2:11289)
	at /Users/ebalsley/.vscode/extensions/ms-python.python-2024.10.0-darwin-arm64/out/client/extension.js:2:574598
	at /Users/ebalsley/.vscode/extensions/ms-python.python-2024.10.0-darwin-arm64/out/client/extension.js:2:574789
	at Array.map (<anonymous>)
	at d.initWatchers (/Users/ebalsley/.vscode/extensions/ms-python.python-2024.10.0-darwin-arm64/out/client/extension.js:2:574507)
	at async d.ensureWatchersReady (/Users/ebalsley/.vscode/extensions/ms-python.python-2024.10.0-darwin-arm64/out/client/extension.js:2:536827)] {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/ebalsley/projects/Netbox/msenetbox/.pixi/envs'
}
2024-07-28 10:17:35.159 [error] Dir "/Users/ebalsley/projects/Netbox/msenetbox/.pixi/envs" is not watchable (directory does not exist)
2024-07-28 10:17:35.159 [info] Default formatter is set to null for workspace /Users/ebalsley/projects/Netbox/msenetbox
2024-07-28 10:17:35.159 [error] Following setting is deprecated: "python.linting.pylintEnabled"
2024-07-28 10:17:35.159 [error] All settings starting with "python.linting." are deprecated and can be removed from settings.
2024-07-28 10:17:35.159 [error] Linting features have been moved to separate linter extensions.
2024-07-28 10:17:35.159 [error] See here for more information: https://code.visualstudio.com/docs/python/linting
2024-07-28 10:17:35.159 [error] Please install "pylint" extension: https://marketplace.visualstudio.com/items?itemName=ms-python.pylint
```

**Comment by llamafilm** [comment]
After carefully disabling extensions one by one, I realized these bad settings come from the `phgn.vscode-starlark` extension.
