### ISSUE TITLE
Terminal smoke tests failing

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#224269]
See the 2nd attempt for Linux x64:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=285756&view=logs&j=0406d1e7-f662-57ee-8715-144c63918fc0&t=6343a13c-b76a-5ae1-96ef-54eddbb16c87&s=325c3323-44a0-5d6f-7a5b-f86454fbd084

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Profiles
           should set the default profile to a contributed one:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (/mnt/vss/_work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForTerminalBuffer (/mnt/vss/_work/1/s/test/automation/out/code.js:175:9)
      at async Terminal._waitForTerminal (/mnt/vss/_work/1/s/test/automation/out/terminal.js:280:9)
      at async Terminal.runCommand (/mnt/vss/_work/1/s/test/automation/out/terminal.js:79:17)
      at async Terminal.createTerminal (/mnt/vss/_work/1/s/test/automation/out/terminal.js:126:9)
      at async Context.<anonymous> (out/areas/terminal/terminal-profiles.test.js:32:13)

  2) VSCode Smoke Tests (Web)
       Terminal
         Terminal Profiles
           should use the default contributed profile on panel open and for splitting:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (/mnt/vss/_work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForTerminalBuffer (/mnt/vss/_work/1/s/test/automation/out/code.js:175:9)
      at async Terminal._waitForTerminal (/mnt/vss/_work/1/s/test/automation/out/terminal.js:280:9)
      at async Terminal.runCommand (/mnt/vss/_work/1/s/test/automation/out/terminal.js:79:17)
      at async Context.<anonymous> (out/areas/terminal/terminal-profiles.test.js:37:13)

  3) VSCode Smoke Tests (Web)
       Terminal
         Terminal Profiles
           createWithProfile command should create a terminal with a contributed profile:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (/mnt/vss/_work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForTerminalBuffer (/mnt/vss/_work/1/s/test/automation/out/code.js:175:9)
      at async Terminal._waitForTerminal (/mnt/vss/_work/1/s/test/automation/out/terminal.js:280:9)
      at async Terminal.runCommandWithValue (/mnt/vss/_work/1/s/test/automation/out/terminal.js:112:13)
      at async Context.<anonymous> (out/areas/terminal/terminal-profiles.test.js:57:13)
```

**Comment by alexr00** [comment]
Ended up disabling these: https://github.com/microsoft/vscode/pull/224273

**Comment by alexr00** [comment]
More of them are failing:

``` Terminal
      Terminal Editors
        ✔ should update color of the tab
        ✔ should rename the tab
        ✔ should show the panel when the terminal is moved there and close the editor
        ✔ should open a terminal in a new group for open to the side
        ✔ should open a terminal in a new group when the split button is pressed
        1) should create new terminals in the active editor group via command
        2) should create new terminals in the active editor group via plus button
        3) should create a terminal in the editor area by default
      Terminal Input
        Auto replies
          4) should automatically reply to a custom entry
      Terminal Persistence
        detach/attach
          5) should support basic reconnection
          - should persist buffer content
      Terminal Profiles
        6) should launch the default profile
        - should set the default profile to a contributed one
        - should use the default contributed profile on panel open and for splitting
        7) should set the default profile
        8) should use the default profile on panel open and for splitting
        9) createWithProfile command should create a terminal with a profile
        - createWithProfile command should create a terminal with a contributed profile
        10) createWithProfile command should create a split terminal with a profile
        11) createWithProfile command should create a split terminal with a contributed profile
      Terminal Tabs
        12) clicking the plus button should create a terminal and display the tabs view showing no split decorations

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=285942&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=28ea5b6f-caa6-595f-762b-3735b6aef94f&s=c041ccde-92b7-5163-1d93-b1c06077f4b4

Will disable these too.

**Comment by Tyriar** [comment]
Tracking in https://github.com/microsoft/vscode/issues/216564

/duplicate
