### ISSUE TITLE
VSCode Server doesn't start when downloading latest version (July 2024)

### ISSUE THREAD

**Issue by carlos-sarmiento** [microsoft/vscode#224498]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.0 July 2024 (assuming from commit id: b1c0a14de1414fcdaa400695b4db1c0799bc3124)
- OS Version: Fedora 41

Steps to Reproduce:

1. `/usr/bin/code serve-web --accept-server-license-terms --without-connection-token --server-data-dir /nas-main-vol/confs/vscode-server --host 0.0.0.0`
2.

Logs
```
 *
 * Visual Studio Code Server
 *
 * By using the software, you agree to
 * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
 * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
 *
 Web UI available at http://0.0.0.0:8000
 [2024-08-01 12:46:13] info Downloading server b1c0a14de1414fcdaa400695b4db1c0799bc3124
 [2024-08-01 12:46:16] info Starting server b1c0a14de1414fcdaa400695b4db1c0799bc3124
 [2024-08-01 12:46:16] info [b1c0a14 stderr]: Loading "original-fs" failed
 [2024-08-01 12:46:16] info [b1c0a14 stderr]: Error: Cannot find module 'original-fs'
 [2024-08-01 12:46:16] info [b1c0a14 stderr]: Require stack:
 [2024-08-01 12:46:16] info [b1c0a14 stderr]: - /home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Module._load (node:internal/modules/cjs/loader:986:27)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at require (node:internal/modules/helpers:179:18)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at n (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:98)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at r.load (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:2:1637)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at h.load (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:13958)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at u (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9338)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Object.errorback (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9457)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at h.triggerErrorback (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:14252)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at /home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:14003
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at r.load (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:2:1654)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at h.load (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:13958)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at u (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9338)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at a._loadModule (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9466)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at a._resolve (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:452)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at a.defineModule (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:5561)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Function.p [as define] (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:1741)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at out-build/bootstrap-amd.js (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:6445)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at /home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:132
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Object.<anonymous> (/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:9767)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     at node:internal/main/run_main_module:28:49 {
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:   code: 'MODULE_NOT_FOUND',
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:   requireStack: [
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:     '/home/user/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js'
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:   ],
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:   phase: 'loading',
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:   moduleId: 'original-fs',
 [2024-08-01 12:46:16] info [b1c0a14 stderr]:   neededBy: [ 'fs' ]
 [2024-08-01 12:46:16] info [b1c0a14 stderr]: }
 [2024-08-01 12:46:16] info [b1c0a14 stderr]: Here are the modules that depend on it:
 [2024-08-01 12:46:16] info [b1c0a14 stderr]: [ 'fs' ]
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: *
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: * Visual Studio Code Server
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: *
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: * By using the software, you agree to
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: *
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: Server bound to /tmp/code-a17faac9-aaf6-42ed-9576-03e09c1efd74
 [2024-08-01 12:46:16] info [b1c0a14 stdout]: Extension host agent listening on /tmp/code-a17faac9-aaf6-42ed-9576-03e09c1efd74
```

**Comment by gustavobergamim** [comment]
Having the same issue here

**Comment by alexdima** [comment]
The only mention of `original-fs` in our sources is here -- https://github.com/microsoft/vscode/blob/f1e16e1e6214d7c44d078b1f0607b2388f29d729/src/bootstrap-amd.js#L48-L53 . Do you by any chance have the env variable `ELECTRON_RUN_AS_NODE` defined somewhere?

**Comment by carlos-sarmiento** [comment]
I don't have `ELECTRON_RUN_AS_NODE` set anywhere I could see

**Comment by dalecurtis** [comment]
Maybe #22019 is related?

**Comment by amytfang** [comment]
Same issue. No `ELECTRON_RUN_AS_NODE` and revert to 1.91.1 fixed the issue.

**Comment by connor4312** [comment]
Please update your host machine version of VS Code to 1.92 to resolve the issue.

**Comment by dalecurtis** [comment]
I wasn't able to find 1.92 from our package manager, but manually installing from https://update.code.visualstudio.com/1.92.0/linux-deb-x64/stable did work.

**Comment by carlos-sarmiento** [comment]
@connor4312 if the solution is to maintain parity between the installed version of `code` and the server version, it would be great if the server did not auto update to a greater version than it supports. Should this be submitted as a feature request?

**Comment by connor4312** [comment]
The VS Code server _should_ be stable between releases. This behavior was a bug, but we cannot patch older versions of VS Code, so putting in any kind of 'fix' would also require taking an update.

**Comment by ernestoalejo** [comment]
I have an extension that runs `code --wait foo` inside, so it has `ELECTRON_RUN_AS_NODE=1` inherited from the environment of its parent process.

How can I run `code --wait foo` inside an extension without triggering this error?

This is the version of vscode, there is no updates available:
```
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by johnzielke** [comment]
I am on version 1.92.0 as far as I can tell, but am still getting the same error while executing a jupyter notebook cell:

> Loading "original-fs" failed
> Error: Cannot find module 'original-fs'
> Require stack:
> - [/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f6a6f686e7a2f70726f6a656374732f67626d2d6c6f6e6769747564696e616c222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f6a6f686e7a2f70726f6a656374732f67626d2d6c6f6e6769747564696e616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002b172-002e27-002e81-002e243.vscode-resource.vscode-cdn.net/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
>     at Module._load (node:internal/modules/cjs/loader:986:27)
>     at Module.require (node:internal/modules/cjs/loader:1233:19)
>     at require (node:internal/modules/helpers:179:18)
>     at i (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:3:98)
>     at r.load (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:2:1637)
>     at h.load (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:1:13958)
>     at u (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:3:9338)
>     at Object.errorback (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:3:9457)
>     at h.triggerErrorback (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:1:14252)
>     at [/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:1:14003](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f6a6f686e7a2f70726f6a656374732f67626d2d6c6f6e6769747564696e616c222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f6a6f686e7a2f70726f6a656374732f67626d2d6c6f6e6769747564696e616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002b172-002e27-002e81-002e243.vscode-resource.vscode-cdn.net/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:1:14003)
>     at r.load (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:2:1654)
>     at h.load (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:1:13958)
>     at u (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:3:9338)
>     at l._loadModule (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:3:9466)
>     at l._resolve (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:4:452)
>     at l.defineModule (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:3:5561)
>     at Function.p [as define] (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:4:1741)
>     at out-build/bootstrap-amd.js (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:4:6445)
>     at [/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:1:132](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f6a6f686e7a2f70726f6a656374732f67626d2d6c6f6e6769747564696e616c222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f6a6f686e7a2f70726f6a656374732f67626d2d6c6f6e6769747564696e616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002b172-002e27-002e81-002e243.vscode-resource.vscode-cdn.net/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:1:132)
>     at Object.<anonymous> (/vscode/vscode-server/bin/linux-x64/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js:4:9653)
> ...
>   neededBy: [ 'fs' ]
> }
> Here are the modules that depend on it:
> [ 'fs' ]

**Comment by mjrist** [comment]
I also have an extension that calls code to open a url in the browser. ELECTRON_RUN_AS_NODE is set to 1 in the extension host.

This is the same issue as @ernestoalejo - https://github.com/microsoft/vscode/issues/224498#issuecomment-2264888560

@connor4312 is there a recommended solution to this?

**Comment by jochemvandooren** [comment]
I have the same issue running on `1.92.1` using vs-code server.

**Comment by rajkundu** [comment]
Same issue here with VS Code v1.92.2 (macOS 14.12).
The following python code:
```python
import plotly
plotly.graph_objects.Figure().show(renderer='browser')
```
fails in Jupyter notebooks but works perfectly fine in a terminal within VS code.
