### ISSUE TITLE
terminal integration proposal replaces the original input

### ISSUE THREAD

**Issue by huazhuangnan** [microsoft/vscode#224553]
VS Code Version: 1.92
OS Version: window 11

Steps to Reproduce:
   1. pwsh + oh-my-oposh
   2. terminal integration  suggest enabled
   3. open pwsh terminal
   4. when using the terminal integration suggestion, if the terminal input line does not contain characters that are not `\u276f`, terminal integration proposal replaces the original input
   
 **oh-my-oposh：** `\u2b9e` 

https://github.com/user-attachments/assets/00c9a171-ed76-47bf-b222-2a4ce74a886d

**oh-my-oposh：** `\u276f` 

https://github.com/user-attachments/assets/57737cf9-543e-47d3-b9f3-9f0f8a96d0cd

**Comment by Tyriar** [comment]
@meganrogge looks like a problem in the acceptSelectedSuggestion around handling wide characters incorrectly

**Comment by Tyriar** [comment]
Can repro.

Init in `C:\Users\Daniel\OneDrive - Microsoft\Documents\PowerShell\profile.ps1`:

```ps1
oh-my-posh
$env:Path += ";C:\Users\Daniel\AppData\Local\Programs\oh-my-posh\bin"
oh-my-posh init pwsh --config "$([Environment]::GetFolderPath("MyDocuments"))\PowerShell\daniel-2line.omp.json" | Invoke-Expression
```

.json theme `C:\Users\Daniel\OneDrive - Microsoft\Documents\PowerShell\daniel-2line.omp.json`:

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "properties": {
            "cache_duration": "none"
          },
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b0",
          "template": " {{ .UserName }} ",
          "foreground": "#ffffff",
          "background": "#c386f1",
          "type": "session",
          "style": "diamond"
        },
        {
          "properties": {
            "cache_duration": "none",
            "style": "folder"
          },
          "template": " \ue5ff {{ .Path }} ",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "background": "#ff479c",
          "type": "path",
          "style": "powerline"
        },
        {
          "properties": {
            "branch_max_length": 25,
            "cache_duration": "none",
            "fetch_status": true,
            "fetch_upstream_icon": true
          },
          "template": " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} ",
          "foreground": "#193549",
          "powerline_symbol": "\ue0b0",
          "background": "#fffb38",
          "type": "git",
          "style": "powerline"
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "properties": {
            "cache_duration": "none"
          },
          "template": "\u2b9e",
          "foreground": "#21c7a8",
          "type": "text",
          "style": "plain"
        }
      ],
      "newline": true
    }
  ],
  "version": 3,
  "final_space": true
}
```

**Comment by Tyriar** [comment]
Error that happens in window log when using this prompt:

```
2025-10-26 03:38:01.878 [error] [Window] [Extension Host] Error parsing output: SyntaxError: Unexpected token 'o', "oh-my-posh"... is not valid JSON
    at JSON.parse (<anonymous>)
    at getAliases (d:\microsoft\vscode3\extensions\terminal-suggest\src\shell\pwsh.ts:64:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at getPwshGlobals (d:\microsoft\vscode3\extensions\terminal-suggest\src\shell\pwsh.ts:13:6)
    at d:\microsoft\vscode3\extensions\terminal-suggest\src\terminalSuggestMain.ts:161:72
    at getShellGlobals (d:\microsoft\vscode3\extensions\terminal-suggest\src\terminalSuggestMain.ts:128:9)
    at Object.provideTerminalCompletions (d:\microsoft\vscode3\extensions\terminal-suggest\src\terminalSuggestMain.ts:273:25)
    at ExtHostTerminalService.$provideTerminalCompletions (file:///d:/microsoft/vscode3/out/vs/workbench/api/common/file:/D:/microsoft/vscode3/src/vs/workbench/api/common/extHostTerminalService.ts:783:23)
2025-10-26 03:38:06.557 [error] [Window] [Extension Host] Error parsing pwsh output: SyntaxError: Unexpected token 'o', "oh-my-posh"... is not valid JSON
    at JSON.parse (<anonymous>)
    at getCommands (d:\microsoft\vscode3\extensions\terminal-suggest\src\shell\pwsh.ts:110:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at getPwshGlobals (d:\microsoft\vscode3\extensions\terminal-suggest\src\shell\pwsh.ts:14:6)
    at d:\microsoft\vscode3\extensions\terminal-suggest\src\terminalSuggestMain.ts:161:72
```
