### ISSUE TITLE
BUG: Unexpected Online Dependencies

### ISSUE THREAD

**Issue by venkatamutyala** [microsoft/vscode#224650]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.90.2
- OS Version: Debian 12

Steps to Reproduce:

1. Install using debian package wget https://update.code.visualstudio.com/1.90.2/linux-deb-x64/stable
2. mv stable stable.deb
3. apt install -f stable.deb
4. (if running as root) code --no-sandbox --user-data-dir=`pwd` --verbose --log=trace --host=0.0.0.0 serve-web

Output:

```
root@debian-16gb-hil-1:~# code --no-sandbox --user-data-dir=`pwd` --verbose --log=trace serve-web --host=0.0.0.0
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Web UI available at http://0.0.0.0:8000?tkn=c9889482-f06e-4bdb-8ac4-cd30c5d813e7
[2024-08-02 22:01:21] info Downloading server b1c0a14de1414fcdaa400695b4db1c0799bc3124
[2024-08-02 22:01:24] info Starting server b1c0a14de1414fcdaa400695b4db1c0799bc3124
[2024-08-02 22:01:24] info [b1c0a14 stderr]: Loading "original-fs" failed
[2024-08-02 22:01:24] info [b1c0a14 stderr]: Error: Cannot find module 'original-fs'
[2024-08-02 22:01:24] info [b1c0a14 stderr]: Require stack:
[2024-08-02 22:01:24] info [b1c0a14 stderr]: - /root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Module._load (node:internal/modules/cjs/loader:986:27)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at require (node:internal/modules/helpers:179:18)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at n (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:98)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at r.load (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:2:1637)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at h.load (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:13958)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at u (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9338)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Object.errorback (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9457)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at h.triggerErrorback (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:14252)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at /root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:14003
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at r.load (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:2:1654)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at h.load (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:13958)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at u (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9338)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at a._loadModule (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9466)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at a._resolve (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:452)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at a.defineModule (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:5561)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Function.p [as define] (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:1741)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at out-build/bootstrap-amd.js (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:6445)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at /root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:132
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Object.<anonymous> (/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:9767)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     at node:internal/main/run_main_module:28:49 {
[2024-08-02 22:01:24] info [b1c0a14 stderr]:   code: 'MODULE_NOT_FOUND',
[2024-08-02 22:01:24] info [b1c0a14 stderr]:   requireStack: [
[2024-08-02 22:01:24] info [b1c0a14 stderr]:     '/root/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js'
[2024-08-02 22:01:24] info [b1c0a14 stderr]:   ],
[2024-08-02 22:01:24] info [b1c0a14 stderr]:   phase: 'loading',
[2024-08-02 22:01:24] info [b1c0a14 stderr]:   moduleId: 'original-fs',
[2024-08-02 22:01:24] info [b1c0a14 stderr]:   neededBy: [ 'fs' ]
[2024-08-02 22:01:24] info [b1c0a14 stderr]: }
[2024-08-02 22:01:24] info [b1c0a14 stderr]: Here are the modules that depend on it:
[2024-08-02 22:01:24] info [b1c0a14 stderr]: [ 'fs' ]
[2024-08-02 22:01:24] info [b1c0a14 stdout]: *
[2024-08-02 22:01:24] info [b1c0a14 stdout]: * Visual Studio Code Server
[2024-08-02 22:01:24] info [b1c0a14 stdout]: *
[2024-08-02 22:01:24] info [b1c0a14 stdout]: * By using the software, you agree to
[2024-08-02 22:01:24] info [b1c0a14 stdout]: * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[2024-08-02 22:01:24] info [b1c0a14 stdout]: * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
[2024-08-02 22:01:24] info [b1c0a14 stdout]: *
[2024-08-02 22:01:24] info [b1c0a14 stdout]: Server bound to /tmp/code-8bb56a5e-61f7-43c6-af3e-0b9d7f369593
[2024-08-02 22:01:24] info [b1c0a14 stdout]: Extension host agent listening on /tmp/code-8bb56a5e-61f7-43c6-af3e-0b9d7f369593
[2024-08-02 22:01:24] info [b1c0a14 stdout]: 
```
So updating to the latest version works but this version used to work before and it appears there is some downloaded dependency and even if running it locally I cannot get around it "Downloading server". 

This forces developers like myself to update to the latest version and are unable to remain pinned to something that was working a few days ago.

**Comment by venkatamutyala** [comment]
Yes the issue goes away if i update. But shouldn't a pinned version continue to work without having to update?

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode/issues/224620
