### ISSUE TITLE
Startup freezes if window is not focussed on i3wm

### ISSUE THREAD

**Issue by powellnorma** [microsoft/vscode#224724]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Linux, i3 version 4.23

Steps to Reproduce:

1. Have multiple windows open, use tabbed mode in i3
2. Exit VSCode 
3. code --disable-extensions --disable-gpu --disable-software-rasterizer --verbose
4. Only the VSCode Window that is focussed will load correctly, all other will freeze:
  ![image](https://github.com/user-attachments/assets/b0bbad3e-d1d5-4de2-9e23-acc77540670b)

The verbose logs show:
```
[17036:0804/100940.429556:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to figure out browser width and height: Error: Unable to figure out browser width and height
    at q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:139:34419)
    at he.load (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:115371)
    at U.zb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:77969)
    at U.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:72755)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122319
    at f.invokeFunction (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:655:684)
    at U.startup (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122115)
    at te.open (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:128802)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js:4:9561", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[17036:0804/100940.429603:INFO:CONSOLE(4)] "[uncaught exception]: Error: Unable to figure out browser width and height", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js (4)
[17036:0804/100940.429622:INFO:CONSOLE(4)] "Error: Unable to figure out browser width and height
    at q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:139:34419)
    at he.load (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:115371)
    at U.zb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:77969)
    at U.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:72755)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122319
    at f.invokeFunction (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:655:684)
    at U.startup (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122115)
    at te.open (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:128802)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js:4:9561", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js (4)
[17036:0804/100940.434435:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to figure out browser width and height: Error: Unable to figure out browser width and height
    at q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:139:34419)
    at he.load (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:115371)
    at U.zb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:77969)
    at U.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:72755)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122319
    at f.invokeFunction (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:655:684)
    at U.startup (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122115)
    at te.open (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:128802)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js:4:9561", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[17036:0804/100940.435173:INFO:CONSOLE(4)] "[uncaught exception]: Error: Unable to figure out browser width and height", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js (4)
[17036:0804/100940.435201:INFO:CONSOLE(4)] "Error: Unable to figure out browser width and height
    at q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:139:34419)
    at he.load (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:115371)
    at U.zb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:77969)
    at U.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:72755)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122319
    at f.invokeFunction (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:655:684)
    at U.startup (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:122115)
    at te.open (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:128802)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js:4:9561", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js (4)

**Comment by powellnorma** [comment]
> Please try upgrading to the latest version and checking whether this issue remains.

Happens in 1.92.0 too

**Comment by powellnorma** [comment]
Any chance to get more details? I guess it's Electron that interacts with X11, so if we would know the exact Electron API that is being used, maybe we could look in the Electron source code to determine how the size is calculated?

I just tested a bit, and can't find any obvious differences. Via `xwininfo -id` (first one being the malfunctioning one):

```
xwininfo: Window id: 0x3a00005 "Visual Studio Code"

  Absolute upper-left X:  0
  Absolute upper-left Y:  24
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1600
  Height: 850
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnviewable
  Override Redirect State: no
  Corners:  +0+24  -0+24  -0-26  +0-26
  -geometry 1600x850+0+24


xwininfo: Window id: 0x3a00003 "get_x11_info.py - Visual Studio Code"

  Absolute upper-left X:  0
  Absolute upper-left Y:  24
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1600
  Height: 850
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnviewable
  Override Redirect State: no
  Corners:  +0+24  -0+24  -0-26  +0-26
  -geometry 1600x850+0+24
```

And also the atoms that XLib window.list_properties() shows seem to be equal:

```
_NET_WM_DESKTOP equal
_NET_WM_STATE equal
WM_STATE equal
_NET_WM_USER_TIME 
   array('I', [5050864]) 
   array('I', [5052505])
_NET_WM_ICON equal
WM_NORMAL_HINTS equal
_MOTIF_WM_HINTS equal
XdndAware equal
_NET_WM_BYPASS_COMPOSITOR equal
WM_NAME 
   b'get_x11_info.py - Visual Studio Code'
   b'Visual Studio Code'
_NET_WM_NAME 
   b'get_x11_info.py - Visual Studio Code' 
   b'Visual Studio Code'
WM_WINDOW_ROLE equal
WM_CLASS equal
_NET_WM_WINDOW_TYPE equal
_NET_WM_PID equal
WM_CLIENT_MACHINE equal
WM_PROTOCOLS equal
```

> I suggest you report this to the window manager.

I did (https://github.com/i3/i3/issues/6191), but it would probably still be helpful to pinpoint the problem a bit further, if possible

**Comment by powellnorma** [comment]
> We are not using Electron APIs for this, but DOM APIs:

Ok, but those are implemented in Electron, right?

I think there is a chance it might be related to i3wm not setting `_NET_FRAME_EXTENTS` correctly - There is a similar sounding issue, where apparently a workaround was added to VirtualBox that made it work: https://github.com/i3/i3/issues/2497#issuecomment-254306362

I might later try the PR https://github.com/i3/i3/pull/5944 and retest.

> Does it reproduce on https://vscode.dev/ with a similar setup?

Opening that in chromium/firefox works fine

**Comment by bpasero** [comment]
I do not think these are specifically changed in Electron, rather inherited from upstream Chromium.

**Comment by powellnorma** [comment]
Would logs like this:
https://chromium.googlesource.com/external/github.com/glfw/glfw/+/refs/heads/ci/src/x11_window.c#2281

get logged to stdout when using `--verbose`?

**Comment by bpasero** [comment]
I would need @deepak1556 expertise to answer that.

**Comment by powellnorma** [comment]
> I might later try the PR https://github.com/i3/i3/pull/5944 and retest.

That seems to not help, unfortunately. It would still be interesting to know where/how to access those "low level" logs of e.g. glfw - Or whatever component ends up interacting with X11 in order to figure out the window size

**Comment by bpasero** [comment]
I suggest to follow this up elsewhere, like StackOverflow. It seems unlikely that a change in VS Code will be done, rather in Electron or in the window manager.

**Comment by powellnorma** [comment]
> It seems unlikely that a change in VS Code will be done, rather in Electron or in the window manager.

@bpasero  
I agree, but what about:

> It would still be interesting to know where/how to access those "low level" logs of e.g. glfw - Or whatever component ends up interacting with X11 in order to figure out the window size

If there was a relevant log message, that could potentially already help a lot. Thank you!
