### ISSUE TITLE
TreeError [SettingsTree] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#224797]
```javascript
Error: TreeError [SettingsTree] Tree element not found: [object Object]
at ai.o in src/vs/base/browser/ui/tree/objectTreeModel.ts:318:10
at ai.rerender in src/vs/base/browser/ui/tree/objectTreeModel.ts:186:25
at fi.rerender in src/vs/base/browser/ui/tree/objectTree.ts:65:14
at $e.bd in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1533:22
at $e.$c in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1515:10
at <anonymous> in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1457:29
at Set.forEach (<anonymous>)
at $e.Yc in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1457:9
at u.value in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:299:10
at o.B in src/vs/base/common/event.ts:1230:13
at o.fire in src/vs/base/common/event.ts:1261:9
at V.zb in src/vs/workbench/services/configuration/browser/configurationService.ts:889:40
at V.Cb in src/vs/workbench/services/configuration/browser/configurationService.ts:931:8
at async Promise.all (index 0)
at async Object.te [as settled] in src/vs/base/common/async.ts:1644:18
at async V.updateValue in src/vs/workbench/services/configuration/browser/configurationService.ts:360:3
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=b1c0a14de1414fcdaa400695b4db1c0799bc3124&bH=91d5e9b6-ad75-a7dd-11c2-56e290c9e3e6)

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/227426
