### ISSUE TITLE
Setting `http.proxy` in Client VSCode will affect Copilot running in SSH - Remote server.

### ISSUE THREAD

**Issue by cesaryuan** [microsoft/vscode#224835]
Type: <b>Bug</b>

Setting http.proxy in Client VSCode will affect copilot running in SSH - Remote server.

- Copilot Chat Extension Version: v1.219.0
- VSCode Version: 1.93.0-insider (user setup)
- Logs:
```
2024-08-05 11:28:35.616 [error] [auth] auth: FetchError: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890
    at fetch (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at XO.fetch (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/lib/src/network/helix.ts:96:22)
    at fetchCopilotToken (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/lib/src/auth/copilotToken.ts:197:16)
    at authFromGitHubToken (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/lib/src/auth/copilotToken.ts:130:22)
    at auth (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/extension/src/auth.ts:40:25)
    at authShowWarnings (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/extension/src/auth.ts:131:25)
    at EM.getCopilotToken (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/extension/src/auth.ts:174:33)
    at attemptAuthentication (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/extension/src/auth.ts:58:9) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNREFUSED',
  errno: -111,
  erroredSysCall: 'connect'
}
2024-08-05 11:28:35.737 [error] [auth] tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890
2024-08-05 11:28:35.907 [error] [default] Error sending telemetry FetchError: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890
    at fetch (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at XO.fetch (/home/ubuntu/.vscode-server-insiders/extensions/github.copilot-1.219.0/lib/src/network/helix.ts:96:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNREFUSED',
  errno: -111,
  erroredSysCall: 'connect'
}
```

Steps to Reproduce:

1. Install VSCode Insiders and start with pure profile.
2. Set `"http.proxy": "http://127.0.0.1:7890"` in client VSCode
3. Prepare an test SSH - Remote server, and Connect to it
4. Install Copilot on server VSCode
5. It throws error: `Error sending telemetry FetchError: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890`
6. Unset `"http.proxy": "http://127.0.0.1:7890"` in client VSCode
7. The error disappeared.

Here is the video:

https://github.com/user-attachments/assets/659836d0-78ab-4517-af4d-7902ef535bdd

VS Code version: Code - Insiders 1.93.0-insider (3b27f1f74bc09fe2e2068997fcd42768be44a4e3, 2024-08-02T05:03:53.254Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux arm64 5.15.0-1016-oracle

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700KF (24 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.82GB (11.67GB free)|
|Process Argv|--crash-reporter-id 09fb0e88-4fb1-4352-b591-b91d82bf7e89|
|Screen Reader|no|
|VM|20%|

|Item|Value|
|---|---|
|Remote|SSH: oracle-arm|
|OS|Linux arm64 5.15.0-1016-oracle|
|CPUs|Neoverse-N1 (4 x 0)|
|Memory (System)|23.43GB (16.70GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
copilot|Git|1.219.0
copilot-chat|Git|0.18.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pri_only:31057983
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
1iic9185:31091668
flightc:31105041
nativeloc1:31106922
wkspc-ranged-c:31107834
cf971741:31108168

```

</details>

**Comment by chrmarti** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1448
