### ISSUE TITLE
Notebooks check object leaks smoketest failure

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#224924]
```
 1) VSCode Smoke Tests (Web)
       Notebooks
         check object leaks:
     Error: Timeout: get element '.notebook-editor .monaco-list-row.focused' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:163:16)
      at async Notebook.openNotebook (/Users/runner/work/1/s/test/automation/out/notebook.js:18:9)
      at async /Users/runner/work/1/s/test/smoke/out/areas/notebook/notebook.test.js:35:17
      at async Profiler.checkObjectLeaks (/Users/runner/work/1/s/test/automation/out/profiler.js:17:9)
      at async Context.<anonymous> (out/areas/notebook/notebook.test.js:34:13)

````

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=286726&view=results

**Comment by alexr00** [comment]
Skipping test with https://github.com/microsoft/vscode/pull/224923

**Comment by neehhaa06** [comment]
Hello @alexr00 :)

fix: #224924

```
I suggest you to, Increase the timeout for waiting and repeatedly check for the presence of the element using a loop with a short delay. This approach accounts for potential delays in rendering and ensures the element is available before proceeding.
```

**Comment by rebornix** [comment]
I don't understand yet why it's failing in Browser, from the screenshot it seems the web view can't be resolved. I'll troubleshoot that separately, and enable notebook smoke test only for electron. Thanks for taking care of it!

**Comment by alexr00** [comment]
It's now failing for electron.

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=350595&view=logs&j=e2741c9b-092a-5194-53b7-e14e2b3f594a&t=57ceab5e-3d19-56d2-373f-c144a65f646d&s=a56e7651-4213-56af-9488-c25fe636c10c

**Comment by alexr00** [comment]
Disabling tests with https://github.com/microsoft/vscode/pull/258417

**Comment by rebornix** [comment]
@amunger it might mean we do have a memory leak for the notebook. It would be great if you can help take a look.

**Comment by benvillalobos** [comment]
Just ran into this (or something similar)

PR: https://github.com/microsoft/vscode/pull/274228
Job: https://github.com/microsoft/vscode/actions/runs/18984386006/job/54225216797?pr=274228

```
  1) VSCode Smoke Tests (Electron)
       Notebooks
         check object leaks:
     Error: Leaked 1 NotebookTextModel
      at Profiler.checkObjectLeaks (/Users/runner/work/vscode/vscode/test/automation/out/profiler.js:30:19)
      at async Context.<anonymous> (out/areas/notebook/notebook.test.js:35:13)
```

**Comment by amunger** [comment]
hopefully. disabling.
