### ISSUE TITLE
Cannot open split terminal, `[UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")`

### ISSUE THREAD

**Issue by michaelfromyeg** [microsoft/vscode#225442]
Does this issue occur when all extensions are disabled?: *Yes*

- VS Code Version

```
$ code --version
1.90.2
5437499feb04f7a586f677b155b039bc2b3669eb
x64
```

- OS Version

```
$ wsl --version
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.26257.5000
```

On Ubuntu 20.

Steps to Reproduce:

1. Go to an open terminal
2. Click the split terminal icon; nothing happens
3. Hit CTRL + SHIFT + 5, the following error appears: `[UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")`

Stack trace is below.

```
2024-08-12 14:46:53.704 [error] [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"): Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
    at w (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:137:45860)
    at new l (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:137:46768)
    at f (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:137:48398)
    at l.from (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:137:47560)
    at new Re (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2375:35871)
    at b.o (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:650:1608)
    at b.createInstance (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:650:1100)
    at i.createInstance (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2377:12959)
    at a.split (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2387:81001)
    at te.Sb (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2377:37718)
    at te.createTerminal (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2377:36350)
```

**Comment by michaelfromyeg** [comment]
Thanks for Claude, I deleted these folders:

```
%APPDATA%\Code\
%USERPROFILE%\.vscode\
```

And set the following setting:

```
"terminal.integrated.splitCwd": "workspaceFolder",
```

Re-installed the WSL extension, re-opened my folder in WSL, and it seems to be working.
