### ISSUE TITLE
unable to create new terminals

### ISSUE THREAD

**Issue by jamalc** [microsoft/vscode#225515]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1 (launched in browser)
- OS Version: Linux 6.1.85+ x86_64

Steps to Reproduce:

1. Have remote workspace open.
2. Launch new terminal.
3. Terminal immediately closes.

![Screen Recording 2024-08-13 at 1 10 30 PM](https://github.com/user-attachments/assets/cf846a80-caf8-4530-ab4e-00cf1d780ef2)

If I restart the PTY host using the restart command, terminals will open again but the issue reliably reoccurs after opening and closing a dozen or fewer terminals.

```log
// ptyhost.log
2024-08-13 16:52:33.472 [trace] [RPC Request] PtyService#createProcess({"executable":"bash","args":[],"cwd":"/home/user/repo","useShellEnvironment":true}, "/home/user/repo", 95, 10, "11", {<redacted>}, {<redacted>}, {"shellIntegration":{"enabled":true,"suggestEnabled":false,"nonce":"f9b0c6df-0754-4364-bcc5-c2eedb30d0db"},"windowsEnableConpty":true,"environmentVariableCollections":[<redacted>],"workspaceFolder":{"uri":{"$mid":1,"fsPath":"/home/user/repo","external":"vscode-remote://<redacted>.cluster-lknrrkkitbcdsvoir6wqg4mwt6.cloudworkstations.dev/home/user/repo","path":"/home/user/repo","scheme":"vscode-remote","authority":"<redacted>.cluster-lknrrkkitbcdsvoir6wqg4mwt6.cloudworkstations.dev"},"name":"repo","index":0}}, true, "-191bb71d", "repo")
2024-08-13 16:52:33.472 [debug] MutationLogger "Persistent process "31" interaction state" set to "None", reason: initialized
2024-08-13 16:52:33.473 [trace] [RPC Response] PtyService#createProcess 31
2024-08-13 16:52:33.508 [trace] [RPC Request] PtyService#start(31)
2024-08-13 16:52:33.508 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":31,"property":{"type":"initialCwd","value":"/home/user/repo"}})
2024-08-13 16:52:33.510 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":31,"property":{"type":"usedShellIntegrationInjection","value":true}})
2024-08-13 16:52:33.510 [trace] node-pty.IPty#spawn <redacted>/bin/bash ["--init-file","/opt/code-oss/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"] {"name":"xterm-256color","cwd":"/home/user/repo","env":{<redacted>}
2024-08-13 16:52:33.512 [trace] [RPC Event] PtyService#_onProcessReady.fire({"id":31,"event":{"pid":8619,"cwd":"/home/user/repo"}})
2024-08-13 16:52:33.512 [trace] [RPC Response] PtyService#start {"injectedArgs":["--init-file","/opt/code-oss/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"]}
2024-08-13 16:52:33.512 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":31,"property":{"type":"title","value":"/user/builtins/bin/bash"}})
2024-08-13 16:52:33.513 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":31,"property":{"type":"shellType"}})
2024-08-13 16:52:33.522 [trace] node-pty.IPty#onData ]633;P;ContinuationPrompt=> 
2024-08-13 16:52:33.524 [trace] TerminalProcess#_queueProcessExit 
    at t.X (/opt/code-oss/out/vs/platform/terminal/node/ptyHostMain.js:50:18845)
    at /opt/code-oss/out/vs/platform/terminal/node/ptyHostMain.js:50:18623
    at EventEmitter2.fire (/opt/code-oss/node_modules/node-pty/lib/eventEmitter2.js:41:22)
    at PipeSocket.<anonymous> (/opt/code-oss/node_modules/node-pty/lib/terminal.js:93:76)
    at PipeSocket.emit (node:events:517:28)
    at Terminal.emit (/opt/code-oss/node_modules/node-pty/lib/terminal.js:155:34)
    at onexit (/opt/code-oss/node_modules/node-pty/lib/unixTerminal.js:102:19)
2024-08-13 16:52:33.527 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":31,"event":"\u001b]633;P;ContinuationPrompt=> \u0007"})
2024-08-13 16:52:33.552 [trace] [RPC Request] PtyService#resize(31, 95, 10)
2024-08-13 16:52:33.552 [trace] node-pty.IPty#resize 95 10
2024-08-13 16:52:33.552 [trace] node-pty.IPty#resize exception ioctl(2) failed, EBADF
2024-08-13 16:52:33.552 [trace] [RPC Response] PtyService#resize undefined
2024-08-13 16:52:33.773 [trace] node-pty.IPty#kill
2024-08-13 16:52:33.774 [trace] [RPC Event] PtyService#_onProcessExit.fire({"id":31,"event":0})
2024-08-13 16:52:33.867 [trace] [RPC Request] PtyService#resize(7, 107, 10)
2024-08-13 16:52:33.867 [trace] node-pty.IPty#resize 107 10
2024-08-13 16:52:33.867 [trace] [RPC Response] PtyService#resize undefined
2024-08-13 16:52:33.867 [trace] node-pty.IPty#onData 
[K
]633;A]0;user@<redacted>: ~/repo[00;35m<redacted>[00m:[01;34m~/repo[00m[01;32m{master}[00m$ ]633;B
2024-08-13 16:52:33.871 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":7,"event":"\r\u001b[K\r\u001b]633;A\u0007\u001b]0;user@<redacted>: ~/repo\u0007\u001b[00;35m<redacted>\u001b[00m:\u001b[01;34m~/repo\u001b[00m\u001b[01;32m{master}\u001b[00m$ \u001b]633;B\u0007"})
2024-08-13 16:52:33.872 [debug] CommandDetectionCapability#handlePromptStart 0 1
2024-08-13 16:52:33.873 [debug] CommandDetectionCapability#handleCommandStart 35 1
2024-08-13 16:52:33.873 [trace] PromptInputModel#_sync: |
2024-08-13 16:52:34.370 [trace] [RPC Request] PtyService#setTerminalLayoutInfo({"workspaceId":"-191bb71d","tabs":[{"isActive":true,"activePersistentProcessId":7,"terminals":[{"relativeSize":1,"terminal":7}]}]})
2024-08-13 16:52:34.370 [trace] [RPC Response] PtyService#setTerminalLayoutInfo undefined
2024-08-13 16:52:34.406 [trace] [RPC Request] PtyService#updateTitle(7, "bash", 2)
2024-08-13 16:52:34.406 [trace] [RPC Response] PtyService#updateTitle undefined
2024-08-13 16:55:03.378 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2024-08-13 16:55:03.378 [trace] [RPC Response] PtyService#getDefaultSystemShell bash
2024-08-13 16:55:03.405 [trace] [RPC Request] PtyService#resize(7, 90, 10)
2024-08-13 16:55:03.406 [trace] node-pty.IPty#resize 90 10
2024-08-13 16:55:03.406 [trace] [RPC Response] PtyService#resize undefined
```

**Comment by meganrogge** [comment]
`node-pty.IPty#resize exception ioctl(2) failed, EBADF`

this is odd, does it happen if you create a new terminal via the + button instead of splitting?

**Comment by meganrogge** [comment]
also, does it reproduce in insider's?

**Comment by jamalc** [comment]
It still happens no matter how the terminal is created. I've seen it happen in insiders as well but I don't use insiders often.
