### ISSUE TITLE
Refactor: move to new file does not work

### ISSUE THREAD

**Issue by a-x-** [microsoft/vscode#225712]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.92.1 (Universal)
- OS Version: MacOS Sonoma 14.5 / Apple M1 Pro

Steps to Reproduce:

1. Refactor > move to new file

What I tried already:
1. Run with `--disable-extensions` to ensure it's not a problem with a package.
2. `typescript.tsserver.enableTrace`
3. find minimal examples
4. search for similar issues

It worked a few versions before. I don't know exactly what version was okay.

not working:
```ts
import { selectStore, useSelector } from '@proterm/core';

export function useOrders() {
    return useSelector(selectStore);
}
```

working:
```ts
import { AnyBaseOrder } from '@terminal/scalp/types';

export function useOrders(symbolId: string): AnyBaseOrder[] {}
```

working:
```ts
import { useSelector } from 'react-redux';

function useOrders() {
    return useSelector((state) => console.log(state));
}
```

working:
```ts
import { selectStore, useSelector } from '@proterm/core';
export function useOrders(symbolId: string): AnyBaseOrder[] {}
```

error:
```
2024-08-15 18:42:15.101 [error] <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154243:32)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143512:3)
    at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144488:3)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:77
    at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:60)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189305:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.5.4)
```

**Comment by a-x-** [comment]
tsconfig.json:
```json5
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "resolveJsonModule": true,
        "outDir": "./dist/",
        "lib": ["es2018", "dom", "ES2020.Promise", "DOM.Iterable", "es2019.array", "ES2021.String"],
        "sourceMap": true,
        "strict": true,
        "module": "esnext",
        "jsx": "react-jsx",
        "target": "es2017",
        "rootDir": ".",
        "allowJs": true,
        "moduleResolution": "node",
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "downlevelIteration": true,
        "importHelpers": true,
        "experimentalDecorators": true,
        "preserveSymlinks": true,
        "useUnknownInCatchVariables": false,

        // COPY: /webpack/tsconfig.json
        // COPY: /webpack/webpack.base.config.ts#alias
        // COPY: /.storybook/main.ts
        "paths": {
            "@proterm/core": ["./src/core"],
            "@terminal/kit": ["./packages/kit"],
            "@terminal/icons": ["./packages/icons"],
            "@terminal/widgets": ["./packages/widgets"],
            "@terminal/scalp/*": ["./packages/scalp/solid/*"],
            "@terminal/*": ["./src/*"]
        },
        "plugins": [
            {
                "name": "typescript-plugin-css-modules",
                "options": {
                    "customMatcher": "\\.less$"
                }
            }
        ]
    },
    "types": ["node", "jest", "@testing-library/jest-dom", "@testing-library/react"],
    "include": ["./src/", "./packages/mobile", "./packages/kit/src", "./packages/widgets/src"],
    "exclude": ["**/__tests__", "**/*.stories.*", "**/__mock__/*.ts", "**/node_modules", "**/lib", "./packages/scalp/solid"]
}
```

**Comment by a-x-** [comment]
So, @proterm/core is an alias to the big file with re-exports and re-exports of re-exports

Moreover, `selectStore` is declared as weird as:
```ts
function selectStore<State>(store: ReducerStore<State>): (state: any) => State;
function selectStore<State>(store: ReducerStore<State>, state: any): State;
function selectStore<State>(store: ReducerStore<State>, state?: any) {
    if (state) {
        return select(store, state);
    }

    function selectStoreCurried(stateCurried: State) {
        return select(store, stateCurried);
    }

    (selectStoreCurried as any)[widgetScope.symbol] = true;

    return selectStoreCurried;
}

(selectStore as any)[widgetScope.symbol] = true;

export default selectStore;
```

**Comment by a-x-** [comment]
Looks like this is a problem, because 
```ts
import { syncSettings } from '@proterm/core';

export function useOrders() {
    return syncSettings;
}
```
works as syncSettings hasn't multiple declarations.

In the save moment, I cannot move other functions w/o referring `selectStore` or things like this.
For instance this does not work too:
```ts
import { useCallback, useRef, useState } from 'react';
import { useLatest } from 'react-use';

type Opts = { lastOnly?: boolean };
type Set<D> = (data: D) => void;
export function useSubscriptionProvider<T extends Set<D>, D>(name: string, data: D, opts?: Opts) {
    const { lastOnly = true } = opts || {};
    const [buffer, setBuffer] = useState<D[]>([]);
    const queueRef = useLatest(buffer);
    const saveBuffer = useCallback((data: D) => setBuffer((q) => [...q, data]), []);
    const ref = useRef<T>();
    console.log('hm', { lastOnly, buffer, queueRef, saveBuffer, ref, name, data });
}
```
