### ISSUE TITLE
Window stops responding when searching large terminal output

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#225735]
`"terminal.integrated.scrollback": 5000,`

```
cd ~/.vscode-insiders/extensions/ms-python.vscode-pylance-2024.8.1
rg 'sub-folder instead'
```

rg prints a very long line, then I cmd+F, and the window stops responding. You could probably also just `cat dist/pyright.bundle.js` instead of `rg`

```
2024-08-15 14:24:30.043 [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47741)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
    at o._findInLine (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules.asar/@xterm/addon-search/lib/addon-search.js:1:47923)
...
```

**Comment by legomushroom** [comment]
The issue is still relevant on stable 1.96.0. The minor clarification to the repro instructions, - you also need to start typing something in the search input, simply opening the search with `cmd+f` does not cause the window to hang on its own.
