### ISSUE TITLE
Reloading the window is longer...

### ISSUE THREAD

**Issue by DingGuodong** [microsoft/vscode#225752]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2(user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Use the Remote for ssh open a folder
2. Click **File** -> **Save workspace as ...**
3. Choose a folder to save the workspace file
4. Reload the windows, then we can get a message 'Reloading the window is longer...'😣
![image](https://github.com/user-attachments/assets/c0f006ec-3736-4df7-96c9-8b5921eb25b9)

5. This vscode window is hanged up and can not closed manually.😂
6. The only way to reopen it is force close it by **Task Manager**.

I can give more information if it need. 🙂

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!

**Comment by DingGuodong** [comment]
I got those logs. Please check it @bpasero .
[20240816T151528.zip](https://github.com/user-attachments/files/16634218/20240816T151528.zip)

**Comment by bpasero** [comment]
Looks like a unhealthy connection to me:

```
2024-08-16 15:16:39.396 [error] resolveAuthority(ssh-remote) returned an error after 1 ms Cannot resolve authority
2024-08-16 15:16:39.397 [error] [remote-connection][Management   ][6a2d8…][reconnect] An unknown error occurred while trying to reconnect, since this is an unknown case, it will be treated as a permanent error! Will give up now! Error:
2024-08-16 15:16:39.397 [error] Error: Cannot resolve authority
    at Q.qb (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3233:26944)
    at Q.Pb (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3235:2756)
    at Q.pb (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3233:26571)
    at Q.ob (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3233:26284)
    at u.value (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3235:4448)
    at o.B (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:732)
    at o.fire (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:949)
    at Object.getAddress (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2324:25676)
    at T (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:694:11442)
    at W.z (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:694:16439)
    at W.y (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:694:15537)
    at u.value (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:694:15329)
    at o.B (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:732)
    at o.fire (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:949)
    at s.fire (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:15085)
    at b.C (vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:19255)
    at vscode-file://vscode-app/c:/Users/z/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:19486
```

**Comment by DingGuodong** [comment]
The vscode client is on **Windows_NT x64 10.0.19045**, Remote SSH server is a host which the network is same with the vscode client. such as  10.0.0.44 -> 10.0.1.245:ssh. The client conntected to the server by ssh with a domain name. And the domain name is valid and always avaiable for me. So it is not a ssh or network connection problem. There must be some wrong with the vscode or Remote for SSH plugin. I do not know why the log file say 'Error: Cannot resolve authority'.

**Comment by ConnorRigby** [comment]
Having the same experience, with the same setup. Same network, windows 10 ssh to linux client. Happens on two linux machines from my Windows machine.

**Comment by TSonono** [comment]
I'm also encountering this (windows -> linux) and have to use the task manager to close VSCode (on 1.92.2). Particularly, this happens when debugging an extension in an extension host window.

**Comment by connor4312** [comment]
I'm not sure there's a good way to repro this consistently. I would just verify with code reviwe.
