### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Xiiyy** [microsoft/vscode#225841]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.6

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
RangeError: Maximum call stack size exceeded
    at Object.scan (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:12570:16)
    at nextTokenWithoutCheck (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31055:36)
    at nextToken (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31065:12)
    at isParenthesizedArrowFunctionExpressionWorker (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33424:20)
    at speculationHelper (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:13376:20)
    at Object.lookAhead (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:13409:12)
    at speculationHelper (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31102:68)
    at lookAhead (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31114:12)
    at isParenthesizedArrowFunctionExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33406:14)
    at tryParseParenthesizedArrowFunctionExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33393:22)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33301:29)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
    at doOutsideOfContext (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30955:12)
    at allowInAnd (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30976:12)
    at parseParenthesizedExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34414:24)
    at parsePrimaryExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:34376:16)
    at parseMemberExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33823:24)
    at parseLeftHandSideExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33817:82)
    at parseUpdateExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33792:24)
    at parseUnaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33711:32)
    at parseBinaryExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33633:25)
    at parseAssignmentExpressionOrHigher (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33306:18)
    at parseExpression (d:\VS_studio\VSCode-huawei\resources\app\extensions\node_modules\typescript\lib\tsserver.js:33272:16)
```

**Comment by mjbvz** [comment]
Closing as this is an old TS version. Please update to use TS 5.5+
