### ISSUE TITLE
  ERR [154] potential listener LEAK detected, having 180 listeners already. MOST frequent listener (27):: Error

### ISSUE THREAD

**Issue by alaric8** [microsoft/vscode#225845]
Type: <b>Bug</b>

event.ts:870 [154] potential listener LEAK detected, having 180 listeners already. MOST frequent listener (27):
check @ event.ts:870
q @ event.ts:1110
P @ menuService.ts:395
q @ event.ts:1118
l @ treeView.ts:1689
getResourceActions @ treeView.ts:1610
renderElement @ treeView.ts:1342
J @ treeView.ts:1363
（匿名） @ treeView.ts:1199
B @ event.ts:1211
C @ event.ts:1222
fire @ event.ts:1246
（匿名） @ workbenchThemeService.ts:285
B @ event.ts:1211
C @ event.ts:1222
fire @ event.ts:1246
Lb @ configurationService.ts:1116
wb @ configurationService.ts:812
reloadLocalUserConfiguration @ configurationService.ts:653
await in reloadLocalUserConfiguration（异步）
Hb @ configurationService.ts:1039
await in Hb（异步）
（匿名） @ configurationService.ts:360
updateValue @ configurationService.ts:360
h @ mainThreadConfiguration.ts:80
g @ mainThreadConfiguration.ts:71
$updateConfigurationOption @ mainThreadConfiguration.ts:50
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:308
（匿名） @ rpcProtocol.ts:161
B @ event.ts:1211
fire @ event.ts:1242
fire @ ipc.net.ts:650
x.onmessage @ localProcessExtensionHost.ts:378
event.ts:871 Error
    at c.create (event.ts:902:15)
    at h.q [as onDidChange] (event.ts:1109:34)
    at Object.P [as onWillAddFirstListener] (menuService.ts:395:34)
    at u.q [as onDidChange] (event.ts:1118:20)
    at Pe.l (treeView.ts:1689:21)
    at Pe.getResourceActions (treeView.ts:1610:24)
    at Ne.renderElement (treeView.ts:1342:34)
    at Ne.J (treeView.ts:1363:10)
    at d.value (treeView.ts:1199:69)
    at l.B (event.ts:1211:13)
    at l.C (event.ts:1222:9)
    at l.fire (event.ts:1246:9)
    at d.value (workbenchThemeService.ts:285:30)
    at l.B (event.ts:1211:13)
    at l.C (event.ts:1222:9)
    at l.fire (event.ts:1246:9)
    at W.Lb (configurationService.ts:1116:35)
    at W.wb (configurationService.ts:812:8)
    at W.reloadLocalUserConfiguration (configurationService.ts:653:9)
    at async W.Hb (configurationService.ts:1039:6)
    at async Promise.all (index 0)
    at async Object.te [as settled] (async.ts:1644:18)
    at async W.updateValue (configurationService.ts:360:3)
check @ event.ts:871
q @ event.ts:1110
P @ menuService.ts:395
q @ event.ts:1118
l @ treeView.ts:1689
getResourceActions @ treeView.ts:1610
renderElement @ treeView.ts:1342
J @ treeView.ts:1363
（匿名） @ treeView.ts:1199
B @ event.ts:1211
C @ event.ts:1222
fire @ event.ts:1246
（匿名） @ workbenchThemeService.ts:285
B @ event.ts:1211
C @ event.ts:1222
fire @ event.ts:1246
Lb @ configurationService.ts:1116
wb @ configurationService.ts:812
reloadLocalUserConfiguration @ configurationService.ts:653
await in reloadLocalUserConfiguration（异步）
Hb @ configurationService.ts:1039
await in Hb（异步）
（匿名） @ configurationService.ts:360
updateValue @ configurationService.ts:360
h @ mainThreadConfiguration.ts:80
g @ mainThreadConfiguration.ts:71
$updateConfigurationOption @ mainThreadConfiguration.ts:50
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:308
（匿名） @ rpcProtocol.ts:161
B @ event.ts:1211
fire @ event.ts:1242
fire @ ipc.net.ts:650
x.onmessage @ localProcessExtensionHost.ts:378
log.ts:439   ERR [154] potential listener LEAK detected, having 180 listeners already. MOST frequent listener (27):: Error
    at c.create (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:88:57139)
    at h.q [as onDidChange] (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:1100)
    at Object.P [as onWillAddFirstListener] (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:790:67117)
    at u.q [as onDidChange] (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:1280)
    at Pe.l (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:12823)
    at Pe.getResourceActions (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:11851)
    at Ne.renderElement (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:7858)
    at Ne.J (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:8282)
    at d.value (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:4821)
    at l.B (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:732)
    at l.C (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:802)
    at l.fire (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1018)
    at d.value (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1883:37044)
    at l.B (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:732)
    at l.C (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:802)
    at l.fire (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1018)
    at W.Lb (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:34917)
    at W.wb (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:27901)
    at W.reloadLocalUserConfiguration (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:24850)
    at async W.Hb (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:33071)
    at async Promise.all (index 0)
    at async Object.te [as settled] (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:139:24668)
    at async W.updateValue (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:20082)

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (6.39GB free)|
|Process Argv|--crash-reporter-id 9e13f3b0-277d-444d-9397-4eec8413abdd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 0)|
|Memory (System)|7.46GB (5.26GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
icons-carbon|ant|0.2.6
mermaid-markdown-syntax-highlighting|bpr|1.6.6
vscode-jetbrains-icon-theme|cha|2.22.0
apc-extension|drc|0.3.9
file-icons|fil|1.1.0
vscode-drawio|hed|1.6.6
dotenv|mik|1.0.1
remote-wsl|ms-|0.88.2
shellman|Rem|5.7.0
vim|vsc|1.27.3
iconify|ant|0.9.2
reveal-button|anw|1.1.1
vscode-notes|dio|1.2.1
code-runner|for|0.12.2
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
vscode-language-pack-zh-hans|MS-|1.91.2024071009
snippet-creator|nik|0.0.5
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571

```

</details>

**Comment by deepak1556** [comment]
Can you share the steps that triggered the above error
