### ISSUE TITLE
[12f] potential listener LEAK detected, having 1029 listeners already. MOST frequent listener (792):

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#226057]
```javascript
Error
at c.create in src/vs/base/common/event.ts:921:15
at h.q [as onDidChange] in src/vs/base/common/event.ts:1128:34
at Object.A [as onWillAddFirstListener] in src/vs/platform/actions/common/menuService.ts:425:34
at u.q [as onDidChange] in out/vs/workbench/workbench.desktop.main.js:91:1280
at D.G in src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts:352:36
at p._runFn in src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts:218:11
at p.j in src/vs/base/common/observableInternal/autorun.ts:196:10
at p.endUpdate in src/vs/base/common/observableInternal/autorun.ts:237:10
at d.finish in src/vs/base/common/observableInternal/base.ts:372:13
at s.set in src/vs/base/common/observableInternal/base.ts:445:9
at y.setVisible in src/vs/workbench/contrib/notebook/browser/viewModel/cellOutputViewModel.ts:31:16
at a.updateOutputHeight in src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts:449:34
at Pe.Wc in src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:3039:9
at u.value in src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:623:29
at o.B in src/vs/base/common/event.ts:1230:13
at o.fire in src/vs/base/common/event.ts:1261:9
at <anonymous> in src/vs/workbench/contrib/webview/browser/webviewElement.ts:198:20
at handler in src/vs/workbench/contrib/webview/browser/webviewElement.ts:510:35
at Set.forEach (<anonymous>)
at H.onmessage in src/vs/workbench/contrib/webview/browser/webviewElement.ts:510:16
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=fee1edb8d6d72a0ddff41e5f71a671c23ed924b9&bH=ba511a03-9df7-9d4f-76b4-5e17f6634dc8)

**Comment by chrmarti** [comment]
Similar in 1.92.2:
```
Error

 [at c.create in src/vs/base/common/event.ts:921:15](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/event.ts#L921:15)

 [at b.q [as onDidChangeContext] in src/vs/base/common/event.ts:1128:34](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/event.ts#L1128:34)

 [at b.n in src/vs/platform/contextkey/browser/contextKeyService.ts:453:51](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/platform/contextkey/browser/contextKeyService.ts#L453:51)

 [at b in src/vs/platform/contextkey/browser/contextKeyService.ts:437:8](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/platform/contextkey/browser/contextKeyService.ts#L437:8)

 [at b.createScoped in src/vs/platform/contextkey/browser/contextKeyService.ts:307:10](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/platform/contextkey/browser/contextKeyService.ts#L307:10)

 [at D.G in src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts:329:84](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts#L329:84)

 [at p._runFn in src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts:218:11](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts#L218:11)

 [at p.j in src/vs/base/common/observableInternal/autorun.ts:196:10](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/observableInternal/autorun.ts#L196:10)

 [at p.endUpdate in src/vs/base/common/observableInternal/autorun.ts:237:10](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/observableInternal/autorun.ts#L237:10)

 [at d.finish in src/vs/base/common/observableInternal/base.ts:372:13](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/observableInternal/base.ts#L372:13)

 [at s.set in src/vs/base/common/observableInternal/base.ts:445:9](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/observableInternal/base.ts#L445:9)

 [at y.setVisible in src/vs/workbench/contrib/notebook/browser/viewModel/cellOutputViewModel.ts:31:16](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/notebook/browser/viewModel/cellOutputViewModel.ts#L31:16)

 [at a.updateOutputHeight in src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts:449:34](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts#L449:34)

 [at Pe.Wc in src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:3039:9](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L3039:9)

 [at u.value in src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:623:29](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L623:29)

 [at o.B in src/vs/base/common/event.ts:1230:13](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/event.ts#L1230:13)

 [at o.fire in src/vs/base/common/event.ts:1261:9](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/base/common/event.ts#L1261:9)

 [at <anonymous> in src/vs/workbench/contrib/webview/browser/webviewElement.ts:198:20](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L198:20)

 [at handler in src/vs/workbench/contrib/webview/browser/webviewElement.ts:510:35](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L510:35)
at Set.forEach (<anonymous>)

 [at H.onmessage in src/vs/workbench/contrib/webview/browser/webviewElement.ts:510:16](https://vscode.dev/github/microsoft/vscode/blob/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L510:16)
```
