### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by FloMaetschke** [Microsoft/vscode#22603]
- VSCode Version: git latest (How to contribute)
- OS Version: Windows 2008 R2

Steps to Reproduce:

.\scripts\npm install
```

116198 error Windows_NT 6.1.7601
116199 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MYUSER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
116200 error node v7.7.2
116201 error npm  v4.2.0
116202 error code ELIFECYCLE
116203 error errno 1
116204 error vscode-ripgrep@0.0.7 postinstall: `node ./src/postinstall.js`
116204 error Exit status 1
116205 error Failed at the vscode-ripgrep@0.0.7 postinstall script 'node ./src/postinstall.js'.
116205 error Make sure you have the latest version of node.js and npm installed.
116205 error If you do, this is most likely a problem with the vscode-ripgrep package,
116205 error not with npm itself.
116205 error Tell the author that this fails on your system:
116205 error     node ./src/postinstall.js
116205 error You can get information on how to open an issue for this project with:
116205 error     npm bugs vscode-ripgrep
116205 error Or if that isn't available, you can get their info via:
116205 error     npm owner ls vscode-ripgrep
116205 error There is likely additional logging output above.
116206 verbose exit [ 1, true ]

```

Any idea how to fix this postinstall error?

**Comment by roblourens** [comment]
Can you look up in the log for mentions of `vscode-ripgrep`? There should be another error message. 

And a workaround: just remove the `vscode-ripgrep` entries in package.json and npm-shrinkwrap.json.

**Comment by FloMaetschke** [comment]
Thx, this worked. .\scripts\npm install returned ok.

Here is the other part of the log:

```
116195 verbose stack Error: vscode-ripgrep@0.0.7 postinstall: `node ./src/postinstall.js`
116195 verbose stack Exit status 1
116195 verbose stack     at EventEmitter.<anonymous> (C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
116195 verbose stack     at emitTwo (events.js:106:13)
116195 verbose stack     at EventEmitter.emit (events.js:194:7)
116195 verbose stack     at ChildProcess.<anonymous> (C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
116195 verbose stack     at emitTwo (events.js:106:13)
116195 verbose stack     at ChildProcess.emit (events.js:194:7)
116195 verbose stack     at maybeClose (internal/child_process.js:899:16)
116195 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
116196 verbose pkgid vscode-ripgrep@0.0.7
116197 verbose cwd D:\code
```

After that I tried executing the watch task, which is running fine, too.
But the actual start of code failed:

D:\code (master) (code-oss-dev@1.11.0)
λ .\scripts\code
[12:40:57] Using gulpfile D:\code\gulpfile.js
[12:40:57] Starting 'clean-electron'...
[12:40:57] Finished 'clean-electron' after 1.84 ms
[12:40:57] Starting 'electron'...
_http_client.js:86
      throw new TypeError('Request path contains unescaped characters');
      ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:86:13)
    at TunnelingAgent.request (http.js:26:10)
    at TunnelingAgent.createSocket (D:\code\node_modules\tunnel-agent\index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (D:\code\node_modules\tunnel-agent\index.js:184:41)
    at TunnelingAgent.addRequest (D:\code\node_modules\tunnel-agent\index.js:80:8)
    at new ClientRequest (_http_client.js:212:16)
    at Object.request (http.js:26:10)
    at Object.request (https.js:206:15)
    at Request.start (D:\code\node_modules\request\request.js:584:30)
    at Request.end (D:\code\node_modules\request\request.js:1212:28)
    at D:\code\node_modules\request\request.js:416:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[12:40:59] Using gulpfile D:\code\gulpfile.js
[12:40:59] Starting 'clean-electron'...
[12:40:59] Finished 'clean-electron' after 1.91 ms
[12:40:59] Starting 'electron'...
_http_client.js:86
      throw new TypeError('Request path contains unescaped characters');
      ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:86:13)
    at TunnelingAgent.request (http.js:26:10)
    at TunnelingAgent.createSocket (D:\code\node_modules\tunnel-agent\index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (D:\code\node_modules\tunnel-agent\index.js:184:41)
    at TunnelingAgent.addRequest (D:\code\node_modules\tunnel-agent\index.js:80:8)
    at new ClientRequest (_http_client.js:212:16)
    at Object.request (http.js:26:10)
    at Object.request (https.js:206:15)
    at Request.start (D:\code\node_modules\request\request.js:584:30)
    at Request.end (D:\code\node_modules\request\request.js:1212:28)
    at D:\code\node_modules\request\request.js:416:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
The system cannot find the path specified.

D:\code (master) (code-oss-dev@1.11.0)

**Comment by roblourens** [comment]
I think that other vscode-ripgrep error might just be the stack from it shutting down. Is there any other error or mention of it further up in the log?

I don't know about the errors from starting up. That's not related to vscode-ripgrpe.

**Comment by FloMaetschke** [comment]
i guess vscode ripgrep is causing the error because it has to use a proxy connection?

**Comment by roblourens** [comment]
Oh, it does try to download something. But we download Electron too.

Do you see the "Request path contains unescaped characters" errors even after removing 'vscode-ripgrep' from the package.json and npm-shrinkwrap, running install again, and building?

**Comment by charles8xu** [comment]
same issue as @FloMaetschke 

- VSCode Version : latest commit [(def13c6d78)](https://github.com/Microsoft/vscode/commit/def13c6d788648100648830b4864b31264e41669)
- OS : macOS Sierra 10.12.5
- node: v6.11.0
- npm: v5.0.3

execute `./scripts/npm.sh install` using a proxy connection

```
> vscode-ripgrep@0.0.12 postinstall /Users/MYUSER/Projects/vscode/node_modules/vscode-ripgrep
> node ./dist/postinstall.js

_http_client.js:52
    throw new TypeError('Request path contains unescaped characters');
    ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:52:11)
    at TunnelingAgent.exports.request (http.js:31:10)
    at TunnelingAgent.createSocket (/Users/MYUSER/Projects/vscode/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/MYUSER/Projects/vscode/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/Users/MYUSER/Projects/vscode/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:159:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Request.start (/Users/MYUSER/Projects/vscode/node_modules/request/request.js:584:30)
    at Request.end (/Users/MYUSER/Projects/vscode/node_modules/request/request.js:1212:28)
(node:27615) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-mutex@0.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 (node_modules/windows-foreground-love):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-foreground-love@0.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-ripgrep@0.0.12 postinstall: `node ./dist/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-ripgrep@0.0.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

@roblourens  after removing 'vscode-ripgrep' from the package.json and npm-shrinkwrap.json,it works well
