### ISSUE TITLE
Build failed: git smoke test

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#226025]
Three macOS integration tests failed related to git smoke tests.  Does not appear to be related to the given change

Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=288643
Changes: https://github.com/Microsoft/vscode/compare/36257be...9550d27

```
  1) git smoke test
       opens diff editor:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
      + actual - expected

+ '/private/var/folders/cy/09t6wxdj6qn64c5q9_kr6czr0000gn/T/tmp.bsDNoDii/newfile.txt'
- '/private/var/folders/cy/09t6wxdj6qn64c5q9_kr6czr0000gn/T/tmp.bsDNoDii/app.js'
      + expected - actual

      -/private/var/folders/cy/09t6wxdj6qn64c5q9_kr6czr0000gn/T/tmp.bsDNoDii/newfile.txt
      +/private/var/folders/cy/09t6wxdj6qn64c5q9_kr6czr0000gn/T/tmp.bsDNoDii/app.js
      
      at Context.<anonymous> (extensions/git/src/test/smoke.test.ts:94:10)
```

```
  2) git smoke test
       stages correctly:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 1

      + expected - actual

      -2
      +1
      
      at Context.<anonymous> (extensions/git/src/test/smoke.test.ts:104:10)
```

```
  3) git smoke test
       stages, commits changes and verifies outgoing change:
     Failed to execute git
  {
    "exitCode": 1,
    "gitCommand": "-c",
    "stdout": "On branch main\nChanges not staged for commit:\n\tmodified:   app.js\n\nUntracked files:\n\tnewfile.txt\n\nno changes added to commit\n",
    "stderr": ""
  }
      at Git._exec (extensions/git/src/git.ts:629:52)
      at Git.exec (extensions/git/src/git.ts:561:10)
      at Repository.exec (extensions/git/src/git.ts:1088:10)
      at Repository.commit (extensions/git/src/git.ts:1705:4)
      at /Users/runner/work/1/s/extensions/git/src/repository.ts:1265:6
      at Repository.retryRun (extensions/git/src/repository.ts:2122:12)
      at Repository.run (extensions/git/src/repository.ts:2091:19)
      at Repository.commit (extensions/git/src/repository.ts:1250:4)
      at Context.<anonymous> (extensions/git/src/test/smoke.test.ts:120:3)

WebSocket connection to 'ws://localhost:8000/insider-9550d27676254ee870e7b6bae419e184b2f55ab4?reconnectionToken=4f3b2621-236d-451d-962b-f810e53792ea&reconnection=false&skipWebSocketFrames=false' failed: The operation couldn’t be completed. Socket is not connected []


```

**Comment by lszomoru** [comment]
Closing this as recently we have made improvements to the git integration tests.
