### ISSUE TITLE
Python code in VSC not launching

### ISSUE THREAD

**Issue by iusegomme** [microsoft/vscode#226155]
Type: <b>Bug</b>

Traceback (most recent call last):
  File "c:\Users\NixSe\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\NixSe\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\__main__.py", line 39, in <module>     
    cli.main()
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 268, in run_file
    start_debugging(target)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 258, in start_debugging
    debugpy.connect(options.address, access_token=options.adapter_access_token)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\api.py", line 297, in connect
    _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\api.py", line 45, in _settrace
    return pydevd.settrace(*args, **kwargs)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydevd.py", line 2821, in settrace
    _locked_settrace(
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydevd.py", line 2942, in _locked_settrace
    py_db.patch_threads()
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydevd.py", line 2392, in patch_threads
    patch_thread_modules()
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 1205, in patch_thread_modules
    patch_thread_module(t)
  File "c:\Users\NixSe\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 1168, in patch_thread_module
    _original_start_new_thread = thread_module._original_start_new_thread = thread_module.start_new_thread
AttributeError: module 'thread' has no attribute 'start_new_thread'

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.58GB free)|
|Process Argv|--crash-reporter-id 5c220058-759d-4ca1-be06-debdd6e0c26b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.42.0
discord-vscode|icr|5.8.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-c:31118571
fje88620:31121564

```

</details>

**Comment by roblourens** [comment]
Please file on the Python extension repo with more details
