### ISSUE TITLE
Cannot split a terminal without a group

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#226494]
- In vscode repo, the main build task is running in a split terminal
- I ctrl+D killed it
- Now when I try to run the build task again, I get this error

```
2024-08-23 14:29:37.044 [error] Cannot split a terminal without a group (instanceId: 2, title: node): Error: Cannot split a terminal without a group (instanceId: 2, title: node)
    at _.Sb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2661:38762)
    at _.createTerminal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2661:37511)
    at async N.Cb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1753:17478)
    at async N.Fb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1753:20250)
    at async N.xb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1753:8830)
    at async Promise.all (index 1)
```

Had to reload the window, then it went away.

**Comment by Tyriar** [comment]
This exception shouldn't be reachable:

https://github.com/microsoft/vscode/blob/f9d0fc9181d346d273605957f977a0b41b22b5c5/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L1076-L1085

Looking at duplicate https://github.com/microsoft/vscode/issues/231083, my guess is that this is happening because tasks is creating split terminals too quickly before the parent terminal instance is registered in the terminal group service?
