### ISSUE TITLE
Using Unittest instead of PyTest

### ISSUE THREAD

**Issue by JLenzy** [microsoft/vscode#226837]
I need to use pytest for my project but VSCode seems to be looking for the tests with unittest:

```
2024-08-27 13:40:52.737 [error] Unittest test discovery error for workspace:  /Users/user/Desktop/lemonaide/MidiTok 
 Failed to import test module: test_attribute_controls
Traceback (most recent call last):
  File "/Users/user/opt/miniconda3/envs/pertok/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/user/opt/miniconda3/envs/pertok/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/user/Desktop/lemonaide/MidiTok/tests/test_attribute_controls.py", line 14, in <module>
    from .utils_tests import (
ImportError: attempted relative import with no known parent package
```

I have this in both my user and workspace settings:
```
"python.testing.unittestEnabled": false,
"python.testing.pytestEnabled": true
```

And have also tried manually selecting `pytest` under `Python: Configure Tests'

**Comment by eleanorjboyd** [comment]
Hi! Could you include your whole logs? I am having trouble narrowing down how it arrived at that file to error. Thanks!

**Comment by rzhao271** [comment]
Hi @JLenzy, are you still seeing the issue with the latest versions of VS Code and the VS Code Python extension?
