### ISSUE TITLE
Suggest doesn't work with terminal in editor area

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#226865]
1. Enable terminal suggest.
2. Create a new pwsh terminal in the editor area.
3. Start typing.
4. :bug: Terminal freezes but the rest of VS Code is OK.

```
Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at new h (simpleSuggestWidget.ts:95:19)
    at f.o (instantiationService.ts:162:18)
    at f.createInstance (instantiationService.ts:128:18)
    at y.mb (terminalSuggestAddon.ts:540:68)
    at y.lb (terminalSuggestAddon.ts:510:30)
    at y.cb (terminalSuggestAddon.ts:398:8)
    at y.$ (terminalSuggestAddon.ts:321:10)
    at t.OscHandler._handler (terminalSuggestAddon.ts:178:16)
    at t.OscHandler.end (OscParser.ts:223:18)
    at t.OscParser.end (OscParser.ts:159:45)
    at h.parse (EscapeSequenceParser.ts:777:43)
    at D.parse (InputHandler.ts:485:35)
    at n._action (CoreTerminal.ts:141:100)
    at n._innerWrite (WriteBuffer.ts:164:27)
    at WriteBuffer.ts:124:29
```

**Comment by Tyriar** [comment]
Not a regression so moving to September.
