### ISSUE TITLE
ERR Illegal value for lineNumber: Error: Illegal value for lineNumber

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#227070]
Sorry, not repro steps but a non-minified stacktrace ⏬ 

```
  ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at TextModel.getLineMaxColumn (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:638:23)
    at CodeEditorWidget.getBottomForLineNumber (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/browser/widget/codeEditor/codeEditorWidget.js:412:50)
    at StickyScrollController.findScrollWidgetState (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/contrib/stickyScroll/browser/stickyScrollController.js:513:62)
    at StickyScrollController._updateState (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/contrib/stickyScroll/browser/stickyScrollController.js:481:38)
    at async StickyScrollController._renderStickyScroll (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/contrib/stickyScroll/browser/stickyScrollController.js:440:21)
```

**Comment by aiday-mar** [comment]
Recently fixed, should not happen anymore
