### ISSUE TITLE
ERR Session already stored for vs.editor.ICodeEditor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#227052]
This is from [here](https://github.com/microsoft/vscode/blob/c95571667318a8ff30e27e7302f29cc6318a4001/src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts#L649) and happens when for the target file a session already exists (of which can only exist one)

```
 ERR Session already stored for vs.editor.ICodeEditor:3@file:///Users/jrieken/Code/vscode/src/vs/editor/test/common/core/range.test.ts: Error: Session already stored for vs.editor.ICodeEditor:3@file:///Users/jrieken/Code/vscode/src/vs/editor/test/common/core/range.test.ts
    at InlineChatSessionServiceImpl.createSession (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/inlineChat/browser/inlineChatSessionServiceImpl.js:138:23)
    at async UniqueContainer.value (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/inlineChat/browser/inlineChatController.js:520:40)
```

**Comment by jrieken** [comment]
Steps

* open range.ts
* open range.test.ts and just start inline chat
* back in range.ts, invoke inline for a function and prompt `/test`
* 💥
