### ISSUE TITLE
ERR InstantiationService has been disposed

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#227073]
* open side by side editors
* in the RHS start and finish an inline chat session
* close the editor group
* 🐛 the error below happens

```
ERR InstantiationService has been disposed: Error: InstantiationService has been disposed
    at InstantiationService._throwIfDisposed (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:47:23)
    at InstantiationService.createInstance (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:18)
    at createActionViewItem (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/platform/actions/browser/menuEntryActionViewItem.js:485:33)
    at Object.actionViewItemProvider (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/chat/browser/chatListRenderer.js:223:83)
    at Object.actionViewItemProvider (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/toolbar/toolbar.js:75:48)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:277:41
    at Array.forEach (<anonymous>)
    at ActionBar.push (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:270:21)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/toolbar/toolbar.js:148:32
    at Array.forEach (<anonymous>)
    at MenuWorkbenchToolBar.setActions (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/toolbar/toolbar.js:147:33)
    at MenuWorkbenchToolBar.setActions (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/platform/actions/browser/toolbar.js:116:19)
    at updateToolbar (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/platform/actions/browser/toolbar.js:229:23)
    at UniqueContainer.value (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/platform/actions/browser/toolbar.js:232:17)
    at DebounceEmitter._deliver (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:967:26)
    at DebounceEmitter.fire (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:996:22)
    at DebounceEmitter.resume (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:1102:31)
    at vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/common/event.js:1136:26
log.ts:439
```

**Comment by roblourens** [comment]
Ouch, don't look at the PR.

But actually, I guess I haven't done much profiling for scenarios that involve multiple chat widgets. It seems like there is still a leak involving ChatEditors, but I don't know why, will debug more.
