### ISSUE TITLE
Flaky `Ternary Search Tree` test

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#227147]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=130125&view=logs&j=f3dd96f0-7bf9-51c6-1e87-22c4cfa2ad69&t=cf063406-446c-522c-4fbd-8e958d7b189e

```
  8800 passing (3m)
  74 pending
  1 failing

  1) Ternary Search Tree
       TernarySearchTree: Cannot read property '1' of undefined #138284 (random):
     
  RangeError: Invalid array length
      at Array.push (<anonymous>)
      at TernarySearchTree._delete (http://localhost:33887/079953d7545e7ca308c82fce64738984/out/vs/base/common/ternarySearchTree.js:427:27)
      at TernarySearchTree._delete (http://localhost:33887/079953d7545e7ca308c82fce64738984/out/vs/base/common/ternarySearchTree.js:466:30)
      at TernarySearchTree.delete (http://localhost:33887/079953d7545e7ca308c82fce64738984/out/vs/base/common/ternarySearchTree.js:415:25)
      at Context.<anonymous> (http://localhost:33887/079953d7545e7ca308c82fce64738984/out/vs/base/test/common/ternarySearchtree.test.js:732:31)

```

**Comment by bpasero** [comment]
Failed again in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=329759&view=logs&j=fc6dc5ac-1218-5601-53e8-73849b99230e&t=74d800e8-a56c-5f19-ff50-077eaeb6e1d0&l=13389

**Comment by jrieken** [comment]
Finally
