### ISSUE TITLE
ERR Attempting to register step with id extensionsWeb twice. Second is dropped.: Error: Attempting to register step with id extensionsWeb twice. 

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode#227280]
Type: <b>Bug</b>

  ERR Attempting to register step with id extensionsWeb twice. Second is dropped.: Error: Attempting to register step with id extensionsWeb twice. Second is dropped.
    at vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:520830:27
    at Array.forEach (<anonymous>)
    at $F_b._registerWalkthrough (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:520828:41)
    at vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:520507:22
    at Array.forEach (<anonymous>)
    at $F_b.S (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:520506:42)
    at new $F_b (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:520503:18)
    at $Er.o (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:123856:28)
    at vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:123986:42
    at $4h.d (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:61245:30)
    at get value (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:61262:22)
    at Object.get (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:124033:42)
    at new $Hac (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:606291:31)
    at $Er.o (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:123856:28)
    at $Er.createInstance (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:123827:31)
    at $Frb.instantiate (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:525155:47)
    at $wLb.Q (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:526201:50)
    at $wLb.P (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:526181:37)
    at $wLb.O (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:526160:37)
    at $wLb.L (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:526097:31)
    at $wLb.openEditor (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:526000:35)
    at vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:563153:78
    at $yLb.Kb (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:563172:19)
    at $yLb.Jb (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:563138:43)
    at $yLb.openEditor (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:563051:25)
    at $iMb.openEditor (vscode-file://vscode-app/c:/Users/artist/AppData/Local/Programs/Microsoft%20Code%20OSS/resources/app/out/vs/workbench/workbench.desktop.main.js:540594:26)

VS Code version: Code - OSS 1.93.0 (deed0fb5213f2f47ed43fa2c0a9259309050b831, 2024-08-31T07:53:45.858Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.39GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.6
reveal-button|anw|1.1.1
prettier-vscode|esb|11.0.0
file-icons|fil|1.1.0
vscode-language-pack-zh-hans|MS-|1.93.2024082809
remote-containers|ms-|0.383.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vim|vsc|1.28.0

(1 theme extensions excluded)

</details>

**Comment by AlaricWeb** [comment]
Isn't the code for the main branch up to date

**Comment by bhavyaus** [comment]
@AlaricWeb which extension were you trying to install?

**Comment by AlaricWeb** [comment]
> @AlaricWeb您想安装哪个扩展？
I already took care of it
