### ISSUE TITLE
Terminal Smoke Test on Windows times out after build agent update

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#227366]
This started failing after an update to the build agent which shouldn't be related, but likely triggered a timing issue:
```
1) VSCode Smoke Tests (Electron)
       Terminal
         Terminal Persistence
           detach/attach
             should support basic reconnection:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:163:16)
      at async QuickInput.waitForQuickInputClosed (D:\a\_work\1\s\test\automation\out\quickinput.js:32:9)
      at async Terminal.runCommandWithValue (D:\a\_work\1\s\test\automation\out\terminal.js:110:9)
      at async Context.<anonymous> (out\areas\terminal\terminal-persistence.test.js:41:17)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=290842&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=9ab437b3-ee70-5588-b120-442542e6d570

/cc @lszomoru 

Revert: https://github.com/microsoft/vscode/pull/227353

**Comment by chrmarti** [comment]
@Tyriar Additionally there were 2 commits from you that added test failures to the main build. I have reverted these in https://github.com/microsoft/vscode/pull/227353 too. Please also take a look at these.
