### ISSUE TITLE
Task Smoke Tests on Windows time out after build agent update

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#227367]
These started failing after an update to the build agent which shouldn't be related, but likely triggered a timing issue:
```
2) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon only:
     Error: Timeout: get element '.single-terminal-tab .codicon' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:163:16)
      at async Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\out\terminal.js:227:17)
      at async Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\out\terminal.js:158:9)
      at async Task.assertTasks (D:\a\_work\1\s\test\automation\out\task.js:37:17)
      at async Context.<anonymous> (out\areas\task\task-quick-pick.test.js:43:17)

  3) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - color only:
     Error: Timeout: get element '.single-terminal-tab' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:163:16)
      at async Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\out\terminal.js:223:17)
      at async Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\out\terminal.js:158:9)
      at async Task.assertTasks (D:\a\_work\1\s\test\automation\out\task.js:37:17)
      at async Context.<anonymous> (out\areas\task\task-quick-pick.test.js:48:17)

  4) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon & color:
     Error: Timeout: get element '.single-terminal-tab' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:163:16)
      at async Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\out\terminal.js:223:17)
      at async Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\out\terminal.js:158:9)
      at async Task.assertTasks (D:\a\_work\1\s\test\automation\out\task.js:37:17)
      at async Context.<anonymous> (out\areas\task\task-quick-pick.test.js:53:17)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=290842&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=9ab437b3-ee70-5588-b120-442542e6d570

/cc @lszomoru 

Revert: https://github.com/microsoft/vscode/pull/227353

**Comment by alexr00** [comment]
Still failing: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=348015&view=logs&j=45e2b0b5-0069-506f-d663-629b6db3a5d5&t=7cde2c7d-5236-5b41-5514-673b49f2139d

**Comment by alexr00** [comment]
I think we now run these on the PR builds too, so this may start blocking PRs.

**Comment by Tyriar** [comment]
For the most recent run https://dev.azure.com/monacotools/Monaco/_build/results?buildId=348015&view=logs&j=45e2b0b5-0069-506f-d663-629b6db3a5d5&t=7cde2c7d-5236-5b41-5514-673b49f2139d

It does what it's meant to do to run the task, but the pty host crashed so nothing happens:

<img width="1224" height="934" alt="Image" src="https://github.com/user-attachments/assets/5790fd0a-6add-421d-8fbb-fb6fb5c2debe" />

**Comment by Tyriar** [comment]
ptyHost heartbeat failure mentioned in main.log:

```
2025-07-08 12:25:45.111 [info] lifecycle (main): phase changed (value: 2)
2025-07-08 12:25:45.144 [info] lifecycle (main): phase changed (value: 3)
2025-07-08 12:25:45.145 [info] update#setState disabled
2025-07-08 12:25:45.145 [info] update#ctor - updates are disabled by the environment
2025-07-08 12:25:47.654 [info] lifecycle (main): phase changed (value: 4)
2025-07-08 12:26:14.384 [warning] No ptyHost heartbeat after 6 seconds
2025-07-08 12:26:19.400 [error] No ptyHost heartbeat after 12 seconds
2025-07-08 12:30:57.795 [info] Lifecycle#app.on(before-quit)
2025-07-08 12:30:57.796 [info] Lifecycle#onBeforeShutdown.fire()
2025-07-08 12:30:57.796 [info] Lifecycle#window.on('close') - window ID 1
2025-07-08 12:30:57.797 [info] Lifecycle#unload() - window ID 1
2025-07-08 12:30:57.813 [info] Extension host with pid 6820 exited with code: 0, signal: unknown.
2025-07-08 12:30:57.855 [info] Lifecycle#onBeforeCloseWindow.fire() - window ID 1
2025-07-08 12:30:57.862 [info] Lifecycle#window.on('closed') - window ID 1
2025-07-08 12:30:57.863 [info] Lifecycle#onWillShutdown.fire()
2025-07-08 12:30:57.865 [info] Lifecycle#app.on(window-all-closed)
2025-07-08 12:30:57.865 [info] Lifecycle#app.on(will-quit) - begin
2025-07-08 12:30:57.894 [info] Lifecycle#app.on(will-quit) - after fireOnWillShutdown
2025-07-08 12:30:57.894 [info] Lifecycle#app.on(will-quit) - calling app.quit()
```

**Comment by Tyriar** [comment]
@deepak1556 any idea how we can get more information about the pty host crash in CI/in general?

**Comment by bpasero** [comment]
Again in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=348714&view=logs&j=45e2b0b5-0069-506f-d663-629b6db3a5d5&t=7cde2c7d-5236-5b41-5514-673b49f2139d&l=203

```
1) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon only:
     Error: Timeout: get element '.single-terminal-tab .codicon' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:233:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:189:16)
      at async Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\out\terminal.js:237:17)
      at async Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\out\terminal.js:168:9)
      at async Task.assertTasks (D:\a\_work\1\s\test\automation\out\task.js:38:17)
      at async Context.<anonymous> (out\areas\task\task-quick-pick.test.js:43:17)

2) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - color only:
     Error: Timeout: get element '.single-terminal-tab' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:233:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:189:16)
      at async Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\out\terminal.js:233:17)
      at async Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\out\terminal.js:168:9)
      at async Task.assertTasks (D:\a\_work\1\s\test\automation\out\task.js:38:17)
      at async Context.<anonymous> (out\areas\task\task-quick-pick.test.js:48:17)

3) VSCode Smoke Tests (Electron)
       Task
         Task Quick Pick
           Tasks: Run Task
             icon - icon & color:
     Error: Timeout: get element '.single-terminal-tab' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:233:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:189:16)
      at async Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\out\terminal.js:233:17)
      at async Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\out\terminal.js:168:9)
      at async Task.assertTasks (D:\a\_work\1\s\test\automation\out\task.js:38:17)
      at async Context.<anonymous> (out\areas\task\task-quick-pick.test.js:53:17)
```

**Comment by deepak1556** [comment]
@Tyriar crashes from any process would automatically be collected and uploaded to the CI artifacts today, for ex:

<img width="1145" height="580" alt="Image" src="https://github.com/user-attachments/assets/f3504b10-026c-4a0c-bd30-7e998a7e5b66" />

However I don't see any crash dumps associated with the task suite for the runs shared here, wonder if there is something other than a crash happening in ptyhost. As a good next step, lets run the windows smoketests with `--verbose`. The current main and ptyhost logs don't contain any information on process launches.

**Comment by aiday-mar** [comment]
Other instance: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=348714&view=results

**Comment by aiday-mar** [comment]
Also this one: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=348680&view=results

**Comment by alexr00** [comment]
These delayed our stable build. Disabled with https://github.com/microsoft/vscode/pull/256249.

**Comment by deepak1556** [comment]
@Tyriar the above run happened in release branch https://monacotools.visualstudio.com/Monaco/_build/results?buildId=348955&view=results and doesn't have the verbose logs, when revisiting in debt week lets get a run with verbose logs to proceed further.

**Comment by deepak1556** [comment]
Oh there is one with verbose logs https://monacotools.visualstudio.com/Monaco/_build/results?buildId=349094&view=results

**Comment by deepak1556** [comment]
@Tyriar the smoketest logs from the above run indicate there is no pty host crash. However, the pty host logs show that the first terminal process gets launched and shutdown immediately. Can you check the logs to see whats happening on the terminal side.

Something else that stands out from the main process logs, we are making setting changes based on policy configurations. Should we be performing policy checks in test runs ? /cc @bpasero 

```
2025-07-16 12:09:45.751 [trace] PolicyConfiguration#initialize
2025-07-16 12:09:45.751 [trace] PolicyConfiguration#updatePolicyDefinitions ["update.mode","update.channel","update.enableWindowsBackgroundUpdates","update.showReleaseNotes","http.useLocalProxyConfiguration","http.electronFetch","http.proxy","http.proxyStrictSSL","http.proxyKerberosServicePrincipal","http.noProxy","http.proxyAuthorization","http.proxySupport","http.systemCertificates","http.experimental.systemCertificatesV2","http.fetchAdditionalSupport","telemetry.telemetryLevel","telemetry.feedback.enabled","telemetry.enableTelemetry","extensions.allowed"]
2025-07-16 12:09:45.751 [trace] NativePolicyService#_updatePolicyDefinitions - Found 4 policy definitions
2025-07-16 12:09:45.751 [trace] NativePolicyService#_onDidPolicyChange - Updated policy values: {}
2025-07-16 12:09:45.751 [trace] PolicyConfiguration#update ["update.mode","telemetry.telemetryLevel","telemetry.feedback.enabled","extensions.allowed"]
2025-07-16 12:09:45.751 [trace] PolicyConfiguration#updatePolicyDefinitions []
2025-07-16 12:09:45.751 [trace] PolicyConfiguration#update []
```

**Comment by bpasero** [comment]
Policy changes are not disabled in test runs. This is something I leave up to @sandy081 and @joshspicer to decide.

**Comment by Tyriar** [comment]
@deepak1556 are you sure we're just logging pty host crashes correctly? The screenshot should only happen when either the pty host is unresponsive in a busy loop for an extended period or the process crashes. I've never had any visibility into pty host crashes, it's launched here for desktop:

https://github.com/microsoft/vscode/blob/d9bb6db34192d312063e6780c5f8f022aa5dacd0/src/vs/platform/terminal/electron-main/electronPtyHostStarter.ts#L50-L65

**Comment by deepak1556** [comment]
Crashes will always get a crash dump and get uploaded to pipeline artifacts. Even if exit code logging was incorrect, crash dumps would have been the source of truth here,

```
2025-07-16 12:09:56.335 [trace] [UtilityProcess type: ptyHost, pid: 5768]: successfully created
...
2025-07-16 12:15:17.345 [trace] [UtilityProcess type: ptyHost, pid: 5768]: received exit event with code 0
```

I can double check the desktop path of pty launch to see if we are logging it incorrectly.

However, I do see in the main process logs that hints an unresponsive loop

```
2025-07-16 12:10:16.343 [warning] No ptyHost heartbeat after 6 seconds
2025-07-16 12:10:21.357 [error] No ptyHost heartbeat after 12 seconds
````

but the ptyhost logs, show

```
2025-07-16 12:09:56.636 [trace] [RPC Request] PtyService#refreshIgnoreProcessNames(["starship","oh-my-posh","bash","zsh"])
2025-07-16 12:09:56.636 [trace] [RPC Response] PtyService#refreshIgnoreProcessNames undefined
2025-07-16 12:09:56.641 [trace] [RPC Request] PtyService#createProcess
...
2025-07-16 12:10:00.249 [trace] [RPC Response] PtyService#start undefined
2025-07-16 12:10:00.249 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":2,"property":{"type":"title","value":"pwsh.exe"}})
2025-07-16 12:10:00.250 [trace] [RPC Event] PtyService#_onDidChangeProperty.fire({"id":2,"property":{"type":"shellType"}})
2025-07-16 12:10:00.252 [trace] [RPC Request] PtyService#resize(2, 11, 13)
2025-07-16 12:10:00.253 [trace] node-pty.IPty#resize 11 13
2025-07-16 12:10:00.253 [trace] [RPC Response] PtyService#resize undefined
2025-07-16 12:10:00.254 [trace] [RPC Request] PtyService#resize(2, 88, 13)
2025-07-16 12:10:00.254 [trace] node-pty.IPty#resize 88 13
2025-07-16 12:10:00.254 [trace] [RPC Response] PtyService#resize undefined
2025-07-16 12:10:00.254 [trace] [RPC Request] PtyService#resize(2, 98, 13)
2025-07-16 12:10:00.255 [trace] node-pty.IPty#resize 98 13
2025-07-16 12:10:00.255 [trace] [RPC Response] PtyService#resize undefined
2025-07-16 12:10:00.255 [trace] node-pty.IPty#onData [6n
2025-07-16 12:10:00.262 [trace] [RPC Event] PtyService#_onProcessData.fire({"id":2,"event":"\u001b[6n"})
2025-07-16 12:10:00.268 [trace] [RPC Request] PtyService#shutdown(2, false)
2025-07-16 12:10:00.268 [trace] TerminalProcess#shutdown 
    at _s.shutdown (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:33:9257)
    at bu.shutdown (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:46:11809)
    at I.shutdown (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:46:2687)
    at i.<computed> (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:45:2938)
    at Object.call (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:28:4204)
    at Zr.s (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:81498)
    at Zr.q (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:81021)
    at pi.value (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:80423)
    at x.C (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:2373)
    at x.D (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:2443)
    at x.fire (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:2660)
    at MessagePortMain.C (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:24:30134)
    at MessagePortMain.emit (node:events:518:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:3073)
2025-07-16 12:10:00.268 [trace] TerminalProcess#_queueProcessExit 
    at _s.X (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:33:8194)
    at _s.shutdown (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:33:9348)
    at bu.shutdown (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:46:11809)
    at I.shutdown (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:46:2687)
    at i.<computed> (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:45:2938)
    at Object.call (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:28:4204)
    at Zr.s (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:81498)
    at Zr.q (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:81021)
    at pi.value (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:80423)
    at x.C (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:2373)
    at x.D (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:2443)
    at x.fire (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:26:2660)
    at MessagePortMain.C (file:///d:/a/_work/1/test/VSCode-win32-x64/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:24:30134)
    at MessagePortMain.emit (node:events:518:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:3073)
2025-07-16 12:10:00.268 [trace] [RPC Response] PtyService#shutdown undefined
2025-07-16 12:10:00.287 [trace] [RPC Request] PtyService#getLatency()
2025-07-16 12:10:00.287 [trace] [RPC Response] PtyService#getLatency []
2025-07-16 12:10:00.288 [trace] [RPC Request] PtyService#getLatency()
2025-07-16 12:10:00.288 [trace] [RPC Response] PtyService#getLatency []
2025-07-16 12:10:00.519 [trace] node-pty.IPty#kill
```

The ptyhost was created at `12:09` and the heartbeat checks came around `12:10:16`, the pty host stopped logging at `12:10:00`. @Tyriar Does any of the process launched and killed in the ptyhost logs match with the test suite ? otherwise we should pursue this with the host being unresponsive and collect cpu profiles.

**Comment by Tyriar** [comment]
Haven't seen this failure since afaik, going to close for now.
