### ISSUE TITLE
TreeError [SettingsTree] Tree element not found

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#227426]
Steps:
- fresh user data dir
- start up (out of sources)
- open settings editor
- close welcome
- quit
- start again:

```
ERR color: #f33 TreeError [SettingsTree] Tree element not found: [object Object]: Error: TreeError [SettingsTree] Tree element not found: [object Object]
    at NonCollapsibleObjectTreeModel.getElementLocation (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:218:19)
    at NonCollapsibleObjectTreeModel.rerender (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:121:31)
    at SettingsTree.rerender (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/browser/ui/tree/objectTree.js:31:20)
    at SettingsEditor2.refreshSingleElement (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1257:31)
    at SettingsEditor2.renderTree (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1240:22)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1187:38
    at Set.forEach (<anonymous>)
    at SettingsEditor2.updateElementsByKey (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1187:18)
    at UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:215:22)
    at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:964:22)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:993:18)
    at WorkspaceService.updateRestrictedSettings (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:738:49)
    at WorkspaceService.onDefaultConfigurationChanged (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:630:18)
    at UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:116:110)
    at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:964:22)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:993:18)
    at DefaultConfiguration.onDidUpdateConfiguration (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/configuration/common/configurations.js:46:40)
    at DefaultConfiguration.onDidUpdateConfiguration (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/configuration/browser/configuration.js:68:15)
    at UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/configuration/common/configurations.js:37:131)
    at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:964:22)
    at Emitter._deliverQueue (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:975:18)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:998:18)
    at ConfigurationRegistry.deltaConfiguration (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/platform/configuration/common/configurationRegistry.js:306:40)
    at ExtensionPoint._handler (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/api/common/configurationExtensionPoint.js:265:27)
    at ExtensionPoint._handle (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/extensionsRegistry.js:96:18)
    at ExtensionPoint.acceptUsers (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/extensionsRegistry.js:89:14)
    at AbstractExtensionService._handleExtensionPoint (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:936:24)
    at NativeExtensionService._doHandleExtensionPoints (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:884:44)
    at NativeExtensionService._processExtensions (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:425:14)
    at NativeExtensionService._initialize (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:381:18)
```

**Comment by wszgrcy** [comment]
build code-oss
open settings
reload window
```
  ERR TreeError [SettingsTree] Tree element not found: [object Object]: Error: TreeError [SettingsTree] Tree element not found: [object Object]
    at NonCollapsibleObjectTreeModel.getElementLocation (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:218:19)
    at NonCollapsibleObjectTreeModel.rerender (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:121:31)
    at SettingsTree.rerender (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/base/browser/ui/tree/objectTree.js:30:20)
    at SettingsEditor2.refreshSingleElement (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1263:31)
    at SettingsEditor2.renderTree (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1246:22)
    at vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1193:38
    at Set.forEach (<anonymous>)
    at SettingsEditor2.updateElementsByKey (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:1193:18)
    at UniqueContainer.value (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/workbench/contrib/preferences/browser/settingsEditor2.js:217:22)
    at Emitter._deliver (vscode-file://vscode-app/c:/code/third-project/vscode/out/vs/base/common/event.js:966:22)
```
