### ISSUE TITLE
Error while fetching extensions. Failed to fetch

### ISSUE THREAD

**Issue by Cartolina-05** [microsoft/vscode#227559]
Type: <b>Feature Request</b>

Hi, I going to install an  extensions , live server, but when i serch this text appears to me: Error while fetching extensions. Failed to fetch, what can i do ?

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by sandy081** [comment]
Can you please share following logs

- F1 > Developer: Toggle Developer Tools
- Output from console.log and also a screenshot of failed requests in network tab

**Comment by bbenginbestas** [comment]
webviewElement.ts:482 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:482
log.ts:419  INFO Started local extension host with pid 9604.
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 
        
        
       Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
log.ts:419  INFO [perf] Render performance baseline is 25ms
log.ts:429  WARN [csharp]: Couldn't find message for key configuration.razor.server.trace.
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 
        
        
       Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
log.ts:439   ERR Failed: Failed to fetch
    at ae.D (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:815:39920)
    at async ae.B (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:815:36691)
    at async ae.getExtensions (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:815:33139)
    at async ne.getExtensions (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2724:15940)
    at async De.Oc (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2660:24242)
    at async De.Xc (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2660:27041)
    at async De.uc (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2660:13448)
    at async vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2660:11707
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 
        
        
       Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
log.ts:439   ERR Failed: Failed to fetch
    at ae.D (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:815:39920)
    at async ae.B (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:815:36691)
    at async ie (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:815:35617)
    at async ae.query (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:815:35915)
    at async ne.queryGallery (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2724:15511)
    at async Le.Kc (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2660:22038)
    at async Le.uc (vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2660:13448)
    at async vscode-file://vscode-app/c:/Users/bbeng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2660:11707
webviewElement.ts:482 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:482
webviewElement.ts:482 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:482

**Comment by bbenginbestas** [comment]
@sandy081

**Comment by sandy081** [comment]
Seems proxy related.

**Comment by chrmarti** [comment]
Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` entering `https://marketplace.visualstudio.com` as the URL?

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

**Comment by bbenginbestas** [comment]
@chrmarti 

Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9)
Network Proxy Test 0.0.12
win32 10.0.19045 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://marketplace.visualstudio.com...
vscode-proxy-agent: DIRECT
Received response:
- Status: 200 OK
Certificate chain:
- Subject: visualstudio.com (Microsoft Corporation)
  Subject alt: DNS:visualstudio.com, DNS:*.visualstudio.com, DNS:*.vsmps.visualstudio.com, DNS:*.vssps.visualstudio.com, DNS:*.vssh.visualstudio.com, DNS:*.vsclt.visualstudio.com, DNS:*.vsrm.visualstudio.com, DNS:*.codelens.visualstudio.com, DNS:*.almsearch.visualstudio.com, DNS:*.csstool.visualstudio.com, DNS:*.artifacts.visualstudio.com, DNS:*.vsblob.visualstudio.com, DNS:*.vsblob.vsassets.io, DNS:*.manage.visualstudio.com, DNS:*.extmgmt.visualstudio.com, DNS:*.marketplace.visualstudio.com, DNS:*.gallery.vsassets.io, DNS:*.pkgs.visualstudio.com, DNS:*.zeus.visualstudio.com, DNS:*.entreq.visualstudio.com, DNS:*.feeds.visualstudio.com, DNS:*.vstsusers.visualstudio.com, DNS:*.portalext.visualstudio.com, DNS:*.analytics.visualstudio.com, DNS:*.my.visualstudio.com, DNS:*.dataimport.visualstudio.com, DNS:*.vstsmms.visualstudio.com, DNS:*.vsaex.visualstudio.com, DNS:*.vslicense.visualstudio.com, DNS:*.vstskalypso.visualstudio.com, DNS:*.vscommerce.visualstudio.com, DNS:*.governance.visualstudio.com, DNS:*.orgsearch.visualstudio.com, DNS:*.portal.visualstudio.com, DNS:*.vskeros.visualstudio.com, DNS:*.vstoken.visualstudio.com, DNS:*.vstmr.visualstudio.com, DNS:*.vscatalog.visualstudio.com, DNS:*.gdprdel.visualstudio.com, DNS:*.userext.visualstudio.com, DNS:*.vsdscops.visualstudio.com, DNS:*.pipelines.visualstudio.com, DNS:*.azboards.visualstudio.com, DNS:*.azminicom.visualstudio.com, DNS:*.commvtwo.visualstudio.com, DNS:*.status.visualstudio.com, DNS:*.vsdevprofile.visualstudio.com, DNS:*.vsevidence.visualstudio.com, DNS:*.vspolicy.visualstudio.com, DNS:*.auditservice.visualstudio.com, DNS:*.vsnotify.visualstudio.com, DNS:*.azchatops.visualstudio.com, DNS:*.azents.visualstudio.com, DNS:*.runtimecatalog.visualstudio.com, DNS:*.artifactcache.visualstudio.com, DNS:*.azpipelines.visualstudio.com, DNS:*.advsec.visualstudio.com, DNS:*.sample.visualstudio.com, DNS:*.vsallin.net, DNS:*.almsearch.vsallin.net, DNS:*.codelens.vsallin.net, DNS:*.csstool.vsallin.net, DNS:*.marketplace.vsallin.net, DNS:*.vsaex.vsallin.net, DNS:*.vscommerce.vsallin.net, DNS:*.vsmps.vsallin.net, DNS:*.vsrm.vsallin.net, DNS:*.vssps.vsallin.net, DNS:*.vsspsext.vsallin.net, DNS:*.vstsusers.vsallin.net, DNS:*.vskeros.vsallin.net, DNS:*.vscatalog.vsallin.net, DNS:*.vsdscops.vsallin.net, DNS:*.vstoken.vsallin.net, DNS:*.gdprdel.vsallin.net, DNS:*.userext.vsallin.net, DNS:*.vslicense.vsallin.net, DNS:*.status.vsallin.net, DNS:*.galleryppe.vsassets.io, DNS:*.vstmrblob.vsassets.io, DNS:*.vstmrblob.vsallin.net, DNS:*.vsassets.io, DNS:*.dpdbot.visualstudio.com
  Validity: Jun 17 05:29:33 2024 GMT - Dec 14 05:29:33 2024 GMT
  Fingerprint: A7:B3:EC:18:0A:43:1F:3C:19:83:AD:BA:41:E3:7B:51:0E:F6:8F:39
- Subject: Microsoft Azure RSA TLS Issuing CA 03 (Microsoft Corporation)
  Validity: Jun  8 00:00:00 2023 GMT - Aug 25 23:59:59 2026 GMT
  Fingerprint: F9:38:8E:A2:C9:B7:D6:32:B6:6A:2B:0B:40:6D:F1:D3:7D:39:01:F6
- Subject: DigiCert Global Root G2 (DigiCert Inc)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Self-signed
Local root certificates:
- Subject: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2 (built-in and OS)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Issuer: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2

Sending GET request to https://marketplace.visualstudio.com using fetch API...
Received response:
- Status: 200

**Comment by bbenginbestas** [comment]
Ah, okay, I think I understand now. It is about my network. My workplace network does not let me connect to http, whereas I can connect to https; that may be the reason.

**Comment by bbenginbestas** [comment]
For the other people with this issue, this is the required information on my workplace network:

Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9)
Network Proxy Test 0.0.12
win32 10.0.19045 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://marketplace.visualstudio.com...
vscode-proxy-agent: DIRECT
Received error: self signed certificate (DEPTH_ZERO_SELF_SIGNED_CERT)
Retrying while ignoring certificate issues to collect information on the certificate chain.

Sending GET request to https://marketplace.visualstudio.com (allowing unauthorized)...
vscode-proxy-agent: DIRECT
Received response:
- Status: 403 Forbidden
Certificate chain:
- Subject: Fortiguard SDNS Blocked Page (Fortinet)
  Validity: Aug 21 21:56:06 2024 GMT - Aug 19 21:56:06 2034 GMT
  Fingerprint: B0:85:5C:96:71:3F:29:51:CF:14:C9:3A:06:6B:69:35:0E:64:FD:9F
  Self-signed

Last certificate not verified by OS root certificates. This might indicate an issue with the root certificates registered in your OS:
- Make sure that the root certificate for the certificate chain is registered as such in the OS. Use `F1` > `Network Proxy Test: Show OS Certificates` to see the list loaded by VS Code.
- Also make sure that your proxy and server return the complete certificate chain (except possibly for the root certificate).

Sending GET request to https://marketplace.visualstudio.com using fetch API...
Received error: net::ERR_CERT_AUTHORITY_INVALID

Sending GET request to https://marketplace.visualstudio.com using fetch API...
Received error: net::ERR_CERT_AUTHORITY_INVALID

**Comment by chrmarti** [comment]
VS Code by itself shouldn't use `http`. Is that something you configure?

**Comment by Kamon2acc** [comment]
I had the same problem on my workplace network.

Here's how I solved it: I disabled the workplace network, enabled internet through USB tethering using my personal phone, downloaded the extensions I needed, and then disabled auto-update for extensions and VS Code.

It's not really a good solution, but it solved my problem.

**Comment by Jonathan5579** [comment]
I had the same problem as @bbenginbestas, my workplace blocks the https://marketplace.visualstudio.com/ webpage, so I cannot access anything related to it. 
Fixed it internally, thanks for your kind support.

**Comment by kl12321** [comment]
I'm having the same issue.The Network Proxy Test extension output these.
Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40)
Network Proxy Test 0.0.12
win32 10.0.22631 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:
http_proxy=127.0.0.1:15732

Sending GET request to https://marketplace.visualstudio.com...
vscode-proxy-agent: PROXY 127.0.0.1:15732
Received error: Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:15732"]
Retrying while ignoring certificate issues to collect information on the certificate chain.

Sending GET request to https://marketplace.visualstudio.com (allowing unauthorized)...
vscode-proxy-agent: PROXY 127.0.0.1:15732
Received error: Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:15732"]

Sending GET request to https://marketplace.visualstudio.com using fetch API...
Received error: net::ERR_PROXY_CONNECTION_FAILED

Sending GET request to https://marketplace.visualstudio.com using fetch API...
Received error: net::ERR_PROXY_CONNECTION_FAILED

**Comment by mahdidev88** [comment]
If you are using VPN or DNS, turn it off. If your VPN is turned off, turn it on and off to resolve the VS code error.

**Comment by habibro0** [comment]
error while fetching extensions failed to fetch 
This  error

**Comment by ER1-53** [comment]
the problem was with my anti-virus, McAfee. It was blocking the fetch. After opening incoming firewall traffic. Problem solved.

**Comment by chrmarti** [comment]
Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code entering `https://marketplace.visualstudio.com` as the URL?

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

**Comment by yoyo837** [comment]
```
Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f)
Network Proxy Test 0.0.14
darwin 24.2.0 arm64

Environment variables:
all_proxy=socks5://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
https_proxy=http://127.0.0.1:7890
no_proxy=::1,localhost,127.0.0.1

DNS Lookup:
- ipv4: 13.107.42.18 (2 ms)
- ipv6: ::ffff:13.107.42.18 (1 ms)

Proxy:
- URL: http://127.0.0.1:7890 (0 ms)
- Connection: 200 Connection established (1 ms)

Sending GET request to https://marketplace.visualstudio.com...
Received response:
- Status: 200 OK
Certificate chain:
- Subject: visualstudio.com (Microsoft Corporation)
  Subject alt: DNS:visualstudio.com, DNS:*.visualstudio.com, DNS:*.vsmps.visualstudio.com, DNS:*.vssps.visualstudio.com, DNS:*.vssh.visualstudio.com, DNS:*.vsclt.visualstudio.com, DNS:*.vsrm.visualstudio.com, DNS:*.codelens.visualstudio.com, DNS:*.almsearch.visualstudio.com, DNS:*.artifacts.visualstudio.com, DNS:*.vsblob.visualstudio.com, DNS:*.vsblob.vsassets.io, DNS:*.manage.visualstudio.com, DNS:*.extmgmt.visualstudio.com, DNS:*.marketplace.visualstudio.com, DNS:*.gallery.vsassets.io, DNS:*.pkgs.visualstudio.com, DNS:*.zeus.visualstudio.com, DNS:*.entreq.visualstudio.com, DNS:*.feeds.visualstudio.com, DNS:*.vstsusers.visualstudio.com, DNS:*.analytics.visualstudio.com, DNS:*.my.visualstudio.com, DNS:*.dataimport.visualstudio.com, DNS:*.vsaex.visualstudio.com, DNS:*.vslicense.visualstudio.com, DNS:*.vstskalypso.visualstudio.com, DNS:*.vscommerce.visualstudio.com, DNS:*.governance.visualstudio.com, DNS:*.vskeros.visualstudio.com, DNS:*.vstoken.visualstudio.com, DNS:*.vstmr.visualstudio.com, DNS:*.vscatalog.visualstudio.com, DNS:*.gdprdel.visualstudio.com, DNS:*.userext.visualstudio.com, DNS:*.vsdscops.visualstudio.com, DNS:*.pipelines.visualstudio.com, DNS:*.azboards.visualstudio.com, DNS:*.azminicom.visualstudio.com, DNS:*.commvtwo.visualstudio.com, DNS:*.status.visualstudio.com, DNS:*.vsdevprofile.visualstudio.com, DNS:*.vsevidence.visualstudio.com, DNS:*.vspolicy.visualstudio.com, DNS:*.auditservice.visualstudio.com, DNS:*.vsnotify.visualstudio.com, DNS:*.azchatops.visualstudio.com, DNS:*.azents.visualstudio.com, DNS:*.runtimecatalog.visualstudio.com, DNS:*.artifactcache.visualstudio.com, DNS:*.azpipelines.visualstudio.com, DNS:*.advsec.visualstudio.com, DNS:*.dpdbot.visualstudio.com, DNS:*.sample.visualstudio.com, DNS:*.vsallin.net, DNS:*.almsearch.vsallin.net, DNS:*.codelens.vsallin.net, DNS:*.marketplace.vsallin.net, DNS:*.vsaex.vsallin.net, DNS:*.vscommerce.vsallin.net, DNS:*.vsmps.vsallin.net, DNS:*.vsrm.vsallin.net, DNS:*.vssps.vsallin.net, DNS:*.vsspsext.vsallin.net, DNS:*.vstsusers.vsallin.net, DNS:*.vskeros.vsallin.net, DNS:*.vscatalog.vsallin.net, DNS:*.vsdscops.vsallin.net, DNS:*.vstoken.vsallin.net, DNS:*.gdprdel.vsallin.net, DNS:*.userext.vsallin.net, DNS:*.vslicense.vsallin.net, DNS:*.status.vsallin.net, DNS:*.galleryppe.vsassets.io, DNS:*.vstmrblob.vsassets.io, DNS:*.vstmrblob.vsallin.net, DNS:*.vsassets.io
  Validity: Sep 24 17:56:19 2024 GMT - Mar 23 17:56:19 2025 GMT
  Fingerprint: EF:F6:AB:94:2B:BA:E8:D5:0C:23:72:AE:97:9A:DB:75:50:34:F9:C9
- Subject: Microsoft Azure RSA TLS Issuing CA 03 (Microsoft Corporation)
  Validity: Jun  8 00:00:00 2023 GMT - Aug 25 23:59:59 2026 GMT
  Fingerprint: F9:38:8E:A2:C9:B7:D6:32:B6:6A:2B:0B:40:6D:F1:D3:7D:39:01:F6
- Subject: DigiCert Global Root G2 (DigiCert Inc)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Self-signed
Local root certificates:
- Subject: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2 (built-in)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Issuer: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2

Sending GET request to https://marketplace.visualstudio.com using fetch from Electron...
Received response:
- Status: 200 

Sending GET request to https://marketplace.visualstudio.com using fetch from Node.js...
Received response:
- Status: 200 OK

Sending GET request to https://marketplace.visualstudio.com using fetch from Node.js (allow HTTP2)...
Received response:
- Status: 200 

```

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry updating extensions and then post the created netlog.json here?

**Comment by OmarSamirr** [comment]
Same Issue for me :(

> ```
> Note: Make sure to replace all sensitive information with dummy values before sharing this output.
> 
> VS Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f)
> Network Proxy Test 0.0.14
> darwin 24.2.0 arm64
> 
> Environment variables:
> all_proxy=socks5://127.0.0.1:7890
> http_proxy=http://127.0.0.1:7890
> https_proxy=http://127.0.0.1:7890
> no_proxy=::1,localhost,127.0.0.1
> 
> DNS Lookup:
> - ipv4: 13.107.42.18 (2 ms)
> - ipv6: ::ffff:13.107.42.18 (1 ms)
> 
> Proxy:
> - URL: http://127.0.0.1:7890 (0 ms)
> - Connection: 200 Connection established (1 ms)
> 
> Sending GET request to https://marketplace.visualstudio.com...
> Received response:
> - Status: 200 OK
> Certificate chain:
> - Subject: visualstudio.com (Microsoft Corporation)
>   Subject alt: DNS:visualstudio.com, DNS:*.visualstudio.com, DNS:*.vsmps.visualstudio.com, DNS:*.vssps.visualstudio.com, DNS:*.vssh.visualstudio.com, DNS:*.vsclt.visualstudio.com, DNS:*.vsrm.visualstudio.com, DNS:*.codelens.visualstudio.com, DNS:*.almsearch.visualstudio.com, DNS:*.artifacts.visualstudio.com, DNS:*.vsblob.visualstudio.com, DNS:*.vsblob.vsassets.io, DNS:*.manage.visualstudio.com, DNS:*.extmgmt.visualstudio.com, DNS:*.marketplace.visualstudio.com, DNS:*.gallery.vsassets.io, DNS:*.pkgs.visualstudio.com, DNS:*.zeus.visualstudio.com, DNS:*.entreq.visualstudio.com, DNS:*.feeds.visualstudio.com, DNS:*.vstsusers.visualstudio.com, DNS:*.analytics.visualstudio.com, DNS:*.my.visualstudio.com, DNS:*.dataimport.visualstudio.com, DNS:*.vsaex.visualstudio.com, DNS:*.vslicense.visualstudio.com, DNS:*.vstskalypso.visualstudio.com, DNS:*.vscommerce.visualstudio.com, DNS:*.governance.visualstudio.com, DNS:*.vskeros.visualstudio.com, DNS:*.vstoken.visualstudio.com, DNS:*.vstmr.visualstudio.com, DNS:*.vscatalog.visualstudio.com, DNS:*.gdprdel.visualstudio.com, DNS:*.userext.visualstudio.com, DNS:*.vsdscops.visualstudio.com, DNS:*.pipelines.visualstudio.com, DNS:*.azboards.visualstudio.com, DNS:*.azminicom.visualstudio.com, DNS:*.commvtwo.visualstudio.com, DNS:*.status.visualstudio.com, DNS:*.vsdevprofile.visualstudio.com, DNS:*.vsevidence.visualstudio.com, DNS:*.vspolicy.visualstudio.com, DNS:*.auditservice.visualstudio.com, DNS:*.vsnotify.visualstudio.com, DNS:*.azchatops.visualstudio.com, DNS:*.azents.visualstudio.com, DNS:*.runtimecatalog.visualstudio.com, DNS:*.artifactcache.visualstudio.com, DNS:*.azpipelines.visualstudio.com, DNS:*.advsec.visualstudio.com, DNS:*.dpdbot.visualstudio.com, DNS:*.sample.visualstudio.com, DNS:*.vsallin.net, DNS:*.almsearch.vsallin.net, DNS:*.codelens.vsallin.net, DNS:*.marketplace.vsallin.net, DNS:*.vsaex.vsallin.net, DNS:*.vscommerce.vsallin.net, DNS:*.vsmps.vsallin.net, DNS:*.vsrm.vsallin.net, DNS:*.vssps.vsallin.net, DNS:*.vsspsext.vsallin.net, DNS:*.vstsusers.vsallin.net, DNS:*.vskeros.vsallin.net, DNS:*.vscatalog.vsallin.net, DNS:*.vsdscops.vsallin.net, DNS:*.vstoken.vsallin.net, DNS:*.gdprdel.vsallin.net, DNS:*.userext.vsallin.net, DNS:*.vslicense.vsallin.net, DNS:*.status.vsallin.net, DNS:*.galleryppe.vsassets.io, DNS:*.vstmrblob.vsassets.io, DNS:*.vstmrblob.vsallin.net, DNS:*.vsassets.io
>   Validity: Sep 24 17:56:19 2024 GMT - Mar 23 17:56:19 2025 GMT
>   Fingerprint: EF:F6:AB:94:2B:BA:E8:D5:0C:23:72:AE:97:9A:DB:75:50:34:F9:C9
> - Subject: Microsoft Azure RSA TLS Issuing CA 03 (Microsoft Corporation)
>   Validity: Jun  8 00:00:00 2023 GMT - Aug 25 23:59:59 2026 GMT
>   Fingerprint: F9:38:8E:A2:C9:B7:D6:32:B6:6A:2B:0B:40:6D:F1:D3:7D:39:01:F6
> - Subject: DigiCert Global Root G2 (DigiCert Inc)
>   Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
>   Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
>   Self-signed
> Local root certificates:
> - Subject: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2 (built-in)
>   Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
>   Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
>   Issuer: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2
> 
> Sending GET request to https://marketplace.visualstudio.com using fetch from Electron...
> Received response:
> - Status: 200 
> 
> Sending GET request to https://marketplace.visualstudio.com using fetch from Node.js...
> Received response:
> - Status: 200 OK
> 
> Sending GET request to https://marketplace.visualstudio.com using fetch from Node.js (allow HTTP2)...
> Received response:
> - Status: 200 
> ```

**Comment by ImMejor35** [comment]
Steps I took to fix it:
1. Go into Windows Settings Date and time and turn on set time zone automatically and set time automatically (location services need to be on)
2. Update certificates if above step didn't work on its own.

**Comment by A-JBotero** [comment]
If you do not have a VPN or some type of antivirus you can try to lower the real-time protection and restart VSCode after that it will let you install the extensions

**Comment by bwagner** [comment]
> Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code entering `https://marketplace.visualstudio.com` as the URL?
> 
> If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

Unfortunately, on that page there's no "Download Extension" link.

**Comment by santhu97** [comment]
@chrmarti @sandy081  I'm facing the same issue Error while fetching extensions. Failed to fetch.

**Comment by kkingsbe** [comment]
I am also getting the same error. Not behind a proxy

```
workbench.desktop.main.js:4931 
 GET https://cursor-cdn.com/queries/undefined/17/84a9283… net::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by iTzOt4vio227** [comment]
on linux without antivirus, proxy and etc.
i started getting this issue 1 week ago

**Comment by vishcious** [comment]
I am on an Ubuntu24 machine and am running into the same problem
the plugin suggested by @chrmarti yields the following result

I ensured that tha proxy settings are fine. I am having the cert issue when using fetch from electron alone according to the results from the plugin

I have the proxy configured in the shell, vscode and have the NODE_EXTRA_CA_CERTS env var also set

Not sure what would cause fetch to fail from electron, but succeed from node.js... thoughts?

```
Sending GET request to https://marketplace.visualstudio.com/ using fetch from Electron...
Received error: Error: net::ERR_CERT_AUTHORITY_INVALID
                at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/utility_init:2:10635)
                at SimpleURLLoaderWrapper.emit (node:events:518:28)
 
Sending GET request to https://marketplace.visualstudio.com/ using fetch from Node.js...
Received response:
- Status: 200 OK
 
Sending GET request to https://marketplace.visualstudio.com/ using fetch from Node.js (allow HTTP2)...
Received response:
- Status: 200
```

**Comment by vishcious** [comment]
figured out the solution to my issue. Apprently, electron apps (aka chromium) store and manage their ca certs in a NSS db. The following solution worked from https://docs.telerik.com/fiddler-everywhere/knowledge-base/setup-ca-electron-ubuntu worked 

```bash
certutil -A -n "ROOT-CA" -t "TCu,Cu,Tu" -i /usr/share/ca-certificates/extra/<CUSTOM_ROOT_CA_CERT>.crt -d sql:/home/${USER}/.pki/nssdb
```

**Comment by lycfyi** [comment]
I have encountered similar issue and turned out I forgot the proxy configs I did while ago
