### ISSUE TITLE
Build failed:  install and enable vscode-smoketest-check timeout

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#227668]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=291589&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=9ab437b3-ee70-5588-b120-442542e6d570

```
  1) VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\out\code.js:204:23)
      at async Code.waitForElement (D:\a\_work\1\s\test\automation\out\code.js:163:16)
      at async Extensions.installExtension (D:\a\_work\1\s\test\automation\out\extensions.js:51:9)
      at async Context.<anonymous> (out\areas\extensions\extensions.test.js:15:13)
```

**Comment by sandy081** [comment]
No artifacts found in the build. Without them difficult to diagnose. Hence closing it.
