### ISSUE TITLE
ssh remote failed when "Remote.SSH: Server Install Path" configured

### ISSUE THREAD

**Issue by m4yue** [microsoft/vscode#227737]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```s
Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```
- OS Version:  local(window) , remote(centos 7.9)

Steps to Reproduce:

1. upgraded to my current version
2. ssh remote connect to a `Remote.SSH: Server Install Path` configured host, my `Remote.SSH: Server Install Path` is 
![image](https://github.com/user-attachments/assets/a5171819-99cd-41e0-98a3-88d763aef705)
3. vscode stuck at setup remote server, last message is some thing like 'scp server to remote'

i reboot my remote server, cause vscode connection broken, and i saw messge 
```s
[10:30:08.370] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:30:08.370] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:30:08.371] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:30:08.371] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:30:08.371] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:30:08.372] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:30:08.394] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[10:30:08.397] Expecting scp to be next to ssh at C:\WINDOWS\System32\OpenSSH\scp.exe
[10:30:08.397] Testing scp with "C:\WINDOWS\System32\OpenSSH\scp.exe"
[10:30:08.421] scp exited with code: 1
[10:30:08.421] Got stderr from scp: usage: scp [-346ABCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[10:30:08.422] Copying file to remote with "C:\WINDOWS\System32\OpenSSH\scp.exe" "vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz" "vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done" devtz:"'/opt/mat'/.vscode-server"
[10:30:08.422] Using cwd: file:///c%3A/Users/DELL/AppData/Local/Temp/vscode_server_1725589808364
[10:30:08.422] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:30:08.819] > vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz   0%    0     0.0KB/]0;C:\WINDOWS\System32\cmd.exe
[10:30:08.949] > vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz 100% 8755KB  67.3MB/
> vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done 100%    9     9
> 
[10:30:10.198] "Copy server to host" terminal command done
[10:34:08.438] > 
>  
> 
[10:38:08.625] > 
>  
> 
[10:39:24.974] > Connection to 192.168.96.161 closed by remote host.
[10:39:24.982] > 
[10:39:26.232] "install" terminal command done
[10:39:26.233] Install terminal quit with output:                          Connection to 192.168.96.161 closed by remote host.
[10:39:26.233] Received install output:                          Connection to 192.168.96.161 closed by remote host.
[10:39:26.233] Failed to parse remote port from server output
[10:39:26.235] Resolver error: Error: 
	at v.Create (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:501404)
	at t.handleInstallOutput (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:498726)
	at t.tryInstall (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:616462)
	at async c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:575790
	at async t.withShowDetailsEvent (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:579019)
	at async k (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:572576)
	at async t.resolve (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:576430)
	at async c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.114.1\out\extension.js:2:844805
[10:39:26.241] ------




[10:39:26.590] Opening exec server for ssh-remote+devtz
[10:39:26.600] Initizing new exec server for ssh-remote+devtz
[10:39:26.602] Using commit id "4849ca9bdf9666755eb463db297b69e5385090e3" and quality "stable" for server
[10:39:26.605] Script variables:
```

i think the bug is:
```s
[10:30:08.422] Copying file to remote with "C:\WINDOWS\System32\OpenSSH\scp.exe" "vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz" "vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done" devtz:"'/opt/mat'/.vscode-server"
```
when build scp command , my configured `Remote.SSH: Server Install Path` was quoted and added to `devtz:"'/opt/mat'/.vscode-server"`, which cause `scp` blocked

**Comment by vuppalaprasanth** [comment]
facing the same issue, any workaround for this?

**Comment by vuppalaprasanth** [comment]
@m4yue 
only workaround i found is as below:
1. remove that entry from settings 
2. and create a symlink manually at your remote home directory.
`ln -s /opt/mat/.vscode_server ~/.vscode_server`

and restart vscode. it will work after that.

**Comment by Aonnghus** [comment]
It seems to be a bug in VSCode server rather than VSCode (https://github.com/microsoft/vscode-remote-release/issues/10230).
Installing the pre-release version of the Remote SSH extension solves the problem

**Comment by joshspicer** [comment]
`v0.114.2` has been released that fixes the single-quoting issue reported here and tracked in https://github.com/microsoft/vscode-remote-release/issues/10230

If you're seeing an issue related to extensions not being installed into the custom install path, please provide your feedback and 👍 https://github.com/microsoft/vscode-remote-release/issues/10255
