### ISSUE TITLE
Windows 10 Update of VSCode from 1.91 -> 1.92/1.93 not working (`Scheme contains illegal characters` )

### ISSUE THREAD

**Issue by vigneshmanick** [microsoft/vscode#227880]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92 and 1.93
- OS Version:  Windows 10 Pro

#### Steps to Reproduce:

1. Start vscode of versions 1.92 / 1.93 either from commandline or double clicking the icon

#### Issue description

After updating from 1.91-> 1.92 / 1.93 Vscode doesn't start. Error message after running with `--verbose` argument is shown below.  

I have tried 

1. Disabling all extensions
2. Downloading and executing the portable installer
3. disable-gpu

#### Error message

```
[main 2024-09-07T14:28:09.147Z] Error: [UriError]: Scheme contains illegal characters.
    at l (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:46:20915)
    at new f (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:46:22115)
    at new g (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:46:23813)
    at f.parse (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:46:22607)
    at C.Bb (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:117:128067)
    at new C (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:117:123341)
    at $.o (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:64:1608)
    at $.createInstance (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:64:1100)
    at j.rb (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:118:46308)
    at j.cb (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:118:34790)
    at j.Z (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:118:33799)
    at j.open (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:118:29689)
    at async yt.startup (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:118:58105)
    at async Fe.a (C:\Users\myuser\Downloads\VSCode-win32-x64-1.93.0\resources\app\out\vs\code\electron-main\main.js:120:1275)
```

Thanks!
```[tasklist]
### Tasks
```

**Comment by vigneshmanick** [comment]
i still have this issue with version 1.94.0

Steps 

1. Download zip installer for windows
2. Unzip to folder `vscode`
3. Create `data` folder within `vscode` folder
4. Open comand prompt and navigate to folder
5. start with `.\Code.exe`

```cmd
c:\temp\vscode>
[main 2024-10-07T09:01:34.636Z] Error: [UriError]: Scheme contains illegal characters.
    at wv (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:30:14931)
    at new ec (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:30:16154)
    at new nr (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:30:17591)
    at ec.parse (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:30:16655)
    at ja.Bb (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:71:52443)
    at new ja (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:71:48287)
    at id.o (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:107:1581)
    at id.createInstance (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:107:1078)
    at tu.rb (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:72:26240)
    at tu.cb (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:72:15731)
    at tu.Z (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:72:14798)
    at tu.open (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:72:11113)
    at async Du.startup (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:81:6030)
    at async R3.a (file:///c:/temp/vscode/resources/app/out/vs/code/electron-main/main.js:111:34559)
[948:1007/110134.748:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[948:1007/110134.749:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
```

**Comment by vigneshmanick** [comment]
reset of the machine fixed the issue. Still unclear of what the issue actually was.
