### ISSUE TITLE
vscode.dev type acquisition fails if project has a `GitHub` dependency

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#228277]
1. For the project https://github.com/mjbvz/test-ts-ata-web, open on GitHub.dev/vscode.dev: https://github.dev/mjbvz/test-ts-ata-web

1. Open `index.ts`

**Bug**
Loading never finishes

The root cause is the our type acquisition fails:

```
 panicked at 'Git dependencies are not enabled. (While trying to process git+ssh://git@github.com/markedjs/marked.git#b47358cb1711b29237e074737cb4e5f9a98e3914)', crates/nassun/src/client.rs:289:24

Stack:

Error: 
	at T.A.wbg.__wbg_new_abda76e883ba8a5f (

...
```

cc @zkat

**Comment by mjbvz** [comment]
Here's the de-minified error stack:

```
console.js:98 [Extension Host] panicked at 'Git dependencies are not enabled. (While trying to process git+ssh://git@github.com/markedjs/marked.git#b47358cb1711b29237e074737cb4e5f9a98e3914)', crates/nassun/src/client.rs:289:24

Stack:

Error: 
	at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:8080/static/sources/extensions/typescript-language-features/dist/browser/extension.js#vscode-extension:32208:21)
	at wasm://wasm/006eb5d6:wasm-function[980]:0x117fcf
	at wasm://wasm/006eb5d6:wasm-function[3148]:0x1627f7
	at wasm://wasm/006eb5d6:wasm-function[1593]:0x1462cc
	at wasm://wasm/006eb5d6:wasm-function[1777]:0x14f131
	at wasm://wasm/006eb5d6:wasm-function[3135]:0x162786
	at wasm://wasm/006eb5d6:wasm-function[2130]:0x159a94
	at wasm://wasm/006eb5d6:wasm-function[2345]:0x15db52
	at wasm://wasm/006eb5d6:wasm-function[1286]:0x1337b7
	at wasm://wasm/006eb5d6:wasm-function[1286]:0x1337c5
	at wasm://wasm/006eb5d6:wasm-function[1366]:0x139143
	at wasm://wasm/006eb5d6:wasm-function[107]:0x4a8a
	at wasm://wasm/006eb5d6:wasm-function[115]:0x1e630
	at wasm://wasm/006eb5d6:wasm-function[573]:0xde655
	at wasm://wasm/006eb5d6:wasm-function[1595]:0x14642a
	at wasm://wasm/006eb5d6:wasm-function[991]:0x11931e
	at wasm://wasm/006eb5d6:wasm-function[2611]:0x1607a9
	at __wbg_adapter_53 (http://localhost:8080/static/sources/extensions/typescript-language-features/dist/browser/extension.js#vscode-extension:31373:10)
	at real (http://localhost:8080/static/sources/extensions/typescript-language-features/dist/browser/extension.js#vscode-extension:31354:20)
```

Seeing if I can catch the error for now

**Comment by mjbvz** [comment]
Not super useful stack in the error message. `real` is form inside `makeMutClosure` from the rust adapter . Here's more of the stack

![Image](https://github.com/user-attachments/assets/5b960539-a994-4259-a473-d5116b58b382)

**Comment by zkat** [comment]
As discussed elsewhere: orogene does not currently support packing, which is needed for git (and http) dependencies supported. We could handwave things away and say that _wasm_ isn't going to have packing/building-related logic, which is probably reasonable. In that case, the changes to orogene are much smaller and most of the important bits are there already and just need to be rearranged a little (namely, orogene already has all the logic it needs around figuring out where github/bitbucket/gitlab put their ready-to-download tarballs, as well as downloading them and extracting them. It just kinda does this maneuver where it tries to extract it into a temp dir first, for Reasons, but we can just skip that and feed the file directly to the package-fetching logic and be done with it.

I'm happy to help walk anyone interested through doing this, as the second alternative is really not a lot of work, or even pairing a bit on it. :)
