### ISSUE TITLE
Testing pytest discovery error

### ISSUE THREAD

**Issue by JavierEscobarOrtiz** [microsoft/vscode#228248]
Hello,

I am trying to use the VSCode Testing module with my `skforecast_py11` environment which has `werkzeug == 3.0.4` installed. The OUTPUT Python section gives me the error `ModuleNotFoundError: No module named 'werkzeug' (see logs below), which is impossible. This is causing that the module doesn't work:

![imagen](https://github.com/user-attachments/assets/cbf48f09-8cb7-4610-b8f9-edc21ab05e65)
 

Any help is appreciated!

VSCode version: 1.93.0
Python: 3.11.5 (package list below)

```
2024-09-11 17:25:15.036 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-09-11 17:25:15.036 [info] Experiment 'pythonSurveyNotification' is active
2024-09-11 17:25:15.036 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-09-11 17:25:15.036 [info] Experiment 'pythonTestAdapter' is active
2024-09-11 17:25:15.036 [info] Native locator: Refresh started
2024-09-11 17:25:15.036 [info] Default formatter is set to ms-python.black-formatter for workspace c:\Users\jaesc2\GitHub\skforecast
2024-09-11 17:25:15.036 [info] > pyenv which python
2024-09-11 17:25:15.036 [info] cwd: .
2024-09-11 17:25:15.204 [info] > conda info --json
2024-09-11 17:25:15.230 [info] Conda environment manager found at: C:\Users\jaesc2\Miniconda3\Scripts\conda.exe
2024-09-11 17:25:15.395 [info] Python interpreter path: ~\Miniconda3\envs\skforecast_py11\python.exe
2024-09-11 17:25:15.564 [info] Native locator: Refresh finished in 1131 ms
2024-09-11 17:25:15.583 [info] > conda info --json
2024-09-11 17:25:15.583 [info] shell: commandPrompt
2024-09-11 17:25:16.685 [info] Starting Pylance language server.
2024-09-11 17:25:17.061 [info] Discover tests for workspace name: skforecast - uri: c:\Users\jaesc2\GitHub\skforecast
2024-09-11 17:25:17.061 [info] Running discovery for pytest using the new test adapter.
2024-09-11 17:25:17.062 [warning] The cwd resolves to a different path, checking if it has a symbolic link somewhere in its path.
2024-09-11 17:25:17.063 [info] All environment variables set for pytest discovery: {"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\jaesc2\\AppData\\Roaming","CHROME_CRASHPAD_PIPE_NAME":"\\\\.\\pipe\\crashpad_32756_BYOMEDJVEOYFLWTO","COMPUTERNAME":"ITES015-NB0029","ELECTRON_RUN_AS_NODE":"1","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","FPS_BROWSER_USER_PROFILE_STRING":"Default","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\jaesc2","IKEALOGS":"C:\\IKEALOGS","LIBJABRA_TRACE_LEVEL":"debug","LOCALAPPDATA":"C:\\Users\\jaesc2\\AppData\\Local","LOGONSERVER":"\\\\DCSEELM-NT6704","NUMBER_OF_PROCESSORS":"16","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"Intel64 Family 6 Model 141 Stepping 1, GenuineIntel","PROCESSOR_LEVEL":"6","PROCESSOR_REVISION":"8d01","PUBLIC":"C:\\Users\\Public","SESSIONNAME":"Console","TEMP":"C:\\Users\\jaesc2\\AppData\\Local\\Temp","TMP":"C:\\Users\\jaesc2\\AppData\\Local\\Temp","USERDNSDOMAIN":"IKEA.COM","USERDOMAIN":"IKEA","USERDOMAIN_ROAMINGPROFILE":"IKEA","USERNAME":"JAESC2","USERPROFILE":"C:\\Users\\jaesc2","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_CODE_CACHE_PATH":"C:\\Users\\jaesc2\\AppData\\Roaming\\Code\\CachedData\\4849ca9bdf9666755eb463db297b69e5385090e3","VSCODE_CRASH_REPORTER_PROCESS_TYPE":"extensionHost","VSCODE_CWD":"C:\\Users\\jaesc2\\AppData\\Local\\Programs\\Microsoft VS Code","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_IPC_HOOK":"\\\\.\\pipe\\3c0d44f5-1.93.0-main-sock","VSCODE_L10N_BUNDLE_LOCATION":"","VSCODE_NLS_CONFIG":"{\"userLocale\":\"en-us\",\"osLocale\":\"es-es\",\"resolvedLanguage\":\"en\",\"defaultMessagesFile\":\"C:\\\\Users\\\\jaesc2\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code\\\\resources\\\\app\\\\out\\\\nls.messages.json\",\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_PID":"32756","ZES_ENABLE_SYSMAN":"1","ComSpec":"C:\\WINDOWS\\system32\\cmd.exe","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","OneDrive":"C:\\Users\\jaesc2\\OneDrive - IKEA","OneDriveCommercial":"C:\\Users\\jaesc2\\OneDrive - IKEA","PSModulePath":"C:\\Users\\jaesc2\\Documents\\WindowsPowerShell\\Modules;C:\\Users\\jaesc2\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\platform\\PowerShell","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PyCharm":"C:\\Program Files\\JetBrains\\PyCharm 2022.1.1\\bin;","SystemDrive":"C:","SystemRoot":"C:\\WINDOWS","windir":"C:\\WINDOWS","Path":"C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Users\\jaesc2\\Miniconda3;C:\\Users\\jaesc2\\Miniconda3\\Library\\mingw-w64\\bin;C:\\Users\\jaesc2\\Miniconda3\\Library\\usr\\bin;C:\\Users\\jaesc2\\Miniconda3\\Library\\bin;C:\\Users\\jaesc2\\Miniconda3\\Scripts;C:\\Users\\jaesc2\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\jaesc2\\AppData\\Local\\GitHubDesktop\\bin;C:\\Program Files\\JetBrains\\PyCharm 2022.1.1\\bin;;C:\\Users\\jaesc2\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Users\\jaesc2\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\jaesc2\\AppData\\Roaming\\Programs\\Zero Install","PYTHONPATH":"c:\\Users\\jaesc2\\.vscode\\extensions\\ms-python.python-2024.14.0-win32-x64\\python_files","TEST_RUN_PIPE":"\\\\.\\pipe\\python-test-discovery-e31bcf9fcc0860f1b3c8-sock"}
2024-09-11 17:25:17.069 [info] > ~\Miniconda3\Scripts\conda.exe info --json
2024-09-11 17:25:18.594 [info] > ~\Miniconda3\Scripts\conda.exe run -n skforecast_py11 --no-capture-output python ~\.vscode\extensions\ms-python.python-2024.14.0-win32-x64\python_files\get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.14.0-win32-x64/python_files/printEnvVariables.py
2024-09-11 17:25:18.594 [info] shell: commandPrompt
2024-09-11 17:25:18.594 [info] > conda run -n skforecast_py11 --no-capture-output python ~\.vscode\extensions\ms-python.python-2024.14.0-win32-x64\python_files\get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.14.0-win32-x64/python_files/printEnvVariables.py
2024-09-11 17:25:18.594 [info] shell: commandPrompt
2024-09-11 17:25:20.220 [info] > pixi --version
2024-09-11 17:25:20.221 [warning] could not find a pixi interpreter for the interpreter at C:\Users\jaesc2\Miniconda3\envs\skforecast_py11\python.exe
2024-09-11 17:25:20.235 [info] > python ~/.vscode/extensions/ms-python.python-2024.14.0-win32-x64/python_files/printEnvVariables.py
2024-09-11 17:25:20.235 [info] shell: commandPrompt
2024-09-11 17:25:20.244 [info] > python -m pytest -p vscode_pytest --collect-only skforecast
2024-09-11 17:25:20.244 [info] cwd: .
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_DEFAULT_ENV in collection to skforecast_py11 {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_EXE in collection to C:\Users\jaesc2\Miniconda3\Scripts\conda.exe {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_EXES in collection to "C:\Users\jaesc2\Miniconda3\condabin\..\Scripts\conda.exe"   {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_PREFIX in collection to C:\Users\jaesc2\Miniconda3\envs\skforecast_py11 {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_PROMPT_MODIFIER in collection to (skforecast_py11)  {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_PYTHON_EXE in collection to C:\Users\jaesc2\Miniconda3\python.exe {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_SHLVL in collection to 1 {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Prepending environment variable PATH in collection to C:\Users\jaesc2\Miniconda3\envs\skforecast_py11;C:\Users\jaesc2\Miniconda3\envs\skforecast_py11\Library\mingw-w64\bin;C:\Users\jaesc2\Miniconda3\envs\skforecast_py11\Library\usr\bin;C:\Users\jaesc2\Miniconda3\envs\skforecast_py11\Library\bin;C:\Users\jaesc2\Miniconda3\envs\skforecast_py11\Scripts;C:\Users\jaesc2\Miniconda3\envs\skforecast_py11\bin;C:\Users\jaesc2\Miniconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files\Git\cmd;C:\Users\jaesc2\Miniconda3;C:\Users\jaesc2\Miniconda3\Library\mingw-w64\bin;C:\Users\jaesc2\Miniconda3\Library\usr\bin;C:\Users\jaesc2\Miniconda3\Library\bin;C:\Users\jaesc2\Miniconda3\Scripts;C:\Users\jaesc2\AppData\Local\Microsoft\WindowsApps;C:\Users\jaesc2\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\PyCharm 2022.1.1\bin;.;C:\Users\jaesc2\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\jaesc2\AppData\Local\Programs\Microsoft VS Code\bin;.;C:\Program Files\Azure Data Studio\bin;C:\Users\jaesc2\AppData\Roaming\Programs\Zero Install; {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable PROMPT in collection to (skforecast_py11) $P$G {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable SSL_CERT_FILE in collection to C:\Users\jaesc2\Miniconda3\envs\skforecast_py11\Library\ssl\cacert.pem {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable CONDA_ROOT in collection to C:\Users\jaesc2\Miniconda3 {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable _CONDA_OLD_CHCP in collection to 850 {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.631 [info] Setting environment variable __CONDA_OPENSLL_CERT_FILE_SET in collection to "1" {"applyAtShellIntegration":true,"applyAtProcessCreation":true}
2024-09-11 17:25:20.762 [error] Traceback (most recent call last):
  File "C:\Users\jaesc2\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main

2024-09-11 17:25:20.762 [error]     return _run_code(code, main_globals, None,
  File "C:\Users\jaesc2\Miniconda3\lib\runpy.py", line 87, in _run_code

2024-09-11 17:25:20.763 [error]     exec(code, run_globals)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\pytest\__main__.py", line 5, in <module>

2024-09-11 17:25:20.763 [error]     raise SystemExit(pytest.console_main())
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\config\__init__.py", line 187, in console_main

2024-09-11 17:25:20.764 [error]     code = main()
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\config\__init__.py", line 145, in main

2024-09-11 17:25:20.764 [error]     config = _prepareconfig(args, plugins)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig

2024-09-11 17:25:20.764 [error]     config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\pluggy\_hooks.py", line 265, in __call__

2024-09-11 17:25:20.765 [error]     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec

2024-09-11 17:25:20.765 [error]     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\pluggy\_callers.py", line 55, in _multicall

2024-09-11 17:25:20.766 [error]     gen.send(outcome)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse

2024-09-11 17:25:20.766 [error]     config: Config = outcome.get_result()
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\pluggy\_result.py", line 60, in get_result

2024-09-11 17:25:20.766 [error]     raise ex[1].with_traceback(ex[2])
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\pluggy\_callers.py", line 39, in _multicall

2024-09-11 17:25:20.766 [error]     res = hook_impl.function(*args)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\config\__init__.py", line 1016, in pytest_cmdline_parse

2024-09-11 17:25:20.767 [error]     self.parse(args)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\config\__init__.py", line 1304, in parse

2024-09-11 17:25:20.767 [error]     self._preparse(args, addopts=addopts)
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\config\__init__.py", line 1187, in _preparse

2024-09-11 17:25:20.767 [error]     self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints

2024-09-11 17:25:20.768 [error]     plugin = ep.load()
  File "C:\Users\jaesc2\Miniconda3\lib\importlib\metadata.py", line 86, in load

2024-09-11 17:25:20.768 [error]     module = import_module(match.group('module'))
  File "C:\Users\jaesc2\Miniconda3\lib\importlib\__init__.py", line 127, in import_module

2024-09-11 17:25:20.769 [error]     return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

2024-09-11 17:25:20.769 [error]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

2024-09-11 17:25:20.769 [error]   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked

2024-09-11 17:25:20.769 [error]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

2024-09-11 17:25:20.769 [error]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

2024-09-11 17:25:20.769 [error]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

2024-09-11 17:25:20.770 [error]   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked

2024-09-11 17:25:20.770 [error]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

2024-09-11 17:25:20.770 [error]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

2024-09-11 17:25:20.770 [error]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

2024-09-11 17:25:20.770 [error]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

2024-09-11 17:25:20.770 [error]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

2024-09-11 17:25:20.771 [error]   File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module

2024-09-11 17:25:20.771 [error]     exec(co, module.__dict__)
  File "C:\Users\jaesc2\AppData\Roaming\Python\Python39\site-packages\dash\__init__.py", line 5, in <module>

2024-09-11 17:25:20.781 [error]     from .dependencies import (  # noqa: F401,E402
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module

2024-09-11 17:25:20.782 [error]     exec(co, module.__dict__)
  File "C:\Users\jaesc2\AppData\Roaming\Python\Python39\site-packages\dash\dependencies.py", line 4, in <module>

2024-09-11 17:25:20.791 [error]     from ._validate import validate_callback
  File "C:\Users\jaesc2\Miniconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module

2024-09-11 17:25:20.792 [error]     exec(co, module.__dict__)
  File "C:\Users\jaesc2\AppData\Roaming\Python\Python39\site-packages\dash\_validate.py", line 5, in <module>

2024-09-11 17:25:20.801 [error]     import flask
  File "C:\Users\jaesc2\AppData\Roaming\Python\Python39\site-packages\flask\__init__.py", line 1, in <module>

2024-09-11 17:25:20.811 [error]     from . import json as json
  File "C:\Users\jaesc2\AppData\Roaming\Python\Python39\site-packages\flask\json\__init__.py", line 6, in <module>

2024-09-11 17:25:20.820 [error]     from ..globals import current_app
  File "C:\Users\jaesc2\AppData\Roaming\Python\Python39\site-packages\flask\globals.py", line 6, in <module>

2024-09-11 17:25:20.834 [error]     from werkzeug.local import LocalProxy
ModuleNotFoundError: No module named 'werkzeug'

2024-09-11 17:25:20.852 [error] Subprocess exited unsuccessfully with exit code 1 and signal null on workspace c:\Users\jaesc2\GitHub\skforecast.
2024-09-11 17:25:20.852 [error] Subprocess exited unsuccessfully with exit code 1 and signal null on workspace c:\Users\jaesc2\GitHub\skforecast. Creating and sending error discovery payload
2024-09-11 17:25:20.852 [error] pytest test discovery error for workspace:  c:\Users\jaesc2\GitHub\skforecast 
  
 The python test process was terminated before it could exit on its own, the process errored with: Code: 1, Signal: null for workspace c:\Users\jaesc2\GitHub\skforecast
```

Package list:

```
absl-py==2.0.0
alembic==1.12.1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
astral==3.2
asttokens==2.4.1
astunparse==1.6.3
attrs==23.1.0
Babel==2.13.1
beautifulsoup4==4.12.2      
bleach==6.1.0
blinker==1.8.2
blosc2==2.7.1
cachetools==5.3.2
catboost==1.2.2
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2   
click==8.1.7
cloudpickle==3.0.0
colorama==0.4.6
colorlog==6.7.0
comm==0.2.0
contourpy==1.2.0
coverage==7.3.2
cycler==0.12.1
Cython==3.0.5
daal==2024.5.0
daal4py==2024.5.0
dask==2023.12.0
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
distributed==2023.12.0
execnet==2.1.1
executing==2.0.1
fastjsonschema==2.19.0
feature-engine==1.7.0
filelock==3.15.4
Flask==3.0.3
flatbuffers==24.3.25
fonttools==4.45.0
fsspec==2023.12.1
gast==0.5.4
ghp-import==2.1.0
google-auth==2.26.1
google-auth-oauthlib==1.2.0
google-pasta==0.2.0
graphviz==0.20.1
greenlet==3.0.1
griffe==0.48.0
grpcio==1.60.0
h5py==3.10.0
holidays==0.42
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.27.0
ipython==8.17.2
ipython-genutils==0.2.0
ipywidgets==8.1.1
itsdangerous==2.2.0
jedi==0.19.1
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-contrib-core==0.4.2
jupyter-contrib-nbextensions @ https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master#sha256=e6a17963a2baded093b95d238f83e2facea84857928739d2d9f04ce2729f4106
jupyter-highlight-selected-word==0.2.0
jupyter-nbextensions-configurator==0.6.3
jupyter_client==8.6.0
jupyter_core==5.5.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupytext==1.15.2
keras==3.4.1
kiwisolver==1.4.5
libclang==16.0.6
lightgbm==4.1.0
line_profiler==4.1.3
llvmlite==0.41.1
locket==1.0.0
lxml==4.9.3
Mako==1.3.0
Markdown==3.5.1
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mdit-py-plugins==0.4.0
mdurl==0.1.2
mergedeep==1.3.4
mike==1.1.2
mistune==3.0.2
mkdocs==1.5.3
mkdocs-autorefs==0.5.0
mkdocs-get-deps==0.2.0
mkdocs-jupyter==0.24.8
mkdocs-material==9.5.30
mkdocs-material-extensions==1.3
mkdocstrings==0.25.2
mkdocstrings-python==1.10.7
ml-dtypes==0.3.2
mpmath==1.3.0
msgpack==1.0.7
namex==0.0.8
nbclient==0.9.0
nbconvert==7.11.0
nbformat==5.9.2
ndindex==1.8
nest-asyncio==1.5.8
networkx==3.3
notebook==6.4.12
numba==0.58.1
numexpr==2.10.1
numpy==1.26.2
oauthlib==3.2.2
opt-einsum==3.3.0
optree==0.12.1
optuna==3.4.0
packaging==23.2
paginate==0.5.6
pandas==2.2.2
pandocfilters==1.5.0
parso==0.8.3
partd==1.4.1
pathspec==0.11.2
patsy==0.5.3
Pillow==10.1.0
platformdirs==4.0.0
plotly==5.18.0
pluggy==1.5.0
pmdarima==2.0.4
prometheus-client==0.19.0
prompt-toolkit==3.0.41
protobuf==4.23.4
psutil==5.9.6
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==14.0.1
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.17.1
pyinstrument==4.6.2
pymdown-extensions==10.4
pyparsing==3.1.1
pytest==8.3.3
pytest-cov==5.0.0
pytest-xdist==3.6.1
python-dateutil==2.8.2
pytz==2023.3.post1
pywin32==306
pywinpty==2.0.12
PyYAML==6.0.1
pyyaml_env_tag==0.1
pyzmq==25.1.1
qtconsole==5.5.1
QtPy==2.4.1
referencing==0.31.0
regex==2023.10.3
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.7.1
rpds-py==0.13.1
rsa==4.9
ruff==0.5.5
scikit-learn==1.4.2
scikit-learn-intelex==2024.5.0
scipy==1.11.4
seaborn==0.13.0
Send2Trash==1.8.2
session-info==1.0.0
shap==0.44.0
six==1.16.0
slicer==0.0.7
sortedcontainers==2.4.0
soupsieve==2.5
SQLAlchemy==2.0.23
stack-data==0.6.3
statsmodels==0.14.0
stdlib-list==0.10.0
stumpy==1.12.0
sympy==1.13.1
tables==3.9.2
tabulate==0.9.0
tbb==2021.13.0
tblib==3.0.0
tenacity==8.2.3
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.2
tensorflow-estimator==2.15.0
tensorflow-intel==2.16.2
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.4.0
terminado==0.18.0
threadpoolctl==3.2.0
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==2.2.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
tsfresh==0.20.1
tslearn==0.6.2
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.1.0
verspec==0.1.0
watchdog==3.0.0
wcwidth==0.2.11
webencodings==0.5.1
Werkzeug==3.0.4
widgetsnbextension==4.0.9
wrapt==1.14.1
xgboost==2.0.2
zict==3.0.0
zipp==3.17.0
```

**Comment by JavierEscobarOrtiz** [comment]
The problem is solved by downgrading the Python extension from `v2024.14.0` to `v2024.10.0`.

**Comment by jeroendv** [comment]
Same problem proposed fixes it indeed

> The problem is solved by downgrading the Python extension from `v2024.14.0` to `v2024.10.0`.

**Comment by Scaramir** [comment]
I would like to add, that on Windows10, I had a similar error stating 
```bash
[info] python ~.vscode\extensions\ms-python.python-2024.14.1-win32-x64\python_files\unittestadapter\discovery.py --udiscovery -v -s ./test -p test_*.py
[info] cwd s:\my_project\correct\path
[error] Python konnte nicht gefunden werden. F�hren Sie die Verkn�pfung ohne Argumente aus, um sie �ber den Microsoft Store zu installieren, oder deaktivieren Sie diese Verkn�pfung unter
[error] Subprocess exited unsuccessfully with exit code 9009 and signal null on workspace s:\my_project\correct\path.
```
This seemed a bit weird to me. 

To at least have VSCode find python again (but now it seems to use the overall conda base environment instead the env I set at workspace level, leading me here), I had to to this after the recent win-update:

Manually deactivate the windows-sliders `python.exe` and `python3.exe` which invoked the Microsoft Store when unittest discovery ran within VSCode (like hitting refresh in vscode but runs in the terminal when i activate the correct env before.). 
This can be found at "win+i / Settings->Apps&Features->App execution Alias-> the two app App-Installer-Sliders". 

Now I can downgrade as mentioned above.

**Comment by nathanneibauer** [comment]
I am encountering a similar issue. Test discovery is working for me and not for him; however, we are both on python extension `v2024.20.0`. The difference we are seeing is that my logs say this:

![Image](https://github.com/user-attachments/assets/2b1ffe80-6907-497e-bc45-196262daf0b8)

And his say:

![Image](https://github.com/user-attachments/assets/fba6d196-b686-4cad-aeba-5e97c005344c)


What is the test adapter? What is different in my environment that I am using the "new test adapter"?

**Comment by eleanorjboyd** [comment]
Hi! the "new test adapter" is a rewrite we have created that redesigns testing and how it works to make it better and less error prone. We are making this the default very soon but for now it is still enabled by a setting. If your coworker sets this, they should be on the rewrite and good to go! 

Enable the rewrite by adding this setting to your users settings.json "python.experiments.optInto": ["pythonTestAdapter"]. Then you can confirm its enabled by finding  Experiment 'pythonTestAdapter' is active in your python logs. If you are unable to see the log for the experiment change your log level to trace and it should show up. To set to trace use `theDeveloper: set log level` command in the command palette. Thanks

**Comment by eleanorjboyd** [comment]
@JavierEscobarOrtiz, are you still seeing this issue? I see `2024-09-11 17:25:20.834 [error]     from werkzeug.local import LocalProxy
ModuleNotFoundError: No module named 'werkzeug'` in your logs which makes me wonder if pytest works if you do it directly from the command line- give that a try and let me know and then we can go from there. Sorry about the delay!

**Comment by JavierEscobarOrtiz** [comment]
Hi @eleanorjboyd, I just installed Python v2024.20.0 (from v2024.10.0) and everything works fine. I didn't need to do anything else.

When I had the problem, I was able to run tests in the terminal using the `pytest` command.

Best,

Javier

**Comment by eleanorjboyd** [comment]
glad the newer version of the extension fixed the issue!
