### ISSUE TITLE
https://github.com/drcika/apc-extension stopped working after latest insiders 1.94 update

### ISSUE THREAD

**Issue by ryan6416** [microsoft/vscode#228377]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
Version: 1.94.0-insider
Commit: 102ff8db3f8dd54027407279ed5cb78e81b4bf19
Date: 2024-09-12T08:48:43.150Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

The following vscode extension, https://github.com/drcika/apc-extension, stopped working after latest update 1.94:

Filed issues in https://github.com/drcika/apc-extension: see https://github.com/drcika/apc-extension/issues/224 and https://github.com/drcika/apc-extension/issues/225

Cross posting here.

**Comment by sandy081** [comment]
Please get this diagnosed from the extension first and file issue with necessary diagnosis details and steps to reproduce.

**Comment by jroman-sh** [comment]
Hey, this is also happening to me

**Comment by gabjohann** [comment]
me too

**Comment by Youssef2430** [comment]
this is still a problem for new installations

**Comment by ZeChArtiahSaher** [comment]
```
2024-10-13 05:47:23.601 [error] Activating extension drcika.apc-extension failed due to an error:
2024-10-13 05:47:23.601 [error] TypeError: Cannot read properties of undefined (reading 'filename')
	at Object.<anonymous> (c:\Users\...\.vscode\extensions\drcika.apc-extension-0.4.1\dist\patch.js:17:52)
	at Module._compile (node:internal/modules/cjs/loader:1373:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (c:\Users\__uiuiiiis_________\.vscode\extensions\drcika.apc-extension-0.4.1\dist\extension.js:7:17)
	at Module._compile (node:internal/modules/cjs/loader:1373:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at hB.xb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
	at async Promise.all (index 0)
```
