### ISSUE TITLE
Debug Launch in Split Terminal Doesn't work

### ISSUE THREAD

**Issue by PN-03** [microsoft/vscode#229360]
- VS Code Version:  1.92.0  to 1.93.1
- OS Version:  Windows 10

Hi, I noticed that since Ver. 1.92.0 launching the C++ Debugger in a Split-Terminal no longer works. It will just do the loading animation and give an  Error in the terminal. This happens with Microsoft's "C/C++ Tools" Extension with the GDB Debugger, or the CodeLLDB Debugger.

Steps to Reproduce:

1.  Open Terminal and get a PowerShell Terminal
2.  Click the Debug Launch button, and the Second Terminal appears
3.  Split the Terminal so that the Normal PowerShell is on one side, and the Debug Launch Terminal is on the other
4.  Stop the Debugger and Click the Debug Launch Button again, or click Restart Debugger after the Terminal is Split
5. The following Error occurs

Error:

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the 
console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor) 
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, 
Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

![Debug - Split Terminal](https://github.com/user-attachments/assets/0858e1a5-45b0-4d72-b617-b29788658763)

**Comment by PN-03** [comment]
This issue was resolved after I installed PowerShell 7.4.6. The old stock version of PowerShell seems to have been the issue,  but now debugging in a split terminal works with no errors.

![Image](https://github.com/user-attachments/assets/ee4fc307-f640-4bd3-aa66-60d15d30951a)

**Comment by PN-03** [comment]
This issue was resolved after installing PowerShell 7.4.6.  The old-stock version of PowerShell seems to have been the problem, but now debugging in a split terminal works with no errors
