### ISSUE TITLE
Invalid Extension: No warning badge on activity bar, should it have one?

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#229488]
Testing #229394

When an extension is invalid and hence is not able to activate, we do not show a badge on the activity bar, should we?

<img width="353" alt="image" src="https://github.com/user-attachments/assets/75df4459-e887-4379-85dd-e11b5399aeec">

Also, the warning is saying `property engines.vscode is mandatory and must be of type string`. I think it would be helpful if we prepended something like: `Invalid Extension: `

**Comment by sandy081** [comment]
Can you please try this on latest insider, because I fixed this yesterday.

**Comment by benibenj** [comment]
This is latest Insiders

**Comment by benibenj** [comment]
Yes 
<img width="441" alt="image" src="https://github.com/user-attachments/assets/9685df3d-7300-4afc-adfd-6bbcd1eef7ba">

**Comment by roblourens** [comment]
I got into a broken state after messing with the package.json. I did this

- Remove `engines.vscode` from the package.json of the installed marketplace version of copilot chat
- Click "uninstall" on the extension
- Click "install pre-release"
- Get this error

```
2024-09-27 11:49:22.364 [error] ScanningExtension: Cannot read the extension from /Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.21.2024092702
    at Ql.scanLocalExtension (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:70:73154)
2024-09-27 11:49:22.366 [error] Cannot read the extension from /Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.21.2024092702: ScanningExtension: Cannot read the extension from /Users/roblou/.vscode-insiders/extensions/github.copilot-chat-0.21.2024092702
    at Ql.scanLocalExtension (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:70:73154)
```

and I couldn't get it fixed until I manually deleted the extension folder under `~/.vscode-insiders/extensions`, and reinstalled. Lmk if you want an issue

**Comment by sandy081** [comment]
I am aware of this. One can get into this state only manually. So deleting manually seems to be reasonable option.
