### ISSUE TITLE
Empty Keybindings View 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#22983]
- VSCode Version: 42bab78641bddd51306e623f699393cd3c3b5c13
- OS Version: OSX

After opening the keybindings file, I see an empty screen:
<img width="651" alt="screen shot 2017-03-21 at 6 48 53 pm" src="https://cloud.githubusercontent.com/assets/12821956/24178565/1f2b82de-0e67-11e7-87fa-bb550833b4d4.png">

This error is printed in the console:

```
TypeError: Cannot read property 'localeCompare' of null
    at Function.n.compareKeybindingData (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:109:26466)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:109:25953
    at Array.sort (native)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:109:25925
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:25264)
    at n.resolve (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:109:25385)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:117:11239
    at then (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:25264)
    at t.render (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:117:11213)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:117:9908

**Comment by sandy081** [comment]
@mjbz Looks like your keybindings file has entries without commands. Still, Keybindings editor should be resilient to such entries. Fixed it by filtering those entries without commands
