### ISSUE TITLE
unable to save notebook due to different edits

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#229883]
going through to test this: https://github.com/microsoft/vscode/issues/228192
https://github.com/user-attachments/assets/44402a90-ffac-4bba-bd97-6ee42f74e5e0

note I forgot to add these settings
```
   "notebook.diff.ignoreMetadata": true,
    "notebook.diff.ignoreOutputs": true
```

got these logs

```
2024-09-26 13:09:23.422 [error] [Extension Host] Trace: trace 13:09:23.420: Jupyter Extension: Python API env change detected, update => '/Users/eleanorboyd/vscode-python/.venv/bin/python'
    at vP.trace (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:97:15250)
    at /Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:98:390
    at Array.forEach (<anonymous>)
    at fee (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:98:377)
    at Object.trace (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:97:15483)
    at $h.<anonymous> (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:115:20527)
    at T.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.C (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:802)
    at T.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1019)
    at gh.value (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:435411)
    at T.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.C (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:802)
    at T.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1019)
    at I.addEnv (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:793459)
    at I.resolveEnv (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:794092)
    at T.getInterpreterDetails (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:784798)
    at f.updateDisplay (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:497219)
    at f.refresh (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:496829)
    at P.refresh (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:507904)
2024-09-26 13:09:43.361 [error] [Extension Host] Trace: trace 13:09:43.346: Jupyter Extension: No controller, hence notebook communications cannot be initialized for editor ~/vscode-python/src/client/testing/testController/ran.ipynb
    at vP.trace (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:97:15250)
    at /Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:98:390
    at Array.forEach (<anonymous>)
    at fee (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:98:377)
    at Object.trace (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:97:15483)
    at np.initializeNotebookCommunication (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:304:68364)
    at /Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:304:68969
    at Array.forEach (<anonymous>)
    at np.onDidChangeVisibleNotebookEditors (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:304:68899)
    at gh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:35160)
    at T.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
    at nh.$acceptDocumentAndEditorsDelta (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:155:14243)
    at Zb.S (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113896)
    at Zb.Q (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113676)
    at Zb.M (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112765)
    at Zb.L (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112003)
    at gh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110667)
    at T.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
    at no.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9399)
    at gh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13273)
    at T.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
    at no.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9399)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11562)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)
2024-09-26 13:09:48.714 [error] [stored file working copy] handleSaveError(1) - exit - resulted in a save error: Error: Document version mismatch file:///Users/eleanorboyd/vscode-python/src/client/testing/testController/ran.ipynb notebook/jupyter-notebook/jupyter-notebook
2024-09-26 13:09:49.215 [error] [stored file working copy] handleSaveError(1) - exit - resulted in a save error: Error: Document version mismatch file:///Users/eleanorboyd/vscode-python/src/client/testing/testController/ran.ipynb notebook/jupyter-notebook/jupyter-notebook
2024-09-26 13:09:49.299 [error] [stored file working copy] handleSaveError(1) - exit - resulted in a save error: Error: Document version mismatch file:///Users/eleanorboyd/vscode-python/src/client/testing/testController/ran.ipynb notebook/jupyter-notebook/jupyter-notebook
2024-09-26 13:10:04.495 [error] [stored file working copy] handleSaveError(1) - exit - resulted in a save error: Error: Document version mismatch file:///Users/eleanorboyd/vscode-python/src/client/testing/testController/ran.ipynb notebook/jupyter-notebook/jupyter-notebook
2024-09-26 13:10:15.537 [error] [stored file working copy] handleSaveError(1) - exit - resulted in a save error: Error: Document version mismatch file:///Users/eleanorboyd/vscode-python/src/client/testing/testController/ran.ipynb notebook/jupyter-notebook/jupyter-notebook
2024-09-26 13:10:24.883 [error] [stored file working copy] handleSaveError(1) - exit - resulted in a save error: Error: Document version mismatch file:///Users/eleanorboyd/vscode-python/src/client/testing/testController/ran.ipynb notebook/jupyter-notebook/jupyter-notebook
2024-09-26 13:10:27.568 [error] [Extension Host] Trace: trace 13:10:27.564: Jupyter Extension: Python API env change detected, update => '/Users/eleanorboyd/vscode-python/.venv/bin/python'
    at vP.trace (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:97:15250)
    at /Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:98:390
    at Array.forEach (<anonymous>)
    at fee (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:98:377)
    at Object.trace (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:97:15483)
    at $h.<anonymous> (/Users/eleanorboyd/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.9.2024092401-darwin-arm64/dist/extension.node.js:115:20527)
    at T.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.C (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:802)
    at T.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1019)
    at gh.value (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:435411)
    at T.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.C (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:802)
    at T.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1019)
    at I.addEnv (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:793459)
    at I.resolveEnv (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:794092)
    at T.getInterpreterDetails (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:784798)
    at f.updateDisplay (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:497219)
    at f.refresh (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:496829)
    at P.refresh (/Users/eleanorboyd/.vscode-insiders/extensions/ms-python.python-2024.15.2024092502-darwin-arm64/out/client/extension.js:2:507904)
```

**Comment by andreamah** [comment]
I think I also ran into something similar while trying to test the same issue. There's some type of version mismatch

![Image](https://github.com/user-attachments/assets/3e146a9a-b646-4581-a6db-b8c9450690f2)

**Comment by andreamah** [comment]
Not sure if it's the same bug. I just:
1. create a notebook by just creating an empty file called `test.ipynb` 
2. add a cell
3. try to save
4. Document mismatch :bug:

**Comment by eleanorjboyd** [comment]
> Not sure if it's the same bug. I just:
> 
> 1. create a notebook by just creating an empty file called `test.ipynb`
> 2. add a cell
> 3. try to save
> 4. Document mismatch 🐛

same steps I used too

**Comment by rebornix** [comment]
Verifier:

- Ensure that `notebook.experimental.remoteSave` is enabled
- Open a notebook, e.g., GitHub issue notebook in VS Code repo
- Modify a cell content and try to save
- No error prompt should show up
