### ISSUE TITLE
[Insiders] Intelli Sense fails for TypeScript

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#22996]
- VSCode Version: 1.11.0-insider (Commit 32942fd950... from 2017-03-22T07:11:40)
- OS Version: Windows Server 2008 R2

Steps to Reproduce:

1. Open Visual Studio Code Insiders
2. Open TypeScript file
3. Try to get Intelli Sense information for a variable
4. You only get a list of "known" variables but not type specific Intelli Sense

Output-Tab shows the following issue:
```
[Error - 9:18:11 AM] 'quickinfo' request failed with error.
Error processing request. Mismatched request id, expected undefined, actual 60
Error: Mismatched request id, expected undefined, actual 60
    at Object.resetRequest (c:\Entwicklung\<Project>\node_modules\typescript\lib\cancellationToken.js:57:27)
    at IOSession.Session.resetCurrentRequest (c:\Entwicklung\<Project>\node_modules\typescript\lib\tsserver.js:73291:40)
    at IOSession.Session.executeWithRequestId (c:\Entwicklung\<Project>\node_modules\typescript\lib\tsserver.js:73299:26)
    at IOSession.Session.executeCommand (c:\Entwicklung\<Project>\node_modules\typescript\lib\tsserver.js:73305:33)
    at IOSession.Session.onMessage (c:\Entwicklung\<Project>\node_modules\typescript\lib\tsserver.js:73325:35)
    at Interface.<anonymous> (c:\Entwicklung\<Project>\node_modules\typescript\lib\tsserver.js:74477:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
```
The project uses TypeScript 2.2.1 and Visual Studio Code has been configured to use the workspace version of TypeScript instead of the built-in version. The identical project worked with yesterdays Insiders build and still works with the current stable build. Switching from the Workspace TypeScript to the built-in TypeScript fixes the issue as well.
`

**Comment by zhengbli** [comment]
Same thing. My error log:
```
[Info  - 1:31:58 AM] Using tsserver from location: C:\Users\lizhe\AppData\Roaming\nvm\v7.5.0\node_modules\typescript\lib\tsserver.js
[Error - 1:31:59 AM] 'compilerOptionsForInferredProjects' request failed with error.
Error processing request. Mismatched request id, expected undefined, actual 1
Error: Mismatched request id, expected undefined, actual 1
    at Object.resetRequest (C:\Users\lizhe\AppData\Roaming\nvm\v7.5.0\node_modules\typescript\lib\cancellationToken.js:57:27)
    at IOSession.Session.resetCurrentRequest (C:\Users\lizhe\AppData\Roaming\nvm\v7.5.0\node_modules\typescript\lib\tsserver.js:74836:40)
    at IOSession.Session.executeWithRequestId (C:\Users\lizhe\AppData\Roaming\nvm\v7.5.0\node_modules\typescript\lib\tsserver.js:74844:26)
    at IOSession.Session.executeCommand (C:\Users\lizhe\AppData\Roaming\nvm\v7.5.0\node_modules\typescript\lib\tsserver.js:74850:33)
    at IOSession.Session.onMessage (C:\Users\lizhe\AppData\Roaming\nvm\v7.5.0\node_modules\typescript\lib\tsserver.js:74870:35)
    at Interface.<anonymous> (C:\Users\lizhe\AppData\Roaming\nvm\v7.5.0\node_modules\typescript\lib\tsserver.js:76022:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
```

**Comment by AvatarWeb1** [comment]
Merci

**Comment by JimiC** [comment]
Same here. In my case, the expected id is `undefined` and actual are 2 and 4.

**Comment by schmuli** [comment]
This is related to #22437

**Comment by schmuli** [comment]
If you use the bundled TS version (2.2.2-insiders) the error doesn't occur.

**Comment by mjbvz** [comment]
Thanks everyone. yes #22437 is the root cause here. I forgot that although the cancellation token API was added in TS 2.2.0, it is broken in releases before TS-2.2.2 insiders. 301d64e should fix the gating. Until then, try upgrading the workspace version of TypeScript to the latest 2.2.2-insiders build or using VSCode's bundled version
