### ISSUE TITLE
Don't reload notebook model if data didn't change

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#230017]
There are a few open issues related to this behavior (https://github.com/microsoft/vscode-jupyter/issues/12863, https://github.com/microsoft/vscode-jupyter/issues/15716) , but I'm trying to get logs to confirm the cause and want to try to figure out a solution separately.
 
Steps to Reproduce:

1. create a notebook cell with the code

```
import time 

for i in range(10):
    time.sleep(3)
    print(i)
```

2. execute the cell, and while it's running, change the `modified time` of the file on disk
e.g. with pwsh

```
$file = get-Item ./notebook.ipynb
$file.LastWriteTime = (Get-Date)
```

You might have to try a few times.

:bug: running cell is cancelled and focus is lost in the notebook

stack for code references:

```
at NotebookFileWorkingCopyModel.update (c:\src\vscode\src\vs\workbench\contrib\notebook\common\notebookEditorModel.ts:349:9)
    at async StoredFileWorkingCopy.doUpdateModel (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopy.ts:711:4)
    at async StoredFileWorkingCopy.resolveFromContent (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopy.ts:674:4)
    at async StoredFileWorkingCopy.resolveFromFile (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopy.ts:615:4)
    at async StoredFileWorkingCopyManager.doResolve (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopyManager.ts:562:4)
    at async StoredFileWorkingCopyManager.reload (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopyManager.ts:453:3)
    at async Object.factory (vscode-file://vscode-app/c:/src/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopyManager.js:167:21)
```

The etag timestamp is checked when resolving to ensure that we are only loading file content if the file is newer: https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L599

**Comment by amunger** [comment]
One hypothesis I've had is that by delegating file writes to the EH for notebooks, the file looks like it has been updated externally. 

There is a check to see if a save operation is in progress to prevent this here:
https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L461
But I don't ever see that getting hit.

Something interesting that I noticed, If I make the EH save operation take a log time to return the etag after writing the file, the filewatcher doesn't trigger at all. @bpasero - do you know why that would happen?

**Comment by bpasero** [comment]
There should be no dependency between the file watcher and code we have written, after all the file watcher will simply report events as notified by the OS. You can run with `--verbose` to get rich event output in the "File Watcher" output channel to diagnose this further.
