### ISSUE TITLE
VSCode freezing when closing Editor tabs with very large files while having the Outline view open

### ISSUE THREAD

**Issue by ZockiRR** [microsoft/vscode#230119]
Type: <b>Performance Issue</b>

I have a custom language symbolprovider for files we use for data transfer.
Some of these files reach 250.000 lines or even more. Each line results in a symbol entry. So the fully expanded outline tree may have more then 250.000 nodes. This works just fine for loading, displaying or navigating.

When I switch from or close the editor tab with this large file while having the Outline view open vscode fully freezes for > 30s.

When I close the Outline before and then close the editor. All works seemlessly, closing the Outline as well as closing the editor tab.
So the issue seems to be in the Outline View. Profiling showed the abstractTree#getViewState function with 30s selftime.

Sadly I currently can't share much more info. Hope it's reproducible.
If not I will try to gather more information in my sparetime.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045

**Comment by ZockiRR** [comment]
Just realised this also happens for very large json files with the build-in json support.

**Comment by jrieken** [comment]
I wasn't able to reproduce this with a file/extension-combination that yields in around 400000 outline entries. Any chance you can share more about your setup? Is it deeply nested trees or a mostly flat structure? Do you have any specific setting/toggle for the outline enabled?

**Comment by ZockiRR** [comment]
Okay. I will try to reproduce it in a private environment where I can share everything, but this could take a few days.

**Comment by jrieken** [comment]
Thanks!

FYI I am using an extension like this. It creates an entry per line in the document and then I open very, very large files

```ts
	vscode.languages.registerDocumentSymbolProvider(['fooLang', { pattern: '**/checker.ts' }], new class implements vscode.DocumentSymbolProvider {
		provideDocumentSymbols(document: vscode.TextDocument, token: vscode.CancellationToken): vscode.ProviderResult<vscode.SymbolInformation[] | vscode.DocumentSymbol[]> {
			const result: vscode.DocumentSymbol[] = [];
			for (let n = 0; n < document.lineCount; n++) {
				const line = document.lineAt(n);
				result.push(new vscode.DocumentSymbol(line.text.substring(0, 13) || '<empty>', '', vscode.SymbolKind.Array, line.range, line.range))
			}
			return result;
		}
	})
```

**Comment by RedCMD** [comment]
I'm getting lots of different `max call stack` errors and many lag spikes while scrolling
but no 30sec freeze on close

<details><summary>click to see errors</summary>

```rust
  ERR Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded: Error: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
	at ae (e:\VSCode-win32-x64\resources\app\extensions\json-language-features\client\dist\node\jsonClientMain.js:1:228009)
	at oe (e:\VSCode-win32-x64\resources\app\extensions\json-language-features\client\dist\node\jsonClientMain.js:1:225969)
	at Immediate.<anonymous> (e:\VSCode-win32-x64\resources\app\extensions\json-language-features\client\dist\node\jsonClientMain.js:1:222263)
	at process.processImmediate (node:internal/timers:478:21)
```

```rust
  ERR Request textDocument/documentSymbol failed with message: Invalid string length: Error: Request textDocument/documentSymbol failed with message: Invalid string length
	at ae (e:\VSCode-win32-x64\resources\app\extensions\json-language-features\client\dist\node\jsonClientMain.js:1:228009)
	at oe (e:\VSCode-win32-x64\resources\app\extensions\json-language-features\client\dist\node\jsonClientMain.js:1:225969)
	at Immediate.<anonymous> (e:\VSCode-win32-x64\resources\app\extensions\json-language-features\client\dist\node\jsonClientMain.js:1:222263)
	at process.processImmediate (node:internal/timers:478:21)
```

```rust
  ERR Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at te.getViewState (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:3182)
    at A.kc (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2430:40462)
    at d.q [as value] (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2430:41605)
    at l.B (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:732)
    at l.C (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:802)
    at l.fire (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:1018)
    at E.p (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1805:114780)
    at E.n (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1805:112709)
    at d.value (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1805:111485)
    at l.B (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:732)
    at l.C (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:802)
    at l.fire (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:866)
    at d.value (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:782:18203)
    at l.B (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:732)
    at l.fire (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:949)
    at v.s (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:131:86800)
    at v.emitOutgoingEvent (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:131:86554)
    at d.value (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:779:29803)
    at l.B (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:732)
    at l.fire (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:949)
    at le.z (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:774:16756)
    at le.endDeferredEmit (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:774:16218)
    at K.changeDecorations (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:774:3076)
    at V.changeDecorations (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:782:10740)
    at x.D (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:805:90468)
    at x.t (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:805:84737)
    at d.value (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:805:83923)
    at l.B (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:732)
    at l.C (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:802)
    at l.fire (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:1018)
    at V.setModel (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:782:507)
    at N.setInput (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2451:29301)
    at async o.S (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2449:24889)
    at async o.L (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2449:23416)
    at async o.openEditor (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2449:22399)
    at async vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2577:27047
```

```rust
  ERR Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at E.U (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:191:12436)
    at E.splice (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:191:11388)
    at vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4:9067
    at Array.forEach (<anonymous>)
    at t.splice (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4:9054)
    at vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:234:8098
    at A.bufferEvents (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:100:3899)
    at te.splice (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:234:8074)
    at te.splice (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:628:64439)
    at f.t (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:187:27391)
    at f.splice (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:187:25598)
    at L.l (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:187:34140)
    at L.setChildren (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:187:33684)
    at C.setChildren (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:6619)
    at Re.J (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:23716)
    at Re.C (vscode-file://vscode-app/e:/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:629:20783)
```
</details>

**Comment by RedCMD** [comment]
change `json.maxItemsComputed` to `50000000`
open file
[200k comments lag.json](https://github.com/user-attachments/files/17238829/200k.comments.lag.json)
open outline
close file
notice 2 max call stack errors

**Comment by benibenj** [comment]
`getViewState` was using `Array.shift()` which is slow for very large arrays. I've pushed a fix. @ZockiRR could you try this out with our insiders build? The build tomorrow will include the fix. You will be able to get it here: https://code.visualstudio.com/insiders/.

**Comment by ZockiRR** [comment]
Thank you very much! The editor tab changes almost instantly now, which is a huge improvement. Now restoring the view state seems to be the slower part. Isn't there a similar throttle here by any chance?
Anyway, my original issue is more than solved. Once again, many thanks. Really appreciate it.

**Comment by benibenj** [comment]
Thanks for letting me know. 

Restoring the view state is a rather slow process in general, not much that can be improved here sadly.
