### ISSUE TITLE
Exception has occurred: Error: process.binding is not supported

### ISSUE THREAD

**Issue by unLomTrois** [microsoft/vscode#230398]
Type: <b>Bug</b>

I decided to rewrite one of my extensions to typescript. So I created one with `yo code`, I opened RUN AND DEBUG, clicked Run Extension. Nothing happened, no "Hello world" message. I enabled Caught Exceptions and Uncaught Exceptions, and get:
```
Exception has occurred: Error: process.binding is not supported
t n.binding (/usr/share/code/resources/app/extensions/git/dist/main.js:2:293433)
	at Object.<anonymous> (/usr/share/code/resources/app/extensions/git/dist/main.js:2:232782)
	at Object.<anonymous> (/usr/share/code/resources/app/extensions/git/dist/main.js:2:232965)
	at i (/usr/share/code/resources/app/extensions/git/dist/main.js:2:230952)
	at Object.<anonymous> (/usr/share/code/resources/app/extensions/git/dist/main.js:2:289783)
	at i (/usr/share/code/resources/app/extensions/git/dist/main.js:2:230952)
	at /usr/share/code/resources/app/extensions/git/dist/main.js:2:231751
	at 8918 (/usr/share/code/resources/app/extensions/git/dist/main.js:2:231760)
	at __webpack_require__ (/usr/share/code/resources/app/extensions/git/dist/main.js:2:1143572)
	at 2489 (/usr/share/code/resources/app/extensions/git/dist/main.js:2:903164)
	at __webpack_require__ (/usr/share/code/resources/app/extensions/git/dist/main.js:2:1143572)
	at 908 (/usr/share/code/resources/app/extensions/git/dist/main.js:2:950586)
	at __webpack_require__ (/usr/share/code/resources/app/extensions/git/dist/main.js:2:1143572)
	at /usr/share/code/resources/app/extensions/git/dist/main.js:2:1144065
	at Object.<anonymous> (/usr/share/code/resources/app/extensions/git/dist/main.js:2:1144315)
	at Module._compile (node:internal/modules/cjs/loader:1373:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at y._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:184:6031)
	at i._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:181:32144)
	at n._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:146:34326)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at i (/usr/share/code/resources/app/out/bootstrap-fork.js:3:98)
	at m.xb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:181:33345)
	at async Promise.all (index 0)
```

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 3764)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.40GB (8.09GB free)|
|Process Argv|-r . --crash-reporter-id d5c48306-b21d-4b82-a7e9-0018cde2d429|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
extension-test-runner|ms-|0.0.12
One-dark-pro|zhu|3.17.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31150322
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by unLomTrois** [comment]
A similar problem was discussed here: https://github.com/microsoft/vscode-discussions/discussions/936

But they didn't figure it out and decided to move an issue here. I didn't find a new issue and decided to create my own.

**Comment by roblourens** [comment]
That error looks like it's from the builtin git extension, not yours, I'm not sure it's part of the issue

**Comment by sagelywizard** [comment]
I'm seeing this same error. Also in the built-in git extension. The extension development host window did start. The extension's command in the command palette weren't available.
