### ISSUE TITLE
workbench.action.chat.submit Doesn't work after inlineChat.start

### ISSUE THREAD

**Issue by kalanyuz** [microsoft/vscode#230364]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: macOS 14.7 (23H124)

```
[
    {
        "key": "cmd+k cmd+c",
        "command": "runCommands",
        "args": {
            "commands": [
                {
                    "command": "inlineChat.start"
                },
                {
                    "command": "type",
                    "args": {
                        "text": "/doc "
                    },
                },
                {
                    "command": "workbench.action.chat.submit",
                },
            ]
        },
    },
]
```

Also workbench.action.quickchat.launchInlineChat can't be followed with type command afterwards.

Steps to Reproduce:

1. Copy the keybindings in keybindings.json
2. Open an editor and try the keybinding.

I got the inline chat modal with the commands typed in to show up.
Using the keyboard shortcut monitoring tool I found that workbench.action.chat.submit gets executed when I press enter to confirm the modal
However I cannot replicate the steps. I'd get the following error in the output tab:
```
2024-10-04 09:06:50.961 [error] Unexpected type: Error: Unexpected type
    at f (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:100:39177)
    at Object.resolveData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2757:33552)
    at z.tb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2672:110425)
    at z.acceptInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2672:109989)
    at i.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2368:1063)
    at handler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:700:21538)
    at f.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:666:684)
    at w.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1745:32236)
    at w.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1745:31824)
    at S.b (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:852:20692)
    at S.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:852:20212)
```
---
Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by jrieken** [comment]
Where does the `runCommands` command come from?

**Comment by kalanyuz** [comment]
Hi @jrieken. Not sure I understand your question.
I'm following this guide: https://code.visualstudio.com/docs/getstarted/keybindings#_running-multiple-commands trying to run multiple commands at a key press.

1. I got the inline chat modal with the commands typed in to show up.
2. Using the keyboard shortcut monitoring tool I found that `workbench.action.chat.submit` gets executed when I press `enter` to confirm the modal

However I cannot replicate the steps. I'd get the following error in the output tab:
```
2024-10-04 09:06:50.961 [error] Unexpected type: Error: Unexpected type
    at f (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:100:39177)
    at Object.resolveData (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2757:33552)
    at z.tb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2672:110425)
    at z.acceptInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2672:109989)
    at i.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2368:1063)
    at handler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:700:21538)
    at f.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:666:684)
    at w.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1745:32236)
    at w.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1745:31824)
    at S.b (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:852:20692)
    at S.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:852:20212)
```

**Comment by jrieken** [comment]
Sorry, didn't know that `runCommands` is something that ships with VS Code. Have to understand what it does and why this doesn't work but generally not all commands can be used like that, the inline chat command doesn't return (and runs the next command) until the whole operation is done

**Comment by jrieken** [comment]
As stated earlier, the `inineChat.start` command wait for the session to finish, therefore the command sequence doesn't work. Tho, the command accepts argument and you can use `message` and `autoSend` from here https://github.com/microsoft/vscode/blob/f10bb2140999946ed845db28da29f65a75373ae7/src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts#L74-L83
