### ISSUE TITLE
notebook editors not rendering correctly

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#230448]
![image](https://github.com/user-attachments/assets/8fba5b6c-7416-4097-b6e3-e0e396524c37)

Steps to Reproduce:

1. open a notebook 
:bug: cells are not rendered correctly

**Comment by amunger** [comment]
```
TypeError: Cannot read properties of undefined (reading 'minimapWidth')
    at EditorScrollbar._setLayout (editorScrollbar.ts:119:80)
    at new EditorScrollbar (editorScrollbar.ts:71:8)
    at new View (view.ts:161:21)
    at CodeEditorWidget._createView (codeEditorWidget.ts:1861:16)
    at CodeEditorWidget._attachModel (codeEditorWidget.ts:1763:36)
    at CodeEditorWidget.setModel (codeEditorWidget.ts:498:9)
    at ReplEditor.setInput (replEditor.ts:443:26)
    at async EditorPanes.doSetInput (editorPanes.ts:449:4)
    at async EditorPanes.doOpenEditor (editorPanes.ts:255:34)
    at async EditorPanes.openEditor (editorPanes.ts:132:11)
```

**Comment by amunger** [comment]
seems fixed now
