### ISSUE TITLE
1.94.0: corrupt package-lock.json inside extensions/git and test/monaco

### ISSUE THREAD

**Issue by brjsp** [microsoft/vscode#230430]
I am trying to build vscode 1.94.0 from source on GNU/Linux. The first step is vendoring all the node modules, which i do by running `npm ci  --verbose --ignore-scripts` in every directory which has a `package-lock.json` (policy requires us to do the actual build on machines without internet access)

While doing this inside `extensions/git` i receive the following error:
```
sh -c ' cd ./extensions/git && npm ci  --verbose --ignore-scripts || exit 255'
npm verbose cli /usr/bin/node22 /usr/bin/npm22
npm info using npm@10.8.1
npm info using node@v22.3.0
npm verbose title npm ci
npm verbose argv "ci" "--loglevel" "verbose" "--ignore-scripts"
npm verbose logfile logs-max:10 dir:/tmp/.npm/_logs/2024-10-03T19_46_26_450Z-
npm verbose logfile /tmp/.npm/_logs/2024-10-03T19_46_26_450Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/tslib 249ms (cache miss)
npm verbose stack Error: 
npm verbose stack `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm verbose stack
npm verbose stack Missing: tslib@2.7.0 from lock file
npm verbose stack
npm verbose stack Clean install a project
npm verbose stack
npm verbose stack Usage:
npm verbose stack npm ci
npm verbose stack
npm verbose stack Options:
npm verbose stack [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm verbose stack [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm verbose stack [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
npm verbose stack [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
npm verbose stack [--no-bin-links] [--no-fund] [--dry-run]
npm verbose stack [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm verbose stack [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm verbose stack
npm verbose stack aliases: clean-install, ic, install-clean, isntall-clean
npm verbose stack
npm verbose stack Run "npm help ci" for more info
npm verbose stack     at CI.usageError (/usr/lib64/node_modules/npm22/lib/base-cmd.js:109:26)
npm verbose stack     at CI.exec (/usr/lib64/node_modules/npm22/lib/commands/ci.js:70:18)
npm verbose stack     at async Npm.exec (/usr/lib64/node_modules/npm22/lib/npm.js:207:9)
npm verbose stack     at async module.exports (/usr/lib64/node_modules/npm22/lib/cli/entry.js:74:5)
npm error code EUSAGE
npm error
npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm error
npm error Missing: tslib@2.7.0 from lock file
npm error
npm error Clean install a project
npm error
npm error Usage:
npm error npm ci
npm error
npm error Options:
npm error [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm error [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm error [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
npm error [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
npm error [--no-bin-links] [--no-fund] [--dry-run]
npm error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm error [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm error
npm error aliases: clean-install, ic, install-clean, isntall-clean
npm error
npm error Run "npm help ci" for more info
npm verbose cwd /tmp/vscode-9WboZsHA/vscode-1.94.0/extensions/git
npm verbose os Linux 6.11.0-1-default
npm verbose node v22.3.0
npm verbose npm  v10.8.1
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: /tmp/.npm/_logs/2024-10-03T19_46_26_450Z-debug-0.log
```

Please update the `package-lock.json` to ensure all the dependencies are there. (Otherwise just doing `npm install` will pick an arbitrary versions, which makes it impossible to verify the source corresponding to a particular binary and opens you to supply chain attacks)

**Comment by brjsp** [comment]
@deepak1556 I suspect #230214 may fix this, will try backporting this and let you know.

**Comment by brjsp** [comment]
@deepak1556 After backporting that patch, `test/monaco` shows even more severe errors:
```
sh -c ' cd ./test/monaco && npm ci  --verbose --ignore-scripts || exit 255'
npm verbose cli /usr/bin/node22 /usr/bin/npm22
npm info using npm@10.8.1
npm info using node@v22.3.0
npm verbose title npm ci
npm verbose argv "ci" "--loglevel" "verbose" "--ignore-scripts"
npm verbose logfile logs-max:10 dir:/tmp/.npm/_logs/2024-10-04T11_09_32_352Z-
npm verbose logfile /tmp/.npm/_logs/2024-10-04T11_09_32_352Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/webpack 352ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2festree 137ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/acorn-import-attributes 238ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/events 132ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/chrome-trace-event 280ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/eslint-scope 295ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/glob-to-regexp 107ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/acorn 359ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/enhanced-resolve 374ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fast 382ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/es-module-lexer 383ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-edit 394ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-parser 396ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/json-parse-even-better-errors 117ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/browserslist 402ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/loader-runner 102ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/graceful-fs 135ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tapable 75ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/neo-async 91ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/mime-types 109ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/watchpack 73ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/webpack-sources 73ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/terser-webpack-plugin 84ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/schema-utils 95ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/webpack 16ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-parser 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-wasm-section 88ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwast-printer 93ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-numbers 111ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-wasm-bytecode 107ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-wasm-bytecode 118ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-api-error 119ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-wasm-bytecode 129ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-opt 127ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-buffer 134ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-gen 139ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fieee754 117ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/graceful-fs 24ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tapable 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2futf8 86ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fleb128 107ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/update-browserslist-db 83ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/esrecurse 79ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/node-releases 100ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/estraverse 81ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/mime-db 85ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fjson-schema 83ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/ajv-keywords 70ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/ajv 110ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/serialize-javascript 79ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/terser 102ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/jest-worker 101ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@jridgewell%2ftrace-mapping 93ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/caniuse-lite 222ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/electron-to-chromium 245ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2ffloating-point-hex-parser 86ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@xtuc%2flong 103ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@xtuc%2fieee754 70ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/browserslist 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/picocolors 49ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/escalade 60ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/estraverse 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/uri-js 53ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/fast-json-stable-stringify 58ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/fast-deep-equal 60ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/json-schema-traverse 64ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/punycode 59ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/source-map-support 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/supports-color 16ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/commander 22ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/randombytes 48ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/merge-stream 74ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fresolve-uri 78ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fsourcemap-codec 85ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fsource-map 95ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 233ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/has-flag 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/undici-types 52ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 53ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/source-map 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/buffer-from 61ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fgen-mapping 109ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fset-array 85ms (cache miss)
npm verbose stack Error: 
npm verbose stack `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm verbose stack
npm verbose stack Missing: webpack@5.95.0 from lock file
npm verbose stack Missing: @types/estree@1.0.6 from lock file
npm verbose stack Missing: @webassemblyjs/ast@1.12.1 from lock file
npm verbose stack Missing: @webassemblyjs/wasm-edit@1.12.1 from lock file
npm verbose stack Missing: @webassemblyjs/wasm-parser@1.12.1 from lock file
npm verbose stack Missing: acorn@8.12.1 from lock file
npm verbose stack Missing: acorn-import-attributes@1.9.5 from lock file
npm verbose stack Missing: browserslist@4.24.0 from lock file
npm verbose stack Missing: chrome-trace-event@1.0.4 from lock file
npm verbose stack Missing: enhanced-resolve@5.17.1 from lock file
npm verbose stack Missing: es-module-lexer@1.5.4 from lock file
npm verbose stack Missing: eslint-scope@5.1.1 from lock file
npm verbose stack Missing: events@3.3.0 from lock file
npm verbose stack Missing: glob-to-regexp@0.4.1 from lock file
npm verbose stack Missing: graceful-fs@4.2.11 from lock file
npm verbose stack Missing: json-parse-even-better-errors@2.3.1 from lock file
npm verbose stack Missing: loader-runner@4.3.0 from lock file
npm verbose stack Missing: mime-types@2.1.35 from lock file
npm verbose stack Missing: neo-async@2.6.2 from lock file
npm verbose stack Missing: schema-utils@3.3.0 from lock file
npm verbose stack Missing: tapable@2.2.1 from lock file
npm verbose stack Missing: terser-webpack-plugin@5.3.10 from lock file
npm verbose stack Missing: watchpack@2.4.2 from lock file
npm verbose stack Missing: webpack-sources@3.2.3 from lock file
npm verbose stack Missing: @webassemblyjs/helper-numbers@1.11.6 from lock file
npm verbose stack Missing: @webassemblyjs/helper-wasm-bytecode@1.11.6 from lock file
npm verbose stack Missing: @webassemblyjs/floating-point-hex-parser@1.11.6 from lock file
npm verbose stack Missing: @webassemblyjs/helper-api-error@1.11.6 from lock file
npm verbose stack Missing: @xtuc/long@4.2.2 from lock file
npm verbose stack Missing: @webassemblyjs/helper-buffer@1.12.1 from lock file
npm verbose stack Missing: @webassemblyjs/helper-wasm-section@1.12.1 from lock file
npm verbose stack Missing: @webassemblyjs/wasm-gen@1.12.1 from lock file
npm verbose stack Missing: @webassemblyjs/wasm-opt@1.12.1 from lock file
npm verbose stack Missing: @webassemblyjs/wast-printer@1.12.1 from lock file
npm verbose stack Missing: @webassemblyjs/ieee754@1.11.6 from lock file
npm verbose stack Missing: @webassemblyjs/leb128@1.11.6 from lock file
npm verbose stack Missing: @webassemblyjs/utf8@1.11.6 from lock file
npm verbose stack Missing: @xtuc/ieee754@1.2.0 from lock file
npm verbose stack Missing: caniuse-lite@1.0.30001667 from lock file
npm verbose stack Missing: electron-to-chromium@1.5.32 from lock file
npm verbose stack Missing: node-releases@2.0.18 from lock file
npm verbose stack Missing: update-browserslist-db@1.1.1 from lock file
npm verbose stack Missing: esrecurse@4.3.0 from lock file
npm verbose stack Missing: estraverse@4.3.0 from lock file
npm verbose stack Missing: estraverse@5.3.0 from lock file
npm verbose stack Missing: mime-db@1.52.0 from lock file
npm verbose stack Missing: @types/json-schema@7.0.15 from lock file
npm verbose stack Missing: ajv@6.12.6 from lock file
npm verbose stack Missing: ajv-keywords@3.5.2 from lock file
npm verbose stack Missing: fast-deep-equal@3.1.3 from lock file
npm verbose stack Missing: fast-json-stable-stringify@2.1.0 from lock file
npm verbose stack Missing: json-schema-traverse@0.4.1 from lock file
npm verbose stack Missing: uri-js@4.4.1 from lock file
npm verbose stack Missing: @jridgewell/trace-mapping@0.3.25 from lock file
npm verbose stack Missing: jest-worker@27.5.1 from lock file
npm verbose stack Missing: serialize-javascript@6.0.2 from lock file
npm verbose stack Missing: terser@5.34.1 from lock file
npm verbose stack Missing: @jridgewell/resolve-uri@3.1.2 from lock file
npm verbose stack Missing: @jridgewell/sourcemap-codec@1.5.0 from lock file
npm verbose stack Missing: @types/node@22.7.4 from lock file
npm verbose stack Missing: merge-stream@2.0.0 from lock file
npm verbose stack Missing: supports-color@8.1.1 from lock file
npm verbose stack Missing: undici-types@6.19.8 from lock file
npm verbose stack Missing: randombytes@2.1.0 from lock file
npm verbose stack Missing: safe-buffer@5.2.1 from lock file
npm verbose stack Missing: has-flag@4.0.0 from lock file
npm verbose stack Missing: @jridgewell/source-map@0.3.6 from lock file
npm verbose stack Missing: commander@2.20.3 from lock file
npm verbose stack Missing: source-map-support@0.5.21 from lock file
npm verbose stack Missing: @jridgewell/gen-mapping@0.3.5 from lock file
npm verbose stack Missing: @jridgewell/set-array@1.2.1 from lock file
npm verbose stack Missing: buffer-from@1.1.2 from lock file
npm verbose stack Missing: source-map@0.6.1 from lock file
npm verbose stack Missing: escalade@3.2.0 from lock file
npm verbose stack Missing: picocolors@1.1.0 from lock file
npm verbose stack Missing: punycode@2.3.1 from lock file
npm verbose stack
npm verbose stack Clean install a project
npm verbose stack
npm verbose stack Usage:
npm verbose stack npm ci
npm verbose stack
npm verbose stack Options:
npm verbose stack [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm verbose stack [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm verbose stack [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
npm verbose stack [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
npm verbose stack [--no-bin-links] [--no-fund] [--dry-run]
npm verbose stack [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm verbose stack [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm verbose stack
npm verbose stack aliases: clean-install, ic, install-clean, isntall-clean
npm verbose stack
npm verbose stack Run "npm help ci" for more info
npm verbose stack     at CI.usageError (/usr/lib64/node_modules/npm22/lib/base-cmd.js:109:26)
npm verbose stack     at CI.exec (/usr/lib64/node_modules/npm22/lib/commands/ci.js:70:18)
npm verbose stack     at async Npm.exec (/usr/lib64/node_modules/npm22/lib/npm.js:207:9)
npm verbose stack     at async module.exports (/usr/lib64/node_modules/npm22/lib/cli/entry.js:74:5)
```

**Comment by deepak1556** [comment]
Probably good timing, I just happened to address that error in https://github.com/microsoft/vscode/pull/230479/files. Can you test with those changes added as well.

**Comment by deepak1556** [comment]
Thanks for confirming! Do you still need us to backport these changes to `release/1.94` or are you able to work with downstream patches ?

**Comment by brjsp** [comment]
I'm able to work with downstream patches myself.
