### ISSUE TITLE
Extensions not updated with vscode insiders today

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#230682]
```
Version: 1.95.0-insider
Commit: 0ca72abae2123195125c9809525eb07f63da0e53
Date: 2024-10-07T05:03:51.952Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Darwin arm64 24.0.0
```
* previous `sharedprocess.log`:
```
2024-10-04 18:23:57.312 [error] [network] #64: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_NETWORK_CHANGED
2024-10-04 18:28:57.335 [error] [network] #65: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_INTERNET_DISCONNECTED
2024-10-04 18:33:57.350 [error] [network] #66: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_INTERNET_DISCONNECTED
2024-10-04 18:52:16.965 [error] [network] #67: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_INTERNET_DISCONNECTED
2024-10-05 03:10:31.183 [error] [network] #103: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_NETWORK_CHANGED
2024-10-06 06:11:15.144 [error] [network] #217: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_RESET
2024-10-07 08:31:34.283 [error] [network] #329: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_NETWORK_CHANGED
2024-10-07 08:32:08.241 [error] [network] #330: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_INTERNET_DISCONNECTED
2024-10-07 08:48:44.803 [error] [network] #331: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_INTERNET_DISCONNECTED
2024-10-07 09:01:46.204 [error] [network] #332: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_INTERNET_DISCONNECTED
2024-10-07 09:19:41.864 [error] [network] #333: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_INTERNET_DISCONNECTED
2024-10-07 09:47:08.220 [error] [network] #336: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_NETWORK_CHANGED
2024-10-07 09:56:13.746 [error] [network] #337: https://vscode-sync-insiders.trafficmanager.net/v1/manifest - error GET net::ERR_NETWORK_CHANGED
2024-10-07 10:01:56.071 [info] Getting Manifest... github.copilot-chat
2024-10-07 10:01:56.072 [info] Getting Manifest... github.vscode-pull-request-github
2024-10-07 10:01:56.072 [info] Getting Manifest... ms-vscode.js-debug-nightly
2024-10-07 10:01:56.265 [info] Installing extension: github.copilot-chat {"installPreReleaseVersion":true,"productVersion":{"version":"1.95.0-insider","date":"1970-01-01T00:00:00.000Z"},"pinned":true,"operation":3,"isApplicationScoped":false,"profileLocation":{"$mid":1,"external":"vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json","path":"/Users/alex/.vscode-insiders/extensions/extensions.json","scheme":"vscode-userdata"},"installOnlyNewlyAddedFromExtensionPack":true}
2024-10-07 10:01:56.266 [info] Installing extension: github.vscode-pull-request-github {"installPreReleaseVersion":true,"productVersion":{"version":"1.95.0-insider","date":"1970-01-01T00:00:00.000Z"},"pinned":true,"operation":3,"isApplicationScoped":false,"profileLocation":{"$mid":1,"external":"vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json","path":"/Users/alex/.vscode-insiders/extensions/extensions.json","scheme":"vscode-userdata"},"installOnlyNewlyAddedFromExtensionPack":true}
2024-10-07 10:01:56.267 [info] Installing extension: ms-vscode.js-debug-nightly {"productVersion":{"version":"1.95.0-insider","date":"1970-01-01T00:00:00.000Z"},"pinned":true,"operation":3,"isApplicationScoped":false,"profileLocation":{"$mid":1,"external":"vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json","path":"/Users/alex/.vscode-insiders/extensions/extensions.json","scheme":"vscode-userdata"},"installOnlyNewlyAddedFromExtensionPack":true}
2024-10-07 10:01:58.027 [info] Extracted extension to file:///Users/alex/.vscode-insiders/extensions/ms-vscode.js-debug-nightly-2024.10.417: ms-vscode.js-debug-nightly
2024-10-07 10:01:58.037 [info] Renamed to /Users/alex/.vscode-insiders/extensions/ms-vscode.js-debug-nightly-2024.10.417
2024-10-07 10:01:58.517 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/Users/alex/.vscode-insiders/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/Users/alex/.vscode-insiders/extensions/extensions.json.vsctmp'
    at hm.create (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:35:39254)
    at Es (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:35:39361)
    at Fr.ib (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:71:22677)
    at Fr.stat (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:71:16010)
    at async Yl.stat (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:70:84491)
    at async Gl.yb (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:70:66605)
2024-10-07 10:01:58.680 [info] Marked extension as uninstalled ms-vscode.js-debug-nightly-2024.10.317
```

* current `sharedprocess.log`:
```
2024-10-07 10:02:17.545 [info] Deleted uninstalled extension from disk ms-vscode.js-debug-nightly /Users/alex/.vscode-insiders/extensions/ms-vscode.js-debug-nightly-2024.10.317
2024-10-07 10:02:20.636 [info] Getting Manifest... github.copilot-chat
2024-10-07 10:02:20.636 [info] Getting Manifest... github.vscode-pull-request-github
2024-10-07 10:02:20.724 [info] Getting Manifest... github.copilot-chat
2024-10-07 10:02:20.725 [info] Getting Manifest... github.vscode-pull-request-github
2024-10-07 10:02:20.797 [info] Installing extension: github.copilot-chat {"installPreReleaseVersion":true,"productVersion":{"version":"1.95.0-insider","date":"2024-10-07T05:03:51.952Z"},"pinned":true,"operation":3,"isApplicationScoped":false,"profileLocation":{"$mid":1,"external":"vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json","path":"/Users/alex/.vscode-insiders/extensions/extensions.json","scheme":"vscode-userdata"},"installOnlyNewlyAddedFromExtensionPack":true}
2024-10-07 10:02:20.798 [info] Installing extension: github.vscode-pull-request-github {"installPreReleaseVersion":true,"productVersion":{"version":"1.95.0-insider","date":"2024-10-07T05:03:51.952Z"},"pinned":true,"operation":3,"isApplicationScoped":false,"profileLocation":{"$mid":1,"external":"vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json","path":"/Users/alex/.vscode-insiders/extensions/extensions.json","scheme":"vscode-userdata"},"installOnlyNewlyAddedFromExtensionPack":true}
2024-10-07 10:02:20.798 [info] Extension is already requested to install github.copilot-chat vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json
2024-10-07 10:02:20.799 [info] Extension is already requested to install github.vscode-pull-request-github vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json
2024-10-07 10:02:28.721 [info] Extracted extension to file:///Users/alex/.vscode-insiders/extensions/github.vscode-pull-request-github-0.99.2024100704: github.vscode-pull-request-github
2024-10-07 10:02:28.754 [info] Renamed to /Users/alex/.vscode-insiders/extensions/github.vscode-pull-request-github-0.99.2024100704
2024-10-07 10:02:29.028 [info] Extracted extension to file:///Users/alex/.vscode-insiders/extensions/github.copilot-chat-0.22.2024100701: github.copilot-chat
2024-10-07 10:02:29.095 [info] Marked extension as uninstalled github.vscode-pull-request-github-0.99.2024100313
2024-10-07 10:02:29.118 [info] Renamed to /Users/alex/.vscode-insiders/extensions/github.copilot-chat-0.22.2024100701
2024-10-07 10:02:29.124 [info] Extension installed successfully: github.vscode-pull-request-github vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json
2024-10-07 10:02:30.184 [info] Marked extension as uninstalled github.copilot-chat-0.22.2024100401
2024-10-07 10:02:30.185 [info] Extension installed successfully: github.copilot-chat vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json
```

Note how the previous vscode knew it had to update the chat and GHPR extensions but it didn't finish?

**Comment by sandy081** [comment]
> Note how the previous vscode knew it had to update the chat and GHPR extensions but it didn't finish?

Looking at the timestamps, it seems you have restarted VS Code Insiders to update to newer version while extensions getting installed.

```
2024-10-07 10:02:28.721 [info] Extracted extension to file:///Users/alex/.vscode-insiders/extensions/github.vscode-pull-request-github-0.99.2024100704: github.vscode-pull-request-github
2024-10-07 10:02:28.754 [info] Renamed to /Users/alex/.vscode-insiders/extensions/github.vscode-pull-request-github-0.99.2024100704
2024-10-07 10:02:29.028 [info] Extracted extension to file:///Users/alex/.vscode-insiders/extensions/github.copilot-chat-0.22.2024100701: github.copilot-chat
2024-10-07 10:02:29.095 [info] Marked extension as uninstalled github.vscode-pull-request-github-0.99.2024100313
2024-10-07 10:02:29.118 [info] Renamed to /Users/alex/.vscode-insiders/extensions/github.copilot-chat-0.22.2024100701
2024-10-07 10:02:29.124 [info] Extension installed successfully: github.vscode-pull-request-github vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json
2024-10-07 10:02:30.184 [info] Marked extension as uninstalled github.copilot-chat-0.22.2024100401
2024-10-07 10:02:30.185 [info] Extension installed successfully: github.copilot-chat vscode-userdata:/Users/alex/.vscode-insiders/extensions/extensions.json
```

From above log extensions seems to be updated to latest versions.

`github.vscode-pull-request-github-0.99.2024100704` is installed and `github.vscode-pull-request-github-0.99.2024100313` uninstalled
`github.copilot-chat-0.22.2024100701` is installed and `github.copilot-chat-0.22.2024100401` is uninstalled

Can you please share more information why you think extensions were not updated.
