### ISSUE TITLE
Crash when typing into TypeScript file

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#23069]
Here are 3 screenshots of the freeze and subsequent crash, it was consistently happening when I tried to redo the task. I'm guessing it's related to Electron and/or the minimap based on the trace.

![image](https://cloud.githubusercontent.com/assets/2193314/24229403/7102af86-0f36-11e7-96d6-e941ada49675.png)

![image](https://cloud.githubusercontent.com/assets/2193314/24229417/7f76329a-0f36-11e7-873b-4bdeba82d909.png)

![image](https://cloud.githubusercontent.com/assets/2193314/24229458/b38c754e-0f36-11e7-82a4-1151bf85577f.png)

Here's the verbose output:

```

~
❯ c --verbose
[main 19:31:42] Starting VS Code in verbose mode
[main 19:31:42] from: /usr/share/code-insiders/resources/app
[main 19:31:42] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 19:31:43] IPC#vscode-machineId
[main 19:31:45] IPC#vscode-workbenchLoaded
[6837:0322/193145:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[6837:0322/193145:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[6837:0322/193145:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[6837:0322/193145:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[VS Code]: detected unresponsive
[main 19:32:31] IPC#vscode-machineId
[6837:0322/193232:INFO:CONSOLE(5)] "[uncaught exception]: Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/code-insiders/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/code-insiders/resources/electron.asar/browser/rpc-server.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/usr/share/code-insiders/resources/electron.asar/browser/api/web-contents.js:228:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[6837:0322/193232:INFO:CONSOLE(5)] "Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/code-insiders/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/code-insiders/resources/electron.asar/browser/rpc-server.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/usr/share/code-insiders/resources/electron.asar/browser/api/web-contents.js:228:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/share/code-insiders/resources/electron.asar/renderer/api/remote.js:217:13)
    at descriptor.get [as id] (/usr/share/code-insiders/resources/electron.asar/renderer/api/remote.js:129:16)
    at new t (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:141:1106)
    at g (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:3720)
    at t._createInstance (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:66:27993)
    at t.createInstance (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:66:26764)
    at e.createContents (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:146:12798)
    at e.open (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:146:20968)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:146:23899
    at Object.g [as _notify] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18429)", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[6837:0322/193232:INFO:CONSOLE(146)] "Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Error (native)
    at new e (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:21446)
    at t._getBuffer (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:25168)
    at t.render (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:27047)
    at t._actualRender (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:1578)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:621
    at G (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:80:12307)
    at t._renderNow (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:599)
    at t._flushAccumulatedAndRenderNow (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:80:19273)
    at t._onRenderScheduled (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:521)", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (146)
[6837:0322/193233:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[6837:0322/193233:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[6837:0322/193233:INFO:CONSOLE(146)] "Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Error (native)
    at new e (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:21446)
    at t._getBuffer (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:25168)
    at t.render (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:27047)
    at t._actualRender (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:1578)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:621
    at G (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:80:12307)
    at t._renderNow (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:599)
    at t._flushAccumulatedAndRenderNow (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:80:19273)
    at t._onRenderScheduled (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:521)", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (146)
[6837:0322/193234:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[6837:0322/193234:INFO:CONSOLE(52)] "%c[IPC Library: Watcher]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (52)
[6837:0322/193257:INFO:CONSOLE(146)] "Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Error (native)
    at new e (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:21446)
    at t._getBuffer (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:25168)
    at t.render (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:57:27047)
    at t._actualRender (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:1578)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:621
    at G (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:80:12307)
    at t._renderNow (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:599)
    at t._flushAccumulatedAndRenderNow (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:80:19273)
    at t._onRenderScheduled (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:81:521)", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (146)
[main 19:32:58] Lifecycle#window-before-close 1
[main 19:32:58] Lifecycle#window-before-close 1
[main 19:32:58] Lifecycle#window-close 1
[main 19:32:58] Lifecycle#window-all-closed
[main 19:32:58] Lifecycle#before-quit
[main 19:32:58] App#will-quit: disposing resources
[6864:0322/193258:WARNING:x11_util.cc(1409)] X error received: serial 207, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
```

**Comment by bpasero** [comment]
@Tyriar can you share more exact repro steps please (e.g. which file, what you typed?)

**Comment by Tyriar** [comment]
This was in `.../terminal/common/terminal.ts` I was trying to type `NEVER_SUGGEST_SELECT_WINDOWS_SHELL` but it always crashed. I was half way through this commit when it happened https://github.com/Microsoft/vscode/commit/3cb39e1a195c5c7554c78b28000b1d06c0a27777, though I think I may have also had other uncommited changes in git.

**Comment by bpasero** [comment]
No repro for me.

**Comment by Tyriar** [comment]
Well the exception reads:

```
Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.
```

We only call `createImageData` in `MiniMapBuffers` and somehow it's being called with a width of 0 so we probably just need to be more defensive there.

**Comment by bpasero** [comment]
@Tyriar maybe next time not call it "crash", I was totally looking into the wrong direction (aka native crash).

**Comment by Tyriar** [comment]
@bpasero it was a crash by my definition, everything froze up and the non responsive window dialog popped up ~10 seconds later. See the screenshot at the top.

**Comment by alexandrudima** [comment]
To investigate 100% CPU usage:
* open dev tools
* press pause
* observe: logic is in endless recursion in matching suggestions

I know because I ran into the same

**Comment by jrieken** [comment]
Yeah, there was an endless recursion issue with fuzzyScore, tho I have nuked the code last Thursday. Closing optimistically because the scenario looks exactly like the one @alexandrudima describes above
