### ISSUE TITLE
Run Build Task fails with "Cannot split a terminal without a group"

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#231083]
Type: <b>Bug</b>

- Cmd-B in a VS Code project which should launch 3 scripts.
- Error notification: `Cannot split a terminal without a group (instanceId: 2, title: npm: watch:tsc-extension)`.
- `Building …` is stuck in loading.

Closed all terminals and still doesn't work

```
TRACE Found terminal to split for group watch
log.ts:439   ERR Cannot split a terminal without a group (instanceId: 2, title: npm: watch:tsc-extension): Error: Cannot split a terminal without a group (instanceId: 2, title: npm: watch:tsc-extension)
    at Kv.Sb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2431:115280)
    at Kv.createTerminal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2431:114088)
    at async IE.Cb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2503:15746)
    at async IE.Fb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2503:18379)
    at async IE.xb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2503:8110)
```

VS Code version: Code - Insiders 1.95.0-insider (490dc3da779118d14a16d3b149d8c44edb9b1e07, 2024-10-10T05:09:29.500Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 6, 6|
|Memory (System)|64.00GB (13.49GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by digitarald** [comment]
Duplicate of #226494
