### ISSUE TITLE
"Sign in to Azure" fails with ERR_SSL_PROTOCOL_ERROR error

### ISSUE THREAD

**Issue by dluc** [microsoft/vscode#231046]
- VS Code Version: September 2024 (Version: 1.94.2 Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427)
- OS Version: MacOS Sequoia 15.0.1, Apple M3
- Browser: tested on Edge and Firefox, both up to date

Steps to Reproduce:

1. Uninstall all VS Code extensions. OS reboot.
2. Launch VS Code and Install one extension that uses Azure, e.g. Logic App Standard.
3. Click on Azure extension and select "Sign in to Azure..."

What happens:
* This URL opens in the browser: `https://127.0.0.1:51006/signin?nonce=....`
* The browser returns an error: 

      The connection for this site is not secure
      127.0.0.1 sent an invalid response.
      ERR_SSL_PROTOCOL_ERROR

**Comment by dluc** [comment]
I'm using 1.94.2

**Comment by dluc** [comment]
Not sure if this is relevant:

```
dotnet dev-certs https -c
No valid certificate found.
```

```
dotnet dev-certs https --trust
There was an error creating the HTTPS developer certificate.
```

```
dotnet dev-certs https --trust -v
[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'security add-trusted-cert -p basic -p ssl -k <<login-keychain>> <<certificate>>'
This command might prompt you for your password to install the certificate on the keychain. To undo these changes: 'security remove-trusted-cert <<certificate>>'

[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[1] Listing certificates from LocalMachine\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[8] Filtered certificates: no certificates
[9] Excluded certificates: no certificates
[16] No valid certificates found.
[17] Generating HTTPS development certificate.
[19] An error has occurred generating the certificate: Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.CreateSelfSignedCertificate(X500DistinguishedName subject, IEnumerable`1 extensions, DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.CreateAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.EnsureAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter, String path, Boolean trust, Boolean includePrivateKey, String password, CertificateKeyExportFormat keyExportFormat, Boolean isInteractive).
There was an error creating the HTTPS developer certificate.
```

**Comment by dluc** [comment]
Out of curiosity I changed the URL changing the protocol from `https` to `http` and everything worked, I could sign in.

`https://127.0.0.1:51006/signin?nonce=....` => `http://127.0.0.1:51006/signin?nonce=....`

**Comment by TylerLeonhardt** [comment]
This is odd to me. If this is the flow provided by VS Code, then `http` would be used (because it's just a loopback server).

Either:
* This is using a custom auth flow
* Something about your browser is forcing https

Is this the `Sign in to Azure` you're talking about?
![Image](https://github.com/user-attachments/assets/37595b5c-d09e-44fe-a669-792531c9d6a6)

When you click it, does it show you this? ![Image](https://github.com/user-attachments/assets/7d0a2be5-8a83-48fe-880c-e8820926155b)

**Comment by dluc** [comment]
you're right, looks like there's something in my system forcing all requests to HTTPS. Thanks!
