### ISSUE TITLE
VSCode Server install of extensions

### ISSUE THREAD

**Issue by nicoostendorf** [microsoft/vscode#231028]
First reported here: https://github.com/microsoft/vscode-python/discussions/24285

They told me to report it here...

### Behaviour
The vscode-python  extension and vscode-jupyter extension is installed on my local machine and is doing fine. After connecting to the server i choose: _Install in SSH: <server>.com_

I am receiving the error: _Can't install 'ms-python.python' extension because it is not compatible with the current version of Visual Studio Code (version 1.93.1)._

### Informations
It worked for the last week and yesterday i got the problem the first time. I did no update or anything else.. So the Extension was for some reason not at the server anymore..

I tried different versions of VSCode: 1.94, 1.93, 1.91, 1.89. And different Versions of vscode-python: v2024.14.1, v2024.12.1, v2024.0.0. Locally all versions are working fine, at the server i am not able to install. 

I install the extension via the marketplace. 

All extension except vscode-python and vscode-jupyter are doing fine.

### Error
```
[error] Can't install 'ms-python.python' extension because it is not compatible with the current version of Visual Studio Code (version 1.93.1).: Incompatible: Can't install 'ms-python.python' extension because it is not compatible with the current version of Visual Studio Code (version 1.93.1).
    at U.N (/home/<user>/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/server/node/server.main.js:180:35468)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/<user>/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/server/node/server.main.js:180:24098
    at async Promise.allSettled (index 0)
    at async U.installGalleryExtensions (/home/<user>/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/server/node/server.main.js:180:24022)
    at async U.installFromGallery (/home/<user>/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/server/node/server.main.js:180:23563)
```

### Question

How could i get the extension running at the server? 

Is there another way to install it via bash on the server? 

Do you guys need other informations?

- VS Code Version: 1.94, 1.93, 1.90, ...
- OS Version: Windows 11

Steps to Reproduce:

1. Install vscode-python 
2. Start connection to server
3. try to install vscode-python also on server

**Comment by sandy081** [comment]
Can you please share following log while you reproduce the issue

- F1 > Open View... > Window
- F1 > Open View... > Server

What is the version of the extension you have installed locally?

**Comment by nicoostendorf** [comment]
**_Window:_**

```
024-10-10 19:05:18.088 [error] Can't install 'ms-python.python' extension because it is not compatible with the current version of Visual Studio Code (version 1.94.2).: Incompatible: Can't install 'ms-python.python' extension because it is not compatible with the current version of Visual Studio Code (version 1.94.2).
    at Vc.O (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:17212)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:6095
    at async Promise.allSettled (index 0)
    at async Vc.installGalleryExtensions (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:6019)
    at async Vc.installFromGallery (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:5639)
```

**_Server:_**

``` 
nothing
```

Server shows nothing, while trying to install extension. But while startup:

```
[error] CodeExpectedError: Could not find pty 1 on pty host
    at M.U (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:11102)
    at M.updateTitle (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:6412)
    at s.<computed> (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:1843)
    at Object.call (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4127)
    at Fc.s (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78860)
    at Fc.q (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78383)
    at os.value (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77785)
    at y.B (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:732)
    at y.fire (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:950)
    at process.v (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29096)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```


**_Extension Versions:_**

_Jupyter_: v2024.9.1

_Python_: v2024.16.1

**Comment by JihedC** [comment]
Hi I got the same issue, I just reverted back to the version of August and it now works:

https://code.visualstudio.com/updates/v1_93

**Comment by nicoostendorf** [comment]
@JihedC  I tried it already with older versions of VSCode.. Also with 1.93.1 i am not able to install extensions via VSCode-server version..

**Comment by sandy081** [comment]
@nicoostendorf Can you please share the complete window and shared log?

**Comment by nicoostendorf** [comment]
@sandy081 

_**Window**_

```
2024-10-11 14:48:16.590 [info] Started local extension host with pid 19108.
2024-10-11 14:48:19.374 [info] [perf] Render performance baseline is 49ms
2024-10-11 14:48:22.509 [error] [Extension Host] (node:19108) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `Code --trace-warnings ...` to show where the warning was created)
2024-10-11 14:48:30.850 [info] Started local extension host with pid 27128.
2024-10-11 14:48:32.853 [info] Invoking resolveAuthority(ssh-remote)...
2024-10-11 14:48:32.853 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2024-10-11 14:48:32.853 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
2024-10-11 14:48:33.868 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1015ms] waiting...
2024-10-11 14:48:34.757 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1904ms] returned Managed(1)
2024-10-11 14:48:34.758 [info] resolveAuthority(ssh-remote) returned 'Managed(1)' after 1904 ms
2024-10-11 14:48:34.758 [info] Creating a socket (renderer-Management-3891e9ee-03db-42d1-9406-543191c7cf49)...
2024-10-11 14:48:34.758 [info] Creating a socket (renderer-ExtensionHost-44e7dc4d-2ae0-4e31-82a7-5dcad43a448b)...
2024-10-11 14:48:34.866 [info] Creating a socket (renderer-ExtensionHost-44e7dc4d-2ae0-4e31-82a7-5dcad43a448b) was successful after 108 ms.
2024-10-11 14:48:34.867 [info] Creating a socket (renderer-Management-3891e9ee-03db-42d1-9406-543191c7cf49) was successful after 109 ms.
2024-10-11 14:48:36.366 [error] Could not find pty 6 on pty host: CodeExpectedError: Could not find pty 6 on pty host
    at M.U (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:11102)
    at M.updateTitle (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:6412)
    at s.<computed> (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:1843)
    at Object.call (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4127)
    at Fc.s (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78860)
    at Fc.q (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78383)
    at os.value (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77785)
    at y.B (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:732)
    at y.fire (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:950)
    at process.v (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29096)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-10-11 14:48:36.631 [info] [perf] Render performance baseline is 49ms
2024-10-11 14:48:39.689 [error] [Extension Host] (node:1444670) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
2024-10-11 14:48:41.603 [error] [Extension Host] [default] Error sending telemetry FetchError: Unspecified GSS failure.  Minor code may provide more information: No Kerberos credentials available (default cache: /tmp/krb5cc_111048)
    at fetch (/home/<user>/.vscode-server/extensions/github.copilot-1.238.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at cachingFetch (/home/<user>/.vscode-server/extensions/github.copilot-1.238.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at Aae.fetch (/home/<user>/.vscode-server/extensions/github.copilot-1.238.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: undefined,
  errno: undefined,
  erroredSysCall: undefined
}
2024-10-11 14:48:54.903 [error] Can't install 'ms-python.python' extension because it is not compatible with the current version of Visual Studio Code (version 1.94.2).: Incompatible: Can't install 'ms-python.python' extension because it is not compatible with the current version of Visual Studio Code (version 1.94.2).
    at Vc.O (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:17212)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:6095
    at async Promise.allSettled (index 0)
    at async Vc.installGalleryExtensions (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:6019)
    at async Vc.installFromGallery (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:50:5639)
2024-10-11 14:48:56.603 [error] [Extension Host] [default] Error sending telemetry FetchError: Unspecified GSS failure.  Minor code may provide more information: No Kerberos credentials available (default cache: /tmp/krb5cc_111048)
    at fetch (/home/<user>/.vscode-server/extensions/github.copilot-1.238.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at cachingFetch (/home/<user>/.vscode-server/extensions/github.copilot-1.238.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at Aae.fetch (/home/<user>/.vscode-server/extensions/github.copilot-1.238.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: undefined,
  errno: undefined,
  erroredSysCall: undefined
}
```

_**Server**_

```
2024-10-11 10:56:59.525 [info] 




2024-10-11 10:56:59.533 [info] Extension host agent started.
2024-10-11 10:56:59.621 [info] Deleted uninstalled extension from disk ms-toolsai.vscode-jupyter-slideshow /home/<user>/.vscode-server/extensions/ms-toolsai.vscode-jupyter-slideshow-0.1.6
2024-10-11 10:56:59.657 [info] [<unknown>][b0ddcc6c][ManagementConnection] New connection established.
2024-10-11 10:56:59.658 [info] [<unknown>][3a2730bd][ExtensionHostConnection] New connection established.
2024-10-11 10:57:00.010 [info] [<unknown>][3a2730bd][ExtensionHostConnection] <1132214> Launched Extension Host Process.
2024-10-11 10:57:01.066 [info] Deleted uninstalled extension from disk ms-python.debugpy /home/<user>/.vscode-server/extensions/ms-python.debugpy-2024.11.2024092501
2024-10-11 10:57:01.069 [info] Deleted uninstalled extension from disk ms-python.vscode-pylance /home/<user>/.vscode-server/extensions/ms-python.vscode-pylance-2024.10.1
2024-10-11 10:57:04.130 [info] [<unknown>][b0ddcc6c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2024-10-11 10:57:04.208 [info] [<unknown>][3a2730bd][ExtensionHostConnection] <1132214> Extension Host Process exited with code: 0, signal: null.
2024-10-11 10:57:04.208 [info] Cancelling previous shutdown timeout
2024-10-11 10:57:04.208 [info] Last EH closed, waiting before shutting down
2024-10-11 10:57:06.923 [info] [<unknown>][61db464c][ExtensionHostConnection] New connection established.
2024-10-11 10:57:06.923 [info] [<unknown>][9c73ce0f][ManagementConnection] New connection established.
2024-10-11 10:57:06.927 [info] [<unknown>][61db464c][ExtensionHostConnection] <1132614> Launched Extension Host Process.
2024-10-11 11:02:04.209 [info] New EH opened, aborting shutdown
2024-10-11 11:02:04.211 [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/server/node/server.main.js:189:5899)
    at process.emit (node:events:531:35)
2024-10-11 12:20:47.406 [info] [<unknown>][9c73ce0f][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2024-10-11 12:20:47.590 [info] [<unknown>][61db464c][ExtensionHostConnection] <1132614> Extension Host Process exited with code: 0, signal: null.
2024-10-11 12:20:47.590 [info] Last EH closed, waiting before shutting down
2024-10-11 12:20:51.536 [info] [<unknown>][6a45f0dd][ExtensionHostConnection] New connection established.
2024-10-11 12:20:51.537 [info] [<unknown>][d0726627][ManagementConnection] New connection established.
2024-10-11 12:20:51.543 [info] [<unknown>][6a45f0dd][ExtensionHostConnection] <1266022> Launched Extension Host Process.
2024-10-11 12:20:53.748 [error] CodeExpectedError: Could not find pty 3 on pty host
    at M.U (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:11102)
    at M.updateTitle (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:6412)
    at s.<computed> (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:1843)
    at Object.call (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4127)
    at Fc.s (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78860)
    at Fc.q (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78383)
    at os.value (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77785)
    at y.B (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:732)
    at y.fire (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:950)
    at process.v (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29096)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-10-11 12:20:59.431 [info] [<unknown>][d0726627][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2024-10-11 12:20:59.481 [info] [<unknown>][6a45f0dd][ExtensionHostConnection] <1266022> Extension Host Process exited with code: 0, signal: null.
2024-10-11 12:20:59.481 [info] Cancelling previous shutdown timeout
2024-10-11 12:20:59.481 [info] Last EH closed, waiting before shutting down
2024-10-11 12:21:04.110 [info] [<unknown>][75d1c6f0][ExtensionHostConnection] New connection established.
2024-10-11 12:21:04.111 [info] [<unknown>][9bcec7ff][ManagementConnection] New connection established.
2024-10-11 12:21:04.115 [info] [<unknown>][75d1c6f0][ExtensionHostConnection] <1266475> Launched Extension Host Process.
2024-10-11 12:25:59.482 [info] New EH opened, aborting shutdown
2024-10-11 14:45:56.187 [info] [<unknown>][1f0a4820][ManagementConnection] New connection established.
2024-10-11 14:45:56.190 [info] [<unknown>][ef3125f2][ExtensionHostConnection] New connection established.
2024-10-11 14:45:56.199 [info] [<unknown>][ef3125f2][ExtensionHostConnection] <1442437> Launched Extension Host Process.
2024-10-11 14:46:44.232 [info] [<unknown>][1f0a4820][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2024-10-11 14:46:44.292 [info] [<unknown>][ef3125f2][ExtensionHostConnection] <1442437> Extension Host Process exited with code: 0, signal: null.
2024-10-11 14:48:35.149 [info] [<unknown>][3891e9ee][ManagementConnection] New connection established.
2024-10-11 14:48:35.151 [info] [<unknown>][44e7dc4d][ExtensionHostConnection] New connection established.
2024-10-11 14:48:35.155 [info] [<unknown>][44e7dc4d][ExtensionHostConnection] <1444670> Launched Extension Host Process.
2024-10-11 14:48:37.444 [error] CodeExpectedError: Could not find pty 6 on pty host
    at M.U (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:11102)
    at M.updateTitle (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:6412)
    at s.<computed> (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:48:1843)
    at Object.call (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:31:4127)
    at Fc.s (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78860)
    at Fc.q (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:78383)
    at os.value (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:77785)
    at y.B (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:732)
    at y.fire (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:29:950)
    at process.v (file:///home/<user>/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29096)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by rlangefe** [comment]
I'm having a similar issue. Extensions work locally but say they are not compatible on a remote machine.

Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by sandy081** [comment]
@nicoostendorf I do not see any traces of extension getting installed in the server log. Can you please enable log level to trace and share the logs again - `F1 > Developer: Set Log Level... > Trace`.

Can you also please share a recording of the issue?
