### ISSUE TITLE
Debug Console misses debug adapter outputs on session startup

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode#231074]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.94.1
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-45-generic

Steps to Reproduce:
1. Clone [this branch](https://github.com/vadimcn/vscode-mock-debug/tree/debug-console) of vscode-mock-debug
2. Build, run.
3. Set focus to the Terminal and start debugging.  Note that all of the `line 1`-`line 4` messages are displayed in the Console tab.
5. Stop debugging
6. Set focus to the Debug Console and start debugging again.  Observe that now only the `line 4` message appears.

The problem seems to be triggered by the Terminal tab taking focus from Debug Console around the time when lines 1-3 are output.

 https://github.com/user-attachments/assets/ff9ff44c-6b9c-4f43-a149-b0444703cdb1

Additionally, I've noticed the following message in VSCode's Developer Tools console around the time when this happens:
```
listView.ts:1522 Measuring item node that is not in DOM! Add ListView to the DOM before measuring row height! Error
    at ooi.xb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265:26606)
    at ooi.wb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265:25507)
    at ooi.U (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265:14459)
    at ooi.splice (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:265:12904)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:263:45177
    at Array.forEach (<anonymous>)
    at nIi.splice (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:263:45164)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:308:7637
    at B9.bufferEvents (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:3811)
    at hAi.splice (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:308:7613)
    at hAi.splice (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:404:72015)
    at NQ.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:405:3929)
    at x.B (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:733)
    at x.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:951)
    at URi.t (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:404:36273)
    at URi.s (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:404:34684)
    at URi.splice (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:404:34533)
    at Lie.l (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:405:6233)
    at Lie.setChildren (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:405:5785)
    at lf.L (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:405:37188)
    at lf.E (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:405:34364)
    at async lf.C (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:405:31271)
    at async lf.updateChildren (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:405:31025)
    at async si.a (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2029:2971)
```

**Comment by vadimcn** [comment]
Perhaps I should explain why I consider this issue important: it tends to eat up debugger diagnostic messages during the debuggee launch, which are important for informing the user about problems with the debug info or source path mappings.

**Comment by eleanorjboyd** [comment]
Hi @vadimcn! Are you able to verify if the fix for this works? It has been fixed and is out on vscode insiders so if you are able to try it there and let us know if it solved the bug, that would be extremely helpful! Thanks
