### ISSUE TITLE
remote connection error: Unavailable (FileSystemError): ENOPRO: resource not found "

### ISSUE THREAD

**Issue by wangzhankun** [microsoft/vscode#231166]
Does this issue occur when all extensions are disabled?: Yes (only with ssh extension)

- VS Code Version: 1.94.2
- OS Version: macos 14.6.1 Apple m3
- remote OS: debian 12
- ssh authored by Kerberos

Steps to Reproduce:

1. connect to remote server
2. try to open remote folder, and then vscode report bug:
![Image](https://github.com/user-attachments/assets/a0b8d2d3-b378-46a3-8320-a0eafed4f8ef)

```log
[670 ms] userEnvProbe: loginInteractiveShell (default)
[670 ms] userEnvProbe: not found in cache
[670 ms] userEnvProbe shell: /usr/bin/zsh
[684 ms] Error reading shell environment.
[684 ms] Error: Connection closed
        at Socket.<anonymous> (/Users/xxxxxxx/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:293877)
        at Object.onceWrapper (node:events:634:26)
        at Socket.emit (node:events:531:35)
        at TCP.<anonymous> (node:net:339:12)
```
```log
ERR ENOPRO: 未找到资源 "vscode-remote://ssh-remote%2B10.xx.xx.xxx/home/xxxxxx/documents/rodan" 的文件系统提供程序: CodeExpectedError: ENOPRO: 未找到资源 "vscode-remote://ssh-remote%2B10.xx.xx.xxx/home/xxxxx/documents/rodan" 的文件系统提供程序
    at Git.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3072:64896)
    at async Git.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3072:66919)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3108:7727
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1942:14511
```
[more log.txt](https://github.com/user-attachments/files/17348629/more.log.txt)

**Comment by medikoo** [comment]
I have exact same issue. It started to happen recently, it's hard to work with any remote host

**Comment by wangzhankun** [comment]
downgrade the vscode will solve the issue, for example version 1.83.1

**Comment by joshspicer** [comment]
Could you let us know if this still reproduces?

If this is a possible VS Code regression, it would help to know which change caused it. We maintain a node.js based CLI tool [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. 

_If it's a VS Code regression it will take at most 8 steps to find exactly the commit that caused the regression._

#### Steps
- Install [node.js](https://nodejs.org/en/download) (if not yet done)
- Run `npx --yes @vscode/vscode-bisect@latest`
- Follow the instructions until you found the offending build (its fine to leave the commit empty)
- Report back the commit range in this issue

**Comment by medikoo** [comment]
@joshspicer I don't see it anymore, so I believe it got fixed

**Comment by joshspicer** [comment]
Thank you for confirming @medikoo
