### ISSUE TITLE
Debug adapter process has terminated unexpectedly when running JS Debug Terminal inside a Devcontainer

### ISSUE THREAD

**Issue by mathiasmaerker** [microsoft/vscode#231106]
Does this issue occur when all extensions are disabled?: Yes

it is a barebondes devcontainer 
```json
{
	"name": "Node.js & TypeScript",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/typescript-node:0-20",
}
```

```bash
log.ts:419  INFO Started local extension host with pid 28696.
log.ts:419  INFO Invoking resolveAuthority(dev-container)...
log.ts:419  INFO [LocalProcess0][resolveAuthority(dev-container,1)][0ms] obtaining proxy...
log.ts:419  INFO [LocalProcess0][resolveAuthority(dev-container,1)][0ms] invoking...
log.ts:419  INFO [LocalProcess0][resolveAuthority(dev-container,1)][1010ms] waiting...
log.ts:419  INFO [LocalProcess0][resolveAuthority(dev-container,1)][2010ms] waiting...
log.ts:419  INFO [LocalProcess0][resolveAuthority(dev-container,1)][3001ms] waiting...
log.ts:419  INFO [LocalProcess0][resolveAuthority(dev-container,1)][4001ms] waiting...
log.ts:419  INFO [LocalProcess0][resolveAuthority(dev-container,1)][4264ms] returned WebSocket(127.0.0.1:43723)
log.ts:419  INFO resolveAuthority(dev-container) returned 'WebSocket(127.0.0.1:43723)' after 4264 ms
log.ts:419  INFO Creating a socket (renderer-Management-a6755b87-a633-4a96-9cb2-74a2cf45ad2e)...
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-82a34faa-f759-47c6-9950-2dfaa59f743d)...
log.ts:419  INFO Creating a socket (renderer-Management-a6755b87-a633-4a96-9cb2-74a2cf45ad2e) was successful after 121 ms.
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-82a34faa-f759-47c6-9950-2dfaa59f743d) was successful after 222 ms.
log.ts:439   ERR [Extension Host] Shell server terminated (code: 137, signal: null)


console.ts:137 [Extension Host] Shell server terminated (code: 137, signal: null)


K_i @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
log.ts:419  INFO [perf] Render performance baseline is 19ms
log.ts:439   ERR [Extension Host] Shell server terminated (code: 137, signal: null)


console.ts:137 [Extension Host] Shell server terminated (code: 137, signal: null)


K_i @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
log.ts:419  INFO [remote-connection][ExtensionHost][82a34…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
log.ts:439   ERR CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}
log.ts:419  INFO [remote-connection][ExtensionHost][82a34…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:419  INFO [remote-connection][ExtensionHost][82a34…][reconnect] resolving connection...
log.ts:419  INFO [remote-connection][ExtensionHost][82a34…][reconnect] connecting to WebSocket(127.0.0.1:43723)...
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-82a34faa-f759-47c6-9950-2dfaa59f743d)...
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-82a34faa-f759-47c6-9950-2dfaa59f743d) was successful after 245 ms.
log.ts:439   ERR [remote-connection][ExtensionHost][82a34…][reconnect][WebSocket(127.0.0.1:43723)] received error control message when negotiating connection. Error:
log.ts:439   ERR Error: Connection error: Unknown reconnection token (seen before)
    at zei (remoteAgentConnection.ts:783:17)
    at NQ.value (remoteAgentConnection.ts:326:17)
    at x.B (event.ts:1242:13)
    at x.fire (event.ts:1273:9)
    at r6.fire (ipc.net.ts:652:19)
    at OUi.A (ipc.net.ts:1028:28)
    at NQ.value (ipc.net.ts:962:72)
    at x.B (event.ts:1242:13)
    at x.fire (event.ts:1273:9)
    at GFe.acceptChunk (ipc.net.ts:394:21)
    at ipc.net.ts:350:51
    at NQ.value (browserSocketFactory.ts:231:39)
    at x.B (event.ts:1242:13)
    at x.fire (event.ts:1273:9)
    at FMs.j.onload (browserSocketFactory.ts:92:17)
log.ts:439   ERR [remote-connection][ExtensionHost][82a34…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
log.ts:439   ERR Error: Connection error: Unknown reconnection token (seen before)
    at zei (remoteAgentConnection.ts:783:17)
    at NQ.value (remoteAgentConnection.ts:326:17)
    at x.B (event.ts:1242:13)
    at x.fire (event.ts:1273:9)
    at r6.fire (ipc.net.ts:652:19)
    at OUi.A (ipc.net.ts:1028:28)
    at NQ.value (ipc.net.ts:962:72)
    at x.B (event.ts:1242:13)
    at x.fire (event.ts:1273:9)
    at GFe.acceptChunk (ipc.net.ts:394:21)
    at ipc.net.ts:350:51
    at NQ.value (browserSocketFactory.ts:231:39)
    at x.B (event.ts:1242:13)
    at x.fire (event.ts:1273:9)
    at FMs.j.onload (browserSocketFactory.ts:92:17)
abstractExtensionService.ts:806 Extension host (Remote) terminated unexpectedly. Code: 0, Signal: 82a34faa-f759-47c6-9950-2dfaa59f743d
xb @ abstractExtensionService.ts:806
xb @ nativeExtensionService.ts:159
wb @ abstractExtensionService.ts:798
(anonymous) @ abstractExtensionService.ts:771
B @ event.ts:1242
fire @ event.ts:1273
F @ remoteExtensionHost.ts:201
(anonymous) @ remoteExtensionHost.ts:135
B @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
acceptDisconnect @ ipc.net.ts:986
cZe @ remoteAgentConnection.ts:772
D @ remoteAgentConnection.ts:727
C @ remoteAgentConnection.ts:721
z @ remoteAgentConnection.ts:675
await in z (async)
y @ remoteAgentConnection.ts:626
(anonymous) @ remoteAgentConnection.ts:593
B @ event.ts:1242
C @ event.ts:1253
fire @ event.ts:1277
fire @ ipc.net.ts:652
(anonymous) @ ipc.net.ts:880
e @ browserSocketFactory.ts:237
B @ event.ts:1242
fire @ event.ts:1273
(anonymous) @ browserSocketFactory.ts:175
log.ts:439   ERR Extension host (Remote) terminated unexpectedly with code null.
log.ts:439   ERR Extension host (Remote) terminated unexpectedly. The following extensions were running: vscode.emmet, vscode.typescript-language-features, vscode.git-base, vscode.npm, vscode.git, vscode.github, vscode.configuration-editing, vscode.json-language-features, vscode.debug-auto-launch, vscode.merge-conflict, ms-vscode.js-debug, vscode.debug-server-ready
log.ts:419  INFO Automatically restarting the remote extension host.
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-00c4427c-56de-42d8-ad2b-c80e8b5ce319)...
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-00c4427c-56de-42d8-ad2b-c80e8b5ce319) was successful after 95 ms.
notificationsAlerts.ts:42 Debug adapter process has terminated unexpectedly (Extension host shut down)
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
B @ event.ts:1242
C @ event.ts:1253
fire @ event.ts:1277
addNotification @ notifications.ts:228
error @ notificationService.ts:208
(anonymous) @ debugService.ts:699
B @ event.ts:1242
C @ event.ts:1253
fire @ event.ts:1277
hb @ debugSession.ts:1456
(anonymous) @ debugSession.ts:1320
B @ event.ts:1242
fire @ event.ts:1273
M @ rawDebugSession.ts:643
L @ rawDebugSession.ts:628
await in L (async)
K @ rawDebugSession.ts:611
await in K (async)
(anonymous) @ rawDebugSession.ts:97
B @ event.ts:1242
fire @ event.ts:1273
fireError @ mainThreadDebugService.ts:499
(anonymous) @ mainThreadDebugService.ts:84
(anonymous) @ lifecycle.ts:350
(anonymous) @ functional.ts:27
De @ lifecycle.ts:303
clear @ lifecycle.ts:405
dispose @ lifecycle.ts:386
dispose @ mainThreadDebugService.ts:184
dispose @ extensionHostManager.ts:175
stopOne @ abstractExtensionService.ts:1231
await in stopOne (async)
xb @ abstractExtensionService.ts:813
xb @ nativeExtensionService.ts:159
wb @ abstractExtensionService.ts:798
(anonymous) @ abstractExtensionService.ts:771
B @ event.ts:1242
fire @ event.ts:1273
F @ remoteExtensionHost.ts:201
(anonymous) @ remoteExtensionHost.ts:135
B @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
acceptDisconnect @ ipc.net.ts:986
cZe @ remoteAgentConnection.ts:772
D @ remoteAgentConnection.ts:727
C @ remoteAgentConnection.ts:721
z @ remoteAgentConnection.ts:675
await in z (async)
y @ remoteAgentConnection.ts:626
(anonymous) @ remoteAgentConnection.ts:593
B @ event.ts:1242
C @ event.ts:1253
fire @ event.ts:1277
fire @ ipc.net.ts:652
(anonymous) @ ipc.net.ts:880
e @ browserSocketFactory.ts:237
B @ event.ts:1242
fire @ event.ts:1273
(anonymous) @ browserSocketFactory.ts:175
log.ts:439   ERR No registered selector for ID: ms-vscode.npm-command

```
- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by connor4312** [comment]
This is a result of the remote EH crashing or being killed

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
