### ISSUE TITLE
Terminal doesn't send onExit event if terminal is not visible

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23119]
- VSCode Version: master
- OS: Windows (not sure if this happens on other OSes)

Steps:
- tasks.json file
```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["-p", "."],
	"showOutput": "silent",
	"echoCommand": true,
	"problemMatcher": "$tsc"
}
```
- have tsc installed globally
- tsconfig.json file
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true
    }
}
```
- HelloWorld.ts
```ts
class Startup {
    public static main(): number {
        console.log('Hello World');
        return 0;
    }
}

Startup.main();
```
- close bottom panel so that the terminal is not visible
- reload the window
- run the task by pressing Ctrl+Shift+B

Observe: the task spinner goes forever

- open the terminal

Observe: the task is terminated. But you can't press a key to close it. Even killing it will not send an exit event.
- reload Window
- bring terminal to front
- Ctrl+Shift+B

Observe: everything works as expected.

**Comment by dbaeumer** [comment]
Debugging it reveals the following exception:
```
[4028:0323/221311:INFO:CONSOLE(39)] "TypeError: Cannot read property 'addEventListener' of undefined
    at new DomListener (file:///P:/mseng/VSCode/vscode/out/vs/base/browser/dom.js:163:23)
    at Object.addDisposableListener (file:///P:/mseng/VSCode/vscode/out/vs/base/browser/dom.js:178:16)
    at TerminalInstance._onPtyProcessExit (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:461:51)
    at ChildProcess.<anonymous> (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:422:73)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)", source: file:///P:/mseng/VSCode/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (39)
```

**Comment by dbaeumer** [comment]
Exception doesn't happen if terminal is visible.

**Comment by Tyriar** [comment]
Thanks for the investigation!

**Comment by michelkaporin** [comment]
The task spinner does not go forever anymore, fixed. ✅ 

Although once task is terminated I can't press a key to close it in the terminal.

**Comment by Tyriar** [comment]
@michelkaporin nice find! Added https://github.com/Microsoft/vscode/issues/23692 for next month since it's low impact.
