### ISSUE TITLE
Can'r register link handler if terminal is not visible

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23148]
- VSCode Version: master

You get:

```
[21176:0324/110430:INFO:CONSOLE(261)] "Cannot read property 'registerCustomLinkHandler' of undefined: TypeError: Cannot read property 'registerCustomLinkHandler' of undefined
    at TerminalInstance.registerLinkMatcher (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:263:37)
    at handlePattern (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:530:42)
    at TerminalTaskSystem.registerLinkMatchers (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:549:21)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:227:52
    at new Promise_ctor (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1641:17)
    at TerminalTaskSystem.executeCommand (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:221:27)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:146:34
    at Promise_ctor.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at TerminalTaskSystem.executeTask (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:139:61)
    at TerminalTaskSystem.run (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:87:97)", source: file:///P:/mseng/VSCode/vscode/out/vs/work
bench/electron-browser/shell.js (261)
```

**Comment by Tyriar** [comment]
https://github.com/sourcelair/xterm.js/issues/618
