### ISSUE TITLE
Error: Illegal state: service accessor is only valid during the invocation of its target method

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#232028]
```
notificationsAlerts.js:31 Error: Illegal state: service accessor is only valid during the invocation of its target method
    at illegalState (errors.js:155:16)
    at Object.get (instantiationService.js:75:31)
    at NewEditSessionAction.run (chatClearActions.js:188:47)
    at async ActionRunner.runAction (actions.js:112:9)
    at async ActionRunner.run (actions.js:104:13)
    at async MenuEntryActionViewItem.onClick (menuEntryActionViewItem.js:157:13)
onDidChangeNotification @ notificationsAlerts.js:31
(anonymous) @ notificationsAlerts.js:22
_deliver @ event.js:966
_deliverQueue @ event.js:977
fire @ event.js:1000
addNotification @ notifications.js:123
error @ notificationService.js:170
(anonymous) @ compositePart.js:181
_deliver @ event.js:966
_deliverQueue @ event.js:977
fire @ event.js:1000
run @ actions.js:109
await in run
onClick @ menuEntryActionViewItem.js:157
(anonymous) @ actionViewItems.js:106
```

**Comment by joyceerhl** [comment]
Verification: run New Edit Session from the command palette and make sure you don't get the error above
