### ISSUE TITLE
MacOS - extfs external drive - python create environment failed

### ISSUE THREAD

**Issue by J-Siu** [microsoft/vscode#232174]
Type: <b>Bug</b>

Hardware:
- MacOS computer
- external/usb drive formated with EXTFS

Software:
- Miniconda install via homebrew

Steps:
1. Create directory "py_tmp" in above external drive
2. Open "py_tmp" in VSCode
3. In command palette -> "Python: Create Environment" -> "Conda" -> "Pythong 3.11"
4. Wait for error

PS: This does not happen on APFS formeted external drive.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 3|
|Memory (System)|24.00GB (0.93GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
godot-files|alf|0.1.0
spellright|ban|3.0.136
markdown-emoji|bie|0.3.0
shell-syntax|bma|1.0.5
vscode-opennewinstance|chr|0.0.15
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.56.0
githistory|don|0.6.20
xml|Dot|2.5.1
prettier-vscode|esb|11.0.0
shell-format|fox|7.2.5
godot-tools|gee|2.3.0
go|gol|0.42.1
todo-tree|Gru|0.0.226
auto-markdown-toc|hun|3.0.13
vscode-edit-csv|jan|0.10.0
pubspec-assist|jer|2.3.2
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
remote-containers|ms-|0.389.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
remove-comments|pli|1.2.2
vscode-yaml|red|1.15.0
vscode-sort-json|ric|1.20.0
datetime|rid|2.2.2
trailing-spaces|sha|0.4.1
code-spell-checker|str|3.0.1
lua|sum|3.11.1
even-better-toml|tam|0.19.2
sort-lines|Tyr|1.11.0

(1 theme extensions excluded)

</details>

**Comment by J-Siu** [comment]
Python output:
```
2024-10-24 13:09:57.583 [info] Telemetry level is off
2024-10-24 13:09:57.583 [info] Experiments are disabled, only manually opted experiments are active.
2024-10-24 13:09:57.583 [warning] Dir "/Volumes/T7B01/tmp/py_tmp/.pixi/envs" is not watchable (directory does not exist)
2024-10-24 13:09:57.583 [info] Default formatter is set to null for workspace /Volumes/T7B01/tmp/py_tmp
2024-10-24 13:09:57.583 [info] Starting Environment refresh
2024-10-24 13:09:57.583 [info] > pixi --version
2024-10-24 13:09:57.583 [info] > hatch env show --json
2024-10-24 13:09:57.583 [info] cwd: .
2024-10-24 13:09:57.583 [info] Python interpreter path: /opt/homebrew/bin/python3
2024-10-24 13:09:57.583 [info] Starting Environment refresh
2024-10-24 13:09:57.588 [info] > /opt/homebrew/bin/python3 -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:09:57.588 [info] Environments refresh paths discovered: 20 milliseconds
2024-10-24 13:09:57.588 [info] Environments refresh paths discovered: 5 milliseconds
2024-10-24 13:09:57.668 [info] Environments refresh finished (event): 100 milliseconds
2024-10-24 13:09:57.669 [info] Environments refresh finished (event): 85 milliseconds
2024-10-24 13:09:57.670 [info] Environment refresh took 102 milliseconds
2024-10-24 13:09:57.670 [info] Environment refresh took 87 milliseconds
2024-10-24 13:09:57.672 [info] > pyenv which python
2024-10-24 13:09:57.672 [info] cwd: .
2024-10-24 13:09:58.611 [info] > conda info --json
2024-10-24 13:09:58.658 [info] Starting Pylance language server.
2024-10-24 13:09:58.996 [info] Selected workspace /Volumes/T7B01/tmp/py_tmp for creating conda environment.
2024-10-24 13:10:01.134 [info] Selected Python version 3.11 for creating conda environment.
2024-10-24 13:10:01.139 [info] Running Conda Env creation script:  [
  '/opt/homebrew/Caskroom/miniconda/base/bin/python',
  '/Users/js/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/create_conda.py',
  '--git-ignore',
  '--install',
  '--python',
  '3.11'
]
2024-10-24 13:10:01.139 [info] > /opt/homebrew/Caskroom/miniconda/base/bin/python ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/create_conda.py --git-ignore --install --python 3.11
2024-10-24 13:10:01.139 [info] cwd: .
2024-10-24 13:10:01.187 [info] Running: /opt/homebrew/Caskroom/miniconda/base/bin/python -m conda create --yes --prefix .conda python=3.11
2024-10-24 13:10:01.505 [info] Channels:
- conda-forge
- defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): ...working...
2024-10-24 13:10:02.074 [info] done
2024-10-24 13:10:02.074 [info] Solving environment: ...working...
2024-10-24 13:10:02.160 [info] done
2024-10-24 13:10:02.181 [info] ## Package Plan ##
environment location: /Volumes/T7B01/tmp/py_tmp/.conda
added / updated specs:
- python=3.11
The following NEW packages will be INSTALLED:
bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h99b78c6_7
ca-certificates    conda-forge/osx-arm64::ca-certificates-2024.8.30-hf0a4a13_0
libexpat           conda-forge/osx-arm64::libexpat-2.6.3-hf9b8971_0
libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5
libsqlite          conda-forge/osx-arm64::libsqlite-3.47.0-hbaaea75_0
libzlib            conda-forge/osx-arm64::libzlib-1.3.1-h8359307_2
ncurses            conda-forge/osx-arm64::ncurses-6.5-h7bae524_1
openssl            conda-forge/osx-arm64::openssl-3.3.2-h8359307_0
pip                conda-forge/noarch::pip-24.2-pyh8b19718_1
python             conda-forge/osx-arm64::python-3.11.10-hc51fdd5_3_cpython
readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1
setuptools         conda-forge/noarch::setuptools-75.1.0-pyhd8ed1ab_0
tk                 conda-forge/osx-arm64::tk-8.6.13-h5083fa2_1
tzdata             conda-forge/noarch::tzdata-2024b-hc8b5060_0
wheel              conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0
xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0
Downloading and Extracting Packages: ...working...
2024-10-24 13:10:02.181 [info] done
Preparing transaction: ...working...
2024-10-24 13:10:02.372 [info] done
2024-10-24 13:10:02.372 [info] Verifying transaction: ...working...
2024-10-24 13:10:07.420 [info] done
2024-10-24 13:10:07.420 [info] Executing transaction: ...working...
2024-10-24 13:10:07.492 [info] Searching for conda environments
2024-10-24 13:10:07.501 [info] > /Volumes/T7W01/ai/AI-Web-Scraper/.conda/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:07.503 [info] > /opt/homebrew/Caskroom/miniconda/base/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:07.505 [info] Finished searching for conda environments: 13 milliseconds
2024-10-24 13:10:07.507 [info] Environments refresh paths discovered: 15 milliseconds
2024-10-24 13:10:07.533 [info] > /opt/homebrew/Caskroom/miniconda/base/envs/airllm/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:07.537 [info] > /opt/homebrew/Caskroom/miniconda/base/envs/extras/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:07.565 [info] > /opt/homebrew/Caskroom/miniconda/base/envs/txt-gen-webui/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:07.570 [info] > /opt/homebrew/Caskroom/miniconda/base/envs/xtts/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:07.602 [info] Environments refresh finished (event): 110 milliseconds
2024-10-24 13:10:15.009 [info] > ./.conda/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:15.009 [info] Environments refresh paths discovered: 6 milliseconds
2024-10-24 13:10:17.254 [info] > ./.conda/bin/python -I ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/interpreterInfo.py
2024-10-24 13:10:17.267 [info] Environments refresh finished (event): 2264 milliseconds
2024-10-24 13:10:19.785 [info] Discover tests for workspace name: py_tmp - uri: /Volumes/T7B01/tmp/py_tmp/.conda/lib/python3.11/site-packages/pkg_resources/tests/data/my-test-package-source/setup.cfg
2024-10-24 13:10:25.562 [info] done
2024-10-24 13:10:25.562 [info] Rolling back transaction: ...working...
2024-10-24 13:10:25.643 [info] Searching for conda environments
2024-10-24 13:10:25.660 [info] Finished searching for conda environments: 17 milliseconds
2024-10-24 13:10:25.661 [info] Environments refresh finished (event): 19 milliseconds
2024-10-24 13:10:25.661 [info] Environments refresh paths discovered: 19 milliseconds
2024-10-24 13:10:27.215 [info] Discover tests for workspace name: py_tmp - uri: /Volumes/T7B01/tmp/py_tmp/.conda/lib/python3.11/site-packages/pkg_resources/tests/data/my-test-package-source/setup.cfg
2024-10-24 13:10:29.469 [info] Environments refresh finished (event): 5 milliseconds
2024-10-24 13:10:29.469 [info] Environments refresh paths discovered: 5 milliseconds
2024-10-24 13:10:34.300 [info] done
2024-10-24 13:10:34.466 [info] CorruptedEnvironmentError: The target environment has been corrupted. Corrupted environments most commonly
occur when the conda process is force-terminated while in an unlink-link
transaction.
environment location: /Volumes/T7B01/tmp/py_tmp/.conda
corrupted file: /Volumes/T7B01/tmp/py_tmp/.conda/conda-meta/._bzip2-1.0.8-h99b78c6_7.json
()
2024-10-24 13:10:34.523 [info] Traceback (most recent call last):
File "/Users/js/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/create_conda.py", line 61, in run_process
2024-10-24 13:10:34.524 [info] subprocess.run(args, cwd=os.getcwd(), check=True)  # noqa: PTH109
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-24 13:10:34.524 [info] ^
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/subprocess.py", line 571, in run
2024-10-24 13:10:34.525 [info] raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError
2024-10-24 13:10:34.525 [info] : Command '['/opt/homebrew/Caskroom/miniconda/base/bin/python', '-m', 'conda', 'create', '--yes', '--prefix', '.conda', 'python=3.11']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/Users/js/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/create_conda.py", line 130, in <module>
main(sys.argv[1:])
2024-10-24 13:10:34.525 [info] File "/Users/js/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/create_conda.py", line 107, in main
run_process(
File "/Users/js/.vscode/extensions/ms-python.python-2024.16.1-darwin-arm64/python_files/create_conda.py", line 63, in run_process
2024-10-24 13:10:34.525 [info] raise VenvError(error_message) from exc
VenvError: CREATE_CONDA.ENV_FAILED_CREATION
2024-10-24 13:10:34.529 [error] Error while running venv creation script:  CREATE_CONDA.ENV_FAILED_CREATION
2024-10-24 13:10:34.530 [error] CREATE_CONDA.ENV_FAILED_CREATION
```

**Comment by karthiknadig** [comment]
@J-Siu This seems like a `conda` issue and not likey an issue with VS Code extension or VS Code. From the error it seems like `conda` detects some environment corruption. Try doing this from a external terminal and see if it is able to create it.

**Comment by J-Siu** [comment]
The extfs / "._" file issue seems to affect multiple apps I use. I am throwing in the towel and switching all my MacOS data drive to apfs🤦‍♂️
