### ISSUE TITLE
Quick chat does not explain to show code block

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#232275]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: `1.95.0-insider`
- OS Version: `macOS 23.6.0`

```
Version: 1.95.0-insider (Universal)
Commit: c0f27916ad81d8de78b62bd0aa0eab3f8cd99178
Date: 2024-10-25T09:02:38.980Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```

Copilot Chat: `v0.22.2024102502 (pre-release)`

~~Presumably related to https://github.com/microsoft/vscode/issues/232096 (which no longer repros)~~

Steps to Reproduce:

1. Ask a question in quick chat 
2. Have the quickchat produce code
3. 🐛  See code block is cut off and unable to be scrolled to

https://github.com/user-attachments/assets/caae0ace-0e34-4d85-a98a-e1d79e3cc4e8

When expanding this quick chat into a the side panel, the code block is visible:

![Image](https://github.com/user-attachments/assets/f65cb123-93c2-4313-8203-95b25d3d39cf)

**Comment by roblourens** [comment]
```
2024-10-25 09:52:57.099 [error] [createInstance] tu depends on UNKNOWN service editorProgressService.: Error: [createInstance] tu depends on UNKNOWN service editorProgressService.
    at tht.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1354:4061)
    at tht.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1354:1236)
    at tht.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1354:1083)
    at G2e.y (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:554:23515)
    at new G2e (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:554:21831)
    at tht.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1354:1586)
    at tht.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1354:1083)
    at tae.c (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:555:6827)
    at tae.get (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:537:23052)
    at eOe.get (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:555:6895)
```

Is this a service that isn't registered in the context that quick chat has?

Not a regression
