### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover. Again Again Again 

### ISSUE THREAD

**Issue by mehran-mousavi** [Microsoft/vscode#23239]
Version 1.11.0-insider
Commit e1d2e7b41c22acf9c3f63123842d5231bfbc2fae
Date 2017-03-24T09:14:58.926Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**And Log :** 

Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  typescriptHero.showCmdGui
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  typescriptHero.resolve.addImport
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  typescriptHero.resolve.addImportUnderCursor
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  typescriptHero.resolve.organizeImports
[Extension Host] vscode-icons is active!
Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at e.onResourceEncodingChange (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:124:23608)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:124:18257
    at e.invoke (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:7244)
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:10877)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:22316
    at e.invoke (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:7244)
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:10877)
    at t.loadWithContent (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:6687)
    at t.handleLoadSuccess (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:5724)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:119:5584
[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'document' of undefined
[Extension Host] TypeError: Cannot read property 'document' of undefined
    at buildStatusBar (C:\Users\mehran\.vscode-insiders\extensions\ianhoney.task-master-0.1.39\out\src\extension.js:140:30)
    at Timeout.doCmdsExist (C:\Users\mehran\.vscode-insiders\extensions\ianhoney.task-master-0.1.39\out\src\extension.js:44:13)
    at Timeout.wrapper (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
Extension host terminated unexpectedly. Please reload the window to recover.
Extension host terminated unexpectedly. Code:  7  Signal:  null

**Comment by mehran-mousavi** [comment]
I founded a solution. when i **disable vscode-icons extension**, my problem resolved !

**Comment by mehran-mousavi** [comment]
After last insider update, this error occurs again 

Version 1.11.0-insider
Commit a35c7da7b8f324c1e8cc7830173418e392542f6d
Date 2017-03-28T12:46:15.098Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Log :** 

[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'document' of undefined
[Extension Host] TypeError: Cannot read property 'document' of undefined
    at buildStatusBar (C:\Users\mehran\.vscode-insiders\extensions\ianhoney.task-master-0.1.39\out\src\extension.js:140:30)
    at Timeout.doCmdsExist (C:\Users\mehran\.vscode-insiders\extensions\ianhoney.task-master-0.1.39\out\src\extension.js:44:13)
    at Timeout.wrapper (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
Extension host terminated unexpectedly. Please reload the window to recover.
Extension host terminated unexpectedly. Code:  7  Signal:  null

Need more details ?

**Comment by joaomoreno** [comment]
Please file an issue on the ianhoney.task-master extension.

**Comment by vjoao** [comment]
I'm getting the same error. Reinstalled VS Code 1.11.1, no extensions at all. No errors on console apart from the `Extension host terminated unexpectedly. Please reload the window to recover.`.
Exit code is `3`. Signal is `null`.
Running on Windows 10

**Comment by Paddy-Hamilton** [comment]
Thanks @mehran-mousavi , sweet relief from this incredibly annoying bug.

**Comment by MehdiRaash** [comment]
Is there a solution for this Error message?
