### ISSUE TITLE
Walkthrough sometimes does not open / show up in list of walkthroughs

### ISSUE THREAD

**Issue by mhuisi** [microsoft/vscode#232425]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.94.2
- OS Version: Fedora Linux 40, 6.10.12-200.fc40.x86_64

In the [VS Code extension for the Lean 4 theorem prover](https://github.com/leanprover/vscode-lean4), first time users sometimes report that the walkthrough of our VS Code extension doesn't open automatically after installing the extension or that they can't find it in the list of walkthroughs in VS Code.

We also have a command that opens our walkthrough by executing the `openWalkthrough` command:
```
commands.executeCommand('workbench.action.openWalkthrough', 'leanprover.lean4#lean4.welcome', false)
```

Recently, I've encountered the issue of the walkthrough not appearing in the list of walkthroughs in VS Code myself, and when using the command described above, the developer console would consistently produce the following error:
```
ERR Could not find category with ID: leanprover.lean4#lean4.welcome: Error: Could not find category with ID: leanprover.lean4#lean4.welcome
    at QO.pc (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2864:25809)
    at QO.makeCategoryVisibleWhenAvailable (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2864:10685)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2866:1769
```

However, after restarting VS Code, the walkthrough would appear in the list of walkthroughs again and the error was gone.

Our [walkthrough declaration](https://github.com/leanprover/vscode-lean4/blob/9ea8703e1f434372f74856c9a35db2c78c120d6a/vscode-lean4/package.json#L829) is the following:
```json
"walkthroughs": [
    {
        "id": "lean4.welcome",
        "title": "Lean 4 Setup",
        "description": "Getting started with Lean 4\n",
        "steps": [
            {
                "id": "lean4.welcome.openSetupGuide",
                "title": "Re-Open Setup Guide",
                "description": "This guide can always be re-opened by opening an empty file, clicking on the ∀-symbol in the top right and selecting 'Documentation…' > 'Docs: Show Setup Guide'.",
                "media": {
                    "image": "media/open-setup-guide.png",
                    "altText": "Click on the ∀-symbol in the top right and select 'Documentation…' > 'Docs: Show Setup Guide'."
                }
            },
            {
                "id": "lean4.welcome.documentation",
                "title": "Books and Documentation",
                "description": "Learn using Lean 4 with the resources on the right.",
                "media": {
                    "markdown": "./media/guide-documentation.md"
                }
            },
            {
                "id": "lean4.welcome.installDeps.linux",
                "title": "Install Required Dependencies",
                "description": "Install Git and curl using your package manager.",
                "media": {
                    "markdown": "./media/guide-installDeps-linux.md"
                },
                "when": "isLinux"
            },
            {
                "id": "lean4.welcome.installDeps.mac",
                "title": "Install Required Dependencies",
                "description": "Install Homebrew, Git and curl.",
                "media": {
                    "markdown": "./media/guide-installDeps-mac.md"
                },
                "when": "isMac"
            },
            {
                "id": "lean4.welcome.installDeps.windows",
                "title": "Install Required Dependencies",
                "description": "Install Git.",
                "media": {
                    "markdown": "./media/guide-installDeps-windows.md"
                },
                "when": "isWindows"
            },
            {
                "id": "lean4.welcome.installElan.unix",
                "title": "Install Lean Version Manager",
                "description": "Install Lean's version manager Elan.\n[Click to install](command:lean4.setup.installElan)",
                "media": {
                    "markdown": "./media/guide-installElan-unix.md"
                },
                "when": "isLinux || isMac"
            },
            {
                "id": "lean4.welcome.installElan.windows",
                "title": "Install Lean Version Manager",
                "description": "Install Lean's version manager Elan.\n[Click to install](command:lean4.setup.installElan)",
                "media": {
                    "markdown": "./media/guide-installElan-windows.md"
                },
                "when": "isWindows"
            },
            {
                "id": "lean4.welcome.setupProject",
                "title": "Set Up Lean 4 Project",
                "description": "Set up a Lean 4 project by clicking on one of the options on the right.",
                "media": {
                    "markdown": "./media/guide-setupProject.md"
                }
            },
            {
                "id": "lean4.welcome.help",
                "title": "Questions and Troubleshooting",
                "description": "If you have any questions or are having trouble with any of the previous steps, please visit us on the [Lean Zulip chat](https://leanprover.zulipchat.com/) so that we can help you.",
                "media": {
                    "markdown": "./media/guide-help.md"
                }
            }
        ]
    }
]
```

No reproduction steps unfortunately because this issue seems to occur randomly.

Some additional context: We use the walkthrough mechanism to provide platform-specific instructions on how to install the Lean 4 theorem prover, so it is very bad if a first time user cannot open it or has to figure out that they need to restart VS Code first, as they are likely to get discouraged. Many of our users are mathematicians (from an undergrad to a research level), not programmers. We are considering to replace the use of the walkthrough mechanism with a custom webview for these inconsistency reasons.

**Comment by bhavyaus** [comment]
We've made several updates to this area. Could you please try a newer stable release (1.95*)?

**Comment by mhuisi** [comment]
I'll test it some more in the coming days to see if I can reproduce it again.

**Comment by mhuisi** [comment]
@bhavyaus I can't reproduce the issue on 1.95.2 and 1.95.3 anymore, thanks! I'll still keep an eye out in the future.

FWIW, we'll still have to instruct our users how to open the setup guide manually when it doesn't open automatically since VS Code doesn't seem to open it on install if the extension was already installed at some previous point in time (this can happen if users tried the extension a while ago, uninstalled it and picked it up again later), but this is probably the intended behavior (?).
