### ISSUE TITLE
"install and enable vscode-smoketest-check extension" smoke test timeout

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#232508]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=301857
Changes: https://github.com/Microsoft/vscode/compare/b8ec85e...852e43a

```
  1) VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:204:23)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:163:16)
      at async Extensions.installExtension (/Users/runner/work/1/s/test/automation/out/extensions.js:51:9)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:15:13)
```

**Comment by connor4312** [comment]
Update: there was a marketplace outage at the time of the build, could have caused this?

**Comment by sandy081** [comment]
Yes, that would be the cause.
