### ISSUE TITLE
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!

### ISSUE THREAD

**Issue by EzioLi01** [microsoft/vscode#232559]
Running vscode-test on 1.95.0 occurred this issue, working well on 1.94.2.

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at H3.add (file:///home/vsts/work/1/s/.vscode-test/vscode-linux-x64-1.95.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1439)
    at yw.n (file:///home/vsts/work/1/s/.vscode-test/vscode-linux-x64-1.95.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:1748)

```

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0
- OS Version:  MasOS, Windows, Linux

Steps to Reproduce:

1. Execute unit test via test-electron in EH.

**Comment by aiday-mar** [comment]
From author's issue, seems to maybe be related to electron

**Comment by deepak1556** [comment]
Based on the stack the error is unrelated to the runtime, it is likely from the recent logging refactor. Stack points to https://github.com/microsoft/vscode/blob/8f0188c73ff77ecc251a549e9af9b64837205fdd/src/vs/workbench/api/common/extHostOutput.ts#L168

**Comment by ArturoDent** [comment]
Still getting these "Errors" - all apparently related to :

```js
exports.dispose = async function () {
  
  if (!exports.outputChannel) return;
  else return exports.outputChannel.dispose();
};
```

> Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
>         at i.add (file:///c:/Users/markm/OneDrive/find-and-transform/.vscode-test/vscode-win32-arm64-archive-1.131.0/e4c7e7b1d6/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:429:1796)
>         at mf.doCreateOutputChannel (file:///c:/Users/markm/OneDrive/find-and-transform/.vscode-test/vscode-win32-arm64-archive-1.131.0/e4c7e7b1d6/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:542:2546)
