### ISSUE TITLE
Data loss smoke test failed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#232530]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=301920
Changes: https://github.com/Microsoft/vscode/compare/c42d363...bf0917f

```
  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies opened editors are restored:
     Error: Quick open file search was unable to find 'www' after 10 attempts, giving up.
      at QuickAccess.openFileQuickAccessAndWait (/Users/runner/work/1/s/test/automation/out/quickaccess.js:82:23)
      at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:99:9)
      at async Context.<anonymous> (out/areas/workbench/data-loss.test.js:27:13)

```

**Comment by bpasero** [comment]
The test resolver failed to install, seeing this:

```
2024-10-29 19:31:41.512 [error] [/var/folders/nj/wh528zms06j9t8y7bmlvpmjm0000gn/T/vscsmoke/extensions-dir/vscode-test-resolver]: Failed to parse /var/folders/nj/wh528zms06j9t8y7bmlvpmjm0000gn/T/vscsmoke/extensions-dir/vscode-test-resolver/package.json: [0, 0] Value expected.
```

I have never seen this before, maybe a corrupt installation.

Adding @aeschli for thoughts.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/blob/7a29a368d735313b45edabf107132fc79b98988c/extensions/vscode-test-resolver/src/extension.ts#L481

Looks like a corrupt installation to me.

**Comment by bpasero** [comment]
This is happening again: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=303704&view=results

**Comment by bpasero** [comment]
@aeschli isn't this really originating from here:

https://github.com/microsoft/vscode/blob/4b5f03fcdc1d7bb6f93fd8db45d9ae06cba26863/src/vs/platform/extensionManagement/common/extensionsScannerService.ts#L720-L730

I am still wondering why then not all tests fail but only one 🤔

**Comment by legomushroom** [comment]
Another fail today: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=304555&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=e827b0bd-5d65-5931-39e8-3dcf252f07ff
