### ISSUE TITLE
Terminal profiles smoke test caused timeout

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#232529]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=301927
Changes: https://github.com/Microsoft/vscode/compare/22b0035...f992298

Terminal tests in this build were all very slow:

```
       ✔ should create a terminal in the editor area by default (117047ms)
      Terminal Input
        Auto replies
          ✔ should automatically reply to a custom entry (47570ms)
      Terminal Persistence
        detach/attach
          ✔ should support basic reconnection (48150ms)
          - should persist buffer content
      Terminal Profiles
        ✔ should launch the default profile
        ✔ should set the default profile to a contributed one
        ✔ should use the default contributed profile on panel open and for splitting (31984ms)
        ✔ should set the default profile (23498ms)
        ✔ should use the default profile on panel open and for splitting (24980ms)
        ✔ createWithProfile command should create a terminal with a profile
        ✔ createWithProfile command should create a terminal with a contributed profile
        ✔ createWithProfile command should create a split terminal with a profile (29530ms)
        ✔ createWithProfile command should create a split terminal with a contributed profile (48906ms)
```

**Comment by bhavyaus** [comment]
Related smoke test failure:

  1) VSCode Smoke Tests (Electron)
```
       Terminal
         Terminal Persistence
           detach/attach
             should support basic reconnection:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:208:23)
      at async Code.waitForElement (/Users/runner/work/1/s/test/automation/out/code.js:164:16)
      at async QuickInput.waitForQuickInputClosed (/Users/runner/work/1/s/test/automation/out/quickinput.js:32:9)
      at async Terminal.runCommandWithValue (/Users/runner/work/1/s/test/automation/out/terminal.js:110:9)
      at async Context.<anonymous> (out/areas/terminal/terminal-persistence.test.js:41:17)


```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=312834&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=dc7a7a05-ae89-521b-55db-0cb2ded34668

**Comment by Tyriar** [comment]
This one's too old to investigate unfortunately. Chances are it was a flake related to the slow build for some unrelated reason.
