### ISSUE TITLE
Can't connect any longer to a remote linux box

### ISSUE THREAD

**Issue by milansekler** [microsoft/vscode#232747]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.0
- OS Version: Windows 10 x86

Steps to Reproduce:

1. on a Windows 10 machine use RemoteSSH to connect to a linux machine
2. I get the following error:
Pseudo-terminal will not be allocated because stdin is not a terminal.
xxxxxxx@10.xxx.xxx.xxx's password: 
xxxxxxx@xxx.xxx.xxx.xxx's password: 
-bash: line 1: $'SSH-2.0-OpenSSH_for_Windows_9.5\r': command not found

output window shows:

```
[11:36:05.701] Log Level: 2
[11:36:05.728] SSH Resolver called for "ssh-remote+100gcap2", attempt 1
[11:36:05.732] "remote.SSH.useLocalServer": false
[11:36:05.732] "remote.SSH.useExecServer": true
[11:36:05.733] "remote.SSH.showLoginTerminal": true
[11:36:05.733] "remote.SSH.remotePlatform": {"xxx-xx-xxxx-01":"linux","xxxxxx2":"linux"}
[11:36:05.733] "remote.SSH.path": undefined
[11:36:05.733] "remote.SSH.configFile": C:\Users\xxxxxxx\.ssh\config
[11:36:05.733] "remote.SSH.useFlock": true
[11:36:05.734] "remote.SSH.lockfilesInTmp": false
[11:36:05.734] "remote.SSH.localServerDownload": auto
[11:36:05.734] "remote.SSH.remoteServerListenOnSocket": false
[11:36:05.734] "remote.SSH.showLoginTerminal": true
[11:36:05.734] "remote.SSH.defaultExtensions": []
[11:36:05.734] "remote.SSH.loglevel": 2
[11:36:05.735] "remote.SSH.enableDynamicForwarding": true
[11:36:05.735] "remote.SSH.enableRemoteCommand": false
[11:36:05.735] "remote.SSH.serverPickPortsFromRange": {}
[11:36:05.735] "remote.SSH.serverInstallPath": {}
[11:36:05.735] "remote.SSH.permitPtyAllocation": false
[11:36:05.735] "remote.SSH.preferredLocalPortRange: undefined
[11:36:05.736] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[11:36:05.749] VS Code version: 1.95.0
[11:36:05.749] Remote-SSH version: remote-ssh@0.116.2024100715
[11:36:05.749] win32 x64
[11:36:05.755] SSH Resolver called for host: xxxxxx2
[11:36:05.755] Setting up SSH remote "xxxxxx2"
[11:36:05.770] Using commit id "912bb683695358a54ae0c670461738984cbb5b95" and quality "stable" for server
[11:36:05.776] Script variables:
 {
  "InstallExitCode.24": "AlreadyInProgress",
  "InstallExitCode.25": "ServerDownloadFailed",
  "InstallExitCode.26": "NoDownloaderAvailable",
  "InstallExitCode.27": "UnsupportedArch",
  "InstallExitCode.28": "StatusCheckFailed",
  "InstallExitCode.29": "NeedInsidersArch",
  "InstallExitCode.30": "NoDownloaderAvailableForStatusCheck",
  "InstallExitCode.31": "ServerTransferFailed",
  "InstallExitCode.32": "ServerFailedToStart",
  "InstallExitCode.33": "NeedInsidersWindows",
  "InstallExitCode.34": "CreateInstallDirFailed",
  "InstallExitCode.35": "UnsupportedPlatform",
  "InstallExitCode.36": "ServerTerminatedCVE20201416",
  "InstallExitCode.37": "UnpackFailed",
  "InstallExitCode.38": "ChangeDirFailed",
  "InstallExitCode.AlreadyInProgress": "24",
  "InstallExitCode.ServerDownloadFailed": "25",
  "InstallExitCode.NoDownloaderAvailable": "26",
  "InstallExitCode.NoDownloaderAvailableForStatusCheck": "30",
  "InstallExitCode.UnsupportedArch": "27",
  "InstallExitCode.StatusCheckFailed": "28",
  "InstallExitCode.NeedInsidersArch": "29",
  "InstallExitCode.ServerTransferFailed": "31",
  "InstallExitCode.ServerFailedToStart": "32",
  "InstallExitCode.NeedInsidersWindows": "33",
  "InstallExitCode.CreateInstallDirFailed": "34",
  "InstallExitCode.UnsupportedPlatform": "35",
  "InstallExitCode.ServerTerminatedCVE20201416": "36",
  "InstallExitCode.UnpackFailed": "37",
  "InstallExitCode.ChangeDirFailed": "38",
  "InstallUnpackCode.Success": "success",
  "InstallUnpackCode.Error": "error",
  "InstallUnpackCode.MissingFiles": "missingFiles",
  "uuid": "2043957873fa",
  "startMarker": "2043957873fa: running",
  "commitId": "912bb683695358a54ae0c670461738984cbb5b95",
  "quality": "stable",
  "token": "11111111-1111-11aa-a1aa-1a1a11a1a1a1",
  "vscodeAgentFolder": "$HOME/.vscode-server",
  "allowClientDownload": "1",
  "forceClientDownload": "0",
  "cliNameInArchive": "code",
  "ignoreWgetConfigFlag": " --no-config ",
  "ignoreCurlConfigFlag": " --disable ",
  "wgetTriesSegment": "--tries=1",
  "listenArgs": "--on-host=127.0.0.1 --on-port",
  "getDownloadServerStartTrigger": "2043957873fa:trigger_server_download",
  "getDownloadServerEndTrigger": "2043957873fa:trigger_server_download_end",
  "getProgressDownloading": "2043957873fa%%1%%",
  "getProgressInstalling": "2043957873fa%%2%%"
}
[11:36:05.780] Install and start server if needed
[11:36:05.789] Checking ssh with "C:\Program Files (x86)\Google\Chrome\Application\ssh.exe -V"
[11:36:05.794] Got error from ssh: spawn C:\Program Files (x86)\Google\Chrome\Application\ssh.exe ENOENT
[11:36:05.794] Checking ssh with "C:\ProgramData\Oracle\Java\javapath\ssh.exe -V"
[11:36:05.796] Got error from ssh: spawn C:\ProgramData\Oracle\Java\javapath\ssh.exe ENOENT
[11:36:05.796] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[11:36:05.798] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[11:36:05.798] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[11:36:05.800] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[11:36:05.800] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[11:36:05.802] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[11:36:05.802] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:36:05.805] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:36:05.805] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[11:36:06.177] > OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

[11:36:06.187] Using SSH config file "C:\Users\xxxxxxx\.ssh\config"
[11:36:06.187] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 56839 -F "C:\Users\xxxxxxx\.ssh\config" xxxxxx2 sh
[11:36:06.191] Generated SSH command: 'type "C:\Users\xxxxxxx\AppData\Local\Temp\vscode-linux-multi-line-command-xxxxxx2-65984402.sh" | "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 56839 -F "C:\Users\xxxxxxx\.ssh\config" 100gcap2 sh'
[11:36:06.192] Using connect timeout of 17 seconds
[11:36:06.193] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:36:07.357] > ]0;C:\WINDOWS\System32\cmd.exe
>
>

[11:36:07.357] Got some output, clearing connection timeout
[11:36:07.533] > Pseudo-terminal will not be allocated because stdin is not a terminal.
[11:36:08.500] > xxxxxxx@10.2.251.11's password: 
[11:36:16.643] > 
[11:36:18.373] > xxxxxxx@172.20.17.207's password: 
[11:36:26.160] > 
[11:36:26.847] > -bash: line 1: $'SSH-2.0-OpenSSH_for_Windows_9.5\r': command not found
[11:37:12.359] > The process tried to write to a nonexistent pipe.
[11:37:13.946] "install" terminal command done
[11:37:13.947] Install terminal quit with output: -bash: line 1: $'SSH-2.0-OpenSSH_for_Windows_9.5\r': command not found
[11:37:13.947] Received install output: -bash: line 1: $'SSH-2.0-OpenSSH_for_Windows_9.5\r': command not found
[11:37:13.949] Failed to parse remote port from server output
[11:37:13.951] Resolver error: Error: 
	at v.Create (c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:493464)
	at t.handleInstallOutput (c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:490786)
	at t.tryInstall (c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:609000)
	at async c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:568038
	at async t.withShowDetailsEvent (c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:571282)
	at async P (c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:564823)
	at async t.resolve (c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:568697)
	at async c:\Users\xxxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.116.2024100715\out\extension.js:2:839279
[11:37:13.972] ------
```

**Comment by joshspicer** [comment]
Are you able to directly (in Windows Terminal) SSH to your remote host using the command that is printed in the log (something like `C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 56839 -F "C:\Users\xxxxxxx.ssh\config" xxxxxx2 sh`)

Looking at your logs and comparing to https://github.com/PowerShell/Win32-OpenSSH/issues/2252, it seems your local SSH program may have gotten misconfigured.  Could you try [these troubleshooting steps on the Win32-OpenSSH repo](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps)?

**Comment by milansekler** [comment]
No, I can not connect with this command "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 56839 -F "C:\Users\xxxxxxx.ssh\config" xxxxxx2 sh". But I can connect fine using  "ssh -J user@xxx.xxx.xxx.xxx user@yyy.yyy.yyy.yyy" where xxx.xxx.xxx.xxx is a jump host and yyy.yyy.yyy.yyy is the destination host. The question is where is this command "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 56839 -F "C:\Users\xxxxxxx.ssh\config" xxxxxx2 sh" comming from. The only configuration file that I am aware of is user/.ssh/config and there is nothing like this in there so it must be stored somewhere else? Registry? I even tried to completely uninstall vscode and install a brand new copy of the latest release but the behavior was the same.
Thank you for your help.

**Comment by joshspicer** [comment]
In this extension, we check your local Windows [$PATH](https://www.thewindowsclub.com/how-to-add-edit-a-path-variable-in-windows) variable and iterate one-by-one checking if the path is viable.  From your log I see how the extension chose that final path:

```
[11:36:05.789] Checking ssh with "C:\Program Files (x86)\Google\Chrome\Application\ssh.exe -V"
[11:36:05.794] Got error from ssh: spawn C:\Program Files (x86)\Google\Chrome\Application\ssh.exe ENOENT
[11:36:05.794] Checking ssh with "C:\ProgramData\Oracle\Java\javapath\ssh.exe -V"
[11:36:05.796] Got error from ssh: spawn C:\ProgramData\Oracle\Java\javapath\ssh.exe ENOENT
[11:36:05.796] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[11:36:05.798] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[11:36:05.798] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[11:36:05.800] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[11:36:05.800] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[11:36:05.802] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[11:36:05.802] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:36:05.805] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:36:05.805] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[11:36:06.177] > OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
```

If you'd like to override the path used for ssh you can do so via this VS Code setting:
![Image](https://github.com/user-attachments/assets/04d80e8f-5e16-4b33-bedd-10076a7644d4)

From the terminal where you were able to successfully use `ssh`, one thing you may try is to get the full path and place it as that setting.  In powershell you can do so:

```
PS C:\Users\jospicer> Get-Command ssh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                            9.5.2.1    C:\Windows\System32\OpenSSH\ssh.exe
```

Or, by repairing your openSSH install of ssh by following this [troubleshooting guide](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps)

Let us know how it goes!

**Comment by milansekler** [comment]
From Power Shell window I got the folloving (same as your output):
Get-Command ssh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                            9.5.2.1    C:\WINDOWS\System32\OpenSSH\ssh.exe

Then I configured Remote.SSH: Path to be C:\WINDOWS\System32\OpenSSH\ssh.exe
.ssh/config file has the following:
ProxyCommand C:\WINDOWS\System32\OpenSSH\ssh.exe -J user@xxx.xxx.xxx.xxx user@yyy.yyy.yyy.yyy
Initiated connection to remote host. Got the password prompt for bot jump_box and remote host. After entering passwords I get this:

> -bash: line 1: $'SSH-2.0-OpenSSH_for_Windows_9.5\r': command not found

And no futher progress. Have to Ctrl-C to exit.
Any idea what this means? Looks like I have to remove something from my local $PATH but I am not sure what!?
Thank you

**Comment by joshspicer** [comment]
It appears the same issue with that specific `ssh` program is repro'ing outside of the Remote - SSH extension.  

Where were you able to use `ssh` successfully? Was it in a command prompt?  Try running this command `which ssh` and then copying that PATH into the setting I shared above.  That will avoid the problem you're seeing with your OpenSSH install of `ssh`.

**Comment by milansekler** [comment]
I am using Windows Power Shell when connecting succesfully as I said in my previous comment.
which ssh doesn't work since PS doesn't understand which command.

**Comment by joshspicer** [comment]
Apologies, I missed your earlier comment

```
No, I can not connect with this command "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 56839 -F "C:\Users\xxxxxxx.ssh\config" xxxxxx2 sh". But I can connect fine using "ssh -J [user@xxx.xxx.xxx.xxx](mailto:user@xxx.xxx.xxx.xxx) [user@yyy.yyy.yyy.yyy](mailto:user@yyy.yyy.yyy.yyy)" where xxx.xxx.xxx.xxx is a jump host and yyy.yyy.yyy.yyy is the destination host.
```

You will need to first update your SSH configuration such that the _exact_ command in the logs that we discussed works outside VS Code.  This could be as simple as converting the `-J` in your second command to similar configuration to:

```
Host xxxxxx2 
   HostName xxxxxx2
   ProxyJump xxx.xxx.xxx.xxx
```

Please make sure you can directly SSH outside of VS Code (in `cmd`) first, as that is critical.

You can edit your configuration through VS Code:
<img width="696" alt="Image" src="https://github.com/user-attachments/assets/d0c06adf-f467-4478-984c-0e922a3323f5" />
