### ISSUE TITLE
Title: Error in NuGetRestoreService.NominateAsync - Cannot read properties of undefined (reading 'size')

### ISSUE THREAD

**Issue by LaurenC2022** [microsoft/vscode#232779]
Description:
An error occurs when attempting to nominate a project for restore. The error message indicates that a property of undefined is being read.

Steps to Reproduce:
Attempt to nominate a project for restore using the NuGetRestoreService.
Observe the error message.
Expected Result:
The project should be nominated for restore without errors.

Actual Result:
An error message is displayed: Cannot read properties of undefined (reading 'size').

Error Message:
=====================
11/1/2024 2:34:20 AM
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.NominateForRestoreAsync(ProjectRestoreInfo restoreInfo, IReadOnlyCollection`1 versions, CancellationToken cancellationToken)
=================================================================

Additional Information:
Date and Time: 11/1/2024 2:34:20 AM
LimitedFunctionality

Environment: 
Github CodeSpace

**Comment by meganrogge** [comment]
what is NuGetRestoreService from?
