### ISSUE TITLE
Testing API: Custom TestRunRequest object in createTestRun(request) leads to duplicate Test Results entries

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#232923]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.95.1, looks like this is not a regression.
- OS Version: macOS 15.1
- Downstream issue:
  - https://github.com/microsoft/playwright/issues/30815
  - https://github.com/microsoft/playwright/issues/31556

Steps to Reproduce:

1. Use e.g. [Playwright VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) and run a single test. Demo project can be created using [these instructions](https://playwright.dev/docs/intro).

Expected: A single Test Result entry gets created
Actual: Two Test Result entries get generated

Investigation Notes:

- This happens only because Playwright's VSCode extension creates its own 'request' object here:
https://github.com/microsoft/playwright-vscode/blob/375a37dd261c5a47c112575b5c9e024489fb1952/src/extension.ts#L372
- If the original 'request' object gets used, this does not happen.
- This is because VSCode can't de-duplicate internally. If we re-use the given request, it will work because they check for identity in: https://github.com/microsoft/vscode/blob/6b924c51528e663dda5091a1493229a361676aca/src/vs/workbench/api/common/extHostTesting.ts#L956-L959
- If its not possible to de-duplicate, it creates a new `TestRun`.
- I think instead of doing it on the 'request' instance level this should check if its the same test run?

More debugging notes:

Stack from the `RunSingleTestDecoration` class:

```
    at eval (eval-b56e36a2.repl:1:6)
    at TestResultService.push (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/common/testResultService.js:109:9)
    at TestResultService.createLiveResult (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/common/testResultService.js:82:25)
    at TestService.runResolvedTests (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/common/testServiceImpl.js:202:41)
    at TestService.runTests (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/common/testServiceImpl.js:168:21)
    at RunSingleTestDecoration.runWith (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/browser/testingDecorations.js:740:33)
    at RunSingleTestDecoration.click (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/browser/testingDecorations.js:710:22)
    at UniqueContainer.value (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/browser/testingDecorations.js:421:44)
    at InteractionEmitter._deliver (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/base/common/event.js:966:22)
    at InteractionEmitter._deliverQueue (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/base/common/event.js:977:18)
```

------------------------------------------------------------------------------------------------------------------------

Stack coming from the Playwright for VSCode extension:

```
    at eval (eval-1a328b50.repl:1:6)
    at TestResultService.push (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/common/testResultService.js:109:9)
    at TestResultService.createLiveResult (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/contrib/testing/common/testResultService.js:103:21)
    at MainThreadTesting.$startedExtensionTestRun (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/api/browser/mainThreadTesting.js:150:28)
    at RPCProtocol._doInvokeHandler (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:388:23)
    at RPCProtocol._invokeHandler (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:373:41)
    at RPCProtocol._receiveRequest (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:314:28)
    at RPCProtocol._receiveOneMessage (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:241:22)
    at UniqueContainer.value (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:120:63)
    at Emitter._deliver (vscode-file://vscode-app/Users/maxschmitt/Developer/vscode/out/vs/base/common/event.js:966:22)
```

Same call / parent process from the IPC call which triggered it:

```
	at TestRunCoordinator.createTestRun (file:///Users/maxschmitt/Developer/vscode/out/vs/workbench/api/common/extHostTesting.js:813:21)
	at Object.createTestRun (file:///Users/maxschmitt/Developer/vscode/out/vs/workbench/api/common/extHostTesting.js:165:40)
	at Extension._runTests (/Users/maxschmitt/.vscode-oss-dev/extensions/ms-playwright.playwright-1.1.11/out/extension.js:9006:42)
	at /Users/maxschmitt/.vscode-oss-dev/extensions/ms-playwright.playwright-1.1.11/out/extension.js:8967:41 (at console.<anonymous> (fil
```

**Comment by mxschmitt** [comment]
Hey @connor4312 I was looking a bit more into it and thought about a few ways of fixing it. Curious to hear your preferred way of fixing it:

1. Make `TestRunRequest` `include` non read-only
1. Add `TestRunRequest` `TestRunRequest.addIncludeItems()` or `.extend()` or something like that
1. Allow `createTestRun` to pass down the original request and a new request
1. Allow passing `new TestRunRequest` to pass down a parent request.
1. Add API to remove originally created createLiveResult

I think 1) would be the easiest but not sure if it aligns with VSCode's API designs.

Thank you!

**Comment by connor4312** [comment]
Why does playwright need to create a new test run instance? Since https://github.com/microsoft/vscode/issues/213182 this should no longer be necessary.

**Comment by mxschmitt** [comment]
I see - sorry for the noise. Can confirm it works for us! Closing as a won't fix.
