### ISSUE TITLE
Editor GPU: Exception is thrown when resizing sometimes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#232979]
Repro is to open a file and resize the window ctrl/cmd++/- several times. It doesn't happen all the time.

```
 ERR Failed to execute 'writeBuffer' on 'GPUQueue': parameter 1 is not of type 'GPUBuffer'.: TypeError: Failed to execute 'writeBuffer' on 'GPUQueue': parameter 1 is not of type 'GPUBuffer'.
    at ViewLinesGpu._updateAtlasStorageBufferAndTexture (vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/viewParts/viewLinesGpu/viewLinesGpu.js:267:32)
    at ViewLinesGpu._renderText (vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/viewParts/viewLinesGpu/viewLinesGpu.js:311:14)
    at ViewLinesGpu.renderText (vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/viewParts/viewLinesGpu/viewLinesGpu.js:304:25)
    at Object.renderText (vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/view.js:437:40)
    at vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/view.js:387:54
    at safeInvokeNoArg (vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/view.js:582:16)
    at View._flushAccumulatedAndRenderNow (vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/view.js:387:22)
    at View.render (vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/view.js:505:18)
    at vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/browser/widget/codeEditor/codeEditorWidget.js:1224:34
    at vscode-file://vscode-app/Users/tyriar/dev/microsoft/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:900:47
```

**Comment by Tyriar** [comment]
Think this is happening since right now there is a hard limit of 2 pages and when resizing in enough, glyphs will will the first 2 pages and overflow to a 3rd+
