### ISSUE TITLE
Error when extension started: Cannot read properties of undefined (reading 'onShowLinkUnderline')

### ISSUE THREAD

**Issue by AF250329** [microsoft/vscode#233000]
Hi

I develop an Angular web app and everything was OK until today (? - not sure about date - may be 3 or 4 days ago)

my launch,json:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "ng serve",
      "type": "chrome",
      "request": "launch",
      "preLaunchTask": "npm: start",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}",
      "trace": true
    },
...
}
```

My Visual Studio Code Insiders:

```
Version: 1.96.0-insider (user setup)
Commit: 19fabc20e35c89915c772116503a079554166a3f
Date: 2024-11-01T16:46:43.216Z (3 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

Suddenly existing build-in Javascript debugger stop working: new Chrome window does open but that's it. It enter an endless 'waiting' (?) loop and nothing renders on the window.

So I updated to the 'nightly' build and disabled 'build-in' extension:
```
Name: JavaScript Debugger (Nightly)
Id: ms-vscode.js-debug-nightly
Description: An extension for debugging Node.js programs and Chrome.
Version: 2024.10.3117
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly
```

and tried again. The same issue appear: blank window and nothing happens after that.  I tried the same steps from Visual Studio Code (not Insiders edition)  and the same happens again.

In output window I see this error:

```
2024-11-04 17:10:01.523 [error] Cannot read properties of undefined (reading 'onShowLinkUnderline'): TypeError: Cannot read properties of undefined (reading 'onShowLinkUnderline')
    at new y (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/xterm/lib/xterm.js:1:72447)
    at t.InstantiationService.createInstance (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/xterm/lib/xterm.js:1:270025)
    at x._createRenderer (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/xterm/lib/xterm.js:1:24270)
    at vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:245795
    at vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:224810
    at Object.dispose (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:201375)
    at f (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:224536)
    at m.clear (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:225116)
    at m.dispose (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:225026)
    at l.dispose (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:225869)
2024-11-04 17:10:29.091 [error] Cannot read properties of undefined (reading 'onShowLinkUnderline'): TypeError: Cannot read properties of undefined (reading 'onShowLinkUnderline')
    at new y (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/xterm/lib/xterm.js:1:72447)
    at t.InstantiationService.createInstance (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/xterm/lib/xterm.js:1:270025)
    at x._createRenderer (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/xterm/lib/xterm.js:1:24270)
    at vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:245795
    at vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:224810
    at Object.dispose (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:201375)
    at f (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:224536)
    at m.clear (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:225116)
    at m.dispose (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:225026)
    at l.dispose (vscode-file://vscode-app/c:/Users/Aleksandr/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/node_modules/@xterm/addon-webgl/lib/addon-webgl.js:1:225869)
```

Restarting, re-installing, etc... didn't help. Everything install successfully but nothing renders on window and I could not debug the app 

I attached the 'trace' file: [vscode-debugadapter-37afd172.json.gz](https://github.com/user-attachments/files/17620291/vscode-debugadapter-37afd172.json.gz)

Also I found this line in logs:
```
2024-11-04 20:17:46.086 [warning] Skipping extension /c:/Users/Aleksandr/.vscode-insiders/extensions/ms-vscode.js-debug-1.72.1 in favour of the builtin extension /c:/Users/Aleksandr/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug.
```

**Comment by AF250329** [comment]
Hi

Just for your information - I updated to latest Visual Studio Code Insiders and everything works perfectly well:

Version: 1.96.0-insider (user setup)
Commit: f87f8a56f3a30238076bee3db39c245bd69be264
Date: 2024-11-05T05:04:15.310Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

You could close this ticket
