### ISSUE TITLE
Opening VSCode results in completely blank window

### ISSUE THREAD

**Issue by simonepri** [microsoft/vscode#233266]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.95.1 (clean install)
- OS Version: macOS 15.1 (clean install)

After factory resetting my macbook and installing VS code I'm unable to open VS code:

<img src="https://github.com/user-attachments/assets/a442aa3d-a91e-4f70-8805-e462a0da1cc6" width="400" />

Running without GPU and extensions with `code --disable-gpu --verbose --disable-extensions` returns the following exception:

```
[3543:1106/234044.223078:INFO:CONSOLE(35)] "%c  ERR color: #f33 Incorrect locale information provided: RangeError: Incorrect locale information provided
    at new Locale (<anonymous>)
    at urt.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3090:21039)
    at urt.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3090:29794)
    at urt.create (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:663:67667)
    at TNs.rc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3086:82218)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3086:79448
    at tht.invokeFunction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1354:673)
    at TNs.startup (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3086:79166)
    at APs.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3088:97983)", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (35)
```

The exception is basically identical to #147086, but there the issue was with "new DateTimeFormat" while here is with "new Locale".
I highly suspect the issue is around my system locale being `en_IT`.

![Image](https://github.com/user-attachments/assets/98670a8d-2c93-47d6-a76b-e09ec9f55696)

**Comment by simonepri** [comment]
The exception seems to be thrown by this line: https://github.com/microsoft/vscode/blob/2cac90058f0df43c91dde33bb2b8910720529368/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L487-L490

**Comment by simonepri** [comment]
It seems that indeed the issue is the locale, running the following fixes the issue (tho this is just a workaround and not a fix):

```bash
defaults write -g AppleLanguages -array "en-US"
defaults write -g AppleLocale -string "en_US"
```

@bpasero would it be possible to handle non-standard locales correctly like we did for date formats in https://github.com/microsoft/vscode/commit/b60fefb1d40de60ccafb00289d1e44255b43f626? Thanks!

**Comment by bpasero** [comment]
Thanks for this investigation you already did, thats helpful! I will need to take a closer look.
