### ISSUE TITLE
Editor GPU: Viewing lines beyond line 3000 break the editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233695]
![Image](https://github.com/user-attachments/assets/ef3ae990-64a7-403f-8712-92734830c4f8)

![Image](https://github.com/user-attachments/assets/2e730cba-f927-48b0-b61c-7d5564d7ba4f)

**Comment by mjbvz** [comment]
I'm still seeing this in `vscode.d.ts`. Here's the error stack:

```
 ERR Failed to execute 'writeBuffer' on 'GPUQueue': Data offset is too large: Error: Failed to execute 'writeBuffer' on 'GPUQueue': Data offset is too large
    at nTi.update (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:218:5063)
    at YIe.P (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:218:11261)
    at YIe.renderText (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:218:11106)
    at Object.renderText (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:225:10143)
    at Object.renderText (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:225:9050)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:225:12979
    at sM (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:225:12399)
    at Dui.g (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:225:12970)
    at Wxe.t [as d] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:225:12792)
    at Wxe.execute (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:32:14662)
```

**Comment by Tyriar** [comment]
This is fixed
