### ISSUE TITLE
Build failed: install and enable vscode-smoketest-check extension not found

### ISSUE THREAD

**Issue by legomushroom** [microsoft/vscode#233736]
Build: [link](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=304368&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=ecad4960-5379-5108-563e-8a65e2414e29)

```shell
 1) VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Extension ms-vscode.vscode-smoketest-check is not found
      at Extensions.searchForExtension (/Users/runner/work/1/s/test/automation/out/extensions.js:33:15)
      at async Extensions.installExtension (/Users/runner/work/1/s/test/automation/out/extensions.js:49:9)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:15:13)
```

**Comment by legomushroom** [comment]
Might be related: https://github.com/microsoft/vscode/issues/227668

**Comment by sandy081** [comment]
Looks like a random network issue on the build machine - From the screenshot it seems, searching for the extension has not finished.
