### ISSUE TITLE
Empty code assist widget stays back

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23414]
Version 1.11.0-insider
Commit 646d0f9e0db0c60f81b099472f4a9e3a722744b1
Date 2017-03-28T12:36:25.374Z

- create the following JavaScript file:
```
// Less configuration
var gulp = require('gulp');
var less = require('gulp-less');

gulp.task('less', function() {
    gulp.src('*.less')
        .pipe(less())
        .pipe(gulp.dest(function(f) {
            return f.base;
        }))
});
gulp.task('default', ['less'], function() {
    gulp.watch('*.less', ['less']);
})
```
- before the second gulp task type`guuu`
-  a code assist window pops up after typing `g` but once all entries are filtered an empty frame stays and the following exception is in the console:

//usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:149 Cannot read property 'row' of undefined: TypeError: Cannot read property 'row' of undefined
    at e.insertItemInDOM (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:1560)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:1224
    at Object.o [as each] (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:6:1580)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:1196
    at Array.forEach (native)
    at e.render (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:1167)
    at e.onScroll (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:2871)
    at e.invoke (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:7244)
    at e.fire (file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:10877)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:38:23340

**Comment by jaitaiwan** [comment]
Same issue as #23411?

**Comment by olebg** [comment]
Same here.

**Comment by joaomoreno** [comment]
An update with the fix is being pushed right now, just keep checking for updates.
