### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode#234174]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Ubuntu 22.04.5 LTS

Steps to Reproduce:

1. Close VSCode with 8 projects opened (most of them DevContainer projects)
2. Open VSCode again from terminal (passing `--trace-warnings` flag to show warning details) without specifying any folder or file (so last working session is used opening the 8 projects)
3. Following log is printed in the terminal:
```bash
[main 2024-11-19T10:24:29.689Z] update#setState idle
(node:471892) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 child-process-gone listeners added to [App]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:593:17)
    at App.addListener (node:events:611:10)
    at Object.X [as onWillAddFirstListener] (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7366)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at Na.H (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:13550)
    at Na.F (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:11857)
    at Na.start (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:15161)
    at vh.start (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:29191)
    at Object.call (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:4563)
    at df.s (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:34:19676)
    at df.q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:34:19199)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:34:18601)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.C (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:816)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:1033)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4908)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5092)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at T (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7343)
    at IpcMainImpl.i (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:21224)
    at IpcMainImpl.emit (node:events:531:35)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85782)
    at WebContents.emit (node:events:519:28)
[main 2024-11-19T10:24:59.835Z] update#setState checking for updates
[main 2024-11-19T10:25:00.551Z] update#setState idle
```

**Comment by rubensa** [comment]
Hi @DonJayamanne 

No, I mean 8 VSCode instances with one project (mostly DevContainer projects) opened in each instance (and, for some projects, more than one workspace folders).

**Comment by DonJayamanne** [comment]
I've tried this but not with dev containers, can you try 8 instances of VS Code each with separate folders, not dev containers.
Here's what I've tried
* Open 8 instances of vscode with 8 separate folders
* Exit VS Code
* Open terminal and run the command you provided.

Do you run into this same issue even without dev containers and all extensions disabled in step 1 (i.e. ensure they are originally disabled when opening 8 worksapces)?

**Comment by rubensa** [comment]
For all opened VSCode workspaces (11 workspaces):

- Reopen in local folder (vs. using DevContainers).
- Disable all extensions.
- Exit VSCode (File --> Exit).
- Re-launch VSCode (`code --disable-extensions --trace-warnings`).

Same result:

```bash
Warning: 'trace-warnings' is not in the list of known options, but still passed to Electron/Chromium.
[main 2024-12-10T06:10:10.952Z] update#setState idle
(node:47505) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 vscode:message listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:593:17)
    at IpcMainImpl.addListener (node:events:611:10)
    at Pw.on (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:21269)
    at Object.X [as onWillAddFirstListener] (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7366)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5077
    at Object.onWillAddFirstListener (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5397)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4900
    at Object.onWillAddFirstListener (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5397)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4710
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:2162)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4908)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at T (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7343)
    at IpcMainImpl.i (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:21224)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85782)
    at WebContents.emit (node:events:519:28)
(node:47505) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 vscode:disconnect listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:593:17)
    at IpcMainImpl.addListener (node:events:611:10)
    at Pw.on (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:21269)
    at Object.X [as onWillAddFirstListener] (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7366)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5077
    at Object.onWillAddFirstListener (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5397)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4900
    at Object.onWillAddFirstListener (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5397)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5222
    at Array.map (<anonymous>)
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5214
    at file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:2360
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4753)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4908)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5092)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at T (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7343)
    at IpcMainImpl.i (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:21224)
    at IpcMainImpl.emit (node:events:531:35)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85782)
    at WebContents.emit (node:events:519:28)
(node:47505) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 child-process-gone listeners added to [App]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:593:17)
    at App.addListener (node:events:611:10)
    at Object.X [as onWillAddFirstListener] (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7366)
    at q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:31:1282)
    at Na.H (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:13550)
    at Na.F (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:11857)
    at Na.start (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:15161)
    at vh.start (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:46:29191)
    at Object.call (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:4563)
    at df.s (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:34:19676)
    at df.q (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:34:19199)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:34:18601)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.C (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:816)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:1033)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:4908)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at qo.value (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:5092)
    at P.B (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:746)
    at P.fire (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:33:964)
    at T (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:28:7343)
    at IpcMainImpl.i (file:///opt/VSCode-linux-x64-1.95.3/resources/app/out/main.js:36:21224)
    at IpcMainImpl.emit (node:events:531:35)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85782)
    at WebContents.emit (node:events:519:28)
```

**Comment by rubensa** [comment]
Just revisiting this.

Currently on:

- VS Code Version: 1.100.2
- OS Version: Ubuntu 22.04.5 LTS.

This is still happening (when the number of opened projects is high, 8 in this case).

```bash
$ code --disable-extensions --trace-warnings
Warning: 'trace-warnings' is not in the list of known options, but still passed to Electron/Chromium.
[main 2025-06-03T05:53:11.749Z] update#setState idle
(node:81551) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 child-process-gone listeners added to [App]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:598:17)
    at App.addListener (node:events:616:10)
    at Object.ee [as onWillAddFirstListener] (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:28:7326)
    at q (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:1546)
    at Ga.G (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:43:13659)
    at Ga.D (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:43:11988)
    at Ga.start (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:43:15203)
    at Dh.start (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:43:29567)
    at Object.call (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:33:4564)
    at Af.s (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:31:20114)
    at Af.q (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:31:19637)
    at Zo.value (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:31:19039)
    at A.B (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:2373)
    at A.C (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:2443)
    at A.fire (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:2660)
    at Zo.value (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:28:4827)
    at A.B (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:2373)
    at A.fire (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:2591)
    at Zo.value (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:28:5015)
    at A.B (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:2373)
    at A.fire (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:30:2591)
    at B (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:28:7302)
    at IpcMainImpl.i (file:///opt/VSCode-linux-x64-1.100.2/resources/app/out/main.js:33:21024)
    at IpcMainImpl.emit (node:events:536:35)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87043)
    at WebContents.emit (node:events:524:28)
[main 2025-06-03T05:53:42.001Z] update#setState checking for updates
[main 2025-06-03T05:53:42.224Z] update#setState idle
```
