### ISSUE TITLE
Cannot read properties of undefined (reading 'change')

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#234274]
I see the following stack trace a lot when debugging in code OSS.

```
2024-11-20 16:16:53.368 [error] Cannot read properties of undefined (reading 'change'): TypeError: Cannot read properties of undefined (reading 'change')
    at vscode-file://vscode-app/home/martin/workspaces/vscode/out/vs/workbench/api/browser/mainThreadEditors.js:139:96
    at Array.map (<anonymous>)
    at FromEventObservable._getValue (vscode-file://vscode-app/home/martin/workspaces/vscode/out/vs/workbench/api/browser/mainThreadEditors.js:139:53)
    at FromEventObservable.handleEvent [as value] (vscode-file://vscode-app/home/martin/workspaces/vscode/out/vs/base/common/observableInternal/utils.js:70:35)
    at Emitter._deliver (vscode-file://vscode-app/home/martin/workspaces/vscode/out/vs/base/common/event.js:966:22)
    at Emitter.fire (vscode-file://vscode-app/home/martin/workspaces/vscode/out/vs/base/common/event.js:995:18)
    at DirtyDiffModel.setChanges (vscode-file://vscode-app/home/martin/workspaces/vscode/out/vs/workbench/contrib/scm/browser/dirtydiffDecorator.js:1080:27)
    at vscode-file://vscode-app/home/martin/workspaces/vscode/out/vs/workbench/contrib/scm/browser/dirtydiffDecorator.js:1072:18
```

https://github.com/microsoft/vscode/blob/aadd78ebbc033822cbe8b36acf8b5ef37ef42dbe/src/vs/workbench/api/browser/mainThreadEditors.ts#L177

**Comment by lszomoru** [comment]
Thanks! I will get this fixed ASAP.

**Comment by aeschli** [comment]
Verified in code
