### ISSUE TITLE
My abuild plugin can be debugged and run normally in versions before 1.92, but it cannot run in subsequent versions (1.92-1.95)

### ISSUE THREAD

**Issue by Y2603012723** [microsoft/vscode#234333]
#

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2,1.93.1,1.94.2,1.95.3
- OS Version: ubuntu22.04

Steps to Reproduce:

1. Open abuild development project
2. F5 Debugging
3. Debug console shows an error, the abuild plugin cannot start

My abuild plugin can be debugged and run normally in versions before 1.92, but it cannot run in subsequent versions (1.92-1.95)

The abuild plugin is a plugin I developed for Linux compilation and development. It has been working well in versions before 1.92 and can maintain the display of the debugging window in versions 1.92-1.94. However, the plugin cannot be started, and the debugging window in version 1.95 exits directly, mainly reporting NLS related errors.

For example, reporting an error in 1.94.2:

Error: !!! NLS MISSING: 523 !!!
    at Ny (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:4480)
    at p (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:4372)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:83929
    at ModuleJob.run (/home/yk/GIT/vscoodePlugIn/abuild/lib/internal/modules/esm/module_job.js:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {stack: 'Error: !!! NLS MISSING: 523 !!!
    at Ny (fi…ort (node:internal/modules/esm/loader:316:24)', message: '!!! NLS MISSING: 523 !!!'}
arg0 =
Error: !!! NLS MISSING: 523 !!!\n    at Ny (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:4480)\n    at p (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:4372)\n    at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:83929\n    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {stack: 'Error: !!! NLS MISSING: 523 !!!\n    at Ny (fi…ort (node:internal/modules/esm/loader:316:24)', message: '!!! NLS MISSING: 523 !!!'}
t @ /usr/share/code/resources/app/out/bootstrap-fork.js:16:1498

![Image](https://github.com/user-attachments/assets/88b03103-cff5-42a5-9469-896ec8d76ffd)
![Image](https://github.com/user-attachments/assets/aee8ac37-09e8-48ea-927c-2dcc5cc48bff)
![Image](https://github.com/user-attachments/assets/b557e7ea-c55d-45e4-a509-5fb219ab00b8)
![Image](https://github.com/user-attachments/assets/00a1211f-4892-4a82-bbff-775b03955d5b)
![Image](https://github.com/user-attachments/assets/f86c33f2-695f-4dfa-a8fd-d8b357b1cf9b)
![Image](https://github.com/user-attachments/assets/55f8830a-7659-4501-b28a-ae069b05607d)
![Image](https://github.com/user-attachments/assets/5f50abb9-7358-49d7-902d-29171531126c)

**Comment by bpasero** [comment]
Extensions are not impacted by ESM.
