### ISSUE TITLE
Auto detection mistakenly assumes a markdown cell as a Perl code

### ISSUE THREAD

**Issue by rohanbari** [microsoft/vscode#234453]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

On writing the following markdown segment:

```markdown
# Kaggle Course on Python

I am very happy to share my works to the world.
```

The Jupyter shows the following suggestion:

![image](https://github.com/microsoft/vscode/assets/54104015/f7002e06-debf-4ae2-b9ba-46f153b87a52)

Which is pointless.

It is probably happening since the markdown content contains the `my` keyword from the Perl language. However, it should not be happening as it is a common word. The detection needs to be improved.

### VS Code Version

Version: 1.86.2 (user setup) Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda Date: 2024-02-13T19:40:56.878Z Electron: 27.2.3 ElectronBuildId: 26908389 Chromium: 118.0.5993.159 Node.js: 18.17.1 V8: 11.8.172.18-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2024.1.1

### Jupyter logs

```shell
Visual Studio Code (1.86.2, undefined, desktop)
Jupyter Extension Version: 2024.1.1.
Python Extension Version: 2024.0.1.
Pylance Extension Version: 2024.2.2.
Platform: win32 (x64).
Workspace folder ~\code\python, Home = c:\Users\Rohan
09:22:58.711 [info] Start refreshing Kernel Picker (1708660378711)
09:22:58.733 [info] Using Pylance
09:22:58.872 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 120ms
09:22:58.884 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
09:22:58.961 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m pip list
09:22:59.753 [info] End refreshing Kernel Picker (1708660378711)
09:23:09.514 [info] Start refreshing Interpreter Kernel Picker
09:23:09.514 [info] Start refreshing Kernel Picker (1708660389514)
09:23:09.582 [info] No interpreter for Pylance for Notebook URI "Untitled-1.ipynb"
09:23:10.913 [info] End refreshing Kernel Picker (1708660389514)
09:23:19.283 [info] No interpreter for Pylance for Notebook URI "~\code\python\Playground.ipynb"
09:23:19.869 [info] No interpreter for Pylance for Notebook URI "~\code\python\Playground.ipynb"
09:23:20.187 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher  (Python Path: ~\AppData\Local\Programs\Python\Python312\python.exe, Unknown, 3.12.1) for '~\code\python\Playground.ipynb' (disableUI=true)
09:23:20.591 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 303ms
09:23:20.673 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:23:20.686 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 12660
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\pythonFiles\vscode_datascience_helpers
09:23:20.922 [warn] Stderr output when getting ipykernel version & path Traceback (most recent call last):
    File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'ipykernel' for ~\AppData\Local\Programs\Python\Python312\python.exe
09:23:21.108 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-12660pqU8flzh1ohf.json
    > cwd: ~\code\python
09:23:21.108 [info] Kernel process 12644.
09:23:21.186 [warn] StdErr from Kernel Process ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher
09:23:21.194 [error] Disposing kernel process due to an error Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON312\PYTHON.EXE
    > at ChildProcess.<anonymous> (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:276:2012)
    > stdErr = ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher
09:23:21.194 [info] Dispose Kernel process 12644.
09:23:21.198 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
09:23:21.198 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
09:23:21.199 [warn] Failed to shutdown kernel, .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher [TypeError: Cannot read properties of undefined (reading 'dispose')
	at J_.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:281:15465)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async $_.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:281:24053)]
09:23:21.203 [warn] Error occurred while trying to start the kernel, options.disableUI=true Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON312\PYTHON.EXE
    > at ChildProcess.<anonymous> (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:276:2012)
    > stdErr = ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher
09:38:17.951 [info] Handle Execution of Cells 0 for ~\code\python\Playground.ipynb
09:38:17.953 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher  (Python Path: ~\AppData\Local\Programs\Python\Python312\python.exe, Unknown, 3.12.1) for '~\code\python\Playground.ipynb' (disableUI=false)
09:38:18.306 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 344ms
09:38:18.316 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:38:18.328 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-12660Gnk99hf3ixQz.json
    > cwd: ~\code\python
09:38:18.328 [info] Kernel process 10868.
09:38:18.399 [warn] Stderr output when getting ipykernel version & path Traceback (most recent call last):
    File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'ipykernel' for ~\AppData\Local\Programs\Python\Python312\python.exe
09:38:18.405 [warn] StdErr from Kernel Process ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher
09:38:18.412 [error] Disposing kernel process due to an error Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON312\PYTHON.EXE
    > at ChildProcess.<anonymous> (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:276:2012)
    > stdErr = ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher
09:38:18.412 [info] Dispose Kernel process 10868.
09:38:18.413 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
09:38:18.414 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
09:38:18.414 [warn] Failed to shutdown kernel, .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher [TypeError: Cannot read properties of undefined (reading 'dispose')
	at J_.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:281:15465)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async $_.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:281:24053)]
09:38:18.415 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON312\PYTHON.EXE
    > at ChildProcess.<anonymous> (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:276:2012)
    > stdErr = ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher
09:38:18.416 [warn] Kernel Error, context = start Error: The kernel died. Error: ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON312\PYTHON.EXE
    > at ChildProcess.<anonymous> (~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\dist\extension.node.js:276:2012)
    > stdErr = ~\AppData\Local\Programs\Python\Python312\python.exe: No module named ipykernel_launcher
09:38:18.451 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 32ms
09:38:18.460 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:38:18.527 [info] Check & install missing Kernel dependencies for ~\AppData\Local\Programs\Python\Python312\python.exe, ui.disabled=false for resource '~\code\python\Playground.ipynb'
09:38:18.534 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:38:18.601 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:38:22.975 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m pip list
09:38:22.980 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:38:23.087 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m pip install -U --user ipykernel
09:39:23.327 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 18ms
09:39:23.333 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:39:24.248 [info] Dispose Kernel '~\code\python\Playground.ipynb' associated with '~\code\python\Playground.ipynb'
09:39:24.254 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m pip list
09:39:24.255 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher  (Python Path: ~\AppData\Local\Programs\Python\Python312\python.exe, Unknown, 3.12.1) for '~\code\python\Playground.ipynb' (disableUI=false)
09:39:24.493 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 234ms
09:39:24.500 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:39:24.516 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-12660IIsbmPh4VCA1.json
    > cwd: ~\code\python
09:39:24.516 [info] Kernel process 4748.
09:39:26.581 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
09:39:27.114 [info] Registering Kernel Completion Provider from kernel Python 3.12.1 for language python
09:39:27.126 [info] Kernel acknowledged execution of cell 0 @ 1708661367125
09:39:27.135 [info] End cell 0 execution after 0.01s, completed @ 1708661367135, started @ 1708661367125
09:40:08.456 [info] Handle Execution of Cells 0 for ~\code\python\Playground.ipynb
09:40:08.466 [info] Kernel acknowledged execution of cell 0 @ 1708661408466
09:40:08.469 [info] End cell 0 execution after 0.002s, completed @ 1708661408468, started @ 1708661408466
09:42:20.118 [info] Handle Execution of Cells 1 for ~\code\python\Playground.ipynb
09:42:20.130 [info] Kernel acknowledged execution of cell 1 @ 1708661540130
09:42:20.133 [info] End cell 1 execution after 0.002s, completed @ 1708661540132, started @ 1708661540130
09:42:47.052 [info] Handle Execution of Cells 1 for ~\code\python\Playground.ipynb
09:42:47.066 [info] Kernel acknowledged execution of cell 1 @ 1708661567066
09:42:47.068 [info] End cell 1 execution after 0.002s, completed @ 1708661567068, started @ 1708661567066
09:42:56.084 [info] Handle Execution of Cells 1 for ~\code\python\Playground.ipynb
09:42:56.094 [info] Kernel acknowledged execution of cell 1 @ 1708661576094
09:42:56.096 [info] End cell 1 execution after 0.001s, completed @ 1708661576095, started @ 1708661576094
09:43:23.540 [info] Handle Execution of Cells 1 for ~\code\python\Playground.ipynb
09:43:23.556 [info] Kernel acknowledged execution of cell 1 @ 1708661603555
09:43:23.557 [info] End cell 1 execution after 0.002s, completed @ 1708661603557, started @ 1708661603555
09:43:48.612 [info] Handle Execution of Cells 1 for ~\code\python\Playground.ipynb
09:43:48.624 [info] Kernel acknowledged execution of cell 1 @ 1708661628624
09:43:48.625 [info] End cell 1 execution after 0.001s, completed @ 1708661628625, started @ 1708661628624
09:50:22.141 [info] Handle Execution of Cells 1 for ~\code\python\Playground.ipynb
09:50:22.152 [info] Kernel acknowledged execution of cell 1 @ 1708662022151
09:50:22.154 [info] End cell 1 execution after 0.002s, completed @ 1708662022153, started @ 1708662022151
09:50:25.123 [info] Handle Execution of Cells 1 for ~\code\python\Playground.ipynb
09:50:25.130 [info] Kernel acknowledged execution of cell 1 @ 1708662025130
09:50:25.135 [info] End cell 1 execution after 0.005s, completed @ 1708662025135, started @ 1708662025130
09:54:28.888 [info] Handle Execution of Cells 2 for ~\code\python\Playground.ipynb
09:54:28.898 [info] Kernel acknowledged execution of cell 2 @ 1708662268897
09:54:28.900 [info] End cell 2 execution after 0.003s, completed @ 1708662268900, started @ 1708662268897
09:54:42.079 [info] Handle Execution of Cells 2 for ~\code\python\Playground.ipynb
09:54:42.086 [info] Kernel acknowledged execution of cell 2 @ 1708662282086
09:54:42.091 [info] End cell 2 execution after 0.004s, completed @ 1708662282090, started @ 1708662282086
09:54:45.392 [info] Handle Execution of Cells 3 for ~\code\python\Playground.ipynb
09:54:45.394 [info] End cell 3 execution after 0s, completed @ undefined, started @ undefined
09:54:47.043 [info] Handle Execution of Cells 4 for ~\code\python\Playground.ipynb
09:54:47.044 [info] End cell 4 execution after 0s, completed @ undefined, started @ undefined
09:54:53.469 [info] Disposing request as the cell (-1) was deleted ~\code\python\Playground.ipynb
09:55:02.033 [info] Disposing request as the cell (-1) was deleted ~\code\python\Playground.ipynb
09:55:10.483 [info] Handle Execution of Cells 2 for ~\code\python\Playground.ipynb
09:55:10.489 [info] Kernel acknowledged execution of cell 2 @ 1708662310489
09:55:10.496 [info] End cell 2 execution after 0.007s, completed @ 1708662310496, started @ 1708662310489
09:55:19.536 [info] Handle Execution of Cells 2 for ~\code\python\Playground.ipynb
09:55:19.546 [info] Kernel acknowledged execution of cell 2 @ 1708662319545
09:55:19.548 [info] End cell 2 execution after 0.003s, completed @ 1708662319548, started @ 1708662319545
09:55:21.616 [info] Handle Execution of Cells 2 for ~\code\python\Playground.ipynb
09:55:21.625 [info] Kernel acknowledged execution of cell 2 @ 1708662321621
09:55:21.632 [info] End cell 2 execution after 0.011s, completed @ 1708662321632, started @ 1708662321621
09:55:35.128 [info] Handle Execution of Cells 2 for ~\code\python\Playground.ipynb
09:55:35.136 [info] Kernel acknowledged execution of cell 2 @ 1708662335134
09:55:35.141 [info] End cell 2 execution after 0.007s, completed @ 1708662335141, started @ 1708662335134
09:56:18.070 [info] Handle Execution of Cells 2 for ~\code\python\Playground.ipynb
09:56:18.081 [info] Kernel acknowledged execution of cell 2 @ 1708662378080
09:56:18.083 [info] End cell 2 execution after 0.002s, completed @ 1708662378082, started @ 1708662378080
09:56:59.486 [info] Disposing request as the cell (0) was deleted ~\code\python\Playground.ipynb
09:56:59.486 [info] Disposing request as the cell (0) was deleted ~\code\python\Playground.ipynb
09:56:59.486 [info] Disposing request as the cell (1) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (1) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (1) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (1) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (1) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (1) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (1) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (2) was deleted ~\code\python\Playground.ipynb
09:56:59.487 [info] Disposing request as the cell (2) was deleted ~\code\python\Playground.ipynb
09:56:59.488 [info] Disposing request as the cell (2) was deleted ~\code\python\Playground.ipynb
09:56:59.488 [info] Disposing request as the cell (2) was deleted ~\code\python\Playground.ipynb
09:56:59.488 [info] Disposing request as the cell (2) was deleted ~\code\python\Playground.ipynb
09:56:59.488 [info] Disposing request as the cell (2) was deleted ~\code\python\Playground.ipynb
09:56:59.488 [info] Disposing request as the cell (2) was deleted ~\code\python\Playground.ipynb
09:56:59.488 [info] Dispose Kernel '~\code\python\Playground.ipynb' associated with '~\code\python\Playground.ipynb'
09:56:59.489 [info] Dispose Kernel process 4748.
09:56:59.499 [info] Process Execution: c:\Windows\System32\taskkill.exe /F /T /PID 4748
09:56:59.640 [info] No interpreter for Pylance for Notebook URI "~\code\python\Arithmetic and Variables.ipynb"
09:58:36.278 [info] Handle Execution of Cells 3 for ~\code\python\Arithmetic and Variables.ipynb
09:58:36.281 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher  (Python Path: ~\AppData\Local\Programs\Python\Python312\python.exe, Unknown, 3.12.1) for '~\code\python\Arithmetic and Variables.ipynb' (disableUI=true)
09:58:36.505 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 221ms
09:58:36.511 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m pip list
09:58:36.516 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 227ms
09:58:36.522 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:58:36.536 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-12660Yo40FSta0WMy.json
    > cwd: ~\code\python
09:58:36.536 [info] Kernel process 564.
09:58:37.931 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
09:58:38.505 [info] Registering Kernel Completion Provider from kernel Python 3.12.1 for language python
09:58:38.519 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2024.1.1-win32-x64\pythonFiles\printJupyterDataDir.py
09:58:38.530 [info] Kernel acknowledged execution of cell 3 @ 1708662518530
09:58:38.533 [info] End cell 3 execution after 0.003s, completed @ 1708662518533, started @ 1708662518530
09:58:43.436 [info] Handle Execution of Cells 3 for ~\code\python\Arithmetic and Variables.ipynb
09:58:43.442 [info] Kernel acknowledged execution of cell 3 @ 1708662523442
09:58:43.447 [info] End cell 3 execution after 0.005s, completed @ 1708662523447, started @ 1708662523442
09:58:46.381 [info] Handle Execution of Cells 3 for ~\code\python\Arithmetic and Variables.ipynb
09:58:46.388 [info] Kernel acknowledged execution of cell 3 @ 1708662526387
09:58:46.395 [info] End cell 3 execution after 0.008s, completed @ 1708662526395, started @ 1708662526387
09:58:51.245 [info] Handle Execution of Cells 3 for ~\code\python\Arithmetic and Variables.ipynb
09:58:51.255 [info] Kernel acknowledged execution of cell 3 @ 1708662531255
09:58:51.258 [info] End cell 3 execution after 0.003s, completed @ 1708662531258, started @ 1708662531255
09:59:06.507 [info] Handle Execution of Cells 3 for ~\code\python\Arithmetic and Variables.ipynb
09:59:06.518 [info] Kernel acknowledged execution of cell 3 @ 1708662546518
09:59:06.521 [info] End cell 3 execution after 0.003s, completed @ 1708662546521, started @ 1708662546518
10:08:00.708 [info] No interpreter for Pylance for Notebook URI "Untitled-1.ipynb"
10:08:04.312 [info] No interpreter for Pylance for Notebook URI "~\code\python\Functions.ipynb"
10:08:04.625 [info] No interpreter for Pylance for Notebook URI "~\code\python\Functions.ipynb"
10:08:04.949 [info] No interpreter for Pylance for Notebook URI "~\code\python\Functions.ipynb"
10:08:04.956 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd077ea1d837ba88d39d1da8a46a378df4d39daecc0b2ec75acfbdc990c6cc53527.~\AppData\Local\Programs\Python\Python312\python.exe.~\AppData\Local\Programs\Python\Python312\python.exe.-m#ipykernel_launcher  (Python Path: ~\AppData\Local\Programs\Python\Python312\python.exe, Unknown, 3.12.1) for '~\code\python\Functions.ipynb' (disableUI=true)
10:08:05.403 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 444ms
10:08:05.409 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m pip list
10:08:05.413 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 361ms
10:08:05.419 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
10:08:05.432 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-126607FZT38NKvOnl.json
    > cwd: ~\code\python
10:08:05.432 [info] Kernel process 10284.
10:08:06.967 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
10:08:07.389 [info] Registering Kernel Completion Provider from kernel Python 3.12.1 for language python
10:13:30.303 [warn] Timeout (after 20000ms) waiting to inspect code 'def and'
10:13:34.835 [warn] Timeout (after 20000ms) waiting to inspect code 'def add_two_to(vars'
10:13:35.656 [warn] Timeout (after 20000ms) waiting to inspect code 'def add_two_to(pass'
10:14:01.482 [info] Handle Execution of Cells 0 for ~\code\python\Functions.ipynb
10:14:01.490 [info] Kernel acknowledged execution of cell 0 @ 1708663441490
10:14:01.496 [info] End cell 0 execution after 0.006s, completed @ 1708663441496, started @ 1708663441490
```

### Coding Language and Runtime Version

Python 3.14.1

### Language Extension Version (if applicable)

v2024.0.1

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
similar to https://github.com/microsoft/vscode/issues/208674
