### ISSUE TITLE
escaping terminal chat / creating inline chat in the editor causes error

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#234596]
1. Run a few chat requests
2. Hit escape

See this error in the console

```
 ERR TreeError [Chat] Tree element not found: [object Object]: Error: TreeError [Chat] Tree element not found: [object Object]
    at Jse.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:423:8336)
    at Jse.expandTo (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:423:7756)
    at Gk.reveal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:423:2165)
    at VD.sb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:717:26633)
    at VD.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:717:38623)
    at $J.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1510:7627)
    at $J.layout (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1510:7434)
    at Het.P (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2505:6300)
    at Het.O (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2505:6030)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2505:5404
```

**Comment by meganrogge** [comment]
call to `layout` where the error is thrown happens before `hide` is called
https://github.com/user-attachments/assets/c337c121-5bcc-4045-91b6-6c0b377c35b0

**Comment by meganrogge** [comment]
the call to `doLayout` is coming from here 

![Image](https://github.com/user-attachments/assets/f7cb0457-ebb4-4bbb-b5fe-9abdb780a373)

**Comment by meganrogge** [comment]
@roblourens bisected to 32f6e84cfb15d14494ee259174172a95558b36b5
![Image](https://github.com/user-attachments/assets/f5fc5069-0f36-4f7f-b645-3310447a7124)

**Comment by meganrogge** [comment]
also reproduces when I open chat in the editor 

![Image](https://github.com/user-attachments/assets/e6c94bde-69de-4394-9690-9042c3250fec)

**Comment by meganrogge** [comment]
maybe related #234595

**Comment by roblourens** [comment]
- Chat list is cleared
- Need to rerender
- List height changes
- Terminal chat widget wants to do a layout in this case
- Try to reveal the last item, but the last item property isn't updated until the render is done, that's incorrect
