### ISSUE TITLE
Errors in console when opening folder that's not under git

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23457]
```
extensionHost.js:153 [Extension Host] debugger listening on port 5870
shell.js:261 Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at c:\Alex\src\vscode\out\vs\workbench\api\node\extHostSCM.js:102:62
    at CallbackList.invoke (c:\Alex\src\vscode\out\vs\base\common\callbackList.js:57:43)
    at Emitter.fire (c:\Alex\src\vscode\out\vs\base\common\event.js:88:40)
    at Timeout._onTimeout (c:\Alex\src\vscode\out\vs\base\common\event.js:285:33)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
extensionHost.js:229 [Extension Host] 
Object {message: "Failed to execute git", stdout: "", stderr: "fatal: Not a git repository (or any of the parent directories): .git↵", exitCode: 128, gitErrorCode: "NotAGitRepository"…}
2
shell.js:261 Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at c:\Alex\src\vscode\out\vs\workbench\api\node\extHostSCM.js:102:62
    at CallbackList.invoke (c:\Alex\src\vscode\out\vs\base\common\callbackList.js:57:43)
    at Emitter.fire (c:\Alex\src\vscode\out\vs\base\common\event.js:88:40)
    at Timeout._onTimeout (c:\Alex\src\vscode\out\vs\base\common\event.js:285:33)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
WorkbenchShell.onUnexpectedError	@	shell.js:261
(anonymous function)	@	shell.js:231
ErrorHandler.onUnexpectedError	@	errors.js:42
onUnexpectedError	@	errors.js:60
MainThreadErrors.onUnexpectedExtHostError	@	mainThreadErrors.js:18
AbstractThreadService.handle	@	abstractThreadService.js:24
invokeHandler	@	ipcRemoteCom.js:201
receiveOneMessage	@	ipcRemoteCom.js:165
_combinedTickCallback	@	internal/process/next_tick.js:67
_tickCallback	@	internal/process/next_tick.js:98

```
![image](https://cloud.githubusercontent.com/assets/5047891/24414957/29d530d0-13e0-11e7-8233-cdcae4c962cc.png)

**Comment by joaomoreno** [comment]
I don't think this could've come from the git scm provider. All `.map` calls in `extHostSCM.ts` are made on stuff that the git provider has strict non-null-or-undefined checks.

Were you implementing an SCM provider?

**Comment by alexandrudima** [comment]
my bad, a `gulp compile-extensions` fixed it, sorry for the noise
