### ISSUE TITLE
[Chat] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#234541]
```
 ERR TreeError [Chat] Tree element not found: [object Object]: Error: TreeError [Chat] Tree element not found: [object Object]
    at ObjectTreeModel.getElementLocation (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:218:19)
    at ObjectTreeModel.expandTo (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:180:31)
    at WorkbenchObjectTree.reveal (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/abstractTree.js:2281:20)
    at ChatWidget.scrollToEnd (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/chat/browser/chatWidget.js:337:23)
    at ChatWidget.layout (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/chat/browser/chatWidget.js:908:18)
    at EditorBasedInlineChatWidget._doLayout (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.js:249:26)
    at EditorBasedInlineChatWidget._doLayout (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.js:424:15)
    at EditorBasedInlineChatWidget.layout (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.js:234:18)
    at InlineChatZoneWidget._doLayout (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/workbench/contrib/inlineChat/browser/inlineChatZoneWidget.js:141:21)
    at InlineChatZoneWidget._onViewZoneHeight (vscode-file://vscode-app/Users/jrieken/Code/vscode/out/vs/editor/contrib/zoneWidget/browser/zoneWidget.js:203:18)
```

**Comment by jrieken** [comment]
To verify

* use inline chat, accept its change
* use inline chat again
* make sure the error above isn't printed on the console
