### ISSUE TITLE
terminal mac os web smoke tests failing

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#234606]
seems like a few consistent smoke test failures:

see build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=306954&view=results and https://dev.azure.com/monacotools/Monaco/_build/results?buildId=306866&view=results
```
  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Input
           Auto replies
             should automatically reply to a custom entry:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:205:23)
      at async Code.waitForTerminalBuffer (/Users/runner/work/1/s/test/automation/out/code.js:176:9)
      at async Terminal.waitForTerminalText (/Users/runner/work/1/s/test/automation/out/terminal.js:262:13)
      at async Context.<anonymous> (out/areas/terminal/terminal-input.test.js:38:17)
```

see build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=306898&view=results and https://dev.azure.com/monacotools/Monaco/_build/results?buildId=306921&view=results and some more

anywhere from 1-14 tests failing like below

```
  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Process-based tests
             Decorations
               terminal.integrated.shellIntegration.decorationsEnabled should determine gutter and overview ruler decoration visibility
                 "before each" hook for "never":
     Error: Timeout: is active element ' .monaco-editor[data-uri$="settings.json"] .native-edit-context' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:205:23)
      at async Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/out/code.js:167:9)
      at async Editor.waitForEditorFocus (/Users/runner/work/1/s/test/automation/out/editor.js:68:9)
      at async SettingsEditor.openUserSettingsFile (/Users/runner/work/1/s/test/automation/out/settings.js:51:9)
      at async SettingsEditor.clearUserSettings (/Users/runner/work/1/s/test/automation/out/settings.js:42:9)
      at async Context.<anonymous> (out/areas/terminal/terminal-shellIntegration.test.js:54:25)

  2) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Process-based tests
             "after all" hook in "Process-based tests":
     Error: Timeout: is active element ' .monaco-editor[data-uri$="settings.json"] .native-edit-context' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:205:23)
      at async Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/out/code.js:167:9)
      at async Editor.waitForEditorFocus (/Users/runner/work/1/s/test/automation/out/editor.js:68:9)
      at async SettingsEditor.openUserSettingsFile (/Users/runner/work/1/s/test/automation/out/settings.js:51:9)
      at async SettingsEditor.clearUserSettings (/Users/runner/work/1/s/test/automation/out/settings.js:42:9)
      at async Context.<anonymous> (out/areas/terminal/terminal-shellIntegration.test.js:33:17)

  3) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Write data-based tests
             "before all" hook in "Write data-based tests":
     Error: Timeout: is active element ' .monaco-editor[data-uri$="settings.json"] .native-edit-context' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:205:23)
      at async Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/out/code.js:167:9)
      at async Editor.waitForEditorFocus (/Users/runner/work/1/s/test/automation/out/editor.js:68:9)
      at async SettingsEditor.openUserSettingsFile (/Users/runner/work/1/s/test/automation/out/settings.js:51:9)
      at async SettingsEditor.addUserSettings (/Users/runner/work/1/s/test/automation/out/settings.js:36:9)
      at async setTerminalTestSettings (out/areas/terminal/terminal-helpers.js:9:5)
      at async Context.<anonymous> (out/areas/terminal/terminal-shellIntegration.test.js:89:17)

  4) VSCode Smoke Tests (Web)
       Terminal
         Terminal Shell Integration
           Write data-based tests
             "after all" hook in "Write data-based tests":
     Error: Timeout: is active element ' .monaco-editor[data-uri$="settings.json"] .native-edit-context' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:205:23)
      at async Code.waitForActiveElement (/Users/runner/work/1/s/test/automation/out/code.js:167:9)
      at async Editor.waitForEditorFocus (/Users/runner/work/1/s/test/automation/out/editor.js:68:9)
      at async SettingsEditor.openUserSettingsFile (/Users/runner/work/1/s/test/automation/out/settings.js:51:9)
```

cc. @lszomoru

**Comment by Tyriar** [comment]
@aiday-mar can you please look into this. The smoke tests work by modifying settings.json via this call:

https://github.com/microsoft/vscode/blob/f408139c28c2c653d673e9a85ba250d6c6a588be/test/smoke/src/areas/terminal/terminal-input.test.ts#L41

This seems to have broken/become flaky with the edit context work. This is what the file looks like after that runs ([from artifacts](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=306954&view=artifacts&pathAsName=false&type=publishedArtifacts)):

![Image](https://github.com/user-attachments/assets/cb0dbdc4-29ab-40d2-952f-1df650778c2c)

We could just set the edit context setting to off here:

https://github.com/microsoft/vscode/blob/f408139c28c2c653d673e9a85ba250d6c6a588be/test/smoke/src/areas/terminal/terminal-helpers.ts#L9-L19

But I'm still worried about flakiness with that since the edit context would need to be swapped out without a reload and we would need to change the settings.json file originally via edit context.

**Comment by aiday-mar** [comment]
Thanks @Tyriar for filing this issue. I decided to disable temporarily the edit context and look into this later, as today is testing day. Pipeline should be green again after the disablement.

**Comment by roblourens** [comment]
Failing again: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=314527&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=9bf4811f-3b17-5241-2b4f-e029360c547f

**Comment by aiday-mar** [comment]
I believe this should be fixed now
