### ISSUE TITLE
UNC host '...' access is not allowed EVEN THOUGH the host is in 'security.allowedUNCHosts' list

### ISSUE THREAD

**Issue by ruby3141** [microsoft/vscode#234720]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:
(I want to provide more detailed info, but I don't know where to retreive more.)

1. add 172.16.1.10 to 'security.allowedUNCHosts' list
```
    "security.allowedUNCHosts": [
        "172.16.1.10"
    ],
```
2. Still it doesn't work
```
2024-11-27 11:42:00.978 [error] Error: Unable to read file '\\172.16.1.10\[REDACTED]\memo.txt' (Unknown (FileSystemError): UNC host '172.16.1.10' access is not allowed. Please update the 'security.allowedUNCHosts' setting if you want to allow this host.)
    at Pnt.F (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Gnt.M (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:9119)
    at async Gnt.readStream (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:8894)
    at async Pde.Db (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1275:11960)
    at async Pde.resolve (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1275:10435)
    at async Unt.W (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:5752)
    at async _Ue.jb (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1941:16380)
    at async Nbe.setInput (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2101:31068)
    at async j8e.U (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:663:100849)
```

I already read https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths and found out defining a global env variable works.
But I think it should work only with 'security.allowedUNCHosts'.

**Comment by ruby3141** [comment]
![Image](https://github.com/user-attachments/assets/60490017-1db3-42dc-b3d8-c8f33f83c0f5)
For the server 172.16.1.10 it's behind this kind of login prompt when accessed via windows file explorer.
With env variable set but not logged in on explorer.exe VSCode failed to access to the file with provided UNC but with different kind of error.
```
2024-11-27 13:45:51.438 [error] Error: Unable to read file '\\172.16.1.10\[Redacted]\memo.txt' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\172.16.1.10\[Redacted]\memo.txt')
    at Pnt.F (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Gnt.M (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:9119)
    at async Gnt.readStream (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:8894)
    at async Pde.Db (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1275:11960)
    at async Pde.resolve (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1275:10435)
    at async Unt.W (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:5752)
    at async _Ue.jb (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1941:16380)
    at async Nbe.setInput (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2101:31068)
    at async j8e.U (vscode-file://vscode-app/c:/Users/ruby3141/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:663:100849)
```

After properly logged in on explorer.exe there's no problem with accessing the file.
