### ISSUE TITLE
Command `View: Toggle Terminal` stops working after spamming it before the terminal is fully loaded

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#234927]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open a folder in vsCode.
2. Immediately start pressing terminal toggle shortcut.
3. When you do this and terminal isn't fully loaded yet, after open and closing it for the first time, the shortcut isn't going to work anymore.

See this video:

https://github.com/user-attachments/assets/8ab184f4-4470-4ef9-9698-d81e59b4cb57

```
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by meganrogge** [comment]
also what do the logs say if you run `Developer: Toggle Keyboard Shortcuts Troubleshooting`?

**Comment by babakfp** [comment]
> any errors in the dev tools console?

```
 INFO Started local extension host with pid 17456.
workbench.desktop.main.js:sourcemap:35  INFO Settings Sync: Updating due to initialize
workbench.desktop.main.js:sourcemap:35  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
workbench.desktop.main.js:sourcemap:35  INFO Settings Sync: Authentication providers updated Array(2)
workbench.desktop.main.js:sourcemap:35  WARN 

----------------------------------------------
***	Installation has been modified on disk ***
----------------------------------------------


workbench.desktop.main.js:sourcemap:35  INFO [perf] Render performance baseline is 30ms
```

> also what do the logs say if you run Developer: Toggle Keyboard Shortcuts Troubleshooting?

```
2024-12-08 01:33:49.229 [info] Started local extension host with pid 10088.
2024-12-08 01:33:49.582 [info] Settings Sync: Updating due to initialize
2024-12-08 01:33:49.582 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.583 [info] Settings Sync: Authentication providers updated []
2024-12-08 01:33:49.595 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.596 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-08 01:33:49.596 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.596 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-08 01:33:49.596 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.597 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 01:33:49.597 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.597 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 01:33:49.623 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-08 01:33:49.623 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.623 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 01:33:49.623 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-08 01:33:49.624 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.624 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 01:33:49.804 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:33:49.804 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 01:33:51.703 [warning] 

----------------------------------------------
***	Installation has been modified on disk ***
----------------------------------------------


2024-12-08 01:33:53.643 [info] [perf] Render performance baseline is 29ms
2024-12-08 01:34:05.314 [warning] [backup tracker] suspended, ignoring unregister event file:///c%3A/Users/Babak/Documents/Code/.archived/CLI/clack/package.json 
2024-12-08 01:34:05.314 [warning] [backup tracker] suspended, ignoring unregister event file:///c%3A/Users/Babak/Documents/Code/.archived/CLI/clack/packages/core/package.json 
2024-12-08 01:34:05.314 [warning] [backup tracker] suspended, ignoring unregister event file:///c%3A/Users/Babak/Documents/Code/.archived/CLI/clack/examples/basic/package.json 
2024-12-08 01:34:05.766 [info] Started local extension host with pid 17456.
2024-12-08 01:34:06.422 [info] Settings Sync: Updating due to initialize
2024-12-08 01:34:06.422 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 01:34:06.423 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 01:34:08.245 [warning] 

----------------------------------------------
***	Installation has been modified on disk ***
----------------------------------------------


2024-12-08 01:34:08.342 [info] [perf] Render performance baseline is 30ms
2024-12-08 01:35:52.751 [error] There are no commenting ranges at the current position (with range).: Error: There are no commenting ranges at the current position (with range).
    at Ov.addCommentAtLine (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:644:2600)
    at Ov.addOrToggleCommentAtLine (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:644:2138)
    at Ov.db (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:644:1787)
    at vZ.value (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:643:21213)
    at Af.B (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:747)
    at Af.C (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:817)
    at Af.fire (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:1034)
    at Af.fire (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:262:19570)
    at s.onMouseUp (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:262:17539)
    at fli.emitMouseUp (vscode-file://vscode-app/c:/Users/Babak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:135:17522)
2024-12-08 01:36:12.813 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-12-08 01:36:12.814 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-12-08 01:36:12.815 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
2024-12-08 01:36:12.815 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
2024-12-08 01:36:12.816 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-12-08 01:36:13.429 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-12-08 01:36:13.430 [info] [KeybindingService]: | Resolving ctrl+C
2024-12-08 01:36:13.430 [info] [KeybindingService]: \ From 8 keybinding entries, matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.
2024-12-08 01:36:13.431 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyC, keyCode: 67, key: c
2024-12-08 01:36:13.431 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyC, keyCode: 33 ('C')
2024-12-08 01:36:13.432 [info] [KeybindingService]: | Resolving ctrl+C
2024-12-08 01:36:13.432 [info] [KeybindingService]: \ From 8 keybinding entries, matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.
2024-12-08 01:36:13.433 [info] [KeybindingService]: + Invoking command editor.action.clipboardCopyAction.
2024-12-08 01:36:14.150 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-12-08 01:36:14.150 [info] [KeybindingService]: | Resolving ctrl+C
2024-12-08 01:36:14.150 [info] [KeybindingService]: \ From 8 keybinding entries, matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.
2024-12-08 01:36:14.150 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyC, keyCode: 67, key: c
2024-12-08 01:36:14.150 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyC, keyCode: 33 ('C')
2024-12-08 01:36:14.150 [info] [KeybindingService]: | Resolving ctrl+C
2024-12-08 01:36:14.151 [info] [KeybindingService]: \ From 8 keybinding entries, matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.
2024-12-08 01:36:14.151 [info] [KeybindingService]: + Invoking command editor.action.clipboardCopyAction.
2024-12-08 01:36:14.328 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-12-08 01:36:14.328 [info] [KeybindingService]: | Resolving ctrl+C
2024-12-08 01:36:14.328 [info] [KeybindingService]: \ From 8 keybinding entries, matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.
2024-12-08 01:36:14.328 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyC, keyCode: 67, key: c
2024-12-08 01:36:14.328 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyC, keyCode: 33 ('C')
2024-12-08 01:36:14.329 [info] [KeybindingService]: | Resolving ctrl+C
2024-12-08 01:36:14.329 [info] [KeybindingService]: \ From 8 keybinding entries, matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.
2024-12-08 01:36:14.329 [info] [KeybindingService]: + Invoking command editor.action.clipboardCopyAction.
2024-12-08 01:36:14.569 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```

**Comment by meganrogge** [comment]
based on the logs, you're actioning the copy action with that 

> matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.

**Comment by babakfp** [comment]
@meganrogge

Are you mentioning the `ctrl` + `c` key presses? I accidentally did that a few times when trying to copy the logs.

Here is a clean logs:

```
2024-12-08 20:05:07.650 [info] Started local extension host with pid 26284.
2024-12-08 20:05:09.182 [info] Settings Sync: Updating due to initialize
2024-12-08 20:05:09.183 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.183 [info] Settings Sync: Authentication providers updated []
2024-12-08 20:05:09.188 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.189 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-08 20:05:09.189 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.189 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-08 20:05:09.189 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.189 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:09.189 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.189 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:09.351 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-08 20:05:09.351 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.351 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:09.351 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-08 20:05:09.351 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.351 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:09.383 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:09.383 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:11.534 [warning] 

----------------------------------------------
***	Installation has been modified on disk ***
----------------------------------------------


2024-12-08 20:05:13.290 [info] Started local extension host with pid 11928.
2024-12-08 20:05:13.752 [info] Settings Sync: Updating due to initialize
2024-12-08 20:05:13.752 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.752 [info] Settings Sync: Authentication providers updated []
2024-12-08 20:05:13.805 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.805 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-08 20:05:13.805 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.805 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-08 20:05:13.805 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.805 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:13.806 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.806 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:13.815 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-08 20:05:13.816 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.816 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:13.816 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-08 20:05:13.816 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.816 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:13.982 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-08 20:05:13.983 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-08 20:05:15.732 [warning] 

----------------------------------------------
***	Installation has been modified on disk ***
----------------------------------------------


2024-12-08 20:05:16.433 [info] [perf] Render performance baseline is 28ms
```

NOTE: the issue happened because I saw the last line in logs.
