### ISSUE TITLE
Settings Sync disabled after jwt expires

### ISSUE THREAD

**Issue by Segdo** [microsoft/vscode#234932]
Type: <b>Bug</b>

Every time I enable settings sync with my microsoft account it disables itself after some time (few hours) and the log says the jwt is expired.

VS Code version: Code - Insiders 1.96.0-insider (275faf6f08b7aa50843f3c18406b4d5969784e52, 2024-11-28T18:04:55.375Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.91GB (38.58GB free)|
|Process Argv|--crash-reporter-id 812f5ae5-3e6e-4065-8cc6-723bebd69a1d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
ng-template|Ang|19.0.2
vscode-tailwindcss|bra|0.12.15
doxdocgen|csc|1.4.0
postcss|css|1.0.9
dart-code|Dar|3.100.0
flutter|Dar|3.100.0
vscode-markdownlint|Dav|0.57.0
vscode-eslint|dba|3.0.10
xml|Dot|2.5.1
gitlens|eam|16.0.4
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
go|gol|0.42.1
better-cpp-syntax|jef|1.27.1
vscode-peacock|joh|4.2.2
cmake-language-support-vscode|jos|0.0.9
json2csv|kha|1.0.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.13.9
csharp|ms-|2.55.29
dotnet-maui|ms-|1.5.34
vscode-dotnet-runtime|ms-|2.2.3
vscodeintellicode-csharp|ms-|2.2.3
remote-containers|ms-|0.392.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
powershell|ms-|2024.4.0
remote-explorer|ms-|0.4.3
vs-keybindings|ms-|0.2.1
vscode-serial-monitor|ms-|0.13.1
vsliveshare|ms-|1.0.5941
js-beautify-extentions|nes|1.0.6
material-icon-theme|PKi|5.14.1
java|red|1.37.0
segdo-script-language-service|Seg|0.0.1
markdown-preview-enhanced|shd|0.8.15
vscode-scss-formatter|sib|3.0.0
cmake|twx|0.0.17
segdomedia-gzip|und|0.0.2
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
markdown-all-in-one|yzh|3.6.2
linkerscript|Zix|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupyter:31046869
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
390bf810:31183120
5b1c1929:31184661

```

</details>

**Comment by Segdo** [comment]
Log output from Settings Sync:

```
2024-11-30 19:35:22.012 [info] Auto Sync: Triggered by Interval
2024-11-30 19:35:22.012 [info] Sync started.
2024-11-30 19:35:22.136 [info] Settings: No changes found during synchronizing settings.
2024-11-30 19:35:22.139 [info] Keybindings: No changes found during synchronizing keybindings.
2024-11-30 19:35:22.140 [info] Snippets: No changes found during synchronizing snippets.
2024-11-30 19:35:22.142 [info] Tasks: No changes found during synchronizing tasks.
2024-11-30 19:35:22.144 [info] GlobalState: No changes found during synchronizing ui state.
2024-11-30 19:35:22.192 [info] Extensions: No changes found during synchronizing extensions.
2024-11-30 19:35:22.193 [info] Profiles: No changes found during synchronizing profiles.
2024-11-30 19:35:22.194 [info] Sync done. Took 182ms
2024-11-30 19:40:22.205 [info] Auto Sync: Triggered by Interval
2024-11-30 19:40:22.205 [info] Sync started.
2024-11-30 19:40:22.313 [info] Settings: No changes found during synchronizing settings.
2024-11-30 19:40:22.315 [info] Keybindings: No changes found during synchronizing keybindings.
2024-11-30 19:40:22.317 [info] Snippets: No changes found during synchronizing snippets.
2024-11-30 19:40:22.319 [info] Tasks: No changes found during synchronizing tasks.
2024-11-30 19:40:22.321 [info] GlobalState: No changes found during synchronizing ui state.
2024-11-30 19:40:22.368 [info] Extensions: No changes found during synchronizing extensions.
2024-11-30 19:40:22.369 [info] Profiles: No changes found during synchronizing profiles.
2024-11-30 19:40:22.370 [info] Sync done. Took 166ms
2024-11-30 19:45:22.373 [info] Auto Sync: Triggered by Interval
2024-11-30 19:45:22.373 [info] Sync started.
2024-11-30 19:45:22.522 [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":401,"execution-id":"46bc1331-c088-46ad-876f-30633d41fab1","operation-id":"9aef118ea3a64bacb6f908e9dae95756"} Failed to verify user: jwt expired
2024-11-30 19:45:22.522 [info] Settings Sync auth token failed microsoft false Unauthorized
2024-11-30 19:45:22.522 [info] Auto Sync: Suspended until auth token is available.
2024-11-30 19:45:22.522 [info] Auto sync: Cancelled sync that is in progress
2024-11-30 19:45:22.522 [info] Auto Sync: Stopped
2024-11-30 19:45:22.522 [error] Unauthorized (UserDataSyncError) syncResource:unknown operationId:9aef118ea3a64bacb6f908e9dae95756: GET request 'https://vscode-sync.trafficmanager.net/v1/manifest' failed because of Unauthorized (401).
    at qh.D (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:104:22606)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qh.manifest (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:104:19954)
    at async vu.createSyncTask (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:104:121443)
    at async vf.I (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:111:9288)
    at async vf.H (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:111:8932)
2024-11-30 19:45:22.556 [info] Auto Sync: Triggered by Interval
2024-11-30 19:45:22.556 [info] Sync started.
2024-11-30 19:45:22.580 [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":401,"execution-id":"8740e310-2c9c-4f5d-ad03-510a7835105a","operation-id":"fd807908b3314650a331873c1f9678c6"} Failed to verify user: jwt expired
2024-11-30 19:45:22.580 [info] Settings Sync auth token failed microsoft true Unauthorized
2024-11-30 19:45:22.580 [info] Auto Sync: Suspended until auth token is available.
2024-11-30 19:45:22.580 [info] Auto sync: Cancelled sync that is in progress
2024-11-30 19:45:22.580 [info] Auto Sync: Stopped
2024-11-30 19:45:22.580 [error] Unauthorized (UserDataSyncError) syncResource:unknown operationId:fd807908b3314650a331873c1f9678c6: GET request 'https://vscode-sync.trafficmanager.net/v1/manifest' failed because of Unauthorized (401).
    at qh.D (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:104:22606)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qh.manifest (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:104:19954)
    at async vu.createSyncTask (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:104:121443)
    at async vf.I (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:111:9288)
    at async vf.H (file:///c:/Users/dmile/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-utility/sharedProcess/sharedProcessMain.js:111:8932)
```

**Comment by TylerLeonhardt** [comment]
Let's merge this with https://github.com/microsoft/vscode/issues/229456
