### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#234914]
I'm getting this in dev console. Based on git-blame at contentHoverStatusBar.ts:48, assigning to you  @aiday-mar 

Not sure how to repro, but should be traceable by code inspection.

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at rhi.add (lifecycle.ts:425:18)
    at qse.B (lifecycle.ts:497:22)
    at qse.addAction (contentHoverStatusBar.ts:48:8)
    at markerHoverParticipant.ts:239:23
```

![Image](https://github.com/user-attachments/assets/e7d5a8e0-eda1-4c1e-8ce3-2f41d2c30587)

Version: 1.96.0-insider
Commit: 275faf6f08b7aa50843f3c18406b4d5969784e52
Date: 2024-11-28T18:04:55.375Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by aiday-mar** [comment]
Hi may I ask you if you still see this? I see the following commit has fixed some issues with disposables recently: https://github.com/microsoft/vscode/commit/f80816ab8e21c65ed7f1f7e08ccdbffae63610c6#diff-47fbdb0b4f5d1fe782f01d11251329a0d7ece5cc8c8bab05c064e3c179ce5ce1

**Comment by ulugbekna** [comment]
@aiday-mar I don't this anymore; closing
