### ISSUE TITLE
potential listener LEAK detected, having 175 listeners already

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#235256]
```
event.ts:902 Error
    at xhi.create (event.ts:933:15)
    at HKe.q [as onDidChange] (event.ts:1140:34)
    at new <anonymous> (testingExplorerView.ts:510:32)
    at rJe.oc (testingExplorerView.ts:498:26)
    at rJe.getActionViewItem (testingExplorerView.ts:334:17)
    at hJe.getActionViewItem (viewPaneContainer.ts:604:34)
    at n.getActionViewItem (panecomposite.ts:145:34)
    at yfe.Qb (compositePart.ts:466:32)
    at Object.actionViewItemProvider (compositePart.ts:408:54)
    at Object.actionViewItemProvider (toolbar.ts:113:29)
```

I'm seeing a lot of this while trying to test https://github.com/microsoft/vscode/issues/210848#issuecomment-2499273293

**Comment by alexr00** [comment]
It's coming from this line:

https://github.com/microsoft/vscode/blob/aab1869b1a1381390c989f30a00f949721bbffa9/src/vs/workbench/contrib/testing/browser/testingExplorerView.ts#L510
