### ISSUE TITLE
Failed to download vscode server

### ISSUE THREAD

**Issue by epicwhale** [microsoft/vscode#236067]
Type: <b>Bug</b>

For bug reports please include the complete log output. (In the VS Code window: `F1` > `Dev Containers: Show Container Log`.)

[2024-12-13T10:28:56.423Z] Stop (1 ms): Run in container: test -d '/root/.vscode-server-insiders/bin/b425f4802fcbcccb11ad991208fa262c06255be3-insider'
[2024-12-13T10:28:56.423Z] Start: Run in container: test -d '/vscode/vscode-server-insiders/bin/linux-arm64/b425f4802fcbcccb11ad991208fa262c06255be3-insider'
[2024-12-13T10:28:56.424Z] 
[2024-12-13T10:28:56.424Z] 
[2024-12-13T10:28:56.424Z] Exit code 1
[2024-12-13T10:28:56.424Z] Stop (1 ms): Run in container: test -d '/vscode/vscode-server-insiders/bin/linux-arm64/b425f4802fcbcccb11ad991208fa262c06255be3-insider'
[2024-12-13T10:28:56.424Z] Installing VS Code Server for commit b425f4802fcbcccb11ad991208fa262c06255be3
[2024-12-13T10:28:56.424Z] Start: Downloading VS Code Server
[2024-12-13T10:28:56.424Z] b425f4802fcbcccb11ad991208fa262c06255be3 linux-arm64 insider
[2024-12-13T10:28:56.641Z] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:b425f4802fcbcccb11ad991208fa262c06255be3/server-linux-arm64/insider): HTTP 400 - Bad Request
[2024-12-13T10:28:56.641Z] Retrying to download VS Code Server.
[2024-12-13T10:28:56.662Z] Stop (238 ms): Downloading VS Code Server
[2024-12-13T10:28:56.664Z] Error: Server returned 400
    at G0 (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:637:18061)
    at Q7e.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1296:62801)

Extension version: 0.394.0
VS Code version: Code - Insiders 1.97.0-insider (Universal) (b425f4802fcbcccb11ad991208fa262c06255be3, 2024-12-13T05:04:19.453Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|64.00GB (1.66GB free)|
|Process Argv|--crash-reporter-id d48f9d6f-0571-4336-b478-887ae20fde19|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551cf:31179977
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
f8hc8238:30694864
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupyter:31046869
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
390bf810:31183120
5b1c1929:31184661

```

</details>

**Comment by joaomoreno** [comment]
It's on us: we added a `retry` that will kick way too soon and cause inconsistencies in the Release service.

**Comment by rzhao271** [comment]
Hi @joaomoreno, what are some verification steps for this issue?

**Comment by joaomoreno** [comment]
There's no good verification here, just code review.
