### ISSUE TITLE
UNRESPONSIVE extension host: 'github.copilot-chat'

### ISSUE THREAD

**Issue by jarshwah** [microsoft/vscode#236421]
Type: <b>Bug</b>

While editing code in python, the editor stops working for a period of time. Hitting ENTER does not create a newline, and sometimes I see the "Activating extension" notification pop each time I hit enter.

Pylance also stops responding as I'd expect it to.

After looking into the output logs, I find in the Extension Host logs:

```
2024-12-18 10:24:44.602 [warning] TextEditor is closed/disposed
2024-12-18 10:24:56.194 [warning] TextEditor is closed/disposed
2024-12-18 10:25:00.498 [warning] TextEditor is closed/disposed
2024-12-18 10:26:36.631 [warning] Edits from command pythonIndent.newlineAndIndent were not applied.
2024-12-18 10:26:36.631 [warning] Edits from command pythonIndent.newlineAndIndent were not applied.
2024-12-18 10:26:36.631 [warning] Edits from command pythonIndent.newlineAndIndent were not applied.
```

Then in the Window logs, it says "[warning] UNRESPONSIVE extension host: 'github.copilot-chat'"

```
2024-12-18 10:26:24.141 [warning] UNRESPONSIVE extension host: 'github.copilot-chat' took 95.16137343263061% of 2271.541ms, saved PROFILE here: 'file:///var/folders/vg/m2xdbbgs6p3974dhpnm73zgm0000gp/T/exthost-1c31cd.cpuprofile'
2024-12-18 10:29:45.721 [info] Extension host (LocalProcess pid: 49790) is unresponsive.
2024-12-18 10:29:46.094 [info] UNRESPONSIVE extension host: starting to profile NOW
2024-12-18 10:29:47.364 [info] Extension host (LocalProcess pid: 49790) is responsive.
2024-12-18 10:29:47.397 [error] 
	 at (anonymous) (file:///Users/josh/.vscode/extensions/github.copilot-chat-0.23.1/dist/extension.js:397:15149)
	 at B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:660)
	 at fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:850)
	 at (anonymous) (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:118878)
	 at B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:660)
	 at C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:771)
	 at fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:850)
	 at $onFileEvent (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:121271)
	 at S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115101)
	 at Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115015)
	 at M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113961)
	 at L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113042)
	 at (anonymous) (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112038)
	 at B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:660)
	 at fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:850)
	 at fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9408)
	 at (anonymous) (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13201)
	 at B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:660)
	 at fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:850)
	 at fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9408)
	 at (anonymous) (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11583)
	 at emit (node:events:465:44)
	 at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2863)
```

Attached is the cpuprofile

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|24.00GB (0.98GB free)|
|Process Argv|--crash-reporter-id 97addac9-f01a-4553-b901-fffadef6f51e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-icontheme-nomo-dark|be5|1.3.6
ruff|cha|2024.56.0
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.1
gitlens|eam|16.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.252.0
copilot-chat|Git|0.23.1
vsc-python-indent|Kev|1.18.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-scss|mrm|0.10.0
debugpy|ms-|2024.15.2024121701
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
sublime-keybindings|ms-|4.1.10
vsliveshare|ms-|1.0.5941
color-highlight|nau|2.8.0
vscode-yaml|red|1.15.0
command-variable|rio|1.66.0
LiveServer|rit|5.7.9
partial-diff|ryu|1.4.3
preview-vscode|sea|2.3.12
even-better-toml|tam|0.19.2
vcl|tho|0.1.2
shellcheck|tim|0.37.1
pdf|tom|1.2.2
errorlens|use|3.21.0
vscodeintellicode|Vis|1.3.2
vscode-icons|vsc|12.10.0
change-case|wma|1.0.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.17.7

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

[exthost-6dfddd.cpuprofile](https://github.com/user-attachments/files/18172497/exthost-6dfddd.cpuprofile)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, sorry you are running into this issue. 
Please can you disable all extensions except for the copilot extension(s) and try again to see if you can repro this.
If you do see a message such as the following `2024-12-18 10:26:24.141 [warning] UNRESPONSIVE extension host: 'github.copilot-chat' took 95.16137343263061% of 2271.541ms, saved PROFILE here: 'file:///var/folders/vg/m2xdbbgs6p3974dhpnm73zgm0000gp/T/exthost-1c31cd.cpuprofile'`,
then please do fine the `*.cpuprofile` file and attach that to this issue.
