### ISSUE TITLE
Packing of terminal-suggest fails on 'fs/promises' while building from source

### ISSUE THREAD

**Issue by anonhostpi** [microsoft/vscode#236831]
Does this issue occur when all extensions are disabled?: Yes/No

No, this is a build issue.

- VS Code Version: main branch
- OS Version: Windows and Ubunuto
- Node Version: 22

Steps to Reproduce:

1. clone repository
2. run `npm run watch-web` or `npm run watch`

```
 npm run watch-web

> code-oss-dev@1.97.0 watch-web
> node ./node_modules/gulp/bin/gulp.js watch-web

(node:8081) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[13:39:23] Using gulpfile /mnt/c/Users/xxxx/Documents/Repos/vscode/gulpfile.js
[13:39:23] Starting 'watch-web'...
[13:41:39] Finished packaging web extension configuration-editing with 0 errors.
[13:41:39] Finished packaging web extension css-language-features/client with 0 errors.
[13:41:39] Finished packaging web extension css-language-features/server with 0 errors.
[13:41:39] Finished packaging web extension emmet with 0 errors.
[13:41:39] Finished packaging web extension extension-editing with 0 errors.
[13:41:39] Finished packaging web extension git-base with 0 errors.
[13:41:39] Finished packaging web extension github-authentication with 0 errors.
[13:41:39] Finished packaging web extension html-language-features/client with 0 errors.
[13:41:39] Finished packaging web extension html-language-features/server with 0 errors.
[13:41:39] Finished packaging web extension ipynb with 0 errors.
[13:41:39] Finished packaging web extension ipynb with 0 errors.
[13:41:39] Finished packaging web extension json-language-features/client with 0 errors.
[13:41:39] Finished packaging web extension json-language-features/server with 0 errors.
[13:41:39] Finished packaging web extension markdown-language-features with 0 errors.
[13:41:39] Finished packaging web extension markdown-math with 0 errors.
[13:41:39] Finished packaging web extension media-preview with 0 errors.
[13:41:39] Finished packaging web extension merge-conflict with 0 errors.
[13:41:39] Finished packaging web extension microsoft-authentication with 0 errors.
[13:41:39] Finished packaging web extension npm with 0 errors.
[13:41:39] Finished packaging web extension references-view with 0 errors.
[13:41:39] Finished packaging web extension search-result with 0 errors.
[13:41:39] Finished packaging web extension simple-browser with 0 errors.
[13:41:39] Finished packaging web extension terminal-suggest with 1 errors.
[13:41:39] {
  moduleIdentifier: '/mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/ts-loader/index.js??ruleSet[1].rules[0].use[0]!/mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/mangle-loader.js??ruleSet[1].rules[0].use[1]!/mnt/c/Users/xxxxt/Documents/Repos/vscode/extensions/terminal-suggest/src/terminalSuggestMain.ts',
  moduleName: './src/terminalSuggestMain.ts',
  loc: '50:24-46',
  message: "Module not found: Error: Can't resolve 'fs/promises' in '/mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/terminal-suggest/src'",
  moduleId: 0,
  moduleTrace: [],
  details: "resolve 'fs/promises' in '/mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/terminal-suggest/src'\n" +
    '  Parsed request is a module\n' +
    '  using description file: /mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/terminal-suggest/package.json (relative path: ./src)\n' +
    "    Field 'browser' doesn't contain a valid alias configuration\n" +
    '    resolve as module\n' +
    "      /mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/terminal-suggest/src/node_modules doesn't exist or is not a directory\n" +
    "      /mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/terminal-suggest/node_modules doesn't exist or is not a directory\n" +
    '      looking for modules in /mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/node_modules\n' +
    "        /mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/node_modules/fs doesn't exist\n" +
    '      looking for modules in /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules\n' +
    "        /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/fs doesn't exist\n" +
    "      /mnt/c/Users/xxxx/Documents/Repos/node_modules doesn't exist or is not a directory\n" +
    "      /mnt/c/Users/xxxx/Documents/node_modules doesn't exist or is not a directory\n" +
    '      looking for modules in /mnt/c/Users/xxxx/node_modules\n' +
    "        /mnt/c/Users/xxxx/node_modules/fs doesn't exist\n" +
    "      /mnt/c/Users/node_modules doesn't exist or is not a directory\n" +
    "      /mnt/c/node_modules doesn't exist or is not a directory\n" +
    "      /mnt/node_modules doesn't exist or is not a directory\n" +
    "      /node_modules doesn't exist or is not a directory",
  stack: "ModuleNotFoundError: Module not found: Error: Can't resolve 'fs/promises' in '/mnt/c/Users/xxxx/Documents/Repos/vscode/extensions/terminal-suggest/src'\n" +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/Compilation.js:2109:28\n' +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/NormalModuleFactory.js:908:13\n' +
    '    at eval (eval at create (/mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)\n' +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/NormalModuleFactory.js:333:22\n' +
    '    at eval (eval at create (/mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)\n' +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/NormalModuleFactory.js:512:22\n' +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/NormalModuleFactory.js:150:10\n' +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/NormalModuleFactory.js:775:25\n' +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/NormalModuleFactory.js:992:8\n' +
    '    at /mnt/c/Users/xxxx/Documents/Repos/vscode/node_modules/webpack/lib/NormalModuleFactory.js:1121:5'
}
[13:41:39] Finished packaging web extension typescript-language-features with 0 errors.
[13:41:39] Finished packaging web extension typescript-language-features with 0 errors.
[13:41:39] Finished packaging web extension vscode-test-resolver with 0 errors.
```

**Comment by anonhostpi** [comment]
I wanted to confirm it wasn't my environments, so I spun up a windows 11 dev VM in Hyper-V. I installed python3.12 from the microsoft store, nvm for Windows, and git. Used nvm to install node 20 and node 22.

I tested both node versions. I'm getting the same build error from both.

**Comment by anonhostpi** [comment]
As I'm reviewing the source code, I don't think terminalSuggestMain.ts is supposed to be part of the VS Code for Web build...

**Comment by anonhostpi** [comment]
So looking over the git blame for the last 3 months, the source of the problem seems to be that the original version of the extension did not utilize fs at all:

https://github.com/microsoft/vscode/blob/dffafc6042e1426181fc34e99a2cd40ca4e09171/extensions/terminal-suggest/src/npmMain.ts

However, the current version does:

https://github.com/microsoft/vscode/blob/151ef3514e76629f4e7bf3951439b1e0dae0a6e5/extensions/terminal-suggest/src/terminalSuggestMain.ts#L7

Because watch-web packs all extensions with an extension-browser.webpack.config.js, the build errors out:

https://github.com/microsoft/vscode/blob/main/extensions/terminal-suggest/extension-browser.webpack.config.js

@meganrogge According to the git blame, this is your work. Care to add anything?

**Comment by anonhostpi** [comment]
This appears to be unique to 1.96, as this extension does not appear to exist for 1.95:

https://github.com/microsoft/vscode/tree/1.95.3/extensions/terminal-suggest

**Comment by anonhostpi** [comment]
This appears to be the breaking change:

https://github.com/microsoft/vscode/commit/3cd70ff9b3b4994b2e30fd413bd72bfb16f7ce1f

**Comment by anonhostpi** [comment]
These 2 changes appear to be when the web build was broken:

https://github.com/microsoft/vscode/blame/3cd70ff9b3b4994b2e30fd413bd72bfb16f7ce1f/extensions/terminal-suggest/src/terminalSuggestMain.ts

https://github.com/microsoft/vscode/blame/339a9707e0f5802be8f905976fdb30ce57a4caaa/extensions/terminal-suggest/src/terminalSuggestMain.ts

**Comment by Tyriar** [comment]
@meganrogge I think we need to tweak the package.json to say it's a workspace, not a UI extension. We could then likely remove some of the webpack stuff.

**Comment by Tyriar** [comment]
We've been shipping suggest for a long time now, this isn't an issue for us.
