### ISSUE TITLE
Suggest preview leaves trail even when suggest widget closed

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#236817]
Type: <b>Bug</b>

As title says. I can't reproduce it 100%, but it happens often and issue was with previous VS Code version as well, but it started probably like 2-3 months ago. I do believe it may be related to a leak (maybe it isn't disposed?). It only disappears if I change tabs and go back.

Setting: `"editor.suggest.preview": true`

Here is a screenshot to show about which part I'm talking about:

<img width="157" alt="Image" src="https://github.com/user-attachments/assets/f23d9c96-15e3-424a-b7ce-1ecb0d1529a1" />

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Darwin arm64 24.2.0

**Comment by svipas** [comment]
I managed to reproduce, and checked Console logs and found **4** exact logs:

```
[Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at Rhi.add (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:25:1553)
    at Kse.B (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:25:2120)
    at Kse.addAction (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:410:148820)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:463:9192
](lifecycle.ts:425)
```

Not sure how helpful this is, but as I assumed this is related to a leak. This was almost a fresh VS Code session with about 5 minutes of work.

**Comment by svipas** [comment]
<img width="253" alt="Image" src="https://github.com/user-attachments/assets/7a8e7674-2725-4f0e-8148-3f82c5560601" />

Okay so managed to catch it and it don't disappear unless I manually switch to other editor tab, but logs didn't show anything, so probably those above aren't related...

**Comment by RedCMD** [comment]
dup? https://github.com/microsoft/vscode/issues/235977
or still not fixed in latest insiders?

**Comment by hediet** [comment]
Thanks for reporting! Does it still reproduce in the latest stable release? Do you have repro steps?

**Comment by svipas** [comment]
@hediet I do think it is fixed, I do use inline completions for suggestions as well and I haven't seen "left trail" of ghost text anymore. Will let you know if I do see it again. Also, there are no repro steps :(
