### ISSUE TITLE
Linux Mint 1.11.1 - Extension library unreachable with http.proxy setting only in GUI. 

### ISSUE THREAD

**Issue by nullism** [Microsoft/vscode#24254]
**Version info:**

- VSCode Version: 1.11.1  ( `code_1.11.1-1491486998_amd64.deb` )
- OS Version: Linux Mint - Ubuntu 14.04 - x86_64 

**Steps to Reproduce:**

1. Be on a machine that requires a proxy, we'll say `my-proxy.example.com:80`.
2. Set the following user settings
    * `"http.proxy": "http://my-proxy.example.com:80"`
3. Test that the proxy works with code by installing via the command line:  
    ``` 
    :~$ code --install-extension AdamCaviness.theme-monokai-dark-soda
    Found 'AdamCaviness.theme-monokai-dark-soda' in the marketplace.
    Installing...
    Extension 'AdamCaviness.theme-monokai-dark-soda' v0.0.5 was successfully installed!
    ```
4. Run code via `:~$ code --verbose`
5. Try to search or install extensions using the UI. For example, `ext install python`. 
6. Observe that no information is displayed with Visual Studio code, but on the CLI the following error is shown:

```
[32413:0407/120533:INFO:CONSOLE(28)] "An unknown error occurred. Please consult the log for more details.", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
WARNING: Promise with no error callback:6
{ exception: 
   Error: net::ERR_ADDRESS_UNREACHABLE
       at Error (native),
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: 
      Error: net::ERR_ADDRESS_UNREACHABLE
          at Error (native),
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_ADDRESS_UNREACHABLE
    at Error (native)
[uncaught exception in main]: Error: net::ERR_ADDRESS_UNREACHABLE

Error: net::ERR_ADDRESS_UNREACHABLE
    at Error (native)
Error: net::ERR_ADDRESS_UNREACHABLE

Error: net::ERR_ADDRESS_UNREACHABLE
    at Error (native)
    at Timeout._onTimeout (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:15297)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[32413:0407/120535:INFO:CONSOLE(29)] "net::ERR_ADDRESS_UNREACHABLE

Error: net::ERR_ADDRESS_UNREACHABLE
    at Error (native): Error: net::ERR_ADDRESS_UNREACHABLE

Error: net::ERR_ADDRESS_UNREACHABLE
    at Error (native)
    at Timeout._onTimeout (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:15297)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[32413:0407/120550:INFO:CONSOLE(20)] "ApplicationInsights:Sender", source: /usr/share/code/resources/app/node_modules/applicationinsights/Library/Logging.js (20)
```

**Comment by joaomoreno** [comment]
#22214
