### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by ayman17** [Microsoft/vscode#24393]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|include-autocomplete|ajshort|0.0.2|
|code-gnu-global|austin|0.2.1|
|java-run|caolin|1.1.4|
|vscode-astyle|chiehyu|0.6.2|
|javadebugger|donjayamanne|0.0.2|
|jupyter|donjayamanne|1.0.0|
|python|donjayamanne|0.6.0|
|replace-smart-characters|DrMattSm|0.0.2|
|java-debug|DSnake|0.0.2|
|vscode-great-icons|emmanuelbeziat|1.1.47|
|eppz-code|eppz|1.0.36|
|javac-linter|faustinoaq|1.2.2|
|code-runner|formulahendry|0.6.15|
|vscode-javac|georgewfraser|0.0.31|
|CppSnippets|hars|0.0.7|
|code-template-replace|heekei|0.1.2|
|Python-autopep8|himanoa|1.0.2|
|beautify|HookyQR|1.0.2|
|hopscotch|idleberg|0.1.4|
|vscode-flake8|jaysonsantos|0.0.4|
|csharpextensions|jchannon|1.3.0|
|theme-material-theme|jprestidge|1.0.1|
|docomment|k--kato|0.0.14|
|clangcomplete|kube|0.0.6|
|live-code-runner|lablup|1.2.0|
|csharpfixformat|Leopotam|0.0.20|
|MagicPython|magicstack|1.0.9|
|vscode-clang|mitaki28|0.2.2|
|quicksnippet|mousetraps|0.0.1|
|cpptools|ms-vscode|0.10.5|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|java|redhat|0.1.0|
|python|tht13|0.2.3|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|
|python-extended-snippets|tushortz|0.0.1|
|cmake-tools|vector-of-bool|0.9.4|
|clang-format|xaver|1.2.1|;

---

Steps to Reproduce:

1.when open vcode this internal error expose
"[Info  - 9:09:10 AM] Connection closed
[Error - 9:09:10 AM] Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:87)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:203)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:139)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:49)
	... 11 more
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.javacs.JavaLanguageServer.initialize(JavaLanguageServer.java:59)
	... 16 more

[Error - 9:09:10 AM] Server initialization failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
"

**Comment by chrmarti** [comment]
Seems to be an extension using Java. Please try to narrow down which extension is causing it and open an issue with them.

**Comment by ayman17** [comment]
this error happened when _java language support_ extention is active and when i try to open .java file.
set **"java.home"** setting to jdk home but it don't work.

**Comment by chrmarti** [comment]
This issue was moved to georgewfraser/vscode-javac#45
