### ISSUE TITLE
Salsa does not flag ReferenceErrors in strict mode

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2450]
Testing #2218 

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

```javascript
"use strict";
                       // Assuming a global variable mistypedVariable exists
mistypedVaraible = 17; // this line throws a ReferenceError due to the 
                       // misspelling of variable
```

When I run it with node v0.12.7 I do get a `ReferenceError`:
```
c:\Alex\working_dir\salsa\strict.js:3
mistypedVaraible = 17; // this line throws a ReferenceError due to the
                 ^
ReferenceError: mistypedVaraible is not defined
    at Object.<anonymous> (c:\Alex\working_dir\salsa\strict.js:3:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I expect Salsa to flag as much as possible of runtime errors, including strict mode reference errors

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6652
