### ISSUE TITLE
NPE in selectBox.ts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#24584]
```
Cannot read property 'selectBackground' of undefined: TypeError: Cannot read property 'selectBackground' of undefined
    at new SelectBox (file:////Users/joao/Work/vscode/out/vs/base/browser/ui/selectBox/selectBox.js:26:44)
    at SwitchTerminalInstanceActionItem.SelectActionItem [as constructor] (file:////Users/joao/Work/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:542:31)
    at new SwitchTerminalInstanceActionItem (file:////Users/joao/Work/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalActions.js:352:32)
    at create (file:////Users/joao/Work/vscode/out/vs/base/common/types.js:163:14)
    at InstantiationService._createInstance (file:////Users/joao/Work/vscode/out/vs/platform/instantiation/common/instantiationService.js:142:43)
    at InstantiationService.createInstance (file:////Users/joao/Work/vscode/out/vs/platform/instantiation/common/instantiationService.js:70:29)
    at TerminalPanel.getActionItem (file:////Users/joao/Work/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:119:51)
    at PanelPart.CompositePart.actionItemProvider (file:////Users/joao/Work/vscode/out/vs/workbench/browser/parts/compositePart.js:331:51)
    at Object.actionItemProvider (file:////Users/joao/Work/vscode/out/vs/workbench/browser/parts/compositePart.js:297:74)
    at Object.actionItemProvider (file:////Users/joao/Work/vscode/out/vs/base/browser/ui/toolbar/toolbar.js:41:65)
```

![image](https://cloud.githubusercontent.com/assets/22350/24950208/87c27504-1f70-11e7-8cfb-05792ed84163.png)

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/24952177/04cdaf5e-1f77-11e7-8d02-5ea4c4b79b99.png)

**Comment by dbaeumer** [comment]
Verified by using select box in output and terminal pane.

**Comment by dbaeumer** [comment]
Opened https://github.com/Microsoft/vscode/issues/25619
