### ISSUE TITLE
Possible memory leak (not sure if VScode or extension)

### ISSUE THREAD

**Issue by hazzlewis** [Microsoft/vscode#24701]
- VSCode Version: 1.11.1
- OS Version: Windows 10.0.14393 Build 14393

Extensions:
- PHP IntelliSense Version: v1.1.5
- PHP Debug Version: v1.10.0

Keep hitting `Extension host terminated unexpectedly.` Errors after a short period of time. I'm not sure if this is a VSCode issue or an extension issue so here's my dev console output:

```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] (node:8108) Warning: Possible EventEmitter memory leak detected. 11 deploy.config.reloaded listeners added. Use emitter.setMaxListeners() to increase limitd.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] PHP process connected
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] 
VirtualAlloc() failed: [0x00000008] Not enough storage is available to process this command.


VirtualFree() failed: [0x000001e7] Attempt to access invalid address.


VirtualAlloc() failed: [0x00000008] Not enough storage is available to process this command.


VirtualFree() failed: [0x000001e7] Attempt to access invalid address.

PHP Fatal error:  Out of memory (allocated 1853882368) (tried to allocate 262144 bytes) in C:\Users\harry\.vscode\extensions\felixfbecker.php-intellisense-1.1.5\vendor\phpdocumentor\type-resolver\src\Types\Compound.php on line 54
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
index.js:5 [uncaught exception]: Error: write EPIPEonError @ index.js:5
index.js:5 Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:706:26)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at onwrite (_stream_writable.js:346:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:807:12)onError @ index.js:5
events.js:160 Uncaught Error: write EPIPE
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Extension host terminated unexpectedly. Please reload the window to recover.e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Extension host terminated unexpectedly. Code:  3  Signal:  null
```
Screenshot if its easier to read:
![image](https://cloud.githubusercontent.com/assets/20228401/25017882/37ea3cd4-207d-11e7-8f9e-2325e50b2ee0.png)

**Comment by jrieken** [comment]
cc @felixfbecker

**Comment by felixfbecker** [comment]
dupe https://github.com/felixfbecker/php-language-server/issues/344
