### ISSUE TITLE
a popup got stuck

### ISSUE THREAD

**Issue by refack** [Microsoft/vscode#24721]
- VSCode Version: Code - Insiders 1.11.0-insider (0b19861f31ed27160c8ea73e55e39dd0213814a6, 2017-03-28T10:48:32.966Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|python|donjayamanne|0.6.0|
|vscode-npm-script|eg2|0.1.9|
|code-runner|formulahendry|0.6.15|
|intellij-idea-keybindings|k--kato|0.2.10|
|MagicPython|magicstack|1.0.9|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|gerrit-vscode|tht13|0.4.1|
|python|tht13|0.2.3|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|;

---

Steps to Reproduce:

Not sure but I was editing a `ps1` file, I think it was around
```ps
  param( [string]$path-item )
```

When a popup got stuck
![2017-04-13-vscore-popup-stuck](https://cloud.githubusercontent.com/assets/96947/25025813/be9e7b7a-2071-11e7-8e8b-8d610310aae5.gif)

**Comment by jrieken** [comment]
@refack Can you reproduce this or was it a one off? Any change you can or did capture the out from dev tools (F1 > Toggle Developer Tools)?

**Comment by refack** [comment]
happened again (same senario editing a `ps1` file)
here's the HTML and console output https://gist.github.com/refack/1c8e0035adfcb52ef406bdb5d9834b53

**Comment by jrieken** [comment]
Thanks. Found this at the end @joaomoreno 

```
xtensionHost.ts:282 [Extension Host] undefined
shell.ts:476 Cannot read property 'row' of undefined: TypeError: Cannot read property 'row' of undefined
    at e.insertItemInDOM (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:1560)
    at file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:38:31964
    at Object.o [as each] (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:6:1580)
    at e.splice (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:38:31936)
    at file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:5126
    at Array.forEach (native)
    at e.splice (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:5097)
    at file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:14882
    at e.bufferEvents (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:12568)
    at e.splice (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:14838)e.onUnexpectedError @ shell.ts:476
3shell.ts:476 Cannot read property 'row' of undefined: TypeError: Cannot read property 'row' of undefined
    at e.removeItemFromDOM (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:1959)
    at file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:38:31592
    at Object.o [as each] (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:6:1580)
    at e.splice (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:38:31564)
    at file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:5126
    at Array.forEach (native)
    at e.splice (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:5097)
    at file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:14882
    at e.bufferEvents (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:31:12568)
    at e.splice (file:///D:/bin/dev/VSCode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:39:14838)
```

**Comment by ramya-rao-a** [comment]
@refack Does this still repro for you?

The error with callstack in https://github.com/Microsoft/vscode/issues/24721#issuecomment-294729099 hasnt occurred after 4/22/2017

**Comment by refack** [comment]
Trying...

**Comment by refack** [comment]
So 10 days no repro. Closing.
Thank you all.
