### ISSUE TITLE
Debugger won't start for PowerShell, Python, etc.

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#24891]
In relation to https://github.com/PowerShell/vscode-powershell/issues/682, I've been encountering some scenarios where the debugger hangs. However, I've reached a point in my VSCode session where the debugger simply will not start at all. Nothing new is showing up in the VSCode PowerShell Extension logs, when I attempt to start the debugger, so I am suspicious of VSCode itself having a transient error state in the debug adapter interface.

I've already tried restarting the PowerShell session, and PowerShell 6.0 is currently showing as active in the status bar, but no matter what, I can't start the debugger. I've tried opening different files to start the debugger, but no file will allow me to invoke the debugger. In fact, I can't even call the `Debug: Start Without Debugging` command from the Command Palette. The entire VSCode debugger seems to be hung. 

At the top of the VSCode window, the debug commands are visible, but are greyed out, and cannot be clicked on.

I opened the VSCode Developer Tools and found the following items in the console logs:

```
[Extension Host] powershell.exe started, pid: 72202, exe: /usr/local/bin/powershell
messageService.ts:126 Linter pylint is not installede.doShow @ messageService.ts:126
messageService.ts:126 The terminal process terminated with exit code: 1e.doShow @ messageService.ts:126
messageService.ts:126 The PowerShell session has terminated due to an error, would you like to restart it?e.doShow @ messageService.ts:126
shell.ts:475 Cannot read property 'forEach' of null: TypeError: Cannot read property 'forEach' of null
    at LanguageClient.stop (/Users/tsulli/.vscode/extensions/ms-vscode.powershell-0.12.2/node_modules/vscode-languageclient/lib/main.js:312:24)
    at vscode.window.onDidCloseTerminal.terminal (/Users/tsulli/.vscode/extensions/ms-vscode.powershell-0.12.2/out/session.js:251:47)
    at e.invoke (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:16423)
    at e.fire (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:20054)
    at e.$acceptTerminalClosed (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354635)
    at t.e.handle (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:277319)
    at s (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:135077)
    at h (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:135754)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:475
index.js:36 [uncaught exception]: TypeError: Cannot read property 'focus' of nullonError @ index.js:36
index.js:39 TypeError: Cannot read property 'focus' of null
    at HTMLDivElement.<anonymous> (terminalPanel.ts:195)onError @ index.js:39
terminalPanel.ts:195 Uncaught TypeError: Cannot read property 'focus' of null
index.js:36 [uncaught exception]: TypeError: Cannot read property 'focus' of nullonError @ index.js:36
index.js:39 TypeError: Cannot read property 'focus' of null
    at HTMLDivElement.<anonymous> (terminalPanel.ts:195)onError @ index.js:39
terminalPanel.ts:195Uncaught TypeError: Cannot read property 'focus' of null
messageService.ts:126The terminal process terminated with exit code: 1e.doShow @ messageService.ts:126
shell.ts:475Cannot read property 'forEach' of null: TypeError: Cannot read property 'forEach' of null
    at LanguageClient.stop (/Users/tsulli/.vscode/extensions/ms-vscode.powershell-0.12.2/node_modules/vscode-languageclient/lib/main.js:312:24)
    at vscode.window.onDidCloseTerminal.terminal (/Users/tsulli/.vscode/extensions/ms-vscode.powershell-0.12.2/out/session.js:251:47)
    at e.invoke (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:16423)
    at e.fire (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:20054)
    at e.$acceptTerminalClosed (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354635)
    at t.e.handle (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:277319)
    at s (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:135077)
    at h (/Users/tsulli/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:135754)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:475
extensionHost.ts:284[Extension Host] powershell.exe started, pid: 72541, exe: /usr/local/bin/powershell
extensionHost.ts:284[Extension Host] powershell.exe started, pid: 73236, exe: /usr/local/bin/powershell
extensionHost.ts:284[Extension Host] powershell.exe started, pid: 73331, exe: /usr/local/bin/powershell
messageService.ts:126Debug adapter process has terminated unexpectedlye.doShow @ messageService.ts:126
extensionHost.ts:284[Extension Host] powershell.exe started, pid: 75254, exe: /usr/local/bin/powershell
extensionHost.ts:284[Extension Host] powershell.exe started, pid: 76925, exe: /usr/local/bin/powershell
messageService.ts:126Cannot read property 'toLowerCase' of undefinede.doShow @ messageService.ts:126
messageService.ts:126Cannot read property 'toLowerCase' of undefined
```

/cc @daviwil 

Cheers,
Trevor Sullivan

**Comment by isidorn** [comment]
@pcgeek86 Thanks for the stack trace however it only shows the powershell debugger has crashed and that should be reported in the powershell extension repository
As for vscode being in a bad state after a crash we would need precise reproducable steps in order to investigate this further.
Also can you also reproduce this with vscode insiders? How about when debugging node programs?
