### ISSUE TITLE
scripts/npm.sh install fail

### ISSUE THREAD

**Issue by rihdus** [Microsoft/vscode#25317]
Hi devs, trying to build the source code on my macbook.
- tried npm cache clean
- removed all global packages
  - `npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm`
  - http://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally
- updated xcode and ran it once to install any updated components
- installed `Command Line Tools for Xcode 8.3.2`

and didn't find a similar issue on google.

Any help is much appreciated.
Thanks.

- VSCode Version: 1.12.0
- OS Version: macOS 10.12.3 (16D32)
- Kernel Version: Darwin 16.4.0

```
$ node -v
v6.9.4

$ npm -v
4.5.0

$ python --version
Python 2.7.12

$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Steps to Reproduce:

1. From vscode repo root run `sh scripts/npm.sh install`

#### logs
```
sh scripts/npm.sh install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.

> code-oss-dev@1.12.0 preinstall /Volumes/HAKO/devel/wk/project/vscode
> node build/npm/preinstall.js


> typechecker@2.0.8 preinstall /Volumes/HAKO/devel/wk/project/vscode/node_modules/.staging/typechecker-2156fa1f
> node ./cyclic.js

npm WARN prefer global coffee-script@1.12.5 should be installed with -g
npm WARN prefer global js-beautify@1.5.10 should be installed with -g

> fsevents@0.3.8 install /Volumes/HAKO/devel/wk/project/vscode/node_modules/fsevents
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Invalid version number: "electronVersion": "1.6.6",
gyp ERR! stack     at getNodeDir (/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:72:25)
gyp ERR! stack     at Object.callback (/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:44:7)
gyp ERR! stack     at Object.<anonymous> (/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:469:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/rihdus/.nvm/versions/node/v6.9.4/bin/node" "/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/HAKO/devel/wk/project/vscode/node_modules/fsevents
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 

> oniguruma@6.1.1 install /Volumes/HAKO/devel/wk/project/vscode/node_modules/oniguruma
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Invalid version number: "electronVersion": "1.6.6",
gyp ERR! stack     at getNodeDir (/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:72:25)
gyp ERR! stack     at Object.callback (/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:44:7)
gyp ERR! stack     at Object.<anonymous> (/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:469:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/rihdus/.nvm/versions/node/v6.9.4/bin/node" "/Users/rihdus/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/HAKO/devel/wk/project/vscode/node_modules/oniguruma
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
code-oss-dev@1.12.0 /Volumes/HAKO/devel/wk/project/vscode

... 
... 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 (node_modules/windows-foreground-love):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-foreground-love@0.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-mutex@0.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXXX/.electron-gyp/.npm/_logs/2017-04-25T17_49_35_921Z-debug.log

```

**Comment by bpasero** [comment]
@rihdus can you try again, maybe there was a network issue. I cannot reproduce just now, but I see https://github.com/electron/electron/issues/9284

**Comment by rihdus** [comment]
@bpasero `npm install electron --save` correctly installed `"electron": "^1.6.6"` in a test project.

But the vscode install is still failing with the exactly the same output

Could it be a problem with my python or C/C++ toolchain ?

```
$ python --version
Python 2.7.12

$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by bpasero** [comment]
I am not sure, I have the same python version. I suggest to post this on StackOverflow where questions should go.
