### ISSUE TITLE
Not opening anymore

### ISSUE THREAD

**Issue by skarllot** [Microsoft/vscode#2562]
The VSCode on my machine stopped to open from one day to another, without updating VSCode.

**A JavaScript error occurred in the main process**
```
Uncaught Exception:
Error: watch ENOSPC
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1247:11)
    at Object.fs.watch (fs.js:1273:11)
    at t.e.registerWatchers (/home/fgodoy/bin/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:18607)
    at t.e (/home/fgodoy/bin/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:17858)
    at new t (/home/fgodoy/bin/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:20553)
    at Object.<anonymous> (/home/fgodoy/bin/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:20864)
    at e._invokeFactory (/home/fgodoy/bin/VSCode-linux-x64/resources/app/out/vs/loader.js:4:13773)
    at e._complete (/home/fgodoy/bin/VSCode-linux-x64/resources/app/out/vs/loader.js:4:14012)
    at e.resolveDependency (/home/fgodoy/bin/VSCode-linux-x64/resources/app/out/vs/loader.js:4:15066)
```

**Comment by skarllot** [comment]
Maybe related to update of nodejs.x86_64 package from 4.2.5-1nodesource.fc22 to 4.2.6-1nodesource.fc22.

**Comment by skarllot** [comment]
Appears to be related to inotify limit, maybe changed after system update.

The VSCode could verify and notify user as the Android Studio does:

External file changes sync may be slow: The current inotify(7) watch limit is too low. [More details](https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit). (show balloon

**Comment by Tyriar** [comment]
This is a known issue https://code.visualstudio.com/Docs/supporting/FAQ#_linux-error-enospc

Try this:

```
fs.inotify.max_user_watches=16384
```

**Comment by skarllot** [comment]
VSCode message could be more friendly.

**Comment by Tyriar** [comment]
Totally agree https://github.com/Microsoft/vscode/issues/50 :)

**Comment by bpasero** [comment]
See https://code.visualstudio.com/Docs/supporting/FAQ#_linux-error-enospc

**Comment by brenthuisman** [comment]
@bpasero: that unfortunately doesn't resolve the issue. I can start Code once, any successive attempts again result in ENOSPC.
