### ISSUE TITLE
ViewModelDecorations: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26106]
Found this in my dev logs, I was playing around with enabling editor DND, references and such but not sure how to repro:

```
"Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at ViewModelDecorations.onModelDecorationsChanged (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/viewModel/viewModelDecorations.js:42:47)
    at ViewModel._onEvents (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:293:42)
    at ViewModel.onEvents (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:171:18)
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/viewModel/viewModelImpl.js:82:90
    at safeInvoke1Arg (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/eventEmitter.js:246:20)
    at OrderGuaranteeEventEmitter._emitEvents (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/eventEmitter.js:229:17)
    at OrderGuaranteeEventEmitter.EventEmitter._emitCollected (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/eventEmitter.js:189:18)
    at OrderGuaranteeEventEmitter.EventEmitter.endDeferredEmit (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/eventEmitter.js:173:22)
    at Model.TextModelWithDecorations.changeDecorations (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModelWithDecorations.js:149:36)
    at Model.TextModelWithDecorations.deltaDecorations (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModelWithDecorations.js:191:25)"
```

**Comment by bpasero** [comment]
This is now our number 1 error telemetry hit (e.g. see https://github.com/Microsoft/vscode/issues/26905)

**Comment by bpasero** [comment]
I do not understand how the commit can fix this.

![image](https://cloud.githubusercontent.com/assets/900690/26594911/e113c990-4569-11e7-9d50-de7198b638f8.png)

**Comment by rebornix** [comment]
Stupid blind check on property key. Actually we should guard the object.

<img width="497" alt="screen shot 2017-06-01 at 1 25 00 pm" src="https://cloud.githubusercontent.com/assets/876920/26699206/bed43c60-46cd-11e7-8ca9-f49e0830d0d6.png">
