### ISSUE TITLE
Install bootstrap framework package through bower in terminal failed 

### ISSUE THREAD

**Issue by hh54188** [Microsoft/vscode#26392]
- VSCode Version:  1.12.1
- OS Version: Windows_NT 6.1.7601 x64

Steps to Reproduce:

1. bower install bootstrap --save

Error information:

```
bower bootstrap#*              extract archive.tar.gz
bower bootstrap#*                EPERM EPERM: operation not permitted, unlink 'C:\Users\lgy\AppData\Local\Temp\lgy-PC-lgy\bower\ca4c50b905dc21ea17a10
549a6f5944f-116-CIoQ7c\archive.tar.gz.1061013984'

Stack trace:
Error: EPERM: operation not permitted, unlink 'C:\Users\lgy\AppData\Local\Temp\lgy-PC-lgy\bower\ca4c50b905dc21ea17a10549a6f5944f-116-CIoQ7c\archive.t
ar.gz.1061013984'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\lgy\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 6.2.1
OS: Windows_NT 6.1.7601 x64
```

**Comment by egamma** [comment]
@hh54188 the error message above is not from VS Code. Does `bower install bootstrap --save` work when you run it in the same folder outside of the VS Code terminal?

**Comment by egamma** [comment]
Cannot act on this issue given the current information. Closing the issue, please reopen when you provide additional information.
