### ISSUE TITLE
Gulp Compile-Build Error For Missing darwin/Credits.rtf When Building on Linux

### ISSUE THREAD

**Issue by ScottHaney** [Microsoft/vscode#26552]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04 Docker Container

## Issue

Building vscode on a Linux machine should not require an OSX resource to be present

## Steps to Reproduce

1. Start with the source code for version 1.12.1 (using the commit hash from product.json)
2. Install npm modules
3. Run `gulp compile-build` in the main directory
4. The following error appears:

~~~
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/vscode/resources/darwin/Credits.rtf'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (/home/vscode/build/gulpfile.vscode.js:109:70)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at require.sync.forEach.f (/home/vscode/gulpfile.js:76:17)
    at Array.forEach (native)
    at Object.<anonymous> (/home/vscode/gulpfile.js:76:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
~~~

5. If an empty Credits.rtf file is created at the location mentioned in the error message the `gulp compile-build` command proceeds successfully

**Comment by joaomoreno** [comment]
Remove `darwinCredits` from your `product.json`.
