### ISSUE TITLE
Settings: Model is disposed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26617]
Found this while running "out of sources", not sure how I was getting into that state, but I had settings opened and probably closed it. Might also be related to snippets?

```
[23396:0514/094110.853577:INFO:CONSOLE(273)] "Model is disposed!: Error: Model is disposed!
    at Model.TextModel._assertNotDisposed (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModel.js:56:23)
    at Model.TextModelWithDecorations.changeDecorations (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModelWithDecorations.js:141:18)
    at InsertSnippetController.stopAll (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/contrib/snippet/common/snippetController.js:287:24)
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/contrib/snippet/common/snippetController.js:154:23
    at CallbackList.invoke (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
    at CodeEditor.CommonCodeEditor.setModel (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/commonCodeEditor.js:147:36)
    at TextFileEditor.clearInput (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/browser/editors/textFileEditor.js:189:31)
    at SideBySidePreferencesWidget.clearInput (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:341:48)
    at PreferencesEditor.clearInput (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:122:46)", source: file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js (273)

```

**Comment by sandy081** [comment]
Looks to me related to Snippets

@jrieken FYI

**Comment by jrieken** [comment]
it's the old code. it's not in use anymore
