### ISSUE TITLE
Error: The mode has failed while tokenizing the input.

### ISSUE THREAD

**Issue by darrenkenny** [Microsoft/vscode#26724]
- VSCode Version: Code - Insiders 1.13.0-insider (613724d43b4d50f6052bbb8007447ca96e687f26, 2017-05-16T06:10:52.652Z)
- OS Version: Linux x64 4.1.12-94.1.8.el7uek.x86_64
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Edit any file

You should then see an error popup, and you see this on the window gaining focus:
```
The mode has failed while tokenizing the input.
```

and in the dev console I see:

```
 /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/code-insiders/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node): Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/code-insiders/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (file:///usr/share/code-insiders/resources/app/out/vs/loader.js:4:10596)
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules/oniguruma/lib/oniguruma.js:69:4)
e.onUnexpectedError @ shell.ts:485
```

Looking at libstdc++.so.6 I don't appear to have anything higher than 3.4.19 on my Oracle Linux 7 machine.

Any suggestions on how to resolve this?

**Comment by darrenkenny** [comment]
Looks like this has been resolved in the latest overnight build:

- VSCode Version: Code - Insiders 1.13.0-insider (78636af970837c2c9c70ccccbaf4ea4ab0a3a03b, 2017-05-16T09:49:36.263Z)

Sorry for the noise.

**Comment by wanghaiyang1930** [comment]
I have the same problem in Debian 7 and the VSCode Version: 1.13.0

**Comment by peterhinners** [comment]
I also have the same issue with Debian 7. Have tried installing newest code and also newest code-insiders.
