### ISSUE TITLE
VScode throw an error on code "try {throw new Error(); } catch (e) {......}" when launch debugger

### ISSUE THREAD

**Issue by Bluesnoweagle** [Microsoft/vscode#26761]
- VSCode Version:1.12.2
- OS Version:win10 64

Steps to Reproduce:
Hi, I am a node.js developer from China.There is problem when I launch VScode debugger after I installed "Q" or "bluebird" module.It will stop and throw an error(Just error,nothing else info) on code "try {throw new Error(); } catch (e) {......}", The "Q" and "bluebird" have the samilar code .But if I type "Node index.js" in CMD to launch my application,It works well.
And this is the error stacks:
发生异常: Error
Error
    at Object.<anonymous> (E:\Google\Nodejs\angulr\node_modules\.3.5.0@bluebird\js\release\util.js:378:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\Google\Nodejs\angulr\node_modules\.3.5.0@bluebird\js\release\promise.js:14:12)
    at Object.<anonymous> (E:\Google\Nodejs\angulr\node_modules\.3.5.0@bluebird\js\release\bluebird.js:9:36)

1.Install Q or "bluebird" module
2.Type code "var Q=require('q')" or "var Promise = require('bluebird')"
3.launch debugger
![qq 20170516234714](https://cloud.githubusercontent.com/assets/26517950/26115455/9ea13e58-3a92-11e7-86c8-6727692f64a2.png)

**Comment by roblourens** [comment]
Do you have the "Break on All Exceptions" box checked? It will cause the debugger to break on exceptions, even if they are caught.
