### ISSUE TITLE
1.12.2 compiled on Windows 7 does not show sidebar, window empty

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#26935]
- VSCode Version: 1.12.2 (checked out from tag "1.12.2")
- OS Version: Windows 7 x64

- Visual Studio 2015 update 3
- Node.js: 7.9.0 (compiled from source)
- Python 2.7.1 (32-bit)

Steps to Reproduce:

1. Execute following commands:

```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

set PYTHON=C:\Program Files (x86)\Python271\python.exe

set PATH=%PATH%;C:\Program Files\7-Zip


npm.cmd config set loglevel silly

mkdir tmp

npm.cmd config set cache tmp --global

npm.cmd cache clean

scripts\npm install
```

The above execution seems to work fine, ending with:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32
npm verb exit [ 0, true ]
npm info ok
```

2. Try regenerating `monaco.d.ts`:

```
node_modules\.bin\gulp watch
```

3. Compile app:

```
node_modules\.bin\gulp vscode-win32
```

Result:

VSCode shows empty window, no sidebar (the one that pops up after a second or two after stargin the app), menu is visible, but selecting any option in it does not seem to have any effect.

I start vscode by runnning `bin\code-oss.cmd` script. 

The above method worked just fine for me with previous `1.11.2` version.

**UPDATE**

Running dev version produces this error:

```
C:\Acme\Dev\projects\vscode1.12>scripts\code.bat
[15:43:36] Using gulpfile C:\Acme\Dev\projects\vscode1.12\gulpfile.js
[15:43:36] Starting 'clean-electron'...
[15:43:36] Finished 'clean-electron' after 2.91 ms
[15:43:36] Starting 'electron'...
[15:43:40] Finished 'electron' after 3.83 s
[15:43:45] Using gulpfile C:\Acme\Dev\projects\vscode1.12\gulpfile.js
[15:43:45] Starting 'clean-electron'...
[15:43:45] Finished 'clean-electron' after 68 ms
[15:43:45] Starting 'electron'...
[15:43:49] Finished 'electron' after 3.84 s

[8108:0519/154353.910:INFO:CONSOLE(201)] "Loading "gc-signals" failed", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (201)
[8108:0519/154353.912:INFO:CONSOLE(202)] "Detail: ", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (202)
[8108:0519/154353.912:INFO:CONSOLE(204)] "Error: The module '\\?\C:\Acme\Dev\projects\vscode1.12\node_modules\gc-signals\build\Release\gcsignals.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Acme\Dev\projects\vscode1.12\node_modules\gc-signals\src\index.js:8:18)
    at Object.<anonymous> (C:\Acme\Dev\projects\vscode1.12\node_modules\gc-signals\src\index.js:67:3)", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (204)
[8108:0519/154353.913:INFO:CONSOLE(206)] "Here are the modules that depend on it:", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (206)
[8108:0519/154353.913:INFO:CONSOLE(207)] "vs/workbench/api/node/mainThreadHeapService", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (207)
```

**Comment by Tyriar** [comment]
> NODE_MODULE_VERSION 50. This version of Node.js requires
> NODE_MODULE_VERSION 53. Please try re-compiling or re-installing

This normally means you need to delete `node_modules` and run `scripts\npm.bat install`
