### ISSUE TITLE
Jump to definition doesn't work for React component tags

### ISSUE THREAD

**Issue by iddan** [Microsoft/vscode#27022]
- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Import a component from another file and use it in a JavaScriptReact file
2. cmd-click the component tag name

**Comment by mjbvz** [comment]
I suspect this may be https://github.com/Microsoft/TypeScript/issues/15814

Can you please try collecting the typescript server trace to see if this is the case:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Reproduce the issue
4. Go to the output panel and share the output from the TypeScript section

Also, please share a minimal code example that demonstrates this issue. Thanks

**Comment by iddan** [comment]
scenario: Trying to cmd-click EntityResult tag name 

code:
```JSX
import EntityResult from 'components/search/results/EntityResult';

const PersonResult = ({ id, fields, viewMode, permissionLevel, highlightedFields }) => {
  const address = get(fields, 'addresses.address', {});
  const highlighted = highlightedFields.map((highlightedField) => get(fields, highlightedField));
  const dateOfBirth = fields.dateOfBirth ? moment(fields.dateOfBirth) : null;
  const dateOfDeath = fields.dateOfDeath ? moment(fields.dateODeath) : null;
  const dateOfBirthString = dateOfBirth ? dateOfBirth.format('DD-MM-Y') : '';
  const dateOfDeathString = dateOfDeath ? dateOfDeath.format('DD-MM-Y') : '';
  const age = moment().diff(dateOfBirth, 'years');

  return (
    <EntityResult highlightedFields={ highlighted } type="person" id={ id } entityName="Person" viewMode={ viewMode } permissionLevel={ permissionLevel }>
     </EntityResult>
   );
};
```

trace:
```
[Trace - 3:05:56 PM] Sending request: definition (27). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/iddan/mexico/app/components/search/results/PersonResult.js",
    "line": 16,
    "offset": 13
}
[Trace - 3:05:56 PM] Response received: definition (27). Request took 2 ms. Success: false . Message: Error processing request. Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at createDefinitionInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63549:53)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63440:25)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71648:38)
    at IOSession.Session.getDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76797:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76338:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77640:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77669:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:78850:27)
[Error - 3:05:56 PM] 'definition' request failed with error.
Error processing request. Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at createDefinitionInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63549:53)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63440:25)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71648:38)
    at IOSession.Session.getDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76797:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76338:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77640:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77669:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:78850:27)
[Trace - 3:05:56 PM] Sending request: quickinfo (28). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/iddan/mexico/app/components/search/results/PersonResult.js",
    "line": 16,
    "offset": 13
}
[Trace - 3:05:56 PM] Response received: quickinfo (28). Request took 3 ms. Success: true 
Result: {
    "kind": "alias",
    "kindModifiers": "",
    "start": {
        "line": 16,
        "offset": 6
    },
    "end": {
        "line": 16,
        "offset": 18
    },
    "displayString": "import EntityResult",
    "documentation": "",
    "tags": []
}
[Trace - 3:05:57 PM] Sending request: definition (29). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/iddan/mexico/app/components/search/results/PersonResult.js",
    "line": 16,
    "offset": 13
}
[Trace - 3:05:57 PM] Response received: definition (29). Request took 1 ms. Success: false . Message: Error processing request. Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at createDefinitionInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63549:53)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63440:25)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71648:38)
    at IOSession.Session.getDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76797:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76338:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77640:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77669:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:78850:27)
[Error - 3:05:57 PM] 'definition' request failed with error.
Error processing request. Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at createDefinitionInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63549:53)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:63440:25)
    at Object.getDefinitionAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71648:38)
    at IOSession.Session.getDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76797:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76338:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77640:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77649:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77669:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:78850:27)
```

**Comment by mjbvz** [comment]
Thanks. This bug actually looks like https://github.com/Microsoft/TypeScript/issues/15813

I just tested this with `typescript@next` and do not see the error anymore. Please [give it a try](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) and let me know if you still run into this issue. We plan on picking up TS 2.4 next month
