### ISSUE TITLE
build failed when running 'scripts\npm install' on windows server 2012 

### ISSUE THREAD

**Issue by 1767083130** [Microsoft/vscode#2706]
```
20472 silly doParallel update-linked 0
20473 silly doSerial install 0
20474 silly doSerial postinstall 0
20475 verbose unlock done using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-625755f64a2a6594.lock for D:\开发环境\vscode\vscode-0.10.6\node_modules\.staging
20476 silly executeActions Finishing
20477 silly rollbackFailedOptional Starting
20478 silly rollbackFailedOptional Finishing
20479 silly runTopLevelLifecycles Starting
20480 silly install runTopLevelLifecycles
20481 silly preinstall Code@0.10.6 D:\开发环境\vscode\vscode-0.10.6\Code-aa2789c2
20482 info lifecycle Code@0.10.6~preinstall: Code@0.10.6
20483 verbose lifecycle Code@0.10.6~preinstall: unsafe-perm in lifecycle true
20484 verbose lifecycle Code@0.10.6~preinstall: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\开发环境\vscode\vscode-0.10.6\node_modules\.bin;C:\Program Files (x86)\PHP\v5.4;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files\MySQL\MySQL Server 5.1\bin;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_05\jre\bin;C:\Users\Administrator\AppData\Roaming\npm;D:\android\开发环境\adt-bundle-windows-x86_64-20140702\sdk\platform-tools;D:\android\adt\sdk\tools;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Java\jdk1.8.0_05\bin;C:\Program Files\Java\jdk1.8.0_05\jre\bin;C:\Users\Administrator\AppData\Roaming\npm;D:\android\adt\sdk\platform-tools;D:\android\sdk\tools;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files (x86)\Microsoft VS Code\bin
20485 verbose lifecycle Code@0.10.6~preinstall: CWD: D:\开发环境\vscode\vscode-0.10.6
20486 silly lifecycle Code@0.10.6~preinstall: Args: [ '/d /s /c', 'node build/npm/preinstall.js' ]
20487 silly lifecycle Code@0.10.6~preinstall: Returned: code: 1  signal: null
20488 info lifecycle Code@0.10.6~preinstall: Failed to exec preinstall script
20489 warn optional Skipping failed optional dependency /chokidar/fsevents:
20490 warn notsup Not compatible with your operating system or architecture: fsevents@0.3.8
20491 verbose stack Error: Code@0.10.6 preinstall: `node build/npm/preinstall.js`
20491 verbose stack Exit status 1
20491 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
20491 verbose stack     at emitTwo (events.js:87:13)
20491 verbose stack     at EventEmitter.emit (events.js:172:7)
20491 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
20491 verbose stack     at emitTwo (events.js:87:13)
20491 verbose stack     at ChildProcess.emit (events.js:172:7)
20491 verbose stack     at maybeClose (internal/child_process.js:818:16)
20491 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
20492 verbose pkgid Code@0.10.6
20493 verbose cwd D:\开发环境\vscode\vscode-0.10.6
20494 error Windows_NT 6.1.7601
20495 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
20496 error node v4.2.4
20497 error npm  v3.5.2
20498 error code ELIFECYCLE
20499 error Code@0.10.6 preinstall: `node build/npm/preinstall.js`
20499 error Exit status 1
20500 error Failed at the Code@0.10.6 preinstall script 'node build/npm/preinstall.js'.
20500 error Make sure you have the latest version of node.js and npm installed.
20500 error If you do, this is most likely a problem with the Code package,
20500 error not with npm itself.
20500 error Tell the author that this fails on your system:
20500 error     node build/npm/preinstall.js
20500 error You can get information on how to open an issue for this project with:
20500 error     npm bugs Code
20500 error Or if that isn't available, you can get their info via:
20500 error     npm owner ls Code
20500 error There is likely additional logging output above.
20501 verbose exit [ 1, true ]
```

**Comment by jrieken** [comment]
> 20489 warn optional Skipping failed optional dependency /chokidar/fsevents:
20490 warn notsup Not compatible with your operating system or architecture: fsevents@0.3.8
20491 verbose stack Error: Code@0.10.6 preinstall: node build/npm/preinstall.js

looks like unsupported platform

**Comment by bpasero** [comment]
@1767083130 is this with NPM 3 or 2? Can you delete the line here [1] and then try npm install again?

[1] https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/package.json#L13

**Comment by 1767083130** [comment]
@bpasero  NPM 3.5.2 and the file doesn't exist the line.

{
	"name": "vscode-api-tests",
	"description": "API tests for VS Code",
	"version": "0.0.1",
	"publisher": "vscode",
	"private": true,
	"engines": {
		"vscode": "*"
	},
	"scripts": {
		"compile": "node ./node_modules/vscode/bin/compile -watch -p ./",
		"vscode:prepublish": "node ../../node_modules/gulp/bin/gulp.js --gulpfile ../../gulpfile.plugins.js compile-plugin:vscode-api-tests ./tsconfig.json"
	},
	"devDependencies": {
		"typescript": "^1.6.2",
		"vscode": "next"
	}
}

**Comment by bpasero** [comment]
Ok good, seems unrelated to the vscode-api-tests then. Moving to Joao if he knows what is going on, unsupported platform might be it.

**Comment by joaomoreno** [comment]
Well, we build Code in a Windows Server 2012 machine, so it can't be that.

@1767083130 can you try installing Node 4 and building with that instead?

**Comment by 1767083130** [comment]
after I upgrated npm and nodejs,the error has gone away.vscode is excellent.thanks for your help

**Comment by soichih** [comment]
@1767083130 Thanks
