### ISSUE TITLE
Automated smoke test terminal test fails when using a multi-line $PS1

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27604]
#27456 

OS: Linux
Command: `npm test -- --latest /usr/share/code-insiders/bin/code-insiders --stable /usr/share/code/bin/code`

```
    Integrated Terminal

      2) opens terminal, runs 'echo' and verifies the output

...

  2) Smoke Test Suite Integrated Terminal opens terminal, runs 'echo' and verifies the output:

      AssertionError: '~/dev/Microsoft/vscode/test/smoke/test_data/vscode-smoketest-express @master[1⇡] ?' == 'test'
      + expected - actual

      -~/dev/Microsoft/vscode/test/smoke/test_data/vscode-smoketest-express @master[1⇡] ?
      +test
      
      at Context.<anonymous> (out/tests/integrated-terminal.js:46:24)
      at next (native)
      at fulfilled (out/tests/integrated-terminal.js:8:58)
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

This is my `$PS1`:

```
\n\[\033[01;34m\]\w\[\033[00m\]$(__git_prompt)\033[0m\n\[\033[1;31m\]❯ \[\033[0m\]
```

I'm assuming it's failing due to the `\n` at the start.

**Comment by roblourens** [comment]
Removing 'bug', I don't think a test failure needs verification.

**Comment by michelkaporin** [comment]
@roblourens This test failure was caused due to missing implementation in smoke test to tackle the problem @Tyriar faced, not because it failed due to a bug in VS Code. It would be still great to verify it.

**Comment by Tyriar** [comment]
It now passes on the same machine :+1:
