### ISSUE TITLE
Unresponsive if open as root

### ISSUE THREAD

**Issue by jaychand** [Microsoft/vscode#2774]
jay@jay-virtual-machine:~/Desktop$ sudo code
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[VS Code]: detected unresponsive
[VS Code]: detected unresponsive
jay@jay-virtual-machine:~/Desktop$ events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at /usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:20:9562
    at t (/usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:11:18479)
    at Object.callOnRemote (/usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:11:18413)
    at Object.onUnexpectedPluginHostError (/usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:4:9764)
    at e.unexpectedErrorHandler (/usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:19:17071)
    at e.onUnexpectedError (/usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:7:17878)
    at Object.u [as onUnexpectedError] (/usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:7:15312)
    at process.<anonymous> (/usr/local/vscode/resources/app/out/vs/workbench/node/pluginHostProcess.js:20:9853)
    at emitOne (events.js:82:20)

**Comment by Tyriar** [comment]
This should be fixed as of the current stable release.
