### ISSUE TITLE
Explorer API samples do not work

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#27807]
(this should really be in the vscode-extension-samples repo... but putting here for visiblity)

windows
insiders 1.13.0-insiders 3a6eda

to repro:
- clone `https://github.com/Microsoft/vscode-extension-samples.git`
- `cd tree-explorer-sample`, run `npm install`
- open folder in VS Code Insiders
- Press `F5` to run

Result:

![image](https://cloud.githubusercontent.com/assets/1487073/26663660/04dea1b0-4641-11e7-85e6-fc217d4d5db9.png)

In console:

``` bash
Extension 'octref.dep' uses PROPOSED API which is subject to change and removal without notice.
Activating extension `octref.dep` failed: Class extends value undefined is not a constructor or null.
Activating extension `octref.dep` failed:  Class extends value undefined is not a constructor or null
Here is the error stack:  TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (d:\src\vscode-extension-samples\tree-explorer-sample\out\src\nodeDependencies.js:75:32)
    at Object.<anonymous> (d:\src\vscode-extension-samples\tree-explorer-sample\out\src\nodeDependencies.js:90:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.$.Q.o._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:410256)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by sandy081** [comment]
@chrisdias There were API changes done during testing and I was also updating the samples using the API to use the latest API. Since you are running the extension with insiders which does not have all changes, extensions are broken.

All tree sample extensions should work with the latest insiders. Sorry for that.

Thanks
