### ISSUE TITLE
Shared process died

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2785]
I don't know how but the shared process died. See stack traces below. This results in very wired behavior for:

- the currently opened rendered: all commands talking to the shared process end in endless progress (for example install extensions)
- a newly opened Windows shows quite some error messages all talking about the extension host not available. However the extension host dies because the shared process is not available

IMO we should have code that detects that the shared process went down and restart it.

```
connect ENOENT \\.\pipe\Code - Alpha-4a1acf-shared-sock: Error: connect ENOENT \\.\pipe\Code - Alpha-4a1acf-shared-sock
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)e.onUnexpectedError @ workbench.main.js:111
workbench.main.js:88 [Plugin Host] Uncaught Exception:  ,Error: connect ENOENT \\.\pipe\Code - Alpha-4a1acf-shared-sock(anonymous function) @ workbench.main.js:88
workbench.main.js:88 [Plugin Host] WARNING: Promise with no error callback:3
workbench.main.js:88 [Plugin Host] Object
2workbench.main.js:88 [Plugin Host] Uncaught Exception:  ,Error: connect ENOENT \\.\pipe\Code - Alpha-4a1acf-shared-sock(anonymous function) @ workbench.main.js:88
workbench.main.js:88 [Plugin Host] Uncaught Exception:  Error: got message before big handler attached!(anonymous function) @ workbench.main.js:88
workbench.main.js:88 [Plugin Host] Error: got message before big handler attached!
    at Object.d.handle (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:23883)
    at process.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\node\pluginHostProcess.js:20:25415)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)(anonymous function) @ workbench.main.js:88
2workbench.main.js:88 [Plugin Host] Uncaught Exception:  ,Error: connect ENOENT \\.\pipe\Code - Alpha-4a1acf-shared-sock(anonymous function) @ workbench.main.js:88
workbench.main.js:88 [Plugin Host] Uncaught Exception:  Error: got message before big handler attached!(anonymous function) @ workbench.main.js:88
workbench.main.js:88 [Plugin Host] Error: got message before big handler attached!
    at Object.d.handle (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:23883)
    at process.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\node\pluginHostProcess.js:20:25415)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)(anonymous function) @ workbench.main.js:88
workbench.main.js:88 [Plugin Host] Uncaught Exception:  Error: got message before big handler attached!

Error: got message before big handler attached!
    at Object.d.handle (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:23883)
    at process.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\node\pluginHostProcess.js:20:25415)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by dbaeumer** [comment]
I am marking this as important since this happens reproducible for me when opening a second window with the latest build.

**Comment by dbaeumer** [comment]
Even switching the folder in an open instance fails  now

**Comment by dbaeumer** [comment]
Actually looking at this with a process monitoring tools shows the following for switching a workspace folder:

- starting VSCode. Everything is ok and shared process is up and running
- switching to another folder: somehow during this the shared process goes down and never comes up again. As a result VSCode can't operate on the switched workspace.

**Comment by bpasero** [comment]
Smells a bit like https://github.com/Microsoft/vscode/issues/762 to me

**Comment by bpasero** [comment]
(at least https://github.com/Microsoft/vscode/issues/762#issuecomment-171714102)

**Comment by dbaeumer** [comment]
Did not see that again.
