### ISSUE TITLE
[IPC Library: Search] TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28293]
- VSCode Version: 1.14 (insiders)
- OS Version: macOS

Steps to Reproduce:

1. vscode workspace
2.search for `openFileFolderPicker|openFilePicker|openFolderPicker` regex search

```
[IPC Library: Search] TypeError: Cannot read property 'then' of null
    at RipgrepParser.<anonymous> (/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/search/node/ripgrepTextSearch.js:64:25)
    at emitOne (events.js:96:13)
    at RipgrepParser.emit (events.js:188:7)
    at RipgrepParser.onResult (/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/search/node/ripgrepTextSearch.js:260:18)
    at RipgrepParser.handleDecodedData (/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/search/node/ripgrepTextSearch.js:197:30)
    at RipgrepParser.handleData (/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/search/node/ripgrepTextSearch.js:168:18)
    at Socket.<anonymous> (/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/search/node/ripgrepTextSearch.js:83:37)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

```

**Comment by roblourens** [comment]
I think the glob.ts change here: https://github.com/Microsoft/vscode/commit/dd9ebe1d6eed63a29a87a87b887cb78b2205a860, parseToAsync will now return 'null' instead of `Promise.as(null)`. cc @mattbierner
