### ISSUE TITLE
vscode not launching

### ISSUE THREAD

**Issue by nickkolok** [Microsoft/vscode#28424]
$ ./scripts/code.sh
[14331:0610/174041.006599:INFO:CONSOLE(201)] "Loading "gc-signals" failed", source: file:///home/nickolaus/git/vscode/out/vs/loader.js (201)
[14331:0610/174041.006739:INFO:CONSOLE(202)] "Detail: ", source: file:///home/nickolaus/git/vscode/out/vs/loader.js (202)
[14331:0610/174041.007118:INFO:CONSOLE(204)] "Error: The module '/home/nickolaus/git/vscode/node_modules/gc-signals/build/Release/gcsignals.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nickolaus/git/vscode/node_modules/gc-signals/src/index.js:8:18)
    at Object.<anonymous> (/home/nickolaus/git/vscode/node_modules/gc-signals/src/index.js:67:3)", source: file:///home/nickolaus/git/vscode/out/vs/loader.js (204)
[14331:0610/174041.007337:INFO:CONSOLE(206)] "Here are the modules that depend on it:", source: file:///home/nickolaus/git/vscode/out/vs/loader.js (206)
[14331:0610/174041.007403:INFO:CONSOLE(207)] "vs/workbench/api/node/mainThreadHeapService", source: file:///home/nickolaus/git/vscode/out/vs/loader.js (207)

**Comment by nickkolok** [comment]
Ubuntu 12.04 LTS
Node v7.10.0
Only gray empty window is shown.

**Comment by serge-io** [comment]
You may need to recompile the modules.
seeing at the error it tells you that you may need to try npm install alternative nom rebuild.
 _NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using npm rebuild ornpm install)._
**see also**
https://github.com/Microsoft/vscode/issues/15553

**Comment by nickkolok** [comment]
Cloning into empty repo ad reinstalling vscode helped, thanks.
