### ISSUE TITLE
Word Wrap and word wrap toggle no longer working when screen reader is detected

### ISSUE THREAD

**Issue by cutecycle** [Microsoft/vscode#28473]
- VSCode Version: 1.13.0
- OS Version: Windows 10 Home

Steps to Reproduce:
I'm not sure... this happened after weeks of word Wrap working fine. This is reproducible with all extensions on and off. It persists between uninstall and reinstall as well. 

1. "editor.wordWrap": on,
2. Turning it off and using alt-Z and the menu all have the same result: no word wrap.
![image](https://user-images.githubusercontent.com/12169942/27015060-78dbe0ec-4ed3-11e7-8216-7216f07e96fb.png)

**Comment by wsmelton** [comment]
You likely will need to include the logs as the template issue noted. I can't reproduce this one, although I am on Windows 10 Pro.

**Comment by cutecycle** [comment]
ah, sorry: as in, include the console output from developer tools?
`keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  terminal.run
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  terminal.stop
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  terminal.open
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  terminal.toggle
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
extensionHost.ts:297 [Extension Host] Congratulations, your extension "terminal" is now active!
2extensionHost.ts:297 [Extension Host] TypeError: Cannot read property 'isEqual' of undefined
    at ModeHandler.<anonymous> (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:499:58)
    at Generator.next (<anonymous>)
    at C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:7:71
    at __awaiter (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:3:12)
    at ModeHandler.handleSelectionChange (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:453:16)
    at Object.promise (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:408:37)
    at TaskQueue.<anonymous> (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\taskQueue.js:27:32)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\taskQueue.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
5extensionHost.ts:297 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:297
2extensionHost.ts:297 [Extension Host] onDidChangeConfiguration
extensionHost.ts:297 [Extension Host] invalid value for set cursor position. This is probably bad?
extensionHost.ts:297 [Extension Host] onDidChangeConfiguration
extensionHost.ts:297 [Extension Host] error.stack
2extensionHost.ts:297 [Extension Host] TypeError: Cannot read property 'match' of undefined
    at Function.immediateMatchingBracket (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\common\matching\matcher.js:130:123)
    at _vimState.editor.edit.edit (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:1055:76)
    at e.edit (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:302000)
    at ModeHandler.<anonymous> (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:1045:49)
    at Generator.next (<anonymous>)
    at C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:7:71
    at __awaiter (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:3:12)
    at ModeHandler.executeCommand (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:995:16)
    at ModeHandler.<anonymous> (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:741:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\cutecycle\.vscode\extensions\vscodevim.vim-0.8.5\out\src\mode\modeHandler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
extensionHost.ts:297 [Extension Host] onDidChangeConfiguration`

**Comment by ramya-rao-a** [comment]
Cant repro this.

@cutecycle Did you try disabling all extensions? In your logs above there are quite errors from a few extensions.

![image](https://user-images.githubusercontent.com/16890566/27052565-e73df61a-4f6e-11e7-8fec-f4df39e1c379.png)

cc @rebornix

**Comment by alexandrudima** [comment]
@cutecycle In 1.13 we have done some optimizations for VS Code such that it works better with Screen Readers. One of the things we do when we detect that a Screen Reader is attached is that we turn off word wrapping, as the wrapping points cannot be communicated properly to the Screen Readers.

From your screenshot, it appears that on your machine VS Code enters this state (via the "Screen Reader Detected" status bar). You can read more about it in [our release notes](https://code.visualstudio.com/updates/v1_13#_screen-reader-detected).

Do you use any Screen Reader software or other software that may be using the same low-level OS APIs as Screen Readers? In any case, you can correct our behaviour by hovering over the status bar entry and following the instructions (use `editor.accessibilitySupport: "off"`), but I would like to know what software on your machine triggers that Electron detects a Screen Reader is attached.

**Comment by cutecycle** [comment]
![image](https://user-images.githubusercontent.com/12169942/27107456-13d8feca-5066-11e7-80e8-8eeb030805a5.png)

I do remember at some point installing NV Reader but then uninstalling it... I'm not sure what to do there, but editor.accessibilitySupport off worked!

![image](https://user-images.githubusercontent.com/12169942/27107681-5a1f9d2a-5067-11e7-9ca1-6f38ecffdb8d.png)

**Comment by ardalis** [comment]
I have no screen readers installed but my system today says "Screen Reader detected" and word wrapping isn't working. I'll use the editor.accessibilitySupport: "off" setting to fix the issue but I'm not sure what prompted the screen reader detection to kick in suddenly.

**Comment by alexandrudima** [comment]
@ardalis Do you perhaps have other software that is acting like a Screen Reader. i.e. using the same OS APIs that a Screen Reader would use to communicate with windows / input boxes / etc ?

**Comment by ardalis** [comment]
Nothing I'm aware of.

(looks at Code now after having been running it last few hours without installing/uninstalling anything)

It is no longer claiming Screen Reader Detected. I have no idea why it's changed.

**Comment by cutecycle** [comment]
For me I had installed but then uninstalled some sort of screen reader from Ninite? NVDA or something? But that screen reader detection still showed that I had one on
