### ISSUE TITLE
Channel closed error

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#28502]
- VSCode Version: from master
- OS Version: Windows

Steps:

- Execute a task without bringing the terminal to front.
- After the task has finished bring the terminal panel to front

I get:
```
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:689:36
    at Promise_ctor.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at TerminalInstance.layout (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:687:32)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:66:19
    at Array.forEach (native)
    at TerminalPanel.layout (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:65:53)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/compositePart.js:217:35
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/browser/parts/compositePart.js:210:51
```

**Comment by dbaeumer** [comment]
I looked into this a little and discovered two things:

- the _process is not set to null in _onPtyProcessExit
- even if _process !== null writing to the child process might fail since the process could have been finished and the exit event not yet processed in VS Code.

I made the following changes:

```ts
	public layout(dimension: Dimension): void {
		const terminalWidth = this._evaluateColsAndRows(dimension.width, dimension.height);
		if (!terminalWidth) {
			return;
		}
		if (this._xterm) {
			this._xterm.resize(this._cols, this._rows);
			this._xterm.element.style.width = terminalWidth + 'px';
		}
		this._processReady.then(() => {
			if (this._process) {
				// The child process could aready be terminated
				try {
					this._process.send({
						event: 'resize',
						cols: this._cols,
						rows: this._rows
					});
				} catch (error) {
					// We tried to write to a closed pipe / channel.
					if (error.code !== 'EPIPE' && error.code !== 'ERR_IPC_CHANNEL_CLOSED') {
						throw(error);
					}
				}
			}
		});
	}
```

and

```ts
	private _onPtyProcessExit(exitCode: number): void {
		// Prevent dispose functions being triggered multiple times
		if (this._isExiting) {
			return;
		}

		this._isExiting = true;
		this._process = null;
		let exitCodeMessage: string;

``` 
Let me know if it is ok for you that I push these.

**Comment by Tyriar** [comment]
@dbaeumer perfect! :ok_hand:
