### ISSUE TITLE
[build-windows] Error running scripts\code.bat

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#28607]
- VSCode Version: insider 24c9b09925...
- OS Version: Windows 10 (64bit)

Steps to Reproduce:

1. Run `scripts\npm.bat install` then `npm run watch`  
2. Run .\scripts\code.bat

What happens?
A new electron window is opened but vscode doesn't properly run and outputs errors:

```
{ Error: Cannot find module './build/Release/keymapping'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (E:\Docs\Dev\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at NativeBinding._init (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:61:18)
    at KeyboardLayoutMonitor.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\out\vs\code\electron-main\keyboard.js:27:30)
    at CodeApplication.registerListeners (E:\Docs\Dev\vscode\out\vs\code\electron-main\app.js:136:55) code: 'MODULE_NOT_FOUND' }
[14816:0613/114719.748:INFO:CONSOLE(201)] "Loading "gc-signals" failed", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (201)
```

More errors follow.

**Comment by joaomoreno** [comment]
Please provide the full npm install log. You'll find errors there.

**Comment by warpdesign** [comment]
@joaomoreno You mean the log of the log I have when running `scripts\npm.bat install`

**Comment by joaomoreno** [comment]
Yes.

**Comment by warpdesign** [comment]
I did not get any errors running the script. Here is the log I had after running it again:

```
> code-oss-dev@1.14.0 preinstall E:\Docs\Dev\vscode
> node build/npm/preinstall.js


> code-oss-dev@1.14.0 postinstall E:\Docs\Dev\vscode
> node build/npm/postinstall.js


> vscode-extensions@0.0.1 postinstall E:\Docs\Dev\vscode\extensions
> node ./postinstall

up to date in 0.672s
up to date in 7.591s

> vscode-colorize-tests@0.0.1 postinstall E:\Docs\Dev\vscode\extensions\vscode-colorize-tests
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: *
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

up to date in 8.152s

> json@0.1.0 postinstall E:\Docs\Dev\vscode\extensions\json
> cd server && npm install

up to date in 0.73s
up to date in 2.216s
up to date in 0.352s
up to date in 0.413s
up to date in 1.515s
up to date in 0.586s
up to date in 0.499s
up to date in 0.579s

> css@0.1.0 postinstall E:\Docs\Dev\vscode\extensions\css
> cd server && npm install

up to date in 0.639s
up to date in 2.18s

> html@0.1.0 postinstall E:\Docs\Dev\vscode\extensions\html
> cd server && npm install

up to date in 0.772s
up to date in 2.036s
up to date in 1.548s
up to date in 0.463s
up to date in 0.464s
up to date in 0.38s
up to date in 1.128s

> emmet@0.0.1 postinstall E:\Docs\Dev\vscode\extensions\emmet
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.10.0
Found minimal version that qualifies engine range: 1.10.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/1.10.0/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

up to date in 16.687s
up to date in 0.436s
up to date in 0.302s

> code-oss-dev-build@1.0.0 postinstall E:\Docs\Dev\vscode\build
> npm run compile


> code-oss-dev-build@1.0.0 compile E:\Docs\Dev\vscode\build
> tsc

up to date in 13.843s
up to date in 124.652s
```

**Comment by joaomoreno** [comment]
Clean the whole repo and start over: `git clean -xfd .` and then `scripts\npm.bat install`. That full log will have an error.

**Comment by warpdesign** [comment]
I am getting this error when running `scripts\npm.bat install`:

```
npm ERR! Cannot read property 'find' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicolas\.npm-electron\_logs\2017-06-14T12_01_26_047Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.14.0 postinstall: `node build/npm/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-oss-dev@1.14.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicolas\.npm-electron\_logs\2017-06-14T12_01_29_372Z-debug.log
```

**Comment by joaomoreno** [comment]
Can you just send me the **full** log?

**Comment by aeschli** [comment]
I'm not able to reproduce in the html client and server folders (using npm 5.0.3)
