### ISSUE TITLE
Unhandled error in debug adapter: TypeError: params.args[0].value.match is not a function

### ISSUE THREAD

**Issue by romanlab** [Microsoft/vscode#28604]
- VSCode Version: Code - Insiders 1.13.0-insider (9a107453944f25e6019b08615e20d63545584855, 2017-06-05T18:12:37.367Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.4|
|gitlens|eamodio|4.1.1|
|node-module-intellisense|leizongmin|1.3.0|
|Go|lukehoban|0.6.62|
|vscode-journal|pajoma|0.5.0|
|vscode-sql-beautify|sensourceinc|0.0.4|;

---

Steps to Reproduce:

1. Run this code(node 8.1) in debug - even a single file debug:
```
let counter = 0;
while (counter < 1000) {
  counter += 1;
  console.log(counter);
}
```
this is the result in debug console:

```
Debugger listening on ws://127.0.0.1:30210/82045de6-f1c3-4673-9dd7-f9e69b41cbf3
Debugger attached.
******** Unhandled error in debug adapter: TypeError: params.args[0].value.match is not a function
    at NodeDebugAdapter.onConsoleAPICalled (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebugAdapter.js:272:104)
    at Client.chrome.Runtime.onConsoleAPICalled.params (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:167:63)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.processMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/noice-json-rpc/lib/noice-json-rpc.js:64:18)
    at LoggingSocket.Client.socket.on.message (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/noice-json-rpc/lib/noice-json-rpc.js:28:46)
    at emitTwo (events.js:111:20)
    at LoggingSocket.emit (events.js:191:7)
    at Receiver.ontext (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/ws/lib/WebSocket.js:841:10)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/ws/lib/Receiver.js:536:18

```

**Comment by romanlab** [comment]
seems to be fixed in the latest update.
