### ISSUE TITLE
Rename symbol broken

### ISSUE THREAD

**Issue by jmoore315** [Microsoft/vscode#28651]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|recent-files|junv|1.1.0|
|graphql-for-vscode|kumar-harsh|1.4.1|
|graphql|mquandalle|0.1.2|;

---

Steps to Reproduce:

1. Rename symbol in a block of text (right click -> rename symbol)
2. Enter new name
3. Press enter
4. Following error message appears at the top of the screen and symbol rename has not worked
![image](https://user-images.githubusercontent.com/3791103/27097514-4fce304a-5029-11e7-96fb-f03532e53e6e.png)

**Comment by mjbvz** [comment]
Can you please provide a code example of the symbol you are trying to rename

**Comment by jmoore315** [comment]
Update: 
was going to add a code sample, but then I tested copying a file where rename was not working, and renaming works in the copied file. This behavior occurs for all files I've tried (attempting to rename a symbol in the original file results in the above error, but renaming works in the copied file

Not sure how vs code stores indexes of files, but maybe my indexes have been corrupted

**Comment by mjbvz** [comment]
If you have having trouble putting together a minimal example,  also try looking at the logs:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Reproduce the issue
3. Open the output panel and look at the `TypeScript` section.  Look for error messages around the `rename` event

**Comment by jmoore315** [comment]
Log output:
`[Trace  - 2:35:03 PM] Response received: rename (19). Request took 1 ms. Success: false . Message: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:73032:23)
    at IOSession.Session.getProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77136:42)
    at IOSession.Session.getRenameLocations (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77154:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76536:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77836:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77827:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77836:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77856:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79040:27)
    at emitOne (events.js:96:13)
[Error  - 2:35:03 PM] 'rename' request failed with error.`

**Comment by mjbvz** [comment]
If you fully close and then reopen the file, does that resolve the issue? Also, are you able to share the complete logs from a session where this occurs?

**Comment by jmoore315** [comment]
Closing the file then restarting VS code resolved the issue **if that is the only file open**. Once I open another file, rename symbol breaks again (both in the newly opened file and in the first file I opened). Note - the file contents itself are independent of the issue. 

Here is the full session log (opening vs code with no files open, successful symbol rename in 1st opened file, failed symbol rename upon opening 2nd file): https://pastebin.com/tpbzhNeb

**Comment by mjbvz** [comment]
Interesting. It looks like typescript is somehow loosing track of the file or the project it is associated with. To get a better understanding of what is going wrong, can you also please try collecting the TS Server logs:


1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VSCode
1. Reproduce the issue
1. Run the `Open TSServer log File` command and view the `tsserver.log` file

If you can share the log file I can take a look through them to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
