### ISSUE TITLE
Markdown previews not working / Electron; getOwnerBrowserWindow errors

### ISSUE THREAD

**Issue by Squibs** [Microsoft/vscode#28749]
- VSCode Version: Code - Insiders 1.14.0-insider (fda3ed38449fea27b97698ad0950c2870bf6afaa, 2017-06-14T05:13:12.994Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

# Steps to Reproduce:

These were from a clean install of VSCode Insiders. I do not have any extensions installed, as I thought maybe they were causing it. But after uninstalling and removing any extensions I have, the previews continued to not work and these errors continued to show up.

1. Open Help > Release Notes; or Any markdown file preview; or any Extension Details.
2. Markdown will not display.

![image](https://user-images.githubusercontent.com/2145187/27155192-3aa804a6-5115-11e7-9af6-ba32550db714.png)

Sidebar content not loading as a result, have to close and reopen sidebar multiple times before anything is displayed in the sidebar.

## Additional getOwnerBrowserWindow errors:

1. With any markdown preview open.
2. Close or resize the side bar.
3. Numerous amounts of errors are generated.

![image](https://user-images.githubusercontent.com/2145187/27155266-90e50616-5115-11e7-9639-bb39732390b0.png)

```
[uncaught exception]: Error: Could not call remote function 'getOwnerBrowserWindow'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'getOwnerBrowserWindow'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
onError @ index.js:41
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:188
window.onerror @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:124
i.globals.onerror @ errorTelemetry.ts:64
dispatchEvent @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\web-view\web-vie…:175
onElementResize @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\web-view\web-vie…:159

```

```
Error: Could not call remote function 'getOwnerBrowserWindow'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'getOwnerBrowserWindow'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:234:13)
    at Object.remoteMemberFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:118:18)
    at t.layout (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2003878)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:85337
    at Array.forEach (native)
    at t.layout (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:85308)
    at t.layoutEditor (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3137162)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3136742
    at Array.forEach (native)
    at t.layoutContainers (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3136720)
onError @ index.js:44
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:188
window.onerror @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:124
i.globals.onerror @ errorTelemetry.ts:64
dispatchEvent @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\web-view\web-vie…:175
onElementResize @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\web-view\web-vie…:159

```

```
Uncaught Error: Could not call remote function 'getOwnerBrowserWindow'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'getOwnerBrowserWindow'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at callFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:234:13)
    at Object.remoteMemberFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:118:18)
    at t.layout (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2003878)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:85337
    at Array.forEach (native)
    at t.layout (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:85308)
    at t.layoutEditor (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3137162)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3136742
    at Array.forEach (native)
    at t.layoutContainers (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3136720)
metaToValue @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:234
remoteMemberFunction @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\api\remote.js:118
t.layout @ webview.ts:268
(anonymous) @ extensionEditor.ts:735
t.layout @ extensionEditor.ts:735
t.layoutEditor @ editorGroupsControl.ts:2040
(anonymous) @ editorGroupsControl.ts:2014
t.layoutContainers @ editorGroupsControl.ts:2013
t.layoutControl @ editorGroupsControl.ts:1984
t.layout @ editorGroupsControl.ts:1889
t.layout @ editorPart.ts:1242
e.layout @ layout.ts:497
e.layout @ workbench.ts:873
e.layout @ shell.ts:470
(anonymous) @ shell.ts:437
(anonymous) @ builder.ts:579
dispatchEvent @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\web-view\web-vie…:175
onElementResize @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\web-view\web-vie…:159
```

**Comment by mjbvz** [comment]
Thanks. This was caused by a url encoding issue with windows paths. Should be fixed in tomorrow's insiders build
