### ISSUE TITLE
Error when running integration-tests

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#28865]
Run `scripts/test-integration` and while the test don't fail the error below shows:
```
[81855:0616/101253.891145:INFO:CONSOLE(85)] "Cannot read property 'getContainer' of undefined: TypeError: Cannot read property 'getContainer' of undefined
    at EditorGroupsControl.hide (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorGroupsControl.js:365:41)
    at EditorPart.doHideEditor (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:468:52)
    at EditorPart.doCloseGroup (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:448:18)
    at EditorPart.doCloseActiveEditor (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:431:22)
    at EditorPart.doCloseEditors (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:550:22)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:501:64
    at Array.forEach (native)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:501:24
    at Object.notifySuccess [as _notify] (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:852:30)", source: file:///Users/jrieken/Code/vscode/out/vs/workbench/services/message/browser/messageService.js (85)
    ✓ registerTextDocumentContentProvider, empty doc (54ms)
```

**Comment by bpasero** [comment]
Yeah I noticed this too and pushed a fix that should take care of it: https://github.com/Microsoft/vscode/commit/d3c2ba364264db396d4eed1e9b27b8f8c223ffce
