### ISSUE TITLE
Cannot click "Submit a bug" in latest insiders on Linux

### ISSUE THREAD

**Issue by AlanRosenthal** [Microsoft/vscode#28897]
`Version 1.14.0-insider
Commit 73015a5e052e6de8ecd60eed2670bea81fad8cac
Date 2017-06-16T05:10:46.035Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0`
On Ubuntu 16.04 x64

Step 1: Click "Submit a bug"
Step 2: Observe "Cannot read property 'length' of undefined
Step 3: Think about the irony

`Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at t.generateExtensionTable (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:431361)
    at t.generateNewIssueUrl (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:431030)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:430521
    at Object.g [as _notify] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:57201)
    at Object.enter (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:60775)
    at n.Class.derive._creator._run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:62603)
    at n.Class.derive._creator._completed (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:62044)
    at Object.g [as _notify] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:57201)
    at Object.enter (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:60775)
    at n.Class.derive._oncancel._run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:62603)
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ actionRegistry.ts:156
done @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
e.doRequest.n.Promise.t.handlers.(anonymous function) @ ipc.ts:246
e.onMessage @ ipc.ts:319
(anonymous) @ ipc.ts:206
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:188
readableAddChunk @ _stream_readable.js:176
Readable.push @ _stream_readable.js:134
onread @ net.js:551`

**Comment by ramya-rao-a** [comment]
Weird, doesn't repro in Mac. @Tyriar can you check this out?

**Comment by roblourens** [comment]
Same as #28961
