### ISSUE TITLE
How to get vscode API after updating the dev to ^0.11

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#2895]
Hi , 
I have updated the API and set the package.json as
`"devDependencies": {
    "typescript": "^1.6.2",
    "vscode": "^0.11.x"
  },`

But im getting error on extension.ts on 
`import * as vscode from 'vscode';`

cannot find module vscode.

How to access latest API?

**Comment by egamma** [comment]
Please see https://code.visualstudio.com/Updates#_extension-authoring

**Comment by shanalikhan** [comment]
> The vscode module will download the appropriate version of vscode.d.ts based on the engine field you declared.

where it file will be downloaded its not in the extension ?

**Comment by egamma** [comment]
Did you:

- Make sure your devDependency to the vscode module is at least 0.11.0.
- Ran npm install from the root of your extension.

This will update vscode.d.ts in the typings folder.

**Comment by egamma** [comment]
And one more thing, change the engines field in the package.json to version of the API you want. The engines field determines which version of the API will be installed. For example:
```json
"engines": {
"vscode": "^0.10.7"
}
```

**Comment by shanalikhan** [comment]
Yes i have set 
`"devDependencies": {
    "typescript": "^1.6.2",
    "vscode": "^0.11.0"
  },`

"engines": {
    "vscode": "^0.10.7"
  },

the vscode.d.ts in typings folder is showing
`/// <reference path="../node_modules/vscode/typings/index.d.ts" />`

extension.ts
`import * as vscode from 'vscode';`

but no intellisense

**Comment by egamma** [comment]
Can you run `npm run postinstall` manually. This will fetch the vscode.d.ts that corresponds to the engine version. What is the output you get from this command?

This is the output you should get

```
npm run postinstall

> tslint@0.5.15 postinstall C:\Users\egamma\Projects\vscode-tslint\tslint
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^0.10.7
Found minimal version that qualifies engine range: 0.10.8
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/0.10.8/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
```

**Comment by shanalikhan** [comment]
I have tried and getting error as :
```

`npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! missing script: postinstall
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\skhan\Dropbox\code-settings-sync\npm-debug.log`
```

**Comment by egamma** [comment]
You have to add the postinstall script manually to the existing scripts section in the package.json

```json
"postinstall": "node ./node_modules/vscode/bin/install"
```

**Comment by shanalikhan** [comment]
I have added in scripts.
"scripts": { "postinstall": "node ./node_modules/vscode/bin/install" } 
```
> code-settings-sync@1.0.1 postinstall C:\Users\skhan\Dropbox\code-settings-sync

> node ./node_modules/vscode/bin/install

module.js:328
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\skhan\Dropbox\code-settings-sync\node_module
s\vscode\bin\install:4:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! code-settings-sync@1.0.1 postinstall: `node ./node_modules/vscode/bin/i
nstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-settings-sync@1.0.1 postinstall script 'node ./node_
modules/vscode/bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the code-settings-sync pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/vscode/bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls code-settings-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\skhan\Dropbox\code-settings-sync\npm-debug.log
``

**Comment by egamma** [comment]
can you run `npm install` and try again, pls.

**Comment by shanalikhan** [comment]
I have tried and getting this error .

```
> code-settings-sync@1.0.1 postinstall C:\Users\shana\Dropbox\code-settings-sync
> node ./node_modules/vscode/bin/install

module.js:328
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\shana\Dropbox\code-settings-sync\node_modules\vscode\bin\install:4:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by shanalikhan** [comment]
@egamma still waiting for your response. :)

**Comment by egamma** [comment]
I've your repo on github (https://github.com/shanalikhan/code-settings-sync) and will try to repro this.

**Comment by egamma** [comment]
It works for me.

- git clone 
- npm install
- edit package.json (as shown below)
- npm install (get the output below)

`package.json`
```json
{
  "name": "code-settings-sync",
  "displayName": "Visual Studio Code Settings Sync",
  "description": "Synchronize Settings, Snippets, launch, keybindings files and extensions Across Multiple Machines using Github GIST.",
  "version": "1.0.1",
  "icon": "images/cloud.png",
  "publisher": "Shan",
  "author": {
        "name": "Shan Khan",
        "url": "http://shanalikhan.github.io"
    },
  "galleryBanner": {
        "color": "#3B4859",
        "theme": "dark"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/shanalikhan/code-settings-sync.git"
    },
    "bugs": {
        "url": "https://github.com/shanalikhan/code-settings-sync/issues",
    "email": "shanalikhan@hotmail.com"
    },
  "engines": {
    "vscode": "^0.10.7"
  },
  "categories": [
    "Other"
  ],
  "activationEvents": [
    "onCommand:extension.updateSettings",
    "onCommand:extension.downloadSettings",
    "onCommand:extension.resetSettings"
  ],
  "main": "./out/src/extension",
  "contributes": {
    "commands": [
      {
        "command": "extension.downloadSettings",
        "title": "Sync : Download Settings"
      },
      {
        "command": "extension.updateSettings",
        "title": "Sync : Update / Upload Settings"
      },
      {
        "command": "extension.resetSettings",
        "title": "Sync : Reset Token and GIST Data"
      }
    ],
    "keybindings": [
      {
        "key": "alt+shift+u",
        "command": "extension.updateSettings",
        "when": "editorTextFocus"
      },
      {
        "key": "alt+shift+d",
        "command": "extension.downloadSettings",
        "when": "editorTextFocus"
      }
    ]
  },
  "scripts": {
    "vscode:prepublish": "node ./node_modules/vscode/bin/compile",
    "compile": "node ./node_modules/vscode/bin/compile -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
  "devDependencies": {
    "typescript": "^1.6.2",
    "vscode": "^0.11.x"
  },
  "dependencies": {
    "fs": "^0.0.2",
    "github": "^0.2.4",
    "open": "^0.0.5",
    "temp": "^0.8.3",
    "adm-zip": "^0.4.7",
    "ncp": "^2.0.0"
  }
}
```

`output`
```
c:\Users\egamma\Projects\tries\code-settings-sync>npm install
npm WARN package.json code-settings-sync@1.0.1 No license field.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
/
> code-settings-sync@1.0.1 postinstall c:\Users\egamma\Projects\tries\code-settings-sync
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^0.10.7
Found minimal version that qualifies engine range: 0.10.8
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/0.10.8/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

vscode@0.11.1 node_modules\vscode
├── semver@5.1.0
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
├── source-map-support@0.3.3 (source-map@0.1.32)
├── mocha@2.4.5 (escape-string-regexp@1.0.2, commander@2.3.0, diff@1.4.0, growl@1.8.1, supports-color@1.2.0, debug@2.2.0, mkdirp@0.5.1, glob@3.2.3, jade@0.26.3)
├── gulp-symdest@1.0.0 (queue@3.1.0, mkdirp@0.5.1, event-stream@3.3.2, vinyl-fs@1.0.0)
├── gulp-vinyl-zip@1.1.2 (queue@3.1.0, yazl@2.3.0, vinyl@0.4.6, event-stream@3.3.2, yauzl@2.4.1, through2@0.6.5, vinyl-fs@0.3.14)
├── request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, node-uuid@1.4.7, qs@6.0.2, combined-stream@1.0.5, mime-types@2.1.10, form-data@1.0.0-rc3, aws4@1.2.1, bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
└── gulp-remote-src@0.4.0 (node.extend@1.1.5, vinyl@0.2.3, event-stream@3.1.7, through2@0.5.1, request@2.58.0)
```

**Comment by shanalikhan** [comment]
Thanks :+1:
