### ISSUE TITLE
Latest VSCode insider doesn't start and outputs error "TypeError: Cannot read property 'reopenFolders' of undefined"

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/vscode#29035]
- VSCode Version: 1.14.0
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

Just installed latest insider build and I can't start the app anymore. I tried doing this from command line and I'm able to see this error message:

> TypeError: Cannot read property 'reopenFolders' of undefined
>     at e.getRestoreWindowsSetting (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:270796)
>     at e.doGetWindowsFromLastSession (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:269767)
>     at e.getWindowsToOpen (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:269099)
>     at e.open (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:265701)
>     at t.openFirstWindow (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:316903)
>     at C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:314524
>     at t.invokeFunction (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:164273)
>     at t.startup (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:314488)
>     at C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:321107
>     at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:67486)
>

**Comment by enbyted** [comment]
Happens for me too, same stacktrace.

**Comment by jtsom** [comment]
Similar problem on macOS Sierra.
```
AVDCreateGPUAccelerator: Error loading GPU renderer
TypeError: Cannot read property 'reopenFolders' of undefined
    at e.getRestoreWindowsSetting (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:270796)
    at e.doGetWindowsFromLastSession (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:269767)
    at e.getWindowsToOpen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:269099)
    at e.open (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:265701)
    at t.openFirstWindow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:316903)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:314524
    at t.invokeFunction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:164273)
    at t.startup (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:314488)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:321107
    at Object.v [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:67486)
```

**Comment by bpasero** [comment]
Sorry for that, should be ok again with todays insider build: http://code.visualstudio.com/Download#insiders

**Comment by clguimanMSFT** [comment]
I get the same error with the latest build

**Comment by Hekitakai** [comment]
http://code.visualstudio.com/Download#insiders link directs to version 1.13.1 - current one
https://code.visualstudio.com/insiders directs to version 1.14.0 from 19/07 - there that bug is still present

**Comment by refack** [comment]
Confirm latest download works
