### ISSUE TITLE
Cannot read property 'getRoot' of null

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29057]
I see this when running out of sources with no folder opened:

Cannot read property 'getRoot' of null: TypeError: Cannot read property 'getRoot' of null
    at Configuration.getConfigurationForResource (file:///Users/chrmarti/Development/repos/vscode/out/vs/platform/configuration/common/configuration.js:243:39)
    at Configuration.getConfigurationModel (file:///Users/chrmarti/Development/repos/vscode/out/vs/platform/configuration/common/configuration.js:232:43)
    at Configuration.getValue (file:///Users/chrmarti/Development/repos/vscode/out/vs/platform/configuration/common/configuration.js:175:36)
    at WorkspaceConfigurationService.getConfiguration (file:///Users/chrmarti/Development/repos/vscode/out/vs/workbench/services/configuration/node/configuration.js:204:40)
    at TextResourceConfigurationService.getConfiguration (file:///Users/chrmarti/Development/repos/vscode/out/vs/editor/common/services/resourceConfigurationImpl.js:43:46)
    at TextFileEditor.BaseTextEditor.updateEditorConfiguration (file:///Users/chrmarti/Development/repos/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:230:87)
    at file:///Users/chrmarti/Development/repos/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:153:23
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at TextFileEditor.BaseTextEditor.setInput (file:///Users/chrmarti/Development/repos/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:150:73)
    at TextFileEditor.setInput (file:///Users/chrmarti/Development/repos/vscode/out/vs/workbench/parts/files/browser/editors/textFileEditor.js:69:39)
WorkbenchShell.onUnexpectedError @ shell.ts:443
(anonymous) @ shell.ts:403
ErrorHandler.onUnexpectedError @ errors.ts:119
onUnexpectedError @ errors.ts:139
(anonymous) @ errors.ts:47
(anonymous) @ errors.ts:44
errors.ts:51 WARNING: Promise with no error callback:2

**Comment by npofopr** [comment]
<details>
  <summary>Can not open the settings:</summary>
`
messageService.ts:125 Невозможно открыть "settings.json": Cannot read property 'getRoot' of null.: Error: Невозможно открыть "settings.json": Cannot read property 'getRoot' of null.
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:403067)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:402673
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:53085)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:56586)
    at n.Class.derive._oncancel._run (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:57907)
    at n.Class.derive._oncancel._error (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:57424)
    at l (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:60966)
    at r.forEach.Y.then.o.(anonymous function) (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:61076)
    at Object.g [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:52505)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:56079)
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
t.doHandleSetInputError @ editorPart.ts:522
(anonymous) @ editorPart.ts:502
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
l @ winjs.base.raw.js:1825
r.forEach.Y.then.o.(anonymous function) @ winjs.base.raw.js:1838
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
then @ winjs.base.raw.js:1566
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
then @ winjs.base.raw.js:1566
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
(anonymous) @ modelBuilder.ts:100
emitNone @ events.js:91
emit @ events.js:185
endReadableNT @ _stream_readable.js:974
_combinedTickCallback @ internal/process/next_tick.js:74
_tickCallback @ internal/process/next_tick.js:98
shell.ts:439 Cannot read property 'getRoot' of null: TypeError: Cannot read property 'getRoot' of null
    at t.e.getConfigurationForResource (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1060649)
    at t.e.getConfigurationModel (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1060390)
    at t.e.getValue (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1059108)
    at t.getConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2248258)
    at t.getConfigurationOverrides (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2757755)
    at t.getConfigurationOverrides (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2808221)
    at t.computeConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2757413)
    at t.updateEditorConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2761196)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2758305
    at e.invoke (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:66897)
e.onUnexpectedError @ shell.ts:439
(anonymous) @ shell.ts:399
e.onUnexpectedError @ errors.ts:119
a @ errors.ts:139
e.invoke @ callbackList.ts:65
e.fire @ event.ts:123
t.setModel @ commonCodeEditor.ts:235
(anonymous) @ textResourceEditor.ts:94
then @ winjs.base.raw.js:1566
t.setInput @ textResourceEditor.ts:79
t.doSetInput @ editorPart.ts:475
(anonymous) @ editorPart.ts:349
then @ winjs.base.raw.js:1566
t.doOpenEditor @ editorPart.ts:343
t.openEditor @ editorPart.ts:309
t.doCloseActiveEditor @ editorPart.ts:579
t.doHandleSetInputError @ editorPart.ts:532
(anonymous) @ editorPart.ts:502
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
l @ winjs.base.raw.js:1825
r.forEach.Y.then.o.(anonymous function) @ winjs.base.raw.js:1838
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
then @ winjs.base.raw.js:1566
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
then @ winjs.base.raw.js:1566
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
(anonymous) @ modelBuilder.ts:100
emitNone @ events.js:91
emit @ events.js:185
endReadableNT @ _stream_readable.js:974
_combinedTickCallback @ internal/process/next_tick.js:74
_tickCallback @ internal/process/next_tick.js:98
shell.ts:439 Cannot read property 'getRoot' of null: TypeError: Cannot read property 'getRoot' of null
    at t.e.getConfigurationForResource (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1060649)
    at t.e.getConfigurationModel (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1060390)
    at t.e.getValue (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1059108)
    at t.getConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2248258)
    at t.getConfigurationOverrides (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2757755)
    at t.getConfigurationOverrides (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2808221)
    at t.computeConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2757413)
    at t.updateEditorConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2761196)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2759761
    at n.Class.define.cancel.then (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:59340)
e.onUnexpectedError @ shell.ts:439
(anonymous) @ shell.ts:399
e.onUnexpectedError @ errors.ts:119
a @ errors.ts:139
(anonymous) @ errors.ts:47
(anonymous) @ errors.ts:44
errors.ts:51 WARNING: Promise with no error callback:244
errors.ts:52 Object {exception: TypeError: Cannot read property 'getRoot' of null
    at t.e.getConfigurationForResource (file:///C:…, error: null, promise: n.C…s.d…e.supportedForProcessing, handler: undefined, id: 244…}
errors.ts:54 TypeError: Cannot read property 'getRoot' of null
    at t.e.getConfigurationForResource (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1060649)
    at t.e.getConfigurationModel (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1060390)
    at t.e.getValue (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1059108)
    at t.getConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2248258)
    at t.getConfigurationOverrides (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2757755)
    at t.getConfigurationOverrides (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2808221)
    at t.computeConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2757413)
    at t.updateEditorConfiguration (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2761196)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2759761
    at n.Class.define.cancel.then (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:59340)
`
</details>

**Comment by sandy081** [comment]
Duplicates #29022
