### ISSUE TITLE
Pasting a file into unresolved explorer folder fails to resolve its full children list

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29177]
1. Copy a file in the Explorer
2. Paste it into an unresolved folder

Only the files before that file, lexicographically, will be resolved.

![kapture 2017-06-21 at 11 10 53](https://user-images.githubusercontent.com/22350/27376396-4cee2688-5672-11e7-8a26-6c6f1321f180.gif)

**Comment by bpasero** [comment]
@isidorn I think this issue existed before but now I am getting this which I think is new following Joaos steps:

```
shell.js:239 Assertion failed (item already registered: file:///Users/bpasero/Documents/ticino-playground:file:///Users/bpasero/Documents/ticino-playground/qunit/Driver.ts): Error: Assertion failed (item already registered: file:///Users/bpasero/Documents/ticino-playground:file:///Users/bpasero/Documents/ticino-playground/qunit/Driver.ts)
    at Object.ok (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/assert.js:13:19)
    at ItemRegistry.register (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/tree/browser/treeModel.js:93:20)
    at new Item (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/tree/browser/treeModel.js:128:28)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/tree/browser/treeModel.js:288:54
    at Object.notifySuccess [as _notify] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.derive._creator._run (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.derive._creator._completed (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1036:18)
    at Object.notifySuccess [as _notify] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:852:30)
```

The event handler for this operation starts from here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L427

It seems like we are missing a resolve call here in case the folder is not yet resolved. Instead, we just add the new element into the folder.

**Comment by isidorn** [comment]
@bpasero code review the fix when you get a chance, thanks

**Comment by bpasero** [comment]
@isidorn thanks, I think that fix is OK.
