### ISSUE TITLE
Problem in Building from Source?!

### ISSUE THREAD

**Issue by questionpython** [Microsoft/vscode#29211]
Hello VS Team,
I try to build vscode from source.
but show errors:

$ ./scripts/npm.sh install --arch=x64
--------
```
> code-oss-dev@1.14.0 preinstall /home/guest/Projects/vscode-master
> node build/npm/preinstall.js

up to date in 3.415s
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-mutex@0.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 (node_modules/windows-foreground-love):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-foreground-love@0.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EINTEGRITY
npm ERR! sha1-18D6KvXVoaZ/QlPa7pgTLnM/Dxk= integrity checksum failed when using sha1: wanted sha1-18D6KvXVoaZ/QlPa7pgTLnM/Dxk= but got sha1-YCA8ATGCcuuCNcbX5fjho6yO2xU=. (48628 bytes)
  

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guest/.electron-gyp/.npm/_logs/2017-06-21T19_41_43_683Z-debug.log
```

------------

cat ~/.electron-gyp/.npm/_logs/2017-06-21T19_41_43_683Z-debug.log
---------
```
...
...
...
...
...
...
...
...
...
...
...
16243 silly pacote trying clap@https://registry.npmjs.org/clap/-/clap-1.2.0.tgz by hash: sha1-WckP4+E3EEdG/xlGmiemNP9oyFc=
16244 silly pacote data for sha1-WckP4+E3EEdG/xlGmiemNP9oyFc= not present. Using manifest.
16245 http fetch GET 200 https://registry.npmjs.org/to-absolute-glob/-/to-absolute-glob-0.1.1.tgz 44313ms
16246 silly pacote to-absolute-glob@https://registry.npmjs.org/to-absolute-glob/-/to-absolute-glob-0.1.1.tgz extracted in 44324ms
16247 silly extract babel-code-frame@6.22.0
16248 silly pacote trying babel-code-frame@https://registry.npmjs.org/babel-code-frame/-/babel-code-frame-6.22.0.tgz by hash: sha1-AnYgvuVnqIwyVhV05/0IAdMxGOQ=
16249 silly pacote data for sha1-AnYgvuVnqIwyVhV05/0IAdMxGOQ= not present. Using manifest.
16250 http fetch GET 200 https://registry.npmjs.org/tildify/-/tildify-1.2.0.tgz 41877ms
16251 silly pacote tildify@https://registry.npmjs.org/tildify/-/tildify-1.2.0.tgz extracted in 41889ms
16252 silly extract chalk@1.1.3
16253 silly pacote trying chalk@https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz by hash: sha1-qBFcVeSnAv5NFQq9OHKCKn4J/Jg=
16254 silly pacote chalk@https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz extracted to /home/max/Projects/vscode-master/node_modules/.staging/chalk-a09b307b by content address 72ms
16255 silly extract supports-color@2.0.0
16256 silly pacote trying supports-color@https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz by hash: sha1-U10EXOa2Nj+kARcIRimZXp3zJMc=
16257 silly pacote supports-color@https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz extracted to /home/max/Projects/vscode-master/node_modules/.staging/supports-color-3b7a29e2 by content address 6ms
16258 silly extract registry-url@3.1.0
16259 silly pacote trying registry-url@https://registry.npmjs.org/registry-url/-/registry-url-3.1.0.tgz by hash: sha1-PU74cPc93h138M+aOBQyRE4XSUI=
16260 silly pacote data for sha1-PU74cPc93h138M+aOBQyRE4XSUI= not present. Using manifest.
16261 http fetch GET 200 https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz 58666ms
16262 silly pacote sshpk@https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz extracted in 58675ms
16263 silly extract registry-auth-token@3.3.1
16264 silly pacote trying registry-auth-token@https://registry.npmjs.org/registry-auth-token/-/registry-auth-token-3.3.1.tgz by hash: sha1-+w0yie4Nmtosu1KvXf5mywcNMAY=
16265 silly pacote data for sha1-+w0yie4Nmtosu1KvXf5mywcNMAY= not present. Using manifest.
16266 http fetch GET 200 https://registry.npmjs.org/split/-/split-0.3.3.tgz 45110ms
16267 silly pacote split@https://registry.npmjs.org/split/-/split-0.3.3.tgz extracted in 45117ms
16268 silly extract rc@1.2.1
16269 silly pacote trying rc@https://registry.npmjs.org/rc/-/rc-1.2.1.tgz by hash: sha1-LgPo5C7kULjLPc5lvhv4l04d/ZU=
16270 silly pacote data for sha1-LgPo5C7kULjLPc5lvhv4l04d/ZU= not present. Using manifest.
16271 http fetch GET 200 https://registry.npmjs.org/through/-/through-2.3.8.tgz 45112ms
16272 silly pacote through@https://registry.npmjs.org/through/-/through-2.3.8.tgz extracted in 45146ms
16273 silly extract strip-json-comments@2.0.1
16274 silly pacote trying strip-json-comments@https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz by hash: sha1-PFMZQukIwml8DsNEhYwobHygpgo=
16275 silly pacote data for sha1-PFMZQukIwml8DsNEhYwobHygpgo= not present. Using manifest.
16276 http fetch GET 200 https://registry.npmjs.org/tmp/-/tmp-0.0.29.tgz 51830ms
16277 silly pacote tmp@https://registry.npmjs.org/tmp/-/tmp-0.0.29.tgz extracted in 51862ms
16278 silly extract redent@1.0.0
16279 silly pacote trying redent@https://registry.npmjs.org/redent/-/redent-1.0.0.tgz by hash: sha1-z5Fqsf1fHxbfsggi3W7H9zDCr94=
16280 silly pacote data for sha1-z5Fqsf1fHxbfsggi3W7H9zDCr94= not present. Using manifest.
16281 http fetch GET 200 https://registry.npmjs.org/vso-node-api/-/vso-node-api-6.1.2-preview.tgz 132942ms
16282 silly pacote vso-node-api@https://registry.npmjs.org/vso-node-api/-/vso-node-api-6.1.2-preview.tgz extracted in 132946ms
16283 silly extract strip-indent@1.0.1
16284 silly pacote trying strip-indent@https://registry.npmjs.org/strip-indent/-/strip-indent-1.0.1.tgz by hash: sha1-DHlipq3vp7vUrDZkYKY4VSrhoKI=
16285 silly pacote data for sha1-DHlipq3vp7vUrDZkYKY4VSrhoKI= not present. Using manifest.
16286 http fetch GET 200 https://registry.npmjs.org/pause-stream/-/pause-stream-0.0.11.tgz 49914ms
16287 silly pacote pause-stream@https://registry.npmjs.org/pause-stream/-/pause-stream-0.0.11.tgz extracted in 49948ms
16288 silly extract strip-eof@1.0.0
16289 silly pacote trying strip-eof@https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz by hash: sha1-u0P/VZim6wXYm1n80SnJgzE2Br8=
16290 silly pacote data for sha1-u0P/VZim6wXYm1n80SnJgzE2Br8= not present. Using manifest.
16291 http fetch GET 200 https://registry.npmjs.org/textextensions/-/textextensions-1.0.2.tgz 48364ms
16292 silly pacote textextensions@https://registry.npmjs.org/textextensions/-/textextensions-1.0.2.tgz extracted in 48365ms
16293 silly extract strip-bom-stream@1.0.0
16294 silly pacote trying strip-bom-stream@https://registry.npmjs.org/strip-bom-stream/-/strip-bom-stream-1.0.0.tgz by hash: sha1-5xRDmFd9Uaa+0PoZlPoF9D/ZiO4=
16295 silly pacote data for sha1-5xRDmFd9Uaa+0PoZlPoF9D/ZiO4= not present. Using manifest.
16296 http fetch GET 200 https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz 49561ms
16297 silly pacote text-table@https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz extracted in 49571ms
16298 silly extract strip-bom@2.0.0
16299 silly pacote trying strip-bom@https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz by hash: sha1-YhmoVhZSBJHzV4i9vxRHqZx+aw4=
16300 silly pacote strip-bom@https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz extracted to /home/max/Projects/vscode-master/node_modules/.staging/strip-bom-6ae98283 by content address 5ms
16301 silly extract strip-bom@3.0.0
16302 silly pacote trying strip-bom@https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz by hash: sha1-IzTBjpx1n3vdVv3vfprj1YjmjtM=
16303 silly pacote data for sha1-IzTBjpx1n3vdVv3vfprj1YjmjtM= not present. Using manifest.
16304 http fetch GET 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz 49164ms
16305 silly pacote rimraf@https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz extracted in 49175ms
16306 silly extract string-width@1.0.2
16307 silly pacote trying string-width@https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz by hash: sha1-EYvfW4zcUaKn5w0hHgfisLmxB9M=
16308 silly pacote data for sha1-EYvfW4zcUaKn5w0hHgfisLmxB9M= not present. Using manifest.
16309 http fetch GET 200 https://registry.npmjs.org/tunnel/-/tunnel-0.0.4.tgz 67132ms
16310 silly pacote tunnel@https://registry.npmjs.org/tunnel/-/tunnel-0.0.4.tgz extracted in 67159ms
16311 silly extract string-width@2.0.0
16312 silly pacote trying string-width@https://registry.npmjs.org/string-width/-/string-width-2.0.0.tgz by hash: sha1-Y1xUNsxypuDDh87KJ41OLuxSaH4=
16313 silly pacote data for sha1-Y1xUNsxypuDDh87KJ41OLuxSaH4= not present. Using manifest.
16314 http fetch GET 200 https://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz 53225ms
16315 silly pacote event-stream@https://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz extracted in 53229ms
16316 silly extract ansi-align@2.0.0
16317 silly pacote trying ansi-align@https://registry.npmjs.org/ansi-align/-/ansi-align-2.0.0.tgz by hash: sha1-w2rsy6VjuJzrVW82kPCx2eNUf38=
16318 silly pacote data for sha1-w2rsy6VjuJzrVW82kPCx2eNUf38= not present. Using manifest.
16319 http fetch GET 200 https://registry.npmjs.org/string-width/-/string-width-2.0.0.tgz 45569ms
16320 silly pacote string-width@https://registry.npmjs.org/string-width/-/string-width-2.0.0.tgz extracted in 45573ms
16321 silly extract string-width@2.0.0
16322 silly pacote trying string-width@https://registry.npmjs.org/string-width/-/string-width-2.0.0.tgz by hash: sha1-Y1xUNsxypuDDh87KJ41OLuxSaH4=
16323 silly pacote string-width@https://registry.npmjs.org/string-width/-/string-width-2.0.0.tgz extracted to /home/max/Projects/vscode-master/node_modules/.staging/string-width-74b36273 by content address 5ms
16324 silly extract strip-ansi@3.0.1
16325 silly pacote trying strip-ansi@https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz by hash: sha1-ajhfuIU9lS1f8F0Oiq+UJ43GPc8=
16326 silly pacote strip-ansi@https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz extracted to /home/max/Projects/vscode-master/node_modules/.staging/strip-ansi-ce06ef5f by content address 4ms
16327 silly extract stringstream@0.0.5
16328 silly pacote trying stringstream@https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz by hash: sha1-TkhM1N5aC7vuGORjB3EKioFiGHg=
16329 silly pacote data for sha1-TkhM1N5aC7vuGORjB3EKioFiGHg= not present. Using manifest.
16330 http fetch GET 200 https://registry.npmjs.org/istextorbinary/-/istextorbinary-1.0.2.tgz 53358ms
16331 silly pacote istextorbinary@https://registry.npmjs.org/istextorbinary/-/istextorbinary-1.0.2.tgz extracted in 53361ms
16332 silly extract readable-stream@1.0.34
16333 silly pacote trying readable-stream@https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz by hash: sha1-Elgg40vIQtLyqq+v5MKRbuMsFXw=
16334 silly pacote readable-stream@https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz extracted to /home/max/Projects/vscode-master/node_modules/.staging/readable-stream-a2da2136 by content address 22ms
16335 silly extract readable-stream@1.0.34
16336 silly pacote trying readable-stream@https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz by hash: sha1-Elgg40vIQtLyqq+v5MKRbuMsFXw=
16337 silly pacote readable-stream@https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz extracted to /home/max/Projects/vscode-master/node_modules/.staging/readable-stream-c4bec855 by content address 12ms
16338 silly extract through2@0.5.1
16339 silly pacote trying through2@https://registry.npmjs.org/through2/-/through2-0.5.1.tgz by hash: sha1-390BLrnHAOIyP9M084rGIqs3Lac=
16340 silly pacote data for sha1-390BLrnHAOIyP9M084rGIqs3Lac= not present. Using manifest.
16341 http fetch GET 200 https://registry.npmjs.org/request/-/request-2.27.0.tgz 71272ms
16342 silly pacote request@https://registry.npmjs.org/request/-/request-2.27.0.tgz extracted in 71273ms
16343 verbose unlock done using /home/max/.electron-gyp/.npm/_locks/staging-f1dd5b6039c7ac86.lock for /home/max/Projects/vscode-master/node_modules/.staging
16344 warn optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
16345 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-mutex@0.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
16346 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    win32
16346 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
16346 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
16346 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
16347 warn optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 (node_modules/windows-foreground-love):
16348 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-foreground-love@0.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
16349 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    win32
16349 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
16349 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
16349 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
16350 verbose stack Error: sha1-18D6KvXVoaZ/QlPa7pgTLnM/Dxk= integrity checksum failed when using sha1: wanted sha1-18D6KvXVoaZ/QlPa7pgTLnM/Dxk= but got sha1-YCA8ATGCcuuCNcbX5fjho6yO2xU=. (48628 bytes)
16350 verbose stack     at Transform.on (/usr/lib/node_modules/npm/node_modules/ssri/index.js:278:19)
16350 verbose stack     at emitNone (events.js:110:20)
16350 verbose stack     at Transform.emit (events.js:207:7)
16350 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
16350 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
16350 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
16351 verbose cwd /home/max/Projects/vscode-master
16352 verbose Linux 4.11.3-1-ARCH
16353 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--arch=x64"
16354 verbose node v8.1.0
16355 verbose npm  v5.0.3
16356 error code EINTEGRITY
16357 error sha1-18D6KvXVoaZ/QlPa7pgTLnM/Dxk= integrity checksum failed when using sha1: wanted sha1-18D6KvXVoaZ/QlPa7pgTLnM/Dxk= but got sha1-YCA8ATGCcuuCNcbX5fjho6yO2xU=. (48628 bytes)
16358 verbose exit [ 1, true ]
```

**Comment by joaomoreno** [comment]
We don't support npm 5 yet. Please go back to npm 4/ node 7.
