### ISSUE TITLE
Install npm packages in windows gives node-gyp error

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#29310]
Steps to Reproduce:

1. .\scripts\npm.bat install
2. 
```bash
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
```

**Comment by con-ssc** [comment]
```bash
8 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules\fsevents):
36159 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
36160 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
36160 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
36160 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
36160 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
36161 verbose stack Error: oniguruma@6.1.1 install: `node-gyp rebuild`
36161 verbose stack Exit status 1
36161 verbose stack     at EventEmitter.<anonymous> (C:\Users\stefan.schneider\AppData\Local\nvs\node\7.4.0\x64\node_modules\npm\lib\utils\lifecycle.js:279:16)
36161 verbose stack     at emitTwo (events.js:106:13)
36161 verbose stack     at EventEmitter.emit (events.js:191:7)
36161 verbose stack     at ChildProcess.<anonymous> (C:\Users\stefan.schneider\AppData\Local\nvs\node\7.4.0\x64\node_modules\npm\lib\utils\spawn.js:40:14)
36161 verbose stack     at emitTwo (events.js:106:13)
36161 verbose stack     at ChildProcess.emit (events.js:191:7)
36161 verbose stack     at maybeClose (internal/child_process.js:885:16)
36161 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
36162 verbose pkgid oniguruma@6.1.1
36163 verbose cwd D:\repositories\git\vscode
36164 error Windows_NT 10.0.14393

```

**Comment by con-ssc** [comment]
same for
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**Comment by codeguy** [comment]
Can confirm when attempting to setup local environment for working on a pull request.

**Comment by dbaeumer** [comment]
I was able to solve this doing the following:
- use node 7.4.0
- git clean -xfd .build     (PLEASE note the . in `.build`)
- git clean -xfd node_modules
-git clean -xfd extensions
- scripts\npm install

**Comment by con-ssc** [comment]
For me it was necessary to also set the `npm config set node_gyp` manually to the node-gyp.js

**Comment by codeguy** [comment]
Still no luck on my end. Do you know if the npm setup is compatible with Visual Studio Community 2017? Or do I need to revert to 2015?

**Comment by i-give-up** [comment]
I had the same issue  which was also resolved using `scripts/npm.bat install --msvs_version=2015` alone (I have multiple versions of VS too). I didn't have to perform the `npm config set node_gyp` step.
