### ISSUE TITLE
Trying to compile VS Code under Windows results in

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29429]
```
P:\mseng\VSCode\vscode [master]> gulp --tasks-simple
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\P:\mseng\VSCode\vscode\node_modules\nsfw\build\Release\nsfw.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (P:\mseng\VSCode\vscode\node_modules\nsfw\lib\src\index.js:3:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

This seems to be caused by the new nsfw module which we now use to compile vscode. Since we use that in gulp and not in vscode it should may be not compiled using the electron environment but the node environment.

**Comment by bpasero** [comment]
Somehow the nsfw package is not being installed when running the root leveled `scripts/npm.sh install`

Will look into this with @joaomoreno. As a workaround you can `set VSCODE_USE_LEGACY_WATCH=1`

**Comment by dbaeumer** [comment]
Work now. Even the watcher after help from @bpasero
