### ISSUE TITLE
VScode output emit error: 'completionEntryDetails' request failed

### ISSUE THREAD

**Issue by Dogyunjeong** [Microsoft/vscode#29692]
- VSCode Version: 1.13.0-insider
- OS Version: windows 10 pro

Steps to Reproduce:

1. While Meteor running, modified meteor client side file

I have worked with VScode and meteor for a month. It is my first time to see this error. 

Here is emitted error stack

```
[Info  - 10:18:13 AM] Using tsserver from: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info  - 10:18:13 AM] Forking TSServer
PATH: undefined
[Error  - 10:21:53 AM] 'completionEntryDetails' request failed with error.
Error: Cancelled Request 45
    at TypeScriptServiceClient.tryCancelRequest (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\out\typescriptServiceClient.js:755:25)
    at token.onCancellationRequested (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\out\typescriptServiceClient.js:695:30)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:14715)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:18522)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:21326)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:21936)
    at n.Class.derive._oncancel.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:59256)
    at n.Class.derive._oncancel._cancelAction (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:55460)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:51217)
    at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:53528)
    at n.Class.derive._oncancel.cancel (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:52693)
    at n.Class.derive._creator._cancelAction (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:53776)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:51217)
    at n.Class.derive._creator._run (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:53528)
    at n.Class.derive._creator.cancel (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:52693)
    at h (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:176262)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by mjbvz** [comment]
The error is expected. It just means that the request was canceled because we no longer care about the result. We've changed how cancelled requests are logged in 1.14 to make it clearer that this is not an error.

Are you seeing incorrect behavior for JS/TS completions?

**Comment by Dogyunjeong** [comment]
Okay.
I suspect it might relate with #28013 and #29132. 
Thank you to inform me.
