### ISSUE TITLE
Strange "Could Not Start Dumper" Error

### ISSUE THREAD

**Issue by Mystagogue** [Microsoft/vscode#2976]
I upgraded from 0.10.6 to 0.10.8.  At a CMD prompt I launched "code", and then witnessed a strange error dump:

C:\repos\hub\vtc\ts-sample>code .

C:\repos\hub\vtc\ts-sample>[6868:6872:0212/111704:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[6868:6872:0212/111704:VERBOSE1:crash_service.cc(142)] window handle is 000A0352
[6868:6872:0212/111704:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\baria\AppData\Local\Temp\VSCode Crashes
[6868:6872:0212/111704:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\baria\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[6868:6872:0212/111704:VERBOSE1:crash_service_main.cc(84)] Ready to process crash requests
[6868:6640:0212/111704:VERBOSE1:crash_service.cc(323)] client start. pid = 5696
[6868:6640:0212/111704:VERBOSE1:crash_service.cc(323)] client start. pid = 6292
[5820:7024:0212/111704:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[5820:7024:0212/111704:VERBOSE1:crash_service.cc(142)] window handle is 001A031C
[5820:7024:0212/111704:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\baria\AppData\Local\Temp\VSCode Crashes
[5820:7024:0212/111704:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\baria\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[5820:7024:0212/111704:ERROR:crash_service.cc(301)] could not start dumper
{ [Error: getaddrinfo ENOTFOUND vscode-update.azurewebsites.net vscode-update.azurewebsites.net:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'vscode-update.azurewebsites.net',
  host: 'vscode-update.azurewebsites.net',
  port: 443 } undefined

I might have been experiencing WIFI connectivity issues approximately when this error occurred - just a bit more info in case it helps.

**Comment by web-dave** [comment]
nearly the same message at every start from commandline.

> D:\Users\damu1de\Documents\workspace\webapp\dpt-app>code .
D:\Users\damu1de\Documents\workspace\webapp\dpt-app>
[8612:648:0216/081901:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[8612:648:0216/081902:VERBOSE1:crash_service.cc(142)] window handle is 00030442
[8612:648:0216/081902:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at D:\Users\damu1de\AppData\Local\Temp\VSCode Crashes
[8612:648:0216/081902:VERBOSE1:crash_service.cc(294)] checkpoint is D:\Users\damu1de\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[8612:648:0216/081902:VERBOSE1:crash_service_main.cc(84)] Ready to process crash requests
[1188:6140:0216/081902:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[8612:10184:0216/081902:VERBOSE1:crash_service.cc(323)] client start. pid = 7520
[1188:6140:0216/081902:VERBOSE1:crash_service.cc(142)] window handle is 00030414
[[1188:6140:0216/081902:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at D:\Users\damu1de\AppData\Local\Temp\VSCode Crashes
8612:10184:0216/081902:VERBOSE1:crash_service.cc(323)] client start. pid = 5468
[1188:6140:0216/081902:VERBOSE1:crash_service.cc(294)] checkpoint is D:\Users\damu1de\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[1188:6140:0216/081902:ERROR:crash_service.cc(301)] could not start dumper

**Comment by MichaelAllenMiller** [comment]
:+1:

**Comment by MichaelAllenMiller** [comment]
The error we are getting is from atom/electron.  My guess is maybe the crash server at https://ticinocrashreporter.azurewebsites.net/crash is not available?  Is it possible to disable verbosity for the crash reporter so that we do not have to see this error every time we launch vs code?

**Comment by MichaelAllenMiller** [comment]
I seem to have solved it, however, I'm not sure why it works.

I set the `ELECTRON_RUN_AS_NODE` environment variable to `1`, which then caused me to get the following error:

>(function (exports, require, module, __filename, __dirname, process, global) { *some text from the file I was opening here*
                                                                                    ^^^^^^^

>SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:130:18)
    at node.js:982:3
Could not execute editor

After removing the environment variable, it seems to work as expected.

**Comment by SofianHn** [comment]
Investigating. @MichaelAllenMiller have you tried to disable crash reporting? maybe this will help you until we figure out the reason for this?

Instructions on how to here: https://code.visualstudio.com/Docs/supporting/faq#_how-to-disable-crash-reporting

**Comment by SofianHn** [comment]
if you run code from the command line you should not hit this, `C:\Program Files (x86)\Visual Studio Code\bin` should be added to your path by the installer, if it's not the case please let us know. 

You can see in the bin that the command line variable is set to disable this: 

```
@echo off
setlocal
set VSCODE_DEV=
set ATOM_SHELL_INTERNAL_RUN_AS_NODE=1
"%~dp0..\\Code.exe" "%~dp0code.js" %*
endlocal
```

if you still want run the exe directly from the command line, make sure to 
`set ATOM_SHELL_INTERNAL_RUN_AS_NODE=1`

**Comment by MichaelAllenMiller** [comment]
Sorry it took so long to reply. Disabling crash reporting seems to have fixed it.

**Comment by nhudacin** [comment]
I was having this same issue. When i checked my path, I had `C:\Program Files (x86)\Visual Studio Code\` instead of `C:\Program Files (x86)\Visual Studio Code\bin\`. Adding `\bin` to the path resolved the issue for me. Thanks for the help!

**Comment by ghoshabhi** [comment]
I have a similar error while deploying app to Google App Engine using its Cloud SDK! This is what I get : 

```
C:\Users\ABHISHEK\Desktop\Udacity Projects\Multi_User_Blog\final-blog-project\my-blog>
[17280:19608:1108/183752:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://crashreporter.atom.io --application-name=Atom --v=1]
[17280:19608:1108/183752:VERBOSE1:crash_service.cc(142)] window handle is 00290722
[17280:19608:1108/183752:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\Atom Crash Service
dumps at C:\Users\ABHISHEK\AppData\Local\Temp\Atom Crashes
[17280:19608:1108/183752:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\ABHISHEK\AppData\Local\Temp\Atom Crashes\crash_checkpoint.txt
server is https://crashreporter.atom.io
maximum 128 reports/day
reporter is electron-crash-service
[17280:19608:1108/183752:VERBOSE1:crash_service_main.cc(84)] Ready to process crash requests
[17280:9504:1108/183752:VERBOSE1:crash_service.cc(323)] client start. pid = 12968
App load time: 332ms
[17280:9504:1108/183753:VERBOSE1:crash_service.cc(323)] client start. pid = 15228
[8580:19344:1108/183753:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://crashreporter.atom.io --application-name=Atom --v=1]
[8580:19344:1108/183753:VERBOSE1:crash_service.cc(142)] window handle is 00580668
[8580:19344:1108/183753:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\Atom Crash Service
dumps at C:\Users\ABHISHEK\AppData\Local\Temp\Atom Crashes
[8580:19344:1108/183753:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\ABHISHEK\AppData\Local\Temp\Atom Crashes\crash_checkpoint.txt
server is https://crashreporter.atom.io
maximum 128 reports/day
reporter is electron-crash-service
[8580:19344:1108/183753:ERROR:crash_service.cc(301)] could not start dumper
```
Also, I see that my Command Prompt Says : `linter-eslint helper` 😫 

Anyone has faced something similar before ? 

Thank You!
