### ISSUE TITLE
vscode_emmet_helper_1.getEmmetMode is not a function

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29830]
* running out of sources
* hello world extension
* run it via F5
* open a folder
* open a "out of workspace file"

```
vscode_emmet_helper_1.getEmmetMode is not a function: TypeError: vscode_emmet_helper_1.getEmmetMode is not a function
    at DefaultCompletionItemProvider.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/extensions/emmet/out/defaultCompletionProvider.js:18:44)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:385:85
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:33:24
    at new Promise_ctor (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1641:17)
    at Object.asWinJsPromise (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:32:16)
    at SuggestAdapter.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:385:28)
    at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:732:98
    at ExtHostLanguageFeatures._withAdapter (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:573:20)
    at ExtHostLanguageFeatures.$provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:732:25)
    at ExtHostThreadService.AbstractThreadService.handle (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/thread/common/abstractThreadService.js:25:27)
```

**Comment by ramya-rao-a** [comment]
How did you run an extension when running code form source?

I get "Configured debug type 'extensionHost' is not supported."

**Comment by ramya-rao-a** [comment]
Alright, @roblourens  helped me set up the env for debugging extension from vscode source.

But I still can't repro

According to the callstack, its coming from https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/defaultCompletionProvider.ts#L21

The class in question (the completion provider) is instantiated when the emmet extension gets activated.

But I don't see how the error could occur though
