### ISSUE TITLE
Error when pasting entire line

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29881]
- VSCode Version: code-oss-dev 1.14.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Copy entire line (including newline)
2. Paste
3. Error in console:

Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at Object.getSpaceCnt (file:///Users/chrmarti/Development/repos/vscode/out/vs/editor/contrib/indentation/common/indentUtils.js:10:32)
    at AutoIndentOnPaste.trigger (file:///Users/chrmarti/Development/repos/vscode/out/vs/editor/contrib/indentation/common/indentation.js:463:58)
    at file:///Users/chrmarti/Development/repos/vscode/out/vs/editor/contrib/indentation/common/indentation.js:385:23
    at CallbackList.invoke (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///Users/chrmarti/Development/repos/vscode/out/vs/base/common/event.js:91:40)
    at CodeEditor.CommonCodeEditor.trigger (file:///Users/chrmarti/Development/repos/vscode/out/vs/editor/common/commonCodeEditor.js:482:38)
    at EditorHandlerCommand.runCommand (file:///Users/chrmarti/Development/repos/vscode/out/vs/editor/common/controller/coreCommands.js:1468:24)
    at handler (file:///Users/chrmarti/Development/repos/vscode/out/vs/editor/common/editorCommonExtensions.js:48:67)
    at InstantiationService.invokeFunction (file:///Users/chrmarti/Development/repos/vscode/out/vs/platform/instantiation/common/instantiationService.js:48:34)
    at CommandService._tryExecuteCommand (file:///Users/chrmarti/Development/repos/vscode/out/vs/platform/commands/common/commandService.js:60:72)

**Comment by chrmarti** [comment]
I see this with the latest in master.

**Comment by rebornix** [comment]
@chrmarti thanks!
