### ISSUE TITLE
CLI proxy support

### ISSUE THREAD

**Issue by JCarlos12** [microsoft/vscode#29910]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:
Without http.proxy set
1. run "code --install-extension HookyQR.beautify" in CLI
2. Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

With
1. run "code --install-extension HookyQR.beautify" in CLI
2. result says "Found 'HookyQR.beautify' in the marketplace.
Installing..."

But it does not install. 
Please I need help . Thanks in advance
![extension](https://user-images.githubusercontent.com/11145777/27724739-e09a5ffc-5da5-11e7-8fe6-6f539cb5e86c.PNG)
![extension2](https://user-images.githubusercontent.com/11145777/27724751-f3425038-5da5-11e7-8f0a-bae203d0e4f2.PNG)

**Comment by joaomoreno** [comment]
Unfortunately, the CLI doesn't support proxies yet.

**Comment by JCarlos12** [comment]
@joaomoreno 
Thanks for that :)
I only tried using the CLI since I cant install through the extensions tab.

Any solution for this?
When I use the extensions tab it gets stuck in Installing
![aaa](https://user-images.githubusercontent.com/11145777/27854767-92a48680-619a-11e7-9cf8-82a5cccb3775.PNG)

**Comment by JCarlos12** [comment]
Any update on this?

**Comment by JCarlos12** [comment]
Nevermind
Found the error why its not installing

It turns out I had a path to my mongodb in the "TEMP" environemnt variable 
I removed it and it now works

**Comment by raoulvm** [comment]
Every other years there should be somebody asking for the status of this.
So I'll do it this year, 2023, because some of my fellow colleagues are behind a firewall/proxy and want to have automatic installs, anyway.

**Comment by tp1050** [comment]
Where can I REad about why this does not exist automatically?

**Comment by Steven23661** [comment]
I'm using Gboard to type in English (US) (QWERTY). You can try it at: https://gboard.app.goo.gl/KDRTPI'm using Gboard to type in English (US) (QWERTY). You can try it at: https://gboard.app.goo.gl/KDRTP

**Comment by hjrb** [comment]
Why doesn't that get fixed? Enterprise customers - those guys that pay you bills - depend on it.

**Comment by lamy** [comment]
[]()

**Comment by salimmolla7401-svg** [comment]
PR #22369

**Comment by ashik91companys** [comment]
#
