### ISSUE TITLE
TypeError: Cannot read property 'input' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29952]
Got this error now a couple of times when running out of sources playing around with multi root and restarts, not sure yet what this could be:

@jrieken looks like the code was added via https://github.com/Microsoft/vscode/commit/54b983873d2d7224a976007f98bf6c9f0809996a maybe you could have a look:

```
"Cannot read property 'input' of undefined: TypeError: Cannot read property 'input' of undefined
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:154:39
    at Object.notifySuccess [as _notify] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1036:18)
    at argDone (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1813:37)
    at Promise.then.errors.(anonymous function) (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1838:78)
    at Object.notifySuccess [as _notify] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:901:30)
    at _Base.Class.derive._creator._run (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1068:29)", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js (239)
```

**Comment by bpasero** [comment]
It looks like the underlying cause is https://github.com/Microsoft/vscode/issues/30030 and so one of the editors to open fails and `undefined` is returned. Would be good to just add a check for `undefined` in the loop to be on the safe side.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/6af048189e62ec1cf69be5c99c825b52695c551e because I was in that area.
