### ISSUE TITLE
Add support for *Free*BSD

### ISSUE THREAD

**Issue by maitesin** [Microsoft/vscode#30046]
- VSCode Version: Any
- OS Version: FreeBSD 11

Steps to Reproduce:

1. Download the source
2. Build it
3. It does not build

Reproduces without extensions: Yes

**Comment by maitesin** [comment]
The error I am getting when running `./scripts/npm.sh install` is the following
```
[maitesin@Ryuk ~/Downloads/vscode/scripts]$ ./npm.sh install

> code-oss-dev@1.15.0 preinstall /usr/home/maitesin/Downloads/vscode
> node build/npm/preinstall.js

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> v8-profiler@5.6.5 preinstall /usr/home/maitesin/Downloads/vscode/node_modules/v8-profiler
> node -e 'process.exit(0)'


> typechecker@2.0.8 preinstall /usr/home/maitesin/Downloads/vscode/node_modules/typechecker
> node ./cyclic.js

npm WARN prefer global js-beautify@1.5.10 should be installed with -g

> windows-mutex@0.2.0 install /usr/home/maitesin/Downloads/vscode/node_modules/windows-mutex
> node-gyp rebuild

gmake: Entering directory '/usr/home/maitesin/Downloads/vscode/node_modules/windows-mutex/build'
  CXX(target) Release/obj.target/CreateMutex/src/main.o
../src/main.cc:2:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^
1 error generated.
gmake: *** [CreateMutex.target.mk:95: Release/obj.target/CreateMutex/src/main.o] Error 1
gmake: Leaving directory '/usr/home/maitesin/Downloads/vscode/node_modules/windows-mutex/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System FreeBSD 11.0-RELEASE-p9
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/maitesin/Downloads/vscode/node_modules/windows-mutex
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> windows-foreground-love@0.1.0 install /usr/home/maitesin/Downloads/vscode/node_modules/windows-foreground-love
> node-gyp rebuild

gmake: Entering directory '/usr/home/maitesin/Downloads/vscode/node_modules/windows-foreground-love/build'
  CXX(target) Release/obj.target/foreground-love/src/foreground-love.o
../src/foreground-love.cc:2:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^
1 error generated.
gmake: *** [foreground-love.target.mk:92: Release/obj.target/foreground-love/src/foreground-love.o] Error 1
gmake: Leaving directory '/usr/home/maitesin/Downloads/vscode/node_modules/windows-foreground-love/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System FreeBSD 11.0-RELEASE-p9
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/maitesin/Downloads/vscode/node_modules/windows-foreground-love
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> v8-profiler@5.6.5 install /usr/home/maitesin/Downloads/vscode/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

sh: node-pre-gyp: not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 (node_modules/windows-foreground-love):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! v8-profiler@5.6.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the v8-profiler@5.6.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maitesin/.electron-gyp/.npm/_logs/2017-07-03T16_56_36_970Z-debug.log
```
Please find attached the log file mentioned in the error

[2017-07-03T16_56_36_970Z-debug.log.txt](https://github.com/Microsoft/vscode/files/1120172/2017-07-03T16_56_36_970Z-debug.log.txt)

**Comment by joaomoreno** [comment]
Moving to electron/electron#3797

**Comment by prash-wghats** [comment]
https://github.com/prash-wghats/VSCode-For-FreeBSD/releases.
This binaries were built with FreeBSD 11. you can probably use the Linux compatibility layer to run the Microsoft cpp extension and omnisharp cpp extension. (you will have to copy libraries from a Linux distribution like debian8, since centos 7 libs doesn't work with vscode)
