### ISSUE TITLE
Had to downgrade from 1.14 to restore JSX intellisense

### ISSUE THREAD

**Issue by nmitha** [Microsoft/vscode#30425]
Intellisense broke in React .jsx/.js files in v1.14 for me (not Typescript).  Downgrading back to v1.13.1 resolved it.

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-jest|Orta|2.2.0|
|vscode-docker|PeterJausovec|0.0.16|
|jsrefactor|cmstead|1.3.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.1|
|vscode-guid|heaths|1.1.0|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|ruby-linter|hoovercj|1.0.0|
|RelativePath|jakob101|0.12.0|
|vscode-todo-parser|minhthai|1.8.10|
|ruby-rubocop|misogi|0.4.0|
|Ruby|rebornix|0.12.1|
|sass-indented|robinbentley|1.4.1|
|gitflow|vector-of-bool|1.1.1|;

---

Steps to Reproduce:

1. Use 1.14.
2. Open a .js file with JSX in it.  Fiddle with Language Mode but nothing works to give Intellisense.  No dice with .jsx files either.

**Comment by drew-wallace** [comment]
Interesting. I'm having the issue for TypeScript.

**Comment by mjbvz** [comment]
Can you try:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Reproduce the issue
3. Check the `TypeScript` section of the output window.

Look for error messages in this window when you trigger a completion. You can also paste up the output and I can take a look.

**Comment by revathskumar** [comment]
Anyone getting this similar error message on `OUTPUT` tab when `TypeScript` is selected.

![screenshot 2017-07-12 02 35 49](https://user-images.githubusercontent.com/463904/28090709-d824f3ce-66aa-11e7-83e8-9d509446d720.png)

VERSION : 
1.15.0-insider (1.15.0-insider)
7bb3b89031cbce46536ba870868d889d639e12f1
2017-07-11T17:41:53.024Z


```
[Error  - 2:32:58 AM] 'definition' request failed with error.
Error processing request. Project '/Users/<username>/<path>/<to>/<project>/jsconfig.json' does not contain document '/users/<username>/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
Error: Project '/Users/<username>/<path>/<to>/<project>/jsconfig.json' does not contain document '/users/<username>/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:75718:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77238:42)
    at ConfiguredProject.Project.getScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77243:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76551:51)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:84
    at Object.map (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1483:29)
    at ModuleBuilder.getReferencedFileInfos (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:31)
    at ModuleBuilder.updateFileReferences (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76708:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76693:30)
    at ModuleBuilder.onProjectUpdateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76684:22)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77177:34)

```

**Comment by drew-wallace** [comment]
Sorry @mjbvz I didn't read the issue carefully. I am however getting less syntax highlighting than I used to in TypeScript.

**Comment by mjbvz** [comment]
@drew-wallace Can you please file a seperate issue with screenshots and sorce code so that I can investigate. Thanks

----

For anyone running into issues with the VSCode 1.14: You probably don't need to downgrade VSCode, just the TypeScript version. [Here are the instructions on that](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). We previously shipped with TS 2.3.4 so you'll want to try installing that version locally and using it in your workspace

**Comment by mjbvz** [comment]
@revathskumar Can you share your `jsconfig.json`?

**Comment by revathskumar** [comment]
@mjbvz My `jsconfig.json`
```
{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs"
	}
}

```

**Comment by nmitha** [comment]
Hi all,

My jsconfig.json:

{
    "compilerOptions": {
        "experimentalDecorators": true
    }
}

And I also have the following in my user settings:

"files.associations": {
        "*.jsx": "javascript"
}

I'm writing ES6 .js and .jsx files (not explicitly using TS).  I had
absolutely no Intellisense in my JS files after upgrading, then downgrading
resolved it.  I didn't check if the culprit was the VSCode version or TS
version.  I apologize but I don't have time right now to go back to 1.14 to
provide the typescript tsserver trace, but if you really need it let me
know and I'll find the time.

-Nadeem

**Comment by dearsaturn** [comment]
I'm experiencing this too :(

**Comment by mjbvz** [comment]
I believe this may be caused by https://github.com/Microsoft/TypeScript/issues/17131

@nmitha or @dearsaturn Can you please try:

1. Set `"typescript.tsserver.trace": "verbose"` in your user settings
1. Restart vscode and open a file that should have intellisense but does not
1. Open the output pane in VSCode
1. Look for `Error processing request.` messages in the `TypeScript` section of the output pane

**Comment by dearsaturn** [comment]
@mjbvz Strangely, updating again brought my intellisense back? Maybe I hadn't waited long enough for results to come in before. I'm sorry.

**Comment by nascode** [comment]
@mjbvz Thanks for the tip. I installed TS 2.3.4 and set "typescript.tsdk" setting to it. Then i got back my JS intellisense.

Looks like built in tsc on v1.14.0 is the culprit.

**Comment by pmaroncelli** [comment]
Same problem here. Intellisense in my typescript project stopped working since upgrading to 1.14. Downgrading to 1.13 solved the problem.

**Comment by venning** [comment]
Possibly related, the following JavaScript does not syntax highlight correctly in v1.14:

```javascript
{
    'd': '(';
}
var foo;
```

`var foo;` will be highlighted incorrectly

**Comment by serkanyersen** [comment]
**Deleting jsconfig.json also fixes this issue.**

Having the same problem, my jsconfig.json looks like this.
```json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": ["node_modules"]
}
```
it works fine if you delete the jsconfig.json file. I'm acquiring type from `@types/jest`

error looks like this: **jsconfig.json' does not contain document**
```ini
[Info  - 2:50:42 PM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 2:50:42 PM] Forking TSServer
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Error  - 2:55:22 PM] 'completions' request failed with error.
Error processing request. Project '/Users/serkanyersen/playground/test-unittests/jsconfig.json' does not contain document '/users/serkanyersen/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
Error: Project '/Users/serkanyersen/playground/test-unittests/jsconfig.json' does not contain document '/users/serkanyersen/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:75718:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77238:42)
    at ConfiguredProject.Project.getScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77243:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76551:51)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:84
    at Object.map (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1483:29)
    at ModuleBuilder.getReferencedFileInfos (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:31)
    at ModuleBuilder.updateFileReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76708:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76693:30)
    at ModuleBuilder.onProjectUpdateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76684:22)
```

**Comment by tafelito** [comment]
Same issue here, I think

This is my error log. Not using TS, just JSX with vscode 1.14. Didn't happen before. I also noticed that if I close and open the editor, it starts and it works for a few seconds and then it stops working and gives the error below.

```
[Error  - 10:56:45 PM] 'completions' request failed with error.
Error processing request. Project '/<project>/jsconfig.json' does not contain document 
'/.../library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
```

**Comment by tafelito** [comment]
OK disabling automatic type acquisition by adding this did the trick as mentioned here   #30122 

```
"typeAcquisition": {
    "enable": false
  },
```

**Comment by zanza00** [comment]
I have a similar problem in #30122 when installing with **yarn** but not when installing with **npm** 

Can anyone try to remove the entire `node_modules` folder and try with `npm` and see if the problem is still present?

**Comment by mjbvz** [comment]
To verify the fix, test the steps listed in this issue https://github.com/Microsoft/TypeScript/issues/17131
