### ISSUE TITLE
Fail to start vscode.typescript extension

### ISSUE THREAD

**Issue by Majirefy** [Microsoft/vscode#30716]
- VSCode Version: 1.14.1
- OS Version: macOS 10.12.5 (16F2104)

Steps to Reproduce:

1. Open Developer Tools for VS Code
2. Restart TypeScript Server in Command Palette, or just type something in a *.ts file.
3. There are error:

`[vscode.typescript]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.typescript: Error: [vscode.typescript]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.typescript
    at q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:398419)
    at Object.get workspaceFolders [as workspaceFolders] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:407824)
    at TypeScriptServiceClient.get mainWorkspaceRootPath [as mainWorkspaceRootPath] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:719:31)
    at servicePromise.Promise (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:375:29)
    at modulePath.then.then.then (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:346:42)
    at process._tickCallback (internal/process/next_tick.js:103:7)
e.onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] rejected promise not handled within 1 second
h.logExtensionHostMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [vscode-tslint] Failed to load tslint library. This failure is not reported to the user since there is no 'tslint.json' in the workspace: Error: [vscode-tslint] Failed to load tslint library. This failure is not reported to the user since there is no 'tslint.json' in the workspace
    at new ResponseError (/Users/majirefy/.vscode/extensions/eg2.tslint-0.16.0/node_modules/vscode-jsonrpc/lib/messages.js:40:28)
    at handleResponse (/Users/majirefy/.vscode/extensions/eg2.tslint-0.16.0/node_modules/vscode-jsonrpc/lib/main.js:305:48)
    at ChildProcess.callback (/Users/majirefy/.vscode/extensions/eg2.tslint-0.16.0/node_modules/vscode-jsonrpc/lib/main.js:486:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] rejected promise not handled within 1 second
h.logExtensionHostMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [vscode.typescript]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.typescript: Error: [vscode.typescript]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.typescript
    at q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:398419)
    at Object.get workspaceFolders [as workspaceFolders] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:407824)
    at TypeScriptServiceClient.get mainWorkspaceRootPath [as mainWorkspaceRootPath] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:719:31)
    at servicePromise.Promise (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:375:29)
    at modulePath.then.then.then (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:346:42)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

<img width="912" alt="2017-07-14 11 03 10" src="https://user-images.githubusercontent.com/3023607/28217700-9e8ebd76-68e8-11e7-894b-cc593f89b3a3.png">

Reproduces without extensions: Yes

This may lead to issue #30707

**Comment by michaelw85** [comment]
I have the same issue on a windows 10 machine starting mocha tests for an extension I'm working on.

**Comment by Hanano-Yuuki** [comment]
same issue on windows 10

**Comment by mjbvz** [comment]
Thanks. Looks like there is a bug in the TS extension when you open individual files. This is already fixed in [insiders](https://code.visualstudio.com/insiders)

You can also work around this issue by opening a folder in VSCode instead of individual files

**Comment by Majirefy** [comment]
@mjbvz I got same error when in an Ionic project. So it doesn't matter whether in a folder or not.

**Comment by mjbvz** [comment]
Fixed by 	d52b097

**Comment by mjbvz** [comment]
To verify, try opening a js file directly instead of opening a folder. Check that basic operations all work in the file, such as intellisense and go do definition
