### ISSUE TITLE
Changed/Deleted workspace should turn into untitled workspace

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#30864]
I think we need to listen to changes to the workspace config file and migrate a window into "Untitled Workspace" once:

* the underlying config file gets deleted or renamed or moved to a different location

Looks like the a similar transition that we now have for Untitled => Workspace needs to be supported the other way around as well.

**Comment by bpasero** [comment]
After discussion we will wait for more user feedback on this issue.

**Comment by sandy081** [comment]
With our new workspace config format, it is more easy to get into this state.

**Comment by bpasero** [comment]
After discussion we think we can install a watcher on the workspace file and if the file gets deleted:
* show a dialog telling the user
* provide an option to delete the workspace (which would bring the window back to empty state)
* provide an option to restore the workspace (which would flush the last known configuration model back to the file)

**Comment by bpasero** [comment]
@sandy081 one idea was to handle the deleted case more gracefully and not crash. I can see that when I delete a workspace while is is opened, immediately this crash happens:

```
shell.js:228 Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at parseWorkspaceFolders (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/workspace/common/workspace.js:108:33)
    at Object.toWorkspaceFolders (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/workspace/common/workspace.js:99:32)
    at WorkspaceService.onWorkspaceConfigurationChanged (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/configuration/node/configuration.js:427:53)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/configuration/node/configuration.js:219:110
    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
    at WorkspaceConfiguration.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/configuration/node/configuration.js:536:132)
    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/node/config.js:152:53
```

It seems that the `defaultConfig` in [here](https://github.com/Microsoft/vscode/blob/ben/34157/src/vs/workbench/services/configuration/node/configuration.ts#L605)  is not a good choice because it will not have any `folder` set. Should be at least a config that maybe has an empty array for `folders`.

**Comment by sandy081** [comment]
@bpasero Agreed showing empty workspace is better than what we have now. I would think still showing a message to user is good.

**Comment by bpasero** [comment]
Pushed a change to have a better `defaultConfig` fallback that does not result in a crash.
