### ISSUE TITLE
CodeHelper pegs out my CPU

### ISSUE THREAD

**Issue by phidias51** [Microsoft/vscode#30870]
After the recent upgrade to Version 1.14.1, CodeHelper now pegs out my CPU, operating at somewhere between 90 and 104%.

I'm running Mac OS 10.10.5 (Yosemite) with 8GB of RAM

**Comment by mjbvz** [comment]
Can you please run:

```bash
$ ps aux | grep -i code
```

in the terminal to identify the offending process name and its command line arguments. The second printed number for each entry is the CPU usage.

You can also identify the process in Activity Monitor and then search by pid

**Comment by phidias51** [comment]
2253 100.9 18.8  4802620 1580360   ??  R    10:48AM  48:41.69 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/Activx/.vscode/extensions/polymer.polymer-ide-0.5.0/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/Activx/.vscode/extensions/polymer.polymer-ide-0.5.0/node_modules/polymer-editor-service/lib/polymer-language-server.js --stdio

I suspect one of the plugins may be having a problem. I've had to restart Code a couple of times.  It never tells me which one is having the problem though. I assume there's a log somewhere with this info.

**Comment by phidias51** [comment]
I disabled my polymer-related plugins, but there doesn't seem to be much difference.

**Comment by mjbvz** [comment]
@phidias51 Did you also force kill the polymer process before restarting vscode? It may be lingering around

**Comment by phidias51** [comment]
I didn't. But when the plugin died again, I managed to get this stack trace.  This may be causing the problem (or may be another problem entirely).

```
Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at Object.provideCompletionItems (/Users/Activx/.vscode/extensions/Zignd.html-css-class-completion-1.7.0/out/src/extension.js:77:27)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:355556
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:63826
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:49058)
    at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:63789)
    at e.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:355510)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:364740
    at t._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:359002)
    at t.$provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:364702)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308956)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189275)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189930)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:443
```

**Comment by phidias51** [comment]
There's also this. Hope it helps.

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewTransitionArray(int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::TracingCpuProfiler::Create(v8::Isolate*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
15: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
16: v8::internal::HeapNumber::HeapNumberPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
17: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
18: 0x8d91fc84167
19: 0x8d920bc9c99

<--- Last few GCs --->

[2961:0x7f813a028000]  1698945 ms: Mark-sweep 1402.8 (1458.6) -> 1402.8 (1458.6) MB, 13714.0 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1afaff3a7831 <JS Object>
    0: builtin exit frame: defineProperty(aka defineProperty)(this=0x2917c5802311 <undefined>,0x124ca5e2e759 <an Object with map 0x2de23d6a2e91>,0x2917c5803019 <String[4]: hour>,0x124ca5e2e721 <an Object with map 0x3b76bf603179>)

    1: toDateTimeOptions(aka toDateTimeOptions) [native i18n.js:~912] [pc=0x8d920bc9c99](this=0x2917c5802311 <undefined>,S=0x2917c5802311 <undefined>,bN=0x1afaff3c085...
```

**Comment by phidias51** [comment]
After I disabled the plugins, closed the Code application and killed the Code Helper process, and restarted Code, the CPU utilization fell back to normal.

**Comment by mjbvz** [comment]
Thanks, please try filing some issues against these two plugin since they seem to be the root cause of the high cpu usage
