### ISSUE TITLE
failed to open new window after sleep and wakeup on mac

### ISSUE THREAD

**Issue by simpzan** [Microsoft/vscode#30894]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
quokka-vscode|Wal|1.0.40
vscode-clang|mit|0.2.2
atom-keybindings|ms-|2.9.1
cpptools|ms-|0.12.0
sublime-keybindings|ms-|2.9.1
advanced-new-file|pat|0.5.0
java|red|0.7.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Leave a vscode window open for a long time, 
2. put mac sleep and wake it up,
3. open a dir with `code dir_path`, the new opened window is blank, and there's some error in developer tools console
```
path.js:1142 Uncaught Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Function.Module._resolveFilename (module.js:461:31)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/renderer/init.js:13:1)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/renderer/init.js:151:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
index.js:17Uncaught ReferenceError: require is not defined
    at index.js:17
```

Reproduces without extensions: Yes/No

**Comment by blynx** [comment]
Same here,
blank screen for example when the mac returns from hibernate / restarts and reopens all windows.
Seems like the documents are actually opened. The cursor changes when hovering about the window, but the windows is just blank.

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.7
pegjs-language|Sir|0.1.0
language-pde|Tob|0.1.21
vscode-color|ans|0.4.1
vscode-eslint|dba|1.2.11
auto-close-tag|for|0.4.3
code-runner|for|0.6.28
cpptools|ms-|0.12.1
sublime-keybindings|ms-|2.9.1
php-docblocker|nei|1.2.0
incrementor|nms|0.1.0
vscode-arduino|vsc|0.2.4

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2259
