### ISSUE TITLE
Find all references and Rename Symbol do not work with --allowJS = true

### ISSUE THREAD

**Issue by otake** [Microsoft/vscode#30948]
Having the allowJS Typescript set to true, makes "Find all References" not work. Also, Rename Symbol just throws an error "Sorry, rename failed to execute."

- VSCode Version: 1.14.1
- OS Version: MacOS Sierra 10.12.4

Steps to Reproduce:

1. Add allowJs: true to compilerOptions in tsconfig.json
2. Reload Window
3. Try to "Find All References" on anything in a .ts file
4. Always returns no results
5. Remove allowJs option from tsconfig.json
6. Reload Window
7. Try to "Find All References" again and it works!

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I suspect this is related to #30425

If you open the output pane in VSCode and go to the TypeScript section, do you see any errors messages?

**Comment by otake** [comment]
Possibly, but I think this problem has been happening for me since before version 1.13. And not all Intellisense is broken for me. Autocomplete and hot clicks (cmd+click) shortucts seem to work fine for me.

Here is what I see in the output panel when I do "Find All References":
```
[Error  - 3:50:01 PM] 'references' request failed with error.
Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:68774:23)
    at IOSession.Session.getProjects (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:72620:42)
    at IOSession.Session.getReferences (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:72708:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:72066:61)
    at /Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:73305:88
    at IOSession.Session.executeWithRequestId (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:73296:28)
    at IOSession.Session.executeCommand (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:73305:33)
    at IOSession.Session.onMessage (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:73325:35)
    at Interface.<anonymous> (/Users/sample/sites/tv/ui/node_modules/typescript/lib/tsserver.js:74477:27)
    at emitOne (events.js:96:13)
```

**Comment by otake** [comment]
Same thing is happening to other developers on my team also. We do share the same tsconfig.json in our git repo.

**Comment by the-spyke** [comment]
@mjbvz I have the same error in output as @otake has, but my project is pure JS and it has a simple `jsconfig.json` in the root:

```
{
    "compilerOptions": {
        "target": "es2016"
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by globerlaxmikant** [comment]
Find all references not working for JavaScript files.
Using Babel in project, find all references not pointing to uses from another files.

**Comment by dlinx** [comment]
Find all references not working for JavaScript files if it is referred in another file.

Using JavaScript with ES7 support.
Steps to reproduce.
1) Export a class XYZ from file xyz.js.
2) Import that class in file abc.js and create instance of XYZ
3) Try to Find All References for XYZ in file xyz.js, it will not point to file abc.js

**Comment by peabnuts123** [comment]
I am in the same boat as @the-spyke

**Comment by mjbvz** [comment]
@otake Are you still seeing this in VS Code 1.18?

**Comment by otake** [comment]
Yes, it is still happening. Same error in the output, same result as I toggle `allowJs: true/false`.

**Comment by mjbvz** [comment]
@otake And you are using TS 2.6? (TS version is shown in the status bar in the lower right hand corner)

If so, please try collecting the full TS server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Run the `Typescript: Open TS Server log` command in vs code and look in the `tsserver.log` file in the opened directory

If you are able to share the logs, I can look through them to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by otake** [comment]
Actually no, I am using my workspace version - TypeScript 2.2.1, but version 2.6 produced the same result.

Here is my tsserver.log. I only included the parts right around where the `No Project` error shows up.
```
{"seq":0,"type":"response","command":"quickinfo","request_seq":28,"success":true,"body":{"kind":"function","kindModifiers":"","start":{"line":352,"offset":10},"end":{"line":352,"offset":22},"displayString":"function getShapeIcon(icon: IShapeIcon): JSX.IntrinsicElements","documentation":"","tags":[]}}
Info 1755 [15:28:26.34] request:
    {"seq":29,"type":"request","command":"quickinfo","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":16}}
Info 1756 [15:28:26.34] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1757 [15:28:26.34] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1758 [15:28:26.35] 29::quickinfo: elapsed time (in milliseconds) 1.0181
Info 1759 [15:28:26.35] response:
    {"seq":0,"type":"response","command":"quickinfo","request_seq":29,"success":true,"body":{"kind":"function","kindModifiers":"","start":{"line":352,"offset":10},"end":{"line":352,"offset":22},"displayString":"function getShapeIcon(icon: IShapeIcon): JSX.IntrinsicElements","documentation":"","tags":[]}}
Info 1760 [15:28:29.198] request:
    {"seq":30,"type":"request","command":"references","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":16}}
Err 1761  [15:28:29.208] Exception on executing command {"seq":30,"type":"request","command":"references","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":16}}:

    No Project.

    Error: No Project.
    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81131:23)
    at IOSession.Session.getProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85879:42)
    at IOSession.Session.getReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85977:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85247:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86660:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86689:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
Info 1762 [15:28:29.208] response:
    {"seq":0,"type":"response","command":"references","request_seq":30,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81131:23)\n    at IOSession.Session.getProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85879:42)\n    at IOSession.Session.getReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85977:37)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85247:61)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86660:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86689:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87881:27)\n    at emitOne (events.js:96:13)\n    at Interface.emit (events.js:191:7)\n    at Interface._onLine (readline.js:241:10)\n    at Interface._normalWrite (readline.js:384:12)\n    at Socket.ondata (readline.js:101:10)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:191:7)\n    at readableAddChunk (_stream_readable.js:178:18)\n    at Socket.Readable.push (_stream_readable.js:136:10)\n    at Pipe.onread (net.js:560:20)"}
Info 1763 [15:28:29.221] request:
    {"seq":31,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","startLine":352,"startOffset":16,"endLine":352,"endOffset":16}}
Info 1764 [15:28:29.221] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1765 [15:28:29.221] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1766 [15:28:29.221] 31::getApplicableRefactors: elapsed time (in milliseconds) 0.5031
Info 1767 [15:28:29.221] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":31,"success":true,"body":[]}
Info 1768 [15:28:30.713] request:
    {"seq":32,"type":"request","command":"occurrences","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":18}}
Info 1769 [15:28:30.714] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1770 [15:28:30.714] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1771 [15:28:30.720] 32::occurrences: elapsed time (in milliseconds) 6.7359
Info 1772 [15:28:30.720] response:
    {"seq":0,"type":"response","command":"occurrences","request_seq":32,"success":true,"body":[{"start":{"line":288,"offset":26},"end":{"line":288,"offset":38},"file":"/mypath/app/xv/diagram/Shape.tsx","isWriteAccess":false},{"start":{"line":352,"offset":10},"end":{"line":352,"offset":22},"file":"/mypath/app/xv/diagram/Shape.tsx","isWriteAccess":true}]}
Info 1773 [15:28:31.91] request:
    {"seq":33,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","startLine":352,"startOffset":10,"endLine":352,"endOffset":22}}
Info 1774 [15:28:31.91] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1775 [15:28:31.91] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1776 [15:28:31.92] 33::getApplicableRefactors: elapsed time (in milliseconds) 1.0031
Info 1777 [15:28:31.92] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":33,"success":true,"body":[]}
Info 1778 [15:28:32.140] request:
    {"seq":34,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","startLine":288,"startOffset":26,"endLine":288,"endOffset":38}}
Info 1779 [15:28:32.140] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1780 [15:28:32.140] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1781 [15:28:32.141] 34::getApplicableRefactors: elapsed time (in milliseconds) 1.1401
Info 1782 [15:28:32.141] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":34,"success":true,"body":[]}
Info 1783 [15:28:50.306] request:
    {"seq":35,"type":"request","command":"quickinfo","arguments":{"file":"/mypath/app/xv/workflowBuilder/components/TaskStepSettings.tsx","line":117,"offset":3}}
Info 1784 [15:28:50.307] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1785 [15:28:50.307] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1786 [15:28:50.307] 35::quickinfo: elapsed time (in milliseconds) 1.0803
Info 1787 [15:28:50.308] response:
    {"seq":0,"type":"response","command":"quickinfo","request_seq":35,"success":false,"message":"No content available."}
```

**Comment by mjbvz** [comment]
@otake Thanks. I'm not sure what is going wrong or what questions to ask further to investigate this, so have moved this issue over to the TypeScript repo for further investigation: https://github.com/Microsoft/TypeScript/issues/20357

Please continue to follow up on that issue.

Closing as upstream
