### ISSUE TITLE
Not able to debug test case (written using protractor )

### ISSUE THREAD

**Issue by Ashutosh-Tripathy** [Microsoft/vscode#31214]
We have written test cases using protractor(selenium based). I am able to run test cases successfully though vscode without debugging but when I am running it in debug mode it is displaying error in debug console (grunt is configured to run test cases)
launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${env:APPDATA}\\npm\\node_modules\\grunt-cli\\bin\\grunt",
            "stopOnEntry": true
        }
    ]
}
```

debug console:
```
Running "modify-and-run:all" (modify-and-run) task
[2017-07-21 19:04:49.809] [INFO] modify-and-run - There are no describe appenders configured.
[2017-07-21 19:04:49.841] [INFO] modify-and-run - Executing: 2/2 ui and 1/1 non-ui tests from a total of: 3
[2017-07-21 19:04:49.841] [INFO] modify-and-run - Number of automated tests: 3/3 (100%)
Running "protractor:modify" (protractor) task
Error: listen EADDRINUSE :::28972
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Agent.Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Agent.Server.listen (net.js:1366:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:75:44)
    at node.js:404:3
```
part of successful console output:
```
Running "modify-and-run:all" (modify-and-run) task
[2017-07-21 19:15:42.967] [INFO] modify-and-run - There are no describe appenders configured.
[2017-07-21 19:15:43.310] [INFO] modify-and-run - Executing: 2/2 ui and 1/1 non-ui tests from a total of: 3
[2017-07-21 19:15:43.310] [INFO] modify-and-run - Number of automated tests: 3/3 (100%)
Running "protractor:modify" (protractor) task
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
problem trying to remove a folder
Started
```

- VSCode Version: 1.14.1
- OS Version:Windows 7 Professional N 64-bit
- Node: 5.10.0

Reproduces without extensions: Yes

**Comment by weinand** [comment]
If you see a "error: listen EADDRINUSE :::28972" this means that the port is already used.

I don't know how "protractor" works but make sure that 
your program `${env:APPDATA}\\npm\\node_modules\\grunt-cli\\bin\\grunt` does the right thing when an command line argument `--inspect-brk=12345` is added by VS Code.
(this happens when you start debugging with your debug configuration from above).
