### ISSUE TITLE
Cannot launch vscode from the command line

### ISSUE THREAD

**Issue by szefany** [Microsoft/vscode#31222]
- VSCode Version: 1.14.2
- OS Version: Linux x64 4.4.0-64-generic (Ubuntu 14.04)

Steps to Reproduce:
1. Simply run `code` or `code <dir>/<file>` in the terminal and it cannot launch vscode. Downgrading to 1.13 can fix the problem.

Reproduces without extensions: Yes

The output of `code --verbose`:
```
(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.
(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.

(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.

(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.

(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.

(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.
(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.
(code:10048): dconf-CRITICAL **: unable to create directory '/run/user/szefany/dconf': Permission denied.  dconf will not work properly.
[10077:0722/024515.981541:ERROR:gl_context_glx.cc(187)] Failed to create GL context with glXCreateContextAttribsARB.
[10077:0722/024515.981607:ERROR:gpu_info_collector.cc(50)] gl::init::CreateGLContext failed
[10077:0722/024515.981610:ERROR:gpu_info_collector.cc(118)] Could not create context for info collection.
[10077:0722/024515.981618:ERROR:gpu_init.cc(85)] gpu::CollectGraphicsInfo failed (fatal).
[10077:0722/024515.982416:ERROR:gpu_child_thread.cc(327)] Exiting GPU process due to errors during initialization
Error: listen EACCES /run/user/szefany/Code-1.14.2-main.sock
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1382:7)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:133560
    at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:74325)
    at Object.t.serve (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:133490)
    at i (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:312624)
    at A (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:313713)
```

After double checking, I found only `/run/user/1000` instead of `/run/user/szefany`, and that's why there are some `unable to create directory` errors above. Then I created a soft link `/run/user/szefany` to `/run/user/1000` and the problem was solved.

**Comment by joaomoreno** [comment]
Do you have the `XDG_RUNTIME_DIR` variable set?
