### ISSUE TITLE
Cannot read property 'offset' of undefined, when updating configuration

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#31348]
For the following extension code:

```ts
const tsConfig = workspace.getConfiguration('typescript');
await tsConfig.update('tsdk', 'abc', false);
```

I'm seeing this error when the users has only opened a folder instead of a workspace:

```
TypeError: Cannot read property 'offset' of undefined
    at ConfigurationEditingService.applyEditsToBuffer (file:///Users/matb/projects/vscode/out/vs/workbench/services/configuration/node/configurationEditingService.js:59:57)
    at ConfigurationEditingService.writeToBuffer (file:///Users/matb/projects/vscode/out/vs/workbench/services/configuration/node/configurationEditingService.js:52:22)
    at file:///Users/matb/projects/vscode/out/vs/workbench/services/configuration/node/configurationEditingService.js:47:59
    at Object.notifySuccess [as _notify] (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.derive._creator._run (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.derive._creator._completed (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at Object.enter (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:747:28)
    at _Base.Class.derive._creator._run (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.derive._creator._setCompleteValue (file:///Users/matb/projects/vscode/out/vs/base/common/winjs.base.raw.js:1052:18)
```

When a workspace is opened, I do not see this

**Comment by sandy081** [comment]
@mjbvz I am not getting this error. Can you help me in reproducing this?

**Comment by sandy081** [comment]
Please reopen this if you still see this issue.

**Comment by sandy081** [comment]
Duplicate of #38196
