### ISSUE TITLE
Cannot read property 'roots' of null, after closing folder

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#31350]
**Version**: 58332b486e7e5196f4b21edc93081686c0509e55
**OS**: Mac 10.12.5

**Repo**
1. Open a folder using the file menu
1. Close the folder using the file menu

**Bug**
```
Cannot read property 'roots' of null: TypeError: Cannot read property 'roots' of null
    at ConfigurationManager.initLaunches (file:///Users/matb/projects/vscode/out/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.js:258:63)
    at new ConfigurationManager (file:///Users/matb/projects/vscode/out/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.js:201:18)
    at create (file:///Users/matb/projects/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:143:43)
    at InstantiationService.createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:71:29)
    at new DebugService (file:///Users/matb/projects/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:53:67)
    at create (file:///Users/matb/projects/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:143:43)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:202:41)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:150:29)
```

**Comment by yeradis** [comment]
After updating the the lastes version i´m getting this error
there is a "blank" windows and nothing else

```
workbench.ts:395Cannot read property 'roots' of null: TypeError: Cannot read property 'roots' of null
    at e.initLaunches (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2303102)
    at new e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2301835)
    at t.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2414)
    at t._createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1082553)
    at t.createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1081324)
    at new t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:283708)
    at t.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2414)
    at t._createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1082553)
    at t._createAndCacheServiceInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1083524)
    at t._getOrCreateServiceInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1082714)
e.startup @ workbench.ts:395
index.js:41 [uncaught exception]: TypeError: Cannot read property 'roots' of null
onError @ index.js:41
index.js:44 TypeError: Cannot read property 'roots' of null
    at e.initLaunches (debugConfigurationManager.ts:295)
    at new e (debugConfigurationManager.ts:235)
    at t.create (types.ts:168)
    at t._createInstance (instantiationService.ts:162)
    at t.createInstance (instantiationService.ts:78)
    at new t (debugService.ts:121)
    at t.create (types.ts:168)
    at t._createInstance (instantiationService.ts:162)
    at t._createAndCacheServiceInstance (instantiationService.ts:230)
    at t._getOrCreateServiceInstance (instantiationService.ts:170)
```

**Comment by isidorn** [comment]
Dup of 31364
