### ISSUE TITLE
Cannot open window without workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31364]
Latest insiders

Open a new window and I see following error

```
Cannot read property 'roots' of null: TypeError: Cannot read property 'roots' of null
    at ConfigurationManager.initLaunches (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.js:258:63)
    at new ConfigurationManager (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.js:201:18)
    at create (file:///Users/sandy081/work/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:143:43)
    at InstantiationService.createInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:71:29)
    at new DebugService (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:53:67)
    at create (file:///Users/sandy081/work/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:143:43)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:202:41)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:150:29)
Workbench.startup @ workbench.js:190
index.js:41 [uncaught exception]: TypeError: Cannot read property 'roots' of null
onError @ index.js:41
index.js:44 TypeError: Cannot read property 'roots' of null
    at ConfigurationManager.initLaunches (debugConfigurationManager.js:258)
    at new ConfigurationManager (debugConfigurationManager.js:201)
    at create (types.js:164)
    at InstantiationService._createInstance (instantiationService.js:143)
    at InstantiationService.createInstance (instantiationService.js:71)
    at new DebugService (debugService.js:53)
    at create (types.js:164)
    at InstantiationService._createInstance (instantiationService.js:143)
    at InstantiationService._createAndCacheServiceInstance (instantiationService.js:202)
    at InstantiationService._getOrCreateServiceInstance (instantiationService.js:150)
```

**Comment by isidorn** [comment]
@sandy081 I will release new insiders bacuease of this
