### ISSUE TITLE
unfolding selected groups of folded code issue

### ISSUE THREAD

**Issue by abdhass** [Microsoft/vscode#31446]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
sublime-babel-vscode|jos|0.2.6
format-php|Kas|1.1.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|3.1.6
laravel-blade|one|1.8.1
laravel5-snippets|one|1.3.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1. fold two divs of code
```
<div>
  <h1></h1>
</div>
<div>
  <h1></h1>
</div>
```
2. Highlight both folded divs.
3. unfold the second div
4. Notice how the highlighted region starts at end of first row

Reproduces without extensions: Yes

Step 1:
![image](https://user-images.githubusercontent.com/8301868/28614599-460e66d8-71ee-11e7-92c0-b97e7cd3750f.png)

Step 2:
![image](https://user-images.githubusercontent.com/8301868/28614612-548898be-71ee-11e7-9b3b-ba49f6ad06b1.png)

Step 3:
![image](https://user-images.githubusercontent.com/8301868/28614716-b31aa408-71ee-11e7-8530-97ff08a41207.png)

**Comment by alexandrudima** [comment]
@aeschli The call that changes the selection in the editor comes from `FoldingController`:

When expanding the second fold region:
```
Error
    at Cursor.setSelections (file:///Users/alex/src/vscode/out/vs/editor/common/controller/cursor.js:248:37)
    at CodeEditor.CommonCodeEditor.setSelections (file:///Users/alex/src/vscode/out/vs/editor/common/commonCodeEditor.js:330:25)
    at FoldingController.updateHiddenAreas (file:///Users/alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:331:29)
    at file:///Users/alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:301:35
    at Model.TextModelWithDecorations._changeDecorations (file:///Users/alex/src/vscode/out/vs/editor/common/model/textModelWithDecorations.js:173:26)
    at Model.TextModelWithDecorations.changeDecorations (file:///Users/alex/src/vscode/out/vs/editor/common/model/textModelWithDecorations.js:145:29)
    at CodeEditor.CommonCodeEditor.changeDecorations (file:///Users/alex/src/vscode/out/vs/editor/common/commonCodeEditor.js:556:31)
    at FoldingController.onEditorMouseUp (file:///Users/alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:294:25)
    at file:///Users/alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:198:88
    at CallbackList.invoke (file:///Users/alex/src/vscode/out/vs/base/common/callbackList.js:58:43)"
```
