### ISSUE TITLE
Code Helper  CPU higher 99%

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#31617]
- VSCode Version:1.14.2
- OS Version:10.12.6

Steps to Reproduce:

1.when i use vscode  i find my mac cpu higher 99%.
2.then i quit vscode  then i find cpu also higher 99%.

this image was i quit my vscode 

![](http://7xs2tr.com1.z0.glb.clouddn.com/zhiqiang21/2017-07-28-014256.jpg?imageslim)

![](http://7xs2tr.com1.z0.glb.clouddn.com/zhiqiang21/2017-07-28-015430.jpg?imageslim)

Reproduces without extensions: No

**Comment by cvharris** [comment]
I'm experiencing the same thing. Only started happening today as well. Turned off all extensions and closed other open windows. Then tried restarting the app. Then tried restarting my whole laptop. Doesn't seem to matter what kind of codebase we're dealing with either: experienced on an Angular2 project, a Wordpress PHP project, and a regular ol' HTML/CSS project. These three did have a lot of files though, excluding node_modules.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by zhiqiang21** [comment]
i will try it .

**Comment by cvharris** [comment]
@bpasero like I said I had turned off all extensions and still experienced the performance impact. However, after yesterday's release I have not experienced this issue any longer

**Comment by bpasero** [comment]
@cvharris then it must be fixed 👍

**Comment by cvharris** [comment]
So it cropped up again and this time I think it has to do with the Emmet-helper. It occurs only when I'm working with HTML-like files, usually in the typeahead loading. The window will either freeze or slow down tremendously, so this time I opened Activity Monitor and quit one of the Code Helper's running at 100% CPU. VSCode then threw an error notification saying 'Extension host terminated unexpectedly. Please reload the window to recover'. This error made me think it was an extension I was using that was the culprit, but when I opened dev tools the only thing throwing errors was from the emmetHelper.js

```
Cannot match against 'undefined' or 'null'.: TypeError: Cannot match against 'undefined' or 'null'.
    at Object.doComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/node_modules/vscode-emmet-helper/out/emmetHelper.js:42:56)
    at DefaultCompletionItemProvider.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/out/defaultCompletionProvider.js:28:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:358833
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:63028
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:48235)
    at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:62991)
    at e.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:358787)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:368883
    at t._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:363145)
    at t.$provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:368845)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308751)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:188848)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I'll disable Emmet and see if I get it again

**Comment by baslr** [comment]
Same here. After VSC stays open for days, one code helper process will hang up with high cpu usage. I cloded VSC but the code helper process wasn't killed.
The right column is CPU usage.
![bildschirmfoto 2017-08-22 um 18 57 22](https://user-images.githubusercontent.com/1494154/29577522-079c2b9a-876c-11e7-9269-1b1e167de228.png)

**Comment by ramya-rao-a** [comment]
@cvharris Do you still see the issue and feel its to do when using html like files?

**Comment by cvharris** [comment]
It was due to a combination of VSCodeVim and AutoCloseTags/AutoRenameTags. I uninstalled both of the later extensions and haven't experienced the problem since.

**Comment by ramya-rao-a** [comment]
@zhiqiang21 @baslr Any updates? Do you still see the issue with extensions disabled?
