### ISSUE TITLE
Error: No such module: atom_renderer_v8_util

### ISSUE THREAD

**Issue by yuankeyang** [Microsoft/vscode#31701]
- VSCode Version: 1.14.2 (Date: 2017-07-19 Commit: cb82feb)
- OS Version:  Windows 7 Pro SP1 (ver:  6.1.7601)
- Exception:
> Error: No such module: atom_renderer_v8_util
    at process.atomBinding (e:\workspace\JavaScript\electron-quick-start\node_modules\electron\dist\resources\electron.asar\common\atom-binding-setup.js:4:14)
    at Object.<anonymous> (e:\workspace\JavaScript\electron-quick-start\node_modules\electron\dist\resources\electron.asar\renderer\init.js:24:22)
    at Object.<anonymous> (e:\workspace\JavaScript\electron-quick-start\node_modules\electron\dist\resources\electron.asar\renderer\init.js:159:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:424:7)

Steps to Reproduce:

1. Debug [electron-quick-start](https://github.com/electron/electron-quick-start)
2. Debug Main Process

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This does not seem related to VSCode. Please provide more info if you believe this is a VSCode issue or try asking the question on [stackoverflow](https://stackoverflow.com)
