### ISSUE TITLE
Error: connect ETIMEDOUT 52.216.226.96:443

### ISSUE THREAD

**Issue by liangzeng** [Microsoft/vscode#31719]
- VSCode Version: 1.15.0
- OS Version: os x ei capitan 10.11.6

./scripts/npm.sh install

```
/Users/liangzeng/Downloads/vscode/node_modules/electron-mksnapshot/download-mksnapshot.js:16
  if (error != null) throw error
                     ^

Error: connect ETIMEDOUT 52.216.226.96:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-foreground-love@0.1.0 (node_modules/windows-foreground-love):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-foreground-love@0.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-mutex@0.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-mksnapshot@1.6.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liangzeng/.electron-gyp/.npm/_logs/2017-07-30T01_13_40_555Z-debug.log

```

**Comment by liangzeng** [comment]
I update electron-mksnapshot to 1.7.1 is ok!

**Comment by gustamora** [comment]
Lets try to range over by "lang"
