### ISSUE TITLE
Cannot launch VSCode without Internet connection.

### ISSUE THREAD

**Issue by Sue425** [Microsoft/vscode#31808]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
vscode-janus-debug|otr|0.0.9
standard|shi|0.2.3
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
What problem are you seeing when launching without Internet connection?

**Comment by Sue425** [comment]
When I'm not connected to the Internet, the application doesn't even start. I click on the shortcut and nothing happens. I've tried from commandline as well, still nothing. But in the moment, when I'm connected to the Internet, everything works as should. Any idea, how can I use VSCode without Internet? ('Cause I don't have access to the Internet everywhere I go :) ). Thanks!

**Comment by weinand** [comment]
And this reproduces even without extensions?

**Comment by Sue425** [comment]
Yes.

**Comment by kieferrm** [comment]
@Sue425 can you pls open a command prompt and start Vs Code from the command line using the `--verbose` option. Can you pls attach here?

**Comment by Sue425** [comment]
This is the output I got:

[3604:0809/134255.012:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
←[93m[main 13:42:55]←[0m Starting VS Code in verbose mode
←[93m[main 13:42:55]←[0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
←[93m[main 13:42:55]←[0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[3604:0809/134300.013:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
←[93m[main 13:43:00]←[0m IPC#vscode-machineId
←[93m[main 13:43:01]←[0m IPC#vscode-workbenchLoaded
[3604:0809/134305.016:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[3604:0809/134310.019:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[3604:0809/134315.022:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[3604:0809/134315.866:INFO:CONSOLE(20)] "ApplicationInsights:Sender", source: C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\applicationinsights\Library\Logging.js (20)
[3604:0809/134320.025:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.

**Comment by weinand** [comment]
@Sue425 is this from a Windows system running in a VM?

**Comment by weinand** [comment]
@joaomoreno do the messages from above ring a bell?

**Comment by weinand** [comment]
BTW, when I launch VS Code on Windows 10 without having an Internet connection I seem to get the same verbose output.
But VS Code works fine!

```
C:\Users\weinand>code --verbose

[8900:0809/174953.714:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[93m[main 17:49:53][0m Starting VS Code in verbose mode
[93m[main 17:49:53][0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[93m[main 17:49:53][0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[93m[main 17:49:55][0m IPC#vscode-machineId
[93m[main 17:49:56][0m IPC#vscode-workbenchLoaded
[8900:0809/174957.364:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[8900:0809/174957.365:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[8900:0809/174957.365:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[8900:0809/174957.365:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[8900:0809/174957.365:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[8900:0809/174957.484:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[8900:0809/174957.485:INFO:CONSOLE(28)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[8900:0809/174958.730:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[8900:0809/175003.746:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[8900:0809/175008.760:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[8900:0809/175009.991:INFO:CONSOLE(20)] "ApplicationInsights:Sender", source: C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\applicationinsights\Library\Logging.js (20)
[8900:0809/175013.765:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[8900:0809/175018.780:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[8900:0809/175023.793:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
WARNING: Promise with no error callback:6
{ exception: Error: net::ERR_NAME_NOT_RESOLVED,
  error: null,
  promise:
   { _creator: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NAME_NOT_RESOLVED,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NAME_NOT_RESOLVED
[uncaught exception in main]: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:4:78286)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[8900:0809/175025.016:INFO:CONSOLE(29)] "net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:4:78286)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[8900:0809/175028.801:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[8900:0809/175033.819:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[8900:0809/175038.824:WARNING:dns_config_service_win.cc(661)] Failed to read DnsConfig.
[93m[main 17:50:39][0m Lifecycle#window-before-close 1
[93m[main 17:50:39][0m Lifecycle#unload() 1
[93m[main 17:50:39][0m Lifecycle#window-before-close 1
[93m[main 17:50:39][0m Lifecycle#window-close 1
[93m[main 17:50:39][0m Lifecycle#window-all-closed
[93m[main 17:50:39][0m Lifecycle#before-quit
[93m[main 17:50:39][0m App#will-quit: disposing resources

```

**Comment by joaomoreno** [comment]
@Sue425 If you use a process manager (eg Process Hacker), can you see Code.exe laying around?

**Comment by Sue425** [comment]
@weinand Yes, it's Windows, but I'm using 8.1

**Comment by joaomoreno** [comment]
I mean with a process manager: an application which lists all running processes in your system, like [Process Hacker](http://processhacker.sourceforge.net/).
