### ISSUE TITLE
NPE in WindowsShellHelper

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31944]
Steps to reproduce:

1. Open and kill terminal very quickly

This can likely happen when the terminal is killed during a wmic.exe call.

```
Cannot read property 'on' of null: TypeError: Cannot read property 'on' of null
    at new WindowsShellHelper (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.js:26:24)
    at file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:98:90
    at Object.notifySuccess [as _notify] (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:92:61
    at CallbackList.invoke (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/base/common/event.js:91:40)
    at ChildProcess.<anonymous> (file:///C:/Users/Daniel/Documents/dev/Microsoft/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:527:45)
```

**Comment by roblourens** [comment]
I can still repro this with the same stack, I don't think the PR fixes the right issue. It fails on this line, because `this._xterm` is null: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.ts#L41

A null xterm object is passed into the constructor, which implies that the terminal instance is null, so I think the problem is the terminalInstance being disposed while `processReady` is running:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L164
