### ISSUE TITLE
MacOS FSWatcher issues

### ISSUE THREAD

**Issue by ifrantar** [Microsoft/vscode#32029]
- VSCode Version: 1.14.2
- OS Version: MacOS 10.12.6

Steps to Reproduce:

We are not able to reproduce this issue all the time, it happens sometimes but we are not sure about what triggers it.

We have some users at work using VS Code on Linux Mint and `fs.inotify.max_user_watches=524288` solved the issue but on MacOS we are getting the following error:

```
/Users/ivanfrantar/CODE/core/node_modules/duplexer/index.js:31
    writer.on("drain", function() {
          ^

TypeError: Cannot read property 'on' of undefined
    at duplex (/Users/ivanfrantar/CODE/core/node_modules/duplexer/index.js:31:11)
    at Object.module.exports (/Users/ivanfrantar/CODE/core/node_modules/stream-combiner/index.js:8:17)
    at childrenOfPid (/Users/ivanfrantar/CODE/core/node_modules/ps-tree/index.js:50:6)
    at kill (/Users/ivanfrantar/CODE/core/node_modules/nodemon/lib/monitor/run.js:271:7)
    at Function.run.kill (/Users/ivanfrantar/CODE/core/node_modules/nodemon/lib/monitor/run.js:204:9)
    at Bus.<anonymous> (/Users/ivanfrantar/CODE/core/node_modules/nodemon/lib/monitor/run.js:336:7)
    at emitOne (events.js:120:20)
    at Bus.emit (events.js:210:7)
    at restartBus (/Users/ivanfrantar/CODE/core/node_modules/nodemon/lib/monitor/watch.js:162:7)
    at FSWatcher.filterAndRestart (/Users/ivanfrantar/CODE/core/node_modules/nodemon/lib/monitor/watch.js:145:16)
```
The error comes form nodemon but based on the experience on Mint we think is related with the FS Events... kind of like https://github.com/Microsoft/vscode/issues/7950#issuecomment-320277006 but on MacOS.

Reproduces without extensions: We have not been able to confirm this...

**Comment by bpasero** [comment]
This should be reported to nodemon.

**Comment by ifrantar** [comment]
@remojansen ^^^
