### ISSUE TITLE
Build from Source: Build fails

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#3205]
Following : https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

I ran: 
```
git clone https://github.com/microsoft/vscode
cd vscode
npm install -g mocha gulp
scripts\npm install
```

`scripts\npm install` fails. My versions: 

```
D:\REPOS\vscode>python -V
Python 2.7.9

D:\REPOS\vscode>node -v
v5.2.0

D:\REPOS\vscode>npm -v
3.3.12
```

The output `scripts\npm install > output.txt 2>&1`: 
```
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"5.2.0","npm":"3.3.12"})
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> Code@0.10.10 preinstall D:\REPOS\vscode
> node build/npm/preinstall.js


> Code@0.10.10 postinstall D:\REPOS\vscode
> npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/

npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
D:\REPOS\vscode\extensions\vscode-api-tests\jade -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\jade\bin\jade
D:\REPOS\vscode\extensions\vscode-api-tests\mkdirp -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\mkdirp\bin\cmd.js
D:\REPOS\vscode\extensions\vscode-api-tests\uuid -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\node-uuid\bin\uuid
D:\REPOS\vscode\extensions\vscode-api-tests\semver -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\semver\bin\semver
D:\REPOS\vscode\extensions\vscode-api-tests\mocha -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\mocha\bin\mocha
D:\REPOS\vscode\extensions\vscode-api-tests\_mocha -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\mocha\bin\_mocha
D:\REPOS\vscode\extensions\vscode-api-tests\strip-bom -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\strip-bom\cli.js
D:\REPOS\vscode\extensions\vscode-api-tests\sshpk-sign -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\sshpk\bin\sshpk-sign
D:\REPOS\vscode\extensions\vscode-api-tests\sshpk-conv -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\sshpk\bin\sshpk-conv
D:\REPOS\vscode\extensions\vscode-api-tests\sshpk-verify -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\sshpk\bin\sshpk-verify
D:\REPOS\vscode\extensions\vscode-api-tests\tsc -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\typescript\bin\tsc
D:\REPOS\vscode\extensions\vscode-api-tests\tsserver -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\typescript\bin\tsserver
D:\REPOS\vscode\extensions\vscode-api-tests\har-validator -> D:\REPOS\vscode\extensions\vscode-api-tests\node_modules\har-validator\bin\har-validator

> vscode-api-tests@0.0.1 postinstall D:\REPOS\vscode\extensions\vscode-api-tests
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: *
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

vscode-api-tests@0.0.1 D:\REPOS\vscode\extensions\vscode-api-tests
├── typescript@1.7.5 
└─┬ vscode@0.11.1 
  ├─┬ glob@5.0.15 
  │ ├─┬ inflight@1.0.4 
  │ │ └── wrappy@1.0.1 
  │ ├── inherits@2.0.1 
  │ ├─┬ minimatch@3.0.0 
  │ │ └─┬ brace-expansion@1.1.3 
  │ │   ├── balanced-match@0.3.0 
  │ │   └── concat-map@0.0.1 
  │ ├── once@1.3.3 
  │ └── path-is-absolute@1.0.0 
  ├─┬ gulp-remote-src@0.4.0 
  │ ├─┬ event-stream@3.1.7 
  │ │ ├── duplexer@0.1.1 
  │ │ ├── from@0.1.3 
  │ │ ├── map-stream@0.1.0 
  │ │ ├── pause-stream@0.0.11 
  │ │ ├── split@0.2.10 
  │ │ ├── stream-combiner@0.0.4 
  │ │ └── through@2.3.8 
  │ ├─┬ node.extend@1.1.5 
  │ │ └── is@3.1.0 
  │ ├─┬ request@2.58.0 
  │ │ ├── aws-sign2@0.5.0 
  │ │ ├── bl@0.9.5 
  │ │ ├── caseless@0.10.0 
  │ │ ├── extend@2.0.1 
  │ │ ├─┬ har-validator@1.8.0 
  │ │ │ └── bluebird@2.10.2 
  │ │ ├── hawk@2.3.1 
  │ │ ├─┬ http-signature@0.11.0 
  │ │ │ ├── asn1@0.1.11 
  │ │ │ ├── assert-plus@0.1.5 
  │ │ │ └── ctype@0.5.3 
  │ │ ├─┬ mime-types@2.0.14 
  │ │ │ └── mime-db@1.12.0 
  │ │ └── qs@3.1.0 
  │ ├─┬ through2@0.5.1 
  │ │ ├─┬ readable-stream@1.0.33 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── isarray@0.0.1 
  │ │ │ └── string_decoder@0.10.31 
  │ │ └── xtend@3.0.0 
  │ └─┬ vinyl@0.2.3 
  │   └── clone-stats@0.0.1 
  ├─┬ gulp-symdest@1.0.0 
  │ ├─┬ event-stream@3.3.2 
  │ │ └── split@0.3.3 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├── queue@3.1.0 
  │ └─┬ vinyl-fs@1.0.0 
  │   ├─┬ duplexify@3.4.2 
  │   │ ├── end-of-stream@1.0.0 
  │   │ └── readable-stream@2.0.5 
  │   ├─┬ glob-stream@4.1.1 
  │   │ ├── glob@4.5.3 
  │   │ ├─┬ glob2base@0.0.12 
  │   │ │ └── find-index@0.1.1 
  │   │ ├── minimatch@2.0.10 
  │   │ ├── ordered-read-streams@0.1.0 
  │   │ ├── through2@0.6.5 
  │   │ └─┬ unique-stream@2.2.1 
  │   │   ├─┬ json-stable-stringify@1.0.1 
  │   │   │ └── jsonify@0.0.0 
  │   │   └─┬ through2-filter@2.0.0 
  │   │     └─┬ through2@2.0.1 
  │   │       └── readable-stream@2.0.5 
  │   ├─┬ glob-watcher@0.0.8 
  │   │ └─┬ gaze@0.5.2 
  │   │   └─┬ globule@0.1.0 
  │   │     ├─┬ glob@3.1.21 
  │   │     │ ├── graceful-fs@1.2.3 
  │   │     │ └── inherits@1.0.2 
  │   │     ├── lodash@1.0.2 
  │   │     └── minimatch@0.2.14 
  │   ├── graceful-fs@3.0.8 
  │   ├─┬ merge-stream@0.1.8 
  │   │ └── through2@0.6.5 
  │   ├── object-assign@2.1.1 
  │   ├─┬ strip-bom@1.0.0 
  │   │ ├── first-chunk-stream@1.0.0 
  │   │ └── is-utf8@0.2.1 
  │   ├── through2@0.6.5 
  │   └── vinyl@0.4.6 
  ├─┬ gulp-vinyl-zip@1.1.2 
  │ ├─┬ event-stream@3.3.2 
  │ │ └── split@0.3.3 
  │ ├─┬ through2@0.6.5 
  │ │ └── xtend@4.0.1 
  │ ├─┬ vinyl@0.4.6 
  │ │ └── clone@0.2.0 
  │ ├─┬ vinyl-fs@0.3.14 
  │ │ ├─┬ defaults@1.0.3 
  │ │ │ └── clone@1.0.2 
  │ │ ├─┬ glob-stream@3.1.18 
  │ │ │ ├── glob@4.5.3 
  │ │ │ ├── minimatch@2.0.10 
  │ │ │ └── unique-stream@1.0.0 
  │ │ └── glob-watcher@0.0.6 
  │ ├─┬ yauzl@2.4.1 
  │ │ └─┬ fd-slicer@1.0.1 
  │ │   └── pend@1.2.0 
  │ └─┬ yazl@2.3.0 
  │   └── buffer-crc32@0.2.5 
  ├─┬ mocha@2.4.5 
  │ ├── commander@2.3.0 
  │ ├─┬ debug@2.2.0 
  │ │ └── ms@0.7.1 
  │ ├── diff@1.4.0 
  │ ├── escape-string-regexp@1.0.2 
  │ ├─┬ glob@3.2.3 
  │ │ ├── graceful-fs@2.0.3 
  │ │ └─┬ minimatch@0.2.14 
  │ │   └── sigmund@1.0.1 
  │ ├── growl@1.8.1 
  │ ├─┬ jade@0.26.3 
  │ │ ├── commander@0.6.1 
  │ │ └── mkdirp@0.3.0 
  │ └── supports-color@1.2.0 
  ├─┬ request@2.69.0 
  │ ├── aws-sign2@0.6.0 
  │ ├─┬ aws4@1.2.1 
  │ │ └── lru-cache@2.7.3 
  │ ├─┬ bl@1.0.3 
  │ │ └─┬ readable-stream@2.0.5 
  │ │   ├── process-nextick-args@1.0.6 
  │ │   └── util-deprecate@1.0.2 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@1.0.0-rc3 
  │ │ ├── async@1.5.2 
  │ │ └── mime-types@2.1.10 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ chalk@1.1.1 
  │ │ │ ├── ansi-styles@2.1.0 
  │ │ │ ├── escape-string-regexp@1.0.4 
  │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ └── ansi-regex@2.0.0 
  │ │ │ ├── strip-ansi@3.0.0 
  │ │ │ └── supports-color@2.0.0 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ ├─┬ is-my-json-valid@2.13.0 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ └── jsonpointer@2.0.0 
  │ │ └─┬ pinkie-promise@2.0.0 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.2.2 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.2 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.7.4 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@0.2.0 
  │ │   ├─┬ dashdash@1.13.0 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.14.0 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.10 
  │ │ └── mime-db@1.22.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.1 
  │ ├── qs@6.0.2 
  │ ├── stringstream@0.0.5 
  │ ├── tough-cookie@2.2.1 
  │ └── tunnel-agent@0.4.2 
  ├── semver@5.1.0 
  └─┬ source-map-support@0.3.3 
    └─┬ source-map@0.1.32 
      └── amdefine@1.0.0 


> json@0.1.0 postinstall D:\REPOS\vscode\extensions\json
> cd server && npm install && npm run compile && cd ..


> vscode-json-server@0.0.1 postinstall D:\REPOS\vscode\extensions\json\node_modules\vscode-json-server
> tsc -p .

json@0.1.0 D:\REPOS\vscode\extensions\json
└── vscode-json-server@0.0.1 


> vscode-json-server@0.0.1 compile D:\REPOS\vscode\extensions\json\server
> tsc -p .

src/jsonContributions.ts(10,28): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsoncontributions/bowerJSONContribution.ts(7,48): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsoncontributions/globPatternContribution.ts(7,64): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsoncontributions/packageJSONContribution.ts(7,48): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsoncontributions/projectJSONContribution.ts(7,48): error TS2307: Cannot find module 'vscode-languageserver'.
src/test/textEditSupport.ts(7,39): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsonCompletion.ts(14,120): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsonDocumentSymbols.ts(10,77): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsonFormatter.ts(8,75): error TS2307: Cannot find module 'vscode-languageserver'.
src/jsonHover.ts(12,79): error TS2307: Cannot find module 'vscode-languageserver'.
src/server.ts(14,8): error TS2307: Cannot find module 'vscode-languageserver'.
src/test/completion.test.ts(14,157): error TS2307: Cannot find module 'vscode-languageserver'.
src/test/documentSymbols.test.ts(15,133): error TS2307: Cannot find module 'vscode-languageserver'.
src/test/formatter.test.ts(8,101): error TS2307: Cannot find module 'vscode-languageserver'.
src/test/hover.test.ts(15,109): error TS2307: Cannot find module 'vscode-languageserver'.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! vscode-json-server@0.0.1 compile: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-json-server@0.0.1 compile script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vscode-json-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get their info via:
npm ERR!     npm owner ls vscode-json-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\REPOS\vscode\extensions\json\server\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "extensions/json/" "install" "extensions/json/"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! json@0.1.0 postinstall: `cd server && npm install && npm run compile && cd ..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the json@0.1.0 postinstall script 'cd server && npm install && npm run compile && cd ..'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the json package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd server && npm install && npm run compile && cd ..
npm ERR! You can get their info via:
npm ERR!     npm owner ls json
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\REPOS\vscode\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! Code@0.10.10 postinstall: `npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Code@0.10.10 postinstall script 'npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Code package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/
npm ERR! You can get their info via:
npm ERR!     npm owner ls Code
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\REPOS\vscode\npm-debug.log
```

The `npm-debug.log` is available here: https://gist.github.com/basarat/e0904fd0b8959da1c3ba 

:rose:

**Comment by egamma** [comment]
A workaround is to copy the npm modules folder from an installed vscode (`C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app`) into the checked out vscode folder. This is what I think most of us do, so there is an issue and update the doc if needed.

**Comment by aeschli** [comment]
I can't reproduce on Ubuntu, node v4.2.6, npm 2.14.12 using the steps above. Seems to work for me.
As workaround manually run `npm install` inside `extensions/json`

**Comment by basarat** [comment]
@aeschli Most likely an npm `3.x` issue. I haven't tried but suspect `v2.x` npm would work fine. 

> As workaround manually run npm install inside extensions/json

I'll give that a go if I get the time next weekend :rose:

**Comment by nhhockeyplayer** [comment]
I see this introduced in beta.7

npm wont build typescript anymore via packages.json

this problem basically breaks rimraf too and the various ways of running scripts so its not even possible to clean

and noticed .bin is gone... and what ever logic ensued to correct never lived

so we have to jump out to the shell and build from project root dir

node node_modules/typescript/bin/tsc -project .

this isnt fun especially wondering what portion of the operation actually succeeded or went arye to perform more trouble... I would think rimraf is highly sensitive to removing every file on your drive if it gets hijacked

**Comment by basarat** [comment]
Just gave `scripts\npm install ` another with the latest code and it worked just fine.

However the next step `gulp watch` fails: 

```
D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:39577
                        resolvedName = resolveModuleName(moduleName, containingFile, options, host).resolvedModule;
                                                                                                   ^

TypeError: Cannot read property 'resolvedModule' of undefined
    at resolveModuleNamesWorker (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:39577:100)
    at processImportedModules (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:40249:35)
    at findSourceFile (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:40225:17)
    at processSourceFile (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:40146:27)
    at processRootFile (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:40056:13)
    at D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:39602:60
    at Object.forEach (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:945:30)
    at Object.createProgram (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:39602:16)
    at synchronizeHostData (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:48342:33)
    at Object.getEmitOutput (D:\REPOS\vscode\node_modules\typescript\lib\typescript.js:51328:13)
```

![image](https://cloud.githubusercontent.com/assets/874898/13540839/0194f598-e2ad-11e5-8eac-6141a0297191.png)

I'll create a separate issue for that once I've investigated that a bit more. Going out for a suit fitting (:necktie: :jeans:) for now :rose:

**Comment by mehedi101** [comment]
I am using windows platform and Homestead ; using these command work for me :

Full steps :

npm install --no-bin-links

gulp

npm rebuild node-sass . -- its fix the issue..

gulp

Now gulp --- working.
