### ISSUE TITLE
Automated smoketest failed in "Debugging JavaScript autodetects program attribute for launch.json"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#32135]
After merging PR #32050 the automated smoke test failed with this error:

```
2017-08-07T07:19:07.5367300Z [0m  1) Smoke Test Suite Debugging JavaScript autodetects program attribute for launch.json:
2017-08-07T07:19:07.5394730Z [0m[31m     SyntaxError: Unexpected token } in JSON at position 385[0m[90m
2017-08-07T07:19:07.5419360Z       at JSON.parse (<anonymous>)
2017-08-07T07:19:07.5439110Z       at JavaScriptDebug.<anonymous> (out/areas/javascript-debug.js:41:31)
2017-08-07T07:19:07.5454090Z       at Generator.next (<anonymous>)
2017-08-07T07:19:07.5467850Z       at fulfilled (out/areas/javascript-debug.js:8:58)
2017-08-07T07:19:07.5481780Z       at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Further investigation showed that commit #a9ebfd8814d71e4e92af776dcbf133535b3e81e4 contained the culprit in debugConfigurationManager.ts:

![2017-08-08_12-43-48](https://user-images.githubusercontent.com/1898161/29068563-9db3b7dc-7c37-11e7-9cc6-0973bd44d16b.png)

After the user selects a debug environment, the content of the launch.json is not passed as an IContent but just as a string. As a consequence the 'value' attribute is undefined and the indexOf doesn't exist.

**Comment by weinand** [comment]
@isidorn I've added a workaround. Please review and/or replace by a proper fix.

**Comment by isidorn** [comment]
Looks like a proper fix to me, thanks
