### ISSUE TITLE
Automated Smoketest failed in "Debugging JavaScript autodetects program attribute for launch.json"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#32133]
The automated smoke test failed after this commit: 

```
2017-08-07T07:19:07.5367300Z [0m  1) Smoke Test Suite Debugging JavaScript autodetects program attribute for launch.json:
2017-08-07T07:19:07.5394730Z [0m[31m     SyntaxError: Unexpected token } in JSON at position 385[0m[90m
2017-08-07T07:19:07.5419360Z       at JSON.parse (<anonymous>)
2017-08-07T07:19:07.5439110Z       at JavaScriptDebug.<anonymous> (out/areas/javascript-debug.js:41:31)
2017-08-07T07:19:07.5454090Z       at Generator.next (<anonymous>)
2017-08-07T07:19:07.5467850Z       at fulfilled (out/areas/javascript-debug.js:8:58)
2017-08-07T07:19:07.5481780Z       at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

indexOf error after selecting a debug environment

**Comment by weinand** [comment]
duplicate of #32135
