### ISSUE TITLE
Syntax tokenizer errors out on CentOS 6.6

### ISSUE THREAD

**Issue by GlenHertz** [Microsoft/vscode#32193]
- VSCode Version: code-stable-code_1.14.2-1500506907_amd64.tar.g
- OS Version: CentOS 6.6

Steps to Reproduce:

1. Untar vs-code
2. code
3. Ctrl-,

Then the following message appears "Error: the mode has failed while tokenizing the input".  Screenshot:

![image](https://user-images.githubusercontent.com/1714451/29125800-a93e9aa0-7cea-11e7-88d0-da8c379a6785.png)

In the xterm, I get the following:

```xterm
WARNING: Promise with no error callback:6
{ exception: Error: net::ERR_NAME_NOT_RESOLVED,
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NAME_NOT_RESOLVED,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NAME_NOT_RESOLVED
[uncaught exception in main]: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (/home/hertz/a/RedHatEnterpriseWorkstation6.4/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:4:78286)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Reproduces without extensions: Yes

The issue was originally reported to the [julia-vscode extension](https://github.com/JuliaEditorSupport/julia-vscode/issues/248) but was found to be unrelated to it.  Linking it here for cross-reference.

**Comment by weinand** [comment]
So this error occurs when you try to open the "User Settings"?
What happens when you switch to "Workspace Settings"?

**Comment by GlenHertz** [comment]
I get the same error with "Workspace Settings".

**Comment by GlenHertz** [comment]
Hi @weinand.  Is there anything else I can try to help debug this?

**Comment by aeschli** [comment]
Please run with all extensions disabled (use `code --disable-extensions`) to see if an extension causes this.
Otherwise, it would be great if you can share the settings file that causes this.

**Comment by GlenHertz** [comment]
Oops. Can you re-open?  @aeschli I get the same error with `code --disable-extensions`.  I'm using a very fresh install.

**Comment by aeschli** [comment]
- Can open the the dev tools (Help > Toggle Developper Tools) and check if there is something in the console?

**Comment by Tyriar** [comment]
Moving to @alexandrudima as the error is related to tokenization.

@GlenHertz I would recommend updating to 1.15.1 and seeing if the issue still reproduces there.

**Comment by alexandrudima** [comment]
@GlenHertz

Is there any error printed in the developer tools console? `Help` > `Toggle Developer Tools` ?

Can you perhaps share the file that produces the error byte-for-byte ?

**Comment by GlenHertz** [comment]
I'm having trouble reproducing now.  I get:

```
code: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by code)
code: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by code)
code: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by code)
code: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /opt/VSCode-linux-x64-1.15/libnode.so)
code: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /opt/VSCode-linux-x64-1.15/libnode.so)
```

I was 99% sure this was working on a CentOS 6.6 so I'm trying to debug why it isn't working now.  I checked with1.14 and 1.15.  There are a few other Issues about getting Code to work with RHEL 6 but it doesn't seem supported yet.

**Comment by alexandrudima** [comment]
I think @Tyriar would know best, here are the deps we want in our rpm package -- https://github.com/Microsoft/vscode/blob/5391eb9ff7475c94f02160624ef1ffce58d44727/resources/linux/rpm/dependencies.json

**Comment by GlenHertz** [comment]
I figured it out.  When it was "working" I had anaconda setting LD_LIBRARY_PATH to anaconda-4.3.1/lib which has most of the missing libraries.  Then when I run with 1.15.1 I get the following errors in the developer console:

```
shell.ts:423 /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node): Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (<embedded>:8:10954)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:69:4)
e.onUnexpectedError @ shell.ts:423
messageService.ts:125 The mode has failed while tokenizing the input.
e.doShow @ messageService.ts:125
shell.ts:423 /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node): Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (<embedded>:8:10954)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:69:4)
e.onUnexpectedError @ shell.ts:423
messageService.ts:125 The mode has failed while tokenizing the input.
e.doShow @ messageService.ts:125
shell.ts:423 /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node): Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (<embedded>:8:10954)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:69:4)
e.onUnexpectedError @ shell.ts:423
messageService.ts:125 The mode has failed while tokenizing the input.
e.doShow @ messageService.ts:125
shell.ts:423 /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node): Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (<embedded>:8:10954)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:69:4)
e.onUnexpectedError @ shell.ts:423
messageService.ts:125 The mode has failed while tokenizing the input.
e.doShow @ messageService.ts:125
shell.ts:423 /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node): Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (<embedded>:8:10954)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/opt/VSCode-linux-x64-1.15/resources/app/node_modules/oniguruma/lib/oniguruma.js:69:4)
e.onUnexpectedError @ shell.ts:423
messageService.ts:125 The mode has failed while tokenizing the input.
e.doShow @ messageService.ts:125
shell.ts:423 net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (/opt/VSCode-linux-x64-1.15/resources/app/out/vs/code/electron-main/main.js:4:77973)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
e.onUnexpectedError @ shell.ts:423
```

It doesn't seem like Anaconda ships with a glibc to resolve the missing GLIBC_2.14.  I tried installing glibc 2.14 and adding it to LD_LIBRARY_PATH but then I get a segfault.

Note: I'm installing from the tar.gz.

**Comment by Tyriar** [comment]
Ah I missed this, we only support Red Hat/CentOS 7+ https://code.visualstudio.com/docs/supporting/requirements#_platforms
