### ISSUE TITLE
Can't search extensions behind a http proxy

### ISSUE THREAD

**Issue by pffang** [Microsoft/vscode#32210]
- VSCode Version: code --version
1.14.2
cb82febafda0c8c199b9201ad274e25d9a76874e
- OS Version: Ubuntu 14.04

Reproduces without extensions: Yes

below is verbose：
```
code -w --verbose
[main 11:26:09 AM] Starting VS Code in verbose mode
[main 11:26:09 AM] from: /usr/share/code/resources/app
[main 11:26:09 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: true,
  w: true,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[main 11:26:09 AM] IPC#vscode-machineId
[main 11:26:10 AM] IPC#vscode-workbenchLoaded
[29370:0810/112613.992523:INFO:CONSOLE(29)] "An unknown error occurred. Please consult the log for more details.", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
[29370:0810/112613.992710:INFO:CONSOLE(28)] "WARNING: Promise with no error callback:104", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[29370:0810/112613.992733:INFO:CONSOLE(28)] "[object Object]", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[29370:0810/112614.053808:INFO:CONSOLE(28)] "An unknown error occurred. Please consult the log for more details.", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[29370:0810/112624.649312:INFO:CONSOLE(20)] "ApplicationInsights:Sender", source: /usr/share/code/resources/app/node_modules/applicationinsights/Library/Logging.js (20)
WARNING: Promise with no error callback:6
{ exception: Error: net::ERR_NAME_NOT_RESOLVED,
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NAME_NOT_RESOLVED,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NAME_NOT_RESOLVED
[uncaught exception in main]: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:78286)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[29370:0810/112639.061142:INFO:CONSOLE(29)] "net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:78286)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
```

**Comment by joaomoreno** [comment]
Can you ask your system administrator to give you access to our commonly used domains?

https://code.visualstudio.com/docs/setup/network#_common-hostnames

**Comment by DarkLite1** [comment]
Seems related to #30850

**Comment by pffang** [comment]
@DarkLite1 Not the same. I can't get the extensions list.

@joaomoreno I can't.
All of our internet access include DNS lookup have to go through http proxy.
Local dns server only resolve the intranet address.

**Comment by joaomoreno** [comment]
@pffang That's the problem. `ERR_NAME_NOT_RESOLVED` means the domain can't be found. This is an issue with your system, not Code itself.

**Comment by pffang** [comment]
@joaomoreno But it work fine in version 1.6.1
9e4e44c19e393803e2b05fe2323cf4ed7e36880e
I think maybe the old version can do DNS lookup through http proxy.
Many applications can do DNS lookup through http proxy. I wish vscode can do it too.

**Comment by DarkLite1** [comment]
My issue in #30850 was similar. Everything worked fine one version before and then all of a sudden it stopped working due to the transparent proxy not being recognized. I think this should be investigated deeper. more users will most likely run into this issue.

Secure traffic, with https, should als be supported behind a proxy.

**Comment by joaomoreno** [comment]
@pffang Does Google Chrome work in your setup?

**Comment by pffang** [comment]
@joaomoreno Google Chrome works fine.

**Comment by joaomoreno** [comment]
Open this in Chrome: `chrome://net-internals/#proxy` what shows up?

**Comment by pffang** [comment]
@joaomoreno 
```
Proxy server for FTP: 127.0.0.1:3128
Proxy server for HTTP: 127.0.0.1:3128
Proxy server for HTTPS: 127.0.0.1:3128
Bypass list: 
  localhost
  127.0.0.0/8
  ::1
Source: GSETTINGS
```

**Comment by pffang** [comment]
The proxy also export to environment variable http_proxy, https_proxy and ftp_proxy.
Most software work fine.

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/setup/network#_proxy-server-support

Can you try:

`code --proxy-server=127.0.0.1:3128`

**Comment by pffang** [comment]
@joaomoreno I don't  know  why, but it  works fine again on version
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
without the parameter  `--proxy-server=127.0.0.1:3128`
