### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#32575]
_From @jacobrillema on August 15, 2017 15:35_

Latest insiders build 1.16.0-insider date of 8/15 is crashing. I could not find the offending extension right away but found this extension was causing the issue. Not sure how much this is helpful from the developer tools. Maybe something with the util.js file?

```
index.js:5 Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
onError @ index.js:5
events.js:163 Uncaught Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ /C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:29 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ /C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:29
```

_Copied from original issue: Microsoft/vscode-github-issues-prs#19_

**Comment by gregvanl** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/32530
