### ISSUE TITLE
Intermittent Git Smoke Test failures

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#32659]
We are seeing these fail on Linux from time to time. More often recently:

```
2017-08-16T18:58:44.7605180Z [0m  1) Smoke Test Suite Git verifies current changes are picked up by Git viewlet:
2017-08-16T18:58:44.7644380Z [0m[31m     AssertionError: '1' == 2[0m[90m
2017-08-16T18:58:44.7667470Z       at Context.<anonymous> (out/tests/git.js:40:24)
2017-08-16T18:58:44.7686750Z       at Generator.next (<anonymous>)
2017-08-16T18:58:44.7713700Z       at fulfilled (out/tests/git.js:8:58)
2017-08-16T18:58:44.7736430Z [0m
2017-08-16T18:58:44.7748810Z 
2017-08-16T18:58:44.7795930Z [0m  2) Smoke Test Suite Git verifies 'app.js' diff viewer changes:
2017-08-16T18:58:44.7822890Z [0m[31m     Error: the string "Cannot fine app.js in a viewlet." was thrown, throw an Error :)[0m[90m
2017-08-16T18:58:44.7846060Z   
2017-08-16T18:58:44.7866750Z [0m
2017-08-16T18:58:44.7891230Z [0m  3) Smoke Test Suite Git stages 'app.js' changes and checks stage count:
2017-08-16T18:58:44.7919180Z [0m[31m     Error: the string "app.js was not found in SCM viewlet" was thrown, throw an Error :)[0m[90m
2017-08-16T18:58:44.7959630Z       at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-08-16T18:58:44.7981480Z [0m
2017-08-16T18:58:44.7993650Z 
2017-08-16T18:58:44.8015910Z [0m  4) Smoke Test Suite Git stages, commits change to 'app.js' locally and verifies outgoing change:
2017-08-16T18:58:44.8043010Z [0m[31m     Error: the string "app.js was not found in SCM viewlet" was thrown, throw an Error :)[0m[90m
2017-08-16T18:58:44.8067210Z       at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-08-16T18:58:44.8092840Z [0m
```

**Comment by joaomoreno** [comment]
@chrmarti You mean they often succeed but sometimes fail?

**Comment by chrmarti** [comment]
Yes. I should add that I have seen this with the release branch.
