### ISSUE TITLE
Error: invalid provider

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#32783]
* start vs code on a folder with `.git`.
* kill the extension host process

```
shell.js:225 invalid provider: Error: invalid provider
    at SCMService.setActiveSCMProvider (file:///Users/alex/src/vscode/out/vs/workbench/services/scm/common/scmService.js:80:23)
    at SCMService.set [as activeProvider] (file:///Users/alex/src/vscode/out/vs/workbench/services/scm/common/scmService.js:55:22)
    at file:///Users/alex/src/vscode/out/vs/workbench/services/scm/common/scmService.js:105:42
    at Object.dispose (file:///Users/alex/src/vscode/out/vs/base/common/lifecycle.js:47:21)
    at file:///Users/alex/src/vscode/out/vs/workbench/api/electron-browser/mainThreadSCM.js:215:85
    at Array.forEach (native)
    at MainThreadSCM.dispose (file:///Users/alex/src/vscode/out/vs/workbench/api/electron-browser/mainThreadSCM.js:215:18)
    at ExtensionService._stopExtensionHostProcess (file:///Users/alex/src/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:64:30)
    at ExtensionService._onExtensionHostCrashed (file:///Users/alex/src/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:102:18)
    at file:///Users/alex/src/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:79:30
```

**Comment by joaomoreno** [comment]
`setActiveSCMProvider` is gone! :tada:
