### ISSUE TITLE
Uncaught exception when trying to restore a tab pointing at a deleted file

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#32895]
- VSCode Version: Code - Insiders 1.16.0-insider (0626479859787fa87c7c57ba19195b939050a843, 2017-08-21T05:17:04.920Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.17.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
Ruby|reb|0.15.0
vim|vsc|0.9.0

(1 theme extensions excluded)

---

I believe this happens when you have an opened tab that's pointing at a file that has been deleted on disk. You can get into this state via hot exit as the tabs are not individually checked when they are restored, only when you try open them.

![image](https://user-images.githubusercontent.com/2193314/29528505-1fc88a5e-8651-11e7-8f86-f262da992be1.png)

![image](https://user-images.githubusercontent.com/2193314/29528513-2506d0f2-8651-11e7-84f0-04c6052d2276.png)

The steps I used to get to this:

1. Open a folder with a saved workspace that contains a file that's been deleted
2. Ctrl+w multiple times

**Comment by bpasero** [comment]
@Tyriar I cannot reproduce, here is what I do:
* open a folder (or workspace)
* open some files
* shutdown Code
* from OS delete a file that was opened in Code but was not the active file
* restart Code
* close tabs via Cmd+W until I see an error about the deleted file

=> the error however is the typical one you get when you try to open a file that does not exist, not the error you are reporting.

Can you maybe refine the steps or try to reproduce running out of sources with a better stack?

**Comment by Tyriar** [comment]
I see this now:

![image](https://user-images.githubusercontent.com/2193314/29652209-4ace6e6c-8859-11e7-89a9-b55c9af02b54.png)

When I repro'd this it was on a workspace that was restored that I hadn't touched in quite a while (2-4 weeks?), so I swiftly closed all the tabs and ran into this. Let's close for now as the repro steps are bad.

**Comment by Tyriar** [comment]
Just saw this again when rapidly closing tabs on a workspace I was using yesterday

```
Unable to open 'User Settings': Cannot read property 'uri' of null.: Error: Unable to open 'User Settings': Cannot read property 'uri' of null.
    at t.doHandleSetInputError (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:644112)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:643713
    at Object.v [as _notify] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:52974)
    at Object.enter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:56466)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:57787)
    at n.Class.derive._oncancel._error (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:57304)
    at l (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:60830)
    at n.Class.derive.join.r.forEach.$.then.o.(anonymous function) (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:60937)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:52394)
    at Object.enter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:55959)
```

Not sure what settings file was the problem there though. Maybe it's something to do with settings, perhaps there is a race condition when disposing? /cc @sandy081

**Comment by Tyriar** [comment]
Hit this again:

```
messageService.ts:125 Unable to open 'User Settings': Cannot read property 'lineNumber' of null.: Error: Unable to open 'User Settings': Cannot read property 'lineNumber' of null.
    at t.doHandleSetInputError (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:29:667984)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:29:667585
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:52974)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:55959)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:57787)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:57228)
    at l (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:60723)
    at n.Class.derive.join.r.forEach.$.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:60937)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:52394)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:28:55959)
```

I finally have a good repro:

1. Open settings
2. Open another file
3. Reload window
4. Press ctrl+w twice rapidly

The issue happens when settings.json is closed while it's still initializing (the window reload before closing the files means it will start initialization on the first ctrl+w).

@sandy081 please consider fixing this for August if possible, I've hit it about 5 times so far.

**Comment by sandy081** [comment]
@Tyriar Thanks for providing steps. Will consider for August.

**Comment by Tyriar** [comment]
@sandy081 thanks for the quick turn around 😃
