### ISSUE TITLE
npm ERR! invalid: @emmetio/css-parser@0.4.0 /home/markus/tmp/vscode/extensions/emmet/node_modules/@emmetio/css-parser

### ISSUE THREAD

**Issue by octoploid** [Microsoft/vscode#32941]
On Linux vscode fails to build:
```
 % ./scripts/npm.sh install --arch=x64 && gulp vscode-linux-x64 
...
[11:38:43] Finished 'optimize-vscode' after 29 s                                         
[11:38:43] Starting 'vscode-linux-x64'...   
Unhandled Rejection at: Promise Promise {   
  <rejected> { Error: Command failed: npm list --production --parseable --depth=99999    
npm ERR! invalid: @emmetio/css-parser@0.4.0 /home/markus/tmp/vscode/extensions/emmet/node_modules/@emmetio/css-parser                                                              

    at ChildProcess.exithandler (child_process.js:270:12)                                
    at emitTwo (events.js:125:13)           
    at ChildProcess.emit (events.js:213:7)  
    at maybeClose (internal/child_process.js:927:16)                                     
    at Socket.stream.socket.on (internal/child_process.js:348:11)                        
    at emitOne (events.js:115:13)           
    at Socket.emit (events.js:210:7)        
    at Pipe._handle.close [as _onclose] (net.js:545:12)                                  
  killed: false,                            
  code: 1,                                  
  signal: null,                             
  cmd: 'npm list --production --parseable --depth=99999' } } reason: { Error: Command failed: npm list --production --parseable --depth=99999                                      
npm ERR! invalid: @emmetio/css-parser@0.4.0 /home/markus/tmp/vscode/extensions/emmet/node_modules/@emmetio/css-parser                                                              

    at ChildProcess.exithandler (child_process.js:270:12)                                
    at emitTwo (events.js:125:13)           
    at ChildProcess.emit (events.js:213:7)  
    at maybeClose (internal/child_process.js:927:16)                                     
    at Socket.stream.socket.on (internal/child_process.js:348:11)                        
    at emitOne (events.js:115:13)           
    at Socket.emit (events.js:210:7)        
    at Pipe._handle.close [as _onclose] (net.js:545:12)                                  
  killed: false,                            
  code: 1,                                  
  signal: null,                             
  cmd: 'npm list --production --parseable --depth=99999' } 


 % gulp --version
[11:47:51] CLI version 3.9.1
[11:47:51] Local version 3.9.1
 % npm --version
3.10.8

```

**Comment by ramya-rao-a** [comment]
Can you do a `git clean -xfd` and try again?

**Comment by octoploid** [comment]
Oh, I already did. It doesn't help.

**Comment by ramya-rao-a** [comment]
@Tyriar had another idea of using `gulp vscode-linux-x64 --max_old_space_size=4096` to ensure node has enough memory

If the issue is still isn't fixed, I'll try on an linux machine tomorrow.

**Comment by octoploid** [comment]
Unfortunately --max_old_space_size=4096 doesn't help.

**Comment by Tyriar** [comment]
I can't seem to reproduce and our build machines seem fine as well. I'm running npm@3.10.10, perhaps that's the issue? Could you try running `npm i -g npm@3.10.10` and seeing if that fixes it?

You could also try installing that particular module in a new folder and see if you run into a problem:

```
mkdir tmp
cd tmp
npm init -y
npm i -S git://github.com/ramya-rao-a/css-parser.git#370c480ac103bd17c7bcfb34bf5d577dc40d3660
npm list
```

**Comment by octoploid** [comment]
@Tyriar Updating to npm@3.10.10 does fix the issue. Thanks.
Maybe you should mention it in your documentation?

**Comment by ramya-rao-a** [comment]
cc @joaomoreno About need for npm@3.10.10 and adding it to documentation
