### ISSUE TITLE
When starting to debug hosted SPFx receiving ""hamburgerCallback must not be undefined"

### ISSUE THREAD

**Issue by DennisKuhn** [Microsoft/vscode#33037]
Since yesterday morning, NZ-time, when I start to debug my hosted SPFx webpart, I receive two exceptions.  After "ignoring"/F5 the exceptions, it seems to run sweet. 

First exception:

    Error: ***The value for "hamburgerCallback" must not be undefined
       at Function.e.isNotNullOrUndefined (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-11.019/sp-webpart-workbench-assembly_en-us_1103575b589894e6f7c32232400ee52c.js:273:1058)
       at e.get [as hamburgerCallback] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-11.019/sp-webpart-workbench-assembly_en-us_1103575b589894e6f7c32232400ee52c.js:1276:17281)
       at e._onRender (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-11.019/sp-webpart-workbench-assembly_en-us_1103575b589894e6f7c32232400ee52c.js:1262:22876)
       at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-11.019/sp-webpart-workbench-assembly_en-us_1103575b589894e6f7c32232400ee52c.js:1262:22699
       at https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_1a333542.js:22:15411

Second exception:

    Error: Sys.InvalidOperationException: Operation is not valid due to the current state of the object.
        at Function.Error.create (https://r1.res.office365.com/o365/versionless/shellcoreming2am_90c8efd1.js:65:13)
        at Function.Error.invalidOperation (https://r1.res.office365.com/o365/versionless/shellcoreming2am_90c8efd1.js:137:19)
        at Function._o365cl.a.b (https://r1.res.office365.com/o365/versionless/shellcoreming2am_90c8efd1.js:2479:12319)
        at _o365sg2c.r.b.f (https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_1a333542.js:20:1641)
        at _o365sg2c.r.a (https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_1a333542.js:20:858)
        at Function.O365Shell.InvokeSuiteAPILoaded (https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_1a333542.js:22:16618)
        at _o365sg2p.Loader.h (https://r1.res.office365.com/o365/versionless/shellplusg2m_90bca886.js:36:11288)

Any help would be greatly appreciated :-)

**Comment by DennisKuhn** [comment]
It happens during loading. At the initial startup of the workbench, before I can add the webpart to the page: 

gulp serve --nobrowser:

    [04:51:32] Starting subtask 'serve'...
    Starting api server on port 5432.
    Registring api: /getwebparts
    Registring api: /*.*
    Registring api: /workbench
    [04:51:41] Finished subtask 'serve' after 8.96 s
    [04:51:41] Finished 'serve' after 49 s
    [04:51:41] Server started https://localhost:4321
    [04:51:41] LiveReload started on port 35729
    [04:51:41] ==================[ Finished ]==================
    [04:51:42] Project ilog version: 0.2.5
    [04:51:42] Build tools version: 2.5.3
    [04:51:42] Node version: v6.11.0
    [04:51:42] Total duration: 52 s
    --> Build finished -> Hit F5
    --> Workbench loads, can see the full empty page
      Request: '/temp/manifests.js'
    --> Code stops at hamburgerCallback exception -> Hit F5
    --> Code stops at InvalidOperation Exception  -> Hit F5
    --> Can add Webpart to workbench page

And then with every reload:

    [04:46:49] Starting subtask 'reload'...
    [04:46:49] Finished subtask 'reload' after 1.16 ms
      Request: '/temp/manifests.js'
    --> Code stops at Exception hamburgerCallback -> Hit F5
      Request: '/lib/webparts/iLogger/loc/en-us.js'
    --> Code stops at Exception InvalidOperation -> Ht F5

**Comment by weinand** [comment]
What debugger extension are you using? If not the built-in **node debug**, please file this issue against the extension you are using. You can move the issue with this tool: https://github-issue-mover.appspot.com.

**Comment by DennisKuhn** [comment]
I am using the "Debugger for Chrome" extension.

**Comment by DennisKuhn** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#481
