### ISSUE TITLE
Hints and variables highlight became totally broken

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#33151]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-92-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
sass-lint|gle|0.0.4
sass-indented|rob|1.4.1
vscode-multiclip|sle|0.1.2

(22 theme extensions excluded)

---

Unfortunately, can't specially reproduce this bug, but it often happens, when VS Code stay opened for 5-6 hours and more.

Regarding to this bug, hints and highlight of same variables are becoming totally broken, like on screenshot:

![default](https://user-images.githubusercontent.com/26549754/29714405-c1151fa0-89ab-11e7-95d0-fbb3a63be514.png)

**Comment by mjbvz** [comment]
Do you remember if this happens after switching branches or similar types of file system operations?

If this happens again, can you please first try:

1. Set `"typescript.tsserver.trace": "verbose"` in your user settings
1. Reproduce the problem in the editor
1. Open the output panel and go to the `typescript` section of the output panel 

Check that printed output for the last operation you performed and see if there are any errors there

**Comment by antony-chopin** [comment]
@mjbvz ok, thank you, i'll try to reproduce this bug with your instructions.

Anyway, the only system operation i always do in vscode is creating/renaming files/folders. And it definetly doesn't happen after switching branches.

**Comment by antony-chopin** [comment]
@mjbvz well, finally it happened again. The last error in TS output, after which it happened:

```
[Trace  - 19:18:47] Sending request: completions (13257). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/levitator/projects/mp/mp-frontend-clear/src/components/SRPTest.jsx",
    "line": 36,
    "offset": 59
}
[Trace  - 19:18:47] Response received: completions (13257). Request took 10 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at tryReuseStructureFromOldProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57353:22)
    at Object.createProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57166:34)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76169:33)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76235:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79213:53)
    at ConfiguredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79171:39)
    at ConfiguredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:78911:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82250:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:81364:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82698:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82689:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82698:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82718:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83804:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 19:18:47] 'completions' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at tryReuseStructureFromOldProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57353:22)
    at Object.createProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:57166:34)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76169:33)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76235:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79213:53)
    at ConfiguredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79171:39)
    at ConfiguredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:78911:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82250:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:81364:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82698:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82689:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82698:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82718:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83804:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Trace  - 19:18:47] Sending request: change (13258). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/home/levitator/projects/mp/mp-frontend-clear/src/components/SRPTest.jsx",
    "line": 36,
    "offset": 59,
    "endLine": 36,
    "endOffset": 59,
    "insertString": "r"
}
```

**Comment by mjbvz** [comment]
Please try the latest VS Code insiders builds. I believe this bug (https://github.com/Microsoft/TypeScript/issues/16591) was fixed by Typescript in the most recent release
