### ISSUE TITLE
EH Debugging: Restart produces in DA error 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33343]
testing #33305 on Windows:

- debug hello world exception
- press "F5" and wait until EH appears
- press "Restart"

Observe this error on the debug console:
![2017-08-29_11-00-40](https://user-images.githubusercontent.com/1898161/29813229-cddcdf24-8ca9-11e7-9b9d-d4d83c00ad64.png)

```
******** Unhandled error in debug adapter: Error: not opened
    at LoggingSocket.send (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\ws\lib\WebSocket.js:219:16)
    at LoggingSocket.send (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeConnection.js:43:20)
    at Client._sendQueuedRequests (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:82:30)
    at LoggingSocket.Client.socket.on (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:25:18)
    at emitNone (events.js:86:13)
    at LoggingSocket.emit (events.js:188:7)
    at LoggingSocket.establishConnection (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\ws\lib\WebSocket.js:887:8)
    at ClientRequest.upgrade (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\ws\lib\WebSocket.js:778:25)
    at Object.onceWrapper (events.js:293:19)
    at emitThree (events.js:116:13)
```

**Comment by roblourens** [comment]
Seems ok now
