### ISSUE TITLE
WindowsShellHelper exception when exiting powershell via "exit" command

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33536]
devtools opens and exception appears:

```
index.js:44 TypeError: Cannot read property 'name' of undefined
    at WindowsShellHelper.traverseTree (file:///C:/Users/daimms.REDMOND/Documents/dev/vscode/out/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.js:43:47)
    at file:///C:/Users/daimms.REDMOND/Documents/dev/vscode/out/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.js:77:35
    at native.getProcessList (C:\Users\daimms.REDMOND\Documents\dev\vscode\node_modules\windows-process-tree\lib\index.js:26:5)
```

**Comment by isidorn** [comment]
Verified by typing "exit" in the powershell integreted terminal and no exception in devtools
