### ISSUE TITLE
Json: TextDocument/documentColor failed with message: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33627]
- VSCode Version: Code - Insiders 1.16.0-insider (8b942faafb2d1bee6fd6a346853548d528c7eb5a, 2017-08-31T07:18:42.889Z)
- OS Version: Darwin x64 16.7.0

---

Sorry, not sure of exact repo steps here. I've seen this when editing `.code-workspace` files mostly I believe:

```
workbench.main.js:sourcemap:29 Request textDocument/documentColor failed with message: Cannot read property 'type' of undefined: Error: Request textDocument/documentColor failed with message: Cannot read property 'type' of undefined
	at new ResponseError (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/main.js:421:48)
	at processMessageQueue (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/main.js:249:17)
	at Immediate.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/main.js:233:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
```

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@mjbvz Can you see if there is something in the 'JSON Language Server' output view? You might have to set `"json.trace.server": "messages"` to enable the logging.

**Comment by EbXpJ6bp** [comment]
So do I. (1.15.1, 41abd21afdf7424c89319ee7cb0445cc6f376959)
```
enable
[Error - 22:18:37] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'type' of undefined
  Code: -32603 
[Trace - 22:20:06] Sending notification '$/setTraceNotification'.
[Trace - 22:20:06] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 22:20:07] Received request 'vscode/content - (4)'.
[Trace - 22:20:07] Received request 'vscode/content - (5)'.
[Trace - 22:20:07] Sending response 'vscode/content - (5)'. Processing request took 0ms
[Trace - 22:20:07] Sending response 'vscode/content - (4)'. Processing request took 12ms
[Trace - 22:20:07] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:07] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:07] Received request 'vscode/content - (6)'.
[Trace - 22:20:07] Sending response 'vscode/content - (6)'. Processing request took 0ms
[Trace - 22:20:07] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:07] Sending notification 'workspace/didChangeWatchedFiles'.
[Trace - 22:20:07] Sending request 'json/colorSymbols - (10)'.
[Trace - 22:20:07] Sending request 'json/colorSymbols - (11)'.
[Trace - 22:20:07] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:07] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:07] Received response 'json/colorSymbols - (10)' in 403ms.
[Trace - 22:20:07] Received response 'json/colorSymbols - (11)' in 26ms.
[Trace - 22:20:10] Sending request 'json/colorSymbols - (12)'.
[Trace - 22:20:10] Received response 'json/colorSymbols - (12)' in 12ms. Request failed: Request json/colorSymbols failed with message: Cannot read property 'type' of undefined (-32603).
[Trace - 22:20:11] Sending request 'json/colorSymbols - (13)'.
[Trace - 22:20:11] Sending request 'json/colorSymbols - (14)'.
[Trace - 22:20:11] Received response 'json/colorSymbols - (13)' in 1ms.
[Trace - 22:20:11] Received response 'json/colorSymbols - (14)' in 0ms. Request failed: Request json/colorSymbols failed with message: Cannot read property 'type' of undefined (-32603).
[Trace - 22:20:11] Sending notification 'textDocument/didClose'.
[Trace - 22:20:11] Sending request 'json/colorSymbols - (15)'.
[Trace - 22:20:12] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:12] Received response 'json/colorSymbols - (15)' in 9ms.
[Trace - 22:20:12] Sending request 'json/colorSymbols - (16)'.
[Trace - 22:20:12] Sending request 'json/colorSymbols - (17)'.
[Trace - 22:20:12] Received response 'json/colorSymbols - (16)' in 0ms.
[Trace - 22:20:12] Received response 'json/colorSymbols - (17)' in 1ms.
[Trace - 22:20:13] Sending notification 'textDocument/didClose'.
[Trace - 22:20:13] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:15] Sending notification 'textDocument/didOpen'.
[Trace - 22:20:15] Sending request 'json/colorSymbols - (18)'.
[Trace - 22:20:15] Received response 'json/colorSymbols - (18)' in 13ms. Request failed: Request json/colorSymbols failed with message: Cannot read property 'type' of undefined (-32603).
[Trace - 22:20:16] Received notification 'textDocument/publishDiagnostics'.
[Trace - 22:20:16] Sending request 'textDocument/hover - (19)'.
[Trace - 22:20:16] Received response 'textDocument/hover - (19)' in 1ms.
[Trace - 22:20:16] Sending request 'json/colorSymbols - (20)'.
[Trace - 22:20:16] Received response 'json/colorSymbols - (20)' in 0ms. Request failed: Request json/colorSymbols failed with message: Cannot read property 'type' of undefined (-32603).
```

**Comment by aeschli** [comment]
Fixed through https://github.com/Microsoft/vscode-json-languageservice/commit/63ecfea6eb77e9c5541420eb45d0aaf25e7fe140
