### ISSUE TITLE
Cannot read property 'folderQueries' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33637]
I just hit this in insiders selfhost. I was searching in a root folder that does not exist on disk (not sure if that has any impact):

```
shell.js:228 Cannot read property 'folderQueries' of undefined: TypeError: Cannot read property 'folderQueries' of undefined
    at SearchViewlet.validateQuery (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/browser/searchViewlet.js:790:44)
    at SearchViewlet.onQueryChanged (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/browser/searchViewlet.js:780:18)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/browser/searchViewlet.js:196:99
    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
    at SearchWidget.submitSearch (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/browser/searchWidget.js:301:38)
    at SearchWidget.onSearchInputKeyUp (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/browser/searchWidget.js:280:26)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/browser/searchWidget.js:186:78
    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
```

**Comment by roblourens** [comment]
> I was searching in a root folder that does not exist on disk

What do you mean, like with `./foo` where there is no `foo`? That should give a sane error message

**Comment by bpasero** [comment]
Yeah I think I have seen that error message once.

**Comment by roblourens** [comment]
Dumb mistake, I don't think it's breaking anything though.
