### ISSUE TITLE
vscode build from source. Cannot start tests after clone repo

### ISSUE THREAD

**Issue by volosovich** [Microsoft/vscode#33707]
- VSCode Version:
Version 1.15.1
- OS Version:
ubuntu 16.04

Steps to Reproduce:

1. install Linux dependencies
2. clone repo
3. install all using ./scripts/npm.sh install --arch=x64
4. run tests ./scripts/test.sh --debug (and without debug, it's doesn't matter)
5. after downloading electron, starting devTools with error:

```
Uncaught Error: Cannot find module '/home/user/Documents/vscode-dev/vscode/out/vs/loader'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/user/Documents/vscode-dev/vscode/.build/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at initLoader (/home/user/Documents/vscode-dev/vscode/test/electron/renderer.js:25:11)
    at EventEmitter.ipcRenderer.on (/home/user/Documents/vscode-dev/vscode/test/electron/renderer.js:263:2)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
```

folders and file vscode/out/vs/loader doesn't exist.
try to find info for this error, but fale. Try to reinstall all, reclone all, used gulp clean - it did't help me.
What I'm doing wrong?

**Comment by volosovich** [comment]
need to build before run `npm run compile`
https://stackoverflow.com/questions/46026227/vscode-build-from-source-cannot-start-tests-after-clone-repo
