### ISSUE TITLE
[extension developping] Setting "vscode": "^0.10.7" fails on Travis

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#3372]
Hi,

when I set `"vscode": "0.10.x"` in `engine` part of a `package.json`, everything fails.

Mac OS says:

node ./node_modules/vscode/bin/install
Detected VS Code engine version: ^0.10.7
Error installing vscode.d.ts: TypeError: Object #<Object> has no method 'map'
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! jsthis@0.0.1 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsthis@0.0.1 postinstall script.
npm ERR! This is most likely a problem with the jsthis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/vscode/bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls jsthis
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!5m     /Users/travis/build/obrejla/vscode-jsthis/npm-debug.log

Linux process the installation, but my code then fails on:

TypeError: alsoThisVars.slice is not a function
      at shouldComplete (src/ThisCompletionItemProvider.js:49:33)
      at Object.module.exports.provideCompletionItems (src/ThisCompletionItemProvider.js:139:13)
      at test/thiscompletionitemprovider.test.js:89:62
      at Object.p [as _notify] (.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/vs/workbench/node/vs/base/common/winjs.base.raw.js:1440:1)
      at Object.__dirname.undefined.L.enter (.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/vs/workbench/node/vs/base/common/winjs.base.raw.js:1127:1)
      at [object Object].__dirname.undefined.t.Class.define._run (.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/vs/workbench/node/vs/base/common/winjs.base.raw.js:1343:1)
      at [object Object].__dirname.undefined.t.Class.define._completed (.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/vs/workbench/node/vs/base/common/winjs.base.raw.js:1311:1)
      at Object.p.handle (.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/vs/workbench/node/file:/vso/work/3/s/src/vs/platform/plugins/common/ipcRemoteCom.ts:86:11)
      at process.<anonymous> (.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/vs/workbench/node/file:/vso/work/3/s/src/vs/workbench/node/pluginHostProcess.ts:42:15)

Where `alsoThisVars` is an array returned by `vscode.workspace.getConfiguration('jsthis.thisVarNames')`.

Everything passes locally (Mac) and when I set engine to `0.10.x`, then it passes also on [Travis](https://travis-ci.org/obrejla/vscode-jsthis).

Thanks`

**Comment by obrejla** [comment]
Update: 

when I changed back an `engine` to `0.10.x`, it [passed](https://travis-ci.org/obrejla/vscode-jsthis/jobs/111332293) in Linux Travis, but [failed](https://travis-ci.org/obrejla/vscode-jsthis/jobs/111332292) on Mac Travis.

Thanks.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode-extension-vscode/issues/12
