### ISSUE TITLE
Task system fails to execte composite task

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33773]
Steps to reproduce:

- define a composite task
- execute it.

It fails with the following exception:
```
Cannot read property 'presentation' of undefined: TypeError: Cannot read property 'presentation' of undefined
    at TaskEntry.doRun (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/browser/quickOpen.js:52:29)
    at TaskEntry.run (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/browser/taskQuickOpen.js:38:25)
    at QuickOpenModel.run (file:///P:/mseng/VSCode/vscode/out/vs/base/parts/quickopen/browser/quickOpenModel.js:560:26)
    at QuickOpenWidget.elementSelected (file:///P:/mseng/VSCode/vscode/out/vs/base/parts/quickopen/browser/quickOpenWidget.js:376:42)
    at file:///P:/mseng/VSCode/vscode/out/vs/base/parts/quickopen/browser/quickOpenWidget.js:160:35
    at safeInvoke1Arg (file:///P:/mseng/VSCode/vscode/out/vs/base/common/eventEmitter.js:246:20)
    at Tree.EventEmitter._emitToSpecificTypeListeners (file:///P:/mseng/VSCode/vscode/out/vs/base/common/eventEmitter.js:130:21)
    at Tree.EventEmitter._emitEvents (file:///P:/mseng/VSCode/vscode/out/vs/base/common/eventEmitter.js:146:22)
    at file:///P:/mseng/VSCode/vscode/out/vs/base/common/eventEmitter.js:99:27
    at safeInvoke1Arg (file:///P:/mseng/VSCode/vscode/out/vs/base/common/eventEmitter.js:246:20)
WorkbenchShell.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
ErrorHandler.onUnexpectedError @ errors.ts:119
onUnexpectedError @ errors.ts:138
safeInvoke1Arg @ eventEmitter.ts:297
EventEmitter._emitToSpecificTypeListeners @ eventEmitter.ts:162
EventEmitter._emitEvents @ eventEmitter.ts:181
(anonymous) @ eventEmitter.ts:129
safeInvoke1Arg @ eventEmitter.ts:295
EventEmitter._emitToBulkListeners @ eventEmitter.ts:170
EventEmitter._emitEvents @ eventEmitter.ts:176
EventEmitter.emit @ eventEmitter.ts:196
TreeModel.setSelection @ treeModel.ts:1030
Tree.setSelection @ treeImpl.ts:267
DefaultController.onLeftClick @ treeDefaults.ts:168
DefaultController.onClick @ treeDefaults.ts:151
TreeView.onClick @ treeView.ts:1191
(anonymous) @ treeView.ts:501
messageService.ts:125 Cannot read property 'id' of undefined
WorkbenchMessageService.doShow @ messageService.ts:125
WorkbenchMessageService.show @ messageService.ts:104
TaskService.handleError @ task.contribution.ts:1691
(anonymous) @ task.contribution.ts:952
notifyError @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
argDone @ winjs.base.raw.js:1813
Promise.then.errors.(anonymous function) @ winjs.base.raw.js:1838
notifySuccess @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
(anonymous) @ terminalTaskSystem.ts:391
emitTwo @ events.js:111
emit @ events.js:194
ChildProcess._handle.onexit @ internal/child_process.js:215
shell.ts:419 Cannot read property 'options' of undefined: TypeError: Cannot read property 'options' of undefined
    at TerminalTaskSystem.createTerminal (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:389:59)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:308:32
    at new Promise_ctor (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1641:17)
    at TerminalTaskSystem.executeCommand (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:307:27)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:219:34
    at Object.notifySuccess [as _notify] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at argDone (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1813:37)
WorkbenchShell.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
ErrorHandler.onUnexpectedError @ errors.ts:119
onUnexpectedError @ errors.ts:138
(anonymous) @ errors.ts:47
(anonymous) @ errors.ts:44
errors.ts:51 WARNING: Promise with no error callback:73
errors.ts:52 Object {exception: TypeError: Cannot read property 'options' of undefined
    at TerminalTaskSystem.createTerminal (fil…, error: null, promise: Promise_ctor, handler: undefined, id: 73…}
errors.ts:54 TypeError: Cannot read property 'options' of undefined
    at TerminalTaskSystem.createTerminal (terminalTaskSystem.ts:432)
    at terminalTaskSystem.ts:354
    at new Promise_ctor (winjs.base.raw.js:1641)
    at TerminalTaskSystem.executeCommand (terminalTaskSystem.ts:353)
    at terminalTaskSystem.ts:269
    at Object.notifySuccess [as _notify] (winjs.base.raw.js:1170)
    at Object.enter (winjs.base.raw.js:852)
    at Promise_ctor._run (winjs.base.raw.js:1068)
    at Promise_ctor._completed (winjs.base.raw.js:1036)
    at argDone (winjs.base.raw.js:1813)
shell.ts:419 Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at TerminalService.setActiveInstance (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/common/terminalService.js:137:80)
    at TerminalTaskSystem.executeCommand (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:350:34)
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:219:34
    at Object.notifySuccess [as _notify] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at argDone (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1813:37)
    at Promise.then.errors.(anonymous function) (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1838:78)
    at Object.notifySuccess [as _notify] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
WorkbenchShell.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
ErrorHandler.onUnexpectedError @ errors.ts:119
onUnexpectedError @ errors.ts:138
(anonymous) @ errors.ts:49
(anonymous) @ errors.ts:44
errors.ts:51 WARNING: Promise with no error callback:75
errors.ts:52 Object {exception: null, error: TypeError: Cannot read property 'id' of undefined
    at TerminalService.setActiveInstance (file:///…, promise: ErrorPromise_ctor, handler: undefined, id: 75…}
```

**Comment by dbaeumer** [comment]
This used to work but might got already broken for 1.5.

**Comment by dbaeumer** [comment]
To verifiy:

- create a workspace
- inside create a folder server and client both having a file in it.
- add the following tasks.json

```ts
{
	"version": "2.0.0",
	"tasks": [
		{
			"taskName": "dir",
			"dependsOn": [
				"client dir",
				"server dir"
			],
			"problemMatcher": []
		},
		{
			"taskName": "client dir",
			"type": "shell",
			"command": "dir",
			"options": {
				"cwd": "${workspaceRoot}\\client"
			},
			"presentation": {
				"panel": "dedicated"
			},
			"problemMatcher": []
		},
		{
			"taskName": "server dir",
			"type": "shell",
			"command": "dir",
			"options": {
				"cwd": "${workspaceRoot}\\server"
			},
			"presentation": {
				"panel": "dedicated"
			},
			"problemMatcher": []
		}
	]
}
```
- execute the dir task

Ensure that the client and server dir command is executed (you have two Task in the terminal drop down) and that no exceptions appear in the developer console.

![capture](https://user-images.githubusercontent.com/1931590/30018545-9dd1d20e-915d-11e7-957e-ef2bb6f6278e.png)

**Comment by dbaeumer** [comment]
Pushed to release/1.16 branch
