### ISSUE TITLE
Provide "Go Last" navigation command.

### ISSUE THREAD

**Issue by brandonbloom** [Microsoft/vscode#33902]
@bpasero requested over in PR #33715 that I create this issue.

My goal is to implement a pair of related Vim "jump to mark" commands: https://github.com/VSCodeVim/Vim/pull/1993

As far as I can tell, VSCode does not currently offer "marks" ("bookmarks"), but does have back/forward navigation history. In Vim, when you "jump" (navigate) anywhere, the specially named `'` and <code>\`</code> "last jump" marks are set each time. The first time you press `''` or <code>``</code>, the experience is indistinguishable from "Navigate Back". However, that navigation is itself a jump, setting the special last jump marks. That means, if you press the key sequences again, you jump back to where you just came from. So pressing `''` over and over will flip back and forth between two places. The ' register marks a line and the <code>\`</code> register marks a full position. The former can be implemented in terms of the latter.

While Vim implements this behavior in terms of marks, it's equally valid to implement it in terms of jumps, since the navigation history inherently includes cursor position information (ie anonymous marks). All that's necessary is a single variable storing one layer of additional navigation history: The last place you came from.

In practice, this feature works out something like alternating between "Go Back" and "Go Forward", letting you flip between to places quickly to compare them. This is frequently useful when comparing two places in one file, or when comparing places between files. Side-by-side comparisons are useful, but require more window manipulation to set up and tear down. "Go Last" enables quick overlay comparisons like flipping pages of a book back and forth.

**Comment by bpasero** [comment]
@brandonbloom could you verify this works as expected? Then we can close this as verified.

**Comment by brandonbloom** [comment]
I don't see a "Go Last" command in Version 1.16.1 - has this change been released? I'm not familiar with VS Code's release schedule/process.

**Comment by bpasero** [comment]
@brandonbloom It is included into our nightly insider builds. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by brandonbloom** [comment]
Thanks.

Yup, this is working great in an insiders build for me!

**Comment by bpasero** [comment]
@brandonbloom thanks for verifying

**Comment by brandonbloom** [comment]
This worked just fine in the insider build I tried, but something else has broken since then. When I try to use this command, I occasionally get an error: `"Cannot read property 'selection' of undefined"`. After this error occurs, the normal "Go Back" and "Go Forward" commands also become broken with the same error.

**Comment by bpasero** [comment]
@brandonbloom any ideas for how to reproduce consistently? Can you share the full stack trace here when you see it again?

**Comment by brandonbloom** [comment]
How would I go about getting a full stack trace? Running VS Code under it's own debugger, I can't get pause on exceptions or rejections to actually pause in this context. Instead, I just get the error on the little bubble on the top of the window.

<img width="376" alt="screen shot 2017-10-16 at 3 18 00 pm" src="https://user-images.githubusercontent.com/119164/31637783-379d4f74-b285-11e7-86c9-3211422d1538.png">

**Comment by brandonbloom** [comment]
Weird - I seem to have "fixed" it by closing every window in my editor session and re-openning the folder. There must have been some cached state that was invalid. It seems to work now... I'm no longer able to reproduce the failure and this is working fine again.

**Comment by brandonbloom** [comment]
Whoops, spoke too soon. Apologies for the noise. It failed again after about 5 minutes of work. I think I can reproduce somewhat reliably, so I'll try to get you a stack trace if you have advice on how to go about that.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by brandonbloom** [comment]
OK, thanks. Looks like this commit that landed the day after mine is the issue: 273dbeef4a9ac3e0713872b2488ebad442a06b7c

In particular, this line: `if (entry.selection && !acrossEditors) {` doesn't guard the fact that entry may be undefined because the index may be out of range. I'm not sure what paths lead this code to be triggered, but lots of other code in the file guards against `index < 0`.

**Comment by bpasero** [comment]
@brandonbloom how is that possible though, when I look into the version of that file from 1.15 where your change was not included we already had a case where we accessed the entry without checking for null (see https://github.com/Microsoft/vscode/blob/release/1.15/src/vs/workbench/services/history/browser/history.ts#L324). So it seems that the "Go Last" command can result in the index not being correct, can you check how that can happen so that we can fix the command?

**Comment by topecongiro** [comment]
Sorry for chipping in, I had a same issue. I am using `1.17.2 b813d12980308015bcd2b3a2f6efa5c810c33ba5`.
the following is what I got from `code --verbose`:

```
[13364:1019/125849.663531:INFO:CONSOLE(28)] "%c[Extension Host] %cinvalid value for set cursor position. This is probably bad? %c(at VimState.set allCursors [as allCursors] (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:151:25))", source: file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (28)
[13364:1019/125849.665850:INFO:CONSOLE(28)] "%c[Extension Host] %cerror.stack %c(at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:644:25))", source: file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (28)
[13364:1019/125849.665891:INFO:CONSOLE(28)] "%c[Extension Host] %cTypeError: Cannot read property 'document' of undefined
        at Function.getLineCount (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/textEditor.js:119:46)
        at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:865:58)
        at Generator.next (<anonymous>)
        at fulfilled (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:4:58)
        at <anonymous> %c(at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:645:25))", source: file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (28)
[13364:1019/125849.665918:INFO:CONSOLE(28)] "%c[Extension Host] %cTypeError: Cannot read property 'document' of undefined
        at Function.getLineCount (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/textEditor.js:119:46)
        at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:865:58)
        at Generator.next (<anonymous>)
        at fulfilled (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:4:58)
        at <anonymous> %c(at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:646:25))", source: file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (28)
[13364:1019/125850.745410:INFO:CONSOLE(28)] "Cannot read property 'selection' of undefined: TypeError: Cannot read property 'selection' of undefined
    at t.navigate (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2501577)
    at t.last (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2501036)
    at t.run (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2894265)
    at file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2615209
    at n.Class.derive._oncancel.then (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:60387)
    at p (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2615166)
    at file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2614886
    at t.invokeFunction (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:1089386)
    at t._tryExecuteCommand (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:1080627)
    at file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:1080327", source: file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (28)
```

and from **Console**:

```
/home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] invalid value for set cursor position. This is probably bad? (at VimState.set allCursors [as allCursors] (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:151:25))
console.ts:123 [Extension Host] error.stack (at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:644:25))
console.ts:123 [Extension Host] TypeError: Cannot read property 'document' of undefined
	at Function.getLineCount (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/textEditor.js:119:46)
	at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:865:58)
	at Generator.next (<anonymous>)
	at fulfilled (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:4:58)
	at <anonymous> (at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:645:25))
console.ts:123 [Extension Host] TypeError: Cannot read property 'document' of undefined
	at Function.getLineCount (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/textEditor.js:119:46)
	at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:865:58)
	at Generator.next (<anonymous>)
	at fulfilled (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:4:58)
	at <anonymous> (at ModeHandler.<anonymous> (/home/uchida/.vscode/extensions/vscodevim.vim-0.10.1/out/src/mode/modeHandler.js:646:25))
messageService.ts:125 Cannot read property 'selection' of undefined: TypeError: Cannot read property 'selection' of undefined
    at t.navigate (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2501577)
    at t.last (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2501036)
    at t.run (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2894265)
    at file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2615209
    at n.Class.derive._oncancel.then (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:60387)
    at p (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2615166)
    at file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:2614886
    at t.invokeFunction (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:1089386)
    at t._tryExecuteCommand (file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:1080627)
    at file:///home/uchida/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:28:1080327
e.doShow @ messageService.ts:125
```

**Comment by bpasero** [comment]
Filed https://github.com/Microsoft/vscode/issues/36544 to track this for October.

**Comment by brandonbloom** [comment]
Hey @bpasero, sorry, you're right: The unguarded undefined entry isn't a new problem. I jumped to conclusions because I was using this command in my private build without issues until the new release came out. I'll try to find some time to look at this more closely soon.
