### ISSUE TITLE
tsserver: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#34123]
- VSCode Version: 2c385b98066eebb8e39dfd98b1fcb8cc254196b6
- OS Version: windows 10 x64

Steps to Reproduce:

1. Edit TSX file
2. Try to define a function parameter as _something

```ts
          <Stager
            ref={(_stager)=> this.stager=_stager } // << here
            onChange={this.setTitle}
            >
```

```
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (C:\nodejs\node_modules\typescript\lib\tsserver.js:8627:18)
    at Object.getSuggestionForNonexistentSymbol (C:\nodejs\node_modules\typescript\lib\tsserver.js:19848:95)
    at Object.getActionsForCorrectSpelling [as getCodeActions] (C:\nodejs\node_modules\typescript\lib\tsserver.js:73600:38)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:73316:33
    at Object.forEach (C:\nodejs\node_modules\typescript\lib\tsserver.js:1299:30)
    at Object.getFixes (C:\nodejs\node_modules\typescript\lib\tsserver.js:73315:16)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:77197:35
    at Object.flatMap (C:\nodejs\node_modules\typescript\lib\tsserver.js:1531:25)
    at Object.getCodeFixesAtPosition (C:\nodejs\node_modules\typescript\lib\tsserver.js:77195:23)
    at IOSession.Session.getCodeFixes (C:\nodejs\node_modules\typescript\lib\tsserver.js:83234:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\nodejs\node_modules\typescript\lib\tsserver.js:82152:61)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:83378:88
    at IOSession.Session.executeWithRequestId (C:\nodejs\node_modules\typescript\lib\tsserver.js:83369:28)
    at IOSession.Session.executeCommand (C:\nodejs\node_modules\typescript\lib\tsserver.js:83378:33)
    at IOSession.Session.onMessage (C:\nodejs\node_modules\typescript\lib\tsserver.js:83398:35)
    at Interface.<anonymous> (C:\nodejs\node_modules\typescript\lib\tsserver.js:84529:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18390
