### ISSUE TITLE
The window is no longer responding

### ISSUE THREAD

**Issue by supercocoa** [Microsoft/vscode#34348]
- VSCode Version:1.16.0
- OS Version: mac os 10.12.6

Steps to Reproduce:

1. open vscode and switch to other app's window.
2. it shows "The window is no longer responding" when return to vscode.

Reproduces without extensions: Yes

``` shell
code --verbose --disable-extensions .                                                                                                                                             
[main 14:48:44] Starting VS Code in verbose mode
[main 14:48:44] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 14:48:44] args: { _: [ '/Users/scott/workspace/react/react-native-0.43.5' ],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[main 14:48:45] IPC#vscode-machineId
[main 14:48:46] IPC#vscode-workbenchLoaded
[main 14:53:56] App#activate
[main 14:54:02] [VS Code]: detected unresponsive
[main 14:54:11] IPC#vscode-machineId
[28699:0914/145411.915010:INFO:CONSOLE(5)] "[uncaught exception]: Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[28699:0914/145411.915113:INFO:CONSOLE(5)] "Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[28699:0914/145411.915159:INFO:CONSOLE(28)] "Uncaught Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (28)
[28699:0914/145411.915455:INFO:CONSOLE(5)] "[uncaught exception]: Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[28699:0914/145411.915520:INFO:CONSOLE(5)] "Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[28699:0914/145411.915573:INFO:CONSOLE(28)] "Uncaught Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (28)
[28699:0914/145412.461055:INFO:CONSOLE(29)] "connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock: Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (29)
[main 14:54:12] IPC#vscode-workbenchLoaded
[28699:0914/145452.577046:INFO:CONSOLE(29)] "connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock: Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.0-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (29)
```

**Comment by alexandrudima** [comment]
@supercocoa Are there any more steps to reproduce the hang? I am leaving VS Code in the background quite often and it doesn't hang/crash for me. Is this something that happens after doing a certain set of actions, is this something that happens when opening a specific folder ?

**Comment by supercocoa** [comment]
@alexandrudima  Open `android studio` or `webstorm` can make this happen sometimes.

**Comment by supercocoa** [comment]
@alexandrudima   And it never hangs when run by sudo...

**Comment by supercocoa** [comment]
@joaomoreno  What can i do next?

**Comment by joaomoreno** [comment]
I strongly advise against running Code under sudo. There is no reason whatsoever to do that.

Then, you can use sudo to delete `/Users/scott/Library/Application Support/Code/1.16.0-shared.sock`.

Then, try launching Code normally again.

**Comment by mdvorscak** [comment]
I have the same issue on windows 10, running VS Code 1.16.1. This happens any time I try to open a particular file (unfortunately, I cannot provide the file since it is a closed source project). The other files can be opened/edited normally. I'm not sure how to get the crash logs; if you can tell me how, I can retrieve them and provide them here.

This did not happen on the previous version of VS Code.

**Comment by mdvorscak** [comment]
My issue, which may have been unrelated was due to a parsing error in my jsdoc:

```js
//The offending line:
* @param {string | object} [opts.data={@link WebTools.serializeForm}
//closing the square bracket fixed the issue
* @param {string | object} [opts.data={@link WebTools.serializeForm}]
```

**Comment by supercocoa** [comment]
@joaomoreno  "delete /Users/scott/Library/Application Support/Code/1.16.0-shared.sock" is not work, Code still hang next time.

**Comment by joaomoreno** [comment]
@supercocoa Can you check the permissions of all files under `/Users/scott/Library/Application Support/Code`? Does your user have permissions to write to them?

**Comment by supercocoa** [comment]
@joaomoreno

**Comment by supercocoa** [comment]
@joaomoreno  I just open Code like this, then open webstorm + androidstudio.
``` shell
chmod -R 777 "/Users/scott/Library/Application Support/Code"                                                                                                                                                        ✓  11636  18:42:5
code --verbose --disable-extensions                                                                                                                                                                                 ✓  11637  18:43:0
[main 18:43:36] Starting VS Code in verbose mode
[main 18:43:36] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 18:43:36] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[main 18:43:37] IPC#vscode-machineId
[main 18:43:37] IPC#vscode-workbenchLoaded
[main 18:43:38] IPC#vscode:broadcast vscode:changeColorTheme {"id":"vs-dark vscode-theme-defaults-themes-dark_plus-json","background":"#1e1e1e"}
[main 18:44:39] [VS Code]: detected unresponsive
[main 18:44:46] IPC#vscode-machineId
[26227:0920/184447.186329:INFO:CONSOLE(5)] "[uncaught exception]: Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.1-shared.sock", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[26227:0920/184447.186454:INFO:CONSOLE(5)] "Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.1-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[26227:0920/184447.186504:INFO:CONSOLE(28)] "Uncaught Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.1-shared.sock", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (28)
[26227:0920/184447.193005:INFO:CONSOLE(5)] "[uncaught exception]: Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.1-shared.sock", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[26227:0920/184447.193143:INFO:CONSOLE(5)] "Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.1-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[26227:0920/184447.193197:INFO:CONSOLE(28)] "Uncaught Error: connect ECONNREFUSED /Users/scott/Library/Application Support/Code/1.16.1-shared.sock", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (28)
[main 18:44:48] IPC#vscode-workbenchLoaded
```

**Comment by joaomoreno** [comment]
@supercocoa Can you check the permissions of all files and folders under /Users/scott/Library/Application Support/Code? Does your user have permissions to write to them?

**Comment by supercocoa** [comment]
@joaomoreno    yes, I chmod all files  to 777 first.

**Comment by joaomoreno** [comment]
Can you completely delete `/Users/scott/Library/Application Support/Code` and try launching Code again? And please, don't use sudo.

**Comment by supercocoa** [comment]
@joaomoreno  I already try this way, but not work...

**Comment by joaomoreno** [comment]
Does it work if you run `code --user-data-dir ~/Desktop/new-data-dir`?

**Comment by supercocoa** [comment]
not work as well..
``` shell
code --verbose --disable-extensions --user-data-dir tmp_dir                                                                                                                                                         ✓  11789  19:28:4
[main 19:30:29] Starting VS Code in verbose mode
[main 19:30:29] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 19:30:29] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'user-data-dir': 'tmp_dir' }
[main 19:30:29] Unable to read folders in /Users/scott/tmp_dir/Workspaces (Error: ENOENT: no such file or directory, scandir '/Users/scott/tmp_dir/Workspaces').
[main 19:30:30] IPC#vscode-machineId
[main 19:30:31] IPC#vscode-workbenchLoaded
[main 19:31:09] [VS Code]: detected unresponsive
[main 19:31:23] App#activate
[main 19:31:24] IPC#vscode-machineId
[main 19:31:24] IPC#vscode-workbenchLoaded
[33942:0921/193124.946445:INFO:CONSOLE(29)] "connect ECONNREFUSED /Users/scott/tmp_dir/1.16.1-shared.sock: Error: connect ECONNREFUSED /Users/scott/tmp_dir/1.16.1-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (29)
[33942:0921/193124.946817:INFO:CONSOLE(5)] "[uncaught exception]: Error: connect ECONNREFUSED /Users/scott/tmp_dir/1.16.1-shared.sock", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[33942:0921/193124.946886:INFO:CONSOLE(5)] "Error: connect ECONNREFUSED /Users/scott/tmp_dir/1.16.1-shared.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[33942:0921/193124.946930:INFO:CONSOLE(28)] "Uncaught Error: connect ECONNREFUSED /Users/scott/tmp_dir/1.16.1-shared.sock", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (28)
[33942:0921/193124.947178:INFO:CONSOLE(5)] "[uncaught exception]: Error: connect ECONNREFUSED /Users/scott/tmp_dir/1.16.1-shared.sock", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[33942:0921/193124.947233:INFO:CONSOLE(5)] "Error: connect ECONNREFUSED /Users/scott/tmp_dir/1.16.1-shared.sock
```

**Comment by joaomoreno** [comment]
Is there something special about your machine, file system?

**Comment by supercocoa** [comment]
I found that Code will must hang when I open android studio , so I use idea instead of it, and Code never hangs again.
