### ISSUE TITLE
Error: Cannot find module './build/Release/keymapping'

### ISSUE THREAD

**Issue by Faynman** [Microsoft/vscode#34419]
- VSCode Version: v1.17.0
- OS Version: win10_x64

Steps to Reproduce:

1.scripts/npm.bat install 

2.npm run watch

3.scripts/code.bat

PS C:\Users\Faynman\Desktop\vscode> .\scripts\code.bat
[11:39:37] Using gulpfile ~\Desktop\vscode\gulpfile.js
[11:39:37] Starting 'clean-electron'...
[11:39:37] Finished 'clean-electron' after 2.73 ms
[11:39:37] Starting 'electron'...
[11:39:39] Finished 'electron' after 2.06 s
[11:39:42] Using gulpfile ~\Desktop\vscode\gulpfile.js
[11:39:42] Starting 'clean-electron'...
[11:39:42] Finished 'clean-electron' after 177 ms
[11:39:42] Starting 'electron'...
[11:39:44] Finished 'electron' after 2.01 s

{ Error: Cannot find module './build/Release/keymapping'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\Faynman\Desktop\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at NativeBinding._init (C:\Users\Faynman\Desktop\vscode\node_modules\native-keymap\index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (C:\Users\Faynman\Desktop\vscode\node_modules\native-keymap\index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (C:\Users\Faynman\Desktop\vscode\node_modules\native-keymap\index.js:61:18)
    at KeyboardLayoutMonitor.onDidChangeKeyboardLayout (C:\Users\Faynman\Desktop\vscode\out\vs\code\electron-main\keyboard.js:27:30)
    at CodeApplication.registerListeners (C:\Users\Faynman\Desktop\vscode\out\vs\code\electron-main\app.js:148:55) code: 'MODULE_NOT_FOUND' }
[19964:0915/113945.924:INFO:CONSOLE(224)] "Loading "gc-signals" failed", source: file:///C:/Users/Faynman/Desktop/vscode/out/vs/loader.js (224)
[19964:0915/113945.925:INFO:CONSOLE(225)] "Detail: ", source: file:///C:/Users/Faynman/Desktop/vscode/out/vs/loader.js (225)
[19964:0915/113945.925:INFO:CONSOLE(227)] "Error: Cannot find module '../build/Release/gcsignals'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\Faynman\Desktop\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Faynman\Desktop\vscode\node_modules\gc-signals\src\index.js:8:18)
    at Object.<anonymous> (C:\Users\Faynman\Desktop\vscode\node_modules\gc-signals\src\index.js:67:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)", source: file:///C:/Users/Faynman/Desktop/vscode/out/vs/loader.js (227)
[19964:0915/113945.925:INFO:CONSOLE(229)] "Here are the modules that depend on it:", source: file:///C:/Users/Faynman/Desktop/vscode/out/vs/loader.js (229)
[19964:0915/113945.927:INFO:CONSOLE(230)] "vs/workbench/api/electron-browser/mainThreadHeapService", source: file:///C:/Users/Faynman/Desktop/vscode/out/vs/loader.js (230)

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Does this file exist? What if you rebuild everything by running:

1.  `git clean -xfd` to clean out all files that are not part of the git repo
2. `./scripts npm install` to install everything again
3. `npm run watch` to build again

**Comment by Faynman** [comment]
@mjbvz Thank you for your reply.

I've tried it many times and  can't solve the problem.

the error is " Cannot find module './build/Release/keymapping'" at (C:\Users\Administrator\Desktop\vscode\node_modules\native-keymap\index.js:15:22)

so, i check the "index.js" file, 
![image 1](https://user-images.githubusercontent.com/9510173/30695122-809e2c8c-9f09-11e7-9c19-22933d5a7fe6.png)

"build" is not exist in the index.js file directory. then i run the command "npm install", the build directory appear. 
![image](https://user-images.githubusercontent.com/9510173/30695458-d8c9640c-9f0a-11e7-845d-d0dfa4c7d47f.png)

![image](https://user-images.githubusercontent.com/9510173/30695534-0b413cc0-9f0b-11e7-9f61-178245a13787.png)

but the module still doesn't exist.

**Comment by joaomoreno** [comment]
What's your npm version?

**Comment by Faynman** [comment]
![image](https://user-images.githubusercontent.com/9510173/30700956-ac6f8100-9f1b-11e7-926b-487e8f19c979.png)
npm version v5.3.0

**Comment by joaomoreno** [comment]
Can you install npm 4 and retry again? `npm i -g npm@4`. We don't support 5 yet: #30134
