### ISSUE TITLE
class URI cannot represent relative file paths

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#34449]
`Uri.file(...)` always adds a '/' to the path.

```ts
suite("Uri file path tests", () => {

    test("absolute path", () => {
        const path = '/foo/bar';
        assert.equal(vscode.Uri.file(path).path, path);
     });

     test("relative path", () => {
        const path = 'foo/bar';
        assert.equal(vscode.Uri.file(path).path, path);
    });

    test("relative path with dot", () => {
        const path = './foo/bar';
        assert.equal(vscode.Uri.file(path).path, path);
    });
});
```

result in this:
```
Uri file path tests
    ✓ absolute path
    1) relative path
    2) relative path with dot
  1 passing (13ms)
  2 failing
  1) Uri file path tests relative path:
      AssertionError: '/foo/bar' == 'foo/bar'
      + expected - actual
      -/foo/bar
      +foo/bar
      
      at Context.test (/Users/weinand/MS/Projects/TestProjects/ext-hello/test/extension.test.ts:24:16)
  2) Uri file path tests relative path with dot:
      AssertionError: '/./foo/bar' == './foo/bar'
      + expected - actual
      -/./foo/bar
      +./foo/bar
      
      at Context.test (/Users/weinand/MS/Projects/TestProjects/ext-hello/test/extension.test.ts:29:16)
```

**Comment by jrieken** [comment]
"Fix" will be to disallow creating uris via `URI#file` and relative paths. We cannot guarantee identity for such paths because file-uris get formatted with double slashes: https://tools.ietf.org/html/rfc8089#section-2. 

That makes the following sequence of `toString` and `parse`: 

```ts
const uri = URI.parse('file:./relative/path'); // allowed but dangerous 💣 
assert.equal(uri.scheme, 'file');
assert.equal(uri.authority, '');
assert.equal(uri.path, './relative/path');

assert.equal(uri.toString(), 'file://./relative/path');

// this is asymetric to be spec-compliant
const uri2 = URI.parse(uri.toString());
assert.equal(uri2.authority, '.');
assert.equal(uri2.path, '/relative/path');
```

To prevent this from happening we make the `Uri#file`-factory-function more strict and it will error when a path isn't absolute

```ts
// good 👍 
URI.parse('c:\ok')
URI.parse('/usr/bin')
URI.parse('\\host\shares\ok')

// now disallowed
URI.parse('./boom')
URI.parse('boom')
URI.parse('../boom')
```

**Comment by weinand** [comment]
@jrieken you meant `URI.file(...)` instead of `URI.parse(...)` in the 6 examples form above, right?

**Comment by jrieken** [comment]
> @jrieken you meant URI.file(...) instead of URI.parse(...) in the 6 examples from above, right?

Ops, yeah. Corrected.

**Comment by weinand** [comment]
And the "allowed but dangerous" example is dangerous because it results in this:

```ts
    test("relative path", () => {
        const fileUri1 = vscode.Uri.parse(`file:foo/bar`);
        assert.equal(fileUri1.path, 'foo/bar'); // looks good: relative path seems to be supported

        const uri = fileUri1.toString();
        assert.equal(uri, 'file://foo/bar');    // looks ok, but isn't
        const fileUri2 = vscode.Uri.parse(uri);
        assert.equal(fileUri2.path, '/bar');    // oops
        assert.equal(fileUri2.authority, 'foo');    // ohh, I see...
    });
``ts

**Comment by jrieken** [comment]
Things are more tricky with other/unknown schemes. This is for instance what nodejs/url does

```js
new (require('url').URL)('foo:bar').pathname
"bar"
new (require('url').URL)('file:bar').pathname
"/bar"
new (require('url').URL)('http://foo').pathname
"/"
```

So, `file`-uris are made absolute while paths from unknown protocols aren't. We could do something similar, keep the existing behaviour in place, except for a well known protocols like `file`, `http` and the scheme of file system providers...
