### ISSUE TITLE
New terminal renderer throws from time to time

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#34493]
See the following exception from time to time in the console when running a task in the terminal. No exact steps to reproduce. 
```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at CharAtlasGenerator.generate (P:\mseng\VSCode\vscode\node_modules\xterm\lib\renderer\CharAtlas.js:115:44)
    at Object.acquireCharAtlas (P:\mseng\VSCode\vscode\node_modules\xterm\lib\renderer\CharAtlas.js:34:27)
    at BackgroundRenderLayer.BaseRenderLayer._refreshCharAtlas (P:\mseng\VSCode\vscode\node_modules\xterm\lib\renderer\BaseRenderLayer.js:28:34)
    at BackgroundRenderLayer.BaseRenderLayer.onThemeChanged (P:\mseng\VSCode\vscode\node_modules\xterm\lib\renderer\BaseRenderLayer.js:23:14)
    at P:\mseng\VSCode\vscode\node_modules\xterm\lib\renderer\Renderer.js:58:15
    at Array.forEach (native)
    at Renderer.setTheme (P:\mseng\VSCode\vscode\node_modules\xterm\lib\renderer\Renderer.js:57:28)
    at Terminal._setTheme (P:\mseng\VSCode\vscode\node_modules\xterm\lib\Terminal.js:388:36)
    at P:\mseng\VSCode\vscode\node_modules\xterm\lib\Terminal.js:379:23
```

**Comment by dbaeumer** [comment]
Always shows when doing:

- clone https://github.com/Microsoft/vscode-languageserver-node.git
- execute the task client:compile
