### ISSUE TITLE
Cannot build on Fedora

### ISSUE THREAD

**Issue by bkeys** [Microsoft/vscode#34523]
- VSCode Version: 1.16.1
- OS Version: Fedora 26

Steps to Reproduce:

1. ```wget https://github.com/Microsoft/vscode/archive/1.16.1.tar.gz```
2. ```tar xf 1.16.1.tar.gz```
2.  ```cd vscode-1.16.1```
3.  ```./scripts/npm.sh install --arch=x64```

And it will fail to build with the following output
```
npm ERR! Linux 4.12.11-300.fc26.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--arch=x64"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! keytar@4.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@4.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bkeys/Devel/vscode-1.16.1/npm-debug.log
```

The npm-debug.log file is massive so [here is the pastebin of it](https://paste.fedoraproject.org/paste/rGyrFoIQhmVWtqOi1dL~SA)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@bkeys Have you installed all the prerequisites listed at https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source ?

![image](https://user-images.githubusercontent.com/5047891/30533805-8ab51704-9c5b-11e7-9f27-4e0778038f6e.png)

**Comment by bkeys** [comment]
Yep that fixes it, and I got an RPM built and installed, but now the binary does not run. I did the following to create an RPM
1) wget https://github.com/Microsoft/vscode/archive/1.16.1.tar.gz
2) tar xf 1.16.1.tar.gz
3) cd vscode-1.16.1
4) ./scripts/npm.sh install --arch=x64
5) gulp vscode-linux-x64-min
6) gulp vscode-linux-x64-build-rpm

 I ran code-oss with the ```--disable-extensions``` flag as well and I got the same result. When I pass the ```--verbose``` flag I get this output
```
The factory method of "vs/code/electron-main/main" has thrown an exception
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at t.get (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:174289)
    at t.n.(anonymous function) [as nodeCachedDataDir] (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:8934)
    at L (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:343285)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:345541
    at t.invokeFunction (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:159994)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:345507
    at t.invokeFunction (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:159994)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:345297
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at t.get (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:174289)
    at t.n.(anonymous function) [as nodeCachedDataDir] (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:8934)
    at L (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:343285)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:345541
    at t.invokeFunction (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:159994)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:345507
    at t.invokeFunction (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:159994)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:4:345297
```
my system monitor shows the process running, but the process itself has no window or anything. It does this whether or not I specify a path to the binary.

**Comment by bkeys** [comment]
Okay so I built it again fresh, but this time I did not use the minified build and it works just fine. However I would like to have a minified built.

**Comment by bkeys** [comment]
Another note, on the unminified build which runs, the terminal never opens up either.

**Comment by joaomoreno** [comment]
Does the minified build run fine before the rpm?

**Comment by bkeys** [comment]
No I get the same error I posted above when I invoke it with the --verbose flag.
The process shows up in my system monitor, but it does not create a window or anything.

**Comment by joaomoreno** [comment]
> Okay so I built it again fresh, but this time I did not use the minified build and it works just fine. However I would like to have a minified built.

Did you do this by running `gulp vscode-linux-x64`? If not, do that and check if you still get the error there. The stack trace should be more informative in that case.

**Comment by bkeys** [comment]
Alright I did that and here is what I get when I run ```code-oss```
```
he factory method of "vs/code/electron-main/main" has thrown an exception
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at EnvironmentService.get (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:13269:59)
    at EnvironmentService.descriptor.(anonymous function) [as nodeCachedDataDir] (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:505:31)
    at createPaths (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21098:31)
    at /home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21223:78
    at InstantiationService.invokeFunction (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:12552:34)
    at /home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21223:41
    at InstantiationService.invokeFunction (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:12552:34)
    at main (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21213:37)
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at EnvironmentService.get (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:13269:59)
    at EnvironmentService.descriptor.(anonymous function) [as nodeCachedDataDir] (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:505:31)
    at createPaths (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21098:31)
    at /home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21223:78
    at InstantiationService.invokeFunction (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:12552:34)
    at /home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21223:41
    at InstantiationService.invokeFunction (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:12552:34)
    at main (/home/bkeys/Devel/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:21213:37)
```
I get the same output when I run it with the ```--verbose``` flag

**Comment by joaomoreno** [comment]
Got it, thanks!

@jrieken Maybe you need a safeguard for when `product.commit` is `undefined`: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/environmentService.ts#L146 We should probably change `commit: string` to `commit?: string`.
