### ISSUE TITLE
Is it expected that in 1.16, Hovers with null items in their arrays do not render at all

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#34520]
This seems to be a breaking change in 1.16. I don't know if it's a bug or the old behaviour is considered bad, but it's resulted in a lot of hovers no longer rendering after the update.

`HoverProvider` contains Code looks like this:

```ts
resolve(new Hover(
	[{ language: 'dart', value: data.displayString }, data.documentation],
	range
));
```

The data passed to the hover is an array - the first item is an object with a language/value and the second item is additional documentation (which is just a markdown string).

If `data.documentation` is null in 1.15, the tooltip still rendered, just ignoring the second item:

![Working hovers](https://user-images.githubusercontent.com/1078012/30514362-1a8b9ba2-9b0b-11e7-8601-70cf3eeb1690.png)

However after updating, the hover does not appear *at all* when there's a null in that array.

![Broken hovers](https://user-images.githubusercontent.com/1078012/30514368-2be2e950-9b0b-11e7-8246-5b5f50d24d8e.png)

Is this an expected change? I can update my extension not to put nulls in here, though I don't know whether this might affect other extensions too. It was kinda convenient for Code to skip over this nulls, we could just string a bunch of variables together that may or may not be set for a given hover, but now we'll need to conditionally push them onto an array before sending.

**Comment by DanTup** [comment]
This only seems to happen for nulls... If I do `data.documentation || undefined` it appears fine.

**Comment by jrieken** [comment]
Will investigate...

**Comment by jrieken** [comment]
Yep, shows this error for me

```
shell.js:228 Cannot read property 'language' of null: TypeError: Cannot read property 'language' of null
	at isCodeblock (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostTypeConverters.js:132:32)
	at from (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostTypeConverters.js:136:17)
	at Array.map (native)
	at Object.fromMany (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostTypeConverters.js:127:27)
	at Object.fromHover (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostTypeConverters.js:261:38)
	at /Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:155:45
	at Promise_ctor.CompletePromise_then [as then] (/Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
	at HoverAdapter.provideHover (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:145:119)
	at /Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:701:96
	at ExtHostLanguageFeatures._withAdapter (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:629:20)
```

**Comment by jrieken** [comment]
Always refreshing to get remained about the fact that `typeof null === 'object'`....

**Comment by DanTup** [comment]
Great, thanks! 👍
