### ISSUE TITLE
[folding] NPE when closing an editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3472]
Open two files. Close one.
Most likely there's a timer that is not disposed?

```
Invalid arguments: Error: Invalid arguments
    at CodeEditorWidget.CommonCodeEditor.revealPositionInCenterIfOutsideViewport (file:///C:/Alex/src/vscode/out/vs/editor/common/commonCodeEditor.js:272:23)
    at FoldingController.updateHiddenAreas (file:///C:/Alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:371:25)
    at Object.FoldingController.onModelChanged.localToDispose.push.dispose (file:///C:/Alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:270:27)
    at Object.disposeAll (file:///C:/Alex/src/vscode/out/vs/base/common/lifecycle.js:21:28)
    at FoldingController.cleanState (file:///C:/Alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:180:47)
    at FoldingController.onModelChanged (file:///C:/Alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:248:18)
    at Array.<anonymous> (file:///C:/Alex/src/vscode/out/vs/editor/contrib/folding/browser/folding.js:133:128)
    at CodeEditorWidget.EventEmitter._emitToSpecificTypeListeners (file:///C:/Alex/src/vscode/out/vs/base/common/eventEmitter.js:177:37)
    at CodeEditorWidget.EventEmitter._emitEvents (file:///C:/Alex/src/vscode/out/vs/base/common/eventEmitter.js:202:22)
    at CodeEditorWidget.EventEmitter.emit (file:///C:/Alex/src/vscode/out/vs/base/common/eventEmitter.js:219:22)
```

**Comment by aeschli** [comment]
fixed with commit e68a6bd
