### ISSUE TITLE
Output: Cannot read property 'updateTitle' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34746]
Found this in my console when running out of sources, not sure how I triggered it though:

```
shell.js:228 Cannot read property 'updateTitle' of undefined: TypeError: Cannot read property 'updateTitle' of undefined
    at PanelPart.CompositePart.updateTitle (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/compositePart.js:252:28)
    at file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/compositePart.js:75:23
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1566:49)
    at PanelPart.CompositePart.doOpenComposite (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/compositePart.js:73:32)
    at PanelPart.CompositePart.openComposite (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/compositePart.js:58:25)
    at file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/panel/panelPart.js:84:60
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1566:49)
    at PanelPart.openPanel (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/panel/panelPart.js:84:28)
    at OutputService.showOutput (file:///Users/bpasero/Development/monaco/out/vs/workbench/parts/output/browser/outputServices.js:180:38)
    at Object.show (file:///Users/bpasero/Development/monaco/out/vs/workbench/parts/output/browser/outputServices.js:120:67)
```

Maybe related to recent changes around multi root workspace support? CC @sandy081

**Comment by bpasero** [comment]
@isidorn I can reproduce on every reload of the workbench, seems to be triggered by new code added from @dbaeumer (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1564) that appends output very early on startup.

**Comment by dbaeumer** [comment]
I can looking into postponing this a little...

**Comment by dbaeumer** [comment]
Otherwise @jrieken gets after me :-)

**Comment by dbaeumer** [comment]
Done

**Comment by dbaeumer** [comment]
@isidorn assigning back to you to decide whether you want to fix this. Others might do something like this as well.
