### ISSUE TITLE
Vscode hangs when expanding folder with 200K files

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#34841]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04

There are also around 200K error messages in the developer console, says something like
```ts
ipc.cp.ts:164 [IPC Library: Watcher] Error: watch /mnt/SSD/datasets/202585.jpg ENOSPC
```

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Related topic: https://code.visualstudio.com/docs/setup/linux#_error-enospc

**Comment by innerlee** [comment]
After increasing the `max_user_watches` limit, it still hangs with the following error
```javascript
Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at t.onInsertItems (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:218597)
    at t.onItemExpanded (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:721646)
    at t.onModelEvents (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:717366)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:716809
    at r (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:90777)
    at t.e._emitToBulkListeners (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:92856)
    at t.e._emitEvents (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:92938)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:92185
    at r (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:90777)
    at t.e._emitToBulkListeners (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28:92856)
e.onUnexpectedError @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29
```

**Comment by bpasero** [comment]
Smells like tree @joaomoreno

**Comment by joaomoreno** [comment]
Strange, that method isn't even recursive.

**Comment by agauniyal** [comment]
Call stack contains other things like arguments passed to it which could exceed call stack size as well

**Comment by agauniyal** [comment]
Call stack contains other things eg. arguments passed to it which could exceed call stack size as well so it might be something else than recursion...

**Comment by joaomoreno** [comment]
#18180
