### ISSUE TITLE
ArchLinux packaging

### ISSUE THREAD

**Issue by NicoHood** [Microsoft/vscode#34856]
Hi,
I am Nico, as Trusted user of ArchLinux. I am currently trying to package vscode for ArchLinux. Of course we want to compile the source from scratch and not use any precompiled binaries. However I got some difficulties to get the build running:

```
$ /var/lib/archbuild/extra-x86_64/arch/build/visual-studio-code/src/vscode-1.16.1/scripts/code.sh 
Could not load our cross platform file watcher: Error: The module '/var/lib/archbuild/extra-x86_64/arch/build/visual-studio-code/src/vscode-1.16.1/node_modules/nsfw/build/Release/nsfw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Falling back to our platform specific watcher...
module.js:529
    throw err;
    ^

Error: Cannot find module 'gulp-watch'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/archbuild/extra-x86_64/arch/build/visual-studio-code/src/vscode-1.16.1/build/lib/watch/index.js:32:68)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
Could not load our cross platform file watcher: Error: The module '/var/lib/archbuild/extra-x86_64/arch/build/visual-studio-code/src/vscode-1.16.1/node_modules/nsfw/build/Release/nsfw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Falling back to our platform specific watcher...
module.js:529
    throw err;
    ^

Error: Cannot find module 'gulp-watch'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/archbuild/extra-x86_64/arch/build/visual-studio-code/src/vscode-1.16.1/build/lib/watch/index.js:32:68)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
/var/lib/archbuild/extra-x86_64/arch/build/visual-studio-code/src/vscode-1.16.1/scripts/code.sh: line 41: /var/lib/archbuild/extra-x86_64/arch/build/visual-studio-code/src/vscode-1.16.1/.build/electron/code-oss: No such file or directory
```

The PKGBUILD I used was this one:
```bash
# Maintainer: NicoHood <archlinux {cat} nicohood {dog} de>
# PGP ID: 97312D5EB9D7AE7D0BD4307351DAE9B7C1AE9161
# Contributor: D. Can Celasun <can[at]dcc[dot]im>

pkgname=visual-studio-code
_pkgname=vscode
pkgver=1.16.1
pkgrel=1
pkgdesc="Open source editor for building and debugging modern web and cloud applications"
arch=('x86_64' 'i686')
url="https://code.visualstudio.com/"
license=('MIT')
provides=('vscode' 'visualstudiocode')
depends=(fontconfig libxtst gtk2 python cairo alsa-lib gconf nss gcc-libs libnotify libxss gvfs gulp)
makedepends=(npm electron git python2 libxkbfile)
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/Microsoft/${_pkgname}/archive/${pkgver}.tar.gz"
        "${pkgname}.desktop")
sha512sums=('98d50a799686063e4a320300bdb0de948e8c995e972caa69bf1ee0d09bbf5bdcd37c59e9b4377d7b4b3d196ef4c695eb3bad74b87043e6cc0b0463b28bbd9e30'
            '1c4e26c36e52c9272653f0f59f1972decb631db3fc0f0deb686ecbc710a69151d76b40bbf6ed11f99281a79d6d126777d6900c23ecae2116fa9389681cb033b3')
package() {
    cd "${_pkgname}-${pkgver}"
    if [ "${CARCH}" = "x86_64" ]; then
        ./scripts/npm.sh install --arch=x64 --python=/usr/bin/python2
    else
        ./scripts/npm.sh install --arch=ia32 --python=/usr/bin/python2
    fi
}
```

Note: The package is currently empty, I try to run vscode from the build directory, which should also work. Once this step succeeds, I can package it properly. I've installed all dependencies of course.

Any help appreciated.

**Comment by dcelasun** [comment]
@NicoHood You are using the wrong PKGBUILD (the one I wrote), it is intended only for the official binary distribution. 

You need to use the `-oss` [package](https://aur.archlinux.org/packages/visual-studio-code-oss) to build from source.

**Comment by NicoHood** [comment]
@dcelasun Thanks for pointing me into the correct direction. I totally missed this package. It seems that there is still a lot of patching required, which could be fixed by microsoft.

**Comment by Tyriar** [comment]
ArchLinux packaging is being handled by @dcelasun. I'm also at Ubuntu Rally right now working with Canonical on a snap package.
