### ISSUE TITLE
Error when searching one file, no folder open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35192]
- Open a new Code window, no folder
- Open exactly one file
- Do a search
- See results but also an error from RipgrepParser in the console. Doesn't seem to break it. This is because rg doesn't write the result file name when only searching one file, and the parser expects it.

**Comment by loveconlee** [comment]
I really am new to all this my Kodi isn't working like before I need help figuring it out I believe I deleted a few things help needed fixing I don't know what to do

**Comment by roblourens** [comment]
```
TypeError: Cannot read property 'addMatch' of undefined
    at t.handleMatchLine (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:4:154137)
    at t.handleDecodedData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:4:153868)
    at t.handleData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:4:153528)
    at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/search/node/searchApp.js:4:152371)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
