### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35204]
Found this in my console:

```
"Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at DebugViewlet.ViewsViewlet.updateViewStateSize (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:509:57)
    at DebugViewlet.ViewsViewlet.updateViews (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:360:46)
    at DebugViewlet.ViewsViewlet.onContextChanged (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:324:22)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:218:117
    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:35:39)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:294:37", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js (263)

```

**Comment by joaomoreno** [comment]
@sandy081 This happens when the same view descriptor appears twice on the `toDelete` array. @bpasero can you try to repro in the debug viewlet?

**Comment by sandy081** [comment]
Is it due to that debug scripts view is being registered multiple times with the same id?

**Comment by sandy081** [comment]
I would be placing a guard in the registry to prevent registering views with same id. Also got the confirmation that @weinand updates this debug script views to have unique ids.

**Comment by joaomoreno** [comment]
A guard doesn't really fix the issue... it would be great to have repro steps.

**Comment by sandy081** [comment]
Was not this due to duplicate ids?

**Comment by joaomoreno** [comment]
Could be, that's why I'm asking for repro steps, since we no longer have duplicate ids. Unless @bpasero saw this on an old version...?

**Comment by sandy081** [comment]
Ok. I think guard for preventing duplicate ids is good to have. May be I will wait to push that until we get the confirmation so that it will not obstruct to reproduce.

**Comment by joaomoreno** [comment]
Oh!!! Yes man, sorry, I didn't understand you meant the registry! I was thinking it was within the viewlet. Yeah we still need that. 👍

**Comment by sandy081** [comment]
No worries. 👍

**Comment by sandy081** [comment]
Reopening it, just to get confirmation from @bpasero

**Comment by bpasero** [comment]
I can verify from home, I do not have that setup here at work.
