### ISSUE TITLE
Intellisense and symbol search stops working in large Javascript project

### ISSUE THREAD

**Issue by markus-brt** [Microsoft/vscode#35212]
- VSCode Version: 1.16.1
- OS Version: Win10

We have a large JS project with approx. 8000 files. Since one of the latest releases the Intellisense (for all kinds of symbols, also DOM) stops working and also Symbol search (Ctrl-Shift-O). It will work for a few minutes, then it will only show "Loading..." or the loading animation of the search bar.
I noticed that the vscode process will allocate memory up to 1,2 GB and then go down to 500 MB again, (see the screenshot) and consumes 25-30% CPU. This continues for 1/2 hour. When "finished" the features works again, but only a few times until it starts over with "Loading..." and again the same CPU and memory usage.
It is also strange that my colleagues who use the same project are not affected by this issue.

![vscode_memory2](https://user-images.githubusercontent.com/18584269/30904072-19c251e8-a371-11e7-9a95-a0bf7526f27d.PNG)

Steps to Reproduce: ?
Reproduces without extensions: Yes

**Comment by markus-brt** [comment]
This is the Typescript output/logs:

[Info  - 10:34:31] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:34:31] Forking TSServer
PATH:...
[Error  - 10:44:39] TSServer exited with code: 3
[Info  - 10:44:39] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:44:39] Forking TSServer
PATH:...
[Error  - 10:44:39] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:405:32)
	at ChildProcess.childProcess.on (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:316:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Error  - 11:38:25] TSServer exited with code: 3
[Info  - 11:38:25] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 11:38:25] Forking TSServer
PATH:...
[Error  - 11:38:25] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:405:32)
	at ChildProcess.childProcess.on (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:316:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18847
