### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null.

### ISSUE THREAD

**Issue by dhmorrison** [Microsoft/vscode#35601]
Hi there,

I have no clue what this is about, but it is crashing the app we are developing.  It would appear that something (an object I know not what) is null and blowing up the xterm console when I move my mouse in the Chrome browser.

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-angular2-files|ale|1.3.10
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
bower|don|0.0.3
githistory|don|0.2.3
vscode-npm-script|eg2|0.2.1
Angular2|joh|2.7.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
view-in-browser|qin|0.0.5
nativescript|Tel|0.7.2
html-snippets|wge|0.1.5
html-css-class-completion|Zig|1.10.0

---

Steps to Reproduce:

1. Debug the web app in VS Code.
2. Navigate to any view.  
3. Move the mouse.

The whole app crumbles at: at NgIf.module.exports.NgIf._updateView...

I need to use *ngIf for obvious reasons, since this is an angular app.

>Uncaught TypeError: Cannot read property '1' of null     at SelectionModel.areSelectionValuesReversed  (C:\Program Files\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionModel.js:51)

fail: Microsoft.AspNetCore.NodeServices[0]
      ERROR ReferenceError: document is not defined
          at createDropCue (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\main-server.js:10885:24)
          at GroupConnectionService.register (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\main-server.js:10915:24)
          at new GroupPanelComponent (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\main-server.js:54294:14)
          at createClass (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\vendor.js:21881:26)
          at createDirectiveInstance (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\vendor.js:21699:37)
          at createViewNodes (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\vendor.js:23127:49)
          at Object.createEmbeddedView (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\vendor.js:23010:5)
          at TemplateRef_.module.exports.TemplateRef_.createEmbeddedView (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\vendor.js:21214:38)
          at ViewContainerRef_.module.exports.ViewContainerRef_.createEmbeddedView (C:\Users\dmorri3\Source\repos\revrec.Workbookmanager\rr.webapi\ClientApp\dist\vendor.js:2099

Honestly, I can't figure out if it is something I am doing wrong.  I have not seen this behavior before, and hope never to see it again.

Thanks for checking it out.

David

<h3>Reproduces without extensions: Not sure.  When I Control + f5 I get "Configured debug type 'coreclr' is not supported." </h3>

**Comment by isidorn** [comment]
Adding verified by code review. End can not now be null
