### ISSUE TITLE
"Some projects have trouble loading" error makes viewport smaller than entire editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3574]
Notice right down the bottom and the top:

![image](https://cloud.githubusercontent.com/assets/2193314/13416893/001c0bba-df1b-11e5-92d1-13597b10fd48.png)

To get in this state I loaded a folder that had an old C# project in it with tools version 12. It gave me an error at the top, so I opened and read it. Then I tried to close the file by middle clicking the file name up the top which entered the cursor scroll mode, allowing me to scroll the editor down. I did this immediately after installing C# (OmniSharp) on the latest Insiders build on Windows 10.

Here is the output that caused the issue:

```
[INFO] Starting OmniSharp at 'c:\Users\Daniel\Documents\dev\image-converter\ImageConverter.sln'...
[INFO] Started OmniSharp from 'C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.csharp-0.3.3\bin\omnisharp.cmd' with process id 3268...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location 'c:\Users\Daniel\Documents\dev\image-converter' on host 5004.
[ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations C:\Users\Daniel\.dnx\runtimes\dnx-clr-win-x86.default
C:\Users\Daniel\.dnx\runtimes\kre-clr-win-x86.default
C:\Users\Daniel\.dnx\packages\KRE-CLR-x86.default
C:\Users\Daniel\.k\runtimes\dnx-clr-win-x86.default
C:\Users\Daniel\.k\runtimes\kre-clr-win-x86.default
C:\Users\Daniel\.k\packages\KRE-CLR-x86.default
C:\Users\Daniel\.kre\runtimes\dnx-clr-win-x86.default
C:\Users\Daniel\.kre\runtimes\kre-clr-win-x86.default
C:\Users\Daniel\.kre\packages\KRE-CLR-x86.default.
Visit https://github.com/aspnet/Home for an installation guide.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning 'c:\Users\Daniel\Documents\dev\image-converter' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] No project.json based projects found
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Detecting projects in 'c:\Users\Daniel\Documents\dev\image-converter\ImageConverter.sln'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'c:\Users\Daniel\Documents\dev\image-converter\ImageConverter\ImageConverter.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for c:\Users\Daniel\Documents\dev\image-converter\ImageConverter\ImageConverter.csproj
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file 'c:\Users\Daniel\Documents\dev\image-converter\ImageConverter\ImageConverter.csproj'.
Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "12.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".  c:\Users\Daniel\Documents\dev\image-converter\ImageConverter\ImageConverter.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(MSBuildOptions options, ILogger logger, String solutionDirectory, String projectFilePath, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProject(String projectFilePath)
c:\Users\Daniel\Documents\dev\image-converter\ImageConverter\ImageConverter.csproj(0,0)
Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "12.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".  c:\Users\Daniel\Documents\dev\image-converter\ImageConverter\ImageConverter.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(MSBuildOptions options, ILogger logger, String solutionDirectory, String projectFilePath, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProject(String projectFilePath)

[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'c:\Users\Daniel\Documents\dev\image-converter'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
```

**Comment by bpasero** [comment]
@Tyriar can you inspect what HTML element the message is in DOM? I suspect the middle mouse scrolling revealed it somehow.

**Comment by Tyriar** [comment]
```
<div class="alert" role="alert" aria-atomic="true">Warning: Some projects have trouble loading. Please review the output for more details.</div>
```

Inside `body > div.aria-container`

**Comment by bpasero** [comment]
Thanks, I suspected that one.

**Comment by Tyriar** [comment]
Adding `left: -999em` to `.aria-container` will correctly take it out of the page flow.

**Comment by bpasero** [comment]
Yeah, something like that. We still have to ensure a screen reader picks it up.

**Comment by Tyriar** [comment]
Yep, sending it off screen should still be read out by the screen reader.

**Comment by isidorn** [comment]
@Tyriar please verify until end of week since this is a stable-candidate

**Comment by Tyriar** [comment]
Not working in latest alpha with the changes, it's even worse:

![image](https://cloud.githubusercontent.com/assets/2193314/13502875/a522671e-e121-11e5-8f59-f1cd1db1244c.png)

Verified again in devtools, `left:-999em;` takes it out of the flow of the page.

**Comment by bpasero** [comment]
@Tyriar ok I pushed a change with your suggestion to stable, can you please verify again?

**Comment by Tyriar** [comment]
Fixed :+1:
