### ISSUE TITLE
Running MSBuild based build task hangs forever

### ISSUE THREAD

**Issue by plbpietrz** [Microsoft/vscode#35752]
VSCode gets stuck when trying to build a simple C++ project (Visual C++ template console app) using the default build task (generated by the editor) with the terminal showing that it tries to execute MSBuild. The editor indicates that the command is running but the process explorer shows only one new `code.exe` process instance spawned and one of the existing earlier `code.exe` processes spinning excessively on `Code.exe!IsSandboxedProcess`, nothing else. Now I can't run any more build tasks and cannot stop the 'executing' one. To reset the situation I have to restart the editor.

- VSCode Version: 1.16
- OS Version: Windows 10 Professional x64

Steps to Reproduce:

1. Create dummy C++ console app project in Visual C++
2. Open solution folder with `code .` (from visual studio developer prompt but no difference if normal `cmd.exe` is used)
3. Create default MSBuild build task in `tasks.json`
4. Execute build task (ctrl + shift + b)
5. Wait...

Reproduces without extensions: Yes

**Comment by Identifier** [comment]
I'm having the exact same issue with a C# project (trying to use msbuild task to generate an .exe with .NET 4.7 -- not using .NET Core).  The build task just hangs forever (shows a spinning icon in the bottom-left statusbar) and killing VS Code is the only way to terminate it.  I'm attaching the sample project here.

[HangsVSCode.zip](https://github.com/Microsoft/vscode/files/1377977/HangsVSCode.zip)

**Comment by dbaeumer** [comment]
I was able to reproduce this. It is independent of the .Net version. I haven't found out yet why this is broken right now (it used to work before), but an easy workaround is to change the type from process to shell. 
```ts
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"taskName": "build",
			"type": "shell",
			"command": "msbuild",
			"args": [
				// Ask msbuild to generate full paths for file names.
				"/property:GenerateFullPaths=true",
				"/t:build"
			],
            "group": {
                "kind": "build",
                "isDefault": true
            },
 			"presentation": {
				// Reveal the output only if unrecognized errors occur.
				"reveal": "silent"
			},
			// Use the standard MS compiler pattern to detect errors, warnings and infos
			"problemMatcher": "$msCompile"
		}
	]
}
```

**Comment by dbaeumer** [comment]
@Tyriar to execute a process in the terminal I basically uses it as the executable to be started. The command line for the msbuild process looks like this:

![capture](https://user-images.githubusercontent.com/1931590/31485141-1472dad2-af33-11e7-8267-c07390fd079f.png)

For some reason that fails but I get no feedback why. All I see is that the node process started as `--type=terminal` is still around but has no sub processes.  If it try to execute a task like this
```ts
        {
            "taskName": "node",
            "type": "process",
            "command": "node",
            "args": [
                "hello.js"
            ]
        }
```
it works fine. So this is not a principal issue. I guess somehow the command line for msbuild gets messed up. Is there a way I can debug this?

**Comment by dbaeumer** [comment]
@Tyriar  I found https://github.com/Microsoft/vscode/issues/31301 which is very likely the cause of this.

**Comment by Identifier** [comment]
@dbaemer thanks, setting type from process to shell definitely got past the hanging build task problem.  Now it's on to the next issue for me:

```
> Executing task: msbuild /property:GenerateFullPaths=true /t:build <

'msbuild' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

I will look for a separate bug for that.  Thanks!

**Comment by plbpietrz** [comment]
@Identifier is MSBuild on your `%PATH%`? I used to run `code` from a developer prompt provided by the Visual Studio installation so the directory containing `msbuild` was already on the search path. It's not set globally by default.

**Comment by Identifier** [comment]
@plbpietrz Nope, I purposefully haven't installed Visual Studio on this machine yet - I wanted to see how easy it was to create a simple console application (.exe, not .NET Core) with _just_ VSCode on a clean machine.  I was hoping that the version of MSBuild that comes with OmniSharp would have been sufficient but unfortunately it's not.  Even if you add it to the path (or fully specify the full path in the "command" parameter in tasks.json) it fails for some other reason:

```
> Executing task: C:\Users\User\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe /property:GenerateFullPaths=true /t:build <


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
The terminal process terminated with exit code: 3762504530

Terminal will be reused by tasks, press any key to close it.
```

I finally got it to build on the clean machine by pointing to a version of MSBuild at C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe which must have been installed sometime else.  But none of this would have been even possible without @dbaemer's suggestion of changing the type from process to shell.  Thanks again @dbaeumer

**Comment by Tyriar** [comment]
@dbaeumer yeah I was reminded of https://github.com/Microsoft/vscode/issues/31301, let's leave this open until we close that so we can get this verified independently.

**Comment by dbaeumer** [comment]
@Identifier good to hear that it works for you as a shell task. I will make this the default for msbuild since it makes more sense anyways. Keeping this open since we need to fix the underlying issue as well.

**Comment by alexjamesbrown** [comment]
changing from process to shell worked for me too.
