### ISSUE TITLE
Can't compile across multi-lines~wtf

### ISSUE THREAD

**Issue by countBunny** [Microsoft/vscode#35864]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.3.2
azure-functions-tools|joh|0.3.1
vscode-codemetrics|kis|1.9.6
debugger-for-chrome|msj|3.3.1
vscode-for-node-js-development-pack|nod|1.1.0
vscode-docker|Pet|0.0.18
code-settings-sync|Sha|2.8.3
vscode-import-cost|wix|2.5.0

---

Steps to Reproduce:

1.just write code like this 
```
ctx.response.body = 
'<h1>index</h1>
<form action="/signin" method="post">
<p>Name:<input name="name" value="koa"></p>
<p>Password:<input name="password" type="password"></p>
<p><input type="submit" value="Submit"></p>
</form>'
```

2.then try to run them, compile exception happened
```
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:605:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
please tell me how to deal with it, as I'm not familiar with this IDE

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
This is an error with your code, not with VSCode. You need to use backticks (`) instead of single quotes for mulitline strings in JavaScript
