### ISSUE TITLE
Missing workspace prevents start of vscode

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#35871]
- VSCode Version: 1.7
- OS Version: 10.13

Steps to Reproduce:

1. Trying to start vscode stable
2. Getting the following error
```
Error: ENOTDIR: not a directory, open '/Users/stschneider/Library/Application Support/Code/Workspaces/.DS_Store/workspace.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at e.resolveWorkspaceSync (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:328478)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:331924
    at Array.map (native)
    at e.getUntitledWorkspacesSync (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:331900)
    at e.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:291018)
    at t.openFirstWindow (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:354654)
```

Reproduces without extensions: Yes

**Comment by bm-stschneider** [comment]
Okay, found a solution. I went to the folder and there was a Workspace folder but it was completely empty so I removed it and I was able to start vscode stable again.
