### ISSUE TITLE
black window

### ISSUE THREAD

**Issue by qtbit** [Microsoft/vscode#36029]
- VSCode Version: 1.18.0-insider
- OS Version: Win10

Steps to Reproduce:

1. run VS Code Insiders
2. add `C:\Program Files\Microsoft VS Code Insiders\bin` to PATH env var
3. run `code-insiders .` from cmd line
4. just black windows appears

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/25822015/31426682-97f55f94-ae64-11e7-8517-731550c33fed.png)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by qtbit** [comment]
The verbose output is:

`code --verbose .

[90m[main 8:06:51 AM][0m Sending env to running instance...
[90m[main 8:06:51 AM][0m Sending some foreground love to the running instance: 5924
[90m[main 8:06:51 AM][0m Sent env to running instance. Terminating...`

The console log is more interesting:

![image](https://user-images.githubusercontent.com/25822015/31532569-5ac440dc-afee-11e7-8543-2c655bfe71e4.png)

**Comment by bpasero** [comment]
@qtbit I wonder if something is mixed up with your installation and the user you are running code with. It almost looks like parts of VS Code cannot be accessed with the user rights. 

Generally we do not recommend to run code as administrator. Does it change anything when you run as normal user? Also please make sure you have Code installed as normal user and not via running as admin.

**Comment by qtbit** [comment]
There should be nothing mixed up with my installation. Interestingly it works, when I run Code as normal user! Do not understand why, since the admin has more rights than a normal user. Anyway I use a file manager with admin rights and run Code from there, so it's not a solution for me :-(

It looks like Code cannot run `C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\files\node\watcher\win32\CodeHelper.exe` as a node child process for some reason (spawn EACCES).

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mlapierre** [comment]
I have the same problem. It's fine if I open from a cmd prompt as a normal user, but fails to initialize correctly if I'm using an admin session.

Here's the console output from the current insiders build:

```
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:10 spawn EACCES: Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:390:9)
    at t.startWatcher (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2467085)
    at new t (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2466939)
    at e.startWatching (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2468971)
    at e.setupWorkspaceWatching (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2471464)
    at new e (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2470407)
    at t.e (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2485401)
    at new t (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2490549)
e.createContents @ /C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:10
index.js:5 [uncaught exception]: Error: spawn EACCES
onError @ index.js:5
index.js:5 Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:390:9)
    at t.startWatcher (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2467085)
    at new t (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2466939)
    at e.startWatching (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2468971)
    at e.setupWorkspaceWatching (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2471464)
    at new e (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2470407)
    at t.e (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2485401)
    at new t (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:9:2490549)
```

`--verbose` shows output similar to what @qtbit reported.

**Comment by mlapierre** [comment]
Well this is unhelpful I'm afraid. I restarted my PC and now I can't reproduce the error. I'll comment again if I can reliably reproduce it.

**Comment by qtbit** [comment]
@bpasero Thanks, the latest update of VS Code Insiders fixed the black screen issue. However, there are still errors in the dev console.

![image](https://user-images.githubusercontent.com/25822015/32898896-bb4309c8-cae9-11e7-9763-330f7d490f41.png)

**Comment by ramya-rao-a** [comment]
@qtbit If you still see the console errors, then please log a new issue as the original issue of black window has been resolved.
