### ISSUE TITLE
Can't debug js code in Edge from VS Code

### ISSUE THREAD

**Issue by purelight01** [Microsoft/vscode#36158]
I am using Windows 10 preview build (Build 16299.15) with EdgeHTML 16.16299.
Visual Studio Code 1.17.0.

Here is debug config on the launch.json.
Basically I created 2 entries: each for Chrome and Edge.
```json
{
	"type": "chrome",
	"request": "launch",
	"name": "Launch Chrome",
	"diagnosticLogging": true,
	"sourceMaps": true,
	"file": "${workspaceRoot}/Chapter1-hello-world/hello.html"
},
{
	"type": "edge",
	"request": "launch",
	"name": "Launch Edge",
	"diagnosticLogging": true,
	"sourceMaps": true,
	"file": "${workspaceRoot}/Chapter1-hello-world/hello.html"
},
```

When debugging using Chrome, the breakpoint in the js file works just expected.
Switching to Edge, I am getting errors.

 ›Error: unexpected server response (400)
    at ClientRequest.response (C:\Users\glay1\.vscode\extensions\msjsdiag.debugger-for-edge-0.4.1\node_modules\ws\lib\WebSocket.js:694:15)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"[debugger-for-chrome] unexpected server response (400)"}
  ›******** ERROR! Unhandled promise rejection: Error: unexpected server response (400)
  ›Adapter error: Error: Command failed: C:\Users\glay1\.vscode\extensions\msjsdiag.debugger-for-edge-0.4.1\node_modules\edge-diagnostics-adapter\dist\x64\EdgeDiagnosticsAdapter.exe --port=9222
[2017-10-12 10:56:23] [error] Handshake ended with HTTP error: 400
[2017-10-12 10:56:23] [error] Handshake ended with HTTP error: 400
[2017-10-12 10:56:23] [error] Handshake ended with HTTP error: 400
[2017-10-12 10:56:23] [error] Handshake ended with HTTP error: 400
[2017-10-12 10:56:24] [error] Handshake ended with HTTP error: 400
[2017-10-12 10:56:24] [error] Handshake ended with HTTP error: 400
[2017-10-12 10:56:24] [error] Handshake ended with HTTP error: 400

  ›From client: disconnect({"restart":false})
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}

**Comment by isidorn** [comment]
Please file this against the edge extension here https://github.com/Microsoft/vscode-edge-debug
