### ISSUE TITLE
Failed to execute 'getComputedStyle' error on run build task

### ISSUE THREAD

**Issue by BenoitValdes** [Microsoft/vscode#36204]
- VSCode Version: Code - Insiders 1.18.0-insider (d1047a65ed5db2ffc26c01ebc6f4ed91a0b5eb26, 2017-10-13T05:11:50.336Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
clarissecomandport|Ben|0.5.0
indenticator|Sir|0.4.2
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
python|don|0.7.0
cpptools|ms-|0.13.1
live-server-preview|neg|0.0.4
datetime|rid|1.0.5
vscode-icons|rob|7.15.0

(1 theme extensions excluded)

---

I just updated vscode-insiders. From this moment everytime that I run my build task I get these messages:
![screen shot 2017-10-13 at 09 57 42](https://user-images.githubusercontent.com/12208428/31536122-d5182a74-affd-11e7-9102-9cfbf2428747.png)
![screen shot 2017-10-13 at 09 58 00](https://user-images.githubusercontent.com/12208428/31536142-df3b1a48-affd-11e7-9079-700b4477402e.png)
The first message appears only the first time. The second one appears every time I launch build task

Steps to Reproduce:

1. Run Build Task

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
This happens if the terminal has never been to the front.

**Comment by dbaeumer** [comment]
I saw this as well when running out of source and the two traces are:
```
[21112:1013/082917.677:INFO:CONSOLE(45)] "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.            
    at TerminalInstance.setVisible (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:463:44)         
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/common/terminalService.js:146:34                                                  
    at Array.forEach (native)                                                                                                                           
    at TerminalService.setActiveInstanceByIndex (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/common/terminalService.js:145:37)       
    at TerminalService.createInstance (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalService.js:57:22)        
    at TerminalTaskSystem.createTerminal (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:550:47)    
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:314:32                                        
    at new Promise_ctor (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1641:17)                                                   
    at TerminalTaskSystem.executeCommand (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:313:27)    
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:224:34", source: file:///P:/mseng/VSCode/vscod
e/out/vs/base/common/errors.js (45)                                                                                                                     
[21112:1013/082917.677:INFO:CONSOLE(263)] "Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined                    
    at TerminalService.setActiveInstance (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/terminal/common/terminalService.js:137:80)              
    at TerminalTaskSystem.executeCommand (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:357:34)    
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:224:34                                        
    at Promise_ctor.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)                        
    at TerminalTaskSystem.executeTask (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:217:61)       
    at TerminalTaskSystem.run (file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.js:105:97)               
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/task.contribution.js:1111:63                                        
    at _Base.Class.derive._creator.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)         
    at file:///P:/mseng/VSCode/vscode/out/vs/workbench/parts/tasks/electron-browser/task.contribution.js:1110:56                                        
    at Promise_ctor.CompletePromise_then [as then] (file:///P:/mseng/VSCode/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)", source: file:///P:/ms
eng/VSCode/vscode/out/vs/workbench/electron-browser/shell.js (263)                                                                                      
```

**Comment by dbaeumer** [comment]
@Tyriar moving to you. The `setActiveInstance` failure is a follow-up error of the task system not handling the terminal creation failure correctly. I fixed that.

**Comment by Tyriar** [comment]
The `getComputedStyle` issue was fixed the other day, I think it's good in the latest Insiders.
