### ISSUE TITLE
Error building VSCode in Windows

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#36356]
- VSCode Version: current master
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. checkout vscode git repository
2. type `scripts\npm.bat install`
3. type `npm run watch`
4. type `.\scripts\code.bat`

The following error appears in the console:

```
E:\Docs\Dev\vscode>.\scripts\code.bat

{ Error: Cannot find module './build/Release/keymapping'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (E:\Docs\Dev\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at NativeBinding._init (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:61:18)
    at KeyboardLayoutMonitor.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\out\vs\code\electron-main\keyboard.js:26:30)
    at CodeApplication.registerListeners (E:\Docs\Dev\vscode\out\vs\code\electron-main\app.js:148:55) code: 'MODULE_NOT_FOUND' }
[7192:1016/143148.321:INFO:CONSOLE(224)] "Loading "gc-signals" failed", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (224)
[7192:1016/143148.321:INFO:CONSOLE(225)] "Detail: ", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (225)
[7192:1016/143148.322:INFO:CONSOLE(227)] "Error: A dynamic link library (DLL) initialization routine failed.
\\?\E:\Docs\Dev\vscode\node_modules\gc-signals\build\Release\gcsignals.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Docs\Dev\vscode\node_modules\gc-signals\src\index.js:8:18)
    at Object.<anonymous> (E:\Docs\Dev\vscode\node_modules\gc-signals\src\index.js:67:3)", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (227)
[7192:1016/143148.322:INFO:CONSOLE(229)] "Here are the modules that depend on it:", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (229)
[7192:1016/143148.322:INFO:CONSOLE(230)] "vs/workbench/api/electron-browser/mainThreadHeapService", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (230)

E:\Docs\Dev\vscode>
E:\Docs\Dev\vscode>
E:\Docs\Dev\vscode>.\scripts\code.bat

{ Error: Cannot find module './build/Release/keymapping'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (E:\Docs\Dev\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at NativeBinding._init (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\node_modules\native-keymap\index.js:61:18)
    at KeyboardLayoutMonitor.onDidChangeKeyboardLayout (E:\Docs\Dev\vscode\out\vs\code\electron-main\keyboard.js:26:30)
    at CodeApplication.registerListeners (E:\Docs\Dev\vscode\out\vs\code\electron-main\app.js:148:55) code: 'MODULE_NOT_FOUND' }
[10024:1016/145316.117:INFO:CONSOLE(224)] "Loading "gc-signals" failed", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (224)
[10024:1016/145316.121:INFO:CONSOLE(225)] "Detail: ", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (225)
[10024:1016/145316.125:INFO:CONSOLE(227)] "Error: A dynamic link library (DLL) initialization routine failed.
\\?\E:\Docs\Dev\vscode\node_modules\gc-signals\build\Release\gcsignals.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Docs\Dev\vscode\node_modules\gc-signals\src\index.js:8:18)
    at Object.<anonymous> (E:\Docs\Dev\vscode\node_modules\gc-signals\src\index.js:67:3)", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (227)
[10024:1016/145316.126:INFO:CONSOLE(229)] "Here are the modules that depend on it:", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (229)
[10024:1016/145316.126:INFO:CONSOLE(230)] "vs/workbench/api/electron-browser/mainThreadHeapService", source: file:///E:/Docs/Dev/vscode/out/vs/loader.js (230)
```

**Comment by mjbvz** [comment]
Possibly https://github.com/Microsoft/vscode/issues/34419

Which npm version are you using? We only support npm 4 current.

**Comment by warpdesign** [comment]
@mjbvz I was running `npm 5.3`. I downgraded to `npm 4.6.1` typed `git clean -xfd` and re-ran npm install but I still get the same error.

**Comment by davidsk** [comment]
Yeah, I'm seeing this too.

**Comment by davidsk** [comment]
Downgraded to npm 4 and seems to be working

**Comment by warpdesign** [comment]
I installed npm@4.0, cleaned up using `git clean -xfd`, also removed any files that were modified by previous build/install process using `git reset --hard` and after doing the process all over again (it's so slow on Windows) it's now working.

I suggest adding a note about the version in the [How-To-Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) file to indicate that only `npm 4` is supported for now.
