### ISSUE TITLE
convertOutputPositionToInputPosition can throw 'Not supported' when landing in an invisible line

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3662]
fyi @egamma

**Comment by alexandrudima** [comment]
From unit tests, I could find a reproducible case. Have a javascript file:
```
something {
  asd
  asd
  asd
  asd }
```

* Place cursor at the end of the first line (such that you get bracket matching)
* Fold the region
* Observe error:
```
Not supported: Error: Not supported
    at IdentitySplitLine.getOutputLineMaxColumn (file:///C:/Alex/src/vscode/out/vs/editor/common/viewModel/splitLinesCollection.js:41:23)
    at SplitLinesCollection.getOutputLineMaxColumn (file:///C:/Alex/src/vscode/out/vs/editor/common/viewModel/splitLinesCollection.js:482:42)
    at ViewModel.getLineMaxColumn (file:///C:/Alex/src/vscode/out/vs/editor/common/viewModel/viewModel.js:312:31)
    at View.getCenteredRangeInViewport (file:///C:/Alex/src/vscode/out/vs/editor/browser/view/viewImpl.js:454:107)
    at CodeEditorWidget.getCenteredRangeInViewport (file:///C:/Alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:87:31)
    at ViewModel.getCurrentCenteredModelRange (file:///C:/Alex/src/vscode/out/vs/editor/common/commonCodeEditor.js:539:146)
    at file:///C:/Alex/src/vscode/out/vs/editor/common/viewModel/viewModel.js:125:56
    at ViewModel.EventEmitter.deferredEmit (file:///C:/Alex/src/vscode/out/vs/base/common/eventEmitter.js:230:26)
    at ViewModel.onEvents (file:///C:/Alex/src/vscode/out/vs/editor/common/viewModel/viewModel.js:121:18)
    at Array.<anonymous> (file:///C:/Alex/src/vscode/out/vs/editor/common/viewModel/viewModel.js:117:102)
```

**Comment by alexandrudima** [comment]
@egamma It can also happen when the first line is collapsed. It is not clear to me how you got in this state, but it looks like your first line was collapsed in the editor view state:
```
"contributionsState": {
    "editor.contrib.folding": [
        {
            "startLineNumber": 1,
            "endLineNumber": 5,
            "indent": 0,
            "isCollapsed": true
        },
```

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by egamma** [comment]
goodness!
