### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36868]
Steps to Reproduce:

0. open empty window
1. open debug viewlet
2. open explorer
3. add 1 folder
4. add 1 folder
5. remove 1 folder
6. remove 1 folder

```
		Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
		    at DebugViewlet.ViewsViewlet.updateViewStateSize (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:520:57)
		    at DebugViewlet.ViewsViewlet.updateViews (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:359:46)
		    at DebugViewlet.ViewsViewlet.onViewsDeregistered (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:308:25)
		    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:35:39)
		    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
		    at class_1.exports.ViewsRegistry.class_1.deregisterViews (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsRegistry.js:74:39)
		    at ExplorerViewlet.registerViews (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/browser/explorerViewlet.js:139:47)
		    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/browser/explorerViewlet.js:88:105
		    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:35:39)
		    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
```

**Comment by isidorn** [comment]
This is coming from the `viewsViewlet` an `undefined` view is being passed as seen in the picture. Forwarding to @joaomoreno 

![screen shot 2017-10-25 at 17 00 29](https://user-images.githubusercontent.com/1926584/32006061-12452e4a-b9a6-11e7-9782-6aca2dfd6b22.png)

**Comment by joaomoreno** [comment]
Seems to be independent of my refactoring and more about how the `ViewsViewlet` works.

**Comment by HutzlerGregg** [comment]
#36227

**Comment by HutzlerGregg** [comment]
@bpasero
