### ISSUE TITLE
Crash on Ubuntu 12.04

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3700]
*From @isomorphisms on https://github.com/Microsoft/vscode/issues/50*

I got this error in Ubuntu 12.04.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/opt/VSCode-linux-ia32/resources/atom.asar/browser/lib/init.js:120:7)
    at Object.<anonymous> (/opt/VSCode-linux-ia32/resources/atom.asar/browser/lib/init.js:132:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:130:18)
    at node.js:982:3

```

**Comment by bpasero** [comment]
Likely an electron issue...

**Comment by Tyriar** [comment]
@bpasero there were 2 reports in like 24 hours, electron wasn't touched recently was it?

**Comment by bpasero** [comment]
@Tyriar no

**Comment by bpasero** [comment]
Filed https://github.com/atom/electron/issues/4705 to get some more insights from Electron.

**Comment by Tyriar** [comment]
Another case https://github.com/Microsoft/vscode/issues/3737, they all seem to be on Ubuntu 12.04.

**Comment by bpasero** [comment]
@isomorphisms @Tyriar  According to electron: Electron needs to write to $XDG_CONFIG_HOME/APP_NAME, this error happens when users don't have permission to create or write to that directory. please make sure you have the permissions. 

We should probably add this to our FAQ. @gregvanl fyi

**Comment by biazzotto** [comment]
I just did:
`sudo rm -r -f ~/.cache`

I don't know if it was the best solution at all, but it does the trick...
