### ISSUE TITLE
Cannot read property 'panel' of undefined

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode#37026]
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T04:19:22.491Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
tslint|eg2|1.0.13
vscode-abap|lar|0.1.0
Go|luk|0.6.66
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.4.0
vscode-icons|rob|7.16.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Start VS Code
2. Open the extension sidebar menu
3. Search for an extension (search query is not relevant)
4. The following error appears:

![image](https://user-images.githubusercontent.com/17984549/32096039-7288bb72-bb05-11e7-9f37-efd579a3c947.png)

(First try to reproduce, not relevant anymore)

> 1. Don't open a folder, just open VS Code
> 2. Open the terminal, do something (in my case create a new VS Code extension with yo)
> 3. Open the extension page (via the sidebar)
> 4. Search for an extension (in my case postscript)

Stacktrace:
```
/C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property 'panel' of undefined: TypeError: Cannot read property 'panel' of undefined
    at t.updateViewHeaders (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:10:399066)
    at file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:10:403928
    at n.Class.derive._oncancel.then (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:9:69045)
    at t.<anonymous> (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:10:403886)
    at i (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:10:1152363)
    at Object.v.__generator.r [as next] (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:10:1151698)
    at s (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:9:72607)
    at n.Class.derive._oncancel.then (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:9:69045)
    at c (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:9:72741)
    at g (file:///C:/Programme/VSCodeInsider/resources/app/out/vs/workbench/workbench.main.js:9:72751)
```

Reproduce without extension: Yes

**Comment by maxibanki** [comment]
This is the part where the exception occurs (Line 274 i think):
https://github.com/Microsoft/vscode/blob/10ba78f6f3d17116aa378188b71fbd01d5dea7a8/src/vs/workbench/browser/parts/views/panelViewlet.ts#L272-L279
