### ISSUE TITLE
 TypeError: Cannot read property 'addMatch' of undefined

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode#37046]
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T04:19:22.491Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
tslint|eg2|1.0.13
vscode-abap|lar|0.1.0
Go|luk|0.6.66
postscript|max|1.0.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.4.0
vscode-icons|rob|7.16.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

```

console.ts:123 [IPC Library: Search] TypeError: Cannot read property 'addMatch' of undefined
    at t.handleMatchLine (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\services\search\node\searchApp.js:4:154137)
    at t.handleDecodedData (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\services\search\node\searchApp.js:4:153868)
    at t.handleData (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\services\search\node\searchApp.js:4:153528)
    at Socket.<anonymous> (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\services\search\node\searchApp.js:4:152371)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
t.log @ console.ts:123
(anonymous) @ ipc.cp.ts:158
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
r @ event.ts:12
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

```

Steps to Reproduce:

1. No idea sorry

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/35192
