### ISSUE TITLE
can't build on Ubuntu

### ISSUE THREAD

**Issue by isomorphisms** [Microsoft/vscode#3705]
```
/opt/vscode$ ./scripts/code.sh
[03:40:27] Using gulpfile /opt/vscode/gulpfile.js
[03:40:27] Starting 'electron'...
[03:40:27] Finished 'electron' after 382 μs
[32666:0304/034027:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/opt/vscode/.build/electron/resources/atom.asar/browser/lib/init.js:120:7)
    at Object.<anonymous> (/opt/vscode/.build/electron/resources/atom.asar/browser/lib/init.js:132:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:130:18)
    at node.js:982:3
```

**Comment by isomorphisms** [comment]
```
...
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/lib/common/beautify.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/lib/common/beautify-html.mock.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/lib/common/beautify-html.d.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/lib/common/beautify-css.d.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/php/common/php.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/php/common/php.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/markdown/common/markdownWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/markdown/common/markdownTokenTypes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/markdown/common/markdown.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/markdown/common/markdown.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/less/common/lessWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/less/common/lessTokenTypes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/less/common/less.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/less/common/less.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/json/common/jsonWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/json/common/jsonSchemaService.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/json/common/jsonIntellisense.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/json/common/json.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/json/common/json.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/html/common/htmlWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/html/common/htmlTokenTypes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/html/common/htmlTags.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/html/common/htmlScanner.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/html/common/htmlEmptyTagsShared.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/html/common/html.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/html/common/html.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/javascript/common/javascriptWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/javascript/common/javascript.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/javascript/common/javascript.extensions.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/javascript/common/javascript.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/handlebars/common/handlebarsTokenTypes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/handlebars/common/handlebars.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/handlebars/common/handlebars.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/css/common/level.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/css/common/cssWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/css/common/cssTokenTypes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/css/common/css.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/css/common/css.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/node/plist.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/node/flow.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/node/decoder.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/uuid.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/uri.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/types.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/strings.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/sortedList.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/scorer.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/paths.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/objects.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/network.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/mime.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/keyCodes.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/json.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/graph.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/glob.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/filters.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/eventEmitter.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/event.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/errors.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/collections.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/cancellation.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/async.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/assert.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/arrays.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/common/actions.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/quickopen.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/progressBar.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/mockDom.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/mockDom.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/mockBrowserService.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/htmlContent.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/highlightedLabel.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/dom.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/builder.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/browserService.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/test/browser/browser.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/worker/workerServer.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/worker/workerProtocol.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/worker/workerClient.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/worker/simpleWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/marked/simpleMarkedWorker.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/marked/marked.mock.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/marked/marked.d.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/diff/diffChange.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/diff/diff2.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/diff/diff.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/bits/encoding.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/test/common/testModes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/test/common/servicesTestUtils.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/test/common/modesUtil.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/test/common/modesTestUtils.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/test/common/editorTestUtils.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/node/textMate/vscode-textmate.d.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/node/textMate/TMSyntax.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/node/textMate/TMSnippets.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/xml.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/vb.tests.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/testUtil.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/swift.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/sql.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/ruby.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/r.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/python.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/powershell.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/objective-c.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/lua.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/java.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/jade.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/go.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/fsharp.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/dockerfile.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/csharp.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/cpp.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/coffee.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/test/bat.test.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/common/modes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/common/languages.common.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/common/editorCommonExtensions.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/common/editorCommon.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/common/editorActionEnablement.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/common/editorAction.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/common/commonCodeEditor.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/browser/editorBrowserExtensions.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/browser/editorBrowser.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/browser/editor.all.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/worker/workerMain.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/worker/defaultWorkerFactory.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/windows.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/window.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/update-manager.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/storage.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/sharedProcessMain.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/sharedProcess.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/settings.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/menus.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/main.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/lifecycle.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/env.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-main/cli.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/window.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/update.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/shell.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/main.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/main.contribution.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/integration.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/crashReporter.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/electron-browser/actions.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/node/userSettings.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/node/pluginHostProcess.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/node/extensionPoints.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/node/extensionHostMain.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/viewlet.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/storage.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/panel.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/options.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/memento.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/events.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/editor.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/contributions.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/constants.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/composite.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/component.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/common/actionRegistry.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/workbench.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/viewlet.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/quickopen.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/part.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/panel.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/layout.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/composite.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/workbench/browser/actionBarRegistry.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/zip.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/stream.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/stdFork.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/service.net.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/service.cp.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/request.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/proxy.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/processes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/ports.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/plist.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/pfs.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/mime.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/flow.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/extfs.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/env.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/encoding.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/decoder.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/node/aiAdapter.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/winjs.base.d.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/uuid.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/uri.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/types.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/timer.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/strings.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/stopwatch.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/sortedList.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/severity.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/service.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/scrollable.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/scorer.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/remote.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/processes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/platform.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/paths.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/parsers.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/objects.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/numbers.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/network.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/mime.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/marshalling.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/lifecycle.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/labels.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/keyCodes.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/jsonSchema.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/json.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/iterator.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/http.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/htmlContent.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/hash.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/graph.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/glob.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/flags.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/filters.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/events.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/eventEmitter.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/event.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/errors.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/diagnostics.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/dates.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/comparers.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/collections.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/cancellation.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/callbackList.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/async.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/assert.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/arrays.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/common/actions.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/touch.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/styleMutator.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/mouseEvent.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/keyboardEvent.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/iframe.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/idleMonitor.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/htmlContentRenderer.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/globalMouseMoveMonitor.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/dom.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/dnd.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/builder.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/browserService.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/base/browser/browser.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/node/languageConfiguration.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/xml.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/vb.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/types.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/swift.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/sql.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/ruby.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/r.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/python.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/powershell.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/objective-c.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/lua.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/java.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/jade.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/ini.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/go.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/fsharp.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/dockerfile.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/csharp.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/cpp.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/coffee.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/bat.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/standalone-languages/all.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/platform/platform.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/languages/languages.main.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/editor/editor.main.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/vscode.d.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/nls.d.ts
[03:30:00] [check semantics] /opt/vscode/src/vs/css.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/yauzl.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/winreg.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/windows-mutex.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/weak.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/semver.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/sax.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/require.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/node.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/native-keymap.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/mocha.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/iconv-lite.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/https-proxy-agent.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/http-proxy-agent.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/graceful-fs.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/getmac.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/electron.d.ts
[03:30:00] [check semantics] /opt/vscode/src/typings/applicationInsights.d.ts
[03:30:03] [check semantics*] /opt/vscode/src/typings/mocha.d.ts is an internal module and it has changed shape -> check whatever hasn't been checked yet
[03:30:03] [tsb] time: 30184ms mem: 418MB Δ387
*** Finished with 0 errors.
```

**Comment by Tyriar** [comment]
This was just reported recently https://github.com/Microsoft/vscode/issues/3700, closing in favor of that.

What versions of Ubuntu and VSCode are you on?

**Comment by isomorphisms** [comment]
@Tyriar  Ubuntu 12.04, and `/opt/VSCode-linux-ia32/Code --version` doesn’t tell me anything but I just downloaded it from http://code.visualstudio.com/Docs/?dv=linux32.
