### ISSUE TITLE
Error extracting function in module scope

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37050]
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T05:12:19.123Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
regex|chr|0.1.0
ssh|chr|0.0.2
vscode-eslint|dba|1.4.0
ghlink|dt|0.0.6
tslint|eg2|1.0.13
azure-account|ms-|0.1.3
azurecli|ms-|0.3.0
github-issues-prs|ms-|0.6.0
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
vscode-versionlens|pfl|0.19.1
vscode-open-in-github|sys|1.6.0

---

Steps to Reproduce:

1. Select entire line: https://github.com/Microsoft/vscode-probot/blob/01f79fd069ba6e7d9cb574a89e658ef7a12b6ebd/hubot/src/travis.ts#L229
2. Run "Extract function in module scope".
3. Nothing happens in the UI, but there is an error in the console:

```
Error processing request. Cannot read property 'externalModuleIndicator' of undefined
TypeError: Cannot read property 'externalModuleIndicator' of undefined
    at Object.isExternalModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:12466:20)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21856:101
    at Object.forEachEntry (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2044:26)
    at trySymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21852:27)
    at getAccessibleSymbolChainFromSymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21832:30)
    at forEachSymbolTableInScope (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21817:20)
    at getAccessibleSymbolChain (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21827:20)
    at getSymbolChain (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22543:49)
    at symbolToName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22508:29)
    at typeToTypeNodeHelper (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22154:46)
    at Object.typeToTypeNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22059:41)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77965:44
    at Map.forEach (native)
    at extractFunctionInScope (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77960:31)
    at getFunctionExtractionAtIndex (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77834:24)
    at Object.getEditsForAction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77538:28)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:74989:41)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80201:32)
    at IOSession.Session.getEditsForRefactor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86457:59)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85418:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86645:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86636:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86645:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86665:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87857:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

It works when selecting only the right hand side of the assignment. Couldn't immediate find a simple example to reproduce.

**Comment by mjbvz** [comment]
Posted minimal repo to https://github.com/Microsoft/TypeScript/issues/19395#issuecomment-340117161

Seems to be fixed in typescript@next 

Closing as upstream. Please let me know if you run into any other cases of this
