### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by Flynrod** [Microsoft/vscode#37161]
**- VSCode Version:** LATEST
**- OS Version:** OS X 10.13 (17A405)

Steps to Reproduce:

1. Run ./scripts/npm.sh install
2. Run npm install

`npm install

> code-oss-dev@1.18.0 preinstall /Users/lionel/Documents/Lab/vscode-master
> node build/npm/preinstall.js

You can't use plain npm to install Code's dependencies.
Please run './scripts/npm.sh install' instead.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.18.0 preinstall: `node build/npm/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the code-oss-dev@1.18.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lionel/.npm/_logs/2017-10-30T16_09_10_150Z-debug.log
Mini-de-Lionel:vscode-master lionel$ npm test

> code-oss-dev@1.18.0 test /Users/lionel/Documents/Lab/vscode-master
> mocha

module.js:515
    throw err;
    ^

Error: Cannot find module '../out/vs/loader'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/lionel/Documents/Lab/vscode-master/test/all.js:39:14)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at /Users/lionel/Documents/Lab/vscode-master/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/lionel/Documents/Lab/vscode-master/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/lionel/Documents/Lab/vscode-master/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/lionel/Documents/Lab/vscode-master/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! Test failed.  See above for more details.`
**Reproduces without extensions:** Yes

**Comment by mjbvz** [comment]
What npm version are you using?

**Comment by Flynrod** [comment]
Here's my NodeJS version: v8.8.1

**Comment by mjbvz** [comment]
We don't support npm 5.x currently. Can you try cleaning and reinstalling using npm 4.x

**Comment by Flynrod** [comment]
v4.8.4 is supported ?

**Comment by mjbvz** [comment]
yes. Still running into issues using it?

**Comment by Flynrod** [comment]
Same error
`npm install

> code-oss-dev@1.18.0 preinstall /Users/lionel/Documents/Lab/vscode-master
> node build/npm/preinstall.js

You can't use plain npm to install Code's dependencies.
Please run './scripts/npm.sh install' instead.

npm ERR! Darwin 17.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.18.0 preinstall: `node build/npm/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the code-oss-dev@1.18.0 preinstall script 'node build/npm/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the code-oss-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/npm/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs code-oss-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls code-oss-dev
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lionel/.npm/_logs/2017-10-30T16_57_03_832Z-debug.log`

**Comment by mjbvz** [comment]
Wait, are you running both `./scripts/npm.sh install` and `npm install`? You should only need to run the first. Regular `npm install` is not supported

**Comment by Flynrod** [comment]
So, I should use this one ? ./scripts/npm.sh

**Comment by mjbvz** [comment]
yes that will install everything

**Comment by Flynrod** [comment]
Thanks, it works!
