### ISSUE TITLE
Cannot read property 'saveViewState' of null

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3728]
alpha channel commit 8e63756

Not sure how i got into this state... i have a couple of folders with a couple of markdown files, autoSave is on. I was doing a lot of scrolling in Preview mode of one of the markdown files and as I was scrolling, this error popped:

![image](https://cloud.githubusercontent.com/assets/1487073/13533398/94cf0ca4-e230-11e5-9580-de22ff9bbad9.png)

From the console:

``` bash
Cannot read property 'saveViewState' of null: TypeError: Cannot read property 'saveViewState' of null
    at t.getResults (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:9199)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:17409
    at n.undefined.t.Class.define.then (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:23448)
    at t.handleSpecificHandler (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:16980)
    at t.onType (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:15168)
    at Object.quickOpenWidget.quickOpenWidget.d.QuickOpenWidget.onType (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:13136)
    at e.doShowWithPrefix (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:49:8628)
    at e.show (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:49:8456)
    at t.show (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:13658)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:108:19822e.onUnexpectedError @ shell.ts:480
messageService.ts:147 Cannot read property 'saveViewState' of null: TypeError: Cannot read property 'saveViewState' of null
    at t.getResults (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:9199)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:17409
    at n.undefined.t.Class.define.then (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:23448)
    at t.handleSpecificHandler (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:16980)
    at t.onType (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:15168)
    at Object.quickOpenWidget.quickOpenWidget.d.QuickOpenWidget.onType (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:13136)
    at e.doShowWithPrefix (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:49:8628)
    at e.show (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:49:8456)
    at t.show (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:13658)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:108:19822e.doShow @ messageService.ts:147
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26 [uncaught exception]: TypeError: Cannot convert object to primitive valueonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29 TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (/Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/node_modules/applicationinsights/Library/Client.js:67:25)
    at e.logException (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:30903)
    at e.log (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:112:12590)
    at t.handleEvent (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:30720)
    at t.e.publicLog (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:27905)
    at t.publicLog (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:504)
    at t.e.flushErrorBuffer (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:25914)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:25774onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29
/Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/node_modules/applicationinsight…:67 Uncaught TypeError: Cannot convert object to primitive value
/Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/node_modules/applicationinsight…:19 ApplicationInsights:Sender [Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:80
    at err…]
```

**Comment by isidorn** [comment]
I see some uses of `editor.getControl() .saveViewState` without first checking if `control !== null`

**Comment by bpasero** [comment]
Could reproduce when opening "Problems and Warnings" when having markdown preview open.

**Comment by chrisdias** [comment]
verified best i could... i did alot of markdown previewing and scrolling... no issues.
