### ISSUE TITLE
Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode#37316]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.0.3
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|5.7.1
tslint|eg2|1.0.14
vscode-abap|lar|0.1.0
Go|luk|0.6.66
postscript|max|1.0.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
vscode-icons|rob|7.17.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
html-preview-vscode|tht|0.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

No idea, sorry. Just programming Go and React for a while and it appears in the console.

```

Cannot read property '_id' of undefined: TypeError: Cannot read property '_id' of undefined
	at c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:438761
	at Object.g [as _notify] (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:65284)
	at Object.enter (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:68849)
	at n.Class.derive._oncancel._run (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:70677)
	at n.Class.derive._oncancel._completed (c:\Programme\VSCodeInsider\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:70118)
	at <anonymous>
e.onUnexpectedError @ shell.ts:459
```

**Comment by octref** [comment]
Seems to be an error thrown from extensionHostProcess, so passing to @jrieken.
