### ISSUE TITLE
doesn’t run on Ubuntu 12.04

### ISSUE THREAD

**Issue by isomorphisms** [Microsoft/vscode#3737]
```
/opt/VSCode-linux-ia32$ ./Code
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/opt/VSCode-linux-ia32/resources/atom.asar/browser/lib/init.js:120:7)
    at Object.<anonymous> (/opt/VSCode-linux-ia32/resources/atom.asar/browser/lib/init.js:132:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:130:18)
    at node.js:982:3

```

**Comment by isomorphisms** [comment]
oops, duplicate
