### ISSUE TITLE
Cannot read property '_setProcessId' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37501]
Found this in my insiders selfhost console today, not sure how to reproduce:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property '_setProcessId' of null: TypeError: Cannot read property '_setProcessId' of null
	at e.$acceptTerminalProcessId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:478042)
	at t.e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:509390)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354777)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354467)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353494
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355413
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:85151
	at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84434)
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86156)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:144165)
```

**Comment by bpasero** [comment]
Saw it now also when running out of sources:

```
shell.js:265 Cannot read property '_setProcessId' of null: TypeError: Cannot read property '_setProcessId' of null
	at ExtHostTerminalService.$acceptTerminalProcessId (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostTerminalService.js:114:21)
	at ExtHostThreadService.AbstractThreadService.invoke (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/thread/node/abstractThreadService.js:29:27)
	at RPCProtocol._invokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:81:66)
	at RPCProtocol._receiveOneMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:70:47)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:16:92
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:118:21
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:366:70
	at CallbackList.invoke (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:35:39)
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
	at Socket.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
```

**Comment by Tyriar** [comment]
I can't seem to repro on the actual Insiders but I can reproduce in the OSS build/Linux with:

1. ctrl+p
2. "term "
3. Select create new integrated terminal

As for why it's happening I'm not sure right now. I wouldn't think this code would be hit unless there is an extension using the terminal API :confused:

**Comment by Tyriar** [comment]
After taking a look, the only explanation I have for this is if it was always happening and logging was recently changed for the ext host to be exposed in the console. When a terminal is created it will send over the process ID to the ext host to send to that side if it was created via the ext host.
