### ISSUE TITLE
Error: IRequestService.makeRequest: Url is required.

### ISSUE THREAD

**Issue by 1dot75cm** [Microsoft/vscode#3753]
I try to build test the latest release. It return following error. This looks like a function call error. 

RPM spec: http://copr-dist-git.fedorainfracloud.org/cgit/mosquito/test/vscode.git/tree/vscode.spec?id=c1799988130b6ebb5b1db42b1582d626f6ee7a12

```
Version 0.10.10
Commit 97d4ad1c55a82369f65078406ed770e8a34055fc
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
$ dnf install https://copr-be.cloud.fedoraproject.org/results/mosquito/test/fedora-23-x86_64/00166088-vscode/vscode-0.10.10-1.fc23.x86_64.rpm
$ export ELECTRON_ENABLE_LOGGING=1
$ export ELECTRON_ENABLE_STACK_DUMPING=1
$ /usr/lib64/vscode/vscode
[21099:0306/203333:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[20877:0306/203336:INFO:CONSOLE(133360)] "IRequestService.makeRequest: Url is required.: Error: IRequestService.makeRequest: Url is required.
    at RequestService.makeRequest (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:137627:23)
    at GalleryService.queryCache (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:121102:40)
    at GalleryService.query (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:121057:30)
    at ExtensionTipsService._getAvailableExtensions (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:92773:41)
    at ExtensionTipsService._init (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:92735:46)
    at new ExtensionTipsService (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:92705:18)
    at create (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:5252:14)
    at file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:61565:45
    at AccessLock.runUnlocked (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:61393:24)
    at ServicesMap.createInstance (file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js:61564:31)", source: file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js (133360)
[20877:0306/203336:INFO:CONSOLE(26)] "[uncaught exception]: Error: IRequestService.makeRequest: Url is required.", source: file:///usr/lib64/vscode/resources/app/out/vs/workbench/electron-browser/index.html?config={"pathArguments":[],"programStart":0,"workers":-1,"enablePerformance":false,"verboseLogging":false,"logPluginHostCommunication":false,"firstrun":false,"openNewWindow":false,"openInSameWindow":false,"gotoLineMode":false,"disablePlugins":false,"execPath":"/usr/lib64/vscode/vscode","appName":"Visual Studio Code","darwinBundleIdentifier":"com.microsoft.VSCode","appRoot":"/usr/lib64/vscode/resources  ..................
[20877:0306/203336:INFO:CONSOLE(109401)] "%c[Plugin Host]", source: file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js (109401)
[20877:0306/203336:INFO:CONSOLE(109401)] "%c[Plugin Host]", source: file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js (109401)
[20877:0306/203336:INFO:CONSOLE(109401)] "%c[Plugin Host]", source: file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js (109401)
[20877:0306/203336:INFO:CONSOLE(109401)] "%c[Plugin Host]", source: file:////usr/lib64/vscode/resources/app/out/vs/workbench/workbench.main.js (109401)
.............
```

**Comment by joaomoreno** [comment]
This code changed recently, can you try again?

`rpm` is not supported by us yet, btw.

**Comment by 1dot75cm** [comment]
I remove follows content from product.json. It work fine. Where can I find the manual for these parameters?

```
"extensionsGallery": {
	"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
	"itemUrl": "https://marketplace.visualstudio.com/items"
},
```

**Comment by joaomoreno** [comment]
Yeah, it's missing the `cacheUrl`.

Two fixes here:
- you can add `"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index"` to that object;
- I pushed 0ef0a43 which fixes the exception in your log, in case `cacheUrl` is missing.

**Comment by 1dot75cm** [comment]
:+1:  Yes, fixed it. Thanks.
I just saw [src/vs/workbench/electron-main/env.ts](https://github.com/Microsoft/vscode/blob/7e89b382ef30a81fef73c93065a3d9d71d123b54/src/vs/workbench/electron-main/env.ts) file.
