### ISSUE TITLE
build a win32-x64 or win32-ia32 package from source code failed

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#37575]
- VSCode Version: 1.16.0
- OS Version: window 7 professional sp1
- node: 7.4.0
- npm: 4.0.5

Steps to Reproduce:
1. scripts\npm.bat install --------success
2. npm run watch            --------success
3. .\scripts\code.bat        --------success, and the vscode show up
4. gulp vscode-win32-ia32 or  vscode-win32-x64   ------seems ok, but can't run the exe file

After the 4th step finished, I got a directory "VSCode-win32-ia32". 
"Code - OSS.exe"  is in the dir. Everything seems to be ok now.

**Comment by joaomoreno** [comment]
Not sure what happens... If you run that exe from a command prompt, any interesting output comes out?

**Comment by chongchai** [comment]
@joaomoreno 

the error is here. Seems the electron can't get the path after the package. 

```
D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64>"Code - OSS.exe"

D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64>
The factory method of "vs/code/electron-main/main" has thrown an exception
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at EnvironmentService.get (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x
64\resources\app\out\vs\code\electron-main\main.js:13269:59)
    at EnvironmentService.descriptor.(anonymous function) [as nodeCachedDataDir]
 (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\out\vs\code\
electron-main\main.js:505:31)
    at createPaths (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resource
s\app\out\vs\code\electron-main\main.js:21098:31)
    at D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\out\vs\
code\electron-main\main.js:21223:78
    at InstantiationService.invokeFunction (D:\github\vscode-src\vscode-1.16.0\V
SCode-win32-x64\resources\app\out\vs\code\electron-main\main.js:12552:34)
    at D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\out\vs\
code\electron-main\main.js:21223:41
    at InstantiationService.invokeFunction (D:\github\vscode-src\vscode-1.16.0\V
SCode-win32-x64\resources\app\out\vs\code\electron-main\main.js:12552:34)
    at main (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\o
ut\vs\code\electron-main\main.js:21213:37)
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at EnvironmentService.get (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x
64\resources\app\out\vs\code\electron-main\main.js:13269:59)
    at EnvironmentService.descriptor.(anonymous function) [as nodeCachedDataDir]
 (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\out\vs\code\
electron-main\main.js:505:31)
    at createPaths (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resource
s\app\out\vs\code\electron-main\main.js:21098:31)
    at D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\out\vs\
code\electron-main\main.js:21223:78
    at InstantiationService.invokeFunction (D:\github\vscode-src\vscode-1.16.0\V
SCode-win32-x64\resources\app\out\vs\code\electron-main\main.js:12552:34)
    at D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\out\vs\
code\electron-main\main.js:21223:41
    at InstantiationService.invokeFunction (D:\github\vscode-src\vscode-1.16.0\V
SCode-win32-x64\resources\app\out\vs\code\electron-main\main.js:12552:34)
    at main (D:\github\vscode-src\vscode-1.16.0\VSCode-win32-x64\resources\app\o
ut\vs\code\electron-main\main.js:21213:37)
```

**Comment by chongchai** [comment]
I find the error. 
in file _resources\app\out\vs\code\electron-main\main.js:13269_
`return this.isBuilt ? path.join(this.userDataPath, 'CachedData', product_1.default.commit) : undefined; `

The `product_1.detail.commit` is undefined, since the default product.json doesn't contain a commit key. 
 I add a commit key to this json file, then code-oss starts successfully.

Thanks for your help! 
Maybe this undefined problem can be added in the [https://github.com/Microsoft/vscode/wiki/How-to-Contribute#packaging](url) or dealt in the source code.

**Comment by joaomoreno** [comment]
cc @jrieken for the `CachedData` problem again.
