### ISSUE TITLE
All status bar smoke tests failed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37603]
```
12) Statusbar verifies presence of all default status bar elements:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:110:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitForElement (out/spectron/client.js:109:16)
      at StatusBar.<anonymous> (out/areas/statusbar/statusbar.js:36:40)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.js:7:12)
      at StatusBar.waitForStatusbarElement (out/areas/statusbar/statusbar.js:35:16)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:25:43)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.test.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.test.js:7:12)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:23:16)

  13) Statusbar verifies that 'quick open' opens when clicking on status bar elements:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:64:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitAndClick (out/spectron/client.js:63:16)
      at StatusBar.<anonymous> (out/areas/statusbar/statusbar.js:41:40)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.js:7:12)
      at StatusBar.clickOn (out/areas/statusbar/statusbar.js:40:16)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:42:43)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.test.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.test.js:7:12)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:40:16)

  14) Statusbar verifies that 'Problems View' appears when clicking on 'Problems' status element:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:64:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitAndClick (out/spectron/client.js:63:16)
      at StatusBar.<anonymous> (out/areas/statusbar/statusbar.js:41:40)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.js:7:12)
      at StatusBar.clickOn (out/areas/statusbar/statusbar.js:40:16)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:63:43)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.test.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.test.js:7:12)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:61:16)

  15) Statusbar verifies that 'Tweet us feedback' pop-up appears when clicking on 'Feedback' icon:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:64:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitAndClick (out/spectron/client.js:63:16)
      at StatusBar.<anonymous> (out/areas/statusbar/statusbar.js:41:40)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.js:7:12)
      at StatusBar.clickOn (out/areas/statusbar/statusbar.js:40:16)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:73:43)
      at Generator.next (<anonymous>)
      at out/areas/statusbar/statusbar.test.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/statusbar/statusbar.test.js:7:12)
      at Context.<anonymous> (out/areas/statusbar/statusbar.test.js:68:16)

  16) Statusbar checks if 'Go to Line' works if called from the status bar:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:127:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitForActiveElement (out/spectron/client.js:126:16)
      at QuickOpen.<anonymous> (out/areas/quickopen/quickopen.js:54:40)
      at Generator.next (<anonymous>)
      at out/areas/quickopen/quickopen.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/quickopen/quickopen.js:7:12)
      at QuickOpen.waitForQuickOpenOpened (out/areas/quickopen/quickopen.js:53:16)
      at QuickOpen.<anonymous> (out/areas/quickopen/quickopen.js:22:24)
      at Generator.next (<anonymous>)
      at fulfilled (out/areas/quickopen/quickopen.js:8:58)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  17) Statusbar verifies if changing EOL is reflected in the status bar:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:127:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitForActiveElement (out/spectron/client.js:126:16)
      at QuickOpen.<anonymous> (out/areas/quickopen/quickopen.js:54:40)
      at Generator.next (<anonymous>)
      at out/areas/quickopen/quickopen.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/quickopen/quickopen.js:7:12)
      at QuickOpen.waitForQuickOpenOpened (out/areas/quickopen/quickopen.js:53:16)
      at QuickOpen.<anonymous> (out/areas/quickopen/quickopen.js:22:24)
      at Generator.next (<anonymous>)
      at fulfilled (out/areas/quickopen/quickopen.js:8:58)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```

**Comment by bpasero** [comment]
@joaomoreno @sandy081 any clue what `Not allowed to run nested waitFor calls` means?

**Comment by sandy081** [comment]
I am not able to reproduce it. But I know when this message is shown `Not allowed to run nested waitFor call`. Will see.

**Comment by joaomoreno** [comment]
`waitFor` is our global hammer for waiting on stuff. Since it has a fixed value for waiting for stuff, if you nest calls of `waitFor` then that time will grow quadratically (eg `waitFor(() => waitFor(() => ...))`. So we forbid nesting them, in order to keep the time waiting for stuff at a minimum.

The only way this could've happened is if [this](https://github.com/Microsoft/vscode/blob/master/test/smoke/src/spectron/client.ts#L177) never returns, thus causing mocha to bail out with a timeout and continue running tests. The very next time `waitFor` is called, it will fail.

So... unfortunately these tests may as well have passed. They only failed because the test suite right before it failed with a timeout. The bug is in that suite.

One fix for `waitFor` is to maybe set [`running`](https://github.com/Microsoft/vscode/blob/master/test/smoke/src/spectron/client.ts#L156) to `false` before every single test runs.

I can take this.
