### ISSUE TITLE
Debug smoke test failures

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37604]
```
  4) Debug start debugging:
     Error: undefined: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:183:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>

  5) Debug focus stack frames and variables:
     Error: Waiting for Stack Frame: looking for layer.js: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:183:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>

  6) Debug stepOver, stepIn, stepOut:
     Error: Waiting for Stack Frame: looking for response.js: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:183:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>

  7) Debug continue:
     Error: connect ECONNREFUSED 127.0.0.1:80
      at Object._errnoException (util.js:1024:11)
      at _exceptionWithHostPort (util.js:1046:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

  8) Debug debug console:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:127:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitForActiveElement (out/spectron/client.js:126:16)
      at QuickOpen.<anonymous> (out/areas/quickopen/quickopen.js:54:40)
      at Generator.next (<anonymous>)
      at out/areas/quickopen/quickopen.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/quickopen/quickopen.js:7:12)
      at QuickOpen.waitForQuickOpenOpened (out/areas/quickopen/quickopen.js:53:16)
      at QuickOpen.<anonymous> (out/areas/quickopen/quickopen.js:22:24)
      at Generator.next (<anonymous>)
      at fulfilled (out/areas/quickopen/quickopen.js:8:58)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  9) Debug stop debugging:
     Error: Not allowed to run nested waitFor calls!
      at SpectronClient.<anonymous> (out/spectron/client.js:174:23)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitFor (out/spectron/client.js:172:16)
      at SpectronClient.<anonymous> (out/spectron/client.js:64:25)
      at Generator.next (<anonymous>)
      at out/spectron/client.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/spectron/client.js:7:12)
      at SpectronClient.waitAndClick (out/spectron/client.js:63:16)
      at Debug.<anonymous> (out/areas/debug/debug.js:97:40)
      at Generator.next (<anonymous>)
      at out/areas/debug/debug.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/debug/debug.js:7:12)
      at Debug.stopDebugging (out/areas/debug/debug.js:96:16)
      at Context.<anonymous> (out/areas/debug/debug.test.js:140:39)
      at Generator.next (<anonymous>)
      at out/areas/debug/debug.test.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/areas/debug/debug.test.js:7:12)
      at Context.<anonymous> (out/areas/debug/debug.test.js:138:16)
```

**Comment by isidorn** [comment]
This is just the usual unreliabnes of the smoke test I believe.
Closing as there is nothing specific that I can do for the debug tests (since they always pass for me)

fyi @joaomoreno

**Comment by joaomoreno** [comment]
Did you check the screenshots?

**Comment by isidorn** [comment]
@joaomoreno good point.
@jrieken could you please attach the screenshots?
