### ISSUE TITLE
Smoke test: Git tests are failing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37600]
Maybe related to decorations (@jrieken fyi). I ran them on Linux:

![image](https://user-images.githubusercontent.com/900690/32376285-9e74b4e4-c0a4-11e7-8c99-9e31989181f2.png)

**Comment by jrieken** [comment]
Postponing. This is how far I get when running the smoke-test locally

```
ieken:~/Code/vscode$ npm run smoketest

> code-oss-dev@1.19.0 smoketest /Users/jrieken/Code/vscode
> cd test/smoke && mocha



*** Test data: /var/folders/jh/nmq5w60n2vn_491r573nf0fr0000gn/T/t526477u4UM23h5PH6
*** Preparing smoketest setup...
*** Fetching keybindings...
*** Creating workspace file...
*** Cloning test project repository...
*** Running npm install...
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
added 198 packages in 3.677s
*** Smoketest setup done!

  1) "before all" hook
  2) "after all" hook

  0 passing (31s)
  2 failing

  1)  "before all" hook:
     Error: getHTML with selector [id="workbench.main.container"]: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:183:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>

  2)  "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at Context.<anonymous> (out/main.js:215:24)
      at Generator.next (<anonymous>)
      at out/main.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out/main.js:7:12)
      at Context.<anonymous> (out/main.js:214:12)
```

**Comment by jrieken** [comment]
Likely, this needs changes

```ts
const name = element.querySelector('.label-name') as HTMLElement;
				const icon = element.querySelector('.monaco-icon-label') as HTMLElement;
				const actionElementList = element.querySelectorAll('.actions .action-label');
				
```

**Comment by jrieken** [comment]
Closing... Apparently it did run a few days ago, on some machine surely not on mine which still shows above error
