### ISSUE TITLE
Search smoke test failures

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37602]
```
 1) Search searches for body & checks for correct result number:
     Error: getText with selector div[id="workbench.view.search"] .search-viewlet .messages[aria-hidden="false"] .message>p: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:183:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>

  2) Search dismisses result & checks for correct result number:
     Error: getText with selector div[id="workbench.view.search"] .search-viewlet .messages[aria-hidden="false"] .message>p: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:183:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>

  3) Search replaces first search result with a replace term:
     Error: getText with selector div[id="workbench.view.search"] .search-viewlet .messages[aria-hidden="false"] .message>p: Timed out after 20 seconds.
      at SpectronClient.<anonymous> (out/spectron/client.js:183:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/spectron/client.js:8:58)
      at <anonymous>
```

**Comment by roblourens** [comment]
Passed locally for me, was this a local run or are there logs/screenshots somewhere?
