### ISSUE TITLE
Blank editor afetr update to 1.19.0-insider in Ubuntu 16.04

### ISSUE THREAD

**Issue by Mofiqul** [Microsoft/vscode#37703]
I am getting blank editor after updating this evening. 
- VSCode Version: 1.19.0-insider
--
- OS Version: Ubuntu 16.04 amd-64 bit

**Comment by daanhorn** [comment]
Same here on Ubuntu Mate 17.10

**Comment by CarlosAzocar** [comment]
Same here on Debian 8

**Comment by jtsom** [comment]
Same here. Ubuntu Mate 17.10. It looks like the page is scrolled to the last line, but I can't scroll up to see the text.

**Comment by jtsom** [comment]
More info. Developer tools console is full of this error:
```
charCode is not defined: ReferenceError: charCode is not defined
    at o (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:530695)
    at Object.s [as renderViewLine] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:531359)
    at e.renderLine (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1491408)
    at e._finishRendering (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:400302)
    at e.render (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:398052)
    at e.renderLines (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:397467)
    at t.renderText (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1538123)
    at t._actualRender (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1641210)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1640476
    at z (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1633012)
```

**Comment by stefanmaric** [comment]
Experiencing the same on Ubuntu Gnome 17.10.

```
Version 1.19.0-insider
Commit 432b53bc3a263fda8db6ecca83d1ce89ede04bf2
Date 2017-11-06T06:22:36.757Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by brunocasado** [comment]
same here

**Comment by stefanmaric** [comment]
Just noticed this is a duplicated of #37698.

**Comment by jtsom** [comment]
Any chance this is going to get any comment or fix soon? The app is pretty much broken.

**Comment by stefanmaric** [comment]
> Any chance this is going to get any comment or fix soon? The app is pretty much broken.

You can downgrade to latest 1.18 in the meantime:

```
sudo apt install code-insiders=1.18.0-1509770825
```

**Comment by Mofiqul** [comment]
I have downgrade to 1.18. Is this issue only in Linux?

**Comment by stefanmaric** [comment]
> Is this issue only in Linux?

The error doesn't look like something platform specific, but haven't seen Windows or Mac users complaining.

**Comment by jtsom** [comment]
My windows and Mac systems don't have the 1.19-insiders available yet, so it's hard to test. The Linux builds generally get the new insiders (when versions change) a couple days before Win and Mac (for whatever magical reason.)

**Comment by bpasero** [comment]
Lets continue here: https://github.com/Microsoft/vscode/issues/37698
