### ISSUE TITLE
Unable to view files in newest insiders build

### ISSUE THREAD

**Issue by pwicks86** [Microsoft/vscode#37732]
- VSCode Version: Code - Insiders 1.19.0-insider (432b53bc3a263fda8db6ecca83d1ce89ede04bf2, 2017-11-06T06:22:36.757Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.2
python|don|0.7.0
gitlens|eam|5.7.1
cpptools|ms-|0.14.0
vetur|oct|0.11.0
vim|vsc|0.10.2

---

Steps to Reproduce:

1. Open any file
2. The text view is blank.

Reproduces without extensions: Yes

It also is a problem in both normal and multi-root workspaces.

The following shows up in the dev tools console:

```
shell.ts:459 charCode is not defined: ReferenceError: charCode is not defined
    at o (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:530695)
    at Object.s [as renderViewLine] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:531359)
    at e.renderLine (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1491408)
    at e._finishRendering (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:400302)
    at e.render (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:398052)
    at e.renderLines (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:397467)
    at t.renderText (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1538123)
    at t._actualRender (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1641210)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1640476
    at z (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9:1633012)
```

**Comment by pwicks86** [comment]
Oops, looks like this is also a duplicate of #37703
