### ISSUE TITLE
Win Server Core: open file dialog crashes

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/vscode#37850]
- VSCode Version: any
- OS Version:  Windows ServerCore 

Steps to Reproduce:

1. get vscode to server core  (probably via chromium
2. install.
3. open vscode and select a file. 
Boom.

If you specify the file via the command line, it will open nicely and it appears to be debuggable from there.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@yakman2020 can you share a video or screenshot what happens?

**Comment by donid** [comment]
I just experienced the same problem while I tried the "Install from VSIX" menu which opens a "Select file", too. 
I typed "code.exe" in the command line, the vscode window appears and there are several "Visual Studio Code" processes visible in Task Manager. Then I choose "Install from VSIX" and the VSCode Window disappears immediately and so do all "Visual Studio Code"  processes in Task Manager (one instance takes a little longer to disappear). The command line from which I started vscode stays busy (locked) until I hit ctrl+C.

**Comment by donid** [comment]
Is still more info needed, or is the "needs more info" tag now obsolete?

**Comment by bpasero** [comment]
Yeah, for example a crash dump would help or a video how this all crashes (as asked).

**Comment by donid** [comment]
@bpasero : I could not find a crash dump or an entry in the event log, but I did some more experiments:
My statement that the command line is locked after vscode has disappeared is wrong, It just doesn't show the prompt message, but you can type and execute new commands.
The described behavior happens (unsurprisingly) for all menus that show a file open/save or folder-browser dialog (File / Save As, Open Folder, Open Workspace)

Here is a screenshot before I click "Install from VSIX"
![image](https://user-images.githubusercontent.com/6991562/33598257-5708c6e2-d9a2-11e7-9708-f20bff1123a3.png)

After the click, the menu disappears and then the vscode window disappears (all within approx. 1sec) and the screen looks like this (I have done the test three times to created the snapshots):
![image](https://user-images.githubusercontent.com/6991562/33598635-cf7a79f8-d9a3-11e7-939a-473d91c4dcde.png)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by donid** [comment]
Since vscode also disappears when I use "save as" in the developer tools **console**, I had to copy the **console** content where selecting text is a bit awkward:

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Error: Git installation not found.
	at first.then.then (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\git.js:94:42)
	at <anonymous>
	at runMicrotasksCallback (internal/process/next_tick.js:64:5)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9) (at init.catch.err (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\main.js:63:31))
﻿
(Only) one time when choosing "save as" in the **console** the "vscode has stopped working" dialog appeared and in the **command prompt** window was this text:

WARNING: Promise with no error callback:6
{ exception:
   Error: net::ERR_CONNECTION_TIMED_OUT
       at Menu.popup (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\menu.js:180:8)
       at callFunction (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:249:18)
       at EventEmitter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:357:5)
       at emitMany (events.js:127:13)
       at EventEmitter.emit (events.js:204:7)
       at WebContents.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:256:13)
       at emitTwo (events.js:106:13)
       at WebContents.emit (events.js:194:7),
  error: null,
  promise:
   { _creator: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: g],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value:
      Error: net::ERR_CONNECTION_TIMED_OUT
          at Menu.popup (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\menu.js:180:8)
          at callFunction (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:249:18)
          at EventEmitter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:357:5)
          at emitMany (events.js:127:13)
          at EventEmitter.emit (events.js:204:7)
          at WebContents.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:256:13)
          at emitTwo (events.js:106:13)
          at WebContents.emit (events.js:194:7),
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_CONNECTION_TIMED_OUT
    at Menu.popup (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\menu.js:180:8)
    at callFunction (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:249:18)
    at EventEmitter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
[1196:1205/122438.188:ERROR:CONSOLE(234)] "Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: net::ERR_CONNECTION_TIMED_OUT

Error: net::ERR_CONNECTION_TIMED_OUT
    at Menu.popup (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\menu.js:180:8)
    at callFunction (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:249:18)
    at EventEmitter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: net::ERR_CONNECTION_TIMED_OUT

Error: net::ERR_CONNECTION_TIMED_OUT
    at Menu.popup (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\menu.js:180:8)
    at callFunction (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:249:18)
    at EventEmitter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at callFunction (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (c:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)", source: c:\Program Files\Microsoft VS Code\resources\electron.asar\renderer\api\remote.js (234)


And finally here is the content of the **command prompt** window when I clicked "Install from VSIX" and vscode had disappeared:
c:\Program Files\Microsoft VS Code>code --verbose

c:\Program Files\Microsoft VS Code>
[main 12:22:13 PM] Starting VS Code in verbose mode
[main 12:22:13 PM] from: c:\Program Files\Microsoft VS Code\resources\app
[main 12:22:13 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false }
[main 12:22:13 PM] Unable to read folders in C:\Users\Administrator\AppData\Roaming\Code\Workspaces (Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\AppData\Roaming\Code\Workspaces').
[main 12:22:14 PM] IPC#vscode-machineId
[main 12:22:15 PM] IPC#vscode-workbenchLoaded

**Comment by bpasero** [comment]
I fear it is something down in the OS level or Electron that goes wrong. It could be that we are just not supporting Windows Server Core yet as OS.

**Comment by carlosrpcaldas** [comment]
Will it be supported anytime soon? Any workarounds?
Just installed latest version 1.26.1, same issue.

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by bpasero** [comment]
I am closing this, we are not officially supporting the OS "Windows Server Core". Based on https://docs.microsoft.com/en-us/windows-server/administration/server-core/what-is-server-core it reads specifically that:

> In other words, there is no desktop in Server Core, by design. While maintaining the capabilities required to support traditional business applications and role-based workloads, Server Core does not have a traditional desktop interface. Instead, Server Core is designed to be managed remotely through the command line, PowerShell, or a GUI tool (like RSAT or Windows Admin Center).
