### ISSUE TITLE
Sidebar explodes when contribution is removed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#38213]
To explore more lazy loading I have removed eager loading of `debug.contribution.ts`. The sidebar doesn't approve...

```
index.js:46 TypeError: Cannot read property 'id' of undefined
    at ViewletActivityAction.ActivityAction [as constructor] (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/compositebar/compositeBarActions.js:30:52)
    at new ViewletActivityAction (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/activitybar/activitybarActions.js:30:32)
    at create (file:///Users/jrieken/Code/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:106:43)
    at InstantiationService.createInstance (file:///Users/jrieken/Code/vscode/out/vs/platform/instantiation/common/instantiationService.js:67:29)
    at Object.getActivityAction (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/activitybar/activitybarPart.js:42:95)
    at CompositeBar.toAction (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/compositebar/compositeBar.js:244:56)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/compositebar/compositeBar.js:192:60
    at Array.map (native)
    at CompositeBar.updateCompositeSwitcher (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/compositebar/compositeBar.js:192:18)
```

**Comment by isidorn** [comment]
@jrieken this is happening because the sidebar is on startup measuring how large each item is. In your previous session you had a `debug` viewlet shown which is stored in your storage service.
I can fix this by failing more gracefully, and you can as a workaround clear this storage key and everything should be fine
`workbench.activity.pinnedViewlets`

**Comment by isidorn** [comment]
After inspecting this futher the activitybar is depending on the viewlets being registered so it can render their icons in the activity bar.
I think this makes sense.

So either:
* we also postpone the layouting of the activity bar
* debug in advance registers the viewlet and does the rest lazily

@jrieken let me know what you think

**Comment by jrieken** [comment]
All makes sense but the question why it explodes when a viewlet is there anymore (as in removed from our source code). I smells like some memento state is trusted without validation
