### ISSUE TITLE
User Settings editor tab crashes when re-opening editor (no-provider error)

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#38267]
- VSCode Version: code-oss-dev 1.19.0 (Built from 0790dd3f866eb2943f0916062b739f2d66abaa89)
- OS Version: Darwin x64 17.2.0
- Extensions: none
---

Steps to Reproduce:

1. Have welcome page or user settings open
2. Hot exit the editor 
3. Re-open the editor 
4. Get this error message:

```js
index.js:46 ENOPRO: no provider for vscode://defaultsettings/0/settings.json
    at file:///Users/ggilmore/mess/vscode/out/vs/workbench/services/files/electron-browser/remoteFileService.js:112:31
    at Object.notifySuccess [as _notify] (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.derive._creator._run (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.derive._creator._completed (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at Object.notifySuccess [as _notify] (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (file:///Users/ggilmore/mess/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at LazyPromise.resolveOk (file:///Users/ggilmore/mess/vscode/out/vs/workbench/services/extensions/node/lazyPromise.js:43:22)
onError @ index.js:46
```

I suspect there is some sort of race condition going on.

**Comment by roblourens** [comment]
I see this too

**Comment by jrieken** [comment]
From some reason they are a TextFileEditorModel 

<img width="1007" alt="screen shot 2017-11-14 at 08 26 06" src="https://user-images.githubusercontent.com/1794099/32767845-7b7ffd8a-c915-11e7-835f-62349ab2d04e.png">

**Comment by bpasero** [comment]
@jrieken looks like a race condition between the [`preferencesContribution#start()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/common/preferencesContribution.ts#L110) method and the editor wanting to open the preferences. 

I adopted the `LifecyclePhase.Starting` for all workbench contributions and it looks like the change here is that `LifecycleService.when()` executes with a `timeout(0)` where before it executed sync. We should ensure that the starting phase executes without timeout.

**Comment by sandy081** [comment]
@bpasero This is also happening for Welcome page

**Comment by jrieken** [comment]
> it looks like the change here is that LifecycleService.when() executes with a timeout(0)

Where? I didn't change anything since adding that method.

**Comment by bpasero** [comment]
@jrieken nevermind, fix pushed.
