### ISSUE TITLE
"Start without debugging" throws an error

### ISSUE THREAD

**Issue by peppy** [Microsoft/vscode#38466]
- VSCode Version: Code - Insiders 1.19.0-insider (3a7d517f65212de615f469587c2ace53275ce96e, 2017-11-15T06:11:00.322Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.1
EditorConfig|Edi|0.11.1
code-settings-sync|Sha|2.8.5
gitlens|eam|6.1.0
file-icons|fil|1.0.7
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.4
docomment|k--|0.0.17
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
snippet-creator|nik|0.0.4
subtle-brackets|raf|2.0.2
spellchecker|swy|1.2.13
ayu|tea|0.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Debug > Start Without Debugging
2. Error is thrown

```
Cannot add property noDebug, object is not extensible: TypeError: Cannot add property noDebug, object is not extensible
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3781:817
    at n.Class.derive._oncancel.then (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:141:984)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3781:37
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:135:449)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:138:778)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:140:573)
    at n.Class.derive._oncancel._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:140:14)
    at l (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:143:460)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:143:674)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:135:449)
```

Reproduces without extensions: Yes

**Comment by weinand** [comment]
@isidorn the problem is independent from any debug extension and occurs because the launch configuration is now frozen, so it is no longer possible to add properties on the fly.

**Comment by isidorn** [comment]
@weinand what do you mean by frozen? What changed in this area recently?

**Comment by weinand** [comment]
@jrieken or @sandy081 mentioned that is the standup

**Comment by jrieken** [comment]
@weinand  is correct. For performance reasons the configuration service doesn't clone configuration anymore (before handing them out to consumers). Instead config-objects are frozen and need to be cloned (which is expensive btw) manually if manipulation is desired.

**Comment by isidorn** [comment]
@jrieken thanks for clarification.

**Comment by sandy081** [comment]
Right, configuration object is frozen now for performance reasons. 

I made a complete pass of usages of configuration object to check if cloning has to be done on the consumer side. One more miss here unfortunately.

**Comment by isidorn** [comment]
@sandy081 no worries, I shuold have paid more attention in the standup yesterday 😊
I will fix it now

**Comment by peppy** [comment]
Thanks for the quick fix!
