### ISSUE TITLE
yarn doesn't always install dependencies

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#38549]
- VSCode Version: 1.19-Insider
- OS Version: macOS

Node: 8.9.1
yarn: 0.16.0

Followed steps in https://github.com/Microsoft/vscode/pull/38481
* `nvm install 8.9.1`
* `npm i -g yarn `
* `git clean -xfd`
* `yarn`

Most of the time I got errors when installing vscode-ripgrep

```
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[8/16] ⠐ v8-profiler: CXX(target) Release/obj.target/profiler/src/profiler.o
[9/16] ⠐ vscode-fsevents: spawn args   '-Goutput_dir=.' ]
[10/16] ⠐ vscode-ripgrep
[4/16] ⠐ native-keymap: CXX(target) Release/obj.target/keymapping/src/keyboard_mac.o
error /Users/penlv/code/vscode/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: sh
Arguments: -c node ./dist/postinstall.js
Directory: /Users/penlv/code/vscode/node_modules/vscode-ripgrep
Output:
Downloading ripgrep failed: Error: Missing ./_node_modules...
```

I succeed installing all the packages twice, after that, I ran `yarn watch` or `gulp watch`, I got following errors 

```
yarn watch v0.16.0
$ gulp watch --max_old_space_size=4096
[11:47:44] Node flags detected: --max_old_space_size=4096
[11:47:44] Respawned to PID: 3858
child_process.js:644
    throw err;
    ^

Error: Command failed: yarn list --json
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at getYarnProductionDependencies (/Users/penlv/code/vscode/build/dependencies.js:46:17)
    at Object.getProductionDependencies (/Users/penlv/code/vscode/build/dependencies.js:62:15)
    at Object.<anonymous> (/Users/penlv/code/vscode/build/gulpfile.vscode.js:38:37)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at require.sync.forEach.f (/Users/penlv/code/vscode/gulpfile.js:76:17)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/penlv/code/vscode/gulpfile.js:76:4)
    at Module._compile (module.js:635:30)
```

**Comment by rebornix** [comment]
`vscode-ripgrep` tries to check `node_modules` in `postinstall`, which doesn't exist when doing `yarn install`.

**Comment by rebornix** [comment]
Yarn's cache leads to this problem

* `yarn cache clean`
* `yarn add vscode-ripgrep`
* vscode-ripgrep has a folder `_node_modules`, it has a postscript which will remove this folder and add a new folder called `bin`
* if we run `yarn add vscode-ripgrep` again, yarn will load the module directly from cache (which has the `bin` folder instead of `_node_modules`) and try to execute postscript again.

**Comment by rebornix** [comment]
Besides, it only happens on an old version of yarn, upgrading to the latest one solves the problem.

**Comment by roblourens** [comment]
Should be fixed now

**Comment by joaomoreno** [comment]
Great job guys!
