### ISSUE TITLE
Startup broken on OSX for latest self updating VSCODE !!!!!

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode#3855]
VSCode requested to self update. It did that and restarted itself.

Then, It asked me to edit my ".bash_profile" to remove a reference to "code". It even asked me to do it inside VSCode. I removed the line and it asked to restart.
Here is the line:
````
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
````

Now, from terminal i get:

`````
x-MacBook-Pro:~ apple$ code .
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xf79d6]

goroutine 1 [running]:
github.com/dancannon/GoRethink_TodoDemo/common.init.1.func1(0x4e5450, 0x9, 0x0, 0x0, 0xef4530, 0xc820073920, 0x0, 0x0)
	/Users/apple/workspace/go/src/github.com/dancannon/GoRethink_TodoDemo/common/util.go:16 +0x46
path/filepath.Walk(0x4e5450, 0x9, 0xc82005def8, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:394 +0xa5
github.com/dancannon/GoRethink_TodoDemo/common.init.1()
	/Users/apple/workspace/go/src/github.com/dancannon/GoRethink_TodoDemo/common/util.go:15 +0xa3
github.com/dancannon/GoRethink_TodoDemo/common.init()
	/Users/apple/workspace/go/src/github.com/dancannon/GoRethink_TodoDemo/common/ws_hub.go:50 +0x59
main.init()
	/Users/apple/workspace/go/src/bitbucket.org/gedw99/apparently_different/backend/code/ws_changes.go:71 +0x54

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/ru

```

**Comment by joeblew99** [comment]
I had to remove a comment with the work "code" in it.

that fixed it.
