### ISSUE TITLE
'Can't read property filter of undefined' error when querying extension marketplace for terms starting with 'type'

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#38561]
- VSCode Version: Code - Insiders 1.19.0-insider (91a2020698b5220e50f60682724927a810608356, 2017-11-16T06:10:28.922Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.22
Go|luk|0.6.67
MagicPython|mag|1.0.12
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0

---

Steps to Reproduce:

1. Open Extensions viewlet 
2. Search for the term `type` or `typescript` 
3. Get the following error: 

![screen shot 2017-11-16 at 2 35 45 pm](https://user-images.githubusercontent.com/9022011/32919645-7450647e-cadb-11e7-984d-18121b999f62.png)

Stacktrace: 

```js
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2718 Cannot read property 'filter' of undefined: TypeError: Cannot read property 'filter' of undefined
    at w (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4442:545)
    at k (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4443:583)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4449:758
    at Array.map (native)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4449:733
    at Object.g [as _notify] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:134:449)
    at Object.enter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:137:778)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:139:573)
    at n.Class.derive._oncancel._completed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:139:14)
    at t.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4442:8)
```

Reproduces without extensions: Yes

**Comment by rodrigoelp** [comment]
Hi @ggilmore, I raised this issue a few days ago here #38357

**Comment by ggilmore** [comment]
@rodrigoelp I'd be happy to close this - could you modify the title / post an update that specifically says that it happens when you search for `type...`?

**Comment by ggilmore** [comment]
Closed in favor of https://github.com/Microsoft/vscode/issues/38357

**Comment by rodrigoelp** [comment]
Updated. Thanks for your observation
