### ISSUE TITLE
Multiple vs code extensions error on ubuntu

### ISSUE THREAD

**Issue by bivinvinod** [Microsoft/vscode#38584]
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04 LTS

Am getting this error on multiple extensions. Try removing all extensions and config etc. Still cant fix it

`console.ts:123 [Extension Host]% Array(4)
console.ts:123 [Extension Host] Error: spawn php-cs-fixer ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
console.ts:123 [Extension Host]% (4) ["fix", "--using-cache=no", "/tmp/temp-lveplztq.php", "--rules=@PSR2"]
console.ts:123 [Extension Host] Error: spawn php-cs-fixer ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)`

Reproduces without extensions: No

**Comment by bivinvinod** [comment]
My bad
