### ISSUE TITLE
Error running npm run watch

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#3864]
When trying to run `npm run watch` I get the following error.

```
jsloyer@Jeffs-MacBook-Pro ~/dev/vscode (master)$ npm run watch

> Code@0.10.12 watch /Users/jsloyer/dev/vscode
> gulp watch

/Users/jsloyer/dev/vscode/build/gulpfile.vscode.js:324
var rpmBuildPath = path.join(os.homedir(), 'rpmbuild');
                                ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/jsloyer/dev/vscode/build/gulpfile.vscode.js:324:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jsloyer/dev/vscode/gulpfile.js:188:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! Code@0.10.12 watch: `gulp watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Code@0.10.12 watch script 'gulp watch'.
npm ERR! This is most likely a problem with the Code package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls Code
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jsloyer/dev/vscode/npm-debug.log
```

I am up to do to this commit locally, https://github.com/Microsoft/vscode/commit/a4f8a1657f57dc4a91242e0d294c29e97c8e2054.

**Comment by jsloyer** [comment]
It looks like `os.homedir()` was not added till Node 4.  I updated to Node 4 and things now work.  I would like to suggest updating the readme to state Node 4 is required, not Node 0.12.

**Comment by joaomoreno** [comment]
Thanks for the tip, let me do that.
