### ISSUE TITLE
Command 'python.updateFeedbackCounter' not found while using python remote debugging

### ISSUE THREAD

**Issue by ojhaujjwal** [Microsoft/vscode#38940]
- VSCode Version: 1.18.1
- OS Version: macOS Sierra Version 10.12.6

Steps to Reproduce:

1. Run a python process in vscode.
2. Create the following launch configuration:
```json
        {
            "name": "xxxxx Remote",
            "type": "python",
            "request": "attach",
            "localRoot": "/Users/xxx/yy/zzz",
            "remoteRoot": "/home/xxx/yy/zzz",
            "port": 3453,
            "secret": "my_secret",
            "host": "192.168.7.156"
        },
```
I got the following stack trace while initializing the debugger through vscode.

```
Command 'python.updateFeedbackCounter' not found: Error: command 'python.updateFeedbackCounter' not found
    at t._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1117373)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1117212
    at n.Class.define.cancel.then (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:69309)
    at t.executeCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1117186)
    at e.$executeCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2823079)
    at t.e.invoke (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2876809)
    at e._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2440566)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2440256)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2439283
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2441202
e.onUnexpectedError @ workbench.main.js:10
(anonymous) @ workbench.main.js:10
e.onUnexpectedError @ workbench.main.js:9
o @ workbench.main.js:9
e.$onUnexpectedError @ workbench.main.js:9
e.invoke @ workbench.main.js:9
e._invokeHandler @ workbench.main.js:9
e._receiveOneMessage @ workbench.main.js:9
(anonymous) @ workbench.main.js:9
(anonymous) @ workbench.main.js:9
e.invoke @ workbench.main.js:9
e.fire @ workbench.main.js:9
(anonymous) @ workbench.main.js:9
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: https://github.com/Microsoft/vscode-python/issues
