### ISSUE TITLE
SyntaxError: Unexpected end of JSON input. Build failing on MacOS

### ISSUE THREAD

**Issue by jordwalke** [Microsoft/vscode#39067]
- VSCode Version: `master` branch
- OS Version: 10.12.6 Mac OS

Steps to Reproduce:

1. Follow clone/build instructions perfectly.

Cannot build the repo. Followed instructions perfectly.
At [this stage](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build) in the instructions, I get the following error:

```
me-MacBook:vscode jwalke$ yarn run watch
yarn run v0.27.5
$ gulp watch --max_old_space_size=4096
[15:53:49] Node flags detected: --max_old_space_size=4096
[15:53:49] Respawned to PID: 11974
undefined:1
{"type":"tree","data":{"type":"list","trees":[{"name":"abbrev@1.0.9","children":[],"hint":null,"color":"bold","depth":0},{"name":"amdefine@1.0.1","children":[],"hint":null,"color":"bold","depth":0},{"name":"ansi-regex@2.1.1","children":[],"hint":null,"color":"bold","depth":0},{"name":"argparse@1.0.9","children":[{"name":"sprintf-js@~1.0.2","color":"dim","shadow":true}],"hint":null,"color":"bold","depth":0},{"name":"assert-plus@1.0.0","children":[],"hint":null,"color":"bold","depth":0},{"name":"async@1.5.2","children":[],"hint":null,"color":"bold","depth":0},{"name":"aws-sign2@0.6.0","children":[],"hint":null,"color":"bold","depth":0},{"name":"balanced-match@0.4.2","children":[],"hint":null,"color":"bold","depth":0},{"name":"boom@0.4.2","children":[{"name":"hoek@0.9.x","color":"dim","shadow":true},{"name":"hoek@0.9.1","children":[],"hint":null,"color":"bold","depth":0}],"hint":null,"color":"bold","depth":0},{"name":"camelcase@2.1.1","children":[],"hint":null,"color":"bold","depth":0},{"name":"cas

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getYarnProductionDependencies (/Users/jwalke/github/vscode/build/dependencies.js:53:21)
    at Object.getProductionDependencies (/Users/jwalke/github/vscode/build/dependencies.js:62:15)
    at Object.<anonymous> (/Users/jwalke/github/vscode/build/gulpfile.vscode.js:38:37)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at require.sync.forEach.f (/Users/jwalke/github/vscode/gulpfile.js:76:17)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/jwalke/github/vscode/gulpfile.js:76:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
error Command failed with exit code 1.
```

**Comment by jordwalke** [comment]
More info:

```
yarn --version
0.27.5
```

```
node --version
v8.9.1
```

**Comment by jordwalke** [comment]
Upgrading to yarn `v1.3.2` seemed to fix this. I would recommend putting a requirement on the version in the docs. Closing.
