### ISSUE TITLE
macOS High Sierra 10.13.1, run yarn fail,scode/node_modules/nsfw: Command failed.

### ISSUE THREAD

**Issue by yuzhidi** [Microsoft/vscode#39362]
macOS High Sierra 10.13.1
Leocones:vscode leocone$ yarn
yarn install v1.3.2
$ node build/npm/preinstall.js
[1/4] 🔍 Resolving packages...
[2/4] 🚚 Fetching packages...
info windows-foreground-love@0.1.0: The platform "darwin" is incompatible with this module.
info "windows-foreground-love@0.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.2.0: The platform "darwin" is incompatible with this module.
info "windows-mutex@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.1.6: The platform "darwin" is incompatible with this module.
info "windows-process-tree@0.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗 Linking dependencies...
[4/4] 📃 Building fresh packages...
[8/12] ⠠ vscode-fsevents: CXX(target) Release/obj.target/fse/fsevents.o
[9/12] ⠠ vscode-ripgrep: Renaming _node_modules => node_modules
[10/12] ⠠ oniguruma: spawn args '-Goutput_dir=.' ]
[4/12] ⠠ native-keymap: CXX(target) Release/obj.target/keymapping/src/keyboard_mac.o
error /Users/leocone/Study/vscode/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/leocone/Study/vscode/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/leocone/Study/vscode/node_modules/nsfw/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/leocone/.node-gyp/iojs-1.7.9/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/leocone/.node-gyp/iojs-1.7.9',
gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/leocone/.node-gyp/iojs-1.7.9/<(target_arch)/iojs.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/leocone/Study/vscode/node_modules/nsfw',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
CC(target) Release/obj.target/openpa/openpa/src/opa_primitives.o
CC(target) Release/obj.target/openpa/openpa/src/opa_queue.o
LIBTOOL-STATIC Release/openpa.a
libtool: unrecognized option -static' libtool: Trylibtool --help' for more information.
make: *** [Release/openpa.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/leocone/Study/vscode/node_modules/nsfw

**Comment by yuzhidi** [comment]
any info should I provide?

**Comment by yuzhidi** [comment]
I should put /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/
in $PATH
