### ISSUE TITLE
Cannot read property toString of null error when opening settings page 

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#39377]
- VSCode Version: code-oss-dev 1.19.0 (Commit e86931145f2d035c74e7c06263abe3a5c46dfe06)
- OS Version: Darwin x64 17.2.0
- Extensions: none
---

Steps to Reproduce:

1. Open user settings page (`Cmd + ,`)
2. Get this error in the console: 

```fish
[97174:1130/111605.856171:INFO:CONSOLE(274)] "Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at OpenEditorsView.getIndex (file:///Users/ggilmore/mess/vscode/out/vs/workbench/parts/files/electron-browser/views/openEditorsView.js:187:80)
    at OpenEditorsView.onEditorStacksModelChanged (file:///Users/ggilmore/mess/vscode/out/vs/workbench/parts/files/electron-browser/views/openEditorsView.js:249:34)
    at file:///Users/ggilmore/mess/vscode/out/vs/workbench/parts/files/electron-browser/views/openEditorsView.js:59:91
    at Emitter.fire (file:///Users/ggilmore/mess/vscode/out/vs/base/common/event.js:104:38)
    at file:///Users/ggilmore/mess/vscode/out/vs/workbench/common/editor/editorStacksModel.js:1007:101
    at Emitter.fire (file:///Users/ggilmore/mess/vscode/out/vs/base/common/event.js:104:38)
    at EditorGroup.fireEvent (file:///Users/ggilmore/mess/vscode/out/vs/workbench/common/editor/editorStacksModel.js:437:44)
    at EditorGroup.setActive (file:///Users/ggilmore/mess/vscode/out/vs/workbench/common/editor/editorStacksModel.js:381:18)
    at EditorGroup.openEditor (file:///Users/ggilmore/mess/vscode/out/vs/workbench/common/editor/editorStacksModel.js:246:26)
    at EditorPart.doOpenEditor (file:///Users/ggilmore/mess/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:275:19)", source: file:///Users/ggilmore/mess/vscode/out/vs/workbench/electron-browser/shell.js (274)
```

**Comment by isidorn** [comment]
@ggilmore thanks for quickly filling this with nice repro steps
