### ISSUE TITLE
syntax error is not highlighted nor is the line identified when in debug

### ISSUE THREAD

**Issue by johngrabner** [Microsoft/vscode#39392]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. create code with this error

```
let transaction = {
        type: "record change",
        record_id: this.id,

        new_value: new_value,
        new_magic_code = makeid(),

        old_value = this.current_value,
        old_magic_code = this.current_magic_code,

        old_state = this.state,
        new_state = this.master?"confirmed" : "pending"
    }
```

2. run dubuger
 exception will only show the line doing the require

Exception has occurred: SyntaxError
SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\John\Documents\GitHub\jjg_distributed_db\test\test_1_entity.js:6:16)

3.  So must leave Visual Code Studio and run node directly to see the line at fault

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20381
