### ISSUE TITLE
`Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null` after updating settings.

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#39453]
- VSCode Version: Code - Insiders 1.19.0-insider (adcde8ddeb37f7a5881494707b13353e3f560097, 2017-12-01T05:15:02.148Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
scope-bar|amo|0.0.3
markdown-emoji|bie|0.0.7
vscode-remind-me|cg-|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
gitignore|cod|0.5.0
compulim-vscode-closetag|Com|1.1.0
gitlens|eam|6.3.0
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.1
php-intellisense|fel|2.0.2
auto-close-tag|for|0.5.4
auto-rename-tag|for|0.0.15
composer|ika|0.7.1
smarty|imp|0.2.0
vscode-apache|mrm|1.1.1
php-docblocker|nei|1.3.2
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.18.1
code-settings-sync|Sha|2.8.6
lorem-ipsum|Tyr|1.1.0
vscode-todo-highlight|way|0.5.11
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Update your settings with Developer Tools enabled
2. Get this:
```
workbench.main.js:4490 Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at t.getIndex (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3905:835)
    at t.onEditorStacksModelChanged (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3907:273)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3901:567
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:159:551)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2093:326
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:159:551)
    at e.fireEvent (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2082:548)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2080:247
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:159:551)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2065:404
```

Reproduces without extensions: Yes

**Comment by cleidigh** [comment]
@jens1o 
I could not reproduce on Windows 7, have you tried/seen this on anything other than Windows 10?

**Comment by jens1o** [comment]
I do not have another operating system at the moment besides Windows 10, unfortunately.

What can I do to help you finding the problem quicker?

**Comment by cleidigh** [comment]
@jens1o 
I have a Windows ten VM which is barely usable speed wise.  MaybeICan give that a try to reproduce.

**Comment by isidorn** [comment]
I fixed this in latest
