### ISSUE TITLE
[ERROR] Error: Failed to start OmniSharp

### ISSUE THREAD

**Issue by egenita** [Microsoft/vscode#3949]
[INFO] Starting OmniSharp at 'd:\dev\aspnet vnext\MovieAngularJsApp'...
[INFO] Started OmniSharp from 'C:\Users\EGenita\.vscode\extensions\ms-vscode.csharp-0.3.3\bin\omnisharp.cmd' with process id 3228...
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at OmniSharp.OmnisharpWorkspace..ctor(HostServicesBuilder builder)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.TypedParts.ActivationFeatures.DisposalFeature.<>c__DisplayClass1.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass2.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport[TExport](String contractName)
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, ILibraryManager manager, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOptions`1 optionsAccessor)
[ERROR] Error: Failed to start OmniSharp

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#83

**Comment by hickford** [comment]
I have a similar problem "Error starting OmniSharp"
