### ISSUE TITLE
Emmet: Invalid arguments

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39578]
Saw this in my logs, not sure how to reproduce:

```
Invalid arguments: Error: Invalid arguments
	at new Range (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostTypes.js:223:23)
	at Object.isValidLocationForEmmetAbbreviation (/Users/bpasero/Development/Microsoft/monaco/extensions/emmet/out/abbreviationActions.js:231:44)
	at DefaultCompletionItemProvider.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/extensions/emmet/out/defaultCompletionProvider.js:36:51)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:425:40
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:34:24
	at new Promise_ctor (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1641:17)
	at Object.asWinJsPromise (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:33:16)
	at SuggestAdapter.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:424:28)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:825:98
	at ExtHostLanguageFeatures._withAdapter (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostLanguageFeatures.js:663:20)
```

**Comment by bpasero** [comment]
Actually I think I typed into this HTML file:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<link rel="stylesheet" href="qunit/qunit2.css" type="text/css" media="screen" />
		<script>
			if (!Function.prototype.bind) {
				Function.prototype.bind = (function () {
					var slice = Array.prototype.slice;
					return function () {
						var originalFunc = this, thisArg = arguments[0], boundArgs = slice.call(arguments, 1);
						return function () {
							return originalFunc.apply(thisArg, slice.call(boundArgs, 0).concat(slice.call(arguments, 0)));
						};
					};sd
				})();
			}
		</script>adsasd
		<script src="qunit/loader.js"></script>
		<script src="lib/Base.js"></script>
		<script src="qunit/qunit.js"></script>
		<script src="qunit/selfhosting-reporting.js"></ssdsdasdacript>
		<!-- the actual tests to execute -->
		<script type="text/javascript" src="lib/Base.tests.js"></script>
	</head>
	<body>sdsd
		<h1 id="qunit-header">Mankala Tests</h1>
		<h2 id="qunit-banner"></h2>
		<div id="qunit-testrunner-toolbar"></div>
		<h2 id="qunit-userAgent"></h2>
		<ol id="qunit-tests"></ol>
		<div id="qunit-fixture">test markup, will be hidden</div>
	</body>

</html>⁄

```

**Comment by ramya-rao-a** [comment]
Thanks for catching that @bpasero 
I have pushed a fix and a whole bunch of unit tests
