### ISSUE TITLE
integrated terminal mbed compile error (python "print" io error 0)

### ISSUE THREAD

**Issue by Meano** [Microsoft/vscode#39608]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|ms-|0.8.0
cpptools|ms-|0.14.3

---

Mbed compile error, mbed-cli command runs well in cmd/powershell but print error 0 in VSCode shell.

Steps to Reproduce:

1. Install Python 2 & Git
2. Install mbed-cli : pip install mbed-cli
3. Install gcc-arm : https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
4. Try compile for example:
     (1) mbed new mbed-example
     (2) mbed target NUCLEO_F446ZE
     (3) mbed toolchain GCC_ARM
     (4) mbed compile --profile debug -c -vv
    `[DEBUG] Return: 0Traceback (most recent call last):
  File "E:\Project\CPP\mbed-example\mbed-os\tools\make.py", line 296, in <module>
    stats_depth=options.stats_depth)
  File "E:\Project\CPP\mbed-example\mbed-os\tools\build_api.py", line 540, in build_project
    objects = toolchain.compile_sources(resources, resources.inc_dirs)
  File "E:\Project\CPP\mbed-example\mbed-os\tools\toolchains\__init__.py", line 928, in compile_sources
    return self.compile_queue(queue, objects)
  File "E:\Project\CPP\mbed-example\mbed-os\tools\toolchains\__init__.py", line 982, in compile_queue
    res['command']
  File "E:\Project\CPP\mbed-example\mbed-os\tools\toolchains\__init__.py", line 1089, in compile_output
    self.debug("Return: %s"% _rc)
  File "E:\Project\CPP\mbed-example\mbed-os\tools\toolchains\__init__.py", line 1183, in debug
    self.notify({'type': 'debug', 'message': message})
  File "E:\Project\CPP\mbed-example\mbed-os\tools\toolchains\__init__.py", line 504, in notify
    return self.notify_fun(event, self.silent)
  File "E:\Project\CPP\mbed-example\mbed-os\tools\toolchains\__init__.py", line 475, in print_notify
    print msg
IOError: [Errno 0] Error
[mbed] ERROR: "D:\Software\Develop\Python2\python.exe" returned error code 1.
[mbed] ERROR: Command "D:\Software\Develop\Python2\python.exe -u E:\Project\CPP\mbed-example\mbed-os\tools\make.py -t GCC_ARM -m NUCLEO_F446ZE --profile debug --source . --build .\BUILD\NUCLEO_F446ZE\GCC_ARM -c -v" in "E:\Project\CPP\mbed-example"
---`
     Error like this, it's python "print" function IO error but the scripts works well in external terminal or compile in Windows 7.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#349
