### ISSUE TITLE
code --status crashes for some folders opened in code

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39731]
#33051 - VSCode Version: Code - Insiders 1.19.0-insider (6bc5a14bf34e44b3af5508350cc1221fcc999ceb, 2017-12-05T06:14:37.864Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: none
---

Testing #39376

Steps to Reproduce:

1. On Ubunutu 16.0.4 
1. `code-insiders /home/parallels/Desktop`
2. `code-insiders -s`

**Bug**

```
parallels@parallels-vm:~/Desktop$ code-insiders -s

Version:          Code - Insiders 1.19.0-insider (6bc5a14bf34e44b3af5508350cc1221fcc999ceb, 2017-12-05T06:14:37.864Z)
OS Version:       Linux x64 4.10.0-40-generic)
CPUs:             Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)
Memory (System):  3.85GB (2.09GB free)
Load (avg):       2, 1, 1
VM:               100%
Screen Reader:    no

CPU %	Mem MB	Process
   21	   103	code-insiders main
    0	    28	   zygote
   67	   233	     window (Welcome - Desktop - Visual Studio Code - Insiders)
   31	    51	       watcherService
   19	    55	       extensionHost
   38	    95	     shared-process
    4	    43	   gpu-process

Workspace Stats:
|  Window (Welcome - Desktop - Visual Studio Code - Insiders)
|    Folder (Desktop)
[main 1:58:06 PM] Error: ENOENT: no such file or directory, stat '/home/parallels/Desktop/Parallels Shared Folders/Home/.atom/dev/packages/language-javascript'
    at fs.statSync (fs.js:973:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
    at c (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:134:124)
    at c (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:134:179)
    at c (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:134:179)
    at c (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:134:179)
    at c (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:134:179)
    at c (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:134:179)
    at Object.o [as collectWorkspaceStats] (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:134:205)
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:184:405
```

**Comment by mjbvz** [comment]
Actually seems unrelated to the user-data-dir as I original thought. Just opening the desktop folder in code causes this crash when you run `--status`

**Comment by bpasero** [comment]
@mjbvz can you try again with latest, I pushed a change to catch an error and show it to the user instead.

@egamma in your workspace stats implementation you might want to tweak the loop to catch errors and handle them more gracefully.

**Comment by egamma** [comment]
@bpasero yes will do and it also needs an upper bound for the number of files that are 'stated'.
