### ISSUE TITLE
TypeScript debugging with Chrome and webpack

### ISSUE THREAD

**Issue by k-vekos** [Microsoft/vscode#39797]
Similar issue as https://github.com/Microsoft/vscode/issues/39288

Getting this error message when launching chrome for debugging: 

```
SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:52911/dist/filter.js.map
SourceMaps.getMapForGeneratedPath: exception while processing path: http://localhost:52911/dist/vendor.js?v=T9CSTAima0yMmi79RS6ysKsthTYkWO4Wn7OFpq4Bwic, sourcemap: filter.js.map
SyntaxError: Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\Users\zzz\.vscode\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:20:25)
    at sourceMapContentsP.then.contents (C:\Users\zzz\.vscode\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:53:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Here is my `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:52911/maintenance-tasks",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/ClientApp/",
            "sourceMapPathOverrides": {      
                "webpack:///./*":"${workspaceRoot}\\*"
            },
            "runtimeArgs": ["--disable-session-crashed-bubble"]
        }
    ]
}
```

Tried the solution from the linked issue but didn't help in my case.

- VSCode Version: 1.18.0

**Comment by k-vekos** [comment]
Maybe this will help... If I look at `filter.js` in Chrome debugging tools I see it is mapped from main-client.js and doesn't mention vendor.js:

![image](https://user-images.githubusercontent.com/23462254/33668292-56c39fba-da6d-11e7-998e-c52ae50b30b9.png)

**Comment by roblourens** [comment]
Do you know what the actual path for the sourcemap for vendor.js is? Apparently Chrome is telling us it's `filter.js.map` so we look for that file next to vendor.js. Don't know whether that makes sense.

**Comment by k-vekos** [comment]
I'm not exactly sure what you're asking. I know that `vendor.js` actually contains this line: `//# sourceMappingURL=filter.js.map` and I take that to mean that webpack packed all the sourcemaps including `filter.js.map` into `vendor.js` but it seems like the debugger just can't understand the packed file?

**Comment by roblourens** [comment]
That means that if vendor.js is at `http://localhost:52911/dist/vendor.js`, then the sourcemap is at `http://localhost:52911/dist/filter.js.map`, so the debug adapter is trying the right thing. But you said that you get a blank page when you visit that url, so something is wrong.

I'm asking where filter.js.map is on disk, although with some tools, it may not be on disk at all.

Can you try something else too? Open `http://localhost:52911/dist/filter.js.map?v=T9CSTAima0yMmi79RS6ysKsthTYkWO4Wn7OFpq4Bwic` - I wonder if that query param is needed to download the sourcemap file.

Also if you can share this project, that would be helpful. And the screenshot is confusing, that doesn't look like your sources, that looks like babel/webpack output, but chrome devtools says it's sourcemapped.

**Comment by auchenberg** [comment]
Would it be possible for you to share a demo app with your webpack setup @k-vekos? Looks like we are trying to parse a JS file as json.

**Comment by k-vekos** [comment]
@roblourens I tried `...filter.js.map?v=...` and got the same blank result. I found only these places where a file named `filter.js.map` exist:

```
\node_modules\rxjs\_esm2015\add\operator\filter.js.map
\node_modules\rxjs\_esm2015\operator\filter.js.map
\node_modules\rxjs\_esm2015\operators\filter.js.map
\node_modules\rxjs\_esm5\add\operator\filter.js.map
\node_modules\rxjs\_esm5\operator\filter.js.map
\node_modules\rxjs\_esm5\operators\filter.js.map
\node_modules\rxjs\add\operator\filter.js.map
\node_modules\rxjs\operator\filter.js.map
\node_modules\rxjs\operators\filter.js.map
```

Of course none of these are visible by the hosted app though.

@auchenberg I will try to create a demo and replicate the issue.

**Comment by roblourens** [comment]
Without looking at your setup, one possibility is that you end up with multiple sourcemapping steps, which could explain some of the weirdness.

**Comment by k-vekos** [comment]
My setup is based on the default VS2017 ASP.Net Core w/ .NET Framework + Angular template. For now I can post my webpack configs while I try to replicate the issue in a demo.

[webpack.config.js](https://gist.github.com/k-vekos/274507e0b67d4a4435ad9dd20889c95e#file-webpack-config-js)
[webpack.config.vendor.js](https://gist.github.com/k-vekos/65345d8ca55926d989a221a10352a573#file-webpack-config-vendor-js)

**Comment by k-vekos** [comment]
I used the default VS2017 .NET Core + .NET Framework + Angular template for my project. Here are my webpack config files while I try to replicate the issue in a demo project:

[webpack.config.js](https://gist.github.com/k-vekos/274507e0b67d4a4435ad9dd20889c95e#file-webpack-config-js)
[webpack.config.vendor.js](https://gist.github.com/k-vekos/65345d8ca55926d989a221a10352a573#file-webpack-config-vendor-js)

EDIT: Posted the wrong configs before, now they're correct.

**Comment by k-vekos** [comment]
@roblourens @auchenberg Ok looks like it happens with just the default template project with no modifications!

Where can I upload the .zip of my project?

**Comment by k-vekos** [comment]
Nevermind, got upload to work here:

[VSCodeDebugError.zip](https://github.com/Microsoft/vscode/files/1549155/VSCodeDebugError.zip)

Here's my repro steps:

1. Open and run the application in VS2017 in Debug mode on Any CPU and config "VSCodeDebugError".
2. Open VSCode and edit `launch.json` to have the correct URL and port # for debugging.
3. Run debugging in VSCode.
4. Once the page launches check the VSCode console for the below error message:

```
SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:10928/dist/tryCatch.js.map
SourceMaps.getMapForGeneratedPath: exception while processing path: http://localhost:10928/dist/vendor.js?v=RCvRrqPvM2Kc5BlkEQ045FeXR6gPMRIwfn51ludN14I, sourcemap: tryCatch.js.map
SyntaxError: Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\Users\z0034sxn.SH01\.vscode\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:20:25)
    at sourceMapContentsP.then.contents (C:\Users\z0034sxn.SH01\.vscode\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:53:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by roblourens** [comment]
Sorry for the late response but I don't know how to run your project. I can build it with webpack. But what do you do to start a server?
