### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by KayUOM** [Microsoft/vscode#40162]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
Angular-BeastCode|Mik|5.1.8
material-icon-theme|PKi|3.1.0
html-snippets|abu|0.1.0
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
theme-monokai-pro-vscode|mon|1.1.2
typescript-hero|rbb|1.8.0
vscode-icons|rob|7.19.0
move-ts|str|1.5.0
---

Steps to Reproduce: None

Reproduces without extensions: No

Developer console output:

```

 debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
%c 1: node::Abort() [/usr/share/code/libnode.so]
 2: 0x7f236027ca57 [/usr/share/code/libnode.so]
 3: %c0x7f236001add7 [/usr/share/code/libnode.so]
 4: 0x7f236001ad55 [/usr/share/code/libnode.so]
 5: %cv8::internal::Factory::NewStruct(v8::internal::InstanceType) [/usr/share/code/libnode.so]
 6: v8::internal::Factory::NewTuple3(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/share/code/libnode.so]
 7: %c0x7f235fdd633d [/usr/share/code/libnode.so]
 8: %c0x7f235fdd8ee5 [/usr/share/code/libnode.so]
 9: %c0x7f235fdd89d9 [/usr/share/code/libnode.so]
10: %c0x7f235fddd6fa [/usr/share/code/libnode.so]
11: 0x33244318437d
%c
<--- Last few GCs --->

[21449:0x26f00bb93000]    78540 ms: Mark-sweep 2058.8 (2124.1) -> 2058.9 (2108.1) MB, 4265.8 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 4266 ms) last resort 
[21449:0x26f00bb93000]    82628 ms: Mark-sweep 2058.9 (2108.1) -> 2058.7 (2108.1) MB, 4085.8 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x20d05ee2b959 <JS Object>
    1: addTag(aka addTag) [/home/kay/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:18465] [pc=0x3324439e5331](this=0x3983c5a02311 <undefined>,tag=0x39a405375671 <a NodeObject with map 0x3414d72888c9>,comments=0x39a4053756f9 <JS Array[0]>)
    2: parseTag(aka parseTag) [/home/kay/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib...


index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
onError @ index.js:5
events.js:163 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
e._onExtensionHostCrashed @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly.
```
 (Same errors every time)

User Settings: 

```
{
    "workbench.colorTheme": "Monokai Classic",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontSize": 16,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
    "editor.detectIndentation": false,
    "eslint.autoFixOnSave": true,
    "tslint.autoFixOnSave": true,
}
```

Update: After disabling typescript-hero ive not gotten this error message.

**Comment by danielo515** [comment]
this was happening to me too. How did you realized the problem was typescript hero ?

**Comment by KayUOM** [comment]
@danielo515 

The js stacktrace in my original post mentions typescript.

**Comment by danielo515** [comment]
You're right.  After disabling the extension the problem have dissapeared to me too. Thanks
