### ISSUE TITLE
SelectBox Custom: Stack error , infinite disposal loop

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#40465]
New SelectBox custom implementation creates a circular disposal since toDispose is still passed to
the select box delegate where the class objects  are added into the disposable list which is really the parents list.

Steps to Reproduce:

1. start code, open a terminal (instantiates the drop-down lists)
2. Toggle panel (disposes SelectBox)
3. Code gives a stack err, panel becomes blank and unusable
4. Debugging shows an infinite disposal loop.

Debug added on disposal:

[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.474:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.474:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.474:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.475:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.475:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.476:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.476:INFO:CONSOLE(85)] "Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at Object.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:19)
    at SelectBoxList.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:443:42)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:56
    at Array.forEach (native)
    at Object.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:19)
    at SelectBoxList.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:443:42)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:56
    at Array.forEach (native)
    at Object.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:19)", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/services/message/browser/messageService.js (85)

**Comment by cleidigh** [comment]
Fixed with #40467
