### ISSUE TITLE
Unable to build 1.19 from source (Windows 32-bit) - %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by mattdsteele** [Microsoft/vscode#40476]
- VSCode Version: 1.19 (via Git tag)
- OS Version: Windows Server 2016, 64-bit

Steps to Reproduce:

1. Check out VSCode via git
1. Run `yarn --arch=ia32`
1. Run `gulp watch` (to rebuild monaco.d.ts)
1. Run `gulp vscode-win32-ia32`
1. Launch `Code - OSS.exe` - it fails with this error:

```
C:\Users\Administrator\Desktop\VSCode-win32-ia32>"Code - OSS.exe"

C:\Users\Administrator\Desktop\VSCode-win32-ia32>
{ errorCode: 'load',
  moduleId: 'spdlog',
  neededBy: [ 'vs/platform/log/node/spdlogService' ],
  detail:
   Error: %1 is not a valid Win32 application.
   \\?\C:\Users\Administrator\Desktop\VSCode-win32-ia32\resources\app\node_modules\spdlog\build\Release\spdlog.node
       at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
       at Object.Module._extensions..node (module.js:598:18)
       at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at require (C:\Users\Administrator\Desktop\VSCode-win32-ia32\resources\app\out\vs\loader.js:657:36)
       at bindings (C:\Users\Administrator\Desktop\VSCode-win32-ia32\resources\app\node_modules\bindings\bindings.js:81:44)
       at Object.<anonymous> (C:\Users\Administrator\Desktop\VSCode-win32-ia32\resources\app\node_modules\spdlog\index.js:3:35) }

```

I can compile and run `vscode-win32-x64` fine.

This appears related to a similar issue I encountered with 1.14 (prior to using Yarn): https://github.com/Microsoft/vscode/issues/31342.

Is cross-compiling like this still supported?

**Comment by joaomoreno** [comment]
In our build scripts we use the `npm_config_arch` set to `ia32` instead of passing `--arch=ia32` to yarn. Can you try that?

**Comment by mattdsteele** [comment]
Setting the `NPM_CONFIG_arch` to `ia32` did the trick! You might want to update the build instructions with this flag, as I'm sure I'll forget again 🙃  Thanks!

**Comment by joaomoreno** [comment]
@mattdsteele Updated! 👍
