### ISSUE TITLE
Error by building vscode

### ISSUE THREAD

**Issue by christianbender** [Microsoft/vscode#40521]
I want to build vscode as developer. I using/ have installed vscode. (1.19.0)

- VSCode Version: current repository
- OS Version: Linux Mint 

Steps to Reproduce:

I have already cloned the repository.

1.  call ``` yarn run watch ```

I get the following error message:

```
yarn run v1.3.2
$ gulp watch --max_old_space_size=4096
[16:11:52] Node flags detected: --max_old_space_size=4096
[16:11:52] Respawned to PID: 10815
module.js:471
    throw err;
    ^

Error: Cannot find module 'event-stream'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/christian/Programmierung/GitHub/Code/vscode/build/lib/util.js:7:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

I uses gulp version 
```
[16:12:27] CLI version 1.4.0
[16:12:27] Local version 3.9.1

```

node version **v6.12.2**

**Comment by cleidigh** [comment]
@christianbender 
From your issue comment, it appears you might not have installed all dependencies.
You need to use:

yarn

with no other options, this will install all development dependencies, then you can use the build watch task.
Also make sure you have all the other development pieces, Python Microsoft build tools etc

**Comment by joaomoreno** [comment]
```
git clean -xfd .
yarn
yarn run watch
```

**Comment by christianbender** [comment]
@all thanks it works. I have forgot ``` yarn ```
