### ISSUE TITLE
status CLI option - Cannot read property 'mem' of undefined

### ISSUE THREAD

**Issue by benurb** [Microsoft/vscode#40660]
Running the `--status` command on my Mac Book produced the following output:
```
$ code --status

Version:          Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
OS Version:       Darwin x64 15.6.0)
CPUs:             Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)
Memory (System):  16.00GB (2.37GB free)
Load (avg):       3, 6, 10
VM:               0%
Screen Reader:    no
[main 16:48:43] TypeError: Cannot read property 'mem' of undefined
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:182:900)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:181:452
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:181:476
    at <anonymous>
```

- VSCode Version: 1.19.0 and 1.19.1
- OS Version: mac OS 10.11.6 El Capitan

Steps to Reproduce:

1. Launch VS Code
2. Execute `code --status` on the terminal

Reproduces without extensions: Yes

**Comment by andi1984** [comment]
Same for me… adding my traceback in case it might be helpful:

```
Version:          Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
OS Version:       Darwin x64 16.7.0)
CPUs:             Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)
Memory (System):  16.00GB (2.81GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
[main 19:28:47] TypeError: Cannot read property 'mem' of undefined
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:182:900)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:181:452
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:181:476
    at <anonymous>
```

**Comment by benurb** [comment]
Quick update. I upraded mac OS from El Capitan to High Sierra and the problem persists:
```
$ code --status

Version:          Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
OS Version:       Darwin x64 17.3.0)
CPUs:             Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)
Memory (System):  16.00GB (1.06GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
[main 11:51:26] TypeError: Cannot read property 'mem' of undefined
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:182:900)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:181:452
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:181:476
    at <anonymous>
```

**Comment by weinand** [comment]
Do you see this problem every time you run `code --status`?

**Comment by benurb** [comment]
As far as I can tell: Yes

**Comment by weinand** [comment]
with "x folder(s) opened in VS Code" you mean
- "x workspaces open" or 
- "one workspace with x root folders open"?

**Comment by benurb** [comment]
I haven't tried out workspaces yet.
My workflow: "File" --> "New window", then "Open" and select a folder.
So I guess that's "x workspaces open", right?
