### ISSUE TITLE
TypeError: _this.task is not a function

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4071]
No steps. Just had a dev window openend and typed in it, switched editors, etc.
I saw it a few times already...

_this.task is not a function: TypeError: _this.task is not a function
    at file:///C:/Alex/src/vscode/out/vs/base/common/async.js:139:40
    at Object.notifySuccess [as _notify] (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_success_notify.enter (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1127:30)
    at Promise_ctor.WinJS.Class.define._run (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at Promise_ctor.WinJS.Class.define._completed (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1311:18)
    at file:///C:/Alex/src/vscode/out/vs/base/common/async.js:146:23

**Comment by joaomoreno** [comment]
Thanks for the help @alexandrudima!

**Comment by joaomoreno** [comment]
Would you care to give it a nice code review?

**Comment by alexandrudima** [comment]
LGTM
