### ISSUE TITLE
Support to call system-installed URL handlers

### ISSUE THREAD

**Issue by perlun** [microsoft/vscode#40858]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.22
prettier-eslint-vscode|Rob|0.7.3
vscode-wakatime|Wak|1.1.22
vagrant|bbe|0.5.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
git-project-manager|fel|1.4.0
file-icons|fil|1.0.7
vscode-ghc-mod|hoo|1.2.0
csharpextensions|jch|1.3.0
language-haskell|jus|2.4.0
docomment|k--|0.0.17
net-core-project-manager|ksu|0.3.6
coffeelinter|lky|1.2.0
VS-code-vagrantfile|mar|0.0.7
dotenv|mik|1.0.0
ruby-rubocop|mis|0.5.0
prettify-json|moh|0.0.3
python|ms-|0.9.1
azure-account|ms-|0.2.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
advanced-new-file|pat|1.1.0
Ruby|reb|0.15.0
java|red|0.16.0
rust|rus|0.3.2
final-newline|sam|0.3.2
RustyCode|sav|0.19.1
vscode-nginx|sha|0.4.1
trailing-spaces|sha|0.2.11
code-spell-checker|str|1.6.2
vscode-gfm-preview|tom|0.1.2
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
gitblame|wad|2.2.0
markdown-pdf|yza|0.1.7

(4 theme extensions excluded)

## Steps to Reproduce:

1. Cmd-click on a "onepassword" link.
2. You get an error as above. Full stack trace below:

```
[76132:1227/095005.696199:INFO:CONSOLE(38)] "[uncaught exception]: ENOPRO: no provider for onepassword://search/7B761EB044694029AD8E0CE1559EBE89", source: file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (38)
[76132:1227/095005.696267:INFO:CONSOLE(41)] "ENOPRO: no provider for onepassword://search/7B761EB044694029AD8E0CE1559EBE89
    at file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/files/electron-browser/remoteFileService.js:112:31
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Volumes/extra/git/3rd-party/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at RemoteFileService._withProvider (file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/files/electron-browser/remoteFileService.js:109:100)
    at RemoteFileService._doResolveContent (file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/files/electron-browser/remoteFileService.js:204:25)
    at RemoteFileService.resolveStreamContent (file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/files/electron-browser/remoteFileService.js:198:29)
    at TextFileService.resolveTextContent (file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/textfile/electron-browser/textFileService.js:36:37)
    at TextFileEditorModel.loadFromFile (file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:252:18)
    at file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:237:30
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Volumes/extra/git/3rd-party/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at TextFileEditorModel.loadWithBackup (file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:219:77)", source: file:///Volumes/extra/git/3rd-party/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (41)
```

### More details

[1Password](https://1password.com/) is a popular password manager for Windows, Mac and others.

They have their own URL scheme which has the format onepassword://search/uuid, where the uuid is a UUID-resembling identifier identifing an individual password entry. Being able to link to these is a very useful feature when working together in a team.

These URLs get registered on the system (macOS in this case) so copy-pasting an URL like this into Spotlight _works_, it does the right thing. But Cmd-clicking such a link in vscode does not.

I debugged this very briefly in a local vscode checkout, and concluded that this scheme (`onepassword:`) is seemingly not registered with the `RemoteFileService` class. How to fix this is beyond my knowledge of the VSCode internals though, I was hoping to submit a PR for this but I don't  really know where to start.

Could it be that VSCode does not pick up the system-registered URLs as expected?

If someone reading this knows how to fix it, _please let me know_ and suggest a path forward! I'll gladly cooperate with Microsoft and others on sorting this out, eventually submitting a PR to fix this.

Reproduces without extensions: Yes, tested - same behavior.

**Comment by perlun** [comment]
@joaomoreno/anyone, ideas on how to resolve this? As mentioned, I'll gladly dig in and share a helping hand if someone points me in the right direction.

**Comment by jrieken** [comment]
Yeah, today the list of known URI-schemes is fixed, as it's either a file, an http(s)-url, or a remote-file (a feature still under development). We don't have support to reach out to other, installed, os-level handlers but it does make sense.

**Comment by perlun** [comment]
@jrieken Alright, thanks (had missed your reply.) Where is this list? I can gladly submit a PR just as long as I know where to look.

**Comment by perlun** [comment]
Ping @jrieken - where is the fixed list?

**Comment by jrieken** [comment]
Check the `openerService`
