### ISSUE TITLE
Terminal.applyAddon is not a function

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40889]
Open terminal when running out of sources:

```
Terminal.applyAddon is not a function: TypeError: Terminal.applyAddon is not a function
    at TerminalInstance.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:264:38)
    at step (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:52:23)
    at Object.next (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:33:53)
    at fulfilled (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:24:58)
    at Object.notifySuccess [as _notify] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._completed (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1036:18)
    at <anonymous>
```

**Comment by Tyriar** [comment]
Should fix it:

```
rm -rf node_modules/xterm
yarn
```

I'll put a PSA out
