### ISSUE TITLE
Terminal throws Promise and TypeError , fails to launch

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#40927]
Current Master 12-28
OS: Windows 7

May be upstream issue with xterm.

Steps to reproduce:
- build code
- launch code and start terminal

See debug output.

> Executing task in folder vscode: .\scripts\code.bat <

[28188:1228/192153.718:INFO:CONSOLE(125)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/platform/keybinding/common/keybindingsRegistry.js (125)
[28188:1228/192153.719:INFO:CONSOLE(125)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/platform/keybinding/common/keybindingsRegistry.js (125)
[28188:1228/192153.719:INFO:CONSOLE(125)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/platform/keybinding/common/keybindingsRegistry.js (125)
[28188:1228/192154.685:INFO:CONSOLE(186)] "%c  ERR", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/platform/log/common/log.js (186)
[28188:1228/192154.685:INFO:CONSOLE(42)] "WARNING: Promise with no error callback:7", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/errors.js (42)
[28188:1228/192154.686:INFO:CONSOLE(43)] "[object Object]", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/errors.js (43)
[28188:1228/192155.345:INFO:CONSOLE(231)] "%c[Extension Host] %cdebugger listening on port 5870", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (231)
[28188:1228/192155.724:INFO:CONSOLE(146)] "%c[Extension Host] %cdebugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/c5e59a43-1853-4bbf-81be-10dd03ea23c8
", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (146)
[28188:1228/192156.483:INFO:CONSOLE(89)] "%c[Extension Host] %cvscode-icons is active! %c(at activate (C:\Users\Christopher Leidigh\.vscode-oss-dev\extensions\robertohuertasm.vscode-icons-7.12.0\out\src\index.js:50:13))", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/node/console.js (89)
Debugger listening on port 5876.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5876/810229ec-2266-47e0-bd10-4d4ab8cbec98
[28188:1228/192214.981:INFO:CONSOLE(38)] "[uncaught exception]: TypeError: Cannot read property 'measure' of undefined", source: file:///C:/VSC%20Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (38)
[28188:1228/192214.982:INFO:CONSOLE(41)] "TypeError: Cannot read property 'measure' of undefined
    at Terminal.resize (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\xterm\lib\Terminal.js:1248:25)
    at TerminalInstance.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:955:29)
    at TerminalInstance.setVisible (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:524:26)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/common/terminalService.js:152:34
    at Array.forEach (native)
    at TerminalService.setActiveInstanceByIndex (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/common/terminalService.js:151:37)
    at TerminalService.createInstance (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalService.js:54:22)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:88:67", source: file:///C:/VSC%20Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (41)
[28188:1228/192215.088:INFO:CONSOLE(186)] "%c  ERR", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/platform/log/common/log.js (186)
[28188:1228/192215.089:INFO:CONSOLE(42)] "WARNING: Promise with no error callback:90", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/errors.js (42)
[28188:1228/192215.090:INFO:CONSOLE(43)] "[object Object]", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/errors.js (43)
[28188:1228/192215.090:INFO:CONSOLE(45)] "TypeError: this._xterm.winptyCompatInit is not a function
    at TerminalInstance.<anonymous> (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:281:41)
    at step (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:52:23)
    at Object.next (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:33:53)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:27:71
    at new Promise_ctor (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/winjs.base.raw.js:1641:17)
    at __awaiter (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:23:12)
    at TerminalInstance._createXterm (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:253:20)
    at new TerminalInstance (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:121:44)
    at create (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/platform/instantiation/common/instantiationService.js:106:35)", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/errors.js (45)
[28188:1228/192215.637:VERBOSE1:CONSOLE(8479)] "Main._createAppUI: 67.18701171875ms", source: chrome-devtools://devtools/bundled/inspector.js (8479)
[28188:1228/192215.678:VERBOSE1:CONSOLE(8484)] "Main._showAppUI: 39.158935546875ms", source: chrome-devtools://devtools/bundled/inspector.js (8484)
[28188:1228/192215.920:VERBOSE1:CONSOLE(8485)] "Main._initializeTarget: 97.6669921875ms", source: chrome-devtools://devtools/bundled/inspector.js (8485)
[28188:1228/192216.951:INFO:CONSOLE(38)] "[uncaught exception]: TypeError: Cannot read property 'measure' of undefined", source: file:///C:/VSC%20Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (38)
[28188:1228/192216.953:INFO:CONSOLE(41)] "TypeError: Cannot read property 'measure' of undefined
    at Terminal.resize (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\xterm\lib\Terminal.js:1248:25)
    at TerminalInstance.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalInstance.js:955:29)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:72:19
    at Array.forEach (native)
    at TerminalPanel.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:71:53)
    at PanelPart.CompositePart.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/browser/parts/compositePart.js:383:38)
    at PanelPart.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:170:49)
    at WorkbenchLayout.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/browser/layout.js:554:24)
    at Workbench.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/workbench.js:671:38)
    at WorkbenchShell.layout (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/shell.js:264:28)", source: file:///C:/VSC%20Dev/vc-fork-cdl/vscode/out/vs/workbench/electron-browser/bootstrap/index.js (41)

Terminal will be reused by tasks, press any key to close it.

**Comment by cleidigh** [comment]
@Tyriar 
Just verified building Code after and including commit 114adf703be6203fba2da696aeac439449241ac9
the xterm upgrade is where the problem begins.

Also just saw @bpceee encountered this with OS X also.

**Comment by Tyriar** [comment]
I must be doing something wrong with yarn, the package in yarn.lock is correct but it's not the one being downloaded...

**Comment by Tyriar** [comment]
Maybe with yarn this is now necessary because of some aggressive caching or something? https://github.com/Microsoft/vscode/issues/38342

**Comment by cleidigh** [comment]
@Tyriar 
Can the module be downloaded manually?  Would that prove anything?

**Comment by Tyriar** [comment]
Temporary fix to get you going:

```
rm -rf node_modules/xterm
yarn add Tyriar/xterm.js#vscode-release/1.20
```

**Comment by cleidigh** [comment]
That works, good to know the single module yarn patching...

**Comment by Tyriar** [comment]
Should be fixed now, make sure you update your modules
