### ISSUE TITLE
TSServer Crashes After npm install rxjs

### ISSUE THREAD

**Issue by ophirbushi** [Microsoft/vscode#40998]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: none
---

Steps to Reproduce:

1. run npm install rxjs
2. open a new javascript file 
3. require Observable like this: const { Observable } = require('rxjs/Observable');

TSServer crashes

some of the tsserver log:

```
[Info  - 11:24:53 PM] TSServer exited
[Info  - 11:24:54 PM] Started TSServer
[Info  - 11:24:54 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 11:24:54 PM] Forking TSServer
PATH: /home/ophir/.nvm/versions/node/v8.9.2/bin:/home/ophir/bin:/home/ophir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[Info  - 11:24:54 PM] Started TSServer
[Error  - 11:24:57 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 11:24:57 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 11:24:57 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 11:24:58 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 11:24:59 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 11:27:06 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 11:27:06 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Info  - 11:27:20 PM] Killing TS Server
[Info  - 11:27:20 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 11:27:20 PM] TSServer log file: /tmp/vscode-tsserver-log-7cOWKp/tsserver.log
[Info  - 11:27:20 PM] Forking TSServer
PATH: /home/ophir/.nvm/versions/node/v8.9.2/bin:/home/ophir/bin:/home/ophir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[Info  - 11:27:21 PM] TSServer exited
[Info  - 11:27:21 PM] TSServer log file: /tmp/vscode-tsserver-log-7cOWKp/tsserver.log
[Info  - 11:27:21 PM] Started TSServer
[Info  - 11:27:21 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 11:27:21 PM] TSServer log file: /tmp/vscode-tsserver-log-68RD2v/tsserver.log
[Info  - 11:27:21 PM] Forking TSServer
PATH: /home/ophir/.nvm/versions/node/v8.9.2/bin:/home/ophir/bin:/home/ophir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[Info  - 11:27:21 PM] Killing TS Server
[Info  - 11:27:21 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 11:27:21 PM] TSServer log file: /tmp/vscode-tsserver-log-Xw8kmC/tsserver.log
[Info  - 11:27:21 PM] Forking TSServer
PATH: /home/ophir/.nvm/versions/node/v8.9.2/bin:/home/ophir/bin:/home/ophir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[Info  - 11:27:21 PM] TSServer exited
[Info  - 11:27:21 PM] TSServer log file: /tmp/vscode-tsserver-log-Xw8kmC/tsserver.log
[Info  - 11:27:21 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 11:27:21 PM] TSServer log file: /tmp/vscode-tsserver-log-NsZCHI/tsserver.log
[Info  - 11:27:21 PM] Forking TSServer
PATH: /home/ophir/.nvm/versions/node/v8.9.2/bin:/home/ophir/bin:/home/ophir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[Info  - 11:27:21 PM] Started TSServer
[Info  - 11:27:21 PM] Started TSServer
[Info  - 11:27:21 PM] Started TSServer
[Error  - 11:27:28 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 11:27:29 PM] 'completions' request failed with error.
Error processing request. Debug Failure. False expression: Script info with relative file name can only be open script info
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:82929:39)
    at HostCache.createEntry (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79730:44)
    at new HostCache (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:22)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:79934:29)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:83005:26)
    at IOSession.Session.getCompletions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:85661:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87013:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87022:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:87042:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20964
