### ISSUE TITLE
SyntaxError: Unexpected token ... while building VS code (source code)

### ISSUE THREAD

**Issue by monalisakalla** [Microsoft/vscode#41004]
home/monalisa/build/dependencies.js:46
	const raw = cp.execSync('yarn list --json', { cwd, encoding: 'utf8', env: { ...process.env, NODE_ENV: 'production' }, stdio: [null, null, 'ignore'] });
	                                                                            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)home/monalisa/build/dependencies.js:46
	const raw = cp.execSync('yarn list --json', { cwd, encoding: 'utf8', env: { ...process.env, NODE_ENV: 'production' }, stdio: [null, null, 'ignore'] });
	                                                                            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monalisa/build/gulpfile.vscode.js:35:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monalisa/build/gulpfile.vscode.js:35:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

- VSCode Version:latest source code available on gitHub
- OS Version:ubuntu 16.0

Steps to Reproduce:

1.clone vs code 
2.intall all prerequisite packages(git, nodejs version 8.9.2, yarn version 1.3.2 etc)
3)while doing sudo yarn run watch

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this still happen if you pull in the latest version from master?

**Comment by monalisakalla** [comment]
I have taken the vscode 4 days back available on link "https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run" and it happens.

**Comment by mjbvz** [comment]
@monalisakalla Please pull in the latest vscode sources and try again: `git pull origin master`

**Comment by ZhYong10** [comment]
This occur when I use the wrong version of NodeJS, v6.9.2 for example.
I worked out when I changed the version of NodeJS to v8.4.0 .
