### ISSUE TITLE
Release notes 1.19.1 won't go away

### ISSUE THREAD

**Issue by Shikkic** [Microsoft/vscode#41108]
I have been having this issue for awhile where the release notes will not go away, and they appear on every launch of vscode.

I saw this question on SO https://stackoverflow.com/questions/45913900/visual-studio-code-keeps-opening-the-release-notes, but it wasn't much help and couldn't find any related GH issues for it. (Not that it's super complicated but here is a [visual](https://i.imgur.com/OQYfVfr.mp4) of whats happening on my end).

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Extensions are disabled

Steps to Reproduce:

1. Open up file, or new VS code window
2. Release notes 1.19.1 always appears

Reproduces without extensions: Yes

FWIW, I imagine it might be that vscode is having trouble saving something internally, maybe due to a perm issue in some data folder, but I'm not sure.

**Comment by joaomoreno** [comment]
@bpasero The update contribute code uses the storage service for this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/update/electron-browser/update.ts#L236

It seems to work for pretty much everyone except this user. What could go wrong for him?

**Comment by bpasero** [comment]
@Shikkic how about other view state, e.g. is your last used editor restoring properly after a restart of Code on the same folder?

**Comment by Shikkic** [comment]
@bpasero @joaomoreno 

Yes. If I close the window without quitting vscode and reopen with the same folder all the files are restored properly without the release notes appearing.

**Comment by bpasero** [comment]
@Shikkic how do you "force quit"?

**Comment by Shikkic** [comment]
@bpasero I'm on macOS, so I use ⌘+Q

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Shikkic** [comment]
```log.ts:141 TRACE openWorkbench configuration {"_":["/Users/dancadden/dev/themuse"],"verbose":true,"appRoot":"/Applications/Visual Studio Code.app/Contents/Resources/app","machineId":"18c1ae670890f41882dd846880cc76a4e8f58d6fe089eb803b9569524109cbdc","execPath":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","userEnv":{"VSCODE_IPC_HOOK":"/Users/dancadden/Library/Application Support/Code/1.19.1-main.sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"/Users/dancadden/Library/Application Support/Code/logs/20180109T005919"},"isInitialStartup":true,"folderPath":"/Users/dancadden/dev/themuse","filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"/Users/dancadden/Library/Application Support/Code/CachedData/0759f77bb8d86658bc935a10a64f6182c5a1eeba","backupPath":"/Users/dancadden/Library/Application Support/Code/Backups/bff381d2f82d01b61ebb7a57b4702556","baseTheme":"vs","backgroundColor":"#ffffff","perfEntries":["mark","main:loadWindow",1515477559308,0],"perfStartTime":1515477558938,"perfAppReady":1515477559036,"perfWindowLoadTime":1515477559308}
00:59:20.329 extensionHost.ts:290 [Extension Host] debugger listening on port 9333
00:59:20.543 extensionService.ts:656 [/Users/dancadden/.vscode/extensions/ms-vscode.cpptools-0.14.5]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
00:59:20.544 extensionService.ts:656 [/Users/dancadden/.vscode/extensions/ms-vscode.cpptools-0.14.5]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
00:59:20.653 extensionHost.ts:200 [Extension Host] debugger inspector at %cStarting inspector on 127.0.0.1:9333 failed: address already in use

00:59:21.856 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.857 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.858 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.859 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.860 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.868 console.ts:123 [Extension Host] Unhandled Rejection at: Promise  Object  reason:  TypeError: Cannot read property 'options' of undefined
	at /Users/dancadden/.vscode/extensions/vscodevim.vim-0.10.8/out/extension.js:75:56
	at Generator.next (<anonymous>)
	at fulfilled (/Users/dancadden/.vscode/extensions/vscodevim.vim-0.10.8/out/extension.js:4:58)
	at <anonymous> (at process.<anonymous> (/Users/dancadden/.vscode/extensions/vscodevim.vim-0.10.8/out/extension.js:341:13))
00:59:21.868 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.868 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.868 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.868 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.868 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.869 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.870 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.870 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.870 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.870 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.872 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.872 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.879 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.901 log.ts:141 TRACE SCMService#registerSCMProvider
00:59:21.903 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:21.992 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:22.016 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:22.854 log.ts:141 TRACE CommandService#executeCommand setContext
00:59:22.872 console.ts:123 [Extension Host] rejected promise not handled within 1 second (at Timeout._onTimeout (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:534:327))
t.log @ console.ts:123
00:59:22.872 mainThreadExtensionService.ts:43 [vscodevim.vim]Cannot read property 'options' of undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
00:59:22.872 mainThreadExtensionService.ts:44 TypeError: Cannot read property 'options' of undefined
	at /Users/dancadden/.vscode/extensions/vscodevim.vim-0.10.8/out/extension.js:75:56
	at Generator.next (<anonymous>)
	at fulfilled (/Users/dancadden/.vscode/extensions/vscodevim.vim-0.10.8/out/extension.js:4:58)
	at <anonymous>```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Shikkic** [comment]
Just tried it out @bpasero  and I can't seem to reproduce the issues.

The release notes are gone, and it saves my session when I force quit the application and I'm able to restore where I left off.

**Comment by Shikkic** [comment]
Do you think it make sense to try and clear the `Local Storage >> file://` data? Maybe something is corrupt and it can't restore the session properly?

I dumped the storage into a [gist](https://gist.github.com/Shikkic/e341c10b887ed3d3b7d78c1d0f59fea6) if you wanna take a look.

I notice that towards the bottom it has multiple copies of similar data + keys for the following:

```
...
storage://workspace/empty:1510864758660/lifecyle.lastshutdownreason 
storage://workspace/empty:1510864758660/memento/workbench.editor.walkthroughpart
storage://workspace/empty:1510864758660/workbench.sidebar.hidden
...
```

**Comment by bpasero** [comment]
Can you share your settings?

**Comment by Shikkic** [comment]
@bpasero 

```{
    // Go
    "go.testOnSave": true,
    "go.coverOnSave": false,
    "go.useLanguageServer": false,
    "go.lintOnSave": "package",
    "go.vetOnSave": "package",
    "go.buildOnSave": "workspace",

    // Editor
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "editor.minimap.enabled": false,

    // Workbench
    "workbench.colorTheme": "Base16 Light Colors",
    "workbench.editor.enablePreview": false,
    "workbench.colorCustomizations": {
        "terminal.ansiBlack": "#181818",
        "terminal.ansiRed": "#ab4642",
        "terminal.ansiGreen": "#a1b56c",
        "terminal.ansiYellow": "#f7ca88",
        "terminal.ansiBlue": "#7cafc2",
        "terminal.ansiMagenta": "#ba8baf",
        "terminal.ansiCyan": "#86c1b9",
        "terminal.ansiWhite": "#d8d8d8",
        "terminal.ansiBrightBlack": "#585858",
        "terminal.ansiBrightRed": "#ab4642",
        "terminal.ansiBrightGreen": "#a1b56c",
        "terminal.ansiBrightYellow": "#f7ca88",
        "terminal.ansiBrightBlue": "#7cafc2",
        "terminal.ansiBrightMagenta": "#ba8baf",
        "terminal.ansiBrightCyan": "#86c1b9",
        "terminal.ansiBrightWhite": "#ffffff",
        "terminal.background": "#1d1f21",
        "terminal.foreground": "#fff"
    },

    // Atom Key Mappings
    "atomKeymap.promptV3Features": true,

    // Search Exclude
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/bower_components": true,
        "**/jspm_packages": true,
        "**/node_modules": true,
        //"**/vendor":true
    },

    // Vim
    "editor.lineNumbers": "relative",

    // Javascript
    "typescript.disableAutomaticTypeAcquisition": true,
    "javascript.validate.enable": false,
    "javascript.format.enable": false,
    "workbench.iconTheme": "vscode-great-icons",
    "window.zoomLevel": 0,
    "go.testFlags": [
        "-v"
    ],
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressUpdateNotice": false,
        "suppressWelcomeNotice": true
    },
    "extensions.ignoreRecommendations": false,
    "python.linting.enabledWithoutWorkspace": false,
    "python.disablePromptForFeatures": [
        "pylint"
    ],
    "rust.rustup": {
        "toolchain": "stable-x86_64-apple-darwin"
    },
    "rust.mode": "legacy",
    //"go.buildTags": "integration"
}
```

**Comment by bpasero** [comment]
@Shikkic what is the size of this folder for you: `/Users/<your user>/Library/Application Support/Code/Local Storage`?

**Comment by Shikkic** [comment]
@bpasero It's 2mb

**Comment by bpasero** [comment]
@Shikkic thats not too bad. Can you try this scenario with "code --user-data-dir <some empty folder>"? This will make sure the storage is written to a new empty place. I would expect this issue to not happen anymore in that case.

**Comment by Shikkic** [comment]
@bpasero It's still happening when I use `code --user-data-dir` 😢

**Comment by bpasero** [comment]
@Shikkic wow that is crazy, so then it must be related to Code stable vs Code insider. I have no idea what we changed though that could have an impact...

**Comment by bpasero** [comment]
@Shikkic to confirm, when you used that option, all settings were back to default and you saw the welcome screen right?

**Comment by Shikkic** [comment]
@bpasero I spoke too soon that was my bad, it actually worked, I forgot to specify the data dir with the flag.

If I do `code . --user-data-dir='.'` I don't see the release notes anymore

**Comment by Shikkic** [comment]
@bpasero How should I follow up? I'm assuming something in the user data folder is corrupted?

**Comment by bpasero** [comment]
@Shikkic ok you could take out the VS Code specific things from that folder and delete the storage related things. Basically:
* keep the `User` folder
* keep the `Workspaces` folder
* keep `storage.json` file
* keep `machineid`
* keep `Backups` folder

=> delete the rest and restart Code

**Comment by Shikkic** [comment]
@bpasero So I started deleting things one-by-one and re-opening VScode to see if I could find which fixed it.

I started with deleting `Local Storage` first, opened VS code and it works!! I'm no longer bound to the hellish prison of re-reading 1.19.1 release notes everyday.

Thanks so much for your consistent help! 🎉 🎈

**Comment by bpasero** [comment]
@Shikkic ok great to hear that
