### ISSUE TITLE
i am not able to type in terminal.

### ISSUE THREAD

**Issue by shubhamXelpmoc** [Microsoft/vscode#41694]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.4
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
guides|spy|0.9.1
local-history|xyz|1.6.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Will need more information in order to diagnose the problem. For starters what's in your settings.json file and can you post a screenshot of what the terminal looks like??

**Comment by shubhamXelpmoc** [comment]
![untitled](https://user-images.githubusercontent.com/22446939/35135519-c7980a42-fd03-11e7-8dc3-0c997bfbfb50.png)

settings.json
{
    "editor.renderIndentGuides": false,
    "workbench.startupEditor": "newUntitledFile",
    "window.openFilesInNewWindow": "on",
    "files.autoSave": "off",
    "workbench.editor.enablePreview": false,
    "editor.formatOnSave": false,
   "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\cmd.exe",
    "window.zoomLevel": 0
}

**Comment by Tyriar** [comment]
This will probably fix your problem:

```
"terminal.integrated.shell.windows": "C:\WINDOWS\System32\cmd.exe"
```

**Comment by shubhamXelpmoc** [comment]
Already tried. Not working

**Comment by Tyriar** [comment]
Are there any errors in devtools? (Help > Toggle Developer Tools)

**Comment by shubhamXelpmoc** [comment]
mainThreadExtensionService.ts:44 TypeError: Cannot read property 'document' of undefined
	at HistoryTreeProvider.changeActiveFile (C:\Users\Administrator\.vscode\extensions\xyz.local-history-1.6.2\out\src\historyTree.provider.js:149:56)
	at vscode.window.onDidChangeActiveTextEditor.e (C:\Users\Administrator\.vscode\extensions\xyz.local-history-1.6.2\out\src\extension.js:50:65)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:218)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:858
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:218)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:435:723)
	at t.e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:516:87)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:580)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:270)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:356:206
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:358:204

**Comment by Tyriar** [comment]
That error looks like a problem with this extension: xyz.local-history-1.6.2

On the terminal problem I'm not sure why this is happening, could you try running the select default shell command via the command palette (F1) and see if those options remedy the situation?

**Comment by shubhamXelpmoc** [comment]
Not working.

**Comment by shubhamXelpmoc** [comment]
No error in dev tools

**Comment by Tyriar** [comment]
Do any of the options work in the select default shell command? I'm out of ideas if powershell/git bash also don't work.
