### ISSUE TITLE
Couldn't start client HTML Language Server

### ISSUE THREAD

**Issue by Askewpoet53** [Microsoft/vscode#41829]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (2d79f9da3ca330ad7ebeb7dc3f538a0cf1634fa3, 2018-01-18T05:14:16.814Z)</li>
	<li>OS Version: Windows_NT x64 10.0.16299</li>
	<li>Extensions: none</li>
</ul>

---

Note: I am using materialize CSS along with a custom CSS file 
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="materialize/css/materialize.min.css" media="screen,projection" />
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="materialize/js/materialize.min.js"></script>
    <!--Import Custom Css File-->
    <link type="text/css" href="index.css" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pente</title>
</head>

<body class="mint-cream">
    <header>
        <nav>
            <div class="raspberry nav-wrapper">
                <a class="center brand-logo">Pente</a>
            </div>
        </nav>
    </header>
    <main>
        <div class="my-wrapper valign-wrapper center-align">
            <div class="container">
                <div class="row">
                    <div class="col offset-s2 s8">
                        <div class="card air-blue">
                            <div class="card-content white-text">
                                <span class="center card-title">Select a Game Type</span>
                                <br/>
                                <div class="center row">
                                    <div class="col s6">
                                        <a onclick="setGameMode(false); changeCard(1);" class="eagle-green waves-effect waves-light btn">Player v Player</a>
                                    </div>
                                    <div class="col s6">
                                        <a onclick="setGameMode(true); changeCard(1);" class="eagle-green waves-effect waves-light btn">Player v Computer</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="card air-blue">
                            <div class="card-content white-text">
                                <span class="center card-title">Player 1 Enter your name</span>
                                <div class="row">
                                    <div class="input-field col offset-s1 s10">
                                        <input id="first_name" type="text" class="center raisin-black-border">
                                        <label for="first_name">Name</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col offset-s4 s4">
                                        <a onclick="setPlayer();" class="eagle-green waves-effect waves-light btn">Submit</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="card air-blue">
                            <div class="card-content white-text">
                                <span class="center card-title">Player 2 Enter your name</span>
                                <div class="row">
                                    <div class="input-field col offset-s1 s10">
                                        <input id="first_name" type="text" class="center raisin-black-border">
                                        <label for="first_name">Name</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col offset-s4 s4">
                                        <a onclick="setPlayer();" class="eagle-green waves-effect waves-light btn">Submit</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="card air-blue">
                            <div class="card-content white-text">
                                <div class="row">
                                    <div class="col s9">
                                        <canvas id='canvas' width="500px" height="500px"></canvas>
                                    </div>
                                    <div class="col s3 sideBar">
                                        <h4 id="turnTitle">Player 1 turn</h4>
                                        <br/>
                                        <a id="endBtn" onclick="finishTurn();"  class="waves-effect waves-light btn">End Turn</a>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="card air-blue">
                            <div class="card-content white-text">
                                <span class="center card-title">(Winning Player Name) is the Winner!</span>
                                <br/>
                                <h5 class="center">Would you like to play again?</h5>
                                <br/>
                                <div class="row">
                                    <div class="center-align">
                                        <div class="col s6">
                                            <a class=" waves-effect waves-light btn">Yes</a>
                                        </div>
                                        <div class="col s6">
                                            <a class=" waves-effect waves-light btn">No</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer class="raspberry page-footer">
        <div class="footer-copyright">
            <div class="container">
                © 2018 Copyright
                <a class="grey-text text-lighten-4 right" href="https://www.pente.net/instructions.html">Instructions</a>
            </div>
        </div>
    </footer>
    <script src="script.js" type="text/javascript"></script>
</body>

</html>
```
I only opened a basic HTML file for a project for college

[Error - 2:34:58 PM] Starting client failed
Error: spawn C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by aeschli** [comment]
Sorry I can not reproduce
- I create an html file with the content you provided
- I opened the file in VSCode
- All opened and renderes fine, no exception or crash.

Please provide more detailed steps.
