### ISSUE TITLE
 ERR Illegal value 0 for `lineNumber`

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#41925]
* latest (macOS)
* open a file
* remove all text
* save

=>

```
 ERR Illegal value 0 for `lineNumber`: Error: Illegal value 0 for `lineNumber`
    at TextModel.getLineContent (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModel.js:558:23)
    at TrimFinalNewLinesParticipant.doTrimFinalNewLines (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/electron-browser/mainThreadSaveParticipant.js:129:37)
    at TrimFinalNewLinesParticipant.participate (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/electron-browser/mainThreadSaveParticipant.js:110:22)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/electron-browser/mainThreadSaveParticipant.js:261:46
    at next (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:338:46)
    at thenHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:346:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by raulesgalindo** [comment]
I can't replicate the bug on linux. It didn't show any error output on console.

**Comment by alexandrudima** [comment]
To reproduce, it is necessary to use `"files.trimFinalNewlines": true`.
