### ISSUE TITLE
yarn --arch=armhf fails for 1.19.2 checkout

### ISSUE THREAD

**Issue by couven92** [Microsoft/vscode#42046]
When running `yarn` to during cross-platform build for ARM, `yarn` fails with the following error message:

> arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-m64’

```
user@localhost:~/Documents/Source/GitHub/Microsoft-vscode$ yarn --arch=armhf
yarn install v1.3.2
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.8: The platform "linux" is incompatible with this module.
info "vscode-fsevents@0.3.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-foreground-love@0.1.0: The platform "linux" is incompatible with this module.
info "windows-foreground-love@0.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.2.0: The platform "linux" is incompatible with this module.
info "windows-mutex@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.1.6: The platform "linux" is incompatible with this module.
info "windows-process-tree@0.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/12] ⠠ gc-signals: CXX(target) Release/obj.target/gcsignals/src/gcsignal.o
[6/12] ⠠ node-pty: https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
[3/12] ⠠ keytar: gyp info spawn args   '-Goutput_dir=.' ]
[4/12] ⠐ native-keymap: gyp info spawn args   '-Goutput_dir=.' ]
error /home/user/Documents/Source/GitHub/Microsoft-vscode/node_modules/gc-signals: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/user/Documents/Source/GitHub/Microsoft-vscode/node_modules/gc-signals
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp http GET https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/opt/node-v8.9.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Documents/Source/GitHub/Microsoft-vscode/node_modules/gc-signals/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/node-v8.9.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.node-gyp/iojs-1.7.9/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.node-gyp/iojs-1.7.9',
gyp info spawn args   '-Dnode_gyp_dir=/opt/node-v8.9.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.node-gyp/iojs-1.7.9/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/Documents/Source/GitHub/Microsoft-vscode/node_modules/gc-signals',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/Documents/Source/GitHub/Microsoft-vscode/node_modules/gc-signals/build'
  CXX(target) Release/obj.target/gcsignals/src/gcsignal.o
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-m64’
make: *** [Release/obj.target/gcsignals/src/gcsignal.o] Error 1
gcsignals.target.mk:92: recipe for target 'Release/obj.target/gcsignals/src/gcsignal.o' failed
make: Leaving directory '/home/user/Documents/Source/GitHub/Microsoft-vscode/node_modules/gc-signals/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v8.9.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-31-generic
gyp ERR! command "/opt/node-v8.9.4-linux-x64/bin/node" "/opt/node-v8.9.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Documents/Source/GitHub/Microsoft-vscode/node_modules/gc-signals
```

- VSCode Version: `1.19.2`
- OS Version: Ubuntu xenial 16.04.3 LTS

Steps to Reproduce: (as described in [Cross Compiling for Debian Based Linux](https://github.com/Microsoft/vscode/wiki/Cross-Compiling-for-Debian-Based-Linux))

1. `git checkout tags/1.19.2`
1. `sudo qemu-debootstrap --arch=armhf --variant=minbase jessie rootfs`
1. `sudo chroot rootfs apt install --yes --allow-unauthenticated libx11-dev`
1. `export CC=$(which arm-linux-gnueabihf-gcc)`
1. `export CXX="$(which arm-linux-gnueabihf-g++) -L$(pwd)/rootfs/usr/lib/arm-linux-gnueabihf/"`
1. `yarn --arch=armhf`

This makes it impossible to create a VS Code ARM package.

The cross-platform-compiler complains about an unrecognized `-m64` option. Appearently it tries to compile for x64 which might be the issue.

**Comment by Tyriar** [comment]
The cross compile docs was a community contribution, we never really officially supported it or building for arm in general. We'd love to get some help with this though. Duplicate https://github.com/Microsoft/vscode/issues/6442
