### ISSUE TITLE
PieceTreeBase.appendToNode : RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42111]
I had a very large file (100k lines) and copied all and then pasted all:

```
ERR Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at PieceTreeBase.appendToNode (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.js:760:53)
    at PieceTreeBase.insert (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.js:362:26)
    at PieceTreeTextBuffer._doApplyEdits (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.js:315:37)
    at PieceTreeTextBuffer.applyEdits (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.js:211:39)
    at TextModel._applyEdits (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModel.js:902:39)
    at TextModel.applyEdits (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModel.js:860:29)
    at EditStack.pushEditOperation (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/editStack.js:39:40)
    at TextModel._pushEditOperations (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModel.js:854:41)
    at TextModel.pushEditOperations (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModel.js:783:29)
    at Function.CommandExecutor._innerExecuteCommands (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/controller/cursor.js:479:45)
```

**Comment by bpasero** [comment]
[Game.ts.zip](https://github.com/Microsoft/vscode/files/1660998/Game.ts.zip)

**Comment by rebornix** [comment]
@bpasero thanks, I like large files.
