### ISSUE TITLE
Code Segfaults on Linux

### ISSUE THREAD

**Issue by lawliet89** [Microsoft/vscode#42186]
- VSCode Version: 1.19.3
- OS Version: Ubuntu 17.10 `4.13.0-31-generic #34-Ubuntu SMP Fri Jan 19 16:34:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Steps to Reproduce:

1. Launch code.
2. VSCode crashed without a word. It basically segfaults.

It didn't happen until I updated to 1.19.3.

Does this issue occur when all extensions are disabled?: Yes

I have attached the stacktrace from the [native crash](https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#linux) debugging page.

```
#0  0x00000000019c79f3 in ?? ()
#1  0x0000000003fedb85 in __start_google_malloc ()
#2  0x0000000001a29e05 in calloc ()
#3  0x00007f3478a7b5d1 in g_malloc0 () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f347b6a34c9 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f347b6a8855 in g_type_register_static () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f347b6a8af5 in g_type_register_static_simple () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f347c839e04 in gdk_display_get_type () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#8  0x00007f347c83ad00 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#9  0x00007f347b6a61c9 in g_type_class_ref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f347b68bd98 in g_object_new_with_properties () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f347b68c801 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f347c83af75 in gdk_display_manager_get () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#13 0x00007f347cc17954 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x00007f347cbfdf28 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#15 0x00007f3478a81fdf in g_option_context_parse () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f347cbfe538 in gtk_parse_args () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#17 0x00007f347cbfe5b9 in gtk_init () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#18 0x000000000284c7c6 in ?? ()
#19 0x00000000028458ff in ?? ()
#20 0x0000000002848376 in ?? ()
#21 0x0000000003fbff7b in brightray::BrowserMainParts::PreEarlyInitialization() ()
#22 0x0000000003e59059 in atom::AtomBrowserMainParts::PreEarlyInitialization() ()
#23 0x0000000002a2afc5 in ?? ()
#24 0x0000000002bb368e in ?? ()
#25 0x0000000002cde7e8 in ?? ()
#26 0x0000000002862e7c in ?? ()
#27 0x00000000028632d0 in ?? ()
#28 0x0000000003e50658 in main ()
```

**Comment by lawliet89** [comment]
This is really strange. I don't know what happened, but once I rebooted the machine, it seems to work again. Not sure what is going on.

Going to close this issue for now.
