### ISSUE TITLE
Error: No extension gallery service configured.

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#42204]
I see this error in my console when I run VS code out of sources

  ERR No extension gallery service configured.: Error: No extension gallery service configured.
    at ExtensionGalleryService.query (file:///Users/sandy081/work/vscode/out/vs/platform/extensionManagement/node/extensionGalleryService.js:283:56)
    at ExtensionTipsService.processWorkspaceRecommendations (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/extensions/electron-browser/extensionTipsService.js:111:45)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/parts/extensions/electron-browser/extensionTipsService.js:91:57
    at Object.notifySuccess [as _notify] (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.derive._creator._run (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.derive._creator._completed (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at Object.notifySuccess [as _notify] (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._run (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)

**Comment by monokrome** [comment]
Why was this closed? I'm having the same issue

**Comment by ramya-rao-a** [comment]
@monokrome Do you have the same issue in the latest Insiders?

**Comment by Passw** [comment]
```
ONSOLE(85)] "No extension gallery service configured.: Error: No extension gallery service configured.
```

still have this issue with the latest master branch

**Comment by ramya-rao-a** [comment]
@Passw Please paste the complete call stack

**Comment by Passw** [comment]
@ramya-rao-a  Thanks for your reply.

Since I build and compile **vscode** from the ***master*** branch, it seems that the extensions manager is disabled by default.
I have done workaround to enable the extensions managerment according to https://github.com/Microsoft/vscode/issues/2647#issuecomment-269403183

More detail reference https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005
