### ISSUE TITLE
node_modules/vscode-ripgrep/bin/rg ENOENT

### ISSUE THREAD

**Issue by aliev** [Microsoft/vscode#42219]
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1225   ERR spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg ENOENT: Error: spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg ENOENT,    at exports._errnoException (util.js:1050:11),    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32),    at onErrorNT (internal/child_process.js:367:16),    at _combinedTickCallback (internal/process/next_tick.js:80:11),    at process._tickCallback (internal/process/next_tick.js:104:9)
```

- VSCode Version: 1.19.2
- OS Version: OSX 10.13.3

**Comment by roblourens** [comment]
Can you tell me whether a file exists there at `/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg`? And what are the file attributes (`ls -l '/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg'`)?

**Comment by aliev** [comment]
@roblourens 

```
➜  server git:(feature/SS-1529) ✗ ls -l /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
-rwxr-xr-x@ 1 aliev  staff  2469424 Jan 10 08:08 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
➜  server git:(feature/SS-1529) ✗
```

**Comment by roblourens** [comment]
When do you see that error? Does cmd+p work? Does text search work?

**Comment by aliev** [comment]
When I'm trying to use cmp+p search I see error:

<img width="1366" alt="screen shot 2018-01-27 at 12 26 26 am" src="https://user-images.githubusercontent.com/407134/35459259-c72e0372-02f8-11e8-970e-dbfb0842026f.png">

Text search works. Also search (Shift+CMD+F works)

Go to symbol works but shows the same error.

**Comment by roblourens** [comment]
@chrmarti ?

**Comment by martingronlund** [comment]
+1 also having this since a week or two

**Comment by jasonlfunk** [comment]
I am also having this issue.

```
ls -l /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
-rwxr-xr-x@ 1 jasonlfunk  staff  2469440 Jan 25 02:52 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
```

**Comment by yaronlevi** [comment]
+1 For having this problem

**Comment by roblourens** [comment]
Did it just show up after the 1.19.3 update? Can you try reinstalling or, see whether it works in Insiders?

**Comment by roblourens** [comment]
And the binary itself seems to exist with the correct permissions. Please try just running it from the command line. `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg`

**Comment by jasonlfunk** [comment]
It just started happening recently, last few days. I am running 1.19.3. I don't know for sure if it was because of the update.

Running the command manually seems to work fine. (Though, at the moment, the error has went away for me. I can't get it to trigger.)

**Comment by triestpa** [comment]
This is happening to me too, but **only within multi-root workspaces**.  The `CMD-P` file search prompt is having trouble finding files and displays the `node_modules/vscode-ripgrep/bin/rg ENOENT` error whenever a file is opened using the `CMD-P` prompt.  If I open the project directory on its own (instead of opening code using the `.code-workspace` file), the error does not appear.
___
macOS High Sierra - 10.13.2 
VSCode - 1.19.3

**Comment by chrmarti** [comment]
Is anyone seeing this on another OS/version than High Sierra?

Since `ls -l` is showing an `@`, could everyone run it with `-@` to show extended attributes:
```
ls -l -@ /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
```

**Comment by martingronlund** [comment]
Using High Sierra
```
> ls -l -@ /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
-rwxr-xr-x  1 mg  staff  2469440 Jan 25 02:52 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
```

**Comment by jasonlfunk** [comment]
```
ls -l -@ /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
-rwxr-xr-x@ 1 jasonlfunk  staff  2469440 Jan 25 02:52 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
        com.apple.quarantine         57
```

Looks like we might have found the cause.

**Comment by chrmarti** [comment]
Does removing that attribute help?
```
sudo xattr -d com.apple.quarantine /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg
```

**Comment by hryanjones** [comment]
Just mentioning that I'm also getting this same problem with the same symptoms on Ubuntu 16.04:
- can `ls` that file and it seems to have appropriate permissions
- can run the file
- this only occurs when opening from a `.code-workspace` file
  - I'm just going to work-around by opening differently for now
- VSCode Version 1.19.3

**Comment by roblourens** [comment]
@hryanjones Does this affect quickopen (ctrl+p), or search (ctrl+shift+f) or both? (please check that it's getting results from all files, not just open ones)

**Comment by hryanjones** [comment]
Only affects quickopen, not search and 719 directories (excluding anything in soft links).
```bash
$ find src -type d | wc -l
719
```

**Comment by roblourens** [comment]
Thanks, I just meant, how many folders are in your code-workspace file? Because spawn a separate rg process for each one, and that's the only interesting difference between how quickopen and text search use rg that I can think of.

**Comment by hryanjones** [comment]
Ah, I hadn't actually inspected that file. When I did I found that there were 4 and also some of those folders no longer exist. When I deleted the ones that don't exist it now appears to be working fine.

**Comment by roblourens** [comment]
Oh, I can repro with a workspace folder that doesn't exist. I don't know why that gives ENOENT though.  Thanks!
