### ISSUE TITLE
NPE in TextFileEditorModel after switching language

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#42210]
- open the settings editor
- add the following
```
	"files.associations": {
		"foo.txt": "json"
	}
```
- make changes to the langage (json -> jsonc)
- dev tools console shows:
4log.js:199   ERR Cannot read property 'substr' of null: TypeError: Cannot read property 'substr' of null
    at TextFileEditorModel.BaseTextEditorModel.getFirstLineText (file:///home/aeschli/workspaces/vscode/out/vs/workbench/common/editor/textEditorModel.js:99:52)
    at TextFileEditorModel.updateTextEditorModelMode (file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:133:38)
    at TextFileEditorModel.onFilesAssociationChange (file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:127:18)
    at file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:67:107
    at Emitter.fire (file:///home/aeschli/workspaces/vscode/out/vs/base/common/event.js:104:38)
    at TextFileService.onFilesConfigurationChange (file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/textfile/common/textFileService.js:292:48)
    at file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/textfile/common/textFileService.js:103:27
    at Emitter.fire (file:///home/aeschli/workspaces/vscode/out/vs/base/common/event.js:104:38)
    at WorkspaceService.triggerConfigurationChange (file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/configuration/node/configurationService.js:534:48)
    at WorkspaceService.onUserConfigurationChanged (file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/configuration/node/configurationService.js:387:18)

`textSnapshot.read()` returns null.

**Comment by rebornix** [comment]
Can't remember which issue but I remember that we fixed this bug already. Verified with latest version as well.
