### ISSUE TITLE
Cannot read property getAssociatedPreferencesModel

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#42240]
Not reproducable, but I got this error after editing the user settings (added a setting). 

```
workbench.main.js:2913 Unable to open 'Workspace Settings': Cannot read property 'getAssociatedPreferencesModel' of null.: Error: Unable to open 'Workspace Settings': Cannot read property 'getAssociatedPreferencesModel' of null.
    at t.doHandleSetInputError (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4186:761)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4186:362
    at n.Class.derive._creator.then (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:146:770)
    at t.doSetInput (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4186:124)
    at t.doOpenEditor (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4184:617)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4183:736)
    at e.doOpenEditor (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3195:443)
    at e.openEditor (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3194:916)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3638:838
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:140:868)
```

**Comment by sandy081** [comment]
Yah... hard to reproduce.. but from code I see this can happen.
