### ISSUE TITLE
code-insiders no longer starts after update to version 1.20.0-1517293131

### ISSUE THREAD

**Issue by glaure** [Microsoft/vscode#42394]
After todays update visual studio code no longer starts.
It worked with the previous version. code-insiders_1.20.0-1517206683_amd64.deb 

- VSCode Version: 1.20.0-1517293131
- OS Version: Ubuntu 17.10

Steps to Reproduce:
1. Install current version : code-insiders_1.20.0-1517293131_amd64.deb  
2. Just start code-insiders from shell

**Output:**
code-insiders --disable-extensions
{ errorCode: 'load',
  moduleId: 'iconv-lite',
  neededBy: [ 'vs/base/node/encoding', 'vs/code/node/cli' ],
  detail: 
   { Error: Cannot find module 'iconv-lite'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:911)
       at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:465)
       at s (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:811)
       at Object.errorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:1003)
       at e.triggerErrorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:826)
       at /usr/share/code-insiders/resources/app/out/vs/loader.js:13:535 code: 'MODULE_NOT_FOUND' } }
{ errorCode: 'load',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ],
  detail: 
   { Error: Cannot find module 'minimist'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:911)
       at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:465)
       at s (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:811)
       at Object.errorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:1003)
       at e.triggerErrorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:826)
       at /usr/share/code-insiders/resources/app/out/vs/loader.js:13:535 code: 'MODULE_NOT_FOUND' } }

Does this issue occur when all extensions are disabled?: 
Yes!

**Comment by glaure** [comment]
Related to https://github.com/Microsoft/vscode/issues/42393
