### ISSUE TITLE
Error: Cant modify splitview"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42403]
Saw this in my "running out of sources" logs, not sure what I did though, I might have clicked on multiple repositories in the SCM view. However the stack seems to originate from the explorer:

```
"[uncaught exception]: Error: Cant modify splitview", source: file:///Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/bootstrap/index.js (39)
[19214:0130/100528.556469:INFO:CONSOLE(42)] "Error: Cant modify splitview
    at SplitView.resizeView (file:///Users/bpasero/Development/monaco/out/vs/base/browser/ui/splitview/splitview.js:189:23)
    at PanelView.resizePanel (file:///Users/bpasero/Development/monaco/out/vs/base/browser/ui/splitview/panelview.js:308:28)
    at ExplorerViewlet.PanelViewlet.resizePanel (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/views/panelViewlet.js:262:28)
    at ExplorerViewlet.ViewsViewlet.resizePanels (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:434:26)
    at ExplorerViewlet.ViewsViewlet.layout (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:317:22)
    at SidebarPart.CompositePart.layout (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/compositePart.js:383:38)
    at SidebarPart.layout (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:93:44)
    at WorkbenchLayout.layout (file:///Users/bpasero/Development/monaco/out/vs/workbench/browser/layout.js:549:26)
    at Workbench.layout (file:///Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/workbench.js:678:38)
    at WorkbenchShell.layout (file:///Users/bpasero/Development/monaco/out/vs/workbench/electron-browser/shell.js:303:28)"
```

**Comment by joaomoreno** [comment]
This comes from the ViewsViewlet. It happens when you try to modify the splitview in the middle of an ongoing modification.

**Comment by sandy081** [comment]
@joaomoreno Is it possible to queue these modifications in Split view?

**Comment by joaomoreno** [comment]
I think so, but I would not be so happy about it. Especially because that would mean that once the calls return, you don't know whether the change was applied or not.

**Comment by sandy081** [comment]
You mean to queue them in ViewsViewlet?

**Comment by joaomoreno** [comment]
I mean, look into how is it possible that there are nested calls. Usually it happens when you `addView` and then call `addView` again somewhere inside the `render` method of the first view. That shouldn't happen at all.

**Comment by sandy081** [comment]
It seems this cannot happen with new refactorings from @joaomoreno in Splitview. Hence closing this.
