### ISSUE TITLE
Windows update - install loop

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#42433]
Looks like I´m getting into an install loop. As soon as an update is available the badge indicates that there is a new update available.

![image](https://user-images.githubusercontent.com/172399/35563031-ae890fc8-05b5-11e8-8b54-ededcfa2af1f.png)

The Main log shows an exception during updating the state:
```
[2018-01-30 10:31:38.865] [main] [info] update#setState idle
[2018-01-30 10:32:08.871] [main] [info] update#setState checking for updates
[2018-01-30 10:32:09.944] [main] [info] update#setState downloading
[2018-01-30 10:32:09.955] [main] [info] update#setState downloaded
[2018-01-30 10:32:49.125] [main] [info] update#setState updating
[2018-01-30 10:34:30.988] [main] [info] update#setState ready
[2018-01-30 11:30:51.911] [main] [info] update#setState idle
[2018-01-30 11:31:21.955] [main] [info] update#setState checking for updates
[2018-01-30 11:31:23.079] [main] [info] update#setState downloading
[2018-01-30 11:31:48.278] [main] [info] update#setState downloaded
[2018-01-30 11:34:25.654] [main] [info] update#setState updating
[2018-01-30 11:35:26.964] [main] [info] update#setState ready
[2018-01-30 11:37:18.513] [main] [info] update#setState idle
[2018-01-30 11:37:48.517] [main] [info] update#setState checking for updates
[2018-01-30 11:37:49.621] [main] [info] update#setState downloading
[2018-01-30 11:37:49.642] [main] [info] update#setState downloaded
[2018-01-30 11:49:46.121] [main] [info] update#setState updating
[2018-01-30 11:50:33.132] [main] [error] [uncaught exception in main]: Error: Cannot read property 'indexOf' of null

TypeError: Cannot read property 'indexOf' of null
    at d (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:155:770)
    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:156:599)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[2018-01-30 11:50:33.132] [main] [error] Error: Cannot read property 'indexOf' of null

TypeError: Cannot read property 'indexOf' of null
    at d (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:155:770)
    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:156:599)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:90:585)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2018-01-30 11:51:22.463] [main] [info] update#setState ready
[2018-01-30 11:53:20.028] [main] [info] update#setState idle
[2018-01-30 11:53:50.144] [main] [info] update#setState checking for updates
[2018-01-30 11:53:51.350] [main] [info] update#setState downloading
[2018-01-30 11:53:51.360] [main] [info] update#setState downloaded
[2018-01-30 11:54:01.909] [main] [info] update#setState updating
[2018-01-30 11:58:24.973] [main] [info] update#setState ready
[2018-01-30 11:59:19.331] [main] [info] update#setState idle
[2018-01-30 11:59:49.334] [main] [info] update#setState checking for updates
[2018-01-30 11:59:50.076] [main] [info] update#setState downloading
[2018-01-30 11:59:50.083] [main] [info] update#setState downloaded
[2018-01-30 12:00:07.427] [main] [info] update#setState updating
[2018-01-30 12:01:04.628] [main] [info] update#setState ready
[2018-01-30 12:01:22.783] [main] [info] update#setState idle
[2018-01-30 12:01:52.787] [main] [info] update#setState checking for updates
[2018-01-30 12:01:53.536] [main] [info] update#setState downloading
[2018-01-30 12:01:53.542] [main] [info] update#setState downloaded
```

**Comment by joaomoreno** [comment]
We're enabling this only for insiders, so moving to February.

**Comment by joaomoreno** [comment]
@egamma If update has been working fine for you, just mark it as verified.
