### ISSUE TITLE
Promise rejection for fetching translation.

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#42525]
Re #42366
```
[transifex] Fetching /api/2/project/vscode-extensions/resource/vscode-chrome-debug/translation/hu?file&mode=onlyreviewed
[transifex] Fetching /api/2/project/vscode-extensions/resource/vscode-node-debug/translation/hu?file&mode=onlyreviewed
[transifex] Fetching /api/2/project/vscode-extensions/resource/vscode-node-debug2/translation/hu?file&mode=onlyreviewed
(node:14438) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'forEach' of undefined
(node:14438) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: TypeError: Cannot read property 'forEach' of undefined
```

I tried to download translation files for `hu`, but ran into this exception every time, after fetching `vscode-node-debug2/translation`.

**Comment by RMacfarlane** [comment]
I'm seeing the same thing.
```
[transifex] Fetching /api/2/project/vscode-extensions/resource/vscode-node-debug2/translation/sv?file&mode=onlyreviewed
(node:7562) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at /Users/ramacfar/dev/vscode/build/lib/i18n.js:245:32
    at Array.forEach (<anonymous>)
    at /Users/ramacfar/dev/vscode/build/lib/i18n.js:231:27
    at Parser.<anonymous> (/Users/ramacfar/dev/vscode/build/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:160:13)
    at SAXParser.onclosetag (/Users/ramacfar/dev/vscode/build/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/Users/ramacfar/dev/vscode/build/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/ramacfar/dev/vscode/build/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/ramacfar/dev/vscode/build/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/ramacfar/dev/vscode/build/node_modules/sax/lib/sax.js:1436:13)
```
