### ISSUE TITLE
Cannot read property 'provideDecoration' of undefined

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42602]
### Issue Type
Bug

### Description

I was testing #42195 (the workspace folder API):

TypeError: Cannot read property 'provideDecoration' of undefined
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:534:586
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:524
	at new n.Class.derive._oncancel (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:75:657)
	at Object.t.asWinJsPromise (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:487)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:534:551
	at Array.map (native)
	at e.$provideDecorations (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:534:475)
	at e._doInvokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:579:983)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:579:701)
	at e._receiveRequest (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:578:836)

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8adf87c03d78597e385ef787e8fb1ef564f8995b, 2018-01-31T06:18:41.654Z)
OS version: Linux x64 3.13.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2194)|
|Load (avg)|0, 0, 0|
|Memory (System)|3.86GB (0.17GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --enable-proposed-api|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces only with extensions

**Comment by jrieken** [comment]
@chrmarti Did you by any change cause an extension host reload with adding/removing folders?

**Comment by chrmarti** [comment]
No, I was rotating folders 1..n-1.

**Comment by jrieken** [comment]
Thanks

**Comment by chrmarti** [comment]
Pushed it here, in case you need to reproduce it: https://github.com/chrmarti/test42195.git
