### ISSUE TITLE
Cannot read property 'resource' of undefined

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#42626]
### Issue Type
Bug

### Description

Testing #42195

Found after doing many individual renames on the workspace folders:

  ERR Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
    at Function.e.mergeLocalWithDisk (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2348:409)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4433:577
    at Array.forEach (native)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4433:537
    at Object.g [as _notify] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:140:868)
    at Object.enter (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:144:153)
    at n.Class.derive._oncancel._run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:145:970)
    at n.Class.derive._oncancel._completed (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:145:411)
    at l (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:148:888)
    at j.then.o.(anonymous function) (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:149:78)

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (010de7da99e63841dfe5bc5a45ce1509f9fd1479, 2018-01-31T09:45:32.303Z)
OS version: Linux x64 3.13.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2194)|
|Load (avg)|1, 1, 0|
|Memory (System)|3.86GB (0.29GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces only with extensions

**Comment by bpasero** [comment]
Seems to originate from the explorer: `mergeLocalWithDisk`

**Comment by isidorn** [comment]
All I can do is null guard for this. Which is what I just did

**Comment by bpasero** [comment]
@isidorn is that a smart fix? shouldn't you check where on the calling side you can get a NULL for the stat?

**Comment by isidorn** [comment]
@bpasero thanks. I have addressed your concern via 45e95c62f6

**Comment by bpasero** [comment]
@isidorn great thanks
