### ISSUE TITLE
Language pack generation fails if path ends in \

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42623]
Ran `npm run update-localization-extension ..\vscode-language-pack-bg\` and it produced:

```
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat 'P:\mseng\VSCode\vscode-language-pack-bg"'
    at Object.fs.statSync (fs.js:948:11)
    at update (P:\mseng\VSCode\vscode\build\npm\update-localization-extension.js:24:22)
    at Object.<anonymous> (P:\mseng\VSCode\vscode\build\npm\update-localization-extension.js:69:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```

Running `npm run update-localization-extension ..\vscode-language-pack-bg` work fine

**Comment by aeschli** [comment]
This works on linux: `npm run update-localization-extension ../vscode-language-pack-hu/`

Looks like a windows problem. Discussed with @dbaeumer and we will not bother to fix it
