### ISSUE TITLE
VS Code 1.20.0 wont launch on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by jhony1104** [Microsoft/vscode#43506]
- VSCode Version: 1.20.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Download the .app file
2. Double click it

VS Code wont launch. The icon appears in the dock, but vanishes shortly after.

**Comment by octref** [comment]
Can you follow this guide and post the crash log?

https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#macos

**Comment by octref** [comment]
Also, try running `code --disable-gpu`.

**Comment by jhony1104** [comment]
I don't see a crash log entry for code following that guide. Running `code --disable-gpu` is also not working, what is not surprising since i'm using a Mac mini (Late 2012) with no dedicated gpu.

Running `Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose` I get:
```sh
[main 10:48:52] Error: listen ENOTSUP /Network/Servers/intranet.company/Volumes/Macintosh HD2/NetUsers/jhony1104/Library/Application Support/Code/1.20.0-main.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1247:19)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1413:5)
    at /Network/Servers/intranet.company/Volumes/Macintosh HD2/NetUsers/jhony1104/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:154:456
    at new n.Class.derive._oncancel (/Network/Servers/intranet.company/Volumes/Macintosh HD2/NetUsers/jhony1104/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:81:234)
    at Object.t.serve (/Network/Servers/intranet.company/Volumes/Macintosh HD2/NetUsers/jhony1104/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:154:386)
    at n (/Network/Servers/intranet.company/Volumes/Macintosh HD2/NetUsers/jhony1104/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:443:882)
    at J (/Network/Servers/intranet.company/Volumes/Macintosh HD2/NetUsers/jhony1104/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:446:235)
```

**Comment by bpasero** [comment]
Moving to @joaomoreno since this seems to ail setting up a socket.

**Comment by joaomoreno** [comment]
You seem to be running off a network share `/Network/Servers...`

Try using `--user-data-dir LOCAL_PATH`.

**Comment by jhony1104** [comment]
With `--user-data-dir LOCAL_PATH` code works.

Is there any way to use this solution when starting from the dock?

**Comment by joaomoreno** [comment]
There isn't unfortunately. You're going to have to write a shortcut in order to do that.
