### ISSUE TITLE
docker-compose fails when running in integrated terminal

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#43532]
from: https://github.com/Microsoft/vscode-docker/issues/212, see https://github.com/Microsoft/vscode-docker/issues/212#issuecomment-364928473 specifically.

Windows
Insiders: 1.21.0
Docker, Docker Compose versions:

![image](https://user-images.githubusercontent.com/1487073/36116234-6809b4b4-0fea-11e8-99aa-62f270b2214f.png)

Create a `docker-compose.yml` file:

``` yml
version: '3'

services:
  redis:
    image: "redis:alpine"
```

Then run:
``` bash
docker compose -f docker-compose.yml up -d --build
```

Results:

``` console
D:\src\stickerapp>docker-compose -f docker-compose.1.yml up -d --build
Pulling redis (redis:alpine)...
alpine: Pulling from library/redis
ff3a5c916c92: Extracting [=====================>                             ]  884.7kB/2.066MB
aae70a2e6027: Download complete
87c655da471c: Download complete
a0bd51ac7350: Waiting
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 959, in up
  File "compose\project.py", line 452, in up
  File "compose\service.py", line 318, in ensure_image_exists
  File "compose\service.py", line 1081, in pull
  File "compose\progress_stream.py", line 44, in stream_output
  File "compose\progress_stream.py", line 63, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

When running from the normal command prompt (`cmd.exe`) it works fine.

To clean up after a successful run, so as to repeat the process:

``` bash
docker compose -f docker-compose.yml down
docker rmi redis:alpine
```

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36630
