### ISSUE TITLE
dotnet core compilation with ncurses 6.1

### ISSUE THREAD

**Issue by b0wter** [Microsoft/vscode#43539]
- VSCode Version: 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:10:15.949Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: openSUSE Tumbleweed 
ncurses 6.1-1.1 
dotnet 2.1.4

Steps to Reproduce:

1. use the dotnet command to create a new project (e.g. dotnet new console -n test).
2. open the project in vs code and try to build it

=> Build will crash immediately with the following exception:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.InvalidOperationException: The terminfo database is invalid.
   at System.TermInfo.Database..ctor(String term, Byte[] data)
   at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
   at System.TermInfo.Database.ReadDatabase(String term)
   at System.TermInfo.Database.ReadActiveDatabase()
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.ConsolePal.EnsureInitializedCore()
   at System.ConsolePal.ControlCHandlerRegistrar.Register()
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 526

Unhandled Exception: System.InvalidOperationException: The terminfo database is invalid.
   at System.TermInfo.Database..ctor(String term, Byte[] data)
   at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
   at System.TermInfo.Database.ReadDatabase(String term)
   at System.TermInfo.Database.ReadActiveDatabase()
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.ConsolePal.EnsureInitializedCore()
   at System.ConsolePal.ControlCHandlerRegistrar.Register()
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 748
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 215
```

This might be related with https://github.com/dotnet/corefx/issues/26966

However, using the dotnet command in a regular terminal causes no problems at all (which is what the original reporter stated (running dotnet restore crashes in the terminal).

Does this issue occur when all extensions are disabled?: N/A

Cannot run this without the c#/dotnet core extensions.

**Comment by Tyriar** [comment]
It looks like https://github.com/dotnet/corefx/issues/26966 has issues with certain terminals, let's track it there until that discussion is resolved.

**Comment by jogleasonjr** [comment]
Is there a way to specify a terminal as an argument to vscode when launching? Without wanting to set TERM in something like ~/.bashrc, as a workaround I've changed the default shell [here](https://github.com/jogleasonjr/vscode/commit/3ec3e62f3d82ce21141ccf14f1dd69d9ed24c70c#diff-dc09948028c646a458fac5f5b5d32276).

**Comment by Tyriar** [comment]
@jogleasonjr you can set the shell and its arguments using `terminal.integrated.<os>.shell` and `terminal.integrated.<os>.shellArgs`. Changing `$TERM` could break stuff, there is no nicer way to do that AFAIK (I don't think the `.env` setting will allow that to be set).

**Comment by jogleasonjr** [comment]
@Tyriar yes I wouldn't want to change `$TERM` for anything non-experimental. It seems to me that the integrated terminal's configuration does not affect the one that invokes `dotnet build` from `tasks.json`.

For example setting an alternative shell using `terminal.integrated.linux.shell` (or just typing `TERM=something_else` in the integrated terminal on vscode launch) will fix the build errors in the terminal but not in a debug task.

Launching and attaching still work thankfully, so it seems to me that the best workaround for the moment is to comment out `preLaunchTask` in 'launch.json` and just build outside of the editor like the good 'ol days.

**Comment by Tyriar** [comment]
I think tasks take control of the shell as otherwise tasks.json would not be portable (eg. things that run in WSL don't run in cmd)

**Comment by jogleasonjr** [comment]
One way I found to do that in tasks.json is by setting the environment variable in the `command` property before the usual `dotnet build`:

    "tasks": [
     {
        "label": "build",
        "command": "dotnet build",
        "linux": {
            "command": "env TERM=rxvt-unicode-256color dotnet build"
        },
       ...
      }
    ]

Setting TERM in `tasks.linux.options.env: { }` didn't seem to take affect, nor did the user setting `terminal.integrated.env.linux: { }`. 

So the above workaround, as ill-advised as it may be in many cases, seems to work for now until [this update](https://github.com/dotnet/corefx/pull/27109) propagates its way to vscode and the arch repos. It will allow for one click (or F5 key) build/debugging.
