### ISSUE TITLE
Integrated Terminal (Powershell 1.0) - Issue with docker-compose

### ISSUE THREAD

**Issue by Burnett01** [Microsoft/vscode#43576]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open the integrated terminal (Powershell 1.0)
2. Run a docker container by using ``docker-compose up``
2. Get this error:

``database_1  | Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 975, in up
  File "compose\cli\log_printer.py", line 105, in run
  File "compose\cli\log_printer.py", line 109, in write
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose``

It was already mentioned in #39926 and I'm surprised @isidorn simply tagged it as "*caused by extension*" whereas this isn't true. If I use the command with that standalone powershell app, it works. VScode integrated terminal though seems to have an issue with it.

Does this issue occur when all extensions are disabled?:  Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36630, it's a Windows issue unfortunately.

**Comment by Burnett01** [comment]
@Tyriar Thank you for your reply. Now I definitely know it's not an extension that's causing this but the OS.
