### ISSUE TITLE
JSON server doesn't work

### ISSUE THREAD

**Issue by fmagrosoto** [Microsoft/vscode#43679]
### Issue Type
Bug

### Description

Error: EIO: i/o error, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:509:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
[Info  - 10:37:20] Connection to server got closed. Server will restart.
fs.js:682
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EIO: i/o error, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:509:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
[Info  - 10:37:24] Connection to server got closed. Server will restart.
fs.js:682
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EIO: i/o error, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:509:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
[Info  - 10:37:27] Connection to server got closed. Server will restart.
fs.js:682
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EIO: i/o error, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:509:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
[Error - 10:37:30] Connection to server got closed. Server will not be restarted.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.13.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2394)|
|Load (avg)|3, 3, 2|
|Memory (System)|7.70GB (3.23GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.0
vscode-standardjs|che|1.2.1
tslint|eg2|1.0.27
vscode-npm-script|eg2|0.3.3
php-intellisense|fel|2.2.7
team|ms-|1.122.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
vscode-todo-highlight|way|0.5.11

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by aeschli** [comment]
Please add more details. What are the steps?
Where do you see this message? Dev tools? HTML language server output view?

**Comment by fmagrosoto** [comment]
Ok, sorry.
That happens when I try to open a JSON file in the editor.
When the file opens is when the error triggers.
I don´t use VSCODE in dev tools mode.

**Comment by aeschli** [comment]
Just open the Dev tools (Help > Toggle Developper Tools) and check if there is something in the Dev tools console.
Where do you see the error messages? Can you add a screenshot?

**Comment by fmagrosoto** [comment]
Thanks.
I attach a screen capture.
There is an error in develper tools.
And only happens when a JSON file is open.

2018-02-15 15:06 GMT-06:00 Martin Aeschlimann <notifications@github.com>:

**Comment by aeschli** [comment]
@fmagrosoto If you have a screenshot that would be great.
