### ISSUE TITLE
this.commitInputBox.layout is not a function: TypeError: this.commitInputBox.layout is not a function

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#437]
Found this when switching to git viewlet and the result was an empty viewlet:

			[8037:1121/090324:INFO:CONSOLE(309)] "this.commitInputBox.layout is not a function: TypeError: this.commitInputBox.layout is not a function
			    at ChangesView.layout (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/git/browser/views/changes/changesView.js:123:33)
			    at GitViewlet.layout (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/git/browser/gitViewlet.js:109:34)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:235:33
			    at CompletePromise_then [as then] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1826:49)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:228:49
			    at CompletePromise_ctor.CompletePromise_then [as then] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1826:49)
			    at SidebarPart.showViewlet (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:190:41)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:109:34
			    at Object.notifySuccess [as _notify] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1440:59)
			    at Object.state_success_notify.enter (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1127:30)", source: file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js (309)
			[8037:1121/090324:INFO:CONSOLE(309)] "this.commitInputBox.layout is not a function: TypeError: this.commitInputBox.layout is not a function
			    at ChangesView.layout (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/git/browser/views/changes/changesView.js:123:33)
			    at Array.<anonymous> (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/git/browser/views/changes/changesView.js:108:109)
			    at InputBox.EventEmitter._emitToSpecificTypeListeners (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/eventEmitter.js:177:37)
			    at InputBox.EventEmitter._emitEvents (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/eventEmitter.js:202:22)
			    at InputBox.EventEmitter.emit (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/eventEmitter.js:219:22)
			    at InputBox.adjustHeight (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/inputbox/inputBox.js:245:18)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/inputbox/inputBox.js:67:51", source: file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js (309)
			[8037:1121/090327:INFO:CONSOLE(309)] "this.commitInputBox.layout is not a function: TypeError: this.commitInputBox.layout is not a function
			    at ChangesView.layout (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/git/browser/views/changes/changesView.js:123:33)
			    at GitViewlet.layout (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/git/browser/gitViewlet.js:109:34)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:235:33
			    at CompletePromise_then [as then] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1826:49)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:228:49
			    at CompletePromise_ctor.CompletePromise_then [as then] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1826:49)
			    at SidebarPart.showViewlet (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:190:41)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:109:34
			    at CompletePromise_ctor.CompletePromise_then [as then] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1826:49)
			    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:93:54", source: file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js (309)

**Comment by joaomoreno** [comment]
Bad compilation. :-1:

**Comment by bpasero** [comment]
:hamburger:
