### ISSUE TITLE
VSCode doesn't reopen opened files

### ISSUE THREAD

**Issue by quan1101** [Microsoft/vscode#43704]
### VSCode & OS info

- VSCode Version: 

    Version 1.20.0
    Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
    Date 2018-02-07T17:10:15.949Z
    Shell 1.7.9
    Renderer 58.0.3029.110
    Node 7.9.0
    Architecture x64

- OS Version: Ubuntu 16.04

### Steps to Reproduce:

1. Open VSCode by typing `code` in a terminal window.
2. Open a folder (File -> Open Folder).
3. Open a file from the File Explorer on the left.
4. Close the VSCode window by clicking the X button.
5. Reopen VSCode using `code` on a terminal window.

- **Expected result**: The opened file should be reopened.
- **Actual result**: The opened file is not reopened.

### User's preferences file:

```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 13,
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "python.pythonPath": "python3",
    "workbench.iconTheme": "vscode-icons",
    "workbench.startupEditor": "none",
    "workbench.colorTheme": "One Dark Pro",
    "window.menuBarVisibility": "default",
    "editor.minimap.enabled": false,
    "window.zoomLevel": 1,
    "vsicons.dontShowNewVersionMessage": true,
    "files.autoSave": "onFocusChange",
    "window.restoreWindows": "all",
    "files.hotExit": "onExitAndWindowClose",
    "window.restoreFullscreen": true,
    "workbench.list.openMode": "singleClick",
    "window.reopenFolders": "all",
}
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by quan1101** [comment]
@bpasero The issue doesn't occur with the insider version - VSCode reopens opened files normally.

**Comment by bpasero** [comment]
@quan1101 does it reproduce if you run "`code --user-data-dir <some folder>`" with the normal stable version?

**Comment by quantran13** [comment]
@bpasero No, if I run that VSCode reopens files normally. Do I need to use that every time?

**Comment by bpasero** [comment]
@quan1101 can you run again normally "code --verbose" and see if any output is printed to the terminal?

**Comment by quan1101** [comment]
@bpasero Yeah, there was a lot of stuff printed. I saw a lot of error messages on sqlite error - `database disk image is malformed`.

Here's the output.

```
[main 10:59:18 AM] Starting VS Code
[main 10:59:18 AM] from: /usr/share/code/resources/app
[main 10:59:18 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false }
[main 10:59:18 AM] Resolving machine identifier...
[main 10:59:18 AM] Resolved machine identifier: 7cc84baa162e72ccde6689329a87884eb92c32266f47a4e367198fbf86f22346
[main 10:59:18 AM] update#setState idle
[9025:0220/105920.931484:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105920.940853:ERROR:connection.cc(1954)] DOMStorageDatabase sqlite error 11, errno 0: database disk image is malformed, sql: SELECT * from ItemTable
[main 10:59:21 AM] IPC#vscode-workbenchLoaded
[9025:0220/105922.994938:INFO:CONSOLE(4183)] "Overwriting extension /usr/share/code/resources/app/extensions/ms-vscode.node-debug2 with /home/quan/.vscode/extensions/ms-vscode.node-debug2-1.20.1.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105922.996697:INFO:CONSOLE(4183)] "[/home/quan/.vscode/extensions/ms-python.python-2018.1.0]: Command `jupyter.runSelectionLine` appears multiple times in the `commands` section.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105922.997054:INFO:CONSOLE(4183)] "[/home/quan/.vscode/extensions/ms-python.python-2018.1.0]: Command `jupyter.execCurrentCell` appears multiple times in the `commands` section.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105922.997240:INFO:CONSOLE(4183)] "[/home/quan/.vscode/extensions/ms-python.python-2018.1.0]: Command `jupyter.execCurrentCellAndAdvance` appears multiple times in the `commands` section.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105922.997343:INFO:CONSOLE(4183)] "[/home/quan/.vscode/extensions/ms-python.python-2018.1.0]: Command `jupyter.gotToPreviousCell` appears multiple times in the `commands` section.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105922.997487:INFO:CONSOLE(4183)] "[/home/quan/.vscode/extensions/ms-python.python-2018.1.0]: Command `jupyter.gotToNextCell` appears multiple times in the `commands` section.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105922.997693:INFO:CONSOLE(4183)] "[/home/quan/.vscode/extensions/ms-vscode.cpptools-0.15.0]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105922.997815:INFO:CONSOLE(4183)] "[/home/quan/.vscode/extensions/ms-vscode.cpptools-0.15.0]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (4183)
[9025:0220/105923.046704:INFO:CONSOLE(227)] "Overwriting extension <<.html>> to now point to mime <<text/x-html>>", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (227)
[9025:0220/105923.046732:INFO:CONSOLE(227)] "Overwriting extension <<.htm>> to now point to mime <<text/x-html>>", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (227)
[main 10:59:23 AM] IPC#vscode:broadcast vscode:changeColorTheme {"id":"vs-dark vscode-theme-defaults-themes-dark_plus-json","background":"#1e1e1e"}
[9025:0220/105923.850482:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.850638:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.850737:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.850821:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.850884:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.850967:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851030:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851106:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851162:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851230:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851304:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851369:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851437:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851512:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851586:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851655:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851738:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851806:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851873:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.851947:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852014:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852088:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852157:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852226:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852296:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852368:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852471:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852529:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852600:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852688:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852850:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.852950:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853010:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853062:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853120:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853180:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853235:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853298:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853354:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853503:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853519:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853531:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853580:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853636:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853689:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853744:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853808:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853869:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.853921:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.854003:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.854035:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.877162:INFO:CONSOLE(253)] "%c[Extension Host] %cLooking for parseable documents... %c(at /home/quan/.vscode/extensions/Zignd.html-css-class-completion-1.17.1/out/src/extension.js:28:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105923.913493:INFO:CONSOLE(253)] "%c[Extension Host] %cvscode-icons is active! %c(at activate (/home/quan/.vscode/extensions/robertohuertasm.vscode-icons-7.20.0/out/src/index.js:41:13))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105923.930626:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.931707:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.932321:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105923.952088:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105924.130295:INFO:CONSOLE(1306)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105924.130434:INFO:CONSOLE(1306)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105924.149628:INFO:CONSOLE(253)] "%c[Extension Host] %cFound all parseable documents. %c(at /home/quan/.vscode/extensions/Zignd.html-css-class-completion-1.17.1/out/src/extension.js:35:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105924.149662:INFO:CONSOLE(253)] "%c[Extension Host] %cParsing documents and looking for CSS class definitions... %c(at /home/quan/.vscode/extensions/Zignd.html-css-class-completion-1.17.1/out/src/extension.js:40:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105925.033503:INFO:CONSOLE(253)] "%c[Extension Host] %cSummary: %c(at /home/quan/.vscode/extensions/Zignd.html-css-class-completion-1.17.1/out/src/extension.js:60:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105925.033620:INFO:CONSOLE(253)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105925.033637:INFO:CONSOLE(253)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105925.033701:INFO:CONSOLE(253)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105925.033834:INFO:CONSOLE(253)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105925.033868:INFO:CONSOLE(253)] "%c[Extension Host] %c %c(at /home/quan/.vscode/extensions/Zignd.html-css-class-completion-1.17.1/out/src/extension.js:65:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105925.622460:INFO:CONSOLE(253)] "%c[Extension Host] %cUnhandled Rejection at: Promise ", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105926.623654:INFO:CONSOLE(253)] "%c[Extension Host] %crejected promise not handled within 1 second %c(at Timeout._onTimeout (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:711:946))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105926.624326:INFO:CONSOLE(1306)] "%c  ERR", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[main 10:59:48 AM] update#checkForUpdates, state =  idle
[main 10:59:48 AM] update#setState checking for updates
[main 10:59:49 AM] update#setState idle
[9025:0220/105959.682961:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105959.715004:INFO:CONSOLE(1306)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1306)
[9025:0220/105959.716893:INFO:CONSOLE(253)] "%c[Extension Host] %cCongratulations, your extension "code-gnu-global" is now active! %c(at Console.originalConsole.(anonymous function) [as log] (/home/quan/.vscode/extensions/ms-vscode.cpptools-0.15.0/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105959.723593:INFO:CONSOLE(253)] "%c[Extension Host] %cactivating extension %c(at Console.originalConsole.(anonymous function) [as log] (/home/quan/.vscode/extensions/ms-vscode.cpptools-0.15.0/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[9025:0220/105959.737808:INFO:CONSOLE(253)] "%c[Extension Host] %cstarting language server %c(at Console.originalConsole.(anonymous function) [as log] (/home/quan/.vscode/extensions/ms-vscode.cpptools-0.15.0/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (253)
[main 11:00:09 AM] Lifecycle#window-before-close 1
[main 11:00:09 AM] Lifecycle#unload() 1
[main 11:00:09 AM] Lifecycle#window-before-close 1
[main 11:00:09 AM] Lifecycle#window-close 1
[main 11:00:09 AM] Lifecycle#window-all-closed
[main 11:00:09 AM] Lifecycle#before-quit
[main 11:00:10 AM] App#will-quit: disposing resources
[9025:0220/110010.088239:ERROR:connection.cc(1954)] DOMStorageDatabase sqlite error 11, errno 0: database disk image is malformed, sql: INSERT INTO ItemTable VALUES (?,?)
[9025:0220/110010.088279:ERROR:connection.cc(1954)] DOMStorageDatabase sqlite error 11, errno 0: database disk image is malformed, sql: INSERT INTO ItemTable VALUES (?,?)

```

**Comment by bpasero** [comment]
@quan1101 wow that is quite bad, I think all will be good when you delete this folder: `/home/<name>/.config/code/LocalStorage`

**Comment by quan1101** [comment]
@bpasero That works - I deleted the folder (which is actually `/home/<name>/.config/Code/Local\ Storage` f or me), and it works now. Thanks! 

Is there anything else I have to do to perhaps prevent this from happening in the future?

**Comment by bpasero** [comment]
@quan1101 no we plan on moving off that storage anyways. That is tracked in https://github.com/Microsoft/vscode/issues/18439
