### ISSUE TITLE
exception when installing extension locally

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4377]
I saw the install progress being stuck and found this on the console. I believe it was cause by me installing an extension from a vsix file.

```
Cannot read property 'publisher' of undefined: TypeError: Cannot read property 'publisher' of undefined
    at m (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:23206)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:26048
    at Array.filter (native)
    at e.onDidInstallExtension (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:26022)
    at e.invoke (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:27:19247)
    at e.fire (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:27:20700)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:11679
    at e.invoke (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:27:19247)
    at e.fire (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:27:20700)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:14683
```

**Comment by joaomoreno** [comment]
Great catch!
