### ISSUE TITLE
Extension that errors during activation still says isActive=true

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#44956]
I'm trying to write a test that ensures my extension activates without error, but currently it seems like I can't detect this. My test looks like:

```ts
const ext = vs.extensions.getExtension("Dart-Code.dart-code");
describe("Extension", () => {
	it("activated", async () => {
		await ext.activate();
		assert.equal(ext.isActive, true);
	});
});
```

The test passes:

```text
  Test environment
    √ has opened the correct folder
  Extension
    √ activated
  2 passing (78ms)
Tests exited with code: 0
```

Yet the extension actually errors in it's activate method:

```text
Activating extension `Dart-Code.dart-code` failed: Path must be a string. Received undefined.
Activating extension `Dart-Code.dart-code` failed:  Path must be a string. Received undefined
Here is the error stack:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at activate (C:\projects\dart-code\src\extension.ts:221:42)
    at Function.t._callActivateOptional (c:\projects\dart-code\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:688:725)
    at Function.t._callActivate (c:\projects\dart-code\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:688:409)
    at c:\projects\dart-code\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:687:572
    at Object.g [as _notify] (c:\projects\dart-code\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
    at Object.enter (c:\projects\dart-code\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
    at n.Class.derive._oncancel._run (c:\projects\dart-code\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
    at n.Class.derive._oncancel._completed (c:\projects\dart-code\.vscode-test\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
```

Note: My extension actually activate before the test ran, because I'm opening a folder which causes it to activate. I'm fine that my test isn't catching the exception (after all, the test is running after it occurred) however I don't expect `isActive` to return true for an extension that errored during activation, otherwise it seems impossible to put tests around extension activation (at least for the scenario of having a folder open).

**Comment by sandy081** [comment]
@DanTup Does `isActive` returns `true` even if the extension was not activated before?

**Comment by DanTup** [comment]
@sandy081 Yep, seems to. The `activate()` call doesn't appear to throw (this seems strange?) and `isActive` still is true:

```
  Extension
Activating extension `Dart-Code.dart-code` failed: Test error during activation.
Activating extension `Dart-Code.dart-code` failed:  Test error during activation
Here is the error stack:  Error: Test error during activation
    at activate (M:\Coding\Applications\Dart-Code\src\extension.ts:274:8)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:688:725)
    at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:688:409)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:687:572
    at Object.g [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
    at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
    at n.Class.derive._oncancel._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
    at c (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:888)
    at n.Class.derive.join.i.forEach.q.then.o.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:78)
    √ activated
```

Test looked like this:

```ts
describe("Extension", () => {
	it("activated", async () => {
		await ext.activate();
		assert.equal(ext.isActive, true);
	});
});
```

**Comment by alexandrudima** [comment]
Reproducible steps:

* `44956-1/package.json`
```json
{
    "publisher": "alex",
    "name": "44956-1",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [],
    "main": "index.js"
}
```
* `44956-1/index.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    throw new Error('broken');
    return {
        sum: function(a, b) {
            return a + b;
        }
    }
}
```
* `44956-2/package.json`:
```json
{
    "publisher": "alex",
    "name": "44956-2",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```
* `44956-2/index.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    const ext = vscode.extensions.getExtension('alex.44956-1');
    ext.activate().then((api) => {
        console.log(`I have api`);
    }, (err) => {
        console.log(`there is an err`);
        console.log(err);
    })
}
```

Control path should go into the err callback and should log `there is an err`.

**Comment by alexandrudima** [comment]
The API will still say `isActive` because `isActive` reflects if `activate()` was invoked, it does not reflect if `activate()` produced an error or not.

**Comment by DanTup** [comment]
@alexandrudima So how should I check if an extension successfully activated (eg. to use it's `exports`, or to test that it activated correctly in a test)?

**Comment by DanTup** [comment]
Oh, looking at your change - can I just call `activate` again, and it'll re-throw the original errors?

**Comment by alexandrudima** [comment]
Yes, `activate()` is called only once on the extension and the result of the call (exported API or thrown exception) is permanently cached.

This is in order to cover various cases where the extension is already activated by the time the other extension tries to activate it.

I agree the name `isActive` is misleading, as it reflects if `activate()` was called on the extension and does not reflect the successful/unsuccessful result of the call. You could simply always call `ext.activate()` and it will be a no-op if the extension is already activated. i.e. you could simply not use `isActive`...

**Comment by DanTup** [comment]
> Yes, `activate()` is called only once on the extension and the result of the call

Excellent, this will solve my problem perfectly - I wanted to write tests that failed if activate had thrown and it seems like that'll just happen automatically now (I call `activate` in my test `before` hook). Thanks! 👍
