### ISSUE TITLE
Blank editor-none of the options work 

### ISSUE THREAD

**Issue by clowery52916** [Microsoft/vscode#44993]
- VSCode Version: 1.20
- OS Version: 10.13.3

Steps to Reproduce:

1. I've tried the options you listed in all the other questions on this same issue, I've removed all extensions, I've uninstalled and then reinstalled in a different area, as suggested. I installed it via a downloaded link, I then reinstalled it in the terminal. I do see something about some of the fonts I installed on a program before (Fira Code iScript), but that problem is, I have deleted that file and it shouldn't be saved anywhere so I am not sure why that is the one registering. Its not even in my github saved that way. I can't change the font, I am not in that specific folder.... Please help!
2. Here is the errors - it seems the majority of it is coming from the workbench 

```
 ERR Failed to execute 'add' on 'DOMTokenList': The token provided ('monaco-font-aliasing-Fira Code iScript') contains HTML space characters, which are not valid in tokens.: Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('monaco-font-aliasing-Fira Code iScript') contains HTML space characters, which are not valid in tokens.
    at e.setFontAliasing (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4632:237)
    at e.renderWorkbench (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4636:492)
    at e.startup (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4616:763)
    at e.createWorkbench (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4688:3)
    at e.createContents (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4687:407)
    at e.open (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4695:415)
    at file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4701:837
    at Object.g [as _notify] (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:140:868)
    at Object.enter (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:153)
    at n.Class.derive._oncancel._run (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:145:970)
index.js:5 [uncaught exception]: InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('monaco-font-aliasing-Fira Code iScript') contains HTML space characters, which are not valid in tokens.
onError @ index.js:5
index.js:5 Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('monaco-font-aliasing-Fira Code iScript') contains HTML space characters, which are not valid in tokens.
    at e.setFontAliasing (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4632)
    at e.renderWorkbench (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4636)
    at e.startup (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4616)
    at e.createWorkbench (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4688)
    at e.createContents (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4687)
    at e.open (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4695)
    at /private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4701
    at Object.g [as _notify] (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8…o Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:140)
    at Object.enter (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8…o Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144)
    at n.Class.derive._oncancel._run (/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8…o Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:145)
onError @ index.js:5
/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1306   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at e.setCompoundSchemaValues (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3473:611)
    at file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3472:511
    at e._handle (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:415)
    at e.setHandler (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:98)
    at e.registerListeners (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3471:846)
    at new e (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3470:238)
    at t.create (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90:535)
    at e._createInstance (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1289:289)
    at e.createInstance (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1288:560)
    at new t (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3963:417)
/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8…o Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:253 [Extension Host] TypeDefinition null
/private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8… Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1306   ERR Cannot read property 'getHTMLElement' of undefined: TypeError: Cannot read property 'getHTMLElement' of undefined
    at t.addEntry (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3414:126)
    at e.$setEntry (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2760:281)
    at e._doInvokeHandler (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2770:216)
    at e._invokeHandler (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2769:944)
    at e._receiveRequest (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2769:61)
    at e._receiveOneMessage (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2768:842)
    at file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2767:923
    at file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2770:750
    at e.fire (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:161:76)
    at Socket.<anonymous> (file:///private/var/folders/mm/g2hg_ts90mjg_mhzgcw48dzr0000gn/T/AppTranslocation/8890BA1E-A83F-49EC-8B3A-9D3F2355D0E0/d/Visual Studio Code 4.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:286:187)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I think this can be reproduced by somehow editing `workbench.fontAliasing`

**Comment by bpasero** [comment]
@clowery52916 can you share your settings file?

**Comment by clowery52916** [comment]
This file has been removed, I can't edit anything anymore.... Why has this
ticket been closed?

**Comment by bpasero** [comment]
@clowery52916 it is closed because I pushed a fix for this issue so that it does not happen again. The settings file should be here: `/Users/<name>/Library/Application Support/code/User/settings.json`
