### ISSUE TITLE
VS code does not start on Ubuntu 17.10 - Glib version too old

### ISSUE THREAD

**Issue by breiteswiesel** [Microsoft/vscode#45024]
Visual studio code does not start on Ubuntu and throws the following verbose output
```Shell
vscode --verbose
[7428:0304/210159.141774:ERROR:browser_main_loop.cc(279)] Gtk: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
[7428:0304/210159.141834:ERROR:browser_main_loop.cc(279)] Gtk: Loading IM context type 'ibus' failed
[main 9:01:59 PM] Error: listen EACCES /run/user/1026/snap.vscode/Code-1.20.1-main.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1247:19)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1413:5)
    at /snap/vscode/26/usr/share/code/resources/app/out/vs/code/electron-main/main.js:154:456
    at new n.Class.derive._oncancel (/snap/vscode/26/usr/share/code/resources/app/out/vs/code/electron-main/main.js:81:234)
    at Object.t.serve (/snap/vscode/26/usr/share/code/resources/app/out/vs/code/electron-main/main.js:154:386)
    at n (/snap/vscode/26/usr/share/code/resources/app/out/vs/code/electron-main/main.js:443:882)
    at J (/snap/vscode/26/usr/share/code/resources/app/out/vs/code/electron-main/main.js:446:235)
```

- VSCode Version: Snap 1.20.1
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Start vscode from terminal with verbose

Does this issue occur when all extensions are disabled?: Yes

**Comment by breiteswiesel** [comment]
Closed due to duplicate
