### ISSUE TITLE
Update to 1.21 breaks mocha require

### ISSUE THREAD

**Issue by mscottx88** [Microsoft/vscode#45152]
- VSCode Version: ~1.20.1~  1.21
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Using sinon, chai, sinon-chai, and mocha in orchestration, setup a testing suite as follows:

Create `setup.js` to setup your test environment:

```
'use strict';

const chai = require('chai');
const sinon = require('sinon');
const sinonChai = require('sinon-chai');

chai.use(sinonChai);
```

Create a test case that tries to use `calledOnce` such as:

```
'use strict';

const sinon = require('sinon');
const expect = require('chai').expect;

const sandbox = sinon.sandbox.create();
const myStub = sandbox.stub(yourService, 'method');

... invoke your method under test here

// FAILS with error Invalid Chai property when calling calledOnce
expect(myStub).calledOnce.and.calledWithExactly();  
```

Now, attempt to debug interactively this test case with a Launch Configuration such as:

```
{
      "type": "node",
      "request": "launch",
      "name": "Test Spec",
      "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
      "args": [
        "-c",
        "--require",
        "test/setup.js",
        "${file}",
        "--no-timeouts"
      ],
      "skipFiles": [
        "${workspaceRoot}/node_modules/**/*",
        "<node_internals>/**/*"
      ],
      "cwd": "${workspaceRoot}",
      "runtimeArgs": [
        "--nolazy"
      ]
    }
```

2. Downgrade to 1.19.1 and see the exact same test cases you've been working with for months work just fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
What version of node.js are you using?

**Comment by mscottx88** [comment]
I am on 8.9.0

**Comment by roblourens** [comment]
It should write the command that it uses to start the program to the debug console - is it exactly the same between the two vscode versions?

**Comment by mscottx88** [comment]
Here is the Debug Console output when running a test cases:

```
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

```
Debugging with inspector protocol because Node.js v8.9.0 was detected.
node --nolazy --inspect-brk=48972 node_modules\mocha\bin\_mocha -c --require test/setup.js e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js --no-timeouts 
Debugger listening on ws://127.0.0.1:48972/a8635c80-58fc-465e-9c2f-1618db9241e4

  services
    ItemWorksheetCreator
      constructor
        √ returns a configured instance of ItemWorksheetCreator, which extends EventEmitter
      addAttribute
        √ adds a new attribute to the attributeMap, only once
      addItem
        √ only adds an item to the worksheet if at least one attribute has been added
        √ adds an item to an internal array of rows
        √ when adding items, defaults can be supplied
        √ only assigns a value to an attribute known to the spreadsheet
        √ assigns a warning color to invalid items
      addItems
        √ adds items to the worksheet, persisting the data in blocks
      addUpdateHyperlink
        √ adds some padding rows and then a row with the hyperlink
      createWorksheet
        √ creates a worksheet from a template and shares it
      finalizeWorksheet
        √ emits an empty worksheet event if there are no items
        √ performs a variety of tasks to finalize the worksheet
      populateHeadings
        √ populates the headings of the worksheet
        √ supplies a default for version if falsy
      saveRows
        √ only saves rows if there are any pending to be saved
        √ creates the worksheet and appends rows as needed
      sortAttributes
        √ only sorts if there is a need to do so
        √ sorts attributes by their display name
  18 passing (167ms)
```

Now, here is the results when running on latest VS Code:
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

```
node --nolazy --inspect-brk=16737 node_modules\mocha\bin\_mocha -c --require test/setup.js e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js --no-timeouts 
Debugger listening on ws://127.0.0.1:16737/90f29062-4186-439b-9e9e-42513c392156

  services
    ItemWorksheetCreator
      constructor
        √ returns a configured instance of ItemWorksheetCreator, which extends EventEmitter
      addAttribute
        √ adds a new attribute to the attributeMap, only once
      addItem
        √ only adds an item to the worksheet if at least one attribute has been added
        √ adds an item to an internal array of rows
        √ when adding items, defaults can be supplied
        √ only assigns a value to an attribute known to the spreadsheet
        √ assigns a warning color to invalid items
      addItems
        1) adds items to the worksheet, persisting the data in blocks
      addUpdateHyperlink
        2) adds some padding rows and then a row with the hyperlink
      createWorksheet
        3) creates a worksheet from a template and shares it
      finalizeWorksheet
        4) emits an empty worksheet event if there are no items
        5) performs a variety of tasks to finalize the worksheet
      populateHeadings
        6) populates the headings of the worksheet
        7) supplies a default for version if falsy
      saveRows
        8) only saves rows if there are any pending to be saved
        9) creates the worksheet and appends rows as needed
      sortAttributes
        10) only sorts if there is a need to do so
        11) sorts attributes by their display name
  7 passing (247ms)
  11 failing
  1) services
       ItemWorksheetCreator
         addItems
           adds items to the worksheet, persisting the data in blocks:
     Error: Invalid Chai property: calledTwice
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:396:28)
      at <anonymous>

  2) services
       ItemWorksheetCreator
         addUpdateHyperlink
           adds some padding rows and then a row with the hyperlink:
     Error: Invalid Chai property: calledTwice
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:405:28)
      at <anonymous>

  3) services
       ItemWorksheetCreator
         createWorksheet
           creates a worksheet from a template and shares it:
     Error: Invalid Chai property: calledOnce
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:423:34)
      at <anonymous>

  4) services
       ItemWorksheetCreator
         finalizeWorksheet
           emits an empty worksheet event if there are no items:
     Error: Invalid Chai property: calledOnce
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:469:28)
      at <anonymous>

  5) services
       ItemWorksheetCreator
         finalizeWorksheet
           performs a variety of tasks to finalize the worksheet:
     Error: Invalid Chai property: called. Did you mean "all"?
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:63:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:489:28)
      at <anonymous>

  6) services
       ItemWorksheetCreator
         populateHeadings
           populates the headings of the worksheet:
     Error: Invalid Chai property: calledTwice
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:575:11)
      at <anonymous>

  7) services
       ItemWorksheetCreator
         populateHeadings
           supplies a default for version if falsy:
     Error: Invalid Chai property: calledTwice
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:602:11)
      at <anonymous>

  8) services
       ItemWorksheetCreator
         saveRows
           only saves rows if there are any pending to be saved:
     Error: Invalid Chai property: called. Did you mean "all"?
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:63:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:624:39)
      at <anonymous>

  9) services
       ItemWorksheetCreator
         saveRows
           creates the worksheet and appends rows as needed:
     Error: Invalid Chai property: calledOnce
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:635:35)
      at <anonymous>

  10) services
       ItemWorksheetCreator
         sortAttributes
           only sorts if there is a need to do so:
     Error: Invalid Chai property: called. Did you mean "all"?
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:63:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:676:45)
      at <anonymous>

  11) services
       ItemWorksheetCreator
         sortAttributes
           sorts attributes by their display name:
     Error: Invalid Chai property: calledOnce
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (e:\code8-io\item-api\test\spec\services\item-worksheet-creator.spec.js:686:41)
      at <anonymous>


```

**Comment by mscottx88** [comment]
The one line at the top is missing "Debugging with inspector protocol..." not sure if that's relevant.

**Comment by mscottx88** [comment]
Ha, and i just realized this is occurring in v1.21

**Comment by roblourens** [comment]
If you just run that command in vscode's integrated terminal (without the --inspect-brk part) does it work?

**Comment by mscottx88** [comment]
No:

```
$ node --nolazy "node_modules\mocha\bin\_mocha" -c --require test/setup.js "e:\code8-io\item-api\test\spec\services\item-worksheet-reader.spec.js" --no-timeouts


  services
    ItemWorksheetReader
      constructor
        1) "before each" hook for "returns a configured instance of ItemWorksheetReader"


  0 passing (56ms)
  1 failing

  1) services
       "before each" hook for "returns a configured instance of ItemWorksheetReader":
     Error: Invalid Chai property: calledOnce
      at Object.proxyGetter [as get] (e:\code8-io\item-api\node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.beforeEach (e:\code8-io\item-api\test\spec\services\item-worksheet-reader.spec.js:367:30)
      at <anonymous>
```

**Comment by roblourens** [comment]
Ok, how do you run it normally to see it work? And what's the difference between the two?

**Comment by mscottx88** [comment]
Are you unable to reproduce the problem? If not, I'll create a trimmed down version.

To answer your question, all I do is open the spec file and press F5 to debug the spec interactively.

When I am on 1.19.1 it works fine. On 1.21.0 it fails.

**Comment by roblourens** [comment]
I'd appreciate a trimmed down version that I can just run.

**Comment by mscottx88** [comment]
Hopefully this helps: https://github.com/mscottx88/vs-code-bug-45152-mocha-require

**Comment by roblourens** [comment]
I can't figure out what 1.19 was doing differently, but given that the command string doesn't work in the terminal, I think 1.21 is actually doing the right thing. But this is fixed for me just by using `${relativeFile}` instead of `${file}`. I think one of the libraries involved just can't handle the absolute path.

**Comment by mscottx88** [comment]
I can confirm this works as well.  Perhaps this breaking change should be mentioned to the community.

**Comment by roblourens** [comment]
I don't see this as a vscode breaking change. The command doesn't work in the terminal, and the debug adapter should be emulating the behavior of running the command in the terminal. Rather, it's something that accidentally worked before.
