### ISSUE TITLE
statusBar.foreground is read-only (breaks plugins)

### ISSUE THREAD

**Issue by vuldin** [Microsoft/vscode#45340]
- VSCode Version: 1.22.0-insider
- OS Version:mac high sierra 10.13.3 (17D102)

Steps to Reproduce:

1. Attempt to use vim plugin version 0.11.1 (or any other plugin that needs to modify statusBar.foreground)
2. any interaction that makes the plugin attempt to edit this property (hitting hjkl in this case) causes the following error in the console:

```
Error: TypeError: Cannot delete read only property 'statusBar.foreground' of object
    at Object.deleteProperty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:524:821)
    at StatusBarImpl.SetColor (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/statusBar.js:30:20)
    at ModeHandler._renderStatusBar (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:1065:39)
    at ModeHandler.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:1048:18)
    at Generator.next (<anonymous>)
    at /Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:3:12)
    at ModeHandler.updateView (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:884:16)
    at ModeHandler.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:202:28)
    at Generator.next (<anonymous>)
    at /Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:3:12)
    at ModeHandler.handleSelectionChange (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:97:16)
    at Object.taskQueue_1.taskQueue.enqueueTask [as promise] (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:68:58)
    at TaskQueue.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/taskQueue.js:32:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/taskQueue.js:4:58)
    at <anonymous> (at TaskQueue.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/taskQueue.js:36:29))
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:398
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by bpasero** [comment]
@sandy081 see https://github.com/VSCodeVim/Vim/issues/2432#issuecomment-371737601

**Comment by roblourens** [comment]
Also, if settings.json is dirty, then I get constant log spam whenever I move the cursor using the vim extension:

`[renderer3] [error] Unable to write into user settings because the file is dirty. Please save the user settings file first and then try again.: Error: Unable to write into user settings because the file is dirty. Please save the user settings file first and then try again`

Is that supposed to happen when the settings file is dirty and an extension tries to update the configuration?

**Comment by sandy081** [comment]
@roblourens Good catch. 

> I think the problem is with .get('colorCustomizations'); and Object.assign doesn't work.

Problem is not with `assign`. It's because JSON.stringify() on the result object (which is proxy) is not returning proper value. Proxy should have a trap for `toJSON` property access.  Having this trap fixes this.

> Is that supposed to happen when the settings file is dirty and an extension tries to update the configuration?

Yes, this is expected.
