### ISSUE TITLE
更新後エディターが使えない。-  VSCode after update can not be used.

### ISSUE THREAD

**Issue by ohbayashi** [Microsoft/vscode#45536]
Issue Type: <b>Bug</b>

最新への更新を行ったらエディターの編集が全くできなくなりました。
使えないと仕事ができないので、更新前の状態に戻したいです。

再現手順
1. VSCodeを起動直後。
2. エクスプローラーでどのファイルを選択してもエディターで表示されない。
3. その他、拡張機能一覧なども表示できないので、無効化することができない。

バージョン 1.22.0-insider
コミット 3817c899cae312e0e989da8bfbc61308cfbf45f1
日付 2018-03-09T05:15:56.454Z
シェル 1.7.9
レンダラー 58.0.3029.110
Node 7.9.0
アーキテクチャ x64

--- --- ---

VSCode after update can not be used.

Editing of the editor can not be done at all when updating to the latest.
Since I can not work if I can not use it, I want to return to the state before updating.

Reproduction procedure
1. Immediately after starting VSCode.
2. Whatever file is selected in Windows Explorer, it is not displayed in the editor.
3. Other, extended function list etc. can not be displayed, so it can not be invalidated.
--- --- ---

VS Code version: Code - Insiders 1.22.0-insider (3817c899cae312e0e989da8bfbc61308cfbf45f1, 2018-03-09T05:15:56.454Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440S CPU @ 2.80GHz (4 x 2794)|
|Memory (System)|7.92GB (1.55GB free)|
|Process Argv|C:\Program Files\MicrosoftVSCodeInsiders\Code - Insiders.exe C:\vagrant\vortex-trade|
|Screen Reader|no|
|VM|18%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
vscode-markdownlint|Dav|0.13.0
tslint|eg2|1.0.28
php-debug|fel|1.12.1
phpcs|ika|1.0.5
plantuml|jeb|2.5.5
debugger-for-chrome|msj|4.2.0
laravel-blade|one|1.17.0
markdown-preview-enhanced|shd|0.3.3
vscode-table-formatter|shu|1.2.1
blueprint|tea|1.5.0
vscode-apielements|vnc|0.6.7
markdown-all-in-one|yzh|1.1.0

</details>
Reproduces only with extensions

**Comment by bpasero** [comment]
@ohbayashi can you make a screen recording and attach it here to demonstrate the issue?

**Comment by ohbayashi** [comment]
![vscode_screen_freeze](https://user-images.githubusercontent.com/21698965/37267827-fc092920-2605-11e8-8920-0b8a0345c7d2.gif)

It is hard to understand, but I click and double click.

**Comment by bpasero** [comment]
@ohbayashi can you share your settings?

**Comment by ohbayashi** [comment]
```json
{
    "editor.tabSize": 4,
    "editor.autoClosingBrackets": false,
    "editor.autoIndent": false,
    "editor.renderWhitespace": "boundary",
    "editor.renderControlCharacters": true,
    "editor.renderIndentGuides": true,
    "editor.rulers": [ 60, 80, 100 ],
    "editor.minimap.enabled": false,    // あんまり便利じゃない
    "editor.minimap.maxColumn": 120,
    // "files.autoGuessEncoding": true,
    "files.defaultLanguage": "markdown",
    "files.exclude": {
        // "**/.vscode": true,
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/storage": true,
        "**/node_modules": false
    },
    "files.eol": "\n",       // LF
    // https://github.com/shd101wyy/vscode-markdown-preview-enhanced/blob/master/package.json
    // "markdown-preview-enhanced.previewTheme": "one-dark.css",
    "markdown-preview-enhanced.revealjsTheme": "white.css",
    "files.trimTrailingWhitespace": true,
    "search.exclude": {
        "**/bootstrap/**/*": true,
        "**/centos7/**/*": true,
        "**/node_modules/**/*": true,
        "**/public/build/js": true,
        "**/vendor/**/*": true,
        "**/jquery*.js": true
    },
    "window.openFilesInNewWindow": "on",
    "window.title": "${rootName}${separator}${dirty}${activeEditorLong}",
    "window.zoomLevel": 0,
    "window.menuBarVisibility": "default",
    "workbench.startupEditor": "newUntitledFile",

    // 端末 = git bush
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "git.confirmSync": false,

    // Alternate plantuml.jar location. Leave it blank to use integrated jar.
    // "plantuml.jar": "C:\\Apps\\PlantUML\\plantuml.jar",
    "extensions.ignoreRecommendations": true,

    "markdown.extension.orderedList.marker": "one",

    "[css]": {
    },
    "[json]":  {
        "editor.insertSpaces": false,
        "editor.quickSuggestions": {
            "strings": true
        }
    },
    "[markdown]":  {
        "editor.insertSpaces": true,
        "files.trimTrailingWhitespace": false
    },
    "[html]": {
    },
    "[javascript]": {},
    "[php]": {      // psr-2
        "editor.insertSpaces": true,
        "editor.rulers": [ 80, 120 ]
    },
    "[sql]": {
        "editor.insertSpaces": false
    },

    // tslint
    "tslint.alwaysShowRuleFailuresAsWarnings": true,

    // phpcs
    "phpcs.autoConfigSearch": false,
    "phpcs.executablePath": "C:\\Users\\ohbay\\AppData\\Roaming\\Composer\\vendor\\bin\\phpcs.bat",
    "phpcs.standard": ".\\phpcs.ruleset.xml",
}
```

**Comment by ohbayashi** [comment]
1. execute `C:\Program Files\MicrosoftVSCodeInsiders\bin\code-insiders --verbose`
1. Help >Toggle Developer Tools  
1. console.log

```
/C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:3250 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: c:\Program Files\MicrosoftVSCodeInsiders\resources\app\extensions\yaml\syntaxes\yaml.tmLanguage.json.
New grammar file: C:\Users\ohbay\.vscode-insiders\extensions\vncz.vscode-apielements-0.6.7\syntaxes\YAML.tmLanguage
```

**Comment by abhishekBM4576** [comment]
I've never seen this case before. Try dragging and dropping the file into the editor. Maybe it works

**Comment by ohbayashi** [comment]
> I've never seen this case before. Try dragging and dropping the file into the editor. Maybe it works
>
I tried it but the result was the same. does not open.

The result is the same even if trying to open the project folder of markdown only.

**Comment by ohbayashi** [comment]
It now works after deleting the following folders.
Although the cause is unknown, I will return the setting little by little and explore it.

`.vscode`

Thank you.

**Comment by abhishekBM4576** [comment]
Do you remember what you had in your project settings?

**Comment by EbXpJ6bp** [comment]
I can repo this.

**Comment by ohbayashi** [comment]
```
.vscode
  settings.json
  tasks.json
  style.less
  keybindings.json
```
There are 4 files.
By the way, these have not recently been updated.

**Comment by EbXpJ6bp** [comment]
When "editor.insertSpaces" is configured as language specific setting in workspace setting, it can repo.

in this case:
```
    "[php]": {      // psr-2
        "editor.insertSpaces": true,
        "editor.rulers": [ 80, 120 ]
    },
    "[sql]": {
        "editor.insertSpaces": false
    },
```

**Comment by bpasero** [comment]
@EbXpJ6bp are you saying you can reproduce this issue that files do not open?

@ohbayashi are you saying it works now after you deleted the local `.vscode` folder? Does it break again when you put it back?

**Comment by EbXpJ6bp** [comment]
@bpasero yes

![ttest](https://user-images.githubusercontent.com/8474118/37314876-e09bbe52-2699-11e8-8061-9329dc88f5cb.gif)


<details>
  <summary>Console</summary>

```
log.ts:171   ERR Cannot assign to read only property 'insertSpaces' of object '[object Object]': TypeError: Cannot assign to read only property 'insertSpaces' of object '[object Object]'
    at t.e.mergeContents (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:891)
    at t.e.mergeContents (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:862)
    at d (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:462)
    at t.e.merge (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:551)
    at t.e.getWorkspaceConsolidatedConfiguration (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1403:790)
    at t.e.getConsolidatedConfigurationModelForResource (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1403:407)
    at t.e.getConsolidateConfigurationModel (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1403:198)
    at t.e.getValue (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1400:121)
    at t.getValue (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2611:203)
    at t.getValue (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3893:917)
    at e._updateUserOptIn (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1600:234)
    at e.fire (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:238)
    at t.triggerConfigurationChange (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3905:816)
    at t.onDefaultConfigurationChanged (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3900:435)
    at file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3891:285
    at e.fire (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:218)
    at e.registerConfigurations (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1367:361)
    at file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2752:99
    at e._handle (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2659:138)
    at e.acceptUsers (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2658:952)
    at Function.O._handleExtensionPoint (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2837:777)
    at file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2830:551
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at n.Class.define.cancel.then (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:517)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:147:374)
    at n.Class.derive._creator._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._setCompleteValue (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:776)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:951)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at l (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:152:1011)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:205)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at c (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:203)
    at s (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:107)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at c (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:203)
    at s (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:107)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:190:503
    at D:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\graceful-fs.js:78:16
    at tryToString (original-fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (original-fs.js:436:12)

index.js:44 TypeError: Cannot assign to read only property 'insertSpaces' of object '[object Object]'
    at t.e.mergeContents (configurationModels.ts:113)
    at t.e.mergeContents (configurationModels.ts:109)
    at d (configurationModels.ts:86)
    at t.e.merge (configurationModels.ts:83)
    at t.e.getWorkspaceConsolidatedConfiguration (configurationModels.ts:425)
    at t.e.getConsolidatedConfigurationModelForResource (configurationModels.ts:407)
    at t.e.getConsolidateConfigurationModel (configurationModels.ts:402)
    at t.e.getValue (configurationModels.ts:294)
    at t.getValue (configurationModels.ts:167)
    at t.getValue (configurationService.ts:249)
    at r.editorOpenHandler (explorerViewlet.ts:198)
    at r.doOpenEditor (editorService.ts:434)
    at r.e.openEditor (editorService.ts:205)
    at t.openEditor (explorerViewer.ts:521)
    at t.onLeftClick (explorerViewer.ts:464)
    at t.e.onClick (treeDefaults.ts:157)
    at t.onClick (treeView.ts:1143)
    at HTMLDivElement.<anonymous> (treeView.ts:497)
onError @ index.js:44
(anonymous) @ index.js:113
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ D:\Program Files\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:135
i.globals.onerror @ errorTelemetry.ts:64

configurationModels.ts:113 Uncaught TypeError: Cannot assign to read only property 'insertSpaces' of object '[object Object]'
    at t.e.mergeContents (configurationModels.ts:113)
    at t.e.mergeContents (configurationModels.ts:109)
    at d (configurationModels.ts:86)
    at t.e.merge (configurationModels.ts:83)
    at t.e.getWorkspaceConsolidatedConfiguration (configurationModels.ts:425)
    at t.e.getConsolidatedConfigurationModelForResource (configurationModels.ts:407)
    at t.e.getConsolidateConfigurationModel (configurationModels.ts:402)
    at t.e.getValue (configurationModels.ts:294)
    at t.getValue (configurationModels.ts:167)
    at t.getValue (configurationService.ts:249)
    at r.editorOpenHandler (explorerViewlet.ts:198)
    at r.doOpenEditor (editorService.ts:434)
    at r.e.openEditor (editorService.ts:205)
    at t.openEditor (explorerViewer.ts:521)
    at t.onLeftClick (explorerViewer.ts:464)
    at t.e.onClick (treeDefaults.ts:157)
    at t.onClick (treeView.ts:1143)
    at HTMLDivElement.<anonymous> (treeView.ts:497)
```
</details>

It seems  https://github.com/Microsoft/vscode/commit/81f1deec2fb233b5e0da3739fea712f3f0a5cb82

**Comment by ohbayashi** [comment]
We have identified the pattern that causes an error.
The following corrected settings.json
```
{
    :
    "editor.autoIndent": false,
    "editor.insertSpaces": true,    <- default insert. < override.
    "editor.renderWhitespace": "boundary",
    "editor.renderControlCharacters": true,
    "editor.rulers": [ 60, 80, 100 ],
    "editor.minimap.enabled": false,
    :

    "[json]":  {
        "editor.insertSpaces": false,    <- Only when changing the value override
        "editor.quickSuggestions": {
            "strings": true
        }
    },
    "[php]": {
    },
    "[sql]": {},
    ;
}
```
With this setting the error is zero.

Error when making the following changes.
```
    },
    "[php]": {
        "editor.rulers": [ 80, 120 ]      <- Insert only this line insert.
    },
    "[sql]": {},
    ;
```

developer tools console.log.
```
ERR Cannot assign to read only property 'rulers' of object '[object Object]': TypeError: Cannot assign to read only property 'rulers' of object '[object Object]'
    at t.e.mergeContents (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1396:891)
    at t.e.mergeContents (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1396:862)
    at d (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1396:462)
    at t.e.merge (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1396:551)
    at t.e.getWorkspaceConsolidatedConfiguration (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1403:790)
    at t.e.getConsolidatedConfigurationModelForResource (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1403:407)
    at t.e.getConsolidateConfigurationModel (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1403:198)
    at t.e.getValue (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1400:121)
    at t.getValue (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:2611:203)
    at t.getValue (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:3893:917)
    at e._updateUserOptIn (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1600:234)
    at e.fire (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:165:238)
    at t.triggerConfigurationChange (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:3905:816)
    at t.onDefaultConfigurationChanged (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:3900:435)
    at file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:3891:285
    at e.fire (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:165:218)
    at e.registerConfigurations (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:1367:361)
    at file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:2752:99
    at e._handle (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:2659:138)
    at e.acceptUsers (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:2658:952)
    at Function.O._handleExtensionPoint (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:2837:777)
    at file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:2830:551
    at Object.g [as _notify] (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at n.Class.define.cancel.then (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:151:517)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:147:374)
    at n.Class.derive._creator._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:776)
    at Object.g [as _notify] (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:144:951)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at l (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:152:1011)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:153:205)
    at Object.g [as _notify] (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at c (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:155:203)
    at s (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:155:107)
    at Object.g [as _notify] (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at c (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:155:203)
    at s (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:155:107)
    at Object.g [as _notify] (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at file:///C:/Program Files/MicrosoftVSCodeInsiders/resources/app/out/vs/workbench/workbench.main.js:190:503
    at C:\Program Files\MicrosoftVSCodeInsiders\resources\app\node_modules.asar\graceful-fs\graceful-fs.js:78:16
    at tryToString (original-fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (original-fs.js:436:12)
```

**Comment by ohbayashi** [comment]
>@ohbayashi are you saying it works now after you deleted the local .vscode folder?
>
Yes.

> Does it break again when you put it back?
> 
Yes.

**Comment by bpasero** [comment]
@sandy081 looks like a regression from your proxy work

**Comment by sandy081** [comment]
Yes, this is due to proxy work but not due to proxies. A change to optimise merge (during proxy work) surfaced this issue.

To verify:

- Have following setting in User settings

```json
"[php]": {
        "editor.rulers": [ 80 ]
},
```

- Have following setting in Workspace settings

```json
"[php]": {
        "editor.rulers": [ 80, 120 ]
},
```

- Reload VS Code.
- 💥 Editor does not work. Error in console.

```
ERR Cannot assign to read only property 'rulers' of object '[object Object]': TypeError: Cannot assign to read only property 'rulers' of object '[object Object]'
```

**Comment by sandy081** [comment]
@bpasero Better to do a rebuild?

**Comment by bpasero** [comment]
@sandy081 as you like, I think we had been running with this for days already?

**Comment by sandy081** [comment]
Yes, from Thursday build. Then we can wait  for tomorrow's build
