### ISSUE TITLE
TypeError: Cannot read property 'viewColumn' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45548]
From https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=6c10cce6-2923-6f1a-51d3-71a6bca96ac6

```
TypeError: Cannot read property 'viewColumn' of undefined
/vs/workbench/api/node/extHostTextEditors.ts#163:18 (apply)
/vs/workbench/services/extensions/node/rpcProtocol.ts#174:16 (_doInvokeHandler)
/vs/workbench/services/extensions/node/rpcProtocol.ts#159:27 (_invokeHandler)
/vs/workbench/services/extensions/node/rpcProtocol.ts#108:39 (_receiveRequest)
/vs/workbench/services/extensions/node/rpcProtocol.ts#90:9 (call)
at /out/vs/workbench/node/extensionHostProcess.js:585:494 
at /out/vs/workbench/node/extensionHostProcess.js:588:343 
at /out/vs/workbench/node/extensionHostProcess.js:87:749 
/vs/base/common/event.ts#142:15 (fire)
/vs/base/parts/ipc/node/ipc.net.ts#81:22
```

**Comment by jrieken** [comment]
dupe https://github.com/Microsoft/vscode/issues/45547#issuecomment-372242092
