### ISSUE TITLE
ERR Cannot assign to read only property 'insertFinalNewline' of object '[object Object]'

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#45565]
```
ERR Cannot assign to read only property 'insertFinalNewline' of object '[object Object]': TypeError: Cannot assign to read only property 'insertFinalNewline' of object '[object Object]'
at t.e.mergeContents (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:891)
    at t.e.mergeContents (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:862)
    at d (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:462)
    at t.e.merge (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1396:551)
    at t.e.getWorkspaceConsolidatedConfiguration (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1403:790)
    at t.e.getConsolidatedConfigurationModelForResource (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1403:407)
    at t.e.getConsolidateConfigurationModel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1403:198)
    at t.e.getValue (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1400:121)
    at t.getValue (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2611:203)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2612:104
    at Array.filter (native)
    at t.compareAndUpdateWorkspaceConfiguration (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2612:60)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3902:972
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2622:789
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:218)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2619:820
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:517)
    at e.runner (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2619:762)
    at e.onTimeout (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:190:290)
```

- VSCode
Версия 1.22.0-insider
Фиксация 5450fdc79778b5a76a27ea7e5fd68e9ebbe44107
Дата 2018-03-12T05:15:51.483Z
Оболочка 1.7.9
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура x64
- OS Version: win7 pro

Steps to Reproduce:

1. config file:
```json
{
  "editor.tabSize": 2,
  "editor.rulers": [110],
  "editor.detectIndentation": false,
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 3000,
  "files.trimTrailingWhitespace": true,
  "files.eol": "\n",
  "[javascript]": {
    "files.insertFinalNewline": true
  }
}
```
2. Open `code`

**Comment by IgorNovozhilov** [comment]
Версия 1.22.0-insider
Фиксация 112670122d3acf863aa9542b1642d64c69be10bf
Дата 2018-03-13T06:13:20.479Z
Оболочка 1.7.9
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура x64

linux mint 18.2
```
  ERR Cannot assign to read only property 'insertFinalNewline' of object '[object Object]': TypeError: Cannot assign to read only property 'insertFinalNewline' of object '[object Object]'
    at t.e.mergeContents (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1398:891)
    at t.e.mergeContents (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1398:862)
    at d (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1398:462)
    at t.e.merge (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1398:551)
    at t.e.getWorkspaceConsolidatedConfiguration (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1405:790)
    at t.e.getConsolidatedConfigurationModelForResource (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1405:407)
    at t.e.getConsolidateConfigurationModel (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1405:198)
    at t.e.getValue (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1402:121)
    at t.getValue (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2609:435)
    at t.getValue (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3901:917)
    at e._updateUserOptIn (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1602:234)
    at e.fire (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:165:238)
    at t.triggerConfigurationChange (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3913:816)
    at t.onDefaultConfigurationChanged (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3908:435)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3899:285
    at e.fire (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:165:218)
    at e.registerConfigurations (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1369:361)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2759:904
    at e._handle (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2658:169)
    at e.acceptUsers (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2657:1001)
    at Function.O._handleExtensionPoint (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2845:777)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2838:551
    at Object.g [as _notify] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at n.Class.define.cancel.then (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:151:517)
    at Object.enter (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:147:374)
    at n.Class.derive._creator._run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._setCompleteValue (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:149:776)
    at Object.g [as _notify] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:144:951)
    at Object.enter (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._oncancel._completed (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:149:523)
    at l (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:152:1011)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:15
```

**Comment by IgorNovozhilov** [comment]
fixed in
Версия 1.22.0-insider
Фиксация 02def72023c9c03907884d7298a3e042c16975c7
Дата 2018-03-15T06:16:25.881Z
Оболочка 1.7.9
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура x64
