### ISSUE TITLE
"Markdown" editor rendering issues

### ISSUE THREAD

**Issue by Senpos** [Microsoft/vscode#45735]
Issue Type: <b>Bug</b>

**Setting up**
- Install **Hack** font 
- Turn on the font in settings
 `"editor.fontFamily": "Hack, Consolas, 'Courier New', monospace",`
- Set this
`"editor.renderWhitespace": "boundary",` 

**Doing things**
1. Clone [this repository](https://github.com/amureki/django_faq)
2. Open `README.md` (**not** the English one!)
3. Probably it will lag already, try to scroll down and up

**[Short video demonstration](https://drive.google.com/uc?id=1PVIFMJ-gqxhifZOD_TbSRCr5lSq30au1)**

**Error 1**
```
  ERR Cannot read property 'type' of undefined: TypeError: Cannot read property 'type' of undefined
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:669:752
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:669:829
    at Object.o [as renderViewLine] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:671:98)
    at e.renderLine (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1651:989)
    at e._finishRendering (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:478:275)
    at e.render (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:476:14)
    at e.renderLines (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:475:426)
    at t.renderText (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1699:360)
    at t._actualRender (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1770:123)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1769:366
    at z (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1761:1015)
    at t._renderNow (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1769:344)
    at t._flushAccumulatedAndRenderNow (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1766:400)
    at t._onRenderScheduled (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1769:266)
    at e.execute (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:195:972)
    at o (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:196:169)
```

**Error 2**
```
ERR Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at e._removeLinesBefore (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:477:207)
    at e.render (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:476:389)
    at e.renderLines (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:475:426)
    at t.renderText (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1699:360)
    at t._actualRender (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1770:123)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1769:366
    at z (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1761:1015)
    at t._renderNow (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1769:344)
    at t._flushAccumulatedAndRenderNow (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1766:400)
    at t._onRenderScheduled (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1769:266)
    at e.execute (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:195:972)
    at o (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:196:169)
```
A **lot** of these errors in _Developer Tools_, while i'm on the problematic area of file.

Tried **both** in VS Code **stable** and **Insiders**.

~~Will try to reproduce this issue with other fonts.~~ 
~~Couldn't reproduce with **Iosevka** and **Consolas**.~~
Well, it is not clear for me when it fails. Sometimes it works with other fonts, sometimes not. Yikes.

**VS Code version:** Code - Insiders 1.22.0-insider (a716373aaaf50cbce3618688a645b324721b35dd, 2018-03-14T05:15:41.910Z)
**OS version:** Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|Memory (System)|7.94GB (3.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by Senpos** [comment]
**Important update**

After some time playing around with this issue, I've found that this bug can be easily reproduced with next steps:
- put this into your settings `"editor.renderWhitespace": "boundary",` 
- resize VS Code window

**[Here is another video example](https://drive.google.com/uc?id=1bMHnamlopvL8-BzEYFCAFlbA-MlMM2GF)**
- 00:00 - 00:11 - **without** `"editor.renderWhitespace": "boundary",`, VS Code **full screen**
- 00:11 - 00:18 - **with**  `"editor.renderWhitespace": "boundary",`,  VS Code **full screen**
- 00:18 - 00:28 -  **with**  `"editor.renderWhitespace": "boundary",`,  VS Code **windowed**,  **_bug appeared_** (!)

**Comment by alexandrudima** [comment]
The root cause is 020afb768d01f349b56db8d7358bbe5b970b2f7e , combined with a bug in the implementation for `getLineCharCode`, which would lead to the range being validated incorrectly.
