### ISSUE TITLE
Opening Remote Folder via "Open Folder" is not working reliably

### ISSUE THREAD

**Issue by swarnendubiswas** [Microsoft/vscode#45783]
- VSCode Version: 1.21.0
- OS Version: CentOS 7.4

Steps to Reproduce:

1. Mount a path via sftp on Nautilus
2. Select "Open Folder" in VSC and navigate to the desired folder on the remote system.
3. I expect the folder to be opened in VSC all the time, but this does not happen reliably. More often than not, VSC is not able to open the folder.

Output from the Log (Main): 

[2018-03-14 11:48:45.243] [main] [error] [uncaught exception in main]: TypeError: Error processing argument at index 11, conversion failure from undefined
[2018-03-14 11:48:45.243] [main] [error] TypeError: Error processing argument at index 11, conversion failure from undefined
    at Object.showMessageBox (/workspace/sbiswas/software/visual-code/usr/share/code/resources/electron.asar/browser/api/dialog.js:277:20)
    at /workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:411:422
    at new n.Class.derive._oncancel (/workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:81:378)
    at Object.factory (/workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:411:384)
    at t.e.consume (/workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:105:230)
    at /workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:105:17
    at new n.Class.derive._oncancel (/workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:81:378)
    at t.e.queue (/workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:104:955)
    at e.showMessageBox (/workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:411:360)
    at /workspace/sbiswas/software/visual-code/usr/share/code/resources/app/out/vs/code/electron-main/main.js:396:77

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@swarnendubiswas  Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
