### ISSUE TITLE
Failing test: ExtHostDocumentSaveParticipant event delivery, overall timeout

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#45795]
https://monacotools.visualstudio.com/Monaco/_build/index?buildId=36916&_a=summary

```
2018-03-14T15:53:51.6986695Z   1) ExtHostDocumentSaveParticipant event delivery, overall timeout:
2018-03-14T15:53:51.7001683Z 
2018-03-14T15:53:51.7022470Z       AssertionError: 1 == 2
2018-03-14T15:53:51.7050198Z       + expected - actual
2018-03-14T15:53:51.7064580Z 
2018-03-14T15:53:51.7086039Z       -1
2018-03-14T15:53:51.7107227Z       +2
2018-03-14T15:53:51.7126714Z       
2018-03-14T15:53:51.7150732Z       at file:///opt/vsts/work/1/s/out/vs/workbench/test/electron-browser/api/extHostDocumentSaveParticipant.test.js:205:24
2018-03-14T15:53:51.7175218Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:1183:59)
2018-03-14T15:53:51.7197743Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:865:30)
2018-03-14T15:53:51.7231713Z       at Promise_ctor._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:1081:29)
2018-03-14T15:53:51.7253941Z       at Promise_ctor._completed (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:1049:18)
2018-03-14T15:53:51.7277332Z       at file:///opt/vsts/work/1/s/out/vs/base/common/async.js:311:17
2018-03-14T15:53:51.7301505Z       at _Base.Class.derive._creator.CompletePromise_done [as done] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:1537:34)
2018-03-14T15:53:51.7326162Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:1193:48)
2018-03-14T15:53:51.7352209Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:865:30)
2018-03-14T15:53:51.7376363Z       at _Base.Class.derive._creator._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.raw.js:1081:29)
```

Seems to happen rarely.

**Comment by joaomoreno** [comment]
Another one:

https://monacotools.visualstudio.com/Monaco/_build/index?buildId=38455&_a=summary
