### ISSUE TITLE
vs/nls loading errors in insiders

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#45839]
1. In current insiders
2. Open dev console:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9 Loading "vs/nls" failed
n @ /private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9
/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9 Detail: 
n @ /private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9
/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9 Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…ode%20-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/vs/nls.js' failed to load.
    at e.load (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:16:396)
    at e.load (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:15:406)
    at o (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:29:586)
    at s._loadModule (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:29:716)
    at s._resolve (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:31:166)
    at s.defineModule (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:25:768)
    at o (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:32:921)
    at r (file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:33:968)
    at file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…siders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:144:468
    at file:///private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTransloc…nsiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:159:73
n @ /private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9
/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9 Here are the modules that depend on it:
n @ /private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9
/private/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/AppTranslocation/8…-%20Insiders.app/Contents/Resources/app/out/vs/base/worker/workerMain.js:9 vs/nls!vs/base/common/severity
```

<img width="986" alt="screen shot 2018-03-15 at 1 47 27 am" src="https://user-images.githubusercontent.com/12821956/37452789-d9fe2828-27f2-11e8-9d07-80f3a0282ffa.png">

Looks like the same root cause as https://github.com/Microsoft/vscode/issues/16953

**Comment by mjbvz** [comment]
@jrieken Could 185630f92560e07d85d304d8ff0d72af9fcc6dd1 have caused an issue similar to #16953? Specifically the new import in `standaloneBase`

**Comment by jrieken** [comment]
Yeah, don't use vs/nls in workers... It doesn't explode when running out of source, mean.
