### ISSUE TITLE
Error: Cannot find module '../net'

### ISSUE THREAD

**Issue by alexlamsl** [Microsoft/vscode#45851]
Issue Type: <b>Bug</b>

1. Launch vscode.exe from Command Prompt
2. Close & exit VSCode
```
[main 6:32:25 PM] update#setState idle
[main 6:32:56 PM] update#setState checking for updates
[main 6:32:56 PM] { Error: Cannot find module '../net'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Program Files\Microsoft VS Code\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as net] (C:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at Object.a [as getRawRequest] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:417:96)
    at Object.l [as request] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:352:139)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:417:342
    at t.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:416:935) code: 'MODULE_NOT_FOUND' }
[main 6:32:56 PM] update#setState idle
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.14393

Extensions: none
Reproduces without extensions

**Comment by alexlamsl** [comment]
@vscodebot FWIW, none of those reports seems to be related.

**Comment by mjbvz** [comment]
Your install may be corrupted. Can you try reinstalling vscode to see if that fixes the problem

**Comment by alexlamsl** [comment]
The error is intermittent, i.e. it doesn't show up for every invocation of VSCode.

Would a corrupted installation do that?

**Comment by vvedachalam** [comment]
![Uploading 2018-03-27 23_26_29-Error_ Cannot find module '.._net' · Issue #45851 · Microsoft_vscode.png…]()
Got same issue. I was unable to update VS code as it kept prompting 'program is running' even after I restart the system and didnt open any program other than vs code

**Comment by vvedachalam** [comment]
![2018-03-27 23_26_29-error_ cannot find module _net issue 45851 microsoft_vscode](https://user-images.githubusercontent.com/7630355/37998652-50b68c70-3217-11e8-82a1-c4a5fbe38a2b.png)

**Comment by alexandrudima** [comment]
@alexlamsl @vvedachalam You appear to have broken installations of VS Code. Do you remember having done anything that brought you to this state?

**Comment by alexlamsl** [comment]
@aleksijuvani I think my case is slightly different in that while there are error message in the Command Prompt, VSCode works AFAICT.

All I did was to upgrade to the reported version via "Check for Updates..."

**Comment by joaomoreno** [comment]
Please fully reinstall VS Code.
