### ISSUE TITLE
Links in release notes don't work

### ISSUE THREAD

**Issue by tricki** [Microsoft/vscode#45873]
Issue Type: <b>Bug</b>

1. Open the "Release Notes: 1.21.1" page (Help -> Release Notes)
2. Click on one of the highlight links (e.g. "New Notifications UI")

**Expected result**
Browser opens `https://code.visualstudio.com/updates/v1_21#_new-notifications-ui`

**Actual result**
Browser opens `https://code.visualstudio.com/raw/#new-notifications-ui` and shows a 404 error.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.89GB (6.02GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by chrmarti** [comment]
Is there anything in the console (Help > Toggle Developer Tools)?

**Comment by tricki** [comment]
After some further testing I got some errors in the console output. I had just reloaded Code without extensions and clicked the "Help" menu entry. It became unresponsive for a couple seconds, after which these errors were output:

<details>
<summary>Console output</summary>

```
4dom.ts:187 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
2log.ts:171   ERR Object has been destroyed: Error: Object has been destroyed
    at WebContents.send (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:95:15)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:341:299
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:572)
    at Object.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:924)
    at n.Class.derive._oncancel._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:719)
    at n.Class.derive._oncancel._completed (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:160)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:342:925
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
log.ts:171   ERR Cannot read property 'indexOf' of null: TypeError: Cannot read property 'indexOf' of null
    at f (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:155:316)
    at ChildProcess.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:156:84)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
log.ts:171   ERR Object has been destroyed: Error: Object has been destroyed
    at WebContents.send (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:95:15)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:341:299
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:572)
    at Object.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:924)
    at n.Class.derive._oncancel._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:719)
    at n.Class.derive._oncancel._completed (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:160)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:342:925
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/core/vs\base\worker\workerMain.js.map
4dom.ts:187 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
2log.ts:171   ERR Object has been destroyed: Error: Object has been destroyed
    at WebContents.send (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:95:15)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:341:299
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:572)
    at Object.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:924)
    at n.Class.derive._oncancel._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:719)
    at n.Class.derive._oncancel._completed (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:160)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:342:925
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
log.ts:171   ERR Cannot read property 'indexOf' of null: TypeError: Cannot read property 'indexOf' of null
    at f (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:155:316)
    at ChildProcess.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:156:84)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
log.ts:171   ERR Object has been destroyed: Error: Object has been destroyed
    at WebContents.send (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:95:15)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:341:299
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:572)
    at Object.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:924)
    at n.Class.derive._oncancel._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:719)
    at n.Class.derive._oncancel._completed (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:160)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:342:925
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/core/vs\base\worker\workerMain.js.map
```
</details>

The first error (2log.ts:171) appears every now and then after a reload (about every 5th reload). Before it does Code is unresponsive. However, I wasn't able to detect any lasting problems stemming from this.

I also checked the links in the release notes again and can confirm it's only the links in the table of contents that don't work correctly.
These links also show the wrong URL in the tooltip, so it's not necessarily a JS problem.

**Comment by mjbvz** [comment]
I can't repo this. Clicking on `new notification UI` should just scroll to that section in the release notes page, not open any browser. 

@tricki Can you please try checking the console in the webview developer tools as we. Just run the `Developer: Open Webview developer tools` command

**Comment by tricki** [comment]
I ran the command but didn't see anything happen.

The release notes table of contents has always linked to the website for me, on multiple Windows 10 machines.
![image](https://user-images.githubusercontent.com/523154/37535587-72a0727e-2948-11e8-8dd1-cc52db7d3853.png)

The anchor behavior you describe I only ever saw in the Interactive Playground and as far as I know the "Release Notes" and "Interactive Playground" pages are rendered differently. (Specifically because I can only reproduce #25856 on the "Release Notes" page.)

**Comment by tricki** [comment]
After a couple of reloads I was able to open the Webview developer tools.  There was nothing in the console. 

I then set a global click event listener, clicked the link and stepped through the code. Since then the links scroll to the correct section without opening the browser. In fact, I'm unable to open the link in the browser.
I restarted Code multiple times to check that this behavior is persistent.

But now when I reopen the Release Notes it automatically scrolls down to a strange position (not exactly where it was before, might just be a problem with images not loaded when changing scrollTop). But I guess that's probably another issue.

I'm curious why the links suddenly work correctly. Do you have any explanation?

**Comment by mjbvz** [comment]
Caching of an old version of the release notes perhaps? I'm not sure though. Let me know if you start seeing the problem again

The scroll restoring issue is #45571
