### ISSUE TITLE
Find All References

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#45976]
- VSCode Version: 1.21.1
- OS Version: macOS

![image](https://user-images.githubusercontent.com/30043375/37522381-63692704-292c-11e8-9f5b-804da60f38ce.png)

![image](https://user-images.githubusercontent.com/30043375/37522458-a1e2562c-292c-11e8-94b9-938c701a7bdd.png)

If I change from `options` to `option` it works. What is going on? 😄

**Comment by bsvipas** [comment]
Checked TypeScript output and found this error:

```
[Error  - 15:15:10] 'references' request failed with error.
Error processing request. Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at unescapeLeadingUnderscores (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:9434:18)
    at Object.idText (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:9438:16)
    at IdentifierObject.get [as text] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82347:27)
    at isValidReferencePosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70145:36)
    at getReferencesAtLocation (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70191:22)
    at getReferencesInContainer (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70186:21)
    at getReferencesInSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70178:24)
    at searchForName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70043:21)
    at getReferencedSymbolsForSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:69910:29)
    at Object.getReferencedSymbolsForNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:69820:24)
    at findAllReferencedSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:69665:43)
    at Object.findReferencedEntries (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:69654:36)
    at getReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83178:41)
    at Object.getReferencesAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83162:20)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:89868:71
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:89032:124
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1698:25)
    at combineProjectOutput (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:89032:30)
    at IOSession.Session.getReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:89867:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:89113:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90553:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90544:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90553:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90573:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by bsvipas** [comment]
@mjbvz Every time I run find all references on `options` property I get the exact same error in the TypeScript output.

/cc

**Comment by mjbvz** [comment]
Possibly https://github.com/Microsoft/TypeScript/issues/20792

@bsvipas Can you test this out once we pick up TypeScript 2.8 in vscode insiders? That should happen early next week sometime

**Comment by bsvipas** [comment]
@mjbvz, of course, I can! I can even download TS RC and use it in VS Code if needed.

**Comment by mjbvz** [comment]
Yes, please try the current `typescript@next`. The RC has a few bugs that have already been fixed in `@next`

**Comment by bsvipas** [comment]
@mjbvz With TS@next problem is fixed. You were right! 👍 When TS 2.8 will be released? Because I think VS Code need to have it in next release to fix this problem.

**Comment by mjbvz** [comment]
The latest VSCode insiders build now includes TS 2.8-insiders. We'll pick up the final release of 2.8 once it is released
