### ISSUE TITLE
Labels: Reduce call count to isEqualOrParent

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#45971]
* instrument `isEqualOrParent` to count how often is was called from there
* reload the workbench while showing a full explorer, one editor tab, and a few open editors
* 🐌  see that ~400 calls have been make to `isEqualOrParent` from the `tidify`-function but I can only spot a very UI locations in which I would wanna show a tildified-path. 

```
429 ->     at Object.isEqualOrParent (file:///Users/jrieken/Code/vscode/out/vs/base/common/paths.js:298:19)
    at tildify (file:///Users/jrieken/Code/vscode/out/vs/base/common/labels.js:73:75)
    at Object.getPathLabel (file:///Users/jrieken/Code/vscode/out/vs/base/common/labels.js:42:19)
    at FileLabel.ResourceLabel.render (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/labels.js:140:51)
```

<img width="690" alt="screen shot 2018-03-16 at 12 49 25" src="https://user-images.githubusercontent.com/1794099/37519190-7b544402-2918-11e8-9c42-6bc0e61a6ab5.png">

**Comment by jrieken** [comment]
added this to instrument the call

```ts
global.trace = new Map();
export function isEqualOrParent(path: string, candidate: string, ignoreCase?: boolean): boolean {

	let key = new Error().stack.split('\n').slice(1, 5).join('\n');
	let value = global.trace.get(key) || 0;
	global.trace.set(key, value + 1);
```
