### ISSUE TITLE
insiders build won't start due to sudden newer GLIBC requirement

### ISSUE THREAD

**Issue by darkvertex** [Microsoft/vscode#46264]
- VSCode Version: code-insiders-1.22.0-1521639327.el7.x86_64
- OS Version: CentOS Linux release 7.4.1708 (Core)

Does this issue occur when all extensions are disabled?: Yes

I usually update my code-insiders build every morning and as of a few days ago I can no longer open it. Running `code-insiders` never gives me a UI or an error. Some processes hang in the background and no windows appear.

When I run `code-insiders -s` I get:

```
> code-insiders -s
{ errorCode: 'load',
  moduleId: 'spdlog',
  neededBy: [ 'vs/platform/log/node/spdlogService' ],
  detail: 
   Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
       at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
       at Object.Module._extensions..node (module.js:598:18)
       at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at n (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:513)
       at bindings (/usr/share/code-insiders/resources/app/node_modules.asar/bindings/bindings.js:81:44)
       at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules.asar/spdlog/index.js:3:35)
       at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules.asar/spdlog/index.js:21:3)
       at Module.i._compile (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:731)
       at Object.Module._extensions..js (module.js:580:10)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:16:56)
       at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:587)
       at i (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:777)
       at Object.errorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:898)
       at e.triggerErrorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:952)
       at /usr/share/code-insiders/resources/app/out/vs/loader.js:13:657
       at ReadFileContext.callback (/usr/share/code-insiders/resources/app/out/vs/loader.js:16:267)
       at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13) }
```

Has the glibc version indeed changed recently? Is the newer version absolutely necessary?

Latest non-insiders/stable build (`code-1.21.1-1521039056.el7.x86_64`) works just fine. :/

If it helps:
```
> strings /usr/lib/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.0
GLIBC_2.4
GLIBC_2.1
GLIBC_2.1.3
GLIBC_2.3.2
GLIBC_2.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
Strings from current insiders build:
```
> strings /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node | grep -E "^GLIBCXX_"
GLIBCXX_3.4.18
GLIBCXX_3.4.14
GLIBCXX_3.4.19
GLIBCXX_3.4.21
GLIBCXX_3.4.11
GLIBCXX_3.4.20
GLIBCXX_3.4
```
vs strings from current stable build:
```
> strings /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node | grep -E "^GLIBCXX_"
GLIBCXX_3.4.18
GLIBCXX_3.4.14
GLIBCXX_3.4.19
GLIBCXX_3.4.11
GLIBCXX_3.4
```

**Comment by bpasero** [comment]
Seems like an issue related to requiring `spdylog`:

` neededBy: [ 'vs/platform/log/node/spdlogService' ],`
