### ISSUE TITLE
Can no longer require vscode-textmate from extensions as of 1.21.1 update

### ISSUE THREAD

**Issue by yo1dog** [Microsoft/vscode#46281]
- VSCode Version: 1.21.1
- OS Version: 10.10.5

Previously, if `vscode-textmate` was needed for an extension, the solution was to `require` the one that shipped with vscode rather than having it be a dependency of the extension and having to deal with compiling oniguruma. This is discussed [here](https://github.com/Microsoft/vscode-textmate/issues/23#issuecomment-248225621) on Microsoft/vscode-textmate#23. Example:

```typescript
require(path.join(require.main.filename, '../../node_modules/vscode-textmate/release/main.js'));
```

However, as of the 1.21.1 update the above line fails with:

```
Error: Cannot find module 'c:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js'
extensionHostProcess.js:453
  at Function.Module._resolveFilename (module.js:470:15)
  at Function.Module._load (module.js:418:25)
  at Function.J.Y.t.getExtensionPathIndex.then.o._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:784)
  at Module.require (module.js:498:17)
  at Module.patchedRequire [as require] (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\Mike\.vscode\extensions\siegebell.scope-info-0.2.0\out\src\text-mate.js:3:12)
  at Object.<anonymous> (C:\Users\Mike\.vscode\extensions\siegebell.scope-info-0.2.0\out\src\text-mate.js:22:3)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
```

What is the new way to require `vscode-textmate` from an extension?

**Comment by mjbvz** [comment]
Loading core vscode node_modules from extensions has never been officially supported. The comment linked to was a hack that our recent move to ASAR broke.

@alexandrudima Should know if there is a proper way to use `vscode-textmate` in an extension

**Comment by yo1dog** [comment]
I appreciate you looking into it. As far as I know, using `vscode-textmate` to reparse files is the only way to get scope/grammar/token information. However, as noted in the original comment, to try and require `vscode-textmate` from the extension would be difficult due to the binary dependencies.

I have heard rumors of this information possibly being exposed to extensions via an API at some point. That would be excellent.

**Comment by alexandrudima** [comment]
See https://github.com/Microsoft/vscode/issues/36997#issuecomment-366629363 
https://github.com/formulahendry/vscode-mysql/pull/25/files

**Comment by yo1dog** [comment]
Thanks very much!

To recap, the new solution is to use the following:

```typescript
const textmate = getCoreNodeModule('vscode-textmate');

/**
 * Returns a node module installed with VSCode, or null if it fails.
 */
function getCoreNodeModule(moduleName: string) {
  try {
    return require(`${vscode.env.appRoot}/node_modules.asar/${moduleName}`);
  } catch (err) { }
  
  try {
    return require(`${vscode.env.appRoot}/node_modules/${moduleName}`);
  } catch (err) { }
  
  return null;
}
```
