### ISSUE TITLE
VS Code frequently locking up for seconds, no high CPU usage, often when resuming focus

### ISSUE THREAD

**Issue by serprex** [Microsoft/vscode#46314]
````
[2018-03-21 19:52:49.478] [renderer1] [error] ViewModel is out of sync with Model!: Error: ViewModel is out of sync with Model!
    at e._ensureValidState (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1197:726)
    at e.convertModelPositionToViewPosition (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1206:246)
    at e.convertModelPositionToViewPosition (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1196:706)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1222:577
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:729)
    at f.forceTokenization (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1092:311)
    at f.tokenizeIfCheap (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1092:476)
    at Function.e.shouldAutoTrigger (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1594:59)
    at e._onNewContext (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1601:46)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1600:227
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:145:572)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:924)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:160)
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:152:119)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:3)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:413)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:145:552)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:924)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:160)
    at l (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:654)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:868)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:145:572)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:418)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:236)
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:146:170)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:418)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:236)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:184:97
    at n.Class.derive._oncancel.done (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:254)
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:146:343)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:418)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._oncancel.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at e.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2804:624)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:184:900
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:729)
    at e.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:182:865)
    at e.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:183:578)
    at n.Class.derive._oncancel.t.asWinJsPromise [as _oncancel] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:184:796)
    at n.Class.derive._oncancel._cancelAction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:152:618)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:441)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._oncancel.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at n.Class.derive._creator._cancelAction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:967)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:441)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:1014
    at Array.forEach (native)
    at n.Class.derive._oncancel.n.Class.derive.join [as _oncancel] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:946)
    at n.Class.derive._oncancel._cancelAction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:152:618)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:441)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._oncancel.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at n.Class.derive._creator._cancelAction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:967)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:441)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:272)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:272)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at n.Class.derive._creator._cancelAction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:967)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:441)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at n.Class.derive._creator._cancelAction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:967)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:441)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at n.Class.derive._creator._cancelAction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:967)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:148:441)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:719)
    at n.Class.derive._creator.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:904)
    at e.cancel (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1597:271)
    at e._onCursorChange (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1597:874)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1595:371
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:729)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1309:588
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:729)
    at t._emitStateChangedIfNecessary (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1171:952)
    at t.setStates (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1168:448)
    at t._onModelContentChanged (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1170:7)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1167:276
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1070:316
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:729)
    at t.endDeferredEmit (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1106:364)
    at f.pushEditOperations (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1083:155)
    at t.executeEdits (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1305:545)
    at e.applyEdits (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2830:413)
    at e.$tryApplyEdits (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3368:529)
    at e._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2858:983)
    at e._invokeHandler (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2858:701)
[2018-03-21 19:52:50.856] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:52:54.374] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:54:48.977] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:54:53.964] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:55:13.917] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:55:20.193] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:55:46.060] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:56:19.097] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:56:28.992] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:56:37.546] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:56:55.230] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:57:06.690] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:57:14.278] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:57:47.655] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:57:49.510] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:58:59.266] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 19:59:03.538] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:20:30.077] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:22:24.132] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:24:13.902] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:24:17.159] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:24:29.085] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:24:37.337] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:24:44.620] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:24:57.288] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:25:04.881] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:25:11.552] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:25:15.861] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:25:23.878] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:26:08.566] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:26:23.151] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:27:15.375] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:27:18.689] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:27:30.597] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:50:30.494] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:51:58.057] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:52:03.902] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:52:56.020] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:53:40.340] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:53:46.121] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:53:49.556] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:55:17.216] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:55:24.807] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:55:52.976] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:56:22.187] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:56:43.883] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 20:58:55.445] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:05:33.921] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:06:36.332] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:06:43.215] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:06:52.341] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:08:48.294] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:08:59.129] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:12:00.415] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:16:03.664] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:17:00.664] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:36:37.091] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:36:39.974] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:37:13.214] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:37:20.629] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:37:29.111] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:41:48.521] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:49:48.994] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:49:54.815] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:50:00.094] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:50:15.648] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:50:33.813] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:50:44.714] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:50:58.988] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 21:51:04.692] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 22:20:17.481] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 22:20:56.175] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 22:20:59.023] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 22:44:43.797] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 22:44:46.564] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 22:46:52.022] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:19:40.468] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:21:31.144] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:22:00.852] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:22:09.652] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:23:08.414] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:23:21.496] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:23:31.638] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:25:09.567] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:25:12.949] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:25:20.681] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:25:26.338] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:25:29.475] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:25:55.277] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:33:10.289] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:33:39.835] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:33:46.755] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:33:55.262] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:34:01.577] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:48:59.143] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:49:16.294] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:49:21.129] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:55:07.324] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:56:09.020] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:58:47.576] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-21 23:58:50.428] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:00:19.798] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:01:05.512] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:10:52.291] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:10:59.184] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:11:01.012] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:11:33.338] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:12:12.179] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:12:32.216] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:12:52.751] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:13:45.583] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:14:06.377] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:14:12.036] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:14:17.017] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:16:13.489] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:16:58.457] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:17:16.959] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:17:21.301] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:17:30.147] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:18:40.130] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:22:00.100] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:23:24.043] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:29:05.383] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:40:57.506] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 00:59:59.594] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:05:52.455] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:08:08.034] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:09:17.410] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:10:29.043] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:26:37.192] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:32:20.586] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:32:24.857] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:32:27.789] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:33:41.805] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:39:21.535] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:43:08.536] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
````
Problem persists with extensions disabled. Gets worse as time passes. Been happening for past few days

I was able to get the below to occur pretty frequently by repeatedly typing lines of `console.log()` 
````
[2018-03-22 01:52:39.315] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:53:08.881] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:55:42.268] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:07.722] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:23.833] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:26.689] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:38.037] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:40.587] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:55.365] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:56.786] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:56:59.551] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-03-22 01:57:01.618] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
````

**Comment by alexandrudima** [comment]
The stack trace is benign. i.e. does not cause freezes. But I could reproduce by having a completion item provider that edits the active editor in the provider and by having the same editor opened twice.

**Comment by alexandrudima** [comment]
Adding `verified`, because the test covers the stack trace.
