### ISSUE TITLE
Cannot read property 'getItem' of null:

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#46565]
1. Have a workspace with a folder
2. Remove that folder from the workspace such that you no longer have any folder in that workspace
3. Notice error in console

Assigning to @joaomoreno due to https://github.com/Microsoft/vscode/commit/83558baef98f2035e4ac155828f8d146f9e542d8 which seems to have caused this

```
 ERR Cannot read property 'getItem' of null: TypeError: Cannot read property 'getItem' of null
    at FileIconThemableWorkbenchTree.Tree.updateWidth (file:///Users/isidor/Development/vscode/out/vs/base/parts/tree/browser/treeImpl.js:122:34)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/parts/files/electron-browser/views/explorerViewer.js:179:26
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:103:38)
    at FileLabel.ResourceLabel.render (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/labels.js:171:31)
    at FileLabel.ResourceLabel.onFileDecorationsChanges (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/labels.js:83:22)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:238:125
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:103:38)
    at FileDecorationsService.registerDecorationsProvider (file:///Users/isidor/Development/vscode/out/vs/workbench/services/decorations/browser/decorationsService.js:312:42)
    at MainThreadDecorations.$registerDecorationProvider (file:///Users/isidor/Development/vscode/out/vs/workbench/api/electron-browser/mainThreadDecorations.js:71:57)
    at RPCProtocol._doInvokeHandler (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:145:27)
    at RPCProtocol._invokeHandler (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:130:54)
    at RPCProtocol._receiveRequest (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:88:50)
    at RPCProtocol._receiveOneMessage (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:71:26)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:17:92
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:175:21
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:103:38)
    at Socket.<anonymous> (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
log.ts:171   

ERR Cannot read property 'getItem' of null: TypeError: Cannot read property 'getItem' of null
    at FileIconThemableWorkbenchTree.Tree.updateWidth (file:///Users/isidor/Development/vscode/out/vs/base/parts/tree/browser/treeImpl.js:122:34)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/parts/files/electron-browser/views/explorerViewer.js:179:26
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:103:38)
    at FileLabel.ResourceLabel.render (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/labels.js:171:31)
    at FileLabel.ResourceLabel.onFileDecorationsChanges (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/labels.js:83:22)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:238:125
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:103:38)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:263:37
```

**Comment by joaomoreno** [comment]
I fixed a few stack errors. Now I see this when I remove the folder:

```
ERR Cannot read property 'getHighlight' of null: TypeError: Cannot read property 'getHighlight' of null
    at FileIconThemableWorkbenchTree.Tree.getHighlight (file:///Users/joao/Work/vscode/out/vs/base/parts/tree/browser/treeImpl.js:177:30)
    at file:///Users/joao/Work/vscode/out/vs/workbench/parts/files/electron-browser/views/explorerView.js:554:47
    at Throttler.queue (file:///Users/joao/Work/vscode/out/vs/base/common/async.js:123:34)
    at file:///Users/joao/Work/vscode/out/vs/base/common/async.js:240:93
    at file:///Users/joao/Work/vscode/out/vs/base/common/async.js:196:28
    at Object.notifySuccess [as _notify] (file:///Users/joao/Work/vscode/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/joao/Work/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/joao/Work/vscode/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (file:///Users/joao/Work/vscode/out/vs/base/common/winjs.base.js:1051:18)
    at file:///Users/joao/Work/vscode/out/vs/base/common/async.js:201:23
```


Then I see this when I add it back:

```
console.js:99 [Extension Host] TypeError: Cannot read property 'provideDecoration' of undefined
	at /Users/joao/Work/vscode/out/vs/workbench/api/node/extHostDecorations.js:33:81
	at /Users/joao/Work/vscode/out/vs/base/common/async.js:34:24
	at new Promise_ctor (/Users/joao/Work/vscode/out/vs/base/common/winjs.base.js:1656:17)
	at Object.asWinJsPromise (/Users/joao/Work/vscode/out/vs/base/common/async.js:33:16)
	at /Users/joao/Work/vscode/out/vs/workbench/api/node/extHostDecorations.js:33:32
	at Array.map (native)
	at ExtHostDecorations.$provideDecorations (/Users/joao/Work/vscode/out/vs/workbench/api/node/extHostDecorations.js:30:56)
	at RPCProtocol._doInvokeHandler (/Users/joao/Work/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:145:27)
	at RPCProtocol._invokeHandler (/Users/joao/Work/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:130:54)
	at RPCProtocol._receiveRequest (/Users/joao/Work/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:88:50)
	at RPCProtocol._receiveOneMessage (/Users/joao/Work/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:71:26)
	at /Users/joao/Work/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:17:92
	at /Users/joao/Work/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:175:21
	at /Users/joao/Work/vscode/out/vs/base/common/event.js:341:70
	at Emitter.fire (/Users/joao/Work/vscode/out/vs/base/common/event.js:103:38)
	at Socket.<anonymous> (/Users/joao/Work/vscode/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20) (at /Users/joao/Work/vscode/out/vs/workbench/api/node/extHostDecorations.js:36:29)
```

**Comment by isidorn** [comment]
@joaomoreno thanks, i believe I fixed the remaining errors by not reacting on events if I am disposed
