### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#46626]
1.22 insiders, no extensions.

Logged to the console when I open the workbench:

ERR Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/node_modules/vscode-languageclient/lib/client.js:1546:19)
	at Object.provideFoldingRanges (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/client/out/cssMain.js:88:27)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:882
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:95:387
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:75:378)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:95:350)
	at e.provideFoldingRanges (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:836)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:663:557
	at e._withAdapter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:654:925)
	at e.$provideFoldingRanges (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:663:519)
	at e._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:594:395)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:594:113)
	at e._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:593:237)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:593:6)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:592:75
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:594:929
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:30
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:263)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:142:487)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)

**Comment by aeschli** [comment]
Should be fixed in build 0a42355840f1e0f1ebd00565dc2b6d47a3b2e98f

**Comment by johnpapa** [comment]
this is happening for me in Version 1.23.0-insider (1.23.0-insider)

cc @fiveisprime

**Comment by shankarramr** [comment]
I too get this error in 1.23.0-insiders and one of the plugin red hat's Language Support for Java does not work.

**Comment by aeschli** [comment]
@johnpapa @shankarramr Please file new issues containing the stack trace you get.
