### ISSUE TITLE
Auto attach does not connect on ElementaryOS 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#46672]
Testing #46570

elementary OS 0.4.1 Loki
Built on "Ubuntu 16.04.2 LTS"

node v8.9.1

- create index.js
```js
setInterval(() => {
    console.log('ssss');
}, 1000);
```
- enable auto attach
- in the integrated terminal run `node --inspect index.js`

Dev tools show:
```
[ms-vscode.node-debug]Maximum call stack size exceeded
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
mainThreadExtensionService.ts:44 RangeError: Maximum call stack size exceeded
	at RegExp.exec (<anonymous>)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:96:44)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:105:13)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:105:13)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:105:13)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:105:13)
```

**Comment by aeschli** [comment]
Also tried on a bare Ubuntu 16.04 LTS. No stracktrace in the dev console,  ut also no connect.

**Comment by aeschli** [comment]
Same on Fedora 25. No stack trace

**Comment by aeschli** [comment]
Same when starting from an external terminal

**Comment by weinand** [comment]
basically the same issue as #46672

**Comment by weinand** [comment]
This feature is confined to the integrated terminal. Processes in external terminals are not picked up.

**Comment by aeschli** [comment]
Still the same problem in Version 1.22.0-insider
Commit 952b2a641da89a6c7bc28387474bc8afd47f0d2f
Date 2018-03-29T05:13:04.457Z
on Elementary OS

[ms-vscode.node-debug]Maximum call stack size exceeded
e.$onExtensionRuntimeError @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2867
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2867 RangeError: Maximum call stack size exceeded
	at RegExp.exec (<anonymous>)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:96:44)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:105:13)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:105:13)
	at walker (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug/out/node/extension/nodeProcessTree.js:105:13)

**Comment by aeschli** [comment]
But works on Fedora.

**Comment by aeschli** [comment]
Also works on a plain Ubuntu 16.04 LTS. Looks like it's related to Elementary OS.

**Comment by weinand** [comment]
What version of node.js are you using?

**Comment by aeschli** [comment]
[psout.txt](https://github.com/Microsoft/vscode/files/1859573/psout.txt)

**Comment by aeschli** [comment]
[psout.txt](https://github.com/Microsoft/vscode/files/1859576/psout.txt)

Node v8.9.1

**Comment by weinand** [comment]
Can reproduce with your ps output.
