### ISSUE TITLE
Cannot start VS Code from Applications menu in KDE Plasma 5.8 on Debian Stretch

### ISSUE THREAD

**Issue by Jesuszilla** [Microsoft/vscode#47000]
When I open VS Code from the Applications menu, I get this error:
``Uncaught Exception:
Error: EIO: i/o error, write
    at Object.fs.writeSync (fs.js:745:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:241:11)
    at Console.warn (console.js:51:16)
    at r.error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:182:690)
    at t.error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:185:730)
    at X (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:437:401)
    at e.invokeFunction (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:175:831)
``
- VSCode Version:
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64

This does not occur when running from command line, whether extensions are disabled or not. All extensions have been removed and the problem still occurs.
- OS Version:
Debian 9.4 Stretch

Steps to Reproduce:

1. Open VS Code from Applications > Development

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
I cannot reproduce unfortunately, I setup a VM with Stretch/KDE on it and both the CLI and launching via the application menu works. If you find out anything more we'd be glad to look into it further but it seems like something with your environment.

**Comment by myrdd** [comment]
I've had the same problem, but I cannot reproduce it anymore. For the record, I'll post what I've been capturing during the problem. First, my OS etc.:

* OS: Debian 9.4 (stretch)
* `code --version`
  * `1.22.1`
  * 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
  * `x64`
* `code-insiders --version`
  * `1.23.0-insider`
  * 609c4ba1e7abc39952ef5fb7f3a22c0be0349efe
  * `x64`

(I've always been using the stable version. However, yesterday I've installed the insiders version, just to try if it fixes a recent bug.)

**So this is what I've done:**

1. I've been using vscode (stable) for multiple days. (Suspend to RAM at night.)
2. I've been installing vscode-insiders.
3. I've executed vscode-insiders using the (KDE) menu entry. (The command is `/usr/share/code-insiders/code-insiders --unity-launch %F`.) (I've probably still been running vscode "stable" somewhere.)
4. I got a launch feedback (i.e. the vscode icon next to the mouse cursor)
5. Shortly after, I got a modal window showing **error message <span>#</span>1** (see below).
6. I've closed the modal window (and another one, which showed up shortly after closing the first one; it showed a short, generic error message.)
7. I've closed _all_ remaining vscode-"stable" windows, repeated steps 3–6, and got the same modal windows.
8. I tried to start code-insiders from the command-line (using the command `code-insiders --verbose`). I got an error message in the CLI, it's **error message <span>#</span>2** (see below). (I wondered about the first line saying `Sending env to running instance...`.)
9. I've identified multiple `code` and `code-insiders` processes still be running, and I've terminated them (`TERM` signal).
10. Running `code-insiders` in the CLI now works (vscode's main window and its "welcome" tab show up). Running `code-insiders --unity-launch` (the menu entry's command) works as well. Closing vscode ends all processes, so everything works as intended.
11. (**Strange thing, probably some other issue:** When trying to open vscode (either version) using the KDE menu, now no window shows up at all, only processes show up. When I tell KDE to run the command in a terminal (setting ”Run in terminal“ in the KDE Menu Editor), everything works fine. Without that option enabled, nope.)

I'll reboot my PC later to see what happens then.

BTW I had no extensions installed at all in the vscode-insiders installation.

### error message <span>#</span>1

Error message of opening `vscode-insiders` using the KDE menu. (Looks very similar to what @Jesuszilla posted.)

```
Uncaught Exception:
Error: EIO: i/o error, write
    at Object.fs.writeSync (fs.js:745:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:241:11)
    at Console.warn (console.js:51:16)
    at r.error (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:184:690)
    at t.error (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:187:730)
    at X (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:446:874)
    at e.invokeFunction (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:177:802)
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:447:824
    at n.Class.derive._creator.done (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:80:254)
    at Object.g [as _notify] (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:75:343)
    at Object.enter (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:78:418)
    at n.Class.derive._creator._run (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:719)
    at n.Class.derive._creator._chainedError (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:78)
    at n (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:76:929)
    at Object.g [as _notify] (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:75:170)
    at Object.enter (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:78:418)
    at n.Class.derive._oncancel._run (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:719)
    at n.Class.derive._oncancel._error (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:236)
    at Object.g [as _notify] (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:75:170)
    at Object.enter (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:78:418)
    at n.Class.derive._oncancel._run (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:719)
    at n.Class.derive._oncancel._error (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:79:236)
    at t.handlers.(anonymous function) (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:145:310)
    at e.onMessage (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:146:133)
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:144:526
    at e.fire (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:94:344)
    at Socket.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:151:187)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### error message <span>#</span>2

CLI error message on `code-insiders --verbose`.

```
[main 9:48:11 AM] Sending env to running instance...
[main 9:48:11 AM] [ 'TypeError: Cannot convert undefined or null to object',
  '    at Function.keys (<anonymous>)',
  '    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:37:233',
  '    at Array.forEach (native)',
  '    at Object.t.assign (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:37:199)',
  '    at e.openInBrowserWindow (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:407:461)',
  '    at e.doOpen (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:401:880)',
  '    at e.open (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:398:176)',
  '    at e.startOpenWindow (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:298:494)',
  '    at e.start (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:297:938)',
  '    at e.call (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:296:487)',
  '    at e.onCommonRequest (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:141:240)',
  '    at e.onMessage (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:141:76)',
  '    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:140:879',
  '    at e.fire (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:94:344)',
  '    at Socket.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:149:14)',
  '    at emitOne (events.js:96:13)',
  '    at Socket.emit (events.js:191:7)',
  '    at readableAddChunk (_stream_readable.js:178:18)',
  '    at Socket.Readable.push (_stream_readable.js:136:10)',
  '    at Pipe.onread (net.js:560:20)' ]
[main 9:48:11 AM] Lifecycle#kill()
```

**Comment by Tyriar** [comment]
It looks like the second error message is failing on this line:

https://github.com/Microsoft/vscode/blob/485a469b94b55f2af7e4b55eadc2bfe03d2a7639/src/vs/code/electron-main/windows.ts#L1048

The actual call that's causing the exception is `Object.keys(undefined)` (or `null`). This means that `this.initialUserEnv` must be `undefined | null`.
