### ISSUE TITLE
Can't build VSCode on Windows

### ISSUE THREAD

**Issue by jasonpezzimenti** [Microsoft/vscode#47020]
I Can't install VSCode on Windows. node-gyp errors.

I've already seen the other issues in this repo and other repos related to gyp and node errors when building VS Code but the suggestions and solutions on those pages haven't worked for me.

Can anyone provide any insight? How can I fix this? I have all the right versions of node, python, gyp, build tools, VS, etc. And honestly, I have no idea what the below error messages even mean.

Please help, brain is hurting:

```
C:\Users\Jay\Documents\GitHub\vscode>yarn
yarn install v1.5.1
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.8: The platform "win32" is incompatible with this module.
info "vscode-fsevents@0.3.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/16] ⠁ gc-signals: '-Goutput_dir=.' ]
[6/16] ⠁ native-watchdog: using node@8.11.1 | win32 | x64
[3/16] ⠂ keytar: '-Goutput_dir=.' ]
[4/16] ⠂ native-is-elevated: spawn args   '-Goutput_dir=.' ]
error An unexpected error occurred: "C:\\Users\\Jay\\Documents\\GitHub\\vscode\
ode_modules\\gc-signals: Command failed.
Exit code: 7
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\\Users\\Jay\\Documents\\GitHub\\vscode\
ode_modules\\gc-signals
Output:
C:\\Users\\Jay\\Documents\\GitHub\\vscode\
ode_modules\\gc-signals>if not defined npm_config_node_gyp (node \"C:\\Program Files\
odejs\
ode_modules\
pm\\bin\
ode-gyp-bin\\\\..\\..\
ode_modules\
ode-gyp\\bin\
ode-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp info spawn C:\\Python27\\python.EXE
gyp info spawn args [ 'C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\Jay\\\\Documents\\\\GitHub\\\\vscode\\\
ode_modules\\\\gc-signals\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\Jay\\\\.node-gyp\\\\iojs-1.7.12\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\Jay\\\\.node-gyp\\\\iojs-1.7.12',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Jay\\\\.node-gyp\\\\iojs-1.7.12\\\\<(target_arch)\\\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\Jay\\\\Documents\\\\GitHub\\\\vscode\\\
ode_modules\\\\gc-signals',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\Jay\\\\Documents\\\\GitHub\\\\vscode\\\
ode_modules\\\\gc-signals\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn D:\\Installed Software\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\Bin\\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn D:\\Installed Software\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\Bin\\MSBuild.exe ENOENT
gyp ERR! stack     at _errnoException (util.js:1022:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\Program Files\\\
odejs\\\
ode.exe\" \"C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\bin\\\
ode-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\Jay\\Documents\\GitHub\\vscode\
ode_modules\\gc-signals
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:





C:\Users\Jay\Documents\GitHub\vscode>
```

- VSCode Version:
- OS Version: Windows 10, Home Edition

Steps to Reproduce:

1. Follow instructions on VSCode's Contributions page
2. Observe entire universe implode

**Comment by jasonpezzimenti** [comment]
The bot's links have nothing to do with this.

**Comment by jasonpezzimenti** [comment]
Can someone please help? I'm pulling my hair out, here!

**Comment by weinand** [comment]
@jasonpezzimenti you are trying to **build** VS Code on Windows, not **installing** it, right?

**Comment by jasonpezzimenti** [comment]
@weinand exactly, the link you posted is what I'm following. I'm interested in contributing to VSCode, and I'm up to the point where it says:

Finally, install all dependencies using Yarn:
```
cd vscode
yarn
```

But `yarn` fails with the error shown in my question above.

**Comment by weinand** [comment]
I just did:

```
cd vscode
git pull
yarn
.\scripts\code.bat
```

and that worked fine for me of Windows 10.

I'm using `yarn 1.3.2` and `node 8.9.3`.

**Comment by jasonpezzimenti** [comment]
@weinand Thank you, I will install those versions now. In case that doesn't work, would you happen to know which file I need to edit so that I can edit the file path that it uses to locate Visual Studio (the paths you can see above in error log)?

**Comment by jasonpezzimenti** [comment]
@weinand ok so now I have the following versions installed:
MSBuild Tools and VS 2015
node 8.9.3
yarn 1.3.2
node-gyp -v v3.6.2
python v2.7

Just ran `yarn` again from within vscode folder and failed. Exact same error.

Is there anything else you can suggest?

**Comment by weinand** [comment]
@jasonpezzimenti sorry, but I have no deeper insight into the build process on Windows but I'll assign this to someone who should know.

**Comment by jasonpezzimenti** [comment]
@weinand Thanks for the help, I really appreciate it. I learned a few things I'd forgotten along the way, too.

**Comment by jasonpezzimenti** [comment]
@weinand This issue has been resolved:

Open: C:\Users\Jase\Documents\GitHub\vscode\node_modules\native-keymap\build\binding.sln in Visual Studio 2015, install whatever missing dependencies there are, then Rebuild the solution in Release mode. Close VS and then CMD > `cd \documents\github\vscode` && `yarn`.
