### ISSUE TITLE
jsdom errors raised during debug using WSL in JS node project 

### ISSUE THREAD

**Issue by lfurzewaddock** [Microsoft/vscode#47045]
- VSCode Version: 1.8.1, 1.21.1, 1.22.0-insider
- OS Version: MS Windows 10 Pro version: 1709 OS build: 16299.309
- Ubuntu 16.04.3 LTS (WSL / aka Bash on Windows)
- Node v8.11.1
- npm 5.6.0

Steps to Reproduce:

1. Set-up JS project which includes jsdom (See sample files below and error messages further below).

**File package.json**
```
{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "jsdom": "^11.6.2"
  }
}
```
**File .vscode/launch.json**
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch in WSL",
      "useWSL": true,
      "program": "${workspaceFolder}/jsdom.environment.js"
    }
  ]
}
```
**File jsdom.environment.js**
```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM();

global.window = dom.window;
global.document = dom.window.document;
window.console = global.console;

Object.keys(document).forEach((property) => {
  if (typeof global[property] === "undefined") {
    global[property] = document[property];
  }
});

global.navigator = {
  userAgent: "node.js",
};

global.documentRef = document;
```

2. Debug on WSL with 'breakpoints' option 'All exceptions' enabled.

Does this issue occur when all extensions are disabled?: Yes

**Errors raised;**
```
Exception has occurred: Error
Error: Cannot find module 'canvas'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at some.moduleName (d:\Projects\Dev\temp\node_modules\jsdom\lib\jsdom\utils.js:203:23)
    at Array.some (<anonymous>)
    at Object.<anonymous> (d:\Projects\Dev\temp\node_modules\jsdom\lib\jsdom\utils.js:201:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
	

Exception has occurred: Error
Error: Cannot find module 'canvas-prebuilt'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at some.moduleName (d:\Projects\Dev\temp\node_modules\jsdom\lib\jsdom\utils.js:203:23)
    at Array.some (<anonymous>)
    at Object.<anonymous> (d:\Projects\Dev\temp\node_modules\jsdom\lib\jsdom\utils.js:201:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
	

Exception has occurred: Error
Error: Cannot find module 'bufferutil'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\Projects\Dev\temp\node_modules\ws\lib\buffer-util.js:29:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
	
Exception has occurred: Error
Error: Cannot find module 'utf-8-validate'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\Projects\Dev\temp\node_modules\ws\lib\validation.js:4:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by roblourens** [comment]
This sounds like an issue with your project. Do you see those errors if you launch using the terminal?

**Comment by lfurzewaddock** [comment]
No, just during debug with breakpoints 'All exceptions' option enabled. 

To further simplify the steps to recreate, I've found that just requiring jsdom is enough to trigger these errors so the file above 'jsdom.environment.js' can be changed to ;

**File jsdom.environment.js**

```
const jsdom = require("jsdom");
```

In the terminal even with a try/catch wrapped around the require statement, no errors are raised.

I have been having issues with debug breakpoints not binding/working and during testing to try and resolve those issues I discovered this issue reported. Incidentally, I downgraded to VSCode 1.8.1 and breakpoints work again, but with a small UI quirk: the red dot disappears when the yellow arrow is at the same position.

**Comment by roblourens** [comment]
Do you need to set cwd in your launch config?

**Comment by weinand** [comment]
@lfurzewaddock What happens if you enable 'Uncaught exceptions' instead?

**Comment by lfurzewaddock** [comment]
@roblourens, I tried adding `"cwd": "${workspaceRoot}"` then, `"cwd": "${workspaceFolder}"` and there was no change for either alteration to the launch config.

**Comment by lfurzewaddock** [comment]
@weinand, No errors are raised if just the 'Uncaught Exceptions' breakpoints option is enabled.

**Comment by weinand** [comment]
This means that your program is catching all those errors and only if you enable 'All Exceptions' the errors become visible in VS Code (which is the expected behaviour).
