### ISSUE TITLE
VSCode cannot start with no network connection

### ISSUE THREAD

**Issue by Antares95** [Microsoft/vscode#47174]
Issue Type: <b>Bug</b>

1.unplug the network cable or disconnect wifi.
2.start VSCode

error infomation:
net.js:10
const cares = process.binding('cares_wrap');
                      ^

Error: EFILE
    at net.js:10:23
    at net.js:1645:3
    at NativeModule.compile (bootstrap_node.js:535:7)
    at NativeModule.require (bootstrap_node.js:475:18)
    at internal/child_process.js:6:13
    at internal/child_process.js:903:3
    at NativeModule.compile (bootstrap_node.js:535:7)
    at NativeModule.require (bootstrap_node.js:475:18)
    at child_process.js:12:23
    at child_process.js:542:3

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|15.89GB (12.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1

</details>
Reproduces only with extensions

**Comment by Antares95** [comment]
duplicated..... sorry....
