### ISSUE TITLE
Can't see installed extensiones

### ISSUE THREAD

**Issue by equiman** [Microsoft/vscode#47200]
- VSCode Version: 1.21.1 (1.21.1)
- OS Version: macOS High Sierra 10.13.3 (17D102)

Steps to Reproduce:

1. Open VS Code
2. Go To Extensions
    - Installed section is empty.
4. cmd+shift+p and select: Developer: Show Running Extensions
    - Show a tab with all installed extensions running
5. Extension menu (... dots) and select "Show Installed Extension" 
    - Show this popup message: Cannot read property 'id' of undefined

![screen shot 2018-04-04 at 11 18 04](https://user-images.githubusercontent.com/933393/38320629-bc22c40e-37fa-11e8-953e-bc93df0a0549.png)

Does this issue occur when all extensions are disabled?: Yes
But only show preinstalled extensions.

![screen shot 2018-04-04 at 11 19 14](https://user-images.githubusercontent.com/933393/38320641-c2169ad4-37fa-11e8-91cd-9ada7cc3c7bd.png)

Output Log (Window) show this:

```
[2018-04-04 11:25:12.294] [renderer1] [error] Cannot read property 'contributes' of undefined: TypeError: Cannot read property 'contributes' of undefined
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4854:838
    at Array.filter (native)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4854:802
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84)
[2018-04-04 11:25:12.396] [renderer1] [error] Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3600:953
    at Array.map (native)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3600:917
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84)
[2018-04-04 11:25:12.405] [renderer1] [error] Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2643:985
    at Array.map (native)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2643:905
    at n.Class.define.cancel.then (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:151:517)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2643:879
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
[2018-04-04 11:25:14.510] [renderer1] [error] Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:584:1001
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:202)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:556)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:380)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:73:823)
	at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:527:384)
	at e._receiveReply (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:587:165)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:586:500)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:585:494
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:588:343
[2018-04-04 11:25:14.898] [renderer1] [error] Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at Object.o [as getGalleryExtensionIdFromLocal] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1271:739)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4626:174
    at Array.filter (native)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4626:140
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
[2018-04-04 11:25:15.867] [renderer1] [error] Unable to download data from Visual Studio Marketplace. Status code: 400
[2018-04-04 11:25:25.743] [renderer1] [error] Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3600:953
    at Array.map (native)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3600:917
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:149:523)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:971)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:148:277)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:84) (2 errors in total)
```

This message call my attention: [2018-04-04 11:25:15.867] [renderer1] [error] Unable to download data from Visual Studio Marketplace. Status code: 400

Then I test my connection with cmd+shift+p and select: Developer: Toggle Shared Process
And test with:  Show recommended extensions and returns Status code: 200

![screen shot 2018-04-04 at 11 38 01](https://user-images.githubusercontent.com/933393/38321292-c81af810-37fc-11e8-9e78-530c58bc4219.png)

**Comment by ramya-rao-a** [comment]
Can you open dev tools before this happens, enable  'break on all errors', and attach a screen shot for all the breakpoints that's hit?

<img width="225" alt="screen shot 2018-03-28 at 16 15 46" src="https://user-images.githubusercontent.com/1794099/38034779-4c224366-32a3-11e8-9df3-759046caebdf.png">

**Comment by equiman** [comment]
Steeps:

1. Open vscode and open devtools.
2. Change to extensions tab.
![screen shot 2018-04-05 at 09 11 49](https://user-images.githubusercontent.com/933393/38371287-a81029cc-38b1-11e8-8e0d-d1ae5fcba322.png)
3. Continue button:
![screen shot 2018-04-05 at 09 12 22](https://user-images.githubusercontent.com/933393/38371292-ad9e4f40-38b1-11e8-9954-584388a5ebe6.png)
3. Hit Extensions menu and select "Show Installed extensions". Show this message but don't show any exception on dev tools.
![screen shot 2018-04-05 at 09 12 45](https://user-images.githubusercontent.com/933393/38371357-d7603140-38b1-11e8-9238-2012ac2113c5.png)

**Comment by ramya-rao-a** [comment]
Hmm.. The breakpoints hit in the screenshots are not related to the `Cannot read property ...` issue.

Do you see this happening in the latest [Insiders](https://code.bisualstudio.com/insiders) as well?

**Comment by equiman** [comment]
Yes, on steep 4 I explained that. When show this popup error, don't stop on DevTools.

I'm not using insiders version.

There is another thing that I can do?

**Comment by equiman** [comment]
Still happen on VSCode Version: 1.22.0

**Comment by equiman** [comment]
I have installed insiders version, and not happen the same:

![screen shot 2018-04-06 at 10 03 43](https://user-images.githubusercontent.com/933393/38428644-e6484db6-3981-11e8-8448-95c3d20b92d5.png)

Even, I installed some extensions to see what happens:

![screen shot 2018-04-06 at 10 05 33](https://user-images.githubusercontent.com/933393/38428815-56331a20-3982-11e8-9129-d75b886b4081.png)
![screen shot 2018-04-06 at 10 05 52](https://user-images.githubusercontent.com/933393/38428826-5c181184-3982-11e8-81c6-fff3ce9a58a0.png)

**Comment by equiman** [comment]
I found this folder ~/.vscode/extensions and I remove all files inside it and works again. 

![screen shot 2018-04-06 at 11 13 49](https://user-images.githubusercontent.com/933393/38432055-dd65a748-398b-11e8-9380-aa8e3a7ba15c.png)

I think this bug, maybe will be related to something inside this folder.

**Comment by ramya-rao-a** [comment]
It might have been related to one of the extensions that was installed. 

I'll close this issue as you dont see this problem anymore. If you see this again, please provide the list of all extensions you have installed.

**Comment by equiman** [comment]
Once again the same. All it's working fine until I tried to uninstall Java extension related. I can uninstalled as normal user then I had opened as admin with `sudo code` and uninstall this Java extensions.

Close vscode and open as normal user and now the bug happen again.

**Comment by ramya-rao-a** [comment]
@sandy081 Can you think of any reason why opening as admin vs normal user would have any effect on how we fetch installed extensions in the view?

**Comment by sandy081** [comment]
I do not think so. It is interested to see
- What extensions are still there in user extensions folder
- See shared process log to check for any un-exepected activity
