### ISSUE TITLE
myTree.reveal errors when switching between documents

### ISSUE THREAD

**Issue by pltrant** [Microsoft/vscode#47262]
- VSCode Version: 1.22
- OS Version: Windows 10

Steps to Reproduce:

1. Create a `treeDataProvider` that has events to trigger `onDidChangeActiveTextEditor` and `onDidChangeTextEditorSelection`.  Those events should refresh the tree based upon the content of the document.
2.  Click to switch between different documents.
  a.) when switching to a document like the Welcome page, then back to the original document, performing a `myTree.reveal` results in no error, but also does not reveal any node.
  b.) when switching to another normal document, `myTree.reveal` results in `Error: Cannot resolve tree item for element 0/0:`

![mytreereveal](https://user-images.githubusercontent.com/9040032/38394433-154060b0-38f4-11e8-90f5-6a4a151f676f.gif)

This is very difficult to explain, so I'm going to include a .vsix of my extension and some test files so you can more easily reproduce the issues.

[gsl-1.3.3.vsix.zip](https://github.com/Microsoft/vscode/files/1881999/gsl-1.3.3.vsix.zip)

**Comment by pltrant** [comment]
I noticed when clicking between documents, it would actually cause the `onDidChangeActiveTextEditor` and `onDidChangeTextEditorSelection` events to both trigger.  That's understandable, but also unnecessary for my setup, so I was looking into a way to prevent the `onDidChangeTextEditorSelection` event in this scenario.  I noticed the `event.kind` was undefined when this happens (instead of one of the expected values for [TextEditorSelectionChangeKind](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditorSelectionChangeKind)), so I added logic to not refresh my view when it's undefined, which resolved my original issue (of 2 events refreshing the tree back-to-back), but I also noticed it then doesn't cause the `Error: Cannot resolve tree item for element 0/0:` error on `myTree.reveal` when switching betwen actual documents as previously noted.  However, like when switching to something like the Welcome page, it simply does nothing under this setup (doesn't reveal a node in the tree despite having been called in `onDidChangeActiveTextEditor`).

```javascript
vscode.window.onDidChangeTextEditorSelection((e) => {
    if (e.kind) {
        this.refresh();
    }
});
```

**Comment by sandy081** [comment]
To verify:

- Install the attached vsix
- Open a folder in VS Code
- Create a file `test.gsl` with following data
```
!
: "test1"
.
: "test2"
.
: "test3"
.
: "test4"
.
: "test5"
.
```
- Create another file `test2.gsl` with following data
```
!
: "test6"
.
: "test7"
.
: "test8"
.
: "test9"
.
```
- Open above two files in two tabs
- Switch between two tabs

Expected: There should not be any errors in the console

**Comment by pltrant** [comment]
@sandy081, if you want me to open a new bug for this, let me know, but I noticed today that sometimes when I highlight multiple lines, it still throws an error:

```
WARNING: Promise with no error callback:2

Object
  exception: Object
  error: null
  promise :Object
    _value: Object
    _isException: true
    _errorId: 2
  id: 2
Error: Cannot resolve tree item for element 0/0:test3
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:57
	at n.Class.define.cancel.then (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:517)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:484:953
	at n.Class.define.cancel.then (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:517)
	at t.resolveTreeNode (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:484:893)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:483:778
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:971)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:80:277)
	at n.Class.derive._creator._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._creator._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:523)
	at n.Class.derive._creator.then (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:517)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:79:374)
	at n.Class.derive._creator._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._creator._setCompleteValue (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:776)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:951)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:80:277)
	at n.Class.derive._creator._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._creator._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:523)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:971)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:80:277)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:523)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:482:918
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:971)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:80:277)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:84)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:523)
	at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:545:791)
	at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:165)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:473)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

Screenshot of what I selected from the previous test.gsl file:

![image](https://user-images.githubusercontent.com/9040032/41303813-f6b448f8-6e33-11e8-8bcf-90875600da30.png)

**Comment by sandy081** [comment]
@pltrant Please file a new issue with steps to reproduce.
