### ISSUE TITLE
TypeScript: occurrences request failed with error

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#47470]
Saw this today in selfhost in the file `textFileEditorModel.ts` using TS 2.8.1:

```
[Error  - 11:01:49 AM] 'occurrences' request failed with error.
Error processing request. Debug Failure. Did not expect MethodDeclaration to have an Identifier in its trivia
Error: Debug Failure. Did not expect MethodDeclaration to have an Identifier in its trivia
    at NodeObject.addSyntheticNodes (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83665:34)
    at processNode (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83709:29)
    at NodeObject.createChildren (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83723:21)
    at NodeObject.getChildren (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83749:22)
    at getTokenAtPositionWorker (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:66283:43)
    at getTouchingToken (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:66270:16)
    at Object.getTouchingPropertyName (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:66266:16)
    at getReferencesAtLocation (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71721:44)
    at getReferencesInContainer (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71717:21)
    at getReferencesInSourceFile (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71709:24)
    at searchForName (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71578:21)
    at getReferencedSymbolsForSymbol (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71434:29)
    at Object.getReferencedSymbolsForNode (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71349:24)
    at Object.getReferenceEntriesForNode (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:71192:58)
    at getSemanticDocumentHighlights (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70200:57)
    at Object.getDocumentHighlights (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70189:20)
    at getDocumentHighlights (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:84687:42)
    at Object.getOccurrencesAtPosition (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:84672:31)
    at IOSession.Session.getOccurrences (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:91137:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90743:61)
    at /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:92067:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:92058:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:92067:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:92087:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:93288:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#23278
