### ISSUE TITLE
Can't start Code Helper service. VScode Version:1.22.1 OS: OS X 10.11 EI Capitan

### ISSUE THREAD

**Issue by 3lackrush** [Microsoft/vscode#47486]
- VSCode Version: 1.22.1
- OS Version: OS X 10.11 EI Capitan

Steps to Reproduce:

1. Start VScode IDE
2. The output console throw the following error:
[Error - 19:39:18] Starting client failed
Error: spawn /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)

So i try to start the code helper service by myself. The location of Code helper is /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS
i tried to execute with this command "./Code helper" but the program trow this error: "module.js:472
    throw err;
    ^

Error: Cannot find module '/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/Resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3"

it seems to be the resource file was missing. Then i tried to reinstall the vscode. but the result was also the same.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@3lackrush you should not need to start the helper yourself, it almost sounds as if your installation is not complete, can you fully reinstall?
