### ISSUE TITLE
Terminal exception when debugging extension in Code - OSS

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#47489]
Repro steps:

1. `./scripts/code.sh`
2. Create an extension (`yo code`, ...)
3. Open ext folder
4. F5

```
TypeError: Cannot read property 'syncScrollArea' of undefined
    at Terminal.reset (/home/daniel/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Terminal.js:1457:22)
    at Object.escapedStateHandler.c (/home/daniel/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Parser.js:39:14)
    at Parser.parse (/home/daniel/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Parser.js:192:48)
    at Terminal._innerWrite (/home/daniel/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Terminal.js:822:38)
    at /home/daniel/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Terminal.js:807:23
```

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1379
