### ISSUE TITLE
An exception occured : TypeError During Debug

### ISSUE THREAD

**Issue by Bastorx** [Microsoft/vscode#47581]
VSCode version: 1.22.1
Client OS : Mac OS Sierra
Server OS: Docker - Alpine.3.7

How to reproduce, debug an app nodejs in a Docker Alpine with node with --inspect=0.0.0.0:9229

An exception occured : TypeError
TypeError: argument string is required
    at Object.parse (/Users/app/node_modules/media-typer/index.js:141:12)
    at normalizeType (/Users/app/node_modules/type-is/index.js:239:21)
    at tryNormalizeType (/Users/app/node_modules/type-is/index.js:258:13)
    at typeis (/Users/app/node_modules/type-is/index.js:48:14)
    at typeofrequest (/Users/app/node_modules/type-is/index.js:142:11)
    at checkType (/Users/app/node_modules/body-parser/lib/types/json.js:230:21)
    at jsonParser (/Users/app/node_modules/body-parser/lib/types/json.js:116:11)
    at Layer.handle [as handle_request] (/Users/app/node_modules/express/lib/router/layer.js:95:6)
    at trim_prefix (/Users/app/node_modules/express/lib/router/index.js:317:14)
    at /Users/app/node_modules/express/lib/router/index.js:284:8
    at Function.process_params (/Users/app/node_modules/express/lib/router/index.js:335:13)
    at next (/Users/app/node_modules/express/lib/router/index.js:275:11)
    at compression (/Users/app/node_modules/compression/index.js:220:6)
    at Layer.handle [as handle_request] (/Users/app/node_modules/express/lib/router/layer.js:95:6)
    at trim_prefix (/Users/app/node_modules/express/lib/router/index.js:317:14)
    at /Users/app/node_modules/express/lib/router/index.js:284:8
    at Function.process_params (/Users/app/node_modules/express/lib/router/index.js:335:13)
    at next (/Users/app/node_modules/express/lib/router/index.js:275:11)
    at expressInit (/Users/app/node_modules/express/lib/middleware/init.js:40:6)
    at Layer.handle [as handle_request] (/Users/app/node_modules/express/lib/router/layer.js:95:6)
    at trim_prefix (/Users/app/node_modules/express/lib/router/index.js:317:14)
    at /Users/app/node_modules/express/lib/router/index.js:284:8
    at Function.process_params (/Users/app/node_modules/express/lib/router/index.js:335:13)
    at next (/Users/app/node_modules/express/lib/router/index.js:275:11)
    at query (/Users/app/node_modules/express/lib/middleware/query.js:45:6)
    at Layer.handle [as handle_request] (/Users/app/node_modules/express/lib/router/layer.js:95:6)
    at trim_prefix (/Users/app/node_modules/express/lib/router/index.js:317:14)
    at /Users/app/node_modules/express/lib/router/index.js:284:8

**Comment by mjbvz** [comment]
This looks like an error in the program itself, not vscode?

**Comment by Bastorx** [comment]
I fixed this by adding --nolazy parameters to node (with inspect)

This stack was weird x')
