### ISSUE TITLE
Python Debugging - Odd Behavior

### ISSUE THREAD

**Issue by jd-mtb** [Microsoft/vscode#47589]
- VSCode Version:
- OS Version:

Steps to Reproduce:

In testing python debugging simply, after having some issues in a project, I noticed a few random-feeling issues related to python debugging. This could easily be related to my corporate environment but I would like some help figuring this out.

To reproduce, I simply run the following:

_____
try:
    tryagain = (1/0)
except:
    print("you cannot divide by zero")
_____

If I run this a few times I get several different behaviors including successful debugging.

However, here are some of the alternative endings:

Unknown command (output):
PS C:\Users\TDPOFFU\Documents\GitRepos> cd 'c:\Users\TDPOFFU\Documents\GitRepos'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'C:\Users\TDPOFFU\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher.py' 'c:\Users\TDPOFFU\Documents\GitRepos' '56490' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' 'c:\Users\TDPOFFU\Documents\GitRepos\_Ansible\Python_Galaxy\python_ansiblegalaxy_init.py'
unknown command b'\x00\x00\x00\x00'

MemoryError (output):
PS C:\Users\TDPOFFU\Documents\GitRepos> cd 'c:\Users\TDPOFFU\Documents\GitRepos'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'C:\Users\TDPOFFU\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher.py' 'c:\Users\TDPOFFU\Documents\GitRepos' '56509' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' 'c:\Users\TDPOFFU\Documents\GitRepos\_Ansible\Python_Galaxy\python_ansiblegalaxy_init.py'
Traceback (most recent call last):
  File "C:\Users\TDPOFFU\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 1729, in loop
    cmd()
  File "C:\Users\TDPOFFU\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 1942, in command_set_exception_info
    name = read_string(self.conn)
  File "C:\Users\TDPOFFU\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 163, in read_string
    res = res + conn.recv(strlen - len(res))
MemoryError

Hung Terminal:
Debugging never starts, the pre-command is shown to have run but it never attaches to the main terminal as the bottom remains blue instead of the debug mode orange. Output below:
PS C:\Users\TDPOFFU\Documents\GitRepos> cd 'c:\Users\TDPOFFU\Documents\GitRepos'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'C:\Users\TDPOFFU\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher.py' 'c:\Users\TDPOFFU\Documents\GitRepos' '56522' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' 'c:\Users\TDPOFFU\Documents\GitRepos\_Ansible\Python_Galaxy\python_ansiblegalaxy_init.py'

Other Issues:
In some rare cases, the entire PC will crash.

Others VS hangs only, stuck in a debug state.

Sometimes I get a debugger failed to load message but debugging mode will enter. Closing this notification and pressing shift+F5 will get me back to normal.

I suspect it could have to do with pylint installation though I allowed VScode to install it for me at some time ago.

NOTE: Other examples, such as the following, will NOT reproduce ANY of the above errors for me. This indicates it may be related to assigning a value compared to print, or some other difference between the two.
____
try:
    print(1/0)
except:
    print("you cannot divide by zero")
____

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jd-mtb** [comment]
Sorry, thanks!

**Comment by jd-mtb** [comment]
Fixed it!
(Pretty darn sure at least)

If anyone stumbles across this I think I know what fixed it for me. There is actually a warning in the successful runs about something called 'cython'. It is needed to debug in vscode successfully and I don't think my linter was working properly until I got this working as well. You need to install "visual studio build tools" if you don't have them as well. Most references online say you need the 14 version of the tools but I didn't get it working until I used the below links which references can also be found to this when searching for 'install cython'.

Link found here:
https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017
Direct Link:
https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15

Just install with basic + the build tools which is the top left tick box. It took a few GBs though, there is probably some smaller combination of tick boxes to reduce the size but I didn't fuss with it.

Once that is installed you just need to run the install cython command which looks like this (you can do this before rebooting in my experience):

C:\WINDOWS\system32>"C:\Program Files\Python\Python36\python.exe" "C:\Users\<REDACTED>\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\experimental\ptvsd\ptvsd\pydevd\setup_cython.py" build_ext --inplace


My understanding of that cython does is limited, I think it is something that allows python code to be modified to c and ran as c. The linter and debugger must expect certain characteristics (maybe, only, speed) which is why it will work 'sometimes'. I wish I could help more but I just followed through with the only warning message I got and it works now!
