### ISSUE TITLE
ApplicationInsights makes requests even when Telemetry is disabled (new vscode profile)

### ISSUE THREAD

**Issue by gima** [Microsoft/vscode#47687]
- VSCode Version: 1.21.1 
- OS Version: Arch Linux

Steps to Reproduce:

1. Open VSCode with fresh user profile (`--user-data-dir /tmp/new-vscode-profile`)
2. Specify the following User Settings and close VSCode
~~~
{
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "update.channel": "none",
    "extensions.autoUpdate": false,
    "workbench.startupEditor": "none"
}
~~~
3. Capture network traffic and start VSCode
4. Observe DNS query to `dc.services.visualstudio.com` and TLS connection to returned IP on port 443.

Does this issue occur when all extensions are disabled?: Yes

**Bug Description**
Opening VSCode with telemetry disabled causes uncalled-for network requests.

The request is:  
`GET https://dc.services.visualstudio.com/api/profiles/AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217/appId`
Returned HTTP status code is 404.

* The request is being done by 
`app/extensions/git/node_modules/applicationinsights`  
*(Empty window, no welcome screen, as it was disabled by user setting above).*  
HTTP request caused by:
~~~
CorrelationIdManager.queryCorrelationId = function : Library/CorrelationIdManager.js
CorrelationIdManager.queryCorrelationId(..); : Library/Config.js
set: function : Library/Config.js
this.profileQueryEndpoint = : Library/Config.js
~~~

Stacktrace at function responsible for the HTTP request:
~~~
at Function.CorrelationIdManager.queryCorrelationId (/tmp/vsc/resources/app/extensions/git/node_modules/applicationinsights/out/Library/CorrelationIdManager.js:35:10)
at Config.set [as profileQueryEndpoint] (/tmp/vsc/resources/app/extensions/git/node_modules/applicationinsights/out/Library/Config.js:31:34)
at new Config (/tmp/vsc/resources/app/extensions/git/node_modules/applicationinsights/out/Library/Config.js:21:35)
at NodeClient.TelemetryClient (/tmp/vsc/resources/app/extensions/git/node_modules/applicationinsights/out/Library/TelemetryClient.js:24:22)
at new NodeClient (/tmp/vsc/resources/app/extensions/git/node_modules/applicationinsights/out/Library/NodeClient.js:25:42)
at Object.setup (/tmp/vsc/resources/app/extensions/git/node_modules/applicationinsights/out/applicationinsights.js:41:33)
~~~

* Additional request is being done by 
app/extensions/git/node_modules/applicationinsights
*(When User Settings is left open, and restored on VSCode startup).*

References to `dc.services.visualstudio.com` can be found in the following files:
* app/node_modules/applicationinsights
* app/extensions/html/node_modules/applicationinsights
* app/extensions/git/node_modules/applicationinsights
* app/extensions/typescript/node_modules/applicationinsights
* app/extensions/markdown/node_modules/applicationinsight
* app/extensions/json/node_modules/applicationinsights

In my view this is not supposed to happen. Telemetry should not be sent when telemetry is disabled. I don't know whether this is a bug in each of the [base,html,git,typescript,markdown,json] extensions or in applicationinsights (https://github.com/Microsoft/ApplicationInsights-node.js)

Hopefully this was enough information to fix the problem.

**Comment by joaomoreno** [comment]
Should've forwarded this longer ago, sorry @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@gima Thanks for all the details. Can you also share how you captured all this information? I tried Network capture in Chrome dev tools and Fiddler, but was unable to catch the outgoing request to `dc.services.visualstudio.com`

Regardless, following the stack traces you have provided I was able to make a fix which should be available in tomorrow's [Insiders](https://code.visualstudio.com/insiders). Can you download the Insiders tomorrow and confirm if the fix has worked for you?

**Comment by joaomoreno** [comment]
Thanks @ramya-rao-a !
