### ISSUE TITLE
I/O error on trying to launch from Albert/dmenu

### ISSUE THREAD

**Issue by MrHuds0n** [Microsoft/vscode#47776]
- VSCode Version: 1.22.1
- OS Version: elementary OS 0.4 Loki

Steps to Reproduce:

1. Launch VSCode from albert or dmenu twice.

Does this issue occur when all extensions are disabled?: Yes

```
Uncaught Exception:
Error: EIO: i/o error, write
    at Object.fs.writeSync (fs.js:745:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:241:11)
    at Console.warn (console.js:51:16)
    at r.error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:184:690)
    at t.error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:187:730)
    at X (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:443:874)
    at e.invokeFunction (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:177:998)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:444:824
    at n.Class.derive._creator.done (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:80:254)
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:75:343)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:78:418)
    at n.Class.derive._creator._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:79:719)
    at n.Class.derive._creator._chainedError (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:79:78)
    at n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:76:929)
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:75:170)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:78:418)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:79:719)
    at n.Class.derive._oncancel._error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:79:236)
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:75:170)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:78:418)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:79:719)
    at n.Class.derive._oncancel._error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:79:236)
    at t.handlers.(anonymous function) (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:142:643)
    at e.onMessage (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:143:460)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:141:865
    at e.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:94:344)
    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:148:536)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by bpasero** [comment]
@Tyriar seen this before?

**Comment by Tyriar** [comment]
Nope, not sure what's going on here. @MrHuds0n when you say launch twice do you mean launching twice in quick succession, as in trying to launch a second time before the first window is up?
