### ISSUE TITLE
Debug console does not support links to errors

### ISSUE THREAD

**Issue by alejandromagnorsky** [Microsoft/vscode#48015]
- VSCode Version: 1.22.2
- OS Version: Mac OS 10.13.4 (High Sierra)
- Node Version: 9.11.1

Steps to Reproduce:

1. Insert the following in launch.json:
 ```
{
      "type": "node",
      "request": "launch",
      "name": "Example",
      "outputCapture": "std",
      "program": "${workspaceRoot}/index.js"
}
```
2. Create an index.js file with simply `a` as the content.

3. Run the Example using the debug tool from VSCode:
```
/usr/local/bin/node --inspect-brk=3587 index.js 
Debugger listening on ws://127.0.0.1:3587/d0ddfdf1-fa6a-4335-a26d-e71aee45d6e0
Debugger attached.
/Users/xxx/Developer/api/index.js:1
(function (exports, require, module, __filename, __dirname) { a;
                                                              ^
ReferenceError: a is not defined
    at Object.<anonymous> (/Users/xxx/Developer/api/index.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:651:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Waiting for the debugger to disconnect...
ReferenceError: a is not defined
index.js:1
    at Object.<anonymous> (/Users/xxx/Developer/api/index.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:651:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

So, not only the error show twice (for some reason) but also the line /Users/xxx/Developer/api/index.js:1:63 is not a link, thus I have to manually go to the file and line to see the error. I believe this was doable before in the Debug Console so I am confused about why it stopped working.

Does this issue occur when all extensions are disabled?: Yes

Thank you.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34026
