### ISSUE TITLE
version control doesn't refresh

### ISSUE THREAD

**Issue by akshaybabloo** [Microsoft/vscode#48097]
Version control doesn't refresh when it is committed using an external software example GitKraken or GitHub Desktop

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Edit a file on VSCode
2. Commit it using an external software.

**Update**

Even refresh button doesn't update it; it works once in a while.

**Comment by bpasero** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.

**Comment by akshaybabloo** [comment]
OK this will take time

**Comment by akshaybabloo** [comment]
**I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)**
It still happens here.

**I verified that this issue is happening outside of a node_modules folder. Our file watcher ignores this folder!**
I am not including `node_modules`, it happens to all the text files. In my case a python code and markdown file.

---

**What OS are you on**
Windows 10

**Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?**
I am not using any workspace, I opend a md file with vscode. vscode picked up the git folder and strted tracking the file.

**Do you have files.useExperimentalFileWatcher: true configured in settings?**
No

**What is your configured files.watcherExclude setting?**

```json
"files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/*/**": true
  }
```

---

**It reproduces with any folder or workspace you open**
Yes

**The files/folders you open are on your local disk and not on a network share nor a UNC drive**
Yes, they are local files.

**The files/folders you open are not behind a symbolic link**
No, not symbolically linked.

**The folder(s) opened use the exact same casing as they are on disk**
This is not applicable as I am opening a local file.

**It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)**
Yes. i have tried it with Notepad++ and Pycharm.

From the command prompt
```
C:\Users\aksha>code --verbose

[main 5:46:39 PM] Starting VS Code
[main 5:46:39 PM] from: c:\Program Files\Microsoft VS Code\resources\app
[main 5:46:39 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false }
[main 5:46:39 PM] Resolving machine identifier...
[main 5:46:39 PM] Resolved machine identifier: 1302a08bf5c6448343880a82820daa76e1f40a78fc9e7d000a81003e7b34680c
[main 5:46:39 PM] update#setState idle
[2112:0423/174640.325:ERROR:jump_list.cc(274)] Failed to append custom category 'Recent Workspaces' to Jump List due to system privacy settings.
[2112:0423/174653.883:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174653.939:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174654.045:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 5:46:54 PM] windowsService#whenSharedProcessReady
[main 5:46:54 PM] windowsService#startCrashReporter
[main 5:46:55 PM] windowsService#setRepresentedFilename 1
[2112:0423/174655.664:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 5:46:55 PM] IPC#vscode-workbenchLoaded
[2112:0423/174656.543:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174656.543:INFO:CONSOLE(233)] "Overwriting extension <<.html>> to now point to mime <<text/x-html>>", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (233)
[2112:0423/174656.543:INFO:CONSOLE(233)] "Overwriting extension <<.htm>> to now point to mime <<text/x-html>>", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (233)
[2112:0423/174656.543:INFO:CONSOLE(3301)] "Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: c:\Program Files\Microsoft VS Code\resources\app\extensions\python\syntaxes\MagicPython.tmLanguage.json.
New grammar file: C:\Users\aksha\.vscode\extensions\magicstack.magicpython-1.0.12\grammars\MagicPython.tmLanguage", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (3301)
[main 5:46:58 PM] windowsService#isFocused 1
[2112:0423/174658.710:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174706.626:INFO:CONSOLE(260)] "%c[Extension Host] %cvscode-icons is active! %c(at activate (C:\Users\aksha\.vscode\extensions\robertohuertasm.vscode-icons-7.22.0\out\src\index.js:41:13))", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (260)
[2112:0423/174709.309:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 5:47:09 PM] update#checkForUpdates, state =  idle
[main 5:47:09 PM] update#setState checking for updates
[main 5:47:09 PM] RequestService#request https://vscode-update.azurewebsites.net/api/update/win32-x64/stable/3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
[main 5:47:11 PM] update#setState idle
[2112:0423/174712.466:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174712.474:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174718.435:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174722.187:VERBOSE1:CONSOLE(8479)] "Main._createAppUI: 90.766845703125ms", source: chrome-devtools://devtools/bundled/inspector.js (8479)
[2112:0423/174722.260:VERBOSE1:CONSOLE(8484)] "Main._showAppUI: 87.81298828125ms", source: chrome-devtools://devtools/bundled/inspector.js (8484)
[2112:0423/174722.435:VERBOSE1:CONSOLE(8485)] "Main._initializeTarget: 13.743896484375ms", source: chrome-devtools://devtools/bundled/inspector.js (8485)
[2112:0423/174748.412:INFO:CONSOLE(79)] "Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\aksha\AppData\Roaming\Code\clp'

Error: ENOENT: no such file or directory, scandir 'C:\Users\aksha\AppData\Roaming\Code\clp'", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (79)
[2112:0423/174757.076:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174757.306:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174757.686:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174758.437:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174801.063:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174801.212:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174801.473:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174802.298:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174803.735:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174803.921:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174804.202:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174804.340:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174806.502:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174806.611:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174806.821:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174807.447:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174809.198:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174809.340:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174809.407:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174809.560:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174810.062:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174810.236:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174810.508:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174811.472:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174812.946:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[2112:0423/174812.998:INFO:CONSOLE(2896)] "%c[node.js Watcher]%c", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (2896)
[2112:0423/174813.012:INFO:CONSOLE(2896)] "%c[node.js Watcher]%c", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (2896)
[2112:0423/174813.143:INFO:CONSOLE(2897)] "%c[node.js Watcher]%c >> normalized", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (2897)
[2112:0423/174813.644:INFO:CONSOLE(2896)] "%c[node.js Watcher]%c", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (2896)
[2112:0423/174813.657:INFO:CONSOLE(2896)] "%c[node.js Watcher]%c", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (2896)
[2112:0423/174813.709:INFO:CONSOLE(2897)] "%c[node.js Watcher]%c >> normalized", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (2897)
[2112:0423/174821.118:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
```

From developers tool
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE openWorkbench configuration {"_":[],"help":false,"h":false,"version":false,"v":false,"wait":false,"w":false,"diff":false,"d":false,"add":false,"a":false,"goto":false,"g":false,"new-window":false,"n":false,"unity-launch":false,"reuse-window":false,"r":false,"open-url":false,"performance":false,"p":false,"prof-startup":false,"verbose":true,"logExtensionHostCommunication":false,"disable-extensions":false,"disableExtensions":false,"list-extensions":false,"show-versions":false,"nolazy":false,"issue":false,"skip-getting-started":false,"skip-release-notes":false,"sticky-quickopen":false,"disable-restore-windows":false,"disable-telemetry":false,"disable-updates":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"status":false,"s":false,"file-write":false,"file-chmod":false,"appRoot":"c:\\Program Files\\Microsoft VS Code\\resources\\app","machineId":"1302a08bf5c6448343880a82820daa76e1f40a78fc9e7d000a81003e7b34680c","execPath":"C:\\Program Files\\Microsoft VS Code\\Code.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\9df8557d6adb430fc73b481e968f423d-1.22.2-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"C:\\Users\\aksha\\AppData\\Roaming\\Code\\logs\\20180423T174639"},"isInitialStartup":true,"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"C:\\Users\\aksha\\AppData\\Roaming\\Code\\CachedData\\3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9","backupPath":"C:\\Users\\aksha\\AppData\\Roaming\\Code\\Backups\\1524461073092","windowId":1,"logLevel":0,"fullscreen":false,"highContrast":false,"accessibilitySupport":false,"baseTheme":"vs-dark","backgroundColor":"#002b36","perfEntries":["mark","main:started",1524462398583,0,"mark","main:appReady",1524462399009,0,"mark","main:loadWindow",1524462400068,0],"perfStartTime":1524462398583,"perfWindowLoadTime":1524462400069}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE lifecycle: starting up (startup kind: 1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE lifecycle: phase changed (value: 2)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE lifecycle: phase changed (value: 3)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:233 Overwriting extension <<.html>> to now point to mime <<text/x-html>>
(anonymous) @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:233
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:233 Overwriting extension <<.htm>> to now point to mime <<text/x-html>>
(anonymous) @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:233
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3301 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: c:\Program Files\Microsoft VS Code\resources\app\extensions\python\syntaxes\MagicPython.tmLanguage.json.
New grammar file: C:\Users\aksha\.vscode\extensions\magicstack.magicpython-1.0.12\grammars\MagicPython.tmLanguage
e.register @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3301
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE lifecycle: phase changed (value: 4)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] vscode-icons is active! (at activate (C:\Users\aksha\.vscode\extensions\robertohuertasm.vscode-icons-7.22.0\out\src\index.js:41:13))
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE SCMService#registerSCMProvider
2/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1305 TRACE CommandService#executeCommand setContext
log.ts:147 TRACE CommandService#executeCommand deleteLeft
dom.ts:319 [Violation] 'requestAnimationFrame' handler took 87ms
log.ts:147 TRACE CommandService#executeCommand type
dom.ts:319 [Violation] 'requestAnimationFrame' handler took 57ms
5log.ts:147 TRACE CommandService#executeCommand type
dom.ts:319 [Violation] 'requestAnimationFrame' handler took 52ms
2log.ts:147 TRACE CommandService#executeCommand type
2dom.ts:187 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
browser.ts:139 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
[Violation] 'setTimeout' handler took 54ms
log.ts:147 TRACE CommandService#executeCommand type
[Violation] Forced reflow while executing JavaScript took 31ms
2log.ts:147 TRACE CommandService#executeCommand type
4log.ts:147 TRACE CommandService#executeCommand deleteLeft
3log.ts:147 TRACE CommandService#executeCommand type
async.ts:555 [Violation] 'setTimeout' handler took 63ms
[Violation] Forced reflow while executing JavaScript took 45ms
log.ts:147 TRACE CommandService#executeCommand type
log.ts:147 TRACE CommandService#executeCommand deleteLeft
async.ts:555 [Violation] 'setTimeout' handler took 76ms
[Violation] Forced reflow while executing JavaScript took 54ms
log.ts:147 TRACE CommandService#executeCommand deleteLeft
async.ts:555 [Violation] 'setTimeout' handler took 79ms
log.ts:147 TRACE CommandService#executeCommand deleteLeft
async.ts:555 [Violation] 'setTimeout' handler took 60ms
log.ts:147 TRACE CommandService#executeCommand deleteLeft
log.ts:147 TRACE CommandService#executeCommand workbench.action.files.save
2fileService.ts:1109 [node.js Watcher] [CHANGED] c:\Users\aksha\Documents\GitHub\Go-Notes\README.md
fileService.ts:1123 [node.js Watcher] >> normalized [CHANGED] c:\Users\aksha\Documents\GitHub\Go-Notes\README.md
2fileService.ts:1109 [node.js Watcher] [CHANGED] c:\Users\aksha\Documents\GitHub\Go-Notes\README.md
fileService.ts:1123 [node.js Watcher] >> normalized [CHANGED] c:\Users\aksha\Documents\GitHub\Go-Notes\README.md
log.ts:147 TRACE CommandService#executeCommand setContext
```

**Comment by bpasero** [comment]
@akshaybabloo that makes me wonder if this is file events related actually because you say that even when you refresh in the git view, the view is not updated? Can you somehow record a screen cast or screen shots how this looks like for you?

**Comment by dgreensp** [comment]
I have the same issue.  However, running the Git Refresh command or pressing the Refresh button in the Version Control panel does always bring things up to date.  The Refresh button in the file explorer does not.  I don't have any other file-watching issues that I'm aware of.

I have been using VS Code for about six months, and I've never seen VS Code's version control status update in response to external changes (e.g. committing from the command-line, which I tend to prefer).  Is it supposed to?  It would be a big improvement if it did.

I set `"git.autorefresh": true` in my settings, but it doesn't seem to have helped.

Can someone confirm that VS Code is actually supposed to notice if the git status of files changes externally?  I've just never seen that behavior.

**Comment by bpasero** [comment]
@dgreensp 
VS Code is using different file watching strategies depending on your OS and your setup. If something does not seem to work here is a list of things to check:

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] What OS are you on
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
