### ISSUE TITLE
VS Code dont start and no show editor window

### ISSUE THREAD

**Issue by deniscass** [Microsoft/vscode#48240]
Hi guys,

Today i restart my machine after a hang Windows crash and restart my VS Code to continue my work in some projects with NodeJS. But VS Code dont start, only shows window freeze app with menus and no contente in editor window. I attempt to remove latest updates but no success. I uninstall and reinstall VS Code again and no luck. 

Visual Studio 2017 Works fine, but my favorite code editor is buggy and unusable. Can help-me? I attempt remove %APPDATA%/Code and .vscode dirs, rename my Project folders but without success.

- VSCode Version: 1.22.1
- OS Version: Windows 10 64bits latest version all updates installed

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@deniscass can you run "`code --verbose`" from the command line and attach the output here?

**Comment by deniscass** [comment]
Hi BPasero, i get these logs:

Microsoft Windows [versão 10.0.16299.371]
(c) 2017 Microsoft Corporation. Todos os direitos reservados.

C:\Users\deniscass>code --verbose

[main 23:12:44] Starting VS Code
[main 23:12:45] from: c:\Program Files\Microsoft VS Code\resources\app
[main 23:12:45] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false }
[main 23:12:45] Resolving machine identifier...
[main 23:12:45] Resolved machine identifier: e1b767c8d3212144675e14536254985c62e315ca2662937424bece6b319cff4e
[main 23:12:45] update#setState idle
[12656:0421/231246.093:INFO:CONSOLE(79)] "WARNING: Promise with no error callback:3", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (79)
[12656:0421/231246.096:INFO:CONSOLE(79)] "[object Object]", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (79)
[12656:0421/231246.096:INFO:CONSOLE(79)] "Uncaught Error: listen EADDRINUSE \\.\pipe\0dfabac870057ed0a4d91b81119a741a-1.22.2-shared-sock

Error: listen EADDRINUSE \\.\pipe\0dfabac870057ed0a4d91b81119a741a-1.22.2-shared-sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1247:19)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1413:5)
    at t.serve (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:133:456)
    at new n.Class.derive._oncancel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:70:378)
    at Object.t.serve (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:133:386)
    at t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:279:774)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:280:128", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (79)
[12656:0421/231246.571:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 23:12:46] windowsService#whenSharedProcessReady
[12656:0421/231246.608:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[12656:0421/231246.633:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 23:12:47] windowsService#startCrashReporter
[main 23:12:47] windowsService#setRepresentedFilename 1
[12656:0421/231247.403:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[main 23:12:47] IPC#vscode-workbenchLoaded
[main 23:12:48] windowsService#isFocused 1
[12656:0421/231249.624:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[12656:0421/231249.638:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[12656:0421/231249.770:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[12656:0421/231249.775:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)
[12656:0421/231249.932:INFO:CONSOLE(1305)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1305)

**Comment by nickdbush** [comment]
Not sure if this is the same issue, or a differnet one:

![image](https://user-images.githubusercontent.com/10998201/39095830-d44e1b44-463e-11e8-8a76-67091e3d25d6.png)

**Comment by bpasero** [comment]
@deniscass could it be that another instance of VS Code is already running when you try to start? Can you restart fully and run "`code --verbose`" from the command line again?

 @nickdbush your installation seems to be corrupt, maybe try to uninstall and reinstall to see if that fixes it?

**Comment by faultfactory** [comment]
I am seeing a similar issue. 

code --verbose produces the following: 

  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false }
[main 2:54:37 PM] Resolving machine identifier...
[main 2:54:37 PM] Resolved machine identifier: 63ebc2801851bf4005e4503d7c0e08473a1f4387a8a40d41ed49c401f2b9124e
[main 2:54:37 PM] update#setState idle

C:\Users\Jesse>code -verbose
1.22.2
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
x64

C:\Users\Jesse>code --verbose

[main 3:00:15 PM] Starting VS Code
[main 3:00:15 PM] from: c:\Program Files\Microsoft VS Code\resources\app
[main 3:00:15 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false }
[main 3:00:15 PM] Resolving machine identifier...
[main 3:00:15 PM] Resolved machine identifier: 63ebc2801851bf4005e4503d7c0e08473a1f4387a8a40d41ed49c401f2b9124e
[main 3:00:15 PM] update#setState idle

**Comment by bpasero** [comment]
@faultfactory is that with stable or insiders of VS Code?

**Comment by faultfactory** [comment]
@bpasero 
This would be a download from the standard vscode site so I have to assume it's the stable build. 
FYI, I also uninstalled and reinstalled when attempting to resolve this. It didn't make a difference.

**Comment by deniscass** [comment]
Hi guys,
I was using the stable version of VS Code and Insider version too. In both i get these bugs with two graphic cards. Then i get same issues with some NodeJS/Eléctron apps and some Windows Store apps as Instagram. Then, i reset my PC and install all again and Works fine, but VS Code still have issues. As workaround i can set the specific graphic card to default use of VS Code and no issues. Uninstall and install dont resolve for me.
