### ISSUE TITLE
`workspace.fetchTasks` throws a `TypeError`

### ISSUE THREAD

**Issue by alpaix** [Microsoft/vscode#48260]
#### VSCode Version
Version 1.23.0-insider
Commit 1fdf60b882f0edc6753fc964b253783eb46d56ef
Date 2018-04-19T13:37:07.476Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

#### Steps to Reproduce

1. Open a workspace [Microsoft/vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node).
2. Try calling `workpace.fetchTasks()` API on it.

**Expected:**
Get a collection of available tasks

**Actual:**
The API call threw the following exception
> "TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:98:689
    at Array.forEach (<anonymous>)
    at Object.t.assign (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:98:655)
    at Object.e.from (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2858:885)
    at Object.e.from (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2861:833)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2864:460
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:146:729)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:61)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:866)
    at n.Class.derive._creator._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:307)
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:301)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:109)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:866)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:560)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:146:709)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:61)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:866)
    at n.Class.derive._creator._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:307)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:146:729)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:61)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:866)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:307)
    at o (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3933:582)
    at n.Class.derive._creator.done (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:169)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:146:871)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:61)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:866)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:307)
    at e.resolveOk (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2815:452)
    at e._receiveReply (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2873:708)
    at e._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2873:6)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2871:837
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2874:942
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:166:917)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:295:1008)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)"

**Comment by dbaeumer** [comment]
Able to reproduce. Looking into a fix.

**Comment by dbaeumer** [comment]
@alpaix can you please verify. Thanks
