### ISSUE TITLE
Smoketest: flaky preferences test

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#48261]
It happens quite rarely but these failures still happen in the smoketest:

```
2018-04-20T08:44:54.6730078Z   1) Test Preferences turns off editor line numbers and verifies the live change:
2018-04-20T08:44:54.6730629Z      Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
2018-04-20T08:44:54.6731088Z       at Timeout.<anonymous> (D:\a\1\s\node_modules\mocha\lib\runnable.js:226:19)
2018-04-20T08:44:54.6731361Z 
2018-04-20T08:44:54.6732236Z   2) Test Preferences changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:
2018-04-20T08:44:54.6733022Z      Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
2018-04-20T08:44:54.6733670Z       at Timeout.<anonymous> (D:\a\1\s\node_modules\mocha\lib\runnable.js:226:19)
```

I've only seen it happening on Windows: https://monacotools.visualstudio.com/Monaco/_build/index?buildId=38457&_a=summary&tab=artifacts

---

### Test Preferences turns off editor line numbers and verifies the live change

Times out with:

```
[2018-04-20T08:43:47.569Z] getElements .line-numbers
```

![test_preferences_turns_off_editor_line_numbers_and_verifies_the_live_change](https://user-images.githubusercontent.com/22350/39040955-5592b3d0-4488-11e8-9666-c29babec540c.png)

### Test Preferences changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it

Times out with:

```
[2018-04-20T08:44:07.674Z] getElements .part.activitybar.right
```

![test_preferences_changes__workbench_action_togglesidebarposition__command_key_binding_and_verifies_it](https://user-images.githubusercontent.com/22350/39040954-55772b88-4488-11e8-9643-151d09169204.png)

---

[smoketest.log](https://github.com/Microsoft/vscode/files/1931397/smoketest.log)

**Comment by joaomoreno** [comment]
We probably need a bit more logging here. Maybe we can also attach the user settings into the build artifacts and see whether the smoketests messed it up.

**Comment by sandy081** [comment]
Looks like the first test that is writing into the settings caused some errors. Is there a screenshot while writing in to settings and saving it?

**Comment by joaomoreno** [comment]
None 😄 But we can add

**Comment by joaomoreno** [comment]
Just hit again: https://vscode.visualstudio.com/VSCode/_build?buildId=1782

**Comment by sandy081** [comment]
@joaomoreno Is this still flaky?

**Comment by joaomoreno** [comment]
Let's close it.
