### ISSUE TITLE
Build scripts broken ?

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#48393]
I tried to compile a local VS Code version today using `npm run gulp vscode-win32-x64` and this fails without any message. Digging a little around showed that the `packageTask` task fails with

```
[13:05:50] Error: ENOENT: no such file or directory, open 'C:\Users\dirkb\Projects\mseng\VSCode\vscode\out-vscode\vs\workbench\workbench.main.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at computeChecksum (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\gulpfile.vscode.js:205:20)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\gulpfile.vscode.js:193:22
    at Array.forEach (<anonymous>)
    at computeChecksums (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\gulpfile.vscode.js:191:12)
    at Gulp.<anonymous> (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\gulpfile.vscode.js:225:21)
    at module.exports (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:214:10)
```

The package tast assumes `out-vscode` while the compile task still compiles to `out-build`.

**Comment by joaomoreno** [comment]
Three problems.

First is a bad usage of `localize`, which can't be passed along as a function: @egamma 

- https://github.com/Microsoft/vscode/blob/master/extensions/npm/src/main.ts#L30
- https://github.com/Microsoft/vscode/blob/master/extensions/npm/src/main.ts#L45

Created https://github.com/Microsoft/vscode/pull/48400

---

Second is an insufficient error message: @dbaeumer 

```
2018-04-23T05:11:08.8982313Z main.js(36,50): localize function (bound to localize) used in an unusal way.
2018-04-23T05:11:08.8984373Z main.js(51,141): localize function (bound to localize) used in an unusal way.
2018-04-23T05:11:08.9002495Z Failed to rewite file: main.js
```

Maybe we should print the faulty file in absolute path form instead of relative, to make it easier to find: https://github.com/Microsoft/vscode-nls-dev/issues/17

---

Third is an improper pipe connect somewhere between our build pipeline and vscode-nls-dev, because when such errors happen gulp should actually blow up. I can look into that.

**Comment by dbaeumer** [comment]
Regarding the third item. It happens here:

https://github.com/Microsoft/vscode/blob/master/build/gulpfile.extensions.js#L88

If there is something I can change in `vscode-nls-dev` please let me know.

**Comment by joaomoreno** [comment]
This was a tough one. It's incredible how after so long I'm still learning more about this. It seems that `pipe` doesn't forward `error` calls. It's apparently a well known annoyance in the gulp world.

I believe that since we rarely have errors which are not TypeScript compilation errors (which travel down the pipeline differently than stream errors), we just don't hit this often...?

I could solve it with using [`gulp-plumber`](https://github.com/floatdrop/gulp-plumber) and the following commit: https://github.com/Microsoft/vscode/commit/1891516706d10064b5a2282ec73cce1076188432
