### ISSUE TITLE
TypeError: Cannot read property 'inputBox' of undefined

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#48543]
* Open user `settings.json`
* Add the following:
```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "heading.2.markdown",
                "settings": {
                    "foreground": "#ff00ff",
                }
            }
        ]
    },
```
* Save

```
  ERR Cannot read property 'inputBox' of undefined: TypeError: Cannot read property 'inputBox' of undefined
    at QuickInputService.updateStyles (file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/quickinput/quickInput.js:380:24)
    at QuickInputService.Themable.onThemeChange (file:///Users/alex/src/vscode/out/vs/workbench/common/theme.js:366:18)
    at file:///Users/alex/src/vscode/out/vs/workbench/common/theme.js:354:99
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:103:38)
    at file:///Users/alex/src/vscode/out/vs/workbench/services/themes/electron-browser/workbenchThemeService.js:216:50
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:103:38)
    at WorkspaceService.triggerConfigurationChange (file:///Users/alex/src/vscode/out/vs/workbench/services/configuration/node/configurationService.js:550:48)
    at WorkspaceService.onUserConfigurationChanged (file:///Users/alex/src/vscode/out/vs/workbench/services/configuration/node/configurationService.js:422:18)
    at file:///Users/alex/src/vscode/out/vs/workbench/services/configuration/node/configurationService.js:53:105
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:103:38)
    at file:///Users/alex/src/vscode/out/vs/platform/configuration/node/configuration.js:34:136
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:103:38)
    at file:///Users/alex/src/vscode/out/vs/base/node/config.js:151:53
    at file:///Users/alex/src/vscode/out/vs/base/node/config.js:78:24
    at /Users/alex/src/vscode/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (original-fs.js:439:3)
```

**Comment by bpasero** [comment]
@alexandrudima @chrmarti owns this
