### ISSUE TITLE
getWorkspaceStats prints errors to console

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#48570]
* install the MemFS-sample extensions: https://marketplace.visualstudio.com/items?itemName=jrieken.vscode-memfs
* have a workspace configuration as outlined
* open a window, notice errors appear on the console...

<img width="580" alt="screen shot 2018-04-24 at 18 48 31" src="https://user-images.githubusercontent.com/1794099/39201720-22ca5f14-47f0-11e8-9bae-afbb6983447f.png">

```
  ERR File not found (memfs:/package.json): Error: File not found (memfs:/package.json)
    at new FileOperationError (file:///Users/jrieken/Code/vscode/out/vs/platform/files/common/files.js:199:32)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/services/files/electron-browser/remoteFileService.js:279:31
    at Object.notifySuccess [as _notify] (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1051:18)
    at argDone (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1828:37)
    at Promise.then.errors.(anonymous function) (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1853:78)
    at Object.notifySuccess [as _notify] (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:916:30)
    at Promise_ctor._run (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._error (file:///Users/jrieken/Code/vscode/out/vs/base/common/winjs.base.js:1056:18)
    at LazyPromise.resolveErr (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/lazyPromise.js:53:22)
    at RPCProtocol._receiveReplyErr (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:196:26)
    at RPCProtocol._receiveOneMessage (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:147:26)
```

**Comment by jrieken** [comment]
<img width="1175" alt="screen shot 2018-04-26 at 10 36 21" src="https://user-images.githubusercontent.com/1794099/39295062-b7ef80f8-493d-11e8-94eb-628da94348c1.png">

**Comment by chrmarti** [comment]
Missed that we dropped a check with `resolveFile` when reviewing #48296. Thanks @ramya-rao-a! /fyi @kieferrm
