### ISSUE TITLE
Error: Header must provide a Content-Length property

### ISSUE THREAD

**Issue by iDev0urer** [Microsoft/vscode#4869]
- VSCode Version: 0.10.11
- OS Version: Windows 7

I am getting the following error when trying to create a language server: 
```
    at Socket.<anonymous> (c:\Users\FA-0042\Documents\Projects\javascript\MavensMate-VSCode\node_modules\vscode-jsonrpc\lib\messageReader.js:95:19)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

My method that starts the server:
```typescript
private startApexLanguageServer() {
        
        let serverModule = this.context.asAbsolutePath(path.join("server", "out", "server.js"));
        let debugOptions = { execArgv: ["--nolazy", "--debug=6004"] };
        
        let serverOptions: ServerOptions = {
            debug: { module: serverModule, options: debugOptions },
            run: { module: serverModule },
        };
        
        let clientOptions: LanguageClientOptions = {
            documentSelector: ["apex"],
            synchronize: {
                configurationSection: "apexServer",
                fileEvents: [
                    vscode.workspace.createFileSystemWatcher("**/.cls"),
                    vscode.workspace.createFileSystemWatcher("**/.apex"),
                ],
            },
        };
        
        let client = new LanguageClient("Apex Language Server", serverOptions, clientOptions);
        let disposable = client.start();
        
        this.context.subscriptions.push(disposable);
        
    }
```

And the server itself
```typescript
'use strict';
import * as vscode from 'vscode';
import { createConnection, IConnection, TextDocuments, ITextDocument, Diagnostic,
    InitializeParams, InitializeResult } from 'vscode-languageserver';

console.log("Apex server initialized");

// Create a new connection for the server.
let connection: IConnection = createConnection(process.stdin, process.stdout);
let documents: TextDocuments = new TextDocuments();

documents.listen(connection);

// After the server has started the client sends an initilize request. The server receives
// in the passed params the rootPath of the workspace plus the client capabilites. 
let workspaceRoot: string;
connection.onInitialize((params): InitializeResult => {
    workspaceRoot = params.rootPath;
    return {
        capabilities: {
            // Tell the client that the server works in FULL text document sync mode
            textDocumentSync: documents.syncKind,
        },
    };
});

// Listen on the connection
connection.listen();
```

The server code doesn't ever get hit and I never see the console.log(). I have also completely erased the content in the server file and the error prevails

**Comment by dbaeumer** [comment]
@iDev0urer traditionally the language server uses stdio to communicate between VSCode and the server. If you write to console.log('...') then it is like sending a message. And the header of the message is not correct. This is why you see the exception. There are two options to make this work:

- You still use stdio as the transport and use the connection.console object to log. In you code you would write
```ts
connection.console.log("Apex server initialized");
```
- or you use a different transport than stdio. Since your server is written in node you can use Node's IPC as a transport. Your code would do the following on the client side (note the transport property):
```ts
	let serverOptions = {
		run: { module: serverModule, transport: TransportKind.ipc },
		debug: { module: serverModule, transport: TransportKind.ipc, options: debugOptions}
	};
```
and this on the server side:
```ts
let connection: IConnection = createConnection(new IPCMessageReader(process), new IPCMessageWriter(process));
```

I will adopt the node example to this pattern.
