### ISSUE TITLE
Extensions don't run on save and Intellisense stuck at "Loading"

### ISSUE THREAD

**Issue by hugmanrique** [Microsoft/vscode#48850]
Issue Type: <b>Bug</b>

I can't find a way to reproduce this consistently, but it usually happens randomly when I've been working with the same files for more than 1 hour. Here's the error (happens everytime I save on the TypeScript Output tab once the bug occurs):

```[Error  - 20:37:25] 'occurrences' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at addIndirectUser (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69208:26)
    at handleDirectImports (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69173:37)
    at getImportersForExport (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69126:13)
    at State.importTracker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69103:26)
    at State.getImportSearches (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69967:33)
    at searchForImportsOfExport (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70003:32)
    at getImportOrExportReferences (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70293:21)
    at getReferencesAtLocation (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70231:17)
    at getReferencesInContainer (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70186:21)
    at getReferencesInSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70178:24)
    at searchForImportedSymbol (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70038:21)
    at getImportOrExportReferences (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70289:25)
    at getReferencesAtLocation (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70231:17)
    at getReferencesInContainer (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70186:21)
    at getReferencedSymbolsForSymbol (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69904:25)
    at Object.getReferencedSymbolsForNode (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69820:24)
    at Object.getReferenceEntriesForNode (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:69660:58)
    at getSemanticDocumentHighlights (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:68595:57)
    at Object.getDocumentHighlights (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:68584:20)
    at getDocumentHighlights (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83133:42)
    at getOccurrencesAtPositionCore (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83136:46)
    at Object.getOccurrencesAtPosition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83122:27)
    at IOSession.Session.getOccurrences (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89656:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89272:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90553:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90544:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90553:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90573:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

This issue seems similar to #43427, but the error is different. If you reload the window the error is gone.

Reproduces without extensions

**Comment by mjbvz** [comment]
Looks like you are on an old VS Code version (1.21.1). Please test this in [VS Code insiders](https://code.visualstudio.com/insiders/)

**Comment by hugmanrique** [comment]
Closing as it's a duplicate of #48478
