### ISSUE TITLE
Broken Windows integration suite: workspace-namespace

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49078]
There are three failing integration tests on Windows.

https://vscode.visualstudio.com/VS%20Code/_build/index?buildId=14&_a=summary

I'm not sure who owns this, so please just forward to the right person, if it isn't you.

They all seem to be coming from this exception: https://github.com/Microsoft/vscode/commit/bca16d831e53c7966d821cc33f72b7b5c3f7b472 cc @jrieken 

```
2018-05-02T19:06:33.4399371Z   1) workspace-namespace openTextDocument, untitled is dirty:
2018-05-02T19:06:33.4399844Z      Error: cannot open untitled:d%3A%5Ca%5C1%5Cs%5Cextensions%5Cvscode-api-tests%5CtestWorkspace%5Cnewfile.txt. Detail: Files above 50MB cannot be synchronized with extensions.
2018-05-02T19:06:33.4400507Z       at file:///D:/a/1/s/out/vs/workbench/api/electron-browser/mainThreadDocuments.js:158:60
2018-05-02T19:06:33.4400944Z       at Object.notifySuccess [as _notify] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1185:59)
2018-05-02T19:06:33.4401384Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-05-02T19:06:33.4401804Z       at _Base.Class.derive._creator._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4402265Z       at _Base.Class.derive._creator._completed (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1051:18)
2018-05-02T19:06:33.4402723Z       at CompletePromise_ctor.CompletePromise_then [as then] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1581:49)
2018-05-02T19:06:33.4403137Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:762:28)
2018-05-02T19:06:33.4403718Z       at _Base.Class.derive._creator._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4404148Z       at _Base.Class.derive._creator._setCompleteValue (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1067:18)
2018-05-02T19:06:33.4404559Z       at Object.notifyError [as _notify] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1224:32)
2018-05-02T19:06:33.4404957Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:916:30)
2018-05-02T19:06:33.4405343Z       at Promise_ctor._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4405881Z       at Promise_ctor._error (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1056:18)
2018-05-02T19:06:33.4406255Z       at file:///D:/a/1/s/out/vs/base/common/async.js:612:135
2018-05-02T19:06:33.4406600Z       at file:///D:/a/1/s/out/vs/base/node/extfs.js:37:32
2018-05-02T19:06:33.4406933Z       at D:\a\1\s\node_modules\graceful-fs\polyfills.js:284:29
2018-05-02T19:06:33.4407281Z       at FSReqWrap.oncomplete (original-fs.js:114:15)
2018-05-02T19:06:33.4407579Z 
2018-05-02T19:06:33.4407890Z   2) workspace-namespace openTextDocument, untitled closes on save:
2018-05-02T19:06:33.4408366Z      Error: cannot open untitled:d%3A%5Ca%5C1%5Cs%5Cextensions%5Cvscode-api-tests%5CtestWorkspace%5Cnewfile.txt. Detail: Files above 50MB cannot be synchronized with extensions.
2018-05-02T19:06:33.4408837Z       at file:///D:/a/1/s/out/vs/workbench/api/electron-browser/mainThreadDocuments.js:158:60
2018-05-02T19:06:33.4409252Z       at Object.notifySuccess [as _notify] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1185:59)
2018-05-02T19:06:33.4409669Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-05-02T19:06:33.4410403Z       at _Base.Class.derive._creator._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4410849Z       at _Base.Class.derive._creator._completed (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1051:18)
2018-05-02T19:06:33.4412345Z       at CompletePromise_ctor.CompletePromise_then [as then] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1581:49)
2018-05-02T19:06:33.4412817Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:762:28)
2018-05-02T19:06:33.4413230Z       at _Base.Class.derive._creator._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4413677Z       at _Base.Class.derive._creator._setCompleteValue (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1067:18)
2018-05-02T19:06:33.4414120Z       at Object.notifyError [as _notify] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1224:32)
2018-05-02T19:06:33.4414700Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:916:30)
2018-05-02T19:06:33.4415090Z       at Promise_ctor._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4415483Z       at Promise_ctor._error (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1056:18)
2018-05-02T19:06:33.4415837Z       at file:///D:/a/1/s/out/vs/base/common/async.js:612:135
2018-05-02T19:06:33.4416182Z       at file:///D:/a/1/s/out/vs/base/node/extfs.js:37:32
2018-05-02T19:06:33.4416517Z       at D:\a\1\s\node_modules\graceful-fs\polyfills.js:284:29
2018-05-02T19:06:33.4416864Z       at FSReqWrap.oncomplete (original-fs.js:114:15)
2018-05-02T19:06:33.4417057Z 
2018-05-02T19:06:33.4417310Z   3) workspace-namespace applyEdit:
2018-05-02T19:06:33.4417756Z      Error: cannot open untitled:d%3A%5Ca%5C1%5Cs%5Cextensions%5Cvscode-api-tests%5CtestWorkspace%5Cnew2.txt. Detail: Files above 50MB cannot be synchronized with extensions.
2018-05-02T19:06:33.4418259Z       at file:///D:/a/1/s/out/vs/workbench/api/electron-browser/mainThreadDocuments.js:158:60
2018-05-02T19:06:33.4418652Z       at Object.notifySuccess [as _notify] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1185:59)
2018-05-02T19:06:33.4419048Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-05-02T19:06:33.4419447Z       at _Base.Class.derive._creator._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4420035Z       at _Base.Class.derive._creator._completed (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1051:18)
2018-05-02T19:06:33.4420650Z       at CompletePromise_ctor.CompletePromise_then [as then] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1581:49)
2018-05-02T19:06:33.4421086Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:762:28)
2018-05-02T19:06:33.4421666Z       at _Base.Class.derive._creator._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4422313Z       at _Base.Class.derive._creator._setCompleteValue (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1067:18)
2018-05-02T19:06:33.4422753Z       at Object.notifyError [as _notify] (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1224:32)
2018-05-02T19:06:33.4423146Z       at Object.enter (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:916:30)
2018-05-02T19:06:33.4423707Z       at Promise_ctor._run (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1083:29)
2018-05-02T19:06:33.4424102Z       at Promise_ctor._error (file:///D:/a/1/s/out/vs/base/common/winjs.base.js:1056:18)
2018-05-02T19:06:33.4424453Z       at file:///D:/a/1/s/out/vs/base/common/async.js:612:135
2018-05-02T19:06:33.4424796Z       at file:///D:/a/1/s/out/vs/base/node/extfs.js:37:32
2018-05-02T19:06:33.4425147Z       at D:\a\1\s\node_modules\graceful-fs\polyfills.js:284:29
2018-05-02T19:06:33.4425475Z       at FSReqWrap.oncomplete (original-fs.js:114:15)
```

**Comment by bpasero** [comment]
+ @alexandrudima

**Comment by joaomoreno** [comment]
I'm sorry guys, but I had to comment out those tests, in order to get a green build.

I noticed also many tests in that file are commented out... does this test suite need a quick refresh?

**Comment by jrieken** [comment]
Problem is that we don't allow relative file-uris anymore and that, internally, in order to get an untitled file with path we need a file-uris. I have changed that in the untitled-editor service (fyi @bpasero) with a flag to indicate that the path of the uri should be trusted.
