### ISSUE TITLE
Smoke test: Flaky 'Go To Definition' test on Windows

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49107]
https://vscode.visualstudio.com/VS%20Code/_build/index?buildId=41&_a=summary

```
2018-05-03T09:18:57.6212198Z   1) Test Editor verifies that 'Go To Definition' works:
2018-05-03T09:18:57.6212638Z      Error: Timeout: get element '.tabs-container div.tab.active[aria-selected="true"][aria-label="index.d.ts, tab"]' after 20 seconds.
2018-05-03T09:18:57.6213026Z       at D:\a\1\s\test\smoke\out\vscode\code.js:139:23
2018-05-03T09:18:57.6213336Z       at Generator.next (<anonymous>)
2018-05-03T09:18:57.6213636Z       at fulfilled (D:\a\1\s\test\smoke\out\vscode\code.js:8:58)
2018-05-03T09:18:57.6213933Z       at <anonymous>
```

[smoketest.log](https://github.com/Microsoft/vscode/files/1970293/smoketest.log)
![test_editor_verifies_that__go_to_definition__works](https://user-images.githubusercontent.com/22350/39569640-1af9214e-4ec6-11e8-9d55-bf54ebe0cd27.png)

**Comment by joaomoreno** [comment]
Another one: https://vscode.visualstudio.com/VS%20Code/_build/index?buildId=98&_a=summary
