### ISSUE TITLE
Smoke test: Flaky search test

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49117]
This search test seldomly fails on Windows. When it does, so does debug, because the code is left in a broken state.

https://vscode.visualstudio.com/VS%20Code/_build/index?buildId=48&_a=summary

```
2018-05-03T11:05:02.9506795Z   1) Test Search replaces first search result with a replace term:
2018-05-03T11:05:02.9507791Z      Error: Timeout: is active element 'div[id="workbench.view.search"] .search-view .search-widget .search-container .monaco-inputbox input' after 20 seconds.
2018-05-03T11:05:02.9508496Z       at D:\a\1\s\test\smoke\out\vscode\code.js:139:23
2018-05-03T11:05:02.9509006Z       at Generator.next (<anonymous>)
2018-05-03T11:05:02.9523580Z       at fulfilled (D:\a\1\s\test\smoke\out\vscode\code.js:8:58)
2018-05-03T11:05:02.9525954Z       at <anonymous>
```

[smoketest.log](https://github.com/Microsoft/vscode/files/1970722/smoketest.log)
![test_search_replaces_first_search_result_with_a_replace_term](https://user-images.githubusercontent.com/22350/39575494-08f1b4e2-4edb-11e8-9b8f-754a502a3c39.png)

**Comment by joaomoreno** [comment]
It appears that focus is stolen away from the search viewlet. I've added more logging for when this happens to find who the focus thief is. Let's wait for the next failing build.

**Comment by joaomoreno** [comment]
Found the thief:

```
2018-05-04T00:32:39.3284288Z Error: Active element not found. Current active element is 'DIV.monaco.tree.monaco.tree.instance.3.focused'
```

**Comment by joaomoreno** [comment]
https://vscode.visualstudio.com/VS%20Code/_build/index?buildId=114&_a=summary

Not fixed.

**Comment by joaomoreno** [comment]
This probably fixed it! https://github.com/Microsoft/vscode/commit/3de695109dfc55591de3753a008b109729ccbec6

**Comment by joaomoreno** [comment]
Finally figured out what was wrong here! In the smoketest we need to click the `X` action in a file search result, to remove it from the view. The `X` only shows up if you hover a file result. So we move the mouse over it and then click the `X`. The problem is that sometimes Chrome isn't fast enough to process the mouse move, enable the `:hover` pseudo class and show the `X`. It also happens that the `X` is always in the DOM, but without the `:hover` pseudo class, it is just `display: none`. So, when Chrome is slow enough not to render the `X`, we go ahead and ask for its `top, left` coordinates in order to click it, which returns `0, 0`. Clicking that origin coordinate shows the Explorer, since that's where the Explorer activity icon lives...

Thanks for the help and patience, @isidorn!

![sherlock](https://media.giphy.com/media/FMZvZ3Cw0pZZe/giphy.gif)
