### ISSUE TITLE
Terminal API: Task terminal won't send data when "reveal" == "never"

### ISSUE THREAD

**Issue by alpaix** [Microsoft/vscode#49377]
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:10.813Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

#### Steps to Reproduce
1. Add a task to a project with `"presentation.reveal": "never"`
```js
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "start",
            "problemMatcher": [
                "$eslint-compact"
            ],
            "presentation": {
                "echo": true,
                "reveal": "never",
                "focus": false,
                "panel": "shared"
            },
            "isBackground": true
        }
    ]
}
```
2. Run the task in a task terminal with a listener attached to `onData`

#### Expected
The listener receives data sent to the terminal.

#### Actual
No data sent.

**Comment by dbaeumer** [comment]
@Tyriar adding you as well. Is there something I need to do to make this work ?

**Comment by Tyriar** [comment]
I cannot reproduce this with the following steps (terminal panel is never opened):

1. Run a watch task
2. Attach a data listener
3. Trigger a watch change

Outputs fine:

```
[Extension Host] onData: c (at /home/daniel/dev/Microsoft/vscode-extension-samples/terminal-sample/out/extension.js:87:25)
console.ts:136 [Extension Host] onData: 11:58:33 - File change detected. Starting incremental compilation...


 (at /home/daniel/dev/Microsoft/vscode-extension-samples/terminal-sample/out/extension.js:87:25)
console.ts:136 [Extension Host] onData: 11:58:33 - Compilation complete. Watching for file changes.


 (at /home/daniel/dev/Microsoft/vscode-extension-samples/terminal-sample/out/extension.js:87:25)
```

Watch task I was using:

```
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": "$tsc-watch",
            "isBackground": true,
            "presentation": {
                "echo": true,
                "reveal": "never",
                "focus": false,
                "panel": "shared"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
