### ISSUE TITLE
Trying to build vscode from source fails on Windows 10

### ISSUE THREAD

**Issue by iDev0urer** [Microsoft/vscode#4938]
- VSCode Version: Master branch
- OS Version: Windows 10

Steps to Reproduce:

1. Follow the Windows steps in https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

When I attempt to build from source I get the following error:

```
[2188:0404/191234:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[16864:0404/191235:INFO:CONSOLE(137)] "Loading "weak" failed", source: file:///C:/Users/FA-0042/Documents/Projects/forks
/vscode/out/vs/loader.js (137)
[16864:0404/191235:INFO:CONSOLE(138)] "Detail: ", source: file:///C:/Users/FA-0042/Documents/Projects/forks/vscode/out/v
s/loader.js (138)
[16864:0404/191235:INFO:CONSOLE(140)] "Error: %1 is not a valid Win32 application.
C:\Users\FA-0042\Documents\Projects\forks\vscode\node_modules\weak\build\Release\weakref.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:140:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (C:\Users\FA-0042\Documents\Projects\forks\vscode\node_modules\weak\node_modules\bindings\bindings.js:76
:44)
    at Object.<anonymous> (C:\Users\FA-0042\Documents\Projects\forks\vscode\node_modules\weak\lib\weak.js:7:35)
    at Module._compile (module.js:434:26)", source: file:///C:/Users/FA-0042/Documents/Projects/forks/vscode/out/vs/load
er.js (140)
[16864:0404/191235:INFO:CONSOLE(142)] "Here are the modules that depend on it:", source: file:///C:/Users/FA-0042/Docume
nts/Projects/forks/vscode/out/vs/loader.js (142)
[16864:0404/191235:INFO:CONSOLE(143)] "vs/workbench/api/node/extHostDocuments", source: file:///C:/Users/FA-0042/Documen
ts/Projects/forks/vscode/out/vs/loader.js (143)
```

**Comment by iDev0urer** [comment]
Fixed it by deleting the directory that I downloaded it to, re-cloning, and following the instructions again for installing. No idea what went wrong
