### ISSUE TITLE
Python ext: flake8 tracebacks

### ISSUE THREAD

**Issue by bocekm** [Microsoft/vscode#49529]
- VSCode Version: 1.2.3
- OS Version: Fedora 28

Steps to Reproduce:

1. Have the following installed:
   - Python extension version 2018.4.0
   - flake8, it exhibits the same behaviour with both pip or Fedora package
     - pip: flake8-3.5.0-py2.py3
     - Fedora: python2-flake8-3.4.1-3.fc28
2. Have the flake8 linting enabled (`"python.linting.flake8Enabled": true,`)
3. Open any Python file and look to the Output window in VS Code (and select Python)
4. See traceback:
```
##########Linting Output - flake8##########
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 392, in _handle_results
    task = get()
  File "/usr/lib/python2.7/site-packages/flake8/exceptions.py", line 66, in __init__
    self.original_exception = kwargs.pop('exception')
KeyError: 'exception'
```

Does this issue occur when all extensions are disabled?: No

**Comment by bocekm** [comment]
Thanks for pointing that out. I have created a new issue in the Python extension repo:
https://github.com/Microsoft/vscode-python/issues/1653
