### ISSUE TITLE
 Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#49553]
Issue Id: <b>9c6d050e-7b4b-a645-ada6-9bc418ffdc26</b><br /><br />*Versions* <br />- 1.23.0<br />-  b8475d1dc68bfee70c3fbe3e7fc39f6e0003803b<br />-  d801331ca874c03372fccc804c089e234e771b2b<br />-  a656d397e424173c86f32703e0c0293bd8084da0<br />*Stack* <br />TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/base/node/extfs.ts#637:3](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/extfs.ts#L637:3)<br />    at out/vs/workbench/workbench.main.js:284:457<br />    at FSWatcher.<anonymous> (out/vs/workbench/workbench.main.js:282:283)<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by Tyriar** [comment]
@ramya-rao-a is there any way to get symbols for this?

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/base/node/extfs.ts#637:3](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/extfs.ts#L637:3)<br />    at out/vs/workbench/workbench.main.js:284:457<br />    at FSWatcher.<anonymous> (out/vs/workbench/workbench.main.js:282:283)<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by Tyriar** [comment]
Failing on this line https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L175

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/base/node/extfs.ts#637:3](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/extfs.ts#L637:3)<br />    at out/vs/workbench/workbench.main.js:284:457<br />    at FSWatcher.<anonymous> (out/vs/workbench/workbench.main.js:282:283)<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/base/node/config.ts#175:15 (onConfigFileChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L175:15 (onConfigFileChange))<br />[/vs/base/node/config.ts#156:24 (onChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L156:24 (onChange))<br />[/vs/base/node/extfs.ts#637:3](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/extfs.ts#L637:3)<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />    at e.onConfigFileChange (out/vs/workbench/workbench.main.js:284:716)<br />[/vs/base/node/config.ts#175:15 (onConfigFileChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L175:15 (onConfigFileChange))<br />[/vs/base/node/config.ts#156:24 (onChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L156:24 (onChange))<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />    at e.onConfigFileChange (out/vs/workbench/workbench.main.js:284:716)<br />[/vs/base/node/config.ts#175:15 (onConfigFileChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L175:15 (onConfigFileChange))<br />[/vs/base/node/config.ts#156:24 (onChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L156:24 (onChange))<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />    at e.onConfigFileChange (out/vs/workbench/workbench.main.js:284:716)<br />[/vs/base/node/config.ts#175:15 (onConfigFileChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L175:15 (onConfigFileChange))<br />[/vs/base/node/config.ts#156:24 (onChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L156:24 (onChange))<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />    at e.onConfigFileChange (out/vs/workbench/workbench.main.js:284:716)<br />[/vs/base/node/config.ts#175:15 (onConfigFileChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L175:15 (onConfigFileChange))<br />[/vs/base/node/config.ts#156:24 (onChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L156:24 (onChange))<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Path must be a string. Received null<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/base/node/config.ts#175:15 (onConfigFileChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L175:15 (onConfigFileChange))<br />[/vs/base/node/config.ts#156:24 (onChange)](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/config.ts#L156:24 (onChange))<br />[/vs/base/node/extfs.ts#637:3](https://github.com/microsoft/vscode/blob/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/base/node/extfs.ts#L637:3)<br />    at emitTwo (events.js:106:13)<br />    at FSWatcher.emit (events.js:194:7)<br />    at FSEvent.__dirname.FSWatcher._handle.onchange (original-fs.js:1392:12)<br />

**Comment by ramya-rao-a** [comment]
Callstacks are now fixed
