### ISSUE TITLE
Error occurs in console log when installing extensions from local vsix file

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode#49814]
- VSCode Version: 1.23.1
- OS Version: Win 10 v1709

Steps to Reproduce:

1. click `Toggle Developer Tool` to open the console monitor.
2. in extension view, try installing one extension from local vsix file.
3. some error messages occur in the console output.

Does this issue occur when all extensions are disabled?: **Yes**

```
  ERR Cannot read property 'manifest' of null: TypeError: Cannot read property 'manifest' of null
    at Object.o [as getGalleryExtensionIdFromLocal] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1273:472)
    at t.get [as id] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3737:825)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3756:378
    at Array.filter (native)
    at e.onDidInstallExtension (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3756:344)
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166:1012)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294:101
    at Object.y [as _progress] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:147:812)
    at n.Class.derive._creator._progress (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:457)
    at Object.y [as _progress] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:147:812)
    at n.Class.derive._oncancel._progress (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:457)
    at Object.y [as _progress] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:147:812)
    at n.Class.derive._oncancel._progress (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:457)
    at e.doRequest.n.TPromise.t.handlers.(anonymous function) (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:290:881)
    at e.onMessage (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:291:600)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:289:1006
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166:992)
    at Socket.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:296:377)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

In v1.23.0, there's no such error message.

**Comment by sandy081** [comment]
@Eskibear Is it possible to provide the vsix file to reproduce this issue?

**Comment by Eskibear** [comment]
You can download it [HERE](https://vscjavaci.cloudapp.net/job/vscode_maven/job/vscode-maven.vsix/184/Azure/), I just grant the READ privilege to username sandy081

**Comment by sandy081** [comment]
@Eskibear Above link is requesting access to my personal or organisation account. Not sure if I can provide it.

**Comment by Eskibear** [comment]
@sandy081  I can share one and email to you

**Comment by sandy081** [comment]
@Eskibear Install works for me. Can you please check in your extensions folder that there are any extensions without manifest?

**Comment by Eskibear** [comment]
@sandy081 I just reproduce the issue using:
* a new machine
* newly installed Win10 Enterprise
* newly installed VSCode with no extension

```
```
Attaching the image:

![image](https://user-images.githubusercontent.com/2351748/40291082-3c381864-5cf5-11e8-933e-e0eb1debd21c.png)

**Comment by Eskibear** [comment]
And I want to clarify that the installation is ok, and it's not a blocking issue. The problem is something must be wrong because there's an error message in the console.

**Comment by sandy081** [comment]
@Eskibear Can you please open your extensions folder and check if the installed extension has file called `package.json` ?

**Comment by Eskibear** [comment]
@sandy081 I just tried, yes there is the file `package.json`.

FYI,
![image](https://user-images.githubusercontent.com/2351748/40352083-91c56ef8-5de0-11e8-9fa9-5bb01ea152fe.png)

**Comment by sandy081** [comment]
Thanks @Eskibear for the details. I could reproduce it and see the error. 

Caused by 552a4aeb7f78613364bcad82c01151abf68e4bee.

Fixed it.

**Comment by isidorn** [comment]
Can not repro with the original steps. Adding verified label.
If I should follow some other steps please let me know.
