### ISSUE TITLE
Crash when opening Code via the command line

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50]
Ubuntu 12.04, vscode 0.10.1

Note that I have file symlinks setup for these config files which could having something to do with this crash:

- `~/.config/Code/User/keybindings.json`
- `~/.config/Code/User/settings.json`

**Repro:**
1. Open terminal
2. `Code &`
3. Open another terminal (at `~`)
4. `Code . &`

**Expected:**
vscode opens successfully

**Actual:**
Crash:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: watch ENOSPC
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1247:11)
    at Object.fs.watch (fs.js:1273:11)
    at e.registerWatchers (/home/local/ANT/daniimms/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:3462)
    at new e (/home/local/ANT/daniimms/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:3207)
    at Object.<anonymous> (/home/local/ANT/daniimms/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:7:4907)
    at e._invokeFactory (/home/local/ANT/daniimms/VSCode-linux-x64/resources/app/out/vs/loader.js:5:13773)
    at e._complete (/home/local/ANT/daniimms/VSCode-linux-x64/resources/app/out/vs/loader.js:5:14012)
    at e.resolveDependency (/home/local/ANT/daniimms/VSCode-linux-x64/resources/app/out/vs/loader.js:5:15066)
    at e._onModuleComplete (/home/local/ANT/daniimms/VSCode-linux-x64/resources/app/out/vs/loader.js:5:21369)
```

**Comment by bpasero** [comment]
@Tyriar try increasing your file system handle limit: https://code.visualstudio.com/Docs/supporting/FAQ#_linux-error-enospc

**Comment by Tyriar** [comment]
I added it, I won't be able to reboot to check right now though. Regardless, shouldn't this fail gracefully instead of throwing a cryptic exception?

**Comment by JC1738** [comment]
I have this same issue with ubuntu 14.04, i increased the file handle limit, still have the problem.

**Comment by Tyriar** [comment]
I'm still hitting it when I try open a second instance after setting the watch limit `fs.inotify.max_user_watches=16384`.

@JC1738 are you using symlinks for your config files? Or is there anything else special about your set up?

**Comment by isomorphisms** [comment]
I got this error too in Ubuntu 12.04.

**Comment by Tyriar** [comment]
@isomorphisms looks like a distinct issue, I created https://github.com/Microsoft/vscode/issues/3700
