### ISSUE TITLE
Error: Can't run recursive splices.

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#50083]
- VSCode Version: 1.23.1
- OS Version: Window10

Steps to Reproduce:

1. disable all extension
2. start debug my extension
3. In the extension window, show the warn message ``扩展未在 10 秒内启动，可能在第一行已停止，需要调试器才能继续。``
4. In the main window dev tool. I can found the error stack

Does this issue occur when all extensions are disabled?: Yes

### Main Window stack

```
  ERR Can't run recursive splices.: Error: Can't run recursive splices.
    at e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:388:199)
    at e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:398:655)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:417:361
    at e.bufferEvents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:169:659)
    at r.e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:417:317)
    at t.onBreakpointsChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4230:348)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4226:201
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166:992)
    at e.removeFunctionBreakpoints (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2370:203)
    at t.removeFunctionBreakpoints (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4295:69)
    at u (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4236:578)
    at HTMLInputElement.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4236:914)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:219:693
    at e.releaseRow (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:219:719)
    at e.release (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:219:551)
    at e.removeItemFromDOM (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:392:128)
    at e._splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:388:520)
    at e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:388:274)
    at e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:398:655)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:417:361
    at e.bufferEvents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:169:659)
    at r.e.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:417:317)
    at t.onBreakpointsChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4230:348)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4226:201
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166:992)
    at e.setExceptionBreakpoints (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2367:120)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4301:525
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:146:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:337)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2437:107
    at t.e.acceptMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2384:797)
    at t.handleData (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2385:660)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2385:156)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### Extension Window dev-tool log

![1](https://user-images.githubusercontent.com/9758711/40219640-d4de661c-5aa8-11e8-96b8-13bcd16823b8.PNG)

**Comment by isidorn** [comment]
@axetroy sorry for the slow response I was on vacation
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If you can can you please F1 > developer tools > check "Pause caucht exception" icon
Once exception happens take a screenshot and paste it here so we know where is the exact cause. Thanks a lot
