### ISSUE TITLE
(/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:605:445)

### ISSUE THREAD

**Issue by GACLove** [Microsoft/vscode#50094]
Issue Type: <b>Bug</b>

	at Object.t.toPosition (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:605:445)
	at e.provideHover (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:651:488)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:665:567
	at e._withAdapter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:662:852)
	at e.$provideHover (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:665:529)
	at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:599:737)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:599:455)
	at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:529)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:298)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:597:226
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:600:324
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:88:119
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:496)
	at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.4.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3741)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.72GB (0.49GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
vscode-language-pack-zh-hans|MS-|1.23.5
githistory|don|0.4.1
gitlens|eam|8.3.0
CppSnippets|har|0.0.13
vscode-cudacpp|kri|0.1.1
cppcheck|mat|0.2.2
rainbow-csv|mec|0.2.1
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.4.0
cpptools|ms-|0.17.1
Go|ms-|0.6.80
vscode-gitignore-generator|pio|1.0.1
vscode-yaml|red|0.0.12
vscode-icons|rob|7.23.0
cmake|twx|0.0.17
cmake-tools|vec|0.11.1
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.3.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Fixed by 9f6053242ff246857ee29514befc141dc111534b I believe
