### ISSUE TITLE
Terminal's "Switch to Dom renderer" notification "no" button has no effect

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#50124]
Issue Type: <b>Bug</b>

1. Trigger the `switch to dom renderer` alert for the terminal (not sure why I saw this in the first place)
2. Try clicking on the no button

**Bug** 
No effect. Here's the error:

```
 ERR e.run is not a function: TypeError: e.run is not a function
    at e._actionCallback (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3119:257)
    at e.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185:901)
    at t.e.runAction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:186:585)
    at t.runAction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2271:774)
    at t.e.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:186:395)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2281:181
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:169:917)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:355:523
    at HTMLAnchorElement.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:343:984)
```

VS Code version: Code - Insiders 1.24.0-insider (912fff91ac4ff1bff9695e8da69abd729f7ae956, 2018-05-18T05:11:58.249Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_5690733|
|Screen Reader|no|
|VM|18%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-docker|Pet|0.0.26
color-info|bie|0.5.0
emojisense|bie|0.4.0
lit-html|bie|1.2.0
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-image-size|bie|0.0.2
speech|bie|0.0.1
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.4.9
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
mdmath|goe|2.2.1
vscode-styled-components|jpo|0.0.18
vscode-memfs|jri|0.0.3
theme-karyfoundation-themes|kar|18.0.1
hg|mrc|1.2.3
vscode-azurefunctions|ms-|0.9.0
vscode-cosmosdb|ms-|0.7.1
mssql|ms-|1.3.1
python|ms-|2018.4.0
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
typescript-javascript-grammar|ms-|0.0.41
debugger-for-chrome|msj|4.4.3
angular2-inline|nat|0.0.17

(15 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I think there must be something going wrong with the condition I'm checking as @jtsom also saw the message but probably shouldn't have https://github.com/Microsoft/vscode/issues/50130

Also "No" is meant to dismiss the notification only. In the overflow there is a don't show again option

**Comment by jtsom** [comment]
FYI.. I when I saw the notification, I too tried to click the No button (since I wasn't seeing any problems), but clicking did nothing.
