### ISSUE TITLE
Debugging node js 10.1.0 in vscode has issues

### ISSUE THREAD

**Issue by prabhurangan** [Microsoft/vscode#50188]
- VSCode Version: 1.23.1
- OS Version: OS x EL Capitan (10.11.6)

Steps to Reproduce:

1. By default i have node js 10.1.0 installed to my system
2. now load my node js app in vscode
3. click on start debug application
`Error: Cannot find module '/Users/prpandurangan/Documents/payments/ebaypayonboardingweb/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.11/node-v64-darwin-x64/profiler.node'
loader.js:571
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Function._load (/Users/prpandurangan/Documents/payments/ebaypayonboardingweb/node_modules/brogan-ebay/index.js:30:53)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/prpandurangan/Documents/payments/ebaypayonboardingweb/node_modules/@risingstack/v8-profiler/v8-profiler.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
`

Does this issue occur when all extensions are disabled?: Yes

**Comment by SACdeTERRE** [comment]
same here

**Comment by roblourens** [comment]
I don't see any issues. It looks like you're trying to load a native node module possibly built for the wrong version, though. If you still have issues, please share your project or a code sample that doesn't work.
