### ISSUE TITLE
TypeScript seems broken

### ISSUE THREAD

**Issue by massimonewsuk** [Microsoft/vscode#50405]
Issue Type: <b>Bug</b>

Stack trace from TypeScript output tab
```
[Info  - 15:58:17] Using tsserver from: c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 15:58:17] Forking TSServer
PATH: C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GitExtensions\;C:\Program Files (x86)\get_iplayer;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\PowerShell\6.0.1\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Users\Test\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Test\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\Test\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExtensions\;C:\Program Files (x86)\get_iplayer;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\Test\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\PostgreSQL\9.3\bin;C:\Users\Test\AppData\Local\Yarn\bin;C:\Users\Test\AppData\Roaming\npm
[Info  - 15:58:18] Started TSServer
[Error  - 16:14:29] 'getCodeFixes' request failed with error.
Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.isJsxOpeningLikeElement (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:12823:24)
    at getActionsForNonUMDImport (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:84263:33)
    at Object.getImportCodeActions [as getCodeActions] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:84216:19)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83107:121
    at Object.flatMap (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1802:25)
    at Object.getFixes (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83107:23)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90303:35
    at Object.flatMap (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1802:25)
    at Object.getCodeFixesAtPosition (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90301:23)
    at IOSession.Session.getCodeFixes (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:96959:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:95788:61)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97132:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97123:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97132:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97152:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98357:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

VS Code version: Code - Insiders 1.24.0-insider (8bf066e3dca775522bdebde4f742e71498b09bca, 2018-05-24T05:17:13.260Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.77GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.10
githistory|don|0.4.1
xml|Dot|1.9.2
EditorConfig|Edi|0.12.2
prettier-vscode|esb|1.3.1
graphql-for-vscode|kum|1.11.0
PowerShell|ms-|1.7.0
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.0.27
vscode-icons|rob|7.23.0
quokka-vscode|Wal|1.0.125
wallaby-vscode|Wal|1.0.84

</details>

![error](https://user-images.githubusercontent.com/35228622/40495613-8c1ce63a-5f6f-11e8-9808-d0c860cb80f5.PNG)

**Comment by massimonewsuk** [comment]
Sorry just realised it was a duplicate of https://github.com/Microsoft/vscode/issues/50395
