### ISSUE TITLE
Joining lines can break the editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#50471]
Also reproes in 1.23.1

- Have a file with contents:
```
let a = {

}
```
- Cursor at column 0 on the line between the {}
- Press ctrl+j to join lines
- Press ctrl+j again (current line highlight disappears)
- Press backspace, nothing happens 🐛 
- Left/right arrows, nothing happens
- Up arrow works

Error:

```
ERR Cannot read property 'node' of null: TypeError: Cannot read property 'node' of null
log.ts:171
    at PieceTreeBase.getValueInRange2 (file:///Users/roblou/code/vscode/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.js:382:30)
    at PieceTreeBase.getValueInRange (file:///Users/roblou/code/vscode/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.js:367:30)
    at PieceTreeTextBuffer.getValueInRange (file:///Users/roblou/code/vscode/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.js:61:36)
    at TextModel.getValueInRange (file:///Users/roblou/code/vscode/out/vs/editor/common/model/textModel.js:559:33)
    at Function.MultiCursorSession.create (file:///Users/roblou/code/vscode/out/vs/editor/contrib/multicursor/multicursor.js:176:48)
    at Function.SelectionHighlighter._createState (file:///Users/roblou/code/vscode/out/vs/editor/contrib/multicursor/multicursor.js:660:40)
    at SelectionHighlighter._update (file:///Users/roblou/code/vscode/out/vs/editor/contrib/multicursor/multicursor.js:626:49)
    at file:///Users/roblou/code/vscode/out/vs/editor/contrib/multicursor/multicursor.js:611:27
    at Emitter.fire (file:///Users/roblou/code/vscode/out/vs/base/common/event.js:103:38)
    at file:///Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:962:55
    at Emitter.fire (file:///Users/roblou/code/vscode/out/vs/base/common/event.js:103:38)
    at Cursor._emitStateChangedIfNecessary (file:///Users/roblou/code/vscode/out/vs/editor/common/controller/cursor.js:311:35)
    at Cursor.setStates (file:///Users/roblou/code/vscode/out/vs/editor/common/controller/cursor.js:151:18)
    at Cursor.setSelections (file:///Users/roblou/code/vscode/out/vs/editor/common/controller/cursor.js:255:18)
    at CodeEditorWidget.executeEdits (file:///Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:661:29)
    at JoinLinesAction.run (file:///Users/roblou/code/vscode/out/vs/editor/contrib/linesOperations/linesOperations.js:624:20)
    at JoinLinesAction.EditorAction.runEditorCommand (file:///Users/roblou/code/vscode/out/vs/editor/browser/editorExtensions.js:144:25)
    at file:///Users/roblou/code/vscode/out/vs/editor/browser/editorExtensions.js:113:30
    at InstantiationService.invokeFunction (file:///Users/roblou/code/vscode/out/vs/platform/instantiation/common/instantiationService.js:48:34)
    at CodeEditorWidget.invokeWithinContext (file:///Users/roblou/code/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:175:47)
    at JoinLinesAction.EditorCommand.runCommand (file:///Users/roblou/code/vscode/out/vs/editor/browser/editorExtensions.js:107:27)
    at handler (file:///Users/roblou/code/vscode/out/vs/editor/browser/editorExtensions.js:48:67)
    at InstantiationService.invokeFunction (file:///Users/roblou/code/vscode/out/vs/platform/instantiation/common/instantiationService.js:48:34)
    at CommandService._tryExecuteCommand (file:///Users/roblou/code/vscode/out/vs/workbench/services/commands/common/commandService.js:70:72)
    at file:///Users/roblou/code/vscode/out/vs/workbench/services/commands/common/commandService.js:60:65
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/roblou/code/vscode/out/vs/base/common/winjs.base.js:1581:49)
    at CommandService.executeCommand (file:///Users/roblou/code/vscode/out/vs/workbench/services/commands/common/commandService.js:60:32)
    at WorkbenchKeybindingService.AbstractKeybindingService._dispatch (file:///Users/roblou/code/vscode/out/vs/platform/keybinding/common/abstractKeybindingService.js:143:38)
    at file:///Users/roblou/code/vscode/out/vs/workbench/services/keybinding/electron-browser/keybindingService.js:239:50
  ERR Illegal argument: character must be non-negative: Error: Illegal argument: character must be non-negative
log.ts:171
	at Object.illegalArgument (/Users/roblou/code/vscode/out/vs/base/common/errors.js:152:20)
	at new Position (/Users/roblou/code/vscode/out/vs/workbench/api/node/extHostTypes.js:54:32)
	at to (/Users/roblou/code/vscode/out/vs/workbench/api/node/extHostTypeConverters.js:20:25)
	at Array.map (native)
	at ExtHostEditors.$acceptEditorPropertiesChanged (/Users/roblou/code/vscode/out/vs/workbench/api/node/extHostTextEditors.js:96:61)
	at RPCProtocol._doInvokeHandler (/Users/roblou/code/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:215:27)
...
```

![may-25-2018 10-18-21](https://user-images.githubusercontent.com/323878/40557436-05e387ea-6005-11e8-8563-5efbf481cd00.gif)

**Comment by rebornix** [comment]
@roblourens really good catch! A minimal reproduce steps

```
let a = {
}
```

Put cursor at line 2, column 1, then press Ctrl+J.

**Comment by rebornix** [comment]
Root cause, we tried to validate position when making edits by checking `typeof lineNumber === 'number'`, however the `lineNumber` we passed in is `NaN` and `typeof NaN` is 'number', tada.
