### ISSUE TITLE
Smoketest: Search tests are broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#50857]
They always fail, even locally.

```
 Test
    Search
** Timeout!
Did not pass accept function
      1) searches for body & checks for correct result number
      ✓ searches only for *.js files & checks for correct result number
** Timeout!
Did not pass accept function
      2) dismisses result & checks for correct result number


  1 passing (50s)  2 failing

  1) Test Search searches for body & checks for correct result number:
     Error: Timeout: get text content 'div[id="workbench.view.search"] .search-view .messages[aria-hidden="false"] .message>p' after 20 seconds.
      at out/vscode/code.js:139:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
      at <anonymous>
  2) Test Search dismisses result & checks for correct result number:
     Error: Timeout: get text content 'div[id="workbench.view.search"] .search-view .messages[aria-hidden="false"] .message>p' after 20 seconds.
      at out/vscode/code.js:139:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
      at <anonymous>
```

**Comment by joaomoreno** [comment]
My bad, they broken when I introduced `package-lock.json` to the smoketest repo.

**Comment by bpasero** [comment]
Verified they are broken 💯
