### ISSUE TITLE
Clearing search text from the Extension search box results in `Cannot read property 'reasonId' of undefined`

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#50884]
Issue Type: <b>Bug</b>

1. Open the Extensions view
1. Type some text and then clear (delete) the text
1. :bug: A notification pops up saying `Cannot read property 'reasonId' of undefined`
```
notificationsAlerts.ts:40 TypeError: Cannot read property 'reasonId' of undefined
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4962:452
    at Array.map (native)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4962:399
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at l (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:157:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:158:45)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at l (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:157:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:158:45)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:153:592)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:413)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:196:912
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:286:300
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (original-fs.js:114:15)
```

VS Code version: Code - Insiders 1.24.0-insider (08537497eecd3172390194693d3d7c0ec8f52b70, 2018-05-31T05:17:57.180Z)
OS version: Windows_NT x64 10.0.17677

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (13.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
None of those are duplicates

**Comment by ramya-rao-a** [comment]
Thanks for reporting!
This is fixed with https://github.com/Microsoft/vscode/commit/015ec8303cb2f0caf24709bb79fd24444c6361d6
