### ISSUE TITLE
Smoketest: TypeScript definition location broke

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#50944]
As reported by @roblourens, the smoketests have been failing consistently over the past 1/2 days here:

```
2018-06-01T09:52:00.7191680Z   1) Test Editor verifies that 'Go To Definition' works:
2018-06-01T09:52:00.7212410Z      Error: Timeout: get element '.tabs-container div.tab.active[aria-selected="true"][aria-label="index.d.ts, tab"]' after 20 seconds.
2018-06-01T09:52:00.7230570Z       at out/vscode/code.js:139:23
2018-06-01T09:52:00.7246630Z       at Generator.next (<anonymous>)
2018-06-01T09:52:00.7261910Z       at fulfilled (out/vscode/code.js:8:58)
2018-06-01T09:52:00.7277260Z       at <anonymous>
2018-06-01T09:52:00.7284880Z 
2018-06-01T09:52:00.7301760Z   2) Test Editor verifies that 'Peek Definition' works:
2018-06-01T09:52:00.7326260Z      Error: Timeout: get text content '.monaco-editor .zone-widget .zone-widget-container.peekview-widget.reference-zone-widget.results-loaded .head .peekview-title .filename' after 20 seconds.
2018-06-01T09:52:00.7344360Z       at out/vscode/code.js:139:23
2018-06-01T09:52:00.7360160Z       at Generator.next (<anonymous>)
2018-06-01T09:52:00.7375460Z       at fulfilled (out/vscode/code.js:8:58)
2018-06-01T09:52:00.7390640Z       at <anonymous>
```

Both tests test the definition of `express`. This seems to have changed from `index.d.ts` to the actual JavaScript file where `express` is defined... for some reason. @mjbvz Maybe something has changed recently in TS?

This happens to be exactly the same issue as https://github.com/Microsoft/vscode/issues/49107... expect it reproduces much more reliably right now.

**Comment by joaomoreno** [comment]
In order to fix this, I will simply change the definition target and use something within the same file.
