### ISSUE TITLE
Extension Host - Error: Channel has been closed

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/vscode#50955]
## Summary
I am an author of Windows VS Code extension - [IIS Express for VS Code ](https://github.com/warrenbuckley/IIS-Express-Code/issues/39) and I have recently come across this 'Channel has been closed` detailed in the Extension Host Log output, as shown below.

## Machine Info
- Version 1.23.1
- Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
- Date 2018-05-10T17:11:17.614Z
- Shell 1.7.12
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

Steps to Reproduce:

1. First run of extension works fine (Uses node to spawn process of IISExpress exe)
2. Close/stop the site & kill the process
3. Restart the site - the IIS Express .exe process never fires back up & the error below is thrown

## Extension Host Error Log
```
[2018-06-01 17:31:59.926] [exthost1] [error] Error: Channel has been closed
    at e.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:591)
    at e.show (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:379)
    at IIS.startWebsite (C:\Users\warre\.vscode\extensions\warren-buckley.iis-express-1.1.0\out\src\IISExpress.js:37:22)
    at IIS.restartSite (C:\Users\warre\.vscode\extensions\warren-buckley.iis-express-1.1.0\out\src\IISExpress.js:154:18)
    at C:\Users\warre\.vscode\extensions\warren-buckley.iis-express-1.1.0\out\src\extension.js:60:17
    at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:704)
    at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:141)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20) extension.iis-express.restart
```
## Other extensions - experiencing the same
It seems with a quick google there seems to be some other users of other extensions experiencing similar issues with this `Channel has been closed` problem, very recently too.

* https://github.com/Microsoft/vscode-jshint/issues/60
* https://github.com/JakeBecker/vscode-elixir-ls/issues/73
* https://github.com/redhat-developer/vscode-java/issues/533

### Full Extension Host Log
```
[2018-06-01 17:31:36.151] [exthost1] [info] extension host started
[2018-06-01 17:31:36.190] [exthost1] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-06-01 17:31:36.190] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\out\extension
[2018-06-01 17:31:36.284] [exthost1] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-06-01 17:31:36.284] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\out\main
[2018-06-01 17:31:36.546] [exthost1] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-06-01 17:31:36.546] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\out\extension
[2018-06-01 17:31:36.566] [exthost1] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
[2018-06-01 17:31:36.566] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\warre\.vscode\extensions\dbaeumer.vscode-eslint-1.4.10\client\out\extension
[2018-06-01 17:31:36.653] [exthost1] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"activationEvent":"*"}
[2018-06-01 17:31:36.653] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\warre\.vscode\extensions\eamodio.gitlens-8.3.3\out\extension
[2018-06-01 17:31:36.975] [exthost1] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare {"startup":true,"activationEvent":"*"}
[2018-06-01 17:31:36.975] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\warre\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.246\out\src\extension
[2018-06-01 17:31:38.113] [exthost1] [info] ExtensionService#_doActivateExtension vscode.html-language-features {"startup":false,"activationEvent":"onLanguage:html"}
[2018-06-01 17:31:38.113] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\client\out\htmlMain
[2018-06-01 17:31:39.222] [exthost1] [info] eager extensions activated
[2018-06-01 17:31:43.495] [exthost1] [info] ExtensionService#_doActivateExtension warren-buckley.iis-express {"startup":false,"activationEvent":"onCommand:extension.iis-express.start"}
[2018-06-01 17:31:43.495] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\warre\.vscode\extensions\warren-buckley.iis-express-1.1.0\out\src\extension
[2018-06-01 17:31:59.926] [exthost1] [error] Error: Channel has been closed
    at e.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:591)
    at e.show (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:379)
    at IIS.startWebsite (C:\Users\warre\.vscode\extensions\warren-buckley.iis-express-1.1.0\out\src\IISExpress.js:37:22)
    at IIS.restartSite (C:\Users\warre\.vscode\extensions\warren-buckley.iis-express-1.1.0\out\src\IISExpress.js:154:18)
    at C:\Users\warre\.vscode\extensions\warren-buckley.iis-express-1.1.0\out\src\extension.js:60:17
    at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:704)
    at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:141)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20) extension.iis-express.restart
```

**Comment by isidorn** [comment]
Seems to be coming from https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostOutputService.ts#L68

Forwarding @sandy081

**Comment by sandy081** [comment]
Assigned to June for investigation

**Comment by sandy081** [comment]
@warrenbuckley Looks like you are trying to use the channel which is disposed. Can you please check your code path that you disposed your channel before you are using  it again?
