### ISSUE TITLE
Please support to solve "TypeError" problem when using debug

### ISSUE THREAD

**Issue by mct1209** [Microsoft/vscode#51040]
Issue Type: <b>Bug</b>

Dear Sirs, please support to solve "TypeError" when debug of Visual Studio Code.
I'm working with:
- Visual studio code version: 1.23.1
- Go: 0.6.80
- Windows 10 
The follows are error message, many thanks...:
"TypeError: Cannot read property 'currentGoroutine' of null
    at GoDebugSession.evaluateRequest (C:\Users\mengche\.vscode\extensions\ms-vscode.go-0.6.80\out\src\debugAdapter\goDebug.js:717:45)
    at GoDebugSession.dispatchRequest (C:\Users\mengche\.vscode\extensions\ms-vscode.go-0.6.80\node_modules\vscode-debugadapter\lib\debugSession.js:416:22)
    at GoDebugSession._handleData (C:\Users\mengche\.vscode\extensions\ms-vscode.go-0.6.80\node_modules\vscode-debugadapter\lib\protocol.js:97:38)
    at Socket.inStream.on (C:\Users\mengche\.vscode\extensions\ms-vscode.go-0.6.80\node_modules\vscode-debugadapter\lib\protocol.js:18:44)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)"

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-language-pack-zh-hant|MS-|1.23.3
cpptools|ms-|0.17.4
Go|ms-|0.6.80

</details>

**Comment by octref** [comment]
@ramya-rao-a Seems to be a Go extension specific issue.

**Comment by octref** [comment]
@mct1209 Actually, can you open the issue at https://github.com/Microsoft/vscode-go? They'll be able to help you out.
