### ISSUE TITLE
Insiders build crashes immediately on launch

### ISSUE THREAD

**Issue by SeanLatimer** [Microsoft/vscode#51048]
- VSCode Version:
- OS Version: MacOS High Sierra

When running in terminal with verbose mode, it gives this error: 
```
[main 16:42:52] Could not delete obsolete instance handle { Error: ENOENT: no such file or directory, unlink '/Volumes/MacData/MovedUsers/seanlatimer/Library/Application Support/Code - Insiders/1.24.0-insider-main.sock'
    at Object.fs.unlinkSync (original-fs.js:1091:18)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:495:334
    at Object.g [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:83:170)
    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:418)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:719)
    at n.Class.derive._oncancel._error (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:236)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/Volumes/MacData/MovedUsers/seanlatimer/Library/Application Support/Code - Insiders/1.24.0-insider-main.sock' }
[main 16:42:52] Error: ENOENT: no such file or directory, unlink '/Volumes/MacData/MovedUsers/seanlatimer/Library/Application Support/Code - Insiders/1.24.0-insider-main.sock'
    at Object.fs.unlinkSync (original-fs.js:1091:18)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:495:334
    at Object.g [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:83:170)
    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:418)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:719)
    at n.Class.derive._oncancel._error (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:236)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[main 16:42:52] Lifecycle#kill()
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@SeanLatimer Does this reproduce after a system restart?

**Comment by SeanLatimer** [comment]
Removing these 2 folders
```
~/Library/Application Support/Code - Insiders
~/.vscode-insiders
```

Basically making it a fresh install, it will launch once.
Any subsequent attempts to launch then gives this error, reboots etc don't cause any change.

**Comment by joaomoreno** [comment]
Interesting. Does a `/Volumes/MacData/MovedUsers/seanlatimer/Library/Application Support/Code - Insiders/1.24.0-insider-main.sock` file exist? Is that a special file system, in any way?

**Comment by SeanLatimer** [comment]
The file does not exist, no.

Other than my user directory being on another HDD, there's nothing special about it.

**Comment by joaomoreno** [comment]
This might be #20567.

What is the full contents of `/Volumes/MacData/MovedUsers/seanlatimer/Library/Application Support/Code - Insiders`?

Can you try choosing a shorter path for your user data dir? Use `code --user-data-dir PATH` to try this out. Does it work there?>

**Comment by SeanLatimer** [comment]
`tree` output of the directory: https://hastebin.com/xadawilice.txt

It appears to be an issue with long paths.

In the default directory, I was getting these:
```
1.24.0-insider-main 
1.24.0-insider-shar 
```

I manually renamed them to:
```
1.24.0-insider-main.sock 
1.24.0-insider-share.sock
```

After that, it starts up with no issues. Until a fix is available, this is a workaround for the issue. Although it would need to be repeated every time a new version is released.

**Comment by joaomoreno** [comment]
YES! That is exactly #20567.

Interesting that renaming them works for you. Can you now try to delete them and start Code... does it start OK?

Unfortunately, having your home directory be `/Volumes/MacData/MovedUsers/seanlatimer` will hit this all the time. I suggest to use a different user-data-dir with `--user-data-dir`. Or maybe move your home folder to a shorter path...?

**Comment by SeanLatimer** [comment]
After deleting them, Code creates them with the truncated names and it's back to crashing.

It's not a huge issue, now that I know it can be fixed on my end. 

I'll close this since a remedy has been found, appreciate the help!

**Comment by andremacola** [comment]
I have a similar, my VScode Insiders is creating 1.24.0-insider-shared.soc instead of 1.24.0-insider-shared.sock and I need to rename every time even with a full reinstall. OSX High Sierra
