### ISSUE TITLE
keyboard shortcuts editor opens up empty

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#51109]
Issue Type: <b>Bug</b>

Open the keyboard shortcut editor from the Preferences menu. 

Result: It is empty

![image](https://user-images.githubusercontent.com/1487073/40944827-10e88c2c-680b-11e8-9e7c-b9a06d555773.png)

Errors in Console:

```
  ERR Cannot read property 'ignoreCase' of null: TypeError: Cannot read property 'ignoreCase' of null
    at e.serialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1261:972)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1262:908
    at Array.map (native)
    at e.serialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1262:883)
    at Function.i.toKeybindingEntry (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3238:165)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3236:974
    at n.Class.derive._oncancel.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:366)
    at i.resolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3236:722)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3870:311
    at n.Class.define.cancel.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:366)
    at t.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3870:160)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3862:744
    at n.Class.define.cancel.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:366)
    at t.setInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3862:712)
    at t.doSetInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4600:604)
    at t.doOpenEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4599:84)
    at t.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4598:221)
    at e.doOpenEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3519:186)
    at e.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3518:625)
    at t.openGlobalKeybindingSettings (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4153:382)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4880:32)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2212:537
    at <anonymous>
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:166 WARNING: Promise with no error callback:181
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:166 Object
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:166 TypeError: Cannot read property 'ignoreCase' of null
    at e.serialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1261:972)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1262:908
    at Array.map (native)
    at e.serialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1262:883)
    at Function.i.toKeybindingEntry (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3238:165)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3236:974
    at n.Class.derive._oncancel.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:366)
    at i.resolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3236:722)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3870:311
    at n.Class.define.cancel.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:366)
    at t.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3870:160)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3862:744
    at n.Class.define.cancel.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:366)
    at t.setInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3862:712)
    at t.doSetInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4600:604)
    at t.doOpenEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4599:84)
    at t.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4598:221)
    at e.doOpenEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3519:186)
    at e.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3518:625)
    at t.openGlobalKeybindingSettings (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4153:382)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4880:32)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2212:537
    at <anonymous>
```

If I click on the `Sort by Precedence` button in the upper right corner, the shortcuts appear.

![image](https://user-images.githubusercontent.com/1487073/40944885-4151209a-680b-11e8-8dfe-8c48634bfdf3.png)

My keybindings.json looks like this:

```json
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "cmd+r",
        "command": "workbench.action.openRecent"
    },
    {
        "key": "shift+cmd+'",
        "when": "editorTextFocus && resourceLangId == 'azcli'",
        "command": "ms-azurecli.runLineInEditor"
    },
    {
        "key": "cmd+r",
        "command": "workbench.action.quickOpenNavigateNext",
        "when": "inQuickOpen"
    },
    {
        "key": "f6",
        "command": "workbench.action.reloadWindow",
        "when": "!inDebugMode"
    },
    {
        "key": "cmd+n cmd+i",
        "command": "workbench.action.tasks.runTask",
        "args": "npm install",
        "when": "resourceFilename =~ **/package.json && aaa =~ **/*"
    },
    {
        "key": "f7",
        "command": "workbench.action.terminal.runSelectedText",
        "when": "editorTextFocus && resourceLangId == 'shellscript'"
    }


]
```

VS Code version: Code - Insiders 1.24.0-insider (f67e6397855fb25becbdf33df185f96da7fdd108, 2018-06-04T20:51:23.413Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.41GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chrisdias** [comment]
looks like this causes it:

``` json
        "when": "resourceFilename =~ **/package.json && aaa =~ **/*"
```

**Comment by chrisdias** [comment]
although having this still causes it to not open:

``` json
        "when": "resourceFilename =~ **/package.json"
```

@jrieken `=~` should be the indicator to match on glob pattern, correct?

**Comment by jrieken** [comment]
@chrisdias The regex needs to be enclosed by slashes, e.g `"when": "resourceFilename =~ /**/package.json/"`

**Comment by jrieken** [comment]
Also, note that this is regular expressions, not glob-patterns, and that `**/package.json` isn't correct, use something like `"when": "resourceFilename =~ /.*\\.package.json/"` instead.

**Comment by jrieken** [comment]
I have pushed a change to prevent the errors. The rest (see above) is the designed behaviour.
