### ISSUE TITLE
Smoke Test: Flaky Debug test

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#51138]
I don't think I've seen this one before:

https://vscode.visualstudio.com/VSCode/_build/index?buildId=1424&_a=summary&tab=summary

```
2018-06-05T10:05:40.9381880Z   1) Test Debug continue:
2018-06-05T10:05:40.9382371Z      Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-tree-row .stack-frame' after 20 seconds.
2018-06-05T10:05:40.9382671Z       at D:\a\1\s\test\smoke\out\vscode\code.js:139:23
2018-06-05T10:05:40.9382865Z       at Generator.next (<anonymous>)
2018-06-05T10:05:40.9383087Z       at fulfilled (D:\a\1\s\test\smoke\out\vscode\code.js:8:58)
2018-06-05T10:05:40.9383452Z       at <anonymous>
```

```
2018-06-05T10:04:38.4370166Z ** Timeout!
2018-06-05T10:04:38.4543306Z Error: Active element not found. Current active element is 'DIV.monaco.tree.monaco.tree.instance.4.focused'
```

![test_debug_continue](https://user-images.githubusercontent.com/22350/40970615-6bacf9da-68bb-11e8-951b-bbcc9e59f162.png)

**Comment by joaomoreno** [comment]
I've pushed https://github.com/Microsoft/vscode/commit/c221484da0b9b03bf1cd8a3993598d32e514c9ac which should provide a bit more information on who is stealing focus.
