### ISSUE TITLE
Unable to load TS language service plugin - RangeError

### ISSUE THREAD

**Issue by divyenduz** [Microsoft/vscode#51158]
Trying to get a custom TS language service plugin up and running. 

Related issue: https://github.com/Microsoft/vscode/issues/34276
But I need to use the workspace version of typescript. 

- VSCode Version: 1.23.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Run `git clone git@github.com:divyenduz/ts-vscode-graphql-plugin.git` - [repo](https://github.com/divyenduz/ts-vscode-graphql-plugin)
1. Run `cd ts-vscode-graphql-plugin`, `npm install`, `npm link`, `npm run build`, `cd ..`
1. Run `git clone git@github.com:divyenduz/ts-base.git` - [repo](https://github.com/divyenduz/ts-base)
1. Run `cd ts-base`, `npm install`, `npm link ts-vscode-graphql-plugin`, `npm run build`
1. Run `code .`, go to `src/index.ts`,and use the typescript workspace version from `ts-base` as [suggested here](https://github.com/RyanCavanaugh/sample-ts-plugin/issues/4#issuecomment-356405843)

The output logs for "TypeScript" yields the following error:-

```
RangeError: out of range index
    at ProtocolBuffer.tryReadContent (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/out/utils/wireProtocol.js:74:21)
    at Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/out/utils/wireProtocol.js:100:41)
    at Socket.Reader.readable.on (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/out/utils/wireProtocol.js:87:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

Notice that this error does not occur if I misspell the name of the plugin in `tsconfig.json`. 

Does this issue occur when all extensions are disabled?: NA

**Comment by divyenduz** [comment]
I already also tried the "relative path" way to load the plugin as [documented here](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#testing-locally) but nothing happens and the plugin is not loaded.

**Comment by divyenduz** [comment]
P.S. I am also able to replicate this on the insiders version of VSCode: `1.24.0-insider`

**Comment by divyenduz** [comment]
Here is my `tsserver.log` which states that the extension loaded properly:-
https://pastebin.com/vEf21re8

**Comment by mjbvz** [comment]
This is because you are writing to stdout (`console.log`). This is how the tsserver talks to vscode. 

Instead, use the TS server logging methods for logging
