### ISSUE TITLE
Illegal argument: globalActivityId: Error: Illegal

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#51181]
Issue Type: <b>Bug</b>

In the latest master, I'm see this error in the console when switching files:

```
Illegal argument: globalActivityId: Error: Illegal argument: globalActivityId
    at Object.illegalArgument (file:///Users/matb/projects/vscode/out/vs/base/common/errors.js:152:20)
    at ActivitybarPart.showGlobalActivity (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/activitybar/activitybarPart.js:94:32)
    at ActivitybarPart.showActivity (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/activitybar/activitybarPart.js:86:25)
    at ActivityService.showActivity (file:///Users/matb/projects/vscode/out/vs/workbench/services/activity/browser/activityService.js:27:41)
    at StatusUpdater.render (file:///Users/matb/projects/vscode/out/vs/workbench/parts/scm/electron-browser/scmActivity.js:52:61)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/scm/electron-browser/scmActivity.js:30:75
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:238:125
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:103:38)
    at MainThreadSCMProvider.$updateSourceControl (file:///Users/matb/projects/vscode/out/vs/workbench/api/electron-browser/mainThreadSCM.js:205:31)
    at MainThreadSCM.$updateSourceControl (file:///Users/matb/projects/vscode/out/vs/workbench/api/electron-browser/mainThreadSCM.js:328:22)
    at RPCProtocol._doInvokeHandler (file:///Users/matb/projects/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:215:27)
    at RPCProtocol._invokeHandler (file:///Users/matb/projects/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:200:54)
    at RPCProtocol._receiveRequest (file:///Users/matb/projects/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:155:50)
    at RPCProtocol._receiveOneMessage (file:///Users/matb/projects/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:138:26)
    at file:///Users/matb/projects/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:75:92
    at file:///Users/matb/projects/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:248:21
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:103:38)
    at Socket.<anonymous> (file:///Users/matb/projects/vscode/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

Looks like it tries to look up a global activity for `workbench.view.scm` which is not registered? 

VS Code version: code-oss-dev 1.25.0 (Commit unknown, Date unknown)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Users/matb/projects/vscode/.build/electron/Code - OSS.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.13.0
cat-coding|ms-|0.0.1
vsliveshare|ms-|0.3.262

</details>

**Comment by sandy081** [comment]
Fixed by fc6c30ed3158d2e4b30d767e97635b984c9fd32c
