### ISSUE TITLE
"custom request failed: Error: custom request failed" when terminating debug session

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#51302]
When terminating my Dart debug sessions, I get this in the console:

```
  ERR custom request failed: Error: custom request failed
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2888:190
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:153:592)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._error (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:413)
    at n.Class.derive._oncancel.t.internalSend [as _oncancel] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2460:177)
    at n.Class.derive._oncancel._cancelAction (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156:865)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:152:622)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel.cancel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:61)
    at n.Class.derive._creator._cancelAction (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:155:175)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:152:622)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._creator.cancel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:61)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2462:836
    at Array.forEach (native)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2462:804
```

I've put logging at the top of my DA's `customRequest` method and also all locations that send custom requests, but it doesn't appear that any of them are being called during termination when this happens, so I'm not sure how to debug further.

**Comment by DanTup** [comment]
I found the code raising the error and put a breakpoint in it, response is undefined, but I can't inspect `request` at this point to see what the request was:

![screen shot 2018-06-07 at 8 35 59 am](https://user-images.githubusercontent.com/1078012/41085099-e26d2090-6a2d-11e8-970a-6d6680319f0c.png)

**Comment by DanTup** [comment]
Oh, I think I see what's happening.. I have customRequests where I'm not calling `super.customRequest` during the session, and when the session terminates is when Code realises they were never responded to. My bad!

**Comment by DanTup** [comment]
Actually, the above comment is wrong - the super implementation of `customRequest` sends an error (`unrecognised request`). So, I'm unsure how I'm supposed to respond to custom events to avoid this error. @weinand any ideas?

**Comment by eyqs** [comment]
This was resolved in [this commit](https://github.com/Dart-Code/Dart-Code/commit/b7e8f244be84fda1edf92dd1715f98512698256e).

**Comment by DanTup** [comment]
@eyqs It did not - if I made it, it would immediately send an "unrecognised request". If I remember correctly, this issue is because custom requests that do *not* call super are not acknowledged as ever being completed, so when the session ends it complains.

That said, I can't seem to repro today so I'm not sure if it's fixed or I just can't remember exactly what I was doing 🤷‍♂️

**Comment by eyqs** [comment]
I think you can close this issue unless it comes up again. The custom requests just have to call `this.sendResponse(response)` to be completed (in my app).

**Comment by DanTup** [comment]
@eyqs I did that above, and commented that it resulted in "unrecognised request" error? :/

But since I'm not seeing this now, I'll close and re-open if I see it again.
