### ISSUE TITLE
There is bug in 1.24.0

### ISSUE THREAD

**Issue by leozhangjie66** [Microsoft/vscode#51336]
- VSCode Version:1.24.0
- OS Version:win7/win10

I get a error what is "canot read property 'filtyer' of undefined" when i use the Tools For AI in VScode 1.24.0.

**Comment by aeschli** [comment]
Can you add a screenshot of the error and also see if there is more information the Dev Tools Console?
('Help > Toggle Developer Tools')

**Comment by xinyingking** [comment]
I have the same error. 


`Error: Cannot read property 'filter' of undefined
	at PlatformManager.getAll (C:\Users\xinyi\.vscode\extensions\ms-toolsai.vscode-ai-0.1.8\out\src\platformManager.js:27:39)
	at ConfigurationManager.getAll (C:\Users\xinyi\.vscode\extensions\ms-toolsai.vscode-ai-0.1.8\out\src\configurationManager.js:51:48)
	at ConfigExplorerTreeDataProvider.getChildren (c:\Users\xinyi\.vscode\extensions\ms-toolsai.vscode-ai-0.1.8\out\src\treeView\configExplorer\configExplorerTreeDataProvider.js:47:96)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:478
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:887
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:776)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:850)
	at t.fetchChildrenNodes (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:430)
	at t.getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:483:292)
	at e.$getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:481:487)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)`

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-tools-for-ai#36

**Comment by qfyin** [comment]
Thanks for reporting the issue.
We just published a hotfix to resolve this issue, thanks.
