### ISSUE TITLE
Cannot close VS Code: "Cannot read property 'toString' of null"

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#51381]
Mac OS
Version 1.24.0-insider (1.24.0-insider)
b4e6fe3bd751448783ed20c8e49fdabd69514b8d
2018-06-05T16:38:32.971Z

Started up this morning, went to restart the tool to get the latest update, keep getting this error every time i try to Quit the app:

![image](https://user-images.githubusercontent.com/1487073/41118515-0ccbf3c2-6a45-11e8-97ff-9de983f63e31.png)

Errors in Console:

``` console
ERR Cannot read property 'Symbol(Symbol.iterator)' of null: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
	at SourcegraphApi.hover (/Users/chris/.vscode-insiders/extensions/eamodio.remotehub-0.1.1/out/sourcegraphApi.js:55:36)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)
3/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1311   

ERR Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3406:642
    at Object.v [as _notify] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:150:375)
    at Object.enter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:153:592)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._creator._error (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:413)
    at n (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:152:150)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
14/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2265 

Cannot read property 'toString' of null
e.onDidNotificationChange @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2265
```

I had to do a Forced Quit to restart, then the error went away.

**Comment by eamodio** [comment]
I see the same error (starting in the 2nd insider release today), except I get it when using `Files: Save All`, not on shutdown.

When I break in the debugger I see it is coming from `untitledEditorService.ts: isDirty` and the resource is `null` -- But I don't have any untitled documents open. Wait -- seems like when I have my users settings open, that is the "untitled" document.

Here is the stack with the error, but it doesn't look right.
```
Cannot read property 'toString' of null
e.onDidNotificationChange @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
t.onError @ fileActions.ts:102
(anonymous) @ fileActions.ts:1234
then @ winjs.base.js:1451
t.run @ fileActions.ts:1233
(anonymous) @ actions.ts:114
Promise resolved (async)
e.when @ lifecycleService.ts:124
i.Registry.add.e._triggerAndDisposeAction @ actions.ts:100
i.Registry.add.e._createCommandHandler @ actions.ts:92
e.invokeFunction @ instantiationService.ts:57
t._tryExecuteCommand @ commandService.ts:61
(anonymous) @ commandService.ts:50
then @ winjs.base.js:1581
t.executeCommand @ commandService.ts:50
t.run @ actions.ts:165
t.run @ actions.ts:203
(anonymous) @ commandsHandler.ts:306
done @ winjs.base.js:1539
g @ winjs.base.js:1195
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
setTimeout (async)
(anonymous) @ winjs.base.js:1601
n.Class.derive._oncancel @ winjs.base.js:1656
(anonymous) @ winjs.base.js:1598
timeout @ winjs.base.js:1971
t.runAction @ commandsHandler.ts:296
t.run @ commandsHandler.ts:280
e.run @ quickOpenModel.ts:586
e.elementSelected @ quickOpenWidget.ts:535
(anonymous) @ quickOpenWidget.ts:216
```

**Comment by fadedDexofan** [comment]
Same too on any save action
```
workbench.main.js:sourcemap:2285 Cannot read property 'toString' of null
e.onDidNotificationChange @ workbench.main.js:sourcemap:2285
(anonymous) @ workbench.main.js:sourcemap:2284
e.fire @ workbench.main.js:sourcemap:170
e.notify @ workbench.main.js:sourcemap:2277
e.error @ workbench.main.js:sourcemap:3308
t.onError @ workbench.main.js:sourcemap:4867
(anonymous) @ workbench.main.js:sourcemap:4885
then @ workbench.main.js:sourcemap:156
t.run @ workbench.main.js:sourcemap:4885
(anonymous) @ workbench.main.js:sourcemap:2244
```

**Comment by isidorn** [comment]
@eamodio thanks for the repro steps I pushed a fix for your case.
I can not repro any issue in stable, only insiders.

Let me know if anyone still sees exceptions in tomorrow insiders

**Comment by bpasero** [comment]
@isidorn thanks

**Comment by eamodio** [comment]
@isidorn I also found the steps to repo the case that @chrisdias saw. He was using RemoteHub, which uses a custom `FileSystemProvider`, and since everything should be readonly the provider throws on write. So he must have edited an opened file (accidentally or not) and vscode tries to save it on shutdown but the exception stops the shutdown.
