### ISSUE TITLE
Debugger fails to launch after upgrading the VS code to latest 1.24.0

### ISSUE THREAD

**Issue by jaan** [Microsoft/vscode#51502]
- VSCode Version: 1.24.0
- OS Version: MacOS High Sierra - v10.13.3

Steps to Reproduce:

1. Go to "Debug" Mode and try to run the debug config on a typescript spec file.
2. Debugger fails to launch

Error log:
```[2018-06-08 17:19:08.794] [renderer2] [error] Unexpected token / in JSON at position 78: SyntaxError: Unexpected token / in JSON at position 78
    at JSON.parse (<anonymous>)
    at /Users/<user>/.vscode/extensions/christian-kohler.path-intellisense-1.4.2/out/src/utils/config.js:20:25
    at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:76:971)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:80:277)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:84)
    at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:523)
    at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:545:791)
    at e._receiveReply (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:165)
    at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:473)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:634:315
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:637:395
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:95:432
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:764)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:338)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
Can you reproduce this if you disable all extensions?
If yes, can you provide some reproducable steps, like a repository for us to look into?

**Comment by jaan** [comment]
No, it wont occur when i disable all the plugin as said in the description.
It seems to becasue of path intellisense plugin. 
https://github.com/ChristianKohler/PathIntellisense

**Comment by isidorn** [comment]
Please file this issue against that extension then
