### ISSUE TITLE
Exception when opening/closing Welcome tab

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#51598]
In dev, open the Welcome.

```
  ERR Cannot read property 'getContribution' of undefined: TypeError: Cannot read property 'getContribution' of undefined
    at MainThreadComments.getFocusedEditor (file:///Users/joao/Work/vscode/out/vs/workbench/api/electron-browser/mainThreadComments.js:155:64)
    at file:///Users/joao/Work/vscode/out/vs/workbench/api/electron-browser/mainThreadComments.js:75:41
    at Emitter.fire (file:///Users/joao/Work/vscode/out/vs/base/common/event.js:103:38)
    at EditorService.doEmitActiveEditorChangeEvent (file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:100:43)
    at EditorService.handleActiveEditorChange (file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:94:18)
    at file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:107:27
    at Emitter.fire (file:///Users/joao/Work/vscode/out/vs/base/common/event.js:103:38)
    at file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:657:49
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/joao/Work/vscode/out/vs/base/common/winjs.base.js:1581:49)
    at EditorGroupView.doShowEditor (file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:654:84)
    at EditorGroupView.doOpenEditor (file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:642:41)
    at EditorGroupView.openEditor (file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:624:25)
    at EditorService.doOpenEditor (file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:239:26)
    at EditorService.openEditor (file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:218:29)
    at WelcomePage.openEditor (file:///Users/joao/Work/vscode/out/vs/workbench/parts/welcome/page/electron-browser/welcomePage.js:204:39)
    at WelcomePageAction.run (file:///Users/joao/Work/vscode/out/vs/workbench/parts/welcome/page/electron-browser/welcomePage.js:76:18)
    at file:///Users/joao/Work/vscode/out/vs/workbench/common/actions.js:81:68
    at <anonymous>
```

And when you close it:

```
  ERR Cannot read property 'getContribution' of undefined: TypeError: Cannot read property 'getContribution' of undefined
    at MainThreadComments.getFocusedEditor (file:///Users/joao/Work/vscode/out/vs/workbench/api/electron-browser/mainThreadComments.js:155:64)
    at file:///Users/joao/Work/vscode/out/vs/workbench/api/electron-browser/mainThreadComments.js:75:41
    at Emitter.fire (file:///Users/joao/Work/vscode/out/vs/base/common/event.js:103:38)
    at EditorService.doEmitActiveEditorChangeEvent (file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:100:43)
    at EditorService.handleActiveEditorChange (file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:94:18)
    at file:///Users/joao/Work/vscode/out/vs/workbench/services/editor/browser/editorService.js:107:27
    at Emitter.fire (file:///Users/joao/Work/vscode/out/vs/base/common/event.js:103:38)
    at EditorGroupView.doCloseActiveEditor (file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:856:40)
    at EditorGroupView.doCloseEditor (file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:795:22)
    at file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:788:23
    at _Base.Class.derive._creator.CompletePromise_then [as then] (file:///Users/joao/Work/vscode/out/vs/base/common/winjs.base.js:1581:49)
    at EditorGroupView.closeEditor (file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:783:47)
    at CloseOneEditorAction.run (file:///Users/joao/Work/vscode/out/vs/workbench/browser/parts/editor/editorActions.js:437:34)
    at EditorCommandsContextActionRunner.ActionRunner.runAction (file:///Users/joao/Work/vscode/out/vs/base/common/actions.js:184:40)
    at EditorCommandsContextActionRunner.ActionRunner.run (file:///Users/joao/Work/vscode/out/vs/base/common/actions.js:177:25)
    at EditorCommandsContextActionRunner.run (file:///Users/joao/Work/vscode/out/vs/workbench/common/editor.js:530:41)
    at ActionItem.BaseActionItem.onClick (file:///Users/joao/Work/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:129:32)
    at Immediate.<anonymous> (file:///Users/joao/Work/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:111:70)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by joaomoreno** [comment]
Also when opening/closing images.

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/a3ba24d849cdde7785f08983b335ff1d3ee3a85e

**Comment by joaomoreno** [comment]
@isidorn Not fixed.

**Comment by isidorn** [comment]
@joaomoreno I can not repro with latest out of source
Also the fix seeems to be good, notice here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadComments.ts#L126
