### ISSUE TITLE
Bundled TypeScript (v2.9) has issues with auto-complete, intellisense, ctrl+click on JS projects

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#51626]
- VSCode Version: May 2018 (version 1.24)
- OS Version: Windows 10, Version 1803

Steps to Reproduce:

1. Create/Open a JavaScript project with a `jsconfig.json` file similar to this:

```json
{
    "compilerOptions": {
        "target": "es6",
        "moduleResolution": "node"
    },
    "exclude": [
        ".gitlab",
        ".vscode",
        "node_modules",
        "reports",
        "target"
    ]
}
```

2. Open any `.js` file and just left-click a function name.

3. Get this:

```
[Error  - 5:46:33 PM] 'occurrences' request failed with error.
Error processing request. Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90203:113
    at Object.map (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1745:29)
    at getDocumentHighlights (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90203:42)
    at Object.getOccurrencesAtPosition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90192:31)
    at IOSession.Session.getOccurrences (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:96285:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:95865:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97221:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97250:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98456:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

4. Also, hover the mouse on a function name and get this:

```
[Error  - 5:49:10 PM] 'quickinfo' request failed with error.
Error processing request. Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89815:37)
    at Object.getQuickInfoAtPosition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89988:30)
    at IOSession.Session.getQuickInfoWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:96629:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:95719:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97221:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97250:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98456:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

5. And as a last example, try to <kbd>Alt</kbd>+<kbd>Click</kbd> a function name on an `import` statement and get this:

```
[Error  - 5:50:20 PM] 'definition' request failed with error.
Error processing request. Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89815:37)
    at Object.getDefinitionAtPosition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90153:105)
    at IOSession.Session.getDefinition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:96208:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:95679:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97221:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97250:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98456:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

For each different action there's a different error:

- `[Error  - 5:46:33 PM] 'occurrences' request failed with error.`
- `[Error  - 5:49:10 PM] 'quickinfo' request failed with error.`
- `[Error  - 5:50:20 PM] 'definition' request failed with error.`

Does this issue occur when all extensions are disabled?: **Yes**

Workaround available?

1. Install TypeScript v2.8.3 globally (e.g: `npm -g install typescript@2.8.3`, or `typescript@next` also seems to work just fine).
2. Configure your `typescript.tsdk` user setting to point to that version (e.g: `"typescript.tsdk": "C:\\Users\\AmaralR\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib"`
3. Use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and pick `TypeScript: Select TypeScript Version`.
4. You'll see your globally installed version on the list, select that.
5. TypeScript Standalone Server will relaunch in the background with that version.
6. Profit!

**Comment by mjbvz** [comment]
I can't repo this with a simple project containing just that jsconfig and a js file. Can you please share a small example project and/or additional repo steps. What do the function and imports look like for example?

**Comment by whhhooop** [comment]
Hmm i could not reproduce it on a simple project as well. So i removed everything that does not cause the bug in one of my projects. It turns out jsconfig.json might not be the problem (although it helps to remove the file. weird.)
I reproduced above-mentioned error in a single-file project without jsconfig.json. All i have is index.js with the following code
```
/**
 * @param {<Array<number>} arr
 */
function foo(arr) {}
```
And the problem is the first "<" in the param type. If i change param type from `<Array<number>` to `Array<number>` everything works fine. Otherwise i have `TypeError: Cannot read property 'getSourceFile' of undefined` error.

**Comment by mjbvz** [comment]
Thanks @whhhooop. I opened https://github.com/Microsoft/TypeScript/issues/24913 to track this upstream

@rfgamaral  Does that sound like your issue as well or is the problem caused by something different?

**Comment by rfgamaral** [comment]
@mjbvz Maybe, I'll need to check tomorrow at work. I'll report back.

**Comment by mjbvz** [comment]
@rafaelstz So everything works properly when you upgrade to typescript 3.0? If so, I'll close the bug as upstream. We'll pick up 3.0 next iteration but until then you can work around this by manually upgrading
