### ISSUE TITLE
Extension host terminated unexpectedly and Terminal console not working

### ISSUE THREAD

**Issue by efranchi** [Microsoft/vscode#51696]
1) Open Visual Studio Code 

- Version 1.24.0
- Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
- Date 2018-06-06T17:35:40.560Z
- Shell 1.7.12
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

2) Wait a few secs
3) Error message "Extension host terminated unexpectedly" shows up.
4) Terminal console opens for a couple of secs then it closes
==========================================

Console errors:

1) Extension host terminated unexpectedly. Code:  0  Signal:  null
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2946 

2) Extension host terminated unexpectedly.
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2265 

Output console: (JSON Language server)
1) Error Request textDocument/colorPresentation failed
2) Error: Connection got disposed.
       at Object.dispose (c:\Program Files\Microsoft VS 
       Code\resources\app\extensions\json-language-features\node_modules\vscode-jsonrpc\lib\main.js:825.25)
       at Object.dispose (c:\Program Files\Microsoft VS 
       Code\resources\app\extensions\json-language-features\node_modules\vscode-languageclient\lib\client.js:57.35)
       at Object.dispose (c:\Program Files\Microsoft VS 
       Code\resources\app\extensions\json-language-features\node_modules\vscode-languageclient\lib\client.js:1895.28)						
       at <anonymous>

**Comment by Tyriar** [comment]
Let's use this issue for the extension host problem. If you want to follow up on the terminal problem please create a new issue.

**Comment by aeschli** [comment]
Can you put `"java.trace.server": "verbose"` in the settings and check the  the `Output` view, `JSON language` tab for additional messages.

**Comment by efranchi** [comment]
Trace result:


/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1311  INFO no standard startup: panel is active
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1311   ERR Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendRequest (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\node_modules\vscode-languageclient\lib\client.js:1562:19)
	at provideDocumentColors (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\node_modules\vscode-languageclient\lib\colorProvider.js:56:27)
	at Object.provideDocumentColors (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\node_modules\vscode-languageclient\lib\colorProvider.js:71:23)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:699:487
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:887
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:776)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:850)
	at e.provideColors (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:699:441)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:709:680
	at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:701:385)
	at e.$provideDocumentColors (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:709:642)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166 WARNING: Promise with no error callback:171
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166 Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166 WARNING: Promise with no error callback:175
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:166 Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1311   ERR Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendRequest (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\node_modules\vscode-languageclient\lib\client.js:1562:19)
	at Object.provideFoldingRanges (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\client\out\jsonMain.js:131:31)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:700:202
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:887
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:776)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:850)
	at e.provideFoldingRanges (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:700:156)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:710:216
	at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:701:385)
	at e.$provideFoldingRanges (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:710:178)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)

**Comment by starsundar** [comment]
Was there ever a solution for this issue ?

**Comment by aeschli** [comment]
This remained a mystery bug. Please reopen if you still this.
