### ISSUE TITLE
Debug.toolBarLocation :docked  doesn't works well

### ISSUE THREAD

**Issue by dholakiyaankit** [Microsoft/vscode#51741]
Issue Type: <b>Bug</b>

after updating the vs code I changed my code to
 "debug.toolBarLocation": "docked"
This doesn't work all the time, the debugging panel disappears time to time.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (1.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
es7-react-js-snippets|dsz|1.8.2
vscode-babel-coloring|dza|0.0.4
debugger-for-chrome|msj|4.6.0
js-jsx-snippets|sky|0.0.9
vscode-react-native|vsm|0.6.11

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
The debugging panel should only appear while you are debugging, that is designed behavior.
If this is not the case then please provide a video showing the issue.
Or exact steps to repro. Thanks

**Comment by dholakiyaankit** [comment]
![desktop](https://user-images.githubusercontent.com/6862074/41399999-777fa4f4-6fd9-11e8-9941-48ada811398d.png)
as you can see it doesn't appears event if I am on debugging mode.

For more info:
I have this in my console
```

Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (c:\Users\.vscode\extensions\msjsdiag.debugger-for-chrome-4.6.0\node_modules\vscode-chrome-debug-core\out\src\utils.js:71:24)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by cROSs116** [comment]
Oh, i see what u mean, its only on the debug tab, not the behavior that i was expecting with docked :(, going back to "floating", would have loved it on the explore window aswell. Please make it a feature?

**Comment by dholakiyaankit** [comment]
@isidorn  I see what you mean, I think this should be visible for explorer too.

**Comment by isidorn** [comment]
Just put floating, and drag it to the viewlet area, then you will see it for every viewlet, even the explorer

**Comment by dholakiyaankit** [comment]
I know that, but how will you justify docked feature? it should be visible to any area even for the explorer.

**Comment by nhdoublek** [comment]
Why would I want to only have access to the debug toolbar when on the debug panel.  It makes no sense that I would have to switch to the explorer panel to open a file to set break points then go back to the debug panel step through code via the toolbar.  Why can't it just be docked under the menu like every other windows applications works.  I have hated the floating toolbar since I started using VSCode.

**Comment by dholakiyaankit** [comment]
@nhdoublek Exactly, Its been quite a few days I want to explain the same to them, But looks like they are not listening.
