### ISSUE TITLE
Unfolded telemetry events

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5186]
Still getting unfolded events from telemetry in 0.1.15-insiders:
We get folded as well as folded events. All unfolded events seem to happen on Mac.
```
TypeError: Cannot read property 'document' of null 
 at e.Object.defineProperty.get [as document] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:19:10563) 
 at Guides.getRangesForLine (/Users/a123/.vscode-insiders/extensions/spywhere.guides-0.2.1/out/src/extension.js:215:47) 
 at Guides.updateEditor (/Users/a123/.vscode-insiders/extensions/spywhere.guides-0.2.1/out/src/extension.js:142:34) 
 at null._onTimeout (/Users/a123/.vscode-insiders/extensions/spywhere.guides-0.2.1/out/src/extension.js:121:19) 
 at Timer.listOnTimeout (timers.js:89:15) 
```

**Comment by aeschli** [comment]
Also seems to happen in Win:
TypeError: Cannot read property 'forEach' of undefined 
 at C:\Users\a123\.vscode-insiders\extensions\Zignd.html-css-class-completion-0.0.2\extension.js:17:17 
 at Object.p [as _notify] (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:12448) 
 at Object.__dirname.undefined.L.enter (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:15610) 
 at __dirname.undefined.t.Class.define._run (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:17436) 
 at __dirname.undefined.t.Class.define._completed (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:16877) 
 at h (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:16675) 
 at doNTCallback0 (node.js:420:9) 
 at process._tickCallback (node.js:349:13)

**Comment by aeschli** [comment]
Error: Canceled 
 at /Users/a123/.vscode-insiders/extensions/ms-vscode.csharp-0.3.7/out/omnisharpServer.js:235:31 
 at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:14035) 
 at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:15488) 
 at e.cancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:16809) 
 at e.cancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:17419) 
 at DiagnosticsProvider._validateProject (/Users/a123/.vscode-insiders/extensions/ms-vscode.csharp-0.3.7/out/features/diagnosticsProvider.js:149:37) 
 at DiagnosticsProvider._onDocumentAddOrChange (/Users/a123/.vscode-insiders/extensions/ms-vscode.csharp-0.3.7/out/features/diagnosticsProvider.js:102:18) 
 at DiagnosticsProvider.<anony

**Comment by jrieken** [comment]
to verify

* install an extension that is known to throw errors, like `spywhere.guides`.
* toggle between a JS file and another files, notice exception showing in the console
* open dev tools, open workbench.main.js, find the `handleEvent` method of the _mainTelemetryService_ (use format (`{}`-icon) and outline (cmd+shift+o) feature to find it)
* make sure no PII is contained in the data we send, esp when sending the error info printed on the console
