### ISSUE TITLE
Building 1.24.1 on Windows 7 - Error: Cannot find module 'extensions\postinstall'

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#52058]
- VSCode Version: 1.24.1, source checked out from tag
- OS Version: Windows 7 x64

node: v8.9.4
npm:  5.6.0

Steps to Reproduce:

```
git clone (main repo)
git checkout 1.24.1

"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

set PYTHON=C:\Program Files (x86)\Python271\python.exe

set PATH=%PATH%;C:\Program Files\7-Zip

npm.cmd config set loglevel verbose

mkdir tmp

npm.cmd config set cache tmp --global

npm.cmd cache clean --force

npm set npm_config_arch ia32
```

Then `yarn` per instructions:

```
C:\acme\Dev\projects\vscode>yarn
yarn install v1.7.0
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.8: The platform "win32" is incompatible with this module.
info "vscode-fsevents@0.3.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ node build/npm/postinstall.js
yarn install v1.7.0
warning package.json: No license field
warning vscode-extensions@0.0.1: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

$ node ./postinstall
[##] 2/2module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\acme\Dev\projects\vscode\extensions\postinstall'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.




C:\acme\Dev\projects\vscode>yarn -v
1.7.0

```

**Comment by RMacfarlane** [comment]
Does the same error happen when you don't do `npm set npm_config_arch ia32`?

**Comment by mrkafk** [comment]
Hello RMacfarlane,

It works (when I do not use `npm set npm_config_arch ia32`). Thanks!
