### ISSUE TITLE
Node.js debugger adapter crashes with TypeError about 'url' of undefined

### ISSUE THREAD

**Issue by dramforever** [Microsoft/vscode#52369]
Issue Type: <b>Bug</b>

This crash occurs on both 1.25.0-insider and 1.24.1.

## Steps to reproduce:

Put this file into `vscbug.js`

```javascript
function fc(fn) {
    return new Promise((resolve, _reject) =>
        setImmediate(() => resolve(fn())));
}

fc(parseInt).then(console.log);
```

And hit `F5` to start debugging.

### Expected

Debugging runs normally to completion, with output:

```
NaN
```

### Actual

The debugger adapter crashes. This is shown in the debugging tab:

```
D:\Program Files\nodejs\node.exe --inspect-brk=17564 vscbug.js 
Debugger listening on ws://127.0.0.1:17564/88a53b9b-7fe0-4b9e-8436-adb5261d61de

******** Unhandled error in debug adapter: TypeError: Cannot read property 'url' of undefined
    at isLogpointMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\internalSourceBreakpoint.js:25:55)
    at Object.stackTraceWithoutLogpointFrame (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\internalSourceBreakpoint.js:28:9)
    at NodeDebugAdapter.onConsoleAPICalled (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:983:50)
    at NodeDebugAdapter.onConsoleAPICalled (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:382:19)
    at Client.chrome.Runtime.on.params (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:317:67)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at Client.processMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:78:18)
    at LoggingSocket.Client.socket.on (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-de[...]
```

VS Code version: Code - Insiders 1.25.0-insider (b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9, 2018-06-19T07:49:07.900Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (2.98GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
I believe this is the same as https://github.com/Microsoft/vscode-chrome-debug-core/issues/334 which is fixed in the next Insiders.

**Comment by dramforever** [comment]
Okay, thanks
