### ISSUE TITLE
Error when running from sources

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#52440]
```
 ERR No extension gallery service configured.: Error: No extension gallery service configured.
    at ExtensionGalleryService.query (file:///Users/alex/src/vscode/out/vs/platform/extensionManagement/node/extensionGalleryService.js:298:56)
    at ExtensionTipsService.processConfigContent (file:///Users/alex/src/vscode/out/vs/workbench/parts/extensions/electron-browser/extensionTipsService.js:218:41)
    at file:///Users/alex/src/vscode/out/vs/workbench/parts/extensions/electron-browser/extensionTipsService.js:165:58
    at Object.notifySuccess [as _notify] (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1051:18)
    at argDone (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1828:37)
    at Promise.then.errors.(anonymous function) (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1853:78)
    at Object.notifySuccess [as _notify] (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:867:30)
    at _Base.Class.derive._creator._run (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1083:29)
    at _Base.Class.derive._creator._completed (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1051:18)
    at Object.notifySuccess [as _notify] (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (file:///Users/alex/src/vscode/out/vs/base/common/winjs.base.js:1051:18)
    at IconvLiteDecoderStream.<anonymous> (file:///Users/alex/src/vscode/out/vs/workbench/services/files/electron-browser/fileService.js:187:73)
    at emitNone (events.js:111:20)
    at IconvLiteDecoderStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I am just interacting with the extensions viewlet.

**Comment by ramya-rao-a** [comment]
There is a check in place that ensures `processConfigContent` never gets called if the gallery is not configured, so I don't see how this can happen. I am not able to repro either.

Can you provide more details about your setup and what actions you were performing?

**Comment by alexandrudima** [comment]
Perhaps it has something to do with `isEnabled` not being invoked as a function.

Perhaps
```ts
if (!this.isEnabled) { return TPromise.as([]); }
```
should be
```ts
if (!this.isEnabled()) { return TPromise.as([]); }
```

at [this location](https://github.com/Microsoft/vscode/blob/b7e6e04666ca8dde560b69081c43365dce77d12a/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L211)

**Comment by ramya-rao-a** [comment]
Thanks @alexandrudima. That must be it.

@JacksonKearl This got introduced in #51941. This [test case](https://github.com/Microsoft/vscode/blob/442e5e202a89c1f8efe642c89c0554cab1f15a9e/src/vs/workbench/parts/extensions/test/electron-browser/extensionsTipsService.test.ts#L303) was supposed to cover the case of no gallery service. Can you fix this and see why the test case wasn't failing?
