### ISSUE TITLE
Language server extension crashes in run mode but not in debug mode.

### ISSUE THREAD

**Issue by tansvanio** [Microsoft/vscode#52488]
Greetings,

I have come to submit a bug report because I have encountered a serious problem in the development of a Visual Studio Code extension.

Up until a few days ago I was developing my extension, which means I program it and test it in debug mode. Every once in a while I would generate a vsix package, install it and test it without problems.

I noticed today that while my extension runs perfectly fine in debug mode (opening the source and pressing F5) in a normal installation (install from vsix). I even tried setting them up to run with the same debug settings in both run and debug instances but the problem persists.

Another thing I tried was adding a try catch block to catch the language server disposable, but this also does not work. In fact I noticed the extension does not even manage to run code inside the activate function.

The extension crashes with the following error in the logs:

`[2018-06-20 15:55:27.675] [renderer1] [info] no standard startup: not a new window
[2018-06-20 15:55:29.950] [renderer1] [error] Channel has been closed: Error: Channel has been closed
	at e.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:575:761)
	at e.append (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:575:300)
	at Socket.serverProcess.stderr.on.data (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\lib\main.js:275:92)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
`

And here is the full error from the developer console:

`[Extension Host] Error: Channel has been closed
	at e.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:575:761)
	at e.appendLine (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:575:395)
	at LanguageClient.info (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\lib\client.js:1574:28)
	at LanguageClient.handleConnectionClosed (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\lib\client.js:1875:18)
	at LanguageClient.handleConnectionClosed (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at IPCMessageReader.AbstractMessageReader.fireClose (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at ChildProcess.<anonymous> (C:\Users\Ricardo da Silva\.vscode\extensions\luduscristaltec.age-language-server-0.3.58\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:253:61)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
t.log @ console.ts:136`

I have seen some people are having similar problems and I wonder if this is fixable on my part.
Is anyone able to give me some insight?

Many thanks,
Ricardo

**Comment by tansvanio** [comment]
Did further testing and found out some code inside the activation function is indeed working, which means the problem is directily related to the declaration or subscription of the language server. This is however very strange, because I have all the activation code inside a try catch, which is not catching any errors even though the server part of the extension crashes.

**Comment by dbaeumer** [comment]
From the stack trace it looks like the language server connection gets closed. So the extension is not really crashing but the language server does. There is a difference in starting the server whether you are debugging or nor but I am not sure if this is the case for you. Can you share your code?
