### ISSUE TITLE
Code-insiders doesn't start

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#52576]
Issue Type: <b>Bug</b>

Testing #51422

Steps to Reproduce:
1. Set `"window.titleBarStyle": "custom"` in setting.json
2. Restart Code

bug

<details>
<summary>Output; code-insiders --verbose</summary>

```
>code-insiders --verbose

[main 18:31:47] Starting VS Code
[main 18:31:47] from: d:\Program Files\Microsoft VS Code Insiders\resources\app
[main 18:31:47] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 18:31:47] Resolving machine identifier...
[main 18:31:47] Resolved machine identifier: 
[main 18:31:47] update#setState idle
[43648:0621/183148.555:INFO:CONSOLE(1362)] "%cTRACE", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[main 18:31:48] windowsService#whenSharedProcessReady
[43648:0621/183148.639:INFO:CONSOLE(1362)] "%cTRACE", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183148.651:INFO:CONSOLE(1362)] "%cTRACE", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183148.686:INFO:CONSOLE(1362)] "%c  ERR", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183148.687:INFO:CONSOLE(5)] "[uncaught exception]: TypeError: Cannot read property '1' of null", source: file:///D:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[43648:0621/183148.687:INFO:CONSOLE(5)] "TypeError: Cannot read property '1' of null
    at n (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2406:118)
    at t.setupCustomMenubar (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2407:64)
    at t.setupMenubar (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2404:395)
    at t.createContentArea (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2412:202)
    at t.create (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2386:733)
    at t.createMenubarPart (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5263:79)
    at t.renderWorkbench (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5262:506)
    at t.startup (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5243:584)
    at e.createWorkbench (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5297:66)
    at e.createContents (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5296:477)
    at e.open (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5304:990)
    at file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5313:28
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)", source: file:///D:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[main 18:31:48] windowsService#startCrashReporter
[43648:0621/183149.620:INFO:CONSOLE(1362)] "%c  ERR", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183149.636:INFO:CONSOLE(1362)] "%c  ERR", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183149.890:INFO:CONSOLE(1362)] "%c  ERR", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[main 18:31:49] windowsService#isFocused 1
[43648:0621/183150.634:INFO:CONSOLE(1362)] "%cTRACE", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183150.718:INFO:CONSOLE(1362)] "%cTRACE", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183150.718:INFO:CONSOLE(1362)] "%cTRACE", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[43648:0621/183151.188:INFO:CONSOLE(1362)] "%cTRACE", source: file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1362)
[main 18:32:05] Lifecycle#window-before-close 1
[main 18:32:05] Lifecycle#onBeforeWindowClose.fire()
[main 18:32:05] Lifecycle#window-before-close 1
[main 18:32:05] Lifecycle#window-close 1
[main 18:32:05] Lifecycle#window-closed 1
[main 18:32:05] Lifecycle#onShutdown.fire()
[main 18:32:05] Lifecycle#window-all-closed
[main 18:32:05] Lifecycle#before-quit
[main 18:32:05] Lifecycle#onBeforeShutdown.fire()
[main 18:32:05] App#will-quit: disposing resources
```

</details>

---

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T08:08:46.972Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (2.19GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by bpasero** [comment]
@EbXpJ6bp can you still reproduce? do you get any output?

**Comment by EbXpJ6bp** [comment]
@bpasero yes.
I got a following output after starting code-insiders with `--verbose` (from first comment)
``` 
[43648:0621/183148.687:INFO:CONSOLE(5)] "[uncaught exception]: TypeError: Cannot read property '1' of null", source: file:///D:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[43648:0621/183148.687:INFO:CONSOLE(5)] "TypeError: Cannot read property '1' of null
    at n (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2406:118)
    at t.setupCustomMenubar (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2407:64)
    at t.setupMenubar (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2404:395)
    at t.createContentArea (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2412:202)
    at t.create (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2386:733)
    at t.createMenubarPart (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5263:79)
    at t.renderWorkbench (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5262:506)
    at t.startup (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5243:584)
    at e.createWorkbench (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5297:66)
    at e.createContents (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5296:477)
    at e.open (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5304:990)
    at file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5313:28
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)", source: file:///D:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
```

**Comment by bpasero** [comment]
@EbXpJ6bp something is weird, I am trying to find the location in sourcecode but the line numbers do not match, e.g. I tried to open `Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2406:118` but that seems not the right location. Are you sure the output is from the same version? Do you have an extension that maybe modifies the source bits?

**Comment by EbXpJ6bp** [comment]
@bpasero 
Sorry, I pasted it from my first comment. So, the output comes from c5c7d43, 2018-06-21T05:19:04.026Z.

Following output is correct.  (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:18:12.763Z)
```
[712:0627/233408.722:INFO:CONSOLE(5)] "[uncaught exception]: TypeError: Cannot read property '1' of null", source: file:///D:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[712:0627/233408.722:INFO:CONSOLE(5)] "TypeError: Cannot read property '1' of null
    at n (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2427:962)
    at t.setupCustomMenubar (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2429:258)
    at t.setupMenubar (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2426:265)
    at t.createContentArea (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2434:202)
    at t.create (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2408:733)
    at t.createMenubarPart (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5285:79)
    at t.renderWorkbench (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5284:506)
    at t.startup (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5265:584)
    at e.createWorkbench (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5319:66)
    at e.createContents (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5318:477)
    at e.open (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5326:989)
    at file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5335:28
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)", source: file:///D:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
```

**Comment by Tyriar** [comment]
Verified with code review
