### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by naveed-butt** [Microsoft/vscode#53088]
Issue Type: <b>Bug</b>

This notification pops up every time I open VS Code... It is not bothering me in anything (at least not in my day to day activities) but there is a notification that keeps on popping up every time.. 

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.89GB (7.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.4
php-intellisense|fel|2.3.3
vscode-solution-explorer|fer|0.2.29
python|ms-|2018.6.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.7.0
easyzoom|Nab|0.1.0
vscode-docker|Pet|0.0.27
vscode-icons|rob|7.24.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Next time it pops up, can you check the window log:

![image](https://user-images.githubusercontent.com/323878/41989908-c1352616-79f5-11e8-93f3-13660da232cc.png)

For the full stack? Also, does it appear if you start with `--disable-extensions`? It could be from an extension.

**Comment by naveed-butt** [comment]
No the issue does not appear after I have disabled the extensions

**Comment by naveed-butt** [comment]
Here is the Window log

[2018-07-02 10:01:30.278] [renderer1] [info] standard startup {"version":"1.24.1","ellapsed":2007,"timers":{"ellapsedExtensions":919,"ellapsedExtensionsReady":2330,"ellapsedRequire":672,"ellapsedEditorRestore":489,"ellapsedViewletRestore":29,"ellapsedWorkbench":602,"ellapsedWindowLoadToRequire":328,"ellapsedTimersToTimersComputed":19,"ellapsedNlsGeneration":0,"ellapsedAppReady":51,"ellapsedWindowLoad":322},"platform":"win32","release":"10.0.16299","arch":"x64","totalmem":17066569728,"freemem":7791104000,"meminfo":{"workingSetSize":297932,"peakWorkingSetSize":307764,"privateBytes":256332,"sharedBytes":57440},"cpus":{"count":4,"speed":2808,"model":"Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz"},"loadavg":[0,0,0],"initialStartup":true,"isVMLikelyhood":0,"hasAccessibilitySupport":false,"emptyWorkbench":false,"common.machineId":"e2a265c73f054452e862f3f8c08785e77b22bb0335dabb57581c772dafcd42a6","sessionID":"dd9a6256-75f7-409d-8a81-c5bb948573af1530507686685","commitHash":"24f62626b222e9a8313213fb64b10d741a326288","common.platformVersion":"10.0.16299","common.platform":"Windows","common.nodePlatform":"win32","common.nodeArch":"x64","timestamp":"2018-07-02T05:01:30.312Z","common.timesincesessionstart":3626,"common.sequence":10,"common.version.shell":"1.7.12","common.version.renderer":"58.0.3029.110","common.firstSessionDate":"Mon, 14 May 2018 11:02:03 GMT","common.lastSessionDate":"Mon, 02 Jul 2018 04:59:12 GMT","common.isNewSession":"0","common.instanceId":"fbc3ac6f-deb4-4b81-9612-f432eb6be1ab"}

**Comment by naveed-butt** [comment]
Why would you close this ? I could not reach my machine over the weekend...

**Comment by roblourens** [comment]
I can always reopen it :)

That doesn't show the issue, can you see if the full stack is in the dev tools console? (Help > Toggle Developer Tools)

**Comment by naveed-butt** [comment]
This is the error in the log file...
[2018-07-03 10:44:26.721] [renderer1] [error] Pending request cancelled: /codecheck: Error: Pending request cancelled: /codecheck
    at RequestQueue.cancelRequest (C:\Users\naveed.butt\.vscode\extensions\ms-vscode.csharp-1.15.2\src\omnisharp\requestQueue.ts:62:29)
    at RequestQueueCollection.cancelRequest (C:\Users\naveed.butt\.vscode\extensions\ms-vscode.csharp-1.15.2\src\omnisharp\requestQueue.ts:157:15)
    at token.onCancellationRequested (C:\Users\naveed.butt\.vscode\extensions\ms-vscode.csharp-1.15.2\src\omnisharp\server.ts:494:36)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
    at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:102:109)
    at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:102:833)
    at DiagnosticsProvider._onDocumentRemove (C:\Users\naveed.butt\.vscode\extensions\ms-vscode.csharp-1.15.2\src\features\diagnosticsProvider.ts:178:50)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:784)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:684:315
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
    at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:114)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by naveed-butt** [comment]
and this is the developer console error...

workbench.main.js:sourcemap:2265 Error: Cannot read property 'forEach' of undefined
    at project.elements.forEach.element (C:\Users\naveed.butt\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.29\out\model\Projects\Kinds\StandardProject.js:293:33)
    at Array.forEach (native)
    at StandardProject.parseDocument (C:\Users\naveed.butt\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.29\out\model\Projects\Kinds\StandardProject.js:291:26)
    at new StandardProject (C:\Users\naveed.butt\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.29\out\model\Projects\Kinds\StandardProject.js:34:18)
    at Function.<anonymous> (C:\Users\naveed.butt\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.29\out\model\Projects\ProjectFactory.js:48:20)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\naveed.butt\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.29\out\model\Projects\ProjectFactory.js:4:58)
    at <anonymous>

**Comment by naveed-butt** [comment]
Looks like an issue with Solution Explorer. You can close this one now :)
