### ISSUE TITLE
ERR File not found: package.json

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53204]
Steps to Reproduce:

1. open a folder without package.json
2. check the console

  ```
ERR File not found (file:///Users/bpasero/Documents/ticino-playground/package.json): Error: File not found (file:///Users/bpasero/Documents/ticino-playground/package.json)
    at new FileOperationError (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/files/common/files.js:201:32)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/files/electron-browser/fileService.js:243:40
    at Object.notifyError [as _notify] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.js:1224:50)
    at Object.enter (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.js:916:30)
    at Promise_ctor._run (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._error (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.js:1056:18)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/async.js:677:135
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/node/extfs.js:37:32
    at /Users/bpasero/Development/Microsoft/monaco/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (original-fs.js:114:15)
```

This seems to originate from `workspaceStats.ts`

**Comment by chrmarti** [comment]
@ramya-rao-a Your recent change does not handle the mix of folders with `package.json` and without `package.json`.

**Comment by ramya-rao-a** [comment]
Thanks @chrmarti

**Comment by ramya-rao-a** [comment]
To verify load a multi root setup where one folder has package.json file and another that doesn't.
The console shouldn't have the above errors
