### ISSUE TITLE
Has errors, when run `code .` in command line

### ISSUE THREAD

**Issue by marekchen** [Microsoft/vscode#53216]
- VSCode Version: 1.24.1 (1.24.1)
- OS Version: macOS 10.13.5

Steps to Reproduce:

1.run `code .` in command line
has the following error log:
```
{ errorCode: 'load',
  moduleId: 'iconv-lite',
  neededBy: [ 'vs/base/node/encoding', 'vs/code/node/cli' ],
  detail: 
   { Error: Cannot find module 'iconv-lite'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:56)
       at e.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:587)
       at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:27:777)
       at Object.errorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:27:898)
       at e.triggerErrorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:952)
       at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:657 code: 'MODULE_NOT_FOUND' } }
{ errorCode: 'load',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ],
  detail: 
   { Error: Cannot find module 'minimist'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:56)
       at e.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:587)
       at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:27:777)
       at Object.errorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:27:898)
       at e.triggerErrorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:952)
       at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:657 code: 'MODULE_NOT_FOUND' } }
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Your install appears to be corrupt. Please try re-installing VS Code
