### ISSUE TITLE
Smoketest: fails on extension check

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#53315]
OS X

Get the latest vs code insiders, run the smoke test. Notice error:

1) Test
       Extensions
         install and activate vscode-smoketest-check extension:
     Error: Timeout: click 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[aria-label="vscode-smoketest-check"] .extension li[class='action-item'] .extension-action.install' after 20 seconds.
      at /Users/isidor/Development/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
      at <anonymous>

**Comment by chrmarti** [comment]
Also on Linux.
