### ISSUE TITLE
gyp configure error when building on Manjaro

### ISSUE THREAD

**Issue by somarlyonks** [Microsoft/vscode#53422]
```bash
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | linux | x64
gyp info spawn /usr/bin/python2.7
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/yaourt-tmp-sy/aur-code/src/vscode/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sy/.node-gyp/iojs-1.7.12/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/sy/.node-gyp/iojs-1.7.12',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/sy/.node-gyp/iojs-1.7.12/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/yaourt-tmp-sy/aur-code/src/vscode/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Call to 'pkg-config x11 xkbfile --libs' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.52-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/yaourt-tmp-sy/aur-code/src/vscode/node_modules/native-keymap
```

Built with `yaourt -S code`.

`node v8.11.3`, `node-gyp v3.7.0`.

**Comment by joaomoreno** [comment]
Do you have `pkg-config` installed?

**Comment by somarlyonks** [comment]
@joaomoreno Yes.

I figured it out and built it successfully.

The complains seemed to be caused by `proxychains`.
