### ISSUE TITLE
Can't build locally anymore

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#53445]
I get the following exception when building locally using `npm run gulp vscode-win32-x64`. Reason is that for some Search features a tag 1.25.0 is expected but we upgraded already to insider 1.26 and 1.25 isn't tag yet. We should at least not fail the build completely in this case.

```
[15:22:05] Error: Failed to find git tag for base version, 1.25.0
    at getLatestTagFromBase (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\lib\util.js:234:19)
    at Object.getPreviousVersion (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\lib\util.js:254:16)
    at getSettingsSearchBuildId (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\gulpfile.vscode.js:492:24)
    at Gulp.<anonymous> (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\gulpfile.vscode.js:268:33)
    at module.exports (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:214:10)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\lib\runTask.js:21:8)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\lib\runTask.js:52:4
```

**Comment by joaomoreno** [comment]
@roblourens We've also hit this when building forks for VS Code on branches other than master. Can you make this a little bit more fault tolerant?

**Comment by joaomoreno** [comment]
I had to push this in order to get a build running: https://github.com/Microsoft/vscode/commit/87668839f3f2941c6b5f6e097171bd643c697e3d

**Comment by roblourens** [comment]
It should break the build for real builds that we will release. But it can be skipped for others. How can I tell the difference?

**Comment by roblourens** [comment]
I could change it to count from the release branch, instead of the tag.

**Comment by roblourens** [comment]
Actually I'll just check for `process.env.BUILD_SOURCEBRANCH` like I already do for the upload step.

**Comment by roblourens** [comment]
Oh, I see that this is really about the gap between incrementing the package.json and tagging, not local builds.

**Comment by roblourens** [comment]
I have a better fix which simplifies this whole process, but makes the generated build id longer. First I need to test it with my Bing counterpart to make sure it's handled ok on their end.

**Comment by joaomoreno** [comment]
Mac builds are failing now: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=40052&view=logs
