### ISSUE TITLE
Focus search results list

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#53696]
When I am paging through the search results list, and after I have moved focus to the editor, I would like to be able to move focus back to the search result list, so I can continue to page through the results using my arrow keys.

Using "focus into side bar" will focus the input. Perhaps it should instead return focus to the last element within the side bar to have focus.

I am aware of the "focus next/previous search result" commands, however this doesn't focus the list per se, it just *selects* the search result to show it in the editor. This is not a replacement for paging the list using the arrow keys, e.g. without focusing the list, it's not possible to replace all in file.

Perhaps a separate command could be provided to give focus to the currently selected search result in the list, e.g.

- "Search: Focus currently selected result in list"
- "Search: Focus list" (and implicitly return focus to the currently selected result)

![image](https://user-images.githubusercontent.com/921609/42376040-9ce2a316-8115-11e8-96be-102527588b84.png)

**Comment by roblourens** [comment]
A `"Search: Focus list"` command sounds like a good idea, I would take a PR.

**Comment by stoiandan** [comment]
I'd like to help. How can I find the file that contains the "focus into side bar" command?

**Comment by stoiandan** [comment]
I've wrote the command, but I can't run `yarn`, sorry for this, I'm new to the tool.
I get the flowing output when I runt `yarn run watch `

```
[dan@dan-laptop vscode]$ yarn run watch
yarn run v1.7.0
$ gulp watch --max_old_space_size=4095
[21:15:55] Node flags detected: --max_old_space_size=4095
[21:15:55] Respawned to PID: 3583
[21:15:58] Using gulpfile ~/git/vscode/gulpfile.js
[21:15:58] Starting 'clean-client'...
[21:15:58] Starting 'clean-extension:configuration-editing'...
[21:15:58] Starting 'clean-extension:css-language-features-client'...
[21:15:58] Starting 'clean-extension:css-language-features-server'...
[21:15:58] Starting 'clean-extension:emmet'...
[21:15:58] Starting 'clean-extension:extension-editing'...
[21:15:58] Starting 'clean-extension:git'...
[21:15:58] Starting 'clean-extension:grunt'...
[21:15:58] Starting 'clean-extension:gulp'...
[21:15:58] Starting 'clean-extension:html-language-features-client'...
[21:15:58] Starting 'clean-extension:html-language-features-server'...
[21:15:58] Starting 'clean-extension:jake'...
[21:15:58] Starting 'clean-extension:json-language-features-client'...
[21:15:58] Starting 'clean-extension:json-language-features-server'...
[21:15:58] Starting 'clean-extension:markdown-language-features-preview-src'...
[21:15:58] Starting 'clean-extension:markdown-language-features'...
[21:15:58] Starting 'clean-extension:merge-conflict'...
[21:15:58] Starting 'clean-extension:npm'...
[21:15:58] Starting 'clean-extension:php-language-features'...
[21:15:58] Starting 'clean-extension:python'...
[21:15:58] Starting 'clean-extension:search-rg'...
[21:15:58] Starting 'clean-extension:typescript-basics-test-colorize-fixtures'...
[21:15:58] Starting 'clean-extension:typescript-language-features'...
[21:15:58] Starting 'clean-extension:vscode-api-tests'...
[21:15:58] Starting 'clean-extension:vscode-colorize-tests'...
[21:15:58] Finished 'clean-extension:css-language-features-client' after 3.58 ms
[21:15:58] Starting 'watch-extension:css-language-features-client'...
[21:15:58] Starting compilation...
[21:15:58] Finished 'clean-extension:grunt' after 29 ms
[21:15:58] Starting 'watch-extension:grunt'...
[21:15:58] Finished 'clean-extension:gulp' after 32 ms
[21:15:58] Starting 'watch-extension:gulp'...
[21:15:58] Finished 'clean-extension:jake' after 35 ms
[21:15:58] Starting 'watch-extension:jake'...
[21:15:58] Finished 'clean-extension:json-language-features-client' after 42 ms
[21:15:58] Starting 'watch-extension:json-language-features-client'...
[21:15:58] Finished 'clean-extension:markdown-language-features-preview-src' after 45 ms
[21:15:58] Starting 'watch-extension:markdown-language-features-preview-src'...
[21:15:58] Finished 'clean-extension:markdown-language-features' after 47 ms
[21:15:58] Starting 'watch-extension:markdown-language-features'...
[21:15:58] Finished 'clean-extension:npm' after 48 ms
[21:15:58] Starting 'watch-extension:npm'...
[21:15:58] Finished 'clean-extension:php-language-features' after 50 ms
[21:15:58] Starting 'watch-extension:php-language-features'...
[21:15:58] Finished 'clean-extension:python' after 52 ms
[21:15:58] Starting 'watch-extension:python'...
[21:15:58] Finished 'clean-extension:search-rg' after 54 ms
[21:15:58] Starting 'watch-extension:search-rg'...
[21:15:58] Finished 'clean-extension:typescript-basics-test-colorize-fixtures' after 58 ms
[21:15:58] Starting 'watch-extension:typescript-basics-test-colorize-fixtures'...
[21:15:58] Finished 'clean-extension:typescript-language-features' after 60 ms
[21:15:58] Starting 'watch-extension:typescript-language-features'...
[21:15:58] Finished 'clean-extension:vscode-api-tests' after 62 ms
[21:15:58] Starting 'watch-extension:vscode-api-tests'...
[21:15:58] Finished 'clean-extension:configuration-editing' after 67 ms
[21:15:58] Starting 'watch-extension:configuration-editing'...
[21:15:58] Finished 'clean-extension:css-language-features-server' after 78 ms
[21:15:58] Starting 'watch-extension:css-language-features-server'...
[21:15:58] Finished 'clean-extension:extension-editing' after 80 ms
[21:15:58] Starting 'watch-extension:extension-editing'...
[21:15:58] Finished 'clean-extension:emmet' after 83 ms
[21:15:58] Starting 'watch-extension:emmet'...
[21:15:58] Finished 'clean-extension:git' after 85 ms
[21:15:58] Starting 'watch-extension:git'...
[21:15:58] Finished 'clean-extension:html-language-features-server' after 87 ms
[21:15:58] Starting 'watch-extension:html-language-features-server'...
[21:15:58] Finished 'clean-extension:html-language-features-client' after 89 ms
[21:15:58] Starting 'watch-extension:html-language-features-client'...
[21:15:58] Finished 'clean-extension:json-language-features-server' after 94 ms
[21:15:58] Starting 'watch-extension:json-language-features-server'...
[21:15:58] Finished 'clean-extension:merge-conflict' after 102 ms
[21:15:58] Starting 'watch-extension:merge-conflict'...
[21:15:58] Finished 'clean-extension:vscode-colorize-tests' after 109 ms
[21:15:58] Starting 'watch-extension:vscode-colorize-tests'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/dan/git/vscode/extensions/html-language-features/server/src ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/dan/git/vscode/build/lib/watch/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/dan/git/vscode/build/lib/watch/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/dan/git/vscode/build/lib/watch/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/dan/git/vscode/build/lib/watch/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/dan/git/vscode/build/lib/watch/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/dan/git/vscode/build/lib/watch/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yogeshmangaj** [comment]
@roblourens I attempted to address this issue. Registered a `Search: Focus List` command.

(this is my first attempted open source contribution ever, I am aware that @stoiandan has already committed to solving this and is working on it, but I wanted to give it a try)

**Comment by stoiandan** [comment]
No, I've solved it by running `sudo sysctl -p`, it's a known Linux problem. Well, if @yogeshmangaj  solved it, I guess I'll look at another issue.
