### ISSUE TITLE
Building 1.25.0 on macOS 10.11

### ISSUE THREAD

**Issue by daiyam** [Microsoft/vscode#53858]
- VSCode Version: *release* 1.25.0
- OS Version: macOS 10.11.6
- Node Version: v8.9.2 (version defined in `.nvmrc`)
- Yarn Version: v1.7.0

Steps to Reproduce:

1. `yarn install`

Error:
```
yarn install v1.7.0
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/2] ⠠ fsevents
error /Users/baptiste/Development/Projects/VSCode/vscode-1.25.0/build/lib/watch/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/baptiste/Development/Projects/VSCode/vscode-1.25.0/build/lib/watch/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.2 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/baptiste/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/baptiste/Development/Projects/VSCode/vscode-1.25.0/build/lib/watch/node_modules/nsfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/baptiste/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/baptiste/.node-gyp/8.9.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/baptiste/.node-gyp/8.9.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/baptiste/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/baptiste/.node-gyp/8.9.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/baptiste/Development/Projects/VSCode/vscode-1.25.0/build/lib/watch/node_modules/nsfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/openpa/openpa/src/opa_primitives.o
  CC(target) Release/obj.target/openpa/openpa/src/opa_queue.o
  LIBTOOL-STATIC Release/openpa.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/openpa.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/baptiste/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/baptiste/.nvm/versions/node/v8.9.2/bin/node" "/Users/baptiste/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/baptiste/Development/Projects/VSCode/vscode-1.25.0/build/lib/watch/node_modules/nsfw
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

error Command failed with exit code 1.
```

**Comment by daiyam** [comment]
@joaomoreno I've tested on a clean macOS and I've got no errors...
So since the error is related to python, on my machine, I removed `brew` python versions and set the default python as `system` (via `pyenv`).
Then, everything is fine :)
