### ISSUE TITLE
Omnisharp failing to load

### ISSUE THREAD

**Issue by worthingtonjg** [Microsoft/vscode#53917]
Starting OmniSharp server at 7/9/2018, 7:56:47 PM
    Target: p:\Files\code\SightWordGames\SightWordGames.sln

OmniSharp server started
    Path: C:\Users\plex-server\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe
    PID: 17364

System.BadImageFormatException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 800700c1  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at OmniSharp.MSBuild.Discovery.Interop.GetSetupConfiguration() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\Interop.cs:line 20
   at OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider.GetInstances() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\Providers\VisualStudioInstanceProvider.cs:line 28
   at OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\MSBuildLocator.cs:line 145
   at OmniSharp.CompositionHostBuilder.RegisterMSBuildInstance(IMSBuildLocator msbuildLocator, ILogger logger) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\CompositionHostBuilder.cs:line 91
   at OmniSharp.CompositionHostBuilder.Build() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\CompositionHostBuilder.cs:line 61
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IConfiguration configuration, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in C:\projects\omnisharp-roslyn\src\OmniSharp.Stdio\Host.cs:line 54
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in C:\projects\omnisharp-roslyn\src\OmniSharp.Stdio.Driver\Program.cs:line 62
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OmniSharp.HostHelpers.Start(Func`1 action) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\HostHelpers.cs:line 54

**Comment by weinand** [comment]
Please file this issue against OmniSharp extension.
