### ISSUE TITLE
WARNING: Promise with no error callback:undefined

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#53955]
I don't know if this is a bug in my extension/tests or in VS Code, but I see the following when running my tests from the command line:

```


  extension

    ✓ resolves the correct debug config for a nested project





  2 passing (32ms)



WARNING: Promise with no error callback:undefined

Error: Promise did not implement oncancel
    at n.Class.derive._oncancel._cancelAction (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:90:565)
    at Object.enter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:441)
    at n.Class.derive._oncancel._run (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._oncancel.cancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:904)
    at Object.enter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:272)
    at n.Class.derive._creator._run (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._creator.cancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:904)
    at n.Class.derive._creator._cancelAction (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:88:967)
    at Object.enter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:441)
    at n.Class.derive._creator._run (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._creator.cancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:904)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:157:704
    at Object.dispose (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:33:849)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:157:1013
    at Array.forEach (native)
    at e.dispose (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:157:973)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:160:611
    at e.fire (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:103:764)
    at WebContents.r (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:109:201)
    at emitOne (events.js:101:20)
    at WebContents.emit (events.js:191:7)
```

I'm not sure whether there's enough info there to investigate, or if I can get more information; but it seems very reproducible so lmk if there is anything I should try to get more info.

**Comment by DanTup** [comment]
There's a similar error/stack in https://github.com/Microsoft/vscode/issues/44740 but the bottom of the stack is different and there was a fix committed, so maybe unrelated.

**Comment by jrieken** [comment]
@DanTup Any clues and what your are doing at that point? What apis/commands is you test using?

**Comment by DanTup** [comment]
In this instance, it was a really small test suite of only two tests:

https://github.com/Dart-Code/Dart-Code/blob/baa6e256454e4b3fcdd4b06f877c7eebfdcb51b5/test/multi_project_folder/extension.test.ts

However it does call `resolveDebugConfiguration` so it is hitting [a fair bit of my code](https://github.com/Dart-Code/Dart-Code/blob/baa6e256454e4b3fcdd4b06f877c7eebfdcb51b5/src/providers/debug_config_provider.ts#L42-L144).

I didn't dig too much as I was in the middle of something; but I'll have a quick go on some older code and see whether it seems to have started with any of my recent changes (if so, maybe I can bisect it).

**Comment by DanTup** [comment]
Hmmm, well annoyingly I can't reproduce this even with my `master` branch which is basically what I was using yesterday :(

If I see it again I'll try and do some more digging. Let me know if I there's anything specific I can do to get more info when I do have a repro. Feel free to close this in the meantime if you don't think it's actionable.

**Comment by jrieken** [comment]
Ok. Keep us posted - we are currently trying to reduce our winjs.promise-dependencies and we are trying to gradually phase it out during the next 2-3 months. Then, this shouldn't exist anymore
