### ISSUE TITLE
CSS Language Server server crashed (Portable Mode)

### ISSUE THREAD

**Issue by zmni** [Microsoft/vscode#54167]
- VSCode Version: 1.25 Portable Mode
- OS Version: Windows 8.1

Steps to Reproduce:

1. Start fresh.
2. Open css file (attached below).

Does this issue occur when all extensions are disabled?: Yes

Output:
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../data/browsers'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at e:\VSCode\resources\app\extensions\css-language-features\server\node_modules\vscode-css-languageservice\lib\umd\services\languageFacts.js:17:20
    at Object.defineProperty.value (e:\VSCode\resources\app\extensions\css-language-features\server\node_modules\vscode-css-languageservice\lib\umd\services\languageFacts.js:3:17)
    at Object.<anonymous> (e:\VSCode\resources\app\extensions\css-language-features\server\node_modules\vscode-css-languageservice\lib\umd\services\languageFacts.js:9:3)
    at Object.<anonymous> (e:\VSCode\resources\app\extensions\css-language-features\server\node_modules\vscode-css-languageservice\lib\umd\services\languageFacts.js:837:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
[Info  - 18:43:12] Connection to server got closed. Server will restart.
```

Attach css files causing the problem: [userChrome.zip](https://github.com/Microsoft/vscode/files/2188474/userChrome.zip) (extract this in to your firefox profile).

**Comment by aeschli** [comment]
Can you check if your installation has a file
` e:\VSCode\resources\app\extensions\css-language-features\server\node_modules\vscode-css-languageservice\lib\umd\data\browsers.js`
If not, this looks like a corrupted installation.
