### ISSUE TITLE
"TypeError: e.onCancellationRequested is not a function" calling hover provider in Insiders

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#54174]
In Insiders, all of my Hover Provider tests are failing like this:

```
1) dart_hover_provider
       does not return hovers for blank areas of the document:
     TypeError: e.onCancellationRequested is not a function
      at Object.t.wireCancellationToken (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:193:579)
      at Object.provideHover (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3819:10)
      at file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1614:26
      at Array.map (native)
      at a (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1613:983)
      at file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1520:441
      at file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1518:178
      at e.invokeFunction (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1369:836)
      at t._tryExecuteCommand (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2945:960)
      at file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2945:676
      at n.Class.define.cancel.then (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:158:366)
      at t.executeCommand (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2945:650)
      at e.$executeCommand (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3099:842)
      at e._doInvokeHandler (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3158:983)
      at e._invokeHandler (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3158:701)
      at e._receiveRequest (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3157:767)
      at e._receiveOneMessage (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3157:536)
      at file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3156:424
      at file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3159:575
      at e.fire (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:496)
      at c (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:306:526)
      at Socket.<anonymous> (file://.vscode-test/insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:306:703)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at Pipe.onread (net.js:560:20)
```

I stripped the test back to this:

```ts
it.only("does not return hovers for blank areas of the document", async () => {
	await vs.commands.executeCommand("vscode.executeHoverProvider", doc.uri, doc.positionAt(0));
});
```

And my implementation back to this:

```ts
public provideHover(document: TextDocument, position: Position, token: CancellationToken): Thenable<Hover> {
	return Promise.resolve(null);
}
```

And the issue still occurs; so I don't think it's my fault. As far as I can tell, this isn't happening for normal editor hovers though; it may be specific to calling that command, or being within tests.

**Comment by daytonellwanger** [comment]
I've noticed the same.

`await vscode.commands.executeCommand<vscode.Hover[]>('vscode.executeHoverProvider', uri, position);` throws with this stack:
```
TypeError: e.onCancellationRequested is not a function
    at Object.t.wireCancellationToken (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:193:579)
    at Object.provideHover (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3793:636)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1606:26
    at Array.map (native)
    at a (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1605:983)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1512:441
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1510:178
    at e.invokeFunction (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1361:808)
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2922:960)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2922:676
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at t.executeCommand (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2922:650)
    at e.$executeCommand (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3076:842)
    at e._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3135:356)
    at e._invokeHandler (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3135:74)
    at e._receiveRequest (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3134:164)
    at e._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3133:940)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3132:863
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3135:942
    at e.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:172:496)
    at c (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:306:259)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:306:436)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
