### ISSUE TITLE
VS Code - Github Desktop error WITH .exe in PATH!

### ISSUE THREAD

**Issue by SeaDude** [Microsoft/vscode#54410]
Please search existing issues to avoid creating duplicates.

**- I did and verified that GithubDesktop.exe is in my PATH var**

Also please test using the latest insiders build to make sure your issue has not already been fixed: 
- Updated today to latest ver

- VSCode Version: **1.25.1**
- OS Version: **Windows 10 Pro 10.0.16299 Build 16299**

**Steps to Reproduce:**

1. Create new repo on Github.com
2. Do NOT init with README.md
3. Click "Setup in Desktop"
4. Directory is cloned to C:/Users/me/Desktop/git/newRepo
5. Open newRepo in VS Code
6. Create README.md
7. CTRL + S to save new file
8. Enter a commit message in VS Code
9. Click CTRL + ENTER or the "check" icon
10. Message: 
11. Click Elipses then Show Git Output: ERROR
```
Looking for git in: C:\Users\me\AppData\Local\GitHubDesktop\GitHubDesktop.exe
Using git v8.2.1 from C:\Users\me\AppData\Local\GitHubDesktop\GitHubDesktop.exe
> git rev-parse --show-toplevel
module.js:487
    throw err;
    ^

Error: Cannot find module 'c:\Users\me\Desktop\git\newRepo\rev-parse'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git config --get commit.template
Open repository: \.
> git status -z -u
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
module.js:487
    throw err;
    ^

Error: Cannot find module 'c:\Users\me\Desktop\git\newRepo\rev-parse'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\config'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git symbolic-ref --short HEAD
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\symbolic-ref'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git rev-parse HEAD
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\rev-parse'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\remote'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\for-each-ref'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git init
module.js:487
    throw err;
    ^

Error: Cannot find module 'c:\Users\me\Desktop\git\newRepo\init'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git rev-parse --show-toplevel
module.js:487
    throw err;
    ^

Error: Cannot find module 'c:\Users\me\Desktop\git\newRepo\rev-parse'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git rev-parse --show-toplevel
module.js:487
    throw err;
    ^

Error: Cannot find module 'c:\Users\me\Desktop\git\newRepo\rev-parse'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
> git rev-parse --show-toplevel
module.js:487
    throw err;
    ^

Error: Cannot find module 'c:\Users\me\Desktop\git\newRepo\rev-parse'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3

```

Environment Variables: 
Whats strange here is that Github Desktop is listed in a "Path" var (note lower case here which is weird)
![image](https://user-images.githubusercontent.com/8636973/42778279-72945634-88f1-11e8-866e-0dc9076a310c.png)

When I double click the "Path" var under "User variables for me", THEN I see BOTH Github Desktop and VS Code:
![image](https://user-images.githubusercontent.com/8636973/42778404-cfb06862-88f1-11e8-9727-de8c01fc07aa.png)

Whats going on here?

**Comment by zhuowei** [comment]
@SeaDude It looks like VS Code is trying to execute GitHub Desktop's GUI instead of the command line Git client included in GitHub Desktop.

Did you set a custom `"git.path"` in your user settings? If you did, try removing the setting and running again.

Also, it appears that VS Code [doesn't support](https://github.com/Microsoft/vscode/issues/40335#issuecomment-352345146) using the copy of Git from GitHub Desktop. Try installing Git for Windows and using its copy of Git instead.

**Comment by SeaDude** [comment]
Thanks for the response. I did not set a custom git.path. I will try installing Git for Windows to see if that works.
