### ISSUE TITLE
Breadcrumbs with new settings editor results in empty window after restart

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#54451]
If I close the VS Code window while the new settings editor is open, after restarting VS Code, the window is empty:
![code - insiders_2018-07-17_09-24-47](https://user-images.githubusercontent.com/304384/42802451-53e6b1ca-89a3-11e8-93f4-a77a32cf4649.png)
After disabling the breadcrumbs, everything works fine.

Developer Toolbar shows the following errors:
```
  ERR Cannot read property 'scheme' of null: TypeError: Cannot read property 'scheme' of null
    at e.update (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4240:311)
    at t.updateBreadcrumbsControl (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4324:841)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4326:986)
    at t.doShowEditor (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4887:998)
    at t.restoreEditors (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4881:795)
    at new t (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4874:924)
    at t.create (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:111:430)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1374:325)
    at e.createInstance (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1373:600)
    at Function.t.createFromSerialized (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4875:130)
    at r.doCreateGroupView (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4907:432)
    at Object.fromJSON (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4913:897)
    at Function.t.deserializeNode (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:487:885)
    at Function.t.deserializeNode (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:487:781)
    at Function.t.deserialize (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:488:476)
    at r.doCreateGridControlWithState (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4913:823)
    at r.doCreateGridControlWithPreviousState (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4913:621)
    at r.doCreateGridControl (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4913:135)
    at r.createContentArea (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4912:606)
    at r.t.create (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2440:455)
    at t.createEditorPart (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5367:31)
    at t.renderWorkbench (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5365:576)
    at t.startup (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5346:380)
    at t.createWorkbench (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5400:782)
    at t.renderContents (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5400:205)
    at t.open (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5408:363)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5416:28
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:151:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:155:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:156:932)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:156:373)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
and

```
TypeError: Cannot read property 'scheme' of null
    at e.update (breadcrumbsControl.ts:199)
    at t.updateBreadcrumbsControl (tabsTitleControl.ts:141)
    at t.openEditor (tabsTitleControl.ts:262)
    at t.doShowEditor (editorGroupView.ts:790)
    at t.restoreEditors (editorGroupView.ts:418)
    at new t (editorGroupView.ts:145)
    at t.create (types.ts:166)
    at e._createInstance (instantiationService.ts:120)
    at e.createInstance (instantiationService.ts:73)
    at Function.t.createFromSerialized (editorGroupView.ts:59)
    at r.doCreateGroupView (editorPart.ts:497)
    at Object.fromJSON (editorPart.ts:862)
    at Function.t.deserializeNode (grid.ts:435)
    at Function.t.deserializeNode (grid.ts:428)
    at Function.t.deserialize (grid.ts:464)
    at r.doCreateGridControlWithState (editorPart.ts:856)
    at r.doCreateGridControlWithPreviousState (editorPart.ts:838)
    at r.doCreateGridControl (editorPart.ts:811)
    at r.createContentArea (editorPart.ts:789)
    at r.t.create (part.ts:53)
    at t.createEditorPart (workbench.ts:1065)
    at t.renderWorkbench (workbench.ts:989)
    at t.startup (workbench.ts:286)
    at t.createWorkbench (shell.ts:189)
    at t.renderContents (shell.ts:166)
    at t.open (shell.ts:459)
    at main.ts:103
    at Object.g [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1089)
    at n.Class.derive._oncancel._completed (winjs.base.js:1057)
    at runCallback (timers.js:672)
    at tryOnImmediate (timers.js:645)
    at processImmediate [as _immediateCallback] (timers.js:617)
```

- VSCode Version: 1.26.0-insider, b48367a8652bd0aa862638bbc24555a70823d3bd
- OS Version: Win10

**Comment by jrieken** [comment]
fixed via
