### ISSUE TITLE
Annoying error in insiders build and current stable build

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#54466]
Debugger listening on ws://127.0.0.1:26494/b8e43402-3513-47cd-9490-9d1eddb4dc8c
Debugger attached.
******** Unhandled error in debug adapter - Unhandled promise rejection: SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at SourceMap.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:73:29)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71
    at Promise (<anonymous>)
    at __awaiter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:6:12)
    at SourceMap.init (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:71:16)
    at Function.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:62:22)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71
******** Unhandled error in debug adapter - Unhandled promise rejection: SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at SourceMap.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:73:29)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71
    at Promise (<anonymous>)
    at __awaiter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:6:12)
    at SourceMap.init (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:71:16)
    at Function.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:62:22)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71
******** Unhandled error in debug adapter - Unhandled promise rejection: SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at SourceMap.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:73:29)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71
    at Promise (<anonymous>)
    at __awaiter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:6:12)
    at SourceMap.init (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:71:16)
    at Function.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:62:22)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71
******** Unhandled error in debug adapter - Unhandled promise rejection: SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at SourceMap.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:73:29)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71
    at Promise (<anonymous>)
    at __awaiter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:6:12)
    at SourceMap.init (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:71:16)
    at Function.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:62:22)
    at Generator.next (<anonymous>)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:10:71

**Comment by jpike88** [comment]
In sourceMap.js:

```
static create(generatedPath, json, pathMapping, sourceMapPathOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const sm = new SourceMap();
            yield sm.init(generatedPath, json, pathMapping, sourceMapPathOverrides);
            return sm;
        });
    }
```
Is pathMapping supposed to be undefined?

**Comment by jpike88** [comment]
More investigating... no idea what's going on here

![screen shot 2018-07-17 at 6 44 06 pm](https://user-images.githubusercontent.com/9585787/42815383-6bf4d2a8-89f1-11e8-988c-e97985563fc7.png)
