### ISSUE TITLE
Smoketests complain about original-fs

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54550]
Maybe since https://github.com/Microsoft/vscode/commit/4e975a1bebd8e346a511339c8d177d8bf35a945a

```
$ yarn smoketest
yarn run v1.7.0
$ cd test/smoke && node test/index.js


*** Test data: /tmp/t24666wvi0InXZSe2a
*** Preparing smoketest setup...
*** Creating workspace file...
*** Cloning test project repository...
*** Running yarn...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

*** Smoketest setup done!

  Test
Loading "original-fs" failed
Detail:  { Error: Cannot find module 'original-fs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NodeScriptLoader.load (/home/joao/Work/vscode/out/vs/loader.js:732:39)
    at OnlyOnceScriptLoader.load (/home/joao/Work/vscode/out/vs/loader.js:578:32)
    at loadNextPath (/home/joao/Work/vscode/out/vs/loader.js:1431:41)
    at Object.errorback (/home/joao/Work/vscode/out/vs/loader.js:1439:25)
    at OnlyOnceScriptLoader.triggerErrorback (/home/joao/Work/vscode/out/vs/loader.js:591:36)
    at /home/joao/Work/vscode/out/vs/loader.js:578:151 code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'original-fs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NodeScriptLoader.load (/home/joao/Work/vscode/out/vs/loader.js:732:39)
    at OnlyOnceScriptLoader.load (/home/joao/Work/vscode/out/vs/loader.js:578:32)
    at loadNextPath (/home/joao/Work/vscode/out/vs/loader.js:1431:41)
    at Object.errorback (/home/joao/Work/vscode/out/vs/loader.js:1439:25)
    at OnlyOnceScriptLoader.triggerErrorback (/home/joao/Work/vscode/out/vs/loader.js:591:36)
    at /home/joao/Work/vscode/out/vs/loader.js:578:151
Here are the modules that depend on it:
[ 'fs' ]
```

**Comment by bpasero** [comment]
Adding @alexandrudima since I am about to leave. This is probably a regression from https://github.com/Microsoft/vscode/commit/4e975a1bebd8e346a511339c8d177d8bf35a945a

**Comment by bpasero** [comment]
@alexandrudima thanks!
