### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by omarzion** [Microsoft/vscode#54750]
- VSCode Version: 1.25.1  commit 1dfc5e557209371715f655691b1235b6b26a06be
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Launch vs code after update to 1.25.1
1. Launch vs code with --disable-gpu --disable extensions (or any variation thereof)

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/11347689/43014430-bdfd8d2a-8c11-11e8-83d5-43aaa23461c6.png)

trying to open integrated terminal
![image](https://user-images.githubusercontent.com/11347689/43014454-d08b2bf0-8c11-11e8-8827-dfb7ab6433d5.png)

after closing terminal

![image](https://user-images.githubusercontent.com/11347689/43014614-5d59b826-8c12-11e8-86bc-76f7e6e888e2.png)

**Comment by Tyriar** [comment]
Some follow ups:

- How did you install VS Code?
- Can you try `code --verbose` and paste in the output
- Can you try `code --user-data-dir ./tmp` and see if that fixes the issue?

**Comment by omarzion** [comment]
I installed by following this https://code.visualstudio.com/docs/setup/linux
`code --user-data-dir ./tmp` produces same result, I also moved ~/.config/Code to ~/.config/Code.old earlier to no avail as well

```
code --verbose
[12890:0720/134631.844446:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.844681:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[12890:0720/134631.844724:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.844812:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.844847:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[12890:0720/134631.844886:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.844979:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845027:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845076:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845128:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845184:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845242:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845301:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845414:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845470:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845514:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845559:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845638:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845689:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845772:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845816:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845854:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845892:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845925:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.845993:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.846023:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.846066:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.846507:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.846861:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.846902:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.846936:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.846989:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[12890:0720/134631.847035:ERROR:browser_main_loop.cc(257)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[main 1:46:32 PM] Starting VS Code
[main 1:46:32 PM] from: /usr/share/code/resources/app
[main 1:46:32 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 1:46:32 PM] Resolving machine identifier...
[main 1:46:32 PM] Resolved machine identifier: 719263aba3b5c1f2af3b2c7b93394935f501a93bc9d26f2cefd4068acd63835a
[main 1:46:32 PM] update#setState idle
[12890:0720/134632.735503:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 1:46:32 PM] windowsService#whenSharedProcessReady
[12890:0720/134632.761958:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134632.773074:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 1:46:32 PM] windowsService#getRecentlyOpened 1
[main 1:46:32 PM] windowsService#setRepresentedFilename 1
[12890:0720/134632.851410:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134632.851989:INFO:CONSOLE(1375)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 1:46:33 PM] windowsService#getRecentlyOpened 1
[main 1:46:33 PM] windowsService#startCrashReporter
[12890:0720/134633.296779:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134633.296798:INFO:CONSOLE(1375)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134633.296885:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134633.296907:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134633.297074:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134633.335632:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 1:46:33 PM] windowsService#setRepresentedFilename 1
[12890:0720/134633.470057:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 1:46:33 PM] windowsService#getWindowCount
[main 1:46:33 PM] IPC#vscode-workbenchLoaded
[12890:0720/134633.511000:INFO:CONSOLE(1375)] "%c INFO", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134633.542676:INFO:CONSOLE(3148)] "Overwriting extension /usr/share/code/resources/app/extensions/ms-vscode.node-debug2 with /home/asparks/.vscode/extensions/ms-vscode.node-debug2-1.26.4.", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (3148)
[12890:0720/134633.718792:INFO:CONSOLE(270)] "%c[IPC Library: Watcher] %cStart watching: /home/asparks/git/blog-api]", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[main 1:46:33 PM] windowsService#isFocused 1
[12890:0720/134634.778246:INFO:CONSOLE(270)] "%c[Extension Host] %cLooking for parseable SCSS %c(at /home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/extension.js:36:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134634.866091:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134634.868008:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134634.896879:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.017250:INFO:CONSOLE(1375)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.017277:INFO:CONSOLE(1375)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.038539:INFO:CONSOLE(1375)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.040304:INFO:CONSOLE(1375)] "%cDEBUG", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.150880:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.163734:INFO:CONSOLE(1376)] "%c  ERR", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1376)
[12890:0720/134635.187007:INFO:CONSOLE(270)] "%c[IPC Library: Watcher] %c[ADDED]", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134635.204444:INFO:CONSOLE(270)] "%c[Extension Host] %cFound all parseable SCSS files %c(at /home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/extension.js:48:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134635.204594:INFO:CONSOLE(270)] "%c[Extension Host] %cParsing documents and looking for SCSS Elements... %c(at /home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/extension.js:54:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134635.239086:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.241184:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.374401:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.374456:INFO:CONSOLE(270)] "%c[IPC Library: Watcher] %c >> normalized", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134635.374486:INFO:CONSOLE(270)] "%c[IPC Library: Watcher] %c[DELETED]", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134635.378360:INFO:CONSOLE(270)] "%c[IPC Library: Watcher] %c >> normalized", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134635.404943:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.405005:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.405044:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.405063:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.405073:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.405087:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.405096:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134635.986050:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134636.477367:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134637.854146:INFO:CONSOLE(270)] "%c[Extension Host] %cError:param type is not arguments %c(at Object.params [as default] (/home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/parse-engines/typehandler/arguments.js:7:17))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134637.854176:INFO:CONSOLE(270)] "%c[Extension Host] %cError:param type is not arguments %c(at Object.params [as default] (/home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/parse-engines/typehandler/arguments.js:7:17))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134637.854487:INFO:CONSOLE(270)] "%c[Extension Host] %cError:param type is not arguments %c(at Object.params [as default] (/home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/parse-engines/typehandler/arguments.js:7:17))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134637.855765:INFO:CONSOLE(270)] "%c[Extension Host] %cError:param type is not arguments %c(at Object.params [as default] (/home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/parse-engines/typehandler/arguments.js:7:17))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134637.862223:INFO:CONSOLE(270)] "%c[Extension Host] %cError:param type is not arguments %c(at Object.params [as default] (/home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/parse-engines/typehandler/arguments.js:7:17))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.165010:INFO:CONSOLE(270)] "%c[Extension Host] %c"live-sass-compiler" is now actived! Go and Debug :P  %c(at activate (/home/asparks/.vscode/extensions/ritwickdey.live-sass-3.0.0/out/src/extension.js:7:13))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.205756:INFO:CONSOLE(270)] "%c[Extension Host] %cSumary: %c(at /home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/extension.js:76:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.205798:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206019:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206036:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206050:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206056:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206121:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206185:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206322:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.206379:INFO:CONSOLE(270)] "%c[Extension Host] %c/home/asparks/git/blog-api/admin/admin/src/styles/libs/bootstrap/mixins/_clearfix.scss
/home/asparks/git/blog-api/admin/admin/src/styles/libs/bootstrap/mixins/_text-truncate.scss
/home/asparks/git/blog-api/admin/admin/src/styles/libs/bootstrap/mixins/_text-hide.scss
/home/asparks/git/blog-api/admin/admin/src/styles/libs/bootstrap/mixins/_forms.scss
/home/asparks/git/blog-api/admin/admin/src/styles/libs/bootstrap/mixins/_grid.scss
/home/asparks/git/blog-api/plugins/content-manager/node_modules/strapi-plugin-content-manager/admin/src/styles/variables/variables.bootstrap.scss
/home/asparks/git/blog-api/plugins/content-manager/admin/src/styles/variables/variables.bootstrap.scss
 %c(at /home/asparks/.vscode/extensions/aaronphy.scss-scan-0.1.67/out/src/extension.js:85:21)", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[12890:0720/134638.228616:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134638.276510:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134638.286327:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134638.306507:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134638.441095:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[12890:0720/134642.808158:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 1:47:02 PM] update#checkForUpdates, state =  idle
[main 1:47:02 PM] update#setState checking for updates
[main 1:47:02 PM] RequestService#request https://vscode-update.azurewebsites.net/api/update/linux-x64/stable/1dfc5e557209371715f655691b1235b6b26a06be
[main 1:47:02 PM] update#setState idle
```

**Comment by omarzion** [comment]
Resolved GTK errors by installing `gtk2-engines-pixbuf` and 'gnome-themes-standard'
ran 'code --verbose --disable-extensions --disable-gpu' again

```
code --verbose --disable-extensions --disable-gpu
[main 2:03:26 PM] Starting VS Code
[main 2:03:26 PM] from: /usr/share/code/resources/app
[main 2:03:26 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  'disable-gpu': true }
[main 2:03:26 PM] Resolving machine identifier...
[main 2:03:26 PM] Resolved machine identifier: 719263aba3b5c1f2af3b2c7b93394935f501a93bc9d26f2cefd4068acd63835a
[main 2:03:26 PM] update#setState idle
[15679:0720/140326.996662:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[15679:0720/140327.013291:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[15679:0720/140327.028017:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[15679:0720/140327.084750:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 2:03:27 PM] IPC#vscode-workbenchLoaded
[main 2:03:27 PM] windowsService#whenSharedProcessReady
[main 2:03:27 PM] windowsService#getRecentlyOpened 1
[main 2:03:27 PM] windowsService#getRecentlyOpened 1
[main 2:03:27 PM] windowsService#setRepresentedFilename 1
[main 2:03:27 PM] windowsService#getRecentlyOpened 1
[main 2:03:27 PM] windowsService#setRepresentedFilename 1
[main 2:03:27 PM] windowsService#getWindowCount
[main 2:03:27 PM] windowsService#startCrashReporter
[15679:0720/140327.253379:INFO:CONSOLE(1375)] "%c INFO", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 2:03:27 PM] windowsService#isFocused 1
[15679:0720/140327.652068:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[15679:0720/140330.002479:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[15679:0720/140330.091268:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 2:03:56 PM] update#checkForUpdates, state =  idle
[main 2:03:56 PM] update#setState checking for updates
[main 2:03:56 PM] RequestService#request https://vscode-update.azurewebsites.net/api/update/linux-x64/stable/1dfc5e557209371715f655691b1235b6b26a06be
[main 2:03:56 PM] update#setState idle
```

**Comment by omarzion** [comment]
Dev tools isn't rendering correctly either oddly enough 
![image](https://user-images.githubusercontent.com/11347689/43021212-69ff2654-8c28-11e8-94c8-fa92354a246f.png)

**Comment by Tyriar** [comment]
@omarzion it looks like this is an electron/chromium issue, have you tried to see if this repros in another electron app or Chrome?

**Comment by omarzion** [comment]
@Tyriar yes, I use Chrome, and after running into this issue I re-downloaded Atom to continue working, also postman, google music desktop player all work fine.  That is why I thought it was odd.
It started working again this morning, could it be from updating chrome last night?
```
Unpacking google-chrome-stable (68.0.3440.75-1) over (67.0.3396.99-1) 
```

**Comment by Tyriar** [comment]
@omarzion well if you're on Insiders we updated to Electron 2 which jumps from Chromium 58 to 61?

**Comment by omarzion** [comment]
No, I believe I am on stable... I have no idea why it didn't work for days then honestly..
here is the about

```
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```

**Comment by omarzion** [comment]
After some further thought, it was choking on auto restoring the last opened project.. opening a specific folder from the terminal was what fixed it..  so maybe the problem lies within a project level config on auto restore?  Unfortunately I can't share the the project..  I'll see if I can recreate the auto restore issue when I have some time..  I have a feeling it's going to be an odd edge case though

**Comment by Tyriar** [comment]
Let me know if you run into it again.
