### ISSUE TITLE
Debugging an extension should forcably enable it (at least for that session)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#54764]
Issue Type: <b>Bug</b>

This is mainly user error, but I lost so much time because of it, it would be great if there was a solution.

Scenario:
1. Install *Extension A* from a vsix
1. Disable *Extension A* from the Extensions panel and close vscode
1. Open the code for *Extension A* in vscode
1. Debug *Extension A*
1. :bug: vscode will open an extension host window to debug the extension, but since the extension is disabled it will never load. And since there is no visible indication of this, it looks like debugging is broken

It would be great if there was a warning, or better yet, just re-enable the extension for the debugging session.

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:18:39.569Z)
OS version: Windows_NT x64 10.0.17713

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.74GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Eric\code\codestream\vscode-codestream\codestream.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment]
@eamodio It works well for me on latest insiders. 

- I installed an extension using vsix
- Opened the same extension source in VS Code 
- Disabled the extension
- Ran the extension 

And I see the extension is active and can be debugged

**Comment by eamodio** [comment]
This is still 100% reproducible for me in both stable and insiders. Also verified that it doesn't have anything to do with vsix.

1. Have GitLens installed and enabled
1. Open vscode to the vscode-gitlens repo
1. Switch to extensions and disabled GitLens
1. Reload vscode
1. Start debugging (F5)
1. The extension host window that opens will not start GitLens

**Comment by sandy081** [comment]
@eamodio I could not try your extension as I was getting errors while building. I tried with another extension and it works.


![kapture 2018-08-22 at 18 52 19](https://user-images.githubusercontent.com/10746682/44478004-9867fb00-a63c-11e8-9bc9-eb0050422187.gif)

Here are the errors I see when I run gitlens extensions

<details>
Executing task: npm run build <


> gitlens@8.2.1 build /Users/sandy081/work/vscode-extensions/vscode-gitlens
> npm run lint && tsc -m commonjs -p ./ && npm run build-ui -- --env.quick


> gitlens@8.2.1 lint /Users/sandy081/work/vscode-extensions/vscode-gitlens
> tslint --project tslint.json


> gitlens@8.2.1 build-ui /Users/sandy081/work/vscode-extensions/vscode-gitlens
> webpack --context ./src/ui --config ./src/ui/webpack.config.js "--env.quick"

Hash: fcf496d8aea37a461fdc
Version: webpack 4.5.0
Time: 4624ms
Built at: 8/22/2018 6:53:26 PM
              Asset      Size    Chunks             Chunk Names
        settings.js  71.2 KiB  settings  [emitted]  settings
         welcome.js  70.6 KiB   welcome  [emitted]  welcome
../../settings.html  80.9 KiB            [emitted]
 ../../welcome.html  27.8 KiB            [emitted]
Entrypoint settings = settings.js
Entrypoint welcome = welcome.js
[./node_modules/css-loader/index.js??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./scss/main.scss] ./node_modules/css-loader??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./scss/main.scss 4 KiB [built] [failed] [1 error]
[./scss/main.scss] 6.9 KiB [built] [failed] [1 error]
   [0] multi ./settings/index.ts ./scss/main.scss 40 bytes {settings} [built]
   [1] multi ./welcome/index.ts ./scss/main.scss 40 bytes {welcome} [built]
[./settings/app.ts] 646 bytes {settings} [built]
[./settings/index.ts] 70 bytes {settings} [built]
[./shared/app-base.ts] 10.3 KiB {welcome} {settings} [built]
[./shared/colors.ts] 3.33 KiB {welcome} {settings} [built]
[./shared/dom.ts] 439 bytes {welcome} {settings} [built]
[./welcome/app.ts] 453 bytes {welcome} [built]
[./welcome/index.ts] 68 bytes {welcome} [built]
    + 2 hidden modules

ERROR in ./scss/main.scss (./node_modules/css-loader??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./scss/main.scss)
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3
    at module.exports (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:225:3)
    at NormalModule.build (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:343:15)
    at Compilation.buildModule (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:361:10)
    at factory.create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:587:15)
    at factory (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at resolver (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:126:29)
    at process.nextTick (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./scss/main.scss 2:14-136

ERROR in ./scss/main.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3
    at module.exports (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:225:3)
    at NormalModule.build (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:343:15)
    at Compilation.buildModule (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:361:10)
    at moduleFactory.create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:717:12)
    at factory (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/tapable/lib/Hook.js:35:21)
    at resolver (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:126:29)
    at process.nextTick (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at runLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:242:20)
    at /Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:225:3)
    at NormalModule.build (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:343:15)
    at Compilation.buildModule (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:361:10)
    at moduleFactory.create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:717:12)
    at factory (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/tapable/lib/Hook.js:35:21)
    at resolver (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:126:29)
    at process.nextTick (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./scss/main.scss
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!scss/main.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./scss/main.scss] ./node_modules/css-loader??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./scss/main.scss 4.17 KiB {0} [built] [failed] [1error]

    ERROR in ./scss/main.scss (./node_modules/css-loader??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./scss/main.scss)
    Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v4.8.3
        at module.exports (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/node-sass/lib/index.js:14:35)
        at Module._compile (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/Users/sandy081/work/vscode-extensions/vscode-gitlens/src/ui/node_modules/sass-loader/lib/loader.js:3:14)
        at Module._compile (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:13:17)
        at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:173:18
        at loadLoader (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/loadLoader.js:36:3)
        at iteratePitchingLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
        at NormalModule.doBuild (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:225:3)
        at NormalModule.build (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModule.js:343:15)
        at Compilation.buildModule (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:361:10)
        at moduleFactory.create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/Compilation.js:717:12)
        at factory (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:366:6)
        at hooks.afterResolve.callAsync (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:143:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/tapable/lib/Hook.js:35:21)
        at resolver (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:126:29)
        at process.nextTick (/Users/sandy081/work/vscode-extensions/vscode-gitlens/node_modules/webpack/lib/NormalModuleFactory.js:304:9)
        at process._tickCallback (internal/process/next_tick.js:61:11)
Child html-webpack-plugin for "../../settings.html":
     1 asset
    Entrypoint undefined = ../../settings.html
    [../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./settings/index.html] 82 KiB {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "../../welcome.html":
     1 asset
    Entrypoint undefined = ../../welcome.html
    [../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./welcome/index.html] 28.3 KiB {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gitlens@8.2.1 build-ui: `webpack --context ./src/ui --config ./src/ui/webpack.config.js "--env.quick"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gitlens@8.2.1 build-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sandy081/.npm/_logs/2018-08-22T16_53_26_681Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gitlens@8.2.1 build: `npm run lint && tsc -m commonjs -p ./ && npm run build-ui -- --env.quick`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gitlens@8.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sandy081/.npm/_logs/2018-08-22T16_53_26_717Z-debug.log
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.
</details>

**Comment by eamodio** [comment]
@sandy081 from those errors it looks like `node-sass` isn't compatible with your OS version 😢 

Although I've just tried again from the latest insiders and it seems to be working now.
