### ISSUE TITLE
VSCode Insiders crashes on open with TypeError: Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by LarsVonQualen** [Microsoft/vscode#54933]
- VSCode Version: 26e5a55cd8452477bfb7a472ea9475761600adf0 x64
- OS Version: WIndows 7 Enterprise

Steps to Reproduce:

1. From command line run `code-insiders --verbose`
2. Watch it open for an instance, then close down immediately after the following has been logged to console:
```
code-insiders --verbose

[main 1:54:55 PM] Starting VS Code
[main 1:54:55 PM] from: c:\Program Files\Microsoft VS Code Insiders\resources\app
[main 1:54:55 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 1:54:55 PM] Resolving machine identifier...
[main 1:54:55 PM] Resolved machine identifier: d48a40325366f0a29516342691e38369721a3ddba7fd28a6e2921687728644a3
[main 1:54:55 PM] update#setState idle
[main 1:54:55 PM] TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.o [as basename] (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:46:538)
    at Object.t.getWorkspaceLabel (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:335:280)
    at e.createOpenRecentMenuItem (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:367:142)
    at e.setOpenRecentMenu (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:366:326)
    at e.setFileMenu (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:362:923)
    at e.install (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:358:524)
    at new e (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:355:177)
    at t.create (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:52:365)
    at e._createInstance (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:207:703)
    at e.createInstance (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:206:959)
    at t.afterWindowOpen (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:522:583)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:517:699
    at e.invokeFunction (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:206:638)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:517:663
    at n.Class.define.cancel.then (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:90:201)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:517:523
    at n.Class.define.cancel.then (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:90:201)
    at t.startup (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:516:912)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:528:539
    at Object.v [as _notify] (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:83:572)
    at Object.enter (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:86:924)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:88:790)
    at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:88:231)
    at Server.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:169:657)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[main 1:54:55 PM] Lifecycle#kill()
[main 1:54:55 PM] Lifecycle#window-closed 1
[main 1:54:55 PM] Lifecycle#onShutdown.fire()
[main 1:54:55 PM] telemetry/optInStatus { optIn: true }
[main 1:54:55 PM] telemetry/update:win32SetupTarget { target: 'system' }
```

Does this issue occur when all extensions are disabled?: Yes, but i can't disable any because the entire app is crashing.

**Comment by kieferrm** [comment]
@LarsVonQualen it seems that `code` tries to open workspace whose configuration file you previously saved but that it now can't find. What should get you out of this is to explicitly open VS Code on a particular folder: `code-insiders .` for example.

**Comment by kieferrm** [comment]
Culprit is https://github.com/Microsoft/vscode/blob/5c82fedfed58e186c179606643010e6b299abfbe/src/vs/platform/workspaces/common/workspaces.ts#L134

**Comment by bstoney** [comment]
For anyone else who encounters this issue, I was able to start vscode by deleting everything except the `User` folder from `%APPDATA%\Code - Insiders`. Using `code-insiders .` didn't work.

**Comment by bpasero** [comment]
Easier repro:
* have a user-data-folder that contains data from 1.26 (or master)
* check out release/1.25
* run it

You get this right on startup:

```
[main 11:07:16] TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.basename (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/paths.js:43:24)
    at Object.getWorkspaceLabel (/Users/bpasero/Desktop/vscode-125/out/vs/platform/workspaces/common/workspaces.js:41:32)
    at CodeMenu.createOpenRecentMenuItem (/Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/menus.js:427:38)
    at CodeMenu.setOpenRecentMenu (/Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/menus.js:401:48)
    at CodeMenu.setFileMenu (/Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/menus.js:326:18)
    at CodeMenu.install (/Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/menus.js:189:18)
    at new CodeMenu (/Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/menus.js:40:18)
    at create (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (/Users/bpasero/Desktop/vscode-125/out/vs/platform/instantiation/common/instantiationService.js:106:35)
    at InstantiationService.createInstance (/Users/bpasero/Desktop/vscode-125/out/vs/platform/instantiation/common/instantiationService.js:67:29)
    at CodeApplication.afterWindowOpen (/Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/app.js:431:38)
    at /Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/app.js:262:95
    at InstantiationService.invokeFunction (/Users/bpasero/Desktop/vscode-125/out/vs/platform/instantiation/common/instantiationService.js:48:34)
    at /Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/app.js:262:45
    at CompletePromise_ctor.CompletePromise_then [as then] (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/winjs.base.js:1581:49)
    at /Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/app.js:255:32
    at CompletePromise_ctor.CompletePromise_then [as then] (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/winjs.base.js:1581:49)
    at CodeApplication.startup (/Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/app.js:240:44)
    at /Users/bpasero/Desktop/vscode-125/out/vs/code/electron-main/main.js:300:111
    at Object.notifySuccess [as _notify] (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (/Users/bpasero/Desktop/vscode-125/out/vs/base/common/winjs.base.js:1051:18)
    at Server.<anonymous> (/Users/bpasero/Desktop/vscode-125/out/vs/base/parts/ipc/node/ipc.net.js:203:17)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Assigning to a couple of folks who may be in charge.

**Comment by aeschli** [comment]
in 1.26-insiders we modified the data format of the list of recently opened workspaces.
1.25 code doesn't make any validity check on the data format.

The fix is to use a new `workspaces2` property in `storage.json` instead of modifying the existing one.

**Comment by sandy081** [comment]
@aeschli Thanks for the fix. 

I assume this fix is to support forward compatibility (older versions (< 1.26) of VS Code to run on new user data dir).

**Comment by monkeysuffrage** [comment]
deleting storage.json got me going again
