### ISSUE TITLE
Exception when saving file editor opened from remote file provider

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55051]
Testing #54863
- install [Remotehub extension](https://marketplace.visualstudio.com/items?itemName=eamodio.remotehub)
- open  `code-insiders --folder-uri remotehub://github.com/Microsoft/vscode-nls`
- open and modify a file, save

```
ERR Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at file:///home/aeschli/workspaces/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:608:116
    at Object.notifyError [as _notify] (file:///home/aeschli/workspaces/vscode/out/vs/base/common/winjs.base.js:1230:50)
    at Object.enter (file:///home/aeschli/workspaces/vscode/out/vs/base/common/winjs.base.js:916:30)
    at _Base.Class.derive._creator._run (file:///home/aeschli/workspaces/vscode/out/vs/base/common/winjs.base.js:1089:29)
    at _Base.Class.derive._creator._error (file:///home/aeschli/workspaces/vscode/out/vs/base/common/winjs.base.js:1062:18)
    at error (file:///home/aeschli/workspaces/vscode/out/vs/base/common/winjs.base.js:758:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by aeschli** [comment]
The exception in the exception handling prevents VSCode from being closed. I pushed a temporary fix.

**Comment by bpasero** [comment]
The fix is not good, because now when an error occurs during save that is not one of the well defined errors (which can always happen), we do not do proper error handling but simply return too early.

**Comment by bpasero** [comment]
@aeschli please code review and verify

**Comment by aeschli** [comment]
Verified as well
