### ISSUE TITLE
Caused system crashed when drag mouse to change window size

### ISSUE THREAD

**Issue by QiWang19** [Microsoft/vscode#55063]
Issue Type: <b>Bug</b>

I used VScode in frdora28, and find it always leads system crashing when I drag  the mouse to change the VScode window size

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.6-200.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2617)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.48GB (4.11GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.2
flow-for-vscode|flo|0.8.2
auto-close-tag|for|0.5.6
Go|ms-|0.6.84
remote-vscode|raf|1.1.0
JavaScriptSnippets|xab|1.7.0

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@Tyriar known electron issue?

**Comment by Tyriar** [comment]
@kieferrm I haven't seen this before, looks like it's on stable as well (Electron 1.7.12)

@QiWang19 can you close all windows and launch VS Code using `code --verbose` and try to reproduce? This should give some logs in the terminal you launched from.

**Comment by QiWang19** [comment]
below is all the log after code --verbose

[main 3:49:59 PM] Starting VS Code
[main 3:49:59 PM] from: /usr/share/code/resources/app
[main 3:49:59 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 3:49:59 PM] Resolving machine identifier...
[main 3:49:59 PM] Resolved machine identifier: 517982b30ae7e654779283d5a55b5a0fa0c4e7b604597bb56a72abc45bab839d
[main 3:49:59 PM] update#setState idle
[6272:0726/155000.066683:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[6272:0726/155000.078628:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[6272:0726/155000.095270:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[6272:0726/155000.181118:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 3:50:00 PM] IPC#vscode-workbenchLoaded
[main 3:50:00 PM] windowsService#whenSharedProcessReady
[main 3:50:00 PM] windowsService#getRecentlyOpened 1
[main 3:50:00 PM] windowsService#getWindowCount
[main 3:50:00 PM] windowsService#startCrashReporter
[main 3:50:00 PM] windowsService#getRecentlyOpened 1
[main 3:50:00 PM] windowsService#setRepresentedFilename 1
[6272:0726/155000.437429:INFO:CONSOLE(1375)] "%c INFO", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[6272:0726/155000.570786:INFO:CONSOLE(3148)] "[xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (3148)
[main 3:50:00 PM] windowsService#isFocused 1
[6272:0726/155001.047694:INFO:CONSOLE(270)] "%c[Extension Host] %c[2018-07-26 15:50:01.043] [TRACE] extension - initialize %c(at Logger.<anonymous> (/home/qiwan/.vscode/extensions/rafaelmaiolla.remote-vscode-1.1.0/node_modules/log4js/lib/appenders/console.js:8:5))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[6272:0726/155001.047966:INFO:CONSOLE(270)] "%c[Extension Host] %c[2018-07-26 15:50:01.047] [TRACE] extension - getConfiguration %c(at Logger.<anonymous> (/home/qiwan/.vscode/extensions/rafaelmaiolla.remote-vscode-1.1.0/node_modules/log4js/lib/appenders/console.js:8:5))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[6272:0726/155001.050309:INFO:CONSOLE(270)] "%c[Extension Host] %c[2018-07-26 15:50:01.047] [DEBUG] extension - getConfiguration { onStartup: false,
  dontShowPortAlreadyInUseError: false,
  port: 52698,
  host: '127.0.0.1' } %c(at Logger.<anonymous> (/home/qiwan/.vscode/extensions/rafaelmaiolla.remote-vscode-1.1.0/node_modules/log4js/lib/appenders/console.js:8:5))", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (270)
[6272:0726/155001.062930:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[6272:0726/155001.094639:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[6272:0726/155002.791823:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[6272:0726/155003.189479:INFO:CONSOLE(1375)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 3:50:29 PM] update#checkForUpdates, state =  idle
[main 3:50:29 PM] update#setState checking for updates
[main 3:50:29 PM] RequestService#request https://vscode-update.azurewebsites.net/api/update/linux-x64/stable/1dfc5e557209371715f655691b1235b6b26a06be
[main 3:50:29 PM] update#setState idle

**Comment by Tyriar** [comment]
@QiWang19 does this happen on the Insiders build? https://code.visualstudio.com/insiders/

**Comment by QiWang19** [comment]
@Tyriar I used it in Fedora28 Linux

**Comment by Tyriar** [comment]
@QiWang19 you used 1.25.1 in the original report, did you try see if it happens also in 1.26.0-insiders?
