### ISSUE TITLE
Error: Promise did not implement oncancel

### ISSUE THREAD

**Issue by alexlamsl** [Microsoft/vscode#55136]
Issue Type: <b>Bug</b>

- open VSCode via Command Prompt
- observe the following stacktrace

```
[main 7:20:31 PM] update#setState idle
WARNING: Promise with no error callback:undefined
Error: Promise did not implement oncancel
    at n.Class.derive._oncancel._cancelAction (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:90:565)
    at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:86:441)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:88:719)
    at n.Class.derive._oncancel.cancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:87:904)
    at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:86:272)
    at n.Class.derive._creator._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:88:719)
    at n.Class.derive._creator.cancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:87:904)
    at n.Class.derive._creator._cancelAction (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:88:967)
    at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:86:441)
    at n.Class.derive._creator._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:88:719)
    at n.Class.derive._creator.cancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:87:904)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:157:704
    at Object.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:33:849)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:157:1013
    at Array.forEach (native)
    at e.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:157:973)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:160:611
    at e.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:103:764)
    at WebContents.r (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:109:201)
    at emitOne (events.js:101:20)
    at WebContents.emit (events.js:191:7)
```

It is an intermittent issue, i.e. not reproducible every time.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.14393

Extensions: none

**Comment by alexlamsl** [comment]
Sometimes I get this instead:
```
[main 7:28:28 PM] update#setState idle
You should really not try to cancel this ready promise!
```

**Comment by kieferrm** [comment]
@alexlamsl what you see is leaking from #53526. As we go through all of our code, you won't see those anymore.
