### ISSUE TITLE
VS Code can not open / start Ubuntu18.04 lts

### ISSUE THREAD

**Issue by babiloneos** [Microsoft/vscode#55173]
- VSCode Version: 1.25.1
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1.Open VSCode in the application menu (when I do it through the terminal it does not happen anymore).
2.It shows the application in the top bar for a few seconds and then disappears.

Does this issue occur when all extensions are disabled?: Yes

My VSCode is newly installed

When tried to run in terminal code --verbose i got all this:

`[13403:0726/125749.198009:ERROR:nss_util.cc(94)] Failed to create /home/usuario_gbl/.pki/nssdb directory.
[13405:0726/125749.223922:ERROR:nss_util.cc(94)] Failed to create /home/usuario_gbl/.pki/nssdb directory.
Gtk-Message: 12:57:49.242: Failed to load module "canberra-gtk-module"
[13435:0726/125749.499049:ERROR:nss_util.cc(94)] Failed to create /home/usuario_gbl/.pki/nssdb directory.
[main 12:57:49] { Error: EACCES: permission denied, open '/home/usuario_gbl/.config/Code/storage.json'
    at Object.fs.openSync (original-fs.js:584:18)
    at Object.fs.readFileSync (original-fs.js:491:33)
    at e.loadSync (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:274:880)
    at e.ensureLoaded (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:274:339)
    at e.getItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:274:391)
    at e.getItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:275:314)
    at e.handleRestarted (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:290:575)
    at new e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:290:472)
    at t.create (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:52:365)
    at e._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:204:458)
    at e._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:205:403)
    at e._getOrCreateServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:204:595)
    at Object.get (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:203:274)
    at $ (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:522:452)
    at e.invokeFunction (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:203:400)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:523:584
    at n.Class.derive._creator.done (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:89:254)
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:84:343)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:87:418)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._oncancel._error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:236)
    at u (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:91:761)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:91:893
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:84:170)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:87:418)
    at n.Class.derive._creator._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._creator._chainedError (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:78)
    at n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:85:929)
    at n.Class.define.cancel.then (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:89:504)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:86:3)
    at n.Class.derive._creator._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._creator._setCompleteValue (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:413)
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:84:152)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:87:418)
    at n.Class.derive._creator._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._creator._chainedError (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:78)
    at n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:85:929)
    at n.Class.define.cancel.then (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:89:504)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:86:3)
    at n.Class.derive._creator._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._creator._setCompleteValue (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:413)
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:84:152)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:87:418)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:719)
    at n.Class.derive._oncancel._error (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:88:236)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:119:290
    at FSReqWrap.oncomplete (fs.js:114:15)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/usuario_gbl/.config/Code/storage.json' }
[main 12:57:49] Startup error: Error: EACCES: permission denied, mkdir '/home/usuario_gbl/.config/Code/User',,Error: EACCES: permission denied, mkdir '/home/usuario_gbl/.config/Code/CachedData/1dfc5e557209371715f655691b1235b6b26a06be',Error: EACCES: permission denied, mkdir '/home/usuario_gbl/.config/Code/logs/20180726T125749'
[main 12:57:49] Lifecycle#kill()
`

But i don't know how to solve it, because i'm new on ubuntu.

**Comment by babiloneos** [comment]
Solved it

**Comment by babiloneos** [comment]
the solution is this:

`sudo apt-get install --reinstall overlay-scrollbar-gtk2`
`sudo apt install libcanberra-gtk-module libcanberra-gtk3-module`

And whit the next comand, change the permission for every path that is in the Error as a root
`chown -v "user" "path"`

this is my result:

`usuario_gbl@UbuntuSO:~$ code --verbose
[main 19:08:35] Sending env to running instance...
[main 19:08:35] Sent env to running instance. Terminating...
[main 19:08:35] Lifecycle#kill()
`
