### ISSUE TITLE
code-insiders crashes after install user distribution

### ISSUE THREAD

**Issue by Aleph06** [Microsoft/vscode#55170]
- VSCode Version: 1.26.0-insider
7e992cab07f6d3faf5a137e8ca0d094f8dffeee6
x64
- OS Version: Win 7 x64
- Installed using: VSCodeUserSetup-x64-1.26.0-insider.exe

Steps to Reproduce:

1. Run "code-insiders .": app starts then closes immediatly
2. Run "code-insiders . --verbose": shows error:
[main 11:50:55] Resolving machine identifier...
[main 11:50:55] Resolved machine identifier: b1b20d254f199fd3be024bd44ed4ebf3c46a42acbsd682815b63ab597922087b9
[main 11:50:55] update#setState idle
[main 11:50:56] TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.o [as basename] (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:46:538)
    at Object.t.getWorkspaceLabel (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:334:880)
    at %UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:404:415
    at Array.map (native)
    at e.updateWindowsJumpList (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:404:315)
    at t.afterWindowOpen (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:521:189)
    at %UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:516:275
    at e.invokeFunction (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:205:920)
    at %UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:516:239
    at n.Class.define.cancel.then (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:90:201)
    at %UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:516:99
    at n.Class.define.cancel.then (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:90:201)
    at t.startup (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:515:488)
    at %UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:527:131
    at Object.v [as _notify] (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:83:572)
    at Object.enter (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:86:924)
    at n.Class.derive._oncancel._run (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:88:790)
    at n.Class.derive._oncancel._completed (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:88:231)
    at Server.<anonymous> (%UserProfile%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:168:908)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[main 11:50:56] Lifecycle#kill()

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@Aleph06  it seems that code tries to open workspace whose configuration file you previously saved but that it now can't find. What should get you out of this is to explicitly open VS Code on a particular folder: `code-insiders .` for example.
