### ISSUE TITLE
`code-insiders --prof-startup` failes with exception

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55675]
Elementary Loki (Ubuntu 16.04)

Version: 1.26.0-insider
Commit: c86cab2
Date: 2018-08-02T05:18:18.450Z

- start `code-insiders --prof-startup`
- dialog opens ' Successfully created profiles', click on 'Creas Issues and Restart'
- nothing happens. Dev tools show
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4820:889
    at Object.g [as _notify] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._oncancel._run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._oncancel._completed (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at e.doRequest.n.TPromise.t.handlers.(anonymous function) (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3
```
After a while the console from with code-insiders was started show:
```
[ [ { Error: connect ECONNREFUSED 127.0.0.1:9223
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
```

In the debugger I see that the home folder `/user/aeschli` is searched for files with a given prefix, but no file or folder has been created there.

**Comment by aeschli** [comment]
Now I suddenly get profile files. The dialog shows the file names and an issue can be created.

**Comment by jrieken** [comment]
Hm, maybe it connected to the wrong instance? When running with --prof-startup it should take a little while before starting and showing a window. I will tweak this to try with less predictive/busy ports...

**Comment by jrieken** [comment]
I have improved this and made things more stable. Now, when running with `--prof-startup` when it's not the only window an error is printed, tho a little delayed
