### ISSUE TITLE
PythonTools Intellisense stack trace "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by ijstokes** [Microsoft/vscode#55815]
Issue Type: <b>Bug</b>

Intellisense with PythonTools is regularly (every couple of minutes) triggering a stack trace which pops up in the OUTPUT terminal tab.  See example below.

```
[Error - 07:34:56] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ClassDefinition node)
   at Microsoft.PythonTools.Parsing.Ast.ClassDefinition.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.WalkBody(Node node, AnalysisUnit unit)
   at Microsoft.PythonTools.Analysis.ClassAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.Worker(Object threadStarted)
[Error - 08:01:11] Request textDocument/completion failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
[object Object]
```

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.93GB free)|
|Process Argv|/Users/ijstokes/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
node-module-intellisense|jhe|1.6.0
restructuredtext|lex|65.0.0
python|ms-|2018.7.1
vim|vsc|0.15.7

</details>

**Comment by ijstokes** [comment]
This seems to be quite repeatable now.  I have an ABC called `JSONifyInterface` which has an abstract classmethod `fromjson(self, obj)`.  When I go to implement the classmethod on a concrete class Foo I get the exception above as soon as I type `@class` in front of my method definition.

The ABC part *may* all be a red-herring.  Maybe it is just intellisense borking on the `class` reserved word when I haven't quite yet finished typing `classmethod` and the `@` decorator unary prefix operator.  IOW: Intellisense may be getting mixed up when I type `@class` on my way to punching out `@classmethod`.

Maybe this screenshot will help:

![image](https://user-images.githubusercontent.com/293525/43676512-f7206568-97c0-11e8-866f-c8d28d2d101b.png)
