### ISSUE TITLE
Smoketest: Debug test fails often

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#56069]
The `focus stack frames and variables` test is failing very often.

https://vscode.visualstudio.com/VSCode/_build/results?buildId=4943&_a=summary&view=logs

```
2018-08-09T09:20:14.4269620Z [0m  1) Test
2018-08-09T09:20:14.4286390Z        Debug
2018-08-09T09:20:14.4301540Z          focus stack frames and variables:
2018-08-09T09:20:14.4319910Z [0m[31m     Error: Timeout: click 'div[id="workbench.view.debug"] .monaco-tree-row .stack-frame .file[title$="layer.js"]' after 20 seconds.[0m[90m
2018-08-09T09:20:14.4337190Z       at /Users/vsts/agent/2.136.1/work/1/s/test/smoke/out/vscode/code.js:142:23
2018-08-09T09:20:14.4353700Z       at Generator.next (<anonymous>)
2018-08-09T09:20:14.4368840Z       at fulfilled (out/vscode/code.js:8:58)
2018-08-09T09:20:14.4384070Z       at <anonymous>
```

**Comment by isidorn** [comment]
The issue was that we were matching on the end of the title element for the stack frame name.
However the end was in some cases "readonly content from node", thus I changed the selector to match a substring on the whole title, instead only looking at the end.
fyi @roblourens
