### ISSUE TITLE
Cannot build on windows: Unhandled stream error in pipe

### ISSUE THREAD

**Issue by GongT** [Microsoft/vscode#56146]
- VSCode Version: git master
- OS Version: Windows 10 x64

Error Step:
> npm run gulp -- vscode-win32-x64-min

Output:
```
[21:14:18] Using gulpfile X:\.release\maix-ide-release-x64\gulpfile.js
[21:14:18] Starting 'clean-minified-vscode'...
[21:14:18] Starting 'clean-optimized-vscode'...
[21:14:18] Starting 'clean-client-build'...
[21:14:18] Starting 'clean-extension:configuration-editing'...
[21:14:18] Starting 'clean-extension:css-language-features-client'...
[21:14:18] Starting 'clean-extension:css-language-features-server'...
[21:14:18] Starting 'clean-extension:debug-auto-launch'...
[21:14:18] Starting 'clean-extension:emmet'...
[21:14:18] Starting 'clean-extension:extension-editing'...
[21:14:18] Starting 'clean-extension:git'...
[21:14:18] Starting 'clean-extension:grunt'...
[21:14:18] Starting 'clean-extension:gulp'...
[21:14:18] Starting 'clean-extension:html-language-features-client'...
[21:14:18] Starting 'clean-extension:html-language-features-server'...
[21:14:18] Starting 'clean-extension:jake'...
[21:14:18] Starting 'clean-extension:json-language-features-client'...
[21:14:18] Starting 'clean-extension:json-language-features-server'...
[21:14:18] Starting 'clean-extension:markdown-language-features-preview-src'...
[21:14:18] Starting 'clean-extension:markdown-language-features'...
[21:14:18] Starting 'clean-extension:merge-conflict'...
[21:14:18] Starting 'clean-extension:npm'...
[21:14:18] Starting 'clean-extension:php-language-features'...
[21:14:18] Starting 'clean-extension:python'...
[21:14:18] Starting 'clean-extension:search-rg'...
[21:14:18] Starting 'clean-extension:typescript-basics-test-colorize-fixtures'...
[21:14:18] Starting 'clean-extension:typescript-language-features'...
[21:14:18] Starting 'clean-extension:vscode-api-tests'...
[21:14:18] Starting 'clean-extension:vscode-colorize-tests'...
[21:14:18] Starting 'clean-vscode-win32-x64'...
[21:14:18] Finished 'clean-minified-vscode' after 7.37 ms
[21:14:18] Finished 'clean-optimized-vscode' after 5.18 ms
[21:14:18] Finished 'clean-extension:markdown-language-features-preview-src' after 3.81                                                                                                        ms
[21:14:18] Starting 'compile-extension-build:markdown-language-features-preview-src'...
[21:14:18] Starting compilation...
[21:14:18] Finished 'clean-extension:typescript-basics-test-colorize-fixtures' after 23                                                                                                        ms
[21:14:18] Starting 'compile-extension-build:typescript-basics-test-colorize-fixtures'.                                                                                                       ..
[21:14:18] Finished 'clean-vscode-win32-x64' after 25 ms
[21:14:18] Finished 'clean-extension:css-language-features-server' after 30 ms
[21:14:18] Starting 'compile-extension-build:css-language-features-server'...
[21:14:18] Finished 'clean-extension:debug-auto-launch' after 32 ms
[21:14:18] Starting 'compile-extension-build:debug-auto-launch'...
[21:14:18] Finished 'clean-extension:emmet' after 33 ms
[21:14:18] Starting 'compile-extension-build:emmet'...
[21:14:18] Finished 'clean-extension:extension-editing' after 34 ms
[21:14:18] Starting 'compile-extension-build:extension-editing'...
[21:14:18] Finished 'clean-extension:html-language-features-client' after 35 ms
[21:14:18] Starting 'compile-extension-build:html-language-features-client'...
[21:14:18] Finished 'clean-extension:merge-conflict' after 40 ms
[21:14:18] Starting 'compile-extension-build:merge-conflict'...
[21:14:18] Finished 'clean-extension:search-rg' after 41 ms
[21:14:18] Starting 'compile-extension-build:search-rg'...
[21:14:18] Finished 'compile-extension-build:markdown-language-features-preview-src' af                                                                                                       ter 40 ms
[21:14:18] Finished 'compile-extension-build:typescript-basics-test-colorize-fixtures'                                                                                                        after 19 ms
[21:14:18] Finished 'clean-client-build' after 76 ms
[21:14:18] Starting 'compile-client-build'...
[21:14:18] Finished 'clean-extension:configuration-editing' after 82 ms
[21:14:18] Starting 'compile-extension-build:configuration-editing'...
[21:14:18] Finished 'clean-extension:css-language-features-client' after 84 ms
[21:14:18] Starting 'compile-extension-build:css-language-features-client'...
[21:14:18] Finished 'clean-extension:gulp' after 85 ms
[21:14:18] Starting 'compile-extension-build:gulp'...
[21:14:18] Finished 'clean-extension:git' after 87 ms
[21:14:18] Starting 'compile-extension-build:git'...
[21:14:18] Finished 'clean-extension:grunt' after 88 ms
[21:14:18] Starting 'compile-extension-build:grunt'...
[21:14:18] Finished 'clean-extension:html-language-features-server' after 89 ms
[21:14:18] Starting 'compile-extension-build:html-language-features-server'...
[21:14:18] Finished 'clean-extension:json-language-features-client' after 90 ms
[21:14:18] Starting 'compile-extension-build:json-language-features-client'...
[21:14:18] Finished 'clean-extension:jake' after 91 ms
[21:14:18] Starting 'compile-extension-build:jake'...
[21:14:18] Finished 'clean-extension:json-language-features-server' after 92 ms
[21:14:18] Starting 'compile-extension-build:json-language-features-server'...
[21:14:18] Finished 'clean-extension:npm' after 94 ms
[21:14:18] Starting 'compile-extension-build:npm'...
[21:14:18] Finished 'clean-extension:markdown-language-features' after 96 ms
[21:14:18] Starting 'compile-extension-build:markdown-language-features'...
[21:14:18] Finished 'clean-extension:php-language-features' after 98 ms
[21:14:18] Starting 'compile-extension-build:php-language-features'...
[21:14:18] Finished 'clean-extension:python' after 99 ms
[21:14:18] Starting 'compile-extension-build:python'...
[21:14:18] Finished 'clean-extension:typescript-language-features' after 100 ms
[21:14:18] Starting 'compile-extension-build:typescript-language-features'...
[21:14:18] Finished 'clean-extension:vscode-api-tests' after 101 ms
[21:14:18] Starting 'compile-extension-build:vscode-api-tests'...
[21:14:18] Finished 'clean-extension:vscode-colorize-tests' after 102 ms
[21:14:18] Starting 'compile-extension-build:vscode-colorize-tests'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: Found 3 errors
    at Stream.<anonymous> (X:\.release\maix-ide-release-x64\build\lib\reporter.js:80:31                                                                                                       )
    at _end (X:\.release\maix-ide-release-x64\node_modules\through\index.js:65:9)
    at Stream.stream.end (X:\.release\maix-ide-release-x64\node_modules\through\index.j                                                                                                       s:74:5)
    at StreamFilter.onend (X:\.release\maix-ide-release-x64\node_modules\readable-strea                                                                                                       m\lib\_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at StreamFilter.emit (events.js:208:7)
    at endReadableNT (X:\.release\maix-ide-release-x64\node_modules\readable-stream\lib                                                                                                       \_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I have tried many times. Error was same.

**Comment by GongT** [comment]
Oh
I found that I can successful build everytime I remove node_modules and reinstall it... (still break 2nd try)

**Comment by joaomoreno** [comment]
Let's try again:

```
git clean -xfd
yarn
gulp vscode-win32-x64-min
```

Works?

**Comment by GongT** [comment]
Yes, It works

**Comment by WilliamABradley** [comment]
@joaomoreno I manage to consistently get this every time, even after performing the commands.

**Comment by joaomoreno** [comment]
@WilliamABradley Please create a separate issue.

**Comment by WilliamABradley** [comment]
@joaomoreno #59219
