### ISSUE TITLE
Exception when liniting package.json

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#56170]
Version: 1.26.0-insider
Commit: a8033aaf216d684d775e058489d25186702d28e3
Date: 2018-08-07T23:17:55.610Z
Architecture: x64

- generate a TypeScript extension with `yo code`
- open the package.json file
```
[4780:0810/215004.399:INFO:CONSOLE(100)] "%c[Extension Host] %cTypeError: Cannot read property 'value' of undefined
        at ExtensionLinter.readPackageJsonInfo (c:\workspaces\vscode\extensions\extension-editing\out\extensionLinter.js:314:33)
        at c:\workspaces\vscode\extensions\extension-editing\out\extensionLinter.js:160:55
        at step (c:\workspaces\vscode\extensions\extension-editing\out\extensionLinter.js:36:23)
        at Object.f [as next] (c:\workspaces\vscode\extensions\extension-editing\out\extensionLinter.js:17:53)
        at step (c:\workspaces\vscode\extensions\extension-editing\out\extensionLinter.js:21:139)
        at Object.f [as next] (c:\workspaces\vscode\extensions\extension-editing\out\extensionLinter.js:17:53)
        at fulfilled (c:\workspaces\vscode\extensions\extension-editing\out\extensionLinter.js:8:58)
        at <anonymous> %c(at <anonymous>)", source: file:///C:/workspaces/vscode/out/vs/base/node/console.js (100)
```

**Comment by aeschli** [comment]
Caused by 839a40edb3d256986e44fbcbf6e46b5948bd9663 ('repo.value')

**Comment by chrmarti** [comment]
@aeschli That change is only in master. Are you seeing this in insiders?

**Comment by aeschli** [comment]
Master only

**Comment by chrmarti** [comment]
Thx.
