### ISSUE TITLE
Loaded scripts: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#56252]
Start vscode out of source `scripts/code.sh`

Have the following js file
`console.log('hello there');`

Start debugging it (you do not have to set a breakpoint). Notice the exception in the chrome dev tools console.
Note that I can not repro with vsocde insiders.

```
  ERR Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///Users/isidor/Development/vscode/out/vs/base/parts/tree/browser/treeView.js:592:35
    at file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:272:28
    at Object.notifySuccess [as _notify] (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1191:59)
    at Object.enter (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1089:29)
    at Promise_ctor._completed (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1057:18)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:277:23
errors.js:42 WARNING: Promise with no error callback:53
```

If you pause on exception you can see this is coming from the loaded scripts view line 326

![screen shot 2018-08-13 at 10 57 11](https://user-images.githubusercontent.com/1926584/44022360-a7f0fca4-9ee7-11e8-9abd-d881bc311ed9.png)

**Comment by isidorn** [comment]
This seems like the same stack trace as https://github.com/Microsoft/vscode/issues/57007
Not adding verified yet
