### ISSUE TITLE
Breakpoints List: Error: Can't run recursive splices.

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56443]
Steps to Reproduce:

1. click the "+" to add a function breakpoint in the view
2. click into the editor to add a breakpoint

```
Can't run recursive splices.: Error: Can't run recursive splices.
    at ListView.splice (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listView.js:76:23)
    at file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/splice.js:13:62
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/splice.js:13:30)
    at file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listWidget.js:824:83
    at EventBufferer.bufferEvents (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/common/event.js:417:13)
    at WorkbenchList.List.splice (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listWidget.js:824:32)
    at BreakpointsView.onBreakpointsChange (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/workbench/parts/debug/browser/breakpointsView.js:168:31)
    at file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/workbench/parts/debug/browser/breakpointsView.js:53:116
    at Emitter.fire (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/common/event.js:148:38)
    at Model.removeFunctionBreakpoints (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/workbench/parts/debug/common/debugModel.js:1117:42)
    at DebugService.removeFunctionBreakpoints (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/workbench/parts/debug/electron-browser/debugService.js:567:24)
    at wrapUp (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/workbench/parts/debug/browser/breakpointsView.js:427:44)
    at HTMLInputElement.<anonymous> (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/workbench/parts/debug/browser/breakpointsView.js:442:21)
    at removeFromParent (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/rowCache.js:10:35)
    at RowCache.releaseRow (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/rowCache.js:47:13)
    at RowCache.release (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/rowCache.js:42:18)
    at ListView.removeItemFromDOM (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listView.js:238:24)
    at ListView._splice (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listView.js:94:22)
    at ListView.splice (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listView.js:80:29)
    at file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/splice.js:13:62
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/splice.js:13:30)
    at file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listWidget.js:824:83
    at EventBufferer.bufferEvents (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/common/event.js:417:13)
    at WorkbenchList.List.splice (file:///Users/bpasero/Development/vscode-react-hackathon/out/vs/base/browser/ui/list/listWidget.js:824:32)
```

**Comment by isidorn** [comment]
I can not reproduce this.
I assume when you say "click into the editor" you mean into the input box.
Do you have any other breakpoints in the view? Can you reproduce this all the time?

I remeber this issue was happening when I change the breakpoints view to be a list but we did not see it since afaik @joaomoreno

**Comment by bpasero** [comment]
@isidorn sorry, when I say "click into the editor" I actually meant to say "add another breakpoint by clicking into a breakpoint in the editor"

**Comment by isidorn** [comment]
@bpasero thanks, I can repro now

**Comment by isidorn** [comment]
The issue here is that while the first splice is in progress the second splice comes on the list.
In this particular case this is expected behavior from the debug, however it seems that the list can not handle this.
@joaomoreno is there some way for me to figure out if a splice is in progress? Since it does not return a promise?

**Comment by joaomoreno** [comment]
> The issue here is that while the first splice is in progress the second splice comes on the list.

It should be possible to do what you want to do without calling splice in your renderer, which is what you seem to be doing.
