### ISSUE TITLE
VSCode won't launch on Windows if path contains # character

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/vscode#56506]
I've tried searching in existing issues but couldn't find one tracking this issue.

- VSCode Version:
1.27.0 Insider build as well as other versions

- OS Version:
Windows 10 Version 1709

Steps to Reproduce:

1. Download the VScode installer for windows and set the install path to a folder with # character in the name for example: C:\Program Files\Microsoft VS # Code
2. Try launching VS code from a cmd window.

Result:
VS code is not launching with the following error in the cmd window:

The factory method of "vs/base/node/paths" has thrown an exception
{ Error: Cannot find module 'c:\Program Files\Microsoft VS Code '
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (C:\Program Files\Microsoft VS Code # Insiders\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:30:770)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\code\electron-main\main.js:135:413)
    at Function.t._safeInvokeFunction (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:19:248)
    at Function.t._invokeFactory (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:19:495)
    at t.complete (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:19:732)
    at s._onModuleComplete (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:30:25)
    at s._resolve (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:29:599)
    at s.defineModule (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:23:862)
    at o (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\loader.js:31:180)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code # Insiders\resources\app\out\vs\code\electron-main\main.js:135:265)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This could be https://github.com/electron/electron/issues/10311 (even though that one talks about a leading "#").

**Comment by bpasero** [comment]
@alanrenmsft for some reason I cannot reproduce this issue. I installed VSCode Insiders to this folder: "C:\Program Files\Microsoft VS # Code Insiders" and it starts fine. I do not remember we pushed a fix for this but could you maybe try again with latest insiders?
