### ISSUE TITLE
No quickfix and no lightbulb

### ISSUE THREAD

**Issue by macbielecki** [Microsoft/vscode#56501]
After update to version 1.26 no lightbulb is present when eslint reports errors and no quick fix options are visible in the editor (also: no editor.action.quickFix option in Settings).

**Comment by ramya-rao-a** [comment]
Can you open the console (Help -> Toggle Developer Tools -> Console) and share the errors found there when you try to use the eslint features?

**Comment by kkolstad** [comment]
I am seeing the same behavior on Mac using `cmd+.` with typescript files.

<img width="369" alt="screen shot 2018-08-15 at 2 51 34 pm" src="https://user-images.githubusercontent.com/1631066/44175338-be205d80-a09a-11e8-8eb8-4e2357ea089d.png">


The console error is not very useful:
```
ERR An unknown error occurred. Please consult the log for more details.
```

**Comment by macbielecki** [comment]
Exactly. I also have the red underline, even the eslint tip `[eslint] Mixed spaces and tabs. (no-mixed-spaces-and-tabs`, but no bulb on the left pane to fix it:
![image](https://user-images.githubusercontent.com/29729527/44194424-3f78fe00-a136-11e8-951a-e3c958431f88.png)
And `ctrl+.` results in `No code actions available` as in @kkolstad comment, but this would be understood, since there is no `editor.action.quickFix` option in Settings.
The following error occurs when I hit `ctrl+.`, but nothing else related to missing bulb happens:
`ERR Cannot read property 'then' of undefined: TypeError: Cannot read property 'then' of undefined
    at e.show (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:736:395)
    at e._onCodeActionsEvent (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2051:338)
    at file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2050:597
    at e.fire (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:172:532)
    at e._signalChange (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1575:498)
    at e._createEventAndSignalChange (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1573:983)
    at e.trigger (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1572:631)
    at e.trigger (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1575:709)
    at e.triggerFromEditorSelection (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2051:802)
    at x (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2049:796)
    at t.run (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2052:773)
    at t.runEditorCommand (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1528:374)
    at file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1527:812
    at e.invokeFunction (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1377:638)
    at t.invokeWithinContext (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1864:369)
    at t.runCommand (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1527:704)
    at handler (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1526:895)
    at e.invokeFunction (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1377:638)
    at t._tryExecuteCommand (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2990:627)
    at file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2990:343
    at n.Class.define.cancel.then (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at t.executeCommand (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2990:317)
    at t._dispatch (file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1383:860)
    at file:///C:/Users/502719682/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3402:260`

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by iRoachie** [comment]
@mjbvz I can confirm the error still occurs in the latest insiders build.

My test was very simple. Tried using a type that I had not yet imported from a package.

```ts
import {
  Keyboard,
  StyleProp,
  StyleSheet,
  TextInput,
  TextInputProperties,
  TextStyle,
  TouchableOpacity,
  View,
} from 'react-native'

// Further in code
onBlur = (e: NativeSyntheticEvent<TextInputFocusEventData>)
```

Both are available from the react-native typings which I do have installed. The same unhelpful error mesage reported by @kkolstad shows.

**Comment by iRoachie** [comment]
Sure thing.
```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "jsx": "react-native",
    "noEmit": true,
    "moduleResolution": "node",
    "strictPropertyInitialization": false,
    "skipLibCheck": true,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "noUnusedLocals": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedParameters": true,
    "sourceMap": true,
    "paths": {
      "@components": ["components"],
      "@config": ["config"],
      "@pages": ["pages"],
      "@types": ["types"],
      "@util": ["util"],
      "@actions": ["actions"],
      "@reducers": ["reducers"],
      "@data": ["data"]
    },
    "lib": ["es2017", "dom"]
  },
  "exclude": ["node_modules"]
}
```

`"@types/react-native": "^0.56.7",`

**Comment by macbielecki** [comment]
Guys... My original issue **was not a ts issue**. This is a vuejs project. I can't test it with all extensions disabled, because when eslint extension is disabled, it's obvious that I get no quick fix options (since everything is ok).
With eslint extension enabled though, I see the red underline and eslint's tooltip with error message:
![image](https://user-images.githubusercontent.com/29729527/44590188-ce32ee00-a7ba-11e8-8e3d-7bcbb8aaac18.png)
But there is no lightbulb and no options when I hit `ctrl+.`:
![image](https://user-images.githubusercontent.com/29729527/44590283-10f4c600-a7bb-11e8-835b-e700a28c9e6f.png)
This is a `.vue` file and this feature was working fine before I updated to `VSCodeUserSetup-x64-1.26.0`. So what happened?

**Comment by mjbvz** [comment]
Yes if it is eslint specific you should file this against the eslint extension (or maybe the vue extension). It wasn't clear if the dev tools error was related but it sounds like it is not

@iRoachie Let's move your problem to a new issue

**Comment by macbielecki** [comment]
I don't understand why you closed this so quickly. Is the yellow lightbulb related to eslint or vue extension?? Or is it vscode?

**Comment by mjbvz** [comment]
The fix/lightbulb comes from eslint or vue. VS Code just the ui for it

**Comment by macbielecki** [comment]
OK, thanks. I will revert the vscode version.

**Comment by iRoachie** [comment]
@kkolstad Moved issue here https://github.com/Microsoft/vscode/issues/57156
