### ISSUE TITLE
node command not working

### ISSUE THREAD

**Issue by Tsukiij** [Microsoft/vscode#56524]
Issue Type: <b>Bug</b>

when I try to execute an exercise using node 01-current-year in the terminal. This shows up module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/Tsukiyume/Downloads/bootcamp-prep-master-2/pre-work-workshops/02-values-and-types/01-current-year'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|4.00GB (0.06GB free)|
|Process Argv|/private/var/folders/w6/qw6c9gv91hxgxw_jpg3qbnwc0000gn/T/AppTranslocation/76910558-46C2-498A-90CC-11853CCCB43B/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tsukiij** [comment]
I see this on both terminals. Can you give me any advice?

**Comment by Tsukiij** [comment]
I see this on both terminals. Can you give me any advice?
