### ISSUE TITLE
Flaky test: WorkspacesMainService getUntitledWorkspaceSync

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#56553]
This test failed for no apparent reason: https://vscode.visualstudio.com/VSCode/_build/results?buildId=5342&_a=summary&view=logs

**Comment by bpasero** [comment]
```
4218 passing (37s)
2018-08-16T08:27:52.9759292Z   8 pending
2018-08-16T08:27:52.9785820Z   1 failing
2018-08-16T08:27:52.9793982Z 
2018-08-16T08:27:52.9810281Z   1) WorkspacesMainService getUntitledWorkspaceSync:
2018-08-16T08:27:52.9821001Z 
2018-08-16T08:27:52.9838022Z       AssertionError [ERR_ASSERTION]: 2 == 1
2018-08-16T08:27:52.9855126Z       + expected - actual
2018-08-16T08:27:52.9863909Z 
2018-08-16T08:27:52.9880012Z       -2
2018-08-16T08:27:53.0096392Z       +1
2018-08-16T08:27:53.0110215Z       
2018-08-16T08:27:53.0126534Z       at file:///opt/vsts/work/1/s/out/vs/platform/workspaces/test/electron-main/workspacesMainService.test.js:305:28
2018-08-16T08:27:53.0142283Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1191:59)
2018-08-16T08:27:53.0157113Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-08-16T08:27:53.0241373Z       at Promise_ctor._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-08-16T08:27:53.0258189Z       at Promise_ctor._completed (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
2018-08-16T08:27:53.0274095Z       at Promise_ctor.CompletePromise_done [as done] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1545:34)
2018-08-16T08:27:53.0289015Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1201:48)
2018-08-16T08:27:53.0303867Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-08-16T08:27:53.0319619Z       at Promise_ctor._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-08-16T08:27:53.0335134Z       at Promise_ctor._completed (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
```

**Comment by bpasero** [comment]
```
1) WorkspaceContextService - Workspace add folders triggers change event:
2018-08-16T14:23:15.4786921Z 
2018-08-16T14:23:15.4802365Z       AssertionError [ERR_ASSERTION]: false == true
2018-08-16T14:23:15.4828780Z       + expected - actual
2018-08-16T14:23:15.4837709Z 
2018-08-16T14:23:15.4892735Z       -false
2018-08-16T14:23:15.4907322Z       +true
2018-08-16T14:23:15.4921225Z       
2018-08-16T14:23:15.4944858Z       at file:///opt/vsts/work/1/s/out/vs/workbench/services/configuration/test/electron-browser/configurationService.test.js:196:24
2018-08-16T14:23:15.4961702Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1191:59)
2018-08-16T14:23:15.4977109Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-08-16T14:23:15.4992179Z       at Promise_ctor._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-08-16T14:23:15.5007474Z       at Promise_ctor._completed (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
2018-08-16T14:23:15.5023140Z       at _Base.Class.derive._creator.CompletePromise_done [as done] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1545:34)
2018-08-16T14:23:15.5038448Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1201:48)
2018-08-16T14:23:15.5053503Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-08-16T14:23:15.5068159Z       at _Base.Class.derive._creator._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-08-16T14:23:15.5083858Z       at _Base.Class.derive._creator._completed (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
```

**Comment by bpasero** [comment]
I added some logging to the test that we need to inspect once the test fails again.
