### ISSUE TITLE
IPC depends on WinJS.Promise timing

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#56579]
I have made f8dad22a and then saw this error... Reverted the change for now

```
ERR Cannot read property '/Users/jrieken/Code/_samples/ConsoleAppDnx' of undefined: TypeError: Cannot read property '/Users/jrieken/Code/_samples/ConsoleAppDnx' of undefined,    at ChokidarWatcherService.setRoots (/Users/jrieken/Code/vscode/out/vs/workbench/services/files/node/watcher/unix/chokidarWatcherService.js:26:45),    at WatcherChannel.call (/Users/jrieken/Code/vscode/out/vs/workbench/services/files/node/watcher/unix/watcherIpc.js:20:54),    at Server.ChannelServer.onPromise (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.js:64:35),    at Server.ChannelServer.onMessage (/Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.js:48:26),    at /Users/jrieken/Code/vscode/out/vs/base/parts/ipc/common/ipc.js:39:89,    at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:148:38),    at process.fn (/Users/jrieken/Code/vscode/out/vs/base/common/event.js:599:27),    at emitTwo (events.js:126:13),    at process.emit (events.js:214:7),    at emit (internal/child_process.js:772:12)
```

**Comment by joaomoreno** [comment]
By timing, you mean the order of execution of the ctor callback, right?

**Comment by jrieken** [comment]
Yeah, something like that. Having made that change and errors have appeared 😢

**Comment by joaomoreno** [comment]
IPC is now TPromise free!
