### ISSUE TITLE
Flaky tests 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#56649]
```
1) WorkspaceContextService - Workspace add folders triggers change event:
2018-08-16T14:23:15.4786921Z 
2018-08-16T14:23:15.4802365Z       AssertionError [ERR_ASSERTION]: false == true
2018-08-16T14:23:15.4828780Z       + expected - actual
2018-08-16T14:23:15.4837709Z 
2018-08-16T14:23:15.4892735Z       -false
2018-08-16T14:23:15.4907322Z       +true
2018-08-16T14:23:15.4921225Z       
2018-08-16T14:23:15.4944858Z       at file:///opt/vsts/work/1/s/out/vs/workbench/services/configuration/test/electron-browser/configurationService.test.js:196:24
2018-08-16T14:23:15.4961702Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1191:59)
2018-08-16T14:23:15.4977109Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-08-16T14:23:15.4992179Z       at Promise_ctor._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-08-16T14:23:15.5007474Z       at Promise_ctor._completed (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
2018-08-16T14:23:15.5023140Z       at _Base.Class.derive._creator.CompletePromise_done [as done] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1545:34)
2018-08-16T14:23:15.5038448Z       at Object.notifySuccess [as _notify] (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1201:48)
2018-08-16T14:23:15.5053503Z       at Object.enter (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-08-16T14:23:15.5068159Z       at _Base.Class.derive._creator._run (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-08-16T14:23:15.5083858Z       at _Base.Class.derive._creator._completed (file:///opt/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
```

extracted from https://github.com/Microsoft/vscode/issues/56553

**Comment by sandy081** [comment]
Added some logs to get more info

**Comment by sandy081** [comment]
Different tests in the same suite are failing for the same reason. So added detailed assertions to all tests to capture more information. Will keep an eye on future failures.

**Comment by sandy081** [comment]
I do not see these failing in last 6 months. Could be fixed.

I would reopen them if they fail again.
