### ISSUE TITLE
'Problems' pane shows incorrect errors and becomes non-responsive

### ISSUE THREAD

**Issue by ronp001** [Microsoft/vscode#56763]
Issue Type: <b>Bug</b>

When working on a TypeScript/ReactNative project (with build set to 'tsc watch'), the Problems pane starts showing an messed up list of problems.  Clicking on any of these problems does not have any result (focus does not change). 

Screenshot of the Problems Pane in this state:
![image](https://user-images.githubusercontent.com/524102/44310353-0a420980-a3dd-11e8-9886-571753b71468.png)

Closing and re-opening the workspace restores normal functionality for a while.

I do not know how to reproduce this problem - it happens every once in a while.  

Started happening after auto-update to the Aug 13 2018 build.  Originally happened every several minutes. I disabled all extensions, and the frequency went down significantly to every several hours.

Log files uploaded (Log file ID: 48136725)

The Output (Log) pane shows multiple errors, such as:

[2018-08-19 18:14:04.387] [renderer4] [error] Cannot read property 'id' of null: TypeError: Cannot read property 'id' of null
    at t.e.itemAfter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:345:960)
    at t.insertItemInDOM (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:976:259)
    at t.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:959:133)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:954:429
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:532)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:392:566
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:532)
    at t._setState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:255:372)
    at t.setScrollPositionNow (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:253:889)
    at t._onMouseWheel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:396:706)
    at HTMLDivElement.n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:395:652)

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 9, 13|
|Memory (System)|16.00GB (1.62GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ronp001** [comment]
This issue is not covered by any of the issues listed by the bot.
