### ISSUE TITLE
Failed to build since vscode 1.26+

### ISSUE THREAD

**Issue by eomarjee** [Microsoft/vscode#56830]
- VSCode Version: 1.26 and 1.26.1 (didn't have this issue with 1.25.1)
- OS Version: Arch x86_64 

Steps to Reproduce:

Build this package: ([https://aur.archlinux.org/packages/code/](https://aur.archlinux.org/packages/code/))

Got this error:
```
[18:47:09] Using gulpfile ~/packages/code/src/vscode/gulpfile.js
[18:47:09] Starting 'clean-minified-vscode'...
[18:47:09] Starting 'clean-optimized-vscode'...
[18:47:09] Starting 'clean-client-build'...
[18:47:09] Starting 'clean-extension:configuration-editing'...
[18:47:09] Starting 'clean-extension:css-language-features-client'...
[18:47:09] Starting 'clean-extension:css-language-features-server'...
[18:47:09] Starting 'clean-extension:debug-auto-launch'...
[18:47:09] Starting 'clean-extension:emmet'...
[18:47:09] Starting 'clean-extension:extension-editing'...
[18:47:09] Starting 'clean-extension:git'...
[18:47:09] Starting 'clean-extension:grunt'...
[18:47:09] Starting 'clean-extension:gulp'...
[18:47:09] Starting 'clean-extension:html-language-features-client'...
[18:47:09] Starting 'clean-extension:html-language-features-server'...
[18:47:09] Starting 'clean-extension:jake'...
[18:47:09] Starting 'clean-extension:json-language-features-client'...
[18:47:09] Starting 'clean-extension:json-language-features-server'...
[18:47:09] Starting 'clean-extension:markdown-language-features-preview-src'...
[18:47:09] Starting 'clean-extension:markdown-language-features'...
[18:47:09] Starting 'clean-extension:merge-conflict'...
[18:47:09] Starting 'clean-extension:npm'...
[18:47:09] Starting 'clean-extension:php-language-features'...
[18:47:09] Starting 'clean-extension:python'...
[18:47:09] Starting 'clean-extension:search-rg'...
[18:47:09] Starting 'clean-extension:typescript-basics-test-colorize-fixtures'...
[18:47:09] Starting 'clean-extension:typescript-language-features'...
[18:47:09] Starting 'clean-extension:vscode-api-tests'...
[18:47:09] Starting 'clean-extension:vscode-colorize-tests'...
[18:47:09] Starting 'clean-vscode-linux-x64'...
[18:47:09] Finished 'clean-extension:markdown-language-features-preview-src' after 3.28 ms
[18:47:09] Starting 'compile-extension-build:markdown-language-features-preview-src'...
[18:47:09] Starting compilation...
[18:47:09] Finished 'clean-extension:typescript-basics-test-colorize-fixtures' after 102 ms
[18:47:09] Starting 'compile-extension-build:typescript-basics-test-colorize-fixtures'...
[18:47:09] Finished 'clean-vscode-linux-x64' after 108 ms
[18:47:09] Finished compilation with 0 errors after 123 ms
[18:47:09] Finished 'compile-extension-build:markdown-language-features-preview-src' after 152 ms
[18:47:09] Finished 'compile-extension-build:typescript-basics-test-colorize-fixtures' after 51 ms
[18:47:09] Finished 'clean-extension:configuration-editing' after 270 ms
[18:47:09] Starting 'compile-extension-build:configuration-editing'...
[18:47:09] Starting compilation...
[18:47:09] Finished 'clean-extension:debug-auto-launch' after 273 ms
[18:47:09] Starting 'compile-extension-build:debug-auto-launch'...
[18:47:09] Finished 'clean-extension:css-language-features-client' after 275 ms
[18:47:09] Starting 'compile-extension-build:css-language-features-client'...
[18:47:09] Finished 'clean-extension:extension-editing' after 276 ms
[18:47:09] Starting 'compile-extension-build:extension-editing'...
[18:47:09] Finished 'clean-extension:grunt' after 278 ms
[18:47:09] Starting 'compile-extension-build:grunt'...
[18:47:09] Finished 'clean-extension:html-language-features-client' after 285 ms
[18:47:09] Starting 'compile-extension-build:html-language-features-client'...
[18:47:09] Finished 'clean-extension:jake' after 288 ms
[18:47:09] Starting 'compile-extension-build:jake'...
[18:47:09] Finished 'clean-extension:gulp' after 291 ms
[18:47:09] Starting 'compile-extension-build:gulp'...
[18:47:09] Finished 'clean-extension:merge-conflict' after 302 ms
[18:47:09] Starting 'compile-extension-build:merge-conflict'...
[18:47:09] Finished 'clean-extension:python' after 304 ms
[18:47:09] Starting 'compile-extension-build:python'...
[18:47:09] Finished 'clean-extension:vscode-colorize-tests' after 310 ms
[18:47:09] Starting 'compile-extension-build:vscode-colorize-tests'...
[18:47:09] Finished 'clean-extension:css-language-features-server' after 378 ms
[18:47:09] Starting 'compile-extension-build:css-language-features-server'...
[18:47:09] Finished 'clean-extension:git' after 380 ms
[18:47:09] Starting 'compile-extension-build:git'...
[18:47:09] Finished 'clean-extension:emmet' after 383 ms
[18:47:09] Starting 'compile-extension-build:emmet'...
[18:47:09] Finished 'clean-extension:json-language-features-server' after 384 ms
[18:47:09] Starting 'compile-extension-build:json-language-features-server'...
[18:47:09] Finished 'clean-extension:json-language-features-client' after 387 ms
[18:47:09] Starting 'compile-extension-build:json-language-features-client'...
[18:47:09] Finished 'clean-extension:npm' after 390 ms
[18:47:09] Starting 'compile-extension-build:npm'...
[18:47:09] Finished 'clean-extension:markdown-language-features' after 394 ms
[18:47:09] Starting 'compile-extension-build:markdown-language-features'...
[18:47:09] Finished 'clean-extension:search-rg' after 397 ms
[18:47:09] Starting 'compile-extension-build:search-rg'...
[18:47:09] Finished 'clean-extension:vscode-api-tests' after 398 ms
[18:47:09] Starting 'compile-extension-build:vscode-api-tests'...
[18:47:09] Finished 'clean-extension:typescript-language-features' after 404 ms
[18:47:09] Starting 'compile-extension-build:typescript-language-features'...
[18:47:10] Finished 'clean-extension:php-language-features' after 786 ms
[18:47:10] Starting 'compile-extension-build:php-language-features'...
[18:47:19] Finished 'clean-extension:html-language-features-server' after 9.72 s
[18:47:19] Starting 'compile-extension-build:html-language-features-server'...
[18:47:23] Finished 'compile-extension-build:python' after 13 s
[18:47:25] Finished 'clean-minified-vscode' after 16 s
[18:47:25] Finished 'compile-extension-build:css-language-features-client' after 16 s
[18:47:25] Finished 'compile-extension-build:gulp' after 16 s
[18:47:25] Finished 'compile-extension-build:grunt' after 16 s
[18:47:26] Finished 'compile-extension-build:jake' after 17 s
[18:47:26] Finished 'compile-extension-build:vscode-colorize-tests' after 17 s
[18:47:26] Finished 'clean-client-build' after 17 s
[18:47:26] Starting 'compile-client-build'...
[18:47:27] Finished 'clean-optimized-vscode' after 18 s
[18:47:27] Finished 'compile-extension-build:configuration-editing' after 18 s
[18:47:29] Finished 'compile-extension-build:json-language-features-client' after 20 s
[18:47:30] Finished 'compile-extension-build:extension-editing' after 21 s
[18:47:30] Finished 'compile-extension-build:html-language-features-client' after 21 s
[18:47:30] Finished 'compile-extension-build:json-language-features-server' after 21 s
[18:47:34] Finished 'compile-extension-build:debug-auto-launch' after 24 s
[18:47:34] Finished 'compile-extension-build:css-language-features-server' after 24 s
[18:47:34] Finished 'compile-extension-build:search-rg' after 24 s
[18:47:37] Finished 'compile-extension-build:npm' after 28 s
[18:47:38] Finished 'compile-extension-build:merge-conflict' after 28 s
[18:47:38] Finished 'compile-extension-build:php-language-features' after 28 s
[18:47:38] Finished 'compile-extension-build:vscode-api-tests' after 28 s
[18:47:43] Finished 'compile-extension-build:git' after 34 s
[18:47:45] Finished 'compile-extension-build:emmet' after 35 s
[18:47:45] Finished 'compile-extension-build:markdown-language-features' after 35 s
[18:47:45] Finished 'compile-extension-build:html-language-features-server' after 26 s
[18:47:49] Finished 'compile-extension-build:typescript-language-features' after 40 s
[18:47:49] Starting 'compile-extensions-build'...
[18:47:49] Finished 'compile-extensions-build' after 76 μs
[18:50:28] [monaco.d.ts] Starting monaco.d.ts generation
[18:50:31] [monaco.d.ts] Finished monaco.d.ts generation
[18:50:31] Finished compilation with 0 errors after 201896 ms
[18:50:31] Finished 'compile-client-build' after 3.08 min
[18:50:31] Starting 'compile-build'...
[18:50:31] Finished 'compile-build' after 5.46 μs
[18:50:31] Starting 'optimize-vscode'...
CSS INLINING IMAGE AT out-build/vs/editor/contrib/colorPicker/images/opacity-background.png MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/BooleanData_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/BooleanData_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Field_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Field_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Method_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Method_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Method_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Method_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Namespace_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Namespace_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Namespace_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Namespace_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Namespace_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/Namespace_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/String_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/documentSymbols/media/String_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/images/previous.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/images/next.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/images/close.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/images/previous-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/images/next-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/images/close-dark.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-dirty.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-dirty-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/notifications/media/down-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/notifications/media/down.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/comments/electron-browser/media/comment.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/current-arrow.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/start.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/continue-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/start.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/extensions/electron-browser/media/loading.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/extensions/electron-browser/media/profile-stop.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/feedback/electron-browser/media/info.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/edit.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/edit_inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/info.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/edit.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/edit_inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build/vs/workbench/parts/welcome/code-icon.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
[18:51:19] Finished 'optimize-vscode' after 47 s
[18:51:19] Starting 'optimize-index-js'...
[18:51:19] Finished 'optimize-index-js' after 455 μs
[18:51:19] Starting 'minify-vscode'...
[18:54:55] Finished 'minify-vscode' after 3.6 min
[18:54:55] Starting 'vscode-linux-x64-min'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 0.0.0.0:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

**Comment by Tyriar** [comment]
We don't support ArchLinux currently but I suspect it's related to the Electron 2 update: https://github.com/Microsoft/vscode/issues/55934. If you find out what the problem is let us know, the definition for the build task is here https://github.com/Microsoft/vscode/blob/f8168e6c2ed6da949c1b7137e69e0499913b5792/build/gulpfile.vscode.js#L382
