### ISSUE TITLE
Crashes randomly and unable to successfully Force Quit, consumes a lot of Energy while appear

### ISSUE THREAD

**Issue by walaa-alkhanaizi-bose** [Microsoft/vscode#56865]
VS Code crashes randomly on MacOS High Sierra while I am not even using it. I am unable to close it, or even force quit. I force quit using Activity Monitor and checked back later and it was still there, but I was unable to force quit out of it. Now that I was able to, I don't seem to be able to launch VS Code by clicking on the application icon, or from the Spotlight search, or even from the command line.

- VSCode Version: 1.26.1
- OS Version: MacOS High Sierra (10.13.6)

Steps to Reproduce:
It happened a few times, but seemingly randomly and I am not sure how to reproduce it

Does this issue occur when all extensions are disabled?: Yes/No
I can't check because I am unable to launch VS Code now.

**Comment by nicois** [comment]
I am running ubuntu 18.04, and am also unable to even open code.
I installed the SSH filesystem provider, exited and tried to reload, and I get a stack trace:

```
$ code --verbose
[main 11:49:38] Starting VS Code
[main 11:49:38] from: /usr/share/code/resources/app
[main 11:49:38] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 11:49:38] Resolving machine identifier...
[main 11:49:38] Resolved machine identifier: c3620e039719648956719b8cab7c99464842fe1741390b2dd4be3ad35a30c0c0
[main 11:49:38] update#setState idle
[main 11:49:38] windowsManager#open
[main 11:49:38] TypeError: Cannot read property 'replace' of null
    at Object.t.unmnemonicLabel (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:66:271)
    at e.createOpenRecentMenuItem (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:389:53)
    at e.setOpenRecentMenu (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:388:326)
    at e.setFileMenu (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:384:923)
    at e.install (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:380:722)
    at e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:377:378)
    at t.create (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:52:694)
    at e._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:209:325)
    at e.createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:208:600)
    at t.afterWindowOpen (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:531:755)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:526:794
    at e.invokeFunction (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:208:279)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:526:758
    at n.Class.define.cancel.then (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:91:201)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:526:618
    at n.Class.define.cancel.then (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:91:201)
    at t.startup (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:526:25)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:537:862
    at Object.v [as _notify] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:84:572)
    at Object.enter (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:87:924)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:89:790)
    at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:89:231)
    at Server.<anonymous> (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:170:865)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[main 11:49:38] Lifecycle#kill()
[main 11:49:38] Lifecycle#window-closed 1
[main 11:49:38] Lifecycle#onShutdown.fire()
[main 11:49:38] telemetry/optInStatus { optIn: true }
```

**Comment by bpasero** [comment]
@nicois can you open a separate issue with that detail, it seems unrelated

@walaa-alkhanaizi-bose can you run `code --verbose` from the command line to see if any output is printed when it hangs?

**Comment by bpasero** [comment]
@nicois your issue seems to be https://github.com/Microsoft/vscode/issues/57027
