### ISSUE TITLE
Cannot read property 'updateElementsByName' of undefined:

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#56913]
OS X, out of source

1. Start vscode, sometimes happens on startup

Sorry for not precise steps, but it happens seldomly.

```
  ERR Cannot read property 'updateElementsByName' of undefined: TypeError: Cannot read property 'updateElementsByName' of undefined
    at file:///Users/isidor/Development/vscode/out/vs/workbench/parts/preferences/browser/settingsEditor2.js:521:81
    at Array.forEach (<anonymous>)
    at SettingsEditor2.updateElementsByKey (file:///Users/isidor/Development/vscode/out/vs/workbench/parts/preferences/browser/settingsEditor2.js:521:22)
    at SettingsEditor2.onConfigUpdate (file:///Users/isidor/Development/vscode/out/vs/workbench/parts/preferences/browser/settingsEditor2.js:479:29)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/parts/preferences/browser/settingsEditor2.js:51:23
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:148:38)
    at WorkspaceService.triggerConfigurationChange (file:///Users/isidor/Development/vscode/out/vs/workbench/services/configuration/node/configurationService.js:574:48)
    at WorkspaceService.onDefaultConfigurationChanged (file:///Users/isidor/Development/vscode/out/vs/workbench/services/configuration/node/configurationService.js:414:22)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/configuration/node/configurationService.js:56:179
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:148:38)
    at ConfigurationRegistry.registerConfigurations (file:///Users/isidor/Development/vscode/out/vs/platform/configuration/common/configurationRegistry.js:55:46)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/configuration/common/configurationExtensionPoint.js:117:31
    at ExtensionPoint._handle (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/extensionsRegistry.js:67:17)
    at ExtensionPoint.acceptUsers (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/extensionsRegistry.js:55:18)
    at Function.ExtensionService._handleExtensionPoint (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:832:28)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:431:38
    at Object.notifySuccess [as _notify] (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1191:59)
    at Object.enter (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:867:30)
    at _Base.Class.derive._creator._run (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1089:29)
    at _Base.Class.derive._creator._completed (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1057:18)
    at <anonymous>
```

**Comment by isidorn** [comment]
Did not see it today -> verified
Will reopen if I see it again
