### ISSUE TITLE
Unable to convert markdown TM syntax to extension

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5692]
- VSCode Version: 1.0.1-alpha
- OS Version: Mac OS X 10.11

Steps to Reproduce:

1. create an extension from https://raw.githubusercontent.com/textmate/markdown.tmbundle/master/Syntaxes/Markdown.tmLanguage
2. Run the extension
3. create a README.md file with below contents
4. open it

Crash:
```
//Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/shell.js:240 Cannot read property 'split' of null: TypeError: Cannot read property 'split' of null
    at DecodeMap.getTokenIds (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/node/textMate/TMSyntax.js:127:34)
    at decodeTextMateToken (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/node/textMate/TMSyntax.js:218:36)
    at Tokenizer.tokenize (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/node/textMate/TMSyntax.js:190:33)
    at Object.tokenize (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/node/textMate/TMSyntax.js:111:92)
    at Model.TextModelWithTokens._updateTokensUntilLine (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModelWithTokens.js:540:60)
    at Model.TextModelWithTokens._revalidateTokensNow (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModelWithTokens.js:497:22)
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModelWithTokens.js:450:27
```

Contents:
```
# README
## This is the README for your extension "test-ts"
You can author your README using Visual Studio Code.  Here are some useful editor keyboard shortcuts:

* Split the editor (`Cmd+\` on OSX or `Ctrl+\` on Windows and Linux)
* Toggle preview (`Shift+CMD+V` on OSX or `Shift+Ctrl+V` on Windows and Linux)
* Press `Ctrl+Space` (Windows, Linux) or `Cmd+Space` (OSX) to see a list of Markdown snippets

### For more information
* [Visual Studio Code's Markdown Support](http://code.visualstudio.com/docs/languages/markdown)
* [Markdown Syntax Reference](https://help.github.com/articles/markdown-basics/)

**Enjoy!**
```

@aeschli fyi

**Comment by aeschli** [comment]
The tmgrammar has the following empty capture on line 1078:
```xml
				<key>raw</key>
				<dict>
					<key>captures</key>
					<dict>

						<key>2</key>
						<dict/>
```

I created https://github.com/Microsoft/vscode-textmate/issues/10.

As a workaround just remove these two lines.

**Comment by bpasero** [comment]
👍
