### ISSUE TITLE
Secondary windows and integrated terminals crashed/stopped after waking up mac

### ISSUE THREAD

**Issue by OzzyTheGiant** [Microsoft/vscode#57011]
After waking up laptop, I find that the integrated terminals I had running have crashed and if I have multiple windows open, all but the first window are gone. In some rare cases, the entire app has quit. And what's worse, it's all silent. No system dialog box saying it crashed, no error logs, nothing.

This has also happened with Adobe XD too, but not very often. Just not sure if it's a system issue or an app issue.

- VSCode Version: 1.26.0
- OS Version: 10.12.6

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@OzzyTheGiant can you launch VS Code with code --verbose and paste in the output you see in the terminal if it happens again?

**Comment by OzzyTheGiant** [comment]
Ok I'll keep a look out. Hasn't happened yet so, I'll post when I see this again.

**Comment by Tyriar** [comment]
@OzzyTheGiant 👍

**Comment by OzzyTheGiant** [comment]
@Tyriar Ok it happened again. I left VS Code open while putting laptop to sleep. On wake up, the laptop takes nearly a minute just get the screen turned on, and I find that VS Code has completely crashed silently. I was not using a second window this time though. Here's the output I got from using code --verbose:

[main 11:07:45 PM] Starting VS Code
[main 11:07:46 PM] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 11:07:46 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 11:07:46 PM] Resolving machine identifier...
[main 11:07:46 PM] Resolved machine identifier: b1e4d5407b46481738b603d09c6d9c7cbfc2f0c4f1fdad302781c6e79dab5c49
[main 11:07:46 PM] update#setState idle
[main 11:07:46 PM] windowsManager#open
[main 11:07:52 PM] telemetry/optInStatus { optIn: true }
[94207:0902/230806.573722:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:06 PM] windowsService#whenSharedProcessReady
[94207:0902/230806.772074:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230806.931308:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:07 PM] windowsService#getRecentlyOpened 1
[94207:0902/230808.797288:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:08 PM] windowsService#setRepresentedFilename 1
[main 11:08:13 PM] windowsService#getRecentlyOpened 1
[94207:0902/230813.907300:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230813.907769:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230813.908202:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:14 PM] windowsService#startCrashReporter
[main 11:08:15 PM] windowsService#updateTouchBar 1
[main 11:08:16 PM] update#checkForUpdates, state =  idle
[main 11:08:16 PM] update#setState checking for updates
[main 11:08:19 PM] telemetry/update:notAvailable { explicit: false }
[main 11:08:19 PM] update#setState idle
[94207:0902/230823.114146:INFO:CONSOLE(1398)] "%c WARN", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1398)
[94207:0902/230823.166979:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230823.167118:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230823.169791:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:25 PM] windowsService#setRepresentedFilename 1
[94207:0902/230825.572882:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:25 PM] windowsService#getWindowCount
[94207:0902/230825.752437:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:25 PM] IPC#vscode-workbenchLoaded
[94207:0902/230825.805137:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230826.758187:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230830.826814:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230830.827008:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230835.684575:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230835.684760:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230837.044321:INFO:CONSOLE(272)] "%c[IPC Library: Watcher] %cStart watching: /Users/Ozzy/Projects/Web Development/gm-cpas.com]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/230848.626622:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230850.190735:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230850.308536:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230850.323243:INFO:CONSOLE(245)] "Overwriting extension <<.html>> to now point to mime <<text/x-html>>", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (245)
[94207:0902/230850.323328:INFO:CONSOLE(245)] "Overwriting extension <<.htm>> to now point to mime <<text/x-html>>", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (245)
[94207:0902/230850.324445:INFO:CONSOLE(245)] "Overwriting extension <<.conf>> to now point to mime <<text/x-apacheconf>>", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (245)
[94207:0902/230850.326923:INFO:CONSOLE(245)] "Overwriting extension <<.gradle>> to now point to mime <<text/x-gradle>>", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (245)
[94207:0902/230850.327765:INFO:CONSOLE(246)] "Overwriting filepattern <<bootstrap*.yml>> to now point to mime <<text/x-spring-boot-properties>>", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (246)
[94207:0902/230850.331057:INFO:CONSOLE(4188)] "Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/Ozzy/.vscode/extensions/ms-mssql.mssql-1.4.0/syntaxes/SQL.plist", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (4188)
[94207:0902/230850.331157:INFO:CONSOLE(4188)] "Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///Users/Ozzy/.vscode/extensions/naco-siren.gradle-language-0.2.3/syntaxes/groovy.tmLanguage.json", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (4188)
[94207:0902/230850.331348:INFO:CONSOLE(4188)] "Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/Ozzy/.vscode/extensions/pivotal.vscode-spring-boot-0.5.0/yaml-support/yaml.tmLanguage", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (4188)
[94207:0902/230850.570861:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230850.595904:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:51 PM] windowsService#setRepresentedFilename 1
[main 11:08:52 PM] windowsService#updateTouchBar 1
[94207:0902/230854.755487:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:08:55 PM] windowsService#isFocused 1
[94207:0902/230857.123696:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230857.207119:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230857.407114:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230857.424816:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230901.437949:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230901.637223:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230901.637372:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230901.637473:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230901.734052:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230901.734218:INFO:CONSOLE(1397)] "%c INFO", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230924.879495:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230925.110907:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/230925.111567:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:09:56 PM] App#activate
[94207:0902/231001.492234:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.492841:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.493227:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.493841:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.494311:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.494873:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.495332:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.495989:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.496450:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.496904:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.497571:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.498006:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.498514:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.498973:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.508620:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.508776:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.508902:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.509015:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.509116:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231001.509207:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.537371:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.538005:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.538500:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.541523:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.542155:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.542673:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.543246:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.543781:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.544293:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231004.743563:INFO:CONSOLE(272)] "%c[Extension Host] %cCongratulations, your extension "git tags" is now active! %c(at activate (/Users/Ozzy/.vscode/extensions/howardzuo.vscode-git-tags-1.3.1/out/index.js:21:13))", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231004.836148:INFO:CONSOLE(272)] "%c[Extension Host] %cTelemetry enabled! %c(at enable (/Users/Ozzy/.vscode/extensions/mtxr.sqltools-0.15.0/dist/api/telemetry.js:56:16))", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231004.951913:INFO:CONSOLE(272)] "%c[Extension Host] %cvscode-icons is active! %c(at activate (/Users/Ozzy/.vscode/extensions/robertohuertasm.vscode-icons-7.25.0/out/src/index.js:41:13))", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231006.036465:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.036874:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.037058:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.037391:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.037502:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.038176:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.040276:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.367977:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.368108:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375321:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375432:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375509:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375592:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375680:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375769:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375873:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.375971:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376057:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376139:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376222:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376305:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376385:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376470:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376554:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376647:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376731:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376817:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376905:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.376995:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.377075:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.714236:INFO:CONSOLE(1397)] "%cDEBUG", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.873531:INFO:CONSOLE(1397)] "%cDEBUG", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.943505:INFO:CONSOLE(1397)] "%cDEBUG", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231006.945217:INFO:CONSOLE(1397)] "%cDEBUG", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231008.147374:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231010.130354:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231010.130612:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231010.243432:INFO:CONSOLE(272)] "%c[Extension Host] %ctags refreshed with remote %c(at child_process.exec (/Users/Ozzy/.vscode/extensions/howardzuo.vscode-git-tags-1.3.1/out/services/gitTagsResolver.js:107:17))", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231010.573764:INFO:CONSOLE(272)] "%c[IPC Library: Watcher] %c[ADDED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231010.635973:INFO:CONSOLE(272)] "%c[IPC Library: Watcher] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231010.935599:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231010.983658:INFO:CONSOLE(272)] "%c[IPC Library: Watcher] %c[DELETED]", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231011.035569:INFO:CONSOLE(272)] "%c[IPC Library: Watcher] %c >> normalized", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (272)
[94207:0902/231026.581396:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231026.582565:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231026.582677:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231026.582772:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231026.586017:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231026.586399:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231026.587025:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231026.587276:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231036.062225:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231036.062479:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231036.063125:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[94207:0902/231036.063275:INFO:CONSOLE(1397)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:13:37 PM] App#activate

**Comment by Tyriar** [comment]
I suspect this is a duplicate of https://github.com/Microsoft/vscode/issues/56628 which will be fixed in the next version (releasing very soon).
