### ISSUE TITLE
Vs Code will not open with version 1.26.1 Even with a fresh install

### ISSUE THREAD

**Issue by vlurgio** [Microsoft/vscode#57027]
- VSCode Version: 1.26.1
- OS Version: Mac 10.13.6

Steps to Reproduce:

1. open code from finder or command line
2. code trys to open and can't

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Output from --verbose
```bash
Starting VS Code
[main 12:41:11 PM] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 12:41:11 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 12:41:11 PM] Resolving machine identifier...
[main 12:41:11 PM] Resolved machine identifier: 9836439229ff1408148cd1c4db433ff8273ba94f870c3c844d86712d0ff80719
[main 12:41:11 PM] update#setState idle
[main 12:41:11 PM] windowsManager#open
2018-08-22 12:41:11.384 Electron[2000:14897] *** WARNING: Textured window <AtomNSWindow: 0x7fcffd7d1ff0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[main 12:41:11 PM] TypeError: Cannot read property 'replace' of null
    at Object.t.unmnemonicLabel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:66:271)
    at e.createOpenRecentMenuItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:389:53)
    at e.setOpenRecentMenu (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:388:326)
    at e.setFileMenu (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:384:923)
    at e.install (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:380:722)
    at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:377:378)
    at t.create (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:52:694)
    at e._createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:209:325)
    at e.createInstance (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:208:600)
    at t.afterWindowOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:531:755)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:526:794
    at e.invokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:208:279)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:526:758
    at n.Class.define.cancel.then (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:91:201)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:526:618
    at n.Class.define.cancel.then (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:91:201)
    at t.startup (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:526:25)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:537:862
    at Object.v [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:572)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:924)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:89:790)
    at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:89:231)
    at Server.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:170:865)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[main 12:41:11 PM] Lifecycle#kill()
[main 12:41:11 PM] Lifecycle#window-closed 1
[main 12:41:11 PM] telemetry/optInStatus { optIn: true }
```

**Comment by bpasero** [comment]
This seems to be another regression (or maybe an existing one we dealt with already?) with the change from string => URI. 

/cc @isidorn

**Comment by aeschli** [comment]
@vlurgio Can you send us your `storage.json` file 
`/Users/$userid/Library/Application Support/Code/storage.json`?

Deleting that file (or the `openedPathsList` list) should fix the VSCode startup.

**Comment by sandy081** [comment]
Probably provide us the value of `openedPathsList` property before deleting it so that we can reproduce it and fix the issue.

**Comment by datatechnology** [comment]
code --verbose
[main 12:36:15 AM] Sending env to running instance...
[main 12:36:15 AM] Sent env to running instance. Terminating...
[main 12:36:15 AM] Lifecycle#kill()
[46697:0906/003615.619663:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

**Comment by datatechnology** [comment]
same here,
$code --verbose
[main 12:37:04 AM] Sending env to running instance...
[main 12:37:04 AM] Sent env to running instance. Terminating...
[main 12:37:04 AM] Lifecycle#kill()

$code --version
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64

**Comment by bpasero** [comment]
@datatechnology I am not sure that is the same issue, you seem to have a VS Code instance already running, could that be true?

**Comment by datatechnology** [comment]
Nope, it cannot be launched, I am using insider version now, which works fine

**Comment by bpasero** [comment]
@datatechnology restart your computer and try again with stable

**Comment by datatechnology** [comment]
I will find some time to restart, as insider is working, no eager to solve the problem

**Comment by bpasero** [comment]
OK

**Comment by vlurgio** [comment]
For anyone that's wondering It didn't register a key I had mapped and this made it unable to start not sure why deleting all the lingering files allowed me to start up again.

**Comment by sandy081** [comment]
@datatechnology Please reopen it when you see this problem again.
