### ISSUE TITLE
Find replace does not show diffs properly

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57076]
1. Search find labelService
2. Replace it with labelService2

Notice how the diffs are not properly shown. Yes two identical editors side by side
fyi @sandy081

**Comment by roblourens** [comment]
I have no idea, debugged and it looks normal, do you know what changed @sandy081 ?

**Comment by sandy081** [comment]
Not aware of any changes went in here.. Will investigate.

**Comment by sandy081** [comment]
@bpasero There is following error in console

```
 ERR Cannot edit a read-only editor.: Error: Cannot edit a read-only editor.
    at file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:188:47
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.js:1587:49)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:182:126
    at Map.forEach (<anonymous>)
    at BulkEditModel.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:181:41)
    at step (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:50:23)
    at Object.next (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:31:53)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:21:12)
    at BulkEditModel.prepare (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:170:20)
    at BulkEdit.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:396:56)
    at step (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:50:23)
    at Object.next (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:31:53)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:21:12)
    at BulkEdit._performTextEdits (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:387:20)
    at BulkEdit.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:304:59)
    at step (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:50:23)
    at Object.next (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:31:53)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:21:12)
    at BulkEdit.perform (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:264:20)
    at BulkEditService.apply (file:///Users/sandy081/work/vscode/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js:466:56)
    at ReplaceService.replace (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/search/browser/replaceService.js:123:43)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/parts/search/browser/replaceService.js:164:41
    at Promise_ctor.CompletePromise_then [as then] (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.js:1587:49)
    at ReplaceService.updateReplacePreview (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/search/browser/replaceService.js:151:18)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/parts/search/browser/replaceService.js:138:23
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.js:1587:49)
    at ReplaceService.openReplacePreview (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/search/browser/replaceService.js:137:16)
    at SearchView.onFocus (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/search/browser/searchView.js:1184:37)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/parts/search/browser/searchView.js:439:35
    at Emitter.fire (file:///Users/sandy081/work/vscode/out/vs/base/common/event.js:148:38)
    at file:///Users/sandy081/work/vscode/out/vs/base/common/event.js:363:37
```

**Comment by isidorn** [comment]
@sandy081 I introduced that by throwin an error when somebody tries to edit a read only editor.
https://github.com/Microsoft/vscode/commit/8281fa7fadd56655744e747f8d2d138ba34c46b8
Why are you editing a read only editor (I guess left hand side)?

**Comment by sandy081** [comment]
Because, it is a replace preview that shows before and after. Both sides are readonly as left side shows current data (which is readonly by default) and right side shows after data (is made readonly explicitly).

**Comment by isidorn** [comment]
@sandy081 I understand that, but why don't you set the content on the model when you create, why are you appliying edits?
Example that seems to work just fine: git showing diff - left hand side is readonly. Why don't you follow the pattern that git is doing?

**Comment by isidorn** [comment]
@sandy081 can you in that case re-create the model?
Otherwise what you want is not a readonly editor since you are applying edits to it.

**Comment by peiblox** [comment]
I've experienced the same problem. The diffs editor doesn't show the changes properly, but when you apply the change, it is done properly. It always changes two more characters than it should.

For example:
`get_header_actions` replace it with `getHeaderActions`

If the code looks like this:
`$this->get_header_actions();` in the diffs editor it shows like `$this->getHeaderActions;`

It lacks the parenthesis in the editor but when you replace it is done properly. It seems to happen randomly.
 
![screenshot-1](https://user-images.githubusercontent.com/16763048/44574902-fc98d500-a78a-11e8-860f-4cd04c865204.png)

![screenshot-2](https://user-images.githubusercontent.com/16763048/44574901-fc003e80-a78a-11e8-8f38-1399325fd565.png)

**Comment by sandy081** [comment]
@isidorn Do you mean I can apply the changes directly onto the model?

**Comment by sandy081** [comment]
Fix:

- Replace preview updates are done directly on the model instead of using BulkEditService
