### ISSUE TITLE
Error when opening explorer context menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5712]
With latest, rightclick into the explorer:

```
index.html:31 Error: [createInstance] RenameFileAction depends on UNKNOWN service progressService.
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:104:27
    at Array.map (native)
    at InstantiationService._createInstance (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:101:51)
    at InstantiationService.createInstance (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:59:29)
    at new TriggerRenameFileAction (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/browser/fileActions.js:149:54)
    at create (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/types.js:150:14)
    at InstantiationService._createInstance (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:130:43)
    at InstantiationService.createInstance (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:59:29)
    at FilesViewerActionContributor.getSecondaryActions (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/browser/fileActions.contribution.js:78:56)
    at FileActionProvider.ContributableActionProvider.getSecondaryActions (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/actionBarRegistry.js:127:61)
```

@jrieken seems like a regression from your changes?

**Comment by jrieken** [comment]
Yep, it needs a @optional decorator. I ran tests and clicked around but it's likely I misses that
