### ISSUE TITLE
VS Code Insider not starting on ubuntu 18.10

### ISSUE THREAD

**Issue by raushankumar27** [Microsoft/vscode#57208]
VS Code Insider not starting on ubuntu 18.10.
got this message from gnome-logs

code-insiders[9606]: segfault at ab6fd0 ip 0000000000ab6fd0 sp 00007ffccb9a80f8 error 15 in code-insiders[200000+1615000]

- VSCode Version:code-insiders_1.27.0-1535087956_amd64
- OS Version:Ubuntu 8.10

Steps to Reproduce:

1. Launch VsCode insider on ubuntu 8.10

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sryze** [comment]
I have the same problem with 1.28.0-1536643513 on Ubuntu 18.10:

```
#0  0x0000000000ab6fd0 in  ()
#1  0x00007ffff7d839a2 in node::http2::Http2Session::Callbacks::Callbacks(bool) () at /usr/share/code-insiders/libnode.so
#2  0x00007ffff7d83a65 in  () at /usr/share/code-insiders/libnode.so
#3  0x00007ffff7fe398a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe138, env=env@entry=0x7fffffffe148)
    at dl-init.c:72
#4  0x00007ffff7fe3a89 in call_init (env=0x7fffffffe148, argv=0x7fffffffe138, argc=1, l=<optimized out>) at dl-init.c:30
#5  0x00007ffff7fe3a89 in _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe138, env=0x7fffffffe148) at dl-init.c:119
#6  0x00007ffff7fd40ca in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in  ()
#8  0x00007fffffffe4f3 in  ()
#9  0x0000000000000000 in  ()
```

I was told by Electron developers that it's because of this bug: https://github.com/electron/electron/issues/13972

**Comment by prantlf** [comment]
code-insiders 1.28.0-1537261834 works on Ubuntu 18.10 from today.
