### ISSUE TITLE
unable to generate a Visual Studio Code Extension using Yeoman

### ISSUE THREAD

**Issue by marcdahan** [Microsoft/vscode#57412]
my package.json :
```

{
  "name": "vscode.extention.1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "marc",
  "license": "ISC",
  "dependencies": {
    "generator-code": "^1.1.37",
    "node": "^8.11.4",
    "yo": "^2.0.5"
  }
}
```
when trying to generate an app, I get this errors . 
```

C:\Users\xxxx\lab\vscode.extention>yo code
C:\Users\xxxx\lab\vscode.extention\node_modules\generator-code\generators\app\index.js:47
    async prompting() {
          ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as code:app] (C:\Users\xxxx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:39:27)
    at Store.get (C:\Users\xxxx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:62:39)
```

thanks for the help

**Comment by veremenko-y** [comment]
I am having the same issue right now.

**Comment by veremenko-y** [comment]
@marcdahan try to upgrade to node 10, it is working there

`generator-code` should refuse to install on incompatible versions

**Comment by marcdahan** [comment]
@veremenko-y thx a lot. Nowadays the 8.11.4 is "recomended for most users".

**Comment by mjbvz** [comment]
Closed as it seemed fixed by using a newer node version
