### ISSUE TITLE
1.26.1 work very slow

### ISSUE THREAD

**Issue by Koljasha** [Microsoft/vscode#57493]
Issue Type: <b>Bug</b>

Dear,
new version 1.26.1 work very slow (Windows, clean install)
1.25.1 was perfectly

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.96GB (0.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --prof-startup|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

![000](https://user-images.githubusercontent.com/17413854/44784722-47ee2180-ab97-11e8-876c-f0f1088848cb.jpg)

**Comment by Koljasha** [comment]
if I run code --prof-startup
create 1 file 2017a - (down) and print:
$ code --prof-startup
[ <1 empty item>,
  [ { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 },
    { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9222 } ] ]

file 2017a:
--inspect-brk=9222|--remote-debugging-port=9223|--inspect-brk-extensions=9224|--prof-startup-prefix|C:\Users\fedorov\207a|--no-cached-data

**Comment by Koljasha** [comment]
And if need:

$ code --status


Version:          Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS Version:       Windows_NT x64 10.0.14393
CPUs:             Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)
Memory (System):  3.96GB (0.77GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Users\f____v\AppData\Local\Programs\Microsoft VS Code\Code.exe
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                unavailable_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       85   13184  code main
    0       62    3492     gpu-process
    0      142    7392     shared-process
    0       24   11240     utility
    0      132   11860     window (Welcome - Visual Studio Code [Administrator])
    0       37    9712       searchService
    0       15   11320       electron-crash-reporter
    0      129   11876       extensionHost

[13752:0829/145442.029:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

**Comment by dbaeumer** [comment]
@jrieken can you help interpreting these numbers.
