### ISSUE TITLE
Flaky test: close editor does not dispose when editor opened in other group

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57661]
Seen a few times:

```
2018-08-31T05:23:34.6191268Z   1) Editor service close editor does not dispose when editor opened in other group (diff input):
2018-08-31T05:23:34.6192759Z      Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
2018-08-31T05:23:34.6194311Z       at _Base.Class.derive._creator.CompletePromise_then [as then] (file:///D:/a/1/s/out-build/vs/base/common/winjs.base.js:1587:49)
```

**Comment by alexandrudima** [comment]
After I've commented this test, the next test has also failed.

```
2018-08-31T14:09:03.0832233Z   4247 passing (50s)
2018-08-31T14:09:03.0982070Z   7 pending
2018-08-31T14:09:03.1251864Z   1 failing
2018-08-31T14:09:03.1252447Z 
2018-08-31T14:09:03.1253273Z   1) Editor service close editor disposes properly (diff input):
2018-08-31T14:09:03.1254603Z      Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
2018-08-31T14:09:03.1256272Z       at _Base.Class.derive._creator.CompletePromise_then [as then] (file:///D:/a/1/s/out-build/vs/base/common/winjs.base.js:1587:49)
2018-08-31T14:09:03.1268775Z 
2018-08-31T14:09:03.1269270Z 

```

**Comment by bpasero** [comment]
I commented out all tests that involve a diff input to see if that makes any difference.

**Comment by bpasero** [comment]
I don't ever want these tests back.
