### ISSUE TITLE
Getting error "Node.js did not repond to request 'continue' in a reasonable amount of time."

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5782]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows10

I observed if user left the VSCode debug session active for a long time and try to resume (I tried around after 12hrs.) then user is unable to proceed with active debug session and keep getting errors like below: LogFile
[NodeJSResponseIssue.zip](https://github.com/Microsoft/vscode/files/235586/NodeJSResponseIssue.zip)

![image](https://cloud.githubusercontent.com/assets/17735796/14801893/f3032df6-0b01-11e6-8a45-3db77d8c8f08.png)

![image](https://cloud.githubusercontent.com/assets/17735796/14801914/22a92a88-0b02-11e6-84c9-86c0743e67e8.png)

Developer tool console:
**
workbench.main.js:90 Node.js did not repond to request 'continue' in a reasonable amount of time.: Error: Node.js did not repond to request 'continue' in a reasonable amount of time.
    at file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:79:16975
    at Object.p [as _notify](file:///C:/Program Files %28x86%29/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:22802)
    at Object.__dirname.undefined.F.enter (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:26130)
    at __dirname.undefined.t.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:27451)
    at __dirname.undefined.t.Class.define._error (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:23:26968)
    at file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:79:12204
    at t.e.dispatch (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:79:13276)
    at t.e.handleData (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:79:12800)
    at Socket.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:79:12070)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)e.doShow @ workbench.main.js:90
**
![nodejsresponseissue](https://cloud.githubusercontent.com/assets/17735796/14801880/c64b92bc-0b01-11e6-95e6-ba35b2838d90.gif)

**Comment by bpasero** [comment]
I do not think this is a scenario that is very common...

**Comment by v-pavanp** [comment]
Initially I though this is related to long active debug session but I am keep getting error like "Node.js did not respond" whenever I am debugging. I tried couple of time after re-launching VSCode.

**Comment by weinand** [comment]
no longer a problem for "inspector" protocol.
