### ISSUE TITLE
"Error processing 'configurationDone' request. Unknown Error: 0x89720010" on dotnet core debugging.

### ISSUE THREAD

**Issue by mentoreet** [Microsoft/vscode#57840]
OS : Windows 10 64bit.
(I'm totally new to open source issue system, so i may writing this on wrong place. So if you feel this is wrong place to talk about this bug, move it please.)

I have searched about the error message and confirmed the 0x89720010 error has resolved.

But i got this error now(today!), so please keep read my post.

I cloned the vs code repository today, and installed all the prerequisites(yarn, python2.7, node, vs2017 community, etc...).

Atfer that, i ran the command 'yarn' and launched vs code by command 'code.bat'

vs code runs fine, so i do some debugging test on dotnet core console project.

with C# for Visual Studio Code extension(installed with vsix, because extension market doesn't works), intellisense works well... but,

when i start debugging with f5 it stop with error "Error processing 'configurationDone' request. Unknown Error: 0x89720010" and chrome debug console displays error log like below,

------------------------------------------

Error processing 'threads' request. Unknown Error: 0x9233000b: Error: Error processing 'threads' request. Unknown Error: 0x9233000b
    at file:///C:/Users/mentoreet/vscode2/out/vs/workbench/parts/debug/electron-browser/rawDebugSession.js:190:119
    at Object.notifyError [as _notify] (file:///C:/Users/mentoreet/vscode2/out/vs/base/common/winjs.base.js:1230:50)
    at Object.enter (file:///C:/Users/mentoreet/vscode2/out/vs/base/common/winjs.base.js:916:30)
    at Promise_ctor._run (file:///C:/Users/mentoreet/vscode2/out/vs/base/common/winjs.base.js:1089:29)
    at Promise_ctor._error (file:///C:/Users/mentoreet/vscode2/out/vs/base/common/winjs.base.js:1062:18)
    at file:///C:/Users/mentoreet/vscode2/out/vs/workbench/parts/debug/electron-browser/rawDebugSession.js:207:25
    at DebugAdapter.AbstractDebugAdapter.acceptMessage (file:///C:/Users/mentoreet/vscode2/out/vs/workbench/parts/debug/node/debugAdapter.js:95:25)
    at DebugAdapter.StreamDebugAdapter.handleData (file:///C:/Users/mentoreet/vscode2/out/vs/workbench/parts/debug/node/debugAdapter.js:148:38)
    at Socket.<anonymous> (file:///C:/Users/mentoreet/vscode2/out/vs/workbench/parts/debug/node/debugAdapter.js:121:64)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

------------------------------------------

I totally have no idea why i got this error.

Could somebody shed some light on this issue please?

Thank you for reading.

**Comment by weinand** [comment]
What debugger are you using?
How does your launch config look like?

**Comment by mentoreet** [comment]
Sorry for lack of information!

I'm trying to using 'coreclr' debug type and my project's launch.json,

-----------------------
- launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/test5.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}

-----------------------

if i missing another information, let me know please.

Thank you.
