### ISSUE TITLE
VS Code not able to start after latest update due to special characters in path

### ISSUE THREAD

**Issue by adiessl** [Microsoft/vscode#58042]
Issue Type: <b>Bug</b>

After updating VS Code to the latest version (1.27.0) I was unable to get it to start properly.

![image](https://user-images.githubusercontent.com/42088160/45139512-44b6ef00-b1b0-11e8-9309-672ae2184334.png)

Starting via command line with the `verbose` flag shows the following error message:

```
PS C:\Users\a.dießl> code --verbose

Error: Failed opening file C:\Users\a.die├ƒl\AppData\Roaming\Code\logs\20180906T083348\main.log for writing: No such file or directory
    at new RotatingLogger (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:231:857)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:547:639
    at Object.v [as _notify] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:85:807)
    at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:89:85)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:90:932)
    at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:90:373)
    at Server.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:174:783)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[main 8:33:48 AM] Starting VS Code
[main 8:33:48 AM] from: c:\Program Files\Microsoft VS Code\resources\app
```

The reason for this seems to be that the path contains a "special" character, in my case the German letter `ß` (`a.die├ƒl` should be `a.dießl`). If I start VS Code via `code --user-data-dir C:\vscode` everything works as expected. This bug is present in VS Code after either using the **system installer** or the **user installer**.

How to reproduce the problem? Maybe create a test folder containing special characters (e.g. `C:\téßt`) and open VS Code via `code --user-data-dir C:\téßt`.
___

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:29:44.670Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.89GB (15.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --user-data-dir C:\vscode|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jibsen** [comment]
Same problem here, my user name contains the Danish character 'ø'.

Is there a way to download the previous version?

**Comment by muhammedtas** [comment]
Same here!

**Comment by joaomoreno** [comment]
/duplicate #57982

**Download** `1.26.1` from here:

- [Windows User Setup x64](https://vscode-update.azurewebsites.net/1.26.1/win32-x64-user/stable)
- [Windows System Setup x64](https://vscode-update.azurewebsites.net/1.26.1/win32-x64/stable)
- [Windows Archive x64](https://vscode-update.azurewebsites.net/1.26.1/win32-x64-archive/stable)
- [Windows User Setup x64](https://vscode-update.azurewebsites.net/1.26.1/win32-user/stable)
- [Windows System Setup x64](https://vscode-update.azurewebsites.net/1.26.1/win32/stable)
- [Windows Archive x64](https://vscode-update.azurewebsites.net/1.26.1/win32-archive/stable)
