### ISSUE TITLE
code itself is listening on port 9000

### ISSUE THREAD

**Issue by korsmakolnikov** [Microsoft/vscode#58045]
- VSCode Version: darwin Versione 1.26.1 (1.26.1)
- OS Version: Mac Os 10.12.6

Steps to Reproduce:

1. Install intelephense PHP and PHP debugger plugins
2. Setup xdebug
3. Start debugger on a php docker project
4. In vscode start listening for incoming xdebug
5. vscode responds with error `listen EADDRINUSE :::9000`
```
{ Error: listen EADDRINUSE :::9000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Promise (/Users/BlackSheep/.vscode/extensions/felixfbecker.php-debug-1.12.5/out/phpDebug.js:240:24)
    at new Promise (<anonymous>)
    at createServer (/Users/BlackSheep/.vscode/extensions/felixfbecker.php-debug-1.12.5/out/phpDebug.js:184:40)
    at PhpDebugSession.<anonymous> (/Users/BlackSheep/.vscode/extensions/felixfbecker.php-debug-1.12.5/out/phpDebug.js:244:27)
    at Generator.next (<anonymous>)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 9000 }
```

This isn't a plugin's issue. Simply vscode has a language server process listening on the port 9000, that has been the xdebug default port for a thousand years. **Yes, this port could be changed but this is not always a chance. In my case I should impose a thousand of devs to change their configuration** that is unacceptable. 

Please reserve port 9000 to other processes.

**Comment by korsmakolnikov** [comment]
This issue is not caused by extension! I've said clearly. You should almost read the whole text of an issue before close it. Actually vscode is avoiding to extension to work properly.

**Comment by majelbstoat** [comment]
@korsmakolnikov I thought the same, but it's not the case, at least not for v1.27.1. I was having a different conflict on port 9000 which went away when closing VSCode. But running with `code --disable-extensions` made the the problem go away.

**Comment by muhamadazmy** [comment]
I had similar issue, i started disabling extensions that I suspect they caused the issue, and it happened to be the `Swagger Viewer` plugin. Check if u have this plugin enabled, or if there another plugin that could have caused this issue.
