### ISSUE TITLE
debug - errors in console

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5824]
#5644
- debugged a C# app that uses Tasks
- found exception in the dev tools console

```
//Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117 
source: property 'sourceReference' is missing: Error: source: property 'sourceReference' is missing
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:17181
    at Object.p [as _notify] (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:22802)
    at Object.__dirname.undefined.F.enter (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:26130)
    at __dirname.undefined.t.Class.define._run (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:27451)
    at __dirname.undefined.t.Class.define._error (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:26968)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:12410
    at t.e.dispatch (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:13482)
    at t.e.handleData (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:13006)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:12276)
    at emitOne (events.js:90:13)e.onUnexpectedError @ //Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117
winjs.base.js:47WARNING: Promise with no error callback:undefined
```

**Comment by isidorn** [comment]
This error is coming from the c# debug adapter, and you are seeing it due to issue #5828.
If you have repro steps you could file it agains the c# debug adapter

**Comment by isidorn** [comment]
Filed https://github.com/OmniSharp/omnisharp-vscode/issues/248

**Comment by gregg-miskelly** [comment]
@isidorn this doesn't sound like a C# extension issue, so I am closing our side.

**Comment by isidorn** [comment]
@gregg-miskelly ok, then I will reopen on our side to investigate

**Comment by isidorn** [comment]
Did not see this again. Closing until I hear more complaints with steps
