### ISSUE TITLE
IPC error on every shutdown

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58305]
Do a search, reload window:

```
  ERR Cannot read property 'trigger' of null: TypeError: Cannot read property 'trigger' of null
log.ts:171
    at Object.onLastListenerRemove (file:///Users/roblou/code/vscode/out/vs/base/parts/ipc/node/ipc.cp.js:107:46)
    at Object.dispose (file:///Users/roblou/code/vscode/out/vs/base/common/event.js:116:56)
    at Object.onLastListenerRemove (file:///Users/roblou/code/vscode/out/vs/base/common/event.js:599:46)
    at Object.dispose (file:///Users/roblou/code/vscode/out/vs/base/common/event.js:116:56)
    at file:///Users/roblou/code/vscode/out/vs/base/common/lifecycle.js:19:56
    at Array.forEach (<anonymous>)
    at Object.dispose (file:///Users/roblou/code/vscode/out/vs/base/common/lifecycle.js:19:19)
    at FileWatcher.dispose (file:///Users/roblou/code/vscode/out/vs/workbench/services/files/node/watcher/nsfw/watcherService.js:89:42)
    at file:///Users/roblou/code/vscode/out/vs/workbench/services/files/node/watcher/nsfw/watcherService.js:62:47
    at Object.dispose (file:///Users/roblou/code/vscode/out/vs/base/common/lifecycle.js:41:41)
    at RemoteFileService.FileService.dispose (file:///Users/roblou/code/vscode/out/vs/workbench/services/files/electron-browser/fileService.js:859:55)
    at Emitter.fire (file:///Users/roblou/code/vscode/out/vs/base/common/event.js:154:41)
    at EventEmitter.<anonymous> (file:///Users/roblou/code/vscode/out/vs/platform/lifecycle/electron-browser/lifecycleService.js:65:35)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
```

**Comment by roblourens** [comment]
Similar

```
TypeError: d.dispose is not a function
    at lifecycle.ts:24
    at Array.forEach (<anonymous>)
    at dispose (lifecycle.ts:24)
    at dispose (lifecycle.ts:34)
    at Set.forEach (<anonymous>)
    at ChildProcess.<anonymous> (ipc.cp.ts:227)
    at emitTwo (events.js:126)
    at ChildProcess.emit (events.js:214)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198)
```
