### ISSUE TITLE
ENOENT: no such file or directory, open 'rendererLog'

### ISSUE THREAD

**Issue by Duracell1989** [Microsoft/vscode#58346]
Issue Type: <b>Bug</b>

The problem exists after upgrading to VS Code 1.27.1
When I try to debug my java code; I get the error that's search for the "rendererLog"-file.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

More info:

> at Object.fs.openSync (fs.js:646:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
	at Object.fs.readFileSync (fs.js:551:33)
	at Object.fs.readFileSync (ELECTRON_ASAR.js:545:29)
	at TrailingSpaces.freezeLastVersion (%userprofile%\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:266:51)
	at %userprofile%\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:56:19
	at e.fire (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at %userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:786:954
	at e.fire (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at e.$acceptDocumentsAndEditorsDelta (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:785:159)
	at e._doInvokeHandler (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at %userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at %userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (%userprofile%\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

**Comment by joaomoreno** [comment]
This is an issue with the shardulm94.trailing-spaces extension, please file an issue in its repository.

**Comment by pzelnip** [comment]
To save people the hassle of Googling, that's this extension: https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces
