### ISSUE TITLE
TypeScript: not fit to cancel requests

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58421]
Seeing this ever since I adopted the cancellation token in quick open (`getWorkspaceSymbols`). Each keystroke can potentially cancel a request now:

```
 ERR Cancelled Request 13: Error: Cancelled Request 13
	at TypeScriptServiceClient.tryCancelRequest (/home/bpasero/development/monaco/extensions/typescript-language-features/out/typescriptServiceClient.js:675:21)
	at dispose_1.Disposable.dispose_1.Disposable.executeImpl.executeInfo.token.onCancellationRequested (/home/bpasero/development/monaco/extensions/typescript-language-features/out/typescriptServiceClient.js:571:30)
	at Emitter.fire (/home/bpasero/development/monaco/out/vs/base/common/event.js:151:38)
	at MutableToken.cancel (/home/bpasero/development/monaco/out/vs/base/common/cancellation.js:45:35)
	at CancellationTokenSource.cancel (/home/bpasero/development/monaco/out/vs/base/common/cancellation.js:102:29)
	at Object.cancel (/home/bpasero/development/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:217:73)
	at RPCProtocol._receiveCancel (/home/bpasero/development/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:250:52)
	at RPCProtocol._receiveOneMessage (/home/bpasero/development/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:171:26)
	at /home/bpasero/development/monaco/out/vs/workbench/services/extensions/node/rpcProtocol.js:89:68
	at /home/bpasero/development/monaco/out/vs/base/common/event.js:456:70
	at Emitter.fire (/home/bpasero/development/monaco/out/vs/base/common/event.js:151:38)
	at acceptChunk (/home/bpasero/development/monaco/out/vs/base/parts/ipc/node/ipc.net.js:104:46)
	at Socket.Protocol.Protocol.firstDataChunk._socketDataListener (/home/bpasero/development/monaco/out/vs/base/parts/ipc/node/ipc.net.js:130:17)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

/cc @jrieken

**Comment by bpasero** [comment]
I have not seen this since.
