### ISSUE TITLE
Failing unit test: WorkspaceContextService - Workspace update folders (remove last and add to end)

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58513]
On Linux

https://dev.azure.com/vscode/VSCode/_build/results?buildId=6856&view=logs

```
2018-09-12T10:13:34.4655839Z   1) WorkspaceContextService - Workspace update folders (remove last and add to end):
2018-09-12T10:13:34.4665317Z 
2018-09-12T10:13:34.4720372Z       AssertionError [ERR_ASSERTION]: false == true
2018-09-12T10:13:34.4747896Z       + expected - actual
2018-09-12T10:13:34.4757052Z 
2018-09-12T10:13:34.4845269Z       -false
2018-09-12T10:13:34.4861517Z       +true
2018-09-12T10:13:34.4949534Z       
2018-09-12T10:13:34.4966923Z       at file:///home/vsts/work/1/s/out/vs/workbench/services/configuration/test/electron-browser/configurationService.test.js:247:24
2018-09-12T10:13:34.4984695Z       at Object.notifySuccess [as _notify] (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1191:59)
2018-09-12T10:13:34.5006658Z       at Object.enter (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-09-12T10:13:34.5115572Z       at Promise_ctor._run (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-09-12T10:13:34.5131100Z       at Promise_ctor._completed (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
2018-09-12T10:13:34.5146493Z       at Object.notifySuccess [as _notify] (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1191:59)
2018-09-12T10:13:34.5162407Z       at Object.enter (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-09-12T10:13:34.5180903Z       at _Base.Class.derive._creator._run (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-09-12T10:13:34.5199435Z       at _Base.Class.derive._creator._completed (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
2018-09-12T10:13:34.5222602Z       at CompletePromise_ctor.CompletePromise_then [as then] (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1587:49)
2018-09-12T10:13:34.5238114Z       at Object.enter (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:762:28)
2018-09-12T10:13:34.5253631Z       at _Base.Class.derive._creator._run (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-09-12T10:13:34.5268959Z       at _Base.Class.derive._creator._setCompleteValue (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1073:18)
2018-09-12T10:13:34.5325489Z       at Object.notifySuccess [as _notify] (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1191:28)
2018-09-12T10:13:34.5343115Z       at Object.enter (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-09-12T10:13:34.5430816Z       at _Base.Class.derive._creator._run (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-09-12T10:13:34.5454365Z       at _Base.Class.derive._creator._completed (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
2018-09-12T10:13:34.5489294Z       at Object.notifySuccess [as _notify] (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1191:59)
2018-09-12T10:13:34.5511384Z       at Object.enter (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:867:30)
2018-09-12T10:13:34.5526926Z       at Promise_ctor._run (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1089:29)
2018-09-12T10:13:34.5542832Z       at Promise_ctor._completed (file:///home/vsts/work/1/s/out/vs/base/common/winjs.base.js:1057:18)
2018-09-12T10:13:34.5558240Z       at file:///home/vsts/work/1/s/out/vs/workbench/services/configuration/node/configuration.js:64:17
2018-09-12T10:13:34.5575210Z       at file:///home/vsts/work/1/s/out/vs/base/node/config.js:148:28
2018-09-12T10:13:34.5591748Z       at file:///home/vsts/work/1/s/out/vs/base/node/config.js:78:24
2018-09-12T10:13:34.5615632Z       at /home/vsts/work/1/s/node_modules/graceful-fs/graceful-fs.js:78:16
2018-09-12T10:13:34.5636424Z       at /home/vsts/work/1/s/node_modules/graceful-fs/graceful-fs.js:78:16
2018-09-12T10:13:34.5653854Z       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by jrieken** [comment]
another one https://dev.azure.com/vscode/VSCode/_build/results?buildId=7764&view=logs
