### ISSUE TITLE
VS Code Insiders will not start if the WiFi adaptor is disabled.

### ISSUE THREAD

**Issue by JeffHanna** [Microsoft/vscode#58830]
Issue Type: <b>Bug</b>

* Put a laptop in Airplane mode or turn off the WiFi adaptor
* Try to start VS Code Insiders.
   * From a desktop icon nothing will happen.
   * From a command prompt the following output will be printed:

C:\Users\#####>code-insiders
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

VS Code version: Code - Insiders 1.28.0-insider (7fcd81cd0f88bb2040f249b09cf6bdd83d9ea2ef, 2018-09-17T09:37:55.086Z)
OS version: Windows_NT x64 10.0.18219

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.46GB free)|
|Process Argv|C:\Users\jeffb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by JeffHanna** [comment]
This appears to be a duplicate of a duplicate. Closing.

**Comment by JeffHanna** [comment]
This appears to be a duplicate of a duplicate. Closing.
