### ISSUE TITLE
'localize' keys must be string literals

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58859]
This is breaking a local build for me, and I actually don't know why the real build isn't broken?

TerminalActions has a localize call with a variable as id: https://github.com/Microsoft/vscode/blob/c7cff3819c1ea2a30675e96f514cef9b80069fb6/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L1201

And these calls get rewritten into another file where that variable doesn't exist.

```
$ yarn run gulp vscode-darwin 
[...]
[18:26:10] Starting 'optimize-vscode'...
out-build/vs/workbench/parts/terminal/electron-browser/terminalActions.nls.keys.js:64
        TERMINAL_COMMAND_ID.TOGGLE_FIND_REGEX,
        ^

ReferenceError: TERMINAL_COMMAND_ID is not defined
    at Object.<anonymous> (out-build/vs/workbench/parts/terminal/electron-browser/terminalActions.nls.keys.js:64:2)
    at NodeScriptLoader._loadAndEvalScript (evalmachine.<anonymous>:801:15)
    at evalmachine.<anonymous>:771:31
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by roblourens** [comment]
Oh, the real build broke, but not CI
