### ISSUE TITLE
VSCode can't launch without arguments

### ISSUE THREAD

**Issue by jeryckho** [Microsoft/vscode#58868]
Issue Type: <b>Bug</b>

Hello.

Since 1.27, by launching VSCode without argument (icon or in cmd.exe "C:\Program Files (x86)\Microsoft VS Code\Code.exe"), the program fail with this error :

````
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'C:\Program Files (x86)\Microsoft VS Code\resources\app\out\main'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\init.js:186:8)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)

[OK]
````

By right clicking a folder, and using "Open with Code", it works...

Have a nice day

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.67GB (8.47GB free)|
|Process Argv|C:\Users\jerome.chery\AppData\Local\Programs\Microsoft VS Code\Code.exe L:\Prj\clusterone-rubedo|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.27.2

</details>

**Comment by bpasero** [comment]
@jeryckho can you try if a full uninstall and reinstall helps?

**Comment by jeryckho** [comment]
Ok, worked for me.

To be noticed, I had to uninstall `Microsoft Visual Studio Code (User) 1.27.2` _**and**_ `Microsoft Visual Studio Code 1.26.0`.
I don't know why 1.26.0 was still installed.
