### ISSUE TITLE
Can not use source control

### ISSUE THREAD

**Issue by StArRy5211** [Microsoft/vscode#58863]
- Extension Name: git
- Extension Version: 1.0.0
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.0-insider
- Git version: 2.7.4
 
![image](https://user-images.githubusercontent.com/10266007/45669037-4ccc4280-bb51-11e8-8c18-9152bee155e6.png)

Source control panel become a blank empty page.

**Comment by octref** [comment]
@StArRy5211 Can you give some more information? For example, what did you do in VS Code? Did you open a folder/workspace, or a single file?

**Comment by StArRy5211** [comment]
I opened a folder. Before yesterday's update, it works fine. I found a error on log output(Window).
![image](https://user-images.githubusercontent.com/10266007/45725215-5b1b6c80-bbec-11e8-8009-d3b9563b3028.png)

**Comment by StArRy5211** [comment]
[2018-09-19 09:06:06.484] [renderer1] [error] Cannot read property 'getLabel' of null: TypeError: Cannot read property 'getLabel' of null
    at i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4898:483)
    at t.renderBody (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4899:651)
    at t.e.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:456:55)
    at t.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4590:853)
    at t.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4897:254)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4909:1000
    at Array.map (<anonymous>)
    at t.onSelectionChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4909:880)
    at t.onDidAddRepository (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4906:705)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:180:133)
    at e.registerSCMProvider (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3878:355)
    at e.$registerSourceControl (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3845:768)
    at t._doInvokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3280:506)
    at t._invokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3280:172)
    at t._receiveRequest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3278:777)
    at t._receiveOneMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3277:703)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3275:553
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:180:113)
    at a (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:316:348)
    at Socket.n._socketDataListener (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:316:567)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

**Comment by joaomoreno** [comment]
Did you install any extensions which modify VS Code's core CSS/Javascript?

**Comment by SEAPUNK** [comment]
I am getting this issue too. Latest VSCode insiders, running Git 2.19.0.

This started happening yesterday for me as well; I did not install/update any new extensions between that time.

Running without extensions seems to make the source panel work again. I'll go through the extension list and see which one is causing problems.

**Comment by SEAPUNK** [comment]
Disabling the vscode-database plugin by `Bajdzis` seems to fix the git panel.

**Comment by ScenK** [comment]
Same issue here. Disabling all the plugins could not work. Reinstalling code-insider still could not make it work.

**Comment by joaomoreno** [comment]
Everyone, please do not comment on other people's issue, when the discussion is already narrowing down to a specific cause. Please create a separate issue.

@StArRy5211 Did you install any extensions which modify VS Code's core CSS/Javascript? Also, can you update Git? That's a pretty old version.

**Comment by thientrung** [comment]
@StArRy5211 
I have same issue. Disable all plugins and enable all again works for me. You can try.
