### ISSUE TITLE
textDocument/hover sends escaped colon after drive letter

### ISSUE THREAD

**Issue by rjmholt** [Microsoft/vscode#58985]
- VSCode Version:
```
1.28.0-insider
29e6dce4352db76d8956035990b8630580226588
x64
```
- OS Version:
```
10.0.18242 N/A Build 18242
```

I work on the PowerShell extension/language service for VSCode, and we have [a bug report](https://github.com/PowerShell/vscode-powershell/issues/1518) where PowerShellEditorServices crashes because we render the wrong path; there's a `#` character in the path and `System.Uri` in C# drops everything after the `#` as a fragment. Easy fix -- we shouldn't escape the path prematurely, but I wondered why it was done in the first place (since it's more effort).

I was working on [the fix PR](https://github.com/PowerShell/PowerShellEditorServices/pull/750#discussion_r218946581) and @SeeminglyScience noticed I haven't escaped the `:` after drive letters in the URIs in the tests. I escape it and everything crashes.

But looking at the [logs](https://github.com/PowerShell/vscode-powershell/files/2361566/Log.zip) I notice that VSCode itself is sending the colon escaped:
```
2018-09-19 09:21:46.574 [DIAGNOSTIC] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs: In method 'ReadMessage', line 114:
    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 18,
      "method": "textDocument/hover",
      "params": {
        "textDocument": {
          "uri": "file:///e%3A/%23Libraries/iCloudDrive/%23%23%23Travail%23%23%23/CurrentWork/Powershell/DSC/EssaiDSC/Validation/DSQ_ITEC_CAIS_TRAITEMENT/DSQ_INSTALL_CAIS_Traitement.ps1"
        },
        "position": {
          "line": 45,
          "character": 34
        }
      }
    }

2018-09-19 09:21:46.574 [VERBOSE] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs: In method 'ReadMessage', line 123:
    Received Request 'textDocument/hover' with id 18

2018-09-19 09:21:46.574 [VERBOSE] C:\PowerShellEditorServices\src\PowerShellEditorServices\Workspace\Workspace.cs: In method 'ResolveFilePath', line 378:
    Resolved path: e:\

2018-09-19 09:21:46.580 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'e:\' is denied.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleHoverRequest>d__41.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'e:\' is denied.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleHoverRequest>d__41.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.Tasks.Task.Execute()<---
    

2018-09-19 09:21:46.580 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: In method 'ProtocolEndpoint_UnhandledException', line 435:
    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.
```

I notice that in the examples I can find of `file://` scheme URIs, the drive letter's colon is never escaped:
- [RFC 8089 - The "file" URI Scheme](https://tools.ietf.org/html/rfc8089#appendix-E.2)
- [IE Blog from 2006 on file URIs](https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/)
- [The Wikipedia article on the file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme)
- [The IETF draft on the file URI scheme](https://tools.ietf.org/id/draft-kerwin-file-scheme-07.html#drive-letters)
- [Various](https://stackoverflow.com/questions/12685797/drive-letter-from-uri-type-file-path-in-c-sharp/12685924) StackOverflow [posts](https://stackoverflow.com/questions/12685797/drive-letter-from-uri-type-file-path-in-c-sharp)

The [only issue I can find on this with VSCode](https://github.com/Microsoft/vscode/issues/2990) is about needing to use the right method on the node `Uri` class to avoid this issue.

But we're seeing this problem in the encoding of a message VSCode itself is sending.

Is this intended behaviour? Is there a standard way to handle this?

**Comment by octref** [comment]
Although I guess the escaping happens in `vscode-languageclient` -> @dbaeumer, still @jrieken FYI.

**Comment by dbaeumer** [comment]
@jrieken assigning to you as our URI expert. I call on the URI I get in the vscode API `toString()` before sending it to the LSP server.

**Comment by dbaeumer** [comment]
Please assign back if there is something you think needs to be done in the LSP client.

**Comment by jrieken** [comment]
This is the design, as we do minimal to none scheme specific encoding. To encode minimal you can use `someUri.toString(true)`. 

@rjmholt How do you use the URI? What library to you use to parse an uri-object from that string? I am asking because escaping too much shouldn't be a problem.

**Comment by rjmholt** [comment]
We're using the URI to resolve a workspace file on the filesystem.

We use .NET's [`System.Uri`](https://docs.microsoft.com/en-au/dotnet/api/system.uri?view=netframework-4.5.1) (I linked to .NET Framework 4.5.1, but we also use .NET Core 2.1 to do the same thing).

`System.Uri` has the following behaviour:
- `new Uri("file:///e%3A/%23Folder/").LocalPath` is `/e:/#Folder/` (**not** a valid location on Windows)
- `new Uri("file:///e:/%23Folder/").LocalPath` is `e:\#Folder\` (a valid Windows path)

If you have a Windows machine, the easiest way to verify this is with PowerShell:
```powershell
> [uri]::new('file:///e%3A/%23Folder/')
AbsolutePath   : /e%3A/%23Folder
AbsoluteUri    : file:///e%3A/%23Folder
LocalPath      : /e:/#Folder
Authority      :
HostNameType   : Basic
IsDefaultPort  : True
IsFile         : True
IsLoopback     : True
PathAndQuery   : /e%3A/%23Folder
Segments       : {/, e%3A/, %23Folder}
IsUnc          : False
Host           :
Port           : -1
Query          :
Fragment       :
Scheme         : file
OriginalString : file:///e%3A/%23Folder
DnsSafeHost    :
IdnHost        :
IsAbsoluteUri  : True
UserEscaped    : False
UserInfo       :
```

[RFC 8089 Appendix E.2](https://tools.ietf.org/html/rfc8089#appendix-E.2) is the best resource I've found that describes the unescaped colon expected for DOS-style paths.

The mismatch between the URI that VSCode sends and the one that `System.Uri` expects means we have to do [special handling](https://github.com/PowerShell/PowerShellEditorServices/blob/3b87e4d1a94c6010801ea7875315d804bbd97751/src/PowerShellEditorServices/Workspace/Workspace.cs#L493-L525) of the URI ourselves (that's in a PR to fix the fact that we used to crash).

**Comment by jrieken** [comment]
> RFC 8089 Appendix E.2 is the best resource I've found that describes the unescaped colon expected for DOS-style paths.

The things is there are so many RFCs that you always find one for whatever point you wanna make. We mostly stick to https://tools.ietf.org/html/rfc3986 which doesn't define any scheme-specific things and actually try to avoid that...

So, from playing with dotnetfiddle it seems that the URI is all happy and can be parsed, no exception or so. The `LocalPath` property seems to be a bit magic as it seems to turn slashes around and it might do other things as well. This is related to our `URI#fsPath` property which we introduced for more or less that reason. Unsure whom to blame here...

<img width="548" alt="screen shot 2018-09-21 at 18 52 50" src="https://user-images.githubusercontent.com/1794099/45894740-95912f00-bdcf-11e8-924a-4724364262f9.png">

**Comment by rjmholt** [comment]
> Unsure whom to blame here...

Honestly, [the RFCs are pretty complex](https://news.ycombinator.com/item?id=17955626) as you say.

> The things is there are so many RFCs that you always find one for whatever point you wanna make.

But the real problem is that .NET (Core and Framework) expect something different to what we receive — and even if we got traction in [corefx](https://github.com/dotnet/corefx) (where we also open the odd issue), it's still this way forever in .NET 451 (and .NET 461, which we're changing to later). In the original issue description I listed a few other references that expect an unescaped colon.

> So, from playing with dotnetfiddle it seems that the URI is all happy and can be parsed, no exception or so.

While true, only the ones with the unescaped colon yield a path from either `LocalPath` or `AbsolutePath` that is valid on Windows and doesn't require further processing. The magic `LocalPath` is [an OS-specific conversion of the URI](https://docs.microsoft.com/en-us/dotnet/api/system.uri.localpath?view=netframework-4.7.2#System_Uri_LocalPath).

At the end of the day, we've handled the issue. In fact, we've handled it so that if this behaviour changes, we're still doing the right thing.

I was surprised that nobody had opened this issue before, but perhaps that means everyone else has adapted. [It looks like Omnisharp does something similar to us](https://github.com/OmniSharp/omnisharp-roslyn/blob/6836fadb9c35a88d4695276d14302336a460b841/src/OmniSharp.LanguageServerProtocol/Helpers.cs#L70-L82) — see https://github.com/OmniSharp/omnisharp-roslyn/issues/1125. [Looks like the Haskell LSP hit this too](https://github.com/alanz/haskell-lsp/pull/53/files). The other language servers I looked at either use the VSCode TypeScript APIs to decode the URI (the [OCaml](https://github.com/freebroccolo/ocaml-language-server/blob/6310438abaaad6b79175e3443e82437d2b91f1cd/src/bin/server/virtual/resource.ts) and [MS C++](https://github.com/Microsoft/vscode-cpptools) LSPs) or seem to handle it properly in the standard library ([Java](https://github.com/eclipse/eclipse.jdt.ls/blob/fc6b40e58808d23a324628a1e79e50f117c534de/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java#L120-L136) (notice the special handling for Windows), [Python](https://github.com/palantir/python-language-server/blob/000993507a1bee471f4ab74f652e11875faed9a4/pyls/uris.py) (although MS's python language server is [written in C#](https://github.com/Microsoft/python-language-server/tree/12fe3b33a18e096b4d51d2b32e8903024f4bfd2e) so might have a similar issue) and [Rust](https://github.com/rust-lang-nursery/rls/blob/3f3877613b58e1b592dde736dbf3dca48db2131a/src/lsp_data.rs#L58-L66) LSPs).

**Comment by dbaeumer** [comment]
@rjmholt there is a way in the LSP client were you can intercept all translations from vscode.URI => string and string => vscode.URI. (see https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L463)

So you could plug in our own converters to overcome this problem for now. But please be aware that this might make the server dependent on running in VS Code.

**Comment by jrieken** [comment]
> But the real problem is that .NET (Core and Framework) expect something different to what we receive 

Acknowledged - lets see what we can do during October. It's not the first time this comes up and the also weird .NET behaviour are reason to change this

**Comment by jrieken** [comment]
I have pushed a fix for this and we will see how well it works, depending on that there is chance that we revert this.

**Comment by rjmholt** [comment]
Thanks @jrieken

**Comment by jrieken** [comment]
It happened: https://github.com/Microsoft/vscode/issues/60163#issuecomment-430287120

**Comment by rjmholt** [comment]
If you want to revert, there's no harm to us (or, I don't think, omnisharp. I looked at the F# extension, but I couldn't find any handling). Stability on this is probably more important -- I don't want to have broken all the other extensions out there.

Ideally this is documented wherever VSCode's message URI format is so that anyone else writing a .NET back end doesn't hit the `System.Uri` difference the hard way. I can provide a PR if you point me to the right document.

Thanks for giving it a shot @jrieken

**Comment by jrieken** [comment]
Not yet reverted. I have pushed a different fix for https://github.com/Microsoft/vscode/issues/60163#issuecomment-430342701 and I am still optimistic :-)
