### ISSUE TITLE
can not run ./scripts/test.sh

### ISSUE THREAD

**Issue by justnull** [Microsoft/vscode#59009]
- VSCode Version: developing version.
- OS Version: ubuntu 18.04 in virtualBox hosted on win10.

Steps to Reproduce:
after "yarn run watch",I had see  "Finished compilation" . but when I run "./scripts/test.sh",
`[13:03:34] Using gulpfile ~/js/vscode/gulpfile.js
[13:03:34] Starting 'clean-electron'...
[13:03:34] Finished 'clean-electron' after 12 ms
[13:03:34] Starting 'electron'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
./scripts/test.sh: line 39: .build/electron/code-oss: No such file or directory
`

**Comment by octref** [comment]
It seems your computer failed to access api.github.com. Try opening https://api.github.com/ in your browser. Does it work?

**Comment by justnull** [comment]
@octref 
![qq 20180921095950](https://user-images.githubusercontent.com/724861/45855975-33134100-bd85-11e8-895c-958fa802e536.png)
still have No such file or directory.
`[09:55:09] Using gulpfile ~/js/vscode/gulpfile.js
[09:55:09] Starting 'clean-electron'...
[09:55:09] Finished 'clean-electron' after 25 ms
[09:55:09] Starting 'electron'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)
./scripts/test.sh: 行 39: .build/electron/code-oss: No such file or directory
`
