### ISSUE TITLE
projectStatus : [Extension Host] TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5900]
Found this running "out of sources" in an VS Code instance without folder opened, opening a *.js file (attached below).

```
threadService.js:141 [Extension Host] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1253:7)
    at /Users/bpasero/Development/Microsoft/monaco/extensions/typescript/out/utils/projectStatus.js:55:40
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

```javascript
/*
  © 2014 by Philipp Dunkel <pip@pipobscure.com>
  Licensed under MIT License.
 */

/* jshint node:true */
'use strict';

var fs = require('fs');
var path = require('path');
var test = require('tap').test;

test('functionality testing', function(t) {
  try {
    fs.mkdirSync(__dirname + '/temp');
  } catch (ex) {}
  var evt = require('../')(__dirname + '/temp').start();
  t.on('end', function() {
    evt.stop();
  });
  t.plan(16);

  evt.on('fsevent', function(name, flags, id) {
    console.error("id:\t" + id);
    console.error("flags:\t" + JSON.stringify(flags));
    if (name === __dirname + '/temp') return;
    if (path.basename(name) === 'created-fsevent') {
      t.ok('number' === typeof flags, 'created file was caught with flags:' + flags);
      t.ok('number' === typeof id, 'id is a number ' + id);
    }
    if (path.basename(name) === 'moved-fsevent') {
      t.ok('number' === typeof flags, 'renamed file was caught with flags:' + flags);
      t.ok('number' === typeof id, 'id is a number ' + id);
    }
  });

  evt.on('change', function(name, info) {
    console.error("name:\t" + name);
    console.error("base:\t" + path.basename(name));
    console.error("event:\t" + info.event);
    console.error("info:\t" + JSON.stringify(info));
    if (name === __dirname + '/temp') return;
    t.ok(name === info.path, 'matched path');
    switch (info.event) {
      case 'created':
        t.ok(path.basename(name) === 'created-fsevent', 'file created: ' + path.basename(name));
        break;
      case 'moved-out':
        t.ok(path.basename(name) === 'created-fsevent', 'file moved out: ' + path.basename(name));
        break;
      case 'moved-in':
        t.ok(path.basename(name) === 'moved-fsevent', 'file moved in: ' + path.basename(name));
        break;
      case 'deleted':
        t.ok(path.basename(name) === 'moved-fsevent', 'file deleted: ' + path.basename(name));
        break;
    }
  });

  setTimeout(function() {
    console.error("===========================================================================");
    console.error("\twriteFileSync(__dirname + '/temp/created-fsevent', 'created-fsevent');");
    fs.writeFileSync(__dirname + '/temp/created-fsevent', 'created-fsevent');

    console.error("===========================================================================");
  }, 5000);
  setTimeout(function() {
    console.error("===========================================================================");
    console.error("\trenameSync(__dirname + '/temp/created-fsevent', __dirname + '/temp/moved-fsevent');");
    fs.renameSync(__dirname + '/temp/created-fsevent', __dirname + '/temp/moved-fsevent');

    console.error("===========================================================================");

  }, 10000);
  setTimeout(function() {
    console.error("===========================================================================");
    console.error("\tunlinkSync(__dirname + '/temp/moved-fsevent');");
    fs.unlinkSync(__dirname + '/temp/moved-fsevent');
    console.error("===========================================================================");
  }, 15000);
  setTimeout(function() {
    console.error("===========================================================================");
    console.error("\trmdirSync(__dirname + '/temp');");
    fs.rmdirSync(__dirname + '/temp');
    console.error("===========================================================================");
  }, 20000);
});
```

![image](https://cloud.githubusercontent.com/assets/900690/14859006/95f0d38c-0ca2-11e6-837a-e70ff51cedc6.png)

**Comment by jrieken** [comment]
happens when you run with only a file not a folder open
