### ISSUE TITLE
Gulp Build on Windows: "ModuleDependencyWarning: Critical dependency"

### ISSUE THREAD

**Issue by WilliamABradley** [Microsoft/vscode#59219]
VSCode Version: git master
OS Version: Windows 10 Pro 1809 17751.1 x64

Error Step:
```
git clean -xfd
yarn
npm run gulp -- vscode-win32-x64-min
```

This consistently occurs every time the git folder is cleaned.

Output:
```
[21:32:47] Node flags detected: --max_old_space_size=4095
[21:32:47] Respawned to PID: 24544
[21:32:51] Using gulpfile C:\Programming\Github\vscode\gulpfile.js
[21:32:51] Starting 'clean-minified-vscode'...
[21:32:51] Starting 'clean-optimized-vscode'...
[21:32:51] Starting 'clean-client-build'...
[21:32:51] Starting 'clean-extension:configuration-editing'...
[21:32:51] Starting 'clean-extension:css-language-features-client'...
[21:32:51] Starting 'clean-extension:css-language-features-server'...
[21:32:51] Starting 'clean-extension:debug-auto-launch'...
[21:32:51] Starting 'clean-extension:emmet'...
[21:32:51] Starting 'clean-extension:extension-editing'...
[21:32:51] Starting 'clean-extension:git'...
[21:32:51] Starting 'clean-extension:grunt'...
[21:32:51] Starting 'clean-extension:gulp'...
[21:32:51] Starting 'clean-extension:html-language-features-client'...
[21:32:51] Starting 'clean-extension:html-language-features-server'...
[21:32:51] Starting 'clean-extension:jake'...
[21:32:51] Starting 'clean-extension:json-language-features-client'...
[21:32:51] Starting 'clean-extension:json-language-features-server'...
[21:32:51] Starting 'clean-extension:markdown-language-features-preview-src'...
[21:32:51] Starting 'clean-extension:markdown-language-features'...
[21:32:51] Starting 'clean-extension:merge-conflict'...
[21:32:51] Starting 'clean-extension:npm'...
[21:32:51] Starting 'clean-extension:php-language-features'...
[21:32:51] Starting 'clean-extension:python'...
[21:32:51] Starting 'clean-extension:search-rg'...
[21:32:51] Starting 'clean-extension:typescript-basics-test-colorize-fixtures'...
[21:32:51] Starting 'clean-extension:typescript-language-features'...
[21:32:51] Starting 'clean-extension:vscode-api-tests'...
[21:32:51] Starting 'clean-extension:vscode-colorize-tests'...
[21:32:51] Starting 'clean-vscode-win32-x64'...
[21:32:51] Finished 'clean-minified-vscode' after 14 ms
[21:32:51] Finished 'clean-optimized-vscode' after 13 ms
[21:32:51] Finished 'clean-client-build' after 13 ms
[21:32:51] Starting 'compile-client-build'...
[21:32:51] Starting compilation...
[21:32:51] Finished 'clean-extension:configuration-editing' after 30 ms
[21:32:51] Starting 'compile-extension-build:configuration-editing'...
[21:32:51] Finished 'clean-extension:css-language-features-client' after 34 ms
[21:32:51] Starting 'compile-extension-build:css-language-features-client'...
[21:32:51] Finished 'clean-extension:css-language-features-server' after 36 ms
[21:32:51] Starting 'compile-extension-build:css-language-features-server'...
[21:32:51] Finished 'clean-extension:debug-auto-launch' after 38 ms
[21:32:51] Starting 'compile-extension-build:debug-auto-launch'...
[21:32:51] Finished 'clean-extension:emmet' after 40 ms
[21:32:51] Starting 'compile-extension-build:emmet'...
[21:32:51] Finished 'clean-extension:extension-editing' after 41 ms
[21:32:51] Starting 'compile-extension-build:extension-editing'...
[21:32:51] Finished 'clean-extension:git' after 43 ms
[21:32:51] Starting 'compile-extension-build:git'...
[21:32:52] Finished 'clean-extension:grunt' after 44 ms
[21:32:52] Starting 'compile-extension-build:grunt'...
[21:32:52] Finished 'clean-extension:gulp' after 45 ms
[21:32:52] Starting 'compile-extension-build:gulp'...
[21:32:52] Finished 'clean-extension:html-language-features-client' after 46 ms
[21:32:52] Starting 'compile-extension-build:html-language-features-client'...
[21:32:52] Finished 'clean-extension:html-language-features-server' after 47 ms
[21:32:52] Starting 'compile-extension-build:html-language-features-server'...
[21:32:52] Finished 'clean-extension:jake' after 48 ms
[21:32:52] Starting 'compile-extension-build:jake'...
[21:32:52] Finished 'clean-extension:json-language-features-client' after 50 ms
[21:32:52] Starting 'compile-extension-build:json-language-features-client'...
[21:32:52] Finished 'clean-extension:json-language-features-server' after 51 ms
[21:32:52] Starting 'compile-extension-build:json-language-features-server'...
[21:32:52] Finished 'clean-extension:markdown-language-features-preview-src' after 52 ms
[21:32:52] Starting 'compile-extension-build:markdown-language-features-preview-src'...
[21:32:52] Finished 'clean-extension:markdown-language-features' after 53 ms
[21:32:52] Starting 'compile-extension-build:markdown-language-features'...
[21:32:52] Finished 'clean-extension:merge-conflict' after 56 ms
[21:32:52] Starting 'compile-extension-build:merge-conflict'...
[21:32:52] Finished 'clean-extension:npm' after 58 ms
[21:32:52] Starting 'compile-extension-build:npm'...
[21:32:52] Finished 'clean-extension:php-language-features' after 59 ms
[21:32:52] Starting 'compile-extension-build:php-language-features'...
[21:32:52] Finished 'clean-extension:python' after 61 ms
[21:32:52] Starting 'compile-extension-build:python'...
[21:32:52] Finished 'clean-extension:search-rg' after 62 ms
[21:32:52] Starting 'compile-extension-build:search-rg'...
[21:32:52] Finished 'clean-extension:typescript-basics-test-colorize-fixtures' after 65 ms
[21:32:52] Starting 'compile-extension-build:typescript-basics-test-colorize-fixtures'...
[21:32:52] Finished 'clean-extension:typescript-language-features' after 66 ms
[21:32:52] Starting 'compile-extension-build:typescript-language-features'...
[21:32:52] Finished 'clean-extension:vscode-api-tests' after 68 ms
[21:32:52] Starting 'compile-extension-build:vscode-api-tests'...
[21:32:52] Finished 'clean-extension:vscode-colorize-tests' after 69 ms
[21:32:52] Starting 'compile-extension-build:vscode-colorize-tests'...
[21:32:52] Finished 'compile-extension-build:markdown-language-features-preview-src' after 39 ms
[21:32:52] Finished 'compile-extension-build:typescript-basics-test-colorize-fixtures' after 24 ms
[21:32:58] Finished 'compile-extension-build:python' after 6.05 s
[21:32:58] Finished 'clean-vscode-win32-x64' after 6.53 s
[21:32:58] Finished 'compile-extension-build:debug-auto-launch' after 6.62 s
[21:32:58] Finished 'compile-extension-build:grunt' after 6.61 s
[21:32:58] Finished 'compile-extension-build:css-language-features-client' after 6.62 s
[21:32:58] Finished 'compile-extension-build:gulp' after 6.61 s
[21:32:58] Finished 'compile-extension-build:jake' after 6.61 s
[21:32:58] Finished 'compile-extension-build:vscode-colorize-tests' after 6.6 s
[21:32:59] Finished 'compile-extension-build:configuration-editing' after 7.88 s
[21:32:59] Finished 'compile-extension-build:json-language-features-client' after 7.86 s
[21:33:01] Finished 'compile-extension-build:html-language-features-client' after 9.83 s
[21:33:01] Finished 'compile-extension-build:json-language-features-server' after 9.82 s
[21:33:01] Finished 'compile-extension-build:extension-editing' after 9.83 s
[21:33:01] Finished 'compile-extension-build:css-language-features-server' after 9.87 s
[21:33:03] Finished 'compile-extension-build:search-rg' after 12 s
[21:33:04] Finished 'compile-extension-build:npm' after 13 s
[21:33:05] Finished 'compile-extension-build:php-language-features' after 14 s
[21:33:06] Finished 'compile-extension-build:merge-conflict' after 15 s
[21:33:06] Finished 'compile-extension-build:vscode-api-tests' after 15 s
[21:33:07] Finished 'compile-extension-build:git' after 15 s
[21:33:08] Finished 'compile-extension-build:html-language-features-server' after 17 s
[21:33:08] Finished 'compile-extension-build:emmet' after 17 s
[21:33:08] Finished 'compile-extension-build:markdown-language-features' after 17 s
[21:33:08] Finished 'compile-extension-build:typescript-language-features' after 17 s
[21:33:08] Starting 'compile-extensions-build'...
[21:33:08] Finished 'compile-extensions-build' after 31 μs
[21:34:17] [monaco.d.ts] Starting monaco.d.ts generation
[21:34:19] [monaco.d.ts] Finished monaco.d.ts generation
[21:34:19] Finished compilation with 0 errors after 87224 ms
[21:34:19] Finished 'compile-client-build' after 1.45 min
[21:34:19] Starting 'compile-build'...
[21:34:19] Finished 'compile-build' after 2.5 μs
[21:34:19] Starting 'optimize-vscode'...
CSS INLINING IMAGE AT out-build\vs\base\browser\ui\menu\submenu.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\base\browser\ui\menu\check.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\colorPicker\images\opacity-background.png MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\BooleanData_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\BooleanData_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Field_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Field_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Method_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Method_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Method_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Method_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Namespace_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Namespace_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Namespace_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Namespace_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Namespace_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\Namespace_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\String_16x.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\documentSymbols\media\String_16x_darkp.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\find\images\previous.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\find\images\next.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\find\images\close.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\find\images\previous-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\find\images\next-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\editor\contrib\find\images\close-dark.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-dirty.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-dirty-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\notifications\media\down-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\notifications\media\down.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\comments\electron-browser\media\comment.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\current-arrow.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\start.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\continue-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\start.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\extensions\electron-browser\media\loading.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\extensions\electron-browser\media\profile-stop.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\feedback\electron-browser\media\info.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\preferences\browser\media\edit.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\preferences\browser\media\edit_inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\preferences\browser\media\info.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\preferences\browser\media\edit.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\preferences\browser\media\edit_inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\welcome\code-icon.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
[21:34:41] Finished 'optimize-vscode' after 22 s
[21:34:41] Starting 'optimize-index-js'...
[21:34:41] Finished 'optimize-index-js' after 744 μs
[21:34:41] Starting 'minify-vscode'...
[21:36:38] Finished 'minify-vscode' after 1.95 min
[21:36:38] Starting 'vscode-win32-x64-min'...
[21:36:39] Downloading extension: ms-vscode.node-debug@1.28.2 ...
[21:36:39] Downloading extension: ms-vscode.node-debug2@1.28.2 ...
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
[21:37:33] Bundled extension: search-rg\extension.webpack.config.js...
[21:37:33] Bundled extension: gulp\extension.webpack.config.js...
[21:37:33] Bundled extension: grunt\extension.webpack.config.js...
[21:37:33] Bundled extension: debug-auto-launch\extension.webpack.config.js...
[21:37:33] Bundled extension: jake\extension.webpack.config.js...
[21:37:34] Bundled extension: configuration-editing\extension.webpack.config.js...
[21:37:34] Bundled extension: php-language-features\extension.webpack.config.js...
[21:37:35] Bundled extension: merge-conflict\extension.webpack.config.js...
[21:37:40] Bundled extension: emmet\extension.webpack.config.js...
[21:37:43] Bundled extension: css-language-features\server\extension.webpack.config.js...
[21:37:44] Bundled extension: css-language-features\extension.webpack.config.js...
[21:37:46] Bundled extension: extension-editing\extension.webpack.config.js...
[21:37:46] Bundled extension: json-language-features\extension.webpack.config.js...

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.28.0 gulp: `gulp --max_old_space_size=4095 "vscode-win32-x64-min"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-oss-dev@1.28.0 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Willi\AppData\Roaming\npm-cache\_logs\2018-09-24T09_37_47_234Z-debug.log
```

**Comment by joaomoreno** [comment]
> ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression

Is this webpack?

**Comment by WilliamABradley** [comment]
@joaomoreno I think so, yes

**Comment by WilliamABradley** [comment]
@aeschli I am using Yarn 1.7.0

**Comment by WilliamABradley** [comment]
I will update my yarn to the latest stable and try again.

**Comment by WilliamABradley** [comment]
@aeschli updating Yarn to 1.9.4 fixed the issue, and this works now, however, I still get the message about failed to parse dependency applicationinsights.

**Comment by WilliamABradley** [comment]
ApplicationInsights seems to still cause issues, and I can't reliably build `vscode-win32-ia32-min` and `vscode-win32-x64-min` together, as  is needed to make a multi-architecture package.

```
[01:29:08] Downloading extension: ms-vscode.node-debug2@1.28.2 ...
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
Failed to parse dependency: applicationinsights@git://github.com/Microsoft/ApplicationInsights-node.js#e5160c1c29c00e430d414b381077212d4e5bd8b4
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.28.0 gulp: `gulp --max_old_space_size=4095 "vscode-winstore-x64-devsign"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-oss-dev@1.28.0 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Willi\AppData\Roaming\npm-cache\_logs\2018-09-25T13_29_49_266Z-debug.log
```

**Comment by aeschli** [comment]
Yes, I'm also seeing this. Not clear if it is related to the appinsights package.
Working on it.
