### ISSUE TITLE
Search breaks when keybindings editor is open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#59293]
- Open keybindings editor
- Search in search viewlet
- Spins forever

```
TypeError: Cannot read property 'toString' of null
errors.ts:51
    at EditorService.doGetOpened (file:///Users/roblou/code/vscode/out/vs/workbench/services/editor/browser/editorService.js:374:38)
    at EditorService.isOpen (file:///Users/roblou/code/vscode/out/vs/workbench/services/editor/browser/editorService.js:335:27)
    at file:///Users/roblou/code/vscode/out/vs/workbench/services/search/node/searchService.js:298:46
    at Array.forEach (<anonymous>)
    at SearchService.getLocalResults (file:///Users/roblou/code/vscode/out/vs/workbench/services/search/node/searchService.js:293:24)
    at SearchService.search (file:///Users/roblou/code/vscode/out/vs/workbench/services/search/node/searchService.js:97:37)
    at SearchModel.search (file:///Users/roblou/code/vscode/out/vs/workbench/parts/search/common/searchModel.js:743:53)
    at SearchView.onQueryTriggered (file:///Users/roblou/code/vscode/out/vs/workbench/parts/search/browser/searchView.js:1095:28)
    at file:///Users/roblou/code/vscode/out/vs/workbench/parts/search/browser/searchView.js:886:23
```

Looks like `resource` can be null here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/editor/browser/editorService.ts#L422

This breaks smoketests too https://dev.azure.com/vscode/VSCode/_build/results?buildId=7711&view=logs

**Comment by bpasero** [comment]
Good catch.
