### ISSUE TITLE
Failed to install extension

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#59429]
I tried to install an extension (`zignd.html-css-class-completion`) and got this error. It worked the second time. 

Maybe this is just a weird fluke but in case it's helpful at all, here's a stack...

```
TypeError: Cannot read property 'identifier' of undefined
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3868:856
    at Array.filter (<anonymous>)
    at e.checkAndEnableDisabledDependencies (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3868:800)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3867:500
    at Object.g [as _notify] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:729)
    at Object.enter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:163:61)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:164:902)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:164:343)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sandy081** [comment]
It's a timing issue and hard to repro. Please try installing above extension multiple times and make sure you do not see this error.

**Comment by octref** [comment]
@sandy081 I don't think that would repro this case, because you added mechanism to not really delete an extension for uninstall, so you can bring it back instantly when reinstalling. Correct?

**Comment by sandy081** [comment]
@octref This is nothing to do with removing the extension from disk or not. Its purely a communication timing issue between renderer and shared process. I can explain to you if wanted. 

But I think your way of verification is also sufficient.
