### ISSUE TITLE
Cannot read property 'lineNumber' of null

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#59451]
1. Have the follwoing program
```javascript
console.log('hello')
debugger
```
2. Hover over console -> you get a debug hover, now put the mouse over the debug hover
3. Notice error in console

```
Cannot read property 'lineNumber' of null: TypeError: Cannot read property 'lineNumber' of null
	at Object.to (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostTypeConverters.js:66:48)
	at HoverAdapter.provideHover (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:170:44)
	at /Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:852:96
	at ExtHostLanguageFeatures._withAdapter (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:784:20)
	at ExtHostLanguageFeatures.$provideHover (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostLanguageFeatures.js:852:25)
	at RPCProtocol._doInvokeHandler (/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:391:27)
	at RPCProtocol._invokeHandler (/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:376:54)
	at RPCProtocol._receiveRequest (/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:300:32)
	at RPCProtocol._receiveOneMessage (/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:235:26)
	at /Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/rpcProtocol.js:114:69
	at /Users/isidor/Development/vscode/out/vs/base/common/event.js:456:70
	at Emitter.fire (/Users/isidor/Development/vscode/out/vs/base/common/event.js:151:38)
	at acceptChunk (/Users/isidor/Development/vscode/out/vs/base/parts/ipc/node/ipc.net.js:104:46)
	at Socket.Protocol.Protocol.firstDataChunk._socketDataListener (/Users/isidor/Development/vscode/out/vs/base/parts/ipc/node/ipc.net.js:130:17)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

Note that I am properly returing a position in my debugHover [here](https://github.com/Microsoft/vscode/blob/bac5061d612db24bb99bb03c7f272d40f1f40306/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L288) 
@jrieken might you have the clue what is the issue here

**Comment by jrieken** [comment]
@isidorn this means someone requests the hover without providing a position. I am pretty sure this is debugging itself, via this https://github.com/Microsoft/vscode/blob/200d30e467f9020cc2de8c5cbb2cb2c1fd1831ce/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L418

**Comment by isidorn** [comment]
@jrieken thanks! You were correct I was wrongly requesting the hover
