### ISSUE TITLE
VS Code Fails to Launch

### ISSUE THREAD

**Issue by manbearian** [Microsoft/vscode#59477]
- VSCode Version: 1.26.1
- OS Version: Windows 10 18247.rl_lkg.180922-1650

Steps to Reproduce:

1. run code.cmd
2.

Does this issue occur when all extensions are disabled?: Unknown, as I cannot launch VS code

C:\Users\ianb>code -v
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

**Comment by manbearian** [comment]
Thank you. I was able to uninstall and reinstall to work around the problem. This is the second time ive managed to get vs code into this state.

Ian


-------- Original message --------
