### ISSUE TITLE
Regression? Integration tests fail on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#5948]
* Run `scripts\test-integration.bat`

`openTextDocument, untitled closes on save` fails. Git blame shows you were editing there last. I will file a separate issue for the second test failure `applyEdit`.

```
 1) workspace-namespace openTextDocument, untitled closes on save:
     Error: the string "cannot open untitled://c:\\alex\\src\\vscode\\extensions\\vscode-api-tests\\testworkspace\\newfile.txt. Detail: file already exists on disk" was thrown, throw an Error :)
      at Runner.fail (c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runner.js:226:11)
      at c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runner.js:549:18
      at done (c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runnable.js:276:5)
      at c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runnable.js:326:11
      at Object.notifyError [as _notify] (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1470:50)
      at Object.state_error_notify.enter (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1176:30)
      at WinJS.Class.define._run (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1343:29)
      at WinJS.Class.define._chainedError (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1306:18)
      at state_waiting.enter.error (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1012:29)
      at ErrorPromise_ctor.ErrorPromise_then [as then] (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1694:50)

  2) workspace-namespace applyEdit:
     Error: the string "cannot open untitled://c:\\alex\\src\\vscode\\extensions\\vscode-api-tests\\testworkspace\\new2.txt. Detail: file already exists on disk" was thrown, throw an Error :)
      at Runner.fail (c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runner.js:226:11)
      at c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runner.js:549:18
      at done (c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runnable.js:276:5)
      at c:\Alex\src\vscode\extensions\vscode-api-tests\node_modules\mocha\lib\runnable.js:326:11
      at Object.notifyError [as _notify] (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1470:50)
      at Object.state_error_notify.enter (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1176:30)
      at WinJS.Class.define._run (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1343:29)
      at WinJS.Class.define._chainedError (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1306:18)
      at state_waiting.enter.error (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1012:29)
      at ErrorPromise_ctor.ErrorPromise_then [as then] (c:\Alex\src\vscode\out\vs\base\common\winjs.base.raw.js:1694:50)

```

**Comment by alexandrudima** [comment]
Sister issue #5949

**Comment by alexandrudima** [comment]
Looks like @jrieken fixed this test.

**Comment by bpasero** [comment]
Nice 👍
