### ISSUE TITLE
vscode seg-faults after upgrade to Fedora 29 beta (Gnome 3.30?)

### ISSUE THREAD

**Issue by mykaul** [Microsoft/vscode#59526]
- VSCode Version: code-1.27.2-1536736788.el7.x86_64
- OS Version: Fedora 29 beta.

Steps to Reproduce:
Launch vscode.

```
Sep 27 10:25:47 ykaul.tlv.redhat.com systemd-coredump[17248]: Process 17246 (code) of user 1000 dumped core.
                                                              
                                                              Stack trace of thread 17246:
                                                              #0  0x0000000000ab6fd0 n/a (code)
Sep 27 10:25:47 ykaul.tlv.redhat.com audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-17247-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 27 10:25:47 ykaul.tlv.redhat.com systemd[1]: Started Process Core Dump (PID 17247/UID 0).
Sep 27 10:25:47 ykaul.tlv.redhat.com kernel: Code: 18 06 03 55 04 0a 13 11 57 6f 53 69 67 6e 20 43 41 20 4c 69 6d 69 74 65 64 31 2a 30 28 06 03 55 04 03 13 21 43 65 72 74 69 66 <69> 63 61 74 69 6f 6e 20 41 75 74 68 6f 72 69 74 79 20 6f 66 20 57 
Sep 27 10:25:47 ykaul.tlv.redhat.com kernel: code[17246]: segfault at ab6fd0 ip 0000000000ab6fd0 sp 00007fff0ab4cf98 error 15 in code[200000+1615000]
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mykaul** [comment]
Running with gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000ab6fd0 in ?? ()
(gdb) bt
#0  0x0000000000ab6fd0 in  ()
#1  0x00007ffff7d829a2 in node::http2::Http2Session::Callbacks::Callbacks(bool) () at /usr/share/code/libnode.so
#2  0x00007ffff7d82a65 in  () at /usr/share/code/libnode.so
#3  0x00007ffff7fe1cea in call_init.part () at /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7fe1dea in _dl_init () at /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7fd314a in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#6  0x0000000000000001 in  ()
#7  0x00007fffffffd83d in  ()
#8  0x0000000000000000 in  ()
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mykaul** [comment]
Same result, using 1.28.0-1538026054.el7
```
[ykaul@ykaul ovirt-system-tests]$ gdb /usr/share/code/code 
GNU gdb (GDB) Fedora 8.2-2.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/share/code/code...(no debugging symbols found)...done.
Missing separate debuginfos, use: dnf debuginfo-install code-1.27.2-1536736788.el7.x86_64
(gdb) r
Starting program: /usr/share/code/code 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments

Program received signal SIGSEGV, Segmentation fault.
0x0000000000ab6fd0 in ?? ()
(gdb) bt
#0  0x0000000000ab6fd0 in  ()
#1  0x00007ffff7d829a2 in node::http2::Http2Session::Callbacks::Callbacks(bool) () at /usr/share/code/libnode.so
#2  0x00007ffff7d82a65 in  () at /usr/share/code/libnode.so
#3  0x00007ffff7fe1cea in call_init.part () at /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7fe1dea in _dl_init () at /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7fd314a in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#6  0x0000000000000001 in  ()
#7  0x00007fffffffd841 in  ()
#8  0x0000000000000000 in  ()
(gdb) 
```

**Comment by dralley** [comment]
Do you know when the patch will be released via the standard channels?

**Comment by dralley** [comment]
@bpasero Do you know when the patch will be released via the standard channels?
