### ISSUE TITLE
Alt+Click on a link in hover is opening workbench html 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#59538]
Alt+Click on a link in hover is opening workbench html

**Comment by jrieken** [comment]
@san Did this change make it that insiders?

**Comment by sandy081** [comment]
I checked it and the above build with version b4d09d27509f2c023f63d4315aa966a5ec7581e9 contains it.

**Comment by sandy081** [comment]
I still see it in latest insiders.

**Comment by jrieken** [comment]
Yeah, holy smokes me too

**Comment by jrieken** [comment]
Ok, problem is that `#Foo` isn't a valid link and that calling `URI#parse` throws an error. That makes us never call preventDefault...

**Comment by jrieken** [comment]
@sandy081  please review https://github.com/Microsoft/vscode/pull/59598

**Comment by alexr00** [comment]
It looks like there's still something wrong with links in hover text. I clicked on the same link in `showErrorMessage` and nothing appeared to happen. In the console there is an error:

    ** ERR [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: "window.showInformationMessage"}: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: "window.showInformationMessage"}
    at file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:125:506
    at t.e (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:126:340)
    at new t (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:127:895)
    at Function.e.parse (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:127:155)
    at Object.callback (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1443:748)
    at file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:253:376
    at HTMLDivElement.<anonymous> (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:211:292)**

It's not opening workbench html anymore though.

**Comment by jrieken** [comment]
Yeah, the error is to be expected and tracked here https://github.com/Microsoft/vscode/issues/59469
