### ISSUE TITLE
Crashes on launch and leaves an empty window

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#59752]
Issue Type: <b>Bug</b>

I've gotten myself into a strange issue. I was debugging an extension and messing around with the grid layout and I ended up somehow causing an error when trying to close an empty editor group. Ever since then anytime I try to debug an extension it opens the shell of a vscode window, but quickly opens the devtools with the output below. And the vscode window never loads, its just a dead blank window. My guess (and hope) is that if I clear the local storage for that window it will be fixed. EDIT: Clearing the state for that workspace fixed the issue.

EDIT: If it helps here is my `editorpart.state`:
```
{"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":5,"editors":[],"mru":[]},"size":394}],"size":723},"orientation":1,"width":614,"height":723},"activeGroup":6,"mostRecentActiveGroups":[6,5]}
```

```
  ERR Cannot read property 'focus' of undefined: TypeError: Cannot read property 'focus' of undefined
    at t.doCreateGridControlWithPreviousState (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5048:161)
    at t.doCreateGridControl (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5047:527)
    at t.createContentArea (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5046:965)
    at t.create (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2503:990)
    at t.createEditorPart (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5490:18)
    at t.renderWorkbench (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5488:809)
    at t.startup (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5469:380)
    at t.createWorkbench (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5523:790)
    at t.renderContents (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5523:205)
    at t.open (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5531:449)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5538:808
    at Object.g [as _notify] (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._oncancel._run (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._completed (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:165:343)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
bootstrap-window.js:195 [uncaught exception]: TypeError: Cannot read property 'focus' of undefined
onUnexpectedError @ bootstrap-window.js:195
bootstrap-window.js:198 TypeError: Cannot read property 'focus' of undefined
    at t.doCreateGridControlWithPreviousState (editorPart.ts:832)
    at t.doCreateGridControl (editorPart.ts:802)
    at t.createContentArea (editorPart.ts:780)
    at t.create (part.ts:53)
    at t.createEditorPart (workbench.ts:1062)
    at t.renderWorkbench (workbench.ts:1018)
    at t.startup (workbench.ts:281)
    at t.createWorkbench (shell.ts:201)
    at t.renderContents (shell.ts:168)
    at t.open (shell.ts:467)
    at main.ts:119
    at Object.g [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1089)
    at n.Class.derive._oncancel._completed (winjs.base.js:1057)
    at runCallback (timers.js:789)
    at tryOnImmediate (timers.js:751)
    at processImmediate [as _immediateCallback] (timers.js:722)
onUnexpectedError @ bootstrap-window.js:198
extensionService.ts:1010 Loading development extension at c:\Users\Eric\code\vscode-gitlens
mime.ts:62 Overwriting filename <<.gitignore>> to now point to mime <<text/x-gitignore>>
(anonymous) @ mime.ts:62
o @ mime.ts:52
e._mergeLanguage @ languagesRegistry.ts:134
e._registerLanguage @ languagesRegistry.ts:107
e._registerLanguages @ languagesRegistry.ts:63
(anonymous) @ languagesRegistry.ts:53
e.fire @ event.ts:140
e.registerLanguages @ modesRegistry.ts:38
(anonymous) @ workbenchModeService.ts:138
e._handle @ extensionsRegistry.ts:115
e.acceptUsers @ extensionsRegistry.ts:99
E._handleExtensionPoint @ extensionService.ts:993
(anonymous) @ extensionService.ts:602
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
Promise resolved (async)
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.G.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
(anonymous) @ async.ts:687
(anonymous) @ c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284
(anonymous) @ original-fs.js:152
mime.ts:58 Overwriting extension <<.svg>> to now point to mime <<image/svg+xml>>
(anonymous) @ mime.ts:58
o @ mime.ts:52
e._mergeLanguage @ languagesRegistry.ts:127
e._registerLanguage @ languagesRegistry.ts:107
e._registerLanguages @ languagesRegistry.ts:63
(anonymous) @ languagesRegistry.ts:53
e.fire @ event.ts:140
e.registerLanguages @ modesRegistry.ts:38
(anonymous) @ workbenchModeService.ts:138
e._handle @ extensionsRegistry.ts:115
e.acceptUsers @ extensionsRegistry.ts:99
E._handleExtensionPoint @ extensionService.ts:993
(anonymous) @ extensionService.ts:602
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
Promise resolved (async)
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.G.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
(anonymous) @ async.ts:687
(anonymous) @ c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284
(anonymous) @ original-fs.js:152
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///c%3A/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///c%3A/Users/Eric/.vscode-insiders/extensions/ms-vscode.typescript-javascript-grammar-0.0.45/syntaxes/JavaScript.tmLanguage.json
e.register @ TMSyntax.ts:47
t._handleGrammarExtensionPointUser @ TMSyntax.ts:320
(anonymous) @ TMSyntax.ts:182
e._handle @ extensionsRegistry.ts:115
e.acceptUsers @ extensionsRegistry.ts:99
E._handleExtensionPoint @ extensionService.ts:993
(anonymous) @ extensionService.ts:602
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
Promise resolved (async)
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.G.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
(anonymous) @ async.ts:687
(anonymous) @ c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284
(anonymous) @ original-fs.js:152
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///c%3A/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: file:///c%3A/Users/Eric/.vscode-insiders/extensions/ms-vscode.typescript-javascript-grammar-0.0.45/syntaxes/TypeScript.tmLanguage.json
e.register @ TMSyntax.ts:47
t._handleGrammarExtensionPointUser @ TMSyntax.ts:320
(anonymous) @ TMSyntax.ts:182
e._handle @ extensionsRegistry.ts:115
e.acceptUsers @ extensionsRegistry.ts:99
E._handleExtensionPoint @ extensionService.ts:993
(anonymous) @ extensionService.ts:602
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
Promise resolved (async)
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.G.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
(anonymous) @ async.ts:687
(anonymous) @ c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284
(anonymous) @ original-fs.js:152
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///c%3A/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: file:///c%3A/Users/Eric/.vscode-insiders/extensions/ms-vscode.typescript-javascript-grammar-0.0.45/syntaxes/TypeScriptReact.tmLanguage.json
e.register @ TMSyntax.ts:47
t._handleGrammarExtensionPointUser @ TMSyntax.ts:320
(anonymous) @ TMSyntax.ts:182
e._handle @ extensionsRegistry.ts:115
e.acceptUsers @ extensionsRegistry.ts:99
E._handleExtensionPoint @ extensionService.ts:993
(anonymous) @ extensionService.ts:602
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
Promise resolved (async)
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.G.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
(anonymous) @ async.ts:687
(anonymous) @ c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:284
(anonymous) @ original-fs.js:152
extensionHost.ts:330 [Extension Host] STOPPED on first line for debugging on port 33009
(anonymous) @ extensionHost.ts:330
_tickCallback @ internal/process/next_tick.js:188
Promise resolved (async)
t._tryFindDebugPort @ extensionHost.ts:322
t._tryFindDebugPort @ extensionHost.ts:321
t.start @ extensionHost.ts:170
t @ extensionService.ts:148
t.create @ types.ts:166
e._createInstance @ instantiationService.ts:120
e.createInstance @ instantiationService.ts:73
E._startExtensionHostProcess @ extensionService.ts:396
i @ extensionService.ts:333
(anonymous) @ extensionService.ts:348
extensionHost.ts:237 Extension Host
extensionHost.ts:238 Debugger listening on ws://127.0.0.1:33009/059ee769-b597-4f57-9c6c-2228fe59f565
For help see https://nodejs.org/en/docs/inspector

extensionHost.ts:237 Extension Host
extensionHost.ts:238 Debugger attached.

console.ts:136 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""} (at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:45:177)
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] Git extension API method 'getGitPath' is deprecated. (at c.r.value (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:53:45010))
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
log.ts:171   ERR Cannot read property 'children' of undefined: TypeError: Cannot read property 'children' of undefined
    at t.getEntries (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2929:627)
    at t.addEntry (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2929:318)
    at e.$setEntry (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3240:598)
    at t._doInvokeHandler (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3267:118)
    at t._invokeHandler (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3266:742)
    at t._receiveRequest (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3265:322)
    at t._receiveOneMessage (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3264:234)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3262:81
    at e.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at a (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:318:348)
    at Socket.n._socketDataListener (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:318:567)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
console.ts:136 [Extension Host] [2018-10-01 16:50:17:720] [GitLens] Git found: 2.19.0.windows.1 @ C:\Program Files\Git\cmd\git.exe • 82 ms (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:17:725] [GitLens] Starting repository search in 2 folders (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:17:725] [GitLens] Searching for repositories (depth=1) in 'c:\Users\Eric\code\vscode-gitlens' ... (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:17:740] [GitLens] GitLens(v9.0.0-alpha) activated • 192 ms (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:17:806] [GitLens] [c:\Users\Eric\code\vscode-gitlens] git rev-parse --show-toplevel • 79 ms  (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:17:807] [GitLens] Repository found in 'c:/Users/Eric/code/vscode-gitlens' (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:17:840] [GitLens] Completed repository search (depth=1) in 'c:\Users\Eric\code\vscode-gitlens' • 114 ms (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:17:841] [GitLens] Searching for repositories (depth=1) in 'c:\Users\Eric\code\gitlens.github.io' ... (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] Git extension API method 'getGitPath' is deprecated. (at c.r.value (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:53:45010))
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] [2018-10-01 16:50:18:552] [GitLens] [c:\Users\Eric\code\gitlens.github.io] git rev-parse --show-toplevel • 710 ms  (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:18:553] [GitLens] Repository found in 'c:/Users/Eric/code/gitlens.github.io' (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:18:604] [GitLens] Completed repository search (depth=1) in 'c:\Users\Eric\code\gitlens.github.io' • 763 ms (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
console.ts:136 [Extension Host] [2018-10-01 16:50:18:614] [GitLens] getRemotesCore('c:/Users/Eric/code/gitlens.github.io') (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
bootstrap-window.js:195 [uncaught exception]: TypeError: Cannot read property 'hide' of undefined
onUnexpectedError @ bootstrap-window.js:195
(anonymous) @ bootstrap-window.js:38
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:147
setTimeout (async)
e._withWindowProgress @ progressService2.ts:128
e.withProgress @ progressService2.ts:109
e.$startProgress @ mainThreadProgress.ts:35
t._doInvokeHandler @ rpcProtocol.ts:442
t._invokeHandler @ rpcProtocol.ts:427
t._receiveRequest @ rpcProtocol.ts:344
t._receiveOneMessage @ rpcProtocol.ts:274
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
bootstrap-window.js:198 TypeError: Cannot read property 'hide' of undefined
    at e._updateWindowProgress (progressService2.ts:152)
    at e._updateWindowProgress (progressService2.ts:178)
    at progressService2.ts:131
onUnexpectedError @ bootstrap-window.js:198
(anonymous) @ bootstrap-window.js:38
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:147
setTimeout (async)
e._withWindowProgress @ progressService2.ts:128
e.withProgress @ progressService2.ts:109
e.$startProgress @ mainThreadProgress.ts:35
t._doInvokeHandler @ rpcProtocol.ts:442
t._invokeHandler @ rpcProtocol.ts:427
t._receiveRequest @ rpcProtocol.ts:344
t._receiveOneMessage @ rpcProtocol.ts:274
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
console.ts:136 [Extension Host] [2018-10-01 16:50:18:688] [GitLens] [c:/Users/Eric/code/gitlens.github.io] git remote -v • 73 ms  (at Function.log (C:\Users\Eric\code\vscode-gitlens\dist\extension.js:1:229912))
log.ts:171   ERR Cannot read property 'children' of undefined: TypeError: Cannot read property 'children' of undefined
    at t.getEntries (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2929:627)
    at t.addEntry (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2929:318)
    at e.$setEntry (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3240:598)
    at t._doInvokeHandler (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3267:118)
    at t._invokeHandler (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3266:742)
    at t._receiveRequest (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3265:322)
    at t._receiveOneMessage (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3264:234)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3262:81
    at e.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at a (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:318:348)
    at Socket.n._socketDataListener (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:318:567)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

VS Code version: Code - Insiders 1.28.0-insider (83d5a29433d7f576b59db8019575a0c9dc78a967, 2018-10-01T13:31:33.485Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (20.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
@eamodio you were using insiders right? any way to reproduce?

**Comment by eamodio** [comment]
Yeah, I was using insiders. I don't really know how to get into that situation -- although I have seen some strange issues (nothing I can repro reliably to really report) with debugging extensions with webviews (because they leave behind empty editor groups on reload) and very infrequently when I close one of the empty editor groups it will error out. But normally it doesn't really cause any issue, but this time it killed the window from ever loading right again (for that workspace).

My guess is that if you take my `editorpart.state` above, and add that to the local storage for one of your workspaces, it will repro the crash.

**Comment by bpasero** [comment]
I have pushed https://github.com/Microsoft/vscode/commit/f0bfe7ce71b28e91b70c42622bce087f5e03807f to never fail restoring the grid as a workaround (I used to have that code before).

**Comment by joaomoreno** [comment]
@eamodio Nice move with saving that `editorPart.state`!

**Comment by eamodio** [comment]
Thanks 😄. I had tried to debug it, but not knowing the code and dealing with source map line/breakpoint issues I gave up and just captured the state.
