### ISSUE TITLE
[Build] Non-working build made by gulp optimize-index-js

### ISSUE THREAD

**Issue by Jaakkonen** [Microsoft/vscode#59792]
- VSCode Version: Commit 09c738074e6f186903117a97a58a077cd9723278
- OS Version: Fedora 28 kernel 4.18

Running build gotten by gulp optimize-index-js fails on Cannot find module 'minimist'

Steps to Reproduce:

1. Build by runnint gulp optimize-index-js
2. Execute electron out-build/main.js
3. Cannot find module 'minimist'
```
Error: Cannot find module 'minimist'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/jaakko/.nvm/versions/node/v8.12.0/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at parseCLIArgs (/home/jaakko/dev/vskode/vscode/out-build/main.js:185:19)
    at Object.<anonymous> (/home/jaakko/dev/vskode/vscode/out-build/main.js:28:14)
    at Object.<anonymous> (/home/jaakko/dev/vskode/vscode/out-build/main.js:612:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at loadApplicationPackage (/home/jaakko/.nvm/versions/node/v8.12.0/lib/node_modules/electron/dist/resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/home/jaakko/.nvm/versions/node/v8.12.0/lib/node_modules/electron/dist/resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/home/jaakko/.nvm/versions/node/v8.12.0/lib/node_modules/electron/dist/resources/default_app.asar/main.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Object.<anonymous> (/home/jaakko/.nvm/versions/node/v8.12.0/lib/node_modules/electron/dist/resources/electron.asar/browser/init.js:189:8)
    at Object.<anonymous> (/home/jaakko/.nvm/versions/node/v8.12.0/lib/node_modules/electron/dist/resources/electron.asar/browser/init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
```

Does this issue occur when all extensions are disabled?: Yes (Electron opens window but fails before other than background UI-elements)

**Comment by mjbvz** [comment]
Do you still see this error in the latest version from master? (make sure to update modules with yarn too)
