### ISSUE TITLE
Real Time Compile and Error reporting not working

### ISSUE THREAD

**Issue by motor75** [Microsoft/vscode#59836]
Issue Type: <b>Bug</b>

It seems that since I have introduced solution files (.sln) into my projects, the red squiggles that show errors as you're coding has stopped altogether.  I have multiple projects in which this is occurring.  It had been working, but seems to have stopped since I put existing projects in solutions.  I had created an ASP.NET Core Web API project and wanted to add a Unit Test project to it - thus the need for a solution file.  However, that seems to be when this issue started.  I have not yet tried uninstalling and reinstalling Visual Studio Code because I wanted to report the issue and have it be replicated so that a fix can be made. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (2 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.99GB free)|
|Process Argv|C:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.16.1

</details>

**Comment by motor75** [comment]
Additional details - in the Problems window, I can see the errors and when I double click on them, it opens the same file in a new editor tab (now the same file is opened twice) and shows the red underline under the code in question.

**Comment by RMacfarlane** [comment]
@motor75 In the Problems panel, what's listed as the source of the errors? The csharp extension?

**Comment by motor75** [comment]
@RMacfarlane  - I restarted VS Code and all is working now...but eventually this will start happening again and I'll let you know....but when it was happening earlier (from my previous post), it showed the same file as the source separately - as if it was seeing two copies of it when only one exists.  Very strange.  I thought maybe I have some circular logic in the solution file or in my unit test project file - but this is not the case.  I have two projects; the solution has each of them only once and the unit test project references the web api project only once.

**Comment by motor75** [comment]
@RMacfarlane - it took a day but I'm back to nothing showing compile errors.  See attached screen shot...
![image](https://user-images.githubusercontent.com/42443455/46484436-cdcd4000-c7c7-11e8-9946-5d23cb8d281e.png)

Here's my Problems window....no problems showing...
![image](https://user-images.githubusercontent.com/42443455/46484529-f1908600-c7c7-11e8-98ad-926af4e01350.png)

Also it seems debugging via XUnit no longer works in this state...
![image](https://user-images.githubusercontent.com/42443455/46484632-2270bb00-c7c8-11e8-95d0-ac422d12bf16.png)

There is this error in the Log window which is most likely the reason that this is occurring...and I see a bunch of these in the last 3 or 4 minutes in the same window (they're all the same error repeated over and over):

**[2018-10-04 11:27:12.412] [renderer1] [error] Pending request cancelled: /codecheck: Error: Pending request cancelled: /codecheck
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:394:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:130)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:854)
	at DiagnosticsProvider._validateProject (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\features\diagnosticsProvider.js:188:37)
	at DiagnosticsProvider._onDocumentAddOrChange (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\features\diagnosticsProvider.js:137:18)
	at DiagnosticsProvider._onDidChangeActiveTextEditor (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\features\diagnosticsProvider.js:131:18)
	at DiagnosticsProvider.vscode.window.onDidChangeActiveTextEditor.event (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\features\diagnosticsProvider.js:112:74)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:937)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:786:954
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at e.$acceptDocumentsAndEditorsDelta (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:785:159)
	at e._doInvokeHandler (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)**

**Comment by motor75** [comment]
It appears that this all started with this error (which is different from what I put in my previous post):

**[2018-10-04 11:19:06.920] [renderer1] [error] This socket is closed: Error: This socket is closed
	at Socket._writeGeneric (net.js:726:18)
	at Socket._write (net.js:786:8)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at Socket.Writable.write (_stream_writable.js:290:11)
	at Socket.write (net.js:704:40)
	at OmniSharpServer._makeRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:507:35)
	at RequestQueue.OmniSharpServer._requestQueue.requestQueue_1.RequestQueueCollection.request [as _makeRequest] (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:92:109)
	at RequestQueue.processPending (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\requestQueue.js:73:29)
	at RequestQueueCollection.drain (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\requestQueue.js:137:33)
	at RequestQueueCollection.enqueue (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\requestQueue.js:107:14)
	at Promise (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:390:36)
	at new Promise (<anonymous>)
	at OmniSharpServer.<anonymous> (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:382:27)
	at Generator.next (<anonymous>)
	at C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:7:12)
	at OmniSharpServer.makeRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\server.js:376:16)
	at Object.<anonymous> (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\utils.js:174:23)
	at Generator.next (<anonymous>)
	at C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\utils.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\utils.js:7:12)
	at Object.debugTestStop (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\omnisharp\utils.js:173:12)
	at DebugEventListener.onDebuggingStopped (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\features\dotnetTest.js:429:21)
	at Socket.socket.on (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.1\out\src\features\dotnetTest.js:364:34)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)**

**Comment by RMacfarlane** [comment]
@motor75 Since the issues seems to be the behavior of the C# extension and not VSCode itself, I moved it over to the extension repo

**Comment by motor75** [comment]
Awesome; thanks for your help.
