### ISSUE TITLE
Mojave: SyntaxError: Unexpected token n in JSON at position 5988

### ISSUE THREAD

**Issue by liweijian** [Microsoft/vscode#59904]
I just upgrade my system to macOS Mojave, but my vscode doesn't work as before.

```shell
$ code --verbose
...
[941:1003/230153.564526:INFO:CONSOLE(5)] "[uncaught exception]: SyntaxError: Unexpected token n in JSON at position 5988", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[941:1003/230153.564823:INFO:CONSOLE(5)] "SyntaxError: Unexpected token n in JSON at position 5988
    at JSON.parse (<anonymous>)
    at e.loadMemento (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2398:601)
    at new e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2398:361)
    at e.getMemento (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2397:1000)
    at t.getMemento (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2474:451)
    at t.getEditorMemento (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2481:554)
    at t [as constructor] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3900:218)
    at t [as constructor] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4853:289)
    at t.create (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:111:535)
    at e._createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1392:10)
    at e.createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1391:269)
    at e.instantiate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2483:515)
    at t.doInstantiateEditorControl (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3536:512)
    at t.doCreateEditorControl (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3536:201)
    at t.doShowEditorControl (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3535:926)
    at t.openEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3535:643)
    at t.doShowEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4986:678)
    at t.restoreEditors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4980:569)
    at t [as constructor] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4973:411)
    at t.create (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:111:535)
    at e._createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1392:10)
    at e.createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1391:269)
    at Function.t.createFromSerialized (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4973:639)
    at t.doCreateGroupView (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5006:341)
    at Object.fromJSON (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5012:625)
    at Function.t.deserializeNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:464:510)
    at Function.t.deserializeNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:464:406)
    at Function.t.deserialize (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:465:179)
    at t.doCreateGridControlWithState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5012:551)
    at t.doCreateGridControlWithPreviousState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5012:349)
    at t.doCreateGridControl (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5011:856)
    at t.createContentArea (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5011:308)
    at t.create (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2479:107)
    at t.createEditorPart (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5455:147)
    at t.renderWorkbench (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5453:998)
    at t.startup (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5434:234)
    at t.createWorkbench (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5488:782)
    at t.renderContents (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5488:205)
    at t.open (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5496:402)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5504:218
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:343)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)", source: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
```

And there's another error:

```shell
[941:1003/230158.463558:ERROR:connection.cc(1964)] DOMStorageDatabase sqlite error 11, errno 0: database disk image is malformed, sql: DELETE FROM ItemTable WHERE key=?
```

**Comment by bpasero** [comment]
@liweijian that is weird and should not happen. You can fix this by:
* close code
* empty the folder `/Users/<username>/Library/Application Support/Code/Local Storage`
* start again

Do you remember how you got into that state?

**Comment by liweijian** [comment]
After removing `/Users/<username>/Library/Application Support/Code/Local Storage`, it works now, thank you.

I just upgrade my system from macOS 10.13 to 10.14 and it happens.

**Comment by ovidius72** [comment]
I'm having a similar issue in the latest code insider build 1.29.0-insider. I'm on a Mac with HightSierra

`
[2018-10-09 20:03:33.247] [renderer1] [error] Unexpected token � in JSON at position 0: SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5520:858)
    at emitNone (events.js:106:13)
    at t.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

I've emptied the local Storage folder under both code and code - Insiders but the problem persists.
