### ISSUE TITLE
Extensions stop working after some time: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by mrjones2014** [Microsoft/vscode#60046]
Issue Type: <b>Bug</b>

1. Open VS Code
2. Work on a project for a few hours (the time it takes for this bug to occur is not consistent).
  2.a. Some extra information: my workspace contains `*.vue`, `*.md`, `*.js`, `*.css`, `*.md` files, and a single `web.xml` file. Executing "Reload Window" from the Command Pallette fixes the issue, temporarily, then it will happen again after a few more hours.

Console output in VS Code developer tools console:
```
INFO no standard startup: not a new window
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Git extension API method 'getGitPath' is deprecated.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Sync : Connected with user : 'mrjones2014'
6/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1411   ERR Cannot read property 'peekBack' of undefined: TypeError: Cannot read property 'peekBack' of undefined
	at IndentSpy._peekBack (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:250:28)
	at IndentSpy._buildHoverString (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:234:35)
	at IndentSpy._buildHoverprovider (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:215:28)
	at Object.provideHover (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:205:29)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:761:91)
	at e.$provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:786)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1411   ERR Cannot read property 'peekBack' of undefined: TypeError: Cannot read property 'peekBack' of undefined
	at IndentSpy._peekBack (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:250:28)
	at IndentSpy._buildHoverString (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:234:35)
	at IndentSpy._buildHoverprovider (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:215:28)
	at Object.provideHover (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:205:29)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:761:91)
	at e.$provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:786)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
3/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1411   ERR Cannot read property 'peekBack' of undefined: TypeError: Cannot read property 'peekBack' of undefined
	at IndentSpy._peekBack (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:250:28)
	at IndentSpy._buildHoverString (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:234:35)
	at IndentSpy._buildHoverprovider (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:215:28)
	at Object.provideHover (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:205:29)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:761:91)
	at e.$provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:786)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1411   ERR Cannot read property 'peekBack' of undefined: TypeError: Cannot read property 'peekBack' of undefined
	at IndentSpy._peekBack (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:250:28)
	at IndentSpy._buildHoverString (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:234:35)
	at IndentSpy._buildHoverprovider (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:215:28)
	at Object.provideHover (/Users/mat/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:205:29)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:761:91)
	at e.$provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:786)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
4/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1411  WARN Aborted onWillSaveTextDocument-event after 1750ms
console.ts:136 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ console.ts:136
(anonymous) @ ipc.cp.ts:200
e.fire @ event.ts:140
i @ event.ts:588
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/mat/MyWorkspace.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
bracket-pair-colorizer|Coe|1.0.60
vue-peek|dar|1.0.2
gitlens|eam|8.5.6
vsc-material-theme|Equ|2.4.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-firefox-debug|hbe|1.7.0
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
code-settings-sync|Sha|3.1.2
indenticator|Sir|0.6.0

</details>

**Comment by mrjones2014** [comment]
doesn't look like any of the issues suggested by `vscodebot` are even close to this issue.

**Comment by mrjones2014** [comment]
Another note: when this happens, I also lose any and all IntelliSense, and *much* of the syntax highlighting. This issue is *quite* annoying and has plagued me from day 1, even before I had any extensions installed.

**Comment by egamma** [comment]
The crash happens inside the https://marketplace.visualstudio.com/items?itemName=SirTori.indenticator extension. Can you reproduce the issue when you uninstall this extension?

**Comment by mrjones2014** [comment]
@egamma Seems like it was in fact just an issue with the extension. This isn't the first time I've had such an issue with an extension. Is there an easier way to figure out which extension is causing issues in the future?

**Comment by mrjones2014** [comment]
@egamma this issue popped up again, and the extension we thought caused it before is not installed. There are no warnings or errors from extensions in the log. Can we reopen this issue please? This is the only stack trace:

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
4/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1411  WARN Aborted onWillSaveTextDocument-event after 1750ms
console.ts:136 [IPC Library: Search] (node:48600) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ console.ts:136
(anonymous) @ ipc.cp.ts:200
e.fire @ event.ts:140
i @ event.ts:588
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
```

**Comment by mrjones2014** [comment]
@egamma happening again, still without that extension installed. Here's an updated stack trace:

```
INFO no standard startup: not the explorer viewlet
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Git extension API method 'getGitPath' is deprecated.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Sync : Connected with user : 'mrjones2014'
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] No editors associated with document: /Users/mat/Dataforma/dflowslope/src/main/webapp/webpack/src/module/job/list/AdvancedSearch.vue
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] No editors associated with document: /Users/mat/Dataforma/dflowslope/src/main/webapp/webpack/src/module/job/list/PrjWoQuickfind.vue
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [IPC Library: Search] (node:44336) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1409  WARN Aborted onWillSaveTextDocument-event after 1750ms
```

**Comment by egamma** [comment]
Assigning to @roblourens 

>t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [IPC Library: Search] (node:44336) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by roblourens** [comment]
That's not an issue (although we should hide the warning), do you have a workspace with several folders in it? And it wouldn't affect extensions

**Comment by roblourens** [comment]
What's the actual issue you're seeing? "Extensions stop working after some time" what does that mean?

**Comment by mrjones2014** [comment]
@roblourens I mean basically none of the features or extensions work.... I get no IntelliSense, no Emmet support, a lot of the syntax highlighting goes away, CMD+Click to peek/go to definition doesn't work, even auto-indenting stops working. Basically, I might as well be using dark themed Windows Notepad.

As for the workspace, I have a workspace with 4 root folders. The folders contain a combination of *.jsp, *.css, *.html, *.js, and *.vue files.

**Comment by roblourens** [comment]
Have you upgraded to 1.28 yet? Do you ever see a notification that says "The extension host has stopped responding"?

**Comment by mrjones2014** [comment]
@roblourens I have updated to 1.28, no I've never seen such a notification. also, this issue has existed since at least version 1.25 for me.

**Comment by roblourens** [comment]
Ok, thanks for mentioning that. When this happens next, can you open the Process Explorer (under the help menu), find the extensionHost process, and check whether it's using high CPU or whether it's missing from that list for some reason?

**Comment by mrjones2014** [comment]
@roblourens will do. I should clarify, when I said it has existed since at least version 1.25, I meant because that's the first version that I used. I am not sure if the bug predates that.

**Comment by mrjones2014** [comment]
@roblourens I started experiencing this issue again. Looks like the cause is the extensionHost process using 100% CPU.
![image](https://user-images.githubusercontent.com/8648891/47313807-e46bf780-d60d-11e8-9ed3-4fdfa8909de5.png)

**Comment by roblourens** [comment]
It sounds like there is probably some extension doing something wrong and blocking other extensions from running.

You can run the "Show Running Extensions" command to see the list of running extensions, then click "Start Extension Host Profile" to try to get a profile while this is happening. If the extension host is at 100% for a long time, that may not work. 

You can also try disabling extensions to try to figure out which one is responsible.

**Comment by mrjones2014** [comment]
I'm not positive, but I _think_ it may have to do with the Auto Rename Tag extension: https://github.com/formulahendry/vscode-auto-rename-tag/issues/32

**Comment by mrjones2014** [comment]
@roblourens I ran the extension profiler, it seems to be the "Auto Rename Tag" extension that's the issue; also, process explorer shows extensionHost using _over 100% CPU_ somehow....

I've also attached the extension profile report for the "Auto Rename Tag" extension.

![image](https://user-images.githubusercontent.com/8648891/47513658-b58f9480-d84c-11e8-8a25-c56df29445d0.png)



[CPU-20181025T155324.487Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2515791/CPU-20181025T155324.487Z.cpuprofile.txt)

**Comment by roblourens** [comment]
Sounds like maybe https://github.com/formulahendry/vscode-auto-rename-tag/issues/32 then. The profile might be useful in that issue.
