### ISSUE TITLE
flow-for-vscode extension no longer working after update

### ISSUE THREAD

**Issue by doberkofler** [Microsoft/vscode#60194]
Issue Type: <b>Bug</b>

After the latest update of vscode-insiders the flow-for-vscode extention is no longer working. Uninstalling and reinstalling the extension does not solve the problem. No errors visible in the Output panel.

VS Code version: Code - Insiders 1.29.0-insider (1358e903716cf77711493770d63dde1ea178a73e, 2018-10-08T05:16:11.119Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
flow-for-vscode|flo|0.8.4
prettify-json|moh|0.0.3
python|ms-|2018.8.0
printcode|nob|3.0.0
vscode-icons|rob|7.27.0
code-settings-sync|Sha|3.1.2
stylelint|shi|0.43.0
language-stylus|sys|1.10.0
stylint|vtf|0.0.2
plsql-language|xyz|1.5.0

</details>

**Comment by doberkofler** [comment]
Log (Window) shows the following:
```

[2018-10-08 22:29:48.707] [renderer1] [info] no standard startup: panel is active
[2018-10-08 22:31:29.004] [renderer1] [info] Requested uninstalling the extension flowtype.flow-for-vscode from window 1
[2018-10-08 22:31:29.034] [renderer1] [info] Uninstalling the extension flowtype.flow-for-vscode-0.8.4 from window 1
[2018-10-08 22:31:33.097] [renderer1] [info] no standard startup: not a new window
[2018-10-08 22:32:45.907] [renderer1] [info] no standard startup: not a new window
[2018-10-08 23:00:55.423] [renderer1] [info] no standard startup: not a new window
```

**Comment by mjbvz** [comment]
Possibly #60168

**Comment by doberkofler** [comment]
```
INFO no standard startup: not a new window
console.ts:134 [Extension Host] vscode-icons is active! (at activate (C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\robertohuertasm.vscode-icons-7.27.0\out\src\index.js:44:13))
console.ts:134 [Extension Host] Activating extension 'flowtype.flow-for-vscode' failed: regeneratorRuntime is not defined. (at Object.showMessage (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:624:702))
t.log @ console.ts:134
console.ts:134 [Extension Host] Activating extension `flowtype.flow-for-vscode` failed:  regeneratorRuntime is not defined (at c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:295:9)
t.log @ console.ts:134
console.ts:134 [Extension Host] Here is the error stack:  ReferenceError: regeneratorRuntime is not defined
	at C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.8.4\build\utils\util.js:9:31
	at Object.<anonymous> (C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.8.4\build\utils\util.js:53:2)
	at Object.<anonymous> (C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.8.4\build\utils\util.js:151:3)
	at Module.i._compile (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:268)
	at Function.o._load (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:601:548)
	at Module.require (module.js:586:17)
	at n (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.8.4\build\utils\index.js:7:13)
	at Object.<anonymous> (C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.8.4\build\utils\index.js:34:3)
	at Module.i._compile (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:268)
	at Function.o._load (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:601:548)
	at Module.require (module.js:586:17)
	at n (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.8.4\build\index.js:14:14)
	at Object.<anonymous> (C:\Users\doberkofler.LBITS\.vscode-insiders\extensions\flowtype.flow-for-vscode-0.8.4\build\index.js:27:3)
	at Module.i._compile (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:268)
	at Function.o._load (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:601:548)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:31:146)
	at c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:628:90
	at t._doActivateExtension (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:628:202)
	at t._activateExtension (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:627:14)
	at Object.actualActivateExtension (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:624:834)
	at e._activateExtension (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:294:880)
	at c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:294:499
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:294:474)
	at e.activateByEvent (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:292:709)
	at t.activateByEvent (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:625:203)
	at t.$activateByEvent (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:629:650)
	at t._doInvokeHandler (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:742)
	at t._receiveRequest (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:641:234)
	at c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:81
	at c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:820)
	at Socket._socketDataListener (c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:155:42)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) (at c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:295:77)
extensionService.ts:994 Activating extension 'flowtype.flow-for-vscode' failed: regeneratorRuntime is not defined.
E._logMessageInConsole @ extensionService.ts:994
```

**Comment by doberkofler** [comment]
@jrieken Starting with "--no-cached-data" worked for me.
