### ISSUE TITLE
Python intelisense fails after latest insiders update

### ISSUE THREAD

**Issue by BlackHoleFox** [Microsoft/vscode#60212]
- VSCode Version: 1.29.0-insider (Commit: 1358e903716cf77711493770d63dde1ea178a73e)
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Make sure you're running the latest VSCode insiders update with the Microsoft Python extension
2. Open a Python file and look at the developers terminal to see error

Does this issue occur when all extensions are disabled?: No, as the Python extension isn't loaded ever.

I believe something in the latest VSCode update broke the extension to the point it won't work outright.

Here's the VSCode's console log:
```console
console.ts:134 [Extension Host] Activating extension 'ms-python.python' failed: Reflect.hasOwnMetadata is not a function. (at Object.showMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:623:628))
t.log @ console.ts:134
extensionService.ts:994 Activating extension 'ms-python.python' failed: Reflect.hasOwnMetadata is not a function.
E._logMessageInConsole @ extensionService.ts:994
console.ts:134 [Extension Host] Activating extension `ms-python.python` failed:  Reflect.hasOwnMetadata is not a function (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:295:9)
t.log @ console.ts:134

[Extension Host] Here is the error stack:  TypeError: Reflect.hasOwnMetadata is not a function
    at _tagParameterOrProperty (C:\Users\User\.vscode-insiders\extensions\ms-python.python-2018.8.0\node_modules\inversify\lib\annotation\decorator_utils.js:22:17)
    at Object.tagParameter (C:\Users\User\.vscode-insiders\extensions\ms-python.python-2018.8.0\node_modules\inversify\lib\annotation\decorator_utils.js:7:5)
    at C:\Users\User\.vscode-insiders\extensions\ms-python.python-2018.8.0\node_modules\inversify\lib\annotation\inject.js:24:31
    at C:\Users\User\.vscode-insiders\extensions\ms-python.python-2018.8.0\out\client\languageServices\languageServerSurveyBanner.js:11:37
    ---SHORTENED---```

**Comment by BlackHoleFox** [comment]
Oh, seems its been breaking more extensions they just Python. Will close then :)
