### ISSUE TITLE
Node debugger starting failed.

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#60227]
DevTool console of Debugger Window shows the following message:

"Error: 无法连接到运行中的进程，将在10000毫秒后超时 - （原因：目标的响应似乎无效。错误: Unexpected token  in JSON at position 324。响应: [ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:45969/650cf166-ace5-4a18-8411-787669eea913",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "650cf166-ace5-4a18-8411-787669eea913",
  "title": "���",
  "type": "node",
  "url": "file://",
  "webSocketDebuggerUrl": "ws://127.0.0.1:45969/650cf166-ace5-4a18-8411-787669eea913"
} ]

）
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2633:324
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:302)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:568)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:419)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2633:592
    at t.e.acceptMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2572:599)
    at t.handleData (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2573:452)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2572:954)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)"

And, on the new window side, shows this:

![image](https://user-images.githubusercontent.com/19996314/46643971-f2069380-cbb0-11e8-83d8-c59eb0397a28.png)

**Comment by liwangqian** [comment]
launch.json:
{
            "type": "extensionHost",
            "request": "launch",
            "name": "Launch Client",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceRoot}"
            ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/client/**/*.js"
            ]
            // "preLaunchTask": "npm: watch:client"
        },

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders
https://code.visualstudio.com/insiders/
