### ISSUE TITLE
Panel resize doesn't propagate with Terminal and TypedArrays

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#60253]
Happens on macOS

1. Set `"terminal.integrated.experimentalBufferImpl": "TypedArray"`
2. Put terminal to the side
3. Run tmux
4. Enlarge panel with sash

**Sometimes** terminal doesn't appear to grow with the panel size. When it happens, I get this error, which **sometimes** appears as an error message in the workbench (we seem to be eating up some errors there)

```
  ERR Source is too large: RangeError: Source is too large
    at Uint32Array.set (native)
    at BufferLineTypedArray.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferLine.js:179:22)
    at Buffer.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:116:39)
    at BufferSet.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferSet.js:74:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Terminal.js:1077:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/public/Terminal.js:53:20)
    at t._resize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3539:796)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3538:923)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3628:920)
    at Object.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:414:8)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:421:557
    at Array.forEach (<anonymous>)
    at t.layoutViews (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:421:528)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:416:699)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3627:727)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3633:207)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5448:68
    at Array.forEach (<anonymous>)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5448:39)
    at o.t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5024:146)
    at o.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5071:624)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4609:107)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4603:10
    at <anonymous>
```

**Comment by Tyriar** [comment]
Caused by one of the `data.set` calls in: https://github.com/xtermjs/xterm.js/blob/8d16bb6ea2e90312b0efb28bee3f39d3995a906f/src/BufferLine.ts#L221-L230

**Comment by jerch** [comment]
@Tyriar You also might want to add https://github.com/xtermjs/xterm.js/pull/1740, otherwise the consumers of `Buffer.translateBufferLineToString` will see truncated string after resize.

**Comment by Tyriar** [comment]
@jerch thanks for the reminder, will look at this now 👍
