### ISSUE TITLE
Code completion for import suggestion stopped working

### ISSUE THREAD

**Issue by zfeher** [Microsoft/vscode#60273]
- VSCode Version: 1.28.0
- VSCode Insiders Version: 1.29.0-insider (user setup) Commit: c1100eff93b35dc220ce63e2ed0d5ace54259795 Date: 2018-10-09T06:54:02.898Z
- OS Version: Windows 10 1803

Steps to Reproduce:

1. open some project
2. start to type a function name which is not yet imported. code completion should show import suggestions during typing and when pressing CTRL+SPACE

Does this issue occur when all extensions are disabled?: Yes

The following error occurs in TypeScript output
```
[Error  - 11:27:50 AM] 'completionInfo' request failed with error.
Error processing request. Cannot read property 'some' of undefined
TypeError: Cannot read property 'some' of undefined
    at c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94664:59
    at c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108298:21
    at forEachExternalModule (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108311:21)
    at Object.forEachExternalModuleToImportFrom (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108296:13)
    at getSymbolsFromOtherSourceFileExports (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94651:28)
    at getGlobalCompletions (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94548:21)
    at tryGetGlobalSymbols (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94471:25)
    at getCompletionData (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94350:22)
    at Object.getCompletionsAtPosition (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:93542:34)
    at Object.getCompletionsAtPosition (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114798:35)
    at IOSession.Session.getCompletions (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122583:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121645:61)
    at c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123052:28)
    at IOSession.Session.executeCommand (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123061:33)
    at IOSession.Session.onMessage (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123081:35)
    at Interface.<anonymous> (c:\Users\zfeher\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27640
