### ISSUE TITLE
Intellisense - Import suggestions show up but are not inserted/loaded?

### ISSUE THREAD

**Issue by Alexand3r** [Microsoft/vscode#60314]
As the title, when I try to "auto import" a component in a React Project , intellisense shows the suggestion, but on selecting it, it is not inserted

- VSCode Version: 1.28.0
- OS Version: Kubuntu 18.04

Steps to Reproduce:

1.Type in render function any React Component from any package ( my case from @material-ui/core the component TableHead, however it is not limited to this )
2. Press ctrl+space for Intellisense suggestion
3. Select Suggestion TableHead (tried with both mouse and keyboard arrows, same result)
4. Nothing happens, the small window for details doesn't show, however the suggestion is there.

Small note: This has been happening since ~ 1.20, however the imports would be imported at one point after some loading time, was blaming the huge number of node modules and the heavy usage of the machine. However with 1.28, it's dead.

Does this issue occur when all extensions are disabled?: Yes
Edit: This also happens in Visual Studio Code Insiders 1.29 version

I've set the typescript.tsserver.trace to verbose and got this :
_the ****** are to hide the project_

```

[Trace  - 2:46:03 PM] Sending request: completionEntryDetails (26). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/andrei/Desktop/Work/*********/src/views/Collections/CollectionCards/CollectionDevices.js",
    "line": 18,
    "offset": 18,
    "entryNames": [
        {
            "name": "TableCell",
            "source": "/home/andrei/Desktop/Work/*********/node_modules/@material-ui/core/TableCell/TableCell"
        }
    ]
}
[Trace  - 2:46:03 PM] Response received: completionEntryDetails (26). Request took 91 ms. Success: false . Message: Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32169:32)
    at getTargetOfExportAssignment (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31995:29)
    at getTargetOfAliasDeclaration (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32017:28)
    at Object.getImmediateAliasedSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30419:45)
    at getDefaultExportInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:39)
    at getDefaultLikeExportInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108171:24)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107968:35
    at forEachExternalModule (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108311:21)
    at getAllReExportingModules (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107963:13)
    at Object.getImportCompletionAction (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107949:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:94041:33)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:93991:30)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114803:35)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122609:57
    at Object.mapDefined (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122607:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:121654:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123052:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123081:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 2:46:03 PM] 'completionEntryDetails' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32169:32)
    at getTargetOfExportAssignment (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31995:29)
    at getTargetOfAliasDeclaration (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32017:28)
    at Object.getImmediateAliasedSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30419:45)
    at getDefaultExportInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:39)
    at getDefaultLikeExportInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108171:24)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107968:35
    at forEachExternalModule (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108311:21)
    at getAllReExportingModules (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107963:13)
    at Object.getImportCompletionAction (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107949:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:94041:33)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:93991:30)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114803:35)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122609:57
    at Object.mapDefined (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122607:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:121654:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123052:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123081:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

Edit Insiders log:
```
[Info  - 4:03:40 PM] Using tsserver from: /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib
[Info  - 4:03:40 PM] Forking TSServer
[Info  - 4:03:40 PM] Started TSServer
[Error  - 4:04:15 PM] 'completionEntryDetails' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32169:32)
    at getTargetOfExportAssignment (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31995:29)
    at getTargetOfAliasDeclaration (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32017:28)
    at Object.getImmediateAliasedSymbol (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30419:45)
    at getDefaultExportInfoWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:39)
    at getDefaultLikeExportInfo (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108171:24)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107968:35
    at forEachExternalModule (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108311:21)
    at getAllReExportingModules (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107963:13)
    at Object.getImportCompletionAction (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107949:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:94041:33)
    at Object.getCompletionEntryDetails (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:93991:30)
    at Object.getCompletionEntryDetails (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114803:35)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122609:57
    at Object.mapDefined (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122607:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:121654:61)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123052:28)
    at IOSession.Session.executeCommand (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:33)
    at IOSession.Session.onMessage (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123081:35)
    at Interface.<anonymous> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

```
![screenshot_20181009_160758](https://user-images.githubusercontent.com/988056/46674891-90a8e980-cbdd-11e8-9713-3f8d23130744.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27636

**Comment by fortinmike** [comment]
Microsoft/TypeScript#27636 is closed but I'm still seeing this in Code 1.28.2 (which supposedly includes TypeScript 3.1.3). I have no global typescript installed (we only work with JavaScript).

It worked perfectly until recently, but now every time I try auto-importing something, the completion details are missing, auto-import does not work and the following pops up in the TypeScript output:

```
[Error  - 8:12:11 PM] 'completionEntryDetails' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32172:32)
    at getTargetOfExportAssignment (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30421:45)
    at getDefaultExportInfoWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108209:39)
    at getDefaultLikeExportInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108191:24)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107988:35
    at forEachExternalModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108331:21)
    at getAllReExportingModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107983:13)
    at Object.getImportCompletionAction (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107969:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114823:35)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122634:57
    at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122632:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121674:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123077:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123086:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123106:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

What can I do to help diagnosing this?

**Comment by mjbvz** [comment]
Hey @sandersn, any idea why someone may be seeing this error? I haven't been able to reproduce it locally so I can't verify that 3.1.3 fixed it

**Comment by eugeniumegherea** [comment]
vscode 1.28.2, typescript 3.1.3. Still having issues.
Cannot reproduce error in new projects (tried in angular 6 and angular 5.2.0)
In an older project on angular 5.2.0 error is consistent
```
[Trace  - 10:27:12 AM] Response received: getCodeFixes (289). Request took 15 ms. Success: false . Message: Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32172:32)
    at getTargetOfExportAssignment (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30421:45)
    at getDefaultExportInfoWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108209:39)
    at getDefaultLikeExportInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108191:24)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108174:35
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108318:21
    at forEachExternalModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108316:13)
    at getExportInfos (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108158:57)
    at getFixesInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108099:50)
    at Object.getCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107861:28)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:106400:121
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:499:25)
    at Object.getFixes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:106400:23)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115125:35
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115123:23)
    at IOSession.Session.getCodeFixes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121789:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123077:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123086:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123106:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 10:27:12 AM] 'getCodeFixes' request failed with error.
```

**Comment by Alexand3r** [comment]
@eugeniumegherea @fortinmike https://github.com/Microsoft/TypeScript/issues/27636#issuecomment-428874485 
take a look at my comment regarding the fix, if any version of typescript is still present, it will still affect you, try running ```npm list -g typescript```, remove those packages that use typescript and re-add them. If the issue still persist try opening an issue on that package repo to upgrade their typescript dependency

**Comment by fortinmike** [comment]
I don't think I have any global typescript installed:

```
~ npm list -g typescript
/Users/michael/.nvm/versions/node/v10.5.0/lib
└── (empty)
```

**Comment by eugeniumegherea** [comment]
For now, I ended up downgrading typescript for current workspace. Here's how:
- `npm i -D typescript@3.0.3` <- 3.0.3 was typescript version for vscode 1.27.x, which worked fine.
- in vscode settings add:
`"typescript.tsdk": "./node_modules/typescript/lib"` <- relative path for downgraded typescript

**Comment by fortinmike** [comment]
@eugeniumegherea I tried doing that and while I don't see the error in the TypeScript output anymore, the auto import still doesn't work. Same incorrect behaviour, but no error.

**Comment by sandersn** [comment]
Ping @andy-ms, the actual author of the fix.

**Comment by sandersn** [comment]
The 3.1 errors sound different from the 3.0 ones, which I believe only affected re-exported `export default`. @fortinmike I think that explains the behaviour you see after downgrading to 3.0.

**Comment by fortinmike** [comment]
@sandersn The import statement warning is still present when reverting to Code 1.28.2's default typescript (3.1.3). In essence, the only thing that changes (at least for me) when reverting to typescript 3.0.1 is:

- Auto-importing named exports defined in the app starts working
- No exception logged in the TypeScript output, but other auto import issues remain

**Comment by mrsufgi** [comment]
I started experiencing the same issue since 1.28, but it only happens when I use 'commonjs' module resolution in my jsconfig.js file. otherwise ('es6'), it works.

**Comment by fortinmike** [comment]
I'm still trying to find the time to prepare a project to reproduce the issue, as I'm currently quite busy.

However, I can say that I do have a mix of ES6 and commonjs import / exports (for historical reasons) within my main app and our homegrown lib as @mrsufgi mentions.

Never had any issues with this previously.

I don't have a jsconfig file either. Would that help somehow?

**Comment by fortinmike** [comment]
@andy-ms I finally had time to tear down one of our projects to create a minimal repro. Here is the result:

https://github.com/Simbioz/typescript-auto-import-bug-repro

If you clone this, `npm install` in the `Ripple.Base` folder then try to auto-import the `Render` type in the `main.jsx` file, you'll either get the previously-mentioned error *or* `Render` won't appear in the list at all (seems to switch intermittently between the two).

I reproduced this (with this repo) on both macOS and a couple of Windows 10 computers at work, with the latest version of VS Code (`1.29.1`). I added more details in the `main.jsx` file, including the full error that's logged when auto import fails.

If you need any more info to debug this feel free to ask! This issue is a real pain for us as it messes up auto-import for our whole workspace. Anything to make fixing this quicker :)
