### ISSUE TITLE
intellisense for js suddenly stopped working

### ISSUE THREAD

**Issue by jper92** [Microsoft/vscode#60337]
Issue Type: <b>Bug</b>

Cannot reproduce, I open any project and doesn't autocomplete anymore (js projects). Ctrl + space don't show anything useful now

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.54GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.6
vscode-eslint|dba|1.6.0
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6

(1 theme extensions excluded)

</details>

**Comment by jper92** [comment]
whenever I hit ctrl + space, I see this line in the window log:
```
[2018-10-09 11:19:25.745] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-10-09 11:19:42.461] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
```

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions and restart VS Code. Also please look at the typescript server trace :

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the `output` panel and share the output from the `typescript` output section.

**Comment by UzEE** [comment]
Stumbled upon this issue since Intellisense for my Ember.js JavsScript project had also suddenly stopped working after the update to 1.28.0. I eventually resolved it by manually installing `@types/ember` from npm, despite the fact that it was working fine without installing types before. I checked my Window log and I've noticed the exact same log entries around the time Intellisense wasn't working. 

The problem still isn't fully resolved though since my JavaScript auto-imports are now doing an in-place dynamic import (`import("../path/to/module").ModuleName`) where I press `Ctrl+Space` on a symbol instead of the regular ES2016 style import at the top (`import ModuleName from "../path/to/module";`) which is very annoying and completely useless for me since it's against our code style.

I've tried disabling / reinstalling every Ember.js related extension but the problem persists.

___

My setup info:

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (16.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
emberjs|emb|1.0.1
vscode-ember|emb|0.2.0
vsc-ember-cli|fel|0.3.3
ember-related-files|jos|1.3.1
restructuredtext|lex|78.0.0
python|ms-|2018.9.0
PowerShell|ms-|1.9.0
vscode-docker|Pet|0.3.1
EmberES6Snippets|pha|2.3.3
vscode-icons|rob|7.27.0
preview-vscode|sea|1.4.4


</details>

**Comment by jper92** [comment]
[ts.log](https://github.com/Microsoft/vscode/files/2462186/ts.log)

I'm attaching the log from ts, I spotted these exceptions several times inside it:

```
[Trace  - 2:54:23 PM] Response received: completionInfo (17). Request took 29 ms. Success: false . Message: Error processing request. Cannot read property 'some' of undefined
TypeError: Cannot read property 'some' of undefined
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94664:59
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108298:21
    at forEachExternalModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108311:21)
    at Object.forEachExternalModuleToImportFrom (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108296:13)
    at getSymbolsFromOtherSourceFileExports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94651:28)
    at getGlobalCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94548:21)
    at tryGetGlobalSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94471:25)
    at getCompletionData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94350:22)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:93542:34)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114798:35)
    at IOSession.Session.getCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122583:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121645:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123052:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123081:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 2:54:23 PM] 'completionInfo' request failed with error.
```

**Comment by mjbvz** [comment]
Thanks. from the log this looks like this upstream issue: https://github.com/Microsoft/TypeScript/issues/27640

Will continue investigating upstream. If you have a small example project that reliable reproduces this issue, please share it as well
