### ISSUE TITLE
NPE when hitting `TAB` on a TS file

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#60397]
1. Open any TS file in our sources
2. Move to the beginning of an empty line
3. Hit <kbd>Tab</kbd>

NPE:

```
ERR Cannot read property 'label' of undefined: TypeError: Cannot read property 'label' of undefined
    at e.getParameterLabelOffsets (file:///home/joao/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2079:42)
    at e.renderParameters (file:///home/joao/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2078:509)
    at e.render (file:///home/joao/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2077:292)
    at file:///home/joao/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2074:861
    at e.fire (file:///home/joao/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:179:496)
    at file:///home/joao/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2072:430
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by joaomoreno** [comment]
Actually the stack trace is irrelevant to this... I was just in "tab moves focus" mode :facepalm:.
