### ISSUE TITLE
Extension crashed while doing code completion

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#60442]
Issue Type: <b>Bug</b>

vscode: 1.28.0
os: windows 7 x64

error message:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

devtool output:

```
  ERR no adapter found: Error: no adapter found
	at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:117)
	at e.$releaseCompletionItems (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:519:113)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket.n._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.99GB (7.12GB free)|
|Process Argv|--folder-uri file:///d%3A/works/luacoderassist-2.1.1|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
Bookmarks|ale|9.1.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.60
xml|Dot|2.3.2
gitlens|eam|8.5.6
code-runner|for|0.9.4
Lua|key|0.0.9
vs-color-picker|lih|0.7.0
codechat|liw|0.0.1
luacoderassist|liw|1.3.8
markdown-shortcuts|mdi|0.8.1
code-beautifier|mic|2.1.0
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.8.0
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2
color-highlight|nau|2.3.0
partial-diff|ryu|1.4.0
text-marker|ryu|1.9.0
Align|ste|0.2.0
vscode-pclint|liw|0.1.0
c-cpp-snippets|wlh|0.1.0
markdown-all-in-one|yzh|1.6.2

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
what steps? what extensions? what language? what file?
