### ISSUE TITLE
While building from source, ffmpeg...zip and electron...zip files are not downloaded unless VSCode is ran in development mode

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#60507]
- VSCode Version: 1.28.0
- OS Version: Win7 x64

Steps to Reproduce:

```
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

set PYTHON=C:\Program Files (x86)\Python271\python.exe

rem # (or Python 2.7 in PATH)

set PATH=%PATH%;C:\Program Files\7-Zip

rem # (or 7-zip in PATH)

call npm.cmd config set loglevel verbose

mkdir tmp

call npm.cmd config set cache tmp --global

call npm.cmd cache clean --force

yarn
```

Then

```
yarn run watch
```

So far, so good. Now trying to package:

```
C:\ACME\Dev\projects\vscode>yarn run gulp vscode-win32-x64


CSS INLINING IMAGE AT out-build\vs\workbench\parts\welcome\code-icon.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
[14:08:07] Finished 'optimize-vscode' after 1.88 min
[14:08:07] Starting 'vscode-win32-x64'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

It's only once I run VSCode in development mode that ffmpeg...zip and electron...zip are downloaded:

```
C:\ACME\Dev\projects\vscode>scripts\code.bat
[14:19:47] Using gulpfile C:\ACME\Dev\projects\vscode\gulpfile.js
[14:19:47] Starting 'clean-electron'...
[14:19:47] Finished 'clean-electron' after 81 ms
[14:19:47] Starting 'electron'...
? ffmpeg-v2.0.9-win32-x64.zip [====================] 100%
? electron-v2.0.9-win32-x64.zip [====================] 100%
[14:20:41] Finished 'electron' after 54 s
```

Otherwise, I get the above "Error: socket hang up" exception when I try to package (I got that exception on several packaging attempts before I ran VSCode in dev mode).

**After I run VSCode in development mode at least once, packaging succeeds**:

```
...
[14:30:44] Finished 'vscode-win32-x64' after 4.37 min
Done in 561.04s.
```

**Comment by joaomoreno** [comment]
Not sure why this happens. But since it doesn't hit our production and development scenario, I won't really look into it. This might be an issue with your machine being too slow (notice the 561.04s) when building and due to the fact that we use a single thread to do pretty much everything, there are downloads from the internet which take too long, making the servers serving them cut the sockets off. cc @aeschli
