### ISSUE TITLE
Cross-compiling on arm64 in Travis CI works, but window is empty after installing deb 

### ISSUE THREAD

**Issue by 435vic** [Microsoft/vscode#60564]
I built VSCode on arm64 with Travis CI, and set the `npm_config_arch` variable to `arm`. The build runs without errors, but when I install the deb file on my chromebook, the window is empty once launched. I can see that loading a module called `node-pty` failed, and that a shared object file cannot be found. Here is a screenshot:
![image](https://user-images.githubusercontent.com/13788817/46766851-ded6ef00-cca8-11e8-8ef6-098f30f75f4c.png)
This is the output of the command `vscodium --verbose`:
```
Error: /usr/share/vscodium/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/usr/share/vscodium/resources/app/out/vs/loader.js:15:808)
    at bindings (/usr/share/vscodium/resources/app/node_modules.asar/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/share/vscodium/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Object.<anonymous> (/usr/share/vscodium/resources/app/node_modules.asar/spdlog/index.js:21:3)
    at Module.i._compile (/usr/share/vscodium/resources/app/out/vs/loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/usr/share/vscodium/resources/app/out/vs/loader.js:31:146)
    at Object.t.createSpdLogService (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:231:561)
    at /usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:534:447
    at Object.v [as _notify] (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:96:807)
    at Object.enter (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:100:85)
    at n.Class.derive._creator._run (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:101:932)
    at n.Class.derive._creator._completed (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:101:373)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: /usr/share/vscodium/resources/app/node_modules.asar.unpacked/native-keymap/build/Release/keymapping.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/usr/share/vscodium/resources/app/out/vs/loader.js:15:808)
    at NativeBinding._init (/usr/share/vscodium/resources/app/node_modules.asar/native-keymap/index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (/usr/share/vscodium/resources/app/node_modules.asar/native-keymap/index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (/usr/share/vscodium/resources/app/node_modules.asar/native-keymap/index.js:61:18)
    at e.onDidChangeKeyboardLayout (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:318:939)
    at t.registerListeners (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:519:645)
    at t (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:516:967)
    at t.create (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:62:770)
    at e._createInstance (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:213:703)
    at e.createInstance (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:212:959)
    at /usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:534:501
    at Object.v [as _notify] (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:96:807)
    at Object.enter (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:100:85)
    at n.Class.derive._creator._run (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:101:932)
    at n.Class.derive._creator._completed (/usr/share/vscodium/resources/app/out/vs/code/electron-main/main.js:101:373)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[main 9:24:59 PM] Starting VS Code
[main 9:24:59 PM] from: /usr/share/vscodium/resources/app
[main 9:24:59 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false }
[main 9:24:59 PM] Resolving machine identifier...
[main 9:24:59 PM] Resolved machine identifier: 8dd7ce575121be5a4bc18923af27954d1175d4dccf036072690e72157116395a
[main 9:24:59 PM] update#ctor - updates are disabled
[main 9:25:00 PM] windowsManager#open
[3102:1010/212500.465977:ERROR:bus.cc(395)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3102:1010/212502.154622:INFO:CONSOLE(7)] "Loading "node-pty" failed", source: /usr/share/vscodium/resources/app/out/vs/loader.js (7)
[3102:1010/212502.155050:INFO:CONSOLE(7)] "Detail: ", source: /usr/share/vscodium/resources/app/out/vs/loader.js (7)
[3102:1010/212502.155973:INFO:CONSOLE(7)] "Error: /usr/share/vscodium/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/usr/share/vscodium/resources/app/out/vs/loader.js:15:808)
    at Object.<anonymous> (/usr/share/vscodium/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:21:11)
    at Object.<anonymous> (/usr/share/vscodium/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:252:3)
    at Module.t._initNodeRequire.i._compile (/usr/share/vscodium/resources/app/out/vs/loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/usr/share/vscodium/resources/app/out/vs/loader.js:15:808)
    at Object.<anonymous> (/usr/share/vscodium/resources/app/node_modules.asar/node-pty/lib/index.js:13:20)
    at Object.<anonymous> (/usr/share/vscodium/resources/app/node_modules.asar/node-pty/lib/index.js:51:3)
    at Module.t._initNodeRequire.i._compile (/usr/share/vscodium/resources/app/out/vs/loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at i (/usr/share/vscodium/resources/app/out/vs/loader.js:31:146)
    at t.load (/usr/share/vscodium/resources/app/out/vs/loader.js:16:408)
    at e.load (/usr/share/vscodium/resources/app/out/vs/loader.js:13:813)
    at i (/usr/share/vscodium/resources/app/out/vs/loader.js:28:217)
    at Object.errorback (/usr/share/vscodium/resources/app/out/vs/loader.js:28:338)
    at e.triggerErrorback (/usr/share/vscodium/resources/app/out/vs/loader.js:14:176)
    at /usr/share/vscodium/resources/app/out/vs/loader.js:13:883
    at ReadFileContext.callback (/usr/share/vscodium/resources/app/out/vs/loader.js:16:619)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)", source: /usr/share/vscodium/resources/app/out/vs/loader.js (7)
[3102:1010/212502.156405:INFO:CONSOLE(7)] "Here are the modules that depend on it:", source: /usr/share/vscodium/resources/app/out/vs/loader.js (7)
[3102:1010/212502.156635:INFO:CONSOLE(7)] "vs/workbench/parts/terminal/node/terminalProcess", source: /usr/share/vscodium/resources/app/out/vs/loader.js (7)
```
### Clarifications
The VSCode version is 1.28.
I tested the application on the Asus chromebook C101PA running crostini.
I built from a patched fork of VSCode called VSCodium, but no build files are changed.
The built deb files are in the releases section of the repo (specified below).
The VSCodium repo is [here](https://github.com/435vic/vscodium).
The Travis CI repo site is [here](https://travis-ci.com/435vic/vscodium).

**Comment by mjbvz** [comment]
Please start by filing this against VSCodium

**Comment by 435vic** [comment]
I understand that patching VSCode sounds like something likely to produce an error like this, so I made a test repository that simply downloads and builds the repo. However, the issue is still there. This is  [the repo](https://github.com/435vic/vscode-arm64). 
[This](https://travis-ci.com/435vic/vscode-arm64) is the Travis CI repo link.
Again, nothing about the actual repo is changed. It is cloned, then `cd`'d into, and run with yarn. You can check in the repo. Anyways, here are some screenshots:
![image](https://user-images.githubusercontent.com/13788817/46808971-2b670c80-cd33-11e8-9857-fa5c07c0dd79.png)
![image](https://user-images.githubusercontent.com/13788817/46809418-07f09180-cd34-11e8-8b9a-b2e14216687a.png)
Since the output of `code-oss --verbose` is pretty long, the contents are on [pastebin](https://pastebin.com/Hv5yTY6w).
