### ISSUE TITLE
Typescript cannot display import prompt.

### ISSUE THREAD

**Issue by linwrui** [Microsoft/vscode#60745]
Typing code with typescript,cannot display import prompt.

**Comment by mjbvz** [comment]
Please follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) to submit a proper issue report. This should include:

- What are you trying to do?
- What went wrong?
- Steps to reproduce the problem

**Comment by ctretyak** [comment]
It doesn't show import in Quick Fix

![image](https://user-images.githubusercontent.com/4935982/46902252-59cb2000-ceca-11e8-8ed4-8bce33a9d18c.png)

**Comment by mjbvz** [comment]
@ctretyak What vscode version are you running? Please share an small example project or at least some additional information about your project structure

**Comment by linwrui** [comment]
vscode version: 1.28.1

**Comment by linwrui** [comment]
![image](https://user-images.githubusercontent.com/22316156/46993794-da488580-d143-11e8-8990-212a177435bc.png)
See the screenshot!

**Comment by ctretyak** [comment]
@mjbvz 1.28.1
My .tsconfig
```
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "target": "esnext",
    "downlevelIteration": true,
    "strict": true,
    "strictFunctionTypes": false,
    "types": ["node"],
    "sourceMap": true,
    "allowJs": true,
    "allowUnreachableCode": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "jsx": "react",
    "noUnusedLocals": true,
    "baseUrl": "./src/client",
    "skipLibCheck": true
  },
  "exclude": [
    "node_modules",
    ".awcache",
    ".hard-source",
    "dist",
    "src/client/assets"
  ],
  "compileOnSave": false
}
```

**Comment by eugeniumegherea** [comment]
Version 1.28.0 broke import prompt for me too.
Previous version of vscode worked as expected in the snippet below (had an option to auto import missing imports). 
![image](https://user-images.githubusercontent.com/25582225/47099802-c0d83400-d23e-11e8-9852-2610d8a2ed45.png)

Angular 5.2.0 project
tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "outDir": "./dist/out-tsc",

    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,

    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by mjbvz** [comment]
First please try upgrading to VS Code 1.28.2. If it is still not working, two things:

1. Check the TypeScript Server trace:

    1. Set `"typescript.tsserver.trace": "verbose"`
    1. Reproduce the problem
    1. Open the output panel and view the `TypeScript` section

    Are there any errors or stack traces printed near the end?

1. Provide an example project or steps to reproduce in a new project

**Comment by linwrui** [comment]
Follow your suggestion steps and I get these:
[Trace  - 10:04:38 AM] Response received: getCodeFixes (15). Request took 108 ms. Success: false . Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1446:24)
    at getDefaultExportInfoWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108210:80)
    at getDefaultLikeExportInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108174:35
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108318:21
    at forEachExternalModule (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108316:13)
    at getExportInfos (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108158:57)
    at getFixesInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108099:50)
    at Object.getCodeActions (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107861:28)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:121
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getFixes (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:23)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115125:35
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115123:23)
    at IOSession.Session.getCodeFixes (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121789:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 10:04:38 AM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1446:24)
    at getDefaultExportInfoWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108210:80)
    at getDefaultLikeExportInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108174:35
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108318:21
    at forEachExternalModule (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108316:13)
    at getExportInfos (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108158:57)
    at getFixesInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108099:50)
    at Object.getCodeActions (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107861:28)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:121
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getFixes (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:23)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115125:35
    at Object.flatMap (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115123:23)
    at IOSession.Session.getCodeFixes (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121789:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

**Comment by mjbvz** [comment]
Thanks @linwrui. From the stack trace, you are hitting this upstream issue: https://github.com/Microsoft/TypeScript/issues/27878 Unfortunately I do not believe we can workaround this on the VS Code side

If you have repo steps or a project that demonstrates this problem please post them on that typescript issue

**Comment by linwrui** [comment]
My typescript version is 2.6.1. This happened after vscode 1.28.0.
