### ISSUE TITLE
Unable to build, electron-<arch> failing in github-releases-ms

### ISSUE THREAD

**Issue by headmelted** [Microsoft/vscode#60784]
- VSCode Version: latest code
- OS Version: Debian Stretch

Steps to Reproduce:

1. Run gulp "electron-arm" (also happens for electron-x64)

[12:50:42] Starting 'electron-arm'...
internal/streams/legacy.js:59
throw er; // Unhandled stream error in pipe.
Error: Not Found
  at Request._callback (/root/build/code/node_modules/github-releases-ms/lib/github.js:83:17)
  at Request.self.callback (/root/build/code/node_modules/github-releases-ms/node_modules/request/request.js:185:22)
  at emitTwo (events.js:126:13)
  at Request.emit (events.js:214:7)
  at Request.<anonymous> (/root/build/code/node_modules/github-releases-ms/node_modules/request/request.js:1161:10)
  at emitOne (events.js:116:13)
  at Request.emit (events.js:211:7)
  at IncomingMessage.<anonymous> (/root/build/code/node_modules/github-releases-ms/node_modules/request/request.js:1083:12)
  at Object.onceWrapper (events.js:313:30)
  at emitNone (events.js:111:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Not sure if it's something that's changed in my config, but can't for the life of me get this to work.  Has the process changed recently? (Maybe environment variables have been introduced that I need?).

Could be something I'm doing wrong, but has started happening suddenly.

In the github-releases-ms code line 83 looks to be referencing a token that I'm assuming is the environment variable $GITHUB_TOKEN, which I've confirmed is set correctly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by headmelted** [comment]
Appears to have been due to configuration that's since been obsoleted (electronRepository in product.json)
