### ISSUE TITLE
Checking for updates blocks with a company proxy that requires a username and password

### ISSUE THREAD

**Issue by ElCondor1969** [Microsoft/vscode#60948]
Issue Type: <b>Bug</b>

Hi to all.
Behind a company proxy that requires a username and password, although you enter the data correctly for the connection through the appropriate popups, Visual Studio Code blocks to checking for updates.
I attached here some pictures that illustrate the problem.

![image](https://user-images.githubusercontent.com/17902325/46941726-14deef00-d06c-11e8-8691-71fbde889216.png)
![image](https://user-images.githubusercontent.com/17902325/46941740-1f998400-d06c-11e8-83f4-ec29ed3743ab.png)

As you can see, the menu item that allows you to check for updates remains constantly disabled.
The strange thing is that instead the extensions work without any problems, in the sense that you can perform searches and launch their updates.
I've seen if there were any communication errors through the development tools, but I've never seen anything of this kind.
Bye.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.31GB free)|
|Process Argv|--inspect-extensions=42168|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.12.0
xml|Dot|2.3.2
vscode-todo-plus|fab|4.8.4
gc-excelviewer|Gra|2.1.26
svn-scm|joh|1.43.0
rainbow-csv|mec|0.7.0
vscode-todo-parser|min|1.9.1
vscode-language-pack-it|MS-|1.28.2
vsliveshare|ms-|0.3.790
vsliveshare-audio|ms-|0.1.38
debugger-for-chrome|msj|4.10.2
omnipascal|Wos|0.16.1
plsql-language|xyz|1.5.0

</details>

**Comment by egamma** [comment]
Have you configured the VS Code network connection for proxy access? Please see https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by ElCondor1969** [comment]
Hi egamma.
Yes, VS Code is configured correctly to exit on the internet through the company proxy.
In fact, through VS Code, I can navigate any web page, including those of the authors of the various VS Code installed extensions and the others too.
Moreover, the extensions, as I wrote before, check their updates correctly and download them without any problems.
When I start VS Code, I am correctly asked for my username/password to authenticate myself with the proxy and this happens without any problems.
It's just checking for VS Code updates that seems to have problems, as I wrote earlier.
Bye.

**Comment by philippart-s** [comment]
Hi,

Same problem with the following error : 
> [2018-10-20 17:14:56.524] [main] [info] update#setState idle
[2018-10-20 17:15:19.745] [main] [info] update#setState checking for updates
[2018-10-20 17:15:19.940] [main] [info] update#setState downloading
[2018-10-20 17:15:19.951] [main] [info] update#setState updating
[2018-10-20 17:15:19.974] [main] [error] [uncaught exception in main]: Error: spawn UNKNOWN
[2018-10-20 17:15:19.974] [main] [error] Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:514:9)
    at D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:514:789
    at Object.v [as _notify] (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:96:807)
    at Object.enter (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:100:85)
    at n.Class.derive._oncancel._run (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:101:932)
    at n.Class.derive._oncancel._completed (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:101:373)
    at Object.v [as _notify] (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:96:807)
    at Object.enter (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:100:85)
    at n.Class.derive._oncancel._run (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:101:932)
    at n.Class.derive._oncancel._completed (D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:101:373)
    at D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:132:688
    at D:\logiciels\dev\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:161:141
    at FSReqWrap.oncomplete (original-fs.js:135:15)

**Comment by ElCondor1969** [comment]
Hi.
Since the 1.29.1 version the issue seems not to occur anymore and the check for new updates seems to work properly.
Bye.
