### ISSUE TITLE
Pressing Ctrl+P shows Error

### ISSUE THREAD

**Issue by erkenfelt** [Microsoft/vscode#60960]
Issue Type: <b>Bug</b>

When I press Ctrl+P I get the following error:
`[UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}`

I have removed all extensions, reset all user settings, restarted my computer, tested adding my proxy settings. But nothing works.  

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz (8 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (8.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by erkenfelt** [comment]
And the problem is that nothing happens. I cannot use `ctrl+P` since it does not search when I type in the input box. I can't even close it by using `Esc`, I have to open like `ctrl+T`and then use `Esc` to close it.

**Comment by bogdan-calapod** [comment]
I also have this problem. The weird thing is that this only happens in one project - maybe something in `package.json` is throwing it off ? I can provide `package.json` files for a project that works and one that has the issue.

**Comment by egamma** [comment]
When this happens please open the developer tools ('Help>Toggle Developer Tools'). Switch to the Console tab and copy and paste the output. The output should include a full stack trace.

**Comment by erkenfelt** [comment]
This is the console output:
`
 INFO no standard startup: not just one text editor
log.ts:171   ERR [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:125:506
    at t.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:126:340)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:127:895)
    at Function.e.parse (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:127:155)
    at e.deserialize (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3666:270)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:944
    at Array.map (<anonymous>)
    at t.loadHistory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:756)
    at t.ensureHistoryLoaded (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:62)
    at t.handleEditorEventInHistory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3707:800)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3707:614)
    at t.onActiveEditorChanged (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3703:924)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3703:131
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at t.doEmitActiveEditorChangeEvent (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4574:993)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4574:769)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4575:117
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5023:522
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:167:366)
    at t.doShowEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5023:468)
    at t.doOpenEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5023:340)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5022:846)
    at t.doOpenEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4577:691)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4577:459)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3363:724)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3360:926
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164:568)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:419)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:205:1001
    at go$readdir$cb (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\graceful-fs\graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (original-fs.js:135:15)
`

**Comment by bpasero** [comment]
@erkenfelt @bogdan-calapod workaround is to configure `search.quickOpen.includeHistory: false` in settings.

**Comment by erkenfelt** [comment]
Thank you for your help, I set `search.quickOpen.includeHistory: false` but unfortunately it did not help.
` INFO no standard startup: not just one text editor
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1409   ERR [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:125:506
    at t.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:126:340)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:127:895)
    at Function.e.parse (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:127:155)
    at e.deserialize (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3666:270)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:944
    at Array.map (<anonymous>)
    at t.loadHistory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:756)
    at t.ensureHistoryLoaded (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:62)
    at t.handleEditorEventInHistory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3707:800)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3707:614)
    at t.onActiveEditorChanged (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3703:924)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3703:131
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at t.doEmitActiveEditorChangeEvent (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4574:993)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4574:769)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4575:117
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5023:522
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:167:366)
    at t.doShowEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5023:468)
    at t.doOpenEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5023:340)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5022:846)
    at t.doOpenEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4577:691)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4577:459)
    at t.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3363:724)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3360:926
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164:568)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:419)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:205:1001
    at go$readdir$cb (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\graceful-fs\graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (original-fs.js:135:15)
log.ts:171   ERR [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:125:506
    at t.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:126:340)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:127:895)
    at Function.e.parse (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:127:155)
    at e.deserialize (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3666:270)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:944
    at Array.map (<anonymous>)
    at t.loadHistory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:756)
    at t.ensureHistoryLoaded (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3712:62)
    at t.handleEditorEventInHistory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3707:800)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3707:614)
    at t.onActiveEditorChanged (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3703:924)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3703:131
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at t.doEmitActiveEditorChangeEvent (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4574:993)
    at t.handleActiveEditorChange (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4574:769)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4575:117
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5023:522
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._creator._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:343)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by bpasero** [comment]
workbench.main.js:3666:270 hints to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/webview/electron-browser/webviewEditorInputFactory.ts#L55

I will add a try/catch in history to prevent this from happening, but the underlying issue seems deeper.

**Comment by elrasco** [comment]
I had the same problem. My workround was to cancel the project and then clone it again in another folder, with different name.

**Comment by erkenfelt** [comment]
> I had the same problem. My workround was to cancel the project and then clone it again in another folder, with different name.

That worked for me too, thanks!

**Comment by i4004** [comment]
Another workaround is to remove all paths from "%USERPROFILE%\AppData\Roaming\Code\storage.json" related to project where error happening.

**Comment by lordscarlet** [comment]
As far as I can tell this thread does not contain a solution to being unable to save or open files, did I miss anything?

**Comment by octref** [comment]
@mjbvz Need steps for verifying, and not sure why it's marked as Webview.

**Comment by mjbvz** [comment]
Not sure how to do this without a poor behaving extension. To check:

1. Clone https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-sample
1. Update the webview to set an URI without a scheme for the iconPath, such as: `bla.png`
1. Start extension; open webview; then reload vscode
1. Make sure we don't throw an exception

**Comment by johnkors** [comment]
Suddenly appeared here as well. Haven't done anything to my setup lately. Cmd+P just triggers the warning:

```
[UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
```

Debug console:

```
[Extension Host] WARNING: Promise with no error callback:2
console.ts:136 [Extension Host]% 
```


```
[Extension Host] TypeError: Cannot read property 'result' of undefined
	at vscode.window.showWarningMessage.then.selection (/Users/johnkors/.vscode/extensions/ms-vscode.csharp-1.17.0/out/src/assets.js:345:54)
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:78:971)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:100)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:559)
	at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:444:313)
	at t._receiveReply (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:117)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:638:425)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:926
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:138
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:213)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_read
```
