### ISSUE TITLE
Error: Cannot read property 'getModeId' of null

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#61027]
Issue Type: <b>Bug</b>

Editor content is not visible:
![code - insiders_2018-10-16_10-15-24](https://user-images.githubusercontent.com/304384/47002245-bb8ac480-d12c-11e8-9c4d-d637134605bf.png)

Error in the developer tools:
```
  ERR Cannot read property 'getModeId' of null: TypeError: Cannot read property 'getModeId' of null
    at file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4573:34
    at Array.forEach (<anonymous>)
    at file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4572:842
    at e.fire (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:180:263)
    at file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4611:112
    at e.fire (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:180:263)
    at file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5078:522
    at Object.g [as _notify] (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:159:807)
    at Object.enter (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:163:85)
    at n.Class.derive._creator._run (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:164:932)
    at n.Class.derive._creator._completed (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:164:373)
    at n.Class.derive._creator.then (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:166:366)
    at Object.enter (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:162:184)
    at n.Class.derive._creator._run (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:164:932)
    at n.Class.derive._creator._setCompleteValue (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:164:626)
    at Object.g [as _notify] (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:159:787)
    at Object.enter (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:163:85)
    at n.Class.derive._oncancel._run (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:164:932)
    at n.Class.derive._oncancel._completed (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:164:373)
    at IconvLiteDecoderStream.<anonymous> (file:///C:/Users/[redacted]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1153:32)
    at emitNone (events.js:111:20)
    at IconvLiteDecoderStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

VS Code version: Code - Insiders 1.29.0-insider (a0b91c2c5dff3ad25aab867f4692d08c700d5c10, 2018-10-16T07:33:17.566Z)
OS version: Windows_NT x64 10.0.16299

Extensions disabled

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/47353255-150a6a80-d6bc-11e8-9fae-87034c488c80.png)
