### ISSUE TITLE
Getting OmniSharp errors in logs debugging xunit

### ISSUE THREAD

**Issue by motor75** [Microsoft/vscode#61064]
Issue Type: <b>Bug</b>

I have yet to discover the pattern or the steps to produce this issue, but after a period of time unit testing (xunit) & debugging a C# ASP.NET core Web API controller, the ability to debug (using the "Run Tests" or "Debug Tests" under the [Fact] attribute on a unit test method) no longer exists - they suddenly disappear.  Under the [Fact] there is nothing indicating that this is a unit test nor the ability to run the test (this occurs for all unit test methods all at once).  It is quite simply the [Fact] attribute and the next line is the method signature - the debug and run tests links that typically show in between disappear altogether.  Also, it seems that compile error messages no longer happen when incorrect code is put in (I had filed a bug about this a while ago and it was refiled under OmniSharp but after 3 weeks, it has received no updates).  The only way to fix this issue is to exit Visual Studio Code and restart - then eventually this issue happens again.  Below is the Log(Window) errors that indicate the beginning of this issue.  In the middle of this stack trace of errors, there is this message:

[2018-10-16 12:50:00.867] [renderer1] [error] An unknown error occurred. Please consult the log for more details.

I have looked through the logs in Visual Studio Code, but I can't find any other errors except those shown below in the Log(Window).  If there's some other file that has more info which this message is referring to, let me know and I'll obtain it and update this bug.

Errors From the Log(Window):

[2018-10-16 12:38:21.710] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at OmniSharpServer._makeRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:511:35)
	at RequestQueue.OmniSharpServer._requestQueue.requestQueue_1.RequestQueueCollection.request [as _makeRequest] (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:93:109)
	at RequestQueue.processPending (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:73:29)
	at RequestQueueCollection.drain (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:134:31)
	at RequestQueueCollection.enqueue (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:107:14)
	at Promise (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:391:36)
	at new Promise (<anonymous>)
	at OmniSharpServer.<anonymous> (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:383:27)
	at Generator.next (<anonymous>)
	at C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:7:12)
	at OmniSharpServer.makeRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:377:16)
	at Object.<anonymous> (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\utils.js:120:23)
	at Generator.next (<anonymous>)
	at C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\utils.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\utils.js:7:12)
	at Object.typeLookup (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\utils.js:119:12)
	at OmniSharpHoverProvider.<anonymous> (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\hoverProvider.js:25:32)
	at Generator.next (<anonymous>)
	at C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\hoverProvider.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\hoverProvider.js:7:12)
	at OmniSharpHoverProvider.provideHover (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\hoverProvider.js:22:16)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:500:127
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:368
	at new n.Class.derive._oncancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:776)
	at Object.t.asThenable (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:333)
	at e.provideHover (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:500:86)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:514:826
	at e._withAdapter (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:91)
	at e.$provideHover (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:514:788)
	at t._doInvokeHandler (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:60)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-10-16 12:38:32.585] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-10-16 12:38:33.415] [renderer1] [error] Pending request cancelled: /codecheck: Error: Pending request cancelled: /codecheck
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:395:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:331)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:107:51)
	at DiagnosticsProvider._validateProject (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\diagnosticsProvider.js:201:37)
	at DiagnosticsProvider._onDocumentAddOrChange (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\diagnosticsProvider.js:151:14)
	at DiagnosticsProvider._onDidChangeActiveTextEditor (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\diagnosticsProvider.js:143:18)
	at DiagnosticsProvider.vscode.window.onDidChangeActiveTextEditor.event (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\features\diagnosticsProvider.js:113:74)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:516)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:588:237
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.$acceptDocumentsAndEditorsDelta (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:488:823)
	at t._doInvokeHandler (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-10-16 12:38:33.986] [renderer1] [error] Pending request cancelled: /typelookup: Error: Pending request cancelled: /typelookup
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:395:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:331)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:107:51)
	at Object.l (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:104)
	at t._receiveCancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:864)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:387)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-10-16 12:38:36.441] [renderer1] [error] Pending request cancelled: /typelookup: Error: Pending request cancelled: /typelookup
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:395:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:331)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:107:51)
	at Object.l (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:104)
	at t._receiveCancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:864)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:387)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-10-16 12:38:53.158] [renderer1] [error] Pending request cancelled: /typelookup: Error: Pending request cancelled: /typelookup
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:395:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:331)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:107:51)
	at Object.l (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:104)
	at t._receiveCancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:864)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:387)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-10-16 12:38:55.475] [renderer1] [error] Pending request cancelled: /typelookup: Error: Pending request cancelled: /typelookup
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:395:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:331)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:107:51)
	at Object.l (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:104)
	at t._receiveCancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:864)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:387)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-10-16 12:39:01.163] [renderer1] [error] Pending request cancelled: /typelookup: Error: Pending request cancelled: /typelookup
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:395:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:331)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:107:51)
	at Object.l (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:104)
	at t._receiveCancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:864)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:387)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-10-16 12:39:01.814] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-10-16 12:39:01.815] [renderer1] [error] Pending request cancelled: /v2/codestructure: Error: Pending request cancelled: /v2/codestructure
	at RequestQueue.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\out\src\omnisharp\server.js:395:40)
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:106:331)
	at e.cancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:107:51)
	at Object.l (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:104)
	at t._receiveCancel (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:864)
	at t._receiveOneMessage (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:387)
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (2 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-test-explorer|for|0.5.4
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.16.2

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Please file this issue against the c# extension
