### ISSUE TITLE
CSS smoke tests are failing

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#61268]
Seems to be problems related.

```
2018-10-18T16:18:20.9410428Z [0m  1) Running Code
2018-10-18T16:18:20.9410573Z        CSS
2018-10-18T16:18:20.9410666Z          verifies warnings for the empty rule:
2018-10-18T16:18:20.9410750Z [0m[31m     Error: Timeout: get element 'div[aria-label="Problems grouped by files"] .icon.warning' after 20 seconds.[0m[90m
2018-10-18T16:18:20.9410830Z       at D:\a\1\s\test\smoke\out\vscode\code.js:142:23
2018-10-18T16:18:20.9410926Z       at Generator.next (<anonymous>)
2018-10-18T16:18:20.9410991Z       at fulfilled (out\vscode\code.js:8:58)
2018-10-18T16:18:20.9411074Z       at <anonymous>
2018-10-18T16:18:20.9411130Z [0m
2018-10-18T16:18:20.9412461Z [0m  2) Running Code
2018-10-18T16:18:20.9413556Z        CSS
2018-10-18T16:18:20.9413629Z          verifies that warning becomes an error once setting changed:
2018-10-18T16:18:20.9413729Z [0m[31m     Error: Timeout: get element 'div[aria-label="Problems grouped by files"] .icon.error' after 20 seconds.[0m[90m
2018-10-18T16:18:20.9413831Z       at D:\a\1\s\test\smoke\out\vscode\code.js:142:23
2018-10-18T16:18:20.9413895Z       at Generator.next (<anonymous>)
2018-10-18T16:18:20.9413982Z       at fulfilled (out\vscode\code.js:8:58)
2018-10-18T16:18:20.9414044Z       at <anonymous>
```

**Comment by joaomoreno** [comment]
Fixed by deadcd4d47f89858c7f05d81566222bf65a8a847
