### ISSUE TITLE
Python debugger crashes

### ISSUE THREAD

**Issue by rtanase** [Microsoft/vscode#61279]
Issue Type: <b>Bug</b>

Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 649, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 819, in do_wait_suspend
    self._activate_mpl_if_needed()
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 442, in _activate_mpl_if_needed
    activate_function = self.mpl_modules_for_patching.pop(module)
KeyError: 'matplotlib.pyplot'
Traceback (most recent call last):
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 316, in __call__
    ).trace_dispatch(frame, event, arg)
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 649, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 819, in do_wait_suspend
    self._activate_mpl_if_needed()
  File "c:\Users\ratanase\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 442, in _activate_mpl_if_needed
    activate_function = self.mpl_modules_for_patching.pop(module)
KeyError: 'matplotlib.pyplot'

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|47.79GB (29.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gitdiffer|aag|0.0.3
scope-bar|amo|0.1.0
vscode-python-docstring|aza|0.0.5
jupyter|don|1.1.4
xml|Dot|2.3.2
gitlens|eam|8.5.6
compareit|in4|0.0.2
vscode-line-endings|jha|0.1.0
nbpreviewer|jit|1.0.0
binary-viewer|mom|0.0.1
python|ms-|2018.9.1
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
autodocstring|njp|0.2.3
partial-diff|ryu|1.4.0
git-merger|sha|0.4.1
vscodeintellicode|Vis|1.0.5
markdown-all-in-one|yzh|1.6.2
t4-support|zbe|0.4.2

</details>

**Comment by bjg2** [comment]
Hey, this happened to me as well. I can't debug my code, can you please fix this?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
