### ISSUE TITLE
Maximum call stack size exceeded error 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#61524]
Steps to Reproduce:

1. Install extension from https://github.com/kieferrm/vscode-22804 (preferred) or clone repo, open folder, and <kbd>F5</kdb>
2. Run **Crazy: Flood Problems View with Files** from Command Palette
3. Select 40000 files with 3 errors each
4. Try filtering using filter input box. After some time when I clear the filter I see following error. I also see this error when I move the scroll bar while tree is being populated 

A small number of errors on a large number of files is a situation that can easily happen with compiled languages in a misconfigured larger project.

![image](https://user-images.githubusercontent.com/10746682/47314361-b6a0a600-d641-11e8-8a5c-897d0cd09c72.png)

```
ERR Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at ListView._splice (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listView.js:109:41)
    at ListView.splice (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listView.js:83:29)
    at file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/list/splice.js:13:62
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/list/splice.js:13:30)
    at file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listWidget.js:873:83
    at EventBufferer.bufferEvents (file:///Users/sandy081/work/vscode/out/vs/base/common/event.js:433:21)
    at List.splice (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listWidget.js:873:32)
    at IndexTreeModel.refilter (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:111:23)
    at ObjectTreeModel.refilter (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:71:24)
    at WorkbenchObjectTree.AbstractTree.refilter (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/abstractTree.js:224:24)
    at MarkersPanel.updateFilter (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanel.js:201:23)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanel.js:319:27
    at Emitter.fire (file:///Users/sandy081/work/vscode/out/vs/base/common/event.js:159:38)
    at MarkersFilterAction.set [as filterText] (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanelActions.js:114:39)
    at MarkersFilterActionItem.onDidInputChange (file:///Users/sandy081/work/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanelActions.js:234:36)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanelActions.js:180:148
    at file:///Users/sandy081/work/vscode/out/vs/base/common/async.js:189:28
    at Object.notifySuccess [as _notify] (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.js:1191:59)
    at Object.enter (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.js:1089:29)
    at Promise_ctor._completed (file:///Users/sandy081/work/vscode/out/vs/base/common/winjs.base.js:1057:18)
    at file:///Users/sandy081/work/vscode/out/vs/base/common/async.js:194:23
```

**Comment by sandy081** [comment]
![kapture 2018-10-22 at 21 36 34](https://user-images.githubusercontent.com/10746682/47314688-ac32dc00-d642-11e8-9618-1309bfbea171.gif)

**Comment by sandy081** [comment]
In this video, I am just scrolling the view while it is getting updated

![kapture 2018-10-22 at 21 41 11](https://user-images.githubusercontent.com/10746682/47314922-501c8780-d643-11e8-8e82-234efc28b863.gif)

**Comment by joaomoreno** [comment]
OK that's a HUGE example. That `10K` label needs some updating. 😆

**Comment by sandy081** [comment]
Yeah. Label can simply say `${number}K+`.

**Comment by joaomoreno** [comment]
@sandy081 I am confused. There seem be to a couple separate issues here.

1. Filtering while tree is populating. What is wrong with that? I can't understand from the GIF.
2. Scrolling while tree is populating. I can't understand what is wrong with that either from the GIF.
3. Clearing the filter throws max call stack size error. Does it always happen? Is the tree being populated, or it is stable at that point?

**Comment by sandy081** [comment]
@joaomoreno I got max call stack size error in two ways, one is while filtering and the other is while scrolling. Hence, I filed one issue thinking that both are related/similar.

> Filtering while tree is populating. What is wrong with that? I can't understand from the GIF.

Filtering works correctly but at the end there is an error - Max call stack. 

> Scrolling while tree is populating. I can't understand what is wrong with that either from the GIF.

Same here too. At the end there is an error.

Please have an eye on the console and you can see errors at the end in both videos.

> Clearing the filter throws max call stack size error. Does it always happen? Is the tree being populated, or it is stable at that point?

It does not happen always. My guess is that it happens while tree is refreshed/rendered and filter is cleared.

> I have a separate, isolated, example with 100k rows each with 3 children, and filtering works without an issue; especially a max call stack size one.

Can you please try with the sample I mentioned in the description? Have 40K files with 3 errors each and try to filter/clear filter while tree is being populated.

Please let me know if you need more information or we can do screensharing

**Comment by joaomoreno** [comment]
We can also check it next week together 👍

**Comment by joaomoreno** [comment]
@sandy081 This test isn't hitting a tree/list rendering limit. It's hitting a JavaScript limit: `splice` requires passing in all new items as arguments to its function call, all of which end up on the stack, so if you splice a large enough collection of items, you end up exceeding the max stack size.

**Comment by sandy081** [comment]
Good findings.
