### ISSUE TITLE
Cannot start VS code - offline

### ISSUE THREAD

**Issue by StephD** [Microsoft/vscode#61536]
Done

- VSCode Version: 1.28.2
- OS Version: Win 10

Steps to Reproduce:
1. Disconnect Wifi or source of internet
2. Launch VScode (icon or CMD (code))

Does this issue occur when all extensions are disabled?: Yes/No
YES

Additionnals information : 
From the command launch, I got this error : 

> dns.js:246
    this._handle = new ChannelWrap();
                   ^
Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

It happen with `code`, `code --verbose` and `code --disable-extensions`
Additionnal, the ^ symbol in under the `new` or `new ChannelWrap()`

Thanks

**Comment by StephD** [comment]
Sorry, duplicate. Bad research
Thank you @vscodebot
