### ISSUE TITLE
Typescript Auto import not working on v1.28.1

### ISSUE THREAD

**Issue by samuel-gay** [Microsoft/vscode#61660]
Issue Type: <b>Bug</b>

I've only checked this on typescript. When using the auto import feature:
Cursor at the end of a classname that is not imported already
Ctrl + Space to access the list of available imports
Tab OR Enter to use auto import for selected item
nothing happens, ie, import does not appear at the top of the file (or anywhere else)

I've tested it by disabling all of my extensions, still doesn't work.
I installed the previous version of VSCode (1.27) and it worked again.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.90GB free)|
|Process Argv|C:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Please check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Are there any errors or stack traces printed near the end?

**Comment by samuel-gay** [comment]
When I click on the item I want to use to add an auto import, the Typescript out is as below.

`[Trace  - 10:28:13 AM] Response received: getCodeFixes (47). Request took 10 ms. Success: false . Message: Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108174:35
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108318:21
    at forEachExternalModule (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108316:13)
    at getExportInfos (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108158:57)
    at getFixesInfo (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108099:50)
    at Object.getCodeActions (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107861:28)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:121
    at Object.flatMap (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getFixes (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:23)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115125:35
    at Object.flatMap (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115123:23)
    at IOSession.Session.getCodeFixes (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121789:61)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 10:28:13 AM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108174:35
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108318:21
    at forEachExternalModule (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108316:13)
    at getExportInfos (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108158:57)
    at getFixesInfo (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108099:50)
    at Object.getCodeActions (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107861:28)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:121
    at Object.flatMap (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getFixes (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:23)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115125:35
    at Object.flatMap (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115123:23)
    at IOSession.Session.getCodeFixes (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121789:61)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)`


Towards the bottom, after repeating the steps above (triggering the auto import), typescript out error is as below (there was a lot of json that isn't included below).
`[Trace  - 10:28:49 AM] Response received: completionEntryDetails (50). Request took 32 ms. Success: false . Message: Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107988:35
    at forEachExternalModule (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at getAllReExportingModules (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107983:13)
    at Object.getImportCompletionAction (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107969:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114823:35)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122634:57
    at Object.mapDefined (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122632:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121674:61)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 10:28:49 AM] 'completionEntryDetails' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107988:35
    at forEachExternalModule (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at getAllReExportingModules (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107983:13)
    at Object.getImportCompletionAction (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107969:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114823:35)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122634:57
    at Object.mapDefined (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122632:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121674:61)
    at c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Users\Samuel (Work)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)`

**Comment by djensen47** [comment]
I have the exact same issue.

**Comment by djensen47** [comment]
Upgrading to typescript@next did _not_ solve the problem.

**Comment by djensen47** [comment]
Can we get this re-opened?

**Comment by inorganik** [comment]
I experienced this issue in 1.28.2 running on Linux (CentOS) on a project that is pinned to TS 2.7.2. I was able to fix the issue by [using the workspace version of Typescript](https://stackoverflow.com/a/53013953/591487). 

Please understand in many projects, such as Angular projects, a project is pinned to a certain version of typescript - we can't upgrade it because certain versions of Angular require a specific versions of Typescript.

**Comment by mjbvz** [comment]
@djensen47 Are you seeing the same trace, or something else?

**Comment by djensen47** [comment]
Same trace. "Unknown entity name kind."

**Comment by mjbvz** [comment]
Then it's the same issue that we're tracking upstream: https://github.com/Microsoft/TypeScript/issues/28149 

Can you please comment on that issue that typescript@next did not work for you

**Comment by dawnmist** [comment]
Still seeing this in 1.29.0, which includes typescript 3.1.4 as its release version. This is throwing errors in both `getCodeFixes` and `completionEntryDetails` resulting in no auto-imports and the description of imports missing when clicking Ctrl-Space for autocomplete.

Auto-complete/auto-import works when using a workspace version of typescript for 2.9.2, 3.0.3 and 3.20.0-dev, but 3.0.3 and 3.20.0-dev.20181113 are still continually throwing errors in `getCodeFixes` (the `completionEntryDetails` error is gone for them).

This means that the only typescript version that is not throwing errors repeatedly is 2.9.2.

**Comment by djensen47** [comment]
🤦‍♂️

What's it going to take to get this fixed?

**Comment by djensen47** [comment]
Wait, shouldn't this be re-opened?
