### ISSUE TITLE
TypeScript doesn't finish initiation

### ISSUE THREAD

**Issue by kurtextrem** [Microsoft/vscode#61682]
Issue Type: <b>Bug</b>

I don't really know how to reproduce this - however, I get the following in the TypeScript output, if I set it to "messages"/"verbose": 
```[Trace  - 10:36:16 AM] Response received: quickinfo (11). Request took 1 ms. Success: false . Message: Error processing request. Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114591:38)
    at Object.getQuickInfoAtPosition (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114832:30)
    at IOSession.Session.getQuickInfoWorker (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122512:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121617:61)
    at c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Users\Jacob\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

Also happens for the 'quickinfo' request and I guess every other out there. Do you need the source code of the JS file?

Screenshot: http://prntscr.com/l9sc71

VS Code version: Code - Insiders 1.29.0-insider (43823dae97f07760958ffbb5e16c7f219307159c, 2018-10-24T05:21:57.644Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (8.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
markdown-toc|Ala|1.5.6
TabOut|alb|0.1.6
vs-code-css-comments|ash|1.0.5
markdown-preview-github-styles|bie|0.1.3
npm-intellisense|chr|1.3.0
vscode-react-proptypes-intellisense|cun|0.0.3
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
find-more|Fen|0.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
backticks|fra|1.3.0
referenceshelper|gay|0.2.3
editorenhancements|gur|1.0.0
vscode-auto-open-markdown-preview|hnw|0.0.4
JSDocTagComplete|Hoo|0.0.2
vs-docblock|jer|0.4.0
diff-tool|jin|0.0.1
node-module-intellisense|lei|1.5.0
expand-region|let|0.1.2
vscode-language-babel|mgm|0.0.21
HTMLHint|mka|0.5.0
highlight-dodgy-characters|nac|1.0.0
react-proptypes-intellisense|OfH|1.0.3
vscode-versionlens|pfl|0.22.0
extension-update-reporter|ryu|1.0.2
vscode-open|san|0.1.0
stylelint|shi|0.44.0
packagelinker|sin|0.0.5
indenticator|Sir|0.6.0
vscode-csstree|sme|0.7.0
code-spell-checker|str|1.6.10
reopenclosedtab|uyi|1.0.1
bracket-padder|via|0.0.1
highlight-matching-tag|vin|0.7.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#28119
