### ISSUE TITLE
Quick Fix Lightbulb Not Appearing

### ISSUE THREAD

**Issue by Sara-Cagle** [Microsoft/vscode#61821]
Issue Type: <b>Bug</b>

I am on version 1.28.2 of VSCode. Since I updated to this version, the quick fix lightbulb no longer appears. Specifically, when I use a component or something that needs to be imported, the lightbulb is never visible. My setting for the quick fix lightbulb says it should appear in 10 miliseconds, but it never does.

For example, I want to use a service or component that is not imported yet in my project. I type the component name where I want it, and wait for it to be underlined in red. Then I hover over it so the quick fix light bulb appears. Normally, I'd click it and have it suggest where to import the component from. Now, even though it underlines in red, the quick fix lightbulb never appears. Ctrl+. is configured properly but has never worked for me and still does not work for auto imports. 

This has severely slowed by work since I can no longer auto import. I've tried restarting VSCode, restarting machine, etc. It's been a few days since I updated and the problem still persists.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.40
HTMLHint|mka|0.5.0
vsliveshare|ms-|0.3.869
typescript-hero|rbb|3.0.0
alphabetical-sorter|ue|2.0.1

</details>

**Comment by mjbvz** [comment]
Sounds like #61660 

Can you please check the TypeScript Server trace to confirm:

1. Set `"typescript.tsserver.trace": "verbose"` in VS Code settings
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Are there any errors or stack traces printed near the end?

**Comment by Sara-Cagle** [comment]
Yes there are a couple of errors being printed.
```
[Trace  - 7:40:21 PM] Sending request: getCodeFixes (8778). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "....",
    "startLine": 23,
    "startOffset": 43,
    "endLine": 23,
    "endOffset": 49,
    "errorCodes": [
        2304
    ]
}
[Trace  - 7:40:21 PM] Response received: getCodeFixes (8778). Request took 42 ms. Success: false . Message: Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108174:35
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108318:21
    at forEachExternalModule (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108316:13)
    at getExportInfos (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108158:57)
    at getFixesInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108099:50)
    at Object.getCodeActions (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107861:28)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:121
    at Object.flatMap (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getFixes (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:23)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115125:35
    at Object.flatMap (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115123:23)
    at IOSession.Session.getCodeFixes (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121789:61)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 7:40:21 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108174:35
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108318:21
    at forEachExternalModule (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108316:13)
    at getExportInfos (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108158:57)
    at getFixesInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108099:50)
    at Object.getCodeActions (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107861:28)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:121
    at Object.flatMap (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getFixes (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:106400:23)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115125:35
    at Object.flatMap (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115123:23)
    at IOSession.Session.getCodeFixes (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121789:61)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Trace  - 7:40:23 PM] Sending request: completionEntryDetails (8779). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "...",
    "line": 23,
    "offset": 44,
    "entryNames": [
        {
            "name": "OnInit",
            "source": ".../node_modules/@angular/core/src/metadata/lifecycle_hooks"
        }
    ]
}
[Trace  - 7:40:23 PM] Response received: completionEntryDetails (8779). Request took 33 ms. Success: false . Message: Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107988:35
    at forEachExternalModule (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at getAllReExportingModules (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107983:13)
    at Object.getImportCompletionAction (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107969:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114823:35)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122634:57
    at Object.mapDefined (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122632:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121674:61)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 7:40:23 PM] 'completionEntryDetails' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32172:32)
    at getTargetOfExportAssignment (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:30421:45)
    at getDefaultExportInfoWorker (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108209:39)
    at getDefaultLikeExportInfo (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107988:35
    at forEachExternalModule (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108331:21)
    at getAllReExportingModules (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107983:13)
    at Object.getImportCompletionAction (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:107969:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114823:35)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122634:57
    at Object.mapDefined (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122632:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121674:61)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by mjbvz** [comment]
Thanks. Yes from the error stack this sounds like #61660 which is tracked upstream as https://github.com/Microsoft/TypeScript/issues/28149

The exception means that all js/ts quick fixes will stop working, it is not autoimport specific
