### ISSUE TITLE
Search in files is not working

### ISSUE THREAD

**Issue by Eldair** [Microsoft/vscode#61862]
- VSCode Version: 1.29.0-insider
- OS Version: Win 10 build 17763.55

Steps to Reproduce:

1. Open directory
2. Search in files (same thing with --disable-extensions)
3. No results are found and search cannot be stopped either

Log (window) output:
```
Error: A Match can only be built from a single search result
    at new e (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3943:218)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3947:387
    at Array.forEach (<anonymous>)
    at t.updateMatches (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3947:361)
    at t.updateMatchesForModel (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3946:699)
    at t.createMatches (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3945:593)
    at t [as constructor] (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3945:340)
    at t.create (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:120:870)
    at t.e._createInstance (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1423:568)
    at t.e.createInstance (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1422:885)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3951:92
    at Array.forEach (<anonymous>)
    at t.add (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3950:898)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3955:79
    at Map.forEach (<anonymous>)
    at e.forEach (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:135:81)
    at t.add (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3955:3)
    at t.onSearchProgress (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3960:616)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3959:412
    at Array.forEach (<anonymous>)
    at Proxy.t.textSearch (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4637:577)
    at t.search (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3959:324)
    at t.onQueryTriggered (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5457:867)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5454:550
    at Object.g [as _notify] (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:162:971)
    at Object.enter (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:166:277)
    at n.Class.derive._oncancel._run (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:168:100)
    at n.Class.derive._oncancel._completed (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:167:559)
    at l (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:170:1011)
    at n.Class.derive.join.r.forEach.G.then.o.(anonymous function) (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:171:205)
    at Object.g [as _notify] (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:162:971)
    at Object.enter (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:166:277)
    at n.Class.derive._creator._run (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:168:100)
    at n.Class.derive._creator._completed (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:167:559)
    at Object.g [as _notify] (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:162:971)
    at Object.enter (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:166:277)
    at n.Class.derive._oncancel._run (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:168:100)
    at n.Class.derive._oncancel._completed (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:167:559)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3372:666
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3373:538
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:296:530
    at Function.<anonymous> (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3373:511)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:296:137
    at s (file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:295:684)
    at file:///C:/Users/krist/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:295:788
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Eldair** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/61860
