### ISSUE TITLE
VS Code still not launching when offline / no internet connection

### ISSUE THREAD

**Issue by paulstelzer** [Microsoft/vscode#61974]
There were a lot of issues related to VS Code not launching when offline / no internet connection, but all are closed. Only #7570 is opened, but you cannot comment to it. **But it's not resolved**, this issue still exist in the latest version and also in the insiders version. The output on `code --verbose` is the same many people mentioned earlier. So I reopen this issue, because it's still an issue also the original issue #7570 is already more than 2 years old.

- VSCode Version: 1.28.2 / 1.29-insider
- OS Version: Windows 10 1809
- Node.js Version: 10.9.0

Steps to Reproduce:

1. Use airplane / offline mode
2. Try to start VS Code
3. VS Code is not launching (error code see below)

Does this issue occur when all extensions are disabled?: Yes

```
AppData\Local\Programs\Microsoft VS Code Insiders> code --verbose
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

**Comment by paulstelzer** [comment]
Should fixed with electron-3.0.x but it seems not to be integrated into VS Code Insiders yet, so we have to wait how it seems
