### ISSUE TITLE
typescript autofix not worked on react components

### ISSUE THREAD

**Issue by mshatikhin** [Microsoft/vscode#62028]
Click on not imported react component. 

![2](https://user-images.githubusercontent.com/1788385/47644133-2c9b9480-db8f-11e8-93dc-256bc41d8e7c.PNG)

```
[Error  - 3:11:08 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:1435:24)
    at getDefaultExportInfo (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105224:63)
    at c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105201:32
    at c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105322:21
    at forEachExternalModule (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105335:21)
    at forEachExternalModuleToImportFrom (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105320:13)
    at getExportInfos (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105196:13)
    at getFixesInfoForNonUMDImport (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105182:57)
    at getFixesInfo (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:105120:19)
    at Object.getCodeActions (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:104905:28)
    at c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:103931:121
    at Object.flatMap (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:498:25)
    at Object.getFixes (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:103931:23)
    at c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:111782:35
    at Object.flatMap (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:498:25)
    at Object.getCodeFixesAtPosition (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:111780:23)
    at IOSession.Session.getCodeFixes (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:119374:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:118248:61)
    at c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:119531:88
    at IOSession.Session.executeWithRequestId (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:119522:28)
    at IOSession.Session.executeCommand (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:119531:33)
    at IOSession.Session.onMessage (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:119551:35)
    at Interface.<anonymous> (c:\work\GCloud\Client\node_modules\typescript\lib\tsserver.js:120805:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

tsconfig.json 
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "module": "es6",
    "moduleResolution": "node",
    "target": "es6",
    "jsx": "preserve",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strict": true,
    "noImplicitAny": false
  },
  "typeRoots": ["node_modules/@types", "typings"],
  "include": ["src/**/*.ts", "src/**/*.tsx", "node_modules/@types", "typings/**/*.ts"]
}

vscode: 1.28.2
typescript: 3.0.3
node: v8.11.3

**Comment by mjbvz** [comment]
Sounds like https://github.com/Microsoft/TypeScript/issues/26562

It looks like you are using an older version of typescript in your workspace. Does this reproduce when you use vscode's bundled version of typescript (3.1.3)?
