### ISSUE TITLE
setting a breakpoint errors

### ISSUE THREAD

**Issue by vgrafe** [Microsoft/vscode#62156]
- VSCode Version: 1.29.0-insider 
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. open nodejs project
2. run it using the following condiguration set in `launch.json`
```json
{
      "type": "node",
      "request": "launch",
      "name": "start server",
      "program": "${workspaceFolder}/server.js"
    }
```
3. set a breakpoint anywhere
4. the following error message appears in the debug console: 
```
Error processing "setBreakpoints": SyntaxError: Invalid regular expression: /(?<=^|file:\\\/\\\/\\\/)([a-zA-Z]):/: Invalid group
    at Object.pathToRegex (/Users/vgrafe/.vscode-insiders/extensions/ms-vscode.node-debug2-1.29.3/node_modules/vscode-chrome-debug-core/out/src/utils.js:465:23)
    at NodeDebugAdapter.<anonymous> (/Users/vgrafe/.vscode-insiders/extensions/ms-vscode.node-debug2-1.29.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1353:44)
    at Generator.next (<anonymous>)
    at /Users/vgrafe/.vscode-insiders/extensions/ms-vscode.node-debug2-1.29.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vgrafe/.vscode-insiders/extensions/ms-vscode.node-debug2-1.29.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:6:12)
    at NodeDebugAdapter.addBreakpoints (/Users/vgrafe/.vscode-insiders/extensions/ms-vscode.node-debug2-1.29.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1339:16)
    at NodeDebugAdapter.<anonymous> (/Users/vgrafe/.vscode-insiders/extensions/ms-vscode.node-debug2-1.29.3/out/src/nodeDebugAdapter.js:613:62)
    at Generator.next (<anonymous>)
    at /Users/vgrafe/.vscode-insiders/extensions/ms-vscode.node-debug2-1.29.3/out/src/nodeDebugAdapter.js:10:71
```
5. the breakpoint won't be hit.

when disabling the extensions, the node script does not even run.

**Comment by vgrafe** [comment]
Indeed - same bug. Closing this one.
