### ISSUE TITLE
Debug not stoping on breakpoints

### ISSUE THREAD

**Issue by ChristianAF** [Microsoft/vscode#62292]
OS: Ubuntu 18.04
Hi, I'm using de Debug of Vscode and is not stopping on breakpoints,this is the log :
Debugger listening on ws://127.0.0.1:25002/53180691-da97-4b14-909a-7fa81aef37f5
Debugger attached.
Error processing "setBreakpoints": SyntaxError: Invalid regular expression: /(?<=^|file:\\\/\\\/\\\/)([a-zA-Z]):/: Invalid group
    at Object.pathToRegex (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/utils.js:465:23)
    at NodeDebugAdapter.<anonymous> (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1353:44)
    at Generator.next (<anonymous>)
    at /usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:6:12)
    at NodeDebugAdapter.addBreakpoints (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1339:16)
    at NodeDebugAdapter.<anonymous> (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebugAdapter.js:613:62)
    at Generator.next (<anonymous>)
    at /usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebugAdapter.js:10:71
Error processing "setBreakpoints": SyntaxError: Invalid regular expression: /(?<=^|file:\\\/\\\/\\\/)([a-zA-Z]):/: Invalid group
    at Object.pathToRegex (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/utils.js:465:23)
    at NodeDebugAdapter.<anonymous> (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1353:44)
    at Generator.next (<anonymous>)
    at /usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:10:71

**Comment by isidorn** [comment]
Duplicate, fixed in latest insiders

**Comment by ChristianAF** [comment]
I have this version 1.29.0-insider, and the issue is still there.

**Comment by isidorn** [comment]
fyi @roblourens

**Comment by roblourens** [comment]
Please "check for updates" to make sure you are on the latest version. This exact issue was fixed yesterday.

**Comment by roblourens** [comment]
If you installed a .deb package or something then I think you should be able to get updates through your package manager or through Help > Check For Updates.
