### ISSUE TITLE
SQLite tests failing on my machine

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#62469]
The `basics (broken DB falls back to in-memory)` test keeps failing on my machine.

```
➜  vscode git:(master) ./scripts/test.sh -f SQLite

  SQLite Storage Library
    ✓ basics
    ✓ basics (open multiple times) (221ms)
    1) basics (broken DB falls back to in-memory)
    ✓ real world example (155ms)
    ✓ very large item value (238ms)
    ✓ multiple concurrent writes execute in sequence (255ms)


  5 passing (1s)
  1 failing

  1) SQLite Storage Library basics (broken DB falls back to in-memory):
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.<anonymous> (file:///home/joao/Work/vscode/out/vs/base/test/node/storage/storage.test.js:382:34)
      at step (file:///home/joao/Work/vscode/out/vs/base/test/node/storage/storage.test.js:35:23)
      at Object.next (file:///home/joao/Work/vscode/out/vs/base/test/node/storage/storage.test.js:16:53)
      at fulfilled (file:///home/joao/Work/vscode/out/vs/base/test/node/storage/storage.test.js:7:58)
      at <anonymous>
```

**Comment by joaomoreno** [comment]
Fixed by re-running `yarn`. :man_shrugging:
