### ISSUE TITLE
TSServer exited with code: 3

### ISSUE THREAD

**Issue by kfy90hw** [Microsoft/vscode#62654]
Issue Type: <b>Bug</b>

[Info  - 7:31:32 PM] Forking TSServer
[Info  - 7:31:32 PM] Started TSServer
[Error  - 7:36:06 PM] ReaderError
RangeError: out of range index
	at Buffer.copy (buffer.js:602:18)
	at l.tryReadContent (f:\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:158004)
	at t.Reader.onLengthData (f:\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:158570)
	at Socket.e.on.e (f:\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:158337)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[Error  - 7:36:06 PM] TSServer exited with code: 3

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.99GB (5.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
eslint-disable-snippets|drK|1.1.5
tslint|eg2|1.0.40
idea-directory-diff|iam|0.0.1
intellij-idea-keybindings|k--|0.2.28
python|ms-|2018.9.2
debugger-for-chrome|msj|4.11.0
code-settings-sync|Sha|3.2.0

(1 theme extensions excluded)

</details>

**Comment by kfy90hw** [comment]
[C:\Users\l00355968\AppData\Roaming\Code\logs\20181107T104808\exthost1\vscode.typescript-language-features\tsserver-log-JS1GFs\tsserver.log](url)

**Comment by kfy90hw** [comment]
ok

**Comment by kfy90hw** [comment]
Info 20706[10:49:31.585] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/formatters/unix.js 500 Project:  WatchType: Closed Script info
Info 20707[10:49:31.585] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/formatters/visualstudio.js 500 Project:  WatchType: Closed Script info
Info 20708[10:49:31.585] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/accessor-pairs.js 500 Project:  WatchType: Closed Script info
Info 20709[10:49:31.585] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/array-bracket-newline.js 500 Project:  WatchType: Closed Script info
Info 20710[10:49:31.585] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/array-bracket-spacing.js 500 Project:  WatchType: Closed Script info
Info 20711[10:49:31.585] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/array-callback-return.js 500 Project:  WatchType: Closed Script info
Info 20712[10:49:31.585] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/array-element-newline.js 500 Project:  WatchType: Closed Script info
Info 20713[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/arrow-body-style.js 500 Project:  WatchType: Closed Script info
Info 20714[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/arrow-parens.js 500 Project:  WatchType: Closed Script info
Info 20715[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/arrow-spacing.js 500 Project:  WatchType: Closed Script info
Info 20716[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/block-scoped-var.js 500 Project:  WatchType: Closed Script info
Info 20717[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/block-spacing.js 500 Project:  WatchType: Closed Script info
Info 20718[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/brace-style.js 500 Project:  WatchType: Closed Script info
Info 20719[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/callback-return.js 500 Project:  WatchType: Closed Script info
Info 20720[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/camelcase.js 500 Project:  WatchType: Closed Script info
Info 20721[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/capitalized-comments.js 500 Project:  WatchType: Closed Script info
Info 20722[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/class-methods-use-this.js 500 Project:  WatchType: Closed Script info
Info 20723[10:49:31.601] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/comma-dangle.js 500 Project:  WatchType: Closed Script info
Info 20724[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/comma-spacing.js 500 Project:  WatchType: Closed Script info
Info 20725[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/comma-style.js 500 Project:  WatchType: Closed Script info
Info 20726[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/complexity.js 500 Project:  WatchType: Closed Script info
Info 20727[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/computed-property-spacing.js 500 Project:  WatchType: Closed Script info
Info 20728[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/consistent-return.js 500 Project:  WatchType: Closed Script info
Info 20729[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/consistent-this.js 500 Project:  WatchType: Closed Script info
Info 20730[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/constructor-super.js 500 Project:  WatchType: Closed Script info
Info 20731[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/curly.js 500 Project:  WatchType: Closed Script info
Info 20732[10:49:31.616] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/default-case.js 500 Project:  WatchType: Closed Script info
Info 20733[10:49:31.632] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/dot-location.js 500 Project:  WatchType: Closed Script info
Info 20734[10:49:31.632] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/dot-notation.js 500 Project:  WatchType: Closed Script info
Info 20735[10:49:31.632] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/eol-last.js 500 Project:  WatchType: Closed Script info
Info 20736[10:49:31.632] FileWatcher:: Added:: WatchInfo: ***//eslint/lib/rules/eqeqeq.js 500 Project:  WatchType: Closed Script info

**Comment by kfy90hw** [comment]
The reason may be that we can't download packages  from the inner npm-registry. The problem was solved after the npm-registry changed. Thank you

**Comment by kfy90hw** [comment]
The reason may be that we can't download packages from the inner npm-registry. The problem was solved after the npm-registry changed. Thank you
