### ISSUE TITLE
VSCode  Extension host crashed

### ISSUE THREAD

**Issue by SamvelRaja** [Microsoft/vscode#62826]
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Opening VSCode shows **Extension host terminated unexpectedly** and Search is not working(maybe it is an extension internally)

```
{ errorCode: 'load',
  moduleId: 'iconv-lite',
  neededBy: [ 'vs/base/node/encoding', 'vs/code/node/cli' ],
  detail: { Error: Cannot find module 'iconv-lite'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at t.load (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:408)
    at e.load (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:813)
    at i (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:217)
    at Object.errorback (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:338)
    at e.triggerErrorback (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:14:176)
    at C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:883
    at ReadFileContext.callback (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:619)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13) code: 'MODULE_NOT_FOUND' } }
{ errorCode: 'load',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ],
  detail: { Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at t.load (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:408)
    at e.load (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:813)
    at i (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:217)
    at Object.errorback (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:338)
    at e.triggerErrorback (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:14:176)
    at C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:883
    at ReadFileContext.callback (C:\Users\SamvelRaja\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:619)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13) code: 'MODULE_NOT_FOUND' } }
```
Does this issue occur when all extensions are disabled?: Yes

Extension and task log files  are empty
SharedProcess log scanned 0 user extensions. as don't have any extensions installed. Deleted the `%USERPROFILE%/.vscode/` folder

**Comment by SamvelRaja** [comment]
Re-installing didn't help
One improvement though

In cmd, Tried opening via `code`
It showed the above error.

Did `npm install iconv-lite minimist` This opened the app, but upon opening same Extension Host Terminated unexpectedly came.  

In dev tools The below error is available.

![capture](https://user-images.githubusercontent.com/5114052/48252150-f9c48c80-e429-11e8-8b61-02676034c213.PNG)

I can't install `node-pty` as the post-install script requires few build tools which are not installed which are conflicting with my development.


For me, the search is not working at all in this app now.

Hope this helps.

**Comment by chrmarti** [comment]
The console messages refer to a system level install under `C:\Program Files` and you refer to a user level install under your user dir. Maybe the system level install is corrupt. Could you uninstall both, make sure they are gone (check the folders) and then reinstall?

**Comment by chrmarti** [comment]
Also: Reboot before you uninstall, just to make sure there can be no leaked process hanging on to the installed files.

**Comment by SamvelRaja** [comment]
@chrmarti  That's my bad. I am trying out in both system level install and user level install (Took the screenshot wrongly). And yeah it is happening on both installers. I even tried out the .Zip variation :(

Regarding reboot, It is a clean install, removed all extensions, made sure all processes killed. Even deleted the extensions folder every time (As I mentioned before). 

Does opening the installer via cmd helps in getting installer logs? Sometimes squirrel logs would get caught in that way for my projects. I know VSCode is not using squirrel. Any ideas in that front?

**Comment by SamvelRaja** [comment]
@chrmarti 
I can see node-pty available in `node_modules.asar.unpacked` folder but requiring it is not working in the extension host code 🤔 

![capture1](https://user-images.githubusercontent.com/5114052/48393044-f6841600-e733-11e8-8e89-4efb666197d7.PNG)

It is the zipped version downloaded.

**Comment by SamvelRaja** [comment]
Regarding Virus scanner, it is not problem with that.

**Comment by alexandrudima** [comment]
@SamvelRaja Can you please try precisely these steps:
1) download [win32 zip](https://az764295.vo.msecnd.net/stable/5f24c93878bd4bc645a4a17c620e2487b11005f9/VSCode-win32-ia32-1.29.0.zip) or [win64 zip](https://az764295.vo.msecnd.net/stable/5f24c93878bd4bc645a4a17c620e2487b11005f9/VSCode-win32-x64-1.29.0.zip)

2) extract it to a new top level folder e.g. `C:\test` --- to avoid any long path name issues or unicode characters in path name problems.

3) open from the explorer `C:\test\Code.exe` --- to avoid any environmental variables that might be set by accident in some consoles.

**Comment by SamvelRaja** [comment]
@alexandrudima No luck 😢  I need vscode back :/
![vscode](https://user-images.githubusercontent.com/5114052/48533086-139e1d80-e8c9-11e8-9a39-cbf28719c622.PNG)

**Comment by alexandrudima** [comment]
@SamvelRaja Those node modules are definitely present, but they are packed inside `resources\app\node_modules.asar`. Those error messages are an indication that reading from the `.asar` file fails. Electron provides the following enviornmental variables for dealing with `.asar` archives:
* `ELECTRON_NO_ASAR` - did you perhaps define this in your environment by any chance? If yes, then please unset it.
* `ELECTRON_LOG_ASAR_READS` - logs reads

Can you perhaps try the following:
```
# close all instances of code and unset ELECTRON_NO_ASAR and enable asar logging
> set ELECTRON_NO_ASAR=
> SET ELECTRON_LOG_ASAR_READS=1
> Code.exe
```

Then, open developer tools `F1 > Developer: Toggle Developer Tools` and check the log locations. Then we can compare with e.g. my logs and check if something is off.

**Comment by SamvelRaja** [comment]
@alexandrudima I got my Vscode back 😄 

Yus `ELECTRON_NO_ASAR`  does the trick. 
Lessons learnt 🗡 

Closing this issue. 
Thanks for the awesome support and product
