### ISSUE TITLE
Cannot debug 'extensionHost'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62870]
Issue Type: <b>Bug</b>

**Repo**
1. Open VS Code extension sample
1. Try debugging with f5

**Bug**
If extensions are enabled, see:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2429 Error: Failed to find debugger extension info for type:extensionHost
    at ShareDebugManager.createSharedDebugConfiguration (/Users/matb/.vscode-insiders/extensions/ms-vsliveshare.vsliveshare-0.3.925/out/src/debugger/shareDebugManager.js:129:19)
    at ShareDebugManager.resolveDebugConfiguration (/Users/matb/.vscode-insiders/extensions/ms-vsliveshare.vsliveshare-0.3.925/out/src/debugger/shareDebugManager.js:99:53)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:476:297
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:114:65
    at new Promise (<anonymous>)
    at Object.t.asThenable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:114:33)
    at e.$resolveDebugConfiguration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:476:266)
    at t._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:609:757)
    at t._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:609:423)
    at t._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:608:15)
    at t._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:606:957)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:604:773
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:103:886
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:105:344)
    at a (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:156:881)
    at Socket._socketDataListener (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:157:95)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

If extensions are disabled then see error:

![screen shot 2018-11-09 at 12 57 46 pm](https://user-images.githubusercontent.com/12821956/48287906-4ce51200-e41f-11e8-8d32-1a38c018f252.png)

VS Code version: Code - Insiders 1.29.0-insider (5e481940ccf7ed9005dfd810f586c09a49421355, 2018-11-09T14:55:36.370Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|

</details>

**Comment by mjbvz** [comment]
This was caused by `node debug (legacy)` being enabled and `node debug` being disabled

No idea how I got into this state as I do not recall ever disabling these extensions

**Comment by octref** [comment]
Happened to me too. I'm pretty sure I did not disable the newer node debug extension myself.

@sandy081 Any idea what condition might have caused this?

```
[2018-11-13 10:48:48.631] [sharedprocess] [info] main {"machineId":"1cee44e606b4df171ece2af3e31bc1e7dce72f667e790dac3af0a91d62fe09e3"}
[2018-11-13 10:48:48.669] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:48:48.705] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:48:48.719] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:48:48.749] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 10:48:48.752] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 10:48:50.113] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:48:50.141] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 10:48:50.864] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:48:54.495] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:48:54.531] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 10:48:54.880] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:49:28.639] [sharedprocess] [info] Starting to clean up unused language packs.
[2018-11-13 10:53:50.932] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:53:54.900] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:58:50.953] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 10:58:54.920] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:03:50.934] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:03:54.904] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:04:21.887] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:04:21.917] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 11:04:22.158] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:04:59.995] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:30.999] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:31.044] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:31.048] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:31.054] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:31.119] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 11:06:31.121] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 11:06:31.125] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 11:06:35.007] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:35.009] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:35.015] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:35.085] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 11:06:35.088] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 11:06:35.090] [sharedprocess] [info] Scanned system extensions: 71
[2018-11-13 11:06:43.917] [sharedprocess] [info] Scanned user extensions: 10
[2018-11-13 11:06:43.936] [sharedprocess] [info] Scanned system extensions: 71
```

**Comment by isidorn** [comment]
Seems like the issue is that the build in extensions get disabled. Forwarding to @sandy081 
fyi @weinand

**Comment by sandy081** [comment]
Just a hunch, do you remember disabling an extension that has node debug extension is a dependency or part of extension pack?

**Comment by octref** [comment]
I only remember disabling references extension because of the startup flash.

**Comment by sandy081** [comment]
And are you able to repro it consistently (Even after enabling)?

**Comment by octref** [comment]
It's not a reliable repro. I hit this once for a newly setup Mojave machine. Then I enabled the new Node Debug and disabled Legacy Node Debug. I coded a few hours and ran another launch config and see it disabled again.

The only interactions I did was disabling references extension and maybe installing a few extensions from marketplace.

**Comment by weinand** [comment]
@octref just to be clear about "Node-Debug (legacy)": Node-Debug depends on "Node-Debug (legacy)". So disabling "Node-Debug (legacy)" is a very bad idea.

**Comment by octref** [comment]
@weinand Thanks for the explanation.

I also got a reliable repro:

- Open new window. References extension show `Reload to Update` and `Disable`. I choose `Disable`
  ![image](https://user-images.githubusercontent.com/4033249/48515265-23f4c080-e815-11e8-8a0a-4fa7b09d01d0.png)
- Node Debug becomes disabled 🐛(it was enabled). Node Debug (legacy) remains activated.
![image](https://user-images.githubusercontent.com/4033249/48515349-543c5f00-e815-11e8-891c-90dc902a7cbc.png)
- In a while, References extension becomes enabled (probably due to auto-update?)

**Comment by octref** [comment]
- Disable References extension disables Node Debug
- Enable Node Debug enables References extension

This means I either can't debug `extensionHost` or I suffer https://github.com/Microsoft/vscode/issues/62861 for each new window I open.

**Comment by sandy081** [comment]
This is happening because References extension is using (copy/paste) the id of Node debug 2 extension in `builtInExtensions.json` - 1a12e0a02a107e7d1db47e14b1f065032cac17d4

Got the id of the References extension from Market place and updated it. This fixes it.

@jrieken FYI
