### ISSUE TITLE
Running the contributed command: 'emmet.expandAbbreviation' failed. 

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#63033]
- VSCode Version: 1.30.0-ins
- OS Version: win7x64

```
Version: 1.30.0-insider (system setup)
Commit: c72cb129f2a0b8117c9b01f3767026041d7d1d31
Date: 2018-11-13T06:19:28.504Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Trying to expand a word in the **.html** and getting this...

![image](https://user-images.githubusercontent.com/24613274/48419146-dff3b400-e75f-11e8-8cbf-61c84269b3d9.png)

Trying to do it with "Tab", as always. Tried to change the key-binding. The same effect.

![emmet abbr failed](https://user-images.githubusercontent.com/24613274/48420933-264b1200-e764-11e8-96cf-8111b85192e4.gif)

-----------

So, when I press "Tab" - nothing happens in console.
But when I type any letter - console gets errors:

```
  ERR f.extractAbbreviation is not a function: TypeError: f.extractAbbreviation is not a function
	at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (c:\! SOFT !\VS Code Insiders\resources\app\extensions\emmet\dist\extension.js:1:46280)
	at t.DefaultCompletionItemProvider.provideCompletionItems (c:\! SOFT !\VS Code Insiders\resources\app\extensions\emmet\dist\extension.js:1:45076)
	at c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:791
	at t.asThenable (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:93)
	at new Promise (<anonymous>)
	at Object.t.asThenable (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:136:61)
	at e.provideCompletionItems (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:543:750)
	at c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:911
	at e._withAdapter (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:549:554)
	at e.$provideCompletionItems (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:873)
	at t._doInvokeHandler (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:963)
	at t._invokeHandler (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:635)
	at t._receiveRequest (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:196)
	at t._receiveOneMessage (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:126)
	at c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:10
	at c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:126:16
	at e.fire (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:127:466)
	at a (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:179:853)
	at Socket.n._socketDataListener (c:\! SOFT !\VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:180:50)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by cjlaborde** [comment]
I have the exact same issue in Linux Ubuntu 18.04 after updating.
![image](https://user-images.githubusercontent.com/40572114/48439642-2abffc80-e75d-11e8-93e5-b200d5c4633a.png)

**Comment by zackkrida** [comment]
Same issue on MacOs:

```
1.30.0-insider
c72cb129f2a0b8117c9b01f3767026041d7d1d31
x64
```

Relevant settings.json content:
```
  "emmet.includeLanguages": {
    "blade": "php",
    "javascript": "javascriptreact",
    "vue": "html",
    "vue-html": "html"
  },
  "emmet.showAbbreviationSuggestions": false,
  "emmet.triggerExpansionOnTab": true,
```


if i press tab at all i get the "Running the contributed command:'emmet.expandAbbreviation' failed." notification.

**Comment by ramya-rao-a** [comment]
Thanks for reporting everyone

I see this only in the latest Insiders, but not when running the code from the master branch.
So, lets wait and see if tomorrow's Insiders fixes this.

**Comment by sshmyg** [comment]
Version 1.30.0-insider (1.30.0-insider)

Has same error!

**Comment by zackkrida** [comment]
@ramya-rao-a still unresolved, unfortunately! I've simply disabled emmet tab completion for now.

**Comment by ramya-rao-a** [comment]
We were able to narrow down the root cause to be missing node_modules folder for the emmet extension in the latest Insiders which in turn was due to a bug in our build scripts.

Fixed with https://github.com/Microsoft/vscode/commit/3c6b6e614d4a70d5a84e3d5b80bf7baa6cdb457a. Tomorrow's Insiders will have the fix.

Thanks for your patience everyone!

**Comment by selrond** [comment]
Confirmming it's fixed in `Version 1.30.0-insider (1.30.0-insider)`

**Comment by sshmyg** [comment]
@ramya-rao-a What about non insider version? I admitted that 1.29.1 arrived today, but still with emmet bug ((

**Comment by ramya-rao-a** [comment]
@sshmyg The bug only got introduced in the Insider version. What issue are you seeing with 1.29.1? Do you see the same error `Running the contributed command:'emmet.expandAbbreviation' failed` ?

**Comment by sshmyg** [comment]
@ramya-rao-a 1.29.0 had failed with this command but 1.29.1 - not.

**Comment by sshmyg** [comment]
Works fine without `"editor.tabCompletion": "off",` for 1.29.1.
