### ISSUE TITLE
Python Debugger crashes with AttributeError

### ISSUE THREAD

**Issue by wrhansen** [Microsoft/vscode#63157]
- VSCode Version: 1.29
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Run debugger on python file
2. Instantly crashes before anything runs

Error:

```python
Traceback (most recent call last):
  File "/home/wes/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd_launcher.py", line 14, in <module>
    import ptvsd
  File "/home/wes/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/__init__.py", line 15, in <module>
    from ptvsd.attach_server import (
  File "/home/wes/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/attach_server.py", line 5, in <module>
    from ptvsd._remote import (
  File "/home/wes/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_remote.py", line 11, in <module>
    from ptvsd.pydevd_hooks import install
  File "/home/wes/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/pydevd_hooks.py", line 13, in <module>
    from ptvsd import multiproc
  File "/home/wes/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/multiproc.py", line 32, in <module>
    subprocess_queue = queue.Queue()
AttributeError: 'module' object has no attribute 'Queue'
```

Does this issue occur when all extensions are disabled?: Yes -- can't run python debugging without extensions?

**Comment by roblourens** [comment]
Please file this on the python debugger extension
