### ISSUE TITLE
Rpm builds fail

### ISSUE THREAD

**Issue by egdoc** [Microsoft/vscode#63167]
- VSCode Version: 1.29.0
- OS Version: Ubuntu 18.04, Fedora 29

Steps to Reproduce:

1. Run yarn to start compiling - The application compiles without errors
2. Run `$ yarn run gulp vscode-linux-x64-build-rpm` to build an rpm - the following error is reported:

```
yarn run v1.12.3
$ gulp --max_old_space_size=4095 vscode-linux-x64-build-rpm
[21:53:22] Node flags detected: --max_old_space_size=4095
[21:53:22] Respawned to PID: 9036
[21:53:34] Using gulpfile ~/vscode/gulpfile.js
[21:53:34] Starting 'clean-vscode-linux-x64-rpm'...
[21:53:34] Finished 'clean-vscode-linux-x64-rpm' after 32 ms
[21:53:34] Starting 'vscode-linux-x64-prepare-rpm'...
[21:53:35] Finished 'vscode-linux-x64-prepare-rpm' after 121 ms
[21:53:35] Starting 'vscode-linux-x64-build-rpm'...
Building target platforms: x86_64
Building for target x86_64
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.h5wnPs
+ umask 022
+ cd /home/egdoc/vscode/.build/linux/rpm/x86_64/rpmbuild/BUILD
+ mkdir -p /home/egdoc/vscode/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.30.0-1542228814.el7.x86_64/usr/share/code-oss
+ mkdir -p /home/egdoc/vscode/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.30.0-1542228814.el7.x86_64/usr/share/applications
+ mkdir -p /home/egdoc/vscode/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.30.0-1542228814.el7.x86_64/usr/share/pixmaps
+ cp -r usr/share/code-oss/* /home/egdoc/vscode/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.30.0-1542228814.el7.x86_64/usr/share/code-oss
cp: cannot stat 'usr/share/code-oss/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.h5wnPs (%install)
    Bad exit status from /var/tmp/rpm-tmp.h5wnPs (%install)


RPM build errors:
[21:53:36] 'vscode-linux-x64-build-rpm' errored after 1.17 s
[21:53:36] Error: Command `HOME="$(pwd)/.build/linux/rpm/x86_64" fakeroot rpmbuild -bb .build/linux/rpm/x86_64/rpmbuild/SPECS/code-oss.spec --target=x86_64` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Unlike .rpm, .deb packages are created without problems.

**Comment by joaomoreno** [comment]
Did you run `yarn gulp vscode-linux-x64-min` beforehand?

**Comment by egdoc** [comment]
Yes, the ` vscode-linux-x64-min` command is executed without errors. Also` yarn gulp vscode-linux-x64-build-deb` produces the deb package.
I noticed that the error is generated when executing  the %install section of the vscode/resources/linux/rpm/code.spec.template.

**Comment by sergei-dyshel** [comment]
@egdoc
Try building RPM *after* running `vscode-linux-x64-min`.

**Comment by Tyriar** [comment]
This definitely works as we ship an rpm, you can look at what our build machine does here https://github.com/Microsoft/vscode/blob/master/build/azure-pipelines/linux/publish.sh
