### ISSUE TITLE
VS becomes unresponsive when editing an IDL file, no folder opened.

### ISSUE THREAD

**Issue by DevGavin** [Microsoft/vscode#63172]
Issue Type: <b>Bug</b>

```
[VS Code]: detected unresponsive
[main 2:51:15 PM] [VS Code]: detected unresponsive
[main 2:51:35 PM] [uncaught exception in main]: SyntaxError: Unexpected token o in JSON at position 0
[main 2:51:35 PM] SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at c (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:177:254)
    at e.onRawMessage (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:178:948)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:178:528
    at e.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:185:795
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:478
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:705
    at e.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at EventEmitter.r (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:127:987)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (C:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
[main 2:51:35 PM] [uncaught exception in main]: SyntaxError: Unexpected token o in JSON at position 0
[main 2:51:35 PM] SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at c (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:177:254)
    at e.onBuffer (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:182:571)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:180:669
    at e.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:185:795
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:478
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:705
    at e.fire (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at EventEmitter.r (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:127:987)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (C:\Program Files\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
IPC client with id 'window:1' is already registered.
```

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (17.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by joaomoreno** [comment]
Those are strange... It's as if someone is messing around our IPC channels, eg writing to them. @DevGavin Does this reproduce after restarting your machine?

**Comment by DevGavin** [comment]
It happened 1 month ago and I don't have the repro any more. As I remember, it repro'ed even after restarting my machine. Since it does not repro any more, you may close it and I will re-activate if I ever see it again.

**Comment by jrieken** [comment]
ok, closing for now. thanks for getting back to us
