### ISSUE TITLE
Cannot debug code in VS Code, but can in other IDEs

### ISSUE THREAD

**Issue by manjchana** [Microsoft/vscode#63207]
Issue Type: <b>Bug</b>

Hi,

I have created a test script simply of one command - "import getpass". I cannot run and debug this script in VS Code, it fails when trying to import certain any module. 

I have disabled extensions, reinstalled VS Code, reinstalled extensions, tried the portable version of VS Code, but still no luck. The code will not run in VS code, but will run in other applications such as Python's IDLE, Notepad++ and PythonWin.

The error encountered is listed below:

Traceback (most recent call last):
  File "c:\Users\mchana\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd_launcher.py", line 38, in <module>
    main(sys.argv)
  File "c:\Users\mchana\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 265, in main
    wait=args.wait)
  File "c:\Users\mchana\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 258, in handle_args
    debug_main(addr, name, kind, *extra, **kwargs)
  File "c:\Users\mchana\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 45, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "c:\Users\mchana\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "c:\Users\mchana\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 140, in _run
    _pydevd.main()
  File "c:\Users\mchana\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1936, in main
    if setup['cmd-line']:
TypeError: 'NoneType' object is not callable

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz (8 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (10.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.10.1

</details>

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-python#3370
