### ISSUE TITLE
Can't install .NET Core Debugger with latest dotnet

### ISSUE THREAD

**Issue by ppekrol** [Microsoft/vscode#6322]
- VSCode Version: 1.1.0
- OS Version: Win10 Pro x64
- dotnet --version => 1.0.0-preview1-002702

Steps to Reproduce:

1. Installed latest VSCode (first time)
2. Added C# extension
3. Opened *.cs file
4. 

Downloading and configuring the .NET Core Debugger...
Telemetry is: Enabled
log  : Restoring packages for C:\Users\ppekr\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.json...
info : Committing restore...
log  : Writing lock file to disk. Path: C:\Users\ppekr\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.lock.json
log  : C:\Users\ppekr\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.json
log  : Restore completed in 936ms.

NuGet Config files used:
    C:\Users\ppekr\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\NuGet.config

Feeds used:
    https://www.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/coreclr-debug/api/v3/index.json
Telemetry is: Enabled
Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

System.InvalidOperationException: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
   at Microsoft.DotNet.ProjectModel.BuildWorkspace.GetRuntimeContext(ProjectContext context, IEnumerable`1 runtimeIdentifiers)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass71_0.<SelectContexts>b__1(ProjectContext c)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1
Error while installing .NET Core Debugger.

**Comment by isidorn** [comment]
This sounds like an issue with the C# extension. Can you please file this issue in their repo?
https://github.com/OmniSharp/omnisharp-vscode
