### ISSUE TITLE
 debug  simple codes which import pyglib " IndexError: list index out of range". but works directly

### ISSUE THREAD

**Issue by angrysword** [Microsoft/vscode#63259]
- VSCode Version: 1.28.1
- OS Version: windows 10

Steps to Reproduce:

1.  install pyglib
2. add a file test.py include the following python code

from pyglib import app, gflags, log

gflags.DEFINE_integer('bananas', 7, 'Number of bananas.')

FLAGS = gflags.FLAGS

def main(args):
    log.info('There are %s bananas.', FLAGS.bananas)
    log.debug('This will only show up if you run with --verbosity=10')

if __name__ == '__main__':
    app.run()

3. run current file in the GUI. will have error. run it outside python test.py. works well.

The error will show

Traceback (most recent call last):
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd_launcher.py", line 38, in <module>
    main(sys.argv)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 265, in main
    wait=args.wait)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 258, in handle_args
    debug_main(addr, name, kind, *extra, **kwargs)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 45, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 140, in _run
    _pydevd.main()
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1925, in main
    debugger.connect(host, port)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1283, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1290, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "c:\Users\caofamily\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "c:\Users\xxx\Documents\python_test\pygtest.py", line 16, in <module>
    app.run()
  File "C:\Users\xxx\Anaconda3\envs\python352\lib\site-packages\pyglib\app.py", line 57, in run
    rt = mainmodule.main(positional_args)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 262, in main
    args, extra = parse_args(argv)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2018.10.1\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 91, in parse_args
    prog = argv[0]
IndexError: list index out of range

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by angrysword** [comment]
I do not get it. What extension are you talking?  why a stupid vscodebot can close the issue.

**Comment by weinand** [comment]
VS Code does not support Python debugging out of the box.
You have installed the Python extension for this functionality.
So if there is an issue with Python debugging you will have to file this issue against the Python extension since the VS Code cannot help.
