### ISSUE TITLE
I want to learn about extendsion , but I get this exception  and I have no idea at all.

### ISSUE THREAD

**Issue by 756445638** [Microsoft/vscode#63375]
```
Exception has occurred: Error
Error: Cannot find module 'supports-color'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at n (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\node.js:29:23)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\node.js:188:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\index.js:9:20)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\node_modules\debug\src\index.js:12:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\index.js:11:13)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\http-proxy-agent\index.js:113:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\index.js:17:22)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\index.js:134:3)
    at Module.t._initNodeRequire.o._compile (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at t.load (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:415)
    at e.load (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:813)
    at i (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:217)
    at Object.errorback (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:28:338)
    at e.triggerErrorback (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:14:176)
    at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:883
    at ReadFileContext.callback (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:626)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by 756445638** [comment]
I still have thie issue when I "open folder with code" ...

**Comment by mjbvz** [comment]
Please follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) to submit a proper issue report. This should include:

- What are you trying to do?
- What went wrong?
- Steps to reproduce the problem
