### ISSUE TITLE
VSCode freezes while using debug (PHP XDebug)

### ISSUE THREAD

**Issue by lwxbr** [Microsoft/vscode#63449]
I don't know if is the extension is related to the issue but I quote here because the problem only happens when I'm using the extension.

Motivation of this issue: #63432

- VSCode Version: 1.29.0
- OS Version: Windows 10 Home Single Language

Steps to Reproduce:

1. Open VSCode
2. Install and use this extension: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug
3. Program in PHP for a while and wait until it bugs.

Does this issue occur when all extensions are disabled?: No

Extra information:

**main.log:**
```
[2018-11-19 16:42:16.775] [main] [info] update#setState idle
[2018-11-19 16:42:46.776] [main] [info] update#setState checking for updates
[2018-11-19 16:42:46.999] [main] [info] update#setState downloading
[2018-11-19 16:42:47.004] [main] [info] update#setState downloaded
[2018-11-19 17:15:55.218] [main] [error] [VS Code]: detected unresponsive
[2018-11-19 17:16:01.475] [main] [error] [uncaught exception in main]: SyntaxError: Unexpected token o in JSON at position 0
[2018-11-19 17:16:01.475] [main] [error] SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at c (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:177:254)
    at e.onRawMessage (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:178:948)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:178:528
    at e.fire (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:185:795
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:478
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:705
    at e.fire (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at EventEmitter.r (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:127:987)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
[2018-11-19 17:16:01.476] [main] [error] [uncaught exception in main]: SyntaxError: Unexpected token o in JSON at position 0
[2018-11-19 17:16:01.476] [main] [error] SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at c (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:177:254)
    at e.onBuffer (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:182:571)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:180:669
    at e.fire (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:185:795
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:478
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:705
    at e.fire (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at EventEmitter.r (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:127:987)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

**Comment by roblourens** [comment]
This sounds like the issue we fixed in 1.29.1, please upgrade and tell me if it still happens https://github.com/Microsoft/vscode/issues/62970

**Comment by lwxbr** [comment]
Up to 1.29.1 and watching for bugs. If any I post here. Thanks for info @roblourens. Out.

**Comment by lwxbr** [comment]
Reporting new freeze after update to 1.29.1, this is the log:

**About section:**
Versão: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Data: 2018-11-15T19:11:49.509Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Arquitetura: ia32

**main.log:**
```
[2018-11-21 09:32:26.917] [main] [info] update#setState idle
[2018-11-21 09:32:56.918] [main] [info] update#setState checking for updates
[2018-11-21 09:32:57.136] [main] [info] update#setState downloading
[2018-11-21 09:34:30.401] [main] [info] update#setState updating
[2018-11-21 09:34:41.330] [main] [info] update#setState ready
[2018-11-21 10:14:01.468] [main] [error] [VS Code]: detected unresponsive
[2018-11-21 10:14:16.056] [main] [error] [uncaught exception in main]: SyntaxError: Unexpected token o in JSON at position 0
[2018-11-21 10:14:16.056] [main] [error] SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at c (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:177:254)
    at e.onRawMessage (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:178:948)
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:178:528
    at e.fire (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:185:795
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:478
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:705
    at e.fire (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at EventEmitter.r (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:127:987)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
[2018-11-21 10:14:16.056] [main] [error] [uncaught exception in main]: SyntaxError: Unexpected token o in JSON at position 0
[2018-11-21 10:14:16.056] [main] [error] SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at c (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:177:254)
    at e.onBuffer (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:182:571)
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:180:669
    at e.fire (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:185:795
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:478
    at C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:120:705
    at e.fire (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:122:218)
    at EventEmitter.r (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:127:987)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (C:\Users\Lucas Vendramini\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```

**Comment by lwxbr** [comment]
@roblourens, yup, specifically when I use the debug, it freezes and I'm forced to close the editor. The main difficult is get the profile WHEN it freezes, that should spit in a log file before VSCode freezes. I will try out.

**Comment by lwxbr** [comment]
I will close this issue because I didn't observed errors anymore related to it. Thanks @roblourens and all the collaborators for the attention given, in case of any problems, please reopen this issue to discuss what is causing the problem if any.
