### ISSUE TITLE
Powershell Terminal long command exception

### ISSUE THREAD

**Issue by agonzalezm** [Microsoft/vscode#63670]
- VSCode Version: 1.28.2
- OS Version: Windows 10

Steps to Reproduce:

1. Run Long powershell command line  in Terminal and this error happens:

An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 3000.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.MoveCursorToIndex(Int32 promptStartCol, Int32 promptStartRow, Int32 consoleWidth, Int32 newCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__95.MoveNext()

**Comment by Tyriar** [comment]
Looks like a powershell issue, create an issue here if you're using the extension https://github.com/PowerShell/vscode-powershell, otherwise to the main repo?
