### ISSUE TITLE
tsserver failing

### ISSUE THREAD

**Issue by jacobjojan** [Microsoft/vscode#63698]
Issue Type: <b>Bug</b>

(h:\Projects\project1\node_modules\typescript\lib\tsserver.js:98831:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
vscode-markdownlint|Dav|0.21.0
gitlens|eam|8.5.6
vscode-jest|Ort|2.9.2
tsimporter|pmn|1.2.14
typescript-hero|rbb|3.0.0
sass-indented|rob|1.4.9
angular-follow-selector|san|1.2.0
git-merger|sha|0.4.1
move-ts|str|1.11.3

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
