### ISSUE TITLE
SCMViewlet creates many, many action items

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#63693]
With the new listener leak limit being 100 and *without* https://github.com/Microsoft/vscode/commit/0e86dd639b51c2a546ae304e8dd64a3be6cc009f you can see the following warnings on the console while scrolling up/down in a full SCM viewlet

```
at ContextAwareMenuItemActionItem.MenuItemActionItem.render (file:///Users/jrieken/Code/vscode/out/vs/platform/actions/browser/menuItemActionItem.js:168:50)
    at file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:505:22
    at Array.forEach (<anonymous>)
    at ActionBar.push (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:487:21)
    at updateActions (file:///Users/jrieken/Code/vscode/out/vs/workbench/parts/scm/electron-browser/scmViewlet.js:415:36)
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:223:38)
    at Menu.<anonymous> (file:///Users/jrieken/Code/vscode/out/vs/platform/actions/common/menu.js:33:40)
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:226:41)
    at file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:441:37
```

<img width="831" alt="screenshot 2018-11-23 at 16 17 43" src="https://user-images.githubusercontent.com/1794099/48950426-62882a80-ef3b-11e8-9dff-637892113dd3.png">

**Comment by joaomoreno** [comment]
@jrieken Good catch. This is a consequence of menus having coarse "I just changed" events. I then create the action array for that menu and from there create the matching action item array. As the fix, I introduce an action cache, so I can do `array.equals` and avoid creating action items for those actions if they are the same as before. I wonder if that caching could be pushed further down and have the "alive" menu compute that difference itself and not emit that event if nothing has changed?

**Comment by joaomoreno** [comment]
I pay attention to the menu change event for when context keys change, eg git contributes different actions depending on the state of the repo.

**Comment by joaomoreno** [comment]
Yes. I do it for when context keys change.

**Comment by mjbvz** [comment]
I'm still seeing the following potential leak in latest master:

```
   at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:506:20
    at Object.onFirstListenerAdd (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:429:32)
    at _event (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:164:44)
    at new Menu (file:///Users/matb/projects/vscode/out/vs/platform/actions/common/menu.js:31:164)
    at MenuService.createMenu (file:///Users/matb/projects/vscode/out/vs/platform/actions/common/menuService.js:23:20)
    at ResourceRenderer.renderElement (file:///Users/matb/projects/vscode/out/vs/workbench/parts/scm/electron-browser/scmViewlet.js:417:41)
    at PipelineRenderer.renderElement (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listWidget.js:632:26)
    at ListView.insertItemInDOM (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:266:22)
    at ListView.render (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:230:26)
    at ListView.onScroll (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:426:22)
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:226:41)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:123:33
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:223:38)
    at Scrollable._setState (file:///Users/matb/projects/vscode/out/vs/base/common/scrollable.js:227:28)
    at Scrollable.setScrollPositionNow (file:///Users/matb/projects/vscode/out/vs/base/common/scrollable.js:160:18)
    at ScrollableElement.AbstractScrollableElement._onMouseWheel (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:278:42)
    at HTMLDivElement.onMouseWheel (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:233:27)
```

This was after staging `node_modules` and scrolling through the changes list

**Comment by mjbvz** [comment]
Actually, I'll open a new issue since I don't see the action item problem anymore
