### ISSUE TITLE
NPE with Spring Boot Data LDAP

### ISSUE THREAD

**Issue by zhangqi26** [Microsoft/vscode#63694]
- VSCode Version: 1.29.1
- OS Version: Win and Mac

Steps to Reproduce:

1. This is a very basic demo about Spring Data for LDAP in unit testing. Please refer to the following code: 

@RunWith(SpringRunner.class)
@DataLdapTest
public class DirectoryTests {

    @Autowired
    private LdapTemplate ldapTemplate;

    @Test
    public void whenFindByTitleThenReturnDiscipline() {
        LdapQuery query = LdapQueryBuilder.query().where("objectclass").is("person");

        List<String> list = ldapTemplate.search(query, new AttributesMapper<String>() {
            public String mapFromAttributes(Attributes attrs)
                    throws NamingException {
                return (String) attrs.get("cn").get();
            }
        });

        assertThat(list.size()).isEqualTo(3);
    }
}

2. The same code runs well with IntelliJ, but got the following error message with VS Code:

java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at org.springframework.ldap.core.support.SimpleDirContextAuthenticationStrategy.setupEnvironment(SimpleDirContextAuthenticationStrategy.java:42)
	at org.springframework.ldap.core.support.AbstractContextSource.setupAuthenticatedEnvironment(AbstractContextSource.java:194)
	at org.springframework.ldap.core.support.AbstractContextSource.getAuthenticatedEnv(AbstractContextSource.java:582)
	at org.springframework.ldap.core.support.AbstractContextSource.doGetContext(AbstractContextSource.java:134)
	at org.springframework.ldap.core.support.AbstractContextSource.getReadOnlyContext(AbstractContextSource.java:158)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:357)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:309)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:616)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:586)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:1651)
	at cn.focusmedia.workforce.directory.DirectoryTests.whenFindByTitleThenReturnDiscipline(DirectoryTests.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at com.microsoft.java.test.runner.junit4.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at com.microsoft.java.test.runner.junit4.CustomizedJUnit4CoreRunner.run(CustomizedJUnit4CoreRunner.java:45)
	at com.microsoft.java.test.runner.junit4.JUnit4Launcher.execute(JUnit4Launcher.java:30)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:53)

Does this issue occur when all extensions are disabled?: Yes/No

With all extensions disabled, Java won't work, will it?

**Comment by alexr00** [comment]
This sounds like an issue with the extension you're using. Does that extension have a repository you can report the issue to?

**Comment by zhangqi26** [comment]
I cannot root cause which extension, though I think it might be Java Extension Pack owned by Microsoft. Which might be the right repository? Thanks.

**Comment by alexr00** [comment]
Go to the info page for the extension and it should have a link somewhere for reporting issues.

**Comment by zhangqi26** [comment]
Thanks, I posted the issue here: https://github.com/Microsoft/vscode-java-pack/issues/71
