### ISSUE TITLE
Hovering over SCSS nested @at-root  causes an error with the CSS lang server

### ISSUE THREAD

**Issue by abdullahseba** [microsoft/vscode#63805]
When hovering over a nested `@at-root` in scss vscode pops up with the css language server which shows the following:
```
[Error - 8:46:11 PM] Error while computing hover for file:///c%3A/Users/abdul/Documents/GitHub/theme-pack/src/core/scss/%40abstract/_mixins.scss: Cannot read property 'findAttribute' of null
TypeError: Cannot read property 'findAttribute' of null
    at e.doPrintElement (c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:550944)
    at e.doPrint (c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:550741)
    at e.print (c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:550594)
    at Pn (c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:553619)
    at e.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:555264)
    at l.runSafe (c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:71000)
    at Immediate.setImmediate (c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain.js:1:96171)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

```
This only happens if `@at-root` is nested within a mixin or class, and not when its use independently. 
It's mostly just annoying as when you move the mouse around, the terminal will switch to the output tab.
Or it pops up if it as already closed.
I have noticed this issue some time ago. it wasn't specific to this version of VSCode.

System info:
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Create an empty scss file.
2. Add the following:
```scss
.test {
    @at-root {
    }
  }
```
2. Hover over `@at-root`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by abdullahseba** [comment]
Bad boy bot. Completely unrelated _plus_ dead link.

**Comment by mjbvz** [comment]
This is still broken in insiders.. I suspect that we just need to pick up a new version of `vscode-css-languageservice` that includes the fix

Adding @aeschli since @octref is out

**Comment by aeschli** [comment]
Updated service...

**Comment by mjbvz** [comment]
Closing and marked as verified since the update seems to have fix it in insiders
