### ISSUE TITLE
Peek references broken 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#63978]
Open any typescript file, context menu, peek references, the view is broken.
Example: open `editorPart.ts`, peek referneces on `IEditorPartUIState`

![screenshot 2018-11-29 at 11 17 59](https://user-images.githubusercontent.com/1926584/49215328-d5c0ef00-f3c8-11e8-8582-37f0b920cd15.png)

Here's the exception
```
 ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at i.e.getDataNode (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:970:492)
    at i.e.reveal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:969:673)
    at r.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2403:15)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:181:275
    at Object.s.__generator.a.label [as next] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:181:380)
    at o (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:180:479)
    at new Promise (<anonymous>)
    at o (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:180:256)
    at r._revealReference (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2402:682)
    at r.setSelection (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2401:205)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2410:375
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by joaomoreno** [comment]
This is something else. This is the special case in which the references tree doesn't render file names since all references are in the same file. You see to attempt to reveal the file row, when it was never rendered.
