### ISSUE TITLE
"potential listener LEAK detected", while running extension tests in VS Code

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64039]
Issue Type: <b>Bug</b>

**Repo**
1. In the vscode code base, use the debugger to `TypeScript extension tests` a few times. I had the debug console window open while doing this

**bug**
In dev tools, see:

```
 potential listener LEAK detected, having 673 listeners already. MOST frequent listener (45):
 at onDidRegisterExtensions (./workbench/browser/labels.ts:67:39)
  at registerListeners (./workbench/browser/labels.ts:61:7)
  at call (./workbench/browser/labels.ts:281:2)
  at apply (./base/common/types.ts:165:6)
  at apply (./platform/instantiation/common/instantiationService.ts:104:19)
  at _createInstance (./platform/instantiation/common/instantiationService.ts:69:17)
  at createInstance (./workbench/parts/scm/electron-browser/scmViewlet.ts:508:46)
  at renderTemplate (./base/browser/ui/list/listWidget.ts:845:35)
  at map (./base/browser/ui/list/listWidget.ts:845:24)
  at renderTemplate (./base/browser/ui/list/rowCache.ts:42:33)
  at alloc (./base/browser/ui/list/listView.ts:335:25)
  at insertItemInDOM (./base/browser/ui/list/listView.ts:214:9)
  at _splice (./base/browser/ui/list/listView.ts:148:15)
  at splice (./base/browser/ui/list/splice.ts:17:34)
  at forEach (./base/browser/ui/list/splice.ts:17:19)
  at splice (./base/browser/ui/list/listWidget.ts:1033:56)
  at fn (./base/common/event.ts:488:12)
  at bufferEvents (./base/browser/ui/list/listWidget.ts:1033:21)
  at splice (./workbench/parts/scm/electron-browser/scmViewlet.ts:661:18)
  at onDidSpliceGroups (./workbench/parts/scm/electron-browser/scmViewlet.ts:615:7)
  at ./workbench/parts/scm/electron-browser/scmViewlet.ts:916:23
  at call (./base/common/event.ts:225:18)
  at fire (./workbench/parts/scm/electron-browser/scmViewlet.ts:1216:30)
  at setVisible (./workbench/browser/parts/compositePart.ts:280:12)
  at showComposite (./workbench/browser/parts/compositePart.ts:146:7)
  at doOpenComposite (./workbench/browser/parts/compositePart.ts:110:14)
  at openComposite (./workbench/browser/parts/sidebar/sidebarPart.ts:142:14)
  at openViewlet (./workbench/services/viewlet/browser/viewletService.ts:73:43)
  at openViewlet (./workbench/browser/parts/activitybar/activitybarActions.ts:69:29)
  at run (./base/common/actions.ts:209:31)
  at runAction (./base/common/actions.ts:201:14)
  at run (./base/browser/ui/actionbar/actionbar.ts:170:21)
  at onClick (./base/browser/ui/actionbar/actionbar.ts:140:37)
```

VS Code version: Code - Insiders 1.30.0-insider (cd5b4d1bb3fc7e509fba077095b2b280b8ff7161, 2018-11-29T06:12:26.485Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
I actually see this potential leak as well:

```
  at onDidChangeDecorations (./workbench/browser/labels.ts:73:41)
  at registerListeners (./workbench/browser/labels.ts:61:7)
  at apply (./base/common/types.ts:165:6)
  at apply (./platform/instantiation/common/instantiationService.ts:104:19)
  at _createInstance (./platform/instantiation/common/instantiationService.ts:69:17)
  at createInstance (./workbench/parts/debug/browser/loadedScriptsView.ts:520:41)
  at renderTemplate (./base/parts/tree/browser/treeView.ts:63:41)
  at alloc (./base/parts/tree/browser/treeView.ts:298:33)
  at insertInDOM (./base/parts/tree/browser/treeView.ts:1665:7)
  at insertItemInDOM (./base/parts/tree/browser/treeView.ts:703:8)
  at render (./base/parts/tree/browser/treeView.ts:527:8)
  at call (./base/common/event.ts:223:15)
  at fire (./base/browser/ui/scrollbar/scrollableElement.ts:177:18)
  at call (./base/common/event.ts:223:15)
  at fire (./base/common/scrollable.ts:334:17)
  at _setState (./base/common/scrollable.ts:221:7)
  at setScrollDimensions (./base/browser/ui/scrollbar/scrollableElement.ts:260:19)
  at setScrollDimensions (./base/parts/tree/browser/treeView.ts:876:25)
  at scrollTop (./base/parts/tree/browser/treeView.ts:771:19)
  at onRowsChanged (./base/parts/tree/browser/treeView.ts:763:7)
  at call (./base/common/event.ts:225:18)
```

**Comment by joaomoreno** [comment]
Moved the last one to https://github.com/Microsoft/vscode/issues/64439
