### ISSUE TITLE
I can't Solve This error : vs code not open .. No network

### ISSUE THREAD

**Issue by MA-Norouzifar** [Microsoft/vscode#64064]
i search a lot on github and google for solved this error but can't find any solution ... 
i find this links but not help me :
https://github.com/Microsoft/vscode/issues/61044
https://github.com/Microsoft/vscode/issues/59477
https://github.com/Microsoft/vscode/issues/59634
https://github.com/Microsoft/vscode/issues/58830
https://github.com/Microsoft/vscode/issues/56623

realy what i can do .......................?
error :
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
tslint|eg2|1.0.40
code-runner|for|0.9.5
beautify|Hoo|1.4.7
python|ms-|2018.11.0
cpptools|ms-|0.21.0-insiders
csharp|ms-|1.17.1
vsliveshare|ms-|0.3.1005
debugger-for-chrome|msj|4.11.1
LiveServer|rit|5.3.1
vscode-icons|rob|7.28.0

</details>

**Comment by MA-Norouzifar** [comment]
bad bad and vs code is bad  error  always error : vs code 👎 

dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13



giv me a video a file any things for this issues .. set ELECTRON_ENABLE_LOGGING=true   not help meeeeeeeee

**Comment by MA-Norouzifar** [comment]
Help Me..............................

**Comment by MA-Norouzifar** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Crash at launch when no network (#61044)](https://www.github.com/Microsoft/vscode/issues/61044)
> * [cannot start VSCode when offline (#61652)](https://www.github.com/Microsoft/vscode/issues/61652)
> * [Cannot start  VSCode without network (#62535)](https://www.github.com/Microsoft/vscode/issues/62535)
> * [Not opening  (#61302)](https://www.github.com/Microsoft/vscode/issues/61302)
> * [code fails to launch if DNS is unavailable since 1.29.1 (#63585)](https://www.github.com/Microsoft/vscode/issues/63585)

giv me a video a file any things for this issues .. set ELECTRON_ENABLE_LOGGING=true not help meeeeeeeee


i cant't find any way ... help me

**Comment by hossmf** [comment]
same issue here!

**Comment by hossmf** [comment]
Which company in the world launch a program that doesn't launch? Funny Microsoft! 😂
