### ISSUE TITLE
Insiders and RC3?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#6408]
- VSCode Version:1.1.1-Insider
- OS Version: Mac 10.10.5 

Steps to Reproduce:

1. Upgrade to RC2 from RC1-Updatesomething, using the instructions provided for .Net Core
2. Upgrade VSCode, see lots of log messages about how it's installing RC3 ... which I don't get, given that I just installed RC2 - did I miss the memo about Insiders using RC3 when RC2 comes out?
But then, clicking on the release notes, leads me to 1.2.0 release notes, for May 2016, and looks like an empty template...And finally, it looks like 10.10.x64 is getting left behind...and I must have not seen it, because the logs are saying that "The project does not list one of 'osx.10.10-x64' in the 'runtimes' section." And it suggests that I run dotnet restore, which I do, but then it downloads rc-1 stuff, which I no longer want...Actually, here's the full set of errors which came at the end:

Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'osx.10.10-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.10-x64' in the 'runtimes' section.
Error: 

System.InvalidOperationException: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'osx.10.10-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.10-x64' in the 'runtimes' section.
   at Microsoft.DotNet.ProjectModel.BuildWorkspace.GetRuntimeContext(ProjectContext context, IEnumerable`1 runtimeIdentifiers)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1
Error while installing .NET Core Debugger.

So lots going on here.

**Comment by isidorn** [comment]
This looks like an issue with the C# extension, please file it against this repository
https://github.com/OmniSharp/omnisharp-vscode
