### ISSUE TITLE
can not open vscode 1.29 without internet 

### ISSUE THREAD

**Issue by MA-Norouzifar** [Microsoft/vscode#64083]
can not open vscode 1.29 without internet 
https://github.com/Microsoft/vscode/issues/64064

error :
dns.js:246
this._handle = new ChannelWrap();
^

Error: EFILE
at new Resolver (dns.js:246:20)
at dns.js:377:25
at dns.js:431:3
at NativeModule.compile (bootstrap_node.js:606:7)
at NativeModule.require (bootstrap_node.js:550:18)
at net.js:45:13
at net.js:1730:3
at NativeModule.compile (bootstrap_node.js:606:7)
at NativeModule.require (bootstrap_node.js:550:18)
at internal/child_process.js:6:13

**Comment by MA-Norouzifar** [comment]
vscodebot sheet!!!!!!!!!!!!!!!!!!!!!!!!!

Give me a true solution   ...............................  i an't read a lot of issues or topic And in the end no solution can be found

**Comment by hossmf** [comment]
same issue here!
