### ISSUE TITLE
potential listener LEAK detected:  at FileMatch.registerListeners

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#64120]
Steps to Reproduce:

1. open vscode workspace
2. search for "storageService"

```
at FileMatch.registerListeners (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:157:46)
    at FileMatch [as constructor] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:133:19)
    at create (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:107:35)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:76:31)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:407:66
    at Array.forEach (<anonymous>)
    at FolderMatch.add (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:394:17)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:596:33
    at Map.forEach (<anonymous>)
    at ResourceMap.forEach (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/map.js:428:22)
    at SearchResult.add (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:590:26)
    at SearchModel.onSearchProgress (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:857:36)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/search/common/searchModel.js:792:23
    at onProviderProgress (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/search/node/searchService.js:102:25)
    at progressCallback (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/search/node/searchService.js:136:25)
    at Array.forEach (<anonymous>)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/search/node/searchService.js:517:45
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:223:38)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:226:41)
    at handler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.js:380:59)
    at ChannelClient.onResponse (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.js:432:17)
    at ChannelClient.onBuffer (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.js:421:33)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.js:285:91
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:223:38)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.cp.js:146:44
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:223:38)
    at ChildProcess.fn (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:701:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

/cc @jrieken

**Comment by bpasero** [comment]
Not sure if the leak warning needs to be adjusted for this case or search should somehow install global listener for all results instead of one per result.

**Comment by jrieken** [comment]
> Also the leak check is not free, maybe that's a +1 for reducing the number of calls

That's because it captures a stack trace. Not sure how often events have been registered to get to 33ms. Please file a new issue when you see this often, we can then disable the warning for stable builds

**Comment by roblourens** [comment]
This was for a typical text search. But what do you think I should be doing here, ignore the warning for now, move the listener to be registered less often, or come up with a way to disable it for this particular instance?

**Comment by jrieken** [comment]
> or come up with a way to disable it for this particular instance?

You can already do that - each emitter can be configured individually using the `EmitterOptions`. However, having the container listen instead of its children is often the better approach, esp the all listeners are the same.

**Comment by roblourens** [comment]
I mean instance of the listener, but yeah moving the listener is better, I will do that in debt week.

**Comment by roblourens** [comment]
Actually the warning is not a good look, I'll do it in November...

**Comment by bpasero** [comment]
@roblourens there are still many more warnings printed when doing a search+replace over > 100 files because we easily create more than 100 text models for the text edit and tons of listeners are being created temporarily. Honestly I do not even know how to fix that other than maybe disposing the models in chunks of a 100 while doing the replace operation (/cc @sandy081 @jrieken)

**Comment by sandy081** [comment]
Its also the same when we do rename that touches hundreds of files. No idea how to fix such.
