### ISSUE TITLE
DirtyDiff listener leak?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64238]
Found this in the console after typing for while...

```
/Users/jrieken/Code/vscode/out/vs/base/common/event.js:113 [5gh] potential listener LEAK detected, having 398 listeners already. MOST frequent listener (299):
LeakageMonitor.check @ /Users/jrieken/Code/vscode/out/vs/base/common/event.js:113
/Users/jrieken/Code/vscode/out/vs/base/common/event.js:114     at TextModel.onDidChangeContent (file:///Users/jrieken/Code/vscode/out/vs/editor/common/model/textModel.js:230:39)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.js:871:71
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jrieken** [comment]
Setting a breakpoint shows a fishy amount of listeners...

<img width="452" alt="screenshot 2018-12-03 at 17 39 40" src="https://user-images.githubusercontent.com/1794099/49387571-72b1be00-f722-11e8-994a-05d1986b0691.png">

**Comment by jrieken** [comment]
verified via review
