### ISSUE TITLE
Listener leak in diryDiffDecorator

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64259]
Issue Type: <b>Bug</b>

**Repo**
1. In a js file:

```js
console
```
1. Keep typing `.l` then hitting enter to accep the log suggestion. Undo a repeat

**Bug**
In dev tools console, see:

```
event.ts:96     at TextModel.onDidChangeContent (file:///Users/matb/projects/vscode/out/vs/editor/common/model/textModel.js:230:39)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.js:871:71
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Looks like we keep adding listeners for the same model over and over again: 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts#L1047

VS Code version: code-oss-dev 1.30.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by mjbvz** [comment]
Duplicate of #64238
