### ISSUE TITLE
errors when having no search provider

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64313]
Test #59922

* have an extension that contributes a file system but not a search provider (like the memfs sample)
* open file search (cmd+p)
* :bug: you see an error message pop up, the console also has errors

```
ERR No search provider registered for scheme: mem: Error: No search provider registered for scheme: mem
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4720:335
    at Array.forEach (<anonymous>)
    at t.searchWithProviders (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4720:170)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4719:412
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/58370

We need some warning or message but maybe we leave it in devtools but don't show a notification.
