### ISSUE TITLE
Potential leak detected in actionbar

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64467]
Issue Type: <b>Bug</b>

**repo**
Unclear. just noticed this in the dev tools console

**Bug**
In devtools console, see:
```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:188 [ce9] potential listener LEAK detected, having 100 listeners already. MOST frequent listener (1):

Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:188     at t [as constructor] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:913:330)
  at call (./base/browser/ui/actionbar/actionbar.ts:242:2)
  at ./base/browser/ui/actionbar/actionbar.ts:618:11
  at forEach (./base/browser/ui/actionbar/actionbar.ts:600:10)
  at push (./workbench/browser/parts/editor/tabsTitleControl.ts:438:15)
  at createTab (./workbench/browser/parts/editor/tabsTitleControl.ts:258:39)
  at openEditor (./workbench/browser/parts/editor/editorGroupView.ts:809:24)
  at doShowEditor (./workbench/browser/parts/editor/editorGroupView.ts:421:14)
  at restoreEditors (./workbench/browser/parts/editor/editorGroupView.ts:145:28)
  at apply (./base/common/types.ts:165:6)
  at apply (./platform/instantiation/common/instantiationService.ts:104:19)
  at _createInstance (./platform/instantiation/common/instantiationService.ts:69:17)
  at createInstance (./workbench/browser/parts/editor/editorGroupView.ts:59:30)
  at createFromSerialized (./workbench/browser/parts/editor/editorPart.ts:504:31)
  at doCreateGroupView (./workbench/browser/parts/editor/editorPart.ts:882:22)
  at fromJSON (./base/browser/ui/grid/grid.ts:453:29)
  at deserializeNode (./base/browser/ui/grid/grid.ts:446:35)
  at deserializeNode (./base/browser/ui/grid/grid.ts:482:32)
  at deserialize (./workbench/browser/parts/editor/editorPart.ts:876:38)
  at doCreateGridControlWithState (./workbench/browser/parts/editor/editorPart.ts:838:9)
  at doCreateGridControlWithPreviousState (./workbench/browser/parts/editor/editorPart.ts:810:8)
  at doCreateGridControl (./workbench/browser/parts/editor/editorPart.ts:787:7)
  at createContentArea (./workbench/browser/part.ts:53:26)
  at create (./workbench/electron-browser/workbench.ts:1067:18)
  at createEditorPart (./workbench/electron-browser/workbench.ts:1023:7)
  at renderWorkbench (./workbench/electron-browser/workbench.ts:280:7)
  at startup (./workbench/electron-browser/shell.ts:211:13)
  at createWorkbench (./workbench/electron-browser/shell.ts:181:24)
  at renderContents (./workbench/electron-browser/shell.ts:528:7)
  at open (./workbench/electron-browser/main.ts:146:10)
```

VS Code version: Code - Insiders 1.30.0-insider (85f805acf9436381b878cab5ab6c5146beec7893, 2018-12-05T12:13:44.894Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_7104198|
|Screen Reader|no|
|VM|18%|

</details>

**Comment by mjbvz** [comment]
Looks like a leaking action item. One idea is that `ActionBar.pull` does not disposed of the pulled item properly

**Comment by sbatten** [comment]
@bpasero `item.dispose()` needed in the `pull` function?

**Comment by mjbvz** [comment]
I think 2 out of the four callers of `pull` already do dispose of the item being removed. Not sure if a dispose call is needed in the other two case but probably worth reviewing

**Comment by bpasero** [comment]
@mjbvz I assume you just had >100 editors open that all restored on startup? That is the only time I can reproduce that issue.

I agree that the `pull` should probably `dispose` but that is unrelated to this issue. When closing a tab I verified that the action item gets disposed.
