### ISSUE TITLE
Potential leak in title control

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64470]
Issue Type: <b>Bug</b>

**Repo**
1. open an editor. 
1. Keep splitting the editor and then closing the split editors
1. Repeat a number of times

**Bug**
```
[8h7] potential listener LEAK detected, having 197 listeners already. MOST frequent listener (100):

event.ts:96     at ResourceContextKey [as constructor] (file:///Users/matb/projects/vscode/out/vs/workbench/common/resources.js:44:42)
    at create (file:///Users/matb/projects/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:107:35)
    at InstantiationService.createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:76:31)
    at TabsTitleControl.TitleControl [as constructor] (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/titleControl.js:52:58)
    at TabsTitleControl [as constructor] (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/tabsTitleControl.js:33:32)
    at create (file:///Users/matb/projects/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:107:35)
    at InstantiationService.createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:76:31)
    at EditorGroupView.createTitleAreaControl (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:321:73)
    at EditorGroupView.create (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:147:18)
    at EditorGroupView [as constructor] (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:69:19)
    at create (file:///Users/matb/projects/vscode/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:107:35)
    at InstantiationService.createInstance (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:76:31)
    at Function.EditorGroupView.createNew (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:77:41)
    at EditorPart.doCreateGroupView (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:447:63)
    at EditorPart.doAddGroup (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:421:37)
    at EditorPart.addGroup (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:414:30)
    at Object.splitEditor (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorCommands.js:355:43)
    at SplitEditorAction.BaseSplitEditorAction.run (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorActions.js:68:30)
    at file:///Users/matb/projects/vscode/out/vs/workbench/common/actions.js:80:59
    at <anonymous>
```

VS Code version: code-oss-dev 1.30.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|18%|

</details>

**Comment by bpasero** [comment]
I found another one in explorer view.
