### ISSUE TITLE
Potential listener leaks detected while scrolling through changes view 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64573]
Steps to Reproduce:

1. Stage `node_modules` (or a lot of files) in git
2. Scroll through the changes lists

**bug**
See these potential leaks reported:

```
   at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:506:20
    at Object.onFirstListenerAdd (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:429:32)
    at _event (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:164:44)
    at new Menu (file:///Users/matb/projects/vscode/out/vs/platform/actions/common/menu.js:31:164)
    at MenuService.createMenu (file:///Users/matb/projects/vscode/out/vs/platform/actions/common/menuService.js:23:20)
    at ResourceRenderer.renderElement (file:///Users/matb/projects/vscode/out/vs/workbench/parts/scm/electron-browser/scmViewlet.js:417:41)
    at PipelineRenderer.renderElement (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listWidget.js:632:26)
    at ListView.insertItemInDOM (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:266:22)
    at ListView.render (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:230:26)
    at ListView.onScroll (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/list/listView.js:426:22)
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:226:41)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:123:33
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:223:38)
    at Scrollable._setState (file:///Users/matb/projects/vscode/out/vs/base/common/scrollable.js:227:28)
    at Scrollable.setScrollPositionNow (file:///Users/matb/projects/vscode/out/vs/base/common/scrollable.js:160:18)
    at ScrollableElement.AbstractScrollableElement._onMouseWheel (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:278:42)
    at HTMLDivElement.onMouseWheel (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:233:27)
```

Scrolling is also rather janky

**Comment by joaomoreno** [comment]
Not a leak, just lost of event listeners which come and go.

Also related: https://github.com/Microsoft/vscode/issues/64503
