### ISSUE TITLE
Running yarn start or npm start gives Error 

### ISSUE THREAD

**Issue by byionline** [Microsoft/vscode#64678]
**My VS code Details:**
Version: 1.29.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**npm start or yarn start dont work max of the times Gives Following error:**

`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/test-app/public ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/test-app/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/test-app/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/test-app/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/test-app/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/home/test-app/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/test-app/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

In previous Version 1.27 
npm start works .

**Comment by byionline** [comment]
One Solution is run the following command for debain:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
For others visit:
[https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers](url)
