### ISSUE TITLE
Mac error when updating while offline

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64739]
From https://github.com/Microsoft/vscode/issues/60966

I see this on Mac:

- Go offline
- Click "Check for updates"
- In devtools:

```
  ERR context is not defined: ReferenceError: context is not defined
    at t.onError (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:347:147)
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:123:532)
    at AutoUpdater.r (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:129:235)
    at emitTwo (events.js:126:13)
    at AutoUpdater.emit (events.js:214:7)
```

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/update/electron-main/updateService.darwin.ts#L49

This builds because `context` is a global from mocha
