### ISSUE TITLE
"go to next error" for error in non-existent file - infinite retrying

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64767]
- The markers panel had an error in a file that had actually been deleted due to git operations. 
- I pressed F8 to navigate to the next error
- The editor title changed but the content didn't change
- I looked in devtools and saw it printing this over and over:

```
Unable to open 'dataTree.ts': File not found (file:///Users/roblou/code/vscode/src/vs/base/browser/ui/tree/dataTree.ts).
[snip]

ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at e.getElementLocation (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:214:266)
    at e.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:213:757)
    at i.e.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:962:723)
    at i.e.isExpanded (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:962:786)
    at t.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4710:827)
    at t.autoReveal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4710:647)
    at t.onActiveEditorChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4707:826)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:189:532)
    at t.doEmitActiveEditorChangeEvent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4720:942)
    at t.handleActiveEditorChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4720:718)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4721:55
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:189:512)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5170:861
    at Object.g [as _notify] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:167:807)
    at Object.enter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:171:85)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:932)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:373)
    at <anonymous>
```

So I debugged and found this stack:

```
t.run (gotoError.ts:373)
t.runEditorCommand (editorExtensions.ts:218)
(anonymous) (codeEditorWidget.ts:312)
e.invokeFunction (instantiationService.ts:54)
(anonymous) (codeEditorWidget.ts:311)
e.run (editorAction.ts:44)
(anonymous) (gotoError.ts:380)
g (winjs.base.js:1191)
enter (winjs.base.js:916)
_run (winjs.base.js:1089)
_chainedError (winjs.base.js:1052)
n (winjs.base.js:751)
then (winjs.base.js:1457)
enter (winjs.base.js:762)
_run (winjs.base.js:1089)
_setCompleteValue (winjs.base.js:1073)
v (winjs.base.js:1230)
enter (winjs.base.js:916)
_run (winjs.base.js:1089)
_error (winjs.base.js:1062)
n (winjs.base.js:758)
Promise rejected (async)
enter (winjs.base.js:762)
_run (winjs.base.js:1089)
_setCompleteValue (winjs.base.js:1073)
n.Class.define.cancel (winjs.base.js:1500)
wrap (winjs.base.js:1993)
t.doSetInput (editorControl.ts:175)
t.openEditor (editorControl.ts:67)
t.doShowEditor (editorGroupView.ts:793)
t.doOpenEditor (editorGroupView.ts:785)
t.openEditor (editorGroupView.ts:744)
t.doOpenEditor (editorService.ts:247)
t.openEditor (editorService.ts:240)
t.doOpenCodeEditor (codeEditorService.ts:64)
t.openCodeEditor (codeEditorService.ts:60)
t.run (gotoError.ts:373)
t.runEditorCommand (editorExtensions.ts:218)
(anonymous) (codeEditorWidget.ts:312)
e.invokeFunction (instantiationService.ts:54)
(anonymous) (codeEditorWidget.ts:311)
e.run (editorAction.ts:44)
(anonymous) (gotoError.ts:380)
... repeats forever
```

What seems to be happening is that we try to run `MarkerNavigationAction`,  `gotoError.ts:373` tries to open the code editor for the file, it fails but gets into the `then` with an editor anyway for some reason, and we get to `gotoError.ts:380` which tries to get the action with id `"editor.action.marker.nextInFiles"`, and run it in the new editor, but since the new editor didn't open and the uri check above fails, we recurse for all of eternity...

**Comment by bpasero** [comment]
Not a regression, I can reproduce in 1.29. I think this is a regression from the grid work where previously we would return `null` as editor when opening fails, but now we always return the active control. I can change that but would not feel good about changing this as a candidate.

**Comment by roblourens** [comment]
Oh ok, yeah not a candidate.

**Comment by bpasero** [comment]
@roblourens this was a really good one. A regression from Grid work.
