### ISSUE TITLE
Smoketest: Extensions install and activate vscode-smoketest-check extension

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64833]
```
       Extensions
         install and activate vscode-smoketest-check extension:
     Error: Timeout: is active element 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-editor textarea' after 20 seconds.
      at /Users/roblou/code/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
      at <anonymous>
```

**Comment by sandy081** [comment]
Cannot repro it anymore
