### ISSUE TITLE
Smoketest failure: Editor finds 'All References' to 'app'

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64830]
```
Error: Timeout: get elements '.monaco-editor .zone-widget .zone-widget-container.peekview-widget.reference-zone-widget.results-loaded .body .ref-tree.inline .monaco-tree-row .reference' after 20 seconds.
      at /Users/roblou/code/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
      at <anonymous>
```

**Comment by jrieken** [comment]
Like https://github.com/Microsoft/vscode/issues/64829, another sneaky CSS selector change that comes with the new tree.
