### ISSUE TITLE
Smoketest: Editor renames local 'app' variable

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64831]
```
       Editor
         renames local 'app' variable:
     Error: Timeout: is active element '.monaco-editor .monaco-editor.rename-box .rename-input' after 20 seconds.
      at /Users/roblou/code/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
      at <anonymous>
```

**Comment by alexandrudima** [comment]
@joaomoreno How would I proceed to tackle this one?

@roblourens This, obviously, does not reproduce for me.

**Comment by alexandrudima** [comment]
Commenting the previous test (find all references) makes this pass, so closing as dup #64830
