### ISSUE TITLE
Error while computing signature help for file:///d%3A/workspace/vue/test/test.html: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by linzhipenghn** [Microsoft/vscode#64952]
- VSCode Version: **1.30**
- OS Version: **win10 x64 1609**

Steps to Reproduce:

1. In VS Code. In an html file script block
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <script>
    let target = {}
    let proxy = new Proxy(target, {
      getPrototypeOf()
    })
  </script>
</body>
</html>
```
2. input 'getPrototypeOf()' **brackets** In terminal output
```
[Error - 12:35:57 PM] Error while computing signature help for file:///d%3A/workspace/vue/test/test.html: Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at hasContextSensitiveReturnExpression (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:40711:25)
    at checkFunctionExpressionOrObjectLiteralMethod (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:50582:61)
    at checkObjectLiteralMethod (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:51671:38)
    at checkObjectLiteral (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:47332:29)
    at checkExpressionWorker (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:51800:28)
    at checkExpression (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:51745:42)
    at checkExpressionWithContextualType (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:51575:26)
    at inferTypeArguments (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:48778:35)
    at chooseOverload (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:49237:49)
    at resolveCall (d:\software\vscode\resources\app\extensions\node_modules\typescript\lib\typescript.js:49165:26)
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/29032 to track this upstream
