### ISSUE TITLE
Missing file error  for pollyfill.ts when building editor-distro

### ISSUE THREAD

**Issue by ClarkFrench** [Microsoft/vscode#65040]
When building standalone editor  (gulp editor-distro) get error src/vs/editor/common/standalone/promise-pollyfill/pollyfille.ts no such file or directory.  This is from a cloned repository pulled today Dec 13 2018.

I did not get this error with build 1.29.0

**Comment by jrieken** [comment]
@alexandrudima there is still 
```
[09:29:10] Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/vscode/src/vs/editor/common/standalone/promise-polyfill/polyfill.ts'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
```

**Comment by dbaeumer** [comment]
I now get

```
[12:38:19] Node flags detected: --max_old_space_size=4095
[12:38:19] Respawned to PID: 21256
[12:38:33] Using gulpfile ~\Projects\mseng\VSCode\vscode\gulpfile.js
[12:38:33] Starting 'clean-editor-distro'...
[12:38:33] Starting 'clean-editor-esm'...
[12:38:33] Starting 'clean-editor-src'...
[12:38:33] Starting 'clean-minified-editor'...
[12:38:33] Starting 'clean-optimized-editor'...
[12:38:33] Starting 'clean-editor-build'...
[12:38:33] Finished 'clean-editor-distro' after 17 ms
[12:38:33] Finished 'clean-editor-esm' after 14 ms
[12:38:33] Finished 'clean-editor-src' after 16 ms
[12:38:33] Starting 'extract-editor-src'...
If the build fails, consider tweaking shakeLevel below to a lower value.
vs/editor/browser/editorExtensions.ts: - 275,6 - "Property 'finally' does not exist on type 'Promise<{}>'."
vs/editor/contrib/codeAction/codeActionWidget.ts: - 57,5 - "Property 'finally' does not exist on type 'Promise<any>'."
[12:38:52] 'extract-editor-src' errored after 19 s
[12:38:52] Error: Compilation Errors encountered.
    at Object.shake (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\lib\treeshaking.js:47:15)
    at Object.extractEditor (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\lib\standalone.js:47:22)
    at Gulp.<anonymous> (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\gulpfile.editor.js:71:13)
    at module.exports (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:214:10)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\Users\dirkb\Projects\mseng\VSCode\vscode\node_modules\orchestrator\lib\runTask.js:29:3)
    at _rimraf (C:\Users\dirkb\Projects\mseng\VSCode\vscode\build\lib\util.js:175:24)
[12:38:52] Finished 'clean-minified-editor' after 19 s
[12:38:52] Finished 'clean-optimized-editor' after 19 s
[12:38:52] Finished 'clean-editor-build' after 19 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jrieken** [comment]
🤔

**Comment by jrieken** [comment]
@alexandrudima Is some tree shake whitelisting needed?

**Comment by alexandrudima** [comment]
I think the standalone editor builds with a promise definition which doesn't contain `finally`...

**Comment by jrieken** [comment]
Not sure - the `tsconfig.monaco.json` build works just fine and I believe all promise is defined in `es6-promise.d.ts` (monaco and vscode)

**Comment by jrieken** [comment]
@alexandrudima I have a local change that add the definition for finally. With that I get a step further, but it seems there are different compiler versions/options at play here

```
[16:46:59] Starting compilation...
[16:47:29] Error: /Users/jrieken/Code/vscode/out-editor-src/vs/platform/list/browser/listService.ts(245,21): Argument of type 'this' is not assignable to parameter of type 'IThemable'.
  Property 'style' is missing in type 'WorkbenchAsyncDataTree<TInput, T, TFilterData>' but required in type 'IThemable'.
[16:47:29] Finished compilation with 1 errors after 29998 ms
[16:47:29] Error: /Users/jrieken/Code/vscode/out-editor-src/vs/platform/list/browser/listService.ts(245,21): Argument of type 'this' is not assignable to parameter of type 'IThemable'.
  Property 'style' is missing in type 'WorkbenchAsyncDataTree<TInput, T, TFilterData>' but required in type 'IThemable'.
[16:47:29] Finished compilation with 1 errors after 29999 ms
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: Found 1 errors
    at Stream.<anonymous> (/U
```

**Comment by alexandrudima** [comment]
This now just works...

**Comment by RMacfarlane** [comment]
I still see errors with the latest from today:
```
[10:25:08] Starting compilation...
[10:25:08] Starting extract-editor-esm ...
[10:25:08] Finished extract-editor-esm after 524 ms
[10:25:08] Starting compile-editor-esm ...
vs/base/common/path.ts(1682,1): error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.
vs/editor/contrib/format/format.ts(70,26): error TS2345: Argument of type 'DocumentRangeFormattingEditProvider[]' is not assignable to parameter of type '{ extensionId?: ExtensionIdentifier; }[]'.
  Type 'DocumentRangeFormattingEditProvider' has no properties in common with type '{ extensionId?: ExtensionIdentifier; }'.


[10:25:19] Finished compile-editor-esm after 10774 ms
[10:25:41] Error: /Users/ramacfar/dev/vscode/out-editor-src/vs/editor/contrib/format/format.ts(70,26): Argument of type 'DocumentRangeFormattingEditProvider[]' is not assignable to parameter of type '{ extensionId?: ExtensionIdentifier; }[]'.
  Type 'DocumentRangeFormattingEditProvider' has no properties in common with type '{ extensionId?: ExtensionIdentifier; }'.
[10:25:41] Finished compilation with 1 errors after 33237 ms
[10:25:41] Error: /Users/ramacfar/dev/vscode/out-editor-src/vs/editor/contrib/format/format.ts(70,26): Argument of type 'DocumentRangeFormattingEditProvider[]' is not assignable to parameter of type '{ extensionId?: ExtensionIdentifier; }[]'.
  Type 'DocumentRangeFormattingEditProvider' has no properties in common with type '{ extensionId?: ExtensionIdentifier; }'.
[10:25:41] Finished compilation with 1 errors after 33238 ms
[10:25:41] 'editor-distro' errored after 1.78 min
```

**Comment by alexandrudima** [comment]
We shipped the standalone editor, so this did work. It gets broken again and again and we fix it when we ship the editor, so it's ok, no verification needed.
