### ISSUE TITLE
"Extension host terminated unexpectedly" error persists

### ISSUE THREAD

**Issue by szalapski** [Microsoft/vscode#65304]
I keep getting "Extension host terminated unexpectedly" error persists,

- VSCode Version: 1.30.0
- OS Version: Windows 10.0.17134

Steps to Reproduce:

1. Closed all folders/projects (so VS Code is empty) and rebooted.
2. Renamed folder "C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions" to "extensions1" to force out all extensions, even Microsoft ones
3. Start vscode with  --disable-extensions.

I still get the error "Extension host terminated unexpectedly", and I am out of ideas on what else to try.

Trying to reveal "F1 > Developer: Show Logs ... > Extension Host" shows nothing, presumably because the extension host has crashed and the log has been closed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by szalapski** [comment]
I do see this in the Window log:
`[2018-12-18 09:30:05.995] [renderer1] [info] no standard startup: not the explorer viewlet
[2018-12-18 09:30:09.162] [renderer1] [error] Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at Object.s [as getGalleryExtensionIdFromLocal] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1201:509)
    at e.hasDuplicates (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3101:987)
    at e.getDistinctInstalledExtensions (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3100:795)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3099:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-12-18 09:30:09.248] [renderer1] [error] Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5679:893
    at Array.map (<anonymous>)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5679:812
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by alexandrudima** [comment]
@szalapski To rule out any installation specific problems, can you please install the insiders version -- https://code.visualstudio.com/insiders/

Does this one also fail to start the extension host?

**Comment by szalapski** [comment]
Trying it now...

**Comment by szalapski** [comment]
The Insider's edition works well; no extension host crash.  What should I do next?

**Comment by alexandrudima** [comment]
ugh... I think there could be two kind of things:
- corruption in the installation bits
- corruption in the user settings / user data

Let's start with the first one (since it is easier). Can you please uninstall the stable version and install it again?

**Comment by szalapski** [comment]
I suppose.  Ugh indeed.  I need to be working on my code instead of this!  I'll have to copy down all my extensions first...

**Comment by szalapski** [comment]
OK, a remove and install fixed this issue.  No idea what could have caused it.  The only think I can think is that my system administrator pushed a group policy update that allowed me to choose my own default browser, and I did so.  (Before this change it was forced to be IE11).

I am now reinstating settings and installing extensions.

**Comment by szalapski** [comment]
Hmm, looks like my extensions were retained.  Nice!  Thanks again.
