### ISSUE TITLE
"Illegal state: service accessor is only valid during the invocation of its target method" while starting development version of vs code

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#65336]
VS Code version: Code - Insiders 1.31.0-insider (d85a16f2e4354f2850b4171f84fe0c94b0cea338, 2018-12-18T06:13:24.919Z)
OS version: Darwin x64 18.2.0

Steps to Reproduce:

1. On Mac with a VS Code dev environment and [timeout](https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x) installed
1. Run this bash:

```
for i in {1..100}; do gtimeout --foreground --kill-after=2 2 ./scripts/code.sh; done
```

2. Every few starts, see:

```
[16:42:13] Syncronizing built-in extensions...
[16:42:13] You can manage built-in extensions with the --builtin flag
[16:42:13] [marketplace] ms-vscode.node-debug@1.30.4 ✔︎
[16:42:13] [marketplace] ms-vscode.node-debug2@1.30.3 ✔︎
[16:42:13] [marketplace] ms-vscode.references-view@0.0.19 ✔︎
Failed to load browser extensions from directory: /Users/matb/Library/Application Support/code-oss-dev/DevTools Extensions
{ Error: ENOENT: no such file or directory, open '/Users/matb/Library/Application Support/code-oss-dev/DevTools Extensions'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at App.<anonymous> (/Users/matb/projects/vscode/.build/electron/Code - OSS.app/Contents/Resources/electron.asar/browser/chrome-extension.js:419:52)
    at Object.onceWrapper (events.js:273:13)
    at App.emit (events.js:187:15)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/Users/matb/Library/Application Support/code-oss-dev/DevTools Extensions' }
[main 2018-12-19T00:42:13.838Z] Error: Illegal state: service accessor is only valid during the invocation of its target method
    at Object.illegalState (/Users/matb/projects/vscode/out/vs/base/common/errors.js:117:20)
    at Object.get (/Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:47:44)
    at setup (/Users/matb/projects/vscode/out/vs/code/electron-main/main.js:140:47)
    at /Users/matb/projects/vscode/out/vs/code/electron-main/main.js:227:28
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I hit this in normal development, the `timeout` command can just help trigger it. It is very timing dependent

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Thanks, I did something silly in https://github.com/Microsoft/vscode/commit/bd2e5b8c904bc36f141a9fdc009d541d77fc6b4c
