### ISSUE TITLE
Language server failed 5 times

### ISSUE THREAD

**Issue by OlegSomov** [Microsoft/vscode#65709]
Issue Type: <b>Bug</b>

Intelisense doesn't works from time to time. Last time I reinstalled windows to get this working but now I'm getting the same issue, and I seems to be not dependent on the project im using. 
also tried using different version of cpptools 0.17.6 and 0.20.0

```
	[Error - 5:47:25 PM] Connection to server got closed. Server will not be restarted.
[Error - 5:47:25 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:554:12)
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
debug|web|0.22.0

</details>

**Comment by OlegSomov** [comment]
Thanks @sean-mcmanus, I moved it https://github.com/Microsoft/vscode-cpptools/issues/2972
