### ISSUE TITLE
 Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#65702]
Issue Id: <b>35051995-6ff7-b013-25cc-ea377e0f0290</b><br /><br />*Versions* <br />- 1.31.0-insider (12/21/2018 6:20:22 AM)<br />*Stack* <br />TypeError: Cannot read property 'style' of undefined<br />    at DomRenderer._setCellUnderline (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:291:18)<br />    at DomRenderer._onLinkLeave (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:282:14)<br />    at Linkifier.<anonymous> (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:67:79)<br />    at Linkifier.EventEmitter.emit (\node_modules.asar\vscode-xterm\lib\common\EventEmitter.js:70:20)<br />    at MouseZone.leaveCallback (\node_modules.asar\vscode-xterm\lib\Linkifier.js:191:19)<br />    at MouseZoneManager.clearAll (\node_modules.asar\vscode-xterm\lib\ui\MouseZoneManager.js:58:39)<br />    at Terminal.<anonymous> (\node_modules.asar\vscode-xterm\lib\Terminal.js:432:105)<br />    at Terminal.EventEmitter.emit (\node_modules.asar\vscode-xterm\lib\common\EventEmitter.js:70:20)<br />    at Terminal.emit (\node_modules.asar\vscode-xterm\lib\public\Terminal.js:47:20)<br />    at t._getDimension (out/vs/workbench/workbench.main.js:3643:574)<br />    at t._evaluateColsA<br />

**Comment by Tyriar** [comment]
```
TypeError: Cannot read property 'style' of undefined
at DomRenderer._setCellUnderline (/node_modules.asar/vscode-xterm/lib/renderer/dom/DomRenderer.js:291:18) 
at DomRenderer._onLinkLeave (/node_modules.asar/vscode-xterm/lib/renderer/dom/DomRenderer.js:282:14) 
at Linkifier. (/node_modules.asar/vscode-xterm/lib/renderer/dom/DomRenderer.js:67:79) 
at Linkifier.EventEmitter.emit (/node_modules.asar/vscode-xterm/lib/common/EventEmitter.js:70:20) 
at MouseZone.leaveCallback (/node_modules.asar/vscode-xterm/lib/Linkifier.js:191:19) 
at MouseZoneManager.clearAll (/node_modules.asar/vscode-xterm/lib/ui/MouseZoneManager.js:58:39) 
at Terminal. (/node_modules.asar/vscode-xterm/lib/Terminal.js:432:105) 
at Terminal.EventEmitter.emit (/node_modules.asar/vscode-xterm/lib/common/EventEmitter.js:70:20) 
at Terminal.emit (/node_modules.asar/vscode-xterm/lib/public/Terminal.js:47:20) 
at t._getDimension (out/vs/workbench/workbench.main.js:3643:574) 
at t._evaluateColsA
```

```
TypeError: Cannot read property 'style' of undefined
at DomRenderer._setCellUnderline (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:291:18) 
at DomRenderer._onLinkLeave (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:282:14) 
at Linkifier. (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:67:79) 
at Linkifier.EventEmitter.emit (\node_modules.asar\vscode-xterm\lib\common\EventEmitter.js:70:20) 
at MouseZone.leaveCallback (\node_modules.asar\vscode-xterm\lib\Linkifier.js:191:19) 
at MouseZoneManager.clearAll (\node_modules.asar\vscode-xterm\lib\ui\MouseZoneManager.js:58:39) 
at Terminal. (\node_modules.asar\vscode-xterm\lib\Terminal.js:432:105) 
at Terminal.EventEmitter.emit (\node_modules.asar\vscode-xterm\lib\common\EventEmitter.js:70:20) 
at Terminal.emit (\node_modules.asar\vscode-xterm\lib\public\Terminal.js:47:20) 
at t.setVisible (out/vs/workbench/workbench.main.js:3653:896) 
at out/vs/workbench/wo
```

**Comment by Tyriar** [comment]
I couldn't reproduce this one, please review the change at https://github.com/xtermjs/xterm.js/pull/1861
