### ISSUE TITLE
Unable to launch code on Ubuntu 18.04 at all

### ISSUE THREAD

**Issue by m-hcb** [Microsoft/vscode#65879]
- VSCode Version: 1.30.0
- OS Version: 18.04

It stopped launching suddenly. 

Here is output of `code --verbose`

`[20665:0101/114339.429884:WARNING:browser_main_loop.cc(275)] Gtk: Locale not supported by C library.
	Using the fallback 'C' locale.
'g_io_module_load': /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_io_module_load
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
'g_io_module_load': /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_io_module_load
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
'g_io_module_load': /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_io_module_load
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
[20665:0101/114339.591990:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/entry.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[20665:0101/114339.592734:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/button.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[20665:0101/114339.593294:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/button-toolbar.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
[20699:0101/114339.719580:ERROR:gl_context_glx.cc(186)] Failed to create GL context with glXCreateContextAttribsARB.
[20699:0101/114339.719630:ERROR:gpu_info_collector.cc(51)] gl::init::CreateGLContext failed
[20699:0101/114339.719635:ERROR:gpu_info_collector.cc(119)] Could not create context for info collection.
[20699:0101/114339.719647:ERROR:gpu_init.cc(96)] gpu::CollectGraphicsInfo failed (fatal).
[20699:0101/114339.720518:ERROR:gpu_child_thread.cc(252)] Exiting GPU process due to errors during initialization
[20665:0101/114339.725073:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[main 11:43:39 AM] Starting VS Code
[main 11:43:39 AM] from: /snap/vscode/72/usr/share/code/resources/app
[main 11:43:39 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false }
[main 11:43:39 AM] Resolving machine identifier...
[main 11:43:39 AM] Resolved machine identifier: 4ef009bba93355223a29bd8177f20fd69c01893129495e691277f8b8b8ea78c4
[main 11:43:39 AM] [storage :memory:] open()
[main 11:43:39 AM] [uncaught exception in main]: Failed to watch /home/haseeb/.config/Code/User for changes (Error: watch /home/haseeb/.config/Code/User ENOSPC)
[main 11:43:39 AM] telemetry/optInStatus { optIn: true }
[main 11:43:39 AM] [storage :memory:] Trace (event): PRAGMA user_version = 1;
[main 11:43:39 AM] [storage :memory:] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
[main 11:43:39 AM] [storage :memory:] getItems(): Map(0) {}
[main 11:43:39 AM] update#setState idle
[main 11:43:39 AM] Error: watch /snap/vscode ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (original-fs.js:1386:19)
    at Object.fs.watch (original-fs.js:1412:11)
    at t [as constructor] (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:349:333)
    at t.create (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:68:770)
    at t.e._createInstance (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:234:215)
    at t.e._createServiceInstance (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:236:234)
    at t._createServiceInstance (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:237:862)
    at t.e._createServiceInstanceWithOwner (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:235:982)
    at t.e._createAndCacheServiceInstance (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:235:652)
    at t.e._getOrCreateServiceInstance (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:234:795)
    at Object.get (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:233:112)
    at Ee.openFirstWindow (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:539:458)
    at /snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:535:808
    at t.e.invokeFunction (/snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:233:247)
    at /snap/vscode/72/usr/share/code/resources/app/out/vs/code/electron-main/main.js:535:772
    at <anonymous>
[main 11:43:39 AM] Lifecycle#kill()
[main 11:43:39 AM] [storage :memory:] Trace (event): SELECT * FROM ItemTable
`

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
