### ISSUE TITLE
VSCode shows dialog box twice after crashing and reloading

### ISSUE THREAD

**Issue by ccloli** [Microsoft/vscode#65959]
Issue Type: <b>Bug</b>

Once VSCode crashes, VSCode will ask for reloading the workspace. But after reloading, all the dialog box shows twice.

![image](https://user-images.githubusercontent.com/8115912/50628096-83e42980-0f71-11e9-875e-dbe7e07b7b7d.png)
_(VSCode crashes and asks for reopen)_

![twice-dialog](https://user-images.githubusercontent.com/8115912/50628853-d8d56f00-0f74-11e9-9370-4bc985c5954f.gif)
_(All the dialog shows twice)_

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (0.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
regular-autocomplete|che|0.2.1
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.30.2
sublime-keybindings|ms-|4.0.0
nodejs-docs|Muk|0.2.2
open-in-browser|tec|2.0.0
full-react-snippets|wal|1.1.2
markdown-pdf|yza|1.2.0
markdown-html|zhy|0.1.8

</details>

**Comment by bpasero** [comment]
If someone wants to investigate 👍

**Comment by bpasero** [comment]
@joaomoreno I believe this could be some bug in your IPC library where the same call gets executed simply twice because reloading the window from an unresponsive window is a bit special (e.g. we cannot run the dispose handlers in the renderer).

**To reproduce:**
* change an action (really any you can invoke via command palette) to "`process.crash()`"
* run out of sources and invoke the action
* wait for the unresponsive dialog to show up
* click to reload window
* now invoke an action that needs IPC, e.g. delete a file from the explorer which will bring up a dialog
* the dialog opens twice

From the main side I see this call happening twice:

```
showMessageBox Error
    at WindowsManager.showMessageBox (/Users/bpasero/Development/monaco/out/vs/code/electron-main/windows.js:1437:43)
    at /Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:124:125
    at WindowsService.withWindow (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:615:24)
    at WindowsService.<anonymous> (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:124:48)
    at step (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:55:23)
    at Object.next (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:36:53)
    at /Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:30:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:26:12)
    at WindowsService.showMessageBox (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:120:20)
    at WindowsChannel.call (/Users/bpasero/Development/monaco/out/vs/platform/windows/node/windowsIpc.js:35:60)
    at ChannelServer.onPromise (/Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.js:222:35)
    at ChannelServer.onRawMessage (/Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.js:207:33)
    at /Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.js:168:91
    at Emitter.fire (/Users/bpasero/Development/monaco/out/vs/base/common/event.js:539:38)
    at /Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.electron.js:13:69
    at /Users/bpasero/Development/monaco/out/vs/base/common/event.js:94:61
    at /Users/bpasero/Development/monaco/out/vs/base/common/event.js:112:74
    at Emitter.fire (/Users/bpasero/Development/monaco/out/vs/base/common/event.js:539:38)
    at EventEmitter.fn (/Users/bpasero/Development/monaco/out/vs/base/common/event.js:342:31)
    at EventEmitter.emit (events.js:187:15)
    at WebContents.<anonymous> (/Users/bpasero/Development/monaco/.build/electron/Code - OSS.app/Contents/Resources/electron.asar/browser/api/web-contents.js:284:13)
    at WebContents.emit (events.js:182:13)
showMessageBox Error
    at WindowsManager.showMessageBox (/Users/bpasero/Development/monaco/out/vs/code/electron-main/windows.js:1437:43)
    at /Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:124:125
    at WindowsService.withWindow (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:615:24)
    at WindowsService.<anonymous> (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:124:48)
    at step (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:55:23)
    at Object.next (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:36:53)
    at /Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:30:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:26:12)
    at WindowsService.showMessageBox (/Users/bpasero/Development/monaco/out/vs/platform/windows/electron-main/windowsService.js:120:20)
    at WindowsChannel.call (/Users/bpasero/Development/monaco/out/vs/platform/windows/node/windowsIpc.js:35:60)
    at ChannelServer.onPromise (/Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.js:222:35)
    at ChannelServer.onRawMessage (/Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.js:207:33)
    at /Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.js:168:91
    at Emitter.fire (/Users/bpasero/Development/monaco/out/vs/base/common/event.js:539:38)
    at /Users/bpasero/Development/monaco/out/vs/base/parts/ipc/node/ipc.electron.js:13:69
    at /Users/bpasero/Development/monaco/out/vs/base/common/event.js:94:61
    at /Users/bpasero/Development/monaco/out/vs/base/common/event.js:112:74
    at Emitter.fire (/Users/bpasero/Development/monaco/out/vs/base/common/event.js:539:38)
    at EventEmitter.fn (/Users/bpasero/Development/monaco/out/vs/base/common/event.js:342:31)
    at EventEmitter.emit (events.js:187:15)
    at WebContents.<anonymous> (/Users/bpasero/Development/monaco/.build/electron/Code - OSS.app/Contents/Resources/electron.asar/browser/api/web-contents.js:284:13)
    at WebContents.emit (events.js:182:13)

```

**Comment by joaomoreno** [comment]
Related to https://github.com/Microsoft/vscode/issues/62524 ?

**Comment by bpasero** [comment]
🥇

**Comment by bpasero** [comment]
@joaomoreno debugging this it indeed seems to be a missing call to [`this.mainProcessClient.dispose()`](https://github.com/Microsoft/vscode/blob/471a3ff/src/vs/workbench/electron-browser/shell.ts#L619). Simpler repro:
- comment out that line
- reload window
- close a dirty file

Is there anything I could call on the main side to unregister the window? If that was possible we could do something custom in the case of crash/unresponsive.

**Comment by joaomoreno** [comment]
Great research and steps @bpasero! I wonder why we didn't see this more often. Fixed it at the Electron IPC layer by detecting when clients reconnect.

**Comment by bpasero** [comment]
Epic

**Comment by dbaeumer** [comment]
Verified using steps from here: https://github.com/Microsoft/vscode/issues/65959#issuecomment-451949087
