### ISSUE TITLE
code failing to run while developing with API rate limit exceeded for <IP>

### ISSUE THREAD

**Issue by o0rebelious0o** [Microsoft/vscode#66096]
- VSCode Version: master source branch
- OS Version: Win10 1809 17763.195

Steps to Reproduce:
1. Build and then run the vs code OSS version from source using .\scripts\code.bat several times in a short-ish period.  I'm not sure exactly how long I've been building and running for this morning/afternoon.

Expected: built vscode runs.
Actual: vscode fails to run with unhandled exception from `internal\streams\legacy.js:59` whilst starting electron and doesn't run.  Powershell output below:
```
PS E:\Source Code\vscode> .\scripts\code.bat
[13:51:38] Using gulpfile E:\Source Code\vscode\gulpfile.js
[13:51:38] Starting 'clean-electron'...
[13:51:38] Finished 'clean-electron' after 1.62 ms
[13:51:38] Starting 'electron'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Request._callback (E:\Source Code\vscode\node_modules\github-releases-ms\lib\github.js:83:17)
    at Request.self.callback (E:\Source Code\vscode\node_modules\github-releases-ms\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (E:\Source Code\vscode\node_modules\github-releases-ms\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (E:\Source Code\vscode\node_modules\github-releases-ms\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
[13:51:40] Syncronizing built-in extensions...
[13:51:40] You can manage built-in extensions with the --builtin flag
[13:51:40] [marketplace] ms-vscode.node-debug@1.30.4 ✔︎
[13:51:40] [marketplace] ms-vscode.node-debug2@1.31.2 ✔︎
[13:51:40] [marketplace] ms-vscode.references-view@0.0.21 ✔︎
The system cannot find the path specified.
```

Does this issue occur when all extensions are disabled?: No

I can use my VPN provider to change my outbound IP, then it works, but this is a limitation to developers wishing to contribute.

**Comment by bpasero** [comment]
Yup, you can resolve this by exporting a GITHUB_TOKEN variable with an access token from your account.
