### ISSUE TITLE
VSCode Blank White Window

### ISSUE THREAD

**Issue by p30arena** [Microsoft/vscode#66340]
- VSCode Version: 1.30.2.0
- OS Version: 6.3

Steps to Reproduce:

First I got errors from Razor (Asp.NET Extension?), then a sudden reboot.
Now All I see is a Full Screen WHITE WINDOW.

When I run from console, it outputs:
**update#setState idle**

Does this issue occur when all extensions are disabled?: Yes

```
C:\Users\W>code --disable-extensions
D:\Program Files\Microsoft VS Code\resources\app\out\cli.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buf
fer) { return function (exports, require, module, __filename, __dirname) {



SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

**Comment by p30arena** [comment]
I renamed **Code** directory in %APPDATA%
now the WHITE WINDOW replaced by a BLACK WINDOW.

**Comment by p30arena** [comment]
`"D:\Program Files\Microsoft VS Code\Code.exe" --disable-extensions`

This **crashes** my **FireFox** Browser.

**Comment by p30arena** [comment]
So I reinstalled vscode.
now its Fixed.
