### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by david-waterworth** [Microsoft/vscode#66514]
I'm getting the error message below when using python, the error itself isn't a problem but every time it occurs the `OUTPUT` tab automatically gets focus (I'm working in the python `TERMINAL` tab and it's automatically switching)

> [Error - 2:46:48 pm] Request textDocument/hover failed.
>   Message: unknown document
>   Code: -32000 
>    at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
>    at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
>    at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken)
>    at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken)

**Comment by dbaeumer** [comment]
Very strange. I do call `show(true)` which should preserve the focus. I will change the code to show a notification that something got posted to the output channel.

@david-waterworth please also reported this to the vscode python extension since there seems to be something wrong there as well.
