### ISSUE TITLE
css language server error on suggest

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#66637]
Issue Type: <b>Bug</b>

I'm not sure of the exact repro steps, I saw this while typing in a css file when completion items were triggered. I'll provide better steps if I see it again.

```
Error - 4:30:48 PM] Unhandled exception: Cannot read property 'getChildren' of undefined
TypeError: Cannot read property 'getChildren' of undefined
    at er (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:581664)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:586291
    at e.visitRuleSet (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:586605)
    at e.visitNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:583785)
    at t.e.accept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:111597)
    at t.e.accept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:111669)
    at t.e.acceptVisitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:111724)
    at Function.e.entries (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:582413)
    at e.doValidation (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:591888)
    at then.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:70477)
```

VS Code version: Code - Insiders 1.31.0-insider (d3024ec0c4eb830eb22a39bc2f2feacd314a952a, 2019-01-16T07:51:38.794Z)
OS version: Darwin x64 18.0.0

**Comment by vSanjo** [comment]
Having the same issue within Insiders. 

I can open an empty `.scss` file, and drop the following in.

```scss
.test {
}
```

Then I can type `b`, tab out to `border` with the autocompletes showing, and it'll error.

```
[Error - 10:02:56 am] Unhandled exception: Cannot read property 'getChildren' of undefined
TypeError: Cannot read property 'getChildren' of undefined
    at er (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:581664)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:586291
    at e.visitRuleSet (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:586605)
    at e.visitNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:583785)
    at t.e.accept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:111597)
    at t.e.accept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:111669)
    at t.e.acceptVisitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:111724)
    at Function.e.entries (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:582413)
    at e.doValidation (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:591888)
    at then.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:70477)
```
