### ISSUE TITLE
Error while disabling an extension

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#66986]
Disabled and enabled a theme extension multiple times ended in an exception:

It comes from a JSON.parse(value) where value in empty

```
 ERR Unexpected end of JSON input: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StorageManager.get (file:///home/aeschli/workspaces/vscode/out/vs/platform/extensionManagement/common/extensionEnablementService.js:398:25)
    at ExtensionEnablementService._getExtensions (file:///home/aeschli/workspaces/vscode/out/vs/platform/extensionManagement/common/extensionEnablementService.js:327:39)
    at ExtensionEnablementService._getDisabledExtensions (file:///home/aeschli/workspaces/vscode/out/vs/platform/extensionManagement/common/extensionEnablementService.js:318:25)
    at ExtensionEnablementService.getEnablementState (file:///home/aeschli/workspaces/vscode/out/vs/platform/extensionManagement/common/extensionEnablementService.js:153:22)
    at ExtensionEnablementService.isEnabled (file:///home/aeschli/workspaces/vscode/out/vs/platform/extensionManagement/common/extensionEnablementService.js:212:40)
    at file:///home/aeschli/workspaces/vscode/out/vs/workbench/parts/preferences/electron-browser/preferencesSearch.js:89:86
    at Array.filter (<anonymous>)
    at file:///home/aeschli/workspaces/vscode/out/vs/workbench/parts/preferences/electron-browser/preferencesSearch.js:89:22
    at process._tickCallback (internal/process/next_tick.js:68:7)
/home/aeschli/workspaces/vscode/out/vs/platform/log/common/log.js:206 
```

**Comment by sandy081** [comment]
Steps to repro:

- Start VS Code with fresh user data directory
- Disable any installed extension (you can use built in too)
- Enable it back immediately

🐛 Above error in the console

**Comment by sandy081** [comment]
Fixed it on my side. 

@bpasero Storage service is returning empty string even though I provide a default

```
this.storageService.get(key, scope, '[]')
```

Please check why it is not returning default. Before calling above method, I am deleting the key

```
this.storageService.remove(key, scope);
```

**Comment by bpasero** [comment]
@sandy081 great catch, this is a regression introduced by strict-null from @mjbvz (via https://github.com/Microsoft/vscode/commit/7970f2a7ca9be92210af5717d0a87a333247b010#diff-a84f9571f1154077b72f2af443a285acR60).

@mjbvz in the future I would appreciate a PR when you make changes in code I own. This was insane to find out after the fact, took my entire morning.

**Comment by aeschli** [comment]
Verified with steps above.
