### ISSUE TITLE
Disable prettier for html also disable main html formater

### ISSUE THREAD

**Issue by merobal** [Microsoft/vscode#67055]
- VSCode Version: Latest
- OS Version: Win10

With prettier v1.15 they introduced html formatting, however we would like to use vscode's built-in html formatter, because that formats code better.

The bug is if we disable prettier to format html that also disables the built-in formatter. There is an issue at the prettier-vscode repo, but it's maybe a vscode issue itself.

Related: https://github.com/prettier/prettier-vscode/issues/689

**Comment by octref** [comment]
@aeschli It seems HTML only register a range formatter, but not document formatter.

@jrieken Just to make sure I get the problem correctly, was there a fallback logic to use range formatter when no document formatter is registered?

**Comment by jrieken** [comment]
Yeah, the range formatter is a default document formatter (range is the document range)

**Comment by octref** [comment]
@merobal Does it work after you reload / restart VS Code?

**Comment by merobal** [comment]
I did a detailed test now, and now the formatters work as we expect (after restart).

But I tested with Insider build too, and I got this error in dev console:
>Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'resolve'. 
```
[Extension Host] Here is the error stack:  Error: Cannot find module 'resolve'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\requirePkg.js:5:17)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\requirePkg.js:37:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\PrettierEditProvider.js:14:22)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\PrettierEditProvider.js:165:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\extension.js:4:32)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\extension.js:60:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:31:542)
	at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:738:5
	at t._doActivateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:738:113)
	at t._activateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:736:785)
	at Object.actualActivateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:733:633)
	at e._activateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:557)
	at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:180
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:155)
	at e.activateByEvent (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:329:14)
	at t._activateByEvent (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:174)
	at t._handleEagerExtensions (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:739:590)
	at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:743:250
	at process._tickCallback (internal/process/next_tick.js:68:7) (at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:792)
```

**Comment by octref** [comment]
@merobal I'll just add HTML range formatter also as the whole document formatter.

The root problem is:
- HTML extension only registers a range formatter
- Prettier extension registers both range and document formatter
- When Prettier disables HTML mode, VS Code still sees there were registrations for document formatter, so "Format Document" doesn't fall back to the still existing range formatter coming from HTML extension.

**Comment by octref** [comment]
For the error, you should report to the prettier extension.

**Comment by octref** [comment]
@aeschli Is there any reason we don't register the HTML formatter as whole document formatter? If not I'll just proceed to add it.

**Comment by aeschli** [comment]
@octref this looks like a bug in the formatter provider registry. The way I understand it, when there's no document formatter for the current document, or none of the matching document formatters provide a result, the range providers should be asked.

Assigning @jrieken

**Comment by jrieken** [comment]
This is a bug with prettier. When disabled, it doesn't remove the formatter but just returns a null-edit. VS Code will proceed with that because we don't run multiple formatters. Reference: https://github.com/prettier/prettier-vscode/blob/master/src/PrettierEditProvider.ts#L102
