### ISSUE TITLE
Explorer: Data tree node not found

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67069]
1. Create `foo/bar/file.txt`
2. Open `file.txt`
3. Reload

```
  ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.AsyncDataTree.getDataNode (file:///Users/joao/Work/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:542:23)
    at WorkbenchAsyncDataTree.AsyncDataTree.reveal (file:///Users/joao/Work/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:514:35)
    at file:///Users/joao/Work/vscode/out/vs/workbench/parts/files/electron-browser/views/explorerView.js:479:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by joaomoreno** [comment]
Fixed by b1d8e8dca9116f60e32e60539aba615f207eb129
