### ISSUE TITLE
Search: badge styler is not properly disposed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67071]
Found using @jrieken event listener leak warning:

```
[0d1] potential listener LEAK detected, having 197 listeners already. MOST frequent listener (14):
at s (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1858:201)
    at Object.t.attachBadgeStyler (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1858:486)
    at t.renderTemplate (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5250:365)
    at e.renderTemplate (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:993:298)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:869:359
    at Array.map (<anonymous>)
    at e.renderTemplate (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:869:334)
    at e.alloc (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:176:207)
    at e.insertItemInDOM (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:426:941)
    at e._splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:424:206)
    at e.splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:422:713)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:7:408
    at Array.forEach (<anonymous>)
    at e.splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:7:379)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:877:203
    at e.bufferEvents (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:729)
    at e.splice (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:877:159)
    at e._setListNodeCollapsed (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:368)
    at e._setCollapsed (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90:937)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90:789
    at e.bufferEvents (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:729)
    at e.setCollapsed (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90:756)
    at e.setCollapsed (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:671)
    at n.e.collapseAll (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1006:236)
    at t.run (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5239:784)
    at t.runAction (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:101:991)
    at t.run (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:101:799)
    at t.onClick (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:913:492)
    at Immediate._onImmediate (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:913:10)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
e.check @ /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79
```

It looks like the badge styler is registered on the renderer but not on the template itself. Thus it never gets disposed as part of the lifecycle of a template. Locations:
* https://github.com/Microsoft/vscode/blob/d49b0a5/src/vs/workbench/parts/search/browser/searchResultsView.ts#L93
* https://github.com/Microsoft/vscode/blob/d49b0a5/src/vs/workbench/parts/search/browser/searchResultsView.ts#L156

Better these disposables should be added to the template data and disposed when the template gets disposed.

**Comment by roblourens** [comment]
Good catch
