### ISSUE TITLE
NPE while changing tree children when filter is active

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67233]
1. Start debugging, to pause
2. Type some text in the type filter of Variables
3. Step

```
  ERR Invalid start index: 1: Error: Invalid start index: 1
    at List.splice (file:///home/joao/Work/vscode/out/vs/base/browser/ui/list/listWidget.js:1032:23)
    at IndexTreeModel.splice (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:73:27)
    at ObjectTreeModel.setChildren (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:60:31)
    at ObjectTree.setChildren (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/objectTree.js:28:31)
    at WorkbenchAsyncDataTree.AsyncDataTree.setChildren (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:758:23)
    at WorkbenchAsyncDataTree.<anonymous> (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:624:34)
    at step (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:46:23)
    at Object.next (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:27:53)
    at fulfilled (file:///home/joao/Work/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:18:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

cc @isidorn

**Comment by isidorn** [comment]
Can not repro with latest out of source and seems to behave fine -> verified
