### ISSUE TITLE
Listener leak at renderReplaceInput()

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67385]
I found this in insiders, not sure how to reproduce, but I am puzzled why the replace input needs to be renderer 175 times:

```
6fh] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
e.check @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79     at s (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1866:201)
    at Object.t.attachInputBoxStyler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1866:683)
    at t.renderReplaceInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5293:635)
    at t.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5289:867)
    at t [as constructor] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5287:614)
    at t.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:229:596)
    at t.e._createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1506:215)
    at t.e.createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1505:561)
    at t.createSearchWidget (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5664:61)
    at t.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5657:589)
    at o.t.showComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5311:137)
    at o.t.doOpenComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:994)
    at o.t.openComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:491)
    at o.doOpenViewlet (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5374:745)
    at o.openViewlet (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5374:49)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4938:173)
    at t.runAction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:102:255)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:102:63)
    at t.onClick (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:919:105)
    at Immediate._onImmediate (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:918:592)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by roblourens** [comment]
Are viewlets ever disposed and recreated in normal usage? Did you toggle the search view from panel -> sidebar 175 times?

**Comment by bpasero** [comment]
@roblourens no they should not

**Comment by roblourens** [comment]
I haven't been able to repro this. I think that exact stack only showed up once though?

> MOST frequent listener (1)
