### ISSUE TITLE
Cannot read property then of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6739]
Refs: https://github.com/Microsoft/vscode/issues/6655

I am right clicking on `greeting` and "Find All References" and I get: Cannot read property then of undefined.

```html
<!-- Single statement block -->
@{ var myMessage =	"Hello World"; }

<!-- Inline expression or variable -->
<p>The value of myMessage is: @myMessage</p> 

<!--	Multi-statement block -->
@{
var greeting = "Welcome to our site!";
var weekDay = DateTime.Now.DayOfWeek;
var greetingMessage = greeting + " Here in Huston it is: " + weekDay;
}
<p>The greeting is: @greetingMessage</p>
```

**Comment by bpasero** [comment]
Same for handlebars btw.

**Comment by alexandrudima** [comment]
also happens in html

**Comment by alexandrudima** [comment]
It is a problem in the UI code.

`ReferenceWidget.setModel` returns undefined in some cases.

```
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31 TypeError: Cannot read property 'then' of undefined
    at file:///C:/Alex/src/vscode/out/vs/editor/contrib/referenceSearch/browser/referencesController.js:120:60
    at Object.notifySuccess [as _notify] (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_success_notify.enter (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1127:30)
    at Promise_ctor.WinJS.Class.define._run (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at Promise_ctor.WinJS.Class.define._completed (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1311:18)
    at argDone (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:2072:37)
    at Promise.then.errors.(anonymous function) (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:2097:78)
    at Object.notifySuccess [as _notify] (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_success_notify.enter (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1127:30)
    at Promise_ctor.WinJS.Class.define._run (file:///C:/Alex/src/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
```

**Comment by jrieken** [comment]
**verifier**: run a reference search that yields in no result.
