### ISSUE TITLE
TypeError: Cannot read property '_data' of undefined

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67439]
Got into this error. Terminal is blank and I can't input anything:

![image](https://user-images.githubusercontent.com/4033249/51929918-36ab7a00-23ae-11e9-847d-e939ed763d17.png)

<details>
<summary>error log</summary>

```
ERR Cannot read property '_data' of undefined: TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferLine.js:165:27)
    at Buffer._reflowSmaller (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:242:45)
    at Buffer._reflow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:170:18)
    at Buffer.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Terminal.js:1096:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/public/Terminal.js:53:20)
    at D._resize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3806:361)
    at D.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3805:503)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3901:182)
    at Object.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:445:146)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:153
    at Array.forEach (<anonymous>)
    at t.layoutViews (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:124)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:448:34)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3899:847)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3905:445)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5737:68
    at Array.forEach (<anonymous>)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5737:39)
    at t._updateFont (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5742:285)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5736:685
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t.setVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2657:648)
    at o.t.showComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5312:204)
    at o.t.doOpenComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:994)
    at o.t.openComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:491)
    at o.openPanel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5362:988)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2660:620)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5709:25)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2576:57
notificationsAlerts.ts:38 TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:327)
    at Buffer._reflow (Buffer.ts:238)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1702)
    at Terminal.resize (Terminal.ts:51)
    at D._resize (terminalInstance.ts:1215)
    at D.layout (terminalInstance.ts:1185)
    at e.layout (terminalTab.ts:200)
    at Object.layout (splitview.ts:211)
    at splitview.ts:616
    at Array.forEach (<anonymous>)
    at t.layoutViews (splitview.ts:616)
    at t.layout (splitview.ts:360)
    at e.layout (terminalTab.ts:129)
    at t.layout (terminalTab.ts:410)
    at terminalPanel.ts:125
    at Array.forEach (<anonymous>)
    at t.layout (terminalPanel.ts:125)
    at o.t.showComposite (compositePart.ts:293)
    at o.t.doOpenComposite (compositePart.ts:148)
    at o.t.openComposite (compositePart.ts:112)
    at o.openPanel (panelPart.ts:228)
    at t.run (panel.ts:89)
    at t.run (terminalActions.ts:90)
    at actions.ts:113
t.onDidNotificationChange @ notificationsAlerts.ts:38
bootstrap-window.js:202 [uncaught exception]: TypeError: Cannot read property 'get' of undefined
onUnexpectedError @ bootstrap-window.js:202
bootstrap-window.js:205 TypeError: Cannot read property 'get' of undefined
    at TextRenderLayer._forEachCell (TextRenderLayer.ts:75)
    at TextRenderLayer._drawBackground (TextRenderLayer.ts:184)
    at TextRenderLayer.onGridChanged (TextRenderLayer.ts:263)
    at Renderer.ts:198
    at Array.forEach (<anonymous>)
    at Renderer._renderRows (Renderer.ts:198)
    at RenderDebouncer._innerRefresh (RenderDebouncer.ts:49)
    at RenderDebouncer.ts:40
onUnexpectedError @ bootstrap-window.js:205
TextRenderLayer.ts:75 Uncaught TypeError: Cannot read property 'get' of undefined
    at TextRenderLayer._forEachCell (TextRenderLayer.ts:75)
    at TextRenderLayer._drawBackground (TextRenderLayer.ts:184)
    at TextRenderLayer.onGridChanged (TextRenderLayer.ts:263)
    at Renderer.ts:198
    at Array.forEach (<anonymous>)
    at Renderer._renderRows (Renderer.ts:198)
    at RenderDebouncer._innerRefresh (RenderDebouncer.ts:49)
    at RenderDebouncer.ts:40
log.ts:173   ERR Cannot read property '_data' of undefined: TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferLine.js:165:27)
    at Buffer._reflowSmaller (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:242:45)
    at Buffer._reflow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:170:18)
    at Buffer.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Terminal.js:1096:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/public/Terminal.js:53:20)
    at D._resize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3806:361)
    at D.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3805:503)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3901:182)
    at Object.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:445:146)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:153
    at Array.forEach (<anonymous>)
    at t.layoutViews (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:124)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:448:34)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3899:847)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3905:445)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5737:68
    at Array.forEach (<anonymous>)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5737:39)
    at t._updateFont (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5742:285)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5736:685
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t.setVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2657:648)
    at o.t.showComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5312:204)
    at o.t.doOpenComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:994)
    at o.t.openComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:491)
    at o.openPanel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5362:988)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2660:620)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5709:25)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2576:57
notificationsAlerts.ts:38 TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:327)
    at Buffer._reflow (Buffer.ts:238)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1702)
    at Terminal.resize (Terminal.ts:51)
    at D._resize (terminalInstance.ts:1215)
    at D.layout (terminalInstance.ts:1185)
    at e.layout (terminalTab.ts:200)
    at Object.layout (splitview.ts:211)
    at splitview.ts:616
    at Array.forEach (<anonymous>)
    at t.layoutViews (splitview.ts:616)
    at t.layout (splitview.ts:360)
    at e.layout (terminalTab.ts:129)
    at t.layout (terminalTab.ts:410)
    at terminalPanel.ts:125
    at Array.forEach (<anonymous>)
    at t.layout (terminalPanel.ts:125)
    at o.t.showComposite (compositePart.ts:293)
    at o.t.doOpenComposite (compositePart.ts:148)
    at o.t.openComposite (compositePart.ts:112)
    at o.openPanel (panelPart.ts:228)
    at t.run (panel.ts:89)
    at t.run (terminalActions.ts:90)
    at actions.ts:113
t.onDidNotificationChange @ notificationsAlerts.ts:38
log.ts:173   ERR Cannot read property '_data' of undefined: TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferLine.js:165:27)
    at Buffer._reflowSmaller (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:242:45)
    at Buffer._reflow (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:170:18)
    at Buffer.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Terminal.js:1096:22)
    at Terminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/public/Terminal.js:53:20)
    at D._resize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3806:361)
    at D.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3805:503)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3901:182)
    at Object.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:445:146)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:153
    at Array.forEach (<anonymous>)
    at t.layoutViews (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:124)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:448:34)
    at e.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3899:847)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3905:445)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5737:68
    at Array.forEach (<anonymous>)
    at t.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5737:39)
    at t._updateFont (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5742:285)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5736:685
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t.setVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2657:648)
    at o.t.showComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5312:204)
    at o.t.doOpenComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:994)
    at o.t.openComposite (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5309:491)
    at o.openPanel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5362:988)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2660:620)
    at t.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5709:25)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2576:57
notificationsAlerts.ts:38 TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:327)
    at Buffer._reflow (Buffer.ts:238)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1702)
    at Terminal.resize (Terminal.ts:51)
    at D._resize (terminalInstance.ts:1215)
    at D.layout (terminalInstance.ts:1185)
    at e.layout (terminalTab.ts:200)
    at Object.layout (splitview.ts:211)
    at splitview.ts:616
    at Array.forEach (<anonymous>)
    at t.layoutViews (splitview.ts:616)
    at t.layout (splitview.ts:360)
    at e.layout (terminalTab.ts:129)
    at t.layout (terminalTab.ts:410)
    at terminalPanel.ts:125
    at Array.forEach (<anonymous>)
    at t.layout (terminalPanel.ts:125)
    at o.t.showComposite (compositePart.ts:293)
    at o.t.doOpenComposite (compositePart.ts:148)
    at o.t.openComposite (compositePart.ts:112)
    at o.openPanel (panelPart.ts:228)
    at t.run (panel.ts:89)
    at t.run (terminalActions.ts:90)
    at actions.ts:113
t.onDidNotificationChange @ notificationsAlerts.ts:38
bootstrap-window.js:202 [uncaught exception]: TypeError: Cannot read property 'isWrapped' of undefined
onUnexpectedError @ bootstrap-window.js:202
bootstrap-window.js:205 TypeError: Cannot read property 'isWrapped' of undefined
    at SelectionManager.get [as selectionText] (SelectionManager.ts:219)
    at SelectionManager._onMouseUp (SelectionManager.ts:648)
    at HTMLDocument._mouseUpListener (SelectionManager.ts:135)
onUnexpectedError @ bootstrap-window.js:205
SelectionManager.ts:219 Uncaught TypeError: Cannot read property 'isWrapped' of undefined
    at SelectionManager.get [as selectionText] (SelectionManager.ts:219)
    at SelectionManager._onMouseUp (SelectionManager.ts:648)
    at HTMLDocument._mouseUpListener (SelectionManager.ts:135)
notificationsAlerts.ts:38 TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:327)
    at Buffer._reflow (Buffer.ts:238)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1702)
    at Terminal.resize (Terminal.ts:51)
    at D._resize (terminalInstance.ts:1215)
    at D.layout (terminalInstance.ts:1185)
    at D.setVisible (terminalInstance.ts:878)
    at terminalTab.ts:366
    at Array.forEach (<anonymous>)
    at t.setVisible (terminalTab.ts:366)
    at terminalService.ts:203
    at Array.forEach (<anonymous>)
    at Proxy.e.setActiveTabByIndex (terminalService.ts:203)
    at Proxy.e.setActiveTabToNext (terminalService.ts:253)
    at t.run (terminalActions.ts:563)
    at actions.ts:113
```

</details>

**Comment by Tyriar** [comment]
Another one:

```
bootstrap-window.js:205 TypeError: Cannot read property 'getWidth' of undefined
    at Object.reflowLargerGetLinesToRemove (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\BufferReflow.js:38)
    at Buffer._reflowLarger (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:174)
    at Buffer._reflow (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:167)
    at Buffer.resize (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:152)
    at BufferSet.resize (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\BufferSet.js:78)
    at Terminal.resize (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Terminal.js:1096)
    at Terminal.resize (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\public\Terminal.js:53)
    at D._resize (terminalInstance.ts:1215)
    at D.layout (terminalInstance.ts:1185)
    at e.layout (terminalTab.ts:200)
    at Object.layout (splitview.ts:211)
    at splitview.ts:616
    at Array.forEach (<anonymous>)
    at t.layoutViews (splitview.ts:616)
    at t.layout (splitview.ts:360)
    at e.layout (terminalTab.ts:129)
    at t.layout (terminalTab.ts:410)
    at terminalPanel.ts:125
    at Array.forEach (<anonymous>)
    at t.layout (terminalPanel.ts:125)
    at o.t.layout (compositePart.ts:476)
    at o.layout (panelPart.ts:307)
    at t.layout (layout.ts:655)
    at t.layout (workbench.ts:1508)
    at t.layout (shell.ts:609)
    at t.onWindowResize (shell.ts:581)
    at shell.ts:564
```

**Comment by mjbvz** [comment]
I can sometimes repo this by:

1. With a narrow terminal
1. Run `ls -R`
1. Focus terminal and hold the `a` key
1. While holding the `a` key, quickly resize the window using dragging
