### ISSUE TITLE
rejected promise not handled within 1 second doesn't show details of a promise

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#67580]
When I was debugging SVN extension (https://github.com/JohnstonCode/svn-scm/issues/465) I saw this message in console:
![image](https://user-images.githubusercontent.com/7345761/52014011-86de2580-24ef-11e9-9f4f-7390875b3059.png)

Then I've discovered that this promise is unhandled in another extension, after I've edited `extensionHostProcess.js` file and inserted breakpoint. Please provide some stacktrace or message of rejected Promise it's hard to find the root of the problem.

```
"TypeError: Cannot read property 'fileName' of undefined
    at DocumentWatcher.<anonymous> (C:\Users\yanpas\.vscode\extensions\editorconfig.editorconfig-0.12.7\out\src\DocumentWatcher.js:103:72)
    at Generator.next (<anonymous>)
    at __awaiter (C:\Users\yanpas\.vscode\extensions\editorconfig.editorconfig-0.12.7\out\src\DocumentWatcher.js:6:71)
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\yanpas\.vscode\extensions\editorconfig.editorconfig-0.12.7\out\src\DocumentWatcher.js:2:12)
    at DocumentWatcher.resolveConfig (C:\Users\yanpas\.vscode\extensions\editorconfig.editorconfig-0.12.7\out\src\DocumentWatcher.js:97:16)
    at __dirname.constructor.subscriptions.push.vscode_1.window.onDidChangeWindowState.state (C:\Users\yanpas\.vscode\extensions\editorconfig.editorconfig-0.12.7\out\src\DocumentWatcher.js:35:22)
    at e.fire (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
    at e.$onDidChangeWindowFocus (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:644:42)
    at t._doInvokeHandler (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:837)
    at t._invokeHandler (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:509)
    at t._receiveRequest (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:126)
    at t._receiveOneMessage (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:59)
    at c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:895
    at c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:130:793
    at e.fire (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
    at a (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:186:147)
    at Socket.n._socketDataListener (c:\Users\yanpas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:186:368)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)"
```

**Comment by jrieken** [comment]
Yeah, I got that. I have #67640 for that (thanks to @Yanpas)
