### ISSUE TITLE
Tree exception in file search panel

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67595]
Issue Type: <b>Bug</b>

**Repo**
1. Using a build from master (498eb67b0c2d7bd29f8a724d619675a18a988687)
1. Perform a workspace search
1. Select one of the items in the results
1. Perform the same search again

**Bug**
In dev tools console, see:

```
 ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at ObjectTreeModel.getElementLocation (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:142:23)
    at ObjectTreeModel.getNode (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:123:33)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:72
    at Array.map (<anonymous>)
    at WorkbenchObjectTree.AbstractTree.setSelection (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:34)
    at TreeResourceNavigator2.onFocus (file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:486:23)
    at file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:480:87
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:714:67
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:54
    at Array.forEach (<anonymous>)
    at EventBufferer.bufferEvents (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:20)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:659:37
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at IndexTreeModel.splice (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:83:31)
    at ObjectTreeModel.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:60:31)
    at WorkbenchObjectTree.ObjectTree.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTree.js:28:31)
    at SearchView.refreshTree (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:340:27)
    at SearchView.refreshAndUpdateCount (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:334:25)
    at SearchView.onSearchResultsChanged (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:325:29)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:198:97
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:603:93
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at FolderMatch.BaseFolderMatch.clear (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:433:28)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:647:86
    at Array.forEach (<anonymous>)
    at SearchResult.clear (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:647:34)
    at SearchModel.search (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:826:31)
    at SearchView.doSearch (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:1157:35)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:1024:50
log.ts:173   ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at ObjectTreeModel.getElementLocation (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:142:23)
    at ObjectTreeModel.getNode (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:123:33)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:72
    at Array.map (<anonymous>)
    at WorkbenchObjectTree.AbstractTree.setSelection (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:34)
    at TreeResourceNavigator2.onFocus (file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:486:23)
    at file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:480:87
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:714:67
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:54
    at Array.forEach (<anonymous>)
    at EventBufferer.bufferEvents (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:20)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:659:37
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at IndexTreeModel.splice (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:83:31)
    at ObjectTreeModel.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:60:31)
    at WorkbenchObjectTree.ObjectTree.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTree.js:28:31)
    at SearchView.refreshTree (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:340:27)
    at SearchView.refreshAndUpdateCount (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:334:25)
    at SearchView.onSearchResultsChanged (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:325:29)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:198:97
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:603:93
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at BaseFolderMatch.clear (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:433:28)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:647:86
    at Array.forEach (<anonymous>)
    at SearchResult.clear (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:647:34)
    at SearchModel.search (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/common/searchModel.js:826:31)
    at SearchView.doSearch (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:1157:35)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:1024:50
log.ts:173   ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at ObjectTreeModel.getElementLocation (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:142:23)
    at ObjectTreeModel.getNode (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:123:33)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:72
    at Array.map (<anonymous>)
    at WorkbenchObjectTree.AbstractTree.setSelection (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:34)
    at TreeResourceNavigator2.onFocus (file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:486:23)
    at file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:480:87
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:714:67
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:54
    at Array.forEach (<anonymous>)
    at EventBufferer.bufferEvents (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:20)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:659:37
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at IndexTreeModel.splice (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:83:31)
    at ObjectTreeModel.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:60:31)
    at WorkbenchObjectTree.ObjectTree.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTree.js:28:31)
    at SearchView.refreshTree (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:340:27)
    at SearchView.refreshAndUpdateCount (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:334:25)
    at file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:1150:27
log.ts:173   ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at ObjectTreeModel.getElementLocation (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:142:23)
    at ObjectTreeModel.getNode (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:123:33)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:72
    at Array.map (<anonymous>)
    at WorkbenchObjectTree.AbstractTree.setSelection (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:872:34)
    at TreeResourceNavigator2.onFocus (file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:486:23)
    at file:///Users/matb/projects/vscode/out/vs/platform/list/browser/listService.js:480:87
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:714:67
    at file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:54
    at Array.forEach (<anonymous>)
    at EventBufferer.bufferEvents (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:727:20)
    at file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/abstractTree.js:659:37
    at Emitter.fire (file:///Users/matb/projects/vscode/out/vs/base/common/event.js:542:38)
    at IndexTreeModel.splice (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:83:31)
    at ObjectTreeModel.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:60:31)
    at WorkbenchObjectTree.ObjectTree.setChildren (file:///Users/matb/projects/vscode/out/vs/base/browser/ui/tree/objectTree.js:28:31)
    at SearchView.refreshTree (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:340:27)
    at SearchView.refreshAndUpdateCount (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:334:25)
    at SearchView.onSearchResultsChanged (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:325:29)
    at onComplete (file:///Users/matb/projects/vscode/out/vs/workbench/parts/search/browser/searchView.js:1044:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

VS Code version: code-oss-dev 1.31.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by roblourens** [comment]
@joaomoreno seems that this was caused by 31feeba3f33dfb86ff481b77e91b9089475da8a1

**Comment by roblourens** [comment]
I think this is also causing an issue in the settings tree

- Search `zoom`
- Click one of the TOC items
- They blink selected but the become unselected because when the tree rerenders (technically not necessary so I could try to work around it on my end) they get unfocused

**Comment by joaomoreno** [comment]
@roblourens That last flicker issue happens because you rerender the whole tree when focus changes: https://github.com/Microsoft/vscode/blob/66b8820e56a23a38c4f4b21ee47c71fc15a8736f/src/vs/workbench/parts/preferences/electron-browser/settingsEditor2.ts#L563. Both focus and selection go through a huge round trip of changes and the flicker happens. This is very strange and we should go in a talk so I understand what you're trying to do here. Ping me next milestone.

**Comment by roblourens** [comment]
I think the previous 'refresh' API didn't rerender if nothing changed but setChildren always does, so I will rethink some of this during debt week...
