### ISSUE TITLE
Errors while scrolling in extensions view

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67604]
- Open extensions view
- "Show Popular Extensions"
- Scroll down for a bit

See a lot of `Got bad scroll event: {width: 0, scrollWidth: 0, scrollLeft: 0, height: 735, scrollHeight: 601400, …}`

and

```
Cannot read property 'identifier' of null: TypeError: Cannot read property 'identifier' of null
    at t.set [as extension] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5515:702)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2802:1012
    at Array.forEach (<anonymous>)
    at n.set [as extension] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2802:974)
    at Object.set extension [as extension] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5541:53)
    at e.renderPlaceholder (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5541:396)
    at e.renderElement (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:889:702)
    at e.renderElement (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:874:856)
    at e.insertItemInDOM (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:428:978)
    at e.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:427:854)
    at e.onScroll (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:434:185)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:332)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:404:911
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t._setState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:212:817)
    at t.setScrollPositionNow (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:211:357)
    at t._onMouseWheel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:409:125)
    at HTMLDivElement.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:40
```

**Comment by joaomoreno** [comment]
@sandy081 

```
  ERR Cannot read property 'identifier' of null: TypeError: Cannot read property 'identifier' of null
    at StatusLabelAction.set [as extension] (file:///home/joao/Work/vscode/out/vs/workbench/parts/extensions/electron-browser/extensionsActions.js:2047:124)
    at file:///home/joao/Work/vscode/out/vs/workbench/parts/extensions/common/extensions.js:56:75
    at Array.forEach (<anonymous>)
    at ExtensionContainers.set [as extension] (file:///home/joao/Work/vscode/out/vs/workbench/parts/extensions/common/extensions.js:56:33)
    at Object.set extension [as extension] (file:///home/joao/Work/vscode/out/vs/workbench/parts/extensions/electron-browser/extensionsList.js:127:51)
    at Renderer.renderPlaceholder (file:///home/joao/Work/vscode/out/vs/workbench/parts/extensions/electron-browser/extensionsList.js:141:28)
    at PagedRenderer.renderElement (file:///home/joao/Work/vscode/out/vs/base/browser/ui/list/listPaging.js:37:27)
    at PipelineRenderer.renderElement (file:///home/joao/Work/vscode/out/vs/base/browser/ui/list/listWidget.js:730:26)
    at ListView.insertItemInDOM (file:///home/joao/Work/vscode/out/vs/base/browser/ui/list/listView.js:408:26)
    at ListView.render (file:///home/joao/Work/vscode/out/vs/base/browser/ui/list/listView.js:353:26)
    at ListView.onScroll (file:///home/joao/Work/vscode/out/vs/base/browser/ui/list/listView.js:606:22)
    at Emitter.fire (file:///home/joao/Work/vscode/out/vs/base/common/event.js:545:41)
    at file:///home/joao/Work/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:123:33
    at Emitter.fire (file:///home/joao/Work/vscode/out/vs/base/common/event.js:542:38)
    at Scrollable._setState (file:///home/joao/Work/vscode/out/vs/base/common/scrollable.js:227:28)
    at Scrollable.setScrollPositionNow (file:///home/joao/Work/vscode/out/vs/base/common/scrollable.js:160:18)
    at ScrollableElement.AbstractScrollableElement._onMouseWheel (file:///home/joao/Work/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:284:42)
    at HTMLDivElement.onMouseWheel (file:///home/joao/Work/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:234:27)
```
