### ISSUE TITLE
Renderer windows error 

### ISSUE THREAD

**Issue by EddieNejadi** [Microsoft/vscode#67646]
I got the following error during running some of my extensions like setting sync:

> Cannot read property 'concat' of undefined
I can see the following error right after opening vs code even without running any extension command 
`[2019-01-31 09:17:31.066] [renderer1] [error] Cannot read property 'concat' of undefined: TypeError: Cannot read property 'concat' of undefined
	at new u (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:51:4995)
	at module.exports.t.Sync.<anonymous> (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71779)
	at Generator.next (<anonymous>)
	at module.exports.n (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71507)
	at new Promise (<anonymous>)
	at module.exports.n (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71284)
	at module.exports.t.Sync.bootstrap (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71738)
	at C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:46974
	at Generator.next (<anonymous>)
	at s (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:46614)
	at <anonymous>`

my other extensions are:
PS C:\WINDOWS\system32> code --list-extensions
DavidAnson.vscode-markdownlint
DotJoshJohnson.xml
eg2.tslint
formulahendry.code-runner
hollowtree.vue-snippets
ms-python.python
ms-vscode.Go
octref.vetur
PeterJausovec.vscode-docker
robertohuertasm.vscode-icons
sdras.vue-vscode-snippets
Shan.code-settings-sync
streetsidesoftware.code-spell-checker
Tyriar.shell-launcher
vscodevim.vim
vscoss.vscode-ansible

* vs code information:
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by dbaeumer** [comment]
Please report the error to the provider of the settings sync extension (`shan.code-settings-sync-3.2.4`)
