### ISSUE TITLE
errors in error panel - "ERR Tree element not found"

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67658]
Sorry no steps, but I have just found this. The panel is currently *not* visible but might have been doing me verifying bugs...

```
ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at e.getElementLocation (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:99:517)
    at e.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:887)
    at n.e.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1016:19)
    at t.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4891:276)
    at t.autoReveal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4891:95)
    at t.onActiveEditorChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4888:212)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:332)
    at t.doEmitActiveEditorChangeEvent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4902:709)
    at t.handleActiveEditorChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4902:485)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4902:833
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5339:314
workbench.main.js:1533   ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at e.getElementLocation (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:99:517)
    at e.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:887)
    at n.e.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1016:19)
    at t.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4891:276)
    at t.autoReveal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4891:95)
    at t.onActiveEditorChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4888:212)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:332)
    at t.doEmitActiveEditorChangeEvent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4902:709)
    at t.handleActiveEditorChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4902:485)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4901:923
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t.doSetGroupActive (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5359:901)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5359:343
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5332:15
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3832:82
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2662:118
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:163:201
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at HTMLDivElement.r (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:1001)
    at t.setSelectionRange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:538:448)
    at e.writeToTextArea (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:518:580)
    at a._setAndWriteTextAreaState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:535:850)
    at a.writeScreenReaderContent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:536:32)
    at a._setHasFocus (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:535:657)
    at a.focusTextArea (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:535:411)
    at t.focusTextArea (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1996:289)
    at t.focus (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2023:275)
    at t.focus (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2043:450)
    at t.focus (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4270:742)
    at t.focus (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5338:100)
    at t.doCloseActiveEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5341:845)
    at t.doCloseAllEditors (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5344:457)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5344:300
```

**Comment by jrieken** [comment]
None minified stack trace

```
ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at ObjectTreeModel.getElementLocation (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:142:23)
    at ObjectTreeModel.isCollapsed (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:111:33)
    at WorkbenchObjectTree.AbstractTree.isCollapsed (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/abstractTree.js:905:31)
    at MarkersPanel.revealMarkersForCurrentActiveEditor (file:///Users/jrieken/Code/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanel.js:496:32)
    at MarkersPanel.autoReveal (file:///Users/jrieken/Code/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanel.js:489:22)
    at MarkersPanel.onActiveEditorChanged (file:///Users/jrieken/Code/vscode/out/vs/workbench/parts/markers/electron-browser/markersPanel.js:400:18)
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:545:41)
    at EditorService.doEmitActiveEditorChangeEvent (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/editor/browser/editorService.js:102:43)
    at EditorService.handleActiveEditorChange (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/editor/browser/editorService.js:96:18)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/services/editor/browser/editorService.js:73:92
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:542:38)
    at EditorPart.doSetGroupActive (file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:502:42)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:464:23
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:542:38)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:290:35
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:542:38)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:145:111
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:542:38)
    at file:///Users/jrieken/Code/vscode/out/vs/workbench/browser/composite.js:78:91
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:542:38)
    at onFocus (file:///Users/jrieken/Code/vscode/out/vs/base/browser/dom.js:826:39)
    at Emitter.fire (file:///Users/jrieken/Code/vscode/out/vs/base/common/event.js:542:38)
    at HTMLDivElement.fn (file:///Users/jrieken/Code/vscode/out/vs/base/browser/event.js:9:48)
    at TextAreaWrapper.setSelectionRange (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/textAreaInput.js:499:26)
    at TextAreaState.writeToTextArea (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/textAreaState.js:29:26)
    at TextAreaInput._setAndWriteTextAreaState (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/textAreaInput.js:366:27)
    at TextAreaInput.writeScreenReaderContent (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/textAreaInput.js:374:18)
    at TextAreaInput._setHasFocus (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/textAreaInput.js:352:26)
    at TextAreaInput.focusTextArea (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/textAreaInput.js:334:18)
    at TextAreaHandler.focusTextArea (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/textAreaHandler.js:326:33)
    at View.focus (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:374:35)
    at Object.focusTextArea (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/view/viewImpl.js:138:27)
    at focus (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:162:38)
    at TouchHandler.MouseHandler._onMouseDown (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:166:17)
    at file:///Users/jrieken/Code/vscode/out/vs/editor/browser/controller/mouseHandler.js:53:111
    at HTMLDivElement.<anonymous> (file:///Users/jrieken/Code/vscode/out/vs/editor/browser/editorDom.js:104:17)
```

**Comment by sandy081** [comment]
@joaomoreno Looks like my model and tree are out of sync. How can I check if the tree contains my model element or not?

**Comment by joaomoreno** [comment]
> How can I check if the tree contains my model element or not?

The right question is "how did the model get out of sync"? Otherwise you're going to have to populate your code with `if (tree.hasElement(e)) { ... }`
