### ISSUE TITLE
Extensions list: Cannot read property 'identifier' of null

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67673]
Issue Type: <b>Bug</b>

**Repo**
1. Open extensions panel
1. Search for `a` in extensions
1. Wait for initial results to load
1. Quickly scroll through the rest of the list

**Bug**
See the following in the developer console:

```
listView.ts:697 Got bad scroll event: {width: 0, scrollWidth: 0, scrollLeft: 0, height: 1105, scrollHeight: 197160, …}
e.onScroll @ listView.ts:697
e.fire @ event.ts:569
(anonymous) @ scrollableElement.ts:177
e.fire @ event.ts:567
t._setState @ scrollable.ts:334
t.setScrollPositionNow @ scrollable.ts:258
t._onMouseWheel @ scrollableElement.ts:376
i @ scrollableElement.ts:312
```

```
log.ts:173   ERR Cannot read property 'identifier' of null: TypeError: Cannot read property 'identifier' of null
    at t.set [as extension] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5521:702)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2805:1012
    at Array.forEach (<anonymous>)
    at n.set [as extension] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2805:974)
    at Object.set extension [as extension] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5547:53)
    at e.renderPlaceholder (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5547:396)
    at e.renderElement (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:889:702)
    at e.renderElement (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:874:856)
    at e.insertItemInDOM (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:428:978)
    at e.render (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:427:854)
    at e.onScroll (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:434:185)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:332)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:404:911
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t._setState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:212:817)
    at t.setScrollPositionNow (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:211:357)
    at t._onMouseWheel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:409:125)
    at HTMLDivElement.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:408:3)
```

VS Code version: Code - Insiders 1.31.0-insider (7f136b44cff0cd3486ac88b43598b8c72b025d16, 2019-01-31T06:13:53.077Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_22394202|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
comment-tagged-templates|bie|0.2.1
emojisense|bie|0.4.1
folder-source-actions|bie|0.0.4
github-markdown-preview|bie|0.0.2
lit-html|bie|1.11.0
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-image-size|bie|0.0.2
markdown-mermaid|bie|1.1.2
markdown-preview-github-styles|bie|0.1.4
speech|bie|0.0.2
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
vscode-npm-script|eg2|0.3.5
vscode-pull-request-github|Git|0.3.2
vscode-styled-components|jpo|0.0.25
vscode-memfs|jri|0.0.3
theme-karyfoundation-themes|kar|18.2.1
vscode-sshfs|Kel|1.11.2
vscode-azurefunctions|ms-|0.13.1
vscode-cosmosdb|ms-|0.9.1
vscode-language-pack-de|MS-|1.31.2
vscode-language-pack-zh-hans|MS-|1.31.2
mssql|ms-|1.4.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
Go|ms-|0.8.0
vscode-typescript-tslint-plugin|ms-|0.4.0
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
live-server-preview|neg|0.1.4
java|red|0.38.0
shader|sle|1.1.4
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0

(16 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Duplicate of #67604
