### ISSUE TITLE
Callstack is broken when multiple debug sessions are present

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67898]
- Start a launch config
- Start a second launch config
- Click between the two debug session entries in the callstack, see weirdness

![image](https://user-images.githubusercontent.com/323878/52245290-e2186b00-2895-11e9-8a19-8b026d9be278.png)

```
TypeError: Cannot read property 'set' of undefined
    at ThreadsRenderer.renderElement (file:///Users/roblou/code/vscode2/out/vs/workbench/parts/debug/electron-browser/callStackView.js:365:24)
    at DataTreeRenderer.renderElement (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/asyncDataTree.js:143:27)
    at TreeRenderer.renderElement (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/abstractTree.js:184:27)
    at PipelineRenderer.renderElement (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/listWidget.js:731:26)
    at ListView.insertItemInDOM (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/listView.js:408:26)
    at ListView._splice (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/listView.js:231:26)
    at ListView.splice (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/listView.js:165:29)
    at file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/splice.js:13:62
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/splice.js:13:30)
    at file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/listWidget.js:1050:83
    at EventBufferer.bufferEvents (file:///Users/roblou/code/vscode2/out/vs/base/common/event.js:725:21)
    at TreeNodeList.List.splice (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/list/listWidget.js:1050:32)
    at TreeNodeList.splice (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/abstractTree.js:626:37)
    at IndexTreeModel.splice (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/indexTreeModel.js:108:27)
    at ObjectTreeModel.setChildren (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/objectTreeModel.js:60:31)
    at ObjectTree.setChildren (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/objectTree.js:28:31)
    at WorkbenchAsyncDataTree.AsyncDataTree.render (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/asyncDataTree.js:874:23)
    at WorkbenchAsyncDataTree.<anonymous> (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/asyncDataTree.js:621:34)
    at step (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/asyncDataTree.js:46:23)
    at Object.next (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/asyncDataTree.js:27:53)
    at fulfilled (file:///Users/roblou/code/vscode2/out/vs/base/browser/ui/tree/asyncDataTree.js:18:58)
```

**Comment by roblourens** [comment]
Oh I see it's already fixed
