### ISSUE TITLE
TFS / TFVC / Azure extension broken

### ISSUE THREAD

**Issue by onelifenyc** [Microsoft/vscode#68015]
- VSCode Version: 1.31.0
- OS Version: windows 10 pro 

Steps to Reproduce:

1. Launch project (folder)
2. TFS connection does not work
3. Try to authenticate - dies silently after correct password is entered 

In reality on startup of vscode Log(Window) shows the following:

```
[2019-02-06 17:43:35.450] [renderer1] [error] Cannot set property 'resourceStates' of undefined: TypeError: Cannot set property 'resourceStates' of undefined
	at TfvcSCMProvider.onDidModelChange (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\tfvcscmprovider.js:128:44)
	at e.fire (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:133)
	at Model.<anonymous> (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:188:31)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:8:58)
```

Does this issue occur when all extensions are disabled?: N/A

**Comment by onelifenyc** [comment]
Extra details:
I did put back 1.30.0. The Azure Repos (the extension in question) needed to authenticate again but it did so successfully.

However, I did see the same error in my original post in the Log(Window):
`[2019-02-06 17:54:09.856] [renderer1] [error] Cannot set property 'resourceStates' of undefined: TypeError: Cannot set property 'resourceStates' of undefined
	at TfvcSCMProvider.onDidModelChange (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\tfvcscmprovider.js:128:44)
	at e.fire (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:238)
	at Model.<anonymous> (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:188:31)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\...\.vscode\extensions\ms-vsts.team-1.144.1\out\src\tfvc\scm\model.js:8:58)
	at <anonymous>`

**Comment by kieferrm** [comment]
Moved to https://github.com/Microsoft/azure-repos-vscode/issues/477. 

/cc @joaomoreno

**Comment by onelifenyc** [comment]
@kieferrm @joaomoreno are we making an educated assumption that the extension should be fixed/updated even though we know that the extension host process script in vscode repo did get updated with 1.31 of vscode?
