### ISSUE TITLE
launching task fails upon closing the terminal

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/vscode#68187]
Issue Type: <b>Bug</b>

1. open a workspace folder
2. run a task
3. after successfull run, close the terminal
4. again run the same task or another one
5. the following error appears 'Failed to create terminal for task build-kernel', in my case 'build-kernel' is my task label

copy-paste from developer tool window:
  ERR Cannot read property 'group' of undefined: TypeError: Cannot read property 'group' of undefined
    at e.createTerminal (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3320:796)
    at l (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3314:873)
    at new Promise (<anonymous>)
    at e.executeInTerminal (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3314:834)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3311:394
    at process._tickCallback (internal/process/next_tick.js:68:7)
log.ts:173   ERR Failed to create terminal for task build-kernel: Error: Failed to create terminal for task build-kernel
    at e.executeInTerminal (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3317:152)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3311:394
    at process._tickCallback (internal/process/next_tick.js:68:7)

VS Code version: Code - Insiders 1.32.0-insider (45c7f29565821668f4d010b25e3289953bd9ac71, 2019-02-07T10:22:16.187Z)
OS version: Linux x64 4.20.7-042007-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 2990WX 32-Core Processor (64 x 1715)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|125.83GB (120.48GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
code-runner|for|0.9.7
sftp|lix|1.9.3
python|ms-|2019.1.0
cpptools|ms-|0.22.0-insiders
merge-n-paste|RAW|1.0.4
shellman|Rem|4.2.0
bash-debug|rog|0.3.3
highlight-words|rsb|0.1.1
partial-diff|ryu|1.4.0
code-spell-checker|str|1.6.10
ninja|sur|0.0.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
debug|web|0.22.0
change-case|wma|1.0.0

</details>

**Comment by 123swk123** [comment]
closing this since its duplicate of #68150 , i hope OS type and vscode version does not influence this bug.
