### ISSUE TITLE
VSCode become unresponsive when provided wrong name for terminal in integratedTerminal setting.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6834]
- VSCode Version: Latest alpha
- OS Version: WIndows10

Steps to Reproduce:
1.  Launch VSCode and update setting in settings.json to some random text or just "powershell" (no extension) or "cms"
![image](https://cloud.githubusercontent.com/assets/17735796/15517237/9d6f3df6-21ab-11e6-97a3-c8c70084ba4f.png)
2. Reload window to get reflection of the new setting.
3. Now try to launch terminal window with CTRL+` and verify app behavior.

Actual:
1. Most of the time Application is not responsive.
2. Restart app didn't solve the issue.
3. user is not able to modify settings as user not able to set mouse point on editor window.
4. In taskmanager you see VSCode is consuming lots of memory 
![image](https://cloud.githubusercontent.com/assets/17735796/15517426/82e1c3a4-21ac-11e6-8beb-4d56d47e81f1.png)

 **I could see Error: write EPIPE in developer tool.**

index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31 Error: write EPIPE
    at exports._errnoException (util.js:890:11)
    at ChildProcess.target._send (internal/child_process.js:634:20)
    at ChildProcess.target.send (internal/child_process.js:521:19)
    at Terminal.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:4:2809)
    at Terminal.EventEmitter.emit (C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\node_modules\term.js\src\term.js:3493:8)
    at Terminal.keyDown (C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\node_modules\term.js\src\term.js:3196:8)
    at HTMLDocument.<anonymous> (C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\node_modules\term.js\src\term.js:594:29)

**Comment by v-pavanp** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/6683
