### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by cameron-sjo** [Microsoft/vscode#68561]
Issue Type: <b>Bug</b>

I get the following error after running `npm install` on my Chatbot project directory. While, I don't think the two are correlated, this is my best guess. 

Usually reinstalling VS Code will fix the issues. I've attempted to run it without extensions and even then it fails to launch with the same error.

Error:
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'C:\ProgramData\App-V\C29289BF-2472-4D99-ABC3-E50C501ECC49\04D81759-70D3-4D0F-BEFF-42BB3C1244D2\Root\VFS\ProgramFilesX64\Microsoft VS Code\resources\app\out\main'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\ProgramData\App-V\C29289BF-2472-4D99-ABC3-E50C501ECC49\04D81759-70D3-4D0F-BEFF-42BB3C1244D2\Root\VFS\ProgramFilesX64\Microsoft VS Code\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (C:\ProgramData\App-V\C29289BF-2472-4D99-ABC3-E50C501ECC49\04D81759-70D3-4D0F-BEFF-42BB3C1244D2\Root\VFS\ProgramFilesX64\Microsoft VS Code\resources\electron.asar\browser\init.js:171:8)
    at Object.<anonymous> (C:\ProgramData\App-V\C29289BF-2472-4D99-ABC3-E50C501ECC49\04D81759-70D3-4D0F-BEFF-42BB3C1244D2\Root\VFS\ProgramFilesX64\Microsoft VS Code\resources\electron.asar\browser\init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

[OK]
```

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (21.37GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
cake-vscode|cak|0.11.4
gitlens|eam|9.5.0
csharp|ms-|1.17.1
team|ms-|1.144.1
code-spell-checker|str|1.6.10

</details>

**Comment by cameron-sjo** [comment]
Issue is still occuring on 1.31.1

**Comment by cameron-sjo** [comment]
I've ended up downgrading to 1.30.2, and seems to be working. I figured out that I can successfully open Code if it's opened from the installer. As soon as that process is closed, the application will fail to launch the next time.

```
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.15063
```

**Comment by joaomoreno** [comment]
Does the `C:\ProgramData\App-V\C29289BF-2472-4D99-ABC3-E50C501ECC49\04D81759-70D3-4D0F-BEFF-42BB3C1244D2\Root\VFS\ProgramFilesX64\Microsoft VS Code\resources\app\out\main` file exist on disk?

**Comment by cameron-sjo** [comment]
I haven't been able to replicate the issue since I downgraded and it automagically updated to latest.

I'll close the issue until I can get the issue to replicate again.
