### ISSUE TITLE
JS/TS language settings not working, cannot change TypeScript version

### ISSUE THREAD

**Issue by furkle** [Microsoft/vscode#68668]
Issue Type: <b>Bug</b>

I cannot access any Intellisense features whatsoever, the right click menu has only "change all occurrences," cut, copy, paste, and "command palette", and I cannot change the TypeScript version. When I attempt to do so, I get the following error log:

```
[2019-02-13 22:36:47.695] [exthost] [error] TypeError: Cannot read property 'serviceClient' of undefined
	at t.SelectTypeScriptVersionCommand.execute (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:70764)
	at e._executeContributedCommand (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:485:959)
	at e.$executeContributedCommand (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:486:443)
	at t._doInvokeHandler (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) typescript.selectTypeScriptVersion
```

I have uninstalled and reinstalled the editor, disabled all extensions, and tried the insiders edition, and none change this.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (9.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>
Extension|Author (truncated)|Version
---|---|---
monitrc|dru|0.0.1
dotenv|mik|1.0.1
python|ms-|2019.1.0
vscode-docker|Pet|0.5.2
wallaby-vscode|Wal|1.0.109
</details>

**Comment by furkle** [comment]
Closed, discovered the issue was a PATH problem as discussed in https://github.com/Microsoft/vscode/issues/17945. Closing the editor and reopening it was necessary for the editor to start working again.
