### ISSUE TITLE
Cannot read property `extensionId` of undefined

### ISSUE THREAD

**Issue by selfrefactor** [Microsoft/vscode#68699]
- VSCode Version: latest `insiders`
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Upgrade to latest Insiders
2. Try to disable extension from extension menu

Does this issue occur when all extensions are disabled?: Yes/No

This is the output of Log(Window):

```
[2019-02-14 13:26:53.227] [renderer1] [info] no standard startup: panel is active
[2019-02-14 13:27:34.554] [renderer1] [info] no standard startup: not a new window
[2019-02-14 13:27:38.324] [renderer1] [error] Cannot read property 'extensionId' of undefined: TypeError: Cannot read property 'extensionId' of undefined
    at e.filter.e (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4948:256)
    at Array.filter (<anonymous>)
    at Function.getColorThemes (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4948:201)
    at e.getActionGroups (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4934:303)
    at U.<anonymous> (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:5311:260)
    at Generator.next (<anonymous>)
    at r (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:30:772)
```

Removing extension folder did not help.

**Comment by NeckBeardPrince** [comment]
Getting same thing

MacOS Insiders: 1.32.0-Insider

Only happens on my Installed Extensions.
I disabled all Extensions did not help.

**Comment by kieferrm** [comment]
Works for me on macOS for both the stable and insiders.

**Comment by sandy081** [comment]
@selfrefactor May I know which extension are you trying to disable?

**Comment by selfrefactor** [comment]
any

**Comment by sandy081** [comment]
@aeschli Is it possible that `extensionData` of a theme can be undefined?

https://github.com/Microsoft/vscode/blob/6002b5d43c2bf45b284d01572a56abd451288441/src/vs/workbench/contrib/extensions/electron-browser/extensionsActions.ts#L1128

**Comment by aeschli** [comment]
@sandy081 Yes, the unloaded themes (alive only in the veriy beginning) do not have a extensionData.
It is a bug that this survived longer. Pushed a fix but also adopted your code

**Comment by sbatten** [comment]
I could not reproduce this issue in builds from the time the issue was created so I can't say this is verified. If OP could verify, that would be ideal.

**Comment by selfrefactor** [comment]
I am still experiencing the issue and start to learn living with it. I opened this issue not so much for my convenience as to contribute to VSCode. I see that @sandy081 made a commit referencing this issue and I do hope that the next VSCode release will fix it. I can report how the next build influence this issue, but for now it is still on.

**Comment by sandy081** [comment]
This is the same commit as @aeschli

**Comment by selfrefactor** [comment]
The new version indeed fixes the bug - hurrah!
