### ISSUE TITLE
Broken syntax coloring

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#68764]
- VSCode Version: 1.31.1
- OS Version: macOS latest

I got this yesterday, I thought it's same issue as this: https://github.com/Microsoft/vscode/issues/66322, but @roblourens suggested me to open a new issue. I don't know how it was related but one of my file syntax colorings was broken. I didn't use a debugger, just updated VS Code and after some time run into this issue. **I can't reproduce it anymore, seems it works fine after `Reload Window`.**

### Broken coloring

<img width="787" alt="screenshot 2019-02-14 at 14 04 10" src="https://user-images.githubusercontent.com/10441177/52785747-6f5f7a80-3061-11e9-8712-3957792f6fca.png">

**I'm using Default Dark+ theme.**

<hr>

### Log (Window)
```
[2019-02-14 09:57:03.218] [renderer1] [error] Cannot read property 'adapter' of undefined: TypeError: Cannot read property 'adapter' of undefined
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:553:140)
	at e.$provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:556:796)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644:118)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:744)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:256)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:155)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:960
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38:994
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-02-14 13:46:06.244] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
```

### Log (Extension Host)

```
[2019-02-14 13:46:06.242] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-02-14 13:46:06.242] [exthost] [error] {"label":"Acquiring typings...","detail":"Acquiring typings definitions for IntelliSense."}
```

### Toggle Developer Tools (Warnings)

```
[Extension Host] INVALID text edit -> must have at least a label
```

```
[e2e] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
```

```
 at s (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1874:428)
    at Object.t.attachBadgeStyler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1874:713)
    at e.renderTemplate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5255:459)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:874:798
    at Array.map (<anonymous>)
    at e.renderTemplate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:874:773)
    at e.alloc (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:177:207)
    at e.insertItemInDOM (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:428:686)
    at e.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:427:854)
    at e.onScroll (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:434:185)
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:332)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:404:911
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t._setState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:212:817)
    at t.setScrollDimensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:210:923)
    at t.setScrollDimensions (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:407:198)
    at e.layout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:427:294)
    at i.e.layout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:884:135)
    at t.layoutBody (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5266:492)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5264:75
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at t.layout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:949:145)
    at t.layoutBody (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5266:396)
    at t.e.layout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:492:340)
    at Object.layout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:445:146)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:153
    at Array.forEach (<anonymous>)
    at t.layoutViews (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:453:124)
    at t.relayout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:447:520)
    at t.addView (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:446:268)
    at t.addPanel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:496:263)
    at t.addPanel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4995:747)
    at t.addPanels (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4994:940)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5275:313
    at Array.forEach (<anonymous>)
    at t.onSelectionChange (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5275:291)
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:332)
    at t.onListSelectionChange (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5254:372)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:996
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:744
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at e.set (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:860:131)
    at i.e.setSelection (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:884:316)
    at t.restoreSelection (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5254:624)
    at t.onListSelectionChange (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5254:271)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:996
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:730
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:899
    at Array.forEach (<anonymous>)
    at e.bufferEvents (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:872)
    at i.e.splice (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:883:42)
    at t.splice (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5253:238)
    at t.onDidChangeVisibility (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5253:6)
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:332)
    at t.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2668:974)
    at t.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5273:145)
    at o.t.showComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5329:967)
    at o.t.doOpenComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5327:626)
    at o.t.openComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5327:123)
    at o.doOpenViewlet (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5393:335)
    at o.openViewlet (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5392:657)
    at t.run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4988:80)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2587:698
e.check @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1536   ERR An unknown error occurred. Please consult the log for more details.
```

**Comment by svipben** [comment]
Seems again color is broken and I got this:

# Log (Window)
```
[2019-02-18 08:31:49.944] [renderer1] [info] no standard startup: not the explorer viewlet
[2019-02-18 14:40:32.063] [renderer1] [error] Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at i.e.getDataNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1037:266)
    at i.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1034:703)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:33:935
    at Object.next (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:33)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:33:160
    at new Promise (<anonymous>)
    at i (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:32:952)
    at i.e.expand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1034:342)
    at Array.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5627:417)
    at t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:105:891)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

# Toggle Developer Tools
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3366 [Extension Host] debugger listening on port 52314
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3364 Extension Host
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3364 Debugger listening on ws://127.0.0.1:52314/8f2aca64-9263-446a-8db6-d948aa09baf7
For help, see: https://nodejs.org/en/docs/inspector

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:287 [Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1535  INFO no standard startup: not the explorer viewlet
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:287 [Extension Host] Warning: The 'prefer-readonly' rule requires type information.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:287
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1536   ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at i.e.getDataNode (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1037:266)
    at i.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1034:703)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:33:935
    at Object.next (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:33)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:33:160
    at new Promise (<anonymous>)
    at i (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:32:952)
    at i.e.expand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1034:342)
    at Array.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5627:417)
    at t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:105:891)
    at process._tickCallback (internal/process/next_tick.js:68:7)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79 [83g] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
e.check @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79     at s (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1874:428)
    at Object.t.attachSelectBoxStyler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1876:48)
    at t [as constructor] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5745:628)
    at t.create (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:229:596)
    at t.e._createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1513:215)
    at t.e.createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1512:561)
    at t.getActionItem (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5763:196)
    at o.t.actionItemProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5332:437)
    at Object.actionItemProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5331:778)
    at Object.actionItemProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:993:756)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:926:566
    at Array.forEach (<anonymous>)
    at t.push (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:926:276)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:994:738
    at Array.forEach (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:994:706
    at o.t.showComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5329:575)
    at o.t.doOpenComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5327:626)
    at o.t.openComposite (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5327:123)
    at o.openPanel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5381:533)
    at t.run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2671:930)
    at t.run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5732:186)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2587:698
e.check @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79
event.ts:434 [83g] potential listener LEAK detected, having 196 listeners already. MOST frequent listener (3):
e.check @ event.ts:434
_event._event @ event.ts:514
t @ viewImpl.ts:119
t._createView @ codeEditorWidget.ts:1454
t._attachModel @ codeEditorWidget.ts:1352
t.setModel @ codeEditorWidget.ts:411
(anonymous) @ textResourceEditor.ts:79
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
(anonymous) @ textResourceEditor.ts:64
Promise.then (async)
t.setInput @ textResourceEditor.ts:63
t.setInput @ outputPanel.ts:127
t.doShowChannel @ outputServices.ts:599
t.onDidPanelOpen @ outputServices.ts:529
(anonymous) @ outputServices.ts:462
(anonymous) @ event.ts:56
e.fire @ event.ts:567
t.doOpenComposite @ compositePart.ts:155
t.openComposite @ compositePart.ts:112
o.openPanel @ panelPart.ts:230
t.run @ panelActions.ts:185
t.runAction @ actions.ts:209
t.run @ actions.ts:201
t.onClick @ actionbar.ts:169
(anonymous) @ actionbar.ts:139
runCallback @ timers.js:696
tryOnImmediate @ timers.js:667
processImmediate @ timers.js:649
event.ts:435     at s (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1874:428)
    at Object.t.attachListStyler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1880:950)
    at e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2277:875)
    at t.create (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:229:596)
    at t.e._createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1513:215)
    at t.e.createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1512:561)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2292:432
    at e._executor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:113:534)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:113:628
e.check @ event.ts:435
_event._event @ event.ts:514
t @ viewImpl.ts:119
t._createView @ codeEditorWidget.ts:1454
t._attachModel @ codeEditorWidget.ts:1352
t.setModel @ codeEditorWidget.ts:411
(anonymous) @ textResourceEditor.ts:79
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
(anonymous) @ textResourceEditor.ts:64
Promise.then (async)
t.setInput @ textResourceEditor.ts:63
t.setInput @ outputPanel.ts:127
t.doShowChannel @ outputServices.ts:599
t.onDidPanelOpen @ outputServices.ts:529
(anonymous) @ outputServices.ts:462
(anonymous) @ event.ts:56
e.fire @ event.ts:567
t.doOpenComposite @ compositePart.ts:155
t.openComposite @ compositePart.ts:112
o.openPanel @ panelPart.ts:230
t.run @ panelActions.ts:185
t.runAction @ actions.ts:209
t.run @ actions.ts:201
t.onClick @ actionbar.ts:169
(anonymous) @ actionbar.ts:139
runCallback @ timers.js:696
tryOnImmediate @ timers.js:667
processImmediate @ timers.js:649
```

**Comment by alexandrudima** [comment]
@svipben The errors in the console might be unrelated to the coloring problem. Can you please share with us your exact file, it might be something in that file that helps reproduce.

**Comment by svipben** [comment]
@alexandrudima It happens to different files, and it happened to me a second time and when I opened developer tools I saw exactly the same problem with listeners. I don't know how to reproduce it, why it happens, but what I can say it happens to different files, I will keep you updated with more info if I will run into this problem again.

**Comment by mjbvz** [comment]
Closing this as there has not been recent activity and no other users have reported hitting it
