### ISSUE TITLE
"workspaceContains:**" throws errors (only in insiders)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#68969]
In the current Insiders build I see this when running my tests:

```
Error: command failed with error code 2: error parsing glob '**/pubspec.yaml, **/*.dart': invalid use of **; must be one path component
extensionHostProcess.js:685
    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3815:49)
    at Promise.all.then.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4472:372)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This doesn't happen in stable. The only place I have those globs is in `packages.json` in `activationEvents/workspaceContains`:

```js
"activationEvents": [
	"onLanguage:dart",
	"onView:dartPackages",
	"workspaceContains:**/pubspec.yaml",
	"workspaceContains:**/*.dart",
	"onCommand:flutter.createProject",
	"onCommand:dart.createProject",
	"onCommand:_dart.flutter.createSampleProject",
	"onCommand:flutter.doctor",
	"onCommand:flutter.upgrade",
	"onUri"
],
```

In the docs, there's an example that uses `"workspaceContains:**/.editorconfig"`. It's not clear from the message (`invalid use of **; must be one path component`) what's wrong.

**Comment by jtsom** [comment]
Am seeing the same error, however I do not know what is causing it:
```
console.ts:134 [IPC Library: Search] command failed with error code 2: error parsing glob '/*.csproj, *.sln, *.csx, *.cake, **/*.csproj, **/*.sln, **/*.csx, **/*.cake': invalid use of **; must be one path component
console.ts:134 [Extension Host] Error: command failed with error code 2: error parsing glob '/*.csproj, *.sln, *.csx, *.cake, **/*.csproj, **/*.sln, **/*.csx, **/*.cake': invalid use of **; must be one path component

    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3819:70)
    at Promise.all.then.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4476:372)
    at process._tickCallback (internal/process/next_tick.js:68:7) (at S.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:687:920))
```
