### ISSUE TITLE
Script execution is prohibited  at Client

### ISSUE THREAD

**Issue by chetanclozio** [Microsoft/vscode#69140]
Hi Team,
I am facing an issue with when trying to debug Angular application. Getting below issue,
"Error: Script execution is prohibited at Client" 
Log details,

Error processing "launch": Error: Script execution is prohibited
    at Client.processMessage (c:\Users\chetanm\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:66:36)
    at LoggingSocket.Client.socket.on (c:\Users\chetanm\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:42:48)
    at LoggingSocket.emit (events.js:187:15)
    at Receiver.receiverOnMessage (c:\Users\chetanm\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\websocket.js:742:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (c:\Users\chetanm\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\receiver.js:417:14)
    at perMessageDeflate.decompress (c:\Users\chetanm\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\receiver.js:374:23)
    at _decompress (c:\Users\chetanm\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\permessage-deflate.js:298:9)
    at _inflate.flush (c:\Users\chetanm\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:480:3)

- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Run the angular application with - ng s
2. Start debugger by hitting F5.
3. Getting above error. 

Does this issue occur when all extensions are disabled?: Yes, tried with enabling / disabling chrome extension.

**Comment by roblourens** [comment]
Can you check whether javascript is enabled in Chrome? https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c8ceef8b-4edb-49cf-ac1c-302519652ea9/debuggerforchrome-error-processing-quotlaunchquot-script-execution-is-prohibited?forum=vsdebug

**Comment by chetanclozio** [comment]
Javascript is enabled in chrome. refer attachment for the same. I tried with chrome uninstall  and installation but not worked.
![2019-02-22_1456](https://user-images.githubusercontent.com/39291804/53232987-4b7be480-36b2-11e9-874c-281755c7d569.png)

**Comment by roblourens** [comment]
Is that the instance of chrome that was launched by vscode? When launching it for debugging, we launch with a fresh user profile, so it could have different settings.

If your computer is managed by corporate IT or something like that, maybe they are messing with your settings.
