### ISSUE TITLE
Potential listener leak detected

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#69191]
1. Open preferences UX and an editor side by side
2. Play around in the preferences UX (I was changing the font size and dragging the preferences editor to different editor groups)

Notice warning in dev tools

```
[8af] potential listener LEAK detected, having 200 listeners already. MOST frequent listener (10):
at attachStyler (file:///Users/isidor/Development/vscode/out/vs/platform/theme/common/styler.js:33:29)
    at Object.attachSelectBoxStyler (file:///Users/isidor/Development/vscode/out/vs/platform/theme/common/styler.js:68:16)
    at SettingEnumRenderer.renderTemplate (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/preferences/browser/settingsTree.js:582:44)
    at TreeRenderer.renderTemplate (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:152:48)
    at renderers.map.r (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:703:46)
    at Array.map (<anonymous>)
    at PipelineRenderer.renderTemplate (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:703:35)
    at RowCache.alloc (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/rowCache.js:32:47)
    at ListView.insertItemInDOM (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:365:39)
    at ListView.rerender (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:753:34)
    at ListView.layout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:310:26)
    at TreeNodeList.layout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listWidget.js:950:23)
    at SettingsTree.layout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/abstractTree.js:796:23)
    at SettingsEditor2.layoutTrees (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/preferences/electron-browser/settingsEditor2.js:976:31)
    at SettingsEditor2.layout (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/preferences/electron-browser/settingsEditor2.js:156:18)
    at EditorControl.layout (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:167:37)
    at EditorGroupView.layout (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:1034:32)
    at LeafNode.layout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/gridview.js:331:30)
    at Object.layout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:113:27)
    at viewItems.forEach.item (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:429:49)
    at Array.forEach (<anonymous>)
    at SplitView.layoutViews (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:429:28)
    at SplitView.relayout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:213:18)
    at SplitView.onViewChange (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:312:22)
    at view.onDidChange.size (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:105:70)
    at e (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:79:135)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:477:38)
    at i (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:52:93)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:477:38)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:480:41)
    at EditorControl.doSetActiveControl (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:104:46)
    at EditorControl.doShowEditorControl (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:59:18)
    at EditorControl.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:45:34)
    at EditorGroupView.doShowEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:575:56)
    at EditorGroupView.doOpenEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:569:25)
    at EditorGroupView.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:535:25)
    at EditorGroupView.doCloseActiveEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:764:22)
    at EditorGroupView.doCloseEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:718:22)
    at handleDir
```

**Comment by roblourens** [comment]
I can get there with 4 groups open at the same time that once contained a settings editor. Doesn't need to be 4 settings editors open at the same time. They are only disposed when the group is closed. That seems like too many enum templates to render a settings editor? I'll look into it some more.

**Comment by roblourens** [comment]
Oh that particular stack was only hit 10 times so it might not be a real problem. Will still look into it because I've seen this randomly before too.

**Comment by jtulk** [comment]
I'm getting a similar issue while trying to figure out some noticeably degraded performance in VSCode. Not sure if this will help.

```
[45e] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ workbench.main.js:76
workbench.main.js:76     at new e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5197:612)
    at c._createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:671)
    at createInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:92)
    at C.renderTemplate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5224:621)
    at renderTemplate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:828:131)
    at renderers.map.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:817:247)
    at Array.map (<anonymous>)
    at H.renderTemplate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:817:238)
    at n.alloc (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:166:34)
    at w.insertItemInDOM (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:417:48)
    at w.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:416:249)
    at w.onScroll (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:421:330)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:1003)
    at _register._scrollable.onScroll.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:395:347)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at r._setState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:211:482)
    at r.setScrollPositionNow (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:210:91)
    at v._onMouseWheel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:399:281)
    at HTMLDivElement._mouseWheelToDispose.push.i.addDisposableListener.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:398:284)
```

**Comment by roblourens** [comment]
Not able to repro and don't rememer randomly seeing this for awhile. Closing for now
