### ISSUE TITLE
Activating extension `vscode.debug-server-ready` failed

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69190]
1. Start debugging. Notice error in console

```
 Activating extension `vscode.debug-server-ready` failed:  Cannot find module '/Users/isidor/Development/vscode/extensions/debug-server-ready/out/extension' (at define._activateExtension.newlyActivatingExtension._host.actualActivateExtension.then (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionActivator.js:247:25))
console.js:100 [Extension Host] Here is the error stack:  Error: Cannot find module '/Users/isidor/Development/vscode/extensions/debug-server-ready/out/extension'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.Module._load (/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:20:33)
	at Function.load (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHost.api.impl.js:795:33)
	at Function.load [as _load] (/Users/isidor/Development/vscode/out/vs/workbench/services/extensions/node/proxyResolver.js:257:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.nodeRequire [as __$__nodeRequire] (/Users/isidor/Development/vscode/out/vs/loader.js:1708:32)
	at loadCommonJSModule (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:610:25)
	at ExtHostExtensionService._doActivateExtension (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:310:17)
	at ExtHostExtensionService._activateExtension (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:268:25)
	at ExtHostExtensionService.<anonymous> (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:135:33)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:10:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:6:12)
	at Object.actualActivateExtension (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:128:67)
	at ExtensionsActivator._activateExtension (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionActivator.js:245:57)
	at define._activateExtensions.Promise.all.green.map (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionActivator.js:230:58)
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionActivator.js:230:42)
	at ExtensionsActivator.activateByEvent (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionActivator.js:137:25)
	at ExtHostExtensionService._activateByEvent (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:189:36)
	at define.$activateByEvent._readyToRunExtensions.wait.then._ (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionService.js:553:33) (at define._activateExtension.newlyActivatingExtension._host.actualActivateExtension.then (/Users/isidor/Development/vscode/out/vs/workbench/api/node/extHostExtensionActivator.js:248:25))

**Comment by weinand** [comment]
Are you running out of source or what build are you using?

**Comment by weinand** [comment]
I cannot reproduce this when running out of source.
Did you do a "yarn" after pulling?

**Comment by isidorn** [comment]
My mistake. Sorry.
Can not repro after doing yarn
