### ISSUE TITLE
IPreferencesService should use SyncDescriptor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69226]
It looks like `IPreferencesService` in `workbench.ts` is directly instantiated instead of using a `SyncDescriptor`.  I see no reason why this is done as such and would like to change it. However, adding this line:

```ts
serviceCollection.set(IPreferencesService, new SyncDescriptor(PreferencesService));
```

Triggers an avalanche of exceptions that I cannot really explain:

```
ERR illegalState - creating UNKNOWN service instance: Error: illegalState - creating UNKNOWN service instance
    at InstantiationService._createServiceInstanceWithOwner (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:171:23)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:156:43)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:106:29)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:62:36)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:52:31)
    at ActionBarRegistry.createActionBarContributor (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/actions.js:185:56)
    at ActionBarRegistry.setInstantiationService (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/actions.js:181:22)
    at Workbench.initServices (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:369:68)
    at Workbench.doStartup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:129:18)
    at Workbench.startup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:97:22)
    at dom_1.domContentLoaded.then (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/main.js:60:36)
/Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:202 [uncaught exception]: Error: illegalState - creating UNKNOWN service instance
onUnexpectedError @ /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:202
callbackResult.then.error @ /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:129
Promise.then (async)
result @ /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:124
Module._invokeFactory @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:993
Module.complete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1003
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1603
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._resolve @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1565
ModuleManager.defineModule @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1229
load @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1500
(anonymous) @ css.js:103
BrowserCSSLoader._onLoad @ css.js:45
callback @ css.js:68
loadEventListener @ css.js:34
load (async)
BrowserCSSLoader.attachListeners @ css.js:40
BrowserCSSLoader.createLinkTag @ css.js:70
BrowserCSSLoader.load @ css.js:90
CSSPlugin.load @ css.js:102
ModuleManager._loadPluginDependency @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1505
ModuleManager._resolve @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1549
ModuleManager.defineModule @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1229
ModuleManager._onLoad @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1306
(anonymous) @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1476
OnlyOnceScriptLoader.triggerCallback @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:594
(anonymous) @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:588
NodeScriptLoader._loadAndEvalScript @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:814
(anonymous) @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:780
readFileAfterClose @ fs.js:440
/Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:205 Error: illegalState - creating UNKNOWN service instance
    at InstantiationService._createServiceInstanceWithOwner (instantiationService.js:171)
    at InstantiationService._createAndCacheServiceInstance (instantiationService.js:156)
    at InstantiationService._getOrCreateServiceInstance (instantiationService.js:106)
    at InstantiationService._createInstance (instantiationService.js:62)
    at InstantiationService.createInstance (instantiationService.js:52)
    at ActionBarRegistry.createActionBarContributor (actions.js:185)
    at ActionBarRegistry.setInstantiationService (actions.js:181)
    at Workbench.initServices (workbench.js:369)
    at Workbench.doStartup (workbench.js:129)
    at Workbench.startup (workbench.js:97)
    at dom_1.domContentLoaded.then (main.js:60)
onUnexpectedError @ /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:205
callbackResult.then.error @ /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:129
Promise.then (async)
result @ /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:124
Module._invokeFactory @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:993
Module.complete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1003
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1603
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1615
ModuleManager._resolve @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1565
ModuleManager.defineModule @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1229
load @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1500
(anonymous) @ css.js:103
BrowserCSSLoader._onLoad @ css.js:45
callback @ css.js:68
loadEventListener @ css.js:34
load (async)
BrowserCSSLoader.attachListeners @ css.js:40
BrowserCSSLoader.createLinkTag @ css.js:70
BrowserCSSLoader.load @ css.js:90
CSSPlugin.load @ css.js:102
ModuleManager._loadPluginDependency @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1505
ModuleManager._resolve @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1549
ModuleManager.defineModule @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1229
ModuleManager._onLoad @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1306
(anonymous) @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:1476
OnlyOnceScriptLoader.triggerCallback @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:594
(anonymous) @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:588
NodeScriptLoader._loadAndEvalScript @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:814
(anonymous) @ /Users/bpasero/Development/Microsoft/monaco/out/vs/loader.js:780
readFileAfterClose @ fs.js:440
extensionHost.js:242 [Extension Host] debugger listening on port 5870
extensionHost.js:150 [Extension Host] debugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/0a093576-f31b-4e05-bfba-f3896e512983
log.js:139   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at ConfigurationManager.setCompoundSchemaValues (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.js:267:47)
    at ExtensionPoint.debugSchemas_1.debuggersExtPoint.setHandler [as _handler] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.js:232:22)
    at ExtensionPoint._handle (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/extensionsRegistry.js:86:22)
    at ExtensionPoint.setHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/extensionsRegistry.js:74:18)
    at ConfigurationManager.registerListeners (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.js:180:46)
    at new ConfigurationManager (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.js:39:18)
    at create (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/types.js:161:20)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:81:35)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:52:31)
    at new DebugService (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/debug/electron-browser/debugService.js:65:67)
    at create (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/types.js:161:20)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:81:35)
    at InstantiationService._createServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:175:25)
    at InstantiationService._createServiceInstanceWithOwner (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:165:29)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:156:43)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:106:29)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:62:36)
    at InstantiationService.createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:52:31)
    at ExtensionHostProcessManager._createExtensionHostCustomers (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/extensionHostProcessManager.js:146:61)
    at ExtensionHostProcessManager._extensionHostProcessProxy._extensionHostProcessWorker.start.then (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/electron-browser/extensionHostProcessManager.js:43:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

//cc @jrieken

**Comment by bpasero** [comment]
@jrieken adding you, I am lost why this happens, it makes no sense to me why the instantiation fails. It looks like the instantiator is complaining about an unknown service `IFileDialogService` when creating the `ITaskService` from the instantiation of the [`QuickOpenActionContributor`](https://github.com/Microsoft/vscode/blob/dafd1aa/src/vs/workbench/contrib/tasks/browser/quickOpen.ts#L202) through the call to [`Registry.as<IActionBarRegistry>(ActionBarExtensions.Actionbar).setInstantiationService(this.instantiationService)`](https://github.com/Microsoft/vscode/blob/dafd1aa/src/vs/workbench/electron-browser/workbench.ts#L723)

**Comment by jrieken** [comment]
Hm, that error means that we are creating an instance of this service without its id being registered... Anyways, when I use the sync descriptor for the preferences service, I don't see this error...

**Comment by jrieken** [comment]
I have pushed the change and I am optimistically closing this

**Comment by bpasero** [comment]
Yeah weird, seems to work fine now. Not sure what changed, will report back when I see it again.
