### ISSUE TITLE
Error launching vscode on windows with network path (lstat)

### ISSUE THREAD

**Issue by artbycrunk** [Microsoft/vscode#69355]
- VSCode Version: 1.31.1
- OS Version: Windows 7

Steps to Reproduce:

1. Copy vscode windows .zip to a network location \\kratos\apps\VSCode-win-x64-1.31.1
2. Map that network location to a drive letter for example Z:\
3. Run vscode via the bin\code.cmd

```
Z:\VSCode-win-x64-1.31.1\bin>code.cmd
fs.js:143
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, lstat 'Z:\'
    at Object.realpathSync (fs.js:1702:5)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at toRealPath (internal/modules/cjs/loader.js:210:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:276:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:599:25)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
````
It works fine with older versions like 1.29.1

Any ideas what could be causing this, and where in the source one could start looking for answers?

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by artbycrunk** [comment]
@jrieken would this have something to do with the update to electron in this version of vscode?

**Comment by bpasero** [comment]
Yeah this sounds like an issue with node.js.

We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)
