### ISSUE TITLE
onDidChangeBodyVisibiliy fires 3 times on startup

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69374]
1. Put a breakpoint here https://github.com/Microsoft/vscode/blob/d1b1529f7b9ff69cde9ce5592000d74d2973afbb/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L204
2. Reload workbench (with having explroer open)
3. Notice that the brekapoint is hit 3 times. First for visible: true, than with false and then with true again

I would expect that only 1 onDidChangeBodyVisibility is fired on startup

**Comment by bpasero** [comment]
It seems to me the event is right given that the view gets visible, hidden and then visible again:

```
visible changed to  true Error
    at ExplorerView.setVisible (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/panelViewlet.js:39:61)
    at ExplorerViewlet.onDidAddViews (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:146:23)
    at ExplorerViewlet.create (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:46:22)
    at ExplorerViewlet.create (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/files/browser/explorerViewlet.js:123:19)
    at SidebarPart.showComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:120:27)
    at SidebarPart.doOpenComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:69:18)
    at SidebarPart.openComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:42:25)
    at SidebarPart.doOpenViewlet (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:159:25)
    at SidebarPart.openViewlet (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:125:45)
    at Workbench.restoreParts (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:467:55)
    at Workbench.doStartup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:148:25)
    at Workbench.startup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:97:22)
    at dom_1.domContentLoaded.then (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/main.js:60:36)
panelViewlet.js:39 visible changed to  false Error
    at ExplorerView.setVisible (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/panelViewlet.js:39:61)
    at ExplorerViewlet.onDidAddViews (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:162:23)
    at ExplorerViewlet.create (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:46:22)
    at ExplorerViewlet.create (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/files/browser/explorerViewlet.js:123:19)
    at SidebarPart.showComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:120:27)
    at SidebarPart.doOpenComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:69:18)
    at SidebarPart.openComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:42:25)
    at SidebarPart.doOpenViewlet (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:159:25)
    at SidebarPart.openViewlet (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:125:45)
    at Workbench.restoreParts (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:467:55)
    at Workbench.doStartup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:148:25)
    at Workbench.startup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:97:22)
    at dom_1.domContentLoaded.then (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/main.js:60:36)
panelViewlet.js:39 visible changed to  true Error
    at ExplorerView.setVisible (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/panelViewlet.js:39:61)
    at panels.filter.map (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:78:37)
    at Array.map (<anonymous>)
    at ExplorerViewlet.setVisible (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsViewlet.js:78:18)
    at ExplorerViewlet.setVisible (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/files/browser/explorerViewlet.js:171:19)
    at SidebarPart.showComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:177:23)
    at SidebarPart.doOpenComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:69:18)
    at SidebarPart.openComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:42:25)
    at SidebarPart.doOpenViewlet (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:159:25)
    at SidebarPart.openViewlet (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:125:45)
    at Workbench.restoreParts (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:467:55)
    at Workbench.doStartup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:148:25)
    at Workbench.startup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/workbench.js:97:22)
    at dom_1.domContentLoaded.then (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/main.js:60:36)
```

**Comment by isidorn** [comment]
Why all those changes on startup? Why not visible from start?

**Comment by bpasero** [comment]
🤔

**Comment by sandy081** [comment]
@isidorn Good catch
