### ISSUE TITLE
Data tree node not found

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69950]
Any os

1. Take the insiders which is not to become stable
2. Open explorer, have autoReveal: true, open some file which is a bit nested
3. Collapse all in explorer, Refresh in explorer -> notice error in console

So does not repro in our candidate to be shipped. Only happens after your tree refactoring thus I believe that is the cause of this issue. First giving to you @joaomoreno 

```
ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:416:23)
    at WorkbenchAsyncDataTree.<anonymous> (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:325:35)
    at Generator.next (<anonymous>)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:6:12)
    at WorkbenchAsyncDataTree.expand (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:317:20)
    at Array.<anonymous> (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:405:81)
    at next (file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:281:59)
    at thenHandler (file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:287:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Tyriar** [comment]
I'm still reproing this on master with autoReveal: false and running the Reveal Active File in Side Bar command.

**Comment by jrieken** [comment]
Yeah, same here

**Comment by isidorn** [comment]
Can no longer repro with latest out of source following my steps -> adding verified label

**Comment by DanTup** [comment]
I'm seeing an issue on Insiders 0ac111466ec925fd5ca180ab9893f51531e419b2  2019-04-01T15:39:08.133Z that I suspect may still be this. (LMK if you think it's different and I should open a new issue).

I had VS Code open and ran a command that created some files (see output pane), but they never appeared in the explorer. I opened dev tools and had this:

```

t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1408   ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at Y.getDataNode (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:955:302)
    at Y.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:953:631)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:32:460
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:32:237)
    at Y.expand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:953:398)
    at e.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5248:778)
    at Generator.next (<anonymous>)
    at r (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:32:293)
```

![Screenshot 2019-04-02 at 9 11 29 am](https://user-images.githubusercontent.com/1078012/55386526-93025580-5527-11e9-9cbf-e2a3d53f344e.png)

**Comment by isidorn** [comment]
@DanTup yes please create a new issue with reproducable steps. Thanks a lot!

**Comment by DanTup** [comment]
Opened https://github.com/Microsoft/vscode/issues/71588. I don't have good repro steps yet (I can reliably repro it, but not with anything I can share) but I'll see if I can make something.
