### ISSUE TITLE
Changing log level results in exception

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#69990]
Steps:
Command Palette -> Set Log Level -> Choose any option

Output from Log(Window):
```
[2019-03-07 13:41:57.545] [renderer3] [info] no standard startup: not the explorer viewlet
[2019-03-07 13:45:56.204] [renderer3] [error] Call not found: setLevel: {1}
[2019-03-07 13:45:58.726] [renderer3] [trace] telemetry/workbenchActionExecuted {"id":"workbench.output.action.switchBetweenOutputs","from":"panel"}
[2019-03-07 13:46:00.654] [renderer3] [trace] telemetry/workbenchActionExecuted {"id":"workbench.output.action.switchBetweenOutputs","from":"panel"}
[2019-03-07 13:46:01.207] [renderer3] [trace] telemetry/UnhandledError {"msg":"Call not found: setLevel","callstack":"Error: Call not found: setLevel\n    at r.call (/out/vs/code/electron-main/main.js:227:69)\n    at w.onPromise (/out/vs/code/electron-main/main.js:167:322)\n    at w.onRawMessage (/out/vs/code/electron-main/main.js:166:981)\n    at protocolListener.protocol.onMessage.e (/out/vs/code/electron-main/main.js:166:547)\n    at u.fire (/out/vs/code/electron-main/main.js:49:209)\n    at e (/out/vs/code/electron-main/main.js:173:22)\n    at u.fire (/out/vs/code/electron-main/main.js:49:209)\n    at e (/out/vs/code/electron-main/main.js:44:794)\n    at u.fire (/out/vs/code/electron-main/main.js:49:209)\n    at e (/out/vs/code/electron-main/main.js:44:940)\n    at u.fire (/out/vs/code/electron-main/main.js:49:209)\n    at EventEmitter.i (/out/vs/code/electron-main/main.js:46:720)\n    at EventEmitter.emit (events.js:187:15)\n    at WebContents.<anonymous> (<REDACTED: user-file-path> Studio Code - <REDACTED: user-file-path>:285:13)\n    at WebContents.emit (events.js:182:13)","count":1}
```

**Comment by mjbvz** [comment]
Looking over the code, I think the log level is being set properly but then we log a false error
