### ISSUE TITLE
VS Code doesn't terminate a process being run in a terminal when a recent project is opened

### ISSUE THREAD

**Issue by SergTanchenko** [microsoft/vscode#70158]
**Environment:** OS: Windows 8 x64.

**1.** Create 2 projects (First and Second) and open them one by one (it is needed to have these project listed in File -> Open Recent menu).
**2.** Open the First project.
**3.** Open Terminal. Select "cmd" in dropdown.
**4.** Launch a process in terminal that needs to be terminated. In my case I run webpack-dev-server:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
C:\Git_Repository\redux-personal-project>yarn start
yarn run v1.7.0
$ nodemon
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Git_Repository\redux-personal-project\webpack/**/* package.json .babelrc
[nodemon] starting `webpack-dev-server --config=./webpack/webpack.config.babel.js --env development`
i ｢wds｣: Project is running at http://192.168.0.102:3000/
```
**5.** Open a recent project (the Second).
**6.** Open the First project again from Recent projects.
**7.** Repeat steps: 3 and 4.

**Actual Result:** Error in the console: "address already in use 0.0.0.0:3000" : 
```
C:\Git_Repository\redux-personal-project>yarn start
yarn run v1.7.0
$ nodemon
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Git_Repository\redux-personal-project\webpack/**/* package.json .babelrc
[nodemon] starting `webpack-dev-server --config=./webpack/webpack.config.babel.js --env development`
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1290:14)
    at listenInCluster (net.js:1338:12)
    at doListen (net.js:1471:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1317:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Expected result:** When I open another project and have the running process in the current one I expect to see popup with the warning: "The current project has a running process if you press 'Yes' the process will be terminated" or something similar.

**Comment by Tyriar** [comment]
I believe this is related to certain node server software not properly cleaning up.
