### ISSUE TITLE
debugger timeout when send break-point request

### ISSUE THREAD

**Issue by mccoysc** [microsoft/vscode#70266]
node.exe --inspect-brk=11031 xxTEA.js 
Debugger listening on ws://127.0.0.1:11031/69841ef3-6704-45c5-902a-f16296458837
For help, see: https://nodejs.org/en/docs/inspector
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:71:24)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

[xxTEA.zip](https://github.com/Microsoft/vscode/files/2954580/xxTEA.zip)

when i try to debug file xxTEA.js which attached  step by step,deubgger hang and timeout.
node version:v11.9.0 x64
OS:window 10 x64 professional

vscode version:
1.32.1 (user setup)
05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Thanks for the report and sorry for the slow response but I need more details. This works ok for me, where are you setting breakpoints? What are the exact steps? You can set `"trace": true` and reproduce the issue, then upload the log from the path printed to the debug console.
