### ISSUE TITLE
Smoketest: Editor tests fail

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#70387]
```
  Running Code
    Editor
      ✓ shows correct quick outline
      ✓ finds 'All References' to 'app'
      ✓ renames local 'app' variable
** Timeout!
Did not pass accept function
      1) verifies that 'Go To Definition' works
** Timeout!
Did not pass accept function
      2) verifies that 'Peek Definition' works


  3 passing (60s)
  2 failing

  1) Running Code
       Editor
         verifies that 'Go To Definition' works:
     Error: Timeout: get element '.monaco-editor .view-overlays>:nth-child(11) .current-line' after 20 seconds.
      at /home/joao/Work/vscode/test/smoke/out/vscode/code.js:142:23                                          
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  2) Running Code
       Editor
         verifies that 'Peek Definition' works:
     Error: Timeout: get element '.monaco-editor .zone-widget .zone-widget-container.peekview-widget.reference-zone-widget.results-loaded' after 20 seconds.
      at /home/joao/Work/vscode/test/smoke/out/vscode/code.js:142:23                                          
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
```

**Comment by jrieken** [comment]
seems to work by now
