### ISSUE TITLE
Debug smoketest is failing

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70423]
I'm getting this error when running against 1.32 release:

```
  4) Running Code
       Debug
         focus stack frames and variables:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .debug-variables .monaco-list-row .expression' after 20 seconds.
      at /Users/octref/Code/work/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
```

Command:

```
yarn smoketest --build ~/Desktop/Visual\ Studio\ Code.app -f "Debug"
```

I manually checked the smoke test. Focusing on each stack frame reveals variables correctly.

**Comment by isidorn** [comment]
I can not reproduce with latest out of source. Can you reproduce if you run it against latest?

![Screenshot 2019-03-14 at 10 18 32](https://user-images.githubusercontent.com/1926584/54345054-8bdfda00-4642-11e9-89f6-76a2070e73ac.png)

**Comment by octref** [comment]
I see a different error now running master smoketest against the 1.32.2 binaries:

```
yarn smoketest --build ~/Desktop/Visual\ Studio\ Code.app -f "Debug"
```

```
*** Smoketest setup done!

  Running Code
    Debug
      ✓ configure launch json
      ✓ breakpoints
      ✓ start debugging
** Timeout!
Error: Element not found: div[id="workbench.view.debug"] .monaco-list-row .stack-frame .file[title*="layer.js"]
    at g.<anonymous> (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbenc
h.main.js:2173:103)
    at Generator.next (<anonymous>)
    at file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:939
    at new Promise (<anonymous>)
    at n (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:716)
    at g._getElementXY (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2173:8)
    at g.<anonymous> (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2173:398)
    at Generator.next (<anonymous>)
    at file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:939
    at new Promise (<anonymous>)
    at n (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:30:716)
    at g._click (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2173:339)
    at g.click (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2172:922)
    at call (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1368:343)
    at b.onPromise (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:307:632)
    at b.onRawMessage (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:307:268)
    at protocolListener.protocol.onMessage.e (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:306:856)
    at d.fire (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:73:416)
    at e (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:313:394)
    at d.fire (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:73:416)
    at EventEmitter.n (file:///Users/pine/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:19)
    at EventEmitter.emit (events.js:182:13)
      1) focus stack frames and variables
** Timeout!
Did not pass accept function
      2) stepOver, stepIn, stepOut
```

And I see the same thing for `yarn smoketest -f "Debug"` against latest source.

**Comment by Tyriar** [comment]
I can reproduce this on master via `yarn smoketest`, it hangs here:

<img width="1281" alt="Screen Shot 2019-03-21 at 11 50 55 AM" src="https://user-images.githubusercontent.com/2193314/54777511-af210100-4bcf-11e9-91fc-650fbe797382.png">

**Comment by isidorn** [comment]
Still works both for me and @weinand 

So to get more details
@Tyriar what error do you get in the console?
@octref @Tyriar if you get the error that the element layer.js is missing. If you start debugging the smoke test repo just like the smoke test do you see the layer.js in the stack frame. If yes inspect it and check if the element matches `div[id="workbench.view.debug"] .monaco-list-row .stack-frame .file[title*="layer.js"]` like it does on my machine

**Comment by Tyriar** [comment]
This is the failure I see:

```
  1) Running Code
       Debug
         focus stack frames and variables:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .debug-variables .monaco-list-row .expression' after 20 seconds.
      at /Users/daimms/dev/Microsoft/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
```

It's fixed if I increment the numbers by 1 in each of the `waitForVariableCount` calls. Is this the expected state [here](https://github.com/Microsoft/vscode/blob/75bf16eb5064ae61c4bf8693a124d2557415b633/test/smoke/src/areas/debug/debug.test.ts#L64)?

<img width="307" alt="Screen Shot 2019-03-22 at 8 43 22 AM" src="https://user-images.githubusercontent.com/2193314/54835103-b521eb00-4c7e-11e9-9c7e-7646788f0d52.png">

Is `[[StableObjectId]]` causing the issue? I'm on node v10.15.3. Please try fix this or comment out the test for March, this failed last month on release day and it's going to fail again.

**Comment by isidorn** [comment]
Thanks for more details. Yes the [[StableObjectId]] on different node versions is causing the issue.
Now that we now what is going on we can of course fix this milestone.
