### ISSUE TITLE
Git smoketests failing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#70420]
On Linux:

```
  5) Running Code
       Git
         reflects working tree changes:
     Error: Timeout: get elements 'div[aria-label="Quick Picker"] .monaco-tree-rows.show-twisties .monaco-tree-row .quick-open-entry .label-name' after 20 seconds.
      at /datadrive/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  6) Running Code
       Git
         stages, commits changes and verifies outgoing change:
     Error: Timeout: get text content 'div[id="workbench.parts.statusbar"] .statusbar-entry a[title$="Synchronize Changes"]' after 20 seconds.
      at /datadrive/vscode/test/smoke/out/vscode/code.js:142:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

```

**Comment by octref** [comment]
5/6 are fixed by https://github.com/Microsoft/vscode/commit/7b8af7a5ab795af04a3c2af7f449de7249639a15, but I guess we don't cherry-pick it to release branch.

**Comment by joaomoreno** [comment]
Yup this was fixed yesterday
