### ISSUE TITLE
Cannot read property 'getLineContent' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7053]
Got this opening settings after maybe suggest was open?

```
shell.js:234 Cannot read property 'getLineContent' of null: TypeError: Cannot read property 'getLineContent' of null
    at new Context (file:////Users/bpasero/Development/monaco/out/vs/editor/contrib/suggest/browser/suggestModel.js:12:36)
    at file:////Users/bpasero/Development/monaco/out/vs/editor/contrib/suggest/browser/suggestModel.js:243:36
    at Object.notifySuccess [as _notify] (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_success_notify.enter (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1127:30)
    at WinJS.Class.define._run (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._completed (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1311:18)
    at Object.notifySuccess [as _notify] (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1440:59)
    at Object.state_success_notify.enter (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1127:30)
    at WinJS.Class.define._run (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._completed (file:////Users/bpasero/Development/monaco/out/vs/base/common/winjs.base.raw.js:1311:18)

```

**Comment by joaomoreno** [comment]
@alexandrudima Can an editor be opened without a model? Seems like that happened here.

**Comment by alexandrudima** [comment]
@joaomoreno yes. `getModel()` can be null
