### ISSUE TITLE
 [vscode.typescript-language-features] provider FAILED for file renaming

### ISSUE THREAD

**Issue by vitalics** [Microsoft/vscode#70559]
Issue Type: <b>Bug</b>

local information:
typescript: 3.3.3

**description**:
after rename file(e.g. js to ts) log for extension host looks like

It seems that it is similar #69767

**log**: 
[2019-03-15 14:57:33.587] [exthost] [error] Error: TypeScript Server Error (3.3.3)
Could not find file: 'd:/<project>/test/functional/services/browser.ts'.
Error: Could not find file: 'd:/<project>/test/functional/services/browser.ts'.
    at getValidSourceFile (tsserver.js:118276:23)
    at Proxy.getApplicableRefactors (tsserver.js:119054:24)
    at IOSession.Session.getApplicableRefactors (tsserver.js:126908:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125781:61)
    at tsserver.js:127127:88
    at IOSession.Session.executeWithRequestId (tsserver.js:127118:28)
    at IOSession.Session.executeCommand (tsserver.js:127127:33)
    at IOSession.Session.onMessage (tsserver.js:127149:35)
    at Interface.<anonymous> (tsserver.js:128410:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (c:\Users\vitali_haradkou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:173419)
	at v.dispatchResponse (c:\Users\vitali_haradkou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:178725)
	at v.dispatchMessage (c:\Users\vitali_haradkou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:177477)
	at constructor._reader.onData.e (c:\Users\vitali_haradkou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:176833)
	at u.fire (c:\Users\vitali_haradkou\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:254)
	at t.Reader.onLengthData (c:\Users\vitali_haradkou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:182693)
	at Socket.t.Reader.constructor.e.on.e (c:\Users\vitali_haradkou\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:182341)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

We picked up a new TS version that may fix this
