### ISSUE TITLE
IntelliSense and autocomplete are broken after a period of time

### ISSUE THREAD

**Issue by Disane87** [Microsoft/vscode#70763]
Versions:
```
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Datum: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17763
```

Steps to Reproduce:

1. Starting VS code
2. Working a time
3. Then IntelliSense (and autocomplete and other stuff) is not working anymore

Does this issue occur when all extensions are disabled?: Yes

Additionally I've reinstalled NPM, Typescript and previous Version of VS Code and the Insider-Build, nothing worked. This problem occuredyesterday the first time.

Are there any logs I can check or other stuff, which can help me to solve this?

**Comment by mjbvz** [comment]
Please provide some example code or steps the reproduce the issue if possible. What isn't working for example?

**Comment by Disane87** [comment]
It‘s very difficult to catch an action, which triggers it, so I can‘t really reproduce it. I only can reproduce it by closing vsc and back starting it again. Then the ts/js lang services are started and I can work i.e. With ts autocompletion or general intellisense (i.e hovering over functions to show the parameters and docs).

It crashes very randomly imho. Not just after five minutes of working. If I restart vsc, it works fine for a period of time. I really can‘t figure out what‘s the cause of this, because it first occured total random. The only thing I did was the latest february update. But even the downgrade and the insiders build crashes

**Comment by mjbvz** [comment]
Ok, you can try collecting the TS Server logs to see if those show anything:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Disane87** [comment]
Thank you @mjbvz! Gonna try this tomorrow at work. 

I can send you the full log, with replacement of sensitive data.

**Comment by IAmStrong** [comment]
Same issue here.

**Comment by Disane87** [comment]
There is an error in the `server.log`:

> Err 17803 [9:58:12.454] Exception on executing command {"seq":716,"type":"request","command":"quickinfo","arguments":{"file":"c:/Projekte/[replaced projectname]/AngularFrontend/ClientApp/src/app/vng-controls/dialog.service.ts","line":65,"offset":28}}:
> 
>     Debug Failure. False expression.
> 
>     Error: Debug Failure. False expression.
>         at Object.computePositionOfLineAndCharacter (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:6449:22)
>         at TextStorage.lineOffsetToPosition (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:120375:31)
>         at ScriptInfo.lineOffsetToPosition (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:120658:41)
>         at IOSession.Session.getPosition (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:125166:81)
>         at IOSession.Session.getQuickInfoWorker (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:125249:96)
>         at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:124301:61)
>         at c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:125836:88
>         at IOSession.Session.executeWithRequestId (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:125827:28)
>         at IOSession.Session.executeCommand (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:125836:33)
>         at IOSession.Session.onMessage (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:125858:35)
>         at Interface.<anonymous> (c:\Projekte\[replaced projectname]\AngularFrontend\ClientApp\node_modules\typescript\lib\tsserver.js:127118:27)
>         at Interface.emit (events.js:182:13)
>         at Interface._onLine (readline.js:290:10)
>         at Interface._normalWrite (readline.js:433:12)
>         at Socket.ondata (readline.js:149:10)
>         at Socket.emit (events.js:182:13)
>         at addChunk (_stream_readable.js:279:12)
>         at readableAddChunk (_stream_readable.js:264:11)
>         at Socket.Readable.push (_stream_readable.js:219:10)
>         at Pipe.onread (net.js:636:20)
> 
> File text of c:/Projekte/[replaced projectname]/AngularFrontend/ClientApp/src/app/vng-controls/dialog.service.ts:
>     import { EventEmitter, Injectable, TemplateRef } from '@angular/core';
>     import { ComponentService } from '@services/component.service';
>     import { NotificationsService, NotificationType } from 'angular2-notifications';
>     import { ModalOptions } from 'ngx-bootstrap';
>     // import { BsModalRef, BsModalService } from 'ngx-bootstrap/modal';
>     import { Button } from './button/button.component';
>     import { BaseDialogComponent } from './dialogs/base/base.component';
>     import { NgbModal, NgbModalRef, NgbModalOptions } from '@ng-bootstrap/ng-bootstrap';
>     
>     @Injectable()
>     export class DialogService {
>     
>         // public dialog$: Observable<boolean> = new Observable<boolean>();
>         private defaultPosition = 'modal-dialog-centered';
>     
>         /**
>          * Alle geöffneten Dialoge
>          *
>          * @private
>          * @type {BsModalRef[]}
>          * @memberOf DialogService
>          */
>         private dialogs: Dialog[] = [];
>     
>         private defaultToastConfig: ToastConfig = {
>             timeOut: 3000,
>             showProgressBar: true,
>             pauseOnHover: true,
>             clickToClose: true
>         };
>     
>         constructor(private notificationService: NotificationsService, private modalService: NgbModal, private componentService: ComponentService) {
>     
>         }
>     
>         showDialog(content: any | string | TemplateRef<any>, config: DialogOptions = {}): Promise<any> {
>     
>             if(!('componentOptions' in config)){
>                 config.componentOptions = {};
>             }
>     
>             if(!('centered' in config)){
>                 config.centered = true;
>             }
>     
>             /** Wenn der Content kein Objekt ist, dann wird er vermutlich der tatsächliche Inhalt sein als String */
>             if (typeof(content) === 'string') {
>                 const componentType = this.componentService.getControls(content)[0];
>     
>                 // debugger;
>                 if (componentType) {
>                     content = componentType.proto;
>                 } else {
>                     config.componentOptions['body'] = content;
>                     content = this.componentService.getControls('BaseDialog')[0].proto;
>                 }
>             }
>     
>     
>             // this.bsModalService.config = config;
>             const modalRef = this.modalService.open(content, config);
>     
>             this.setInstanceValues(config.componentOptions, modalRef.componentInstance);
>             return modalRef.result;
>         }
>     
>         showToast(config: ToastConfig, title?: string, message?: string, type?: string) {
>             this.notificationService.create(title, message, <NotificationType>type, <ToastConfig>config || this.defaultToastConfig);
>         }
>     
>     
>         showDynamicDialog(componentName: string, componentOptions: object) {
>             const dialogParams: any[] = [];
>             dialogParams['componentName'] = componentName;
>             dialogParams['componentParams'] = { options: componentOptions };
>     
>             // this.
>     
>             // this.showDialog({
>             //     component: 'DynamicDialogComponent',
>             //     componentParams: dialogParams,
>             //     showConfirmButton: false
>             // });
>         }
>     
>         setInstanceValues(options: object, modalInstance: any) {
>             if (options && modalInstance) {
>                 Object.keys(options).forEach(option => {
>                     modalInstance[option] = options[option];
>                 });
>             }
>         }
>     }
>     
>     export interface Dialog {
>         modalRef: NgbModalRef;
>         onShow: EventEmitter<any>;
>         onHide: EventEmitter<any>;
>     }
>     
>     /**
>      * Optionen der Toasts
>      */
>     export interface ToastConfig {
>         position?: string;
>         timeOut?: number;
>         showProgressBar?: boolean;
>         pauseOnHover?: boolean;
>         lastOnBottom?: boolean;
>         clickToClose?: boolean;
>         clickIconToClose?: boolean;
>         maxLength?: number;
>         maxStack?: number;
>         preventDuplicates?: boolean;
>         preventLastDuplicates?: boolean;
>         theClass?: string;
>         rtl?: boolean;
>         animate?: string;
>         icons?: string;
>     }
>     
>     export interface DialogContent {
>         content: string | TemplateRef<any> | any;
>     }
>     
>     /**
>      * Optionen für einen Dialogs
>      * gemäß: https://github.com/valor-software/ngx-bootstrap/blob/development/src/modal/modal-options.class.ts
>      * Doku: https://valor-software.com/ngx-bootstrap/#/modals#modal-options
>      * @export
>      * @interface DialogOptions
>      */
>     export interface DialogOptions extends NgbModalOptions {
>         title?: string;
>         content?: string | TemplateRef<any> | any;
>         buttons?: Button[];
>         componentOptions?: object;
>     }
>     
>     /**
>      * Mögliche Dialog-Positionen im Fenster
>      * @export
>      * @interface DialogPositions
>      */
>     export interface DialogPosition {
>         horizontal: 'left' | 'middle' | 'right';
>         vertical: 'top' | 'middle' | 'bottom';
>     }
>     
>     
>     /**
>      * Dialog-Modus (Modal / Toast)
>      *
>      * @export
>      * @enum {number}
>      */
>     export enum DialogMode {
>         modal,
>         toadt
>     }

It seems, that the ts server has some serious problems with my file/code.

**Comment by dschrubba** [comment]
+1

**Comment by mjbvz** [comment]
@Disane87 Are you using an old version of typescript in your workspace by chance? Or does this happen on TS 3.4-rc as well?

**Comment by Disane87** [comment]
It is an angular project with the latest angular package (should be 7.3.6) which needs ts >= 3.2.4. So we have this version in the project and ts 3.3.3333 globally. 

But I‘ve discovered, that I made changes to the tsconfig.json and added a tslint plugin.
We‘ve deleted that and at the moment it works.

This problem occurred on a colleagues machine which runs a visual studio pro. That leads us to the assumption, that something is broken with ts and we found that plugin (which was only für testing purposes). 

But I‘ll report back tomorrow when I‘ve worked some hours with that „fix“, only to be sure, that this is the fix.

**Comment by Disane87** [comment]
@mjbvz it seems, this was not a solution. The tsserver seems to be broken when I open my file `dialog.service.ts` and I really don't know why.
