### ISSUE TITLE
Pylint Broke after Upgrade to 1.32.3

### ISSUE THREAD

**Issue by paulmaia** [Microsoft/vscode#70826]
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Python 2.7.13

PyLint was installed and working perfectly, has been for a couple months.
I noticed a VSCode update was available recently and installed it.
Afterwards, Pylint runs (manually and automatically), but fails in Python, without even getting to the point where it processes any file parameters. Just running Pylint gives this, now:
D:\Projects\PowerShell\Python>c:\Python27\Scripts\pylint.exe
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pylint\__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "c:\python27\lib\site-packages\pylint\lint.py", line 1270, in __init__
    ), option_groups=self.option_groups, pylintrc=self._rcfile)
  File "c:\python27\lib\site-packages\pylint\lint.py", line 466, in __init__
    config_file=pylintrc or config.PYLINTRC)
  File "c:\python27\lib\site-packages\pylint\config.py", line 464, in __init__
    self.reset_parsers(usage, version=version)
  File "c:\python27\lib\site-packages\pylint\config.py", line 478, in reset_parsers
    self.cfgfile_parser = configparser.ConfigParser(inline_comment_prefixes=('#', ';'))
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'

*** This was working fine before the update ***

Google showed others had seen this in the past, from VSCode 'futures'. A lot of noise and not a lot of solutions.

Is there a list of the files that were updated in the Python directory that I can remove to troubleshoot this?

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by paulmaia** [comment]
If you know that it is caused by an extension, can you tell me which one or tell me how I can figure out which one it is, so I can complain to the correct folks?
