### ISSUE TITLE
Got bad scroll event

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#70902]
VSCode out of source
1. Open vscode repo
2. Expand src folder
3. Right click on src -> new file
4. Start scrolling with the mouse, tree gets broken

Can not repro with insiders, so it must be caused by latest changes.

Console has error:
```
  ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at ListView.removeItemFromDOM (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:454:71)
    at ListView.render (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:358:26)
    at ListView.onScroll (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/list/listView.js:521:22)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:480:41)
    at AbstractScrollableElement._register._scrollable.onScroll (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:107:32)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:477:38)
    at Scrollable._setState (file:///Users/isidor/Development/vscode/out/vs/base/common/scrollable.js:209:28)
    at Scrollable.setScrollPositionNow (file:///Users/isidor/Development/vscode/out/vs/base/common/scrollable.js:144:18)
    at ScrollableElement._onMouseWheel (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:265:42)
    at HTMLDivElement.onMouseWheel (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/scrollbar/scrollableElement.js:216:26)
listView.js:527 Got bad scroll event: {width: 0, scrollWidth: 0, scrollLeft: 0, height: 1272, scrollHeight: 2618, …}
onScroll @ listView.js:527
fire @ event.js:480
AbstractScrollableElement._register._scrollable.onScroll @ scrollableElement.js:107
fire @ event.js:477
_setState @ scrollable.js:209
setScrollPositionNow @ scrollable.js:144
_onMouseWheel @ scrollableElement.js:265
onMouseWheel @ scrollableElement.js:216
listView.js:527 Got bad scroll event: 
```

**Comment by joaomoreno** [comment]
1. Resize window in order to have a scroll bar in Explorer
2. Scroll all the way down
3. Rename last file in explorer
4. Scroll up

The explorer attempts to move a file:

![Screenshot from 2019-03-21 15-48-33](https://user-images.githubusercontent.com/22350/54760656-ccb29280-4bf0-11e9-806a-fba6e12312f5.png)

**Comment by isidorn** [comment]
@joaomoreno I can not repro your steps from the previosu comment.
I can repro my original comment which I am now looking into

**Comment by isidorn** [comment]
@joaomoreno the issue here is that I am telling to expand an element which the tree is aware of, but the element is not visible.
I would expect that this does not throw. And I do not think I am doing anything wrong.

So following my exact stpes from the first comment, I tell `tree.expand(item)` where item represents the `src` folder and since the `src` folder is no longer visible tree explodes with 
`Cannot read property 'templateData' of null`
