### ISSUE TITLE
Selfhost Typescript language services do not work

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#71076]
I've tried switching between the workspace Typescript version (3.3.1) and the shipped one (3.4.0-rc), get the same behavior:

![Screenshot from 2019-03-25 14-46-01](https://user-images.githubusercontent.com/22350/54924453-b8320b00-4f0c-11e9-9bed-dfa031f53ab7.png)

```
[Info  - 2:42:02 PM] Using tsserver from: /var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib
[Info  - 2:42:02 PM] Forking TSServer
[Info  - 2:42:02 PM] Started TSServer
[Error  - 2:42:16 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:16 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:16 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:16 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:19 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:19 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:21 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:22 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:23 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:23 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:24 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:24 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:26 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:37 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:37 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:42:37 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Info  - 2:43:19 PM] Killing TS Server
[Info  - 2:43:19 PM] Using tsserver from: /home/joao/Work/vscode/node_modules/typescript/lib
[Info  - 2:43:19 PM] Forking TSServer
[Info  - 2:43:19 PM] Started TSServer
[Error  - 2:43:32 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:43:32 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:43:32 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:43:33 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:43:33 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[Error  - 2:43:33 PM] ReaderError
RangeError: Index out of range
	at Buffer.copy (buffer.js:635:12)
	at l.tryReadContent (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183053)
	at t.Reader.onLengthData (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183619)
	at Socket.t.Reader.constructor.e.on.e (/var/lib/snapd/snap/code-insiders/97/usr/share/code-insiders/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by bpasero** [comment]
I wonder if this is related to some code we pushed because afaik this morning I was coding fine without issues...

**Comment by bpasero** [comment]
Caused by https://github.com/Microsoft/vscode/commit/6d7959a938328efa70b93c392db2093b25b0a4f0
