### ISSUE TITLE
Typing sometime results in cursor not after last character

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#71238]
This happened to me like once a day. I remember it started to show up since 1-2 months ago.

The behavior:

- Typing `foo`
- You expect `foo|`, where `|` is the cursor
- You get `fo|o`, where cursor is not after last character

Unfortunately I don't have a repro and I don't know what's causing it. I'm also not sure if it's caused by Vim mode. But AFAIK Vim mode in insert mode doesn't do anything special, so this might as well be a VS Code  issue.

**Comment by octref** [comment]
Just right after this happens, is there anyway I can get logs or collect info as to what went wrong?

**Comment by alexandrudima** [comment]
I honestly believe this is a vim issue.

We have no logging built-in for edits / selection changes. You would need to build a custom version of VS Code which logs each and every stacktrace of the cursor position getting changed.

I would try to reproduce in dev mode, and log from here https://github.com/Microsoft/vscode/blob/76e18d0915b18b1aa5971272293fb923b5c2040e/src/vs/editor/common/controller/cursorCollection.ts#L111 and check which code path last sets the cursor.

**Comment by terrysahaidak** [comment]
Hi @alexandrudima, I'm not a VIM user and experiencing the same behavior (as well as some of my colleagues).

Could you please provide me some steps which can help us to determine where the issue comes from?

**Comment by alexandrudima** [comment]
@terrysahaidak Have you found any steps which can reproduce the problem? Does this reproduce when typing in any file (i.e. `.txt`) or is it specific to a certain file type. Do you have quick suggestions enabled?

@octref same questions for you.

**Comment by octref** [comment]
This just happened when I'm typing a comment in a TS file, where there aren't any completions (originally I thought it could be timing issues related to slow completions).

@alexandrudima I don't have a repro. Do you want to make a build which would log all required information for you to debug? I can install it and next time it happens send you the logs.

**Comment by alexandrudima** [comment]
@octref I've created a branch `alex/71238` where various things are traced using our log infrastructure. Be careful before sharing this log as it contains every keystroke you do. You can trigger a build of that branch and selfhost using it.

This is the regular renderer log:
```
[2019-04-02 16:14:28.713] [renderer1] [info] KeybindingService: dispatching [Enter]
[2019-04-02 16:14:28.713] [renderer1] [info] CommandService: executing acceptSelectedSuggestionOnEnter
[2019-04-02 16:14:28.723] [renderer1] [info] ----------------------------
textModel: file:///Users/alex/src/working_dir/game-of-life.ts
stack: Error
    at Tracer.finish (file:///Users/alex/src/vscode/out/vs/editor/common/controller/cursorCollection.js:30:27)
    at CursorCollection.setStates (file:///Users/alex/src/vscode/out/vs/editor/common/controller/cursorCollection.js:139:19)
    at Cursor.setStates (file:///Users/alex/src/vscode/out/vs/editor/common/controller/cursor.js:134:27)
    at Cursor._onModelContentChanged (file:///Users/alex/src/vscode/out/vs/editor/common/controller/cursor.js:214:22)
    at Cursor._register._model.onDidChangeRawContent (file:///Users/alex/src/vscode/out/vs/editor/common/controller/cursor.js:76:22)
    at _eventEmitter.slowEvent (file:///Users/alex/src/vscode/out/vs/editor/common/model/textModel.js:210:56)
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:477:38)
    at DidChangeContentEmitter.endDeferredEmit (file:///Users/alex/src/vscode/out/vs/editor/common/model/textModel.js:2372:39)
    at TextModel.pushEditOperations (file:///Users/alex/src/vscode/out/vs/editor/common/model/textModel.js:882:36)
    at SnippetSession.insert (file:///Users/alex/src/vscode/out/vs/editor/contrib/snippet/snippetSession.js:350:38)
    at SnippetController2._doInsert (file:///Users/alex/src/vscode/out/vs/editor/contrib/snippet/snippetController2.js:66:31)
    at SnippetController2.insert (file:///Users/alex/src/vscode/out/vs/editor/contrib/snippet/snippetController2.js:43:22)
    at SuggestController._onDidSelectItem (file:///Users/alex/src/vscode/out/vs/editor/contrib/suggest/suggestController.js:178:71)
    at SuggestController.acceptSelectedSuggestion (file:///Users/alex/src/vscode/out/vs/editor/contrib/suggest/suggestController.js:286:22)
    at EditorControllerCommandImpl.handler [as _callback] (file:///Users/alex/src/vscode/out/vs/editor/contrib/suggest/suggestController.js:393:25)
    at EditorControllerCommandImpl.runEditorCommand (file:///Users/alex/src/vscode/out/vs/editor/browser/editorExtensions.js:74:30)
    at editor.invokeWithinContext (file:///Users/alex/src/vscode/out/vs/editor/browser/editorExtensions.js:93:29)
    at InstantiationService.invokeFunction (file:///Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:37:27)
    at CodeEditorWidget.invokeWithinContext (file:///Users/alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:191:47)
    at EditorControllerCommandImpl.runCommand (file:///Users/alex/src/vscode/out/vs/editor/browser/editorExtensions.js:87:27)
    at handler (file:///Users/alex/src/vscode/out/vs/editor/browser/editorExtensions.js:40:55)
    at InstantiationService.invokeFunction (file:///Users/alex/src/vscode/out/vs/platform/instantiation/common/instantiationService.js:37:27)
    at Proxy._tryExecuteCommand (file:///Users/alex/src/vscode/out/vs/workbench/services/commands/common/commandService.js:72:74)
    at waitFor.then._ (file:///Users/alex/src/vscode/out/vs/workbench/services/commands/common/commandService.js:61:47)
1/1: view state: [9,10 -> 9,24] --->>>window.addEventListener|
1/1: model state: [9,10 -> 9,24] ---->>>window.addEventListener|
```

**Comment by terrysahaidak** [comment]
By the way, I've tried the insider build and it happens with it as well :(

I will try that custom build later this week and share logs.

**Comment by octref** [comment]
@terrysahaidak If you want to run on this build as well, here you go: https://az764295.vo.msecnd.net/insider/efa47d77cfd55cbad68bef54a2d765b73d7beb13/VSCode-darwin-insider.zip

Remember to set `"update.mode": "none"`, and logs are available in `Cmd + Shift + P` -> `Developer: Open Logs Folder` -> the `rendererX.log`s

**Comment by octref** [comment]
I got a log and sent to you on Slack @alexandrudima

**Comment by terrysahaidak** [comment]
@octref do you use prettier?

I've just realized I'm using prettier with both `formatOnSave` and `autosave`, so I think prettier formats just when I'm typing and breaks everything down.

**Comment by octref** [comment]
I do but I don’t have format on save on.

**Comment by mcarpenterjr** [comment]
How consistent is this for everyone? I have a work station that this rarely happens on with no bias towards repository and I have another work station where it's a consistent thing but only for certain repositories. Both for local and network shares. Both instances have `formatOnSave` off

**Comment by octref** [comment]
@mcarpenterjr I still hit it once or twice a day in my faster work machine. In a Macbook Air 13 that's less powerful and there are programs taking most of the resources, it can happy every few minutes.
All my repos are local.

**Comment by octref** [comment]
@alexandrudima This still happens to me every day, especially when the machine is under heavy load.

**Comment by alexandrudima** [comment]
Here is the relevant log from @octref:

<details><summary>Raw output</summary>

```
[2019-04-15 12:01:03.637] [renderer189] [info] CommandService: executing setContext
[2019-04-15 12:01:04.680] [renderer189] [info] KeybindingService: dispatching [KeyN]
[2019-04-15 12:01:04.681] [renderer189] [info] CommandService: executing type
[2019-04-15 12:01:04.720] [renderer189] [info] KeybindingService: dispatching [KeyO]
[2019-04-15 12:01:04.721] [renderer189] [info] CommandService: executing type
[2019-04-15 12:01:04.739] [renderer189] [info] CommandService: executing default:type
[2019-04-15 12:01:04.740] [renderer189] [info] ----------------------------
textModel: file:///Users/octref/Code/mine/v/vetur/server/src/modes/script/transformTemplate.ts
stack: Error
    at r.finish (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1387:460)
    at a.setStates (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:475)
    at a.setSelections (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:180)
    at m._interpretCommandResult (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:347)
    at m._executeEditOperation (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:91)
    at m._type (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1401:106)
    at m.trigger (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1399:828)
    at e.trigger (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1890:934)
    at y.runCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1581:669)
    at handler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1553:205)
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1372:251)
    at Proxy._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3008:470)
    at r.then.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3008:169)
    at process._tickCallback (internal/process/next_tick.js:68:7)
1/1: view state: [51,8 -> 51,8] --->>>      n|
1/1: model state: [51,8 -> 51,8] ---->>>      n|

[2019-04-15 12:01:04.745] [renderer189] [info] ----------------------------
textModel: file:///Users/octref/Code/mine/v/vetur/server/src/modes/script/transformTemplate.ts
stack: Error
    at r.finish (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1387:460)
    at a.setStates (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:475)
    at m.setStates (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1395:690)
    at m.setSelections (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397:745)
    at e.setSelections (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1888:648)
    at h.setSelections (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3185:243)
    at e.$trySetSelections (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3191:266)
    at u._doInvokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3295:202)
    at u._invokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3294:894)
    at u._receiveRequest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3293:547)
    at u._receiveOneMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3292:283)
    at _protocol.onMessage.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3290:565)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:806)
    at a (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:314:769)
    at e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:314:815)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:806)
    at _receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:323:432)
    at _socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:320:722)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:806)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:317:344)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:316:714)
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:664)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
1/1: view state: [51,7 -> 51,7] --->>>      |n
1/1: model state: [51,7 -> 51,7] ---->>>      |n

[2019-04-15 12:01:04.746] [renderer189] [info] CommandService: executing default:type
[2019-04-15 12:01:04.746] [renderer189] [info] ----------------------------
textModel: file:///Users/octref/Code/mine/v/vetur/server/src/modes/script/transformTemplate.ts
stack: Error
    at r.finish (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1387:460)
    at a.setStates (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:475)
    at a.setSelections (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:180)
    at m._interpretCommandResult (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:347)
    at m._executeEditOperation (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:91)
    at m._type (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1401:106)
    at m.trigger (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1399:828)
    at e.trigger (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1890:934)
    at y.runCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1581:669)
    at handler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1553:205)
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1372:251)
    at Proxy._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3008:470)
    at r.then.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3008:169)
    at process._tickCallback (internal/process/next_tick.js:68:7)
1/1: view state: [51,8 -> 51,8] --->>>      o|n
1/1: model state: [51,8 -> 51,8] ---->>>      o|n

[2019-04-15 12:01:04.780] [renderer189] [info] CommandService: executing setContext
[2019-04-15 12:01:04.856] [renderer189] [info] KeybindingService: dispatching [KeyD]
[2019-04-15 12:01:04.858] [renderer189] [info] CommandService: executing type
[2019-04-15 12:01:04.862] [renderer189] [info] CommandService: executing default:type
[2019-04-15 12:01:04.864] [renderer189] [info] ----------------------------
textModel: file:///Users/octref/Code/mine/v/vetur/server/src/modes/script/transformTemplate.ts
stack: Error
    at r.finish (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1387:460)
    at a.setStates (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:475)
    at a.setSelections (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1390:180)
    at m._interpretCommandResult (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:347)
    at m._executeEditOperation (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398:91)
    at m._type (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1401:106)
    at m.trigger (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1399:828)
    at e.trigger (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1890:934)
    at y.runCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1581:669)
    at handler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1553:205)
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1372:251)
    at Proxy._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3008:470)
    at r.then.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3008:169)
    at process._tickCallback (internal/process/next_tick.js:68:7)
1/1: view state: [51,9 -> 51,9] --->>>      od|n
1/1: model state: [51,9 -> 51,9] ---->>>      od|n
```

</details>

And with my explanations:
```
- KeybindingService: dispatching [KeyN]
- CommandService: executing type (this sends a message to the extension host to vim)
- KeybindingService: dispatching [KeyO]
- CommandService: executing type (this sends a message to the extension host to vim)
- CommandService: executing default:type (I think vim invokes default:type with `n`)
- the default:type command modifies the buffer and the selection:
1/1: view state: [51,8 -> 51,8] --->>>      n|
1/1: model state: [51,8 -> 51,8] ---->>>      n|
- [!!BUG!!] a call comes from the extension host to change the selection location (`$trySetSelections`). Somebody (an extension, perhaps vim) is setting `TextEditor.selection` or `TextEditor.selections`:
1/1: view state: [51,7 -> 51,7] --->>>      |n
1/1: model state: [51,7 -> 51,7] ---->>>      |n
- CommandService: executing default:type (I think vim invokes default:type with `o`)
- the default:type command modifies the buffer and the selection:
1/1: view state: [51,8 -> 51,8] --->>>      o|n
1/1: model state: [51,8 -> 51,8] ---->>>      o|n
...
```

**Comment by octref** [comment]
@terrysahaidak If you are not using Vim, are you using format on save?
My guess is there's a long running formatting operation like so:

```js
function foo() {
  |
}
```

And if you type `n`, it should become `n|`, but after the formatting finishes (with the old text), it replaces (or fails to replace) the current text with the old text, with the side effect of resetting cursor position to `  |n` from `  n|`.

**Comment by terrysahaidak** [comment]
Hey there, it's not happening for me for a month or so, don't know if it a fix in some new version or I changed something in my settings/extensions list, but it's good now.

**Comment by rebornix** [comment]
After adding more log I think we find the root cause for the particular case @octref is running into: Editor Config has a document watcher which tries to set selections, when the extension host is being blocked by some heavy lifting work, Editor Config messed up with the current selection.

For everyone who has similar issues but didn't know which extension might modify the selection, you can narrow it down by 

* Disable auto save, which will disable Save Participants when type
* Disable format on save/type, which will disable formatters when save/type

**Comment by alexandrudima** [comment]
@rebornix It's great that you found the root cause! Should we report this to the editorconfig extension?

**Comment by rebornix** [comment]
@alexandrudima thanks, posted there ;)
