### ISSUE TITLE
terminal integration tests: name.charCodeAt is not a function

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#71379]
When running the integration tests and I focus in the test window and I open the dev tools then I get the following failure.

Not sure it has any relevance, just wanted to report:

rejected promise not handled within 1 second: TypeError: name.charCodeAt is not a function
stack trace: TypeError: name.charCodeAt is not a function
    at Object.get (/home/aeschli/workspaces/vscode/out/vs/workbench/services/extensions/node/file:/home/aeschli/workspaces/vscode/src/vs/workbench/services/extensions/node/rpcProtocol.ts:184:31)
    at formatValue (util.js:450:28)
    at formatProperty (util.js:1034:11)
    at formatObject (util.js:774:17)
    at formatValue (util.js:697:18)
    at inspect (util.js:327:10)
    at new AssertionError (internal/assert.js:252:19)
    at innerFail (assert.js:79:9)
    at Function.equal (assert.js:281:5)
    at vscode_1.window.onDidChangeTerminalDimensions (/home/aeschli/workspaces/vscode/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts:702:12)
    at Emitter.fire (/home/aeschli/workspaces/vscode/out/vs/base/common/file:/home/aeschli/workspaces/vscode/src/vs/base/common/event.ts:584:16)
    at define.$acceptTerminalDimensions._getTerminalByIdEventually.then.terminal (/home/aeschli/workspaces/vscode/out/vs/workbench/api/node/file:/home/aeschli/workspaces/vscode/src/vs/workbench/api/node/extHostTerminalService.ts:370:42)

**Comment by aeschli** [comment]
In the window I see the message 'Not enough space to split terminal.'

**Comment by Tyriar** [comment]
This is expected if you make the window smaller, you should pull devtools into its own window to work around this.

Discussion on the notification here https://github.com/Microsoft/vscode/issues/72649
