### ISSUE TITLE
cannot run from source on macOS 10.14.4

### ISSUE THREAD

**Issue by nhooyr** [Microsoft/vscode#71557]
So I cloned, installed node version v10.15.2, then `yarn install`.

`yarn watch` works but `scripts/code.sh` gives:

```
$ ./scripts/code.sh
[14:06:31] Syncronizing built-in extensions...
[14:06:31] You can manage built-in extensions with the --builtin flag
[14:06:31] [marketplace] ms-vscode.node-debug@1.33.3 ✔︎
[14:06:31] [marketplace] ms-vscode.node-debug2@1.33.0 ✔︎
[14:06:31] [marketplace] ms-vscode.references-view@0.0.26 ✔︎
App threw an error during load
Error: Cannot find module './vs/base/common/performance'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/Users/nhooyr/Programming/forks/vscode/.build/electron/Code - OSS.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/nhooyr/Programming/forks/vscode/out/main.js:9:14)
    at Object.<anonymous> (/Users/nhooyr/Programming/forks/vscode/out/main.js:346:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

Any ideas?

macOS 10.14.4

**Comment by mjbvz** [comment]
Still seeing this with the latest master?

**Comment by nhooyr** [comment]
Yes.

```
[18:42:54] Syncronizing built-in extensions...
[18:42:54] You can manage built-in extensions with the --builtin flag
[18:42:54] [marketplace] ms-vscode.node-debug@1.33.3 ✔︎
[18:42:54] [marketplace] ms-vscode.node-debug2@1.33.0 ✔︎
[18:42:54] [marketplace] ms-vscode.references-view@0.0.26 ✔︎
App threw an error during load
Error: Cannot find module './vs/base/common/performance'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/Users/nhooyr/Programming/forks/vscode/.build/electron/Code - OSS.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/nhooyr/Programming/forks/vscode/out/main.js:9:14)
    at Object.<anonymous> (/Users/nhooyr/Programming/forks/vscode/out/main.js:346:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
^C⏎                     
```

**Comment by mjbvz** [comment]
What commit are you on? Just run `git rev-parse HEAD`

**Comment by nhooyr** [comment]
6e66ff6ec2dcfb5ae437941dc054269b6a68173d

**Comment by joaomoreno** [comment]
Have you tried to fully reset?

```
git clean -xfd
yarn watch
./scripts/code.sh
```

**Comment by nhooyr** [comment]
@joaomoreno that worked thanks :)

**Comment by bmdelacruz** [comment]
Deleting the `out` folder was enough to resolve this issue. You'd need to install the dependencies again if you're going to run `git clean -xfd`.
