### ISSUE TITLE
vs code hanging during autocomplete

### ISSUE THREAD

**Issue by mohamedamin90** [Microsoft/vscode#71658]
- VSCode Version: 1.32.3
- OS Version: linux ubunutu 18.04

Steps to Reproduce:

1- I don't know the reason for that just when i tried to autocomplete as usual i found that vscode doesn't work properly - the autocomplete results can't be read - there is images for that (https://www.mediafire.com/view/9wrq87jm5rdg2yk/Screenshot_from_2019-04-03_15-37-17.png/file , https://www.mediafire.com/view/khcp0gxg8ulf262/Screenshot_from_2019-04-03_15-37-23.png/file)

Does this issue occur when all extensions are disabled?: No

**Comment by mohamedamin90** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Add known languages to autocomplete for language-specific settings (#48317)](https://www.github.com/Microsoft/vscode/issues/48317)

this is another issue not mine.

**Comment by jrieken** [comment]
Please provide steps/insights that allow me to reproduce this. Thanks

**Comment by mohamedamin90** [comment]
i can't know dedicated steps for reproduce that at all, iam telling you wha
1- jslint uninstall.
2- install react  packeges.
3- back to code  = the picture attached happened.
 I tried to increase the size allowed for vscode then uninstall vscode and back again i found that the issue still exist

**Comment by rjkz808** [comment]
I've also faced this problem and I've found this information from `Log(Window)` output useful:

```node
[renderer1] [error] Cannot read property 'updateStatus' of undefined: TypeError: Cannot read property 'updateStatus' of undefined
	at Array._onEvent (C:\Users\mrbin\.vscode\extensions\fbosch.battery-indicator-1.0.0\out\src\extension.js:46:32)
	at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:728)
	at define.constructor._extHostDocumentsAndEditors.onDidChangeActiveTextEditor.e (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:305)
	at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at u.$acceptDocumentsAndEditorsDelta (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:522:159)
	at d._doInvokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (d:\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by jrieken** [comment]
> I've found this information from Log(Window) output useful:

Really? It has nothing to with suggestions nor with VS Code it self. It's a problem with this extensions `fbosch.battery-indicator-1.0.0`. So please forward the issue to them. Thanks.

**Comment by rjkz808** [comment]
@jrieken Ok, thank you.

**Comment by mohamedamin90** [comment]
I deleted everything in setting.json to reset vscode again - i'll mention the packages which caused the previous error if it happened again.

**Comment by jrieken** [comment]
Also try with 1.33 which now stable
