### ISSUE TITLE
Unable to write program user data in tmux session

### ISSUE THREAD

**Issue by ruinshe** [Microsoft/vscode#71906]
- VSCode Version: 1.33.0
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. The message is pop up when I try to open code in command line **in a tmux session** by `code --wait` or `code`, it shows that I didn't have permission to read `~/.vscode/Code`, even if I grant `0755` to whole folder recursively. 
2. When I open terminal out of tmux session, it seems everything goes well.

Does this issue occur when all extensions are disabled?
Yes

Besides, when I tried to run `code --disable-extensions --verbose` inside tmux session.

```text
[9643:0408/105817.925945:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
Gtk-Message: 10:58:17.967: GtkDialog mapped without a transient parent. This is discouraged.
[main 2019-04-08T02:58:21.283Z] Error: listen EACCES /run/user/1000/snap.tmux/vscode-8d186350-1.33.0-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1477:5)
    at Promise (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:182:976)
    at new Promise (<anonymous>)
    at Object.t.serve (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:182:913)
    at n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:485:266)
    at T (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:487:559)
    at u.invokeFunction (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:221:103)
    at then (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:489:347)
[main 2019-04-08T02:58:21.286Z] Lifecycle#kill()
```

**Comment by Tyriar** [comment]
This looks like a snap confinement issue, maybe with tmux? @flexiondotorg any thoughts?

**Comment by joaomoreno** [comment]
Interesting, I run Code snap within tmux all the time, can't repro this.

**Comment by ruinshe** [comment]
Did you try the version `1.33.0`?

Besides, I can't reproduce it as well update upgrading the version to `1.33.1`.

**Comment by kneilb** [comment]
I believe this occurs when tmux is run from a snap.

**Comment by WhoAteDaCake** [comment]
Still getting this
code: 1.34.0
When running from tmux (installed via snap)
On ubuntu
