### ISSUE TITLE
Can not run npm in integrated terminal

### ISSUE THREAD

**Issue by deathmood** [Microsoft/vscode#7194]
- VSCode Version: 1.2 insider
- OS Version: windows 10 insiders
- node - 6.2.0
- npm - 3.8.9

Steps to Reproduce:

1. Open integrated terminal
2. type `npm -v` or `npm start` or just `npm`
3. `npm` throws errors

![image](https://cloud.githubusercontent.com/assets/2758540/15786304/972566b6-29c4-11e6-8de8-ad184a75ff4d.png)

BTW -- `node` and packages run normally

**Comment by Tyriar** [comment]
Looks like you're running into https://github.com/npm/npm/issues/12887

**Comment by deathmood** [comment]
@Tyriar -- npm works normally in plain cmd (at least in my case). The problem shows only in integrated terminal.

**Comment by Tyriar** [comment]
@deathmood people in the issue are experiencing a similar situation:

> I have the same issue but only when I execute npm in something other than a regular cmd.exe window. If I use git bash, or cmd.exe from within Intellij the issue occurs.

**Comment by deathmood** [comment]
if it can help -- just checked -- in my case npm runs normally in git bash

**Comment by Coridyn** [comment]
Does anyone know if this is fixed in Windows 10 build 14361 released on June 8?

**Comment by SaltyDH** [comment]
Still happening on 14361 for me

**Comment by gerane** [comment]
If you have code open a 64bit terminal, does this still occur?

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/issues/7095 for some info on running 64 bit terminals.

**Comment by Coridyn** [comment]
In an update on [npm/npm#12887](https://github.com/npm/npm/issues/12887#issuecomment-225241118) some people have found that manually updating the `gauge` package fixes the problem.

@SaltyDH @deathmood can you try updating that package and seeing if it fixes things for you.

**Comment by mauricionr** [comment]
I'm also getting this error with integrated terminal.

```logs

c:\users\mauricio\documents\git\frontend\npm run start
events.js:154
      throw er; // Unhandled 'error' event
      ^
 
Error: This socket is closed.
    at WriteStream.Socket._writeGeneric (net.js:642:19)
    at WriteStream.Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at WriteStream.Writable.write (_stream_writable.js:207:11)
    at WriteStream.Socket.write (net.js:620:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)
 events.js:154
      throw er; // Unhandled 'error' event
      ^
 
Error: This socket is closed.
    at WriteStream.Socket._writeGeneric (net.js:642:19)
    at WriteStream.Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at WriteStream.Writable.write (_stream_writable.js:207:11)
    at WriteStream.Socket.write (net.js:620:40)
    at WriteStream.stream.write (C:\Users\Mauricio Nunes dos R\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Users\Mauricio Nunes dos R\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Users\Mauricio Nunes dos R\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26
)
    at Object.ProgressBar.hide (C:\Users\Mauricio Nunes dos R\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)

```

**Comment by Tyriar** [comment]
Update from the windows console team https://github.com/npm/npm/issues/12887#issuecomment-226011262:

> Hey everybody,
>
> I'm an engineer on the windows console team, and I've been investigating this a little bit on our end. It seems as though yes, resizing the console window (any conhost window, cmd, powershell, bash.exe, etc) could cause that particular exception to get thrown by npm. Turns out it was an exception in the lower levels of conhost itself.
> 
> I'm happy to say that fortunately, this has already been fixed, and should be on it's way out to insiders soontm, however the best I can say is that it should be fixed when the Anniversary Update officially ships.
> 
> Sorry for any troubles this regression may have accidentally caused!

As such, I'm closing this off as it's being fixed in Windows.
