### ISSUE TITLE
code.sh is broken in WSL after commit  "run code wsl in dev "

### ISSUE THREAD

**Issue by fadeevab** [microsoft/vscode#72263]
- VSCode Version: master branch
- OS Version: Windows 10

Steps to Reproduce:

1. ./tests/code.sh

Error:

```bash
wslpath: /home/sashawin/repositories/fadeevab/vscode/scripts/code-cli.bat: Result not representable
'--locate-extension' is not recognized as an internal or external command,
operable program or batch file.
```

How to fix:
```bash
git revert 251a4904304cce4aab914135b02be8b3a79151ca
```

**Comment by fadeevab** [comment]
@aeschli

**Comment by aeschli** [comment]
@fadeevab What is your setup? Is it vscode cloned inside wsl?

**Comment by fadeevab** [comment]
Yes, I just made a git clone into WSL (Ubuntu installed from Marketplace), then I installed nodejs 10.x, yarn, etc., X server is launched in Windows. So I run code.sh as being inside Linux, so I think it's not really expected to see code-cli.bat in the error message...

**Comment by aeschli** [comment]
Sure, will push a fix.

**Comment by aeschli** [comment]
Yes, that's correct.
`wslpath: /home/alros/repos/Microsoft/vscode/scripts/code-cli.bat: Invalid argument` is not pretty, will fix in May.

**Comment by aeschli** [comment]
Yes, that's correctly verified.
The printing of `wslpath: /home/alros/repos/Microsoft/vscode/scripts/code-cli.bat: Invalid argument` is not nice.
Reopen to fix this in May.

**Comment by alexr00** [comment]
After a successful `yarn run compile`:
```
alros@ALROS-1:~/repos/Microsoft/vscode$ ./scripts/code.sh
'\\wsl$\Ubuntu\home\alros\repos\Microsoft\vscode'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
net.js:268
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:268:24)
    at createWritableStdioStream (internal/process/stdio.js:191:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:20:14)
    at console.js:454:19
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at setupGlobalConsole (internal/bootstrap/node.js:407:41)
    at startup (internal/bootstrap/node.js:142:7)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
net.js:268
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:268:24)
    at createWritableStdioStream (internal/process/stdio.js:191:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:20:14)
    at console.js:454:19
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at setupGlobalConsole (internal/bootstrap/node.js:407:41)
    at startup (internal/bootstrap/node.js:142:7)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
net.js:268
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:268:24)
    at createWritableStdioStream (internal/process/stdio.js:191:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:20:14)
    at console.js:454:19
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at setupGlobalConsole (internal/bootstrap/node.js:407:41)
    at startup (internal/bootstrap/node.js:142:7)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
The system cannot find the path specified.
[15:26:26] Using gulpfile ~/repos/Microsoft/vscode/gulpfile.js
[15:26:26] Starting 'electron'...
[15:26:26] Starting clean-electron ...
[15:26:26] Finished clean-electron after 9 ms
[15:26:26] Starting electron ...
[15:26:29] Finished electron after 2394 ms
[15:26:29] Finished 'electron' after 2.42 s
[15:26:30] Syncronizing built-in extensions...
[15:26:30] You can manage built-in extensions with the --builtin flag
[15:26:30] Downloading extension: ms-vscode.node-debug@1.35.3 ...
[15:26:30] Downloading extension: ms-vscode.node-debug2@1.33.0 ...
[15:26:30] Downloading extension: ms-vscode.references-view@0.0.27 ...
[15:26:31] [marketplace] ms-vscode.node-debug ✔︎
[15:26:31] [marketplace] ms-vscode.references-view ✔︎
[15:26:32] [marketplace] ms-vscode.node-debug2 ✔︎
.build/electron/code-oss: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

**Comment by AleksandrHovhannisyan** [comment]
I noticed the original estimate was May. Is there a fix planned for this maybe later in the year? I also ran into this problem. Thanks!

**Comment by AleksandrHovhannisyan** [comment]
I pulled the latest master with c94b270 and am still getting `.build/electron/code-oss: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory` when running `./scripts/code.sh`. I'm using Ubuntu WSL on a 64-bit Windows host.

**Comment by AleksandrHovhannisyan** [comment]
I tried building again with the latest master (including c94b270) but still got the same error: `error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`. I'm using Ubuntu WSL on a 64-bit Windows, if that info makes any difference.

**Comment by aeschli** [comment]
@AleksandrHovhannisyan `
- `error while loading shared libraries:`: That looks like an (unrelated) problem with your [prerequisites](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites)
- errors in terminal.tests: seems to be fixed in master

The problem this issue was about were the error messages that got emmited while the code tries to run Code in Windows through the [Remote WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl).

That said, the Remote WSL extension is the way to go when using VSCode on WSL. Running Code inside WSL is not what we recommend nor actively support.

**Comment by AleksandrHovhannisyan** [comment]
Thanks for the quick response! I actually already have that extension (the one that allows me to invoke vscode, which is installed on Windows 10, from WSL).

Were new commits pushed that fix the terminal.tests errors? I was using the latest master at the time of running that.

Cheers!

**Comment by aeschli** [comment]
Yes, new commits got pushed.
