### ISSUE TITLE
Edit in settings.json throws error when the default value is null

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#72354]
Issue Type: <b>Bug</b>

* Install GitHub Pull Request
* Search for GitHub Pull Request: Remotes
* Click Edit in settings.json
* JSON Settings editor is opened, but nothing happened
* Errors in console 

```
  ERR Cannot read property 'settingsGroups' of undefined: TypeError: Cannot read property 'settingsGroups' of undefined
    at e.createFilterModel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3814:582)
    at e.triggerSearch (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3813:798)
    at e.onSearchInputChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3813:42)
    at _register.searchWidget.onInputDidChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3799:793)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:818)
    at D.w.disposables.push.w.onDidChangeContent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3591:365)
    at _eventEmitter.slowEvent.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1172:40)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:818)
    at z.endDeferredEmit (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1209:888)
    at P.pushEditOperations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1184:487)
    at executeEdits (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1899:219)
    at D.setValue (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3592:142)
    at e._setOptions (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3796:546)
    at setInput.then.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3795:968)
    at process._tickCallback (internal/process/next_tick.js:68:7)
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2849 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancing
scanNext @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2849
2workbench.main.js:1411   ERR Cannot read property 'updatePreference' of null: TypeError: Cannot read property 'updatePreference' of null
    at Q._defaultPreferencesRenderer.e._defaultPreferencesRenderer._defaultPreferencesRenderer.onUpdatePreference (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4097:399)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:838)
    at D._register.editSettingActionRenderer.onUpdateSetting.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3844:722)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:818)
    at O.updateSetting (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3857:767)
    at Object.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3857:682)
    at o.runAction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:94:596)
    at o.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:94:434)
    at x.runAction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2765:58)
    at Object.click (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2764:641)
    at EventEmitter.c (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:308:508)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
```

VS Code version: Code - Insiders 1.34.0-insider (4f212683c16977661ad51f8d13957de9d3280b30, 2019-04-15T14:12:07.955Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_905437|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.5.2
markdown-emoji|bie|0.0.7
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.6.0
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
flow-for-vscode|flo|1.1.1
vscode-pull-request-github-insiders|Git|1.101.0
ocaml|hac|0.6.43
beautify|Hoo|1.4.11
vscode-github-releases-updater|joa|0.16.0
references-plusplus|jri|0.0.5
graphql-for-vscode|kum|1.13.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.12
vscode-azurefunctions|ms-|0.16.0
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6558
azure-account|ms-|0.8.2
cpptools|ms-|0.22.1
Go|ms-|0.9.2
powershell|ms-|1.12.1
remote-containers|ms-|0.21.0
remote-ssh|ms-|0.8.0
remote-ssh-edit|ms-|0.8.0
remote-ssh-explorer|ms-|0.8.0
remote-wsl|ms-|0.10.0
vscode-remote-extensionpack|ms-|0.4.0
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.45
debugger-for-chrome|msj|4.11.3
debugger-for-ios-web|msj|0.1.2
vetur|oct|0.18.1
subtitles-editor|pep|1.0.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.7.0
seti-icons|qin|0.1.3
ruby|reb|0.22.3
smartpaste|reb|0.0.3
toggle|reb|0.0.1
vscode-fuzzsymbols|reb|0.0.1
sass-indented|rob|1.5.1
rust|rus|0.6.1
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.2
vscode-intelli-nav|vsi|0.0.6

(12 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
*Reset to default* stops working after I add the right setting to `settings.json` as well.
