### ISSUE TITLE
Terminal always crash

### ISSUE THREAD

**Issue by lgngnr** [Microsoft/vscode#72532]
Issue Type: <b>Bug</b>

It is a continuosly crash of the terminal, becoma irresponsive and if i try to close freeze the entire VSCode application appear the message to wait or reopen it 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|15.37GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
auto-close-tag|for|0.5.6
vscode-language-babel|mgm|0.0.22
JavaScriptSnippets|nat|0.2.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.7.0
java|red|0.43.0
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1

</details>

**Comment by usernamehw** [comment]
I'm having the same error. Terminal is crushing constantly and takes the entire window with it.

Not sure if this is the error that does the crash or not:
```
[renderer1] [error] Cannot read property 'closeMessage' of undefined: TypeError: Cannot read property 'closeMessage' of undefined
    at Object.leaveCallback [as hoverLeaveCallback] (resources/app/out/vs/workbench/workbench.main.js:2918:598)
    at MouseZone.leaveCallback (resources\app\node_modules.asar\vscode-xterm\lib\Linkifier.js:194:25)
    at MouseZoneManager.clearAll (resources\app\node_modules.asar\vscode-xterm\lib\ui\MouseZoneManager.js:59:39)
    at Terminal.<anonymous> (resources\app\node_modules.asar\vscode-xterm\lib\Terminal.js:428:105)
    at Terminal.EventEmitter.emit (resources\app\node_modules.asar\vscode-xterm\lib\common\EventEmitter.js:70:20)
    at Terminal.emit (resources\app\node_modules.asar\vscode-xterm\lib\public\Terminal.js:47:20)
    at e._getDimension (resources/app/out/vs/workbench/workbench.main.js:3642:248)
    at e._evaluateColsAndRows (resources/app/out/vs/workbench/workbench.main.js:3641:514)
    at e.layout (resources/app/out/vs/workbench/workbench.main.js:3658:482)
    at u.layout (resources/app/out/vs/workbench/workbench.main.js:3500:186)
    at Object.layout (resources/app/out/vs/workbench/workbench.main.js:425:919)
    at viewItems.forEach.e (resources/app/out/vs/workbench/workbench.main.js:433:87)
    at Array.forEach (<anonymous>)
    at p.layoutViews (resources/app/out/vs/workbench/workbench.main.js:433:74)
    at p.layout (resources/app/out/vs/workbench/workbench.main.js:428:544)
    at h.layout (resources/app/out/vs/workbench/workbench.main.js:3499:88)
    at g.layout (resources/app/out/vs/workbench/workbench.main.js:3503:798)
    at e._terminalService.terminalTabs.forEach.t (resources/app/out/vs/workbench/workbench.main.js:5417:261)
    at Array.forEach (<anonymous>)
    at I.layout (resources/app/out/vs/workbench/workbench.main.js:5417:248)
    at I._updateFont (resources/app/out/vs/workbench/workbench.main.js:5423:140)
    at _register.onDidChangeVisibility.e (resources/app/out/vs/workbench/workbench.main.js:5416:862)
    at d.fire (resources/app/out/vs/workbench/workbench.main.js:77:818)
    at I.setVisible (resources/app/out/vs/workbench/workbench.main.js:2466:305)
    at e.showComposite (resources/app/out/vs/workbench/workbench.main.js:4881:484)
    at e.doOpenComposite (resources/app/out/vs/workbench/workbench.main.js:4879:306)
    at e.openComposite (resources/app/out/vs/workbench/workbench.main.js:4878:845)
    at e.openPanel (resources/app/out/vs/workbench/workbench.main.js:5064:561)
    at S.run (resources/app/out/vs/workbench/workbench.main.js:5058:117)
    at o.runAction (resources/app/out/vs/workbench/workbench.main.js:96:596)
    at o.run (resources/app/out/vs/workbench/workbench.main.js:96:434)
    at e.onClick (resources/app/out/vs/workbench/workbench.main.js:849:146)
    at Immediate.options.options.isMenu.i.setImmediate [as _onImmediate] (resources/app/out/vs/workbench/workbench.main.js:848:723)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

VS Code version: Code - Insiders 1.34.0-insider (7d39e805fb66a6eac22f19af8bb90f48da863fd5, 2019-04-19T05:19:16.037Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gombosg** [comment]
Same here.

From dev tools:
```
BufferLine.ts:196 Uncaught TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:342)
    at Buffer._reflow (Buffer.ts:242)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1709)
    at Terminal.resize (Terminal.ts:51)
    at e._resize (terminalInstance.ts:1216)
    at (/usr/share/vscodium/resources/app/out/vs/code/electron-browser/workbench/anonymous function).setTimeout (file:///usr/share/vscodium/resources/app/out/vs/workbench/workbench.main.js:20:603)
BufferLine.copyCellsFrom @ BufferLine.ts:196
Buffer._reflowSmaller @ Buffer.ts:342
Buffer._reflow @ Buffer.ts:242
Buffer.resize @ Buffer.ts:215
BufferSet.resize @ BufferSet.ts:102
Terminal.resize @ Terminal.ts:1709
Terminal.resize @ Terminal.ts:51
_resize @ terminalInstance.ts:1216
(anonymous function).setTimeout @ decorators.ts:85
setTimeout (async)
(anonymous) @ decorators.ts:84
layout @ terminalInstance.ts:1189
layout @ terminalTab.ts:200
layout @ splitview.ts:210
viewItems.forEach.e @ splitview.ts:602
layoutViews @ splitview.ts:602
layout @ splitview.ts:359
layout @ terminalTab.ts:129
layout @ terminalTab.ts:410
e._terminalService.terminalTabs.forEach.t @ terminalPanel.ts:121
layout @ terminalPanel.ts:121
showComposite @ compositePart.ts:295
doOpenComposite @ compositePart.ts:150
openComposite @ compositePart.ts:114
openPanel @ panelPart.ts:225
run @ panel.ts:93
run @ terminalActions.ts:94
t.when.then @ actions.ts:113
Promise.then (async)
triggerAndDisposeAction @ actions.ts:99
(anonymous) @ actions.ts:90
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:64
r.then.i @ commandService.ts:53
Promise.then (async)
executeCommand @ commandService.ts:53
_doDispatch @ abstractKeybindingService.ts:210
_dispatch @ abstractKeybindingService.ts:169
_register.o.addDisposableListener.e @ keybindingService.ts:331

bootstrap-window.js:202 [uncaught exception]: TypeError: Cannot read property 'isWrapped' of undefined
onUnexpectedError @ bootstrap-window.js:202
(anonymous) @ bootstrap-window.js:44
emit @ events.js:182
window.onerror @ /usr/share/vscodium/resources/electron.asar/renderer/init.js:143
n.globals.onerror @ errorTelemetry.ts:77

bootstrap-window.js:205 TypeError: Cannot read property 'isWrapped' of undefined
    at e._sendLineData (terminalInstance.ts:1087)
    at e.dispose (terminalInstance.ts:731)
    at M.run (terminalActions.ts:114)
    at o.runAction (actions.ts:209)
    at o.run (actions.ts:201)
    at m.onClick (actionbar.ts:170)
    at Immediate.options.options.isMenu.i.setImmediate (actionbar.ts:140)
    at runCallback (timers.js:696)
    at tryOnImmediate (timers.js:667)
    at processImmediate (timers.js:649)
```
VSCode is latest stable.
Fedora 29.

**Comment by marcbelmont** [comment]
Same here:
```
bootstrap-window.js:202 [uncaught exception]: TypeError: Cannot read property '_data' of undefined
onUnexpectedError @ bootstrap-window.js:202

bootstrap-window.js:205 TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:342)
    at Buffer._reflow (Buffer.ts:242)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1709)
    at Terminal.resize (Terminal.ts:51)
    at e._resize (terminalInstance.ts:1216)
    at (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/anonymous function).setTimeout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:20:603)
onUnexpectedError @ bootstrap-window.js:205

BufferLine.ts:196 Uncaught TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (BufferLine.ts:196)
    at Buffer._reflowSmaller (Buffer.ts:342)
    at Buffer._reflow (Buffer.ts:242)
    at Buffer.resize (Buffer.ts:215)
    at BufferSet.resize (BufferSet.ts:102)
    at Terminal.resize (Terminal.ts:1709)
    at Terminal.resize (Terminal.ts:51)
    at e._resize (terminalInstance.ts:1216)
    at (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/anonymous function).setTimeout (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:20:603)
```
