### ISSUE TITLE
when I run 

### ISSUE THREAD

**Issue by helinyu** [Microsoft/vscode#72783]
when I run : yarn watch 
always display like the info below , i don't know how to deal with it ,plase help me .

[11:45:15] 'watch' errored after 12 s
[11:45:15] TypeError: fsevents is not a constructor
    at createFSEventsInstance (/Users/felix/typescript_workspace/vscode/vscode/node_modules/chokidar/lib/fsevents-handler.js:28:11)
    at setFSEventsListener (/Users/felix/typescript_workspace/vscode/vscode/node_modules/chokidar/lib/fsevents-handler.js:82:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/Users/felix/typescript_workspace/vscode/vscode/node_modules/chokidar/lib/fsevents-handler.js:252:16)
    at FSWatcher.<anonymous> (/Users/felix/typescript_workspace/vscode/vscode/node_modules/chokidar/lib/fsevents-handler.js:386:25)
    at LOOP (fs.js:1565:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by SupinePandora43** [comment]
why you're created 2 issues?
