### ISSUE TITLE
Markdown Preview not showing

### ISSUE THREAD

**Issue by AbhishekTripathi** [Microsoft/vscode#72873]
I tried searching for duplicates but all I found are already closed. Possibly this is a regression?

- VSCode Version: 1.33.1
- OS Version: Windows 10 V1809 Build 17763.379

Steps to Reproduce:
1. Create a markdown file with `.md` extension.
2. Save it at desktop location.
3. Exit VSCode
4. Open VSCode again and open the file.
5. Try pressing Ctrl + K, V or click the icon on top right to open the Markdown preview window on right side.

Expectation: The preview window should appear.
Observed: There is no preview window. The dev console shows error log which is defined below.

Does this issue occur when all extensions are disabled?: Yes
I tried both with and without extension but the behavior is same. I also tried launching the locked preview which gave a popup on lower right corner with error 
` command 'markdown.showLockedPreviewToSide' not found `

Dev console log
```
console.ts:134 [Extension Host] rejected promise not handled within 1 second: Error: command '_workbench.htmlPreview.postMessage' not found
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] stack trace: Error: command '_workbench.htmlPreview.postMessage' not found
    at Proxy._tryExecuteCommand (file:///D:/dropbox/tools/VSCode/resources/app/out/vs/workbench/workbench.main.js:3027:549)
    at r.then.i (file:///D:/dropbox/tools/VSCode/resources/app/out/vs/workbench/workbench.main.js:3027:430)
    at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
log.ts:173   ERR command '_workbench.htmlPreview.postMessage' not found: Error: command '_workbench.htmlPreview.postMessage' not found
    at Proxy._tryExecuteCommand (file:///D:/dropbox/tools/VSCode/resources/app/out/vs/workbench/workbench.main.js:3027:549)
    at r.then.i (file:///D:/dropbox/tools/VSCode/resources/app/out/vs/workbench/workbench.main.js:3027:430)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by AbhishekTripathi** [comment]
I tried this with **1.34.0-insider** _without any extensions_ and this issue is **not reproducible**.

**Comment by mjbvz** [comment]
Thanks. I'm going to close this as not-reproducable

If you see this again when enabling extensions, please try tracking down which extension causes this and file an issue against them
