### ISSUE TITLE
`Error: end of central directory record signature not found` on Linux Travis tests

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#7293]
I'm seeing Travis failures for `vscode-go` with this error, but only on Linux, not OS/X.  This is seen building the current master branch of https://github.com/Microsoft/vscode-go.  

It looks like a different issue than #2384 though that led to the same error message.

```
$ npm test --silent
### VS Code Extension Test Run ###
Current working directory: /home/travis/gopath/src/github.com/Microsoft/vscode-go
Downloading VS Code into "/home/travis/gopath/src/github.com/Microsoft/vscode-go/.vscode-test" from: https://vscode-update.azurewebsites.net/1.2.0/linux-x64/stable
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: end of central directory record signature not found
    at /home/travis/gopath/src/github.com/Microsoft/vscode-go/node_modules/vscode/node_modules/gulp-vinyl-zip/node_modules/yauzl/index.js:167:14
    at /home/travis/gopath/src/github.com/Microsoft/vscode-go/node_modules/vscode/node_modules/gulp-vinyl-zip/node_modules/yauzl/index.js:475:5
    at Object._onImmediate (/home/travis/gopath/src/github.com/Microsoft/vscode-go/node_modules/vscode/node_modules/gulp-vinyl-zip/node_modules/yauzl/node_modules/fd-slicer/index.js:200:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
The command "npm test --silent" exited with 1.
```

**Comment by alexandrudima** [comment]
`gulp-vinyl-zip`

**Comment by joaomoreno** [comment]
@Tyriar did you change **all** linux builds to produce `tar.xz` files instead of `zip`? We have tools that depend on the fact that they are zip files.

**Comment by Tyriar** [comment]
This should be fixed now, it happened because stable was built using some changes in vscode-distro that I wasn't expecting. I created https://github.com/Microsoft/vscode/issues/7308 to follow this up in the June release so this doesn't happen in the real switch over.
