### ISSUE TITLE
Cannot jump to file from Integrated Terminal

### ISSUE THREAD

**Issue by ccirello** [Microsoft/vscode#7321]
- VSCode Version: 1.2
- OS Version: OS X

Steps to Reproduce:
1. Open the terminal and make a compilation error in your favorite language
2. Click on the file name it won't jump to the chosen file.

```
--> Monitor: Files changed, Building...
go build -v -i
github.com/REDACTED/REDACTED-ms/REDACTED
REDACTED/crumb.go:223: undefined: rpcCall
```

When selecting and clicking on `REDACTED/crumb.go:223` it won't jump to the file.

Check how iTerm2 and ACME addresses this issue.

**Comment by TurkeyMan** [comment]
:+1: Do want!

**Comment by tht13** [comment]
The latest insiders build has a command `workbench.action.terminal.focus` which is both available in the `F1` command palette under "Focus Terminal" and available to attach to a keybinding.

**Comment by ccirello** [comment]
@tht13 what you said does not address the issue.

**Comment by tht13** [comment]
Apologies, I'm not sure why I thought that was relevant

**Comment by Tyriar** [comment]
Doing this will likely be based on xterm.js' linkify addon which is currently not production ready. So this is blocked on https://github.com/sourcelair/xterm.js/issues/27

**Comment by kaiserdan** [comment]
This would especially be handy for js stack traces

`SyntaxError: Unexpected token )
    at Object.exports.compile (/Users/daniel/Code/planuni/node_modules/jade/lib/jade.js:160:8)
    at Object.exports.render (/Users/daniel/Code/planuni/node_modules/jade/lib/jade.js:199:17)
    at View.exports.renderFile [as engine] (/Users/daniel/Code/planuni/node_modules/jade/lib/jade.js:227:13)
    at View.render (/Users/daniel/Code/planuni/node_modules/express/lib/view.js:126:8)
    at tryRender (/Users/daniel/Code/planuni/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/Users/daniel/Code/planuni/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/Users/daniel/Code/planuni/node_modules/express/lib/response.js:960:7)
    at /Users/daniel/Code/planuni/design/pug.js:20:7
    at Layer.handle [as handle_request] (/Users/daniel/Code/planuni/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/daniel/Code/planuni/node_modules/express/lib/router/route.js:131:13)`

**Comment by Tyriar** [comment]
Keeping this open to track as there will be some integration work to do once it's implemented upstream.

**Comment by Tyriar** [comment]
I gave an update to this in https://github.com/Microsoft/vscode/issues/17897#issuecomment-270182060:

> My plan with linkify was to wait until it's worked out upstream either by myself or another contributor and then mold it so it works with VS Code. This may need to be put into xterm.js' core depending on how it performs. Also simply enabling addons will not just let it work as xterm.js is build for the browser, not electron. linkify adds `<a>` tags which will need to be handled specially within VS Code and thus will need tighter integration.
